### ISSUE TITLE
<?= $this->href ?> regarding ce_teaser.html5

### ISSUE THREAD

**Issue by sdfghasdfg** [contao/contao#100]
Error report regarding
/html/contao/vendor/contao/core-bundle/src/Resources/contao/templates/elements/ce_teaser.html5, line 10:

`<p class="more"><a href="<?= $this->href ?>" title="<?= $this->readMore ?>"><?= $this->more ?><span class="invisible"> <?= $this->headline ?></span></a></p>`

href doubles URL-Content just like this:
https://www.world.wld/my_article/articles/my_article.html

URL must written like this:
https://www.world.wld/my_article.html

Used Contao version: Version 4.4.26
Host: Mittwald Medien

**Comment by asaage** [comment]
This has always been like that - keep in mind that this url strips all other articles from that page as it is an article-teaser - not a page-teaser.

https://github.com/contao/core-bundle/issues/1417 describes a different approach and i realy would like to know if this element has any significant usage - i never use it.

**Comment by sdfghasdfg** [comment]
thx to you asaage

Bad news for me. In that case google would index double content because i use short URLs in all other menus.

Need a work around. Anyone knows how to fix it?

**Comment by asaage** [comment]
you could replace:
```<?= $this->href ?>```
with
```<?= \PageModel::findById(\ArticleModel::findById($this->article)->pid)->getFrontendUrl() ?>```

but the headline would still be that of the article not that of the page.

**Comment by sdfghasdfg** [comment]
Wow, thanks a million times to you asaage. This is a great help to avoid double content in google.

Now ce_teaser.html5 works like this example: [https://www.rechtsanwalt-darmstadt.de/gerichtsurteile.html](https://www.rechtsanwalt-darmstadt.de/gerichtsurteile.html)

Template: Tao/Rocksolid

Diff:

`<div class="<?= $this->class ?> ce_text block"<?= $this->cssID ?><?php if ($this->style): ?> style="<?= $this->style ?>"<?php endif; ?>>`
`<?php if ($this->headline): ?>`
`    <h1><?= $this->headline ?></h1>`
`  <?php endif; ?>`

`  <?= $this->text ?>`

`  <p class="more" style="margin: -10px 30px 40px 0; text-align: right;"><a href="<?= \PageModel::findById(\ArticleModel::findById($this->article)->pid)->getFrontendUrl() ?>" class="button -quaternary" title="<?= $this->readMore ?>"><?= $this->more ?><span class="invisible"> <?= $this->headline ?></span></a></p>`

`</div>`
`<hr>`
