### ISSUE TITLE
An error occurred during upgrading Contao

### ISSUE THREAD

**Issue by baymax88** [contao/contao#1011]
**Affected` version(s)**
Contao 4.4 LTS

**Description**  
I've tried to migrate Contao 3.5.2 project to 4.4 LTS version.
I've already updated the database according to other's experience and copied `/templates` and `/files` folders too.
But an error occurred when I try to connect and view front-end display.

```[2019-11-22 10:22:13] request.INFO: Matched route "contao_frontend". {"route":"contao_frontend","route_parameters":{"_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::indexAction","_scope":"frontend","alias":"home-en","_route":"contao_frontend"},"request_uri":"http://contao-dev/home-en.html","method":"GET"} []
[2019-11-22 10:22:13] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2019-11-22 10:22:13] app.CRITICAL: An exception occurred. {"exception":"[object] (Exception(code: 0): Could not find template \"gallery_grid_34\" at C:\\xampp\\htdocs\\contao-dev\\vendor\\contao\\core-bundle\\src\\Resources\\contao\\library\\Contao\\TemplateLoader.php:153)"} []
```
I can't find `gallery_grid_34` template anywhere.
**How to reproduce**

**Comment by fritzmg** [comment]
You should use the community forum for this kind of question.

> I can't find `gallery_grid_34` template anywhere.

That's the problem ;). Use the [debug mode](https://docs.contao.org/manual/en/system/debug-mode/) to get the full stack trace, so you can find out where this template is requested.

**Comment by baymax88** [comment]
Thanks for your help.
But I can't use debug mode for my current version.
Please let me know how I can use that.

**Comment by fritzmg** [comment]
> Please let me know how I can use that.

This functionality of the Contao Manager is only available for newer Contao versions. For Contao 4.4, you need to enable the debug mode via the command line. See https://docs.contao.org/manual/en/system/debug-mode/#contao-4-4 » https://docs.contao.org/manual/en/system/debug-mode/#command-line

**Comment by baymax88** [comment]
Thanks 👍
