### ISSUE TITLE
Caching completely broken with Symfony 4.4

### ISSUE THREAD

**Issue by Toflar** [contao/contao#1028]
**Affected version(s)**

4.8 (if we allow Symfony 4.4) and master

**Description**

There have been changes again in Symfony, more specifically in this PR: https://github.com/symfony/symfony/pull/33663
These basically cause the `AbstractSessionListener` to always turn all the responses to `private` because at least our 2FA implementation always accesses `getToken()` and is thus invoking the new token tracking.

I also noticed that our `MakeResponsePrivateListener` turns all the responses private when working with HttpCache and any of the requests started the session. For Varnish etc. it would of course work but we need some session stack there as well or we have to rely on the `AbstractSessionListener` of Symfony which already does that (just not the way we need it right now).

The thing is: I have absolutely no clue if and how we can fix this. But I'm leaving the issue here so people know that things are broken if they try out master or adjust their dependencies etc.

**How to reproduce**  

Allow SF 4.4 and enable page caching.

**Comment by wadjeroudi** [comment]
Did you try to switch anonymous firewall to lazy like [suggested](https://github.com/symfony/symfony/pull/33663#issuecomment-559182047) ?

**Comment by Toflar** [comment]
Yes that won't help and is completely unrelated. It doesn't matter whether the firewall is lazy or not. It's related to the fact that `getToken()` just turns any response private now.

**Comment by Toflar** [comment]
See https://github.com/contao/contao/pull/1033.
