### ISSUE TITLE
C48 - Updating contao-components/chosen (1.2.2 => 1.2.3)

### ISSUE THREAD

**Issue by bizon1** [contao/contao#1029]
A todays composer update:
With some other packages i've got
- Updating contao-components/chosen (1.2.2 => 1.2.3): Downloading (100%)

This effected to most of the select-fields in backend. No Options can be chosen anymore, the select-field just disappears.

A conflict entry in composer.json solved the problem:
`"conflict": {
    "contao-components/chosen": "1.2.3"
},`

**Comment by cliffparnitzky** [comment]
Cannot confirm ... no problemes in my installation

**Comment by bizon1** [comment]
I tested it in 3 different C48 installations all with the same result. 
For example the select-field element type in content elements is affected and also in page layout select fields "Eingebundene Module".
And as I wrote - in each installation.

**Comment by leofeyer** [comment]
@bizon1 Which browser and OS are you using? Try purging the browser cache or try opening the websites in a different browser.

**Comment by bizon1** [comment]
OS: Manjaro Linux (Arch)
Browsers and every other Software with latest version:
Pale Moon: Here is the biggest issue - the select fields disappear completly - no options available
Firefox: little issue - the select field disappears half but is readable - options are available
Chromium: works fine
Opera: works fine
Seems that this just effects the gecko browsers.

**Comment by cliffparnitzky** [comment]
I tested on Windows 7 PRO:

- Chrome 78.0.3904.108: no problems
- Firefox 70.0.1: top border disappears after the selection has been changed

**Comment by leofeyer** [comment]
I have tested this on macOS 10.15:

* Chrome 78: no problems
* Safari 13: no problems
* Firefox 71: the same problem as reported by @cliffparnitzky (why, Firefox? 🤦‍♂)

@fritzmg Could you test this on Windows for us please?

**Comment by cliffparnitzky** [comment]
I tested on Window 7 (updated my comment).

**Comment by fritzmg** [comment]
> * Firefox 71: the same problem as reported by @cliffparnitzky (why, Firefox? 🤦‍♂)

Yeah, I can confirm that weird behaviour. Windows 10 and FireFox 70.0.1 as well as 71.0.

**Comment by leofeyer** [comment]
Any problems with the other browsers on Windows?

**Comment by cliffparnitzky** [comment]
I can confirm the behaviour @bizon1 described with Windows 7 and IE 11 as well with Windows 10 and IE 11 and Edge.

**Comment by leofeyer** [comment]
I am going to revert the changes and we will not use Chosen in the meta wizard in Contao 4.9 anymore (see #1058).

**Comment by leofeyer** [comment]
Reverted in contao-components/chosen@7f03cea8db23d0a3990fde33d58ab66ef649c302 (aka version 1.2.4).
