### ISSUE TITLE
Force browser to not store cache for logout page

### ISSUE THREAD

**Issue by sebj54** [contao/contao#1032]
**Affected version(s)**

4.4.41 (and superior?)

**Description**  

With a logout cache, `Cache-Control` header is set to `private` by default.

If we refer to the documentation on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Cacheability), this does not prevent browser from caching the page.

> Indicates that the response is intended for a single user and must not be stored by a shared cache. A private cache may store the response.

If a user disconnects, reconnects and tries to disconnect again (it happens, trust me!), Chrome caches the page (it seems that Firefox doesn't). So the redirection is made correctly but user is not disconnected.

**How to reproduce**  

 - Connect
 - Disconnect
 - Re-connect
 - Try to disconnect again

You may not be able to reproduce because I didn't experience this behaviour on my staging server. Anyway, this `private` value does not seem like a way to avoid caching for this kind of page.

**How to solve**

I solved this bug by adding headers to the `RedirectResponse` constructor called in [PageLogout.php](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/pages/PageLogout.php):

```php
return new RedirectResponse($strRedirect, 302, [
    'Cache-Control' => 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
]);
```

**Comment by leofeyer** [comment]
As discussed in Mumble on November 28th, we want to <del>add the `'Cache-Control' => 'no-store'` header</del> use a `307` redirect, which should not be cached by the browser.


@sebj54 Can you please test if this fixes your problem?

**Comment by sebj54** [comment]
Hi @leofeyer, it works for me!

**Comment by leofeyer** [comment]
See #1041
