### ISSUE TITLE
Multi domain: root pages in individual navigation

### ISSUE THREAD

**Issue by bit7ms** [contao/contao#1038]
We have a multi domain contao project. to give the visitors a better overview of the group of companies and domains, we decided to display a meta navigation with the single web projects to the user.
We tried to use the classical individual navigation. I was wondering why I can't choose a root pages. If I do, it won't be displayed in FE.
The behavior should be like internal or external links. The Name (and css classes) should appear in the FE. A click on the navigation point should redirect to the "main page", with is shown, when the domain is loaded.

Would be great to have that feature. Thx!

**Comment by leofeyer** [comment]
How did you set up the meta navigation?

**Comment by bit7ms** [comment]
I set up a frontend- module with a modul typ "individual navigation" and selected the root pages of the different web sites. I didn't make any template changes.

**Comment by fritzmg** [comment]
» https://github.com/contao/contao/issues/72#issuecomment-559927374

**Comment by bit7ms** [comment]
Okay, I tried to recreate the constellation in the Contao demo. Here the root nodes are displayed.
Sorry. So this is a bug in my installation. I close this issue.

**Comment by fritzmg** [comment]
> Okay, I tried to recreate the constellation in the Contao demo. Here the root nodes are displayed.
> Sorry. So this is a bug in my installation. I close this issue.

It's not a bug in your installation. The Contao Demo uses

```yml
contao:
  prepend_locale: true
```

In this case selecting root nodes in the individual navigation works. See the linked PR on why this has been disabled when this option is not enabled (and only one domain is present). As I said in my comment, imho this change should be reverted, since I consider the use case a misconfiguration of Contao.

**Comment by bit7ms** [comment]
you're right!

**Comment by fritzmg** [comment]
See https://github.com/contao/contao/pull/1202
