### ISSUE TITLE
Contao 4.8.5 Newsletter Reader - Chanel checkbox missed

### ISSUE THREAD

**Issue by Cleanerrr** [contao/contao#1044]
**Contao 4.8.5**
![newsletter-reader-bug](https://user-images.githubusercontent.com/30474317/70064190-64260d00-15e9-11ea-8ce1-9c997a04a6fc.JPG)

**Comment by fritzmg** [comment]
Did you create Channels?

**Comment by Cleanerrr** [comment]
Yes, of course.
Checkbox missed only in last Contao 4.8.5.

**Comment by leofeyer** [comment]
Did you set a redirect page in the channel settings? Otherwise the channel cannot be used in the newsletter reader.

**Comment by Cleanerrr** [comment]
> Did you set a redirect page in the channel settings? Otherwise the channel cannot be used in the newsletter reader.

Ohh, I forgot.
Now it's OK.
Maybe should these "fields" mark as mandatory. 
Thank you very much

**Comment by asaage** [comment]
related to https://github.com/contao/contao/issues/494
