### ISSUE TITLE
Update 4.4 to 4.8, editor only works after a hard reload

### ISSUE THREAD

**Issue by tpk109** [contao/contao#1059]
**Affected version(s)**
4.8

**Description**  
After updating from 4.4 to 4.8 the editor in text element did not appear. There was a js error which I think contained something with theme(s).
After a hard reload in Chrome the editor works again.

**How to reproduce**

**Comment by fritzmg** [comment]
You should post the error ;)

**Comment by tpk109** [comment]
I would if I could. I was expecting something serious and did not expect the reload to help ;-) Could be that it said line 12

Edit: Should'nt the error be moot? This looks like the backend does not force a refresh of (all) js files after an update.

**Comment by aschempp** [comment]
I would assume that was just a cache issue in your browser, as the editor files might have changed from Contao 4.4 to 4.8. Not much we can do about that…
