### ISSUE TITLE
Overridden default template not shown in template selection

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#1060]
**Affected version(s)**
Contao 4.8.5

**Description**  
Currently the default template is not shown in the custom template selection, e.g. for a content element. However, this also includes default templates, that have been overriden in the `templates/` folder.

![ce_text](https://user-images.githubusercontent.com/4970961/70218403-3d7be980-1743-11ea-85b3-cdee8f5b34d2.png)

![Screenshot_2019-12-05 Templates c48 local(1)](https://user-images.githubusercontent.com/4970961/70220164-66ea4480-1746-11ea-943e-8526d3ec5909.png)

This is confusing, since now you cannot see, that your overridden default template is actually used - _and from which theme_ (wherever applicable).

**How to reproduce**  

1. Log into the back end.
2. Go to _Templates_.
3. Create a new `ce_text` template and rename it to `ce_text_foo`.
4. Create a new default `ce_text` template.
5. Go to _Articles_ and create a new _Text_ content element.

The custom template selection will not show the custom default template.

**Comment by tpk109** [comment]
Can you check in the frondend which template will actually be used, if you choose no template? It seems to to me that ce_text_foo is the new default for every new created text element. 
Texts created before creating the template should use ce_text in the frontend.

**How to reproduce**
Exactly the steps from fritzmg, but ce_text_foo needs to be different from ce_text to tell the difference.

**Comment by fritzmg** [comment]
> Can you check in the frondend which template will actually be used, if you choose no template?

Yes `templates/ce_text.html5` will be used.

**Comment by tpk109** [comment]
In my case ce_text_foo is the default.

**Comment by leofeyer** [comment]
> Yes `templates/ce_text.html5` will be used.

This is the intended behavior. The "custom template" drop-down menu does not show the default template, because you cannot not use it.

```
ce_text.html5
ce_text.html5 (global)
```

If we would show these options, people would assume they could select `ce_text.html5` to use the default template. However, if they were actually able to select it, Contao would still use the `ce_text.html5 (global)` template.

**Comment by fritzmg** [comment]
Well the suggestion was not to show both

```
ce_text.html5
ce_text.html5 (global)
``` 

but only

```
ce_text.html5 (global)
```

to signify that Contao's default template is in fact not in use. That would be the previous behavior (minus the inapplicable templates).

**Comment by leofeyer** [comment]
No, that would be wrong. It implies that you can use the default template by selecting the empty option, which you cannot.

**Comment by fritzmg** [comment]
I know, it's not perfect. Just mentioning this break from previous versions and that it's confusing some users on the forum and slack.

**Comment by contaoacademy** [comment]
Perhaps the name of the default template could be listed in a label or note. This would be very helpful for usability to know which template to create to overwrite.
![ce-text](https://user-images.githubusercontent.com/23719181/74349528-a96a7600-4db4-11ea-9a81-07c6437d402c.jpg)

**Comment by leofeyer** [comment]
Agreed

**Comment by fritzmg** [comment]
Btw. why not simply restore the old behaviour (i.e. showing `ce_text` or `ce_text (global)`) and remove `includeBlankOption`? This way it's clear that the only option, that is shown, is the default template - or the overridden template within `templates/`, if applicable.

Then it would also be consistent with the "element" template select:

![Screenshot_2020-02-13 Themes › Default › Front end modules › Edit module ID 1 c49 local(1)](https://user-images.githubusercontent.com/4970961/74418855-f6942980-4e40-11ea-8f74-0ede0c8e460e.png)

**Comment by leofeyer** [comment]
> why not simply restore the old behaviour (i.e. showing `ce_text`

Because then the database entry will be `ce_text` instead of a blank string.

But we can adjust the drop-down menu to show the default template name instead of the dash for the blank option: `<option value="">ce_text</option>`

Then the UX would be the same as before and the database entry would still be blank.

**Comment by fritzmg** [comment]
Sounds good to me :). Also with the `(global)` or `(themefolder)` indicator?

**Comment by leofeyer** [comment]
No, because `(global)` means "the template is in the `/templates` directory" and `(themefolder)` means "the template is in the `/templates/themefolder` directory" and neither one is correct.

**Comment by fritzmg** [comment]
Not sure what you mean, that is correct is it not? If there is a `templates/ce_text.html5`, then it should say

```html
<option value="">ce_text (global)</option>
```

etc.

**Comment by leofeyer** [comment]
Ah, I see. 👍

**Comment by leofeyer** [comment]
Nope, that does not work, I'm afraid. The field is called **Custom element template** so UX requires it to be empty by default.

**Comment by fritzmg** [comment]
Even though the UX is now a little worse than before? 😁

**Comment by leofeyer** [comment]
As discussed in Mumble on April, 9th, we want to overwrite the blank option with the default theme name (e.g. `ce_text (global, Theme A)`) and rename the field from "Custom module template" to "Module template".
