### ISSUE TITLE
Search: phrases are split for highlighting

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#1061]
**Affected version(s)**
4.8.5, probably 4.4.45 too

**Description**  
If you search for a phrase via `"…"`, then the Contao search will correctly only show pages where this phrase appears in its content. However, the highlighting will be wrong, as it will highlight also the individual words, instead of just the phrase:

https://demo.contao.org/en/search.html?keywords=%22the+open+source%22

![Screenshot_2019-12-05 Search this website - Contao Official Demo](https://user-images.githubusercontent.com/4970961/70224635-e891a080-174d-11ea-984d-eb6ff7564013.png)

This is a little confusing as this looks like Contao actually did not search for the whole phrase (which it actually did).

**Comment by leofeyer** [comment]
Solving this is not trivial though, as the basis for highlighting words is the `matches` field from the search results object. If you e.g. search for `"the open source" awesome`, the search result object will look like this:

```php
[
    'sid' => '1',
    'matches' => 'the,awesome,open,source',
    'count' => '4',
    'relevance' => '42',
    'id' => '1',
    'pid' => '2',
    'tstamp' => '1580484246',
    'title' => 'Contao Official Demo',
    'url' => 'https://managed-edition.wip/en/',
    'text' => 'Contao Official Demo Welcome to the official Contao demo site. Here you can …',
    'filesize' => '74.55',
    'checksum' => '70254bb0a84c06ba7ab8bcc42b289a85',
    'protected' => '',
    'groups' => '0',
    'language' => 'en',
]
```

There is no way to distinct between single keywords and phrases anymore.

**Comment by leofeyer** [comment]
Turns out there is a way to fix this, however, it implies a BC break (see #1270).
