### ISSUE TITLE
Invalid token - cannot log in

### ISSUE THREAD

**Issue by emiliaborowska** [contao/contao#1069]
From today, I cannot log in to contao manager of my website. 

When I try to log in, the following appears: 
Invalid request token!
The request token could not be verified. Please go back and try again.

This error occurres if there is a POST request without a valid authentication token. In Contao 2.10, the referer check has been replaced with a request token system. If the problem persists, you are maybe using an incompatible third-party extension or have not correctly updated your Contao installation.

For more information, visit the Contao FAQ page or search the Contao forum.

On the main page, the following code is visible: 

Warning: fopen(/home/.sites/94/site2771/web/system/tmp/d02fcb0a72a4c2d51be40adc23fd0bdb) [function.fopen]: failed to open stream: Disk quota exceeded in /home/.sites/94/site2771/web/system/libraries/FileCache.php on line 113
#0 [internal function]: __error(2, 'fopen(/home/.si...', '/home/.sites/94...', 113, Array)
#1 /home/.sites/94/site2771/web/system/libraries/FileCache.php(113): fopen('/home/.sites/94...', 'wb')
#2 [internal function]: FileCache->__destruct()
#3 {main}

Warning: fputs() expects parameter 1 to be resource, boolean given in /home/.sites/94/site2771/web/system/libraries/FileCache.php on line 114
#0 [internal function]: __error(2, 'fputs() expects...', '/home/.sites/94...', 114, Array)
#1 /home/.sites/94/site2771/web/system/libraries/FileCache.php(114): fputs(false, 'a:4:{s:6:"Confi...')
#2 [internal function]: FileCache->__destruct()
#3 {main}

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/.sites/94/site2771/web/system/libraries/FileCache.php on line 115
#0 [internal function]: __error(2, 'fclose() expect...', '/home/.sites/94...', 115, Array)
#1 /home/.sites/94/site2771/web/system/libraries/FileCache.php(115): fclose(false)
#2 [internal function]: FileCache->__destruct()
#3 {main}

Warning: rename(/home/.sites/94/site2771/web/system/tmp/d02fcb0a72a4c2d51be40adc23fd0bdb,/home/.sites/94/site2771/web/system/tmp/bc2b06d0d6aef24c1d8441404a74cef4.txt) [function.rename]: No such file or directory in /home/.sites/94/site2771/web/system/libraries/FileCache.php on line 124
#0 [internal function]: __error(2, 'rename(/home/.s...', '/home/.sites/94...', 124, Array)
#1 /home/.sites/94/site2771/web/system/libraries/FileCache.php(124): rename('/home/.sites/94...', '/home/.sites/94...')
#2 [internal function]: FileCache->__destruct()
#3 {main}

Warning: Unknown: open(/home/.sites/94/site2771/tmp/sess_gvrjdm6oagl8u5nbvltt2ap2s6, O_RDWR) failed: Disk quota exceeded (122) in Unknown on line 0
#0 [internal function]: __error(2, 'Unknown: open(/...', 'Unknown', 0, Array)
#1 {main}

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/home/.sites/94/site2771/tmp) in Unknown on line 0
#0 [internal function]: __error(2, 'Unknown: Failed...', 'Unknown', 0, Array)
#1 {main}

What should I do? I do not have access to manager and cannot add any content. 

Let me know please if there are any suggestions, any support from contao side?

**Comment by fritzmg** [comment]
Just read the error message ;)

> Disk quota exceeded

Your web hosting ran out of disk space.
