### ISSUE TITLE
downgrading of symfony/filesystem & symfony/console

### ISSUE THREAD

**Issue by asaage** [contao/contao#107]
**Affected version(s)**
4.6.5
**How to reproduce**  
I ran "update packages" in the contao-manager and noticed the following

```
  - Updating symfony/filesystem (v4.1.4 => v3.4.15): Downloading (100%)
  - Updating symfony/console (v4.1.4 => v3.4.15): Downloading (100%)
```
That looks kind of strange to me and not exactly like an update.

Probably it's a contao-leads issue which in the same step was not updated but removed and installed with the next version.

**Comment by ausi** [comment]
contao-leads in version 1.4.11 is [not compatible with Symfony 4.*](https://github.com/terminal42/contao-leads/blob/1.4.11/composer.json#L15-L16), so the downgrade to 3.4.15 seems correct to me.

> That looks kind of strange to me and not exactly like an update.

What exactly looks strange? What did you expect to happen instead?

**Comment by asaage** [comment]
I had contao-leads 1.4.10
with symfony/filesystem 4.1.4
and symfony/console 4.1.4
running before this update (i think the contao version was already 4.6.5)

and ```contao-console about``` tells me i am still using symfony 4.1.4

I am just having some difficulties getting my head around [this](https://github.com/contao/contao/commit/58ad40cd8782bb2b07b75dc1c58cc819f93791a0#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) and the output of the update-command.
Intuitively i'd never expect an update to intall lower versions than those that are currently installed but it seems that everything just works - so i am closing this.

**Comment by fritzmg** [comment]
> Intuitively i'd never expect an update to intall lower versions than those that are currently installed

That can happen at any time.
