### ISSUE TITLE
Error 500 without error log

### ISSUE THREAD

**Issue by sebj54** [contao/contao#1070]
**Affected version(s)**

At least Contao 4.4 and 4.8 (maybe all versions).

**Description**  

Contao crashes with an error 500. There is no log in `var/logs`.

**How to reproduce**  

Install a new Contao instance normally (create database, create tables and all). Then truncate all tables and refresh any front-office page. You'll get an error 500 but no log.

**Comment by Toflar** [comment]
You likely don't get any logs because PHP itself crashes. There's nothing we can do to prevent this.
Make sure you check your server logs instead (Apache or Nginx error logs).

**Comment by sebj54** [comment]
You're right, I have this error in my PHP error log:

```
[09-Dec-2019 11:56:18 UTC] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Contao\CoreBundle\Fragment\FragmentRegistry::get() must be of the type string, object given, called in C:\wamp64\www\eqodis\vendor\contao\core-bundle\src\HttpKernel\ControllerResolver.php on line 43 in C:\wamp64\www\eqodis\vendor\contao\core-bundle\src\Fragment\FragmentRegistry.php:54
Stack trace:
#0 C:\wamp64\www\eqodis\vendor\contao\core-bundle\src\HttpKernel\ControllerResolver.php(43): Contao\CoreBundle\Fragment\FragmentRegistry->get(Object(Closure))
#1 C:\wamp64\www\eqodis\vendor\symfony\http-kernel\HttpKernel.php(134): Contao\CoreBundle\HttpKernel\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#2 C:\wamp64\www\eqodis\vendor\symfony\http-kernel\HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 2)
#3 C:\wamp64\www\eqodis\vendor\symfony\http-kernel\EventListener\ExceptionListener.php(62): Symfony\Component\HttpKernel\ in C:\wamp64\www\eqodis\vendor\contao\core-bundle\src\Fragment\FragmentRegistry.php on line 54
```

Isn't it possible to have an early check to see if there is a site structure or something like this? This error only happens on a frontend route, backend works perfectly. Throwing an exception will make the error obvious for everyone. 

Actually, when you create a Contao instance, you don't expect the frontend to work before creating a root page. But when you perform a migration (ie. when deploying the website on a server), you might spend a few minutes trying to figure out what is happening. Sometimes you also don't have an easy access to the PHP log.

**Comment by Toflar** [comment]
It's a PHP fatal error. PHP execution halts. 
You can only prevent such errors by static analysis or during compilation time for compiled languages (which PHP is not).
So no, that's not possible. That's how PHP works :)

**Comment by m-vo** [comment]
@Toflar He probably meant preventing the error in the first place not catching it (which of course isn't possible).

**Comment by Toflar** [comment]
Well, there are a billion possibilities on why someone passes an invalid parameter type anywhere in the code. How would we be able to catch that?

**Comment by sebj54** [comment]
Exactly @m-vo, this is exactly what I meant! 

I don't want to fix this fatal error, I would like to prevent it only in the specific case I mentioned (when all tables are empty). So frontend routes don't show a blank page but an error page (which can be customized).

Maybe that early check can only be an exception thrown if there is no root page to display.

**Comment by aschempp** [comment]
> `[09-Dec-2019 11:56:18 UTC] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Contao\CoreBundle\Fragment\FragmentRegistry::get() must be of the type string, object given, called in C:\wamp64\www\eqodis\vendor\contao\core-bundle\src\HttpKernel\ControllerResolver.php on line 43 in C:\wamp64\www\eqodis\vendor\contao\core-bundle\src\Fragment\FragmentRegistry.php:54
`

This looks strange to me, and shouldn't be related to an empty database table. Can you reproduce/find out why this happens in the code?

**Comment by sebj54** [comment]
Sure, I'll check this tomorrow morning and get back to you.

**Comment by sebj54** [comment]
Hi @aschempp, I investigated to see what is happening here. I don't know Symfony that much so I'm not sure what is wrong.

Here is the value of `$request->attributes->get('_controller')` (which should be a string if I'm right):

```
Closure Object
(
    [static] => Array
        (
            [debug] => 
        )

    [this] => Symfony\Component\HttpKernel\EventListener\DebugHandlersListener Object
        (
            [exceptionHandler:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => 
            [logger:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => 
            [levels:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => 32767
            [throwAt:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => 0
            [scream:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => 
            [fileLinkFormat:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => Symfony\Component\HttpKernel\Debug\FileLinkFormatter Object
                (
                    [fileLinkFormat:Symfony\Component\HttpKernel\Debug\FileLinkFormatter:private] => 
                    [requestStack:Symfony\Component\HttpKernel\Debug\FileLinkFormatter:private] => 
                    [baseDir:Symfony\Component\HttpKernel\Debug\FileLinkFormatter:private] => 
                    [urlFormat:Symfony\Component\HttpKernel\Debug\FileLinkFormatter:private] => 
                )

            [scope:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => 
            [charset:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => UTF-8
            [firstCall:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => 
            [hasTerminatedWithException:Symfony\Component\HttpKernel\EventListener\DebugHandlersListener:private] => 1
        )

    [parameter] => Array
        (
            [$request] => 
        )

)
```

If I disable the condition by commenting it (`vendor/contao/core-bundle/src/HttpKernel/ControllerResolver.php:42`), I don't have the fatal error but this:

![image](https://user-images.githubusercontent.com/5880435/70537085-34828200-1b60-11ea-8801-fac294a2d0af.png)

Tell me if I can produce logs more helpful or even a zip of my project. I can reproduce this bug systematically on versions 4.4 and 4.8 (two completely different projects) on Windows (local machine) and a Debian server.

**Comment by aschempp** [comment]
I _think_ the controller is actually allowed to be an object. I'll have to investigate that in the Symfony code.

**Comment by aschempp** [comment]
However, are you sure the same error appears in Contao 4.4? Because Contao 4.4 does not have a `FragmentRegistry`

**Comment by sebj54** [comment]
You're right, it does not happen with Contao 4.4. It's another problem with a i18n module (trying to redirect on a localized route).

I reinstalled a clean 4.4 version (without modules) with an empty database and it shows this error (no root page found):

![image](https://user-images.githubusercontent.com/5880435/70605870-993eea80-1bfb-11ea-9036-eef4197d49c4.png)

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/1087
