### ISSUE TITLE
Symlink generation for 'files' folder depends on hidden .public file

### ISSUE THREAD

**Issue by mMuck** [contao/contao#109]
**Affected version(s)**
4.4.24; 4.4.x?, 4.x?

**Description**  
In my migration process from contao 3.x to 4.4 I had problems with a missing web/files symlink which generated an error after accessing the main frontend page. I tried to find the reason an found this:
( contao/core-bundle/src/Command/SymlinksCommand.php )

    private function symlinkFiles($uploadPath)
    {
        $this->createSymlinksFromFinder(
            $this->findIn($this->rootDir.'/'.$uploadPath)->files()->name('.public'),
            $uploadPath
        );
    }

When will the .public file be created. Perhaps I deleted it because I migrated files manually from the older installation. It wasn't really easy to find out this condition for the symlink creation. First I assumed it could be a wrong configuration and the uploadPath parameter would give an invalid path...

**How to reproduce**  
At my installation the web/files symlink wasn't created through the maintenance function until I created the .public file in <Root>/files.

**Comment by xchs** [comment]
> When will the .public file be created.

It will be created as soon as you set a folder to public in the back end file manager.

**Comment by mMuck** [comment]
> It will be created as soon as you set a folder to public in the back end file manager.

OK, so my issue is related to the way I migrated and this misconfiguration in the file manager. Thanks for your help! :smiley:
