### ISSUE TITLE
Search index indices 500er error pages

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1091]
**Affected version(s)**
4.4.45

**Description**
After calling

`https://example.org/de/some-alias?%28function%28%29%7bif%28typeof%20bb4og%3d%3d%3d%27undefined%27%29%7bvar%20a%3dnew%20Date%28%29%3bdo%7bvar%20b%3dnew%20Date%28%29%3b%7dwhile%28b-a%3c20000%29%3bbb4og%3d1%3b%7d%7d%28%29%29=1`

the page, which produces

`Oops! An Error Occurred The server returned a "500 Internal Server Error". Something is broken.`

is being copied into the search index.

How can I avoid that? Am I doing something wrong? Thanks in advance!

bye

**Comment by leofeyer** [comment]
Which HTTP status code does the Oops! page send?

**Comment by Defcon0** [comment]
It sends status code 500.

**Comment by leofeyer** [comment]
Indeed, it seems that we are not checking the status code of the response. 🤔 

https://github.com/contao/contao/blob/4.4/core-bundle/src/EventListener/AddToSearchIndexListener.php

@contao/developers Can this be true?

**Comment by Toflar** [comment]
That‘s been like that ever since and has been reworked in 4.9.

**Comment by leofeyer** [comment]
We should still check the status code in Contao 4.4, shouldn't we?

**Comment by Toflar** [comment]
We can, yes. But we haven't for 2.5 years, so I wonder why this only comes up now? 😄

**Comment by leofeyer** [comment]
Me too.
