### ISSUE TITLE
Event names not consistent?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1096]
While working on #1095, I noticed that we have some event names starting with `contao.` and other with `kernel.`:

```
{ name: kernel.event_listener, event: contao.backend_menu_build }
{ name: kernel.event_listener, event: contao.robots_txt }

{ name: contao.frontend_module, category: user }
{ name: contao.picker_provider, priority: 160 }
{ name: contao.escargot_subscriber }
```

@contao/developers Shouldn't all our event names begin with `contao.`?

**Comment by ausi** [comment]
The last three of your examples are not events I think.
`contao.frontend_module` is the name of the tag.

**Comment by aschempp** [comment]
@ausi is absolutely right, you're confusing tags with tagging events 😊

**Comment by leofeyer** [comment]
Valid point, however, the question remains: Shouldn't all our tags begin with `contao.`? Just like Doctrine uses `doctrine.event_listener`?

```
- { name: doctrine.event_listener, event: onSchemaIndexDefinition }
```

**Comment by aschempp** [comment]
you're confusing it again 😂
Doctrine has it's own event dispatcher, because it is used outside Symfony as well. Contao uses the Symfony event dispatcher, therefore we use `kernel.event_listener` and not `contao.event_listener`. There is absolutely no benefit from using another event dispatcher.

**Comment by leofeyer** [comment]
I see. 👍
