### ISSUE TITLE
No individual Templates available

### ISSUE THREAD

**Issue by akroii** [contao/contao#1099]
**Affected version(s)**
4.8.5, not testet in 4.4 

**Description**
For Modules no individual Templates are selectable. The dropdown is empty.

**How to reproduce**
1. Install clean 4.8.5
2. Go to modules
3. Inputfield "Individual Templates" remains emptiness

**Comment by fritzmg** [comment]
That's normal. Templates only show up, if you actually created any individual templates (with a name other than the default one).
