### ISSUE TITLE
Don't use __DIR__ in symfony commands

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1104]
**Affected version(s)**
4.4.45

**Description**
When overriding for example `Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication` in the project root's `composer.json` we get problems with __DIR__, when the command is in another directory than the original file was. Better would be to use the project root and then go to the appropriate files.

**How to reproduce**
Replace `Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication` with a custom file in another location and run it.

Thanks!

**Comment by aschempp** [comment]
you mean your custom script handler is extending the core script handler? Why would you override that, and not just add your script additionally in the `composer.json`?

**Comment by Defcon0** [comment]
Because of line 72:

```
static::executeCommand('contao:install-web-dir', $event);
```

It calls contao:install-web-dir without any parameters. But I need to call it with --no-dev parameter so that app_dev.php isn't created in the live system.

**Comment by aschempp** [comment]
Have you tried executing that command after the regular callback? Will it remove the `app_dev.php`? Personally, I simply use deployment tools to remove the file afterwards 😈

**Comment by Defcon0** [comment]
I could do that, but once the app_dev.php is created I have to delete it again afterwards. I try to avoid creating it in the first place. What kind of development tools do you mean?

**Comment by aschempp** [comment]
I mostly use https://deployer.org now but worked with https://www.magephp.com for a long time.

**Comment by Defcon0** [comment]
Ah ok, I'll take a look into this tools.

For the sake of update safety, I added a new script after the core's one as you advised. This way the app_dev.php exists for some milliseconds which is ok I guess ;-)

Thanks!
