### ISSUE TITLE
Fehlendes endif

### ISSUE THREAD

**Issue by Olli** [contao/contao#1108]
**Affected version(s)**
4.8.6
**Description**
Das if für die Sizes hat kein endif in  contao/core-bundle/src/Resources/contao/templates/picture/picture_default.html5  

` <?php if (!empty($this->img['sizes'])): ?> sizes="<?= $this->img['sizes'] ?>" `
**How to reproduce**
Eine ganz normale Bildausgabe sollte nicht klappen.

**Comment by cliffparnitzky** [comment]
Hier? https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/templates/picture/picture_default.html5#L5

Ich meine, dass alles passt.

**Comment by fritzmg** [comment]
> Hier? https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/templates/picture/picture_default.html5#L5
> 
> Ich meine, dass alles passt.

Ich zähle 11 `if` und 10 `endif` ;)

**Comment by cliffparnitzky** [comment]
Hmmm, frage ich mich wie das gezählt wird. Beim oben verlinkten Template im `master` komme ich immer auf korrekt Werte.

Bei dem Template im `4.8.6` Tag stimmt wirklich was nicht: https://raw.githubusercontent.com/contao/contao/4.8.6/core-bundle/src/Resources/contao/templates/picture/picture_default.html5

Allerdings zähle ich 10 `if` und 9 `endif`.

**Comment by christianbarkowsky** [comment]
Den Fehler kann ich bestätigen.

**Comment by Anke** [comment]
Ich auch. (Wäre ja nicht so schlimm, wenn dadurch in C4 nicht gleich die komplette Website lahm gelegt würde.)

**Comment by contaoacademy** [comment]
Als Workaround ein neues Template `picture_default.html5` anlegen und dann in Zeile 9 das `endif` ergänzen.

`<?php if (!empty($this->img['sizes'])): ?> sizes="<?= $this->img['sizes'] ?>"<?php endif; ?>`

**Comment by christianbarkowsky** [comment]
Oder hier komplett zum einfügen:

https://gist.github.com/christianbarkowsky/d65c5dca8ffb4c4089f76a0df382f967

**Comment by frontendschlampe** [comment]
Der Fehler ist in Commit 9cb3f27f6da19d87540e8e49161e33131e471c85 entstanden. Da wurde aus einem `elseif` ein `if` und somit fehlt nun jetzt das `endif`

**Comment by Anke** [comment]
Shit happens ;-)

**Comment by leofeyer** [comment]
See #1111

**Comment by contaoacademy** [comment]
Hmm, kann es sein, dass ich jetzt meine Responsive Image Konfiguration anpassen muss? Zumindest reagiert die Ausgabe jetzt anders als vorher
