### ISSUE TITLE
BE-Login: Set focus on 2FA field

### ISSUE THREAD

**Issue by Anke** [contao/contao#1110]
**Description**
Just a comfort issue: Wouldn't it be nice to already have the cursor in the 2FA-field? (after login users are focused on their phones, blindly entering the displayed code - to no avail)

**Example**

**Comment by leofeyer** [comment]
How do I reproduce this? I just tried Safari, Chrome and Firefox on Mac OS and the 2FA field hat the focus in all three browsers.

**Comment by Anke** [comment]
Leo, I'm sorry, it didn't work for me in FF a while ago, but it is now.
