### ISSUE TITLE
Update to 4.8.6

### ISSUE THREAD

**Issue by michaelgawlik** [contao/contao#1112]
After update from 4..8.5 to 4.8.6 I got this error:

`[2019-12-17 14:44:18] request.CRITICAL: Uncaught PHP Exception ParseError: "syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)" at .../vendor/contao/core-bundle/src/Resources/contao/templates/picture/picture_default.html5 line 14 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) at .../vendor/contao/core-bundle/src/Resources/contao/templates/picture/picture_default.html5:14)"} []
`

**Comment by bytehead** [comment]
See #1111
