### ISSUE TITLE
Neue CSS-Klassen für "full screen mode"

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1119]
mit dem neuen "full screen mode" ist die kleinste Aufteilung der Eingabemasken vom 50% immer noch recht breit - die Idee von https://github.com/OMOSde/contao-om-backend/blob/master/FEATURES.md#17-backend-css finden wir vom "MM-Team" sehr gut...

Bitte kurze Rückmeldung, ob sowas in Planung ist oder aus OMO übernommen wird - ansonsten würden wir das für MM in unser CSS + Stylepicker einbauen.

**Comment by aschempp** [comment]
🤷‍♂ der Link zeigt mir leider nichts

**Comment by zonky2** [comment]
ich sehe da eine Beschreibung und zwei Screenshots - Du nicht?

ansonsten - das CSS: https://github.com/OMOSde/contao-om-backend/blob/master/src/Resources/public/css/om_backend.css#L130-L158
