### ISSUE TITLE
Member not accessible through token storage

### ISSUE THREAD

**Issue by christian-kolb** [contao/contao#112]
**Affected version(s)**
4.5 and 4.6

**Description**  
When I'm logged in as a `FrontendUser` and call an API Endpoint, I'm not able to access the user in the API Controller. As of 4.5 the symfony security components are used, so I should be able to get the user by token, shouldn't I?

**How to reproduce**  
Setup a symfony controller, make it available through routing, login as a frontend user then open a new tab with the controller endpoint. Put in the following content:

```
$tokenStorage = $this->get('security.token_storage');
$token = $tokenStorage->getToken();
var_dump($token);

$tokenChecker = $this->get('contao.security.token_checker');
$username = $tokenChecker->getFrontendUsername();
var_dump($username);

exit;
```

Both return `null`.

The second example is from the `getInstance()` function of the `FrontendUser` class.

What am I missing? 🙂

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
The frontend firewall is only active if your route has `_scope = contao_frontend`.

**Comment by christian-kolb** [comment]
> The frontend firewall is only active if your route has `_scope = contao_frontend`.

@aschempp Work's with the scope. Where could I have found this info? 🙂I think I searched through all articles and Contao news I could find about this topic.

**Comment by Toflar** [comment]
@fritzmg is currently working on a new documentation, we might maybe start labeling issues with `documentation` so we can refer back to those once it's ready and people can contribute 🤔

**Comment by christian-kolb** [comment]
@fritzmg Is there already a draft version online somewhere? I'm happy with every single bit of information I can find on Contao and it's transformation to the Symfony components. @contao/developers Awesome work there by the way 🙂

**Comment by fritzmg** [comment]
@Toflar good idea
@christian-kolb no, not yet
