### ISSUE TITLE
allow local_domain parameter to be set via parameters.yml

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#113]
For example, if you use Google G Suite and you need to route outgoing emails of a website through the SMTP Relay Service without authentication (for whatever reason), you'll need to set the [`local_domain` parameter](https://symfony.com/doc/current/reference/configuration/swiftmailer.html#local-domain) (new since version `2.4.0` of the swiftmailer-bundle and supported since `6.0` of swiftmailer) to one of your G Suite account's domain, so that Swiftmailer uses that in the EHLO/HELO command.

In my case I need to do this because the [suggested solutions](https://github.com/contao/contao/issues/64#issuecomment-423247185) for sending emails without SMTP are not working in Contao 4.6 for some reason.

**Comment by leofeyer** [comment]
Why does this have to be configurable in the `parameters.yml`? You should use the `config.yml` for this kind of things.

**Comment by fritzmg** [comment]
Indeed :)

(and I can use parameters from the `parameters.yml` myself in the `config.yml` anyway)
