### ISSUE TITLE
No label keys in widgets if there is no translation

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/contao#1135]
**Affected version(s)**
4.8.x

**Description**
Since #953 , if you have no label-key definied in the DCA and there is no translation-file you can't see the label key in the widgets. 

![image (1)](https://user-images.githubusercontent.com/1027521/71588014-39fc3800-2b20-11ea-890e-916c7ad51ea4.png)

Reproduce
---
- install contao
- delete all languages except of `en`
- delete/rename `tl_member.xlf`
- go to members in backend

usecase
---
when i prototype some new extensions i dont want to do the translations

**Comment by leofeyer** [comment]
As discussed in Mumble on January 16th, if there is no label (`null`), the key should be used. To have an empty label, it must be set to an empty string or `false`.
