### ISSUE TITLE
Sortierreihenfolge von Quelldateien in Inhaltselementen kann ohne Berechtigung für Feld Sortierreihenfolge geändert werden

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1137]
In einem Inhaltselement (beispielsweise Elementtyp Downloads) kann ein Benutzer, der die Berechtigung für das Feld Quelldateien (``multiSRC``) hat, auch die Sortierreihenfolge (``orderSRC``) der ausgewählten Dateien ändern ("Elemente können durch Ziehen umsortiert werden"), wenn er keine Berechtigung für das Feld Sortierreihenfolge (``orderSRC``) hat.

**Comment by aschempp** [comment]
In welcher Contao Version? Das Feld `orderSRC` sollte in den Benutzerberechtigungen nicht erscheinen.

**Comment by leofeyer** [comment]
@Mynyx /ping

**Comment by Mynyx** [comment]
In den aktuellen Versionen kann ich das Problem nicht mehr nachvollziehen.
