### ISSUE TITLE
Kein System-Log Eintrag bei fehlgeschlagener Zwei-Faktor-Authentifizierung

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1142]
Bei Eingabe eines falschen Bestätigungscodes für die Zwei-Faktor-Authentifizierung wird, im Gegensatz zur Eingabe eines falschen Passwortes, kein System-Log Eintrag erstellt.

**Comment by leofeyer** [comment]
This has been fixed in Contao 4.9.
