### ISSUE TITLE
Link Backend-Tastaturkürzel

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1143]
Der Link unter Backend-Tastaturkürzel auf dem Dashboard verweist noch auf die alte Dokumentation https://docs.contao.org/books/manual/current/de/02-administrationsbereich/backend-tastaturkuerzel.html statt https://docs.contao.org/manual/de/administrationsbereich/backend-tastaturkuerzel/.

**Comment by leofeyer** [comment]
Ich habe die deutsche Übersetzung angepasst. Die englische Übersetzung können wir aber erst anpassen, nachdem die englische Anwenderdoku veröffentlicht wurde.

**Comment by netzarbeiter** [comment]
Wir haben die englische Übersetzung für die Tastenkürzel eingepflegt.

https://docs.contao.org/manual/en/administration-area/back-end-keyboard-shortcuts/

**Comment by fritzmg** [comment]
Ich habe auch Redirects für beide alten URLs eingerichtet.

**Comment by leofeyer** [comment]
See #1293
