### ISSUE TITLE
Versionsvergleich Frontend-Modul Personendaten Feld "Editierbare Felder"

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1144]
Wenn bei einem Frontend-Modul mit dem Modultyp Personendaten im Feld "Editierbare Felder" die Auswahl geändert wird, dann wird im Versionsvergleich nicht angezeigt, welche Änderungen konkret vorgenommen wurden:

![image](https://user-images.githubusercontent.com/1632642/71632100-e3b8f300-2c0c-11ea-88c8-fd483d4f8a90.png)

**Comment by leofeyer** [comment]
Die SQL-Definition von `tl_module.editable` ist falsch, daher denkt die `Versions`-Klasse, dass es sich um ein Binary-Feld handelt. Es muss `text NULL` anstatt `blob NULL` sein.

**Comment by fritzmg** [comment]
Hm, but all `*Wizard` input types use `*blob NULL`, not just `tl_module.editable`.

**Comment by leofeyer** [comment]
Then we need to fix them all. 🤷‍♂ Unless they contain real binary data such as UUIDs of course.

**Comment by leofeyer** [comment]
@ausi and @Toflar taught me better:

> Note that this is a binary string which may include null bytes, and needs to be stored and handled as such. For example, **serialize() output should generally be stored in a BLOB field** in a database, rather than a CHAR or TEXT field.

**Comment by Toflar** [comment]
But we could check if it's all UTF-8 and in such a case deserialize for version comparison. Should be as easy as `preg_match('//u', $string)`. Or using the UTF8 lib.

**Comment by leofeyer** [comment]
See #1294
