### ISSUE TITLE
Improve the contao:crawl output

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1152]
<img width="1129" alt="" src="https://user-images.githubusercontent.com/1192057/71721058-096c1500-2e24-11ea-8cc7-b737c16c6bb5.png">

I can see that the crawler has found three broken links, however, I have to look twice to actually find them in the exception text.

@contao/developers Do you think we should invest time to improve this?

**Comment by Toflar** [comment]
Not sure how this can be improved, really. I mean, I knew that a table might be better but these are log entries after all. So it's just a line of text for every error and it can contain arbitrary data. And subscriber A does provide different data than subscriber B. So there's not too much we can unify here which would be required to have a table.

**Comment by Toflar** [comment]
I do have a few ideas though. Imho the functionality is correct and we are talking about "smoothening" 4.9 so we have a bit more time here.

**Comment by Toflar** [comment]
Closing in favor of https://github.com/contao/contao/pull/1171
