### ISSUE TITLE
Useragent für ausgehende Mails

### ISSUE THREAD

**Issue by kroerig** [contao/contao#1156]
Beim Aufsetzen und Testen eines neuen Antispam-Gateways mit RSPAMd bin ich bei der Analyse der über die Webseite verschickten Mails auf einen Eintrag gestoßen:

XM_UA_NO_VERSION (0.01): X-Mailer/User-Agent has no version

Das bringt zwar nicht massig an Spampunkten, aber ich finde auch die 0.01 (default) müssen nicht sein. Lässt sich da was machen, dass Contao bei ausgehenden Mails einen Useragent mit Versionsnummer mitschickt?

R_MIXED_CHARSET (0.625)
MID_RHS_WWW (0.5)
MIME_GOOD (-0.1) [text/plain]
XM_UA_NO_VERSION (0.01)
REPLYTO_DN_EQ_FROM_DN (0)
HAS_REPLYTO (0) [info@xxxxxx.de]
REPLYTO_DOM_NEQ_FROM_DOM (0)
ARC_NA (0)
FROM_NO_DN (0)
MIME_TRACE (0) [0:+]
FROM_EQ_ENVFROM (0)
RCVD_COUNT_ZERO (0) [0]
TO_DN_NONE (0)
RCPT_COUNT_ONE (0) [1]
TO_EQ_FROM (0)
TO_MATCH_ENVRCPT_ALL (0)
ASN (0) [asn:24940, ipnet:46.4.0.0/16, country:DE]

Das summiert sich dann zu 1.03 Spampunkten.

**Comment by leofeyer** [comment]
Hm, ich weiß nicht. Als Versionsnummer käme ja nur die Contao-Version in Frage, aber das scheidet für mich aus, weil man dadurch die Version einer Installation herausfinden könnte (indem man sich z.B. registriert und dann den Mail-Header ausliest). Und eine statische Versionsnummer erscheint mir irgendwie sinnlos.

@contao/developers WDYT?

**Comment by m-vo** [comment]
> Und eine statische Versionsnummer erscheint mir irgendwie sinnlos.

Wozu wird die Versionsnummer denn benutzt?

**Comment by kroerig** [comment]
Es könnte ja auch die Version vom Swiftmailer sein.

**Comment by fritzmg** [comment]
~~Laut https://tools.ietf.org/html/draft-melnikov-email-user-agent-00 soll da auch keine Version drin stehen.~~

Hm, eine Version _kann_ drin stehen, muss aber nicht - aber vielleicht interpretiere ich auch den RFC falsch.

**Comment by kroerig** [comment]
Es soll etwas drinstehen, das den MUA eindeutig identifiziert.
Jeder klassische Mailclient schickt seinen Namen und in irgendeiner Form seine Version mit.

Spamfiler werten das aus. Heute zwar nicht mehr so streng wie zu Anfang, aber es spielt mit rein.

Es gibt so ein paar Privacy Appliances, die meinen sie müssten das Feld (und noch ein paar andere) aus Datenschutzgründen entfernen. Diese Mails sammeln dann auch gerne Spampunkte.

**Comment by fritzmg** [comment]
> Es gibt so ein paar Privacy Appliances, die meinen sie müssten das Feld (und noch ein paar andere) aus Datenschutzgründen entfernen. Diese Mails sammeln dann auch gerne Spampunkte.

Hier muss die Spam Filterung angepasst werden, nicht umgekehrt.

**Comment by kroerig** [comment]
Im Fall dieser Privacy Appliances, gehört das Teil selbst in die Tonne, die machen nämlich i.d.R. die ganze Mail kaputt. Aber darum geht es nicht.

Spamassassin und RSPAMd werten es als Spamindiz, wenn eine Mail zwar einen User-Agent oder X-Mailer enthält, dieser aber keine Version enthält, da jeder klassische MUA halt eine Version mitsendet:

- User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Thunderbird/60.8.0
- User-Agent: Roundcube Webmail/1.4.2
- X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
- X-Mailer: Agnitas EMM 19.04
- X-Mailer: Microsoft Outlook 14.0
- X-Mailer: PHPMailer 5.2.27 (https://github.com/PHPMailer/PHPMailer)
- X-Mailer: iPhone Mail (17D50)

Oder aber man lässt es ganz weg. Dann gibt es (zumindest bei RSPAMd) auch keine Punkte.

Wobei es mir immer ganz lieb ist sehen zu können womit eine Mail generiert wurde, wenn es zu Zustellproblemen kommt.




> Als Versionsnummer käme ja nur die Contao-Version in Frage, aber das scheidet für mich aus, weil man dadurch die Version einer Installation herausfinden könnte

Was wäre daran so schlimm? Security by obscurity sollte im Open Source-Bereich kein Thema sein.

**Comment by fritzmg** [comment]
> Was wäre daran so schlimm?

Du könntest automatisiert auf Web Applikationsversionen testen, die eine bekannte Sicherheitslücke haben.

**Comment by kroerig** [comment]
Das kann ich auch so. Dazu brauche ich keinen Mailheader.
Wie gesagt, ganz weglassen wäre auch eine Möglichkeit.

**Comment by fritzmg** [comment]
> Das kann ich auch so.

Nein, auf Versionen nicht - denn die Web Applikation sollte die Versions Nummer eben nirgendwo Preis geben. Du könntest höchstens auf Verdacht auf gewisse Sicherheitslücken testen - aber das funktioniert bei komplexeren Sicherheitslücken nicht mehr so leicht.

**Comment by aschempp** [comment]
Aus meiner Sicht können wir _Contao_ rein schreiben. Eine Version ist aus verschiedenen Gründen nicht richtig und nicht nötig. Selbst die Browser beginnen in ihren User-Agents die Version zu _freezen_, sodass die effektive Browser-Version nicht mehr verwendet werden kann.
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/-2JIRNMWJ7s/yHe4tQNLCgAJ

**Comment by fritzmg** [comment]
> Aus meiner Sicht können wir _Contao_ rein schreiben.

Es wird bereits _Contao Open Source CMS_ geschrieben: 

https://github.com/contao/contao/blob/8ba73b834c88ad6a275420bded02fe436a2f4e0e/core-bundle/src/Resources/contao/library/Contao/Email.php#L132

**Comment by ausi** [comment]
Ich würde den Header entfernen. GMail nutzt den Header z. B. auch nicht.
