### ISSUE TITLE
Benutzergruppen » viele Erlaubte Felder = keine Rechte

### ISSUE THREAD

**Issue by exscorp** [contao/contao#1161]
**Affected version(s)**
4.8.7 wahrscheinlich auch Versionen drunter

**Description**
Bei den Benutzergruppenrechten werden die Rechte (checkbox) nicht gechecked bei sehr vielen Erlaubten Feldern. Gibt es hier eine Limitierung (Anzahl)? Details siehe "**How to reproduce**". 

****

**How to reproduce**
1. » frische Contao 4.8.7 installation 
2. » eine Benutzergruppe erstellen
3. » überall "Alle auswählen" anklicken damit die Benutzergruppe alle Rechte hat

- = alle checkboxen werden "gechecked" und Rechte werden gespeichert
- = alles OK

1. » jetzt "isotope/isotope-core" installieren
2. » die Benutzergruppe öffnen
3. » die neuen/restlichen checkboxen anklicken
4. » "Speichern" anklicken

- = alle checkboxen unterhalb von "tl_module » Link zur primären URL [iso_link_primary]" verlieren den "checked" wert
- = dementsprechend verliert die Benutztergruppe jewelige Rechte
- = wenn man irgendwo ein paar "checked" rausnimmt und dann unten bei den "unchecked" die gleiche anzahl aktiviert, dann wird der Wert gespeichert
- = "Speichern und schließen"-Button funktioniert nicht richtig, speichert zwar aber schließt die Seite nicht

Ich weiß nicht ob es ein Bug in Contao und/oder isotope ist, ich hatte es mit paar anderen extensions Probiert aber keine bringt so viele zusätzliche Rechte zum freigeben mit.

Kann das jemand Prüfen und den "Bug" bestätigen.

**Comment by fritzmg** [comment]
https://docs.contao.org/manual/de/installation/systemvoraussetzungen/#php-konfiguration-php-ini

**Comment by akroii** [comment]
Stell die `max_input_vars` auf 1000 bzw. 1500. Dann sollte es funktionieren.

**Comment by exscorp** [comment]
ok, habe gerade auf 2000 erhöht und es funktioniert. danke euch.

wird ein höherer Wert nur zum Speichern benötigt (wie es in den Systemvoraussetzungen steht) und dann wieder runtersetzten oder sollte dieser dann auch aktiv bleiben (bei der Seite)?

**Comment by fritzmg** [comment]
Wird grundsätzlich überall dort benötigt, wo viele Daten per POST Request gesendet werden (bspw. beim Speichern der Benutzerberechtigungen). Den Wert kannst du ruhig hoch eingestellt lassen. Kannst du auch auf 100000 setzen.

**Comment by exscorp** [comment]
ok, dann lasse ich den erstmal so.

danke dir
