### ISSUE TITLE
Adding extra unique field in page module 

### ISSUE THREAD

**Issue by hoss-ps** [contao/contao#1163]
**Description**
Currently working with page module specially in some hooks like  '**getPageIdFormUrl**' need fixes Alias or Name to identify page which is not good idea, alias or name (in worst  case page id ) may need to change frequently from beginning of project until end specially for SEO purpose .
it will be nice to have an extra field for unique identification of the page in page backed module. 
currently i add this field manually in any project , but will be nice to have an extra field in backend just for identification of the page instead of pageID which will change by deleting page and not human readable  , pageAlias or pageName which can frequently change time to time by customer request.
in this case can get instance of page from PageModel, based on unique identification filed.

**Comment by m-vo** [comment]
Maybe I don't get your use case: Why exactly do you need to delete a page that needs to be referenced again later? The ID already is a stable identifier.

**Comment by hoss-ps** [comment]
let say in getPageIdFormUrl hook , i want to handle different levels of fragment in a unique page ,
or generate a page based on other page.
in this case let say we have many pages , how usually trace the page id? 
looking page alias in db to find Page Id?
 is it good idea to use pageID as identifier ?

**Comment by Toflar** [comment]
It really depends. I don't see an issue with having the page ID in the URL. It only allows people to understand that if the URL says `domain.com/166-foobar.html` that maybe `166` is the page ID and from that we can guess that there might be `167`, `168` etc. and that there's likely at least `166` pages. All of which is not dangerous information. If I'm able to guess a different existing page ID - so what? That page is still protected if I'm not allowed to access it. So here it's really not a security issue but purely an astethic one. If you don't like the way plain ID look in the URL, you may use hashids (https://hashids.org/).

However, having consecutively numbered IDs in the URL is not always a good idea. E.g. when you want unique URLs to provide access to fairly protection worthy data. Then you need random tokens, UUIDs etc.
But that's not the case for page IDs so I don't see any need to introduce additional complexity for no real use case.

**Comment by aschempp** [comment]
Please also be aware that ** getPageIdFormUrl** is very much outdated! You should rather work with the Symfony routing.

**Comment by hoss-ps** [comment]
@aschempp 👍  thanks for your information , currently in contao 4.4 i have tested Symfony routing ( YML version) and work really fine even beside old Hooks loading  but it get some issues with annotation. hope can use it in later versions.
