### ISSUE TITLE
Video/audio Element - add image size function to preview image 

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#1166]
**Description**
Contao 4.8.7

Add image size function to preview image for video/audio element.

There is only the option to select the image without the option to set the image dimensions and the resize mode.

**Comment by leofeyer** [comment]
This has been implemented meanwhile:

<img width="634" alt="" src="https://user-images.githubusercontent.com/1192057/136515268-c33b5c68-74f9-412f-ac3c-7230bff29469.png">
