### ISSUE TITLE
Video/Audio Element show no preview image when using chrome browser (Frontend)

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#1167]
**Affected version(s)**
Contao 4.8.7
Chrome Browser

**Description**
If a preview image is used with a video element and the preloading is set to the default value of `Auto`, the image is not displayed in the frontend.

According to research, this is probably a special problem with Chrome.
Firefox works fine.

For this reason I recommend to set the default value of the preload to `none`.
Because the chrome browser does not support preloading correctly at default setttings.

See also:
* https://support.google.com/chrome/thread/15245443?hl=en
* https://stackoverflow.com/questions/13492198/video-disappears-when-poster-attribute-and-preload-is-defined

**How to reproduce**
1. Create Video/Audio Element
2. Set player size and select a source file
3. Add preview image
4. Set preloading to "auto"
5. Open frontend with chrome browser

**Comment by fritzmg** [comment]
Actually, `preload` should not be set at all by default. According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-preload 

> The default value is different for each browser. The spec advises it to be set to metadata.

**Comment by leofeyer** [comment]
See #1316
