### ISSUE TITLE
Updatehinweis /Autoupdater

### ISSUE THREAD

**Issue by kroerig** [contao/contao#118]
Hallo,

in der 3er Version gab es für den Anwender immer einen kleinen Hinweis im Backend, wenn eine neue Version verfügbar war. Lässt sich das in Conato 4 auch wieder realisieren?

Der gemeine User guckt ja nicht ständig mit Composer oder Manager nach ob es Updates gibt. Da wäre ein Hinweis beim Login sehr hilfreich. Gleiches gilt auch für die installieren Erweiterungen. In Contao3 konnte man das recht schnell mit einem Klick erledigen und hatte eine Übersicht. Jetzt muss man immer erst entweder auf die Konsole oder in den Manager wechseln (ein Link vom Backend zum Manager wäre auch was feines)

Die Kollegen von WP gehen ja den Weg, dass Core-Updates automatisch eingespielt werden. Ich vermute durch den ressourcenfressenden Composer wird das nicht möglich sein, oder?

Klaus

**Comment by Toflar** [comment]
> in der 3er Version gab es für den Anwender immer einen kleinen Hinweis im Backend, wenn eine neue Version verfügbar war. Lässt sich das in Conato 4 auch wieder realisieren?

Viele User wollten das immer deaktiviert haben. Den normalen Redakteur interessiert es nämlich nicht bzw. es ist sogar nur störend (weil man als Admin dann immer Anrufe kriegt) und der Admin selber weiss es. Ich sehe also keinen Mehrwert.

> Die Kollegen von WP gehen ja den Weg, dass Core-Updates automatisch eingespielt werden. Ich vermute durch den ressourcenfressenden Composer wird das nicht möglich sein, oder?

Mit Composer hat das nichts zu tun, es ist einfach ziemlich gefährlich wie ich finde (hat WP ja auch bereits bewiesen). Ich würde das niemals aktivieren.

**Comment by kroerig** [comment]
Dem einfachen Redakteur muss die Meldung ja nicht gezeigt werden, aber bei Admin-Benutzern finde ich die Funktion sehr hilftreich. Wie soll der Admin erfahren, dass es ein Update für ein spezielles Bundle gibt (muss ja nicht mal Contao-Core sein), wenn die Software es selbst nicht meldet.

Selbst im Contao-Manager kann ich nicht direkt sehen für welche Bundles ein Update anstünde (und dann wäre noch die Frage, ob ich das überhaupt installieren will).

Wenn ich mal überlege, was ich so an Software betreue:
Moodle: prüft regelmäßig per Cron und schickt dem Admin eine Mail
Nextcloud: Meldet Updates bei Admin-Login
Wordpress: Installiert per Default Core-Updates automatisch (auf Wunsch auch Plugins und Theme; muss man kein Freund von sein - bin ich auch nicht), andernfalls weist es Admins auf ausstehenede Updates hin.

Das Problem mit dem Auto-Update und Composer sah ich ehr in der Zeit, die es braucht die Abhänigigkeiten aufzulösen, bei WP ist während eines Updates die Seite im Wartungsmodus.

Ich bin auch kein Freund der Zwangsupdates, aber irgendwie muss ich ja erfahren, dass da was Neues zur Installation ansteht.

**Comment by netzarbeiter** [comment]
Du könntest dir folgenden RSS-Feed abonnieren:
https://packagist.org/feeds/package.contao/core-bundle.rss

**Comment by dmolineus** [comment]
Wenn es dir darum geht wegen allen möglichen Paketen einen Hinweis zu erhalten, ob ein Update notwendig ist, könntest du `composer update --dry-run --no-dev` auf der Konsole ausführen. Sobald dort mehr steht als "Nothing to install or update" gibt es neue Versionen. Dies könnte man tatsächlich in den Manager integrieren, dass er beim Booten im Hintergrund prüft ob Updates vorliegen.

Es gibt auch noch `composer outdated`, was hier aber nicht weiterhilft. Es prüft nicht die definierten Abhängigkeiten.

**Comment by kroerig** [comment]
> 
> 
> Du könntest dir folgenden RSS-Feed abonnieren:
> https://packagist.org/feeds/package.contao/core-bundle.rss

@netzarbeiter Nur das Mozilla und Google die Unterstützung für RSS-Feeds gestrichen haben: https://www.heise.de/newsticker/meldung/Mozilla-entfernt-RSS-Reader-aus-Firefox-4121155.html
Und ich kann ja nicht für jedes installierte Paket nach einem RSS-Feed suchen, bzw. weiß ich ja teilweise gar nicht, welche Pakete durch Abhängigkeiten mitinstalliert wurden.

@dmolineus Das setzt voraus, dass ich bzw. der Kunde eine Konsole haben. Dank dem Manager ist die ja nicht (mehr) erforderlich um Contao 4 benutzen zu können.

Jede simple Software bringt heute einen Update-Check mit.

Und nicht jeder Kunde will oder kann sich einen Pflegevertrag für seine Webseite leisten. Wenn dann aber beim Login ein Hinweis erscheint "Ihre Installation ist veraltet" oder "es liegen Updates vor", dürfte sich doch der ein oder andere mal melden mitbekommen, dass man auch ein CMS (und nicht nur die Inhalte) pflegen muss. Wordpress weist auf Updates hin, Joomla tut es.

Man muss es ja nicht per Default einschalten bzw. nur für bestimmte Benutzer/ Gruppen aktivieren. Aber ich denke es könnte dazu beitragen, dass auch Installationen, die nicht von Profis gepflegt werden auf einem aktuellen Stand gehalten werden.

**Comment by xchs** [comment]
> Das setzt voraus, dass ich bzw. der Kunde eine Konsole haben.

Den Probelauf (dry-run) kannst Du inzwischen auch direkt im Contao Manager ausführen. Dafür brauchst Du bzw. die Kunden keinen Shell-Zugang (mehr).

**Comment by kroerig** [comment]
Ja, den habe ich bisher so verstanden, dass ich damit teste, ob ein Update funktionieren würde, nicht um zu schauen, ob und welche Updates es gibt.

Und damit ich den Button überhaupt nutzen, muss ich vorher in den Manager und auf "Pakete aktualisieren" klicken.

Bei mir berechnet er dann teilweise bis zu 75 Sekunden Abhängigkeiten, aber dann sehe ich immernoch nicht, welche Paket neu sind, außer ich wühle mich durch die Konsolenausgabe.

Was ich gerne hätte, ist eine optische Anzeige bei dem Paket, wenn eine neue Version verfügbar ist. **Und dann** mache ich einen Testlauf um zu prüfen, ob sich das Update auch ohne Fehler einspielen ließe.

**Comment by Toflar** [comment]
Das liesse sich sicher machen. Im Manager kann das ja auch hin, aber nicht im Contao Backend, das halte ich für falsch. Wir Admins sollten andere Informationsquellen haben als das Backend und dem regulären User sollte es egal sein, weil dafür hat er ja seinen Admin 😄

**Comment by kroerig** [comment]
Warum können Contao selbst und der Manager nicht miteinander kommunizieren?

Wenn ich mich als Admin an Contao anmelde, darf das System mir ruhig anzeigen, dass ich mal in den Manager wechseln sollte um anstehende Updates einzuspielen. (aber auch nur wenn, es auch welche gibt)

**Comment by Toflar** [comment]
Es sind zwei unabhängige Applikationen. Die eine soll lauffähig bleiben ohne die andere, damit man die Installation wieder hinbiegen kann, wenn man sie verkonfiguriert hat. Die Kommunikation kann nicht stattfinden, weil du dich dafür im Manager einloggen müsstest.

**Comment by kroerig** [comment]
> 
> 
> Das liesse sich sicher machen. Im Manager kann das ja auch hin, aber nicht im Contao Backend, das halte ich für falsch. Wir Admins sollten andere Informationsquellen haben als das Backend und dem regulären User sollte es egal sein, weil dafür hat er ja seinen Admin 😄

Dann möge jemand dieses Ticket doch bitte zum Contao-Manager verschieben.

**Comment by ghost** [comment]
Das Ticket wurde nach contao/contao-manager#350 verschoben.
