### ISSUE TITLE
Vorschau funktioniert nicht mehr bei Kombination Contao 4.8 und PHP 7.4.1

### ISSUE THREAD

**Issue by LinkingYou** [contao/contao#1183]
**Affected version(s)**
4.8.7

**Description**
Wenn man Contao 4.8.7 unter PHP 7.4.1 verwendet, kommt es bei der Vorschau und anschließendem Klick auf den "Anwenden"-Button zu einem Error 500:

**Return value of Contao\CoreBundle\Security\Authentication\Token\FrontendPreviewToken::showUnpublished() must be of the type bool, null returned**

in vendor/contao/core-bundle/src/Security/Authentication/Token/FrontendPreviewToken.php (line 50)

**How to reproduce**
- Frisches Contao 4.8.7 unter PHP 7.4.1 installieren
- Ins Backend einloggen
- Auf "Vorschau" klicken
- Auf "Anwenden" klicken

Getestet sowohl in einer aktuellen Debian-Umgebung sowie in einem Docker-Container. Anschließend im Docker-Container zurück auf PHP 7.3.x -> der Fehler tritt dort nicht mehr auf.

**Comment by fiedsch** [comment]
Ich kann das Problem mit zwei identischen Installationen, eine PHP 7.4.1 und eine mit PHP 7.3.13 reproduzieren.

* Login ins Backend und bei einem Artikel auf Vorschau => OK
* Vorschau als ein bestimmtes Mitglied => Fehler in der PHP 7.4er Version

**Comment by aschempp** [comment]
der Fehler wurde bereits in https://github.com/contao/contao/commit/b980cd1d0fc2fd761915674b5455d28192bc1a4d#diff-f666db4e4a80c10241a60085eded3c11 behoben (allerdings bisher nur für Contao 4.9)

**Comment by fiedsch** [comment]
> der Fehler wurde bereits in [b980cd1#diff-f666db4e4a80c10241a60085eded3c11](https://github.com/contao/contao/commit/b980cd1d0fc2fd761915674b5455d28192bc1a4d#diff-f666db4e4a80c10241a60085eded3c11) behoben (allerdings bisher nur für Contao 4.9)

Gerade mit 4.9.0-RC1 ausprobiert. Funzt. Danke!

**Comment by Tastaturberuf** [comment]
Kann man auch einfach so fixen:
```php
class FrontendPreviewToken extends AbstractToken
{
    /**
     * @var bool
     */
    private $showUnpublished = false;

    //...
}
```

**Comment by leofeyer** [comment]
Siehe #1305.
