### ISSUE TITLE
Wrong error message if the 2FA token is invalid

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1186]
If you enter an invalid 2FA token, the error message of the username/password step will be used:

<img width="572" alt="" src="https://user-images.githubusercontent.com/1192057/72383913-be53db00-371c-11ea-8edb-d357645df56d.png">

Maybe we can show a more suitable error message in this case?

**Comment by bytehead** [comment]
I'm pretty sure there was a different message before #1178 got merged: https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/languages/en/default.xlf#L225
