### ISSUE TITLE
HTML-Inhaltselemente im RSS-Feed

### ISSUE THREAD

**Issue by Funbug** [contao/contao#1187]
**Affected version**
Contao 4.8.7

**Description**
HTML-Inhaltslemente von Nachrichten werden im RSS-Feed als Text ausgegeben. Aus `<div class="panel">` wird `<pre>&lt;div class=&quot;panel&quot;&gt;</pre>`
Beispiel: https://km-kd.de/share/news.xml

Erwartetes Ergebnis wäre, dass das HTML im RSS-Feed als solches ausgegeben wird.

**Comment by cliffparnitzky** [comment]
Kann den beschriebenen Fehler in deiner Bespiel Datei nicht nachvollziehen.

**Comment by Funbug** [comment]
Ich auch nicht mehr. Interessant. Gestern war das noch definitiv so. Kann es sein, dass `Contao\News::generateFeedsByArchive` und `Contao\News::generateFeeds` das unterschiedlich handhaben? Die wurden seither nämlich ausgeführt.

**Comment by Funbug** [comment]
Wenn ich eine Nachricht unsichtbar schalte, wird der Feed mit o.g. Problem generiert. Ganz aktuell sieht man es wieder in o.g. Feed. Ich kann allerdings nicht nachvollziehen, welche Funktion auslöst, dass es wieder "normal" wird.

**Comment by cliffparnitzky** [comment]
> Ganz aktuell sieht man es wieder in o.g. Feed

Ah ja, jetzt ist es drin.

**Comment by Funbug** [comment]
Jetzt wurde laut System-Log - warum auch immer - `Contao\News::generateFeeds` ausgeführt. Damit stimmt es dann vorübergehend wieder.

**Comment by fritzmg** [comment]
Das macht der Cron. Offensichtlich ist es über den Cron richtig - über die direkte Aktualisierung bei Änderung im Backend (oder Systemwartung?) falsch.

**Comment by leofeyer** [comment]
Wie genau lässt sich das Problem reproduzieren?

**Comment by Funbug** [comment]
Wenn ich eine bestehende Nachricht unsichtbar schalte, wird der Feed falsch ausgegeben:
https://km-kd.de/share/news.xml

Sobald der Cron wieder drüberläuft, ist es wieder richtig.

**Comment by Funbug** [comment]
Betrifft auch 4.9.1.

**Comment by Funbug** [comment]
Im RSS-Feed muss "Ganze Beiträge" ausgewählt sein. Das Problem besteht auch in der Online-Demo.

`Contao\News::generateFeed` und `Contao\News::generateFeedsByArchive` machen es falsch. `Contao\News::generateFeeds` macht's richtig.

**Comment by leofeyer** [comment]
Ich kann das Problem noch immer nicht reproduzieren. Folgendes habe ich gemacht:

1. Ein News-Feed anlegen und darin "Ganze Beiträge" auswählen -> XML-Datei korrekt, HTML von `<![CDATA[` umschlossen und ohne Entities.

2. Einen News-Beitrag auf unsichtbar schalten -> der Feed wird aktualisiert, allerdings ist das HTML weiterhin von `<![CDATA[` umschlossen und ohne Entities.

3. Systemwartung -> XML-Dateien neu schreiben -> der Feed wird aktualisiert, das HTML ist weiterhin von `<![CDATA[` umschlossen und ohne Entities.

Wie genau kann ich das Problem also in einer aktuellen Contao 4.9er-Version mit der COD reproduzieren?

**Comment by Funbug** [comment]
Schau JETZT mal https://demo.contao.org/share/test.xml an.

- Neuen RSS-Feed anlegen
  - Ganze Beiträge
- RSS-Feed im Theme einbinden
- z.B. in der ersten News an der ersten Stelle ein HTML-Inhaltselement einfügen
  - z.B. `<div class="test">test</div>`
  - Speichern und Schließen
  - Element unsichtbar stellen
  - Element sichtbar stellen

Ergebnis in der text.xml:
`<pre>&lt;div class=&quot;test&quot;&gt;test&lt;/div&gt;</pre>`

Wenn du's nicht nachstellen kannst, ruf mich gerne kurz an 07231 3979640 und ich zeigs dir per TeamViewer in der COD.

**Comment by ausi** [comment]
@Funbug der Fehler betrifft nur das HTML-Inhaltselement? Alle anderen Inhaltselemente die HTML-Code enthalten funktionieren?

Wenn dem so ist, liegt der Fehler vermutlich an folgenden Code-Zeilen: https://github.com/contao/contao/blob/2560349f1985eae6eb69da4f2eeb9a3ad6e4f37a/core-bundle/src/Resources/contao/elements/ContentHtml.php#L31-L38

Dort wird das Element anders ausgegeben abhängig davon ob man sich im Backend befindet oder nicht.

**Comment by Funbug** [comment]
Ja. Das wird's wohl sein.

**Comment by leofeyer** [comment]
Ich konnte das Problem nun reproduzieren. Es ist dasselbe Problem, das wir schon öfters diskutiert haben (z.B. in contao/core#7587) und für das wir bisher noch keine vernünftige Lösung gefunden haben. Ich habe das Ticket daher mal auf "up for discussion" gesetzt.

**Comment by leofeyer** [comment]
Wie am 27. August auf Mumble besprochen, sollten wir `TL_MODE` durch den Scope-Matcher ersetzen, damit wir den Scope entsprechend setzen können.
