### ISSUE TITLE
Default working path while running contao-console

### ISSUE THREAD

**Issue by spotbot2k** [contao/contao#119]
**Affected version(s)**
contao/manager-bundle 4.4.26
php 7.2.7 and 7.2.10

**Description**  

- `contao-console` does not test, if the current working directory == contao project directory
- Current working path is default for execution and not the current project path

While I was trying to set the password for app_dev.php by running 

`sudo -u www-data ../vendor/bin/contao-console contao:install-web-dir --user=lamp --password`

the second web directory was created inside the original, so the new app_dev.php was saved into web/web/app_dev.php. While it is arguably correct, useful in some cases and might be avoided when using path argument a small warning, interaction or a hint (e.g. showing absolute path in the output) would be nice to avoid confusion. IMHO setting default to the current project path is a more correct way for this utility, as it is always dependant on installation and not really meant to be used globally.

This "issue" was reproduced on a test server with just contao and official demo installed, as well as a project I'm working on.

**How to reproduce**  
Run `contao-console contao:install-web-dir` from outside of the contao project directory without the `path` argument

**Comment by spotbot2k** [comment]
Ich habe da selbst [versucht einen weg zu finden](https://github.com/spotbot2k/contao/commit/7b801c9215747af303b8b62d5fca52f9d1ea292b#diff-36267bc77d2718a6fe1d3874ed888294), bin aber nicht glücklich damit - einerseits ist der kernel so weit ich weis im `configure` noch nicht erreichbar, andererseits ist die Logik für die Variablen in `interact`, und da könnte man es setzen, ist ja aber keine Interaktion...

**Comment by ausi** [comment]
Ich denke man kann sich `%kernel.project_dir%` über die services config injecten lassen:

```yml
contao.command.install-web-dir:
    class: Contao\ManagerBundle\Command\InstallWebDirCommand
    calls:
        - [setProjectDir, ["%kernel.project_dir%"]]
```

**Comment by Toflar** [comment]
Jup, wir sollten das `project_dir` nutzen.

**Comment by spotbot2k** [comment]
> Ich denke man kann sich `%kernel.project_dir%` über die services config injecten lassen:
> 
> ```yaml
> contao.command.install-web-dir:
>     class: Contao\ManagerBundle\Command\InstallWebDirCommand
>     calls:
>         - [setProjectDir, ["%kernel.project_dir%"]]
> ```

Ist definitiv besser als über getContainer(), aber `setProjectDir` wird trotzdem erst nach `configure` aufgerufen, oder liege ich da falsch?

**Comment by Toflar** [comment]
Wenn es ein Service ist, können wir auch einfach Constructor-Injection nutzen, das ist kein Problem.

**Comment by ausi** [comment]
Vermutlich sollten wir beide parameter nutzen: `kernel.project_dir` für die .env Datei und `contao.web_dir` für das web zeug...

**Comment by leofeyer** [comment]
Ich hätte jetzt einfach einen Check eingebaut, ob das Skript aus dem Root-Verzeichnis heraus ausgeführt wird. Das ist auch im Hinblick auf die Install- und Symlinks-Commands best practice.

**Comment by spotbot2k** [comment]
> Ich hätte jetzt einfach einen Check eingebaut, ob das Skript aus dem Root-Verzeichnis heraus ausgeführt wird. Das ist auch im Hinblick auf die Install- und Symlinks-Commands best practice.

Aber bitte kein Exception, weil es gibt schon Szenarien wo man es von außerhalb aufrufen muss

**Comment by spotbot2k** [comment]
Würde es ggf. sinnvoll sein den Benutzer zu warnen/fragen? Wie man es vom composer kennt - 

`No composer.json in current directory, do you want to use the one at %s`

So behält man die Flexibilität, und vermeidet Fehler gleichzeitig. [probe](https://github.com/spotbot2k/contao/blob/master/manager-bundle/src/Command/InstallWebDirCommand.php)

**Comment by leofeyer** [comment]
Behoben in 85966ffaf2a231a4590e1648ef12910ab2a3f7a6. Die weiteren Optimierungen hinsichtlich Constructor Injection kommen im nächsten Commit.
