### ISSUE TITLE
"magic keys" Details abändern

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1192]
siehe https://github.com/contao/contao/blob/1d68530e7899b6b2880cea5f9fa6fce0a9f9a3f3/core-bundle/src/Resources/contao/modules/ModulePersonalData.php#L377-L378

Für Contao 5 könnte man überlegen, das `Details` auf `_details` zu ändern um analog zu `_legend` arbeiten

**Comment by leofeyer** [comment]
I‘m not sure if the snake case notation is better, but we should definitely change `personalData` to `personalDetails`, so we don‘t have to check the key anymore (see #4760).
