### ISSUE TITLE
Errors in the list of countries

### ISSUE THREAD

**Issue by DissCent** [contao/contao#12]
**Affected version(s)**

All until now.

**Description**  

Contao stores a list of countries across the world (https://github.com/contao/core-bundle/blob/master/src/Resources/contao/config/countries.php) in a PHP array, which also gets translated into different languages (e.g. the German version https://github.com/contao/core-bundle/blob/master/src/Resources/contao/languages/de/countries.xlf).

Including this country list into a contact form, the list shows some entries which don't really make sense. Just to name some:

 - "Clipperton Island" is an island, not a country (managed by France; completely unpopulated)
 - "Diego Garcia" is an atoll, not a country (part of British territory in the Indian ocean)
 - The German translation contains an entry "Isle of", which misses the last word "Man"
 - "Congo-Brazzaville" should rather be "Republic of the Congo" (https://en.wikipedia.org/wiki/Republic_of_the_Congo)
 - "Kongo-Kinshasa" should rather be "Democratic Republic of the Congo" (https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo)

Maybe using the country list by the Universal Postal Union (http://www.upu.int/en/the-upu/member-countries.html) or some other standardized list could be used as a better source?

**Comment by leofeyer** [comment]
Fixed in e44f73009e1aba02e260da7f35eb1b7b004c6089.

I have seen that Symfony also uses e.g. "Diego Garcia" in their [intl component](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Intl/Resources/data/locales/fr.json#L117). Maybe you should report it there as well?

**Comment by DissCent** [comment]
Thank you! I will have a look at this.

Can you please edit https://github.com/contao/core-bundle/blob/master/src/Resources/contao/languages/de/countries.xlf as well to fix the missing "Man" in "Isle of Man"?

**Comment by fritzmg** [comment]
@DissCent this is probably handled on transifex.

**Comment by leofeyer** [comment]
Correct.

**Comment by DissCent** [comment]
@leofeyer Okay, I have submitted a request for joining the translation team in order to submit the change.

**Comment by leofeyer** [comment]
I have already fixed it. It will be part of the next release.

**Comment by DissCent** [comment]
Thank you!
