### ISSUE TITLE
Interne Weiterleitung bleibt nach Umstellung auf Reguläre Seite bestehen

### ISSUE THREAD

**Issue by falkgeist** [contao/contao#120]
**Affected version(s)**
4.4.26 ( -> Update lieferte erstmal nichts neueres)

**Description**  
Ich habe (wie im unten beschriebenen Problem) eine reguläre Seite erstellt, daraus eine interne Weiterleitung gemacht, dann wieder eine reguläre Seite.
Leider scheint es in dem unter dem Link beschriebenen Problem daran zu liegen, dass eine Zahl als Alias gewählt bzw. automatisch erstellt wurde. In meinem Fall ist dies nicht gegeben.

Folgende Seite wirft dass Problem aus:
http://recker.wueins.de/neuigkeiten.html
Diese war verlinkt auf /neuigkeiten/uebersicht.html (eine Unterseite, die ich nach Umstellung der Neuigkeiten-Seite (parent) auf "Reguläre Seite" wieder gelöscht habe).

Was äußert seltsam ist: Ich habe die Seite probeweise zwischendurch wieder auf "Interne Weiterleitung" gestellt, auf /start.html verlinkt. Jetzt wird anscheinend automatisch auf /start/uebersicht.html weitergeleitet, auch wenn diese Seite nie existiert hat.
Also ist anscheinend irgendwo "uebersicht.html" noch in einer Datei als Weiterleitung angegeben.
Diese Vermutung verfestigt sich bei mir auch dadurch, das die Weiterleitung auch nach Löschung und Neuerstellung der Neuigkeiten-Seite weiterhin besteht.

Ich habe auch bereits die .htaccess überprüft, dort liegen keine Weiterleitungen vor, ist so jungfräulich wie nach der Installation.

Ich bin zwar inzwischen halbwegs geübt mit dem Umgang mit Contao, aber ich habe keinen Schimmer, wo die Wurzel dieses Problems liegen könnte.

Übrigens habe ich den Cache bereits mehrfach (sowohl im Manager als auch im BE als auch im Browser) erneuert.

Ich schaue es mir morgen nochmal genauer an und versuche es in der Demo zu reproduzieren, aber ich bin gerade etwas ratlos.

Auch wundert mich, dass durch das Aktualisieren im Manager die Version von Contao nicht upgedatet wurde, ist 4.4.26 die neueste (stabile) Version??

Ähnliches Problem:
[https://community.contao.org/de/showthread.php?71238-Regul%C3%A4re-gt-Interne-Weiterleit-gt-Regul%C3%A4re-quot-The-server-returned-a-quot-404-Not-Found-quot-quot&highlight=interne+weiterleitung](url)

**How to reproduce**  
Konnte es bisher nicht in der Contao Demo reproduzieren (evtl. in Contao 4.5.x behoben?)...

**Comment by tophcodes** [comment]
Das Problem wird vermutlich lokal sein, zumindest tritt es bei mir nicht auf.

Ich vermute, dass du als Weiterleitungstyp "301 Permanent Redirect" ausgewählt hast, sodass die Weiterleitung auf die Unterseite "/uebersicht.html" von deinem Browser gecached wird. Wenn du deinen Redirect Cache leerst oder es an einem anderen Computer versuchst sollte es gehen.

**Comment by fritzmg** [comment]
@Falkgeist die Seite funktioniert einwandfrei. 301 Redirects werden vom Browser gecached ("_Permanent_ Redirect").

**Comment by falkgeist** [comment]
Pff, tja, ihr habt Recht, da habe ich an der falschen Stelle gesucht. Werde um permanente Redirects jetzt während der Entwicklung einen Bogen machen. (...und ich dachte, ich hätte den entsprechenden Eintrag im Browsercache gelöscht, war aber wohl nicht so.)

Danke!
