### ISSUE TITLE
Sortierreihenfolge beim Navigationspunkt «Inhalte»

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#1205]
Früher war die Reihenfolge nach der Gewichtung, jetzt ist die Bundle-Reihenfolge ausschlaggebend.

Würde eine alphabetische Reihenfolge nicht für mehr Klarheit sorgen?

**Contao 4.8**
![content48](https://user-images.githubusercontent.com/1942550/72606957-e8291f80-391f-11ea-9a58-e7b830d6da9a.png)

**Contao 4.9**
![content49](https://user-images.githubusercontent.com/1942550/72607000-fecf7680-391f-11ea-99ec-ef720d5ee3ea.png)

**Comment by Toflar** [comment]
Die Reihenfolge kann nie deterministisch bestimmt werden. Einzig eine alphabetische Sortierung würde aus UX funktionieren. Sollten wir imho tun @contao/developers

**Comment by leofeyer** [comment]
Wie am 13. Februar auf Mumble besprochen, wollen wir die Menüpunkte, die [$user->navigation()](https://github.com/contao/contao/blob/68b47c6ccab103c8fd205bc1c9a7f105c293d86b/core-bundle/src/EventListener/Menu/BackendMenuListener.php#L85) zurück gibt, alphabetisch sortieren. Anschließend kann bei Bedarf mittels Event Listenern die Reihenfolge angepasst werden.
