### ISSUE TITLE
Newsletter: Abonnenten-Import überspringt 1. Zeile

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#1206]
Beim CSV-Import von Abonnenten im Newsletter wird die 1. Zeile immer als ungültig zurückgewiesen. Damit ich trotzdem alle Adressen reinbekomme, mache ich die 1. Zeile als Leerzeile. Dann ist wenigstens nur die Leerzeile ungültig.

**Comment by leofeyer** [comment]
Die erste Zeile enthält bei einer CSV-Datei normalerweise die Feldnamen (siehe https://de.wikipedia.org/wiki/CSV_(Dateiformat)#Beispiel).
