### ISSUE TITLE
TinyMCE: Geschützte Leerzeichen werden ungewollt eingefügt

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#1207]
Beim TinyMCE werden insbesondere nach Listen (ul) Leerzeilen eingefügt:

```html
<p>[nbsp]</p>
<p>& nbsp;</p>
```

Die bekommt man nur raus, wenn man die Zeilen in der HTML-Ansicht rauswirft. Bearbeitet man später wieder das Element ohne HTML-Ansicht, sind diese Leerzeilen wieder drin. Das Phänomen tritt in der 4.8 an allen möglichen Stellen auf, wo der TinyMCE eingesetzt wird, z.B. Nachrichten-Teaser, leere Text-Elemente.

**Comment by aschempp** [comment]
Welche Contao Version verwendest du? Das sollte in neueren Versionen behoben sein. 

/cc @ausi

**Comment by Samson1964** [comment]
Aktuell 4.8.7. Wenn das nicht die neueste ist, muß ich aktualisieren.

**Comment by ausi** [comment]
Ich kann das Problem weder mit Firefox noch mit Chrome reproduzieren.

Welchen Browser in welcher Version hast du verwendet?  
Lässt sich das Problem auf <https://demo.contao.org/> reproduzieren, falls ja wie sind die genauen Schritte?

**Comment by Samson1964** [comment]
Online-Demo mit Firefox:

1. Eine der Nachrichten öffnen und z.B. ein Inhaltselement Text bearbeiten
2. ENTER hinter dem Text drücken, ein neuer Abschnitt erscheint
3. Abschnitt wieder löschen und Speichern
4. Nun erscheint ein neuer Abschnitt mit [nbsp]
5. Nun wieder Speichern klicken
6. Es erscheint wieder ein neuer Abschnitt mit [nbsp] usw. usf.

Dieses Verhalten tritt seit 4.8.x bei allen Formularelementen mit TinyMCE auf. Die Leerzeilen/abschnitte lassen sich nur in der HTML-Ansicht entfernen, tauchen aber bei Bearbeitung im WYSIWYG-Modus immer wieder auf.

**Comment by fritzmg** [comment]
I am unable to reproduce this with FireFox 72.0.2 on Windows 10 Pro x64.

**Comment by Samson1964** [comment]
Bei mir auch FireFox 72.0.2 (64 Bit) mit Windows 10 Pro x64

**Comment by de-es** [comment]
Es geht auch einfach (in der Demo) mit dem Einfügen eines leeren Absatzes mit ENTER und speichern. TinyMCE fügt den neuen Absatz als `<p>&nbsp;</p>` ein, Contao macht beim Speichern ein `<p>[nbsp]</p>` daraus. Konnte mit diversen Browsern (Win/Linux) keinen Unterschied im Ergebnis feststellen.

**Comment by fritzmg** [comment]
@de-es das ist soweit ich weiß normal. _Absichtlich_ generierte leere Absätze werden immer mit dem non-breaking space befüllt.

**Comment by de-es** [comment]
Ok, das hatte ich mir schon fast gedacht. Ich lösche die immer automatisch per Callback, da viele "Freizeitredakteure" mit dem nbsp nichts anfangen können und sich sonst fragen, wo das herkommt. :-)

**Comment by Samson1964** [comment]
Ich füge keine leeren Absätze wissentlich ein. Die sind einfach da. Nach jedem Speichern wird ein neuer Absatz eingefügt. Es fängt immer mit `<p>&nbsp;</p>` an, gefolgt von `<p>[nbsp]</p>` und nach jedem Speichern kommt ein `<p>[nbsp]</p>` hinzu.
Ich habe auch leere Textelemente in meiner Installation, die ich per SQL eingefügt habe. Da ist im Text selbst absolut nichts drin. Jedenfalls früher. Wenn ich jetzt so ein Element aufmache, steht von hause aus `<p>&nbsp;</p><p>[nbsp]</p>` immer drin. Das wird also von Contao neuerdings automatisch eingefügt.

**Comment by asaage** [comment]
Ich denke, das war schon immer so.
1. leere Textelemente kannst du nicht speichern TinyMCE macht daraus automatisch ein ```<p>&nbsp;</p>``` wenn das wieder geladen wird wird daraus ein  ```<p>[nbsp]</p>```
2. machst du copy&paste aus Word&Co. werden Leerzeilen zu Leer-Absätzen (Ich find jedenfalls selten mal ein Worddokument mit manuellen Zeilenumbrüchen.
3. Ich trichter meinen Redakteuren permanent den Unterschied zwischen ```Enter``` und ```Shift+Enter``` ein aber da das css, welches Contao in den Tiny lädt keinen Abstand zwischen den Absätzen hat wird das sogut wie immer Ignoriert. 
4. Gibt's eine Liste und der Redakteur kommt nicht damit klar, dass der Cursor hinter dem letzten Buchstaben stehen bleibt - wird auch gern mal ein leerer Absatz manuell hinzugefügt.

**Comment by fritzmg** [comment]
@asaage das ist aber nicht das, was @Samson1964 meint.

**Comment by asaage** [comment]
ja
- dass insbesondere nach Listen (ul) Leerzeilen eingefügt werden
- oder sich Leerzeilen durch speichern vervielfältigen

kann ich so jedenfalls nicht nachstellen.

**Comment by Samson1964** [comment]
Es ist generell so, daß `<p>&nbsp;</p><p>[nbsp]</p>` überall eingefügt wird, wo der TinyMCE im Einsatz ist. Man bekommt das nur weg, indem man im Quelltext diese Zeichenfolge rauswirft und dann sofort speichert. Arbeitet man nicht mit dem Quelltext und löscht die Zeichenfolge im WYSIWYG-Modus läßt der TinyMCE offensichtlich ein `<p>&nbsp;</p>` drin. Im WYSIWYG-Modus kommt man aber mit dem Cursor nicht in diesen leeren Absatz - da ist nichts. Speichert man nun, steht wieder  `<p>&nbsp;</p><p>[nbsp]</p>` drin. Speichert man nochmal steht  `<p>&nbsp;</p><p>[nbsp]</p><p>[nbsp]</p>` drin. Usw. usf.

**Comment by ausi** [comment]
@Samson1964 kannst du bitte testen ob der Fehler bei dir auch im Chrome-Browser auf demo.contao.org auftritt?
Und im Firefox bitte einmal im Inkognito-Modus (Neues privates Fenster) testen.

**Comment by Samson1964** [comment]
Bingo. Firefox im privaten Modus und Chrome ist alles in Ordnung.

**Comment by ausi** [comment]
Eventuell liegt es an einer Erweiterung im Firefox die im privaten Modus nicht aktiv ist, oder am Browser-Cache.

**Comment by Samson1964** [comment]
Danke, das war es! Als ich Cisco Webex, Empty Cache Button und OpenVideo deinstalliert habe, war der Spuk vorbei. Eine von diesen drei Erweiterungen war also schuld. Ich tippe auf OpenVideo, weil ich die erst vor ein paar Wochen hinzugefügt habe.
Sorry nochmal, das ich das als einen Bug in Contao/TinyMCE angesehen hatte.
