### ISSUE TITLE
create new public folder but it isn't public 

### ISSUE THREAD

**Issue by Ainschy** [contao/contao#1208]
**dev-master / 4.9 RC1**

**new root folder are not public by default**
if create a new root folder by file manager with option public this folder will create without public flag. After edit the folder and set public checkbox again then the folder is public.

testet on Windows 10 pro, Lavagon Stack, php 7.2.17

**Comment by fritzmg** [comment]
I can confirm the issue.

**Comment by frontendschlampe** [comment]
I can confirm the issue, too.

**Comment by leofeyer** [comment]
See #1282
