### ISSUE TITLE
scope für Eventlistener (service-tags) in Verbindung mit dem "Personendaten"-Modul schlägt fehl

### ISSUE THREAD

**Issue by srhinow** [contao/contao#1216]
**Affected version(s)**
Contao 4.8.7

**Description**
Es fehlt eine Möglichkeit den scope beim service tagging (https://docs.contao.org/dev/framework/dca/#using-service-tagging) mit anzugeben?
Denn ich habe ein onSubmitCallback für die Member-Tabelle angelegt. Im Backend klappt es wie gewohnt auch. Jetzt ist mir im Frontend beim Ändern der Email-adresse ein Fehler vor die Füße gefallen. Da ich in der onSubmitCallback den DataContainer erwarte und im Frontend die Parameter object(FrontendUser) und object(ModulePersonalData) übergeben werden. 

Ist mir auch neu das im Frontend die Callbacks aufgerufen werden.

**How to reproduce**
in der services.yml 
```
 xxxxx\xxxxxx\EventListener\Dca\Member:
    public: true
    tags:
      - { name: 'contao.callback', table: 'tl_member', target: 'config.onsubmit', method: 'onSubmitCallback' }

```
und in der eigenen Member-EventListener-Class:

```
    public function onSubmitCallback(DataContainer $dc): void
    {
        $this->sendTokenEmail($dc);
    }
```
Wenn man dann im geschützten Frontendbereich ein "Personendaten" Modul anlegt wird ein Fehler geschmissen da die Übergabeparameter object(FrontendUser) und object(ModulePersonalData)  und nicht DataContainer ist.

**Comment by bytehead** [comment]
> Ist mir auch neu das im Frontend die Callbacks aufgerufen werden.

Das ist in 4.4 auch schon so (und wahrscheinlich auch in 3.x): https://github.com/contao/contao/blob/42a01480174f1d8672391e151db94ebd5d92809d/core-bundle/src/Resources/contao/modules/ModulePersonalData.php#L343-L357

Nur gab es da kein Service-Tagging wo dann PHP wegen typisierten Parametern ausruft :)

**Comment by fritzmg** [comment]
» https://github.com/contao/docs/pull/230

**Comment by richardhj** [comment]
Dies ist schon seit jeher so und kann in Contao 4 nicht geändert werden.
du kannst den ScopeMatcher verwenden oder auch `$dc instanceof DataContainer`.

**Comment by srhinow** [comment]
> Dies ist schon seit jeher so und kann in Contao 4 nicht geändert werden.
> du kannst den ScopeMatcher verwenden oder auch `$dc instanceof DataContainer`.

@richardhj kannst du das bitte noch mal für Dumme beschreiben. Wie kann ich das jetzt bei meiner Situation anders schreiben das es passt? Wie soll ich denn schon in der services.yml nen Scope zuweisen? Wenn ich es in der Methode behandele, ist es ja schon zu spät da der Methoden-Parameter nicht stimmt und schon in dem Moment ne Exception wirft.

zu "...Dies ist schon seit jeher so ..." könnte man denn nicht in den tag-Paramtern nen scope mit übergeben und dann dies in den jeweiligen Callback-Calls abfangen? Dann ist es doch auch rückwert kompatibel.

**Comment by fritzmg** [comment]
@srhinow du darfst keinen PHP 7 parameter type bei deiner Funktion angeben, weil je nach Context der Typ des Parameters dieses Callbacks anders sein kann. Innerhalb deines Callbacks kannst du dann mit `instanceof` abfragen, was du dann tatsächlich bekommen hast.

**Comment by srhinow** [comment]
jup @fritzmg deine Antwort hat geholfen. 

Ich finde aber trotzdem das man in den "services tags" nen scope als Paramter mit aufnehmen könnte und im jeweiligen Callback zukünftig drauf reagiert je nach Scope. Mein Fall ist aktuell zwar exotisch aber wenn Contao sich weiter so entwickelt und sich Symfony anpasst und mehr als bundle als nur als reines CMS versteht, schätze ich mal das es nicht das letzte mal sein wird wo es vor die Füße fällt.

**Comment by aschempp** [comment]
Services haben nichts mit dem Request Scope zu tun, und Callbacks/Hooks auch nicht. Genau so wenig wie man einem Symfony Event Listener einen Scope taggen kann. Es ist einfach ein Fehler der Doku, welcher Fritz schon behoben hat 😊

**Comment by Tastaturberuf** [comment]
Geht nicht einfach das zu nullablen und dann zu prüfen? Hatte mir der @Toflar mal irgendwo so genannt. (Das wird nen Running-Gag :-) ) 
```php
public function onSubmitCallback(DataContainer $dc = null): void
{
    if ( null === $dc)
   {
        return;
    }
    // something else
}
```

**Comment by bytehead** [comment]
Nein, wenn da ein String daherkommt, knallts.

Am besten machst du was wie `onSubmitCallback(...$arguments): void` und prüfst dann innerhalb der Methode das Array `$arguments` auf Datentypen.

**Comment by Tastaturberuf** [comment]
Wer schickt denn da nen String mit? Ich kenne bisher nur Callbacks die keinen DC liefern. Aber "falsche" Typen sind mir noch nicht begegnet.

**Comment by bytehead** [comment]
Im Frontend kommt z.B. als erstes Argument ein Objekt vom Typ `User` mit.

**Comment by srhinow** [comment]
sorum wie ich es jetzt mit @bytehead Vorschlag umgesetzt habe, das ich den Argument-Type DataContainer weglasse bekomme ich im Frontend keinen Fehler mehr. Aber was ist wenn es anders herum gebraucht wird? Sprich das man es im Frontend benötigt 2 Argumente übergibt ... das mosert er im Backend bestimmt rum das er ja nur 1 Argument (DataContainer) erwartet aber gleich 2 Argumente geleifert bekommt.

**Comment by fritzmg** [comment]
Du musst halt `= null` verwenden. Oder so wie @bytehead es beschrieben hat.

**Comment by bytehead** [comment]
Du kriegst in dem Fall die Argumente im Array `$arguments`:
Backend:
```
[
	0 => $dc
]
```

Frontend:
```
[
	0 => $user,
    1 => $module
]
```

und mit `$arguments[0] instanceof DataContainer` kannst du das z.B. überprüfen.

**Comment by bytehead** [comment]
http://docs.php.net/manual/en/functions.arguments.php#functions.variable-arg-list

**Comment by srhinow** [comment]
das mit den drei Punkten kannte ich noch gar nicht. Dachte ddie ganze Zeit das du dein beispiel einfach nur vereinfacht schreiben wilst ;)

Wir könne gerne hier schluss machen -> hat sich ja jetzt erledigt. Danke an alle die mit drüber geschaut haben.

**Comment by bytehead** [comment]
Nene, PHP 5.6 Feature 😎
