### ISSUE TITLE
Versions broken when using Doctrine Schema Representation to define DCA's sql

### ISSUE THREAD

**Issue by fiedsch** [contao/contao#1219]
**Affected version(s)**

Contao 4.8.7 

**Description**

When comparing old and new version of a record while debug mode is switched on I get:

```
Warning: strncmp() expects parameter 1 to be string, array given
Exception Logs 1 Stack Trace
ErrorException
in vendor/contao/core-bundle/src/Resources/contao/classes/Versions.php (line 508)
```

It however works when debug mode is switched off.

**How to reproduce**

Define a DCA field using Doctrine Schema Representation as described [in the documentation](https://docs.contao.org/dev/reference/dca/fields/#sql-column-definition), e.g.:

```
             'sql'       => ['type' => 'string', 'length' => 255, 'default' => ''],
```
instead of 
```
             'sql'       => "VARCHAR(255) NOT NULL default ''",
```

create a new version of such a record and click the compare icon with debug mode switched on.

Cause is probably the `DCAExtractor` which uses

```
$this->arrFields[$field] = $config['sql'];
```
and thus creating an array entry as opposed to the expected string entry.

**Comment by aschempp** [comment]
siehe https://github.com/contao/contao/pull/1251
