### ISSUE TITLE
Asset loading fails for domains with underscores

### ISSUE THREAD

**Issue by m-vo** [contao/contao#1220]
**Affected versions**
At least current master / 4.9. Probably all.

**How to reproduce**
* create a domain with underscores in the name (which is [perfectly legal](https://stackoverflow.com/a/2183140/3146819) btw): 
e.g. `_a.domain.wip`
* open the Contao backend & look at the browser's network tab
* &rarr; the underscore is missing in the asset urls thus failing to load them

![underscore_domain](https://user-images.githubusercontent.com/5305677/72715903-a2639580-3b71-11ea-8de2-9a1e46643b62.png)

**Comment by aschempp** [comment]
can you debug who's generating the incorrect URL? This could be a bug in Symfony Asset

**Comment by m-vo** [comment]
Had a quick look at it. The backend templates sets `Environment::get('base')` which already contains the wrong url.

It's actually caused by this regex in the `Environment` class that removes the underscore from the `host` key:

https://github.com/contao/contao/blob/f1266ecd44dfb9cd40bffc1b6f0b3d151c7c0528/core-bundle/src/Resources/contao/library/Contao/Environment.php#L299

What's this regex for btw? It's in there all along. :smile:

**Comment by leofeyer** [comment]
See #1266.
