### ISSUE TITLE
FE preview redirect for pages inconsistent

### ISSUE THREAD

**Issue by Toflar** [contao/contao#1224]
**Affected version(s)**

4.9 RC1

**Description**

The FE preview URL when clicking on the icon in the page tree looks as follows: `/contao?do=feRedirect&page=299`. That looks like the old format because when you edit a page and click on preview, you get to `/contao/preview?page=299`.
This should be unified. Imho the `do=feRedirect` is the old way and can be replaced.

**Comment by leofeyer** [comment]
You are right that we do not need `do=feRedirect` in the page structure. 👍 

It seems that the only purpose of `do=feRedirect` is to trigger `Controller::redirectToFrontendPage()`, which additionally adds the `/articles/` fragment to the URL. (Which is also why `do=feRedirect` is only used in `tl_article.php`.)

Maybe we should deprecate `do=feRedirect` altogether?

**Comment by Toflar** [comment]
> Maybe we should deprecate `do=feRedirect` altogether?

I guess we should yes.



> (Which is also why `do=feRedirect` is only used in `tl_article.php`.)

No, it's also used in `tl_page` or actually in `Backend::addPageIcon()`.

**Comment by leofeyer** [comment]
Yes, but it is wrong there and needs to be removed.

**Comment by leofeyer** [comment]
See #1286.
