### ISSUE TITLE
Replace the less.php dependency

### ISSUE THREAD

**Issue by andreheeke** [contao/contao#1226]
**Affected version(s)**
4.8.7 | 4.9.0-RC1

**Description**
The repository [oyejorge/less.php](https://github.com/oyejorge/less.php) has been archived by the owner. We should replace this with another package. Alternatively, [leafo/lessphp](https://github.com/leafo/lessphp) could be considered.

**Comment by leofeyer** [comment]
According to the [README](https://github.com/oyejorge/less.php/blob/master/README.md), the "official" successor is [wikimedia/less.php](https://github.com/wikimedia/less.php).

I am not sure whether [leafo/lessphp](https://github.com/leafo/lessphp) is still maintained or will continued to be maintained in the future, given that [leafo/scssphp](https://github.com/leafo/scssphp) has already been archived.

**Comment by andreheeke** [comment]
You're right. I didn't read it in that much detail. I was only aware of this alternative.
We should use the Wikimedia fork as described in the README.

**Comment by leofeyer** [comment]
See #1283
