### ISSUE TITLE
Upload per Dropzone funktioniert nicht mehr (4.9.0-RC1)

### ISSUE THREAD

**Issue by LinkingYou** [contao/contao#1229]
**Affected version(s)**
(4.9.0-RC1)

**Description**
Der Upload per Dropzone im Backend funktioniert nicht mehr. Auf der Console bekomme ich von der Dropzone den Fehler "No URL provided."

Lt. Doku von Dropzone https://www.dropzonejs.com/#usage, muss die Option "url" gesetzt sein, wenn kein Form-Tag mit Action-Attribute vorhanden ist. In Contao 4.8 war dort noch ein Action-Attribute vorhanden, dass jetzt in der 4.9 fehlt.

Zum Testen habe ich den url-Parameter hinzugefügt (mit der aktuellen URL).

Zusätzlich zum vorhandenen Code

```
    window.addEvent("domready", function() {
      new Dropzone("#tl_files", {
        paramName: "' . $this->strName . '",
        maxFilesize: ' . $intMaxSize . ',
          ...
      })
```
habe ich die "url" ergänzt.

```
    window.addEvent("domready", function() {
      new Dropzone("#tl_files", {
        url: window.location.href,
        paramName: "' . $this->strName . '",
        maxFilesize: ' . $intMaxSize . ',
          ...
      })
```

Damit funktioniert der Upload per Dropzone bei mir wieder.

Bug? Oder habe ich hier ein "seltsames" Setup (das eigentlich ziemlich blanko ist)? 

**How to reproduce**
Im Backend unter **Dateiverwaltung** den Punkt **Dateiupload** anklicken und beliebigen Ordner auswählen. Dann versuchen, per Drag-and-Drop Dateien hochzuladen.

**Comment by planepix** [comment]
Kann ich bestätigen. Auch die Darstellung ist anders.
Klick in die Fläche bleibt ohne Funktion.
![Dateiverwaltung-4 9-RC-1](https://user-images.githubusercontent.com/1823889/72848196-5d8c4b80-3ca4-11ea-983d-938f5c0bde2b.png)

**Comment by bytehead** [comment]
Wahrscheinlich hängt das mit der (nun fehlenden) Form action zusammen, die in #1170 entfernt wurde.

**Comment by leofeyer** [comment]
Siehe #1232
