### ISSUE TITLE
Auswahl der Weiterleitungsseite bei Modulen wird nicht übernommen (4.9.0-RC1)

### ISSUE THREAD

**Issue by LinkingYou** [contao/contao#1231]
**Affected version(s)**
4.9.0-RC1

**Description**
Beim klick auf "Anwenden" erhalte ich von mootools.min.js:

`Cannot read property 'getParent' of undefined`

![image](https://user-images.githubusercontent.com/23259908/72874980-94d61900-3cf3-11ea-84b2-99a9ad39f0ba.png)

**How to reproduce**
Im Backend Themes / Frontend-Module bearbeiten / Modul bearbeiten (z.B. ein Modul "Suchmaschine"):
Dort dann bei Weiterleitungsseite den Button "Auswahl ändern" klicken. Im Picker dann beliebige Seite auswählen und mit "Anwenden" bestätigen. In der Console erscheint dann der angegebene Fehler und die Auswahl wird nicht übernommen.

**Comment by fritzmg** [comment]
Duplicate of #1214
