### ISSUE TITLE
Invalid value of @context

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1236]
<img width="745" alt="" src="https://user-images.githubusercontent.com/1192057/72912252-a7744080-3d3b-11ea-97b4-7c8c0445d7ed.png">

To fix this, we either have to define the context inline

```
{
  "@context": {
    "name": "http://schema.org/name",
    "image": {
      "@id": "http://schema.org/image",
      "@type": "@id"
    },
    "homepage": {
      "@id": "http://schema.org/url",
      "@type": "@id"
    }
  },
  "name": "Manu Sporny",
  "homepage": "http://manu.sporny.org/",
  "image": "http://manu.sporny.org/images/manu.png"
}
```

or link to a valid document which defines the context (e.g. https://json-ld.org/contexts/person.jsonld).

**Comment by leofeyer** [comment]
I am closing this in favor of #1250.

**Comment by plandolt** [comment]
Moving from `https://contao.org/` to `https://schema.contao.org/` has not made that any better regarding google search console.

![image](https://user-images.githubusercontent.com/922919/74910114-0ddf9380-53ba-11ea-919e-15f8161a47bd.png)

**Comment by plandolt** [comment]
I think its because of this:

> A context definition MUST be a map whose keys MUST be either terms, compact IRIs, IRIs, or one of the keywords @base, @import, @language, @propagate, @protected, @type, @version, or @vocab.

Found on https://w3c.github.io/json-ld-syntax/#context-definitions

**Comment by Toflar** [comment]
It doesn‘t need to be fixed. The search console is wrong. It seems like it just analyzes the things it knows and reports everything else as an error which is not the idea of JSON-LD.

**Comment by jochi44** [comment]
I just received an email from "Google Search Console Team" regarding the wrong type "@context" for a recently updated Contao 4.9-website.

I understand the point of @Toflar, you can't please every checking tool.
In this case it's not just "some tool", it's Google.
If users/webmasters of every updated Contao 4.9-site receive an email and the email says "Fehler können verhindern, dass Ihre Seite oder Funktion in den Suchergebnissen angezeigt wird." it will cause troubles. People won't understand the technical background of it.

IMHO there should be some kind of "solution" on this topic.

**Comment by Toflar** [comment]
Please, there's no point in commenting on this topic unless you actually know **how** it can be fixed. We'll happily fix it if anyone finds out how.

**Comment by bennyborn** [comment]
It may not be valid by definition but actually switching back the context to schema.org seems to fix the problem for Google.

![image](https://user-images.githubusercontent.com/226890/75449219-e4e87100-596c-11ea-81a5-bd9247efa029.png)

**Comment by Toflar** [comment]
Yeah, invalid output is marked as valid. Even better...

**Comment by asaage** [comment]
For me it seems very strange to have that kind of internal data publicly available on the page anyway 🤷🏼‍♂️

**Comment by aschempp** [comment]
> For me it seems very strange to have that kind of internal data publicly available on the page anyway 🤷🏼‍♂️

The definition of _internal_ for you seems to be whether its relevant for Google. However, it's relevant for other systems. Imagine an RSS feed on your page. It's not _relevant to the visitor_, but its relevant meta information about the page content. So the JSON-LD is very much relevant, because we (the Contao search engine) needs it to know about your page content.

**Comment by bennyborn** [comment]
>because we (the Contao search engine) needs it to know about your page content.

Would it be possible to add a special header like `X-Requested-With: Contao-Crawler` and the JSON-LD is only shown if that header is present? This way you could ignore the problems with Google completely.

**Comment by Toflar** [comment]
No, that would kill HTTP caching completely. I mean, we could vary on that header (not `X-Requested-With` but any custom one) but that would mean we have two entries for every single page.

**Comment by bennyborn** [comment]
Why two entries? Why not "disable" caching entirely if the crawler requests the pages?

**Comment by Toflar** [comment]
Because it would be nonsense? Why would I want to slow down crawling?
And again, it is **not** internal information. It is meta information that might be useful for everybody who wants to read information from Contao pages. It's just meta information and it's a great thing that there's machine readable data now.
I don't understand the problem, really.

What part of the JSON-LD bothers you and why? And please don't tell me "I don't like it" or "my gut feeling is that it's not a good idea". I want a technical, scientific reason. Everything else is irrelevant.

**Comment by bennyborn** [comment]
> What part of the JSON-LD bothers you and why? [...] I want a technical, scientific reason. Everything else is irrelevant.

The only thing bothering me is the current situation where the Google Search Console throws errors for no apparent reason and users are insecure if something is broken. I personally don't mind if the JSON is there or not ;)

**Comment by LIVID-Media** [comment]
To get back to the problem: As far as I can see, the context at schema.contao.org is wrong. Every property that could be used should be defined in the context. So far this is only the case for 'RegularPage' and 'preview'. The latter is not currently used in the JSON-LD, but rather 'fePreview'.

The problem with the Google test tool is that no foreign schema is definitely called. But maybe this works:

```json
{
  "@context": {
    "RegularPage": "http://schema.contao.org",
    "pageId": {
      "@id": "http://schema.contao.org/pageId",
      "@type": "xsd:integer"
    },
    "noSearch": {
      "@id": "http://schema.contao.org/noSearch",
      "@type": "xsd:boolean"
    },
    "protected": {
      "@id": "http://schema.contao.org/protected",
      "@type": "xsd:boolean"
    },
    "fePreview": {
      "@id": "http://schema.contao.org/fePreview",
      "@type": "xsd:boolean"
    }
  },
  "@type": "RegularPage",
  "pageId": 42,
  "noSearch": false,
  "protected": false,
  "fePreview": false
}
```

I have completely integrated the context area, but the individual properties should be stored under http://schema.contao.org. I couldn't find anything about the property 'group', so I left it out.

**Comment by ausi** [comment]
```html
<script type="application/ld+json">
{
	"@context": {"contao": "http://schema.contao.org/"}, 
    "@type": "contao:Page",
    "contao:pageId": 3,
    "contao:noSearch": false,
    "contao:protected": false,
    "contao:groups": [],
    "contao:fePreview": false
}
</script>
```

<img width="595" alt="Bildschirmfoto 2020-03-02 um 13 33 04" src="https://user-images.githubusercontent.com/367169/75676836-5e909f80-5c8a-11ea-8175-b5e806ca53c9.png">

**Comment by rustykowski** [comment]
still invalid – perhaps slashes should not be escaped?
In Contao 4.9.1 i get this @context values:
`"@context":"https:\/\/schema.contao.org\/"`

**Comment by fritzmg** [comment]
Contao 4.9.2 hasn't been released yet.

**Comment by operatorone** [comment]
Still invalid output in 4.13.38.

**Comment by fritzmg** [comment]
@operatorone what exactly do you mean?

**Comment by operatorone** [comment]
After validation a just updated page there is an error in the JSON, see https://validator.schema.org/?hl=en-US#url=https%3A%2F%2Fwww.haas-magnettechnik.com%2Fen%2F

Line 1092: `"@context": "https:\/\/schema.contao.org",`

Uncategorized Errors
This @context string is unknown to the parser and we do not support remote JSON-LD context fetching. Please use a known @context value (e.g. "https://schema.org/") or define a local context.

**Comment by bytehead** [comment]
Don't now if the schema.org tool just fails to check on https://schema.contao.org:

```
This @context string is unknown to the parser and we do not support remote JSON-LD context fetching
```

**Comment by fritzmg** [comment]
@operatorone that is an issue with the validator, not with Contao. See https://github.com/schemaorg/schemaorg/issues/2921

**Comment by ausi** [comment]
See https://github.com/contao/contao/issues/3555 and https://github.com/schemaorg/schemaorg/issues/2921#issuecomment-1692892440

**Comment by operatorone** [comment]
Thank you for providing clarification.

**Comment by Total-Reality** [comment]
Can change this in Contao please? It is clear, that schema.org won't change this in the next time. The issue there is open for more than 2 years.

**Comment by ausi** [comment]
> Can change this in Contao please?

What do you mean by that? What should we change in Contao?
