### ISSUE TITLE
Suche bei Artikel um ID für Inhaltselement erweitern

### ISSUE THREAD

**Issue by zonky2** [contao/contao#124]
**Description**  
Suche bei Artikel um ID für Inhaltselement erweitern

**Comment by leofeyer** [comment]
Warum? Kein normaler Benutzer kennt doch die ID von irgendeinem Inhaltselement. Was genau möchtest Du erreichen?

**Comment by zonky2** [comment]
wenn ich nach dem Inhaltslement suche, dessen ID ich aus "bezogenes Inhaltselement" habe oder von einem Inserttag... aktueller Weg ist dann Suche in der DB tl_content -> pid raus finden -> Artikel über Alias oder ID finden
