### ISSUE TITLE
Replace dependency zendframework/zend-code

### ISSUE THREAD

**Issue by jochi44** [contao/contao#1240]
**Affected version(s)**
4.9.0-RC1

**Description**
While updating the packages for V4.9.0-RC1 with the contao-manager the following message appears:

Package [zendframework/zend-code](https://github.com/zendframework/zend-code) is abandoned, you should avoid using it. Use [laminas/laminas-code](https://github.com/laminas/laminas-code) instead.

PS: This is my first issue-report on github. Hopefully I've done it the right way.

**Comment by m-vo** [comment]
It's not required by contao but by it's dependencies.

If you run `composer why zendframework/zend-code` (or `composer why zendframework/zend-code --tree` for a more verbose output) you'll see that it's actually `ocramius/proxy-manager` requiring the dependency.

**Comment by fritzmg** [comment]
iirc it's already changed in `ocramius/proxy-manager`, but the change has no stable release tag yet.
