### ISSUE TITLE
Replace dependancy zendframework/zend-eventmanager

### ISSUE THREAD

**Issue by jochi44** [contao/contao#1241]
**Affected version(s)**
4.9.0-RC1

**Description**
While updating the packages for V4.9.0-RC1 with the contao-manager the following message appears:

Package [zendframework/zend-eventmanager](https://github.com/zendframework/zend-eventmanager) is abandoned, you should avoid using it. Use [laminas/laminas-eventmanager](https://github.com/laminas/laminas-eventmanager) instead.

**Comment by m-vo** [comment]
see #1240
