### ISSUE TITLE
Darstellungsfehler des divs id=#paste_hint bei Neuanlage div. Elemente im Backend

### ISSUE THREAD

**Issue by jochi44** [contao/contao#1247]
**Affected versions:**
4.8.7 | 4.9.0-RC1

**Description:**
Wie von [aasage](https://github.com/asaage) in [diesem Issue](https://github.com/contao/contao/pull/467#issuecomment-489598953) angeführt, befindet sich bei der Anlage eines neuen Elements (im Backend), welches eine notwendige Positionierung des neuen Elements erfordert (z.B. neuer Artikel, neue Seite),  der Hinweistext "Legen Sie als Nächstes die (neue) Position des Elements fest" (=div #paste_hint) positionsmäßig HINTER der ersten Zeile des "listing containers".

![image](https://user-images.githubusercontent.com/60215157/72993426-a7d11200-3df5-11ea-95ee-a0f72bc723c2.png)

Ist zwar kein Weltungergang, könnte jedoch ggf. in der 4.9er-Version korrigiert werden.

**Comment by leofeyer** [comment]
Siehe #1284
