### ISSUE TITLE
Contao 4.9-RC1: Subpaletten öffnen nicht

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#1248]
Ich möchte eine Subpalette öffnen, z.B. Seitenlayouts > Seitenlayout bearbeiten > "jQuery laden" aktivieren, dann kommt das weiß-transparente Overlay mit dem Hinweis "Die Daten werden geladen ..." und das bleibt endlos stehen. In der Konsole kommt dann folgender Fehler:

`[Error] Failed to load resource: the server responded with a status of 404 () (null, line 0)`

@ainschy hat den Fehler ebenfalls

Ich habe PHP 7.3 und Ainschy PHP 7.2

In dem weißen Overlay ist jedoch der Button "Speichern und Schließen" nicht überlagert und so dass ich ihn betätigen kann. Wenn ich dann wieder das Layout bearbeite, ist jQuery auch aktiviert.

**Comment by planepix** [comment]
Liest sich das Problem: https://github.com/contao/contao/issues/1214

**Comment by frontendschlampe** [comment]
you're right :-)

**Comment by frontendschlampe** [comment]
Siehe #1225
