### ISSUE TITLE
4.9: Deaktivierung SERP-Vorschau

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#1249]
Könnte man darüber nachdenken, die SERP-Vorschau optional zu machen? Also separat über eine Einstellung in der `config.yml` oder so?!

Grund: Ich weiß genau, was der erste Kunde sagen wird, der das nutzt: Das sieht ja gar nicht genauso aus, wie bei Google! Warum nicht?

**Comment by fritzmg** [comment]
```php
// contao/dca/tl_page.php
use Contao\CoreBundle\DataContainer\PaletteManipulator;

PaletteManipulator::create()
    ->removeField('serpPreview')
    ->applyToPalette('regular', 'tl_page')
;
```

**Comment by frontendschlampe** [comment]
ja ... der Weg ist mir bekannt. Wollte nur wissen, ob man es ggfs. nicht grundsätzlich konfigurierbar machen könnte. ;-)

**Comment by fritzmg** [comment]
Naja, es gibt grundsätzlich keine DCA Felder in Contao, die konfigurierbar sind bisher, oder? Fände ich etwas seltsam jetzt plötzlich eines (und nur eines) konfigurierbar zu machen.

**Comment by frontendschlampe** [comment]
> Naja, es gibt grundsätzlich keine DCA Felder in Contao, die konfigurierbar sind bisher, oder? Fände ich etwas seltsam jetzt plötzlich eines (und nur eines) konfigurierbar zu machen.

Ja ... gebe ich Dir Recht.

Diese SERP-Vorschau ist halt ein "diskutierbares" Feature.

**Comment by m-vo** [comment]
Kannst du nicht einfach das Feld für die relevante Usergruppe entfernen? Das musst du ja sowieso für die meisten Felder machen.

**Comment by frontendschlampe** [comment]
> Kannst du nicht einfach das Feld für die relevante Usergruppe entfernen? Das musst du ja sowieso für die meisten Felder machen.

In den meisten Websites haben die User sowieso einen Admin-Zugang (ist ja ihre eigene Website), aber alles gut ... ich deaktiviere es einfach, wie @fritzmg vorgeschlagen hat.

**Comment by leofeyer** [comment]
Aber es sieht doch so aus wie bei Google?

**Comment by frontendschlampe** [comment]
> Aber es sieht doch so aus wie bei Google?

Ich denke nicht ... Google verwendet zur Zeit nicht die Beschreibung als Ergebnistext, sondern die Passagen, wo die Suchbegriffe vorkommen. Dann gibt's gerade tolle Favicons und nächste Woche gibt's bestimmt ganz tolle andere Sachen. ;-) Aber alles gut ...
