### ISSUE TITLE
IntlBreakIterator::getRules() does not exist

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#125]
**Affected version(s)**

4.6+

**Description**  

@ausi I wonder how this code has ever worked:

https://github.com/contao/contao/blob/4c4c9622ff61a707c253f60e98a5a72aad374439/core-bundle/src/Resources/contao/library/Contao/Search.php#L280-L291

The `getRules()` method only exists in the `IntlRuleBasedBreakIterator` class but not in the `IntlBreakIterator` class. I think we need to fix this, don't we?

**Comment by ausi** [comment]
What do you mean by `IntlBreakIterator::getRules()` doesn’t exist? It is not used in the linked code.

I can’t see why it should not work, working example: <https://3v4l.org/BiUYW>

**Comment by leofeyer** [comment]
WTF? The method should not exist in this class. 😄

* http://php.net/manual/de/class.intlbreakiterator.php
* http://php.net/manual/de/class.intlrulebasedbreakiterator.php

Maybe 3v4l.org uses an old Intl version?

**Comment by leofeyer** [comment]
Changed in d8781cbd7ac44a61fff0c24c95d2ff77aa380109.
