### ISSUE TITLE
Non-existent service error if search is disabled

### ISSUE THREAD

**Issue by ausi** [contao/contao#1252]
Setting `contao.search.default_indexer.enable` to `false` result in an `You have requested a non-existent service "contao.search.indexer.delegating"` error when building the container.

**Comment by leofeyer** [comment]
@Toflar Can you look into this please?

**Comment by Toflar** [comment]
We're removing the `contao.search.indexer.delegating` if there's not a single search indexer. However, we also inject the search indexer into the `SearchIndexSubscriber` (the one that's indexing on crawling) and the `SearchIndexListener` (the one that updates the index on `kernel.response`).
In fact we would also need to remove both of them if there is no indexer. And if there's no crawl subscriber at all, we could also disable the maintenance part as well as the `contao:crawl` command...

Not sure what's best here? Either remove all of it (which might be quite a few things and people are suddenly wondering why a command is missing etc.) or if we should replace it with a `NullIndexer` that just doesn't do anything. What's the preferred solution @contao/developers?

**Comment by leofeyer** [comment]
Depending on how much work it is, I lean towards removing the subscriber and the listener in case there is no search indexer.

**Comment by Toflar** [comment]
So it would look more or less like #1295?

**Comment by leofeyer** [comment]
Yes, #1295 looks correct (I have not tested the changes yet).

**Comment by ausi** [comment]
Closed in favor of #1295
