### ISSUE TITLE
Legends aren't searchable

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1253]
Hello,

affected version if Contao 4.4, but I think it has also been this way in Contao 3 ;-)

When I use Ctrl+F in Chrome e.g. in the Contao system settings, the collapsible legends are not searched by the browser search.

This seems to be a Chrome issue: https://support.google.com/chrome/thread/6256714?hl=en

Maybe we can change the legends to some other html element which is searchable?

Thanks in advance!

Bye Defcon0

**Comment by fritzmg** [comment]
`<legend>` is the correct tag. If that is an issue in Google Chrome, Google needs to fix this.
