### ISSUE TITLE
Folder can get in public state unexpectedly

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1254]
Hello,

I think, I just found an issue concerning the public state of folders in the file manager.

## How to reproduce

1. Create a folder with some name, let's say "test" in the root of the files directory and set it to non-public (i.e. private).
1. Create a folder with the same name as a sibling to the first one (i.e. also in the root of the file manager) and set to public. You should get a validation error ("same name already existing").
1. Now leave the edit form ("back" button).

Now the first folder created in step 1 is public :-O

Could you please check if you also have this issue? Thanks!

Bye Defcon0

**Comment by leofeyer** [comment]
I can confirm this issue. Which Contao version is affected?

@contao/developers Since the path of a file or folder is used as its ID, I am not sure whether we can fix this. Any ideas?

**Comment by ausi** [comment]
I think we should change https://github.com/contao/contao/blob/04fd76118a55003a671df9fd7343a5e5bc47f696/core-bundle/src/Resources/contao/dca/tl_files.php#L815 to:

```php
if (Contao\Input::post('name') && !is_dir($rootDir . '/' . $strPath))
```

Because only if the old path (before the rename) does no longer exist, we know that the rename was successful.
