### ISSUE TITLE
Wrong parameter passed to Widget::getAttributesFromDca() in ModuleRegistration

### ISSUE THREAD

**Issue by koertho** [contao/contao#1259]
In ModuleRegistration a wrong parameter is passed to Widget::getAttributesFromDca(). Instead of an DataContainer object or null the own instand (Module object) is passed. Since this parameter is also passen to the `getAttributesFromDca` hook, this may throw an type exception if the hook parameters are typed (which they are in my case).

Code reference:
https://github.com/contao/contao/blob/feda301a54a68920d2b5be38f6a13b8641aa211b/core-bundle/src/Resources/contao/modules/ModuleRegistration.php#L203

Affected version:
4.4.46, current master branch (so I think all versions.)

**Comment by m-vo** [comment]
You might want to check #1216 - maybe that was done intentionally and the hook's docs are wrong (saying you can't use type hints).

**Comment by koertho** [comment]
@m-vo But DataContainer is also expected in Widget:getAttributesFromDca():

https://github.com/contao/contao/blob/feda301a54a68920d2b5be38f6a13b8641aa211b/core-bundle/src/Resources/contao/library/Contao/Widget.php#L1230

The issue with typed hook listeners is just an follow-up problem.

**Comment by fritzmg** [comment]
> The issue with typed hook listeners is just an follow-up problem.

No, that is the actual problem. All of the hooks and callbacks involved with the member front end modules cannot use a strict type. The documentation needs to be adjusted to that.

**Comment by fritzmg** [comment]
See https://github.com/contao/docs/pull/239

**Comment by m-vo** [comment]
The `@param` annotations are probably wrong nevertheless.

**Comment by leofeyer** [comment]
We should check if we need to adjust the phpDocs before closing this.
