### ISSUE TITLE
"Weiterlesen..." im Backend selbst definieren

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#1260]
Hallo zusammen,

ich habe eine Frage bzw. eine Bitte.

Können wir es so machen, dass man den Text "Weiterlesen..." im Backend selbst definiert?

**Problem:**
Der Text "Weiterlesen..." lässt sich zwar über Template oder über default.php überschreiben, aber wenn man mehrere News-Archive hat vererbt sich die Umbenennung auf die andere Archive.

Bis jetzt bin ich so oft an solchen Problemen gestoßen und müsste ich jedesmal die Templates mit Archive-Abfragen erweitern und unterschiedliche $GLOBALEN ausgeben um die Anforderungen der Kunden gerecht zu werden. 

**Eventuelle Lösung:**
Wenn man bei den Beitragseinstellungen unter Weiterleitungsziel (source_legend) ein Feld dazu tun würde (z.B. more_title), könnte man den Text für jeden Beitrag individuell definieren. Wenn nichts angegeben wird, kann man auf dem Default-Wert in der Language-Datei zurückgreifen.

Vielen Dank!

**Comment by havutcuoglu** [comment]
> Issues bitte im Mono Repository anlegen.

@leofeyer Danke dir!

> Zum Issue selbst: imho ist das nichts für den Core und sollte wenn dann mit einer Erweiterung gemacht werden.

Ich denke, das diese Texte vom Redakteur individuell editierbar sein sollten. Genauso wie beim Hyperlink- und Download-Element etc. Der Contra sollte dafür einen handfesten Grund liefern.

Man kann für solche grundsätzliche Dinger nicht immer Erweiterungen verwenden. Dann bleiben wir beim `Template` und `default.php` Lösung, was allerdings genauso schlimm ist.

**Comment by fritzmg** [comment]
Warum nicht als Erweiterung programmieren?

**Comment by havutcuoglu** [comment]
Weil es für eine Textänderung eine Erweiterung zu programmieren Overkill ist.

Was spricht dagegen, den Textfeld in den core auf zu nehmen?

**Comment by m-vo** [comment]
> Der Contra sollte dafür einen handfesten Grund liefern.

Templates und Translations musst du eh immer anpassen.

> Was spricht dagegen, den Textfeld in den core auf zu nehmen?

Es ist ein unnötiges Feld für die allermeisten User. Eine Extension ist imo der richtige Ansatz.

**Comment by havutcuoglu** [comment]
Wenn man aber verschiedene Texte haben möchte, weil der bedarf besteht, und nicht nur weiterlesen da stehen soll, macht so ein Feld imo schon Sinn.

News-bundle bietet sich sehr gut für Nachrichten, Blogs, Aktuelles, Angebote, Jobs ...
Hier wird eben vom Kunden oder Redakteure erwartet, das da nicht weiterlesen steht sondern zur Blogbeitrag oder Mehr über das Angebot erfahren oder oder...

> Es ist ein unnötiges Feld für die allermeisten User.

Sprechen wir hier von Entwickler oder vom Redakteure?

**Comment by fritzmg** [comment]
In den meisten Fällen reicht ja die Translation Änderung. Es ist ja ein Spezialfall von dir, dass du das nur für ein einzelnes Archiv anders haben möchtest

**Comment by planepix** [comment]
Es gibt diese Erweiterung:

https://extensions.contao.org/?q=More&pages=1&p=ngdot%2Fcontao-changenewsmore

Vielleicht löst das schon deine Wünsche

**Comment by havutcuoglu** [comment]
Was bringt es, wenn der Redakteur die Texte für die einzelne Beiträge nicht selbst definieren kann?

Wenn es so ist, dann sollte man die Texte für Hyperlink und Download ebenfalls rausnehmen. Kann man auch global definieren für Hyperlink reicht "Link folgen..." völlig aus und für Download auch "Herunterladen..." würde ausreichen.

Also die Argumente die Ihr liefert klink für mich so, als würde man versuchen sich die Arbeit zu sparen. :)

**Comment by havutcuoglu** [comment]
> Es gibt diese Erweiterung:
> https://extensions.contao.org/?q=More&pages=1&p=ngdot%2Fcontao-changenewsmore
> Vielleicht löst das schon deine Wünsche

Wie es aussieht bin ich nicht der Einziger, der diesen einzelnen Fall hat.

**Comment by fritzmg** [comment]
> Also die Argumente die Ihr liefert klink für mich so, als würde man versuchen sich die Arbeit zu sparen. :)

Sorry, aber was soll diese Einstellung bitte? Wir diskutieren hier darüber, ob das eine sinnvolle Erweiterung für den Core ist - und das ist sie unseres (@fritzmg & @m-vo) Erachtens bisher nicht.

**Comment by havutcuoglu** [comment]
Sorry, nicht falsch verstehen. Vielleicht bin ich zu direkt. 
In Contao-Forum gibt es so viele Threads und im Internet gibt es so viele Foren mit Fragen darüber, wie man den einen Text individuell gestalten kann, und ihr seid der Meinung das es keinen Sinn macht es in den Core aufzunehmen.
Da wird man eben etwas enttäuscht und misstrauisch.

**Comment by fritzmg** [comment]
> In Contao-Forum gibt es so viele Threads und im Internet gibt es so viele Foren mit Fragen darüber, wie man den einen Text individuell gestalten kann, und ihr seid der Meinung das es keinen Sinn macht es in den Core aufzunehmen.

Solche Anfragen gibt es - aber das was du vorschlägst ist mir im noch nirgendwo untergekommen.

**Comment by havutcuoglu** [comment]
Wenn etwas öfter gefragt wird, dann ist da grundsätzlich was schief gelaufen.
Das ist für mich ein Indiz dafür, den Text manuell editierbar zu machen, und zwar so, dass jeder es editieren kann.

Was ich vorschlage ist nicht anderes als das was die User erwarten.

**Comment by fritzmg** [comment]
Ja, und wie bereits gesagt habe ich die Anfrage _Weiterlesen Link Label pro Nachrichtenarchiv definieren können_ noch nicht zuvor gesehen.

**Comment by havutcuoglu** [comment]
Eigentlich nicht pro Nachrichtenarchiv sondern pro Beitrag.

> Wenn man bei den Beitragseinstellungen unter Weiterleitungsziel (source_legend) ein Feld dazu tun würde (z.B. more_title), könnte man den Text für jeden Beitrag individuell definieren. Wenn nichts angegeben wird, kann man auf dem Default-Wert in der Language-Datei zurückgreifen.

Andere CMS bieten diese Möglichkeit. z.B. Joomla

**Comment by asaage** [comment]
Also ich fahr' super damit den Link bei Bedarf im Template anzupassen.
Oft entfern' ich den sogar und nutz' das Bild und die Überschrift als Link.
Um Templateanpassungen bin ich in letzter Zeit sowieso nicht mehr herumgekommen.
Das pro Beitrag als extra Feld zu wollen ist doch echt nur eine winzige DCA-Anpassung die man machen kann wenn man's denn braucht.

**Comment by havutcuoglu** [comment]
Man kann für alles Erweiterungen schreiben.

> Also ich fahr' super damit den Link bei Bedarf im Template anzupassen.

Soll ich in Template etwa abfragen:
```
if($this->id == 32) { echo "Weiterlesen";}
elseif($this->id == 33) { echo "Details anschauen";}
elseif($this->id == 35) { echo "Mehr erfahren";}
elseif($this->id == 48) { echo "Der XY erzählte noch folgendes";} 
...
else { $this->more;}
```
Das wird ja nie ein Ende haben. :)

Ich weiß immer noch nicht was dagegen spricht? Also den Grund habe ich nicht verstanden. 

Die Aussage unten ist nicht plausible.
> Es ist ein unnötiges Feld für die allermeisten User. Eine Extension ist imo der richtige Ansatz.

Meiner Meinung nach müsste/sollte man den Weiterlesen-Text von Nachrichtenbeitrag bzw. Nachrichten-Teaser individuell anpassen können.

Vielleicht gibt es noch weitere User der es genauso denkt.

**Comment by aschempp** [comment]
In den allermeisten Fällen sollte dieser Text vom Redakteur der News nicht bearbeitet werden können, es ist eine Aufgabe des Designs. Und aus UX-Sicht finde ich es auch sinnvoll es konsistent zu halten, damit die Besucher wissen was passiert.

Das Feld hinzuzufügen benötigt vermutlich eine Datei und 5 Zeilen Code in deinem System. Wir können nicht 1001 Funktionen einbauen welche nur für 1% der Anwender nutzbar sind. Genau dafür kann/soll man das System ja personalisieren, und genau dafür ist Contao ja so leicht anpassbar.

**Comment by havutcuoglu** [comment]
> Das Feld hinzuzufügen benötigt vermutlich eine Datei und 5 Zeilen Code in deinem System.

Das möchte ich sehen, wie es mit 5 Zeilen Code umgesetzt wird. 😃

> ...und genau dafür ist Contao ja so leicht anpassbar.

Klar ist Contao leicht anzupassen, aber dauert ewig, weil man – wie du bereit sagst – an 1001 Stellen Funktionen einbauen muss.

Aber trotzdem danke schön, das Ihr Zeit für mein Anliegen genommen habt. 👍

**Comment by fritzmg** [comment]
> Das möchte ich sehen, wie es mit 5 Zeilen Code umgesetzt wird. 😃

```php
// contao/dca/tl_news.php
use \Contao\CoreBundle\DataContainer\PaletteManipulator;

$GLOBALS['TL_DCA']['tl_news']['fields']['readMoreText'] = [
    'label' => ['"Weiterlesen" Text', 'Wenn angegeben, wird dieser Text für den "Weiterlesen" Link benutzt.'],
    'inputType' => 'text',
    'eval' => ['tl_class' => 'w50', 'maxlength' => 255],
    'sql' => ['type' => 'string', 'length' => 255, 'default' => ''],
];

PaletteManipulator::create()
    ->addField('readMoreText', 'expert_legend', PaletteManipulator::POSITION_APPEND)
    ->applyToPalette('default', 'tl_news')
;
```
```php
// templates/news_latest.html5
…
    <p class="more"><a href="<?= $this->link ?>"><?= $this->readMoreText ?: $this->trans('MSC.more') ?></a></p>
…
```

**Comment by havutcuoglu** [comment]
> `use \Contao\CoreBundle\DataContainer\PaletteManipulator;`

@fritzmg das mit dem `PaletteManipulator` wusste ich nicht. 😲

Das macht natürlich alles um vielfaches einfacher. 👍
