### ISSUE TITLE
SPAM trotz Honeypot in Contao 4.4 (form_captcha.html5)

### ISSUE THREAD

**Issue by sennamint** [contao/contao#1262]
Einer unserer Kunden berichtete uns von einer Welle an SPAM-Mails, die er in den letzten Tagen über das Kontaktformular seiner Contao-Website erhalten hat trotz verborgener Captcha-Rechenaufgabe mit Honeypot-Script, wie es in Contao 4.4 Standard ist.

Dieses Thema wurde u.a. schon einmal in diesem Ticket behandelt:
https://github.com/contao/core/issues/8874

Ich habe mir deshalb die im Template [form_captcha.html5](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/forms/form_captcha.html5) eingesetzte Honeypot-Javascript-Lösung angesehen. Wenn ich es richtig verstehe, wird hierbei die Sicherheitsfrage versteckt und automatisch ausgefüllt, sobald Javascript vorhanden ist.

Ich vermute nun, dass der SPAM-Bot, der nicht im Honig kleben geblieben ist, in der Lage ist, Javascript zu interpretieren und das DOM entsprechend zu modifizieren. Dies wäre z.B. über den Selenium WebDriver denkbar.

Wir haben als Interimslösung eine Kopie vom Template "form_captcha.html5" angelegt und diese beiden Zeilen auskommentiert:

```javascript
p.style.display = 'none';
e.value = '<?= $this->getSum() ?>';
```

Damit wird die Anzeige der Sicherheitsfrage wiederhergestellt und muss vom Besucher ausgefüllt werden. Das ist eine Lösung. Aber sicher nicht die beste.

Ich möchte deshalb hier die Diskussion anregen, ob und wie sich eine sicherere Logik des Honeypots umsetzen ließe.

Danke und beste Grüße.

**Comment by ausi** [comment]
Für Anregungen sind wir gerne offen denke ich.

Als Info, folgende Anforderungen haben zur aktuellen Lösung geführt:

- Soll auch ohne JavaScript (für Menschen) bedienbar bleiben.
- Soll möglichst keine Fehler mit Browser-Plugins verursachen die Formularfelder automatisch ausfüllen.
- Soll von den meisten Besuchern gar nicht bemerkt werden dass ein Schutz da ist.

Könntest du in deinem Projekt bitte testen ob folgende Änderung das Spam-Aufkommen reduziert:

```js
p.style.display = 'none';
setTimeout(function () {
  e.value = '<?= $this->getSum() ?>';
}, 5000);
```

**Comment by sennamint** [comment]
Danke, Martin, für Deine Informationen zu den Anforderungen. Das ist nachvollziehbar und absolut sinnvoll.

Danke Dir auch für die sehr clevere und simple Lösung mit dem Timeout. Wir haben das Timeout sicherheitshalber gleich auf 10 Sekunden festgelegt. Das ist eine Zeitspanne, bei der vermutlich kein Bot am Ball bleiben würde. Ein Mensch wird für das Ausfüllen eines Kontaktformulars mindestens 10 Sekunden benötigen. Selbst wenn statische Daten vom Browser vorausgefüllt werden, muss er ja noch einen Text schreiben.

Wir haben unseren Kunden gebeten, das künftige SPAM-Aufkommen im Blick zu behalten und uns zu informieren, sollte weiterhin SPAM über das Kontaktformular eintreffen.

**Comment by leofeyer** [comment]
@sennamint Kann das Ticket dann erstmal geschlossen werden oder bleibt noch etwas zu tun bzw. zu beantworten?

**Comment by ausi** [comment]
Wenn @sennamint bestätigen kann, dass das SPAM-Aufkommen durch die Änderung gesunken ist, sollten wir das Timeout in das Standard-Template übernehmen denke ich.

**Comment by sennamint** [comment]
Ich habe soeben bei unserem Kunden noch einmal nachgehakt und hoffe auf baldige Antwort, ob das SPAM-Aufkommen abgenommen hat oder nicht. Ich gebe Bescheid, sobald ich Antwort habe.

**Comment by bibib** [comment]
Ich habe dieses Timeout auch bei einem Kunden eingebaut, der trotz Honeypot-Spamschutz ca. 50 Spammails pro Woche bekommen hat. Habe gerade nachgefragt, direkt nach dem Einbau (Ende Jänner) war erst einmal Ruhe, aber seit letzter Woche kommen doch wieder geschätzt so 15-20 Spammails pro Woche rein.

**Comment by sennamint** [comment]
Ich habe nun eine positive Rückmeldung unseres Kunden erhalten. Bei ihm ist seit der Änderung (Timeout) kein SPAM mehr eingegangen. Ob es am Timeout liegt oder möglicherweise daran, dass der SPAM-Bot einfach nicht mehr aktiv war seit der Änderung, kann ich nicht sagen. So oder so halte ich es für sinnvoll, den Timeout ins Standard-Template zu übernehmen.

**Comment by bibib** [comment]
Nachdem die Lösung bei sennamint funktioniert hat, habe ich die Sache bei meinem Kunden nochmals überprüft und festgestellt, dass ein Template eines Themes dem Spamschutz in die Quere gekommen ist. Ich habe das Template eliminiert und den Spamschutz nochmal überprüft - seit einer Woche ist kein Spam mehr angekommen. Dankeschön!

**Comment by sennamint** [comment]
Na dann nichts wie ab mit der Timeout-Lösung in das Standard-Template, wie @ausi es vorgeschlagen hat, oder?

**Comment by leofeyer** [comment]
Wie am 12. März auf Mumble besprochen, wollen wir einen Timeout von 5 Sekunden einbauen und schauen, wie stark es die Usability einschränkt.
