### ISSUE TITLE
Login führt zu einer Fehlermeldung

### ISSUE THREAD

**Issue by V15** [contao/contao#1263]
Ich habe eine neue Installation von Contao 4.8.x bei Hetzner aufgesetzt und diese dann auf 4.9 RC1 upgedatet. Nach dem Login unter der Domain http://www.domain.de/contao/login erscheint die folgende Fehlermeldung:

` base64_decode() expects parameter 1 to be string, null given`

Wenn ich die Seite neulade, passiert nichts.
Wenn ich hinter der Domain bzw. hinter "login" in der Domain "Enter" drücke, komme ich normal ins Backend.
![login](https://user-images.githubusercontent.com/4067828/73372420-78b81600-42b7-11ea-8f03-16ae37a1beb9.png)

**Comment by bytehead** [comment]
See https://github.com/contao/contao/pull/1246.

**Comment by bytehead** [comment]
Sorry, the issue is not related to the mentioned ticket! 🙈

**Comment by bytehead** [comment]
Kannst du den Pretty-Error-Screen deaktivieren und den Stacktrace vom Fehler hier posten?

**Comment by V15** [comment]
> Kannst du den Pretty-Error-Screen deaktivieren und den Stacktrace vom Fehler hier posten?

Wenn du mir verräts wie ich das mache, gerne.

**Comment by bytehead** [comment]
Du müsstest in der `config/config.yml` oder `config/config.yaml` folgendes stehen haben:
```yaml
contao:
    pretty_error_screens: false
```

**Comment by bytehead** [comment]
Oder vielleicht siehst du im Log-File unter `var/log/` was?

**Comment by V15** [comment]
Mit dem Eintrrag in der config.yml erscheint nur eine Standardfehlermeldung:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by V15** [comment]
Log-File:
`[2020-01-29 17:25:31] request.INFO: Matched route "contao_backend_login". {"route":"contao_backend_login","route_parameters":{"_route":"contao_backend_login","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::loginAction"},"request_uri":"http://domain.de/contao/login","method":"POST"} []
[2020-01-29 17:25:32] security.INFO: User has been authenticated successfully. {"username":"V15"} []
[2020-01-29 17:25:32] request.CRITICAL: Uncaught PHP Exception TypeError: "base64_decode() expects parameter 1 to be string, null given" at /contao/vendor/contao/core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php line 142 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): base64_decode() expects parameter 1 to be string, null given at /contao/vendor/contao/core-bundle/src/Security/Authentication/AuthenticationSuccessHandler.php:142)"} []`

**Comment by bytehead** [comment]
Danke, das hilft schon mal.

**Comment by fritzmg** [comment]
Mit dem Debug-Modus von Contao bekommst du auch den Stack Trace ;)

**Comment by V15** [comment]
OT: Das wäre sooo praktisch, wenn es dazu einen einfachen Link (im Manager!?) geben würde mit einer kurzen Erläuterung wie man das macht.

Ich habe den schon mal verwendet, aber das kommt einfach zu selten vor, daher weiß ich nicht mehr was nötig ist um den Debug-Modus aufzurufen.

Das liegt aber auch an euch - normalerweise funktioniert alles, daher braucht man den Debug-Modus nicht häufig ;-)

**Comment by fritzmg** [comment]
https://docs.contao.org/manual/de/system/debug-modus/

**Comment by bytehead** [comment]
Wie sieht das gerenderte HTML aus von deinem Login-Formular?

**Comment by V15** [comment]
> Wie sieht das gerenderte HTML aus von deinem Login-Formular?

Daran hat es gelegen: Ich hatte noch ein be_login.html5 Template (mit einem Logo) von der 4.4 in dem Template Ordner liegen. Das habe ich nun gelöscht und der Login funktioniert einwandfrei.

Entschuldigt bitte das ich das nicht früher gesehen habe :-(

**Comment by bytehead** [comment]
Ah, ja das hat sich in 4.5 eigentlich schon geändert. Aber durch die Base64-Kodierung des Parameters erst in 4.9-RC1 zum Fehler geführt.

**Comment by joseluisq** [comment]
I have tried it out Contao v4.9 today just for testing purposes in my workstation via:

```sh
~> php -v
PHP 7.2.28 (cli) (built: Feb 20 2020 10:35:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.28, Copyright (c) 1999-2018, by Zend Technologies

~> php -d memory_limit=-1 \
          $(which composer) create-project contao/managed-edition . 4.9

# Everything was installed fine. Database configured ok.

~> php -S localhost:8200 -t web/
```

But then when I tried `http://localhost:8200/contao` I got a `base64_encode() expects parameter 1 to be string, null given.`

```log
[2020-03-12 11:22:02] request.CRITICAL: Uncaught PHP Exception TypeError: "base64_encode() expects parameter 1 to be string, null given" at /Users/jq/contao-49/vendor/contao/manager-bundle/src/EventListener/BackendMenuListener.php line 105 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): base64_encode() expects parameter 1 to be string, null given at /Users/jq/contao-49/vendor/contao/manager-bundle/src/EventListener/BackendMenuListener.php:105)"} []
```

Then I found [this link](https://docs.contao.org/manual/en/system/debug-mode/#contao-4-8-and-up).

I created a `.env` on root directory with `APP_ENV=dev` (if you omit this you get the same base64_encode() error). Now it works.

So, it looks like Contao 4.9 is not able to run without `APP_ENV=dev` defined explicitly. 
For me particularly is confusing to have a `parameters.yml` and `.env` file. What is the difference? Why I need both and not just one `.env` file?

**Comment by aschempp** [comment]
> For me particularly is confusing to have a parameters.yml and .env file. What is the difference? Why I need both and not just one .env file?

You don't need both (in Contao 4.9). You can configure the database in the `.env` file the same you can in any Symfony configuration. Just be aware that you can't use the install tool anymore in that case (to change the credentials).
```
DATABASE_URL=mysql://user:password@host:port/database
```
