### ISSUE TITLE
[4.9] Subpalettes öffnen nicht

### ISSUE THREAD

**Issue by WebRoxx** [contao/contao#1264]
Folgendes habe ich in der 4.9 RC1 festgestellt. 

**Zum Beispiel:** 

Seitenstruktur -> eine Seite wählen -> Checkbox: Seite schützen -> passiert nichts, nur Ladeanimation

Post-Request sendet da wohl "null"

**Comment by bytehead** [comment]
Siehe https://github.com/contao/contao/pull/1225.

**Comment by WebRoxx** [comment]
Oh Sorry

**Comment by bytehead** [comment]
Könnte damit zusammenhängen.

**Comment by WebRoxx** [comment]
Ja das wird vermutlich so sein.

**Comment by bytehead** [comment]
Definitiv: `No route found for "POST /null"` laut Inspector. Ist durch #1225 behoben.
