### ISSUE TITLE
tl_session missing

### ISSUE THREAD

**Issue by epsreps** [contao/contao#1269]
In a fresh install of contao 4.8.7 the table tl_session is missing after running contao/install. is this the correct behavior? i've nothing found in the issues and forums.

**Comment by bytehead** [comment]
Yes, the session table got kicked with Contao 4.5 (introducing the Symfony security system): https://github.com/contao/core-bundle/pull/1232. It is the correct behaviour.

**Comment by epsreps** [comment]
i see. thanks
