### ISSUE TITLE
Better error messages for editing meta information

### ISSUE THREAD

**Issue by MatthiasBusch** [contao/contao#127]
Tested with contao 4.6.*

**Description**  
At the moment, when you try to edit the metainformation of a file in the file manager, while your root page has an invalid language definition, you are unable to edit the metainformation, but the only error you get is the following (german setup) ''Sie müssen einen Startpunkt in der Seitenstruktur anlegen, um Metadaten einzugeben.''

This is really irritating, as there is already a root page. The error should rather be something like 'Die Sprache in einem der Startpunkte in der Seitenstruktur ist fehlerhaft'. In my opinion it would be even better, if there is already a language validation in the root page settings, as it has such a big impact. (In my case I used it for share buttons in a gallery, but couldn't create the links and the only place to do so was in fact the file manager)

**Comment by leofeyer** [comment]
What exactly do you mean by "invalid language definition"?

**Comment by MatthiasBusch** [comment]
In my case I used 'en-en' as language

**Comment by leofeyer** [comment]
Fixed in a628b17c4202606a38f1e16dd300475c37dd05be.
