### ISSUE TITLE
Übersetzung "channel" im Newsletter Bundle

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1272]
Im Newsletter Bundle sollte die Übersetzung von "channel" stets "Verteiler" lauten.

https://github.com/contao/contao/blob/bf87609767e5623d9da8b98920683bef2d651997/newsletter-bundle/src/Resources/contao/languages/de/tl_newsletter.xlf#L56-L59

https://github.com/contao/contao/blob/bf87609767e5623d9da8b98920683bef2d651997/newsletter-bundle/src/Resources/contao/languages/de/tl_newsletter.xlf#L80-L83

https://github.com/contao/contao/blob/bf87609767e5623d9da8b98920683bef2d651997/newsletter-bundle/src/Resources/contao/languages/de/tl_newsletter.xlf#L88-L91

**Comment by leofeyer** [comment]
Ich habe die deutsche Übersetzung angepasst.
