### ISSUE TITLE
BE: Sortierung der Kalender und Events

### ISSUE THREAD

**Issue by Anke** [contao/contao#1273]
**A. Events (contao?do=calendar):**

Wenn man eine Liste mehrerer Kalender hat wie z.B.

- Termine 2015
- Termine 2016
- Termine 2017  
- Termine 2018  
- Termine 2019  
- Termine 2020
- 
wäre es schön, wenn man die Sortierung beeinflussen könnte. Bis jetzt gibt es nur eine Such- und Filter-Funktion.

**B. Events/[Kalendername]/Events (contao?do=calendar&table=tl_calendar_events):**

Hier kann man die Datensätze zwar sortieren (z.B. nach Startzeit), aber nur in der vorgegebenen Richtung. Wenn man Termine für ein Jahr im Voraus eingibt und immer den Januar 2021 oben und den Februar 2020 ganz unten in der Liste hat, wäre es angenehm, die Sortierung auch umkehren zu können.

**Comment by steadyyyyy** [comment]
Love to help but please write it in english :(

**Comment by fritzmg** [comment]
@steadyyyyy basically @Anke is requesting two features for the _Events_ back end module:

1. The ability to sort calendars on demand.
2. The ability to define the sort direction of events within a calendar.

**Comment by leofeyer** [comment]
See #5425.
