### ISSUE TITLE
RFC: Command to generate a contao-templates.lock

### ISSUE THREAD

**Issue by Toflar** [contao/contao#1276]
**Description**

I find myself missing template changes over and over again.
When I update to new Contao versions, I just run `composer update` to update to the latest packages. Then I execute migrations with the new `contao:migrate` command and I'm done.
However, when I have adjusted templates in my project and there were core template changes, I have to check manually to see if there were changes. The same applies for templates of extensions of course.
And I have to admit that I usually miss them 😄 

I really don't need anything complicated that shows me diffs or anything like that. If - after a `composer update` - I knew what templates have been updated since the last `composer update`, I would already be happy.
We could achieve this by storing e.g. a SHA1 hash along with the paths of all the template files to that lock file. A simple diff in my git repository will tell me which templates have been adjusted and I know which ones I thus need to compare or double check.

**Example**

1. Run the `contao:generate-templates-lock` command
2. It generates a `contao_templates.lock` file which might look something like this:

```json
{
     "vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5": "8843d7f92416211de9ebb963ff4ce28125932878",
     "vendor/contao/faq-bundle/src/Resources/contao/templates/modules/mod_faqlist.html5": "c0ac73e304ca4fd4275985fe1e5ee6a113399eee",
     "system/modules/ajaxform/template/ajaxform_confirm.html5": "037526671b140b9060aa6de1083a96fb607db988",
}
```

Sure, we might also store along the whole contents instead of just a hash so the changes can be seen immediately but I don't know how much data that would generate etc.
Also it's not as simple as it sounds because we'd need to check which bundles are coming from the `vendor` or `system` folders (we're not interested in keeping hashes of the locally overwritten templates) etc.

But I wanted to keep that idea here. Any comments?

**Comment by m-vo** [comment]
>However, when I have adjusted templates in my project and there were core template changes, I have to check manually to see if there were changes

Yeah, I feel the same way. I once had the idea to add tests to my toolchain, that fail as soon as there are changes to templates I'm using/extending (storing file hashes in the test).

**Comment by aschempp** [comment]
I like the idea of "seeing what templates changed". But for some reason I don't like the templates.lock, and I have no other clever idea how to fix this… I don't want git to tell me the hash has changed, I want to see the actual differences (and possibly without git?).

**Comment by Toflar** [comment]
The alternative would be to store all template contents in one file so you can see the diff. Not using git would mean you need to store two files which doesn't make sense to me.
VCS were invented for this.

**Comment by fritzmg** [comment]
👍 for the idea in general. I frequently have to tell people in the forum that they of course need to compare all their modified templates after each major or minor update at least. Knowing at least _which_ templates have changed would help a lot.

**Comment by Toflar** [comment]
We would leave those people behind because they don't use VCS. If we wanted that, we'd need to keep track of the changes somewhere else (aka the database). And I cannot even express how much I'm against such a solution. Use VCS. End of story.

**Comment by leofeyer** [comment]
> If we wanted that, we'd need to keep track of the changes somewhere else (aka the database). And I cannot even express how much I'm against such a solution. Use VCS. End of story.

ACK.

**Comment by fritzmg** [comment]
> We would leave those people behind because they don't use VCS.

I don't think _all_ of those people _don't_ use VCS :). I am not against your approach. And if we have something like this in Contao, then it will promote using a VCS to those that aren't.

**Comment by aschempp** [comment]
Unfortunately, noone of use uses VCS for the templates, because they are in the `vendor` folder. I _would_ use VCS if I could, but that would probably mean I need to exclude templates from `.gitignore`?

**Comment by Toflar** [comment]
The goal is that we introduce a new command (we can add this to the default ones that are executed in the ME) which generates a `contao-templates.lock`. This lock file can contain all the template contents of all the third party (`vendor` and `system/modules`) templates. For example:

```
<!-- vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5 -->

<div class="tinyMCE" ...>
...
</div>

<!-- vendor/contao/faq-bundle/src/Resources/contao/templates/modules/mod_faqlist.html5 -->

<div class="mod_faq" ...>
...
</div>
```

That means, whenever you run `contao:generate-templates-lock` it will just write this file again (meaning in the ME it could happen for ever `composer update` and `composer install`) and you'll thus see what's changed in this file.

**Comment by m-vo** [comment]
> I would use VCS if I could, but that would probably mean I need to exclude templates from .gitignore?

Sure, you could unignore the template folder on the application level. But you would need to do this manually for all extensions which imo is impractical.

**Comment by aschempp** [comment]
That's my point 😆
