### ISSUE TITLE
Route 'contao_backend_switch' not found

### ISSUE THREAD

**Issue by ausi** [contao/contao#1277]
**Affected version** `4.9.x-dev`

Did we rename the route `contao_backend_switch` to `contao_backend_preview_switch` in #989 on purpose?

If so we need to update https://github.com/contao/contao/blob/68b47c6ccab103c8fd205bc1c9a7f105c293d86b/UPGRADE.md#L312 and probably mention the rename of the route in a `Version 4.* to 4.9` section in the *UPGRADE.md*.

/cc @richardhj

**Comment by richardhj** [comment]
The routes are not functional identical, I guess this is why I renamed the route 🤷‍♀️

**Comment by leofeyer** [comment]
We should restore the original route name IMHO. @contao/developers WDYT?

**Comment by Toflar** [comment]
Doesn‘t really matter to me. I don‘t see why routes would be covered by a BC promise. That makes no sense to me.

**Comment by leofeyer** [comment]
They are not covered by the BC promise, but there is also no reason to change the route name, which then requires to adjust the documentation.

**Comment by Toflar** [comment]
Agreed

**Comment by richardhj** [comment]
Rolling back the route name is OK for me. But people who rely on the `contao_backend_switch` route will encounter problems nonetheless in Contao 4.9. So having a break here might seem reasonable.

**Comment by leofeyer** [comment]
> will encounter problems nonetheless

In what way?

**Comment by richardhj** [comment]
I correct myself.
Both the old script and the new `BackendPreviewSwitchController` will return the toolbar on a GET request. I don't think, anyone utilizes this route, but we can change back the name :-)

**Comment by ausi** [comment]
> I don't think, anyone utilizes this route

I do 🙃 https://github.com/madeyourday/contao-rocksolid-frontend-helper/blob/519ed500a582069baaa1bb9456039f706f7b7ab0/src/FrontendHooks.php#L288

**Comment by leofeyer** [comment]
So what now?

**Comment by richardhj** [comment]
> So what now?

#1292 :-)

**Comment by ausi** [comment]
Closed in favor of #1292
