### ISSUE TITLE
Default table sorting is not applied

### ISSUE THREAD

**Issue by loilo** [contao/contao#1278]
**Affected version(s)**
< 4.8, including 4.4 LTS (only tested 4.4 upwards)

**Description**
Sortable tables are not sorted initially, although according to the sort index description they should be ("The number of the default sort column"). Since 4.4 is currently still LTS, this should probably be fixed.

**How to reproduce**
1. Create a table.
2. Make it sortable with the *Sortable table* checkbox.

**Steps to fix**
This is how we've locally fixed the issue for a client:

- Backport the `sortDefault` template variable [from 4.8](https://github.com/contao/core-bundle/blob/4.8/src/Resources/contao/elements/ContentTable.php#L42), adjust its format (because of the changed JS library) and pass it to the table template.
- React to the passed data by adjusting the `j_tablesort` template accordingly. (Alternatively, we could update to a more recent version of `tablesorter` which [picks up the appropriate `data-*` attribute automatically](https://mottie.github.io/tablesorter/docs/#sortlist) and has no breaking changes according to the changelog — but I doubt we'd want to run that risk.)
- Possibly cherry-pick the fix into the 4.5/6/7 branches? (Not sure how strict you are about the end-of-life on these.)

---

I'd be happy to attach a PR if you would like to see this fixed.

**Comment by aschempp** [comment]
> Make it sortable with the *Sortable table* checkbox.

I don't know about that checkbox, can you please explain it?

**Comment by loilo** [comment]
Sure. I mean the checkbox in the "Sorting options" section when editing a table content element:

![Screenshot of the said checkbox in the Contao backend](https://user-images.githubusercontent.com/1922624/74006987-83d90900-497d-11ea-8267-fc2fa9a1a450.png)

**Comment by aschempp** [comment]
Thanks for the clarification. I wasn't aware you did mean the table content element, I assumed some PHP code in the back end 😂

**Comment by loilo** [comment]
That's a reasonable assumption I guess. 😅

**Comment by leofeyer** [comment]
See #1315
