### ISSUE TITLE
 Error thrown while running command contao:migrate

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#1279]
**Affected version(s)**
Version 4.9.0-RC1

**Description**
Command `contao:migrate` throw error

**How to reproduce**
1. Install extension `terminal42/notification_center`
2. Execute `vendor/bin/contao-console contao:migrate`

The problem doesn't occur with every extension. I also tried with` terminal42/contao-easy_themes` which run fine.

**Stack-Trace**
[stack-trace-migrate.txt](https://github.com/contao/contao/files/4152642/stack-trace-migrate.txt)

**Comment by ausi** [comment]
Der Fehler scheint in der Datei *terminal42/notification_center/config/runonce.php* zu liegen. Die Fehlermeldung deutet darauf hin, dass darin eine Abfrage fehlt ob die Tabelle `tl_nc_language` existiert.

**Comment by ausi** [comment]
Die Zeile https://github.com/terminal42/contao-notification_center/blob/ef96a2af1f26ec66ae7b7b9947799556549caff3/config/runonce.php#L11 sollte vermutlich folgendermaßen erweitert werden:

```php
if (\Database::getInstance()->tableExists('tl_nc_language') && \Database::getInstance()->fieldExists('file_override', 'tl_nc_language')) {
```

**Comment by contaoacademy** [comment]
Danke. Kann ich das Ticket verschieben zum notification_center oder muss ich das neu erstellen?

**Comment by ausi** [comment]
Bitte ein neues Ticket erstellen.

Dieses hier würde ich noch offen lassen, da die *runonce.php*-Datei aus dem notification center schon 5 Jahre alt ist, könnte es sein dass sich an Contao hier etwas geändert hat.

**Comment by fritzmg** [comment]
Hm, dieser Fehler sollte aber auch ohne den neuen Migrations auftreten. Allerdings habe ich den Verdacht, dass vorher etwaige Fehler in der runonce.php einfach verschluckt wurden.

**Comment by ausi** [comment]
> Allerdings habe ich den Verdacht, dass vorher etwaige Fehler in der runonce.php einfach verschluckt wurden.

Dein Verdacht ist korrekt: https://github.com/contao/contao/blob/4.8/core-bundle/src/Resources/contao/classes/Backend.php#L259-L265

Bisher wurden alle Exceptions ignoriert und die Datei danach dennoch gelöscht. Sollten wir für Rückwärtskompatibilität das Verhalten so übernehmen?

Ich wäre dafür das Verhalten im Migrate Command so zu lassen wie es jetzt ist, also den Fehler zu werfen und den Prozess abzubrechen. Im Install-Tool kommt ohnehin noch das „alte“ Verhalten zum Einsatz und somit wäre es kein Problem mit der Rückwärtskompatibilität aus meiner Sicht.
