### ISSUE TITLE
fos_http_cache.tags.enabled

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#128]
**Description**

If we could remove `fos_http_cache.tags.enabled` or set it to `false`, we would no longer need to install `sensio/framework-extra-bundle`. See the [TagListenerPass](https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/src/DependencyInjection/Compiler/TagListenerPass.php) class.

**Comment by Toflar** [comment]
Needs adjustments in the bundle: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/489

**Comment by Toflar** [comment]
Should be possible now by requiring version `^2.6` and using `tags.annotations.enabled: false`. Thanks a lot @dbu!

**Comment by leofeyer** [comment]
Changed in e9334ee0e3a684ab349e1d5fac7cff35901964c0.
