### ISSUE TITLE
Crawler: Anzeige Frontend-Mitglied nur bei aktivierter Suche von geschützten Seiten

### ISSUE THREAD

**Issue by saress** [contao/contao#1280]
**Affected version(s)**
C 4.9.x-dev

**Description**
Im Bereich Systemwartung sollte beim "Crawler" die Auswahlmöglichkeit eines Frontend-Mitglieds nur angezeigt werden, wenn die Suche für geschützte Seiten über die config.yml explizit aktiviert wurde.

Aktuell geht man davon aus, dass der Crawler nach der Auswahl eines Frontend Mitglieds auch geschützte Seiten indexiert, was aber nicht stimmt, da die Indexierung von geschützten Seiten standardmäßig deaktiviert ist.

Laut @Toflar kann man die Indexierung über die config.yml mittels

`contao.search.index_protected: true`

aktivieren und das funktioniert auch bestens, siehe auch:
https://contao.slack.com/archives/CK4J0KNDB/p1580798092210200

**Comment by contaoacademy** [comment]
Wäre super, wenn es einen kleinen Hinweis im Backend dazu gibt.
"Um geschützte Seiten zu indizieren, muss die Funktion in der `config.yml` aktiviert werden".
Oder so ähnlich

**Comment by contaoacademy** [comment]
Wäre außerdem super, wenn das Ticket https://github.com/contao/contao/issues/754 gleich mit berücksichtigt wird :-)

**Comment by leofeyer** [comment]
Siehe #1291
