### ISSUE TITLE
Ausgabe in der Konsolen ab Contao 4.9 anpassen

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#1288]
Wenn ich auf der Konsole ein `composer update` durchführe, wird mir am Schluss folgende Meldung ausgegeben:

`Done! Please open the Contao install tool and make sure the database is up-to-date.`

Da ich dank `contao:migrate` jetzt das Datenbank-Update auch direkt auf der Konsole anschieben kann, würde ich die Meldung wie folgt ändern:

`Done! Please open the Contao install tool or run contao:migrate on the command line to make sure the database is up-to-date.`

**Comment by Toflar** [comment]
https://github.com/contao/contao/pull/1289
