### ISSUE TITLE
Website Crawl on Valet Server

### ISSUE THREAD

**Issue by samuelheer** [contao/contao#1297]
**Affected version(s)**
Version 4.9-RC1

**Description**
In meiner lokalen Entwicklungsumgebung (Laravel Valet) ist es nicht möglich den Contao Crawl auszuführen.

[Contao\CoreBundle\Crawl\Escargot\Subscriber\BrokenLinkCheckerSubscriber] [[object] (Terminal42\Escargot\CrawlUri: URI: http://localhost/examplesite.html (Level: 0, Processed: yes, Found on: root, Tags: none))] Broken link! HTTP Status Code: 404.

Wenn ich auf dem Root-Knoten ein Website angebe kommt folgende Fehlermeldung:
[Contao\CoreBundle\Crawl\Escargot\Subscriber\BrokenLinkCheckerSubscriber] [[object] (Terminal42\Escargot\CrawlUri: URI: https://businesscard.test/examplesite.html (Level: 0, Processed: yes, Found on: root, Tags: none))] Broken link! Could not request properly: Couldn't resolve host name for "https://businesscard.test/examplesite.html"..

Scheint so, als ob es hier Probleme beim Auflösen über Valet gibt. Ob das ein Contao-Problem oder ein Valet Problem ist, weiß ich nicht?

**Comment by Toflar** [comment]
Das hat nichts mit Contao zu tun.

> Couldn't resolve host name for "https://businesscard.test/examplesite.html"..

Heisst einfach, PHP kann keine Requests auf diese URL absetzen, weil dieser Host nicht existiert.
Ich weiss, dass Valet irgendwie mit DnsMasq funktioniert, ggf. musst du also dafür sorgen, dass die Crawler-Requests korrekt geproxy'ed werden.
Das wiederum kannst du natürlich bei Contao konfigurieren 😎 

```yaml
contao:
    crawl:
        default_http_client_options:
            proxy: 'http://localhost:7080'
            verify_peer: false
```

So funktioniert es dann z.B. mit dem Symfony Local Web Server (dessen Proxy auf 7080 läuft). `verify_peer` deaktiviert die Prüfung des SSL-Zertifikats, da ich lokal meine eigene CA hab.
Du kannst da alle Optionen übergeben, die der Symfony HTTP Client kennt (https://github.com/symfony/symfony/blob/master/src/Symfony/Contracts/HttpClient/HttpClientInterface.php#L26), also z.B. auch Basic Auth etc., falls das erforderlich sein sollte.
