### ISSUE TITLE
Consider the start/stop dates in cache timeouts

### ISSUE THREAD

**Issue by richardhj** [contao/contao#13]
<sup>(OOTB = Out of the box)</sup>

I'm a fan of the shared caching since Contao 4.6.

There are two more points I want to address:

**Start/stop of content elements**  

At the moment, the start and stop date of content elements will not affect the cache, i.e., will not invalidate the cache when one content element reaches its start or stop date leading to pages being out-of-date.

For reference, this is the code that sets the caching max-age header on legacy modules:

https://github.com/contao/contao/blob/4.6/core-bundle/src/Resources/contao/classes/FrontendTemplate.php#L383-L391

As a solution, I came up with the following pseudo-code:
```php
global $objPage;

$allStartTimestampsOfContentElementsOnThisPage = '…';
$allStopTimestampsOfContentElementsOnThisPage = '…';

// Get all relevant timestamps
$min1 = min(
    array_filter($allStartTimestampsOfContentElementsOnThisPage, function($start) {
        return $start > time();
    })
);
$min2 = min(
    array_filter($allStopTimestampsOfContentElementsOnThisPage, function($stop) {
        return $stop > time();
    })
);

// calculate max age from timestamp
$min2 = $min1 - time();
$min2 = $min2 - time();

$sharedMaxAge = min($objPage->cache, $min1, $min2);
$response->setSharedMaxAge($sharedMaxAge);
```

Doing so, the max age will be the time one element reaches the start/stop date.

**Vary on user context**  

What are your plans on this one? :-)
At the moment, the cache will be put out of action when a user is logged in.

**Comment by Toflar** [comment]
Start and stop support could be added to the https://github.com/contao/contao/blob/master/core-bundle/src/Controller/AbstractFragmentController.php which is designed to be the parent of all fragments (content elements, front end modules, insert tags (not implemented yet)). That would be a nice addition if you want to work on that 😄 

> User context: What are your plans on this one? :-)

No plans, I don't think we'll ever do that. The benefits in a regular application are negligible compared to how much more complicated the caching would get. I mean, sure we could share some of the content if e.g. members are part of the same member group but then again, you would need thousands of members to have a real advantage here 😄

**Comment by richardhj** [comment]
I just tried to render a module as ESI.

```yml
 richardhj.mymodule:
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: contao.frontend_module, type: …, category: …, renderStrategy: esi }
```

```php
class UserApplication extends AbstractFrontendModuleController
{
    protected function getResponse(Template $template, ModuleModel $model, Request $request): Response
    {
        return Response::create($template->parse())->setSharedMaxAge(10);
    }
}
```

The response then reaches Symfony's fragment handler where the headers get ignored.

https://github.com/symfony/symfony/blob/6a4de2278721d60deb42064764fcf72ee80446fd/src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php#L107

<hr>

**User context**

If I don't get it wrong, a page will never be cachable when a user is present. Wouldn't it be better to decide on the per-content-element-basis whether to cache this element instead of disabling cache entirely?

**Comment by Toflar** [comment]
No it's not ignored. The content will be `<esi....` 😄 Only if there's no surrogate capability (e.g. in app_dev.php) it will render `inline` instead of `esi`.



> If I don't get it wrong, a page will never be cachable when a user is present. Wouldn't it be better to decide on the per-content-element-basis whether to cache this element instead of disabling cache entirely?

It's not dependent on the user. It's dependent on the session. If the session is started, Symfony disables any caching by default. Which is a good default behaviour because it gets really complex otherwise. You can disable this though by setting a special response header if you're using Symfony 4.1 (see https://github.com/symfony/symfony/pull/26681).
