### ISSUE TITLE
Edge: cannot link to news article with TinyMCE

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#131]
**Affected version(s)**
4.6.6

**Description**  
Trying to link some text in the TinyMCE to a news article with the new picker will not work.

**How to reproduce**  

1. Use Microsoft Edge (tested with version 42.17134.1.0).
2. Log into the Contao Demo.
3. Edit any news article or regular article with a text content element.
4. Edit any text content element.
5. Select any text.
6. Click _Insert/edit link_.
7. Click the browse button for the URL.
8. Select _News_ in the page picker overlay.
9. Go into the _Contao Official Demo News_ archive.
10. Select any news article.
11. Click _Apply_.
12. Click _Ok_.

The text will not actually be linked. The _Insert/edit link_ and _Remove link_ buttons of TinyMCE will be active - however, there won't be an actual link. The source code view of TinyMCE also reveals, that no link has been inserted.

**Comment by ausi** [comment]
I can reproduce this issue in Edge.

**Comment by asaage** [comment]
Same applies to Files, Events, FAQ and Articles.
Only Pages do work.

**Comment by leofeyer** [comment]
I don't have Edge, therefore I cannot debug this. Please help.

**Comment by leofeyer** [comment]
Is this issue still relevant now that Edge uses Chromium?

**Comment by fritzmg** [comment]
I cannot reproduce this anymore in Microsoft Edge 44.18362.449.0
