### ISSUE TITLE
Tooltipps in Liste Benutzer für Icons links ergänzen

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1310]
Tooltipps in Liste Benutzer für Icons links ergänzen

**Comment by Toflar** [comment]
Bitte was?

**Comment by zonky2** [comment]
Backend: Listenansicht Benutzer - die Icons links haben kein Tooltipp

**Comment by netzarbeiter** [comment]
![Bildschirmfoto 2020-02-12 um 11 46 55](https://user-images.githubusercontent.com/1942550/74328026-7bbe0680-4d8d-11ea-98c4-893ccf2e80f2.png)
Meinst du diese Icons ohne Funktion?

**Comment by zonky2** [comment]
ja, mit dem Status als Tooltipp
Admin vs. Benutzer
aktiv vs. inaktiv
2FA

... für unbedarften User ist das m.E. nicht selbsterklärend - zumal es (nach meiner Durchsicht) auch im Manual nicht erklärt ist

**Comment by aschempp** [comment]
@zonky2 für sowas könntest du doch einen PR machen, dann wär das schneller gefixt?

**Comment by zonky2** [comment]
kann ich probieren - wollte erstmal Meinungsbild haben :D
