### ISSUE TITLE
Crawler usability

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#1312]
**Description**
I was testing out the new crawler. Unfortunately it did not work at all (log reports `Couldn't resolve host name for http://foo.local/.....` but thats another story.

More interesting is the fact that the UI, although an error occured, does not state any problems at all. Everything is green and says `0 URL(s) erfolgreich indexiert. 0 fehlgeschlagen.`

If a user has a big installation with many pages and multiple roots this could be a real problem.

As long as he does not open the debug log, which IMHO should only be available in debug mode, he will never know that something might not work at all. I've seen there's an option to search explicitly for broken links but since you already have the information that something went wrong why not pass it onto the user?

**Addition**

On further testing I noticed that crawling for broken links is quite strange.
My Demo-Installation only has a few pages (13 + News) but looking at the numbers and logs Contao crawls, in this case, more than 800 (!) external  pages. And again, the messages presented to the user are not quite reasonable since the numbers do not match up at all.

![crawler-2020-02-12 132144](https://user-images.githubusercontent.com/226890/74334969-5801bd00-4d9b-11ea-93d2-cf50f5882ca0.png)

**Comment by aschempp** [comment]
The stats are certainly corrrect. Be aware that this is a _Crawler_, it crawls your page and follows every link there is. That's not related to your page structure. For example, every news might have a detail page. Every calendar module possibly has 100 links to go forward and back in time to see different calendar items. A gallery content element might generate multiple pages of content with different images.

That's the whole advantage of the Crawler. It actually finds everything the same way a search engine (Google, DuckDuckGo, etc. does.

**Comment by bennyborn** [comment]
I totally get the use behind the Crawler but crawling on external pages not belonging to your Contao installation seems unnecessary (afair Escargo seems to be aware if an page is external) and I can image it could quite cause some trouble on some standard hostings where this might also violate the Terms of use.

Nonetheless if an error occurs the user should be notified. Stating "everything is okay" is just wrong.

**Comment by Toflar** [comment]
> I totally get the use behind the Crawler but crawling on external pages

It does not crawl external pages. It only requests the ones found on your page and only if you activated the broken link checker. You can see that from the debug log (on the top right, next to the progress bar).

**Comment by bennyborn** [comment]
> It does not crawl external pages [...]

Please see the attached debug log. These are definitely pages that are not linked within the Contao installation.

[crawl_debug_log.zip](https://github.com/contao/contao/files/4198932/crawl_debug_log.zip)

**Comment by Toflar** [comment]
That log looks correct to me?

**Comment by bennyborn** [comment]
Okay, small example: The installation links to `https://policies.google.com/privacy` on the privacy policy page. Crawler crawls this page and finds the link `https://myaccount.google.com/privacycheckup?utm_source=pp` and the message says `Did not index because it was not part of the base URI collection.`. Clearly if the crawler does indeed not crawl any external page, how would it find that link?

**Comment by Toflar** [comment]
I've just released `terminal42/escargot` 0.5.5. Can you check if that improves your results?

**Comment by bennyborn** [comment]
@Toflar Seems to work fine with 0.5.5. It recognizes the link to e.g facebook.com as an external domain and does not crawl any further 👍

**Comment by Toflar** [comment]
Can we close this issue then?

**Comment by bennyborn** [comment]
I did not have the chance to confirm the following point yet, has this been adressed as well?

> although an error occured, does not state any problems at all. Everything is green and says `0 URL(s) erfolgreich indexiert. 0 fehlgeschlagen.`

**Comment by Toflar** [comment]
No but not sure how to solve that. I mean, it‘s not really a bug. It might be that you have zero pages to index in which case the result is just fine :) If we turn that into an error, it‘s probably wrong too. It should probably just have a warning, what do you think?

**Comment by bennyborn** [comment]
If there are indeed no pages to be indexed the message would be fine. But if any of the pages to be indexed cannot be indexed, e.g. due to an error like in #1400 or in my case if the hostname cannot be resolved, I think it would be correct to state that those pages failed.

**Comment by Toflar** [comment]
Closing i favor of the other issue then.
