### ISSUE TITLE
Stop using document.write()

### ISSUE THREAD

**Issue by Toflar** [contao/contao#1313]
**Affected version(s)**

4.4+

**Description**

We still use `document.write()` for our jQuery, MooTools fallbacks and we should use `document.createElement('script')`. Also see https://developers.google.com/web/updates/2016/08/removing-document-write.

I could also see usages in `be_ace.html5`, `be_tinyMCE.html5`, `core.js` etc.

**Comment by leofeyer** [comment]
> Chrome will not intervene for scripts with a matching eTLD+1 (e.g. a script hosted on js.example.org inserted on www.example.org)

So the only problematic case would be if someone configures a completely different domain as assets URL, e.g. when using a CDN. Other than that, we are never loading external scripts via `document.write()` in Contao.

**Comment by Toflar** [comment]
`document.write()` also blocks rendering, so we should just not use it at all.


> Other than that, we are never loading external scripts via `document.write()` in Contao.

How come? I even mentioned other places where we use it.
https://github.com/contao/contao/blob/ce47fcbcf135f3cb98a74a8b11c94c404b5e9521/core-bundle/src/Resources/contao/pages/PageRegular.php#L402
https://github.com/contao/contao/blob/ce47fcbcf135f3cb98a74a8b11c94c404b5e9521/core-bundle/src/Resources/contao/pages/PageRegular.php#L437
https://github.com/contao/contao/blob/5edfc391bcb755854325b18eda90134acb30f5c6/core-bundle/src/Resources/contao/templates/backend/be_ace.html5#L8
https://github.com/contao/contao/blob/10a9fe48a6caf9bcef9f292af55a3b66543759fe/core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5#L8
https://github.com/contao/contao/blob/10a9fe48a6caf9bcef9f292af55a3b66543759fe/core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5#L8
[probably more...]

**Comment by leofeyer** [comment]
Yes, but none of these calls are cross-origin requests. They are all eTLD+1.

**Comment by Toflar** [comment]
They are still blocking and should be replaced. We should not use `document.write()` anywhere.

**Comment by leofeyer** [comment]
Agreed.

**Comment by leofeyer** [comment]
I have just tried to implement this, however, neither ACE nor TinyMCE will load if the script is added in a non-blocking way, because their init script relies on the main script being loaded beforehand. 🤷‍♂

**Comment by Toflar** [comment]
Can't we load everything async and execute the init after it was loaded?

```js
function addScript(src, callback) {
  var s = document.createElement('script');
  s.src = src;
  s.async = true;
  s.onload = callback;
  document.body.appendChild(s);
}
   
window.tinymce || addScript('tinymce.min.js', function() {
    tinymce.init({
        // ...
    });
});
```

**Comment by leofeyer** [comment]
As discussed in Mumble on February 13th, we cannot remove the `document.write()` in the front end, because we explicitly want the script to be loaded synchronously. In the back end, however, we could add the ACE/TinyMCE scripts via `$GLOBALS['TL_JAVASCRIPT']` and remove the `document.write()`.

**Comment by leofeyer** [comment]
```php
<?php

namespace Contao;

if ($GLOBALS['TL_CONFIG']['useRTE']):

$GLOBALS['TL_JAVASCRIPT'][] = TL_ASSETS_URL . 'assets/tinymce4/js/tinymce.min.js"';

?>
<script>
window.tinymce && tinymce.init({
  skin: 'contao',
  selector: '#<?= $this->selector ?>',
  language: '<?= Backend::getTinyMceLanguage() ?>',
  element_format: 'html',
  document_base_url: '<?= Environment::get('base') ?>',
  entities: '160,nbsp,60,lt,62,gt,173,shy',
  branding: false,
  setup: function(editor) {
    editor.getElement().removeAttribute('required');
  },
  init_instance_callback: function(editor) {
    if (document.activeElement && document.activeElement.id && document.activeElement.id == editor.id) {
      editor.editorManager.get(editor.id).focus();
    }
    editor.on('focus', function() { Backend.getScrollOffset(); });
  },
  file_browser_callback: function(field_name, url, type, win) {
    Backend.openModalBrowser(field_name, url, type, win, '<?= $this->source ?>');
  },
  file_browser_callback_types: <?= json_encode($this->fileBrowserTypes) ?>,
  plugins: 'autosave charmap code fullscreen image importcss link lists paste searchreplace stripnbsp tabfocus table visualblocks',
  browser_spellcheck: true,
  tabfocus_elements: ':prev,:next',
  importcss_append: true,
  extended_valid_elements: 'q[cite|class|title],article,section,hgroup,figure,figcaption',
  menubar: 'file edit insert view format table',
  toolbar: 'link unlink | image | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | undo redo | code'
});
</script>
<?php endif; ?>
```

**Comment by bennyborn** [comment]
I thought I'd answer to this issue since we just noticed a small problem with putting the script just into `$GLOBALS['TL_JAVASCRIPT']`.

We have a textarea with tinyMCE as part of a subpalette which is triggered by a checkbox. Since ticking the checkbox only loads the necessary fields from the subpalette via AJAX and does not reload the page in it's entirety, the script tag never gets added to the head and therefor the tinyMCE will not be initialized until we reload the page manually (or hit 'save').

So it would be best to go back to a pure JS solution like
```js
<script>
    var script = document.createElement('script');
    script.src = "<?= $this->asset('js/tinymce.min.js', 'contao-components/tinymce4'); ?>";
    document.getElementsByTagName('head')[0].appendChild(script);
</script>
```

@leofeyer Could you please reopen this issue?

**Comment by leofeyer** [comment]
Ah, that was the reason why we did not add it to `$GLOBALS['TL_JAVASCRIPT']` in the first place. 🤦‍♂

**Comment by bennyborn** [comment]
@leofeyer Maybe this ticket should be reopened? 

![image](https://user-images.githubusercontent.com/226890/105143877-b9c6bd00-5afc-11eb-90f0-5324e542303a.png)

After all no solution was ever implemented.
