### ISSUE TITLE
Static Layout of #wrapper is not working (4.8.7 API version 2)

### ISSUE THREAD

**Issue by lolohz** [contao/contao#1314]
Contao 4.8.7 (API version 2)
PHP 7.3 API 20180731 

Hello
Static Layout (Overall width and Alignment) of #wrapper is not working for me.

Themes > Any Theme > Page layouts › Edit page layout | Static layout 

It seems the generated html always put the Static Layout style section before the tag that includes internal styles so "layout.min.css,responsive.min.css,grid.min.css,colorbox.min.css,...-6224921c.css" is overwriting that static layout style section.

Best regards.
![StaticLayout02](https://user-images.githubusercontent.com/36300963/74381807-6deb9e00-4dec-11ea-9239-37a91e96a2e3.png)
![StaticLayout01](https://user-images.githubusercontent.com/36300963/74381808-6f1ccb00-4dec-11ea-887d-a813d75c4cc2.png)

**Comment by leofeyer** [comment]
How do I reproduce this issue in the online demo?

**Comment by lolohz** [comment]
Hi Leo
I'm attaching some screenshots.

Thanks and Regards.

![Layout1column-001](https://user-images.githubusercontent.com/36300963/74769818-5c424480-528b-11ea-96f7-3dd0b58f7f5d.png)
![Layout1column-002](https://user-images.githubusercontent.com/36300963/74769820-5cdadb00-528b-11ea-9261-80c74ea26276.png)
![Layout1column-003](https://user-images.githubusercontent.com/36300963/74769816-5c424480-528b-11ea-8951-ccdfb5b14085.png)
![Layout1column-004](https://user-images.githubusercontent.com/36300963/74769814-5c424480-528b-11ea-9dff-47515d2757c9.png)
![Layout1column-006](https://user-images.githubusercontent.com/36300963/74769808-5b111780-528b-11ea-988d-805ab9b69d09.png
![Layout1column-007](https://user-images.githubusercontent.com/36300963/74770270-35384280-528c-11ea-8be3-08df54ec466f.png)

**Comment by leofeyer** [comment]
It seems that the CSS of the Contao Official Demo does not account for this option, which is OK I guess, because the Official Demo does not use the internal CSS framework.

**Comment by lolohz** [comment]
Hello Leo
Excuse me, I didn't understood your answer.The fact was that the "Overall width" didn't work in https://demo.contao.org.
What is that option for?
When it is possible to use it?
Should Demo Package be updated to allow set 100% for its width?

Best regards.

**Comment by lolohz** [comment]
Hello again
Now it is clear for me.
Oh, I just read your answer in https://github.com/contao/contao/pull/1585


"The fact that no one noticed this for such a long time shows that most people do not use the layout builder anymore (which is good, because it is old and deprecated in favor of a yet to be developed grid/flex solution)."

"Turns out that this is a bug in the Contao Official Demo"

Tx a lot!
