### ISSUE TITLE
Must set no-store on insert tags controller

### ISSUE THREAD

**Issue by Toflar** [contao/contao#132]
Here: https://github.com/contao/contao/blob/master/core-bundle/src/Controller/InsertTagsController.php#L52

`else` should be `no-store`.

**Comment by leofeyer** [comment]
This is a bugfix for Contao 4.4, right?

**Comment by Toflar** [comment]
Yes! Sorry, I've just quickly created an issue so I don't forget about it rather than creating a proper PR :)

**Comment by leofeyer** [comment]
Never mind. 😄

**Comment by leofeyer** [comment]
Fixed in 5b8a39667f3cc6b0b554f97aa0cb5854e3dcc9c9. Thank you @Toflar.
