### ISSUE TITLE
Image files of imported Themes are not been aplied in frontend (4.8.7 API version 2)

### ISSUE THREAD

**Issue by lolohz** [contao/contao#1325]
Contao 4.8.7 (API version 2)
PHP 7.3 API 20180731
Linux 4.4.59+ #23824 SMP PREEMPT Fri Oct 26 18:34:33 CST 2018 x86_64 GNU/Linux apollolake

Hello
I imported a very simple Theme that contains images for text articles. As the images were not shown in the frontend I checked one of the articles that contained a image. It was not showed in the list, but in the selection window was fine.

Articles › Slider › Content elements › Edit content element ID 327 | Add an image

It seems the files when importing themes are saved in /contao/files/ and when using the Frontend Contao try to load those files from /contao/web/files/
Contao Official Demo theme works fine because there is a link from /contao/web/files/ to ../../files/contaodemo which is another link to /contao/vendor/contao/official-demo/src/files/contaodemo where all files actually exists.
I made a link from /contao/web/files/mytheme to /contao/files/mytheme and the issue was fixed.
It would convenient unify those paths (/contao/files/ and /contao/web/files/) having only one?

Best regards.
![themes001](https://user-images.githubusercontent.com/36300963/74492446-37d31a80-4ecf-11ea-8388-b3f03605c053.png)

**Comment by xchs** [comment]
Did you set the relevant folders to "Public"? Only then the resources get symlinked in the document root so that they are publicly available.

**Comment by lolohz** [comment]
Hello xchs
Excuse me, I didn't understand your question. What did you mean when you asked about "set" relevant folders to public? Are you talking about some access attributes of the /contao/web/files folder?

Thanks and Regards.

**Comment by xchs** [comment]
No, I am talking about the corresponding option in the folder settings (Contao administration area > File manager > Edit the folder settings).

**Comment by asaage** [comment]
> Did you set the relevant folders to "Public"?

shouldn't the theme-export/import include the ```.public``` zerobyte-files?
Maybe just Recreate the symlinks under System->Maintenance

**Comment by lolohz** [comment]
Hello
Uhm, I'm convinced there is an error managing that folder: "Contao Official Demo" package create that symlink (it is not only a Theme, but a package that is able to create that symlink). 

I have no folders in the File Manager, even after synchronizing , so there is no options to do anything.
I cannot see any option for creating symlinks in System->Maintenance. I have only three options: Enable maintenace mode, Rebuild Index and Purge data.
On the other hand, an undocumented zero file named .public in any place seems too estrange for me as a valid solution, it is more easy make the symlink by my self.

Thanks and Regards.

**Comment by xchs** [comment]
Please refer to the [forums](https://community.contao.org/). There we can discuss the problem in more detail. You obviously have a problem with your installation.

**Comment by lolohz** [comment]
Hello again
I would like to discuss the problem there. I'm waiting my account to be activated. But I think I have good news and it are not be necessary.
I made a clean installation (4.8.8) to check all installation steps and all worked fine, even Contao-Manager package installation. I installed Contao Official Demo and it created the link. After that I created a folder in Folder Manger and check "Public" check box. Another link was created fine. But by chance I changed to debug mode and when I tried to back to the normal mode and this error was shown "**Failed to create /volume1/contao/contao4.8/var/cache/prod/translations mkdir(): Permission denied**". 
![mkdir-error](https://user-images.githubusercontent.com/36300963/74692843-61e74e00-51e9-11ea-893e-d543e7af9a7b.png)
![mkdir-error001](https://user-images.githubusercontent.com/36300963/74692937-d28e6a80-51e9-11ea-8c0f-4841f9be0dde.png)

I realized that my **php was running as root instead of as http user** and created those files as root, so I changed the ownership to http users of the whole cache folder and it worked well again.  I think that this issue could be related with this problem. 
I changed again the ownership of all files of contao root folder to http user and changed permissions to 755. Then I imported the theme without problems and I could see all folders and files of my theme in File Manager!
Unfortunately I cannot change the user execute php in the web server. If I install Contao leaving root as the owner Contao doesn't work. If I change the owner to the web user (http) and set the permission to 755 Contao works except in some cases. 
So I am going to make more tests to discover how to resolve this limitation. At this moment I don't know if this is an issue or merely my server is not able to run Contao. Could you advise me about what to do with this issue? Should I close or someone should analyze this web server configuration?

Thank you very very much by your support!
Regards.
