### ISSUE TITLE
Fehler in Dateiverwaltung / Icons bei Ordner für eingeschränkter Nutzer fehlen

### ISSUE THREAD

**Issue by chopsol** [contao/contao#1326]
In der aktuellen Version 4.9-RC2 werden bei einschränkten Benutzern die neu angelegt werden in der Dateiverwaltung die Icons bei den Ordnern nicht angezeigt. (in 3 Installationen getestet)

Anzeige beim eingeschränkten Nutzer:
![ordner-user](https://user-images.githubusercontent.com/12293848/74517322-32e38a80-4f12-11ea-8a85-a232d5d4993d.png)

Anzeige für Administrator:
![ordner-admin](https://user-images.githubusercontent.com/12293848/74517303-27905f00-4f12-11ea-9fbf-7330ed7f205c.png)

Wenn ein Nutzer mit den eingeschränkten Rechten aus einer 4.4 mit ce_access auf die 4.9-RC2 aktualisiert wird, ist sind die Icons vorhanden! (lediglich einmal geprüft)

**Comment by leofeyer** [comment]
Ich kann das Problem nicht reproduzieren. Folgendes habe ich gemacht:

* Einen neuen BE-Benutzer angelegt.
* Diesem Zugriff auf die Dateiverwaltung gegeben und einen Ordner gemountet.
* Wechsel zu dem neu angelegten Benutzer.
* Aufruf des Dateimanagers -> die Icons sind da.

**Comment by aschempp** [comment]
@chopsol ev. hast du die Berechtigungen nicht korrekt konfiguriert?

<img width="574" alt="Bildschirmfoto 2020-02-18 um 12 18 26" src="https://user-images.githubusercontent.com/1073273/74731697-ce456a00-5248-11ea-8ebc-b68c7646a919.png">

**Comment by chopsol** [comment]
@aschempp die Zugriffsrechte bei mir sehen exakt so aus.
Ich hatte es bisher nicht über die Zugriffsrechte des Benutzers sondern über Gruppenrechte realisiert, aber auch ein frischer Test mit einem Benutzer bei dem ich nur die Zugriffsrechte für die Dateiverwaltung und die von Andi im Screenshot gezeigten Rechte gesetzt habe, zeigt das gleiche Problem.
Ich werde es morgen mal mit der finalen 4.9 mir noch mal anschauen.

**Comment by contaoacademy** [comment]
Es sieht so aus, als ob die Icons nur auf der obersten Ebene (/files/xxx) fehlen.
(siehe Screenshot)
![files](https://user-images.githubusercontent.com/23719181/74870840-b2ca8400-535a-11ea-8cf0-7ab30ee2ec8d.jpg)

**Comment by chopsol** [comment]
Wie @contaoacademy schreibt fehlen die Icons nur für die Ordner in der obersten Ebene. Diesen waren bisher wie beiden Unterordnern grau / inaktiv - nur jetzt fehlen sie komplett und damit fehlt auch die Möglichkeit über das grüne + direkt beim Ordner den Upload für neue Bilder zu starten.
![screen](https://user-images.githubusercontent.com/12293848/75013019-a3932580-5483-11ea-906e-4e398565e34b.png)

**Comment by leofeyer** [comment]
Ich hab das gerade nochmal mit einer alten 3.5er-Installation verglichen und auch da werden mir keine inaktiven Buttons für die Folder-Mounts angezeigt. Einzig das grüne "Upload"-Icon scheint in Contao 4.9 zu fehlen.

<img width="745" alt="" src="https://user-images.githubusercontent.com/1192057/75029349-317e0900-54a2-11ea-802f-8c49b737849b.png">

Könnt ihr bitte mal einen Screenshot von Contao 4.4 hochladen, auf dem die grauen/inaktiven Buttons zu sehen sind?

**Comment by chopsol** [comment]
Bei meinen 4.4er Installationen ist es ebenso wie bei @leofeyer; es wird nur das grüne "Upload"-Icon und keine grauen/inaktiven Icons angezeigt. Es fehlt also nur das Upload-Icon.
