### ISSUE TITLE
Backend: "Zurück"-Button im Bearbeitungsmodus sollte nie eine Speicherung von Änderungen auslösen

### ISSUE THREAD

**Issue by jochi44** [contao/contao#1328]
**Affected version(s)**
getestet: 4.4, 4.8, 4.9-RC2

**Description**
Wird im Backend z.B. eine Seite oder ein Artikel bearbeitet und eine Änderung durchgeführt, der Bearbeitungsmodus dann jedoch ohne zu speichern (Buttons unten) mit "Zurück" (rechts oben) verlassen, werden die Änderungen (ungewollt) gespeichert.
Die "Zurück"-Schaltfläche sollte wirklich nur "zurück" gehen, ohne Änderungen zu speichern.

**How to reproduce**
Beispiel:
1. Layout -> Seitenstruktur -> eine Seite bearbeiten
2. Unter "Zugriffsrechte" die Schaltfläche "Zugriffsrechte zuweisen" anhaken
3. Bearbeitungsmodus mit der "Zurück"-Schaltfläche rechts oben verlassen
4. Kontrolle durch erneutes Bearbeiten der Seite -> Häkchen bei "Zugriffsrechte zuweisen" ist da, obwohl die Änderung nicht explizit mit den "Speichern"-Buttons bestätigt wurde

**Comment by fritzmg** [comment]
This is a known limitation. Any `submitOnChange` checkbox will cause the edit form to be submitted, on change, as the name suggests. And at that point, the changes are saved.

**Comment by jochi44** [comment]
OK, I didn't find anything related on this subject via the github search function. I'll close this issue.
