### ISSUE TITLE
Elementyp Artikel gibt umschließendes <div class=“mod_article”> mit aus

### ISSUE THREAD

**Issue by CONTEGRA** [contao/contao#1334]
Version:  4.9.0-RC2

Bei Verwendung des Elementyp Artikel wird das umschließende `<div class=“mod_article”>` des einzubindenden Artikels mit ausgegeben und nicht wie vorher nur die Inhaltselemente. Bug oder Feature?

**Comment by zonky2** [comment]
hat es was damit zu tun?
https://community.contao.org/de/showthread.php?71069-insert_article-mit-und-ohne-container

**Comment by CONTEGRA** [comment]
Sorry es lag tatsächlich an der alten 3er mod_article.html5, die unverändert ist aber natürlich trotzdem geladen wurde.
