### ISSUE TITLE
Überschrift "Migration" beim Install-Tool

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1337]
In das Polyfill-Bundle wird die Migration eingearbeitet - siehe https://github.com/contao-community-alliance/contao-polyfill-bundle/pull/2

Bei den Tests ist aufgefallen, dass eine Überschrift wie "Migration" o.ä. für das Ausgabefenster schön wäre - Meinung dazu?

![Migration](https://user-images.githubusercontent.com/1045318/74566183-34916a80-4f73-11ea-9382-579ea28b7d55.png)

**Comment by aschempp** [comment]
Für welches Ausgabefenster? Für die gelbe Box? Gibt es die im Contao Core auch?

**Comment by discordier** [comment]
@aschempp hier: https://github.com/contao/contao/blob/master/installation-bundle/src/Resources/views/main.html.twig#L14

**Comment by zonky2** [comment]
ja, die gelbe Box - die kommt von Contao 4.9 - wir befüllen die nur....

**Comment by leofeyer** [comment]
IMHO braucht es an der Stelle keine Überschrift.

**Comment by baumannsven** [comment]
@leofeyer Warum nicht? Gelbe Box was ist da drin. Wie bringst du das den Anwendern bei?

**Comment by zonky2** [comment]
IMHO schon - insbesondere, da das Fenster neu ist und für "Verwirrung" sorgen könnte...

**Comment by leofeyer** [comment]
> da das Fenster neu ist und für "Verwirrung" sorgen könnte

Keine Ahnung was Du damit meinst. Den gelben Kasten gibt es seit Contao 4.0. 🤷‍♂ 

https://github.com/contao/installation-bundle/blob/4.4/src/Controller/InstallationController.php#L382-L388

**Comment by zonky2** [comment]
o.k. - dann zumindest bisher noch nie (bewusst) gesehen... aber o.k. - Du bist der Chef...

**Comment by zonky2** [comment]
Schade...
