### ISSUE TITLE
error message or notice when cookies are disabled

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#134]
If the user has disabled cookies in their browser, the user will be unable to submit any POST forms on the Contao website. He will always only see the "Invalid request token" error page (which will be meaningless to the user).

Wouldn't it make sense to integrate some sort of error message within Contao telling the user that he cannot send forms on the website, if they disabled cookies in their browser?

Or - may be the "Invalid request token" error page should be revamped and include a user friendly description that this could be due to disabled cookies in their browser. The current description does not mention that at all.

However a notice _before_ sending the form would be preferable. Imagine having a really long form which the user painstakingly fills out. Then the user sends and all their data is lost, because they only see the error message.

**Comment by leofeyer** [comment]
I like the idea. @contao/developers Any objections?

**Comment by Toflar** [comment]
I think both should be done :)

**Comment by fritzmg** [comment]
In one project I did something like this:
```php
/**
 * Inserts cookie check.
 */
public function onCompileFormFields($arrFields, $formId, Form $objForm)
{
    if ('POST' === $objForm->method && !Config::get('disableRefererCheck')) {
        $GLOBALS['TL_BODY'][] = (new FrontendTemplate('cookie_check'))->parse();
    }

    return $arrFields;
}
```
```html
<!-- cookie_check.html5 -->
<div class="cookie-check-overlay">
  <div class="cookie-check-overlay__content">
    <h2>This page uses Cookies</h2>
    <p>You need to enable cookies in order to use the full functionality of this page.</p>
    <button type="button">Ok</button>
  </div>
</div>
<script>
(function($, undefined) {
  'use strict';
  var cookieEnabled = (navigator.cookieEnabled) ? true : false;
  if (undefined === navigator.cookieEnabled && !cookieEnabled) { 
    document.cookie = "testcookie";
    cookieEnabled = (document.cookie.indexOf("testcookie") != -1) ? true : false;
  }
  if (!cookieEnabled) {
    var $overlay = $('.cookie-check-overlay');
    $overlay.fadeIn(200);
    $overlay.find('button').click(function() {
      $overlay.fadeOut(200);
      return false;
    });
  }
})(jQuery);
</script>
```
May be we could integrate the same in Contao - though with a more simple `cookie_check` template (may be just a JavaScript `alert`), that users then adjust to their needs.

**Comment by aschempp** [comment]
How can one disable cookies? And aren't they then used to tons of websites breaking?

**Comment by fritzmg** [comment]
Cookies can be disabled in the browser settings. And yeah, may be the amount of people who are doing this is not really that significant. But we had a few cases at least.

**Comment by birdmedia** [comment]
As the complaints about this error are increasing - is there any solution to this problem? Should users with disabled cookies really be prevented from using contact forms? Aren't there any more convenient solutions? In terms of security, I can't fully evaluate how critical it would be to disable the request tokens / cookies.

**Comment by fritzmg** [comment]
@birdmedia are you using the latest Contao and dependency versions? There was an issue where this could occur even if you have cookies enabled. See https://github.com/contao/website/issues/109

**Comment by birdmedia** [comment]
@fritzmg The problem seems to occur in 4.6.6 and previous versions. I will have a look at it, thank you. The  question concerning cookies is still pending. 😉

**Comment by leofeyer** [comment]
Visitors can no longer send forms in Contao 4.6 if they have disabled cookies, because we are now using a technique called "double submit cookie" to prevent cross-site request forgery (CSRF) attacks. This is nothing we can change (or you should disable), because Contao would be vulnerable to this kind of attack then.

So a warning in the form (or even a disabled submit button) seems a reasonable improvement to me.

**Comment by leofeyer** [comment]
Implemented in e9c3279b8f81a9b1a59c3c45d52e5ae2373f7a11.

**Comment by xchs** [comment]
Is it intended that this note is only displayed for forms created with the Contao form generator?

Because I can still submit **comment forms** without being notified that cookies are disabled in the browser.

**Comment by leofeyer** [comment]
It actually affects all forms that generate POST requests (login, registration, etc.). But do we really want to clutter the HTML code with multiple warnings that is never shown to 99.999% of the users?

**Comment by xchs** [comment]
> It actually affects all forms that generate POST requests (login, registration, etc.)

I tested this new feature in the Contao Official Demo and was just wondering why this warning is only displayed for the contact form and not for the comment form as well.

> But do we really want to clutter the HTML code with multiple warnings that is never shown to 99.999% of the users?

No, not really!

**Comment by Toflar** [comment]
What about extracting that info in a JS template that searches for forms containing an input with name `REQUEST_TOKEN`. It can generate the `div` on the fly above every `form`. It would then be completely optional (enable it in the page layout if you want to) and it can be hidden using CSS in the forms you don‘t want to show it.

**Comment by fritzmg** [comment]
I like the `js_` template approach :)

**Comment by leofeyer** [comment]
I have thought about this as well, however, this only works if people enable the template in their page layout, which should not be required for a warning that applies to all installations.

**Comment by Toflar** [comment]
Then do not make it configurable. The JS only solution would not clutter the HTML and work for all forms on the page :)

**Comment by aschempp** [comment]
I think the comments form would really make sense, too. But not stuff like the login form…

**Comment by leofeyer** [comment]
I have added a `js_` template in f85d810376eb12a8ad07aa475be714c050e7fd11.
