### ISSUE TITLE
Enter does not submit the user field in the preview bar

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1343]
**Affected version(s)**

4.9.*

**Description**

If you change the username in the preview bar and hit "Enter", the form is not submitted. I assume we have to adjust the dataliast JavaScript?

@richardhj @aschempp /cc

**Comment by richardhj** [comment]
When I select and mouse-click a username from the option list and hit enter, the form is submitted. If this does not work for you, what browser are you using?

Unfortunately, in Firefox hitting Enter when selecting a username with the keyboard, pressing enter does not select the option. But I think, this is a Firefox issue? In Safari and Chrome, I can select an option with the enter key and press enter again to submit the form.

Tested in Safari, Chrome, and Firefox. Overall, looking good for me

**Comment by leofeyer** [comment]
What happens if you enter a username manually and then hit Enter?

**Comment by leofeyer** [comment]
I think I found the issue. After manually entering the username, the first Enter will close the option list and only the second Enter will submit the form.
