### ISSUE TITLE
Crawler does not work without domain name on CLI

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1344]
**Affected version(s)**

4.9.*

**Description**

If the root page in the site structure does not contain a domain name, the crawler assumes `localhost`, which is not correct on my system. I am missing a parameter to pass the correct domain name to the contao:crawl command in such a case.

@Toflar /cc

**Comment by Toflar** [comment]
Configure the domain? It makes no sense not to do so, we‘ve even discussed making it mandatory sometime.

**Comment by Funbug** [comment]
I leave it blank for almost every non-multidomain website. It's just one more thing I don't have to change when switching from dev to prod.

**Comment by leofeyer** [comment]
I am doing it the same way as @Funbug.

> we‘ve even discussed making it mandatory sometime

It is not mandatory at the moment, therefore we should handle this case and add an argument to the command instead of forcing everyone to fill in the domain name – which may not be possible depending on the use case anyway.

**Comment by Toflar** [comment]
But maybe `localhost` is correct? We're just using `$pageModel->getAbsoluteUrl()`, how are we supposed to know if that's the desired host or just the fallback?
Would you check if `dns` was left empty and do this only on CLI?

**Comment by leofeyer** [comment]
IDK. Let's discuss this in the next call.

**Comment by m-vo** [comment]
I also leave this blank in nearly all installations for the said reasons.

However: In many scenarios the domain is also needed when deploying (in order to clear the opcache). So having this property accessible would be help there as well.

**Comment by ausi** [comment]
I used the `router.request_context.*` parameters for this use case in my projects: <https://symfony.com/doc/current/routing.html#generating-urls-in-commands>

**Comment by fritzmg** [comment]
> I used the `router.request_context.*` parameters for this use case in my projects: https://symfony.com/doc/current/routing.html#generating-urls-in-commands

I was about to suggest the same :)

**Comment by Toflar** [comment]
The fix is actually pretty simple. I think having `https?://localhost` is always wrong, isn't it? It can never be the desired domain. You always need to have some domain name even when working locally. The use case that you only ever have one Contao setup locally and it's the only one listening to port 80 on localhost is highly, highly unlikely.

So I would just add a check for that on CLI and if any of them contains that, emit a warning providing the two possible solutions (either configure a domain or use `router.request_context.*`).
Wdyt?

**Comment by fritzmg** [comment]
Technically you can run several Contao installations under localhost. Contao specifically allows this. But I am all for emitting a warning :)

**Comment by Toflar** [comment]
Only if you have a port assigned.
I would emit a warning on `if (preg_match('@^https?://localhost(?!:).*$@'...`.

**Comment by fritzmg** [comment]
> Only if you have a port assigned.

No, you can run them alongside each other:

* https://localhost/contao1/web
* https://localhost/contao2/web
* https://localhost/contao3/web
* …

**Comment by Toflar** [comment]
Not when leaving the `dns` field empty.

**Comment by fritzmg** [comment]
No, the `dns` field can stay empty. Just tried it, I can access all of my local Contao installations via `https://localhost/<foldername>/web/(app.php)`. Contao only disallows this, when the hostname is _not_ `localhost`.

**Comment by Toflar** [comment]
It doesn't matter where you can access it? I'm talking about what `$pageModel->getAbsoluteUrl()` will give you on CLI because this is the problem we're talking about here.

**Comment by fritzmg** [comment]
Yes of course, I am simply commenting on this:

> You always need to have some domain name even when working locally. The use case that you only ever have __one__ Contao setup locally and it's the only one listening to port 80 on localhost is highly, highly unlikely.

I am just showing that it is perfectly possible to develop several Contao installations accessible via `localhost:80`, not just one. Running all your Contao installations on `localhost` was probably very common at some point, but hopefully not anymore, after that long of a time since the release of Contao 4.

**Comment by Toflar** [comment]
Yes but that doesn't matter for this discussion. If you have this setup, you will still get `http(s)://localhost` for all of them on CLI, wouldn't you?

**Comment by fritzmg** [comment]
Yes, of course. I am just saying it's possible - and the crawler would work fine in that case. But regardless, the warning should be emitted in that case, imho.

**Comment by aschempp** [comment]
> I am just showing that it is perfectly possible to develop several Contao installations accessible via `localhost:80`, not just one. Running all your Contao installations on `localhost` was probably very common at some point, but hopefully not anymore, after that long of a time since the release of Contao 4.

That was added to allow local development of multiple Contao installations. Although I agree the crawler should always support that (as I don't see a reason why it should not), I can't think of a reason anyone would crawl the localhost (except for testing purposes 😆 )

**Comment by Toflar** [comment]
So? We leave it as is because it's just a misconfiguration and we cannot know if it is or if it's not?

**Comment by fritzmg** [comment]
No, I am in favor of showing the warning anyway.

**Comment by Toflar** [comment]
Always? Or when? Can you guys please get a bit more specific in solutions?

**Comment by fritzmg** [comment]
Yes, always show the warning, if the crawler defaults to `localhost`. Unless someone has specifically used `localhost` in the `dns` settings, or in the `router.request_context.*` setting I suppose - but I think we can ignore that ...

**Comment by Toflar** [comment]
Closing in favor of https://github.com/contao/contao/pull/1385
