### ISSUE TITLE
Security encoder support in ^4.8 breaks extension

### ISSUE THREAD

**Issue by ben-eSM** [contao/contao#1345]
**Affected version(s)**
^4.8
**Description**
Due to the change in a9d5000a89d93ab6f5ee79f83fe43f6c4f6a2f9f to use the Symfony security encoder, the registration module throws an empty password exception if used with the terminal42/contao-mailusername extension due to the following validation.
https://github.com/contao/contao/blob/c9e195891d08bdb26504c394775cf956f23bf719/core-bundle/src/Resources/contao/modules/ModuleRegistration.php#L225
The username post variable is empty because the module will set the email address as username afterwards.
**How to reproduce**
Install the extension terminal42/contao-mailusername in a Contao 4.8 system and implement a registration form with password and email fields.

I know it's not necessarily a contao core issue, but since @Toflar who is also contributor to the aforementioned extension commited the change, it should be mentioned.

**Comment by Toflar** [comment]
I think you should report that issue in the mentioned extension because it doesn't look like the Contao core is related here. And I have no clue about that extension at all, I didn't work on it other than some tiny adjustments back in 2013 🤷‍♂

**Comment by ben-eSM** [comment]
All right then. To the extension the ticket goes. :)

**Comment by aschempp** [comment]
However, the core might want to catch that exception, and at least display a meaningful error message?
