### ISSUE TITLE
Legacy Modules only working in Debug Mode

### ISSUE THREAD

**Issue by mrwhy-orig** [contao/contao#1346]
**Affected version(s)**
4.9-RC2

**Description**
I'm trying to use a legacy backend module(3.5.*) in 4.9-RC2. It is working in Debug Mode. In production mode it isn't loaded.

**How to reproduce**
Put a legacy 3.5 Contao Module in the system/modules folder. In Debug Mode it is getting displayed in backend, with production mode it isn't.

Is there anywhere a config I'm missing to activate legacy modules?

**Comment by bennyborn** [comment]
Besides #1311 I did not notice any problems with 3.5 modules in 4.9 yet...

**Comment by mrwhy-orig** [comment]
Ok. My problem was the prod cache. It's not getting deprecated as soon you use the cache clearing options. Is something like a dev mode planned? Or is the Debug Mode for this implemented? Do I have to manually clear the cache on production sites if I'm going to add legacy modules?

**Comment by bytehead** [comment]
After adding modules you'll always have to clear the cache, especially in production environment. Afaik the cache is disabled in dev.
