### ISSUE TITLE
Übersetzung MSC.noTrustedDevices

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1352]
Die Übersetzung ``MSC.noTrustedDevices`` müsste statt ``Zurzeit sind keine vertrauenswürdige Geräte vorhanden.`` korrekt ``Zurzeit sind keine vertrauenswürdigen Geräte vorhanden.`` heißen.

https://github.com/contao/contao/blob/bf87609767e5623d9da8b98920683bef2d651997/core-bundle/src/Resources/contao/languages/de/default.xlf#L2644-L2647

**Comment by leofeyer** [comment]
Ich habe die deutsche Übersetzung angepasst.
