### ISSUE TITLE
Crawler: Argument 2 passed to Symfony\Component\HttpClient\CurlHttpClient::createRedirectResolver() must be of the type string, null given

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1353]
Der über die Systemwartung gestartete Crawler bleibt nach einiger Zeit stehen und im Log ist folgende Fehlermeldung zu finden:

> [2020-02-18 23:08:47] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://xxx/contao?act=crawl&crawl_subscriber_names%5B0%5D=broken-link-checker&do=maintenance&jobId=e765f2a3-ec58-4786-bba8-4b513538a47c&ref=ZBaLlR7C","method":"POST"} []
> [2020-02-18 23:09:08] request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 2 passed to Symfony\Component\HttpClient\CurlHttpClient::createRedirectResolver() must be of the type string, null given, called in /www/htdocs/xxx/vendor/symfony/http-client/CurlHttpClient.php on line 311" at /www/htdocs/xxx/vendor/symfony/http-client/CurlHttpClient.php line 460 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 2 passed to Symfony\\Component\\HttpClient\\CurlHttpClient::createRedirectResolver() must be of the type string, null given, called in /www/htdocs/xxx/vendor/symfony/http-client/CurlHttpClient.php on line 311 at /www/htdocs/xxx/vendor/symfony/http-client/CurlHttpClient.php:460)"} []

**Comment by Toflar** [comment]
Wie kann das reproduziert werden? Imho kann das nur passieren, wenn eine komplett invalide URL requested wird. Ggf. kannst du schauen, was denn als 2. Argument übergeben wird?

**Comment by Mynyx** [comment]
Mit den aktuellen Versionen kann ich das Problem nicht mehr nachvollziehen.
