### ISSUE TITLE
Migration loop

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/contao#1357]
**Affected version(s)**
Contao 4.9.0
PHP 7.4.2
MariaDB 10.4 (Strict Mode)

**Description**
Der Migrationsprozess bildet eine Endlosschleife.

**How to reproduce**
1. Wenn ich `contao:migrate` ausführe will er `tl_user_group.fields` und `tl_user_group.elements` löschen da sie nicht mehr im DCA vorhanden sind. Normales Verhalten.

2. Dann möchte er die Migration `Contao\CoreBundle\Migration\Version409\CeAccessMigration` ausführen und fügt die Felder wieder hinzu.

3. Siehe 1. 

Im Install-Tool das selbe, ich fürchte die Migration wird im Hintergrund ausgeführt und es stehen immer die Felder zur Löschung an:

```
ALTER TABLE tl_user_group DROP fields
ALTER TABLE tl_user_group DROP elements
```

**Comment by leofeyer** [comment]
> 1. will er `tl_user_group.fields` und `tl_user_group.elements` löschen da sie nicht mehr im DCA vorhanden sind. Normales Verhalten.

Das ist kein normales Verhalten, da diese beiden Felder sehr wohl im DCA vorhanden sind.

https://github.com/contao/contao/blob/240d9868432754082109e14e24be74a42a6cb021/core-bundle/src/Resources/contao/dca/tl_user_group.php#L137-L158

Hast Du den Symfony-Cache nach dem Update geleert?

**Comment by Tastaturberuf** [comment]
> Das ist kein normales Verhalten, da diese beiden Felder sehr wohl im DCA vorhanden sind.

Ich guckte im `tl_membe_group`... 🙈

> Hast Du den Symfony-Cache nach dem Update geleert?

Nicht manuell, nein. Ich bin davon ausgegangen das der ScriptHandler das hier macht:

```
 // Clearing the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.


 // Warming up the cache for the prod environment with debug false


 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
```

Wie so oft war es letztlich wieder mal der dumme Cache... bzw. nicht daran zu denken.

**Comment by m-vo** [comment]
Vielleicht sollten wir vor der Aussicht des migrate commands immer den Schema cache invalidaten/neu aufbauen. :thinking:  Das Install Tool macht ja stets ein cache:clear (IIRC).

**Comment by Tastaturberuf** [comment]
Genau das hatte ich mir mal in irgendeiner Slack-Diskussion gewünscht, man will doch niemals die gecachte Migration haben. Das Install-Tool macht das auch nicht, sonst hätte es ja dort geklappt.

**Comment by ausi** [comment]
> Vielleicht sollten wir vor der Aussicht des migrate commands immer den Schema cache invalidaten/neu aufbauen. 🤔

Aber wenn der ScriptHandler nach dem update den Cache geleert hat, muss es ja an etwas anderem liegen? Läuft der migrate command vielleicht nicht im prod environment und nur das wird beim update geleert?

**Comment by Tastaturberuf** [comment]
Martin hat mich auf die Spur gebracht. Die Installation hat eine `.env` und die ist auf `APP_ENV=dev`. Der ScriptHandler berücksichtigt das Enviroment nicht, die `contao-console` schon.

**Comment by Tastaturberuf** [comment]
Dennoch würde ich es während der Entwicklung vorziehen die aktuelle Migration zu haben. Entweder durch z.B. `contao-migrate --no-cache` oder weil das Command das Enviroment checkt und bei `dev` den Cache invalidiert. Ja ich weiß man kann das chainen, is aber hässlich:
 `vendor/bin/contao-console cache:clear && vendor/bin/contao-console contao:migrate`. 

Im Zweifel lebe ich aber damit.

**Comment by fritzmg** [comment]
Related: https://github.com/contao/contao/pull/1369

**Comment by leofeyer** [comment]
This should be fixed in #1369.
