### ISSUE TITLE
Meldung "Contao 4.x.0 Update executed successfully" im Installtool nicht übersetzt

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1358]
Wenn das Installtool nach einem Upgrade von Contao 4.4 auf Contao 4.9 erstmalig aufgerufen wird, erscheinen folgende Meldungen:

````
Contao 4.5.0 Update executed successfully
Contao 4.6.0 Update executed successfully
Contao 4.7.0 Update executed successfully
Contao 4.8.0 Update executed successfully
````

Die Meldungen sind nicht übersetzt.

**Comment by leofeyer** [comment]
The message is part of the migrations framework (see [AbstractMigration](https://github.com/contao/contao/blob/4.9/core-bundle/src/Migration/AbstractMigration.php#L25)), therefore it does not need to be translated IMHO. @contao/developers WDYT?

**Comment by Toflar** [comment]
No need. This is technical stuff and should remain technical.
