### ISSUE TITLE
Problem mit vordefinierten Bildgrößen

### ISSUE THREAD

**Issue by pr1601com** [contao/contao#1360]
**Contao 4.9/4.8**

Bei einer frischen Contao 4.9 oder 4.8 Installation werden die vordefinierten Bildgrößen nicht im Backend beim Einfügen eines Bildes im Select angezeigt. Die über config/config.yml erzeugten werden nach dem Leeren des Caches angezeigt.

**Comment by ausi** [comment]
Hat der Backend-Benutzer die entsprechenden Rechte um die Bildgrößen sehen zu können?

**Comment by ff1601com** [comment]
@ausi Ja, die sollte er besitzen, weil es ein Admin-Benutzer ist.
Die Bildgrößen werden nach der Erstellung im Backend auch in der Tabelle `tl_image_size` abgelegt, nur sind sie im Backend-Select nicht sichtbar.

**Comment by ausi** [comment]
Lässt sich das Problem auf <https://demo.contao.org/> reproduzieren?

**Comment by ff1601com** [comment]
Nein, dort funktioniert das Anlegen einwandfrei und es wird im Select-Menü angezeigt.

![image](https://user-images.githubusercontent.com/40162179/75439424-0b50e100-595a-11ea-9d0f-62e95f29a672.png)

**Comment by ausi** [comment]
Dann sollten wir versuchen rauszufinden warum sich deine Installation anders verhält. Sind Erweiterungen installiert?

**Comment by ff1601com** [comment]
Ja, sind es.

```
    "require": {
        "php": "^7.1",
        "contao/calendar-bundle": "^4.9",
        "contao/comments-bundle": "^4.9",
        "contao/conflicts": "@dev",
        "contao/faq-bundle": "^4.9",
        "contao/listing-bundle": "^4.9",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "^4.9",
        "contao/newsletter-bundle": "^4.9",
        "madeyourday/contao-rocksolid-slider": "^2.0",
        "madeyourday/contao-rocksolid-custom-elements": "^2.2",
        "agentur1601com/seosee": "^2.0",
        "craffft/css-style-selector-bundle": "^1.6"
    },
```

* SeoSee ist eine Eigenentwicklung.

##

Ich habe jedoch mit meinem Kollegen gesprochen, welcher das Contao installiert hatte und er meinte, dass die Bildgrößen auch bei einem frisch installierten System nicht funktioniert hatten.

Ich würde heute auch testweise nochmal ein leeres System aufsetzen und testen.

**Comment by ausi** [comment]
> Ich würde heute auch testweise nochmal ein leeres System aufsetzen und testen.

Das wäre am besten. Bitte die Schritte möglichst genau dokumentieren damit wir es nachstellen können.

**Comment by ff1601com** [comment]
Ich habe nun nochmal ein leeres Contao49 aufgesetzt und dort funktioniert es.

Schritte:

> * Composer installieren
> * Contao49 über console installiert
>   * php7-73LATEST-CLI composer.phar create-project contao/managed-edition . 4.9
> * Seite aufgerufen und Datenbankverbindung hergestellt
> * Theme angelegt
>   * Seitenlayout erstellt
>   * Test-Bildgröße erstellt
> * Über die Seitenstruktur einen neuen Seitenbaum angelegt
>   * Bild hochgeladen, Content-Element im Artikel ausgewählt und Bildgröße ausgewählt

**Comment by ausi** [comment]
Du könntest die Installation bei der der Fehler auftritt auf ein Testsystem duplizieren, und dort dann eine Erweiterung nach der anderen entfernen. Eventuell lässt sich dadurch herausstellen wovon der Fehler verursacht wird.

**Comment by ff1601com** [comment]
Das habe ich nun getan.
Ich habe nacheinander alle zusätzlich installierten Erweiterungen aus dem Testsystem geworfen, aber leider wurden noch immer keine Bildgrößen angezeigt.

Danach habe ich die Konfiguration meiner Composer.json der meiner blanken Contao49 Installation angepasst - auf welcher die Bildgrößen funktionieren - doch leider klappte es damit auch nicht.

Ich bin etwas ratlos. Hast Du noch einen Ansatz?

##

Edit: Mir kam das Ganze jetzt nun so seltsam vor, dass ich etwas getestet habe, was ich schon längst für getestet hielt: Ich habe ein neues Theme mit neuem Seitenlayout im System erstellt.

Und siehe da -> Es funktioniert nun.
Jetzt muss nur noch geklärt werden, was am alten Theme anders/fehlkonfiguriert wurde und somit dafür sorgt, dass die vordefinierten Bildgrößen nicht ausgegeben werden.

##

Edit2: Ich habe die Lösung in unserem System gefunden.

Der Theme-Titel besteht nur aus nummerischen Zeichen:
![image](https://user-images.githubusercontent.com/40162179/75473883-42dd7e80-5996-11ea-9272-c32775a35860.png)

Sobald ich diesen auf etwas ändere, was nicht nur aus nummerischen Zeichen besteht, funktioniert es und die vordefinierten Bildgrößen werden angezeigt.

@ausi Ich habe das eben mal in der von dir verlinkten Contao-Demo getestet und auch da werden die vordefinierten Bildgrößen nicht angezeigt, wenn der Theme-Titel ein rein nummerischer Wert ist.

Soll ich mein Test-Theme aus der Demo wieder löschen oder willst Du es dir nochmal ansehen?

**Comment by ausi** [comment]
Ich kann den Fehler nun reproduzieren, danke @ff1601com für die detaillierte Fehlersuche!

**Comment by ausi** [comment]
Mit #1439 sollte der Fehler behoben werden.

**Comment by ff1601com** [comment]
Super. Danke für den schnellen Fix und die rasche Rückmeldung.
