### ISSUE TITLE
Dev-Cache wird nicht automatisch erneuert

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1361]
Wenn  ``composer update`` aufgerufen wird, dann wird durch ``Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication`` auch automatisch der Prod-Cache erneuert.

Der Dev-Cache wird jedoch nicht automatisch erneuert, sodass es beispielsweise bei Aktivierung des Debug-Modus im Backend zu unerwarteten Fehlern kommen kann.

**Comment by andreheeke** [comment]
Wenn der Dev-Cache mit aufgebaut werden würde, dann würden Änderungen während des aktiven Debug-Modus im schlimmsten Fall nicht sichtbar sein (da schon gecacht). Der Modus soll ja den Symfony-Cache „umgehen“, um die Änderungen unverfälscht wiedergeben zu können.

**Comment by dmolineus** [comment]
Erneuern ist hier wohl der falsche Begriff, der Dev-Cache sollte mit geleert werden. Da Symfony die Eigenart hat auch im Dev-Modus viel zu cachen, kommt es immer wieder vor, dass der Dev-Cache out of date ist. 

Da Contao das Umschalten in den DEV-Modus per UI im Backend ermöglicht, gebe ich @Mynyx recht, dass der Cache auch automatisch geleert werden sollte.

**Comment by Mynyx** [comment]
> Wenn der Dev-Cache mit aufgebaut werden würde, dann würden Änderungen während des aktiven Debug-Modus im schlimmsten Fall nicht sichtbar sein (da schon gecacht). Der Modus soll ja den Symfony-Cache „umgehen“, um die Änderungen unverfälscht wiedergeben zu können.

Symfony hat separate Caches für die Prod- und Dev-Umgebung. In welchem Umfang der Cache jeweils genutzt wird, ist in der Prod- und Dev-Umgebung unterschiedlich.

Auch bei Nutzung der Dev-Umgebung wird der entsprechende Cache im Laufe der Zeit sowieso automatisch befüllt, sodass dieser nicht leer bleibt. Insofern kann ich noch nicht nachvollziehen, welche konkreten Nachteile ein vorheriges Warmup des Caches der Dev-Umgebung hätte.

Das Problem aufgrund dessen ich das Ticket eröffnet hatte, wird aber natürlich auch gelöst, wenn der Cache lediglich geleert wird.

**Comment by leofeyer** [comment]
See #1369
