### ISSUE TITLE
toggleVisibility in tl_page broken

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#1362]
**Affected version(s)**
4.9.0

**Description**
When trying to toggle the visibility in tl_page console throws an JavaScript error. The toggling itself still works but it's not done via AJAX anymore, instead it redirects the user.

![image](https://user-images.githubusercontent.com/226890/74838919-b216fb00-5324-11ea-8932-2ac8d0946fae.png)

**Comment by leofeyer** [comment]
Please clear the browser cache or try another browser.

**Comment by bennyborn** [comment]
Thats a fresh installation, all Caches cleared.

**Comment by andreheeke** [comment]
I cannot reproduce the error. In my installation the AJAX request works fine.

**Comment by michb** [comment]
I've just setup a completly new and fresh Contao 4.9 without any other extension.
I have the same problem as described by @bennyborn, if I click on pages without children.
If I click on a page with at least one child AJAX works fine.

**Comment by bytehead** [comment]
I can confirm this:
```
mootools.min.js,mooRainbow.min.js,chosen.min.js,simplemodal.min....-2d0c2b50.js:7 Uncaught TypeError: Cannot read property 'get' of null
    at Object.toggleVisibility (mootools.min.js,mooRainbow.min.js,chosen.min.js,simplemodal.min....-2d0c2b50.js:7)
    at HTMLAnchorElement.onclick (contao?do=page&ref=d2N1F4qD:365)
```

Edit: It happens only on pages without children.

**Comment by leofeyer** [comment]
I can reproduce it for pages without child pages.
