### ISSUE TITLE
Zwei-Faktor-Authentifizierung Gerätebezeichnung "Other" nicht übersetzt

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1363]
In der Tabelle "Vertrauenswürdige Geräte" wird in der Spalte "Gerät", die Bezeichnung "Other" angezeigt, wenn das Gerät nicht näher bestimmt werden konnte. Die Bezeichnung "Other" ist nicht übersetzt.

**Comment by leofeyer** [comment]
Ich weiß nicht, ob wir das übersetzen sollten. Der String kommt direkt aus der Library und dort gibt es auch noch andere Fallback-Strings wie z.B. "Generic Smartphone" oder "Generic Tablet". IMHO macht es keinen Sinn, die alle zu übersetzen.

@contao/developers WDYT?

**Comment by Toflar** [comment]
Das ist halt was die User erwarten. Ich würd's versuchen, auch wenn wir vielleicht nicht alle erwischen. Dann ergänzen wir die Liste eben nach und nach.

**Comment by aschempp** [comment]
wäre aus meiner Sicht aber eine Aufgabe der entsprechenden Bibliothek, Übersetzungs-Möglichkeiten zu bieten. Ev. nutzen sie den Translator und wir müssen "nur" die Dateien bereitstellen?

**Comment by leofeyer** [comment]
Leider nicht. https://github.com/ua-parser/uap-php

**Comment by leofeyer** [comment]
Wie am 12. März auf Mumble besprochen, wollen wir anstatt "Other" nur "-" anzeigen. Langfristig wäre es schön, wenn man die Geräte selbst benennen könnte.

**Comment by Mynyx** [comment]
> Der String kommt direkt aus der Library und dort gibt es auch noch andere Fallback-Strings wie z.B. "Generic Smartphone" oder "Generic Tablet".

Sollten die anderen Fallback-Strings dann nicht auch mit "-" ersetzt werden?
