### ISSUE TITLE
The Database->prepare() statement can not be used more than once

### ISSUE THREAD

**Issue by benfolds** [contao/contao#1365]
**Affected version(s)**
Tested in contao 4.8.8

**Description**
If you try to use da Database->prepare() statement more than once, you always get the result of the first query. 

**How to reproduce**
```
$result = $this->Database->prepare("SELECT * FROM tl_member LIMIT ?, 1");
for($i = 0; $i < 3; $i++) {
    var_dump($result->execute([$i])->fetchAllAssoc());
}
```

The result is three times the database row ID 1.

```          
for($i = 0; $i < 3; $i++) {
    $result = $this->Database->prepare("SELECT * FROM tl_member LIMIT ?, 1");
    var_dump($result->execute([$i])->fetchAllAssoc());
}
```
This gives the results 1,2,3

If you compare this with PDO, this is not the desired behaviour: https://www.php.net/manual/de/pdo.prepare.php

**Comment by Toflar** [comment]
Yes, that's different from PDO but we're not introducing or changing anything anymore in old legacy stuff. Don't use that class at all but use the Doctrine connection and you have your PDO behaviour :)
