### ISSUE TITLE
Crawlvorgang startet nach Neuladen der Seite erneut

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1371]
Wenn in der Systemwartung ein Crawlvorgang durchgeführt wurde und die Ergebnisseite dann neu geladen wird, dann wird der Crawlvorgang mit derselben Jobid neu gestartet anstatt direkt die vorhandenen Ergebnisse darzustellen.

**Comment by leofeyer** [comment]
@contao/developers Ist das nicht korrekt? Wenn ich die Seite neu lade, erwarte ich doch, dass der Vorgang erneut gestartet wird.

**Comment by Toflar** [comment]
Ich denke nicht. Der Vorgang sollte gestartet werden, wenn ich den Button klicke. Aber das ist halt so, weil sobald der Job fertig ist, wird die Queue gelöscht. Wenn wir das nicht tun, bleiben die Resultate für immer in der DB, ausser jemand leert die Queue manuell in der Systemwartung.
Und ein Cron kann das nicht machen, weil es ist nicht bekannt, von wann ein Job stammt. D.h. er könnte ggf. die Queue eines gerade aktiven Jobs killen.

**Comment by m-vo** [comment]
Und was ist dann der Use-Case die Seite überhaupt neuzuladen?

**Comment by leofeyer** [comment]
Bisher war es so, dass man die Seite "Suchindex neu aufbauen" durch F5 neu laden konnte und dadurch der Vorgang neu gestartet wurde. Der Crawler verhält sich aktuell genauso. Warum ist das jetzt auf einmal falsch?

**Comment by Toflar** [comment]
Für mich ist "ist so weil ist so" eh auch in Ordnung. Die Alternative wäre auf die Maintenance-Seite umzuleiten, weil die Resultate sind weg. Von daher würd ich es einfach so lassen.

**Comment by Mynyx** [comment]
> Ich denke nicht. Der Vorgang sollte gestartet werden, wenn ich den Button klicke. Aber das ist halt so, weil sobald der Job fertig ist, wird die Queue gelöscht. Wenn wir das nicht tun, bleiben die Resultate für immer in der DB, ausser jemand leert die Queue manuell in der Systemwartung.

So wie die Log-Dateien gespeichert werden, könnte doch auch eine Datei mit dem zusammengefassten Ergebnis im JSON-Format gespeichert werden?

Einen neuen Crawl-Vorgang mit derselben Jobid zu starten, sieht nicht richtig aus.

**Comment by Toflar** [comment]
Ja, könnte man. Aber es ist echt so unterirdisch unwichtig....
Lassen wir das Ticket mal offen, vielleicht ist mir irgendwann enorm langweilig.
