### ISSUE TITLE
Übersetzung MSC.twoFactorExplain

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1380]
In der Übersetzung ``MSC.twoFactorExplain`` sollte ``verification code``, wie dies in allen anderen Übersetzungen der Fall ist, auch mit ``Bestätigungscode`` statt ``Verifizierungscode`` übersetzt werden.

https://github.com/contao/contao/blob/bf87609767e5623d9da8b98920683bef2d651997/core-bundle/src/Resources/contao/languages/de/default.xlf#L2548-L2551

**Comment by leofeyer** [comment]
Ich habe die deutsche Übersetzung angepasst.
