### ISSUE TITLE
Fortschrittsanzeige nach erfolgreichem Abschluss des Crawlvorgangs bei 99 %

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1381]
Nach erfolgreichem Abschluss des Crawlvorgangs zeigt die Fortschrittsanzeige nicht 100 % sondern nur 99 % an.

![image](https://user-images.githubusercontent.com/1632642/75096071-f102b600-559b-11ea-8c41-fe692fd3c2c7.png)

**Comment by leofeyer** [comment]
Kann ich bei mir nicht reproduzieren. @Toflar Könnte das ein Rundungsfehler im Skript sein?

**Comment by aschempp** [comment]
Könnte auch an den 18 übersprungenen liegen …

**Comment by Toflar** [comment]
Die sind nicht relevant, die Anzeige hat nichts mit den Resultaten zu tun, sie zeigt nur die Queue.
Ich habe mir entsprechende Stellen angesehen und kann mir nicht erklären, wie dieser Fall zu Stande kommen soll.

@Mynyx ist das bei dir reproduzierbar? Wenn ja, könntest du dir die Ajax-Requests ansehen und schauen, was die periodischen Updates zum Schluss für `pending` und `total` Werte enthalten?

**Comment by Mynyx** [comment]
Das sind die Responses der letzten vier XHR-Requests:

``{"pending":49,"total":738,"finished":false,"results":{"search-index":{"wasSuccessful":true,"summary":"389 URL(s) erfolgreich indexiert. 0 fehlgeschlagen.","warning":"18 URL(s) wurde(n) \u00fcbersprungen (wenn Sie eine URL vermissen, pr\u00fcfen Sie das Debug-Log).","info":{"stats":{"ok":389,"warning":18,"error":0}},"hasLog":true}},"hasDebugLog":true}``

``{"pending":29,"total":738,"finished":false,"results":{"search-index":{"wasSuccessful":true,"summary":"389 URL(s) erfolgreich indexiert. 0 fehlgeschlagen.","warning":"18 URL(s) wurde(n) \u00fcbersprungen (wenn Sie eine URL vermissen, pr\u00fcfen Sie das Debug-Log).","info":{"stats":{"ok":389,"warning":18,"error":0}},"hasLog":true}},"hasDebugLog":true}``

``{"pending":5,"total":738,"finished":false,"results":{"search-index":{"wasSuccessful":true,"summary":"390 URL(s) erfolgreich indexiert. 0 fehlgeschlagen.","warning":"18 URL(s) wurde(n) \u00fcbersprungen (wenn Sie eine URL vermissen, pr\u00fcfen Sie das Debug-Log).","info":{"stats":{"ok":390,"warning":18,"error":0}},"hasLog":true}},"hasDebugLog":true}``

``{"pending":0,"total":738,"finished":true,"results":{"search-index":{"wasSuccessful":true,"summary":"390 URL(s) erfolgreich indexiert. 0 fehlgeschlagen.","warning":"18 URL(s) wurde(n) \u00fcbersprungen (wenn Sie eine URL vermissen, pr\u00fcfen Sie das Debug-Log).","info":{"stats":{"ok":390,"warning":18,"error":0}},"hasLog":true}},"hasDebugLog":true}``

**Comment by Toflar** [comment]
Klassischer Floating Point Error.
Das JS macht folgendes (leicht abgeändert zur besseren Leserlichkeit):

```js
var done = response.total - response.pending;
var percentage = parseInt(100 / response.total * done, 10);
```

Und in JS ergibt halt `100 / 738 * 738` einfach `99.99999999999999`, weil ja zuerst dividiert wird.

Easy Fix:

```js
var percentage = parseInt(done / response.total * 100, 10);
```

Zudem sollten wir noch abfangen, ob `response.total` `0` ist, um division by zero Fehler abzufangen.

**Comment by leofeyer** [comment]
Also so?

```js
var done = response.total - response.pending,
	percentage = response.total > 0 ? parseInt(done / response.total * 100, 10) : 0,
	result;
```

Oder muss `percentage` 100 sein, wenn `response.total` 0 ist?

**Comment by Toflar** [comment]
Der Fall kann ja gar nicht vorkommen, eigentlich. Aber ich denk 100 wäre in diesem Fall korrekt, ja.
