### ISSUE TITLE
Missing Polish translation for core-bundle

### ISSUE THREAD

**Issue by qzminski** [contao/contao#1383]
**Affected version(s)**
4.9 LTS

**Description**
It seems that there is no Polish translation for `core-bundle` in the latest stable version. I assume it is due to some threshold level but as of now `core-bundle` has 92.93% strings translated. All the other Contao bundles are translated at least in 93% and they are in fact included, so it seems the threshold level is at around 93%. Is that correct? Is this threshold level mentioned somewhere?

Perhaps this threshold level could be lowered to `>=90%`? That would be a bit more fair I think rather than 93%. At the current state of 92.93% we have 8428 strings translated and 641 untranslated, which IMO is still worth to be included.

Another question – if we translate enough strings to get through the threshold of 93%, will the translation make its way to the next hotfix version?

**Comment by leofeyer** [comment]
Translations must be at least 95% complete to be included in the distribution.

**Comment by qzminski** [comment]
We have just completed the Polish translation for version 4.9. We would highly appreciate if it can make its way into the next hotfix release 🙏🏻

**Comment by leofeyer** [comment]
It will be.
