### ISSUE TITLE
URL-Prüfung beim Formular funktioniert nicht

### ISSUE THREAD

**Issue by Schmidty2** [contao/contao#1384]
**Affected version(s)**
4.4.47 und 4.9.0

**Description**
Wenn einem Formularfeld die Prüfung nach einer gültigen URL zugewisen wird, funktioniert die Prüfung im Frontend nicht (zum Test wurde die E-Mail-Prüfung aktiviert, diese funktioniert).
Zusatz-Info: Die HTML5-Prüfung in den Formulareinstellungen ist deaktiviert.

**How to reproduce**
Kann unter demo.contao.org nachvollzogen werden,
siehe Screensots von demo.contao.org

![Feld-Konfiguration](https://user-images.githubusercontent.com/2067428/75147111-e3187680-56fc-11ea-8655-65f46fb17548.jpg)
![Frontend-Ausgabe](https://user-images.githubusercontent.com/2067428/75147114-e57ad080-56fc-11ea-8608-0d1e320c19df.jpg)

**Comment by aschempp** [comment]
Eine URL-Prüfung in Contao bedeutet, dass nur valide URL-Zeichen enthalten sein dürfen. Es bedeutet nicht dass der Wert eine vollständige URL sein muss.

**Comment by leofeyer** [comment]
@contao/developers Das ist auch so ein unerwartetes Verhalten, das wir mal ändern sollten. 😄

**Comment by bennyborn** [comment]
Wäre dafür es "richtig" zu machen :D

**Comment by aschempp** [comment]
_Richtig_ wäre für mich einzelne Formularfeld-Typen für die einzelnen Eingabetype in HTML. Eigentlich ein `easy-pick` 😉

**Comment by bennyborn** [comment]
Problem wäre dann nur entweder BC break oder man hat es doppelt.

**Comment by leofeyer** [comment]
Wie am 12. März auf Mumble besprochen, wollen wir `'rgxp' => 'httpurl'` für absolute URLs hinzufügen, die mit `https?://` beginnen. Außerdem könnten wir `'rgxp' => 'custom', 'custom_rgxp' => '/…/'` hinzufügen, um eigene reguläre Ausdrücke zu erlauben.
