### ISSUE TITLE
Crawler Log "Found on URI" robots.txt

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1386]
Sowohl im Debug-Log als auch im Suchindex-Log wird bei diversen Seiten, die auch erfolgreich indexiert wurde ("Forwarded to the search indexer. Was indexed successfully."), in der Spalte "Found on URI" statt der tatsächlichen URI "http://[...]/robots.txt" angegeben.

**Comment by Mynyx** [comment]
Zusätzlich ist mir noch aufgefallen, dass in der Spalte "Found on level" nur die Werte 0, 2, 3 und 4 vorhanden sind. Der Wert 1 fehlt.

**Comment by Toflar** [comment]
Die URI wurde ja auch in der robots.txt gefunden. Das ist gewollt.
Und für das Level bräuchten wir mehr Details. Da müsste ja stehen auf welcher URI sie gefunden wurden.

**Comment by Mynyx** [comment]
> Die URI wurde ja auch in der robots.txt gefunden. Das ist gewollt.

Wie meinst du das? Die Spalte "Found on URI" habe ich so aufgefasst, dass dort die URI der Seite stehen soll, auf der ein Link zur jeweiligen Seite, die in der Spalte "URI" steht, gefunden wurde. Und der befindet sich natürlich nicht in der robots.txt!?!

**Comment by Toflar** [comment]
Doch klar, in einer Sitemap die in der robots.txt gelistet ist. Dort hat sie der Crawler zuerst entdeckt. Das ist die Quelle für den Crawler und ob sie danach noch mal irgendwo gefunden wird, ist irrelevant.
Wir könnten auch die Sitemap URL als Quelle angeben, aber grundsätzlich ist die robots.txt schon die eigentliche Quelle.

**Comment by Mynyx** [comment]
Die Sitemap wurde in der robots.txt gefunden, aber die Seite/URI in der Sitemap. Ich denke es wäre sinnvoll, das zu ändern.

Optimal wäre es, wenn dann zusätzlich noch ein Eintrag mit URI der Sitemap im Debug-Log erfasst wird, bei dem als "Found on URI" die robots.txt angegeben wird.

**Comment by Toflar** [comment]
Sollte dann in der nächsten `terminal42/escargot` Version (noch nicht published) entsprechend so sein. Du kannst den master Branch testen, wenn du möchtest. Ref: https://github.com/terminal42/escargot/commit/7e2bc9a56200e4ef51b9f0df4e33ea2478ccc3e7
