### ISSUE TITLE
Validierung Seitenstruktur Feld Domainname

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1387]
Wenn in der Seitenstruktur bei einer Seite des Typs "Startpunkt einer Webseite" im Feld Domainname eine vollständige URL eingefügt wird (http://example.com/), dann wird keine Fehlermeldung angezeigt. 

Stattdessen wird das Protokoll entfernt, jedoch der Slash am Ende verbleibt (example.com/).

Dadurch kommt es beim Aufruf der Webseite zu einem Fehler.

**Comment by leofeyer** [comment]
Welche Contao-Version betrifft das?

**Comment by Mynyx** [comment]
Festgestellt in 4.9.0.
