### ISSUE TITLE
Seiten mit abweichendem Canonical Tag nicht in den Suchindex aufnehmen

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1394]
Seiten, bei denen ein Canonical Tag vorhanden ist und auf eine andere URL verweist, sollten nicht in den Suchindex aufgenommen werden.

**Comment by fritzmg** [comment]
Das wäre nicht Rückwärtskompatibel.

**Comment by bennyborn** [comment]
> Das wäre nicht Rückwärtskompatibel.

@fritzmg Wurde sowas vor Escargot überhaupt ausgewertet?

**Comment by fritzmg** [comment]
Die Aufnahme in den Suchindex passiert ja weiterhin durch Contao.

**Comment by bennyborn** [comment]
Achso stimmt, der Crawler packt ja dann nur zusätzliche Links mit dazu... Ok, verstanden.

**Comment by aschempp** [comment]
Finde ich aber ein interessanter Gedanke. Wenn die Canonical-Seite auf derselben Root-Seite ist, sollten wir sie vielleicht nicht indexieren. Eine externe Seite können wir vermutlich nicht direkt verlinken, bzw. das müsste man wohl schon konfigurieren?

Allerdings müssen wir auch bedenken, dass Contao von haus-aus keine Canonicals unterstützt. Man kann sowas also auch nicht für eine Seite konfigurieren… 🤷‍♂
