### ISSUE TITLE
News sorting doesn't work

### ISSUE THREAD

**Issue by AgenceUpMotion** [contao/contao#1397]
**Affected version(s)**
4.9
**Description**
Order by in NewsList 
**How to reproduce**

When I make a news list, sorting doesn't work

**Comment by fritzmg** [comment]
Are you able to reproduce this in the Contao Online Demo?

**Comment by AgenceUpMotion** [comment]
yes but the online demo is down

**Comment by AgenceUpMotion** [comment]
Humm. no ! I will search, thx
