### ISSUE TITLE
Forms is not translated 

### ISSUE THREAD

**Issue by AgenceUpMotion** [contao/contao#1398]
In French, Forms is not translated in the menu on the left.

Translate to: Formulaire de contact

**Comment by fritzmg** [comment]
What exactly do you mean?

**Comment by AgenceUpMotion** [comment]
The word in the contao menu "Forms" has not been translated into French

**Comment by netzarbeiter** [comment]
![forms](https://user-images.githubusercontent.com/1942550/75267188-34586100-57f6-11ea-9f2e-62a442ee8c19.png)

**Comment by AgenceUpMotion** [comment]
Yes, it's not Forms but "Formulaire de Contact"

**Comment by fritzmg** [comment]
Why should it be "Formulaire de Contact"? Shouldn't it be "Formulaires"?

**Comment by xchs** [comment]
Translation are managed on transifex.com. You can join the French translation team and change the strings yourself: https://www.transifex.com/contao/dashboard/all_projects/fr/

**Comment by AgenceUpMotion** [comment]
Translation are managed on transifex.com. You can join the French translation team and change the strings yourself: https://www.transifex.com/contao/dashboard/all_projects/fr/

Can you Add me ?

**Comment by xchs** [comment]
> Can you Add me ?

I'm sorry, I cannot do that. Just make a request to join the French translation team.
