### ISSUE TITLE
Twig-Templates im Template-Editor bearbeiten

### ISSUE THREAD

**Issue by fiedsch** [contao/contao#1399]
**Description**

enstsprechend der Diskussion im Formum (https://community.contao.org/de/showthread.php?71102-Contao-4-Wartungsmodus/page2&p=520178&viewfull=1#post520178) und der Symfony-Dokumentation (https://symfony.com/doc/4.4/bundles/override.html#templates) sollte das service_unavailable.html.twig in einem Unterordner von templates/ liegen. 

Abgesehen davon, daß wir das noch dokumentieren müssen (mache noch ein Ticket oder PR bei contao/docs), frage ich mich, ob in Contao noch etwas fehlt:

Die Ordnerstruktur bundles/ContaoCoreBundle/Error wird im Backend angezeigt, aber da Contao unter "Templates" nur *.html5 Dateien listet und zum editieren anbietet ist das Ergebnis eher verwirrend. 

Meine Befürchtung: ein Backenduser sieht das Verzeichnis, meint es ist leer und löscht es (und damit das Template). Außerdem wäre es m.E. sinnvoll, auch diese Templates hier bearbeiten zu können.

**Comment by Nightwing0815** [comment]
Meine (laienhafte) Frage wäre: kann man das nicht so einfach gestalten, wie die 401 / 403 / 404 Errorpages in Contao? Sprich: Auswahl bei Seitentyp, und dort dann gestalten.
Oder steht dem technisch gesehen das Symfony Routing im Weg?

ToM

**Comment by andreheeke** [comment]
Stimme @fiedsch zu. Im Hinblick darauf, dass auch Twig-Templates aus technischer Sicht in Contao (Content-Elemente, Frontend-Module etc.) gerendert werden können, sollten wir die Dateiübersicht um die Dateiextension `*.twig` erweitern.

**Comment by fiedsch** [comment]
Für die Diskussion:

- In https://gist.github.com/fiedsch/584bfe7b69c23b3105a97d2667112086 habe ich meinen aktuellen (quick and **dirty**) Stand der `tl_templates.php`, die `*.twig` Templates im Backend anzeigt und sie damit bearbeitbar macht.
- Die dort ebenfalls eingebaute Änderung in `addNewTemplate()` lässt mich zwar ein eigenes Twig Template hinzufügen, allerdings ist das so eher sinnfrei, denn Symfony dürfte sich nicht dafür interessieren, daß in `templates/` neue `views` liegen.
- Daß hier nur bestimmte Twig-Templates bearbeitet werden können ist für BE-User sicher nicht nachvollziehbar, denn es ist eine technische Restriktion und kein "Designgrund".
- Für oben im Ticket beschriebene Problem ist der schlanke Weg dann wohl: anstelle "Twig Templates im BE bearbeitbar machen" (was mehr nach sich zieht als im ersten Moment angenommen) vielleicht doch nur "den Ordner `bundles/ContaoCoreBundle/Error` nicht anzeigen.

**Comment by fritzmg** [comment]
> * Für oben im Ticket beschriebene Problem ist der schlanke Weg dann wohl: anstelle "Twig Templates im BE bearbeitbar machen" (was mehr nach sich zieht als im ersten Moment angenommen) vielleicht doch nur "den Ordner `bundles/ContaoCoreBundle/Error` nicht anzeigen.

Bzw. den Ordner `templates/bundles/`generell.

**Comment by leofeyer** [comment]
Wie am 12. März auf Mumble besprochen, wollen wir alle Dateien anzeigen, die im Ordner `/templates` liegen und den Bearbeiten-Button jeweils deaktivieren (Bugfix in Contao 4.9).

Um Twig-Templates bearbeitbar zu machen, müssten wir nach dem Speichern das kompilierte Template aus dem Cache löschen (Feature in Contao 4.10). Dazu müssten wir vermutlich den gesamten Ordner leeren, in dem Twig die kompilierten Templates speichert, weil es keine Möglichkeit gibt, den Pfad zu einem einzelnen Template herauszufinden.

**Comment by leofeyer** [comment]
Teil 1 (Bugfix in Contao 4.9): #1591

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2051
