### ISSUE TITLE
Download element -> support opening file in the browser instead of downloading

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#14]
Hello,

title says it all. Would be possible with:

```
header('Content-type: application/pdf');
header('Content-Disposition: inline; filename="' . basename(\Input::get('file')) . '"');
header('Content-Transfer-Encoding: binary');
header('Content-Length: ' . filesize(TL_ROOT . '/' . $file));
header('Accept-Ranges: bytes');
@readfile(TL_ROOT . '/' . $file);
exit();
```

Should I build a pull request or do you think, we don't need that in the core?

Bye Defcon0

**Comment by fritzmg** [comment]
Why do you need this?

**Comment by Defcon0** [comment]
It's a customer wish ;-) He's arguing that this way his download folder won't get "polluted" because we're talking about a media library ("mediathek") with hundreds of "downloads".

**Comment by fritzmg** [comment]
Currently the download(s) content element produces the following header:
```
Content-Disposition: attachment; filename="…"
```
May it should be configurable whether it should be `attachment` or `inline`.

**Comment by Defcon0** [comment]
That would also be an option, you're right. Would be a very simple fix. If you like, I could do a PR.

**Comment by fritzmg** [comment]
PR never hurts ;)

**Comment by Defcon0** [comment]
OK, but would be good to know what the other devs think so that I don't do it for nothing ;-) I'm quite busy atm.

**Comment by Toflar** [comment]
Is it a protected file? If not just use the hyperlink element.

**Comment by Defcon0** [comment]
Yup, it‘s protected. This is why I used the download element (because it uses Controller::sendFileToBrowser())

**Comment by asaage** [comment]
The same can probably be achived with the use of a Browser-extension (didn't test it)
https://superuser.com/questions/692168/disable-content-disposition-attachment-and-force-inline-display

I am fine with ```Content-Disposition: attachment``` or optionaly ```Content-Disposition: inline```

I'd rather like to see links eliminated from the download(s)-element and use a solution based on post-forms (mainly to prevent hot-linking and indexing) but that's another topic (https://github.com/contao/core/issues/8375#issuecomment-256895407).

**Comment by Defcon0** [comment]
OK, I created the pull request for contao 4.4 branch. Hope it gets merged ;-)

**Comment by leofeyer** [comment]
See #20.
