### ISSUE TITLE
Can't DROP 'pid_email';

### ISSUE THREAD

**Issue by kroerig** [contao/contao#140]
**Affected version(s)**
4.6

**Description**  
While upgrading from 3.5 to 4.6 the database update fails because an index on an nonexisting column cannot be dropped.
`[2018-10-22 11:07:14] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'DROP INDEX pid_email ON tl_newsletter_recipients':  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'pid_email'; check that column/key exists" at /var/www/web0/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 126 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'DROP INDEX pid_email ON tl_newsletter_recipients':\n\nSQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'pid_email'; check that column/key exists at /var/www/web0/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:126, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'pid_email'; check that column/key exists at /var/www/web0/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:109, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'pid_email'; check that column/key exists at /var/www/web0/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:107)"} []
`

**How to reproduce** 
Upgrade from 3.5 to 4.6

**Comment by leofeyer** [comment]
This is most likely caused by #106. @Toflar /cc

**Comment by Toflar** [comment]
Can you check if #166 fixes the issue please?

**Comment by kroerig** [comment]
Howto?
I've created a fresh install of 3.5.x and prepared a 4.x install.
How do I get a version with the changes?

**Comment by fritzmg** [comment]
You could simply replace `vendor/contao/installation-bundle/src/Database/Installer.php` with the fixed one and run the Contao Install Tool again (on the Contao 3.5 database).

**Comment by kroerig** [comment]
@Toflar I replaced the file with the one from the repository.
New error:
`[2018-11-06 16:03:39] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'DROP INDEX PRIMARY ON tl_newsletter_recipients':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY ON tl_newsletter_recipients' at line 1" at /var/www/web0/html/test/c4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 99 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'DROP INDEX PRIMARY ON tl_newsletter_recipients':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY ON tl_newsletter_recipients' at line 1 at /var/www/web0/html/test/c4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:99, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY ON tl_newsletter_recipients' at line 1 at /var/www/web0/html/test/c4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:109, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY ON tl_newsletter_recipients' at line 1 at /var/www/web0/html/test/c4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:107)"} []
`

**Comment by leofeyer** [comment]
See #166.

**Comment by leofeyer** [comment]
Fixed in 3d9c5943f6cd933a0aad539d5ffddca7c55981af.

**Comment by kroerig** [comment]
Just for your information. With version 4.6.8 upgrading from 3.5 works fine without any database errors.
