### ISSUE TITLE
Crawler: Fehler 500 während Aktualisierung des Suchindex wird nicht angezeigt

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1400]
Wenn der Crawler mit der Funktion ``Den Suchindex aktualisieren`` gestartet wird und während des Crawlvorgangs beim Zugriff auf eine Seite ein Fehler 500 auftritt, wird keine Fehlermeldung angezeigt, sondern nur die Erfolgsmeldung ``x URL(s) erfolgreich indexiert. 0 fehlgeschlagen.`` ausgegeben.

**Comment by bennyborn** [comment]
Würde ich zu #1312 dazuzählen.

**Comment by Toflar** [comment]
I just tried using  http://httpstat.us/500 and I then get `[ERROR] Checked 0 link(s) successfully. 1 were broken.` - that looks correct to me?
Can you tell me how I can reproduce this?

**Comment by Mynyx** [comment]
> Wenn der Crawler mit der Funktion `Den Suchindex aktualisieren` gestartet wird

I think you have used the broken link checker, too.

**Comment by Toflar** [comment]
Aaah, sorry, I misunderstood the issue here. :)
