### ISSUE TITLE
Crawler folgt Weiterleitungen unmittelbar

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1401]
Der Crawler folgt Weiterleitungen (z. B. 301) unmittelbar, statt die Zielseite der Queue hinzuzufügen. Dadurch wird die Zielseite erneut ausgewertet, auch wenn diese bereits gecrawlt wurde.

**Comment by leofeyer** [comment]
Der Crawler ist ein Drittanbieter-Paket. Bitte melde Probleme hier: https://github.com/terminal42/escargot/issues

**Comment by Mynyx** [comment]
Siehe https://github.com/terminal42/escargot/issues/12
