### ISSUE TITLE
Crawler: Unvollständiger Debug-Log bei alleiniger Ausführung des BrokenLinkCheckerSubscribers

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1404]
Wenn der Crawler nur mit der Funktion "Nach defekten Links suchen" ausgeführt wird, enthält der Debug-Log keine Informationen zu den gecrawlten Seiten:

````
Source,URI,"Found on URI","Found on level",Tags,Message
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 20 request(s)."
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 20 request(s)."
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 20 request(s)."
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 20 request(s)."
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 20 request(s)."
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 20 request(s)."
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 20 request(s)."
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 20 request(s)."
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 20 request(s)."
"Terminal42\Escargot\Escargot",---,---,---,---,"Finished crawling! Sent 4 request(s)."
````

**Comment by leofeyer** [comment]
Der Crawler ist ein Drittanbieter-Paket. Bitte melde Probleme hier: https://github.com/terminal42/escargot/issues

**Comment by Mynyx** [comment]
Der ``BrokenLinkCheckerSubscriber`` ist Bestandteil des ``core-bundle``?

https://github.com/contao/contao/blob/master/core-bundle/src/Crawl/Escargot/Subscriber/BrokenLinkCheckerSubscriber.php

**Comment by Toflar** [comment]
Kann ich nicht reproduzieren.

**Comment by Mynyx** [comment]
Hast du tatsächlich **nur** die Funktion "Nach defekten Links suchen" ausgewählt?

**Comment by Toflar** [comment]
Ja. Aber natürlich mit allen aktuellen 4.9er Änderungen. Also ggf. durch meine anderen Fixes bereits behoben.

**Comment by Mynyx** [comment]
Auch mit 4.9.2 ist der Debug-Log unverändert.

Das Issue bezieht sich darauf, dass der Debug-Log keine Informationen zu den gecrawlten Seiten enthält, es geht nicht um die dabei festgestellten Fehler. Liegt da vielleicht ein Missverständnis vor?

**Comment by Toflar** [comment]
Ach so, du meinst jede einzelne URL die angefragt wird?
Das wird bisher nie geloggt und wäre ja auch unabhängig des Subscribers.
