### ISSUE TITLE
Endless 404 page loop due to orphan pages

### ISSUE THREAD

**Issue by qzminski** [contao/contao#1408]
**Affected version(s)**
4.8.8, probably 4.9 as well

**Description**
The `contao.routing.page_404_router` service introduced in 16355846ae8029800aaacc5382cb1876fb4e811c can cause an infinite 404 page loop when rendering any frontend page in `prod` environment. This happens only if there are some orphan `tl_page` records (i.e. subpages without a page root)  in the database:

```sql
SELECT * FROM tl_page WHERE pid > 0 AND pid NOT IN (SELECT id FROM tl_page)
```

The problem is that Contao generates routes for these pages (https://github.com/contao/contao/blob/4.8/core-bundle/src/Routing/RouteProvider.php#L249) and if they do not have an associated website root, they will simply have no `_locale` requirement that is one of the requirements in `Route` class. This also causes the `vendor/bin/contao-console debug:router` command to throw an `\InvalidArgumentException: Routing requirement for "_locale" must be a string.`.

It is highly unlikely that such records will appear in the database but is certainly possible (not sure how to reproduce though). The `DC_Table::reviseTable()` does not check against such records and perhaps it should.

**How to reproduce**
Have orphan pages non-related to any website root.

**Proposals**
1. Make `DC_Table::reviseTable()` wipe out the orphans described above.
2. Ensure the `_locale` route requirement is present before adding a page route to collection.

/cc @Toflar

**Comment by leofeyer** [comment]
See #1411
