### ISSUE TITLE
No XHR Request by toggle visibility on Pages without subpages

### ISSUE THREAD

**Issue by trilobit-gmbh** [contao/contao#1414]
**Affected version(s)** 4.9

**Description**

**How to reproduce**
Demo > Pagetree > toggle visibility page "Content Elements": OK, XHR
Demo > Pagetree > toggle visibility page "Text elements": no XHR; default link action; backend reloads

**Comment by Funbug** [comment]
I can confirm this.

**Comment by leofeyer** [comment]
See #1362

**Comment by trilobit-gmbh** [comment]
Thanks ;-)
