### ISSUE TITLE
contao.web_dir not used in contao:install-web-dir

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#142]
**Affected version(s)**
 - 4.4
 - 4.5
 - 4.6
 - master

**Description**

Since 8f4c7f3ecab905d4f04dee7fbaddb27683eedb73 Contao used an `contao.web_dir` to indicate where to place the web folder. However the `contao:install-web-dir` command does ignore it.

https://github.com/contao/contao/blob/efbc2e760f9d685fc69ed7812c2ea35555389114/manager-bundle/src/Command/InstallWebDirCommand.php#L123

I expect that the command would recognize the web dir path.

Symfony 4 uses a different approach to set the public path, so it does not depend on the container configuration: https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-public-directory

**How to reproduce**  

Configure contao.web_dir to a custom folder and run `contao:install-web-dir`.

**Comment by leofeyer** [comment]
Fixed in 3e8e76bf13599111c09c727bf5a254c812ba7625.
