### ISSUE TITLE
Get back the "old" black background :-)

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1429]
Hello,

at first I'd like to thank you all for the new Contao 4.9. I just installed it the first time and can't wait to see the new crawler :-)

Only one thing bothers me. I know, it's kind of subjective and only a minor thing. Nevertheless I'm interested in your opinion.

I got used to the Contao 4.4 backend theme and very much liked the black gradient background. After opening the new Contao 4.9 I was kind of irritated because I thought this gray background would be a css styling issue ;-) But in the online demo on contao.org it's just the same, so I guess it's not a bug but a feature :-)

Is there an easy way to get back the black background? Or would one have to write a bundle for that? Is there a chance for some select field for custom theming?

Thanks in advance!

Bye Defcon0

**Comment by fritzmg** [comment]
I also like the black/blue gradient background more 😁

**Comment by Defcon0** [comment]
Just reminded myself that there's a select for the theme in the backend user's preferences. But this would imply that I'd have to copy the "flexible" folder completely which wouldn't be update-safe anymore then.

My current guess is that I'll have to write a tiny bundle just having

```
background: #132330 radial-gradient(#234058,#0f1c26);
```

inside as a css file included in the global CSS array ;-)

**Comment by asaage** [comment]
You wouldn't need a bundle or a copy of the theme for that,
just create ```templates/be_main.html5```
and make your adjustments there.

```php
<?php $this->extend('be_main'); ?>

<?php $this->block('head'); ?>
  <?php $this->parent(); ?>
  <style>
      /* your styles here */
  </style>
<?php $this->endblock(); ?>
```

**Comment by Defcon0** [comment]
OK, thanks!
