### ISSUE TITLE
Clicking Debug in a fresh Contao 4.9.1 installation leads to a 404

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1430]
**Affected version(s)**
4.9.1

**Description**
Clicking "Debug" in the main menu bar leads to the url being loaded without app.php which leads to a 404:

`http://test.local/app.php/contao?do=page&ref=buwhibOA` -> `http://test.local/contao?do=page&ref=buwhibOA`

**How to reproduce**
Install Contao 4.9.1 by composer
Hit Debug

**Comment by aschempp** [comment]
Why do you have `app.php` in the URL at all? Does your server not support URL rewriting?

**Comment by Defcon0** [comment]
I just installed it locally on my ubuntu. I‘ll check that, thanks for the hint

**Comment by Defcon0** [comment]
OK, it works. My new Mint installation didn't have mod_rewrite enabled.

**Comment by fritzmg** [comment]
Nevertheless, shouldn't it always work without it too? What if you had a custom entry point for the back end for whatever reason?
