### ISSUE TITLE
Formulareditor: Einrückung der Fieldsetbereiche

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1431]
Es wäre eine Hilfe im Formulareditor, wenn alle Elemente zwischen Fieldset-Start und -Ende eingerückt wären, so dass die "Pärchen" leichter auszumachen sind.

**Comment by fritzmg** [comment]
Das ist doch bereits der Fall:

![Screenshot_2020-02-28 Forms › Test › Fields c49 local](https://user-images.githubusercontent.com/4970961/75538298-4a416e00-5a10-11ea-8745-90c6caa4f762.png)

**Comment by zonky2** [comment]
ist das in 4.9 rein gekommen? in 4.4 sehe ich das nicht..

**Comment by fritzmg** [comment]
Vor 4.9 (ich weiß nicht welche Version).
