### ISSUE TITLE
Add Extra feature to DCA search/filter.

### ISSUE THREAD

**Issue by hoss-ps** [contao/contao#1432]
**Description**
Currently DCA search (protected function searchMenu(){} ) allow us to search in Database based on REGEXP.
is it possible to add a feature for DCA search to search value in DCA array in case field is not exist in DB aswell ? many DCA have call back functions and do not use database fields directly or may even use extra table  (mapping table beside DCA table itself).
**Example**
1-I use input callback in a field (DCA) that has no DB field and need to search it.
2-For unix timestamp fields , i created a formatted input callback field and wanna search based on return.
3- I fetch a mixed data from other table and demonstrate it as a field in DCA Panel and need to search it.

By the way, i know we have an option to assign it into search session or even replace data and use it, but will be fine if DCA search itself find it in Array  if no field exist in DB. 

Thanks.

**Comment by aschempp** [comment]
you should probably use the `panel_callback` https://docs.contao.org/dev/reference/dca/callbacks/#list-sorting-panel-callback-subpanel for this. You can see some code examples in Isotope eCommerce: https://github.com/isotope/core/blob/master/system/modules/isotope/dca/tl_iso_product.php#L96
