### ISSUE TITLE
New elements only show up in lists after page reload

### ISSUE THREAD

**Issue by intradesign** [contao/contao#1433]
**Affected version(s)**
Contao 4.9

**Description**
When creating new elements, they are often not displayed in the list views immediately after creation, but only after the list page has been reloaded.

Also affected is the activation of the debug mode. The debug modus is activated, but the debug bar in the backend is only visible after a page reload. 

**I noticed this with the following elements:**
pages, articles, content elements, modules, image sizes, news... so it looks like all lists are affected somehow.

**How to reproduce**
Description only for content elements. Other elements behave accordingly.

**1) create new elements**
- Create a new content element.
- Enter content and define the settings.
- Save the content element (Save and Close).
- It will not appear in the list.
- Reload the page.
- The item appears.

**2) Copy/move and paste elements**
- Copy or move a single or multiple items from one article to another.
- The elements do not appear in the list. 
- Reload the page.
- The items appear.

Someone else has reported that the problem also occurs with the new "picker".

The above mentioned problems occur in two installations, a fresh Contao 4.9 installation on PHP 7.4 and an installation updated from Contao 4.8.7 to 4.9 on PHP 4.3.

**Comment by aschempp** [comment]
do I understand correctly that you move or create something in the picker and _expect_ the parent page to reload??

**Comment by intradesign** [comment]
No, the Picker Issue was the one I quoted from someone else. See the second post (by SilentBob) at my forum post from yesterday:
https://community.contao.org/de/showthread.php?77278-Elemente-im-Backend-erst-nach-page-reload-sichtbar&p=520491#post520491

**Comment by aschempp** [comment]
@contao/developers looks like the responses in the Contao back end are not private/uncacheable by default? Maybe related to our cache/response handling?

**Comment by leofeyer** [comment]
@Toflar /cc

**Comment by Toflar** [comment]
Why would this be related to the cache? There's no cache in the back end and even if there was, why would a reload change anything? @leofeyer can you confirm that it's reproducible?

**Comment by fritzmg** [comment]
As discussed on the forum, it was caused by a

```
ExpiresByType text/html "access plus 1 month"
```

directive.
