### ISSUE TITLE
BN und/oder PW für app_dev funktioniert nicht nach dessen Anlage via SSH

### ISSUE THREAD

**Issue by m-werk** [contao/contao#144]
**Betroffene Version**
Version 4.4.26

**Beschreibung**
Das erstellen der Zugangsdaten für app_dev.php über die Konsole funktioniert, aber der Zugang als solcher, wo man dann BN und PW eingibt funktioniert nicht. Es wird nicht angenommen.

**Wie zu reproduzieren**
Ich habe via SSH für app_dev.php folgendes bei mir eingegeben:
`/usr/bin/php72 vendor/bin/contao-console contao:install-web-dir --user=admin --password=abcd1234`

(wobei das PW hier nur zu Testzwecken dient.
Die Konsole schrib dann folgendes:

> Added/updated the web/app_dev.php file.
> Added /updated the web/app.php file. 

Wenn ich jetzt im Frontend www.domain.at/app_dev.php eingebe, kommt die Authentfizierung wo ich jetzt meinen Benutzername und mein Passwort eingeben kann. 

Leider kommt immmer wieder dieses Eingabeformular im Frontend. Es wird also mein BN und PW nicht angenommen.

Im Root-Verzeichnis von Contao liegt eine neue Datei mit .env die auch einen verschlüsselten Inhalt hat.

LG, Andi

**Comment by xchs** [comment]
Ich kann das Problem in meiner Contao 4.4.26 Testinstallation nicht reproduzieren. Dort funktioniert die Authentifizierung mit den oben angegebenen Zugangsdaten einwandfrei.

**Comment by m-werk** [comment]
Komisch, wie gesagt, es wird auch ein .env-Datei erstellt, aber es greift einfach nicht. Hab dies jetzt x-mal probiert. (zuvor immer die .env gelöscht).

Diese Domain liegt bei World4You. Vielleicht hat es mit einer anderen Einstellung zu tun? Auch mehrere Browser hab ich getestet. Ohne Erfolg

**Comment by m-werk** [comment]
So, nun hab ich ein paar Tests gemacht. 
Ich hab jetzt mal Contao auf die V. 4.5.14 upgedated. Dann über den CM die Einstellungen für den Cache-Modus aktiviert mit BN und PW. Zuvor hatte ich die alte .env-Datei gelöscht.

Siehe da, von da aus geht's nun.

Jetzt bin ich dann wieder zurück auf die Version 4.4.26 gegangen (via CM) und es funktioniert nicht. Ich hab die .env so gelassen. 

Dann bin ich jetzt wieder auf die Version 4.5.14 umgestiegen und es funktioniert dort weiterhin.

Bei mir dürfte es wirklich an der 4.4.16 liegen. Ab 4.5 und über CM funktioniert es.

**Comment by leofeyer** [comment]
Hast Du es mal mit einer frischen 4.4er-Installation versucht?

**Comment by daniel-nemeth** [comment]
Hallo zusammen!
@leofeyer Danke für Eure tolle Arbeit.

Ich verwende Contao 4.6 und habe das selbe Phänomen. Bei mir kommt die Abfrage der Zugangsdaten auch jedes mal wieder ohne einen Login.

Bei einer frischen Installation gehts, kopiere ich meine Vorlage jedoch auf einen neuen Host, passe die Datenbankdaten an, erneuere beide Caches funktioniert soweit alles einwandfrei, nur die app_dev.php lässt sich nicht mit den zuvor angelegten Zugangsdaten öffnen.

LIVE-Test: https://beta.feuerwehr-seite.at/app_dev.php
User: dev
Pass: devtest

Vielen Dank für Eure Hilfe!

**Comment by fritzmg** [comment]
@daniel-nemeth verwendest du evt. für die Live Umgebung einen bestehenden Passwortschutz über .htpasswd (etc.)?

**Comment by daniel-nemeth** [comment]
@fritzmg nein. Ich verwende die unveränderte .htaccess von Contao 4 im /web/ Ordner.

Gerne kann ich einen Zugang zum Contao Manager oder FTP zur Verfügung stellen.

**Comment by daniel-nemeth** [comment]
Ich habe nochmals einige Versuche gemacht. Das Problem tritt bei mir dann auf, wenn man eine 4.6 dupliziert, zB. bei Verwendung einer Vorlage.

Installiert man alles neu funktioniert der Debug-Mode-Login normal.

Installiert man 4.6 neu und spielt dann die Datenbank ein, funktioniert der Debug-Mode-Login ebenfalls normal.

**Comment by leofeyer** [comment]
Also wenn Du alles neu installierst, funktioniert es, richtig? Und was passiert, wenn Du die neue Installation, in der es funktioniert, duplizierst? Funktioniert es dann nicht mehr?

**Comment by contaolove** [comment]
Ja genau. Ich habe eine contao vorlage. Bei dieser funktioniert die app_dev einwandfrei. 

Dann dupliziere ich die vorlage und beim duplikat geht es dann nicht mehr.

**Comment by leofeyer** [comment]
Und beim Duplizieren wird auch die `.env`-Datei mit dupliziert? Und Du hast den Cache nach dem Duplizieren geleert?

**Comment by contaolove** [comment]
Ja, wurde gemacht. Ich versuche es aber nochmal neu.

**Comment by leofeyer** [comment]
Und?
