### ISSUE TITLE
Pretty Error Screens without contao.pretty_error_screens: true

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#1442]
**Affected version(s)**
4.9.1

**Description**
Despite not having configured `contao.pretty_error_screens: true` in my `config/config.yml`, I get the following screens in the front end:

![Screenshot_2020-02-29 Service unavailable](https://user-images.githubusercontent.com/4970961/75607159-0f146d00-5aec-11ea-9d22-089219598ea7.png)

![Screenshot_2020-02-29 An error occurred](https://user-images.githubusercontent.com/4970961/75607160-0fad0380-5aec-11ea-8153-1aea7e55fbbc.png)

Weirdly, [some users report](https://community.contao.org/de/showthread.php?77280-Anpassung-Wartungsmodus-4-9) that they do not get this and they only see the pretty error screens, if they specifically enable them in the `config.yml`, as it would normally be the case.

As a side note: `Lato` is used in those screens, but not actually integrated. I think this is an oversight, since we generally switched to a native font stack in the back end. I'll provide a PR for that.

**How to reproduce**

1. Enable maintenance mode in the back end.
2. Open the front end (without `APP_ENV=dev`) in a private browsing window.

**Comment by leofeyer** [comment]
The manager bundle enables this by default:

https://github.com/contao/contao/blob/4.9/manager-bundle/src/Resources/skeleton/config/config_prod.yml#L4-L6

**Comment by fritzmg** [comment]
Right, then we actually need a reproduction for the cases, where the users do _not_ see the pretty error screen in their Contao 4.9 setups.

**Comment by aschempp** [comment]
if you explicitly set `contao.pretty_error_screens: false` in your `config.yml`, the managed edition configuration should be overridden (and no pretty error screens should show up).

**Comment by fritzmg** [comment]
Closing this, as we don't have a reproduction for the problem, where a user does not see the pretty error screen by default.
