### ISSUE TITLE
Hook annotation in Contao 4.9 not working?

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1449]
**Affected version(s)**
Contao 4.9.1

**Description**
According to the [docs](https://docs.contao.org/dev/framework/hooks/#invokable-services) I registered a new hook listener by service annotation:

```
<?php

namespace Acme\SomeBundle\EventListener;

use Contao\CoreBundle\Routing\ScopeMatcher;
use Contao\CoreBundle\ServiceAnnotation\Hook;
use Symfony\Component\HttpFoundation\RequestStack;
use Terminal42\ServiceAnnotationBundle\ServiceAnnotationInterface;

/**
 * @Hook("initializeSystem")
 */
class InitializeSystemListener implements ServiceAnnotationInterface
{
    /**
     * @var ScopeMatcher
     */
    private $scopeMatcher;
    /**
     * @var RequestStack
     */
    private $requestStack;

    public function __construct(ScopeMatcher $scopeMatcher, RequestStack $requestStack)
    {
        $this->scopeMatcher = $scopeMatcher;
        $this->requestStack = $requestStack;
    }

    public function __invoke(): void
    {
        // some code
    }
}
```
I removed all caches, created autoload map (basically I ran composer install). But my hook isn't triggered and is not part of `$GLOBALS['TL_HOOKS']['initializeSystem']`.

I understood the [docs](https://docs.contao.org/dev/framework/hooks/#invokable-services) in the way that I **don't** need to register the class as a services tagged with `contao.hook`. Or is that wrong? So I didn't create an entry in my service.yml.

So is it a bug?

Thanks for clarification in advance!

Bye Defcon0

**Comment by fritzmg** [comment]
In Contao 4.9, services in the `App\` namespace are automatically registered, autowired and configured. In your own bundle, you still need to register your services yourself of course. The service annotation should work, if you enabled autoconfiguration for your services.

**Comment by Defcon0** [comment]
Ah, I see. Now it works. I defined it in a listener.yml and removed the hook service annotation as it wuld be redundant now. Thanks!

**Comment by fritzmg** [comment]
Just define the following in your `.yml`:

```yml
services:
  _defaults:
    autoconfigure: true

  Acme\SomeBundle\EventListener: ~
```

or

```yml
services:
  _defaults:
    autoconfigure: true

  my_event_listener:
    class: Acme\SomeBundle\EventListener
```

Now the annotation should work.

**Comment by m-vo** [comment]
Services of reusable bundles should not use auto configuration ([see best practices](https://symfony.com/doc/4.4/bundles/best_practices.html#services)).

**Comment by Defcon0** [comment]
Ah ok. In fact we're not using autoconfigure in our bundles, but we do use autowiring. As I can see, using autowiring is also discouraged for services in public bundles as you cannot tell what's in the service container.

I don't quite understand this position since we require certain bundles via composer.json and we inject new services by constructor injection with the concrete service name (fully qualified class name). So indeed we **can** tell which classes are injected, can't we?

@m-vo Do you understand, why it's discouraged to use autowiring in public bundles?

**Comment by fritzmg** [comment]
> Services of reusable bundles should not use auto configuration ([see best practices](https://symfony.com/doc/4.4/bundles/best_practices.html#services)).

That seems wrong. It should be perfectly fine to use autoconfiguration for public bundles.

**Comment by fritzmg** [comment]
@Defcon0 regarding autowiring in public bundles: @Toflar recently made a PR for that: https://github.com/symfony/symfony-docs/pull/13063

https://symfony.com/doc/4.4/service_container/autowiring#public-and-reusable-bundles

**Comment by m-vo** [comment]
> The reason is that bundles shouldn't rely on features such as service autowiring or autoconfiguration to not impose an overhead when compiling application services.

:man_shrugging:

**Comment by Defcon0** [comment]
Mhm, very sad. It's such a comfort feature and we shouldn't use it in bundle development? In my opinion the use case where someone would override the class in the service container with some incompatible class, is very articificial and why should a developer do that?

**Comment by aschempp** [comment]
I actually disagree with Symfony here as well. If your bundle is _implementing a library_ (e.g. the monolog bundle for monolog), then you should not use autowiring or autoconfiguration. For any other reason, it seems perfectly valid to me.

Just to write it down, you can also use annotations without autoconfiguration:

```
Acme\SomeBundle\EventListener:
    tags: ['terminal42_service_annotation']
```
