### ISSUE TITLE
Veranstaltung wird ausgeblendet wenn Endzeit 00:00 Uhr ist

### ISSUE THREAD

**Issue by Floxn** [contao/contao#1459]
**Affected version(s)**
4.8.7 & 4.9.0 (demo.contao.org)

**Description**
Eine Veranstaltung wird in der Liste nicht mehr angezeigt wenn die Endzeit 00:00 Uhr beinhaltet. Listenansicht ist mit "alle zukünftigen Events" eingestellt. Stellt man die Endzeit auf 23:59 Uhr erscheint die Veranstaltung wieder.

**How to reproduce**
In der Demo eine Veranstaltung auf das heute Datum stellen, Startseite auf eine noch kommende Uhrzeit stellen und die Endzeit auf 00:00 setzen. Im Frontend auf die [Veranstaltungsseite](https://demo.contao.org/en/events.html) gehen. -> Veranstaltung taucht nicht auf. Dann Endzeit und 23:59 Uhr setzen und Frontend neu laden. -> Veranstaltung erscheint wieder.

Vorschlag: 
Ggf. Endzeit von 00:00 Uhr nicht erlauben, da es ja schon der neue Tag ist?

**Comment by Physiklehrer** [comment]
Contao verhält sich hier doch korrekt entsprechend der üblichen Zeitrechnung. Heute 0:00 Uhr ist eben definiert als "heute früh um Mitternacht" und ist damit den ganzen Tag über schon verstrichen. Wenn das die Endzeit ist, taucht das Event folgerichtig bei "alle zukünftigen Events" nicht mehr auf.

Wer "morgen 0:00 Uhr" als Endzeit haben möchte, muss eben das Datum von morgen einstellen, nicht das von heute. Auch wenn die Verwechslungsgefahr besteht, würde ich 0:00 Uhr lieber nicht sperren, denn prinzipiell ist das ja eine gültige Eingabe.

--> Ticket schließen?

**Comment by m-vo** [comment]
Startzeit > Endzeit macht aber nie Sinn, gegen diesen Fall sollten wir validieren.

**Comment by Physiklehrer** [comment]
das ist richtig! Also: Ticket doch nicht schließen, sondern Validierung einbauen!

Edit: bzw. wiederherstellen, ich denke das war sicher schon mal drin

**Comment by fritzmg** [comment]
Related: https://github.com/contao/contao/pull/1134

**Comment by leofeyer** [comment]
This issue will be fixed as soon as #1134 has been merged.

**Comment by leofeyer** [comment]
See #812
