### ISSUE TITLE
Failed to symlink tcpdf config

### ISSUE THREAD

**Issue by bezin** [contao/contao#146]
**Affected version(s)**
dev-master

**Description**  
The ScriptHandler::initializeAppliaction fails to symlink tcpdf.php. It looks for it in vendor\contao\core-bundle, which is obviously not there. 

```ERROR   system/config/tcpdf.php   Failed to create symbolic link from "C:\dev\web\contao-core\vendor\contao\core-bundle\src\Resources\contao\config\tcpdf.php" to "C:\dev\web\contao-core\system\config\tcpdf.php"```

**How to reproduce**  
1. Run ```composer create-project --no-install contao/managed-edition dev-master contao-core```
2. Adjust composer.json according to readme
3. Run ```composer update```

**Comment by fritzmg** [comment]
The path `vendor\contao\core-bundle\src\Resources\contao\config\tcpdf.php` is correct: https://github.com/contao/contao/blob/4.6.6/core-bundle/src/Resources/contao/config/tcpdf.php

**Comment by bezin** [comment]
Sure, but not, if the monolithic repository is used?

**Comment by fritzmg** [comment]
How do you install the mono repository via composer?

**Comment by bezin** [comment]
As is [stated in the readme](https://github.com/contao/contao#development). 
```
// composer.json
"require": {
    "php": "^7.1",
    "contao/contao": "dev-master"
}
```

**Comment by leofeyer** [comment]
I'm closing this in favor of #149.
