### ISSUE TITLE
Übersetzung tl_calendar.jumpTo.1, tl_calendar_events.jumpTo.1 und tl_calendar_events.articleId.1

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1473]
Verbesserungsvorschläge für die Übersetzungen ``tl_calendar.jumpTo.1``, ``tl_calendar_events.jumpTo.1`` und ``tl_calendar_events.articleId.1``:

https://github.com/contao/contao/blob/bf87609767e5623d9da8b98920683bef2d651997/calendar-bundle/src/Resources/contao/languages/de/tl_calendar.xlf#L16-L19

``Bitte wählen Sie die Eventleser-Seite aus, zu der Besucher weitergeleitet werden, wenn sie ein Event anklicken.``

https://github.com/contao/contao/blob/bf87609767e5623d9da8b98920683bef2d651997/calendar-bundle/src/Resources/contao/languages/de/tl_calendar_events.xlf#L212-L215

``Bitte wählen Sie die Seite aus, zu der Besucher weitergeleitet werden, wenn sie das Event anklicken.``

https://github.com/contao/contao/blob/bf87609767e5623d9da8b98920683bef2d651997/calendar-bundle/src/Resources/contao/languages/de/tl_calendar_events.xlf#L220-L223

``Bitte wählen Sie den Artikel aus, zu dem Besucher weitergeleitet werden, wenn sie das Event anklicken.``

**Comment by leofeyer** [comment]
Ich habe die deutsche Übersetzung entsprechend angepasst.
