### ISSUE TITLE
Umbruch zwischen Buttons beim Bearbeiten von Artikeleinstellungen

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1484]
**Affected version(s)**

Festgestellt in Contao 4.9.1

**Description**

Wenn beim Bearbeiten von Artikeleinstellungen die Fensterbreite verkleinert wird, tritt ein Bereich auf, in dem die Buttons nicht in eine Reihe passen und dennoch nicht gruppiert werden.

![image](https://user-images.githubusercontent.com/1632642/75807153-3174e780-5d85-11ea-89e6-1aa5732704ec.png)

**Comment by leofeyer** [comment]
Der Breakpoint für die Split-Buttons ist momentan 1236px, d.h. ist der Viewport schmaler, werden die Buttons zusammengefasst. Wir können jetzt entweder den Breakpoint erhöhen (z.B. auf 1280px) oder dafür sorgen, dass die Buttons schmaler werden (z.B. "Speichern & neu" anstatt "Speichern und neu").

@contao/developers Was wäre euch am liebsten?

**Comment by Mynyx** [comment]
Ergänzend könnte eine dynamische Lösung mittels JavaScript sinnvoll sein, abhängig vom tatsächlich benötigten Platz der Buttons?

Denn derzeit werden auch Buttons, die deutlich weniger Platz benötigen, gruppiert, wenn der Viewport schmaler als der statische Breakpoint ist.

**Comment by ausi** [comment]
> @contao/developers Was wäre euch am liebsten?

Breakpoint erhöhen.

**Comment by leofeyer** [comment]
@Mynyx Eine dynamische JavaScript-Lösung wäre ein neues Feature, das wir erstmal diskutieren müssten, und ist daher als Bugfix nicht geeignet. Solltest Du schon eine konkrete Idee dazu haben, freuen wir uns über einen PR für Contao 4.10.
