### ISSUE TITLE
Using /contao in page aliases

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#1488]
While working on the relaunch of our new website (we're a Contao Premium Partner) we've noticed that it's not possible to use `/contao` within a page alias. Creating a page with an url like `http://foo.bar/contao/agency.html` would result in a simple 401 error being thrown.

Since I'm lacking a deep enough understanding of Symfony I've created a non-upgrade-safe hack by editing the pattern of the `contao_install`-directive within `vendor/contao/manager-bundle/src/Resources/skeleton/config/security.yml` to also allow for .html url's.

But I was wondering: Is there actually any way to to this the right way and might that also be a feature for future versions?

**Comment by leofeyer** [comment]
No, there is no way, because `/contao` is reserved for the back end. Use `contao-agency.html` instead.

**Comment by fritzmg** [comment]
Could still be a bug though. There is no catch-all for `/contao…` in the router, so I do wonder why this throws `401`.

**Comment by leofeyer** [comment]
The configuration is in the `security.yml` file:

https://github.com/contao/contao/blob/b9c1002fb70588936db66415dbfa286fd11617f6/manager-bundle/src/Resources/skeleton/config/security.yml#L63

**Comment by fritzmg** [comment]
I see, makes sense. We could throw an exception though when creating such an alias (though I guess that is gonna be more complicated with the upcoming changes to the routing).

**Comment by bennyborn** [comment]
Okay, besides `/contao` being reserved for the backend... As far as I can tell there seems to be currently no way to extend the firewall rules if I were to build a Symfony bundle which should be used within a Contao installation. Regarding the fact that you guys try to move further and further into using Symfony this might become a problem in the future which should be discussed.

**Comment by bytehead** [comment]
You can use `contao/core-bundle` just as a regular Symfony bundle where you can adjust the firewall rules yourself: https://docs.contao.org/dev/getting-started/initial-setup/symfony-application/

**Comment by bytehead** [comment]
And bundles can never ship own firewall configs, as there is only one `security.yml` per application. But you can tell the users to add certain pieces to their existing `security.yml` to configure your bundle then.

**Comment by bennyborn** [comment]
Thanks for the explanation @bytehead, that was very helpful!

**Comment by Toflar** [comment]
If you're using the Contao ME, you can even add your firewall via the Manager Plugin. It's not super easy but I've explained why it's not and how you can do it in the docs: https://docs.contao.org/dev/framework/manager-plugin/#adding-a-custom-symfony-firewall

**Comment by bennyborn** [comment]
> If you're using the Contao ME, you can even add your firewall via the Manager Plugin [...]

Awesome. I guess thats exactly what I'd need! :)
