### ISSUE TITLE
expand 'overwrite metadata' copy contents or unselect specific contents to overwrite

### ISSUE THREAD

**Issue by JensB74** [contao/contao#1490]
Ich finde die Metadaten bei den Dateien sehr nützlich, doch manchmal muss man diese nun mal an anderer Stelle überschreiben, z.B. wenn man bei einem Bild auf einer Übersichtsseite noch einen Link zur Detailsseite anbietet und auf der Detailseite diesen Link nicht mehr benötigt, alle anderen Daten aber schon.
Nun könnte ich zwar die Metadaten überschreiben, muss dafür aber alle anderen Angaben wieder eintragen, weil diese nicht übernommen wurden.

Vorschläge:
1. wenn man "Metadaten überschreiben" anklickt könnten die Felder mit Daten aus dem Dateimanager gefüllt werden
oder
2. wenn man "Metadaten überschreiben" anklickt könnten die Felder mit Daten aus dem Dateimanager gefüllt werden, aber zusätzlich gibt es noch Checkboxen vor den Feldern, welche Felder man gerne überschreiben möchte, ein Häkchen bedeutet Übernahme aus dem Dateimanager (Feld bleibt ausgegraut und kann nicht editiert werden), kein Häkchen bedeutet "Feld leeren um dort selbst etwas einzutragen"

Dies ist mein erster Feature Request, ich hoffe er ist so ok?! ;)

**Comment by leofeyer** [comment]
Duplicate of #599
