### ISSUE TITLE
Dateiverwaltung > Bild Auswahl nicht möglich

### ISSUE THREAD

**Issue by kalterwind** [contao/contao#1492]
**Affected version(s)**

Contao 4.9.1

**Description**

1. Einloggen mit normalen Benutzer
(kein Admin (!), auch wenn sonst alle Checkboxen ausgefüllt sind bei der Rechtevergabe, nur Gruppenrechte).

2. zB Inhaltselement Text > "Ein Bild hinzufügen" > "Auswahl ändern".

3. PopUp bleibt weiß./contao?do=files&popup=1&picker=[...TOKEN...] => Status 500.
(Als Administrator geht der gleiche Link)

Weitere Infos:
[https://github.com/contao/contao/issues/1492#issuecomment-596468655](https://github.com/contao/contao/issues/1492#issuecomment-596468655)

**Comment by fritzmg** [comment]
Benutze de Debug-Modus und poste den Stack Trace.

**Comment by kalterwind** [comment]
Aufgefallen ist mir jetzt, dass es nur bei EINEM Benutzer ist, bei den anderen geht es. Obwohl alle NUR die gleichen Gruppenrechte verwenden!?

> Benutze de Debug-Modus und poste den Stack Trace.

Wie genau?
Debug Modus aktiviert, in Contao als Admin eingeloggt und auf einen normalen Benutzer (mit dem Problem) gewechselt. Picker geöffnet, erhalte kein Fehler, nur eine weiße Seite.
Schließe ich das PopUp und wechsel auf den Symfony Profiler sehe ich in den Logs keine Erros, Profile Search Status 500 ergibt auch nichts.

**Comment by kalterwind** [comment]
Der Fehler tritt wieder auf, jetzt viel auf, dass der Fehler auch nicht nur im PopUp sondern direkt über die Dateiverwaltung erscheint. Auch mit meinem Admin Account, immer wenn ich auf "Alle umschalten" klicke... wenn ich dann per FTP alle Ordner verschiebe, kann ich die Dateiverwaltung wieder aufrufen.
Danach kann ich alle Ordner zurück schieben und die Dateiverwaltung aufrufen. Kann auch diverse Ordner manuell öffnen... der Fehler erscheint und bleibt sobald ich wieder auf "alle umschalten" klicke. Leider kommt ein 500er Fehler, der mir keine weiteren Errors ausgibt.
ich kann übrigens in jeden einzelnen Ordner gehen und auf "alle umschalten" gehen, funktioniert. Der Fehler kommt nur, wenn die Seite nach "alle umschalten" aus der ersten Ebene lädt.
