### ISSUE TITLE
Aliasgenerierung bei Zahl unterschiedlich

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1497]
Bei der "herkömmlichen" Aliasgenerierung wird nur geprüft, ob das erste Zeichen eine Zahl ist - wenn ja, wird ein `id-` davor gesetzt...

https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L998-L1001

Bei Slug wird geprüft, ob der gesamte Alias eine Zahl ist
https://github.com/contao/contao/blob/master/core-bundle/src/Slug/Slug.php#L60-L62

letzteres macht m.E. mehr Sinn, da z. B. `123-moin` kein "numerischer Alias" - sprich ID - für eine Seite sein kann

**Comment by ausi** [comment]
Soweit ich weiß wird `standardize()` auch an Stellen für CSS-IDs oder Klassen verwendet. Diese dürfen nicht mit einer Zahl beginnen.

**Comment by zonky2** [comment]
hmm... - o.k. @leofeyer ist das so? dann schließe ich das wieder

**Comment by ausi** [comment]
Beispiel: 

https://github.com/contao/contao/blob/80355f3f7e2fa95759008f28d6ea3293ed210dea/core-bundle/src/Resources/contao/templates/block/block_section.html5#L2
