### ISSUE TITLE
4.4.27 Fehlende Parameter beim Erzeugen der Symlinks

### ISSUE THREAD

**Issue by eS-IT** [contao/contao#150]
**Affected version(s)**
Contao 4.4.27

**Description**  
Im [Automator.php#L398](https://github.com/contao/contao/blob/4.4.27/core-bundle/src/Resources/contao/library/Contao/Automator.php#L398) wird eine Instanz des `SymlinksCommand` erstellt. Der Konstruktor benötigt laut [SymlinksCommand.php#L80](https://github.com/contao/contao/blob/4.4.27/core-bundle/src/Command/SymlinksCommand.php#L80) Parameter, die hier nicht übergeben werden. Es wird deshalb folgende Fehlermeldung erzeugt:
```
Type error: Too few arguments to function Contao\CoreBundle\Command\SymlinksCommand::__construct(), 0 passed in /www/htdocs/***/***/***/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Automator.php on line 398 and exactly 4 expected
```

**How to reproduce**  
Contao 4.4.27 installieren und dann im BE unter Systemwartung die Symlinks neu erstellen lassen.

**Comment by leofeyer** [comment]
Fixed in 898d0f1ffb184a793079c7121e215449af8617ba.

**Comment by xchs** [comment]
https://github.com/contao/contao/commit/898d0f1ffb184a793079c7121e215449af8617ba is causing an issue in Contao 4.6 (see https://github.com/contao/contao/issues/153)
