### ISSUE TITLE
Crawler returns error 500.

### ISSUE THREAD

**Issue by spin80** [contao/contao#1504]
Hi,
When I try to run the crawler, I get an error:

```
Source,URI,"Found on URI","Found on level",Tags,Message
"Contao\CoreBundle\Crawl\Escargot\Subscriber\BrokenLinkCheckerSubscriber",https://domain.com/new-page.html,,0,,"Broken link! HTTP Status Code: 500."
```

New-page.html is an alias of the root node. When I type this address into my browser, it redirects me to the first page: start.html. So it seems to be okay.

Crawler doesn't see subpages. It stops at the root node. There are no errors in the var/logs directory.
Contao 4.9.1, php 7.2

Any ideas?

**Comment by Toflar** [comment]
Is that domain reachable for the crawler? Your browser !== your crawler. E.g. you might have proxy settings in your browser, the crawler does not know about.

**Comment by spin80** [comment]
I think so.
I checked the domain with https://robhammond.co/tools/seo-crawler
And everything seems to be okay. What else can I do to check it out?

**Comment by qzminski** [comment]
We are debugging it with hoster as cURL call returns an empty string for the mentioned URL + 500 header.

**Comment by leofeyer** [comment]
What is the status of this issue?

**Comment by qzminski** [comment]
I think it can be closed as the problem lies on the hosting provider side. For some reason, the requests coming out from the server to the server itself are processed with PHP 5.6 and not PHP 7. For the latter we'd have to use different ports than 80/443 and that's already a total absurd.
