### ISSUE TITLE
Schema diff / order of execution

### ISSUE THREAD

**Issue by m-vo** [contao/contao#1507]
**Affected version(s)**
all (but in this iteration only relevant since `contao:migrate` exists)

**Description**
When dealing with database constraints, the order of executing schema changes matters (e.g. you cannot drop a table before dropping a foreign key constraint on that table). Doctrines schema diff already handles this correctly but we reorder the commands afterwards in order to group them in different categories (`CREATE` / `DROP` / `ALTER_ADD`/ `ALTER_CHANGE`).

There was an [attempt to mitigate that problem ](https://github.com/contao/contao/pull/169) but it got reverted. When using the install tool to execute the commands, the order could at least be manually  selected in multiple steps to work around the issue. With the new command this cannot be resolved.

This is a real bummer, especially because the command plays nicely in a CI/CD environment (and the install tool can be disabled completely).

**Possible solutions**
* We could start a new attempt of fixing it by adding another method to the installer that returns the commands by hashes in order they were received from the schema diff. This would cover most/all scenarios (I'd be willing to do that if we decide to).
* We could at least try to reorder some things in `MigrateCommand->getCommandHashes()`. For example `ALTER_DROP` could be executed before `DROP` all the time in order to allow removing tables with a FK constraint on. This would probably miss some scenarios, e.g. where there are inner dependencies between the commands of one group.

(Btw.: Yes, I know that I can run `doctrine:migrations:diff` / `doctrine:migrations:execute ...` but I don't think we should need to execute both in order for migrations to work.)

**Comment by aschempp** [comment]
this should most likely be fixed by https://github.com/contao/contao/pull/1445, can you check that?

**Comment by ausi** [comment]
> fixing it by adding another method to the installer that returns the commands by hashes in order they were received from the schema diff.

This would be the right approach IMO. I should’ve done that when creating the migrate command 🙈

Could also be a parameter instead of a new method like `getCommands(bool $byGroup = true)` ?
