### ISSUE TITLE
Breadcrumb im Backend-Modul Nachrichten

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1510]
**Affected version(s)**

Festgestellt in Contao 4.9

**Description**

Im Backend-Modul Nachrichten wird im Breadcrumb "Artikel" statt "Beiträge" angezeigt.

![image](https://user-images.githubusercontent.com/1632642/76250610-ee63ba00-6245-11ea-8b43-ea43255c3e50.png)

**Comment by leofeyer** [comment]
Ich habe die deutsche Übersetzung angepasst.
