### ISSUE TITLE
Do not show FE preview button if no preview script was configured

### ISSUE THREAD

**Issue by Toflar** [contao/contao#1511]
**Affected version(s)**

Contao 4.9

**Description**

The `BackendPreviewListener` adds the preview link even if there was no `contao.preview_script` configured. I think we should not show it in that case as imho it always makes sense to have a special preview URL, even if you don't necessarily use any caching system.

Wdyt?
/cc @bytehead @sheeep because you're using the core-bundle standalone as well.

**Comment by leofeyer** [comment]
> The `BackendPreviewListener` adds the preview link even if there was no `contao.preview_script` configured. I think we should not show it in that case

Agreed.

**Comment by bytehead** [comment]
I'm fine with hiding it when no `contao.preview_script` is configured. We should definitely mention this in the docs for curious people.

**Comment by aschempp** [comment]
I think the (initial) idea was to always show it, but the link should just point to the "current" entry point. Not showing it is not necessarily correct, because if an entry point does not have a cache its totally fine to use it. And the button is very useful e.g. inside a news item to see it in the front end.

**Comment by Toflar** [comment]
But apparently that doesn't work. If you leave it empty, you'll end up in a 404 according to Slack. Can you maybe verify, @bytehead?

**Comment by bytehead** [comment]
If I remove the `contao.preview_script` parameter in my `config/packages/contao_core.yaml` I get an endless redirect after clicking the preview button.

**Comment by Toflar** [comment]
Either one has to be fixed, then 😄

**Comment by bytehead** [comment]
IMHO the button makes no sense to me if the preview script is not properly configured.

**Comment by aschempp** [comment]
Again, it makes sense to me. I'm sure we can fix the endless redirect easily.

**Comment by bytehead** [comment]
If there is no explicit preview entry point what should be shown to the user?

**Comment by aschempp** [comment]
> I think the (initial) idea was to always show it, but the link should just point to the "current" entry point. Not showing it is not necessarily correct, because if an entry point does not have a cache its totally fine to use it. And the button is very useful e.g. inside a news item to see it in the front end.

**Comment by leofeyer** [comment]
As discussed in Mumble on April, 9th, we want to keep the button and fix the endless redirect.
