### ISSUE TITLE
json+ld not valid

### ISSUE THREAD

**Issue by akroii** [contao/contao#1512]
**Affected version(s)**

only Contao > 4.9

**Description**

Contao delivers json+ld `@type":"RegularPage"` by default at the bottom of the source code. But the json is not valid.

Steps to reproduce:
1. [view-source:demo.contao.org](view-source:demo.contao.org)
2. copy: `
{"@context":"https:\/\/schema.contao.org\/","@type":"RegularPage","pageId":2,"noSearch":false,"protected":false,"groups":[],"fePreview":false}
`
3. validate markup at: [https://json-ld.org/playground/](https://json-ld.org/playground/)
4. check error message:
```
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
```

Notes:
After I switch the protocoll from https to http, i get the following message: `jsonld.SyntaxError: Invalid JSON-LD syntax; a term definition must not contain @set`

**Comment by Anke** [comment]
If I may add this here, as I think both problems might be associated, Google Search Console says:

> Problem mit Strukturierte Daten, für die kein Parsen möglich ist. Die folgenden Fehler wurden auf Ihrer Website gefunden: Falscher Werttyp "@context".

**Comment by Xirdion** [comment]
I think the error is just the additional **contao** for the context-entry. Should be `"@context":"https://schema.org" `

**Comment by Toflar** [comment]
No it should not because it's our own schema. Anyway, we know exactly what to do here, that's why it's marked defect and assigned to 4.9.

**Comment by leofeyer** [comment]
@aschempp, @Toflar and @ausi have fixed the schema on schema.contao.org now.

**Comment by mrwhy-orig** [comment]
I tried to validate a Contao 4.13 website and run into an error.

This @context string is unknown to the parser and we do not support remote JSON-LD context fetching. Please use a known @context value (e.g. "https://schema.org/") or define a local context.


 {
        "@context": "https:\/\/schema.contao.org",
        "@graph": [
            {
                "@type": "Page",
                "fePreview": false,
                "groups": [],
                "noSearch": false,
                "pageId": 2,
                "protected": false,
                "title": "Meine neue Webseite"
            }
        ]
    }

**Comment by fritzmg** [comment]
@mrwhy-orig I think you were using https://validator.schema.org/ ? [Google's Rich Results Validator](https://search.google.com/test/rich-results) will ignore any custom contexts.
