### ISSUE TITLE
Mehrere Fehlerseiten 404 unter einem Startpunkt

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1521]
**Affected version(s)**

Festgestellt in Contao 4.9

**Description**

Unter einem Startpunkt können mehrere Fehlerseiten 404 (Seitentyp "404 Seite nicht gefunden") angelegt werden. Es wird dann offenbar stets die erste Seite angezeigt.

So wie unter einem Startpunkt nicht mehrere Seiten mit demselben Alias angelegt werden können, sollte es jedoch auch nicht möglich sein, mehrere Fehlerseiten 404 unter einem Startpunkt anzulegen.

**Comment by michb** [comment]
Gleiches sollte dann auch für die 403 Seite gelten.

**Comment by Mynyx** [comment]
Shouldn't the stale bot ignore issues with ``bug`` label?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2397
