### ISSUE TITLE
Calling contao?do=calendar&table=tl_calendar_events&id=&act=delete leads to data loss

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1524]
Hello,

I just had a bug in the URL generation in the backend (the bug was mine, nothing to bother about for you). In the end, the ID parameter in the delete action link in the DC_Table list was empty (see issue title). This lead to all events being deleted :-(

Is this deleted or shouldn't we catch this case and throw an error? Of course, the script did exactly what I told it, but it's also a potential data loss.

What's your opinion on that?

Bye Defcon0

**Comment by fritzmg** [comment]
Please provide the necessary information as described in the issue template.

**Comment by fritzmg** [comment]
I cannot reproduce the problem in Contao `4.9.1`. When simply removing the ID from the edit URL, e.g.

``` 
contao?do=calendar&table=tl_calendar_events&id=&act=edit&rt=…&ref=…
```

I simply get the following error, as expected:

```
Cannot load record "tl_calendar_events.id=".
```

**Comment by Defcon0** [comment]
Interesting. I‘ll dig deeper and report. I tested in Contao 4.4.

**Comment by Defcon0** [comment]
Seems like an error on my side.
