### ISSUE TITLE
tl_files::protectFolder() should respect the save_callback()

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1535]
**Affected version(s)**

Contao 4.4

**Description**

When manipulating a folder's name with a `save_callback`, the `input_field_callback` in the field `tl_files::protected` only takes `\Input::post('name')` and not the result from the `save_callback`.

Is this a bug or intended?

Bye Defcon0

**Comment by leofeyer** [comment]
I think it is a bug. What exactly does your save callback do?

**Comment by Defcon0** [comment]
I'm currently developing a drafting system for contao. After a user tries to change a folder's name, it gets copied in the background and the user works on the this copied draft record. If the folder has the same name as the "old" folder, we have a problem (name is unique), so I add a fixed suffix to the folder's name in the file system (foldername_suffix123) that I remove in the load_callback and re-add in the save_callback so that the user can't change it.

**Comment by leofeyer** [comment]
Can you outline your load and save callbacks so I can reproduce this?

**Comment by Defcon0** [comment]
OK, no problem:

```
$dca['fields']['name']['save_callback'][] = function ($value, DataContainer $dc) {
    if (!$value) {
        return $value;
    }

    if (BackendUser::getInstance()->isAdmin && !$this->isChangeModeActive() && (!$dc->activeRecord || !$this->isDraftRecord($dc->activeRecord))) {
        return $value;
    }

    $fixedValue = $value.static::DRAFT_FILE_SUFFIX.BackendUser::getInstance()->id;

    // set to post for tl_files::protectFolder() callback (see #1535)
    Input::setPost('name', $fixedValue);

    return $fixedValue;
};

$dca['fields']['name']['load_callback'][] = function ($value, DataContainer $dc) {
    // don't manipulate the value while saving; else the link to the original file is lost
    if ('tl_files' === $this->request->getPost('FORM_SUBMIT')) {
        return $value;
    }

    if (BackendUser::getInstance()->isAdmin && !$this->isChangeModeActive() && (!$dc->activeRecord || !$this->isDraftRecord($dc->activeRecord))) {
        return $value;
    }

    return $this->deleteLastSuffix($value);
};
```

**Comment by leofeyer** [comment]
And how would you like the callback to work instead?

**Comment by Defcon0** [comment]
It should respect the `save_callback` and not directly use `Input::post(„name“)`.

**Comment by leofeyer** [comment]
So, after all, I think your workaround is the correct solution.

```php
    // set to post for tl_files::protectFolder() callback (see #1535)
    Input::setPost('name', $fixedValue);
```

Since the value is not actually saved, it would be wrong to tigger the save_callback IMHO. @contao/developers WDYT?

**Comment by ausi** [comment]
> Since the value is not actually saved, it would be wrong to tigger the save_callback IMHO.

As far as I understand the issue, it is not about triggering the save_callback but to respect changes from the save_callback on the `name` field in the `tl_files::protectFolder()` method.

We could check if `$dc->activeRecord->name` holds the correct value in this case and use it instead of `Input::post('name')`?
