### ISSUE TITLE
Cronjob wird nicht ausgeführt

### ISSUE THREAD

**Issue by henobi** [contao/contao#1539]
**Affected version(s)**

Contao 4.9

**Description**

Folgende Klasse wurde angelegt:
```php
<?php

namespace App\Cron;

use Contao\CoreBundle\ServiceAnnotation\CronJob;
use Terminal42\ServiceAnnotationBundle\ServiceAnnotationInterface;

class TestCron implements ServiceAnnotationInterface
{
    /**
     * @CronJob("minutely")
     */
    public function onMinutely(): void
    {
        echo "test\n";

        file_put_contents(
            '/Users/hendrik/contao49/demo.txt',
            'test'
        );
    }
}
```

Im Anschluss wurde der Cache geleert: `php vendor/bin/contao-console cache:clear`.

**Wenn ich nun den Cronjob über die Konsole starten möchte, wird mein `TestCron` nicht ausgeführt.**
    
```
php vendor/bin/contao-console contao:cron -vvv                                                                                 
21:27:08 DEBUG     [app] Executing cron job "Contao\CoreBundle\Cron\LegacyCron::onMinutely"
```

Es erfolgt keine Ausgabe und die Datei wird auch nicht angelegt.

Bei Rückfragen einfach Bescheid geben.
Vielen Dank schon mal im voraus!

Hendrik

**Comment by fritzmg** [comment]
Ist der Serivce registriert und getagged?

```
vendor/bin/contao-console debug:container TestCron
```

**Comment by henobi** [comment]
Danke für die schnelle Antwort.
Hier der Output:

```
$ vendor/bin/contao-console debug:container TestCron                                                                                                            

No services found that match "TestCron".  
```

**Comment by m-vo** [comment]
Dann ist deine Klasse nicht als Service registriert. Du musst sie in deiner `service.yml` explizit eintragen oder generell 'service autoregistration' aktivieren.

**Comment by henobi** [comment]
Hi, danke für die Antwort!

```yaml
services:
    App\Cron\TestCron:
        tags:
            - { name: contao.cron, cli: true, priority: 10 }
```

```
$ vendor/bin/contao-console debug:container TestCron                                                                              

Information for Service "App\Cron\TestCron"
===========================================

 ---------------- ------------------------------------ 
  Option           Value                               
 ---------------- ------------------------------------ 
  Service ID       App\Cron\TestCron                   
  Class            App\Cron\TestCron                   
  Tags             contao.cron (cli: 1, priority: 10)  
  Public           no                                  
  Synthetic        no                                  
  Lazy             no                                  
  Shared           yes                                 
  Abstract         no                                  
  Autowired        no                                  
  Autoconfigured   no                                  
 ---------------- ------------------------------------ 


 ! [NOTE] The "App\Cron\TestCron" service or alias has been removed or inlined when the container was compiled.         
```

So müsste das doch passen, oder?
Die Methode und das Interval (minutely) habe ich ja bereits über die Annotation angegeben.

Leider klappt es noch nicht...
Danke nochmal vorab für weitere Hinweise.

**Comment by fritzmg** [comment]
> Die Methode und das Interval (minutely) habe ich ja bereits über die Annotation angegeben.

Service Tagging machst du _entweder_ über die Service Definition in der `services.yml`, _oder_ über Annotations.

Grundsätzlich brauchst du in Contao 4.9 _keine_ eigene `services.yml` erzeugen. Das machst du nur dann, wenn du speziellere Definitionen machen willst. Versuche es also zuerst _ohne_.

**Comment by henobi** [comment]
Ok, aber dann hätte es ja so wie im Anfangspost gezeigt (https://github.com/contao/contao/issues/1539#issue-582580234) bereits funktionieren müssen, weil da hatte ich es ja nur über Annotations versucht. Wo lag dann da das Problem?

**Comment by m-vo** [comment]
Automatic loading of services inside `src` should work as of 4.9.-RC1 (#1165). Do you perhaps use a different directory?

**Comment by fritzmg** [comment]
Yes, check if you are using the correct directory and also check if the correct autoloading definition is present in your `composer.json`. The path of your class should be `src/Cron/TestCron.php`, relative to the Contao root directory.

**Comment by henobi** [comment]
My source code is stored in `src/App/Cron/TestCron.php`. So seems like that caused the problem. Thank's @m-vo & @fritzmg !
