### ISSUE TITLE
Keine Weiterleitung mit instert tag {{insert_form::ID|uncached}}

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#154]
**Affected version(s)**
4.4.28

**Description**  
Ich habe ein Kontaktformular ( mit Weiterleitung auf eine Bestätigungsseite ) auf jeder Seite. 

Wenn ich das Formular via {{insert_form::ID}} einbinde funktioniert die im Formular eingetragene Weiterleitungsseite. 

Wenn ich {{insert_form::ID|uncached}} verwende kommen die Mails zwar an (ohne angepaßte parameters.yml), die Weiterleitungsseite wird aber ignoriert. 

Ich hatte dies schon im Zusammenhang mit [#48](https://github.com/contao/contao/issues/48) angemerkt.

**Comment by leofeyer** [comment]
Das andere Issue ist mittlerweile als gelöst markiert. Besteht Dein Problem weiterhin?

**Comment by fkaminski** [comment]
Hinsichtlich der Fehlermeldung "Unknown insert tag flag |uncached" aus #48 - Ja,
In Bezug auf die nicht funktionierende Weiterleitung zusammen mit dem uncached Flag - Leider Nein

**Comment by leofeyer** [comment]
Wir haben das Problem soeben nochmal auf Mumble besprochen und eigentlich müssten die Änderungen aus #48 das Problem lösen. Wie kann man das Problem denn in der Onlinedemo reproduzieren?

**Comment by fkaminski** [comment]
> In Bezug auf die nicht funktionierende Weiterleitung zusammen mit dem uncached Flag - Leider Nein

In der Online Demo ein Formular mit Weiterleitungsseite anlegen und das Formular dann
via {{insert_form::ID|uncached}} auf einer o. mehreren Seiten einbinden ...

Evtl. kann ich das Morgen testen - sollte das denn mit z.B. der 4.4.32 dann funktionieren?

**Comment by fkaminski** [comment]
Habe es mit Contao 4.4.32 prpbiert:

{{insert_form::ID}} - Klappt
{{insert_form::ID|uncached}} - Klappt nicht

Erhalte dann im Browser: 
"Oops! An Error Occurred
The server returned a "500 Internal Server Error"."

In der log:
` request.INFO: Matched route "contao_index". {"route":"contao_index","route_parameters":{"_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\FrontendController::index
Action","_scope":"frontend","_route":"contao_index"},"request_uri":"http://192.168.99.100/","method":"POST"} []
[2018-12-21 08:36:52] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2018-12-21 08:36:52] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Error when rendering "http://192.168.99.100/_fragment?_hash=vo3FsvynXEp5Dr3rBXTz6Mx980WxTQo0jrp7oZRwctg%3D&_path=insertT
ag%3D%257B%257Binsert_form%253A%253A1%257Cuncached%257D%257D%26_format%3Dhtml%26_locale%3Dde%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&clientCache=0&pageId=2&request=" (Status code
is 303)." at /var/www/share/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/AbstractSurrogate.php line 99 {"exception":"[object] (RuntimeException(code: 0): Error when renderin
g \"http://192.168.99.100/_fragment?_hash=vo3FsvynXEp5Dr3rBXTz6Mx980WxTQo0jrp7oZRwctg%3D&_path=insertTag%3D%257B%257Binsert_form%253A%253A1%257Cuncached%257D%257D%26_format%3Dhtml%26_locale%3Dde%26_cont
roller%3Dcontao.controller.insert_tags%253ArenderAction&clientCache=0&pageId=2&request=\" (Status code is 303). at /var/www/share/project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCach
e/AbstractSurrogate.php:99)"} []
`

**Comment by leofeyer** [comment]
Ich habe es gerade nochmals in meiner Test-Umgebung nachgestellt und konnte das Problem nicht reproduzieren. Kannst Du nochmal ausführlich beschreiben, wie man das Problem in der [Online-Demo](https://demo.contao.org) reproduziert?

**Comment by fkaminski** [comment]
1. Eine normale Seite für die Formular Weiterleitung erstellen
2. Diese Seite als Weiterleitung im Formular "Contact" eintragen
3. Unter Themes ein Modul "Eigener HTML-Code" anlegen
4. Hier {{insert_form::5|uncached}} eintragen
5. Im Seitenlayout "1 column" in "Frontend-Module" dieses Modul für Spalte "Fußzeile" hinzufügen
6. Die Startseite aufrufen und das Formular absenden

Ohne das "|uncached" flag wird die Weiterleitungsseite korrekt aufgerufen ...

**Comment by leofeyer** [comment]
Hier ist die Fehlermeldung aus dem Log:

`[2019-01-22 11:18:58] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Error when rendering "https://demo.contao.org/_fragment?_hash=…&_path=insertTag%3D%257B%257Binsert_form%253A%253A5%257Cuncached%257D%257D%26_scope%3Dfrontend%26_format%3Dhtml%26_locale%3Den%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&clientCache=0&pageId=2&request=en%2F" (Status code is 303)." at /home/www/releases/31/vendor/symfony/http-kernel/HttpCache/AbstractSurrogate.php line 99 {"exception":"[object] (RuntimeException(code: 0): Error when rendering \"https://demo.contao.org/_fragment?_hash=…&_path=insertTag%3D%257B%257Binsert_form%253A%253A5%257Cuncached%257D%257D%26_scope%3Dfrontend%26_format%3Dhtml%26_locale%3Den%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&clientCache=0&pageId=2&request=en%2F\" (Status code is 303). at /home/www/releases/31/vendor/symfony/http-kernel/HttpCache/AbstractSurrogate.php:99)"} []`

@Toflar @aschempp Kann es am Status-Code 303 liegen oder daran, dass es ein POST-Request ist?

**Comment by aschempp** [comment]
Der normale Symfony Inline Renderer akzeptiert keinen Status Code ausserhalb von 2xx als Fragment. Unter anderem aus diesem Grund haben wir (ich glaube in der 4.6) den Forward-Renderer eingeführt. Allerdings sollte das Fragment auch keine Response zurück geben, sondern eine `RedirectException` werfen, denn diese sollte dank `ignore_errors = false` beim `ResponseExceptionListener` ankommen.

**Comment by ricowe** [comment]
Gibt es hierfür schon einen Lösungsansatz?
Steh gerade vor dem gleichen Problem und komme nicht weiter.

**Comment by leofeyer** [comment]
> Allerdings sollte das Fragment auch keine Response zurück geben, sondern eine `RedirectException` werfen

Das tut es eigentlich auch:

https://github.com/contao/contao/blob/b10dac251a053b5e38edc4c750e61f1469a86956/core-bundle/src/Resources/contao/forms/Form.php#L554-L559

Und beide Methoden rufen `Controller::redirect()` auf:

https://github.com/contao/contao/blob/b10dac251a053b5e38edc4c750e61f1469a86956/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1022-L1027

**Comment by aschempp** [comment]
könnte es sein dass die Exception schon im ExceptionListener für jeden Request abgearbeitet und in eine 302-Redirect-Response umgewandelt wird?
