### ISSUE TITLE
Database password issue when upgrading from Contao 4.4 to 4.9

### ISSUE THREAD

**Issue by toubibe** [contao/contao#1543]
**Affected version(s)**
Contao 4.9
When upgrading Contao 4.4 to 4.9, the database user passwords starting with special caracters are not taken correctly into the new version. Installtool is then showing up and asking for credentials, but the correct database user password, starting with one or more special caracters (like %%password1234) is not working. Installation is completely blocked.
Workaround: before doing the upgrade change the database user password and avoid special caracters at first place.

**Comment by m-vo** [comment]
You musst put the string in quotes or double the percent signs to properly escape them.

**Comment by contaoacademy** [comment]
https://github.com/contao/contao/pull/1037

**Comment by leofeyer** [comment]
How exactly is the password stored in your `parameters.yml`?

**Comment by toubibe** [comment]
Something like:  %%password1234
And within the file:
database_password: '%%password1234'

**Comment by toubibe** [comment]
> 
> 
> You musst put the string in quotes or double the percent signs to properly escape them.

The string is in (single) quotes already. But redoubleing the special caracters is in fact a working option.

**Comment by leofeyer** [comment]
See #1632.
