### ISSUE TITLE
Error 500 - Kein Zugriff auf Contao Manager und auf das Backend 

### ISSUE THREAD

**Issue by IslaBlanca** [contao/contao#1544]
Hallo liebe Gemeinde. 

Nachdem ich gestern mein Kontaktformular anpassen wollte und die Parameter.yml bearbeitet habe komme ich nicht mehr in meine Contao Installation. 

Ich bekomme einen Error 500 Fehler angezeigt...

Nun weiß ich keinen Rat wie ich das wieder gerade biegen soll. 

Vielleicht kennt sich jemand aus oder hatte das gleiche Problem.

Liebe Grüße 

![fatal-error-500](https://user-images.githubusercontent.com/61472019/77164750-363dd900-6ab1-11ea-9f08-3fe3ec44c323.png)

![fatal-error-500 - details](https://user-images.githubusercontent.com/61472019/77164709-22927280-6ab1-11ea-9a3d-9b8a0a50e07c.png)

**Comment by aschempp** [comment]
Deine Frage wäre im Contao Forum (https://community.contao.org) oder dem Slack Support Channel besser aufgehoben. Ich vermute du hast einen (Tipp-) Fehler in deiner Datei oder Sonderzeichen im Passwort oder ähnliches.
