### ISSUE TITLE
Pass module data (or at least module id) to nav item template rendering

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#155]
Hello,

what I want to achieve is the following:

I have some config parameters in a navigation module's model (`ModuleNavigation`). The nature of these config parameters is that I need them in the context of the navigation *item's* template, i.e. `nav_default.html5`.

Unfortunately there seems to be absolutely no way to accomplish that with the current implementation.

My proposal would be the following:

`ModuleNavigation.php`:

```
$this->Template->items = $this->renderNavigation($trail[$level], 1, $host, $lang, $this->row());
```

`Module.php`:

```
protected function renderNavigation($pid, $level=1, $host=null, $language=null, $moduleData=array())
{
    // ...
    $objTemplate->items = $items;
    $objTemplate->moduleData = $this->arrData;
```

Would that be possible to include? Or is there an other way to accomplish what I'm trying?

Thanks in advance.

Bye Defcon0

**Comment by leofeyer** [comment]
Can you try to pass `$this` instead of `$this->row()` please? You should then be able to access your configuration via `$this->my_parameter`.

**Comment by Defcon0** [comment]
@leofeyer Since no $this->arrData is passed to the objTemplate here:

```
// Controller::renderNavigation():

$objTemplate = new \FrontendTemplate($this->navigationTpl);

$objTemplate->pid = $pid;
$objTemplate->type = \get_class($this);
$objTemplate->cssID = $this->cssID; // see #4897
$objTemplate->level = 'level_' . $level++;
```

this can't work, or am I overlooking something?

**Comment by leofeyer** [comment]
True. We should pass `$this->arrData` there as well.

**Comment by bennyborn** [comment]
I second this. Not being able to determine in which exact module we're in (talking about e.g. `nav_default.html5`) can sometimes be a big problem. Had this problem many times and had to solve it by adding a specific CSS class to the module (not very prectical).

**Comment by leofeyer** [comment]
@Defcon0 Can you please test if the following changes fix your issue?

```diff
--- a/core-bundle/src/Resources/contao/modules/Module.php
+++ b/core-bundle/src/Resources/contao/modules/Module.php
@@ -281,6 +281,7 @@ abstract class Module extends Frontend
 		$objTemplate->type = \get_class($this);
 		$objTemplate->cssID = $this->cssID; // see #4897
 		$objTemplate->level = 'level_' . $level++;
+		$objTemplate->model = $this->objModel;
 
 		/** @var PageModel $objPage */
 		global $objPage;
```

```diff
--- a/core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
+++ b/core-bundle/src/Resources/contao/modules/ModuleCustomnav.php
@@ -109,6 +109,7 @@ class ModuleCustomnav extends Module
 		$objTemplate->type = \get_class($this);
 		$objTemplate->cssID = $this->cssID; // see #4897 and 6129
 		$objTemplate->level = 'level_1';
+		$objTemplate->model = $this->objModel;
 
 		/** @var PageModel[] $arrPages */
 		foreach ($arrPages as $objModel)
```

You should then be able to access `$this->model->my_parameter` in you navigation template.

**Comment by Defcon0** [comment]
Thanks, @leofeyer . This fixes it!

**Comment by leofeyer** [comment]
Great. I am not so happy with the naming though, because `$this->model` might as well be the model of the current item. What about `$this->module` or `$this->parent`?

@contao/developers /cc

**Comment by Defcon0** [comment]
You‘re right. I‘d definitely prefer $this->module.

**Comment by leofeyer** [comment]
See #1121
