### ISSUE TITLE
Bug in der Klasse TwoFactorFrontendListener

### ISSUE THREAD

**Issue by MalteGross** [contao/contao#1550]
**Affected version(s)**

4.9

**Description**

Ich habe für einen Kunden die 2-Faktor-Authentifizierung für das Frontend eingerichtet. Die initiale Einrichtung der Authentifizierung mit einem Mitglied mittels QR-Code funktioniert einwandfrei, das Mitglied ist erfolgreich eingeloggt und kann auch frei in Contao navigieren.

Loggt sich das Mitglied aus und meldet sich wieder mit Benutzername und Passwort an, dann bekomme ich auf jeder Seite(!) in Contao eine 401 Fehlermeldung. Auch auf der Loginseite. Auf dieser müsste jetzt allerdings eigentlich den Authentifizierungscode meines Authenticators eingeben werden können.

Ich konnte für mich den Fehler vorerst beheben. In der Klasse "TwoFactorFrontendListener" habe ich ab Zeile 113 folgende Code-Anpassung vorgenommen:

https://github.com/contao/contao/blob/6f803bebc2e1cd24c98883440c61ae8d03447204/core-bundle/src/EventListener/TwoFactorFrontendListener.php#L113

durch

```
if ($token instanceof TwoFactorToken) {
	return;
}
if ($token instanceof \Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken) {
    return;
}
```

ersetzt. Dann funktioniert es. Ich bin mir nur nicht 100% sicher, um meine Anpassung richtig sind, bin noch nicht zu 100% durch den Code durchgestiegen.

PS: Hatte auch ein Loop-Redirect Problem, weil ich von meiner 401 Seite auf die Startseite weitergeleitet hatte. Das führt zu Problem beim Login mit einem Mitglied, dass bereits den Authenticator eingerichtet hatte. Nachdem ich den Redirect entfernt hatte bekam ich im zumindestens die 401 Seite und nicht die Fehlermeldung vom Browser "err_to_many_redirects". Trotzdem ein wenig nervig.

**Comment by bytehead** [comment]
Hallo

>  Auf dieser müsste jetzt allerdings eigentlich den Authentifizierungscode meines Authenticators eingeben werden können.

Korrekt - hast du allenfalls das Login-Template (`mod_login.html5`) angepasst?

Ich habe es kurz bei der Online-Demo ausprobiert:

1. Seite für 2FA erstellt im Member-Bereich
2. Modul `Zwei-Faktor-Authentifizierung` unter Themes erstellt
3. Modul auf der Seite 2FA eingebunden.
4. Login mit `j.smith` im Frontend
5. Einrichten der Zwei-Faktor-Authentifizierung auf der neuen Seite
6. Logout
7. Erneutes Login mit Benutzername / Passwort
8. Zwei-Faktor-Authentifizierung wird abgefragt:

<img width="757" alt="Bildschirmfoto 2020-03-23 um 08 31 41" src="https://user-images.githubusercontent.com/754921/77292760-36bcb680-6ce1-11ea-8535-13bd05b350e9.png">

Scheint mir eher ein Konfigurationsproblem zu sein.

**Comment by MalteGross** [comment]
Ich habe das core-bundle mod_login.html5 Template verwendet. Mit den Code-Anpassungen, die ich vorgenommen habe funktioniert es zu mindestens. Habe alle Funktionalitäten durchgetestet. Hast du evtl. noch eine Idee woran es liegen könnte, dass es bei mir nicht funktioniert?

**Comment by bytehead** [comment]
Fehlerhafte Security config (`security.yaml`)?

Deine vorgeschlagene Anpassung ist sicher falsch, solange der 2FA-Code nicht eingeben wurde, solltest du immer wieder auf dem Login-Screen (wo sich auch das 2FA-Code-Feld befinden sollte) weitergeleitet werden.

**Comment by MalteGross** [comment]
Ich bin der Anleitung unter https://github.com/contao/contao/pull/363 gefolgt.
Die Config habe ich bei mir unter app/config/security.yaml abgespeichert und entsprechend angepasst. Cache habe ich zwischendurch immer wieder geleert. Wenn ich mich versuche ohne meine Anpassungen einzuloggen, dann bekomme ich immer nur ein 401 Fehler. Auch auf der Loginseite.

**Comment by aschempp** [comment]
@MalteGross hast du in deiner Seitenstruktur denn eine Seite vom Typ 401 angelegt und/oder in der Root-Seite die 2FA-Seite konfiguriert? Ohne diese weiss Contao ggf. nicht auf welcher Seite der 2FA Code eingegeben werden soll, daher die Fehlermeldung.

**Comment by leofeyer** [comment]
@MalteGross Hast Du das Problem lösen können? Falls ja, dann schließe bitte das Ticket.
