### ISSUE TITLE
robots.txt with insert-tags support?

### ISSUE THREAD

**Issue by V15** [contao/contao#1552]
I usually write the path to the sitemap in my robots.txt like this:
`sitemap:https://www.domain.de/share/sitemap.xml`

It would be useful if insert-tags are supported so I can use it for the domain:
`sitemap:{{env::url}}/share/sitemap.xml`

**Comment by fritzmg** [comment]
Contao 4.9 automatically adds the correct `sitemap.xml` to the dynamic `robots.txt`, you do not need to do that yourself.

**Comment by V15** [comment]
Awesome! Thanks.
