### ISSUE TITLE
Remove lock when running contao:user:password

### ISSUE THREAD

**Issue by m-vo** [contao/contao#1553]
When changing a password for a user on the CLI we imo should remove any locks still present on this user.

**Comment by aschempp** [comment]
Sounds legit. Is that for Contao 4.4 or 4.9? And wanna do a Pull Request? 🙃

**Comment by m-vo** [comment]
I'd say it's a feature for 4.10? I can provide a PR.

**Comment by aschempp** [comment]
Not sure, I would consider that a bugfix (as it should always have been the case) wdyt @contao/developers ?

**Comment by fritzmg** [comment]
I'd say bugfix.

**Comment by aschempp** [comment]
@m-vo would you be willing to provide a PR? 😊

**Comment by m-vo** [comment]
Sign me up! :wink:

**Comment by m-vo** [comment]
closing in favor of #1724
