### ISSUE TITLE
Contao 4.9.1 no able to run properly under a TLS proxy due X-Forwarded-Proto header is not checked

### ISSUE THREAD

**Issue by joseluisq** [contao/contao#1558]
### Affected version(s)

**Contao v4.9.1**

### Description

We are testing a fresh installation of latest Contao v4.9.1 LTS under a HTTP Proxy with TLS but it can't run properly because `HTTP_X_FORWARDED_PROTO` is not checked. Of course, the installation page only shows 404s requests.

**composer.json**
This is the default file generated with `composer create-project contao/managed-edition . 4.9` that we are using.

```json
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0-or-later",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": ">=7.2",
        "contao/calendar-bundle": "^4.9",
        "contao/comments-bundle": "^4.9",
        "contao/conflicts": "@dev",
        "contao/faq-bundle": "^4.9",
        "contao/listing-bundle": "^4.9",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "^4.9",
        "contao/newsletter-bundle": "^4.9"
    },
    "conflict": {
        "contao-components/installer": "<1.3"
    },
    "extra": {
        "contao-component-dir": "assets",
        "symfony": {
            "require": "^4.4"
        }
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

Why [this `HTTP_X_FORWARDED_PROTO`](https://github.com/contao/core/commit/40a05412254677f464a60b9103e14e9a1c7a615d) checking was not also considered in https://github.com/contao/contao/blob/4.9/core-bundle/src/Resources/contao/library/Contao/Environment.php ? 
I know that above commit was `v3.5` but are you checking for `HTTP_X_FORWARDED_PROTO` in the new version as well?
Or how can I get it work from settings for example? because I only found just outdated discussions and workarounds.

**Testing workaround:** The ugly workaround that I found (and tested) was overwrite the `web/index.php` file adding `HTTP_X_FORWARDED_PROTO` checking manually.

**Comment by Toflar** [comment]
Did you configure the `TRUSTED_PROXIES` and `TRUSTED_HOSTS` environment variables correctly? Contao doesn't trust proxies blindly. No application should.
Read more here: https://docs.contao.org/dev/reference/config/#environment-variables-for-the-contao-managed-edition

**Comment by joseluisq** [comment]
> Did you configure the `TRUSTED_PROXIES` and `TRUSTED_HOSTS` environment variables correctly?

Does work similar to https://symfony.com/doc/current/deployment/proxies.html#solution-settrustedproxies? Because it doesn't work. Or probably is not "right" configured. 

> Contao doesn't trust proxies blindly. No application should.

What do have to do `HTTP_X_FORWARDED_PROTO` with trusted IP proxies?

Question what is my proxy ip is not static?

**Comment by Toflar** [comment]
Yes, it works exactly the same because it uses the same code :) 

> What do have to do HTTP_X_FORWARDED_PROTO with trusted IP proxies?

Well, the `HTTP_X_FORWARDED_PROTO` is only taken into account, if your request is coming from a trusted proxy. Otherwise, everybody could just set that value in their request and fake an HTTPS request.

> Question what is my proxy ip is not static?

If it is not static, you cannot trust it. You may need to find another solution to find out how you can trust the sender.

**Comment by joseluisq** [comment]
> Well, the `HTTP_X_FORWARDED_PROTO` is only taken into account, if your request is coming from a trusted proxy. Otherwise, everybody could just set that value in their request and fake an HTTPS request.

What if my proxy is the only entry point TLS (445) and the Contao app runs in an isolated environment (localhost). Example a Docker container?

**Comment by joseluisq** [comment]
I got it to work using `TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR` as described on https://symfony.com/doc/current/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly

But there is a concern of mine. 
During the installation process, I was using by default an .env file located at root dir. But when I have combined them with system exported (set) env variables, the `TRUSTED_PROXIES` doesnt work. So I guess that system exported (set) env variables take precedence or I don't know. Is that documented somewhere?

**Comment by Toflar** [comment]
https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local

> Real environment variables always win over env vars created by any of the .env files.

**Comment by joseluisq** [comment]
I also never found https://docs.contao.org/dev/reference/config/#environment-variables-for-the-contao-managed-edition doc. Is that dev one? It also makes no reference to https://symfony.com/doc/current/deployment/proxies.html#but-what-if-the-ip-of-my-reverse-proxy-changes-constantly.

**Comment by Toflar** [comment]
You are very welcome to contribute to the docs 😄 I'm closing the issue as there seems to be all good here.

**Comment by fritzmg** [comment]
I have added a link in https://github.com/contao/docs/commit/2c88db14a3f9b01231d24df828fa868847f76713
