### ISSUE TITLE
Recorvery record

### ISSUE THREAD

**Issue by wisniewskim** [contao/contao#156]
**Affected version(s)**
2.11.11

**Description**  
Hi,
In the Back End Module -> Content -> Catalog I creata a catalog with 18 items.
In the "Edit multiple" option all 18 was checked and at all parent ID was change from 1-18.
In result almost all items disappear.

System log show details as:
"A new version of record "artykuly.id=13" has been created (parent records: tl_catalog_types.id=18)" 

**How to reproduce**  
Is there any way to reverse those change or the data is lost?

**Comment by ausi** [comment]
Please refer to the [forums](https://community.contao.org) for this kind of question.
