### ISSUE TITLE
Feature: ID for templates

### ISSUE THREAD

**Issue by jankout** [contao/contao#1563]
I think it would be nice to have IDs for templates as we already have it for files. 

1. So we could connect them/it with other content based on their/its ID (e.g. in inserttags). 
2. It would be also very helpful in case of **renaming of templates** - they can be stayed connected because of their/its ID. 

What do you think? 

Thank you very much for your respond and great work.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/issues/586
