### ISSUE TITLE
colorbox Accessibility

### ISSUE THREAD

**Issue by Floxn** [contao/contao#1576]
**Affected version(s)**

Contao 4.4 & Contao 4.9?

**Description**

Web Accessibility Checker haben die leeren Buttons der Colorbox angemeckert:
```
cboxPrevious
cboxNext
cboxSlideshow
```

Das wurde auch schon direkt bei der CBox [reported](https://github.com/jackmoore/colorbox/issues/765). Die [Lösung](https://github.com/jackmoore/colorbox/pull/832/files) gibt auch schon. Habe ich bei mir eingebunden und die Fehler sind verschwunden.

Da die Colorbox ja offensichtlich nicht mehr weiter entwickelt wird, bleibt der Fehler ja bestehen. Kann da Contao eine modifizierte Version einbinden? Oder was kann man da machen?

Gruß

**Comment by leofeyer** [comment]
The patch has been added in version 1.6.6 (see contao-components/colorbox@80c3b1b5adff4add0a7a54db93ad0bf15ae6bd9d).
