### ISSUE TITLE
Wrong german term for "Bildunterschrift" in element type "Video/Audio"

### ISSUE THREAD

**Issue by jochi44** [contao/contao#1577]
**Affected version(s)**
Contao 4.4 and Contao 4.9

**Description**
The german term "Bildunterschrift" is not correct for elements of type "video/audio" as it's not an image element.
suggestions:
"Text unterhalb des Video-/Audio-Elements"
"Hier können Sie einen Text eingeben, der unter dem Video-/Audio-Element angezeigt wird."

![image](https://user-images.githubusercontent.com/60215157/77765650-d7430b80-703e-11ea-883c-6d412dcb24b4.png)

**Comment by leofeyer** [comment]
Und dieses Feld wird Dir im Element "Video/Audio" angezeigt?

Denn laut DCA ist `caption` Teil der Palette `overwriteMeta` und die wiederum Teil der Paletten `addImage` und `useImage`. Letztere werden allerdings nur in den Inhaltselementen `text`, `accordionSingle` und `hyperlink` verwendet.

**Comment by fritzmg** [comment]
Das ist das Feld `playerCaption`, welches folgende Deutsche Übersetzung hat:

https://github.com/contao/contao/blob/9e111216a2f5fb3ffc0c1114540c285aa52dc7be/core-bundle/src/Resources/contao/languages/de/tl_content.xlf#L476-L483

**Comment by leofeyer** [comment]
Interessant. Die Übersetzung hat Transifex wohl automatisch aus dem Translation Memory übernommen.

**Comment by leofeyer** [comment]
Ich habe die deutsche Übersetzung angepasst.
