### ISSUE TITLE
Crawler search index rebuilds only 19 pages of 87

### ISSUE THREAD

**Issue by tonsinn** [contao/contao#1578]
Contao 4.9.1
After update of Contao 4.4.46 installation to 4.9.1 only part of all pages are indexed.
Site structure and page config was not changed after Contao update.

The crawl_search-index_log.csv has 60 "Forwarded to the search indexer. Was indexed".

Also the terminal command "php74 vendor/bin/contao-console contao:crawl"
does not find more pages.

**Comment by Toflar** [comment]
We cannot really do anything here without having more information. You will have to check yourself why they are not indexed. The log file should give you all the necessary information for this. Maybe a page is configured to `nofollow` and thus others are not found etc. 
You may also attach the log file here.

**Comment by Mynyx** [comment]
Do you have protected pages or do you use the ``nofollow`` option?

**Comment by tonsinn** [comment]
YES! After I changed all searched pages from "nofollow" to "follow" the crawler works.
Good to know. This is a small but interesting difference to Contao 4.4.
Thank you!

**Comment by Toflar** [comment]
Yeah, the crawler now also unveils possible misconfigurations. Now you know why Google probably did not index other URLs so far... 😎
