### ISSUE TITLE
Additional Line Breaks in tables

### ISSUE THREAD

**Issue by V15** [contao/contao#159]
**Affected version(s)**
4.x

**Description**  
Additional Line Breaks in tables if using `<p>` or `<li>` elements.

**How to reproduce** 
Add a new content element "table".
Insert `<p>` or `<li>` elements:

`<p>Text</p>`
`<p>Text</p>`
`<p>Text</p>`

`<ul>`
`<li>Text</li>`
`<li>Text</li>`
`<li>Text</li>`
`</ul>`

Looks good in the backend but HTML in Frontend adds `<br>` Tags after each line.

See also: [https://github.com/terminal42/contao-rte_table/issues/3](https://github.com/terminal42/contao-rte_table/issues/3)

**Comment by leofeyer** [comment]
Fixed in daf26f002d2dbc57b99a10f1d50ae32b69a3b2f5.

**Comment by V15** [comment]
Danke.
