### ISSUE TITLE
console contao:symlinks removes web/files/ directory permanently

### ISSUE THREAD

**Issue by joseluisq** [contao/contao#1603]
**Affected version(s)**

Contao v4.9.1

**Description**

During the testing of a Contao v4.9.1 fresh installation, we have created a `web/files/` **directory** with some content. But when we have executed `php -q bin/console contao:symlinks --env=prod` the `web/files` and their content was removed **without** advice [1].

[1] Details:

<img width="1057" alt="Screenshot 2020-03-31 at 15 40 28" src="https://user-images.githubusercontent.com/1700322/78035888-f1942680-7369-11ea-9107-b87730237157.png">
 
So the question is WHY `contao-console contao:symlinks` is responsible of content removal?
Because the tool is "supposed" to make symlinks but not content remove operations.

```sh
~> php -q bin/console --version
Contao Managed Edition 4.9.1 (env: prod, debug: false)
~> php -q bin/console contao:symlinks --help
Description:
  Symlinks the public resources into the web directory.
~> php -q bin/console contao:symlinks --env=prod
 --- ------------------------ ----------------------------------------------------------------
      Symlink                  Target / Error
 --- ------------------------ ----------------------------------------------------------------
  ✔   system/themes/flexible   vendor/contao/core-bundle/src/Resources/contao/themes/flexible
  ✔   web/assets               assets
  ✔   web/system/themes        system/themes
  ✔   system/logs              var/logs
```

**Comment by Toflar** [comment]
`files` is the default upload path for Contao files. Either you have to configure `contao.upload_path` to something else or you have to use a different folder name.

**Comment by joseluisq** [comment]
The problem is we are testing a migration from v4.4 to v4.9, but we have a `files` dir even symliked to `web/files`. Also there are some themes that are using that dir and documentation, links to files, etc. 
In general, It should be not a problem if we copy the entire dir to `web/files` but `contao-console contao:symlinks` is tricky.

**Comment by fritzmg** [comment]
You need to make your files folders public in the file manager of Contao.

**Comment by joseluisq** [comment]
Have you some reference how to do this? Is documented somewhere?

**Comment by fritzmg** [comment]
> Have you some reference how to do this?

Just edit the folder, check _Public_ and save. This creates the symlink and creates a `.public` file within the folder, which in turn will create the symlink on `composer install/update`.

> Is documented somewhere?

Only in German currently: https://docs.contao.org/manual/de/dateiverwaltung/downloads-kontrollieren/#verzeichnis-schuetzen

**Comment by joseluisq** [comment]
Ok, thanks. Let me to try it out and see how it behaves.

**Comment by joseluisq** [comment]
I close the issue due it was addressed via the file manager.
