### ISSUE TITLE
Geschützte Events innerhalb eines öffentlichen Events

### ISSUE THREAD

**Issue by akroii** [contao/contao#1606]
Es kann vorkommen, dass man innerhalb eines öffentlichen Archives trotzdem geschützte Events anlegen möchte (ohne ein separates Archiv anzulegen). Ist es möglich dass man auf Event-Ebene einen Haken setzen kann, dass man diesen Event-Eintrag für bestimmen Mitgliedergruppen sichtbar machen möchte? Diese sehen dann die geschützten Einträge nach erfolgreichen Login.

**Comment by fritzmg** [comment]
Das ist aktuell nicht möglich. Die Lösung innerhalb von Contao ist, zwei verschiedene Kalender dafür zu verwenden.
