### ISSUE TITLE
Adjust server_version in config.yml

### ISSUE THREAD

**Issue by stefansl** [contao/contao#1616]
I had an issue while moving a Contao installation from one server to another 
(C4.9.1 Debian 9 / MariaDB 10.1.44 -> C4.9.1 / Debian 10 / MariaDB 10.3.22).

The install tool offered a lot of ALTER TABLE ... DEFAULT NULL statements. Executing those statements via install tool or contao:migrate did not work (actually it did not execute any statement).

After a little bit of research I found out, it's a doctrine DBAL config error. Changing server_version in the config.yml from '5.7' to 'mariadb-10.3.22' changed the behaviour and all ALTER TABLE statements were gone.

I don't know, if it's a common problem, but if, the install tool could dump a config.yml with the correct values.

See: 
https://github.com/doctrine/dbal/issues/3321#issuecomment-447642346
https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration

**Comment by leofeyer** [comment]
> But isn't the server version automatically detected by Doctrine anyway?

Yes, as soon as there is a DB connection aka the login credentials have been provided. Before that, Contao falls back to the `server_version` parameter.

@stefansl Maybe you forgot to clear the cache after you had provided the DB login credentials?

**Comment by stefansl** [comment]
@leofeyer no, I started with composer create-project on the new server and copied only files, templates, DB and some modules. But I will test it again on that machine

**Comment by stefansl** [comment]
Another test:
`composer create-project contao/managed-edition test`
Go to contao/install -> add DB credentials
Contao dumped only the parameters.yml in /config

That's what I expected, because I did not find any code in the installtool writing or changing the config.yml.

**Comment by m-vo** [comment]
Contao should never ever change the config.yml. :smile: (If necessary the managed edition can prepend configuration though.)

But: Normally you don't need to explicitly set a server version at all because doctrine can guess it as soon there is a database present.

Why did you specify one in the first place? (Do you need functional tests or something?)

**Comment by stefansl** [comment]
@m-vo I never changed `server_version` before :D It must be auto-generated at some point

**Comment by fritzmg** [comment]
Oh, you had set the `server_version` to `5.7` in your _own_ `config/config.yml`?

**Comment by m-vo** [comment]
>@m-vo I never changed server_version before :D It must be auto-generated at some point

>Oh, you had set the server_version to 5.7 in your own config/config.yml?

Ok. That was what I had assumed. :smile:

**Comment by stefansl** [comment]
No, i never set `server_version`. Because I did not know about it - since yesterday

**Comment by fritzmg** [comment]
Ah ok, good :). Btw. this problem seems to be the same as or at least related to https://github.com/contao/contao/issues/979

The underlying problem is, that Doctrine is unable to auto-detect the server version in your case, for whatever reason.

**Comment by stefansl** [comment]
In my case I have a & character at the end of the password ...

**Comment by Toflar** [comment]
= Doctrine is unable to connect to the database and thus, unable to determine the version :)

**Comment by fritzmg** [comment]
Why would the Install Tool be able to connect to the database in such a case, but not Doctrine?

**Comment by stefansl** [comment]
Maybe that's the problem: I started with an 4.4 installation on the old server, where I updated to 4.9.1 (Debian 9 / MariaDB 10.1.44. 
Then I moved my DB and files to the new server MariaDB 10.3.22 - Debian 10.

I'm not sure, if I copied the parameters.yml as well, because the DB pass did not change.

The pass is not quoted in the parameters.yml. Maybe this is a result of an old issue?

**Comment by m-vo** [comment]
In 4.4 you had an older symfony version that wasn't as strict on yaml parsing. But if this was the problem you'd get errors on every container build etc.

**Comment by stefansl** [comment]
Ok, so I guess this can be closed? But for now, we know how those errors can be fixed easily and what questions we do have to ask to people having the same problem

**Comment by fritzmg** [comment]
I'd still like to know how this is possible: https://github.com/contao/contao/issues/1616#issuecomment-607706296

**Comment by m-vo** [comment]
...especially because Doctrine *is* providing a schema in your case. :-)

**Comment by fritzmg** [comment]
Yeah exactly. There must be a reason why the `server_version` auto-detection is not working, while the general database connection for everything else _is_ working.
