### ISSUE TITLE
Shared Cache bei Nutzung der Trusted-Devices Funktion

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1618]
**Affected version(s)**

Contao 4.9

**Description**

Wenn Benutzer die Trusted-Devices Funktion der 2-Faktor-Authentifizierung nutzen, wird ein ``trusted_device`` Cookie gespeichert. Dieses Cookie führt dazu, dass sämtliche Seitenaufrufe der Benutzer nicht mehr aus dem Shared Cache ausgeliefert werden - auch wenn diese nicht angemeldet sind.

**Comment by fritzmg** [comment]
I think that's normal. You have to configure the `COOKIE_WHITELIST` yourself: https://docs.contao.org/dev/reference/config/#environment-variables-for-the-contao-managed-edition

**Comment by aschempp** [comment]
We‘ve discussed this, and there‘s no easy solution to fix. However, we agreed that this can‘t be a big issue. A shared cache is meant to improve performance for 95% of your visitors, it will neber be for 100%. For example, some will run into a cache miss. And visitors that have a backend account and therefore _possibly_ a trusted device cookie are not the majority of your visitors.

**Comment by Mynyx** [comment]
> I think that's normal. You have to configure the `COOKIE_WHITELIST` yourself: https://docs.contao.org/dev/reference/config/#environment-variables-for-the-contao-managed-edition

If the cookie is generally stripped (e. g. if it is missing in the whiteliste), the trusted devices function can't work.

**Comment by Mynyx** [comment]
> We‘ve discussed this, and there‘s no easy solution to fix. However, we agreed that this can‘t be a big issue. A shared cache is meant to improve performance for 95% of your visitors, it will neber be for 100%. For example, some will run into a cache miss. And visitors that have a backend account and therefore _possibly_ a trusted device cookie are not the majority of your visitors.

The trusted devices function is available in the front end, too!? Furthermore, backend users could get a bad impression of the performance of their own website.

In opposite to the session cookie or other cookies, the ``trusted_device`` is only relevant for ``POST`` requests. Could it be a solution to strip the ``trusted_device`` cookie only at ``GET`` requests?

**Comment by aschempp** [comment]
Yes, visitors with front end logins are not the majority of visitors. If they are, the cache is useless anyway, because they will most likely be logging in ;)

> We‘ve discussed this, and there‘s no easy solution to fix.

As i said. Its not impossible, but its not easy (especially given the current Symfony security component and the two-factor bundle).

I don‘t think „a bad impression for backend users“ is a valid case. One could train them to use a different browser so they behave like a real visitor.
