### ISSUE TITLE
Crawler: Externe URIs in crawl_search-index_log.csv

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1626]
**Affected version(s)**

Contao 4.9.2

**Description**

Wenn der Crawler mit den Funktionen ``Nach defekten Links suchen`` und ``Den Suchindex aktualisieren`` gestartet wird, werden Fehler beim Crawling externer URIs auch in den ``crawl_search-index_log.csv`` aufgenommen.

**Comment by Toflar** [comment]
I think that's an Escargot issue. Can you check if https://github.com/terminal42/escargot/commit/54c495f3a881f2b8cce7ad86b805de345c0cccc1 fixes that?

PS: Could you stick to English? I noticed you do speak it so please, always do. We should allow as many people as possible to follow our project. :)

**Comment by Mynyx** [comment]
Okay, external URIs are ignored but a similiar issue remains. Broken internal links e. g. to PDF documents are still listed.

**Comment by Mynyx** [comment]
But it isn't an issue, because the content type isn't pdf if the file is missing. Than everything is fine. :)

**Comment by Toflar** [comment]
And it is a broken link, so it's correct to be reported. I'm closing this then :)
