### ISSUE TITLE
Failed login attempt in front end module login form starts session

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1627]
**Affected version(s)**

Contao 4.9

**Description**

Even if a login attempt in the front end module ``login form`` fails, a session is started and the ``PHPSESSID`` cookie is set.

**Comment by leofeyer** [comment]
@contao/developers This seems like the expected behavior, doesn't it?

**Comment by Toflar** [comment]
I don't think it's expected. It maybe is for flashbag error messages.
But what's kept in the session then?

**Comment by leofeyer** [comment]
> But what's kept in the session then?

@Mynyx Can you check please?

**Comment by Mynyx** [comment]
The attempted username is saved in the session attribute ``_security.last_username``.

During the session the attempted username is shown in the login form. Is this really sensible? It wasn't so in Contao 4.4.

**Comment by aschempp** [comment]
I think it is intended, but it should be deleted "on the first use". So the username is still there after reloading the page (after unsuccessful login).

**Comment by leofeyer** [comment]
I can confirm that the session cookie is **not** removed again after the unsuccessful login attempt. Here is the content of `$container->get('session')->all()`:

<img width="366" alt="" src="https://user-images.githubusercontent.com/1192057/85696433-3a454c80-b6d9-11ea-9463-5b7a643bdb3c.png">

**Comment by leofeyer** [comment]
@ausi @bytehead /cc

**Comment by ausi** [comment]
As far as I understand it, the `last_username` only gets removed once a successful login occurs, see https://github.com/symfony/symfony/blob/bfc0351da6c6d3af229228c27910f7f605638230/src/Symfony/Component/Security/Http/Firewall/AbstractAuthenticationListener.php#L205

**Comment by leofeyer** [comment]
Thank you for checking. Then this is indeed the intended behavior.

**Comment by aschempp** [comment]
I don't think it is. It obviously has to be removed on a successful login, because it wouldn't be shown in the login screen anymore. But we should also remove it after displaying it to the user - just so the session can be cleaned up as well.

**Comment by leofeyer** [comment]
I am not sure if we should mess with Symfony's logic here. 🤷🏻‍♂️

**Comment by aschempp** [comment]
Symfony is not very consistent with that stuff anyway, believe me I messed with it already 😆

**Comment by ausi** [comment]
In this case we could remove it from the session in our existing `ClearSessionDataListener` for GET requests with `200` responses. This should be late enough I think.

**Comment by ausi** [comment]
See #2399
