### ISSUE TITLE
Contao 4.9.2 "Templates" zeigt nur php, keine html5 mehr

### ISSUE THREAD

**Issue by lennier83** [contao/contao#1629]
**Affected version(s)**

Contao 4.9.2

**Description**

Nach update von Contao 4.9.1 -> 4.9.2 zeigt im Backend das "Templates" Verzeichnis nur noch PHP (Endung .php) Dateien an (z.B. von RockSolid Custom Elements). Keine angepassten .html5 mehr.
Sowohl bei Mittwald als auch Domainfactory. Jeweils PHP 7.2/7.3

**Comment by ghost** [comment]
Habe das selbe Verhalten und bei RockSolid Custom Elements hat es dann geklingelt. Wenn du es deinstallierst, sollte es wieder funktionieren.

**Comment by larp-welt** [comment]
Habe auch gerade das Problem, will aber nicht auf die RockSolid Custom Elementes verzichten. 
Ich probiere erstmal die Templates über Filesystem zu bearbeiten.

**Comment by ghost** [comment]
Ich bin zum Glück erst bei Projektbeginn und schiebe es noch ein bisschen auf.

**Comment by fritzmg** [comment]
https://github.com/madeyourday/contao-rocksolid-custom-elements/issues/118

**Comment by ausi** [comment]
Der Fehler wurde in Version [2.2.15](https://github.com/madeyourday/contao-rocksolid-custom-elements/releases/tag/v2.2.15) der Custom Elements Erweiterung behoben.
