### ISSUE TITLE
Redirect does not respect https when reverse proxy is used

### ISSUE THREAD

**Issue by jzaeske** [contao/contao#1630]
**Affected version(s)**

Contao 4.9.1

**Description**

I have a setup running Contao behind a Reverse Proxy, which does TLS Termination. For Contao the Environment Variable `TRUSTED_PROXIES` is set so it respects X-Forwarded-Proto Header set by the Proxy. This works for alle asset related URLs

When using redirect after login, the redirect is performed to a HTTP URL instead of HTTPS.

![image](https://user-images.githubusercontent.com/441002/78369085-f1439780-75c4-11ea-8f5f-d79d30cf681d.png)

The URL seems to be genereated in https://github.com/contao/contao/blob/9c0502bc4b41f5208a3f54e0e07e5d509be2654e/core-bundle/src/Resources/contao/modules/ModuleLogin.php#L165 

https://github.com/contao/contao/blob/85e7dda6e19d305d3e9d9958e8d5e3895afa0a74/core-bundle/src/Resources/contao/models/PageModel.php#L1113-L1132

Here only the `rootUseSSL` field in the Page Object is checked, but X-Forwarded-Proto is not.

I guess the Symfony Router behind the URL Generator would automatically detect the TLS Proxy but  was is overwritten by explicitly setting `_ssl` to falls inside the PageModel which triggers a schema overwrite in `UrlGenerator::prepareDomain`

**Comment by aschempp** [comment]
And you probably didn‘t enable the checkbox in the root page because you don‘t want the system to redirect the proxy to SSL?

Just curious, why would anyone today - with the availability of free certificates like LetsEncrypt - still use such a reverse proxy setup?

**Comment by jzaeske** [comment]
We have a shared database instance for a preview environment (with TLS, Proxy does provisioning of Certificates from LetsEncrypt) and a local development environment (withou TLS). 

If I enable the checkbox, the local environment would break.
So I like to handle TLS specific behaviour without configuration in the database

I admit, this is probably not a very common setup, but since database manipulation is done on both environments we need to keep them synchronized.

**Comment by leofeyer** [comment]
Is there anything that we can do to fix the issue?
