### ISSUE TITLE
Installation Contao 4.9 und MAMP Pro schlägt fehlt wegen server_version

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#1631]
**Affected version(s)**
- Contao 4.9
- MacOS Catalina
- PHP 7.4
- MAMP Pro 5.7

**Description**
Bei einer frischen Installation von Contao 4.9 über den Contao Manager bricht die Installation kurz vor Schluss ab. Problem ist wohl die Prüfung der Datenbankverbindung. (siehe Ausgabe)

Leider konnte ich bisher den Fehler nur bei 2 Kunden sehen, allerdings bei meinem eigenen System nicht nachvollziehen und reproduzieren.

Das Problem tritt erst seit Contao 4.9 auf.
Wenn Contao 4.4 installiert wird, läuft alles fehlerfrei durch.

Hier auch ein Beitrag im Forum zu diesem Problem.
https://community.contao.org/de/showthread.php?77266-Lokale-Installation-von-contao-4-9-in-MAMP-mit-php7-4-2-unvollst%C3%A4ndig-bricht-ab

Wie kann das Problem analysiert werden bzw. wie kann ich zur Fehlersuche beitragen?

```
- Installing contao/newsletter-bundle (4.9.2): Downloading (100%)
Generating optimized autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
In ScriptHandler.php line 89:
  An error occurred while executing the "contao:install-web-dir" command:      
  In ConnectionFactory.php line 79:                                            
                                                                    
    An exception occured while establishing a connection to figure out your p  
  la                                                                           
    tform version.                                                             
                                                                               
    You can circumvent this by setting a 'server_version' configuration value  
                                                               
    For further information have a look at:                                    
                                                                               
    https://github.com/doctrine/DoctrineBundle/issues/673                      
                                                                   
  In AbstractMySQLDriver.php line 93:                                          
                                                                       
    An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for  
   u                                                                           
    ser 'root'@'localhost' (using password: NO)                                
                                                                     
  In PDOConnection.php line 31:                                                
                                                                    
    SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using p  
  as                                                                           
    sword: NO)                                                                 
                                                                     
  In PDOConnection.php line 27:                                                
                                                                 
    SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using p  
  as                                                                           
    sword: NO)                                                                 

```

**Comment by netzarbeiter** [comment]
Dieses Problem ist mir auch schon begegnet, geholfen hat folgendes:

Ein Verzeichnis «config» erstellt und darin die Datei mit Namen «parameters.yml» mit folgendem Inhalt angelegt:

```yml
parameters:
    database_host: localhost
    database_port: 3306
    database_user: benutzer
    database_password: 'passwort'
    database_name: datenbankname
```

Danach die Paket Aktualisierung erneut starten.

**Comment by contaoacademy** [comment]
Ich konnte jetzt die Ursache für den Fehler herausfinden.

Der Fehler entsteht dann, wenn ein anonymer User angelegt ist.
(siehe Screenshots)
Sobald der User gelöscht wird, funktioniert wieder alles.


**Frage**
Ist es ein Contao Problem oder ein Konfigurationsproblem?
Kann dieses Problem abgefangen werden?

![user-accounts](https://user-images.githubusercontent.com/23719181/78556658-a49fcc80-780f-11ea-8f16-61dfa8b4b70f.jpg)


![users](https://user-images.githubusercontent.com/23719181/78556538-715d3d80-780f-11ea-9250-cb25364a5cfd.jpg)

Ein ähnliches Thema in einem anderen Zusammenhang siehe https://github.com/contao/core-bundle/issues/736

**Comment by leofeyer** [comment]
> Ist es ein Contao Problem oder ein Konfigurationsproblem?

Es ist auf jeden Fall kein Contao-Problem. Vermutlich hast Du `mysql_secure_installation` nicht ausgeführt, sonst wäre der anonyme Benutzer entfernt worden.

**Comment by m-vo** [comment]
Für die lokale Entwicklung kannst du deinem Datenbankserver auch klarmachen, dass er Benutzer und Passwörter generell ignorieren soll:

```
#/etc(/mysql)/my.cnf

[mysqld]
skip-grant-tables
```

Macht das Leben leichter. :smile:

**Comment by contaoacademy** [comment]
@leofeyer 
Ich habe im Grunde gar nichts gemacht, da ich davon ausgegangen bin, dass MAMP das schon für mich alles machen wird ;-)

@m-vo
Danke für den Tipp. Ich werde das testen.

Sollen wir das Ticket dann schließen, denn damit ist es ja kein Contao Problem.

**Comment by aschempp** [comment]
Aus meiner Sicht ist es etwas, das wir verbessern sollten.

**Comment by leofeyer** [comment]
Und hast Du auch eine Idee, wie man das verbessern könnte?

**Comment by aschempp** [comment]
Naja, wir machen ja bereits ein DB Connect um herauszufinden ob wir die server_version setzten müssen. Scheinbar reicht das nicht, d.h. wir müssten auch prüfen ob der (anonyme) User effektiv was tun kann? Vielleicht ein `List Tables` oder so?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/1698 for the bug fix
