### ISSUE TITLE
Backend section Templates shows php files only after update to 4.9.2 

### ISSUE THREAD

**Issue by ben-eSM** [contao/contao#1633]
**Affected version(s)**
Contao 4.9.2

**Description**
After updating an installation to 4.9.2, the templates editor shows only php files. All .html5 files don't show up. I think it must be related to the changes made in #1591

**Comment by bytehead** [comment]
Maybe related to #1629?

**Comment by leofeyer** [comment]
The issue has been fixed in version [2.2.15](https://github.com/madeyourday/contao-rocksolid-custom-elements/releases/tag/v2.2.15) of the Custom Elements extension.

**Comment by ben-eSM** [comment]
Oh well...didn't check well enough. Thanks for the hint. That solves it. Just assumed due to the changelog it might be related with that commit. Sorry! 😳

**Comment by leofeyer** [comment]
No problem 😊
