### ISSUE TITLE
Deletion of wrong translation in file not possible

### ISSUE THREAD

**Issue by Olli** [contao/contao#1635]
**Affected version(s)**

 Contao 4.9.2

**Description**
If a file has a additional description in a foreign language and this description should be deleted with a click on x (see image)
![grafik](https://user-images.githubusercontent.com/1754/78541192-bd46bd00-77e4-11ea-83bc-75d2a3aa6e41.png)
it's not been deleted. The js console puts an error:
"TypeError: n.getElement(...) is null" (line 13378) ... 
The metaDelete function tries to get a <select> but the <select> isn't been found.

**Comment by aschempp** [comment]
Can you reproduce this in the Contao demo at https://demo.contao.org ?

**Comment by Olli** [comment]
No because in the demo I cant edit the metadata of image files :(

**Comment by Olli** [comment]
I just tried it on my own demo system. I can reproduce it.

**Comment by Olli** [comment]
Maybe some additional info:
I added in the site tree a root site with an unknown language code. Then I changed the language code to something other. 
Some files which I had edited did have the old wrong language code and the new language code. The descriptions of the old language code can't be deleted.
Sorry that I had forgotten to provide that additional info in the first place.

**Comment by Olli** [comment]
Danke - Works like a charm :+1:
