### ISSUE TITLE
initialize.php always expects a request

### ISSUE THREAD

**Issue by aschempp** [contao/contao#1637]
@Toflar Can it be, that the newest version detects console-commands as GET Requests but has no URI, because we are on the console? I'm getting a similar error on all cronjob-commands, since i updated from Contao 4.9.1 to 4.9.2 with all dependencies.

**One example command would be:**
`vendor/terminal42/notification_center/bin/queue -s 2 -n 10`

**Error:**
```
Fatal error: Uncaught InvalidArgumentException: Unable to parse URI: http://:/ in /home/linderim/public_html/contao49/vendor/nyholm/psr7/src/Uri.php:51
Stack trace:
#0 /home/linderim/public_html/contao49/vendor/contao/core-bundle/src/Search/Document.php(133): Nyholm\Psr7\Uri->__construct('http://:/')
#1 /home/linderim/public_html/contao49/vendor/contao/core-bundle/src/EventListener/SearchIndexListener.php(68): Contao\CoreBundle\Search\Document::createFromRequestResponse(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpFoundation\Response))
#2 /home/linderim/public_html/contao49/vendor/symfony/event-dispatcher/EventDispatcher.php(304): Contao\CoreBundle\EventListener\SearchIndexListener->__invoke(Object(Symfony\Component\HttpKernel\Event\TerminateEvent), 'kernel.terminat...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /home/linderim/public_html/contao49/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Compon in /home/linderim/public_html/contao49/vendor/nyholm/psr7/src/Uri.php on line 51
```

**As a Hotfix i added this:** 
```php
if ($request->getUri() == 'http://:/'){
    return;
}
```

to /vendor/contao/core-bundle/src/EventListener/SearchIndexListener.php just before the Call to createFromRequestResponse() on Line 67.

Is this a local problem in my page or something caused by a logic-error in the SearchIndexListener?
_In the database i could not find an empty href-attribute._

Thanks in advance for your help

_Originally posted by @rorych in https://github.com/contao/contao/issues/1356#issuecomment-610245747_

**Comment by fritzmg** [comment]
See https://github.com/contao/contao/issues/1356#issuecomment-679941392

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2344 and https://github.com/contao/contao/pull/2345
