### ISSUE TITLE
No cache invalidation if publish/unpublish an element with eye icon

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1641]
**Affected version(s)**

4.9.2

**Description**

If publish/unpublish or hide/unhide an element with the edit operation, related cache entries will be automatically invalidated. 

But if publish/unpublish or hide/unhide an element with the eye icon this doesn't happen.

**Comment by leofeyer** [comment]
This issue needs to be confirmed and fixed.

**Comment by Toflar** [comment]
Easy to confirm: The `toggleVisibility` callbacks never execute cache tag invalidation because they do not rely on DC methods.
