### ISSUE TITLE
Dateiverwaltung -> Alle öffnen -> Error 500

### ISSUE THREAD

**Issue by kalterwind** [contao/contao#1648]
**Affected version(s)**

Contao 4.9.2 (war auch in 4.9.1)

**Description**

System > Dateiverwaltung, klick auf "Alle umschalten".
Error 500.

Ordner hat nur 14.5 MB.
7 Unterordner (einige davon mit einem weiteren Unterordner).
Insgesamt nur ca 110 Dateien. Keine Datei über 500KB.
Keine Sonderzeichen oder defekte Dateien ersichtlich. Ich kann jeden Ordner einzeln in der Dateiverwaltung öffnen.

**Öffne ich alle, Error 500:**
`[08-Apr-2020 12:36:23 Europe/Berlin] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1466368 bytes) in /www/htdocs/XXXXX/demo/XXXXX/var/cache/prod/ContainerP4nCwVR/appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php on line 508
[08-Apr-2020 12:36:23 Europe/Berlin] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1466368 bytes) in /www/htdocs/XXXXX/demo/XXXXX/vendor/composer/ClassLoader.php on line 444`

Server All Inkl, Premium Paket.

**Comment by xchs** [comment]
Du könntest mal versuchen, das PHP Memory Limit in der `web/.htaccess` entsprechend zu erhöhen:
```
php_value memory_limit 512M
```

**Comment by kalterwind** [comment]
> Du könntest mal versuchen, das PHP Memory Limit in der `web/.htaccess` entsprechend zu erhöhen:
> 
> ```
> php_value memory_limit 512M
> ```

Das brachte keine Veränderung, außer das der Error gestiegen ist:
`[09-Apr-2020 09:33:00 Europe/Berlin] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 1466368 bytes) in /www/htdocs/XXXXX/demo/XXXXX/var/cache/prod/ContainerP4nCwVR/appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php on line 508
[09-Apr-2020 09:33:00 Europe/Berlin] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 1466368 bytes) in /www/htdocs/XXXXX/demo/XXXXX/vendor/composer/ClassLoader.php on line 444`

Und das kann bei den wenigen Daten ja eigentlich auch gar nicht sein.
Bei Contao 4.4 hatte ich ganz andere Projekte auf gleichem Server wo es keinerlei Probleme gibt.

**Comment by bytehead** [comment]
Dann reichen auch 512M nicht aus. Was passiert wenn du da `-1` angibst?

**Comment by Toflar** [comment]
Evtl. ein Endless-Loop?

**Comment by kalterwind** [comment]
-1 funktioniert.
Aber halte es ehr für einen Fehler bei den kleinen Daten... wie zB ein Endless Loop!?

Habe auch mal einen Test einer ganz anderen Webseite (ebenfalls mit 4.9.2) gemacht, dort gleiches Problem (gleicher Server). Es sind dort auch nur wenige Daten drin und ganz andere (was eine defekte Datei in der ersten Installation ausschließt, wo zB ein Vorschaubild nicht generiert werden könnte oä).

**Comment by fritzmg** [comment]
Can you provide us with your `files/` directory?

**Comment by kalterwind** [comment]
> Can you provide us with your `files/` directory?

Unfortunately not for licensing reasons, customer data.
But the same problem also with completely different data. Only JPGs contain up to 22 per folder.
Does not occur in all folders, maybe only if there are at least 3 levels (files/bilder/gueterverkehr/lokomotiven/).
(PHP Version 7.3.11-nmm1 + PHP Version 7.4.2)

**Comment by fritzmg** [comment]
I cannot reproduce this issue. I made a test putting 2.05 GiB worth of files into `files/`, 2520 files in total, within 321 folders. The peak memory usage of the request to open all folders was only 48 MiB. I also tried to synchronize the DBAFS and then re-open the file manager in its state with all folders open, still only 50 MiB peak memory usage.

**Comment by kalterwind** [comment]
Mein Deutsch ist besser, sorry^^

Ich habe auf einem anderen Server (ebenfalls gleiches Paket bei All Inkl) ebenso eine 4.9.2 Installation in Entwicklung, dort habe ich die Daten mal hinkopiert, dort ging es auch ohne Probleme.

Jetzt frag ich mich, wieso es bei 2 Installationen auf dem gleichen Server mit komplett unterschiedlichen Daten auftritt. Alle Daten sind Web optimiert und relativ Klein.
In dem Files Ordner sind mehrere Unterordner, das Problem tritt auch nicht bei allen auf, in einer Installation habe ich mal 4 von 5 Ordnern der 1. Ebene entfernt, dann blieb das Problem. Wenn ich alle 4 drin lasse und den 5. entferne, dann geht es... . Wieso es an diesem Ordner liegt kann ich nicht verstehen (außer das es dort mehrere Unterordner gibt). In der anderen Installation sind es halt aber auch komplett andere Ordner/Dateien.

Ich kann es sonst erstmal ignorieren, nur "-1" geht es ja jetzt (da der Kunde relativ oft zu viele Ordner anklickt und dann den 500er Error erhält). Wenn die Seite Online geht wechselt der Server, vllt erledigt sich das dann damit. Scheint für mich jedoch ein Fehler in Contao zu sein, da ich das Problem bei 30 anderen Installation noch nie hatte (mit <4.9).

**Comment by fritzmg** [comment]
> Scheint für mich jedoch ein Fehler in Contao zu sein

We cannot confirm that without a proper reproduction.

**Comment by xchs** [comment]
Könntest Du bitte mal Deine `composer.json` zeigen?

**Comment by kalterwind** [comment]
> Könntest Du bitte mal Deine `composer.json` zeigen?

```{
    "type": "project",
    "require": {
        "christianbarkowsky/contao-tiny-compress-images": "^1.0",
        "codefog/contao-cookiebar": "^2.2",
        "contao/conflicts": "*@dev",
        "contao/listing-bundle": "4.9.*",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "4.9.*",
        "craffft/css-style-selector-bundle": "^1.6",
        "do-while/contao-backupdb-bundle": "^1.4",
        "omosde/contao-om-backend": "^1.6"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

und die andere Installation die mir auffiel:

```{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0-or-later",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": "^7.1",
        "christianbarkowsky/contao-tiny-compress-images": "^1.0",
        "contao/conflicts": "*@dev",
        "contao/listing-bundle": "4.9.*",
        "contao/manager-bundle": "4.9.*",
        "do-while/contao-backupdb-bundle": "^1.4",
        "omosde/contao-om-backend": "^1.6"
    },
    "conflict": {
        "contao-components/installer": "<1.3"
    },
    "require-dev": {
        "sensiolabs/security-checker": "^4.1"
    },
    "extra": {
        "branch-alias": {
            "dev-4.6": "4.6.x-dev"
        },
        "contao-component-dir": "assets"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**Comment by xchs** [comment]
Bitte wiederhole den Test ohne installierte Drittanbietererweiterungen!

**Comment by fritzmg** [comment]
@kalterwind please post your composer.jsons in three backticks, not one.

**Comment by asaage** [comment]
@kalterwind hast du evl. sonderbare Zeichen in den Datei-/Ordnernamen?
Oder Datei-/Ordnernamen, die auf gleicher Ebene in unterschiedlicher Groß-/Kleinschreibung existieren?
Kann mich erinnern, das ich das vor geraumer Zeit auch mal hatte (war glaube ich noch Contao 3) und die Dateiverwaltung das mit 500er quittierte.

**Comment by kalterwind** [comment]
Datei/Ordner kann ich jetzt nicht entdecken. Ich selbst achte da genau drauf. Kunden muss man es zwar immer wieder sagen. Das Problem schließe ich hier jedoch eigentlich aus (Dateien wurden mittlerweile etwas verschoben)... denn Ordner A alleine funktioniert, Ordner B ebenso. Aber A+B funktioniert nicht. Was für mich auf ein Memory Problem / Loop oder was auch immer hindeutet.

Habe alle Erweiterungen im Manager deinstalliert.
Cache gelöscht.

Problem blieb bestehen.

Ich kann nächste Woche versuchen eine neue Installation aufzubauen und es mit Demo Bildern zu reproduzieren, die ich freigeben kann.

**Comment by bennyborn** [comment]
@kalterwind Schau mal bitte ob es etwas bringt wenn Du im Backend in Deinem Profil den Haken bei `Vorschaubilder anzeigen` entfernst. Wir hatten eine ähnliche Situation mal bei einem Kunden mit sehr vielen Dateien und Unterordnern. So kann man zumindest eingrenzen ob es vielleicht am Generieren der Thumbnails liegt.

**Comment by fritzmg** [comment]
@bennyborn besteht das Problem auch in Contao 4.9? Dort werden die Bilder nicht im selben Request erzeugt.

**Comment by bennyborn** [comment]
@fritzmg Dazu kann ich leider noch nichts sagen da ich aufgrund des komplexen Deployments (auf Amazon) die Installation leider nicht einfach testweise updaten kann.

**Comment by fritzmg** [comment]
Also war es eine 4.4 Installation? Dann wird das vermutlich unter Contao 4.9 nicht mehr das Problem sein.

**Comment by kalterwind** [comment]
> @kalterwind Schau mal bitte ob es etwas bringt wenn Du im Backend in Deinem Profil den Haken bei `Vorschaubilder anzeigen` entfernst. Wir hatten eine ähnliche Situation mal bei einem Kunden mit sehr vielen Dateien und Unterordnern. So kann man zumindest eingrenzen ob es vielleicht am Generieren der Thumbnails liegt.

Brachte leider nichts, danke aber für den Tipp.

Da ich (dank Corona-Zeit) nun auch in Kurzarbeit bin, habe ich diese Woche wohl leider neben den Jobs keine Zeit über für einen Aufbau zum freigeben (hoffe das zeitnah nachzuholen).
