### ISSUE TITLE
Add a click event for redisplaying the FE preview button after it's been hidden by the user

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1649]
Hello,

the title says it all. After I had hidden the frontend preview bar with the button on the right, I was unable to display it again (like the symfony debug bar is able to).

Of course, I could delete the cookies but a click would be more convenient. Especially for editors.

Or am I missing something?

Bye Defcon0

**Comment by leofeyer** [comment]
See #1623.

**Comment by Defcon0** [comment]
Ah, I see, sorry for that one.
