### ISSUE TITLE
Establish rules for service definitions

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1655]
**Class names or service ID**

We generally want to use class names instead of service IDs (see #763). There will be cases in which this does not work:

 * Two services use the same class (e.g. `contao.assets.assets_context`)
 * A service uses a third-party class (e.g. `contao.csrf.token_manager`)

**Service autoconfiguration**

Using service autoconfiguration is allowed in our bundles.

**Service autowiring**

Service autowiring should not be used in bundles (see [the Symfony docs](https://symfony.com/doc/current/service_container/autowiring.html#public-and-reusable-bundles)), however, since Contao is something in between a bundle and an app, there are exceptions to this rule:

 * Anything that implements the `ServiceSubscriberInterface` (mostly controllers)

A possible convention would be to have a `services.yml` file without autowiring and several specific files such as `controllers.yml` or `migrations.yml` that use autowiring.

**Comment by leofeyer** [comment]
@contao/developers Please help defining the exceptions rule above (see TODO).

@aschempp You mentioned something about services that run "in the app context" and other that do not. Can you explain this again please?

**Comment by aschempp** [comment]
> You mentioned something about services that run "in the app context" and other that do not. Can you explain this again please?

That's probably what you meant above with *since Contao is something in between a bundle and an app, there are exceptions to this rule.*.

Some of our services (like routing or security) are part of the _framework_, but some (like commands or voters) are part of the _application_ to me.

**Comment by leofeyer** [comment]
I am closing this in favor of #3686.
