### ISSUE TITLE
Add "do not track" option to the Vimeo content element

### ISSUE THREAD

**Issue by nkirstein** [contao/contao#1657]
By default, Vimeo sets a cookie to track the performance of an embedded player. By adding "dnt=1" to the URL, you can disable tracking and prevent Vimeo from setting a cookie: https://vimeo.zendesk.com/hc/en-us/articles/360001494447-Using-Player-Parameters (search for "dnt").

As of Contao 4.9.2, this can only be done by editing the ce_vimeo template. I think it would be nice to have a checkbox for this option in the Vimeo content element, along with autoplay, looping etc.

**Comment by Mynyx** [comment]
Would there be any disadvantage if the ``dnt`` option is set by default?

**Comment by nkirstein** [comment]
As far as I understand, `dnt=1` disables tracking of the video completely so playback events won't get registered in the Vimeo viewing statistics. That's quite a significant departure from the expected behavior. So I don't think the option should be enabled by default.

**Comment by MarkejN** [comment]
This seems to be a small change. I could create a PR for it, if it is still wanted?

**Comment by fritzmg** [comment]
Sure, go ahead :). Should be implemented in the same manner as the options of the YouTube element, I think?

**Comment by aschempp** [comment]
Closed in favour of https://github.com/contao/contao/pull/3379
