### ISSUE TITLE
German translations: Sie/sie

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1660]
**Affected version(s)**

Contao 4.9.2

**Description**
Creating a new event archive:
![grafik](https://user-images.githubusercontent.com/1645099/79074895-5b5beb00-7cef-11ea-9ce8-60b799c82162.png)

Text:
"Bitte wählen Sie die Eventleser-Seite aus, zu der Besucher weitergeleitet werden, wenn **_Sie_** ein Event anklicken."

It should be a small "sie" and not the polite "Sie", becaus it refers to "Besucher" and not to the backend user.

**Comment by leofeyer** [comment]
I have updated the German translation on transifex.com. It will be shipped with the next release.
