### ISSUE TITLE
Replace the Ocramius/PackageVersions package

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1662]
**Affected version(s)**

Contao 4.9

**Description**

Since the will not be a version that is compatible with PHP 7.2/7.3 and Composer v2 (see https://github.com/Ocramius/PackageVersions/pull/133), we should no longer use the package and e.g. fork it or extend our own `PackageUtil` class.

**Comment by m-vo** [comment]
As long as `doctrine/orm` is also using that same package (and we're using doctrine), this effectively won't change anything, right? :man_shrugging:

**Comment by m-vo** [comment]
(unless we're composer-replacing it of course)

**Comment by leofeyer** [comment]
Dang 😣

**Comment by bytehead** [comment]
Doctrine has to solve the issue as well, don't they?

**Comment by aschempp** [comment]
> As long as `doctrine/orm` is also using that same package (and we're using doctrine), this effectively won't change anything, right? 🤷‍♂️

Well if our package "provides" or "replaces" `ocramius/package-versions` then we'd be on the safe side imho. Or if we can get someone like https://packagist.org/packages/muglug/package-versions-56 to "provide" 

Edit: Quickly checking Packagist, `muglug/package-versions`, `muglug/package-versions-56`, `samsonasik/package-versions` and `vdechenaux/package-versions` all replace `ocramius/package-versions` 🤷

**Comment by Toflar** [comment]
There's an official replacement now by Composer itself :) 
https://github.com/composer/composer/commit/1d4185b844dd22718562fcfe77d3ad785aa2c8fa

https://packagist.org/packages/composer/package-versions-deprecated

**Comment by leofeyer** [comment]
Ok, so we can omit the package and use `Composer\Versions` for our `PackageUtil` class instead, correct? Do we also have to require `composer/package-versions-deprecated` somewhere so we can install Doctrine with PHP 7.2 and Composer v2?

**Comment by Toflar** [comment]
> Ok, so we can omit the package and use `Composer\Versions` for our `PackageUtil` class instead, correct?

No, we can't. We can only do that once Composer v2 is out and stable and we will force everybody to install Contao using Composer v2 only from then on.
Right now, we have to replace our requirement.

**Comment by leofeyer** [comment]
It seems that Composer v2 installs `composer/package-versions-deprecated` automatically if you require `ocramius/package-versions` and do not have PHP 7.4. Can you confirm? Then we would not have to do anything and we could close this PR.

**Comment by m-vo** [comment]
Where did you find this? 

All I know so far is that a notice is generated:
https://github.com/composer/composer/blob/master/src/Composer/DependencyResolver/SolverProblemsException.php#L70

**Comment by leofeyer** [comment]
I stumbled upon it when I tried to install Contao with Composer v2 and the packages was removed and the other one installed. Even though I was still requiring `ocramius/package-versions` in my composer.json file.

**Comment by ausi** [comment]
Maybe one of the dependencies installs a replacement for `ocramius/package-versions`?

**Comment by leofeyer** [comment]
That seems more likely indeed. 😄

**Comment by leofeyer** [comment]
But it is not the case:

```
$ composer why composer/package-versions-deprecated                      
composer/package-versions-deprecated  1.8.0    replaces  ocramius/package-versions (1.2 - 1.8.99)  
doctrine/orm                          v2.7.2   requires  ocramius/package-versions (^1.2)          
ocramius/proxy-manager                2.2.3    requires  ocramius/package-versions (^1.1.3)        
symplify/easy-coding-standard         v7.3.15  requires  ocramius/package-versions (^1.4)    
```

This comes in very handy. 😎

**Comment by m-vo** [comment]
But who is requiring composer/package-versions-deprecated is the question, isn't it? :smiley:

**Comment by leofeyer** [comment]
No?

**Comment by Toflar** [comment]
Sure, that is the question. Replacements don't just happen magically :)
Here's the reason:

`symplify/easy-coding-standard@7.3.15` requires `jean85/pretty-package-versions@^1.2` and depending on your combinations, this one might load `composer/package-versions-deprecated`: https://github.com/Jean85/pretty-package-versions#compatibility

But there's no magic. We need to require `composer/package-versions-deprecated` ourselves.

**Comment by m-vo** [comment]
Then I don't get it. I see one "replaces" in the list (from `composer/package-versions-deprecated` itself) and the others requiring the original bundle?

Edit: Eh, sorry for the spam. The other answer did not load for me until after submitting the message. :see_no_evil:
