### ISSUE TITLE
Call to Collection::createFromDbResult throws ClassNotFoundException if Model::getClassFromTable does not return a valid class name

### ISSUE THREAD

**Issue by felix-kaestner** [contao/contao#1665]
**Affected version(s)**

Contao 4.4 and above

**Description**

The static function  `createFromDbResult`  from the class  `Contao\Collection`  includes the following:
`$strClass = Model::getClassFromTable($strTable);` [(link)](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Model/Collection.php#L127)

Currently there is not check, wether this class name is valid or not. This results in an error later since Contao tries to create an instance of this class. [(see here)](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Model/Collection.php#L141)

A possible solution would be to return null in this case, like
```
if(!class_exists($strClass)){
    return null;
}
```
in line [#128](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Model/Collection.php#L128).

Note: This check is also done in other place that use the function `Model::getClassFromTable` like the classes [Hybrid](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/classes/Hybrid.php#L110), [BackendFile](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/controllers/BackendFile.php#L90), [BackendPage](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/controllers/BackendPage.php#L90), while others also assume only valid class names returned from `Model::getClassFromTable` like the classes [Model](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Model.php#L163) and [tl_page](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/dca/tl_page.php#L1569).

As far as I can tell, the only usage of the function `Collection::createFromDbResult(Result $objResult, $strTable)`  within Contao is inside the Model class with the function `Contao\Model::createCollectionFromDbResult(Result $objResult, $strTable)`. [(link)](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Model.php#L1261)

This function is called in the following places [CommentsNotifyModel](https://github.com/contao/contao/blob/master/comments-bundle/src/Resources/contao/models/CommentsNotifyModel.php#L130), [StyleSheetModel](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/models/StyleSheetModel.php#L103), [NewsletterRecipientsModel](https://github.com/contao/contao/blob/master/newsletter-bundle/src/Resources/contao/models/NewsletterRecipientsModel.php#L127), [Model](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Model.php#L1102), [MemberModel](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/models/MemberModel.php#L254) and [PageModel](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/models/PageModel.php#L615). 

All of these have a possible return value of `null` which would the proposed solution valid, I guess. 

My question is wether these findings represent a valid bug in Contao. If so, I could provide a Pull Request which solves this Issue, if you wish to.
Otherwise please let me know if this is a wanted behaviour and I will be happy to close this Issue and use a try-catch statement instead.

**Comment by fritzmg** [comment]
Why do you want it to return null? If the Model class is missing, then an exception should be thrown.

**Comment by felix-kaestner** [comment]
My initial thought was that if the model class is invalid, it could return null in a means of that there are no actual models for this table. But now that I think of it in another way, you are right. Since this function is only called by Contao\Model, I guess it is only meant to handle cases where there is an actual model class and throw an exception if that class is missing. I was thinking that this function could also be used in a more generic way aside from Contao Models. Like for example, with Doctrine Entities where the class name and table name would not align. So null would mean no models for this table. But I guess that is out of scope.

**Comment by felix-kaestner** [comment]
As stated above, I think this Issue can be closed.
