### ISSUE TITLE
Meta data fields are in chapter "forwarding target"

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1666]
**Affected version(s)**

Contao 4.9.2

**Description**
backend: news editing

Contao 4.9.2
meta data fields are in chapter "forwarding target".
![grafik](https://user-images.githubusercontent.com/1645099/79689605-41258e00-8256-11ea-86aa-a6dc5580f629.png)

Expected behavior:

Contao 4.9.0 (demo.contao.org)
seperate "meta data" chapter
![grafik](https://user-images.githubusercontent.com/1645099/79689647-847ffc80-8256-11ea-837f-10568010e1e4.png)

Not in chapter "forwarding target"
![grafik](https://user-images.githubusercontent.com/1645099/79689623-60242000-8256-11ea-8336-d8a4a7228044.png)

**Comment by fritzmg** [comment]
That's intentional. See https://github.com/contao/contao/pull/1598

**Comment by fritzmg** [comment]
Though I do agree, that it would be nicer to keep having it in its own fieldset.

**Comment by aschempp** [comment]
It should easily be possible to have its own palette, it would just require a page reload instead of fetching the fields through Ajax.

**Comment by leofeyer** [comment]
> Though I do agree, that it would be nicer to keep having it in its own fieldset.

Then the fields would be visible although their values would never be used. How is this nicer?

**Comment by fritzmg** [comment]
Well, may be just adjust the palette in an `config.onload_callback`?

**Comment by leofeyer** [comment]
So that when you change something way down the page, new fields appear at the top of the page? That seems like a bad UX decision.

**Comment by fritzmg** [comment]
It's the same situation as with the website root fallback. If you enable `fallback`, a whole new fieldset `{website_legend},favicon,robotsTxt;` is added to the palette. Why not do the same here?

The only difference is, that the new fieldset for `tl_page` is directly after the `fallback` checkbox. We could move the meta fieldset of `tl_news` after the source fieldset. Or, conversely, move the source fieldset up.

**Comment by contaoacademy** [comment]
I would prefer the solution as separate "meta data".

> new fields appear at the top of the page

The default setting is "standard", so the fields are hidden after changing the option.

**Comment by leofeyer** [comment]
As discussed in Mumble on May 7th, we want to move the "Redirect target" fieldset after the "Date and time" fieldset and have the meta fields in their own fieldset after the "Redirect target" fieldset.
