### ISSUE TITLE
Set helpful values to autocomplete attribute in user context

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1669]
Instead of ``autocomplete="off"`` the following values for the ``autocomplete`` attribute could be set in forms of the user context (e.g. registration, login).

Credential | Autocomplete Values
-- | --
User Name | username
Password | current-password
New Password | new-password
One-Time Code | one-time-code

https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by dmolineus** [comment]
Related: https://github.com/contao/contao/issues/598
