### ISSUE TITLE
The installation-bundle is missing require in the core-bundle

### ISSUE THREAD

**Issue by baumannsven** [contao/contao#1671]
The command `contao:migrate` use the database installer from the `installation-bundle`.

So i think the `core-bundle` must require the `installation-bundle`.

**Comment by m-vo** [comment]
Imo it must be the other way round: You cannot use the installer if you do not require the installation bundle (meaning: there should not be a core dependency that requires the latter).

**Comment by baumannsven** [comment]
The command `contao:migrate` has a usage of the a class from the `installation-bundle`.
See https://github.com/contao/contao/blob/edf7b746548da900ce5fe44211c4d36089f809b2/core-bundle/src/Command/MigrateCommand.php#L18.

@m-vo

**Comment by m-vo** [comment]
The command should probably not be registered in that case. Unresolved usages do not break code btw.

**Comment by fritzmg** [comment]
@baumannsven the installer is optional: https://github.com/contao/contao/blob/edf7b746548da900ce5fe44211c4d36089f809b2/core-bundle/src/Command/MigrateCommand.php#L51

**Comment by discordier** [comment]
The installer is "optional", as noted [here](https://github.com/contao/contao/blob/edf7b746548da900ce5fe44211c4d36089f809b2/core-bundle/src/Command/MigrateCommand.php#L199)

> The command should probably not be registered in that case. Unresolved usages do not break code btw.

I do not know how you define "Unresolved usage", but it definitely CAN break code.

**Comment by Toflar** [comment]
The installer needs to be moved anyway. I thought there's already an issue for that.
Imho the best way to hotfix this is a class_exists() and a message to install the installation-bundle as done in many places in Symfony. We can then remove that once the installer is part of the core.
Removing the command is not a good idea, imho. It doesn't let people understand why it's missing.

**Comment by m-vo** [comment]
> I do not know how you define "Unresolved usage",

Putting a class inside a `use` statement that doesn't exist is valid code. Otherwise you could not use a `class_exist` check together with imports.

**Comment by discordier** [comment]
> > I do not know how you define "Unresolved usage",
> 
> Putting a class inside a `use` statement that doesn't exist is valid code. Otherwise you could not use a `class_exist` check together with imports.

That is true but simply specifying a class via `use` does not count as usage of a class but rather as defining an alias of the class in the current scope (hence the fatal errors when importing a class via 
`use` that is already defined in the current namespace).
Accessing the class or its members however counts as usage of the class.
This is however unrelated to this issue but simply definition of how the PHP internals work.

**Comment by ausi** [comment]
The case of a missing installer is already handled by the migrate command: https://github.com/contao/contao/blob/e1a12ef3ef3217de448a03d91d3ca429014de178/core-bundle/src/Command/MigrateCommand.php#L199

See also: https://github.com/contao/contao/pull/709#discussion_r358099163

**Comment by leofeyer** [comment]
As discussed in Mumble on June 4th, the current setup is correct. The installation bundle is not required to run Contao (e.g. in production) unless you want to run `contao:migrate`, which will check this itself.
