### ISSUE TITLE
Update scssphp to 1.1.0 for Contao 4.4 and higher

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#1672]
**Affected version(s)**

Contao 4.4 and higher

**Description**

With combination of Zurb Foundation 6 you get from scssphp **infinite calling loop** error by compiling the scss files. See [scssphp#89](https://github.com/scssphp/scssphp/issues/89)

The problem is fixed by scssphp in [Tagging 1.1.](https://github.com/scssphp/scssphp/tree/1.1.0)

Can you please fix this problem also by Contao 4.4 and higher in  .../core-bundle/composer.json?

Thanks a lot.

**Comment by leofeyer** [comment]
There is nothing to do on our side. Next time you run `composer update`, you will get version 1.1 automatically.
