### ISSUE TITLE
Add fields for copyright to the file manager

### ISSUE THREAD

**Issue by jankout** [contao/contao#1675]
According to the copyright law it is not just necessary to mention the author but also the licence, if there is a special one, and link to it. If we could do it in the file manager that would be great. But for this case it would be nice to have 2 (or more) additional fields 

**1. Licence
2. Link to the licence**
_Maybe_
**3. Author 
4. Link to author**

I'm suggesting it because in current version these informations are not separated and if I use the current link field there this is not optimal because it can collapse with another links. I think it should be core function.

**Comment by fritzmg** [comment]
> I'm suggesting it because in current version these informations are not separated

Why dou you need them to be separated? And if they would be separate, what should be done with it? I.e. what kind of front end output do you then expect?

**Comment by fritzmg** [comment]
Related https://github.com/contao/core-bundle/issues/1297

**Comment by jankout** [comment]
They should be separated because the information and the link to it are different ones than the current solution. 

I would like to output them everywhere I need them and where I can generely put images - text, gallery, news, events, picture etc. 

It would be nice to set **the additional caption informations** centrally. 

If the user would like to overwrite them somewhere it should be possible like now with the meta informations.

**Comment by leofeyer** [comment]
You can add as many additional fields as you like by adjusting the DCA configuration. Other than that, please see contao/core-bundle#1297.
