### ISSUE TITLE
Improve: Layout title and site structure search field

### ISSUE THREAD

**Issue by Anke** [contao/contao#1677]
On larger websites, esp. after extensive changes to the website, it may be necessary to check which page layouts are linked to which pages. This can be done by using the search field in the sites structure. 
But this search isn't working properly when the page layout titles contain characters like brackets e.g. while it doesn't seem to have any problems with spaces or hyphens, which may cause a user to delete a page layout that assumedly isn't in use anymore.

Would it be possible to only allow those characters in the layout title field that the search/filter in the site structure is able to handle? (It would be good to have a reliable way to check which page layouts can be deleted if they are not in use anymore.)

Examples:
Layout title: "2 columns (Events)" -> search in site structure willl not find any page using a layout by this name
Layout title: "2 columns - Events" -> will be found

**Comment by aschempp** [comment]
Dies it work if you search for `2 columns \(Events\)`?

**Comment by Anke** [comment]
No, the hashes don't work either.

Furthermore I just noticed that if a page layout has been set in the starting point of a website, then only this starting point shows up in the search results. But this page layout has also been allocated to several child pages within this website - however, they don't show in the search results.

Reproduce in the Contao demo: 

- Go to the site structure
- Select "page layout" in the search field and enter "2-columns"

Result: Only the website starting point will be listed, although other pages are also using layouts starting with "2-columns". The result will be the same if you allocate the the "2-columns [ default ]" layout to other pages before searching.
Searching for "news" lists the demo pages using the news layout, because all of them are child pages and the starting point is not using a news layout.

Funny thing that nobody has ever noticed this misbehavior, although the site structure search field is quite a powerful tool ...

**Comment by leofeyer** [comment]
I have just tried to reproduce the issue, but everything worked as expected on my system. I searched for both `(Events)` and `\[ default ]` (note that the opening bracket needs to be escaped due to the regex search) in the field "Page layout" and found the matching pages.

**Comment by Anke** [comment]
Well, it isn't working in the Contao demo.

I just set the layout "2 columns - [ default ]" for the page "Link elements". Then I searched for `2 columns` as well as for `\[ default ]`. Both search results only showed the root page "Contao Official Demo", not the page "Link elements".

(For my second test I left the site tree expanded before searching, which doesn't make a diffenernce.)

Edit: The search for page layout `column` (singular) shows:
Contao Official Demo (2 columns - [ default ])
- Home (1 column)
- About Contao (1 column)

The page "Link elements" is not listed. Well, but unintentionally I then filtered the node "Modules" and only then the pages "Events", "Event detail" and "Newsletter" were listed, so I double-checked the node "Content elements".

So I assume **you can only use the search for one node at a time**, is that so? No way to search the whole site structure at once?

**Comment by leofeyer** [comment]
Works for me in the online demo. 🤷‍♂️ 

<img width="798" alt="" src="https://user-images.githubusercontent.com/1192057/82022817-8be7c980-968d-11ea-8763-1975434bf15d.png">

**Comment by Anke** [comment]
Well, I'm not the youngest any more but wouldn't consider myself being senile - it's working für me, too, now. Until yesterday I didn't even get to see a plus or minus in front of a node. Weird.

Yet, in one of my sites I'm using the following page layouts:

![screenshot_layoutsearch_2](https://user-images.githubusercontent.com/1300920/82036119-c6a72d00-96a0-11ea-96cf-bab2faa1bd22.jpg)

Entering a partial string shows this result:

![screenshot_layoutsearch_3](https://user-images.githubusercontent.com/1300920/82036655-75e40400-96a1-11ea-9905-35bc53fea9b4.jpg)

Searching for "2-col-layout" shows the same result as above, while searching for "2-col-layout " (with a space added at the end) is finding more pages:

![screenshot_layoutsearch_4](https://user-images.githubusercontent.com/1300920/82037204-1b977300-96a2-11ea-8764-c49724064504.jpg)

I notice is that the "Home" page is listed almost at the bottom, so the sorting doesn't match the positions in the site structure. And the above found pages are in fact using the following layouts: 

![screenshot_layoutsearch_5](https://user-images.githubusercontent.com/1300920/82037927-1c7cd480-96a3-11ea-908d-43ec6e5934e8.jpg)

The page "Matchday Referee" e.g. has no layout assigned and is - like many other pages - using the site's main layout (Startpunkt).

(Contao 4.9.2., system maintenance was run before trying this)

**Comment by frontendschlampe** [comment]
Maybe our extension https://github.com/hofff/contao-layoutusage is something for you :-)

**Comment by Anke** [comment]
Thank you @frontendschlampe, I'll definitely try your extension! Yet, having a built-in possibility to check which layouts are in use, this function ought to show reliable results.

Edit:
Okaaay! Great extension, very practical!
