### ISSUE TITLE
GROUP BY in models not working anymore with MySQL 5.7

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1680]
**Affected version(s)**

Contao 4.4 and Contao 4.9

**Description**

When having MySQL 5.7+ installed with the new GROUP BY behavior, I get an error after running:

```
$abc = CalendarEventsModel::findBy(null, null, [
    'group' => 'title'
]);
```

The error is:

```
An exception occurred while executing 'SELECT tl_calendar_events.*, j1.`id` AS memberAuthor__id, j1.`tstamp` AS memberAuthor__tstamp, j1.`firstname` AS memberAuthor__firstname, j1.`lastname` AS memberAuthor__lastname, j1.`dateOfBirth` AS memberAuthor__dateOfBirth, j1.`gender` AS memberAuthor__gender, j1.`company` AS memberAuthor__company, j1.`street` AS memberAuthor__street, j1.`postal` AS memberAuthor__postal, j1.`city` AS memberAuthor__city, j1.`state` AS memberAuthor__state, j1.`country` AS memberAuthor__country, j1.`phone` AS memberAuthor__phone, j1.`mobile` AS memberAuthor__mobile, j1.`fax` AS memberAuthor__fax, j1.`email` AS memberAuthor__email, j1.`website` AS memberAuthor__website, j1.`language` AS memberAuthor__language, j1.`groups` AS memberAuthor__groups, j1.`login` AS memberAuthor__login, j1.`username` AS memberAuthor__username, j1.`password` AS memberAuthor__password, j1.`assignDir` AS memberAuthor__assignDir, j1.`homeDir` AS memberAuthor__homeDir, j1.`disable` AS memberAuthor__disable, j1.`start` AS memberAuthor__start, j1.`stop` AS memberAuthor__stop, j1.`dateAdded` AS memberAuthor__dateAdded, j1.`lastLogin` AS memberAuthor__lastLogin, j1.`currentLogin` AS memberAuthor__currentLogin, j1.`loginAttempts` AS memberAuthor__loginAttempts, j1.`locked` AS memberAuthor__locked, j1.`session` AS memberAuthor__session, j1.`secret` AS memberAuthor__secret, j1.`useTwoFactor` AS memberAuthor__useTwoFactor, j1.`backupCodes` AS memberAuthor__backupCodes, j1.`trustedTokenVersion` AS memberAuthor__trustedTokenVersion, j1.`newsletter` AS memberAuthor__newsletter FROM tl_calendar_events LEFT JOIN tl_member j1 ON tl_calendar_events.`memberAuthor`=j1.id GROUP BY title':

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'acme_corporate.tl_calendar_events.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

It seems that adding `id` to the GROUP BY statement in the case that `$options['group']` is set solves the issue:

```
// Group by
if (isset($arrOptions['group']))
{
	$strQuery .= " GROUP BY id, " . $arrOptions['group'];
}
```

Of course, id must be the private key which can differ from `id`.

Also I'm not sure at the moment, if the above solution works in each and every case. In my test case it worked very well though. And grouping with a unique field shouldn't make any difference, should it?

Thanks in advance for yur opinions!

Bye Defcon0

**Comment by fritzmg** [comment]
~~You need to specify the table:~~

Ah, I misunderstood the problem, nvm :)

**Comment by Defcon0** [comment]
Yes, just tried ;-) Didn't work ;-)

**Comment by ausi** [comment]
`GROUP BY id, title` is very different from `GROUP BY title`. What do you want to achieve with `'group' => 'title'`?

**Comment by Defcon0** [comment]
Yep, I also saw that. I want to achieve a grouping by title by the code ;-) Of course, it's a simplified sample code to illustrate the problem. The real world problem is to get option values out of a model set.

In mySQL 5.5 it was no problem. But now this breaks the "group" index in the model's options array.

**Comment by m-vo** [comment]
> In mySQL 5.5 it was no problem. But now this breaks the "group" index in the model's options array.

That has rather something to do with your sql mode now containing `ONLY_FULL_GROUP_BY` now. (See `SELECT @@sql_mode;`)

What do you expect `id` to be in a query like `SELECT id FROM table GROUP by column`?  It's arbitrary and that's why it's not allowed.  You need to either drop those columns from the projection or wrap them in a aggregation function (or something like `ANY_VALUE()` in extreme edge cases). Relying on those ambivalent columns in code is a almost always a bug. 

So I really don't get it - what's the intended output for those models? Random values? Grouping and a full set values (all columns / fully hydrated model) isn't a compatible concept.

**Comment by Defcon0** [comment]
Well, I don't compose the query in the first hand. The fields in the SELECT are composed by contao's QueryBuilder class taking into account the `relations` defined in the DCA.

I just do

```
$abc = CalendarEventsModel::findBy(null, null, [
    'group' => 'title'
]);
```

and this should work, don't you think?

I'm aware of the SQL mode having changed. But changing this mode away from the default one in a hosting environment will likely not be an option. You need admin rights for that to my knowledge.

Wrapping the fields in the SELECT clause in `AVY_VALUE()` will likely work (we've implemented that in another module already) but it must take place in the core (`QueryBuilder`). Also wrapping `tl_table.*` in `AVY_VALUE()` isn't possible to my knowledge and this is also added in `QueryBuilder`.

**Comment by m-vo** [comment]
I'm aware of the fact it's Contao building the query. I didn't want to sound as if you're doing this. :smiley: 

But what do you expect those model values to be when you add the 'group' option? Imo this option doesn't make any sense at all (without having control over the projection/select part).

**Comment by Defcon0** [comment]
I'm not quite sure if I agree ;-) Grouping is a useful feature. But in the model context it's a bit misleading I guess.

But the solution might be difficult because

1. We can't simply drop the option since devs might have used it in the past. (-> BC break)
2. Solving using ANY_VALUE() isn't possible with the current implementation because of `tl_table.*` added to the fields per default. We solved it in our bundles by adding every single field separately, i.e. `SELECT ANY_VALUE(tl_table.field1), ANY_VALUE(tl_table.field2), field3 FROM tl_table GROUP BY field3` instead of `SELECT tl_table.* FROM tl_table GROUP BY field3`

**Comment by m-vo** [comment]
We cannot use `ANY_VALUE()` because it doesn't work in MariaDB. 

Solutions I could think of (SQL) are something like a subquery with `LIMIT 1` on every field or some hack with `GROUP_CONCAT()` and selecting the first OR `MIN()`/`MAX()`. But: I wouldn't do those.

Alternatively the model's `find()` method could handle this case (partially hydrating, using some values of some entry?...). But still: Why do you need this? What's your use case?

Honestly, I feel this could just be added to the known limitations, deprecated and removed some day in the future. 

(Edit: Adjusting the query builder alone by only including the grouped fields in the `SELECT` clause doesn't fix the original issue.)

**Comment by Defcon0** [comment]
The use case is to retrieve all values of a field from entities of a certain table from the db with one query and no additional logic necessary.

I know I can achieve this afterwards, but this way it’s been very convenient. And changing all the implementations based on that isn’t joyful ;-)

**Comment by m-vo** [comment]
You mean you need the equivalent of `SELECT DISTINCT field FROM table`? Then you should imo simply use dbal and not abuse the models.

**Comment by Defcon0** [comment]
„Abuse“ the models with an option available by the core!?? Is there any documentation showing us devs what’s the ok usage for models and what’s „abuse“ already?

**Comment by m-vo** [comment]
"Abuse", because you aren't interested in any of the models values other than the one column that imo makes sense after grouping (because the models do not aggregate or group select anything). :smiley: 

But that's just my opinion. Let's see what others have to say.

**Comment by ausi** [comment]
I think adding the `group` option in 7e920d7ab4759af6d9ba877e7261372bea43be6a was a mistake. AFAIK this “feature” does not get used anywhere in the core.

I cannot think of a use case for this or how a “fix” for that should look like, so IMO we should deprecate it.

> „Abuse“ the models with an option available by the core!??

I think the “abuse” is done by the core here, not by you.

**Comment by Defcon0** [comment]
It means pain but I also would prefer removing that from the models. Models are (if I understood correctly) "only" wrappers for the database (ORM) with a 1:1 relation, i.e. one model object represents one db record. So having a grouped value breaks that principle imo.

I guess then the solution would be to deprecate the option.

But: If it's decided to remove the option, at least using a GROUP BY in the Database class must be possible. I can remember that relations are even in the db `Result`-instances. I'll have to check if using a GROUP BY in `Database` class is possible, but I suspect it is.

**Comment by bennyborn** [comment]
Because #1661 got closed I'd like to add, like in my OG issue, that this is not only a question of someone using the models with the "group" option but also that the core is currently broken (please see #1661 for further information) which should be a totally separate issue IMHO.

**Comment by m-vo** [comment]
>  Models are (if I understood correctly) "only" wrappers for the database (ORM) with a 1:1 relation, i.e. one model object represents one db record.

Yes (including the gray area of _new_ records, that are not yet persisted and do not have an id).

> at least using a GROUP BY in the Database class must be possible

The database class is independent of your query, so your free to execute whatever you want. If you need a more sophisticated query builder have a look into doctrine's.

**Comment by leofeyer** [comment]
> I think adding the `group` option in [7e920d7](https://github.com/contao/contao/commit/7e920d7ab4759af6d9ba877e7261372bea43be6a) was a mistake. 

@contao/developers Do you agree?

> I cannot think of a use case for this or how a “fix” for that should look like, so IMO we should deprecate it.

Even though the feature is working fine if the SQL mode does not include `ONLY_FULL_GROUP_BY`?

**Comment by ausi** [comment]
> > I cannot think of a use case for this or how a “fix” for that should look like, so IMO we should deprecate it.
> 
> Even though the feature is working fine if the SQL mode does not include `ONLY_FULL_GROUP_BY`?

What exactly means “is working fine” here? As the MySQL server is [*“free to choose any value from each group”*](https://dev.mysql.com/doc/refman/5.6/en/group-by-handling.html) only the value of the column by which the grouping is done can be relied upon. The other columns can have **any** value from the matching rows and (if I understood the MySQL manual correctly) they may not even refer to the same data base row.

**Comment by leofeyer** [comment]
Valid point.

**Comment by leofeyer** [comment]
Ok, so how to we fix this? Do we trigger a deprecation and still add the `GROUP BY` part to the query? Even though we know it is not working? Or do we remove the option altogether?

**Comment by ausi** [comment]
I’d deprecate it but still add the `GROUP BY` to keep the behaviour the same.

We could additionally try to “fix” the `GROUP BY` error by using optimizer hints like `SELECT /*+ SET_VAR(sql_mode=sys.list_drop(@@sql_mode, 'ONLY_FULL_GROUP_BY')) */ * FROM ...` but I don’t know if that’s necessary (if possible at all).

**Comment by leofeyer** [comment]
I don't think that's necessary.

**Comment by aschempp** [comment]
Deprecation for sure. Having a model built from GROUP BY is a big mistake. Do we exclude the result from the registry? Because it will most likely retrieve invalid data...
