### ISSUE TITLE
Contao v4.9 doesn't work with MySQL 8 by default

### ISSUE THREAD

**Issue by joseluisq** [contao/contao#1696]
**Affected version(s)**
Contao v4.9.2

**Stack used**
- MySQL v8.0.20 (Linux on x86_64)
- PHP-FPM v7.4
- Apache Server v2
- Docker 20.10.8

**Composer file**

```json
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0-or-later",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": ">=7.2",
        "contao/calendar-bundle": "^4.9",
        "contao/comments-bundle": "^4.9",
        "contao/conflicts": "@dev",
        "contao/faq-bundle": "^4.9",
        "contao/listing-bundle": "^4.9",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "^4.9",
        "contao/newsletter-bundle": "^4.9"
    },
    "conflict": {
        "contao-components/installer": "<1.3"
    },
    "extra": {
        "contao-component-dir": "assets",
        "symfony": {
            "require": "^4.4"
        }
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**Description**

During the testing of a fresh Contao installation we got few MySQL errors and only the first three tables were created:

```
tl_crawl_queue
tl_cron_job
tl_remember_me
tl_trusted_device
```

**Complete error log trace**

`
[2020-05-04 00:00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'CREATE TABLE tl_article (id INT UNSIGNED AUTO_INCREMENT NOT NULL, pid INT UNSIGNED DEFAULT 0 NOT NULL, sorting INT UNSIGNED DEFAULT 0 NOT NULL, tstamp INT UNSIGNED DEFAULT 0 NOT NULL, title VARCHAR(255) DEFAULT '' NOT NULL, alias VARCHAR(255) DEFAULT '' NOT NULL COLLATE `utf8mb4_bin`, author INT UNSIGNED DEFAULT 0 NOT NULL, inColumn VARCHAR(32) DEFAULT 'main' NOT NULL, keywords TEXT DEFAULT NULL, showTeaser CHAR(1) DEFAULT '' NOT NULL, teaserCssID VARCHAR(255) DEFAULT '' NOT NULL, teaser TEXT DEFAULT NULL, printable VARCHAR(255) DEFAULT '' NOT NULL, customTpl VARCHAR(64) DEFAULT '' NOT NULL, protected CHAR(1) DEFAULT '' NOT NULL, groups BLOB DEFAULT NULL, guests CHAR(1) DEFAULT '' NOT NULL, cssID VARCHAR(255) DEFAULT '' NOT NULL, published CHAR(1) DEFAULT '' NOT NULL, start VARCHAR(10) DEFAULT '' NOT NULL, stop VARCHAR(10) DEFAULT '' NOT NULL, INDEX alias (alias), INDEX pid_start_stop_published_sorting (pid, start, stop, published, sorting), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups BLOB DEFAULT NULL, guests CHAR(1) DEFAULT '' NOT NULL, cssID VARCHAR(255)' at line 1" at /var/www/share/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'CREATE TABLE tl_article (id INT UNSIGNED AUTO_INCREMENT NOT NULL, pid INT UNSIGNED DEFAULT 0 NOT NULL, sorting INT UNSIGNED DEFAULT 0 NOT NULL, tstamp INT UNSIGNED DEFAULT 0 NOT NULL, title VARCHAR(255) DEFAULT '' NOT NULL, alias VARCHAR(255) DEFAULT '' NOT NULL COLLATE `utf8mb4_bin`, author INT UNSIGNED DEFAULT 0 NOT NULL, inColumn VARCHAR(32) DEFAULT 'main' NOT NULL, keywords TEXT DEFAULT NULL, showTeaser CHAR(1) DEFAULT '' NOT NULL, teaserCssID VARCHAR(255) DEFAULT '' NOT NULL, teaser TEXT DEFAULT NULL, printable VARCHAR(255) DEFAULT '' NOT NULL, customTpl VARCHAR(64) DEFAULT '' NOT NULL, protected CHAR(1) DEFAULT '' NOT NULL, groups BLOB DEFAULT NULL, guests CHAR(1) DEFAULT '' NOT NULL, cssID VARCHAR(255) DEFAULT '' NOT NULL, published CHAR(1) DEFAULT '' NOT NULL, start VARCHAR(10) DEFAULT '' NOT NULL, stop VARCHAR(10) DEFAULT '' NOT NULL, INDEX alias (alias), INDEX pid_start_stop_published_sorting (pid, start, stop, published, sorting), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups BLOB DEFAULT NULL, guests CHAR(1) DEFAULT '' NOT NULL, cssID VARCHAR(255)' at line 1 at /var/www/share/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups BLOB DEFAULT NULL, guests CHAR(1) DEFAULT '' NOT NULL, cssID VARCHAR(255)' at line 1 at /var/www/share/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:83, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups BLOB DEFAULT NULL, guests CHAR(1) DEFAULT '' NOT NULL, cssID VARCHAR(255)' at line 1 at /var/www/share/project/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:78)"} []
`

**Environment variables used**
- APP_ENV: `prod`
- SECRET: `abcdef1230`
- TRUSTED_PROXIES: `127.0.0.1,REMOTE_ADDR`
- DATABASE_URL: `mysql://username:passwd@database:3306/dbname`

**Steps to reproduce the issue**

https://github.com/contao/contao/issues/1696#issuecomment-944373619

**Screenshots**

https://github.com/contao/contao/issues/1696#issuecomment-945426969

**Comment by fritzmg** [comment]
`groups` is a reserved keyword and needs to be quoted. However, Doctrine should have taken care of that, shouldn't it?

**Comment by joseluisq** [comment]
@fritzmg could that help https://github.com/concrete5/concrete5/pull/6753?

**Comment by dhaeb** [comment]
> `groups` is reserved keyword and needs to be quoted. However, Doctrine should have taken care of that, shouldn't it?

Yeah - I'm not an expert at doctrine but the whole SQL generation should be handled transparently by the ORM - including "escaping" of reserved keywords. Does Doctrine support MySQL 8? What config do we need to change there? Just point us to the right sources and I'll be happy :)

**Comment by fritzmg** [comment]
> Does Doctrine support MySQL 8?

Yes, since Version 2.8: https://github.com/doctrine/dbal/blob/2.8/lib/Doctrine/DBAL/Platforms/Keywords/MySQL80Keywords.php

**Comment by ausi** [comment]
Since version 2.8.0 doctrine/dbal should escape the `GROUPS` keyword for MySQL 8 correctly. Which version of `doctrine/dbal` is installed in your project? Maybe the MySQL version was not detected (or configured) correctly?

**Comment by fritzmg** [comment]
> Which version of `doctrine/dbal` is installed in your project? Maybe the MySQL version was not detected (or configured) correctly?

contao/core-bundle 4.9.2 requires doctrine/dbal ^2.10 - so anything lower than `2.10` is not possible anyway. Likely the MySQL version was not detected by Doctrine then.

**Comment by joseluisq** [comment]
> Since version 2.8.0 doctrine/dbal should escape the `GROUPS` keyword for MySQL 8 correctly. Which version of `doctrine/dbal` is installed in your project? Maybe the MySQL version was not detected (or configured) correctly?

I really don't know, check out above our composer.json file used.

**Comment by fritzmg** [comment]
> I really don't know

You can check with

```
composer show doctrine/dbal
```

However, as I pointed out, if you are really using Contao 4.9, then anything lower than 2.10 is not possible anyway.

**Comment by joseluisq** [comment]
```
~> composer show doctrine/dbal
name     : doctrine/dbal
descrip. : Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
keywords : abstraction, database, db2, dbal, mariadb, mssql, mysql, oci8, oracle, pdo, pgsql, postgresql, queryobject, sasql, sql, sqlanywhere, sqlite, sqlserver, sqlsrv
versions : * 2.10.2
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://www.doctrine-project.org/projects/dbal.html
source   : [git] https://github.com/doctrine/dbal.git aab745e7b6b2de3b47019da81e7225e14dcfdac8
dist     : [zip] https://api.github.com/repos/doctrine/dbal/zipball/aab745e7b6b2de3b47019da81e7225e14dcfdac8 aab745e7b6b2de3b47019da81e7225e14dcfdac8
path     : /var/www/share/project/vendor/doctrine/dbal
names    : doctrine/dba
```

**Comment by fritzmg** [comment]
How exactly did you install Contao on the aforementioned environment? Please describe every step you took, including any special configurations or settings you might have done prior on your environment.

**Comment by fritzmg** [comment]
As a workaround you could add the following:

```yml
# config/config.yml
doctrine:
    dbal:
        connections:
            default:
                server_version: '%env(DATABASE_SERVER_VERSION)%'
```
```
# .env.local
DATABASE_SERVER_VERSION=8.0.20
```

_Note:_ in order for the `.env.local` file to work, you need to also add an `.env` file, if not already present. See also https://docs.contao.org/dev/getting-started/starting-development/#application-configuration. Alternatively you can also use real environment variables on your server environment. May be your environment actually already has such an environment variable.

Keep in mind that you would need to change the `DATABASE_SERVER_VERSION` environment variable whenever the database server version changes.

**Comment by joseluisq** [comment]
Your workaround doesn't work. I think because we are using `DATABASE_URL` system env, no config files.

Do you know how we can pass `server_version` via `DATABASE_URL` env? I can not find info about on Symfony docs. Everything is config-like files based.

**Comment by fritzmg** [comment]
That should be no problem. Using `url` for the database connection would not override `server_version`. I assume you cleared and rebuilt the Symfony Application Cache after making those changes?

**Comment by joseluisq** [comment]
We are passing `DATABASE_SERVER_VERSION` as system env, the `config/config.yml` is also in place with the workaround, but It simply doesn't work. 
It seems like the `DATABASE_SERVER_VERSION` env is not taken into account.

Additionally we have skipped the `.env.local` file because is useless here.

I suggest that you reproduce this as we did using the stack above.

**Comment by leofeyer** [comment]
I have installed MySQL 8.0.19 on my system to reproduce this, however, I could not. The screenshot shows that the `groups` column is quoted correctly in the install tool:

<img width="534" alt="" src="https://user-images.githubusercontent.com/1192057/80975634-a36bba80-8e22-11ea-867a-d6d50fa3e03c.png">

The database update completed without errors.

**Comment by joseluisq** [comment]
@leofeyer  Can you share your set up and let me try it out again.

**Comment by leofeyer** [comment]
Sure. I am on macOS 10.15.4 and I have installed PHP 7.4.5 and MySQL 8.0.19 via Homebrew. I am using the [Symfony Local Web Server](https://symfony.com/doc/current/setup/symfony_server.html) v4.14.3 and I have tested the current `4.9` branch of Contao (commit 4ec9a7351629de97b10361bdc398df1eb670df36).

**Comment by joseluisq** [comment]
Have you tried it out the @fritzmg workaround together with system env variables?
I'm also using `APP_ENV`, `TRUSTED_PROXIES`, `DATABASE_URL`, `DATABASE_SERVER_VERSION`.

**Comment by leofeyer** [comment]
You should not use `DATABASE_SERVER_VERSION`. Contao will autodetect the database platform and version.

**Comment by joseluisq** [comment]
Ok, let me try it out once again. Just FYI I'm not using any config file.

**Comment by joseluisq** [comment]
When I use `APP_ENV=prod` is not quoting `groups` but it does it with `APP_ENV=dev`. 
Maybe cache related issue? How can I clean the Contao cache? Because I'm using [this](https://symfony.com/doc/3.4/console/usage.html) but then I get table something not found (500) using `APP_ENV=prod`.

**Comment by leofeyer** [comment]
You should use `vendor/bin/contao-console cache:clear -e prod` instead.

**Comment by leofeyer** [comment]
@joseluisq Were you able to solve your issue? Then please close this issue.

**Comment by joseluisq** [comment]
@leofeyer sorry for the delay.

Unfortunately we had no time to try to reproduce this along with your indications.
The team decided to go for the latest Contao `v4.9.3` and MySQL `v5.7` on production.

I'm going to close this issue for now.
If we found time to reproduce the environment again we let you know here.

**Comment by joseluisq** [comment]
Taking up above issue again:

> When I use `APP_ENV=prod` is not quoting `groups` but it does it with `APP_ENV=dev`.
> Maybe cache related issue? How can I clean the Contao cache? Because I'm using [this](https://symfony.com/doc/3.4/console/usage.html) but then I get table something not found (500) using `APP_ENV=prod`.

In order to reproduce this, just use a simple Dockerfile similar to below one:

```Dockerfile
# the-contao-image

# Use whatever image you prefer
FROM joseluisq/php-fpm:7.4
# composer.json used here is the same as above
COPY composer.json .
RUN composer install --no-dev --optimize-autoloader --no-ansi --no-interaction
RUN chown -R www-data:www-data . && chmod -R g+s .
```

Let's use a docker-compose file with php, apache and database for testing.

```yml
version: "3.3"
services:
  php-fpm:
    image: the-contao-image
    environment:
      - "APP_ENV=prod"
      - "SECRET=abcdef1230"
      - "TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR"
      - "DATABASE_URL=mysql://username:passwd@database:3306/dbname"

  # other setup necessary like database, apache, etc ...
```

Then navigate to `http://localhost/contao/install`, the page loads and shows the whole SQL script to execute but `groups` is unquoted.

The problem is not with Apache or the database (MySQL 8). The issue is that Contao is not quoting SQL reserved words when `APP_ENV=prod` is used.

**Comment by ausi** [comment]
The container gets probably built in the `RUN composer install` step and the server version can not be determined there because there is no database yet.

A config like this should fix your issue:

```yaml
# config/config.yml
doctrine:
    dbal:
        connections:
            default:
                server_version: '8.0.20'
```

The underlying issue should get fixed with #3345 I think.

**Comment by joseluisq** [comment]
@ausi Did you test it too?
Looks like doesn't work using `APP_ENV=prod` but it does with `APP_ENV=dev`

Here the some screenshots without success for now

<img src="https://user-images.githubusercontent.com/1700322/137684184-eabf4153-489e-4e8a-972e-26455ae72e7c.png" width="400">

<img src="https://user-images.githubusercontent.com/1700322/137684473-e0b03fc0-df37-4a53-a84b-df38e737b06f.png" width="400">

**Comment by joseluisq** [comment]
BTW I refreshed the issue's title and description.

**Comment by fritzmg** [comment]
> @ausi Did you test it too?
> Looks like doesn't work using `APP_ENV=prod` but it does with `APP_ENV=dev`

Did you run `composer install` or `cache:clear --no-warmup` and `cache:warmup` after adding the `server_version`?

**Comment by joseluisq** [comment]
> Did you run `composer install` or `cache:clear --no-warmup` and `cache:warmup` after adding the `server_version`?

No, just this `composer install --no-dev --optimize-autoloader --no-ansi --no-interaction`. Check the comment above. https://github.com/contao/contao/issues/1696#issuecomment-944373619

**Comment by fritzmg** [comment]
> Check the comment above. [#1696 (comment)](https://github.com/contao/contao/issues/1696#issuecomment-944373619)

That comment only regards your initial setup. I just wanted to confirm that you rebuilt the application cache after changing your `config/config.yaml`.

**Comment by joseluisq** [comment]
Do I need to rebuild the cache after the install? Because I copy the config file suggested first and then I do the compose install.

**Comment by joseluisq** [comment]
Is this the command `php -q bin/console cache:clear --env=prod --no-warmup` to run after the install ?

**Comment by fritzmg** [comment]
> Because I copy the config file suggested first and then I do the compose install.

Then it should be fine.

**Comment by fritzmg** [comment]
> Is this the command `php -q bin/console cache:clear --env=prod --no-warmup` to run after the install ?

Oh, are you not using the Contao Managed Edition anymore?

**Comment by joseluisq** [comment]
> Oh, are you not using the Contao Managed Edition anymore?

I'm using the managed one.

--

After the `vendor/bin/contao-console cache:clear --env=prod --no-warmup` I got this

```
NOTICE: PHP message: PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Cannot rename "/tmp/bundles.mapcNEAec" to "/var/www/html/var/cache/prod/bundles.map". in /var/www/html/vendor/symfony/filesystem/Filesystem.php:290
contao-cms-php-fpm-1   | Stack trace:
contao-cms-php-fpm-1   | #0 /var/www/html/vendor/symfony/filesystem/Filesystem.php(692): Symfony\Component\Filesystem\Filesystem->rename('/tmp/bundles.ma...', '/var/www/html/v...', true)
contao-cms-php-fpm-1   | #1 /var/www/html/vendor/contao/manager-plugin/src/Bundle/BundleLoader.php(106): Symfony\Component\Filesystem\Filesystem->dumpFile('/var/www/html/v...', '<?php return ar...')
contao-cms-php-fpm-1   | #2 /var/www/html/vendor/contao/manager-plugin/src/Bundle/BundleLoader.php(79): Contao\ManagerPlugin\Bundle\BundleLoader->loadFromPlugins(false, '/var/www/html/v...')
contao-cms-php-fpm-1   | #3 /var/www/html/vendor/contao/manager-plugin/src/Bundle/BundleLoader.php(63): Contao\ManagerPlugin\Bundle\BundleLoader->loadFromCache(false, '/var/www/html/v...')
contao-cms-php-fpm-1   | #4 /var/www/html/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php(367): Contao\ManagerPlugin\Bundle\BundleLoader->getBundleC in /var/www/html/vendor/symfony/filesystem/Filesystem.php on line 290
```

**Comment by joseluisq** [comment]
What are the commands to execute after the composer install? Can you share pelase?

Actually I do the following in the container:

```Dockerfile
FROM joseluisq/php-fpm:7.4
ENV APP_ENV=prod
# composer.json used here is the same as above
COPY composer.json .
COPY docker/config/config.yml config/config.yml
RUN composer install --no-dev --optimize-autoloader --no-ansi --no-interaction
RUN vendor/bin/contao-console cache:clear --env=prod --no-warmup
RUN chown -R www-data:www-data . && chmod -R g+s .
```

I think I'm missing something.

**Comment by joseluisq** [comment]
Or do I need to do composer install using `APP_ENV=prod` ?

**Comment by fritzmg** [comment]
> What are the commands to execute after the composer install? Can you share please?

The necessary commands are already executed by the [post install/post update script of the Contao Manged Edition](https://github.com/contao/managed-edition/blob/c66640744653e2577a076dfd680650cd9262af1d/composer.json#L25-L30). [These are the commands](https://github.com/contao/contao/blob/89d51f466144835e6bb6775c789facc77e750ca7/manager-bundle/src/Command/ContaoSetupCommand.php#L80-L88) that the `contao:setup` command (which is executed by `vendor/bin/contao-setup`) executes. But in theory you should not have to do anything yourself.

**Comment by joseluisq** [comment]
But why this below doesn't work? even with and without `vendor/bin/contao-console cache:clear --env=prod --no-warmup` one.

> Actually I do the following in the container:
> 
> ```dockerfile
> FROM joseluisq/php-fpm:7.4
> ENV APP_ENV=prod
> # composer.json used here is the same as above
> COPY composer.json .
> COPY docker/config/config.yml config/config.yml
> RUN composer install --no-dev --optimize-autoloader --no-ansi --no-interaction
> RUN vendor/bin/contao-console cache:clear --env=prod --no-warmup
> RUN chown -R www-data:www-data . && chmod -R g+s .
> ```

The `composer.json` is the same as above and the `config/config.yml` file is copied with the content suggested too.
Note that I also added `ENV APP_ENV=prod` at the beginning.

It would be great if you can also test this by your own.

What is curious for me is that when I set `ENV APP_ENV=dev` then it is working.

**Comment by ausi** [comment]
I think this might still be related to #3345

Could you please check what the following command prints?

```
vendor/bin/contao-console debug:config doctrine dbal.connections.default.server_version --env=prod
```

**Comment by joseluisq** [comment]
> I think this might still be related to #3345

Ok, then it means that #1696 can be considered as an issue right?

> Could you please check what the following command prints?
> 
> ```
> vendor/bin/contao-console debug:config doctrine dbal.connections.default.server_version --env=prod
> ```

<img src="https://user-images.githubusercontent.com/1700322/137702058-4b641b24-ffb6-4603-9cf0-e60041e6f4e7.png" width="400">

It uses the [suggested](https://github.com/contao/contao/issues/1696#issuecomment-944393601) `config/config.yml` .

**Comment by joseluisq** [comment]
Is the `vendor/bin/contao-console cache:clear --env=prod --no-warmup` irrelevant here? or do we still need it?

**Comment by ausi** [comment]
> It uses the [suggested](https://github.com/contao/contao/issues/1696#issuecomment-944393601) `config/config.yml` .

That is weird. Can you send me your docker, docker-compose, composer and config files in a zip archive (to martin@contao.org) so that I can try to reproduce it?

**Comment by joseluisq** [comment]
> That is weird. Can you send me your docker, docker-compose, composer and config files in a zip archive (to [martin@contao.org](mailto:martin@contao.org)) so that I can try to reproduce it?

Sure, but even better I can create a testing Github repo so you can reproduce it easily.
I will let you know during the day.

**Comment by joseluisq** [comment]
@ausi here the repo https://github.com/joseluisq/contao49-mysql8-issue
If you need help just let me know.

**Comment by ausi** [comment]
https://github.com/joseluisq/contao49-mysql8-issue/pull/1

**Comment by joseluisq** [comment]
> joseluisq/contao49-mysql8-issue#1

The issue was addressed specifying the version number on the database url string.

`DATABASE_URL=mysql://contao:contao@database:3306/contao?serverVersion=8.0.20`

Thanks @ausi for the workaround.

**Comment by ausi** [comment]
I was able to confirm that #3345 is causing the issue in this case. If you run the following command in your php-fpm container you can see that `serverVersion` is set to `5.5` there.

```sh
cat var/cache/prod/ContainerS7aEaaH/appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php | grep serverVersion
# output: return $this->services['doctrine.dbal.default_connection'] = …, 'serverVersion' => '5.5',…
```

Thank you @joseluisq for the perfect reproduction example!

To verify that this exact case works properly after fixing #3345 I’d like to keep this open until the fix is verified with this reproduction case.

**Comment by ausi** [comment]
@joseluisq can you verify if the fix from https://github.com/contao/contao/pull/3623 works for your use case?

**Comment by joseluisq** [comment]
@ausi sure, but how should I proceed? Should I use some dev 4.9 branch or something? and how can I do it via the `composer.json`?

**Comment by ausi** [comment]
@joseluisq probably best to wait until #3623 was merged. After that you can use something like this in your composer.json:

```json
"contao/core-bundle": "4.9.x-dev as 4.9.22",
```
