### ISSUE TITLE
"Weisse/Leere Seite" Installtool / Benutzergruppe

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#1697]
**Affected version(s)**
Contao 4.9.2

**Description**
Nach update auf Symfony 4.4.8 funktioniert das Install-Tool und das Anlegen von Benutzergruppen nicht mehr! Es kommt nur eine weisse/leere Seite! Kein Fehlereintrag unter /var/logs. Debugmodus bringt auch nichts! Hier wird auch nur die weisse Seite angezeigt. Manuelles löschen des Caches zeigt die Seite einmalig an bis der Cache im Hintergrund wieder aufgebaut ist und danach gleich wieder eine weisse Seite!
**Update:** Die Login-Maske fürs Installtool kommt noch und nach erfolgreichem Login dann die leere/weisse Seite!

**Historie**
Contao war bereits in der aktuellen Version 4.9.2 installiert und es hat alles wunderbar funktioniert. Heute über den Contao-Manager die Pakete upgedated. Hier wurde vor allem symfony auf 4.4.8 upgedated! Es waren auch noch 2-3 andere Pakete dabei welche ich aber nicht mehr weiss (kann man das nachschauen?). Nach Update kam es zu obigem Fehler! Es muss irgendwie mit den Cache zusammenhängen!

**Comment by aschempp** [comment]
Siehst du eine Fehlermeldung in den Log-Dateien (`var/logs`) oder deinem Server-Log (Apache/Nginx)?

**Comment by xprojects-de** [comment]
Hallo Andreas,
ich bin ein Schritt weiter. Es scheint das "Notification Center" in der aktuellen Version 1.5 zu sein oder halt eine Abhängigkeit davon. Entferne ich das Module ist alles gut! Füge ich es wieder hinzu dann ist der Fehler wieder da! Konnte das auf mehreren Seiten verifizieren!

Sorry, dann ist der Issue wohl im falschen Repo! Gerne schliessen wenn nötig!

@aschempp 
Soll ich beim Notification-Center ein extra Ticket aufmachen?

Danke für die schnelle Rückmeldung!

**Comment by aschempp** [comment]
then this is a duplicate of https://github.com/contao/contao/issues/962 😆

**Comment by xprojects-de** [comment]
Top danke!
