### ISSUE TITLE
Internal CSS not loading after update from 3.5 to 4.4

### ISSUE THREAD

**Issue by k-webdesign** [contao/contao#170]
**Affected version(s)**
Tested with 4.4.x

**Description**  
When I update an 3.5 installation to 4.4 that contains internal CSS files (e.g. when using a theme), the CSS won't be loaded in the frontend. I need to go into every single internal CSS file and edit any element (just click "edit" and save without changes). 

**How to reproduce**  
Update an Contao 3.5 with internal CSS and check the frontend.

**Comment by leofeyer** [comment]
What about "System" -> "Maintenance" -> "Purge the script cache"?

**Comment by Teetrinker** [comment]
> What about "System" -> "Maintenance" -> "Purge the script cache"?

Doesn't resolve the problem. (and shouldn't be necessary, as the other scripts are automatically in the output)

**Comment by leofeyer** [comment]
That's strange, because the help text says

> Removes the automatically generated .css and .js files, recreates the internal style sheets and then purges the page cache.

and that is exactly what the `Automator::purgeScriptCache()` method does. Are there any _Generated style sheet…_ entries in the system log?
