### ISSUE TITLE
Contao 4.9.2: News -> target = external URL -> 1 in frontend

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1707]
Contao 4.9.2

News-Bundle

Target = external URL
![grafik](https://user-images.githubusercontent.com/1645099/81232379-188ee980-8ff5-11ea-9e00-fd8c44ceceb2.png)

creates a "1" in the frontend.
![grafik](https://user-images.githubusercontent.com/1645099/81232335-feeda200-8ff4-11ea-8cb2-c9829d6e0275.png)

event_list.html5: $this->details 
it echos a bool(1)
![grafik](https://user-images.githubusercontent.com/1645099/81232430-32c8c780-8ff5-11ea-8f3a-156ed362e4e5.png)

because of ModuleEventReader.php Line 231
![grafik](https://user-images.githubusercontent.com/1645099/81232556-673c8380-8ff5-11ea-9df4-a8adc124fc97.png)

This "1" I do not expect.

**Comment by contaoacademy** [comment]
Same for calender. See https://community.contao.org/de/showthread.php?76873-Kalender-Liste-zeigt-statt-Details-nur-eine-quot-1-quot&p=519011#post519011
