### ISSUE TITLE
News Modul und breitere Nutzbarkeit

### ISSUE THREAD

**Issue by Olli** [contao/contao#1709]
Hi,
ich habe aktuell das Newsmodul "missbraucht" für Content der eher eine auflistbaren Charakter hat (z.B. eine Projektübersicht mit lauter durchgeführten Projekten und deren Details). Das Newsmodul ist in seiner Art soweit o.k. aber es kann eigentlich viel viel mehr als "nur" als Blog zu dienen.
Ich sehe das Newsmodul eher als Listcontent Modul. Es fehlt noch die Möglichkeit, den Inhalt frei wählbar zu sortieren. 
Ansonsten kann man es aber für ein immer wiederkehrendes Contentschema nutzen (Teaser, Teaserbild, frei definierter Content). Dafür sind mMn. Artikel in Seiten ungeeignet (auch schon wegen dem fehlenden Teaserbild) weil alles schnell sehr unübersichtlich wird wenn eine Seite 10 oder 20 Artikel beinhaltet. 
Ich kann mir das Anwendungen des Newsmoduls zum Beispiel neben "durchgeführten Projekten" auch als Praktikumsplatzübersicht, Auflistung + Details von Firmenstandorten etc vorstellen - also Content, der zusammengefasst sich immer irgendwie gleicht und irgendwie in eine Liste passt (aber nicht News oder Blogartikel ist)

Die angeregte Änderung betrifft:
- freie Sortierbarkeit der Content-Artikel/Newsdinger (wie auch immer man die nennt)
- Umbenennung weg von "Nachrichten"/"News" hin zu einem Namen, der auf die Multi-Purpose Möglichkeiten des Moduls Gewicht legt
- vielleicht auch eine Shortcutlink so dass ein Redakteur im Artikelmenu direkt in die damit verbundene Seitenlistung (also in das entsprechende Nachrichtenarchiv) springen kann und somit in der Bedienung auch eine engere Verknüpfung  entsteht.

Mir ist klar, dass so eine Änderung ziemlich tief in Contao eingreift aber ich denke, dass man dadurch einen breiteren Einsatz des doch mächtigen Modules erreichen kann.

Ich bin mir nicht sicher aber ist ungefähr verständlich über welche Idee ich etwas diskutieren möchte?

**Comment by patrickjDE** [comment]
Das News-Modul lässt sich gut für viele Zwecke verwenden, aber dabei ist es in meinen Augen immer nur eine Behelfslösung, wenn die Ansprüche an die Auflistung der gewünschten Inhalte gering sind, oder das Budet keine dedizierte Lösung erlaubt.

Sobald es um Filter- oder Suchfunktionen geht, Metadaten benötigt werden, o.Ä. kommt man um Anpassungen am Modul oder direkt ein eigenes Modul kaum herum.

Von daher sehe ich nicht den großen Nutzen - als Behelfslösung kann man weiterhin einfach das Newsmodul wie es ist verwenden, die eigene Sortierung lässt sich über das Datum abbilden.

Falls allgemein der Bedarf doch höher eingeschätzt wird würde ich auf jeden Fall dazu tendieren, das ganze als neues Modul zu realisieren, statt das Newsmodul anzupassen.

**Comment by asaage** [comment]
Hab das News-Modul auch schon oft "missbraucht".
Ich würd' aber eher an den Artikeln ansetzen wollen (dort zum Teaser eine Bilddatei ergänzen u. ggf. weitere Metadaten) und das Teaser-Element verbessern (https://github.com/contao/core-bundle/issues/1417).
https://github.com/terminal42/contao-node bietet aber auch ein paar gute Lösungsansätze zu der Thematik.

**Comment by Olli** [comment]
@asaage das habe ich auch schon überlegt. Nur wenn du 10 Artikel hast (oder ich hatte mal jemand der hat da irgendwo 40 oder 50 rein gedonnert) fängt das an, sehhhhr lästig zu werden. Die Bedienung leidet mMn massiv. Wenn dann sollten Artikel komplett den Teaser verlieren.

@patrickjDE Warum sollte man komplett was neues realisieren wenn sehr viele Funktionen von dem Newsmodul schon abgedeckt werden. Gerade die Sortierung, wie du sie angeregt hast ist nur Nerds zumutbar - das ist einem Redakteur nicht vermittelbar. Auch die Implementierung der freien Sortierung ist eher einfach.
Es geht mir im Grunde darum, das Newsmodul soweit umzuändern, dass all die "Behelfslösungen" aus ihrem Behelfsstatus raus kommen und man sagen kann "Genau dafür ist dieses Modul da".

**Comment by patrickjDE** [comment]
> Warum sollte man komplett was neues realisieren wenn sehr viele Funktionen von dem Newsmodul schon abgedeckt werden.

Vor allem 2 Gründe: Rückwärtskompatibilität & konsistente Benennung. Dass es am Ende ein neues Modul wird heißt ja nicht, dass man das Newsmodul nicht als Grundlage für die Entwicklung nehmen kann.

**Comment by fkaminski** [comment]
Für Kategorien o. Tags existieren ja Erweiterungen. Schön wäre dies evtl. dennoch im Core - 
Evtl. mit entsprechenden Frontend Filter Möglichkeiten in den Listen Darstellungen (o. dies zumindest anhand von CSS-Klassen ermöglichen).

**Comment by aschempp** [comment]
Es gibt diverse kommerzielle und freie Erweiterungen für Datenverwaltung und Auflistung. Das News-Modul kann dafür missbraucht werden - genau wie ich mit Hammer und Meissel ein Haus einreissen kann, es ist halt nicht so praktisch wie wenn ich einen Bagger nutze 🤷‍♂️

**Comment by fritzmg** [comment]
Wir benutzen das Nachrichtenmodul auch sehr oft für allgemeine, dynamische Inhalte. Eine Umbenennung sehe ich _nicht_ notwendig, denn das lässt sich ja in Contao sehr einfach pro Applikation machen.

Dem News Modul sind auch schon in der Vergangenheit Features hinzugefügt worden, die diese Art der Benutzung noch besser gestaltet - bspw. durch so einfache Dinge wie mehr Sortieroptionen. Die freie Sortierbarkeit sehe ich als eines der nächsten Features dafür an. Macht ja durchaus auch für Nachrichten Sinn, wenn diese auf einer Seite in einer vom Redakteur/Layouter/Designer gewünschten Reihenfolge ausgegeben werden sollen, anstatt strikt nach Datum oder Alphabetisch.

Also 👍 für custom sorting, 👎 zum Rest ;)

**Comment by Olli** [comment]
Das Problem bei Erweiterungen ist, dass die mal gehen, mal nicht gehen, es gibt Unsicherheiten etc. 
Ich bin jemand, der weitgehend versucht Projekte nur mit den Core Contao umzusetzen - man kann sicher mit Modulen alles machen aber oft nerven einfach alle Abhänigkeiten (da kann ich ja gleich Wordpress nehmen ;-)

Als Feature könnte ich mir noch vorstellen, dass man per Klick ein Archiv in die Navigationsleiste mit übernommen werden kann. 
@fritzmg klar kann man das übersetzen - das habe ich auch gemacht aber eine komplette Umbenennung würde dem Modul einfach eine umfangreicheren Einsatzzweck attestieren. So würden zum Beispiel auch Neubenutzer eher auf die Idee kommen, das nicht nur für News zu nutzen.

**Comment by math-GH** [comment]
Was spricht gegen die Nutzung von https://now.metamodel.me/ ?

Inhalte zu verwalten ist eh fast immer ein sehr individuelles Ding. Dafür sollten wir nicht das News-Modul umbiegen.

**Comment by Olli** [comment]
@mathContao die wesentlich längere Aufsetzzeit, zusätzliche Komplexität im Code, einige Bugs die nerven und überhaupt Metamodel ist zwar toll aber ich versuche diesen Koloss zu vermeiden wenn es geht - das fühlt sich leider alles ziemlich unagil und schwerfällig an.

Es geht auch nicht so sehr ums Umbiegen sondern darum, dass das Newsmodul ohnehin schon für viele Sachen genutzt wird wofür es (vom Namen her) nicht gedacht ist. Da könnte man es eigentlich gleich umwidmen und somit dem geneigten Entwickler signalisieren "Damit kannst du mehr machen als nur deine 3 Newsarchive zu verwalten". 
Vielleicht wäre im Forum eine Umfrage interessant was die Nutzer alles mit dem Newsmodul machen - keine Ahnung ob das was bringt.

**Comment by Defcon0** [comment]
@Olli Genau aus diesem Grund haben wir damals das [contao-list-bundle](https://github.com/heimrichhannot/contao-list-bundle) sowie das [contao-reader-bundle](https://github.com/heimrichhannot/contao-reader-bundle).

Dort kann man beliebige Entitäten als Liste darstellen mit allen gewünschten Funktionen (Sortierung, Filterung, Paginierung, automatische Formatierung spezieller Felder (Datum, Bild, ...), TWIG-Support, ...). Auf der Detailseite hat man dann analog ein Modul aus dem Reader-Bundle. Dort können analog beliebige Entitäten dargestellt werden.

Es gibt für beide Module auch eine Anbindung an DC_Multilingual für mehrsprachige Projekte.

Das ganze ist sicherlich nicht optimal (aber welche Erweiterung ist das schon), aber wir haben die Module nun schon in sehr vielen Projekten erfolgreich eingesetzt.

Du kannst dort auch tl_news anzeigen. Theoretisch kannst du dir aber auch deine eigene Entität bauen und diese dort ausgeben.

**Comment by math-GH** [comment]
weitere Gespräche könnten sicher auch gut im Forum geführt werden ;)
