### ISSUE TITLE
Symlink-Service fehlerhaft

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#171]
**Affected version(s)**
Contao 4.6.7 - Managed Edition

**Description**  
Fehler beim Aufbau der Symlinks im Backend unter Systemwartung. Fehlermeldung: 

> The "contao.command.symlinks" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**How to reproduce**  
https://community.contao.org/de/showthread.php?72491-contao-command-symlinks-fehlt-oder-kaputt&p=486324

**Comment by xchs** [comment]
Already fixed. See https://github.com/contao/contao/issues/153
