### ISSUE TITLE
Contao 4.9.2: Contao-Vorschau nach dem Schließen wieder anzeigen

### ISSUE THREAD

**Issue by minstyle** [contao/contao#1710]
**Affected version(s)**

Contao 4.9.2

**Description**

Klickt man im Frontend von Contao 4.9 in der Contao-Vorschau (URI beinhaltet preview.php) auf das X-Icon wird die Leiste entsprechend geschlossen/ausgeblendet.

Wie kann man die Leiste wieder über das Backend einblenden ohne den Browser Cache leeren zu müssen?

**Comment by Toflar** [comment]
Die ist immer da wenn `preview.php` in der URL steht?

**Comment by minstyle** [comment]
Nein, nicht wenn der Balken über das X-Icon geschlossen wurde. Danach lässt sich die Vorschau nicht mehr aktivieren bzw. der Balken wird nicht mehr angezeigt. 

Unter demo.contao.org ist dieses Phänomen auch zu sehen.

**Comment by fritzmg** [comment]
Yes, currently there does not seem to be a way to bring the toolbar back once closed. But I think the :x: is supposed to stay anyway, isn't it? Like Symfony's toolbar. So the bug is actually, that the :x: vanishes together with the toolbar.

**Comment by rabauss** [comment]
Unfortunately, with some themes the ❌ is no longer visible because of to low `z-index`
For example, for the rocksolid oneo theme I added the following css:
```
// custom.css
.cto-toolbar__open {
    z-index: 6;
}
```

**Comment by fritzmg** [comment]
That's a different issue though.

**Comment by ausi** [comment]
I was not able to reproduce that on demo.contao.org. I think @rabauss is right that this is a CSS z-index issue.

![toolbar](https://user-images.githubusercontent.com/367169/81378312-5f6d0400-9107-11ea-84e6-f28e2ca53dac.gif)

**Comment by leofeyer** [comment]
See #1623.

**Comment by fiedsch** [comment]
> @ausi 
> I was not able to reproduce that on demo.contao.org. 

You can if you make your browser window narrow enough. Then the `#header` will be above the `.cto-toolbar`

**Comment by fritzmg** [comment]
@ausi I tested on a local installation where no CSS is applied. However, I was not able to reproduce it today either 😕 . I did notice some CSS issues, though. The toolbar button is missing a `top: 0` and the toolbar itself is missing a `left: 0`. Also the button does not have the same height as the toolbar, which I find odd - but may be that's a personal preference ;). I'll make a PR with some suggestions.

**Comment by minstyle** [comment]
Bitte exemplarisch auch mal mobil unter demo.contao.org testen (Portraitmodus, iPhone 11, Safari). Das Contao-Icon zum Öffnen der Vorschau im Frontend ist nicht zu sehen und verbirgt sich hinter dem Header. 

[Video mit iOS aufgenommen](https://www.dropbox.com/s/9xbunpgjc20exax/Video%2008.05.20%2C%2010%2024%2016.mov?dl=0)

**Comment by fritzmg** [comment]
> Bitte exemplarisch auch mal mobil unter demo.contao.org testen (Portraitmodus, iPhone 11, Safari). Das Contao-Icon zum Öffnen der Vorschau im Frontend ist nicht zu sehen und verbirgt sich hinter dem Header.

» https://github.com/contao/contao/issues/1710#issuecomment-625676552
