### ISSUE TITLE
News/Events: comments: security question now shown

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1718]
**Affected version(s)**

Contao 4.9.2

**Description**
In the comment section of News/Events there is no security question.

![grafik](https://user-images.githubusercontent.com/1645099/81447999-efe62b80-917d-11ea-9f2d-33ab4d3444a0.png)

The checbox is disabled.
![grafik](https://user-images.githubusercontent.com/1645099/81447983-e5c42d00-917d-11ea-909a-82423de10719.png)

**Comment by asaage** [comment]
It is just set to **display:none**.
That is the normal behaviour since a honepot was added and also applies to other forms with security questions.
![image](https://user-images.githubusercontent.com/4138336/81454657-32fbcb00-918d-11ea-9833-4521a0a7a31e.png)

**Comment by math-GH** [comment]
OK. Thanks.

So we should change the description and label of the checkbox to describe it clear(er)

**Comment by fritzmg** [comment]
What do you want to change and why?

**Comment by math-GH** [comment]
I would it re-name in:
Label:
Sicherheitsfrage deaktivieren => Spamschutz deaktiveren
Disable the security question => Disable spam protection

maybe in the description there could be some more information that it is a hidden (non-displayed) security question.
