### ISSUE TITLE
Subpaletten-Titel: Es sind immer "Einstellungen"

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1719]
**Affected version(s)**

Contao 4.9.2 (sicherlich alle Versionen)

**Description**
Die Titel der Subpaletten sind oft mit "Konfiguration" oder "Einstellung" (mal mit mal ohne Bindestrich) beschrieben.
Es sind aber immer Einstellungen, die dort getätigt werden.

![grafik](https://user-images.githubusercontent.com/1645099/81448649-0640b700-917f-11ea-8501-d7ad7bb93d28.png)
![grafik](https://user-images.githubusercontent.com/1645099/81448672-1062b580-917f-11ea-9ba9-bb93b8617245.png)

Konsequent müsste es dann auch "Zugriffschutz-Einstellungen" heißen.

Betrifft sowohl englisch als auch deutsch. Mit Sicherheit auch sehr viele andere Sprachen.

**Comment by m-vo** [comment]
> Konsequent müsste es dann auch "Zugriffschutz-Einstellungen" heißen.

bzw. alles weg, weil redundant

**Comment by math-GH** [comment]
das ist auch meine Intention.

**Comment by leofeyer** [comment]
Ich finde "Modul-Einstellungen" und "Bildeinstellungen" wesentlich klarer als "Modul" und "Bild". 🤷‍♂️

**Comment by contaoacademy** [comment]
Ich würde sagen, einfach alles so lassen und die Zeit für andere Dinge nutzen.

**Comment by Total-Reality** [comment]
> Ich finde "Modul-Einstellungen" und "Bildeinstellungen" wesentlich klarer als "Modul" und "Bild". 🤷‍♂️

Warum heißt es dann aber bei den Inhaltselementen "Sichtbarkeit" und nicht "Sichtbarkeitseinstellungen"? Oder es heißt "Vorschaubild" und nicht "Vorschaubildeinstellungen".

Das ist wirklich Geschmackssache, ich würde aber auch dazu tendieren das mit den "Einstellungen" irgendwie zu umgehen, das wird wirklich inflationär bzw. redundant verwendet. Außerdem muss man auch bei der Entwicklung von Erweiterungen jedes mal nachdenken, ob man das jetzt mit Bindestrich oder ohne Bindestrich schreibt...

Bezogen auf mathContao muss ich allerdings leider widersprechen. Ich finde es zwar auch furchtbar, dass es mal mit Bindestrich und mal ohne Bindestrich geschrieben wird. Allerdings ist das von der Rechtschreibung her völlig korrekt.
1. Alle zusammengesetzten Substantive, die englische Begriffe enthalten, aber am Ende ein deutsches Wort, werden mit Bindestrich geschrieben. Bspw. _Template-Einstellungen_
2. Alle zusammengesetzten Substantive, die komplett deutsch sind, werden normalerweise ohne Bindestrich geschrieben. Bspw. _Bildeinstellungen_
Es geht aber auch mit Bindestrich, wenn ich das richtig verstanden habe...
Sähe aber bspw. merkwürdig aus, wenn man schreibt "Datums-Einstellungen" statt "Datumseinstellungen"

https://www.business-schreibkurse.de/zusammengesetzte-woerter-zusammen-oder-getrennt-schreiben/

Demnach wäre folgendes noch theoretisch gesehen inkonsequent bezogen auf die Module/CE's:

- Menü-Konfiguration -> Menükonfiguration
- Akkordeon-Einstellungen -> Akkordeoneinstellungen

**Comment by fritzmg** [comment]
> Warum heißt es dann aber bei den Inhaltselementen "Sichtbarkeit" und nicht "Sichtbarkeitseinstellungen"? Oder es heißt "Vorschaubild" und nicht "Vorschaubildeinstellungen".

Aus meiner Sicht ist es klar, dass man unter "Sichtbarkeit" die Sichtbarkeit des jeweiligen Elements regelt und unter "Vorschaubild" das Vorschaubild etc. Es wäre nicht klar, was man unter "Modul" regelt.

**Comment by patrickjDE** [comment]
Das Ganze lässt sich kaum verallgemeinern, dazu sind die Subpaletten und ihre Benennungen einfach zu unterschiedlich.

Manche sind nach Aktionen benannt (Veröffentlichung, Formulardaten versenden), manche nach einer bestimmten Komponente/Bereich/Eigenschaft (Bild-Einstellungen, Cache-Einstellungen, Zugriffsrechte, Metadaten, Sichtbarkeit), manche sind Sammelsurien (Globale Einstellungen, Experteneinstellungen), einige dieser Sammelsurien sind nach ihrem Kontext benannt (Formular-Konfiguration, Menü-Konfiguration, Modul-Konfiguration).

Viele davon könnte man auch ohne große Probleme zwischen den aufgezählten Gruppen umherswitchen (à la "Cache-Einstellungen" <-> "Caching"), aber es kommt dabei ja auch auf den Inhalt und die Intention an.
"Veröffentlichung" und "Sichtbarkeit" z.B. passen mMn deutlich besser als "Veröffentlichungseinstellungen" und "Sichtbarkeitseinstellungen", weil es in >90% der Fälle einfach nur um diese einfache Ja/Nein-Entscheidung geht.
Auf der anderen Seite spiegelt "Bild-Einstellungen" die Vielzahl der Konfigurationsmöglichkeiten, die sich hinter dieser Palette verbergen besser wider als einfach nur "Bild", was zumindest bei mir direkt die Assoziation mit einer Bilddatei, bzw. halt einem Auswahlfeld weckt.

Über einzelne Benennungen kann man sicher diskutieren und halt im Einzelfall entscheiden, aber die Diskussion im großen Stil "für alles" ist mMn recht müßig und nicht zielführend, weil eine simple Vereinheitlichung keinen Qualitätsgewinn bringt.
