### ISSUE TITLE
Backend - Messages will not be shown when there is a redirect after submit

### ISSUE THREAD

**Issue by benfolds** [contao/contao#172]
**Affected version(s)**
4.6.x
**Description**  
I extend the tl_page.php in my bundle and add a new class. Inside this class i create a message

` Message::addError(
     sprintf($GLOBALS['TL_LANG']['MOD']['readerMessageInfo'],$reader['title'],$reader['table'],$reader['id'])
);`

This message will only be shown when i use the "Save" button. When using "Save and close", i will be redirected to the pagetree view. There, the message will not be shown. When talking about errors, it would be important to show the message i guess.

**Comment by benfolds** [comment]
Same behaviour in 4.4 and 4.5

**Comment by leofeyer** [comment]
Where exactly are you adding the error message?

**Comment by benfolds** [comment]
I use the onsubmit_callback to check some things and trigger the Error Message. 

[dieschittigs/contao-redirect-bundle/ -> tl_page.php](https://github.com/DieSchittigs/contao-redirect-bundle/blob/master/src/Resources/contao/dca/tl_page.php)

In this case, i do not need to prevent the user from leaving the form.

**Comment by leofeyer** [comment]
The `onsubmit_callback` is probably not the right place to do this, as per definition it is executed **after** the form has been validated. Can you use the `save_callback` instead?

**Comment by benfolds** [comment]
The error should not prevent the page from redirecting to the list because it is related to another backend module.

In this case, the bundle does the following thing:
If you change the alias of a page that has a reader module on it, you get a notification/error that this is a bad idea. But you can do so if you want, because mostly you have a good reason to do this. When you submit this change, the bundle sets a redirect rule in a table that redirects all old reader items to the new page. I want to notify the user that this rule is entered and he has to publish it if he wants to use it.

But i see this is kind of a very special case :)

**Comment by benfolds** [comment]
Isn't this related to #58 ? Message/data handling when redirecting?

**Comment by leofeyer** [comment]
No, it is not related IMHO.

**Comment by leofeyer** [comment]
You could just unset `$_POST['saveNclose']` in your onsubmit_callback. It is a little hacky but it should prevent Contao from redirecting. 🙈 

**Edit:** This would still generate a new version though.

**Comment by srhinow** [comment]
i have solved this with `System::setCookie('NAME', $msg, time()+60*60)` in onsubmit_callback-Methode and in the onload_callback-Methode is the following code:

```
if($_COOKIE['NAME']) Message::addNew($_COOKIE['NAME']);
System::setCookie('NAME','',time()-60);
```
Of course, you can also use any other message method, such as addError.
