### ISSUE TITLE
Comments: Detail page - comment shows HTML

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1720]
**Affected version(s)**

Contao 4.9.2

**Description**
Comment details

field "comment" shows HTML, that was not written by the author.

![grafik](https://user-images.githubusercontent.com/1645099/81450066-f1b1ee00-9181-11ea-8498-6aa82a451d79.png)

![grafik](https://user-images.githubusercontent.com/1645099/81450220-448ba580-9182-11ea-8e93-b678bf0ec6f8.png)

**Comment by fritzmg** [comment]
That's normal. You will see any HTML content this way.
