### ISSUE TITLE
Some back end widgets break layout in Firefox 76

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1721]
**Affected version(s)**

Contao 4.9.2

**Description**

Start point of website

Sub palette "DNS settings"

language and fallback language are not in the correct column.
![grafik](https://user-images.githubusercontent.com/1645099/81451100-068f8100-9184-11ea-95f4-9960f777f7d8.png)

**Comment by fritzmg** [comment]
I can confirm the problem in Firefox under Windows. For some reason some Widgets are 0.5px higher than they should be.

**Comment by math-GH** [comment]
It looks like a bigger problem in Firefox (76, Windows).

![grafik](https://user-images.githubusercontent.com/1645099/81509633-379abd80-930c-11ea-8ce2-c9bded8c0c59.png)

**Comment by leofeyer** [comment]
Firefox is the new Internet Explorer. 🤷‍♂️

**Comment by leofeyer** [comment]
I don't have Windows, so someone else needs to debug this.

**Comment by fritzmg** [comment]
I'll work on this.

**Comment by fritzmg** [comment]
Btw. I was able to reproduce this in Chrome as well with different zoom settings. Example with 80% zoom on a device configured with a pixel density ratio of **1**:

![chrome](https://user-images.githubusercontent.com/4970961/84504584-13881e80-acb4-11ea-8fc3-b0ed4a23b0cf.png)

Imho the current CSS relies too much on individual elements of the widget (the `h3`, the `input/select/textarea` and the `p`) being a certain height. Different rendering engines are handling sub-pixel values differently and thus these discrepancies can occur.

**Comment by fritzmg** [comment]
Closing in favour of #1823 (Contao 4.9) & #1824 (Contao 4.4).
