### ISSUE TITLE
Kommentare: absenden erzeugt Fehler - Fehlermeldung nicht im Backlog-Fehlerlog

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1722]
**Affected version(s)**

Contao 4.9.2

**Description**

Irgendwie ist das Thema nicht ganz rund und ich weiß noch nicht, welcher Teil davon defekt ist.

Es geht um Kommentare (z.B. in Events).

Sendet der User im Frontend ein Kommentar unter einem Event ab, dann kommt die Fehlerseite.
![grafik](https://user-images.githubusercontent.com/1645099/81484729-53d52680-9248-11ea-870a-f9224ab67506.png)

Im Fehlerlog in var/logs/prod-2020.....log steht dieser Fehler:

> [2020-05-09 22:47:41] request.INFO: Matched route "tl_page.17". {"route":"tl_page.17","route_parameters":{"_token_check":true,"_controller":"Contao\\FrontendIndex::renderPage","_scope":"frontend","_locale":"de","pageModel":"[object] (Contao\\PageModel: {})","parameters":"/XXXXXXXX","_route":"tl_page.17"},"request_uri":"https://XXXXXXXX.html","method":"POST"} []
[2020-05-09 22:47:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-05-09 22:47:41] request.CRITICAL: Uncaught PHP Exception Swift_TransportException: "Expected response code 220 but got an empty response" at /var/www/XXXXXXXX/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 445 {"exception":"[object] (Swift_TransportException(code: 0): Expected response code 220 but got an empty response at /var/www/XXXXXXXX/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:445)"} []

Im Backen Fehlerlog ist dieser Fehler jedoch nicht zu finden
![grafik](https://user-images.githubusercontent.com/1645099/81484760-84b55b80-9248-11ea-99d8-aaf529f16920.png)

Das dürfte daran liegen, dass in der parameter.yaml (noch) keine SMTP Daten für den E-Mailversand eingetragen sind.

An dieser aktuellen Situation sehe ich folgende Schwierigkeiten:
1) im Installatiosprozess findet keine Abfrage der SMTP-Daten statt. Im Backend gibt es keinen Hinweis darauf, dass die SMTP-Daten fehlen (weder als Banner noch als Eingabemaske). Wenigstens ein HInweis sollte erfolgen, dass keine Zugangsdaten für den E-Mailversand in parameter.yaml hinterlegt sind.
2) Die Fehlermeldung sollte nicht nur in der var/log/.log Fehlerdatei landen, sondern auch im Fehlerlog im Backend, damit Redakteure und durchschnittliche Admins den Fehler im Fehlerlog erkennen können.

**Comment by fritzmg** [comment]
Bitte formuliere das Issue um, je nach dem ob du einen Bug in Contao gefunden, oder einen Vorschlag für eine Änderung hast. Ansonsten benutze die Kanäle der Contao Community für Support.

**Comment by math-GH** [comment]
aus meiner Sicht ist es ein Bug, dass die Einträge in var/log/prod....log nicht im Backend-System-Log zu finden ist.

**Comment by leofeyer** [comment]
Es ist so beabsichtigt, dass nicht alle Log-Einträge aus `var/log` auch im Backend landen. Insbesondere nicht die, für die es eine Pretty-Error-Screen gibt.
