### ISSUE TITLE
E-Mail-Adresse des Systemadministrators wird auch zum Versenden verwendet

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1723]
**Affected version(s)**

Contao 4.9.2

**Description**
Die E-Mailadresse des Systemadministrators wird nicht nur als Empfänger, sondern auch als Absender verwendet (z.B. für Kommentare unter den Events).

![grafik](https://user-images.githubusercontent.com/1645099/81485115-0dcd9200-924b-11ea-8cf1-9c5c0f172524.png)

![grafik](https://user-images.githubusercontent.com/1645099/81485052-c6470600-924a-11ea-82d8-9d2cfe647b68.png)

Ich denke, dass die Beschreibung zu dem Feld sollte angepasst werden.

Mit der jetzigen Beschreibung würde ich eine private Mailadresse des Systemadministrators angeben.
Mit dem Wissen, dass diese E-Mail auch als Absender verwendet wird, dann würde ich eine System-Mailadresse hinterlegen (zum Beispiel: webseite@domain.tld).

**Comment by leofeyer** [comment]
Wie genau würdest Du die Meldung anpassen wollen?

**Comment by math-GH** [comment]
Vorschläge:

Ich würde das Feld einfach als "System-E-Mailadresse" bezeichnen (oder: "E-Mailadresse des Systems")

Beschreibung: "Diese E-Mailadresse wird zum Versenden und Empfangen von System-Nachrichten verwendet"

**Comment by aschempp** [comment]
Und in der Seitenstruktur dann „Seitenadmin“?

**Comment by math-GH** [comment]
> 
> 
> Und in der Seitenstruktur dann „Seitenadmin“?

klingt nachvollziehbar

**Comment by Metis77** [comment]
Ich würde hier sogar einen Schritt weiter gehen und eine separate System E-Mail angeben wollen.

**Begründung**:
Admin -> my@domain.de

Server -> irgend ein Kunden Server, der nicht im Namen von my@domain.de senden darf. 
Alle E-Mails landen deshalb im Spam, insbesonderen, wenn ich für mich bei my@domain.de DMARC & SPF streng eingerichtet habe.

**Lösung**:
eine eigene System E-Mail sollte hinterlegt werden können.
Diese wird dann für ausgehende E-Mails verwendet.
System -> this@server.de 
(oder eine beliebige Kunden E-Mail Domain, wenn man vorher den SPF der Domain für den Kunden  entsprechend eingerichtet hat)

**Workaround bisher**
Bisher müssen wir immer als Admin eine E-Mail Adresse des Kunden hinterlegen, weil sonst evtl. Seitenbesucher (zB bei Bestätigungsmails) unsere Admin Adresse sehen würden.

**Comment by fritzmg** [comment]
@Metis77 ab Contao 4.10 kannst du eine andere E-Mail Adresse als Absender Adresse forcieren. Siehe https://docs.contao.org/manual/de/system/einstellungen/#verschiedene-e-mail-konfigurationen-und-absenderadressen
