### ISSUE TITLE
Show elements to guests if "Protect element" group is assigned

### ISSUE THREAD

**Issue by operatorone** [contao/contao#1725]
**Affected version(s)**
Contao 4.4 & 4.9

**Description**
If a member group is assigned to a content element with "Protect element/article/page/..." and the option "Show to guests only" is also selected, the element is no longer visible to guests. 

It may sound illogical, but it can happen that you only want to show a certain element to all member groups and guests, but you want to exclude one specific member group.

So, the best ways I think, is to make it possible to use both option at the time, so the element is visible to guests also, if a group is assigned and the "Guests only" option is used.

It still can be achieved to show the elements only guests by not choosing a group in the "Protect element" option.

**Comment by fritzmg** [comment]
You can implement custom logic using the [isVisibleElement hook](https://docs.contao.org/dev/reference/hooks/isVisibleElement/).

**Comment by operatorone** [comment]
Thanks for the hint, but I do not assume that everybody can implement it and it might be a benefit to the overall rights management, to be able to achieve this just out of the box.

**Comment by fritzmg** [comment]
Imho your use-case does not fit within Contao's rights management concept. However, as pointed out, the beauty of Contao is that you can customize a lot of its behaviours and options, to tailor it to your application's needs.

**Comment by operatorone** [comment]
But imho I see the need for a rights management concept not only to be able to include groups and user, but also to be able to exclude them as needed and show the content to a guest too.

**Comment by aschempp** [comment]
I think there are some cases (maybe it was pages) where the system already behaves this way. So it might be worth having a look at 🙃

**Comment by leofeyer** [comment]
> I think there are some cases (maybe it was pages) where the system already behaves this way.

Are you sure? Which ones?

**Comment by Ernestopheles** [comment]
I would appreciate if there was a **negative** protection also. That is to exclude a member group. 

Let's say you have a member group _clubMember_ and you do not want to show the _application for Membership_ form to them (for they have already applied to). 
S.th. like  _MemberGroup allow disallow_ 
where _allow_ and _disallow_ are radiobuttons.

Today we have _MemberGroup allow_ 
and this does in general **not** disallow if not checked.

F.i. a ClubMember may very well be also a Member of a energy-forum. And the latter group should see the application form as long as they do not belong to the ClubMember group.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 27th, the best way to accomplish this is to remove the "show to guests only" field and add a "virtual" member group with the ID 0 for guests that can be selected in the "allowed member groups" field.

**Comment by leofeyer** [comment]
We have to consider, though, that the "show to guests only" checkbox is only available in the site structure and the "allowed member groups" feature everywhere.
