### ISSUE TITLE
Suche - Keine Suchergebnisse wenn Referenzseite auf NewsDetails festgelegt wird

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#1730]
**Affected version(s)**
Contao 4.9.2

**Description**
Ich möchte in meiner Suche nur die Ergebnisse meines Blogs anzeigen. Dazu habe ich als Referenzseite meine "News Detail Seite" ausgewählt.

Wenn ich nun eine Suche durchführen, kommen keine Ergebnisse zurück.

**Reproduktion in der Online-Demo**
1. Module > Suchmaschine > Referenzseite > News Detail einstellen
2. Suche nach einem Begriff innerhalb der News (z.B. release)
4. Keine Ergebnisse gefunden

Anpassen der Referenzseite
1. Löschen der Referenzseite
2. Suche nach einem Begriff innerhalb der News (z.B. release)
3. Ergebnis wird angezeigt.

**Comment by Toflar** [comment]
Already fixed with https://github.com/contao/contao/pull/1670.

**Comment by contaoacademy** [comment]
@Toflar Habe das Problem gestern mit der aktuellsten dev-master getestet. Sind da die Änderungen auch schon drin?

Update: sieht nicht so aus, habe zumindest die Änderungen nicht im Code gefunden.
Ich werde die Änderungen kurz manuell einfügen und noch mal testen

**Comment by ausi** [comment]
@contaoacademy `dev-master` hat die Änderungen noch nicht. Mit `4.9.x-dev` solltest du es testen können.

**Comment by contaoacademy** [comment]
> Mit `4.9.x-dev` solltest du es testen können.

Danke. Der Code ist jetzt dabei.

Allerdings funktioniert damit die Suche leider immer noch nicht zuverlässig.
Ich kann das Problem nicht als behoben bestätigen.

Erst wenn ich keine Referenz angeben, dann kommen die Ergebnisse.

**Comment by contaoacademy** [comment]
@ausi @Toflar Könntet ich euch das noch mal ansehen und das Ticket noch mal öffnen

**Comment by Toflar** [comment]
Es ist alles korrekt, du musst den Suchindex neu aufbauen.

**Comment by fritzmg** [comment]
@contaoacademy hast du nach Einspielen der Änderung den Suchindex neu aufgebaut und den Such Cache gelöscht?

**Comment by contaoacademy** [comment]
Ja. Mehrfach
Ich erstelle euch gerne ein Video

**Comment by contaoacademy** [comment]
Hier das Video.
https://vimeo.com/fenepedia/review/417547727/95b7474270

**Comment by Toflar** [comment]
Was für eine `pid` haben die Einträge in `tl_search`?

**Comment by fritzmg** [comment]
I also tried it on the `4.9` branch, the news detail pages are not indexed correctly. It appears the crawler is not receiving the news detail URLs. It only indexed news detail URLs for me, that happen to be linked some where else on the page (e.g. in a news list).

**Comment by Toflar** [comment]
@aschempp @qzminski is it possible that the urlmatcher does not return the matched `pageModel` in case of a news?

**Comment by contaoacademy** [comment]
Hier der Inhalt von tl_search und tl_search_index
<img width="768" alt="tl_search" src="https://user-images.githubusercontent.com/23719181/81670465-f4456980-9447-11ea-80c0-3662477c6e22.png">
<img width="540" alt="tl_search_index" src="https://user-images.githubusercontent.com/23719181/81670475-f7d8f080-9447-11ea-97aa-11ba5158ebec.png">

**Comment by contaoacademy** [comment]
Hier die DB-Abfrage:

`SELECT * FROM (SELECT tl_search_index.pid AS sid, GROUP_CONCAT(word) AS matches, COUNT(*) AS count, SUM(relevance) AS relevance FROM tl_search_index WHERE (word LIKE '%hund%') AND tl_search_index.pid IN(SELECT id FROM tl_search WHERE pid IN(36)) GROUP BY tl_search_index.pid ORDER BY relevance DESC) matches LEFT JOIN tl_search ON(matches.sid=tl_search.id);`

**Comment by aschempp** [comment]
> @aschempp @qzminski is it possible that the urlmatcher does not return the matched `pageModel` in case of a news?

Pretty sure it does. CMF-Routing (currently) does not know anything about "news" or thelike. It simply matches a page with additional `{parameters}` at the end, which are then converted to `$_GET` as per Contao 3.

I don't think it could be a subrequest either. But what @fritzmg said makes sense, not sure if that is the problem though?

**Comment by Toflar** [comment]
Ah, I think the indexing is correct, so it's not a problem of the linked PR. As you can see, the `pid` is correctly assigned in `tl_search`.
But I guess something might be wrong with the query adjustments of @ausi in https://github.com/contao/contao/pull/1678.

**Comment by ausi** [comment]
I will take a look at it.

**Comment by ausi** [comment]
@contaoacademy Can you send me an SQL dump of your setup? (e.g. via Slack)

**Comment by fritzmg** [comment]
> Ah, I think the indexing is correct, so it's not a problem of the linked PR. As you can see, the `pid` is correctly assigned in `tl_search`.

The search indexer skips pages where the `pid` could not be determined. I get this for most news detail pages, but not for all (for whatever reason):

```
"Contao\CoreBundle\Crawl\Escargot\Subscriber\SearchIndexSubscriber",http://c49.local/news/lorem-ipsum,http://c49.local/share/c49-en.xml,3,noindex,"Forwarded to the search indexer. Did not index because of the following reason: No page ID could be determined."
```

**Comment by fritzmg** [comment]
> Pretty sure it does. CMF-Routing (currently) does not know anything about "news" or thelike. It simply matches a page with additional `{parameters}` at the end, which are then converted to `$_GET` as per Contao 3.

For most news URLs

https://github.com/contao/contao/blob/41c7ba2827e81190dd97efe1732c84b77f4ca036/core-bundle/src/Search/Indexer/DefaultIndexer.php#L116

throws

```
"None of the routers in the chain matched url '/news/lorem-ipsum'"
```

and thus no page ID is retrieved.

**Comment by contaoacademy** [comment]
> @contaoacademy Can you send me an SQL dump of your setup? (e.g. via Slack)

Done

**Comment by ausi** [comment]
It is not related to the search query. Something with the indexing seems to be wrong. As you can see in https://github.com/contao/contao/issues/1730#issuecomment-627240088 some of the news get indexed with `pid` set to `13` and `13` is the id of the error 404 page.

**Comment by Toflar** [comment]
@fritzmg can you check why you get sort of a duplicated URL?

**Comment by Toflar** [comment]
Okay, then something with the matcher doesn't work 🤷‍♂️

**Comment by Toflar** [comment]
Tried to find the issue here together with @qzminski - no luck so far.
Something in that url matching process is really strange.

**Comment by contaoacademy** [comment]
I did some tests. The error is new in Contao 4.9.2
Contao 4.9.1 work correctly.

**Comment by contaoacademy** [comment]
I found the files which causes the problem:
`core-bundle/src/Resources/contao/pages/PageRegular.php`
`core-bundle/src/Search/Document.php`

https://github.com/contao/contao/pull/1457/files

Update: Maybe some more files… but if I replace this 2 files in Contao 4.9.1 with the files from Contao 4.9.2 the search doesn't work any more.

**Comment by contaoacademy** [comment]
After all I think this isn't something new because you already tried to fix it with https://github.com/contao/contao/pull/1670.

If I can help you with further test let me know.

**Comment by contaoacademy** [comment]
I did some more tests with `4.9.x-dev`

I found out some interesting.

If I disable my 404 page and double run the crawler. The tl_search is filled correctly.

After the first crawling:
<img width="918" alt="crawl-1" src="https://user-images.githubusercontent.com/23719181/81777072-62456b80-94f0-11ea-932f-78d4bb7727e6.png">

After the second crawling
<img width="955" alt="crawl-2" src="https://user-images.githubusercontent.com/23719181/81777099-6c676a00-94f0-11ea-8c6c-9ab8fc87251f.png">

Here the logs from both crawlings
[logs.zip](https://github.com/contao/contao/files/4620137/logs.zip)

**Comment by leofeyer** [comment]
I watched the video and reproduced it myself. It is about

* no reference page -> 3 results for "hund"
* with reference page -> only 1 result for "hund"

However, I fail to see how this is related to the indexer? Searching the website does not change the `tl_search` table, so isn't this a bug in the search query, which does not handle the reference page correctly?

**Comment by leofeyer** [comment]
@contaoacademy Can you please checkout the latest `4.9.x-dev` branch and try again? We have fixed the issue in #1738.

**Comment by contaoacademy** [comment]
Thx. Looks great!
