### ISSUE TITLE
tl_calendar_events date variable contains time when it shouldn't

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#174]
**Affected version(s)**
Contao 4.4.28

**Description**
For example in event_upcoming.html5 we have:

```
<div class="event layout_upcoming<?= $this->classUpcoming ?>" itemscope itemtype="http://schema.org/Event">

  <time datetime="<?= $this->datetime ?>" class="date" itemprop="startDate"><?= $this->date ?><?php if ($this->time): ?>, <?= $this->time ?><?php endif; ?></time>
  <a href="<?= $this->href ?>" title="<?= $this->title ?> (<?php if ($this->day) echo $this->day . ', '; ?><?= $this->date ?><?php if ($this->time) echo ', ' . $this->time;?>)"<?= $this->target ?> itemprop="url"><?= $this->link ?></a>

</div>
```

As you can see we have the following line:

```
<time datetime="<?= $this->datetime ?>" class="date" itemprop="startDate"><?= $this->date ?><?php if ($this->time): ?>, <?= $this->time ?><?php endif; ?></time>
```

With the current implementation this results in

`23.11.2018 11:00–24.11.2018 13:00, 11:00–13:00`

But shouldn't be no time stored in `$this->date` so that it would be

`23.11.2018–24.11.2018, 11:00–13:00`

The line in `Events.php` is 234:

```
$strDate = \Date::parse($objPage->datimFormat, $intStart) . $GLOBALS['TL_LANG']['MSC']['cal_timeSeparator'] . \Date::parse($objPage->datimFormat, $intEnd);
```

My correction proposal would be:

```
$strDate = \Date::parse($objPage->dateFormat, $intStart) . $GLOBALS['TL_LANG']['MSC']['cal_timeSeparator'] . \Date::parse($objPage->dateFormat, $intEnd);
```

**Comment by leofeyer** [comment]
But `23.11.2018–24.11.2018, 11:00–13:00` means _on November 23rd from 11am to 1pm and on November 24th from 11am to 1pm_ whereas `23.11.2018 11:00–24.11.2018 13:00` means _from November 23rd at 11am to November 24th at 1pm_. Which case did you want to configure?

**Comment by Defcon0** [comment]
Good question. But I guess this is a fundamental question which the CMS cannot finally decide because it depends on the context. In my special case, `23.11.2018–24.11.2018, 11:00–13:00` was the way to go, but in other people's projects this might differ.

In any case, `23.11.2018 11:00–24.11.2018 13:00, 11:00–13:00` seems wrong to me.

I'd vote for a consistent solution which is always used in the whole CMS. I assume, my use case is more likely, but I might be wrong ;-) I'd go with this solution. If the user needs to have it another way, he could override the templates.

**Comment by leofeyer** [comment]
As discussed in Mumble on December 20th, `23.11.2018 11:00–24.11.2018 13:00` is how other calendars (Apple, Google etc.) interpret a multi-day event with time.

<img width="599" alt="" src="https://user-images.githubusercontent.com/1192057/50295109-a0fc0100-0477-11e9-8b30-c0aabf4f770e.png">

**Comment by Defcon0** [comment]
I'm ok with that ;-) Thanks for discussing it.

**Comment by leofeyer** [comment]
@Defcon0 How did you set up your event to get the wrong output?

```
23.11.2018 11:00–24.11.2018 13:00, 11:00–13:00
```

Because I have tried it this way:

<img width="764" alt="" src="https://user-images.githubusercontent.com/1192057/51183726-63ea2980-18d2-11e9-9ff5-b57f52090f1a.png">

And the output seems correct to me:

<img width="332" alt="" src="https://user-images.githubusercontent.com/1192057/51183743-75333600-18d2-11e9-9c0b-091eed89f40a.png">

**Comment by Defcon0** [comment]
Ah, you're right. I had an error in reasoning ("Denkfehler"). If the `$span` is > 0 the time is simply empty. Sorry for that one.
