### ISSUE TITLE
ce_youtube Untertitel / Teaser

### ISSUE THREAD

**Issue by operatorone** [contao/contao#1751]
Es wäre super, wenn der Untertitel keine Begrenzung auf 255 Zeichen hätte, sondern eher 1024 Zeichen zuließe. 

Alternativ könnte ein zusätzliched Feld "Beschreibung" eingefügt werden, um z. B. auch weitere Texte und Links etc. platziert werden.

Ich bin auch kein großer Fan von kombinierten Elementen und platziere lieber einzelne Elemente untereinander, aber es ist doch immer einfacher für den Redakteur, wenn er die Dinge kompakt vorfindet.

**Comment by fritzmg** [comment]
> Es wäre super, wenn der Untertitel keine Begrenzung auf 255 Zeichen hätte, sondern eher 1024 Zeichen zuließe.

You can adjust such things easily through your own DCA customization.

**Comment by asaage** [comment]
...
oder das ce_youtube template anpassen und die "Beschreibung" direkt von youtube beziehen...

https://stackoverflow.com/questions/5155029/getting-title-and-description-of-embedded-youtube-video

**Comment by operatorone** [comment]
Das wäre auch eine gute Option. Es ist oft aber different was auf der Webseite steht und was auf Youtube hinterlegt ist. Ggf. hat man ja da noch irgendwelchen Youtube-spezifischen Inhalt drin, aber die Idee ist trotzdem gut.

**Comment by operatorone** [comment]
> > Es wäre super, wenn der Untertitel keine Begrenzung auf 255 Zeichen hätte, sondern eher 1024 Zeichen zuließe.
> 
> You can adjust such things easily through your own DCA customization.

Kannst du das beispielhaft darstellen? Oder hast du einen Link der dies veranschaulicht?

**Comment by fritzmg** [comment]
> Kannst du das beispielhaft darstellen? Oder hast du einen Link der dies veranschaulicht?

https://docs.contao.org/dev/getting-started/dca/ ;)

**Comment by asaage** [comment]
Das field-property müsste wohl
```$GLOBALS['TL_DCA']['tl_content']['fields']['playerCaption']['sql']   => "varchar(255) NOT NULL default ''"``` sein

**Comment by fritzmg** [comment]
You can also write

```php
// contao/dca/tl_content.php
$GLOBALS['TL_DCA']['tl_content']['fields']['playerCaption']['sql'] = [
    'type' => 'string',
    'length' => 1024,
    'default' => '',
];
```

**Comment by operatorone** [comment]
Super, ganz lieben Dank für den Tipp.
