### ISSUE TITLE
No root page found

### ISSUE THREAD

**Issue by markus361** [contao/contao#1752]
Contao 4.9

The language fallback does not seem to work. If you go to https://demo.contao.org/de/ you get a 404 page and this log entry:
[2020-05-14 15:28] No root page found (host "demo.contao.org", language "de")

**Comment by fritzmg** [comment]
That's normal. If you specifically request a language sub tree and that language sub tree does not exist, Contao responds with a 404 status.

The language fallback is for cases when you use language parameters and you request the domain without any language parameter. Then Contao will either redirect to the appropriate language sub tree according to the `Accept-Language` header - or the fallback language.

**Comment by markus361** [comment]
we are currently running a multilang and multidomain installation and in the last 2 days there have been about 4000 of these entries in the log
