### ISSUE TITLE
Installation of custom bundle fails on 4.9

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#1755]
Hi there,

If we need some custom functionality we usually create a customer specific bundle and place it into a `src` folder within the root of the Contao installation like this:

```
├── app
├── assets
├── composer.json
├── composer.lock
├── config
├── files
├── src
│    ├── composer.json
│    └── src
│        ├── FooBundle.php
│        ├── ContaoManager
│        │   └── Plugin.php
│        └── Resources
│            └── contao
├── system
├── templates
├── var
```

Of course we adjusted the `composer.json` of the installation to point to the correct path:

```
    "repositories": [
        {
            "type": "path",
            "url": "src"
        }
    ]
```

Then it's just a matter of `composer require numero2/foo-bundle` to install it.

**This worked fine from Contao 4.4 to 4.8.**

Doing the same thing in a Contao 4.9 installation fails during the `composer require` with the following exception:

```
[RuntimeException]
An error occurred while executing the "contao:install-web-dir" command: PHP Fatal error:  Cannot declare class numero2\FooBundle\ContaoManager\Plugin, because the name is already in use in /home/user/www/project/src/src/ContaoManager/Plugin.php on line 25
```

The only way we got it to work is to put our bundle into a subdirectory below `/src` and adjust the `composer.json` accordingly. Or use a totally different folder name than `src` like `mybundle` ;)

```
    "repositories": [
        {
            "type": "path",
            "url": "src/*"
        }
    ]
```

```
├── app
├── assets
├── composer.json
├── composer.lock
├── config
├── files
├── src
│   └── foo-bundle
│       ├── composer.json
│       └── src
│           ├── FooBundle.php
│           ├── ContaoManager
│           │   └── Plugin.php
│           └── Resources
│               └── contao
├── system
├── templates
├── var
```

Is this a now intended behaviour in 4.9 or is it a bug?

**Comment by fritzmg** [comment]
You don't need to create and install a bundle for application-specific code. Just place your code directly into the `src/` folder.

**Comment by bennyborn** [comment]
> [... ] Just place your code directly into the `src/` folder.

Doing so only works if I have no `Plugin.php` in there otherwise `composer install` fails with

```
PHP Fatal error:  Cannot declare class numero2\FooBundle\ContaoManager\Plugin, because the name is already in use in /home/user/www/project/src/ContaoManager/Plugin.php on line 25
```

How would I then define the order of loading the dependencies of my bundle / extension (speaking about `BundleConfig::setLoadAfter`)?

**Comment by fritzmg** [comment]
The Symfony 4+ convention is that you simply do not have a bundle for your application specific code. Thus you do not need to load your bundle with a Contao Manager Plugin - simply because there is no bundle.

**Comment by bennyborn** [comment]
Thanks for the clarification!

**Comment by fritzmg** [comment]
Btw. you can still have a Contao Manager Plugin for your application :). (e.g. for loading third-party non-Contao bundles in the Contao Managed Edition). It is simply automatically loaded if its FQCN is `App\ContaoManager\Plugin`.
