### ISSUE TITLE
Improve the template select menu

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1758]
As discussed in #1729, there are edge cases in which the template select menu is confusing.

<img width="628" alt="" src="https://user-images.githubusercontent.com/1192057/81777989-45aa3300-94f2-11ea-853f-35575acc90d4.png">

The screenshot shows that there is a custom `ce_text` template in the "Theme 2" theme. However, if the content element is used within "Theme 1", the default template will be used instead of the one of Theme 2, but the drop-down does not "say" so.

Possible improvements are:

<img width="616" alt="" src="https://user-images.githubusercontent.com/1192057/81778087-6ecac380-94f2-11ea-9855-4c5f91f6798c.png">

<img width="593" alt="" src="https://user-images.githubusercontent.com/1192057/81778097-7722fe80-94f2-11ea-81d5-d43b37b6b6df.png">

We could not yet agree on a solution, therefore we should discuss this in the next Mumble call.

**Comment by lumas-consulting** [comment]
I'd suggest that mixing default templates with custom templates within one dropdown shouldn't be possible at all.
Overwriting a default template like ce_text.html5 should be possible but the template should not be selectable within an article oder element. This wouldn't be necessary as it is default by nature. 
So why no add a "default" folder to the template folder where only (customized) default templates (for the whole theme) will be placed (always with the original file name as ce_text.html5).
All custom templates will be placed into a custom folder. 
These templates can be chosen by the user within the content element but only when checking a checkbox "use custom template".
This might be intuitive also for none experienced editors.

Contao routine
-> first check custom folder (selectable in Backend)
-> second check default folder
-> third take contao defaults

**Comment by kreativsoehne** [comment]
Hallo, es wäre schön wenn dieser Bug in der 4.9.3 schnell gelöst werden könnte.
Man hat keinerlei Zugriff mehr auf die "default" Templates. Wir können aktuell gar keine neuen Inhaltselemente mehr anlegen, nur solchem, die wir ins eigene Theme abgeleitet haben.

**Comment by fritzmg** [comment]
@Kreativsoehne It sounds more like you need general support from the Contao community, as there is no such known bug within Contao. Likely you are experiencing problems caused by an extension.

**Comment by kreativsoehne** [comment]
i thought the closed ticket above was the bug report.
i create a new one.

**Comment by fritzmg** [comment]
> i thought the closed ticket above was the bug report.

No, this is about an improvement. You are experiencing a different problem, likely caused by an extension.

**Comment by leofeyer** [comment]
As discussed in Mumble on July 30th, we want to use `default` and `global`.
