### ISSUE TITLE
install.php Error ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by lumas-consulting** [contao/contao#1759]
**Affected version(s)**

Contao 4.9.3

**Description**

After updating to Contao 4.9.3, using the Contao Manager (1.2.4) I am trying to update the database but I receive an ERR_TOO_MANY_REDIRECTS Error.
There are no other extensions installed.
PHP 7.3.6
Installation was running fine under 4.9.1

**Comment by aschempp** [comment]
there is no `install.php` in Contao 4.9 ?

**Comment by lumas-consulting** [comment]
I meant contao/install

**Comment by lumas-consulting** [comment]
I reinstalled from scratch. Works now with 4.9. Must have been a corrupt file...
