### ISSUE TITLE
Cookie “PHPSESSID” will be soon rejected

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#1760]
## Affected version(s)

Contao 4.4, 4.9

## Description

Firefox 76.0.1 currently shows this notice in the console on Contao 4.4, as well as Contao 4.9, both when using `http://` or `https://`:

> Cookie “PHPSESSID” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To learn more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies

_Note:_ the warning is only shown in the console, if the cookie is set in the same request.

## Solution

The `sameSite` attribute of the session cookie needs to be set to either `Lax` or `Strict`.

### Contao 4.4

The PHP setting [`session.cookie_samesite`](https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-samesite) is only available in PHP 7.3+ and the Symfony Framework configuration [`framework.session.cookie_samesite`](https://symfony.com/blog/new-in-symfony-4-2-samesite-cookie-configuration) is only available in Symfony 4.2+, thus adjusting the `sameSite` parameter of the session cookie does not seem to be an option for Contao 4.4.

However, we could adjust the `secure` parameter, if it is an HTTPS request. e.g. in the `app.php`/`app_dev.php` (© @toflar):

```diff
 // Handle the request
 $request = Request::createFromGlobals();
+if ($request->isSecure()) {
+    ini_set('session.cookie_secure', 'On');
+}
 $response = $kernel->handle($request);
 $response->send();
```

But for HTTP requests, the session (or any other Cookie) won't work in the future in Contao 4.4 …

### Contao 4.9

Simply add

```yml
framework:
    session:
        cookie_samesite: lax
```

to the `config.yml` of the `contao/manager-bundle` (if `lax` is the correct option, I am not sure 😉).

## Follow up

Originally we thought, that Contao 4.9 automatically uses `secure: true` when using HTTPS in the site structure. However, that is not actually the case.

Also the same restrictions apply to _any_ cookie of course, so other Cookies set by Contao may need to be adjusted as well. The CSRF token cookie already uses `secure: true` (if applicable) and `sameSite: Lax`.

**Comment by aschempp** [comment]
Are you sure that parameter exists in all supported Symfony versions?

**Comment by fritzmg** [comment]
> Are you sure that parameter exists in all supported Symfony versions?

It is available since Symfony 4.2 and Contao 4.9 requires `symfony/framework-bundle` `4.4.*`.

**Comment by msippel** [comment]
I included your code in app.php and app_dev.php in contao 4.4 but the warning is still shown. Our site is HTTPS. What else can I do to resolve this issue?

**Comment by msippel** [comment]
I included your code in app.php and app_dev.php. This solution works for PHPSESSID. But now I get this warning in backend:
`Cookie “BE_PAGE_OFFSET” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies`

How can I fix this?

**Comment by fritzmg** [comment]
> How can I fix this?

You just need to wait, until this is dealt with within Contao itself. Also, the `BE_PAGE_OFFSET` Cookie is not critical for Contao's operation, so you don't have to worry.

Speaking of worry: so far I couldn't find any info on when this change is supposed to be implemented in all the Browser's. Chromium apparently pushed back the change to "Summer": https://redmondmag.com/articles/2020/04/06/samesite-cookie-changes-rolled-back.aspx

**Comment by leofeyer** [comment]
As discussed in Mumble on June 6th, we want to fix this as follows:

**Contao 4.4**

```diff
 // Handle the request
 $request = Request::createFromGlobals();
+if ($request->isSecure()) {
+    ini_set('session.cookie_secure', 'On');
+}
 $response = $kernel->handle($request);
 $response->send();
```

**Contao 4.9**

```yaml
framework:
    session:
        cookie_secure: auto
```

Note that the `auto` value has changed to `null` in Symfony 5 (see https://symfony.com/doc/current/reference/configuration/framework.html#cookie-secure).

**Comment by leofeyer** [comment]
Also, we want to adjust the `System::setCookie()` method and set the default value of `$blnSecure` to `null` and if it is `null`, we set the value depending on `Request::isSecure()`.

**Comment by m-vo** [comment]
For the sake of completion - that's how chromes deals with the topic (see the issue tracker links): 

> A cookie associated with a cross-site resource at http://127.0.0.1/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by leofeyer** [comment]
PR for Contao 4.4: #2117

**Comment by leofeyer** [comment]
PR for Contao 4.9: #2118
