### ISSUE TITLE
getFrontendModule hook is not fired when included in ContentElement

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#1764]
**Affected version(s)**

Contao 4.9.2 in my case, but it looks like it's been like this for a while

I'm not sure whether it's intentional or just overlooked, but feels unexpected after reading the docs. The reason is, the hook is being called from `Controller::getFrontendModule()`, but ContentElement class just calls `$objModule->generate()` directly, bypassing Controller altogether.

Maybe it's not really a bug, but, for instance, even the [example from the docs](https://docs.contao.org/dev/reference/hooks/getFrontendModule/) will not work, if you include the module in the content element, so I felt it needs to be reported.

**Comment by m-vo** [comment]
Modules and content elements are two different concepts (although similar). Are you maybe mixing these up?

Edit: maybe I misread your question: Do you mean the hook is not fired when creating an include content element (that's referencing a module)?

**Comment by ameotoko** [comment]
> Edit: maybe I misread your question: Do you mean the hook is not fired when creating an include content element (that's referencing a module)?

Yes, that's exactly what I meant. Sorry for not making it clear enough.

**Comment by leofeyer** [comment]
@contao/developers Either the docs or the code is wrong here. Which one is it?

**Comment by fritzmg** [comment]
Hm, do you mean we should add "but not if the module was included via Content Element" to the docs?

The same applies to `getContentElement` and `getArticle`. These hooks aren't executed, if the content element `alias` or `article` is used.

**Comment by Toflar** [comment]
That's just been that way ever sine, really. I have encountered this multiple times in 12 years of Contao. I'm pretty sure some people somehow rely on the fact that this is the case by now.
I agree it's inconsistent but I wouldn't fix this in the core for said reasons.

**Comment by fritzmg** [comment]
Technically you could still implement a `getContentElement` hook in addition to a `getFrontendModule` hook, and retrieve the module there, since the `getContentElement` hook is (or at least should be) still executed for the `module` content element.

I will add some notes to the dev docs (see https://github.com/contao/docs/issues/433).

**Comment by leofeyer** [comment]
> The same applies to `getContentElement` and `getArticle`. These hooks aren't executed, if the content element `alias` or `article` is used.

Yes, because our alias elements have been designed to only adopt the content of an element, not the settings. This is also the reason why an alias element does not inherit the CSS classes of the original element.

**Comment by leofeyer** [comment]
As discussed in Mumble on July 30th, this is the intended behavior. We will adjust the documentation to clarify.
