### ISSUE TITLE
Is it possible to grant access for editing accordion labels (accordionStart) to user groups?

### ISSUE THREAD

**Issue by ricowe** [contao/contao#1765]
Is it possible to grant access for editing accordion labels (accordionStart) to user groups?
As far as I can see there is only Text, Headline, HTML etc.

_Originally posted by @ricowe in https://github.com/contao/contao/pull/705#issuecomment-633537240_

**Comment by m-vo** [comment]
See the dca definition for which fields are used:

https://github.com/contao/contao/blob/8be2a14739a4d21b6907d2e126b74a987dc4da53/core-bundle/src/Resources/contao/dca/tl_content.php#L110

You probably want to use `mooHeadline`. If this isn't granular enough for your use case, you can still add your own field to the `tl_content` dca and use this one instead in the templates.

**Comment by ricowe** [comment]
I meant controlling the content elements via user/group rights as implemented in contao 4.9.
There is a option "accordion", but even if the opening element of an accordion is granted, there is no way to edit the text in it.
![screen1](https://user-images.githubusercontent.com/37615273/82813322-19e56080-9e95-11ea-971d-8a375cc8759a.jpg)

**Comment by m-vo** [comment]
Well, did you also allow the relevant fields (`tl_content`)?

**Comment by ricowe** [comment]
Ok, thats it. Thank you.
How can I guess that it can be found as "mooheadline" ;-)
![screen2](https://user-images.githubusercontent.com/37615273/82814272-1ce15080-9e97-11ea-8b4b-f869908b2e83.jpg)
