### ISSUE TITLE
Application cache of dev environment in install tool

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#1766]
**Affected version(s)**

Contao 4.9.4

**Description**

The application cache of the dev environment is not considered by the install tool when saving the database configuration.

1. New Installation
2. Open and fully execute the install tool
3. Login to the backend
5. Activate debug mode
4. Exception: ``An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)``

**Comment by aschempp** [comment]
The dev env cache us not warmed by default, and it should automatically be rebuilt on changes. 

The problem is most likely that the container does not track the `parameter.yml` for changes because the file did not exist yet.
