### ISSUE TITLE
Auflösung von Inserttags in den E-Mail-Feldern z.B. Newsletter

### ISSUE THREAD

**Issue by zonky2** [contao/contao#177]
**Description**  
Auflösung von Inserttags in den E-Mail-Feldern z.B. Newsletter

z.B. damit mal per `{{include_content::123}}` einen allgemeinen E-Mail-Footer einsetzen kann

**Example**  
z.B. Newsletter Abonnieren oder Kündigen

**Comment by leofeyer** [comment]
Duplikat von contao/core#8834. Vor Contao 5 wird das schwierig (siehe https://github.com/contao/core/issues/7587).

**Comment by zonky2** [comment]
@leofeyer Ich bin mir nicht sicher, ob wir das selbe meinen - ich will nix in die Newsletter-E-Mail rein schubsen, sondern in die Anmelde und -bestätigungsmail ... und da auch nur reinen Text - siehe Screenshot

![screenshot_266](https://user-images.githubusercontent.com/1045318/48362478-06541980-e6a4-11e8-9186-64e6a34e54c6.jpg)
