### ISSUE TITLE
addImageToTemplate: undefined method "getName" of class "stdClass"

### ISSUE THREAD

**Issue by Xirdion** [contao/contao#1773]
**Affected version(s)**

Contao 4.9

**Description**

If we use the youtube content element with a splash-image, the function `addImageToTemplate` of the Class `Controller` will be called.
The first parameter of this function is the template object. In the content element this is a `stdClass` object. On line 1701 in the Controller-class the function `getName()` of the tempalte-object is called. But the stdClass-object does not provide such a function.

```php
$strLightboxId = substr(md5($objTemplate->getName() . '_' . $arrItem['id']), 0, 6);
```
`objTemplate` is of type `stdClass`.

https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1701

What value is expected here?

**Comment by fritzmg** [comment]
I can confirm the problem. Reproduction:

1. Create a new _Image_ content element.
2. Enable the **Full-size view/new window** checkbox and select an image.
3. Save the content element.
4. Switch the content element type to _YouTube_.
5. Enable the splash image and select an image.
6. Save the element and open the front end.
