### ISSUE TITLE
Compare page alias with page title and use alias as a subpages as subfolder if both are different

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#1775]
Is it possible to compare the Page alias and page title and use the page alias if it's different as the page title, and then set the subfolder alias for subpages?

For example:
If I create a main page called **Company** and change the alias to **Services**, all subpages will get the page title of the parent page in Alias as a subdirectory. In this case **company/foo.html** and not **services/foo.html**

I think if page alias was changed manually it should inherit to the subpages. Unless you change the subpage alias manually.

It is also important from an SEO perspective that the sub-pages consistently belong to the same subdirectory so that the search engines can assign them correctly.

UPDATE:
Also if you set the alias of the main page as **company/index**, the subpages get **index/....html** as an alias. That is also not correct. If so, it should be called **company/index/....html**.

**Comment by bytehead** [comment]
You can use the `edit multiple` function and re-generate the aliases for the selection.

**Comment by cliffparnitzky** [comment]
Generally, the alias of the parent is used, when creating a new subpage. In case of renaming the function mention by @bytehead should help.

**Comment by havutcuoglu** [comment]
@bytehead thanks a lot but I know the option to **edit multiple**.
@cliffparnitzky if I use the **edit multiple** Contao will delete all aliases and generate them new. This is not what I want.

The Problem is, if I create a new main page called Company the Contao generate the alias `company.html`, then I create a subpage called About us contao set subpage alias as `company/about-us.html` that is OK.

Now, if I create a main page called Company and change the alias manually to `company/concern` and then I create a subpage called About us. Now Contao create the subpage alias as `concern/about-us.html` correct alias musst be `company/concern/about-us.html`

Why Contao ignore the subfolder from the main page alias?

**Comment by fritzmg** [comment]
> Now, if I create a main page called Company and change the alias manually to `company/concern` and then I create a subpage called About us. Now Contao create the subpage alias as `concern/about-us.html` correct alias musst be `company/concern/about-us.html`

That should not happen. And I cannot reproduce that. If I create a page with the Alias `company/concern` and then a subpage within that page, its automatic alias will be prefixed with `company/concern`.

**Comment by asaage** [comment]
As far as i can reproduce this, the autogenerated alias with enabled folder-urls is built from top to bottom (or root/parent to child if you wish to say so) but somehow it only works as expected when the number of slashes matches the nesting level.
Is that your problem?


> I think if page alias was changed manually it should inherit to the subpages. Unless you change the subpage alias manually.

That would be bad from an SEO perspective (changing the url of existing/indexed pages automatically)

**Comment by havutcuoglu** [comment]
@asaage
> That would be bad from an SEO perspective (changing the url of existing/indexed pages automatically)

I don't change existing pages. It is a new website.

@fritzmg check this video.
[https://we.tl/t-SbUk2hIceM](url)

I use actually the contao 4.9.3

**Comment by fritzmg** [comment]
You are right, now I was able to reproduce it to, I didn't actually use `company/concern` before.

### Reproduction:

1. Enable the **Enable folder URLs** system setting.
2. Create a new page within a website root, use the **Alias** `company/concern`.
3. Create another page _as a sub page_ of the previously created page with the **Page name** _Foo_ and save.

The automatically generated alias will be `concern/foo` instead of `company/concern/foo`.

**Comment by havutcuoglu** [comment]
Exactly. That's it.

The other problem is, if you set the alias of the main page as company/index, the subpages will get foo/goo/index/....html as an alias. But I think nobody will want that (folder name index).

**Comment by asaage** [comment]
> https://we.tl/t-SbUk2hIceM

... number of slashes does not match hirarchy-level... that is what i noticed earlier.
To mitigate that (and i used that technique a lot) you probably could insert an internal redirect-page without jump-to and build your structure like that 

- root
  - company (internal redirect without target & alias=company)
    - your actual company-page (regular page with alias company/concern)
    - about-us (autogenerated alias will be company/about-us)

**Comment by havutcuoglu** [comment]
**But if I have a structure like that, it will not work.**
- Company (as Overview for all subpages & alias=`company/index`)
-- concern (alias=`company/concern`) (contao generated alias=`index/concern`) **wrong alias**
-- about-us (alias=`company/about-us`) (contao generated alias=`index/about-us`) **wrong alias**

**then i have to do it like as you wrote**
- Company (redirect to index subpage & alias=`company`)
-- index (as Overview for all subpages & alias=`company/index`)
-- concern (alias=`company/concern`)
-- about-us (alias=`company/about-us`)

however, it doesn't change the fact that the aliases are generated incorrectly.

**Comment by asaage** [comment]
I would say it's in fact a bug and the autogenerated alias should in fact be a true concatenation of ancestor-aliases+page-name.

If you are concerned about the redirect you could also take a look at https://github.com/terminal42/contao-folderpage (though i'm not quite shure if there are aliases involved at all)

I think i don't understand exactly what you are trying to achieve 🤔

**Comment by havutcuoglu** [comment]
I need SEO friendly URLs for main page and sub pages like

- company/index
- company/concern
- company/about-us

Google and Co. can handle this kind of aliases better then like this
- company
- company/concern
- company/about-us

**Comment by asaage** [comment]
just use ```url_suffix="/" or ""``` and be happy without redirect-hack's?

**Comment by havutcuoglu** [comment]
What is the reason of this discussion?
The alias generation with subfolder from manually changed aliases is a feature or it is a bug?

**Comment by fritzmg** [comment]
It is a bug that the automatic alias generation skips a fragment. It is not supposed to.

**Comment by havutcuoglu** [comment]
Shell I make a bug report or this issue is enough for the documentation?

**Comment by fritzmg** [comment]
This issue is already your bug report ;)

**Comment by dmolineus** [comment]
You might have a look at https://github.com/hofff/contao-trueurl which provides full control about alias inheritance to sub pages. If wanted aliases of subpages get automatically updated if the parent page changes

**Comment by leofeyer** [comment]
> You are right, now I was able to reproduce it to, I didn't actually use `company/concern` before.
> 
> ### Reproduction:
> 1. Enable the **Enable folder URLs** system setting.
> 2. Create a new page within a website root, use the **Alias** `company/concern`.
> 3. Create a another page _as a sub page_ of the previously created page with the **Page name** _Foo_ and save.
> 
> The automatically generated alias will be `concern/foo` instead of `company/concern/foo`.

Does this affect both Contao 4.4 and 4.9?

**Comment by fritzmg** [comment]
Yes, just reproduced it in Contao 4.4.49 too.
