### ISSUE TITLE
News: Es ist nicht möglich einen individuellen Link zu setzen

### ISSUE THREAD

**Issue by jankout** [contao/contao#178]
**Affected version(s)**
4.6.7
**Description**  
Wenn ich auf der ersten Ebene eine News einen individuellen Link setzen möchte, wird es nicht möglich - egal ob in Firefox oder in Safari (macOS 10.14.1). 
**How to reproduce**  
siehe Bild. Wenn ich auf die Funktion "Individuelle URL" klicke, passiert nichts bzw. die Seite wird nur neu geladen, aber es ändert sich nichts. 
![news-individuelle verlinkung](https://user-images.githubusercontent.com/3715050/48272211-62b5ff80-e43e-11e8-80e0-7738d9e07bfd.png)

**Comment by jankout** [comment]
ok, ich habe es herausgefunden - es lag daran, dass das Newsarchiv von Redakteuer kopiert wurde, allerdings nicht die Weiterleitung des Newsarchivs auf eine bestimmte Seite bestimmt. Könnte man bitte einen Hinweis zeigen, damit das für den Redakteuer klarer wird, warum es dann nicht funktioniert? Danke.

**Comment by fritzmg** [comment]
@jankout ich denke nicht, dass das etwas mit dem core zu tun hat. Offensichtlich hast du da sehr viele Extensions bzw. DCA Änderungen.
