### ISSUE TITLE
CORS policy error when using Combine scripts with CDN for font files

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#1780]
**Affected version(s)**

Contao 4.9

**Description**

I use some fonts in my website that are located if "files/fonts".  When using a subdomain like cdn.mywebsite.com for "File URL" and "Assests URL" in site structure [without "Combine scripts"], everything is OK and font files are accesible from website. But if "Combine scripts" is check, Access to fonts will block by CORS policy.

**Comment by leofeyer** [comment]
Is there an error message in the browser console?

**Comment by ausi** [comment]
If you want to load webfonts from a different domain you have to make sure, that your webserver of your CDN sets the appropriate `Access-Control-Allow-Origin` header for the font files.

**Comment by hamidpeywasti** [comment]
> Is there an error message in the browser console?
Error in "Inspector Console":

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.mywebsite.com/files/theme/fonts/Shabnam/Shabnam-WOL.woff2. (Reason: CORS header Access-Control-Allow-Origin missing).`

> If you want to load webfonts from a different domain you have to make sure, that your webserver of your CDN sets the appropriate `Access-Control-Allow-Origin` header for the font files.

Yes, My solution was adding `Header set Access-Control-Allow-Origin "*"` in .htaccess, and everything OK. 

What interesting to me is that, this occurs only when "Combine scripts" is checked.

**Comment by ausi** [comment]
> What interesting to me is that, this occurs only when "Combine scripts" is checked.

This would indicate that without “Combine scripts” the font gets loaded from a different domain. 

Can you disable “Combine scripts” in your website and post a link to it?  
Or alternatively look at the source code to check from which domains the CSS and font files get loaded?

**Comment by hamidpeywasti** [comment]
Whitout "Combine scripts", css files are loading from main domain and not CDN!
After enable "Conbine scripts", css files loaded form CDN?

CDN = https://cdn.pmtcookware.com

page without "Combine scripts": https://pmtcookware.com/fa/
page with "Combine scripts": https://pmtcookware.com/fa/about


Ich denke: The problem is that, when "Combine scripts" is enabled, "assets [or files] URL" is not applied!

**Comment by ausi** [comment]
> The problem is that, when "Combine scripts" is enabled, "assets [or files] URL" is not applied!

I think it is the other way round, when “Combine scripts” is **disabled** the assets/files URL seems to be missing.

**Comment by ausi** [comment]
I was able to reproduce it in 4.9. Does this issue occur in Contao 4.4 too?

**Comment by hamidpeywasti** [comment]
Dann muss der Titel geändert werden.

**Comment by ausi** [comment]
Closed in favor of #2180
