### ISSUE TITLE
Contao 4.9 + Honeypot

### ISSUE THREAD

**Issue by Alibi-Contao** [contao/contao#1782]
Nach Deaktivierung der HTML5-Validierung erscheint beim falsch ausgefüllten Formular die Sicherheitsabfrage (Wieviel ist xy+z?) .
Das Verhalten kann man bei der Contao Demo nachvollziehen. 
Bei aktiver HTML5-Validierung tritt dieses Verhalten nicht auf. Dort bleibt die Sicherheitsabfrage unsichtbar.
Unter Contao 4.8x erscheint die Sicherheitsabfrage nicht.

**Comment by ausi** [comment]
Ich konnte den Fehler auf demo.contao.org nicht reproduzieren. Hast du das Formular eventuell sehr schnell ausgefüllt (unter 5 Sekunden)?

**Comment by Alibi-Contao** [comment]
Jep, sorry, das war unter 5 Sekunden. Ich wollte ja die die Fehlermeldungen zu den Feldern "provozieren" (zum Prüfen meiner CSS-Datei) und hab daher kein Feld ausgefüllt und gleich auf Senden geklickt. Macht dann natürlich Sinn, da kein Mensch so schnell die Felder befüllen kann.
Wieder was dazu gelernt. Vielen Dank

**Comment by xchs** [comment]
> da kein Mensch so schnell die Felder befüllen kann.

Chuck Norris schafft das locker in deutlich unter einer Sekunde. 💪 😄
