### ISSUE TITLE
Articles tab missing in the universal picker

### ISSUE THREAD

**Issue by Webstylerin** [contao/contao#1783]
**Affected version(s)**

Contao 4.9.3

**Description**

When Contao is installed without news or events it is impossible to switch to the article overview in the include content element to select the referenced element. The navigation is missing.

![missing](https://user-images.githubusercontent.com/3033160/83420116-7234d900-a426-11ea-8796-abb1b95dff0a.png)

**Comment by aschempp** [comment]
It is intentional that there is no tab if there's only one item. However, we should figure out how to navigate to the root item in this case. I don't think this is only related to content elements.

**Comment by leofeyer** [comment]
Showing the tab would be the easiest way to fix this, however, being able to use the "go back" button would be the more intuitive fix. I stumbled upon this myself already.
