### ISSUE TITLE
Google-Fonts API Version 2 Handling

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#1791]
As mentioned in the [forum](https://community.contao.org/de/showthread.php?78134-Google-Fonts-API-Base-URL&p=526398&viewfull=1#post526398):

By using the suggested Google-Fonts embed parameters for example:
https://fonts.google.com/specimen/Oswald?sidebar.open&vfonly&query=Oswald&selection.family=Oswald:wght@200;380;400

within the Pagelayout/Webfonts settings we get unexpected results. This is because of the Google Fonts APIv2 - see: https://developers.google.com/fonts/docs/css2

So maybe this should be mentioned in the pagelayout help text. Difficult to describe ...
Or switch to the new API Version?
Or leaving a hint in the docs? 
...

**Comment by fkaminski** [comment]
See: Add Notice for Google Fonts API Version [#414](https://github.com/contao/docs/pull/414) in the docs

**Comment by leofeyer** [comment]
What would be the correct/best solution here?

**Comment by fkaminski** [comment]
It still works as before. But not with the new [API 2 Syntax](https://developers.google.com/fonts/docs/css2). There is a [hint in the docs](https://docs.contao.org/manual/de/layout/theme-manager/seitenlayouts-verwalten/#webfonts) for now.
Optional one could use this as with any other CDN font within "Zusätzliche <head>-Tags".
Therefore, this could in principle be removed in the future (IMO). But don't know how to make it backwards compatible then ...

**Comment by fritzmg** [comment]
We could:

* Remove the field from the palette, as it may not be as relevant now as it was in the past.
* Implement a validation for the field, so at least users get an error, if they use the v2 syntax.
* Implement an automatic detection of the new v2 syntax, so the correct URL will then be used in the front end.

Personally, I am in favour of removing that feature in the future. But that may not be a popular decision ;).

**Comment by leofeyer** [comment]
I'm in favor or removing the field, too. But if we are going to keep the field, we should detect and handle the new v2 syntax accordingly.

@contao/developers Keep or remove?

**Comment by frontendschlampe** [comment]
remove :-)

**Comment by fkaminski** [comment]
> But that may not be a popular decision

That will probably happen - Personally i never used it (self hosted the fonts). If removed, could you make sure that existings settings will then applied to "Zusätzliche -Tags"? Otherwise user may wonder why their custom fonts disapear

**Comment by Toflar** [comment]
Remove the field and migrate it to custom head tags. That's the only sensible solution imho.

**Comment by fkaminski** [comment]
@Toflar  ShortnSweet - Love it

**Comment by Funbug** [comment]
@Toflar 
With "migrate it to custom head tags" you mean the update will take care of it, right?

**Comment by Toflar** [comment]
It should, yes :)

**Comment by bennyborn** [comment]
I just wanted to add, even if you remove the Google Fonts: The only GDPR compliant way is to host the fonts locally. This also applies to loading Mootools or jQuery from a CDN. Maybe there should be a discussion about removing CDNs from the core entirely.

**Comment by fritzmg** [comment]
The GDPR does not prevent you from using any external services on your site. Removing such features is not necessary as you are always responsible for implementing a website according to your local law.

**Comment by bennyborn** [comment]
> The GDPR does not prevent you from using any external services on your site.

That's correct. But if you can waive such external resource with reasonable effort (which would totally be the case with Webfonts, jQuery or Mootools) you should host them locally or ask the user for his permission prior to loading them.

> Removing such features is not necessary as you are always responsible for implementing a website according to your local law.

I was under the impression that Contao went for a GDPR compliance out of the box some time ago but if that's the position of the team I'm totally fine with that.

**Comment by fritzmg** [comment]
Google Fonts and jQuery/Mootools via CDN are not enabled by default. Also using Google Webfonts or jQuery/Mootools via CDN does not mean you are not GDPR compliant.
