### ISSUE TITLE
Handle the new (ugly) outlines in Chrome 83+ for inputs, selects, textareas, buttons

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1793]
Hello,

after upgrading to Chrome 83+ the user gets very ugly thick black borders around inputs, selects, textareas, buttons in the contao backend.

Example:

![Unbenannt](https://user-images.githubusercontent.com/1485098/83791305-df03d980-a699-11ea-8448-a4d6436029f9.png)

The solution is to simply set an outline. We fixed it by using the following code (which is simply the old Chrome default code). Maybe we could add an orange outline as it's Contao primary color for all browsers?

```
body.chrome {
  input, button, select, textarea {
    &:focus {
      outline-color: rgb(77, 144, 254);
      outline-offset:-2px;
      outline-style:auto;
      outline-width:1px;
    }
  }
}
```

The reason why the ugly black borders appear now is that at the moment simply no outline is set in contaos base css.

See here for more info:

- https://support.google.com/chrome/thread/49555984?hl=en
- https://stackoverflow.com/questions/61920365/strange-outline-appears-in-chrome-83-ie-on-my-windows-10
- https://support.google.com/chrome/thread/48974735?hl=en

Hoping for your opinions.

Bye Defcon0

**Comment by m-vo** [comment]
I assume the reason behind Chrome's change wasn't for the aesthetics but for better accessibility (which is a good thing). We should keep that in mind.

**Comment by Defcon0** [comment]
No question. Because of this we didn't simply remove the outline but restored the old blue style.

**Comment by leofeyer** [comment]
Actually, we are trying to adhere to the browser standards as much as possible. If Chrome decides to change their focus style, we should not mess with it IMHO.

**Comment by Defcon0** [comment]
I understand the argument, but with this reasoning, I could also say that we can't style the buttons since chrome styled it already ;-)

I think more and more frameworks will now define outlines since Chrome's change some kind of forces them. But the result is good since there were no outlines before at all. Maybe that was the plan of Google in the first place ;-)

BTW: We already have had the first customer complaints telling us that "a bug has happened" and the style is corrupted :-D

**Comment by m-vo** [comment]
> I could also say that we can't style the buttons since chrome styled it already

And that's what the web is moving to and what should imo be another goal (bridging the gap between native apps and websites).

**Comment by Defcon0** [comment]
But aren't the browser manufacterers doing the exact opposite right now? Chrome's controls look the same on Windows and on macOS e.g. No adaptation here in order to bridge the gap between web and the local system.

Also visual creativity also of a backend UI is a bit gone in my opinion.

Nevertheless I understand both views though. I didn't have made up my mind completely atm.

**Comment by asaage** [comment]
Contao alway's has put effort in accessibility thats whyi think there should have been some kind of focus-styles in the first place.

**Comment by bennyborn** [comment]
While I'm also on the side of Contao doing it's best the be as accessible as it can be I think Chrome took it a bit too far but on purpose. While the previous "light blue glow" was pleasing to the eye and fitted within many styles most websites just took the default styling for granted and didn't bother to come up with something on their own which might be one reason why the new styling is so "drastic".  Just to show the designers "hey guys, you've missed something here". I think Contao should add it's own focus-styling to match the rest of the backend design and still have good accessibility ;)

**Comment by fritzmg** [comment]
> While the previous "light blue glow" was pleasing to the eye and fitted within many styles most websites just took the default styling for granted and didn't bother to come up with something on their own which might be one reason why the new styling is so "drastic". Just to show the designers "hey guys, you've missed something here".

I don't think that's the case at all. I think it's there solely for accessibility.

**Comment by Defcon0** [comment]
>  Just to show the designers "hey guys, you've missed something here". I think Contao should add it's own focus-styling to match the rest of the backend design and still have good accessibility ;)

I agree to that. This was also my suspicion :-)

**Comment by fritzmg** [comment]
Personally I find the new default focus outline of Chrome to be very helpful and enjoyable in the Contao back end.

However, this decision should of course not be made based upon personal tastes or opinions. I think we should consult UX and more importantly accessibility experts for this.

**Comment by may17** [comment]
From the official chromium blog about this Change:

> Note that there are still some scenarios where the focus ring may be hard to perceive—for example, if a black button is on a white background, or if the focus ring is clipped by elements that are positioned closely together.
If you run into a scenario where the focus ring is hard to perceive, or if the new focus indicator does not match the design of your site, there are ways to style focus including the new :focus-visible pseudo-class, which provides fine-grained control over when the focus indicator is displayed.

Source: https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html?m=1

Imho there is nothing wrong to keep the functionality but tweak the color a little bit with their Intention in mind.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 27th, we do not want to mess with this – unless there was a real accessibility/usability problem, which is not the case.

**Comment by Defcon0** [comment]
Ok, I understand this. Thanks for taking it into account though!
