### ISSUE TITLE
Default priority for callbacks uncertain

### ISSUE THREAD

**Issue by rabauss** [contao/contao#1795]
**Affected version(s)**

Contao 4.9?

**Description**

I registered a callback with annotations (`@Callback(table="tl_content", target="config.onload")`) but without priority.

Deviating from the documentation the callback is not executed after all other callbacks - it's the first one. Although my Bundle is registered after ContaoCoreBundle!

See the docs here: https://github.com/contao/docs/blame/master/docs/dev/framework/dca/_index.md#L96

@aschempp noticed that it was like the docs in the first draft - see:
https://github.com/contao/contao/pull/39/commits/6577835f22a5811b8387aa70804fd7668c0870b3#diff-26ec4b3e6c5b2ff5898a7c6caa86c1c6R128

 But now it isn't anymore the last! Is it intended, that the callback is registered as first instead of last with `priority=0` (default) or is it a failure in the docs? Only with `priority=-1` the Callback gets correctly loaded after all other callbacks!

**Comment by leofeyer** [comment]
@aschempp @fritzmg /cc

**Comment by aschempp** [comment]
> @aschempp noticed that it was like the docs in the first draft - see: 6577835#diff-26ec4b3e6c5b2ff5898a7c6caa86c1c6R128

That must be a misunderstanding, I meant that it was always like that, even from the first draft. Unfortunately, it is different for hooks and callbacks, which isn't really intuitive. But I can't think of a way to change that without potential conflicts? 🤔

**Comment by fritzmg** [comment]
If we want to keep BC in that regards, then I guess we have to live with it :(

**Comment by leofeyer** [comment]
As long as it is documented correctly, I guess we could live with it.

**Comment by rabauss** [comment]
I can live with that too - if it's properly documented ;-)
@aschempp sorry for the misunderstanding - I was so confused with the order of the callbacks against hooks

**Comment by leofeyer** [comment]
@rabauss @fritzmg So do we have to adjust the docs or is everything fine as is?

**Comment by fritzmg** [comment]
We have to adjust the docs, it's on my todo list (PRs welcome though 😉).

**Comment by fritzmg** [comment]
Btw. should we add the labels `bug` `incompatible` so that we might change this in Contao 5, if still applicable?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to adjust the callback behavior to the hook behavior, so it works as already described in the docs: https://github.com/contao/docs/blame/main/docs/dev/framework/dca/_index.md#L96

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4940
