### ISSUE TITLE
HTML Content Element script Tag incorrect save

### ISSUE THREAD

**Issue by Clonk-HTML5** [contao/contao#18]
**Affected version(s)**
Version 4.4.18

**Description**  
If i save a Html Content Element than contao handles some incorrect escaping over the html string 

**How to reproduce**  

for example :

```
<script src="https://www.holidaycheck.de" type="text/javascript"></script>
<div id="holidaycheck-widget-hotel" class="holi-mediu-23456"><div id="holidaycheck_widget_placeholder-1905712" style="width:120px;padding:5px;background:#0058a2;"></div></div>
```

is escaped by contao to this:

```
&lt;script src="https://www.holidaycheck.de" type="text/javascript">&lt;/script><div id="holidaycheck-widget-hotel" class="holi-mediu-23456"><div id="holidaycheck_widget_placeholder-1905712" style="width:120px;padding:5px;background:#0058a2;"></div></div>
```

**Comment by xchs** [comment]
You would have to wrap your code with code tags to see what is meant.

**Comment by fritzmg** [comment]
Also you should always updated to the most recent bugfix or minor version, before reporting bugs.

**Comment by asaage** [comment]
See https://github.com/contao/core/issues/8246
