### ISSUE TITLE
Systemwartung->Symlinks neu erstellen verursacht Internal Server Error

### ISSUE THREAD

**Issue by srhinow** [contao/contao#180]
verwende Contao 4.6.7, PHP7.2

Wenn ich im Backend unter Systemwartung den Haken bei "Symlinks neu erstellen" setze und das ausführen lassen möchte, bekomme ich die Fehlerseite mit:

> Internal Server Error
> Was ist das Problem?
> The "contao.command.symlinks" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Comment by Toflar** [comment]
Another duplicate of https://github.com/contao/contao/issues/153
