### ISSUE TITLE
Wrong position in backend menu?

### ISSUE THREAD

**Issue by kikmedia** [contao/contao#1804]
I just stumbled into this, wondering that even if we sort backend modules in Contao 4.9 by alphabet, (see https://github.com/contao/contao/commit/42f85a4e26eeec8dc3886ae200fb0567f231e641)  the Manager still appears at the very last position in backend system menu.

Is that the intended behaviour?

**Comment by ausi** [comment]
I think this is a bug and we should change the code in https://github.com/contao/contao/blob/5790005f0bb3f5523f69bb658349235b4c7cbadd/manager-bundle/src/EventListener/BackendMenuListener.php#L165 to insert the link at the correct position.

**Comment by leofeyer** [comment]
It is actually not a bug. We are only sorting the output of `BackendUser::navigation()` alphabetically but we are not messing with menu items that are added through event listeners. And the Contao Manager link is (intentionally) added last.

**Comment by kikmedia** [comment]
May I ask what your intention was?

**Comment by m-vo** [comment]
The manager isn't part of the application and thus the link should be separate? Imo that's correct.

**Comment by leofeyer** [comment]
@kikmedia What exactly do you mean? Why we are only sorting the `navigation()` output alphabetically or why we are adding the Manager link last?

**Comment by kikmedia** [comment]
I was just curious why everything in navigation is sorted alphabetically but the part of the manager is not. I'm not going to claim about that decision (even if I think it's so-so), but I think from a usabitilty point of view the position of the manager is unexpected. If everything is sorted, why this one is not?

On the other hand this is quite cool because there is one think which position never changes. After some customers noticed me about that usability thing, I thought this not-sorting could be wrong somehow.

So I tried to understand why you did it this way. I want to understand, I don't want to claim about it.

Now I noticed that the debug button on top of the site is another thing that behaves like the manager button - visible only to admins, calling some symfony functions.

So, wouldn't it be an good idea to bundle all those admin stuff in a either in a separate menu where it may be sorted whatever way you want, or put the non-alphabetically-sorted manager link together with the debug button on top of the backend?

**Comment by leofeyer** [comment]
I feel like we have to discuss this again. I am not too happy with the alphabetic sorting, either.

**Comment by fritzmg** [comment]
See also: https://github.com/contao/contao/issues/1706

I think it needs to be possible to define priorities for each back end module in `$GLOBALS['BE_MOD']` (see https://github.com/contao/contao/issues/1706#issuecomment-634493886).

**Comment by Ernestopheles** [comment]
To fit every one it might be useful to implement a manual sort (like in content-element tree).
I personally did not care about the sorting yet.

**Comment by leofeyer** [comment]
As discussed in Mumble on July 2nd, we want to revert the alphabetical sorting. Instead, we want to allow each user to resort the menu items individually. (We still have to discuss whether to store these changes on the server or in the local browser storage.)

**Comment by asaage** [comment]
The local browser storage does not seem to be the right place...

- there are a bunch of items
- the order might easily get lost (browse incognito / different browser / ...)
- there will be no possibility as an admin to preorder items for other users

**Comment by aschempp** [comment]
@asaage is right, it sure must be in the user profile (simply the user session bag)

**Comment by ausi** [comment]
Why is this issue closed now?

Didn’t we

> want to allow each user to resort the menu items individually. (We still have to discuss whether to store these changes on the server or in the local browser storage.)

**Comment by fritzmg** [comment]
#1706 is still open
