### ISSUE TITLE
Warning in ModuleRegistration when Username is empty

### ISSUE THREAD

**Issue by koertho** [contao/contao#1809]
**Affected version(s)**

Contao 4.9

**Description**

When registering a new member in the frontend and no username is set (which is possible since it must not be checked in field selection), a "empty password" warning is thrown on line 225 in ModuleRegistration (to be correct in SodiumPasswordEncoder line 93).

https://github.com/contao/contao/blob/4.9/core-bundle/src/Resources/contao/modules/ModuleRegistration.php#L225

![Bildschirmfoto vom 2020-06-11 11-46-57](https://user-images.githubusercontent.com/12064642/84371076-693bc880-abd9-11ea-87f5-cc6eb047ee3b.png)

**Comment by leofeyer** [comment]
So you did enable the password field but not the username field? What is the use-case here?

**Comment by koertho** [comment]
@leofeyer A use case would be setting username automatically by email address. Like in our email2username bundle (https://github.com/heimrichhannot/contao-email2username-bundle)

**Comment by fritzmg** [comment]
@koertho does the problem also occur with https://packagist.org/packages/terminal42/contao-mailusername for example?

**Comment by koertho** [comment]
@fritzmg With this extension it works. I will add the fix to our bundle, thanks! But for the core I think there should be at least a check if the post variable is set. Even better would be an event before to evaluate the input variables :grinning: :wink:

**Comment by fritzmg** [comment]
> But for the core I think there should be at least a check if the post variable is set.

And what should happen, if it is not set? Then another exception would need to be thrown anyway. I think it is not necessary to add such a check, since the functionality of the module depends on a username being present.

**Comment by leofeyer** [comment]
I think we should skip the "password matches username" check if there is no username.

**Comment by koertho** [comment]
@fritzmg Shure, an exception would be better then a warning only visible in dev mode and an always invalid password in prod mode. But @leofeyer's idea sounds also a good idea. Then the bundles are responsible for the match check.
