### ISSUE TITLE
[RFC] Make favicon.ico dynamic

### ISSUE THREAD

**Issue by Toflar** [contao/contao#181]
In https://github.com/contao/contao/commit/9d8ac9299c7336f22bb6a4a0264a29e9f1dfbe56 a default `favicon.ico` was added to the Managed Edition Skeleton.
This has one major downside: Contao is multi-domain capable so I can have 5 different domains running on the same installation. In that case, I likely have different logos/icons and I cannot replace them dynamically. Yes, of course I can have a different icon in HTML pages using `<meta>` tags but that doesn't work e.g. for file downloads.

If we'd register `favicon.ico` as a Symfony route and dynamically serve the icon from the root page settings, that would work as well.
Also, for those that are concerned about not serving files using php, you can still just place the `favicon.ico` in your `web` folder if you want to. As long as you configured your server to serve static files first if they exist (which is default) there should be no problem doing so.

Any objections why we should not introduce this?

**Comment by fritzmg** [comment]
I am all for it.

Also I still want to have a default favicon ico for the back end that is _not_ the regular orange icon, which is used on every Contao page (contao.org, community.contao.org) ;)

**Comment by leofeyer** [comment]
I'm not a big fan of using Symfony (or PHP in general) to deliver images. I think the `<link rel="icon"` tag has been introduced for exactly this use case, therefore we should use it IMHO.

**Comment by fritzmg** [comment]
> I think the `<link rel="icon"` tag has been introduced for exactly this use case, therefore we should use it IMHO.

But this will not be present for files. Imagine you have a multi domain setup with two completely different favicons:

* example.org
* lorem.com

Now let's assume you put the favicon of _example.org_ into the `/web` folder. If you then directly open an image in the browser, e.g.:

* https://example.org/files/foo.jpg
* https://lorem.com/files/moo.png

both these URLs will display the favicon of _example.org_.

And as @Toflar said if you do not need or like favicons being served via PHP, you can still simply put a _favicon.ico_ into the `/web` folder yourself which will then served by the web server directly.

**Comment by Toflar** [comment]
Which is BTW exactly what's described in the original issue description 😄

**Comment by fritzmg** [comment]
True, just wanted to emphasize it ;)

**Comment by frontendschlampe** [comment]
But for "modern" Websites one favicon isn't enough! There are many sizes of icons ...

Why are we even delivering an favicon?

**Comment by fritzmg** [comment]
> But for "modern" Websites one favicon isn't enough! There are many sizes of icons ...

For that you'll still use the appropriate HTML meta tags.

**Comment by frontendschlampe** [comment]
@fritzmg you're right, but why using two version for the same thing? If I have to include icons manually, so I can include all the icons manually. For the Backend I have no problem with such a solution, but in Frontend ...

**Comment by fritzmg** [comment]
See https://github.com/contao/contao/issues/181#issuecomment-437847776 (and @Toflar 's original description) above. There is not other way, if you want to have the correct favicon when viewing files directly in the browser.

**Comment by leofeyer** [comment]
As discussed in Mumble on November 22nd, we want to remove the default `web/favicon.ico` file, then it is up to the user to decide whether to use a static favicon or an extension such as https://github.com/hofff/contao-favicon (which could be enhanced with a custom favicon route).

**Comment by leofeyer** [comment]
Fixed in f4217a579820b9b1ea5d96449e54fdc48de2c0f3.
