### ISSUE TITLE
Filterung im BE bei Seitenstruktur nach unveröffentlichte: geht nicht innerhalb eines Zweiges

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1811]
Filterung im BE bei Seitenstruktur nach unveröffentlichte: geht nicht innerhalb eines Zweiges

aus Demo:

![Zwischenablage02](https://user-images.githubusercontent.com/1045318/84393176-8b464280-abfb-11ea-9e78-a711af9a3888.jpg)

**Comment by ausi** [comment]
I can confirm the issue in Contao 4.4 and 4.9. It only occurs if a subtree is selected (`tl_page_node` in the session).
