### ISSUE TITLE
Encode date ranges by microdata markup

### ISSUE THREAD

**Issue by xchs** [contao/contao#1812]
This is a follow up to https://github.com/contao/core/issues/8012 regarding the discussion about the HTML markup for date ranges. The [W3 consortium suggests](http://www.w3.org/TR/html5/text-level-semantics.html#the-time-element) to use some kind of microdata markup:
- hCalendar microformat vocabulary

``` html
  <time class="dtstart" datetime="2015-11-26">26/11/2015</time> –
  <time class="dtend" datetime="2015-11-30">30/11/2015</time>
```
- schema.org microdata vocabulary

``` html
  <time itemprop="startDate" datetime="2015-11-26">26/11/2015</time> –
  <time itemprop="endDate" datetime="2015-11-30">30/11/2015</time>
```

I have found some articles where they all suggest to use two separate `<time>` elements when it comes to mark up date ranges:
- http://www.brucelawson.co.uk/2012/best-of-time/
- http://www.sitepoint.com/html5-time-element-guide/#limitations

**Comment by MDevster** [comment]
Maybe we could use an insert tag "time" to achieve the desired behavior.

```
<div class="event layout_full block<?= $this->class ?>" itemscope itemtype="http://schema.org/Event">
...
<p class="info">{{time::<?= $this->tstamp ?>}}</p>
...
</div>
```

tstamp contains a time object with the necessary times.
Without any specification it would output the following:

```
<time datetime="<?= $this->datetime ?>" itemprop="startDate"><?= $this->date ?><?php if ($this->time): ?> <?= $this->time ?><?php endif; ?></time>
```

You could define a new time format in config.yml, so it would output the other formats for the whole system.
Or if you only want to change something in some template you could adjust the tag:

```
{{time::<?= $this->tstamp ?>::hCal}}
{{time::<?= $this->tstamp ?>::schema}}
```

**Comment by aschempp** [comment]
I don't see how the insert tag is related to adjusting the calendar module templates?

**Comment by MDevster** [comment]
I wanted to make it easier for the user to understand, hence the insert tag. But we could also put the logic into the controller.

`<?= $this->localizedDateAndTime() ?>`

Results in 

```
<time datetime="<?= $this->datetime ?>" itemprop="startDate">>?= $this->date ?>>?php if ($this->time): ?> <?= $this->time ?>>?php endif; ?></time>
```

----

`<?= $this->localizedDateAndTime ('hCalendar'); ?>`

Results in 

```
 <time class="dtstart" datetime="2015-11-26">26/11/2015</time> -
  <time class="dtend" datetime="2015-11-30">30/11/2015</time>
```

----

`<?= $this->localizedDateAndTime('microdata'); ?>`

Results in 

```
<time itemprop="startDate" datetime="2015-11-26">26/11/2015</time> -
  <time itemprop="endDate" datetime="2015-11-30">30/11/2015</time>
```

**Comment by aschempp** [comment]
our templates already use the microdata format (as far as I know), so we should simply put that markup into the template …

**Comment by fritzmg** [comment]
Since https://github.com/contao/contao/pull/3155 we now use JSON-LD to output the meta data and since https://github.com/contao/contao/pull/6496 we also include the start and end dates and times and the template output is otherwise now uniform.
