### ISSUE TITLE
Crawler Problem

### ISSUE THREAD

**Issue by dp-designpilot** [contao/contao#1813]
**Affected version(s)**
Contao 4.9.3

**Description**
Ich habe in Plesk jetzt einiges probiert (auch das /tmp/contao-crawl Verzeichnis manuel zu erstellen, in dem ich es an diversen Orten probiert habe)

![Bildschirmfoto 2020-06-11 um 18 52 28](https://user-images.githubusercontent.com/57160987/84416807-010ad800-ac15-11ea-8c54-fc238b4b4015.png)
![Bildschirmfoto 2020-06-11 um 18 53 31](https://user-images.githubusercontent.com/57160987/84416808-01a36e80-ac15-11ea-9280-3d207b55acf9.png)

Ich hab es im Basisverzeichnis versucht und auch im /system/tmp Verzeichnis und zusätzlich dort wo die composer.json Datei liegt, aber es hat alles nichts genutzt.

**Auszug der Log Datei**
`[2020-06-11 18:31:23] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://www.murg-kultur.ch/contao?act=crawl&crawl_subscriber_names%5B0%5D=search-index&do=maintenance&jobId=e3c5486e-71bc-4255-ba7b-68a890021d1e&ref=rgpghmwM","method":"POST"} []
[2020-06-11 18:31:23] request.CRITICAL: Uncaught PHP Exception UnexpectedValueException: "The stream or file "/tmp/contao-crawl/e3c5486e-71bc-4255-ba7b-68a890021d1e_log.csv" could not be opened: failed to open stream: Permission denied" at /home/httpd/vhosts/murg-kultur.ch/httpdocs/webseite/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php line 109 {"exception":"[object] (UnexpectedValueException(code: 0): The stream or file \"/tmp/contao-crawl/e3c5486e-71bc-4255-ba7b-68a890021d1e_log.csv\" could not be opened: failed to open stream: Permission denied at /home/httpd/vhosts/murg-kultur.ch/httpdocs/webseite/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:109)"} []`

Aber der Crawler startet nur und bleibt immer auf 0% stehen egal ob ich beide Checkboxen anwähle oder nur jede einzeln.

Kann mir da jemand Helfen

**Comment by fritzmg** [comment]
We had some issues with putting files in sub directories of the `sys_get_temp_dir()`, which is one of the reasons we deprecated the `AbstractLockedCommand`, iirc.

**Comment by fritzmg** [comment]
@dp-designpilot to check if the permission problem is with the sub directory, you could try to remove the sub-directory from

https://github.com/contao/contao/blob/87d21c174b5cb24305e2a5a0bfcb5206def42621/core-bundle/src/Resources/contao/classes/Crawl.php#L90

and

https://github.com/contao/contao/blob/87d21c174b5cb24305e2a5a0bfcb5206def42621/core-bundle/src/Resources/contao/classes/Crawl.php#L277

On a related note: I noticed that `sys_get_temp_dir()` will return a trailing slash in some environments, producing a path with a double slash (i.e. `/tmp//contao-crawl/…`).

**Comment by dp-designpilot** [comment]
Can I try that?
https://community.contao.org/de/showthread.php?77356-Crawler-bricht-nach-kurzer-Zeit-(auch)-in-der-Konsole-ab&p=525773&viewfull=1#post525773

**Comment by fritzmg** [comment]
> Can I try that?

No, that has nothing to do with your problem.

**Comment by dp-designpilot** [comment]
> @dp-designpilot to check if the permission problem is with the sub directory, you could try to remove the sub-directory from
> 
> https://github.com/contao/contao/blob/87d21c174b5cb24305e2a5a0bfcb5206def42621/core-bundle/src/Resources/contao/classes/Crawl.php#L90
> 
> and
> 
> https://github.com/contao/contao/blob/87d21c174b5cb24305e2a5a0bfcb5206def42621/core-bundle/src/Resources/contao/classes/Crawl.php#L277
> 
> On a related note: I noticed that `sys_get_temp_dir()` will return a trailing slash in some environments, producing a path with a double slash (i.e. `/tmp//contao-crawl/…`).

I followed the steps but had no result

**Comment by fritzmg** [comment]
> I followed the steps but had no result

Post the error message to confirm.

**Comment by dp-designpilot** [comment]
I just tried something now

https://github.com/contao/contao/blob/87d21c174b5cb24305e2a5a0bfcb5206def42621/core-bundle/src/Resources/contao/classes/Crawl.php#L90

**i changed the line to:** $crawLogsDir = 'contao-crawl';

and this 

https://github.com/contao/contao/blob/87d21c174b5cb24305e2a5a0bfcb5206def42621/core-bundle/src/Resources/contao/classes/Crawl.php#L277

**i changed the line to:** return 'contao-crawl/' . $jobId . '_' . $subscriberName . '_log.csv';

And now it works:
![Bildschirmfoto 2020-06-11 um 20 53 42](https://user-images.githubusercontent.com/57160987/84427786-c2314e00-ac25-11ea-8edc-1ed54a66c5b0.png)
![Bildschirmfoto 2020-06-11 um 20 54 10](https://user-images.githubusercontent.com/57160987/84427789-c2c9e480-ac25-11ea-9af0-585e4d421061.png)

**The directory must be there:**
![Bildschirmfoto 2020-06-11 um 21 02 45](https://user-images.githubusercontent.com/57160987/84428600-0b35d200-ac27-11ea-92e6-9ee51a28f871.png)

**Comment by leofeyer** [comment]
Yeah, we must not use `sys_get_temp_dir()`. It is too error-prone.

**Comment by fritzmg** [comment]
imho each Contao instance - or rather Symfony application instance - should use its own temp directory within the project directory. Related: https://github.com/symfony/symfony/issues/23354

**Comment by dp-designpilot** [comment]
Is there still a solution for this bug? Or can I do that?

**Comment by Toflar** [comment]
I've said this many times before: We must be able to rely on `sys_get_temp_dir()`. It is an invalid configuration if this doesn't work. There's loads of stuff that depends on that, in all kinds of third-party libraries we're using.

**Comment by leofeyer** [comment]
Actually, I could not find a single place where `sys_get_temp_dir()` is used in the production part of the code. Granted, it is used a lot in unit test classes and mocks, but that is not problematic.

Can you point me to where `sys_get_temp_dir()` is used in production?

**Comment by Toflar** [comment]
* `Symfony\Component\Lock\Store\FlockStore.php`
* `Symfony\Component\Process\Pipes\WindowsPipes.php`
* `Symfony\Component\Translation\Util\XliffUtils.php`
* `Symfony\Component\DomCrawler\Field\FileFormField.php`
* `Symfony\Component\DependencyInjection\Loader\XmlFileLoader.php`
* `Symfony\Component\Console\Helper\QuestionHelper.php`
* `Symfony\Component\Cache\Traits\FilesystemCommonTrait.php`
* a few Swiftmailer classes
* lots of other stuff we might not use right now but maybe some day

Remember: Even if Contao doesn't use things in production right now, apart from the fact that we might be using it somewhen in the future, lots of things might be required by the Contao Manager (e.g. PHAR handling and process management often requires writing things to a temporary directory). Most likely users would be affected there anyway.

Again: The purpose of the function `sys_get_temp_dir()` is to [tell me the path to a temporary directory](https://github.com/php/php-src/blob/6b45039fb768a038783dff496ce14780c478482a/php.ini-production#L751-L753) where I can write temporary data without worrying about garbage collection. If I'm not allowed to write data to that directory, it is a misconfiguration.

**Comment by ausi** [comment]
The folder for `sys_get_temp_dir()` can be customized via *php.ini*. So if someone has problems with the temp directory from the system they could try to set the following in their *php.ini* configuration:

```ini
sys_temp_dir = "/absolute/path/to/your/webspace/var/tmp"
```

Or in the apache config:

```apache
php_admin_value sys_temp_dir /absolute/path/to/your/webspace/var/tmp
```

@dp-designpilot can you try if this solves your issue?

**Comment by ausi** [comment]
@dp-designpilot were you able to solve your issue with my suggestion from above?
