### ISSUE TITLE
Galerie-Element "vergißt" ausgewählte Bilder

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#1816]
Kann in der Demo nachgestellt werden:

1. Galerie-Element anlegen und Bilder aus einem Unterordner wählen. Dabei den Unterordner im Pfad fest einstellen.
2. Dateimanager aufrufen und einen anderen Pfad dort einstellen.
3. Zurück zum Galerie-Element wechseln und weitere Bilder aus dem anderen Pfad hinzufügen. Nach dem Klick auf Anwenden sind die Bilder aus dem Pfad in Punkt 1 verschwunden.

**Comment by fritzmg** [comment]
Meinst du mit "Pfad fest einstellen" eine Filterung auf den Pfad? Wenn ja, dann ist das zu erwarten, meiner Meinung nach. Nur alle sichtbaren Checkboxen werden übernommen.  Ein ähnliches Ticket gab es erst vor kurzem - finde es aber gerade nicht.

**Comment by leofeyer** [comment]
Ich habe es so verstanden:

<img width="903" alt="" src="https://user-images.githubusercontent.com/1192057/38991001-88128fda-43dc-11e8-988a-c3b3cc9dd170.png">

Und das Problem ist, dass Bilder einer bestehenden Galerie außerhalb des gewählten Pfades nicht angezeigt werden und dann beim Speichern verloren gehen.

**Comment by rabauss** [comment]
Wir haben das für einen Kunden schon mal an einigen Stellen so gelöst, dass wir das Widget erweitert haben und uns die vorherigen Werte in der Session merken und dann mit den neuen Werten "mergen".
Das war und ist bei großen Installation die beste Lösung und funktioniert nun auch schon einige Zeit sehr zuverlässig.

Ich sehe das auch als neues aber sehr sehr hilfreiches Feature!

**Comment by leofeyer** [comment]
> dass wir das Widget erweitert haben und uns die vorherigen Werte in der Session merken und dann mit den neuen Werten "mergen".

Wie habt ihr den Fall gelöst, dass der Kunde Bilder aus der Auswahl entfernen möchte?

**Comment by rabauss** [comment]
Wir haben das über einen Ajax-Callback auf das [x] im Listen-Eintrag gelöst - eigentlich könnte ich das auch mal im Projekt raussuchen und in einem Pull Request anfangen für den Core zu liefern ;-)

EDIT:
Okay ich könnte das wohl wirklich aus unserem Projekt übernehmen, v.a. könnten wir dann dort auch den eigenen Picker ablösen :-) Hierzu aber noch ein paar Fragen zur Namensgebung:
1. Wie würdet ihr die Option für den Picker nennen, dass dieser die bisherigen Werte "merged"? - im Projekt haben wir das `mergeCurrent` genannt und als `eval`-Option umschaltbar ermöglicht.
2. Ich bräuchte noch einen sinnvollen generischen Selektor namen statt `.gimage`, damit die removable-Buttons besser wiederverwendbar initialisiert werden können - `removable` ist schon vergeben - was meint ihr? https://github.com/contao/contao/blob/711a454f830473a78cdf6438ba14d50a8dc9e4e0/core-bundle/src/Resources/public/core.js#L1428

**Comment by rabauss** [comment]
oh das wollte ich mir ja ansehen /cc myself

**Comment by fritzmg** [comment]
@rabauss nicht mehr notwendig :) #2296
