### ISSUE TITLE
Calendar-Module ignores event coming from the get getAllEvents-Hook for boundaries calculation

### ISSUE THREAD

**Issue by michb** [contao/contao#1818]
In
https://github.com/contao/calendar-bundle/blob/f18b9130ba4d02ef0c189ed5fb16ef8d2922c8ec/src/Resources/contao/modules/ModuleCalendar.php#L116
the module tries to find its boundaries. This will be used to determine if there is a next and/or prev button.
But this calculation only takes events from the `tl_events` table into account.

In my case I wrote an extension that will load additional events from an given URL and adds them through the `getAllEvents`-Hook.
This all works fine. They will be displayed in the listing and in the calendar module. 
But the next and prev button in the calendar won't be generated as there are no current events in the database.

I think a good solution would be to iterate over all `$this->arrEvents` and find the boundaries.

Another case is if one used the `getAllEvents`-Hook to filter some events, e.g. all events. Then the next button will be generated, but there is no event to be displayed.

**Comment by leofeyer** [comment]
As discussed in Mumble on October 22nd, we need a separate hook to find the lower and upper boundaries (similar to the `newsListCountItems` hook).

**Comment by leofeyer** [comment]
Since Contao 4.4 is now in the "security updates only" phase of the LTS cycle, I am moving this issue to the 4.9 milestone.
