### ISSUE TITLE
Show custom default template for fragments

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#1819]
See https://github.com/contao/contao/issues/1734#issuecomment-630647379

> Btw. there is one other improvement we could do. Say you have a content element like this:
> 
> ```php
> <?php
> 
> /**
>  * @ContentElement(category="texts", template="ce_foo")
>  */
> class ExampleElementController extends AbstractContentElementController
> {
>     protected function getResponse(Template $template, ContentModel $model, Request $request): ?Response
>     {
>         // …
>     }
> }
> ```
> 
> i.e. with a template defined within the service tag, the template selection still looks like this:
> 
> <img src="https://user-images.githubusercontent.com/4970961/82298787-8a2f4600-99ac-11ea-8607-85bf4a385832.png" width="375" alt="example_element">
> 
> i.e. the blank option is still called `ce_example_element`, instead of `ce_foo`. Since in this case we _know_ the default template name, couldn't we also show that for the blank option here?
> 

@contao/developers bug or feature?

**Comment by leofeyer** [comment]
I would say it is a bug.

**Comment by fritzmg** [comment]
Still on my radar ;)
