### ISSUE TITLE
system/themes/default/images/about.gif wird nicht gefunden

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#1820]
Contao 4.8

Ist vielleicht in der 4.9 schon behoben.
In der 4.8 gibt es kein default-Theme mehr für das Backend, weshalb bei einem DCA-Feld vom Typ checkbox diese Grafik nicht mehr gefunden wird, wenn man die Option explanation verwendet.

Funktionierendes Beispiel. Hier wird system/themes/flexible/icons/about.svg angezeigt und das verlinkte Popup zeigt den Hilfetext an:

```php
'erwerb' => array
(
	'label'                   => &$GLOBALS['TL_LANG']['tl_lizenzverwaltung_items']['erwerb'],
	'inputType'               => 'text',
	'exclude'                 => true,
	'flag'                    => 8,
	'explanation'             => 'lizenzverwaltung_erwerb', 
	'eval'                    => array
	(
		'rgxp'                => 'date',
		'datepicker'          => true,
		'helpwizard'          => true,
		'tl_class'            => 'w50 wizard',
		'doNotCopy'           => true
	),
	'sql'                     => "varchar(11) NOT NULL default ''"
),
```

Dieses Beispiel funktioniert nicht. Eingebunden wird diesmal die nichtvorhandene Datei system/themes/default/images/about.gif und das verlinkte Popup zeigt außer der Überschrift nichts weiter an:

```php
'codex' => array
(
	'label'                   => &$GLOBALS['TL_LANG']['tl_lizenzverwaltung_items']['codex'],
	'inputType'               => 'checkbox',
	'default'                 => true,
	'explanation'             => 'lizenzverwaltung_codex', 
	'exclude'                 => true,
	'eval'                    => array
	(
		'mandatory'           => false,
		'tl_class'            => 'w50',
		'helpwizard'          => true,
		'isBoolean'           => true,
		'submitOnChange'      => true
	),
	'sql'                     => "char(1) NOT NULL default ''"
),
```

**Comment by aschempp** [comment]
Contao 4.8 wird nicht mehr unterstütz. Bitte teste das auf Contao 4.9, dann gerne das Ticket wieder öffnen falls der Fehler noch besteht.
