### ISSUE TITLE
Update Sicherheitsfrage/Honeypot - Ideen zur besseren Spamvermeidung bei Formularen

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#183]
Wir nutzen ja mittlerweile in Contao 4 bei der Sicherheitsfrage eine Honeypotfunktion, um Spammails zu verhindern. Das hat bisher auch sehr gut geklappt, aber seit ein paar Wochen gibt es diverse Spammails, die doch wieder durchkommen - auch am Honeypot vorbei.

Wir müssten uns also irgendwas einfallen lassen, wie wir das wieder eindämmen oder verhindern können.

Nach ein paar Gesprächen auf dem Camp und auch im Mumble bin ich mit dem Problem nicht allein.

Wir hatten folgende Ideen:

- reCaptcha - ist aber Google :-(
- sonstige Captcha-Dienste (ggfs. kostenpflichtig)
- Spamfilter in Contao auf Basis von Black/Whitelisting von IP u.a.  - IP's kommen aus entsprechenden Diensten - bekämpft nur die Symptome, aber nicht die Ursache

Mittlerweile kenne ich viele Websites, die Ihre Formulare komplett entfernen, aber das ist ja keine Lösung.

Wie sind Eure Erfahrungen damit? Was kann es für Lösungen geben?

**Comment by leofeyer** [comment]
Duplikat von contao/core#8874. Das Ticket hatten wir damals geschlossen, weil keine Log-Dateien zur Verfügung gestellt werden konnten. Ich habe das Ticket jetzt wieder geöffnet, damit Du die notwendigen Log-Dateien hochladen kannst, damit @ausi es sich ansehen kann.
