### ISSUE TITLE
Never allow regular users to promote any user to be an admin

### ISSUE THREAD

**Issue by Toflar** [contao/contao#184]
Right now it is possible for a regular user to promote themselves and others to become administrator.
Of course, it is only possible if the user has the permissions to do so (`alexf` on `tl_user.admin`) but it still feels wrong. You cannot promote anybody to become `root` if you're not `root` yourself. It shouldn't be dependent on the permissions.

I'd suggest to remove `admin` from the excluded fields completely and adding it to the `tl_user` palettes only if the currently logged in user is admin as well using the `PaletteManipulator`.
Wdyt?

**Comment by leofeyer** [comment]
Changed in b7acf28b6084f328cd3a5574a2765d282bbb30a0.
