### ISSUE TITLE
Add image size to news and calendar feed for teaser images

### ISSUE THREAD

**Issue by bezin** [contao/contao#1842]
Hello there,

while working with the Contao core news feed I stumbled upon the issue, that the link to the teaser images will point to the source image in the files folder. However, these images might be a couple of MB in size. I would prefer to define a specific image size for this, so that the link points to an optimized thumbnail in the feed and even takes the important area into account.

This should be quite easily doable and I would be happy to provide a PR.

Another issue on the other hand is, that images from content elements would need to be resized to. 

I ran into this issue when we worked  on a newsletter template for CleverReach; they provide the feature, that one can dynamically include content in the newsletter via an RSS feed. However, the current implementation would include the 4000px×2800px source file. We implemented our own RSS feed to work around this issue in the application.

Any thoughts welcome :-)

**Comment by asaage** [comment]
> the link to the teaser images will point to the source image in the files folder

Shouldn't the teaser-images be linked to the news-details-view?
At least for news-lists that is the default case - and if you specify the full-size/lightbox-view
tl_layout->lightboxSize would be applied.
I would prefer the feed to behave likewise.

Thoughts on the other issue:
I use the core-newsletter solution and added templates to the be_tinyNews.html5.
https://www.tiny.cloud/docs/plugins/template/
The url of those templates point to a stripped-down hidden page on my site wich just displays a newslist wich can be configured independently.

**Comment by bezin** [comment]
> Shouldn't the teaser-images be linked to the news-details-view?

What do you mean? The URL of the feed item links to the detail page, yes. But I am talking about the image file itself. This will be the source file from /files (i.e. the path stored in tl_files). 

Your solution for the newsletter sounds interesting however we need a more powerful solution :-)

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
The feature would be an image size field in the `tl_news_feed` DCA?
But the image sizes of the content elements in the news article would stay as configured in the content elements?

**Comment by leofeyer** [comment]
Since the only purpose of this is to prevent the large source image to be used in the RSS feed, we might as well either

a) use the fallback image size from the page layout or
b) hardcode a reasonable default format for images in RSS feeds.

I doubt that the image size will be different per feed.

**Comment by bezin** [comment]
Hello, I totally missed out on this discussion due to my holidays 🙈 

> The feature would be an image size field in the tl_news_feed DCA?
But the image sizes of the content elements in the news article would stay as configured in the content elements?

Yes, that was the initial idea. But for my use case, one would of course need to overwrite every image content element sizes (as well as maybe filter out some content management at all). So maybe my initial proposal is not enough 🤔 

>a) use the fallback image size from the page layout or
b) hardcode a reasonable default format for images in RSS feeds.

I don't really like both proposals. To solve my issues I think It would be necessary to apply own logic during feed generation, i.e. hook into / listen somewhere here: https://github.com/contao/contao/blob/af6fbee47ea5375deefcf4dca6d4362d584a7ff4/news-bundle/src/Resources/contao/classes/News.php#L106 This way I could overwrite image sizes and filter out content elements...

**Comment by m-vo** [comment]
Just thinking: could/should we maybe use a twig template for the feed? Then you could tweak it however you want.

**Comment by leofeyer** [comment]
As discussed in Mumble on November 19th, we want to add this to the feed settings.

**Comment by bezin** [comment]
Ah, I missed the call :( but great news :)

**Comment by bezin** [comment]
This is merged now 👍
