### ISSUE TITLE
Inhaltselemente duplizieren erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by hjotto** [contao/contao#1845]
Contao 4.9.3

**Description**

Fehler trat in eigener Installation und auf https://demo.contao.org auf.

Beim Duplizieren eines Inhaltelements vom Typ "Inhaltselement" (Include-Elemente > Inhaltselement) und dem gleichzeitigen ändern des "Bezogenes Inhaltselement" ohne Zwischenschritt "Speichern" erfolgt beim abschließenden Speichern eine Fehlermeldung. Das neue "Bezogenes Inhaltselement" muss von einer **anderen** Seite innerhalb des Artikelbaums kommen. 
Wird das Duplizierte Inhaltselement erst gespeichert und dann wieder aufgerufen und geändert kommt keine Fehlermeldung.
Ist das neue "Bezogenes Inhaltselement" von der gleichen Seite erfolgt keine Fehlermeldung.

### **Fehlermeldung**

Forbidden
Was ist das Problem?
Cannot load record "tl_content.id=330".

### **Schritte auf dem Onlinedemo**

An Onlinedemo anmelden
_Inhalte > Artikel_
Seite: Home - Artikel Home [Hauptspalte] bearbeiten
Neu > Include-Elemente - Inhaltselement
Bezogenes Inhaltselement : About this demo ID 1 wählen
Speichern und schließen
Erzeugtes Inhaltselement duplizieren
Bezogenes Inhaltselement ändern: Learn more ID 46 wählen
Speichern und schließen
ok
Erzeugtes Inhaltselement duplizieren
Seite: Home - Artikel Home Right [Hauptspalte]
Bezogenes Inhaltselement ändern: Back end Login ID 47 wählen
Speichern und schließen
**Fehler**

**Forbidden
Was ist das Problem?
Cannot load record "tl_content.id=330".**

Seite zurück
Speichern
Fehler
Seite zurück
Inhalte > Artikel
Seite: Home - Artikel Home [Hauptspalte] bearbeiten
**Inhaltselement ID 330 wird nicht angezeigt**

### **System > System-Log**

**ID 38: A new entry "tl_content.id=330" has been created by duplicating record "tl_content.id=329" (parent records: tl_article.id=1, tl_page.id=2)
ID 41: A record with the ID "330" does not exist in table "tl_content"**

**Comment by leofeyer** [comment]
Ich konnte die Schritte anhand Deiner sehr guten Anleitung nachvollziehen, allerdings ist der Fehler bei mir nicht aufgetreten. Kannst Du das Problem in der [Online-Demo](https://demo.contao.org/contao) reproduzieren?

**Comment by hjotto** [comment]
Hallo Leo,
ich habe eine Videoaufzeichnung von dem Fehler in der Online-Demo gemacht.
Unter dem Link https://1drv.ms/v/s!Ao32NkNStjqMkFzDy4htAO_Wlz2X?e=p6WP22 findest du die Mp4-Datei.

**Comment by ausi** [comment]
Ich vermute das Problem liegt an der `DC_Table::reviseTable()`-Methode. Eventuell sollten wir dort prüfen ob wir uns in einem Picker befinden und in diesem Fall die Methode nicht ausführen?

**Comment by aschempp** [comment]
> Ich vermute das Problem liegt an der `DC_Table::reviseTable()`-Methode. Eventuell sollten wir dort prüfen ob wir uns in einem Picker befinden und in diesem Fall die Methode nicht ausführen?

Das tun wir eigentlich schon...
