### ISSUE TITLE
Bezogene Inhaltselemente "Kinder" optional mit löschen, wenn "Elternelement" gelöscht wird

### ISSUE THREAD

**Issue by zonky2** [contao/contao#1847]
Aktuell müssen alle Kindelemente aufgespürt werden, wenn das Elternelement gelöscht wird. Mit der Erweiterung https://github.com/inspiredminds/contao-include-info wird das Aufspüren der "Kinder" erleichtert, eine Option, alle Kinder mit zu löschen, wäre m.E. schön.

Meinung dazu?

**Comment by fritzmg** [comment]
@zonky2 means the `alias` content element, by the way.

**Comment by m-vo** [comment]
What exactly is the question? :smile:

**Comment by m-vo** [comment]
related: https://github.com/contao/contao/issues/1682

**Comment by leofeyer** [comment]
> eine Option, alle Kinder mit zu löschen, wäre m.E. schön.

Sounds like a feature request for the Contao Include Info extension?
