### ISSUE TITLE
Reset von 2FA eines Frontend Users

### ISSUE THREAD

**Issue by Georg-Git** [contao/contao#1851]
Erfreue mich gerade an den 2FA Funktionen für Backend und Frontend User.

Als Admin vermisse ich jedoch die Funktion 2FA Daten von einzelnen Mitgliedern (also Frontend User) zu löschen/zu reseten. Aktuell muss ich dafür die entsprechenden 2FA Felder des Frontend Users in der DB Löschen.

**Comment by leofeyer** [comment]
Der vorgesehene Weg ist, dass Du Dich als der jeweilige Frontend-Benutzer anmeldest und dann die 2FA-Einstellungen anpasst.

<img width="426" alt="" src="https://user-images.githubusercontent.com/1192057/85700085-572f4f00-b6dc-11ea-98e8-4911077ad92f.png">

**Comment by Georg-Git** [comment]
Wenn ich 2FA Zwang für Frontend User konfiguriert habe, wird der Button zur Deaktivierung von 2FA nicht angeboten - Dein Weg ist also nicht die Lösung für meinen Request.

**Comment by leofeyer** [comment]
Da hast Du Recht. @bytehead Wie hatten wir uns das denn gedacht?

**Comment by bytehead** [comment]
Wenn 2FA erzwungen wird, dann darfst du es nicht deaktivieren können. Und eine Reset-Möglichkeit gibt es bis anhin meines Wissens noch nicht.

**Comment by leofeyer** [comment]
Die bräuchten wir aber wohl in dieser Konstellation. Eventuell könnten wir erlauben, dass ein Benutzer 2FA trotz 2FA-Zwang deaktiviert und dann direkt wieder zur Aktivierung umgeleitet wird?

**Comment by bytehead** [comment]
Wir müssen es erlauben. Umgehen kann man damit den 2FA-Zwang nicht, da wie du schon sagst, der Redirect auf die 2FA-Konfigurationsseite geschieht, sobald ein neuer Login stattfindet.
