### ISSUE TITLE
downloads element not accepting new files written by NC 

### ISSUE THREAD

**Issue by Ernestopheles** [contao/contao#1853]
Contao 4.9

Downloads element showing to a directory /files/dir/. 

Adding files to dir/ by notification center (.txt)

Downloads does not integrate these new files to it's list. New files will not be shown on side.

If new files being dragged and dropped in filemanager hence and forth, downloads will integrate them.

Maybe a bug of NC? Or of Contao?

**Comment by fritzmg** [comment]
If you selected a folder in the downloads element, then the element will only show files that have been added to the DBAFS (`tl_files`). Presumably, the NC does not add the generated file to the DBAFS.

**Comment by Ernestopheles** [comment]
Yes, that is the case. I will move this issue to NC then

**Comment by Ernestopheles** [comment]
[https://github.com/terminal42/contao-notification_center/issues/214](url)
