### ISSUE TITLE
Downloads element not removing deleted files from its list

### ISSUE THREAD

**Issue by Ernestopheles** [contao/contao#1854]
Contao 4.9

Downloads element showing to a directory /files/dir/.

Manually deleting files in filemanager from dir/

Downloads still having all files in it's list. All files will be shown on side, deleted ones with 0 Byte.

**Comment by fritzmg** [comment]
I cannot reproduce the problem in Contao 4.9.3.

**Comment by Ernestopheles** [comment]
If I click "synchronize" the problem vanishes.

**Comment by fritzmg** [comment]
Are you sure you deleted the file via the file manager in the back end and not through other means?

**Comment by Ernestopheles** [comment]
Testing it now does not show any misbehaviour. Not sure why, did system maintenance in between, perhaps s.th. having being inconsistent before.

**Comment by Ernestopheles** [comment]
I will reopen if I experience the problem again
