### ISSUE TITLE
Keine default Template-Auswahl beim Anlegen von Inhaltselementen

### ISSUE THREAD

**Issue by kreativsoehne** [contao/contao#1857]
**Affected version(s)**

Contao 4.9.3

**Description**

Nach dem Update von Contao 4.9.2. auf Contao 4.9.3 gibt es im Backend beim Anlegen von Inhaltselementen nur noch die Option auf abgeleitete Templates im eigenen Theme-Ordner zuzugreifen.
Hier am Beispiel einer Überschrift zu sehen.
Es wird kein default-Inhaltselement mehr zugelassen bzw. zur Auswahl bereitgestellt.
Auch der Versuch "ce_headline" manuell zu suchen bzw. anzugeben scheitert und führt zu keinem Ergebnis.

<img width="920" alt="Bildschirmfoto 2020-06-22 um 15 27 40" src="https://user-images.githubusercontent.com/2213199/85292986-ffef6b80-b49c-11ea-9121-53375e70131d.png">

**Comment by fritzmg** [comment]
According to your screenshot, you are using a PCT theme. This is a known issue with their extensions. Please contact PCT for support.
