### ISSUE TITLE
UX - improve handling of conditional mandatory fields

### ISSUE THREAD

**Issue by asaage** [contao/contao#1859]
There is one thing which bothers me a long time already and i dont' know a propper solution, that is applicable in the BE.
Whenever there are checkboxes in the BE wich cause mandatory additional fields to appear in the palette the state of this item is kind of stuck.
Let's name the ```Add an image``` or ```Protect element``` checkboxes for exampple in tl_content (there are a lot more).
![image](https://user-images.githubusercontent.com/4138336/85300921-77c29380-b4a7-11ea-897d-47442ea4c308.png)
Once an image is added there is no way of removing it from the datarecord.
You can deselect but then you won't be able to save.
You can deselect and uncheck ```Add an image``` / ```Protect element``` but the next time i check ```Add an image``` or ```Protect element``` i see my old entries. That's not always a bad thing but sometimes really annoying.
Maybe someone has an idea how to make this possible.

**Comment by netzarbeiter** [comment]
Do you now the way with "Reset selection"?

![Reset-selection](https://user-images.githubusercontent.com/1942550/85380545-58764580-b53d-11ea-93db-2daece33e24f.png)

**Comment by fritzmg** [comment]
Reproduction:

1. Create a new `text` content element.
2. Check __Add an image__.
3. Choose an image and save.
4. De-select the image.
5. Uncheck __Add an image__ and save.
6. Recheck __Add an image__.

The previously selected image will still be selected, even though the image had been deselected before. This is because unchecking __Add an image__ also removes the image selection, thus the unselected image is never sent in the POST request.

**Comment by asaage** [comment]
> Do you now the way with "Reset selection"?

Absolutely - but you won't be ble to save that because a selection i mandatory as soon as **Add an image** is checked and you won't be able to "Reset selection" if **Add an image** is unchecked.

I did open this as a FR and not necessarily as a bug because i always considered this a known limitation.
Maybe a *submit-on-change* for the mandatory fields in question could eliviate this problem but i'm
a) not sure if that would trigger the form-validation error regardless
b) not the biggest fan of *submit-on-change* either

From my inspections the subpalette will be injected into the markup by the time you check **Add an image** but wont' be removed (just hidden) if you uncheck again. So maybe it's even possible to add that to the POST request.??

**Comment by leofeyer** [comment]
I fail to see the problem here. Either you want to add an image, so you enable the checkbox and select an image (mandatory field), or you do not want to add an image, so you disable the checkbox. Contao does not care if the `singleSRC` column is empty or not – unless you enable the "Add an image" checkbox, no image will be added.

**Comment by asaage** [comment]
It's not a Problem in the FE.
It just happens, that in the designprocess i fiddle a lot with placeholder-images or experiment with protection settings an often do copy elements and decide to change the type later on.
 Like text with added image vs. text and separate image or protected elements vs. protected articles.
When the customer later decides to change things on his own there might be cases where i don't want to cause confusions because he might think that i made a preselection while in reality it was just a leftover.
Feel free to label it up "up for discussion" or close it right away if you think it's totally unneccessary.
I can run a couple of mysql-statements to clean up (but admittedly have trashed a bunch of elements doing so in the past).

**Comment by m-vo** [comment]
That's a limitation of the current DCA/shared model concept. We're running over this issue all the time but I think we cannot change anything. 

It's also a feature btw (think switching between content elements and reusing input fields or accidentally clicking on a checkbox), so it's not even 100% clear what the intended behavior should be.

**Comment by asaage** [comment]
alright...
🤦‍♂️
I still think it's bit weired to present a "Reset Selection" radio-btn - then you can hit "Apply" but then you cannot "Save".
