### ISSUE TITLE
Deprecations vs. functional testing

### ISSUE THREAD

**Issue by m-vo** [contao/contao#1860]
While building functional tests for #1753 I noticed I cannot test legacy code paths that trigger an `E_USER_DEPRECATED` error type. They will fail  with exit code 1 due to remaining 'self deprecation notices'.

Probably because of the deprecation helper in place it's not possible to use `$this->expectDeprecation()` in the tests (PHPUnit reports `Failed asserting that exception of type "PHPUnit\Framework\Error\Deprecated" is thrown.` then).

In my use case I'm explicitly testing against the old code in order to replace it with functional identical new code, so the errors will disappear (&rarr; this is only working if it's done inside the same PR). But I'm wondering if we should loosen the constraints for the functional tests or have another 'legacy functional testsuite'. Besides working in smaller steps this would also enable us to reuse the tests in the LTS versions.

**Comment by leofeyer** [comment]
This will help:

```php
/**
 * @group legacy
 *
 * @expectedDeprecation Defining the "prepend_locale" parameter in the parameters.yml file %s.
 */
```

**Comment by m-vo** [comment]
Nice. Adding the 'legacy' group via annotation does the trick. 

Is this something the deprecation helper is reading (the annotations)? Because apparently it does not work the programmatic way via `$this->setGroups()` which I tried before :smile: ...
