### ISSUE TITLE
List of bugs/quirks in Controller::addImageToTemplate

### ISSUE THREAD

**Issue by m-vo** [contao/contao#1862]
**Affected version(s)**
Contao 4.4 ./ 4.9

**Description**
The current implementation of `Controlller::addImageToTemplate()` contains some bugs + quirks. I'm collecting these in this *meta/documentary issue* while writing tests for #1753 (intended to replace the logic) so that we can decide later on which ones we possibly want to fix for 4.4/4.9. 

### Issues
* [ ] bad array access / `$imgSize` can be `false`
https://github.com/contao/contao/blob/9736169f50c2729cf291853328a73e649f0d5de5/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1535
https://github.com/contao/contao/blob/9736169f50c2729cf291853328a73e649f0d5de5/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1560-L1561

* [ ] inconsistent template vars/defaults (empty string/null/not present) depending on preconditions
   compare `linkTitle`,  `imageTitle`, `imageUrl`, `href` ...

* [ ] meta data (partially) not present in the output if `overwriteMeta` is set but no `FilesModel` specified
   `alt` and `title` are still in the `picture` array but not in the 'root' - in other words: overwriting meta data does not work if no `FilesModel` is set; **however**: setting `imageUrl` still has an effect :shrug: :confused: &larr; this does not check if overwriteMeta is actually set or not

* [ ] setting/picking a `{{file::uuid}}` as url (meta data) + enabling light box/fullsize does not create a light box from the resource
  instead it's treated as a link (fullsize)

* [ ] invalid resources (i.e. tl_file entry pointing to a non-existing file) result in a broken (obviously) and incoherent (some values null, others empty, others missing) template set but still contain meta data

* [ ] external resources should always contain the link attribute `rel="noreferrer noopener"`
  currently that's only the case if *no* light box attribute is created

* [ ] `$arrMeta` is not guaranteed to contain keys that are accessed (e.g. if tl_files.metaFields is changed)

* [ ] bad array access (e.g. `imageTitle` which was unset before)
https://github.com/contao/contao/blob/8e364e7574063a55f0db5d9842b94d6fd1f7bc8d/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1802-L1805
  this results in a `null` value due to not being in strict mode...

* [ ] "Move the title to the link tag so it is shown in the lightbox" isn't consistent - it should imo always be the case as soon there is a link set (no matter light box or external) but currently depends on the `$arrItem` preconditions

* [ ] a (file) insert tag in the url should be resolved beforehand, so that the output of `href` is consistent - now it can also be the (yet unresolved) insert tag

* [ ] setting an `imageUrl` to `''`  vs. `'foo`  makes a difference if the `$picture['title']` attribute is defined or not - 

* [ ] using `$intMaxWidth` with a `PictureConfiguration` does not fall back to using the original size (&larr; obviously because it cannot be easily altered but would need to regenerate the image)

* [ ] ...

*Disclaimer: this is a work in progress.*

**Comment by Toflar** [comment]
@m-vo do you still intend to work on it or do we want the stale bot to close the issue?

**Comment by m-vo** [comment]
:smiley: 

Not really tbh.

I made this list to help me through the refactoring madness. As these are all things that were a problem (or actually weren't because people got used to it) all the time, I think it's fine to close it. It's still here in case we ever need it.
