### ISSUE TITLE
4.4.49: Fehler/Warning beim Löschen von Datensätzen in Contao\Database\Result (array_key_exists)

### ISSUE THREAD

**Issue by webdecker** [contao/contao#1867]
**Affected version(s)**

Contao 4.4.49 (nach Upgrade von 4.4.47)
Contao 4.4.49 Core only

**Description**

Beim Löschen von Elementen mit Eltern-Bezug (z.B. Inhaltselemente, Newsletter-Abonnenten) wird die Warnung erzeugt:

Warning: array_key_exists() expects parameter 2 to be array, null given
in vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Result.php (line 181)

Das Problem ist an sich nur ein Problem, wenn display_errors On ist (und dann die Warning-Seite zeigt), was bei app_dev.php der Fall ist und dann verwirrt/den Prozess stört, oder beim Provider nicht-überschreibbare Grundeinstellung sein könnte (Host Europe z.B.).
Das Ganze zeigt eine kleine Schwachstelle und einen kleinen wirklichen Fehler (Ursache). 

1. In Contao\Database\Result Zeile 181 steht:

if (\array_key_exists($strKey, $this->resultSet[$this->intIndex]))

Hilfreich wäre hier 
if ( \array_key_exists($this->intIndex, $this->resultSet) &&  \array_key_exists($strKey, $this->resultSet[$this->intIndex]))
damit's eben keine Warning gibt, wenn das Result set leer ist.

2. In Contao\Backend Zeile 515 steht ein select, das offenbar den Parent-Datensatz (Artikel, NL-Channel) holen soll (config's ptable), es aber mit der ID des eben gelöschten Datensatzes tut (dc->id).
Daher ist im Result das Result set leer und die Warning kommt.

Also, ist eigenlich / vielleicht unwichtig, wollte es mal erwähnt haben, vielleicht zieht sich das auch in 4.9 durch und macht eines Tages anderweitig Probleme...

Viele Grüße

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/contao/pull/1741

**Comment by webdecker** [comment]
Ah, okay, hatte ich nicht gefunden / gesehen. Danke!

Wobei o.g. Punkt 2 aber noch als eigentliche Ursache bleibt, ohne jetzt zu wissen, welche Relevanz die besagte Stelle hat ("Add the name of the parent elements"). Könnte falsche Ergebnisse liefert, falls die IDs tatsächlich mal passen...
