### ISSUE TITLE
Also mark current events in the event reader

### ISSUE THREAD

**Issue by xchs** [contao/contao#187]
**Description**  

Events of the **current day** are marked in the event list with the CSS class `current`. Could we also output this class in the event reader?

**Example**  

* Log into the Contao Official Demo
* Create a new event in the _"Contao Public Example Events"_ calendar and set the start date to the current day
* Open the front end page https://demo.contao.org/en/events.html and compare the CSS classes in the event list and event reader module, respectively

**Comment by leofeyer** [comment]
You mean the CSS class should be `event layout_full current block`? What do you need this for?

**Comment by xchs** [comment]
> You mean the CSS class should be `event layout_full current block`?

Yep, exactly.



> What do you need this for?

I would like to style these events differently in the list view as well as in the reader.

I was just wondering why this class only exists in the event list module and not also in the event reader. 
Maybe there is a good reason why this CSS class cannot be shown in the reader as well (?).

**Comment by leofeyer** [comment]
Implemented in d0acba77a586243068595fd95b799965391690aa.
