### ISSUE TITLE
Using a dca picker to link a file in a tinymce textarea leads to the generated inserttag being replaced

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1874]
**Affected version(s)**

Contao 4.4 (4.9 not tested)

**Description**

When I select a file using the dcaPicker in a tinyMCE the `{{file::uuid}}` insert tag is created properly. But after saving the field, the insert tag gets replaced which shouldn't be the case because now the link isn't safe when the file is being moved using the file manager.

Is that a bug or intentionally? For pages and news the handling is correct, i.e. the insert tag survives the saving in the tinymce.

Thanks!

**Comment by leofeyer** [comment]
It is only replaced in TinyMCE, so it can render the image. The database value remains unchanged.

**Comment by Defcon0** [comment]
Wow, didn't know that. Awesome :)
