### ISSUE TITLE
Model liefert int immer als string

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#1876]
**Affected version(s)**

Contao 4.9

**Description**

Model liefert INT-Felder immer als String aus und deswegen ist in der Bundle-Programmierung immer ein CAST notwendig!
Das Problem liegt an Doctrine, aber ist das so gewollt!? Problem scheint ja im Doctrine bekannt zu sein.
Sehr whrscheinlich hängt es aber auch von der installierten php_mysql-Version vom Server ab!

Laut I-Net könnte man es folgendermaßen einstellen:

`doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                options:
                    20: false`

Frage: Ist das so im Contao gewollt bzw. bekannt?

Danke und Grüße

EDIT:
Fällt eigentlich nur auf wenn man über declare(strict_types=1); versucht Typsicher in PHP zu programmieren :-)

**Comment by m-vo** [comment]
Das liegt an den Models (die Typen nicht wirklich kennen), nicht an Doctrine...

Aber eine `Model#getId(): int` bzw.  `Model#getPk(): int` fände ich auch schön. :smiley: (wenn das in allen Fällen denn immer stimmt)

**Comment by xprojects-de** [comment]
:-) Noch schöner wären natürlich sogar Entities welche man qausi dem Model optional als Skeleton mitgeben könnte! So würde aus dem dynamischen Model, welches ja quasi wirklich prinzipiell schon eine Entity ist, ein typsicheres Entity.
Vielleicht ja in der Zukunft :-) Ist ja nicht so trivial durch die Dynamik der User-Bundles!

Zurück zur Frage: Gibt es zu obigem Beispiel schon Ideen?

Edit: 
Gerade gelesen: https://contao.org/de/news/rueckblick-auf-das-erste-core-entwicklertreffen-2020.html
Cool! Da kommt ja was :-)
