### ISSUE TITLE
Contao 4.9 and InnoDB: SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large.

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#1882]
**Affected version(s)**

Contao 4.9

**Description**

I just upgraded a contao 3.5 system to 4.9 which worked great so far!

Now I tried to install some extensions and I get the following error:

```
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
```

I know the rowsize is limited, but the limit seems to be way smaller for InnoDB compared to MyISAM. I have a system way larger than the one mentioned above and there we have 490 columns in tl_module compared to 388 in the Contao 4.9 system at the moment.

In the MyISAM system no problems occurred even with larger number of columns. I know, it's not the number but the size. But since we have installed very much the same extensions (even less in the 4.9 system) without an issues in the 4.4 system.

Is it possible that the limit is smaller in the InnoDB system? Could it be a misconfiguration in my local MySQL? I use

`mysql  Ver 14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper`

in Linux Mint 19.1.

Did you also experience this issues in larger systems?

The interesting thing is that I made ~30 fields smaller of size, applied the changes and then tried to add a new field with being only a CHAR(1) which was **also** not possible. So it seems it's more the number of columns but the total size although the error message states something different.

Any help/opinion is highly appreciated!

Bye Defcon0

**Comment by leofeyer** [comment]
Here are two good reads:

* https://dev.mysql.com/doc/refman/8.0/en/column-count-limit.html
* https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/

**Comment by Defcon0** [comment]
OK, then we'll have to refactor some of our modules to store into a separate table instead of `tl_module`. As a workaround we switched to MyISAM using https://docs.contao.org/manual/de/installation/systemvoraussetzungen/#mysql-mindestanforderungen

**Comment by fritzmg** [comment]
> OK, then we'll have to refactor some of our modules to store into a separate table instead of `tl_module`.

You could also reduce the size of individual fields, if possible.

Also, in some cases it helps (for some reason) if you execute each `ALTER TABLE`  query individually.

**Comment by Defcon0** [comment]
I did that already. Nevertheless I had no good feeling about reducing the size of some of the fields...

> The interesting thing is that I made ~30 fields smaller of size, applied the changes and then tried to add a new field with being only a CHAR(1) which was also not possible. So it seems it's more the number of columns but the total size although the error message states something different.

**Comment by m-vo** [comment]
This sounds like *a lot* of columns. Do you really need every single one to be individually searchable? You could either only store a reference to another table or serialize data (&larr; this is indeed not an antipattern if it is only ever used together).

**Comment by fritzmg** [comment]
Btw. related to or duplicate of https://github.com/contao/core/issues/7313 ;)

**Comment by m-vo** [comment]
By the way: There is a limit on how big a row can get independent of the storage engine - so it might only be a matter of time until you run into this (sth. around 64KB IIRC). Changing fields to referenced types (e.g. TEXT) could probably  help.

**Comment by fritzmg** [comment]
@Defcon0 you could provide a PR for `DC_Table`, so that fields can be defined as `virtual` or something and don't have their own SQL definition. Instead, they'll be serialized as a JSON object into one single field. Not an easy task though probably ;)

**Comment by Defcon0** [comment]
@m-vo As mentioned earlier, we already transformed nearly all of our modules like list bundle, filter bundle or reader bundle to have their config in their own table so we don't run into this problem.

But you're right. In fact not every field needs to be in a separate column. But it's best practice for performance reasons of course. `LIKE`ing a serialized column is slower that an oradinary one.

I know for MyISAM the limit also persists but as mentioned in the first post, we have the same bundles and many more in a way larger project and here we don't have any issues. So I guess, the limit is somehow way lower in InnoDB.

After I switched to MyISAM, it worked again. On the long run we'll have to fix the "problem" that we added many fields to tl_module in the old modules.

**Comment by leofeyer** [comment]
Have you tried increasing the `innodb_page_size` value?

**Comment by Defcon0** [comment]
No, because I thought I likely might not be able to change that in a live environment, am I?

**Comment by leofeyer** [comment]
True. The server admin would have to change this.

**Comment by Defcon0** [comment]
So this is actually not an option sadly. Ok, I guess all is said concerning this problem. Thanks for the help!
