### ISSUE TITLE
Check if DCA indexes are configured correctly

### ISSUE THREAD

**Issue by ausi** [contao/contao#1885]
@leofeyer https://github.com/contao/contao/pull/1679#discussion_r445514095 :
> I just figured because we are using indexes that span multiple columns quite often:
> 
> https://github.com/contao/contao/blob/8e364e7574063a55f0db5d9842b94d6fd1f7bc8d/core-bundle/src/Resources/contao/dca/tl_page.php#L63-L69

@ausi https://github.com/contao/contao/pull/1679#discussion_r445529262 :
> `'pid,type,start,stop,published'` seems wrong to me. The order would have to be `'pid,type,published,start,stop'` I think because start/stop are queried as ranges and not as exact values.

**Comment by aschempp** [comment]
be aware that some of these originate from the routing component, so you might want to check that code

**Comment by leofeyer** [comment]
Original issue: https://github.com/contao/core/issues/7450
@KaiserCh /cc
