### ISSUE TITLE
Reconsider redirects with status code 302

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1887]
**Affected version(s)**

Contao 4.4

**Description**

As discussed in https://github.com/contao/contao/pull/1762#issuecomment-651129888, we should check all places where we currently use a 302 redirect and replace it with 307 if applicable.

**Comment by fritzmg** [comment]
Don't you mean `303` or both?

**Comment by leofeyer** [comment]
Both. (But we are using `302` a lot more than `303`.)

**Comment by fritzmg** [comment]
> (But we are using `302` a lot more than `303`.)

I don't think so actually, since `Controller::redirect` is executed without its second argument a lot more. And that's a `303` redirect :). In fact, I can only find one `302` instance.

**Comment by leofeyer** [comment]
All `Page*` classes either use 301 or 302 redirects. And all the `getRedirectStatusCode()` methods do `return ($objPage->redirect == 'temporary') ? 302 : 301`.

But it does not matter anyway. We have to check all 302 and 303 redirects.
