### ISSUE TITLE
Secure target="_blank" with additional rel attribute

### ISSUE THREAD

**Issue by Shoekrates** [contao/contao#189]
**Description**  
In Contao it is relative easy to open a link in a new window, e.g. by checking “Open in new window“ in a hyperlink CE.
It would be more secure to add the attribute rel="noopener" as well when editor chooses to open a link in a new window. This could be added automatically or with an additional (conditional) input field for the rel attribute.

More information:
https://mathiasbynens.github.io/rel-noopener/
https://developers.google.com/web/tools/lighthouse/audits/noopener

**Example**  

Markup should be:
`<a href="domain.de" target="_blank" rel="noopener">`

**Comment by fritzmg** [comment]
Should already be the case in Contao 4.6. Duplicate of https://github.com/contao/core-bundle/issues/1125

**Comment by Shoekrates** [comment]
Ah, sorry. I used the issue search but this didn't show up. Feature request can be closed then. Thanks!

**Comment by fritzmg** [comment]
Well, the mono repository is still pretty new, currently you have to search in the bundle repositories as well ;)
