### ISSUE TITLE
Kategorisierung im CSS-Editor

### ISSUE THREAD

**Issue by simon-1977** [contao/contao#1901]
**Affected version(s)**

Contao 4.9.3

**Description**

Sind die CSS-Elemente kategorisiert und ein Filter auf die Kategorie gesetzt, dann wird die Kategorie beim Anlegen eines neuen Elements nicht übernommen.

**Comment by leofeyer** [comment]
Der CSS-Editor ist veraltet und wird nicht mehr weiter entwickelt.

<img width="1026" alt="" src="https://user-images.githubusercontent.com/1192057/88381141-1f342e00-cda6-11ea-8f95-6489c19b33c8.png">
