### ISSUE TITLE
Firefox: Cookie “BE_PAGE_OFFSET” wird in Zukunft bald abgelehnt werden

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1906]
**Affected version(s)**

 Contao 4.9.3

Firefox 78

**Description**
Backend von Contao aufrufen. (Nachvollziehbar in der Contao Demo)

Aus der Konsole vom Firefox:

Das Cookie “BE_PAGE_OFFSET” wird in Zukunft bald abgelehnt werden, da es für das Attribut "sameSite" entweder "none" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "sameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

![grafik](https://user-images.githubusercontent.com/1645099/86520867-89ae1a00-be49-11ea-9c93-0db1a06c62a2.png)

**Comment by fritzmg** [comment]
Duplicate of #1760
