### ISSUE TITLE
Extend HTML module with CSS class + ID

### ISSUE THREAD

**Issue by math-GH** [contao/contao#1907]
**Affected version(s)**

all Contao versions

**Description**
insert module (module = html code).
![grafik](https://user-images.githubusercontent.com/1645099/86520986-0097e280-be4b-11ea-986c-7c018f3e2837.png)

The given CSS class and ID will not inserted into the frontend.

So the mod_html.html5 template should be extended to take care of the class+ID.

I suggest:
![grafik](https://user-images.githubusercontent.com/1645099/86520967-cdedea00-be4a-11ea-989c-d7e28ebea792.png)

**Comment by ausi** [comment]
This would break all use cases for seperate opening and closing HTML-elements (e.g. one element to open a `<div>` and one to close `</div>`). If you want to use a CSS class or ID you should set dem directly in the HTML-Code itself.

**Comment by fritzmg** [comment]
Yeah, this is intentional. You can still use the variables in your own `mod_html(_*)` template(s).
