### ISSUE TITLE
Add missing translation for Czechia in cs-CZ

### ISSUE THREAD

**Issue by rabauss** [contao/contao#1925]
**Affected version(s)**

Contao 4.4 and Contao 4.9

**Description**

The cs-CZ translation for `CNT.cz` is missing - see:
https://github.com/contao/contao/blob/4.4/core-bundle/src/Resources/contao/languages/cs/countries.xlf#L224

Should be replaced by:
```xml  
<trans-unit id="CNT.cz">
    <source>Czechia</source>
    <target>Česká republika</target>
</trans-unit>
```

**Comment by leofeyer** [comment]
The missing translation needs to be added on transifex.com and will then be included in the next release.
