### ISSUE TITLE
No cache headers in back end responses

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#1928]
**Affected version(s)**

Contao 4.9

**Description**

In Contao 4.4, any back end request also returned the following headers:

```
Cache-Control: max-age=0, must-revalidate, private
Expires: Fri, 10 Jul 2020 12:56:44 GMT
```

(`Expires` will always be the current time). In Contao 4.9 however, this is not the case any more. This in itself is not problematic, but it breaks the back end, if someone happens to have

```
ExpiresByType text/html "access plus 6 hours"
```

in their `.htaccess`, since this causes the back end requests to be cached by the browser for the configured time.

Shouldn't we disallow caching of back end responses in the private cache with the appropriate response headers? Quite a few users in the Contao community already stumbled over this issue.

**Comment by Toflar** [comment]
I don't think this makes sense. We do disallow caching by setting `max-age=0` and `private` but `Expires` takes precedence for BC reasons. That's why browsers correctly take the `Expires` setting in this case. 
Adding
```
ExpiresByType text/html "access plus 6 hours"
```

to your `.htaccess` is pretty nonsense anyway. It will also affect the FE caching. Basically it affects everything.
Make sure you get your server settings right - it's a server issue, not a Contao issue. We are not supposed to try to fix those because there are a hundred million things that can go wrong in your server config.

**Comment by fritzmg** [comment]
> We do disallow caching by setting `max-age=0`

We do? I don't see it in the responses from the back end.

```
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Date: Fri, 10 Jul 2020 13:33:16 GMT
Contao-Merge-Cache-Control: 1
x-powered-by: PHP/7.3.18
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer-when-downgrade, strict-origin-when-cross-origin
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Cache-Control: private
Contao-Cache: miss
```

But since `Expires` takes precedence, it wouldn't matter anyway.

> We are not supposed to try to fix those because there are a hundred million things that can go wrong in your server config.

I do agree with that. It's just that the issue is fairly common, so may be this is just an issue of documentation.

**Comment by Toflar** [comment]
The back end controller should of course send `max-age: 0`. That should be fixed but not sure this would solve the misconfiguration anyway.

**Comment by fritzmg** [comment]
I think we currently do not set any `Cache-Control` header for the back end actually. Not sure why I had `Cache-Control: private` in my example.

**Comment by Toflar** [comment]
Because Contao turns all responses with cookies into `private` ones.

**Comment by fritzmg** [comment]
Ah yes, but only in `prod` it seems, not in `dev`.

**Comment by maniaxatwork** [comment]
I hope i am right here. 
A customer called me, that he isn't able to log out from the backend.
It is interesting. I have tried it, too. But for the first logout, everything is fine, but if i log in and do the logout again, i'll be forwarded to the Contao Dashboard.

The response is following:
`
set-cookie: PHPSESSID=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
set-cookie: contao_settings=deleted; expires=Mon, 21-Oct-2019 06:38:12 GMT; Max-Age=0; path=/; httponly
`

Is it just me, with this error?
I also have this in my .htaccess
`ExpiresByType text/html "access plus 6 hours"`

**Comment by fritzmg** [comment]
> I also have this in my .htaccess
> `ExpiresByType text/html "access plus 6 hours"`

You need to remove that.

**Comment by maniaxatwork** [comment]
> 
> 
> > I also have this in my .htaccess
> > `ExpiresByType text/html "access plus 6 hours"`
> 
> You need to remove that.

The whole part of the Expires block?
I'm sorry for asking, but i just enter those lines, because of PageSpeed optimization. I took it over from Contao 4.4

**Comment by fritzmg** [comment]
Just

```
ExpiresByType text/html "access plus 6 hours"
```

> I took it over from Contao 4.4

Yeah, in Contao 4.4 this was not a problem.

**Comment by leofeyer** [comment]
As discussed in Mumble on October 22nd, we want to add `$response->headers->set('Cache-Control', 'no-cache, no-store');` in the `BackendTemplate::getResponse()` method, similar to

https://github.com/contao/contao/blob/de9872d6edb9bbec0d7b626c0417ee8a07cd2094/core-bundle/src/Resources/contao/classes/FrontendTemplate.php#L82-L94

but not limited to `be_` templates.

**Comment by Aybee** [comment]
Had the same problem. I removed 
`ExpiresDefault "access plus 1 month"`
from my htaccess. This seems to help.

**Comment by fritzmg** [comment]
@Aybee you should create a separate issue about this.
