### ISSUE TITLE
Model::createModelFromDbResult beachtet nicht $GLOBALS['TL_MODELS']

### ISSUE THREAD

**Issue by webdecker** [contao/contao#1929]
**Affected version(s)**

Contao 4.4 (Contao 4.9?)

**Description**

Von Model::createModelFromDbResult(Database\Result $objResult) wird zurück geliefert:
new static($objResult);

Konsequenterweise müsste m.E. etwas zurück geliefert werden wie:

$strClass = \Model::getClassFromTable(static::$strTable); 
return new $strClass($objResult);

Denn sonst nützt es nichts, wenn ich z.B. via $GLOBALS['TL_MODELS']['tl_news'] eine eigene NewsModel-Ableitung definiere, weil ich bei Aufrufen wie 
\NewsModel::findPublishedByParentAndIdOrAlias(...) (vgl. ModuleNewsReader)
doch wiederum ein NewsModel und nicht meine Ableitung bekomme...

**Comment by Toflar** [comment]
Du sollst auch nicht `Model::createModelFromDbResult()` aufrufen, sondern eben `FoobarModel::createModelFromDbResult()`.

Du bist für die Wahl des korrekten Models zuständig. Models lassen sich ja auch aus Arrays bilden, die Klasse kann nicht selber entscheiden, was du haben möchtest.

**Comment by webdecker** [comment]
Hallo,

bitte noch mal genauer anschauen und dann wieder aufmachen... ;-)

Kurz gesagt, es ist m.E. ein Bug im Core, der verhindert, dass ich  `$GLOBALS['TL_MODELS']['tl_news']` sinnvoll nutzen kann.

Es geht nicht darum, dass **ICH** `Model::createModelFromDbResult` aufrufe, sondern dass **Contao** es tut.

Konkret:

Contao `ModuleNewsReader `ruft `\NewsModel::findPublishedByParentAndIdOrAlias()` auf und wenn man den Weg im Code verfolgt, so landet man am Ende in der Klasse Model bei `createModelFromDbResult()`.
Dort wird "`new static($objResult);`" zurück gegeben - ergo eine `\NewsModel`-Instanz, denn es wurde ja vom `\Contao\ModuleNewsReader` eine `\NewsModel`-Methode aufgerufen. 
Diese Stelle ignoriert ein ggf. via `$GLOBALS['TL_MODELS']['tl_news']` konfiguriertes anderes, \NewsModel ableitendes Model!
Während dies an anderen Stellen beachtet wird, so dass z.B. bei News-Listen meine Model-Instanzen zurück geliefert werden.

Falls noch nicht konkret genug: Ich habe den Effekt fest gestellt in einem meiner Contao-4-Projekte, in dem ich sowohl das NewsModel als auch das CalendarEventsModel ableiten und meine Ableitung nutzen will - via config `$GLOBALS['TL_MODELS']['tl_news']` / `$GLOBALS['TL_MODELS']['tl_calendar_events']`.

In den jeweiligen Listen-Modulen werden korrekterweise meine Model-Instanten geliefert und ich sehe in den Listen das, was meine Models produzieren - nehmen wir jetzt mal beispielhaft an, mein Model-Konstruktor hängt an headline bzw. title ein "Hallo" ran., so sehe ich in den Listen bei jedem Item "Hallo".
Aber auf der Detailseite mit den Reader-Modulen werden die \Contao\NewsModel- bzw. \Contao\CalendarEventsModel-Instanzen geliefert, was falsch ist, wenn `$GLOBALS['TL_MODELS']['tl_news']` einen Sinn ergeben soll. Ich sehe kein "Hallo".

Also sollte, wie im Issue oben beschrieben, auch `createModelFromDbResult()` TL_MODELS beachtet werden, sonst ist das Ganze irgendwie sinnlos...

**Comment by fritzmg** [comment]
I do find it inconsistent, that `Model::findBy` (which calls `Model::createFromDbResult`) and `Model::findOneBy` (which calls `Model::createModelFromDbResult` return _different_ model instances. I agree that `Model::createModelFromDbResult` should also consider the registered model type, just like `Model::createFromDbResult` does. However, I suppose this isn't something we can fix in Contao 4 for BC reasons?

**Comment by fritzmg** [comment]
It could also be argued, that it is a bug that `Model::findBy` returns a different model instance than the class it is called for. May be `Model::findBy` should in fact not consider `TL_MODELS`. I think the primary use case of registering model classes in `TL_MODELS` is to figure out the correct model class when you only have the table name.

But within the newslist or newsreader module for example you don't need that, since you already know the correct model class.

Thus being able to _override_ model classes could be considered an inconsistent side effect.

**Comment by aschempp** [comment]
I think the issue would be that the news module(s) do not use the class from the global registry in the first place?

**Comment by fritzmg** [comment]
@aschempp they don't do themselves, but the news list module will return instances of the registered model, while the newsreader does not. Simply because that's how the model methods `findBy` and `findOneBy` currently work. The former will always return the registered model while the latter will not.

**Comment by webdecker** [comment]
Thank you for re-opening and discussing.
Yes, I think as well, it is inconsistent, that findBy and findOneBy (may) return different model classes.
The most consequent solution would be that createModelFromDbResult() respects TL_MODELS - or, as @fritzmg states, that no method except from getClassFromTable() would respect it.
But that would be sad because it is such a cool feature!
I understand that it might feel too spooky to change a central core method like createModelFromDbResult(), though it looks like it would make no difference for anyone except from me and my project...

Independent of the concrete Model/createModelFromDbResult solution another "not dangerous" solution would be, that the news and event modules (and faq, ...) would respect the registered model class(@aschempp I think this is what you meant?).
E.g. like this:


return \NewsModel::countPublishedByPids($newsArchives, $blnFeatured);
==>
$strClass = \Model::getClassFromTable('tl_news');
return $strClass::countPublishedByPids($newsArchives, $blnFeatured);
		

return \NewsModel::findPublishedByPids($newsArchives, $blnFeatured, $limit, $offset);
==> 
$strClass = \Model::getClassFromTable('tl_news');
$objItem = $strClass::findPublishedByPids($newsArchives, $blnFeatured, $limit, $offset);


$objArticle = \NewsModel::findPublishedByParentAndIdOrAlias(\Input::get('items'), $this->news_archives);
==> 
$strClass = \Model::getClassFromTable('tl_news');
$objArticle = $strClass::findPublishedByParentAndIdOrAlias(\Input::get('items'), $this->news_archives);

One or both solutions in version 4 would be really really cool...!

**Comment by leofeyer** [comment]
As discussed in Mumble on July 30th, we want to adjust the `Model::createModelFromDbResult()` method and replace `return new static($objResult)` with

```php
/** @var static $strClass */
$strClass = static::getClassFromTable(static::$strTable);

return new $strClass($objResult);
```
