### ISSUE TITLE
Sitemap location

### ISSUE THREAD

**Issue by rburch** [contao/contao#193]
I tend to work with a few SEO and marketing firms. They don't like that Contao puts the sitemap xml files in the share folder. They think it should be in the root. I've done some research on this and it seems that the correct way to do it is have the sitemap in a folder names after the pages you want mapped. So of example /child/ would only index the pages in the child. So that would indicate that a site-wide site map should be in the root. Others say it doesn't matter where it is but there should be a redirect from domain.com/sitemap.xml to whatever the location of the file is so that bots can find it. Does anyone know how this should be set up. Should Contao do it differently?

**Comment by asaage** [comment]
I use https://github.com/terminal42/contao-url-rewrite
and do redirect ```sitemap.xml → share/{{env::host|standardize}}.xml, 301``` while naming my sitemap files like the domain of each root-page.
I do something similar to robots.txt ```robots.txt → files/robots/{{env::host|standardize}}.txt, 301``` and specify the stitemap inside there as well.
Google does not complain about that.
You could use this also for favicons  and apple-touch-icons

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/core/issues/8728
