### ISSUE TITLE
Contao - Installation-Bundle - Database - Installer vs. MySQL VIEWs

### ISSUE THREAD

**Issue by xx81** [contao/contao#1934]
**Affected version(s)**

Contao 4.4 or Contao 4.9?

**Description**

Hi everybody, this is not mainly a bug, but something that may be occur if you are using MySQL VIEWS for Sharing Tables.

What has happend:
On an Installation there are 2 Contao Installations which sharing specific tables. This is done by a MySQL VIEW, so that both installations have access to the same data.

What is the Problem:
In the contao\installation-bundle\src\Database\Installer.php on Line 251 is made a check for the engine:

```
// The table does not yet exist
            if (false === $tableOptions) {
                continue;
            }

            $engine = $table->getOption('engine');
            $innodb = 'innodb' === strtolower($engine);

            if (strtolower($tableOptions->Engine) !== strtolower($engine)) {
                if ($innodb && $dynamic) {
                    $command = 'ALTER TABLE '.$tableName.' ENGINE = '.$engine.' ROW_FORMAT = DYNAMIC';
                } else {
                    $command = 'ALTER TABLE '.$tableName.' ENGINE = '.$engine;
                }

```
The Problem is,that a VIEW has no engine ... so the line with the innodb === strtolower($engine) produces the following error cause $engine is empty:

![image](https://user-images.githubusercontent.com/1532987/87397612-e54c7600-c5b4-11ea-9a7e-e83b4cf851c3.png)

What about implementing a check for a VIEW and if the table is a view do a continue like done on line 246 (The table does not yet exists) ?

I know this is a very specific problem.

**Comment by fritzmg** [comment]
I'd just do this:

```diff
-   if (strtolower($tableOptions->Engine) !== strtolower($engine)) {
+   if (!empty($engine) && strtolower($tableOptions->Engine) !== strtolower($engine)) {
```

// edit, that won't work, the whole if/else needs to be skipped for a view

**Comment by xx81** [comment]
I made a quick change with a "continue statement" for our installations, so that the Installer runs again ... but this is resulting in the following: the installer tries to create the "missing tables" which exists as a view, so you have to do the database update carefully and deselect the CREATE TABLE statements.

**Comment by m-vo** [comment]
possibly related to #1664

So you want to e.g. have `tl_foo` as a read-only table/view that got created outside the application and use it like a regular table.  Do I get your use case right? And is `tl_foo` a DCA/Entity, custom/core?

**Comment by xx81** [comment]
@m-vo Yes you are right ... 

In Contao Installation 1 - its a innoDB Table in DB1 so it worked as expected
In Contao Installation 2 - its a VIEW of the Table in Database 1

**Comment by m-vo** [comment]
And is the table in question from the core or from your code? (And from a DCA or Entity?)

**Comment by m-vo** [comment]
In general I think we could/should support views in the schema diff. That's something that also works if you set up a doctrine entity and later (e.g. for performance reasons) switch out the table for a view.

You would however want to set it up as read-only (`@ORM\Entity(readOnly=true)` and possibly with a private constructor) as a contract to guarantee this *is* actually read-only. We do not have these contracts in the core, so that's something to be warned about at least. :slightly_smiling_face:

**Comment by m-vo** [comment]
(btw.: if your second installation is just a read-only copy you could also setup a second database user with read rights only and use that with the same database)

**Comment by xx81** [comment]
@m-vo 

About your question:
The Table itself is from the DCA ... We created a complete Module and configured / created the table and its fields by the DCA.

Cause we are using the Contao Database-Class/Models we have to use a VIEW so for Contao Core its a "real table".

BTW: Both Contao Installations use CRUD Operations, so there is no need for readonly.

Do u need further information ?
