### ISSUE TITLE
Fehlerhafte Sicherheitsfrage in Kombination mit 404-Weiterleitung

### ISSUE THREAD

**Issue by chiron501** [contao/contao#194]
**Affected version(s)**
4.4.28
PHP 7.1.2

**Description**  
Existiert auf der Startseite (Alias: index.html) ein Formular mit einer Sicherheitsfrage auf dieser eine Weiterleitung einer 404-Seite eingerichtet ist, wird beim Versenden der Formulardaten die Sicherheitsfrage angezeigt. 
Auch wenn die Sicherheitsfrage richtig beantwortet wird lässt sich das Formular nicht absenden. Es wird immer wieder die Sicherheitsfrage angezeigt.
Deaktiviert man die Sicherheitsfrage funktioniert das Formular wie erwartet.
Platziert man das Formular auf einer anderen Seite mit aktivierter Sicherheitsfrage funktioniert das Formular wie erwartet. Platziert man jetzt aber das Formular zusätzlich auf der Startseite funktioniert das Formular auf keiner Seite mehr.

**How to reproduce**  
Seitenstruktur:
- Startpunkt
  |
  - 404-Seite (301 Weiterleitung auf index.html)
  - Startseite (Alias: index; Server- u. Client-Cachezeit: 0)
    |
    - Danke (Weiterleitungsseite Formular)

Formular:
  Textfeld
  Sicherheitsfrage
  Absendefeld

**Comment by fritzmg** [comment]
Ich verstehe dein Setup nicht. Was genau meinst du mit 

> Existiert auf der Startseite (Alias: index.html) ein Formular mit einer Sicherheitsfrage auf dieser eine Weiterleitung einer 404-Seite eingerichtet ist

und

> * 404-Seite (301 Weiterleitung auf index.html)

? Warum genau hast du das so eingerichtet?

**Comment by chiron501** [comment]
Ich habe eine 404-Seite (Seitentyp: 404 Seite nicht gefunden) eingerichtet, die als Weiterleitungsziel die Startseite (index.html) hat.
Ich möchte das alle Fehlanfragen auf die Startseite weitergeleitet werden, dass geht ja nur mit einer eingestellten Weiterleitungsseite beim Seitentyp 404. Oder habe ich da was falsch verstanden?
Auf der Startseite wiederum ist ein Formular platziert mit einer Sicherheitsfrage.

**Comment by fritzmg** [comment]
> Ich habe eine 404-Seite (Seitentyp: 404 Seite nicht gefunden) eingerichtet, die als Weiterleitungsziel die Startseite (index.html) hat.
> Ich möchte das alle Fehlanfragen auf die Startseite weitergeleitet werden, dass geht ja nur mit einer eingestellten Weiterleitungsseite beim Seitentyp 404. Oder habe ich da was falsch verstanden?

Prinzipiell ist das möglich, solltest du aber [niemals machen](https://www.seroundtable.com/google-redirect-urls-home-26270.html). Ich würde ja eigentlich vorschlagen, dass dieses Feature aus Contao entfernt wird ;)

Unabhängig davon: verschiebe die 404 Seite mal an die unterste Stelle innerhalb des Startpunktes. Das sollte zwar (mittlerweile) keinen Unterschied mehr machen, aber vielleicht gibt es doch hier noch ein Problem.

**Comment by chiron501** [comment]
Google ist Google und Kunde ist Kunde, der eine wünscht sich dies der andere wünscht sich jenes ;)

Das verschieben der 404-Seite macht keinen Unterschied. 
Erst wenn ich das explizite Weiterleitungsziel "Startseite" auf der 404-Seite rausnehme, funktioniert das Formular.
Desweiteren tritt der Fehler auch auf, wenn die 404-Seite auf irgendeine beliebige Seite weitergeleitet wird wo ein Formular drauf ist. Das dort platzierte Formular funktioniert dann auch nicht.

**Comment by ausi** [comment]
@chiron501 kannst du einen link zur betroffenen Seite bereitstellen?

**Comment by chiron501** [comment]
http://dev-contao44.ais-work.de
Ist ein geschützter Bereich. Zugang:
Benutzer: zugang
Passwort: nichtfuerdich

Kann Euch auch gerne Zugangsdaten fürs Backend zukommen lassen. Ist aber wie gesagt ein reines Contao was ich heute Früh auf die schnelle Installiert habe.

**Comment by ausi** [comment]
Der Fehler tritt auf, weil beim Aufruf der Seite der Browser versucht die Datei `/favicon.ico` zu laden, die auf die Startseite weiterleitet und dadurch eine neue Sicherheitsfrage generiert.

Du musst entweder ein Favicon hinzufügen, oder sicherstellen dass auf der 404-Seite keine Sicherheitsfrage ausgegeben wird.

**Comment by chiron501** [comment]
Wieso versucht ein "jungfreuliches" Contao ein Favicon zu laden?

**Comment by ausi** [comment]
Das versucht der Browser von selbst, hängt nicht mit Contao zusammen.

**Comment by chiron501** [comment]
Erstmal Danke für die Lösung.
Aber nur zum Verständnis für mich, hab ich eine Formular ohne Sicherheitsabfrage ist das nicht vorhandene Favicon ja kein Problem. Dann werden die Formulardaten ja versendet.
So ganz schuldfrei ist da Contao bzw. die Sicherheitsabfrage nicht oder?

**Comment by fritzmg** [comment]
Es ist so wie @ausi bereits erklärt hat:

1. Du rufst die Startseite auf und für das dort befindliche Formular wird eine Sicherheitsfrage wird generiert.
2. Dein Browser ruft die `/favicon.ico` auf.
3. Da kein `/favicon.ico` existiert, wird die 404 Seite von Contao generiert.
4. Da du bei der 404 Seite von Contao eine Weiterleitung auf die Startseite eingestellt hast, landet der Aufruf der `/favicon.ico` tatsächlich auf der Startseite.
5. Dadurch wird für das Formular auf der Startseite eine neue Sicherheitsfrage generiert und die vorherige ist ungültig.

Auf anderen Unterseiten ist das kein Problem, da die 404 Weiterleitung ja auf die Startseite führt.

**Comment by chiron501** [comment]
Das was @ausi erklärt hat habe ich schon verstanden.
Es existiert aber trotzdem meiner Meinung nach ein Problem.
Mal angenommen ich mache eine ganz normale 404-Seite ohne explizite Weiterleitung. Auf dieser 404-Seite möchte ich gerne ein Formular setzen, damit whatever...
Dann produziert mir irgendeine Ressource, hier jetzt das Favicon, die nicht geladen werden kann ein Problem.
http://dev-contao44.ais-work.de/seite-nicht-gefunden-404.html
Nicht euer ernst?

**Comment by ausi** [comment]
Ja, das ist ein Problem. Allerdings lässt sich das schwer beheben mit der Art wie das Captcha funktioniert.

In Contao 4.6 wurde das Captcha umgebaut damit es ohne Session funktioniert. Dort sollte das Problem nicht mehr auftreten.

Für Contao 4.4 würde ich empfehlen kein Formular auf der 404-Seite zu platzieren, oder darauf zu achten dass keine Requests der Formularseite einen 404-Error erzeugen.

Wenn jemand einen Lösungsvorschlag hat, können wir versuchen das in Contao 4.4 zu beheben.

**Comment by dmolineus** [comment]
> Für Contao 4.4 würde ich empfehlen kein Formular auf der 404-Seite zu platzieren, oder darauf zu achten dass keine Requests der Formularseite einen 404-Error erzeugen.

Das Problem tritt z.B. auch dann auf, wenn ein Ajax-Request auf eine Contao Seite gemacht wird, und in einem Modul nach dem Formular behandelt wird. (Ja, ich weiß, dass es nicht optimal ist über den Seitenbaum zu laufen um einen Ajax-Request zu handeln. Jedoch funktionieren einige Contao Erweiterungen so).

> Wenn jemand einen Lösungsvorschlag hat, können wir versuchen das in Contao 4.4 zu beheben.

Die Frage ist halt, ob die Contao Catch All Route wirklich jede Dateianfrage handeln sollte. Ggf. nur zu reagieren, wenn als Content-Type `text/html` angefordert wird. Oder funktioniert die 404 Behandlung nicht über die Catch All Route?

**Comment by ausi** [comment]
> Ggf. nur zu reagieren, wenn als Content-Type `text/html` angefordert wird.

Das wäre grundsätzlich eine gute Idee denke ich (unabhängig von diesem Issue), allerdings lädt der Firefox (evtl. auch andere Browser) das Favicon leider mit `Accept: text/html,…` wodurch der Fehler weiter bestehen bleiben würde.

**Comment by ghost** [comment]
Ein neues Ticket dazu wurde unter contao/contao#249 angelegt.
