### ISSUE TITLE
Use generics in the Model classes

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1940]
Right now, we are using inline `@var` comments to make PHPStan understand the return value of a model collection. E.g. here:

https://github.com/contao/contao/blob/d4adea42691cde07f813ed3099f6dd13a3740ad7/core-bundle/src/Routing/RouteProvider.php#L493-L494

As discussed in https://github.com/contao/contao/pull/1924#discussion_r455825192, we could improve this with generics, however, we first have to adjust our [Contao PHPStan extension](https://github.com/contao/phpstan) so it understands the `__callStatic` logic.

@m-vo @bytehead /cc

**Comment by m-vo** [comment]
On a sidenote: we might also want to discuss if we want to settle on `phpstan-` or `psalm-` prefixed `@var`/`@return`/`@param` annotations. 

Because (as of now) just replacing the existing annotations with generic/complex ones would degrade most IDE's type inference capabilities.
