### ISSUE TITLE
Disabled icons

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#195]
As you know, Contao uses disabled icons if a function is not available for a user. I had initially designed it this way so the same icons are always underneath each other. However some extensions do it differently, so I wanted to quickly discuss which approach you like more.

**File tree**

<img width="757" alt="" src="https://user-images.githubusercontent.com/1192057/48773204-fd2c0380-ecc6-11e8-8fa5-ce16694b5414.png">

<img width="755" alt="" src="https://user-images.githubusercontent.com/1192057/48773208-00bf8a80-ecc7-11e8-976e-4491ce8dd22e.png">

**Site structure**

<img width="751" alt="" src="https://user-images.githubusercontent.com/1192057/48773056-8858c980-ecc6-11e8-928d-7b18c7ff5709.png">

<img width="752" alt="" src="https://user-images.githubusercontent.com/1192057/48773062-8c84e700-ecc6-11e8-80c5-c59389a573d5.png">

**Comment by OMOSde** [comment]
Für mich wäre jeweils die erste Ansicht die angenehmere. Es wirkt allgemein sauberer, ordentlicher. Außerdem könnte man im Tooltip von ausgeblendeten Icons kundtun, warum die Funktion nicht verfügbar ist.

**Comment by xchs** [comment]
> Für mich wäre jeweils die erste Ansicht die angenehmere.

I feel the same way.

**Comment by pagestyles** [comment]
+1 for disabled icons
-> better UX in my view
-> looks better

**Comment by Toflar** [comment]
I feel the exact opposite. I like the second approach much better and it feels a lot cleaner to me. I also think it's better UX. All of the buttons on the right side are "operations". Operations **do** something. If they are there, they should **do** something. Disabled icons just tell me "if you had the right permissions you could click me" which is not an information a user needs. If that was a good approach we could as well show disabled "System settings" or "System maintenance" links in the left main navigation. And we don't do that either.

**Comment by dmolineus** [comment]
On the first sight I'd prefer the second approach as it clearly shows which operations are avialable.

However from my working experience - I worked on a project where some page actions were hidden by additional rules - the UX get's worse. Imaging working on a large page structure where you want to edit a page. You have to move the mouse more between different pages which - for my experience - is really annyoing.

I'd prefer only showing 1-2 main actions (edit and toggle icon) and hide all others in a dropdown. But this is another story.

**Comment by Wusch** [comment]
![bildschirmfoto 2018-11-21 um 15 06 25](https://user-images.githubusercontent.com/2745704/48846322-23bd6d80-ed9f-11e8-8e44-aba2e29d96f2.png)
In the second approach we have disabled icons only if you can toggle them. In the first approach we mix toggle icons and disabled icons and it's not clear what they will do.

**Comment by fritzmg** [comment]
What about a third option, where the icons that are not available to the user, will not be shown (like option 2), but stilly occupy the same space as they would normally, so that each icon is still in the same column (like in option 1)? But may be that will look too weird.

**Comment by OMOSde** [comment]
Something like this: 

![weird](https://user-images.githubusercontent.com/2035628/48850491-1c9b5d00-eda9-11e8-8bbd-e5deb7d13603.png)

**Comment by cliffparnitzky** [comment]
I think, that what will happen to the mouse movement (mentioned by @dmolineus) will be a disaster. So I think the first approach is the better one. Maybe the toggle idea of @dmolineus should be the better improvement for the future.

**Comment by m-vo** [comment]
I also much prefer the second approach. 

>I'd prefer only showing 1-2 main actions (edit and toggle icon) and hide all others in a dropdown. But this is another story.

Yes, that's the key I guess. The need for alignment only comes with (already too) many items. 

And greyed out items that cannot be clicked nor give some additional information (e.g. tooltip that helps understand the system) really aren't worth anything. If a user lacks permissions for a certain part of the backend or some dca fields we don't render them well.

**Comment by leofeyer** [comment]
As discussed in Mumble on November 22nd, we should only show icons (operations) if they are functional (see https://github.com/contao/contao/issues/195#issuecomment-440282004). Generally, if a user is not allowed to delete a record, they should not see the inactive delete button.

Before we change it, however, we should ask more users in a poll.

**Comment by leofeyer** [comment]
By the way, it is pretty easy to A/B test this in Contao. You just have to add the following markup in your `be_main.html5` template:

```html
<style>#tl_versions td>img,.tl_right>img,.tl_content_right>img,.tl_right_nowrap>img{display:none}</style>
```

It will hide all placeholder icons and leave the clickable icons in place.

**Comment by asaage** [comment]
> add the following CSS at the end of ...

another reason why custom BE-CSS would be useful to have in the settings.
https://github.com/contao/core-bundle/issues/1664#issuecomment-412091356

I personally do not like the misalignment of the icons if those that are not functional get droped and i think gaps are not an option.
From admin point of view i think the grey icons are handy when you are editing permissions and impersonate users - it's much easier to see which permissions are missing.

**Comment by leofeyer** [comment]
If you want to have it even easier, you can add a custom `be_main.html5` template in the templates editor in the back end and paste the following content:

```php
<?php $this->extend('be_main'); ?>

<?php $this->block('head'); ?>
  <?php $this->parent(); ?>
  <style>#tl_versions td>img,.tl_right>img:not([src*="pasteafter"]):not([src*="pasteinto"]),.tl_content_right>img,.tl_right_nowrap>img{display:none}</style>
<?php $this->endblock(); ?>
```

**Comment by asaage** [comment]
> you can add a custom ``` be_main.html5 ``` template

never thought about that .. 👍

**Comment by Metis77** [comment]
I prefer the grey disabled icons.
Otherwise I have to search for where to click, as icons are somewhere else on different rows.

Also editor user may feel better, if they see (and therefore know) that actions like delete are there, but not allowed / available.

Just leaving the icons away looks to me like an error.

**Comment by patrickjDE** [comment]
Generally I like hiding better, but there's quite a problem with that here. The frequently used actions (edit, header) are on the very left, the commonly disabled actions (delete, move, copy) are placed to their right, and everything is right-aligned.
So the frequently used actions are frequently switching their position, placing unnecessary cognitive load onto the user, while the actual goal was to simplify things...

Actually hiding might work well when alignment of frequent actions is conserved, and even better when combined with a dropdown (probably even configurable which actions to place in there?).

**Comment by leofeyer** [comment]
Since there is no clear majority for removing the disabled icons, I am closing this issue. If you prefer hiding the disabled icons, you can adjust your `be_main.html5` template as mentioned [here](https://github.com/contao/contao/issues/195#issuecomment-441254677).
