### ISSUE TITLE
Expand languages ​​to ISO-639-2

### ISSUE THREAD

**Issue by hinzke** [contao/contao#1957]
Could the languages not ​​be extended to ISO 693-2 to include languages ​​such as Low German or Sorbian?

Like Wikipedia and others, that also works fine there.

I would also like to offer to translate the Contao-Backend to Low German.

**Comment by aschempp** [comment]
> I think we should support any language/region that can be parsed by the Intl extension `Locale::parseLocale()`.

I agree, but that means we don't simply want to add ISO-693-2. See https://github.com/contao/core-bundle/issues/233 for extensive information 😉

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2305
