### ISSUE TITLE
Argument 2 passed to Contao\CoreBundle\EventListener\DataContainer\PageUrlListener::stripPrefixesAndSuffixes() must be of the type string, null given, 

### ISSUE THREAD

**Issue by bytehead** [contao/contao#1958]
**Affected version(s)**

Contao 4.10-RC1

**Description**

Go to pagetree, edit page and save.
```
Argument 2 passed to Contao\CoreBundle\EventListener\DataContainer\PageUrlListener::stripPrefixesAndSuffixes() must be of the type string, null given, called in /vendor/contao/core-bundle/src/EventListener/DataContainer/PageUrlListener.php on line 273
```

**Comment by aschempp** [comment]
https://github.com/contao/contao/blob/master/core-bundle/src/EventListener/DataContainer/PageUrlListener.php#L259-L267

This happens because prefix/suffix are `null` (not submitted in post data) in legacy mode.
