### ISSUE TITLE
contao-merge-cache-control header is exposed

### ISSUE THREAD

**Issue by Toflar** [contao/contao#1959]
**Affected version(s)**

4.9?

**Description**

Not a big deal but that info shouldn't be public so we should remove that.

**Comment by leofeyer** [comment]
Can we remove it here or do we need a separate method?

https://github.com/contao/contao/blob/51e84537ccbe8d031c87f0c1bf3e8ecec7117f75/core-bundle/src/EventListener/SubrequestCacheSubscriber.php#L83-L85

**Comment by aschempp** [comment]
I think we can, yes
