### ISSUE TITLE
Preview link does not open FE preview

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1968]
**Affected version(s)**

Contao 4.10

**Description**

- Back end home page → Preview → **no preview bar** (and no `preview.php` fragment)
- Site structure → edit page → Preview → preview bar is shown
- Articles → edit article → Preview → preview bar is shown
- Members → Preview front end as member → **no preview bar**

So it seems that the `/contao/preview` route with anything but `?page=` is broken?

@aschempp @richardhj /cc

**Comment by aschempp** [comment]
I'm pretty sure that's the same behavior in Contao 4.9 😂 Preview is only if you click the preview in the header. Not any other links…

**Comment by m-vo** [comment]
> Preview is only if you click the preview in the header.

I can reproduce this by clicking exactly this button.

**Comment by m-vo** [comment]
This happens because the `PreviewURLConvertListener` won't set the preview URL (because `$request->query->has('page')` is `false`) and therefore the `BackendPreviewController` redirects to `/`.

Edit: It should probably just return this instead, does it?
```php
return new RedirectResponse($this->previewScript);
```

**Comment by richardhj** [comment]
In my Contao 4.9, it correctly redirects to /preview.php, which is correct. The `BackendPreviewController` defaults to redirecting to the contao_root route.
So I guess it broke in 4.10. @aschempp you deprecated the `contao_root` route, didn't you?

**Comment by m-vo** [comment]
@richardhj When is it correct to redirect to `/` here https://github.com/contao/contao/blob/master/core-bundle/src/Controller/BackendPreviewController.php#L93 ?

**Comment by richardhj** [comment]
In 4.9 the line looked like this:
```php
        return new RedirectResponse($this->router->generate('contao_root', [], UrlGeneratorInterface::ABSOLUTE_URL));
```

**Comment by leofeyer** [comment]
IMHO the bigger issue is that the "open frontend as member …" feature is broken. Not sure whether these two are related?

**Comment by leofeyer** [comment]
It seems they are: #1972 🎉
