### ISSUE TITLE
images in galleries: meta not shown

### ISSUE THREAD

**Issue by b-fender** [contao/contao#197]
**Affected version(s)**
Contao 4.6.8

**Description**  
with file-manager filled in meta-informations of images not shown in content-element "gallery".

**How to reproduce**  
Upload a few images
fill in e.g. alt-text and/or title of uploaded images in file-manager
create an article
create a content-element "gallery" and choose the uploaded images for the gallery,
save, reload frontend
"alt" is empty in the gallery,
in file-manager ist is shown.

P.S:
in Contao 4.4 everything works fine, meta-informations are shown correctly with the same procedure.

dump of one $col->picture in template gallery_default:
`Array (
   [img] => Array (
     [srcset] => files/content/img/testbilder/photo-1419.jpg 
     [src] => files/content/img/testbilder/photo-1419.jpg
     [width] => 470
     [height] => 676
      ) 
  [sources] => Array ( ) 
   [alt] => 
) `

**Comment by leofeyer** [comment]
I cannot reproduce this. I have added an alternative text to one of the images in the official demo and it was immediately shown in the front end:

```html
<img src="assets/images/6/DSC_5276-cca4e16e.jpg" width="300" height="200" alt="Voting" itemprop="image">
```

**Comment by b-fender** [comment]
Sorry, have You tested it with Contao 4.6.8?
I tested it multiple Times in 4.6.8 (with original template gallery_default) and meta is empty.
I cannot test ist in the official demo, because file editing is not allowed there.

**Comment by leofeyer** [comment]
Yes, I have tested it with Contao 4.6.8.

**Comment by b-fender** [comment]
ok. thanks for testing then.
