### ISSUE TITLE
Class property annotations

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#1974]
While reviewing https://github.com/contao/contao/pull/1973/files#r459559277, I realized that Symfony does not use `@var` annotations for class properties, e.g. here:

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Routing/Annotation/Route.php

What would you prefer for the future? Keeping them as is, switching to PHP 7.4 and using types, or removing them altogether if the type can be inferred from the constructor?

**Comment by m-vo** [comment]
If we need a general rule, I'd keep them.

1) Variables that aren't set from within the constructor likely cannot be inferred by the IDE.

1) As long as it's statically analyzed for consistency hints at properties add another level of sanity checking: You should define the type when defining the variable. That's the same what you do in function signatures and with typed properties and hopefully some day variables.

I believe we will still add annotations for typed collections, generic types or in the future maybe other constraints like `readonly`. Having annotations only for half of the properties will maybe kill aesthetics a bit :smile: but it's probably going to happen anyway.

**Comment by aschempp** [comment]
We should either have type annotations or real types on properties. As we do not use PHP 7.4 only, we can't do the later. But as soon as we switch (maybe in 4.11) we can. However, I don't think we should "automatically" rewrite everything. 1: it's not worth the effort and 2: probably error-prone ?

**Comment by leofeyer** [comment]
As discussed in Mumble on August 27th, if we can use typed properties, we can remove the phpDoc comment.
