### ISSUE TITLE
Beschriftung ändern: "Nach kaputten Links suchen" zu "Nach defekten Links suchen"

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#1979]
**Affected version(s)**
Contao 4.10 RC1

**Description**
Die Beschriftung der Checkbox in der Systemwartung lautet unter Contao 4.9 `Nach defekten Links suchen`.
Unter Contao 4.10 RC1 lautet diese jetzt wieder `Nach kaputten Links suchen`.
Das wurde schon mal geändert, siehe auch: https://github.com/contao/contao/issues/1309#issuecomment-584691187 
Außerdem steht während des Crawlvorgangs ebenfalls statt "defekt" das Wort "kaputten".

Ich finde den Begriff "kaputt" sehr umgangssprachlich und würde hier gerne wieder "defekt" verwenden.

**Comment by leofeyer** [comment]
Die Sprachdateien werden erst in der RC2 aktualisiert sein (siehe #1977).
