### ISSUE TITLE
Consider already attached external CSS and JS files in layout settings

### ISSUE THREAD

**Issue by kikmedia** [contao/contao#198]
**Affected version(s)**
Contao 4.6.8

**Description**  
If I navigate to a sub folder in File Manager and want to edit a layout afterwards for changing something in external CSS and / or JS files, the previous selected files are gone. 

Already selected external files should be considered.

**How to reproduce** 
- Log into the demo, switch to file manager 
- navigate to a sub folder, for example /contaodemo/media
- switch to Themes -> Layout -> edit a layout
- in the demo, an external CSS file is present
- click on external "change selection" and then "apply" without changing anything
- the previous selection of external CSS is gone (and I presume this would happen with external JS also)

IMO, the previously selected files should be considered if they come from another part of the files tree, or am I completely wrong?

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/core-bundle/issues/1487, I think?

**Comment by kikmedia** [comment]
Obviously, it is. Sorry, didn‘t check the other repository.
