### ISSUE TITLE
Included Element has "inColumn" set to "main" even when both articles are in footer-column

### ISSUE THREAD

**Issue by oikodomo** [contao/contao#1981]
Version: 4.9.3
Example:
In the ce_text template I var_dump the variable"$this->inColumn" for testing.
Then I created a standard text element in the footer of page A.
After that I create in the article for page B a new element with the  elementtype "include-elements" as a reference to the text element that I created for page A.  On page A "inColumn" is set correctly with the value "footer". 
On the page B, where I included the element, the value is "main".
Because both articles are in the footer-column, the included element shouldn't have the default value of "main".

**Comment by fritzmg** [comment]
The last parameter is missing here: 

https://github.com/contao/contao/blob/737136844176870077d8e8f5f1734e8470c8a0c2/core-bundle/src/Resources/contao/elements/ContentArticle.php#L27

Should probably be

```diff
-   return $this->getArticle($this->articleAlias, false, true);
+   return $this->getArticle($this->articleAlias, false, true, $this->strColumn);
``` 

(or it should be fetched from the article itself?)

But we probably cannot change this due to BC.

**Comment by oikodomo** [comment]
I tried it and it works - thank you!

**Comment by leofeyer** [comment]
> But we probably cannot change this due to BC.

Why do you think so?

**Comment by fritzmg** [comment]
> > But we probably cannot change this due to BC.
> 
> Why do you think so?

Because then suddenly content elements that are included via an `article` content element will have a different column, while they always had `main` previously. May be someone relies on that? Who knows ;).

Also it's not clear to me what the column should actually be. Should it be the column of the _original_ article or should it be the column of the including element? Probably the latter, since the column should signify where the article is _currently_ displayed, right?

**Comment by oikodomo** [comment]
IMHO:
My expectation is that if I inlcude an element, I get the content of the _original_ article, but in the environment of the _current_ article -> that would mean the inColumn variable gets the value from wherever the element is implemented, not from the _original_ source/article.
Otherwise this has a great potential to mislead/confuse many, for example by getting "header" as a value of inColumn in a footer, or vice versa.

**Comment by asaage** [comment]
> In the ce_text template I var_dump the variable"$this->inColumn" for testing.

Why would a content-element (ce_text) have a *inColumn* property in the first place? That is only of interest for the containing article.

**Comment by oikodomo** [comment]
> > In the ce_text template I var_dump the variable"$this->inColumn" for testing.
> 
> Why would a content-element (ce_text) have a _inColumn_ property in the first place? That is only of interest for the containing article.

I think it definitly has a right to exist.
This is how we use it:
A standard ce_text has different looks in a design, depeding in which column(header/main/footer) the user creates an element.
And with that knowledge we add the template ce_text in templates and add the condition:
`if($this->inColumn == "footer")
   $this->class .= " [here goes a special css class]";`
with that change you can create your standard text element, without changing the template and  without forcing the user to insert a class in the cssID/class field. 
This is just an example and I know, there are million ways to do exactly that, but we find this way elegant.
What I try to say is, that this variable is a nice tool to manipulate templates in context of the position in the html

**Comment by fritzmg** [comment]
> Why would a content-element (ce_text) have a _inColumn_ property in the first place? That is only of interest for the containing article.

So that you can query in which column the element resides. See the second argument for the `\Contao\ContentElement` constructor.

**Comment by m-vo** [comment]
Thinking about includes/insert tags I don't like the fact that this creates a context. But not sure if this is a problem already.

**Comment by asaage** [comment]
@PhillipK12 i see...
but if it's only for looks it would be way easier to use css

```css
#main .ce_text { style.. }
#footer .ce_text { other-style.. }
```

**Comment by fritzmg** [comment]
> Thinking about includes/insert tags I don't like the fact that this creates a context. But not sure if this is a problem already.

It's something you can already do yourself, with the 4th parameter of `\Contao\Controller::getArticle` for example.

**Comment by oikodomo** [comment]
> @PhillipK12 i see...
> but if it' only for looks it would be way easier to use css
> 
> ´´´css
> #main .ce_text { style.. }
> #footer .ce_text { other-style.. }
> ´´´

You are right with "if it only for looks", but sometimes thats not the case.

**Comment by aschempp** [comment]
> > > But we probably cannot change this due to BC.
> 
> > 
> 
> > Why do you think so?
> 
> 
> 
> Because then suddenly content elements that are included via an `article` content element will have a different column, while they always had `main` previously. May be someone relies on that? Who knows ;).


Fixing a bug is always a BC break, bit that should be Ok



> Also it's not clear to me what the column should actually be. Should it be the column of the _original_ article or should it be the column of the including element? Probably the latter, since the column should signify where the article is _currently_ displayed, right?

I think it should be the current column

**Comment by leofeyer** [comment]
As discussed in Mumble on July 30th, the is a bugfix and therefore ok.
