### ISSUE TITLE
DCA: foreignKey and relations doesn't work with showColumns

### ISSUE THREAD

**Issue by danielkochengineer** [contao/contao#1989]
**Affected version(s)**

Contao 4.9

**Description**

I am not sure if this is the desired functionality or a bug. If this is the desired functionality, then just let me know.

When I use a _foreignKey_ and a _relation_ like the following in the DCA:

`
'foreignKey'            => 'tl_law_monitoring_users.firstname',
'relation'  => ['type' => 'hasOne', 'load' => 'eagerly'],
`
or a more complicated one using CONCAT
`
'foreignKey'            => 'tl_law_monitoring_users.CONCAT(firstname," ",lastname)',
'relation'  => ['type' => 'hasOne', 'load' => 'eagerly'],
`

This results in a correct "edit" or "create" form", where select-boxes show the correct value and dropdown.

This doesn't work correctly in the normal table view. When I use list.label.showColumns=true and put this field into list.label.fields, it just shows the ID (key that is saved in the DB) in the table instead of the value from the foreignKey.

<img width="1202" alt="Screenshot 2020-07-25 at 10 15 22" src="https://user-images.githubusercontent.com/50423180/88452529-c9bc5780-ce5f-11ea-93d0-cd0d896b7885.png">

This issue was created out of this community thread: https://community.contao.org/de/showthread.php?78540-DCA-showColumns-und-Relationen&p=529254#post529254

**Comment by fritzmg** [comment]
Apparently there is a feature to "map" these values: https://de.contaowiki.org/DCA_Field_Mapping - which I didn't even know about (noted for documentation: https://github.com/contao/docs/issues/489).

However, imo it would be nice if the listing also takes the `foreignKey` information into account automatically.

**Comment by danielkochengineer** [comment]
@fritzmg Yes, I tried the _DCA Field Mapping_, but it seems to be limited. For example it doesn't work if you want to combine multiple attributes using the mysql function `CONCAT`. Or am I wrong at this point? Is there a way to do that?

**Comment by aschempp** [comment]
If you have special needs for the list view (like combining values), you should use the `label_callback`.

**Comment by danielkochengineer** [comment]
@aschempp Thanks, I tried that and it worked for my needs. Should we close this issue then or does it still make sense to change something here?

**Comment by aschempp** [comment]
I think it should be closed 😊
