### ISSUE TITLE
Missing images do not generate 404 page

### ISSUE THREAD

**Issue by aschempp** [contao/contao#1995]
**Affected version(s)**

Contao 4.9

**Description**

If I request an image file that does not exist on the server, I get the following in my log: `InvalidArgumentException: "files/example.jpg does not exist" at vendor/contao/image/src/Image.php line 61`

Shouldn't we throw a 404 error instead or convert this somewhere in the deferred image controller?

**Comment by ausi** [comment]
How do I reproduce that? In my test the exception got correctly converted to a `NotFoundHttpException` in https://github.com/contao/contao/blob/87cc286a198e04709757a59239e36e91f4215339/core-bundle/src/Controller/ImagesController.php#L65

**Comment by aschempp** [comment]
The exception seems to be thrown on line 71: https://github.com/contao/contao/blob/87cc286a198e04709757a59239e36e91f4215339/core-bundle/src/Controller/ImagesController.php#L71

**Comment by aschempp** [comment]
Probably because the deferred image config file is there, but the source image is not (anymore).

**Comment by ausi** [comment]
This is an error than IMO. Why does the config file exist but the source image does not?

I’m not sure if we should remove the config file if we run into this issue. What if the image is only missing temporarily? 
Also, if you get this error in your logs, doesn’t that mean that someone still tries to access this image which probably is an actual error?

**Comment by aschempp** [comment]
I would assume:
 1. The image was uploaded and added to a content element
 2. The front end was viewed and the page cached, but obviously not all image sizes created because they are deferred
 3. The source image was deleted afterwards

Is there a reason not to catch (and probably ignore) that error? A 500 seems worse that a 404 to me?

**Comment by ausi** [comment]
So, we should ignore that error, but keep the deferred JSON file in place?
I guess that would be OK with me.

**Comment by leofeyer** [comment]
Fine with me, too.

**Comment by Toflar** [comment]
> So, we should ignore that error, but keep the deferred JSON file in place?

No, the JSON file must also be removed. See https://github.com/contao/contao/issues/2324.
Otherwise `contao:resize-images` will report those orphan JSON files forever and disk usage will grow endlessly.

**Comment by ausi** [comment]
Note to myself: I need to first add proper exceptions to `contao/image` so that we can catch the error of the missing source file explicitly.

> > So, we should ignore that error, but keep the deferred JSON file in place?
> 
> No, the JSON file must also be removed.

How about adding a parameter to the `resize-images` command `--delete-images-with-missing-source`?

**Comment by Toflar** [comment]
I think deleting them should be the default but I'd be okay with a flag. Maybe we can even store the number of times the image wanted to get resized in the JSON itself and if it didn't work for like 5 times or so, delete it then. That would cover your "file was not available for a short time" use case.

**Comment by ausi** [comment]
Still on my list.

**Comment by ausi** [comment]
@aschempp @Toflar could you please check if #2883 is OK with you (before I merge contao/image#79 )
