### ISSUE TITLE
Search engine: forwading page

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2010]
**Affected version(s)**

Contao 4.9.3

**Description**
If the forwarding page (Weiterleitungsseite) is empty

![grafik](https://user-images.githubusercontent.com/1645099/88588174-6bf26000-d057-11ea-8fb2-9d50d4d5b6eb.png)

the search engine works fine
https://demo.contao.org/en/search.html?keywords=jones
![grafik](https://user-images.githubusercontent.com/1645099/88588257-8b898880-d057-11ea-9823-e3fdd539c73d.png)

But: if you set any forwarding page
![grafik](https://user-images.githubusercontent.com/1645099/88588395-c4296200-d057-11ea-9ae9-59a76c999058.png)

the search engine is broken. No results are shown
![grafik](https://user-images.githubusercontent.com/1645099/88588467-e4592100-d057-11ea-899f-7f090c580b8e.png)
https://demo.contao.org/en/search.html?keywords=jones

**Comment by fritzmg** [comment]
That's the intended behaviour.

**Comment by math-GH** [comment]
It not a bug - it is a not documented feature?

![grafik](https://user-images.githubusercontent.com/1645099/88591163-3603aa80-d05c-11ea-8261-eb4de969e691.png)
https://docs.contao.org/manual/de/layout/modulverwaltung/website-suche/

**Comment by fritzmg** [comment]
See https://github.com/contao/docs/pull/495

**Comment by asaage** [comment]
So the use-case of this is basically if you only need the search-form of the search-engine and want to display the results on another page? But you would still need a(nother) search-engine without a redirect-page on the page you are being directed to?
That looks a bit wonky... i tend to use a GET-form in this case.

**Comment by fritzmg** [comment]
> That looks a bit wonky... i tend to use a GET-form in this case.

You can do whatever you want of course ;)
