### ISSUE TITLE
Memberlist in Backend: Filter für newsletter-recipients

### ISSUE THREAD

**Issue by Ernestopheles** [contao/contao#2011]
Feature request:

The member list in the Backend should please show the information, which members subscribed to which newsletters. A filter would do: filter by newsletter-channel.

We need to know this, as we use newsletters for internal (one-way) communication. So if we find anybody not subscribed, we could remind him.

**Comment by ausi** [comment]
You can do that in the DCA configuration of your installation with one line:

```
$GLOBALS['TL_DCA']['tl_member']['fields']['newsletter']['filter'] = true;
```

**Comment by Ernestopheles** [comment]
Herzlichen Dank dafür!!

**Comment by Ernestopheles** [comment]
Thanks for your kind support
