### ISSUE TITLE
submitOnChange gives blank page

### ISSUE THREAD

**Issue by adojck** [contao/contao#202]
**Affected version**
Contao 4.6.9

**Description**
Where `submitOnChange` is used, after selecting option, the page refreshes into blank page (no errors logged, no messages, no HTML in page). Happens with our own bundle, and with standard bundles too.

**How to reproduce**  
1) Go to: Themes -> Front-End Modules -> New Module and then change Module Type, after page reloads it stays blank
2) Go to: Articles -> Edit any article -> New Element and then change Element Type, after page reloads it stays blank

**Notes**
PHP versions tested: `7.1` and `7.2`
No errors in logs... No content in empty page.
Same problem with all browsers (_Firefox, Chrome, Opera_), so I think it's browser independent.

**Comment by fritzmg** [comment]
I cannot confirm that (Contao `4.6.9`, PHP `7.1`).

**Comment by adojck** [comment]
Found the reason of this problem.

In logs showed up this:
`[warn] PHP Warning:  Cannot modify header information - headers already sent by [...]`

Headers was already sent by template file which was saved as UTF-8 with BOM.

**Comment by adojck** [comment]
We found all files which has UTF-8 BOM with this command:
`grep -rlIR $'\xEF\xBB\xBF' `
Source: https://www.dynobin.com/linux-remove-byte-order-mark-bom-from-files/
