### ISSUE TITLE
Controller->getContentElement() does not support FragmentControllers

### ISSUE THREAD

**Issue by philvdb** [contao/contao#2022]
**Affected version(s)**

Contao 4.9

**Description**

Hey Team,

maybe I am missing something here but I was in the mood to refactor our custom content elements to Fragment Controllers as [shown in the docs](https://docs.contao.org/dev/guides/fragment-controllers/).

I have new content element types within new content element types, so I have been getting/rendering these via `Controller->getContentElement($objContentModel)`. Problem here is that generating the element is hard-coded as

```PHP
$objElement = new $strClass($objRow, $strColumn);
$strBuffer = $objElement->generate();
```

Which makes it impossible to use Fragment Controllers if I understand the concept correctly, as [according to the (Contao) docs](https://docs.contao.org/dev/guides/fragment-controllers/) they are meant to be invoked as functions like this:

```PHP
$objElement = new $strClass();
$strBuffer = $objElement($objRow, $strColumn);
```

So the obvious suggestion here would be to add an `is_callable()` in the controller logic and prefer that?

Or am I missing something about how Fragments are to be used?

**Comment by fritzmg** [comment]
What kind of issue happens, when you use `\Contao\Controller::getContentElement`? For any fragment content element Contao also registers a `\Contao\CoreBundle\Fragment\Reference\ContentElementReference\ContentProxy`, which should get rendered within `\Contao\Controller::getContentElement`.

**Comment by philvdb** [comment]
First of all, thank you guys for replying so quickly, I really appreciate having the developers' ear like this.

My current issue is that the model is not available in the content element which from my understanding stems from the fact that the CustomContentElement now has a constructor that expects (and utilizes) no arguments and the `__invoke` method is never used.

From your answer I understand that you would expect a ContentProxy class to deal with adapting the Contao way of generating the element to the Fragment way. Xdebug shows the actual class being used inside the `\Contao\Controller::getContentElement()` function to be my class directly though, not a proxy.

**Comment by philvdb** [comment]
Ooh. The example in the docs was just extending `ModuleNewsList` and there was no mention of `AbstractContentElementController` so I guess I inferred that all ContentElements would be descendants of that ContentElementController, which they're obviously not.

We already had an abstraction of regular Contao elements, an `AbstractTwigContentElement` that uses Twig in the Frontend, but it extends the regular old `\Contao\ContentElement` so I'm assuming that is why the proxying is not kicking in.

If that is the problem sorry to have bothered you and I would only suggest adapting the example in the docs somehow to make clear that `ModuleNewsList` and `ContentGallery` are descendants of the Module and CE Controllers.

**Comment by philvdb** [comment]
Okay, I'm not sure whether we are actually going to use the fragments for now as there is a lot of logic dealing with Contao html5 templates, we have switched to Twig for our content elements in the Frontend though.

Thank you again for pushing me in the right direction!

**Comment by philvdb** [comment]
By the way it is still not working even though now my `AbstractTwigContentElement` extends `AbstractContentElementController`:

![Bildschirmfoto von 2020-07-28 15-30-44](https://user-images.githubusercontent.com/1567784/88672276-90961880-d0e7-11ea-9a1d-4746f06bfdc1.png)

We are still calling the literal class and not any proxy class within `getContentElement()`.

So I am giving up on Fragments for now and will continue extending traditional Content Elements.

Let me know if you suspect it's more than my ineptitude, I will share more debug information with you.

**Comment by fritzmg** [comment]
I am not really sure what you are trying to do from your description ;)

May be you should seek consultation on the community forum and post your code there.

**Comment by m-vo** [comment]
>  we have switched to Twig for our content elements in the Frontend though.

I use Twig exclusively in most of my projects. This *does* play well with the fragment concept. Just ignore the `$template` argument from `getResponse()` and render your Twig template instead.

**Comment by philvdb** [comment]
> I am not really sure what you are trying to do from your description ;)

I was excited by the idea of Controller Fragments from the docs and followed the instructions as closely as I could but found the way it was set up in `Controller->getContentElement()` couldn't work. So I thought it was a bug, but I guess it's a feature ;)

> I use Twig exclusively in most of my projects. This does play well with the fragment concept. Just ignore the $template argument from getResponse() and render your Twig template instead.

It seemed inefficient to me to instantiate the Contao template all the way and then throw it away, so I have overwritten the `__invoke()` function of `AbstractContentElementController` and skipped the Contao template stuff. Maybe that was my mistake?

Thank you for your input and congratulations on getting Fragments to work!

**Comment by fritzmg** [comment]
> I was excited by the idea of Controller Fragments from the docs and followed the instructions as closely as I could but found the way it was set up in `Controller->getContentElement()` couldn't work. So I thought it was a bug, but I guess it's a feature ;)

I still don't get why you want to call `\Contao\Controller::getContentElement`, you'd need to show an example of what you are trying to do.

> It seemed inefficient to me to instantiate the Contao template all the way and then throw it away, so I have overwritten the `__invoke()` function of `AbstractContentElementController` and skipped the Contao template stuff. Maybe that was my mistake?

You don't have to use the Abstract class, you can do whatever you want within your fragment controller ;). As long as you use the correct interfaces and service tags and return a response, everything is fine :)

**Comment by philvdb** [comment]
> I still don't get why you want to call \Contao\Controller::getContentElement, you'd need to show an example of what you are trying to do.

If you look at the screenshot I posted closely, I'm not even the one calling `getContentElement()` in this instance - `\Contao\ModuleArticle` is. It is the standard way to retrieve a rendered Content Element as far as I know so I was using it in my code as well. But this function fails to render a Fragment Controller, as these (as you know) have to be `__invoke`d, not `__construct`ed and `generate`d. You said Proxies were supposed to take care of this translation and you're obviously right that they *should*, but they are not doing that in my case.

I have a rather complex code base to start with though and would have to break it down all the way to the minimum required to demonstrate failure. Just pasting all the classes in here would not be suitable for a bug tracker. 

I guess a better approach for me would be to start from a minimum Fragment setup that does still work (as there are at least two people in the world I have read of that managed to get Fragment Controllers to work in Contao!) and add our existing complexity from there.

Alas, as much fun as this kind of refactoring can be, I need to start closing issues that users actually see a difference from now. It seemed clear to me that this was a bug, that's why I posted in the bug tracker. If it's not and I'm just missing something from the documentation or some peculiarity of our setup is messing me up I obviously need to debug it myself or turn to the forums. Thank you again for your input - we probably will get back around to it eventually!

**Comment by philvdb** [comment]
Just a final follow-up: Mea culpa (as was to be expected).

Turns out I messed up in `services.yml`. Fragment Controllers are running fine, using Twig and with on-demand provision of Twig template values - everything A-OK.

Apologies again for having mistaken my ineptitude for a bug. That one is obviously a feature :laughing:
