### ISSUE TITLE
Always try to find the root page getRootPageFromUrl()

### ISSUE THREAD

**Issue by richardhj** [contao/contao#2025]
**Affected version(s)**

Contao 4.10

**Description**

When the request attribute does not have a `pageModel`, it should fall back to the legacy logic.

https://github.com/contao/contao/blob/75c4c7b41f8e4843c090953c8c10caa0d8707607/core-bundle/src/Resources/contao/classes/Frontend.php#L320

When you define routes in your application manually, those routes do not have a `pageModel` attached. Contao should look up the root page by the hostname nonetheless instead of throwing the Exception.

Proposal: Remove throwing an exception.

**Comment by richardhj** [comment]
**The underlying questions are:**
How do you add custom routes that do not have a corresponding page model? What other side effects might occur when using custom routes in the front end scope?

**Comment by aschempp** [comment]
Technically, a custom route does not belong to a Contao page, so there can't really be a (root) page assigned.

Maybe you can answer the question first why you would use that function at all? And then maybe you should use a page controller in that case?

**Comment by richardhj** [comment]
Prior it was possible to find the root page by the current domain name. This way, it was possible to load the correct layout and output the proper layout, etc.

I guess I will replace all those routes by pages with a custom page controller each, even though those pages do not need to be managed by the CMS.

**Comment by aschempp** [comment]
I know, though I never really understood. How is that supposed to know your language etc? You can easily find the current fallback root by querying the database.

However, why would the root page layout apply to your page? Apart from the fact that the root page does not _need_ a layout at all. Wouldn't that be the perfect reason for your routes to **be** pages?

**Comment by asaage** [comment]
> Apart from the fact that the root page does not need a layout at all

I guess it's needes so pages can inherit the layout of their parent.?

**Comment by richardhj** [comment]
> > Apart from the fact that the root page does not need a layout at all
> 
> I guess it's needes so pages can inherit the layout of their parent.?

Not necessarily, pages can have a layout defined, so you do not have to define one at root level.

**Comment by fritzmg** [comment]
I usually only ever define the page layout in the root page.

**Comment by richardhj** [comment]
I assume the new routing/matching works as expected. No bug here 😄
