### ISSUE TITLE
Autoresize for backend textareas

### ISSUE THREAD

**Issue by Anke** [contao/contao#2033]
In Contao 4.9.4 I notice that html/code textareas are just one row high, if used without code editor. Is this intended to be that way?

Also, TinyMCE textareas are quite small in height, which is why I'd like to propose to implement the autoresize plugin as a default feature. 

Having to resize the editor windows each and every time an editor wants to edit content is making their work harder than necessary.

**Comment by bytehead** [comment]
See #2004, will be fixed in 4.9.5.

**Comment by Anke** [comment]
That's why I didn't find it under "issues". Thanks.
