### ISSUE TITLE
debug:router throws "No root page found"

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2043]
**Affected version(s)**

Contao 4.10

**Description**

```
vendor/bin/contao-console debug:router                   
11:32:42 ERROR     [console] Error thrown while running command "debug:router". Message: "No root page found" ["exception" => Contao\CoreBundle\Exception\NoRootPageFoundException^ { …},"command" => "debug:router","message" => "No root page found"]

In PageModel.php line 1048:
                      
  No root page found  
                      
debug:router [--show-controllers] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command> [<name>]
```

The exception is thrown here:

https://github.com/contao/contao/blob/75c4c7b41f8e4843c090953c8c10caa0d8707607/core-bundle/src/Resources/contao/models/PageModel.php#L1044-L1049

I wonder why `TL_MODE == 'FE'` is true when running `debug:router`?

**Comment by aschempp** [comment]
This should only happen if you have a misconfigured page (not belonging to a root page)?

**Comment by leofeyer** [comment]
I do not have such a page. But I have added `dump($this->title);` in line 1047 and here is the output:

```
vendor/bin/contao-console debug:router
^ "Text elements"
^ "Accordion"
^ "Content slider"
^ "Link elements"
^ "Media elements"
^ "File elements"
^ "Include elements"
^ "Text elements"
12:47:29 ERROR     [console] Error thrown while running command "debug:router". Message: "No root page found" ["exception" => Contao\CoreBundle\Exception\NoRootPageFoundException^ { …},"command" => "debug:router","message" => "No root page found"]

In PageModel.php line 1048:
                      
  No root page found  
                      
debug:router [--show-controllers] [--format FORMAT] [--raw] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command> [<name>]
```

The exception is only thrown the second time the "Text elements" page is processed. Does this help?

**Comment by leofeyer** [comment]
Turns out I really had pages with an invalid PID that have not been purged automatically. 🙃

**Comment by MariaEngelold** [comment]
> Turns out I really had pages with an invalid PID that have not been purged automatically. 🙃

Hey @leofeyer just switched from contao 4.5 to 4.10 and run into an issue with _(probably)_ misconfigured pages.
Could you tell me how you found out what pages of your installation caused the problem? 
I'm also wondering what in general causes the error message `Page ID "35" does not belong to a root page` when clearly the page is a child of the root page?

![image](https://user-images.githubusercontent.com/39092370/90672167-02c8cb80-e256-11ea-8c9c-b85b73c99298.png)

**Comment by leofeyer** [comment]
You can use the following SQL query to find pages with an invalid PID:

```sql
SELECT * FROM `tl_page` WHERE pid > 0 AND pid NOT IN (SELECT id from `tl_page`)
```

If you want to delete the pages, use this SQL query:

```sql
DELETE FROM `tl_page` WHERE pid > 0 AND pid NOT IN (SELECT id FROM (SELECT id FROM `tl_page`) AS page_id)
```

Note that you might have to run the query multiple times, because after each deletion, there can be new orphan records.

**Comment by ameotoko** [comment]
I'm having this problem too, the only difference is that it is a recurring issue – the orphaned pages that I deleted keep coming back. Every once in a while (randomly), when visiting front end, this exception is thrown, and Contao creates these orphaned pages again – they appear in the database with all the data they had and the same ids.

Also, I never saw it happen on my local copy (maybe doesn't happen in dev environment?)
