### ISSUE TITLE
Time limit for sessionTimeout not lower than

### ISSUE THREAD

**Issue by Paddy0174** [contao/contao#205]
**Affected version(s)**  
Contao 3.x, and 4.x

**Description**  
The sessionTimeout value can be set as low as one second. In this case, the user will be logged out straight after logging in.

There should be a minimum value, let's say at least 60 seconds. 

See [the corrsponding thread in the community board](https://community.contao.org/de/showthread.php?72745-Contao-3-5-Zeit-f%C3%BCr-automatisches-Log-Out-auf-1sek-gestellt)

EDIT: Considering this a bug, doesn't necessarily mean, it should be implemented right away. Changing this during the move to the CM is fine, nevertheless it's not a feature, imho.

**Comment by Ainschy** [comment]
Die Verantwortung liegt nach meiner Auffassung beim Admin der Zugriff auf die Systemeinstellungen hat.

Zu mal der Wert in der localconfig korrigiert werden kann.

**Comment by fritzmg** [comment]
Also a value of 60 seconds seems very arbitrary. As @Ainschy said, it is the responsibility of the administrator to set correct values there. And if he did use "incorrect" values, it's in their responsibility to change them again.

**Comment by Paddy0174** [comment]
As said in the thread, I'm with you, that an Admin should know, what she/he is doing. 

On the other hand, it is, as far as I know, the only setting, where you can log out an Admin in a running system. There are other settings, that can break your Admin account, but all of these settings break your page as well. This setting doesn't.

And btw not all Admins have an account for the FTP server to change it back.

So it should be at least a ``"minlength"=> 3`` set for the value in settings. At least 100 seconds are enough time, to change this setting back again, if accidently set wrong. 

As @Ainschy said in the thread, this setting will be moved to the CM, the reasons still exist. I would set a minimum value for this in CM as well. 

In my opinion, this should be considered a bug, as I can log out an Admin. Contao does prevent this on many different occasions in the system, but not here. I find that not consistent.

**Comment by leofeyer** [comment]
> In my opinion, this should be considered a bug, as I can log out an Admin. Contao does prevent this on many different occasions in the system, but not here. I find that not consistent.

That's a point for sure. We have also added routines so admins cannot accidentally remove the `admin` flag on their own accounts, therefore adding the `minlength` attribute sounds reasonable.

**Comment by leofeyer** [comment]
Fixed in efae12ea5cb6ae4c3641434f840f756ced6825f6.
