### ISSUE TITLE
Contao Frontend-Vorschau: Fehlende Mitgliederauswahl

### ISSUE THREAD

**Issue by minstyle** [contao/contao#207]
**Affected version(s)**
contao/core-bundle 4.4.29
contao/core-bundle 4.6.8

**Description**  
In der Frontend-Vorschau von Contao werden keine Benutzernamen aller verfügbaren Mitglieder zur Auswahl angezeigt.

**How to reproduce**

_Wie in der offiziellen Contao Online Demo (https://demo.contao.org) zu sehen:_

Mitglieder erstellen:
![image](https://user-images.githubusercontent.com/2649562/49205973-e2d1e400-f3b0-11e8-832b-2c30d9eb0a25.png)

Die Frontend-Vorschau über den entsprechenden Button im Backend betätigen:
![image](https://user-images.githubusercontent.com/2649562/49205825-7e168980-f3b0-11e8-9372-211bf92f048a.png)

Es werden keine Benutzernamen angezeigt:
![image](https://user-images.githubusercontent.com/2649562/49205939-c635ac00-f3b0-11e8-99ac-e5f4c0be108c.png)

**Comment by Toflar** [comment]
Die werden schon seit jeher mit Ajax nachgeladen. Du musst tippen, sonst wäre die Liste bei 5000 Mitgliedern ganz schön lang.

**Comment by minstyle** [comment]
Ich denke, hier sollte es wenigstens eine Ajax Autovervollständigung implentiert werden, um die Usability zu erhöhen. Wenn ich aktuell in das entsprechende Feld tut sich nämlich nichts...

**Comment by minstyle** [comment]
Danke für die Info!
