### ISSUE TITLE
Children of unpublished parent page not added to sitemap

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#2070]
**Affected version(s)**

Tested on 4.9.2, seems to be the same in 4.4

**Description**

If we have a site structure like this
```
───root
   ├───subpage
   │   ├───child1
   │   ├───child2
   │   └───child3
```
and all child pages are set to `index, follow` but their parent (subpage) is set to "not published"
they will no be added to the sitemap. This is due to the fact that `Backend::findSearchablePages` follows the site structure tree and only scans for published pages.

**Is this intended behaviour?**

If so I think this should be changed.

This behaviour suggests that the children would inherit properties of the parent which is not true in the case of "published/unpublished". 

All child pages can have an alias that is non related to the parent in any way, their visibility can be set completely independend from their parent and even if the parent is set to "unpublished" the children are still published.

So why should this be different within the sitemap.xml?

**Comment by leofeyer** [comment]
I agree. It is quite a behavior change though. @contao/developers WDYT?

**Comment by fritzmg** [comment]
Definitely a bug. Any published page that is set to `index,…` should appear in the sitemap.
