### ISSUE TITLE
Use input event instead of keyup in the preview toolbar

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2079]
On a side note unrelated to this PR: We probably want to use the [*input* event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) instead. Afaik *keyup* isn't triggered when pasting for instance.

https://github.com/contao/contao/blob/de2a224239fbfae3cfd85b1aa76383e7e233dfdc/core-bundle/src/Resources/views/Frontend/preview_toolbar_base_js.html.twig#L258

_Originally posted by @m-vo in https://github.com/contao/contao/pull/2077_

**Comment by leofeyer** [comment]
@ausi @richardhj WDYT?

**Comment by ausi** [comment]
👍

**Comment by richardhj** [comment]
👍

**Comment by m-vo** [comment]
see #2089
