### ISSUE TITLE
[4.4] zwei Newsletter-Anmeldung-Widgets auf einer Seite - man kommt nicht über die Sicherheitsabfrage

### ISSUE THREAD

**Issue by zonky2** [contao/contao#208]
Contao 4.4.21

Ich habe zwei Newsletter-Anmeldung-Widgets auf einer Seite - 1x Fußzeile und 1x "oben" auf der Seite Newsletter.

Wenn man seine E-Mail eingibt, kommt beim ersten Versenden die Sicherheitsabfrage und danach kommt diese immer wieder mit der Meldung, man hätte falsch gerechnet.

**Comment by fritzmg** [comment]
Du musst immer auf die neueste Contao Version aktualisieren und dann erst testen und dann erst ggf. einen Bug Report machen.

**Comment by zonky2** [comment]
die C 4.4.21 ist die "aktuellste" (im LTS-Zweig)

ob "Bug oder Feature" kann ich so nicht entscheiden

**Comment by netzarbeiter** [comment]
Die aktuelle Contao-Version im LTS-Zweig ist [4.4.29](https://github.com/contao/contao/blob/4.4/CHANGELOG.md) vom 22. November 2018.

**Comment by zonky2** [comment]
o.k. - habe über den Manager ein Update gemacht und Contao bleibt auf der 4.4.21 - meldet auf der Konsolenausgabe aber auch nicht, dass eine Abhängigkeit am Update hindert.. hmmm

**Comment by zonky2** [comment]
o.k. - alle Pakete geupdatet ... nun Contao 4.4.29

selber Effekt :(

**Comment by fritzmg** [comment]
> o.k. - habe über den Manager ein Update gemacht und Contao bleibt auf der 4.4.21 - meldet auf der Konsolenausgabe aber auch nicht, dass eine Abhängigkeit am Update hindert.. hmmm

Siehe https://github.com/contao/contao/issues/10#issuecomment-416487202

> o.k. - alle Pakete geupdatet ... nun Contao 4.4.29
> 
> selber Effekt :(

Dass zwei mal das selbe Formular auf der Seite einbinden nicht funktioniert ist denke ich eine known limitation. Du musst zwei verschiedene Formulare erzeugen.

**Comment by zonky2** [comment]
o.k. - hatte das für FE-Modul der Anmeldung so nicht auf dem Schirm
