### ISSUE TITLE
Add @phpstan-var to inline phpDoc comments

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2080]
See https://github.com/contao/contao/pull/2075#discussion_r465509239

<img width="812" alt="" src="https://user-images.githubusercontent.com/1192057/89381767-f1ca7700-d6f9-11ea-8544-4821da3f7bec.png">

**Comment by m-vo** [comment]
Btw.: I'm pretty sure PHPStorm will understand the psalm/phpstan annotations in the near future. They announced to support the tools out of the box last month: https://blog.jetbrains.com/phpstorm/2020/07/phpstan-and-psalm-support-coming-to-phpstorm/

**Comment by leofeyer** [comment]
It seems we no longer need an annotation at all?

<img width="927" alt="" src="https://user-images.githubusercontent.com/1192057/119017205-0c28c500-b99b-11eb-8e90-3f2341dba86d.png">

**Comment by m-vo** [comment]
IMHO Psalm still needs it - here is a stripped down version* [with](https://psalm.dev/r/2b6a879ffd) and [without](https://psalm.dev/r/9388ba8465) the annotation. 

*) I only added  `array<string>` to `$arrClassNames` so that the differences become obvious
