### ISSUE TITLE
Language redirect uses 301

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2084]
**Affected version(s)**

Contao 4.4 & 4.9

**Description**

In a multi-language setup with

```yml
# config/config.yml
contao:
    prepend_locale: true
```

the redirect from `https://example.org/` to `https://example.org/<LANGUAGE>/` uses a redirect response with a status code of `301`.

However, since the actual response is dependent on the `Accept-Language` request header, shouldn't it be a temporary redirect? Or do we assume that the `Accept-Language` header from the same client is unlikely to change and thus it is fine to use a permanent redirect in this particular case.

**Comment by ausi** [comment]
Yes, I think a temporary redirect is what most websites use.

> the actual response is dependent on the `Accept-Language` request header

In this case we should set `Vary: Accept-Language` I think.

**Comment by leofeyer** [comment]
When I open https://www.apple.de in my browser, I am being redirected to https://www.apple.com/de/ with a 301 status code.

<img width="399" alt="" src="https://user-images.githubusercontent.com/1192057/89411158-3d464a80-d725-11ea-9ae3-c64c62c23023.png">

**Comment by fritzmg** [comment]
But that's not the same. That's just a redirect from one domain to another.

**Comment by fritzmg** [comment]
See this more suitable example where you stay on the same domain:

```
$ curl -I -H "User-Agent: Mozilla" https://www.microsoft.com/
HTTP/2 302
content-length: 0
location: https://www.microsoft.com/en-gb/
date: Wed, 05 Aug 2020 12:23:46 GMT
tls_version: tls1.2
strict-transport-security: max-age=31536000
x-rtag: ARRPrd
```

In this case microsoft.com redirects according to the client IP.

**Comment by leofeyer** [comment]
> In this case we should set `Vary: Accept-Language` I think.

@Toflar WDYT?

**Comment by Toflar** [comment]
Temporary redirects are not stored in cache so the `Vary` header is pointless imho

**Comment by fritzmg** [comment]
I think @ausi meant in case the response status stays at `301`, then the response should include `Vary: Accept-Language`.

**Comment by Toflar** [comment]
That's correct then. However, I don't really like that because `Accept-Language` can take on arbitrary values, causing the cache to get flooded. That's why it should be a temporary redirect imho.

**Comment by aschempp** [comment]
I think it should be permanent, but to the client only. So I assume the response is not cacheable?

**Comment by Toflar** [comment]
That would be a cacheable `301` and `Cache-Control: private` then :)

**Comment by ausi** [comment]
mozilla.org uses a `301` with a `vary` header, microsoft uses a `302` without `vary`. 

I think both versions are fine but I’d vote for using `302`.

**Comment by leofeyer** [comment]
See https://kinsta.com/knowledgebase/307-redirect/

> Unless your target audience uses legacy clients, avoid using the 302 Found redirect response.

So is `303` without `vary` ok as well?

**Comment by Toflar** [comment]
> A 303 response SHOULD NOT be cached unless it is indicated as cacheable by Cache-Control or Expires header fields.

So you'd need to make sure we have `Cache-Control: no-store`.

**Comment by leofeyer** [comment]
I lean towards `301` with `vary`, however, the Symfony redirect controller does not provide such an option:

https://github.com/contao/contao/blob/a786424a602615889b7c090de63bd3ecade656a0/core-bundle/src/Routing/RouteProvider.php#L231-L233

It neither provides a `303` with `Cache-Control: no-store` option, so our choices seem to be `'permanent' => false` or adding a custom redirect controller.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 27th, we want to change `'permanent' => true,` to `'permanent' => false,`.

**Comment by leofeyer** [comment]
PR for Contao 4.4: #2216

**Comment by leofeyer** [comment]
PR for Contao 4.9: #2221

**Comment by leofeyer** [comment]
PR for Contao 4.10: #2227
