### ISSUE TITLE
Add class "empty" directly to mod_eventlist too

### ISSUE THREAD

**Issue by jankout** [contao/contao#209]
Hello, 

I think it would be nice to add the class _empty_ to the div _mod_eventlist_ because I would usually like to handle the whole div block, not only the message box inside the main div block. I'm not the only one who has this problem - see your forum. Thank you.

**Comment by leofeyer** [comment]
You can adjust the template accordingly – see the forum.

**Comment by jankout** [comment]
Ok. I think it would be better to implement it for the core too. 

it could be small, but significant improvement of the developer experience.

**Comment by m-vo** [comment]
It would be a breaking change as well.

Am Mo., 3. Dez. 2018, 16:28 hat Jan Kout <notifications@github.com>
geschrieben:
