### ISSUE TITLE
Replace Database implementation with DBAL implementation

### ISSUE THREAD

**Issue by tristanlins** [contao/contao#21]
I have written a [Doctrine DBAL implementation](https://github.com/bit3/contao-doctrine-dbal-driver) of the `Database` framework some time ago. For Contao 4 it would make sense to use this implementation to reuse the already existing doctrine dbal connection from the DIC.

**Comment by leofeyer** [comment]
Closed in favor of #31.

**Comment by aschempp** [comment]
I guess you meant https://github.com/contao/core-bundle/pull/31 :D

**Comment by leofeyer** [comment]
Ups, yes I did.
