### ISSUE TITLE
News: in neuen Fenster öffnen funktioniert nicht

### ISSUE THREAD

**Issue by seibtph** [contao/contao#210]
**Affected version(s)**
Contao 4.6.x

**Description**  
Die Option "In neuem Fenster öffnen" funktioniert bei News nicht. Stattdessen wird die Seite im gleichen Fenster geöffnet.

**How to reproduce**  
Ich konnte es auf der Demo-Seite ebenfalls reproduzieren: https://demo.contao.org/en/news.html

1. Beitragseinstellungen einer News öffnen
2. Bei Weiterleitungsziel Individuelle URL auswählen
3. In neuen Fenster öffnen auswählen

**Comment by fritzmg** [comment]
Diese Option bezieht sich nur auf das Teaser Bild, nicht auf die News an sich. Bei aktivierter Option wird das Teaser Bild in einem neuen Fenster bzw. einer Lightbox angezeigt.

**Comment by leofeyer** [comment]
Ich denke @seibtph meint das hier:

<img width="843" alt="" src="https://user-images.githubusercontent.com/1192057/49382913-dda9c780-f717-11e8-9409-d6663cc40489.png">

**Comment by fritzmg** [comment]
Ah, sorry ^_^

**Comment by seibtph** [comment]
@leofeyer Genau das meinte ich.

**Comment by leofeyer** [comment]
Ich kann das Problem in der Onlinedemo nicht reproduzieren:

<img width="763" alt="" src="https://user-images.githubusercontent.com/1192057/49498545-ae0bd400-f86b-11e8-9521-6513d647197f.png">

**Comment by seibtph** [comment]
Wenn man der News ein Bild hinzufügt wird der Link nicht im neuen Fenster geöffnet. Beim Titel funktioniert es, das stimmt.

![contao-46-news-bildlink](https://user-images.githubusercontent.com/17127525/49500841-e31b2500-f871-11e8-893f-7b69a084aa0c.png)

**Comment by fritzmg** [comment]
Dass das Bild mit der News verlinkt ist, ist erst vor kurzem hinzu gekommen, daher gab es dieses Problem vorher noch nicht.

Wenn "Großansicht/Neues Fenster" für das Bild __nicht__ ausgewählt wurde, dann sollte der Bildlink vermutlich auch auf die generelle News Einstellung "In neuem Fenster öffnen" reagieren, falls gesetzt.

**Comment by seibtph** [comment]
Die Option "Großansicht/Neues Fenster" beim Bild habe ich gar nicht angehakt.

**Comment by fritzmg** [comment]
Ja, das meine ich ja. Wenn diese Option beim Bild _nicht_ angehakt ist, dann sollte Contao für den Bildlink weiterhin die Option "In neuem Fenster öffnen" berücksichtigen.

Mit _sollte_ meine ich hier: in einer der nächsten Versionen ;)

**Comment by leofeyer** [comment]
Betrifft das nur Contao 4.6 oder auch Contao 4.4?

**Comment by seibtph** [comment]
@leofeyer Dass das Bild in der News verlinkt ist, ist ja erst in der 4.6 dazugekommen? Dann betrifft es nur die 4.6.

**Comment by leofeyer** [comment]
Behoben in b9c192a2424d4dd0c208f2eea3671b3006f22c9b.

**Comment by V15** [comment]
Das Problem besteht in der aktuellen 4.9.x ebenfalls.

Ich habe bei einer Nachricht kein Bild eingefügt, nur bei dem Weiterleitungsziel "Individuelle URL" angegeben und den Haken bei "In neuem Fenster öffnen" gesetzt.

Bei Klick auf die Überschrift oder "Weiterlesen" wird die Seite im gleichen Fenster geöffnet.
Im Quelltext wird kein "target" Element ausgegeben.

Das lässt sich auch in der Demo nachvollziehen: Einfach bei einer der Meldungen eine URL angeben und den Haken setzen.

**Comment by fritzmg** [comment]
@V15 I think you mean this: https://github.com/contao/contao/issues/2947 ?

**Comment by V15** [comment]
@fritzmg Yes, you are right!
