### ISSUE TITLE
Change offered redirect statuses for redirect pages to 301, 303, 307

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2100]
Currently, internal and external redirect pages offer the following redirect statuses:

* `301`
* `302`

It would make sense to replace `302` with `303` and additionally offer `307`. This way you can better control whether the client should always switch to a `GET` request for the new URL (» `303`) or if the original request type (e.g. `POST`) should be used again (» `307`).

**Comment by ausi** [comment]
But then we would need to offer a `308` too, right?

I think offering 301 and 303 should be enough. Most users would not understand what “keep the HTTP method” means anyway.

**Comment by leofeyer** [comment]
> But then we would need to offer a `308` too, right?

Yes.

**Comment by leofeyer** [comment]
As discussed in Mumble on October 22nd, we want to stick with "permanent" (301) and "temporary" (303).

**Comment by leofeyer** [comment]
@fritzmg I think this issue can be closed, can't it? Contao already uses 303 and Symfony uses whatever it uses (currently 302 I think, however, it does not matter, because 302 and 303 are factually the same).

**Comment by fritzmg** [comment]
Yes, also with a Page Controller it's pretty easy to create a custom page type anyway, if you a different response status and the flexibility within your site structure.
