### ISSUE TITLE
Password modules do not respect onload_callback of tl_member

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#2108]
**Affected version(s)**

Contao 4.4, 4.9, 4.10

**Description**

Both `ModuleRegistration` and `ModulePersonalData` check for onload_callbacks in tl_member since they use fields from the DCA. `ModulePassword` and `ModuleChangePassword` also loads `username` and `email` from the DCA but do not respect any onload_callbacks which imho is an inconsistency.

https://github.com/contao/contao/blob/a4dffd5495cace44948096d0e9481a32617b4d21/core-bundle/src/Resources/contao/modules/ModuleRegistration.php#L73-L88

**Comment by leofeyer** [comment]
FYI, `ModuleChangePassword` does not trigger the onload callbacks, either.

**Comment by leofeyer** [comment]
As discussed in Mumble on October 22nd, we want to add the callback in the two classes.

**Comment by fritzmg** [comment]
I just noticed that the same inconsistency exists for the `load_callback` of the individual fields. The `load_callback` is executed in `ModulePersonalData`, but not in any of the other member modules. I'll provide a PR.
