### ISSUE TITLE
TinyMCE funktioniert nach Update 4.10.0-RC2 > 4.10.0-RC3 nicht mehr (Problem 1)

### ISSUE THREAD

**Issue by ghost** [contao/contao#2109]
Nach dem Update 4.10.0-RC2 > 4.10.0-RC3 via Manager funktioniert TinyMCE nicht mehr. Wenn ich es recht gesehen habe, ist mit dem Update auch eine Wechsel TinyMCE4 > TinyMCE5 verbunden. In .../assets steht immer noch der Ordner TinyMCE4. Im BE > Profil ist "Rich Text Editor verwenden" aktiviert. Das Datenbankupdate ist gemacht, ebenso die Systemwartung.

Beim Klick auf "Seitenstruktur" im BE bekam ich nach dem Update ab und zu die unten angehängte Meldung. Neuerdings ist "Seitenstruktur" im BE gar nicht mehr zugänglich - die Fehlermeldung erscheint bei jedem Aufruf. 

![fehlermeldung](https://user-images.githubusercontent.com/5571037/89544855-e747d480-d802-11ea-8e4f-ae3efc00b628.PNG)

**Comment by aschempp** [comment]
see https://github.com/contao/contao/issues/2112
