### ISSUE TITLE
Logout-Seite: Weiterleitungsseite oder "Zur zuletzt besuchten Seite"

### ISSUE THREAD

**Issue by zonky2** [contao/contao#211]
Im Seitentyp "Logout" müsste m.E. keine Weiterleitungsseite definiert werden, wenn die Checkbox "Zur zuletzt besuchten Seite" gesetzt wird - aktuell kommt eine Fehlermeldung

![screenshot_290](https://user-images.githubusercontent.com/1045318/49424173-1c806180-f79a-11e8-854e-105de871eaba.jpg)

Vorschlag: 
* Checkbox und PagePicker Position wechseln
* PagePicker ausblenden, wenn Checkbox gesetzt ist

**Comment by ausi** [comment]
Wenn die zuletzt besuchte Seite nicht ermittelt werden kann, wird auf die Weiterleitungsseite geleitet. Das ist vermutlich der Grund warum die Weiterleitungsseite auch bei aktivierter Checkbox ein Pflichtfeld ist.

**Comment by zonky2** [comment]
dann wäre ein Hinweis auf die Fallback-Funktion im Text des Pickers sicher prima...
