### ISSUE TITLE
Empty URL in getCandidates()

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2113]
The following exception will be thrown if there is a double slash in the URL, e.g. `https://domain.com//`:

https://github.com/contao/contao/blob/a4dffd5495cace44948096d0e9481a32617b4d21/core-bundle/src/Routing/Candidates/AbstractCandidates.php#L88-L90

This causes a lot of useless log entries and/or Sentry notifications, because there is nothing I can do about it. Therefore, can we either

- not throw an exception at all or
- throw a dedicated exception that I can ignore in Sentry?

**Comment by aschempp** [comment]
well what should happen in that case? Should we show a 404 page (because that route can't exist) or should we redirect or should we threat it as the root page?

**Comment by leofeyer** [comment]
Maybe throw a `ResourceNotFoundException` like we do here?

https://github.com/contao/contao/blob/a4dffd5495cace44948096d0e9481a32617b4d21/core-bundle/src/Routing/Enhancer/InputEnhancer.php#L74-L77

**Comment by aschempp** [comment]
I'd rather like to know how a normal webserver behaves if you request that URL. Would it serve the index.html ?

**Comment by leofeyer** [comment]
That depends on the web server. Apple's server normalizes double slashes: https://www.apple.com//

**Comment by leofeyer** [comment]
So does GitHub: https://github.com//contao/contao

**Comment by aschempp** [comment]
Thats funny… https://github.com/////contao/contao should we do the same?

**Comment by leofeyer** [comment]
Not sure. Right now, we are responding with a 404 status if there is a double slash in the URL, e.g. https://contao.org/de//download.html. I consider this more reasonable that normalizing double slashes.

@contao/developers /cc

**Comment by fritzmg** [comment]
Apache normalizes it too: https://docs.contao.org/dev/////getting-started//////

// edit: but I am also in favor of responding with 404 🤷

**Comment by leofeyer** [comment]
Ok, so as a first step, we should send a 404 response so the handling of `https://domain.com//` is consistent with the handling of `https://domain.com/de//download.html`. Then, in a second step, we can discuss whether we want to normalize double slashes or not. Agreed?
