### ISSUE TITLE
Insertag {{env::request}} + Event full view: &times -> ×

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2114]
**Affected version(s)**

Contao 4.9.4

**Description**
If you put the insert tag

`{{env::request}}`

into the template of a event full view module it parse the `&time=` parameter to × (=> `&time;`)

Example:

Page url: domain.tld/details/event-sept-dez-2020.html?day=20200922&times=1600725600,1608245999

result of `{{env::request}}`:

![grafik](https://user-images.githubusercontent.com/1645099/89561055-3f3d0600-d818-11ea-970f-87533a843e32.png)

**Comment by ausi** [comment]
Does it work with `{{env::request|specialchars}}` ?

**Comment by math-GH** [comment]
`{{env::request|specialchars}}` works fine.

![grafik](https://user-images.githubusercontent.com/1645099/89632822-24fc3a00-d8a3-11ea-83a2-b678fe5280f1.png)

**Comment by math-GH** [comment]
`$_SERVER['REQUEST_URI'];` does the same result like `{{env::request}}`.

The `&times` (without ";" ) makes more problems: https://stackoverflow.com/questions/16834320/using-times-word-in-html-changes-to-%C3%97

**Comment by leofeyer** [comment]
@ausi Should we apply `specialchars()` to the request insert tag by default?

**Comment by ausi** [comment]
> Should we apply `specialchars()` to the request insert tag by default?

Using `{{env::request}}` inside CSS or JS code would break then.

I think using `{{env::request|specialchars}}` for outputting the URL in an HTML context is the correct solution for this issue.
