### ISSUE TITLE
Disable language redirect not working

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#2116]
**Affected version(s)**
Contao 4.10.x-dev (06.08.2020, 09:09)

**Description**
I'd like to test the new feature "Disable language redirect". But in my configuration it doesn't work as expected.

**Configuration**
Root-Page A:
- URL_prefix: deutsch
- Language: de
- Language fallback: check
- Disable language redirect: empty

Root-Page B:
- URL_prefix: englisch
- Language: en
- Language fallback: empty
- Disable language redirect: check

My Browser is configured to use "en - english" as default language

**Expected behavior**
If I browse to my Homepage, always the pages from "de" would be served.
But this wouldn't happen. Instead I get the pages from "en" as configured in my Browser.

Did I something wrong?

**Comment by ngdot** [comment]
Try to remove the prefix from Root-Page A.

**Comment by contaoacademy** [comment]
If I remove the prefix from Root-Page A I get always page A. Also if I don't check the option in my Root-Page B.

@aschempp
Could you explain the correct settings. Does this option only work, if I remove the prefix from the preferred main Root-Page?

**Comment by leofeyer** [comment]
Yes, I think so. This feature is the "apple.com" case, where you have your main website without language prefix and the translations with language prefix.

* https://www.apple.com
* https://www.apple.com/iphone/
* https://www.apple.com/de/
* https://www.apple.com/de/iphone/

**Comment by contaoacademy** [comment]
Ok, maybe we should add a small notice in the description, that the primary Page-Root must have an empty prefix.
What do you think?

**Comment by fritzmg** [comment]
That seems counter-intuitive though.

**Comment by contaoacademy** [comment]
@fritzmg The best way would be to add this specific configuration to the docs :-)

**Comment by fritzmg** [comment]
Well yeah but even then, why should this only work for when the website root has no prefix? We might as well implement an error message saying that you can't enable this option together with having a prefix. But then again, I would expect this option to work with or without prefix.

**Comment by aschempp** [comment]
> Could you explain the correct settings. Does this option only work, if I remove the prefix from the preferred main Root-Page?

No, it's supposed to work in either case. Are you sure the redirect is not a cache from your browser? I just tried it locally, and it seems to work correctly. Be aware that you are still redirected to the fallback language, if none of the root pages have the language redirect enabled.

You can also get more information by enabling the debug mode in Contao. The Symfony inspector will show you the current and previous routes/controllers in the left bottom screen:
<img width="337" alt="Bildschirmfoto 2020-08-11 um 17 04 32" src="https://user-images.githubusercontent.com/1073273/89914099-ca414600-dbf4-11ea-8ad3-468ed2bb68bf.png">

**Comment by contaoacademy** [comment]
I did some more tests and found out the following.

If I configure the homepage from DE and EN both with alias "index", then it does not work.

As soon as I change the alias to "home-de" and "home-en" for both homepages, the redirect works as expected.

So it looks like a problem with the alias "index".
Can somebody confirm this?

**Comment by aschempp** [comment]
This was it! The property was not inherited to the child pages, therefore the redirect was added for the `index` page. Fixed in https://github.com/contao/contao/pull/2151
