### ISSUE TITLE
Cannot insert url_prefix/suffix in root page

### ISSUE THREAD

**Issue by Seefahrer** [contao/contao#2119]
Affected version: Contao 4.10.0-RC3 only (RC2 is ok).

Despite removing the parameters 
`
prepend_locale: false
url_suffix: ''
`

in "/config/config.yml" I cannot insert the corresponding parameters in the websites root-page setup.
The input fields are greyed out with info that I need to disable the legacy routing before I'm allowed to set up any parameter in this respect. Under RC2 it was working fine as to be expected.
Without a.m. parameters in config.yml I run into a "Too many redirects error" when calling my site.

**Comment by aschempp** [comment]
Yes, this has been changed in #2065 
You need to set the following in your `config.yml`:
```yaml
contao:
    legacy_routing: false
```
