### ISSUE TITLE
Exception cannot be caught?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2123]
**Affected version(s)**

Contao 4.9+

**Description**

According to Psalm, the exception in the following two methods cannot be caught, because it does not extend `Exception` or implement `Throwable` (see https://github.com/avalanche123/Imagine/blob/master/src/Exception/Exception.php):

https://github.com/contao/contao/blob/4b882d86b9bc8a74e4c8282bf53254cd5827cebf/core-bundle/src/Image/LegacyResizer.php#L96-L98

https://github.com/contao/contao/blob/4b882d86b9bc8a74e4c8282bf53254cd5827cebf/core-bundle/src/Image/LegacyResizer.php#L105-L107

@ausi Is this correct?

**Comment by leofeyer** [comment]
Forgot to mention: You have to set the Psalm error level to `6` to see the error.

**Comment by fritzmg** [comment]
`Imagine\Exception\Exception` is an interface that Imagine implements for all its exceptions. Catching exceptions via an interface works:

https://3v4l.org/3H9rn

**Comment by ausi** [comment]
Would `/** @var \Throwable&ImagineException $exception */` help?

**Comment by ausi** [comment]
We clould also replace the type `\Throwable` for the return value and the parameter in `enhanceImagineException()` to `ImagineException`. The `\RuntimeException` needs to be replaced with a `RuntimeException` from Imagine then.

**Comment by aschempp** [comment]
I don't think changing this for a code validation tool is correct. It's correct to catch an interface, therefore `psalm` is wrong here, not our code.

**Comment by ausi** [comment]
Fix: #2128
