### ISSUE TITLE
Template renaming back to original name: error

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2126]
**Affected version(s)**

Contao 4.9.4

**Description**

I tried to rename the template "event_list_xx.html5" (on "root" level) back to the origial name "event_list.html5" but I get this error
![grafik](https://user-images.githubusercontent.com/1645099/89720188-e2844b80-d9cf-11ea-82b9-471459d390fc.png)

but there is no another "event_list.html5"
![grafik](https://user-images.githubusercontent.com/1645099/89720210-18293480-d9d0-11ea-8397-1fb28c287de7.png)

After I moved the template in a subfolder I could rename it
![grafik](https://user-images.githubusercontent.com/1645099/89720274-7ce48f00-d9d0-11ea-85c8-3b141720faff.png)

And then I moved back to "root" level. Without any trouble.

**Comment by leofeyer** [comment]
I was not able to reproduce this issue. Does it occur with any template or just `event_list`?

**Comment by math-GH** [comment]
cannot reproduce it anymore.... mhm... strange..
