### ISSUE TITLE
Installtool unter 4.5.14 wirft Fehler 

### ISSUE THREAD

**Issue by michb** [contao/contao#213]
Wenn man ein Contao Version 4.5(.14) neu aufsetzt erhält man nach dem "aktualisieren" der Datenbank im Installtool eine Fehler. Der Fehler dürfte auch bei Installationen auftreten die geupdated wurden, hab ich aber nun nicht getestet,
![image](https://user-images.githubusercontent.com/17873830/49440890-35523c80-f7c5-11e8-8103-a41246ccf409.png)

Unter Version 4.6.9 tritt dieser Fehler nicht auf.

PHP Version 7.1
Datenbank: 10.1.23-MariaDB-9

**Beschreibung**
Im Stacktrace sieht man, dass der seinen Ursprung in InstallTool.php -> hasOldDatabase() liegt.

Problem ist hierbei, dass der Quelltext zwar gleich ist, sich aber unterschiedlich verhält:
```php
        $sql = $this->connection
            ->getDatabasePlatform()
            ->getListTableColumnsSQL('tl_layout', $this->connection->getDatabase())
        ;
        $column = $this->connection->fetchAssoc($sql." AND COLUMN_NAME = 'sections'");
```
Unter 4.5 erhält man in `$sql`
```sql
SELECT
	COLUMN_NAME AS Field,
	COLUMN_TYPE AS Type,
	IS_NULLABLE AS `Null`,
	COLUMN_KEY AS `Key`,
	COLUMN_DEFAULT AS `Default`,
	EXTRA AS Extra,
	COLUMN_COMMENT AS COMMENT,
	CHARACTER_SET_NAME AS CharacterSet,
	COLLATION_NAME AS COLLATION
FROM
	information_schema. COLUMNS
WHERE
	TABLE_SCHEMA = 'contao4514'
AND TABLE_NAME = 'tl_layout'
ORDER BY
	ORDINAL_POSITION ASC
```
und unter 4.6
```sql
SELECT
	COLUMN_NAME AS Field,
	COLUMN_TYPE AS Type,
	IS_NULLABLE AS `Null`,
	COLUMN_KEY AS `Key`,
	COLUMN_DEFAULT AS `Default`,
	EXTRA AS Extra,
	COLUMN_COMMENT AS COMMENT,
	CHARACTER_SET_NAME AS CharacterSet,
	COLLATION_NAME AS COLLATION
FROM
	information_schema. COLUMNS
WHERE
	TABLE_SCHEMA = 'contao469'
AND TABLE_NAME = 'tl_layout'
```
Da nun aber an diese Abfragen noch ein `Where`-Staetement angehängt wird kommt es bei 4.5 zu Fehler, da dort bereits ein Order By angegeben ist.

**How to reproduce**  

- Contao 4.5.* installieren via composer
- Installtool leere Datenbank angeben
- Datenbank aktulisieren
- Dann erscheint der Fehler

**Comment by Toflar** [comment]
Contao 4.5 ist nicht mehr supported. https://contao.org/en/release-plan.html

**Comment by m-vo** [comment]
4.4 oder 4.6 / 4.5 ist unsupported.

**Comment by fritzmg** [comment]
Duplicate of #212

**Comment by michb** [comment]
ok, danke daran hatte ich nicht gedacht. Kann also geschlossen werden
