### ISSUE TITLE
Exception while using new Feature Expression Syntax

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#2130]
**Affected version(s)**
Version 4.10.x-dev (06.08.2020)

**Notice:**
I added the extension "Notification Center", maybe this is not a Contao core error.

**Description**
I tested the new feature "Simple Token with Expression Syntax" added by @Toflar 
https://github.com/contao/contao/pull/1509

**Setup**
Simple Contao form with 2 numeric fields

Here's my Expression:
```
{if form_wert1+form_wert2<10}
Summe kleiner 10
{endif}

{if form_wert1+form_wert2>=10}
Summe größer oder gleich 10
{endif}
```

After submitting the form, I get the following error:

`[2020-08-10 09:19:33] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Variable "form_wert2HASTE" is not valid around position 12 for expression `form_wert1+form_wert2HASTE-TAG-OPEN-64c8ab8e1ad15fedebbabc3ef6cc9cc810`." at /www/htdocs/xxx/xxx/demo1/vendor/contao/core-bundle/src/Util/SimpleTokenParser.php line 133 {"exception":"[object] (InvalidArgumentException(code: 0): Variable \"form_wert2HASTE\" is not valid around position 12 for expression `form_wert1+form_wert2HASTE-TAG-OPEN-64c8ab8e1ad15fedebbabc3ef6cc9cc810`. at /www/htdocs/xxx/xxx/demo1/vendor/contao/core-bundle/src/Util/SimpleTokenParser.php:133, Symfony\\Component\\ExpressionLanguage\\SyntaxError(code: 0): Variable \"form_wert2HASTE\" is not valid around position 12 for expression `form_wert1+form_wert2HASTE-TAG-OPEN-64c8ab8e1ad15fedebbabc3ef6cc9cc810`. at /www/htdocs/xxx/xxx/demo1/vendor/symfony/expression-language/Parser.php:203)"} []`

**Comment by fritzmg** [comment]
That's an issue with Contao Haste, not Contao itself. The Notification Center uses `\Haste\Util\StringUtil::recursiveReplaceTokensAndTags` which in turn replaces all intances of `<` and `>` with `HASTE-TAG-OPEN-…` and `HASTE-TAG-CLOSE-…` respectively, before the simple tokens are parsed. Therefore you cannot use such comparisons in the Notification Center currently.

**Comment by contaoacademy** [comment]
@fritzmg Thx. Should I close this ticket or should this ticket moved to Haste or Notifification Center?

**Comment by fritzmg** [comment]
It needs to be changed within Haste - or Notification Center should stop using `\Haste\Util\StringUtil` (though that's unlikely I guess).

**Comment by contaoacademy** [comment]
I closed the ticket and have opened a new one.
https://github.com/codefog/contao-haste/issues/150
