### ISSUE TITLE
Disable "Disable language redirect" in legacy routing mode

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#2131]
**Affected version(s)**
Version 4.10.x-dev (06.08.2020)

**Description**
I think the option "Disable language redirect" must be disabled if routing uses the legacy mode.

![screen-20200810_G7O9mE3q@2x](https://user-images.githubusercontent.com/23719181/89761829-90d2e280-daef-11ea-9fe1-218c6e728953.jpg)

**Comment by aschempp** [comment]
This technically works in any mode, you can use it to exclude the user from being redirected to certain languages. I think it _could_ still be useful if you want all users to always go to `/en/` and never detect the browser language?

**Comment by contaoacademy** [comment]
@aschempp Ok, I didn't test this feature under legacy mode. If this works as well, we could close the ticket

**Comment by leofeyer** [comment]
We should not add new features to the legacy routing, therefore I prefer to disable the checkbox.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2145
