### ISSUE TITLE
Missing skin in contao-components/tinymce4: ^5.0

### ISSUE THREAD

**Issue by bytehead** [contao/contao#2135]
**Affected version(s)**

Contao 4.10-RC3

**Description**

If you want to edit comments or answer to comments, the textareas are broken.

Missing skin in `contao` in `contao-components/tinymce4`: `^5.0`:
https://github.com/contao-components/tinymce4/blob/5.x/js/skins/contao/skin.min.css

**Comment by leofeyer** [comment]
You have to adjust your `be_tinyMCE.html5` template accordingly.

https://github.com/contao/contao/blob/4.10/core-bundle/src/Resources/contao/templates/backend/be_tinyMCE.html5

The `skin` option is no longer available in TinyMCE 5.

**Comment by bytehead** [comment]
🙏

**Comment by leofeyer** [comment]
Or even better, make use of template inheritance when adjusting TinyMCE templates:

https://github.com/contao/contao/blob/4.10/core-bundle/src/Resources/contao/templates/backend/be_tinyNews.html5

**Comment by bytehead** [comment]
Perfect, thanks!
