### ISSUE TITLE
Disable SchemaManager cache during migrations

### ISSUE THREAD

**Issue by ausi** [contao/contao#2138]
**Affected version(s)**

Contao 4.9

**Description**

It seems that the `SchemaManager` uses a cache (cc @aschempp) which creates problems when running migrations because the table structure will most likely be changed in most migrations. We should disable this cache in the migrations command and in the install tool.

**Comment by leofeyer** [comment]
I could not find a schema cache. Can you point me to it, please?

**Comment by ausi** [comment]
I didn’t find one either. @aschempp ?

**Comment by leofeyer** [comment]
As discussed in Mumble on September 24th, this needs to be debugged the next time the error occurs.

**Comment by aschempp** [comment]
I was unable to reproduce it, so let's just close it for now.
