### ISSUE TITLE
Form is rendered twice

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#214]
**Affected version(s)**

Tests in Contao 4.6, but probably 4.4 will be also affected.

**Description**  

I stumpled upon an issue that a `parseTemplate` hook, which should listen to the `form_wrapper` template got called twice, I realised that the form template is parsed twice.

*Rendered in the hybrid*
https://github.com/contao/contao/blob/10ba74288a43fef2dadd37e970130d2ce4dd35ed/core-bundle/src/Resources/contao/classes/Hybrid.php#L259

*Rendered also in the compile method even though the return value is ignored.*

https://github.com/contao/contao/blob/10ba74288a43fef2dadd37e970130d2ce4dd35ed/core-bundle/src/Resources/contao/classes/Hybrid.php#L236

https://github.com/contao/contao/blob/10ba74288a43fef2dadd37e970130d2ce4dd35ed/core-bundle/src/Resources/contao/forms/Form.php#L298

I guess that the form template shouldn't be parsed in the `compile()` method. I however don't know if you consider it a BC break removing it, as the docs says it would return a string.

**How to reproduce**  

1. Create a form
2. Create a `parseTemplate` hook which manipulates only the `form_wrapper` template
3. Submit the form with an error so that no redirect happens
4. The `parseTemplate` hook is called twice

/cc @frontendschlampe

**Comment by leofeyer** [comment]
Yes, that seems to be a bug. The `Form::compile()` method is not supposed to return anything, therefore `return $this->Template->parse()` needs to be removed.

**Comment by leofeyer** [comment]
Fixed in 224ba0917c7f4f9478bd810b17ad4193213cf8d1.
