### ISSUE TITLE
Rerendering of articles might lead to unexpected behaviour

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2147]
**Affected version(s)**

- `~4.4.50`
- `^4.9.4`

**Description**

Since #1803 an article might be rendered twice which causes several issues.

1. Content elements, modules might be rendered twice. Error messages, e.g. of a login form get lost because it get's overriden
2. Frontend modules which might trigger some actions (sending mails, making api calls for some tracking/logging services etc.) will be triggered multiple times
3. Custom css classes defined in a content element for a module get applied multiple times
4. It's raises the rendering cost just for the sake of some stupid `last` classes

**How to reproduce it**

1. Create a page with two articles
2. Create a login form on the first article
3. Protect the second article
4. Try to login with invalid data. You should see an error message, but you doesn't

**Proposed solution**
A placeholder might be injected as class which gets replaced with the last class or an empty string if not last.

**Note**
It cannot be reproduced in the online demo as it still runs 4.9.3.

/cc @frontendschlampe

**Comment by aschempp** [comment]
Good idea with the placeholders!

**Comment by ausi** [comment]
I don’t like a string replacement of the template output as we cannot know what the template does with `$this->class`. It might need context specific escaping or the template-code could check if `last` is included in the class names.

An alternative would be to iterate through the rows array backwards as soon we got our `first` element. But this would still have issues for articles with only one single element.

**Comment by leofeyer** [comment]
IMHO, we should revert the changes from #1803 and remove the classes entirely, as @Toflar has suggested in https://github.com/contao/contao/issues/239#issuecomment-454016655.

**Comment by dmolineus** [comment]
I suggest to remove the classes at all as suggested by @Toflar here https://github.com/contao/contao/issues/239#issuecomment-454016655.

Edit: @leofeyer was faster. :-)

**Comment by fritzmg** [comment]
I also agree with @Toflar 's original [comment](https://github.com/contao/contao/issues/239#issuecomment-454016655).

**Comment by Toflar** [comment]
I also agree with @Toflar 's original [comment](https://github.com/contao/contao/issues/239#issuecomment-454016655).

**Comment by ausi** [comment]
> IMHO, we should revert the changes from #1803 and remove the classes entirely, as @Toflar has suggested in [#239 (comment)](https://github.com/contao/contao/issues/239#issuecomment-454016655).

Agree. Removing the classes will go into version 4.11?

**Comment by fritzmg** [comment]
I'd be fine with removing it in 4.10 already and restoring the old behavior in 4.4 and 4.9.

**Comment by leofeyer** [comment]
> I'd be fine with removing it in 4.10 already and restoring the old behavior in 4.4 and 4.9.

Me too. 👍🏻

**Comment by leofeyer** [comment]
Moving the issue to the 4.10 milestone as a reminder to remove the CSS classes entirely in Contao 4.10.
