### ISSUE TITLE
Workaround for cookie SameSite attribute doesn't seem to work

### ISSUE THREAD

**Issue by plorenz-etes** [contao/contao#2158]
**Affected version(s)**

Contao 4.4.51
Contao 4.9.5

**Description**

The workaround introduced in #2117 and #2118 doesn't seem to work correctly.
After upgrading to the new Contao versions, Firefox still shows this message:

```
Cookie “PHPSESSID” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

When viewing the cookie list, the following can be seen in Contao 4.4:

![contao44](https://user-images.githubusercontent.com/43336309/90389001-0eb36280-e089-11ea-9537-ab61a1f8211a.png)

And this can be seen in 4.9:

![contao49](https://user-images.githubusercontent.com/43336309/90389023-15da7080-e089-11ea-8175-9fbcecca24f4.png)

As you can see, the cookies don't have the "SameSite" attribute set at all - and for some reason, the "Secure" flag is only set in 4.9 but not in 4.4. However, both installations are hosted at the same hosting provider and both use HTTPS only.

The Set-Cookie header in the HTTP response looks like this:

Contao 4.4:

`Set-Cookie: PHPSESSID=7mlo7bemguq3l8nunnvjuo0345; path=/; httponly`

Contao 4.9:

`Set-Cookie: PHPSESSID=oe3nsnk11ngdrl052pmuksmac2; path=/; secure; httponly`

Strangely enough, Firefox complains about this - but Chrome doesn't.

Tested in the following browsers:
Firefox 78
Firefox 79
Chrome 84
Chromium 84

**Comment by fritzmg** [comment]
> The workaround introduced in #2117 and #2118 doesn't seem to work correctly.

According to your output, the changes in #2118 work. As you can see, the cookie does have the _Secure_ flag now.

Regarding the changes in Contao 4.4: try to manually delete the app.php and app_dev.php and then run `composer install` again.

**Comment by plorenz-etes** [comment]
Thank you for the reply.
Your hint for Contao 4.4 is working, the "Secure" flag is set now. Is there a way to automate this procedure so other people don't run into this issue?

For some reason, the warning now also disappeared in Firefox.

**Comment by fritzmg** [comment]
> Is there a way to automate this procedure so other people don't run into this issue?

@contao/developers should we implement some sort of Migration for this? Currently `contao:install-web-dir` won't update the `app.php` or `app_dev.php` (in case you made changes to it).

> For some reason, the warning now also disappeared in Firefox.

What do you mean "for some reason"? It disappeared, because you fixed it 😁

**Comment by plorenz-etes** [comment]
> What do you mean "for some reason"? It disappeared, because you fixed it grin

I mean, because the warning was also present in my Contao 4.9 installation which I didn't touch ;)

**Comment by ausi** [comment]
> Currently `contao:install-web-dir` won't update the `app.php` or `app_dev.php` (in case you made changes to it).

This is only the case in Contao 4.4, right? AFAIK the files get replaced in the install-web-dir command of Contao 4.9.

**Comment by fritzmg** [comment]
Yes, the files are replaced in Contao 4.9, but not in 4.4.

**Comment by ausi** [comment]
I’m not sure if we should change this in a bugfix release.

**Comment by leofeyer** [comment]
If it is OK to overwrite the files in Contao 4.9, it should be OK to overwrite them in Contao 4.4 as well, shouldn't it?

**Comment by fritzmg** [comment]
I think not, because in Contao 4.4 you need to edit your `app.php` in order to add trusted proxies for example. At least I assume that's why we don't overwrite it in Contao 4.4.

**Comment by Toflar** [comment]
All good then, just leave it as is. 4.4 users need to adjust their entry point. Users of later versions benefit from having things done automatically for them.
