### ISSUE TITLE
External Js / global tl_body order.

### ISSUE THREAD

**Issue by sitenzo** [contao/contao#2159]
**Affected version(s)**

Contao 4.9

**Description**

In the [documentation](https://docs.contao.org/dev/framework/asset-management/) it states _$GLOBALS['TL_BODY']_ : _Contains HTML code to be included before < /body>._ 

When i add for example 
`$GLOBALS['TL_BODY'][] =
\Contao\Template::generateScriptTag('bundles/mybundle/datatables/media/js/jquery.dataTables.min.js', false, null);`

It will output before all the external JS because [PageRegular.php#L733-L749 (ExternalJS)](https://github.com/contao/contao/blob/6bce4398a31846af0e72ee2d67c6527084aa57a1/core-bundle/src/Resources/contao/pages/PageRegular.php#L733-L749) is after [PageRegular.php#L715-L731 (TL_BODY)](https://github.com/contao/contao/blob/6bce4398a31846af0e72ee2d67c6527084aa57a1/core-bundle/src/Resources/contao/pages/PageRegular.php#L715-L731)

I have a template with a lot of external JS, how do i output after externalJS.

**Comment by fritzmg** [comment]
You mean your script depends on another script that is included via a JavaScript template? I think you should restructure that as I find it not safe to rely on that.

**Comment by sitenzo** [comment]
In my page layout i have some JS files including Jquery and other dependence.
My custom bundle needs those dependence.

Is there a way to hook into $objLayout->script to add my scsripts.

**Comment by fritzmg** [comment]
If you enable jQuery in your page layout, then it is added to the `<head>` by Contao. If your script only depends on jQuery, then it does not really matter where you include it, as jQuery will always be loaded first.

> Is there a way to hook into $objLayout->script to add my scsripts.

You could do it with a `getPageLayout` hook, but I am not sure that's really necessary for you.
