### ISSUE TITLE
Comments module: abo mail confirmation

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2160]
**Affected version(s)**

Contao 4.9.5

**Description**
The author of a comment can subscribe to the following comments. He/She has to confirm it and gets an email.

I think, that the default (German) email subject is not correct:

"Ihr Newsletter-Abonnement"

I think it is NOT an newslette subscription. It is just a subscribtion or a comments subscribtion, because it is not the newsletter module.

![grafik](https://user-images.githubusercontent.com/1645099/90445495-08040a00-e0e0-11ea-98b3-0f86132eded2.png)

**Comment by leofeyer** [comment]
I have adjusted the German translation accordingly.
