### ISSUE TITLE
Set MAILER_DSN default to native://default

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2164]
This is a reminder issue for myself in order to set the `MAILER_DSN` env var by default to `native://default`, once Symfony 5.2 has been released: https://github.com/symfony/symfony/pull/36131

This will configure the Mailer to use the "native configuration" from the `php.ini` - which in turn will reduce the likeliness of having to define an SMTP server yourself on some hosting environments. The reason being that apparently on some hosting environments using `sendmail` would still work - but not with the default sendmail command parameters that the Swiftmailer Bundle uses for instance. So it would work with `/usr/sbin/sendmail -t` instead of `/usr/sbin/sendmail -bs` for example.

Under the assumption this is correctly configured by the hoster in the `php.ini`, sending mails should then work out of the box with Contao 4.11 in such cases, without the need to either set the sendmail command parameters or define an SMTP server yourself.

**Comment by aschempp** [comment]
> once Symfony 5.2 has been released

That would also be the minimum requirement though, right?

**Comment by fritzmg** [comment]
Well if we allow lower Symfony Versions we can check for the version and only set the default to `native://default` accordingly.
