### ISSUE TITLE
 TinyMCE5 is not working correctly

### ISSUE THREAD

**Issue by hinzke** [contao/contao#2165]
**Affected version(s)**

Contao 4.10

**Description**

TinyMCE5 is not working correctly after Update from Version 4.9.5

![grafik](https://user-images.githubusercontent.com/36923405/90502997-07568c80-e14f-11ea-8b3b-f0548b1f7fde.png)

**Comment by fritzmg** [comment]
Are you using a custom `be_tinyMCE` template? If yes, then you need to delete/adjust that.

**Comment by hinzke** [comment]
No, this is a clean installation without extra templates

**Comment by leofeyer** [comment]
Looks like a browser cache issue to me. Please try purging the browser cache or using a different browser.

**Comment by hinzke** [comment]
Omg, that's it
Thanks
