### ISSUE TITLE
Update from 3.3 to 4.6 doesn't find tl_image_size

### ISSUE THREAD

**Issue by Olli** [contao/contao#217]
Update from 3.3 to 4.6 gives  the error: 
`
An exception occurred while executing '     SELECT                 id             FROM                 tl_image_size         ':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'table.tl_image_size' doesn't exist" at /path/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing '\n            SELECT\n                id\n            FROM\n                tl_image_size\n        ':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'table.tl_image_size' doesn't exist`

**How to reproduce**  
1. Install a 4.6.10. 
2. Open /contao/install 
3. use a existing database from 3.3 .

**Comment by fritzmg** [comment]
> 3\. use a existing database from 3.3 .

You cannot update a Contao 3.3 installation to Contao 4. You need to update to the latest Contao 3.5 version first.

**Comment by Olli** [comment]
Ok that's something I didn't know. I just added the tl_image_size and tl_image_size_item table structure and it obviously worked. 
Ok thanks.

**Comment by Olli** [comment]
No it didn't work ... the image-GUID thing make my life hard ;-)

**Comment by fritzmg** [comment]
Just update to Contao 3.5.36 first ;)
