### ISSUE TITLE
Image sizes: Options PNG to WEBP and JPEG to WEBP -> errors

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2170]
**Affected version(s)**

Contao 4.9.5

**Description**

image size. Options PNG to WEBP and JPEG to WEBP are enabled.
![grafik](https://user-images.githubusercontent.com/1645099/90560800-f2561980-e19f-11ea-9d52-d2f0f85588b1.png)

result:
errors in error log
![grafik](https://user-images.githubusercontent.com/1645099/90560657-b9b64000-e19f-11ea-99ee-4ca4430a8d5b.png)

and the src="" in the <img> is empty (the image will not shown in the frontend)

(I use not ImageMagick. I use GD as here described: https://github.com/contao/contao/issues/1913)

After I unchecked the PNG-WEBP and JPEG->WEBP the images are shown.

**Comment by ausi** [comment]
Can you give more details about where this error occurs? 
The log details should show in which function the error got triggered.

**Comment by math-GH** [comment]
![grafik](https://user-images.githubusercontent.com/1645099/90671961-b4b3c800-e255-11ea-9733-6dfd61705bde.png)

**Comment by ausi** [comment]
Please add `dump($size);` to this line: https://github.com/contao/contao/blob/95084f3a4f9b5fb1912d2af0c3d06b0d01f8c333/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1555 and open the frontend in debug mode. The symfony toolbar should then show a dump section with the contents of `$size`.

**Comment by math-GH** [comment]
aus unbekannten Gründen kann ich den Fehler nicht mehr reproduzieren.

Damit würde ich den Bug schließen wollen. Falls er wieder auftritt melde ich mich
