### ISSUE TITLE
{{link_url}} Insert-Tag broken on roots with different domains

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#2171]
**Affected version(s)**

Contao 4.10

**Description**

When creating a link to a page from another root with a different domain the link generated by e.g `{{link_url::1}}` should be an absolute but Contao generates a relative one.

**Steps to reproduce**

- Create two roots with domain `a.com` and `b.com`
- Create a link on `a.com` which links to a site on `b.com` using e.g `{{link_url::1}}`
- The generated link says `/b.com/site.html` which will be interpreted as `http://a.com/b.com/site.html` because of the base path

**Comment by leofeyer** [comment]
@aschempp The `UrlGenerator` in Contao 4.9 automatically sets the reference type to `URL_ABSOLUTE` if the hostname does not match the context hostname:

https://github.com/contao/contao/blob/de1d4b9342fac7ac1df8f614ce36969de45579e8/core-bundle/src/Routing/UrlGenerator.php#L169-L174

Do you want me to adjust the `PageUrlGenerator` accordingly?

**Comment by aschempp** [comment]
That shouldn't be necessary. The (default) routes in Contao 4.9 do not have a host, we manually create them. In Contao 4.10, routes _always_ have a host based on their page settings, as far as I know the system should automatically add the host if the current context does not match it. But I don't know (yet) why this does not happen here …

**Comment by leofeyer** [comment]
I can tell you. The Symfony UrlGenerator sets the reference type to `NETWORK_PATH` if it is not `ABSOLUTE_URL` and the host does not match the route host:

```php
            if ($routeHost !== $host) {
                $host = $routeHost;
                if (self::ABSOLUTE_URL !== $referenceType) {
                    $referenceType = self::NETWORK_PATH;
                }
            }
```

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L264-L269

**Comment by leofeyer** [comment]
@bennyborn Until the issue is resolved, you can add the `|absolute` flag to the insert tag, so it generates the correct URL.

**Comment by aschempp** [comment]
@bennyborn can you please also check if you enabled the `https only` flag in the root page? If you do that (and assuming your website uses https), I would think the protocol is appended automatically.

**Comment by bennyborn** [comment]
@aschempp Just tried it. Enabling `https only` does not seem to have any effect.

**Comment by leofeyer** [comment]
See #2323.
