### ISSUE TITLE
Add List-Unsubscribe Header to decrease SPAM detection

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#2174]
I'm using the contao newsletter in combination with amazon SES and found out, that some email providers like United Internet (GMX, web.de) block my newsletters, when the List-Unsubscribe Header is missing. Furhermore, some email clients like thunderbird detect the newsletter as spam.

**My quick and dirty solution:**
i added the List-Unsubscribe Header by myself 
```
$objEmail->addHeader('List-Unsubscribe', '<mailto:'.$objNewsletter->sender.'?subject=Newsletter-Abmeldung>');
```

[here](https://github.com/contao/newsletter-bundle/blob/master/src/Resources/contao/classes/Newsletter.php#L331).

As it may be possible to put this into an extension, i think it's better to have this in `contao-newsletter` itself. What do you think?

**Comment by leofeyer** [comment]
@contao/developers Any objections against adding the header?

**Comment by fritzmg** [comment]
Sounds like a good feature to me 👍 

However I am unsure how this should be implemented? The Newsletter itself has no information about where the unsubscribe module is located, does it?

**Comment by frontendschlampe** [comment]
Maybe you can add an unsubscribe page picker in newsletter settings?!

**Comment by Toflar** [comment]
No objections.

**Comment by ausi** [comment]
No objections. But I think the unsubscribe URL should be configurable or directly link to the unsubscribe page/module (if technically possible).

**Comment by leofeyer** [comment]
We cannot use the unsubscribe URL, as most mail clients do not support it. We will have to use the `mailto:` link.

https://blog.mailtrap.io/list-unsubscribe-header/#Which_email_clients_support_list-unsubscribe_header
