### ISSUE TITLE
Verwenden eines Insert-Tags beim Einfügen von Bildern im TinyMCE

### ISSUE THREAD

**Issue by madmaharaja** [contao/contao#2175]
Diese Anfrage ist im Grunde genommen ein Duplikat von https://github.com/contao/core/issues/5965 (beim Einfügen eines Bildes via TinyMCE sollte keine absolute Pfadangabe mehr, sondern ein Inserttag verwendet werden). Wenn ich den alten Thread richtig verstehe, gab es zum Schluss konsens darüber, dass die Umsetzung sinnvoll wäre, sodass es einen commit und angeblich auch eine Implementierung gab: https://github.com/contao/core/issues/5965#issuecomment-41713418

Wenn ich aber in der aktuellen Contao-Demo (4.9.5) nachschaue, scheint die Implementierung nicht (mehr?) vorhanden zu sein: Es wird nach wie vor kein Inserttag, sondern eine Pfadangabe eingesetzt:
![grafik](https://user-images.githubusercontent.com/3133710/90730436-6d1a5400-e2c8-11ea-919a-e14ed715c905.png)

Habe ich etwas übersehen oder wurde die Implementierung aus irgendeinem Grund rückgängig gemacht? Ich würde diese Funktionalität jedenfalls nach wie vor als absolut sinnvoll und notwendig erachten.

**Comment by fritzmg** [comment]
Das wurde nicht rückgängig gemacht. Die Pfadangabe wird beim Abspeichern in einen Insert Tag und beim Laden wieder zurück in einen Pfad verwandelt. Deshalb siehst du diesen Insert Tag im Backend auch nie. Den siehst du praktisch nur in der Datenbank.

**Comment by madmaharaja** [comment]
Aha! Danke für die Rückmeldung, @fritzmg!
Quasi ein WYSIWYG-Editor mit What-you-see-is-not-what-you-get-Feature ... ;-)

**Comment by fritzmg** [comment]
> Quasi ein WYSIWYG-Editor mit What-you-see-is-not-what-you-get-Feature ... ;-)

Eigentlich nicht. Du fügst ein Bild ein, siehst das Bild im Backend und auch im Frontend. Wenn du den Insert Tag sehen würdest, dann wäre es "what-you-see-is-not-what-you-get" ;) (da der Insert Tag im Frontend dann ja ersetzt wird).
