### ISSUE TITLE
"Fake pages" in structure for being titles in menu 

### ISSUE THREAD

**Issue by JLBA** [contao/contao#2178]
Hello,
When creating a page in structure, it can be a simple page, an internal or external url. So each page is always a link.
But when a page has subpages, it's often like in computers menus : you click on it only to dropdown menu items, not to go to the page. So this could be useful if we can choose if a "page" has a link or is only a title for dropdown menu.

Could this be a checkbox in page parameters, in menu module or a special kind of page (a no link page) in structure ?

Thanks.

**Comment by fritzmg** [comment]
Just use https://github.com/terminal42/contao-folderpage

**Comment by JLBA** [comment]
Perfect. Thanks fritzmg. (Should be integrated to core...)
