### ISSUE TITLE
No articles in a new contao 4.10 installation

### ISSUE THREAD

**Issue by paddibr** [contao/contao#2179]
**Affected version(s)**

Contao 4.10

**Description**

Hi, i have a new complete contao installation over the contao manager.

I set some new pages but there are no articles:

![contao4_10](https://user-images.githubusercontent.com/9463756/90868910-c7ceb100-e397-11ea-8d9f-601d151bfdd6.jpg)

**Comment by aschempp** [comment]
see https://github.com/contao/contao/issues/1994#issuecomment-663981471

However, we could improve that by creating articles if there is no page layout assigned yet, what do you think @contao/developers ?

**Comment by paddibr** [comment]
Ah okay, i created a page layout and added a article. But i got the following errors:

![contao4_10_2](https://user-images.githubusercontent.com/9463756/90871235-06199f80-e39b-11ea-88fb-9bde434ff500.jpg)

**Comment by m-vo** [comment]
@paddibr see https://github.com/contao/contao/issues/2165

> However, we could improve that by creating articles if there is no page layout assigned yet

I think we should. You already have to have a lot of implicit knowledge about the order things should be done in the BE if you want to be effective or not run into dead ends. This would kind of add to this if your workflow was creating the structure first.

**Comment by paddibr** [comment]
@aschempp #2165 works for me.

**Comment by aschempp** [comment]
Please keep this open (see https://github.com/contao/contao/issues/2179#issuecomment-678119405)

**Comment by theDyingMountain** [comment]
We still have this problem in a Contao 4.10.5 Installation, even if a page layout with articles in the main section is added to the root page.

**Comment by fritzmg** [comment]
I can confirm the issue. Even with a page layout that has the articles module defined, a new article is not automatically generated when creating a new page.

**Comment by contaoacademy** [comment]
Should be fixed with https://github.com/contao/contao/pull/4433
