### ISSUE TITLE
Install Tool shows wrong console command

### ISSUE THREAD

**Issue by patrickjDE** [contao/contao#218]
**Affected version(s)**
4.4.30

**Description**  
When the install tool is locked, the error message tells the user to run `vendor/bin/contao-console contao:install:unlock`. If contao is not installed as a managed edition, the contao-specific console file does not exist and the command obviously fails.

Is it possible to detect this case and show the correct command `bin/console contao:install:unlock` to the user?

**Comment by leofeyer** [comment]
@aschempp Another reason why we should have `bin/console` in the managed edition. 🙈

**Comment by aschempp** [comment]
It is not possible to know the location of the console in a non-managed edition. Therefore, we should not show/alter this message if `contao/manager-bundle` is not installed …

**Comment by leofeyer** [comment]
It is not possible to know for sure, but I'm pretty confident that 99.999999999999% of all users use the default `bin/console`. 😛

**Comment by patrickjDE** [comment]
If it can't be determined for sure, I'd also prefer a generic "run this command in your symfony console" style message.
After all the important part of the message is the command itself, not the console location.

**Comment by leofeyer** [comment]
As discussed in Mumble on January 17th, @aschempp will add an option to unlock the install tool in the manager. Then we can adjust the message saying

> Please unlock the install tool using the Contao Manager or on the command line (`contao:install:unlock`).

**Comment by leofeyer** [comment]
Fixed in e0029a39c5e26ea50f68ffd6abf56cde6ef14bca.

**Comment by aschempp** [comment]
The respective option will be added in the next Manager release (see https://github.com/contao/contao-manager/commit/63d10e4d3d17046a719952495c1ce448312dda73)
