### ISSUE TITLE
CSRF: Cookie-Deletion and unsecure connections causes Browser-Warnings (SameSite=none without secure)

### ISSUE THREAD

**Issue by HenryVolkmer** [contao/contao#2185]
**Affected version(s)**

contao >= 4 till dev-master

**Description**

as discussed [here](https://github.com/isotope/core/issues/2154), Symfony removes Cookies by fulfill the correlate Cookie-Value with the string `deleted`. The result is a Cookie with SameSite-Attribute `none` which leads in a Browser-Warning (on unsecured connections). Since Symfony 4.4, it is possible to set the SameSite-Attribute for Cookie-Clearance and we should utilize this feature.

**Comment by leofeyer** [comment]
Closing this issue in favor of #2186.
