### ISSUE TITLE
Nachrichten: Weiterleitung auf Event

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#2196]
Es ist aktuell nicht möglich von einer Newsmeldung auf ein Event weiterzuleiten. Dies kann ich aktuell nur umgehen, wenn ich im Teaser im TinyCME Editor einen Link setze oder bei Individuelle Url den Url der Veranstaltung eintrage.
![grafik](https://user-images.githubusercontent.com/4446224/91190572-03e57700-e6f4-11ea-9e17-87538d7f09b5.png)

**Comment by fritzmg** [comment]
If you choose "Individuelle URL", you can choose an Event in the picker.

**Comment by m-vo** [comment]
Is there any benefit from being able to select 'articles' as this could be selected in the picker well? Maybe we should remove this for consistency?

**Comment by fritzmg** [comment]
Same with 'page' as well :)

**Comment by m-vo** [comment]
True :slightly_smiling_face:

**Comment by leofeyer** [comment]
We would save two DB columns by removing the options, so +1 I guess.

**Comment by theDyingMountain** [comment]
Oh sorry for not checking the picker... But glad to see, that some optimizations are detected by the way.
