### ISSUE TITLE
HTML-tags in the field "Bildunterschrift" are not converted in HTML in Contao 4.10

### ISSUE THREAD

**Issue by jochi44** [contao/contao#2197]
**Affected version**

Contao 4.10

**Description**

In Contao 4.10 HTML-tags in the field "Bildunterschrift" (Inhaltselement "Text" -> "Ein Bild hinzufügen" -> "Metadateien überschreiben") are not converted in HTML anymore.

For example do I use something like this quite often for a "Bildunterschrift":
`Quelle: <a href="https://abc.to" target="_blank">abc.to</a>`

Unfortunately in Contao 4.10 the frontend-output shows
`Quelle: <a href="https://abc.to" target="_blank">abc.to</a>`
instead of the HTML
`Quelle: abc.to`

Im not shure but think the HTML-conversion worked until Version 4.9.

**Comment by ausi** [comment]
Independent from the issue itself: You can use `{{link::https://abc.to}}` for this kind of use cases.

**Comment by asaage** [comment]
I was not aware, this was even allowed by defaut - but it is...
https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/dca/tl_content.php#L300

**Comment by jochi44** [comment]
> Independent from the issue itself: You can use `{{link::https://abc.to}}` for this kind of use cases.

Thank you, @ausi , for this information.
Unfortunately I don't see a possibility to add the "target=_blank"-argument when using this insert tag.
The insert tag `{{link_target::*}}` does only work when linking a Contao intern site (if I read the Contao docs correctly).
