### ISSUE TITLE
Usergroup Setting "allowed member groups" gets ignored

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#2202]
**Affected version(s)**

Contao 4.9.5

**Description**
When i set for example 1 of 3 membergroups in usergroup settings, the user still can see/choose all 3 existing member groups when creating a new member. He should only see the one i set in his usergroup settings.

I can reproduce this behaviour in the contao demo, so this should not be an issue caused by an extension.

VG Frank

**Comment by Kahmoon** [comment]
Is this issue at the right place?

**Comment by ausi** [comment]
> Is this issue at the right place?

Yes 👍

> When i set for example 1 of 3 membergroups in usergroup settings

Do you mean the “Allowed member groups” setting in the settings of a user group?

The help text of that field says “Members of these groups can be used in the front end preview.”.  
This setting does not affect creating new members, it only affects the front end preview.

**Comment by Kahmoon** [comment]
Hmm that makes sense....

Is there any way to set this when creating new members?

**Comment by ausi** [comment]
That should be possible with a custom DCA configuration for `$GLOBALS['TL_DCA']['tl_member']['fields']['groups']['options_callback']`.

**Comment by Kahmoon** [comment]
Thanks. At which file should i place this?

Path probably contao/dca

**Comment by fritzmg** [comment]
See the [dev docs](https://docs.contao.org/dev/) on how to implement DCA callbacks.

**Comment by Kahmoon** [comment]
Thanks. To much coding for me. Sorry
