### ISSUE TITLE
CSS-Klasse wird mehrfach ausgegeben

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#2203]
**Affected version(s)**

Contao 4.9.5

**Description**

- Ein neues Inhaltselement vom Typ Modul einfügen und in den Experteneinstellungen die Klasse `test-01` hinzufügen.
- Ein zweites Inhaltselement vom Typ Modul einfügen und in den Experteneinstellungen die Klasse `test-02` hinzufügen.

CSS-Ausgabe im Frontend beim ersten Element:
`mod_listing test-01 ce_table listing block`

CSS-Ausgabe im Frontend beim zweiten Element:
`mod_listing test-01 test-02 ce_table listing block`

Aus irgendeinem Grund, wird die Klasse vom ersten Element auch im zweiten Element ausgegeben.

Problem trat bei mir nach einem Update von 4.9.2 auf 4.9.5 auf.

**Comment by leofeyer** [comment]
Zeigen beide Inhaltselemente auf dasselbe Modul?

**Comment by netzarbeiter** [comment]
Ja, beide auf `Applications - Listing [Auflistung]`.

**Comment by leofeyer** [comment]
Das Problem wird von der Änderung in #2082 verursacht.

**Comment by leofeyer** [comment]
The PR also only changed the `ContentModule` class and not the following two, so besides this bug, it also caused inconsistencies.

https://github.com/contao/contao/blob/33841159b9b653e386a3fbecddb8d5336a743351/core-bundle/src/Resources/contao/elements/ContentAlias.php#L41-L48

https://github.com/contao/contao/blob/33841159b9b653e386a3fbecddb8d5336a743351/core-bundle/src/Resources/contao/library/Contao/Controller.php#L576-L580

@aschempp /cc
