### ISSUE TITLE
TinyMCE Bug in der Console - DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#2205]
**Affected version(s)**
Contao 4.9.5

**Description**
Bearbeitung eines Inhaltselements mit Textarea und TinyMCE Editor im Google Chrome Browser.
Fehler tritt laut Aussage eines Kollegen im Firefox nicht auf.

Das sieht man auf jeden Fall auch in der offiziellen Demo:
https://demo.contao.org/contao?do=article&table=tl_content&id=1&act=edit&rt=hkCiqHOWe4G8zJozWZyJOQ0aDGHqsrnkBvIBv8sihCg&ref=2pectHRZ

**Error message**

> DevTools failed to load SourceMap: Could not load content for https://demo.contao.org/assets/tinymce4/js/skins/contao/skin.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Weitere Fehlermeldungen in der Konsole lauten:

> contao?do=article&table=tl_content&id=1&act=edit&rt=hkCiqHOWe4G8zJozWZyJOQ0aDGHqsrnkBvIBv8sihCg&ref=2pectHRZ:217 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
(anonymous) @ contao?do=article&table=tl_content&id=1&act=edit&rt=hkCiqHOWe4G8zJozWZyJOQ0aDGHqsrnkBvIBv8sihCg&ref=2pectHRZ:217
2contao?do=article&table=tl_content&id=1&act=edit&rt=hkCiqHOWe4G8zJozWZyJOQ0aDGHqsrnkBvIBv8sihCg&ref=2pectHRZ:217 [Violation] Parser was blocked due to document.write(<script>)
(anonymous) @ contao?do=article&table=tl_content&id=1&act=edit&rt=hkCiqHOWe4G8zJozWZyJOQ0aDGHqsrnkBvIBv8sihCg&ref=2pectHRZ:217
tinymce.min.js?v=4.9.11:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
xe @ tinymce.min.js?v=4.9.11:2
Se.y.bind @ tinymce.min.js?v=4.9.11:2
(anonymous) @ tinymce.min.js?v=4.9.11:2
vn @ tinymce.min.js?v=4.9.11:2
each @ tinymce.min.js?v=4.9.11:2
on @ tinymce.min.js?v=4.9.11:2
it @ theme.min.js:1
postRender @ theme.min.js:1
postRender @ theme.min.js:1
(anonymous) @ tinymce.min.js?v=4.9.11:2
postRender @ theme.min.js:1
(anonymous) @ tinymce.min.js?v=4.9.11:2
(anonymous) @ theme.min.js:1
jt @ tinymce.min.js?v=4.9.11:2
each @ theme.min.js:1
exec @ theme.min.js:1
postRender @ theme.min.js:1
(anonymous) @ tinymce.min.js?v=4.9.11:2
postRender @ theme.min.js:1
(anonymous) @ tinymce.min.js?v=4.9.11:2
(anonymous) @ theme.min.js:1
jt @ tinymce.min.js?v=4.9.11:2
each @ theme.min.js:1
exec @ theme.min.js:1
postRender @ theme.min.js:1
(anonymous) @ tinymce.min.js?v=4.9.11:2
(anonymous) @ theme.min.js:1
jt @ tinymce.min.js?v=4.9.11:2
each @ theme.min.js:1
exec @ theme.min.js:1
postRender @ theme.min.js:1
(anonymous) @ tinymce.min.js?v=4.9.11:2
renderBefore @ theme.min.js:1
be @ theme.min.js:1
Tt @ theme.min.js:1
renderUI @ theme.min.js:1
_w @ tinymce.min.js?v=4.9.11:2
Aw @ tinymce.min.js?v=4.9.11:2
(anonymous) @ tinymce.min.js?v=4.9.11:2
(anonymous) @ tinymce.min.js?v=4.9.11:2
jt @ tinymce.min.js?v=4.9.11:2
u @ tinymce.min.js?v=4.9.11:2
n @ tinymce.min.js?v=4.9.11:2
l.<computed>.l.<computed>.l.<computed>.o.onload @ tinymce.min.js?v=4.9.11:2
Show 14 more frames
tinymce.min.js?v=4.9.11:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
xe @ tinymce.min.js?v=4.9.11:2
Se.y.bind @ tinymce.min.js?v=4.9.11:2
(anonymous) @ tinymce.min.js?v=4.9.11:2
vn @ tinymce.min.js?v=4.9.11:2
each @ tinymce.min.js?v=4.9.11:2
on @ tinymce.min.js?v=4.9.11:2
ct @ theme.min.js:1
postRender @ theme.min.js:1
(anonymous) @ tinymce.min.js?v=4.9.11:2
(anonymous) @ theme.min.js:1
jt @ tinymce.min.js?v=4.9.11:2
each @ theme.min.js:1
exec @ theme.min.js:1
postRender @ theme.min.js:1
(anonymous) @ tinymce.min.js?v=4.9.11:2
(anonymous) @ theme.min.js:1
jt @ tinymce.min.js?v=4.9.11:2
each @ theme.min.js:1
exec @ theme.min.js:1
postRender @ theme.min.js:1
(anonymous) @ tinymce.min.js?v=4.9.11:2
renderBefore @ theme.min.js:1
be @ theme.min.js:1
Tt @ theme.min.js:1
renderUI @ theme.min.js:1
_w @ tinymce.min.js?v=4.9.11:2
Aw @ tinymce.min.js?v=4.9.11:2
(anonymous) @ tinymce.min.js?v=4.9.11:2
(anonymous) @ tinymce.min.js?v=4.9.11:2
jt @ tinymce.min.js?v=4.9.11:2
u @ tinymce.min.js?v=4.9.11:2
n @ tinymce.min.js?v=4.9.11:2
l.<computed>.l.<computed>.l.<computed>.o.onload @ tinymce.min.js?v=4.9.11:2
Show 3 more frames
tinymce.min.js?v=4.9.11:2 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
bw @ tinymce.min.js?v=4.9.11:2
ww @ tinymce.min.js?v=4.9.11:2
Aw @ tinymce.min.js?v=4.9.11:2
(anonymous) @ tinymce.min.js?v=4.9.11:2
(anonymous) @ tinymce.min.js?v=4.9.11:2
jt @ tinymce.min.js?v=4.9.11:2
u @ tinymce.min.js?v=4.9.11:2
n @ tinymce.min.js?v=4.9.11:2
l.<computed>.l.<computed>.l.<computed>.o.onload @ tinymce.min.js?v=4.9.11:2
DevTools failed to load SourceMap: Could not load content for https://demo.contao.org/assets/tinymce4/js/skins/contao/skin.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by leofeyer** [comment]
Fixed in contao-components/tinymce4@dbcef881803de095d39f59fdf97292b1c25a6c76.

**Comment by Total-Reality** [comment]
Cool, danke für die schnelle Reaktion.

Kriegen wir die Warnungen auch noch raus?
Leider waren die oben beim zitieren nicht gut zu sehen.

```
https://demo.contao.org/contao?act=edit&do=article&id=1&ref=2pectHRZ&table=tl_content&rt=CG4eCI9HIMat_tjrmal_wOguc6CT3tN0kjIUYscsrUk
[Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write

https://demo.contao.org/assets/tinymce4/js/tinymce.min.js?v=4.9.12
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

Das Thema mit "marking event handler passive" ist übrigens auch im Frontend ein Problem, wenn man Google Insights zwecks Pagespeed laufen lässt.

**Comment by fritzmg** [comment]
> ```
> https://demo.contao.org/contao?act=edit&do=article&id=1&ref=2pectHRZ&table=tl_content&rt=CG4eCI9HIMat_tjrmal_wOguc6CT3tN0kjIUYscsrUk
> [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
> ```

There were plans to remove `document.write()` from the `be_tinyMCE` template, unfortunately it did not work out. See https://github.com/contao/contao/pull/1424

> ```
> https://demo.contao.org/assets/tinymce4/js/tinymce.min.js?v=4.9.12
> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
> ```

This comes from within TinyMCE itself. You can update to Contao 4.10 in order to get TinyMCE 5 and check if that is still used there.
