### ISSUE TITLE
Disabled settings trigger errors upon saving

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2210]
**Affected version(s)**

Contao 4.10

**Description**

Since #1382, settings defined in the app configuration are disabled in the back end. When trying to save the form, however, these fields trigger errors:

<img width="709" alt="" src="https://user-images.githubusercontent.com/1192057/91582314-eb719880-e94f-11ea-8a92-8f1f9a230ed1.png">

**Comment by ausi** [comment]
Adding `$GLOBALS['TL_DCA']['tl_settings']['fields'][$field]['eval']['mandatory'] = false;` to https://github.com/contao/contao/blob/5324c34972dbabe6c439cd2ff6f01cde974f1a36/core-bundle/src/EventListener/DataContainer/DisableAppConfiguredSettingsListener.php#L55-L57 fixed the issue in my test.

**Comment by fritzmg** [comment]
But that's not really how `disabled` fields are supposed to work, is it? 🤔

**Comment by ausi** [comment]
I don’t know. Setting a `disabled` field to `mandatory` could be seen as a misconfiguration I guess?

**Comment by fritzmg** [comment]
Yeah, I guess you are right.

**Comment by ausi** [comment]
But intuitively I would also expect the `disabled` option to take precedence over all other settings.

To make this work we could change https://github.com/contao/contao/blob/af6fbee47ea5375deefcf4dca6d4362d584a7ff4/core-bundle/src/Resources/contao/library/Contao/Widget.php#L809-L812 to `if (!$this->mandatory || !$this->blnSubmitInput)`

**Comment by leofeyer** [comment]
Should we not return immediately if we know that the widget does not submit anything?

```php
	protected function validator($varInput)
	{
		if (!$this->submitInput())
		{
			return null;
		}

		if (\is_array($varInput))
```

**Comment by leofeyer** [comment]
And is this not the actual cause of the error?

https://github.com/contao/contao/blob/af6fbee47ea5375deefcf4dca6d4362d584a7ff4/core-bundle/src/Resources/contao/classes/DataContainer.php#L375-L388

Why validate a widget that does not submit any input?

**Comment by ausi** [comment]
I honestly don’t know for what `submitInput()` is meant to be used for. Maybe the widget could get the value from somwhere else but still needs to be validated and saved?

I think I would just extend the check in https://github.com/contao/contao/blob/af6fbee47ea5375deefcf4dca6d4362d584a7ff4/core-bundle/src/Resources/contao/library/Contao/Widget.php#L809 this should most likely not break existing code.

**Comment by aschempp** [comment]
I don't think returning on empty content is correct (as suggested by @ausi). We must not validate a widget that does not submit input (which is the case if it is disabled, or the widget has only presentational purpose).

**Comment by leofeyer** [comment]
That is what I think, too.

**Comment by ausi** [comment]
I just looked at this again: If `$objWidget->submitInput()` is false the save method is never called. So I think @aschempp is right *“We must not validate a widget that does not submit input”* 👍
