### ISSUE TITLE
Script tag for JSON-LD schema is not closed properly

### ISSUE THREAD

**Issue by Sigma-90** [contao/contao#2212]
**Affected version(s)**

Contao 4.9.3

**Description**

Today I was linking a news feed to the reader page for the first time in this Contao version and was stumped to see that the web page's fonts reverted to ugly Times New Roman when I opened an article.
The cause of the issue was quickly identified: 
The theme I'm using is adding another script tag to the header (which handles theme initialization and opt-in web font loading) right after the JSON-LD schema script tag for the type "NewsArticle". 
_But this schema script tag is not closed properly:_ What is supposed to be the closing tag is in fact another opening tag. 
This causes the entire following script block to be considered as part of the JSON-LD block, so of course it never executes.

The HTML reads like this (shortened):
```
<script type="application/ld+json">{"@context":"https://schema.org","@type":"NewsArticle","mainEntityOfPage":{"@type":"WebPage","@id":"http://my-url.com/news/details/my-article.html"},"headline":"My article headline","description":"Lorem ipsum dolor sit amet.","datePublished":"2020-08-28T18:00:00+02:00","dateModified":"2020-08-28T22:14:31+02:00","author":{"@type":"Person","name":"Administrator User"},"image":"http://my-url.com/files/cto_layout/img/news-pictures/image.jpg"}<script>

<script>
// Opt-in
if(localStorage.getItem('user_privacy_settings') >= 1)
{
	jQuery('head').append('<link id="webfonts_optin" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,300,700">');
}

// listen to Eclipse.user_privacy Event
jQuery(document).on('Eclipse.user_privacy',function(event,params)
{
	if(params.level > 0)
	{
		jQuery('head').append('<link id="webfonts_optin" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,300,700">');
	}
});
</script>
```

And because of that little missing "/", the browser interprets that piece of HTML like this:
![image](https://user-images.githubusercontent.com/1439340/91615892-e3801b80-e984-11ea-803e-f8a030116a05.png)

Such a tiny mistake, but such huge impact. I sincerely hope this can be fixed asap, because now I have to either load the web fonts at all times and ignore whether the user actually opted in or risk the page looking rather silly whenever a news article is opened.

**Comment by fritzmg** [comment]
> **Affected version(s)**
> 
> Contao 4.9.3

You need to report bugs that affect a current version of Contao. Update to Contao 4.9.5 and test again.

**Comment by Sigma-90** [comment]
Apologies Leo & Co., it seems I posted this issue too hastily. 
After modifying my search term a bit in my IDE, a new file showed up in the list which actually contained the cause of the bug. And it turned out to belong to the theme as well, so it actually wasn't Contao's fault. My bad. I will contact the theme devs as soon as possible so they can fix it on their end.
