### ISSUE TITLE
Generated page urls contains host information twice

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2214]
**Affected version(s)**

Contao 4.10.0

**Description**

I have a Contao setup where a custom port is used and as part of the root page dns (`PageModel::domain`). Contao isn't able to generate valid page urls anymore. A generated page url for the root page dns setting `localhost:8080` looks like `http://localhost:8080/localhost:8080:8080/example.html`

The issue seems to be be related to the host tokens of the compiled route of a page. Contao contains the port in the route host, where the `UrlGenerator` of symfony, which is used by the `PageUrlGenerator` of Contao, does not contain the port information and so a change of the reference type happens.

https://github.com/symfony/symfony/blob/69f8eaeec548566a25b5959b8f116e44cf2fe126/src/Symfony/Component/Routing/Generator/UrlGenerator.php#L264-L269

It only happens for relative urls and not for urls linking to another root page.

I do not have a clue if this a Contao specific issue or a general Symfony routing issue.

/cc @frontendschlampe

**Comment by bennyborn** [comment]
Seems related to #2171

**Comment by aschempp** [comment]
> I do not have a glue if this a Contao specific issue

🤣 🤣 🤣 
I guess you mean clue (*Idee/Ahnung*) not glue (*Leim/Kleber*) 😂 

> Seems related to #2171

Yes, and https://github.com/contao/contao/pull/2262 might fix (parts of) it. @dmolineus can you try that patch?

**Comment by leofeyer** [comment]
It seems that Symfony does not support a host with a port number: https://github.com/symfony/symfony/issues/7592 We can probably solve it by adjusting the routing context?

**Comment by aschempp** [comment]
We _could_, but that would be "against Symfony's design". I think @fabpot is right saying that it is very unlikely that a server users multiple ports, even cross-domain. I think its very unlikely that someone tries to run multiple websites on the same host name but different ports (run by the same webserver)?

**Comment by frontendschlampe** [comment]
any updates here?

**Comment by aschempp** [comment]
this should already be fixed in the latest Contao version (see https://github.com/contao/contao/pull/2323)?

**Comment by leofeyer** [comment]
As discussed in Mumble on November 19th, we have to ignore/strip the port number in the DNS settings of the Contao root pages, because the Symfony router will re-add the current port automatically when generating URLs.

It should be enough to strip `:[0-9]+$`, because IPv6 addresses should be wrapped in square brackets (e.g. `[::1]`).
