### ISSUE TITLE
Hinweis "fehlender Sprachen-Fallback Website-Startpunkt" nur für Benutzer mit entsprechenden Zugriffsrechten

### ISSUE THREAD

**Issue by madmaharaja** [contao/contao#2222]
Ich administriere eine Contao-Installation mit über 100 Redakteuren/Benutzern. Jedoch hat bis auf mir kein anderer Benutzer die Benutzerrechte, um die DNS-Einstellungen in einer Rootseite in der Seitenstruktur zu bearbeiten. Dennoch wird allen Benutzern in Contao der Warnhinweis eingeblendet: "_Keiner der aktiven Website-Startpunkte für foo.bar wurde als Sprachen-Fallback definiert._"
Das führt schonmal zu Irritationen, da die anderen Redakteure mit dem Hinweis nichts anzufangen wissen, aber denken, irgendetwas falsch eingestellt zu haben. Und selbst, wenn sie theoretisch wüssten, was sich hinter dem Hinweis verbirgt, wären sie nicht in der Lage etwas daran zu ändern -- mit anderen Worten, der Hinweis hat für sie keine Relevanz, sorgt aber evtl. für Verunsicherung.

Deshalb wäre mein Vorschlag, dass dieser Warnhinweis nur den Benutzern angezeigt werden sollte, die tatsächlich auch die Benutzerrechte hätten, das "Problem" zu beheben. Mit anderen Worten eine Überprüfung, ob ein Benutzer 
1. die den Warnhinweis auslösende Rootseite(n) bearbeiten darf 
_und_ 
2. Benutzerrechte für die Felder "Domainname", "Sprache" und "Sprachenfallback" hat. 

Nur wenn all diese Voraussetzungen gegeben sind, macht es meiner Meinung nach Sinn, dem Benutzer den Warnhinweis einzublenden.

Nachvollziehen lässt sich dieser Umstand, wenn man in der aktuellen Contao-Demo eine neue Rootseite anlegt mit irgendeinem Domainnamen (außer demo.contao.org) und einen Benutzer, der keine Bearbeitungsrechte für die neue Rootseite hat und/oder die DNS-Einstellungen hat und dann in die Ansicht des betreffenden Benutzers wechselt.
![grafik](https://user-images.githubusercontent.com/3133710/91962473-dfe5ef00-ed0c-11ea-8e25-3bdb7973f293.png)

**Comment by fritzmg** [comment]
Hm, why is that important to you? Regardless of who sees or does not see this warning - it shouldn't be something that stays for a long time anyway.

**Comment by madmaharaja** [comment]
It is not super important -- but I already mentioned why I think it makes sense.
The warning mainly has popped up for test sites that I set up within our installation under dedicated subdomains. In these cases I have sometimes forgoten or neglected the fallback setting and warning for a while because it wasn't really relevant for any public websites. However, it did confuse some people. So, one could argue that it was basically my fault -- but then again: why should others be bothered/confused by the actions of someone else, if it's not relevant to them and they can't change anything about it?

**Comment by fritzmg** [comment]
I would argue that a misconfiguration is also relevant for back end users who cannot do anything about it, since they then will know what's wrong if they run into an error related to said misconfiguration. And they can contact the site's administrator about the warning.

**Comment by aschempp** [comment]
I agree it could be confusing, but I think it's a good thing the confused user will contact the site administrator, which should fix the issue.
