### ISSUE TITLE
Search indexer performance penalty/glitches

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2235]
**Affected version(s)**

(only tested with current master so far, probably at least 4.10)

**Description**

The search indexer locks and updates the search tables on every call even if nothing has changed (case A) with the exception of one scenario where the page was visited in preview mode first and therefore contains the wrong url (case B). When fixing this we should also make sure the lock only ever occurs after the checksum check/early return if possible.

**How to reproduce case A**
1. Make sure the search indexer runs in the FE
1. Open a page &rarr; will be indexed
1. Open the same page again without changing the content &rarr; `tl_search` and `tl_search_term` will be updated again<sup>*)</sup>

**How to reproduce case B**
1. Make sure the search indexer runs in the FE
1. Truncate the search tables
1. Open a page in the preview mode &rarr; the stored url will contain `preview.php/` 
1. Open the same page through the regular entry point &rarr; no change happens to the url or any associated record<sup>**)</sup>

--------
<sup>*)</sup> because there is no early return in the case of matching checksums and urls

<sup>**)</sup> because this first condition https://github.com/contao/contao/blob/fab8317d8f06000b8977987fb9dd71ee3d66415d/core-bundle/src/Resources/contao/library/Contao/Search.php#L188-L192 evaluates to `true` and the following to `false` resulting in a `return` in line 220.

**Comment by leofeyer** [comment]
I have fixed case A in #2249. I am not sure about case B though; what exactly would you expect? That Contao removes the `/preview.php` fragment from the URL?

**Comment by leofeyer** [comment]
We will most likely need a separate PR for Contao 4.10, because @ausi has reworked the search logic (e.g. there is no table locking in Contao 4.9).

**Comment by ausi** [comment]
> We will most likely need a separate PR for Contao 4.10

Done: #2250

**Comment by m-vo** [comment]
> I am not sure about case B though; what exactly would you expect? That Contao removes the /preview.php fragment from the URL?

I think so. The `/preview.php` fragment never makes sense in the index, does it?

**Comment by m-vo** [comment]
And by the way: :hearts: for your two super quick PRs/fixes!

**Comment by ausi** [comment]
But just removing `/preview.php` from the URL would not work as the potentially wrong content would then get indexed. I think `Search::indexPage()` should not get called in the first place for `/preview.php`.

**Comment by leofeyer** [comment]
IMHO, the if condition in the following code is incomplete:

https://github.com/contao/contao/blob/989d8986989a818973bbb814ba80ed97004b6485/core-bundle/src/Resources/contao/library/Contao/Search.php#L201-L224

**if → Use the new URL if**

* the new URL does not have a query string but the current one does

**elseif → Use the current URL if**

* the new URL has more slashes than the current one or
* the new URL has a query string but the current one does not or
* the new URL is longer than the current one

Should we not also check the following cases in the first if condition?

* Use the new URL if it has less slashes than the current one;
* Use the new URL if it is shorter than the current one.

This would solve case B:

> Open the same page through the regular entry point → no change happens to the url

**Comment by ausi** [comment]
Why does the code delete existing entries? This doesn’t make sense IMO.

As far as I understand the purpose of this code: If an index for the same page ID with the exact same content (checked via checksum) exists we want to use the shorter/more canonical URL of both entries.

I think we should rewrite the code to:

1. Check which URL is more canonical, `$objIndex->url` or `$arrSet['url']`.
2. If `$objIndex->url` is more (or equally) canonical, return false as we don’t need to change anything in this case.
3. If `$arrSet['url']` is more canonical, just update the `url` column of the existing entry and return false.

**Comment by leofeyer** [comment]
> Why does the code delete existing entries? This doesn’t make sense IMO.

Did you probably forget to remove these lines in your PR? Or are they still in because of a merge conflict?

**Comment by ausi** [comment]
I did not change this logic, it’s the same in 4.9 (besides the deletion queries adapted for the new table structure).

**Comment by leofeyer** [comment]
Then we should probably rework this. 🙈

**Comment by ausi** [comment]
I will make PR

**Comment by ausi** [comment]
Done: #2276
