### ISSUE TITLE
How do pages not added to sitemap.xml?

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#2237]
**Affected version(s)**

Contao 4.*

**Description**

Why only for `Robots tag = "noindex,nofollow"`, the page will be eliminate from sitemap.xml? I mean; if `Robots tag = "noindex,follow"`, the page is added to sitemap.xml and Google Search Console throws error: "Submitted URL marked ‘noindex’".

This is what it should be?

**Comment by fritzmg** [comment]
See the discussion in #501.

**Comment by hamidpeywasti** [comment]
> See the discussion in #501.

 Thanks, but this is a bit confusing.
