### ISSUE TITLE
IDN Domain wird nicht erkannt

### ISSUE THREAD

**Issue by Babelfisch** [contao/contao#2239]
Contao 4.9.5

Lege ich einen neuen Startpunkt einer Webseite an und trage die IDN-Domain `www.übungsgrammatik.de` als Domainnamen ein, steht nach dem Speichern nur noch `www.` im Textfeld drin. Entsprechend kann der Startpunkt nicht aufgerufen werden.

Trage ich nur `übungsgrammatik.de` für den Domainnamen ein, bleibt die Domain korrekt im Textfeld stehen. Allerdings bekomme ich beim Aufruf der Webseite dann „Es ist ein Fehler aufgetreten“ und im Log steht folgende Fehlermeldung:

```
request.CRITICAL: Uncaught PHP Exception LogicException: "Cannot use UTF-8 route patterns without setting the "utf8" option for route "/"." at /var/www/…/web/vendor/symfony/routing/RouteCompiler.php line 114 {"exception":"[object] (LogicException(code: 0): Cannot use UTF-8 route patterns without setting the \"utf8\" option for route \"/\". at /var/www/…/web/vendor/symfony/routing/RouteCompiler.php:114)"} []
```

Es funktioniert nur korrekt, wenn ich die Domain in der Punycode-Entsprechung eintrage.

**Comment by fritzmg** [comment]
May be the `url` `rgxp` should also automatically use `Idna::encode` and `Idna::decode`? The `email` `rgxp` does the same (although it does not decode).

**Comment by aschempp** [comment]
Does it work in Contao 4.4?

**Comment by leofeyer** [comment]
I can confirm the issue. The hostname is cut at the first UTF-8 character.

**Comment by leofeyer** [comment]
And if I manually add the hostname in the DB, Symfony throws the following exception:

<img width="796" alt="" src="https://user-images.githubusercontent.com/1192057/94280739-0be04300-ff4e-11ea-82b1-5f32e7ac9a36.png">

So we should definitely store the hostname in Punycode format in the DB.

**Comment by ausi** [comment]
> May be the `url` `rgxp` should also automatically use `Idna::encode` and `Idna::decode`?

I think the `url` `rgxp` is not only meant for domain names, right?

We should problably just use `Idna::decode` in the `save_callback` of the `dns` field.
