### ISSUE TITLE
Benutzer ohne Adminrechte darf keine Templates bearbeiten

### ISSUE THREAD

**Issue by derastronaut** [contao/contao#224]
Betrifft Contao 4.6.10

Lege ich einen Benutzer ohne Adminrechte an, gebe diesem Benutzer die Erlaubnis Templates zu bearbeiten (Gruppenrechte oder individuelle Rechte ist egal), erhalte ich die Fehlermeldung `Not enough permissions to edit the file source of file "templates/fe_page.html5".`, wenn ich den Quelltext eines Templates bearbeiten möchte.

Templates angelegen, löschen, verschieben, Name ändern oder neue Ordner anlegen funktioniert hingegen. Nur kann ich mit diesem Benutzer den Quelltext nicht bearbeiten. Erst wenn ich dem Benutzer Adminrechte gebe, kann der den Quellcode bearbeiten.

Ich habe das in zwei Contao-Installationen getestet, eine davon eigens für dieses Problem frisch angelegt.

Da ich sonst keine Einstellungsmöglichkeit hinsichtlich der Rechte für Templates gefunden habe, gehe ich von einem Bug aus. Oder habe ich etwas übersehen?

**Comment by leofeyer** [comment]
Und in Contao 4.4 funktioniert es?

**Comment by ausi** [comment]
Wurde in den Berechtigungseinstellungen im Bereich „Filemounts“ die Checkbox „Dateien im Quelltexteditor bearbeiten“ aktiviert?

**Comment by derastronaut** [comment]
> Wurde in den Berechtigungseinstellungen im Bereich „Filemounts“ die Checkbox „Dateien im Quelltexteditor bearbeiten“ aktiviert?

Verdammt, ja, das war's...

Mir war nicht bewusst, dass das mit Templates zusammenhängt. Sorry für die Umstände.

**Comment by leofeyer** [comment]
@contao/developers Macht es überhaupt jemals Sinn, einem Benutzer den Template-Editor freizugeben aber nicht das Bearbeiten der Dateien? IMHO sollten wir das im Template-Editor immer erlauben.

**Comment by Toflar** [comment]
In meinen Augen macht es niemals Sinn, dem Benutzer überhaupt Zugriff auf die Templates zu geben...

**Comment by Paddy0174** [comment]
Es macht keinen Sinn, im Grunde ein- und denselben Zugriff in den Rechten aufzuteilen. Ich finde schon, dass es die Genehmigung an sich aber geben sollte. 

Grundsätzlich macht es natürlich wenig Sinn, einem Benutzer die entsprechenden Rechte zu geben, aber gerade aus der eher "technischen" Sicht kann ich mir das durchaus vorstellen. Die Technik macht die Administration der Seite, der Benutzer "Grafikabteilung" sollte aber die Templates schon bearbeiten können.

**Comment by leofeyer** [comment]
@Paddy0174 Der Grund für @Toflar's Aussage ist, dass jeder, der ein Template bearbeiten darf, vollen Zugriff auf das System hat. Er kann sich selbst zu einem Administrator machen oder irgendwelche Sachen installieren oder <was auch immer mit PHP möglich ist>. Die Grafikabteilung ist somit implizit ebenfalls Administrator.

**Comment by leofeyer** [comment]
Zu diskutieren wäre:

1. Sollten wir das Templates-Modul überhaupt in den Benutzer-Einstellungen als Option anzeigen?
2. Wenn ja, sollten die Templates nicht immer editierbar sein?

**Comment by aschempp** [comment]
Aus meiner Sicht ist es ganz klar eine Benutzereinstellung. Und wenn ich Zugang zu den Templates habe, kann ich die auch editieren. Die Berechtigungsprüfung macht in diesem Fall keinen Sinn.

**Comment by leofeyer** [comment]
Wie am 20. Dezember auf Mumble besprochen, wollen wir die Option in den Benutzer-Einstellungen behalten aber die Templates sollen immer editierbar sein (unabhängig von der "Dateien im Quelltexteditor bearbeiten"-Einstellung).

**Comment by leofeyer** [comment]
Außerdem wollen wir auf der Hauptseite "Benutzergruppen" eine blaue Info anzeigen, wenn es Benutzergruppen gibt, die Templates bearbeiten dürfen.

**Comment by leofeyer** [comment]
Ich wollte die Änderungen gerade umsetzen, stelle aber fest, dass das Bearbeiten von Templates nicht an die Dateirechte gebunden ist. Es gibt in der `tl_templates.php` weder eine Methode `checkPermission()` noch eine Prüfung auf `$this->User->hasAccess('f5', 'fop')`. 🤔 

@derastronaut Kannst Du bitte nochmal prüfen, ob Deine Benutzer wirklich keine Templates mehr bearbeiten dürfen, wenn Du die Checkbox „Dateien im Quelltexteditor bearbeiten“ deaktivierst?

**Comment by derastronaut** [comment]
> @derastronaut Kannst Du bitte nochmal prüfen, ob Deine Benutzer wirklich keine Templates mehr bearbeiten dürfen, wenn Du die Checkbox „Dateien im Quelltexteditor bearbeiten“ deaktivierst?

Ja, nehme ich das Häkchen raus und speichere, bekommt der betroffene Benutzer die Meldung, dass er nicht genug Berechtigungen zum Bearbeiten des Quelltextes der Datei foo/bar.html5 hat (auf Englisch).

**Comment by leofeyer** [comment]
Wie kann ich das denn in meiner Entwicklungsumgebung (mit der COD) reproduzieren?

**Comment by derastronaut** [comment]
Anscheinend geht das in der Demo nicht, da der Punkt **Templates** nicht zur Auswahl als mögliche Rechtevergabe steht. Leider kann ich auch keinen neuen Benutzer in der Demo anlegen, da ich jedes Mal, wenn ich speichern will, die Meldung **Cannot load record "tl_user.id=4".** erhalte.

Sowohl in meiner produktiven als auch in meiner Testinstallation hatte ich einen Benutzer angelegt, diesem die Rechte **Templates** und **Dateien im Quelltexteditor bearbeiten** gewährt. Hatte es gestern in der produktiven Installation noch mal getestet (4.6.12).

**Comment by leofeyer** [comment]
> Anscheinend geht das in der Demo nicht

Ich hatte ja auch "in meiner Entwicklungsumgebung" geschrieben und nicht "in der Online-Demo". 😄 

Kannst Du mir eventuell einen Backend-Zugang für Deine Installation anlegen, damit ich es dort nachvollziehen kann?

**Comment by derastronaut** [comment]
Zur produktiven Installation nicht, aber ich kann dir Zugang zur Testinstallation geben.

Soll ich dir die Zugangsdaten an die hier hinterlegte E-Mail-Adresse schicken?

**Comment by leofeyer** [comment]
Ja bitte.

**Comment by leofeyer** [comment]
@derastronaut Danke, jetzt konnte ich das Problem endlich reproduzieren. 👍 

Das eigentliche Problem ist, dass im `DC_Folder` in zwei Methoden `$this->User->hasAccess()` geprüft wird. Das ist insofern falsch, als dass die DCs keine Annahme über Berechtigungen machen sollen – dafür gibt es nämlich die onload_callbacks. Insofern ist das ein Bug, der ab Contao 4.4 gefixt werden muss.

**Comment by leofeyer** [comment]
> Außerdem wollen wir auf der Hauptseite "Benutzergruppen" eine blaue Info anzeigen, wenn es Benutzergruppen gibt, die Templates bearbeiten dürfen.

Diesen Teil habe ich in a9dc17c4d2b104245825b78ed235c6c32b6a8445 implementiert.

<img width="769" alt="" src="https://user-images.githubusercontent.com/1192057/51040383-a43a6680-15b7-11e9-96cb-50e15ad080d3.png">

**Comment by leofeyer** [comment]
Behoben in f06a65fbe9eaa3df447ab13b71ca62822be33ce0.
