### ISSUE TITLE
\Controller::redirect() not working in save_callback in ModuleRegistration

### ISSUE THREAD

**Issue by SGehle** [contao/contao#2240]
**Affected version(s)**

Contao 4.9.5

**Description**

If i use the \Controller::redirct()-Method in a DCA save_callback in ModuleRegistration, the Widget shows "This exception has no message. Use $exception->getResponse() instead." 
I think its because of the thrown RedirectResponseException.

**Comment by m-vo** [comment]
>If i use the \Controller::redirct()-Method in a DCA save_callback 

Why would you want to do this?

**Comment by SGehle** [comment]
I have to use it, because if a special value is entered, if have to cancel the registration process and redirect to another page. I can also not use the createUser Hook because when its triggered, the new user is already created.

**Comment by fritzmg** [comment]
We have to add

```php
catch (ResponseException $e)
{
	throw $e;
}
```

In `ModuleRegistration::compile`, just as we do in `DataContainer::row`.
