### ISSUE TITLE
Add an onshow_callback

### ISSUE THREAD

**Issue by Toflar** [contao/contao#225]
I would like to have an `onshow_callback` so I can somehow add/modify the output in `DC_Table::show()`. This has bothered me for a long time already. You can't do anything there other than overriding the DC. Imho this is rather an easy pick and it would be great to have anybody else contribute so I don't have to 😄 

Also, kind of related: There's no built in handling for `eval->csv` and `foreignKey`. Imho when I set `eval->csv = ','` on a field and I also provide a `foreignKey` it could comma-separate the foreign key values instead of the IDs.

**Comment by qzminski** [comment]
Created a pull request in #235.
