### ISSUE TITLE
Issue with leafo/scssphp version 0.6

### ISSUE THREAD

**Issue by James90** [contao/contao#226]
**Affected version(s)**
Contao 4.4

**Description**  
Sasscompiler Leafo/sassphp in version 0.6 has issues with mix-function  check: https://github.com/leafo/scssphp/issues/551

This was fixed with version 0.7.6

**How to reproduce**  
check example: https://github.com/leafo/scssphp/issues/551

**How to resolve**
Please change requirements for leafo/scssphp to version 0.7.6 or higher

**Comment by arboc** [comment]
👍  same here

**Comment by leofeyer** [comment]
Fixed in 2b1cb189c933c808a885c9f7c2d09a145f573c4d.
