### ISSUE TITLE
Sorting in Theme-Editor breaks when adding new elements (Page Layout)

### ISSUE THREAD

**Issue by jxns** [contao/contao#2266]
**Affected version(s)**

Contao 4.10.0?

**Description**

When adding external stylesheets (and also external JavasScripts) into the themes page layout, the sorting breaks and all previously added (and sorted) stylesheets are resorted.

I was able to reproduce this issue on all my 4.10.0 versions.

**Comment by Toflar** [comment]
See https://github.com/contao/contao/pull/2267
