### ISSUE TITLE
Get rid of phpunit/php-token-stream

### ISSUE THREAD

**Issue by ausi** [contao/contao#2282]
We should replace `phpunit/php-token-stream` with something else because it is abandoned.

***
 
https://github.com/contao/contao/pull/2281#issuecomment-690348360 @leofeyer Can we maybe rework the class so it works without the package? Maybe using the PHP function `token_get_all()`?

https://github.com/contao/contao/pull/2281#issuecomment-690352583 @m-vo That's what `PHP_Token_Stream` is doing as well: https://github.com/sebastianbergmann/php-token-stream/blob/master/src/Stream.php#L413-L514

Maybe this function gets small enough if we reduce it to our use case to adopt it.

I had a quick look at it. Parsing and stripping PHP tags is the easy part. Unfortunately we would have to write/adapt quite a lot of code to handle all the namespace edge cases, which makes it - well - a doable but non-trivial task.

https://github.com/contao/contao/pull/2281#issuecomment-690907506 @leofeyer Maybe we can use https://github.com/nikic/PHP-Parser?

**Comment by m-vo** [comment]
👍 I'll have a look if Nikita's package works for us.

**Comment by m-vo** [comment]
The stable channel of `nikic/php-parser` requires at least PHP 7.0 - would we still use this in Contao 4.4?

**Comment by leofeyer** [comment]
Contao 4.4 will not be compatible with PHP 8 anyway, so we only need to fix things in Contao 4.9+.

**Comment by m-vo** [comment]
Alright. The package is still abandoned, though.

**Comment by leofeyer** [comment]
You cannot avoid this with a long term package that lives 4 years. 🤷🏻‍♂️

**Comment by m-vo** [comment]
see #2284
