### ISSUE TITLE
Add support for AVIF image format

### ISSUE THREAD

**Issue by Toflar** [contao/contao#2283]
I guess we can just implement it the same as for webp?
I quickly checked locally for `var_dump(Imagick::queryFormats('AVIF'));` and I do get a result 😄 

/cc @ausi

**Comment by ausi** [comment]
This needs to be added in Imagine first I think in https://github.com/avalanche123/Imagine/blob/develop/src/Imagick/Image.php#L941 and in https://github.com/avalanche123/Imagine/blob/develop/src/Imagick/Image.php#L819

Did you check if `‌Imagick::setImageCompressionQuality()` works for AVIF images?

**Comment by Toflar** [comment]
Nope, I did not.

**Comment by ausi** [comment]
I created a pull request for Imagine: https://github.com/avalanche123/Imagine/pull/759

**Comment by leofeyer** [comment]
The PR has been merged meanwhile. How do we continue here?

**Comment by ausi** [comment]
I think we did all we need already with #3542 

After someone verifies that this works with `imagine/imagine` version 1.3.1, we can close this ticket IMO.
