### ISSUE TITLE
Bei der Ausführung des Skriptes ist ein Fehler aufgetreten. Irgendetwas funktioniert nicht richtig.

### ISSUE THREAD

**Issue by temran** [contao/contao#2289]
**Affected version(s)**

Contao 4.4 or Contao 4.9?

**https://delingsdorf.glantz.de/galerie-delingsdorf/v-tour-hoffest-2017-luftpanorama.html

Was ist das Problem?
Bei der Ausführung des Skriptes ist ein Fehler aufgetreten. Irgendetwas funktioniert nicht richtig.

Wie kann ich das Problem lösen?
Öffnen Sie die aktuelle Log-Datei im Ordner var/logs und suchen Sie die zugehörige Fehlermeldung (normalerweise die letzte).

Weitere Informationen
Die Skriptausführung wurde gestoppt, weil irgendetwas nicht korrekt funktioniert. Die eigentliche Fehlermeldung wird aus Sicherheitsgründen hinter dieser Meldung verborgen und findet sich in der aktuellen Log-Datei (siehe oben). Wenn Sie die Fehlermeldung nicht verstehen oder nicht wissen, wie das Problem zu beheben ist, durchsuchen Sie die Contao-FAQs oder besuchen Sie die Contao-Supportseite.**

**Comment by m-vo** [comment]
Please refer to the Contao forum or slack channel for these kind of support questions.

It would also be helpful if you open the page in debug mode and look at the actual error message (or in the log as stated in your posted error message).

**Comment by leofeyer** [comment]
> Weitere Informationen
> Die Skriptausführung wurde gestoppt, weil irgendetwas nicht korrekt funktioniert. **Die eigentliche Fehlermeldung** wird aus Sicherheitsgründen hinter dieser Meldung verborgen und **findet sich in der aktuellen Log-Datei** (siehe oben). Wenn Sie die Fehlermeldung nicht verstehen oder nicht wissen, wie das Problem zu beheben ist, durchsuchen Sie die Contao-FAQs oder **besuchen Sie die Contao-Supportseite**.**

https://contao.org/de/support.html

**Comment by temran** [comment]
Thank you, I have informed the site owner. His webmaster will be solving this problem.
