### ISSUE TITLE
Newsletter subscribe modul in page layout always triggers captcha

### ISSUE THREAD

**Issue by arno1979** [contao/contao#229]
**Affected version(s)**
I experienced the problem in 4.4.30 (but not in 4.6.10).

**Description**  
I have a newsletter subscription frontend module and placed it in the page footer via a pagelayout.
Showing of channels is disabled, disable captcha is NOT activated.
When loading the page for the first time the input field for the e-mail address is displayed as expected.
When entering an e-mail address and submitting the form is is not send, instead the captcha field appears in addition to the e-mail input field.
The captcha can never be solved though: Although I am completely sure to have correctly calculated the value for the field I am never able to send the form. The page is always displayed with the prompt to solve the captcha again.
Currently the only way to make it work is by disabling the captcha in the module configuration.
And I double checked: If I insert it into a single page as a content element the problem does not occur.

**How to reproduce**  
I could not reproduce this on the Contao demo version because the problem is apparently limited to Contao 4.4.x.
In a 4.4.30 setup create a newsletter subscription module and place it into a page layout.
Load a page with the matching layout assigned and try subscribing to the newsletter.

**Comment by asaage** [comment]
Just guessing...
I suspect you have another form on this page and/or not configured a redirect-page.

**Comment by arno1979** [comment]
@asaage I have the search form and yes: No redirect page as it is not needed and not required.
I made a quick test, removed the search form and set a redirect page: It makes no difference.

**Comment by asaage** [comment]
Then check [this](https://github.com/contao/contao/issues/194) or provide a link!

**Comment by arno1979** [comment]
Okay, after reading #194 I checked and there were 404s on every page because of a webfont that could not be loaded. After fixing that the problem goes away.
Thanks!
