### ISSUE TITLE
Allow using Twig templates to implement/replace Contao templates

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2303]
Some time ago I created a [bundle](https://github.com/m-vo/contao-twig) that allows using Twig templates instead of or to overwrite Contao PHP templates. This concept really works out nicely if you want a 'twig-only' approach without having to change every single template. 

One thing that bothers me, though, is that a [proxy PHP template](https://github.com/m-vo/contao-twig/blob/master/src/Resources/contao/templates/twig_template_proxy.html5) needs to be rendered along each Twig template. If we would implement this in the core instead, the correct renderer could be chosen from the beginning.

This would basically mean that templates inside the `/templates` folder can either have a `.html5` or `.twig` extension (same logic). If both exist I'd give the Twig version precedence.

**Comment by aschempp** [comment]
We've discussed Twig a few times, but there are a few more obstacles than "just" using it in modules.

**Comment by m-vo** [comment]
>  but there are a few more obstacles than "just" using it in modules.

This is not about replacing our templates but enabling users that know how to deal with it to use them (like #1399). Or do you see any specific problems with this?

**Comment by m-vo** [comment]
Still thinking about this.

**Comment by m-vo** [comment]
Closing in favor of #2612
