### ISSUE TITLE
"Edit comment" links without token check

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#2310]
**Affected version(s)**
4.4, 4.9, 4.10

**Problem**
If someone adds a new comment, I correctly get a notification by email.
If you click to the edit-link you become a stop-message (see attachment)

Is there an option to generate a notification that doesn't show this stop-message?
Maybe by adding a token to the link?
My customers feel insecure with this message.

**Steps**
1. Add Comment
2. Open email notification
3. Click edit-link

![ungueltiges-token](https://user-images.githubusercontent.com/23719181/93660626-424f2700-fa51-11ea-91d6-c5f8b6dfdf9b.jpg)

**Comment by ausi** [comment]
Backend URLs that have the `act` parameter set, require to have the request token parameter `rt` too.

Maybe we could exclude `act=edit` from that check? I think `act=edit` should not cause any changes so it should not require a request token. But I’m not sure if we can guarantee that this is the case everywhere in Contao.

**Comment by Toflar** [comment]
This message is there because we have links that incorrectly execute actions despite being GET request (e.g. `act=delete`). We‘ve thus added this token protection a very long time ago and we can‘t fix this properly for Contao 4.x as this would be a major BC break.
In theory, edit links are unproblematic but we just don‘t know. Extension developers might also execute actions (which is wrong but well) and rely on this token being present and thus being a desired action. This is too much of a risk for me, I would leave it as is.

**Comment by contaoacademy** [comment]
Many thanks for the explanation. Then the users just have to read. 😁

**Comment by ausi** [comment]
I think we should reopen this issue and change the links to something without `act=` that then redirects to the correct edit page.

**Comment by aschempp** [comment]
wouldn't that make the current security approach obsolete if you can bypass it by knowing the URL?

**Comment by leofeyer** [comment]
That is what I was thinking, too.

**Comment by ausi** [comment]
> wouldn't that make the current security approach obsolete if you can bypass it by knowing the URL?

The security approach is wrong in this case. The edit url is not dangerous, but we cannot allow it generally (for all `act=edit` URLs).

Adding a different URL without `act=` for this specifc case only enables this specific `act=`-URL and not generally all `act=`-URLs which would be dangerous.

**Comment by aschempp** [comment]
Maybe we could use signed URLs in the email to bypass the token check?

**Comment by leofeyer** [comment]
See #5461.
