### ISSUE TITLE
Simple tokens evaluation behaviour different between Contao 4.10 and <4.10

### ISSUE THREAD

**Issue by SimonSpi** [contao/contao#2315]
**Affected version(s)**
Contao 4.10

**Description**
There is an incompatibility in simple token evaluation in Contao 4.10 and earlier versions. When a simple token value is non-existent in prior versions this evaluated to NULL however starting from Contao 4.10 this will throw an exception. The root cause seems to be the switch to using Symfony Expression Language for simple token evaluation.
The problem for me popped up because I'm using a template in notification center for different forms. Because some input fields are only available in certain forms I used the following statements for dealing with the problem:
```
{if form_foo!=NULL}
Bar: ##form_foo##
{endif}
```
However this does not work anymore with Contao 4.10.

For Symfony Expression Language the issue is known for a long time and was reported in https://github.com/symfony/symfony/issues/21691. However it seems that resolution is not planned in a sensible timeframe. Community user webstar came up with the idea of resolving the incompatibility within Contao (see https://community.contao.org/de/newreply.php?do=newreply&p=531754).

Any changes resolving the problem will be greatly appreciated. Thanks

**Comment by m-vo** [comment]
Are we talking about the `InvalidArgumentException` being thrown here?

https://github.com/contao/contao/blob/321062bd8b25cb09c09f11afc79ce2c19940521b/core-bundle/src/Util/SimpleTokenParser.php#L141-L145

/cc @Toflar

**Comment by SimonSpi** [comment]
I guess so, however I for some reason have kind of a mismatch of the line of code:
`in [...]/vendor/contao/corebundle/src/Util/SimpleTokenParser.php (line 133)`

Just to make sure we are talking about the same version - Contao Manager says Version 4.10.0 (14.08.2020, 08:59)

**Comment by m-vo** [comment]
Can you please post the entire error message/stack trace?

**Comment by SimonSpi** [comment]
Sure. Here it is:

```
InvalidArgumentException
in [...]vendor/contao/core-bundle/src/Util/SimpleTokenParser.php (line 133)
in [...]vendor/contao/core-bundle/src/Util/SimpleTokenParser.php -> evaluateExpression (line 65)
in [...]vendor/contao/core-bundle/src/Resources/contao/library/Contao/StringUtil.php -> parseTokens (line 565)
in [...]vendor/codefog/contao-haste/library/Haste/Util/StringUtil.php :: parseSimpleTokens (line 49)
in [...]vendor/terminal42/notification_center/library/NotificationCenter/MessageDraft/EmailMessageDraft.php :: recursiveReplaceTokensAndTags (line 156)
in [...]vendor/terminal42/notification_center/library/NotificationCenter/Gateway/Email.php -> getTextBody (line 122)
in [...]vendor/terminal42/notification_center/library/NotificationCenter/Gateway/Email.php -> sendDraft (line 194)
in [...]vendor/terminal42/notification_center/library/NotificationCenter/Model/Message.php -> send (line 83)
in [...]vendor/terminal42/notification_center/library/NotificationCenter/Model/Notification.php -> send (line 52)
in [...]vendor/terminal42/notification_center/classes/tl_form.php -> send (line 62)
in [...]vendor/contao/core-bundle/src/Resources/contao/forms/Form.php -> sendFormNotification (line 537)
in [...]vendor/contao/core-bundle/src/Resources/contao/forms/Form.php -> processFormData (line 251)
in [...]vendor/contao/core-bundle/src/Resources/contao/classes/Hybrid.php -> compile (line 232)
in [...]vendor/contao/core-bundle/src/Resources/contao/forms/Form.php -> generate (line 86)
in [...]vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php -> generate (line 589)
in [...]vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php :: getContentElement (line 187)
in [...]vendor/contao/core-bundle/src/Resources/contao/modules/Module.php -> compile (line 209)
in [...]vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php -> generate (line 74)
in [...]vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php -> generate (line 529)
in [...]vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php :: getArticle (line 380)
in [...]vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php :: getFrontendModule (line 168)
in [...]vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php -> prepare (line 48)
in [...]vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php -> getResponse (line 343)
in [...]vendor/symfony/http-kernel/HttpKernel.php -> renderPage (line 158)
in [...]vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 80)
in [...]vendor/symfony/http-kernel/Kernel.php -> handle (line 201)
Kernel->handle(object(Request))
in [...]web/preview.php (line 31)
/** @var Composer\Autoload\ClassLoader */$loader = require __DIR__.'/../vendor/autoload.php';$request = Request::createFromGlobals();$kernel = ContaoKernel::fromRequest(\dirname(__DIR__), $request);$response = $kernel->handle($request);// Force no-cache on all responses in the preview front controller$response->headers->set('Cache-Control', 'no-store');// Strip all tag headers from the response
Symfony\Component\ExpressionLanguage\
SyntaxError
Variable "form_foo" is not valid around position 1 for expression `form_foo!=NULL`.
```

**Comment by m-vo** [comment]
We should not throw an exception if a variable does not exist but log it instead. Maybe we should implicitly add non-existing tokens with a value of `null`. 

I'll see what we can do.

**Comment by SimonSpi** [comment]
@m-vo - did you see the comment by tolecar https://github.com/symfony/symfony/issues/21691#issuecomment-696064698 at the Symfony repository? I'm not sure if this is of any help as it will be a separate library however this might be considered anyways.

**Comment by m-vo** [comment]
@SimonSpi I think we can work around this. 

I started to setup some unit tests in #2341 that allow comparing against the old implementation - we should first add some more samples there and then look what should be done.

**Comment by Kahmoon** [comment]
Hi, i also have a problem since the last contao update.

I´m using one notification for different forms. Actually i get an error of a missing field (not every form has this field).

**Error:**
`InvalidArgumentException:Variable "form_termine" is not valid around position 1 for expression `form_termine!=""``

**Configuration in notification**
```
Anfrage für: ##form_herkunft##
{if form_termine!=""}
   Termin: ##form_termine##
{endif}


{if form_formtyp!="erweitert"}
Name: ##form_name##
E-Mail: ##form_email##
Telefon: ##form_telefon##
{else}
Vorname: ##form_vorname##
Name: ##form_name##
Straße: ##form_strasse##
PLZ: ##form_plz##
Ort: ##form_ort##
{endif}
```

In previous versions it worked fine. 

Workaround: Actually i have to add a hidden field "termine" to every form which does not have it :-(.

greetz
Frank

**Comment by m-vo** [comment]
This doesn't add any new case new to [the list](https://github.com/contao/contao/pull/2341#issuecomment-699525334), does it?

**Comment by SimonSpi** [comment]
Thx, for having this fixed quickly!
