### ISSUE TITLE
Trailing spaces in news URL results in unexpected behavior

### ISSUE THREAD

**Issue by TheOnlySpeedy** [contao/contao#2319]
**Affected version(s)**

Contao 4.4 and Contao 4.9?

**Description**

When a trailing space or %20 is added to the end of an alias in the URL, the original news page is still loaded and shown instead of a 404 page.
This can result in duplicate content errors in e.g. Google search console as it is a different URL but with the exactly same content.

https://demo.contao.org/en/news-detail/new-contao-versions-in-short-intervalls.html
is the same as https://demo.contao.org/en/news-detail/new-contao-versions-in-short-intervalls%20.html
https://contao.org/de/news/rueckblick-auf-das-zweite-core-entwicklertreffen-2020.html
is the same as https://contao.org/de/news/rueckblick-auf-das-zweite-core-entwicklertreffen-2020%20.html
This only occurs on news pages, article pages are not affected by this.
https://demo.contao.org/en/content-elements.html works
https://demo.contao.org/en/content-elements%20.html does not work / 404 page not found

As far as I've found, it's because of how MySQL compares strings with the equal operator (https://blogs.agilefaqs.com/2011/06/22/trailing-white-spaces-are-ignored-by-mysql-for-comparison-in-a-select-statement/).
`Select 'test' = 'test ';` returns true
`Select 'test' like 'test ';`returns false

Changing from = to like in news-bundle/src/Resources/contao/models/NewsModel:190 solves the problem.
But maybe a validation check for the alias before `$objArticle = NewsModel::findPublishedByParentAndIdOrAlias(Input::get('items'), $this->news_archives);` (news-bundle/src/Resources/contao/modules/ModulesNewsReader:91) is more suitable?

**Comment by ausi** [comment]
We cloud check for that case and explicitly disallow spaces at the end with something like  
`if (substr((string) $varId, -1) === ' ') { return null; }`

But that would break actual aliases that have spaces at the end, so maybe the switch to `LIKE` is our best option?

**Comment by ausi** [comment]
@m-vo and I looked at this a little bit more. We think making a `BINARY` comparison might be the best fix for this issue: `WHERE BINARY $t.alias=?`

**Comment by leofeyer** [comment]
This would affect all WHERE conditions with `alias=`, wouldn't it?

**Comment by leofeyer** [comment]
Also, will `BINARY` not make aliases case-sensitive?

**Comment by m-vo** [comment]
> Also, will BINARY not make aliases case-sensitive?

Yes. 

Before it would depend on the chosen collation. If we do not want case-sensitivity we would ideally choose a case insensitive collation without padding (e.g. `utf8mb4_unicode_nopad_ci`) but unfortunately this isn't widely available across mysql/mariadb versions.

**Comment by ausi** [comment]
> Also, will `BINARY` not make aliases case-sensitive?

I think they are already because of the `_bin` collation we are using now. See https://contao.org/de/release-Plan.html vs https://contao.org/de/release-plan.html

**Comment by leofeyer** [comment]
So to fix this, we have to replace all occurrences of `WHERE $t.alias=?` with `WHERE BINARY $t.alias=?`?
