### ISSUE TITLE
DCA maxlength validation causes unexpected behaviour, by use of special characters

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#2325]
**Affected version(s)**

Contao 4.9

**Description**

If I set the maxlength for a dca inputfield (in my example 150), the maxlength validation returns an error, if special characters like brackets are in the string. Technically this occurs because utf8 encoding of special characters, but this is not the expected behaviour 

Here is my Example:

`Unsere Produkte mit technischen Vorteilen (z.B. Leichtbau, ESD-Fähigkeit, EMV-Verträglichkeit) sind nachhaltig erzeugt und verbessern die CO2-Bilanz.` → 150 characters

After encoding:

`Unsere Produkte mit technischen Vorteilen &#40;z.B. Leichtbau, ESD-Fähigkeit, EMV-Verträglichkeit&#41; sind nachhaltig erzeugt und verbessern die CO2-Bilanz.` → 157 characters

**Comment by asaage** [comment]
Did you try that with ```eval => useRawRequestData= true``` ?
https://docs.contao.org/dev/reference/dca/fields/#evaluation

That might have other sideeffects but i don't think there is a way to predict the final length of text after encoding.

**Comment by theDyingMountain** [comment]
Imo the check should be done before the encoding. The actual behaviour is not user friendly.

**Comment by fritzmg** [comment]
> Imo the check should be done before the encoding. The actual behaviour is not user friendly.

But then the string will be cut off, if it reaches the maximum length of the database field.

**Comment by m-vo** [comment]
Yes, that's imo only solvable with output encoding and a database charset able to store the unprocessed input. 
Probably nobody will notice it with sufficient headroom, though.
