### ISSUE TITLE
No output of image caption using referenced article with gallery

### ISSUE THREAD

**Issue by lumas-consulting** [contao/contao#233]
**### Can be deleted. Problem solved. Caused by a different language Code on the referenced page
#####**

**Affected version(s)**
3.5.35
**Description**  
I have an article with a gallery. Meta data are set in file. In the origin article all metadata are output.
When I reference this article on another site, the caption meta will not be output.
**How to reproduce**  

Orignial article 
![original](https://user-images.githubusercontent.com/6641281/49926283-8516bf00-febb-11e8-9ec0-38040484ed5e.png)
Related article
![referenced_article](https://user-images.githubusercontent.com/6641281/49926284-8516bf00-febb-11e8-82ef-fe56dc53ed93.png)

**Comment by fritzmg** [comment]
> When I reference this article on another site, the caption meta will not be output.

What do you mean by "reference" and "another site"? Is the site in another language for example?

**Comment by lumas-consulting** [comment]
As mentioned above, this issue can be deleted/closed. 
The site was in another language and no specific meta data for this language captured.
