### ISSUE TITLE
Image size set to width=0 height=0

### ISSUE THREAD

**Issue by ausi** [contao/contao#2330]
**Affected version(s)** 
Contao 4.10

**Description**

If a files/assets static URL is set in the root page, the image dimensions are missing.

I think the following line https://github.com/contao/contao/blob/b7e1aecd3ebe998b4189f530fe857eb8df1bf788/core-bundle/src/Image/Studio/Figure.php#L260 needs to be replaced with: 

```php
$fileInfoImageSize = (new File(StringUtil::stripRootDir($image->getPicture()->getImg()['src']->getPath())))->imageSize;
```

Also, if the size cannot be determined we should set an empty string here I think: https://github.com/contao/contao/blob/b7e1aecd3ebe998b4189f530fe857eb8df1bf788/core-bundle/src/Image/Studio/Figure.php#L276 this currently results in ` width="0" height="0"` which ist most probably not desired.

/cc @m-vo

**Comment by m-vo** [comment]
`$image->getImageSrc()` should imo already return the path. When does this return something else then a string?

We should definitely normalize it, though. (Maybe with `Path` instead of `StringUtil` but :+1: )

> Also, if the size cannot be determined we should set an empty string here I think

:+1:

**Comment by ausi** [comment]
`$image->getImageSrc()` returns the URL. That’s why there is currently a `rawurldecode()` around it.

Should we add a `$image->getImageSrcPath()` method?  
Or a parameter `getImageSrc(bool $asPath = false)`?
Or use `$image->getPicture()->getImg()['src']->getPath()` directly?
