### ISSUE TITLE
Show correct Punycode for umlaut subdomains in Contao backend meta title

### ISSUE THREAD

**Issue by minstyle** [contao/contao#2335]
**Affected version(s)**

Contao 4.9.5 (other Contao releases not tested)

**Description**

The meta title in the backend shows the domain. It would be nice if the punycode would not be displayed here for umlaut subdomains, ie "demo.präfner.de" instead of "demo.xn--prfner-cua.de".

See also: #507 

**How to reproduce**

Call the Contao backend with an umlaut subdomain.

**Comment by ausi** [comment]
We should probably replace https://github.com/contao/contao/blob/79540dc4b96246e575355f03ec03f3c28d8c091b/core-bundle/src/Resources/contao/classes/Backend.php#L1152 with something like

```php
if (strpos($host, 'xn--') !== 'false')
```
