### ISSUE TITLE
Link-Address is not replaced correctly

### ISSUE THREAD

**Issue by jxns** [contao/contao#2346]
**Affected version(s)**

Contao 4.10.1

**Description**

When selecting a new link-address for a Hyperlink content element (after a link-address was previously already set), the insert-tag is not set correctly and the link is not working:

**Example:**
Insert Tag before selecting a new page for the link-address: {{link_url::21}}
Insert Tag after selecting a new page for the link-address: 21,{{link_url::25}}
Expected insert tag after selecting a new page for the link-address: {{link_url::25}}

**Comment by fritzmg** [comment]
Hm, I think this is probably related to https://github.com/contao/contao/pull/2296, I'll have a look.
