### ISSUE TITLE
#2294 breaks several form field generator fields using value '0'

### ISSUE THREAD

**Issue by philvdb** [contao/contao#2347]
**Affected version(s)**

Contao 4.9.6 (likely 4.4 and 4.10 branches as well)

**Description**

In versions up to 4.9.5, it was possible to enter the integer `0` (which gets converted to `"0"`) as value in a select menu field of the form generator, like so:

![Bildschirmfoto von 2020-09-24 17-22-40](https://user-images.githubusercontent.com/1567784/94165750-d888b000-fe8a-11ea-9db2-fa9c702f4216.png)

I believe this may very well be a common use case, with any form field widget that allows options, like select, radio or checkbox menus.

With the change in #2294, entering the value `0` will be serialized as `""` (not as `"0"` like before) because of [this line](https://github.com/contao/contao/blame/4.9/core-bundle/src/Resources/contao/library/Contao/Widget.php#L813) having changed from `$value == ''` (which was `false` for `$value = "0"`) to `!$value`, which unfortunately evaluates to `true` for `$value = "0"`.

This subtle change has actually wreaked havoc on our install and caused some data loss. I could imagine this having adverse effects in several other more or less expected places.

**Comment by fritzmg** [comment]
Would it be fixed by https://github.com/contao/contao/pull/2342 ?

**Comment by philvdb** [comment]
Absolutely.

I see you're already on this, sorry, I didn't know that.
