### ISSUE TITLE
'Unknown Option' in several checkbox widgets

### ISSUE THREAD

**Issue by LIVID-Media** [contao/contao#2349]
**Affected version(s)**

Contao 4.10.1?

**Description**

After updating Contao from 4.10 to 4.10.1 there is an 'Unknown Option' in several checkbox widgets like 'Convert image formats' in the image sizes or the 'News archives' in newslist module. They appeared without making any changes. Maybe a effect of #920 and #2215?

**Comment by ausi** [comment]
Can you post a screenshot of an example and check what data is stored in the database for that specific field?

**Comment by scoomDev** [comment]
![image](https://user-images.githubusercontent.com/26569519/94194375-e30a7000-feb1-11ea-8f57-fc93ff1e6c3d.png)

I have the same problem in `tl_page` => protected option

**Comment by ausi** [comment]
@scoomDev what data is stored in the database for that specific field?

**Comment by LIVID-Media** [comment]
![grafik](https://user-images.githubusercontent.com/61419192/94232529-7d949e80-ff06-11ea-8900-d689c16de226.png)

And in den database:
a:3:{i:0;s:12:"png:webp,png";i:1;s:27:"jpg:webp,jpg;jpeg:webp,jpeg";i:2;s:12:"gif:webp,gif";}

If I deselect all and save the entry, the 'Unknown option' is gone. If I then select one or all of the options again, the 'Unknown option' is there again.

The 'Unknown option' is always deselected. By selecting it manually (all others selected too) and saving the entry, the database changes to:
a:4:{i:0;s:12:"png:webp,png";i:1;s:27:"jpg:webp,jpg;jpeg:webp,jpeg";i:2;s:12:"gif:webp,gif";i:3;s:93:"a:3:{i:0;s:12:"png:webp,png";i:1;s:27:"jpg:webp,jpg;jpeg:webp,jpeg";i:2;s:12:"gif:webp,gif";}";}

**Comment by akroii** [comment]
Same issue in Theme -> Layout -> javascript-Templates:
<img width="447" alt="Bildschirmfoto 2020-09-25 um 10 47 18" src="https://user-images.githubusercontent.com/8830861/94246822-82fce380-ff1c-11ea-82bd-bec958ce3029.png">

In the database:
`a:5:{i:0;s:11:"j_smartmenu";i:1;s:18:"j_accordion_footer";i:2;s:12:"j_slick-hero";i:3;s:11:"j_slick-car";i:4;s:13:"j_equalHeight";}`

Contao 4.10.1

**Comment by leofeyer** [comment]
I can confirm the issue in the online demo:

<img width="603" alt="" src="https://user-images.githubusercontent.com/1192057/94248622-07506600-ff1f-11ea-9c7d-753c655f805f.png">

**Comment by mpitz** [comment]
I can confirm this in 4.9.7 selecting frontend modules:
![image](https://user-images.githubusercontent.com/6831223/94248963-80e85400-ff1f-11ea-96da-7493ad1d4f15.png)

**Comment by zonky2** [comment]
Currently the debug mode runs empty with a warning, because in some widgets the StringUtil is called with an array instead of string :(
