### ISSUE TITLE
Main article module is not generate

### ISSUE THREAD

**Issue by scoomDev** [contao/contao#2352]
**Affected version(s)**

Contao 4.9.6?

Description

After updating Contao from 4.9.5 to 4.9.6, when i save a layout (tl_layout). The main article module is save with an empty ID, not "0" and isn't generate.

I try that in 3 differents projects.

**Comment by fritzmg** [comment]
Should be fixed by https://github.com/contao/contao/pull/2342

**Comment by philvdb** [comment]
I've spent some time debugging this today as well .. `$value == ''` is not synonymous with `!$value`, learned the hard way.
