### ISSUE TITLE
Hook for validating user registrations

### ISSUE THREAD

**Issue by jxns** [contao/contao#2356]
Hello!
Is it possible to extend the hooks for users?

I added a field to the member DCA which I also query in the registration. I want to confirm the field and make it dependent on whether a registration is allowed or not. Like a query for a license key.

The only hook I found which would be nearly matching was the createNewUser-Hook but this hook is fired **after** the registration is already done.

Can we add a new hook like **verifyNewUser** which is executed after the registration form was send but before the new user is created and which also requires a return value so that the registration can be rejected, if necessary?

**Comment by fritzmg** [comment]
Just use a `save_callback` on your field in order to validate it.

**Comment by jxns** [comment]
Thank you, that was exactly what I was looking for!
