### ISSUE TITLE
Articles are not shown anymore

### ISSUE THREAD

**Issue by jxns** [contao/contao#2357]
**Affected version(s)**

Contao 4.10.1

**Description**

All articles are not displayed in the frontend anymore. They are activated and the content is still available in the backend.
When inspecting the fe_page template, I noticed that the whole content of the main object ($this->main) is empty.
I cannot narrow down the problem any further. What can I provide you to give you more insight?

**Comment by aschempp** [comment]
This should be fixed in Contao 4.10.2, please update your installation. see https://github.com/contao/contao/issues/2352

**Comment by fritzmg** [comment]
You need to update Contao to version **4.10.2**. See https://github.com/contao/contao/pull/2342#issuecomment-698513745
