### ISSUE TITLE
Fehler bei der Verarbeitung der Galerie

### ISSUE THREAD

**Issue by mokaki60** [contao/contao#2358]
**Affected version(s)**

ab Contao 4.10.0

**Description**

**Fehler in der Galerie:**
Vorschaubilder werden korrekt angezeigt, aber die "Großansicht" wird nicht eingebunden, wenn die Dateiendung .JPG Großgeschrieben ist (kein link). 
Änderung der Dateiendung auf Kleinschreibung und Synchronisierung behebt (als Soforthilfe) das Problem.

**Comment by m-vo** [comment]
What do you mean with "no link"? Is there an empty src tag for instance? 

Edit: sorry misread it probably: I assume you selected lightbox/fullsize. Do you use any lightbox/mediabox script?

**Comment by mokaki60** [comment]
with "no link" i mean that the A element is completely missing from the html for images with uppercase file extensions. and i am using j_colorbox.

example from one of the pages i am managing: [link here](https://www.mfg-alt-neuoetting.de/bildberichte-details/ostern.html)
ever since the update (no other changes were made) the images in this article can not be clicked anymore (see the missing A element), while images from other articles can be clicked ([example here](https://www.mfg-alt-neuoetting.de/bildberichte-details/fertigstellung.html)). the same bug appeared on another project. some testing showed that the uppercase file extension are the culprits.

the problem should be easy to reproduce by uploading and showing an image with uppercase file extension.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2365
