### ISSUE TITLE
Change from 'tl_content' the option 'marcAsCopy' => 'headline'

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#236]
Hello Conto Team
By copying content elements, the Contao adds the suffix (copy) to headline.

'marcAsCopy' => 'headline'

If you duplicate several elements (e.g. 30 elements in same article), the headlines all of these elements get the suffix (copy).
As a result, each element has to be reworked individually and this is counter productive for the back end user.

I think that this option is not good for the back end user and only drives more effort.
There is certainly a reason why it is so, but I did't understand what it should be good for?

Can anyone explain for me the reason why it is so, maybe I can understand it and find it useful.

**Comment by leofeyer** [comment]
Please refer to the [forums](https://community.contao.org) for this kind of questions.

**Comment by fritzmg** [comment]
It's not really a question, more a suggestion to remove this within Contao by default, unless there is a good reason to keep it.

**Comment by leofeyer** [comment]
Of course there is: https://github.com/contao/core/issues/2938
