### ISSUE TITLE
Potential issue in migration order

### ISSUE THREAD

**Issue by aschempp** [contao/contao#2364]
**Affected version(s)**

Contao 4.9+

**Description**

Because migrations have no priority (https://github.com/contao/contao/pull/1963), the core migrations might not be executed in the expected order:

<img width="524" alt="Bildschirmfoto 2020-09-25 um 15 23 41" src="https://user-images.githubusercontent.com/1073273/94292531-63d27600-ff5d-11ea-9e14-18fa1a2738c5.png">

@ausi wants to fix this another way than priorities 😆

**Comment by m-vo** [comment]
What is the expected order? :slightly_smiling_face: 
Imo this could/should be done with the right precondition checks (`shouldRun`).

**Comment by ausi** [comment]
> What is the expected order? 🙂

The core migrations should be ordered by version ascending.

>  Imo this could/should be done with the right precondition checks (`shouldRun`).

You are right, but the older migrations were not written very “defensive” and expected to run in the correct order.

I think we should move the older migrations from the installation-bundle to the core-bundle and improve some of the `shouldRun` checks.

**Comment by ausi** [comment]
On my list ☺️

**Comment by ausi** [comment]
Closed in favor of #2545
