### ISSUE TITLE
News module : separate date and time

### ISSUE THREAD

**Issue by JLBA** [contao/contao#2367]
In news module metadatas, let the option to display date only and or date and time.

**Comment by kikmedia** [comment]
Isn't this a thing you can achieve within a template or a site specific date setting with ease?

**Comment by JLBA** [comment]
Thanks Carolina,
I set up the french date setting. But when checking date in news archive, news module displays date and time. 
I found how to display date only in template : `<?php echo date('d/m/Y', $this->time) ?>`. Then Andreas corrected me with the right Contao way of thinking : `<?= \Date::parse('d/m/Y', $this->time) ?> `. But this not so obvious for me as I'm coming from design, not from development. So, a simple radio button to choose between 'Date' or 'Date and time' would be some help.
