### ISSUE TITLE
[Request]: Newsletter - Aktivierungsmail bei manueller Eintragung

### ISSUE THREAD

**Issue by kroerig** [contao/contao#2370]
Hallo,

ich vermisse eine Funktionen einem Benutzer eine Aktivierungsmail zu schicken, wenn ich ihn manuell zu einem Newsletter hinzufüge. Dort kann ich ihn zwar direkt aktivieren, dann haben aber beide keinen Nachweis.

Hintergrund: Wenn ich mündlich auf unseren Newsletter hinweise, erhalte ich oft die Antwort: "Dann nimm mich da auch mal auf". Auf den Hinweis, sich doch selbst über die Homepage anzumelden (damit Double-Opt-In greift), kommt dann meinst ein: "Dann mach Du das für mich".

Ähliches dürfte z.B. auf Messen gelten, wo man ein Kundengespräch schriftlich festhält und dem Kunden die Aufnahme in einen Newsletter anbietet.

Hier fände ich es gut, wenn es eine Option gäbe manuell die Opt-In-Mail auszulösen oder auch nur eine einfache Mail, die dem Empfänger bestätigt, dass er - wie gewünscht - aufgenommen wurde. So kann sich später keiner beschweren er hätte von nichts gewusst.

**Comment by frontendschlampe** [comment]
Naja, wenn es dem Interessent schon zu viel ist, sich selbst einzutragen, dann wird er auch die Opt-In-Mail nicht beantworten. Aber wenn du selbst Abonnenten einträgst, dann solltest du das selbst dokumentieren. Bei einer Messe hast du ja den Nachweis, wenn du ein entsprechendes Kontaktkärtchen ausfüllen lässt. Für die mündliche Zusage ist es so oder so schwierig. Klar kannst du dokumentieren, dass die Eintragung auf Basis eines Telefonats oder so lief, aber da nützt auch ein Infomail, dass er eingetragen wurde, nichts.

Wenn du also wirklich sicher gehen willst, dann lass ihn sich selber anmelden.

Eine andere Variante wäre: trag die Mailadresse doch einfach selber im Frontend bei der Newsletteranmeldung ein, dann bekommt er die entsprechende Opt-In-Mail.

P.S. Ich bin kein Anwalt, aber so würde ich es persönlich sehen/ machen.

**Comment by kroerig** [comment]
> Naja, wenn es dem Interessent schon zu viel ist, sich selbst einzutragen, dann wird er auch die Opt-In-Mail nicht beantworten.

Das ist da das Problem. Selbst eintragen ist ihnen zu kompliziert, aber die Info erhalten würden sie schon gern. Zielgruppe Ü60.

Im Backend kann ich ja auch Nutzer manuell hinzufügen. Warum löst dass dann nicht einfach die Opt-In-Mail aus?

**Comment by fritzmg** [comment]
> Im Backend kann ich ja auch Nutzer manuell hinzufügen. Warum löst dass dann nicht einfach die Opt-In-Mail aus?

Because it is assumed that you already got the permission to do that. Otherwise, why would you add it this way?

Mailchimp for example handles it the same way.

As @frontendschlampe already said, just use the front end module, if you want the recipient to receive the opt-in email.

**Comment by frontendschlampe** [comment]
> Warum löst dass dann nicht einfach die Opt-In-Mail aus?

Ich bin kein Entwickler, aber ich denke, im Backend fehlt die Zuordnung zu den entsprechenden Mails/Modulen und der Empfängerliste bzw. die Verbindung herzustellen ist nicht möglich.

**Comment by asaage** [comment]
Wie von @frontendschlampe beschrieben: trag die Mailadresse im Frontend ein wenn du Opt-In-Nachweise und Benachrichtigungen brauchst.

**Comment by m-vo** [comment]
You can also add another, possibly restricted, FE page with a (more) convenient registration form for your client that can be used on trade shows / from the hotline bureau and such. Your lawyer will tell you the details. :smile:

**Comment by leofeyer** [comment]
> Wie von @frontendschlampe beschrieben: trag die Mailadresse im Frontend ein wenn du Opt-In-Nachweise und Benachrichtigungen brauchst.

👍🏻
