### ISSUE TITLE
Contao 4.10.2 strips port number

### ISSUE THREAD

**Issue by tsarma** [contao/contao#2374]
**Affected version(s)**

Contao 4.10.2

**Description**

I am using Symfony's builtin web server for local developments:  `symfony server:start -d`

Symfony webserver is always started on some specific port. 
`The Web server is using PHP FPM 7.2.27`
`https://127.0.0.1:8000`.

And you can view your website on URL https://127.0.0.1:8000 without a problem, until Contao 4.10.0.
Now with the latest version Contao 4.10.2, I can not open the website in frontend as it strips away the port number from Url. 

But I can work in the backend as usual.

**Comment by leofeyer** [comment]
@aschempp /cc

**Comment by leofeyer** [comment]
What did you enter in the "Domain name" field?

<img width="781" alt="" src="https://user-images.githubusercontent.com/1192057/94578037-86270500-0277-11eb-9bd9-0fce25096858.png">

It does work for me if I leave the field empty. It does not work if I enter `127.0.0.1:8001`, but that is because of #2214.

**Comment by tsarma** [comment]
@leofeyer I did not enter anything in `Domain name`, it did not work for me then. But it works now! 

After following a suggestion by @m-vo in slack. I have enabled a Symfony proxy domain, which opened me another way to view a website during development phase. 

Why it is now working puzzled me a bit. Just to test it again, I've installed a fresh `contao 4.10.2`. Made a basic setups like default layout, admin user, website root, default language ... but without `Domain name`.  And I started symfony webserver `symfony server:start -d`. When I open the website (Frontend), the port number is stripped again, resulting in 403. !!

**Comment by m-vo** [comment]
> It does work for me if I leave the field empty. It does not work if I enter 127.0.0.1:8001, but that is because of #2214.

Same for me. 

@tsarma Maybe you can debug where the 403 comes from and if it's actually the right server (+ no hidden redirects). Make sure certificates are working and your browser cache is nuked.

**Comment by tsarma** [comment]
@m-vo Sorry, I was naive in my statement when I said 403. Since the port number is stripped away I was redirected to localhost (127.0.0.1).

**Comment by m-vo** [comment]
>  I was redirected to localhost

What is causing this redirect?

**Comment by tsarma** [comment]
Since the port number is stripped away, then it just list my directory.

**Comment by aschempp** [comment]
your screenshot says you configured https, are you using the correct protocol for your server?

**Comment by leofeyer** [comment]
The screenshot shows my installation and yes, I am using the correct protocol. The Symfony web server supports HTTPS even for 127.0.0.1:8001.

**Comment by tsarma** [comment]
@aschempp thanks for the hint. It works, when I enabled `https://` protocol from the website root Setting. By default from Contao it is set to `http://` (which I never cared to set it to https: during dev phase) but the Symfony webserver URL has `https://` in it.

I think this issue can be close, or should I close it?

**Comment by leofeyer** [comment]
Yes, please close the issue.
