### ISSUE TITLE
Articles cannot be created after a new installation

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#2384]
**Affected version(s)**

 Contao 4.10.2 andere Versionen habe ich diesbezüglich (noch) nicht getestet

**Description**
Bei Neuinstallation von Contao 4.10.2 (ohne Erweiterungen) können keine Artikel angelegt werden.
Nach Anlegen einer Seitenstruktur mit zwei Seiten sind unter Artikel keine Artikel vorhanden.

![2020-10-01_problem_artikel_contao_4_10_screen1](https://user-images.githubusercontent.com/3602676/94822218-b2bb5800-0402-11eb-8ae8-6d3f3a8801a6.jpg)

Versucht man über das Plus einen neuen Artikel anzulegen gibt es keinen Platz wo man den Artikel anlegen könnte.

![2020-10-01_problem_artikel_contao_4_10_screen2](https://user-images.githubusercontent.com/3602676/94822299-c666be80-0402-11eb-92a3-abee0bdb7bc5.jpg)

Wenn notwendig kann es in meiner Testinstallation angeschaut werden.

Hosting: Hostingwerk
PHP: Version PHP 7.4.10

Das Problem tauchte auch schon vor ein Paar Tagen in Slack auf https://contao.slack.com/archives/CK4J0KNDB/p1601460395118000

**Comment by contaoacademy** [comment]
Hast du auf der Testseite im Root ein Layout zugewiesen?

**Comment by mlwebworker** [comment]
Nein hatte ich zum Testen noch nicht.

**Comment by contaoacademy** [comment]
Bitte mach das mal, dann sollte es zumindest wieder gehen. Ob das so gewünscht ist, kann ich nicht beurteilen.

**Comment by fritzmg** [comment]
Duplicate of #2179 

@mlwebworker sorry for making you create an issue, just remembered there already is one 😁

**Comment by mlwebworker** [comment]
Kein Problem. Ich sollte mir vielleicht auch angewöhnen in den vorhandenen Tickets mal vorher zu suchen.
Mit zugewiesenem Layout lassen sich dann die Artikel auch hinzufügen.
