### ISSUE TITLE
"gender" is not valid around position 1 - kein Newsletter Testversand

### ISSUE THREAD

**Issue by Joam55** [contao/contao#2387]
**Affected version(s)**

Contao 4.10.2

**Description**
{if gender=="male"}Sehr geehrter Herr ##lastname##,{elseif gender=="female"}Sehr geehrte Frau ##lastname##,{else}Liebe Mitglieder,{endif}

Variable "gender" is not valid around position 1 for expression `gender=="male"`

Im Newsletter Testversand, der reguläre Versand funktioniert

**Comment by fritzmg** [comment]
Related: #2315
