### ISSUE TITLE
.mod_article.first im Zusammenhang mit "nur Gästen anzeigen"

### ISSUE THREAD

**Issue by bekanntmacher** [contao/contao#239]
Wenn der 1. Artikel nur Gästen angezeigt wird, erhält der zweite Artikel beim eingeloggten Zustand kein `.first`

**Comment by leofeyer** [comment]
Das ist leider ein kleines Henne-Ei-Problem, denn wir müssen die CSS-Klasse setzen, bevor wir [Controller::getArticle()](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Controller.php#L273) aufrufen, wissen aber erst anhand des Return-Wertes, ob der Artikel angezeigt wird oder nicht.

@contao/developers Wie lässt sich das sinnvoll (ohne Code Duplication) lösen?

**Comment by Toflar** [comment]
Die Klasse ersatzlos streichen. Sie liefert ja offentsichtlich nicht konstante Ergebnisse und ist somit nutzlos. Die Artikel wissen nichts voneinander und sollten es auch nicht. Mit `:first-child` und `nth-child()` haben wir ja genügend Möglichkeiten, die Probleme per CSS zu lösen.

**Comment by contaoacademy** [comment]
Die Klasse dürfte aber dann erst in einer 4.7 entfernt werden und nicht 4.4.33.

**Comment by asaage** [comment]
Also für mich klingt das logisch.
Mit CSS ```:first-child``` und ```nth-child()``` zu arbeiten macht natürlich Sinn wenn es die Optik betrifft.
Ich glaube ich hab das hin und wieder im Template als Kondition für bestimmte Ausgaben genutzt und bin erstmal dagegen.
Das gleiche Phänomen tritt im Übrigen auch auf ContentElement-Ebene auf.

**Comment by Toflar** [comment]
Hilft ja nix, dagegen zu sein. Es lässt sich nicht fixen. Und ich denke eine falsche `first` Klasse ist schlechter als gar keine.

**Comment by asaage** [comment]
Die Klasse im FE mag in einigen Fällen falsch sein.
Aber wenn's ersatzlos gestrichen werden soll dann bitte konsequent - also auch ```class="last"``` und bei den ContentElementen.
Ich möchte lieber nicht mutmaßen wie-viele Layouts das entfernen der Klasse zerschießen wird.
Interessanterweise gibt's das Problem bei Seiten nicht ( - da kommen die ```first``` und ```last``` Klassen wohl aus dem knpMenue.?.)
und bei den News/Events/FAQ - Listen auch nicht (da fehlt die Möglichkeit einzelne Elemente nur für Gäste zugänglich zu machen).
Dass sich das nicht fixen lässt mag ich irgendwie nicht glauben.
Ich ändere meinen Status dann mal von "bin dagegen" in "hab bedenken" ;-)

**Comment by bekanntmacher** [comment]
Ich habe es viel benutzt weil es da war. Bei den Artikeln vor allem auch zu gestalterischen Zwecken...
Eigeführt wurde es Ende 13: https://github.com/contao/core/issues/2583

Wenn man es streicht, dann müsste man es doch konsequent machen? 
Also auch bei:
- Newsliste
- Eventliste
- FAQliste
- Content Elemente
- Formular
- Galerie
- Navigation
- etc.

Grad bei Newslisten ist es halt schon praktisch: man kann für den ersten Beitrag das Template anders machen.

**Comment by Toflar** [comment]
Ich glaube ihr habt da etwas nicht ganz verstanden. Die Newsliste, Eventliste, FAQ-Liste, Galerie und Navigation sind Listenelemente. Das Element selber weiss von den Einträgen und kann denen daher die korrekten CSS-Klassen vergeben.
Ein Artikel ist kein Listenelement, genau das ist das Problem.
Und um konsistent zu bleiben, müssten die Klassen auch beim Content Element und Formular wegfallen, weil die haben potenziell genau das gleiche Problem. Sie wissen nichts voneinander.

**Comment by bekanntmacher** [comment]
ja das wäre so konsistent, schätze aber, dass wirft hohe Wellen.

NB: zu styling-Zwecken braucht es theoretisch bei den Listen auch keine Klassen. Beim responsiv nützt ein `row_first` oder ein `col_last` nicht viel...

**Comment by aschempp** [comment]
@leofeyer this should be closed (see https://github.com/contao/contao/pull/1803) and not `up-for-discussion`?

**Comment by leofeyer** [comment]
Closed in favor of #1803.
