### ISSUE TITLE
fe_page.html5 <?= $this->mootools ?>

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2393]
(I am not sure if it is a bug or improvement)

**Affected version(s)**
Contao 4.9

**Description**
in template fe_page.html5 at the end of file 
`<?= $this->mootools ?>` loads some JavaScript.

For me $this->mootools has some unclear points:
- it loads more than just mootools. It loads also jQuery AND my own JavaScript.
- it loads the JavaScript in another order than in the page layout (page layout: first my own JavaScript, than jQuery, than Mootools. But in frontend: it loads first the jQuery than mootools and than my own JavaScript)

I expected:
- fe_page.html5: $this->mootools loads only mootools stuff + (new) $this->jQuery and $this->javaScript
- the order in page layout settings would be in the "correct" order: jquery, mootools and after it the JavaScript Section

page layout settings in Contao 4.9:
![grafik](https://user-images.githubusercontent.com/1645099/94973226-614ac000-050b-11eb-81aa-98888720c1e1.png)

fe_page.html5 output
![grafik](https://user-images.githubusercontent.com/1645099/94974023-8fc99a80-050d-11eb-9044-80d0259fa5b5.png)

**Comment by fritzmg** [comment]
The variable is called `mootools` for historical reasons and remains as such for backwards compatibility.
