### ISSUE TITLE
Image link to the start page with alias index does not work

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#2394]
**Affected version(s)**

Contao 4.10
Contao 4.9 ist nicht betroffen
Contao 4.4 habe ich nicht getestet

**Description**
Setzt man ein Bildlink zur Startseite mit dem Alias "index" in der Dateiverwaltung oder bei "Metadaten überschreiben" in einer einsprachigen Contao-Installation (ohne Sprachkürzel) dann wird kein Link auf die Startseite gesetzt. Das Bild erscheint im Großformat. Der Link wurde über den Seitenwähler gesetzt. Ein Link zu jeder beliebigen Seite mit anderem Alias als "index" funktioniert.
Das Problem ist im Forum aufgetreten https://community.contao.org/de/showthread.php?79031-Link-auf-Startseite-mit-Alias-quot-index-quot-wird-nicht-erstellt#post532698 und auch bei einem Kunden der Contao Academy und konnte auch von @fritzmg reproduziert werden.

**Comment by fritzmg** [comment]
Closing in favour of #2395

**Comment by m-vo** [comment]
@mlwebworker Until we've got a solution for this you can probably enter `/` instead of the insert tag.

**Comment by mlwebworker** [comment]
Ja ich weiss. Hatte ich auch im Forum schon vermerkt. Ist auch nicht wirklich mein Problem, sondern ein Problem aus dem Forum.
