### ISSUE TITLE
schema.org/article: Read more = headline?

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2396]
**Affected version(s)**

Contao 4.9

**Description**
I guess Contao has anything to do regarding schema.org items

I tested demo.contao.org with this tool from Google:
https://search.google.com/test/rich-results?url=http%3A%2F%2Fdemo.contao.org%2F&user_agent=1
![grafik](https://user-images.githubusercontent.com/1645099/95002409-e7323e00-05d3-11eb-9d1d-573edacc18ae.png)
You can see, that f.e. the "Read more" is marked as "headline".
![grafik](https://user-images.githubusercontent.com/1645099/95002325-cfa68580-05d2-11eb-8f53-d4ade59811c2.png)

I know that schema.org could be a difficult topic......

I found out, that <meta itemprop="" content="" /> could help to struggle less with the mixture of html and schema.org-tags
![grafik](https://user-images.githubusercontent.com/1645099/95002449-85260880-05d4-11eb-8de1-0435c028f938.png)
https://schema.org/docs/gs.html

**Comment by aschempp** [comment]
is this a problem in your setup as well, or something we should fix on contao.org?

**Comment by fritzmg** [comment]
> I guess Contao has anything to do regarding schema.org items

What exactly do you mean?

> You can see, that f.e. the "Read more" is marked as "headline".

Yeah, that is indeed an error within `ModuleNews`. The error was introduced in https://github.com/contao/contao/commit/81560309b51cb822ee1511bd33c923bccce8d99b.
@leofeyer I don't think it ever makes sense to generate external links with `itemprop="headline"` and internal links where only "Read more ..." is marked with `itemprop="headline"`? I suppose this is may be done for the `news_simple` template, but I think it should be solved there by wrapping `<?= $this->linkHeadline ?>` with `<span itemprop="name">`.

**Comment by math-GH** [comment]
> 
> 
> is this a problem in your setup as well, or something we should fix on contao.org?

it is a problem of the standard news templates.

contao.org news archive 2020
![grafik](https://user-images.githubusercontent.com/1645099/95010656-62730e80-062b-11eb-9f79-5ab29c86df90.png)
https://search.google.com/test/rich-results?id=AMpVQ2cFdBDKsyCbJ1SShA

demo.contao.org news module
![grafik](https://user-images.githubusercontent.com/1645099/95010676-8afb0880-062b-11eb-8be7-088c23e228e2.png)
https://search.google.com/test/rich-results?id=35Qs6LnZhVinsJ3UDwYKng

**Comment by math-GH** [comment]
@fritzmg :
one more example where Contao could provide better Schema.org information by default: Events

on demo.contao.org I created a test event
![grafik](https://user-images.githubusercontent.com/1645099/95011346-65bcc900-0630-11eb-8930-de0f18d4211a.png)

![grafik](https://user-images.githubusercontent.com/1645099/95011370-7cfbb680-0630-11eb-88b2-64972a6586f2.png)
(https://demo.contao.org/en/event-detail/titel.html)

analysis:
![grafik](https://user-images.githubusercontent.com/1645099/95011386-a0266600-0630-11eb-9f8c-5180e403ac65.png)
https://search.google.com/test/rich-results?id=8b8bkJnIT3nBS6wWvA2t5w

- endDate: Contao has an enddate, but does not provide that information as schema.org
- itemscope of PostalAddress has no itemprop inside
![grafik](https://user-images.githubusercontent.com/1645099/95011457-188d2700-0631-11eb-9f27-03751a7d1c19.png)

**Comment by math-GH** [comment]
In case of startDate and endDate:

original template:
![grafik](https://user-images.githubusercontent.com/1645099/95012444-de278800-0638-11eb-9f29-ba559cad069c.png)


my new template:
![grafik](https://user-images.githubusercontent.com/1645099/95012430-c94af480-0638-11eb-876b-cc4d6e2308d3.png)

result
![grafik](https://user-images.githubusercontent.com/1645099/95012461-057e5500-0639-11eb-85db-06cf57b42734.png)

![grafik](https://user-images.githubusercontent.com/1645099/95012473-2777d780-0639-11eb-9c91-b68e7b59a68f.png)

**Comment by leofeyer** [comment]
I am not 100% sure what you are referring to. Is it this?

https://github.com/contao/contao/blob/103649e2971e34b8b956c0a645272d07f708a649/news-bundle/src/Resources/contao/modules/ModuleNews.php#L369-L371

https://github.com/contao/contao/blob/103649e2971e34b8b956c0a645272d07f708a649/news-bundle/src/Resources/contao/modules/ModuleNews.php#L391-L393

**Comment by fritzmg** [comment]
That's what I am referring to in https://github.com/contao/contao/issues/2396#issuecomment-703212985 at least, yes. That should be fixed.
