### ISSUE TITLE
Fehlerhafte Generierung der Eventleser-Detailseite bei Weiterleitungsziel

### ISSUE THREAD

**Issue by minstyle** [contao/contao#24]
**Affected version(s)**
contao/core-bundle 4.4.21
contao/calendar-bundle 4.4.21

**Description**  
Wenn ich ein neues Event erstelle (ohne Inhalt!) und als Weiterleitungsziel eine "externe URL" definiere, dann wird von Contao trotzdem eine Detailseite generiert, die über den "Event-Alias" erreichbar ist.

Suchmaschinen indexieren diese leeren Detailseiten!

**How to reproduce**  
1. Weiterleitungsziel "externe URL"
![image](https://user-images.githubusercontent.com/2649562/44449727-3b922380-a5ef-11e8-8606-e2f1d2e41a5c.png)

2. Aufruf des erstellten Events über den "Event-Alias"

![image](https://user-images.githubusercontent.com/2649562/44450070-4600ed00-a5f0-11e8-9db2-667dd400065c.png)

Z. B. über http://domain.de/de/veranstaltungen/detail/xxx

**Comment by fritzmg** [comment]
This is already changed in Contao 4.6. See https://github.com/contao/news-bundle/issues/33 » https://github.com/contao/calendar-bundle/commit/bb35f032e09dc9545a9ceab93c7419a0b0345202#diff-a6cd6f059e33db003de9fd87e0db02a2

It will show a 404 page now.
