### ISSUE TITLE
Fix StringUtil::parseSimpleTokens evaluating unknown tokens as false

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2402]
**Affected version(s)**

Contao 4.4

**Description**

from #2341:

> If we always return false if the condition contains unknown variables wouldn’t that flip the logic of inverted comparisons like {if foo!=""}?

We should define the values with `null` instead and continue with the evaluation. 

see https://github.com/contao/contao/pull/2341#discussion_r500259589

**Comment by aschempp** [comment]
I don't think we should change this in Contao 4.4, it has been like that _forever_ and noone complained. There's a risk of breaking something in a patch release, which seems only fine for me in 4.10 (as we did in your other PR).

**Comment by m-vo** [comment]
Well, it worked this way since the introduction in Contao 3 (2?) until we broke it in 4.2 and it works again in 4.10. For the sake of consistency I think we should make it work in the other supported versions as well.

**Comment by ausi** [comment]
> it has been like that _forever_

We broke it in Contao 4.2.3 (538f8ed8ce76e71b8f6d2d9d5782a6fd29855904), see https://github.com/contao/core-bundle/pull/570
I think we should fix it so that it works as it did in Contao 4.2.2 and before.

**Comment by leofeyer** [comment]
Agreed.

**Comment by m-vo** [comment]
see #2453
