### ISSUE TITLE
4.10.x Lightbox is not added to images when extension is uppercase e.g. .JPG

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#2405]
**Affected version(s)**

Contao 4.10.2

**Description**

When i add images to a contao gallery which have a file extension in uppercase (.JPG), lightbox is not added to the code. When i change this image to .jpg in lowercase, the lightbox is added.

In Contao 4.9.x this was no problem.

Greetings Frank

**Comment by m-vo** [comment]
Duplicate of #2358.

This is already fixed in #2365.

**Comment by Kahmoon** [comment]
@m-vo  Thx. But i still have this issue on a fresh installation!? When is this fix released?

**Comment by m-vo** [comment]
Probably tomorrow.

**Comment by Kahmoon** [comment]
ahh ok, nice. Thanks for the fast response
