### ISSUE TITLE
Don't use a plus symbol as icon for duplicate action

### ISSUE THREAD

**Issue by j-schroeder-schetelig** [contao/contao#241]
**Description**  
The current icon for the 'duplicate element' action is a green plus symbol on white background, which looks too similar to the icon of the 'new element' action, which is a white plus symbol on green background.

I propose to keep the plus for new and give the duplicate action a new distinct and easily recognizable icon, for example something like this:
https://www.iconfinder.com/icons/1608634/clone_icon

For me, the only way to distinguish the actions from another is to remember which action is left and which is right. But almost every time I have to look at the tooltip.

The position of the icon should not be the only main identifyer of its function.
The icon should be chosen such that its action is recognizible on first glance, even if its position may change as is discussed here: contao/core#195

**Comment by bekanntmacher** [comment]
https://github.com/contao/contao/issues/5391

**Comment by leofeyer** [comment]
Closing this in favor of #5391.
