### ISSUE TITLE
Content element and front end module fragments not shown in select options

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2415]
**Affected version(s)**

Contao 4.10.3

**Description**

I can confirm [this report](https://github.com/contao/contao/pull/2360#issuecomment-704910280). Content elements and front end modules implemented as fragments do not show up in the type selection anymore.

e.g.:

```php
// src/Controller/ContentElement/ExampleElementController.php
namespace App\Controller\ContentElement;

use Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController;
use Contao\CoreBundle\ServiceAnnotation\ContentElement;
use Contao\ContentModel;
use Contao\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @ContentElement(category="texts")
 */
class ExampleElementController extends AbstractContentElementController
{
    protected function getResponse(Template $template, ContentModel $model, Request $request): ?Response
    {
        return new Response('Hello World!');
    }
}
```

```php
// src/Controller/FrontendModule/ExampleModuleController.php
namespace App\Controller\FrontendModule;

use Contao\CoreBundle\Controller\FrontendModule\AbstractFrontendModuleController;
use Contao\CoreBundle\ServiceAnnotation\FrontendModule;
use Contao\ModuleModel;
use Contao\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @FrontendModule(category="miscellaneous")
 */
class ExampleModuleController extends AbstractFrontendModuleController
{
    protected function getResponse(Template $template, ModuleModel $model, Request $request): ?Response
    {
        return new Response('Hello World!');
    }
}
```

Switching back to Contao 4.10.2 shows `example_element`/`example_module` as an available option in the respective categories.

**Comment by aschempp** [comment]
does it work in the latest Contao 4.9 release? Because that should be the same implementation…

**Comment by fritzmg** [comment]
Yes, it works in Contao 4.9.8.

**Comment by dmolineus** [comment]
Guess it's caused by https://github.com/contao/contao/commit/f7c15c07e57e6d107e599f2d8f57f2fce9108bcb#diff-a6384623b2493a3d08b3efb4386464e6L103

**Comment by leofeyer** [comment]
Can you test if reverting the changes from #2372 fixes the issue?

**Comment by fritzmg** [comment]
> Can you test if reverting the changes from #2372 fixes the issue?

Yes, that helps.

**Comment by leofeyer** [comment]
@aschempp Did you remove the `$childDefinition->addTag()` call accidentally?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2417 for my suggested fix.

**Comment by Kahmoon** [comment]
Good morning,

is there acutally a workaround until an update will come out? A live installation doesn´t load modules :-( (didn´t recognize it when updating from the dev system).

greetz

**Comment by fritzmg** [comment]
You could downgrade to Contao 4.10.2.

**Comment by Kahmoon** [comment]
hmm thats a bit risky....any idea when this issue probably will be fixed? At 4.10.2 the is a bug with file extensions in uppercase .JPG which also affects my installation a lot ;). Also you cannot change file extension in contao file management. When i do this via ftp...all placements of this images are lost.


Downgrade would be  to enter 4.10.2 manually instead of 4.10.* and update all packages?

**Comment by fritzmg** [comment]
You could also revert the changes from https://github.com/contao/contao/pull/2372, specifically the [change within `RegisterFragmentsPass.php`](https://github.com/contao/contao/pull/2372/files#diff-a6384623b2493a3d08b3efb4386464e6L103).

**Comment by Kahmoon** [comment]
I will try that.

I added the code line in RegisterFragmentsPass.php
`$childDefinition->addTag($tag, $attributes);`

My frontend modules are working again. Thx!
