### ISSUE TITLE
"Entfernen am"-Datum in der Opt-In-Übersicht gültig?

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/contao#2418]
**Affected version(s)**

Contao 4.9.8

**Description**

Abonnenten die sich für einen Newsletter registriert haben werden in der Opt-In-Übersicht "angeblich" in 3 Jahren gelöscht. 

Stimmt das?

![image](https://user-images.githubusercontent.com/1027521/95554038-ccb2f700-0a0f-11eb-8e52-27bcd5573a49.png)

**Comment by Tastaturberuf** [comment]
Ich vermute mittlerweile das nur der Token gelöscht wird. Warum in 3 Jahren?

**Comment by fritzmg** [comment]
> Warum in 3 Jahren?

https://github.com/contao/contao/issues/2309

**Comment by Tastaturberuf** [comment]
Dann sollte das Label angepasst werden in "Entfernen/Verlängern am".

Ich denke jetzt hab ich es verstanden. Danke. 

Ich sehe da noch ein DSGVO-Problem: Es sollte die Möglichkeit geben, den Eintrag zu entfernen, idealerweise wird die E-Mail dann auch aus allen Newslettern entfernt.

**Comment by frontendschlampe** [comment]
Ist es möglich, diese Zeit einstellbar zu machen? Also wann das Token gelöscht wird?

**Comment by leofeyer** [comment]
> Ich sehe da noch ein DSGVO-Problem: Es sollte die Möglichkeit geben, den Eintrag zu entfernen, idealerweise wird die E-Mail dann auch aus allen Newslettern entfernt.

Nicht bestätigte Einträge werden nach 24 Stunden – längstens aber nach 3 Tagen – automatisch gelöscht. Dies hat leider bisher nicht korrekt funktioniert (siehe #2309), daher musst Du die Tabelle einmal manuell korrigieren und alle unbestätigten Token löschen, die bereits älter als 3 Tage sind.

Bestätigte Tokens werden alle 3 Jahre verlängert (gesetzliche Nachweispflicht), wenn der bezogene Datensatz noch existiert, oder eben gelöscht. Beides ist 100% vereinbar mit der DSGVO, daher besteht hier kein Handlungsbedarf.

**Comment by frontendschlampe** [comment]
Ich habe damit begonnen, einen Eintrag in den Docs anzulegen, wo die Speicherzeiten usw. aufgelistet werden. Er ist noch nicht ganz vollständig, aber ich bin dabei. https://github.com/contao/docs/issues/467#issuecomment-709942836

**Comment by Tastaturberuf** [comment]
Hallo Leo,

wenn der Kunde mich auffordert seine Daten unverzüglich zu löschen und dem nicht gesetzliche Hürden entgegenstehen, kann die E-Mail-Adresse in der Tabelle nicht noch bis zu 3 Jahre stehen bleiben, um dann automatisch entfernt zu werden.

Ab Kenntnisnahme des Löschantrags bis zur Löschung darf nur eine angemessene Zeitspanne vergehen. 

Ich denke der Webseitenbetreiber sollte jederzeit die Möglichkeit haben Einträge zu entfernen. Klar kann **ich** das über die Datenbank machen, aber viele andere sicherlich nicht.

**Comment by asaage** [comment]
ist doch alles ein bisschen tricky mit der DSGVO...
Wenn der Kunde mich auffordert seine Daten unverzüglich zu löschen würd' ich persönlich die Token-tabelle gar nicht anrühren. Ich geh ja dann auch nicht durch meine Backup's und lösch dort rückwirkend?!

**Comment by frontendschlampe** [comment]
> kann die E-Mail-Adresse in der Tabelle nicht noch bis zu 3 Jahre stehen bleiben, um dann automatisch entfernt zu werden.

Naja ... das müsste man "anwaltlich" prüfen, denn Deine Nachweispflicht, dass der Kunde sich überhaupt mal registriert hat, bleibt ja trotzdem bestehen und das Token ist der Nachweis dafür.

**Comment by leofeyer** [comment]
@Tastaturberuf Eine gesetzliche Aufbewahrungspflicht hat Vorrang vor dem Löschungsanspruch aus der DSGVO.
