### ISSUE TITLE
Keine Vorschau von WebP Bildern

### ISSUE THREAD

**Issue by Olli** [contao/contao#2422]
**Affected version(s)**

Contao 4.9

**Description**

Ich habe mit Gimp ein webp Image erstellt und dies in den Dateimanager hoch geladen. Es wird keine Vorschau des Bildes und des Zuschnittes erzeugt.
Gehostet ist das Contao bei All-Inkl. Liegt das an Contao oder an den Libs die für die Bildbearbeitung zuständig sind?

**Comment by Olli** [comment]
Und ja ... ich habe es umgestellt, dass es mit Lib-GD läuft. Die Umwandlung der Ausgabebilder im FE von z.B. jpg → webp funktioniert :)

**Comment by ausi** [comment]
Wird ein kaputtes/fehlendes Bild angezeigt, oder versucht Contao erst gar nicht ein Vorschaubild anzuzeigen?

Kannst du bitte testen welchen Wert der `contao.image.valid_extensions` parameter bei dir hat?
```sh
vendor/bin/contao-console debug:container --parameter=contao.image.valid_extensions --format=json
```

**Comment by Olli** [comment]
Das sieht dann so aus 
![grafik](https://user-images.githubusercontent.com/1754/95865435-360b7080-0d56-11eb-908c-db0e9a45e2b8.png)
Contao versucht erst gar nicht das Bild zu bearbeitet. Wenn ich auf 

```
mage.valid_extensions --format=json
{
    "contao.image.valid_extensions": [
        "jpg",
        "jpeg",
        "gif",
        "png",
        "tif",
        "tiff",
        "bmp",
        "svg",
        "svgz",
        "webp"
    ]
}

```
Ich kam dann noch auf die Idee mir mal ein kleiner gemachtes Bild alleine anzuzeigen. Da kommt dann von Contao eine Fehlermeldung:
request.CRITICAL: Uncaught PHP Exception Imagine\Exception\RuntimeException: "Unable to open image /*/files/content/Bilder/*/image3_bearbeitet_pattern.webp" at /*/vendor/imagine/imagine/src/Gd/Imagine.php line 95 {"exception":"[object] (Imagine\\Exception\\RuntimeException(code: 0): Unable to open image /*/files/content/Bilder/*/image3_bearbeitet_pattern.webp at /*/vendor/imagine/imagine/src/Gd/Imagine.php:95)"} []

**Comment by ausi** [comment]
Die Fehlermeldung würde eher darauf hindeuten, dass WEBP in deiner Installation von GD nicht unterstützt wird. Kannst du in deiner phpinfo nachsehen ob WEBP dort tatsächlich aufgelistet wird in der GD-Sektion?

**Comment by Olli** [comment]
Naja ich schrieb ja, dass die Umwandlung der jpg Bilder in WebP im FE funktioniert. Auch in der phpinfo() Ausgabe finde ich ein "enabled" bei WebP.

**Comment by ausi** [comment]
> die Umwandlung der jpg Bilder in WebP im FE funktioniert.

Lade mal bitte ein solches von Contao generiertes WebP-Bild in der Dateiverwaltung hoch, damit wir Probleme mit dem WEBP-Bild von Gimp ausschließen können.

**Comment by Olli** [comment]
Wenn ich "https://*/assets/images/4/image3_bearbeitet-b31b3004.webp" direkt aufrufe bekomme ich obige Fehlermeldung. 
Was meinst du mit "Dateiverwaltung"? Ich habe das in Contao über die Dateiverwaltung hoch geladen. Hier auf Github kann ich keins rein laden weil der Dateityp nicht unterstützt wird.
Ich habe noch einen Test gemacht - eine Umwandlung mit cwebp auf der Konsole. 
Das mit cwebp erzeugte Bild wird im Contao nach dem Upload ein Vorschaubild angezeigt. 
Bei einem Test mit https://bild.online-convert.com/de/umwandeln-in-webp funktionierte das Vorschaubild auch nicht.

**Comment by ausi** [comment]
>  Das mit cwebp erzeugte Bild wird im Contao nach dem Upload ein Vorschaubild angezeigt.

Damit würde ich ausschließen, dass es sich um ein Problem in Contao handelt. Anscheinend kann deine GD-Lib nicht mit allen Arten von WEBP-Bildern umgehen, oder das in Gimp generierte Bild ist fehlerhaft.

**Comment by Olli** [comment]
Ok gut. Es wäre mir zwar lieber gewesen, dass es fixbar wäre aber was solls.

**Comment by Olli** [comment]
By the way ... libgd ist bei All-Inkl auf 2.1.1 von Anfang 2015 ... damit ist das kein Wunder und eher ein Wunder das webp überhaupt läuft.

**Comment by ausi** [comment]
> Es wäre mir zwar lieber gewesen, dass es fixbar wäre

Es ist sicher fixbar. Die Frage ist, an welcher Stelle.

Du könntest mal ein PHP-File mit folgendem Inhalt erstellen:

```php
<?php
var_dump(imagecreatefromwebp(__DIR__.'/pfad/zum/bild.webp'));
```

Damit könntest du eventuell eine genauere Fehlermeldung erhalten.

**Comment by Olli** [comment]
Da bekomme ich nur bool(false)  zurück.

**Comment by ausi** [comment]
Wie sieht’s mit folgendem Code aus?

```php
<?php
error_reporting(-1);
ini_set('display_errors', 'on');
var_dump(imagecreatefromwebp(__DIR__.'/pfad/zum/bild.webp'));
```

**Comment by Olli** [comment]
Das sieht schon "besser" aus
```

Warning: imagecreatefromwebp(): WebP decode: fail to decode input data in /www/htdocs/*/web/test.php on line 4

Warning: imagecreatefromwebp(): '/www/htdocs/*/web/image3_bearbeitet.webp' is not a valid WEBP file in /www/htdocs/*/web/test.php on line 4
```

Ich werde mich da wohl an den Provider wenden müssen.

**Comment by ausi** [comment]
Folgende Zeile könntest du noch testweise hinzufügen:

```php
var_dump(exif_imagetype(__DIR__.'/pfad/zum/bild.webp'));
```

Kommt da `int(18)` raus?

**Comment by Olli** [comment]
Da kommt  int(18)  raus.

**Comment by Olli** [comment]
Nur so der Vollständigkeit halber: nach einem Umzug ist das Thema geklärt. Es lag tatsächlich an einer veralteten libgd Version.
