### ISSUE TITLE
ModuleHtml is not working since Contao 4.9.6

### ISSUE THREAD

**Issue by cboelter** [contao/contao#2424]
**Affected version(s)**

Contao 4.9.6 and higher

**Description**
Since the changes in 4.9.6 to use the ```contao.routing.scope_matcher``` the ModuleHtml is not working.
The ModuleHtml uses return statements inside the compile() function instead of assigning the html to the Template object:

https://github.com/contao/contao/commit/59d455b76fb8d91bcb5a0b4cbabcc24e9f8efe60#diff-48c3a8a044e2f16f1981b99bf39b1793e0ee48f047593ead1b4afbd198ce2a64

The ContentHtml uses the assigning to the Template object:

https://github.com/contao/contao/commit/59d455b76fb8d91bcb5a0b4cbabcc24e9f8efe60#diff-7d54af17e8850b869776f5769b59dc212126d99432e7994fc370d38303ee70ba

If I change the Module to use the Template object it works fine for me.

**Comment by fritzmg** [comment]
> the ModuleHtml is not working

What exactly do you mean?

I just tested the `html` module and could not detect any issues.

> Contao 4.9.6 _and higher_

Did you actually test it in Contao 4.9.**8**?

**Comment by aschempp** [comment]
It won't work if you use a custom template. See https://github.com/contao/contao/pull/2425

**Comment by fritzmg** [comment]
I tested it with a custom template too and it works in Contao 4.9.8.

**Comment by aschempp** [comment]
That might be true. It does not HTML-encode anymore though for sure. Which was wrong to do in the template anyway…
