### ISSUE TITLE
Feature: Event menu for all past and future events

### ISSUE THREAD

**Issue by jankout** [contao/contao#2426]
Unfortunately, the filter function of the **_event menu_** does not work. I've already tried it in the demo version https://demo.contao.org/en/events.html?month=201305 when I used the **_event menu modul_** there - this is on the same page like the frontend module **_event list_**. See also https://michaelbloss.eu/de/dabei-sein/veranstaltungen/alle-vergangenen-veranstaltungen?month=202004

It would be nice to have this logic because I could avoid having an extra page for the filtering.

**Comment by fritzmg** [comment]
Seems to work fine, see https://demo.contao.org/en/events.html?month=201305

You probably did not configure the event list correctly. You need to set the format of the event list accordingly. The event list in the Contao demo is configured to list all events and thus cannot be filtered.

**Comment by jankout** [comment]
But this logic does not work for me. I would like to have **_all past_** event in the event list and the event menu **only** for filtering according to month. In the demo the calendar changes only, the list not at all. I use macOS.

I guess this is a very common case - you have **_all_** past or future events and would like to filter them on the **_same_** page ordered by month. Right? So I could avoid having another page only for the filtering.

If the current logic is right there is a problem: you have the event menu now where the year works as link too. What is with this link if the event list is set for ordered by month? There is no event list for this link and so no output... See https://michaelbloss.eu/de/transparenz/vergangene-besprechungen-nach-monat?month=202010

**Comment by fritzmg** [comment]
> But this logic does not work for me.

Regardless of whether it works for you, it is how it is ;). If you want the event list to be filtered by day, month or year, you need to configure it accordingly.

**Comment by jankout** [comment]
My event list is set up for showing **all** past events and with the event menu I want to show events for chosen month on the same page. But this logic does not work. And again what is with the year link - how does it work in a month filtering?

**Comment by fritzmg** [comment]
> My event list is set for showing **all** past events and with the event menu I want to show events for chosen month on the same page.

That is currently not possible out of the box and would be a new feature.

> And again what is with the year link - how does it work in a month filtering?

What exactly do you mean?

**Comment by jankout** [comment]
See my description above and this webpage. https://michaelbloss.eu/de/transparenz/vergangene-besprechungen-nach-monat?month=202007 and click on the year. Why is there the year link when I cannot use it in the month filtering? This is confusing because it makes expectations that you can filter according to year. But you cannot.

**Comment by fritzmg** [comment]
Yes you can. If you set the **Event list format** for both the _Event list_ and the _Event list menu_ to _Month_, then you can filter by month - and also by year.

**Comment by jankout** [comment]
Yes, I had already done it like this before you saw it. :-) But again I want to have the above solution.

**Comment by fritzmg** [comment]
> But again I want to have the above solution.

May be consult the Contao Community for help.
