### ISSUE TITLE
maintenance mode -> frontend template

### ISSUE THREAD

**Issue by Metis77** [contao/contao#2428]
there should be a template that can be uses as easy as placing it into the /templates folder to style a custom maintenance mode frontend experience.

The current way, the maintenance mode looks just like error.

**Comment by aschempp** [comment]
There is: https://community.contao.org/de/showthread.php?60694-Contao-4-Template-überschreiben

**Comment by Aybee** [comment]
Habe ich auch schon so gemacht, aber sehr kompliziert und aufwendig. Ich wünschte mir auch eine einfachere Möglichkeit eine Wartungsmodusseite zu gestalten.

**Comment by Metis77** [comment]
Ja so machen wir das auch.
Ist aber eher nix für "Anwender", die einfach nur ein Template hinzufügen wollen / können.

Alternativ könnte man in der Meldung irgendwas von "Wartungsmodus" oder "maintenance mode" schreiben.
So wie jetzt wirkt es wie eine Fehlermeldung.

**Comment by fritzmg** [comment]
> Ist aber eher nix für "Anwender", die einfach nur ein Template hinzufügen wollen / können.

But that's all you have to do anyway?

> Habe ich auch schon so gemacht, aber sehr kompliziert und aufwendig. Ich wünschte mir auch eine einfachere Möglichkeit eine Wartungsmodusseite zu gestalten.

What exactly is complicated?

**Comment by Metis77** [comment]
@fritzmg 
Meanwhile I found out that this might be more about handling .html5 vs .twig templates.
A discussion that already takes place on different places.

But to answer your above questions:

1. I cant add twig templates from the contao backend
2. I could not find any offical documentation. Only Google a solution from the contao forum. The same linked here by @aschempp 
3. Other than with .html5 templates, I have to clear cache after each change.

If easily possible and just as workaround until the switch to .twig templates, I think it would help to have a .html5 mainenance mode template. So any "user" can just add that template from the contao backend.

**Comment by m-vo** [comment]
> I cant add twig templates from the contao backend

You will be able to edit them with Contao 4.11:  #2051


> I could not find any offical documentation.

https://symfony.com/doc/current/bundles/override.html#templates


> Other than with .html5 templates, I have to clear cache after each change.

Yes, you need to purge the twig cache. (The PR from above does this for you btw.)

**Comment by fritzmg** [comment]
After #2051 what's still missing is creating Twig templates from the back end. May be we can provide such a functionality for some known templates? Like the error, maintenance and layout template for example.

**Comment by Aybee** [comment]
> What exactly is complicated?

The tutorial thread at the forum has 47 posts up til now.

I've manually placed this files into templates:
ROOT/templates/bundles/ContaoCoreBundle/Error/layout.html.twig
ROOT/templates/bundles/ContaoCoreBundle/Error/maintenance-readme.txt

Content of maintenance-readme.txt
```
Language files:
  _c4_taxiboot.online/contao/languages/de/exeption.php
  _c4_taxiboot.online/contao/languages/en/exeption.php

Used lang vars:
  layout.html.twig:
    matter, howToFix, more, hint

  service_unavailable.html.twig:
    unavailable, maintenance
```

And those into the config folder:
ROOT/contao/languages/de/exception.xlf
ROOT/contao/languages/en/exception.xlf

Additionaly I use a patch for editing twig templates within the BE.

I think this is complicated. I'd wish an option in BE for directly edit the lang vars:
`matter, howToFix, more, hint, unavailable and maintenance`
So I wont need to create a template at all.

**Comment by fritzmg** [comment]
Not sure why you do it this way. Create `templates/bundles/ContaoCoreBundle/Error/service_unavailable.html.twig` and fill it with the HTML content you like.

**Comment by Aybee** [comment]
Ok, thank you. I'll try it the next time.
