### ISSUE TITLE
Formularversand geht nicht bei 1&1 IONOS

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao#243]
Wenn ich unter Contao 4.6.11 versuche ein Kontaktformular per SMTP zu versenden, funktioniert dieses leider nicht. Die E-Mails kommen leider nicht an im 1&1 IONOS Postfach, wenn mann das Kontaktformular abschickt.
Dafür habe ich extra eine E-Mail-Adresse passend zu Webseitendomaine mit contao@xxx.com angelegt (wobei xxx für den richtigen Domainennamen steht, der anderes ist).
In die parameters.yml habe ich folgende Daten rein geschrieben:

mailer_transport: smtp
mailer_host: smtp.ionos.de
mailer_user: contao@xxx.com
mailer_password: xxxxxx
mailer_port: 465
mailer_encryption: ssl

Contao Cache habe ich gelehrt über den Contao-Manager und zusätzlich übers Contao-Backend.
Kann mir da jemand einen Tip geben, wie das Problem zu lösen ist? Soll diese Problem eventl. erst mit Contao 4.7 gelöst werden.
Gibt es was besonderes zu beachten im Contao Backend? Richtige E-Mail-Adresse, Versenden per SMTP ist im Backendend eingetragen.

**Comment by fritzmg** [comment]
Poste das im Community Forum, da hier vermutlich kein grundsätzlicher Fehler in Contao vorliegt.
