### ISSUE TITLE
New Field in tl_news fail Forwarding Destination is changed

### ISSUE THREAD

**Issue by skipman** [contao/contao#2435]
**Affected version(s)**

Contao 4.9.x

**Description**

If a new field is added to the news using the PaletteManipulator, it disappears in the backend as soon as the forwarding destination is changed. 
However, the database field exists and can also be edited manually in the database. Only in the backend is the newly created field no longer visible and editable.

If you do not change the forwarding destination, the new field remains visible and editable in the backend.

Configuration:
Contao 4.9.8
PHP 7.4.11

Installed Extensions:
codefog/contao-news_categories (v 3.2.1)
erdmannfreunde/euf_grid (v 3.1.0)
erdmannfreunde/euf_nutshell (v 1.1.4)
erdmannfreunde/theme-toolbox (v 1.0.0)

Code in ROOT/contao/dca/tl_news.php:
```php
<?php

/* HTML in News Überschriften bzw. Titel erlauben */
$GLOBALS['TL_DCA']['tl_news']['fields']['headline']['eval']['preserveTags'] = true;

/**
 * Append field 'firstname' in table tl_news
 */
// contao/dca/tl_news.php
use Contao\CoreBundle\DataContainer\PaletteManipulator;

$GLOBALS['TL_DCA']['tl_news']['fields']['firstname'] = [
    'label' => ['Vorname', 'Geben Sie hier den Vornamen des Mitglieds ein.'],
    'inputType' => 'text',
    'eval' => ['tl_class' => 'w50', 'maxlength' => 255],
    'sql' => ['type' => 'string', 'length' => 255, 'default' => ''],
];

PaletteManipulator::create()
		// Füge das Feld "firstname" nach der "headline" ein
    ->addField('firstname', 'headline', PaletteManipulator::POSITION_AFTER)
    ->applyToPalette('default', 'tl_news')
;
```

**Comment by m-vo** [comment]
These are different palettes. You need to apply it to all of them.

**Comment by skipman** [comment]
Hi m-vo,

thanks for your answer. Which palette should the other be? I just want to add a field in tl_news!

**Comment by m-vo** [comment]
If you want it to be present in all palettes, you need to add `->applyToPalette()` calls for every palette. 

You are only changing the `default` palette in your code, so you most likely want to add `internal`, `external`, `article` as well.
