### ISSUE TITLE
Use HTTPS for schema.org URLs

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#2436]
**Affected version(s)**
Contao 4.9.7

**Description**
Es gibt ja so einige Templates mit der Angabe für die strukturierten Daten z.B. http://schema.org/BreadcrumbList im Template mod_breadcrumb

Sollte es nicht eher https://schema.org/BreadcrumbList etc. heißen?

**Comment by ausi** [comment]
Both versions should be fine according to the schema.org FAQs: <https://schema.org/docs/faq.html#19>

I think we should change this to HTTPS in Contao 4.11.
