### ISSUE TITLE
Missing class in mod_subscribe

### ISSUE THREAD

**Issue by Pellinger** [contao/contao#2437]
**Affected version(s)**

Contao 4.9

**Description**

The p class for e.a. _Dieses Token wurde bereits verwendet_ is empty. Should be p class="error". Unfortunally this isn't reproducible in the demo because of the missing demo-confirmation-setting.

**Comment by bezin** [comment]
I think it might have happened, when the [Opt-In Service was applied to the Newsletter-Bundle ](https://github.com/contao/contao/pull/196/commits/9298552ae2fd91933a7beee3de1e45b1ffa2255d#diff-73c0ed5feed47732561824c245cea11e203798c3a55ec0f9b87f22fb5fe4fa18L174-R177). 

There the template variable was renamed from `mclass` to `type`, but the `mod_newsletter` template still uses `mclass`, [as is the ModuleSubscribe itself](https://github.com/contao/contao/blob/master/newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php#L275).

**Comment by ausi** [comment]
I think you are right, this was merged in https://github.com/contao/contao/commit/a2c33e53982bfc81d051bb5320cc14196f3842fb#diff-73c0ed5feed47732561824c245cea11e203798c3a55ec0f9b87f22fb5fe4fa18R176
