### ISSUE TITLE
Cannot select files in subfolder

### ISSUE THREAD

**Issue by tpk109** [contao/contao#2439]
**Affected version(s)**

Contao 4.10

I upgraded from 3.1. In files I have a structure:

files/top_folder/css
files/top_folder/pdf

top_folder is set public.

Pdfs in articles and external css files selected in the template are not showing in 4.10 anymore. If I try to select them a new it does not work. I can select them, but they don't show after the file picker closes.

If I move the files to

files/top_folder/css.css or ...pdf.pdf I can pick and save them.

Pictures located in 

files/top_folder/css are displayed on the page though.

**Comment by leofeyer** [comment]
Did you synchronize the file system with the DB after the upgrade?
