### ISSUE TITLE
Folder URL - Alias erzeugt Loop

### ISSUE THREAD

**Issue by ideefixx** [contao/contao#244]
Contao Version 4.4.31
PHP Version 7.2.12
Composer 1.9-dev

Der Alias "layout/overview" erzeugt bei der Verwendung von Ordner URLs einen Loop des Alias.
Der Link wird in der Navigation korrekt generiert und lautet dementsprechend "https://example.com/layout/overview.html".

Beim Aufruf der URL wird jedoch auf die folgende URL umgeleitet "https://example.com/layout/overview/overview/overview.html", welche in diesem Fall natürlich nicht existiert.

Die Weiterleitung zur Ordner-URL funktioniert wie erwartet sobald der Alias bspw. "layout/x-overview" lautet. Link & Aufruf entsprechend "https://example.com/layout/x-overview.html".

**Comment by fritzmg** [comment]
Hast du das in einer frischen Contao Installation mit default .htaccess getestet?

**Comment by ideefixx** [comment]
Ja, Neue Installation

**Comment by ideefixx** [comment]
Bei Contao Version 4.4.30 tritt das selbe phänomen auf

**Comment by leofeyer** [comment]
Ich kann das Problem nicht reproduzieren. Bitte versuch mal einen anderen Browser.

**Comment by ideefixx** [comment]
Das Phänomen tritt in jedem Browser auf. Mir ist dabei aufgefallen, dass es nur auftritt wenn die übergeordnete Seite eine interne Weiterleitung ist.

**Comment by fritzmg** [comment]
Beschreibe deine Seitenstruktur genauer oder stelle einen Datenbank Dump zur Verfügung.

**Comment by ideefixx** [comment]
[tl_page.zip](https://github.com/contao/contao/files/2699065/tl_page.zip)

**Comment by ideefixx** [comment]
ACHTUNG:
Ggf. ist dieser Bug als obsolet zu betrachten.
Ich habe soeben ein Update auf Contao Version 4.4.32 durchgeführt.
In dieser Version ist der Loop nicht aufgetreten.
