### ISSUE TITLE
contao:migrate with a ".env" file = no connection?

### ISSUE THREAD

**Issue by ngdot** [contao/contao#2440]
**Affected version(s)**
Contao 4.9

**Description**
If I use `php vendor/bin/contao-console contao:migrate` via cmd in a managed 4.9.8 version – which establishes a connection via a **.env** file, I get the following error:

```
12:51:36 ERROR     [console] Error thrown while running command "contao:migrate". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory" ["exception" => Doctrine\DBAL\Exception\ConnectionException^ { …},"command" => "contao:migrate","message" => "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory"]

In AbstractMySQLDriver.php line 112:

  An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir
  ectory


In Exception.php line 18:

  SQLSTATE[HY000] [2002] No such file or directory


In PDOConnection.php line 37:

  SQLSTATE[HY000] [2002] No such file or directory
```

Content of the **.env** file:

```
DATABASE_URL="mysql://${DB_USR}:${DB_USRPW}@localhost:3306/${DB_DB}"
```

**Comment by aschempp** [comment]
are you using the latest version of Contao 4.9? And this is not related to the Contao Manager, right?

**Comment by ngdot** [comment]
I'm under 4.9.8. I don't know if it's related to the manager - normal actions works fine with manager, the manager always points to the installtool after installing or removing any extension and don't use the contao:migrate command.

**Comment by ngdot** [comment]
**Addition:** 
Other commands like: `vendor/bin/contao-console cache:clear --no-warmup` are working.

**Comment by m-vo** [comment]
You might want to check if adding a `--env=prod` / `--env=dev` makes a difference.

**Comment by ngdot** [comment]
Nope, same error for both options.

**Comment by aschempp** [comment]
the most likely issue is that you already have an env variable set, therefore the file is not loaded. This should be fixed in the latest Contao version though (there must be a ticket somewhere in here on that).

**Comment by ausi** [comment]
#2208 this one?

**Comment by ngdot** [comment]
The problem is also present in 4.9.9.

**Comment by aschempp** [comment]
I don't think this is a bug in Contao, its rather a problem of your setup. Somehow Contao can't connect to the database on the command line. Either because the configuration is missing (something is overriding it), because the PHP CLI is not compatible (e.g. no PDO_MYSQL support) or because something is blocked (e.g. CLI cannot connect to MySQL server). Not sure how we can help you here 😞

**Comment by ngdot** [comment]
Okay, finally I fixed my problem. 
To get a working database connection via CLI you have to check if the unix_socket is reachable & connectable, the default path from symfony is `/tmp/mysql.sock`. I noticed a difference between the connection via `localhost` or `127.0.0.1`. In my case the CLI database connection only worked with `127.0.0.1`. Also, it's not possible to connect through environment variables in a `.env` file via CLI (frontend connection still works). You have to use the raw data (user, password & databasename) for a working CLI database connection. If I use `localhost` instead of `127.0.0.1` I got also the problem which I posted in #2481 – so fixed 2 of my problems now :) Maybe this information helps someone else!

**Comment by fritzmg** [comment]
> Also, it's not possible to connect through environment variables in a .env file via CLI (frontend connection still works).

What do you mean by that? It should not matter.

**Comment by ngdot** [comment]
CLI doesn't get fastcgi_params as far as I know now!
Means, if I want to read out the fastcgi_param `$ {DB_USR}` from my nginx config into my .env file, it does not work and also doesn't make much sence. So it was a miss configuration from my side.
