### ISSUE TITLE
Current events not visible on front-end

### ISSUE THREAD

**Issue by sietsevandreven** [contao/contao#2448]
**Affected version(s)**
Contao 4.4 to Contao 4.9 (what we know of).

**Description**
The eventlist module has an option to hide ongoing events. But ongoing events are not showing on the front-end when this option is unchecked.

So if an event is set on e.g. today (21-10-2020), it's not visible on the front end.

The settings of the events are:
Startdate = set
Enddate = not set
Time = not set
Location = set
Repetitive event = not checked

**Comment by asaage** [comment]
How do you reproduce that? works fine in the demo.
Did you make sure your eventlist is configured correctly (like all upcoming events in event list format)?

**Comment by sietsevandreven** [comment]
This is the module configuration:

**List of events format**
format: + 1 month

**Short format**
not checked

**Sort order**
Ascending

**Events reader module**
none selected

**Number of events**
0

**Results per page**
10

**Ignore URL parameters**
not checked

Hide ongoing events
not checked (so this should work)
