### ISSUE TITLE
Eventlist module wrong css class.

### ISSUE THREAD

**Issue by tsarma** [contao/contao#2449]
**Affected version(s)**

Contao 4.9

**Description**

The event list module has the wrong css class for the list items. When you choose for a list template `event_list`or `event_teaser`, all list items has the class `even first last`. This is reproducible on the online demo by changing the event_list template.
But it works as expected if you choose the template `event_upcomming`.

**Comment by fritzmg** [comment]
The CSS class depends on the grouping, iirc. i.e. if it is the first or last event on that day for example. There aren't multiple events on the same day in the demo.

**Comment by tsarma** [comment]
Ah, that explains.
