### ISSUE TITLE
Add backend link to the contao manager

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#245]
As initially provided as a [pull request](https://github.com/contao/contao/issues/26), adding a link to the contao manager would increase the UX for users of the contao manager.

The pull request got merge but the changes were removed again. Ticket is created to discuss if the feature will be added to Contao.

**Comment by Paddy0174** [comment]
I'd love to see this, but how to set this up, so only allowed people can see it?  

I'm with you, that it would help, to push the CM forward. 

But I'm with Leo, that the CM and BE are two different things, that should not be mixed.

Maybe it would be doable, if we could "synchronize" the logins for the CM and the BE. If the same user/pw combination exists in both && the BE user is Admin, then the link is shown. But maybe I'm too far here, and make things to complicated. 

All in all I'd say, I'm 60/40 for adding the link.

**Comment by leofeyer** [comment]
As discussed in Mumble on December 20th, we can add the link in a compiler path. Also we want to open the link in the same tab.

I will adjust the reverted changes accordingly.

**Comment by leofeyer** [comment]
Implemented in 559f3cf9984e1abdeb1971d6a9b802b8258fdb61. Thank you @dmolineus.
