### ISSUE TITLE
The sitemap.xml currently contains "noindex" pages - Google complains about it.

### ISSUE THREAD

**Issue by markusmilkereit** [contao/contao#2450]
Valid for Contao 4.9: 

I know that the page setting "sitemap" was detached from the logic for the sitemap.xml generation. We found one issue with that now, when Google Webmaster Tools was complaining about a page:
* that we have in the sitemap.xml
* that is marked with "noindex"

The Google complaint is in vulgo: "If we should not index, why did you submit. This is wrong". Some SEO tools are also marking this as wrong, some even *critically* wrong, because youre delivering broken pages to an external indexer which (aparently) leads some indexers to have limited trust in the technical structure of your whole website (example description [here](https://sitebulb.com/hints/xml-sitemaps/noindex-url-in-xml-sitemaps/)).

As far as I can see the broken behaviour is in `Backend::findSearchablePages` line 679, especially this part (`$blnIsXmlSitemap` is `true` on sitemap.xml generation):
```PHP
// Searchable and not protected
(!$blnIsXmlSitemap || $objPage->robots != 'noindex,nofollow')
```

The logically correct version would be:
* if it's noindex we don't put it in the sitemap
* we don't care about the follow/nofollow, has nothing to do with sitemap logic

I would accompany that with a slight change in the description of the robots field, and explain that noindex also means no sitemap.xml. 

The fix is simple enough, I just did not want to waste time prepping a pull request if there is a reason for the current handling. I just replaced the faulty part from above with:
```PHP
(strpos($objPage->robots, 'noindex') === false)
```

**Comment by fritzmg** [comment]
See the discussion in https://github.com/contao/contao/issues/501 - it was decided to only remove pages from the sitemap, if it has `noindex,nofollow`.

**Comment by markusmilkereit** [comment]
I did not see the discussion there before - but I strongly encourage to pick it up again. "nofollow" (as also discussed there) is mostly used wrong, so the correct setting in many of those cases should be "noindex,follow". And the articles linked above are just a small sample talking about that, as well as how wrong it is to send a "noindex" page to any search engine, not just Google.

Should I switch over to 501?

**Comment by markusmilkereit** [comment]
I could also fix this with an extension, but I would really prefer the Contao core to behave "correctly" - worth the extended discussion in my opinion :)

**Comment by ausi** [comment]
> The Google complaint is in vulgo: "If we should not index, why did you submit. This is wrong".

This would be news to our discussion, in https://github.com/contao/contao/issues/501#issuecomment-544850079 it was stated that google does not characterize this as an error.

Can you please post a screenshot of the error message from Google?

**Comment by markusmilkereit** [comment]
Sure I can - and it currently only is one, because we closed the other cases:
![image](https://user-images.githubusercontent.com/676671/96841788-8072a880-144c-11eb-84b3-b5b28c602a90.png)

Like I said: if you read SEO-articles about it (serious ones, not stupid hypetrain-screamers) you will find a lot more notes on how sitemap.xml should handle it (and many why noindex,nofollow is being used wrongly in many cases).
The Sitebulb article above explains why the "noindex in sitemap" error actually got the critical level in their tool :)

**Comment by ausi** [comment]
> The Sitebulb article above explains why the "noindex in sitemap" error actually got the critical level in their tool

Their first sentence:

> Your XML Sitemap should only contain URLs you wish for search engines to index.

Which is wrong, see [sitemaps.org](https://www.sitemaps.org/):

> Sitemaps are an easy way for webmasters to inform search engines about pages on their sites that are available for crawling.

The difference between crawling and indexing is also referred to ins some Google support articles, e.g.: <https://support.google.com/webmasters/answer/93710?hl=en>

> (and many why noindex,nofollow is being used wrongly in many cases)

Can you elaborate on that? Why would be setting `noindex,nofollow` wrong in your use case? And how should Google find your `noindex,follow` page (to follow the links on the page) if it is missing in the sitemap?

***

Anyway, as this issue still comes up and Google marks it as an “Error” me might give in and also remove `noindex,follow` from the sitemap.xml, even though it is incorrect.

**Comment by markusmilkereit** [comment]
> Which is wrong, see [sitemaps.org](https://www.sitemaps.org/):
> 
> > Sitemaps are an easy way for webmasters to inform search engines about pages on their sites that are available for crawling.

If you deliver a page to a search engine for crawling - actively deliver (as part of a sitemap), it's with the implicit *look at this, this page is important for me and should be crawled*.

That command only makes sense, if the page **should also be indexed** - because just sending it there to be followed is a fruitless exercise - all your other, really important pages are also in the sitemap :)

That's why sending a noindex page to a search engine is wrong - because the logic does not add up.


> > (and many why noindex,nofollow is being used wrongly in many cases)
> 
> Can you elaborate on that? Why would be setting `noindex,nofollow` wrong in your use case? And how should Google find your `noindex,follow` page (to follow the links on the page) if it is missing in the sitemap?

I you have a really nicely done setup, almost the same logic that Contao applies internally should also be used for sitemap generation. Probably the most prominent example: a **news overview page** (list, archive etc.) should not be searched or indexed, but definitely followed. But it should not be in the `sitemap.xml`, because all your (valuable) news detail pages already are.

The `noindex,follow` on the page directly also has an important function: if Google stumbles upon your news overview not through the sitemap, but through regular, "wild" crawling in the web, it now knows how to handle it: don't index the page, but please follow all the links.

In a setup like this the internal Contao logic, the sitemap.xml and the external crawl/index logic all work in harmony ;)

**Comment by ausi** [comment]
> If you deliver a page to a search engine for crawling - actively deliver (as part of a sitemap), it's with the implicit _look at this, this page is important for me and should be crawled_.
> 
> That command only makes sense, if the page **should also be indexed** - because just sending it there to be followed is a fruitless exercise

Why would it be fruitless sending the page to the search engine so that it is able to follow the links on this page? Crawling is not the same as indexing.

For example: A `noindex,follow` page (that is not linked anywhere in the “wild”) has links on in that should get indexed (but are not in the sitemap because different domain). How should the search engine ever find these links?

> I you have a really nicely done setup, almost the same logic that Contao applies internally should also be used for sitemap generation. Probably the most prominent example: a **news overview page** (list, archive etc.) should not be searched or indexed, but definitely followed. But it should not be in the `sitemap.xml`, because all your (valuable) news detail pages already are.

Why does the news overview page in your example needs to be followed if all the linked pages are in the sitemap anyhow?

**Comment by markusmilkereit** [comment]
> Why does the news overview page in your example needs to be followed if all the linked pages are in the sitemap anyhow?

Because there is an important difference (like crawling and indexing) if the robots-meta tag is a standalone information, for a search engine stumbling upon the page that has it. Or if you do the curated, edited submission of your website as a whole in form of a sitemap.xml.

The sitemaps.xml protocol also states, that your sitemaps.xml file should only include links to your own domain - external links are not your responsibility. That would fall into the hands of the other website / domain manager - who should submit their own sitemap. There is an extra section about cross domain content in sitemaps [here](https://www.sitemaps.org/protocol.html#sitemaps_cross_submits) which explains that this is not the recommended way to do things. So your scenario:

> For example: A noindex,follow page (that is not linked anywhere in the “wild”) has links on in that should get indexed (but are not in the sitemap because different domain). How should the search engine ever find these links?

should not be an important factor in generating the sitemap.

I read through the ticket 501 completely, and sometimes the purely technical definition of indexing and crawling is overshadowing the real world application & logic aspects. I know that crawling and indexing is not the same - but there is implicit and explicit logic included when you submit a `noindex` page via sitemap.xml - which results in an error message on Google WMT and many other sitemap.xml check systems.

**Comment by m-vo** [comment]
Doing the wrong thing just that some validation tools are happy doesn't make any sense to me.

Imo before giving in on a bug in a Google tool we should ping someone of the Google dev rel team, kindly ask if this is a valid bug and then act accordingly.

**Comment by markusmilkereit** [comment]
The validation tools are not doing it for the fun of it. Like I said: Sitebulb has a nice explanation also, that the internal structural logic of the behaviour is wrong - they don't mark it as wrong, they mark it in the highest priority as **critically wrong**. And from a logic / SEO point: I agree - hence this discussion :)

**Comment by ausi** [comment]
> The validation tools are not doing it for the fun of it. Like I said: Sitebulb has a nice explanation also, that the internal structural logic of the behaviour is wrong

There is no explanation on the linked article, it just says that the sitemap is for __indexing__ which is exactly the point where I disagree because the sitemap standard itself explicitly says it is for __crawling__.

But Google seems to think it is for indexing and that’s the only reason all SEO tools think the same. If Google changes its opinion SEO tools will follow.

As stated in https://github.com/contao/contao/issues/2450#issuecomment-714329992 I think we should give in and follow what the search engine monopoly thinks about what sitemaps are for.

**Comment by markusmilkereit** [comment]
What would be a nice next step? Should I do a pull request, referencing the ticket? I know it's a tiny change, but I'm trying to be more active again, so: baby steps ;)

**Comment by ausi** [comment]
First we need consensus among @contao/developers I think.

**Comment by markusmilkereit** [comment]
@ausi I saw in a couple discussions that the developers have a sometimes very tech/specs heavy view, if I can add some domain knowledge or user insight I'd be happy to come along. I don't know if the dev discussions also have a project stakeholder, that role is vital in my opinion ;)

**Comment by leofeyer** [comment]
As discussed in Mumble on October 22nd, we all agree that a page that is marked as "noindex,**follow**" should be crawled and therefore should be part of the sitemap.xml file. If Google has a problem with "noindex,follow", then simply use "index,nofollow" if you want to make the tool happy. 🤷🏻‍♂️

**Comment by ausi** [comment]
It looks like Google says that you should set the robots meta tag to `noindex,nofollow`, see <https://www.seroundtable.com/google-long-term-noindex-follow-24990.html>
