### ISSUE TITLE
Contao Installation überprüfen

### ISSUE THREAD

**Issue by akroii** [contao/contao#2451]
In Contao 3.5 gab es das Contao check-Tool womit ich meine Installation überprüfen konnte.

Vlt gibt es ja eine Idee oder Ansatz wie man das ganze auf CLI Basis für Contao  ^4.9 durchführen könnte? Also sowas hier:
`vendor/bin/contao-console contao:check`

oder man fügt neben der Prüfinstanz des Managers noch weitere Prüf-Features hinzu: z.b. also ob er den Ordner `/contao-manager` anlegen konnte usw...

Das Check-Tool hatte folgendes überprüft:

- ~~Check which Contao versions can be installed;~~ -> hierzu gibt es den Manager
- ~~check if PHP is allowed to write files on the server;~~ -> macht der Manager
- ~~check if the Live Update service can be used;~~ -> Obsolete
- ~~check if the Composer package manager can be used;~~ -> Obsolete
- ~~check if the extension repository can be used;~~ -> Obsolete
- ~~install the latest Contao version or Contao LTS version;~~ -> hierzu gibt es den Manager
- validate an existing Contao installation. -> also auch ob die Datein korrupt sind.
- Überprüfe außerdem ob der FTP Benutzer die ausführbare Dateirechte und Schreibrechte besitzt 

Anwendungsfall:
Ich hatte vor kurzem das Problem, dass ich einen FTP Benutzer bekommen hatte, auf dem ich zwar hochladen konnte, aber nachher keine Berechtigung besaß z.b. den Manager auszuführen (sprich den Manager zu installieren).

**Comment by fritzmg** [comment]
Adding a validation like in Contao 3 is not really feasable in my opinion.

Other than that, the Contao Manager already checks for being able to read and write in certain directories.

> Anwendungsfall:
> Ich hatte vor kurzem das Problem, dass ich einen FTP Benutzer bekommen hatte, auf dem ich zwar hochladen konnte, aber nachher keine Berechtigung besaß z.b. den Manager auszuführen (sprich den Manager zu installieren).

If you cannot execute the Contao Manager, then any additional check in the Contao Manager will not help you, will it? ;)
