### ISSUE TITLE
Contao 4.9 FAQ Link 

### ISSUE THREAD

**Issue by toteph42** [contao/contao#2454]
Contao Contao 4.9?

FAQ link does not work. I tried [Slack ](https://contao.slack.com/archives/CK4J0KNDB/p1602754361479400)and [Forum](https://community.contao.org/de/showthread.php?79164-Contao-4-9-FAQ-Link&p=533438#post533438). Since nobody could  explanation / provide a solution I assume it's bug...

**Comment by Toflar** [comment]
Can you provide a description of the error and a step by step instruction how the problem can be reproduced (ideally on demo.contao.org if possible)?

Don't cross link to the forum or Slack, we're not here to extract the information for you and the information might be gone in the future. Every issue should hold all the information required to understand the bug. Thanks :)

**Comment by toteph42** [comment]
Of course:

**Part #1**
1. Installed Conato FAQ
2. In BE I added a internal link to another FAQ `{{faq_url::2}}`
3. After saving new FAQ the resulting HTML code is `<a href="">hier</a>`

![image](https://user-images.githubusercontent.com/2334583/96994104-7e801680-152c-11eb-8234-3edd6ce86e98.png)
![image (1)](https://user-images.githubusercontent.com/2334583/96994106-7f18ad00-152c-11eb-8cb0-90fe24ae40a5.png)

This is from my point of view a real bug.

**Part #2**
Then I tried to add a circumvention and added as link `javascript:openfaq('index1')`. As soon a I save FAQ, content is completely deleted. Contao doc does not mention where to configure to allow `javascript:` (Checked System setting, but there I can only allowed tags and not tag content - in this case `href=`)

**Comment by asaage** [comment]
I think you will need a **jump-to-page** in your faq-settings configured
and the right module  on that page (don't know yet if its page or reader).


Part2:
not sure what url-field or picker you are using... 
```javascript:openfaq('index1')``` probably won't qualify as valid url in
https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Validator.php#L157
https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/dca/tl_content.php#L453
I'd not recommend that - but you might be able to change your tinymce-template to **allow_script_urls** and add your "url" in code-view if you are using a rte field.

**Comment by toteph42** [comment]
Ok, I understand..
