### ISSUE TITLE
Favicon and Individuelle robots.txt Anweisungen do make it into page html

### ISSUE THREAD

**Issue by gganz** [contao/contao#2457]
Contao 4.10.3, no extensions

selecting a favicon file or entering Individuelle robots.txt-Anweisungen in Website-Einstellungen of Startpunkt einer Webseite have no effect on the generated html code, i.e. they do not appear in the head section.

**Comment by fritzmg** [comment]
They are not supposed to appear in the HTML source. These settings change the content of the following URLs:

* `https://example.com/favicon.ico`
* `https://example.com/robots.txt`
