### ISSUE TITLE
No preview bar on 404 pages

### ISSUE THREAD

**Issue by aschempp** [contao/contao#2460]
**Affected version(s)**

Contao 4.9+

**Description**

Since the preview bar is rendered using javascript, it is no longer possible to preview an unpublished page. This is especially true if the root page is not published, which means the whole domain cannot be previewed.

In the iframe context, previewing a non-published root page meant the preview iframe would load, but the page content would be empty. With the new setup, the preview bar is not added to the page at all.

No idea how/if we can fix this @richardhj

**Comment by richardhj** [comment]
Will it work to allow 404 status codes in the event listener?
https://github.com/contao/contao/blob/a9791371c698b060dd97a1839022d8da67a1dee7/core-bundle/src/EventListener/PreviewToolbarListener.php#L77

**Comment by aschempp** [comment]
we already do that with `$response->isClientError()`. I think it works for 404 pages rendered from Contao, but because the root page is not published, there's never such a page. I only get the Twig 404 error page, and our listener is either too soon or on the wrong event to handle that.

**Comment by richardhj** [comment]
Our listener is on the ResponseEvent. This event is dispatched basically every request, isn't it? 
I can imagine that the request matcher fails. No root page = no front end scope? Haven't checked though.

**Comment by aschempp** [comment]
> No root page = no front end scope?

you're absolutely right about that! 🤔

**Comment by leofeyer** [comment]
As discussed in Mumble on November 19th, we could add a fallback-fallback 404 page which has the same content as the Symfony 404 page but additionally shows the preview bar.

**Comment by aschempp** [comment]
see #2685
