### ISSUE TITLE
Setting alternative web/public dir is inconsistent/fails

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2461]
**Affected version(s)**

Contao 4.9

**Description**

see discussion https://github.com/contao/contao/pull/2183#discussion_r511483927

Contao uses two sources for the configured web/public directory: The config from `extra.symfony-public-dir` / `extra.public-dir` (root `composer.json`) and the config key `contao.web_dir` (`core-bundle`). 

The bundle config defaults to `%kernel.project_dir%/web`. It's used in quite some places (templating, images, combiner, ...). The current composer script handler uses the entry from the root `composer.json` and defaults to `web` (relative path). So you need to keep these things in sync otherwise either one fails.

**Possible solution**

Imo we should only only use the config in our code and its default should be:
1. root `composer.json` &rarr;`extra.public-dir`
1. if it does not exist:  root `composer.json` &rarr;  `extra.symfony-public-dir`
1. if it does not exist: `%kernel.project_dir%/web`

**Comment by leofeyer** [comment]
Does it work in Contao 4.9?

**Comment by m-vo** [comment]
No, same there. Or rather: 4.4 isn't affected from the same problem as nothing is read from the `composer.json` there. I adjusted the initial description.

For reference:
- The config was added in 8f4c7f3ecab905d4f04dee7fbaddb27683eedb73.
- The script handler was adjusted in c1d93b5b3662b6670b4520f61ce6ac27b4441b88.

**Comment by aschempp** [comment]
There are two configurations, because there are two separate environments. Contao does not know about the Composer configuration, and Composer does not know about Contao.

Maybe we should add a compiler pass that sets the `contao.web_dir` similar to https://github.com/symfony/symfony/pull/29533?

**Comment by m-vo** [comment]
:+1: The difference being, that Symfony does not have a dedicated config option, right? (I don't see a compiler pass in the referenced PR, maybe I'm missing sth.) 

We would still need to make sure that you did not overwrite the config *and* use a setting the `composer.json`. Also we must only use the config in our code. Correct?

**Comment by leofeyer** [comment]
As discussed in Mumble on November 19th, we want to set `contao.web_dir` from the composer.json configuration, following the Symfony way. If there is no `symfony-web-dir` in the composer.json, we should fall back to `public` in the core-bundle and overwrite this with `web` in the managed-edition (BC).

**Comment by fritzmg** [comment]
For reference, the following parameters can be set in Symfony Flex: https://github.com/symfony/flex/blob/e38520236bdc911c2f219634b485bc328746e980/src/Flex.php#L879-L885

**Comment by m-vo** [comment]
This issue is marked as `feature` against 4.12 whereas https://github.com/contao/contao/issues/2597 as `bug` against 4.9. Can we consolidate these tickets and decide on a strategy (bug vs feature) :smile:?

**Comment by leofeyer** [comment]
As discussed in Mumble on March 11, it should work in Contao 4.9 if you set the web directory in both the composer.json and the app configuration. If this is not the case, we should fix it.

The new feature for Contao 4.12 would be what we have [discussed in the last call](https://github.com/contao/contao/issues/2461#issuecomment-730406371).
