### ISSUE TITLE
No version is shown in backend with composer 2

### ISSUE THREAD

**Issue by Xirdion** [contao/contao#2464]
**Affected version(s)**

Contao 4.4

**Description**

When using Composer 2 with Contao 4.4 you can not see the version of Contao in the backend anymore.
![image](https://user-images.githubusercontent.com/17783055/97289009-edb87c00-1846-11eb-904e-40842e8a5170.png)

**Comment by m-vo** [comment]
Should we drop this feature in 4.4 or also use `package-version-deprecated`?

**Comment by leofeyer** [comment]
I am for using `package-version-deprecated`.

**Comment by leofeyer** [comment]
Turns out it was much easier to adjust the `AddPackagesPass` instead of backporting all the `package-version-deprecated` changes. 🤷🏻‍♂️
