### ISSUE TITLE
Refactor image/picture insert tags

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2466]
We're talking about this:

https://github.com/contao/contao/blob/a9791371c698b060dd97a1839022d8da67a1dee7/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L767-L931

Looks like there is quite some redundant code that could be removed by using the image studio classes. This way we would also normalize the behavior for edge cases.

**Comment by leofeyer** [comment]
Go for it. 👍🏻

**Comment by m-vo** [comment]
After skimming through the code a bit I wonder if we should simply deprecate both insert tags and provide a `figure` insert tag that works similar to the `contao_figure` twig function instead. 

Reason being: BC hell. Also this looks very similar to the old `Controller::addImageToTemplate` stuff it does lots of things in a different way/with a different output. Would be a bigger undertaking to get this to work than I initially expected (silly me :smile:).
