### ISSUE TITLE
Update auf Contao 4.4.31: Event duplizieren und verschieben nicht möglich

### ISSUE THREAD

**Issue by minstyle** [contao/contao#247]
**Affected version(s)**
contao/core-bundle 4.4.31
contao/calendar-bundle 4.4.31

**Description**  
Nach einem Update von Contao 4.4.30 auf Contao 4.4.31 können Redakteure keine Events mehr duplizieren und verschieben.

Ich erhalte dabei folgende Fehlermeldung:

`Not enough permissions to access calendar ID 1234. `

(Bei der ID 1234 handelt es hiebei um die Event-ID.)

Komischerweise ist das Bearbeiten der Eventeinstellungen, editieren, löschen und veröffentlichen/unveröffentlichen allerdings möglich.

Administratoren haben das Problem nicht.

**Comment by jommbee** [comment]
Haben das gleiche Problem mit den News. Nach Update auf  4.4.31 lassen sich durch einen Redakteur News nicht mehr kopieren (verschieben geht). Nachvollziehbar auch in der Contao Demo unter 4.6.11.

**Comment by leofeyer** [comment]
Behoben in 02d9b1b5c360dcc999c56e656b9a107c3a4d8f82.

**Comment by folkfreund** [comment]
Maybe this error was also introduced in 3.5.x? 
I can reproduce the same in Contao 3.5.37

**Comment by jommbee** [comment]
Ja, auch hier ein permission Fehler:
Details: | Not enough permissions to access news archive ID "16"
Funktion: | tl_news::checkPermission

**Comment by leofeyer** [comment]
Fixed in contao/core@28a6741ab1f8e8030bf84ba89b28ad7541dd0808. I'm going to release a new version today.

**Comment by folkfreund** [comment]
Super! Works again in 3.5.38 :-)
Vielen Dank für den schnellen Fix!
