### ISSUE TITLE
Contao Console Command for creating a starter .env file

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#2478]
Regarding:
https://docs.contao.org/dev/reference/commands/
https://docs.contao.org/dev/reference/config/#environment-variables-for-the-contao-managed-edition

It could be helpful to have a Contao-Console command which creates a .env (starter) file with queries/inputs for 
APP_ENV (default: prod), APP_SECRET and DATABASE_URL.

Only if no .env file or config/pararmeters.yml file exists.

One could then automat the installation process on the console (or within a shell script). 
For example like:

- php composer.phar create-project contao/managed-edition . 4.10
- **vendor/bin/contao-console contao:env:create**
- vendor/bin/contao-console doctrine:database:create
- vendor/bin/contao-console contao:migrate
- vendor/bin/contao-console contao:user:create

Of course, you can also create the .env file manually beforehand or create it using a shell script.
But this would unify the approach within the Contao universe

**Comment by m-vo** [comment]
As said before on slack, this most likely would need to be a composer plugin. Commands are part of the application that you want to configure and need the config done beforehand.

**Comment by fkaminski** [comment]
Thank you,
I am afraid that I can contribute nothing in terms of actual implementation. But:

If I create an .env file manually after installing Contao via composer, with the above information it will work. 
(Regarding APP_ENV, APP_SECRET and DATABASE_URL - Just like using the Install-Tool manually afterwards ) 

Hence the naive idea that you could create the .env for Contao automatically afterwards ...

**Comment by leofeyer** [comment]
Does Symfony provide something like this?

**Comment by fkaminski** [comment]
> As said before on slack, this most likely would need to be a composer plugin. Commands are part of the application that you want to configure and need the config done beforehand.

I think I had already understood your comment (hopefully), but then I am confused about possibilities like 
"vendor/bin/contao-console doctrine:database:create 
in this context.

Furthermore: I thought the Install-Tool should be replaced in the future. The Contao Manager should then be able to implement the corresponding approaches(based on contao console commands). These entries will then be be stored in an .env (for example during a new installation)
/ or still in a parameters.yml?!?.

No matter how this will be implemented. 
For the automatic installation via the console I need the above order anyhow.
(Otherwise, as mentioned above, I create the .env with a shell script with the necessary information for a new installation).

**Comment by m-vo** [comment]
> Does Symfony provide something like this?

The only vaguely related thing that comes to my mind is the `dump-env` composer script from the Flex plugin that dumps an optimized `.env.local.php`. 

If it is a docs issue we could also ship a `.env.dist` and put instructions in it.

**Comment by fritzmg** [comment]
This is how it was done in Symfony 3: https://symfony.com/doc/3.3/configuration.html#the-special-parameters-yml-file » https://github.com/Incenteev/ParameterHandler

**Comment by fkaminski** [comment]
When I read this, I have to assume that I have obviously not understood the complexity of the technical implementation of this requirement.

I naively thought that the creation of an .env file (as starting point with APP_ENV, APP_SECRET and DATABASE_URL) would not be that complicated (together with a check if a .env or config/parameters.yml file already exists).

We could therefore write a corresponding manual (ala Automatic Installation via the console) in the documentation with my previous approach:

- composer create-project contao/managed-edition . 4.10
- **Create an .env file with the necessary information manually**
- vendor/bin/contao-console doctrine:database:create
- vendor/bin/contao-console contao:migrate
- vendor/bin/contao-console contao:user:create

Possibly together with an exemplary shell script which, among other things, generates a string for APP_SECRET ala 
```
GetRandomData=$(cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 64 | head -n 1)
# echo $GetRandomData
```

@fritzmg 
If we should include this in the documentary, let me know ...

**Comment by aschempp** [comment]
The Contao Manager would not need that command, there are already other ways (CLI API and `contao-manager.yml` to do that. However, I generally like the idea of a command that asks for the same details as the install tool. Not sure if we can add that to one of the existing or need a new one?
