### ISSUE TITLE
Support for asset-packagist.org

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#248]
Hello,

at the moment we need to have shim repositories for each and every contao component. I guess, it's because of setting

`"type": "contao-component",`

and

`"contao-components/installer": "^1.0.9"`.

Recently I found https://asset-packagist.org . It acts as a bridge between composer and bower/npm. Here we can set the output path as follows (see https://asset-packagist.org/site/about for more info):

```
"installer-paths": {
    "public/assets/{$vendor}/{$name}/": ["type:bower-asset", "type:npm-asset"]
}
```

Do you think, this might be an option for avoiding the creation of contao shim repos in the future?

Bye

**Comment by fritzmg** [comment]
> Recently I found https://asset-packagist.org . It acts as a bridge between composer and bower/npm. Here we can set the output path as follows (see https://asset-packagist.org/site/about for more info):

Nice, didn't know of that yet, thank you ;)

Regarding the contao components: I think you cannot get rid of all of them because some of those assets are modified for Contao.

**Comment by Defcon0** [comment]
OK, that's not a problem. But it would make things a lot easier to have support for this in the standard composer.json of contao so that us bundle developers wouldn't have to create shim repos for contao, as well ;-) Would that be an option?

**Comment by leofeyer** [comment]
> Do you think, this might be an option for avoiding the creation of contao shim repos in the future?

I am not sure. As @fritzmg has already said, the majority of Contao components has been customized, so asset-packagist would most likely not work for them. 

> But it would make things a lot easier to have support for this in the standard composer.json

You are referring to the composer.json file of `contao/managed-edition`, right? We could add the repository there, however, note that the Contao Manager does not use this file anymore.

**Comment by Defcon0** [comment]
> You are referring to the composer.json file of `contao/managed-edition`, right? We could add the repository there, however, note that the Contao Manager does not use this file anymore.

Yes, this is the location I referred to. But how does the Manager then work?? I thought, Contao is composer-driven? :-(

**Comment by leofeyer** [comment]
As discussed in Mumble on Januar 17th, we do not want to use asset-packagist.org, because we do not see a use-case at the moment. Maybe one day when the service has grown and more projects have adopted it, we will adopt it, too.
