### ISSUE TITLE
.env database connection with mariadb / database queries are not removed from installtool

### ISSUE THREAD

**Issue by ngdot** [contao/contao#2481]
**Affected version(s)**
4.4 and 4.9

**Description**
If I use a .env file for a database connection via mariadb 10.3 like this: 
`DATABASE_URL="mysql://${DB_USR}:${DB_USRPW}@localhost:3306/${DB_DB}`

I will get a bunch of of database queries in my installtool with "Alter Table..." that are already done, like mentioned in this issue (#979). My password does not contain a `%`.

```
…
ALTER TABLE tl_remember_me CHANGE expires expires DATETIME DEFAULT NULL
ALTER TABLE tl_trusted_device CHANGE device_family device_family VARCHAR(255) DEFAULT NULL
ALTER TABLE tl_trusted_device CHANGE os_family os_family VARCHAR(255) DEFAULT NULL
ALTER TABLE tl_trusted_device CHANGE ua_family ua_family VARCHAR(255) DEFAULT NULL
ALTER TABLE tl_trusted_device CHANGE userId userId INT DEFAULT NULL
…
```

Adding this to my `config.yml` makes no change.
```
doctrine:
    dbal:
        server_version: 'mariadb-10.3.22'
```

If I add the mariadb version to my connection liks this, the problem is gone!
`DATABASE_URL="mysql://${DB_USR}:${DB_USRPW}@localhost:3306/${DB_DB}?serverVersion=mariadb-10.3.22"`

I don't know if this a real "bug" or just a missmatch of any server requirements?

Server informations:
`PHP 7.4.11`
`mysql  Ver 15.1 Distrib 10.3.22-MariaDB`

**Comment by aschempp** [comment]
what if you don't add the `server_version`? it should be automatically detected if not present.

**Comment by ngdot** [comment]
That's exactly my problem! If I remove the `serverVersion` parameter from my .env the problem is present, the version is **not** autodetected.

**Comment by ngdot** [comment]
see https://github.com/contao/contao/issues/2440#issuecomment-727241828. If I use `127.0.0.1` instead of `localhost` I don't have to use the `serverVersion` parameter.

**Comment by de-es** [comment]
FTR: Auf meinem Arch (aktuell: MariaDB 10.5.6, PHP 7.4.12) funktionierte die Autoerkennung auch noch nie. Ob `127.0.0.1` oder `localhost` macht keinen Unterschied, aber die Parameterübergabe führt hier zum Ziel.
