### ISSUE TITLE
Remove or restrict editing templates in the backend

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2482]
**Affected version(s)**

\>= Contao 4.9 (all versions with Symfony 4 / default template path `/templates`)

**Description**

We're currently allowing backend users to alter things inside the `templates` directory. This leads to a tricky problem because for some operations we would need to rebuild the container. 

If a user wants to overwrite a bundle template in Sf4 they put it under `templates/bundles/<Bundle>/<template>`. This folder is visible in the backend and you can rename or delete it. **But** this will break the application ([ref](https://github.com/contao/contao/pull/2051#issuecomment-719936643)).

**Reproducer**

 - add a  `service_unavailable.html.twig` to `templates/bundles/ContaoCoreBundle/Error`
 - rebuild the cache 
 - open the BE > Templates and rename or delete `ContaoCoreBundle`

**Background**

Here is why: The `TwigExtension` from the `symfony/twig-bundle` adds a method call `NativeFilesystemLoader#addPath` to the container for each found template path at compile time. This does include the ones in `templates/bundles`. `NativeFilesystemLoader#addPath` will throw an exception at runtime if it is given a non-existing path. So, for one: newly created folders won't be picked up as template paths. But worse: if we let the user remove/rename any folder inside `templates/bundles` in the backend the application will immediately crash.

In a dev setup you would just run `cache:clear` and done. In the application rebuilding the container seems impossible:

- It cannot be done at runtime (inside the app) because it'll change classes/paths and will break subsequent execution. It *can* be done to some extent in a very late `kernel.terminate` listener but the request in which this is happening would still need to be made separately (e.g. via ajax) and wouldn't have a way to signal when it has finished. Maybe it could be done with another entry point but that's imo a bit over the top.

- You can switch between `prod` and `dev` in the backend. So we might need to rebuild the cache for both environments, otherwise switching back and forth might be broken. There is imo no way to know the cache location of the 'other' environment, though. Running a command does not work because we do not know the console path. Creating a new Kernel in the respective env and asking it for the directory doesn't work either because we do not know how to instantiate the kernel class. We can only *assume* that it is in `<cacheOfEnvA>/../<cacheOfEnvB>`. 

**Possible solution**

Imo the cleanest solution would be to remove editing templates in the backend and migrate it to the manager. But I know there are lots of people using this functionality for all sorts of things. 

Other than that, I'd disallow editing/deleting any of the affected folders or skip the file operation and add a message that says something like "please remove the folder by hand + rebuild the cache". 

Wdyt? Or am I missing something completely and the problem is easily solveable? :crossed_fingers:  :smiley:

**Comment by aschempp** [comment]
How about decorating the Symfony/Twig service and store the cache somewhere else?

> it cannot be done at runtime (inside the app) because it'll change classes/paths and will break subsequent execution.

doesn't this affect https://github.com/contao/contao/pull/2183 as well?

**Comment by m-vo** [comment]
> How about decorating the Symfony/Twig service and store the cache somewhere else?

What would that solve? The problem isn't caching of the twig files (pool) but caching of the container (model). We could try decorating the `NativeFilesystemLoader` and make it more tolerant against non-existing paths, but this is very fiddly because you would also need to make sure all the other Twig bits that then try to locate and render those missing resources still work. 


> doesn't this affect #2183 as well?

Here each operation runs in a separate process, so the only thing that can possibly be affected is the command that is calling them or rather the things running after it. But if this would be a problem Symfony's `CacheClearCommand` wouldn't work as well.  Maybe its a similar situation, but just much less of a problem on CLI where there are no request based event listeners....

**Comment by aschempp** [comment]
> The TwigExtension from the symfony/twig-bundle adds a method call NativeFilesystemLoader#addPath to the container for each found template path at compile time. This does include the ones in templates/bundles. NativeFilesystemLoader#addPath will throw an exception at runtime if it is given a non-existing path.

We could for example decorate the `FilesystemLoader::addPath` and ignore whatever path does not exist. At the same time we could add new paths in the constructor if necessary.

**Comment by m-vo** [comment]
Thought about decorating as well, but it turned out to be bit harder because the paths are added via a compiler pass.
Nevertheless, there might be a solution, even though a complicated one. 

Closing in favor of #2501
