### ISSUE TITLE
Allowed fields not possible for users with custom permissions

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2484]
**Affected version(s)**

`^4.4`

**Description**

If I choose `custom` af the user permission inheritance I am not able to define the allowed fields (`alexf`). Inf fact a custom can't edit any backend content which has the `exclude` flag. So this option is pretty useless. 

I vote to allow to defiine allowed fields (`alexf`) for users as well or we should deprecate the inherit mode `custom` and remove it at all.

**Comment by aschempp** [comment]
I think the idea is you can configure fields through permissions, but use `custom` to allow specific news archives, page mounts etc.

**Comment by dmolineus** [comment]
You mean it's a readonly access? If I use the `custom` mode no fields are available from groups, so granting access to news archives etc. doesn't make any sense if the user should edit content.

**Comment by fritzmg** [comment]
It cannot be readonly access either, can it? You don't even see the fields then, or do you?

**Comment by frontendschlampe** [comment]
~~In Contao 3.5 the palette with the fields will open and you can choose the ones, you want to have.~~

I'm sorry ... my mistake ... you can edit the tables, not the fields.

**Comment by aschempp** [comment]
sorry I confused this with the `extend` option. `custom` really only makes sense if you have a table/extension that does not use field permissions (e.g. system maintenance)
