### ISSUE TITLE
importantPartHeight & importantPartWidth on svg files wrong after update

### ISSUE THREAD

**Issue by ngdot** [contao/contao#2486]
**Affected version(s)**

Contao 4.9

**Description**

After updating contao 4.4 to 4.9, svg images **without** a width & height attribute doesn't have the same/correct`importantPartHeight` & `importantPartHeight` values like before the update. The new relative image calculation does not work correctly with svg images without a width & height attribute. The important part is so small that the pictures seem to disappear.

**Fix**

Edit the `importantPartHeight` & `importantPartHeight` manually via backend again to the correct area.

**Quote from @ausi :**
 If it has affected many pictures, you can restore the old DB again, downgrade contao/imagine-svg to version 0.2.3 and run the database update again, then you can then update contao/imagine-svg again to the latest version. 
Or you convert them manually, see https://github.com/contao/contao/blob/a9791371c698b060dd97a1839022d8da67a1dee7/installation-bundle/src/Database/Version480Update.php#L155

**Comment by leofeyer** [comment]
Since there is nothing more to do on our side, I am closing this ticket. If you are having the same problem, here is how to fix it:

> Quote from @ausi :
> If it has affected many pictures, you can restore the old DB again, downgrade contao/imagine-svg to version 0.2.3 and run the database update again, then you can then update contao/imagine-svg again to the latest version.
