### ISSUE TITLE
Search results show page title + root page title

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2487]
**Affected version(s)**

Contao 4.9

**Description**

Since Contao 4.9, the search results include the website root title in the title of the result (if configured like that in the page layout, which is the default). After upgrading to Contao 4.9 our customers are complaining that this leads to a lot of superfluous information in the search results.

Before Contao 4.9 the search results might have looked like this:

* Lorem ipsum dolor
* Consectetuer adipiscing elitr
* Nullam quis
* Maecenas tempus
* …

i.e. just the pages' titles, which is expected. Now they look like this:

* Lorem ipsum dolor - Vendor Website Title
* Consectetuer adipiscing elitr - Vendor Website Title
* Nullam quis - Vendor Website Title
* Maecenas tempus - Vendor Website Title
* …

The " - Vendor Website Title" will always be the same for each page, unless you configured the search module to include more than one website root of course (which is not the default).

This happens due to the switch to the crawler, which simply takes an URL's title from the meta data - which in turn is generated (by default) through the insert tag `{{page::pageTitle}} - {{page::rootPageTitle}}`.

I would propose to additionally add `contao:pageTitle` to the JSON-LD, so that this can be stored in the `tl_search` table as before.

**Comment by leofeyer** [comment]
Not sure about that. If you search for `site:contao.org` on Google, it will also show the page title as found in the `<title>` attribute. If that is an issue, you should probably adjust the title tag in the page layout?

**Comment by fritzmg** [comment]
> Not sure about that. If you search for `site:contao.org` on Google, it will also show the page title as found in the `<title>` attribute.

Google does its own thing there too. It will not always be the actual content of the `<title>` meta tag of that page. Disregarding what Google is doing: what benefit do you see from always having ` - Contao Online Demo` for each and every search result: https://demo.contao.org/en/search.html?keywords=the&x=0&y=0 ?

> If that is an issue, you should probably adjust the title tag in the page layout?

Then it will be removed altogether, not just from the search results.

**Comment by leofeyer** [comment]
Yes, but what do you need it for anyway if not for the search results?

**Comment by fritzmg** [comment]
For out-of-context identification of a site, e.g. in the browser's tabs - or in search results together with results from other sites.

Admittedly, the latter can be relevant within the Contao search results too, if you selected multiple website roots with different domains (or at least different root titles) in the search result module.

**Comment by cwittstock** [comment]
This seems to me to be very useful for the Google search results.
But if I look at the local search results - displayed on the site itself - it shows me the title of the page in each link. That looks very ugly.

**Comment by leofeyer** [comment]
As discussed in Mumble on February 11th, we want to add `$GLOBALS['objPage']->pageTitle` to the JSON-LD data and use this instead of the `<title>` content.

We have also discussed adding a general "metadata" field in the next feature release, in which we can store the entire JSON-LD array and/or arbitrary custom fields.

**Comment by Toflar** [comment]
I'm closing this. The PR for a bugfix in 4.9 can be found [here](https://github.com/contao/contao/pull/2737). And I've added a feature request issue for the [custom metadata](https://github.com/contao/contao/issues/2738), so we don't forget about this.
