### ISSUE TITLE
Do not show pretty errors if "text/html" is not accepted

### ISSUE THREAD

**Issue by ghost** [contao/contao#249]
<a href="https://github.com/ausi"><img src="https://avatars3.githubusercontent.com/u/367169?v=4" align="left" width="42" height="42"></img></a> [Comment](https://github.com/contao/contao/issues/194#issuecomment-440354193) by @ausi
November 20th, 2018, 18:14 GMT

> Ggf. nur zu reagieren, wenn als Content-Type `text/html` angefordert wird.

Das wäre grundsätzlich eine gute Idee denke ich (unabhängig von diesem Issue), allerdings lädt der Firefox (evtl. auch andere Browser) das Favicon leider mit `Accept: text/html,…` wodurch der Fehler weiter bestehen bleiben würde.

**Comment by leofeyer** [comment]
It seems we are already checking this: https://github.com/contao/contao/blob/4.4/core-bundle/src/EventListener/PrettyErrorScreenListener.php#L121

**Edit:** As explained by @ausi, the `getFormat()` method checks the `_format` route attribute and not the accept headers.

**Comment by leofeyer** [comment]
Fixed in ec82a9745ad8783799ec563878f4676b24be611e.
