### ISSUE TITLE
Link to Contao Manual (Documentation) within Backend

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#2491]
Maybe it would be helpful to provide a link to the documentation in the Contao backend ...

**Comment by fritzmg** [comment]
There already is a link on the dashboard (for the keyboard shortcuts). However, may be it would be good to overhaul the dashboard in that regards in general?

**Comment by bennyborn** [comment]
> However, may be it would be good to overhaul the dashboard in that regards in general?

+1 from me. We've had quite some projects were we added custom listings to the dashboard by simply overwriting `be_welcome.html5` since there is no way to add more content to it in an update-safe way.

**Comment by ameotoko** [comment]
> There already is a link on the dashboard (for the keyboard shortcuts). However, may be it would be good to overhaul the dashboard in that regards in general?

BTW, this link is broken in https://github.com/contao/contao/blob/7e6bacd4e334bdd1a32996dab12d3b05e1e161cc/core-bundle/src/Resources/contao/languages/en/default.xlf#L1148-L1153

Currently working link is https://docs.contao.org/manual/en/administrationsbereich/keyboard-shortcuts/, but it doesn't look right either, may be **it** should be updated first?

**Comment by fritzmg** [comment]
@ameotoko that's actually an error in the Contao docs which I have now rectified: https://github.com/contao/docs/commit/094febbd58089f2a0e905e15085d54589cd706e3

Thanks for reporting :)

**Comment by leofeyer** [comment]
As discussed in Mumble on December 17th, we want to add a `?` icon in the upper right corner that links to to.contao.org.

**Comment by MDevster** [comment]
@leofeyer should the icon link to support section (https://to.contao.org/support => https://contao.org/de/support.html) or direct to manual (https://to.contao.org/manual => https://docs.contao.org/manual/)?

**Comment by leofeyer** [comment]
Directly to the manual I think.

**Comment by MDevster** [comment]
I would take this

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4123
