### ISSUE TITLE
Can not create articles if no layout suggested

### ISSUE THREAD

**Issue by akroii** [contao/contao#2494]
**Affected version(s)**

4.10.2
Not affected in Contao 4.9.9
Not testet in 4.4

**Description**

I have an existing installation with multi domain pages. After I installed Contao on host and create new root page I can't create new articles. Even I created new pages (normaly articles would created automatically).

In this screen shot I clicked on Button "New" Article in Article List:
![Unbenannt](https://user-images.githubusercontent.com/8830861/99065793-38a4f400-25a8-11eb-9e3f-64e2c4fb63a2.PNG)

PHP 7.4
```

{
    "type": "project",
    "require": {
        "alnv/catalog-manager": "^1.31",
        "bugbuster/contao-botstatistics-bundle": "^1.0",
        "bugbuster/contao-statistic_group-bundle": "^1.0",
        "bugbuster/contao-visitors-bundle": "^1.6",
        "comolo/contao-supertheme": "^3.3",
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "^4.9",
        "fritzmg/contao-lazy-load-element": "^1.0",
        "fritzmg/contao-swiper": "^3.3",
        "inspiredminds/contao-wowjs": "^1.0",
        "jrgregory/m17-sticky-backend-footer": "^2.0",
        "martin-kozianka/contao-timetags": "^1.0",
        "nerdlichter/contao-image-optimizer-bundle": "^1.0",
        "syncgw/contao-spambot": "^1.0",
        "terminal42/contao-inserttags": "^1.9",
        "zmyslny/contao-wrapper_tags": "^2.1"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**ps:
If no layout suggested to a normal page or root page you can not create articles anymore. However it should be possible even without a layout is suggested in tl_page.**

**Comment by fritzmg** [comment]
> 4.10.2

You should always first update your Contao installation, before reporting bugs.

**Comment by akroii** [comment]
I'am sorry... after I've updated to 4.10.4 the problem still exists.

**Comment by asaage** [comment]
I think you need the Article-Module in your Layout.
Then articles will also be automaticaly created again.

**Comment by akroii** [comment]
@asaage it works!
After I added an article-module in layout articles will create automatically when i add a new page.

**Comment by fritzmg** [comment]
> Can not create articles if no layout suggested

What do you mean by that?

**Comment by akroii** [comment]
I've not submitted an layout in root page of any other page

**Comment by fritzmg** [comment]
Not sure what you mean.

In order to be able to create articles in the back end and show articles in the front end, you need to add the article module to your page layout. That page layout needs to be selected in your site structure of course.

**Comment by akroii** [comment]
Of course! Article needs a position in Layout settings - otherwise no articles can be created.
