### ISSUE TITLE
Show error page (404) of fallback language, for not defined language.

### ISSUE THREAD

**Issue by tsarma** [contao/contao#2499]
When your installation is a multilingual and uses a `prepend_locale: true`, then langauge is added to the url. And also say you have defined a page not found for all these roots (let's say, we have roots for `en` and `de`).

Now, if someone access any non available resource on these roots, for example  `mydomain.com/de/junklink` or `mydomain.com/en/junklink`, where `junklink`is non-existing and fictive. Contao shows correct 404 page from respective roots.

But if someone access a page with not defined root for a language, for example `mydomain.com/jp/junklink`. Then Contao shows standard error message `Oops! An Error Occurred`. Here it would be nice to show the error page from the fallback root.

**Comment by leofeyer** [comment]
Which Contao version are you using?

**Comment by tsarma** [comment]
Contao 4.9.9

**Comment by fritzmg** [comment]
> Then Contao shows standard error message `Oops! An Error Occurred`.

What exactly is the error? Use the debug mode to get more information about the error.

**Comment by aschempp** [comment]
> What exactly is the error? Use the debug mode to get more information about the error.

@fritzmg the error is that the fallback 404 page is not shown. There's no further need to analyze, you can easily see it in the demo:
 - https://demo.contao.org/en/foobar
 - https://demo.contao.org/jp/foobar

**Comment by leofeyer** [comment]
That is the expected behavior IMHO. There is no root page for `jp`, therefore the 404 response seems correct.

**Comment by fritzmg** [comment]
Ah, "Oops! An Error Occurred" sounded like another error to me. Just now realised the fallback 404 page shows this and says "something is broken".

Maybe we should change that? I don't think that an URL to a resource that does not exist is akin to "something being broken".

**Comment by leofeyer** [comment]
I agree. However, the default 404 page comes from Symfony so it needs to be changed there.

**Comment by fritzmg** [comment]
Also what would you do in the following setup then: imagine a multi domain and multi language setup:

* `www.example.com/en`
* `www.example.com/de`
* `www.foobar.at/en`
* `www.foobar.at/de`

The domains example.com and foobar.at have a completely different design, layout and different content.

Now if the URL `https://www.foobar.at/jp/foo` is accessed, ideally the 404 page should be in the design and layout of `www.foobar.at`, shouldn't it?

May be we should always show the 404 page of the fallback language in such a case then (if available)? Without a redirect to the fallback language I mean.

**Comment by fritzmg** [comment]
> However, the default 404 page comes from Symfony so it needs to be changed there.

Symfony does not have a 404 page. Symfony 4.4 treats the `PageNotFoundException` like any other HTTP exception and uses the `TwigErrorRenderer` to render the (deprecated) `error.html.twig`, filling in the status code and status text.

**Comment by leofeyer** [comment]
Yes, and the "something is broken" message is in the `error.html.twig` template, so this needs to be adjusted if you want to change the wording.

**Comment by fritzmg** [comment]
Actually, you can create a `templates/bundles/TwigBundle/Exception/error404.html.twig` template, which will automatically be used by Symfony. However that still does not solve the case for multi-domain setups.

**Comment by aschempp** [comment]
I don't see why this would be the expected behavior. If no valid page is found, we should always render the fallback 404 (if available).

**Comment by fritzmg** [comment]
You don't expect to see the design and layout of `www.example.com` if a 404 page is shown there?

**Comment by leofeyer** [comment]
> If no valid page is found, we should always render the fallback 404 (if available).

@fritzmg Is there a fallback 404 page?

**Comment by fritzmg** [comment]
There is a website root for the fallback language. And the 404 page of that website root could be used.

**Comment by aschempp** [comment]
@tsarma can you test if https://github.com/contao/contao/pull/2717 fixes the issue for you?

**Comment by tsarma** [comment]
> @tsarma can you test if #2717 fixes the issue for you?

@aschempp Thanks it works. I've tested it on Contao 4.9.12
