### ISSUE TITLE
Provide a new urldecoded insert tag in Environment.

### ISSUE THREAD

**Issue by tsarma** [contao/contao#2500]
{{env::request}} is good, but not readable for URL with Unicode letters. See the attachment.
![Screenshot](https://user-images.githubusercontent.com/683894/99502592-90af7200-297d-11eb-83b0-0067666532cc.png)

**Comment by ausi** [comment]
This it not easy to fix I think. We would need an insert tag flag that decodes only unicode characters in the url but keeps other encodings like `%3C` for `<` intact.

**Comment by tsarma** [comment]
Oh ok. I didn't think of that. At the moment I'm doing it with a custom insert tag like 
```php
    /*
     * Custom insert Tag for decoded url
     */
    public function decodeUrl($strTag)
    {
        //Decode {{env::request}}
        if ($strTag === 'envDecodedRequest') {
            return urldecode(\Environment::get('indexFreeRequest'));
        }

        return false;
    }
```

**Comment by ausi** [comment]
That would be insecure. With an URL like `%3Cscript%3Ealert%281%29%3B%3C/script%3E` XSS attacks would then be possible.

**Comment by tsarma** [comment]
Yes, you are right.

**Comment by tsarma** [comment]
A not nice but work around:

```php
        //Decode {{env::request}}
        if ($strTag === 'envDecodedRequest') {
            $unsafe = ['%3C'];
            $safe = ['<<i></i>'];
            return urldecode(str_replace($unsafe, $safe, \Environment::get('indexFreeRequest')));
        }
```

This way: It appears the same as in the URL and if you copy&paste it is also the same as in the URL.

**Comment by m-vo** [comment]
You could probably still sneak an XSS vector in with that (think of `onError="..."` and all of these things). :slightly_smiling_face:

**Comment by ausi** [comment]
```php
return urldecode(preg_replace('/%(?=[0-7][0-9a-f])/i', '%25', \Environment::get('indexFreeRequest')));
```

This should work I guess.

**Comment by tsarma** [comment]
@ausi: Yes, it did. But then the text does not appear the same.

In URL is 

`<script>alert%281%29%3B</script>
`

But on the error page is shown as below.
`
%3Cscript%3Ealert%281%29%3B%3C/script%3E
`

**Comment by fritzmg** [comment]
Well what did you expect? `<script>` definitely should not be shown ;)

**Comment by tsarma** [comment]
why not? possible exactly what the person has type wrong should be shown.
