### ISSUE TITLE
Dateiverwaltung - Fehler beim Verschieben von Dateien wenn man sich im selben Knoten befindet

### ISSUE THREAD

**Issue by hh-com** [contao/contao#2503]
**Affected version**

Contao 4.9

**Description**

Beim Verschieben einer Datei kommt eine Fehlermeldung wenn man sich im selben Konten befindet, in dem diese Datei hin soll.

**Beispiel:**
Es soll die Datei /userdata/content/grafik.jpg in das Verzeichnis /demo/ verschoben werden.
Man klickt auf das Verschieben-Icon und wählt (unnötigerweise) den Konten /demo/ aus.
Jetzt werden nur mehr die Inhalte von /demo/ und das Verzeichnis selbst angezeigt.
![image](https://user-images.githubusercontent.com/8200853/99654202-48b24d00-2a5a-11eb-8367-66c3fc1385d2.png)

Will man nun das File in /demo/ ablegen kommt die Fehlermeldung:
![image](https://user-images.githubusercontent.com/8200853/99654460-a3e43f80-2a5a-11eb-9676-1da8133e1f9e.png)

Kommt nur wenn man sich im Konten befindet, in dem diese Datei hin soll.

Wenn man die Konten-Ansicht entfernt oder sich nur eine Ebene darunter befindet, passt alles.

**Comment by leofeyer** [comment]
I can confirm the issue, however, I doubt that we can do much about it. The breadcrumb menu in the file manager works by overwriting `$GLOBALS['TL_DCA']['tl_files']['list']['sorting']['root']`, which is the same as changing the mount point. Therefore anything outside the chosen path is no longer accessible.

@contao/developers /cc

**Comment by aschempp** [comment]
The only "solution" I can think of is to disable the breadcrumb when a file is moved (in clipboard)?

**Comment by leofeyer** [comment]
As discussed in Mumble on December 17th, we want to try to make the breadcrumb independent from `['list']['sorting']['root']`.
