### ISSUE TITLE
File insert tag is removed from content element after reopening in the editor?

### ISSUE THREAD

**Issue by bopsoid** [contao/contao#2513]
**Affected version(s)**

Contao 4.4.54

**Description**

I have an article with a standard text content element. In this text element I use two different insert tags:

{{link_url::Page_ID}} 
and 
{{file::filename.php}}

After saving this content element it works perfectly in the frontend, both insert tags are interpreted correctly, so they were saved to the database correctly.

When I try to edit this content element again, the insert tag {{link_url::Page_ID}} is still there, but the insert tag {{file::filename.php}} has vanished and there is only "filename.php" left. So the insert tag construction that was wrapped around has been removed.

The complete part looks like this before:

`<p><a class="redbutton" href="{{link_url::118}}?id={{file::questhash.php}}">Fragebogen starten</a></p>`

And after reopening:

`<p><a class="redbutton" href="{{link_url::118}}?id=questhash.php">Fragebogen starten</a></p>`

So it seems, that the {{file::filename.php}} insert tag is removed during opening the content for editing. If you don't know this behaviour and just save again after some other changes, your file insert tag is gone and only the text "filename.php" is displayed in the frontend page.

I can't find any settings to allow or disallow special insert tags in the editor like for HTML tags.

Is this a bug or a feature? :-)

Thanks and best regards,
Boris

**Comment by fritzmg** [comment]
Contao automatically converts file paths to file insert tags and vice verca. May be this does not do any distinction there.

**Comment by bopsoid** [comment]
So, more a feature then ... :-)

This only happens in href or src attributes, right? Otherwise the file insert tag would be removed all the time.

Well ... in this special situation this behaviour does not suit my purpose, because I need this tiny little php script to be included that just creates or displays me a defined hash parameter. ;-)

Any workaround? And no, I don't want to code a complete module or anything like for this special situation. ;-) The script behind this is just 5 lines of code or so. 

So, the first time I save it, it works (so the file insert tag seems to be saved somehow). It just disappears when I reopen it for editing. 

I will try to keep that in mind and inform the customer that he NEVER changes this special page. ;-)

Thanks and regards,
Boris

**Comment by m-vo** [comment]
> Any workaround? And no, I don't want to code a complete module or anything like for this special situation. ;-) The script behind this is just 5 lines of code or so.

What about creating an insert tag instead of the php file?

**Comment by bennyborn** [comment]
> Any workaround?

Whenever I encounter some unwanted behaviour within TinyMCE I simply copy the generated markup from the frontend and paste it into a HTML-Element. This way it should be safe even the customer changes something ;)

**Comment by bopsoid** [comment]
Well, this REALLY is a workaround, "quick and dirty". ;-) 

Thanks for the idea, but I think I'll try it the way m-vo recommended. Sounds "cleaner" to me. ;-)

Is there any "How-To" around for Contao 4.4.x? Just found a very old description (Contao 2.6. or so). Or does this still work the same way?

**Comment by m-vo** [comment]
There's a pretty verbose description in the [dev docs](https://docs.contao.org/dev/framework/insert-tags/).

**Comment by bopsoid** [comment]
Thanks! I'll close this issue! :-)
