### ISSUE TITLE
Captcha not displayed in forms

### ISSUE THREAD

**Issue by JLBA** [contao/contao#2530]
**Affected version(s)**

Contao 4.4

**Description**

When adding a captcha widget in form, it's not displayed in FE (display:none). 
In the template code, we find line 19 :  
`  <?php if (!$this->hasErrors()): ?>
`
It works if i change it for : 
`  <?php if ($this->hasErrors()): ?>
`
Thanks.

**Comment by bytehead** [comment]
This is intended to be like this. AFAIK it's the honeypot version of the captcha and only visible when needed.

**Comment by JLBA** [comment]
Thanks Bytehead.
What do you mean by "when needed" ? How does Contao decide if it's needed or not ? Isn't it as simple as I add it because it's needed ?

**Comment by fritzmg** [comment]
> What do you mean by "when needed" ? How does Contao decide if it's needed or not ? Isn't it as simple as I add it because it's needed ?

The captcha field is not displayed by default. It will only be displayed, if a certain hidden field is filled with a value, e.g. when a bot uses the form.

**Comment by JLBA** [comment]
Hi Bytehead.
I don't understand what you mean by "if needed". How Contao detects it's needed ? If i add it, i need it... That's as simple.

**Comment by bytehead** [comment]
You only need it, when a bot fills the form :) Check this, it's based on the same idea/code: https://rocksolidthemes.com/en/contao/plugins/honeypot-antispam

**Comment by JLBA** [comment]
Ok. I understand. 
Thanks to you both.
