### ISSUE TITLE
AbstractContentElementController does not recognize visibility settings

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2533]
**Affected versions**

Contao `^4.6`

**Description**

Legacy content elements are in order to apply the visibility settings (`invisible`, `start`, `stop`). 

https://github.com/contao/contao/blob/7e6bacd4e334bdd1a32996dab12d3b05e1e161cc/core-bundle/src/Resources/contao/elements/ContentElement.php#L245-L248

The new [abstract controller](https://github.com/contao/contao/blob/4.9/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php) doesn't contain the logic nor the [`ContentProxy`](https://github.com/contao/contao/blob/4.9/core-bundle/src/Resources/contao/elements/ContentProxy.php) applies this setting. As a result content elements defined as controllers are always visible.

While discussing the issue on the slack channel the question was raised if the content element should be responsible for it or better be applied from the outside like handling the permission check and the `isElementVisible` hook?

Is the concrete content element (controller) the right place to apply the visibility check or should it be handled by the `Controller::getContentElement()`? If we agree that a content element is responsible for it, a content element might not implement the visibility handling. Otherwise every content element should define the fields in the backend palette.

Depending on the question above this issue could be fixed in the `ContentProxy`, the `AbstractContentElementController` or the `Controller::getContentElement` method.

**Comment by leofeyer** [comment]
As discussed in Mumble on December 17th, we want to solve it as follows:

* add an `isVisible()` method to the `AbstractContentElementController` class;
* move the `getBackendWildcard()` method to the `AbstractFragmentController` class;
* the `addSharedMaxAgeToResponse()` method should be called automatically at the end of the `__invoke()` method in the  `AbstractContentElementController` class.

```php
public function shouldReturnEmptyResponse(): bool
{
	return !$this->isVisible() || !$this->hasAccess();
}

protected function isVisible(): bool
{
	$isInvisible = $this->invisible || ($this->start && $this->start > time()) || ($this->stop && $this->stop <= time());

	// The element is visible, so show it
	if (!$isInvisible)
	{
		return true;
	}

	return $this->isFrontendPreview();
}

protected function isFrontendPreview(): bool
{
	$tokenChecker = System::getContainer()->get('contao.security.token_checker');

	// Preview mode is enabled, so show the element
	if ($tokenChecker->hasBackendUser() && $tokenChecker->isPreviewMode())
	{
		return true;
	}

	$request = System::getContainer()->get('request_stack')->getCurrentRequest();

	// We are in the back end, so show the element
	if ($request && System::getContainer()->get('contao.routing.scope_matcher')->isBackendRequest($request))
	{
		return true;
	}

	return false;
}

protected function hasAccess(): bool
{
	// allowed groups, guests only
}
```

**Comment by Toflar** [comment]
> The AbstractContentElementController needs to figure out if the response already contains cache header (by checking if the Cache-Control exists?), otherwise it should apply addSharedMaxAgeToResponse() automatically.

```php
$response = $this->getResponse($template, $model, $request);

if (!$response->headers->has('Cache-Control') && !$response->headers->has('Expires')) {
    $this->addSharedMaxAgeToResponse($response, $model);
}
```

**Comment by aschempp** [comment]
> move the getBackendWildcard() method to the AbstractFragmentController class;

That would be wrong, as the backend wildcard is specific to modules (linking to edit). Content elements don't have a wildcard by default; if they have one it must be specific to this element.

**Comment by ameotoko** [comment]
> The new [abstract controller](https://github.com/contao/contao/blob/4.9/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php) doesn't contain the logic nor the [`ContentProxy`](https://github.com/contao/contao/blob/4.9/core-bundle/src/Resources/contao/elements/ContentProxy.php) applies this setting.

The `cssID`  setting of the content element is not respected either. Is it a part of the same problem or is it a separate issue?

**Comment by Toflar** [comment]
That's a separate issue but yes, that's not supported.

**Comment by ameotoko** [comment]
> That's a separate issue but yes, that's not supported.

Will it be supported? It doesn't feel right to create multiple copies of a module in back end, just to apply different css classes...

Edit: it is also confusing, that there are fields in the backend, that don't do anything 😁
