### ISSUE TITLE
HTML module, inserttag and JS escaping

### ISSUE THREAD

**Issue by bytehead** [contao/contao#2537]
**Affected version(s)**

Contao 4.9

**Description**

1. Create a HTML module (`<script>` tag allowed) and add following content (makes no sense, but to illustrate the issue):

```html
<script type="text/javascript">
    for (let foo = 1; foo < 5; foo++) {
        // foo
    }
</script>
```

2. Insert that module with an inserttag (in the page layout, e.g. additional head tags): `{{insert_module::ID}}`
3. It will be rendered as following:

```html
<script type="text/javascript">
    for (let foo = 1; foo &lt; 5; foo++) {
        // foo
    }
</script>
```

I didn't find a way to stop Contao replacing `<` with `&lt;`. Is this a known limitation or a bug?

**Comment by asaage** [comment]
in fact it will render the following:

```javascript
&lt;script type="text/javascript">
    for (let foo = 1; foo &lt; 5; foo++) {
        // foo
    }
&lt;/script>
```
That's been the behaviour ever since and it should look perfectly fine in the frontend.
You don't want that to be executed do you?

**Comment by asaage** [comment]
If you need executeable js on a content-element level i suggest to use the file inserttag.
Create your foo-script in Templates like ```foo.js.html5``` and add it with ```{{file::foo.js.html5}}```.

On layout-level you can name the script ```js_foo.js.html5``` and then select/activate it in your layout.

If you want propper display in FE i suggest to use the "Code" element.

If you want your example to be working (like beeing executed) you would probably have to open security holes in your system by allowing the ```<script>``` tag in "Settings->Security settings->Allowed HTML tags" ⬅  **not recommended**

**Comment by bytehead** [comment]
It should be executable, as it is inserted in the `additional head tags` section in the page layout. 
The script tag is explicitly allowed. 
I never use it like this, I just stumbled over an installation which does it use like this and it obviously does not work...

**Comment by asaage** [comment]
🤷🏼‍♂️ not sure what's going on there ```additional head tags```means it's layout-scope so i would go the " **js_** template.html5"-Route or even put the script directly into ```additional head tags``` if it's allowed. (does that work?)
I can't judge if it's a bug or not.

**Comment by bytehead** [comment]
Module 123 would be the HTML module with the javascript stuff:

<img width="490" alt="Bildschirmfoto 2020-12-02 um 21 16 32" src="https://user-images.githubusercontent.com/754921/100926407-b0997680-34e3-11eb-8e02-27dfa0b51e2a.png">

**Comment by leofeyer** [comment]
So the code is encoded correctly when the HTML module is rendered directly but it is not encoded correctly when rendered as insert tag inside another HTML module?

**Comment by bytehead** [comment]
In my example module with the id `123` is the html module with the javascript.

**Comment by bytehead** [comment]
I never tried it when directly rendered. I'll give it a shot.

**Comment by bytehead** [comment]
Directly assigned in the layout:

```html
<!-- TEMPLATE START: vendor/contao/core-bundle/src/Resources/contao/templates/modules/mod_html.html5 -->
<script type="text/javascript">
	for (let foo = 1; foo &lt; 5; foo++) {
		// foo
	}
</script>
<!-- TEMPLATE END: vendor/contao/core-bundle/src/Resources/contao/templates/modules/mod_html.html5 -->
```

Inserted via inserttag:

```html
<!-- TEMPLATE START: vendor/contao/core-bundle/src/Resources/contao/templates/modules/mod_html.html5 -->
<script type="text/javascript">
	for (let foo = 1; foo &lt; 5; foo++) {
		// foo
	}
</script>
<!-- TEMPLATE END: vendor/contao/core-bundle/src/Resources/contao/templates/modules/mod_html.html5 -->
```

The behaviour is the same.

**Comment by bytehead** [comment]
Inserted via inserttag:

```html
<!-- TEMPLATE START: vendor/contao/core-bundle/src/Resources/contao/templates/modules/mod_html.html5 -->
<script type="text/javascript">
	for (let foo = 1; foo &lt; 5; foo++) {
		// foo
	}
</script>
<!-- TEMPLATE END: vendor/contao/core-bundle/src/Resources/contao/templates/modules/mod_html.html5 -->

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
I think this is a known limitation. At least until we change/fix the whole HTML sanitization workflow.

**Comment by bytehead** [comment]
Thanks, I'm fine with that.
