### ISSUE TITLE
Problem with HTML-Tags in caption

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#2539]
**Affected version(s)**

4.10

**Description**

In der Bildbeschreibung können keine HTML-Tags verwendet werden. Das ist in der Bildunterschrift in der Dateiverwaltung so und auch wenn man die Bildunterschrift bei "Metadaten überschreiben" im Artikel nutzt.
Da die _caption_ im Core _allowHTML_ im Core von Contao hinterlegt hat, sollte keine DCA-Anpassung erforderlich sein. Es funktioniert aber auch nicht mit DCA-Anpassung.
Natürlich sind die getesteten HTML-Tags in Contao auch erlaubt.

Ein Gegentest in Contao 4.9 zeigt, dass HTML-Tags ohne DCA-Anpassung sowohl in der Bildunterschrift der Dateiverwaltung als auch in der Bildunterschrift bei "Metadaten überschreiben" möglich sind. 
Natürlich sind die getesteten HTML-Tags in Contao auch erlaubt.

Siehe dazu auch https://community.contao.org/de/showthread.php?79405-Keine-html-tags-in-Bildunterschrift-nach-Update-auf-4-10-4

Getestet wurde in XAMPP mit PHP 7.4 auf Windows 10

**Comment by asaage** [comment]
see:
https://github.com/contao/contao/issues/2197
https://github.com/contao/contao/pull/2199
https://github.com/contao/contao/pull/2527
