### ISSUE TITLE
Über 4000 Einträge im Debug-Modus - Ursache unklar

### ISSUE THREAD

**Issue by tschero** [contao/contao#2546]
**Betroffene Version**

Contao 4.9.9

**Beschreibung**

Bei einer Website mit ca. 250 Nachrichtenteasern auf einer Seite, erscheint im Debug-Modus ca. 4000 Mal folgende Anzeige:

    [2020-12-04 17:59:47] app.DEBUG: Router Symfony\Bundle\FrameworkBundle\Routing\Router was unable to generate route. Reason: 'Route 'contao_frontend' not found': Unable to generate a URL for the named route "contao_frontend" as such route does not exist. [] []

Wo kann man hier mit der Fehlersuche beginnen.
Die kompletten Debug-Infos gerne hier auf Wunsch.

Grüße
MP

**Comment by tschero** [comment]
Hier wird das Thema bereits besprochen:
    https://community.contao.org/de/showthread.php?79645-Fehlermeldung-im-Debug-Modus&p=536236&viewfull=1#post536236

**Comment by fritzmg** [comment]
@tschero im Forum wurde ja die Ursache der schlechten Performance bereits gefunden, inkl. Lösung. Diese Logging Einträge haben damit nichts zu tun (werden ja auch nur in der `dev` Umgebung gelogged).

Unabhängig davon würde es mich aber auch interessieren, was diese Logging Einträge verursacht, da ich das auch in allen Contao Installationen beobachte.

**Comment by tschero** [comment]
@fritzmg 
ja die Anworten habe ich gelesen, vielen Dank auch dafür von mir. Mir geht e auch gerade darum, die Ursache für diese vielen Einträge zu finden.
Auch ein Seitenaufruf von 3 Sekunden ist für eine Standardseite (Text, und ein paar Bilder) zu viel.

Da wollen wir mal schauen ob wir rausbekommen wo die Ursache ist.

**Comment by fritzmg** [comment]
> Auch ein Seitenaufruf von 3 Sekunden ist für eine Standardseite (Text, und ein paar Bilder) zu viel.

Klar, aber das liegt nicht an diesen Loggings.

**Comment by tschero** [comment]
Könnte es sein, dass gem. den Loogings versucht wird, eine View zu erstellen, dafür jedoch noch keine oder nicht genügend Informationen vorhanden sind?
Durch irgendein Ereignis in Symphonie.

Das wäre unsere erste Idee?

**Comment by tschero** [comment]
Weiterhin stehen in der Debug-Spalte - bei einem Seitenaufruf bis zu 20 mal folgende Zeile:

    08:05:06
	doctrine 	UPDATE tl_inserttag_index SET `tstamp`=1607414706 WHERE `id`='451'
08:05:06
	doctrine 	SELECT * FROM tl_inserttag_index WHERE tl_inserttag_index.url = 'https://xyz.xyz.de/ferienwohnungen.html' AND tl_inserttag_index.tag = 'insert_article' AND tl_inserttag_index.params = '14199' AND tl_inserttag_index.flags = '' LIMIT 0,1

Ist es notwendig, dass bei einer einfachen Anzeige mehrere Male ein SELECT * FROM tl_inserttag und ein UPDATE gemacht werden muss?

**Comment by fritzmg** [comment]
Das kommt von der Include Info Extension und hat nichts mit diesem Ticket zu tun. Wende dich bei solchen Fragen an die Contao Community.

**Comment by tschero** [comment]
OK, ich dachte diese Info wäre hier hilfreich um ggf. Fehlersuche betreiben zu können.

**Comment by fritzmg** [comment]
Die Log Einträge sind grundsätzlich normal. Jedes mal wenn eine URL generiert wird, wird der `ChainRouter` von Symfony benutzt, welcher wiederum alle registrierten `Router` durchgeht und versucht die URL jeweils zu generieren. Kann eine Route von einem Router nicht generiert werden, wird vom jeweiligen Router eine Exception geworfen, welche der ChainRouter wiederum logged. In diesem Fall wird einfach beim nächsten Router versucht die URL für die Route zu generieren - bis ein Router gefunden wurde, wo es funktioniert, also wo die Route zum Router passt.

**Comment by tschero** [comment]
Ok vielen Dank für Eure Mühe, 
hat das Performanceeinbusen zur Folge?

**Comment by fritzmg** [comment]
Für den Debug-Modus vielleicht, aber dort ist das ja irrelevant.

**Comment by tschero** [comment]
Vielen Dank für Deine Mühe.

VG
MP
