### ISSUE TITLE
News in the future already available

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#2549]
**Affected version(s)**

4.10.x-dev

**Description**

The news has a date in the future (08.12.2020 16:18) but is already available and the link is already offered in the RSS feed.

https://contao.org/de/news/lass-dich-von-contao-inspirieren.html
https://contao.org/share/news-de.xml
https://community.contao.org/de/showthread.php?79664-Lass-Dich-von-Contao-inspirieren!&p=536361#post536361

**Comment by fritzmg** [comment]
Did you set ~~an "Activate on"~~ a "Show from" date?

**Comment by netzarbeiter** [comment]
![contao](https://user-images.githubusercontent.com/1942550/101471316-739c0c80-3947-11eb-834f-f36fa8f4627b.png)

**Comment by fritzmg** [comment]
If you want the news entry not to be visible in the front end or the RSS Feed until a certain date, you need to set that date in "Show from".

**Comment by netzarbeiter** [comment]
This is a new behaviour in Contao and why should a future news show up in the front end?

**Comment by leofeyer** [comment]
It is not a new behavior. The fields "publish item", "show from" and "show until" control the publication status. The "date" and "time" fields are only meta information and can contain arbitrary data.

**Comment by aschempp** [comment]
This is a new behavior to me too 🤷

**Comment by leofeyer** [comment]
Checkout the `NewsModel` class in Contao 3.5:

https://github.com/contao/core/blob/3.5/system/modules/news/models/NewsModel.php#L189

Same behavior. 🤷🏻‍♂️

**Comment by fritzmg** [comment]
It was always like this, iirc.

**Comment by leofeyer** [comment]
Even in Contao 3.2: https://github.com/contao/core/blob/3.2/system/modules/news/models/NewsModel.php#L187

**Comment by netzarbeiter** [comment]
I just reproduced it in a 3.5, the news will not be published in the front end before the future becomes the present.
And once more, why should a future news show up in the front end?

**Comment by fritzmg** [comment]
> I just reproduced it in a 3.5, the news will not be published in the front end before the future becomes the present.

I just tested it in Contao 3.5.40 and published news which have a date in the future (and no setting for "Show on") will show up immediately in the front end.

> And once more, why should a future news show up in the front end?

This way you are more flexible regarding when news should show up in the front end. Only the _Publish settings_ control when an item is published.

**Comment by netzarbeiter** [comment]
To prevent future data from being accidentally added to the news list, both fields must be filled in. Flexibility kills usability.

**Comment by Total-Reality** [comment]
> To prevent future data from being accidentally added to the news list, both fields must be filled in. Flexibility kills usability.

I can understand your point.

Although it isn't unrealistic to consciously display future news. Certain events are already set in advance, for example, short news could be placed to inform that a world economic forum will take place on February 13th or so. So you could use some news like an event. Or you could use the news as a project list. You enter a date in March 2021; In the frontend you inform that the project will be completed in 03/2021.
Why should Contao prevent it from being visible already now?

You are free to enter your news entry as an event in the backend. You can prevent future events from showing up.
