### ISSUE TITLE
.xlf-Definitionen können nicht mehr mit $GLOBALS['TL_LANG'] überschrieben werden

### ISSUE THREAD

**Issue by srhinow** [contao/contao#255]
**Affected version(s)**
Contao 4.4.32, PHP7.2

**Description**  
Bis Contao 3.5 war es ja so, das man Übersetzungen auch aus den Contao-Core-Modulen wie dem Calendar-Modul z.B. mit:
`$GLOBALS['TL_LANG']['MOD']['calendar'][0] = 'Veranstaltungen';`
überschreiben konnte. Jetzt war mir es nach langem Testen nur  noch möglich, wenn ich die Definitionen nicht in ner modules.php sondern in einer eigenen modules.xlf -Datei überschreibe. 

Ist das ein Bug oder ein Feature?

**How to reproduce** 
 In dem man versucht in einem Modul was nach den zu überschreibenden Modulen geladen wird oder z.B. mit einer Datei unter app/Resources/contao/languages/de/modules.php eine vorhandene Sprachdefinition umzubenennen.

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/core-bundle/issues/740

Will be fixed in Contao 4.7.0.
