### ISSUE TITLE
Unify the response tags for comments

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2552]
Right now, comments are tagged with a different prefix than everything else (`contao.comments.` instead of `contao.db.`). This is technically not necessary, since `tl_comments.source` always refers to a database table and thus we could use the standard prefix.

Original discussion: https://github.com/contao/contao/pull/2551#discussion_r539393797

**Comment by ausi** [comment]
Thinking about that case. To follow our strategy, the comments should only be tagged with it’s own ID like `contao.db.tl_comments.123` and we should remove the current `contao.comments.*.*` tags.

If you create a new comment, the same process as in the DCA should be executed (invalidate all parents).

So if I create a comment on news (ID 123) the tags `tl_news.123`, `tl_news_archive.12`, `tl_news_archive` should get invalidated.

**Comment by leofeyer** [comment]
Should we apply this fix to Contao 4.9 as well?

**Comment by ausi** [comment]
IMO yes.
