### ISSUE TITLE
Wertänderung im load_callback wird nicht gespeichert

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#2557]
Contao 4.8/4.9

Das nachfolgende Problem ist ausführlich im Contao-Forum dokumentiert:
https://community.contao.org/de/showthread.php?79668-Verwendung-von-load_callback-und-save_callback

In einem load_callback will ich ein Feld automatisch mit einem Wert befüllen. Der Wert wird im BE-Formular angezeigt, anschließend aber nicht gespeichert. Dieses Verhalten läßt sich in meinem Bundle https://github.com/Samson1964/contao-kaderlisten-bundle/releases/tag/1.2.1 nachvollziehen.
Nur wenn ich das Feld per Hand befülle (also nicht im Callback), wird der Wert gespeichert.

Ich habe testweise vom load_callback zurückgeben lassen:
```php
return $varValue.'PP';
```

Im BE-Formular erscheint der Wert mit angefügtem "PP". Beim Speichern fehlt "PP" wieder.

Beispiel mit $varValue = 'Test':
Füge ich in meinem DCA zusätzlich noch einen save_callback ein wird bei nur (ohne Manipulation)
```php
return $varValue;
```
nichts gespeichert (statt 'Test'), wenn das Feld vorher von meinem load_callback befüllt wurde.

Mache ich im save_callback stattdessen ein
```php
return $varValue.'PP';
```
wird sowohl $varValue als auch 'PP' gespeichert, also 'TestPP'.

**Comment by aschempp** [comment]
You can try to set `alwaysSave = true` in your `eval` configuration.

**Comment by Samson1964** [comment]
Danke, das war es!

**Comment by fritzmg** [comment]
> You can try to set `alwaysSave = true` in your `eval` configuration.

Seems weird though that you have to do that? Why would the `DC_Table` not save the submitted value in this case?
