### ISSUE TITLE
Open various links in a new window

### ISSUE THREAD

**Issue by skipman** [contao/contao#2559]
Concrete:
The link to the CM in the backend
The link to the install tool or backend in the CM

Would be fine if these links automatically open in a new window.

Thanks!

**Comment by ausi** [comment]
> Would be fine if these links automatically open in a new window.

Why?

The way it is now, you can choose how to open the link. 
With <kbd>cmd</kbd>+click you can open a new window/tab and with a regular click the current window/tab is used.

If we add `target=_blank` the user no longer has the choice, so I’d vote against adding it.

**Comment by leofeyer** [comment]
Ah, I remember the discussion. @ausi is right.

**Comment by fritzmg** [comment]
I agree with @ausi 's notion in principle, but I would also argue that sometimes it is better for the user experience, to set `target="_blank"` on certain links.

**Comment by m-vo** [comment]
> it is better for the user experience

Usually the only reason to do so, is, if omitting it breaks something. E.g. opening the 'terms and conditions' breaks your shop checkout flow. I don't see a reason here.

**Comment by fritzmg** [comment]
When I am browsing via Smartphone I am always annoyed when a link that brought me away from the current web application does not open in a new tab.

**Comment by ausi** [comment]
> When I am browsing via Smartphone I am always annoyed …

You can choose to open links in a new tab on smartphones too.

> > it is better for the user experience
> 
> Usually the only reason to do so, is, if omitting it breaks something.

Agreed. There are cases where this is preferred, mostly in application like websites. That’s why the preview link opens in a new tab. But because I can navigate from the manager to the backend and vice versa it does not make sense in this case I think.

**Comment by fritzmg** [comment]
> You can choose to open links in a new tab on smartphones too.

Yes, but it is way more cumbersome.

**Comment by aschempp** [comment]
As @leo said we have discussed this (and actually removed the new window from the Manager and back end link). I would vote to close this issue.
