### ISSUE TITLE
Unbekannte Option bei Template Auswahl

### ISSUE THREAD

**Issue by jommbee** [contao/contao#2567]
**Affected version(s)**

Contao 4.9.9

**Description**

Beispielszenario:

1. Es gibt für ce_headline ein eigenes Template "ce_headline_test.html" (nur anderer Name, Inhalt gleich)
2. Ich lege ein Element Überschrift an, weise ihm das Template zu und speichere
3. Ich ändere den Elementtyp auf Text
4. Im Dropdown "Inhaltselemente-Template" steht nun "Unbekannte Option"
5. Ich speichere
6.  Im Frontend wird nun folgendes Markup erzeugt:

`<h2 class="ce_text first last"></h2>`

Das führt natürlich zu Fehldarstellungen auf der Website.

![step1](https://user-images.githubusercontent.com/4679889/101898657-c9bdb980-3bac-11eb-9671-3582ca9b4493.png)
![step2](https://user-images.githubusercontent.com/4679889/101898672-ce826d80-3bac-11eb-8f33-08251443f51a.png)

**Comment by fritzmg** [comment]
It's not a bug, it's a feature ;). If you change the element type but not its custom template, then the previously saved custom template option becomes an "Unknown option".

**Comment by Shoekrates** [comment]
Aber sollte der Fallback nicht besser das ce_text.html5 aus dem Core (sofern nicht individuell überschrieben) und nicht „Unbekannte Option” sein? Sonst führt doch die Ausgabe zwangsläufig immer zu unlogischem Markup und damit zu Fehldarstellungen. Siehe oben Headline mit Klasse .ce_text.

**Comment by fritzmg** [comment]
The content element always uses the selected template, if you have selected one. The content element does not know, that the selected template is not the correct one.

**Comment by jommbee** [comment]
Das Inhaltselement weiß das schon, sonst würde es ja nicht auf unbekannte Option wechseln. Das Textelement bietet ja auch nur ce_text_XX.html5 benannte Templates zur Auswahl. Dann macht diese Einschränkung ja auch keinen Sinn mehr.

Wo liegt denn der Sinn darin, einem ce_text das Markup eines ce_headline zu geben? Ich sehe vielleicht gerade nicht was daran ein Feature ist.

**Comment by m-vo** [comment]
@jommbee In general, it's correct that a previously defined option that isn't available (anymore) is reported as 'unknown'.

I agree that changing the CE type should purge the custom template field, though. Keeping it is never useful, isn't it?

Edit: It would break switching back and fourth, though. But I think that's ok.

**Comment by jommbee** [comment]
Dem stimme ich zu. Es darf halt nicht dazu kommen, das fehlerhaftes Markup produziert wird.

**Comment by asaage** [comment]
Kind of related to this one: https://github.com/contao/contao/issues/1859
According to (my) logic an "unknown-option" should just be not save-able.
The difference is just that there is no checkbox to reveal the template-selection.

*and "type" is a submitOnChange field i guess.

**Comment by fritzmg** [comment]
> I agree that changing the CE type should purge the custom template field, though. Keeping it is never useful, isn't it?
> 
> Edit: It would break switching back and fourth, though. But I think that's ok.

Previously that was already the case, sort of. Before introducing the "Unknown option", switching the element would also reset the template selection, once you click "Save", because the select would be reverted to its default state.

**Comment by Shoekrates** [comment]
But why did you change this mechanism? I can't imagine a case where switching a content element type while keeping the individual template would make any sense.
Somehow related: you set as an admin an individual template but your editors aren't allowed to change templates. But the editor can change the type. At the moment this would result in the inital mentioned case with weird markup and the editor couldn't do a thing about it.

**Comment by fritzmg** [comment]
> But why did you change this mechanism?

This wasn't changed specifically. It was just an emergent behaviour of the previous implementation without the new "Unknown option" feature.

**Comment by m-vo** [comment]
Also keep in mind, that this behavior (again in general) is a close call between bug and feature. For the future I hope we can find a way to better define how and if the data should be shared between different types. But this is intertwined with so many things (visibility, permissions, context, ...) + there are technical limitations in the current DCA concept . Not easy to get it right.

**Comment by ausi** [comment]
> you set as an admin an individual template but your editors aren't allowed to change templates. But the editor can change the type. At the moment this would result in the inital mentioned case with weird markup and the editor couldn't do a thing about it.

This was the case ever since I think, unrelated to the “unknown option” feature.

**Comment by aschempp** [comment]
I think we should improve on the _Unknown Option_.
 1. not allow to save a field, so one must handle the option
 2. Show the option value, at least that can give a hint about the unknown option.

**Comment by jommbee** [comment]
Meine Stimme geht an Version 1. Das würde auf einen "Fehler" aufmerksam machen und am ehesten eine "richtige" Auswahl durch den Bearbeiter zur Folge haben.

**Comment by asaage** [comment]
Following use-case should be considered:
A user might be able to change the 'type' of content-element but does not see (has no rights to change) the template-selection at all.
*(ups - that was already mentioned)

**Comment by aschempp** [comment]
> does not see (has no rights to change) the template-selection at all.

If he can't see the field, it would not be validated anyway and shouldn't be a problem.

**Comment by asaage** [comment]
> If he can't see the field, it would not be validated anyway and shouldn't be a problem.

I don't know about the validation but currently there would still be a wrong template in the record and produce nonsense-markup.
Can't we just replace any unknown-templateoption with the appropiate global-or theme-default on the fly?

**Comment by fritzmg** [comment]
@asaage but that's a problem irregardless of this issue, isn't it?

**Comment by asaage** [comment]
Honestly i didn't run into this issue yet.
I just want to evaluate if it's possible to **a)** always produce markup with a sensible template while **b)** still being able to switch content-element-type back and forth without purging the originaly selected template from the record.

**Comment by leofeyer** [comment]
A simple fix would be to reset the template when the element/field/module type changes.
