### ISSUE TITLE
Model getRelated() function can't handle fields with eval options multiple and csv

### ISSUE THREAD

**Issue by ben-eSM** [contao/contao#257]
**Affected version(s)**
any

**Description**  
Since serialized arrays with IDs in the database aren't a recommended solution if you happen to search for set values in some sql statements, storing them as a csv is the better solution. Luckily this can be done easily by adding the eval option csv. Unfortunately the getRelated function for models doesn't handle csv values, resulting in just getting the model of the first value stored in the field.

**How to reproduce**  
Simply define a DCA field where you can set multiple options (e.g. inputType checkbox) and enable the value to be stored as csv by setting the appropriate eval option `csv=>','`. Also set a relation for that field in the DCA.
Now save one item with multiple values selected, load the model of that item and try to retrieve the related models for the above defined field by executing the getRelated function. You will only get the first model instead of every model for each set value.

**Comment by leofeyer** [comment]
Fixed in b8dfbb1f2739b7b48b8e8ccdbdd8c95172e90f25.
