### ISSUE TITLE
Controller::generateFrontendUrl fix domain potentially broken

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2573]
**Affected version(s)**

Contao `^4.10`

**Description**

1. I have a page record fetched from the database `SELECT * FROM tl_page`
2. The page record is passed to `Controller::generateFrontendUrl` with the parameter `blnFixDomain=true`

Since Contao 4.10 the `rootUseSSL` information get lost and a invalid url is generated.

The issue is caused here, because the ssl information is overriden with non existing values:

https://github.com/contao/contao/blob/280339c0529fd52b0963b40caae77bb42b70db0e/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1192-L1196

The method how this information are retrieved has changed between Contao 4.9 and 4.10:

Contao 4.9:
https://github.com/contao/contao/blob/918884ce919f753e8e7fd68c76396bf92cb5703d/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1184-L1190

Contao 4.10:
https://github.com/contao/contao/blob/280339c0529fd52b0963b40caae77bb42b70db0e/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1170-L1177

**Comment by aschempp** [comment]
Are you running 4.10 in legacy mode or not?

**Comment by dmolineus** [comment]
Yes, the project uses the legacy mode.

**Comment by leofeyer** [comment]
How can this be fixed?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2749
