### ISSUE TITLE
News featured toggle results in Internal Server Error 500

### ISSUE THREAD

**Issue by markus361** [contao/contao#2574]
Contao 4.9.10

Trying to toggle the featured option of a news with the star icon in the backend results in a Internal Server Error on the console.

Can be reproduced on the demo (https://demo.contao.org/contao) but the news there gets toggled.

Other versions like 4.9.9 or 4.9.3 seem to work though

**Comment by fritzmg** [comment]
The problem are the newly added `onload_callback` and `onsubmit_callback` in `tl_news::toggleFeatured`. Many event listeners will assume, that their `DataContainer` argument will not be null, including Contao's own event listeners. However, when using this feature, it will indeed be null.

Failure with Contao's own `onsubmit` event listener:

```
TypeError:
Argument 1 passed to tl_news::adjustTime() must be an instance of Contao\DataContainer, null given, called in vendor\contao\contao\news-bundle\src\Resources\contao\dca\tl_news.php on line 1057
```

Failure with `onload` event listener from `terminal42/contao-changelanguage`:

```
TypeError:
Argument 1 passed to Terminal42\ChangeLanguage\EventListener\DataContainer\AbstractChildTableListener::Terminal42\ChangeLanguage\EventListener\DataContainer\{closure}() must be an instance of Contao\DataContainer, null given, called in vendor\contao\contao\news-bundle\src\Resources\contao\dca\tl_news.php on line 993
```

If we want to keep those callbacks, I think we should make sure, that the `DataContainer` is not null.

**Comment by fritzmg** [comment]
This also affects Contao 4.4.55.

// ah, but that's moot now, sorry ;)
