### ISSUE TITLE
Editing metadata of multiple files causes data loss

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#2577]
**Affected version(s)**
- 4.9.10
- maybe also 4.10.x too (didn't test yet)

**Description**
Edit multiple files and do renaming and adding metadata at the same time, the new meta data would not be saved.

**Steps to reproduce**
1. File manager › Edit multiple > Select 2 or more images
2. Available fields > Select all > Continue
3. Rename file name **AND** change caption field
4. Save and close

**Result:**
File would be renamed, but the new meta data (caption) would not be saved.

**Comment by contaoacademy** [comment]
Problem still exists with Contao 4.9.11

**Comment by contaoacademy** [comment]
Problem still exists with Contao 4.9.13

**Comment by contaoacademy** [comment]
Today I noticed the problem in a Contao 4.9.16, I thought this was solved.

**Comment by fritzmg** [comment]
@leofeyer was this accidentally closed? The referenced commit is only for `4.x`.

**Comment by leofeyer** [comment]
It has been fixed in all Contao versions (see #3174).

**Comment by fritzmg** [comment]
Right, I forgot that these changes haven't been integrated into `4.9.16` yet.
