### ISSUE TITLE
Contao\Automator::logRotate prevents monolog log rotate

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2579]
**Affected version(s)**

Contao 4.x

**Description**

The `Contao\Automator::logRotate` rotates all log files in `system/logs`. In fact `system/logs` is a symlink to `var/logs` so it affects all log files generated by monolog. The issue occurs because of the different log file formats. Contao expects a fixed log file name, like `error.log`. The monolog configuration creates a date based error log file `prod-YYYY-MM-DD.log`. The Contao log rotation adds a numeric suffix to the files, which doesn't make any sense for date based files. As the result the the log directory is spamed with date based log files having the suffix `.1`.

This issues does not appear in every Contao project but it depends on the order of log entries and the time when the Contao cron job is called. In our system, it's triggered with a cronjob at `00:00:00` (last run finished at `2020-12-17 00:00:17`).

**Proposed sulition**

The `Contao\Automator::logRotate` has to ignore all files having a date based format.

**Comment by aschempp** [comment]
As far as I know, `Automator::logRotate` is no longer used and only there for BC reasons?

**Comment by dmolineus** [comment]
Ah... you're right. Isotope is the root of evil in this case, see https://github.com/isotope/core/search?q=rotatelogs

**Comment by dmolineus** [comment]
The question is if this method should work as before or be a noop handler which just exists for BC reasons. If it should rotate log files, I think it should be fixed to not rotate date based log files. I reopen the issue for discussions.

**Comment by aschempp** [comment]
I can agree with that. Isotope actually needs that currently or it will fill the log files indefinitely (because it does not yet use Contao 4 services/monolog).

**Comment by leofeyer** [comment]
> If it should rotate log files, I think it should be fixed to not rotate date based log files.

Maybe Isotope should add a check and only enable log rotation if Monolog is not enabled?

**Comment by dmolineus** [comment]
> > If it should rotate log files, I think it should be fixed to not rotate date based log files.
> 
> Maybe Isotope should add a check and only enable log rotation if Monolog is not enabled?

I think it has to be handled inside the `Contao\Automator::rotateLogs` method. This method is here for BC reasons. However the implemented rotation is broken if monolog is enabled.

**Comment by aschempp** [comment]
That check in Isotope would not help, because Monolog only rotates the logs it writes. Isotope uses the Contao 3 file log methods.
