### ISSUE TITLE
Bundle services not loaded when registered in Contao Extension

### ISSUE THREAD

**Issue by codedge** [contao/contao#2585]
**Affected version(s)**

Contao 4.10

**Description**

I created a separate extension `codedge/demo-extension` for Contao Managed Edition 4.10. Inside the extensions `src/ContaoManager/Plugin.php` file I register another bundle, like this:

```php
use League\FlysystemBundle\FlysystemBundle;

public function getBundles(ParserInterface $parser): array
    {
        return [
            BundleConfig::create(FlysystemBundle::class), // Register additional bundle
            BundleConfig::create(GoogleShoppingFeedBundle::class)
                        ->setLoadAfter([
                            ContaoCoreBundle::class,
                            ContaoNewsBundle::class,
                            FlysystemBundle::class,
                        ]),
        ];
    }
```

Now when installing my extension inside Contao Managed Edition via `composer require codedge/demo-extension` and checking the DI container afterwards with `./vendor/bin/contao-console debug:container`, I would assume that the services coming with the additional bundle are auto registered to the DI container.

## Example with Flysystem Bundle

I want to use the [`league/flysystem-bundle`](https://github.com/thephpleague/flysystem-bundle) bundle together with my own bundle. Flysystem bundle registers a single storage service (`default.storage`) - see [basic usage ](https://github.com/thephpleague/flysystem-bundle#basic-usage) - which is not present.

Why does Contao Managed Edition does not register the services from the FlysystemBundle when the bundle is explicitly loaded?

**Comment by fritzmg** [comment]
You probably need to make sure that the `FlysytemBundle` is loaded after the `FrameworkBundle` from Symfony. i.e.:

```php
public function getBundles(ParserInterface $parser): array
{
    return [
        BundleConfig::create(FlysystemBundle::class)
            ->setLoadAfter([
                FrameworkBundle::class,
             ]),
        BundleConfig::create(GoogleShoppingFeedBundle::class)
            ->setLoadAfter([
                ContaoCoreBundle::class,
                ContaoNewsBundle::class,
            ]),
    ];
}
```

**Comment by codedge** [comment]
I tried that but not even then the service is registered. Neither by checking the DI container nor by using the service like 

```php
public function __construct(FilesystemInterface $defaultStorage)
    {
        $this->feedStorage = $defaultStorage;
    }
```

It fails with

```
argument "$defaultStorage" of method "__construct()" references interface "League\Flysystem\FilesystemInterface" but no such service exists
```

of course, as the service does not exist in the container.

**Comment by fritzmg** [comment]
It should work. I just tried the following:

```php
// src/ContaoManager/Plugin.php
namespace App\ContaoManager;

use Contao\ManagerPlugin\Bundle\BundlePluginInterface;
use Contao\ManagerPlugin\Bundle\Config\BundleConfig;
use Contao\ManagerPlugin\Bundle\Parser\ParserInterface;
use League\FlysystemBundle\FlysystemBundle;

class Plugin implements BundlePluginInterface
{
    public function getBundles(ParserInterface $parser)
    {
        return [
            BundleConfig::create(FlysystemBundle::class),
        ];
    }
}
```
```
composer require league/flysystem-bundle
```
```
$ vendor/bin/contao-console debug:container flysystem

Information for Service "flysystem.adapter.lazy.factory"
========================================================

 ---------------- -----------------------------------------
  Option           Value
 ---------------- -----------------------------------------
  Service ID       flysystem.adapter.lazy.factory
  Class            League\FlysystemBundle\Lazy\LazyFactory
  Tags             -
  Public           no
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        no
  Autoconfigured   no
 ---------------- -----------------------------------------
```
Is the code of your bundle publicly available?

**Comment by fritzmg** [comment]
> Flysystem bundle registers a single storage service (`default.storage`) - see [basic usage ](https://github.com/thephpleague/flysystem-bundle#basic-usage) - which is not present.

I think there is the misunderstanding. In a regular Symfony application _Symfony Flex_ creates that configuration by default for your application. In the Contao Managed Edition you have to add that configuration to your `config/config.yaml` yourself - or you use the [`ExtensionPluginInterface`](https://docs.contao.org/dev/framework/manager-plugin/#the-extensionplugininterface) of the Contao Manager Plugin in order to provide a default configuration for the Contao Managed Edition directly via your own bundle.

**Comment by codedge** [comment]
Ah, that is the point. I was expecting that this service is created automatically, like in Symfony. 

As I'd like to use FlysystemBundle inside my own bundle/extension I understand that I need to created the `default.storage` service via the ExtensionPluginInterface.

**Comment by fritzmg** [comment]
> Ah, that is the point. I was expecting that this service is created automatically, like in Symfony.

Well, the flysystem bundle only registers the `flysystem.adapter.lazy.factory` service. That service then registers more services, depending on your configuration.

**Comment by codedge** [comment]
Ok, then I still have a question:
Inside my own bundle can I just provide that configuration in

* the extensions `Resources/config/packages/flysystem.yaml` file
* another file inside the extension
* or do I need to provide that config inside the Contao Managed Edition `config/config.yaml`?

As the FlysystemBundle is only used inside the extension I'd like to make sure everything can be configured/registered etc. inside the extension and not inside the main application.

The config I am talking about would be this:

```yaml
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/web'
```

The bundle can be found here: https://github.com/villa-brocante/contao-google-shopping-feed

**Comment by fritzmg** [comment]
As I said, you need to use the `ExtensionPluginInterface`. There are some different examples in the documentation. In your case it would probably look like this:

```php
public function getExtensionConfig($extensionName, array $extensionConfigs, ContainerBuilder $container)
{
    if ('flysystem' !== $extensionName) {
        return $extensionConfigs;
    }

    foreach ($extensionConfigs as &$extensionConfig) {
        if (isset($extensionConfig['storages'])) {
            continue;
        }

        $extensionConfig['storages'] = [
            'default.storage' => [
                'adapter' => 'local',
                'options' => [
                    'directory' => '%kernel.project_dir%/web'
                ],
            ],
        ];
    }

    return $extensionConfigs;
}
```

**Comment by codedge** [comment]
Works like a charm. Thanks a lot!
