### ISSUE TITLE
The "previous login" message shows two different times

### ISSUE THREAD

**Issue by xchs** [contao/contao#259]
**Affected version(s)**

Contao 4.6.12

**Description** 

The note on the back end dashboard regarding the previous login shows two different time specifications:

![be](https://user-images.githubusercontent.com/1218766/50618500-6ff9e280-0ef3-11e9-9276-cfbe1ec27493.png)

**How to reproduce**  

* Set up a new Contao 4.6.12 installation
* Log into the back end and check the message on the dashboard

**Comment by leofeyer** [comment]
I was not able to reproduce this, neither in the online demo nor in my local test environment.

**Comment by xchs** [comment]
That's weird. I can reproduce it in multiple installations on different hosts. Anyone else?

Did you actually test it with Contao 4.6.12? I have only noticed this problem since the update to Contao 4.6.12. The online demo still runs with Contao 4.6.11.

**Comment by Paddy0174** [comment]
+1 
Can reproduce this in two 4.6.12 locally and in two 4.6.12 on uberspace7 (four different installations with different addons).

**Comment by leofeyer** [comment]
> The online demo still runs with Contao 4.6.11.

You are right. I have updated the online demo and now I can reproduce the issue there as well.

**Comment by leofeyer** [comment]
Until a new Contao version is released, I guess this can be fixed with a conflict for `knplabs/knp-time-bundle` in version `>=2.9`.

**Comment by xchs** [comment]
> this can be fixed with a conflict for `knplabs/knp-time-bundle` in version `>=2.9`

I guess you meant the version constraint `>=1.9` of `knplabs/knp-time-bundle`, don't you? Yes, that fixes the issue. 👍

**Comment by leofeyer** [comment]
It seems the issue is already being worked on: https://github.com/KnpLabs/KnpTimeBundle/pull/111

**Comment by fritzmg** [comment]
Current issue: https://github.com/KnpLabs/KnpTimeBundle/issues/112

**Comment by leofeyer** [comment]
I have added a conflict in 5fc3740601837cedde36674ae3abfed53fe619c8.
