### ISSUE TITLE
Search engine: time

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2596]
**Affected version(s)**

Contao 4.9.10

**Description**
FE-module: Search engine
When searching the time is displayed that is used for the search.
Mostly the time is arround 0.0001 seconds. 
![grafik](https://user-images.githubusercontent.com/1645099/103143323-30e27e80-4714-11eb-8e29-c331f128716b.png)

But:
sometimes it is nearly 10 seconds. The displayed time is 8 or 9 seconds. But the real loading time of the page is less than 1 second
![grafik](https://user-images.githubusercontent.com/1645099/103143369-f200f880-4714-11eb-86dc-fde40dcf480b.png)

I guess:
8 or 9 seconds means: 0.00009 seconds but the calculation fails, because it is faster than 4 decimal digits

**Comment by ausi** [comment]
For very small numbers you get something like `8.6069107055664E-5` and contao takes the first 6 characters of that which results in `8.6069`.

We should probably use something like `System::getFormattedNumber($query_endtime - $query_starttime, 3)` here https://github.com/contao/contao/blob/83dec25e43a7e374d73932b2c8452eec3f1c98b4/core-bundle/src/Resources/contao/modules/ModuleSearch.php#L230 and here https://github.com/contao/contao/blob/83dec25e43a7e374d73932b2c8452eec3f1c98b4/core-bundle/src/Resources/contao/modules/ModuleSearch.php#L327
