### ISSUE TITLE
web dir used for symlinks after changing web_dir

### ISSUE THREAD

**Issue by Ruudt** [contao/contao#2597]
**Affected version(s)**

Contao 4.10

**Description**

When I change the web_dir parameter and clear caches (through Contao Manager) the folder `/web` is still used for symlinking. I tracked down the issue to where 'web' is hard coded
https://github.com/contao/contao/blob/8044e70a5ea6bc54cc67869f0bb2cb865ae86d2c/core-bundle/src/Command/SymlinksCommand.php#L94 

If I change that folder name the symlinks work fine.

The same mention of the web folder is also here:
https://github.com/contao/contao/blob/8044e70a5ea6bc54cc67869f0bb2cb865ae86d2c/core-bundle/src/Command/InstallCommand.php#L74

This is related to #2461, where Contao also uses two possibly different definitions for the web folder name.

**Comment by m-vo** [comment]
Yes, #2461 is on my list but waiting for the script handler ticket.

**Comment by leofeyer** [comment]
See https://github.com/contao/contao/issues/2461#issuecomment-796854096
