### ISSUE TITLE
Add backend link to Contao manager

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#26]
It's just a small thing, but for some users it would be a nice addition if the Contao Manager is linked in the Contao backend. The idea is to add a separate link in the system section of the backend navigation which would open the contao manager in a new window. If you like the idea, I'll provide an PR.

Idea how to implement it:

- Provide a config parameter which points to the Contao Manager entrypoint.
- If config parameter is set, the backend link is generated automatically.
- Maybe there could also be an autolookup which scans for typical names like `contao-manager.phar.php` oder `contao-manager.php` and would set the parameter automatically.

I guess it should be part of the manager-bundle instead of the core-bundle, am I right?

**Comment by leofeyer** [comment]
I'm not sure about this, as the manager is not part of the backend. @aschempp /cc

**Comment by aschempp** [comment]
I very much like the idea, I think it was actually proposed before. The Manager is not part of the backend, but it is an integral part of the system. Here's how it should work in my opinion:

1. A menu option in the system setting, only visible to admins (does not need to be configurable in my opinion).
2. A bundle config to specify the path
3. If no path is given, use the bundle extension to check for the default (`web/contao-manager.phar.php`) and if so, write that to config
4. If config is not empty, show the link in the backend

@dmolineus would you create a PR for this?

**Comment by dmolineus** [comment]
Yes, I'll create a PR for it. Your proposal how it should work is the same idea I do have in mind.

> I guess it should be part of the manager-bundle instead of the core-bundle, am I right?

Wdyt?

**Comment by leofeyer** [comment]
Definitely. If you add the core bundle to an existing Symfony installation, the link does not make sense.

**Comment by dmolineus** [comment]
Closed in favour of #46.

**Comment by mlwebworker** [comment]
Im Forum wurde heute über einen Link zum Manager im Backend diskutiert. Einige haben den Link in der 4.7 gesichtet. Wahrscheinlich aber in der dev-Variante. In meinen stable-Versionen 4.7.1 ist keiner. Sollte der dasein oder kommt er doch erst in der 4.8. Hier noch der Link zum Forum https://community.contao.org/de/showthread.php?67084-Hinweise-zum-Contao-Manager&p=498583&viewfull=1#post498583

**Comment by netzarbeiter** [comment]
Bei mir ist der Link in einer 4.7.1 vorhanden.

![manager](https://user-images.githubusercontent.com/1942550/54350470-b4210600-464d-11e9-8b4d-65fbbd8cd6dc.png)

**Comment by mlwebworker** [comment]
Dann werde ich heute mal eine Neuinstallation testen. Die Installationen sind alle Updates einer 4.4 bzw. 4.6

**Comment by mlwebworker** [comment]
Das Problem hat sich erledigt. Es tritt nur deshalb auf, weil ich meinen Contao Manager immer mit cm.phar.php benenne https://community.contao.org/de/showthread.php?67084-Hinweise-zum-Contao-Manager&p=498677&viewfull=1#post498677
