### ISSUE TITLE
Missing Documentation for config.yml and parameters.yml

### ISSUE THREAD

**Issue by biwerr** [contao/contao#260]
The files /app/config/parameters.yml and config.yml are used to set config values but i've found no documentation.

Is there any documentation which options can be set in the contao config files and what they are used for?

**Comment by planepix** [comment]
Just know the - german - entry in Contao Wiki:
http://de.contaowiki.org/Ordner_und_Dateien_in_Contao_4

**Comment by biwerr** [comment]
Yes, this is the only Documentation i've found. But sadly the parameters and default values are missing for the config files.

**Comment by planepix** [comment]
Ok, dann hab ich noch BugBusters Tipps:
https://contao.ninja/tipps-und-tricks-filter-ergebnis.html?af_filter[2][]=26
https://contao.ninja/tipps-und-tricks-filter-ergebnis.html?af_filter[3][]=28

**Comment by fritzmg** [comment]
It used to be in the README of the core-bundle, but now it's gone (though still present in the 4.4 and 4.5 branch).

**Comment by planepix** [comment]
@fritzmg this one? https://docs.contao.org/books/manual/4.4/de/01-installation/contao-installieren.html

**Comment by fritzmg** [comment]
No, this: https://github.com/contao/contao/blob/4.4/core-bundle/README.md

**Comment by leofeyer** [comment]
> which options can be set in the contao config files

```
vendor/bin/contao-console config:dump-reference ContaoCoreBundle
```

>  and what they are used for?

We have tried to name the parameters in a way that you know what they do. Some parameters also haven an additional description.

If you feel like there had to be more descriptions, you can create a pull request and add them [here](https://github.com/contao/contao/blob/master/core-bundle/src/DependencyInjection/Configuration.php).
