### ISSUE TITLE
Install tool failure after update of doctrine/dbal to v2.9.2

### ISSUE THREAD

**Issue by Seefahrer** [contao/contao#261]
Contao 4.6.12

After Updating doctrine/dbal to v2.9.2 invoking the install tool shows fllwg database update to be due:

`DROP INDEX path ON tl_files;
CREATE INDEX path ON tl_files (
  path(768)
);`

Conducting the mentioned DB-Update is not successful, above necessary DB-Update is shown forever.

**Comment by leofeyer** [comment]
See https://github.com/doctrine/dbal/pull/3420

**Comment by leofeyer** [comment]
Doctrine DBAL 2.9.2 has been released, so a `composer update` should fix the problem now.

**Comment by xchs** [comment]
Isn't this fixed with version **2.9.3** only? In any case, the PR was added to the 2.9.3 milestone and meanwhile merged into the master branch.

**Comment by leofeyer** [comment]
Ah, you are right. It will be fixed once Doctrine DBAL 2.9.3 has been released.

**Comment by contaoacademy** [comment]
Ich bekomme leider diesen Fehler bei einem Update von Contao 3.5 auf Contao 4.6
`"An exception occurred while executing 'ALTER TABLE tl_content CHANGE news_filterPreserve news_filterPreserve TINYINT(1) DEFAULT '0' NOT NULL':  SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'news_filterPreserve' at row 1"`

Ich habe extra gerade noch die aktuellste Version von DBAL installiert:

```
Package operations: 0 installs, 1 update, 0 removals
  - Removing doctrine/dbal (v2.9.2)
  - Installing doctrine/dbal (dev-master 0731608): Cloning 0731608045 from cache
```

Oder ist das ein anderes Problem?

**Comment by contaoacademy** [comment]
The error comes from database update of this statements.
All uses "TINYINT(1) DEFAULT '0' NOT NULL"

But this is an extension…


```
ALTER TABLE tl_content CHANGE news_filterPreserve news_filterPreserve TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_content CHANGE news_filterCategories news_filterCategories TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_module CHANGE news_resetCategories news_resetCategories TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_module CHANGE news_filterPreserve news_filterPreserve TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_module CHANGE news_relatedCategories news_relatedCategories TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_module CHANGE news_filterCategories news_filterCategories TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_module CHANGE news_customCategories news_customCategories TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_news_archive CHANGE limitCategories limitCategories TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_news_category CHANGE excludeInRelated excludeInRelated TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_news_category CHANGE hideInReader hideInReader TINYINT(1) DEFAULT '0' NOT NULL
ALTER TABLE tl_news_category CHANGE hideInList hideInList TINYINT(1) DEFAULT '0' NOT NULL

```

**Comment by leofeyer** [comment]
I have added a conflict in bc2f9aef7305b2a066c369d7f0e8fd28b879298d.
