### ISSUE TITLE
Fehler im Hook "GetFrontendModule" wenn ein Modul vom ModulTyp "Formular" per inserttag eingebunden wird

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#2613]
**Affected version(s)**

Contao 4.9 (maybe 4.10)

**Description**

Fehler im Hook "GetFrontendModule" wenn ein Modul vom ModulTyp "Formular" per inserttag ( {{insert_module::XX}} ) in ein z.B. HTML-Module eingebunden wird! Hier ist der dritte Parameter dann vom Typ Contao\Form und nicht Contao\Module!
Siehe Fehlermeldungen!

`
TypeError: Argument 3 passed to ...\HooksListener::onGetFrontendModule() must be an instance of Contao\Module, instance of Contao\Form given, called in .../vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php on line 426
  at vendor/alpdesk/alpdesk-frontendediting/src/Listener/HooksListener.php:252
  at Alpdesk\AlpdeskFrontendediting\Listener\HooksListener->onGetFrontendModule(object(ModuleModel), '<div class="mod_form block">    <form action="suchergebnisse.htm" method="get" enctype="application/x-www-form-urlencoded">    <div class="formbody">                  <div class="widget widget-text">          <input type="text" name="keywords" id="ctrl_15" class="text" value=""></div>    </div>  </form></div>', object(Form))
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:426)
`

HTML-Element-Module in einem div: 
{{insert_module::XX}}

Module XX ist ein normales Modul vom ModulTyp "Formular"

**Comment by fritzmg** [comment]
As discussed on Slack, this is an error in the documentation. It was fixed for the `getContentElement` hook, (see https://github.com/contao/docs/issues/189), but not for the `getFrontendModule` hook.

Fixed in https://github.com/contao/docs/commit/dee958649127d69aecb7428ac4818ec6f1f49e5d
