### ISSUE TITLE
page layout: analytics templates

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2616]
(I am not sure if it is a bug or improvement or feature request)

**Affected version(s)**

Contao 4.9

**Description**
page layout, chapter "JavaScript"

![grafik](https://user-images.githubusercontent.com/1645099/103414520-97d1be80-4b7e-11eb-9d9d-d5d94fa73aa8.png)

If no settings in the templates are done: There is just "Matomo" or "Google Analytics" written.

I would suggest to add any information like: "Motomo (please edit template analytics_matomo)"

When the template is edited, the label changed from "Matomo" to the template name "analytics_matomo"
![grafik](https://user-images.githubusercontent.com/1645099/103414644-0dd62580-4b7f-11eb-9b02-71ae54b6a353.png)

That is in my opinion nice and clear. 
But in my opinion it does not make sense that the name changed from "Matomo" to the template name "analytics_matomo"

**Comment by math-GH** [comment]
when the template ist edited, than the order is not clear anymore ("Google" before "analytics"?)

The JavaScript templates before are also very technical descripted ("js_.....")

![grafik](https://user-images.githubusercontent.com/1645099/103415097-fac45500-4b80-11eb-96ad-753029ad2aaf.png)

**Comment by fritzmg** [comment]
The template names are normal. As such this is probably a feature request. But what feature are you requesting?

**Comment by math-GH** [comment]
> I would suggest to add any information like: "Motomo (please edit template analytics_matomo)"

**Comment by leofeyer** [comment]
I agree that we should show the template names here.
