### ISSUE TITLE
Maker bundle

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2618]
I'd like to create some [maker-bundle](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html)-like tooling in the future that helps me speed up the creation of custom content elements and other common things. Sf has a really good DX with flex + the `make:*` commands that imo Contao is currently lacking.

Similarly, we could for instance have a `make:content-element` that would spit out fragment controllers, dca and language files, templates and so on. The whole thing should imo be opinionated and adhere to best practices and therefore can make practical assumptions about the application structure/position of files and so on.

This is probably better suited as a 3rd-party bundle and I know there were other efforts made in this direction before but I couldn't find something that looks actively developed. Is there anyone out there that has something started or wants to chime in? :slightly_smiling_face: Maybe we can use this as a starting point for a discussion.

**Comment by aschempp** [comment]
@sheeep is/was working on something like that

**Comment by bytehead** [comment]
Here's @sheeep's work: https://github.com/1up-lab/contao-maker-bundle 🙃

**Comment by bytehead** [comment]
It's actually planned to be ready for 4.11 😬

**Comment by m-vo** [comment]
:heart: Super cool!

**Comment by bytehead** [comment]
Feel free to test and provide some feedback 👍

**Comment by markocupic** [comment]
> I'd like to create some [maker-bundle](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html)-like tooling in the future that helps me speed up the creation of custom content elements and other common things. Sf has a really good DX with flex + the `make:*` commands that imo Contao is currently lacking.
> 
> Similarly, we could for instance have a `make:content-element` that would spit out fragment controllers, dca and language files, templates and so on. The whole thing should imo be opinionated and adhere to best practices and therefore can make practical assumptions about the application structure/position of files and so on.
> 
> This is probably better suited as a 3rd-party bundle and I know there were other efforts made in this direction before but I couldn't find something that looks actively developed. Is there anyone out there that has something started or wants to chime in? 🙂 Maybe we can use this as a starting point for a discussion.

**Comment by markocupic** [comment]
> I'd like to create some [maker-bundle](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html)-like tooling in the future that helps me speed up the creation of custom content elements and other common things. Sf has a really good DX with flex + the `make:*` commands that imo Contao is currently lacking.
> 
> Similarly, we could for instance have a `make:content-element` that would spit out fragment controllers, dca and language files, templates and so on. The whole thing should imo be opinionated and adhere to best practices and therefore can make practical assumptions about the application structure/position of files and so on.
> 
> This is probably better suited as a 3rd-party bundle and I know there were other efforts made in this direction before but I couldn't find something that looks actively developed. Is there anyone out there that has something started or wants to chime in? 🙂 Maybe we can use this as a starting point for a discussion.

With https://github.com/markocupic/contao-bundle-creator-bundle I went a different approach. I generate my modules, content elements, controllers from the contao backend.

**Comment by aschempp** [comment]
> It's actually planned to be ready for 4.11 😬

Did that work out? 😅

**Comment by bytehead** [comment]
Not really. Availability of free time you know 😅

**Comment by leofeyer** [comment]
See #3615.
