### ISSUE TITLE
Ajax-Request "new Request.Contao ..." liefert Status 303

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#2619]
**Affected version(s)**

Contao 4.9 (maybe later version)

**Description**

Der Ajax-Request "new Request.Contao ..." "landet" im "onFailure"-Callback mit einem 303 status trotz "followRedirects = false".

Anwendungsfall: Wenn man beispielweise aus einem eigenen JS ein CE sichbar/unsichtbar stellen möchte und passend im Callback reagieren möchte.

(Eventuell steckt auch ein Anwendungsfehler dahinter :-))

```js
new Request.Contao({
      'url': '/contao',
      followRedirects: false,
      onSuccess: function (responseJSON, responseText) {
        // not called
      },
      onError: function (text, error) {
        // not called
      },
      onFailure: function (f) {
        // always called
      }
    }).get({'do': 'article', 'table': 'tl_content', 'id': myid, 'cid': mycid, 'state': mystate, 'rt': myrt});
```

**Comment by aschempp** [comment]
Kannst du erklären was du genau machen willst?

**Comment by xprojects-de** [comment]
Geht um ein FrontendEditing wo man auf ein eigens erstelltes "Augen-Symbol" eines ContentElement klicken kann um das Element sichtbar/unsichtbar zu schalten. Das Icon hat ein Click-Event und in diesem wird der Request abgeschickt. 

Über die callbacks des Requests wird dann das FrontendView reloaded.

Klar könnte man eine eigene BackendRoute für diesen Fall erzeugen aber sollte es nicht auch auf diese Weise gehen?

**Comment by fritzmg** [comment]
XMLHttpRequests always follow redirects as far as I know, I don't think you can disable that? Also I don't really understand the problem.

**Comment by xprojects-de** [comment]
Jip ist klar und das passt ja denke ich auch. 
Aber ich lande halt immer im onFailure-Callback wenn ich die Toggle-Visible- oder die Delete-URL aufrufe, auch wenn ich followRedirects: true setzte! Das macht keinen Unterschied. 

Wenn es so gewollt ist passt das für mich. Es funktioniert ja auch alles nur dachte ich halt dass es ein onSuccess ein sollte :-)

**Comment by xprojects-de** [comment]
... wegen mir kann der Request geschlossen werden! 👍

**Comment by ausi** [comment]
We should probably execute the check from https://github.com/contao/contao/blob/8f91578a8ff1025227ea05e35c2b42584dcbbc0b/core-bundle/src/Resources/public/mootao.js#L45-L51 in a `failure` handler too if the status code is `>= 300 < 400`.

**Comment by leofeyer** [comment]
@xprojects-de Can you please check if #2689 fixes your issue?

**Comment by xprojects-de** [comment]
Tested with contao version 4.9.x-dev and error still exists! Is that the correct Contao-Version?

**Comment by leofeyer** [comment]
The changes have not yet been merged. Please copy them manually to your `mootao.min.js` file.

**Comment by xprojects-de** [comment]
hmm... if setting followRedirects: false there is the same behaviour like before!

Looking at the code i have to set followRedirects: true. 
Doing that, the rediect is working BUT the main-window-location reloads!! (also logical because location.href!)

Doing the same request with Typescript/Angular the redirect is done in the Javascript-Async-context and i get a success-Callback with Code 200 and the main-window-location does NOT reload! I still get the HTML-Response in the response of the Ajax-Call!
I would expect the same with the contao request or i´m wrong!?!?

Currently i use the Typscript-HttpClient so it´s no longer a problem for that the behaviour is different! :-)
