### ISSUE TITLE
Add HTTPS only flag to root page

### ISSUE THREAD

**Issue by aschempp** [contao/contao#262]
Once https://github.com/contao/contao/pull/95 is implemented, we can add a feature to only allow https URLs. This can be added in `RouteProvider` on every call to `new Route(…)`. We might need to add HTTP redirects in this case.

**Comment by leofeyer** [comment]
As discussed in Mumble on January 17th, we want to allow only HTTPS URLs if the checkbox is enabled and redirect HTTP requests.

**Comment by aschempp** [comment]
Closing in favor of https://github.com/contao/contao/pull/283
