### ISSUE TITLE
Side-effects in FormSelectMenu::generate()

### ISSUE THREAD

**Issue by bezin** [contao/contao#2622]
Hello,

while working with Haste Forms and Contao Widgets (in this case `FormSelectMenu` with `multiple: true`) I experienced the following:

~Firstly:~ When you call the `generate` method of `FormSelectMenu` more than once, the array brackets will be added multiple times to the widget instance name (`field_name[]`, `field_name[][]`, `field_name[][][]`).

I expect this method to always return the same result. Same applies for the `parse()` method: It also modifies the widget instance name. I would expect this to only parse the template with no side-effects. 

~Secondly, the `generate` method is only called in `form_explanation.html5`, but nowhere else (in the Core Bundle at least). Shouldn't this method be deprecated as apparently the prefered way is calling `parse()`?~

Edit: I forgot about the back-end 🙈 In the `be_widget*.html5` templates the `generateWithErrors()` method is called (which calls `generate`).

Cheerio

**Comment by leofeyer** [comment]
How can I reproduce this without Haste?

**Comment by aschempp** [comment]
Create your own `FormSelect` widget instance and generate/parse it more than once.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/3029
