### ISSUE TITLE
Agree on strategy for named arguments

### ISSUE THREAD

**Issue by ausi** [contao/contao#2624]
Originally discussed in https://github.com/contao/contao/issues/2263#issuecomment-732964392

@m-vo
> PHP 8 promotes function arguments to become part of the API (named arguments).
> 
> Should we review and possibly adjust argument names across our codebase before they cannot be changed anymore?
> Or are we explicitly excluding argument names from our BC promise?

@Toflar
> > Or are we explicitly excluding argument names from our BC promise?
> 
> No way to provide BC for named arguments imho. So I would explicitly exclude it. It's pure nonsense.

@ausi
> > Should we review and possibly adjust argument names across our codebase before they cannot be changed anymore?
> 
> If we want to rename something. Now would certainly be the best time ☺️
> 
> We should probably also check if we use the same argument names as the interfaces we implement. Maybe there is a tool that can check for such things?
> 
> > No way to provide BC for named arguments imho. So I would explicitly exclude it. It's pure nonsense.
> 
> I’m not sure about that. Excluding it from our BC promise would mean that nobody can use named arguments with our API.

@m-vo
> > Now would certainly be the best time
> 
> We could also do it like [Wordpress](https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/) and discourage the use of named arguments until explicitly stated (= review/audit finished).
> 
> > We should probably also check if we use the same argument names as the interfaces we implement. Maybe there is a tool that can check for such things?
> 
> This should imo go into to the cs fixer if possible.

**Comment by leofeyer** [comment]
> Maybe there is a tool that can check for such things?

The PhpStorm code inspector checks if arguments of interfaces or parent classes have been renamed. I have already fixed this in #2544.

> No way to provide BC for named arguments imho.

I am for supporting named arguments. Some day in the future I want to be able to do this:

```php
new RequestMatcher(attributes: ['_scope' => 'backend']);
```

instead of having to to this:

```php
new RequestMatcher(null, null, null, null, ['_scope' => 'backend']);
```

**Comment by aschempp** [comment]
Is there something like `@internal` that we can use to mark them as API? Unfortunately that was not included directly in the PHP8 specs (like `strict_types`).

**Comment by leofeyer** [comment]
As discussed in Mumble on February 11th, we do not support named arguments at the moment. We might do so in the future when we are on PHP 8 only and when we feel like it is a good idea to make argument names public API.
