### ISSUE TITLE
DCA-Filterfunktion bei SELECTs mit options_callback

### ISSUE THREAD

**Issue by do-while** [contao/contao#2626]
**Affected version(s)**

Contao 4.9

**Description**

Ich habe  ein Problem mit Filtern im DCA (Contao 4.9.10):
Ich habe ein SELECT, wo in der Datenbank die Texte und nicht die Indices eingetragen werden. Die Optionen werden dynamisch erzeugt und über den options_callback definiert. Das funktioniert auch in dem Widget bei der Eingabe korrekt.  Die Filterwerte in der Listenansicht sind aber immer leer.

Ich habe das Problem mal vereinfacht:
```
    $arrOptions = ['Option A', 'Option B', 'Option C'];     // Beispiel-Array

	//---------------------------------------------------------------

    'title' => array
	(
		'label'                   => &$GLOBALS['TL_LANG']['tl_mytable']['title'],
		'exclude'                 => true,
		'filter'                  => true,
		'sorting'                 => true,
		'flag'                    => 11,
		'inputType'               => 'select',
		// 'options'		  => $arrOptions,
		'options_callback'        => array('tl_mytable', 'getOptions'),
		'eval'                    => array('mandatory'=>true, 'tl_class'=>'w50', 'includeBlankOption'=>true),
		'sql'                     => "varchar(80) NOT NULL default ''"
	),

	//---------------------------------------------------------------

	public function getOptions( DataContainer $dc )
	{
		return $arrOptions;
	}
```
Wenn ich das Array in `options` direkt angebe, funktionieren die Filter.
Verwende ich aber den `options_callback` und gebe einfach nur **das gleiche Array** zurück, sind die Filter tot. (Es ist auch sichergestellt, dass bei jedem Aufruf des Callback das Array auch bereits existiert, das habe ich überprüft)

Der `options_callback` und der Listen-Filter funktionieren offenbar nur korrekt, wenn in der Datenbank der Array-Index gespeichert ist. Sobald der Inhalt vom Array-Element gespeichert ist, geht es nicht.
Vielleicht wird versucht einen Inhalt mit dem Text als Index zu finden?

Da aber bei mir die Optionen in den Einstellungen verändert oder gelöscht werden können und dabei alte Einträge nicht verändert werden dürfen, kann ich nicht mit einem Index auf den Text arbeiten.

**Comment by leofeyer** [comment]
Ich bin mir nicht ganz sicher, ob ich das Problem richtig erfasst habe, aber so wie ich es verstehe ist das das erwartete Verhalten. Die Filter zeigen nur die Optionen an, zu denen es auch passende Datensätze gibt.

**Verfügbare Optionen bei der Auswahl**

<img width="591" alt="" src="https://user-images.githubusercontent.com/1192057/111269898-76d22300-862f-11eb-92fb-8bd365f2dc1e.png">

**Verfügbare Optionen im Filter**

<img width="400" alt="" src="https://user-images.githubusercontent.com/1192057/111269988-9406f180-862f-11eb-97ec-52c031ac67f7.png">
