### ISSUE TITLE
validation of comment form website-field

### ISSUE THREAD

**Issue by asaage** [contao/contao#2629]
Just stumbled about this:
The "website"-field in the comment forms accept **mailto:** urls.
I don't think that's desired but if so - the email-address should at least be encoded in the output.

**Comment by Total-Reality** [comment]
My opinion is that the entire implementation of URL validation in HTML5 is incorrect or insufficient. It cannot be that the user is always forced to write "http" or "https" at the beginning of the URL. Many users don't understand this, so they write www.example.com and are not able to submit the form.
The validation of URLs should be implemented with PHP only - globally in Contao. Please change the behavior of rgxp => url - at least in the Frontend.

**Comment by leofeyer** [comment]
As of Contao 4.11, there is the `httpurl` rgxp option, which does not allow mailto: URLs and which says "Please enter an absolute URL starting with https:// or http://" if the input is not an absolute URL. It essentially solves both issues mentioned in this PR.

@contao/developers Would it be ok to only fix this in Contao 4.11?

**Comment by Total-Reality** [comment]
Sounds good, but why isn't it possible to enter www URLs without http or https? https:// prefix could be added automatically via in the internal PHP script.
Or is it also solved with your new fix?
