### ISSUE TITLE
Incorrect routing behavior with multiple slashes

### ISSUE THREAD

**Issue by aschempp** [contao/contao#263]
**Affected version(s)**
3.* (probably any) & 4.*

**Description**  

While implementing https://github.com/contao/contao/pull/95 I noticed a strange behavior. A URL with alias `foo` and path `foo//bar` ignores the `//bar` part, because the key to `bar` is not given. This does not really make sense, it should be redirected to one slash or render a 404.

The case is handled by `Frontend::getPageIdFromUrl` (around line 254) or after #95 in `InputEnhancer` (around line 76).

**How to reproduce**  

Unfortunately, this seems to depend on the webserver. demo.contao.org runs on Nginx which seems to automatically strip multiple slashes.

**Comment by leofeyer** [comment]
As discussed in Mumble on January 17th, we want to fix this in Contao 4.4 by adding `return false` [here](https://github.com/contao/contao/blob/ef0dae7c933477932e902af1e2e56ffc8014f4e0/core-bundle/src/Resources/contao/classes/Frontend.php#L246) and in Contao 4.7 additionally (!) by throwing a `ResourceNotFoundException` [here](https://github.com/contao/contao/blob/e23259b877df5b16f35e7cce4b468d7940ae7fe4/core-bundle/src/Routing/Enhancer/InputEnhancer.php#L81).

**Comment by leofeyer** [comment]
Fixed in Contao 4.4 in 037689be2fb97a2f3db1d671137e9bdc07349d6a.

**Comment by leofeyer** [comment]
Fixed in Contao 4.7 in 9f887cfdb2dcf83559ef95b183f6181097576b58.
