### ISSUE TITLE
Improve handling of boolean entity fields (DCA)

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2637]
**Affected version(s)**

Contao 4.9

**Description**

This bit in `DC_Table` sets a default value if the current one is considered *empty*: 

https://github.com/contao/contao/blob/5fd76d55ab9266027585eea6d7ace08730af49a7/core-bundle/src/Resources/contao/drivers/DC_Table.php#L3172-L3176

That's a bit of a bummer when using DCA with entities as their data definition. With a checkbox + boolean field type, I already need to keep adding a `save_callback` like this to get the right type:
```php
'save_callback' => [static fn ($v) => '1' === $v]`
```

But due to the string cast, yet another `sql` definition in the DCA is needed just to prevent `DC_Table` from saving an empty string again:
```php
'sql' => ['type' => 'boolean', 'default' => false]`
```

Maybe there's a clever way to improve this situation a but without breaking anything else. :smiley:

**Comment by fritzmg** [comment]
I suppose we have to query the database directly for the field's type, instead of relying on `sql` within the DCA?

**Comment by aschempp** [comment]
Contao uses "" and "1" for Boolean, maybe we could fix that by providing a `boolean_string` datat type (similar as our `binary_string`)?

**Comment by fritzmg** [comment]
> Contao uses "" and "1" for Boolean

It works with `'sql' => ['type' => 'boolean', 'default' => false]` too though.

**Comment by m-vo** [comment]
But not without the sql definition which is the default when using a DCA on entities.

**Comment by aschempp** [comment]
Ah yes, our default value parser does not use the metadata. I've run into this as well with null-defaults for integer fields for example.

**Comment by leofeyer** [comment]
@aschempp Why did you remove the "up for discussion" label? Is there a solution already?

**Comment by fritzmg** [comment]
Related issue: even if you use a DCA, but with `'sql' => ['type' => 'boolean', 'default' => false]` (instead of Contao's usual `char(1)`), the following error will occur in the back end when trying to save a record:

```
An exception occurred while executing 'UPDATE tl_calendar_events SET `foobar`='' WHERE id='15'':

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `foobar`.`tl_calendar_events`.`foobar` at row 1
```

This was actually introduced by https://github.com/contao/contao/pull/2588
Before that fix, the empty value would have been set to `false`, rather than an empty string.

So even if @m-vo added a DCA containing `'sql' => ['type' => 'boolean', 'default' => false]`, it would ~~break~~ have been broken in Contao `4.9.11` :(

**Comment by m-vo** [comment]
*posted by @aschempp in #2668*
> Can't this be solved by using doctrine metadata to get the actual SQL default?

I think so, too. We should imo read the class metadata (from em), check if an entity is defined for the table and take the information from there in this case.

**Comment by fritzmg** [comment]
I don't think you need to check for an entity at all. Simply check if a DCA `sql` definition exists and if not query the meta data from the database and pass that then to `Widget::getEmptyValueByFieldType`.

**Comment by leofeyer** [comment]
As discussed in Mumble on February 11th, we should always check the Doctrine metadata for the empty values. We also want to deprecate the static `Widget::getEmptyValueByFieldType()` method and we want to encapsulate the logic in a service. We then want to use the service  in the non-static `getEmptyValue()` method as well as in the DC_ classes etc.

**Comment by m-vo** [comment]
Can someone shed some light what `Widget::getEmptyStringOrNullByFieldType()` / `Widget#getEmptyStringOrNull()`are supposed to solve resp. what the relationship to the other two methods are.

**Comment by leofeyer** [comment]
```php
class CustomWidget extends Widget
{
    public function foo()
    {
        $this->getEmtpyStringOrNull();

        // This is the same as calling the non-static method above
        static::getEmptyStringOrNullByFieldType($GLOBALS['TL_DCA'][$this->strTable]['fields'][$this->strField]['sql']);
    }
}
```

**Comment by ausi** [comment]
> what the relationship to the other two methods are.

They are very similar, except they only return `null` for nullable columns and in any other case return the empty string.

So we should apply the same changes to these methods IMO (deprecate the static one and use the doctrine metadata in the non-static one)

**Comment by m-vo** [comment]
Still on my list.

**Comment by m-vo** [comment]
Still on my list. Probably not in the nearest future, though.
