### ISSUE TITLE
Rename the default branch in all repos

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2642]
Renaming the default branch for existing GitHub repos is [finally available](https://github.com/github/renaming#creating-a-seamless-move-for-existing-repositories-), therefore I have checked all non-archived repos:

- [x] [contao/calendar-bundle](https://github.com/contao/calendar-bundle): can only be renamed after renaming `contao/contao`
- [x] [contao/comments-bundle](https://github.com/contao/comments-bundle): can only be renamed after renaming `contao/contao`
- [x] [contao/conflicts](https://github.com/contao/conflicts): the default branch is still `master`
- [x] [contao/contao](https://github.com/contao/contao): we will rename `master` to either `main` or `4.x` once Contao 4.11.0-RC1 has been tagged
- [x] [contao/contao-manager](https://github.com/contao/contao-manager): the default branch is `1.x`
- [x] [contao/core-bundle](https://github.com/contao/core-bundle): can only be renamed after renaming `contao/contao`
- [x] [contao/docs](https://github.com/contao/docs): the default branch is still `master` (@fritzmg)
- [x] [contao/docs-archive](https://github.com/contao/docs-archive): the default branch is still `master` (@fritzmg)
- [x] [contao/easy-coding-standard](https://github.com/contao/easy-coding-standard): the default branch is `3.x`
- [x] [contao/faq-bundle](https://github.com/contao/faq-bundle): can only be renamed after renaming `contao/contao`
- [x] [contao/image](https://github.com/contao/image): the default branch is still `master` (@ausi)
- [x] [contao/imagine-svg](https://github.com/contao/imagine-svg): the default branch is still `master` (@ausi)
- [x] [contao/installation-bundle](https://github.com/contao/installation-bundle): can only be renamed after renaming `contao/contao`
- [x] [contao/listing-bundle](https://github.com/contao/listing-bundle): can only be renamed after renaming `contao/contao`
- [x] [contao/managed-edition](https://github.com/contao/managed-edition): the default branch is `main`
- [x] [contao/manager-bundle](https://github.com/contao/manager-bundle): can only be renamed after renaming `contao/contao`
- [x] [contao/manager-plugin](https://github.com/contao/manager-plugin): the default branch is `main`
- [x] [contao/mobile-page-layout-bundle](https://github.com/contao/mobile-page-layout-bundle): the default branch is `main`
- [x] [contao/monorepo-tools](https://github.com/contao/monorepo-tools): can only be renamed after adjusting all CI files in all branches!
- [x] [contao/news-bundle](https://github.com/contao/news-bundle): can only be renamed after renaming `contao/contao`
- [x] [contao/newsletter-bundle](https://github.com/contao/newsletter-bundle): can only be renamed after renaming `contao/contao`
- [x] [contao/official-demo](https://github.com/contao/official-demo): the default branch is `main`
- [x] [contao/package-list](https://github.com/contao/package-list): the default branch is `main`
- [x] [contao/package-metadata](https://github.com/contao/package-metadata): the default branch is `main`
- [x] [contao/phpstan](https://github.com/contao/phpstan): the default branch is `main`
- [x] [contao/polyfill-symfony](https://github.com/contao/polyfill-symfony): the default branch is `main`
- [x] [contao/schema.contao.org](https://github.com/contao/schema.contao.org): the default branch is `main`
- [x] [contao/skeleton-bundle](https://github.com/contao/skeleton-bundle): the default branch is `main`
- [x] [contao/tcpdf-bundle](https://github.com/contao/tcpdf-bundle): the default branch is `1.1`
- [x] [contao/test-case](https://github.com/contao/test-case): the default branch is `4.x`
- [x] [contao/to.contao.org](https://github.com/contao/to.contao.org): the default branch is `main`
- [x] [contao/website](https://github.com/contao/website): the default branch is `main`

**Comment by leofeyer** [comment]
@contao/developers Renaming the default branch of `contao/conflicts` will be challenging, because people now require it as `dev-master` in their `composer.json` files. Can we set a branch alias `dev-master` pointing to `dev-main`?

**Comment by aschempp** [comment]
> @contao/developers Renaming the default branch of `contao/conflicts` will be challenging, because people now require it as `dev-master` in their `composer.json` files. Can we set a branch alias `dev-master` pointing to `dev-main`?

No, but we can (and should) keep both in sync. I can (and will) update the Contao Manager as soon as `main` is available to automatically adjust the `composer.json`. We already automatically maintain that dependency by adding it to all projects. That does not adjust anyone not using Contao Manager, so I would suggest to keep `master` for at least this year.

**Comment by fritzmg** [comment]
> Renaming the default branch of `contao/conflicts` will be challenging, because people now require it as `dev-master`

Do they? The `contao/managed-edition` defaults to `@dev` and so does the Contao Manager I think?

**Comment by aschempp** [comment]
that's true! We actually require `*@dev` 😎

**Comment by fritzmg** [comment]
> that's true! We actually require `*@dev` 😎

The `composer.lock` will still reference `dev-master` though, not sure if that's a problem.

**Comment by ausi** [comment]
> The `composer.lock` will still reference `dev-master` though, not sure if that's a problem.

I just renamed the version in my composer.lock file to a non-existing branch and it did’t seem to have an effect. I think it uses the stored commit hash regardless of the branch.

So I think renaming should not be a problem.

**Comment by ausi** [comment]
> because people now require it as `dev-master` in their `composer.json` files.

That would be an error. The readme explicitly states to use `@dev` as the version constraint. This is required because we might be forced in the future to split our main branch into two or more branches (based on the contao-version for example). With using `@dev` composer would then automatically install the correct branch.

**Comment by leofeyer** [comment]
Renaming the default branch in `contao/conflicts` did not cause any issues:

```
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading contao/conflicts (dev-master b1bab2b => dev-main b1bab2b)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Upgrading contao/conflicts (dev-master b1bab2b => dev-main b1bab2b)
```

**Comment by leofeyer** [comment]
Done. 🎉
