### ISSUE TITLE
Remove duplicate div container with "custom" class from block_sections Template

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#2645]
**Affected version(s)**
Contao 4.9

**Description**
We always work with custom layouts with more than two custom layout sections. 
![layout-be](https://user-images.githubusercontent.com/5235894/104776068-c1433a80-5779-11eb-8843-93e69a2b1bda.PNG)

Result: Divs with css class "custom" exists twice or more in the source code. This div is totally unnecessary. 
The problem is anyway that you can't address the divs differently, because all of them have the css class "custom".

The "custom" div already contains a div with the ID named in the layout section. This one contains a div with the css class "inside". So this is a 3-fold nested div. 

Whatever... 2-fold nested is enough indeed.

1. That wastes unnecessary bytes
2. Additionally it also often hinders the styling.
3. I can't see any benefits, because every custom div has the class "custom". Nobobody styles all custom classes exactly.

![layout-fe](https://user-images.githubusercontent.com/5235894/104776086-c902df00-5779-11eb-83bd-86813d1995a9.PNG)

Can you take this out, please?

Solution: Please remove `<div class = "custom">` from the template block_sections.html5.

**Comment by m-vo** [comment]
I don't think it's worth breaking this to be honest. Or is there something that doesn't work in that regard? Maybe I'm not getting the problem. 🙃

It's still possible to individually access these elements with the class reference and `nth` child selectors or by index when using JS for instance. And for those using only one custom section anyway.

**Comment by Total-Reality** [comment]
Perhaps someone wants to place footer and copyright side by side - so the "custom" class is annoying.

Additionally the "custom" containers are not consistent in the typcial structure. Every first and second level element is an element with an id... wrapper, header, container, footer. 
It should be continued like this. It looks nicer and nothing is duplicate.

As I mentioned before we can save up 26 Bytes for every custom Element multiplied with the number of views of every single page. This results in a few tons unnecessary co2 emissions every year all over the world.

Btw. disadvantages with "nth" selectors instead of unique div ids:
1. You have to count the elements. What if one or more divs does not exist on some pages, because of dynamic content or no/empty articles inside.
2. "nth" selectors doesn't work in all browsers
3. ugly css code and more senseless bytes 
4. You have to change the css code when you delete the first custom div e.g.

**Comment by m-vo** [comment]
>This results in a few tons unnecessary co2 emissions every year all over the world.

This is a *huge* overestimate of the popularity of Contao + the impact of these lines (esp. with compression). It's not measurable in the noise of actual content.

If you're bothered for your projects, you should easily be able to adjust the templates to your need. Keep in mind: this is highly opinionated, again. There's a reason for all the "no IDs" linter rules for instance. And we don't make changes to templates lightly, because we would unnecessarily break a lot of things.

Not arguing about your points in general. But trying to get the point across, why IMHO such changes aren't worth it.

**Comment by Total-Reality** [comment]
Hmm you are right, this issue will break some website styles extremely. However can you change it in the new LTS version, 4.13?
Users with problems need to change only some selectors in css or put a custom template in the templates folder.
 
I know that I can change the template, but I prefer to have custom templates as less as possible.

**Comment by fritzmg** [comment]
> However can you change it in the new LTS version, 4.13?

No, this can only be changed in Contao 5.0. Minor versions need to be BC.

**Comment by Total-Reality** [comment]
Okay, I can understand that. Can you implement this in Contao 5?

**Comment by fritzmg** [comment]
I don't see why not. I have tagged this issue with the labels _feature_ and _incompatible_ meaning that it can be taken into consideration for Contao 5.

**Comment by aschempp** [comment]
Templates are not covered by the BC promise in general. I agree this div is nonsense, but I also think removing it would break a lot of layouts.

Maybe we can change it with 4.14 (after next LTS). But I generally think we need to improve the frontend layout for grid CSS etc as well, so this might become obsolete.
