### ISSUE TITLE
modalIFrame: OK button not displayed

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2646]
**Affected version(s)**

Contao 4.9

**Description**
1) File manager
2) open info box
3) modalIFrame does not display the OK-Button (see 4)
![grafik](https://user-images.githubusercontent.com/1645099/104819670-40df1100-582f-11eb-8073-72ca1a1dec71.png)
(screen shot from demo.contao.org)

Does it have any reason? Or is it a bug? Is it possible to display this button via parameter like title, width and height?

```
onclick="Backend.openModalIframe({'title':'content-images','url':this.href});return false"
```

**Comment by asaage** [comment]
What do you think "OK" should do?
I mean there is the **X** in the top-right corner to close the modal and there is nothing else to save, to acknowledge, to cancel or to select...

**Comment by Total-Reality** [comment]
Nobody needs a button there. The markup should be removed in this case. It's "dirty" to set display:none only. 
We can save some bytes without the markup and the css instructions.

**Comment by m-vo** [comment]
>  It's "dirty" to set display:none only.
We can save some bytes without the markup and the css instructions.

Go ahead and make a PR. It doesn't make sense complaining about these arbitrary details either.

**Comment by Total-Reality** [comment]
You don't like details?
Sorry, that I found details only to optimize, because Contao is nearly perfect ;)

I don't understand how this PR "system" works.

**Comment by math-GH** [comment]
What would I expect as a user?

I would expect a close button at the bottom. Similar to the close button in the file picker (continuous UX/UI)
![grafik](https://user-images.githubusercontent.com/1645099/104838319-91e81700-58ba-11eb-908d-7a850bb6de2b.png)
