### ISSUE TITLE
Remove duration from mod_search template

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#2647]
I have no problem that you calculate the duration in the search engine module, but I don't think that most of the users needs the information about the seconds. 
What is the benefit? 

No top website or platform shows this information except Google (and Contao :D).
Look at Amazon, Bing, Wikipedia, Zalando, Github et cetera.

Why we should display it by default? I think it is a senseless information.

Can you remove this duration part from here? 
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/modules/mod_search.html5#L27

People who want to display this information are free to use a custom template.

**Comment by bytehead** [comment]
> People who want to display this information are free to use a custom template.

Let me adapt this to your needs:
_People who want to hide this information are free to use a custom template._

**Comment by leofeyer** [comment]
Although I am also not quite sure what to do with this information, Google seems to think it is valuable, too:

<img width="876" alt="" src="https://user-images.githubusercontent.com/1192057/110791436-825dcc80-8272-11eb-93bd-2d1fb6babda3.png">

**Comment by leofeyer** [comment]
As discussed in Mumble on March 11, there is more technical information such as relevance and document size, which are also not really relevant for the users. Therefore, we want to adjust the default template in Contao 4.12 and remove the search time, the relevance and the document size (while keeping the variables in the template in case someone wants to show the information).
