### ISSUE TITLE
backend user administration: 2 missed svg files

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2648]
**Affected version(s)**

Contao 4.9

**Description**
backend user administration:
This 2 svg files are missed
![grafik](https://user-images.githubusercontent.com/1645099/104855694-80305f00-590e-11eb-86c4-bcfa0dcf9deb.png)

**Comment by fritzmg** [comment]
I cannot reproduce the problem in Contao 4.9 or 4.10. These files definitely exist under the given URLs.

![Screenshot_2021-01-17 Benutzer demo contao org](https://user-images.githubusercontent.com/4970961/104855977-c8984e80-5907-11eb-8ae9-c904c4e764ed.png)

**Comment by math-GH** [comment]
ok. I found the issue. it is my fault.

It is not a contao bug.
