### ISSUE TITLE
Handle basic entities in the figure insert tag

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2649]
![](https://user-images.githubusercontent.com/1192057/104914439-70a52a80-598f-11eb-9052-0abdb8f7ea5e.png)

If I compare this with the code of the `image` tag, I notice that there are some differences.

https://github.com/contao/contao/blob/6d3ccc6a115719c0f1a5a4e0be90ba7928750a56/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L783-L786

What about decoding and replacing `[&]` with `&`? Is this not necessary here?

_Originally posted by @leofeyer in https://github.com/contao/contao/pull/2607#discussion_r559514669_

**Comment by m-vo** [comment]
see https://github.com/contao/contao/pull/2662
