### ISSUE TITLE
2FA mit Rückfallebene

### ISSUE THREAD

**Issue by kroerig** [contao/contao#265]
Ich habe testweise mal bei einer Installation 2FA für mein Admin-Konto aktiviert. Klappt auch wunderbar, aber... wenn ich mal keinen Zugriff (mehr) auf meinen Tokengenerator habe, dann habe ich mich ausgesperrt.
Dann hilft nur noch ein beherzter Eingriff in die Datenbank. Für einen Admin machbar, für einen einfachen Redakteur mit Sicherheitsverständnis (ja, schwer zu finden) nicht. Der muss dann erst den Admin rufen, und der im schlimmsten Fall noch den Systembetreuer.

Andere Webdienste (u.a. dieser hier und z.B. Nextcloud) bieten hier die Möglichkeit sich Notfallpasswörter zu generieren, mit denen man sich dann anmelden kann.

Wäre schön, wenn Contao das auch könnte.

**Comment by Paddy0174** [comment]
BackupCodes wären sicherlich eine gute Verbesserung, zumal das verwendete Paket (scheb/two-factor-bundle) diese Funktion ohnehin schon inkludiert hat. Man müsste "nur noch" die Implementierung in Contao machen...

👍 von mir

**Comment by Toflar** [comment]
> Man

Feel free 😄

**Comment by Paddy0174** [comment]
@Toflar Der war so klar, ich verkneife mir seit Samstag deshalb einen Kommentar... :-D

Wenn ich Dich im Zweifel mit Fragen nerven darf, dann JA, sonst stehe ich da ziemlich schnell an, vermute ich. Timeframe bei mir: zum Ende Januar hin, vorher nur bei Terminabsagen

**Comment by kroerig** [comment]
Schön, dass meine Idee Anklang findet.

Ich bin leider was Softwareentwicklung angeht komplett raus. Stelle mich aber gerne als Testkandidat zur Verfügung.

**Comment by leofeyer** [comment]
Wir werden die 2-Faktor-Authentifizierung auf dem nächsten Entwicklertreffen weiter ausbauen.

In Contao 4.7 haben wir bereits die Möglichkeit nachgerüstet, das Einmalpasswort ohne QR-Code einzurichten (siehe contao/contao#86). Jetzt fehlt aus meiner Sicht noch:

- 2FA im Frontend
- Recovery-Codes (also "Notfallpasswörter")
- Vertrauenswürdige Geräte (auf denen nicht mehr nach einem Einmalpasswort gefragt wird)

@bytehead /cc

**Comment by bytehead** [comment]
2FA im Frontend habe ich bereits angefangen, alles was Backend-2FA betrifft ist einfacher 😉

**Comment by kroerig** [comment]
Wie funktioniert das denn dann mit den "vertrauenswürdigen" Geräten?

Wird ein Cookie gesetzt? Dann könnte sich ja jeder ohne 2FA von diesem Gerät anmelden.
Oder ein Fingerprint vom System/Browser in Conato gespeichert?
Und wie lange ist dieses Gerät dann vertrauenswürdig?

Dann sollte vllt. auch, wie z.B. Google es macht, eine Mail an den Benutzer gehen mit "Du hast dich gerade von einem neuen Gerät angemeldet. ..."

**Comment by leofeyer** [comment]
See #559 and #719.
