### ISSUE TITLE
BC break in method signature

### ISSUE THREAD

**Issue by richardhj** [contao/contao#2652]
The `: array` type hint was introduced in cc5a03de305f4485269f6b70859700ea7823a1a9 which results in BC break as extending classes have to adapt the changed signature.

I rate it low-severity and it can be easily fixed but we should discuss it here?

https://github.com/contao/contao/blob/bdba298d3f102bf119bdf178e1a7b6e902b90ffb/core-bundle/src/Controller/AbstractFragmentController.php#L36

The method is defined in `Symfony\Contracts\Service\ServiceSubscriberInterface`. I guess the stronger type declaration is just a mistake here.

**Comment by leofeyer** [comment]
> The `: array` type hint was introduced in [cc5a03d](https://github.com/contao/contao/commit/cc5a03de305f4485269f6b70859700ea7823a1a9)

That is not correct. The return type has been there in Contao 4.9 as well:

https://github.com/contao/contao/blob/7bc1599f4ea3f26c5402efc2ef6c8e1a3b222d16/core-bundle/src/Controller/AbstractFragmentController.php#L36

**Comment by richardhj** [comment]
Ah okay. The commit cc5a03de305f4485269f6b70859700ea7823a1a9 was merged into 4.9 and released with the versions 4.11.0-RC1, 4.10.6, and 4.9.11. 😊 The error just occurred for me when updating to the 4.11 recently.
Whenever a custom fragment controller implements the `getSubscribedServices()` method, the page will break.

**Comment by leofeyer** [comment]
@aschempp /cc

**Comment by aschempp** [comment]
I think we can safely remove the type hint to fix the (potential) BC break. I did run into this myself recently.
