### ISSUE TITLE
Try using scheb/2fa-qr-code and scheb/2fa-totp

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#2665]
As a follow-up to #2664, we should try to remove our custom 2FA authentication provider and use `scheb/2fa-totp` instead. This will require to implement the `TwoFactorInterface` in our `Contao\User` class. And it will allow us to use `scheb/2fa-qr-code` instead of `bacon/qr-code`.

**Comment by aschempp** [comment]
What advantage does it provide?

**Comment by leofeyer** [comment]
We no longer have to maintain a custom 2FA authentication provider. And of course it makes sense to use the QR code package of the same vendor as the other 2FA packages, because it will be in sync with the rest.

**Comment by bytehead** [comment]
I don't know if there are any advantages. The idea behind was more to use the stuff that `scheb/2fa-*` packages provide.

**Comment by aschempp** [comment]
I think the whole point of our custom 2FA authentication provider was **not** to implement `TwoFactorInterface` in our user, also because our user is (kind of) a model and cannot use dependency injection.

**Comment by leofeyer** [comment]
I doubt that.

**Comment by bytehead** [comment]
We get rid of the direct dependency `spomky-labs/otphp` as well. But the library will come again as a dependency of `scheb/2fa-totp`.

**Comment by bytehead** [comment]
I've investigated a little time into this issue.

As of now we get the `server_name` from the request (HTTP host):
https://github.com/contao/contao/blob/93755143171d0463fb75e03ff54aef43c097e860/core-bundle/src/Security/TwoFactor/Authenticator.php#L41

And this works seamless in multi domain installations as well and gives a hint to the user and his TOTP app where the access token is used.

In `scheb/2fa-totp` the `server_name` is a configuration value per installation:
https://github.com/scheb/2fa/blob/5.x/doc/providers/totp.md#configuration-options

I didn't find an easy way to make that dynamically set (request based). The configuration is done all on compile time and it doesn't seem to be adjustable. Do I miss something here?  

At the very end we don't win that much as `scheb/2fa-qr-code` requires `endroid/qr-code` in https://github.com/scheb/2fa/blob/70886d7544bdd6ab69ba78b858d5fbf5511af4ed/src/qr-code/composer.json#L16 and `endroid/qr-code` itself requires `bacon/bacon-qr-code` in https://github.com/endroid/qr-code/blob/43cbf2d46a04eeb1f0c3a22fad6edfdd6ac4c4d5/composer.json#L16

**Comment by leofeyer** [comment]
Then we will just leave everything as is. Thank you for checking. 🙏🏻
