### ISSUE TITLE
Element Tabelle mit "Auge"

### ISSUE THREAD

**Issue by Bigga63** [contao/contao#268]
Von einem Kunden kommt die Frage, ob man nicht auch bei dem Tabellenelement dies praktische "Auge" haben könne, mit dem einzelne Zeilen dann zeitweilig unsichtbar geschaltet werden.
Ich würde mich freuen, wenn daran reges Interesse besteht!

**Comment by asaage** [comment]
Ich glaube, das ist ein bisschen zuviel für das kleine einfache Tabellenelement :)
Bei Zeilen hört's ja dann nicht auf - der Nächste mag gern Spalten oder Zellen unsichtbar haben und der übernächste einen Richtext-Editor pro Zelle mit Berechtigungsprüfung und zeitgesteuerter Veröffentlichung.
Eventuell ist das Tabellenelement nicht die richtige Wahl für das, was dein Kunde braucht - oder eine unveröffentlichte Kopie des Elements mit vollständigen Zeilen zum hin- und herschalten tut's vielleicht auch.

**Comment by zonky2** [comment]
ggf. wäre die Möglichkeit CSS-Klassen für Spalten und Zeilen eintragen zu können ein Kompromiss - man könnte eine Formatierung angeben und das Ein/Ausblenden über Klassen regeln ....

ohne den Kunden an den CSS-Enditor zu hängen und mit "nth" arbeiten zu lassen :D

**Comment by leofeyer** [comment]
Wie am 7. März auf Mumble besprochen, sind wir auch der Meinung, dass das Overkill wäre. Neben dem Deaktivieren von Zeilen müsste man dann ja auch noch Spalten deaktivieren können und dasselbe dann für das Listen-Element und so weiter.
