### ISSUE TITLE
[Contao 4.9] Fresh installation fails, worked yesterday

### ISSUE THREAD

**Issue by bohnmedia** [contao/contao#2681]
Hi,

I cannot install Contao 4.9 anymore and get the following error in frontend and backend.

Tried it with a clean installation:

1. Copied "contao-manager.phar.php" into /web folder
2. Opened contao manager
3. Selected PHP 7.4
4. Disabled Composer Cloud
5. Selected Contao 4.9 Minimal for installation
6. Installed Packages
7. Opened install tool
8. Selected empty database
9. Created tables
10. Created adminuser

When I tried to login into the backend after that, I got the following error.

```
request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function Scheb\TwoFactorBundle\Security\TwoFactor\TwoFactorFirewallConfig::__construct(), 3 passed in /var/www/var/cache/prod/ContainerGxvG1kp/getContao_Security_AuthenticationProvider_ContaoBackend_TwoFactorDecoratorService.php on line 25 and exactly 4 expected" at /var/www/vendor/scheb/2fa-bundle/Security/TwoFactor/TwoFactorFirewallConfig.php line 37 {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Scheb\\TwoFactorBundle\\Security\\TwoFactor\\TwoFactorFirewallConfig::__construct(), 3 passed in /var/www/var/cache/prod/ContainerGxvG1kp/getContao_Security_AuthenticationProvider_ContaoBackend_TwoFactorDecoratorService.php on line 25 and exactly 4 expected at /var/www/vendor/scheb/2fa-bundle/Security/TwoFactor/TwoFactorFirewallConfig.php:37)"} []
```

composer.json
```
{
    "type": "project",
    "require": {
        "contao/manager-bundle": "4.9.*",
        "contao/conflicts": "*@dev"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

I installed it yesterday the same way on the same server without problems. Any ideas?

Best regards
Dennis

**Comment by bytehead** [comment]
Yes, see #2680.

**Comment by bytehead** [comment]
temporary fix for you: (put this in your `composer.json`)
```json
"conflict": {
    "scheb/2fa-bundle": ">=5.4"
},

**Comment by bohnmedia** [comment]
Thank you! Sorry for doublepost. Overlooked that.

**Comment by bytehead** [comment]
No worries. You're welcome! The bug is quite new, exists since two hours 😅

**Comment by bohnmedia** [comment]
Ok 😅

**Comment by bytehead** [comment]
Don't forget to remove the conflict when `contao/core-bundle: 4.9.12` is released!

**Comment by bytehead** [comment]
@bohnmedia you can remove the conflict and run a `composer update`. The conflict is now in `contao/conflicts` (see https://github.com/contao/conflicts/pull/15) and will be removed as soon as `contao/core-bundle: 4.9.12` is released 🙃 happy weekend!
