### ISSUE TITLE
Title attribute of image cannot be fetched in picture template

### ISSUE THREAD

**Issue by codedge** [contao/contao#2682]
**Affected version(s)**

4.10

**Description**

Images in Contao have attributes like `name`, `alt` and `title`. Unfortunately the `title` cannot be fetched inside `picture_default.html5` as it is not included inside `$this` or `$this->img`.

Normally I can access them with `$this->img['xyz']` or `$this->alt`, but `$this->title` or `$this->img['title']` does not exist.

```php
/Users/max/code/customer1/templates/picture_default.html5:27:
object(Contao\FrontendTemplate)[903]
  protected 'blnCheckRequest' => boolean false
  protected 'strBuffer' => null
  protected 'strContentType' => string 'text/html' (length=9)
  protected 'arrData' => 
    array (size=3)
      'img' => 
        array (size=5)
          'srcset' => string 'assets/images/2/bild-1-ffd159e6.jpg' (length=91)
          'src' => string 'assets/images/2/bild-1-ffd159e6.jpg' (length=91)
          'width' => int 135
          'height' => int 135
          'hasSingleAspectRatio' => boolean true
      'sources' => 
        array (size=0)
          empty
      'alt' => string 'Esstisch rustikal Wildeiche Massanfertigung Massivholz Baumkante' (length=64)
  protected 'arrCache' => 
    array (size=0)
      empty
  protected 'arrObjects' => 
    array (size=2)
      'Config' => 
        object(Contao\Config)[420]
          protected 'Files' => null
          protected 'strTop' => string '' (length=0)
          protected 'strBottom' => string '' (length=0)
          protected 'blnIsModified' => boolean false
          protected 'arrData' => 
            array (size=0)
              ...
          protected 'arrCache' => 
            array (size=0)
              ...
          protected 'strRootDir' => string '/Users/max/code/customer1' (length=33)
      'ShareButtons' => 
        object(ShareButtons)[1015]
  protected 'strTemplate' => string 'picture_default' (length=15)
  protected 'strParent' => null
  protected 'strDefault' => null
  protected 'strFormat' => string 'html5' (length=5)
  protected 'strTagEnding' => string '>' (length=1)
  protected 'arrBlocks' => 
    array (size=0)
      empty
  protected 'arrBlockNames' => 
    array (size=0)
      empty
  protected 'intBufferLevel' => int 1
```

The user/programmer should have the option to include this tag inside the template.

![image](https://user-images.githubusercontent.com/4409904/105627044-835aac00-5e34-11eb-832e-c315ee21af7d.png)

**Comment by m-vo** [comment]
It's available in `Figure#getMetadata#getTitle()` as well as in the oldschool template data. For the latter there are some context sensitive transformations made for BC reasons. You can find the logic here: https://github.com/contao/contao/blob/4.10/core-bundle/src/Image/Studio/Figure.php#L214-L297. 

But it's in there ever since. Have a look at the `picture_default` template where it's output by default (or in `image` respectively when using a link).

**Comment by codedge** [comment]
Hm.. I cannot confirm. If I open the [`picture_default`](https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/templates/picture/picture_default.html5) template I can see that `$this->title` is inserted but it is actually empty/not existing inside `$this` although the title is set inside the "Dateiverwaltung" at the image.

The image has an alternative text (which is correctly accessible via `$this->alt`) and a title (which is not accessable via `$this->title`).

I am confused about the [`Figure`](https://github.com/contao/contao/blob/4.10/core-bundle/src/Image/Studio/Figure.php#L214-L297) class that you mention, as the object accessable inside `picture_default.html5` is `Contao\FrontendTemplate`.

**Comment by m-vo** [comment]
> I am confused about the Figure class that you mention, as the object accessable inside picture_default.html5 is Contao\FrontendTemplate.

I assume you're talking about images in content elements, then. There, a [Figure's](https://docs.contao.org/dev/framework/image-processing/image-studio/#figure) data will be compiled and added to your template context. The code I posted in my last comment does reference exactly this part of compiling the dataset. 

Do you maybe have a link set or the lightbox enabled? In this case the title will be output at the link tag by default (not the image).

**Comment by codedge** [comment]
That was it. The title of the image was used in the `figure` tag, which came from a different template and was modified to use the `$this->alt` for the `title`. A change to `title="<?= $this->imageTitle >"` solved all the headache.

Thanks for heads up!
