### ISSUE TITLE
PHP version mismatch lcobucci/jwt, error 500 after install

### ISSUE THREAD

**Issue by aznoqmous** [contao/contao#2687]
**Affected version(s)**

Contao 4.9

`contao/managed-edition:4.9` 
`contao/core-bundle:4.9`

**Description**
Server: `php7.2`, contao 4.9 use to work nicely

When installing contao via `composer create-project contao/managed-edition:4.9`
Installation proceed until the end, but give a 500 error when accessing the website
```
AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected 'Parser' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/username/www/vendor/lcobucci/jwt/src/Configuration.php on line 22'
```

The issue is that `jwt` is using php 7.4 syntax when contao requirement is set to php7.2 :
`contao/core-bundle:4.9` is requiring `php ^7.2 || ^8.0`
`lcobucci/jwt:3.4` is requiring `php ^7.4 || ^8.0`

I fixed it locally by requiring `lcobucci/jwt:^3.3.3`

**Comment by fritzmg** [comment]
Composer will resolve these dependencies automatically for you. May be you used the wrong PHP version for the `composer create-project` command?

**Comment by aznoqmous** [comment]
Thanks for the answer, I thought composer relied on php version required inside `composer.json` rather than system requirement
In my case we use different php versions but the one used in composer is always the latest

I fied my issue by adding my platform requirement as below : 
```
"config": {
        "platform": {
            "php": "7.2"
        }
    }
```

Thanks for your answer and keep up the good work !

**Comment by m-vo** [comment]
Composer - even when inside your bin directory - really only is a php file with a shebang. You can run it with any php version by prefixing your wanted version of php: `/usr/bin/php8.0 /usr/bin/composer`.

If you're using the symfony binary, I'd recommend prefixing all composer calls with it (`symfony composer`). That way you also always get the configured version of your project.
