### ISSUE TITLE
Sorting of root nodes in Backend-TreeView is ignored with filters

### ISSUE THREAD

**Issue by rabauss** [contao/contao#269]
**Affected version(s)**
4.x

**Description**  
If filters have been activated in the Backend-TreeView the sorting of the root nodes is ignored.
Without filters everything is fine!

**How to reproduce**  
For example if you activate the published-filter in pageTree the root nodes won't be shown sorted anymore.

**Possible Solution**
https://github.com/contao/contao/blob/4b73fdd80c7c2c82906893a1ffb132d5c974bea1/core-bundle/src/Resources/contao/drivers/DC_Table.php#L3497

The line above could be replaced by:
``$objRoot = $this->Database->prepare("SELECT DISTINCT " . \Database::quoteIdentifier($fld) . ($blnHasSorting ? ", sorting" : '') . " FROM " . $this->strTable . " WHERE " . implode(' AND ', $this->procedure) . ($blnHasSorting ? " ORDER BY sorting" : ''))``

**Comment by leofeyer** [comment]
Fixed in 00b89193021b2a787c5c8f2ba99039bb16e1ecf3.

**Comment by rabauss** [comment]
First I also just added the ORDER-Statement, but then I got a SQL-Error.
I guess it depends on SQL-Mode - because of that I also added the sorting row in SELECT.
At the moment I don't know, which SQL-Mode is prefered by contao...

**Comment by leofeyer** [comment]
Interesting. Which SQL mode are you using?

MySQL 5.7 uses

```
ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION
```

MariaDB as of version 10.2.4 has

```
NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION, STRICT_TRANS_TABLES, ERROR_FOR_DIVISION_BY_ZERO
```

**Comment by rabauss** [comment]
Well, the problem is ``ONLY_FULL_GROUP_BY`` - then you get the error: ``ORDER BY clause is not in SELECT list``

**Comment by leofeyer** [comment]
Well, I do not (get this error).

<img width="1194" alt="" src="https://user-images.githubusercontent.com/1192057/51184932-0b1c9000-18d6-11e9-964b-e60af9b86632.png">

And this is the query:

<img width="840" alt="" src="https://user-images.githubusercontent.com/1192057/51184940-12439e00-18d6-11e9-9989-6cd313a70d36.png">

**Comment by Toflar** [comment]
Sure it's this query that is affected?

**Comment by rabauss** [comment]
Attention: there is a ``DISTINCT`` in the query!
I get an error for ``SELECT DISTINCT published FROM tl_page ORDER by sorting`` and of course not for ``SELECT published FROM tl_page ORDER by sorting`` with SQL-Mode ``ONLY_FULL_GROUP_BY``!
If I remove ``ONLY_FULL_GROUP_BY`` both queries can be executed without errors.

![image](https://user-images.githubusercontent.com/14016098/51207568-7896e380-190b-11e9-8aa8-5ebd6ef15985.png)

**Comment by leofeyer** [comment]
Nope, still no error here.

<img width="462" alt="" src="https://user-images.githubusercontent.com/1192057/51238794-12947580-1978-11e9-85cf-999e1e9af875.png">

Can anyone else reproduce this?

**Comment by Toflar** [comment]
Well, I don't have to reproduce, I can see that the query is wrong. `SELECT DISTINCT` is essentially a `GROUP BY`. So it groups by `published` but it cannot order by `sorting` because it cannot determine which `sorting` value of all the rows with the same `published` it should take. You need an aggregate function there.

Grouping happens before ordering.

So to put that query in words it says: "Take all rows from `tl_page`, group them by `published` and then order by `sorting`".

MySQL doesn't know which sorting, because it does not exist after grouping. Should it take the `sorting` of the first of all that have `published=1`? The last? The max? The min?

**Comment by leofeyer** [comment]
I absolutely agree with you, however, I would still like to know why it works on my system.

**Comment by Toflar** [comment]
Well, your query does not return any row at all, I think that's why it works, because there are no multiple rows that can be grouped 😄

**Comment by leofeyer** [comment]
Good idea, but still no, unfortunately.

<img width="479" alt="" src="https://user-images.githubusercontent.com/1192057/51254996-9f542900-19a2-11e9-81e3-8996dfa291ec.png">

**Comment by Toflar** [comment]
This setup is still not correct, you need multiple results **per group**. So e.g. two or more where published=1.

**Comment by leofeyer** [comment]
I have. It is a distinct query, so it returns only two rows. There are 37 pages though in `tl_page`.

**Comment by Toflar** [comment]
Cannot tell you why it's not working for you. The only thing I can say is that the query is wrong.

**Comment by ausi** [comment]
I think this can be fixed either by using 

```sql
SELECT DISTINCT published FROM tl_page ORDER BY MIN(sorting)
```

or:

```sql
SELECT published FROM tl_page GROUP BY published ORDER BY MIN(sorting)
```

or:

```sql
SELECT published, MIN(sorting) as sorting FROM tl_page GROUP BY published ORDER BY sorting
```

**Comment by Toflar** [comment]
First query won't work:

> Expression #1 of ORDER BY contains aggregate function and applies to the result of a non-aggregated query

Both, the second and third would work. The third would also add `sorting` to the result set, in case that's relevant.

**Comment by leofeyer** [comment]
@rabauss Does `SELECT published FROM tl_page GROUP BY published ORDER BY MIN(sorting)` fix your issue as well?

**Comment by rabauss** [comment]
Yes, this query will work with ``ONLY_FULL_GROUP_BY``!

Although the correct generated Query would be something like `SELECT id FROM tl_page WHERE published = 1 GROUP BY id ORDER BY MIN(sorting)` or `SELECT pid FROM tl_page WHERE published = 1 GROUP BY pid ORDER BY MIN(sorting)` - so the GROUP BY is only necessary for the pid case. I mention this only because I had in between wondered why grouping is necessary at all ;-)

@leofeyer Did you check, if ``ONLY_FULL_GROUP_BY`` is persistent in your system, because the mode variable can be reset after mysql restart

**Comment by leofeyer** [comment]
It seems there is even more wrong here, because `sorting` is actually `tl_child.sorting` and not `tl_parent.sorting`.

<img width="1204" alt="" src="https://user-images.githubusercontent.com/1192057/51399303-ed556200-1b45-11e9-94c9-6d632facbd96.png">

Therefore this is how I think the code should be:

```php
if ($fld == 'id')
{
	// The ID is unique, therefore we do not need to group the results
	$objRoot = $this->Database->prepare("SELECT id FROM " . $this->strTable . " WHERE " . implode(' AND ', $this->procedure) . ($blnHasSorting ? " ORDER BY sorting" : ""))
							  ->execute($this->values);
}
elseif ($blnHasSorting)
{
	// Group by PID and sort by the sorting field of the parent (!) table
	$objRoot = $this->Database->prepare("SELECT pid, (SELECT sorting FROM " . $table . " WHERE " . $this->strTable . ".pid=" . $table . ".id) AS psort FROM " . $this->strTable . " WHERE " . implode(' AND ', $this->procedure) . " GROUP BY pid" . ($blnHasSorting ? " ORDER BY psort" : ""))
							  ->execute($this->values);
}
else
{
	// No sorting field, so just group by PID
	$objRoot = $this->Database->prepare("SELECT pid FROM " . $this->strTable . " WHERE " . implode(' AND ', $this->procedure) . " GROUP BY pid")
							  ->execute($this->values);
}
```

<img width="1202" alt="" src="https://user-images.githubusercontent.com/1192057/51399276-dca4ec00-1b45-11e9-85f3-11945a5e744b.png">

**Comment by leofeyer** [comment]
Fixed in f20e47f2829e93eec029b4b3b7f1c4e3f6c277ea. @rabauss Can you please test my changes?

**Comment by rabauss** [comment]
Now, I realized that the pid case is used in the articles treeview ;-)

Okay I did some tests with official demo database (+ copied root page):
a) in 4.4.32 the roots are not sorted
b) in 4.4.33 I get error because of ``ONLY_FULL_GROUP_BY``
c) in 4.4.x-dev everything is fine in the pageTree but in articleTree I'm not sure!

Just wondered while testing, why the root nodes are not shown anymore in the article list with filters.
Is that another issue? - but it's related to that topic!

The articleTree without filter - 'Contao Official Demo (DE)' root is sorted first!
![image](https://user-images.githubusercontent.com/14016098/51427474-b5f3bd80-1bf8-11e9-9f7c-a542277474b3.png)

With filters the root nodes are not shown and so the 'Home DE' (same sorting as 'Home') is randomly sorted before or after 'Home'. And all other DE nodes are mixed with the EN nodes related to the missing root sorting!
![image](https://user-images.githubusercontent.com/14016098/51427489-d459b900-1bf8-11e9-94fc-34411a5264c4.png)

In 4.4.32 the 'Home DE' is sorted after all EN nodes - I think that's better than all language nodes mixed, isn't it?

**Comment by leofeyer** [comment]
> Just wondered while testing, why the root nodes are not shown anymore in the article list with filters.
Is that another issue?

Yes, that is another issue. The root nodes do not have articles, therefore they do not show up in the results. And since the tree structure is no longer intact, the nodes cannot be sorted as tree anymore.
