### ISSUE TITLE
SitemapController returns 404 for root pages with empty hostname

### ISSUE THREAD

**Issue by ausi** [contao/contao#2692]
**Affected version(s)**

Contao 4.11-RC1

**Description**

In https://github.com/contao/contao/blob/ac8a518c3cdfddd1c67c12143a9684c2dab4449e/core-bundle/src/Controller/SitemapController.php#L41 we only search for root pages with matching host name. This fails for setups with an empty hostname.

If we find no matching root page, we should probably fallback to the root page with `dns = ''`.

**Comment by leofeyer** [comment]
@Toflar /cc

**Comment by Toflar** [comment]
We have the same in the `RobotsTxtListener`, don't we?

**Comment by ausi** [comment]
No, we use `findPublishedFallbackByHostname` there which checks for `dns = ''` explicitly. The `robots.txt` also worked correctly in the installation where I had the problem with the `SitemapController`

**Comment by Toflar** [comment]
See https://github.com/contao/contao/pull/2698
