### ISSUE TITLE
Multiselect in onsubmit_callback has data type string or array

### ISSUE THREAD

**Issue by oikodomo** [contao/contao#2695]
Contao Version 4.9.11 (Didn't had the oppotunity  to test it in other versions) / PHP 7.4.12

I have a mutliselect field in the dca. 
The dca has an onsubmit_callback. 
In the function associated with the onsubmit_callback the datatype of the multiselect field in the active record switches between a string(serialized array) and an array, _**depending if you change the value of the field or not.**_

**The multiselect field:**
`'test' => array
        (
            'label' => array("Test",""),
            'inputType' => 'select',
            'filter' => true,
            'sql' => "varchar(255) NOT NULL default ''",
            'options' => array("Opt1","Opt2","Opt3"),
            'eval' => array('mandatory'=>true, 'multiple'=> true,'chosen'=>true)
        ),`

**The onsubmit_callback:**
`'onsubmit_callback' => array(array('tl_test','onsubmit'))`

**The onsubmit function:**
`
public function onsubmit($dc)
 {  
      var_dump($dc->activeRecord->test);
}
`

**The result:**
When you change the value of the field => Array
`array(2) { [0]=> string(4) "Opt1" [1]=> string(4) "Opt2" }`

When you don't change the value of the field => serialized Array/String
`string(36) "a:2:{i:0;s:4:"Opt1";i:1;s:4:"Opt2";}"`

right now the workaround in my project is the following snippet:
`$opts= is_array($dc->activeRecord->test) ? $dc->activeRecord->test :  unserialize($dc->activeRecord->test);`

**Expectation:**
I think the expected behavior is that the datatype should be the same.
The discussion is which one of the datatypes it needs to be.
If this wont be changed, atleast there should be comment in the documentation, right?

**Comment by ausi** [comment]
> right now the workaround in my project is the following snippet:
> `$opts= is_array($dc->activeRecord->test) ? $dc->activeRecord->test : unserialize($dc->activeRecord->test);`

You could use `$opts = \Contao\StringUtil::deserialize($dc->activeRecord->test, true);` instead.

**Comment by aschempp** [comment]
I think this is a known limitation due to how DC_Table works. It has been like that forever, and what @ausi suggested works perfectly 😊
