### ISSUE TITLE
Fields without inputType don’t show up anymore

### ISSUE THREAD

**Issue by ausi** [contao/contao#2699]
**Affected version(s)**

Contao 4.11-RC1

**Description**

In #2568 we added the lines https://github.com/contao/contao/blob/4155cb4f7edce24be59a1bddff3ca216fb0e042f/core-bundle/src/Resources/contao/classes/DataContainer.php#L227-L230 which was wrong. Fields that use an `input_field_callback` instead of an `inputType` (like `tl_user.session` for example) don’t show up anymore.

I think we should replace these lines with something like this:

```php
if (!isset($arrData['inputType']))
{
	$arrData['inputType'] = null;
}
```

**Comment by leofeyer** [comment]
Good catch. 👍🏻
