### ISSUE TITLE
request.CRITICAL: Uncaught PHP Exception OutOfBoundsException XliffFileLoader.php

### ISSUE THREAD

**Issue by math-GH** [contao/contao#2700]
**Affected version(s)**

Contao 4.9.11

**Description**
While I am working on my extensions I get this error message in var/logs:
```
request.CRITICAL: Uncaught PHP Exception OutOfBoundsException: 
"Cannot load less than 2 or more than 4 levels in XLIFF language files." 
at /vendor/contao/core-bundle/src/Config/Loader/XliffFileLoader.php line 167 
{"exception":"[object] (OutOfBoundsException(code: 0): 
Cannot load less than 2 or more than 4 levels in XLIFF language files. 
at /vendor/contao/core-bundle/src/Config/Loader/XliffFileLoader.php:167)"} []
```
And I have no clue which file and/or which line is affected.

Is it possible to get more concrete information?

**Comment by fritzmg** [comment]
Use the debug mode and reproduce the error in order to get a stack trace.

**Comment by fritzmg** [comment]
This error happens in your [be_piwikcharts](https://github.com/mathContao/be_piwikcharts) extension. You are using more levels in your XLIFF files than are supported. e.g. [`MSC.be_piwikcharts.dashboard.live.headline`](https://github.com/mathContao/be_piwikcharts/blob/f240520702911cf264a922baa91a05ca8cc6280e/languages/de/default.xlf#L12) are 5 levels in total.

If you do want to use XLIFF files in the future, then you need to reduce the number of levels of these labels.

**Comment by math-GH** [comment]
> 
> 
> This error happens in your [be_piwikcharts](https://github.com/mathContao/be_piwikcharts) extension. You are using more levels in your XLIFF files than are supported. e.g. [`MSC.be_piwikcharts.dashboard.live.headline`](https://github.com/mathContao/be_piwikcharts/blob/f240520702911cf264a922baa91a05ca8cc6280e/languages/de/default.xlf#L12) are 5 levels in total.
> 
> If you do want to use XLIFF files in the future, then you need to reduce the number of levels of these labels.

it is still in progress. I try to investigate how XLIFF works.
Some of my questions/infos I posted in the forum: https://community.contao.org/de/showthread.php?80077-XLF-Dateien-richtig-generieren
