### ISSUE TITLE
thoughts on image-captions

### ISSUE THREAD

**Issue by asaage** [contao/contao#2707]
https://github.com/contao/contao/pull/2527 introduced the possibility for more than 255 characters per caption.
That applies only for tl_files - if you use tl_content (ce_image with overwrite metadata) you are still limited.
That could be annoying for some users.
Also the allowHtml for captions wich was fixed/reinroduced in https://github.com/contao/contao/pull/2199 is slightly user-unfriendly because there is no rt-editor in place.
Im not sure if raw is a lucky choice - new users might expect at least something like nl2br to insert linebreaks without writing html-tags.

**Comment by m-vo** [comment]
I agree that it's not very consistent.

I don't think a full-blown rich text editor is the right choice, though. From a HTML spec perspective, sure all [flow content is allowed](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption), so this would be fine. But in a CMS where all possible user input must also have a style counterpart this quickly escalates.

And yes, all of that is already possible just not advertised... I don't like the fact that we're allowing HTML by default and others might need the flexibility. For an editor not familiar with HTML, markdown is IMHO way easier to understand and can simply be replaced when rendering a template (e.g. see [markdown_to_html](https://twig.symfony.com/doc/3.x/filters/markdown_to_html.html) in Twig).

Nevertheless, some thoughts about an rte solution:
1. IMHO a limited subset of phrasing content like `<b>`, `<i>` or maybe `<br>` would be better suited as a default for allowed HTML elements in captions. I'm not sure if the tinyMCE can be stripped down to something like this?
2. Any new rte solution must not introduce paragraph wrappers around everything.
3. The solution also has to work in the `metaWizard` widget.

**Comment by asaage** [comment]
> I don't like the fact that we're allowing HTML by default

Me neither.

No TinyMCE here please - i really like the idea of markdown as it would allow for bolds, italics, and links (and even linebreaks in case of the text-area).

I guess it will be pretty difficult to migrate existing entries in tl_file though 🤔
