### ISSUE TITLE
Unknown News archive

### ISSUE THREAD

**Issue by markus361** [contao/contao#2710]
**Affected version(s)**

Contao 4.9.11

**Description**

I didn't check other Contao Versions, but you can reproduce it in the contao demo:

Go to News and create a new archive, don't fill out anything.
Go to Modules and for example the Newsreader
There should be a empty/unknown news archive to select

**Comment by aschempp** [comment]
Why should there be an empty news archive? You didn't fill anything, so the archive was not created (it was actually deleted again).

**Comment by markus361** [comment]
you can check the demo
![contao-news-archive](https://user-images.githubusercontent.com/8692619/106567455-2648af80-6532-11eb-872b-a175293d5be8.png)

**Comment by fritzmg** [comment]
This is a known limitation. The invalid entry will be deleted once you navigate to the news archives again.
