### ISSUE TITLE
File manager does not shows PNG files - PNG file broken after upload

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#2714]
Hi there,

i have a problem with Contao 4.9.9 and 4.9.10 file manager upload.
The Upload schows that the files are succesfully uploaded but in file tree exist no thumbnail. Also call with direct URL does not shows the png file. Screenshots are below.

![backend](https://user-images.githubusercontent.com/11348417/106882171-bb88a700-66de-11eb-85c4-3eb0ad595715.png)
![frontend-url-call](https://user-images.githubusercontent.com/11348417/106882179-bd526a80-66de-11eb-8e01-180154b548e7.png)
![DWS175](https://user-images.githubusercontent.com/11348417/106882208-c5120f00-66de-11eb-936f-2da4be6e3d79.png)
![file-upload](https://user-images.githubusercontent.com/11348417/106882444-0aced780-66df-11eb-8e8b-9262bc99d37d.png)

**Comment by fritzmg** [comment]
> Also call with direct URL does not shows the png file.

What do you see instead?

**Comment by havutcuoglu** [comment]
In chrome the screenshot with black border.
In Firefox URL as text.

**Comment by ausi** [comment]
What happens if you upload the image via SFTP?

**Comment by havutcuoglu** [comment]
With SFTP/FTP (Filezilla or CyberDuck) is everything fine. 
The problem happens only over the file manager.

**Comment by aschempp** [comment]
Can you please try to switch the uploader implementation in your user profile? Use the "Default uploader" instead of "DropZone".

**Comment by havutcuoglu** [comment]
I tried the default uploader also. It had the same effect.

**Comment by ausi** [comment]
Does this affect all files, or only PNGs? It would be great if you could try JPEGs, PDFs and TXTs too.

**Comment by havutcuoglu** [comment]
I tried JPG and PDF files. All of them works. It happen only with PNGs. I thought it happened because of transparent background or dimensions (px) or sizes (byte) . But it works for some PNGs and it doesn't work for some, with or without transparent background and the sizes or dimensions was also different.

**Comment by ausi** [comment]
> But it works for some PNGs and it doesn't work for some

But the same PNG file does reliably break all the time if you upload the same file again and again?

**Comment by havutcuoglu** [comment]
With the same file you get broken image, every times, again and again. You can upload it with FTP and than overwrite with Contao file manager, then you get again a broken file.

**Comment by ausi** [comment]
Can you please send these files to martin@contao.org ? The orignal PNG before uploading, and the broken PNG after the upload.

**Comment by havutcuoglu** [comment]
@ausi  I can't find the broken pictures. Because that problem, I loaded all the images via FTP. The broken ones was deleted.
I have now tried to reproduce it again so that I can send you the pictures, but the phenomenon is no longer there. The images can be uploaded as normal. With DropZone and default uploader.

But I can send you the original pictures with which I had problems. Do you want this pictures?

I do not get it. I tried it with several installations, as I did then, and the upload works for all. I 

![Bildschirmfoto 2021-04-08 um 09 59 11](https://user-images.githubusercontent.com/11348417/113990048-5a519100-9851-11eb-85ec-5c3400c29b91.png)

**Comment by ausi** [comment]
> But I can send you the original pictures with which I had problems. Do you want this pictures?

No, I would need both images, the broken one and the original, in order to be able to compare them.

Maybe it was an issue with the webserver that your hosting provider has fixed in the meantime.

**Comment by havutcuoglu** [comment]
I was just surprised that the problem occurred with all Contao installations. It was the same with my colleagues. Of course we all work on the same server. Maybe it was really down to the web server.

I apologize for the unnecessary issue and thanks for your support.
