### ISSUE TITLE
Priority for app routes

### ISSUE THREAD

**Issue by aschempp** [contao/contao#2718]
**Affected version(s)**

Contao 4.9+

**Description**

Because app routes (`/config/routing.yml` etc.) are automatically registered by the `contao/manager-bundle`, these routes are sorted on the same position the bundle is - based on bundle dependencies. This usually means they will be sorted after any extension. Be aware that for routes, the bundle dependency order is **inverted** to allow a bundle to override its dependency. However, if I have an extension that adds routes (like our `terminal42/contao-url-rewrite`), it's routes are sorted before the app routes.

Symfony added route priority in 5.1 (https://github.com/symfony/symfony/pull/35608). Though for annotations only, this might help most people adding custom routes in a controller. We could _also_ use this to manipulate the priority (e.g. set it to 99) of the `routing.yml`. However, that won't work with Contao 4.9 for now.

FYI I was able to solve this locally by not using a `routing.yml` but add a Contao Manager Plugin and load the routes myself. Not very convenient though, but maybe that could be a (temporary) solution for the (quite unlikely case) of this being an issue.

**Comment by leofeyer** [comment]
As discussed in the Contao call, this is a long running issue that @aschempp wants to work on in the future.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5790. The fix was really simple 😆
