### ISSUE TITLE
DCA filter for dates on MySQL 8

### ISSUE THREAD

**Issue by danielkochengineer** [contao/contao#2719]
**Affected version(s)**

Contao 4.9
MySQL 8.0.22

**Description**

At first I define a DCA field using filtering together with flag 5-10 (Sort by day/month/year ascending/descending). The field dateAdded stores timestamps like 1612884329.

`
  'dateAdded' => array
  (
    'filter' => true,
    'flag' => 8,
    'sql' => "int(10) unsigned NOT NULL default 0"
  )
`

Now I filter on top of the dca page the dateAdded "01.2021". This throws an error: Error message: Invalid date "1612134000.000000". I think MySQL 8 changed the UNIX_TIMESTAMP method to return a decimal format instead of an integer format. Now it stores the seconds after the dot. (I found this, but it is not a bug on MYSQL side: https://bugs.mysql.com/bug.php?id=82070). Is this a bug or incompatibility to MySQL 8 or did we do a wrong dca configuration?

**Comment by ausi** [comment]
I think we should probably change the `UNIX_TIMESTAMP()`s in https://github.com/contao/contao/blob/0e921de6bc8ed7c770f9fb8a66f3ffee2be09408/core-bundle/src/Resources/contao/drivers/DC_Table.php#L5671-L5686 to something like this:

```php
$what = "IF($what!='', FLOOR(UNIX_TIMESTAMP(FROM_UNIXTIME($what , '%%Y-%%m-%%d'))), '') AS $what";
```
