### ISSUE TITLE
AbstractContentElementController only finds global templates

### ISSUE THREAD

**Issue by bohnmedia** [contao/contao#2720]
**Affected version(s)**

Contao 4.9

**Description**

It seems, AbstractContentElementController can only find templates when they were defined globally.

I created a content element based on this example.
https://docs.contao.org/dev/framework/content-elements/

```php
// src/ContentElement/Color.php

namespace BohnMedia\ColorElementBundle\ContentElement;

use Contao\ContentModel;
use Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController;
use Contao\CoreBundle\ServiceAnnotation\ContentElement;
use Contao\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @ContentElement(category="media")
 */
class Color extends AbstractContentElementController
{
    protected function getResponse(Template $template, ContentModel $model, Request $request): ?Response
    {
        $template->style = 'background-color:#' . $model->color;
        return $template->getResponse();
    }
}
```

I added the option to set a custom template in the dca.

```php
// src/Resources/contao/dca/tl_content.php

$GLOBALS['TL_DCA']['tl_content']['palettes']['color'] = '{type_legend},type,headline;{color_legend},color;{template_legend:hide},customTpl;{protected_legend:hide},protected;{expert_legend:hide},guests,cssID;{invisible_legend:hide},invisible,start,stop;';

$GLOBALS['TL_DCA']['tl_content']['fields']['color'] = [
    'exclude' => true,
    'search' => true,
    'inputType' => 'text',
    'eval' => ['tl_class'=>'w50', 'maxlength'=>6, 'mandatory'=>true, 'colorpicker'=>true],
    'sql' => "varchar(6) NOT NULL default ''"
];
```

I can change to another template (ce_color--small) without problems, when it was defined globally. When I move the template into the template directory of the theme, it is still visible in the custom template select box, but when I select it and load the page I get the following error.

> Could not find template "ce_color--small"

Best regards
Dennis

**Comment by fritzmg** [comment]
> but when I select it and load the page I get the following error.

I assume you mean in the back end? I can only reproduce that error in the back end. The front end works as expected.

**Comment by fritzmg** [comment]
This error does not happen for legacy content elements, because their template is defined via their `protected $strTemplate;` property, which is then used in `ContentElement::generate()`: `$this->Template = new FrontendTemplate($this->strTemplate);`.

`AbstractFragmentController::createTemplate` should only apply the `customTpl` of the model in the front end, I suppose.

**Comment by fritzmg** [comment]
PR: https://github.com/contao/contao/pull/2721

**Comment by bohnmedia** [comment]
Sorry, you are right. I got the error only in backend.

Thank you for the fix.
