### ISSUE TITLE
mod_navigation template

### ISSUE THREAD

**Issue by asaage** [contao/contao#2729]
Can we replace this ```<a>``` here in [mod_navigation.html5](https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/templates/modules/mod_navigation.html5#L13) with ```<span>``` or something other in the long run?
Or just add ```href="#"```?
Lighthouse complains about a not-crawlable link because there is no href.
Could not find a finite answer if href is mandatory here by spec - span should be save i guess...

**Comment by ausi** [comment]
>  Could not find a finite answer if href is mandatory here by spec

According to the w3c validator href is not required: https://validator.w3.org/nu/#textarea

Browsers explicitly style `<a>` differently to `<a href>` so I think this should be fine.

>  Lighthouse complains about a not-crawlable link because there is no href.

How exactly does it complain?

**Comment by asaage** [comment]
![image](https://user-images.githubusercontent.com/4138336/107678510-c7a2d480-6c9b-11eb-80ad-9e9abbc22465.png)
mentioning this:
https://developers.google.com/search/docs/advanced/guidelines/links-crawlable?visit_id=637486633971133260-2872417503&rd=1

**Comment by m-vo** [comment]
Btw. the same is also reported for all links with an empty href (`href=""`) which in fact **is** a valid reference to the current document. So, IMHO this check is overspecific...

**Comment by asaage** [comment]
> IMHO this check is overspecific...

yes - it's just a tool and i don't realy care either

href = optional https://www.w3.org/MarkUp/1995-archive/Elements/A.html

by the way i can make this message go away and still use ```<a>``` without href
if i do
```diff
---<a id="skipNavigation123" class="invisible">&nbsp;</a>
+++<a name="skipNavigation123" class="invisible">&nbsp;</a>
```
just for the record 😉

**Comment by ausi** [comment]
But the validator doesn’t like that 😅

<img width="887" alt="Bildschirmfoto 2021-02-11 um 19 51 15" src="https://user-images.githubusercontent.com/367169/107684025-8eba2e00-6ca2-11eb-80bb-3c41579b5aaf.png">

**Comment by leofeyer** [comment]
I'd be fine with replacing the `<a id="…" class="invisible">` with another element as long as it works.

**Comment by Toflar** [comment]
> Could not find a finite answer if href is mandatory here by spec - span should be save i guess...

`<a>` does not require an `href` attribute. Here's your spec: https://html.spec.whatwg.org/multipage/links.html#links-created-by-a-and-area-elements (green note box)

**Comment by leofeyer** [comment]
As discussed in Mumble on May 12th, the markup is valid and therefore we do want to change it.

**Comment by Aybee** [comment]
> As discussed in Mumble on May 12th, the markup is valid and therefore we do want to change it.

Typo: ... we do NOT want to change it ...
