### ISSUE TITLE
array_replace_recursive in applyLegacyTemplateData

### ISSUE THREAD

**Issue by ausi** [contao/contao#2730]
**Affected version(s)**

Contao 4.10

**Description**

I think we should check if the recursive part is really needed here https://github.com/contao/contao/blob/d381a110efbc704e9793e229e98a9c0dffd16717/core-bundle/src/Image/Studio/Figure.php#L360

/cc @m-vo

**Comment by m-vo** [comment]
See #2731 

Indeed, that bit was a mistake/not necessary. Tests are fine without it and everything seems fine in one of my installations.
