### ISSUE TITLE
Search should only work for keywords longer than 2/3 characters

### ISSUE THREAD

**Issue by fatcrobat** [contao/contao#274]
**Affected version(s)**

3.5-4.6

**Description**  

Contao search currently does not have a declared minimum character length for search keywords. On websites with a large amount of news and pages (big tl_search and tl_search_index tables) a search for keyword with less than 3/4 characters will slow down the database. Elasticsearch for instance also has a 4 character minimum limit by default. (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-term.html)

**How to reproduce**  

If you search for instance for the following search term:

"vob a 2019" with enabled fuzzy search than you will have 3 search keyword:

- vob
- a 
- 2019

**Comment by leofeyer** [comment]
As discussed in Mumble on February 14th, we want to strip keywords that deceed a configurable minimum length. Also, the search results shall show a hint if keywords have been stripped.

**Comment by leofeyer** [comment]
On second though, we should probably not even index words that deceed the minimum length in the first place. So the DB is not bloated with keywords that will never be found.

@contao/developers WDYT?

**Comment by Toflar** [comment]
Indexing and searching are two separate disciplines so I think we should keep that as is for now. 
Might be that you want to have different configurations for different root pages but the index stays the same.

**Comment by leofeyer** [comment]
Implemented in a16279bcfb240af64f27c8b519ef4da91731bfba.
