### ISSUE TITLE
Handling of disabled form fields

### ISSUE THREAD

**Issue by webdecker** [contao/contao#2741]
**Affected version(s)**

Contao 4.9.11

**Description**

Hello,

I know, there have been similar issues, but I think not exactly...

If a form field (frontend) is disabled and has already a value, it should not fill the value by request value but keep the preset value.

Use case: I have a contact form in frontend and if a user is logged in I prefill some fields with user data (lastname, email, ...) and set it to disabled via loadFormField hook.
I want to send the contact form with complete data after successful submission via email to the administrator.
But when I submit the form, the mandatory validation of those disabled fields fail because / and those fields are empty - because the browser (Chrome) does not send the disabled field values.

Suggestion: in validation process, where form field is to be filled: if field is disabled and value not empty then do not override its value by request value (null).
Like this in Widget: public function validate() { if ($this->disabled && $this->varValue) return; /* ... */ }
If this check is done a user may manipulate the request values of the disabled fields but they won't be processed.

**Comment by m-vo** [comment]
You should IMHO set your data programmatically when submitting the form so that you can be sure it's correct. And then just adapt rendering.

You could also use two different forms for this use case.

**Comment by aschempp** [comment]
A widget that is disabled should not be validated at all. Maybe your configuration is coming too late or that's a bug?

**Comment by baumannsven** [comment]
@webdecker
Here is an idea for you. You use a hidden input with the same name. This should come before the deactivated one. And the hidden field become the same value too.

**Comment by webdecker** [comment]
Hello together,

thank you for dealing with this topic.

@m-vo: setting the data twice is what I want to avoid, since in processFormData hook data is usually validated and could be saved, normally I count on that fact. Two different forms is overhead that I like to avoid as well.

@aschempp: Disabled fields / widgets are filled and validated in Form class anyway (call of $objWidget->validate()). If there is no value in Input, then the field is empty and mandatory validation fails.

@baumannsven: Hidden fields would solve my current problem, yes, I thought about that and I will probably do so in my current project.
I even thought about replacing the disabled fields by an explanation field showing the value that is not supposed to be changed, but in this case I would have to retrieve and set the value again in processFormData...


I think, if there is a field in a form, it (and/or $arrSubmitted) should contain a value in processFormData if it was set before and has not been overridden by Input.

So what do you think about my suggestion of not setting and validating a field's value if it already has one and is disabled?
Sure, this mechanic has to rely on the value being valid, but this is my problem if I use it this way.

**Comment by m-vo** [comment]
Do you really need the form generator? This would be easier with programmatically generating the form - e.g. with Symfony forms. 

Alternatively, you could also write your own widget for the name.

**Comment by asaage** [comment]
Disabled form field's not beeing sent by the browser is essential.
What you are looking for is probably the attribute **readonly**.
https://wiki.selfhtml.org/wiki/HTML/Formulare/ausgrauen_mit_readonly,_disabled#readonly_vs._disabled

**Comment by m-vo** [comment]
And still: relying on the data the browser sends is a bad idea.

**Comment by webdecker** [comment]
@m-vo: "easier with symphony forms"??? You have to know, how this is done... I don't know. ;-) I'm still working with contao, and the form generator ist a good thing to integrate a simple contact form which sends the data to the admin via email. 
@assaage: readonly sends the data, yes, but the contact form does not render it into the email... :(
@m-vo: I was never talking about relying on the data the browser sends. I was talking about a value I set programmatically to the input field and processing the data after validation...

So I will probably do it by re-filling the fields... :|

**Comment by asaage** [comment]
> readonly sends the data, yes, but the contact form does not render it into the email

That sounds like a bug to me (on the other hand there are no checkboxes in the formgenerator for those attributes so it might not be a bug).

**Comment by aschempp** [comment]
> Disabled fields / widgets are filled and validated in Form class anyway (call of $objWidget->validate()). If there is no value in Input, then the field is empty and mandatory validation fails.

Contao set the `blnSubmitInput` flag to `false` (https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/library/Contao/Widget.php#L302). However, I'm not sure why disabled fields are still processed in https://github.com/contao/contao/blob/991282912ef0c590b92d25b67785463516a38890/core-bundle/src/Resources/contao/forms/Form.php#L208-L231, maybe that's actually a bug? @contao/developers

**Comment by webdecker** [comment]
It's different / twofold... Don't know whether bug or feature...


$blnSubmitInput is set to false if widget is set to disabled or readonly. Hence, $arrSubmitted passed to processFormData won't contain the widget's value.

If widget is readonly, browser sends a value, widget collects it. If $blnSubmitInput would then be true, the values would be passed to processFormData().

But if widget is disabled, browser sends no value, then widget contains no value - even if it had been set a value before via loadFormField(), because it is overridden with NULL in Widget::validate(). Even if  $blnSubmitInput would be true, there would be no value in $arrSubmitted / processFormData()!


The general question is, for what purposes disabled or readonly widgets are used and what should happen on submit, especially if widget has a value. 
The frontend view is clear, user should not alter the data, it is just for display current data.
On submit: should the form collect and pass only (validated) data that was sent by the browser or should the form collect and pass (validated) data for all widgets?
I guess there are good reasons for both.

What is to be said against the suggested solution: In widget's validate-method: If a widget has a value and is disabled (or readonly?), its value is not overridden by NULL (missing input) and $blnSubmitInput is set to true.
So the widget would contain valid data (because programatically set) and its data would be passed to further processing. 

Like this: Widget: 
```
public function validate() {
	if ($this->disabled && $this->varValue) {
		$this->blnSubmitInput = true; 
		return;
		/* so  $this->varValue remains as it is */ 
	} 
	/* ... codes as is ... */
}
```

Do I miss any problems or drawbacks?

**Comment by leofeyer** [comment]
> However, I'm not sure why disabled fields are still processed in

I guess it is because of #2383.

**Comment by webdecker** [comment]
In #2383 it is said "we are now calling submitInput() before calling validate()".
But this issue refers to DataContainer, not (yet?) to Form (which is the focus here).

By the way, why does Password::validator() actually return '*****' and not $this->varValue (TextStore similar)? If it would return $this->varValue there would be no need to change blnSubmitInput and the whole process... (and it could be saved into database because it is supposed to be the same value as before).

Isn't it all the same? Wouldn't it be an idea to leave $this->varValue unchanged if not empty and if widget/field is disabled, readonly, or - for password/textstore case - if input is '*****' or ''?
