### ISSUE TITLE
[4.9.X] - Porting the UserCreateCommand class

### ISSUE THREAD

**Issue by katgirl** [contao/contao#2745]
Please provide the User CreateCommand class in 4.9.X. In 4.9.11 it works without any problems

see 72c8a9b

> You can do this in an extension/your application. 4.9 is feature complete, so there won't be new ones.
see https://github.com/contao/core-bundle/issues/1720

The next LTS version will not come until 2022. I don't think it's good to build an extension for the Contao console just to use the function that is already included in 4.10. Especially since I don't understand why the Contao console is not a separate package that can be installed independently of the Contao version. Because the extension of the console, the manager and the API should not necessarily depend on the core.

**Comment by richardhj** [comment]
Maybe this is a reason to use the new version? 
New features belong to new versions. LTS does not imply innovation but security.

**Comment by m-vo** [comment]
> Especially since I don't understand why the Contao console is not a separate package that can be installed independently of the Contao version

Because it's part of the Symfony full stack framework. The Contao bundles "just" add some more commands. They are already tied to the respective packages (e.g. `contao:install-web-dir` from the manager bundle or `contao:cron` from the core bundle).

Edit: just to be clear - the `contao-console` binary from the managed edition really is a `symfony/console` application running with the `ContaoKernel`.

**Comment by fritzmg** [comment]
As already said, new features are only released in new feature versions as per semantic versioning that Contao adheres to. If you need a new feature, that newer versions of Contao provide, then you simply need to install those versions.

> I don't think it's good to build an extension for the Contao console just to use the function that is already included in 4.10.

Why not? See https://packagist.org/packages/ausi/contao-slug-backport for example. And there are more examples (also from myself/inspiredminds).

**Comment by richardhj** [comment]
I guess you can create a PR at [contao-community-alliance/contao-polyfill-bundle](https://github.com/contao-community-alliance/contao-polyfill-bundle/). They are likely happy to merge.
