### ISSUE TITLE
Errors are not displayed - display_errors 

### ISSUE THREAD

**Issue by tarun-uwe** [contao/contao#275]
**Affected version**
Contao 4.6.9

**Description**  
We don't get error messages shown. When we display our `phpinfo()` via Contao Manager Popup or via File on any Contao page, we get the info, that `display_errors = Off`. The option in our php.ini is activated and if we view `phpinfo()` in a separate file we get the expected `display_errors = On`.

Initially, I thought this issue https://github.com/contao/core-bundle/issues/1422 was responsible, but we don't get errors in app nor in app_dev. When we add  `ini_set('display_errors', '1');` right in our SomeModule.php we get error messages shown, but is that the wanted way?

**Hoster**
WebGo

Thanks in advance.

**Comment by leofeyer** [comment]
> Initially, I thought this issue contao/core-bundle#1422 was responsible

That was my initial thought as well. Have you tried removing the following line?

https://github.com/contao/contao/blob/e8d634947be528585c72aac9281b2f9c9d3581c3/manager-bundle/src/Resources/skeleton/web/app.php#L19

Then there is also the `contao.error_level` parameter. Did you modify it?

https://github.com/contao/contao/blob/e8d634947be528585c72aac9281b2f9c9d3581c3/core-bundle/src/DependencyInjection/Configuration.php#L101-L105

**Comment by tarun-uwe** [comment]
Thanks for answers, we tried it and figured out that it wasn't a Contao problem but the server itself crashed and couldn't generate an error.

Thanks again and Sorry for the trouble. 

Additional Info: When we made an error by choice we got an error message. 
But even with that line removed, phpinfo() was showing display_error = Off. Strange but not important.

**Comment by leofeyer** [comment]
> Thanks again and Sorry for the trouble.

You are welcome.
