### ISSUE TITLE
Keep migration_versions when migrating

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2760]
**Affected version(s)**

Contao 4.11

**Description**

Now that we dropped the schema filter, the `contao:migrate` command will offer to drop the `migration_versions` table that keeps track of those migrations executed via `doctrine:migration:migrate`. This is because this table doesn't have any associated metadata. IMHO we should have a look how doctrine handles this case and exclude it as well.

**Comment by aschempp** [comment]
I think `contao:migrate` and Doctrine migrations are not supposed to be used together.

**Comment by aschempp** [comment]
Maybe we should even go as far as to disable `contao:migrate` if Doctrine migrations are installed?

**Comment by fritzmg** [comment]
> Maybe we should even go as far as to disable `contao:migrate` if Doctrine migrations are installed?

How would you then run any [Contao Migrations](https://docs.contao.org/dev/framework/migrations/)?

**Comment by m-vo** [comment]
I think these two things can happily coexist. 

For prototyping or migrating certain things on the server I prefer doctrine migrations: For example whenever a manual migration would not work due to missing default values or constraints or when moving data across columns. No need for a service there and trying to find a good `shouldRun` condition (IMHO). Also you can drop them later on in the development process.

For simple updates, I prefer our migrate command (no need to setup a migration file). Also for all the managed migrations from the core and extensions we need that anyway.

**Comment by aschempp** [comment]
When I used Doctrine Migrations before, I wanted to make sure I know (and commited to GIT) what would happen on my database. This does not really work with Migrations, as I can't control them. I often did use Contao Migrations for anything that needed to be migrated in the database, and I agree it would be easier if it was stateful (like Doctrine). Maybe that's just a feature we can add to "get rid" of Doctrine migrations?

**Comment by m-vo** [comment]
Just thinking: In case you're using doctrine migrations (e.g. when adding Contao to a regular Sf application) you could ideally execute run once files and other Contao migrations from within a migration (where `shouldRun` would effectively be `true`). But I never had the need for this tbh - the managed solution was fine for almost every case.

I'm not sure it's worth replicating all of the logic of doctrine migrations (like migrate up/down) and the infrastructure around it (like `make:migration`) but IMHO there are still valid use cases for these things in a Contao application where you 'own' the data structures.

**Comment by Toflar** [comment]
Imho they must coexist! If I'm using Doctrine migrations for my app and install Contao as a bundle, I still want to be able to run Contao migrations. Also for potential extensions I'm installing.
Imho the solution to this problem is that there should be an option where I can configure `contao:migrations` in such a way, that it ignores a given list of tables. Then I can use 10 different migration systems if I want to.

**Comment by aschempp** [comment]
Shouldn't it rather ignore (or offer an option to ignore) database migrations completely and just execute the built-in migrations?

**Comment by Toflar** [comment]
Yeah something like that might be fair as well.

**Comment by ausi** [comment]
There is already a `--schema-only` option, so the new option would basically be the opposite? How should we call it, `--ignore-schema`, `--without-schema`, `--no-schema`?

**Comment by m-vo** [comment]
The 'coded ones' could also alter the schema, so this could be misleading. :thinking: 

Could it be `--schema-only` vs `--<x>-only` with `<x>` being sth. like migrations/programmatic/framework/…?

**Comment by aschempp** [comment]
It would rather be `--migrations-only` to me

**Comment by ausi** [comment]
I think `--migrations-only` can be confusing. Schema updates are migrations too IMO. And runonce files get executed also.

**Comment by aschempp** [comment]
schema updates are schema, not migrations? All of these are "database changes", but a schema update is not migrating anything (except by accident).

**Comment by ausi** [comment]
Should we vote?
👍 for `--migrations-only`
👎 for `--skip-schema`

**Comment by Toflar** [comment]
I cannot really vote on that so I marked it as up for discussion :D

**Comment by leofeyer** [comment]
As discussed in Mumble on April 8th, we want to call the flag `--migrations-only`.

**Comment by ausi** [comment]
Closed in favor of #2945
