### ISSUE TITLE
Warning: array_merge(): Expected parameter 2 to be an array, null given

### ISSUE THREAD

**Issue by xchs** [contao/contao#2761]
**Affected version(s)**

Contao 4.10.7

**Description**

I am getting the following warning message when I run a `composer update` on command line (or via Contao Manager):
```console
In AddAvailableTransportsPass.php line 29:

  Warning: array_merge(): Expected parameter 2 to be an array, null given


Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred while executing the "cache:clear --no-warmup" command:
  In AddAvailableTransportsPass.php line 29:

    Warning: array_merge(): Expected parameter 2 to be an array, null given
```

![image](https://user-images.githubusercontent.com/1218766/108130478-05469980-70b0-11eb-9878-828799b7bde6.png)

It is a vanilla Contao installation without any extensions.

**Comment by m-vo** [comment]
Did you configure any mailer transports and if so how does your config look?

**Comment by xchs** [comment]
> Did you configure any mailer transports and if so how does your config look?

Thank you. You're right. There was actually a missing `#` in the `config.yml` file:
```yaml
# Contao configuration
contao:
#    prepend_locale: true
```
instead of
```yaml
# Contao configuration
# contao:
#    prepend_locale: true
```
