### ISSUE TITLE
GitHub pipeline: Automatic Review Apps for PRs

### ISSUE THREAD

**Issue by richardhj** [contao/contao#2770]
I propose to enable automatic review apps for the contao/contao monorepo.

The idea
---------

The idea is to implement a [Heroku](https://heroku.com) pipeline which triggers builds of containerized apps on pushes inside PRs.

Those review apps become handy for reviewing code changes (i.e. changes on the CSS, new content elements, new features, e.g. twig support, etc.pp.).

How it works
-------------

For each PR, Heroku triggers the build of the app. The build will wait until the CI turns green. This saves some time and encourages fixing the tests.

GitHub will link the app inside the PR. It'll look like this:

<img width="953" alt="Screenshot 2021-02-17 at 20 25 49" src="https://user-images.githubusercontent.com/1284725/108256947-69279b80-715e-11eb-83e9-eca71cdc261a.png">

The pipeline will install a Contao application with the current state of the monorepo. We, however, need to provide a database. I thought of importing the Contao demo, or, loading Doctrine fixtures, or, using the YML-Fixtures from the functional tests.
The least we can do is to run the `contao:migrate` command which will make the Contao installation accessible.

When using fixtures, we can encourage contributors to write new fixtures for each new feature.
 
The database is persistent during the lifetime of the PR (except we decide to load fixtures, which usually purges the database). So you can easily build your test-case inside the review app to demonstrate your changes.

Set-up
-------

The setup is straightforward.
1. Register on Heroku.
2. [Link Heroku-Account with GitHub-Repo](https://devcenter.heroku.com/articles/github-integration#enabling-github-integration) (we should use a machine account for that).
2. Move this repo to the Contao namespace: https://github.com/richardhj/heroku-buildpack-contao
3. Create the [app.json](https://github.com/richardhj/heroku-buildpack-contao#usage) in the root of the Contao monorepo.
4. Set-up pipeline in Heroku dashboard.

Heroku has a free tier of 1000 hours/month. An app is active for 30 minutes before it turns off due to inactivity. This means we can make use of review apps about 2000 times a month (I know, this calculation has its flaws 😄)

This issue is "up for discussion".

**Comment by aschempp** [comment]
I generally like the idea, I think we discussed this before. However, there are a few problems:

1. 99% of the pull requests won't need an app, so "automatically" creating one seems very much overkill to me. _Please consider the environment before print… eh... creating a useless instance_ 😆 
2.
    > Heroku has a free tier of 1000 hours/month. An app is active for 30 minutes before it turns off due to inactivity. This means we can make use of review apps about 2000 times a month (I know, this calculation has its flaws 😄)

    Being available for 30mins is useless to any reviewer, because it's unlikely we'll check the issue that quickly. It would only be useful if created on demand or for the PR developer to review.
3. Also, what about push updates to the PR? Would that create another instance yet again? I often commit & push multiple times within minutes…

**Comment by richardhj** [comment]
>  1. 99% of the pull requests won't need an app, so "automatically" creating one seems very much overkill to me. _Please consider the environment before print… eh... creating a useless instance_ 😆

If we filter out all PRs except tagged with "feature" that might be a good fit. I'll get to know if this works.

>  2. Being available for 30mins is useless to any reviewer, because it's unlikely we'll check the issue that quickly. It would only be useful if created on demand or for the PR developer to review.

It's rather the case that the instance goes sleeping and will re-boot when demanded (i.e. accessing the link). The same instance with the same database state.

>  3. Also, what about push updates to the PR? Would that create another instance yet again? I often commit & push multiple times within minutes…

This triggers a re-build of the instance (available under the same link). This allows to re-load fixtures as well (if it makes sense). However, the build waits until the build pipeline turns green. It's rare that someone pushes perfectly green commits in a row 😆

**Comment by m-vo** [comment]
It would be nice if we'd had a stripped down demo application that only consisted of fixtures. :+1: 

E.g. a `contao/demo-fixtures` bundle that is part of the mono repo and gets installed in the 'app review CI'. This bundle could be updated when implementing new features and would always reflect the state of the current release/branch. Not sure it's really worth the effort to maintain but would probably also open up a new sector of testing (FE).

**Comment by leofeyer** [comment]
As discussed in Mumble on April 8th, we do not want to extend the CI chain in this direction right now, because it will increase the maintenance effort for something that will only provide added value in very few cases. The CI chain already fails often enough. 🙈
