### ISSUE TITLE
Contao 3 extensions cannot be installed

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2773]
**Affected version(s)**

Contao 4.11

**Description**

Currently Contao 3 extensions cannot be installed in Contao 4.11 due to the following error:

```
15:20:47 CRITICAL  [console] Error thrown while running command "--ansi". Message: "An error occurred while executing the "php.exe vendor/contao/contao/manager-bundle/bin/contao-console cache:clear --no-warmup --env=dev --ansi" command:
In ContaoKernel.php line 94:

  Notice: Undefined property: Contao\ManagerBundle\HttpKernel\ContaoKernel::$rootDir
```

_Note:_ my error reporting level is the PHP default, i.e. `E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED`:

```
$ php -r "echo error_reporting();"
22519
```
```
$ php -r "echo E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED;"
22519
```

This happens because Symfony removed `Kernel::$rootDir` in Symfony 5. I am not sure what the best way to fix this is though. Either:

1. Add `protected $rootDir;` to [ContaoKernel](https://github.com/contao/contao/blob/698b72bf2f10f2b0302eff7ad2ae2f8826c0f37f/manager-bundle/src/HttpKernel/ContaoKernel.php).
2. Change the [`ContaoKernel::getRootDir`](https://github.com/contao/contao/blob/698b72bf2f10f2b0302eff7ad2ae2f8826c0f37f/manager-bundle/src/HttpKernel/ContaoKernel.php#L73-L80) method to not use `$this->rootDir`, since it is not available anymore.
3. Remove `ContaoKernel::getRootDir` completely (not possible due to BC I guess).
4. Change [`ModuleConfig::getBundleInstance`](https://github.com/contao/manager-plugin/blob/56e5ef9690c4c954698d74ad2f3748b6a8c9a739/src/Bundle/Config/ModuleConfig.php#L33-L38) to:

```php
public function getBundleInstance(KernelInterface $kernel)
{
    return new ContaoModuleBundle($this->name, $kernel->getProjectDir());
}
```

or

```php
public function getBundleInstance(KernelInterface $kernel)
{
    $dir = method_exists($kernel, 'getProjectDir') ? $kernel->getProjectDir() : $kernel->getRootDir();

    return new ContaoModuleBundle($this->name, $dir);
}
```

**Comment by aschempp** [comment]
That's very unfortunate. We actually tried to be forward-compatible with this, but forgot about the property.

1. That would work, but not ideal to override
2. Probably our best shot. Wouldn't allow to override `$rootDir` anymore, but I don't see a use case for that
3. Certainly not possible as long as we're supporting Symfony 4, because the default `getRootDir` method wouldn't work
4. Only works if the `manager-plugin` is only compatible with Contao 4.9.4+, but we don't want to enforce that

**Comment by qzminski** [comment]
I have just experienced this problem. Let me know if you need a testing environment.

**Comment by fritzmg** [comment]
A fix is already ready: https://github.com/contao/contao/pull/2774

**Comment by qzminski** [comment]
Right, I have noticed it right after submitting my comment 🤦

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2774
