### ISSUE TITLE
404 error for Folder URLs without 'URL suffix'

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#2775]
**Affected version(s)**

Contao 4.11

**Description**

After updating to Contao 4.11, Folder URLs return 404 error [when URL's suffix is empty]. 

https://domain.com                      => OK
https://domain.com/about            => OK
https://domian.com/about/ceo     => error 404

When URLs suffix is changed to '/' or '.html' or something else, everything works properly.

https://domain.com/about.html            => OK
https://domian.com/about/ceo.html     => OK
or
https://domain.com/about/            => OK
https://domian.com/about/ceo/     => OK

Don't matter legacy_routing is false or true.

This website is hosted in Cpanel Server (Couldlinux with Litespeed [PHP info](https://mahanpt.com/info.php)). This problem don't occur in my local Contao installtion (php 7.4 and apache v2.4).

**Comment by ausi** [comment]
I can confirm this issue. I get an `UnusedArgumentsException`: `Unused arguments: auto_item` thrown in https://github.com/contao/contao/blob/9fc3041d7833e35c8a3812ca0954a857b24441fd/core-bundle/src/Resources/contao/classes/FrontendTemplate.php#L143

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2784
