### ISSUE TITLE
Using contao-setup with different PHP versions

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2776]
**Affected version(s)**

Contao 4.11

**Description**

Please see https://github.com/composer/composer/issues/9707 for the original issue. I had used the symfony binary to test different PHP environments but apparently this makes a difference. :unamused: 

Here are some ideas how we could deal with this problem until (hopefully) there is a fix or workaround in Composer:

1. Make the info message suggest `@php vendor/bin/contao-setup` instead of `contao-setup` with `/` being `\` when running on windows. 
1. Create a symlink to `contao-console` in the root directory. :see_no_evil: 
1. …?

Ideas are welcome - here as well as in the Composer issue.

**Comment by m-vo** [comment]
There is something happening. :heart: 

With https://github.com/composer/composer/commit/057006da4fbfab0241cdcdccce1ff676bedfcb63 + https://github.com/composer/composer/pull/9713 we should be able to safely switch to `@php vendor/bin/contao-setup`.

**Comment by aschempp** [comment]
@m-vo this issue can be closed then, right?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2796
