### ISSUE TITLE
Unable to setup a "Weiterleitungsseite" for (News, Forms, FAQ, Events,...)

### ISSUE THREAD

**Issue by PowerNow** [contao/contao#2787]
**Affected version(s)**

Contao 4.10.1 - Contao 4.10.7?

**Description**

Hi, since today I'm not able to setup a "Weiterleitungsseite" for (News, Forms, FAQ, Events,...). If I press on the "Auswahl ändern" Button I'm getting the following server error:

```
TypeError:
preg_replace(): Argument #3 ($subject) must be of type array|string, null given

  at vendor/contao/core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107
  at preg_replace()
     (vendor/contao/core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107)
  at Contao\CoreBundle\EventListener\DataContainer\ContentCompositionListener->renderPageArticlesOperation()
     (vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:804)
  at Contao\DataContainer->generateButtons()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:4028)
  at Contao\DC_Table->generateTree()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:3628)
  at Contao\DC_Table->treeView()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:353)
  at Contao\DC_Table->showAll()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:644)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:48)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:31)  
```   
I have only installed the newest version (3.1.16) of "Sprachwechsler" modul and had until now no problems. Have someone an idea what is going wrong here?
Thxs...

**Comment by m-vo** [comment]
IMHO this gets fixed by #2785

**Comment by fritzmg** [comment]
> I have only installed the newest version (3.1.16) of "Sprachwechsler" modul and had until now no problems.

May be the problem can be reproduced this way though. I'll check later today.

**Comment by PowerNow** [comment]
I have just deinstalled the "Sprachwechsler" modul but unfortunately no change.

**Comment by fritzmg** [comment]
@PowerNow create a file called `contao/dca/tl_page.php` with the following content:

```
<?php

dump($GLOBALS['TL_DCA']['tl_page']['list']['operations']);
```

then rebuild the application cache and then reproduce the error again. Your Symfony Debug Toolbar should now contain some debug output that you can post here.

**Comment by PowerNow** [comment]
Due to I have no contao/dca folder I created one from the top root folder and inserted

`<?php dump($GLOBALS['TL_DCA']['tl_page']['list']['operations']); ?>`

Or to you mean under /vendor/contao?

My debug output (pressed on "Debug-Modus" on the top bar) on the bottom bar shows in red color under 

default locale
missing messages 1 
...

but no further infos.

If I click under "Weiterleitung" on the "Auswahl ändern" button I get the "stack trace" from above and 

under "logs"

```
Matched route "contao_backend".
{
    "route": "contao_backend",
    "route_parameters": {
        "_route": "contao_backend",
        "_scope": "backend",
        "_token_check": true,
        "_controller": "Contao\\CoreBundle\\Controller\\BackendController::mainAction"
    },
    "request_uri": "https://mydomain.com/contao?do=page&picker=H4sIAAAAAAAAAzWMMQqAMBAE_7J1sBAs9BUW9hLiRYLRyJmIEvJ3L4XlzgybYcIR6YkYcOqVoCCD9YUhwzryy_SeJJL14oLYKyQ2FUQ_28B706EomMRMx38yOrMRS3xrn2rb9igf9Fp7GmoAAAA%2C&popup=1",
    "method": "GET"
}
```

I replaces my domain with mydomain.com...

**Comment by m-vo** [comment]
> Due to I have no contao/dca folder I created one from the top root folder and inserted

You need to put the file exactly where @fritzmg told you and create any missing folders if needed.

**Comment by PowerNow** [comment]
Yes, I did as written above. To complete the problem, I changed my domain a few days before from my sub- to my main-domain. May that have something to do with the error?

**Comment by fritzmg** [comment]
Alternatively, you could also upload the content of `var/cache/prod/contao/dca/tl_page.php` of your Contao installation here. It's not strictly necessary to debug this, but I am curious why this happens in the first place.

**Comment by PowerNow** [comment]
Yep, here it is...
[tl_page.zip](https://github.com/contao/contao/files/6021970/tl_page.zip)

**Comment by PowerNow** [comment]
These are the critical logs:
```
[▼
  "exception" => TypeError {#1058 ▶}
]


[▼
  "exception" => TypeError {#1058 ▶}
]
{▼
 /html/code/8_2/vendor/contao/core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php:107 {▶}
 /html/code/8_2/vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:804 {▶}
 /html/code/8_2/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:4028 {▶}
 /html/code/8_2/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:3628 {▶}
 /html/code/8_2/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:353 {▶}
 /html/code/8_2/vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:644 {▶}
 /html/code/8_2/vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167 {▶}
 /html/code/8_2/vendor/contao/core-bundle/src/Controller/BackendController.php:48 {▶}
 /html/code/8_2/vendor/symfony/http-kernel/HttpKernel.php:158 {▶}
 /html/code/8_2/vendor/symfony/http-kernel/HttpKernel.php:80 {▶}
 /html/code/8_2/vendor/symfony/http-kernel/Kernel.php:201 {▶}
  /html/code/8_2/web/index.php:31 {▼
    › 
    › $response = $kernel->handle($request);
    › $response->send();
  }
}

```

**Comment by fritzmg** [comment]
You already posted the stack trace, so that's fine ;)

**Comment by PowerNow** [comment]
I have just setup a fresh contao 4.11 installation (no error) with one site and there is the same error...

**Comment by PowerNow** [comment]
It's becoming more strange. Since a while (maybe half an hour, I didn't do anything) I see above the contao backend some strange arry informations if I switch of the debug mode.

```
^ array:8 [▼
  "edit" => array:3 [▶]
  "copy" => array:4 [▶]
  "copyChilds" => array:4 [▶]
  "cut" => array:4 [▶]
  "delete" => array:4 [▶]
  "toggle" => array:3 [▶]
  "show" => array:2 [▶]
  "articles" => array:2 [▶]
]
```

**Comment by fritzmg** [comment]
That's the debug output from [this change](https://github.com/contao/contao/issues/2787#issuecomment-783317465). Simply delete that file again and rebuild the application cache.

**Comment by PowerNow** [comment]
Ah, ok I see. I think you wanted to have this infos? So I unfolded it..

I just made a second (fresh) installation 4.11 and eyerything works fine. If I connect this installation with the database from the other installation then the error comes back. So the origin of this problem lays somewhere in the database.

Does someone has an fallback solution?

```
^ array:8 [▼
  "edit" => array:3 [▼
    "href" => "act=edit"
    "icon" => "edit.svg"
    "button_callback" => array:2 [▼
      0 => "tl_page"
      1 => "editPage"
    ]
  ]
  "copy" => array:4 [▼
    "href" => "act=paste&amp;mode=copy"
    "icon" => "copy.svg"
    "attributes" => "onclick="Backend.getScrollOffset()""
    "button_callback" => array:2 [▼
      0 => "tl_page"
      1 => "copyPage"
    ]
  ]
  "copyChilds" => array:4 [▼
    "href" => "act=paste&amp;mode=copy&amp;childs=1"
    "icon" => "copychilds.svg"
    "attributes" => "onclick="Backend.getScrollOffset()""
    "button_callback" => array:2 [▼
      0 => "tl_page"
      1 => "copyPageWithSubpages"
    ]
  ]
  "cut" => array:4 [▼
    "href" => "act=paste&amp;mode=cut"
    "icon" => "cut.svg"
    "attributes" => "onclick="Backend.getScrollOffset()""
    "button_callback" => array:2 [▼
      0 => "tl_page"
      1 => "cutPage"
    ]
  ]
  "delete" => array:4 [▼
    "href" => "act=delete"
    "icon" => "delete.svg"
    "attributes" => "onclick="if(!confirm('Soll das Element ID %s wirklich gelöscht werden?'))return false;Backend.getScrollOffset()""
    "button_callback" => array:2 [▼
      0 => "tl_page"
      1 => "deletePage"
    ]
  ]
  "toggle" => array:3 [▼
    "icon" => "visible.svg"
    "attributes" => "onclick="Backend.getScrollOffset();return AjaxRequest.toggleVisibility(this,%s)""
    "button_callback" => array:2 [▶]
  ]
  "show" => array:2 [▼
    "href" => "act=show"
    "icon" => "show.svg"
  ]
  "articles" => array:2 [▼
    "href" => "do=article"
    "icon" => "article.svg"
  ]
]
```

**Comment by fritzmg** [comment]
@PowerNow which PHP version are you using?

**Comment by PowerNow** [comment]
I have php 8.0.1 but I found the reason!
I copied table for table from the current 4.10.7 to the new version 4.11 and was so able to circle the error, it was somewhere in the Sitestructur. As I assigend also these Sites which were not active and/or forwards to other internal sides (they don't need a layout) the error disappears.

So my proposal for this "Weiterleitungsseite" for (News, Forms, FAQ, Events,...):
If no layout is assigned to a page they should be hidden, but not producing an error.

Thxs for your help!!!

**Comment by fritzmg** [comment]
Are you sure? I think this error will always happen in PHP 8 actually, regardless of your setup.

**Comment by PowerNow** [comment]
For my setup I'm sure because I can reproduce this error. Which PHP version do you recommend? I also have 7.2,7.3,7.4,8.0...

**Comment by fritzmg** [comment]
Well Contao 4.11 should be fully compatible with PHP 8 - but there might still be some undetected issues/quirks, like this one. Switching back to PHP 7.4 should resolve the error for now and once the fix is released, you can upgrade to PHP 8 again. Keep in mind though that you need to run a full `composer update` after switching the PHP version each time.

**Comment by PowerNow** [comment]
Now I remember I already tried in the morning to downgrade from PHP 8.0 to 7.4, but unsuccessful regarding this error. I'm only in one point sure, if a layout is assigend to all sites then the error goes away.

**Comment by fritzmg** [comment]
> I'm only in one point sure, if a layout is assigend to all sites then the error goes away.

Yes, that's expected. The error should only occur in PHP 8 or higher though.

**Comment by leofeyer** [comment]
See #2785
