### ISSUE TITLE
SQL alter table command split may cause an error

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2790]
**Affected version(s)**

- Contao `^4.9`

**Related issues**

 - #169
 - #1651

**Description**

The SQL alter command is split into sub statements which leads to invalid sql statements. Adding a primary key does not work without a field, also creating an `AUTO_INCREMENT` field does not work without a primary key (mysql strict mode, not sure if it works without the strict mode):

For example a primary should be added before the field is created:

```sql
  ALTER TABLE tl_xyz_subscription ADD PRIMARY KEY (id)
  ALTER TABLE tl_xyz_subscription ADD state VARCHAR(255) DEFAULT '' NOT NULL
  ALTER TABLE tl_xyz_subscription ADD tstamp INT UNSIGNED DEFAULT 0 NOT NULL
  ALTER TABLE tl_xyz_subscription ADD id INT UNSIGNED AUTO_INCREMENT NOT NULL
```

**Comment by m-vo** [comment]
Does this happen in the `contao:migrate` command? Because there the original order from the schema diff should be preserved (it executes `getCommands(byGroup: false)`).

**Comment by dmolineus** [comment]
The point is that the origin `ALTER` command created by doctrine dbal executes all adjustments in one statement. The installer splits them into seperate statements. The installer is also used in the migrate command so I think the migrate command is also affected.

**Comment by m-vo** [comment]
Ah, got you. We must adjust how things are put in the `$order` array here:

https://github.com/contao/contao/blob/991282912ef0c590b92d25b67785463516a38890/installation-bundle/src/Database/Installer.php#L157-L183

**Comment by m-vo** [comment]
For reference:
*  this was the original issue https://github.com/contao/core-bundle/issues/723
*  and the fix https://github.com/contao/installation-bundle/pull/47 

…that lead to `array_reverse` being introduced.

**Comment by m-vo** [comment]
see #2792 

> For example a primary should be added before the field is created:

This however must be the other way round I believe (and the schema diff does as well). :slightly_smiling_face:
