### ISSUE TITLE
Deleting referenced records of serialized fields leads to unknown option

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2791]
**Affected version(s)**

Contao `^4.9`

**Description**

Since Contao shows the `unknown option` deleting refereced records will lead to unknown options.

The occurs for instance when deleting and the groups are assigned to members/users and or protected/restricted content.

 - user groups
 - member groups

**Comment by aschempp** [comment]
I think that's the intended behavior?

**Comment by dmolineus** [comment]
Imo the intended behaviour should be that the serialized referenced get updated as far a possible.

**Comment by leofeyer** [comment]
As discussed in Mumble on April 8th, we do not want to update the references, because you could accidentally delete a member group and then, when you undo the change, the references would be gone.
