### ISSUE TITLE
Views im listing-bundle

### ISSUE THREAD

**Issue by siegelsupport** [contao/contao#2795]
Bitte ersetzt doch folgenden Code in der Datei

https://github.com/contao/contao/blob/4.x/listing-bundle/src/Resources/contao/dca/tl_module.php#L113

durch den aus

https://github.com/contao/contao/blob/991282912ef0c590b92d25b67785463516a38890/core-bundle/src/Resources/contao/dca/tl_form.php#L516-L528

dann könnte das listing-bundle wieder views darstellen.

Danke an Yanick und Fritz im Slackchannel für diese Lösung!!!!

**Comment by fritzmg** [comment]
I'd propose to actually fix this in the `4.9` branch as this is something that worked previously in Contao 3.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2799
