### ISSUE TITLE
Tree view glitch (4.11 / PHP 8)

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2797]
**Affected version(s)**

Contao 4.11, PHP8.0

**Description**

~~Sometimes~~ when expanding a tree in the tree view (back end), the spinner appears, but the ajax request dies (500 IIRC) and so the spinner keeps on going without anything happening. After a reload, everything is working again. Also the node got expanded correctly. 

I'm currently not sure what is happening here. It's more of a primer. So if someone is experiencing this in dev mode - it might be worth looking at the request in the dev toolbar or the logs.

**Comment by m-vo** [comment]
Happens here:

`Warning: Undefined array key -1`

https://github.com/contao/contao/blob/1873bcc9ea728a08ca8755f6e7251d999d7b316b/core-bundle/src/Resources/contao/drivers/DC_Table.php#L3846

**Comment by fritzmg** [comment]
Probably needs `$arrIds[($i-1)] ?? null` and `$arrIds[($i+1)] ?? null`?

**Comment by m-vo** [comment]
Yes, I'm already fixing it.

**Comment by m-vo** [comment]
see #2805, there was also another problem in the same line (`$arrClipboard` can be `null`).
