### ISSUE TITLE
Contao 4.6 Install tool throws error after updating from 4.4

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#28]
**Affected version(s)**

Contao 4.6.0

**Description**  
After updating a contao installation to Contao 4.6.0 from 4.4.20 I opened the install tool which stopped working because of following error: `"Column not found: 1054 Unknown column 'youtubeOptions' in 'field list'"`

It seems like that the migration script is running before the database fields are created.

**How to reproduce**  

1. Install Contao 4.4
2. Update to Contao 4.6
3. Open the install tool

**Comment by fritzmg** [comment]
Contao 4.5 introduced the `youtubeOptions` field. Contao 4.6 requires a database upgrade involving the `youtubeOptions` field, but it does not create it itself. Thus this error occurs when going directly from 4.4 to 4.6.

**Comment by leofeyer** [comment]
But it should run the version 4.5 update beforehand, shouldn't it?

**Comment by leofeyer** [comment]
Ah, I see. The version 4.5 update does not add the field. 😢

**Comment by fritzmg** [comment]
Exactly. Also it wasn't necessary for the 4.5 update to create the field, since no migration has to be done.

**Comment by leofeyer** [comment]
Fixed in 90d6837c60e83e85112db94247cc011e8c726a4a.
