### ISSUE TITLE
Contao callback that are not postfixed configurable

### ISSUE THREAD

**Issue by baumannsven** [contao/contao#2803]
If I use my own callback and it does not have the postfix `_callback`, it is not possible to define the callback as `service` or `service annotation`.
Therefore, it would be advantageous to add such callbacks as a bundle configuration.

https://github.com/contao/contao/blob/991282912ef0c590b92d25b67785463516a38890/core-bundle/src/DependencyInjection/Compiler/DataContainerCallbackPass.php#L78

**Comment by fritzmg** [comment]
You would need to implement your own Compiler Pass in this case. The Contao Compiler Pass only supports callbacks according to Contao's own conventions and implementations.

**Comment by baumannsven** [comment]
@fritzmg Based on your explanation, I see it exactly like that and it makes sense. Therefore I will close the issue

**Comment by aschempp** [comment]
I would however suggest to follow the convention and add the `_callback` suffix 😅
