### ISSUE TITLE
Preview listener does not show the debug bar

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2810]
**Affected version(s)**

Contao 4.9 and later

**Description**

1. I have the debug mode enabled by switching the app mode in the `.env` file
2. I use the preview link from the backend
3. I expect to see the debug toolbar which does not appear

After debugging it a bit I can provide following additional information:

1. The markup for the toolbar is injected
2. The toolbar tries to call `/preview.php/_wdt/xyz` which ends in a endless redirect
3. The redirect is caused by the `Contao\CoreBundle\EventListener\PreviewAuthenticationListener` which try to login the user as the route is not defined as a backend route

**Comment by dmolineus** [comment]
Preventing the redirect for the `_wdt` route works for me:

```diff
        if (
+           $request->attributes->get('_route') === '_wdt'
+           || !$request->attributes->get('_preview', false)
-           !$request->attributes->get('_preview', false)
            || $this->scopeMatcher->isBackendRequest($request)
            || $this->tokenChecker->hasBackendUser()
        ) {
            return;
        }
```

**Comment by bytehead** [comment]
It works in my setup (barebone Symfony installation with Contao CoreBundle) 🤔

**Comment by fritzmg** [comment]
I can confirm the issue in Contao 4.9.12 (Managed Edition).

**Comment by m-vo** [comment]
(Same for 4.11 ME btw.)

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2829
