### ISSUE TITLE
url-suffix empty vs / 

### ISSUE THREAD

**Issue by asaage** [contao/contao#2812]
I've been struggeling with this for years now and made some tests with contao 4.11 to see if the default to empty url-suffix has actually changed something in the behaviour.
I have folder-urls configured in config.yml as well as in the root-page.
legacy-routing is set to false
prepend-locale, url-suffix and useAutoItem  is not set in config.yml.
I'm working with two regular-pages A and B - A is parent of B - no news- or event-readers are involved

test | page-name      | alias                     | request                                    | url-suffix: empty   | url-suffix: '/'
-----|-----------------|--------------------|---------------------------------|---------------------|--------------------
1     | parentpage-A  | parent                  | domain.com/parent                | 200                       | 404
2     | parentpage-A  | parent                  | domain.com/parent/               | 301 ➝ 200           | 200  
3     | childpage-B     | parent/child         | domain.com/parent/child       | 404                       | 404
4     | childpage-B     | parent/child         | domain.com/parent/child/      | 301 ➝ 404           | 200 
5     | childpage-B     | different/child      | domain.com/different/child    | 200                       | 404
6     | childpage-B     | different/child      | domain.com/different/child/   | 301 ➝ 200           | 200  

If i use url-suffix:/ and forget the trailing slash in the addressbar a 404 is not very nice but i can understand it.
If i use empty url-suffix on the other hand things are not so obvious anymore: **I can't** use the alias of the parent page as first part of the child-page alias - but that's what is generated on page-creation - and most of the time that's what you'd like to use. If the second part of the alias is always treated as a non-existent auto-item what's the point of folder-urls then?
Can somebody please try to reproduce that?

**Comment by fritzmg** [comment]
Some of what you listed is definitely a duplicate of https://github.com/contao/contao/issues/2775

**Comment by asaage** [comment]
> definitely a duplicate

True - that slipped my attention.

**Comment by aschempp** [comment]
@asaage please update the issue & table after upgrading to Contao 4.11.1 (when released).

**Comment by asaage** [comment]
Seems that The testcase 3 & 4 with empty suffix return 200 and 301 ➝ 200 now
That's great 👍🏼
