### ISSUE TITLE
Do not tag contao.db.tl_module.<id> for articles

### ISSUE THREAD

**Issue by m-vo** [contao/contao#2814]
**Affected version(s)**

Contao >=4.9 

**Description**

Every generated `Module` tags the response with `contao.db.tl_module.<id>`, even when rendering articles:

https://github.com/contao/contao/blob/712de2476dc6100cad1876da1f22b809f7558d5c/core-bundle/src/Resources/contao/modules/Module.php#L242

This way the `x-cache-tags` of a page displaying article `ID 5` will look like this even though module `ID 5` is not present:
```
contao.db.tl_article.5,[…],contao.db.tl_module.5
```

**Comment by fritzmg** [comment]
The condition probably needs to be expanded to

```php
if (System::getContainer()->has('fos_http_cache.http.symfony_response_tagger') && !$this instanceof ModuleArticle)
```
