### ISSUE TITLE
_contao/initialize Error 500

### ISSUE THREAD

**Issue by piotrwarsztocki** [contao/contao#2816]
**Affected version(s)**

Contao >= 4.11

**Description**

After upgrade from 4.10.7 to 4.11 all my custom scripts that depend on ``/system/initialize.php`` stoped to work with **http 500 error**. The problem start during contao initialziation thru initialize.php

For example simple test script ``web/test/test.php``

    \define('TL_SCRIPT', 'web/test/test.php');
    \define('TL_MODE', 'FE');
    \define('BYPASS_TOKEN_CHECK', true);
    require_once('../../system/initialize.php');

It generates **http 500 error** and you can find this in log file

    request.CRITICAL: Uncaught PHP Exception LogicException: ""Contao\CoreBundle\Controller\InitializeController" has no container set, did you forget to define it as a service subscriber?" at /data/sites/moj.almatur.pl/site/vendor/symfony/framework-bundle/Controller/ControllerResolver.php line 39 {"exception":"[object] (LogicException(code: 0): \"Contao\\CoreBundle\\Controller\\InitializeController\" has no container set, did you forget to define it as a service subscriber? at /data/sites/moj.almatur.pl/site/vendor/symfony/framework-bundle/Controller/ControllerResolver.php:39)"} []

The same happens if you try direct route ``/_contao/initialize``

Tried also on clean, core-only installation. Same results :(

Any ideas?

**Comment by m-vo** [comment]
see #2807

**Comment by m-vo** [comment]
Btw.: Please consider migrating away from these legacy scripts and use controllers + the app's routing instead.

**Comment by piotrwarsztocki** [comment]
> Btw.: Please consider migrating away from these legacy scripts and use controllers + the app's routing instead.

Ok. I actually did it few minutes ago so from my point of view problem is solved :) Thanks
