### ISSUE TITLE
Cache warming chrashes if dev dependencies are not installed

### ISSUE THREAD

**Issue by bezin** [contao/contao#2817]
Hello there,

I have the following setting within a Contao 4.9 installation:

I required the `DoctrineFixturesBundle` as a dev dependency …
```
composer require doctrine/fixtures-bundle --dev 
```

… and then loaded it in the Apps' Manager plugin as `production-only`
```
// src/ContaoManager/plugin.php
return [
    BundleConfig::create('Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle')->setLoadInProduction(false)
];
```

If you now run `composer install --no-dev` and your app is in production mode, the dev cache warming will crash, because `ContaoKernel` tries to instanciate the bundle that does not exist:

```
 In BundleConfig.php line 153:                                                                                                                    
    The Symfony bundle "Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle" does not exist.
```

**Comment by fritzmg** [comment]
That's not the intended usage, I think. Composer dev dependencies and Symfony application environments are two different things. If your Symfony application relies on the presence of certain classes - no matter which environment - then these classes need to be available and thus you cannot install them as a composer dev dependency only.

> the dev cache warming will crash

Also - the dev cache is never warmed, only cleared. Where exactly does the error happen anyway?

**Comment by m-vo** [comment]
But shouldn't it be possible still? I'd assume that `BundleConfig::create('FooBundle')->setLoadInProduction(false)` would not even try to instantiate the bundle class in prod.

> Also - the dev cache is never warmed, only cleared. Where exactly does the error happen anyway?

It happens in the cache clear stage (`cache:clear --no-warmup --env=dev`).

**Comment by fritzmg** [comment]
> I'd assume that `BundleConfig::create('FooBundle')->setLoadInProduction(false)` would not even try to instantiate the bundle class in prod.

Yes, but the error happens in `dev`, not `prod`.

**Comment by m-vo** [comment]
True :upside_down_face:

**Comment by bezin** [comment]
What I want to achieve is to run `composer install --no-dev` on my remote server and have it properly install and boot the app without the fixtures bundle as it is no dependency of my app in production. I see your point with the difference between Composer and Symfony environments though, and yet it feels weird that a bundle that is in fact not required by the app in production must be present still.

**Comment by aschempp** [comment]
It must not be present in production, only in dev mode. I guess your best shot is to disable the debug mode (backend menu option) in this case, by adding `APP_ENV=prod` to your `.env` file

**Comment by fritzmg** [comment]
Plus you need to implement a custom `post-update-cmd` & `post-install-cmd` script so that the error does not occur during `cache:clear --no-warmup --env=dev`.

**Comment by bezin** [comment]
Thanks for your comments, closing this as it is not a bug.

**Comment by m-vo** [comment]
I still find this very cumbersome. Can't we improve on this?

**Comment by fritzmg** [comment]
I do not think there is anything to be improved - at least not in the Contao Managed Edition. The Contao Managed Edition is supposed to always have a `dev` environment. You can however completely disable the `dev` environment if you really want to, as described. I don't see the benefit of that though, as it's always handy to be able to work in the `dev` environment (via JWT cookie) even in production - for quick debugging of an error for example.
