### ISSUE TITLE
Cookies set via JavaScript cause InvalidRequestTokenException

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2820]
**Affected version(s)**

Contao 4.9.12+

**Description**

If you visit a page with a form where some JavaScript generates a cookie within the site's domain, the form cannot be sent as the newly set cookie triggers the `InvalidRequestTokenException` - if the previous request had no CSRF token cookie in its response.

**Reproduction**

1. Create a simple test form (`POST`) and integrate in into a page.
2. Integrate a JavaScript like `document.cookie = "foobar=foobar";` into the same page.
3. Clear the cookies for the site's domain.
4. Visit the page containing the form in the front end.
5. Submit the form.

If the initial request did not return `true` for `CsrfTokenCookieSubscriber::requiresCsrf` then the subsequent `POST` request will trigger the `InvalidRequestTokenException`, since the newly, client side set cookie now requires a CSRF token to be present, but none was set before of course.

This is a case reported on the [community forum](https://community.contao.org/de/showthread.php?79555-Ung%C3%BCltiges-Anfrage-Token-mal-wieder&p=540676&viewfull=1#post540676) where the cookie is actually set by the Google Tag Manager for example. So when visiting the page for the first time (or after clearing the cookies), form submission will not work for anyone.

**Comment by aschempp** [comment]
I think this is a known limitation, and the cookie should be denylisted anyway.

**Comment by Toflar** [comment]
Putting it on the deny list would still cause trouble in dev mode.
But the behaviour looks correct to me. We don't know which cookies potentially identify you as a person and thus require CSRF protection. Imagine you set `document.cookie = "sender=fritzmgs-address"`. This would "bind" the POST request to you as a person and thus we have to protect you from CSRF in that case. 
There's a solution to it though, what if you extend your JS to do a `window.location.reload()` after you set the cookie?

**Comment by fritzmg** [comment]
> There's a solution to it though, what if you extend your JS to do a window.location.reload() after you set the cookie?

You can only do that with cookies that you set yourself though.

> and the cookie should be denylisted anyway.

Currently we do not have any sort of ignore list for cookies that should be ignored for whether or not a request token is needed.

**Comment by m-vo** [comment]
> Putting it on the deny list would still cause trouble in dev mode.

Can't we always strip cookies on `kernel.request` (before the `CsrfCookieSubscriber`)? This way caching and CSRF token protection don't depend on each other.

I ran into the same issue with the `XDEBUG_SESSION` cookie when debugging btw.

**Comment by fritzmg** [comment]
As @Toflar said, we basically can't strip any cookies, as they all might contain personal data that require CSRF protection. And arguably the cookies set by the Google Tag Manager and/or Google Analytics script for example contain personal data as well as they are supposed to identify you.

**Comment by Toflar** [comment]
I don't see any way to fix this. /cc @ausi

**Comment by fritzmg** [comment]
Me neither :/. How do other applications solve this? It's not like CSRF protection and client-side set cookies are a unique problem to Contao.

**Comment by m-vo** [comment]
> we basically can't strip any cookies, as they all might contain personal data that require CSRF protection.

Isn't that exactly what I can configure with the ALLOW/DENY lists? Telling the system that a cookie - although it technically could be used to - will not affect the output, i.e. not contain private data?

**Comment by fritzmg** [comment]
Cross Site Request Forgery is about unwanted _sending_ of private data, isn't it?

**Comment by ausi** [comment]
Once all major browsers support cookies with `SameSite=Strict` we could use such a cookie that will be always set to `1` to prevent CSRF (no need for a hidden field anymore). It should be safe then to always strip this cookie as it is not used in the hidden field.

But IE11 doesn’t support `SameSite` and most probably never will.

**UDATE:** looks like new verions of IE11 actually support it https://caniuse.com/same-site-cookie-attribute

**Comment by aschempp** [comment]
I agree that we could strip cookies regardless of whether we use a reverse proxy or not. A `kernel.request` event wouldn't be right imho though, as we would basically need to duplicate the functionality.

**Comment by leofeyer** [comment]
As discussed in Mumble on March 11, we want to implement @ausi's [suggestion](https://github.com/contao/contao/issues/2820#issuecomment-788883232) above.

**Comment by leofeyer** [comment]
As discussed in Mumble on March 11th, this is a known limitation and should be solved with the cookie deny list as @aschempp [explained above](https://github.com/contao/contao/issues/2820#issuecomment-788592697).

**Comment by leofeyer** [comment]
We have to adjust the regex here and use `_ga.*` instead of `_ga` and `_gat`:

https://github.com/contao/contao/blob/6cdb7fce22c393ba19e0ca3b9237398b9bbba050/core-bundle/src/EventListener/HttpCache/StripCookiesSubscriber.php#L33-L35
