### ISSUE TITLE
FilesModel::findByPath() does not normalize windows paths

### ISSUE THREAD

**Issue by ausi** [contao/contao#2824]
**Affected version(s)**

Contao 4.11 (most probably 4.9 too)

**Description**

In the `ImageFactory` the `uploadPath` can contain backslashes like `C:\foo\www/files` but the image path is mostly in the normalized form like `C:/foo/www/files/bar.jpg`. This creates problems in https://github.com/contao/contao/blob/1229843fcd1ec18522b85287ee0ebd915a950c18/core-bundle/src/Resources/contao/models/FilesModel.php#L254 because the root path is not stripped correctly. This can result in missing important parts for images like it was the case in the following discussion on slack: https://contao.slack.com/archives/CK4J0KNDB/p1614694011186200

I think we should use the pathutils library to strip the directories there to fix the issue.

**Comment by leofeyer** [comment]
Would it not make more sense to normalize `contao.upload_path` in general? There are other places where the problem should occur as well (I wonder why it did not?):

https://github.com/contao/contao/blob/29f2d850957bf626a9304423962f49fb706abd0f/core-bundle/src/Resources/contao/library/Contao/Dbafs.php#L852-L858

**Comment by fritzmg** [comment]
The problem is not `contao.upload_path` specifically, but the string operation.

**Comment by ausi** [comment]
In the `Dbafs::isFileSyncExclude()` method you cannot know what format `$strPath` uses so you have to normalize there, or better use the correct library function for that use case `Path::isBasePath()` so that we don’t have to think about path normalization. We already use this in https://github.com/contao/contao/blob/991282912ef0c590b92d25b67785463516a38890/core-bundle/src/Image/ImageFactory.php#L312

**Comment by leofeyer** [comment]
So the correct way to solve this issue is to use `Path::isBasePath()` everywhere where we currently use `strncmp()`?

**Comment by m-vo** [comment]
> So the correct way to solve this issue is to use Path::isBasePath() everywhere where we currently use strncmp()?

Imo, that's the easiest way because it automatically canonicalizes all inputs. We just have to be careful if paths can lie outside of the root dir like in #1918.

And it probably won't fit well with the one-char-comparisons (like `strncmp($strFile, '.', 1)`) that are quite frequent as well. :upside_down_face:

**Comment by ausi** [comment]
> So the correct way to solve this issue is to use `Path::isBasePath()` everywhere where we currently use `strncmp()`?

I don’t think we can generalize it like that. It depends on the context IMO and we should use the intended `Path` methods for each case.

- If we want to make an absolute path relative to TL_ROOT we should use `Path::makeRelative()`
- If we want to check if a path is inside `TL_ROOT` we should use `Path::isBasePath()`
- If we want to check if a relative path is inside the upload directory we should use `Path::isBasePath($this->get('contao.upload_path'), $relativePathToCheck)`

Every other case of `strncmp()` should be looked at individually I think.
