### ISSUE TITLE
Allow sorting FE Modules by ID or show IDs beside module name

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#2825]
Hi people, is it possible to add the option sort by ID on frontend modules?

Why?
Some times we get error or warning that module ID xx is not works or exist etc. Then we have to check what is the reason and seek for this module in backend. This is by few modules very easy, but if you have around 200 modules, it take more time to find as to fix this problem. Of course, this reason is not the only one, it will make also the usability easier.

It will also work if you can show the ID beside the module name!

![Bildschirmfoto 2021-03-03 um 08 51 03](https://user-images.githubusercontent.com/11348417/109773864-fad3e600-7bff-11eb-8433-5f8bcc42ec5f.png)

**Comment by m-vo** [comment]
You can already search by ID. This might even be the easier approach for your use case scenario?

Sorting, to me, would only make sense if IDs are displayed as well. Maybe we should add IDs everywhere in `dev` mode as this would mostly be needed for debugging :smile:. But IMHO over the top.

You should be able to adjust the DCA with a label callback and set a `sorting => true` (+ maybe a flag) in the field definition if you need this specifically.

**Comment by havutcuoglu** [comment]
> You should be able to adjust the DCA with a label callback and set a sorting => true (+ maybe a flag) in the field definition if you need this specifically.

That's exactly what I wanted to avoid. 😃
But I think to add this option in DCA in core will be possible.

**Comment by fritzmg** [comment]
I think it would make sense to set `search => true` for the `tl_module.id` field in the core. I don't think sorting by ID is ever useful. Altering the label to include the ID is also something that should be set per application and not in the core.

**Comment by m-vo** [comment]
> I think it would make sense to set search => true for the tl_module.id field in the core

That's already the case.

**Comment by havutcuoglu** [comment]
> I think it would make sense to set search => true for the tl_module.id field in the core

Exactly. That will help also. 👍

May be to show the IDs beside the name? 😁

**Comment by m-vo** [comment]
![image](https://user-images.githubusercontent.com/5305677/109785717-b1d65e80-7c0c-11eb-81c3-ece72c07c6cf.png)

**Comment by fritzmg** [comment]
> That's already the case.

Ah, I only checked in Contao 4.9 :). @havutcuoglu the feature you want is already present. If you need it, you can update to Contao **4.11**. If you want to stay with Contao **4.9**, you can make a DCA adjustment:

```php
// contao/dca/tl_module.php
$GLOBALS['TL_DCA']['tl_module']['fields']['id']['search'] = true;
```
