### ISSUE TITLE
wrong page-title on 404-errorpage with empty or / url_suffix

### ISSUE THREAD

**Issue by asaage** [contao/contao#284]
Today i stumbled about a strange behaviour.
Usually if you request a nonexisting page and you have set a **non-redirecting** 404 page in your sitestructure the response will contain something like ```<title>Page not found - Contao Official Demo</title>``` and a proper responsecode of 404.

My Setup has folder-urls enabled, ```prepend_locale: true``` and ```url_suffix: '/'```
which causes the following results:

- domain.tld/en/contact/  → status ```200``` ```<title>contact...</title>``` ✓
- domain.tld/en/somethingstupid/ → status ```404``` ```<title>page not found...</title>``` ✓
- domain.tld/en/**contact**/somethingstupid/ → status ```404``` ```<title>contact...</title>``` ?

I tried this without folder-urls and/or without ```prepend_locale: true``` achiving the same results.
```url_suffix: ''``` will also give me the same result.

It's probably not a big deal but i think it's a bug (especialy if you have ```<h1>{{page::pageTitle}}</h1>``` in your layout)

**Comment by aschempp** [comment]
I think this is a bug, the page title should not contain the name of the alias, because that page is actually not matched?

**Comment by leofeyer** [comment]
@contao/developers Turns out this is caused by the insert tag cache. The following solutions come to my mind:

1. Exempt the `page` insert tag from caching

2. Add `|refresh` to the default title so it becomes `{{page::pageTitle|refresh}} - {{page::rootPageTitle|refresh}}`

3. Add a static `reset()` method to the `InsertTags` class

**Comment by ausi** [comment]
I think we should go with 1. because the caching isn’t really necessary for the `page` insert tag. Maybe there are other tags that don’t need to be cached too?

**Comment by Toflar** [comment]
I agree with @ausi here :)

**Comment by leofeyer** [comment]
Fixed in 7e5ce6bd78fbd3fa12b30497fb2582ed0a95f7a9 then.
