### ISSUE TITLE
sharebutton links, which are embedded as a module in the layout increase the runtime of the broken link checker enormously

### ISSUE THREAD

**Issue by grashalm4u** [contao/contao#2842]
I want to report a problem, but i'm not sure if it has been reported before ...

I use contao 4.9.12 and the extension sharebuttons from fritzmg in version 2.1.5. After we tried a few things, he said that I should post my request here because it doesn't seem to be causally related to the sharebuttons.

the links of the share buttons are provided with the "data-skip-broken-link-checker" attribute, so that they should actually be ignored by the crawler when scanning for broken links.
during a scan, the crawler finds around 65,000 links on my side using the sharebutton module, which is activated in the layout, and which takes all night to do this. he seems to be counting these links, but not checking them. since the links are included on every page below the article, there are a corresponding number and increase the runtime of the broken link checker enormously.
Would it be possible to program the crawler in such a way that the links with the "data-skip-broken-link-checker" attribute are neither checked nor counted? that would shorten the scanning process for me by many hours.
if I deactivate the share buttons module in the layout, the scan is completed after around 50 minutes.

With best regards,

grashalm

here you can find two examples from the debug-log:

"2021-03-03 22:24:55.399316","Contao\CoreBundle\Crawl\Escargot\Subscriber\BrokenLinkCheckerSubscriber",https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdie-schreibmaus.de%2F&t=startseite,https://die-schreibmaus.de/die-schreibmaus.html,1,"skip-broken-link-checker, rel-nofollow, disallowed-robots-txt","Did not check because it was marked to be skipped using the data-skip-broken-link-checker attribute."

"2021-03-03 22:24:55.606377","Contao\CoreBundle\Crawl\Escargot\Subscriber\BrokenLinkCheckerSubscriber",https://twitter.com/intent/tweet?url=https%3A%2F%2Fdie-schreibmaus.de%2F&text=startseite,https://die-schreibmaus.de/die-schreibmaus.html,1,"skip-broken-link-checker, rel-nofollow","Did not check because it was marked to be skipped using the data-skip-broken-link-checker attribute."

**Comment by fritzmg** [comment]
@grashalm4u you should also post an excerpt of the debug log in order to show that these links are indeed skipped by the broken link checker.

**Comment by leofeyer** [comment]
As discussed in Mumble on April 8th, the crawler cannot completely skip links with the `data-skip-broken-link-checker` attribute, because the link checker is only one of many subscribers. Other subscribers might do something with the URL.

You could configure the behavior of the crawler more granularly on the command line (see https://docs.contao.org/dev/reference/commands/#contao-crawl).

**Comment by Toflar** [comment]
You can update `terminal42/escargot` to version 1.1.0 and set `data-escargot-ignore` on those links to mark them to not even be added to the queue. See https://github.com/terminal42/escargot/releases/tag/1.1.0.

**Comment by grashalm4u** [comment]
Thanks a lot! That solved my problem completely.
