### ISSUE TITLE
Benutzergruppe: Rechteverwaltung: "Von der Synchronisation ausgenommene Ordner" ohne Effekt

### ISSUE THREAD

**Issue by bit7ms** [contao/contao#2847]
**Affected version(s)**

Contao 4.9.12

**Description**

Obwohl ich in der Benutzergruppe die Synchronisation von Ordnern für den Redakteur ausgeschlossen habe, kann dieser trotzdem die Eigenschaft setzten.
Ich habe diesen Bug auf 3 verschiedenen Contao Systemen nachvollziehen können.
Danke für's beheben!

**Comment by ausi** [comment]
Die Checkbox „Das Dateisystem mit der Datenbank synchronisieren“ in den Benutzergruppeneinstellungen bezieht sich denke ich nur auf den „Synchronisieren“-Button in der Dateiverwaltung rechts oben, nicht jedoch auf die Checkbox „Nicht synchronisieren“ in den Einstellungen eines Ordners.

**Comment by bit7ms** [comment]
ok verstehe - dann ist die Bezeichung in den Benutzergruppen-Einstellungen etwas missverständlich.
Dann fehlt die Option aber bei den Nutzerrechten.
Ich habe jetzt schon zweimal das Problem mit Redakteuren gehabt, die diesen Haken (wohl versehentlich) gesetzt haben. Das Problem fällt dann erst mit der Zeit auf und sorgt für viel Iritationen = hoher Zeitaufwand...
Normale Redakteure sollten diese Option gar nicht haben.
=> Urgend Feature

**Comment by ausi** [comment]
Soweit ich das sehe, kann man aktuell die Felder der Dateiverwaltung (name, protected, syncExclude, importantPart…, meta) gar nicht einzeln einstellen. Das wäre aber eventuell ein sinnvolles Feature denke ich.

**Comment by aschempp** [comment]
Ich weiss nicht ob man das für alle Felder braucht … aber wenn die Option für Benutzer deaktiviert ist, würde ich zumindest erwarten dass auch die Checkbox verschwindet …

**Comment by ausi** [comment]
Ich würde das als verschiedene Optionen sehen. Die bestehende Einstellung steuert, ob man die Synchronisierung für das gesamte Dateisystem ausführen darf. Die Feld-Einstellung würde sich nur darauf beziehen ob ich Ordner die ich bearbeiten darf von der Synchronisierung ausnehmen darf.

**Comment by aschempp** [comment]
warum sollte ich welche von der Synchronisierung ausnehmen können, wenn ich nicht synchronisieren kann? Bzw. umgekehrt?

**Comment by ausi** [comment]
Weil es ja dennoch eine Auswirkung hat. Dateien in einem Ordner der nicht synchronisiert wird kann ich z. B. nicht im Picker auswählen. Die Synchronisierung für das gesamte Dateisystem auszuführen ist alternativ dazu eher ein Maintenance task IMO. Synchronisiert wird der Ordner den ich anlege ja trodzdem direkt beim Erstellen und Hochladen.

Analog dazu ist es ja auch so, dass die Berechtigung den Bildercache zu leeren und die Berechtigung Bildgrößen zu bearbeiten auch zwei verschiedene Berechtigungs-Einstellungen sind.

**Comment by leofeyer** [comment]
As discussed in Mumble on June 2nd, we have to add `'exclude' => true` in the `tl_files` DCA, so the fields can be removed per user group. We then have to add a migration to enable the fields by default (backwards compatibility).
