### ISSUE TITLE
UserCreateCommand SQL error

### ISSUE THREAD

**Issue by richardhj** [contao/contao#2849]
**Affected version(s)**

Contao 4.11

**Description**

The UserCreateCommand has an issue with reserved keywords:

```
CRITICAL  [console] Error thrown while running command "contao:user:create". Message: "An exception occurred while executing 'INSERT INTO tl_user (tstamp, name, email, username, password, language, backendTheme, admin, pwChange, dateAdded, groups) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1615137394, "Name", "email", "username", "$2y$13.", "en", "flexible", true, false, 1615137394, ""]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups) 
```

This is because ["groups" is a (new) reserved keyword](https://dev.mysql.com/doc/refman/8.0/en/keywords.html).

However, we are already using DBAL, from which I thought it is taking care of escaping?

https://github.com/contao/contao/blob/6cdb7fce22c393ba19e0ca3b9237398b9bbba050/core-bundle/src/Command/UserCreateCommand.php#L280-L293

**Comment by m-vo** [comment]
What's your version of DBAL? Maybe this is a regression bug.

**Comment by richardhj** [comment]
```
doctrine/common                                         2.13.3           PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support,...
doctrine/data-fixtures                                  1.5.0            Data Fixtures for all Doctrine Object Managers
doctrine/dbal                                           2.12.1           Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle                                1.12.13          Symfony DoctrineBundle
```

I indeed updated from MySQL 5.7 to 8.0
```
$ mysqld --version
/usr/local/Cellar/mysql/8.0.23_1/bin/mysqld  Ver 8.0.23 for osx10.15 on x86_64 (Homebrew)
```

**Comment by fritzmg** [comment]
This error also has been reported on the community forum: https://community.contao.org/de/showthread.php?80359-Contao-pure-%C3%BCber-CLI-einrichten&p=540484&viewfull=1#post540484

I am also surprised that DBAL does not handle this correctly.

**Comment by richardhj** [comment]
I found some resources that Doctrine is not auto-escaping because it is too dependent on the database.

See: https://github.com/doctrine/orm/issues/5874#issuecomment-226213196, https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/limitations-and-known-issues.html#identifier-quoting-and-legacy-databases

The following change change fixes the behaviour (did not check for regression on MySQL 5.7 though):
```diff
 $this->connection->insert(
    'tl_user',
    [
        'tstamp' => $time,
        'name' => $name,
        'email' => $email,
        'username' => $username,
        'password' => $hash,
        'language' => $language,
        'backendTheme' => 'flexible',
        'admin' => $isAdmin,
        'pwChange' => $pwChange,
        'dateAdded' => $time,
-        'groups' => !$isAdmin && !empty($groups) ? serialize(array_map('strval', $groups)) : '',
+        '`groups`' => !$isAdmin && !empty($groups) ? serialize(array_map('strval', $groups)) : '',
    ]
);
```

(we might use `$this->connection->quoteIdentifier()` instead)

**Comment by m-vo** [comment]
I thought this is only true for ORM not DBAL? 😕

See https://github.com/doctrine/dbal/pull/3128 (should be in there since 2.8)

**Comment by ausi** [comment]
> (we might use `$this->connection->quoteIdentifier()` instead)

👍
