### ISSUE TITLE
Make the existing "variable" setting available in SCSS + alternative idea for more dynamic SCSS compilation

### ISSUE THREAD

**Issue by markusmilkereit** [contao/contao#2850]
feature request

## basic version

We were trying to find a nice way to get a SCSS variable from the Contao Backend into the SCSS compilation process for a couple of days now - nice meaning: clean, update-safe, easy to understand and use later.

There is one setting that can already provide a good part of it: the "variables" setting in the Theme:
![image](https://user-images.githubusercontent.com/676671/110249546-d61c9d00-7f76-11eb-9cad-b59f8c15f3b6.png)

We specifically want to use it like shown in the screenshot: we set a variable in the backend, that can be used in conditional logic during the compilation process in SCSS, loading different variables, mixins and/or functions. The big picture: we could deliver a theme with a common code base (bundle) that with a single variable can switch between different subthemes/stylings.

In the SCSS variables we would then do something like this, slimmed down to the max:
``` SCSS
@if $theme == lawyer2 {
	$body-background: #f0f;
}

$body-background: #fff !default;
```

The logic could be included in the Combiner->handleScssLess() , rough version:
``` PHP 
/** @var PageModel $objPage */
global $objPage;
$this->import('Database');
$vars = array();

// Get the global theme variables
$objTheme = $this->Database->prepare("SELECT tl_theme.vars FROM tl_theme, tl_layout WHERE tl_theme.id=tl_layout.pid AND tl_layout.id=?")
						   ->limit(1)
						   ->execute($objPage->layoutId);

if ($objTheme->vars != '' && \is_array(($tmp = StringUtil::deserialize($objTheme->vars))))
{
	foreach ($tmp as $v)
	{
		// remove $ for backwards compatability with existing entries on the key
		$vars[str_replace('$', '', $v['key'])] = $v['value'];
	}
}

$objCompiler->setVariables($vars);
// existing compile() line
return $this->fixPaths($objCompiler->compile($content, $this->strRootDir . '/' . $arrFile['name']), $arrFile);

```

## alternative idea for even more dynamic SCSS 

A Hook to get into the SCSS compilation step would be really nice - that would give a little bit more freedom for different solutions. The suggestion above is much closer to current functionality and would preserve the otherwise useless "variables" setting once internal Stylesheets are dropped.

**Comment by richardhj** [comment]
What about printing the layout variables as CSS variables to the page template for your use case?
`$theme` becomes `--theme` then.
You can register a `parseTemplate` or `getPageLayout` hook for that purpose.

However, I consider the theme's variables section as deprecated as it coupled to the old CSS builder.
There are much better (opinionated) approaches. All of them include using CSS variables. But I would avoid counting on the layout's variables.

**Comment by m-vo** [comment]
I would avoid tying your FE build process to Contao's scss compiler. At least for more complex things.

If you want to go crazy, you could also write the variables in a manifest file and parse it with webpack - should you have node available on the server. But CSS variables + no extra optimization are probably a good middle ground.

**Comment by aschempp** [comment]
> However, I consider the theme's variables section as deprecated as it coupled to the old CSS builder.
There are much better (opinionated) approaches. All of them include using CSS variables. But I would avoid counting on the layout's variables.

I absolutely agree with that. Sounds like something that should be build on CSS variables to me 😊

**Comment by markusmilkereit** [comment]
CSS variables could also work, we'll try on the current project - I would have preferred to keep it in the nicely integrated SCSS compilation within Contao, so it's more browser independent. CSS var() support is not bad, just not as good as native CSS that comes out of SCSS ;)

**Comment by leofeyer** [comment]
As discussed in Mumble on March 11th, the global theme variables are part of the internal style sheet editor, which has been deprecated. Both will be removed in Contao 5, therefore you should not use it as basis of your theme. Instead, use a `variables.scss` file and import it in your main SCSS file.

**Comment by markusmilkereit** [comment]
Thanks for the consideration - we now found a nice solution with CSS variables in a global theme, that can be sub-themed with local CSS variables. The first 3 projects are already using (part of) the solution :)
