### ISSUE TITLE
Cannot create any articles

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#2852]
**Affected version(s)**

Contao 4.11.1

**Description**

I've just setup a clean and empty 4.11.1 (PHP 7.4.9), added some pages. 
When trying to create an article I do not get button/icon to set the location of the new article:

![image](https://user-images.githubusercontent.com/226890/110298640-1ae71900-7ff5-11eb-9cb2-c06eba677fd3.png)

**Comment by fritzmg** [comment]
You can only create articles for a page, if the page's layout contains the _Articles_ module.

**Comment by bennyborn** [comment]
I see... That didn't happen in 4.9 before. Could quite cause some confusion but I agree thats not a bug.
