### ISSUE TITLE
Logout does not redirect to home page on protected pages

### ISSUE THREAD

**Issue by ausi** [contao/contao#2855]
**Affected version(s)**

Contao 4.9.12 (Symfony 4.4.19)
Contao 4.11.1 (Symfony 5.2.3)

**Description**

If you click the logout button in the login module on a protected page you get redirected to the protected page which results in a 401 response.

The `_target_path` hidden field gets set to the home page correctly (if you are on a protected page), but it seems like symfony ignores it.

`_always_use_target_path` is set to the empty string, but setting it to `1` manually doesn’t seem to have an effect either.

**Comment by bytehead** [comment]
I'll have a look at it 👍

**Comment by bytehead** [comment]
Only frontend or backend as well?

**Comment by ausi** [comment]
The backend logout redirects me to `/contao/login` which seems to be the desired behavior I guess. So I think only the frontend is affected by this.

**Comment by bytehead** [comment]
Another question: the login module should never sit on a protected page - you can't login there anyway. Why would you place it on a protected page?

**Comment by fritzmg** [comment]
> Another question: the login module should never sit on a protected page - you can't login there anyway. Why would you place it on a protected page?

You don't place the login module on a protected page directly. But if you access a protected page and you are not logged in, then the content of the 401 page is shown under the same URL, if you did not enable any redirects. Typically you will have the login module on the 401 page.

**Comment by ausi** [comment]
> Why would you place it on a protected page?

Because if you are logged in, the login-module automatically switches to a logout module. (There is no explicit logout module).

Also, if the login/logout module is placed in the header or sidebar, it is visible on all pages (protected or not).

**Comment by ausi** [comment]
So it looks like this line is currently always responsible for redirecting after logout: https://github.com/contao/contao/blob/69e7aa67b0402ab9abbb15a1436c36136344e0ba/core-bundle/src/Security/Logout/LogoutSuccessHandler.php#L49

To actually use a specific redirect URL we probably need to set the `redirect` query string as we do in the other logout module: https://github.com/contao/contao/blob/69e7aa67b0402ab9abbb15a1436c36136344e0ba/core-bundle/src/Resources/contao/modules/ModuleLogout.php#L76

**Comment by aschempp** [comment]
We could also add support for `_target_url` in the `LogoutSuccessHandler`, but it probably does not make sense to support multiple different "ways" for the same think 🤷

**Comment by bytehead** [comment]
Closed in favor of #2901.
