### ISSUE TITLE
Verlinkung von Inhaltselement Hyperlink (ce_hyperlink) im Backend fehlerhaft

### ISSUE THREAD

**Issue by minstyle** [contao/contao#2859]
**Affected version(s)**

Contao 4.9.12

**Description**

Ber der Erstellung eines Hyperlinks wird in der Backend-Inhaltselement-Vorschau von Contao der entsprechende Link-Text falsch verlinkt.

![image](https://user-images.githubusercontent.com/2649562/110324071-c7d18e00-8015-11eb-9b22-b1ef47ae677a.png)

![image](https://user-images.githubusercontent.com/2649562/110324324-1717be80-8016-11eb-92f0-635727e70227.png)
Bei Klick auf den Linknamen erfolgt ein 404-Fehler.

![image](https://user-images.githubusercontent.com/2649562/110324467-4b8b7a80-8016-11eb-9b86-9268289e4665.png)
Anscheinend wird das Contao Insert Tag `{{link_url::*}}` nicht umgewandelt.

Fehler reproduzierbar unter demo.contao.org.

**Comment by fritzmg** [comment]
I would not consider this an error. Insert tags for this view are only replaced in the front end.

**Comment by minstyle** [comment]
Then it shouldn't be linked in backend view of Contao. It's an usability fail.

**Comment by fritzmg** [comment]
> Then it shouldn't be linked in Contao.

The view shows the generated HTML output of that element.

**Comment by leofeyer** [comment]
As discussed in Mumble on April 8th, this is the indented behavior, because when you hover over the link in the back end preview, we want to see `link_url::2` as link target and not the replaced version.
