### ISSUE TITLE
Deprecated classes in Symfony 5.1

### ISSUE THREAD

**Issue by ausi** [contao/contao#2862]
Deprecated since Symfony version 5.1

Interfaces:

- `Symfony\Component\Security\Http\Logout\LogoutHandlerInterface`
- `Symfony\Component\Security\Http\Logout\LogoutSuccessHandlerInterface`

Classes:
- `Symfony\Component\Security\Http\Logout\DefaultLogoutSuccessHandler`

We should check if we can update/remove the usage of those classes (without breaking compatibility with other Symfony versions), or otherwise keep this issue active until we increase the Symfony requirement to 5.1 or higher.

Related: #2857

**Update 2021-07-19:** Also check `Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy` from #3206

**Comment by fritzmg** [comment]
Also related to https://github.com/contao/contao/pull/2818. That bug would not occur with the new security components.

**Comment by aschempp** [comment]
I will most likely have a client budget (and time) to upgrade Symfony security this year 😎

**Comment by ausi** [comment]
I think `LogoutSuccessHandlerInterface` was already removed. 

`LegacyEventDispatcherProxy` only needs to be removed from the tests and from the `DeprecatedClasses`-phpunit-extension it seems.

`LogoutHandlerInterface` and `DefaultLogoutSuccessHandler` are still in use I think.

@bytehead can you confirm that?

**Comment by bytehead** [comment]
Yes, I can confirm that. I've added the `LogoutSuccessListener` to deprecate the `LogoutSuccessHandler`. I'm not sure how to replace the `LogoutHandler` - maybe we should integrate the logic to the `LogoutSuccessListener` and deprecate it as well?

**Comment by leofeyer** [comment]
Yes, if that works. 👍 Although, since we will switch to the new authentication system in Contao 5, maybe we should not spend too much time on this.

**Comment by bytehead** [comment]
The documentation says so (there is only one event in the new authentication system): https://symfony.com/doc/current/security.html#customizing-logout. I'll provide a PR.

**Comment by leofeyer** [comment]
@ausi Can I move this issue to the `5.0` milestone or is there anything left to do for Contao 4.13?

**Comment by ausi** [comment]
> I'm not sure how to replace the `LogoutHandler` - maybe we should integrate the logic to the `LogoutSuccessListener` and deprecate it as well?

Don’t know if the PR @bytehead wants to provide should go into 4.13 or 5.0?

**Comment by bytehead** [comment]
I'll bring it for 4.13 - totally missed this 🙈

**Comment by aschempp** [comment]
@bytehead I guess this has already been fixed?

**Comment by bytehead** [comment]
Not yet 😬

**Comment by bytehead** [comment]
Closed in favor of #4303
