### ISSUE TITLE
Adding "Activate All"-Option within "edit multiple"

### ISSUE THREAD

**Issue by FlorinvV** [contao/contao#2866]
I just came across an Idea, which could make copying bigger websites and site-trees a lot more simple.
By default, when copying a site within the site structure it is deactivated as well as its articles.

Now when I copy my whole site-tree with about 100 pages and over 500 articles, I have to manually go through all and activate them one for one.
My suggestion would be a addition to "edit multiple" like "generate aliases": "activate all". This option would activate all checked sites/articles and therefore I would just have to check all and then activate them by one click.

I hope my suggestion is any helpful for the development of a even greater Contao :D

BR
Florin

**Comment by fritzmg** [comment]
> I have to manually go through all and activate them one for one.

You can just select all and then override all.
