### ISSUE TITLE
Remove the "first", "even", "odd" and "last" CSS classes

### ISSUE THREAD

**Issue by asaage** [contao/contao#2868]
**Affected version(s)**

I think that's been forever.

**Description**

The generated classes of news_list items are mixed up
![image](https://user-images.githubusercontent.com/4138336/110792181-5b53ca80-8273-11eb-93ba-ed0d56dba044.png)

Not a big deal - i just wodered why i was getting strange results while using css like such:
```css
mod_newslist>.even { }
mod_newslist>.odd { }
/* vs */
mod_newslist>:nth-child(even) { }
mod_newslist>:nth-child(odd) { }
```
One/first is an odd number but i think somebody startet counting from zero 😂
FunFact: ```:nth-child(even/odd)``` behaves like ```.even``` if your mod_newslist has a headline.

**Comment by fritzmg** [comment]
Yes, it uses the zero-based index. This is the case everywhere in Contao, not just the newslist. It cannot be changed for BC reasons, at least not in Contao 4. If anything it should be removed (just like we did for articles).

**Comment by m-vo** [comment]
Fun fact: I tripped over the fact `nth-of-type()` uses a one-based index multiple times. I mean, come on, who starts counting at 1?! :smile:

**Comment by fritzmg** [comment]
Same. I am always unsure when using `nth-…(even/odd)` 😁 (but not because of Contao).

**Comment by aschempp** [comment]
we're using Math© (1 is an odd number), looks like CSS got it wrong 😆

**Comment by leofeyer** [comment]
As briefly discussed in Mumble on March 11th, we want to remove these classes in Contao 5.

**Comment by leofeyer** [comment]
Removed in #4178.
