### ISSUE TITLE
Redirect back on frontend login

### ISSUE THREAD

**Issue by AlexejKossmann** [contao/contao#2872]
**Affected version(s)**

Contao 4.9

**Description**

When using Frontend Login Module it is possible to set the option to redirect back after successfull login. The login Module is on its own page, and after login in the redirect url is the login page itself and not the previous page. This happen because `_target_path` is having the wrong url after login. But the referer url is correct.

this my be related to #569

**Comment by fritzmg** [comment]
Where exactly did you put the login module? On the `401` page? If yes, then you should _disable_ the redirect.

**Comment by AlexejKossmann** [comment]
@fritzmg no its on a regular, public page

**Comment by aschempp** [comment]
does `_target_path` point to the 401 page? Or the page where the login module is on?

**Comment by AlexejKossmann** [comment]
Yes, the `_target_path` points to the page where the login module is on, its not a 401. The redirect back page contains comments from the comments-bundle and needs login only to post new comments, the page itself is not 401

**Comment by chromagnon** [comment]
I have the same problem, testet with 2 contao 4.9.13 installations.

**Comment by leofeyer** [comment]
@fritzmg @aschempp Were you able to reproduce this?

**Comment by aschempp** [comment]
I had a similar issue just recently, though it didn't redirect at all. I might be able to figure this out in the coming days/weeks since a client needs the feature 😊

**Comment by Funbug** [comment]
I may have the same problem with 4.9.x and 4.13.2. I guess the target_path is not right. The login redirects to the wrong page. If you need a test case I can give you access to a website.

**Comment by Funbug** [comment]
Got it. I had to deactivate "Redirect on login" of the member groups because a member is in multiple groups and the "bottom" group was always used for forwarding. Instead, the redirect must be activated in the individual login modules. (Each member group has its own login page.)

In my case it was probably a misconfiguration on my part.

**Comment by chromagnon** [comment]
I still think its a bug. There is a memeber which is in only one group, there is no forwarding-page configured for that group and in the login-modul the option "redirect to last visited page after login" is activated, but it doesn't work! After login still the login-page is shown. It's the same bug after updating from 4.9 to 4.13.

**Comment by fritzmg** [comment]
I can confirm the issue. `_target_path` always points to the current URL, rather than the previous URL.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we would have to check the referrer header in the login module (in a safe way that ignores cross-domain request etc.) to add this feature again.
