### ISSUE TITLE
Get Subtititle (Untertitel) for Video/Auto Element from the File Metadata in the Filemanager

### ISSUE THREAD

**Issue by omuellersch** [contao/contao#2873]
The Video/Audio content element has its subtitle in the element's settings. It would be an improvement if the subtitle is displayed from the file metadata. Like the metadata of an image is processed.
It would be more coherent in the users workflow to edit all subtitles for media elements in the file manager.

**Comment by fritzmg** [comment]
Closing in favor of #3684
