### ISSUE TITLE
Provide migration for failed Version480Update migration

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#2881]
Due to https://github.com/contao/contao/issues/2822 there are some Contao 4 installations out there now which were not migrated correctly. There are two problems to solve:

* If the `Version480Update` fails, it will not be offered to be run again, since `ALTER TABLE tl_layout DROP picturefill` is executed right at the beginning of the migration. This should be moved to the end.
* Since the issue in #2822 happened in [this line](https://github.com/contao/contao/blob/cd9121439b195c2588fb741ba704a2e42e7bf729/core-bundle/src/Migration/Version408/Version480Update.php#L176) everything after it was not executed. We should implement a migration that detects a failed migration state and runs the necessary updates again (e.g. important part transformations).

**Comment by ausi** [comment]
Pull request: #2884

**Comment by leofeyer** [comment]
Without a doubt, #2884 is a much more robust and thus preferable way to write migrations.

However, I think it is wrong trying to fix a corrupted migration by adding other migrations that try to compensate. If a migration fails, the DB should be reset and a new migration should be started once the issue has been fixed.

**Comment by fritzmg** [comment]
> However, I think it is wrong trying to fix a corrupted migration by adding other migrations that try to compensate. If a migration fails, the DB should be reset and a new migration should be started once the issue has been fixed.

Most users will probably simply try again, if something has failed. At this point though, the migration will run without any error and thus it will not be known to the user that something is still wrong with their database. Any errors resulting from a failed migration might only surface after a longer period of time and at this point you will likely not be able to reset the database anymore.

**Comment by ausi** [comment]
I think switching to the “more robust” version should be enough. An extra migration for failed migrations should then not be necessary IMO.

**Comment by aschempp** [comment]
Shouldn't we just use transactions and revert if anything fails? After all, these are all DB migrations, right?

**Comment by ausi** [comment]
Transactions do not work in MySQL for changes to the database schema AFAIK.

**Comment by m-vo** [comment]
> Transactions do not work in MySQL for changes to the database schema AFAIK.

Correct.
