### ISSUE TITLE
Inconsistent parameters of label callback for tree view in picker widget

### ISSUE THREAD

**Issue by rabauss** [contao/contao#2882]
**Affected version(s)**

Contao 4.9+

**Description**

Unfortunately, the parameters for the call of `label_callback` are inconsistent for the tree view in the picker widget - see:
https://github.com/contao/contao/blob/cd9121439b195c2588fb741ba704a2e42e7bf729/core-bundle/src/Resources/contao/widgets/Picker.php#L281-L291

versus:
https://github.com/contao/contao/blob/cd9121439b195c2588fb741ba704a2e42e7bf729/core-bundle/src/Resources/contao/drivers/DC_Table.php#L4004-L4014

How should we solve this? I guess we need to add a further switch for mode 5 + 6 in the picker widget!

**Comment by fritzmg** [comment]
Well, the difference is documented here: https://docs.contao.org/dev/reference/dca/callbacks/#list-label-label 😁 

The missing 5th parameter is always `false`. The 6th parameter could may be added to the picker as well?

https://github.com/contao/contao/blob/cd9121439b195c2588fb741ba704a2e42e7bf729/core-bundle/src/Resources/contao/drivers/DC_Table.php#L3917-L3923

**Comment by rabauss** [comment]
Yes, I know that the confusing difference is well documented 👍 
But I added a new callback to a custom treeview with typehint and yesterday we wondered why our other entity throws errors because there the label callback is called in picker context.

In the tree view label callback the 4th param is no `array` - it is a `string`!
for 5th and 6th we can use the recommendation of @fritzmg

**Comment by fritzmg** [comment]
Oh right. I think that's may be a bug then, Contao should pass an empty array may be.

**Comment by aschempp** [comment]
we should absolutely fix the Picker widget to support both modes (because we obviously can't fix `DC_Table`). Sounds like an easy-pick for you @rabauss 😬
