### ISSUE TITLE
hasAccess($id, 'pagemounts') doesn't check parent page access

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#2895]
**Affected version(s)**

Contao 4.9 and above

**Description**
The $backendUser->hasAccess($objPage->id, 'pagemounts') only checks the current id and not the parent page ids. 
So if the page mount is set on a parent page id "false" is returned.

**Comment by xprojects-de** [comment]
Hallo zusammen,

da sich die Diskussion in Grenzen hält :-) (ist nicht schlimm) ist es für mich ok wenn ihr den Issue schliesst! An denen Stellen wo ich es brauche habe ich mir eine Methode gebaut. Dachte nur dass es vielleicht sinnvoll wäre das im Core zu berücksichtigen... Aber es gibt andere Themen welche wichtiger sind!

Trotzdem danke.

Grüße

**Comment by fritzmg** [comment]
@xprojects-de it is labeled as `up for discussion` so it will be discussed in the next public Mumble call.

**Comment by xprojects-de** [comment]
@fritzmg nice! Thanks. Sounds good...

**Comment by leofeyer** [comment]
As discussed in Mumble on April 8th, we agree that the `hasAccess()` method behaves inconsistently for pagemounts and filemounts. However, we cannot change the behavior as it would potentially grant access to more pages than before. We could fix it in one of the next major versions, however, it is very likely that we will use voters instead.

**Comment by aschempp** [comment]
Just to write down my thoughts, we must not extend `$backendUser->hasAccess` but improve our voter to change the behaviour. We could actually already have done that in 4.x imho since the voter can add new behaviour 🙈
