### ISSUE TITLE
Introduce foreign keys for possible tables

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#2896]
What do you think to introduce foreignKeys for possible tables (not possible for all tables!)? 
With InnoDB and mostly Mysql, this should be technically possible and would improve data integrity.
Especially if you work with an API to manage the data, it is very time-consuming to keep the data consistent. 

I can't say whether to go to Cascade or Restrict. But I think it would be good to have the security of integrity when modifing the data.
Maybe it is currently not possible through the DCA structure? :-)

**Comment by m-vo** [comment]
see #2318, #463

Unfortunately we cannot 'just' introduce FKs. This affects a whole lot inside `DC_Table`, schema creation + update alone are extremely complex (that's why you would use doctrine entities in the first place), data integrity is hard to "patch" without breaking stuff, we're using dynamic parent tables and so on…

It's definitely a thing we should get going in the future and I fully agree on the importance of the data integrity aspect, but IMHO #2318 is the first milestone, we need to achieve for this.

**Comment by xprojects-de** [comment]
I agree with you, and for future I think it's wrong to use one field (pid) for different parent tables. In my opinion, every parent table should have its own field in the child table where a ForeignKey Contraint can be set.
e.g. Article <-> Content (pArticle), Content (pNews) <-> News
So a better integrity can be achieved.
... also this way the Bundle itself can "decide" which contraint (CASCADE, RESTRICT,..) should be used...
... and so you are not forced to use entities (there are also people who like to work with the QueryBuilder :-) hehe )

**Comment by xprojects-de** [comment]
... sorry, i just learned that there are two different types of QueryBuilder :-) One for ORM and one for DBAL...! :-)
So it can really work for more complex queries to use the ORM queryBuilder and to make it accessible via repository. 
However, I do not know whether the Entity constrains are checked in the ORM QueryBuilder!?

**Comment by m-vo** [comment]
I don't get what you mean.  The query builder is only a tool to, well, query results.

It doesn't have anything to do with the integrity of your data. Constraints are enforced on a database level (preferred) or as lifecycle events if the database type doesn't support it. Relying on the latter for integrity is a bad choice.

**Comment by xprojects-de** [comment]
Yes I know that. Then I misunderstood your statement above ... 
I thought you meant that you only want to check the constrains in the entities and want to create the database layer without constrains. That confused me a bit.
 
-----
EDIT: 
It's okay for me. I just wanted to address the topic :-) Ticket can be closed. You will solve this correctly, definitely great!
