### ISSUE TITLE
Model::findMultipleByIds() fails when asked to return an array

### ISSUE THREAD

**Issue by patrickjDE** [contao/contao#2897]
**Affected version(s)**

Contao 4.9.12

**Description**

When called with the option `'return' => 'Array'`, findMultipleByIds throws an error:

> "Call to a member function next() on array" at contao/core-bundle/src/Resources/contao/library/Contao/Model.php line 872.

There's simply no logic in place to handle an array returned from the call to `find()` in line 868.

**Comment by fritzmg** [comment]
This should be easily fixable by using `foreach` instead of `while` in line 872. Then it does not matter whether `return` is set to `Array` or `Collection`.

**Comment by fritzmg** [comment]
Closing in favor of #2899
