### ISSUE TITLE
Formular zeigt beim Absenden ungültiges Anfrage-Token

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#29]
**Affected version(s)**
Contao 4.4.21
Unter Contao 4.5.12 konnte ich KEINE Probleme feststellen.

**Description**  
Wird ein Formular abgesendet kommt es zum Fehler "Ungültiges Anfrage-Token".
Fehler hängt vermutlich irgendwie mit dem Session-Cookie zusammen.

**How to reproduce**  
1. Formular erstellen
2. Aus dem Backend abmelden
3. Alles Cookies löschen bzw. Inkognito-Modus nutzen
4. Unterseite mit Formular aufrufen
5. Formular absenden -> Ungültiges Anfrage-Token
6. Formular erneut aufrufen und absenden -> Alles ok

Unterschied dabei.
Beim 1. Versuch gibt es keine PHPSESSID und beim 2. Absenden ist diese vorhanden und es funktioniert.

**Comment by rabauss** [comment]
I can confirm this problem - but I do not know since when that happens.

**Comment by fritzmg** [comment]
@contaoacademy have you noticed this problem (with this exact reproduction) before Contao 4.4.21 as well?

**Comment by rabauss** [comment]
I downgraded to ``contao/core-bundle`` to ``4.4.20`` and the problem doesn't occur or is not reproducable anymore. the token is not generated identically and then the validation fails ...

see also: https://github.com/contao/contao/issues/11

Well, the Problem would be, that in c4.4. the [CsrfTokenCookieListener](https://github.com/contao/core-bundle/blob/master/src/EventListener/CsrfTokenCookieListener.php) is missing!
And so the cookie ``csrf_contao_csrf_token`` is not set for fallback like in >=4.5...

**Comment by fritzmg** [comment]
I see, thank you. Seems like this is may be the same problem as #11

**Comment by leofeyer** [comment]
CRSF in Contao 4.4 is based on the session, therefore I assume this is caused by 5be1f87a0047e71dec8f5c7209862fba5d7883a4.

**Comment by leofeyer** [comment]
Fixed in 7a980dd6e4eeae542cb59c33ce2a49518d9f0457.

**Comment by stefan-at-work** [comment]
Doesn't seem to be fixed.
https://community.contao.org/de/showthread.php?71733-Formular-und-Ung%C3%BCltiges-Anfrage-Token-(invalid-request-token)&p=480908&viewfull=1#post480908

**Comment by leofeyer** [comment]
Please use the latest version (4.4.23). It should be fixed there.
