### ISSUE TITLE
The alert icon tooltip is not aligned correctly

### ISSUE THREAD

**Issue by xchs** [contao/contao#290]
**Affected version(s)**

Contao 4.4 – 4.7

**Description**

The tooltip shown on mouseover the alert icon is not aligned properly:

![tt_alert](https://user-images.githubusercontent.com/1218766/51428823-7503a500-1c08-11e9-8b61-cc76506ab67a.png)

**How to reproduce**  

* Log into the Contao back end
* Mouseover the alert icon

**Comment by mktcode** [comment]
Same for Preview...

![image](https://user-images.githubusercontent.com/6792578/51462198-54e6f980-1d60-11e9-94c0-de2463a868a1.png)

**Comment by leofeyer** [comment]
It works for me though:

<img width="336" alt="" src="https://user-images.githubusercontent.com/1192057/51522340-6cd68000-1e29-11e9-9a54-0e5c0e5dbfd9.png">

Which browser and OS are you using?

**Comment by asaage** [comment]
I can confirm this for Chrome and FF on Windows and Chromium and FF on Linux.
If the Browserwindow-width however is below ~1600px the Preview Tooltip is aligned correctly and only the alert one is not.

**Comment by xchs** [comment]
> Which browser and OS are you using?

Chrome / Windows 10

**Comment by leofeyer** [comment]
Fixed in de175e4dbe8f183bf685be3fe1ba8a8dad8dfb4a.
