### ISSUE TITLE
The confirmation icon is not displayed correctly

### ISSUE THREAD

**Issue by xchs** [contao/contao#291]
**Affected version(s)**

Contao 4.7.0-RC2

**Description**

The icon (`ok.svg`) for the 2FA confirmation message is not shown correctly:

![2fa](https://user-images.githubusercontent.com/1218766/51428688-dcb8f080-1c06-11e9-9269-d1bf2deb68a6.png)

That's due to this change: https://github.com/contao/contao/commit/a9dc17c4d2b104245825b78ed235c6c32b6a8445#diff-03b082bb15add2cde9485b9a27924578R359

**How to reproduce**  

* Set up a new Contao 4.7.x installation
* Enable the two-factor authentication

**Comment by leofeyer** [comment]
Good catch. 👍

**Comment by xchs** [comment]
Affects also the other message types, e.g. when the maintenance mode is activated:

![maintenance](https://user-images.githubusercontent.com/1218766/51433121-10fed200-1c44-11e9-9bd4-daf79d212e37.png)

**Comment by leofeyer** [comment]
Fixed in b735737fc58c1c0944a85d50c86e4f8767d2e953.
