### ISSUE TITLE
Update auf 4.11.2 

### ISSUE THREAD

**Issue by jonnysp** [contao/contao#2921]
Morgen,

kann mir gerade mal einer helfen!! 
habe grade 5 kundenseiten geupdatet auf 4.11.2 und nichts geht mehr kein **Installtool** kein **Backend** keine **Logs**, nur das Installtool geht. downgrade klappt auch nicht. neuinstall geht auch nicht.  wie bekomm ich die seiten wieder online?

**Comment by aschempp** [comment]
Wende dich bitte an die Support-Kanäle von Contao, hier geht es um Bug- und Feature-Tracking von Contao.
https://to.contao.org/support

**Comment by aschempp** [comment]
Nach einer Diskussion im öffentlichen Slack-Kanal, hier ist der Grund (https://github.com/symfony/symfony/issues/40618) und die temporäre Lösung (https://github.com/contao/conflicts/pull/22) für das Problem 🙃

**Comment by jonnysp** [comment]
@aschempp 

Danke hat funktioniert!
