### ISSUE TITLE
DCA panels depend on specific order

### ISSUE THREAD

**Issue by bezin** [contao/contao#2932]
**Affected Versions**
Contao 4.9

Hello there,

in a recent project we had the issue that `DC_Table` ignored our `filter`and `search` panels for the `limit` panel and back-end pagination. The search by e-mail-address results in three entries, which are correctly listed (not visible in the screenshot). The pagination and the `limit` panel however still take all some hundred entries into account.

<img width="222" alt="2021-03-31 10_56_09" src="https://user-images.githubusercontent.com/4400435/113127851-82ba0980-9219-11eb-9d52-11329cd46fcf.png">

The panel configuration in this case was `limit;search;sort`. Because the search panel sets the actual search conditions and values, the limit menu rendered as no search took place. The limit menu then sets the limit for the pagination, hence the pagination is off, too. Defining the panels with `search;sort;limit` fixed this issue.

We should compile the panels in the order necessary to properly work and than reorder them to what was defined by the developer. I'll provide a PR for this as soon as I find the time :-)

Cheers

**Comment by aschempp** [comment]
I think this should be qualified as a known limitation 🙈
