### ISSUE TITLE
Models in Registry include additional data for non-existent columns

### ISSUE THREAD

**Issue by ausi** [contao/contao#2934]
```php
PageModel::findByPk(2)->subpages; // null
PageModel::findPublishedSubpagesWithoutGuestsByPid(1);
PageModel::findByPk(2)->subpages; // "5"
```

This can lead to very weird bugs.
_(I had an issue where a navigation module displayed subpages only on a page where a sitemap module was present)_

To fix this, I think we should remove the subpages column before creating the collection in https://github.com/contao/contao/blob/9864858d36a8319b68b21d3c0f7b912a9d205fc7/core-bundle/src/Resources/contao/models/PageModel.php#L612 and add them back to copies of the models before returning.

This way we can keep the performance benefit of the registry.

Also I’m a bit confused by https://github.com/contao/contao/blob/9864858d36a8319b68b21d3c0f7b912a9d205fc7/core-bundle/src/Resources/contao/models/PageModel.php#L95 
Does someone know a case where `$pageModel->subpages` is actually an array instead of a string-int?

**Comment by leofeyer** [comment]
It should be an array, because there can be multiple subpages, right?

**Comment by ausi** [comment]
As far as I can see, `subpages` is only used in `PageModel::findPublishedSubpagesWithoutGuestsByPid()` and in that query it is a count of pages: `SELECT p1.*, (SELECT COUNT(*) FROM tl_page p2 WHERE …) AS subpages`

So `$objPages->subpages` is something like `"5"` in that case.

**Comment by leofeyer** [comment]
Ah, it is a count value. Then the `@property` is wrong of course. 👍🏻

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/2935
