### ISSUE TITLE
Not setting doctrine.dbal.override_url to true is deprecated

### ISSUE THREAD

**Issue by aschempp** [contao/contao#2938]
**Affected version(s)**

Contao 4.9+

**Description**

> Not setting doctrine.dbal.override_url to true is deprecated. True is the only value that will be supported in doctrine-bundle 3.0.

I get this deprecation notice in Contao 4.9, I guess we should add that to our doctrine configuration (most likely if we read a parameters.yml and override the URL from parameters.

**Comment by leofeyer** [comment]
This has also been fixed in #1889.

**Comment by aschempp** [comment]
@leofeyer has this been fixed? Then we should close it?
