### ISSUE TITLE
The "metadata_cache_driver" configuration key is deprecated.

### ISSUE THREAD

**Issue by aschempp** [contao/contao#2939]
**Affected version(s)**

Contao 4.9+

**Description**

> The "metadata_cache_driver" configuration key is deprecated. PHP Array cache is now automatically registered when %kernel.debug% is false.

Got this deprecation notice from doctrine-bundle. Looks like our default doctrine cache configuration is outdated?

**Comment by leofeyer** [comment]
We have already fixed that in #1889. Do we have to backport the changes?
