### ISSUE TITLE
Remove the tabindex field from the form generator

### ISSUE THREAD

**Issue by minstyle** [contao/contao#2949]
_Contao 4.9.13_

For the checkbox menu and the radio button menu, please add the options to define a `tabindex`, as it is already possible with other form fields.

**Checkbox menu**

![image](https://user-images.githubusercontent.com/2649562/114558771-5071c880-9c6b-11eb-8242-124a23e7575f.png)

**Radio button menu**

![image](https://user-images.githubusercontent.com/2649562/114558860-667f8900-9c6b-11eb-89b7-e713f6822026.png)

**Working example for `tabindex`**

![image](https://user-images.githubusercontent.com/2649562/114558488-00930180-9c6b-11eb-8c7d-438d8fc8b76a.png)

**Comment by ausi** [comment]
I think we should instead deprecate the tabindex field and remove it in a future version.

> Avoid using `tabindex` values greater than 0. Doing so makes it difficult for people who rely on assistive technology to navigate and operate page content. Instead, write the document with the elements in a logical sequence.

<https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex>

**Comment by ausi** [comment]
Also, is adding `tabindex` to the checkbox and radio button menus even possible? Would every checkbox/radio button from the menu get the same `tabindex` value then?

**Comment by minstyle** [comment]
https://www.w3.org/TR/wai-aria-practices/examples/radio/radio-1/radio-1.html

**Comment by ausi** [comment]
https://www.w3.org/TR/wai-aria-practices/#keyboard-interaction-7

**Comment by leofeyer** [comment]
@contao/developers Is there anything against removing the tabindex field already in Contao 4.12?

**Comment by fritzmg** [comment]
We should remove it from the palette and the templates, but keep the database field for BC.

**Comment by ausi** [comment]
IMO we should keep it. If you rely on the tabindex currently, removing it will break the behaviour without telling the admin who updates the installation. I think we should deprecate it and remove it in Contao 5.
