### ISSUE TITLE
Leere Detailseiten von News und Events ist in XML-Sitemap indexiert

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#2950]
**Affected version(s)**

Contao 4.9 

**Description**

Wenn man eine Übersichtsseite und eine Detailseite für Nachrichten oder Events erstellt und die Module integriert, werden die Detailseiten mit in der XML-Sitemap indexiert.

- Übersichtsseite mit Listen-Modul (news.html)
-- Detailseite mit Leser-Modul (news/details.html)
...

XML-Datei:

- <url><loc>.../news.html</loc></url>
- <url><loc>.../news/details.html</loc></url>
- <url><loc>.../news/details/foo.html</loc></url>
- <url><loc>.../news/details/goo.html</loc></url>
- <url><loc>.../news/details/moo.html</loc></url>`

Wenn man die `.../news/details.html` aufruft, wird eine leere Seite angezeigt. Ist die Seite in XML-Sitemap, wird SEO technisch mit berücksichtigt.

Stellt man in den Seiteneinstellungen auf `noindex` so wird die Seite nicht indexiert aber auch alle andere Seiten wie `.../news/details/goo.html` und `.../news/details/moo.html` auch. 

**Possibilities**

Mögliche Lösung könnte eine neue Seitentyp wie **Reader page** sein, bei dem man sicher ist, das sie nur Reader-Module beinhaltet und somit nur die weiterführende Aliase berücksichtigt werden. (nur ein Vorschlag)

`.../news/details.html` nicht in XML-Sitemap berücksichtigen, `.../news/details/*` in XML-Sitemap berücksichtigen.

**Comment by fritzmg** [comment]
Did you enable the **Require an item** setting for the reader page?

**Comment by havutcuoglu** [comment]
Wow. I didn't know this option.
I tried now and it's work fine. Thank you very much @fritzmg 

Sorry for this unnecessary issue 🤓  Now it's closed
