### ISSUE TITLE
Fehlende Sprachen

### ISSUE THREAD

**Issue by Alok-ctrl** [contao/contao#2953]
Contao 4.9

Hallo, beim update einer Installation von 3 auf 4 ist mir aufgefallen, dass leider nicht mehr alle Sprachen vorhanden sind, hier konkret schwedisch. Nach der Anleitung der Contao-Academy https://contao-academy.de/blog/contao-4-dcaconfig-und-langconfig habe ich die Texte für die Newsletter-Frontend-Module in einer /contao/languages/sv/default.xlf angelegt. Nun will ich weitere wichtige Texte (Fehlermeldungen Formularabsendung usw.)  anlegen. Welche Vorgehensweise ist ratsam:
-	Alle Übersetzungen in die gleiche /contao/languages/sv/default.xlf eintragen 
-	Oder in den entsprechenden Ordnerstrukturen eigene Ordner „sv“ anlegen, z.B. vendor/contao/core-bundle/src/Resources/contao/languages/sv/default.xlf . Wären diese dann auch updatesicher?
- 
Gibt es Pläne die „verlorenen“ Sprachen wieder aufzunehmen?

Danke im Voraus
Alok

**Comment by bytehead** [comment]
Schwedisch ist durchaus noch vorhanden, aber der Übersetzungsstatus (84.2% im Core-Bundle) wird wohl zu tief sein, damit die Sprache mitausgeliefert wird: https://www.transifex.com/contao/core-bundle/

**Comment by fritzmg** [comment]
> Gibt es Pläne die „verlorenen“ Sprachen wieder aufzunehmen?

If you speak Swedish yourself or know someone who does you can ask them to register on Transifex and apply for the Swedish translation team for contao/core-bundle there.

**Comment by Alok-ctrl** [comment]
Danke für die Antworten. Gibt es noch einen Tipp wie ich vorgehen sollte, bezüglich der akut benötigten Übersetzungen aus meiner Frage? Also:
Alle Übersetzungen in die gleiche /contao/languages/sv/default.xlf eintragen
Oder in den entsprechenden Ordnerstrukturen eigene Ordner „sv“ anlegen, z.B. vendor/contao/core-bundle/src/Resources/contao/languages/sv/default.xlf . Wären diese dann auch updatesicher?

@fritzmg : weißt Du an wen man sich wenden kann, zwecks einer Registrierung für die Teilnahme an der Übersetzung?

**Comment by fritzmg** [comment]
> Alle Übersetzungen in die gleiche /contao/languages/sv/default.xlf eintragen
> Oder in den entsprechenden Ordnerstrukturen eigene Ordner „sv“ anlegen, z.B. vendor/contao/core-bundle/src/Resources/contao/languages/sv/default.xlf . Wären diese dann auch updatesicher?

Update-sicher kannst du es im Ordner `contao/languages/sv/` machen.

> @fritzmg : weißt Du an wen man sich wenden kann, zwecks einer Registrierung für die Teilnahme an der Übersetzung?

Du musst dich nur auf Transifex registrieren und dann hast du die Möglichkeit bei `contao/core-bundle` auf "Join Team" zu klicken, wo du dann die Sprachen auswählen kannst, bei deren Übersetzung du helfen möchtest. Dein Antrag wird dann geprüft und ggf. wirst du dann dafür freigeschalten.

**Comment by Alok-ctrl** [comment]
@fritzmg. Danke. Ist dann Transifex mit Kosten für mich verbunden? Da auf der Registrirungsseite steht "15 days free trial". Und dann?

**Comment by fritzmg** [comment]
Ich denke Kosten fallen nur an, wenn du selbst eigene Projekte übersetzen lassen möchtest.

**Comment by Alok-ctrl** [comment]
Danke für die Info. Weißt Du, an wen man sich diesbezüglich wenden kann, wer also der Chef dieses Übersetzungsprojekts bei Contao ist und dann auch genau sagen kann, ab welchen Prozentsatz eine Sprache dann wieder aufgenommen wird in den Core, wie das mit den Kosten genau ist usw.?

**Comment by fritzmg** [comment]
@leofeyer manages it and knows the threshold. But the threshold should not matter to you anyway. If you want to provide the missing translations, you should provide all of them, not just some of them, shouldn't you? ;)

**Comment by leofeyer** [comment]
Eine Übersetzung muss mindestens zu 95% fertig sein, damit wir sie in die Distribution aufnehmen.

**Comment by Alok-ctrl** [comment]
@leofeyer Wie ist die Vorgehenweise, damit wir bei der schwedischen Übersetzung mitmachen können?
Sind Kosten für uns damit verbunden?

**Comment by aschempp** [comment]
Es sind keine Kosten damit verbunden. Registriere dich bei https://www.transifex.com/signup/ (oder verwende dein GitHub Konto, das hast du ja bereits). Danach gehst du auf https://www.transifex.com/contao/core-bundle/language/sv/ und klickst oben rechts im Menü hinter den drei Punkten auf "Join Team".

<img width="1038" alt="Bildschirmfoto 2021-04-15 um 08 07 07" src="https://user-images.githubusercontent.com/1073273/114822113-e1f34e80-9dc1-11eb-9beb-76e24a43537f.png">

**Comment by Alok-ctrl** [comment]
@aschempp Danke für die Info. Werde mir das ansehen.

**Comment by Alok-ctrl** [comment]
@aschempp Dieser Link von Dir  https://www.transifex.com/contao/core-bundle/language/sv/ führt mich leider immer nur zu https://www.transifex.com/contao/core-bundle/ und wenn ich dort auf Join team klicke, erscheint im folgenden Auswahlmenü nicht Swedish. Was mache ich falsch?

**Comment by ausi** [comment]
Ich habe das grade getest, bei mir erscheint Swedish.
<img width="690" alt="Bildschirmfoto 2021-04-22 um 12 46 30" src="https://user-images.githubusercontent.com/367169/115702148-db884800-a368-11eb-93f3-9fc5dbf3458a.png">
Ist Spanish und Tamil bei dir zu sehen?

**Comment by Alok-ctrl** [comment]
Sorry bei mir nicht. Oder bin ich in Schwedisch bereits registriert und es erscheint deshalb nicht? Nach Spanish kommt bei Tamil.
Falls ich schon registriert sein sollte für schwedisch, wie komme ich dann dahin?

**Comment by fritzmg** [comment]
Wurdest du schon freigeschalten?

**Comment by Alok-ctrl** [comment]
Hallo wir haben an der Übersetzung ins schwedische gearbeitet und würden uns sehr über eine Aufnahme in die Distribution freuen...
![Screenshot_2021-05-04 The core-bundle translation project on Transifex(3)](https://user-images.githubusercontent.com/81610253/117036539-d2529000-ad05-11eb-8bc2-ba2c0834abd9.png)
