### ISSUE TITLE
Make HTTPS the default protocol for root pages

### ISSUE THREAD

**Issue by ausi** [contao/contao#2968]
**Affected version(s)**

Contao 4.11

**Description**

Since #2323 you have to choose between using HTTP and HTTPS for every root page. I think it would make sense to change the default to HTTPS, because thats the recommeded protocol and nowadays most webspaces already use HTTPS by default AFAIK.

**Comment by fritzmg** [comment]
I am not sure about this. This will surely cause additional confusion in the community. I think in most cases HTTPS is _not_ available when setting up a Contao instance initially, e.g. when first installing it on a remote host or when installing it locally. I bet most people do not have their local web server set up for this.

The fact that we redirect from HTTPS to HTTP is already causing enough problems. May be all of this can be handled in a more user-friendly way?

**Comment by ausi** [comment]
> May be all of this can be handled in a more user-friendly way?

How about using the protocol from the current backend request when the user creates the root page in the backend?

**Comment by fritzmg** [comment]
Yes, I think that would be sensible :)

**Comment by ausi** [comment]
Closed in favor of #2991
