### ISSUE TITLE
Bezeichnung bei Registrierungsmodul anpassen

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#2972]
**Affected version(s)**
Contao 4.9+

**Description**
Beim Modul "Registrierung" wird das Passwort abgefragt.
Aktuelle Labels: `Passwort` und `Bestätigen`

Ein Feedback von einem Kunden war, dass die neuen Benutzer nicht klarkommen, weil Sie bei dem Feld `Bestätigen` erwarten, dass hier schon ein spezieller Bestätigungscode eingetragen werden muss. Es werden also unnötige Supportfälle generiert.

**Vorschlag:**
Änderung des Labels `Bestätigen` auf `Passwort wiederholen`

**Comment by leofeyer** [comment]
"Repeat password" scheint mit jedoch nicht so gebräuchlich wie "Confirm password". Abgesehen davon, dass das Bestätigungsfeld sowieso entfernt werden sollte: https://uxmovement.com/forms/why-the-confirm-password-field-must-die/

**Comment by contaoacademy** [comment]
Danke für den Hinweis. Soll ich das Ticket dann schließen? Die Lösung ohne Bestätigungsfeld wäre mir auch lieber.

**Comment by aschempp** [comment]
Hier auch eine Video-Fassung derselben Ideen 😊 
https://www.youtube.com/watch?v=alGcULGtiv8

**Comment by leofeyer** [comment]
> Soll ich das Ticket dann schließen?

Nein, sonst vergessen wir es ja wieder. 😄

**Comment by leofeyer** [comment]
Wie am 12. Mai auf Mumble besprochen, wollen wir das Bestätigungsfeld in Contao 4.12 entfernen. Ich lasse das Ticket aber noch auf dem 4.9er-Milestone, damit wir daran denken, das Label zu ändern.
