### ISSUE TITLE
Symlinks in back-end file manager are displayed like regular directories

### ISSUE THREAD

**Issue by gmpf** [contao/contao#2974]
**Affected version(s)**

Contao 4.9, likely 4.10 as well

**Note:** This has nothing to do with symlinking from `web/files/…` to `files/…`.

**Issue**

Symlinks from one directory to another within `files/` are displayed as distinct directories.

**Reproduction**

```
cd files
mkdir foo
touch foo/example.txt
ln -s foo bar
```

Open the file manager in Contao. You see two directories, `foo` and `bar`, both seemingly containing separate `example.txt` files.

**Expected behavior**

The symlink is either not shown at all or it is shown, but cannot be opened and shows a marker that clarifies that this is a symlink, similar to the way redirect pages are marked with a blue arrow in the page tree.

**Use case**

An editor who creates newsletters manages a directory that used to be called `newsletter_images`. It was decided that the directory shall be renamed to `newsletter` because it also hosts other types of files linked from the newsletters. Renaming the directory is problematic because all file references in newsletters that had already been sent would then be broken on the recipient side. As a solution, we renamed the directory `newsletter_images` to `newsletter` and created a symlink `newsletter_images -> newsletter`. The entire directory is now visually duplicated in the file manager, once shown as `newsletter` and once as `newsletter_images`.

*Edit:* I later switched to using redirects for this specific case. The issue is not about this specific case exclusively.

**Comment by m-vo** [comment]
It would probably be easier to work around the issue on the webserver side (redirecting the image requests).

Symlink support would be nice but I bet there are few tricky bits involved.

**Comment by fritzmg** [comment]
> **Expected behavior**
>
> The symlink is either not shown at all or it is shown, but cannot be opened and shows a marker that clarifies that this is a symlink, similar to the way redirect pages are marked with a blue arrow in the page tree.

This should _not_ be the expected behaviour. Otherwise you would not be able to use "external" directories in the Contao file manager that have been made available via symlink. Granted there may be other things that prevent this, but the current behaviour is the expected behaviour in my opinion.

If you do not want the folder to be visible for your back end users, then do not add the folder to their folder mounts.

**Comment by gmpf** [comment]
> It would probably be easier to work around the issue on the webserver side (redirecting the image requests).

That is what I ended up doing. The overhead is worse, though.

> Symlink support would be nice but I bet there are few tricky bits involved.

I think that depends on how far you want to take it and whether what you mean by "tricky bits" refers to technical issues or issues of clashing expectations for what should actually happen.

> This should not be the expected behaviour. Otherwise you would not be able to use "external" directories in the Contao file manager that have been made available via symlink. Granted there may be other things that prevent this, but the current behaviour is the expected behaviour in my opinion.

This reads more like a possible clash of use cases to me. I don't see why a symlink out of `files/` into an entirely different directory is a more valid use case than using symlinks within `files/`. Without knowing the specific case, it is easy for me to say, "What is the point of that? Just put that directory in `files`." But of course there is some reason, for otherwise it wouldn't have been done.

Surely, there is currently no official support from Contao for either of these cases. One just happens to be usable while the other does not.

**However, I think they can be reconciled.**
We could differentiate between "target is outside `files/`" and "target is within `files/`".
Or we could have a setting in the properties of "directories" that are symlinks, with the options "show as symlink" or "show as directory". That would be a new feature though, which I'd happily contribute.

Funny side note: This issue wouldn't exist if Contao still used the old-school method of having a curated list of directories that are supposed to be excluded from the file manager. No, I don't want to go back to that, I just thought it was interesting.

> If you do not want the folder to be visible for your back end users, then do not add the folder to their folder mounts.

This is indeed a point against the specific use case in my original post, but I don't think it can be generalized as such. It seems to imply that any directory name an editor created _within their file mount_ is required to not be changed afterwards in this type of case.

Say they create a new directory every month, for the files specific to that month's newsletter, and they changed their naming scheme from `February` to `02_Feb` for whatever reason (something like this has actually happened). Is the expectation that the newsletter editor is given dozens of file mounts over the course of the years, one for each month, with a new one added every month by the site admin? Surely not.

Overall, I'm not sure how useful it is to discuss whether specific examples hold water as opposed to the general question of symlinks in the file manager.

**Comment by fritzmg** [comment]
> Say they create a new directory every month, for the files specific to that month's newsletter, and they changed their naming scheme from `February` to `02_Feb` for whatever reason (something like this has actually happened). Is the expectation that the newsletter editor is given dozens of file mounts over the course of the years, one for each month, with a new one added every month by the site admin? Surely not.

Why would you need a symlink for that? Within Contao you don't need a symlink (just rename the folder within the file manager) and for accessing these resources externally via their old URL you can (and should) use redirects.

**Comment by gmpf** [comment]
> Within Contao you don't need a symlink (just rename the folder within the file manager)

Yes, I know.

> for accessing these resources externally via their old URL you can (and should) use redirects.

Which I ended up doing, as written in the very beginning of the post from which you're quoting. There are advantages of using symlinks over redirects here, but none of the advantages were significant enough, which is why I switched to using redirects.

Back to the general question:
Is the current implementation of displaying symlinks in the file manager the way it should be?

I opened this issue because the way this looked in the file manager seemed odd to me. It sparked a worry about the kinds of problems that can be encountered with symlinks in `files/`. I had no idea that some might actually want it to look that way. I don't want to doubt either viewpoint.

Looking at the actual implementation, I think it's pretty clear that the way symlinks are treated in the file manager isn't an intentional feature. `DC_Folder` simply assumes that whatever isn't a file according to `is_file()` is a folder:

https://github.com/contao/contao/blob/2e762a3eee71ce6076d51cb3fd64cfa0b6ce6758/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L2598-L2609

I think it's reasonable to consider whether that's the way it should be.

Any thoughts on my suggestion?
> Or we could have a setting in the properties of "directories" that are symlinks, with the options "show as symlink" or "show as directory". That would be a new feature though, which I'd happily contribute.

**Comment by m-vo** [comment]
> I don't see why a symlink out of files/ into an entirely different directory is a more valid use case than using symlinks within files/. 

Symlinks in general are a way to abstract 'physical' location. An application should IMO not interfere with this. There are other things like bindfs or mounting that achieve similar things that are completely transparent to the application. But fully supporting this - no matter if coming from a higher FS level or "visible to the app" as symlinks - also includes a lot of special cases like references that point to an inaccessible or missing resource or to its own parent (recursion). AFAIK Contao does not support any of this.

Tbh, I didn't miss those features, yet. Maybe you could clarify what you mean with "There are advantages of using symlinks over redirects here". 

Keep in mind that some limitations do not "only" target `DC_Folder` but also the implementation of the DBAFS itself.

**Comment by gmpf** [comment]
> Symlinks in general are a way to abstract 'physical' location. An application should IMO not interfere with this.

How would implementing my suggestion interfere with abstracting 'physical' location? Note that the suggestion is simply one of giving the user a choice of how to display the symlink: Basically, "should this be displayed as just a line with a folder+arrow icon" or "should this be displayed as a directory that you can open (maybe also with a folder+arrow icon instead of the normal one)"?

> also includes a lot of special cases like references that point to an inaccessible or missing resource or to its own parent (recursion). AFAIK Contao does not support any of this.

That is entirely correct. But Contao has neither support nor no support, it has a sort of "symlinks don't exist" treatment (maybe that is what you mean by Contao not interfering with the abstraction). The issues you describe are already a problem the way it is now. Consider this:
```
cd files
mkdir foo
ln -s foo bar
rm -r foo
```
Now, the file manager displays the link `bar`, that doesn't have a target, as a directory, with an extra editor–disabled icon that you would normally find on text files. Whether the target was once inside `files/` or elsewhere doesn't matter.

To me, all of this reads as supporting the notion that Contao does not support symlinks inside `files/`, no matter where the target may be, i. e. one should not create a symlink in `files/`, full stop. I can understand that standpoint. However, if it's supposed to mean that symlinks that point to another point outside `files/` do not have the same problems, I do not follow.

> Keep in mind that some limitations do not "only" target `DC_Folder` but also the implementation of the DBAFS itself.

That is true. The issue described concerns the UI of the file manager. Maybe it is also not good that the DBAFS does not differentiate, but my suggestion is entirely possible without overhauling that part.

**Comment by asaage** [comment]
I think thats a big can of worms.
Symlinking stuff from the outside into files should just be treated like physikal.
As there is no userinterface in the BE to do such thing one can assume, the person doing so knows what he's doing.
For stuff inside of files i think redirects is the way to go: nobody wants to deal with duplicates in the DBAFS or see it explode because of a recursion.

**Comment by fritzmg** [comment]
Just think of the file manager as if you are connected via an FTP client.

But we can of course fix bugs like the edit icon being shown for invalid symlinks.

**Comment by patrickjDE** [comment]
> > Symlinks in general are a way to abstract 'physical' location. An application should IMO not interfere with this.
> 
> How would implementing my suggestion interfere with abstracting 'physical' location? Note that the suggestion is simply one of giving the user a choice of how to display the symlink: Basically, "should this be displayed as just a line with a folder+arrow icon" or "should this be displayed as a directory that you can open (maybe also with a folder+arrow icon instead of the normal one)"?

One possible problem I see with that option, is that the user does not necessarily know the reasoning behind the existence of said symlink and might lock themself out of some folder they're meant to have access to, by not showing the symlink as a directory. Also that might need to be a "per symlink" configuration, which further complicates things.

I can see the benefit of being able to tell that a directory or file is a symlink, e.g. by a different icon, but for anything further, I'm not convinced.

**Comment by leofeyer** [comment]
As discussed in Mumble on July 1st, we want to keep the current behavior. We explicitly want to support symlinks in the file manager and show them as regular folders.
