### ISSUE TITLE
eval rgxp url

### ISSUE THREAD

**Issue by asaage** [contao/contao#2976]
Is it intentional that field-configurations in dca-files with
```
'eval' => array( 'rgxp'=>'url'...
```
accept pretty much anything maybe to be able to store ```{{insert::tags}}``` or ```#onpagelinks```?

**Comment by fritzmg** [comment]
Yes. If you want to force absolute URLs, then you need to use `httpurl` (forgot to merge https://github.com/contao/docs/pull/566 once 4.11 got released).

**Comment by asaage** [comment]
Oh i missed that https://github.com/contao/contao/pull/2704
Still on 4.10 though
