### ISSUE TITLE
The maxlength for a date field does not observe the length of the actual date

### ISSUE THREAD

**Issue by zonky2** [contao/contao#2978]
**Affected version(s)**

Contao 4.9

**Description**

The maxlength for a date field does not observe the length of the actual date.

timestamp usually has int(10) and therefore the maxlength is 10 - with `27.04.2021` this is still o.k. but not with `27.04.2021 09:43`

see https://github.com/contao/contao/blob/13ca9de98fdef79992a094d962ae9297138a8b24/core-bundle/src/Resources/contao/library/Contao/Widget.php#L1372

**Comment by fritzmg** [comment]
I think this probably needs to be changed to something like

```php
if (!isset($arrAttributes['maxlength']) && $arrAttributes['sql']['type'] ?? null === 'string' && isset($arrAttributes['sql']['length']))
{
	$arrAttributes['maxlength'] = $arrAttributes['sql']['length'];
}
```

as reading the SQL `length` only makes sense for `string` (varchar) fields, and not for `integer`, `blob` or `text`.

**Comment by leofeyer** [comment]
> timestamp usually has int(10) and therefore the maxlength is 10 - with `27.04.2021` this is still o.k. but not with `27.04.2021 09:43`

Both `27.04.2021` and `27.04.2021 09:43` are invalid values for an `int(10)` column. You should use a `date` or `datetime` column instead (or at least a `varchar` column).

**Comment by zonky2** [comment]
Unfortunately, Contao core works with the UNIX timestamp for dates and not with the corresponding MySQL data types. The output is in the FE and a "readable date" is made from the timestamp - only the current limitation on maxlength is set to the eingestllete size of the column specification.

**Comment by ausi** [comment]
I was not able to reproduce that. The following field configuration works fine in Contao 4.9:

```php
array(
    'inputType' => 'text',
    'eval' => array('rgxp' => 'datim', 'tl_class' => 'w50'),
    'sql' => array('type' => 'integer', 'length' => 10, 'default' => 0),
)
```

No `maxlength` gets set on the input field.

**Comment by ausi** [comment]
It looks to me like the whole code block https://github.com/contao/contao/blob/7ee9472cb592cc0de678d3b16af53fb763c64afc/core-bundle/src/Resources/contao/library/Contao/Widget.php#L1366-L1377 (introduced in 4f2121716348a10324be426586d6ab670406434a) doesn’t do anything because it looks for the `sql` key inside the `eval` array and to my knowledge such a key does not exist anywhere in Contao.

@aschempp was this meant to look for `$arrData['sql']` instead or can this be removed?

**Comment by aschempp** [comment]
I would say it was supposed to use `$arrData['sql']` 😇

**Comment by ausi** [comment]
If we change this code block to `$arrData['sql']` we should then also add a check for `type` having to be varchar in order to set `maxlength`.

**Comment by aschempp** [comment]
As far as I remember, an integer does not have a length field in Doctrine.

https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/schema-representation.html#portable-options

> length (integer): The maximum length of the column. Only applies to Doctrine's string and binary types. Defaults to null and is evaluated to 255 in the platform.

**Comment by ausi** [comment]
Yes, that’s why we have to ignore it for all other types I think.

**Comment by aschempp** [comment]
Why ignore when it shouldn't be set at all (because it has no effect on Doctrine)? 😉

**Comment by ausi** [comment]
> because it has no effect on Doctrine

If it has no effect on doctrine, it should have no effect on the `maxlength` attribute IMO.

@zonky2 Why does your date field have a `length` set?

**Comment by zonky2** [comment]
We save the date, time, date + time as timestamp in MetaModels.

https://github.com/MetaModels/attribute_timestamp/blob/be8e002094652aa4f015c1047ca77a763eae90ee/src/Attribute/Timestamp.php#L92

The whole thing was noticed in the frontenditing, where the BE widgets are transferred to the FE and besides the date like 25.05.2021 also the time was entered, e.g. 25.05.2021 13.51.

25.05.2021 has 10 characters and was "correct" to save.
25.05.2021 13.51 has 16 characters and caused an error

**Comment by fritzmg** [comment]
@zonky2 but why did you add a `length`? And where exactly did you add it?
