### ISSUE TITLE
Contao 4.8 migration removing custom j_mediaelement from layout

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#2984]
**Affected version(s)**
Contao 4.9+

**Description**
With Contao 4.8 the `j_mediaelement` was removed.
In a customer-installation I had to add the `j_mediaelement` back again.

To do this, I manually added the file `j_mediaelement.html5` in the templates folder and then activated it in the layout.

Unfortunately, every time the migration is called (console or install-tool), the Contao 4.8 migration is executed and the script template is removed from the layout again.

See:
https://github.com/contao/contao/blob/8eb97ae0fcb8d611be318417e273c5e427aa082e/core-bundle/src/Migration/Version408/Version480Update.php#L151

As a workaround, I have now simply renamed my template and given it a custom name.

**Question**
Is this a bug and needs to be fixed or have I simply made an unsupported use-case?

**Comment by fritzmg** [comment]
Imo this should definitely be fixed. @ausi we could simply check if the template is available or not?

On that note, we could technically do that for any page layout template, couldn't we.

**Comment by ausi** [comment]
> we could simply check if the template is available or not?

Yes, that should be possible with something like `Controller::getTemplateGroup('j_')`

> On that note, we could technically do that for any page layout template, couldn't we.

I think we should only remove _known_ j/js/moo templates that have to be removed so that we don’t cause issues in setups that misuse this field or load templates dynamically or the like.

**Comment by leofeyer** [comment]
Do we really want to invest time here? Version 4.8 has been released two years ago and apparently no one else has had this problem since then.

**Comment by fritzmg** [comment]
imho yes. It's not very intuitive that Contao would silently remove arbitrary templates from the page layout.

**Comment by contaoacademy** [comment]
I have had this problem only in one installation. For me, it is ok to close this and focus on other things.

**Comment by ausi** [comment]
> Version 4.8 has been released two years ago

In any installation with a custom *j_mediaelement* or *js_mediaelement* template this migration will be executed again and again, regardless if there was an update from version 4.8 to the current one or not.

Closed in favor of #3359
