### ISSUE TITLE
c4.7.0-RC3 Backend Symlinks neu erstellen

### ISSUE THREAD

**Issue by squidi** [contao/contao#299]
Contao Version 4.7.0-RC3

Symlinks neu erstellen über das BE/systemwartung ergibt einen Internal Server Error mit der Meldung => Attempted to call an undefined method named "setContainer" of class "Contao\CoreBundle\Command\SymlinksCommand" 

Systemwartung -> Daten Bereinigen -> Symlinks neu erstellen

**Comment by leofeyer** [comment]
Behoben in d9f048abd54eeb4a62a2dc19bbb61e22a6d4d745.

**Comment by jommbee** [comment]
Heute in der 4.4.39 nach Serverumzug gleicher Fehler.
Nach manuellem Fix in der Zeile:
https://github.com/contao/contao/blob/4.4/core-bundle/src/Resources/contao/library/Contao/Automator.php#L400
geht alles wunderbar.

**Comment by ghost** [comment]
Ein neues Ticket dazu wurde unter contao/contao#462 angelegt.

**Comment by jommbee** [comment]
Ok. Danke.
