### ISSUE TITLE
Layout wird nicht gefunden, weil in falschen Startpunkten gesucht wird

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#2992]
Contao 4.11

Ich habe gerade Folgendes gemacht:

- Contao 4.11.2 mit Mate-Theme installiert.
- Zweite Seitenstruktur erstellt und beiden Seitenstruktur-Startpunkten eine Domain zugeordnet.
- Zweite Startpunkt verschoben (mit Domain X) und wieder geändert in eine normale Seite.
- Im ersten Startpunkt wieder die Domain entfernt.
- Seitenlayout gelöscht, was dem verschobenen Startpunkt zugeordnet war.
- Rufe ich nun die Domain X auf, kommt die Meldung "Layout nicht gefunden".

Das heißt für mich: Contao sucht die Domain X in der Datenbank ohne auf den Typ oder Status der Seite zu achten. Die Domain X wurde in einer normalen Seite gefunden, die früher mal ein Startpunkt war. Aber Contao sollte doch eigentlich nur nach Domains in Seiten suchen, die vom Typ Startpunkt sind?!

**Comment by fritzmg** [comment]
Can you provide a dump of tl_page and tl_layout? I did not quite understand your setup.

**Comment by aschempp** [comment]
Was wird dir angezeigt wenn du das Layout nicht löschst?

**Comment by Samson1964** [comment]
Wenn ich das Layout nicht lösche, wird mir nicht mein aktueller Startpunkt angezeigt, sondern der ehemalige Startpunkt, der zu einer regulären Seite geworden ist. Hier das Setup dazu (tl_page, tl_layout):
[db71837_22.sql.zip](https://github.com/contao/contao/files/6461389/db71837_22.sql.zip)
Die Struktur ist etwa so:
Ebene 0: Startpunkt ohne Domain mit Layout default
Ebene 1: Reguläre Seite (früher auch ein Startpunkt) mit Domain (versteckt) und Layout default (Kopie)

Rufe ich nun die Website auf, wird mir die zweite Seite mit dem Layout default (Kopie) angezeigt. Der wirklich einzige Startpunkt wird ignoriert.

**Comment by fritzmg** [comment]
@aschempp may be the routing is missing a check for the page type and only checks `tl_page.dns` currently?

**Comment by aschempp** [comment]
It does not: https://github.com/contao/contao/blob/4.x/core-bundle/src/Routing/RouteProvider.php#L308
