### ISSUE TITLE
Missing migration for highlight.js

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#2993]
**Affected version(s)**
Contao 4.9+

**Description**
After switching from `highlight.php` to `highlight.js` (https://github.com/contao/contao/pull/2593) some highlight-options changed.

I didn't check everything. But the following needs to be fixed.

- `ApacheConf` = `Apache`
- `Text` = `empty` (empty, option isn't avaiable any more)

```
update tl_content set highlight = 'Apache' WHERE type = 'code' and highlight = 'ApacheConf';
update tl_content set highlight = '' WHERE type = 'code' and highlight = 'Text';
```

**Comment by leofeyer** [comment]
It seems that `ApacheConf` is a valid alias for `Apache`:

https://github.com/scrivo/highlight.php/blob/master/src/Highlight/languages/apache.json#L2-L4

Where did you find the information that the options have to be fixed?

**Comment by contaoacademy** [comment]
> It seems that `ApacheConf` is a valid alias for `Apache`:

You're right. I only looked into the database not to the result in the frontend.
Then maybe only the "Text" option is not available any more.

**Comment by leofeyer** [comment]
I am closing this ticket, because as far as I see, we are using the correct options already.

https://github.com/contao/contao/blob/ede19dbe6f617ce76578d0a960108ab8c53b6e90/core-bundle/src/Resources/contao/dca/tl_content.php#L430
