### ISSUE TITLE
Protokollierung Dateiverwaltung

### ISSUE THREAD

**Issue by bit7ms** [contao/contao#2997]
Hallo zusammen,
Ich habe jetzt schon bei mehreren größeren Projekten (> 20 Redakteure, 3 Gruppenrechte) das Problem, dass User in der Dateiverwaltung Daten und Ordner löschen, die in Verwendung sind und noch benötigt werden. Im Nachhinein will es natürlich niemand gewesen sein und Stress unter den Beteiligten ist vorprogrammiert.

Leider kann ich nicht nachvollziehen mangels fehlendem Log, welcher User welche Daten manipuliert/gelöscht hat.
Aktuell ist es wirklich so, dass in einem aktuellen Projekt User sich gegenseitig Daten löschen. Wenn ich hier nicht bald eine Lösung habe und die einzelnen User ausfinden machen kann, wird Contao wohl bei der nachten Ausschreibung im Vorfeld als CMS schon ausscheiden.

Daher bitte ich dringend um das Feature einer Protokollierung der User-Interaktion in der Dateiverwaltung, direkt im Hauptlog und filterbar über das Feld „Funktion".

Vielen Dank!

**Comment by fritzmg** [comment]
You can implement that yourself with an `ondelete_callback`.

**Comment by asaage** [comment]
Whats the deal? My Contao totally logs that...
![image](https://user-images.githubusercontent.com/4138336/117811778-468ab780-b261-11eb-9f64-70cc60fd975f.png)
You can also prevent file deletions in the user-group-settings alltogether if nessessary.

**Comment by fritzmg** [comment]
True, deletions are already logged. @mimamuxx do you need more information than what's already logged?

**Comment by fritzmg** [comment]
Keep in mind that you may want to increase the [`logPeriod`](https://docs.contao.org/manual/en/system/settings/#localconfig) though. The default is only _7 days_. So if someone deleted a file more than 7 days ago, you won't be able to figure out who did it, unless you have database backups from that time.

**Comment by bit7ms** [comment]
ok, so, if I extend the log period, everything should be fine. thx
