### ISSUE TITLE
Services in hooks are not public

### ISSUE THREAD

**Issue by ghost** [contao/contao#30]
<a href="https://github.com/fritzmg"><img src="https://avatars0.githubusercontent.com/u/4970961?v=4" align="left" width="42" height="42"></img></a> [Comment](https://github.com/contao/contao/pull/17#issuecomment-415739345) by @fritzmg
August 24th, 2018, 14:05 GMT

Currently a lot of bundle extensions aren't compatible with Contao 4.6, since their DCA callback and Hook listener services are not defined as "public". As a workaround, one could just require `symfony/dependency-injection:^3.0` - however that does not work in Contao `4.6.0` due to the dependency in the core-bundle on `symfony/http-kernel:^4.1` which in turn requires `symfony/dependency-injection:^4.1`. This means I have to wait until all my dependencies have been updated for Contao 4.6 (wherever applicable), before I can use it in production.

**Comment by leofeyer** [comment]
See #34.
