### ISSUE TITLE
Latest change to FilesModel may lead to exception

### ISSUE THREAD

**Issue by koertho** [contao/contao#3001]
**Affected version(s)**

Contao 4.9.14

**Description**

The changes to FilesModel in 4.9.14 lead to different outcome on method calls (only tested for findByPath). Until 4.9.13 passing an non-string value lead to method returning null, now an exception (InvalidArgumentException of webmozart Assert) is thrown. This breaks code which trust in this behaivior (which is same for most (all?) findBy-Model-Methods.

This is the change: https://github.com/contao/contao/commit/c9b9ba7a8b83885683476a961968dd935252874b#

This is the line leading to an error now: https://github.com/contao/contao/blob/7ee9472cb592cc0de678d3b16af53fb763c64afc/core-bundle/src/Resources/contao/models/FilesModel.php#L260

A simple try-catch should fix the problem.

**Comment by fritzmg** [comment]
> A simple try-catch should fix the problem.

I think we should just typecast to `(string)` instead.

**Comment by leofeyer** [comment]
Passing a non-string argument is actually not valid according to the phpDoc comment. Where exactly does the issue occur?

**Comment by Defcon0** [comment]
It happens in one of our customer modules. Nevertheless, the function should be forgiving, shouldn't it? Also taking into account that former implementations are based on the forgivingness we had before.

**Comment by koertho** [comment]
The error occurs in a bundle where a value is passed that could be null. Until now we rely on the method returning null and I think it's not just us. There shouldn't be such a behavior change in a bugfix release, if it's a known behavior for all other findBy-Methods and since years the "default" behaivor.

@Defcon0 Hey :D

**Comment by fritzmg** [comment]
> Nevertheless, the function should be forgiving, shouldn't it?

No, the method defines that the parameter needs to be a string. Your own code needs to ensure that a string is passed.

**Comment by Defcon0** [comment]
I agree. From a non-pragmatic point of view ;-)

**Comment by koertho** [comment]
I don't agree. All find-Methods are forgiving. Why suddenly change this behavior for a few of them? There is no real reason to do that and it would introduce more problems than it would (not) solve. IMHO.

**Comment by fritzmg** [comment]
> All find-Methods are forgiving.

Not necessarily by design. If your own code passes a variable to one of these methods with a type that differs from the one mentioned in the phpDoc comment then you cannot be certain that it will always work. If the phpDoc comment would mention `mixed` instead of `string`, then the method's implementation would need to take care of it of course.

I don't quite understand the problem, why do you not fix it in your code? It is clearly wrong to pass anything else than a string to the method you mentioned.

**Comment by koertho** [comment]
It's no problem to change the code on our side. I just reported the behavior change that breaks existing code. For me, I don't see the point why something like that should be changed in legacy code, as it leads to more problems than benefits. But that's my opinion and if you decide to keep this, I'm ok with it.

**Comment by ausi** [comment]
Because it worked previously I would add a type check to the beginning of the method:

```php
if (!\is_string($path)) {
	trigger_deprecation('contao/core-bundle', '4.9', 'Using "Contao\FilesModel::findByPath()" with a non-string argument has been deprecated and will no longer work in Contao 5.0.');
	return null;
}
```
