### ISSUE TITLE
defining a custom section and setting a system default id for it breaks the according default section

### ISSUE THREAD

**Issue by Mediazept** [contao/contao#301]
**Affected version(s)**
4.4.34, still present in 4.6.12 (Contao demo)

**Description**  
If a custom layout section is using a system default id, the according default section is broken.
Any content you put into this custom section won't display (the section doesn't render).
Furthermore you won't be able to delete the custom section anymore and you won't see the according default section area in front end module dropdown menu anymore.
In 4.4.34 I wasn't able to undo the change with version history.

**How to reproduce**  
- Create a new layout (Theme -> Layout) with just a header column
- Create a custom layout area "my custom area". Use a default id like "footer". Use a distinct position like "after the wrapper" to have better control for debugging
- Create a sequence of front end modules and assign some content to the custom section
- Load your page: the content of the custom section is not rendered - the whole section is missing as you can see looking at the HTML source code
- Edit your layout to use header *and* footer column
- try assigning content to the default footer segment -> "footer" doesn't show in the front end module menu anymore
- save an reload -> content is rendered
- everything wich was assigned to render in "my custom area" is rendered in default "footer" segment (inside wrapper)
- try deleting the custom section -> doesn't work
- check other layouts: All other layouts are affected. Instead of "footer" the front end modules menu will display "my custom area"
- try working around by creating a new custom section
- neither the mis-named original section, nor the new created custom section will render
- section definitions are stored as a blob -> you have to delete "tl_layout" and start over again.

**Suggested behavior**
Check the input value of the "id" field before creating a new custom section.

**Comment by Mediazept** [comment]
Another aspect of the bug: 
Changing the name of a custom section will also break a layout configuration.

**Comment by leofeyer** [comment]
> try deleting the custom section -> doesn't work

I cannot confirm this. I assume you mean that you cannot delete the last row (which is correct), however you can delete the "title" and "ID" fields, which will remove the custom section.

> Check the input value of the "id" field before creating a new custom section.

Yes, seems reasonable.

**Comment by leofeyer** [comment]
Fixed in e4f933c2a99c318ed3ab281d0d0eddc637c61984.

**Comment by timgatzky** [comment]
Hi Leute,
wäre es nicht flexibler, wenn die Layoutbereiche "Manuelle Ausgabe" weiterhin frei wählbar blieben. Dann bleibt die Möglichkeit erhalten das fe_page Template nach eigenen Wünschen zu gestalten.

ps. Wären Eigene Layoutbereiche nicht sauberer, wenn sie ungewrappt erscheinen? Contao vergibt hardcodiert ein div.custom.
