### ISSUE TITLE
Adjust YouTube-Player parameters

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#3012]
**Affected version(s)**
Contao 4.9+

**Description**
I have checked all the options of the YouTube-player and found out the following:

- **Autoplay**: only works under certain conditions (browser autoplay policy) maybe there should be a hint (https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)
- **Hide the YouTube logo**: Only prevents the YouTube logo from displaying in the control bar, a small YouTube text label will still display in the corner of a paused video
- **Hide the top bar in the preview**: not working anymore, parameter _showinfo_ is deprecated since 2018 and was removed

Source: https://developers.google.com/youtube/player_parameters

**Comment by m-vo** [comment]
> Autoplay: only works under certain conditions

Using autoplay for instance works in most browsers if the iframe has `allow="autoplay"` and only gets injected after clicking (e.g. a splashscreen).

**Comment by ausi** [comment]
I think we should extend the iframe attributes by `allow="autoplay; encrypted-media; picture-in-picture; fullscreen"`.

> **Autoplay**: only works under certain conditions

+1 for adding a hint or an explanation! Video autoplay not working is a very common cause of confusion.
