### ISSUE TITLE
Focus problem when hitting enter in type selector in content elements with another chosen in the palette

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#3013]
**Affected version(s)**

Contao 4.9

**Description**

This ticket relates to https://github.com/Craffft/css-style-selector-bundle/issues/22

The bug is not limited to this bundle,  but it's a general thing.

Reproduction:

1. Create a field e.g. in tl_content as a select with chosen functionality:

```
<?php

$dca = &$GLOBALS['TL_DCA']['tl_content'];

\Contao\CoreBundle\DataContainer\PaletteManipulator::create()
        ->addField('testfield', 'invisible')
    ->applyToPalette('text', 'tl_content')
    ->applyToPalette('headline', 'tl_content');

/**
 * Subpalettes
 */
$fields = [
    'testfield' => [
        'exclude'   => true,
        'filter'    => true,
        'inputType' => 'select',
        'options'   => ['h1', 'h2'],
        'reference' => &$GLOBALS['TL_LANG']['tl_']['reference'],
        'eval'      => ['chosen' => true, 'multiple' => true, 'tl_class' => 'clr'],
        'sql'       => "varchar(64) NOT NULL default ''"
    ],
];

$dca['fields'] = array_merge(is_array($dca['fields']) ? $dca['fields'] : [], $fields);
```

2. Create a text element and save it.
3. Now click into the "type" select at the top of the form and hit "arrow up" on the keyboard in order to select the headline item in the select and then hit return.

The result is that the focus goes into the field "testfield" and the form isn't submitted because the focus is captured by the field and the submit event is not triggered but prevented.

This might be not tooo much of a problem but in fact the first option in the select field "testfield" is selected which can cause trouble the editor didn't expect.

I guess it might be a chosen issue or an issue with the chosen init code.

Thanks in advance for digging into it!

Bye Defcon0

**Comment by Defcon0** [comment]
Unfortunately the error persists. Post to avoid staling.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by ausi** [comment]
Unable to reproduce.

**Comment by leofeyer** [comment]
Thanks for checking. 👍

**Comment by Defcon0** [comment]
Strange, in 4.11 it doesn't happen anymore. Maybe it's fixed there, I can live with that :-)
