### ISSUE TITLE
Remove DI container dependent methods from the StringUtil class

### ISSUE THREAD

**Issue by ausi** [contao/contao#3015]
While working on #3014 with @Toflar we noticed that the `StrigUtil` class has static methods who depend on the DI container and it would probably be a good idea to move them into their own services with dependency injection.

I would suggest moving the following methods to two new services:

`Contao\CoreBundle\Util\HtmlDecoder`:
- `substrHtml` (depends on Config)
- `getRawDecodedValue` (depends on insert tags)
- `getRawDecodedValueFromHtml` (depends on insert tags)

`Contao\CoreBundle\Util\PathUtil`
- `srcToInsertTag` (depends on FilesModel)
- `insertTagToSrc` (depends on FilesModel)
- `stripRootDir` (depends on project_dir)

The rest of the methods are (nearly) pure and can be kept as they are now IMO (maybe with small changes):
- `substr`
- `decodeEntities` (add deprecation for non-utf8 config `characterSet`)
- `specialchars` (add deprecation for non-utf8 config `characterSet`)
- `standardize` (add deprecation for non-utf8 config `characterSet`)
- `restoreBasicEntities`
- `generateAlias`
- `censor`
- `encodeEmail` (can be rewritten to no longer rely on Config)
- `extractEmail`
- `splitFriendlyEmail`
- `wordWrap`
- `highlight`
- `splitCsv`
- `toXhtml` (should be deprecated IMO)
- `toHtml5` (should be deprecated IMO)
- `uuidToBin`
- `binToUuid`
- `sanitizeFileName`
- `resolveFlaggedUrl`
- `convertEncoding`
- `stripInsertTags`
- `deserialize`
- `trimsplit`
- `ampersand`
- `prepareSlug`

**Comment by m-vo** [comment]
I would omit `stripRootDir` because new implementations should IMHO just use `Path::makeRelative` with `%kernel.project_dir%` and not rely on the specific behavior of this method. But :+1: for the rest. 

Maybe the path related things could also go in a new insert tag service that would also replace (or for now redirect to) `Controller::replaceInsertTags`.

**Comment by aschempp** [comment]
Maybe things can be optimized by e.g. passing the allowed tags to `substrHtml`?
