### ISSUE TITLE
Group the page mounts by page root for non-admin users

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#3018]
Hello,

in larger systems it's quite confusing for the editors that the pages allowed for a non-admin user with one or more user groups having page mounts aren't grouped by page root.

I understand why it's the case which is because you can change the order of the page mounts in the user group. Also you can have multiple user groups having pages from different page roots.

But what would be cool is the following: maybe we could iterate all page mounts and sort them the following way:

1st priority: page root
2nd priority: order in the user group

This way pages with same names but existing in different page roots don't look the same for editors anymore.

I also suspect, that might crash with the logic of the treeView at the moment since it's processed from top to bottom without sorting it beforehands.

Do you think this might be a useful feature? Would it be implementable with the core?

Bye Defcon0

**Comment by aschempp** [comment]
I honestly refrain from limiting the page roots. Its better to set correct permissions (disallow editing pages and articles) for the pages the user does not have access to. Otherwise you can't pick the pages from a page picker for example, which is really a pita.

**Comment by Defcon0** [comment]
Ah ok. So how can I disable the access for pages for certain specific user groups? I thought page mounts were the way to go here?

In addition: since it's a large installation we're talkig about here, it's easier to say which pages are accessible than to say which aren't.

**Comment by aschempp** [comment]
Using the access rights in the page configuration.

<img width="1201" alt="Bildschirmfoto 2021-05-26 um 08 17 38" src="https://user-images.githubusercontent.com/1073273/119611343-da7c8780-bdfa-11eb-932a-3a587a6d0480.png">

**Comment by Defcon0** [comment]
OK, so I guess this might be an option. Thanks for the hint!
