### ISSUE TITLE
CHMOD Problem im Verzeichnis assets/images

### ISSUE THREAD

**Issue by markocupic** [contao/contao#302]
Contao 4.6.14
PHP 7.2
Cyon Webhosting

Auf einer nackten Contao 4.6.14 Installation werden verkleinerte Bilder (jpg) nur mit CHMOD 0600 anstatt mit den nötigen 0644 abgespeichert. Daraus resultieren massenhaft Error 403.

Siehe  https://test.kletterkader.com/home.html 

Liegt das an der Server Konfiguration von Cyon?

**Comment by minstyle** [comment]
Contao 4.4.34
PHP 7.2
Kein Cyon Webhosting

Nach einem Update von Contao 4.4.33 zu 4.4.34 habe ich genau das gleiche Problem.

![image](https://user-images.githubusercontent.com/2649562/51828748-917c9d00-22ec-11e9-9677-313212c2b7d1.png)

Alle Bilder auf der Website werden nicht mehr angezeigt. Auch funktioniert die Bildvorschau in der Contao-Dateiverwaltung nicht mehr.

@leofeyer Bitte zeitnah fixen!

**Comment by fritzmg** [comment]
I don't think this has anything to do with Contao. Contact your hosting provider and check the default umask with them.

**Comment by minstyle** [comment]
Vorher hat es noch funktioniert. Erst nach einem Update auf die neueste Contao-Version führt zu diesem Problem ...

**Comment by fritzmg** [comment]
Das heißt, nach einem Downgrade besteht das Problem nicht mehr?

**Comment by minstyle** [comment]
Nach einem Downgrade auf Contao 4.4.33 besteht das Problem komischerweise immer noch. Habe via Konsole den Contao-Cache geleert.

Wenn ich den Befehl "umask" in der Konsole eingebe, erhalte ich den Wert "0022" (siehe z. B. https://community.contao.org/de/showthread.php?17634-Probleme-mit-Dateirechten).

**Comment by fritzmg** [comment]
> Nach einem Downgrade auf Contao 4.4.33 besteht das Problem komischerweise immer noch. Habe via Konsole den Contao-Cache geleert.

Dann hat es, wie gesagt, vermutlich nichts mit Contao zu tun. Kontaktiere den Hoster.

**Comment by ausi** [comment]
Bitte versucht einen Downgrade von contao/image auf 0.3.7. eventuell lässt sich dadurch das Problem beheben.

**Comment by ausi** [comment]
Falls das hilft liegt das Problem vermutlich an 
https://github.com/contao/image/commit/7460eee279c71eb99b545f3d60ce889a2d1f9b29

**Comment by minstyle** [comment]
@ausi 

_Bitte versucht einen Downgrade von contao/image auf 0.3.7. eventuell lässt sich dadurch das Problem beheben._

So sieht derzeit meine composer.json aus:

```javascript
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0-or-later",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": "^5.6|^7.0",
        "contao/calendar-bundle": "^4.4",
        "contao/comments-bundle": "^4.4",
        "contao/faq-bundle": "^4.4",
        "contao/listing-bundle": "^4.4",
        "contao/manager-bundle": "4.4.*",
        "contao/news-bundle": "^4.4",
        "contao/newsletter-bundle": "^4.4",
        "madeyourday/contao-rocksolid-columns": "^2.0",
        "terminal42/contao-ce-access": "^2.0"
    },
    "conflict": {
        "contao/core-bundle": "<4.4.8"
    },
    "extra": {
        "branch-alias": {
            "dev-4.4": "4.4.x-dev"
        },
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

Was muss ich hier genau machen?

**Comment by Wusch** [comment]
Du kannst `"contao/image": "0.3.8"` bei conflict ergänzen:

```
"conflict": {
    "contao/core-bundle": "<4.4.8",
    "contao/image": "0.3.8"
},
```

Bei mir funktioniert es damit wieder. Contao 4.6. Hoster Mittwald.

**Comment by minstyle** [comment]
@Wusch 
Jetzt funktioniert es wieder! Aber was bedeutet das nun für die Zukunft? Handelt es sich hier um einen Contao-Bug?

**Comment by markocupic** [comment]
@all 
Ja, das kann ich bestätigen.
Nach dem Downgrade auf contao/image 0.3.7 funktioniert alles wieder.
Besten Dank @ausi

**Comment by frontendschlampe** [comment]
selbes Problem - aber nach ```"contao/image": "0.3.8"``` geht alles wieder

**Comment by srhinow** [comment]
Bei mir auch der selbe Fehler nach dem Update auf Contao 4.4.34 und Es geht wieder wenn ich wie beschrieben die Zeile 
```
"conflict": {
...
"contao/image": "0.3.8"
}
```
in der composer.json einfüge und ein "`composer update`" behebt das Problem dann wieder.

Danke nochmal an @frontendschlampe für den Tipp des Issues hier.

**Comment by ausi** [comment]
Der Fehler sollte mit https://github.com/contao/image/commit/21bb29b4f15fbab0d36218df95dbd9702e1595e8 behoben sein. Kann bitte jemand testen ob sich das Problem mit `"contao/image": "dev-master as 0.3.9",` im `require` Block jetzt lösen lässt?

**Comment by markocupic** [comment]
@ausi 
Danke dir für das bugfixing. 
> Der Fehler sollte mit [contao/image@21bb29b](https://github.com/contao/image/commit/21bb29b4f15fbab0d36218df95dbd9702e1595e8) behoben sein. Kann bitte jemand testen ob sich das Problem mit `"contao/image": "dev-master as 0.3.9",` im `require` Block jetzt lösen lässt?

Bei mir hat es funktioniert. Super! Bin froh.

**Comment by ausi** [comment]
Vielen Dank fürs testen!  
Version [0.3.9](https://github.com/contao/image/releases/tag/0.3.9) wurde soeben released.

**Comment by srhinow** [comment]
ja der Fix hat bei mir auch geholfen. Vielen Dank @ausi
