### ISSUE TITLE
Option to modify mainHeadline from within BackendModule

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#3020]
When building a custom BackendModule there is no way to modify the mainHeadline to anything other than the module name itself which results in a different UX than in the rest of the Contao backend.

The core itself has it's own logic on how the mainHeadline is set up depending on the current table, ptable, key etc. but there seems to be no way to modify the headline in a custom BackendModule.

These are the lines in question

https://github.com/contao/contao/blob/13ca9de98fdef79992a094d962ae9297138a8b24/core-bundle/src/Resources/contao/classes/Backend.php#L432-L439

I'd like to propose a minimalistic and clean way (no breaking changes, no warnings) to change that.
How about we just pass on the main template object to the custom modules?

```php
/** @var Module $objCallback */
$objCallback = new $arrModule['callback']($dc);
$objCallback->mainTemplate = $this->Template;
$this->Template->main .= $objCallback->generate();
```

Happy to hear about your thoughts and maybe some alternative solutions :)

**Comment by richardhj** [comment]
From what I can tell: This is a major problem when I tried to refactor the backend controllers.

We would need a similar solution as in #2975 for the backend.

**Comment by aschempp** [comment]
I think you can actually set that headline if you use a backend controller and the provided Twig template? https://docs.contao.org/dev/guides/back-end-routes/

**Comment by richardhj** [comment]
> I think you can actually set that headline if you use a backend controller and the provided Twig template? https://docs.contao.org/dev/guides/back-end-routes/

(This works because the twig function directly sets the headline inside the `BackendMain`).

**Comment by michb** [comment]
Well @aschempp and @richardhj the solution will technically work.

But in my opinion this won't be a "clean" solution as with a custom backend controller we also have to implement every security feature and special handling of the request that are already implemented in the Contao core, like `security.authorization_checker`, `contao.picker.builder`, `ajax request`, `act=error`, and maybe more.

At some point the core team has to decide if we, as extension developers, want to extend Contao or just build Symfony modules that have nothing to do with Contao anymore.

Also I think it is not reasonable that every developer has to code his own logic for basic actions or tasks the framework also needs and uses, like what happend to the DCA eval `encryption` flag.

**Comment by richardhj** [comment]
@michb this is what #2808 is about.

**Comment by m-vo** [comment]
With #3180 it would be possible to set/overwrite any variable of the base base template.
