### ISSUE TITLE
Allow direct links to public files in the file picker

### ISSUE THREAD

**Issue by intradesign** [contao/contao#3021]
In the file manager you can open an image or a file in a new window/tab by clicking on the small icon next to the file name.

When selecting images/files for content elements or as teaser images this is not possible, although the view is basically the same as the file manager.

But sometimes you need a quick look at the "big original" right at that moment, instead of just seeing the thumbnail.

Then you first have to awkwardly open the file manager and find or search for the file in the folder structure.

In the old Contao version (<= 3.5.x) you could switch directly from the file selection to the file manager in the same view.

![Nachrichten Beiträge Beitrag ID 10 bearbeiten](https://user-images.githubusercontent.com/21263208/119159819-ec0b0b80-ba57-11eb-8b47-0b505a83aac1.jpg)

**Comment by leofeyer** [comment]
It seems it is not a coincidence that the icon does not work in the picker:

https://github.com/contao/contao/blob/93755143171d0463fb75e03ff54aef43c097e860/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L2916

@contao/developers Do you remember why we prohibit direct links in the picker? I do understand protected files and templates, but public images should be fine, shouldn't they?

**Comment by ausi** [comment]
> Do you remember why we prohibit direct links in the picker?

I think because the link was opened in a lightbox popup back then, and opening a popup within a popup was probably not desired.

The popup was changed to a target _blank link in 0dcf773b54d657a2bb2c5ca954c534dfa990d9ea because of https://github.com/contao/core/issues/6262

So I think we can safely remove the popup/picker check.
