### ISSUE TITLE
URL wird ohne ersichtlichen Grund durch auto_items erweitert

### ISSUE THREAD

**Issue by do-while** [contao/contao#3023]
**Affected version(s)**

Contao 4.9.14

**Description**

Unter bestimmten Umständen, die ich bisher nicht reproduzieren konnte, tritt folgendes Problem auf:
Ein Seitenaufruf einer vorhandenen Seite http://domain.tld/pfad/seite.html läuft in eine 404.
In der Browserzeile steht dann http://domain.tld/pfad/seite/seite/seite/seite.html

Ich habe dann mal eine Debugausgabe in den Hook GetPageIdFromUrl eingebaut. Hier sieht man, dass ohne ersichtlichen Grund der auto_item erzeugt wird:
Aufruf http://domain.tld/karriere/stellenangebote
```
[22-May-2021 17:29:01] hookControl::myGetPageIdFromUrl - arrFragments=Array
(
    [0] => karriere/stellenangebote
    [1] => auto_item
    [2] => stellenangebote
    [3] => stellenangebote
    [4] => stellenangebote
)
```
Das tritt aber nicht bei allen Seiten auf, sondern nur bei wenigen, die anderen werden korrekt aufgerufen und auch wird der auto_item nicht erzeugt.
Die Seite mit dem Fehler enthält aber keine Module, die einen auto_item auswerten.

Die Installation lief korrekt in der 4.9.13 auf einem anderen Server (gleicher Provider), ich habe sie umgezogen und einmal komplett aktualisiert (mit dem Manager). Erst in der Kopie treten diese Fehler auf, allerdings hatte ich die localconfig.php nicht mit übertragen und da sind die Ordner-URLs definiert. Maren vermutete da im Slack das Problem.
Allerdings bekomme ich den Effekt nicht auf allen Seiten weg, selbst nach dem Neuerstellen aller Aliases von Pages und Artikeln und löschen aller Caches.

php 7.4.14, MariaDB 10.5.10, Provider All-Inkl, Erweiterungen:
        "do-while/contao-backupdb-bundle": "^1.4",
        "do-while/contao-ce_be_remarks": "^1.1",
        "fritzmg/contao-backend-documentation": "^1.0",
        "jrgregory/m17-sticky-backend-footer": "^2.0",
        "madeyourday/contao-rocksolid-columns": "^2.0",
        "madeyourday/contao-rocksolid-custom-elements": "^2.3",
        "terminal42/contao-easy_themes": "^2.2",
        "terminal42/contao-pageimage": "^4.0",
        "terminal42/contao-root-protection": "^1.0"

Eine Besonderheit hat noch der temporäre Domainname, der hat viele Sub-Sub-...Domains
domain.de.wxxxxxxx.kasserver.com und ist nicht im Startpunkt eingetragen (da ist der DNS-Eintrag leer)

**Comment by do-while** [comment]
Neue Erkenntnisse:
Ich hatte die Domain vorbereitet mit web-Verzeichnis und habe dort den Manager eingespielt. Dann habe ich die composer.json und composer.lock ins Basisverzeichnis kopiert, die Verzeichnisse templates und files kopiert und dann im Manger die Installation ausführen lassen. Wie geschrieben habe ich die localconfig.php nicht übertragen gehabt, dadurch keine Ordner-URLs aktiv.

Neuer Ansatz:
Ich habe die alte Installation direkt kopiert, alle Dateien, Verzeichnisse und Symlinks, habe nur die neue Datenbank in der parameters.yml eingetragen. Dann habe ich im Manager nur den Cache erneuert, weiter nichts!
Hier funktionieren die Links noch korrekt!

Auch nach einer Komplett-Aktualisierung läuft jetzt alles korrekt.

Der Bug muss also im Contao liegen, dass irgendwo etwas ist, was die auto_items aktiviert obwohl nicht vorhanden.
Im Backend habe ich mit den Aliases viel herumprobiert, es hat sich nicht verändert.

**Comment by fritzmg** [comment]
> Ein Seitenaufruf einer vorhandenen Seite http://domain.tld/pfad/seite.html läuft in eine 404.
> In der Browserzeile steht dann http://domain.tld/pfad/seite/seite/seite/seite.html

You mean `http://domain.tld/pfad/seite.html` responds with a redirect?

**Comment by do-while** [comment]
It seems so, the called URL is changed and then appears in the browser as specified

**Comment by fritzmg** [comment]
Are you able to reproduce this redirect in a clean Contao 4.9.14 installation?

**Comment by do-while** [comment]
Ich werde versuchen, das in den nächsten Tagen nachzubauen. Diese Installation habe ich als "echte" Kopie neu aufgebaut, so funktioniert es ohne diese Probleme.

oMo hat auf Slack ähnliche Probleme gemeldet, könnte gleiche Ursache haben: https://contao.slack.com/archives/CK4J0KNDB/p1621703027114800?thread_ts=1621690350.109700&cid=CK4J0KNDB

**Comment by do-while** [comment]
Ich habe versucht es nachzubauen. Eine neue 4.9 aufgesetzt, entsprechende Einstellungen gemacht, die Installation ohne OrdnerURLs=true kopiert.
Beim Aufruf der entsprechenden Seiten Meldung 404. Nachdem ich die OrdnerURLs=true gesetzt habe, ging aber alles wie es soll.

Ich habe dann eine weitere Kopie meiner Seite, die den Fehler hatte, erstellt. Dort war der Effekt wieder nachzuvollziehen. Nach OrdnerURLs=true haben dann alle Seiten korrekt funktioniert, die ich vorher nicht angesehen habe. Nur die geprüften Seiten zeigten den Fehler.
Der Test in einem anderen Browser ergab, das dieser die Seiten korrekt anzeigt, also muss es am Firefox-Cache gelegen haben, obwohl ich ihn gelöscht hatte. Jetzt, wenn ich den gesamten Cache lösche, geht es auch im Firefox.

War dann wohl ein Fehlalarm, danke für Eure Unterstützung
