### ISSUE TITLE
Multiple picker values cannot be filtered in the backend

### ISSUE THREAD

**Issue by rabauss** [contao/contao#3025]
## Affected version(s)

Contao 4.9+

## Description

If you use the universal picker widget with multiple option in your DCA and activate the filter option, you wont be able to filter the entries correctly in the backend. The reason is that the widget values will be saved as seralized integers and the backend like query quotes the values.

## Example DCA for tl_calendar_events
```php
PaletteManipulator::create()
    ->addLegend('pages_legend', 'details_legend', PaletteManipulator::POSITION_BEFORE)
    ->addField(['pages'], 'pages_legend', PaletteManipulator::POSITION_APPEND)
    ->applyToPalette('default', 'tl_calendar_events')
    ->applyToPalette('internal', 'tl_calendar_events')
    ->applyToPalette('article', 'tl_calendar_events')
    ->applyToPalette('external', 'tl_calendar_events')
;

$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['pages'] = [
    'exclude' => true,
    'filter' => true,
    'inputType' => 'picker',
    'eval' => [
        'context' => 'page',
        'multiple' => true,
        'fieldType' => 'checkbox',
        'orderField' => 'orderPages'
    ],
    'sql' => 'blob NULL',
    'foreignKey' => 'tl_page.CONCAT(title)',
    'relation' => ['type' => 'hasMany', 'load' => 'lazy'],
];

$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['orderPages'] = [
    'label' => &$GLOBALS['TL_LANG']['MSC']['sortOrder'],
    'sql' => 'blob NULL',
];
```

## Possible Solutions

There are two possible solutions and I don't know which one you would prefer - I would take the first one but this could be a BC break 😞 

### 1. Save the picker values as serialized strings
https://github.com/contao/contao/blob/37e1a09d99f6bbde827d1e4e7f47ed41341d6bcb/core-bundle/src/Resources/contao/widgets/Picker.php#L106
  
```php
$arrValue = array_map('\strval', array_filter(explode(',', $varInput)));
```
This also allows you to reliably search for single-digit IDs e.g. `LIKE %"1"%` - the order field also stores the values that way!
By the way this is what I even tried to discuss years ago 😇: https://github.com/contao/core-bundle/pull/1171#pullrequestreview-74145509

### 2. Like filter without quotes for picker

https://github.com/contao/contao/blob/37e1a09d99f6bbde827d1e4e7f47ed41341d6bcb/core-bundle/src/Resources/contao/drivers/DC_Table.php#L5645

```php
if ('picker' === $GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['inputType']) {
    $this->values[] = '%' . $session['filter'][$filter][$field] . '%';
} else {
    $this->values[] = '%"' . $session['filter'][$filter][$field] . '"%';
}
```

What do you think?

EDIT:

There is a third solution which is allready working now in my project ;-)
### 3. save callback for the picker field

```php
namespace App\EventListener\DataContainer;

use Contao\CoreBundle\ServiceAnnotation\Callback;
use Contao\DataContainer;
use Contao\StringUtil;

class EventPersonsListener
{
    /**
     * @Callback(table="tl_calendar_events", target="fields.pages.save")
     */
    public function __invoke($value, DataContainer $dc): ?string
    {
        if (empty($value)) {
            return $value;
        }

        return serialize(array_map('\strval', StringUtil::deserialize($value, true)));
    }
}
```

**Comment by leofeyer** [comment]
I am leaning towards solution 1, because we are expecting a serialized string throughout the code base.

https://github.com/contao/contao/blob/37e1a09d99f6bbde827d1e4e7f47ed41341d6bcb/core-bundle/src/Resources/contao/drivers/DC_Table.php#L5645

@contao/developers WDYT?

**Comment by Toflar** [comment]
Why don't we set `eval->csv`? It will just work fine then :D

**Comment by leofeyer** [comment]
Because we are using `WHERE groups LIKE '%"42"%'` a lot throughout the code base and this would break when we changed to integers or CSV.

**Comment by aschempp** [comment]
I don't see how this is related to the picker? Everything where multiple selection is available (e.g. a select menu) is stored as a serialized array (if you don't use `eval->csv`)?

**Comment by leofeyer** [comment]
The picker casts the values to integers (`array_map('\intval'`) whereas it should cast them to strings (`array_map('\strval'`).

**Comment by ausi** [comment]
I don’t like storing integers as strings.

I would use something like this:

```php
if ((string)(int)$session['filter'][$filter][$field] === (string)$session['filter'][$filter][$field]) {
	$this->procedure[] = '(' . $what . ' LIKE ? OR ' . $what . ' LIKE ?)';
	$this->values[] = '%"' . $session['filter'][$filter][$field] . '"%';
	$this->values[] = '%i:' . $session['filter'][$filter][$field] . ';%';
}
else
{
	$this->procedure[] = $what . ' LIKE ?';
	$this->values[] = '%"' . $session['filter'][$filter][$field] . '"%';
}
```

**Comment by aschempp** [comment]
If int vs string is the problem, then `WHERE groups LIKE '%"42"%'` is the actual problem. I use `WHERE groups LIKE '%"42"%' OR groups LIKE '%i:42%'` in such cases.

**Comment by ausi** [comment]
That is exactly what my code does.

**Comment by leofeyer** [comment]
Ok, then we have to adjust this everywhere else as well.

https://github.com/contao/contao/blob/76e89d81344e6f88864e6751d7959a0689552c50/core-bundle/src/Controller/BackendPreviewSwitchController.php#L172-L175

https://github.com/contao/contao/blob/76e89d81344e6f88864e6751d7959a0689552c50/core-bundle/src/Resources/contao/classes/Crawl.php#L374

https://github.com/contao/contao/blob/ad86686181b7bd85ad1fa00d37a497a9e4e84e70/core-bundle/src/Resources/contao/drivers/DC_Table.php#L5664

**Comment by rabauss** [comment]
Hui, that would be some refactoring - are those all the code places? 🤔
I also don't like saving integers as strings but currently that's my only working solution without fix 😉

**Comment by leofeyer** [comment]
I have added the "up for discussion" label, because changing this is a major BC break IMHO. I have found further occurrences, which all expect string IDs instead of integer IDs:

https://github.com/contao/contao/blob/136a1975126808f52fd3ccc9abdd3a6463f2a5d4/news-bundle/src/Resources/contao/models/NewsFeedModel.php#L94

**Comment by leofeyer** [comment]
* As discussed in Mumble on June 2nd, the `intval` cast is wrong, because we do not know which data format the picker returns (it could be UUIDs). We will therefore fix this by removing the `intval` mapping entirely.

* The suggested workaround to support both integers and strings in the LIKE query does not work, because `'%i:42%'` can be both an index or a value.

* Generally, we all agree that storing IDs as comma separated values and using `find_in_set()` would be better, however, that would be a BC break as well.
