### ISSUE TITLE
Output of file extension type like in ce_download(s)

### ISSUE THREAD

**Issue by jankout** [contao/contao#3026]
Hello, 

I think it would be nice to output the file extension type in `picture_default` too. So It would be possible to add specific class names as we already have it in _**ce_download(s)**_

**Comment by m-vo** [comment]
Can you share the use case for this?

**Comment by jankout** [comment]
For example, I would like to use it to have a difference between image file types to add another CSS styling according to the image file type. As we already have it in _ce_download(s)_

**Comment by asaage** [comment]
should be possible with only css.

```css
source[type$="webp"] + img { border: 1px solid red }
``` 
but in the end you can't be really sure. if the browser does not support webp it will show a jpg with a red border.

If there are different filetypes in [img src] and [source srcset] the only way to tell which one is effectively applied by the browser would be [via JS](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/currentSrc) i guess.

**Comment by ausi** [comment]
> For example, I would like to use it to have a difference between image file types

What would be a use case for this? Styling the image differently if it is WEBP instead of JPEG? Why?

> So It would be possible to add specific class names

This is already possible in with a custom `picture_default` template.
