### ISSUE TITLE
Automator::generateInternalCache doesn't refresh existing dca extract cache files

### ISSUE THREAD

**Issue by ReneLuecking** [contao/contao#3027]
**Affected version(s)**

Tested in Contao 4.10 but according to a quick look at GitHub version history it seems to affect all versions

**Description**

I'm developing in Contao and therefore i often use `php vendor/bin/contao-console contao:automator generateInternalCache` to refresh the config/dca/language cache because it is faster than rebuilding the complete symfony cache.

If i create a new dca file and generate the internal cache the dca and dca extract cache files are correct. But if i now change an sql definition in the dca file (for example extending the sql field length) and generate the internal cache again, only the dca cache file gets updated but not the dca extract cache file.

The issue seems to be that the [`DcaExtractor`](https://github.com/contao/contao/blob/13ca9de98fdef79992a094d962ae9297138a8b24/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php#L119-L129) uses the cached dca extract file to create the new dca extract cache file instead of using the updated dca file.

A solution could be to delete the cached files in `Automator::generateInternalCache` (like Conato 3 did it, see [here](https://github.com/contao/core/blob/303023b5f0b92de97437ce4fb656cdd067c207ed/system/modules/core/library/Contao/Automator.php#L479)) or to tell the DcaExtractor somehow to not use the cached file.

**Comment by fritzmg** [comment]
> I'm developing in Contao and therefore i often use `php vendor/bin/contao-console contao:automator generateInternalCache` to refresh the config/dca/language cache because it is faster than rebuilding the complete symfony cache.

While developing you can use the [debug mode](https://docs.contao.org/manual/en/system/debug-mode/).

**Comment by ReneLuecking** [comment]
I'm using the debug mode, but the Symfony cache (and so the internal Contao cache) will still be used. Only the cache folder isn't the same (`var/cache/dev` vs. `var/cache/prod`). I could of course leave the cache unused by never warming it up, but then Contao is very slow on my PC

**Comment by fritzmg** [comment]
When you are using the debug mode, any config or DCA changes you make should take effect immediately. (Although I do notice that I sometimes have to manually delete `var/cache` when I add _new_ DCA or config files that haven't existed before.)

**Comment by ReneLuecking** [comment]
Maybe i'm doing something wrong, but config and dca changes only take effect after i executed `php vendor/bin/contao-console cache:clear` or `php vendor/bin/contao-console contao:automator generateInternalCache`. I've enabled debug mode via `APP_ENV=dev` in an `.env.local` file

**Comment by fritzmg** [comment]
May be you have aggressive opcache settings? Check the `opcache.revalidate_freq` PHP setting in your environment for instance (you can do that in the debug mode via the profiler).

**Comment by ReneLuecking** [comment]
My opcache settings are:
```
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
```
So it should always revalidate the files.

**Comment by aschempp** [comment]
Its not related to `prod` or `dev` environment, but to whether the cache has been warmed. The DCA/internal cache is "optional", meaning the system can run without it and therefore it is only built when running `cache:warmup`. If you don't want Contao to cache the DCA files, don't warmup the cache.

Also, the automator methods are deprecated and only available for legacy reason, they will stop working at some point and should not be considered stable.

**Comment by ReneLuecking** [comment]
Good to know, that automater is deprecated. I will just work without the dca/internal cache then.

Technically my reported issue is still a bug, but feel free to close this issue, if you don't want to fix it because it's deprecated :)

**Comment by aschempp** [comment]
I think the point of the automator method is to **generate** the internal cache, not refresh it. So if there already is one, it's not changed. Personally I think it's not worth spending time on changing this 😇
