### ISSUE TITLE
PHP 8: Undefined array key "id"

### ISSUE THREAD

**Issue by ausi** [contao/contao#3031]
https://github.com/contao/contao/blob/76e89d81344e6f88864e6751d7959a0689552c50/core-bundle/src/Resources/contao/dca/tl_page.php#L796

Should be replaced with:

```php
if (is_array($session['CLIPBOARD']['tl_page']['id'] ?? null))
```

**Comment by leofeyer** [comment]
Why not `if (isset($session['CLIPBOARD']['tl_page']['id']) && is_array($session['CLIPBOARD']['tl_page']['id']))`?

**Comment by m-vo** [comment]
Because it's shorter and IMHO more readable? :smile:

**Comment by leofeyer** [comment]
True.
