### ISSUE TITLE
Feature Request: Change Markdown Library

### ISSUE THREAD

**Issue by berecont** [contao/contao#3037]
Change Markdown Library to use some either features like `target:_blank` or `rel="noopener noreferrer"`.

**Comment by m-vo** [comment]
The most feature complete markdown parser is IMO `commonmark` (PHP implementation by `league`). There you can configure defaults for external links (e.g. the target). There is an open PR but there is nothing specced yet about configurable attributes. (It's still doable as a parser/renderer step but requires quite a bit of work.)

Beside the technical things I'm opposed to the idea configuring target blank by default/globally for all links.

**Comment by asaage** [comment]
I'd like to see _Tables_ and _Task Lists_ support (github-flavoured)
and more importantly the option to select a _.md_ file via filepicker as source.
That would make this content-element much more useful in my opinion.
I found https://github.com/thephpleague/commonmark (seems to be the most popular and actively maintained) & https://github.com/erusev/parsedown as candidates to replace https://github.com/michelf/php-markdown (which is whats currently beeing used).

**Comment by Toflar** [comment]
Yeah commonmark is definitely the way to go here and it supports all we need. I've worked with it plenty of times.

**Comment by Toflar** [comment]
As I prefer using Markdown to write my developers meeting blog posts, I guess I'll implement that myself :)

**Comment by Toflar** [comment]
Pull request: https://github.com/contao/contao/pull/3055
