### ISSUE TITLE
Invisible skip navigation links affect Lighthouse SEO score

### ISSUE THREAD

**Issue by qzminski** [contao/contao#3039]
**Affected version(s)**

Contao 4.9 and above

**Description**

It seems that the skip navigation links in the navigation module have a negative impact on the Lighthouse SEO score (see image below). It is likely because they do not have a `href` attribute. We tried to add the `rel="nofollow"` attribute but that did not help.

https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/templates/modules/mod_navigation.html5#L13

We were able to solve that only by changing the `<a>` to e.g. `<span>`, but we are not sure if it's the way to go. Can somebody shed some light on this why the target has to be an anchor element? I would assume it's like that because `<a>` is focusable, but maybe there are better ways to do it in 2021?

Reference: https://webmasters.stackexchange.com/questions/132481/lighthouse-says-links-are-not-crawlable-on-the-skip-to-content-link/132482#132482

![2021-05-28 at 15 31](https://user-images.githubusercontent.com/193483/119991502-cfc41d00-bfc9-11eb-94cb-fca331258c13.png)

/cc @Toflar

**Comment by asaage** [comment]
https://github.com/contao/contao/issues/2729
https://github.com/contao/contao/pull/2944

**Comment by qzminski** [comment]
Closing as a duplicate then 😉

**Comment by asaage** [comment]
I just wonder why the issue and the PR was closed.
Just because it's valid markup doesn't mean there is no room for improvement.

**Comment by fritzmg** [comment]
I consider this a bug in Lighthouse. Jump links should not be taken into consideration for their "crawl-ability". Also I doubt that this actually has an effect on the score?

**Comment by asaage** [comment]
>Also I doubt that this actually has an effect on the score?

it actually does affect the score.

**Comment by qzminski** [comment]
@fritzmg it certainly affects the score (for example 92 to 100). The anchor links are handled correctly, it's just that one link without a `href` attribute that is the anchor link's target causes the problem.

**Comment by fritzmg** [comment]
Yes, but that's still a bug that Lighthouse needs to fix.
