### ISSUE TITLE
Check for tables before running database updates

### ISSUE THREAD

**Issue by aschempp** [contao/contao#307]
**Affected version(s)**
4.7.x-dev

**Description**  

You cannot run a database migration for additional bundles in the core, `comments-bundle` is not installed on my system.
https://github.com/contao/contao/blob/master/installation-bundle/src/Database/Version470Update.php#L69-L83

**Comment by leofeyer** [comment]
Fixed in 089ce9f76eb8646d549d56bfa5ccfe54414d92b8.
