### ISSUE TITLE
Duplicate PID?

### ISSUE THREAD

**Issue by aschempp** [contao/contao#3074]
**Affected version(s)**

probably any 😂 

**Description**

Any idea why there is two times `pid` in the URL here?
https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/drivers/DC_Table.php#L2257

**Comment by fritzmg** [comment]
It's not two times, it's either

```php
'&amp;act=create&amp;mode=1&amp;pid=' . $this->intId
```

or

```php
'&amp;act=create&amp;mode=2&amp;pid=' . $this->activeRecord->pid
```

**Comment by aschempp** [comment]
🤦  thanks
