### ISSUE TITLE
JavaScript-Template "js_mediaelement" scheint Konflikt mit Mootools zu verursachen

### ISSUE THREAD

**Issue by vstuber** [contao/contao#308]
In einem Contao-Projekt (Contao 4.4.34) wird das Verhalten von Mootools gestört, wenn im Layout das Javascript-Template "js_mediaelement" aktiviert wird.

Die Sache ist zumindest in meinem Projekt ganz einfach zu reproduzieren und zu testen:

Mit der folgenden Einstellung im Layout

![grafik](https://user-images.githubusercontent.com/1235606/51930163-320cb300-23fa-11e9-8b43-26e1d69671cb.png)

passiert in der Entwicklerkonsole des Browsers folgendes:

![grafik](https://user-images.githubusercontent.com/1235606/51930056-fb369d00-23f9-11e9-8d54-40c38a9f7b7e.png)

Da es das Element mit der ID "header" auf der Seite gibt, ist das natürlich falsch.

Mit der folgenden Einstellung im Layout

![grafik](https://user-images.githubusercontent.com/1235606/51930243-65e7d880-23fa-11e9-89a2-43b3ef770ee3.png)

verhält es sich korrekt:

![grafik](https://user-images.githubusercontent.com/1235606/51930280-7dbf5c80-23fa-11e9-96ea-36e2f4050a3f.png)

Kann dieses Problem sonst noch jemand bestätigen und, noch besser, erklären bzw. beheben?

In der Praxis zerschießt mir das gerade einen großen Teil meiner mit Mootools realisierten Javascript-Funktionalität.

**Comment by xchs** [comment]
Kannst Du das Problem auch in der Contao Official Demo reproduzieren?

**Comment by vstuber** [comment]
Habe ich noch nicht probiert, weil ich zugegebenermaßen nicht weiß, was Du mit "Contao Official Demo" meinst. Wenn Du mir das kurz erklärst, probiere ich es sofort aus!

**Comment by xchs** [comment]
Das wäre eine neue Contao 4.4.34 Installation mit diesem Paket: https://packagist.org/packages/contao/official-demo

**Comment by vstuber** [comment]
Okay, das probiere ich mal eben aus...

**Comment by ausi** [comment]
Hast du in den Layouteinstellungen nur „MooTools laden“ aktiviert, oder auch „jQuery laden“?

**Comment by cliffparnitzky** [comment]
> Das wäre eine neue Contao 4.4.34 Installation mit diesem Paket: https://packagist.org/packages/contao/official-demo

oder Live hier: https://demo.contao.org/contao/login

**Comment by ausi** [comment]
Wenn beide Frameworks aktiviert sind, überschreibt das MediaElement.js die globale `$()` Funktion mit der jQuery-Funktion, siehe [MediaElement.js 4.2.9 src/js/player/library.js:8](https://github.com/mediaelement/mediaelement/blob/4.2.9/src/js/player/library.js#L8)

Die MooTools-Skripte können somit nicht mehr auf `$()` zugreifen und müssten stattdessen `document.id()` verwenden.

**Comment by vstuber** [comment]
Jetzt kam mir etwas dazwischen und ich konnte es noch nicht in der Official Demo ausprobieren aber dank der Aussage von @ausi ist das ja auch gar nicht mehr nötig, denn der Fehler ist jetzt bestätigt und begründet.

Zu der Frage 

> Hast du in den Layouteinstellungen nur „MooTools laden“ aktiviert, oder auch „jQuery laden“?

Auch jQuery ist aktiviert. Deaktiviert man jQuery, verschwindet das Problem auch, aber jQuery selbst ist ja nicht wirklich die Ursache.

Aber was nun? jQuery und Mootools gemeinsam zu betreiben ist ja eigentlich kein Problem, weil man jQuery-Skripte ja normalerweise so schreibt, dass die beiden Systeme kompatibel sind. Und der Parallelbetrieb muss ja auch möglich sein, da man als Webdesigner ja oft darauf angewiesen ist, das Beste aus beiden Welten kombinieren zu können. Insofern ist das, was MediaElement.js macht ja nicht in Ordnung. Und Mootools-Skripte so umzuschreiben, dass sie `document.id()` nutzen statt `$()` ist nicht praktikabel, weil fast jedes Mootools-Skript, das ich kenne, `$()` benutzt.

Der kleinste Eingriff, um das Problem aus der Welt zu schaffen, wäre also eine Anpassung der MediaElement.js. Nun hat MediaElement nicht direkt etwas mit Contao zu tun und ich kenne den Entwickler nicht und auch nicht seine Bereitschaft, eine solche Änderung durchzuführen. Kann jemand einschätzen, ob es realistisch ist, dass das Problem von dieser Seite aus behoben wird?

**Comment by fritzmg** [comment]
MediaElement.js scheint nicht mehr so aktiv entwickelt zu werden: https://github.com/mediaelement/mediaelement/issues/2607#issuecomment-455823904

Contao benutzt aber eigene Versionen von Paketen wie diesen - teilweise sind diese auch extra angepasst. Es wäre daher möglich auch für MediaElement.js eine angepasste Version bereit zu stellen.

**Comment by ausi** [comment]
Für diesen Bug gibt es auch bereits einen Pull Request: mediaelement/mediaelement#2598

**Comment by ben-eSM** [comment]
Eventuell könnte man auch aufgrund der Tatsache, dass MediaElement.js nicht mehr so aktiv entwickelt wird, für die Zukunft einen Wechsel auf https://github.com/sampotts/plyr ins Auge fassen.

**Comment by asaage** [comment]
> https://github.com/sampotts/plyr  ins Auge fassen.

Picture-in-Picture und speed-controls....  nice.
Schade, dass i18n noch nicht's mitkommt.

**Comment by leofeyer** [comment]
@ausi Kannst Du bitte kurz schauen, ob contao-components/mediaelement@b3b7b802ccab9f5514400bb4f99eaf24ef6d49e2 für Dich auch Sinn ergibt? Unser Code sieht irgendwie anders aus als der im verlinkten PR. 🤔

**Comment by leofeyer** [comment]
Behoben in contao-components/mediaelement@b3b7b802ccab9f5514400bb4f99eaf24ef6d49e2.
