### ISSUE TITLE
"name" field in form ignored when submission format is email

### ISSUE THREAD

**Issue by frederikmoellers** [contao/contao#3089]
**Affected version(s)**

Contao 4.9 (running 4.9.13)

**Description**

I have created a form and set it up to send the input as an email to 3 different recipients. Following [the manual](https://docs.contao.org/manual/en/form-generator/forms/#send-form-data) I have configured the form fields' names as `name`, `email`, `subject` and `message`. Additionally I have included a file upload element and two checkboxes. The latter are only used for ToS acknowledgement, so they don't need to be included in the mail.

From testing and from what I read in the manual I expected to receive an email with the "Reply-To" header set to the entered name and email address. However, only the `email` field is copied into the "Reply-To"-header. The entered name completely disappears from the resulting email.

The problem is now that I don't know how to address the senders. I only have their email addresses, but not their names.

**Workaround**

I have now configured the form to use "CSV" as the submission format. All fields are listed in the mail and additionally everything is included in the attached CSV. It's a little more verbose than necessary, but it works for now.

_note:_ If it's easier for you I'm happy to discuss in German here. I just wasn't sure which language to pick for the bug report.

**Comment by m-vo** [comment]
Contao's form email functionality is very minimal. This could for sure be improved, but you might be better off using the [notification center extension](https://extensions.contao.org/?q=notification%20center&pages=1&p=terminal42%2Fnotification_center) for this use case.

**Comment by fritzmg** [comment]
I cannot confirm the problem. `name` and `email` are used for the `Reply-To` header:

```
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=utf-8
Date: Tue, 15 Jun 2021 18:59:35 +0100
From: sender@example.com
MIME-Version: 1.0
Message-ID: <35c4c3dc106cdc494f7886b38dffa2bf@c49.local>
Received: from c49.local by mailhog.example (MailHog)

          id -qxiwBSZlecSSh9lcqeyITv_piRU8USvFC6EOAs33Gw=@mailhog.example; Tue, 15 Jun 2021 18:59:35 +0100
Reply-To: Lorem Ipsum <foo@example.com>
Return-Path: <sender@example.com>,<sender@example.com>
Subject: My Subject
To: recipient@example.com

My Text
```

In this example `Lorem Ipsum` was the the content of the `name` POST variable and `foo@example.com` was the content of the `email` POST variable. (`subject` was `My Subject` and `message` was `My Text`.)
