### ISSUE TITLE
Remove the keywords from articles

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#3095]
Contao 4.9:
Using keywords in an article results in no output in the FE (meta keywords are missing).

I tested it here: https://demo.contao.org/contao?do=article

Perhaps this is a bug, however I would prefer to remove the whole keywords "feature".

https://de.semrush.com/blog/meta-keywords-in-seo/
Summary: The meta keyword tag died in 2002. Only one search engine used it after 2002: Inktomi.

https://erdmann-freunde.de/wissen/tipps/detail/10-tipps-contao-seo/
"Es gibt sogar Gerüchte, dass sich die Verwendung der Keywords negativ auf die Platzierung bei Google auswirken könnte. Wir empfehlen daher, den Bereich für Keywords leer zu lassen..."

**Comment by fritzmg** [comment]
The keywords have already been removed from the `fe_page`. The possibility to enter keywords in articles is there for BC only and thus is likely to be removed in Contao 5.0.
