### ISSUE TITLE
Anyone using the "quicklink" module?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3096]
Is anyone using the "quicklink" module that generates a dropdown navigation menu with a custom set of pages? I am asking because I have noticed that the module ignores the protection status of a page. It just excludes "guests only" pages if there is a front end user:

https://github.com/contao/contao/blob/51d174df940fe28267d021c50738d21325299d33/core-bundle/src/Resources/contao/modules/ModuleQuicklink.php#L75

In contrast, the "quicknav" module does check the protection status:

https://github.com/contao/contao/blob/51d174df940fe28267d021c50738d21325299d33/core-bundle/src/Resources/contao/modules/ModuleQuicknav.php#L137-L138

Since we just have adjusted the "customnav" module to consider the protection status of a page (see #2970), we might want to do the same for the "quicklink" module? Or is no one using the module anymore?

**Comment by m-vo** [comment]
Never used that. :slightly_smiling_face: 

Could this functionality not be achieved with a custom navigation template as well?

**Comment by fritzmg** [comment]
I have also never used it myself, but I have seen it in other (old) Contao instances.

**Comment by ausi** [comment]
> Since we just have adjusted the "customnav" module to consider the protection status of a page (see #2970), we might want to do the same for the "quicklink" module?

IMO yes.

> Or is no one using the module anymore?

We could deprecate both the `quicklink` as well as the `quicknav` module IMO.

**Comment by aschempp** [comment]
Why would you deprecate `quicknav`?

**Comment by leofeyer** [comment]
The two modules are basically a dropdown version of the regular navigation menus.

* quicknav → navigation
* quicklink → custom navigation

We could remove the quick* modules and provide additional templates for the regular navigation modules that render them as dropdown menu?

**Comment by aschempp** [comment]
Uhm, in quicknav I can pick various pages for my nav, independent of the page structure. I can't do that in the navigation module?

Or maybe I'm confusing something 😂

**Comment by ausi** [comment]
> Uhm, in quicknav I can pick various pages for my nav, independent of the page structure.

I was not able to reproduce that. There is no selection for various pages in my setup:

![Bildschirmfoto 2021-06-22 um 09 01 56](https://user-images.githubusercontent.com/367169/122878996-aa140480-d338-11eb-9666-0bc2d810c118.png)

**Comment by leofeyer** [comment]
> We could remove the quick* modules and provide additional templates for the regular navigation modules that render them as dropdown menu?

This turned out to be more complex than expected, so let us not do this for now. @contao/developers I will just update the two modules to correctly check the protection status, ok?
