### ISSUE TITLE
Getting rid of TL_NOINDEX_KEYS

### ISSUE THREAD

**Issue by Toflar** [contao/contao#3097]
Let's discuss how we can get rid of `$GLOBALS['TL_NOINDEX_KEYS']`.

**Comment by ausi** [comment]
I think a solution could be related to a concept for managing `<link rel="canonical">` in Contao. Canonical

**Comment by leofeyer** [comment]
As discussed at the developer's meeting, these are the steps to accomplish the mission:

- [x] Check if Escargot supports canonical URLs (implemented in https://github.com/terminal42/escargot/commit/5e4955739e40d04a8f00ece978283e32e4fadebb)
- [x] Make our indexer ignore pages if the canonical URL does not match the URL (see https://github.com/contao/contao/pull/3617)
- [x] Canonical URLs should be handled in the ResponseContext (with `*` wildcard support) (see https://github.com/contao/contao/pull/3616)
- [x] It should be possible to pass an individual URL to the ResponseContext (see https://github.com/contao/contao/pull/3616)
- [x] It should be possible to enter allowed query parameters and individual URLs in the page settings (see https://github.com/contao/contao/pull/3616)
- [ ] The list modules should have an "add pagination URLs to the search index" checkbox which adds the pagination query variable to the allow list
- [x] It should be possible to disable canonical URLs per root page (see https://github.com/contao/contao/pull/3616)
- [x] Canonical URLs should be disabled for existing pages after the update (see https://github.com/contao/contao/pull/3616)

**Comment by Toflar** [comment]
I'm closing this because 

> The list modules should have an "add pagination URLs to the search index" checkbox which adds the pagination query variable to the allow list

is a totally optional feature and I would even argue, that we shouldn't implement it. The only advantage is that it would automatically add e.g. `page_n23` if you select the correct checkboxes. Which you can also do by configuring `page_n23` or even `page_n*` to your page settings as of now. It's not complicated at all and imho it's even better in the page settings as you have to look at only one place to see the `rel="canonical"` configuration instead of the page and several different module settings.
