### ISSUE TITLE
preview.php allows to create xml files with wrong urls.

### ISSUE THREAD

**Issue by Ainschy** [contao/contao#3099]
**Affected version(s)**

Contao 4.9.15 and Contao 4.11.4

**Description**

The frontend preview allows you to call the backend via preview.php. For changes that lead to the generation of the XML files, the URLs are generated as preview.php URLs.

This happens easily when using the extension Frontend-Helper from Rocksolid. See also [https://github.com/madeyourday/contao-rocksolid-frontend-helper/issues/45](url)

Without the extension the behavior can be adjusted by: domain.tld/preview.php/contao?do=maintenance -> Rewrite XML files.

**Comment by ausi** [comment]
I can confirm the issue in Contao 4.11.4 with the news RSS feeds.

Possibly related: #2507 #2550

The sitemap.xml is not affected in 4.11 because of the dynamic sitemap generation from #2295

**Comment by leofeyer** [comment]
I am not sure how to handle this case. First, the front end preview is obviously not meant to access the back end. Second, would the correct solution not be to redirect `/preview.php/contao` to `/contao`?

**Comment by fritzmg** [comment]
Redirecting `/preview.php/contao` to `/contao` seems reasonable to me.

**Comment by aschempp** [comment]
Another possible solution would be **not** to generate these files if we're in the preview endpoint. There's a request attribute to check for that: https://github.com/contao/contao/blob/4.x/manager-bundle/src/Resources/skeleton/public/preview.php#L30

**Comment by leofeyer** [comment]
As discussed in Mumble on August 26th, we want to redirect `/preview.php/contao` to `/contao` and we want to adjust the front end preview so it redirects to `/contao/login` instead of `/preview.php/contao/login` when the user is not logged in yet.

**Comment by ausi** [comment]
> we want to redirect `/preview.php/contao` to `/contao`

Based on the `_preview` request attribute.
