### ISSUE TITLE
add autoprefixer to leafo/scssphp compiled scss-files

### ISSUE THREAD

**Issue by arboc** [contao/contao#310]
**Description**  
Es wäre hilfreich, wenn die CSS- Styles, die aus den SCSS-Datein generiert werden, automatisch mit 
 einem entsprechenden vendor-prefix versehen werden.

Dazu gibt es ein Issue bei leafo/scssph mit einer Lösung:  
https://github.com/leafo/scssphp/issues/610#issuecomment-459274640

Lässt sich das nicht in Contao einbinden?

**Comment by leofeyer** [comment]
Wie am 7. März auf Mumble besprochen, wollen wir das nicht hinzufügen, da bei der [verlinkten Library](https://github.com/padaliyajay/php-autoprefixer) noch einige Features fehlen und bei nur 16 Commits nicht sicher ist, ob die Library zukünftig weiter entwickelt wird.

**Comment by arboc** [comment]
@leofeyer  
gibt es denn eine Alternative zu leafo/scssphp?

**Comment by m-vo** [comment]
Du kannst/solltest scss Dateien lokal kompilieren.

**Comment by arboc** [comment]
geht leider nicht immer.  
Wir haben Projekte, bei denen der User bestimmte Variablen selbst setzen kann. Danach muss compiliert werden.

**Comment by m-vo** [comment]
(Vlt kannst du Node auf dem Server einsetzen?)

MMn liegt das außerhalb dessen was Contao können soll.

**Comment by arboc** [comment]
nicht alle Server unterstützen nodejs, leider.  
Außerdem ist das Paket nun mal in Contao integriert und kann / soll scss-Dateien verarbeiten.  Sich von dieser Funktion zu verabschieden wäre ein Rückschritt.  

Das Problem hat ja nicht nur Contao. Alle CMS (z.B WP, Typo3, etc. ) nutzen leafo/scssphp, wenn es um scss-Dateien geht.

**Comment by m-vo** [comment]
> Sich von dieser Funktion zu verabschieden wäre ein Rückschritt.

Das sehe ich wirklich anders. Wir haben wie du richtig sagst nunmal idR kein Node auf dem Server. Niemand sollte scss unkompiliert einbinden, wenn die Möglichkeit besteht es lokal zu bauen (& dann z.B. durch postcss samt Plugins zu jagen - je nachdem was deine jeweilige Applikation gerade braucht). Das Feature gibt es aus BC Gründen noch, früher hat das vlt. mal Sinn gemacht.

Dein Anwendungsfall ist eher speziell würde ich sagen.

**Comment by arboc** [comment]
also ich kenne auf anhieb 5 Erweiterungen, die diese Funktion nutzen.  

Die Aussage:  
> Niemand sollte scss unkompiliert einbinden

kann ich beim besten Willen nicht unterstützen.

scss zeichnet sich gerade durch seine Fkexibilität aus. Und wenn man anpassbare Themes entwickelt, dann kommt man nicht um scss herum.  Und anpassbar heißt, durch den User anpassbar. Und das ist jetzt kein Spezialfall von mir.  

Ich könnte noch weitere Bsp. nennen, z.B die Einbindung von css Frameworks, wie Bootstrap.  

Es war ja auch nur die Frage, ob eine Alternative bekannt ist. Nicht ob es Sinn macht. **Die Entscheidung, scss serverseitig zu compilieren sollte jedem Programmierer selbst überlassen sein.**

**Comment by Xirdion** [comment]
@arboc Wenn man **keine** Vorgabe an bestimmte **Browser-Versionen** hat, könnte man für deinen Fall, wenn der User Variablen setzen kann, auch die [Custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) (variables) von CSS verwenden. Dann müsste man nichts neu kompilieren.

**Comment by arboc** [comment]
@Xirdion  
damit lassen sich aber keine Berechnungen durchführen.  
SCSS ist ja mehr, als nur variablen setzen. Das könnte ich auch mit den Contao Bordmitteln, z.B. in den Theme Einstellungen. 

Ich kann verstehen, wenn das Paket von leafo raus fliegt, weil es offensichtlich nicht gut / nicht mehr gepflegt wird. Ich bin darüber auch nicht glücklich.  
Wie oben ausgeführt gibt es aber im Berech Themeing und beim Einsatz von CSS Frameworks gute Gründe, SCSS serverseitig zu kompilieren.

**Comment by leofeyer** [comment]
> Sich von dieser Funktion zu verabschieden wäre ein Rückschritt.

Das haben wir auch gar nicht vor.

**Comment by arboc** [comment]
@leofeyer 
Danke für die Klarstellung.  
Der Kollege @m-vo scheint da ja eine andere Ansicht zu vertreten.
