### ISSUE TITLE
Cache blockiert die Zeitsteuerung

### ISSUE THREAD

**Issue by kroerig** [contao/contao#3101]
**Affected version(s)**

Contao 4.9

**Description**

Wenn Artikel mit einer Zeitsteuerung versehen sind und der Shared Cache aktiv ist , werden die Inhalte erst nach Leeren des Shared Caches übernommen. Siehe dazu auch: https://community.contao.org/de/showthread.php?80450-Zeitgesteuerte-Artikel-amp-Cache

**Comment by Toflar** [comment]
That's currently a known limitation.
Same is already being discussed in https://github.com/contao/contao/pull/2867.

**Comment by Physiklehrer** [comment]
Auch die Zeitsteuerung von Events (bzw. die automatische Cache-Invalidierung bei abgelaufener Uhrzeit) ist defekt.

Nachweis in der Online-Demo:
- Site structure -> Modules -> Events den "Shared cache timeout" auf "1 year" setzen
- ein Event in der Zukunft anlegen, z.B. wenn gerade 16:00 Uhr ist ein Event am gleichen Tag von 16:05 bis 16:06 Uhr.
- Seite https://demo.contao.org/en/events.html aufrufen (Event wird im Footer unter "upcoming events" angezeigt!), die Uhrzeit verstreichen lassen und Seite neu laden: Event wird fälschlicherweise immer noch unter "upcoming events" angezeigt, nach einem Löschen des Shared Cache jedoch nicht mehr.
 
Das Problem besteht in Version 4.9.16. In Version 4.9.10 konnte noch "Shared cache timeout" auf "1 year" gesetzt werden und die zeitliche Anzeige stimmte immer (vgl. https://contao.org/de/news/contao_4-6-0.html. In welcher Zwischenversion das Problem auftrat, kann ich leider nicht sagen.

Eine Abhilfe wäre natürlich den Shared Cache wieder auf 15 Minuten zu setzen, wobei dann natürlich viel mehr Seiten frisch generiert werden müssen als mit der längeren Cachezeit.

**Comment by leofeyer** [comment]
Wie am 29. Juli auf Mumble besprochen, ist das tatsächlich eine Known Limitation.

Das Problem wird sich lösen, sobald alle Inhaltselemente, Module, Artikel etc. in einer zukünftigen Contao-Version als Fragments implementiert sind. Bis dahin ist es jedoch noch ein weiter Weg, da wir hier über eine recht aufwändige Änderung mit vielen potentiellen Nebenwirkungen sprechen.

Wir sollten die [LIMITATIONS.md](https://github.com/contao/contao/blob/4.9/LIMITATIONS.md) entsprechend anpassen.

**Comment by fritzmg** [comment]
I think @aschempp already has a simple solution for this?

**Comment by fritzmg** [comment]
For reference: this is the work that @aschempp showed during the mumble call on July 29th: https://github.com/contao/contao/compare/4.x...aschempp:bugfix/start-stop-caching

**Comment by leofeyer** [comment]
We were able to solve this issue in Contao 6.1 (see #10039).
