### ISSUE TITLE
Deprecate getLanguages hook

### ISSUE THREAD

**Issue by ausi** [contao/contao#3104]
In many new places we only use the `contao.locales` parameter instead of `System::getLanguages()`. So we should IMO deprecate the `getLanguages` hook as it only affects some parts of Contao.

https://github.com/contao/contao/blob/b14a17ea30c1cf8caa351afade6d4154afe1eeb1/core-bundle/src/Resources/contao/library/Contao/System.php#L654

**Comment by Toflar** [comment]
👍 from my side. Should we also deprecate the `getCountries` one and use Intl - is that related?

**Comment by aschempp** [comment]
I don't think they are the same? `contao.locales` is a list of installed language packs. `System::getLanguages()` is a list of ISO languages, regardless if they are installed. `getCountries` is a list of ISO countries, not related at all.

**Comment by Toflar** [comment]
Yeah but coming from some internal list of manually managed countries instead of Intl. That's why I asked.

**Comment by ausi** [comment]
For `System::getCountries()` I would deprecate the whole method, and replace its usage with `Intl` if possible.

**Comment by ausi** [comment]
> `contao.locales` is a list of installed language packs. `System::getLanguages()` is a list of ISO languages, regardless if they are installed.

For `getLanguages(true)` the method returns exactly all languages from `contao.locales` as keys with their translations as values. https://github.com/contao/contao/blob/12097b955adb962fbf37d3d673c35b98eca46abb/core-bundle/src/Resources/contao/library/Contao/System.php#L636-L640

**Comment by ausi** [comment]
Closed in favor of #3138
