### ISSUE TITLE
Running all unit tests misses failing tests

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3121]
**Description**
There is something flaky with out unit-tests. 

If you run `vendor/bin/phpunit --colors=always` (like the CI does) against the current 4.x everything passes, if you run `vendor/bin/phpunit --colors=always core-bundle/tests/Image`, tests are failing however. Reason in this case is the recently added `license` field that is missing from the output:

```diff
--- Expected
+++ Actual
@@ @@
     'href' => 'assets/images/<anything>'
     'imageUrl' => ''
     'imgSize' => ' width="150" height="100"'
+    'license' => ''
     'lightboxPicture' => Array &2 (
         'img' => Array &3 (
             'hasSingleAspectRatio' => true
```

The tests failing is IMHO the correct behavior in this case. This either is another order dependency problem or something wrong in general. Anyone an idea?

**Comment by leofeyer** [comment]
Could it be this?

https://github.com/contao/contao/blob/3a1c6e8824322d76a05e188ad7fa0f2fc0ea2aaa/phpunit.xml.dist#L73-L76

**Comment by m-vo** [comment]
Removing it doesn't make a difference for me.

**Comment by leofeyer** [comment]
Can you reproduce the issue in Contao 4.9 or 4.11 if you modify one of the tests method so it fails (or should fail)?

**Comment by m-vo** [comment]
Eh,... it seems to be the `DcaLoader` cache (beside others). :disappointed: 

I think I have to resurrect and finish #2518 for this…

**Comment by m-vo** [comment]
Would we be fine with changes only for the 4.x branch? This would probably be much easier to do. I assume tests are most affected by new features not bugfixes.

**Comment by leofeyer** [comment]
Yes. 👍🏻

**Comment by m-vo** [comment]
Closing this as the original issue doesn't appear anymore. Likely due to simplifying the image studio tests at one point.
