### ISSUE TITLE
Format-Fehler in der Zeitsteuerung von Elementen

### ISSUE THREAD

**Issue by k00b0ld** [contao/contao#3129]
**Affected version(s)**

Contao 4.9.16

**Description**

Wenn ich Elemente (z.B. Download-Element) zeitgesteuert zu einem gewissen Zeitpunkt aus- oder einblenden möchte, verweigert Contao dies mit dem Hinweis auf einen Formatfehler bei der Datums- und Zeitangabe.

Jedoch wähle ich das Datum und die Uhrzeit über das grüne Kalendersymbol aus, sodass das Format automatisch korrekt sei müsste. Er besteht laut Fehlermeldung jedoch auf das seltsame Format "**TT.MM.JJJJ-TT hh:mm**" (man beachte das "TT" in der Mitte). Jedoch nimmt er auch dieses Format nicht, sodass für mich die Zeitsteuerung von Elementen aktuell nicht funktioniert.

**Fehlermeldung:**
"Bitte geben Sie Datum und Uhrzeit im Format "TT.MM.JJJJ-TT hh:mm" ein!"

**Comment by fritzmg** [comment]
Did you change the date and time format in the system settings?

**Comment by k00b0ld** [comment]
That was it, hanks for the tip. Someone had made a change to the date format in the settings and a typo had crept in. Sorry for the disturbance!

**Comment by fritzmg** [comment]
Btw. if you only want to change the _output_ date format for the front end, you should do it via the page root settings, not via the system settings. The system settings are for the _input_ date format (and also act as a fallback for the output).
