### ISSUE TITLE
Logout nach Änderung von "username" oder "groups"

### ISSUE THREAD

**Issue by thescrat** [contao/contao#313]
Betroffen/Getestet in Contao 4.6.13 / Contao-Online Demo

Im Modul Personendaten (ModulePersonalData) wird das Mitglied im Frontend ausgeloggt, wenn der "username" oder "groups" geändert wird. 

Hooks "updatePersonalData" werden dann ebenfalls nicht ausgeführt. Erst nach dem erneuten Login (mit neuem username) und einem erneuten speichern werden diese dann ausgeführt.

**Comment by xchs** [comment]
Es geht um Contao 4.6.13 (jedenfalls laut Forum).

**Comment by fritzmg** [comment]
It also affects the Contao Online Demo.

**Comment by cliffparnitzky** [comment]
Same with Contao 4.6.14

**Comment by leofeyer** [comment]
We need to update the security token in the personal data module (FE) and in the user manager (BE).

**Comment by leofeyer** [comment]
It seems that the changes from f7340abe4eade7319fb953b0518205576876ff07 fix this issue as well, so thank you @bytehead. 😄
