### ISSUE TITLE
die aktuelle Tabelle mit in der Fehlermeldung ausgeben

### ISSUE THREAD

**Issue by srhinow** [contao/contao#3132]
https://github.com/contao/contao/blob/f277abad6b6a66ace61804b4017e7e2bf8f6c99d/core-bundle/src/Resources/contao/library/Contao/Model.php#L584

die Tabelle mit in der Fehlermeldung ausgeben wo das jeweilige Feld nicht related werden kann.

`throw new \Exception("Field $strKey does not seem to be related in ".self::getTable());`

**Comment by fritzmg** [comment]
Doesn't the stack trace tell you in which model the error occurs?

**Comment by srhinow** [comment]
in API/ Automation Environment? I think this little Change can save much time when the field name is 'pid'.

**Comment by aschempp** [comment]
sound like a good idea to me. @srhinow would you do a pull-request for Contao 4.9?
