### ISSUE TITLE
Different url_suffix for different domains

### ISSUE THREAD

**Issue by cmichael-de** [contao/contao#3133]
Is it possible to define different url_suffixes for different domains in config.yml?

This feature was already asked here
https://github.com/contao/core-bundle/issues/629

and here:
https://community.contao.org/de/showthread.php?72022-Ein-Backend-und-mehrere-Seiten-und-dann-noch-verschiedene-URL-Suffixe-M%C3%B6glich

**Comment by fritzmg** [comment]
Yes this feature is available since Contao 4.10. Note that you will need to disable `contao.legacy_routing` manually via your `config/config.yaml` (see also the manual for more information).
