### ISSUE TITLE
Internal Server Error nach 2. Benutzerwechsel

### ISSUE THREAD

**Issue by thescrat** [contao/contao#314]
**Affected version(s)**
4.6.13 / Online-Demo

**Description**  
Man landet in einem "Internal Server Error" wenn man im Backend unter Benutzer zu einem Benutzer wechselt und dies ein weiteres Mal probiert. Im Profilmenü wird zwar angezeigt "zurück zu [benutzername]" jedoch wird in der Benutzerliste weiterhin das Wechsel-Icon angezeigt, was man ausblenden sollte.

**How to reproduce**  
Wechsel im Backend unter Benutzer zu einem Benutzer (letztes Icon), der ebenfalls die Berechtigung hat zu Benutzer zu wechseln. Egal ob man nach dem Wechsel auf einen weiteren Benutzer wechseln möchte oder zurück zum Ursprungsbenutzer möchte, man landet immer in einem "Internal Server Error".

**Comment by cliffparnitzky** [comment]
**Can not** confirm with my Contao 4.6.14.

**Comment by thescrat** [comment]
**Getestet in Contao 4.6.14.** Fehler besteht weiterhin!

1. Klick im Backend auf Benutzer
2. Wechsle von Benutzer 1 auf Benutzer 2
3. Klicke erneut im Backend auf Benutzer
4. Wechsle von Benutzer 2 auf Benutzer 1 (oder auf anderen Benutzer).

Resultat: Internal Server Error
"You are already switched to "[benutzername]" user."

**Comment by fritzmg** [comment]
Are you able to reproduce it in the Contao Online Demo?

**Comment by thescrat** [comment]
Ja! Hab ich doch im 1. Kommentar geschrieben

Affected version(s)
4.6.13 / **Online-Demo**

Dazu muss man einen Backend-Benutzer halt noch zum Admin machen, damit man von dem wieder "zurückwechseln" kann. Landet dann aber direkt im Fehler

**Comment by asaage** [comment]
I would confirm this.
Might be an unsupported usecase. Why would anyone want to impersonate in multiple layers?
Disabeling impersonation when already impersonating a user should suffice.
You would always have to switch back to your original user on the top right in between then but that's ok i guess.

**Comment by thescrat** [comment]
> Why would anyone want to impersonate in multiple layers?

Also war froh über die Funktion, dass ich zwischen unzähligen Backendbenutzern wechseln konnte. In Contao 3 war das kein Problem, dort konnte ich hin und herwechseln wie ich wollte. Letztlich ist der "Fehler" nur das Icon, was noch angezeigt wird nach dem Benutzerwechsel. Wenn ich erst zum Originalaccount zurück muss um von dort wieder auf einen weiteren Benutzer zu springen, ist das auch ok

**Comment by cliffparnitzky** [comment]
> . Egal ob man nach dem Wechsel auf einen weiteren Benutzer wechseln möchte oder zurück zum Ursprungsbenutzer möchte, man landet immer in einem "Internal Server Error".

Das kann ich nicht bestätigen.

> 1. Klick im Backend auf Benutzer
> 2. Wechsle von Benutzer 1 auf Benutzer 2
> 3. Klicke erneut im Backend auf Benutzer
> 4. Wechsle von Benutzer 2 auf Benutzer 1 (oder auf anderen Benutzer).
> 
> Resultat: Internal Server Error
> "You are already switched to "[benutzername]" user."

Das kann ich bestätigen.

**Comment by thescrat** [comment]
Die Reihenfolge 1-4 ist doch der Wechsel von Benutzer 1 auf Benutzer 2 zurück auf Benutzer 1. Nur halt über die Benutzerliste. Nicht über das Profilmenü.
![userswitch](https://user-images.githubusercontent.com/1240007/52211565-83012900-288a-11e9-9503-e8c52ee40b3d.gif)

**Comment by cliffparnitzky** [comment]
> Das kann ich bestätigen.

ja

**Comment by leofeyer** [comment]
@contao/developers I don't think we want to support multiple nested impersonations, do we?

**Comment by Toflar** [comment]
Sounds super weird to me. If you're an admin, you can impersonate to a certain user. The only thing you can do then is go back to your real account, that's it. In my opinion you cannot continue to impersonate to yet another user that's not the idea of impersonation.

**Comment by cliffparnitzky** [comment]
I agree with @Toflar . The function should be disabled in the backend view, if you impersonated once.

**Comment by aschempp** [comment]
This is actually an issue in Symfony and not Contao, because the impersonation is a default feature of Symfony security. I wonder if this works:
 1. User A impersonates as User B
 2. User B impersonates as **User C**

As far as I could see, the error appears because User B tries to impersonate as User A again, but that user is already in the parent tokens. If so, we should forbid login as all parent users, not generally forbid impersonating a third user.

**Comment by thescrat** [comment]
@aschempp 
Der Fehler passiert ebenso wenn User A zu User B wechselt und anschließend zu User C wechseln möchte. Es spielt also keine Rolle ob User B "zurück" auf A will oder zu einem dritten User wechselt. 

User A => User B (funktioniert)
User A => User B => User A (funktioniert nicht)
User A => User B => User C (funktioniert nicht)

User A => User B => zurück über Profil (User A)  => User C (funktioniert)

**Comment by leofeyer** [comment]
Siehe #345

**Comment by aschempp** [comment]
FYI, ev. kommt das in einer zukünftigen Symfony-Version: https://github.com/symfony/symfony/issues/34690
