### ISSUE TITLE
contao_import_user event missing

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#3157]
**Affected version(s)**

Contao 4.9

**Description**

According to https://docs.contao.org/dev/reference/hooks/importUser/ we shouldn't use the importUser hook anymore and use the event.

I couldn't find the event anywhere in the code.

**Comment by fritzmg** [comment]
Looks like this was planned, but never got implemented: https://github.com/contao/core-bundle/pull/685 /cc @bytehead

**Comment by bytehead** [comment]
🙈 Is there any time left to add this to 4.12? 😬

**Comment by fritzmg** [comment]
In any case we should probably remove the deprecation notice in Contao 4.9 as a bugfix and then introduce the appropriate event in Contao 4.12 or 4.13 (and then adjust the docs accordingly).

**Comment by bytehead** [comment]
I'll prepare PRs.

**Comment by bytehead** [comment]
An other option would be to add #3160 as a bugfix to 4.9 and keep the deprecation message.

**Comment by leofeyer** [comment]
I like the current solution (removing the deprecation message in Contao 4.9 and adding the event in Contao 4.12).

**Comment by bytehead** [comment]
I'll add a PR for the docs as well.

**Comment by leofeyer** [comment]
As discussed in Mumble on July 29th, we do not want to replace the hook and fix the documentation instead.
