### ISSUE TITLE
.skip is ignored due to dependencies

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3159]
**Affected version(s)**

Contao 4.9+

**Description**

Say you have two Contao 3 style modules:

* `system/modules/lorem`
* `system/modules/ipsum`

where the latter requires the former via `requires[] = lorem` in its `config/autoload.ini`. Now if you disable the former module with a `system/modules/lorem/.skip` file, the extension still gets loaded.

The check for `.skip` is done in the Contao Manager Plugin of the Manager Bundle:

https://github.com/contao/contao/blob/dbc64cf6e5a9570481bca9db24bdc895387c5a7e/manager-bundle/src/ContaoManager/Plugin.php#L119-L121

However `$parser->parse()` will also load all dependencies defined via the `autoload.ini`: 

https://github.com/contao/manager-plugin/blob/77607ca06b5c5286540d611963ed9ea33ab00e71/src/Bundle/Parser/IniParser.php#L52-L75

So even though the Contao Manager Plugin initially skipped the `lorem` module, it will still get added to the resulting `$configs`, because the `ipsum` module requires it.

I am not sure if this is by design? One possible fix could be to also check for `.skip` files in the `IniParser` - but that seems wrong. May be the Manager Plugin of the Manager Bundle should filter the resulting `$configs` afterwards and discard modules with `.skip` files?

**Comment by m-vo** [comment]
What should happen if a skipped dependency is required? Should there be an exception?

The current behavior sounds OK to me, although not ideal.

**Comment by fritzmg** [comment]
> What should happen if a skipped dependency is required? Should there be an exception?

Ideally yes, just like when you would require a module that does not exist. Skipping these modules after the fact in the Manager Plugin of the Manager Bundle does not generate such an exception though.

**Comment by m-vo** [comment]
I'd like that more as well. But it would be kind of a breaking change that's maybe not worth it?

**Comment by leofeyer** [comment]
> I am not sure if this is by design?

It is. You cannot disable a module that is required by another module unless you disable the other module as well.

**Comment by fritzmg** [comment]
In Contao 3 you could and then got an error pointing out the dependencies. Now the module silently stays loaded.

**Comment by aschempp** [comment]
> > I am not sure if this is by design?
> 
> It is. You cannot disable a module that is required by another module unless you disable the other module as well.

Correct. We agreed to change this since Contao 3 would simply block you from using the system. If you want to disable the extension, make sure it's not used either.

**Comment by fritzmg** [comment]
> We agreed to change this since Contao 3 would simply block you from using the system. If you want to disable the extension, make sure it's not used either.

Currently there is no feedback though which extension is preventing the disabling (other than looking through all `autoload.ini`) - or that the extension is disabled in the first place.

**Comment by aschempp** [comment]
there is `composer why` 😬 

When implementing the original bundle loading for Contao 4.0, we discussed about optional and required dependencies like we had in Contao 3 (use `*` in `autoload.ini`). We then agreed that this is not the responsibility of the bundle loader. Composer makes sure dependencies are available. The bundle loader takes everything for optional and loads what is there.

**Comment by fritzmg** [comment]
> there is `composer why` 😬

Wouldn't help with manually installed Contao 3 extensions ;)
