### ISSUE TITLE
Interne Weiterleitung leitet falsch auf Unterseite um

### ISSUE THREAD

**Issue by cmartin6** [contao/contao#316]
**Affected version(s)**
Contao 4.4.28

**Description**  
Ich habe auf der Seite eines Kunden eine Interne Weiterleitung von einer Hauptseite auf eine Unterseite eingerichtet, funktioniert soweit auch ganz gut. Wenn jedoch nach der Hauptseite noch ein "Slash" (/) eingefügt wird, wird doppelt auf die Unterseite weitergeleitet.

**How to reproduce**  
Beispiel: 
http://moosleerau.ch/willkommen -> leitet auf http://moosleerau.ch/willkommen/portraet weiter
http://moosleerau.ch/willkommen/ -> leitet auf http://moosleerau.ch/willkommen/portraet/portraet weiter?

**Comment by fritzmg** [comment]
You always need to test with the newest Contao Version first (LTS or otherwise).

**Comment by asaage** [comment]
Mir kommt das irgendwie bekannt vor...
Das TitleTag deiner Seite Stimmt zumindest ```<title>Porträt - Gemeinde Moosleerau</title>```
Mein Ticket dazu war hier: https://github.com/contao/contao/issues/284
Falls das eine Option ist nutz das Standard-```url_suffix: 'html'```
```''``` und ```'/'``` haben bei mir auch immer mal wieder solche Probleme verursacht.
Wo kommt denn der letzte Slash in deiner 2ten url her?

**Comment by cmartin6** [comment]
Der letzte Slash ist natürlich nur Formsache, d.h. das man in manuell eingeben muss - geschieht bei unserem Kunden jedoch relativ häufig... 
.html-Suffix ist für uns leider keine Option

**Comment by cmartin6** [comment]
> You always need to test with the newest Contao Version first (LTS or otherwise).

Just updated to Contao 4.4.34 but the problem persists...

**Comment by mvscheidt** [comment]
@cmartin6 

Könntest du ggf. mal prüfen was der Inhalt von `$strGet` an dieser Stelle

https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/pages/PageForward.php#L106

und an dieser Stelle

https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/pages/PageForward.php#L115 (also in der Zeile nach der Else Condition)

ist?

Ich will abgleichen ob wir ggf. das selbe Problem bei einem Kunden haben.

Ich muss mir das aber noch genauer anschauen da ich bei uns nur festgestellt hab das in manchen Konstellationen einfach "auto_items" erkannt und dann an die URL angehangen werden.

**Comment by leofeyer** [comment]
@cmartin6 @mvscheidt Gibt es hier irgendwelche neuen Erkenntnisse?

**Comment by cmartin6** [comment]
@leofeyer Ich habe die Option "auto_items aktivieren" deaktiviert, und somit wurde der Fehler behoben. Bin mir aber nicht ganz sicher ob das wirklich sinnvoll bzw. richtig ist.

**Comment by leofeyer** [comment]
@mvscheidt Hier sind die Debug-Infos, die Du haben wolltest:

<img width="428" alt="" src="https://user-images.githubusercontent.com/1192057/55947694-40bfe380-5c4f-11e9-82c8-d7390f3b080a.png">

Das erste ist ein `dump($_GET)`. Ich kann das Problem bei mir leider nicht reproduzieren:

* news-redirect/new-contao-versions-in-short-intervalls -> news-reader/new-contao-versions-in-short-intervalls
* news-redirect/new-contao-versions-in-short-intervalls/ -> news-reader/new-contao-versions-in-short-intervalls/

Keine Ahnung wie es zu der Verdopplung kommt.

**Comment by mvscheidt** [comment]
@leofeyer habe ich moment leider kaum Zeit. Ich melde mich sobald ich mehr herausgefunden habe.

**Comment by mvscheidt** [comment]
Vermutlich ist das "Problem" was ich bemerkt habe ein andereres als von @cmartin6 oder ggf. hat er ein leicht anderes Setup. Habe es leider nicht geschafft exakt sein Problem nachzustellen.

Ich weiß nicht ob mein Problem wirklich ein valider Bug ist oder eher eine Limitierung.

Contao versucht ja die URL in "Alias" und "GET" Parameter zu unterteilen (wenn Slashes in der URL vorkommen).

Kann man in der Demo "nachstellen" - wobei diese ohne Folder-URL läuft (glaube ich) und das "komische" Verhalten daher zum Teil zu erwarten ist (?)

1. Auf https://demo.contao.org/contao einloggen
2. Seitenstruktur öffnen
3. Neue Seite `test` mit Alias `test` anlegen
4. Neue Unterseite `subA` mit Alias `suba` anlegen
5. Seite `test als Interne Weiterleitung auf Unterseite `subA`
6. Im Frontend auf https://demo.contao.org/en/test.html gehen
  - Funktioniert wie erwartet und leitet auf https://demo.contao.org/en/suba.html weiter
7. Im Frontend auf https://demo.contao.org/en/test/irgendwas.html gehen
  - Es kommt ein 404 und man landet auf https://demo.contao.org/en/suba/irgendwas.html
    - 404 weil "irgendwas" für Contao ein GET Parameter ist und Contao ja prüft ob dieser via Input Klasse ausgelesen wurde (wenn nein, gibts einen 404 auch wenn die Seite gefunden wurde - das ist vermutlich das was hier passiert) -> Contao leitet also den GET Parameter an die Zielseite weiter
8. Unterseite `subA` den Alias auf `test/suba` ändern
9. Im Frontend auf https://demo.contao.org/en/test.html gehen
10. Man landet auf https://demo.contao.org/en/test/suba/suba/suba/suba.html
11. Im Frontend auf https://demo.contao.org/en/test/irgendwas.html gehen
12. Man landet auf https://demo.contao.org/en/test/suba/suba/suba/irgendwas.html

Mit Folder-URLs kommt bei 12. vermutlich so etwas wie

https://demo.contao.org/en/test/suba/irgendwas.html

raus (habe das in einem lokalen Contao System auch aufgesetzt, allerdings mit aktivierten Folder-Urls)

Erwartet hätte ich da aber einen 404 auf die URL https://demo.contao.org/en/test/irgendwas.html
und nicht erst nach der Weiterleitung.

Problem hier glaube ich: Es lässt sich schwer feststellen ob jetzt wirklich eine Seite (Alias `test/irgendwas`) gemeint war (dann würde man 404 ausgeben auf der URL https://demo.contao.org/en/test/irgendwas.html) oder die Seite mit Alias `test` und dem Parameter `irgendwas`.

In letzterem Fall könnte man bei einer Weiterleitungsseite tatsächlich erwarten das https://demo.contao.org/en/test/suba/irgendwas.html rauskommt -> kann ja sein das man den Parameter an die Zielseite durchreichen will :man_shrugging:

**Comment by ausi** [comment]
Das Problem mit URL-Parametern in Weiterleitungen sollte sich mit der neuen Checkbox die eingeführt werden soll beheben lassen, siehe https://github.com/contao/contao/issues/488#issuecomment-526183143

**Comment by leofeyer** [comment]
Also das eigentliche Problem kann niemand reproduzieren?
