### ISSUE TITLE
Handling missing messages in the contao translator

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#317]
**Description**  

I've struggled working with the custom translation message domain named `contao_example`. I just wondered why the message wasn't neighter translated nor any debug entry in the symfony console was created for a missing translation message.

@ausi revealed that all message domains starting with `contao_` are mapped to the legacy translator reading translations from `$GLOBALS['TL_LANG']`. If the message doesn't exist no debug notice is created nor the translation is delegated to the default translator.

**Suggested change**

I suggest to change following code so that the decorated translator is able to handle the message:

https://github.com/contao/contao/blob/e79f4cb153e09f34c678e500b9031990b8bd81c5/core-bundle/src/Translation/Translator.php#L57-L59

* There's no need to add any debug information in the Contao translator as the decorated translator would do it
* It's possible to use `contao_` as message prefix for custom domains again

```diff
-            return $id;
+            return $this->translator->trans($id, $parameters, 'contao_' . $domain, $locale);
```

**Comment by ausi** [comment]
I’m not sure if this is the best way to improve this. It could lead to even more confusing behavior if some messages come from `$GLOBALS['TL_LANG']` and others from the Symfony translator for the same message domain. This would be way harder to debug IMO.

It would probably be better to add debug information similar to the Symfony translator which also explains that the message was tried to load from `$GLOBALS['TL_LANG']`.

**Comment by leofeyer** [comment]
As discussed in Mumble on February 14th, we want to add a debug message in line 58 with the same text as used in the Symfony translator.

**Comment by leofeyer** [comment]
It seems we have to adjust the [`translator.data_collector`](https://github.com/symfony/symfony/blob/4.2/src/Symfony/Bundle/FrameworkBundle/Resources/config/translation_debug.xml) service so it passes our translator object instead of the default Symfony one. Not 100% sure though.

**Comment by aschempp** [comment]
can you explain?

**Comment by leofeyer** [comment]
Symfony uses a special data collector, which adds missing translations to the profiler. It currently does not handle Contao translations, which I assume is because it gets the default translator object injected instead of our decorated one.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/544
