### ISSUE TITLE
Add a play button and GDPR hint to splash images

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3178]
Is there a specific reason why by default there is no play icon as an overlay over splash images? From a usability point of view I don't find the current solution very user friendly. I've stumbled upon a view examples where I didn't recognize a video as such because it was "disguised" as a "regular" image. IMHO, a play icon should therefore be included as an overlay by default.

_Originally posted by @madmaharaja in https://github.com/contao/contao/issues/300#issuecomment-870039374_

**Comment by aschempp** [comment]
FYI there have been multiple comments to that in #300, here's the initial one by @ausi which I fully agree with

> I think the play icon should be part of the CSS of your website as it would most probably be styled differently by every website.

if we include something, it should be a style sheet similar to the icons CSS that you can individually select in the layout. That would not affect existing sites. But I don't really see the point for like 5 likes of CSS that 5% of websites will use 🤷

**Comment by leofeyer** [comment]
It does not hurt either, does it? Also, it is probably more about the text overlay (_click to play_ … _your IP address will be sent to YouTube_) than the icon.

**Comment by aschempp** [comment]
> It does not hurt either, does it?

Not sure what you're referring to?

**Comment by kroerig** [comment]
I would prefer having a simple default play button and a hint for GDPR. Maybe the last one should be configurable in the settings because it's content may differ from platform to platform.
