### ISSUE TITLE
Loading mootools via CDN fails

### ISSUE THREAD

**Issue by chamisso** [contao/contao#318]
Affected versions: Contao 4.4.34, Mootools 1.6.0.5

Mootools can be loaded locally but not via CDN. Firefox console reports that the script `https://ajax.googleapis.com/ajax/libs/mootools/1.6.0.5/mootools.min.js` can not be found. The sub-directory should be 1.6.0, not 1.6.0.5.

**Comment by xchs** [comment]
See https://github.com/contao/core-bundle/issues/1371 and https://github.com/contao/core-bundle/pull/1391.

**Comment by leofeyer** [comment]
Fixed in 41ad3a6e06fcbb9ed5caf96256e99c384aa21d11.
