### ISSUE TITLE
Hook/Event für den News-/Event-Teaser

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#3184]
Hallo zusammen,

Besteht die Möglichkeit einen Hook/Event für den News-/Event-Teaser bereitzustellen, analog zu "getContentElement" oder "getFrontendModule"?

Derzeit besteht keine Möglichkeit per Hook/Event den Output des Teaser zu manipulieren.
"getContentElement" und "getFrontendModule" haben den großen Vorteil, dass man sowohl das Objekt wie auch den Buffer-Output bekommt und somit alle Informationen und Möglichkeit hat, das Element passend zu modifizieren.

Über den "parseArticles" bekommt man zwar das News-Objekt, kann aber den Buffer (Output-Template) nicht modifizieren.

Nur mal so als Idee :-)

Danke und Grüße

**Comment by m-vo** [comment]
The teaser is a text field, isn't it? Do you want to auto generate teasers on the fly?

Could you provide a use case what you are trying to achieve? :slightly_smiling_face:

**Comment by xprojects-de** [comment]
oh sorry... I guess I didn't write that correctly :-)
I mean the complete news list informations inside the "layout_latest"-section, e.g. teaser, date, author, etc.

The intention is to manipulate the output template using the object information (e.g. NewsList-Object), not only the Teaser itself :-) )

**Comment by m-vo** [comment]
Would it be sufficient if `ModuleNews` would set the 'news article' in the template when parsing articles?

```php
$objTempalte->article = $objArticle;
```

**Comment by xprojects-de** [comment]
According your question:

The usecase is that i want to provide addition infos (data-attributes) to the "layout_latest"-div to add some individual informations for the Javascript for every news-Item separatly! But i do not want to create a individual news-list template. This should work with all News-List templates regardless of whether the user has created his own.

So if the ModuleNewsList does have the article i´m not able to manipulate its output-string? Right?

**Comment by xprojects-de** [comment]
Result could be (see data-info in parent div):

< div class="layout_latest arc_1 block" data-info="{"newsId":1,"otherAttrFromNews":12345}" itemscope itemtype="http://schema.org/Article">
...

**Comment by fritzmg** [comment]
May be we should also pass the template object for the `parseFrontendTemplate` hook, then it would be possible to do this with the existing hook.

```php
// HOOK: add custom parse filters
if (isset($GLOBALS['TL_HOOKS']['parseFrontendTemplate']) && \is_array($GLOBALS['TL_HOOKS']['parseFrontendTemplate']))
{
	foreach ($GLOBALS['TL_HOOKS']['parseFrontendTemplate'] as $callback)
	{
		$this->import($callback[0]);
		$strBuffer = $this->{$callback[0]}->{$callback[1]}($strBuffer, $this->strTemplate, $this);
	}
}
```

**Comment by xprojects-de** [comment]
But you do not have access to a single News-Item, just for the complete Newslist-Output, or i´m wrong?
So you cannot identify the Item itself to add specific information for that to the section.

**Comment by m-vo** [comment]
One of the issues with lists in Contao is IMHO that their child elements are pre-rendered while there should really be an array of data passed on to the template. Then the template could insert child templates with the respective datasets (compare to images for instance). We could probably ship this data to the templates as well (without affecting BC).

Not sure this is exactly the issue you're having. Maybe just related.

**Comment by fritzmg** [comment]
> But you do not have access to a single News-Item, just for the complete Newslist-Output, or i´m wrong?
> So you cannot identify the Item itself to add specific information for that to the section.

@xprojects-de I am not sure I understand the question 100%. But this way you would have access to the complete template object, i.e. all the template data _after_ it already has been parsed. In case of news templates this means that you have (basically) access to all the variables of the news.

Technically you could work around this right now by implementing a stateful service that listens to both the `parseTemplate` and the `parseFrontendTemplate` hook. In the `parseTemplate` hook you store the template object (or just its data) so that you can still access this data in the `parseFrontendTemplate` hook 😉

**Comment by fritzmg** [comment]
> One of the issues with lists in Contao is IMHO that their child elements are pre-rendered while there should really be an array of data passed on to the template. Then the template could insert child templates with the respective datasets (compare to images for instance). We could probably ship this data to the templates as well (without affecting BC).
> 
> Not sure this is exactly the issue you're having. Maybe just related.

@m-vo the main issue is in this case that there is no unified way of injecting arbitrary HTML attributes (e.g. `data-` attributes) to arbitrary templates. Currently you have to parse/regex the HTML output, like this for instance: https://github.com/inspiredminds/contao-wowjs/blob/1c31db81ee6e70f474e1009cff9b4303e2661e68/src/EventListener/HookListener.php#L51-L72 (there is probably a better approach, but you get the idea).

**Comment by xprojects-de** [comment]
yes you are right but in my opinion i do not have access to the specific News-Archiv-Items.

Let´s assume that we have a News-List-Module where 4 News-Archives are selected. Every News-Archive does have more "Teaser-Items" which are displayed. So what i want to do is to manipulate every "Teaser-Item" of every News-Archive individually by setting e.g. the News-Archive-Id, check if the user has access to the archive, manipulate for e.g. just one Item if the author should be displayed and so on.

All in all every Item of an archive should be present seperatly with its Object.

**Comment by fritzmg** [comment]
> yes you are right but in my opinion i do not have access to the specific News-Archiv-Items.

Yes, you would have. And you can have it right now with my workaround.

**Comment by bytehead** [comment]
> Über den "parseArticles" bekommt man zwar das News-Objekt, kann aber den Buffer (Output-Template) nicht modifizieren.

This is exactly what I'm doing in my current project with the `parseArticles` hook/event. You can assign the template object whatever you want and use a custom template in this case - no?

**Comment by fritzmg** [comment]
> This is exactly what I'm doing in my current project with the `parseArticles` hook/event. You can assign the template object whatever you want and use a custom template in this case - no?

@bytehead you can fill the template with arbitrary variables this way, but you would still have to adjust the template in order to output them. Which is not ideal, if you want your extension to automatically add HTML attributes to news list elements for example.

**Comment by xprojects-de** [comment]
@fritzmg yes that´s the problem

**Comment by bytehead** [comment]
Ah I see.

**Comment by xprojects-de** [comment]
@fritzmg 

> Technically you could work around this right now by implementing a stateful service that listens to both the parseTemplate and the parseFrontendTemplate hook. In the parseTemplate hook you store the template object (or just its data) so that you can still access this data in the parseFrontendTemplate hook 😉

This only works if the "Template"-Parameter of "parseTemplate"-Hook is e.g. "instanceOf NewsListTemplate" and the "parseFrontendTemplate" also pass the specified Template-Object, i´m right?

Otherwise i do not understand how to modify the Output-Buffer!?!?

If yes this could be a nice solution...

**Comment by fritzmg** [comment]
> This only works if the "Template"-Parameter of "parseTemplate"-Hook is e.g. "instanceOf NewsListTemplate" and the "parseFrontendTemplate" also pass the specified Template-Object, i´m right?

No, as I said, you could implement a stateful service, that simply stores the template data during the `parseTemplate` hook so that the `parseFrontendTemplate` hook as access to it.

**Comment by xprojects-de** [comment]
ahhh ok.. you mean e.g. as global Object-Parameter in the Hook-Service.
Yes i do it that way at the moment but in my opinion that shouldn't be the standard way of doing this...

**Comment by fritzmg** [comment]
No of course not 😁. Just mentioning it that there is a way right now 🙂

**Comment by fritzmg** [comment]
On a related note: the naming of the hooks is currently a bit confusing, compared to what each of them do. And these hooks are not unified in what data they actually pass to the callback.

* `parseTemplate`: allows you to modify template data __before__ a template is parsed.
* `parseFrontendTemplate`: allows you to modify the resulting buffer __after__ a template is parsed (without any access to the template data right now unfortunately).
* `outputFrontendTemplate`: no difference to `parseFrontendTemplate`.
* `modifyFrontendPage`: same as `parseFrontendTemplate` but __after__ insert tags or dynamic script tags have been replaced.
* `parseWidget`: allows you to modify the resulting buffer of a Widget __after__ the widget has been generated (does allow you to access the widget object though).
* `parseArticles`: allows you to modify _news_ articles (has nothing to do with _page_ articles) __before__ they are parsed.

**Comment by xprojects-de** [comment]
ok thanks for discussion. 
@fritzmg Workaround is clear

Back to the previous question: Is it possible or wanted to generate a standard way to provide this feature? :-)

Thanks

**Comment by fritzmg** [comment]
> Back to the previous question: Is it possible or wanted to generate a standard way to provide this feature? :-)

Yes, as I said, the `parseFrontendTemplate` could simply just pass the object instance (which it should have done in the first place, instead of just the template name). But more generally, all these hooks should probably work in a more unified way anyway (see https://github.com/contao/contao/issues/3184#issuecomment-878173341).

**Comment by xprojects-de** [comment]
Thanks!!! Fine!
