### ISSUE TITLE
Bump or remove version information in issue templates

### ISSUE THREAD

**Issue by Toflar** [contao/contao#3186]
We still use 4.10 there. So we should do the same as @m-vo did in https://github.com/contao/contao/commit/6f3a683cd4679fb0a73eefbdce9304de98c344c3.

Or maybe better find a general wording and use https://to.contao.org/release-plan or so?

**Comment by leofeyer** [comment]
I would just update the files like @m-vo did. Make it as easy as possible for the person reporting the issue.

**Comment by m-vo** [comment]
Like so? :smile:  #3188
