### ISSUE TITLE
Using findInSet() database helper causes unknown column error

### ISSUE THREAD

**Issue by fmenzel** [contao/contao#3198]
**Affected version(s)**

Contao 4.9 and Contao 4.11

**Description**

The findInSet() database helper adds quotes to the FIND_IN_SET() search key. This causes the key to be identified as column name causing an 'unknown column in where clause' error.

The issue seems to have been fixed early on in Contao 4 here:
https://github.com/contao/core-bundle/commit/5117ee4977d457674af8f8fa133a3ca446c0754b
but must have been reintroduced later on.

Or am I missing something here?

**Comment by ausi** [comment]
This was added in https://github.com/contao/core-bundle/pull/1326 in Contao 4.4.13

As you can see in the method description the `$strKey` parameter should be the field name: https://github.com/contao/contao/blob/b686423f6e88c3874ebda0bfdc8114d94c3f3162/core-bundle/src/Resources/contao/library/Contao/Database.php#L214

Can you post an example how you want to use this method in order for us to understad the use case better?

**Comment by fmenzel** [comment]
The use case is part of a some what complex contao 3.5 module I 'inherited' and am currently upgrading to contao 4.9.
It's a product database and find_in_set is being used to filter by different options.
There are columns containing comma separated lists of IDs and FIND_IN_SET is being used to check for the existence of certain IDs in when filtering search queries.
An example query looks like this:

An exception occurred while executing 'SELECT COUNT(*) AS count FROM tl_productdb_product WHERE (FIND_IN_SET(\`4002\`, \`tl_productdb_product\`.\`category\`)) AND (tl_productdb_product.start='' OR tl_productdb_product.start<1626364491) AND (tl_productdb_product.stop='' OR tl_productdb_product.stop>1626364491) AND tl_productdb_product.published=1':

SQLSTATE[42S22]: Column not found: 1054 Unknown column '4002' in 'where clause'

If the ID 4002 isn't quoted in back ticks the FIND_IN_SET works fine. The ID would have to be unquoted or in regular single quotes for the query to work.

Is there a reason to restrict find_in_set to field names?

Thank you for the quick reply :-)

**Comment by ausi** [comment]
The `$database->findInSet()` method is not meant to be used this way. It is meant for using it with an array of values to compare against a column.

For your use-case you should write something like `FIND_IN_SET(?, tl_productdb_product.category)` directly into the query and use a parameter to replace `?` with the value you are searching for.

**Comment by m-vo** [comment]
If you're refactoring anyway you should probably use Doctrine DBAL instead of the old database class.

**Comment by fmenzel** [comment]
Thanks for the quick replies.
It put me on the right track to find that the quoteIdentifier() function does not add backticks if the search string is already in double quotes. Assuming that an unquoted string is a field name seems sensible and I had just missed that the search strings where going in unquoted.
Thanks for the help!
