### ISSUE TITLE
CSRF-Token is removed while using Symfony forms in a content element

### ISSUE THREAD

**Issue by bytehead** [contao/contao#3211]
**Affected version(s)**
Contao 4.9 (possible 4.11, not tested)

**Description**
While using Symfony forms in a Contao content element, the CSRF token gets stripped away from the response by https://github.com/contao/contao/blob/4.9/core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php#L148. 

The `CsrfTokenManager` is injected via DI.

```php
// my content element
$form = $this->formFactory->create(MyFormType::class, $myForm, [
    'csrf_token_manager' => $this->csrfTokenManager,
]);
```

```php
// my form type
    // ...
	public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MyFormType::class,
            'translation_domain' => 'forms',
            'csrf_token_id' => 'contao_csrf_token',
        ]);
    }
    // ...
```

When rendering the form, the token value gets removed from the mentioned listener.

I don't want to disable the CSRF check on the route, as there possible other forms (e.g. Contao forms) on the same route/page.

/cc @ausi

**Comment by ausi** [comment]
We probably need to extend the `Symfony\Component\Security\Csrf\CsrfTokenManager` class for `contao.csrf.token_manager` and move the logic from https://github.com/contao/contao/blob/b686423f6e88c3874ebda0bfdc8114d94c3f3162/core-bundle/src/EventListener/RequestTokenListener.php#L76-L81 to that class.

**Comment by fritzmg** [comment]
But isn't that the desired behaviour? If a request (that returns the form) does not require a CSRF token cookie to be set (because there is no session for example) then it should be fine if the token is missing in the subsequent POST request?

**Comment by bytehead** [comment]
All Symfony forms require a CSRF token afaik (if CSRF is enabled of course).

**Comment by m-vo** [comment]
Yes, this is cumbersome and I especially don't like that the otherwise nice Sf form CSRF protection automatism is broken by default.

As a workaround I'm currently creating Sf forms in Contao fragments with `'csrf_protection' => false` and have something like `<input type="hidden" name="REQUEST_TOKEN" value="{{ '{{request_token}}' }}">` in the template, i.e. letting Contao handle the CSRF stuff.

**Comment by ausi** [comment]
I created a pull request with how I think the request tokens could work with Symfony forms: #3214
