### ISSUE TITLE
Metadaten ce_download(s) name und caption

### ISSUE THREAD

**Issue by delirius** [contao/contao#3212]
**Affected version(s)**

Contao 4.11

**Description**

Im Modul Downloads (mehrere Dateien) sind die Metadaten **name** und **caption** im Template verfügbar (ce_downloads). Und können bei Bedarf ausgegeben werden.

Im Modul Download (einzelne Datei) sind diese nicht verfügbar (ce_download).

**Comment by fritzmg** [comment]
You wrote Contao 4.11, but it's the same in Contao 4.9. It would be a simple change to add the already extracted meta information also to the `ce_download` template. @contao/developers bugfix or feature?

The only problem I see is: in the `downloads` content element, the meta information is provided for each file in the `files` array in the template. For the `download` element there is no such array obviously so the `meta` key would then overwrite a previously set `meta` key.

**Comment by ausi** [comment]
> For the `download` element there is no such array obviously so the `meta` key would then overwrite a previously set `meta` key.

Adding the line 

```php
$this->Template->meta = $arrMeta;
```

to https://github.com/contao/contao/blob/f0a6afc23de389f6342af6a67db0ebc90122ea89/core-bundle/src/Resources/contao/elements/ContentDownload.php#L134

Shouldn’t be a problem.

Not adding new template variables is not one of our backwards compatibility promises I think.

**Comment by fritzmg** [comment]
Well in theory someone could have extended the DCA of `tl_content` with a field called `meta` (for whatever reason). This field would then not be available in the `ce_download` template, because it gets overwritten with the meta data of the selected file.  🤷‍♂️

**Comment by m-vo** [comment]
But that's a problem with a lot of things, isn't it? The core could even add a new dca field that someone used before. 🙃

**Comment by fritzmg** [comment]
@leofeyer if it's a bug, it should be for 4.9, no? ;)
