### ISSUE TITLE
Angepasste Contao-Benutzerrechte für Benutzerprofil werden nicht übernommen

### ISSUE THREAD

**Issue by minstyle** [contao/contao#3224]
**Affected version(s)**

Contao 4.9.16

**Description**

Beim Anlegen einer neuen Contao-Benutzergruppe mit eingeschränkten Zugriffen auf `tl_user` werden trotzdem alle Felder im Benutzerprofil angezeigt.

Beispiel:

1. Neue Benutzergruppe, z. B. "Redaktion" erstellen und unter "Erlaubte Felder > tl_user" nur bestimmte Felder aktivieren.
2. Einen neuen Benutzer erstellen und diesen der Benutzergruppe "Redaktion" (Rechtevererbung: Nur Gruppenrechte verwenden) zuordnen.
3. Danach mit den Benutzerdaten in das Backend anmelden und in Contao oben rechts im Dropdown-Menü "Profil" auswählen.
4. Der Benutzer hat nun Zugriff auf fast alle Felder!

Screenshots:

![image](https://user-images.githubusercontent.com/2649562/127476181-1f080c10-ab7c-4cbf-9a86-d995fe00714e.png)
In der Benutzergruppe "Redaktion" sind nur folgende Felder erlaubt.

![image](https://user-images.githubusercontent.com/2649562/127476450-0fae6d1c-70e9-4001-9f90-b83b86ac6853.png)
In dem Benutzerprofil werden bspw. die Felder _Datei-Uploader_, _Erklärungen anzeigen_ und _Daten bereinigen_ angezeigt, obwohl diese in der Benutzergruppe deaktiviert wurden.

**Comment by leofeyer** [comment]
Die Felder im Benutzerprofil lassen sich nicht über Benutzergruppen einschränken. Wenn Du hier wirklich etwas deaktivieren möchtest, müsstest Du die DCA-Palette anpassen.

**Comment by minstyle** [comment]
Vielen Dank Leo für die Info.
