### ISSUE TITLE
Installation with option of a ready configured FE welcome site

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#3237]
It might be helpful to have an option during the installation to create a ready configured, simple welcome site. 

So that one can immediately achieve a functioning start page and the following, manual steps are omitted: https://docs.contao.org/manual/en/guides/add-first-index-page/

The possibility to integrate a ready-made theme exists. What is meant here, however, is merely the provision of a single start page with the required settings (default values).

Possibly this also in connection with #2781

**Comment by aschempp** [comment]
Would this be an option in the Contao Manager in your opinion?

**Comment by zonky2** [comment]
see https://community.contao.org/de/showthread.php?81537-Was-kann-Contao-leider-kein-Standard-Theme-inklusive&p=548401&viewfull=1#post548401

Consider putting the demo as a separate option in the manager as
* Contao pure
* Contao with all packages
* Contao Demo

The current way via the extension "Demo" I find not so elegant for starters, because you have to know that all Contao packages have to be installed as well and you have to import a DB dump in the installtool...

Edit: Perhaps it is possible to define a "demo format" for the manager so that one can install further demos via it e.g. Isotope demo, MetaModels demo etc.

**Comment by fkaminski** [comment]
Perhaps the definition of "demo" and "theme" should be split in more detail. In the sense of:

Optional "official" Demo Import = Content (DB based)
Meant as an introduction for Contao users to study or understand the backend settings.

Based on this then one or more themes which could be implemented/offered database independent according to the proposal:
https://github.com/contao/contao/issues/2781

**Comment by aschempp** [comment]
Also see https://github.com/contao/project/issues/7

**Comment by zonky2** [comment]
I try https://www.softaculous.com/demos/Contao ...

The start screen greets me as follows: https://easycaptures.com/fs/uploaded/1540/6718760410.png

This would certainly be better solved with the option.

**Comment by fkaminski** [comment]
The content may simply be something like "Welcome ..."
With further links to the [Contaoversum](https://contao.org/de/support.html) (documentation/forum etc.)

The idea here was just to allow a simple, ready-made, optional frontpage display (m. a welcome page (index)) after installation.

So independent from an official Contao demo.
Regarding the COD (v2) and so that this can be maintained easier in the future or so that this is not compared again and again with ready, complete "Themes" see:  https://github.com/contao/official-demo/issues/103

**Comment by may17** [comment]
I think it would be good UX / DX to generate a kickstater page, like @fkaminski suggest.

You always need to do a lot of things to get your first output on the screen. Why not just initally create a root page, a start page, a 404 page, a theme, an article and some content elements with further informations like laravel or the vue cli does? 

Again you always will do those steps and even if not it will not hurt anyone cause other people can still import their own project kickstarter sql and stuff.

**Comment by fkaminski** [comment]
Sample: After installing a fresh 4.9.20 / 4.12.x 
I will be confronted with this (Same via the preview button):

> Oops! An error has occurred
> The server returned a "404 Not Found".
> Something is broken. Please let us know what you were doing when this error occurred. We will fix the error as soon as possible. We apologize for the inconvenience caused.
> 

Would be nice to prevent such a thing... ...

**Comment by aschempp** [comment]
I really like that idea! The "no root page found" exception only appears if there is not a single page in `tl_page` (contrary to Contao 3), so it should be totally fine to adjust that template. If someone has an idea and can make a draft or an example image?

**Comment by fkaminski** [comment]
Close this because of
- https://github.com/contao/contao-demo
- and https://docs.contao.org/manual/en/guides/manager-theme/
