### ISSUE TITLE
Add avatar functionality for users and members

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#3239]
Since this is a frequently requested feature in the community, it would probably be helpful and easier for many users to use a ready-made Contao solution instead of the extension:
https://github.com/terminal42/contao-avatar

**Comment by aschempp** [comment]
Not sure what "frequently requested" means to you. In 10 years of creating Contao website, I only ever needed this once for the Contao Association website. None of my client websites ever needed that feature (in the core). 🤷

**Comment by fritzmg** [comment]
We also only only ever needed it twice or so. Imho this does not need to be integrated into the core.

**Comment by fkaminski** [comment]
Hm, nevertheless, this was created as an extension.
A need was therefore present  :-)

https://community.contao.org/de/search.php?searchid=8380853

**Comment by fritzmg** [comment]
> Hm, nevertheless, this was created as an extension.
> A need was therefore present :-)

There are a lot of Contao extensions. Surely you are not suggesting to add _all_ of them to the core? ;)

> https://community.contao.org/de/search.php?searchid=8380853

That link will not (and does not) work.

**Comment by fkaminski** [comment]
Understood. Of course, solutions exist as extensions. And of course the effort increases with each integration and it always remains a matter of trade-off. Nevertheless, some functions should be considered based on community demand. Not as an extension but as an update secure performance of the system.
JM2C

**Comment by fkaminski** [comment]
I myself have never needed it either. If at all, with a manageable number, then simply via text/photo. But can understand that some want it without an extension dependency.

**Comment by leofeyer** [comment]
Since this discussion keeps popping up, I have tried to make a diagram that shows the decision process. 😄 

<img width="444" alt="" src="https://user-images.githubusercontent.com/1192057/129232663-5b62630e-5405-4846-8850-f1fad2ee2020.png">

Note that `Add it*` means "add it or find someone who is willing to implement and maintain an extension".

**Comment by fkaminski** [comment]
@leofeyer Helpful for understanding ...
If it does not matter I therefore close this.
