### ISSUE TITLE
Improve DX when creating fragment controllers

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3241]
Running `contao-console debug-fragments` will show newly created fragment controllers while they will only appear in the back end after the cache was rebuilt. That's IMHO a bit unintuitive.  Maybe we can improve the DX?

Steps to reproduce:
* create a new `FooFragment extends AbstractContentElementController`
* run `contao-console debug-fragments` (the new element will be listed)
* open the back end (the new element cannot be found in dropdown)
* rebuild cache (…now it's available)

**Comment by bytehead** [comment]
Recognized the same a longer time ago. I've helped myself with adjusting the `cache:clear` command in my `composer.json`:
```
"@php bin/console --ansi cache:clear --no-warmup",
```

Since then no cache rebuild was needed during development and on deploy we'll warm the cache explicitely.

**Comment by fritzmg** [comment]
Hm, I cannot reproduce the problem. When using the `dev` environment, any newly created fragment is immediately visible in the back end as well via `debug:fragments`.

**Comment by m-vo** [comment]
This has definitively something to do with cache warmup and/or our setup process but I could not wrap my head around it, yet.

I noticed a similar (related?) problem with the new `debug:contao-twig` command that returns an empty hierarchy in the following case:

 - make sure the cache is nuked (`rm -rf var/cache`)
 - run `vendor/bin/contao-setup`
 - run `vendor/bin/contao-console debug:contao-twig` (empty set)
 - nuke the cache again and rerun the command (works as expected)

Maybe it has something to do how the mandatory cache warmer acts together with the cache pool. The issue only ever occurs after running the setup.

**Comment by m-vo** [comment]
Ah, weird. It's the `cache:clear --no-warmup --env=dev` causing the issue. Probably because the command (for BC reasons) also clears the cache pools.

**Comment by aschempp** [comment]
Not sure what the problem is or if we can do anything about it. In `dev`, the container is rebuilt every time (if resources change), therefore new services (= new annotations (= new tags)) should be picked up automatically. In `prod` it is only rebuild manually.

Warmup is not related to this. Cache warmers only build optional caches like the Contao internal cache (combine DCA, config.php etc) and Twig templates. Cache warming does not affect how the container is rebuilt if resources change.

**Comment by m-vo** [comment]
If I comment out the `cache:clear --no-warmup --env=dev` part in the setup command, everything works as expected. As we are nuking the cache folder anyway in the 'bin' file we could maybe drop that line (or bot clears) anyway.

**Comment by m-vo** [comment]
Our Twig filesystem loader persists things in the `cache.system` pool. It seems this pool gets lost somehow. But I'll have to debug, I guess…

**Comment by aschempp** [comment]
> If I comment out the `cache:clear --no-warmup --env=dev` part in the setup command, everything works as expected. As we are nuking the cache folder anyway in the 'bin' file we could maybe drop that line (or bot clears) anyway.

The cache clear command also executes listeners that can drop caches outside the cache folder, therefore it still must be run.

**Comment by leofeyer** [comment]
Can we implement a similar solution as we did in #3270?

**Comment by aschempp** [comment]
Honestly I think that's wrong (both here and in Twig). We should never nuke the cache, it is the responsibility of the system (e.g. container config) to know when to rebuild the cache. The container has resource tracking specifically for that, so cache can be rebuild when files (mtime) changes. It is correct that the container gives the cached information if there is a cache that is not configured to watch for changes.

**Comment by aschempp** [comment]
I think this issue is confusing multiple things. Can we please focus on fragment controller (issue) and ignore anything thats "similar" in Twig?
