### ISSUE TITLE
Issues with page mounts

### ISSUE THREAD

**Issue by Toflar** [contao/contao#3242]
**Affected version(s)**

All

**Description**

The way the current page mounts are handled causes a few issues:

1. As an editor, I cannot pick a page I do not have access to. This is nonsense because I just because I cannot edit the content of a page does not mean, I cannot link to a certain page.
2. When I add a new page, I may have issues with the alias because it already exists which is puzzling for a user as they cannot see the other pages.
3. The order of the pages in the site structure is totally random. E.g. as an admin I can sort the pages like so

- Root page A
- Root page B
- Root page C

and a user can get

- Root page C
- Root page A

I think the only real solution to this problem is to always show the whole page tree structure to all users but disallow any operations on the pages that were not allowed by the root settings.

**Comment by fritzmg** [comment]
As far as I know there are users out there who provide websites for multiple customers in the same Contao instance. The back end users for this Contao instance should only see their "own" website and not see the site structure of another customer.

**Comment by asaage** [comment]
The same is true for Filemounts.
Let's assume a directoryhierarchy like:

- departmentA
  - documents
- departmentB
  - documents

wher a user has acces to all documents Folders.
What he sees is:
 
 - documents
 - documents

I would prefer something like "traverse upwards of the actual mount to the root" and at least show all nodes which are on that path.

**Comment by aschempp** [comment]
I agree with @Toflar that this is an issue. However, we should only show the page trees the user is allowed to see – but up to the root (and "just" disable the permissions accordingly).

I don't see this applying to files though, since we never want a user to see/pick a folder she can't see imho.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 26th, it would make sense to always show the trail (the parent pages of the selected ones) up to the root page, so the pagemounts can be sorted correctly.

**Comment by asaage** [comment]
> I don't see this applying to files though, since we never want a user to see/pick a folder she can't see imho.

Can't that be done without ability to pick?
I mean in linux ```pwd``` would give me the trail in any location i can be in - even though i might not have execute right on any folder the way up to see what's inside.

**Comment by Toflar** [comment]
I'm closing this in favor of https://github.com/contao/contao/pull/3391.
Feel free to test the code and see what it does for you.
