### ISSUE TITLE
SubmitOnChange not triggering save_callback

### ISSUE THREAD

**Issue by koertho** [contao/contao#3246]
**Affected version(s)**

Contao 4.9 (occured in 4.9.16) and 4.11 (4.11.5)

**Description**

A field with submitOnChange, for example tl_member.login does not trigger the save_callback, when submitted async (e.g. the login checkbox is triggered and the subpalette ist loaded, the save_callback is not executed).

This was discussed in Slack (https://contao.slack.com/archives/CK4J0KNDB/p1627907859023700) with, among others, @ausi and @m-vo :)

**Comment by leofeyer** [comment]
What exactly does your save_callback do?

**Comment by koertho** [comment]
I wrote this issue some months ago, don't know the exact reason anymore, but from the slack-thread I think I wanted to manipulate the palette on palette change? Maybe :)

But to be honest, this is not important, as this Issue can be summarized to a single question: should the save_callback be triggered on submitOnChange events?

**Comment by koertho** [comment]
I just read the old slack thread a little more carefully and I think I wanted to evaluate if the value of the login field was changed in tl_member.

**Comment by leofeyer** [comment]
See #4236.

**Comment by bytehead** [comment]
This issue still exists on 4.13.15.
