### ISSUE TITLE
Literal insert tag replacement kills Symfony HtmlDumper output

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3249]
The `HtmlDumper` injects JS code like this ([ref](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/VarDumper/Dumper/HtmlDumper.php#L436)):

```js
if (/[\[{]$/.test(elt.previousSibling.nodeValue)) {
    // …
}
```

Our `FrontendTemplate` class however does the following on the whole buffer:
https://github.com/contao/contao/blob/8468881d30b54c448310bc2456920d4ec328e088/core-bundle/src/Resources/contao/classes/FrontendTemplate.php#L155-L156

Which means, it effectively destroys the regular expression. 

To reproduce:

* create `fe_page.html.twig`
* enter `{{ dump(app) }}`
* open a page in the browser (the dumper JS is broken)
* now comment out the above line in `FrontendTemplate` (it's working again)

**Comment by leofeyer** [comment]
Since the code is already in Symfony 4.4, I am assigning this to the `4.9` milestone.

**Comment by m-vo** [comment]
A naive fix that does not need parsing could be something like this, i.e. matching opening + closing 'literal insert tags' together:

```php
$this->strBuffer = preg_replace('/\[{](.*)\[}]/', '{{$1}}', $this->strBuffer);
```

Edit: see #3251

**Comment by m-vo** [comment]
For reference: this is the original issue were the code in question was added: https://github.com/contao/contao/issues/670
