### ISSUE TITLE
Add Option to Video Modul for Youtube "Erweiterte Datenschutz Option"

### ISSUE THREAD

**Issue by itcbchris** [contao/contao#325]
**Description**  

As of GDPR is mandatory in the EU it is recommended to use "Erweiterte Datenschutz Option" by Youtube when embeding videos from there plattform into your website.

so i thin it should be usefull to have this option implemented into the module itself.

**Example**  
Checkbox:
"Erweiterter Datenschutz Modus von Youtube".

Add: -nocookie to URL (maybe some other options? dont really know if google adds more).

**Comment by fritzmg** [comment]
This is already implemented.

**Comment by itcbchris** [comment]
As i See in 4.6?

is there no way to get it in  4.4.* there i only have:

Video ID, Player-Size, and Autoplay in Youtube  Module?

**Comment by contaoacademy** [comment]
For Contao 4.4 LTS you don't get any new features.
But you could replace the YouTube-URL in the template "ce_youtube.html5" by yourself.
