### ISSUE TITLE
Set DataContainerCallbackListener to a lower priority

### ISSUE THREAD

**Issue by koertho** [contao/contao#3255]
**Contao-Version:** 

4.11.5

**Description:**

The DataContainerCallbackListener runs as loadDataContainer - Hook and is responsible for adding dca-callbacks from annotations to the DCA. It is running with default priority and so it mostly will run before other loadDataContainer-Hook-Listener.
But when dca-fields are added from the Hook-Listener and a callback for this fields is registered as annotation, ~~the callback not get registered since the field is not in the dca~~, as the hook-Listener runs after the DataContainerCallbackListener.

EDIT: The Callback IS written in the DCA by DataContainerCallbackListener even if the field not exist, but it get's overridden when adding the field from the hook (e.g. `$GLOBALS['TL_DCA']['tl_table']['fields']['field'] = [/* ... */]`

Steps to reproduce:
1. Make your bundle load after the contao core bundle in your Contao Manager class (typically `Plugin`)
1. Create a `loadDataContainer`-Listener and add an alias field to the dca from there
1. Create a DataContainer-Class like `MemberContainer` and create a `onAliasSaveCallback`-Method with save-Callback Annotation

The callback with not be available in the DCA.

Solution:
Make DataContainerCallbackListener run on a lower priority.

**Comment by aschempp** [comment]
> But when dca-fields are added from the Hook-Listener and a callback for this fields is registered as annotation, the callback not get registered since the field is not in the dca, as the hook-Listener runs after the DataContainerCallbackListener.

I don't think that's the case. The callbacks are added just fine, but your own listener just overrides the whole field definition and therefore drops the callback again. Maybe you can solve this by using `array_replace_recursive`?

**Comment by fritzmg** [comment]
@aschempp but you should not have to do that, otherwise we will have to document that, if you add DCA fields via the `loadDataContainer` hook, you need to be careful to not overwrite existing field definitions. But if this field is unique to your installation or to your extension that does not really make sense to the developer. In my opinion the `DataContainerCallbackListener` definitely needs to run at a priority lower than the default.

**Comment by koertho** [comment]
@aschempp You're totally right, I didn't saw it :open_mouth: 

But lower the priority would still be a good change as this is still no expected behavior.

**Comment by aschempp** [comment]
> if you add DCA fields via the `loadDataContainer` hook, you need to be careful to not overwrite existing field definitions. But if this field is unique to your installation or to your extension that does not really make sense to the developer.

You also added the callback service, so you should know that field is defined. However, as I mentioned in Slack, if you dynamically define the field, you should most likely not use a service with callback either, because that would always be defined. Either just add the callback code to your field listener, or call the callback listener inside your field listener:

```php
// ...
'save_callback' => [function (...$args) {
    return $this->callbackservice->method(...$args)
}],
// ...
```

**Comment by koertho** [comment]
@aschempp I know how to solve this. I just want future developers don't have to stumple over this again. The solution is a simple lower priority. Do you see a problem changing this?

**Comment by aschempp** [comment]
Anyone expecting the current priority would have issues, changing the priority is a BC break to me. If you currently explicitly set your priority to `-1` to delete a callback, your service would not longer work.

**Comment by koertho** [comment]
@aschempp Ok, that's a valid point. Should we keep this issue for 5.0 or can we close it?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to adjust the priority of the `DataContainerCallbackListener` to `-16`. This will not solve all cases but it should solve most of them.
