### ISSUE TITLE
Bildgrößen definieren (Multi-CMS)

### ISSUE THREAD

**Issue by WebRoxx** [contao/contao#326]
In den Theme-Einstellungen (Bildgrößen) wäre es schön wenn man in den Inhaltelementen bei Bildgröße eine Zuordnung zu den Themes hat. Derzeit werden bei Multi-CMS Seiten alle Bildgrößen fortlaufend angezeigt so das ein Nutzer der über alle Seiten adminstrieren kann nicht weiß welche Bildgröße zu welcher Seite gehört. 

-------------------------------------------------------------------------------------------
**Aktuell ist es so**

**Theme 1:** 
Bildgröße A
Bildgröße B
Bildgröße C

**Theme 2:** 
Bildgröße A
Bildgröße B
Bildgröße C

Auswahl:
Bildgröße A
Bildgröße B
Bildgröße C
Bildgröße A
Bildgröße B
Bildgröße C

-------------------------------------------------------------------------------------------
**Besser wäre:** 

Auswahl:
Theme 1 - Bildgröße A
Theme 1 - Bildgröße B
Theme 1 - Bildgröße C
Theme 2 - Bildgröße A
Theme 2 - Bildgröße B
Theme 2 - Bildgröße C

**und noch besser wäre eine Gruppierung nach Theme.**

Theme 1
- Bildgröße A
- Bildgröße B
- Bildgröße C

Theme 2 
- Bildgröße A
- Bildgröße B
- Bildgröße C

**Comment by leofeyer** [comment]
Pull-Request: #539
