### ISSUE TITLE
Make sure Template#getResponse() is used correctly

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3263]
**Affected version(s)**

Contao 4.9 and up

**Description**

see https://github.com/contao/contao/pull/3258#issuecomment-892492357

Currently, `Template#getResponse()` sets headers and executes `compile()` which will make the following code run (that is only meant to run once for `fe_page` or any other 'global wrapper' template):
https://github.com/contao/contao/blob/4cf71a9b3cf787093c9cf9e076d9c1fc6104f2f5/core-bundle/src/Resources/contao/classes/FrontendTemplate.php#L102-L159

- Should users in fragment controllers use `$template->getResponse()` or `new Response($template->parse())`?
- If so: Should we move things out to listeners?

**Comment by m-vo** [comment]
taken from https://github.com/contao/contao/pull/3258#issuecomment-892493203:

> If we are setting cache headers, why not in the `AbstractFragmentController`? 
> 
> There are multiple ways how users will return a response in a fragment's `getReponse()` method:
> 
> - `return $template->getResponse();`
> - `return new Response('foo');`
> - `return $this->render('foo.html.twig');`
>
> For the last two cases I would have to set headers myself while the first one would set them for me?

**Comment by leofeyer** [comment]
I guess they should use `new Response($template->parse())`.

**Comment by fritzmg** [comment]
> I guess they should use `new Response($template->parse())`.

But then the appropriate response headers would be missing if the fragment is rendered as ESI.

**Comment by m-vo** [comment]
> But then the appropriate response headers would be missing if the fragment is rendered as ESI.

They are missing anyway if I don't use Contao templates. Can't we add the headers in the controller?

**Comment by fritzmg** [comment]
True. The only header that makes sense to me that maybe should be added by the template itself is `Content-Type`, since the template knows its content type. But even that depends on `Config::get('characterSet')` currently - which is always `UTF-8`.

**Comment by m-vo** [comment]
I think there are two places where we should split/reorganize responsibilities. Here are some thoughts:

### Template#getResponse()

Here is how this could potentially look when dissected:

* `Template#getResponse()` is simplified to only set the content, content-type and charset:

    ```php
    public function getResponse()
    {
    	$response = new Response($this->compile());
    	$response->headers->set('Content-Type', $this->strContentType);
    	$response->setCharset(System::getContainer()->getParameter('kernel.charset'));  // drop this as its's always UTF-8?
    
    	return $response;
    }
    ```
   I'm not sure about the additional cache settings that `BackendTemplate` ('no-cache, no-store', private) and `FrontendTemplate` (apply the page's cache settings in case of a fe_* template) are applying. To me they shouldn't be in there either but be moved to the respective controllers (or legacy counterparts – e.g `PageRegular`?). 


* The FLoC stuff is moved to a `kernel.response` listener:
    ```php
    	$response->headers->set('Permissions-Policy', 'interest-cohort=()');
    ```

* In a new `AbstractFragmentController#finalizeResponse()` that is called by `__invoke()` with the response before it is returned we enable merging of cache headers:
    ```php
    protected function finalizeResponse(Response $response): void {	
    	// Mark this response to affect the caching of the current page but remove any default cache headers
    	$response->headers->set(SubrequestCacheSubscriber::MERGE_CACHE_HEADER, true);
    	$response->headers->remove('Cache-Control');
    }
    ```
   In this same method we could execute `addSharedMaxAgeToResponse()` for the `AbstractContentElementController` case for instance.

###  Template#compile()

In `FrontendTemplate#compile()` we are doing A LOT<sup>TM </sup>:
1. something with meta keywords I don't understand
1. parse the template
1. execute the `outputFrontendTemplate` hook
1. replace insert tags and dynamic script tags
1. execute the `modifyFrontendPage` hook
1. check for unused `$_GET` parameters (if enabled)
1. minify the markup (if in a page context + enabled)
1. replace literal insert tags

Points 6-8 shouldn't be there IMHO, same goes for the hooks that should only be executed once for each page (not for fragments), so 3-8 could maybe be moved into a `kernel.response` listener. If 1. could be sorted as well `compile` and `parse` would be equivalent.

(btw: `BackendTemplate#compile()` looks different but IMHO the above reasoning could apply there as well.)

**Comment by aschempp** [comment]
> In a new AbstractFragmentController#finalizeResponse() that is called by __invoke() with the response before it is returned we enable merging of cache headers.

This will not work and I cannot think of any other place that will. We must not merge a "default" response into our cache strategy, because a response is always marked as `Cache-Control: private` by default. We cannot know if this was intentionally set by the controller or is just the default. Thats why we remove all cache header and mark the response as _to be merged_, so that when it does have `Cache-Control` it must have been added by `getResponse()` and is intended to be merged into the final response.

**Comment by m-vo** [comment]
> We cannot know if this was intentionally set by the controller or is just the default.

You would overwrite the method if you did not want our default behavior.

**Comment by aschempp** [comment]
Sorry I misread that you want to add this method to the fragment. I would rather have a `createResponse` instead that should be called explicitly be developers, otherwise they simply won't get cache header merging.

**Comment by koertho** [comment]
@fritzmg Asked me to add this to this thread: 
This Issue leads to problems with Messages in Isotope, as the `modifyFrontendPage` Hook is called on `Template::getResponce()`, so `Isotope\Frontend::injectScripts` is executet when an Fragment in rendered. 

Slack: https://contao.slack.com/archives/CK4J0KNDB/p1633089378175200
Isotope Issue: https://github.com/isotope/core/issues/2255
