### ISSUE TITLE
Convert country codes to lowercase

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3265]
**Affected version(s)**

Contao 4.12.0-RC2

**Description**

I wonder if we really want to force everyone to write

```php
            'options_callback' => static function () {
                $countries = System::getContainer()->get(Countries::class)->getCountries();

                // Convert to lower case for backwards compatibility, to be changed in Contao 5.0
                return array_combine(array_map('strtolower', array_keys($countries)), $countries);
            },
```

instead of e.g.

```php
            'options_callback' => static function () {
                return System::getContainer()->get(Countries::class)->getCountries(null, true); // the second argument will be dropped again in Contao 5
            },
```

in their own DCAs?

**Comment by fritzmg** [comment]
Didn't we decide on keeping country codes lowercase anyway? 🤔

**Comment by leofeyer** [comment]
I don't think so. The new methods returns them uppercase and @ausi has explicitly added the code above.

**Comment by ausi** [comment]
> Didn't we decide on keeping country codes lowercase anyway? 🤔

See https://github.com/contao/contao/pull/3138#issuecomment-877806289 _“I think we should keep it lowercase for BC and change it in Contao 5.”_

> I wonder if we really want to force everyone to write

I think we explicitly want everyone to write that because they should use the uppercase version instead. And everyone that uses the deprecated `System::getCountries()` already gets it converted to lowercase.

**Comment by leofeyer** [comment]
But what is the advantage of having uppercase codes? It will break every extension using them for no obvious reason.

**Comment by fritzmg** [comment]
Any existing extension will have used `System::getCountries()`. You will only get the standardised uppercase codes, if you use the new `Countries` service.

**Comment by ausi** [comment]
> But what is the advantage of having uppercase codes?

It is the standard and should potentially increase the interoperability.

> It will break every extension using them for no obvious reason.

It will break some extensions in Contao 5.0 that expect `tl_member.country` to be lowercase.

We also changed `tl_page.language` from `de-DE` to `de_DE` (and this change was made in a minor release).

**Comment by leofeyer** [comment]
> It will break some extensions in Contao 5.0 that expect `tl_member.country` to be lowercase.

I guess it will be more than just "some". I am maintaining four custom extensions for contao.org and they are **all** affected. 😄

**Comment by leofeyer** [comment]
But maybe that is OK in a major release.

Anyway, what I was actually suggesting in this ticket is to add a flag to make the `getCountries()` method return the language keys in lowercase. Can we add this and remove it again in Contao 5?

**Comment by ausi** [comment]
> Anyway, what I was actually suggesting in this ticket is to add a flag to make the `getCountries()` method return the language keys in lowercase.

I think it would be better to not add that so that extension developers see that the uppercase version is preferred.

**Comment by leofeyer** [comment]
But I understand that uppercase language codes are standard, so I guess that is a reasonable breaking change. And regarding  the initial question, we can continue to use `System::getCountries()` to remain backwards compatible.

**Comment by leofeyer** [comment]
<img width="479" alt="" src="https://user-images.githubusercontent.com/1192057/128326813-aa189a73-5ba9-4ae1-a7b8-8732312584dd.png">

That was an accident. Sorry. 🙈

**Comment by ausi** [comment]
<img width="841" alt="Bildschirmfoto 2021-08-05 um 11 26 56" src="https://user-images.githubusercontent.com/367169/128326992-318b985f-fece-4c8c-b170-960f5a51e67f.png">

😜
