### ISSUE TITLE
Missing translations in System::getLanguages()

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3266]
**Affected version(s)**

Contao 4.12.0-RC2

**Description**

Having `'options' => System::getLanguages(),` in my custom DCA, I get the following error:

<img width="974" alt="" src="https://user-images.githubusercontent.com/1192057/128196699-b4f55a5e-431c-44a7-a6d7-ae79cccad65b.png">

@ausi Is this intended?

**Comment by ausi** [comment]
> Is this intended?

No 😓

We should probably use `$translator->getCatalogue()->has(…)` instead. 
But we will need to implement `getCatalogue()` on our translator first to make that possible I think.

**Comment by ausi** [comment]
> We should probably use `$translator->getCatalogue()->has(…)` instead.
> But we will need to implement `getCatalogue()` on our translator first to make that possible I think.

Done in #3276
