### ISSUE TITLE
Register Twig namespaces for themes outside of /templates

### ISSUE THREAD

**Issue by richardhj** [contao/contao#3271]
**Affected version(s)**

Contao 4.12

**Description**

Currently, in the 4.12 RC, all theme templates folders under `/templates` get registered, i.e., https://github.com/contao/contao/blob/4.x/core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php#L54-L59

Prior to 4.12, it was supported to set a theme template folder to a path outside of `/templates`.
```sql
UPDATE tl_theme SET `templates` = '/themes/my_theme/templates' WHERE id=1
```

With an eye on #2781, this behavior will also become necessary. This behavior is consequently required by my [theme-framework](https://github.com/richardhj/contao-theme-framework) extension.

**Comment by m-vo** [comment]
Currently the template locator returns all subdirectories of `/template` as theme paths and each is added:

https://github.com/contao/contao/blob/722d397e3429e3fc4a8d05263fe2f834aa8f2122/core-bundle/src/Twig/Loader/TemplateLocator.php#L46-L70

https://github.com/contao/contao/blob/722d397e3429e3fc4a8d05263fe2f834aa8f2122/core-bundle/src/Twig/Loader/ContaoFilesystemLoaderWarmer.php#L54-L59

We could maybe return registered paths from `tl_theme` instead and refresh the loader cache whenever a new folder gets picked in the back end.

But how would the slugs (used for namespaces) look for arbitrary paths? 
Currently they are `str_replace('/', '_', Path::normalize($relativePath))`.

**Comment by richardhj** [comment]
> But how would the slugs (used for namespaces) look for arbitrary paths?
> Currently they are `str_replace('/', '_', Path::normalize($relativePath))`.

Has to be the full path.
But if we decide whether #2781 will be integrated into Contao one day, we can also strip the `/\/themes/(.*?)/templates/` part.

**Comment by ausi** [comment]
In order to prevent duplicates we could use `@Contao_Theme_foo` for /templates/foo and `@Contao_Theme__foo` for /foo

**Comment by ausi** [comment]
Would be something like `str_replace(['../', '/'], '_', Path::normalize($relativePath))` then.

**Comment by m-vo** [comment]
> In order to prevent duplicates we could use @Contao_Theme_foo for /templates/foo and @Contao_Theme__foo for /foo

Or we always use the project-relative path:  `@Contao_Theme_templates_foo` and `@Contao_Theme_foo`.
These long namespaces aren't really nice, though and you would probably use them inside your templates when including things inside a theme folder…

**Comment by m-vo** [comment]
closing in favor of #3414
