### ISSUE TITLE
Allow selecting Twig templates in every back end dropdown 

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3274]
**Affected version(s)**

Contao 4.12

**Description**

Allow selecting `.html.twig` templates in every back end dropdown. Currently only templates where a `.html5` version exists will be listed. This includes the variant templates (underscore + variant name suffix).

**Comment by fritzmg** [comment]
More generally I wanted to build a `TemplateFinder` service for Contao 4.13 that would essentially handle `Controller::getTemplate` and `Controller::getTemplateGroup`. In a recent project I noticed how inflexible the current system is as I needed to dynamically adjust the visible back end templates on the one hand and on the other hand influence which template to actually use in the front end.

**Comment by m-vo** [comment]
The template hierarchy might be a good starting point - in there all templates (`.html5` and `.html.twig`) are already registered (see `debug:contao-twig`). We could implement the grouping logic on top.

**Comment by m-vo** [comment]
Reading through the code I wonder why we are both using snake cased template names and the underscore as a separator between the original template name and a variant suffix. Without this we would not need any registry of content element/module/form/custom group templates but could just search for prefixes, no? Do I miss something?

**Comment by aschempp** [comment]
> Reading through the code I wonder why we are both using snake cased template names and the underscore as a separator between the original template name and a variant suffix. Without this we would not need any registry of content element/module/form/custom group templates but could just search for prefixes, no? Do I miss something?

For historical reasons 😅 and because "we made a mistake" when implementing fragments and sticking to snake_case instead of camelCase for the default template name 😞

**Comment by m-vo** [comment]
You know the old saying: 

"It's never too late,
for a BC break. :musical_note:"
