### ISSUE TITLE
Navigation is not displayed when linking internally to missing page.

### ISSUE THREAD

**Issue by whitedrow** [contao/contao#3277]
**Affected version(s)**

Contao 4.9 

**Description**

If you use the navigation menu module, it can happen that it is not displayed if there is an internal link (page type: internal redirect) within the page structure to a page that no longer exists or is deactivated.

No output takes place in the frontend.

No error or warning is written to the log.

**Solution**

Error output in the error log. 
For example: Cannot display the module because it links to a non-existent or inactive page.

**Comment by aschempp** [comment]
Do you mean the whole navigation module is not shown or just the internal redirect page is not in the navigation?

**Comment by whitedrow** [comment]
The whole navigation is not shown.

If you use <?php $this->showTemplateVars() ?> you can see that the header content (or whatever content area you use) is complete empty.

**Comment by fritzmg** [comment]
I cannot confirm the problem. This is how I tried to reproduce it:

1. I am using a regular `navigation` module, with default settings. This module is inserted in the page layout.
2. I created and published a regular page called "Page to be deleted".
3. I created and published an internal redirect page with default settings, pointing to "Page to be deleted".
4. I confirmed in the front end, that the navigation is showing both pages as expected.
5. I deleted the page "Page to be deleted".

The front end still showed the navigation module, but with both the pages "Page to be deleted" and the internal redirect page missing from the navigation as expected.

**Comment by whitedrow** [comment]
uh...sorry. I forget to mention an essential thing: The pages are "hide from navigation" except the pages with the redirection.

In the following setting the navigation modul is NOT rendered.
![Bildschirmfoto 2021-08-10 um 15 04 25](https://user-images.githubusercontent.com/7723454/128872390-d69ba18d-06fe-4e2d-8c2d-56c29a336a3f.png)


If i set **Page C** to visible the navigation is rendered.

![Bildschirmfoto 2021-08-10 um 15 10 47](https://user-images.githubusercontent.com/7723454/128872894-2184c43e-67af-43d5-8a9f-c76f77650b76.png)

**Comment by ausi** [comment]
That is the expected behavior I think because page C is not published so there is no URL where Page A can redirect to.

**Comment by fritzmg** [comment]
> uh...sorry. I forget to mention an essential thing: The pages are "hide from navigation" except the pages with the redirection.
> 
> In the following setting the navigation modul is NOT rendered.

That's the expected behaviour. If _all_ pages are hidden from the navigation or unpublished (or deleted), no navigation is rendered. Why do you expect it to be different?

**Comment by whitedrow** [comment]
**Page A** is not hidden, so the module should render it at least.
Seems that the **quick navigation** module does things right.

In the above example, it is not really a problem.
But on a project with pages 700+ and many editors it's hard to maintain and the error is hardly to be found. Or have I missed something and there is a better way to find out which page is _at fault_?

As I said in the beginning: 
It would be better if there would be a log warning output or little yellow triangle or something else.

**Comment by fritzmg** [comment]
> **Page A** is not hidden, so the module should render it at least.

But the target Page of **Page A** is not published, hence it's correct that **Page A** is not displayed, otherwise it will just point to a non-existing page.

> But on a project with pages 700+ and many editors it's hard to maintain and the error is hardly to be found.

I am not sure I understand the problem. If you have 700+ pages and all of them are hidden from the navigation, what is the expectation?

**Comment by fritzmg** [comment]
> It would be better if there would be a log warning output or little yellow triangle or something else.

Do you mean, you want this warning, if an internal redirect page points to a page that is either unpublished or deleted (regardless of the navigation module behaviour)? That should be feasible, yes. 👍

**Comment by whitedrow** [comment]
The problem is that the page being linked to can be anywhere in the page structure. So the problem is not that 700 pages are not visible, but that 700 pages are no longer visible when linking to an invisible page within these pages.

So, yeaaah: I want a hint what went wrong

**Comment by asaage** [comment]
I dont see a Problem here.
Maybe the Term "Redirect/Weiterleitungsziel" is a bit missleading. The Navigation allways takes that into account.
You would **NOT** see ```page_A.html``` in the nav-module and get a 301 to page_c anyway. Instead it would link directly to ```page_c.html``` if it was published.
On the other hand if you request the published ```page_A.html``` directly you would be redirected and get 404 page_c not found.

**Comment by fritzmg** [comment]
>  but that 700 pages are no longer visible when linking to an invisible page within these pages.

But we could not confirm this problem. May be this is something specific to your Contao installation? Were you able to reproduce the problem in a clean Contao installation, or in the Contao Online Demo?

**Comment by whitedrow** [comment]
> > It would be better if there would be a log warning output or little yellow triangle or something else.
> 
> Do you mean, you want this warning, if an internal redirect page points to a page that is either unpublished or deleted (regardless of the navigation module behaviour)? That should be feasible, yes. 👍

I would recommend this as the answer to the problem.

**Comment by fritzmg** [comment]
> I would recommend this as the answer to the problem.

But it seems like your setup is having a different problem ;). The whole navigation should not vanish, if there are still eligible navigation items. I think you should investigate this further first.

**Comment by whitedrow** [comment]
Ok, one last attempt to explain: The problem is not that a redirect to a deleted page makes no sense.
The problem is that the entire navigation module is then not displayed without explaining to the editor why this would be the case.

This can easily be adjusted in a clean installation.

However. If this is only a problem for me and not for anyone else in the world, then the ticket can be closed.

But: You have been warned ;-)

**Comment by fritzmg** [comment]
> The problem is that the entire navigation module is then not displayed without explaining to the editor why this would be the case.

As already said, we could not confirm this problem. Can you provide reproduction steps in a clean Contao installation or in the Contao Online Demo?
