### ISSUE TITLE
Creating a new folder in dev env, PHP 8 causes an ErrorException

### ISSUE THREAD

**Issue by hjurgeleit** [contao/contao#3301]
**Affected version(s)**

 Contao 4.11 (PHP 8.0.9)

**Description**
When **creating a new folde**r in the backend in **APP_ENV=dev** a warning occurs:
```Attempt to read property "id" on null```
This leads to an ErrorException in vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php (line 1324)

**Solution**
Check, if $objModel is not null:
```$objVersions = new Versions($this->strTable, $objModel->id ?? null);```

**Comment by ausi** [comment]
I can confirm this issue, the error occurs when creating a new folder in the file manager.

Maybe we should skip this whole block when the model is `null`?

https://github.com/contao/contao/blob/807e7d92ec0d359333cebcae32fb8a91bf132cbb/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L1323-L1342

**Comment by ausi** [comment]
Closed in favor of #3346
