### ISSUE TITLE
Installtool wants to change database columns forever with PHP 8

### ISSUE THREAD

**Issue by tabcontao** [contao/contao#3305]
**Affected version(s)**

Contao 4.9 and Contao 4.11

**Description**

After installing Contao 4.11 at All-Inkl Webhosting Contao seems at first ok. The install tool creates the needed tables and does not show any database changes afterwards. But after installing an arbitrary bundle (e.g. I installed Rocksolid Custom Elements), the installtool insists on changing database columns which already have been created during Contao installation. After starting the database update those changes are still shown. Contao seems to work ok, though.

** Hosting Envoronment **

Hosting: All-Inkl Webhosting Premium
PHP-Version: 8.0.6
MySQL: (Infos according to phpMyAdmin)
Server-Typ: MariaDB
Server-Version: 10.5.11-MariaDB-1:10.5.11+maria~focal-log - mariadb.org binary distribution
Protokoll-Version: 10

The issue is only seen PHP 8.0.6 and All-Inkl Webhosting, switching to PHP 7.4 the issue disappears. Going back to PHP 8 it appears again. Others have reported that this also happens with Contao 4.9.
[Link to phpinfo output](https://bit-01.de/phpinfo.pdf)
[Link to forum thread](https://community.contao.org/de/showthread.php?81278-Installtool-installiert-nicht-oder-so)

**Comment by ausi** [comment]
> But after installing an arbitrary bundle (e.g. I installed Rocksolid Custom Elements)

Can you post the output that composer showed when installing this extension (maybe another package got updated in the process or a new dependency got installed).

> After starting the database update those changes are still shown.

Can you test via SSH if the command `vendor/bin/contao-console contao:migrate` is affected too?

What is the version of the `doctrine/dbal` package in your installation?

**Comment by tabcontao** [comment]
> Can you post the output that composer showed when installing this extension (maybe another package got updated in the process or a new dependency got installed).

It's gone, but I will repeat the installation later today and provide the output. 

> Can you test via SSH if the command vendor/bin/contao-console contao:migrate is affected too?

Yes, I run the command, it outputs something like
[OK] Executed 575 SQL queries.
[OK] All migrations completed.

I run it again and get the same output again.

> What is the version of the doctrine/dbal package in your installation?

2.13.2

**Comment by tabcontao** [comment]
Just did a complete re-installation. Reproduction appears to be even more simple. No need to install another bundle. After the installation of Contao 4.11 is complete, login once to the BE (probably not necessary), logout. Then just rebuild the application cache and start the install tool again. There we are ...

Anyway, attached the console output of the installation of Rocksolid Custom Elements as requested.

[Konsole-Installation-RSCE.txt](https://github.com/contao/contao/files/6981509/Konsole-Installation-RSCE.txt)

**Comment by fritzmg** [comment]
@tabcontao are these the exact reproduction steps?

1. Install Contao 4.11.
2. Update the database and create an admin account.
3. Login to the back end and then logout.
4. Run `composer install` again.
5. Log into the Install Tool again.

Or how exactly did you rebuild the application cache?

**Comment by tabcontao** [comment]
I rebuilt the application cache by clicking on "Prod.-Cache erneuern" in the "Systemwartung" Page. This would replace your step 4. Alternatively install an arbitrary module, which will also lead to a rebuild of the application cache. I tested this with Rocksolid Custom Elements. As I just tested, running "composer install" again seems NOT to rebuild this cache, at least this didn't appear in the console output. I didn't test if "composer install" would be sufficient to reproduce the issue, though. 
Besides this step 4, your reproduction steps are exactly what I did to reproduce the issue.

**Comment by fritzmg** [comment]
> As I just tested, running "composer install" again seems NOT to rebuild this cache, at least this didn't appear in the console output.

What do you mean by that? `composer install` also rebuilds the cache, unless there are no post-install and post-update scripts defined in your `composer.json`. Can you please post your composer.json?

I tried with my reproduction steps locally under PHP 8.0.6 and MariaDB 10.5.11, but was not able to reproduce it this way.

**Comment by tabcontao** [comment]
Yes, it has to be something in the configuration of PHP 8 and MariaDB at All-Inkl, IMHO. Noone has reported it from other hosters yet.

**Comment by tabcontao** [comment]
Forgot the composer.json. What I did mean with "seems NOT to rebuild ..." is that this was not shown in the console. It may have happened somehow anyway, I don't know. Edit: You're right, I just tried that again and yes, it DOES warm up the cache. Didn't scroll up enough last time, sorry. Below the composer.json ...

composer.json
----------
```
{
    "type": "project",
    "require": {
        "contao/calendar-bundle": "4.11.*",
        "contao/comments-bundle": "4.11.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "4.11.*",
        "contao/listing-bundle": "4.11.*",
        "contao/manager-bundle": "4.11.*",
        "contao/news-bundle": "4.11.*",
        "contao/newsletter-bundle": "4.11.*",
        "madeyourday/contao-rocksolid-custom-elements": "^2.3"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}

```

**Comment by fritzmg** [comment]
@tabcontao could you post the result of

```
SELECT @@sql_mode;
```

in the database?

**Comment by tabcontao** [comment]
<html><body>


@@sql_mode |  
-- | --
NO_ENGINE_SUBSTITUTION


</body>
</html>

**Comment by fritzmg** [comment]
Thank you. Could not reproduce it with that either though.

**Comment by tabcontao** [comment]
Yes, it might get quite difficult to track down this issue. Especially when there ist no way to really debug the Installtool code on the webserver. I'm also aware, that it's probably caused by a special and unique combination of PHP 8 version/configuration and MariaDB version/configuration. It has shown up nowhere besides All-Inkl webhosting yet. And although I would think it has to be a MySQL thing, it doesn't happen with PHP 7.4 using the same MariaDB server. Could it be a difference in the ini-Files used in PHP 7.4 and PHP 8.0.6? Is it possible to read out ini-files in e.g. /etc/php80/cgi/conf.d via Apache? Well, probably not, but maybe worth a try. Otherwise I might try to read out the parameters/settings via SQL, using PHP 7.4 and 8.0 and compare them. As there are quite a lot of Contao installations at All-Inkl, it would be good to find a fix or something to communicate to All-Inkl, although the issue is mainly about making users insecure and not so much about Contao having a _**real**_ problem.

Do you know how exaxtly the comparison of intended table structure and real existing table structure is done? I thought about debugging the output of the MySQL queries involved.

**Comment by fritzmg** [comment]
Can you provide SSH access to one such instance? (And then may be @ausi can take a look at it 🙈)

**Comment by tabcontao** [comment]
Well, not before next week anyway. At least, I'll have to ask the users of a (not encrypted) Nextcloud instance running there for permission first. Alternatively, All-Inkl also offers a free 7-day test account, which would certainly reproduce the same issue. If all else fails, I would have to move the Nextcloud elsewhere.

Edit: We agreed on moving the Cloud, it was planned anyway, to do this in the near future. Therefor, I can provide SSH-Access on Monday.

**Comment by tabcontao** [comment]
I'm ready with the preparations now, the cloud has moved. I've set up the instance once again from scratch. The steps were:

1. Install Contao 4.11.
2. Update the database and create an admin account.
3. Login to the back end and then logout.
4. Rebuild the application cache.
5. Log into the Install Tool again.

If you log into the Install Tool again before step 4, all seems normal, no proposed database changes listed.

So, if it is still of interest, I could provide SSH-Access to the instance now. Just give me a note who should receive the SSH access info and how I can submit it.

**Comment by ausi** [comment]
> Just give me a note who should receive the SSH access info and how I can submit it.

via https://contao.slack.com/ to @ausi or via email to martin@contao.org

**Comment by ausi** [comment]
The error seems to be related to the MySQL connection. The php process executed by the manager is not able to connect to the database and results in an `SQLSTATE[HY000] [2002] No such file or directory` error.

Because of this, the manager plugin thinks that there are no credentials yet and sets the database server version to `5.5` here: https://github.com/contao/contao/blob/807e7d92ec0d359333cebcae32fb8a91bf132cbb/manager-bundle/src/ContaoManager/Plugin.php#L321-L331

With the wrong server version in the container cache, doctrine seems to be unable to correctly compare the columns default values.

Hardcoding the `doctrine.dbal.connections.default.server_version` to `mariadb-10.5.11` doesn’t seem to help either because it gets overwritten by the plugin.

Using “Clear Production Cache” (instead of rebuild/warmup) in the Contao Manager does not fix the issue because the container cache (with the wrong serverVersion) still gets generated this way.

Deleting the *var/cache/prod* manually fixes the issue on this webspace because it deletes the cached container.

***

I think we should maybe look into two things now:

1. Try to improve the check in the plugin or find a workaround that does not need setting the `server_version`.
   See #3345
2. Add an `rm -rf var/cache/prod` to the “Clear Production Cache” after the `cache:clear` command.
   See https://github.com/contao/contao-manager/issues/655

***

@tabcontao thank you for providing access to your webspace!

**Comment by fritzmg** [comment]
Interesting, but why does it only happen in PHP 8.0?

**Comment by ausi** [comment]
> Interesting, but why does it only happen in PHP 8.0?

I would guess that the php74 process is allowed to connect to the database if executed via the Contao Manager.

**Comment by tabcontao** [comment]
@ausi thanks for analyzing the problem.

So it is a problem occuring in the console process that the manager creates for the tasks? Are the credentials, that the manager process provides in the connect-Function incorrect or is the process unable to connect to the MariaDB-Server despite providing correct credentials? Would it be feasible to extract a piece of code that is simple enough for All-Inkl to search the configuration problem, which it IMHO might well be. Besides, that the plugin is not able to spot this problem, which is a bad thing and should be improved, but is not the real cause of the problem. If they (All-Inkl) had a quite simple piece of code that would reproduce the problem with the MySQL connection, it might be easier for them to spot and solve their problem. At least, if it's not something they configured intentionally for security reasons or whatever. But this is unlikely, IMHO, because it works with their other PHP versions.

Anyway I'll preserve the Webspace, SSH credentials, Contao instance and its database as it is for some time, just in case there are still some things which need to be checked. After moving the Nextcloud, there's nothing productive left in this webspace at the moment anyway.

Did I get it right, that removing var/cache/prod manually will resolve the problem and the cache would then be rebuilt by the Contao webprocess during the processing of the first request? Then this would be a workaround for All-Inkl customers for the time being.

**Comment by fritzmg** [comment]
> Did I get it right, that removing var/cache/prod manually will resolve the problem and the cache would then be rebuilt by the Contao webprocess during the processing of the first request? Then this would be a workaround for All-Inkl customers for the time being.

Not recommended though, as this will not build Contao's internal cache. Though accessing the Install Tool afterwards might build it.

**Comment by ausi** [comment]
> Would it be feasible to extract a piece of code that is simple enough for All-Inkl to search the configuration problem…

Done. I sent you an email with the details. The test scripts have the following contents:

```php
// connect.php
$dbh = new PDO('mysql:host=localhost;dbname=…', '…', '…');
var_dump($dbh->query('SHOW TABLES')->fetchColumn());
```

```php
// execute-connect.php
passthru('/usr/bin/php80 '.__DIR__.'/connect.php');
```

Both scripts run without issues via SSH, but the second script does fail if executed via the webserver.

**Comment by tabcontao** [comment]
I contacted the support and provided the information and scripts. The answer is:

> ...
Ihre SSH-Umgebung unterscheidet sich von der passthru-Umgebung. Ich habe Ihr Skript connect.php einmal um die Angabe des Sockets erweitert:
>
>unix_socket=/var/run/mysqld/mysqld.sock
>
>Dieses schlägt nun nicht mehr fehl. Bitte prüfen Sie auch einmal, ob Sie dies in Ihrer Software setzen können.

**Comment by fritzmg** [comment]
@tabcontao what exact changes to the script did they make?

**Comment by ausi** [comment]
~~/cc @aschempp~~

~~But I don’t think setting `unix_socket` can our should be the responsibility of the contao manager, or should it?~~

**Comment by ausi** [comment]
> what exact changes to the script did they make?

They changed the line 

```php
$dbh = new PDO('mysql:host=localhost;dbname=…', '…', '…');
```

to:

```php
$dbh = new PDO('mysql:host=localhost;dbname=…;unix_socket=/var/run/mysqld/mysqld.sock', '…', '…');
```

**Comment by fritzmg** [comment]
So on All-Inkl. Hosting, the database connection needs to be defined like this:

```
DATABASE_URL=mysql://user:password@localhost:3306/db_name?unix_socket=/var/run/mysqld/mysqld.sock
```

**Comment by fritzmg** [comment]
But still, All-Inkl. should investigate why their passthru environment (whatever that is) is different - and only under PHP 8.0.

**Comment by ausi** [comment]
> passthru environment (whatever that is)

I guess they refer to the `passthru()` function used in the test script.

**Comment by tabcontao** [comment]
>@tabcontao what exact changes to the script did they make?

Exactly like @ausi wrote, the changed connect.php now looks like that

```
<?php

$dbh = new PDO('mysql:host=localhost;dbname=...;unix_socket=/var/run/mysqld/mysqld.sock', '...', '...');
var_dump($dbh->query('SHOW TABLES')->fetchColumn());
```

**Comment by tabcontao** [comment]
Well, I'll do some comparisons to PHP 7.4 concerning the output of a info.php, containing a call to phpinfo(), when executed the same way as connect.php. Then I will politely ask, why this "passthru environment" has to behave differently between PHP 8.0 and PHP 7.4 concerning the socket. A difference I certainly find not very intuitive at best. Given there is a workaround anyway by specifying the socket explicitly, I really can't imagine a reason, why they should not simply provide the correct default value for it. Just like they obviously do with PHP 7.4. Maybe they can enlighten me.

**Comment by tabcontao** [comment]
Just for information ...
I looked into the configuration of PHP 8.0 and 7.4 in my Webhosting and found, that in both cases the value of 
`pdo_mysql.default_socket `
is not set in the global php.ini. So whatever the value of this variable is, it's either The PHP default or compiled into PHP. Unfortunately, it can't be set elsewhere (.user.ini or whereever). In the case of PHP 8.0.6 it IS the PHP default (/tmp/mysqld.sock), while in the case of PHP 7.4 it is the correct value (var/run/mysqld/mysqld.sock). So I guess they usually compile it in and maybe forgot this here. I asked them if it wouldn't be possible to set the value in the php.ini to correct the default value globally. 
Still interesting, the default socket path ist set correctly in the CLI-Version if you start it via SSH. So there must be actually something like a "passthru environment" which can be different from the "normal" CLI-Version, although they seem to share the same php.ini, which doesn't set the variable.

Ok, I see there is another plan to solve the problem by now.

**Comment by fritzmg** [comment]
> In the case of PHP 8.0.6 it IS the PHP default (/tmp/mysqld.sock), while in the case of PHP 7.4 it is the correct value (var/run/mysqld/mysqld.sock).

This is definitely something that All-Inkl. needs to fix then.

> Ok, I see there is another plan to solve the problem by now.

All-Inkl. should still fix their PHP setup though.

**Comment by ausi** [comment]
> Ok, I see there is another plan to solve the problem by now.

If you mean #3345 and https://github.com/contao/contao-manager/issues/655 by that, they will not fix the issue but (only) make such cases easier to debug.

**Comment by tabcontao** [comment]
Ah, ok. All-Inkl already fixed the problem - for me at least. pdo_mysql.default_socket ist correct now, the test script works and also the Contao Manager. I hope they will fix it on other servers too, if not already done.

**Comment by fritzmg** [comment]
Btw. this can happen, if the wrong `server_version` gets stored in the container (see also https://github.com/contao/contao/issues/3345). Reproduction:

1. Disable your `DATABASE_URL` in your `.env.local`.
2. Clear the application cache (e.g. with `rm -rf var/cache`).
3. Execute `composer install` for example to rebuild the cache.
4. Enable your `DATABASE_URL` in your `.env.local` again.
5. Run `vendor/bin/contao-console contao:migrate --no-interaction` or open the Contao Install Tool and execute the database updates.
6. Run `vendor/bin/contao-console contao:migrate --no-interaction` or open the Contao Install Tool and execute the database updates again.

The command and the Install Tool will want to execute the same changes again and again. This is because due to the fallback `server_version` cached in the container, the `_platformOptions` for the target schema get removed. But since the database already has the appropriate platform options defined (e.g. `utf8mb4` and `utf8mb4_unicode_ci`), a diff is created. That process it then repeated indefinitely.

Once you clear your application cache again, the actual `server_version` will be stored in the container again and this problem will not occur anymore.

**Comment by leofeyer** [comment]
> Hardcoding the `doctrine.dbal.connections.default.server_version` to `mariadb-10.5.11` doesn’t seem to help either because it gets overwritten by the plugin.

I've had the same problem on contao.org today (Contao 4.12.2) and hardcoding the `server_version` to `mariadb-10.3.1` did fix it. Not sure if this is helpful but I wanted to mention it at least.
