### ISSUE TITLE
Info broken in file manager

### ISSUE THREAD

**Issue by kikmedia** [contao/contao#3306]
**Affected version(s)**

Contao 4.9.19, 4.11.8 & 4.12.0-RC3 

**Description**

In Contao 4.9 the file info in backend is broken. 

If one navigates to file manager and clicks at the blue 'i'-icon of a file or folder, the next thing one will see is a popup with the message "File not found."

I can reproduce this in the official demo.contao.org, so this is not an issue with extensions.

Some users reported that this behaviour occurs since version 4.9.18.

**Comment by kikmedia** [comment]
This seems to be a little bit ridiculous. I just tested this in another installation with the result, that the icon works on some but only a few folder names.

I've got two protected folders "AutobackupDB" and "TinyTemplates". The info is shown at the first, but not the second.

I've got unprotected folders, and there are some I get the info on, and there are files on root level, where the info works in some and won't work in others.

All files or folders belong to the same user and have the same rights.

Addendum: There are files in a folder where the information is inaccessible (in my case /bootstrap/css). Some of them are working fine, others don't. This is what other users report accordingly (see https://community.contao.org/de/showthread.php?81431-Nach-Update-auf-4-9-18-bzw-19-Detailansicht-in-Dateiverwaltung-quot-File-not-found-quot).

**Comment by fritzmg** [comment]
I am assuming those that have a corresponding `tl_files` entry work while the ones that don't show "File not found".

**Comment by kikmedia** [comment]
As far as I can see: No. I've got a folder for which I get the error, and I've got files in this folder for which the information will be displayed. Both have complete entries in tl_files.

**Comment by berecont** [comment]
Just uploaded one *.jpg file in folder A and the result is OK,
the same *.jpg file in folder B and the result is 'File not found'.
both folder have the same rights, both folder have the same hierarchy in the folderstructur
(the file isn't in usage somewhere)

**Comment by fritzmg** [comment]
The problem are likely the changes from https://github.com/contao/contao/commit/dd0ad7b732aa8fbd0fb869aef94aad61a7102489#diff-ab3a6d8cdec727a667eb776b0b0547d1c6fa6f99e6e2a085ebde46fae97c9176, specifically the changes to `Input::stripTags`. The popup URL looks like this for example:

```
/contao/popup?src=ZmlsZXMvZHRzL0RlYXRodG9TdG9ja19NZXRpY3Vsb3VzLTAxLmpwZw==
```

But `Input::get('src', true)` then returns

```
ZmlsZXMvZHRzL0RlYXRodG9TdG9ja19NZXRpY3Vsb3VzLTAxLmpwZw&#61;&#61;
```

and thus the file cannot be found anymore. The `==` get converted to HTML entities in `Input::stripTags`, or more specifically `Input::stripAttributes`:

https://github.com/contao/contao/blob/a8802a0cc3225f8c51a4c77decf89220fbfcc15c/core-bundle/src/Resources/contao/library/Contao/Input.php#L567-L571

The `==` are matched by the regex in line 562 and subsequently this is detected as an empty HTML tag and thus they get converted to HTML entities.

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
@kikmedia can you verify if the changes from #3315 fix your issue?

**Comment by kikmedia** [comment]
Works for me. Excellent!

**Comment by andre5tz** [comment]
Works for me too an solves my problem in ce_hyperlink. 
Thanks.

**Comment by frontendschlampe** [comment]
I think, it's not working for `ce_html`

**Comment by fritzmg** [comment]
> I think, it's not working for `ce_html`

That's a different problem though, please create a new issue.
