### ISSUE TITLE
Add possibility to protect pages, article, modules etc. for members

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#331]
At the moment we have the possibility to protect nearly everything, but we have to select a member group, for which one the item should be protected. But I think, it would be great, if there's a possibility to protect an item for every logged-in member unattached his member group.

The problem: if you add a new member group, you have to go through all protected items and activate the new group otherwise the new group members don't see any protected content. Many items on a websites are just related to the status if the user is logged-in or a guest.

Examples:

- logout button
- status information
- Account information
and more

**Comment by asaage** [comment]
You could easily work around this by creating a group like ```known``` or ```logged-in``` and assign this group to every member by default (in addition to whatever other memberships you need) right?

**Comment by frontendschlampe** [comment]
> You could easily work around this by creating a group like `known` or `logged-in` and assign this group to every member by default (in addition to whatever other memberships you need) right?

You're right, this is a workaround. But a little bit more comfortable would be, if I could activate the protected-checkbox without checking a member group and the item is visible for every logged-in member. If a member group is checked, the item is visible just for the activated member group. :-)

**Comment by leofeyer** [comment]
Having a general group named "members" or "logged-in", to which all members are assigned by default, is the recommended best practice.

**Comment by leofeyer** [comment]
As discussed in Mumble on March 7th, we do not want to add such an option at the moment. You can solve the problem by adding a general group to which all members are assigned by default.
