### ISSUE TITLE
„xlink:href“ gets stripped by new allowed html attribute functionality

### ISSUE THREAD

**Issue by Shoekrates** [contao/contao#3312]
Tested in Contao 4.4.56 and Contao 4.9.18

In html modules or elements I use the svg „use“ tag with the attribute „xlink:href “ to reference an svg sprite I added to the html document globally. Somehow I can't get this attribute to get accepted. Maybe it's the colon in the attribute?

- If I don't add the attribute to the allowed list the only thing that remains when saving is &lt;use&gt;&lt;/use&gt;
- If I add the full attribute „xlink:href“ to the list of allowed attributes the only thing that remains when saving is &lt;use>&lt;/use>
- If I add the full attribute „xlink“ to the list of allowed attributes the only thing that remains when saving is &lt;use xlink=""&gt;&lt;/use&gt;

No {{iflng}} used, so it's not the fix for Contao 4.9.19.
How can we get this working again?

Edit: Added html entities to display html tags in issue

**Comment by ausi** [comment]
> Maybe it's the colon in the attribute?

Yes, that is the issue. We have to fix the attribute parsing for namespaced attributes.

**Comment by ausi** [comment]
@Shoekrates can you verify if the fix from #3314 works for you?

**Comment by Shoekrates** [comment]
@ausi Where do I find the file „core-bundle/tests/Contao/InputTest.php“? 
I don't have a tests-folder in /vendor/contao/core-bundle/ ?
Contao 4.9.19.

**Comment by ausi** [comment]
> Where do I find the file „core-bundle/tests/Contao/InputTest.php“?

You can ignore all changes from the _tests_ directory, only the changes in the _Input.php_ are relevant.

**Comment by Shoekrates** [comment]
The fix works in Contao 4.4.56 and 4.9.19. Saving doesn't strip the attributes now.
But you have to add the full attribute „xlink:href“ to the allowed attributes for the tag „use“ before.
