### ISSUE TITLE
various characters will be escaped after saving ce_html

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#3317]
**Affected version(s)**

Contao 4.9 or Contao 4.11

**Description**

We have a CE HTML with following content:

```html
<!-- JSON-LD -->
<script type='application/ld+json'>
		{
			"@context": "http://schema.org/",
			"@type": "Product",
			"brand": "XXX",
			"offers": {
				"@type": "Offer",
				"priceCurrency": "EUR",
				"price": "999",
				"itemCondition": "http://schema.org/NewCondition",
				"availability": "http://schema.org/InStock",
                                "url": "{{env::url}}/{{page::alias}}",
				"seller": {
				  "@type": "Organization",
				  "name": "XXX"
				}
			}
		}
</script>
```

After update to latest Contao 4.9 or 4.11 and safe or duplicate the CE HTML, the following content will appear:

```html
<!-- JSON-LD --&#62;
<script type="application/ld+json">
		{
			&#34;@context&#34;: &#34;http://schema.org/&#34;,
			&#34;@type&#34;: &#34;Product&#34;,
			&#34;brand&#34;: &#34;XXX&#34;,
			&#34;offers&#34;: {
				&#34;@type&#34;: &#34;Offer&#34;,
				&#34;priceCurrency&#34;: &#34;EUR&#34;,
				&#34;price&#34;: &#34;248.00&#34;,
				&#34;itemCondition&#34;: &#34;http://schema.org/NewCondition&#34;,
				&#34;availability&#34;: &#34;http://schema.org/InStock&#34;,
                                &#34;url&#34;: &#34;{{env::url}}/{{page::alias}}&#34;,
				&#34;seller&#34;: {
				  &#34;@type&#34;: &#34;Organization&#34;,
				  &#34;name&#34;: &#34;XXX&#34;
				}
			}
		}
</script>
```

That's a big problem! :-(

**Comment by ausi** [comment]
`<!-- JSON-LD -->` needs to be fixed, sorry for that one 😓

Allowing `<script>` is “unsafe” so for this use case you can fix your issue by allowing the attribute `*` for the element `*` (this should restore the old behavior).

**Comment by ausi** [comment]
@frontendschlampe can you verify if the fix from #3319 works for you?

**Comment by frontendschlampe** [comment]
> @frontendschlampe can you verify if the fix from #3319 works for you?

yes, it also fixes the encoded characters within `<script>` - I don't make any configuration in `allowedAttributes`

**Comment by ausi** [comment]
> I don't make any configuration in `allowedAttributes`

But then your `type='application/ld+json'` gets stripped, doesn’t it?

**Comment by frontendschlampe** [comment]
> But then your type='application/ld+json' gets stripped, doesn’t it?

yes, but I understand, that the encoding of `"` should be fixed with entry in `allowedAttributes`?! Maybe I misunderstood. With configuration for `<script>` in `allowedAttributes` everything works fine.
