### ISSUE TITLE
Revise the Contao components

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#332]
We should check which Contao components have become obsolete and remove or deprecate them.

## KEEP

| Component | Evaluation |
| --- | --- |
| **ace** | ACE editor used in the back end |
| **dropzone** | Drag and drop file uploads |
| **stylect** | Cross-browser select menu support |
| **tinymce4** | TinyMCE 4 – there is TinyMCE 5 meanwhile though |

## KEEP or REPLACE

| Component | Evaluation |
| --- | --- |
| **chosen** | Multi-select drop-downs; unmaintained but stable |
| **colorbox** | jQuery lightbox |
| **colorpicker** | Mostly used in the internal CSS editor; unmaintained |
| **datepicker** | Unmaintained but stable |
| **mediabox** | Lightbox for images and videos; unmaintained |
| **simplemodal** | Modal dialogues in the back end; unmaintained but stable |
| **swipe** | Used for the content element slider; unmaintained but stable |
| **tablesort** | MooTools table sorter |
| **tablesorter** | jQuery table sorter |

## REMOVE

| Component | Evaluation |
| --- | --- |
| **compass** | SASS compass integration; highly outdated |
| **highlight** | Highlight.js syntax highlighter; replaced with highlight.php |
| **html5shiv** | HTML5 elements shiv; no longer required |
| **mediaelement** | HTML5 audio/video player; no longer required |
| **respimage** | Responsive image shiv; no longer required |

**Comment by andyKempf** [comment]
Hi, Leo Feyer,
first of all many thanks for this great CMS!

My suggestion would be to implement all components with Vanilla JS to resolve the dependency on jQuery. More and more apps and websites do without jQuery to save resources and achieve more pagespeed. (Github also does without jQuery in the meantime)

Of course, it would still be possible to include jQuery for third-party plugins anyway.

Many greetings from Munich!

Translated with www.DeepL.com/Translator

**Comment by andyKempf** [comment]
Hi leofeyer,
first of all many thanks for this great CMS!

My suggestion would be to implement all components in the frontend (like accordion or colorbox) with Vanilla JS to resolve the dependency on jQuery. More and more apps and websites do without jQuery to save resources and achieve more pagespeed. (Github also does without jQuery in the meantime)

Of course, it would still be possible to include jQuery for third-party plugins anyway.

Good accessible vendor plugins are:
- Handorgel Accordion (https://github.com/oncode/handorgel)
- Glide JS Carousel (https://github.com/glidejs/glide)
- Luminous Image Gallery Modalbox (https://github.com/imgix/luminous)

Many greetings from Munich!

**Comment by leofeyer** [comment]
We are planning to integrate [PhotoSwipe](https://photoswipe.com/) in Contao 4.9, because it supports [responsive-images](https://photoswipe.com/documentation/responsive-images.html).

**Comment by leofeyer** [comment]
There is also an actively maintained tablesorter fork (see contao-components/tablesorter#1) if we should decide not to replace the two existing table sorters with a vanilla JS solution.

**Comment by fkaminski** [comment]
Is it possible to consider the fade-transition possibilities ( and more ) when replacing the swipe.js component in the future? For example like:
https://github.com/nolimits4web/swiper
http://idangero.us/swiper/demos/

**Comment by fritzmg** [comment]
> We are planning to integrate PhotoSwipe in Contao 4.9, because it supports responsive-images.

But that's only for images and does not support any other formats, right? (e.g. HTML via CSS ID, URL or AJAX; Videos, etc.)

**Comment by andyKempf** [comment]
Is it also planned to replace the accordion in the frontend with a vanilla solution? This would then resolve the dependency on jQuery a further step.

**Comment by andreheeke** [comment]
Due to the [announcement](https://www.tiny.cloud/blog/tinymce-4-support-window/) by the developers of the TinyMCE to stop developing version 4 by December 31, 2020, I suggest to upgrade directly to version 5 with the release of Contao 4.9. What do you think?

**Comment by Metis77** [comment]
As TinyMCE is one of the most often used tool while working / editing in Contao I would also suggest to use TinyMCE 5 right away for the upcoming Contao CTS 4.9.

Especially as TinyMCE comes with a fresh and modern look, that would further improve the look and feel of Contao.

**Comment by andreheeke** [comment]
I would offer to test if and which changes are needed for the TinyMCE version 5. We should especially keep an eye on the BC, because many developers will have changed the configuration.

**Comment by leofeyer** [comment]
@andreheeke Your help is much appreciated. 🍻

**Comment by may17** [comment]
As i mentioned in the slack channel today, @leofeyer successfully updated the tinymce!? Am i right? 

What ist the status for the other components?
