### ISSUE TITLE
Hide the captcha legend in the registration module

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3324]
**Affected version(s)**

Contao 4.12

**Description**

The captcha legend is still visible in the registration module with the `member_grouped` template:

<img width="645" alt="" src="https://user-images.githubusercontent.com/1192057/129678576-6ba556bf-8dc0-48b2-b514-25cc8b10e911.png">

**Comment by leofeyer** [comment]
This line is the problem:

https://github.com/contao/contao/blob/50079d9fe09ad802ca3bdde6d7ccac6b2338739d/core-bundle/src/Resources/contao/modules/ModuleRegistration.php#L354

It should be `?? null` instead of `?? $key` to remain backwards compatible.

**Comment by m-vo** [comment]
> It should be ?? null instead of ?? $key to remain backwards compatible.

I think I'd go with `?? ''` here as array keys cannot be `null`. This will currently get implicitly converted to `''` but I wouldn't be too surprised if this behavior will be changed to a warning in a 8.* release.
