### ISSUE TITLE
Dynamically add/remove the search tables

### ISSUE THREAD

**Issue by bytehead** [contao/contao#3326]
From https://github.com/contao/contao/pull/3283#issuecomment-899292222:
> Shouldn't we just not offer this option instead in the back end or automator CLI ?

Hide the "clear search index" task from the list when the indexer service is not available.

/cc @aschempp

**Comment by leofeyer** [comment]
As discussed in Mumble on August 26th, we want to drop the search tables if the indexer service is not available. Additionally, we want to add a `SearchSchemaProvider` class that creates the tables only if the indexer service is available.
