### ISSUE TITLE
Inactive member groups are listed on protecting elements

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#333]
**Tested version(s)**
4.6.14

**Description**  
When i want to protect certain elements, all existing member groups are shown. Even the inactive ones. This becomes pretty uncomfortable when you have many groups (in my scenario 48 - monthly growing)

I deactivated some groups from 2015 to 2018 but they are still shown on the list. Are they displayed intentionally?

Any solution to hide them?
 

Greetings Frank

**Comment by patrickjDE** [comment]
It makes sense, as they might only be temporarily disabled.

To improve usability a note indicating that the group is disabled could be added, additionally the sorting could be changed to group the disabled groups at the bottom of the list.

**Comment by leofeyer** [comment]
> It makes sense, as they might only be temporarily disabled.

I second this.

> the sorting could be changed to group the disabled groups at the bottom of the list

IMHO this would worsen the usability, because it would change the order of groups and force me to search then entire list every time I am looking for a certain group (in contrast to knowing that the group is always the third one from above).
