### ISSUE TITLE
Issues with deprecation

### ISSUE THREAD

**Issue by Toflar** [contao/contao#3334]
**Affected version(s)**

4.12, I guess

**Description**

So `PageModel::findPublishedSubpagesWithoutGuestsByPid()` is now deprecated in favor of `Module::getPublishedSubpagesWithoutGuestsByPid()` which was deprecated in favor of `Module::getPublishedSubpagesByPid()`, both of which are `protected`.
How am I supposed to use those now and why does this reside in `Module` now? I'm a bit confused :-)

**Comment by ausi** [comment]
> How am I supposed to use those now

Use `self::getPublishedSubpagesByPid()` if you are in a Module class and you need the `hasSubpages` flag.

Otherwise use `PageModel::findPublishedByPid()` I think.

> why does this reside in `Module` now?

Because it is used by `Module::renderNavigation` and does not make sense in the model I think.

**Comment by Toflar** [comment]
I have a custom content element that is written in the new fragment style so I do not extend from `Module`.

**Comment by ausi** [comment]
Can you use `PageModel::findPublishedByPid()`?

**Comment by Toflar** [comment]
I guess I could, yeah. I just need to check the permissions myself then.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 26th, we want to adjust the deprecations and say `Use PageModel::findPublishedByPid() and check the status yourself` instead of linking to the protected `Module::getPublishedSubpagesByPid()` method.
