### ISSUE TITLE
Language redirect does not consider browser preferences

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#334]
**Affected version(s)**

4.7.0

**Description**  

If I open the URL https://themes.contao.org/ I am redirected to `/en/` even though my preferred browser language is `de` and there is a `/de/` root page in the site structure.

Strange enough, this is not the case on contao.org. 🤔

**Comment by leofeyer** [comment]
Ah, the fallback language is `de` on contao.org and `en` on themes.contao.org .

**Comment by leofeyer** [comment]
I have adjusted the unit tests in 0838deda8567fd6bc99d8ef246aa5f2f4143a4c0 so the problem becomes visible.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/336

**Comment by leofeyer** [comment]
Thank you @aschempp.
