### ISSUE TITLE
Search indexer

### ISSUE THREAD

**Issue by xyzjuhe** [contao/contao#3344]
Contao 4.11.8.

Getestet auf neuer Installation ohne Erweiterungen. 
Beim Einfügen der indexer gibt es folgenden Fehler:
`
`
Das 1. indexer scheint nicht geschlossen zu werden. 
Im Beckend steht aber folgendes:

`<!-- indexer::stop -->`
Lorem Ipsum
`<!-- indexer::continue -->`

**Comment by fritzmg** [comment]
> Beim Einfügen der indexer gibt es folgenden Fehler:

I think you did not post the actual error?

**Comment by xyzjuhe** [comment]
Thx for your answer. Its the actual error.

**Comment by xyzjuhe** [comment]
I forgot the ` sign, sorry.

**Comment by fritzmg** [comment]
> `<!-- indexer::stop --&#62;`
> Lorem Ipsum
> `<!-- indexer::continue --&#62; --> `
> Das 1. indexer scheint nicht geschlossen zu werden.
> Im Beckend steht aber folgendes:

Ah yes, this is a known problem in Contao 4.9.19 and 4.11.8 and should be fixed with the next Contao version. Though I am curious: are these HTML comments that you entered yourself somewhere, e.g. an HTML content element or HTML frontend module? Or are the erroneous HTML comments coming from regular templates?

**Comment by ausi** [comment]
Duplicate of #3317

**Comment by xyzjuhe** [comment]
Thank you for your quick response. (I hadn't seen this bug reported yet.)

The problem occurs in a content element or module. I need this in the footer so that not every page is indexed.

Do you perhaps know until when the new Contao version will come, or is it not known?
Thank you for your help.

**Comment by ausi** [comment]
> Do you perhaps know until when the new Contao version will come, or is it not known?

Probably soon, but in the meantime you could install the version `4.11.x-dev` and report back here if our fix works for your use case.

**Comment by xyzjuhe** [comment]
With 4.11.x-dev appears: Your database server is not running in strict mode! 
I will now downgrade to an older version

**Comment by m-vo** [comment]
This warning in the install tool is intended if your server does not run in a strict SQL mode and has nothing to do with the original issue.

**Comment by xyzjuhe** [comment]
Thx for your answer m-vo
With x-dev the problem is fixed.
