### ISSUE TITLE
No way to create a custom ResizeConfiguration-Mode?

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#3347]
**Affected version(s)**

at leat Contao >= 4.9

**Description**

We needed a new resize mode because the traditional `crop`, `box` and `proportional` didn't work for us so we tried to implement our own (basically the equivalent of `background-size: contain`).

We looked at all the Picture- Image and Whatnot-Factories and got around to something that "works" - at least as long as we modify the image-bundle (see https://github.com/contao/image/blob/1.x/src/ResizeConfiguration.php):

```php
    /**
     * @param string $mode One of the ResizeConfiguration::MODE_* constants
     */
    public function setMode(string $mode): self
    {
        if (!\in_array($mode, [self::MODE_CROP, self::MODE_BOX, self::MODE_PROPORTIONAL], true)) {
            throw new InvalidArgumentException('Mode must be one of the '.self::class.'::MODE_* constants');
        }

        $this->mode = $mode;

        return $this;
    }
```

If we comment out the exception we can at least use our own mode on the `{{picture}}` insert tag (using a predefined image size).

Long story short: Not entirely understanding every aspect of the Image-/Picture-Factory vodoo we still came to the conclusion that, at this point in time, there is no way to properly implement a custom resizing mode that can be used on content elements, insert tags, predefined images sizes,.... because, on many occasions, the core just checks against that known list of core-modes.

Small side-rant: We needed at least 8 classes (with lots of copy'n'paste) to implement what is basically a simple image transformation that could be done in a couple of lines of code - there must be a more elegant way...

If I'm wrong I'd appreciate if someone would take their time to write a small example that could be added to the developer docs because surely there are other folks out there struggling with it.

**Comment by fritzmg** [comment]
> We needed a new resize mode because the traditional `crop`, `box` and `proportional` didn't work for us so we tried to implement our own (basically the equivalent of `background-size: contain`).

The equivalent of `background-size: contain` is already the `box` mode. What would your mode do differently?

**Comment by bennyborn** [comment]
> The equivalent of `background-size: contain` is already the `box` mode. What would your mode do differently?

Not quite. 

`box` seems to generate an image with fixed dimensions and copies the src image into it without altering its size. Our mode resizes the src to the exact width and crops it in it's height.

We also added a second mode which uses fixed dimensions fits the image in there (shrinks it along its longest side) and keeps the whitespace around it - something the core does not provide.

**Comment by fritzmg** [comment]
> `box` seems to generate an image with fixed dimensions and copies the src image into it without altering its size

Not sure what you mean. If your image size is `100x100` with `box` mode, then an image that is for example `1280x720` will be scaled to `100x56`. If the source image size is `720x1280`, it will be scaled to `56x100`.

**Comment by fritzmg** [comment]
> Our mode resizes the src to the exact width and crops it in it's height.

Ah, but that's `background-size: cover` ;). And that's just `crop`.

**Comment by bennyborn** [comment]
Can we just assume we did something different for the sake of the topic? 😋

**Comment by ausi** [comment]
This should be possible by decorating the image and picture factory services I think.

**Comment by michb** [comment]
> This should be possible by decorating the image and picture factory services I think.

That's what we did and like @bennyborn said it kind of works. But for example if we use an inserttag a resize configuratiion is created and throws an exception, like mentioned in the first post.
So technically we decorated the service, but we cannot use it fully in combination with contao, eg inserttag.

**Comment by ausi** [comment]
> But for example if we use an inserttag a resize configuratiion is created and throws an exception

Unable to reproduce. 
The following worked fine in my test with the insert tag `{{picture::files/img/image.jpg?size=my_size}}`

```yaml
# config/services.yaml
services:
  App\Image\PictureFactory:
    decorates: contao.image.picture_factory
    arguments:
      - '@App\Image\PictureFactory.inner'
```

```php
<?php
// src/Image/PictureFactory.php

namespace App\Image;

use Contao\CoreBundle\Image\PictureFactoryInterface;
use Contao\Image\ResizeConfiguration;

class PictureFactory implements PictureFactoryInterface
{
    /**
     * @var PictureFactoryInterface
     */
    private $inner;

    public function __construct(PictureFactoryInterface $inner)
    {
        $this->inner = $inner;
    }

    public function setDefaultDensities($densities)
    {
        return $this->inner->setDefaultDensities($densities);
    }

    public function create($path, $size = null)
    {
        if ($size === 'my_size') {
            $picture = $this->inner->create($path, [100, 100, ResizeConfiguration::MODE_CROP]);
            // Do something custom with $picture
            return $picture;
        }

        return $this->inner->create($path, $size);
    }
}
```

**Comment by bennyborn** [comment]
@ausi That seems a bit too simplistic as you do not create a custom mode rather than just re-using `MODE_CROP`. 

As far as we understood to do it the "proper" way we need at least our own `ResizeConfiguration`, `ResizeCalculator` and of course add our mode(s) as options in `dca/tl_image_size_item.php` and `dca/tl_image_size.php` which leads to throwing the aforementioned exception.

**Comment by fritzmg** [comment]
I think adding your own modes is not supported. But you should not really need it anyway. As described above, your use cases can already be covered with the existing modes.

**Comment by bennyborn** [comment]
> I think adding your own modes is not supported.

Totally fine if that's the case (at least for now). Can we get a confirmation on this by any other core dev just to be sure?

> But you should not really need it anyway. As described above, your use cases can already be covered with the existing modes.

The first mode yes, the second mode (exact size, fitted into box, keeping whitespace) not.

**Comment by fritzmg** [comment]
> The first mode yes, the second mode (exact size, fitted into box, keeping whitespace) not.

But you can implement that with the existing modes …

**Comment by ausi** [comment]
> > I think adding your own modes is not supported.
> 
> Totatlly fine if that's the case. Can we get a confirmation on this by any other core dev just to be sure?

There is no explicit extension point to add your own resize mode. And I think it would be very hard to create a generalized way for this.

> The first mode yes, the second mode (exact size, fitted into box, keeping whitespace) not.

This should be possible with my code example from above. You rewrite your own mode to `box`, then call the original service and after the image was resized you add the “whitespace” to the image in your decorated class.

**Comment by bennyborn** [comment]
We'll try how far we can get using @ausi's example and get back to you. 
We definitely need a way to make the mode/size selectable from within the backend.

**Comment by fritzmg** [comment]
> We definitely need a way to make the mode/size selectable from within the backend.

That you can still do. Your service would then intercept your custom mode and generate the image accordingly (using the pre-existing modes as described above).

**Comment by ausi** [comment]
You probably need to copy some code from the picture factory that reads the sizes from the database, the configuration or the passed sizes array, in order to be able to handle every possible use of resize modes.

Regarding the *exact size, fitted into box, keeping whitespace* requirement: did you check if you could use a CSS solution (in combination with mode `box`) as an alternative?

```
<img
	src="…"
	srcset="…"
	style="width: 100px; height: 100px; object-fit: contain; background: #fff;"
>
```

Your decorated picture factory could dynamically add the `style` attribute for example.

**Comment by bennyborn** [comment]
> You probably need to copy some code from the picture factory that reads the sizes from the database, the configuration or the passed sizes array, in order to be able to handle every possible use of resize modes.

Yap, already did this in our current approach.

> Regarding the _exact size, fitted into box, keeping whitespace_ requirement: did you check if you could use a CSS solution (in combination with mode `box`) as an alternative?

I'm all for CSS whenever it's possible but unfortunately there are situations where you really just need a generated image that fits.

**Comment by bennyborn** [comment]
> ```php
>      $picture = $this->inner->create($path, [100, 100, ResizeConfiguration::MODE_CROP]);
>      // Do something custom with $picture
> ```

@ausi You wrote `Do something custom with $picture` - it seems that is not the right place to do something. `$picture` is an instance of `Contao\Image\Picture` so all the image processing and caching is already done. What we would want is to intersect where the image has already been resized and about to be cached. It seems `Contao\Image\ResizeOptions::processResize` would be the place to go.

Decorating `contao.image.resizer` would be possible but it seems we then would have to re-implement everything that is already done by the core.

Any ideas?

**Comment by ausi** [comment]
> `$picture` is an instance of `Contao\Image\Picture` so all the image processing and caching is already done.

I would probably add the “whitespace” after this step for every image resource that was created.

How about extending `Contao\Image\ResizeConfiguration`, replace the `$size` in the picture factory with an instance of it (if the `$size` uses your mode) and pass that to the parent?

In your resizer decoration you could then check for your own `ResizeConfiguration` and handle your custom logic there.

**Comment by bennyborn** [comment]
> > `$picture` is an instance of `Contao\Image\Picture` so all the image processing and caching is already done.
> 
> I would probably add the “whitespace” after this step for every image resource that was created.

I don't think this would work because the `create` method of the `PictureFactory` gets called on every request. I would then need a way to determine if the image returned by `create`, which might already come from the cache, was already altered by our method.


> How about extending `Contao\Image\ResizeConfiguration`, replace the `$size` in the picture factory with an instance of it (if the `$size` uses your mode) and pass that to the parent?
> 
> In your resizer decoration you could then check for your own `ResizeConfiguration` and handle your custom logic there.

We tried using `Contao\Image\ResizeOptions` and adding a custom property to determine within the Resizer if it's our call or not but that still leaves us with the problem that our decorated Resizer would need to do all the heavy lifting that is already done by the core.

If it helps to make my point a bit more clear don't think about acutally fiddling with the image dimensions rather than just giving it a blue tint, adding a unicron on top or something like that 😂

**Comment by ausi** [comment]
> If it helps to make my point a bit more clear don't think about acutally fiddling with the image dimensions rather than just giving it a blue tint, adding a unicron on top or something like that 😂

That would need for the internals of the resizer to change as it currently makes many assumptions about what cache image it can reuse and when it is possible to skip resizing altogether. This would all break in your blue tint or unicorn case.

I think to meet your needs we would need an extension point for `Resizer::canSkipResize()`, `Resizer::createCachePath()`, `executeResize()` before the call to `$imagineImage->resize()` and `executeResize()` before `$imagineImage->save()`. That seems pretty complex to me 😕

**Comment by bennyborn** [comment]
> [...] That seems pretty complex to me 😕

And that's exactly where we ended up with a bunch of copy'n'pasted core-core which only works to certain extends.

Well I guess the initial question is answered then.

**Comment by leofeyer** [comment]
Can this issue be closed then?

**Comment by bennyborn** [comment]
I guess so...
