### ISSUE TITLE
Form redirects to "Redirect page" although email could not be sent

### ISSUE THREAD

**Issue by j-schroeder-schetelig** [contao/contao#335]
**Affected version(s)** 
Version 4.6.14 and possibly older

**Description**  
I am currently struggling to setup Contao that emails are sent correctly by a test form.
However I noticed the following bug.
Upon submission of the test form (with all data fields entered correctly) the visitor will be redirected to the page selected under "Redirect page", although the email could not be sent by the system.
The System Log shows entries such as
  Form "Test-Formular" could not be sent: Connection could not be established with host ...
or
  Form "Test-Formular" could not be sent: Expected response code 220 but got an empty response
but the visitor will just see whatever is written on the "Redirect page", but no error message is informing them that something went wrong and the data could not be sent.

**How to reproduce**  
The form settings are set to:
[x] Send form data via e-mail
Recipient address*: some-valid.email@address.de
Subject*: Test-Formular Daten
Data format: Raw data
[ ] Skip empty fields
[ ] Store data

**Sidenote**
I could be wrong, but as I understand it, the Redirect page is supposed to display a text element with message of the kind "Thank you for your request. An email has been sent."
Or is there a way to include an module or something that displays an success/fail message?

**Comment by asaage** [comment]
Either sendmail is not available https://github.com/contao/core-bundle/issues/1613
or something else is wrong with your mailer configuration.
I guess we really need the Test-Mail Feature in the contao-manager https://github.com/contao/contao-manager/issues/254

The Redirect-page will be triggered as soon as the form has successfully been submitted - it doesn't  care about successfull delivery of e-mail.
It could be stored to db or processed by notification-center or a processFormData Hook which might take some time.

added: ([smtp config](https://contao.ninja/smtp-einstellungen.html))

**Comment by j-schroeder-schetelig** [comment]
Thanks for the information. I didn't know about notification-center or hooks.
But, the bug that I still see here, is that the user should be informed that their data was lost in nirvana, when the only configured method of delivery is email.
And what happens in the other cases, i.e. if the form is set up to only store data in a db, but there is an error? Will the user be informed?

Maybe the redirection page could contain some kind of module that is showing a progress message that gets updated via ajax? Then it should show configurable success/error messages:
"Thank you. Your data has been submitted/stored."
"An error has occured. The data could not be submitted/stored. Please try again later, or send an e-mail to ...".

Btw, I solved my problem with email sending by configuring smtp in app/config/parameter.yml and rebuilding cache.

**Comment by fritzmg** [comment]
I agree that any failure of processing the form data, be it saving it to the database, sending an email or any failure caused in hooks, should not show the success page.

**Comment by leofeyer** [comment]
I am not sure of what is the best way to fix this. We are currently catching Swift errors here:

https://github.com/contao/contao/blob/46180e9238288a3e6ed6cda5b0d9c4ba1ae74d79/core-bundle/src/Resources/contao/forms/Form.php#L450-L457

We could remove the try-catch block so the exception is thrown. Or we could keep catching the exceptions and show an error message above the form. However, the latter might lead users to think that there is something they have to fix in order to send the form.

**Comment by fritzmg** [comment]
I would treat it the same way as storing the data in the database: if the target table does not exist, or a field does not exist, or the database connection is somehow lost, then an error would be thrown.

if we instead show an error in the front end form for any email related errors, then we should do the same with database related errors as well. But I am not really for that.

**Comment by leofeyer** [comment]
As discussed in Mumble on June 6th, we want to remove the try-catch block, so the request ends in an error 500.

**Comment by kroerig** [comment]
What is the actual state? Will it be working in 4.9?
For me it is realy important that users get to know if the form was submitted successfully or if something went wrong.

**Comment by fritzmg** [comment]
Since it is labelled as a defect, it will probably be integrated into one of the next bug fix versions of Contao 4.4 and 4.8.

**Comment by leofeyer** [comment]
See #1017
