### ISSUE TITLE
Cannot disable debug output for templates anymore

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3351]
**Affected version(s)**

Contao 4.12

**Description**

In https://github.com/contao/contao/commit/4e0c1204af9f39f203eb691f4fd0946e3bdc4833 `TemplateInheritance::inherit` was changed, so that it uses `kernel.debug` instead of `Config::get('debugMode')`. However, as noticed via https://github.com/contao/contao/issues/3349, this now makes it impossible to dynamically disable the debug output when parsing a template.

This will certainly break a lot of extensions in the `dev` environment that rely on this functionality.

**Comment by fritzmg** [comment]
As a workaround you could now use

```php
$content = preg_replace('/<!--(.|\s)*?-->/', '', $template->parse());
```

Though this would strip _all_ HTML comments, not just the template path debug comments.

Imho it would be convenient to be able to specifically enable or disable the debug comments. e.g.:

```php
$content = $template
    ->debug(false)
    ->parse()
;
```

And if `debug()` is not set, `kernel.debug` gets used as the fallback decision factor.

Though either way it would be a BC break and extensions would have to adjust their implementations.

**Comment by aschempp** [comment]
Why would you want to dynamically disable the debug mode?

**Comment by ausi** [comment]
> Why would you want to dynamically disable the debug mode?

Because you want to parse a template and don’t want the debug comments to show up?

**Comment by fritzmg** [comment]
> Why would you want to dynamically disable the debug mode?

To disable the template path HTML comments.

For example they could interfere with whatever you need the parsed template content for. We use Contao templates in order to generate HTML for mPDF - but mPDF does not like HTML comments occurring before `<!DOCTYPE html>` for example and thus we dynamically disable it.

Some more examples where the `debugMode` is dynamically disabled for the template output:

* https://github.com/isotope/core/blob/7f96e87359994a1d82050618d3004f7004d323e7/system/modules/isotope/group.php#L124-L125
* https://github.com/contao/contao/blob/5fdcb347db6e2f18e999ee5e673c7d0c916bcee9/core-bundle/src/Resources/contao/dca/tl_templates.php#L484
* https://github.com/pbd-kn/contao-efg-bundle/blob/master/src/EventListener/DisableDebugModeForInternalTemplatesListener.php

**Comment by bytehead** [comment]
> For example they could interfere with whatever you need the parsed template content for. We use Contao templates in order to generate HTML for mPDF - but mPDF does not like HTML comments occurring before <!DOCTYPE html> for example and thus we dynamically disable it.

But when do you use this in debug mode (except during development)? 🤔

**Comment by fritzmg** [comment]
> But when do you use this in debug mode (except during development)? 🤔

Exactly during development ;). If I weren't able to remove the comments, I could not test and debug the functionality in the `dev` environment. The application should not suddenly break, just because you enabled `APP_ENV=dev` or clicked on _Debug-Mode_ in the Contao back end.

**Comment by ausi** [comment]
If we want to fix BC we have to go back to check for `Config::get('debugMode')`, add `$template->debug(false)` as an alternative and deprecate `Config::set('debugMode',…)`, right?

**Comment by fritzmg** [comment]
> and deprecate `Config::set('debugMode',…)`, right?

It is already deprecated, but I assume you mean deprecate it separately from all the other deprecated config values with a separate deprecation message. I would say yes. Whether or not `$template->debug(false)` is the right way, idk. May be there could also be a non-frozen parameter bag that could control this 🤷. But using `$template->debug(false)` is certainly the most convenient way for the given use cases.

**Comment by ausi** [comment]
Apart from controlling the template output, do you know of any other use cases that use `Config::set('debugMode',…)` that we should provide an alternative for?

**Comment by fritzmg** [comment]
In Contao 4.9 you can also control via `debugMode` whether the `Combiner` should actually combine the assets or not. Or whether the HTML gets minified or not. Among other things. Though I personally never used it for that.

Isotope also disables the `debugMode` in its `Upgrade` class, but I am not sure why (@aschempp ? 😉).

**Comment by ausi** [comment]
I will provide a pull request with the approach outlined in https://github.com/contao/contao/issues/3351#issuecomment-902553157
