### ISSUE TITLE
Field "image.url" missing

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3355]
**Affected version(s)**

Contao 4.12

**Description**

According to the Google Search Console, we are supposed to use `image.url` instead of `image.contentUrl` in the schema.org data of an event.

<img width="416" alt="" src="https://user-images.githubusercontent.com/1192057/130246918-a1d2d770-1a00-4cf3-93d2-f2effac31872.png">

<img width="342" alt="" src="https://user-images.githubusercontent.com/1192057/130246427-c4af57f6-45ed-47ea-bb0d-b6308d821de5.png">

This is the current JSON+LD:

```
{
    "@id": "#\/schema\/events\/329",
    "@type": "Event",
    "description": "…",
    "image": {
        "@id": "#\/schema\/image\/9e2f1769-bc3d-11e4-a94b-50e54942181a",
        "@type": "ImageObject",
        "contentUrl": "files\/events\/2015\/contao_konferenz_logo2015.png"
    },
    "location": {
        "@type": "Place",
        "name": "Seminaris Hotel Bad Honnef, Alexander-von-Humboldt-Straße 20, 53604 Bad Honnef"
    },
    "name": "Contao Konferenz 2016",
    "startDate": "2016-05-19",
    "url": "de\/veranstaltungen\/contao-konferenz-2016.html"
}
```

**Comment by Toflar** [comment]
In the examples on https://schema.org/ImageObject they always use `contentUrl`. But I don't see any difference between `url` and `contentUrl` and they are both allowed. So maybe we should provide both?

**Comment by leofeyer** [comment]
@ausi WDYT?

**Comment by ausi** [comment]
Unable to reproduce 
![Screenshot 2021-08-24 at 11-02-04 Schema Markup Validator](https://user-images.githubusercontent.com/367169/130588916-cbeaf5c3-d421-4bf9-a85f-5d320c3f10dd.png)

Probably an error in the Google Search Console?

**Comment by leofeyer** [comment]
Probably. Yet another one. 😄 Thanks for checking.
