### ISSUE TITLE
Contao Managed Edition: Release Tag for Contao 4.12

### ISSUE THREAD

**Issue by xchs** [contao/contao#3358]
Could we have a release tag for Contao 4.12 in the [contao/managed-edition](https://github.com/contao/managed-edition) split repository so that the Contao Managed Edition can also be[ installed on command line](https://docs.contao.org/manual/de/installation/contao-installieren/#contao-ueber-die-kommandozeile-installieren)?

**Comment by leofeyer** [comment]
Done.
