### ISSUE TITLE
Issues with switching to public as the default web root

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3363]
**Affected version(s)**

Contao 4.12?

**Description**

Detecting the use of `web` as public directory by checking if the resource exists on the filesystem might lead to unwanted behavior, see https://github.com/contao/contao/pull/3084#issuecomment-903163906.

I noticed the problem when creating a new project from a template/skeleton (now with 4.12): 

* the project assumes `web` as the web root
* `web`, however, does not exist initially &rarr; `public` gets created on install
* webpack is run and outputs stuff into the now created `web` directory
* the symfony server is started and picks up `public` as the web root
* the cache is cleared after some work, now `web` exists and things break<sup>*)</sup>

<sup>*)</sup> because the `contao.web_dir` config setting now differs from the actual web root

The same thing will happen when deploying by copying a bare minimum and installing, i.e. without explicitly creating the web directory. There the website will stop working as no entry points will be at the expected location.

IMHO we should neither rely on the existence nor absence of the web directory but only on the config. I've also seen projects using `web` as their js/layout root. :see_no_evil: 

What about this strategy instead?

- use `extra.public-dir` in the app's `composer.json` to set the public dir [like Symfony does](https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-public-directory)
- default config to `web` unless configured otherwise via `composer.json` (or config)
- ship the switch to `public` via the 4.12 managed edition `composer.json`, so that only new projects are affected

We could then ultimately change the default in Contao 5 and remove the `composer.json` config key again (as a BC break).

**Comment by leofeyer** [comment]
I don't think we should do any of this. Keep in mind that the logic only applies to the default value, therefore all of the problems mentioned above can be solved by adding `contao.web_dir` to your `config.yml` file.

**Comment by m-vo** [comment]
So if I'm installing Contao in a Symfony environment where I set my web root via the `composer.json` I need to add a config entry. Same if I am using a new 4.12 with `public` and later on I'll add a `web` folder - not knowing this would do any harm. I don't like that magic at all.

**Comment by m-vo** [comment]
related #3370

**Comment by leofeyer** [comment]
> So if I'm installing Contao in a Symfony environment where I set my web root via the `composer.json` I need to add a config entry. 

Yes. We have decided against using `extra.public-dir` from the `composer.json` file, which is why we have added a separate `contao.web_dir` parameter in the first place. I don't recall the exact reasons but I think it was because there is no way to add custom settings to the `composer.json` file yet.

> Same if I am using a new 4.12 with `public` and later on I'll add a `web` folder - not knowing this would do any harm. I don't like that magic at all.

That is indeed something that we could reconsider, although I don't think many users will run into the issue. Any ideas how to improve it?

**Comment by m-vo** [comment]
> Yes. We have decided against using extra.public-dir from the composer.json file, which is why we have added a separate contao.web_dir parameter in the first place. I don't recall the exact reasons but I think it was because there is no way to add custom settings to the composer.json file yet.

It wouldn't do any harm to support it now, would it? I'd read it once when parsing the config and only use the value if `extra.public-dir` is set and `contao.web_dir` is not set.

> Any ideas how to improve it?

Only trust the config key: the usage would then be consistent at least and would be easier to debug. The auto-detection could still be in there when parsing the config value.

But like I said, I wouldn't try to detect folders at all. :see_no_evil:

**Comment by aschempp** [comment]
https://github.com/contao/contao/pull/3084#issuecomment-861176746 🤷

**Comment by leofeyer** [comment]
As discussed in the Contao call on September 30th, we want to set `contao.web_dir` from `extra.public-dir` in the composer.json file and deprecate the parameter in the configuration tree.

**Comment by m-vo** [comment]
see #3535
