### ISSUE TITLE
Add warning in system log for {{link_url::back}}

### ISSUE THREAD

**Issue by ausi** [contao/contao#3364]
`{{link_url::back}}` doesn’t work anymore as it gets encoded as `javascript%3Ahistory.go(-1)`, we should probably add a warning to the system log if it gets used somewhere.

**Comment by fritzmg** [comment]
Is there really no way to get this working again? What would be the alternative?

**Comment by m-vo** [comment]
Since it relies on js anyway, an easy way around would be to just output a link with a certain attribute and a global piece of code that adds the functionality. 

Something like this:
```js
document.querySelectorAll('[data-link-back']).forEach(el => el.addEventListener('click', history.go(-1)));
```

**Comment by fritzmg** [comment]
In Contao you can enter `{{link_url::back}}` in any URL field (news, events, content elements for example). Typically it is used in the `ce_hyperlink` element for example. Should we then offer a migration that would at least automatically provide this alternative for these elements?

**Comment by ausi** [comment]
> Is there really no way to get this working again?

We could add a check to https://github.com/contao/contao/blob/f1b3c56856666c38fe080fd04e00797b8fbed310/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L1344 if the whole attribute matches exactly `"{{link_url::back|urlattr}}"` (including the quotes) and replace it with `"{{link_url::back}}"` in that case.

But I don’t really like that and I would at least deprecate it then.

**Comment by netzarbeiter** [comment]
In my eyes this is a bc break. We can't remove an insert tag in a bugfix version for whatever reason.

**Comment by m-vo** [comment]
> In my eyes this is a bc break. We can't remove an insert tag in a bugfix version for whatever reason.

Keep in mind, that if it's for security reasons, BC breaks might be a necessity.
