### ISSUE TITLE
Event endtime will not be saved

### ISSUE THREAD

**Issue by matuweb** [contao/contao#3376]
**Affected version(s)**

Contao 4.9 
<img width="1175" alt="Bildschirmfoto 2021-08-24 um 11 12 00" src="https://user-images.githubusercontent.com/13745042/130595807-95e5eeb7-7516-4629-b7eb-f3edfac53596.png">

**Description**

I found a bug in the events module (backend). If you set the time for "Date and Time" for a new or existing entry to 01:00 (end time), this time will not be saved. Any other value (01:01, 02:00, etc.) works correctly. I've tested many combinations in different systems (times, start and end dates, etc.).

**Comment by Toflar** [comment]
Can confirm.

**Comment by leofeyer** [comment]
Could it be this issue? https://github.com/contao/core/issues/7364

**Comment by Toflar** [comment]
I reproduced it in the online demo btw.

**Comment by Total-Reality** [comment]
Can you hotfix it please?

I tried to change this line:

https://github.com/contao/calendar-bundle/blob/4.x/src/Resources/contao/dca/tl_calendar_events.php#L991

`$arrSet['endTime'] = strtotime(date('Y-m-d', $arrSet['endTime']) . ' ' . date('H:i:s', $dc->activeRecord->endTime ?: $dc->activeRecord->startTime));`

To:
`$arrSet['endTime'] = strtotime(date('Y-m-d', $arrSet['endTime']) . ' ' . date('H:i:s', $dc->activeRecord->endTime != -3600 ?: $dc->activeRecord->startTime));`

I don't think it is the best solution, but it works.

**Comment by fritzmg** [comment]
@Total-Reality @matuweb please try the following fix: #3454

You will need to re-save the affected event.
