### ISSUE TITLE
Storage behaviour changed since Contao 4.9.17

### ISSUE THREAD

**Issue by cboelter** [contao/contao#3381]
**Affected version(s)**

Contao 4.9.18 and following

**Description**

```php
Array ( [inputType] => text [eval] => Array ( [mandatory] => 1 [tl_class] => w50 ) [sql] => text NOT NULL ) 
```

In Contao 4.9.17 this Configuration in an datacontainer produces the following result in the database:
![Bildschirmfoto 2021-08-24 um 18 48 04](https://user-images.githubusercontent.com/550207/130658837-89df5cb8-bd70-4d41-9443-a8d87c0b5621.png)

Since Contao 4.9.18 the same configuration produces the following result:
![Bildschirmfoto 2021-08-24 um 18 51 46](https://user-images.githubusercontent.com/550207/130658973-c4a4447b-ceda-4d6f-9dff-bed9373dcd37.png)

I could fix it by adding the ```decodeEntities => true ```but I'm not sure that the new behaviour is the right one.
So it would be nice to have a hint what is the right way to fix the problem or that this is a bug :-)

**Comment by fritzmg** [comment]
You need to update to Contao 4.9.20 and then save the item again.

**Comment by cboelter** [comment]
Forgot that, I have tried it with the 4.9.20 and the 4.9.x-dev, same result :-( only adding the decodeEntities fixed it.

**Comment by ausi** [comment]
> So it would be nice to have a hint what is the right way to fix the problem or that this is a bug :-)

That depends on your usage. Converting the `'` character for HTML contexts is correct and was added in a recent version.

It seems that the value you are storing is used in a CSS context, using `'decodeEntities' => true` is the correct way for that. But you should encode the string properly when adding it to your CSS code (especially if the input comes from an untrusted user).
