### ISSUE TITLE
Missing redirects in legacy routing mode with empty URL suffix

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3382]
**Affected version(s)**

Contao 4.11, 4.12

**Description**

If you configured `contao.prepend_locale = true` and `contao.url_suffix = ''` under Contao 4.9, the following redirects would happen:

| Initial URL | `Location` response header | Result |
| --- | --- | --- |
| `example.com/de` | `example.com/de/` | Shows `index` page of `de` website tree. |
| `example.com/exists` | `example.com/en/exists` | Shows `exists` page of `en` website tree. |
| `example.com/does-not-exist` | `example.com/xx/does-not-exist` | Shows `404` page of the respective website tree (depending on `Accept-Language`). |

However, under Contao 4.11.9, 4.12 with legay routing _not_ disabled the following happens:

| Initial URL | `Location` response header | Result |
| --- | --- | --- |
| `example.com/de` | - | Shows Symfony `404` page. |
| `exapmle.com/exists` | `example.com/en/exists` | Shows `exists` page of `en` website tree. |
| `example.com/does-not-exist` | - | Shows Symfony `404` page. |

At least the non-trailing slash language URL not redirecting (and showing the Symfony `404` page instead) should not be happening with `legacy_routing` enabled.

With `contao.legacy_routing = false` the following happens under Contao 4.12:

| Initial URL | `Location` response header | Result |
| --- | --- | --- |
| `example.com/de` | `example.com/de/` | Shows `index` page of `de` website tree. |
| `exapmle.com/exists` | `example.com/en/exists` | Shows `exists` page of `en` website tree. |
| `example.com/does-not-exist` | - | Shows Symfony `404` page. |

The latter redirect not happening is intended, iirc?

/cc @aschempp

**Comment by leofeyer** [comment]
* The missing `example.com/de` → `example.com/de/` redirect with legacy routing enabled is wrong IMHO.
* The `example.com/does-not-exist` → `example.com/xx/does-not-exist` redirect has been dropped intentionally IIRC.
* The request `example.com/does-not-exist` not being redirected is correct and intended.

**Comment by jxns** [comment]
> The example.com/does-not-exist → example.com/xx/does-not-exist redirect has been dropped intentionally IIRC.
The request example.com/does-not-exist not being redirected is correct and intended.

Is there a particular reason for this? I think it is very inconvenient that there is no redirect in this case.

**Comment by leofeyer** [comment]
Because `example.com/does-not-exist` is a valid URL if the URL suffix is empty and invalid (404) if the URL suffix is `/`. Likewise, `example.com/does-not-exist/` is a valid URL if the URL suffix is `/` and invalid if the URL suffix is empty.

**Comment by jxns** [comment]
But is this:

> The example.com/does-not-exist → example.com/xx/does-not-exist redirect has been dropped intentionally IIRC.

configurable?
Because I have two different installations (both running on 4.11.8). One installation where the redirect is working and one installation where I get an 404 response instead.

**Comment by leofeyer** [comment]
@aschempp /cc

**Comment by ausi** [comment]
> One installation where the redirect is working

By working you mean you get a redirect to `example.com/xx/does-not-exist` that still results in a 404 page, right?

**Comment by jxns** [comment]
> By working you mean you get a redirect to example.com/xx/does-not-exist that still results in a 404 page, right?

I get a successful redirect from `example.com/does-not-exist` to `example.com/xx/does-not-exist`.
("does-not-exist" is a valid and existing subpage. Just to avoid any misunderstandings).

**Comment by fritzmg** [comment]
In my examples `does-not-exist` is representative of page aliases that do not exist in the site structure. I have not tested the case for ones that do.

// I have added an `exists` example. Note however, that in my testing a page with the alias `exists` exists in all website roots.

**Comment by asaage** [comment]
again and again issues with empty suffix and folder urls...
https://github.com/contao/contao/issues/2775
https://github.com/contao/contao/issues/2812
now with prepend_locale in the mix 😵

**Comment by fritzmg** [comment]
The redirect from `example.com/de` to `example.com/de/` in Contao 4.12 does indeed work, if the `contao.url_suffix` is non-empty.

**Comment by jxns** [comment]
In my case, `example.com/exists` still does not redirect to `example.com/de/exists`.
Where you able to reproduce this as well?

**Comment by fritzmg** [comment]
No, I was not able to reproduce that. How many website roots and for which languages do you have, and in which website roots does a page with the alias `exists` exist? And what is the `Accept-Language` of your browser?

**Comment by jxns** [comment]
I have two website roots. One for `de` and one for `en`. 
My Accept-Language is:
`accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7`
The direct is not working on only one of my pages. It is working on other Contao installations (all running on 4.11.8)

**Comment by fritzmg** [comment]
> The direct is not working on only one of my pages. It is working on other Contao installations (all running on 4.11.8)

Is this page present with the same alias in both roots?

**Comment by jxns** [comment]
Yes, the page is present in both languages with the same alias.

**Comment by fritzmg** [comment]
The fact that it is not working seems specific to your Contao instance then may be. I cannot reproduce this.

**Comment by aschempp** [comment]
@fritzmg would you be able to create some failing functional tests for the explained use cases?

**Comment by jxns** [comment]
@fritzmg So what could cause this error? What would you suggest on how to troubleshoot?

**Comment by asaage** [comment]
> The fact that it is not working seems specific to your Contao instance then may be. I cannot reproduce this.

It might be worth to investigate if apache vs nginx have different behaviour in regards of trailing slashes. At least that was what i was encountering some years ago. May be it's just a webserver-config thing.

**Comment by jxns** [comment]
> In my case, example.com/exists still does not redirect to example.com/de/exists.

Okay, I have found at least two of my contao installations, where this occurs. What could cause this behaviour?

**Comment by leofeyer** [comment]
@fritzmg Does the issue occur in Contao 4.13, too? If so, please reassign the milestone.

**Comment by jxns** [comment]
The issue seems to be solved in 4.13. Thank you :-)
