### ISSUE TITLE
Contao 4.4.57 - Featured Star Klick in Listview (Backend) reports an 500er and Value doesn't get stored in the Database

### ISSUE THREAD

**Issue by MacKP** [contao/contao#3389]
**Affected version(s)**
Contao 4.4.57 after the latest patch

**Description**
If I click on the Featured Star in the Backend, i get an Post Error in the Console and after reloading the page the Star isn't changed anymore. In two Installations the Value isn't saved in the Database. In one installation the Value is saved and if i reload the Star is in the State you would expect.

I think this is an issue we have since the last security-patches.

Kind regards

**Comment by fritzmg** [comment]
Are you sure? I think this bug has been around before that.

**Comment by MacKP** [comment]
Ah, i found it in Ticket #2574
It's already in C 4.4.55...

**Comment by aschempp** [comment]
Looks like this has been fixes in Contao 4.9, but Contao 4.4 will not get bugfixes anymore (except for the ones introduced through the security update).

**Comment by MacKP** [comment]
Jep nevermind.. i thought this was introduced with the security update.. sorry for that.
