### ISSUE TITLE
Login Page Title starts with "-"

### ISSUE THREAD

**Issue by wiphi** [contao/contao#339]
**Affected version(s)**
Contao 4.7
[Ubuntu 18.10]
Browser: Firefox, Vivaldi, (but  I think it doesn't matter.)

**Description**  
Just a little, little minor bug:
The title attribute looks a little bit unlikely, since the Contao page title in the backend settings is gone. The `-` seems to be wrong.

![screenshot_contao_login](https://user-images.githubusercontent.com/25878910/52911968-1d119a00-32ab-11e9-86c7-188d1312884c.jpg)

**How to reproduce**  
Update to Contao 4.7. Go to the backend-login page and check the title. 
(I can't reproduce this in the online demo, because there is Contao 4.6 installed.)

**Comment by de-es** [comment]
Mit dem Wegfall des websiteTitle (#203), wodurch es auch zu diesem Anzeigefehler hier kommt, gibt es keine einfache Möglichkeit mehr, sich mit Keepass & Co. projektspezifisch anzumelden, da nun alle Installation denselben Titel haben. Auch Bookmarks vom Backend-Login heißen nun erstmal alle gleich beim Anlegen. Ich würde mir wünschen, dass es optional vielleicht doch noch einen websiteTitle gibt.

**Comment by ausi** [comment]
We could display the domain instead of the websiteTitle: `example.com - Contao Open Source CMS`. @de-es would that solve your issues with Keepass?

**Comment by de-es** [comment]
Ja, das hört sich gut an.

**Comment by wiphi** [comment]
Was würde dann bei Multi-Domain Installationen passieren? Je nach Domain mit der man die Seite aufruft, hätte man dann einen anderen Titel? 🤔

**Comment by de-es** [comment]
Ich persönlich würde das auch Keepass-Sicht sogar als Feature verstehen: Je nach Domain habe ich automatisch andere Zugangsdaten zugeordnet.

**Comment by wiphi** [comment]
Von meiner Seite her ist das auch kein Problem, da ich kein Keepass verwende. War nur aus Interesse gefragt, wie das dann aussieht.

**Comment by leofeyer** [comment]
Fixed in 21ff8c2efbc6e4e5ea650d05f582b7b411cc2083.

**Comment by asaage** [comment]
Please add this for the [installtool](https://github.com/contao/contao/blob/master/installation-bundle/src/Resources/views/layout.html.twig#L6) as well!

**Comment by leofeyer** [comment]
Added in 6eff7bc70f50dfc0534f2e863ab1c95c3ffb7909.
