### ISSUE TITLE
Controller::addToUrl() method too long runtime

### ISSUE THREAD

**Issue by argus231** [contao/contao#3392]
Contao 4.9

Controller :: addToUrl() method is more than 20 times slower in 4.9 than in 3.5. As a result, e.g. the page administration can become slow. In a specific example of a multisite installation, TFB takes about 5 seconds in 3.5, but more than 20 seconds in 4.9. The addToUrl() method is used for almost all action buttons in the backend. According to this, all backend lists are slower than in Contao 3.5 due to this method.

**Comment by Toflar** [comment]
Are you sure this is related to this method? If so, then you can surely give more insights on why exactly this happens?
There are thousands of setups out there, I think we had known something like this earlier. I have lots of setups that have hundreds of pages and I don't have any issues like that. Are you sure it's not related to any extension?

**Comment by leofeyer** [comment]
I can reproduce this and Blackfire confirms it, too:

### PHP 7.4

<img width="1131" alt="php-74" src="https://user-images.githubusercontent.com/1192057/131648917-bf76b9e6-fa3d-417b-b332-94f9cf6ca4b4.png">

### PHP 8.0

<img width="1130" alt="php-80" src="https://user-images.githubusercontent.com/1192057/131648970-d5bd76f7-c379-4285-a5c5-9ce4440b5167.png">

**Comment by leofeyer** [comment]
The number of calls are insane:

* `QueryParser::decode`: 40,158
* `QueryBuilder::encode`: 37,692
* `QueryParser::parsePair`: 20,079
* `QueryParser::buildPair`: 18,846
* `QueryParser::normalize`: 15,030

We should definitely try to improve this. @contao/developers /cc

**Comment by leofeyer** [comment]
<img width="488" alt="" src="https://user-images.githubusercontent.com/1192057/131649609-9b10963d-8290-472f-80bc-e9c08e888ead.png">

**Comment by argus231** [comment]
Sorry that I didn't get back to you. I wanted to show you this today with the help of x-debug. Now you were faster. Yes, it's definitely up to league/uri-components. This is not used in Contao 3.5 and therefore without loss of performance. This makes a large list in the backend, such as an expanded page structure, considerably slower.

Contao 4.9
![contao-4-9](https://user-images.githubusercontent.com/43783562/131652270-bc879792-35ae-45be-a26c-8ebdf1c1bbe4.png)

Contao 3.5
![contao-3-5](https://user-images.githubusercontent.com/43783562/131652324-9363156f-a055-4120-ab68-4e2dd1cbe1a1.png)

**Comment by m-vo** [comment]
The problem isn't the component but the ridiculous amount of calls to it. Likely unwanted recursion. 
Can you maybe debug what is causing it?

**Comment by leofeyer** [comment]
Updating `league/uri-components` to version 2.4 already improves the situation a lot:

### Version 1.8

<img width="429" alt="" src="https://user-images.githubusercontent.com/1192057/131695969-6c084750-7e63-4fd2-9f81-f28d5243ee76.png">

### Version 2.4

<img width="430" alt="" src="https://user-images.githubusercontent.com/1192057/131696026-e9c9b586-aabc-4c5a-862e-3f0aaa3d37e2.png">

I'm not sure if we can change the major version in a bugfix release, though, as there have been breaking changes to the API.

**Comment by Toflar** [comment]
Of course we can. That's why we have Composer :) Everybody else that is using `league/uri-components` must require it themselves so that an update is not possible/only possible once the extension is compatible too.
Absolutely doable.

However, I am with @m-vo - the problem is pretty surely not the component only. How can I reproduce?
