### ISSUE TITLE
Session flash bag is cleared upon "save and close"

### ISSUE THREAD

**Issue by markocupic** [contao/contao#3393]
I don't understand, why contao is clearing the whole session flash bag in contao backend mode, when pressing the saveNclose button? Wouldn't it be better to clear 

_symfony_flashes.contao.BE.info,
_symfony_flashes.contao.BE.error,
_symfony_flashes.contao.BE.confirm

only?

https://github.com/contao/contao/blob/bdc6e30cf50421bf3ec98d67b0b21ddd5ffa950d/core-bundle/src/Resources/contao/drivers/DC_File.php#L336

As it is now, it is not possible to third party backend extensions to properly use the symfony session flash bag.

**Comment by leofeyer** [comment]
@markocupic Can you please check whether #3461 fixes your issue?
