### ISSUE TITLE
bug sitemap.xml Contao 4.12 RC2 / 4.12.1

### ISSUE THREAD

**Issue by falke2020** [contao/contao#3395]
Contao 4.9.12.RC2 or Contao 4.12.1

There is a bug in the above Contao versions. All pages are included in the sitemap.xml, even if they are marked with noindex / nofollow.

**Comment by fritzmg** [comment]
I can confirm the problem in Contao 4.12.x-dev.

**Comment by fritzmg** [comment]
Closing in favor of #3396.
