### ISSUE TITLE
Contao 4.12: Install-Tool and Debug Mode: Error is thrown

### ISSUE THREAD

**Issue by Xendiadyon** [contao/contao#3398]
**Affected version(s)**

Contao 4.9 & 4.12

**Description**

While the debug mode is active, it is not possible to access the install tool. Instead, a symfony exception HTTP 500 Internal Server Error is fired. This should be no error but only a warning, so I would not expect an exception here.

![image](https://user-images.githubusercontent.com/2657385/131325842-ace83b75-ec7c-4525-83b5-dc2c27a49f00.png)

Steps to reproduce:

1. I installed the extension contaoblackforest/contao-dropzone-upload
https://github.com/ContaoBlackForest/contao-dropzone-upload/blob/master/src/Resources/contao/dca/tl_calendar.php
2. I use Contao without the calendar extension
3. When I have the Debug mode activated (e.g., over the contao manager) and try to access the install tool, the warning (nonexistent array) is thrown as an exception.

**Workaround:** Disabling the Debug mode allows me to access the install tool.

**Comment by fritzmg** [comment]
This is an error you need to report in the respective extension, i.e. here: https://github.com/ContaoBlackForest/contao-dropzone-upload/issues

**Comment by Xendiadyon** [comment]
Hi @fritzmg , I don't think so. The PHP warning (undefined array) should imho not lead to an exception, so I would see it as a problem with either the install tool or the debug mode of contao.

**Comment by fritzmg** [comment]
No, that's normal. All warnings will be converted to an exception in the `dev` environment.

**Comment by fritzmg** [comment]
If you want, you can control this via the `%debug.error_handler.throw_at%` parameter or the `framework.php_error.throw: false` bundle configuration for a temporary workaround. See https://symfony.com/doc/4.4/reference/configuration/framework.html#throw

However, the best course of action is to always fix the warning of course (hence why you should report this warning for the aforementioned extension).
