### ISSUE TITLE
Eigene Layoutbereiche - Titel/ID - Inkonsistent?

### ISSUE THREAD

**Issue by Znrl** [contao/contao#341]
**Affected version(s)**
Vermutlich alle ab 4, definitiv 4.6.12 (Demo) und 4.7

**Description**
Während bei 3.5 die Bezeichung = id war hat man jetzt zwei Felder dafür.
Man kann einen eigenen Layoutbereich "anlegen" (ohne Fehlermeldung speichern) und eines der Felder(Titel/ID) leer lassen.
Lässt man den Titel leer, wird der Bereich angelegt und man erhält unter Frontend-Module (Themes -> Seitenlayout Einstellungen)
eine unschöne "leere" Auswahlmöglichkeit (oder auch merere, wenn man mehrere anlegt).
Ansonsten funktioniert es.

Gibt man nur einen Titel ein, wird der Bereich weder im Frontend noch unter den Frontend-Modulen angezeigt. Man könnte ja keine ID brauchen oder ein eigenes Template auswählen.

Ich denke, dass man in dem Fall beide Felder zu Pflichtfeldern machen sollte.
Oder wieder Titel -> ID (alles andere ist unter Frontendmodulen sowieso verwirrend, siehe leere Auswahlmöglichkeit oder gleiche Titel. )
statt ID vtl. Feld für zusätzliche Klassen.

**How to reproduce**  
In der Contao-Demo "Eigene Layoutbereiche" in verschiedenen Kombinationen mit und ohne Titel/ID anlegen.
Unter Frontend-Module bzw. im Frondend (Quelltext) nachschauen.

**Comment by Znrl** [comment]
Noch ein kurzer Nachtrag.
Es ist auch möglich den exakt gleichen Layoutbereich (gleiche Bezeichnung und gleiche ID) Mehrfach anzulegen.
In der Datenbank wird das auch gespeichert, hat ansonsten aber wohl kaum Auswirkungen.

**Comment by leofeyer** [comment]
Behoben in 2c6727b36d5f4b07886b9b365eea5abfa15b0425.
