### ISSUE TITLE
JSON with {{iflng}}-InsertTags in attributes

### ISSUE THREAD

**Issue by kp-mtrame** [contao/contao#3413]
**Affected version(s)**

Contao 4.9

**Description**

With the security fix some attributes that contain JSON **and** {{iflng}}-InsertTags no longer work

`<div data-config='{"foo":{"lang":"{{iflng::de*}}de{{iflng::en}}en{{iflng}}","bar":"123"}}'></div>`

gets replaced with

`<div data-config='{"foo":{"lang":"de","bar":"123"|attr}}'></div>`

**Comment by fritzmg** [comment]
Can you please try `4.9.x-dev` and see if that fixes it?

**Comment by ausi** [comment]
> `<div data-config='{"foo":{"lang":"{{iflng::de*}}de{{iflng::en}}en{{iflng}}","bar":"123"}}'></div>`

Where do you use this code? In an html5 template?

**Comment by kp-mtrame** [comment]
yes, in an html5 template

**Comment by ausi** [comment]
I would use something like this instead then.

```php
<div data-config='<?= htmlspecialchars(json_encode([
	'foo' => [
		'lang' => System::getContainer()->get('request_stack')->getCurrentRequest()->getLocale(),
		'bar' => '123',
	],
])); ?>'></div>
```

If the JSON has to be a string you can use something like this:

```
<div data-config='<?= Controller::replaceInsertTags($yourJson) ?>'></div>
```

But this can cause security issues. You should not mix JSON with insert tags.

**Comment by kp-mtrame** [comment]
The above example was just a simplified version to easily reproduce the problem. The configuration for a slider is actually contained within the attribute. An array contains its configuration.

```php
$config = [
  ...
  'controlsText' => [
       '{{iflng::de*}}Vorheriger Slide{{iflng::en}}Previous slide{{iflng}}', 
       '{{iflng::de*}}Nächster Slide{{iflng::en}}Next slide{{iflng}}'
   ],
   ...
];

<div data-config="<?= json_encode($config) ?>"></div>
```


So it was used more for translating strings. Now we use `$this->trans()` for this. However, the above example worked up to version 4.9.17!

Thanks for the quick responses!

**Comment by m-vo** [comment]
You should not use a high-level user feature like insert tags in your templates if avoidable. In there, you have access to the actual data and services, so just use them. :slightly_smiling_face:

**Comment by ausi** [comment]
> However, the above example worked up to version 4.9.17!

Yes, we are aware of that. Sadly, I was not able to find a solution to this problem that is as secure as the current logic is.

As much as we would like to be 100% backwards compatible, security has to come first.

**Comment by aschempp** [comment]
@kp-mtrame you can replace your template code with this, which is even better for performance:

```php
$config = [
  ...
  'controlsText' => [
       $GLOBALS['TL_LANGUAGE'] === 'de' ? 'Vorheriger Slide' : 'Previous slide', 
       $GLOBALS['TL_LANGUAGE'] === 'de' ? 'Nächster Slide' : 'Next slide'
   ],
   ...
];

<div data-config="<?= json_encode($config) ?>"></div>
```

Alternatively, you might consider moving the labels to actual language files and use translations

```php
$config = [
  ...
  'controlsText' => [
       $this->trans('mySliderPrevious', [], 'contao_default'), 
       $this->trans('mySliderNext', [], 'contao_default')
   ],
   ...
];

<div data-config="<?= json_encode($config) ?>"></div>
```

**Comment by ausi** [comment]
@aschempp `$GLOBALS['TL_LANGUAGE']` is deprecated, just for info ☺️
