### ISSUE TITLE
Improve the error page handling in the sitemap controller

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3415]
**Affected version(s)**

Contao 4.12

**Description**

Currently the `/sitemap.xml` route also shows URLs to the 404, 403 and 401 pages (which then the Contao Crawler for example will complain about, since they do not respond with 200).

The `supportsContentComposition` check is insufficient since these page types do support content composition, but should never show up in a sitemap (nor should they be accessible via their alias at all in my opinion). @aschempp any idea how to filter page types for this purpose in a general way? The old `Backend::findSearchablePages` only returned pages with type `regular`, but that is not sufficient due to custom page types / page controllers. Should we filter the page types based on a hard coded list (or a service parameter)?

**Comment by fritzmg** [comment]
I would propose the following:

* Maintain a list of legacy page types that are supposed to be exempt from showing in the sitemap.
* Introduce a new `sitemap` attribute for the `@Page` annotation / service tag with which you can control whether pages of this page type are allowed to be shown in sitemaps (defaults to `true`).
* Introduce a new `allowedInSitemap` method for the `PageRegistry` service.

**Comment by leofeyer** [comment]
As discussed in Mumble on September 30th, we do not want a `sitemap=false` attribute. The error pages should not have an external route, so it cannot be added to the sitemap. Additionally, we only should only add routes with `'_format' => 'html'`.

As a quick fix, we want to hardcode the exemptions again.
