### ISSUE TITLE
Add Console command to export a .sql dumb to use for the install tool

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#3418]
It would be nice if there was a [console command](https://docs.contao.org/dev/reference/commands/) to quickly export a .sql file that can be used via the install tool. 

See: https://github.com/contao/official-demo/blob/main/docs/Update_COD.md

**Comment by fritzmg** [comment]
Just use `mysqldump`? Or what exactly do you need?

**Comment by ausi** [comment]
> Just use `mysqldump`?

The output format of `mysqldump` is not compatible with the install tool website template import AFAIK.

**Comment by ausi** [comment]
The format created by https://github.com/do-while/contao-BackupDB is the one the install tool expects I think.

**Comment by leofeyer** [comment]
`mysqldump --skip-add-locks --complete-insert --skip-extended-insert --skip-disable-keys --no-create-info` will create an SQL dump that should be compatible with the install tool.
