### ISSUE TITLE
Don’t use input encoding for fields with predefined options

### ISSUE THREAD

**Issue by ausi** [contao/contao#3421]
Encoding the values for fields with `options` like `select` or `radio` doesn’t make much sense I think because the values are predefined and can therefore not be used to inject bad code.

See https://github.com/isotope/core/issues/2249#issuecomment-911553712

**Comment by m-vo** [comment]
Why do we use the real option values in the first place and not a mapping? :slightly_smiling_face: 

I've seen patterns like enumeration from 0 to n or hashes of the value (to prevent selecting the wrong thing if anything was added/removed in the meantime). Maybe that could be useful for us, too.

**Comment by aschempp** [comment]
not a bad idea from @m-vo but this only works if the form is submitted to our widget. It will e.g. not work with a GET form to an external target.
