### ISSUE TITLE
4.12.1 Sprachenkürzel mit Minuszeichen werden falsch gespeichert

### ISSUE THREAD

**Issue by jankout** [contao/contao#3427]
4.12.1

Wenn ich das chinesische Sprachenkürzel standardmäßig _zh-CN_ beim Startpunkt der Webseite eingebe und speichere, wird es mit einem Unterstrich gespeichert, was falsch ist und zu fehlerhaften bzw. gar keinen Übersetzungen führt (z.B. im Sprachenwechsler). Ich habe es in 4.9.x getest, da entsteht dieser Fehler nicht. Siehe beigefügtes Bild.
![Error Language Suffix](https://user-images.githubusercontent.com/3715050/132241436-60b0306f-5ca9-4bcf-ad1f-3d6b49c5cdd5.gif)

**Comment by fritzmg** [comment]
Das ist normal. Seit Contao 4.12 werden die Locales beim Speichern normalisiert. Die changelanguage Extension muss dahingehend evt. noch angepasst werden .

**Comment by tarun-uwe** [comment]
Es handelte sich hier um ein Modul Konfiguration. Durch die Normalisierung wurden die eigenen Übersetzungen im Modul nicht korrekt zugeordnet. Das Ticket kann geschlossen werden.
