### ISSUE TITLE
Feature: Startseite bei gefilterten Seiten anzeigen

### ISSUE THREAD

**Issue by jankout** [contao/contao#3428]
Ich fände sehr hilfreich, wenn beim Seitenfilter auch die Startpunkte angezeigt wären, damit man weiß, zu welcher Sprachversion die aufgelisteten Seiten gehören. 

Wenn man sich vorstellt, dass man mehrere Sprachen mit den Seiten namens Download hat, kann man gleich diesen vorgeschlagen Vorteil nachvollziehen (siehe beigefügtes Bild)
<img width="1180" alt="contao-feature_seitenfilter-mit-startpunkten_1" src="https://user-images.githubusercontent.com/3715050/132313176-e5650147-4cd9-431d-aef5-2b0114e1be18.png">

**Comment by bytehead** [comment]
Maybe solved by #3391...
