### ISSUE TITLE
Remove the trusted hosts/proxies settings from the Contao kernel

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3429]
Because Symfony stores these settings [in the Container](https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/HttpKernel/Kernel.php#L790-L796) as of version 5.3 (see #3329).

**Comment by aschempp** [comment]
I don't think we'll use the container configuration anytime soon, their attempt does not match our requirements imho. They boot the kernel **on every request** with the argument that it does not affect performance with preloading. But 99.99% of our users do not have preloading …
