### ISSUE TITLE
Page controllers do not show up in 'allowed page types'

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3431]
**Affected version(s)**

Contao Contao 4.12

**Description**

Page types that were created via controllers + the `@Page` annotation don't show up in the privilege settings for page types:

![Screenshot_20210907_123619](https://user-images.githubusercontent.com/5305677/132330956-031f8607-4325-4232-8457-19a855480dc7.png)

**Comment by aschempp** [comment]
@m-vo just thinking about this: if you already have custom page controllers, is it true that you cannot allow access to them? Which means currently regular users can never access page controller types?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/3446

**Comment by m-vo** [comment]
@aschempp Sorry for the late response. Yes, they cannot access the custom page types at all (edit is grayed out like if no permission was granted).
