### ISSUE TITLE
insert tag {{post::*}} funktioniert manchmal nicht

### ISSUE THREAD

**Issue by green-pixelbox** [contao/contao#3433]
**Affected version(s)**

Contao 4.9.15, 4.9.17, 4.9.20

**Description**

In den Contao Formular-Einstellungen habe ich einen insert tag {{post::betreff}} unter Formulardaten versenden -> Per E-Mail versenden -> in der Betreff Zeile stehen. Das Insert Tag soll das Feld aus dem Formular "betreff" mit in den Betreff der E-Mail eintragen. Wenn ich im Backend eingeloggt bin und ich teste das Formular im Frontend, ist der Betreff in der versendeten E-Mail enthalten. Wenn ich einen frischen Browser Chrome aufmache, dort das Formular versende, erscheint der Betreff nicht mehr in der E-Mail. Bleibe ich dann in Chrome, und versende das Formular nocheinmal, ist der Betreff plötzlich wieder in der E-Mail vorhanden. Das gleiche habe ich auch in den Browsern Edge und Opera getestet. Dort ist das gleiche Problem. LEider ist das auch so, das Bestätigungsmails von dem Modul Notification Center dann nicht versendet werden, wenn das insert tag {{post::betreff}} in der E-Mail fehlt.

**Comment by green-pixelbox** [comment]
Hier noch die Konfiguration in den Contao-Formular Einstellungen (siehe screenshot)
![contao-inserttag-bug](https://user-images.githubusercontent.com/3920742/132346953-fb47afa0-db2c-4dc8-bb5b-fe5737dcfd48.PNG)

**Comment by aschempp** [comment]
kannst du mal prüfen wann/ob du von Contao ein Session-Cookie bekommst?

**Comment by Toflar** [comment]
Zur Info, die Daten werden für max. 60 Sekunden nach dem Absenden behalten. Danach werden sie gelöscht.

**Comment by green-pixelbox** [comment]
cookie info im screenshot cookie-nach-formular-absenden
![cookie-nach-formular-absenden](https://user-images.githubusercontent.com/3920742/132674644-e8e12084-aeea-4219-8061-b4765590d6d0.PNG)

**Comment by green-pixelbox** [comment]
Hier kann man das Formular auch einsehen und testen. 
https://musterc49.gp-serverpower.de/kontakt
Contao Version 4.9.17
Wenn man es abgesendet hat, sollte man über das notification center eine Bestätiungsmail erhalten, was aber nur passiert, wenn man im gleichen browser im Backend eingeloggt ist. In einem frisch geöffneten Chrome z.B. wird keine Bestätigungsmail versendet und auch der Insert Tag {{post::betreff}} im Betreff der E-Mail bleibt leer.

**Comment by fritzmg** [comment]
I can confirm the problem in all Browsers (well - FF, Chrome, Edge).

Reproduction steps:

1. Create a new form in the form generator.
2. Enable **Send form data via e-mail** and set the **Subject** to `Test: {{post::test}}` for example.
3. Insert a text field into the form called `test` (and a submit button).
4. Insert the form into a page.
5. Open said page in any browser with a fresh session.
6. Enter something in the `test` field and submit the form.
7. Enter something in the `test` field again and submit the form.

The first email will have the subject `Test:` while the second email will have the subject `Test: whatever you entered`.

Response headers of the first request to the page with the form look like this:

```
HTTP/1.1 200 OK
Server: nginx/1.21.1
Content-Type: text/html; charset=utf-8
Content-Length: 18873
Connection: keep-alive
Date: Thu, 09 Sep 2021 11:28:49 GMT
Permissions-Policy: interest-cohort=()
Cache-Control: must-revalidate, no-cache, no-store, private
x-powered-by: PHP/7.4.22
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer-when-downgrade, strict-origin-when-cross-origin
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Contao-Cache: miss
Age: 0
```

**Comment by green-pixelbox** [comment]
der Fehler, das die {{post::*}} Daten nicht in der E-Mail stehen und das die Bestätigungsmail aus dem notification center nicht versendet wird tritt auch in der ContaoVersion 4.12.1 auf.

**Comment by fritzmg** [comment]
@green-pixelbox you can test the changes from #3971, that should fix your issue :)
