### ISSUE TITLE
HTML code is output as a string in the frontend

### ISSUE THREAD

**Issue by andyKempf** [contao/contao#3435]
In Contao 4.9 LTS, an SVG that is maintained in the HTML element type is output as a string in the frontend.

The required tags have been set in the security settings, but are still output as string in the frontend.
The same happens with the template-tag.

Backend:
<img width="1448" alt="Bildschirmfoto 2021-09-07 um 23 14 42" src="https://user-images.githubusercontent.com/48767191/132412943-eedecad9-03a0-46f7-b6bb-b70a1c5f21da.png">
<img width="956" alt="Bildschirmfoto 2021-09-07 um 23 19 45" src="https://user-images.githubusercontent.com/48767191/132412947-e2938395-db77-4f49-bede-faee547cfad0.png">

Frontend:
<img width="1290" alt="Bildschirmfoto 2021-09-07 um 23 14 34" src="https://user-images.githubusercontent.com/48767191/132412936-190135c4-8dd2-49f2-91a5-1e719b09f0ca.png">
<img width="1620" alt="Bildschirmfoto 2021-09-07 um 23 23 32" src="https://user-images.githubusercontent.com/48767191/132412948-a1e72c0e-0262-4fed-88a4-558acaf4dc6d.png">

Does anyone have any ideas?

Best regards from Munich
Andi

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
@andyKempf Did you re-save the HTML content element after changing the allowed elements setting?
