### ISSUE TITLE
if-condition never evaluates to true

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3438]
**Affected version(s)**

Contao 4.9+

**Description**

https://github.com/contao/contao/blob/29920a87dfad8338d6eee28dcfa7c10db2aa5538/core-bundle/src/Resources/contao/dca/tl_files.php#L896-L902

How come no one has reported this yet? Is the if-condition redundant?

**Comment by ausi** [comment]
> Is the if-condition redundant?

Don’t think so, it should probably be reverted to the version before ca02a750072a69002fb21bc68a3b65211437571c

> How come no one has reported this yet?

If this fails, the sync-exclude checkbox is not shown, but only during a folder rename, right? Renaming a folder and changing the sync-exclude field at the same time probably doesn’t happen that often.
