### ISSUE TITLE
Make Template::asset static

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#3448]
Is there any particular reason why methods like `generateStyleTag`, `generateInlineStyle` etc. are static but the method `asset` is not?

Currently I'm building a form widget where I seem to have no access to an instance of `Template` or rather `FrontendTemplate`. In order to make use of the `asset` method I need to create a new `FrontendTemplate` instance.

Adding the assets from within the template, rather than adding them to `TL_HEAD` or `TL_JAVASCRIPT`, wouldn't be a clean solution in this case because a form could have the same type of widget multiple times which would result in multiple loads of the same asset.

**Comment by fritzmg** [comment]
It's a helper function for templates. In your services you can use `assets.packages` directly.

**Comment by bennyborn** [comment]
> It's a helper function for templates.

So is `generateStyleTag` and the others?...

> In your services you can use `assets.packages` directly.

Sure but then I'm still required to strip the leading slash everytime like the core does.

**Comment by fritzmg** [comment]
> Sure but then I'm still required to strip the leading slash everytime like the core does.

You do not really have to do that. No problems will arise if you keep the leading slash (in fact likely less problems will occur 😉).

> So is generateStyleTag and the others?...

The `asset` function is a helper function for templates, because you cannot use dependency injection in your templates and so that you do not have to get the container and then the service each time in the template. Same with `figure` or `trans`.

**Comment by m-vo** [comment]
We cannot remove these things for BC, but the template helpers shouldn't be accessible from outside. In fact, they should ideally only be proxies for services that do the actual work.

**Comment by bennyborn** [comment]
> No problems will arise if you keep the leading slash (in fact likely less problems will occur 😉).

Actually... in our case it would break everything since we're using one domain and subdirectories for different Contao installations during development ;)

> The `asset` function is a helper function for templates, because you cannot use dependency injection in your templates and so that you do not have to get the container and then the service each time in the template. Same with `figure` or `trans`.

I totally got that but my question still stands: Why not make it static and make it easily accessible for others to use and save some lines of unnecessary code? Since it's not using `$this` anywhere it wouldn't cause any problems to do so.

`generateInlineStyle` only spares me a couple of characters but still someone decided at one point in time decided it might be useful for everyone to be easily accessible.

**Comment by m-vo** [comment]
> I totally got that but my question still stands: Why not make it static and make it easily accessible for others to use and save some lines of unnecessary code?

I'm :-1:  on this. We could discuss if a helper is needed, implement it as service or a utility class and use it in there but the method inside `FrontendTemplate` should not be exposed, that's the wrong responsibility.

**Comment by fritzmg** [comment]
And a helper is not really needed, since all the method does in addition is trim the leading slash … which you might not need anyway, depending on your use case.

**Comment by bennyborn** [comment]
> We could discuss if a helper is needed, implement it as service or a utility class and use it in there

Totally fine with that.

> but the method inside `FrontendTemplate` should not be exposed, that's the wrong responsibility.

So from your perspective the other static methods like `generateStyleTag` and `generateInlineStyle` should've not been publicly accessible in the first place?

Don't get me wrong, I'm not fixed on the idea to just make `asset` a static method now. I just want a consistent framework for all Contao Devs to use - maybe something for the roadmap to Contao 5?

> And a helper is not really needed, since all the method does in addition is trim the leading slash … which you might not need anyway, depending on your use case.

Depending on the use case, yes. But if it was decided, for whatever reason, that in order to use the assets correctly in Contao you need to strip the leading slash, this should be a method of the framework accessible for all other Contao extensions. 

There is absolutely no sense in calling it a "framework" and then leaving some of it's functionality open to be re-implemented every time some dev wants to use the same stuff in his own extension.

**Comment by fritzmg** [comment]
> There is absolutely no sense in calling it a "framework" and then leaving some of it's functionality open to be re-implemented every time some dev wants to use the same stuff in his own extension.

I don't think calling something a "framework" automatically means that the framework needs to implement every conceivable use-case for you.

And for this particular instance, the difference would be the following:

```php
$this->assetHelper->getAssetUrl(…);
```

vs

```php
ltrim($this->assets->getUrl(…), '/');
```

It does not really make sense to create an asset helper just for this?

**Comment by bennyborn** [comment]
> It does not really make sense to create an asset helper just for this?

If I understood @m-vo correctly such a helper class / service should then also provide `generateStyleTag`, `generateInlineStyle` etc.

IMHO as soon as such a helper does anything Contao specific, like stripping the leading slash to be complient with the base tag, it should be open for anyone to use to make sure all extensions are behaving the same. 

**Quick real life example:** 
[terminal42/contao-fineuploader](https://github.com/terminal42/contao-fineuploader) is an extension that we cannot test in our dev environment since they've implemented their own "AssetManager" which does not strip that leading slash and therefore is not usable in a Contao installation that lives inside a subdirectory.

If they had used the asset method provided by the Core there would be no problem and their extension would behave the same as all others. 

**My point is just about consistency within the Contao eco system.** 

This does not only apply to this discussion about assets. It's the same with the handling of custom backend modules (I know, this is since then been worked on #3020), custom image processing based on the existing contao/image service (#3347), password hashing / encryption (since the encrypt-flag was deprecated / removed) and much more.

One USP Contao once had was that most of the extensions could be sold as "clean" and "bulletproof" since they mostly relied on functionality provided by the Core. With more and more parts of the framework being removed or led to the devs to write their own implementation, I'm pretty certain we're going down a route that's closer to Wordpress which I really don't want to happen (every dev doing as they like, no framework, no standards, plenty of room for errors and vulnerabilities). 😐

**Comment by m-vo** [comment]
> If I understood @m-vo correctly such a helper class / service should then also provide generateStyleTag, generateInlineStyle etc.

You would only use these from within your templates, no?

**Comment by bennyborn** [comment]
> You would only use these from within your templates, no?

Currently not. As I wrote in the first post:

> Adding the assets from within the template, rather than adding them to `TL_HEAD` or `TL_JAVASCRIPT`, wouldn't be a clean solution in this case because a form could have the same type of widget multiple times which would result in multiple loads of the same asset.

**Comment by m-vo** [comment]
Maybe, I'm missing the point. But i still fail to see any reason to use `generateStyleTag` outside a template context?

**Comment by bennyborn** [comment]
> Maybe, I'm missing the point. But i still fail to see any reason to use `generateStyleTag` outside a template context?

Quick excerpt from the current situation:

```php
class FormMyCustomField extends Widget {

    public function parse() {

        $GLOBALS['TL_HEAD'][] = Template::generateStyleTag($tpl->asset('field.css','myfield'), 'screen');
        $GLOBALS['TL_JAVASCRIPT'][] = $tpl->asset('form.js','myfield');
    }
}
``` 

As said I cannot add the Stylesheet / JavaScript from within the template since this would result in loading the same assets multiple times if my custom field type is used more than once in a form.

**Comment by m-vo** [comment]
IMHO you should not pass pre-rendered HTML to your template. Instead use a template to render it or just use `TL_CSS`?

**Comment by fritzmg** [comment]
> Maybe, I'm missing the point. But i still fail to see any reason to use `generateStyleTag` outside a template context?

That's a pretty common use case though. Especialyl for `generateScriptTag`. But that's not the issue anyway, as these deliberately are public static helper functions.

**Comment by m-vo** [comment]
Still fighting for "no HTML outside templates". :smile:

**Comment by bennyborn** [comment]
> IMHO you should not pass pre-rendered HTML to your template. Instead use a template to render it or just use `TL_CSS`?

Maybe I'm blind but I don't even have a template object to pass anything to from  inside a form widget 🤷‍♂️

**Comment by fritzmg** [comment]
> Still fighting for "no HTML outside templates". 😄

Not sure what you mean? How else would you add additional JavaScript to the end of the body?

**Comment by m-vo** [comment]
I'd say in general: Create a template, add your HTML in there or use the existing asset functions (could e.g. also be `asset` or `encore_entry_script_tags` in Twig) . Then include the template. Only if that's not possible yet (because you cannot control the context), return the rendered result. But still use a template to compose the HTML to use proper encoding etc.

**Comment by fritzmg** [comment]
I am not really sure what you mean. If you have a content element that needs JavaScript for example, you add said JavaScript to the end of the `<body>` via

```php
$GLOBALS['TL_BODY'][] = Template::generateScriptTag('path/to/script.js', true, null);
```

And this should to be done within the content element, not the template of the content element, since it's just PHP code.

**Comment by m-vo** [comment]
Yes, that's how it was done, but I still think it's wrong. There should never be a non-template method generating HTML. And `Template::generateScriptTag()` does exactly that. It suggests this is API of a library (and in fact it is) but it should not. :smile:

**Comment by fritzmg** [comment]
But this is not just how it _was_ done, this is what you _currently_ do in Contao and should also be best practise - until other solutions are here.

Regardless, imho this has no bearing on the discussion at hand anyway. These public static helper functions are functionally different to `asset`, `figure`, `trans` etc.

**Comment by leofeyer** [comment]
As discussed in the Contao call, @aschempp will check if the problem is caused by their extension or if there is a Symfony use case.

**Comment by aschempp** [comment]
@bennyborn can you please see if https://github.com/contao/contao/pull/3595 fixes the problem?

**Comment by bennyborn** [comment]
> @bennyborn can you please see if #3595 fixes the problem?

I certainly will but it seems I missed out on something. What exactly should be "fixed" or what's the initial problem? Surely the method is still not static 🤔

**Comment by fritzmg** [comment]
You (or any other extension, like `terminal42/contao-fineuploader`) should now be able to use `assets.packages` without any issues, even if your Contao instance runs in a subdirectory.
