### ISSUE TITLE
Pages with `tl_page.requireItem` throw exceptions in ModuleBreadcrumb

### ISSUE THREAD

**Issue by SeverinGloeckle** [contao/contao#3450]
**Affected version**

 Contao 4.12

**Description**

Using `ModuleBreadcrumb` on a page with `tl_page.requireItem` enabled ("Require an item"-option) throws:

````php
Contao\CoreBundle\Exception\RouteParametersException

"Parameter "parameters" for route "cmf_routing_object" must match "/.+" ("" given) 
to generate a corresponding URL."
````

The exception is caught within `ModuleBreadcrumb` and the error is just printed to the system log:
> Unable to generate URL for page ID X: Parameter "parameters" for route "cmf_routing_object" must match "/.+" ("" given) to generate a corresponding URL.

**Details**
This is because the `ModuleBreadcrumb` does not pass the parameters to the router:

https://github.com/contao/contao/blob/50079d9fe09ad802ca3bdde6d7ccac6b2338739d/core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php#L202

https://github.com/contao/contao/blob/50079d9fe09ad802ca3bdde6d7ccac6b2338739d/core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php#L250-L262

**Possible fix**
The current auto-item should be resolved by `ModuleBreadcrumb` and passed to the router – either by default or just if the current page has `tl_page.requireItem` set to true.

As an alternative, there could not be generated any url since the breadcrumb menu does not require the url of the current page.

### Bug 2: Parent pages which require an item
The exception is thrown as well if any other page in the breadcrumb trail has `tl_page.requireItem` set to true. While I can hardly think of a reason to have a child page on a page with an auto-item, I still think this is a bug.

**Possible fix**
In my opinion, a parent page which requires an item should not be included in a breadcrumb trail since no correct url can be generated. Thus, it could be ignored as well in:

https://github.com/contao/contao/blob/50079d9fe09ad802ca3bdde6d7ccac6b2338739d/core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php#L100-L103

**Comment by fritzmg** [comment]
> In my opinion, a parent page which requires an item should not be included in a breadcrumb trail since no correct url can be generated. Thus, it could be ignored as well in:

The item needs to be rendered, otherwise the breadcrumb path would not be correct. However, the item could then just not have an URL, yes.

So imho the current implementation is correct already, since no URL is generated (when no URL can be generated). Only the system log entry as an error is misleading - it's not really an error.

**Comment by SeverinGloeckle** [comment]
I'm not sure if I agree about adding parent items without a url to the breadcrumbs.

Currently, this would generate an anchor with the title of the parent page but the base url of the website as `href`, which seems wrong to me.

Now while we could adjust the breadcrumb template and handle items without a url to generate only a text label for those pages, the schema data for `BreadcrumbList` would still include the empty/base url.

However, one could argue that this is just misconfiguration by the user and such pages should get excluded via `tl_page.hide` manually.

**Comment by fritzmg** [comment]
> Currently, this would generate an anchor with the title of the parent page but the base url of the website as `href`, which seems wrong to me.

Ah, yes, that is definitely wrong. When no URL is defined it should be a `<span>` just like in the regular navigation module.

**Comment by SeverinGloeckle** [comment]
While adjusting the breadcrumbs template would fix a symptom of the second issue (trailing pages with `requireItem`), the two basic issues remain:

### 1. Exception for active page
If the active page has `requireItem` enabled, an exception is thrown and written to the system log. No url is generated for the page (a url it not used in the default `mod_breadcrumb` template, but in the JSON-LD data).

Possible fixes:
1. Pass the params of the current request to `getPageFrontendUrl`.
2. Do not generate the url for the active page (requires removal of `@id` in the JSON-LD data for the last item).

### 2. Exceptions for trailing pages
If any trailing page has `requireItem` enabled, an exception is thrown and written to the system log. No url is generated for these pages.

Since it is not possible to restore the required item for a trailing page, we have two options:
1. Do not add these pages to the breadcrumbs trail.
2. Adjust the breadcrumbs template and only add `<span>` instead of `<a>` for these items & swallow the exception.

The second option would still lead to incorrect JSON-LD data:
````json
...
{
  "@type": "ListItem",
  "item": {
    "@id": ".\/",
    "name": "Foo"
  },
  "position": 5
}
`````

--

In my option, solution number 1 is the better solution in both cases.

I think we should agree on the way to go before working on a fix.

**Comment by SeverinGloeckle** [comment]
As discussed in Mumble on September 30th, we want to:
- remove parent pages with `tl_page.requireItem` from the breadcrumbs template and the JSON-LD data
- use the current request path for the URL of the current page

I will create a pull request accordingly.

**Comment by SeverinGloeckle** [comment]
Additionally the breadcrumbs should handle the edge case if a parent page is an error page (404, 403, 401). These should not be added to the breadcrumbs as well.

At best the same logic/solution that will be developed for #3415 can be used to determine whether a page should be added to the breadcrumbs.
