### ISSUE TITLE
HTML-Entities erden encoded trotz gesetztem decodeEntities (rte = ace|sql)

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#3451]
**Affected version(s)**

Contao 4.9

**Description**

Hallo in die Runde,

ich habe folgendes Problem:

```
'sourceWhere' => [
    'label' => &$GLOBALS['TL_LANG']['tl_sync_config']['sourceWhere'],
    'inputType' => 'textarea',
    'exclude' => true,
    'eval' => ['class' => 'monospace', 'rte' => 'ace|sql', 'tl_class' => 'long clr', 'decodeEntities' => true],
    'explanation' => 'insertTags',
    'sql' => 'text NULL',
],
```

Das ist der DCA. Dort ist `decodeEntities` gesetzt. Wenn ich das Feld speichere, sind einige Zeichen aber dann doch encoded:

`tl_submission.tstamp &#62; 0 AND tl_submission.pid NOT IN (10001, 10002, 10004)`

also das ">" wurde encoded.

Ich habe dann mal das `rte` deaktiviert und siehe da: dann geht es. Für ein Syntax-Highlighting wäre es aber schön, wenn ich das aktiv lassen könnte.

@ausi hat die Vermutung, dass es daran liegt, dass bei gesetztem `rte` automatisch `allowHtml` gesetzt wird.

Danke!

Ciao Defcon0

**Comment by ausi** [comment]
We should probably update the check in https://github.com/contao/contao/blob/0ba1acd7d93da55598a02fa6963dacf635bdad87/core-bundle/src/Resources/contao/library/Contao/Widget.php#L1274 to only enable `allowHtml` for rich text editors that output HTML but not for other formats like `ace|sql`.

**Comment by leofeyer** [comment]
> to only enable `allowHtml` for rich text editors that output HTML

How do we know? We can only say this for `'rte' => 'tinyMCE'` and `'rte' => 'ace|…'` but not for any custom editors that might have been added, right?

**Comment by ausi** [comment]
> How do we know? We can only say this for `'rte' => 'tinyMCE'` and `'rte' => 'ace|…'` but not for any custom editors that might have been added, right?

Yes. I think custom editors have to add this setting themself if they want to use it.

**Comment by ausi** [comment]
Closed in favor of #3513
