### ISSUE TITLE
Member gets logged out when member group is changed

### ISSUE THREAD

**Issue by daniel-nemeth** [contao/contao#346]
Hey guys,
I have the following issue.
Cheers for feedback.

**Affected version(s)**
4.6

**Description**  
- The frontend member gets logged out if the member group gets changed via frontend or backend.
- See also: [Contao forum](https://community.contao.org/de/showthread.php?73740-Automatischer-Logout-nach-Speichern-von-Mitgliedergruppen-mit-Modul-quot-Personal-data-quot)
- Reproduce-able in Contao-Demo

**How to reproduce**  
1. Add a member and assign a member group
2. Create a module "Personal data"
3. Add 'member groups' to editable fields
4. Add the module to page
5. Change the member's group settings via the module and save -> You are getting logged out in frontend
6. Change the member's group settings via backend and save -> You are getting logged out in frontend

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/contao/issues/313 :)

**Comment by daniel-nemeth** [comment]
I am sorry!
Want me to delete it?
