### ISSUE TITLE
ce_image 404 in 4.12 / files directory not symlinked to public directory

### ISSUE THREAD

**Issue by aznoqmous** [contao/contao#3465]
**Affected version(s)**

Contao 4.12

**Description**

`files` directory is no longer symlinked running the `contao:symlinks` command, which result in broken images using default `ce_image` content elements

I manually added `$this->symlink('files', Path::join($this->webDir, 'files'));` inside `contao:symlinks` command to solve that issue,
am I doing anything wrong ?

**Comment by m-vo** [comment]
This is correct behavior - the `files` directory should not get symlinked. If you want to publish files move them in a sub directory, enable the `public` checkbox for this directory in the file manager or create a `.public` file in it and rerun the command.

You cannot publish the root `files` directory itself.

**Comment by m-vo** [comment]
For reference https://github.com/contao/contao/issues/286 / https://github.com/contao/contao/commit/02bebafb1f233b22e999a45e8bb9c5209e1805c2.

**Comment by ausi** [comment]
> which result in broken images using default `ce_image` content elements

If you do not enable the “Use original image if dimensions match” checkbox in the settings of the used image size it should not be a broken image because it is stored in *assets/images* then.

**Comment by aznoqmous** [comment]
The issue was in fact that a `.public` **directory** has been created instead of a `.public` **file** inside a `files` subdirectory, leaving it marked as public inside contao file explorer

Thanks a lot for the quick answers !

**Comment by fritzmg** [comment]
> The issue was in fact that a `.public` **directory** has been created instead of a `.public` **file** inside a `files` subdirectory, leaving it marked as public inside contao file explorer
> 
> Thanks a lot for the quick answers !

See https://github.com/contao/contao/pull/3470
