### ISSUE TITLE
Incorrect french translation [ERR.invalidLogin]

### ISSUE THREAD

**Issue by christianbarkowsky** [contao/contao#3469]
**Affected version(s)**

Contao 4.9 to Contao 4.12

**Description**

Our French customer complains about a translation.

fr/defaukt.xlf >> ERR.invalidLogin

Incorrect:
~~Échec de la connexion (noter que les noms d'utilisateur et mots de passe sont sensibles à la casse) !~~

Correct:
**Échec de la connexion (veuillez noter que les noms d'utilisateur et mots de passe tiennent compte de majuscules et minuscules)!**

**Comment by aschempp** [comment]
Translations are managed on Transifex. https://www.transifex.com/contao/core-bundle/dashboard/
