### ISSUE TITLE
Impossible to write literal value of basic entities

### ISSUE THREAD

**Issue by Toflar** [contao/contao#3471]
**Affected version(s)**

all

**Description**

If I want to literally write e.g. `[-]` or `[lt]` or any other of the "basic entitites", there's absolutely no way I can do this.

**Comment by fritzmg** [comment]
You could write `[[-]-[-]]` or `[[-]lt[-]]`, but that's obviously not ideal 🙈

**Comment by m-vo** [comment]
This will get ugly… As we do not have a defined escape character, the only way to solve this might be to use an insert tag.

**Comment by aschempp** [comment]
How about we add something like `[[-]]` and `[[lt]]`? Apart from the fact that you will not be able to write `[[-]]` then 🤣

**Comment by ausi** [comment]
> the only way to solve this might be to use an insert tag.

This is a great idea I think. We could get rid of the basic entities in Contao 5 then.

**Comment by Toflar** [comment]
@ausi is that cleaned up in 5.x now? 🤔

**Comment by ausi** [comment]
Yes, after #4453 basic entities no longer get replaced, so writing them literal is possible now.
The only exception is input fields with `['eval' => ['basicEntities' => true]]` enabled.
