### ISSUE TITLE
Make list of allowed protocols configurable

### ISSUE THREAD

**Issue by MarkejN** [contao/contao#3473]
One of our customers uses Skype-Links `href="skype:name?call"` on his website, which are now encoded. The only way to allow them is to make this list of allowed protocols configurable, right? What do you think?
https://github.com/contao/contao/blob/a7628093a5710bbbb8f0c97950a70e89f3727ba7/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L874-L876

**Comment by fritzmg** [comment]
I think making it configurable is the way to go. The list of officially registered schemes is pretty long otherwise: https://en.wikipedia.org/wiki/List_of_URI_schemes#Official_IANA-registered_schemes (although many of them likely never make any sense in an HTML context).

**Comment by aschempp** [comment]
even the comment says "disallowed" protocols… shouldn't we just disallow javascript (in HTML)? I can imagine linking to app stores for example, and its a PITA to always configure that?

**Comment by ausi** [comment]
> shouldn't we just disallow javascript (in HTML)?

I don’t know how we could do that technically in the `specialcharsUrl()` method.

Also, there are many more dangerous protocols than just `javascript:`, what about `ssh:`, `telnet:`, `ical:`, `file:`?

**Comment by MarkejN** [comment]
Maybe the default allow list can already be quite long and treated like the default cookie deny list?

**Comment by leofeyer** [comment]
Closing this in favor of #3488.
