### ISSUE TITLE
Route defaults inconsistencies

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3477]
**Affected version(s)**

Contao 4.12

**Description**

https://github.com/contao/contao/blob/4cf0a3ce0b5eeb52a35037648e23b4d29cf8c9de/core-bundle/src/Routing/Route404Provider.php#L158

@ausi Does this need to be wrapped in `LocaleUtil::formatAsLanguageTag()` like in the `PageRoute` class?

https://github.com/contao/contao/blob/4cf0a3ce0b5eeb52a35037648e23b4d29cf8c9de/core-bundle/src/Routing/Page/PageRoute.php#L55

@aschempp Do we need to add `'_canonical_route' => 'tl_page.'.$page->id,` after this line like in the `Route404Provider` class?

**Comment by ausi** [comment]
> Does this need to be wrapped in `LocaleUtil::formatAsLanguageTag()` like in the `PageRoute` class?

I think so, yes. See https://github.com/contao/contao/pull/2305#discussion_r489484461

**Comment by aschempp** [comment]
I think this is actually wrong, `_locale` should be a locale (`_`) and not a language tag (`-`).
https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/pages/PageRegular.php#L80-L84

**Comment by aschempp** [comment]
aah, hmm… maybe it must be a language tag for backwards compatibility with legacy routing (where the locale is used as prefix)? 🤔

**Comment by fritzmg** [comment]
The Symfony Translator needs the locale at least. So having a `messages.de_AT.xlf` currently might not work in Contao, since Contao would set the language for the Translator to `de-AT`.

**Comment by leofeyer** [comment]
BTW, the `_canonical_route` feature from #3441 does no longer seem to work in Contao 4.12:

<img width="500" alt="" src="https://user-images.githubusercontent.com/1192057/133747644-92c822f1-24f7-486c-8ab5-0ddc8c58a4ba.png">

<img width="267" alt="" src="https://user-images.githubusercontent.com/1192057/133747676-4b041fcb-a156-4c1f-b5c1-a987a4600333.png">

**Comment by leofeyer** [comment]
This has already been fixed in #3506.
