### ISSUE TITLE
invalid characters break insert tag replacement

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#349]
**Affected version(s)**
4.4.34, probably 4.7.0 too

**Description**
If the `preg_replace` for insert tag replacement

https://github.com/contao/contao/blob/51f3d79ae100d91423c89c5e7338c0d56b63692d/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L78

gets fed with an invalid character _somewhere_ in `$strBuffer`, no insert tag will be matched, and thus potentially _no_ insert tags will be replaced on the page. Instead they will be shown as they are.

This is because of the `u` flag, that was introduced in https://github.com/contao/contao/commit/70a1403a5e05403cad11538d2c5e9c015b76094e

@leofeyer is there a specific reason for adding this flag? Otherwise it can simply be removed to fix the issue.

**How to reproduce**

This is a little more difficult. The test case involved a site which contained characters in the database that were not encoded as UTF-8. This itself is not yet a problem. The issue manifests itself on the search result page of the search module. The search module was cutting of a word in the middle of a non-UTF-8 character, which produced the invalid output. So if the original search result context contained the word `erschlieÃ¼en` (erschließen with the `ß` encoded in a different character set), the search result module was clipping the content right in between the invalid character resulting in
```html
<p class="context">... erschlieÃ</p>
```

/cc @ausi

**Comment by ausi** [comment]
If we want to support unicode characters at the beginning of insert tags (as we currently do) the regex should be `/{{([a-zA-Z0-9\x80-\xFF][^{}]*)}}/` IMO. Otherwise we could use `/{{([a-zA-Z0-9][^{}]*)}}/`

**Comment by leofeyer** [comment]
Fixed in de8245278ddb34c77f65108278a01db7abc2f723. Thank you @ausi.
