### ISSUE TITLE
contao-console security:hash-secret

### ISSUE THREAD

**Issue by katgirl** [contao/contao#3490]
It would be nice if you could also create the hash of the secret with the ```contao-console```.

So instead
``` vendor / bin / contao-console security: hash-password ```

something like that
``` vendor / bin / contao-console security: hash-secret ```

see: ```Base32::encodeUpperUnpadded```

**Comment by fritzmg** [comment]
Wouldn't that be more of a Symfony feature request then? `security:encode-password` comes from `symfony/security-bundle`, not `contao/core-bundle`.

**Comment by katgirl** [comment]
not password, i meen the seceret of OTP. This is a string(128) 

```php
use OTPHP\TOTP;
use ParagonIE\ConstantTime\Base32;

mt_srand(1);

$secret = '';

while (\strlen($secret) < 128) {
    $secret .= \chr(mt_rand() % 256);
}

var_dump ($secret) . PHP_EOL;

echo Base32::encodeUpperUnpadded($secret);

```
see: https://github.com/contao/contao/blob/ef97b65f6965e78c8cf6a824dbcd0dc28e9e4f72/core-bundle/src/Controller/FrontendModule/TwoFactorController.php#L163

I need this reverse to set a string to Database, like that

```php
// example not work!!!!!!


$secret_base32 = '5GIFNE3XVX4ZSAYEXPS6RUJHWHI3KLP7N5EFAPG4H';

$secret = Base32::decode($secret_base32, 128); // to write to Database

```
see: https://github.com/contao/contao/blob/ef97b65f6965e78c8cf6a824dbcd0dc28e9e4f72/core-bundle/src/Resources/contao/dca/tl_user.php#L439-L443
