### ISSUE TITLE
Folder name "0" is not displayed

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3493]
**Affected version(s)**

Contao 4.9+

**Description**

<img width="493" alt="" src="https://user-images.githubusercontent.com/1192057/134545347-a559bd49-4300-420a-98bd-a5d9fc721324.png">

<img width="440" alt="" src="https://user-images.githubusercontent.com/1192057/134545324-f73f1dbd-dbb1-4ce2-89e4-bbe1eea8ff8b.png">

**Comment by SeverinGloeckle** [comment]
This is because there is a loose check in `StringUtil`:

https://github.com/contao/contao/blob/27c55df2b5a9607b780a602ef92ecaaeb312cb1d/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L918-L923

**Comment by leofeyer** [comment]
@SeverinGloeckle Thank you for debugging this one. 👍
