### ISSUE TITLE
Options are not sorted correctly when starting with a non ASCII character

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3494]
**Affected version(s)**

Contao 4.9+

**Description**

<img width="183" alt="" src="https://user-images.githubusercontent.com/1192057/134545663-1ffafd18-20d0-48f5-8640-a1ab755de15a.png">

**Comment by SeverinGloeckle** [comment]
What options are we looking at here?

**Comment by fritzmg** [comment]
Any `options` in the DCA presumably.

**Comment by leofeyer** [comment]
The screenshot shows the filter menu in the back end. Sorry for not mentioning that right away.
