### ISSUE TITLE
Impossible to mock classes extending `Contao\System` with Mockery due to TL_MODE parameter default

### ISSUE THREAD

**Issue by SeverinGloeckle** [contao/contao#3495]
**Affected version(s)**

Contao 4.9 and up

**Description**
It is currently not possible to mock a class that extends from `Contao\System` with Mockery (...) due to the usage of `TL_MODE` as a default parameter value in `getMessages`:

````php
/**
 * Return all messages as HTML
 *
 * @param string $strScope An optional message scope
 *
 * @return string The messages HTML markup
 *
 * @deprecated Deprecated since Contao 4.0, to be removed in Contao 5.0.
 *             Use Message::generate() instead.
 */
protected function getMessages($strScope=TL_MODE)
{
  @trigger_error('Using System::getMessages() has been deprecated and will no longer work in Contao 5.0. Use Message::generate() instead.', E_USER_DEPRECATED);

  return Message::generate($strScope);
}
````

Since there is no constant `TL_MODE` in the test environment, this throws an exception:

````php
Mockery::mock(Widget::class);

// Throws: Use of undefined constant TL_MODE - assumed 'TL_MODE' (this will throw an Error in a future version of PHP)
````

This is because Mockery by default is creating `MethodDefinitions` for all methods on a mocked class.

It would be nice if the legacy Contao classes would be mockable via Mockery. 

**Fix**
The fix is simple by moving the parameter default into the method body - or in this case even simpler by removing the default value altogether since it is set in `Message::generate()` again, which is the only thing called within `System::getMessages()`.

````php
protected function getMessages($strScope=null)
{
  // Not really necessary, since $strScope = null will be set to TL_MODE in Message::generate().
  $strScope = $strScope ?? TL_MODE;

  trigger_deprecation('contao/core-bundle', '4.0', 'Using "Contao\System::getMessages()" has been deprecated and will no longer work in Contao 5.0. Use "Contao\Message::generate()" instead.');

  return Message::generate($strScope);
}
````

Note:
This seems to be the only case besides `Contao\Messages` where a legacy constant is used as a default parameter value.

If we agree that the default value can be dropped, I can submit a pull request. 
I'd suggest to target Contao 4.9.

**Comment by ausi** [comment]
I’m happy with removing `TL_MODE` from the attributes as long as it is backwards compatible. Which I think it is in this case because calling `getMessages(null)` in the current version didn’t work so it should be OK to change this behavior.

**Comment by leofeyer** [comment]
Agreed.

**Comment by SeverinGloeckle** [comment]
> ...because calling `getMessages(null)` in the current version didn’t work

If the `ContaoFramework` is initialized and thus `TL_MODE` is defined, `getMessages(null)` has been working and will also work with `$strScope=null` instead of `$strScope=TL_MODE`. 

In both cases  there is a fallback to `TL_SCOPE` - just that with `$strScope=TL_MODE` the fallback is done by `Message::generate()`:

https://github.com/contao/contao/blob/c88eddcf7eb71916036512d21ebbe53dfdcb1eed/core-bundle/src/Resources/contao/library/Contao/Message.php#L116-L126

**Comment by ausi** [comment]
I don’t see how `Message::generate(null)` falls back to `TL_MODE`, but either way the change is backwards compatbile so everything is fine IMO ☺️

**Comment by SeverinGloeckle** [comment]
You are right, my bad. 

I fully understand your initial comment now: Since `getMessages(null)` wasn't working correctly before (e.g. using session keys like `contao..error` since there is no TL_MODE), it is alright to change this behaviour to use the current `TL_MODE` in this case.

The inline fallback `$strScope = $strScope ?? TL_MODE;` is actually necessary in this case to keep `getMessages()` working without a parameter.
