### ISSUE TITLE
Use `utf8mb4` as default charset for MySQL

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#35]
To fully support Unicode in MySQL, we should use `utf8mb4` as the default charset (see contao/core#7140). However, this would effectively raise the system requirements to MySQL 5.5.3+.

@contao/developers Is this something that we should consider in Contao 4? I don't know how many hosting companies are still running MySQL 5.0 or 5.1? The ones I know have MySQL 5.5 (or MariaDB).

**Comment by leofeyer** [comment]
Changed in contao/core-bundle@7de04f35c52916a3519aaee45b73fe696c0dbb00.

**Comment by aschempp** [comment]
Won't this make existing databases incompatible?

**Comment by leofeyer** [comment]
Hm, you could have a point here. The change does not touch the database, but it will set the default charset of the DB connection to `utf8mb4`. @contao/developers What do you think?

**Comment by ausi** [comment]
AFAIK `utf8mb4` should be completely backwards compatible with `utf8`. The [MySQL-Documentation](http://dev.mysql.com/doc/refman/5.7/en/charset-unicode-utf8mb4.html) says „You need not worry about converting characters or losing data when upgrading utf8 data from older versions of MySQL“. Also, comparison and string functions should work correct with `utf8` and `utf8mb4` mixed.

One thing I noticed in an other project when upgrading from `utf8` to `utf8mb4` was longer index keys, 4 bytes per character instead of 3. A `UNIQUE INDEX (something(255))` [might be too long](http://stackoverflow.com/questions/6172798). But this should only be a problem if you actually change the charset of the table or column.

**Comment by leofeyer** [comment]
@ausi Does this problem only occur for unique indices?

**Comment by ausi** [comment]
The maximum length for non-unique indices is the same, which is 1000 bytes resp. 250 characters for MyISAM. But if you change the charset, the index length is automatically set to the maximum (250) without an error. I also tested it with different SQL modes, so this shouldn’t be a problem.

Do we also want to change the storage engine from MyISAM to InnoDB in Contao 4?

**Comment by Toflar** [comment]
> Do we also want to change the storage engine from MyISAM to InnoDB in Contao 4?

Not sure about BC but we should definitely get rid of MyISAM, it's a pain!

**Comment by ausi** [comment]
From [mysql.com](http://dev.mysql.com/doc/refman/5.6/en/fulltext-restrictions.html): „FULLTEXT index support for InnoDB tables requires MySQL 5.6.4 or higher.“

AFAIR fulltext index is used in `tl_search`

**Comment by ausi** [comment]
> Not sure about BC but we should definitely get rid of MyISAM, it's a pain!

I’d also vote for InnoDB

**Comment by aschempp** [comment]
We should definitely check out InnoDB options!

**Comment by leofeyer** [comment]
Switching to InnoDB (which I'd greatly appreciate) would also imply to modify the `DC_Table` driver. InnoDB supports foreign keys to maintain [referential integrity](http://www.peterkropff.de/site/mysql/referenzaktion.htm), so the driver should no longer try to simulate this.

**Comment by Toflar** [comment]
Exactly, but it does not hurt if it tries to. We can remove that later :)

**Comment by leofeyer** [comment]
Not sure about that. Might throw an exception if the record gets removed by the DB before the driver has finished its routines.

**Comment by Toflar** [comment]
Which only happens when constraints are defined. And this is not the case yet :) I mean, obviously we cannot go for InnoDB and use all its features from day one. But we can at least make sure all users use InnoDB from Contao 4 on and then safely use the features of it in the future :)

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/113.
