### ISSUE TITLE
jumpTo Abhängigkeit der Einstellung bei Modul und Mitgliedergruppe

### ISSUE THREAD

**Issue by zonky2** [contao/contao#3502]
Weder im Forum noch in Slack gab es zur folgenden Frage eine Reaktion/Antwort:

1.) Ich habe zwei Mitgliedergruppen mit entsprechenden Mitgliedern (ist scharf getrennt: entweder/oder) und ich habe eine Loginseite. Wenn sich jemand einloggt, soll dieser direkt auf einer Seite in dem Bereich seiner Mitgliedergruppe landen - dazu habe ich bei der Mitgliedergruppe jeweils eine Weiterleitungsseite eingerichtet. ... funktioniert!

2.) Ich habe eine 401-Seite (Zugruiff verweigert), wenn jemand einen direkten Link zu einer geschützten Mitgliederbereich öffnen möchte - auf der Seite ist ein anderes Loginmodul mit gesetzter Checkbox "Zur zuletzt besuchten Seite". Wenn ich mich hier einlogge, komme ich dennoch auf die eingestellte Startseite aus meiner verknüpften Mitgliedergruppe.

Im Quelltext habe ich nicht entdecken können, wo der Wert für "redirectBack" mit dem aus der Mitgliedergruppe "jumpTo" überschrieben wird. **M.E. müsste bei Checkbox "Zur zuletzt besuchten Seite" die Mitgliedergruppe nicht mehr ausgewertet werden bzw. hier sollte eine neue Option zur Steuerung dessen hin.**

Oder habe ich was übersehen?

**Comment by fritzmg** [comment]
iirc the member redirect group will always override any other redirect setting. Though I could not figure out as well where this redirect is actually set when I had a quick look 🤔

**Comment by zonky2** [comment]
I would try to make a PR or my own module - but i can't find where to put the lever .... hmm??

**Comment by zonky2** [comment]
If I see this correctly, the query would have to be skipped via the module

https://github.com/inspiredminds/contao-facebook-login/blob/5acac2878a32d1b09d3ea9e58903342424a6b08a/src/FacebookLoginBundle/Controller/CallbackController.php#L272-L276
