### ISSUE TITLE
DebugPagesCommand handles legacy page types only

### ISSUE THREAD

**Issue by SeverinGloeckle** [contao/contao#3505]
**Affected version(s)**

Contao 4.11 and up

**Description**
The command `contao-console debug:pages` only shows pages registered in `$GLOBALS['TL_PTY']`:

https://github.com/contao/contao/blob/c88eddcf7eb71916036512d21ebbe53dfdcb1eed/core-bundle/src/Command/DebugPagesCommand.php#L71

**Expected behaviour**
It should show custom page types from the `PageRegistry` as well.

**Possible fix**
If the expected behaviour is correct, I can submit a fix and maybe add a unit-test for `DebugPagesCommand`.

**Comment by aschempp** [comment]
This certainly is a bug! We should get the types from the registry as well, same as we do in the PageTypeOptionsCallback
