### ISSUE TITLE
Page setting requires item leads to 404 error with url suffix /

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#3531]
**Affected version(s)**

Contao 4.9 and Contao 4.12

**Description**

I have a root page setting with the url suffix `/`. If I activate the `requiresItem` setting on a sub page, I get a page not found error. As far as I debugged it's caused by the routing system.

1. The url matcher alsways makes the trailing slash optional https://github.com/symfony/routing/blob/be865017746fe869007d94220ad3f5297951811b/Matcher/UrlMatcher.php#L150-L151
2. This leads to a `parameters` default containing the trailing slash
3. The input enhancer detects 2 empty fragments now and fails to register the auto item: https://github.com/contao/contao/blob/d2dd362bf0d751d85aa0136c27da4b2ee88c1557/core-bundle/src/Routing/Enhancer/InputEnhancer.php#L59

**Possible fix**

Disallowing a trailing slash as last value for the parameters, with following regex `/.+[^/]` solves the issue. Maybe it should only be applied if the url suffix is set to an trailing slash.

https://github.com/contao/contao/blob/d2dd362bf0d751d85aa0136c27da4b2ee88c1557/core-bundle/src/Routing/Page/PageRegistry.php#L65

/cc @aschempp @frontendschlampe

**Comment by aschempp** [comment]
what does your URL look like?

**Comment by dmolineus** [comment]
> what does your URL look like?

`https://example.org/news/details/just-an-example/`

**Comment by asaage** [comment]
I think it's not just url suffix ```/``` but also folder-url's which play a role here.

**Comment by aschempp** [comment]
This should be fixed by https://github.com/contao/contao/pull/2690 (Contao 4.10.7) and therefore in Contao 4.12. It looks like it hasn't been backported (https://github.com/contao/contao/blob/4.9/core-bundle/src/Routing/RouteProvider.php#L243), can you try if the changes in #2690 would fix your Contao 4.9 ?

**Comment by richardhj** [comment]
Hey 👋
I just want to add that the News pages in the Contao demo currently are not accessible (see footer navigation under https://demo.contao.org/en/).
Might be fixed by #3540?

**Comment by aschempp** [comment]
> Hey 👋
> I just want to add that the News pages in the Contao demo currently are not accessible (see footer navigation under https://demo.contao.org/en/).
> Might be fixed by #3540?

This is unrelated, the news detail page in the demo has an archive module that renders the reader, which means it requires/allows to not have an item in the URL. The error is caused by the `News - News archive menu` module which has the detail page set as target page.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4105 and https://github.com/contao/contao/pull/4106 for the fixes in Contao 4.9 and 4.12
