### ISSUE TITLE
Croatian and Romanian language abbreviations are not recognized correctly

### ISSUE THREAD

**Issue by GMTeams** [contao/contao#3533]
**Affected version(s)**

Contao 4.9.x-dev

**Description**

In the site structure, I can fill in the language abbreviations "ro" (Romanian) and "hr" (Croatian) from ISO Standard 639-1.
![image](https://user-images.githubusercontent.com/28180274/135631719-657a5fa8-f765-4536-90f7-cb4e7d6c1f68.png)

In the file management, when you edit meta data of an image, all languages occur in their full notation, e.g. "Französisch - Français" - except Croatian and Romanian, they show the  abbreviations.

![image](https://user-images.githubusercontent.com/28180274/135633303-51a8568f-e234-49ce-b23c-67f96c373057.png)

The following languages (abbreviations) do not have the problem:
- de
- en
- fr
- nl
- sl
- sv
- cs
- it

**Comment by fritzmg** [comment]
I can confirm the issue in `4.9.x-dev`.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/3534
