### ISSUE TITLE
Error when calculating maxPaginationLinks if number is even

### ISSUE THREAD

**Issue by zonky2** [contao/contao#3539]
the default setting of maxPaginationLinks with 7 is an odd number - here the output is correct and we see 7 links

you can change the setting (Contao 4.9.20) e.g.
```
contao:
  localconfig:
    maxPaginationLinks: 4
```
then the display is as follows

![FireShot Pro Webpage Screenshot #618 - 'News   Newsletter - GUTcert' - www gut-cert de](https://user-images.githubusercontent.com/1045318/135765615-5d2541cc-b235-4ef7-8aa1-2f972c587ed3.jpg)

so one too many

with maxPaginationLinks 2 then 3 or maxPaginationLinks 8 then 9

I do not understand the calculation at this point :(
https://github.com/contao/contao/blob/dccba73da017cdffe74d0604ec67e6f8d4fbf137/core-bundle/src/Resources/contao/library/Contao/Pagination.php#L333

**Comment by SeverinGloeckle** [comment]
I can confirm this bug in the pagination: If you set `maxPaginationLinks` to an even number, the pagination generates one more item than set in the value.

The pagination logic tries to split up the links to add an equal padding before and after the current page (that's what the `floor($this->intNumberOfLinks / 2)` is used for). So for example on page 4 with a maximum number of 5 links, the pagination generates:

> 2 | 3 | **4** | 5 | 6

However, the current logic is flawed for even numbers which – together with the current page – result in an uneven number after an even division. For a maximum of 4 links, the same pagination as above will be generated.

**Fix**
The solution is to improve the calculation of the number of padded links to allow an uneven distribution of the available links (with a bias to add one more link after the current page).

I will provide a fix.

**Comment by zonky2** [comment]
> The pagination logic tries to split up the links to add an equal padding before and after the current page (that's what the floor($this->intNumberOfLinks / 2) is used for). 

o.k. - understood...

on closer inspection, the display is wrong for odd numbers. The active page number has no linking and would have to be calculated out of the number - i.e. `maxPaginationLinks` 7 generates 6 links... or the variable should be called `maxPaginationItems` (or similar).

**Comment by SeverinGloeckle** [comment]
You are right, the naming could be improved. That's something to keep in mind for Contao 5.

**Comment by aschempp** [comment]
Closed in favor of #3548
