### ISSUE TITLE
Contao 4 Front-end: Please help me auto log-in Just after the user registration

### ISSUE THREAD

**Issue by masudewucse** [contao/contao#3541]
I have the registration form in Contao 4 front-end. Registration is working good with disabling the user and activating the user after the email URL click. 
What I want is, **user will be enabled and automatically log in just after the registration**.
I found a package (terminal42/contao-autoregistration) but did not work for my contao 4.11 version. 
I would be glad to have some support.

**Comment by fritzmg** [comment]
> I found a package (terminal42/contao-autoregistration) but did not work for my contao 4.11 version.

That's the recommended extension. What exactly did not work?

**Comment by masudewucse** [comment]
> > I found a package (terminal42/contao-autoregistration) but did not work for my Contao 4.11 version.
> 
> That's the recommended extension. What exactly did not work?


I installed the package and did run the migration. 3 new entities have been created for tl_page table. 
but I could not find the checkboxes on the (root)page (contao backend) where I called the member registration module.  so I manually set 1 (enabled) to all 3 entities in the database. 

After I fill in all the info (email, username & password) and click on Register would just refresh the page and does not say anything. 
(yes it does create an entry on the tl:_member table with disabled = 1) 

Please help.

**Comment by fritzmg** [comment]
You need to enable the feature in your website root's settings. There will be a new section called "Member Registration".

Btw. these kinds of questions are more suited for either the issue tracker of the extension - or the community forum or community slack.
