### ISSUE TITLE
Behaviour of submitOnChange

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#3547]
When toggling a field which has `submitOnChange` set, the record gets updated without creating a new version or adding any entry to `tl_log` - this can lead to some confusion...

**Story:**
We just ran into the problem that the site of a customer has been offline due to the root page not having assigned a layout anymore. Looking through the logs we saw nothing that could've explained how this happened. The customer sweared he didn't do anything and we knew for sure we did nothing so how did this happen?

I know how `submitOnChange` works and that a new version is only created once the user actually saves a modified record but having had this situation begs the question if the Core should at least create a new entry in the `System log` so one can understand what happened and why.

This isn't about blaming anyone for doing something wrong rather than making sure the change was done by someone privileged to do so instead of an unknown third party which might have gained access otherwise.

**Comment by aschempp** [comment]
I think this has been discussed before and is a known limitation / open issue, did you check the other issues?

**Comment by bennyborn** [comment]
#3246 seems to be about something different if you meant this one.

**Comment by leofeyer** [comment]
Indeed, if there is an auto submit **checkbox** that loads a sub-palette via Ajax, no log entry is generated. Only auto submit **select menus** that reload the page also generate log entries.

**Comment by aschempp** [comment]
most likely because a select does a reload but a checkbox loads with ajax 🙄

**Comment by bennyborn** [comment]
bump
