### ISSUE TITLE
Strukturierte Daten "@context": "https:\/\/schema.contao.org",

### ISSUE THREAD

**Issue by jonnysp** [contao/contao#3555]
nach Update auf 4.12.2 habe ich fehler in  "jsonLdScripts"
Sowol der https://search.google.com/test/rich-results als auch 
https://validator.schema.org/

<script type="application/ld+json">
[
    {
        "@context": "https:\/\/schema.org",
        "@graph": [
            {
                "@type": "WebPage"
            }
        ]
    },
    {
        "@context": "https:\/\/schema.contao.org",
        "@graph": [
            {
                "@type": "Page",
                "fePreview": false,
                "groups": [],
                "noSearch": false,
                "pageId": 3,
                "protected": false,
                "title": "Willkommen"
            }
        ]
    }
]
</script>
![grafik](https://user-images.githubusercontent.com/1651241/136335349-9b271181-723c-4769-a792-f6c3b67a636a.png)
![grafik](https://user-images.githubusercontent.com/1651241/136335408-170630c7-1b60-42c5-89dd-5927713d9d71.png)

**Comment by fritzmg** [comment]
This is an error in the validator. See https://github.com/schemaorg/schemaorg/issues/2921#issuecomment-879817283

**Comment by jonnysp** [comment]
und warum bekomme ich auch Fehler in der Google Serarch Konsole?
![grafik](https://user-images.githubusercontent.com/1651241/136336309-288953c1-2210-4d5d-9de3-5665cfcce856.png)

**Comment by ausi** [comment]
> und warum bekomme ich auch Fehler in der Google Serarch Konsole?

Für die Search-Console bitte folgendermaßen vorgehen: https://community.contao.org/de/showthread.php?81498-Google-Search-Console-Fehler-quot-Falscher-Werttyp-quot-context-quot&p=550086&viewfull=1#post550086

**Comment by jonnysp** [comment]
danke.
