### ISSUE TITLE
Error on saving root page when using files and assets url

### ISSUE THREAD

**Issue by ReneLuecking** [contao/contao#3556]
**Affected version(s)**

Contao 4.12

**Description**

When using the files url (= `tl_page.staticFiles`) and the assets url (= `tl_page.staticPlugins`) you have to enter these including http(s) because of `'rgxp'=>HttpUrlListener::RGXP_NAME` in [`tl_page.php:368`](https://github.com/contao/contao/blob/4.12/core-bundle/src/Resources/contao/dca/tl_page.php#L368). After checking the entered url the callback [`tl_page::checkStaticUrl`](https://github.com/contao/contao/blob/4.12/core-bundle/src/Resources/contao/dca/tl_page.php#L368) gets called which removes the http(s) before saving it into the database. Therefore everytime I try to save the root page, even if I did not change the files/assets url, I have to manually add http(s) again to fit the url check only for contao removing it afterwards.

It seems like an easy solution to just remove the callback `tl_page::checkStaticUrl` but I don't know if this may cause other problems.

**Comment by fritzmg** [comment]
The changes made to `tl_page.staticFiles` and `tl_page.staticPlugins` in https://github.com/contao/contao/pull/2704 need to be reverted, as these fields do not in fact expect an absolute URL - only a domain.

**Comment by leofeyer** [comment]
But the field had `'rgxp'=>'url'` before, so how can the changes from #2704 break this?

**Comment by fritzmg** [comment]
> But the field had `'rgxp'=>'url'` before, so how can the changes from #2704 break this?

Yes, it had `url` before, which allows non-absolute URLs and only really checks for invalid URL characters otherwise. We must not use `HttpUrlListener::RGXP_NAME` here, as only a domain must be entered, without the scheme (the scheme is automatically removed by the save callback).
