### ISSUE TITLE
Theme path with _ is not working

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#3558]
**Affected version(s)**

Contao 4.12

**Description**
Using template directories with an underscore (e.g. test_v2) create an error. Updating existing sites with this folders disables this site. Frontend is crashing. Choosing directories in theme setting don´t allow folders with "_".

<img width="896" alt="Bildschirmfoto 2021-10-07 um 13 04 01" src="https://user-images.githubusercontent.com/6390770/136372409-fe94a14c-a029-422a-b251-eb2ba85d689f.png">

Logfile

`[2021-10-06T20:13:39.524102+02:00] request.CRITICAL: Uncaught PHP Exception Contao\CoreBundle\Exception\InvalidThemePathExcept ion: "The theme path "test_v2" contains one or more invalid characters: "_"" at /homepages/46/11111/htdocs/xxx-dev/vendor/contao/core-bundle/src/Twig/Loader/ThemeNamespace.php line 52 {"exception":"[object] (Contao\\CoreBundle\\Exception\\InvalidThemePathEx ception(code: 0): The theme path "test_v2" contains one or more invalid characters: "_" at /homepages/46/11111/htdocs/xxxx-dev/vendor/contao/core-bundle/src/Twig/Loader/ThemeNamespace.php:52)"} []
`

**Comment by m-vo** [comment]
That is correct. You cannot use underscores in theme folder names. Use hyphens instead.

**Comment by Kahmoon** [comment]
On a fresh installation no problem but i updated one which had projectxy_v2 since 2 years and the site was offline afterwards :-). I did not check to simple rename this folder. I will probably wait with updating live system until this gets fixed in 4.12.3!? :-)

**Comment by fritzmg** [comment]
> That is correct. You cannot use underscores in theme folder names. Use hyphens instead.

But this breaks any website that updates to Contao 4.12 and already uses an underscore in the theme folder.

**Comment by m-vo** [comment]
No it should not. Only if you try to save the record - but even then the exception should prevent saving?

**Comment by m-vo** [comment]
for reference, see https://github.com/contao/contao/issues/3354#issuecomment-903095184 and  https://github.com/contao/contao/pull/3414

**Comment by Kahmoon** [comment]
I did not check the theme settings in first place and the site was broken straigth after updating. After i figured out the logfile, i tried to resave theme settings, which was not possible.

**Comment by m-vo** [comment]
Interesting. Does the log contain a stack trace?

**Comment by Kahmoon** [comment]
I went back to 4.12.1 but i will update it again. What exactly do you need?

**Comment by m-vo** [comment]
I think I already know the problem… :see_no_evil:

**Comment by m-vo** [comment]
Could you by any chance check if altering the `getThemeSlug()` (L433) method in `ContaoFilesystemLoader` to the following solves the problem? 

```php
    /**
     * Returns and stores the current theme slug or false if not applicable.
     *
     * @return string|false
     */
    private function getThemeSlug()
    {
        if (null === ($page = $GLOBALS['objPage'] ?? null) || null === ($path = $page->templateGroup)) {
            return $this->currentThemeSlug = false;
        }

        try {
            $slug = $this->themeNamespace->generateSlug(Path::makeRelative($path, 'templates'));
        } catch (\Contao\CoreBundle\Exception\InvalidThemePathException $e) {
            $slug = false;
        }

        return $this->currentThemeSlug = $slug;
    }
```

You may need to rebuild your container cache afterwards.

**Comment by Kahmoon** [comment]
Sure. Which folder is this file?

**Comment by m-vo** [comment]
It's lives under `vendor/contao/core-bundle/src/Twig/Loader`. 

https://github.com/contao/contao/blob/4.12/core-bundle/src/Twig/Loader/ContaoFilesystemLoader.php

**Comment by Kahmoon** [comment]
Jepp, error is gone. Frontend is working again but i still cannot save the theme.
<img width="893" alt="Bildschirmfoto 2021-10-07 um 13 51 37" src="https://user-images.githubusercontent.com/6390770/136378783-d65ad54d-1606-4b9e-9f3a-57b810e907db.png">

**Comment by m-vo** [comment]
> Jepp, error is gone. Site is working again but i still cannot save the theme.

Thank you very much for testing. This is the intended behavior now - we do not want to allow theme folders with `_` in their name because that would make our Twig theme namespaces dambiguous (`_` is used to separate namespace parts). 

People using such theme folder names should migrate but things should not start failing out of a sudden of course. :slightly_smiling_face:

**Comment by Kahmoon** [comment]
OK, i just renamed it from jbz_v2 in jbz-v2 and its fine.

**Comment by m-vo** [comment]
see #3559
