### ISSUE TITLE
Newsletter: HTML output is broken

### ISSUE THREAD

**Issue by Mediazept** [contao/contao#3562]
**Affected version(s)**

Contao 4.9.21

**Description and how to reproduce**

Create a new newsletter and enter text into the HTML field. Source code in TinyMCE looks fine, but the output is broken. HTML is not interpreted, tags are rendered as normal text element.
The error can be reproduced with the Contao demo install (see screenshots).
![image](https://user-images.githubusercontent.com/1333429/136454090-4c593471-b99f-43ef-9d66-fe40d7dbe840.png)
![image](https://user-images.githubusercontent.com/1333429/136454132-b995d781-746a-4a39-801a-9b7aa4b1aec4.png)
![image](https://user-images.githubusercontent.com/1333429/136454156-b6182445-9e66-4536-bdb7-2fd149071978.png)

**Comment by ausi** [comment]
This is most probably caused by #3513

@Mediazept can you please test if creating the file *contao/dca/tl_newsletter.php* with the following content fixes the issue?

```php
<?php
$GLOBALS['TL_DCA']['tl_newsletter']['fields']['content']['eval']['allowHtml'] = true;
```

**Comment by Mediazept** [comment]
Thanks for your quick response and providing a workaround. I can confirm that your suggested DCA setting fixes the bug.
