### ISSUE TITLE
User specific translations of system messages don't work anymore

### ISSUE THREAD

**Issue by jochi44** [contao/contao#3564]
>Affected version: 4.12.2

It seems that translations done in user specific xlf-files are not shown in the frontend anymore.

Example:
I created a file `default.xlf` in `/app/Resources/contao/languages/de` with the following content (translation):

```
<?xml version="1.0" ?><xliff version="1.1">
  <file datatype="php" original="src/Resources/contao/languages/en/default.php" source-language="en" target-language="de">
    <body>
      <trans-unit id="MSC.lastLogin.1">
        <source>Your previous login was %s. Welcome back!</source>
        <target>Deine letzte Anmeldung war am %s.<br>Willkommen zurück!</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

I then renewed the prod-cache in the contao manager.
Result: The corresponding text is still shown as "Ihre letzte Anmeldung war...".
I'm almost shure that the behaviour was correct in Contao V4.12.1.

**Comment by fritzmg** [comment]
The correction location would be `contao/langauges/de` (unless you are still using `app/config/` for example).

**Comment by jochi44** [comment]
Thank you @fritzmg!
It was my fault because I entered a `<br>` in the translation.
The contao manager showed an error when renewing the prod cache regarding this (which I overlooked 🤦‍♂️).

**Comment by aschempp** [comment]
Just as a side note, the old locations (`app/Resources`) still work as well, so that shouldn't have been the problem anyway 🙃
