### ISSUE TITLE
Clearing the dev cache leads to "MemoryTokenStorage must not be accessed before it was initialized"

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3567]
**Affected version(s)**

Contao 4.12.2

**Description**

If you clear the application cache while being logged into the back end and then refresh the back end again in your browser, the following exception occurs:

```
LogicException:
MemoryTokenStorage must not be accessed before it was initialized.

  at vendor\contao\core-bundle\src\Csrf\MemoryTokenStorage.php:101
  at Contao\CoreBundle\Csrf\MemoryTokenStorage->assertInitialized()
     (vendor\contao\core-bundle\src\Csrf\MemoryTokenStorage.php:54)
  at Contao\CoreBundle\Csrf\MemoryTokenStorage->hasToken('contao_csrf_token')
     (vendor\symfony\security-csrf\CsrfTokenManager.php:72)
  at Symfony\Component\Security\Csrf\CsrfTokenManager->getToken('contao_csrf_token')
     (vendor\contao\core-bundle\src\Resources\contao\library\Contao\RequestToken.php:57)
  at Contao\RequestToken::get()
     (vendor\contao\core-bundle\src\Framework\Adapter.php:44)
  at Contao\CoreBundle\Framework\Adapter->__call('get', array())
     (vendor\contao\core-bundle\src\Framework\ContaoFramework.php:429)
  at Contao\CoreBundle\Framework\ContaoFramework->handleRequestToken()
     (vendor\contao\core-bundle\src\Framework\ContaoFramework.php:311)
  at Contao\CoreBundle\Framework\ContaoFramework->initializeFramework()
     (vendor\contao\core-bundle\src\Framework\ContaoFramework.php:158)
  at Contao\CoreBundle\Framework\ContaoFramework->initialize()
     (vendor\contao\core-bundle\src\Twig\Loader\TemplateLocator.php:67)
  at Contao\CoreBundle\Twig\Loader\TemplateLocator->findThemeDirectories()
     (vendor\contao\core-bundle\src\Twig\Loader\ContaoFilesystemLoaderWarmer.php:55)
  at Contao\CoreBundle\Twig\Loader\ContaoFilesystemLoaderWarmer->warmUp('var/cache/dev')
     (vendor\symfony\http-kernel\CacheWarmer\CacheWarmerAggregate.php:98)
  at Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('var/cache/dev')
     (vendor\symfony\http-kernel\Kernel.php:584)
  at Symfony\Component\HttpKernel\Kernel->initializeContainer()
     (vendor\contao\manager-bundle\src\HttpKernel\ContaoKernel.php:323)
  at Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer()
     (vendor\symfony\http-kernel\Kernel.php:786)
  at Symfony\Component\HttpKernel\Kernel->preBoot()
     (vendor\symfony\http-kernel\Kernel.php:187)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web\index.php:31)
  at require('web/index.php')
     (web\app.php:4)
```

**Reproduction**

1. Use `APP_ENV=dev` in your `.env.local`.
2. Log into the Contao back end.
3. Execute the following to clear the cache: `vendor/bin/contao-console cache:clear --no-warmup --env=dev`.
4. Refresh the Contao back end.

The aforementioned error will occur. However, the next request will be fine again.

Note: the same occurs when using `rm -rf var/cache/dev` - or a combination of both the `cache:clear` command an manually deleting the cache directory.

@m-vo since the `TemplateLocator` shows up in the stack trace, may be a somewhat related issue to #3557  ?

**Comment by m-vo** [comment]
@fritzmg found out that the problem is the `REQUEST_TOKEN` constant which is being set ìn `ContaoFramework#initialize`. The `MemoryTokenStorage` is initialized in a `kernel.request` event, though. In other words: if the framework is booted in a non-request context, this fails.

A workaround for this issue is, well, *not* using the framework. PR is here: #3576

**Comment by fritzmg** [comment]
> In other words: if the framework is booted in a non-request context, this fails.

Well, to be exact: you _can_ boot the framework on the command line. The `REQUEST_TOKEN` constant will then be set to `null`:

https://github.com/contao/contao/blob/e61d504c9fac4e8e46e865b652b550aeed7afa0d/core-bundle/src/Framework/ContaoFramework.php#L376-L385

However, this won't apply if the cache is warmed during the request - then it will fail.

**Comment by aschempp** [comment]
so we can close this with https://github.com/contao/contao/pull/3576 ?

**Comment by m-vo** [comment]
At least the error should be gone. I don't think we can fundamentally fix it as long as the constant exists.
