### ISSUE TITLE
"Access protection" and "Show to guests only" aren't working with modules

### ISSUE THREAD

**Issue by Exotelis** [contao/contao#357]
This might be more a usability improvement than an actual bug.

**Affected version(s)**
Tested with
4.4.36
4.6.12

**Description** 
I tried to hide a module for guests by enabling the access protection option and selecting any member group. This works perfectly fine with elements such as headers, text etc. but not with modules. Unless, I enable the access protection of the element, which includes the module, it will hide it. Despite the fact, that it's still possible to hide modules by protecting the element which loads the module, the module itself should also be protected or the "Access protection" and "Show to guests only" options should be removed from every module!

**How to reproduce**
- Navigate to Themes -> Edit front end modules -> Add module
- Add a Title -> select module Registration -> Select some "Editable fields" -> Enable "Protect module" and select all
- Go to Articles -> Edit the article "Home" of page "Home"
- Add new element and choose the recently created module
- As you can see on the frontend, the module won't be protected

**Comment by asaage** [comment]
That is for usecases where 
**A)** you include modules inside articles
vs
**B)** you include them directly in layout 
if i remember that correctly.

**Comment by Exotelis** [comment]
Good to know, just tested this and yes you are right. Thank you for the clarification
