### ISSUE TITLE
Custom sender mail address in OptInToken

### ISSUE THREAD

**Issue by Xirdion** [contao/contao#3573]
Currently, it is not possible to use a custom sender address when sending an email with the OptIn-Service.
In the `Contao\CoreBundle\OptIn\OptInToken` a new instance of the `Contao\Email`-class is created. Since there is no sender-address, the Email-class uses the administration-email from the settings.

However, sometimes it would be useful to use another email address.
When you are in a multi-domain-system there could be different page-administrators per root page. Sending an email with the OptIn-Service therefore should use the administrator email of the current root page (if there is a root page (frontend)).

There is already the possibility to extend the OptIn-Service in a way that you can add a custom sender address. But you have to copy a lot of code from the original OptInToken-class because the service uses exactly this class.

```php
return new OptInToken($optIn, $this->framework);
```

https://github.com/contao/contao/blob/4.x/core-bundle/src/OptIn/OptIn.php#L61

Would it be possible to add a method to the `OptInToken`-class to set a custom sender address?
Something like:

```php
public function setSender(string $address, ?string $name = null): self
{
    $this->senderAddress = $address;
    if (null !== $name) {
        $this->senderName = $name;
    }

    return $this;
}
```

So it would be possible to set the sender address for the email instance:

```php
/** @var Email $email */
$email = $this->framework->createInstance(Email::class);
$email->subject = $this->model->emailSubject;
$email->text = $this->model->emailText;

if ('' !== $this->senderAddress) {
    $email->from = $this->senderAddress;
}

if ('' !== $this->senderName) {
    $email->fromName = $this->senderName;
}

$email->sendTo($this->model->email);
```

**Comment by fritzmg** [comment]
> When you are in a multi-domain-system there could be different page-administrators per root page. Sending an email with the OptIn-Service therefore should use the administrator email of the current root page (if there is a root page (frontend)).

That should already be the case.

**Comment by Xirdion** [comment]
If there is no sender address given, the Email class just uses the admin e-mail from the settings.

```php
// Add the administrator e-mail as default sender
if (!$this->strSender)
{
    list($this->strSenderName, $this->strSender) = StringUtil::splitFriendlyEmail(Config::get('adminEmail'));
}
```

So this will not use the admin e-mail from the current root page, will it?

**Comment by aschempp** [comment]
looks like a but to me. It should not use the config class but the global variables instead. This might apply to other places where we "incorrectly" migrated.

https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/controllers/FrontendIndex.php#L232-L240

**Comment by fritzmg** [comment]
An `OptInToken` might also be created on the CLI though.
