### ISSUE TITLE
Content Element HTML - change quotes after saving

### ISSUE THREAD

**Issue by berecont** [contao/contao#3575]
**Affected version(s)**

Contao 4.9.21, Contao 4.12.2
I didn't test other versions

Content Element HTML:
`<source src="files/layout/video/css/my_265.mp4" type='video/mp4; codecs="avc1"'> `
after saving the element it changes to:
`<source src="files/layout/video/css/my_265.mp4" type="video/mp4; codecs="avc1"">`
and notes error: Unexpected character after attribute value. Invalid character in attribute name

chanching the quotes and single quotes in their position it will work
`<source src="files/layout/video/css/my_265.mp4" type="video/mp4; codecs='avc1'"> `

**Comment by ausi** [comment]
I would guess that this is a problem in the textarea output. We have to enable double encoding there so that `type="video/mp4; codecs=&quot;avc1&quot;"` gets output correctly in the browser.

**Comment by ausi** [comment]
Tried today to find a fix for this but didn’t succeed 😕

Such problems no longer occur with the restructured input encoding in Contao 5.0, but I don’t know how we can fix this in 4.9 or 4.13.

**Comment by leofeyer** [comment]
Guess it is a known limitation then.
