### ISSUE TITLE
StringUtil::convertEncoding broken?

### ISSUE THREAD

**Issue by blairwinans** [contao/contao#3581]
**Affected version(s)**

Contao 4.12.2

**Description**

I updated several sites from 4.12.1 to 4.12.2 and now any text element that I create will encode the tags improperly and spit them out as text. I have a feeling this may be the culprit? 
 https://github.com/contao/contao/commit/7dc06ebbe7453988c401093827602865a9ffdad3

Steps to reproduce:

1. Create a text element, edit in the tinyMCE editor and save.
2. Output on the frontend will be `<p>My text</p>` because the p-tags are encoded as entities.

When reverting back to 4.12.1, you need to resave the element, and then the text outputted on the frontend will include the correct HTML tags underneath and only display `My text`. 

I thought it may have just been one site, but every site I updated to 4.12.2 has this happening.

**Comment by ausi** [comment]
This is most probably caused by #3513

Should be fixed with #3571

**Comment by blairwinans** [comment]
@ausi Ahh yes. Thanks!
