### ISSUE TITLE
Add warning to enable SQL strict mode for commandline contao-console contao:migrate

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#3584]
Shouldn't `contao-console contao:migrate` correctly display a hint about the MySQL strict mode similar to the install tool?

As discussed in slack, maybe Contao 4.13 should enable strict mode by default.
see: https://contao.slack.com/archives/CJT61P8R1/p1634553592351600?thread_ts=1634552259.350700&cid=CJT61P8R1

**Comment by Toflar** [comment]
@ausi I took the liberty to assign this one to you 🙈

**Comment by ausi** [comment]
As far as I know we did not yet get information about an extension that doesn’t work with the strict mode. Some users had issues with enabling the strict mode, but all of these cases were actual problems or misconfigurations the strict mode uncovered.

So I think we should enable the strict mode by default in Contao 4.13 (also to cause less confusion in the install tool). @contao/developers please vote 👍 👎

**Comment by fritzmg** [comment]
> As far as I know we did not yet get information about an extension that doesn’t work with the strict mode.

I have seen a few in the community and also provided PRs or guidance for these extensions on how to fix it :)

**Comment by aschempp** [comment]
I would prefer to hard-enable this in Contao 5 only and keep the suggestion in Contao 4.

**Comment by leofeyer** [comment]
As discussed at the developer's meeting, we want to enable the strict mode by default and add a setting so users can disable it in case they have to.

**Comment by m-vo** [comment]
See #4042
