### ISSUE TITLE
Revise table removes elements when using the picker

### ISSUE THREAD

**Issue by ausi** [contao/contao#3597]
While debugging #2201 I found out that `reviseTable()` removes new content elements when using the picker.

Without the following line the error disappears: https://github.com/contao/contao/blob/0ba1acd7d93da55598a02fa6963dacf635bdad87/core-bundle/src/Resources/contao/drivers/DC_Table.php#L3374

Steps to reproduce in Contao 4.9, in this case the `Cannot load record "tl_content.id=123".` is shown:

1. Edit a news article
2. Create a new content element inside it
3. Click on insert-link in the tinyMCE editor
4. Open the picker
5. Go to any news article and click on edit (so that the content elements are shown)
6. Cancel the picker
7. Click save.
8. `Cannot load record "tl_content.id=123".`

Originally posted in https://github.com/contao/contao/issues/2201#issuecomment-917585307

**Comment by leofeyer** [comment]
Without line 3374, new content elements will no longer be removed if they are not saved, will they?

1. Create a new content element
2. Go back without saving
3. The element should automatically be removed

**Comment by ausi** [comment]
> Without line 3374, new content elements will no longer be removed if they are not saved, will they?

Correct, this is no suggested fix but the evindence that revise table causes the issue ☺️

**Comment by leofeyer** [comment]
Too bad. I will add this to our developer's meeting list. In case you want to stay up late again. 😉
