### ISSUE TITLE
Datenbankupdate funktioniert nicht

### ISSUE THREAD

**Issue by m-werk** [contao/contao#36]
Contao 4.5 und 4.6

Nach erfolgreichen Update von 4.4 auf die 4.6er Version funktioniert das DB Update nicht, wenn man auf "Datenbank aktualisieren" klickt.
Es kommt die Fehlermeldung: Contao: Es ist ein Fehler aufgetreten.

Im Log steht dann folgendes:

> [2018-08-29 10:44:56] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_route":"contao_install","_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction"},"request_uri":"http://contao.steinkellner-web.com/contao/install","method":"POST"} []
[2018-08-29 10:44:56] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'ALTER TABLE tl_newsletter_recipients CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci':  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes" at /home/.sites/13/site838/web/contao4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 126 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'ALTER TABLE tl_newsletter_recipients CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci':\n\nSQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes at /home/.sites/13/site838/web/contao4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:126, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes at /home/.sites/13/site838/web/contao4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:109, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes at /home/.sites/13/site838/web/contao4/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:107)"} []

Ich hab dann folgenden Code ausgefürht:
`SHOW VARIABLES LIKE 'innodb_%'`
Das Ergebnis war NULL.

Weiters verwende ich keine InnoDB, sondern MySQL. Mein Provider ist World4You

LG, Andi

**Comment by fritzmg** [comment]
> Weiters verwende ich keine InnoDB, sondern MySQL.

Du meinst wohl `MyISAM` ;)

**Comment by m-werk** [comment]
Ja, sorry, das meinte ich

**Comment by leofeyer** [comment]
> Weiters verwende ich keine InnoDB, sondern MyISAM.

Und hast Du das in der `app/config/config.yml` dem System entsprechend mitgeteilt?

**Comment by m-werk** [comment]
Bei mir existiert diese Datei nicht. Ich hab nur die `parameters.yml` dort stehen. Ich hab auch bei anderen Installationen (v. 4.4.x) nachgesehen, auch bei denen ist keine `config.yml`. In der `parameters.yml` steht nur die Verbindung zur DB.

**Comment by leofeyer** [comment]
Bitte benenn die Datei `parameters.yml` mal in `parameters.yml.bkp` um und ruf dann das Install-Tool auf. Es müsste Dich darauf hinweisen, dass Du kein InnoDB hast.

**Comment by m-werk** [comment]
Hm, jetzt muss ich die Datenbankverbindung erneut eingeben. Das hab ich gemacht. Dann kam wieder das Fenster, wo ich die Datenbank aktualisieren kann. Und wieder ging es nicht. Ich hab auch keine Meldung betreffend InnoDB erhalten.

Dies hab ich über den CM gemacht.

Wenn ich jetzt nur die Datei umbenenne, dann muss ich die Datenbankdaten nicht erneut eingeben, wenn ich das Install-Tool aufrufe. Aber auch da bekomme ich keine Meldung. Ich versteh jetzt nur nicht, warum ich über den CM die Zugangsdaten zur DB erneut eingeben musste, und wenn ich nur das Install-Tool aufrufe, muss ich die Zugangsdaten NICHT erneut eingeben, obwohl die parameters.yml umbenannt ist.

**Comment by leofeyer** [comment]
Das ist seltsam. Bei mir sieht es so aus:

<img width="783" alt="" src="https://user-images.githubusercontent.com/1192057/44833546-a5817d00-ac2e-11e8-86e5-2e80e636ca15.png">

Wie sehen denn die Tabellen in phpMyAdmin aus?

**Comment by m-werk** [comment]
Ich hab es mit verschiedenen Browsern versucht und auch den Browsercache zuvor gelöscht. Bei mir kommt dies nicht.
Was meinst du mit 

> Wie sehen denn die Tabellen in phpMyAdmin aus?

Ich hab folgende Tabellenformate zur verfügung: 

- CSV
- Memory
- Blackhole
- MRG-MYISAM
- MyISAM
- Archive

Und die Tabelle sieht so aus:
![tabellenstruktur_1](https://user-images.githubusercontent.com/1488276/44833966-f8a7ff80-ac2f-11e8-9184-e2d819a896a7.jpg)

und so sieht es aus, wenn ich das Install-Tool aufrufe, obwohl ich die Datei `parameters.yml.bkp` so umbenannt habe.
![db_update](https://user-images.githubusercontent.com/1488276/44834086-63f1d180-ac30-11e8-8fe9-46bd98baac4f.jpg)

**Comment by fritzmg** [comment]
Laut @m-werk kann man bei World4You zwar InnoDB aktivieren - dies sei aber kostenpflichtig. Evt. erkennt dadurch `InstallTool::hasConfigurationError` fälschlicherweise, dass InnoDB zur Verfügung steht?

**Comment by leofeyer** [comment]
Das wäre möglich.

@m-werk Bitte leg Dir eine Datei `app/config/config.yml` mit folgendem Inhalt an:

```yaml
doctrine:
    dbal:
        connections:
            default:
                default_table_options:
                    engine: MyISAM
```

Dann leerst Du einmal den Symfony-Cache (über den Contao Manager oder die Kommandozeile) und dann sollte es gehen.

**Comment by m-werk** [comment]
Hab ich gemacht. Negativ.
Ich hab jetzt wieder die Zugangsdaten eingeben müssen, aber ich kann die DB nicht updaten. Es kommt auch keine Meldung. Ich hab auch zu Testzwecken in der `config.yml` anstelle von MyISAM mal InnoDB eingetragen. Leider auch ohne Erfolg

**Comment by leofeyer** [comment]
Bitte teste mal, ob 1b408b936f5176c2ddc2a0cda74cd27ab9a9a0cf das Problem behebt. Eventuell hast Du zwar InnoDB-Tabellen, aber das row format ist nicht `DYNAMIC`.

**Comment by m-werk** [comment]
Eine kleine Frage: Wie soll ich das genau testen?
Aber ich hab etwas anderes herausgefunden. Ich hab mal das SQL-Statement via PHPMyAdmin direkt in der DB ausgeführt. Dort hat alles funktioniert bis auf genau einen SQL-Befehl.

`ALTER TABLE tl_newsletter_recipients CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`

Hier kommt folgende Meldung:

> #1071 - Specified key was too long; max key length is 1000 bytes

Und daran scheiterte dies.
NACHTRAG:
Ich hab via CM ein update auf die Version 4.6.2 gemacht. Da war dann ja auch die Datei neu. 
Ich hab beim Update auf die DB keine Fehlermeldung bekommen, bis eben auf diese, welche zuvor beschrieben. Also sollte mein row format DYNAMIC sein.

**Comment by christian-schattat** [comment]
Um die Installation erfolgreich abzuschliessen, könntest du versuchen, den ersten Anweisungsblock im Install-Tool zu deaktivieren und zunächst nur denjenigen auszuführen, der die bestehenden Indexe löscht. Im Anschluss kannst du das Install-Tool dann alle Anweisungen fehlerfrei ausführen lassen, da es automatisch die neuen Indexe, auf die maximal von deinem System unterstütze Länge, kürzt.

**Comment by m-werk** [comment]
Ja, hab ich doch gemacht, aber wie gesagt, das funktioniert genau nur bei dieser `tl_newsletter_recipients` nicht.

**Comment by m-werk** [comment]
So, nun hab ich mal die DB gelöscht und auch die Contao Installation.
Ich hab jetzt mal alles neu mit der Version 4.6.2 installiert. Wieder kam dann die Meldung im Install-Tool beim create der Tabellen. Es handelt sich genau um diese beiden:

> tl_newsletter_recipients

> tl_search

Das weitere Problem, was ich nun habe, ist folgendes: Wenn ich diese beiden nicht anklicke, und ein Update der DB trotzdem durchführe, wird auch der Rest nicht gemacht, also folgende SQL-Statements werden dadurch jetzt auch nicht durchgeführt. Sobald ich auf Update klicke, bleibt die Install-Seite stehen und es hat sich nichts getan.

> 

Tabellen ändern
--
  | Alle auswählen
  | ALTER TABLE tl_article ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_calendar ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_calendar_events ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_calendar_feed ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_comments ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_comments_notify ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_content ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_cron ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_faq ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_faq_category ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_files ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_form ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_form_field ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_image_size ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_image_size_item ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_layout ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_log ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_member ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_member_group ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_module ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_news ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_news_archive ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_news_feed ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_newsletter ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_newsletter_blacklist ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_newsletter_channel ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_page ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_remember_me ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_search_index ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_style ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_style_sheet ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_theme ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_undo ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_user ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_user_group ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_version ENGINE = InnoDB ROW_FORMAT = DYNAMIC
Spalten ändern
  | Alle auswählen
  | DROP INDEX path ON tl_files
  | DROP INDEX email ON tl_member
  | DROP INDEX email ON tl_user
  | DROP INDEX fromtable ON tl_version
Spalten anlegen
  | Alle auswählen
  | CREATE INDEX path ON tl_files (   path(768) )
  | CREATE INDEX email ON tl_member (email)
  | CREATE INDEX email ON tl_user (email)
  | CREATE INDEX fromtable ON tl_version (fromtable)

**Comment by xchs** [comment]
Enthält die Tabelle `tl_newsletter_recipients` irgendwelche Datensätze? Falls nicht, kannst Du sowohl `tl_newsletter_recipients` als auch `tl_search` komplett löschen und anschließend vom Contao Installtool wieder neu anlegen lassen.

**Comment by m-werk** [comment]
Nein, ich hab jetzt ja eine ganz neue installation gemacht. Ich hab auch die DB zuvor gelöscht.

So, mir scheint, das funktioniert generell nicht bei mir, denn wenn ich mir die DB jezt so ansehe, habe ich als Type dort MyISAM stehen.

Mir scheint, dass ich hier wirklich eine InnoDB bestellen muss, damit das  funktioniert. Das Problem ist nur, ich hab einige Kunden bei diesem Provider, und diese DB kostet monatlich Geld.

**Comment by fritzmg** [comment]
> Eine kleine Frage: Wie soll ich das genau testen?

`dev-4.6` requiren oder die Änderungen manuell in die jeweiligen DAteien einspielen.

> Mir scheint, dass ich hier wirklich eine InnoDB bestellen muss, damit das funktioniert.

Nein, musst du prinzipiell nicht. Du musst nur herausfinden, warum dieser Fehler passiert.

**Comment by m-werk** [comment]
> requiren oder die Änderungen manuell in die jeweiligen DAteien einspielen.

Hab ich gemacht bzw. hab ich ein update gemacht. Da war dann dieses geändert.

> Du musst nur herausfinden, warum dieser Fehler passiert.

Ok, nur wie?

**Comment by fritzmg** [comment]
> Hab ich gemacht bzw. hab ich ein update gemacht. Da war dann dieses geändert.

Was heißt das genau? Funktioniert es nun? Aus deinen bisherigen Posts erschließt sich mir nicht, ob du nach dieser Änderung das Install Tool nochmal aufgerufen und getestet hast, ob es nun funktioniert.

**Comment by m-werk** [comment]
Nein. Ich hab ja oben geschrieben, dass ich eine ganz neue Installation von Contao 4.6.2 gemacht habe inkl. neuer DB. Es funktioniert weiterhin nicht, wenn ich im Install-Tool ein Datenbank-Update mache. Dies steht noch im Fenster:
>Tabellen anlegen
--
  | Alle auswählen
  | CREATE TABLE tl_newsletter_recipients (   id INT UNSIGNED AUTO_INCREMENT NOT NULL,    pid INT UNSIGNED DEFAULT 0 NOT NULL,    tstamp INT UNSIGNED DEFAULT 0 NOT NULL,    email VARCHAR(255) DEFAULT '' NOT NULL,    active CHAR(1) DEFAULT '' NOT NULL,    addedOn VARCHAR(10) DEFAULT '' NOT NULL,    confirmed VARCHAR(10) DEFAULT '' NOT NULL,    ip VARCHAR(64) DEFAULT '' NOT NULL,    token VARCHAR(32) DEFAULT '' NOT NULL,    UNIQUE INDEX pid_email (pid, email),    INDEX email (email),    PRIMARY KEY(id) ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | CREATE TABLE tl_search (   id INT UNSIGNED AUTO_INCREMENT NOT NULL,    pid INT UNSIGNED DEFAULT 0 NOT NULL,    tstamp INT UNSIGNED DEFAULT 0 NOT NULL,    title VARCHAR(255) DEFAULT '' NOT NULL,    url VARCHAR(255) DEFAULT '' NOT NULL,    text MEDIUMTEXT DEFAULT NULL,    filesize DOUBLE PRECISION DEFAULT '0' NOT NULL,    checksum VARCHAR(32) DEFAULT '' NOT NULL,    protected CHAR(1) DEFAULT '' NOT NULL,    groups BLOB DEFAULT NULL,    language VARCHAR(5) DEFAULT '' NOT NULL,    UNIQUE INDEX url (url),    UNIQUE INDEX checksum_pid (checksum, pid),    PRIMARY KEY(id) ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC
Tabellen ändern
  | Alle auswählen
  | ALTER TABLE tl_article ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_calendar ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_calendar_events ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_calendar_feed ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_comments ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_comments_notify ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_content ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_cron ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_faq ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_faq_category ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_files ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_form ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_form_field ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_image_size ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_image_size_item ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_layout ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_log ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_member ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_member_group ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_module ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_news ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_news_archive ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_news_feed ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_newsletter ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_newsletter_blacklist ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_newsletter_channel ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_page ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_remember_me ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_search_index ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_style ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_style_sheet ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_theme ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_undo ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_user ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_user_group ENGINE = InnoDB ROW_FORMAT = DYNAMIC
  | ALTER TABLE tl_version ENGINE = InnoDB ROW_FORMAT = DYNAMIC
Spalten ändern
  | Alle auswählen
  | DROP INDEX path ON tl_files
  | DROP INDEX email ON tl_member
  | DROP INDEX email ON tl_user
  | DROP INDEX fromtable ON tl_version
Spalten anlegen
  | Alle auswählen
  | CREATE INDEX path ON tl_files (   path(768) )
  | CREATE INDEX email ON tl_member (email)
  | CREATE INDEX email ON tl_user (email)
  | CREATE INDEX fromtable ON tl_version (fromtable)

Und wenn ich die beiden Tabellen wegklicke, so dass wenigstens der Rest gemacht wird, tut sich auch nichts. Es bleibt immer dieses SQL-Statement stehen.

**Comment by fritzmg** [comment]
> Nein. Ich hab ja oben geschrieben, dass ich eine ganz neue Installation von Contao 4.6.2 gemacht habe inkl. neuer DB. Es funktioniert weiterhin nicht, wenn ich im Install-Tool ein Datenbank-Update mache. Dies steht noch im Fenster:

Du musst, wie schon gesagt, das Datenbank Update mit den [Änderungen](https://github.com/contao/contao/issues/36#issuecomment-417884138) testen.

**Comment by m-werk** [comment]
Hab ich gemacht. Ich hab den Code geändert, aber leider nichts. Es will nicht funktionieren. Wenn ich die beiden Tabellen wegklicke so dass wenigstens der Rest des Updates durchgeführt wird, passiert auch nichts. Es bleibt das SQL-Statement so sehen, wie schon oben beschrieben und Meldung in der Log hab ich hierdurch auch keine.

**Comment by m-werk** [comment]
Ich hab mal das SQL-Statement in PHPMyAdmin ausgeführt:

> CREATE TABLE tl_newsletter_recipients (
  id INT UNSIGNED AUTO_INCREMENT NOT NULL, 
  pid INT UNSIGNED DEFAULT 0 NOT NULL, 
  tstamp INT UNSIGNED DEFAULT 0 NOT NULL, 
  email VARCHAR(255) DEFAULT '' NOT NULL, 
  active CHAR(1) DEFAULT '' NOT NULL, 
  addedOn VARCHAR(10) DEFAULT '' NOT NULL, 
  confirmed VARCHAR(10) DEFAULT '' NOT NULL, 
  ip VARCHAR(64) DEFAULT '' NOT NULL, 
  token VARCHAR(32) DEFAULT '' NOT NULL, 
  UNIQUE INDEX pid_email (pid, email), 
  INDEX email (email), 
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC

> MySQL meldet: Dokumentation
#1071 - Specified key was too long; max key length is 1000 bytes

Leider ist hier auch der Fehler. Nur wie bekomme ich das jetzt noch hin.

**Comment by leofeyer** [comment]
> max key length is 1000 bytes

Die Meldung deutet darauf hin, dass Du MyISAM verwendest. Bei InnoDB wäre die maximale Index-Länge 767.

**Comment by m-werk** [comment]
Tja, komisch ist nur, dass die DB installiert wurde (mit der Ausnahme dieser beiden Tabellen). Es stand bei den anderen auch `DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC`
aber wenn ich mir die DB mit den Tabellen ansehe, wurde hier beim TYP "MyISAM" eingetragen. Dort sollte doch InnoDB stehen, oder? Das hat das Install-Tool mal nicht so gemacht.

**Comment by m-werk** [comment]
So, hab den Provider kontaktiert, da ich gesehen habe, dass diese DB auf MySQL 5.5 läuft. Ich habe gebeten, dass er diese auf die Version 5.7 umstellt. Dann sehen wir weiter und es sollte dann auch funktionieren.

**Comment by m-werk** [comment]
Problem gelöst. Mir wurde nun eine DB mit MySQL 5.7 angelegt. Jetzt hab ich die neue DB zugeordnet und das Update der DB lief ohne Fehler durch. In der DB hab ich jetzt bei den Tabellen nun den Typ InnoDB stehen.
Somit hat sich das nun erledigt. Danke für eure Unterstützung.

**Comment by NinaG** [comment]
Zur Info, das Problem tritt auch bei anderen auf:
https://community.contao.org/de/showthread.php?71871-ENGINE-InnoDB-ROW_FORMAT-DYNAMIC&p=482149
