### ISSUE TITLE
Problem with special characters in backend startpage "last edited"

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#360]
**Affected version(s)**
4.6 & 4.7

**Description**  
In the compare view of last edited (contao backend startpage), special characters are not shown correctly.
`Jagdpraxis Teil 4 mit Nico(M-1811) `

becomes

`Jagdpraxis Teil 4 mit Nico &#40;M-1811&#41; `

Greetings

**Comment by leofeyer** [comment]
What record did you change? A page? Or a content element?

**Comment by Kahmoon** [comment]
An event title.

greetz

**Comment by leofeyer** [comment]
@contao/developers Strictly speaking, the diff view is correct, because `&#40;` is what has actually been stored. It seems to confuse some users though. Should we handle this? (And if yes, how do you distinct between `(` and `&#40;` in the diff view then?)

**Comment by Toflar** [comment]
Imho if `decodeEntities` isn't configured to `true` then decode the content.
The output should be encoded for security reasons again though.

**Comment by aschempp** [comment]
> And if yes, how do you distinct between ( and &#40; in the diff view then?)

That should never happen, because the field contains one or the other, right? But what if the user entered `&#40`?

**Comment by leofeyer** [comment]
As discussed in Mumble on May 9th, we need to convert `&#40;` to `(` in the diff view as suggested by @Toflar:

> Imho if `decodeEntities` isn't configured to `true` then decode the content.
> The output should be encoded for security reasons again though.

**Comment by leofeyer** [comment]
Pull-Request: https://github.com/contao/contao/pull/486
