### ISSUE TITLE
Content Element (type html) deletes script tag src attribute for adding javascript file

### ISSUE THREAD

**Issue by Schlingel2018** [contao/contao#3624]
We found this issue in Contao 4.9.21 mabye it occours in older versions too. We had no problems in Contao 4.4.

If you create a content element and choose element type "html" in the past you can include there script tags with a src attribute to load some javascript.

For example you add 

```
<script src="files/test.js"></script>
```

After saving the content element, the src tag will be removed
```
<script></script>
```

If you have older content elements which work at their current state, after opening and save it, the same problem occours.
Very bad when you have a lot of these elements.

Greets

**Comment by Toflar** [comment]
That's by design. It's due to the latest security updates. Checkout the system settings to configure the allowed HTML attributes. :)

**Comment by Schlingel2018** [comment]
Oh okay :-D sorry. Thx.
