### ISSUE TITLE
Formular Validierung mit InsertTags in den Selects

### ISSUE THREAD

**Issue by do-while** [contao/contao#3632]
**Affected version(s)**

Contao 4.9 bis Contao 4.12

**Description**

Bei 2-sprachigen Formularen hat man ggf. auch in den Values der SELECT-Optionen InsertTags {{iflng::xx}} enthalten.
In diesem Fall läßt sich aber das Formular nicht absenden: "Invalid option value!"
Offenbar werden vor dem Validieren die InsertTags nicht aufgelöst.

SELECT-Feld:
Option 1: `{{iflng::de}}Rot{{iflng::en}}Red{{iflng}}` im Wert und in der Beschreibung
Option 2: `{{iflng::de}}Grün{{iflng::en}}Green{{iflng}}` im Wert und in der Beschreibung

Aufgefallen ist es mir in Version 4.9, läßt sich aber auch in der Demo unter 4.12.3 nachvollziehen.

**Comment by aschempp** [comment]
ich denke in einem Option-Wert solltest du keine Insert-Tags haben, sonst könnte aus dem Insert-Tag ja auch HTML in eine Option geschrieben werden, was nie funktionieren kann.

**Comment by do-while** [comment]
Da habe ich jetzt nicht drauf geachtet: Versendet das Notification-Center den Wert oder die Beschreibung der ausgewählten Option? Wenn es die Beschreibung ist, kann es auch ohne SprachInsertTags gehen.
Ich probiere das Morgen gleich aus.

**Comment by do-while** [comment]
Also, sowohl in den ##raw##-Daten, wie auch in den ##form_*##-Feldern werden die Werte der Felder ausgegeben, nicht der Text, den der Besucher gesehen hat.
Das betrifft nicht nur SELECT-Felder, sondern auch die RADIO-Felder.
Mehrsprachige Formulare lassen sich so nicht erstellen, wenn ich keine Sprach-InsertTags in den Values verwenden kann.

Abhilfe wären nur einzelne Formulare für jede Sprache. Ich glaube das ist jetzt erst seit den Sicherheitsupdates, dass die Validierung nicht mehr passt.

**Comment by fritzmg** [comment]
> Mehrsprachige Formulare lassen sich so nicht erstellen, wenn ich keine Sprach-InsertTags in den Values verwenden kann.

Mehrsprachigkeit bei Formularen, Nachrichten, Seiten etc. in Contao funktioniert so, dass du je Sprache ein eigenes Formular, Nachrichtenarchiv, Seitenbaum etc. erstellst.

**Comment by do-while** [comment]
Das habe ich jetzt auch so gemacht.
Ich finde es nur unglücklich, dass im Value im Backend ein Wert angegeben werden kann, der bei Auswahl im Frontend zu einer Fehlermeldung führt. Beim Rendern des Formularelements werden die InsertTags aufgelöst, vor der Validierung im Formular dann aber nicht. Ansich soll diese Validierung ja prüfen und verhindern, dass jemand falsche Einstellungen hier einspeisen möchte.
