### ISSUE TITLE
Prepared statement fails in Contao\Versions

### ISSUE THREAD

**Issue by bezin** [contao/contao#3642]
```An exception occurred while executing a query: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens```

After pulling in 3cadec7dfd444eefced20da70d5ca21408b3ec82 I get the error message mentioned above after logging into the backend. It originates in the Versions class, when counting versions:

https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/classes/Versions.php#L655-L656

I logged in as Admin, hence the ` AND userid=?` part was not added to the prepared statement. The user id however is always passed to `execute()`.

**Comment by ausi** [comment]
Note to myself: `number of bound variables does not match number of tokens` should be allowed but deprecated (if the number of tokens is larger) also using things like `PageModel::findWithDetails(null)` worked previously and the behavior should also be restored and deprecated.

**Comment by leofeyer** [comment]
Note that even though #3643 fixes this particular issue, the underlying issue will only be fixed by @ausi's PR (not available yet). I am therefore leaving the ticket open.

**Comment by ausi** [comment]
> @ausi's PR (not available yet)

#3645
