### ISSUE TITLE
insert tag {{file::*}} wird im tinyMCE nicht richtig aufgelöst

### ISSUE THREAD

**Issue by chiron501** [contao/contao#3646]
**Affected version(s)**

Contao 4.4.57

**Description**

Erstellt man im TinyMCE einen Download-Link wird wie gewohnt der Insert-Tag {{file::*}} eingetragen. Nach dem abspeichern steht im href-Attribut nicht der Pfad zur Datei sondern die Datei-ID, aber ohne die geschweiften Klammern.
`<a href="65adf984-3d7b-11ec-9d99-08002778b90e|urlattr">download</a>`
Der Link im Frontend selber funktioniert zunächst wie gewohnt. Speichert man jetzt aber nochmal das Inhaltselement ab, zerschießt man sich den Link natürlich, da ja im href nur die ID ohne die geschweiften Klammern drin steht.

**Comment by ausi** [comment]
Duplicate of #3430 was fixed in #3455
