### ISSUE TITLE
Shortcut for cache tagging with entities

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3648]
Assume there is an entity `Foo` with table `tl_foo` of which all elements should be output in a `FooListFragment`, a single one in a `FooDetailsFragment` and maybe some more selected ones in a `SelectedFoosDetailsFragment`. 

You would then need to tag you response like so:
```php
// FooListFragment
$this->tagResponse(['contao.db.tl_foo']);

// FooDetailsFragment
$this->tagResponse(['contao.db.tl_foo.' . $element->getId()]);

// SelectedFoosDetailsFragment
$this->tagResponse(
    array_map(static fn(Foo $element): string => 'contao.db.tl_foo.' . $element->getId(), $elements);
);


```

Now, you're losing your abstraction - the `tl_foo` table name gets baked into the code and will probably be missed out when refactoring. And, though small, it's also repetitive code showing up at many places. 

I wonder if we could create a shortcut that works like this:

```php
// FooListFragment
$this->tagResponse(Foo::class);

// FooDetailsFragment
$this->tagResponse([$element]);

// SelectedFoosDetailsFragment
$this->tagResponse($elements);
```

I.e. when passing an entity class name, we substitute it with `['contao.db.<table-name>']` and if a collection of objects is passed we substitute each with `contao.db.<table-name>.<pk>`. All mappings (table name, pk) are available via doctrine's class metadata. 

The same would work with our models I guess.

Wdyt?

**Comment by m-vo** [comment]
This could also propagate through relations if the entity in question is the owning side of a relation.

**Comment by m-vo** [comment]
Here is a prototypical implementation:

```php
use Doctrine\ORM\EntityManagerInterface;
use FOS\HttpCacheBundle\Http\SymfonyResponseTagger;

class EntityTagger
{
    public function __construct(
        private SymfonyResponseTagger $responseTagger,
        private EntityManagerInterface $entityManager
    ) {
    }

    public function tagResponse(array|string $targets): void
    {
        if (\is_string($targets)) {
            $this->tagResponseForEntityClass($targets);

            return;
        }

        if (!\is_array($targets)) {
            throw new \InvalidArgumentException('Targets must either be an entity class name or an array.');
        }

        foreach ($targets as $target) {
            if (\is_object($target)) {
                $this->tagResponseForEntityInstance($target);
            } elseif (\is_string($target)) {
                $this->responseTagger->addTags([$target]);
            } else {
                throw new \InvalidArgumentException('Targets array must only contain entity instances or strings.');
            }
        }
    }

    public function tagResponseForEntityClass(string $entityClassName): void
    {
        $tableName = $this->entityManager
            ->getClassMetadata($entityClassName)
            ->getTableName()
        ;

        $this->responseTagger->addTags(["contao.db.$tableName"]);

        // todo follow relations
    }

    public function tagResponseForEntityInstance(object $object): void
    {
        $tableName = $this->entityManager
            ->getClassMetadata($object::class)
            ->getTableName()
        ;

        $identifier = $this->entityManager
            ->getUnitOfWork()
            ->getSingleIdentifierValue($object)
        ;

        $this->responseTagger->addTags(["contao.db.$tableName.$identifier"]);

        // todo follow relations
    }
}

```

**Comment by ausi** [comment]
Having `tagResponse('string')` meaning something different than `tagResponse(['string'])` could be misleading I think. Can we check if the string includes a backslash and only handle it as a `class-string` then (both in the array and as a single argument)?

**Comment by m-vo** [comment]
> Can we check if the string includes a backslash and only handle it as a class-string then (both in the array and as a single argument)?

Thought about this as well and came to a similar conclusion. :+1:. If we encapsulate the logic into a service we can both supply the well defined/typed implementations as well as a method that is guessing. The latter could then be used inside our `AbstractController#tagResponse()` method.

**Comment by m-vo** [comment]
see #3659
