### ISSUE TITLE
Unsightly effect of autoFocusFirstInputField

### ISSUE THREAD

**Issue by Aybee** [contao/contao#3651]
Contao 4.9

Every time I open a user for editing I get this annoying popup as can be seen in the screenshot.

![Screen-2021-11-06_16-46-37-2](https://user-images.githubusercontent.com/1143013/140651527-10d2f40f-0eb9-47ac-a061-606510ca4514.png)

I think it's the result of `autocomplete = "username"` and at the same time the JS function `autoFocusFirstInputField()`.

IMO we should exclude fields with the attribute `autocomplete` from the function `autoFocusFirstInputField()` in this line:
https://github.com/contao/contao/blob/8468881d30b54c448310bc2456920d4ec328e088/core-bundle/src/Resources/public/core.js#L2597.

**Comment by fritzmg** [comment]
This is a Browser issue. Chrome for example does not show the saved passwords dropdown on any field, if the field was auto focused by JavaScript, as far as I tested. Chrome only shows the dropdown, if the user clicks into a username or password field.
