### ISSUE TITLE
New-Erweiterungs: Fehler in der RSS-Datei, wenn Teaser ein <br> enthält

### ISSUE THREAD

**Issue by arboc** [contao/contao#366]
**Affected version(s)**  
4.4.34

**Description**  
Wenn ich im Teaser einer News einen Text mit einem Zeilenumbruch eintrage, wird eine Fehlerhafte RSS-XML-Datei erstellt.

**How to reproduce**   
Bsp eines Teasers (Quelltext):
```html
<p>Bugfix: Serientermine, Verrechnungsrezepte, Vernichtungen<br>Improvements: xDT-Schnittstelle</p>
```
Fehler Hinweis, z.B. beim Öffnen der XML mit Chrome
```
error on line 1 at column 1034 Opening and ending tag mismatch: br line 0 and p
```

**Comment by Xirdion** [comment]
In XML every tag needs a closing tag.
So would changing the `<br>` to a `<br />` fix this problem?

**Comment by Toflar** [comment]
Ich möchte bitte gern die gesamte XML sehen, die generiert wird. Wenn ich den Code lese, dann müsste der Teaser zur `<description>` hinzugefügt werden und die liegt innerhalb eines `<![CDATA[]]`, darf also beliebige Tags enthalten.

**Comment by arboc** [comment]
Feed-Einstellungen: ATOM und nur Teaser-Texte:
![image](https://user-images.githubusercontent.com/4447843/53231947-53c02980-368a-11e9-923e-5c24a5ad45a9.png)

Die von Contao genereite XML: Zeile 14 enthält den `<br>`

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="de">
    <title>Pharmanews</title>
    <subtitle></subtitle>
    <link rel="alternate" href="https://www.medinizer.de/"/>
    <id>https://www.medinizer.de/</id>
    <updated>2019-02-21T09:45:46+01:00</updated>
    <generator>Contao Open Source CMS</generator>
    <link href="https://www.medinizer.de/share/pharmanews.xml" rel="self"/>
    <entry>
        <title>Neue Version 2.8.2</title>
        <content type="xhtml">
            <div xmlns="http://www.w3.org/1999/xhtml">
                <p>Bugfix: Serientermine, Verrechnungsrezepte, Vernichtungen<br>Improvements: xDT-Schnittstelle
                </p>
            </div>
        </content>
        <link rel="alternate" href="http://www.medinizer.de/newsreader/neue-version-2-8-2.html"/>
        <updated>2019-02-06T12:43:00+01:00</updated>
        <id>http://www.medinizer.de/newsreader/neue-version-2-8-2.html</id>
        <author>
            <name>agentur fipps e.K.</name>
        </author>
    </entry>
</feed>
```

**Comment by Toflar** [comment]
Ah, das ist das Problem. RSS scheint zu passen, aber Atom nicht.
Muss [hier](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Feed.php#L214) analog von RSS geändert werden.
@leofeyer Bug 👍

**Comment by leofeyer** [comment]
Ich denke nicht, dass `<![CDATA[` das Problem ist. Das Markup

```html
<content type="xhtml">
    <div xmlns="http://www.w3.org/1999/xhtml">
```

liest sich so, als würde hier valides XHTML erwartet werden, oder?

**Comment by arboc** [comment]
sehe ich auch so...  
das `<br>` müsste `<br />` heißen.

**Comment by leofeyer** [comment]
Ich habe soeben Deinen Teaser-Text in eine News der COD eingefügt. Im Frontend wird der Zeilenumbruch als `<br>` ausgegeben und in der XML-Datei als `<br />` – also alles korrekt. Ich kann das Problem nicht reproduzieren.

**Comment by arboc** [comment]
@leofeyer  
Ich habe es eben noch mal getestet.  
Bei mir tritt der Fehler immer noch auf. 

Hier die URL zur XML https://www.medinizer.de/share/test.xml. 

scheint an der Installation zu liegen. Evtl eine Erweiterung, die hier stört.
