### ISSUE TITLE
Deprecate `$GLOBALS['TL_AUTO_ITEM']`

### ISSUE THREAD

**Issue by ausi** [contao/contao#3662]
Should we deprecate the `$GLOBALS['TL_AUTO_ITEM']` array?
Is this used widely? Do we need an alternative?

**Comment by fritzmg** [comment]
I've personally never used it. I always used `auto_item` when applicable. The core uses it though (`items` for news and events), but only for legacy reasons as well, I think.

**Comment by aschempp** [comment]
I stopped using it a while ago and I don't think we need an alternative. But I'm sure there's extensions out there using it 🤔

**Comment by leofeyer** [comment]
If we deprecate it, we have to provide an alternative IMHO.

**Comment by aschempp** [comment]
Do we really need an alternative? What is it really useful for?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we can only remove `$GLOBALS['TL_AUTO_ITEM']` if we also remove `useAutoItem` – which we want to do in Contao 5. We then have to adjust things like this to only query the auto_item parameter:

https://github.com/contao/contao/blob/8dbd9ba93e49826c20fca1f523e7fa8794b76741/news-bundle/src/Resources/contao/modules/ModuleNewsReader.php#L58-L68

So we also have to deprecate the variable in Contao 4.13 and then move the issue to the `5.0` milestone.

**Comment by leofeyer** [comment]
Follow-up issue: #3860
