### ISSUE TITLE
Deprecate `$GLOBALS['TL_CSS_UNITS']`

### ISSUE THREAD

**Issue by ausi** [contao/contao#3663]
If we deprecate `$GLOBALS['TL_CSS_UNITS']` how do we replace it?
It is mostly used in the deprecated style editor, but also in some other places.

We could just hardcode the useful units in depending on the use case instead.

**Comment by aschempp** [comment]
stuff like that should be a container parameter in my opinion. Its not something people need to easily change, but they can if it's a container parameter 😊 
I think there's a lot of similar stuff we should/might all change in Contao 5.

**Comment by leofeyer** [comment]
> We could just hardcode the useful units in depending on the use case instead.

Yes. 👍 People can still change the options in the DCA if they want to.

**Comment by aschempp** [comment]
> We could just hardcode the useful units in depending on the use case instead.

Generally fine with me. It's just "stupid" that this value is used in 27 places, and hardcoding **the same value** 27 times seems very wrong to me 😅

**Comment by ausi** [comment]
> It's just "stupid" that this value is used in 27 places, and hardcoding **the same value** 27 times seems very wrong to me 😅

The only non-deprecated usages I could find are `imagemargin` and the header, footer, sidebar and static layout settings in `tl_layout`.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to deprecate the variable in the `DEPRECATED.md` file and directly add the units in the non-deprecated DCAs (only those that make sense there).
