### ISSUE TITLE
DCA bug when MultiColumnWizard reaches 7 rows

### ISSUE THREAD

**Issue by jxns** [contao/contao#3666]
**Affected version(s)**

Contao 4.12.3

**Description**

I have an own DCA table. One of the fields is a MultiColumnWizard with 4 columns:

```
'datasheet_data' => array
    (
      'label'                   => $GLOBALS['TL_LANG']['tl_products']['datasheet_data'],
      'inputType'               => 'multiColumnWizard',
      'eval'                    => array(
        'columnFields' => [
          'headline_de' => [
              'label'     => $GLOBALS['TL_LANG']['tl_products']['datasheet_data']['headline_de'],
              'inputType' => 'textarea',
              'mandatory' => true,
              'eval'      => ['mandatory' => false, 'allowHtml' => false, 'style' => 'width: 100%; resize: none;'],
          ],
          'headline_en' => [
              'label'     => $GLOBALS['TL_LANG']['tl_products']['datasheet_data']['headline_en'],
              'inputType' => 'textarea',
              'mandatory' => true,
              'eval'      => ['mandatory' => false, 'allowHtml' => false, 'style' => 'width: 100%; resize: none;'],
          ],
          'data_de' => [
              'label'     => $GLOBALS['TL_LANG']['tl_products']['datasheet_data']['data_de'],
              'inputType' => 'textarea',
              'mandatory' => true,
              'eval'      => ['mandatory' => false, 'allowHtml' => false, 'style' => 'width: 100%; resize: none;'],
          ],
          'data_en' => [
              'label'     => $GLOBALS['TL_LANG']['tl_products']['datasheet_data']['data_en'],
              'inputType' => 'textarea',
              'mandatory' => true,
              'eval'      => ['mandatory' => false, 'allowHtml' => false, 'style' => 'width: 100%; resize: none;'],
          ]
        ], 'style' => 'max-width:100%'
      ),
      'sql'               => "blob NULL"
    ),
```

This was working fine for a long time. I recently updated to 4.12.3. 
Now, as soon as the MultiColumnWizard reaches 7 rows (doesn't matter if empty or with content), I cannot edit the record anymore.
When clicking the edit-button, instead of opening the record, it just downloads a "contao" file with 0kB.
If I manually delete the database entry, the record is working again until the MultiColumnWizards exceeds the mentioned limit.

** Expected Workflow **
1. Create a record, fill all entrys and insert data to the MultiColumnWizard
2. Save the record
3. If I need to change the data I click on the edit button in the backend and get back to the fields of the DCA

** Current workflow **
1. Create a record, fill all entrys and insert data to the MultiColumnWizard
2. Save the record
3. If I need to change the data I click on the edit button but the page does nothing and just downloads a 0kB "contao" file.

**Comment by fritzmg** [comment]
The MultiColumnWizard ist not part of the Contao Core - you will need to raise this issue here: https://github.com/menatwork/contao-multicolumnwizard-bundle/issues
