### ISSUE TITLE
Seitenstruktur | rel-Attribut beim Seitentyp externe Weiterleitung

### ISSUE THREAD

**Issue by stefan-at-work** [contao/contao#3667]
Momentan gibt in der Seitenstruktur beim Seitentyp externe Weiterleitung keine Möglichkeit dem Anker-Tag ein rel-Attribut wie z.B. rel=”noopener” oder rel=”noreferrer” mitzugeben. Wäre schön, wenn man dies optional direkt etzen könnte.

**Comment by leofeyer** [comment]
Wenn Du die Option "In einem neuen Fenster öffnen" aktivierst, fügt Contao automatisch `rel="noreferrer noopener"` ein:

<img width="628" alt="" src="https://user-images.githubusercontent.com/1192057/142406929-ef2d688d-5a2f-4e6f-9651-022cffb1fea5.png">

**Comment by m-vo** [comment]
> Wenn Du die Option "In einem neuen Fenster öffnen" aktivierst, fügt Contao automatisch rel="noreferrer noopener" ein:

The differentiation makes no sense to me. From a UX persepective you should almost never open a link in a new window. We should IMHO consider adding it always if the url is an external one like in the `FigureBuilder` when linking images to external resources.

**Comment by leofeyer** [comment]
`rel="noopener"` does not really make sense without `target="_blank"`, does it?

**Comment by m-vo** [comment]
I think these are independent: Setting `noopener` just disallows `Window.opener` from the target context. When setting `target="_blank"`, this already implies `noopener`. At least nowadays.

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener

**Comment by leofeyer** [comment]
Nice. So we could remove the `noopener` completely?

**Comment by m-vo** [comment]
IMHO we should instead add it always for external urls - independent of the `target` attribute. It doesn't really hurt and then it even works in IE. :smile:

**Comment by ausi** [comment]
AFAIK adding `rel="noreferrer noopener"` for `target="_blank"` links is just a bug fix for a browser security issue, see <https://mathiasbynens.github.io/rel-noopener/>

`noreferrer` is needed for very old browsers (like Internet Explorer) and `noopener` is needed for older browsers (like Opera or Safari 12.0).

Once these old browsers become obsolete we can remove these things again IMO. 
Setting them independent of the `target` attribute doesn’t make sense to me.

**Comment by aschempp** [comment]
so I guess this can be closed? 😅
