### ISSUE TITLE
Console crawler inherits "noSearch"

### ISSUE THREAD

**Issue by gentlemedia** [contao/contao#3669]
**Affected version(s)**

Contao 4.9.22

**Description**

When using the crawler to create the search index via the console, the log for all open and protected pages states: "Forwarded to the search indexer. Did not index because of the following reason: Was explicitly marked "noSearch" in page settings."
It seems that the console crawler does not update a variable on pass and once it finds "noSearch" in a page, it does not update that for the following pages. In our case, the top page (Home) was set to "noSearch". After I unchecked it here, the crawler indexed the following pages.

**Comment by fritzmg** [comment]
> In our case, the top page (Home) was set to "noSearch". After I unchecked it here, the crawler indexed the following pages.

Just to clarify: by top page you mean "Home" is the _parent_ page and all other pages that were not indexed are _children_ of the "Home" pages? Or do you merely mean "Home" is the first page in the otherwise flat hierarchy?

**Comment by gentlemedia** [comment]
"Home" is the first page.

root 
-- home 
-- documentation
----- page1
------- sub1

**Comment by fritzmg** [comment]
I cannot reproduce the problem. With a site structure like shown by @gentlemedia, setting `home` to `noSearch` does not prevent indexing of the other pages.

**Comment by gentlemedia** [comment]
Are you using the crawler via SSH console?

**Comment by fritzmg** [comment]
Yes, via `vendor/bin/contao-console contao:crawl --subscribers="search-index" --enable-debug-csv`

**Comment by gentlemedia** [comment]
Strange. I can clearly reproduce it on my installation. But anyway, I can live with my workaround. Thanks.

"Home" with "Nicht durchsuchen":
<img width="853" alt="Bildschirmfoto 2021-11-12 um 12 28 02" src="https://user-images.githubusercontent.com/7711886/141460264-fff3d5f7-c8a4-4c88-bcc4-30e7328c4bc6.png">

"Home" without "Nicht durchsuchen":
<img width="866" alt="Bildschirmfoto 2021-11-12 um 12 27 03" src="https://user-images.githubusercontent.com/7711886/141460269-a98076e7-6535-40f8-970f-107560d12f79.png">
