### ISSUE TITLE
problem copying content elements to events or news

### ISSUE THREAD

**Issue by booh111** [contao/contao#367]
**Affected version(s)**
bemerkt in 4.4.32, tritt auch in 4.4.34 auf. Auch in der Contao-Demo 4.6.12 als h.lewis reproduzierbar.
**Description**  
Kopieren von Inhaltselementen aus Artikeln nach News-/Event-Details durch Redakteure bringt Fehlermeldung:
_Invalid news/event content element ID ###._

**Comment by leofeyer** [comment]
https://github.com/contao/contao/blob/master/LIMITATIONS.md#moving-content-elements-as-non-admin-user

**Comment by booh111** [comment]
Ok, danke!
