### ISSUE TITLE
TL_MODE undefined

### ISSUE THREAD

**Issue by arboc** [contao/contao#368]
**Affected version(s)**
4.4.35

**Description**  
Wir verwenden den HOOK `initializeSystem`.  
Bis zur Version 4.4.34 war im Callback TL_MODE verfügbar.  
Mit dem Update zu 4.4.35 nicht mehr.

siehe auch #277

**Comment by leofeyer** [comment]
Wir haben aber eigentlich nichts an TL_MODE geändert von der 4.4.34 auf die 4.4.35:

https://github.com/contao/contao/compare/4.4.34...4.4.35

**Comment by arboc** [comment]
mmm, nagel mich nicht drauf fest   
Jedenfalls in der 4.4.35 ist das wie beschrieben.

**Comment by ausi** [comment]
Was genau bedeutet *„TL_MODE ist nicht verfügbar“*?  
Bekommst du eine PHP-Warnung `Use of undefined constant TL_MODE` oder ist `TL_MODE` auf `null` gesetzt?  
Tritt der Fehler bei jedem Request auf, sowohl Backend als auch Frontend?

**Comment by arboc** [comment]
hat sich erledigt, ich hatte einen Fehler im Code.
