### ISSUE TITLE
Remove preview.php fragment from URL again

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#370]
**Affected version(s)**

4.8.x-dev

**Description**  

When the debug mode is activated, the `preview.php` fragment is added to the URL, however, when the debug mode is deactivated again, the `preview.php` fragment is not removed.

@aschempp /cc

**Comment by aschempp** [comment]
It is not supposed to be removed. The `preview.php` is for *front end preview without cache*, and later on it should probably also add the preview bar (once it is JavaScript and not an iframe anymore). It is not strictly related to the debug mode.

**Comment by leofeyer** [comment]
So it is added automatically but has to be removed manually?

**Comment by aschempp** [comment]
yes, but there's really no reason to ever not use `preview.php` if you're logged in to the back end…

**Comment by leofeyer** [comment]
That seems a little odd to me. If none of the preview features are used, the `preview.php` fragment should be removed IMHO.

**Comment by aschempp** [comment]
Whenever you visit the website while logged in, you *are* using a preview feature, you are (and need to) bypass the cache. Whether hidden elements are shown or the debug mode is enable are just *additional*.

**Comment by leofeyer** [comment]
Yes, but that does _not_ include the back end.

**Comment by aschempp** [comment]
That's correct. That's just a convenience-feature to me. That's why one idea was to name it *admin.php* and only allow backend login to that URL (which helps with people being aware about the entry point).

**Comment by leofeyer** [comment]
As discussed in Mumble on March 7th:

- Only use the `preview.php` fragment in the front end
- Never show any previews if the `preview.php` fragment is not there

@Toflar is going to implement:

- Remove "always bypass private requests"
- If there is no cookie, add `vary: cookie` to the response
- New site checkbox: "always load from cache" (even if there is a logged in user)

**Comment by aschempp** [comment]
> Only use the preview.php fragment in the front end

What if a user opens the backend via `preview.php`?

> Never show any previews if the preview.php fragment is not there

Note to self: That also means ALL back end links need to have the `preview.php` fragment.

**Comment by Toflar** [comment]
> What if a user opens the backend via `preview.php`?

Imho it should be redirected to `/contao` for the sake of consistency?

**Comment by leofeyer** [comment]
Partly fixed in 70d5629320f24f7a5abc3d4a6a1c3e871e0343f5.

1. I have tried to remove the `/preview.php` fragment in the back end, but it did not work without it. Did we plan to adjust the `index.php` entry point so it optionally boots the kernel in debug mode? Because that would mean to parse the JWT cookie upon every request.

2. <del>The FE preview can still be accessed via `/contao/preview` in addition to `/preview.php/contao/preview`. Without the `/preview.php` fragment, the debug mode drop-down is not shown though. </del> Fixed in 7d6428d509505b2e2ecafa6258d25ce3496c8176.

**Comment by leofeyer** [comment]
> Never show any previews if the `preview.php` fragment is not there

How do you want me to implement this? Do I adjust the `TokenChecker::isPreviewMode()` method or just the `BE_USER_LOGGED_IN` constant?

```php
private function setConstants(): void
{
    \define('BE_USER_LOGGED_IN', $this->isPreviewMode());
}

private function isPreviewMode(): bool
{
    if (null === $this->request) {
        return false;
    }

    if ('/preview.php' !== $this->request->getScriptName()) {
        return false;
    }

    return $this->tokenChecker->hasBackendUser() && $this->tokenChecker->isPreviewMode();
}
```

**Comment by aschempp** [comment]
Not really sure, but sounds like we need to do both?

**Comment by leofeyer** [comment]
Agreed. Fixed in 6aa4c398c46196d0263dbef55a3ab06811140357 then.

**Comment by xchs** [comment]
I also came across this thing today. Is it really necessary that the `preview.php/` URL fragment remains in the URL even if front end preview mode is disabled?

**Comment by Toflar** [comment]
Yes it is. If you enabled caching for logged in users (new checkbox) you need that. Also for consistency.

**Comment by leofeyer** [comment]
Also, as @aschempp pointed out, closing the preview bar does not terminate the preview mode in Contao <4.8, therefore it is consistent to keep the `preview.php` fragment.
