### ISSUE TITLE
Fehlerhafte Download-Links nach Update auf 4.9.22

### ISSUE THREAD

**Issue by tinokramm** [contao/contao#3703]
**Affected version(s)**

Contao 4.9.22

**Description**

Bei zwei Websites habe ich seit dem Update von Contao 4.4.57 auf Contao 4.9.22 folgendes Problem: Download-Links funktionieren nicht mehr, weil dem Download-Link offenbar der Parameter &cid an die URL angehangen wird. Es betrifft scheinbar nur das Inhaltselement Download. Klicke ich auf einen solchen Link kommt ein Fehler 404. Entferne ich den Parameter &cid aus der URL wird die verlinkte Datei gefunden.

Danke für Feedback

Tino

**Comment by fritzmg** [comment]
> Download-Links funktionieren nicht mehr, weil dem Download-Link offenbar der Parameter &cid an die URL angehangen wird.

The `cid` parameter is normal and was always there, as it identifies the content element.

**Comment by tinokramm** [comment]
Das kann ich leider nicht bestätigen. In der 4.4er Installation haben die Download-Links diesen Parameter nicht in der URL. Erst nach dem Update auf 4.9 zeigt sich der Parameter in der URL. So zumindest hier bei mir.

4.4er Installation:
https://update.bbe-fenstertechnik.de/downloads-haustueren.html

4.9er Installation:
https://www.bbe-fenstertechnik.de/downloads-haustueren.html

Die Links auf den Bildern funktionieren. Die Links unter den Bildern nicht.

**Comment by tinokramm** [comment]
4.4er Installation:

**Comment by fritzmg** [comment]
> Das kann ich leider nicht bestätigen.

The `cid` parameter has been introduced in https://github.com/contao/contao/commit/3cab24efb00ed737667a2b717d561a80c2d2d734 three and a half years ago in Contao 4.6.0. Without the parameter, the download will not work - at least in a vanilla Contao 4.9+ installation.

**Comment by bytehead** [comment]
I can copy this, there are a lot of Sentry issues raised from this. The download  of the file somehow works, but you'll get 404 `PageNotFoundExceptions` in Sentry. I have updated from `4.8.7` to `4.9.22`.

**Comment by bytehead** [comment]
I couldn't actually track it down yet.

**Comment by tinokramm** [comment]
> The cid parameter has been introduced in 3cab24e three and a half years ago in Contao 4.6.0. Without the parameter, the download will not work - at least in a vanilla Contao 4.9+ installation.

Das mag ja sein, erklärt aber das Verhalten nicht auf meinen Websites. Siehe die Links, die ich oben zum Vergleichen gepostet habe.

**Comment by bytehead** [comment]
Any extension installed that could somehow interfere with the downloads?

**Comment by tinokramm** [comment]
![image](https://user-images.githubusercontent.com/42606103/142633362-5aa2130f-59c7-4a97-bf32-32adb3ff4af2.png)

**Comment by fritzmg** [comment]
> Das mag ja sein, erklärt aber das Verhalten nicht auf meinen Websites. Siehe die Links, die ich oben zum Vergleichen gepostet habe.

Have you tested this in a fresh Contao 4.9.22 installation?

**Comment by tinokramm** [comment]
Wir haben diverse Websites laufen, die wir mit Contao 4.9 begonnen haben. Dort ist solch ein Problem bislang nicht aufgetaucht. Ich vermute das Problem entsteht beim Sprung von 4.4 auf 4.9. Das haben wir gerade bei zwei Websites gemacht und haben bei beiden das gleiche Problem.

**Comment by fritzmg** [comment]
If the problem cannot be reproduced in a fresh Contao installation, then the source of the problem must be some kind of customisation.

**Comment by netzarbeiter** [comment]
Hast du noch ein angepasstes Download-Template aus Contao 4.4?

**Comment by tinokramm** [comment]
Ja. Das gab es tatsächlich und scheint auch Teil des Problems gewesen zu sein. Danke für den Tipp! Jetzt geht es wieder, wie es soll.

**Comment by tinokramm** [comment]
Was mir da an der Stelle unangenehm auffällt ist, wenn ich dem Download-Element sage „Im Browser anzeigen“, habe ich keine Einstellungsmöglichkeit, das in einem neuen Fenster zu tun.

**Comment by fritzmg** [comment]
> Was mir da an der Stelle unangenehm auffällt ist, wenn ich dem Download-Element sage „Im Browser anzeigen“, habe ich keine Einstellungsmöglichkeit, das in einem neuen Fenster zu tun.

Please create a separate ticket for feature requests.
