### ISSUE TITLE
Render the div.limit_toggler only when needed

### ISSUE THREAD

**Issue by Aybee** [contao/contao#3707]
**Affected version(s)**

Contao 4.9.22 or Contao 4.12.3

**Description**
Go to online demo. Create a content element text with` lorem[softbrake]ipsum` (see screenshot). The limit_toggler gets rendered (although it's not necessary), as the last element has a margin to the bottom.

You can avoid this by adding this CSS:
```css
.limit_height [class^=ce_] :last-child {
   margin-bottom: 0;
 }
```

Closed
![Bildschirmfoto am 2021-11-19 um 21 48 08](https://user-images.githubusercontent.com/1143013/142690091-0ceaee29-b437-442c-a216-914e9aee81c4.png)
Opened
![Bildschirmfoto am 2021-11-19 um 21 48 18](https://user-images.githubusercontent.com/1143013/142690090-d0c689bb-73ff-4337-951c-82417686c154.png)

**Comment by Aybee** [comment]
Should be easy to implement. 😉

**Comment by m-vo** [comment]
Go ahead! :slightly_smiling_face:

**Comment by zoglo** [comment]
Doesn't seem to be an issue on 5.x anymore

**Comment by aschempp** [comment]
I think we can close this since the limit toggler has been rewritten in https://github.com/contao/contao/pull/6303
