### ISSUE TITLE
Don't reset CSS for ul, ol and li in BE

### ISSUE THREAD

**Issue by Aybee** [contao/contao#3708]
**Affected version(s)**

Contao 4.9.22 or Contao 4.123

**Description**
If you reset margin, padding and list-style for ul, ol and li, we have no nice rendering of lists in several places in BE, e.g. within the help wizzard text. This values should never be reset. Only reset them where needed, e.g. within navigation lists.

[](https://github.com/contao/contao/blob/2cabec850046d20fd005e11501f581d980121323/core-bundle/src/Resources/contao/themes/flexible/basic.css#L19-L28)](https://github.com/contao/contao/blob/2cabec850046d20fd005e11501f581d980121323/core-bundle/src/Resources/contao/themes/flexible/basic.css#L19-L28)

BTW there's too much resetting anyway. E.g. for margins it should be enough to reset it for body and figure
```css
body,
figure {
  margin: 0;
}
```
For Padding you don't have to reset this at all.

**Comment by aschempp** [comment]
Maybe this can be considered in https://github.com/contao/contao/pull/2697? I generally agree with you on the topic, but I don't think we can easily change this in the current backend, as people also rely on this reset.

**Comment by Aybee** [comment]
> ... as people also rely on this reset.

Really, I just can not believe that. The browser style for paragraphs, lists, form elements, tables, buttons, headings ... is always better than none padding and/or margin at all. If you use an element for special purposes e.g. a list for a navigation, you style it anyway.

#2697 is too complicated for me. But I will follow it.

**Comment by fritzmg** [comment]
> Really, I just can not believe that.

What @aschempp probably means is backwards compatibility. This cannot be changed in a feature version. If you did, an extension that styled its back end components according to the current state will suddenly look different when updating Contao.
