### ISSUE TITLE
Follow-up registration is not possible under certain conditions

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#3709]
**Affected version(s)**

4.12.3

**Description**

There’s a period of time, when the follow-up registration is impossible, because the token has expired, but the member still exists.

Suppose, token is 23-hours old by the time Cron runs (daily by default). Then, an hour later it expires, and the user essentially stuck until the next cronjob runs (so, by default –  for the next 23 hours). He can’t log in (‘account has been disabled’), he can’t activate (‘invalid token’), and he can’t re-register (‘account exists’).

**Comment by fritzmg** [comment]
@contao/developers I think the `Automator::purgeOptInTokens` cronjob, which currently runs daily, needs to actually run minutely, wdyt?

**Comment by fritzmg** [comment]
But even then there could be a period of up to 59 seconds and 99 milliseconds where a member can neither log in, activate their account or register anew. May be `OptIn::purge` should also be called in `ModuleRegistration::compile` (or rather `tl_member.onload`) for example (and may be other places, e.g. newsletter registration).

**Comment by fritzmg** [comment]
Actually, that would not suffice either. OptIn tokens are kept in the database for 72 hours.

**Comment by aschempp** [comment]
Closed in favor of https://github.com/contao/contao/pull/3711
