### ISSUE TITLE
Einen neuen Ordner erstellen ist für den User nicht erlaubt, Namen ändern auch nicht

### ISSUE THREAD

**Issue by Joam55** [contao/contao#3710]
**Affected version(s)**

Contao 4.13

**Description**

Dateiverwaltung files/user/ 

Dem Benutzer sind alle Dateioperationen in seinem Ordner erlaubt, laut Rechteverwaltung.

Doch der Benutzter kann keinen neuen Ordner erstellen oder einen Bestehenden umbenennen, das Feld ist nicht editierbar.
Auch einen bestehenden Ordner umbennen geht nicht, das Feld ist nicht editierbar.

[screenshot_01](https://user-images.githubusercontent.com/108203/142876813-0f3aa725-5984-49d8-a95a-861dcae3f839.png)

![screenshot_03](https://user-images.githubusercontent.com/108203/142878512-0fbbbbcc-e5ad-4986-8883-03dd818a17a4.png)

https://community.contao.org/de/showthread.php?82041-Benutzer-darf-einen-neuen-Ordner-erstellen-gt-NICHT

**Comment by aschempp** [comment]
Sieht aus als hättest du dem Benutzer die Felder in der Tabelle `tl_files` nicht freigegeben?

**Comment by Joam55** [comment]
> Sieht aus als hättest du dem Benutzer die Felder in der Tabelle `tl_files` nicht freigegeben?

Schau mal den Sceenshot_01, du wirst diese Freigaben meinen, oder?

**Comment by ausi** [comment]
> Schau mal den Sceenshot_01, du wirst diese Freigaben meinen, oder?

Nein. Im Bereich „Erlaubte Felder“ musst du die gewünschten Felder für die Tabelle `tl_files` freigeben.

**Comment by Joam55** [comment]
Oje!  Dankeschön!
Asche auf mein Haupt ... diese Freigabe gabs vermutlich bereits in typolight ...

**Comment by ausi** [comment]
> diese Freigabe gabs vermutlich bereits in typolight ...

Nein, die gibt es erst seit kurzem ☺️
