### ISSUE TITLE
Missing LNG labels when using an insert tag

### ISSUE THREAD

**Issue by qzminski** [contao/contao#3712]
**Affected version(s)**

Contao 4.12

**Description**

The insert tag `{{label::LNG:de}}` outputs an empty string, because the `System::loadLanguageFile('languages')` no longer loads the correct files. I think it happened in this commit, where those files were removed:

https://github.com/contao/contao/commit/8f975da820a9dca0415d9da9b669953a41a502c2#diff-96f48168e3462d4b0437106abbc1dc5d8ec39a9aec76ad1da4a334e4a5ae9990

Could it be a BC break? Or is this new behavior intended?

**Comment by Toflar** [comment]
Imho we just missed also updating the `InsertTags` class to fall back to the new stuff. Wdyt @ausi ?

**Comment by ausi** [comment]
Definitley not intended ☺️, I will check this and fix it.

**Comment by ausi** [comment]
Closed in favor of #3716
