### ISSUE TITLE
Page not found at update

### ISSUE THREAD

**Issue by lobebe** [contao/contao#372]
**Affected version(s)**
Contao 4.4
**Description**  
Hello Leo,

I have just migrated to contao 4 and I have this issue after importing the theme:

> [2019-02-25 02:14:37] request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\CoreBundle\Controller\FrontendController::indexAction","_url_fragment":"tl_files/standard/container-bg.gif","_route":"contao_catch_all"},"request_uri":"[http://horse-sales.com/tl_files/standard/container-bg.gif","method":"HEAD"}](http://horse-sales.com/tl_files/standard/container-bg.gif%22,%22method%22:%22HEAD%22%7D) []
> [2019-02-25 02:14:37] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\CoreBundle\Security\ContaoAuthenticator"} []
> [2019-02-25 02:14:37] request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\CoreBundle\Controller\FrontendController::indexAction","_url_fragment":"tl_files/standard/container-bg.gif","_route":"contao_catch_all"},"request_uri":"[http://horse-sales.com/tl_files/standard/container-bg.gif","method":"GET"}](http://horse-sales.com/tl_files/standard/container-bg.gif%22,%22method%22:%22GET%22%7D) []
> [2019-02-25 02:14:37] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\CoreBundle\Security\ContaoAuthenticator"} []
> [2019-02-25 02:14:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: http://horse-sales.com/tl_files/standard/container-bg.gif" at /usr/www/users/horsesal/DE/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\Component\HttpKernel\Exception\NotFoundHttpException(code: 0): Page not found: http://horse-sales.com/tl_files/standard/container-bg.gif at /usr/www/users/horsesal/DE/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\CoreBundle\Exception\PageNotFoundException(code: 0): Page not found: http://horse-sales.com/tl_files/standard/container-bg.gif at /usr/www/users/horsesal/DE/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:64)"} []
> [2019-02-25 02:14:46] request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\CoreBundle\Controller\FrontendController::indexAction","_url_fragment":"tl_files/standard/container-bg.gif","_route":"contao_catch_all"},"request_uri":"[http://horse-sales.com/tl_files/standard/container-bg.gif","method":"HEAD"}](http://horse-sales.com/tl_files/standard/container-bg.gif%22,%22method%22:%22HEAD%22%7D) []
> [2019-02-25 02:14:46] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\CoreBundle\Security\ContaoAuthenticator"} []
> [2019-02-25 02:14:46] request.INFO: Matched route "contao_catch_all". {"route":"contao_catch_all","route_parameters":{"_scope":"frontend","_token_check":true,"_controller":"Contao\CoreBundle\Controller\FrontendController::indexAction","_url_fragment":"tl_files/standard/container-bg.gif","_route":"contao_catch_all"},"request_uri":"[http://horse-sales.com/tl_files/standard/container-bg.gif","method":"GET"}](http://horse-sales.com/tl_files/standard/container-bg.gif%22,%22method%22:%22GET%22%7D) []
> [2019-02-25 02:14:46] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\CoreBundle\Security\ContaoAuthenticator"} []
> [2019-02-25 02:14:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: http://horse-sales.com/tl_files/standard/container-bg.gif" at /usr/www/users/horsesal/DE/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\Component\HttpKernel\Exception\NotFoundHttpException(code: 0): Page not found: http://horse-sales.com/tl_files/standard/container-bg.gif at /usr/www/users/horsesal/DE/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\CoreBundle\Exception\PageNotFoundException(code: 0): Page not found: http://horse-sales.com/tl_files/standard/container-bg.gif at /usr/www/users/horsesal/DE/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:64)"} []
**How to reproduce**

**Comment by xchs** [comment]
Please refer to the [forums](https://community.contao.org) for this kind of question.

**Comment by lobebe** [comment]
Yes, I have been trying to do that since morning but it won't allow me add my complaint.

**Comment by fritzmg** [comment]
Yeah, the english forums need some serious maintenance …

Regarding your problem: you still have your files in `tl_files` rather than `files`. You need to rename the folder to `files` and then manually update your database. Use the following query at your own risk (make sure you have a backup before executing this):
```sql
UPDATE `tl_files` SET `path` = REPLACE(`path`, 'tl_files/', 'files/') WHERE `path` LIKE 'tl_files/%';
```
After that, execute `composer install -o`.

**Comment by lobebe** [comment]
Thank you Fritzmg, I have done that but the images are still not showing and I notice when I click to open image in a new tab, it redirects to home. Is there something that I am missing? 
Please help. Thank you again.

**Comment by fritzmg** [comment]
>  I have done that but the images are still not showing

Did you make the folder of the images public?

> and I notice when I click to open image in a new tab, it redirects to home

I am guessing you added a 404 page to your site structure and enabled a redirect there.

**Comment by xchs** [comment]
`tl_files/standard/container-bg.gif` could be an image reference path in one of your style sheets. Did you check that?

**Comment by lobebe** [comment]
> `tl_files/standard/container-bg.gif` could be an image reference path in one of your style sheets. Did you check that?

Thank you, I got the container-bg.gif sorted out

**Comment by lobebe** [comment]
> > I have done that but the images are still not showing
> 
> Did you make the folder of the images public? 
I have made the images public but still not showing.
> 
> > and I notice when I click to open image in a new tab, it redirects to home
> 
> I am guessing you added a 404 page to your site structure and enabled a redirect there.

Please see my htaccess here:

**Comment by fritzmg** [comment]
Please edit your post and put your `.htaccess` on [Pastebin.com](https://pastebin.com) instead.

**Comment by lobebe** [comment]
> Please edit your post and put your `.htaccess` on [Pastebin.com](https://pastebin.com) instead.

Here is it: 
[https://pastebin.com/embed_iframe/4E7BT9VX](url)

**Comment by fritzmg** [comment]
> I have made the images public but still not showing.

So you went into the file manager in the Contao backend, edited the folder, in which the images reside, and selected _Public_?

> Please see my htaccess here:

Your .htaccess has nothing to do with that. I mean in your _site structure_ in the Contao back end.

> Here is it:
> [https://pastebin.com/embed_iframe/4E7BT9VX](url)

Please edit your post, you just need to post the link to the pastebin - not an iframe embed.

This is an old `.htaccess` from Contao 3. The `.htaccess` of Contao 4 should look quite different.

**Comment by xchs** [comment]
This is probably an old Contao 3 `.htaccess` that you have placed in your Contao root directory. For Contao 4 there must be a `.htaccess` in the `web/` subfolder.

Nevertheless, your `.htaccess` seems to work, otherwise you wouldn't be able to open the [back end login mask](http://horse-sales.com/contao/login) and the front end pages.

**Comment by lobebe** [comment]
> This is probably an old Contao 3 `.htaccess` that you have placed in your Contao root directory. For Contao 4 there must be a `.htaccess` in the `web/` subfolder.

Yes,, there is .htaccess in the web folder. Should I delete the one in the root?

**Comment by xchs** [comment]
> Should I delete the one in the root?

You could rename that `.htaccess` in the root directory to something like `.htaccess.contao35`

**Comment by lobebe** [comment]
> > Should I delete the one in the root?
> 
> You could rename that `.htaccess` in the root directory to something like `.htaccess.contao35`

Thank you

**Comment by lobebe** [comment]
> > I have made the images public but still not showing.
> 
> So you went into the file manager in the Contao backend, edited the folder, in which the images reside, and selected _Public_?
> 
> > Please see my htaccess here:
> 
> Your .htaccess has nothing to do with that. I mean in your _site structure_ in the Contao back end.
> 
> > Here is it:
> > [https://pastebin.com/embed_iframe/4E7BT9VX](url)
> 
> Please edit your post, you just need to post the link to the pastebin - not an iframe embed.
> 
> This is an old `.htaccess` from Contao 3. The `.htaccess` of Contao 4 should look quite different.

I added /files to the Files URL but still images are not showing.

**Comment by xchs** [comment]
We should really discuss this in the forum and not here.

Are you registered in the [English](https://community.contao.org/en/) or [German](https://community.contao.org/de/) forum?

**Comment by lobebe** [comment]
> We should really discuss this in the forum and not here.
> 
> Are you registered in the [English](https://community.contao.org/en/) or [German](https://community.contao.org/de/) forum?

I registered on the English forum but it won't allow me to post on it.

**Comment by xchs** [comment]
Would you mind registering in the [German forum](https://community.contao.org/de/), too? You can also write there in English if you want.

**Comment by lobebe** [comment]
I have registered both on German and English but no luck. With German I am still yet to receive the confirmation code while on the English, I cannot lay my complaints because there is no option to do that.

**Comment by lobebe** [comment]
I need help with a replacement for module. I was using catalog by xtra on Contao2. I have upgraded to 4.7 and now catalog is not compatible, I tried to install metamodel which I see it is the replacement for catalog but it doesn't seem to be compatible with 4.7. Is there any replacement for Catalog that is compatible with Contao 4.7?

Thank you in advance.

**Comment by xchs** [comment]
What is your username on the German forum? We have had some problems with the e-mail notifications for the last few days.

**Comment by lobebe** [comment]
I used lobebe

**Comment by xchs** [comment]
There is currently no open registration request for this username. Can you please try again?

**Comment by lobebe** [comment]
The e-mail address you entered is already in use. Did you forget your password?

**Comment by xchs** [comment]
What email address did you use?

**Comment by lobebe** [comment]
So sorry, my username is adeola.

**Comment by xchs** [comment]
Ok. I just sent you the activation mail again.

**Comment by xchs** [comment]
Your account is now activated.

**Comment by lobebe** [comment]
Thank you

**Comment by xchs** [comment]
@leofeyer You may want to delete the ticket since we can discuss the problem in the forum now.
