### ISSUE TITLE
Backend back button wrong redirect

### ISSUE THREAD

**Issue by Vec7or** [contao/contao#3730]
**Affected version(s)**

Contao 4.12.3

**Description**

When editing elements of an element in the backend ex. news in news archive and going back over the menu bar the back button does not work as expected anymore.

Steps to reproduce:

1. Have two news archives (called "one" and "two" for simplicity)
2. Open archive "one" and open a news item
3. Return to the news archive overview by clicking on "news" in the navigation bar
4. Open the other archive "two" and open a news item
5. Klick on the back button and now you are in the overview of archive "one" instead of archive "two"

This behaviour is also reproducible with similar structures like events.

**Comment by Toflar** [comment]
I think that‘s a duplicate of https://github.com/contao/contao/pull/3690

**Comment by Vec7or** [comment]
@Toflar Sounds like the same issue. So this should be fixed with the next releases. Thanks for the info.
