### ISSUE TITLE
Urlattr suffix not consistent when used with tinyMCE filepicker

### ISSUE THREAD

**Issue by Vec7or** [contao/contao#3731]
**Affected version(s)**

Contao 4.12.3 / 4.9.22

**Description**

When using filepicker within tinyMCE content elements the behaviour of the "urlattr" suffix is not consistent.

Steps to reproduce:

1. Select file with file selector in tinyMCE
    - "urlattr" is attached as a suffix to the insert tag (not visible in file selector but in database)
2. Save the content element
3. Open the content element again and change something inside the tinyMCE content element
4. Save the content element again
    - The "urlattr" suffix is now no longer present on the insert tag

**Comment by ausi** [comment]
This probably needs to be fixed in https://github.com/contao/contao/blob/b1419cc981cf59fd451342863494e61b0ed04c07/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L618

Did you test if the same issue also occurs in Contao 4.9?

**Comment by Vec7or** [comment]
@ausi I just tested this behavior with a newly installed Contao 4.9.22 and it is the same with this version.
