### ISSUE TITLE
Browser login auto fill prevents member drop down in preview bar

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3733]
**Affected version(s)**

Contao 4.9, 4.12, 4.x

**Description**

While working on https://github.com/contao/contao/pull/3732 I noticed the following: currently at least Firefox will always show the login auto fill/complete drop down when clicking into the username field for the member in the preview bar. This will prevent the `userlist` dropdown from showing, when you enter parts of a front end member username:

![2021-11-27 (2)](https://user-images.githubusercontent.com/4970961/143679412-62eb6548-cb75-4f2d-8ba8-db8f164daeea.png)

`autocomplete="off"` will not work here, because browsers will ignore `autocomplete="off"` completely for any detected login input fields (see [here](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields).

As far as I have analysed, Firefox auto detects this input field as a username input field solely because of `placeholder="Username"`. If the attribute is removed or renamed to `placeholder="Foobar"`, then Firefox will not consider this field as a login field anymore and not offer the login auto fill:

![2021-11-27 (1)](https://user-images.githubusercontent.com/4970961/143679506-db538c8e-f419-43c5-a8c2-9e13c4c5b61e.png)

Removing the `placeholder` or changing the translation to not say "Username" just to get Firefox to ignore this field is of course not ideal. May be someone can come up with something better?

**Comment by ameotoko** [comment]
May be just say “Username” as a label? Instead of “Member”

**Comment by fritzmg** [comment]
@leofeyer why did you close this?

**Comment by leofeyer** [comment]
<img width="558" alt="" src="https://user-images.githubusercontent.com/1192057/143884219-1770f230-c1bd-400f-94f0-98b5c9c52742.png">

Does your PR not fix the issue?

**Comment by leofeyer** [comment]
<img width="557" alt="" src="https://user-images.githubusercontent.com/1192057/143884381-13e457a1-2cc2-47c5-bfe6-44ecb466feb8.png">

**Comment by fritzmg** [comment]
I did not specifically link it, Github did that automatically via this comment: https://github.com/contao/contao/pull/3732#discussion_r758146252
I have removed the link now.
