### ISSUE TITLE
CSRF Cookie is blocked due samesite Lax on 3rd party pages

### ISSUE THREAD

**Issue by biwerr** [contao/contao#3736]
**Affected version(s)**

Contao 4.9

**Description**

The Contao CSRF Token is set with the property 'lax' in [CsrfTokenCookieSubscriber](https://github.com/contao/core-bundle/blob/d20147f5a9e51115769eafb58876bba0a035f2aa/src/EventListener/CsrfTokenCookieSubscriber.php#L122) which leads to problems on 3rd party sites with iframe integrations of the Contao page.

![image](https://user-images.githubusercontent.com/6122710/143841630-cdb31a03-753f-4196-b2af-7a2efdca0efc.png)

**Solution**

In order to use the Cookie on 3rd party pages, the setting have to be 'none' ([Source](https://arcagarwal.medium.com/same-site-changes-in-chrome-1c86973454f9))

> SameSite=Nonemeans cookies of first party will be passed in third party context.
SameSite=Lax Cookies with this setting are sent only on same-site requests or top-level navigation with non-idempotent HTTP requests, like HTTP GET.Top-level means that the URL in the address bar changes because of this navigation. This is not the case for iframes, images or XMLHttpRequests.

```php

//core-bundle\src\EventListener\CsrfTokenCookieSubscriber::setCookies
...
$response->headers->setCookie(
    new Cookie($cookieKey, $value, $expires, $basePath, null, $isSecure, true, false, ($isSecure ? Cookie::SAMESITE_NONE : Cookie::SAMESITE_LAX))
);
...
```

**Comment by ausi** [comment]
This is the intended behavior I think, because with iframes and clickjacking you would then be able to send POST requests on behalf of the user, which is exactly what the CSRF cookie tries to prevent.

Can you elaborate on your use-case so that we can maybe suggest a secure alternative?

**Comment by biwerr** [comment]
In our case we have multiple Iframe integrations on other pages where users can donate to a project. Donation is done in a Form, at the moment submitting the form is not possible, because the csrf token is not valid, due the missing cookie.

It would be great if there was an option to configure this behavior in a config file, to enable setting csrf tokens with `same-site:none` so that the csrf cookie is set within the iframe.

**Comment by ausi** [comment]
Are these users logged in? And has the iframe to know the logged in user?

If not, configuring all other cookies to `samesite=lax` should fix your issue I think. 
The session cookie itself can be configured like so:

```yaml
framework:
    session:
        cookie_samesite: lax
```

**Comment by biwerr** [comment]
No, the users are guests. But they have a session cookie. I've tested it with settings above before I opened the ticket. The session cookie is set, but it sadly doesn't fix the problem. Lax would not fix the issue. The Browser blocks the cookie, with the warning message

> "SameSite=Lax" and was blocked because it came from a cross-site response which was not the response to a top-level navigation. The Set-Cookie has to have been set with "SameSite=None" to enable cross-site usage

**Comment by ausi** [comment]
In this case you can use a listener to modify the cookie like so:

```php
<?php

declare(strict_types=1);

namespace App\EventListener;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpKernel\Event\ResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;

class CsrfSameSiteCookieListener implements EventSubscriberInterface
{
    public function onKernelResponse(ResponseEvent $event): void
    {
        if (!$event->isMainRequest()) {
            return;
        }

        $responseHeaders = $event->getResponse()->headers;

        foreach ($responseHeaders->getCookies() as $cookie) {
            if ($cookie->getName() === 'csrf_https-contao_csrf_token') {
                $responseHeaders->setCookie($cookie->withSameSite(Cookie::SAMESITE_NONE));
            }
        }
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::RESPONSE => ['onKernelResponse', -833],
        ];
    }
}
```

But you have to double check that all domains you list in the `X-Frame-Options` header are fully trusted, otherwise you might create a security issue by this.

> It would be great if there was an option to configure this behavior in a config file

I don’t think we should add an option for this as the security implications are not easy to understand and you can already configure it via a listener as shown above.

**Comment by biwerr** [comment]
Thanks for the Listener, seems to be a good idea as a workaround for my issue. I'll try if this works for me :)

**Comment by aschempp** [comment]
maybe you can also adjust the system so the users do not have a session (if they are guests anyway)?
