### ISSUE TITLE
Vorschau einer unveröffentlichten Seite endet in Page not found

### ISSUE THREAD

**Issue by wiphi** [contao/contao#374]
**Affected version(s)**
Contao 4.7.0
Contao 4.7.1

**Description**  
Eine derzeit nicht veröffentlichte Seite kann nicht über die Vorschau Funktion "Unveröffentlichte Elemente anzeigen" angezeigt werden.

Es erscheint ein `Page not found` Error.

**How to reproduce**  
Reproduziert mit der Online-Demo:

- eingeloggt im Backend
- in der Seitenstruktur die Seite "Text elements" die Seite unveröffentlichen
- Vorschau des Frontends öffnen
- Unveröffentlichte Elemente anzeigen - Anwenden
- Zu Content Elements - Text elements navigieren
- Page not found

Edit:
Das Problem tritt nicht auf, wenn die Seite mit dem `app_dev.php` Entry Point aufruft.

**Comment by leofeyer** [comment]
@aschempp Could this be a routing issue?

**Comment by aschempp** [comment]
Sounds like it, but it shouldn't be. See https://github.com/contao/contao/blob/master/core-bundle/src/Routing/Matcher/PublishingFilter.php

**Comment by aschempp** [comment]
However… now that I look at it: Security is not available during routing, because security is based on the matched URL 🤦‍♂️

**Comment by leofeyer** [comment]
As briefly discussed with @aschempp, we have to get rid of the `PublishingFilter` and check the publishing status in the controller (see #405).

**Comment by leofeyer** [comment]
I am re-assigning this to the 4.8 milestone as a reminder to revert the changes in Contao 4.8 (where we have a different entry point for the front end preview).
