### ISSUE TITLE
Remove page from index, if `Do not search` is checked

### ISSUE THREAD

**Issue by tsarma** [contao/contao#3740]
**Affected version(s)**

Contao 4.9.22

**Description**

Remove page from the search index, if it is already indexed by Contao, when in afterwards `Do not search` is checked from the pages setting.

**Comment by fritzmg** [comment]
Should be doable in a `config.submit` callback where we check whether `noSearch` was set in the current request and then delete all items from `tl_search_index` and `tl_search` with the current page's ID. @contao/developers wdyt?

**Comment by aschempp** [comment]
sound legit. Maybe @tsarma can do a pull request? 😎
