### ISSUE TITLE
Why using meta "link" for download elements?

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#375]
What is the reason using meta information "link" for download elements (CE Download and Downloads) and not the "title"?

I have the case, that an image is used as a normal image within ce_text and the meta info "link" is filled with a website link, so you can click on the image to follow the link. The same image is used within a ce_downloads and the title of the download is the website address but it should be the "title". I know, that I can change it in my template, but I just want to discuss, why we don't use the "title" instead of "link" for download elements.

**Comment by asaage** [comment]
I dont't see where ```meta->link``` is used in the ce_download template at all.

https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/elements/ContentDownload.php#L110
https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/elements/ContentDownload.php#L133

may be it's a flaw in the extension you referenced?
https://github.com/hofff/contao-recursive-download-folder/blob/master/system/modules/hofff_recursive-download-folder/elements/ContentRecursiveDownloadFolder.php#L254

**Comment by frontendschlampe** [comment]
It's used in the template: https://github.com/contao/contao/blob/9874b3009644746fd09a7acfeaa0c91b7f35a9da/core-bundle/src/Resources/contao/templates/elements/ce_download.html5#L6

And you can check in your own installation: fill out meta title or link for a file and see, what's used in download elements.

Meta title is just used for the link title.

**Comment by fritzmg** [comment]
So instead of
```html
<a href="files/public/foo.pdf" title="Die Datei files/public/foo.pdf herunterladen">Meta title of the file</a>
```
you want
```html
<a href="files/public/foo.pdf" title="Meta title of the file">files/public/foo.pdf</a>
```
?

Imho the current way is better, because I would expect the meta title to be displayed for the download link, when present (and otherwise just the filepath).

**Comment by frontendschlampe** [comment]
No ... actually the meta link attribute is used for the link of the file. And if meta link is empty, the file name is used. So if the meta link is filled with an URL to a website, the website-URL is used for the name.

Current usage in Contao:
title tag of download link: meta title, if empty just filename
name of download link: meta link, if empty just filename

```
<a href="files/public/foo.pdf" title="Download meta title of file">Meta link of the file</a>
```

I think it's better to use meta title for name of link instead of meta link. But I don't know why actually link is used for download elements. Maybe there's a reason not using meta title, but I don't see it.

**Comment by fritzmg** [comment]
I still don't quite get what you mean - or I cannot reproduce it at least. This is the HTML output of a link of the `ce_downloads` element of a file without any meta information in the file manager:
```html
<a href="?file=files/test/file-without-meta.jpg&amp;cid=7" title="Download file-without-meta.jpg">file-without-meta.jpg <span class="size">(126.2 KiB)</span></a>
```
This is the HTML output of a link of the `ce_downloads` element of a file with all meta information in the file manager:
```html
<a href="?file=files/test/file-with-meta.jpg&amp;cid=7" title="Download file-with-meta.jpg">Meta title of the file <span class="size">(160.3 KiB)</span></a>
```
![screenshot_2019-02-26 file manager files test file-with-meta jpg - contao open source cms](https://user-images.githubusercontent.com/4970961/53409596-9acb5900-39c1-11e9-92ed-4c25baef519c.png)

What exactly should be different?

**Comment by frontendschlampe** [comment]
I think, you have an individual download template in your example, because the original Contao template uses meta link and not meta title for the name of a-tag?!

**Comment by fritzmg** [comment]
No, this is a vanilla Contao 4.7.1 installation.

**Comment by fritzmg** [comment]
This is the output in Contao 4.4.35:
```html
<a href="?file=files/test/file-without-meta.jpg" title="Download file-without-meta.jpg">file-without-meta.jpg <span class="size">(126.2 KiB)</span></a>
```
```html
<a href="?file=files/test/file-with-meta.jpg" title="Download file-with-meta.jpg">Meta title of the file <span class="size">(160.3 KiB)</span></a>
```
The meta "link" attribute is never used, as expected.

**Comment by frontendschlampe** [comment]
*wtf ... here https://github.com/contao/contao/blob/9874b3009644746fd09a7acfeaa0c91b7f35a9da/core-bundle/src/Resources/contao/templates/elements/ce_download.html5#L6

```<?= $this->link ?>``` is used, but I think there's somewhere any magic, that link is not meta link. I don't know, why I had the problem. :-(

**Comment by fritzmg** [comment]
> `<?= $this->link ?>` is used

This is just a template variable name ;). The variable is filled in the corresponding content element class. See @asaage 's [comment](https://github.com/contao/contao/issues/375#issuecomment-467357155).

**Comment by frontendschlampe** [comment]
I was confusing here about the variable name, I think. I should take the time to check carefully. ;-) But now we know it already. :-D I'm sorry for confusing.

**Comment by CMSworker** [comment]
I'm having the same problem I guess (Contao 4.4.39 LTS) and think this issue should be reopened:

When using **ce_download** (singular for one single download, not plural), the **meta titel** of the file (entered manually in file manager) is ignored.

https://github.com/contao/contao/blob/945fd7ed1b90f5d97916abb380dd2c54de0a57e4/core-bundle/src/Resources/contao/templates/elements/ce_download.html5#L6

I only get the filename as linktext in html output.

Please test again with **ce_download** (not "ce_downloads") to confirm this issue.

**Comment by leofeyer** [comment]
@CMSworker I cannot reproduce your issue.

<img width="510" src="https://user-images.githubusercontent.com/1192057/57448983-0bf97900-725b-11e9-8d18-ce3f37636378.png">

Now if I add a title in the file manager, it is used instead of the file name:

<img width="613" src="https://user-images.githubusercontent.com/1192057/57448993-1156c380-725b-11e9-96f5-09cb3021db35.png">

<img width="470" src="https://user-images.githubusercontent.com/1192057/57449001-161b7780-725b-11e9-9dbc-8e206baf2762.png">
