### ISSUE TITLE
Preview mode unpublished: show does not work

### ISSUE THREAD

**Issue by bytehead** [contao/contao#3752]
**Affected version(s)**

Contao 4.x

**Description**

In frontend preview mode `show unpublished` does not work anymore. Login with frontend user still works.

**Comment by leofeyer** [comment]
<del>This is due to the preview switch form pointing to `/preview.php/contao/preview_switch`, which will be redirected to `/contao/preview_switch` unless we add the `_allow_preview` request attribute (see #3692).</del>

That's not it, unfortunately.

**Comment by leofeyer** [comment]
However, the `BackendPreviewSwitchController` already has the `_allow_preview` attribute, so it seems to be something else.

**Comment by leofeyer** [comment]
Found it.

https://github.com/contao/contao/blob/2515c850fea177f01d2e9c6ec57519f3548304d2/core-bundle/src/Controller/BackendPreviewSwitchController.php#L125

`$frontendUsername` is an empty string instead of `null` here. It can be fixed like this:

```php
if ($frontendUsername) {
    $this->previewAuthenticator->authenticateFrontendUser((string) $frontendUsername, $showUnpublished);
} else {
    $this->previewAuthenticator->authenticateFrontendGuest($showUnpublished);
}
```

**Comment by bytehead** [comment]
Closing in favor of #3837.
