### ISSUE TITLE
Search index does not work with insertTag

### ISSUE THREAD

**Issue by tsarma** [contao/contao#3768]
**Affected version(s)**

Contao 4.9

**Description**
Contao search indexer does not work (It does not index page), if you have an insert tag in a content.

**Comment by Toflar** [comment]
I don't think that's true? Can you tell us how to reproduce the problem?

**Comment by tsarma** [comment]
I've tested it. To reproduce just add `{{br}}` in any text field or heading input.

**Comment by tsarma** [comment]
Sorry false alarm!
