### ISSUE TITLE
Error message appears above wrong form on pages with multiple login forms

### ISSUE THREAD

**Issue by maettyhawk** [contao/contao#377]
**Affected version(s)**
4.4.28

**Description** 
On pages with multiple login forms error messages always seem to be displayed in the first form.

**How to reproduce**  
1.) Build page with two login forms
2.) Login with wrong credentials using the second form
3.) Error message appears in first form

**Comment by fritzmg** [comment]
Before reporting a bug, you should always update to the latest version and test there.

**Comment by asaage** [comment]
Can be reproduced on 4.7.1
But having multiple login-forms on one page seems to be a weird thing to do.
