### ISSUE TITLE
Form file upload -> save as UUiD

### ISSUE THREAD

**Issue by lumas-consulting** [contao/contao#3771]
When using the file upload attribute in a form generator and ad the save to database functionality, currently **the path to the file** will be saved to the database.

Wouldn't it be better to **save the UUID** as it does when uploading a file in the backend?

**Comment by fritzmg** [comment]
You can use [fritzmg/contao-store-uuid](https://extensions.contao.org/?p=fritzmg%2Fcontao-store-uuid).

**Comment by lumas-consulting** [comment]
Thank you @fritzmg !
Will try.
But is there a specific reason for using the path as default format?

**Comment by fritzmg** [comment]
By default the form generator makes no assumption on how the upload is used. The UUID is only relevant if you store the file in a table that is managed by a DCA - and the respective field uses the `fileTree` for instance.
