### ISSUE TITLE
Allow preview of non-routeable pages

### ISSUE THREAD

**Issue by aschempp** [contao/contao#3775]
I noticed these changes will result in that the error page types (and other non-routable) pages can no longer be previewed in the front end. The only way to "see" the `401 Access Denied` page is now by accessing a protected page without being logged in. This might be cumbersome to style the page and content, maybe we should allow routing these pages in preview or dev mode?

_Originally posted by @aschempp in https://github.com/contao/contao/issues/3605#issuecomment-986801656_

**Comment by fritzmg** [comment]
I think I would do it for the `_preview`, not just for the dev mode. Then editors will be able to quickly preview the 40x pages' contents by clicking the respective icon in the back end.

**Comment by leofeyer** [comment]
+1 for only in preview mode.

**Comment by aschempp** [comment]
That might work, although only works in a managed edition (or if the preview entry point is manually configured in a Symfony app). It also will not work for pages that do not have an alias (which they _supposedly do not have_ if not routable!).
An alternative idea would be to extend the preview controller. We currently pass `page=XX` to the preview route, which could render the page as a subrequest (which only requires the controller and not a path) instead of forwarding to the frontend URL.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/3797
