### ISSUE TITLE
Redirecting to article list after content element insert

### ISSUE THREAD

**Issue by lumas-consulting** [contao/contao#3779]
**Affected version(s)**

Contao 4.9.23 

**Description**

Backend Issue:
After the Update to 4.9.23 user is being redirected to the article overview after copying and inserting a content element within an article.
One should stay within the article that the CE is inserted in.

**Comment by bytehead** [comment]
Maybe related to #3690 
/cc @Toflar

**Comment by contaoacademy** [comment]
I have also observed the same behavior with "Save & Close". Here I suddenly end up in a completely different place in the backend.
It seems that at some point the referrer is saved, but then no longer is updated.

I'll try to check and reproduce the problem and give you more details.

See also Slack: https://contao.slack.com/archives/CK4J0KNDB/p1638956416218900

**Comment by fritzmg** [comment]
I can reproduce the problem:

1. Log out of the Contao back end.
2. Log into the Contao back end of Contao 4.9.23/4.9.x-dev.
3. Go to _Articles_.
4. Go into an article (with existing content elements).
5. Click the copy icon of a content element.
6. Insert the content element into the same article.
7. Click _Save & Close_.

You will be redirected to the dashboard.

**Comment by leofeyer** [comment]
@eBlick Can you please try if removing the following lines fixes the issue?

https://github.com/contao/contao/pull/3690/files#diff-86b4078961bee6db60db2699805d6b88f4c7ee6fcfc0435bed2f8c2f66d1311bR92-R94

**Comment by lumas-consulting** [comment]
@leofeyer Yes, I can **confirm** that this did the job!
Tested with articles, new archives and file management.
Copy & Paste as well as Cut & Paste
