### ISSUE TITLE
Query parameters are lost during redirect back after login

### ISSUE THREAD

**Issue by leonexcc** [contao/contao#3782]
We want to use GA campaigns on a website that is behind a login. If the visitor isn't login already he will be redirected to the login page here:

https://github.com/contao/contao/blob/27f248764c86bd9929ec1b961c9241b5e593c9e2/core-bundle/src/Resources/contao/pages/PageError401.php#L137

But since the Environment::get('request') is not urlencoded everything after the first & in Environment::get('request')  is lost on the redirect back. If i change this line to
```
$url = $objNextPage->getAbsoluteUrl() . '?redirect=' . urlencode(Environment::get('base') . Environment::get('request'));
```
it seems to work.

**Comment by fritzmg** [comment]
You can circumvent this by changing your setup:

1. Create a 401 page (if not already present) and do _not_ enable any redirect setting in the page.
2. Create a login module and do _not_ enable any redirect setting in the login module.
3. Put this login module onto the 401 page.

If open a protected URL without being logged in then no redirect will happen. Instead the contents of the 401 page will be shown with the login module. When the login module is used to login, again no redirect will happen and the visitor should see the page - and the query parameters should still exist.

**Comment by leonexcc** [comment]
Ok, i have to try that. But shouldn't the redirect URL be encoded correctly anyways?

**Comment by fritzmg** [comment]
imho yes

**Comment by leonexcc** [comment]
We decided to hot-patch this in our application and we hope this gets fixed some day.

**Comment by fritzmg** [comment]
Did you try my suggestion? Imho the setup I described is best practise anyway.

**Comment by leonexcc** [comment]
We didn't want to change to much in our current setup. And we actually liked the redirect function. With the one line patch everything worked like a charm. So we went with "Never change a running system (to much)".
In a new system i might do it like the setup above (for some reason it seams more intuitive with the redirect to me). But i still think this should be fixed too, since this missing encoding is not right in my opinion.

**Comment by leonexcc** [comment]
I still think this is a bug. How can we get this confirmed. And would it help if i submit a pull request?

The fix itself is simple but i don't know if we can make unit tests for this and how.

**Comment by fritzmg** [comment]
> And would it help if i submit a pull request?

Yes :)

> The fix itself is simple but i don't know if we can make unit tests for this and how.

I don't think this particular class is covered by a unit test. In any case we can then help. Also keep in mind that the same adjustment might be necessary for the 403 and 404 page types as well.

**Comment by leonexcc** [comment]
I checked the other page types, but they don't send the original page with the redirect. This is only done from the 401 to redirect back in the login module.
