### ISSUE TITLE
Configuration file format

### ISSUE THREAD

**Issue by aschempp** [contao/contao#38]
I know this has been discussed before, but we should "write down" the final decision regarding configuration file format.

Afair @leofeyer said we should use YAML because it's easer, but later on said we could potentially use XML. Now I noticed Symfony core bundles seem to use XML everywhere, and I also read that XML supports more features. I also find it more readable.

I like [Christian's idea](http://www.testically.org/2011/03/01/do-you-want-yaml-with-the-symfony2-application-i-think-i-prefer-xml-to-go-with-the-bundle/) of using XML for bundles but YAML for the application in general.

Can we vote on the topic?

**Comment by aschempp** [comment]
@Toflar @discordier @leofeyer @tristanlins

**Comment by leofeyer** [comment]
No need to vote IMHO, because Symfony best practice clearly recommends to use YAML.

**Comment by discordier** [comment]
I am with @leofeyer on this one. YAML is the standard recommendation, we should use it.

Sidenote: For my private bundles I prefer to use annotations wherever possible but this merely because it's "faster" to build.

**Comment by aschempp** [comment]
Can you give me a hint about the best practice, if the Symfony bundles are not?

**Comment by leofeyer** [comment]
http://symfony.com/doc/current/best_practices/index.html

**Comment by aschempp** [comment]
Well this is only related to the application configuration, and not bundles. If you read the link in my initial post, I meant to use XML for bundles and YAML for the application configuration.

**Comment by leofeyer** [comment]
Ok, then let's vote. -1 for XML from me.

**Comment by Toflar** [comment]
YAML is fine for me too, it's easier to read and apart from validating against a schema I don't see any advantage for XML. +1 for YAML or -1 for XML, you name it.=

**Comment by leofeyer** [comment]
We have +3 for YAML and +1 for XML, so it is YAML then.

**Comment by aschempp** [comment]
Thanks for closing, I agree.
