### ISSUE TITLE
backend login is not possible after 2 days of installation contao 4.12

### ISSUE THREAD

**Issue by FranziskaMa** [contao/contao#3802]
**Affected version(s)**

Contao 4.12?

**Description**

backend login is not possible
the setup was an update from 3.5.4

**Comment by fritzmg** [comment]
Make sure you run a `composer update` again, so that `symfony/http-kernel` is downgraded to `5.4.0`, if applicable (see https://github.com/contao/conflicts/pull/32).

**Comment by FranziskaMa** [comment]
What is a composer update?

**Comment by fritzmg** [comment]
If you manage your Contao instance with the Contao Manager, then you need to execute this under _Maintenance_:

![image](https://user-images.githubusercontent.com/4970961/145618446-2ec98fa5-b295-4e01-87b1-9347a5864be0.png)

**Comment by FranziskaMa** [comment]
to do this, I first have to be logged in to Contao. This won't do!

**Comment by FranziskaMa** [comment]
Thank you!!!
