### ISSUE TITLE
Different Twig templates cannot be selected in the backend

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#3805]
**Affected version(s)**

4.12

**Description**

Wenn ich zwei verschieden Twig-Templates anlege z.B. ce_image.html.twig und ce_image_test.html.twig dann können diese in den Template-Einstellungen im Backend  nicht ausgewählt werden.
siehe auch https://contao.slack.com/archives/CK4J0KNDB/p1639302648298700

**Comment by m-vo** [comment]
Probably covered by https://github.com/contao/contao/issues/3274

**Comment by m-vo** [comment]
see #4121
