### ISSUE TITLE
Configuring the crawler in the back end

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3809]
As discussed with @Toflar, we want to add two options to the crawler in the back end: concurrency and max depth. Both should be set to `5` by default. The maximum number of requests will be calculated as `setMaxRequests($concurrency * 4)`.

![](https://user-images.githubusercontent.com/1192057/145795883-9961bba9-d816-4618-ae9c-a4fbcc7eef2c.png)

**Comment by m-vo** [comment]
:+1: in genereal, though I'm not sure whether a user does understand the implications of `Concurrency`. Shouldn't this be a system configuration?

**Comment by Toflar** [comment]
It's configurable on the CLI as well so I don't think that's needed.
However, ideally I would like to hide those options in some `Advanced options` legend maybe or whatever. That's why I have never created a PR...because I don't do UI 😄

**Comment by Mynyx** [comment]
The options seem too specific and should better located in the configuration files. Why should these values be changed repeatedly?

The standard maximum depth value is too low. In general, I would not set a limit there as default. As long as really new pages are found, a threshold does not make sense. If a circular is given, e.g. via irregular query parameters, a maximum total number of requests would be more helpful. 

The relation factor 4 between concurrency and maximum number of requests I do not understand?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we do want to make the maximum depth configurable in the back end and the other parameters in the container configuration. This way the user cannot flood the server with too many requests and still adjust the depth according to their needs.

**Comment by Shania567** [comment]
It would be nice for big pages to select a part of the site for the broken link check (Websitetree). On my site the job needs very long until I get an result. It would be great if I could do ist step by step und leave out the sites with comments. There are many broken links from website visitors. There websites doesn't exist any more an I don't want to delete them.
For test purposes it would be nice to do the same for the seach index.
