### ISSUE TITLE
Sorting flags for descending direction not recognized in parent view

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#381]
**Affected version(s)**

 - 4.4
 - 4.7

**Description**  

When I set the sorting flag (f.e. 6) I expect that the records are sorted in descending order. The flag isn't recognized for sorting items itself

**How to reproduce**  

1. Create a data container in parent mode `4`
2. Set sorting flag to `6`
3. Set sorting fields to a time stamp field

**Comment by leofeyer** [comment]
The parent view always sorts records by the `sorting` column, doesn't it?

**Comment by dmolineus** [comment]
No, it doesn't:

https://github.com/contao/contao/blob/e7486e952d0b54843d3a899d872cffa6413de0ee/core-bundle/src/Resources/contao/drivers/DC_Table.php#L4309-L4313

**Comment by leofeyer** [comment]
Have you tried the following?

```php
$GLOBALS['TL_DCA'][$table]['list']['sorting']['mode'] = 4;
$GLOBALS['TL_DCA'][$table]['list']['sorting']['fields'] = array('tstamp DESC');
$GLOBALS['TL_DCA'][$table]['fields']['tstamp']['flag'] = 6;
```

This is how we accomplish the sorting of events in the [tl_calendar_events](https://github.com/contao/contao/blob/master/calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php#L60) DCA.
