### ISSUE TITLE
SQL Error while deleting an news entry in Contao  4.9.23

### ISSUE THREAD

**Issue by dguelden** [contao/contao#3817]
**Affected version(s)**

Contao 4.9.23 - Symfony bundle for the Contao Managed Edition

**Description**

Got an SQL Error if I will delete an news created an empty object. See attachment.

Installed modules:

Contao defaults (News, Kalender, FAQ, Kommentare, Newsletter, Auflistungen)

Extensions (Bot Detection Bundle, Besucher Statistiken, Merger², Google Maps, fipps/contao-rssimport-bundle, kmielke/calendar-extended-bundle, RockSolid Slider, MetaModels Core, Button um zum Anfang der Seite zu springen, Contao Cookiebar, rsm/rsm-googlerecaptcha-modul, wr/onepage-bundle)

All packages are up-to-date.

Server Message:

An exception occurred while executing 'SELECT tl_news.id, tl_files.uuid AS uuid, tl_files.path FROM tl_files LEFT JOIN tl_news ON tl_files.uuid = tl_news.singleSRC WHERE tl_news.pid = '18' GROUP BY tl_files.id': SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'MY-DATABASE.tl_news.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

![Bug_Contao_4 9 23_Delete-News](https://user-images.githubusercontent.com/30050128/145889044-f8e2e918-9b63-4ed4-8812-c7197893b748.PNG)

**Comment by dguelden** [comment]
Update to version Contao 4.9.24.
The error is reproducible and is due to the expansion: https://github.com/fipps/contao-rssimport-bundle

**Comment by bytehead** [comment]
Then you have to report the issue over [there](https://github.com/fipps/contao-rssimport-bundle).

**Comment by dguelden** [comment]
Error is send to the contributors of fipps/contao-rssimport-bundle.
