### ISSUE TITLE
Reihenfolge der Blöcke Metadaten bei Dateien bei mehreren Sprachen

### ISSUE THREAD

**Issue by zonky2** [contao/contao#3818]
siehe https://contao.slack.com/archives/CK4J0KNDB/p1639469896369900

Aktuell ist die Reihenfolge lt. @fritzmg undefiniert - die Reihenfolge war mal mit der Sprache des BE-Users gekoppelt (diese als erste) aber das ist mit https://github.com/contao/core/issues/6254 verloren gegangen.

Die Reihenfolge anhand ggf. vorhandener Rootpages ist m.E. nicht unbedingt sinnvoll, da die Seiten nicht unbedingt was miteinander zu tun haben müssen (unterschiedliche Domains).

Eine Rückführung auf die Sprache des Benutzers wäre aus meiner Sicht aktuell die beste (temporäre) Lösung, da das alte, gewohnte Verhalten wieder hergestellt wird.

Für die Zukunft wäre wohl eine Konfigurationsmöglichkeit anzustreben.

**Comment by fritzmg** [comment]
> Eine Rückführung auf die Sprache des Benutzers wäre aus meiner Sicht aktuell die beste (temporäre) Lösung

What about the other languages though? Which order should they have?

**Comment by zonky2** [comment]
> What about the other languages though? Which order should they have?

wie war es vorher? die Restlichen würde ich alphabetisch anordnen

**Comment by leofeyer** [comment]
> siehe https://contao.slack.com/archives/CK4J0KNDB/p1639469896369900

Please don't post links to Slack here. Not everyone has joined our Slack workspace and even those who have haven't necessarily subscribed to the support channel. Provide a short issue description instead.

**Comment by zonky2** [comment]
> Frage zu den Metadaten bei Dateien: wer oder was bestimmt in welcher Reihenfolge "Deutsch" und "Englisch" kommt?
> Contao 4.9.22
> Redakteurin meint, "früher" war Deutsch immer als Erstes und dann Englisch - das ist nun umgedreht und führt zu "Fehleingaben" - zudem "komisch": wenn man bei Deutsch was einträgt (z.B. Titel), rutscht das an die erste Position... wenn man das wieder löscht, bleibt Deutsch bei dem einen Bild an erster Position... hmmm??

**Comment by leofeyer** [comment]
As discussed in the Contao call, we should render the fields alphabetically by label ("English", "German", "Polish") but store them by language code ("de", "en", "pl"). The language that matches the back end user's language shall be on top.
