### ISSUE TITLE
Display the headline of YouTube-ContentElements in the BE

### ISSUE THREAD

**Issue by asaage** [contao/contao#382]
I think every other CE does it except this one.
If you are only provided the url and you need to sort a handfull of clips in an article this can be a little cumbersome.

https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/elements/ContentYouTube.php#L39-L42

```php
if (TL_MODE == 'BE')
{
  $return = '<p><a href="https://youtu.be/' . $this->youtube . '" target="_blank" rel="noreferrer noopener">youtu.be/' . $this->youtube . '</a></p>';
  if ($this->headline != '')
  {
    $return = '<'. $this->hl .'>'. $this->headline .'</'. $this->hl .'>'. $return;
  }
  return $return;
}
```

**Comment by leofeyer** [comment]
Fixed in 4d8077eeebccb884b710eec97ff8e5deaa9b9334.
