### ISSUE TITLE
Show start/stop publishing status for content elements

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#3826]
### Description

Since we are going down this road: #3784, I would love to see `start`/`stop` values here as well😁

![image](https://user-images.githubusercontent.com/10257912/146260820-92d9a9f9-1c8d-40dc-9fd7-d9330c3c1521.png)

Should I make a PR?

**Comment by bytehead** [comment]
PRs are always welcome! ❤️

**Comment by leofeyer** [comment]
Please also see contao/core-bundle#940 before starting to work on this.

**Comment by ameotoko** [comment]
Thanks for that link, I was not aware how much thought has been put into this already. However, my proposal would solve (or at least ease) the problem in a different manner. It is easily implemented as it is just a few extra lines in `child_record_callback`. 

The idea is to eliminate extra clicks just to see if there are any `start`/`stop` values assigned to an element. This is actually mentioned in the original [feature request](https://community.contao.org/de/showthread.php?65548-Anzeigen-von-und-Anzeigen-bis-Element-unsichtbar-sichtbar-setzen-m%C3%B6glich):

> Sonst muss man in jedes Element rein gehen -und dort nachsehen - was bei 60-70 Elementen recht zeitaufwändig ist.

Granted, to really see if the element is currently visible or not would be even better, but this can quickly lead to a rabbit hole, as [contao/core-bundle#940](https://github.com/contao/core-bundle/pull/940) shows. I think, the current problem is that timed elements are not distinguished in BE **at all**. Once you can see at least the values of `start`/`stop` in the list, it's easier for your brain to infer the resulting publishing status.

**Comment by ameotoko** [comment]
May be the color can highlight the currently applied value?

![image](https://user-images.githubusercontent.com/10257912/146339559-a1f7cf23-820a-4277-958e-a40cb1d9998e.png)

**Comment by ameotoko** [comment]
However, I am concerned, that with [#3875](https://github.com/contao/contao/pull/3785) implemented, there will be too much going on in that space.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add the until/from information in grey as a first step.
