### ISSUE TITLE
Eventlist skipping events that span multiple days

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#383]
**Affected version(s)**
Seems like all since 4.4 up to latest 4.7

**Description**  
I have a site which has events usually starting at 22:00 and ending early in the morning the next day.
So the event spans at least two days. I've found out that if I have an event list with such an event the module will skip to the next event as soon as the starting time of that event has come.

I have list that just shows the upcoming event, it starts at 22:00. At 21:59 everything is fine, the right event is shown. As soon as it's 22:00 the list will skip this event and jump to the next one.

The related line is this one:

https://github.com/contao/calendar-bundle/blob/ada5fbf12ce1729e71116e1a29c44db3bb83eac5/src/Resources/contao/modules/ModuleEventlist.php#L172-L177

I  found out that this was an old bug (see contao/core#8782) and was once already fixed but it seems that with the release of 3.5.30 it came back in since the if-condition was cut down to a bare minimum which is indeed a bit too short.

Before 3.5.30 this was the way doing it and it would indeed work absolutely fine today:

https://github.com/contao/core/blob/9ce6c403aab4be1b3aa86924ae611e4c5a615af8/system/modules/calendar/modules/ModuleEventlist.php#L166-L178

**How to reproduce**

1. Add an event which spans two days e.g. beginning at 22:00 ending at 03:00 the next day
2. Add another event that starts the next day after 03:00
3. Create an event listing module, limit it to the next upcoming event
4. Visit the site at e.g 00:00. Although the event from 22:00 the day before is still going on, the next event will be shown

**Comment by m-vo** [comment]
I guess this depends on what 'upcoming' means. Perhaps we need to distinguish if currently occurring ones should be included or not?

**Comment by fritzmg** [comment]
This is a setting in the event list module. Did you enable it?

**Comment by bennyborn** [comment]
> I guess this depends on what 'upcoming' means. Perhaps we need to distinguish if currently occurring ones should be included or not?

Since there is an option to hide already running events I guess it was decided years ago that "upcoming" should also include events from the past still running.

> This is a setting in the event list module. Did you enable it?

Are you talking about the "Shortened view" option? Of course enabling it fixes it in this case but it's intended purpose is something else.

**Comment by fritzmg** [comment]
No, I mean the setting __Hide running events__, which is available in Contao 4.7.

**Comment by bennyborn** [comment]
> No, I mean the setting **Hide running events**, which is available in Contao 4.7.

I know about this option but that would be exactly the thing I would NOT want to do :)

**Comment by fritzmg** [comment]
Hence the question whether you enabled it or not ;). So, if you are using Contao 4.7 and did not enable this option, yet running events are not shown in upcoming events, then there is a bug.

**Comment by bennyborn** [comment]
Not using 4.7 but if so I'd not have enabled. It is a bug ;)

**Comment by fritzmg** [comment]
No, iirc the behavior was changed in Contao 4. But since some users do want to show running events and some do not, the aforementioned option was introduced in Contao 4.5.

In your original post you wrote this problem also occurs in Contao 4.7 - but now you are saying you are not using Contao 4.7.

Please update your original post and also post reproduction steps for the Contao Online Demo, if you can reproduce the problem there.

**Comment by bennyborn** [comment]
> In your original post you wrote this problem also occurs in Contao 4.7 - but now you are saying you are not using Contao 4.7.

It occurs since 3.5.30 up to 4.7 because the line of code in question remained the same since then.

> Please update your original post and also post reproduction steps for the Contao Online Demo, if you can reproduce the problem there.

Updated it, also was able to reproduce it in the online demo.

**Comment by leofeyer** [comment]
> Updated it, also was able to reproduce it in the online demo.

How exactly did you do it?

**Comment by bennyborn** [comment]
@leofeyer What do you mean? Instructions can be found in the first post.

**Comment by leofeyer** [comment]
You are right, my bad.

**Comment by leofeyer** [comment]
> but it seems that with the release of 3.5.30 it came back in since the if-condition was cut down to a bare minimum which is indeed a bit too short.

It seems there was a good reason to revert the changes: https://github.com/contao/core/issues/8792

> Are you talking about the "Shortened view" option? Of course enabling it fixes it in this case but it's intended purpose is something else.

I am not sure if this is not the intended purpose. But maybe we should consider the "hide running events" option in this case, too? @bennyborn Did you enable the "hide running events" option?

**Comment by bennyborn** [comment]
> I am not sure if this is not the intended purpose.

At least, according to it's description in the backend, it was just meant to display an event only once, even if it spans multiple days. In my opinion this should have nothing to do with the decision if the event should be shown at all.

> But maybe we should consider the "hide running events" option in this case, too? @bennyborn Did you enable the "hide running events" option?

Nope, not enabled since it would be the exact opposite of what I'd tried to achieve :)

**Comment by joehi** [comment]
I see an event always disappearing from the list of all upcoming events, no matter whether the "hide running events" option is set or not. As soon as the start time is in the past the event no longer shows up in the list of upcoming events. It moves to the list of past events, even though it is not yet marked as class "bygone". It gets marked as "bygone" when the calender day is over.
Start time and End time of the event are on the same day.

**Comment by leofeyer** [comment]
As discussed in Mumble on June 6th, we think that this is a bug. The module most likely does not consider the "hide running events" option.

**Comment by leofeyer** [comment]
@bennyborn I'm not able to reproduce the issue in Contao 4.4.41 and Contao 4.7.7. Can you check again and maybe provide detailed instructions how to reproduce the issue without having to do it between 0:00am and 3:00am. 🤣

**Comment by bennyborn** [comment]
@leofeyer There is actually no way to reproduce it without having a day change. If you're on a local webserver like "LAMP" you could adjust your system clock to see it happen during daytime 😉

**Comment by leofeyer** [comment]
What about an event that starts on day one at 10pm and ends on day two at 2pm?

**Comment by bennyborn** [comment]
> What about an event that starts on day one at 10pm and ends on day two at 2pm?

Haven't tried that but I guess it would behave the same.
As stated initially it only occurs if the event starts on one day and end on the other.

**Comment by leofeyer** [comment]
Please let me know how to reproduce it as soon as you have tried.

**Comment by leofeyer** [comment]
@bennyborn /ping

**Comment by bennyborn** [comment]
Sorry for the delay. Will create a test case tomorrow and hopefully come back at it on friday.

**Comment by bennyborn** [comment]
Well, thats strange.

As you suggested I created an event starting 10pm yesterday, ending 2pm today and it is indeed still visible even without checking the checkbox "Verkürzte Darstellung".

Any explanation on this?

**Comment by leofeyer** [comment]
This is the expected behavior. 😄

Maybe there is something wrong with your installation? Maybe a third-party extension that alters the default behavior?

**Comment by bennyborn** [comment]
*sigh*

Clean Installation (tbh a bit older, I guess around 4.4.30) no extensions at all.
Since I'm already in the process of building a similar site based on the latest 4.4.x I suggest we could close this Issue for now and I'll get back to it if the problem persists.
