### ISSUE TITLE
jumpTo page not works in delete or signout .

### ISSUE THREAD

**Issue by hoss-ps** [contao/contao#384]
**Affected version(s)**
  4.5
**Description**  
in ModuleCloseAccount class line 122, log out comes before jumpTo and  it couse 403 error.
is it correct or should be before reload ?
beside it, we have same code for sign out module.
``` php
$this->User->logout();

// Check whether there is a jumpTo page
if (($objJumpTo = $this->objModel->getRelated('jumpTo')) instanceof PageModel)
{
$this->jumpToOrReload($objJumpTo->row());
}

$this->reload();
``` 
**How to reproduce**  

``` php

// Check whether there is a jumpTo page
if (($objJumpTo = $this->objModel->getRelated('jumpTo')) instanceof PageModel)
{
$this->jumpToOrReload($objJumpTo->row());
}
$this->User->logout();
$this->reload();
```

**Comment by contaoacademy** [comment]
Contao 4.5 is not supported any more.
Please update to Contao 4.6 or better 4.7.

I think this problem was fixed here: See https://github.com/contao/contao/pull/162
