### ISSUE TITLE
Change in 4.9.24 leads to empty Template variable

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#3840]
### Affected version(s)

4.9.24

### Description

Hello,

since the latest 4.9 update we get a null error for the Template variable in the `getPageLayout` hook.

The concrete line is:

https://github.com/heimrichhannot/contao-head-bundle/blob/master/src/EventListener/HookListener.php#L52

It throws an error now because Template is null.

Is this with intention? How can we add functions to fe_page now if it's a PHP-supporting HTML5-Template?

Thanks in advance!

Bye Defcon0

**Comment by fritzmg** [comment]
> How can we add functions to fe_page now if it's a PHP-supporting HTML5-Template?

Template functions should be added via the `parseTemplate` hook. See also https://docs.contao.org/dev/reference/hooks/parseTemplate/#examples 

Using the `getPageLayout` Hook for this never worked, because the template was always created _after_ that hook was executed.

**Comment by Defcon0** [comment]
Ah sorry, I meant `generatePage` hook. Is your argumentation still valid in this case?

**Comment by fritzmg** [comment]
`generatePage` is executed after the template is created.

But you are right, this is likely BC break now, as before 4.9.24 `PageRegular::$Template` was a publicly accessible, dynamic property and now it is a protected property. This is caused by https://github.com/contao/contao/pull/3822

**Comment by fritzmg** [comment]
In any case, you should still use the `parseTemplate` hook for this. `PageRegular::$Template` was never intended to be publicly accessible.

**Comment by Defcon0** [comment]
I just changed it to be applied in parseTemplate hook which works :) Thanks for pointing me into the correct direction!
