### ISSUE TITLE
Backend, Speichern Buttons leiten auf falschen Bereich um

### ISSUE THREAD

**Issue by marcfunkDE** [contao/contao#3844]
### Affected version(s)

4.12.4

### Description

Hallo Zusammen!

Wenn ich im Backend in der Seitenstruktur 1x etwas verändere und danach die Speicherbuttons in andere Bereiche nutze wie z. B. bei Artikel (Speichern & Schließen oder Speichern & zurück) lande ich nicht in der Übersicht oder beim letzten Element sondern irgendwo anders im System.

Ich habe es mit mehreren Browsern (Opera, Firefox und Chrome) probiert, Verlauf, Cookies etc. gelöscht und auch verschiedene Endgeräte verwendet.

Ich kann es wie folgt nachstellen:

1. Login Backend
2. Seitenstruktur > eine Seite bearbeiten
3. Änderungen vornehmen > Speichern
4. Artikel öffnen
5. Artikel duplizieren
6. In die Seite xyz einfügen
7. Speichern & Zurück > Ich lande plötzlich in der Seitenstruktur

Das gleiche passiert auch mit Speichern & Schließen. Manchmal lande ich auch die Dateiverwaltung, obwohl ich da z. B. nach dem Login drin war und danach bestimmt 20 x andere Bereiche angeklickt habe.

Oben in der Adressleiste taucht auch immer ein "Referer" auf: domain.org/contao?do=article&ref=hPnISGNo
Wenn ich den manuell entferne und danach weiter mache, passiert das Problem trotzdem und der &ref taucht wieder auf.

**Comment by ausi** [comment]
Tritt derselbe Fehler auch mit der version 4.12.5 auf?

**Comment by marcfunkDE** [comment]
Guten Abend!

Habe gerade aktualisiert - bisher ist er immer in die richtige Maske zurück gesprungen. Scheint also erledigt zu sein.
Ich beobachte es weiter und gebe auf jeden Fall nochmals Rückmeldung.

**Comment by bytehead** [comment]
Sollte eigentlich mit https://github.com/contao/contao/pull/3787 behoben worden sein.
