### ISSUE TITLE
Zurück-Link landet irgendwo, aber nicht da wo man es erwartet

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#3847]
### Affected version(s)

4.9.23

### Description

Seit der 4.9.22 oder 4.9.23 funktioniert der Zurück-Link nicht mehr richtig. Gerade habe ich in einer Nachricht den Zurück-Link angeklickt und landete in den Inhaltselementen eines Artikels, den ich am gleichen Tag mehrere Bearbeitungsvorgänge vorher offen hatte. Mein Kollege berichtet mir auch gerade, das er nach "Speichern und Schließen" im Dashboard landet statt z.B. in der Inhaltselemente-Übersicht einer Nachricht oder eines Artikels. 
Vor ein paar Tagen bin ich ständig in der Seitenstruktur gelandet, obwohl meine Arbeit dort auch schon länger her war. 

Das Problem tritt regelmäßig auf, aber auch nicht immer.

**Comment by aschempp** [comment]
Dieser Fehler ist in der neusten Contao-Version behoben.

**Comment by fritzmg** [comment]
@Samson1964 always update to the most recent Contao version first in order to check whether the issue still exists there.
