### ISSUE TITLE
Brackets in the HTML comment are escaped

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#3849]
### Affected version(s)

4.9.24

### Description

Verwendet man in einem HTML-Element innerhalb von einem HTML-Kommentar eine Klammer, dann wird diese escapt.
z.B. Google Tag Manager Einbindung mit dem üblichen Kommentar
Aus `<!-- Google Tag Manager (noscript) -->` wird `<!-- End Google Tag Manager &#40;noscript&#41; -->` . Das ist zwar nicht wirklich schlimm, aber eben auch nicht schön. 
Mir scheint es auch nicht notwendig, dass Contao aus Sicherheitsgründen auch im Kommentarbereich escapt. 
Siehe auch https://contao.slack.com/archives/CK4J0KNDB/p1640016216484900

**Comment by ausi** [comment]
Kommentare in HTML sind leider recht komplex da es viele Parsing-Regeln zu beachten gilt. Dass die runden Klammern enkodiert werden liegt an der `Intput::encodeSpecialChars()`-Methode. Auf den ersten Blick würde ich keine Probleme damit sehen die runden Klammern dort nicht zu enkodieren, allerdings ist es sehr schwer die möglichen Auswirkungen abzusehen.

Für die Sicherheit würde ich es so belassen wie es jetzt ist.

**Comment by bytehead** [comment]
Sonst einfach ein HTML-Element mit custom Template für den GTM-Tag verwenden, da wird nichts escaped und das Template lässt sich z.B. auch via Git versionieren.

**Comment by mlwebworker** [comment]
Ok, dann bleibt es dabei. Mir ging es auch nicht um den konkreten Fall, sondern allgemein um die möglicherweise unschöne Ausgabe von HTML-Kommentaren.
Ich schließe das Ticket.
