### ISSUE TITLE
cannot use route in button_callback

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#385]
**Affected version(s)**
4.7.0, 4.7.1

**Description**  
In 0d6dcdbf6c1c221147e208234c5e8bf14818d13f a new feature was introduced to allow routes to be defined for table record operations. This was done with a new `route` property in the operation definition.

However, this cannot be used in the [`button_callback`](https://github.com/contao/contao/blob/9874b3009644746fd09a7acfeaa0c91b7f35a9da/core-bundle/src/Resources/contao/classes/DataContainer.php#L796-L807), since neither the route information nor the full 'operation' array is passed to the callback. Since you have to fully implement the button yourself when using the callback, it is impossible to do so when the operation uses a `route` instead of a `href`.

**Comment by leofeyer** [comment]
@aschempp I would solve this by checking if `$v['route']` is set and resolving the route to `$v['href']`. Do you have a better idea?

**Comment by aschempp** [comment]
How about just accessing the DCA in your callback? 🙈

**Comment by fritzmg** [comment]
Hm, yeah 😁 since the `button_callback` is done for a specific button, I can indeed just look at the DCA …

**Comment by leofeyer** [comment]
Ha, that is a surprisingly simple solution indeed. Didn't think of it, either. 😄
