### ISSUE TITLE
Using the dump() Twig function in prod produces an error

### ISSUE THREAD

**Issue by m-vo** [contao/contao#3853]
I can confirm the problem. Using

```twig
{% extends '@Contao/fe_page' %}

{% block main %}
  {{ dump('foo') }}
  <h1>Hello from Twig!</h1>
  {{ parent() }}
{% endblock %}
```

will yield

```
[2021-12-21T10:54:23.936147+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Did you forget to run "composer require symfony/debug-bundle"? Unknown function "dump" in "@Contao/fe_page.html.twig"." at vendor\symfony\twig-bridge\UndefinedCallableHandler.php line 96 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Did you forget to run \"composer require symfony/debug-bundle\"? Unknown function \"dump\" in \"@Contao/fe_page.html.twig\". at vendor\\symfony\\twig-bridge\\UndefinedCallableHandler.php:96)"} []
```

This error is in fact thrown by `symfony/twig-bridge`.

_Originally posted by @fritzmg in https://github.com/contao/contao/issues/3566#issuecomment-998679794_

**Comment by m-vo** [comment]
The reason behind this issue is that we're not loading the `DebugBundle` in `prod`:

https://github.com/contao/contao/blob/a5c401df53881cd09edd0e5dfc9813dbb659c251/manager-bundle/src/ContaoManager/Plugin.php#L89

Because we probably want to keep it that way, we could in theory register a no-op `dump` function in the `manager-bundle` (`prod` only). Wdyt?

For reference: https://github.com/symfony/symfony/issues/45141

**Comment by leofeyer** [comment]
How does Symfony handle this case?

**Comment by m-vo** [comment]
> How does Symfony handle this case?

Not. You would get a `SyntaxError` as well in `prod`.

**Comment by leofeyer** [comment]
So why do we have to handle this differently?

**Comment by fritzmg** [comment]
In Contao we allow to use `dump()` in PHP templates (or `$this->dumpTemplateVars()`). The expectation would imho be that this also works in Twig templates - or at least does not result in an error.

**Comment by leofeyer** [comment]
I disagree. If you want to dump variables or do other debugging, run the application in dev mode. It never makes sense to have a `dump()` call in a production template.

**Comment by m-vo** [comment]
But would you want your application to fail then or should just nothing be output?

**Comment by Toflar** [comment]
We don't use `dump()`. We use the `VarDumper` directly. https://github.com/contao/contao/blob/5.x/core-bundle/src/Resources/contao/library/Contao/Template.php#L272

**Comment by leofeyer** [comment]
> But would you want your application to fail then or should just nothing be output?

Fail. Because that is how the underlying framework handles it.

**Comment by fritzmg** [comment]
> We don't use `dump()`. We use the `VarDumper` directly.

I know. And `dump()` is basically also just a shim for `VarDumper::dump` (though it allows you to dump multiple variables as funciton arguments). My point is that in Contao it is currently possible to use either `dump()`, `VarDumper::dump` or `$this->dumpTemplateVars` in PHP without an error occurring. My expectation would be that `{{ dump() }}` in Twig would behave no different (but it does currently).

**Comment by m-vo** [comment]
So, should we vote what to do in Twig?

* don't change anything, but explain it to users in the docs [:heart:]
* register a no-op [:tada:]
* output in `prod` as well, i.e., load the debug bundle in prod [:+1:]

**Comment by fritzmg** [comment]
I voted 🎉 for now, but I am curious as to what the result of the discussion on Symfony will be.

> * output in `prod` as well, i.e., load the debug bundle in prod [👍]

That would also register two additional compiler passes for prod, not sure if that is desirable?

**Comment by m-vo** [comment]
> That would also register two additional compiler passes for prod, not sure if that is desirable?

Yes, and it might leak information about the app if you're using the unconstrained version without any parameters, which is probably worse.

**Comment by fkaminski** [comment]
>  My expectation would be that {{ dump() }} in Twig would behave no different (but it does currently).

From the user perspective, I think it makes sense if it is implemented uniformly - Either way ...

**Comment by m-vo** [comment]
I thought about this again. I think outputting the untreated context, and potentially the whole context, in `prod` is a really bad idea. And the default behavior of the `dump` function/tag would not even do it even if the `DebugBundle` was registered - as long as debug isn't enabled in the kernel, an early return prevents evaluation. 

So we should either enable the `DebugBundle` in `prod` (to get rid of the exception) or do nothing and educate our users.

**Comment by asaage** [comment]
Just voted for the last option because i use ```$this->dumpTemplateVars``` for a quick insight a lot in production.
I find the debug-mode is just painfully slow and then i'm allway unsure what it does to the site for my visitors.
Didn't dig into twig-templating though...

**Comment by m-vo** [comment]
> because i use $this->dumpTemplateVars for a quick insight a lot in production.

You won't be able to do this with Twig templates anyway as they are compiled and changes in prod would only be effective once the cache was rebuilt. 

>  I think outputting the untreated context, and potentially the whole context, in prod is a really bad idea.

To iterate on that: Besides other things like globally defined tokens, the context contains the global `app` object, that includes information about the token storage, container, request… This is potentially sensitive information, that should never be output on a productive site.

**Comment by fritzmg** [comment]
> To iterate on that: Besides other things like globally defined tokens, the context contains the global app object, that includes information about the token storage, container, request… This is potentially sensitive information, that should never be output on a productive site.

But if we want to prevent that, we would need to do that for _any_ `dump`, not just the ones coming from Twig templates?

**Comment by m-vo** [comment]
> But if we want to prevent that, we would need to do that for any dump, not just the ones coming from Twig templates?

Tbh, I'm only concerned about Twig templates right now. :upside_down_face:. In PHP Templates and anywhere in your code, you can do all sorts of stuff which we cannot control.

**Comment by m-vo** [comment]
Based on the vote and the reaction in the Sf issue I think this is a "won't fix" and we should just document it properly.
