### ISSUE TITLE
Folder::isEmpty() returns false when the folder contains the ".public" file only. 

### ISSUE THREAD

**Issue by markocupic** [contao/contao#3854]
### Affected version(s)

4.x.x

### Description

When a folder is "almost empty" and there is only the .public file left in it, `Folder::isEmpty()` returns a boolean `false`. Shouldn't it return a boolean `true`?

**Comment by fritzmg** [comment]
I would say no. While Contao's `Folder` class does communicate with the DBAFS, it is otherwise independently just an abstraction to deal with any folder within the project.

**Comment by m-vo** [comment]
> it is otherwise independently just an abstraction to deal with any folder within the project

I agree with this. :+1: 

We could however take this into account for our new filesystem abstraction.

**Comment by fritzmg** [comment]
And otherwise you can always use [Symfony Finder](https://symfony.com/doc/current/components/finder.html):

```php
use Symfony\Component\Finder\Finder;

count($finder->in($directory)->notName('.public'));
```
(or something like that, haven't tested)

**Comment by markocupic** [comment]
@fritzmg @m-vo thank you!
