### ISSUE TITLE
executeResize - getCacheName() falscher Cache-Pfad

### ISSUE THREAD

**Issue by LBeckX** [contao/contao#386]
**Affected version(s)**

Contao | 4.4.33
--------|-------

**Description**  

* Forum: https://community.contao.org/de/showthread.php?73743-Bilder-assets-Pfad-aus-Hook&p=493955

Es gibt die Möglichkeit auf über die Hook `executeResize` auf den Bilder-Cache-Name zuzugreifen um  in die Resize-Funktion einzugreifen.
Dieser ist allerdings nicht der richtige Cache-Name (hat nach Ausführung kein reales Bild als Ziel), sollte die Funktion ein `false` zurückgeben. 

**How to reproduce**  
* Bild-Maße ändern
* Auf die Hook `executeResize` zugreifen
* Sich über `$image->getCacheName()` den Cache-Namen ausgeben lassen
* Der Funktion ein `false` als Rückgabewert geben um nicht das Verkleinern zu unterbrechen
* Nach der Ausführung prüfen, ob an der Stelle, des Bildpfades ein Bild existiert

**Comment by ausi** [comment]
Die Image-Hooks sind veraltet und sollten nicht mehr verwendet werden. Stattdessen kannst du in Contao 4.4 z. B. den Service `contao.image.picture_factory` decoraten.

Wie das geht ist in der Symfony Dokumentation beschrieben: <https://symfony.com/doc/current/service_container/service_decoration.html>

Unabhängig davon bleibt natürlich die Frage ob es ein Bug ist, dass `$image->getCacheName()` nicht den richtigen Pfad zurückgibt. Um das zu beheben müssten wir die gesamte Logik von [contao/image src/Resizer.php:158-183](https://github.com/contao/image/blob/4f860aef6966f238c6f342ce33da60437b20bf6d/src/Resizer.php#L158-L183) in die Legacy Klasse übernehmen.

Grundsätzlich konnte man sich auch in Contao 3.5 nicht darauf verlassen, dass `$image->getCacheName()` den korrekten Pfad liefert, da sich dieser durch einen späteren Hook noch ändern könnte oder das Bild gar nicht verkleinert wird falls die Größe des Originals bereits passt und somit der Original-Pfad verwenden wird.

**Comment by LBeckX** [comment]
Vielen Dank für die schnelle Antwort. Werde ich mir anschauen 👍
