### ISSUE TITLE
Feature: Navigationsmenü mit Bildern

### ISSUE THREAD

**Issue by Physiklehrer** [contao/contao#3870]
### Description

Liebes Core-Team,

Contao hat ja zwei tolle Features: die Bildgrößen-Verwaltung und die vielfältigen Möglichkeiten zur Erstellung von Navigationsmenüs aus der Seitenstruktur. Viele Webseiten werten ihre Navigation aber mit Bildern auf, weshalb es toll wäre, beides besser kombinieren zu können.

Hierzu müsste es lediglich die Möglichkeit geben, bei der Seitenstruktur für jede Seite ein Bild festzulegen. Dann könnte es zwei zusätzliche Elemente geben:
1. Modul "Navigationsmenü mit Bildern", das ein Menü mit den bei den jeweiligen Seiten hinterlegten Bildern + Text generiert
2. Inhaltselement "Bild der Seite" mit der das in der Seitenstruktur hinterlegte Bild in einem Artikel eingefügt werden kann.

Alternativ könnten diese Funktionalitäten natürlich auch in die Standardmodule "Navigationsmenü" und "Bild" integriert werden -> Checkbox "Bild der Seite verwenden" o.ä.

Dieses Verhalten wäre für Contao auch nicht wirklich neu, denn bei den News und Events kann ja auch jeweils ein Bild pro Eintrag festgelegt werden, das dann in der Nachrichtenleiste erscheint. Für die Navigation wäre eine solche Funktionalität auch sehr praktisch und eine saubere Lösung statt Workarounds mit CSS oder Bildergalerien, die natürlich auch gut funktionieren, aber viele Klicks mehr sind und keine zentrale Pflege der Bilder erlauben.

Vielen Dank für alles und einen guten Start ins neue Jahr!

**Comment by contaoacademy** [comment]
Sieh dir doch dazu einmal die Erweiterung "terminal42/contao-pageimage" an. Ich denke mit dieser Erweiterung einer individuellen Anpassung im Template der Navigation könnte das realisiert werden. Ich bin mir nicht sicher, ob die Funktion wirklich in den Core gehört.

**Comment by Physiklehrer** [comment]
Vielen Dank, im Store hatte ich nicht recherchiert- tatsächlich deckt die Erweiterung Punkt 2 komplett ab, sogar mit Slider, super :-).

Es bleibt Punkt 1, das Navigationsmenü mit Bildern. Das gibt es ja auch beim Menü von Contao.org und wird dort mit individuellen CSS-Klassen und Background-Links in der CSS gelöst - nicht sehr "schön", oder denke ich zu akademisch? Wenn man das Menü mit Pixelgrafiken bauen will und responsive Bilder möchte, geht das sogar überhaupt nicht per CSS und man müsste z.B. die Bildergalerie zweckentfremden. Alle Varianten erfordern aber viel händische Nacharbeiten, so dass das schnelle Austauschen eines Logos für Redakteure nicht so einfach ist.

Daher der Vorschlag etwas konkreter und in Abgrenzung zur pageimage-Erweiterung nur für die Navigation:
- Seitenstruktur: neuer Punkt "Seitenlogo" -> 1 Bild aussuchen
- Alle Navigationsmodule: Häkchen "Seitenlogo hinzufügen" mit Auswahlmöglichkeit für gewünschte Bildgröße
- Alle Navigationsmodule: Template ohne Logo, mit Logo als Bild und mit Logo als CSS (wie in der pageimage-Erweiterung)

Das könnte alles natürlich auch in die pageimage-Erweiterung dazu (z.B. durch zusätzliche Module und/oder Templates) oder in eine eigene Erweiterung. Da "Navigation mit Bildern" inzwischen häufig zu sehen ist (siehe contao.org) und mit meinem Vorschlag sowohl JPG- als auch SVG elegant eingebunden werden könnten fände ich diese Funktion aber auch im Core gut aufgehoben.

**Comment by fritzmg** [comment]
> Es bleibt Punkt 1, das Navigationsmenü mit Bildern.

But you can do that with the aforementioned extension too? Within your navigation template you can access any variables of the page you want. May be implement a `parseTemplate` hook to automatically provide the necessary HTML code, without having too much business logic in the template itself.

**Comment by Physiklehrer** [comment]
Many thanks for your suggestion! Feel free to close this issue, if you think that an easy way to build navigation menus with icons/images is not worth a core feature.
