### ISSUE TITLE
Using ALT + C goes back too many pages

### ISSUE THREAD

**Issue by sietsevandreven** [contao/contao#3874]
### Affected version(s)

4.12.4

### Description

Normally when using ALT + C to save and close, you're directed to the previous page. But most of the time I'm directed 2 pages back, sometimes even 3.

**Comment by aschempp** [comment]
does this also happen if you press the save & close button?

**Comment by sietsevandreven** [comment]
Unfortunately, yes

**Comment by leofeyer** [comment]
Please make sure to test with the latest Contao version 4.12.5. I'm pretty sure that we have already fixed this issue.
