### ISSUE TITLE
Integration von PeerTube für Videos

### ISSUE THREAD

**Issue by kroerig** [contao/contao#3880]
### Description

Hallo,

es wäre schön, wenn neben Youtube auch Videos von Peertube-Instanzen komfortabel eingebunden werden könnten.
Die Doku zur API findet sich hier: https://docs.joinpeertube.org/api-embed-player
Es müsste aber der Instanzname jeweils abgefragt werden.

Ich bin leider kein Entwickler.

**Comment by Toflar** [comment]
Das wäre dann wohl eher ein Fall für eine Erweiterung und nicht für den Core.

**Comment by kroerig** [comment]
Youtube und Vimeo sind auch im Core enthalten.

**Comment by bytehead** [comment]
Ist wohl auch dem Marktanteil geschuldet.
