### ISSUE TITLE
Twig dump() not shown in Symfony Profiler

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3881]
### Affected version(s)

4.12, 4.x

### Description

I noticed that when using `{{ dump(…) }}` in Twig templates (at least the ones inheriting from a legacy template, like a `fe_page.html.twig` template) the output is directly printed to the page - and not collected in the Symfony Profiler under _Debug_. Shouldn't this be the case @m-vo ? 🤔

**Comment by aschempp** [comment]
are you by chance using this in an ESI fragment or a subrequest (inline fragment)?

**Comment by fritzmg** [comment]
No, in an `templates/fe_page.html.twig` for example. Does it work for you?

**Comment by m-vo** [comment]
That's normal behavior, I think, and the same in a regular Symfony app: using `dump` in templates always outputs it at the respective place in the template. IMHO that kind of makes sense as you are controlling the templates anyway and you would loose the context (the exact place where it's output) when outputting to the debug toolbar. 

Do you have a use case where this would be favorable?

**Comment by fritzmg** [comment]
I don't really have a use case, just find it odd that it is different in Twig Templates. Depending on your HTML/CSS, directly outputting it can make it hard to read.

And it not showing up in the profiler at all is also intended?

**Comment by m-vo** [comment]
> And it not showing up in the profiler at all is also intended?

Likely a side effect of this decision. That would probably be a valuable addition, should we pitch it to Symfony?

**Comment by fritzmg** [comment]
> That would probably be a valuable addition, should we pitch it to Symfony?

I think we should. imho the downsides of this outweigh the upside of seeing the dump at exactly the position the template is used - and even that is questionable in my opinion.

Also consider AJAX requests for example: the Symfony Toolbar conveniently will directly show the link to the Profiler for each AJAX request happening on the page and then you could click the Profiler URL of the respective request and analyse the debug output there. But not for any Twig template dumps in this case. You would have to look at the response in the developer tools of the Browser instead.

**Comment by m-vo** [comment]
Good point with AJAX reqests. For other cases I like that it's output in place - for example when rendering lists of things, you can dump a property of a single thing and directly see the value of each one. Most of the time I think you would not use `dump()` (without a parameter), but dump single literals/objects in which case the size of the debug output is quite small and works inside your layout/css.

**Comment by leofeyer** [comment]
> > That would probably be a valuable addition, should we pitch it to Symfony?
> 
> I think we should.

I‘m closing this issue then since there is nothing more to do on our end.
