### ISSUE TITLE
rss/atom-feed: Self reference doesn't match document location

### ISSUE THREAD

**Issue by Anke** [contao/contao#3893]
### Affected version(s)

4.10.7

### Description

Hi,

as described in https://github.com/contao/core/issues/5478 for Contao 3, I still get this recommendation by the Feed Validation Service for Contao 4.10.7:

> This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
> 
>     line 1, column 450: Self reference doesn't match document location
>     ... hare/termine-djk-kanu.xml" rel="self" /></feed>
> 
>   Source: https://djk-kanu.de/share/termine-djk-kanu.xml
>   `<?xml version="1.0" encoding="utf-8"?><feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="de"><title>DJK-Kanu - Termine</title><subtitle>Aktuelle Termine</subtitle><link rel="alternate" href="https://djk-kanu.de/" /><id>https://djk-kanu.de/</id><updated>2019-12-01T22:24:53+01:00</updated><generator>Contao Open Source CMS</generator><link href="http://djk-kanu.de/share/termine-djk-kanu.xml" rel="self" /></feed>`
> 
>   Message: Self reference doesn't match document location
>   Explanation:  When rel="self", the href attribute is expected to identify a resource equivalent to the containing element.

Nothing serious, I know, but maybe worth looking after?

**Comment by fritzmg** [comment]
> 4.10.7

Contao 4.10 has long reached the end of its lifespan. The current Contao versions are 4.9.24 and 4.12.5 respectively.

Regarding your issue: which **Base URL** did you provide in your RSS feed's settings? It appears you used `http://` instead of `https://`. Your RSS feed is _not_ available under `http://djk-kanu.de/share/termine-djk-kanu.xml`.

**Comment by Anke** [comment]
I know, an update is overdue...

The provided base URL is `https://djk-kanu.de/` and the feed is available under `https://djk-kanu.de/share/termine-djk-kanu.xml`

**Comment by fritzmg** [comment]
But the source still says

```xml
<link href="http://djk-kanu.de/share/termine-djk-kanu.xml" rel="self"/>
```

Double check the setting.

> I know, an update is overdue...

You always need to update to the most current Contao version and reproduce the error there first, before filing a possible bug report. But in your case the issue is likely a misconfiguration.

**Comment by Anke** [comment]
Okay, I checked everything once more. RSS settings is https, and in the starting point settings the protocol is also set to https. However I found a hreflang tag in the page layout with http only and added the missing s. Seems to be working now.

Thank you for your quick help! And for your advice concerning the current version.

**Comment by Anke** [comment]
Okay, I checked everything once more. RSS settings is https, and in the starting point settings the protocol is also set to https. However I found a hreflang tag in the page layout with http only and added the missing s. Seems to be working now.

Thank you for your quick help! And for your advice concerning the current version.
