### ISSUE TITLE
Possible BC break with protected `$Template` property

### ISSUE THREAD

**Issue by SeverinGloeckle** [contao/contao#3894]
### Affected version(s)

4.9.24, 4.12.5

### Description

The new `protected $Template` property added in https://github.com/contao/contao/pull/3822 breaks existing code which accesses or modifies the template property of an object which didn't have the property before.

Before the change, the `Template` was added to the object's `arrData` dynamically and thus accessible via its magic methods.

For example, modifying the template of a form via the `compileFormFields` hook is not possible anymore:

````php
/**
 * @Hook("compileFormFields")
 */
public function enhanceForms(array $fields, string $formId, Form $form): array
{
  // This worked before, now the template is protected and thus inaccessible from the outside.
  $form->Template->foo = 'bar';
}
```` 

Whether this was a supported use case is debatable for sure, but I want to raise awareness for the issue.

A possible fix could be handling the `Template` property explicitly via magic methods while probably triggering appropriate deprecations.

**Comment by aschempp** [comment]
@contao/developers didn't we discuss to revert that?

**Comment by SeverinGloeckle** [comment]
In case the use-case was never supported and will not get fixed, a possible fix from the developer's side would be using reflection to access or modify the template property:

````php
/**
 * Add data to a potentially protected Template property of an object.
 */
public static function addToTemplate(object $target, array $data): void
{
    if ($target->Template) {
        foreach ($data as $k => $v) {
            $target->Template->{$k} = $v;
        }

        return;
    }

    $reflection = new ReflectionClass($target);

    if ($reflection->hasProperty('Template')) {
        $property = $reflection->getProperty('Template');
        $property->setAccessible(true);
        $template = $property->getValue($target);

        foreach ($data as $k => $v) {
            $template->{$k} = $v;
        }

        $property->setValue($target, $template);
    }
}
`````

However, using a different way to access the template is preferable (e.g another hook).

**Comment by leofeyer** [comment]
We have already discussed this and agreed to make the property public. @SeverinGloeckle Will this solve your problem?

**Comment by SeverinGloeckle** [comment]
Yes, `public $Template` will fix all issues and make the template accessible again.

**Comment by aschempp** [comment]
I'm not sure we can make it public. It would break for anyone currently setting the property as `protected` or `private` in their child class.

**Comment by fritzmg** [comment]
imho we should revert all previous changes and only fix the originally affected classes (`PageRegular`).

**Comment by leofeyer** [comment]
Shouldn't we at least add a `System::__set()` method that allows to set `$this->Template`? This would be backwards compatible and still allow us to remove the existing `public/protected $Template` properties.

**Comment by SeverinGloeckle** [comment]
> I'm not sure we can make it public. It would break for anyone currently setting the property as `protected` or `private` in their child class.

It's the same as with the new protected property, just the other way around, isn't it?


> Shouldn't we at least add a `System::__set()` method that allows to set `$this->Template`?

Handling the template in `__set` wouldn't cover all use-cases since the property would still be protected and inaccessible from the outside (see hook example above).

Since the `Controller` class doesn't provide its own magic methods, a fix could be provided by using something like a `TemplatePropertyTrait` in the `Controller` which handles the template property explicitly via `__set`, `__get` and `__isset` (and maybe even `__unset`).

The trait can also trigger appropriate deprecation messages so it could be removed again in Contao 5.

A public property is the easier way, though.

**Comment by aschempp** [comment]
> > I'm not sure we can make it public. It would break for anyone currently setting the property as `protected` or `private` in their child class.
> 
> It's the same as with the new protected property, just the other way around, isn't it?

No. You can make a property `public` in your child class if it is `protected` in the parent, but not he other way around.

**Comment by fritzmg** [comment]
My own extension [fritzmg/contao-inherit-article](https://github.com/fritzmg/contao-inherit-article) is affected by this too 🙃

**Comment by ausi** [comment]
> imho we should revert all previous changes and only fix the originally affected classes (`PageRegular`).

Agree.

**Comment by bytehead** [comment]
Is this related (4.9.24)? 

<img width="1046" alt="Bildschirmfoto 2022-01-12 um 09 37 52" src="https://user-images.githubusercontent.com/754921/149092680-9786d197-3d67-4cd5-bec0-6fa73449fe92.png">

**Comment by fritzmg** [comment]
Yes :)

**Comment by rorych** [comment]
As asked in the Contao Slack Support-Channel, i have a case as well, where i try to get the template data for a PDF generation:

```
$oTemplate = new FrontendTemplate('pdf_xy');
$oModuleModel = ModuleModel::findById(xy);
$oModule = new CustomModule($oModuleModel);
$oModule->generate();
$oTemplate->results = $oModule->Template->getData();
return $oTemplate->parse();
```

Since updateing to Contao 4.9.25 i am getting following error:

```
Call to a member function getData() on null
```
