### ISSUE TITLE
Possible improvement for InsertTags::encodeHtmlAttributes()

### ISSUE THREAD

**Issue by Toflar** [contao/contao#3897]
### Affected version(s)

all

### Description

Noticed this using Tideways.

In my case, `InsertTags::encodeHtmlAttributes()` is called 11 times and requires almost 100ms.

- 9000 `preg_match()` calls itself
- 14000`preg_match()` calls in `fixUnclosedTagsAndUrlAttributes()`

Maybe there's a possibility to have some early returns here?

/cc @ausi

**Comment by ausi** [comment]
Closed in favor of #4408
