### ISSUE TITLE
Deprecate the timeZone setting

### ISSUE THREAD

**Issue by ausi** [contao/contao#3900]
See https://github.com/contao/contao/pull/3888#issue-1091663482

**Comment by fritzmg** [comment]
As mentioned in https://github.com/contao/contao/pull/3888#issuecomment-1003565893 I think it is important that the application itself defines the timezone that any entered (non absolute) date strings refer to - and not the server environment. So even if we deprecate the setting, there should still be an alternative.

The concept of having different time zone settings per back end user is something for the far future only obviously, but should may be be kept in mind :).

**Comment by ausi** [comment]
As discussed in the call today, we want to move the setting from the localconfig to the container configuration.

**Comment by richardhj** [comment]
> The concept of having different time zone settings per back end user is something for the far future only obviously, but should may be be kept in mind :).

Just a side note from my side, as I am struggling with timezones right now:

The server timezone (aka model timezone) and view timezone should be able to differ from each other.

In Twig, this can be realized using the [`twig.date.timezone`](https://symfony.com/doc/current/reference/configuration/twig.html#timezone) config. In Symfony forms, this can be realized by setting the [`view_timezone`](https://symfony.com/doc/current/reference/forms/types/datetime.html#view-timezone) option.

So IMHO the `timeZone` setting should be deprecated in favor of a `viewTimeZone` setting, which then will be applied to the DataContainer (forms widgets).

In practice, the server timezone should be always UTC (as an opinioated best practice).

**Comment by aschempp** [comment]
closing in favor of https://github.com/contao/contao/issues/7060
