### ISSUE TITLE
"Unknown option: regular" when creating a new website root

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3901]
### Affected version(s)

4.12, 4.x

### Description

Currently when creating a new website root, the pre selected page type will be `regular`. The type select will then show `Unknown option: regular` and you have to manually switch back to the _Website root_ page type.

/cc @aschempp

**Comment by aschempp** [comment]
Thats because the database field default is `regular` but we filter the options. I would suggest to remove the default, the dropdown will choose it for us.

**Comment by fritzmg** [comment]
That alone won't work unfortunately. The edit mask will look like this then:

![image](https://user-images.githubusercontent.com/4970961/148567021-ec2d4313-53e7-47df-85bf-dd05e5502438.png)

**Comment by aschempp** [comment]
did you by any chance test this in Contao 4.12 as well? Because I think it should behave the same (incorrect) way.

**Comment by fritzmg** [comment]
Yes, this also happens in Contao 4.12.

**Comment by fritzmg** [comment]
Never mind, this is actually an error in [terminal42/contao-folderpage](https://github.com/terminal42/contao-folderpage/).
