### ISSUE TITLE
Should we show the conflicting pages?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3903]
### Description

https://github.com/contao/contao/blob/df10500be0123729bcd59736a870229df00c6ce9/core-bundle/src/EventListener/DataContainer/PageUrlListener.php#L270

The return value is the which page conflicts, should we display that? (Follow-up on #3843)

**Comment by leofeyer** [comment]
As discussed in the Contao call, we could show the page name and the ID: _This alias already exists in page "Foobar" (ID 12)_

**Comment by aschempp** [comment]
see #3924
