### ISSUE TITLE
How to associate listeners with DCAs?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3907]
### Description

The original discussion is here: https://github.com/contao/contao/pull/3630#pullrequestreview-824357882

<img width="808" alt="" src="https://user-images.githubusercontent.com/1192057/148756107-bba8776f-5636-423c-874e-7c0ce6230575.png">

A possible solution besides using static functions as `options_callback` would be to just add comments:

https://github.com/contao/contao/blob/6e3156a0703917cd137d26ecbe3765130aed8276/core-bundle/src/Resources/contao/dca/tl_page.php#L247-L262

**Comment by fritzmg** [comment]
The callback can still be a service with proper DI but still be set in the DCA itself. After all this is what happens in the end anyway.

Besides we already do this for re-usable event listeners like `AvailableTransports` anyway:

* https://github.com/contao/contao/blob/6e3156a0703917cd137d26ecbe3765130aed8276/newsletter-bundle/src/Resources/contao/dca/tl_newsletter_channel.php#L169
* https://github.com/contao/contao/blob/6e3156a0703917cd137d26ecbe3765130aed8276/newsletter-bundle/src/Resources/contao/dca/tl_newsletter.php#L227

**Comment by m-vo** [comment]
In this specific case it's probably best to implement a generic listener in the core bundle and use tagging (optionally with a comment). But for the news and calendar bundle, it would probably be the easiest to just use `[Contao\CoreBundle\…\TheListener::class, 'method']` in the DCA file to reuse the listener. Otherwise you would need a compiler pass to add tags, no?

**Comment by m-vo** [comment]
@fritzmg wins the race by 8s. :racehorse:

**Comment by bezin** [comment]
But within the same bundle, I should still use annotations?

**Comment by SeverinGloeckle** [comment]
Adding comments to the DCA files is, in my opinion, only addressing the symptoms and will probably be a pain to maintain.

The urge to see the source of options or callbacks directly in the DCA is understandable, but is no longer in line with the current state of development.

Even if some callbacks are highlighted in the DCA, there will almost always be modifications that are added outside of the file.

In my view, a change in thinking is necessary: 
**The DCA file is really just the basic structure of the data, while the final configuration is the sum of various factors.**

A solution like the DebugDcaCommand https://github.com/contao/contao/pull/490 introduced by @aschempp offers, in my view, a more sensible approach to debug or just have a look at a DCA.

This can also be made much simpler by standardising the DCAs. In draft https://github.com/contao/contao/pull/3879, for example, the following is possible:

````bash
## Debug any DCA, optionally with a path to a specific node
php vendor/bin/contao-console debug:dca tl_page config.onsubmit_callback

## Output showing callbacks from both the DCA file and from annotations
-
    - tl_page
    - scheduleUpdate
-
    - contao.listener.data_container.content_composition
    - generateArticleForPage
````


This is not as easy as looking in a DCA's file and requires a running application, but it actually provides the real configuration of a DCA resource.

**Comment by aschempp** [comment]
That's exactly why the `DebugDcaCommand` is here, so you can see the actual structure and because I didn't see where the callbacks are from 🙃

**Comment by Toflar** [comment]
I agree, the command is the only correct solution. The DCA location would only suggest there is a listener but it could be removed by some other code. In fact, it can even provide wrong information. The callback is just the same as any event, where you also use the `debug:event-dispatcher` command.
