### ISSUE TITLE
$objPage could be null

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#3928]
### Affected version(s)

4.x

### Description

Hello,

using Contao as API-Framework the $objPage could be null at 
https://github.com/contao/contao/blob/4166f4eeccafb9cdcbd15e5e89728bbb4f1f3a81/core-bundle/src/Resources/contao/library/Contao/Controller.php#L82

in my case i´m using the notificationCenter to send emails during an API-Request and there is a warning because $objPage is null. 

So maybe we can check if $objPage !== null

Thanks and Greetings

**Comment by fritzmg** [comment]
> in my case i´m using the notificationCenter to send emails during an API-Request

Can you explain this in more detail? Does that mean you have a controller and someone is making a request to that controller - which will send a Notification Center message down the line which will render a template somewhere? And your controller's route has a `frontend` `_scope`?

**Comment by xprojects-de** [comment]
yes it is exactly like that.
And i think the notification center needs the email template. This is how I think the error occurs.

**Comment by xprojects-de** [comment]
Looking at the code i think possible use cases are the one mentioned above and also replacing Inserttags in this context. So maybe https://github.com/contao/contao/blob/a5c401df53881cd09edd0e5dfc9813dbb659c251/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L113 is also affected.

###Edit 
But I think in case of InsertTags everything here has already been tested to null... But maybe we can check also... 

For all other uses of objPage the error seems unlikely ... (with the possible exception of content elements such as downloads )

**Comment by fritzmg** [comment]
At least some insert tags have already been adjusted in this regard.
