### ISSUE TITLE
Self closing tags in svg are removed on save

### ISSUE THREAD

**Issue by ghost** [contao/contao#3933]
### Affected version(s)

4.9.23, 4.12.5

### Description

When i use inline svg inside the html content element and save the content, the trailing slashes on self closing tags in svg elements are removed. This leads to the following problem:

When the trailing slashes are removed in this example, the second red `rect` becomes a child of the green `rect` and is not displayed anymore.

```html
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="200" height="100">
  <rect x="0" y="30" width="200" height="50" fill="green" stroke="black" />
  <rect x="0" y="0" width="200" height="50" fill="red" stroke="black" />
</svg>
```

According to the specification (https://html.spec.whatwg.org/multipage/syntax.html#start-tags (see entry 6)), the self-closing tag (on SVG or MathML) should be valid.

**Comment by fritzmg** [comment]
Did you add `<rect>` to the allowed HTML elements?

**Comment by ghost** [comment]
Yes, i allow `svg` and `rect` in settings.

The following shows the html output in the inspector (Google Chrome) for the two variants.
First the correct behavior - here i add the closing tag as a bugfix, second shows the current behavior in Contao (with trailing slash removed on save).

![image](https://user-images.githubusercontent.com/79627896/149521100-6f8db84d-3b65-4fba-a4ef-4cf17d30e9c7.png)
![image](https://user-images.githubusercontent.com/79627896/149521190-09ca2a99-2f6b-46d5-b2cd-467f50344f6a.png)

**Comment by fritzmg** [comment]
> The following shows the html output in the inspector (Google Chrome) for the two variants.

Don't use the inspector. Analyse the actual source (post the source here).

**Comment by ausi** [comment]
Self closing tags are currently not allowed by the sanitizer, please use `<rect></rect>` instead.

**Comment by oexler** [comment]
> > The following shows the html output in the inspector (Google Chrome) for the two variants.
> 
> Don't use the inspector. Analyse the actual source (post the source here).

I think the inspector was only used to show the interpretation of the browser without trailing slashes.


> Self closing tags are currently not allowed by the sanitizer, please use `<rect></rect>` instead.

Why are they not allowed, when they are valid html.
In this case it was just a sample SVG where you can do this manually. But sometimes SVGs are a bit larger and then fixing them is cumbersome.

**Comment by ausi** [comment]
> Why are they not allowed, when they are valid html.

Because they are only supported in some foreign objects like `<svg>`.

You can test that by comparing `<div /><div />` with `<svg><div /><div />` in your browser. In the first one the `/` gets ignored and in the second one it gets parsed as self-closing.

> But sometimes SVGs are a bit larger and then fixing them is cumbersome.

For larger or more complex SVG files I would recomend storing them in the file manager as _.svg_ files or inside a template.

**Comment by oexler** [comment]
Yes I know, that they are ignored, as the spec states 'This character has no effect on void elements, but on foreign elements it marks the start tag as self-closing.'

> For larger or more complex SVG files I would recomend storing them in the file manager as _.svg_ files or inside a template.

Then I should say many small optimized inline SVG instead of large.

Shouldn't contao allow valid html? For me foreign objects are part of it.
Also I see no point in removing the slashes, as they would have no effect anyway.

**Comment by ausi** [comment]
The `/` is often used to trick browsers and sanitizers into different parsing states.

But if you trust the backend users of your project you can disable the HTML attribute sanitization in the system settings by setting the allowed attributes for the element `*` to `*`. This way the tags themself do not get modified at all.

![Bildschirmfoto 2022-01-14 um 15 15 52](https://user-images.githubusercontent.com/367169/149529632-ecf8229e-f743-4995-9f73-6d52320bfe7b.png)
