### ISSUE TITLE
Systemwartung: Fehler bei Job "Vorschau-Cache leeren"

### ISSUE THREAD

**Issue by jochi44** [contao/contao#3948]
### Affected version(s)

4.13.0-RC1

### Description

Die Ausführung der Systemwartung im Backend führt beim Job "Vorschau-Cache leeren" zu folgendem Fehler:

```
Internal Server Error
Was ist das Problem?
Attempted to load class "ContaoContext" from namespace "Contao". Did you forget a "use" statement for e.g. "Contao\CoreBundle\Asset\ContaoContext" or "Contao\CoreBundle\Monolog\ContaoContext"?
```

Im error.log des Servers sehe ich folgende Meldung:

`2022/01/18 12:13:20 [error] 1112#1112: *12626 FastCGI sent in stderr: "PHP message: PHP Warning:  scandir(/var/www/clients/web/assets/previews/): Failed to open directory: No such file or directory in /var/www/clients/web/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Folder.php on line 586PHP message: PHP Warning:  scandir(): (errno 2): No such file or directory in /var/www/clients/web/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Folder.php on line 586PHP message: PHP Warning:  foreach() argument must be of type array|object, bool given in /var/www/clients/web/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Folder.php on line 586" while reading response header from upstream, client: 111.111.111.111, server: abc.xyz, request: "POST /contao?do=maintenance&ref=My5VwcaP HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web10.sock:", host: "abc.xyz", referrer: "http://abc.xyz/"`

**Comment by fritzmg** [comment]
https://github.com/contao/contao/pull/3702 was merged after https://github.com/contao/contao/pull/3848 and so we still have

https://github.com/contao/contao/blob/4b4d6adb7dd9ff76f095142a7e6f9fcc0ba7d7e3/core-bundle/src/Resources/contao/library/Contao/Automator.php#L152

instead of

```php
System::getContainer()->get('monolog.logger.contao.cron')->info('Purged the preview cache');
```

**Comment by fritzmg** [comment]
@jochi44 regarding your second error: that is unrelated. If you have more information about this error (e.g. a stack trace via the debug mode) please open a separate issue about that.
