### ISSUE TITLE
Löschen des Home-Verzeichnis beim Löschen des Users (Optional)

### ISSUE THREAD

**Issue by zonky2** [contao/contao#395]
**Description**  
Wenn ein User gelöscht wird (FE oder BE) wäre es schön, wenn sein vorhandenes Userverzeichnis (Home-Verzeichnis) mit gelöscht wird. Das dürfte im Sinne der DSGVO sogar Pflicht sein - Plattenplatz spart es auch :D 

Eine zus. Checkbox bei den Moduleinstellungen "Registrierung" wäre prima z.B. "Userverzeichnis bei Kontoauflösung mit löschen"

Prima wäre, wenn die Checkbox "Ein Home-Verzeichnis festlegen" deaktiviert wird, und Checkbox Userverzeichnis bei Kontoauflösung mit löschen" an war, die Abfrage kommt, ob alle Userverzeichnisse der entsprechenden Gruppen gelöscht wird.

Off-Topic: Aus meiner Sicht würde ich die Angabe zum Home-Verzeichnis in die Verwaltung der Mitgliedergruppe setzen. Es ist ja möglich, zwei Registrierungsmodule zu einer Mitgliedergruppe zu machen einmal mit und einmal ohne Home-Verzeichnis... was dann beim Löschen?

Sofern das Feature "gefallen findet" kann man mich gern bezüglich Finanzierung ansprechen.

**Comment by leofeyer** [comment]
Wir sollten die Option zum Modul "Konto schließen" hinzufügen, damit das Home-Verzeichnis mit gelöscht wird, wenn ein Mitglied sein Konto schließt. Wenn Du als Admin ein Mitglied entfernst, musst Du vermutlich selbst daran denken.

**Comment by zonky2** [comment]
o.k. - wäre ein Anfang...

Mein "off-topic" sollte ggf. für C5 irgendwo vorgehalten werden - den BC-Break könnte man sicher erst dann machen.

**Comment by leofeyer** [comment]
Wie am 6. Juni auf Mumble besprochen, sollten wir das "Konto schließen"-Modul so erweitern, dass der Admin festlegen kann, dass beim Schließen eines Kontos auch das Home-Verzeichnis gelöscht wird. Optionen:

* Home-Verzeichnis nicht löschen
* Home-Verzeichnis löschen, wenn nicht geshared
* Home-Verzeichnis immer löschen

**Comment by zonky2** [comment]
Ergänzung: als Radio oder Select

**Comment by jochi44** [comment]
Ich möchte das Thema erneut aufgreifen, bin bei einem aktuellen Projekt genau auf diese Anforderung gestoßen.
In Hinblick auf die DSGVO sollte bei der Kontolöschung durch das Mitglied dessen Home-Verzeichnis auch gelöscht werden.

**Comment by aschempp** [comment]
@jochi44 wir würden uns über einen Pull-Request freuen, der das Feature implementiert 😊

**Comment by zonky2** [comment]
eine Frage, wo ich bisher hängen geblieben bin, ist

> wenn nicht geshared

soll heißen, wenn nicht ein anderes Member sein Homeverzeichnis auf den selben Pfad liegt?

**Comment by jochi44** [comment]
> @jochi44 wir würden uns über einen Pull-Request freuen, der das Feature implementiert 😊

Ja, @aschempp, ich würde da wirklich gerne helfen, nur bin ich mehr der User und Tester als der Entwickler. Sprich: hab keine Ahnung von einer möglichen technischen Umsetzung.

**Comment by zonky2** [comment]
> hab keine Ahnung von einer möglichen technischen Umsetzung.

muss man nicht haben - Finanzierung des Features reicht... frag Deinen Auftraggeber, was er dafür bezahlen möchte

Jemanden, der das dann macht, findet sich sicher in Slack oder im Forum

**Comment by leofeyer** [comment]
This has been implemented in #3522 meanwhile.
