### ISSUE TITLE
Uniform name for the custom template

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#3950]
### Description

Based on the 4.13.0 RC1, the content element is called "Eigenes Template" in German.
As a module, this can then be found under "Individuelles Template".

Maybe the name should be consistent?

**Comment by fkaminski** [comment]
Suggestion: I find the name "**Individuelles Template**" basically more appropriate

**Comment by leofeyer** [comment]
Fixed.

<img width="692" alt="" src="https://user-images.githubusercontent.com/1192057/150163721-7b1681ea-eb38-40e4-9007-3f88b08f0552.png">
