### ISSUE TITLE
Invalid log calls with new logger

### ISSUE THREAD

**Issue by aschempp** [contao/contao#3951]
### Affected version(s)

4.13

### Description

I get the following error message in Contao 4.13

```
Argument 2 passed to Contao\CoreBundle\Monolog\SystemLogger::info() must be of the type array, null given, called in vendor/contao/core-bundle/src/Resources/contao/library/Contao/Email.php on line 614
```

It looks like https://github.com/contao/contao/blob/5.x/core-bundle/src/Resources/contao/library/Contao/Email.php#L607 should default to an empty array and not null. Not sure if there are other places to fix this. @SeverinGloeckle would you be able to look into this? 🙃

**Comment by SeverinGloeckle** [comment]
Thanks for the heads up debugging. Fixed in https://github.com/contao/contao/pull/3952.
