### ISSUE TITLE
Add help wizard description(s) for module "Root page dependent modules"

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#3954]
### Affected version(s)

4.13.0-RC1

### Description

#3613
Please add descriptions (de/en/ translations etc. ) in help wizard.

**Comment by fritzmg** [comment]
Can you please specify what you mean exactly?

**Comment by fkaminski** [comment]
![image](https://user-images.githubusercontent.com/7679799/149970982-b474f365-a0c0-4310-b397-a85bee409588.png)

**Comment by leofeyer** [comment]
Fixed in bfde0b7b5b0bb604da6b82e23617074fecc9ffed.
