### ISSUE TITLE
Add requirement for symfony/security-core

### ISSUE THREAD

**Issue by ausi** [contao/contao#3956]
### Affected version(s)

4.13

### Description

Because we use it in https://github.com/contao/contao/blob/a5c401df53881cd09edd0e5dfc9813dbb659c251/core-bundle/src/Resources/contao/library/Contao/User.php#L18

we should add `"symfony/security-core": "^5.4",`

**Comment by leofeyer** [comment]
Added in 086f7db3cdf11ddd50f7ec5438469d8997b65521.
