### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#3958]
### Affected version(s)

4.13

### Description

If I create a new "Website root" the maintenance mode is enabled by default.

Is that intentional, I would prefer if it was disabled.

The Alert bell no longer shows the maintenance mode.

I would add the hint again and write the list of domains in maintenance mode in the alert window.

**Comment by fritzmg** [comment]
> The Alert bell no longer shows the maintenance mode.
>
> I would add the hint again and write the list of domains in maintenance mode in the alert window.

👍

**Comment by leofeyer** [comment]
> If I create a new "Website root" the maintenance mode is enabled by default.
> 
> Is that intentional, I would prefer if it was disabled.

See #3969.

> The Alert bell no longer shows the maintenance mode.
> 
> I would add the hint again and write the list of domains in maintenance mode in the alert window.

I'm not sure. We showed the warning, because the maintenance mode in Contao <4.13 was enabled globally, so no websites at all were online. Now, however, if the global maintenance mode is enabled, it will also affect the back end, so there is no way you will not notice. And running one of several websites in maintenance mode can be desired, so IDK if a warning is appropriate.

**Comment by m-vo** [comment]
> And running one of several websites in maintenance mode can be desired, so IDK if a warning is appropriate.

It should at least somehow be noticeable by looking at the page structure IMHO.

**Comment by netzarbeiter** [comment]
we got the root-icon in blue for the website root and the same icon comes in grey for unpublished. We could add the icon in red if the maintenance mode is enabled.

**Comment by m-vo** [comment]
> we got the root-icon in blue for the website root and the same icon comes in grey for unpublished. We could a the icon in red if the maintenance mode is enabled.

Or alternatively just a gray `[maintenance mode active]` behind the name so that we do not have to mix two states (published/unpublished + maintenance enabled/disabled).

Edit: Here is a mockup:
![image](https://user-images.githubusercontent.com/5305677/150170459-3d911ea7-20e3-4159-ab1b-4e854fe81e04.png)

**Comment by Tastaturberuf** [comment]
i like to have information behind the page name e.g. ID, layout etc. 

i think it might be a better approach if we add a button to the right (via button callback) and only show it when maintenance mode is active. when clicked, perhaps with JS-alert, it can then exit maintenance mode. 

the icon is placeholder, added it quickly in chrome tools.

or maybe the pencil can go red or something. 

![image](https://user-images.githubusercontent.com/1027521/150300060-e06ebac1-b406-4b29-9000-7c8daeb4b0d4.png)

**Comment by asaage** [comment]
i would like an icon-solution - preferably a red globe like described here: https://github.com/contao/contao/issues/3958#issuecomment-1016622353
or an additional exclamation-icon like seen in the changelanguage extension for untranslated things.
The grey text might interfere with some BE-customisations and there are already enough toggle/action-icons on the right side.

**Comment by fritzmg** [comment]
I am also in favour of a label icon.

**Comment by aschempp** [comment]
I like the red maintenance globe, that does not take up any more space and works perfectly with the existing icons that represent page status (published, unpublished, protected, etc.). see https://github.com/contao/contao/pull/3978
