### ISSUE TITLE
Database\Statement does not handle quoted column names

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3964]
### Affected version(s)

4.13.0-RC1

### Description

This is a follow-up on #3207.

https://github.com/contao/contao/blob/514fecd74f3086ae12de95902ce1fe59a0487371/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php#L158-L161

The regex does not handle columns names that are already quoted, e.g. <code>where \`hash\`='CacheControl'</code>.

<img width="783" alt="" src="https://user-images.githubusercontent.com/1192057/150106791-df47fdeb-4868-4c96-8a38-180c456b8db1.png">

@ausi Allowing backticks in the regex fixed the issue on my system. I am not sure if that is the correct fix, though.

**Comment by ausi** [comment]
how about this one?

```php
'/^(?:[A-Za-z0-9_$]+|`[^`]+`)$/'
```

**Comment by leofeyer** [comment]
Whatever you think is appropriate. 👍

**Comment by m-vo** [comment]
> how about this one?
> 
> ```
> '/^(?:[A-Za-z0-9_$]+|`[^`]+`)$/'
> ```

Why do we need the non-capturing group `?:`?

```php
'/^([A-Za-z0-9_$]+|`[^`]+`)$/'
```

**Comment by ausi** [comment]
> Why do we need the non-capturing group `?:`?

It’s my default goto as it can be more performant ☺️
But it’s negligible in this case so I’m fine either way.
