### ISSUE TITLE
Chosen und CSS-Inline-Style bei [foobar]

### ISSUE THREAD

**Issue by zonky2** [contao/contao#397]
wenn in den Chosen-Selects `[foobar]` steht, kommt bei der Suche nach Buchstaben, die im vom Chosen generierten CSS-Inlinse-Style wie `t` eine "zerwürfelte Ausgabe" :D 

![choosen](https://user-images.githubusercontent.com/1045318/54214000-b8321400-44e5-11e9-9813-da6f0011c5ee.jpg)

das ist schon mind. seit 3.5.31 so in 4.4 dito

**Comment by leofeyer** [comment]
Wie genau kann ich das reproduzieren?

**Comment by zonky2** [comment]
Theme > Layout >eingebundene Module > "t" eingeben

https://demo.contao.org/contao?do=themes&table=tl_layout&id=15&act=edit&rt=s5sps1b1cKpPD2HCibBeGaXVp6NX9OoYBO4zMJq8sDk&ref=qhWkMyyM

**Comment by leofeyer** [comment]
Behoben in contao-components/chosen@ea040f6c9a217f3a3d5253634467dc2ac3434485.

**Comment by zonky2** [comment]
thx
