### ISSUE TITLE
Preview link improvements

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3974]
Currently when clicking _Share URL_ in the preview bar, the back end opens in a new tab in order to create a new `tl_preview_link` entry. However, after saving, you will always have to manually click on the _Preview links_ main menu entry in the back end, in order to actually be able to share this URL (_Save and close_ will likely send you somewhere else, unless you happened to have clicked on _Preview links_ before clicking _Share URL_). Furthermore, once more preview link entries are in that view, it will not be easy to find out which of these preview links you just generated and thus want to share.

I wanted to discuss how we could improve this. May be an additional button _Save and copy preview link_?

**Comment by aschempp** [comment]
Good point. Maybe we can also improve this by adding a (blue) info bar at the top of the record with the share link?

**Comment by fritzmg** [comment]
> Maybe we can also improve this by adding a (blue) info bar at the top of the record with the share link?

Yes, I thought about something like that as well - however, a user might then be inclined to copy that URL immediately, without first saving the record 🤔. And then the preview link will either not work - or any changes would not have been applied (e.g. different expiration time, showing unpublished items).

**Comment by leofeyer** [comment]
IMHO we should make sure that _Save and close_ takes the user to the preview link list. Maybe we can overwrite the referrer URL?

**Comment by fritzmg** [comment]
> IMHO we should make sure that Save and close takes the user to the preview link list. Maybe we can overwrite the referrer URL?

Yes, I was already looking at that. Should be possible in a `config.onload` callback. However, the UX is still not perfect, as it will be difficult to identify which of the preview links you just created or edited.

**Comment by aschempp** [comment]
So in summary this should do both cases?
 1. overwrite the `saveNclose` button/return URL
 2. add a blue info box with the share link, when `tstamp>0`

**Comment by fritzmg** [comment]
> add a blue info box with the share link, when tstamp>0

Still not perfect when you edit a preview link, but not sure how perfect we can actually make this 😁

**Comment by leofeyer** [comment]
No blue info box, please.

**Comment by aschempp** [comment]
> No blue info box, please.

any other idea how the user could get the preview link without needing to search the just-created link in the list and clicking the copy button again?

**Comment by leofeyer** [comment]
Can we add it to their clipboard via JS when they click _Save_ or _Save and close_?

**Comment by fritzmg** [comment]
Yes, and then we could add a `Message` saying that it was copied to the clipboard.

**Comment by SeverinGloeckle** [comment]
As I understand, the share URL only requires the ID of the record, which already exists when editing the record for the first time, so the share URL may be generated even without saving the record first. In addition, the share URL remains the same even if settings of the record are modified.

With this setup, I'd suggest the following interface:
- Add an additional, disabled widget "Share URL" below "Target URL".
- Add a wizard icon to copy the value of the widget to the clipboard (via JavaScript, maybe with an alert as confirmation/browser fallback).
- Add a warning (via `Message`) as long as the preview record is not enabled, indicating that the share URL will not work for an unpublished link.
- As long as the link has not been activated and thus saved once, the warning remains visible.

Going this way provides a more comprehensible interface than overloading the save action with another hidden action.

The share operation in the list view may be kept as an alternative way to getting the share URL directly from the list view.

Another small note: If this was a feature for a customer, I'd proabably also add some kind of "comment" or "title" field to allow editors to add some (internal) information to a preview link (e.g. "Preview of new frontpage 2022-01"). But that is probably a matter of personal preference and may be out of the initial scope.

**Comment by fritzmg** [comment]
> As I understand, the share URL only requires the ID of the record, which already exists when editing the record for the first time, so the share URL may be generated even without saving the record first.

Yes, but if you allow to copy the URL before the current changes are saved, then the user might be inclined to.. well.. copy the changes before the changes are saved :)

**Comment by leofeyer** [comment]
While you are on this, please also add the missing `'exclude' => true` in the `tl_preview_link` DCA.

**Comment by aschempp** [comment]
> While you are on this, please also add the missing `'exclude' => true` in the `tl_preview_link` DCA.

Not sure if that was in a ticket or on our public call where I explained this before. If you have access to the preview module in the back end, it never makes sense not to have access to all fields. Preview links are person (you can only see yours if you're not an admin), therefore it e.g. makes no sense to create a preview link if you can't publish it.

**Comment by SeverinGloeckle** [comment]
> > As I understand, the share URL only requires the ID of the record, which already exists when editing the record for the first time, so the share URL may be generated even without saving the record first.
> 
> Yes, but if you allow to copy the URL before the current changes are saved, then the user might be inclined to.. well.. copy the changes before the changes are saved :)

That's a fair point. However, I don't think patronising the user is necessary in this case, since all of Contao always requires a record to be saved before changes are applied.

One possibility would be an additional hint if the form is "dirty" (e.g. _"Please save your changes to update the settings of the preview link"_). Whether this is actually necessary can be discussed.

@aschempp if a change as described in https://github.com/contao/contao/issues/3974#issuecomment-1017433017 should be the way to go, feel free to let me know if you need any support.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to replace the "save and close" button with an "save and copy to clipboard" button.
