### ISSUE TITLE
Seitenlayouts im Debugmodus nicht erstellbar

### ISSUE THREAD

**Issue by tme55** [contao/contao#3976]
### Affected version(s)

4.13.0-RC1

### Description

Während im Backend der Debugmodus aktiv ist, kann kein neues Seitenlayout erstellt werden. Im Bereich Stylesheets -> CSS-Framework  erscheint die Fehlermeldung
`Warning: Array to string conversion`

Ein Speichern ist nicht möglich.

**Comment by fritzmg** [comment]
Hm, I cannot reproduce in `4.13.0-RC1`. This is an error that should already be fixed in `4.13.0-RC1`.

**Comment by fkaminski** [comment]
I cannot reproduce this in 4.13.0-RC1 with PHP 7.4.20.

**Comment by fritzmg** [comment]
Actually, I can reproduce it in PHP 8.
