### ISSUE TITLE
Datenbankoperationen erzeugen Volllast

### ISSUE THREAD

**Issue by de-es** [contao/contao#3980]
### Affected version(s)

4.13.0-RC1

### Description

Befehle mit bestimmten Datenbankoperationen wie `contao:backup:create` und `contao:migrate --no-backup` (hier explizit ohne Backup, da es nicht nur am Backup liegt) brauchen zur vollständigen Ausführung wider Erwarten mehrere Minuten statt Sekunden. Während der laufenden Ausführung ist der Datenbankprozess dauerhaft auf 100%. Befehle mit "einfachen" Operationen wie `contao:user:list` oder auch Arbeiten im Backend funktionieren dagegen ohne Probleme.

Ein Downgrade von `doctrine/dbal` (3.3.0 => 3.2.2) behebt die Probleme sofort. 3.3.0 wurde als Abhängigkeit automatisch installiert.

Testumgebung: Linux, PHP 7.4/8.0, MariaDB 10.6

**Comment by fritzmg** [comment]
@xprojects-de also reported a performance issue with `doctrine/dbal` 3.x. @xprojects-de could you test if downgrading `doctrine/dbal` to `<3.3` helps? e.g. by adding a conflict for `"doctrine/dbal": ">=3.3"`.

**Comment by xprojects-de** [comment]
Hello all,

I've evaluated it and got the following results (See Profiling-Files).
My result was that in my case the SchemaCreation has the greatest impact. Without that the results are almost comparable .
But i think at SchemaCreation there are a lot of PDO->queries! So maybe every query is bit slower in 3.3.x...

I also added the installTool Profileing files for 3.2 and 3.3.

Using the 3.3 the PDO-query is slower than 3.2! 3.2 is comparable to 2.13. Jipi!! :-) 

So somthing is going wrong in 3.3x, so maybe we have to use 3.2.x now..!?!

Thanks and Greetings

**Comment by xprojects-de** [comment]
[installtool_3.2.gz](https://github.com/contao/contao/files/7913102/installtool_3.2.gz)
[installtool_3.3.gz](https://github.com/contao/contao/files/7913104/installtool_3.3.gz)

... There was no migration to do. Just check the Schema.

**Comment by xprojects-de** [comment]
[test_A_withCreateSchema_3.2.gz](https://github.com/contao/contao/files/7913107/test_A_withCreateSchema_3.2.gz)
[test_A_withCreateSchema_3.3.gz](https://github.com/contao/contao/files/7913111/test_A_withCreateSchema_3.3.gz)
[test_B_withoutCreateSchema_3.2.gz](https://github.com/contao/contao/files/7913116/test_B_withoutCreateSchema_3.2.gz)
[test_B_withoutCreateSchema_3.3.gz](https://github.com/contao/contao/files/7913117/test_B_withoutCreateSchema_3.3.gz)

**Comment by fritzmg** [comment]
> So something is going wrong in 3.3x, so maybe we have to use 3.2.x now..!?!

In the mean time you can add said conflict. 

We could also add a conflict in `contao/conflicts` before releasing 4.13, if this issue isn't resolved until then.

**Comment by xprojects-de** [comment]
Should i addan issue at doctrine/dbal adding the profiling files or does that not make sense?

**Comment by xprojects-de** [comment]
see also https://github.com/doctrine/dbal/issues/5195

**Comment by xprojects-de** [comment]
@de-es 

Can you please replace the method "getListTableForeignKeysSQL" under "vendor/doctrine/dbal/src/Platforms/AbstractMySQLPlatform" as follow and check your test again. It would be interesting if the performance loss is gone...

Thanks

###edit

```php    
public function getListTableForeignKeysSQL($table, $database = null)
    {
        return 'SELECT k.CONSTRAINT_NAME, k.COLUMN_NAME, k.REFERENCED_TABLE_NAME, ' .
               'k.REFERENCED_COLUMN_NAME /*!50116 , c.UPDATE_RULE, c.DELETE_RULE */ ' .
               'FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k /*!50116 ' .
               'INNER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS c ON ' .
               'c.CONSTRAINT_NAME = k.CONSTRAINT_NAME AND ' .
               'c.TABLE_NAME = k.TABLE_NAME */ ' .
               'WHERE k.TABLE_NAME = ' . $this->quoteStringLiteral($table) . ' ' .
               'AND k.TABLE_SCHEMA = ' . $this->getDatabaseNameSQL($database) . ' ' .
               ' /*!50116 AND c.constraint_schema = ' . $this->getDatabaseNameSQL($database) . ' */' . ' ' .
               'ORDER BY k.ORDINAL_POSITION';
  
    }
```

**Comment by de-es** [comment]
Da scheinen ein paar Kommentar-* verloren gegangen zu sein (oder?), denn es kam zu SQL-Fehlern. Mit folgendem Statement klappt es und der Performanceeinbruch ist weg 💪:

```
        return 'SELECT k.CONSTRAINT_NAME, k.COLUMN_NAME, k.REFERENCED_TABLE_NAME, ' .
            'k.REFERENCED_COLUMN_NAME /*!50116 , c.UPDATE_RULE, c.DELETE_RULE */ ' .
            'FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE k /*!50116 ' .
            'INNER JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS c ON ' .
            'c.CONSTRAINT_NAME = k.CONSTRAINT_NAME AND ' .
            'c.TABLE_NAME = k.TABLE_NAME */ ' .
            'WHERE k.TABLE_NAME = ' . $this->quoteStringLiteral($table) . ' ' .
            'AND k.TABLE_SCHEMA = ' . $this->getDatabaseNameSQL($database) . ' ' .
            ' /*!50116 AND c.constraint_schema = ' . $this->getDatabaseNameSQL($database) . ' */' . ' ' .
            'ORDER BY k.ORDINAL_POSITION';

```

**Comment by m-vo** [comment]
@xprojects-de Could you maybe check how the execution plans differ when directly running both queries with `EXPLAIN ANALYZE SELECT […]`?

Edit: Nvm, just realized @morozov is already on that track in the linked issue over at doctrine/dbal. :relaxed:

**Comment by fritzmg** [comment]
@xprojects-de which MySQL server are you running? Just in case this makes a difference (initial author uses MariaDB 10.6 for instance).

**Comment by xprojects-de** [comment]
Tested it on MySql5 and also MariaDB 10.5.x...

Same behaviour...

**Comment by xprojects-de** [comment]
@fritzmg @m-vo 
see https://github.com/doctrine/dbal/issues/5195

Do you understand why it´s a different when using the mysql executable and using php executable!?!?!

###edit
Let´s wait for the reply from @morozov

**Comment by xprojects-de** [comment]
@fritzmg @m-vo 
Should we add a conflict for 3.3.0? So in 3.3.1 the Bug should be solved... maybe it's only necessarry if 4.13 is out before 3.3.1 is released...

**Comment by xprojects-de** [comment]
@de-es Final test :-) 

Can you also checkout the 3.3.x branch and test again? Then we would have verified it again! 

Thanks

**Comment by de-es** [comment]
Looking good so far. Thanks for debugging. :+1:

**Comment by m-vo** [comment]
> Should we add a conflict for 3.3.0? 

I assume 3.3.1 will be released shortly, so I'd wait a few days and otherwise add a conflict for 3.3.0 only that'll resolve itself.

**Comment by leofeyer** [comment]
New Doctrine versions have been released meanwhile.
