### ISSUE TITLE
Limit the number of members in the preview bar

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#3985]
I would also add `LIMIT 20` to the db query, but it might be too opinionated, what do you think?

The first request (with two initial letters of the username) already returns 3000 results for me; does it make sense for browser to download, `JSON.parse` and insert 3000 elements into the DOM at this point? I find `select`s unusable anyway, when options list is higher then screen height. Or would you rather consider it an edge-case?

_Originally posted by @ameotoko in https://github.com/contao/contao/issues/3790#issuecomment-991067385_

**Comment by leofeyer** [comment]
So how can this be accomplished in Doctrine/DBAL? Using `LIMIT 20` in the query is only compatible with MySQL and PostgreSQL (probably the only two DB systems we will ever target).

**Comment by ausi** [comment]
> So how can this be accomplished in Doctrine/DBAL?

Using `->setMaxResults(20)` should work fine AFAIK.
