### ISSUE TITLE
Kommentar-Benachrichtigungsmail: Bearbeitungslink für Autor trotz fehlender Rechte

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#3988]
### Affected version(s)

4.12.5

### Description

In der Demo läßt sich das nicht testen, weil das System keine E-Mail verschickt.

Wenn Events oder Nachrichten kommentiert werden und der Autor eine Benachrichtungsmail bekommt, ist in der Mail ein Bearbeitungslink für das Backend, obwohl der Autor keine Rechte dafür hat.

Siehe auch https://community.contao.org/de/showthread.php?82340-Kommentar-Benachrichtigungen-an-Autor-aber-fehlende-Rechte

**Comment by fritzmg** [comment]
We can add an additional check for whether the author has access to the comments module here:

https://github.com/contao/contao/blob/64952eea57830f86ff95928f3810b5e5aac6d169/news-bundle/src/Resources/contao/modules/ModuleNewsReader.php#L211-L215

**Comment by aschempp** [comment]
But then the author would not get an email at all, right? Begs the question whether we can remove just the link if she does not have access to the module?

**Comment by fritzmg** [comment]
> But then the author would not get an email at all, right? Begs the question whether we can remove just the link if she does not have access to the module?

Currently `Comments::renderCommentForm` (which sends the admin/author notification) does not know about back end users. It only receives the email addresses to be notified. We could of course load the back end user again based on the email address though.

**Comment by leofeyer** [comment]
I consider it bad practice to allow people to write news articles but not to handle comments on them. Then you should probably just disable the comments form completely.
