### ISSUE TITLE
Alias der Webseite hat bei einem PageController mit absolutem Pfad in "path" weiterhin Kontrolle über das Routing

### ISSUE THREAD

**Issue by mwitzmann** [contao/contao#3989]
### Affected version(s)

4.12.5

### Description

In meiner Testinstallation (4.12.5) gibt mir das System einen 404 Fehler, wenn der Alias eines PageControllers “leer” ist und man versucht, einen dynamischen Pfad aufzurufen.

Beispiel:

```php
<?php
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Page(contentComposition=true, path="/test/{slug?}", requirements={"slug"=".+"})
 */
class TestPageController extends AbstractController
{
	public function __invoke(Request $request, PageModel $pageModel, $slug): Response
    {
    	// Der Alias der Seite ist "leer"
    	// /test -> funktioniert
    	// /test/5 -> zeigt einen 404-Fehler

    	// Der Alias der Seite ist "test"
    	// /test -> funktioniert
    	// /test/5 -> funktioniert
    }
}
```

**Comment by mwitzmann** [comment]
Ich habe einpaar Tests gemacht:

Tests:
tl_page.alias = leer; {slug}, default (null) gesetzt; Route: /test -> funktioniert nicht
tl_page.alias = test; {slug}, default (null) gesetzt; Route: /test -> funktioniert nicht
tl_page.alias = leer; {slug?}, default nicht gesetzt; Route: /test -> funktioniert
tl_page.alias = test; {slug?}, default nicht gesetzt; Route: /test -> funktioniert

tl_page.alias = leer; {slug}, default (null) gesetzt; Route: /test/5 -> funktioniert
tl_page.alias = test; {slug}, default (null) gesetzt; Route: /test/5 -> funktioniert
tl_page.alias = leer; {slug?}, default nicht gesetzt; Route: /test/5 -> funktioniert
tl_page.alias = test; {slug?}, default nicht gesetzt; Route: /test/5 -> funktioniert

tl_page.alias = leer; {slug}, default (null) gesetzt; Route: /test/5/abc -> funktioniert nicht
tl_page.alias = test; {slug}, default (null) gesetzt; Route: /test/5/abc -> funktioniert
tl_page.alias = leer; {slug?}, default nicht gesetzt; Route: /test/5/abc -> funktioniert nicht
tl_page.alias = test; {slug?}, default nicht gesetzt; Route: /test/5/abc -> funktioniert

tl_page.alias = leer; {slug?}, default (null) gesetzt; Route: /test -> funktioniert
tl_page.alias = test; {slug?}, default (null) gesetzt; Route: /test -> funktioniert

tl_page.alias = leer; {slug?}, default (null) gesetzt; Route: /test/5 -> funktioniert
tl_page.alias = test; {slug?}, default (null) gesetzt; Route: /test/5 -> funktioniert

tl_page.alias = leer; {slug?}, default (null) gesetzt; Route: /test/5/abc -> funktioniert nicht
tl_page.alias = test; {slug?}, default (null) gesetzt; Route: /test/5/abc -> funktioniert

**Comment by aschempp** [comment]
https://github.com/contao/contao/pull/4026 sollte das Problem beheben, kannst du dies testen?

**Comment by mwitzmann** [comment]
Funktioniert nun bei mir!
