### ISSUE TITLE
LogoutHandler not executed for back end logouts

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#3998]
### Affected version(s)

4.12, 4.13

### Description

In Contao 4.12 and 4.13 the `Contao\CoreBundle\Security\Logout\LogoutHandler` is not executed for back end logouts in the Contao Managed Edition, only for front end logouts (which also means the `postLogout` hook is not executed). In Contao 4.9 said `LogoutHandler` is correctly executed for front end and back end logouts. You'll also notice that you won't find any _User "…" has logged out_ system log entries for back end logouts in 4.12 and up.

Interestingly the `Contao\ManagerBundle\Security\Logout\LogoutHandler` _is_ called.

**Comment by fritzmg** [comment]
This may be a bug in Symfony's BC layer for the deprecated `LogoutHandlerInterface`. Downgrading `symfony/security-http` to `^4.4` fixes the problem. I also noticed [other issues](https://github.com/contao/contao/pull/2818#issuecomment-788272728) with this BC layer some time ago (but unfortunately never got around to further analysing it and creating a PR for Symfony or at least an issue).

**Comment by bytehead** [comment]
Maybe my PR here is missing, see https://github.com/contao/contao/issues/2862#issuecomment-1016857068.

**Comment by fritzmg** [comment]
Yes, but it is also broken in Contao 4.12 though where we still support Symfony 4.4.

**Comment by bytehead** [comment]
This will be fixed by #4303.

<img width="401" alt="Bildschirmfoto 2022-03-21 um 15 01 11" src="https://user-images.githubusercontent.com/754921/159277354-fcd0fd25-5e97-42cf-af34-373a8eaa4473.png">
