### ISSUE TITLE
Remove "disableAlias" mode

### ISSUE THREAD

**Issue by aschempp** [contao/contao#40]
The `disableAlias` mode does not generate URLs with `index.php/alias.html`, instead it uses `index.php?id=5`. 

I think we should drop this in Contao 4. Can anyone remember why this was supported in the first place? I remember something about old IIS support…

Opinions/votes?

**Comment by Toflar** [comment]
I think we could drop that, I've never used this option in 7 years...

**Comment by leofeyer** [comment]
+1

**Comment by stefansl** [comment]
+1

**Comment by aschempp** [comment]
https://github.com/contao/core-bundle/pull/39 removes it from contao/core-bundle, but we still need to remove it from all other bundles.

**Comment by leofeyer** [comment]
Done.
