### ISSUE TITLE
Captcha field of module subscribe has always the same ID

### ISSUE THREAD

**Issue by ausi** [contao/contao#40]
**Affected version(s)**  
4.4+

**Description**  
The name of the captcha field of a subscribe module is always set to `subscribe`, this makes it impossible to place two different subscribe modules on the same page.

I think we should replace the line https://github.com/contao/contao/blob/25a7e87856e18a32ad8f4576929bed42d978b4b7/newsletter-bundle/src/Resources/contao/modules/ModuleSubscribe.php#L99 with:

```php
'name' => 'subscribe_'.$this->id
```

**Comment by leofeyer** [comment]
Fixed in 438d28772f03ff625efdfc02ef49e348129c2fe8.
