### ISSUE TITLE
Using translator to access different languages at once fails

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#4008]
### Affected version(s)

`>= 4.9`

### Description

We're working on a project where we need the same translation in different languages. We saw that this is a known limitation in 4.9 since the `locale` parameter is ignored for everything Contao related:

https://github.com/contao/contao/blob/20cbb7fa7cd4714649d12de6239ccd0584cba773/core-bundle/src/Translation/Translator.php#L44-L50

But it seems like this could've been fixed in 4.12 since the according comment is missing and the whole loading of language files seems to be reworked:

https://github.com/contao/contao/blob/9e0dceaa6660feddeb36608035ad79cd6e6ba136/core-bundle/src/Translation/Translator.php#L55-L75

Unfortunately right after updating to 4.12 the issue still seems to be the same:

```php
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','de') ); // "In neuem Fenster öffnen"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','en') ); // "Open in new window"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','fr') ); // "Ouvrir dans une nouvelle fenêtre"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','it') ); // "Si apre in una nuova finestra"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','de') ); // "Si apre in una nuova finestra"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','en') ); // "Si apre in una nuova finestra"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','fr') ); // "Si apre in una nuova finestra"
dump( $this->translator->trans('MSC.target.0', [], 'contao_default','it') ); // "Si apre in una nuova finestra"
```

It seems like Contao is still stuck to the language that was loaded in last (which was the problem in <=4.9 due to `$GLOBALS['TL_LANG']` being overwritten only if a new language was loaded).

**Comment by ausi** [comment]
I think we should rework `System::loadLanguageFile()` to check if the last loaded language matches the requested one instead of the current logic in https://github.com/contao/contao/blob/64952eea57830f86ff95928f3810b5e5aac6d169/core-bundle/src/Resources/contao/library/Contao/System.php#L460-L464

**Comment by fritzmg** [comment]
@ausi should be fixed in 4.9 as well imho.

**Comment by ausi** [comment]
> should be fixed in 4.9 as well imho.

Even though our decorated Translator doesn’t support it?

**Comment by fritzmg** [comment]
Presumably the same issue happens in 4.9 if you do 

```php
System::loadLanguageFile('default', 'en'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]);
System::loadLanguageFile('default', 'fr'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]);
System::loadLanguageFile('default', 'it'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]);
System::loadLanguageFile('default', 'de'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]);
```

But I haven't actually tested that.

**Comment by bennyborn** [comment]
> Presumably the same issue happens in 4.9 if you do
> 
> ```
> System::loadLanguageFile('default', 'en'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]);
> System::loadLanguageFile('default', 'fr'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]);
> System::loadLanguageFile('default', 'it'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]);
> System::loadLanguageFile('default', 'de'); dump($GLOBALS['TL_LANG']['MSC']['target'][0]);
> ```
> 
> But I haven't actually tested that.

Tested it, same effect in 4.9.
