### ISSUE TITLE
Add filter flags for VirtualFilesystemInterface::listContents()

### ISSUE THREAD

**Issue by Toflar** [contao/contao#4011]
### Description

Currently we have to manually check for `$fileItem->isFile()` or `->isDir()`. Looks like we could improve that by adding more flags to the `VirtualFileSystemInterface`.

See https://flysystem.thephpleague.com/v2/docs/usage/directory-listings/.

**Comment by m-vo** [comment]
I can think of two possible ways to implement this:

* a new flag `$filesOnly = false` for the `VirtualFilesystemInterface#listContents()` method
* returning a custom iterator that has a method `files()` so that you could do `foreach($storage->listContents(…)->files() as $file) { … }`

**Comment by Toflar** [comment]
Both are okay for me. But it should be consistent then. Either one or the other, not both. So the dbafs flags would also need to become part of the iterator.

**Comment by Toflar** [comment]
Would also like to have @ausi's input here :)

**Comment by m-vo** [comment]
IMHO the iterator would have the benefit to be extendable in the future without breaking anything. And too many optional parameters might get cumbersome. So I'm leaning towards this solution.

**Comment by Toflar** [comment]
Same gut feeling over here 👍

**Comment by m-vo** [comment]
see #4012 for a proposal
