### ISSUE TITLE
input type="number" and minimum Value = 0 is like no minimum value

### ISSUE THREAD

**Issue by MacKP** [contao/contao#4016]
### Affected version(s)

4.9.24 and 4.12.5

### Description

Wenn ich bei einem Number Eingabefeld die 0 als Minimum angebe, dann wird das nicht als Minimum gesetzt. Es ist im Grunde so, als ob die Eingabe leer wäre.
Ergebniss im Frontend: Ich kann da auch minus Zahlen setzen...
Erwarten würde ich die 0 als Minimum ;-)

Viele Grüße

**Comment by ausi** [comment]
May be related to #2307, #2779 or #2778 ?

**Comment by MacKP** [comment]
> May be related to #2307, #2779 or #2778 ?

Ah, yes.. sorry, didn't find this this tickets...
