### ISSUE TITLE
Fallback für "Locale"

### ISSUE THREAD

**Issue by zonky2** [contao/contao#4023]
### Description

Wäre es möglich, einen Fallback für Locale einzubauen?

Aktuell agiert Contao wie folgt:

Wir haben als Beispiel die Seiten mit selbiger Domain und den Sprachen en, de, de-CH und en ist die Fallbacksprache...

Kommt jemand mit de-AT wird dieser zu en (Fallback) geleitet, da kein anderer Startpunkt dafür zuständig ist.

Für viele wäre es sicher "logischer", wenn nach einer Prüfung auf Sprache-Lokalisierung und bei einem "miss-match", anschließend erst auf die reine Sprache (de) geprüft wird - erst wenn das auch nicht zu einem Erfolg führt, gehts zum Sprachen-Fallback.

Voraussetzung wäre entweder ein Startpunkt ohne Lokalisierung oder man könnte definieren welcher Startpunkt für die Sprache der Fallback ist (z. B. wenn es statt de ein de-DE gäbe) .

Für MM haben wir für das BE einen "Sprachenfallback" umgesetzt, d.h. es wird nach de-* erst nach de geprüft und dann auf en gegangen - wäre die Frage, ob man das in Contao auch so für das FE implementieren würde/könnte?

**Comment by ausi** [comment]
Bei den Sprachen `en, de, de-CH` sollte ein Benutzer mit Sprache `de-AT` bereits zu `de` geleitet werden. In welcher Version tritt der Fehler auf?

**Comment by ausi** [comment]
Bitte auch den `Accept-Language` header bekanntgeben den der Browser mitschickt.

**Comment by zonky2** [comment]
habe Infos "angefordert"... => @rleyendecker

**Comment by aschempp** [comment]
Soweit ich weiss wird nicht automatisch nach `de` geleitet, aber jeder normale Browser schickt nicht nur de-AT

**Comment by ausi** [comment]
Genau, so steht es auch explizit im Standard. Ein Browser muss sowas wie `de-AT,de;q=0.9` schicken. (Machen auch alle Browser die ich habe).
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4

**Comment by fritzmg** [comment]
This is already implemented in the current version of Contao. Tested with two website roots, one with language `en` (fallback) and one with language `de`:

```
curl -I --header "Accept-Language: de-AT" http://c413.local
```

Response:

```
Location: http://c413.local/de/
```

Works with and without legacy routing. As far as I remember this has been added around Contao 4.11 or so.

**Comment by aschempp** [comment]
Wenn ich das richtig verstehe, dann wäre das bereits im neusten Contao implementiert und daher "erledigt" 😊

**Comment by ausi** [comment]
I think we should wait on feedback from @zonky2 before closing this.
