### ISSUE TITLE
Allow to display different environments to the back end users

### ISSUE THREAD

**Issue by Toflar** [contao/contao#403]
**Description**  

Very often we use different environments for our customers such as `production`, `staging`, `test`, `demo` etc.
It's true that they are all on separate domains and you *should* be able to tell from the subdomain. However, apparently sometimes customers just don't get it.
What do you think about introducing something like 

```
contao:
    environment: 'foobar'
```

If it's not defined, nothing happens, we just don't show anything at all.

**Example**  

Could look something like this:

<img width="733" alt="Bildschirmfoto 2019-03-18 um 10 42 42" src="https://user-images.githubusercontent.com/481937/54521394-20ac4580-496b-11e9-9a0e-3ea357411220.png">

But maybe someone with actual UI skills has a better idea? 😄

**Comment by m-vo** [comment]
Yeah, maybe we could also add the environment name as css class (to the BE root container). Then you could e.g. colorize the top bar to stand out even more.

**Comment by Toflar** [comment]
That would be easy to do, yep. This whole issue is an easy-pick 😄

**Comment by bezin** [comment]
Sounds good and I feel your customers. Even though the subdomain differs, 99% of what's on the screen looks the same, so even I get confused sometimes when switching between locale dev environment and production. 

+1 to the css class to allow minimal different styling.

**Comment by rabauss** [comment]
i can recommend my extension for that: https://github.com/bwein-net/contao-backend-customizer

but if some settings would become core, would be better for manager-users etc.

a setting for header color in core would also be nice, so you can recognize immediatelly the right client system as agency.

**Comment by hella-schu** [comment]
+1

**Comment by bezin** [comment]
Just to persist two more ideas from [this twitter thread](https://twitter.com/toflar/status/1107579503121977344):

* Also output environment in Preview bar
* Add a class to body element

**Comment by JLBA** [comment]
Hi,
Perhaps there could be default colors environnement if we don't want to reconfigure it for each new project.

**Comment by ben-eSM** [comment]
This would come in very handy. Any chance we'll see it in the 4.9 LTS? :)

**Comment by Toflar** [comment]
It's an easy-pick. PR's welcome :)

**Comment by leofeyer** [comment]
See #1604
