### ISSUE TITLE
Events/Calendar - Recurring event results in HTTP 500 error

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#4037]
### Affected version(s)

4.9, 4.12

### Description

Hi,
there is a big performance problem when you set up a recurring event (one is enough) which has a repeat interval of 1 day with recurrences set to 0

I checked it out in the contao demo. It crashed.

1. Set the module settings of an eventlist - option "Number of events" to 0:
https://demo.contao.org/contao?do=themes&table=tl_module&act=edit&id=20

2. Set the repeat interval to "day(s)", not "year(s):
https://demo.contao.org/contao?do=calendar&id=6&table=tl_calendar_events&act=edit

3. Check it out:
https://demo.contao.org/preview.php/en/events.html

**Possible solution:** 
The recurrences should not allow 0 or a value bigger than 10000 (or another meaningfull value). It really makes no sense to have events which repeats more than 10000 times. That would mean, that you have an even which is every day over 30 years 😮 
Or a 200 year event which is every week 😆 

I think already 999 repeats are enough... 

If users need more than 999 repeats, they can set the maxlength or maxval value higher in the dcaconfig.

$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['recurrences']['eval']['minval'] = 1;
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['recurrences']['eval']['maxval'] = 999;

**Comment by leofeyer** [comment]
As discussed in the Contao call, if

* an event list is set to show all future events and
* there are repeated events without limit,

we could show these unlimited events only once to prevent infinite repetitions. However, this is primarily a configuration error, because you have configured both the event and the event list with unlimited recurrences.
