### ISSUE TITLE
Use CsrfTokenManager::randomize() everywhere

### ISSUE THREAD

**Issue by ausi** [contao/contao#4038]
### Affected version(s)

4.12 (maybe 4.9 too)

### Description

In https://github.com/symfony/symfony/commit/8b01095933e5073688b9bde2842974f33cc88412 something was changed for generating the CSRF tokens. They get randomized now and have a different format.

We have to change https://github.com/contao/contao/blob/64952eea57830f86ff95928f3810b5e5aac6d169/core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php#L111 to not use the token storage but the manager instead.

I’m not sure if we can update https://github.com/contao/contao/blob/64952eea57830f86ff95928f3810b5e5aac6d169/core-bundle/src/EventListener/CsrfTokenCookieSubscriber.php#L127 too or if we can get rid of the removal of the (unused) token.

**Comment by ausi** [comment]
Closed in favor of #4045

**Comment by bytehead** [comment]
@ausi is there any way to check if 4.9 is affected?

**Comment by ausi** [comment]
Contao 4.9 schould not be affected as this was not changed in Symfony 4.4.

**Comment by bytehead** [comment]
Contao 4.9 can be installed with Symfony 5.* components afaik...

**Comment by fritzmg** [comment]
Indeed, in Contao 4.9 we are not specifically requiring `symfony/security-csrf`, only `symfony/security-bundle`. May be https://github.com/contao/contao/pull/3972 should be backported to 4.9?

**Comment by fritzmg** [comment]
`symfony/security-bundle` allows `symfony/security-csrf` in version 4.x _and_ 5.x.
