### ISSUE TITLE
Colorpicker in BE overlaps Buttons

### ISSUE THREAD

**Issue by tme55** [contao/contao#4039]
### Affected version(s)

4.13.0-RC1

### Description

The buttons in the backend are flashing thru the  buildin-colorpicker (mooRainbow):

![grafik](https://user-images.githubusercontent.com/13655473/152000545-1330b9cf-4857-4c75-a371-e51735db4fbf.png)

how to reproduce:
add Customfield e.g. in tl_page
```
$GLOBALS['TL_DCA']['tl_page']['fields']['themecolors_color-default'] = array
(
    'label' => &$GLOBALS['TL_LANG']['tl_page']['themecolors_color-default'],
    'inputType'             => 'text',
    'eval'                  => ['maxlength'=>6, 'multiple'=>false, 'size'=>2, 'colorpicker'=>true, 'isHexColor'=>true, 'decodeEntities'=>true, 'tl_class'=>'w50 wizard'],
    'sql'                   => "varchar(64) NOT NULL default ''"
);
```

**Comment by leofeyer** [comment]
Fixed in version 1.5.2 (see https://github.com/contao-components/colorpicker/commit/ce0732ff1d0bd952a3642fd639e3d6a93bd08c94).
