### ISSUE TITLE
Steps to get rid of the installation bundle (possibly)

### ISSUE THREAD

**Issue by m-vo** [contao/contao#404]
The installation bundle's concerns are somewhat overlapping with the core and the manager. I'd like to see if we could get rid of it and - while doing so - improve on some things. To be clear, there are quite a few things to it and I'd like to hear what you think about it.

## InstallationBundle
Currently the installation bundle does/allows the following (Am I missing something?):
1. Set password / log in
1. Dialog to accept the licence / write config
1. Dialog to enter db credentials / write `parameters.yml`, purge cache
1. Run contao version migrations (non interactive)
1. Update the database (interactive)
1. Create a backend user 
1. Import a theme
1. Run `assets:install`, `contao:install`, `contao:symlinks` (non interactive)

Here are some ideas for the _database related_ things: from that list:

### (3.) Dialog to enter db credentials / write `parameters.yml`, purge cache
This should IMO go into the manager. People not using the manager can still enter the credentials on their own. (There still is the [secret](https://github.com/contao/installation-bundle/blob/master/src/Config/ParameterDumper.php#L73) that is generated). To ease things we could create a command (in the core) that could also be accessed by the manager via a ``json`` option.

Proposal:
 - move ``ParameterDumper`` into a command (``CoreBundle``)
 - use the command in the installation bundle
 - later: implement the feature in the manager
 - even later: drop it from the installation bundle (or the whole bundle alltogether)

### (4.) Run contao version migrations (non interactive)
There are [some](https://github.com/contao/installation-bundle/issues/50) [related](https://github.com/contao/installation-bundle/issues/96) [issues](https://github.com/contao/core-bundle/issues/1223) already. One benefit of reworking this part would be to open up migrations to 3rd party code. We once disucssed this in a mumble call and came up with an interface definition like [this](https://github.com/contao/core-bundle/issues/1223#issuecomment-425128629):

```PHP
interface ContaoMigration
{
    public function shouldBeRun(): bool {}
    public function getDescription(): string {}
    public function run(): void {} // can be called multiple times
    public function getRunAfter(): array {} // specify classes to run after
}
```

To get this going we could:
- create a command to trigger contao migrations (``CoreBundle``); commands can be registered by tagging a class that's implementing the interface 
- use the same mechanism for the core's migrations (`VersionXXXUpdate`)
- trigger the command from the installation bundle

### (5.) Update the database (interactive)
Same like the first one. This should probably go into the manager. But here the challenge would be to allow the same functionality without a UI. Ideally a git like `-i` interaction would IMO be perfect - maybe there are ways to get close to that. Or at least allowing the user to group commands by something... Again a ``json`` option could make this accessible for the manager (identifiying single operations by a hash). 

Proposal:
 - evaluate ways to interactively select operations via the CLI
 - create a interactive command to run the migrations
 - use the command in the installation bundle
 - later: implement the feature in the manager
 - even later: drop it from the installation bundle (or the whole bundle alltogether)

-----------

Probably easiest (with most benefit) would be **4.**. But before I create a PR for that we should discuss if those things are any good anyways. 😄

**Comment by aschempp** [comment]
@m-vo I'd like to keep this open because it's a good summary what needs to be implemented in different places (mostly the Manager) 😊

**Comment by m-vo** [comment]
See #4935
