### ISSUE TITLE
Restore View can overflow

### ISSUE THREAD

**Issue by rorych** [contao/contao#4047]
### Affected version(s)

4.13.0-RC1

### Description

In the restore list-view of deleted items, if a large image has been deleted (1920+ px) the table overflows on the right side:
<img width="1560" alt="backend" src="https://user-images.githubusercontent.com/2022054/152133307-be45c813-6133-407b-991b-91669223ee6e.png">

Max-width on the image would solve the problem, not shure if this would make sense in the complete backend?

`.tl_undo_preview img {
	max-width: 100%;
}`

or 

`img {
	max-width: 100%;
}`

**Comment by leofeyer** [comment]
@bezin /cc

**Comment by m-vo** [comment]
see #4057
