### ISSUE TITLE
Problematic order of optional constructor parameters in AsContentElement/AsFrontendModule

### ISSUE THREAD

**Issue by m-vo** [contao/contao#4055]
### Affected version(s)

4.13

### Description

Our `AsContentElement` attribute currently looks like this:

https://github.com/contao/contao/blob/3691e1d7f9ee4eb35a9f5e05a3537dc633f94ffc/core-bundle/src/DependencyInjection/Attribute/AsContentElement.php#L23

Having the first non-optional parameter at the second place forces you to define at least two parameters (https://3v4l.org/Y7N4G#v8.1.2), but with the content element attribute, you typically only define the `category`, which then results in:

```
Contao\CoreBundle\DependencyInjection\Attribute\AsContentElement::__construct(): Argument #1 ($type) not passed
```

(Similar reasoning for `AsFrontendModule`.)

@aschempp What's the reason for this unusual order? Can we change this?

**Comment by m-vo** [comment]
I found a discussion about this very topic https://github.com/contao/contao/pull/3619#discussion_r747652799. But I don't agree with the outcome. :slightly_smiling_face:

**Comment by aschempp** [comment]
This is not a bug. As mentioned in the comment, this is intentional and makes sense to be consistent with annotations. Always use named parameters with (our) attributes.

**Comment by m-vo** [comment]
It does not work, though, even with named parameters unless you pass in at least two. So this is clearly a bug.

**Comment by aschempp** [comment]
What _does not work_?

**Comment by m-vo** [comment]
Did you read anything of what I wrote? You cannot construct the object with a single parameter, no matter if named or not.

> Having the first non-optional parameter at the second place forces you to define at least two parameters (https://3v4l.org/Y7N4G#v8.1.2), but with the content element attribute, you typically only define the category, which then results in:

**Comment by m-vo** [comment]
Just so that we are on the same page:

![image](https://user-images.githubusercontent.com/5305677/152334742-174500fe-fe52-4443-ac98-34aede50d921.png)

=

![image](https://user-images.githubusercontent.com/5305677/152334778-b6e5801e-29b8-4bbd-a175-c0df72de8101.png)

**Comment by fritzmg** [comment]
I agree that this needs to be fixed. Only having to define the category and nothing else should be the minimum for the `AsContentElement` attribute, just as it is already the case with the `ContentElement` annotation.

**Comment by ausi** [comment]
Can this be fixed by making category optional like 
`public function __construct(string $type = null, string $category = null, …` 
and throw an `InvalidArgumentException` if `$category` is null? 

Or use an actual default value like `string $category = 'texts'` instead?

**Comment by m-vo** [comment]
> Can this be fixed by making category optional like
public function __construct(string $type = null, string $category = null, …
and throw an InvalidArgumentException if $category is null?

Yes, this would work. https://3v4l.org/TArPo#v8.1.2

But we could IMHO also just change the order - especially, if you should use named arguments anyways.

**Comment by ausi** [comment]
As this parameter order was not released as stable yet, I agree we should change the order.

**Comment by m-vo** [comment]
By the way, having optional parameters before mandatory ones is deprecated since PHP8.0: https://php.watch/versions/8.0/deprecate-required-param-after-optional

**Comment by m-vo** [comment]
see #4065
