### ISSUE TITLE
Cache is not cleared after TTL-time

### ISSUE THREAD

**Issue by dalley-it** [contao/contao#406]
**Affected version(s)**
4.4.18 - 4.4.35

**Description**  
It seems that some pages cached in http_cache (i have just examined files in folder 'en') are not deleted, even when they are older than the TTL-time that was given in website root.

By this the cache grows permanently. In huge installation with many sites to cache this can be problematic, as we have experienced. We ran into a disk space error caused by a 30GB+ cache.

**How to reproduce**  
1. Enable serverside cache in website root.
2. Set server-cache time to i.e. 6 hours (this is what i have tested with).
3. Examin cache entries after cache time has elapsed.

Several entries are still in the cache although they have been created more than 6 hours ago. This has nothing to do with issue #231, as i first thought. You can also find entries that are not 404-pages, but older than the TTL.

**Comment by Toflar** [comment]
This is the default behaviour of the built-in Symfony HttpCache.
We've switched to an alternative cache implementation in Contao 4.6.
In theory I guess it would be possible to backport these changes but we would introduce a new dependency in a bugfix release which is not usually something you do.

**Comment by dalley-it** [comment]
So if want to stay with the LTS we need to clear the cache manually or by a cronjob until 4.9 is released, right?

**Comment by Toflar** [comment]
Yes. You can also backport the changes in your local Contao 4.4 but it will be replaced with every update so I only consider this a good idea if you put your whole project under version control and are not using the Contao Manager and the like.
@contao/developers I don't know why we did not include it in Contao 4.4. Imho it should be fairly simple (it's adding my store implementation plus https://github.com/contao/contao/blob/master/manager-bundle/src/HttpKernel/ContaoCache.php#L78). Technically it could also be considered a bug.

**Comment by dalley-it** [comment]
> Technically it could also be considered a bug

Practically it is a bug as well. When we first ran into this problem (after Update to 4.4) the disk full error caused mysql to die and we had the page offline (meaning the GAU situation).

**Comment by Toflar** [comment]
Yes. But still, that's the default behaviour and if fixing it means too much new code which potentially breaks other stuff then we rather live with it.

**Comment by dalley-it** [comment]
Yes i understand. However if your implementation could be included to a newer 4.4.x, as you suggested before, it would be highly appreciated. Thank you very much.

**Comment by ngdot** [comment]
In my opinion, this bug should also be fixed in the 4 LTS! We have the same problem with a Contao 4 LTS installation with 3 major websites. It is also unfortunate that you always have to clear the cache for all pages, especially when working with multidomains or multiple websites in one installation. Partly I'm not be able to see the "System maintenance" because the calculation of the cache files takes so long, is that possible? Or is the problem somewhere else?

**Comment by aschempp** [comment]
A much easier solution than implementing @Toflar's store implementation would be to run a nightly/weekly/monthly `cache:clear` cron job or even an `rm -rf /var/cache/http_cache`

**Comment by leofeyer** [comment]
As discussed in Mumble on May 9th, we want to try to backport the changes.

**Comment by leofeyer** [comment]
@Toflar I have to backport d5c8305900b5c02a53f379da17e3d9a7da7f44ba, don't I?

**Comment by Toflar** [comment]
Not exactly all of it. The purge listeners are irrelevant because there's no cache tagging in Contao 4.4.
Also, I would not add `http_cache` there in the directory structure. I'd wait for end of May and Symfony 4.3 anyway, you could then rely on my version 2 of the store directly. That would simplify things I think.

**Comment by leofeyer** [comment]
I don't think we can drop Symfony 3.4 compatibility for Contao 4.4 in a bugfix release though.

**Comment by Toflar** [comment]
Nobody was talking about dropping compatibility. It will be compatbile with 3.4.

**Comment by leofeyer** [comment]
I see. You mentioned Symfony 4.3, so I figured version 2 of your store would only be compatible with that. My bad. 😄

**Comment by Toflar** [comment]
No, I just want to change the default directory path which is why I'm going to release v2 😄

**Comment by Toflar** [comment]
v2 has been released, you're cleared to go (make sure to configure the `composer.json` to `         "toflar/psr6-symfony-http-cache-store": "^2.0"` which is the only thing that needs to be merged upstream).

**Comment by leofeyer** [comment]
Backported in e6b8d1475f20951b7b98b9387ef0eebb73425628.
