### ISSUE TITLE
Contao 4.9 - Remove the Google web fonts field from the page layout

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#4062]
### Description

Regarding this issue: https://github.com/contao/contao/pull/2431

From now on it is unlawful to continue using dynamically Google Fonts. Please remove this setting as far as you can also in Contao 4.9 LTS, not only in >= 4.11 
It is dangerous if backend user fill in the field in the layout form.

I know that this is against the Contao update policy, but it is a very special situation if the disadvantages (costs & cease and desist letters) massively outweigh against the risk of not displaying the correct fonts temporarily.
Everybody could integrate it with the local variant.

I wrote a blog article about the legal problems:
https://www.fast-media.net/de/blog/thema/dynamische-einbindung-von-google-fonts-rechtswidrig/

Source: 
https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/

**Comment by aschempp** [comment]
It is unlawful in _some_ european countries. That does not mean it cannot be used worldwide, and we sure cannot remove it in a patch release. It has already been removed in Contao 4.11 (see https://github.com/contao/contao/pull/2431)
