### ISSUE TITLE
High memory consumption with new nikic/php-parser implementation 

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#4069]
### Affected version(s)

4.9.25

### Description

The new PHP parser implementation based on `nikic/php-parser` that was recently backported to Contao 4.9.25 in https://github.com/contao/contao/pull/4031 causes a much higher memory consumption than the previous implementation based on `phpunit/token-stream`. This scales with the amount of DCA, config and PHP language files that have to be parsed. In one instance on the community forum the usage was bursting through the `128M` `memory_limit` that they happened to have.

In my Contao 4.9 dev instance the _peak_ memory consumption delta (peak memory after minus peak memory before) after `ContaoCacheWarmer::generateConfigCache`, `generateDcaCache` & `generateLanguageCache` is about **8 MiB** in Contao 4.9.24 and about **45 MiB** in Contao 4.9.25.

In the Contao 4.9.25 instance of the community forum user the memory consumption jumps from **40 MiB** to **104 MiB**. Most of it caused by `generateDcaCache` and `generateLanguageCache`.

**Comment by Toflar** [comment]
Can you test how https://github.com/contao/contao/pull/4072 affects your setup?

**Comment by fritzmg** [comment]
I tested the peak memory consumption during `cache:warmup --env=prod` in the Contao instance from the community forum thread:

| Version | Consumption |
| --- | ---:|
| Contao 4.9.24 | 72.05 MiB |
| Contao 4.9.25 | 140.40 MiB |
| #4072 | 79.67 MiB |

👍
