### ISSUE TITLE
FormCheckbox::validate() breaks with inputCallback

### ISSUE THREAD

**Issue by discordier** [contao/contao#407]
**Affected version(s)**
All

**Description**  
in [FormCheckbox](https://github.com/contao/contao/blob/037df49e9fdc1445e7abb316f16493e2bce17ca6/core-bundle/src/Resources/contao/forms/FormCheckBox.php#L140) there is a check if the global `$_POST` is empty.
https://github.com/contao/contao/blob/037df49e9fdc1445e7abb316f16493e2bce17ca6/core-bundle/src/Resources/contao/forms/FormCheckBox.php#L140-L143

As I am 'submitting' form fields via `Widget::inputCallback`, the said array naturally is empty.

I wonder why this test is there at all, as it should never be needed I guess?

**How to reproduce**  
```
// .... build a FormCheckbox() somehow that accepts value 'a' and 'b'.
$widget->setInputCallback(function () use ($value) {
    return ['a', 'b'];
});
$widget->validate();

$value = $widget->value;
// Expected: ['a', 'b']
// Actual: ''
```

**Comment by zonky2** [comment]
important issue!

**Comment by leofeyer** [comment]
> I wonder why this test is there at all

I assume it has to do with multi-page forms. `Widget::getPost()` uses `Input::findPost()` and the latter loads the value from `$_SESSION['FORM_DATA']` if it exists there and does not exist in `$_POST`. However, I do not recall why the value needs to be unset; it seems the code snippet has been in there since TYPOlight 2.

@contao/developers What do we do about this? Shall I remove the code snippet entirely or shall I add an `!\is_callable($this->inputCallback)` check?

**Comment by Toflar** [comment]
I don't know what this check is supposed to do there.

**Comment by aschempp** [comment]
I can't reason for it either, I'd propose to just remove it…

**Comment by leofeyer** [comment]
I vaguely remember that we have changed the checkbox markup a long time ago:

```html
<!--
  OLD: no default value, $_POST['foo'] will only be set
  if the checkbox has been enabled
-->
<input type="checkbox" name="foo" value="bar">

<!--
  NEW: $_POST['foo'] will be set to the default value if
  the checkbox has not been enabled
-->
<input type="hidden" name="foo" value=""><input type="checkbox" name="foo" value="bar">
```

I think the code snippet was used to set the default value if the checkbox had not been enabled, therefore we should have removed it when we changed the markup.

So it should be save to remove it now. I guess. 😄

**Comment by leofeyer** [comment]
Removed in 799b65cfec4eb8d689833ce470a6b15e32ac8b56.

**Comment by zonky2** [comment]
thx
