### ISSUE TITLE
BC break with protected $Template property

### ISSUE THREAD

**Issue by bytehead** [contao/contao#4086]
### Affected version(s)

4.9.26

### Description

The fix from #4075 has still a BC break in `PageRegular`:

<img width="1052" alt="Bildschirmfoto 2022-02-08 um 14 14 25" src="https://user-images.githubusercontent.com/754921/152994983-02cad099-654e-4b28-a42f-9d20d26766f4.png">

**Comment by fritzmg** [comment]
Yes, we still need to decide whether accessing ->Template of PageRegular publicly should be allowed or not. In the past it was allowed, but probably an oversight. However, even if it was not intentional, the current state is inconsistent. `Module` and `ContentElement` allow you to publicly access the `Template` property. `PageRegular` and `BackendMain` do not.

**Comment by m-vo** [comment]
Can we allow it in 4.13 and ultimately drop it everywhere in 5.0?

**Comment by bytehead** [comment]
Before 4.9.24 you could actually access `Template` in `PageRegular` therefore we cannot change this in 4.x IMO.

**Comment by bytehead** [comment]
Or how would you add some properties to the page template?

**Comment by fritzmg** [comment]
> Or how would you add some properties to the page template?

I would do it via the `parseTemplate` hook.

**Comment by ausi** [comment]
Can we make it a public member in Contao 4.9/4.13 and private in Contao 5.0?

**Comment by leofeyer** [comment]
Huh? I don‘t understand. I have merged [the original fix](https://github.com/contao/contao/pull/3725/commits/0b8f74d20d7c0be93478183f7e27fb891674a25f), so why is this breaking now?

**Comment by bytehead** [comment]
Then [this](https://github.com/contao/contao/pull/3725/commits/0b8f74d20d7c0be93478183f7e27fb891674a25f) was also a BC break then.

**Comment by bytehead** [comment]
> Can we make it a public member in Contao 4.9/4.13 and private in Contao 5.0?

Like discussed already: https://github.com/contao/contao/issues/3894#issuecomment-1006420275 😅

**Comment by aschempp** [comment]
jup, it must be public. Or probably just not be set at all. I noticed that too while reading the PR 😂

**Comment by bytehead** [comment]
Did you also read your comment [here](https://github.com/contao/contao/issues/3894#issuecomment-1006450035)? 😬

**Comment by bytehead** [comment]
I'm in for making it public, I doubt that people made the property protected or private by themself. But otherwise, why not leave it as it was and don't set it at all until 5.0? 🤷‍♂️

**Comment by leofeyer** [comment]
Creating dynamic properties is deprecated as of PHP 8.2, which is why this issue came up in the first place.

https://github.com/contao/contao/runs/4498623325?check_suite_focus=true

**Comment by bytehead** [comment]
True, I've already missed that again. So making it public would be the only (futureproof) way.

**Comment by aschempp** [comment]
How about adding a `__get()` method that return the template object? This would work in any case. If a developer did make it `public` in a child class that property would be accessed, and in any other case our `__get()` method would be called?

**Comment by fritzmg** [comment]
You mean: leave everything as it was before (i.e. reverting #4075 again 🙈) and only implement `__get` for `Template` for `PageRegular`? (May be also `BackendMain`)

**Comment by fritzmg** [comment]
There is another issue. We cannot revert #4075 because there are actually extensions who directly access `$this->arrData['Template']`: https://github.com/DERHAEUPTLING/contao-lazy-images/blob/9edd71b3e8d632ad2ad66329c519a8b3a9e0686a/elements/LazyContentImage.php#L26

**Comment by m-vo** [comment]
> Creating dynamic properties is deprecated as of PHP 8.2, which is why this issue came up in the first place.

If we cannot guarantee BC otherwise, we could add `#[AllowDynamicProperties]` in this special case I think.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we do want to add `#[AllowDynamicProperties]`.

**Comment by ausi** [comment]
And use a protected property in Contao 5.0 and remove `#[AllowDynamicProperties]` then.
