### ISSUE TITLE
URL sufix has input on the new feature introduced in #3843

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#4087]
### Affected version(s)

4.13.0-RC2

### Description

Example: The page "News" has the alias `news` and lists all available news items. The page "News-Reader" also has the alias `news` and the option "Require an item" plus shows the detail view of a news item.

If the URL suffix is set to ´/` opening news/foobar/ doesn't show detail view but a page not found.

https://github.com/contao/contao/pull/3843

**Comment by fritzmg** [comment]
So does that mean you were able to create two distinct pages with the same alias (i.e. `news`)?

**Comment by netzarbeiter** [comment]
yes, and it is working with no URL suffix or `.html`

![Bildschirmfoto 2022-02-08 um 16 35 26](https://user-images.githubusercontent.com/1942550/153020793-e614c3b2-2a34-4709-9090-390f4a93afc5.png)

**Comment by aschempp** [comment]
> So does that mean you were able to create two distinct pages with the same alias (i.e. `news`)?

thats a new feature in Contao 4.13 😉

**Comment by aschempp** [comment]
duplicate of https://github.com/contao/contao/issues/3531 😬

**Comment by aschempp** [comment]
https://github.com/contao/contao/pull/4106 should fix this

**Comment by netzarbeiter** [comment]
I have added the fix in **Contao 4.13.0-rc2**.

Replaced the following **line 69** `vendor/contao/core-bundle/src/Routing/Page/PageRegistry.php`:

`$requirements['parameters'] = $pageModel->requireItem ? '/.+' : '(/.+?)?';`

by

`$requirements['parameters'] = $pageModel->requireItem ? '/.+?' : '(/.+?)?';`

And cleared the cache:

```bash
php vendor/bin/contao-console cache:clear --env=prod --no-warmup
php vendor/bin/contao-console cache:warmup --env=prod
```


Now I get a "Page not found" with all suffixes ".html", "/" and "".

Before the "Page not found" only showed up with the suffix "/".

**Comment by leofeyer** [comment]
I have tried to reproduce but it works on my system. Both pages have the alias `news` and the URL suffix is set to `/`. Did you clear the cache after adjusting the file?

**Comment by aschempp** [comment]
it has been fixed by https://github.com/contao/contao/pull/4106 😆
