### ISSUE TITLE
Systemwartung -> Vorschau-Cache leeren => Fehler in server error.log

### ISSUE THREAD

**Issue by jochi44** [contao/contao#4089]
### Affected version(s)

4.13.0-RC2

### Description

Die Ausführung der Funktion Systemwartung -> Vorschau-Cache leeren führt zu folgendem Fehler im error.log des Servers:

`2022/02/08 22:03:24 [error] 11108#11108: *20787 FastCGI sent in stderr: "PHP message: PHP Warning:  scandir(/var/www/client/web/assets/previews/): failed to open dir: No such file or directory in /var/www/client/web/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Folder.php on line 588PHP message: PHP Warning:  scandir(): (errno 2): No such file or directory in /var/www/client/web/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Folder.php on line 588PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/client/web/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Folder.php on line 588" while reading response header from upstream, client: 1.1.1.1, server: abc.tld, request: "POST /contao?do=maintenance&ref=Bm8E_5at HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php5-fpm/web50.sock:", host: "abc.tld", referrer: "https://abc.tld"`

**Comment by bytehead** [comment]
This will likely be fixed by #4078.

**Comment by mlwebworker** [comment]
Ich kann den Fehler bestätigen.
Contao 4.13 RC2
XAMPP mit PHP 7.4.27
Windows 10

Falls es noch wichtig bzw. von Interesse ist hier der Stack Trace
`ErrorException:
Warning: scandir(F:\public_html\test/assets/previews/): Das System kann die angegebene Datei nicht finden. (code: 2)

  at F:\public_html\test\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Folder.php:588
  at Contao\Folder::scan('F:\\public_html\\test/assets/previews/')
     (F:\public_html\test\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Automator.php:139)
  at Contao\Automator->purgePreviewCache()
     (F:\public_html\test\vendor\contao\core-bundle\src\Resources\contao\classes\PurgeData.php:58)
  at Contao\PurgeData->run()
     (F:\public_html\test\vendor\contao\core-bundle\src\Resources\contao\modules\ModuleMaintenance.php:49)
  at Contao\ModuleMaintenance->compile()
     (F:\public_html\test\vendor\contao\core-bundle\src\Resources\contao\classes\BackendModule.php:82)
  at Contao\BackendModule->generate()
     (F:\public_html\test\vendor\contao\core-bundle\src\Resources\contao\classes\Backend.php:440)
  at Contao\Backend->getBackendModule('maintenance', null)
     (F:\public_html\test\vendor\contao\core-bundle\src\Resources\contao\controllers\BackendMain.php:170)
  at Contao\BackendMain->run()
     (F:\public_html\test\vendor\contao\core-bundle\src\Controller\BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (F:\public_html\test\vendor\symfony\http-kernel\HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (F:\public_html\test\vendor\symfony\http-kernel\HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (F:\public_html\test\vendor\symfony\http-kernel\Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (F:\public_html\test\web\index.php:44)  `

**Comment by leofeyer** [comment]
@ausi Should we add `assets/previews` here?

https://github.com/contao/contao/blob/99a73db0e70731dda59f74d471cb0bf8e3f82e10/core-bundle/src/Command/InstallCommand.php#L82-L94

**Comment by ausi** [comment]
No, not necessary IMO
