### ISSUE TITLE
Probleme in Contao 4.12.6 mit  Systemwartung Crawler Suchindex aktualisieren

### ISSUE THREAD

**Issue by TS16V** [contao/contao#4092]
### Affected version(s)

4.12.6

### Description

Hi,

habe das Problem, daß der Suchindex nicht aufgebaut wird.
Siehe Problembeschreibung hier: 

(https://community.contao.org/de/showthread.php?82449-Nach-Update-4-12-6-h%C3%A4ngt-Suchindex-aktualisieren&p=554558&viewfull=1#post554558)

Kann es sich um ein BUG handeln?

**Comment by aschempp** [comment]
from the forum post, maybe @Toflar or @ausi know more about this:

```
An exception occurred while executing 'SELECT uri, level, processed, found_on, tags FROM tl_crawl_queue WHERE (job_id = ?) AND (uri_hash = ?) LIMIT 1' with params ["7eb2e0c8-7dc7-4c8c-92cf-44d43bab2822", "e3c5715516145fd20d1325cfb104b2befbd8cae9"]:
SQLSTATE[HY000]: General error: 1100 Table 'tl_crawl_queue' was not locked with LOCK TABLES at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128

**Comment by Toflar** [comment]
The error message doesn't really help much because what it means is that **a different table** was locked before and no `UNLOCK TABLES` query was executed. It might have also been an extension that caused that bug.

If we don't get a description on how we can reproduce this bug, we have to close it.

**Comment by contaoacademy** [comment]
Hatte Kontakt mit TS16V. Das Problem, dass der Index nicht aufgebaut wurde, scheint nun behoben. Es war ein zu langer Titel bei einem Seitentitel hinterlegt. Denke, das Ticket kann erst mal geschlossen werden.

**Comment by contaoacademy** [comment]
see #4260
