### ISSUE TITLE
MessageCatalogue::isContaoDomain() leads to issues

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#4097]
### Affected version(s)

4.13

### Description

The current implementation of

https://github.com/contao/contao/blob/376f630438f39b9d22737bb7c7c36b74a83e336f/core-bundle/src/Translation/MessageCatalogue.php#L146

in 4.13 leads to:

`Argument 1 passed to Contao\CoreBundle\Translation\MessageCatalogue::isContaoDomain() must be of the type string, null given`

if called like

```
$translator = System::getContainer()->get('translator');

$catalog = $translator->getCatalogue();
$all = $catalog->all();
```

A fix would be:

```
private function isContaoDomain($domain = null): bool
{
    return $domain !== null && 0 === strncmp($domain, 'contao_', 7);
}
```

**Comment by ausi** [comment]
Or something like this:

```php
private function isContaoDomain(?string $domain): bool
{
    return 0 === strncmp($domain ?? '', 'contao_', 7);
}
```

☺️
