### ISSUE TITLE
Cannot delete files

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#4098]
### Affected version(s)

4.13.0-RC2

### Description

When deleting a file, the following exception is thrown: 

`Contao\CoreBundle\EventListener\DataContainer\RecordPreviewListener::storePrecompiledRecordPreview(): Argument #1 ($dc) must be of type Contao\DataContainer, string given`

<img width="1072" alt="" src="https://user-images.githubusercontent.com/1192057/153400433-05953f18-e038-4be1-bb8a-57cccb7451b0.png">

@bezin /cc

**Comment by bezin** [comment]
I can confirm this and I'll take care

**Comment by bezin** [comment]
DC_Table and DC_Folder pass different arguments to the `ondelete_callback`: 

[DC_Table passes a data container instance and the id of the undo row](https://github.com/contao/contao/blob/6d8af7b525f85e790b9edb2b6627354f70019040/core-bundle/src/Resources/contao/drivers/DC_Table.php#L1506)
[DC_Folder passes the path to the deleted file and the data container instance](https://github.com/contao/contao/blob/6d8af7b525f85e790b9edb2b6627354f70019040/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L1014)

We could not add the preview callback to all tables with `DC_Folder`, as restoring data is not possible anyways. However, I don't know what custom DC drivers are out there in the wild. DC General should not be an issue as far as I understood the code.

**Comment by zoglo** [comment]
Having another issue #4125 close to the one above.
Already posted in Slack
