### ISSUE TITLE
Preview links should auto-update "Valid until"

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#4100]
### Affected version(s)

4.13-RC2

### Description

When I create a new link and change the days for the expiration in the select field, the `valid until field` is not updated dynamically. It only would be updated, when I click on "save".

Is this how it should be?
Can this be made more user-friendly?
![screen-20220210_i6tUE6zn](https://user-images.githubusercontent.com/23719181/153440670-281539a5-f894-4062-bf18-7c36b07d3464.png)

**Comment by ausi** [comment]
We should use `submitOnChange` for the dropdown I think ☺️
