### ISSUE TITLE
Preview links cannot be copied to the clipboard

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#4102]
### Affected version(s)

4.13-RC2

### Description

When I click on the icon to copy the preview link to the clipboard, it does not work.
The following JavaScript error appears in the console

`Uncaught TypeError: navigator.clipboard is undefined
    onclick http://cto413.local/contao?do=preview_link&ref=6e93ujZE:1
[contao:1:1](http://cto413.local/contao?do=preview_link&ref=6e93ujZE)
    onclick http://cto413.local/contao?do=preview_link&ref=6e93ujZE:1`

**Comment by Toflar** [comment]
Browser info, please :)

**Comment by contaoacademy** [comment]
- Firefox: 97.0 (64-Bit)
- Brave: Chromium: 98.0.4758.87

**Comment by leofeyer** [comment]
Duplicate of #4007
