### ISSUE TITLE
Index Seite ohne URL-Präfix mit Sprach-Definition ist nicht erreichbar

### ISSUE THREAD

**Issue by Ainschy** [contao/contao#4104]
### Affected version(s)

4.13.0 RC-2

### Description

zwei Seitenbäume gleiche Domain:
Beide Startseiten haben `index` als Alias eingetragen.

1. Startpunkt URL-Präfix: EN; Sprache EN, Sprachen-Fallback
2. Startpunkt ohne URL-Präfix; Sprache NL

Die Startseite der 2. Seite `/index` lässt sich nicht aufrufen. Eine Umleitung `302` erfolgt auf `/en/index`. Weder im Preview noch mit einem Browser ohne NL Sprache lässt sich die index Seite des 2. Seitenbaums aufrufen.

**Comment by aschempp** [comment]
aus meiner Sicht kann die Seite in dieser Konstellation nur aufgerufen werden, wenn dein Browser auch `NL` bevorzugt?

**Comment by aschempp** [comment]
Alternativ könntest du versuchen, bei der englischen Root-Seite die Option _Sprachweiterleitung deaktivieren_ zu aktivieren.

**Comment by Ainschy** [comment]
Leider bringt das Aktiveren der Option nicht den gewünschten Erfolg. Damit "fäng" der englische Seitenbaum nicht mehr die Anfragen eines z.B. deutschsprachigen Nutzers. 

Die NL Startseite (mit dem index Alias) kann ich aus dem Backend über die Vorschau nicht aufrufen um mir diese anzuschauen und ggf. mittels Frontend-Editor zu bearbeiten.

Auch die Change-Language Erweiterung "funktioniert" in diesem Setup nicht.

**Comment by aschempp** [comment]
should be fixed by https://github.com/contao/contao/pull/4717
