### ISSUE TITLE
Create ContentElement or ModuleElement from "faked" model

### ISSUE THREAD

**Issue by michb** [contao/contao#4108]
### Affected version(s)

4.9.12

### Description

Sometimes we need or use the capability to render "fake" Content Elements / Frontend Modules.

For example our custom element / module will reuse the `ContentText` and `ContentDownloads` element to combine it into something new. This way we can also make use of the existing stylings and be more update safe.

For a "fake" Content Element we will create a new `ContentModel`, set the necessary fields and render it:

```php
$oModel = new ContentModel();
$oModel->type = 'image';
$oModel->singleSRC = $some->uuid;
$oModel->fullsize = 1;
...

$oElement = new ContentImage($oModel);

$template->image_element = $oElement->generate();
```

With all the "legacy" core elements this is not a problem so far. But as we transition to the newer Content Element Controller we noticed this is no longer possible.

We expected to see the same behaviour with the `ContentProxy` so we built up the `ContentModel` like above and go on like before:

```php
$oModel = new ContentModel();
$oModel->type = 'somethingawesome';
$oModel->customStuff = 'whatever';
...

$oElement = new ContentProxy($oModel);

$template->awesome_element = $oElement->generate();
```
But this will lead to the following error: `Could not resolve argument $model of "contao.fragment._contao.content_element.somethingawesome()", maybe you forgot to register the controller as a service or missed tagging it with the "controller.service_arguments"?`, on Contao 4.12.

Also setting a "fake" `id` in the `ContentModel` will not help.

From what I understand the problem lies in the way the `ContentProxy` stores and gets its reference.
https://github.com/contao/contao/blob/56e6e3b31bb4450842b4557122752b94fcf12fc4/core-bundle/src/Resources/contao/elements/ContentProxy.php#L31
The `ContentProxy` stores a reference using `ContentElementReference`
https://github.com/contao/contao/blob/56e6e3b31bb4450842b4557122752b94fcf12fc4/core-bundle/src/Resources/contao/elements/ContentProxy.php#L43

Within `ContentElementReference` only the `type` and `id` is really used, the rest of the given `ContentModel` gets thrown away.
https://github.com/contao/contao/blob/56e6e3b31bb4450842b4557122752b94fcf12fc4/core-bundle/src/Fragment/Reference/ContentElementReference.php#L24-L32

When the fragment handler tries to render this element the `ModelArgumentResolver` will kick in and tries to fetch the original model from the database:
https://github.com/contao/contao/blob/56e6e3b31bb4450842b4557122752b94fcf12fc4/core-bundle/src/HttpKernel/ModelArgumentResolver.php#L93-L96
This way we're completely dependant on an already existing `ContentElement` from the database and loose the capability to render "fake" Content Elements on the fly.

We're aware that the current implementation was done this way so the rendered elements can be cached for performance reasons but this is not applicable in such use case since our final custom element will be cached anyway 🤷‍♂️

One last thing: Everything mentioned above also applies to `ModuleProxy`.

**Comment by m-vo** [comment]
Maybe you could use `Controller::getContentElement($contentElementModel)` instead?

For refrence, this is another use case that would benefit from something like https://github.com/contao/contao/pull/3942 in the future.

**Comment by bennyborn** [comment]
> Maybe you could use `Controller::getContentElement($contentElementModel)` instead?

While this looked promising at a first glance it fails exactly in the same way (`Could not resolve argument $model of "contao....`) when using non-legacy elements :\

**Comment by aschempp** [comment]
I don't think we can/should fix this in 4.9. It _can_ be solved with (some of) the changes in https://github.com/contao/contao/pull/3982/files#diff-6ad309fd46908d6dddb34a424b8ad010d57384cb33b6311e8d40a9f5dbc11b50L28, since they no longer result in the model being fetched from the database. I think we should discuss pros and cons for that in a future call.

**Comment by bennyborn** [comment]
With the new LTS coming up I don't think it is critical to fix this in 4.9 but it should surely be fixed during the lifetime of 4.13.

**Comment by aschempp** [comment]
https://github.com/contao/contao/pull/4256 could be a solution to this. 

instead of your initial example

```php
$oModel = new ContentModel();
$oModel->type = 'somethingawesome';
$oModel->customStuff = 'whatever';
...

$oElement = new ContentProxy($oModel);

$template->awesome_element = $oElement->generate();
```

the code would then look like this:

```php
$oModel = new ContentModel();
$oModel->type = 'somethingawesome';
$oModel->customStuff = 'whatever';
...

$fragment = ContentFragmentReference::withModel($oModel);

// maybe System::getContainer()->get('fragment.handler')
$template->awesome_element = $this->fragmentRenderer->render($fragment);

```

This will not work with fragments that "require" ESI, but I suppose that would not be your problem since ESI can never be generated "on the fly".

**Comment by aschempp** [comment]
Btw. you can also manually do the 2 lines of code from #4256 just to try it 😉

**Comment by michb** [comment]
This solution definitely adds some possibilities but it doesn't work for legacy elements.
This will work for content elements of `type` `markdown` and `template` but it fails e.g. for `image` with this error:
```
UnknownFragmentException
Invalid fragment identifier "contao.content_element.image"
in vendor/contao/core-bundle/src/Fragment/FragmentHandler.php (line 53)
```
As only these content elements are added to the `Contao\CoreBundle\Fragment\FragmentRegistry`.

**Comment by fritzmg** [comment]
@michb for legacy elements/modules you still need to do it this way:

```php
$contentModel = new ContentModel();
// …

$contentElement = new ContentImage($contentModel);
echo $contentElement->generate();
```

**Comment by aschempp** [comment]
yeah, it only works for fragment controllers. But I would assume your code knows about the type of element you're manually creating?

**Comment by michb** [comment]
It's fine like this. Just wanted to state what is possible and for later reference.
