### ISSUE TITLE
Preview links - Users could see all unpublished content

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#4109]
### Affected version(s)

4.13-RC2

### Description

When I get a preview link, I can also see other "unpublished" pages and content.

1. create news
2. create preview link
3. logout backend
4. click preview link
5. change to news archive page and all unpublished news will be displayed
6. unpublished pages are also displayed in the menu.

See this short video:
https://www.loom.com/share/4c7e8956d1cc44579ab6731dad9908a2

**Comment by fritzmg** [comment]
That's intended, the preview link currently allows anyone with the link to access the front end preview with the given settings. It is not restricted to a specific URL in any way.

**Comment by leofeyer** [comment]
So it does not actually matter which site I create the link on? The recipient will see all unpublished elements on all sites? @aschempp /cc

**Comment by aschempp** [comment]
yes, that's how our frontend preview works. And I don't think this matters, as you should only send these frontend preview links to a "known" person that is supposed to see something that has not been published yet.

**Comment by contaoacademy** [comment]
Ok, got it. I was hoping there was some kind of solution 😉

**Comment by fritzmg** [comment]
The current solution provides access to the front end preview for non-Contao back end users. Your request would be a [new feature](https://github.com/contao/contao/issues/new?assignees=&labels=feature&template=2_Feature_request.yml) for Contao 5.
