### ISSUE TITLE
Fix the ondelete_callback

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#4110]
### Affected version(s)

4.*

### Description

The `ondelete_callback` passes `$this, $undoId` in DC_Table and `$source, $this` in DC_Folder. Since we usually pass the DC object as last argument, I‘d vote for adjusting the callback in DC_Table in Contao 5.

@contao/developers WDYT?

**Comment by fritzmg** [comment]
There are more candidates:

* `config.onload`
* `config.onsubmit`
* `list.label.label`
* `fields.<FIELD>.load`
* `fields.<FIELD>.save`

If we want to clean this up, I'd prefer introducing events instead, so that it's easier to work with (for both the dispatcher and the subscriber).

**Comment by m-vo** [comment]
> If we want to clean this up, I'd prefer introducing events instead,

I assume it would otherwise be hard to support both 4.13 and 5 in an extension. 👍

But very +1 for cleaning this up!

**Comment by aschempp** [comment]
I agree this is inconsistent, but I honestly think we should just keep it as is. Changing it would be a BC break and a major PITA for extensions to support. And (almost) no extension will ever use the same callback to register for multiple different datacontainer.

(Additional) events might "solve" this, but I still think we should first improve the DC or at least rethink our concept before adding such things.
