### ISSUE TITLE
Do not add dot files in the DBAFS

### ISSUE THREAD

**Issue by m-vo** [contao/contao#4111]
> 1. `.DS_Store` files are now added. They haven‘t been before.
> 
> <img alt="" width="875" src="https://user-images.githubusercontent.com/1192057/152515693-77f7c02e-c6bf-4b49-871c-1a8a54f57655.png">

These are the options we are using now:

https://github.com/contao/contao/blob/be0d1bbff682506f0f9ed9d71425fc91c45c5cea/core-bundle/src/Resources/contao/library/Contao/Dbafs.php#L129

We should not change the behavior IMHO.

_Originally posted by @leofeyer in https://github.com/contao/contao/issues/3990#issuecomment-1036250904_

**Comment by m-vo** [comment]
Before I implement this, what's the intention to skip dot files?

**Comment by ausi** [comment]
macOS automatically creates the DS store files, so these should definitely be ignored.

maybe there is also a historical reason because protected folders used .htaccess

And we use .public ourself now…

**Comment by leofeyer** [comment]
Why can we not discuss this in the original PR? 😕

**Comment by m-vo** [comment]
> Why can we not discuss this in the original PR? confused

Because this doesn't have anything to do with #3990 but with the DBAFS service in general. If the old implementation and the new one behave differently, this is an issue no matter if #3990 is merged or not. Currently the back end and cli version would differ in that regard.

**Comment by leofeyer** [comment]
They should definitely behave the same. And the output should be the same in Contao 4.12 and Contao 4.13, otherwise it‘s a behavior change and the PR would have to be assigned to the next major version.

**Comment by m-vo** [comment]
You realize, that the already merged changes from #3774 affect the CLI? It's just a bug independent of #3990.

**Comment by ausi** [comment]
Can/should we make it a configurable regex that defaults to `^\.` in 4.13 and that we change to something like `^\.(DS_Store|public|nosync)` in 5.0 ?

**Comment by m-vo** [comment]
I think I'd ignore all files for now and maybe add that feature in Contao 5 if needed.

**Comment by m-vo** [comment]
see #4112
