### ISSUE TITLE
Extend backend breadcrumb

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#4128]
### Description

With Contao 4.13 the backend breadcrumb was optimized.
see: #3727

This currently only works with content-elements under «Content > Articles».
Can the concept be implemented universally for Contao so that this can also be used under other areas such as layout, forms, etc.

Possibly, this makes no sense at all?
Understand this ticket as an idea. If this is crap, please feel free to close the ticket.

**Comment by leofeyer** [comment]
I don‘t think that the feature is limited to the article view. I can also click the links in the news module for instance.

**Comment by contaoacademy** [comment]
**Working:**
- Articles
- News
- Events

**Comment by Total-Reality** [comment]
Btw. The breadcrumb link to the article should be removed while you are already in the view of the list of content elements. The link is a reference to the same page where I am at the moment.
This behavior is a little bit confusing.

> **Working:**
> 
> * Articles
> * News
> * Events

**Missing:**
* FAQ
* Forms
* Newsletter
* Front end modules
* Page layouts
* Image sizes
