### ISSUE TITLE
Restrict preview links to single page

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#4130]
### Description

There should be a possibility that the preview links are valid only for the page for which they were generated.
All other "unpublished" pages should remain invisible.

However, this use case is very rare for me. If there is no real need for the function, the ticket can also be closed.

see #4109

**Comment by fritzmg** [comment]
> All other "unpublished" pages should remain invisible.

That won't really be feasible to implement I think. However the preview could may be be restricted to a single URL (via the session). Any other URL would then respond with 403.

**Comment by leofeyer** [comment]
I‘m not very happy with the current solution, either. If a preview link is valid for all pages, why can we generate preview links for specific subpages then? A link to the home page would suffice.

We should either limit the preview links or adjust the way preview links are generated.

**Comment by fritzmg** [comment]
> A link to the home page would suffice.

No, that would not be sufficient. You want to share a specific URL to whoever is concerned.

**Comment by aschempp** [comment]
Most of my pages are not public visible, even if preview is enabled. I might send my client a link to an upcoming news, having a link to the homepage certainly is not useful. With the current preview link, the client can instantly see the unpublished news and "approve". Yes she could also navigate and see other content, but I don't see a problem in that, it always depends on what I tell my client.

**Comment by ausi** [comment]
I would also have assumed that the preview link is only valid for that single page. Although a checkbox for allowing to navigate all pages might be a useful feature.

**Comment by leofeyer** [comment]
There is another issue that has been reported:

> Die Preview-Session wird bei Deaktivierung des Preview-Links nicht beendet. Solange der Besucher konstant aktiv ist und die Session nicht aus anderen Gründen abläuft, kann dieser also ohne zeitliches Limit mit erweiterten Rechten weitersurfen.

Maybe we can improve that as well.

**Comment by fritzmg** [comment]
> I would also have assumed that the preview link is only valid for that single page. Although a checkbox for allowing to navigate all pages might be a useful feature.

For BC it should be the other way around though. You can still change the default for your application via DCA adjustments, if you need to.

**Comment by aschempp** [comment]
> For BC it should be the other way around though. If you can still change the default for your application via DCA adjustments, if you need to.

Just be aware that preview links always expire after a few days, so I don't think we need a hard BC here 😆

**Comment by fritzmg** [comment]
But that has nothing to do with that?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to limit the preview URL to a single site and add a checkbox to optionally grant access to the whole site. A separate listener can check these permissions and can also check if the preview URL has been disabled.

**Comment by ausi** [comment]
With #5454 there is now a Checkbox “Restrict access to specified URL” so you can decide how each shared link should behave.
