### ISSUE TITLE
Installation of 4.13.0-RC3 not possible?

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#4131]
### Affected version(s)

4.13.0-RC3

### Description

We've upgraded our local test installation from 4.12 to 4.13.0-RC3 without any problems but currently it seems to be impossible to install 4.13 from scratch using `composer create-project contao/managed-edition . 4.13.x-dev`. 

Composer is doing his job so far but trying to use the `contao-console` or the Install-Tool fails because there is no way to configure the database connection. 

I know how the `parameters.yml` should look like but is this really intended or just a bug?

**Comment by fritzmg** [comment]
What exactly is the problem?

**Comment by bennyborn** [comment]
Created the project using `composer create-project contao/managed-edition . 4.13.x-dev`, went through without errors. Tried to open `/contao/install` and failed with the following log entry

```
[2022-02-14T15:22:11.335471+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory" at /home/benny/www/413test/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory at /home/benny/www/413test/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/benny/www/413test/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/benny/www/413test/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
```

Also trying to use the `contao-console` command

```benny@devel:~/www/413test$ vendor/bin/contao-console
Contao Managed Edition 4.13.0-RC3 (env: prod, debug: false)

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display help for the given command. When no command is given display help for the list command
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -e, --env=ENV         The Environment name. [default: "prod"]
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

15:22:52 CRITICAL  [console] An error occurred while using the console. Message: "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory" ["exception" => Doctrine\DBAL\Exception\ConnectionException^ { …},"message" => "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory"]

In ExceptionConverter.php line 103:

  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory


In Exception.php line 30:

  SQLSTATE[HY000] [2002] No such file or directory


In Driver.php line 28:

  SQLSTATE[HY000] [2002] No such file or directory


list [--raw] [--format FORMAT] [--short] [--] [<namespace>]
```

It seems running the post install command again now fixed it but shouldn't this have already worked in the first place?

**Comment by fritzmg** [comment]
I cannot reproduce locally. Put `APP_ENV=dev` in your `.env`/`.env.local`, reproduce again and then post the stack trace.

**Comment by bennyborn** [comment]
Trying this now I can't get the Installtool to fail like before. 
This always seems to work now for me.  🤔

But it seems I still can't use the contao-console without completing the installation first. 

Doing a `vendor/bin/contao-console list` is still giving me the same errors but surely this should work without any database connection?

```sh
benny@devel:~/www/413test$ vendor/bin/contao-console list
Contao Managed Edition 4.13.0-RC3 (env: dev, debug: true)

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display help for the given command. When no command is given display help for the list command
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -e, --env=ENV         The Environment name. [default: "dev"]
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

09:42:45 CRITICAL  [console] Error thrown while running command "list". Message: "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory" ["exception" => Doctrine\DBAL\Exception\ConnectionException^ { …},"command" => "list","message" => "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory"]

In ExceptionConverter.php line 103:

  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory


In Exception.php line 30:

  SQLSTATE[HY000] [2002] No such file or directory


In Driver.php line 28:

  SQLSTATE[HY000] [2002] No such file or directory


list [--raw] [--format FORMAT] [--short] [--] [<namespace>]

```

**Comment by Toflar** [comment]
Where is the connection initiated?

**Comment by bennyborn** [comment]
> Where is the connection initiated?

I don't know but judging by the exception something seems to try to open a database connection, right?

**Comment by Toflar** [comment]
I guess so, that's why I'm asking where it's happening :)

**Comment by fritzmg** [comment]
@bennyborn you need to add `-vvv` in order to be able to provide a stack trace.

**Comment by bennyborn** [comment]
> @bennyborn you need to add `-vvv` in order to be able to provide a stack trace.

You told me to create the .env file, which I did ;)
Nonetheless here is [the stack trace](https://github.com/contao/contao/files/8087204/trace.txt).

**Comment by fritzmg** [comment]
> You told me to create the .env file, which I did ;)

That was for the error in the Install Tool. For commands you can use `-vvv` to get a stack trace.

Hm, it's because of the `contao.cron` service, which needs the `contao.repository.cron_job` repository, which in turn seems to require a database connection down the line. However, I still cannot reproduce this locally 🤔

**Comment by bennyborn** [comment]
> However, I still cannot reproduce this locally 🤔

That's strange. Did you really try just doing a fresh install using `composer create-project contao/managed-edition . 4.13.x-dev` and then `vendor/bin/contao-console list` directly afterwards?

Because I just tried it on a second, completely different machine and the behaviour is exactly the same.

**Comment by leonexcc** [comment]
I can reproduce this. It es the detection mechanism for the server version in doctine

**Comment by ausi** [comment]
I think we have to change this here https://github.com/contao/contao/blob/ab4f74cc7627a5cb395897bafa284e481e901d33/core-bundle/src/Resources/config/commands.yml#L44 the same way as we did in https://github.com/contao/contao/commit/2a19b186afd59495e9fbd5174d0deb40543c5079#diff-2a0d76195d45f9f9b0486317e8d4a43845ef063101fa6ea0b3bbe3ef241e71a0L89

**Comment by ausi** [comment]
I was able to reproduce the issue with `vendor/bin/contao-console list`, but I was not able to reproduce an error in the install tool.

@bennyborn can you post the stack trace from the error that happens on `/contao/install`?

**Comment by bennyborn** [comment]
@ausi unfortunately not, as I wrote before

> Trying this now I can't get the Installtool to fail like before. This always seems to work now for me. 🤔

Guess something changed since Monday?...

**Comment by ausi** [comment]
> Guess something changed since Monday?...

Not that I know of.
