### ISSUE TITLE
Default localizations aren't loaded in dca tl_* files

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#4132]
### Affected version(s)

4.13

### Description

Hello,

in 

https://github.com/heimrichhannot/contao-formhybrid/blob/master/dca/tl_module.php#L700

we call another module to add some fields. The function used is this one:

https://github.com/heimrichhannot/contao-privacy-bundle/blob/master/src/Manager/ProtocolManager.php#L437

Unfortunately, the localizations in `$GLOBALS['TL_LANG']['MSC']` are nearly empty at the moment `tl_module` is being run which is a BC break. Means, that the `default.php` files aren't all loaded before the DCA files are loaded which was the case in 4.9.

I hope it's a bug and not intended behavior since many modules rely on this practice still.

Thanks in advance.

**Comment by fritzmg** [comment]
That's normal. If you want the translations to be there, you would have to call `System::loadLanguageFile('default')` yourself. However, from your examples I am unable to see why you need that in the first place.

**Comment by Defcon0** [comment]
??? Since now, we *never* needed to load default localizations at this point. Point is to have a fallback localization.

Also: if I load that manually, it's cached and when the function is called again, we don't have the full array of localizations.

**Comment by fritzmg** [comment]
> Also: if I load that manually, it's cached and when the function is called again, we don't have the full array of localizations.

Why?

**Comment by Defcon0** [comment]
We had the same discussion internally :-) In fact I can't reproduce it, but I indeed have had this issue that, if I call the method twice, I get different results. If it's safe to call it there, we can do it. Although I can't tell from the code of `loadLanguageFile` out of the box.

But shouldn't the localizations of the `default.php` files be loaded automatically anyways?

**Comment by aschempp** [comment]
first of all, I would think to remember the `default` language file is always loaded by the system? It might be different for other files, but `default` should be?

Secondly, @Defcon0 you should most certainly use the `loadDataContainer` hook instead of manipulating that stuff directly in the DCA file. It will give you Dependency Injection, the translator (that loads language files for you!) and everything else you can imagine 😉

**Comment by Defcon0** [comment]
@aschempp We're using the loadDataContainer in most cases already, but in this particular case, I tried just that without success. Fixing the array index warnings for php 8 pointed me in the direction.

**Comment by Defcon0** [comment]
Might be important: it mostly occurs when doing a cache rebuild after a composer install.

Ah, this might be the difference. When changing the function to the following, it works again:

```
public function getSelectorFieldDca($label = null)
    {
        $data = [
            'label' => &$GLOBALS['TL_LANG']['MSC']['huhPrivacy']['addPrivacyProtocolEntry'],
            'exclude' => true,
            'inputType' => 'checkbox',
            'eval' => ['tl_class' => 'w50 clr', 'submitOnChange' => true],
            'sql' => "char(1) NOT NULL default ''",
        ];

        if ($label && \is_string($label)) {
            $data['label'] = $label;
        }

        return $data;
    }
```

**Comment by ausi** [comment]
`$data['label']` is a reference to `$GLOBALS['TL_LANG']['MSC']['huhPrivacy']['addPrivacyProtocolEntry']`, so in the line `$data['label'] = $label;` you are modifying the value of `$GLOBALS['TL_LANG']`.

You should probably use something like `unset($data['label']); $data['label'] = $label;` instead.

**Comment by Defcon0** [comment]
Ah, I see. Thanks for clearification.

**Comment by aschempp** [comment]
I guess this can be closed then?

**Comment by Defcon0** [comment]
I guess so :-)
