### ISSUE TITLE
Root page dependent modules | add information about the root page after modules have been selected (#3613)

### ISSUE THREAD

**Issue by zoglo** [contao/contao#4137]
### Description

**Feature Request for Contao 4.13**

It would be a nice feature if the root page dependent modules would show the root page behind the selected module:

#### Example
![image](https://user-images.githubusercontent.com/55794780/154100073-ab5df375-8245-413f-a378-1be9d138d2e1.png)

**Comment by bytehead** [comment]
Closed in favor of #4139.
