### ISSUE TITLE
Linking to a page with requireItem results in PHP Exception

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#4142]
### Affected version(s)

4.12, 4.13

### Description

If you link to a page with the activated option "requireItem" this will result in an error.

You can reproduce it in the demo. Just link it via insert tag / picker in a tinyMCE window or set a internal redirect to the news detail page.

For example set this page to page type "internal redirect" and choose the news detail page.
https://demo.contao.org/contao?do=page&act=edit&id=2

`request.CRITICAL: Uncaught PHP Exception Contao\CoreBundle\Exception\RouteParametersException: "Unable to generate route for page ID 152. The page requires an item but none was given." at /contao412/vendor/contao/core-bundle/src/Routing/PageUrlGenerator.php line 94 {"exception":"[object] (Contao\\CoreBundle\\Exception\\RouteParametersException(code: 0): Unable to generate route for page ID 152. The page requires an item but none was given. at /contao412/vendor/contao/core-bundle/src/Routing/PageUrlGenerator.php:94)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\InvalidParameterException(code: 0): Parameter \"parameters\" for route \"tl_page.152\" must match \"/.+\" (\"\" given) to generate a corresponding URL. at /contao412/vendor/symfony/routing/Generator/UrlGenerator.php:194)"} []`

Big thanks to @Tastaturberuf & @zoglo for testing with me long after 2 a.m. in Airmeet 🚀 

It isn't very good that the whole page crashes when you set such a link in the footer e.g. 👻 

Additionally it is a problem that links like {{link_url::152}}/hello-world/ doesn't work any more in the new rooting.

I don't know if this is similar or the same like this problem here?
https://github.com/contao/contao/pull/3540

**Comment by aschempp** [comment]
This is not a bug. You cannot link to that page, because it requires a parameter in the URL. Same applies to any other page with a required parameter. 

If you have an idea how we could improve the user experience, please let me know 😊

**Comment by ausi** [comment]
> If you have an idea how we could improve the user experience, please let me know 😊

I think we should wrap the link insert tag in a try-catch block, as users usually don’t expect insert tags to break the whole page.

Also, would it be possible disable the selection of these pages in the picker?

**Comment by Total-Reality** [comment]
> Also, would it be possible disable the selection of these pages in the picker?

The problem is that you can add the _requireItem_ option of the linked page later. 

Unless you check when saving the requireitem option if the current page is linked. But I think that's too cumbersome and unperformant.

> This is not a bug. You cannot link to that page, because it requires a parameter in the URL. Same applies to any other page with a required parameter.

However it is possible to link to that page. It can't be that an editor can crash the whole page with this action! 
It is an unexpected event. A bug is an unexpected event or a result of unexpected actions of the user, isn't it?

**Comment by Tastaturberuf** [comment]
Page A should never be responsible for the misconfiguration on page B. Page B configuration can change on any time.
Just ignore the insert tag and write an error to the Contao log.

**Comment by fritzmg** [comment]
I agree, we need to handle it the same way as in the navigation modules.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to wrap the insert tag in a try/catch-block and add a log entry if the URL cannot be generated.
