### ISSUE TITLE
Improve sorting in System-Log

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#4148]
### Description

By default the System-Log is sorted and grouped by `tstamp`. This is all fine for the usual workflow when using Contao.

In a couple of our projects we've implemented imports (or other routines) which do some logging into the System-Log and might result in 10 or 20 concurrent entries within the same second. Being sorted by `tstamp` rather than `id` this significantly messes with the order of the entries.

Any chance to improve this? I don't see any easy solution because altering the sorting also always messes up the grouping.

**Comment by fritzmg** [comment]
Try:

```php
// contao/dca/tl_log.php
use Contao\DataContainer;

$GLOBALS['TL_DCA']['tl_log']['fields']['id']['flag'] = DataContainer::SORT_DESC; // 12
$GLOBALS['TL_DCA']['tl_log']['list']['sorting']['fields'][] = 'id';
```

**Comment by bennyborn** [comment]
That seems to work nicely 👍 Anything against adding this to the Core?

**Comment by fritzmg** [comment]
I have nothing against it, you could provide a PR for this minimal change :)

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4150
