### ISSUE TITLE
add <details> and <summary> to Allowed HTML tags

### ISSUE THREAD

**Issue by berecont** [contao/contao#4156]
### Description

add `<details>` and `<summary>` to Allowed HTML tags  
so in content-element 'markdown' it's possible to add (in basic settings) a collapsible section like

```
<details>
<summary>click to expand</summary>
<p>my awsome information</p>
</details>
```

**Comment by bytehead** [comment]
See https://github.com/contao/contao/pull/4155

**Comment by Toflar** [comment]
https://github.com/contao/contao/pull/4155
