### ISSUE TITLE
Update search index - download debug log and search index log again

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#4157]
### Description

Affects system maintenance @ Contao 4.9 and 4.13.

Is there a way to download the two logs again in the "Update search index" feature? Even if you left the page in the backend in the meantime or after you get logged out?

The problem is that in a project, e.g. 26,000 pages are crawled and that takes over 1 hour. In the meantime, of course, I don't want to wait. 
After a while I go back to the browser tab of this website again. It often happens that you are already logged out or want to look at something else in the backend. And then you get really annoyed that you can't see the result of the search index crawler tool and additionally you can't download the logs.
You have to check and wait again over 1 hour... 

So could you please create a function to cache the last result or save the log files on the server? There's a nice folder /var/logs - something like that could go in there, couldn't it?

**Comment by ausi** [comment]
We should probably add a check here https://github.com/contao/contao/blob/e8f1f373477839aa301ad1eb5eb4fb84b719957d/core-bundle/src/Resources/contao/classes/Crawl.php#L172-L176 to only (re)start crawling if the jobId does not exist yet.

This way, downloading the log after logging in again should be no problem.

**Comment by leofeyer** [comment]
@Toflar Would that work?

**Comment by Toflar** [comment]
Sure, why not? You can write the CSV to any place you like. It's just not as easy as writing it to `var/logs` (or `var/log`) because that directory is not cleaned up so you would need build some log rotation or whatever in order to clean up old entries.

**Comment by leofeyer** [comment]
@Total-Reality Could you provide a pull request with the necessary changes?

**Comment by ausi** [comment]
> You can write the CSV to any place you like.

I think we could keep the current location of the log files with the solution I suggested in https://github.com/contao/contao/issues/4157#issuecomment-1046256881
