### ISSUE TITLE
MySQL Row size too large

### ISSUE THREAD

**Issue by ausi** [contao/contao#4159]
### Affected version(s)

4.9+

### Description

I was finally able to reproduce the too large row size error after it was [reported on Slack](https://contao.slack.com/archives/CK9GW3ARL/p1645126965059009) today.

It seems that there are two very similar but different error messages at work here:

1. `ERROR 1118 (42000): Row size too large (> 8126). Changing some columns to TEXT or BLOB may help.`  
   This is caused by the InnoDB storage engine.
  
2. `ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs`  
   This limit is the absolute maximum row size for all tables regardless of the storage engine.

See <https://mariadb.com/kb/en/innodb-row-formats-overview/#maximum-row-size> for more details.

`VARCHAR(255)` does **not** add more to the row size than `VARCHAR(2048)` for InnoDB (max 8126) but it does add to the row size for the Database itself (max 65535).

The following query runs into the general size limit (second error from above) because 16383 * 4 = 65532 and the remaining 3 bytes are not enough for the `int` column:

```sql
CREATE TABLE test (col1 varchar(16383), col2 int) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

On the other hand, InnoDB uses a maximum of 40 data bytes per `VARCHAR()` one byte for the length and one additional bit (makes 41.125 bytes per column). So it can store a maximum of 197 `VARCHAR()` columns (whose size is 10 characters (40 bytes) or more).

<details>
<summary>Reproduction:</summary>

```sql
CREATE TABLE test (
   col1 varchar(10) NOT NULL,
   col2 varchar(10) NOT NULL,
   col3 varchar(10) NOT NULL,
   col4 varchar(10) NOT NULL,
   col5 varchar(10) NOT NULL,
   col6 varchar(10) NOT NULL,
   col7 varchar(10) NOT NULL,
   col8 varchar(10) NOT NULL,
   col9 varchar(10) NOT NULL,
   col10 varchar(10) NOT NULL,
   col11 varchar(10) NOT NULL,
   col12 varchar(10) NOT NULL,
   col13 varchar(10) NOT NULL,
   col14 varchar(10) NOT NULL,
   col15 varchar(10) NOT NULL,
   col16 varchar(10) NOT NULL,
   col17 varchar(10) NOT NULL,
   col18 varchar(10) NOT NULL,
   col19 varchar(10) NOT NULL,
   col20 varchar(10) NOT NULL,
   col21 varchar(10) NOT NULL,
   col22 varchar(10) NOT NULL,
   col23 varchar(10) NOT NULL,
   col24 varchar(10) NOT NULL,
   col25 varchar(10) NOT NULL,
   col26 varchar(10) NOT NULL,
   col27 varchar(10) NOT NULL,
   col28 varchar(10) NOT NULL,
   col29 varchar(10) NOT NULL,
   col30 varchar(10) NOT NULL,
   col31 varchar(10) NOT NULL,
   col32 varchar(10) NOT NULL,
   col33 varchar(10) NOT NULL,
   col34 varchar(10) NOT NULL,
   col35 varchar(10) NOT NULL,
   col36 varchar(10) NOT NULL,
   col37 varchar(10) NOT NULL,
   col38 varchar(10) NOT NULL,
   col39 varchar(10) NOT NULL,
   col40 varchar(10) NOT NULL,
   col41 varchar(10) NOT NULL,
   col42 varchar(10) NOT NULL,
   col43 varchar(10) NOT NULL,
   col44 varchar(10) NOT NULL,
   col45 varchar(10) NOT NULL,
   col46 varchar(10) NOT NULL,
   col47 varchar(10) NOT NULL,
   col48 varchar(10) NOT NULL,
   col49 varchar(10) NOT NULL,
   col50 varchar(10) NOT NULL,
   col51 varchar(10) NOT NULL,
   col52 varchar(10) NOT NULL,
   col53 varchar(10) NOT NULL,
   col54 varchar(10) NOT NULL,
   col55 varchar(10) NOT NULL,
   col56 varchar(10) NOT NULL,
   col57 varchar(10) NOT NULL,
   col58 varchar(10) NOT NULL,
   col59 varchar(10) NOT NULL,
   col60 varchar(10) NOT NULL,
   col61 varchar(10) NOT NULL,
   col62 varchar(10) NOT NULL,
   col63 varchar(10) NOT NULL,
   col64 varchar(10) NOT NULL,
   col65 varchar(10) NOT NULL,
   col66 varchar(10) NOT NULL,
   col67 varchar(10) NOT NULL,
   col68 varchar(10) NOT NULL,
   col69 varchar(10) NOT NULL,
   col70 varchar(10) NOT NULL,
   col71 varchar(10) NOT NULL,
   col72 varchar(10) NOT NULL,
   col73 varchar(10) NOT NULL,
   col74 varchar(10) NOT NULL,
   col75 varchar(10) NOT NULL,
   col76 varchar(10) NOT NULL,
   col77 varchar(10) NOT NULL,
   col78 varchar(10) NOT NULL,
   col79 varchar(10) NOT NULL,
   col80 varchar(10) NOT NULL,
   col81 varchar(10) NOT NULL,
   col82 varchar(10) NOT NULL,
   col83 varchar(10) NOT NULL,
   col84 varchar(10) NOT NULL,
   col85 varchar(10) NOT NULL,
   col86 varchar(10) NOT NULL,
   col87 varchar(10) NOT NULL,
   col88 varchar(10) NOT NULL,
   col89 varchar(10) NOT NULL,
   col90 varchar(10) NOT NULL,
   col91 varchar(10) NOT NULL,
   col92 varchar(10) NOT NULL,
   col93 varchar(10) NOT NULL,
   col94 varchar(10) NOT NULL,
   col95 varchar(10) NOT NULL,
   col96 varchar(10) NOT NULL,
   col97 varchar(10) NOT NULL,
   col98 varchar(10) NOT NULL,
   col99 varchar(10) NOT NULL,
   col100 varchar(10) NOT NULL,
   col101 varchar(10) NOT NULL,
   col102 varchar(10) NOT NULL,
   col103 varchar(10) NOT NULL,
   col104 varchar(10) NOT NULL,
   col105 varchar(10) NOT NULL,
   col106 varchar(10) NOT NULL,
   col107 varchar(10) NOT NULL,
   col108 varchar(10) NOT NULL,
   col109 varchar(10) NOT NULL,
   col110 varchar(10) NOT NULL,
   col111 varchar(10) NOT NULL,
   col112 varchar(10) NOT NULL,
   col113 varchar(10) NOT NULL,
   col114 varchar(10) NOT NULL,
   col115 varchar(10) NOT NULL,
   col116 varchar(10) NOT NULL,
   col117 varchar(10) NOT NULL,
   col118 varchar(10) NOT NULL,
   col119 varchar(10) NOT NULL,
   col120 varchar(10) NOT NULL,
   col121 varchar(10) NOT NULL,
   col122 varchar(10) NOT NULL,
   col123 varchar(10) NOT NULL,
   col124 varchar(10) NOT NULL,
   col125 varchar(10) NOT NULL,
   col126 varchar(10) NOT NULL,
   col127 varchar(10) NOT NULL,
   col128 varchar(10) NOT NULL,
   col129 varchar(10) NOT NULL,
   col130 varchar(10) NOT NULL,
   col131 varchar(10) NOT NULL,
   col132 varchar(10) NOT NULL,
   col133 varchar(10) NOT NULL,
   col134 varchar(10) NOT NULL,
   col135 varchar(10) NOT NULL,
   col136 varchar(10) NOT NULL,
   col137 varchar(10) NOT NULL,
   col138 varchar(10) NOT NULL,
   col139 varchar(10) NOT NULL,
   col140 varchar(10) NOT NULL,
   col141 varchar(10) NOT NULL,
   col142 varchar(10) NOT NULL,
   col143 varchar(10) NOT NULL,
   col144 varchar(10) NOT NULL,
   col145 varchar(10) NOT NULL,
   col146 varchar(10) NOT NULL,
   col147 varchar(10) NOT NULL,
   col148 varchar(10) NOT NULL,
   col149 varchar(10) NOT NULL,
   col150 varchar(10) NOT NULL,
   col151 varchar(10) NOT NULL,
   col152 varchar(10) NOT NULL,
   col153 varchar(10) NOT NULL,
   col154 varchar(10) NOT NULL,
   col155 varchar(10) NOT NULL,
   col156 varchar(10) NOT NULL,
   col157 varchar(10) NOT NULL,
   col158 varchar(10) NOT NULL,
   col159 varchar(10) NOT NULL,
   col160 varchar(10) NOT NULL,
   col161 varchar(10) NOT NULL,
   col162 varchar(10) NOT NULL,
   col163 varchar(10) NOT NULL,
   col164 varchar(10) NOT NULL,
   col165 varchar(10) NOT NULL,
   col166 varchar(10) NOT NULL,
   col167 varchar(10) NOT NULL,
   col168 varchar(10) NOT NULL,
   col169 varchar(10) NOT NULL,
   col170 varchar(10) NOT NULL,
   col171 varchar(10) NOT NULL,
   col172 varchar(10) NOT NULL,
   col173 varchar(10) NOT NULL,
   col174 varchar(10) NOT NULL,
   col175 varchar(10) NOT NULL,
   col176 varchar(10) NOT NULL,
   col177 varchar(10) NOT NULL,
   col178 varchar(10) NOT NULL,
   col179 varchar(10) NOT NULL,
   col180 varchar(10) NOT NULL,
   col181 varchar(10) NOT NULL,
   col182 varchar(10) NOT NULL,
   col183 varchar(10) NOT NULL,
   col184 varchar(10) NOT NULL,
   col185 varchar(10) NOT NULL,
   col186 varchar(10) NOT NULL,
   col187 varchar(10) NOT NULL,
   col188 varchar(10) NOT NULL,
   col189 varchar(10) NOT NULL,
   col190 varchar(10) NOT NULL,
   col191 varchar(10) NOT NULL,
   col192 varchar(10) NOT NULL,
   col193 varchar(10) NOT NULL,
   col194 varchar(10) NOT NULL,
   col195 varchar(10) NOT NULL,
   col196 varchar(10) NOT NULL,
   col197 varchar(10) NOT NULL,
   col198 varchar(10) NOT NULL	
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

</details>

***

Conclusion: The 65535 limit is a bigger problem for us because we can only fit 7 `VARCHAR(2048)` or 15 `VARCHAR(1024)` or 64 `VARCHAR(255)` columns in one table.

I would change most `VARCHAR()` columns to `TINYTEXT` as long as they do not need a default value and are longer than 10 characters. This decreases our row size towards the 65535 limit and keeps the size the same regarding the 8126 limit.

**Comment by fritzmg** [comment]
Should we also apply this to 4.9?

**Comment by contaoacademy** [comment]
I have also seen the problem more frequently lately in a support request. E.g. also after an update from Contao 3.5 to Contao 4.9

**Comment by ausi** [comment]
This seems to be reproducible across MySQL 5.7, 8.0 and MariaDB 10.1, 10.3, 10.4, 10.5, 10.6 according to several tests from the community.

We noticed one pitfall: if `innodb_strict_mode` is set to `OFF`, the InnoDB limit is ignored when creating the table. But when inserting a row that is actually too large then (depends on the inserted data) the `INSERT` fails.

But the MySQL limit of 65535 seems to be enforced in all cases.

**Comment by jscholtysik** [comment]
Of course also relevant for 4.13...

Joachim

**Comment by ausi** [comment]
> The 65535 limit is a bigger problem for us

I might have been wrong here. Looking at some discussions in the Contao forum I counted 13 people running into the `8126` limit but only 4 exeeding the `65535` limit.

**Comment by fritzmg** [comment]
> I might have been wrong here. Looking at some discussions in the Contao forum I counted 13 people running into the 8126 limit 

Keep in mind that some of those might be from Contao 4.4 and/or running utf8 instead of utf8mb4.

**Comment by leofeyer** [comment]
@ausi In https://github.com/contao/contao/pull/4179#issuecomment-1047658782 you wrote:

> Briefly discussed with @fritzmg we should probably:
> 
> 1. Apply all `COLLATE ascii_bin` changes
> 2. Change `varchar`s that are lager than 255 to `text`
> 3. Don’t touch all other `varchar`s as the change of the default value from `''` to `null` could cause backwards compatibility issues.

So is this what we have to do to improve the situation?

**Comment by fritzmg** [comment]
I'd say yes. I think @ausi is gonna follow up with an according PR for 4.9, based on our discussions & findings here and in https://github.com/contao/contao/pull/4179

**Comment by ausi** [comment]
> So is this what we have to do to improve the situation?

Yes.

> I think @ausi is gonna follow up with an according PR for 4.9

Yes. I would only modify `tl_content` and `tl_module` though.

**Comment by havutcuoglu** [comment]
I have the same problem with the row size

`Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs`

It happens only by tl_content
```
ALTER TABLE tl_content CHANGE url url VARCHAR(2048) DEFAULT '' NOT NULL
ALTER TABLE tl_content CHANGE imageUrl imageUrl VARCHAR(2048) DEFAULT '' NOT NULL

```
I changed the value back to varchar(255) to finish the update.

Question: When will there be an update for version 4.13 to fix this problem?

**Comment by ausi** [comment]
> > So is this what we have to do to improve the situation?
> 
> Yes.

Done in https://github.com/contao/contao/pull/4179#issuecomment-1080014396
