### ISSUE TITLE
Install tool does not ignore tables without `tl_` prefix

### ISSUE THREAD

**Issue by aschempp** [contao/contao#4160]
### Affected version(s)

4.9+

### Description

![Bildschirmfoto 2022-02-17 um 10 45 10](https://user-images.githubusercontent.com/1073273/154631911-6ab6f01c-f5cf-4163-ade5-580da87b05b0.png)

According to my information, our schema migration checks all tables and does not ignore non-`tl_` prefix.

**Comment by leofeyer** [comment]
Yes it does?

https://github.com/contao/contao/blob/da55d19ac91a529da80453adb299a67ae8c2fabc/installation-bundle/src/Database/Installer.php#L124-L127

**Comment by leofeyer** [comment]
Ah, it seems it does no longer in Contao 4.13.

**Comment by m-vo** [comment]
IIRC we dropped the filter in 4.11 and probably simply forgot to adjust the message.

**Comment by ausi** [comment]
> IIRC we dropped the filter in 4.11

Yes, see #2049 / 2334184de6dec7ab0cda319ec1e44307d41b83b6

**Comment by h-e-l-i-x** [comment]
@aschempp 
(tested w/ contao 4.13.13)
re-adding the filter to only handle tl_ prefixed tables using the config.yml

```
doctrine:
    dbal:
        schema_filter: ~^(tl_.*)~
```


preferred solution: ignore only specific table "mytable", as some extensions might not use the tl_ prefix.

```
doctrine:
    dbal:
        schema_filter: ~^(?!mytable)~
```
