### ISSUE TITLE
License field in the file metadata results in Google warning

### ISSUE THREAD

**Issue by Anke** [contao/contao#4164]
### Affected version(s)

4.13

### Description

It's the first time I used the meta field "license" entering the name of the copyright holder - and just 48 hours later I get this Google warning:

![grafik](https://user-images.githubusercontent.com/1300920/154670968-a0134589-9986-4e19-b354-9d0e61082806.png)

Is this a bug or what exactly do I have to enter into the license field?

Regards,
Anke

**Comment by fritzmg** [comment]
According to https://schema.org/license `license` is supposed to be either an URL or a [CreativeWork](https://schema.org/CreativeWork) object.

@contao/developers may be we should enforce URLs in that meta field?

**Comment by ausi** [comment]
How about changing the label in https://github.com/contao/contao/blob/19baacfd29efde0f088a4b09dcfb2b22438d2ff9/core-bundle/src/Resources/contao/languages/en/default.xlf#L992-L994 to “License URL”?

**Comment by Anke** [comment]
Well, my problem is, that I couldn't find any documentation/manual. Do I enter the name of the copyright holder here or a URL to the respective license like https://creativecommons.org/licenses/by/4.0/ - or both in combination ...

**Comment by Anke** [comment]
> How about changing the label in
> 
> https://github.com/contao/contao/blob/19baacfd29efde0f088a4b09dcfb2b22438d2ff9/core-bundle/src/Resources/contao/languages/en/default.xlf#L992-L994
> to “License URL”?

That sounds easy. In this case I could enter a link to a Contao page containing all copyright/licence information?

**Comment by asaage** [comment]
> used the meta field "license" entering the name of the copyright holder

Well [license](https://schema.org/license) is not the same as [copyrightHolder](https://schema.org/copyrightHolder).
Maybe it's more flexible to use the [copyrightNotice](https://schema.org/copyrightNotice) property?

**Comment by Anke** [comment]
Plus a respective (optional) output of that copyright notice link in the image template?

**Comment by fritzmg** [comment]
That was once rejected: https://github.com/contao/core-bundle/issues/1297#issuecomment-373392678

**Comment by asaage** [comment]
jepp i remember.
I didnt have a look at 4.13 so i dont know what the new field is intended for and how it is rendered in the template.
Just saying if it is rendered as ```itemprop=license``` it's only useful for providing a link to the license.

**Comment by fritzmg** [comment]
> I didnt have a look at 4.13 so i dont know what the new field is intended for and how it is rendered in the template.

It's not rendered in the template, it used for the meta data.

**Comment by Toflar** [comment]
Only a URL makes sense. We should ideally

- adjust the label
- add a url validation
- check if we can even use the picker there or not (probably not easily doable in that widget)

**Comment by m-vo** [comment]
> In this case I could enter a link to a Contao page containing all copyright/licence information?

If this is a use case we could even think about adding a page type for that and then generate a URL to that page by default. Not sure this is worth doing, though.

**Comment by fritzmg** [comment]
> check if we can even use the picker there or not (probably not easily doable in that widget)

It's already a picker :)

**Comment by aschempp** [comment]
> > In this case I could enter a link to a Contao page containing all copyright/licence information?
> 
> If this is a use case we could even think about adding a page type for that and then generate a URL to that page by default.

What would that page type do?

**Comment by asaage** [comment]
I don't understand https://github.com/contao/contao/pull/3076 completely.
I certainly think it's nice to have that data attached to the file but:

- would a license-url wich resides invisible in JSON-LD make any licensor or copyright-holder happy?
- what's the point without a copyright-holder-field? isn't that the requirement of the various stock-image-providers?

**Comment by Anke** [comment]
Whether such a URL points to a Contao page or some external page with licensing information - is this really for us to decide? Or are there standards set by stock-image-providers - or by Google? If so, I guess I don't have much use for this field, 
I just didn't know when and how to use it, so I just entered a name. If it has to be a URL then it shouldn't accept text. 

Maybe someone could occasionally update the documentation and explain how this field works and what it is good for?

**Comment by Toflar** [comment]
> Or are there standards set by stock-image-providers - or by Google?

Yes there are. And that's exactly the purpose of this feature. For example, links to the correct https://creativecommons.org license are handled by Google and your image will appear accordingly if you filter the search results for CC licensed images ;)

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to rename the field to "License URL" and validate the input.

**Comment by Toflar** [comment]
Implemented in https://github.com/contao/contao/pull/4617

**Comment by ThomasJanotta** [comment]
BTW, there's still no mention in the manual...
https://docs.contao.org/manual/de/dateiverwaltung/metadaten/#body-inner

(zzz 10 months later)

**Comment by m-vo** [comment]
> (zzz 10 months later)

You know how open source projects work? Feel free to contribute.

**Comment by ausi** [comment]
> BTW, there's still no mention in the manual...

You can use this link to update the manual: https://github.com/contao/docs/edit/main/docs/manual/file-manager/meta-data.de.md
