### ISSUE TITLE
Idea for a fast database reset in functional tests

### ISSUE THREAD

**Issue by ausi** [contao/contao#4168]
I just came across the [Transportable Tablespaces](https://dev.mysql.com/doc/refman/8.0/en/innodb-table-import.html) feature from InnoDB. If this works as described (and is fast enough) it might be a fit for our functional tests by doing the following:

1. Setup and import DB
2. `FLUSH TABLES t1, t2,… FOR EXPORT;`
3. Backup `datadir/DBNAME/TABLENAME.{ibd,cfg,cfp}`
4. `UNLOCK TABLES;`

After every test:

1. `ALTER TABLE t1, t2,… DISCARD TABLESPACE;`
2. Restore idb,cfg,cfp files
3. `ALTER TABLE t1, t2,… IMPORT TABLESPACE;`

If we can detect which tables have changed we could even do this only for the affected tables.

Not sure if this works, just wanted to write it down so it does not get forgotton ☺️

**Comment by m-vo** [comment]
We could also tinker with the mysql settings for the functional tests. For instance disabling double write buffering or increasing the log buffer/log file size has quite a big impact on importing dumps (IIRC), there are probably settings that affect how transportable tablespaces perform as well.

**Comment by ausi** [comment]
`IMPORT TABLESPACE` was not fast enough to be feasible for our use case, instead we did #4376
