### ISSUE TITLE
Remove "pdf" from the article syndication if the tcpdf-bundle is not installed

### ISSUE THREAD

**Issue by Toflar** [contao/contao#417]
**Affected version(s)**

4.7.*

**Description**  

Right now, when you do not install `contao/tcpdf-bundle`, you still get the option `Print as PDF` in the article syndication in the back end. That makes no sense because what it's going to do is it will produce links in the front end that then throw an exception saying that the bundle is not installed.
Imho it should be the other way around. The option should just not be there if you did not install the bundle but for those who update from previous versions, the DB remains untouched. So in those cases they won't have the option in the back end anymore but still get the links (which is correct) and then get the exception so they know what to do.
So to fix this, the `pdf` option should be extracted to the bundle and it's all good.

**Comment by leofeyer** [comment]
As discussed in Mumble on April 11th, we want to remove "Print as PDF" option in the back end and hide the "Print as PDF" link in the front end if the bundle is not installed.

**Comment by leofeyer** [comment]
Fixed in 388edab7cad4d8bdd0218bd2586d32847a3beea9.
