### ISSUE TITLE
Logging leaving user impersonation

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#4170]
### Affected version(s)

4.13.0

### Description

Leaving user impersonation (user menu -> ``Back to A``) creates a missleading system log entry (``User "B" has switched to user "A"``). But in fact A has quit the impersonation to B.

**Comment by aschempp** [comment]
I think this is technically correct, but could probably be improved. Can you check if this also applies to Contao 4.9?

**Comment by cliffparnitzky** [comment]
I have check this with Contao 4.9.28 ... same "probleme" here.

**Comment by bytehead** [comment]
Closed in favor of #4574
