### ISSUE TITLE
Settings -> Time zone - missing migration

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#4171]
### Affected version(s)

4.13.0

### Description

The field Settings -> Time zone shows ``Unknown option: CET``.

Maybe a migration is missing.

**Comment by ausi** [comment]
I don’t think a migration is needed here.

The “Unknown option: CET” should still work as before. And there is no proper time zone to convert `CET` to without more information.

To what value would you suggest to migrate `CET` to?

**Comment by aschempp** [comment]
> To what value would you suggest to migrate `CET` to?

It does not really mater, does it, as long as it's `GMT+1`? https://www.timeanddate.com/time/zones/cet
We could simply use something like `Europe/Berlin`

**Comment by fritzmg** [comment]
But that would not be correct. What if your actual timezone is Europe/Vienna and Austria suddenly decides to be in a different timezone?


...

😁

**Comment by ausi** [comment]
AFAIK, Vienna and Berlin had different time zones on June 1st, 1945 for example. A conversion is not possible and also not neccesary.

**Comment by aschempp** [comment]
> AFAIK, Vienna and Berlin had different time zones on June 1st, 1945 for example. A conversion is not possible 

What timezone was `CET` on June 1st, 1945? 😝 

> and also not neccesary.

agreed 😉

**Comment by ausi** [comment]
> What timezone was `CET` on June 1st, 1945? 😝

AFAIK, `CET` was always defined as `UTC+1` so it never changed. Btw. Vienna and Berlin use `CEST` in summer, not `CET` 🤓
