### ISSUE TITLE
Description Recreate the XML files in Maintenance

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#4172]
### Affected version(s)

Version 4.13.0

### Description

The description of ``Recreate the XML files`` in Maintenance (``Recreates the XML files (sitemaps and feeds) and then purges the shared cache, so there are no links to deleted resources.``) mentions sitemaps although since 4.11 these are generated dynamically and stored in the shared cache.

**Comment by fritzmg** [comment]
Imho this does not need to be changed. From the outside the effect is the same.

**Comment by leofeyer** [comment]
Also, the feed XML files are still generated and stored in `web/share`, therefore the description is correct.

**Comment by Total-Reality** [comment]
> Also, the feed XML files are still generated and stored in `web/share`, therefore the description is correct.

I don't know if I do sth. wrong, but the XML files are not stored in the web/share folder anymore - 4.12 & 4.13
I recreated them via Maintenance.

**Comment by ausi** [comment]
> the XML files are not stored in the web/share folder anymore

Correct. The sitemap is available over HTTP now via `/sitemap.xml`.

**Comment by Total-Reality** [comment]
However then @Mynyx is right, the text in system maintenance should be changed.

_Schreibt die XML-Dateien (**Sitemaps**/Feeds) neu und leert anschließend den Shared-Cache, damit keine ungültigen Links zurück bleiben._

This suggests that you can still regenerate the sitemap, which is no longer possible. So this is a pointless call to action.

**Comment by fritzmg** [comment]
> This suggests that you can still regenerate the sitemap, which is no longer possible.

That is not true. It _does_ regenerate the sitemap (through clearing the shared cache).

**Comment by Total-Reality** [comment]
I don't understand this. I thought the sitemap is only genereted on the fly (if you open the sitemap URL)?

**Comment by fritzmg** [comment]
It is stored in the [HTTP Cache](https://symfony.com/doc/current/http_cache.html) of [Symfony's reverse proxy](https://symfony.com/doc/current/http_cache.html#symfony-reverse-proxy), like any other response. It will only be generated again, if no valid entry for that URL already exists in the cache.

**Comment by aschempp** [comment]
but then again isn't that exactly the same as "deleting the HTTP cache"? So why do we have/need two options?

**Comment by fritzmg** [comment]
Not sure what you mean, we still need the option to regenerate the XML files (and it still needs to invalidate the shared cache as well) and we still need the option to invalidate the shared cache independently from that.

**Comment by leofeyer** [comment]
It costs more time to keep discussing this than to replace _sitemaps and feeds_ with _feeds_, therefore I am opening this issue again.

**Comment by fritzmg** [comment]
If you remove _sitemaps_ from the description it will from then on be an undisclosed side effect. How is that better and more clear?

**Comment by Total-Reality** [comment]
> It is stored in the [HTTP Cache](https://symfony.com/doc/current/http_cache.html) of [Symfony's reverse proxy](https://symfony.com/doc/current/http_cache.html#symfony-reverse-proxy), like any other response. It will only be generated again, if no valid entry for that URL already exists in the cache.

I can't reproduce this. There is nothing cached. The sitemap.xml is regenerated always while calling the url www.example.com/sitemap.xml

**Comment by fritzmg** [comment]
Did you test without a back end login (or any other Cookies) and without using the debug mode?

**Comment by Total-Reality** [comment]
Yes, I opened the sitemap in Firefox. 
Backend = Chrome.

Btw. I also use 4.13.0

**Comment by fritzmg** [comment]
You can look at the `Contao-Private-Response-Reason` response header in order to figure out why there was no cache hit.

**Comment by Total-Reality** [comment]
I really don't know what you're talking about, but if you are right that this sitemap is cached normally the description shouldn't be changed.

**Comment by aschempp** [comment]
> If you remove _sitemaps_ from the description it will from then on be an undisclosed side effect. How is that better and more clear?

The side effect is that the HTTP cache is cleared, so if we _would_ need to add something its not _sitemap_ 😉

**Comment by Mynyx** [comment]
> but then again isn't that exactly the same as "deleting the HTTP cache"? So why do we have/need two options?

In relation to the sitemap, it is actually exactly the same. The option is only needed for (rss/atom) feeds.

Therefore, it also argues for an adjustment of the description that the advantage of the new dynamic sitemaps is apparent for users. Thanks to the automatic shared cache tags invalidation after changes, the sitemap usually no longer needs to be regenerated in maintenance.
