### ISSUE TITLE
Disable picker for disabled field

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#4173]
### Affected version(s)

4.13.0

### Description

If a field is disabled, a page picker for the field can still be used and is not disabled.

E. g. edit page -> ``Canonical URL`` -> ``Custom URL`` if ``Enable rel="canonical"`` is disabled in root page.

**Comment by aschempp** [comment]
I can confirm this in the online demo. Not sure if we should remove the wizard, or simply hide both fields if canonical URLs are not enabled? @Toflar

**Comment by Toflar** [comment]
I think this is a bug with the picker wizard. Any field can be disabled, not just the canonical ones.
We could simply check for `disabled` here https://github.com/contao/contao/blob/ed4ad4868b28b229830521292af37e222a5f62ed/core-bundle/src/Resources/contao/classes/DataContainer.php#L610?

**Comment by aschempp** [comment]
also, how does datepicker and colorpicker behave in this case?

**Comment by Toflar** [comment]
They are always shown too just like the picker. So it's actually consistent at the moment (doesn't make it any better though).

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4225

**Comment by bennyborn** [comment]
Actually the implemented solution presents us with a small problem. 

We have a textfield which contains an API key. This key is generated automatically and cannot be changed. We used the wizard to open a popup where this key is integrated in an example snippet of how a config file should look. With this fix the wizard is now gone :\ 

Surely that's an edge-case but maybe we could discuss an eval option to force the wizard to be visible regardless if the field is readonly or disabled?

**Comment by aschempp** [comment]
You should use the help wizard for that, not the picker.

**Comment by fritzmg** [comment]
Why the help wizard?

You should use the `fields.<FIELDS>.wizard` callback for that imho. Unfortunately that won't help in this case as the check for `disabled`/`readonly` comes _after_ the callback. May be we can adjust that, so that you can force your own wizard, regardless of `disabled` or `readonly`.

**Comment by bennyborn** [comment]
> You should use the `fields.<FIELDS>.wizard` callback for that imho. 

That's exactly what we already do :)

> Unfortunately that won't help in this case as the check for `disabled`/`readonly` comes _after_ the callback. May be we can adjust that, so that you can force your own wizard, regardless of `disabled` or `readonly`.

Correct. Would be nice if "custom" wizards could decide for themself if they should be visible or not.

**Comment by fritzmg** [comment]
I agree. Please create a separate issue for that though (or preferably a PR directly), since the original issue was not about custom wizards.

**Comment by aschempp** [comment]
you are using `wizard`, you should use `helpwizard` 😉 https://docs.contao.org/dev/reference/dca/fields/#explanation

**Comment by fritzmg** [comment]
> you are using `wizard`, you should use `helpwizard` 😉 https://docs.contao.org/dev/reference/dca/fields/#explanation

The help wizard is for explanations, not for picking things. Why would you use the help wizard for that?

**Comment by bennyborn** [comment]
> The help wizard is for explanations, not for picking things.

It's actually not about picking things. It's just about showing an explanation tailored to the value of the field. This is something that is not possible when using a `helpWizard` iirc.

**Comment by aschempp** [comment]
> It's just about showing an explanation tailored to the value of the field. This is something that is not possible when using a helpWizard iirc.

yeah I guess that's true. But that feels like a separate issue from the picker being disabled

**Comment by fritzmg** [comment]
> This is something that is not possible when using a helpWizard iirc.

It would be possible with a combination of a `xlabel` callback and an `onload` callback. Via the `xlabel` callback you adjust the help wizard URL to include additional parameters based on the widget's value and the `onload` callback adjusts the DCA accordingly. Not the most elegant solution though. For Contao 5.x we should probably make the help wizard pop up more flexible.
