### ISSUE TITLE
Missing label translation in theme module

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/contao#4180]
### Affected version(s)

4.13

### Description

If you sort modules by type the parent labels are missing translation. can confirm in contao demo

![image](https://user-images.githubusercontent.com/1027521/154844375-01048368-a42a-49af-ad00-68600afe9121.png)

**Comment by fritzmg** [comment]
That has always been the case in Contao (including Contao 3, possibly Contao 2 as well), not just in Contao 4.13.

**Comment by aschempp** [comment]
That still makes it a bug though? 😂

**Comment by fritzmg** [comment]
🤷 If you use translations there then the groupings will potentially differ between each language. Not sure if that's desired?

**Comment by aschempp** [comment]
It's grouping by module type, if two modules have the same name that would be another issue in the first place 🤷 
but sorting by translated label is hard(er) because it can't be done in the database – not sure that's really necessary though.

**Comment by fritzmg** [comment]
But that is what we are talking about here? Or do you want to keep grouping (and sorting) by the actual type, but display the translations? That would be really confusing, as the order would potentially not be alphabetical anymore.

**Comment by leofeyer** [comment]
> 🤷 If you use translations there then the groupings will potentially differ between each language. Not sure if that's desired?

I think it is not. That‘s why we have not translated the types IIRC.

> but sorting by translated label is hard(er) because it can't be done in the database

Yes, that is another reason why we are not doing it yet.

**Comment by Tastaturberuf** [comment]
> That has always been the case in Contao (including Contao 3, possibly Contao 2 as well), not just in Contao 4.13.

I actually never noticed this 🙈 maybe we can show the translation additional: 
- `articlelist - Artikelliste` 
- `articlelist [Artikelliste]`
- ...

**Comment by aschempp** [comment]
@Tastaturberuf would you be up for a pull request? 🙃

**Comment by fritzmg** [comment]
Actually - in 4.9 the translated labels are shown, so I was wrong about it always being this way.

**Comment by aschempp** [comment]
> Actually - in 4.9 the translated labels are shown, so I was wrong about it always being this way.

I just tested this in Contao 3.5, 4.4, 4.7 and 4.9, it was never translated. Still could be improved though.
