### ISSUE TITLE
TinyMCE context menu

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#4181]
### Affected version(s)

4.13.0

### Description

TinyMCE replaces the standard context menu of the browser with an own one.

Thus, the standard options such as Undo, Copy, Paste, Spell Checker and others are not available.

The TinyMCE context menu only contains an option to set links, but this function would also be directly available via the button in the toolbar.

It would therefore seem more useful if the standard context menu were retained.

**Comment by fritzmg** [comment]
https://www.tiny.cloud/docs/ui-components/contextmenu/

Use `Ctrl + Right Click`.

**Comment by Mynyx** [comment]
Personally, I use the keyboard shortcuts directly. For inexperienced users, the solution via CTRL is probably not helpful.

Not only for links, but also in tables the TinyMCE context menu has no relevant advantage, because there is already an overlay menu displayed when the cursor is moved in the table:
![image](https://user-images.githubusercontent.com/1632642/154848714-d45ad562-d091-414b-8655-e1d6cf88d41f.png)

**Comment by fritzmg** [comment]
You can bring that up here: https://github.com/tinymce/tinymce/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md

**Comment by bennyborn** [comment]
+1 from me. Absolutely bad UX to replace the context menu as we always tell the users to insert copied texts (e.g from Word documents) using CTRL+SHIFT+V or right click and choose "Insert without formatting". 

IMHO Contao should set the `contextmenu` option to `false` in order to restore the default (see https://www.tiny.cloud/docs/ui-components/contextmenu/)

**Comment by fritzmg** [comment]
> as we always tell the users to insert copied texts (e.g from Word documents) using CTRL+SHIFT+V or right click and choose "Insert without formatting".

You can also enable `paste_as_text`.

https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_as_text

**Comment by bennyborn** [comment]
> You can also enable `paste_as_text`.

I know but this would require us to create a custom Tiny template for every Contao installation which isn't really practical.
Rather than modifying every installation we like to tell our customers how to do it the "right" way 😉

**Comment by fritzmg** [comment]
Not sure if we really should enable this particular feature in Contao 4.x, as this option has been available in all TinyMCE (and Contao) versions and it was never enabled by default.

Contrary to the new context menu, which is new.

**Comment by bennyborn** [comment]
> Not sure if we really should enable this particular feature in Contao 4.x, as this option has been available in all TinyMCE (and Contao) versions and it was never enabled by default.

Absolutely not as this would break copying contents from one element to another.

> Contrary to the new context menu, which is new.

Which I still think should be disabled by Contao.

Not only are we losing such functionality as "Insert without formatting" but we also mess with any extensions the user might have installed for accessibility reasons. I can imagine the "default" context menu might provide an extra option to read the text or smth like that.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to disable the context menu by default.
