### ISSUE TITLE
TinyMCE missing translations

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#4182]
### Affected version(s)

4.13.0

### Description

In the TinyMCE context menu the translation of "Open link" is missing.
![image](https://user-images.githubusercontent.com/1632642/154847762-50308dae-4be7-4da4-ac49-8edb7823d983.png)

Also in the menu Table in the submenu Column translations are missing:
![image](https://user-images.githubusercontent.com/1632642/154849053-bab929d0-0940-4f32-9f75-a9456586138d.png)

Further, in the menu Format "Line height".

**Comment by aschempp** [comment]
Are you sure we are providing these translations? Aren't they supplied by TinyMCE itself?

**Comment by fritzmg** [comment]
The language packs in contao-components/tinymce4 may be need to be updated.

**Comment by leofeyer** [comment]
@Mynyx Please create the issue in the https://github.com/contao-components/tinymce4 repo. I cannot transfer the issue to another organization, otherwise I would have done that for you.

**Comment by Mynyx** [comment]
See https://github.com/contao-components/tinymce4/issues/2
