### ISSUE TITLE
There is currently no session available.

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#4185]
### Affected version(s)

4.13.0, 5.x

### Description

After creating and saving a news element, I can no longer access the "News" section in the backend. The following error occurs:

```
Symfony\Component\HttpFoundation\Exception\SessionNotFoundException:
There is currently no session available.

  at vendor/symfony/http-foundation/RequestStack.php:126
  at Symfony\Component\HttpFoundation\RequestStack->getSession()
     (vendor/symfony/security-core/Authentication/Token/Storage/UsageTrackingTokenStorage.php:89)
  at Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage->getSession()
     (vendor/symfony/security-core/Authentication/Token/Storage/UsageTrackingTokenStorage.php:44)
  at Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage->getToken()
     (vendor/symfony/security-core/Authorization/AuthorizationChecker.php:70)
  at Symfony\Component\Security\Core\Authorization\AuthorizationChecker->isGranted('ROLE_USER', null)
     (vendor/symfony/security-core/Security.php:63)
  at Symfony\Component\Security\Core\Security->isGranted('ROLE_USER')
     (vendor/contao/core-bundle/src/EventListener/PrettyErrorScreenListener.php:87)
  at Contao\CoreBundle\EventListener\PrettyErrorScreenListener->handleException(object(ExceptionEvent))
     (vendor/contao/core-bundle/src/EventListener/PrettyErrorScreenListener.php:79)
  at Contao\CoreBundle\EventListener\PrettyErrorScreenListener->__invoke(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(ExceptionEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (vendor/symfony/http-kernel/HttpKernel.php:213)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable(object(SessionNotFoundException), object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:106)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException(object(SessionNotFoundException), object(Request))
     (vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php:131)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}(object(SessionNotFoundException))
     (vendor/symfony/error-handler/ErrorHandler.php:607)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException(object(SessionNotFoundException))
```

All other sections work fine. Then if I create and save a new event in a calendar, the same thing happens. I will no longer be able to access the "Events" section in the back end (i.e. I can no longer acess "News" and "Events" at that point). This happens under PHP 7.4 as well as 8.1.

The error is unfortunately not reproducible in the Contao Online Demo.

**Comment by aschempp** [comment]
Can you check what version of `symfony/csrf` you have installed (`composer show symfony/csrf`)?

**Comment by fritzmg** [comment]
You mean `symfony/security-csrf`? `5.4.3` in 5.x and 4.13. I can also ask the user with the same problem on the community forum, though I strongly suspect it's the same version.

Btw. the same error also seems to occur in the kernel.terminate event, likely caused by the command scheduler:

<img src="https://user-images.githubusercontent.com/4970961/155160822-f4411530-af05-4c7c-b02d-0a9787a6c0a8.png" width="320">

**Comment by fritzmg** [comment]
> [leofeyer](/leofeyer) added the [ unconfirmed ](/contao/contao/labels/unconfirmed) label [4 hours ago](#event-6117249360)

@leofeyer why did you add `unconfirmed`? According to https://docs.contao.org/dev/internals/issue-workflow/ an issue is not `unconfirmed` anymore if any one of us is able to reproduce the issue?

**Comment by fritzmg** [comment]
To reproduce this all you need to do is the following:

1. Configure an RSS feed for your news.
2. Create or edit a news article.
3. Insert `{{insert_article::*}}` (replace `*` with a valid article ID) into the teaser text.
4. Save.

This is the actual stack trace of the problem:

```
#0 vendor\symfony\security-core\Authentication\Token\Storage\UsageTrackingTokenStorage.php(89): Symfony\Component\HttpFoundation\RequestStack->getSession()
#1 vendor\symfony\security-core\Authentication\Token\Storage\UsageTrackingTokenStorage.php(44): Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage->getSession()
#2 vendor\contao\contao\core-bundle\src\Resources\contao\classes\BackendUser.php(137): Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage->getToken()
#3 vendor\contao\contao\core-bundle\src\Resources\contao\dca\tl_article.php(203): Contao\BackendUser::getInstance()
#4 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\DcaLoader.php(108): include('…')
#5 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\DcaLoader.php(70): Contao\DcaLoader->loadDcaFiles(false)
#6 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php(1414): Contao\DcaLoader->load(false)
#7 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\DcaExtractor.php(380): Contao\Controller::loadDataContainer('tl_article')
#8 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\DcaExtractor.php(128): Contao\DcaExtractor->createExtract()
#9 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\DcaExtractor.php(150): Contao\DcaExtractor->__construct('tl_article')
#10 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Model.php(275): Contao\DcaExtractor::getInstance('tl_article')
#11 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Model.php(1052): Contao\Model::getUniqueFields()
#12 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Model.php(919): Contao\Model::find(Array)
#13 vendor\contao\contao\core-bundle\src\Resources\contao\models\ArticleModel.php(145): Contao\Model::findOneBy(Array, Array, Array)
#14 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php(482): Contao\ArticleModel::findByIdOrAliasAndPid('18', NULL)
#15 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\InsertTags.php(615): Contao\Controller::getArticle('18', false, true)
#16 vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\InsertTags.php(100): Contao\InsertTags->executeReplace('<p>{{insert_art...', false)
#17 vendor\contao\contao\core-bundle\src\InsertTag\InsertTagParser.php(73): Contao\InsertTags->replaceInternal('<p>{{insert_art...', false)
#18 vendor\contao\contao\core-bundle\src\InsertTag\InsertTagParser.php(47): Contao\CoreBundle\InsertTag\InsertTagParser->callLegacyClass('<p>{{insert_art...', false)
#19 vendor\contao\contao\core-bundle\src\InsertTag\InsertTagParser.php(42): Contao\CoreBundle\InsertTag\InsertTagParser->replaceInlineChunked('<p>{{insert_art...')
#20 vendor\contao\contao\news-bundle\src\Resources\contao\classes\News.php(236): Contao\CoreBundle\InsertTag\InsertTagParser->replaceInline('<p>{{insert_art...')
#21 vendor\contao\contao\news-bundle\src\Resources\contao\classes\News.php(105): Contao\News->generateFiles(Array)
#22 vendor\contao\contao\news-bundle\src\Resources\contao\dca\tl_news_archive.php(481): Contao\News->generateFeedsByArchive(1)
#23 vendor\contao\contao\core-bundle\src\Resources\contao\drivers\DC_Table.php(203): tl_news_archive->generateFeed(Object(Contao\DC_Table))
#24 vendor\contao\contao\core-bundle\src\Resources\contao\classes\Backend.php(417): Contao\DC_Table->__construct('tl_news_archive', Array)
#25 vendor\contao\contao\core-bundle\src\Resources\contao\controllers\BackendMain.php(170): Contao\Backend->getBackendModule('news', NULL)
#26 vendor\contao\contao\core-bundle\src\Controller\BackendController.php(49): Contao\BackendMain->run()
#27 vendor\symfony\http-kernel\HttpKernel.php(152): Contao\CoreBundle\Controller\BackendController->mainAction()
#28 vendor\symfony\http-kernel\HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#29 vendor\symfony\http-kernel\Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#30 public\index.php(44): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#31 public\app.php(13): require('…')
```

1. When you save news or events, this will trigger the re-generation of the XML files (the RSS feeds) on the next request.
2. During `News::generateFiles` we push a new fake request to the request stack (see https://github.com/contao/contao/pull/3857).
3. When the content of the RSS feed items is generated, insert tags for the teaser (or detail content, depending on the RSS feed settings) are replaced.
4. For the `{{insert_article::*}}` insert tag the `tl_article` DCA is then loaded.
5. Within the `tl_article` DCA `BackendUser::getInstance()->id` is accessed.
6. This will then trigger the first of many session not found exceptions.

**Comment by leofeyer** [comment]
> According to https://docs.contao.org/dev/internals/issue-workflow/ an issue is not `unconfirmed` anymore if any one of us is able to reproduce the issue?

Yes, but the confirmation must come from someone other than the one who reported the error. Just like you cannot approve your own PR. You will get the pink elephant if you try. 😉

**Comment by fritzmg** [comment]
Alright 😁

**Comment by ausi** [comment]
Can confirm the issue. After follwing the steps from https://github.com/contao/contao/issues/4185#issuecomment-1047918778 I get the error `There is currently no session available.`

**Comment by mafudelaptu** [comment]
Also happens if you want to regenerate the sitemap.xml via maintenance page in backend. :(

Contao Version: 4.13.1

**Comment by leofeyer** [comment]
I cannot reproduce this. Here is what I did:

1. I made sure that my news archive has an RSS feed.
2. I added a text element with `{{include_article::66}}` to one of the news. (Article ID 66 is an existing article.)
3. I saved my changes. No exception there.
4. I rebuilt the XML files in the maintenance module. No exception there, either.

What am I missing?

**Comment by ausi** [comment]
> 2\. I added a text element with `{{include_article::66}}`

Needs to be in the teaser text of the news AFAIR, not a text element.

**Comment by fritzmg** [comment]
~~No, it needs to be detail content. And you need to set the RSS feed to "full story".~~

nvm, that was for a different issue :) - yes the insert tag needs to be in the _teaser_.

**Comment by leofeyer** [comment]
I can reproduce this now. IMHO, we should revert #3857 to fix this.

**Comment by fritzmg** [comment]
> IMHO, we should revert #3857 to fix this.

Why? That would just introduce #3856 again. What's wrong with #4195?

**Comment by leofeyer** [comment]
Closing this in favor of #4195 then.

**Comment by fritzmg** [comment]
Unfortunately this problem still occurs in Contao 4.13. #4195 fixed the problem for recreating the XML files in the back end. But the problem will still occur in Contao 4.13 when the cronjobs are executed in `kernel.terminate`, where the request will not be available in the request stack any more.

**Reproduction:**

1. Enable the command scheduler in the system settings.
2. Follow the instructions [here](https://github.com/contao/contao/issues/4185#issuecomment-1047918778).
3. `TRUNCATE tl_cron_job`
4. Make a request to Contao anywhere (front or back end, does not matter if logged in or not).

I am unsure how to fix this. The underlying problem is the following:

1. In `kernel.terminate`, `->getCurrentRequest()` will be `null` already.
2. We are thus pushing a new empty request to the request stack.
3. `UsageTrackingTokenStorage::shouldTrackUsage` will return `true` because there is now a main request in the request stack - and usage tracking was enabled previously by Symfony's `RegisterTokenUsageTrackingPass`.
4. `UsageTrackingTokenStorage::getToken` will throw the `SessionNotFoundException` since it tries to retrieve the session from the main request - which does not have a session.

We could simply disable usage tracking when generating the news feeds, as I previously suggested (or may be even more generally in the `kernel.terminate` event). However this issue would _still_ occur if any code tries to retrieve the session from the current request, instead of using the `session` service. The latter is deprecated since Symfony 5.3 (but still available in Contao!) and thus everything should actually switch to retrieving the session from the current request instead (and also checking with `hasSession`).

Btw. this problem does not occur on the command line because there usage tracking will not be enabled (usage tracking is enabled via Symfony's `RegisterTokenUsageTrackingPass`).

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add a fake session (`MockArraySessionStorage`) to the fake request.

**Comment by k-webdesign** [comment]
I still can reproduce this in Contao 4.13.13. When I want to save a new or existing news article/element I get:

Symfony\Component\HttpFoundation\Exception\SessionNotFoundException:
There is currently no session available.

  at vendor/symfony/http-foundation/RequestStack.php:126
  at Symfony\Component\HttpFoundation\RequestStack->getSession()
     (vendor/symfony/security-core/Authentication/Token/Storage/UsageTrackingTokenStorage.php:89)
  at Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage->getSession()
     (vendor/symfony/security-core/Authentication/Token/Storage/UsageTrackingTokenStorage.php:44)
  at Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage->getToken()
     (vendor/symfony/security-core/Authorization/AuthorizationChecker.php:70)
  at Symfony\Component\Security\Core\Authorization\AuthorizationChecker->isGranted('ROLE_USER', null)
     (vendor/symfony/security-core/Security.php:63)
  at Symfony\Component\Security\Core\Security->isGranted('ROLE_USER')
     (vendor/contao/core-bundle/src/EventListener/PrettyErrorScreenListener.php:87)
  at Contao\CoreBundle\EventListener\PrettyErrorScreenListener->handleException(object(ExceptionEvent))
     (vendor/contao/core-bundle/src/EventListener/PrettyErrorScreenListener.php:79)
  at Contao\CoreBundle\EventListener\PrettyErrorScreenListener->__invoke(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(ExceptionEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ExceptionEvent), 'kernel.exception')
     (vendor/symfony/http-kernel/HttpKernel.php:223)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable(object(BadRequestHttpException), object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:86)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:44)

**Comment by fritzmg** [comment]
@k-webdesign do you have multiple stack traces in your output? I think the one you are posting is not the original problem.

**Comment by k-webdesign** [comment]
It's the only one

**Comment by k-webdesign** [comment]
<img width="1903" alt="Bildschirm­foto 2022-12-07 um 11 32 32" src="https://user-images.githubusercontent.com/4130440/206155854-c11747ff-d7b1-4701-a34f-29a08e2139c7.png">

**Comment by fritzmg** [comment]
What's the output in "Logs"?

**Comment by k-webdesign** [comment]
Phew, a lot:
[logs.txt](https://github.com/contao/contao/files/10175182/logs.txt)

**Comment by fritzmg** [comment]
Unfortunately our `PrettyErrorScreenListener` obfuscates the original error so it's hard to tell what actual error you are getting on your system without more in-depth investigation.

**Comment by k-webdesign** [comment]
Do you want to check it via Anydesk?
