### ISSUE TITLE
Improve the template for the search index crawler in maintenance

### ISSUE THREAD

**Issue by Total-Reality** [contao/contao#4187]
### Affected version(s)

4.9, 4.12, 4.13

### Description

The usability and markup of the `be_crawl.html5` template should be improved. 

1. Together with 3 people we didn't understand how to find and download the debug log @ the search index crawler.

For example we looked around in the log folder @ ftp. After hours (because we needed to crawl a page with 20.000 pages 2 times) we realized that there a very small icon on the right side of the backend.
Until this moment we really thought that there is a bug.
Together we have about about 30 years experience with Contao but probably this isn't enough 😄 👯‍♂️ 

![contao-crawler1](https://user-images.githubusercontent.com/5235894/155022014-53c74930-d60a-41d3-9fc5-2fcbb0cce8dc.png)

Additionally it is very confusing if you have errors and want to see them quickly, you read the message "wenn Sie eine URL vermissen, prüfen Sie das Debug-Log" - so you think: "okay let's download following log and have a look" - after clicking the button "Log herunterladen" and looking around in the file you don't understand the problem.
We first thought this log is the debug log!

![contao-crawler2](https://user-images.githubusercontent.com/5235894/155022017-37302391-4753-48d9-b259-a37402803e70.png)

I changed the template a little bit, but it is difficult to display both buttons side by side (because of the foreach loop).

![contao-crawler3](https://user-images.githubusercontent.com/5235894/155022019-22842bec-c3dc-44da-8397-65f26b8c2720.png)

2. `<p>` Tags around the buttons a not so useful, `<div>` Tags would be better.

I can create a PR if you want.

**Comment by Mynyx** [comment]
Absolutely agree with the usability issue. I would suggest placing the "Debug-Log herunterladen" button between the progress bar and the next headline (here "Den Suchindex aktualisieren").

**Comment by aschempp** [comment]
I agree, I did have the same issue the few times I used the crawler. I also think we can improve this in Contao 4.9 and not just Contao 5 (bug vs. feature).

**Comment by leofeyer** [comment]
How about this?

<img width="946" alt="" src="https://user-images.githubusercontent.com/1192057/173555772-894e973b-2684-4a59-a56a-72d5f82465b1.png">

@Toflar /cc

**Comment by Toflar** [comment]
LGTM
