### ISSUE TITLE
Creating a new version may result in an exception

### ISSUE THREAD

**Issue by cliffparnitzky** [contao/contao#4188]
### Affected version(s)

4.9.26

### Description

The automatic creation of a new version may result in an exception. This is the case, if the DCA has an attribute `title`, `name`, `firstname`, `headline`, `selector` or `subject` which will be used as description for the version and this field allows more than 255 characters.

This is the part, where the attribute is read: https://github.com/contao/contao/blob/5.x/core-bundle/src/Resources/contao/classes/Versions.php#L187-L223

The description field only allows 255 chars: https://github.com/contao/contao/blob/5.x/core-bundle/src/Resources/contao/dca/tl_version.php#L60

I would suggest to shorten the description value before inserting it into the database.

I can create a PR if my suggestion is okay.

**Comment by cliffparnitzky** [comment]
This may be the simplest solution: `$strDescription = substr($strDescription, 0, 255);` in line [220](https://github.com/contao/contao/blob/5.x/core-bundle/src/Resources/contao/classes/Versions.php#L220).

A bit nice would be to shorten the string only if necessary and add 3 dots at the end.

**Comment by leofeyer** [comment]
`Contao\StringUtil::substr()` will do exactly this.

**Comment by cliffparnitzky** [comment]
Sounds good. I will create the PR.

**Comment by cliffparnitzky** [comment]
Fixed with https://github.com/contao/contao/pull/4192
