### ISSUE TITLE
Missing default css classes like .first, .last

### ISSUE THREAD

**Issue by timgatzky** [contao/contao#4189]
### Affected version(s)

4.13.0

### Description

Hi guys,
in the current 4.13.0 release the default classes are missing like mod_article.first etc.

Tested on a blank installation, with one article containing two texts.

Did I miss something? Isn't that change intended to be in Contao 5 first: https://github.com/contao/contao/pull/4178

Best regards,
Tim

**Comment by fritzmg** [comment]
~I cannot reproduce. Articles still have the `mod_article` class for instance. Are you using custom templates or a `parseTemplate` hook that changes the `class` variable of templates for example?~

Oh, you only meant `first`, `last`. For articles that has already been removed in Contao 4.10. For the rest it's gonna be removed in Contao 5. See [here](https://github.com/contao/contao/blob/4.13.0/UPGRADE.md#css-classes-first-and-last).
