### ISSUE TITLE
Custom backend route prefix not used in robots.txt

### ISSUE THREAD

**Issue by michb** [contao/contao#4191]
### Affected version(s)

4.13

### Description

If you set your contao to have a custom backend route prefix, as described here https://docs.contao.org/manual/en/system/settings/#additional-back-end-settings

The disallow entry in the robots.txt is not adjusted correctly to the new route. As you can see here `contao` is hardcoded in there
https://github.com/contao/contao/blob/c904c5624e7f813980942cbf9dc5386405c0ee27/core-bundle/src/EventListener/RobotsTxtListener.php#L59

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4197
