### ISSUE TITLE
Neuer Maintenance Mode via cli: Backend nicht nutzbar

### ISSUE THREAD

**Issue by ghost** [contao/contao#4198]
### Affected version(s)

4.13.0

### Description

Wird der Wartungsmodus über das Backend am Startpunkt einer Webseite gesetzt, ist das Backend weiterhin nutzbar.
Setzt man über den cli via `vendor/bin/contao-console contao:maintenance-mode on`  den Wartungsmodus, ist das Backend nicht erreichbar, da 503. Ist das so gewollt?

**Comment by aschempp** [comment]
ja, das ist richtig so. In Contao 4.13 lässt sich jede Root-Seite einzeln in den Wartungsmodus versetzen, oder das komplette System. Der systemweite Wartungsmodus funktioniert auch dann, wenn Contao nicht mehr funktioniert, und macht dann Sinn wenn die Installation nicht lauffähig ist (z.B. bei einem Update über den Contao Manager, der den Wartungsmodus automatisch aktiviert 😉)
