### ISSUE TITLE
Console for web profiler

### ISSUE THREAD

**Issue by aschempp** [contao/contao#42]
Just found this bundle, might be useful to include, also if we don't have a full composer support in Contao 4.0.

https://github.com/winzou/ConsoleBundle

**Comment by leofeyer** [comment]
+1

However, we should make sure that this is not a security issue.

**Comment by aschempp** [comment]
Absolutely. It also only works if `assets:install` is called. But composer does that by default, so…

Feel free to assign it to me.

**Comment by aschempp** [comment]
I've played a bit with this and came up with the following results:

1. It's a pretty neat console in the browser, allowing for things like `assets:install` etc.
2. It only runs Symfony console commands, but that still allows to execute database commands etc.
3. Looks like it can't run composer commands (by default)
3. There are several design problems in the current setup that prevent this from easily working (e.g. `RequestToken` check for all POSTs)

**Conclusion:** I still think this could be neat, but only if there is no alternative to e.g. `assets:install`

**Comment by Toflar** [comment]
I guess it could be added as a feature in future, not something we need to spend time on now.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/120.
