### ISSUE TITLE
Time "01:00" o'clock at events changes to "0" when reediting the event

### ISSUE THREAD

**Issue by joehi** [contao/contao#420]
**Affected version(s)**
Contao 4.7.2
Contao 4.4.36

**Description**  
When an event has a starttime or endtime of "01:00" o'clock and after beeing saved will be opened for editing again, the value of the field will change to "0" which will cause an error when saving again.
The behaviour regarding the endtime field differs slightly between 4.7.2 and 4.4.36. Where the field will be empty in 4.7.2 eliminating the endtime completely, in 4.4.36 there will be the "0" in the field.

Temporary solution: manually change it to "01:00" again before saving.

**How to reproduce**  
Log in to the Contao Online Demo, create an event with starttime and/or endtime of 01:00 o'clock, save the event. Then open the event again for editing.

[Comment](https://community.contao.org/de/showthread.php?74533-Zeitangabe-01-00-Uhr-bei-Events-wird-beim-erneuten-Editieren-zu-0-ver%C3%A4ndert&p=500460&viewfull=1#post500460) in the German Contao forum.

**Comment by leofeyer** [comment]
Fixed in 2846b6a7d66b44380ce05d8bbf3256a54b210d3b.
