### ISSUE TITLE
Dbafs.php, int $maxFile causes Fatal Error in php7.4 32bit

### ISSUE THREAD

**Issue by Sarahsolus** [contao/contao#4200]
### Affected version(s)

4.13.0

### Description

Local System with  MampPro4 (php7.4, 32bit)
Path/contao/install causes a Fatal Error:

Compile Error: Default value for property of type int can only be int

Symfony\Component\ErrorHandler\Error\ FatalError
in PFAD\vendor\contao\core-bundle\src\Filesystem\Dbafs\Dbafs.php (line 54)

private Connection $connection;
private EventDispatcherInterface $eventDispatcher;
private string $table;
private string $dbPathPrefix = '';
**private int $maxFileSize = 2147483648; // 2 GiB**
private int $bulkInsertSize = 100;
private bool $useLastModified = true;
/**
* @var array<string, array|null>

Solution:

I changed

private int $maxFileSize = 2147483648; // 2 GiB

to

private int $maxFileSize = 2147483647; // 2 GiB

Recording to the [PHP documentation](https://www.php.net/manual/de/language.types.integer.php)  this is the highest possible int number in the 32bit version.

**Comment by fritzmg** [comment]
Indeed, this should be changed to

```php
min(PHP_INT_MAX, 2147483648);
```

/cc @m-vo

**Comment by fritzmg** [comment]
Although that would probably fail on 32-bit too.. 🤔  May be

```php
$this->maxFileSize = PHP_INT_SIZE >= 8 ? 2147483648 : PHP_INT_MAX;
```

instead?

**Comment by m-vo** [comment]
> Indeed, this should be changed to
>
> min(PHP_INT_MAX, 2147483648);

That would basically be the same as `$value = (int) 2147483648;`. 

We could also make this property a float or use a smaller default. This probably depends on the question whether we are fine with 32bit versions having limitations for the sake of type safe comparisons everywhere else.

**Comment by m-vo** [comment]
Btw.: this only affects property initializers that do not coerce values. You can safely assign a default value in the constructor https://3v4l.org/kTmBS#v8.1.3.

**Comment by ausi** [comment]
> or use a smaller default

👍 We should use something like this IMO:

```php
private int $maxFileSize = 2147483647; // 2 GiB - 1 byte
```

**Comment by m-vo** [comment]
see #4208
