### ISSUE TITLE
Missing size-Label in News

### ISSUE THREAD

**Issue by LIVID-Media** [contao/contao#4201]
### Affected version(s)

4.13

### Description

By adding a picture to a news entry the size label and tip are missing:

![Contao 4 13 News](https://user-images.githubusercontent.com/61419192/155298839-cbabd144-a062-41e5-8b91-0f7a10cfa8c1.png)

**Comment by fritzmg** [comment]
I can confirm the issue. This bug was introduced with https://github.com/contao/contao/pull/3912

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4202
