### ISSUE TITLE
ModuleArticle: Attempt to read property "datimFormat" on null

### ISSUE THREAD

**Issue by Xirdion** [contao/contao#4205]
### Affected version(s)

4.13.0

### Description

If there is a content element of type `article` referencing another article, there will be an error in dev-mode when showing the list view of the content elements.

The problem occurs because contao tries to render / compile the content element.
But `vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php` tries to access some properties of the global `$objPage`. But the page is null (backend view).

As a workaround the `compile` function could check if `$objPage` is given:

```php
$this->Template->date = $objPage ? Date::parse($objPage->datimFormat, $this->tstamp) : (new \DateTimeImmutable())->format('d.m.Y H:i');
```

![image](https://user-images.githubusercontent.com/17783055/155328339-9153343d-9c57-4e10-a42d-58c4d465a64f.png)

**Comment by bezin** [comment]
I unterstood you included an article within another article via the Article include element. That said, I cannot reproduce your issue. 
However I do not understand how the ModuleArticle you referenced in screenshot and code would be triggered in that scenario?

@Xirdion Could you please provide the stack trace?

**Comment by Xirdion** [comment]
@bezin here is the stack trace
```
ModuleArticle.php:125, Contao\ModuleArticle->compile()
Module.php:216, Contao\Module->generate()
ModuleArticle.php:72, Contao\ModuleArticle->generate()
Controller.php:540, Contao\Controller::getArticle()
ContentArticle.php:27, Contao\ContentArticle->generate()
Controller.php:612, Contao\Controller::getContentElement()
tl_content.php:1342, tl_content->addCteType()
DC_Table.php:4623, Contao\DC_Table->parentView()
DC_Table.php:315, Contao\DC_Table->showAll()
Backend.php:655, Contao\Backend->getBackendModule()
BackendMain.php:170, Contao\BackendMain->run()
BackendController.php:49, Contao\CoreBundle\Controller\BackendController->mainAction()
HttpKernel.php:152, Symfony\Component\HttpKernel\HttpKernel->handleRaw()
HttpKernel.php:74, Symfony\Component\HttpKernel\HttpKernel->handle()
Kernel.php:202, Symfony\Component\HttpKernel\Kernel->handle()
index.php:44, {main}()
```

I hope it will help you.

**Comment by bezin** [comment]
Thanks, that helped, I can confirm that. I'll take care of it.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4210
