### ISSUE TITLE
Inconsistent onsubmit_callback behavior

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#4206]
The `onsubmit_callback` in the back end is called **before** a new version is created, however, in the front end, it is called **after** a new version is created.

https://github.com/contao/contao/blob/da55d19ac91a529da80453adb299a67ae8c2fabc/core-bundle/src/Resources/contao/drivers/DC_Table.php#L2105-L2137

https://github.com/contao/contao/blob/da55d19ac91a529da80453adb299a67ae8c2fabc/core-bundle/src/Resources/contao/modules/ModulePersonalData.php#L324-L349

This implies that changes made via `onsubmit_callback` will be versioned in the back end but not in the front end. 😞 

@contao/developers I think we should fix this in Contao 4.9+, shouldn't we?

**Comment by aschempp** [comment]
I agree, we should move it in the front end. Looks like the record is saved even if `$blnDotNotSubmit` is true in the personal data module?
