### ISSUE TITLE
HTML validation: Attribute width not allowed on element source at this point.

### ISSUE THREAD

**Issue by math-GH** [contao/contao#4209]
### Affected version(s)

contao.org (unknown version)

### Description

https://contao.org/de/news.html?year=2022 does not validate with the W3C validator:

see: https://validator.w3.org/nu/?doc=https%3A%2F%2Fcontao.org%2Fde%2Fnews.html%3Fyear%3D2022

Error: Attribute width/height not allowed on element source at this point.

![grafik](https://user-images.githubusercontent.com/1645099/155391491-d7ae8133-c664-45e6-8f1c-5dd07ab2b6b1.png)

**Comment by fritzmg** [comment]
See https://github.com/contao/contao/issues/2746

The W3C validator still has not been updated to the latest HTML specs.
