### ISSUE TITLE
Access protection on Website root returns Internal Server Error

### ISSUE THREAD

**Issue by giodi** [contao/contao#4211]
### Affected version(s)

4.13.0

### Description

When I use the "Protect page" option on the page type "Website root" a Internal Server Error is returned:

![grafik](https://user-images.githubusercontent.com/7964115/155498676-d0775b38-1864-4c97-96f9-819e40b06ab9.png)

**Steps to reproduce on demo:**
- Activate "protect page" option on website root.
- Choose a member group which is not "Guests".
- Click on "preview".

In my experience in the prior LTS version with this configurations it redirected to the 401 Page.

**Comment by fritzmg** [comment]
I can confirm the problem.

**Comment by aschempp** [comment]
how can we render the 401 page if its parent root is protected (and therefore the 401 would be protected as well)? Why would it ever make sense to protect a root page?

**Comment by giodi** [comment]
@aschempp We use this when we want to give access to a preview version of the website to our clients. The alternative would be to protect every page on the first level, which can be a lot. So for me it isn't about protecting the root page (I see that this makes no sense) but about protecting all pages and have to set this only once.

**Comment by fritzmg** [comment]
> Why would it ever make sense to protect a root page?

We have that exact use case and it works in Contao 4.9.

> how can we render the 401 page if its parent root is protected (and therefore the 401 would be protected as well)? 

Why does it work in Contao 4.9 (and all previous Contao versions)?  I do not want to protect each individual page of a domain that is only accessible via member login. I want to set the protection in the website root.

**Comment by aschempp** [comment]
If you want a client to preview the page, why not unpublish it and use a preview link? 😎

**Comment by fritzmg** [comment]
> If you want a client to preview the page, why not unpublish it and use a preview link? 😎

That's not our use case. Our client runs a website that is only accessible via front end login.

**Comment by fritzmg** [comment]
> how can we render the 401 page if its parent root is protected (and therefore the 401 would be protected as well)?

That's a moot point I think, since system pages like the 401 page are not routable and not rendered like a normal page in any case. They are rendered in their respective circumstances. Besides, you cannot protect 401, 403 or 404 pages (the setting does not exist).

**Comment by giodi** [comment]
> If you want a client to preview the page, why not unpublish it and use a preview link? 😎

In my viewpoint there is a lot less flexibility in that:

- Sometimes the client needs to see just certain parts of the site (e.g. the marketing department can see only a few pages, the executive board has access to all pages) while the public has still no access.
- When only a few sites should be seen for one group I would have to generate _n_ Links to provide the same functionality.
- When I unpublish the website root and e.g. the generated preview link expired, I land on the default 404 error page (since the customized error page is also unpublished) which can be irritating for the client.

**Comment by giodi** [comment]
> If you want a client to preview the page, why not unpublish it and use a preview link? 😎

In my viewpoint there is a lot less flexibility in that:

- Sometimes the client needs to see just certain parts of the site (e.g. the marketing department can see only a few pages, the executive board has access to all pages) while the public has still no access.
- When only a few sites should be seen for one group I would have to generate _n_ Links to provide the same functionality.
- When I unpublish the website root and e.g. the generated preview link expired, I land on the default 404 error page (since the customized error page is also unpublished) which can be irritating for the client.

**Comment by aschempp** [comment]
> I land on the default 404 error page (since the customized error page is also unpublished) which can be irritating for the client.

That's a good point as well, isn't it? Would you expect the (protected) 404 to be rendered?

---

I can confirm the problem out of my head, I know why that is happening. We switched from rendering the `Page` class to actually using the controller when rendering an error page. And the controller checks access permissions (which is correct imho).

I think we should discuss whether we want to allow this or if there are other options.

**Comment by aschempp** [comment]
~Btw, if you place the 401 page _inside_ another protected page, wouldn't you have the same issue?~

Nevermind, you can/should only place error page below the root page 😅

**Comment by fritzmg** [comment]
> And the controller checks access permissions (which is correct imho).

But that's wrong, you cannot set access protection on 401, 403 and 404 pages. It wouldn't make sense to do so, since these are system pages that need to be rendered in their respective use cases.

**Comment by aschempp** [comment]
> But that's wrong, you cannot set access protection on 401, 403 and 404 pages. It wouldn't make sense to do so, since these are system pages that need to be rendered in their respective use cases.

Yes, but they currently inherit them. So we would need to figure out a way for `loadDetails` to not inherit protection settings for specific page types. Sounds difficult to me 🙊

**Comment by fritzmg** [comment]
But it already works in Contao 4.9?

**Comment by leofeyer** [comment]
As discussed in the Contao Call, the `PrettyErrorScreenListener` should set `$model->protected = false` when rendering an error page.
