### ISSUE TITLE
Problem beim Synchronisieren

### ISSUE THREAD

**Issue by Wedego** [contao/contao#4215]
### Affected version(s)

4.13

### Description

Contao 4.13 Update problemlos
PHP 7.4.27
BE und FE OK
Im BE Klick auf Synchronisieren und Internal Server Error 
` An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xE4hrige...' for column `txbittel_`.`tl_files`.`path` at row 1`
Was kann man tun?

**Comment by Wedego** [comment]
Das steht in Log:
` An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xE4hrige...' for column `mvbittel_`.`tl_files`.`path` at row 1 at /var/www/vhosts/domain.de/httpdocs/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:119)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1366): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xE4hrige...' for column `mvbittel_`.`tl_files`.`path` at row 1 at /var/www/vhosts/domain.de/httpdocs/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xE4hrige...' for column `mvbittel_`.`tl_files`.`path` at row 1 at /var/www/vhosts/domain.de/httpdocs/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:101)"} []`

**Comment by ausi** [comment]
@m-vo in the old Dbafs we skipped syncing non-UTF-8 in 6d4f9a3e2205e1041c9625bb57a34928a1ce76dc.
If we add this skip to the new implemenation we should IMO trigger a deprecation there and don’t support that anymore in Contao 5.0.

@Wedego there seems to be a file or directory that contains the string `ährige` with the `ä` being not encoded as UTF-8. If you rename that file/folder to `aerige` the issue should disappear.

**Comment by Wedego** [comment]
Hallo ausi, danke, dann suche ich mal diese Datei oder Verzeichnis. 
ährige gibt es viele in den Texten z,B, 50jährige Jubiläum usw. 
Mal sehen, ich sage schon mal Danke und reporte das Ergebnis

**Comment by Wedego** [comment]
Manchmal braucht man(n) auch mal einen Stoß in die Rippen.
Seit 2 Tagen suche ich diesen String vergeblich, jetzt habe ich endlich 2 Dateien (jpg) mit "ä" gefunden.
"60-Jähriges Bestehen.jpg" und "Ständchen Kaupp 1989"
Mann oh Mann, Dankeschön

**Comment by m-vo** [comment]
I can confirm the error.

**Comment by fritzmg** [comment]
> If we add this skip to the new implemenation we should IMO trigger a deprecation there and don’t support that anymore in Contao 5.0.

Not sure that's good for the user experience. Usually this happens when you simply copy files between different filesystems.

**Comment by m-vo** [comment]
see #4216 

@fritzmg let's discuss this over at the linked PR :slightly_smiling_face:

**Comment by Wedego** [comment]
Der Hinweis an markanter Stelle zu Umlauten sollte IMO reichen. Damit kann man leben.
Ob Überspringen gut ist weis ich nicht genau.

**Comment by m-vo** [comment]
@Wedego Umlaute sind kein Problem, es betrifft nur Zeichen, die nicht als UTF-8 kodiert sind.

**Comment by Wedego** [comment]
Hi, die UTF-8 kodierung findet doch Systemintern statt oder irre ich da?

**Comment by m-vo** [comment]
> Hi, die UTF-8 kodierung findet doch Systemintern statt oder irre ich da?

Ich weiß nicht was du meinst? UTF-8 ist eine [Kodierung](https://de.wikipedia.org/wiki/Zeichenkodierung), also eine Konvention als welches Zeichen die vorliegende Bitfolge interpretiert wird.

**Comment by Wedego** [comment]
Kodierung ist schon klar, ich dache wenn es z.B. ein "ä" Unmlaut in einer Datei gibt wird das automatisch in UTF8 kodiert.

**Comment by m-vo** [comment]
Was heißt "ä"? Das ist ja bereits eine interpretierte Kodierung.

**Comment by Wedego** [comment]
Wenn aus z.B. einem "ä" in der DB ein "\\XCirgendwas wird warum auch immer, hat die Kodierung nicht funktioniert.
Aber wir reden wohl aneinander vorbei.

**Comment by fritzmg** [comment]
@Wedego this error can happen if you copy files between different filesystems.

**Comment by Wedego** [comment]
Yes, This error can appear when you copy files between different file systems.
Yes, that's probably how the actual error came about.

**Comment by Wedego** [comment]
Actually, in my case, two systems are excluded.
That's surprising. There were several files with umlauts and only two had the problem.

**Comment by ausi** [comment]
> Not sure that's good for the user experience.

Which one would be bad experience? 
Skipping non-utf-8 files and directories? (this is already the case in Contao 4.12-)
Or throwing an exception in Contao 5?
