### ISSUE TITLE
Benutzergruppen: Erlaubte Datei-Operationen: Fehler in den Option-Values

### ISSUE THREAD

**Issue by trilobit-gmbh** [contao/contao#422]
**Affected version(s)**
Contao 4.4.32

**Description**  
Werden Benutzerrechte nur über Benutzergruppen vergeben, haben die Einstellungen der "Erlaubte Datei-Operationen" keine Auswirkung auf die Verfügbaren Rechte in der Dateiverwaltung.
Werden die Rechte "Erlaubte Datei-Operationen" direkt beim Benutzer eingestellt greifen die Einstellungen.
Ursache sind falsche Options-Werte bei den Gruppen-Einstellungen.

Beispiel: "Dateien auf den Server hochladen"

*richtig* - unter den Benutzerrechten: in diesem Bspl. **value="f1"** 
```
<input type="checkbox" name="fop[]" id="opt_fop_0" class="tl_checkbox" value="f1" checked="" onfocus="Backend.getScrollOffset()">
```

*falsch* - unter den Gruppenrechten: in diesem Bspl. **value="1"** für die selbe Option
```
<input type="checkbox" name="fop[]" id="opt_fop_0" class="tl_checkbox" value="1" checked="" onfocus="Backend.getScrollOffset()">
```

**How to reproduce**  
Rechte der "Erlaubte Datei-Operationen" über eine Benutzergruppe setzen: Fehler
Rechte der "Erlaubte Datei-Operationen" über den Benutzer selbst setzen: OK

**Comment by leofeyer** [comment]
Ich kann das Problem nicht reproduzieren. In der Datei `tl_user_group.php` sind auch die korrekten Optionen eingetragen:

https://github.com/contao/contao/blob/ff3275640a94cb749a9b5b16b0fdcd36889486e7/core-bundle/src/Resources/contao/dca/tl_user_group.php#L167-L177

Könnte es an einer Erweiterung liegen?

**Comment by trilobit-gmbh** [comment]
Hallo, vielen Dank für die Mühen.
Ich habe den "Fehler" ;-) gefunden; verstehe ihn aber noch nicht ;-(.

Es liegt an unserem Pixabay-Bundle. Dieses ergänzt eine Option im Berechtigungsschema:
```
$GLOBALS['TL_DCA']['tl_user_group']['fields']['fop']['options']['pixabay'] = 'pixabay';
```

Wenn die neue Option assoziativ ist tritt der Fehler auf.
Hänge ich den neuen Optionswert einfach nur an
```
$GLOBALS['TL_DCA']['tl_user_group']['fields']['fop']['options'][] = 'pixabay';
```
passen die übrigen Optionen wieder.

Danke für die Mühen; Entschuldigung für die unnötige Arbeit hier. Ich habe mir einen eigenen Issue aufgemacht...
