### ISSUE TITLE
Registrierung

### ISSUE THREAD

**Issue by GabysInstitut** [contao/contao#4222]
### Description

Es wäre ein grosser Vorteil, wenn man die Registrierungsseite so gestalten könnte wie die Formularseite.

Sprich (Pflicht)felder selbst aussuchen, eigene Werte etc. welche dann bei den Mitgliedern im BE editierbar sind.

Jeder der Mitglieder hat, hat auch eigene Belange. Immer!

Wenn das nicht machbar ist, wäre schon mal ein Vorteil, die bestehenden Felder Pflichtfeld ja/nein auswählen zu können.

**Comment by aschempp** [comment]
I would like to see this too, but as soon as you edit a member in the back end, you will run into issues if some of the registration fields were not mandatory but are in the back end. The only correct solution I can think of is to correctly configure the DCA – which will then also configure the registration module.
https://docs.contao.org/dev/getting-started/dca/
