### ISSUE TITLE
Options Callback wird im Debug Modus nicht ausgeführt

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#4223]
### Affected version(s)

4.13.0

### Description

Ein Options Callback, welcher über einen Listener mit Callback Annotation (`Callback(table="tl_member", target="fields.group_select.options")`) angelegt ist, wird im Debugmodus weder im FE noch im BE ausgeführt. Cache wurde mehrmals geleert, im Prod Modus funktioniert alles.

**Comment by fritzmg** [comment]
That seems more like a support question than a bug report (there is no`tl_member.group_select` in Contao). Please use the Contao community forum for that.

**Comment by theDyingMountain** [comment]
`group_select` is the name of my own field. See here https://docs.contao.org/dev/reference/dca/callbacks/#fields-field-options
In Production Mode everything works fine.

**Comment by fritzmg** [comment]
> In Production Mode everything works fine.

Please post on the community forum and provide more information about your field and the way you configured your registration form (or whichever front end module is involved).

**Comment by theDyingMountain** [comment]
Here is the link: [https://community.contao.org/de/showthread.php?82611-Options-Callback-wird-im-Debugmodus-nicht-ausgef%C3%BChrt&p=555721#post555721](https://community.contao.org/de/showthread.php?82611-Options-Callback-wird-im-Debugmodus-nicht-ausgef%C3%BChrt&p=555721#post555721)
