### ISSUE TITLE
Element restriction by layout part for user groups/ users 

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#4238]
### Description

Content elements should not be restricted **in general** but **by layout area** (header, main, right column, ... ). 

For example, a user can only use the text element in the right column, but all elements in the main column.

**Comment by aschempp** [comment]
we've had a similar feature in `ce-access`, to limit elements between pages and content elements. However we agreed on this being a very specific use case that could be added by an extension, and the core would only support the default access (like now). 

@contao/developers should we close this feature request accordingly?
