### ISSUE TITLE
Why <strong> hard coded in nav_default model for li.active ?

### ISSUE THREAD

**Issue by JLBA** [contao/contao#424]
**Affected version(s)**
Contao 4.4.36 / nav_default model

**Description**  
I'm asking why _li.active_ menu item is hard coded between <strong></strong> tags in _nav_default_ model. Rules are now no more formatting directly in html but in css. So this should better be a <span> tag instead of <strong>
 
**How to reproduce**  
```
<li class="<?= $item['class'] ?>"><strong class="<?= $item['class'] ?>"<?php if (!empty($item['subitems'])) echo ' aria-haspopup="true"'; ?> itemprop="name"><?= $item['link'] ?></strong><?= $item['subitems'] ?></li>
    <?php else: ?>
```
should better be

```
<li class="<?= $item['class'] ?>"><span class="<?= $item['class'] ?>"<?php if (!empty($item['subitems'])) echo ' aria-haspopup="true"'; ?> itemprop="name"><?= $item['link'] ?></span><?= $item['subitems'] ?></li>
    <?php else: ?>
```

**Comment by xchs** [comment]
See https://github.com/contao/core/issues/6336

**Comment by fritzmg** [comment]
It's about HTML semantics not about styling.

**Comment by JLBA** [comment]
I understand. I'm just discovering Contao 4 (transfering an "old" 3.5 website under 4.4) so I took a long moment before understanding where this `<strong>` was hidden.  :-)

**Comment by xchs** [comment]
It is also mentioned in the `UPGRADE.md`: https://github.com/contao/contao/blob/master/UPGRADE.md#markup-changes

**Comment by JLBA** [comment]
Ok. Thanks.

Le 08/04/2019 à 14:53, Hannes a écrit :
