### ISSUE TITLE
Inserttag "figure" is not creating responsive image code

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#4242]
### Affected version(s)

4.12.x, 4.13.x

### Description

Using the inserttag "figure" ignores image sizes. The output is plain html image with full resolution but it should be responsive picture in different versions.
```
{{picture::34bc0ef2-949e-11ec-952f-001a4a050652?size=40}}
{{figure::34bc0ef2-949e-11ec-952f-001a4a050652?size=40}}
```

When i´m using the same image with picture tag, the output is fine.

**HTML Picture Tag using image settings ID40**
```
<picture>
	<source srcset="assets/images/9/terminkalender-legende-7807f2b6.webp 510w, assets/images/2/terminkalender-legende-cf3b6d07.webp 1020w, assets/images/c/terminkalender-legende-44f616ab.webp 1530w, assets/images/1/terminkalender-legende-42191382.webp 1766w" sizes="100vw" media="(max-width: 768px)" type="image/webp" width="510" height="159">
	<source srcset="assets/images/3/terminkalender-legende-7897653c.png 510w, assets/images/3/terminkalender-legende-f1a63000.png 1020w, assets/images/8/terminkalender-legende-66e09df7.png 1530w, assets/images/5/terminkalender-legende-faac7944.png 1766w" sizes="100vw" media="(max-width: 768px)" width="510" height="159">
	<source srcset="assets/images/0/terminkalender-legende-e11c7fab.webp 480w, assets/images/e/terminkalender-legende-b0d899c0.webp 960w, assets/images/5/terminkalender-legende-8d0e2f4e.webp 1440w, assets/images/1/terminkalender-legende-42191382.webp 1766w" sizes="100vw" media="(max-width: 480px)" type="image/webp" width="480" height="150">
	<source srcset="assets/images/f/terminkalender-legende-c13c3727.png 480w, assets/images/0/terminkalender-legende-6939d3c3.png 960w, assets/images/c/terminkalender-legende-c7bd677c.png 1440w, assets/images/5/terminkalender-legende-faac7944.png 1766w" sizes="100vw" media="(max-width: 480px)" width="480" height="150">
	<source srcset="assets/images/d/terminkalender-legende-81719635.webp 690w, assets/images/a/terminkalender-legende-816a6a8c.webp 1380w, assets/images/1/terminkalender-legende-42191382.webp 1766w" sizes="100vw" media="(max-width: 1200px)" type="image/webp" width="690" height="216">
	<source srcset="assets/images/8/terminkalender-legende-d9c9e38f.png 690w, assets/images/e/terminkalender-legende-20509abc.png 1380w, assets/images/5/terminkalender-legende-faac7944.png 1766w" sizes="100vw" media="(max-width: 1200px)" width="690" height="216">
	<source srcset="assets/images/f/terminkalender-legende-7cb6c01e.webp 870w, assets/images/4/terminkalender-legende-82f00e51.webp 1740w, assets/images/1/terminkalender-legende-42191382.webp 1766w" sizes="100vw" type="image/webp" width="870" height="272">
    
<img src="assets/images/7/terminkalender-legende-d4f2e4bb.png" srcset="assets/images/7/terminkalender-legende-d4f2e4bb.png 870w, assets/images/b/terminkalender-legende-5da008e7.png 1740w, assets/images/5/terminkalender-legende-faac7944.png 1766w" sizes="100vw" width="870" height="272" alt="" loading="lazy" class="img-fluid">
</picture>
```

**HTML Figure Tag using image settings ID40**
`<figure class="image_container"><img src="files/xxxx/faq/terminkalender-legende.png" alt="" width="1766" height="552"></figure>`

**Settings from images ID40**
<img width="865" alt="Bildschirmfoto 2022-03-07 um 11 14 30" src="https://user-images.githubusercontent.com/6390770/157011790-69dd422d-9044-4367-84d2-b7c17f33daff.png">

Confirmed in Contao 4.12.7 and 4.13

Greetz
Frank

**Comment by m-vo** [comment]
I don't see you setting any configuration such as the size in your examples. What size configuration would you expect?

Here is how the insert tag is supposed to work: https://docs.contao.org/manual/en/article-management/insert-tags/#miscellaneous

**Comment by Kahmoon** [comment]
I added the HTML code output and image settings above

I used the tags like in documentation described. I need "figure" tags because i want to user lightbox.

**Comment by fritzmg** [comment]
> I don't see you setting any configuration such as the size in your examples. What size configuration would you expect?

@m-vo  `size=40` (should) mean that the image size with ID 40 is used - which seems to work for the `{{picture::*}}` insert tag, but not for the `{{figure::*}}` insert tag.

**Comment by Kahmoon** [comment]
Yes, sorry. This is the id for my image settings

<img width="902" alt="Bildschirmfoto 2022-03-07 um 11 14 25" src="https://user-images.githubusercontent.com/6390770/157012631-dea974dc-2671-4a48-b67d-9775c2a1551f.png">

**Comment by m-vo** [comment]
I can confirm the behavior. It seems we broke `parseUrlWithQueryString()` due to encoded entities. :see_no_evil: 
Urls now look like this `71f7e841-8c0c-11ec-9ef5-631784228eb8?size&#61;test` and parsing them results in empty values.

/cc @ausi

**Comment by ausi** [comment]
> It seems we broke `parseUrlWithQueryString()` due to encoded entities.

~~In which version did this break?~~ _with the XSS security fixes._

Solution may be to add support for `&#61;` here?
https://github.com/contao/contao/blob/dba2cf227e062bfc06e6b8c1a2c52c8df4fbb21b/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L1288-L1289

**Comment by m-vo** [comment]
see #4245
