### ISSUE TITLE
Conflicting Controller::reset method

### ISSUE THREAD

**Issue by aschempp** [contao/contao#4257]
### Affected version(s)

4.9.27

### Description

in https://github.com/contao/contao/pull/4091 we added a new `public static reset()` method to `Controller` to reset the internal class properties on kernel shutdown. Unfortunately, this `reset` method might exist in a lot of other classes that _due to the Contao "default"_ inherit from `Controller`. Isotope for example does in https://github.com/isotope/core/blob/f22f6e3a27db8d870e8daeb6923b8930a9acee03/system/modules/isotope/library/Isotope/Backend/Product/Fallback.php#L26.

I wonder if we should rename that method to something "internal" like `public static function controller_cache_reset()`? Since the method name is irrelevant to Contao, it would sure be less conflicting than something like `reset`.

**Comment by ausi** [comment]
How about `resetControllerCache()` or `resetContaoControllerCache()` ?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4294
