### ISSUE TITLE
Search crawler hangs if the page title is too long

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#4260]
### Affected version(s)

4.13

### Description

If you use a very long page title, the search crawler hangs and throws the following error in the debug log:

`An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1`

### Steps to reproduce:
1. create new news post
2. assign extremely long news title (256 characters in my test).
3. start search crawler
4. hangs at some point
5. download debug log

### Suggestion
The news title and page title should have a maximum length.
In my opinion, it makes no sense to have a title in the news with over 256 characters.

**Comment by fritzmg** [comment]
The news headline is limited to `255` characters, so that is not directly the issue. Also this issue is likely reproducible in Contao 4.9 as well?

**Comment by fritzmg** [comment]
I can confirm this issue in Contao 4.9 - though not for the `title` field, but for the `url` field:

```
"2022-03-12 11:51:48.839442","Contao\CoreBundle\Crawl\Escargot\Subscriber\SearchIndexSubscriber",http://c49.local/en/news/news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long,http://c49.local/share/c49-local.xml,3,noindex,"Forwarded to the search indexer. Did not index because of the following reason: Could not add a search index entry: An exception occurred while executing 'INSERT INTO tl_search (`tstamp`, `url`, `title`, `protected`, `filesize`, `groups`, `pid`, `language`, `text`, `checksum`) VALUES (1647085908, 'http://c49.local/en/news/news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long-headline-news-with-long', 'News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long.', '', '55.46', 'a:0:{}', 3, 'en', 'News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long. News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long headline News with long. 2022-03-12 11:48 by Fritz Michael Gschwantner Test', '52ea1cc4884cf839da4a1fe05bd9f02c')':  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1"
```

I think `tl_search.title` and `tl_search.url` should be of type `TEXT` instead of `VARCHAR(255)` as both of these are potentially much longer than 255 characters. @ausi wdyt?

// edit: although `tl_search.url` has an index, so I am not sure about any performance implications.

**Comment by ausi** [comment]
> I think `tl_search.title` and `tl_search.url` should be of type `TEXT` instead of `VARCHAR(255)`

Agree for `tl_search.title`. 

> although `tl_search.url` has an index, so I am not sure about any performance implications.

For `tl_search.url` we should set it to `VARCHAR(768)` which is the highest value that is supported for UNIQE keys (for all charsets) AFAIK.

**Comment by fritzmg** [comment]
How should we handle longer URLs though? Really long URLs are likely to be an edge case - but still... we did after all increase `tl_content.url` to a length of `2048` recently as well.

We could just let the indexer run into the exception. The crawler will finished in any case and make a debug log entry accordingly.

Btw. in truth I haven't _really_ been able to reproduce the original issue as I have only tested the crawler on the command line. There the crawler finishes regularly and simply displays that some URLs had errors at the end. The same should ideally happen in the back end of course.

@contaoacademy are you sure the URL in question is the cause for the "freeze"?

**Comment by Toflar** [comment]
We could add another column where we'd store a hash of the URL for duplicate lookups (with an index) and have the url itself be a regular text field.

**Comment by ausi** [comment]
If we want to support longer URLs we should use `VARCHAR(2048) COLLATE ascii_bin` and check if the URLs are properly URL-encoded when inserting them.

**Comment by fritzmg** [comment]
Will that work for URLs like `http://example.com/某物-中国人`?

**Comment by ausi** [comment]
Yes: `http://example.com/%E6%9F%90%E7%89%A9-%E4%B8%AD%E5%9B%BD%E4%BA%BA`
