### ISSUE TITLE
Error when trying to copy events (copyAll-mode) from one calendar into another (empty!) calendar

### ISSUE THREAD

**Issue by markocupic** [contao/contao#427]
Contao throws an error when I'm trying to copy (copyAll-mode) **as a non admin** multiple events from one calendar into another **empty**! calendar.

https://github.com/contao/contao/blob/c0fc6315af73e8bef9d67e2f8ae952ac1ddda80b/calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php#L662

When I'm escaping Line 662 everything works just fine.
					
Tested in contao 4.7.2 and the contao online demo.

https://we.tl/t-dEYGcNCz6Y

**Comment by leofeyer** [comment]
Fixed in d429be09b6e8d2cd6c9adbbcfe7f23999a948373.
