### ISSUE TITLE
Creating a second starting point of a website not possible

### ISSUE THREAD

**Issue by anuijen** [contao/contao#4276]
### Affected version(s)

4.13.0

### Description

I have installed Contao 4.13.0 and would like to create a multilingual page. There is already a "de" starting point and several pages contained in it. It is not possible to create a second starting point for "en". This error message is displayed:

`Argument 1 passed to Contao\CoreBundle\Util\LocaleUtil::formatAsLocale() must be of the type string, null given, called in ../vendor/contao/core-bundle/src/Routing/Page/PageRoute.php on line 46`

**Comment by leofeyer** [comment]
It seems to work on my system. What exactly did you do and do you have any third-party extensions installed?

**Comment by fritzmg** [comment]
This is likely caused by an extension, e.g. https://github.com/terminal42/contao-folderpage/issues/23

**Comment by anuijen** [comment]
@fritzmg Thanks for the tip. The reason was indeed the Contao Folder Page extension.
