### ISSUE TITLE
Dumper::formatValueForDump() Argument #1 ($value) must be of type ?string, int given

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#4278]
### Affected version(s)

4.13.x-dev

### Description

When using `contao:migrate (or `backup:create`) the following error happens in Contao `4.13.x-dev`:

```
[ERROR] Contao\CoreBundle\Doctrine\Backup\Dumper::formatValueForDump():      
         Argument #1 ($value) must be of type ?string, int given, called in   
         vendor\contao\contao\core-bundle\src\Doctrine\Backup\Dumper.php on line 122 
```

The column in question is `tl_article.id` and the value to be formated is an integer of value `1`. This error was introduced in https://github.com/contao/contao/commit/52753e05c0efdcb6a6cb28e2c75665d544ece208

/cc @Toflar

**Comment by Toflar** [comment]
How come you have an integer there? Can you debug this? Database values are always transferred as strings.

**Comment by leofeyer** [comment]
Turns out to be a new behavior of the PDO driver in PHP 8.1: https://github.com/doctrine/dbal/issues/5228
