### ISSUE TITLE
DCA-Felder mit der rgxp = date (Eval) standardmäßig mit aktuellen Datum vorausgefüllt

### ISSUE THREAD

**Issue by OMOSde** [contao/contao#428]
**Affected version(s)**
Contao 4.4.37 (4.4.36 war ok)
PHP 7.2
getestet in 2 Systemen

**Description**  
DCA-Felder mit der rgxp = date (Eval) nun standardmäßig mit dem aktuellen Datum vorausgefüllt 

Mögliche Ursache [dieser Commit](https://github.com/contao/contao/commit/2846b6a7d66b44380ce05d8bbf3256a54b210d3b)

**How to reproduce**  
DCA-Feld:
`'eval'      => ['rgxp' => 'date',  'datepicker' => true, 'tl_class' => 'w50 wizard'],
 'sql'       => "int(10) unsigned NULL"
`

[Forumsbeitrag](https://community.contao.org/de/showthread.php?74600-Nach-Update-von-4-4-36-auf-4-4-37-DCA-Felder-mit-rgxp-gt-date-immer-vorausgef%C3%BCllt)

**Comment by philvdb** [comment]
Denke da hast du ganz recht, der Commit geht ja von `!= ''` nach `!== ''`. Das SQL-Feld, das du definierst, kann aber gar nicht `''` werden, höchstens eben `null` oder `0`.

Vor besagtem Commit war also `null` oder `0` `!= ''` erfüllt, nach dem Commit ist das nicht mehr gleich.

Kürzer gesagt denke ich du solltest versuchen dein SQL-Feld umzudefinieren, wie du es im Core bei (manchen, nicht allen!) anderen Datumsfeldern siehst: `varchar(10) NOT NULL default ''`. Ob das der "richtige" Weg ist, einen UNIX-Timestamp zu speichern sei dahingestellt, es scheint aber der supportete Contao-Weg zu sein.

**Comment by fritzmg** [comment]
`varchar(10) NOT NULL default ''` is used for `start` and `stop` - presumably so it can be `''`, yes. And I guess it needs to stay this way for BC reasons.

**Comment by philvdb** [comment]
I'm not suggesting we alter `start` and `stop` - I'm suggesting the OP changes his field definition to match the Contao one for `start` and `stop`.

**Comment by fritzmg** [comment]
I can confirm this issue within Contao (and its bundles). Prior to Contao 4.7.3 (including Contao 3) when creating a new event for example the start and end date (of the event, I don't mean the visibility settings) were empty. Since Contao 4.7.3 the start and end date are the current date.

@philvdb this was just a general comment of mine. And changing a regular timestamp field to a varchar should not be the solution. This behaviour was introduced with the recent update and is reproducible within Contao itself.

**Comment by philvdb** [comment]
@fritzmg ah okay, sorry. Didn't realize the change broke core functionality. In that case short of a rollback of the change I guess the definitions of `start` and `stop` would need to be changed, which may not be something for a bugfix release?

**Comment by fritzmg** [comment]
The issue does not concern the `*.start` and `*.stop` fields, but any other date fields within Contao (or extensions. e.g. `tl_calendar_events.startDate`. The `start` and `stop` fields are unaffected.

**Comment by philvdb** [comment]
I would expect it to affect all fields that are defined as integers in the database, as `tl_calendar_events.startDate` is. And not the ones that are strings. We currently have a mixture of strings, unsigned and signed integers in the database all used as dates or times. This bug may just make us have to decide for one variable type :)

**Comment by fritzmg** [comment]
**Reproduction for the Online Demo**

1. Log into the Contao Online Demo.
2. Go to the calendar.
3. Simply edit _each_ event and then immediately save it.
4. Visit https://demo.contao.org/en/events.html

All (previously single day) events will now be multi day events - with the end date being the current date.

It's currently impossible to create an event with _no_ end date.

**Comment by leofeyer** [comment]
Fixed in e632fe36c42c62d77d1fe76cc2641e6badf017b4. @fritzmg @philvdb Can you please verify that the changes fix your issue?

**Comment by fritzmg** [comment]
Yes, I that fixes it.
