### ISSUE TITLE
Remove title tag within sources in ce_player (video/audio)

### ISSUE THREAD

**Issue by CMSworker** [contao/contao#4286]
### Affected version(s)

4.13.1

### Description

ce_player outputs file titles within the souces tags.

I think the titles are useless here and can be removed...

Video sources (line 9):
https://github.com/contao/contao/blob/f00c0ad6035b09e935bcbeab00b10b0f5b19154d/core-bundle/src/Resources/contao/templates/elements/ce_player.html5#L9

Audio sources (line 9):
https://github.com/contao/contao/blob/f00c0ad6035b09e935bcbeab00b10b0f5b19154d/core-bundle/src/Resources/contao/templates/elements/ce_player.html5#L15

https://dev.w3.org/html5/html-author/#the-source-element

**Comment by fritzmg** [comment]
The `title` attribute can be used on any element iirc. However, its usage is discouraged and I also question whether it makes sense to use it on the `<source>` element rather than the `<video>` element at all.
