### ISSUE TITLE
Fehler beim BE-Login für User wenn "Passwort-Änderung notwendig" festgelegt wurde

### ISSUE THREAD

**Issue by LinkingYou** [contao/contao#429]
**Affected version(s)**
Contao 4.4.37

**Description**  
Wenn man im BE bei einem Benutzer die Option "Passwort-Änderung notwendig" aktiviert, dann wird dieser auch beim Login aufgefordert, ein neues Passwort festzulegen. Beim Speichern des neues Passworts erhält man dann aber:

Contao 4.4.37

Internal Server Error

Type error: Too few arguments to function tl_user::invalidateSessions(), 1 passed in /var/www/html/vendor/contao/core-bundle/src/Resources/contao/controllers/BackendPassword.php on line 102 and exactly 2 expected

**How to reproduce**  
- Contao 4.4 installieren (z.B. mit Composer)
- Contao auf 4.4.37 aktualisieren
- Benutzer im BE anlegen und Option "Passwort-Änderung notwendig" aktivieren
- Mit neuem Benutzer anmelden und versuchen ein neues Passwort festzulegen

**Comment by contaoacademy** [comment]
Ich kann den Fehler in der 4.4.37 bestätigen.
Unter Contao 4.7.3 tritt das Problem nicht auf.

**Comment by leofeyer** [comment]
Behoben in a4a1dd89cceaea787507af692bcc95f224c4ba28.
