### ISSUE TITLE
hover effect when inserting a new article

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#4295]
### Description

There is no hover effect when inserting a new article if, for example, one doesn't exist yet. Can we fix this?

![Contao-No-Hover](https://user-images.githubusercontent.com/1622733/158773483-e7d55953-2b4b-4656-8025-1a22828ee396.gif)
![Contao-Hover2](https://user-images.githubusercontent.com/1622733/158773494-6f43f0e6-b6a4-433b-ab1d-957ea8e9bf47.gif)
![Contao-Hover](https://user-images.githubusercontent.com/1622733/158773498-0cb60abb-eb15-48af-a286-2c4f5b8ae0b7.gif)

**Comment by cliffparnitzky** [comment]
Can't confirm. Not reproducable in the demo. @erikherbert Please have a try with https://demo.contao.org/contao/login

**Comment by erikherbert** [comment]
No hover-effect also in the demo. just delete all articles and add a new.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1622733/158807590-c3039a7a-7ed8-47bc-802f-6871a901a3e2.gif)

**Comment by leofeyer** [comment]
Confirmed.

**Comment by cliffparnitzky** [comment]
Okay. Just to clarify. The hover is only missing for the page nodes. Not for the articels itself.
