### ISSUE TITLE
Class "twig.controller.exception" does not exist

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#43]
**Affected version(s)**
4.6.2

**Description**  
If an exception happens in a `Template` (or just a `FrontendTemplate`?), there will always be two errors in the dev environment:

* Class "twig.controller.exception" does not exist.
* The actual exception.

![screenshot_2018-08-31 screenshot](https://user-images.githubusercontent.com/4970961/44906611-afca7680-ad15-11e8-83b0-383aa84f624f.png)

**How to reproduce**  
1. Insert `<?php throw new \Exception('foo') ?>` into one of your front end templates.
2. Open the front end via `app_dev.php` and navigate to a page where that template is included.

**Comment by leofeyer** [comment]
This should have been fixed in Symfony 4.1.1:

- https://github.com/symfony/symfony/issues/27438
- https://github.com/symfony/symfony/pull/27702

Can you run `composer show 'symfony/*'` and post the output here please?

**Comment by fritzmg** [comment]
I see. My `symfony/twig-bundle` is still at `4.1.0`. I cannot update to `4.1.1` or higher, because it depends on `symfony/dependency-injection:^4.1`  and my current project depends on `symfony/dependency-injection:^3.0`.

I have downgraded `symfony/twig-bundle` to `3.4.15`, now the issue is gone :).

May be the requirement in the `contao/core-bundle` should be changed to
```
"symfony/twig-bundle": "3.4.* || ^4.1.1"
```
? Or add a conflict for `symfony/twig-bundle:4.1.0`.

**Comment by leofeyer** [comment]
`"3.4.* || ^4.1.1"` is the right way to go.

**Comment by leofeyer** [comment]
Fixed in f0ab320f5284f7e4a08e99932bc6625aeff8dc46.

**Comment by fritzmg** [comment]
Hm, just curious, why did you add it in the manager-bundle as well? Shouldn't the core-bundle be enough?

**Comment by leofeyer** [comment]
I have added it in all bundles that require `symfony/twig-bundle`.
