### ISSUE TITLE
Image-related deprecations

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#4309]
### Description

https://github.com/contao/contao/blob/d7ccb031e5f89e560cc6d1bd30b420f308891a14/core-bundle/src/Image/ImageFactory.php#L290

https://github.com/contao/contao/blob/d7ccb031e5f89e560cc6d1bd30b420f308891a14/core-bundle/src/Image/ImageSizes.php#L120

https://github.com/contao/contao/blob/d7ccb031e5f89e560cc6d1bd30b420f308891a14/core-bundle/src/Image/LegacyResizer.php#L49

**Comment by ausi** [comment]
Closed in favor of #4328
