### ISSUE TITLE
(solved) ce_hyperlink : image link target disappears after saving

### ISSUE THREAD

**Issue by JLBA** [contao/contao#434]
**Affected version(s)**
Contao 4.4 (not tested under 4.7)
**Description**  
In hyperlink content element, we first have 2 url fields : 
- link target
- if checked, create an image link / overwrite meta data / image link target
I don't know the real difference between both but when saving, image link target field disappears. 
**How to reproduce**

**Comment by leofeyer** [comment]
Fixed in 762b484c181705c150670a39d78cd4044ec65808.

**Comment by JLBA** [comment]
Thanks.
