### ISSUE TITLE
Labels for min and max value in form field settings

### ISSUE THREAD

**Issue by Toflar** [contao/contao#437]
**Affected version(s)**

4.7.*

**Description**  

I think the labels for minimum and maximum value in the form field generator are a bit misleading. See:
![grafik-20190415-120244](https://user-images.githubusercontent.com/481937/56134736-7afeed00-5f8f-11e9-8653-c985af73961f.png)

I think it's the same in English because we re-use the `minlength` and `maxlength` labels. Imho those should get adjusted in an onload_callback or so here otherwise it's super misleading (my customers keep entering `4` and `5` to restrict postal code lengths).

**Comment by fritzmg** [comment]
I made the same mistake recently 😁

**Comment by leofeyer** [comment]
> my customers keep entering `4` and `5` to restrict postal code lengths

What is wrong with that?

**Comment by Toflar** [comment]
It won't work. The `minlength` and `maxlength` fields are abused for `min` and `max` attributes. The other two have no effect on `input type="number"` fields. So what they should enter instead is `1000` and `99999`.

**Comment by leofeyer** [comment]
Ok, that is wrong for sure. 😄

**Comment by Toflar** [comment]
4.7.* only ;)

**Comment by leofeyer** [comment]
I would suggest reverting f7a5ff7afcbda38b186db87ed47a5eff060c2ff4 and adding two fields `tl_form_field.minval` and `tl_form_field.maxval`. Then we can translate them separately and we do not have any "changes its meaning depending on the field type" magic. WDYT?

**Comment by Toflar** [comment]
Sounds good to me, wdyt @qzminski ?

**Comment by qzminski** [comment]
Yep, agreed :+1:

**Comment by leofeyer** [comment]
Changed in 0da382f396195f6b99316e73ecd64067b59528a2.
