### ISSUE TITLE
Revise table takes very long to run for large tables

### ISSUE THREAD

**Issue by tophcodes** [contao/contao#438]
**Affected version(s)**
Unsure, but affected code was last changed 7 years ago, so it's been a while.

**Description**
We have models with the following (1:n) relationships:  
Customer -> Project -> Participant

Each project can have tens of thousands of participants, in our live database the corresponding table has about 20 million entries. The `tl_participant` DCA defines a `ptable` relationship to `tl_customer_project`. When I want to open the list of participants within a project I would expect it to take a little bit longer if this particular project has many participants. In fact however, every single list load for every single project takes somewhere between 20 and 30 seconds because of this query that's run in `DC_Table`: https://github.com/contao/contao/blob/ed2fec5eaaa84875a9a14b5b90e803a65bccec7c/core-bundle/src/Resources/contao/drivers/DC_Table.php#L3400

```sql
DELETE FROM tl_participant WHERE NOT EXISTS 
  (SELECT * FROM tl_customer_project WHERE tl_participant.pid = tl_customer_project.id)
```

I do see why this code is run, but I'm not sure that it's the most sensible place to run this every time the list is loaded. It makes the participant list virtually unusable.

**Comment by leofeyer** [comment]
Can you please show us how your tables look like?

```
$ mysql
$ SHOW CREATE TABLE tl_participant
$ SHOW CREATE TABLE tl_customer_project
```

**Comment by tophcodes** [comment]
```mysql
CREATE TABLE `tl_customer_project` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(10) unsigned NOT NULL DEFAULT '0',
  `tstamp` int(10) unsigned NOT NULL DEFAULT '0',
  `name` varchar(256) NOT NULL DEFAULT '',
  `sub_variant` varchar(256) NOT NULL DEFAULT '',
  `startsOn` int(10) NOT NULL DEFAULT '0',
  `endsOn` int(10) NOT NULL DEFAULT '0',
  `numChildrenOnline` varchar(256) NOT NULL DEFAULT '',
  `numChildrenOffline` varchar(256) NOT NULL DEFAULT '',
  `childrenSeeParentStatus` varchar(256) NOT NULL DEFAULT '',
  `title` varchar(256) NOT NULL DEFAULT '',
  `splashText` text,
  `adAgreementText` text,
  `overviewTextParent` text,
  `overviewTextChild` text,
  `ts_import` varchar(255) NOT NULL DEFAULT '',
  `campaign_type` varchar(256) NOT NULL DEFAULT '',
  `function` varchar(256) NOT NULL DEFAULT '',
  `multicode_limit` varchar(256) NOT NULL DEFAULT '',
  `fk_project_manager` varchar(1024) NOT NULL DEFAULT '',
  `sorting` int(10) unsigned NOT NULL DEFAULT '0',
  `domain` varchar(256) NOT NULL DEFAULT '',
  `fk_error_page` int(10) unsigned NOT NULL DEFAULT '0',
  `features` varchar(256) NOT NULL DEFAULT '',
  `fk_doi_verify_page` int(10) unsigned NOT NULL DEFAULT '0',
  `custom_css` text,
  `footer_copyright` varchar(512) NOT NULL DEFAULT '',
  `mail_sender_name` varchar(256) NOT NULL DEFAULT '',
  `mail_sender_email` varchar(256) NOT NULL DEFAULT '',
  `maintenance` varchar(1) NOT NULL DEFAULT '',
  `registration_without_code` varchar(1) NOT NULL DEFAULT '0',
  `fk_project_template` varchar(10) NOT NULL DEFAULT '',
  `template_imported` varchar(1) NOT NULL DEFAULT '0',
  `field_configuration` blob,
  `min_age` varchar(512) NOT NULL DEFAULT '',
  `global_title_tag` varchar(256) NOT NULL DEFAULT '',
  `global_description_tag` varchar(256) NOT NULL DEFAULT '',
  `ga_code` varchar(256) NOT NULL DEFAULT '',
  `show_cookie_hint` varchar(1) NOT NULL DEFAULT '0',
  `custom_theme` varchar(10) NOT NULL DEFAULT '',
  `use_sticky` varchar(1) NOT NULL DEFAULT '0',
  `zipPassword` varchar(255) NOT NULL DEFAULT '',
  `allow_prefill` varchar(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `pid` (`pid`)
) ENGINE=MyISAM AUTO_INCREMENT=158 DEFAULT CHARSET=utf8
```

```mysql
CREATE TABLE `tl_participant` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tstamp` int(10) unsigned NOT NULL DEFAULT '0',
  `pid` int(10) unsigned NOT NULL DEFAULT '0',
  `fk_generator` int(10) unsigned NOT NULL DEFAULT '0',
  `lcg_used` int(1) unsigned NOT NULL DEFAULT '0',
  `activation_code` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `parent_activation_code` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `doi_md5` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `type` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `email` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `company_name` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `company_field` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `company_size` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `salutation` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `firstname` varchar(26) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `lastname` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `birthdate` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `street` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `number` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `country` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `zip` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `city` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `phone_preselect` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `phone_callnumber` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `soi_date` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `soi_ip` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `soi_host` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `doi_date` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `doi_ip` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `doi_host` varchar(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `unsubscription_date` int(11) NOT NULL DEFAULT '0',
  `unsubscription_ip` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `source` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `external_id` int(11) NOT NULL DEFAULT '0',
  `ts_external_import` int(11) NOT NULL DEFAULT '0',
  `fk_import` varchar(11) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `ts_optin_mail_send` int(11) NOT NULL DEFAULT '0',
  `accepted_privacy` varchar(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `accepted_terms` varchar(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `accepted_advertising` varchar(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `pid` (`pid`),
  KEY `activation_code` (`activation_code`),
  KEY `parent_activation_code` (`parent_activation_code`),
  KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=19100543 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by leofeyer** [comment]
You are mixing `ENGINE=MyISAM` and `ENGINE=InnoDB`. Is this intended?

**Comment by tophcodes** [comment]
That's our development database, the live system's tables are all MyISAM. A while ago I switched one of the tables to InnoDB to see if that improves performance for some more expensive queries but haven't switched it back yet. Other than the engine the tables between the development and live database are identical though.

It doesn't matter for this case I'm pretty sure, the `DELETE` query is equally slow when both tables are MyISAM.

**Comment by Toflar** [comment]
Can you share the `EXPLAIN` result of the query in question?

**Comment by tophcodes** [comment]
Do you mean
```mysql
EXPLAIN DELETE FROM tl_participant WHERE NOT EXISTS 
  (SELECT * FROM tl_customer_project WHERE tl_participant.pid = tl_customer_project.id)
```
?

| id | select_type | table | partitions | type | possible_keys | key | key_len | ref | rows | filtered | Extra |
|---|---|---|---|---|---|---|---|---|---|---|---|
| 1 | DELETE | tl_participant | `NULL` | ALL | `NULL` | `NULL` | `NULL` | `NULL` | 6937079 | 100.00 | Using where |
| 2 | DEPENDENT SUBQUERY | tl_customer_project | `NULL` | eq_ref | PRIMARY | PRIMARY | 4 | dev_db.tl_participant.pid | 1 | 100.00 | Using index |

**Comment by Toflar** [comment]
And how long does that query take?

**Comment by tophcodes** [comment]
The explain query takes 0.001 seconds. The actual `DELETE` query takes between 23 and 24 seconds.

**Comment by m-vo** [comment]
24s sounds way too long for that (even with lots of entries). :thinking:  Can you check if using a joined query improves performance?

sth like 
```SQL
DELETE FROM tl_participant 
LEFT JOIN tl_customer_project ON tl_participant.pid = tl_customer_project.id 
WHERE tl_customer_project.id IS NULL
```

**Comment by tophcodes** [comment]
The joined query takes 22 seconds, so not much better.

**Comment by m-vo** [comment]
>The joined query takes 22 seconds, so not much better.

Can you please post an explain for that as well? I've got the strong feeling the index on `pid` (`tl_participant`) isn't used and a table scan occurs instead. (You could also try to force using it with `USE INDEX` / `FORCE IDEX` and see if this changes something, allthough it's super unlikely that the planner is misjudging in such a simple query.)

Having lots of rows in a `DELETE` is insanely slow but there shouldn't be that many affected rows if any. Could you verify this as well? And maybe also profile a mere select statement:

```SQL
SELECT id FROM tl_participant 
LEFT JOIN tl_customer_project ON tl_participant.pid = tl_customer_project.id 
WHERE tl_customer_project.id IS NULL
```

**Comment by Toflar** [comment]
Can't we invert the query? Revise table revises 22 million rows by saying `WHERE NOT EXISTS <valid relation>`. But 99.9% are valid so the result set is huge (`6937079` rows).
Can't we do `WHERE EXISTS <invalid relation>`.?

**Comment by Toflar** [comment]
`DELETE FROM tl_participant WHERE EXISTS (SELECT * FROM tl_customer_project WHERE tl_participant.pid != tl_customer_project.id)` - should be the same or is it too early and I'm still asleep?

**Comment by m-vo** [comment]
In the end you'll have to check for each child if the parent exists. Fastest way is probably to have a sorted set (or rather sorted index) on each relation and walk along in both sets simultaneously. In that case it's `O(n)`. But that is basically what the execution plan should look like in any way. (And if the set only contains a key the size shouldn't be the bottleneck...)

It could be - however - that the `DELETE` query does not use indices at all. In that case using a two-step approach (select first, then delete) would help.

**Comment by Toflar** [comment]
I don't think we have to change a lot of it here, just invert the logic. What it does now is this:

- SELECT all valid entries -> DELETE everything that is not inside this result set.

But it's the vast majority that is valid. Maybe the very, very first time `reviseTable()` is executed it's not. But afterwards the table is clean and maybe there are one or two invalid rows. 

- SELECT all invalid entries -> DELETE everything that is inside this result set.

**Comment by m-vo** [comment]
Yeah but these are transformations the execution planner should normally apply anyway when resolving the order / indices. So I would assume there shouldn't be a difference in speed. But it's worth a try of course. 😃

**Comment by Toflar** [comment]
In fact

> DELETE FROM tl_participant LEFT JOIN tl_customer_project ON tl_participant.pid = tl_customer_project.id WHERE tl_customer_project.id IS NULL

should be the fastest imho. That should be extremely fast because of the index. So I think there's something wrong with @padarom's database here.
Alternatively you could try

> DELETE FROM tl_participant WHERE tl_participant.id IN (SELECT tl_participant.id FROM tl_participant LEFT JOIN tl_customer_project ON tl_participant.pid = tl_customer_project.id WHERE tl_customer_project.id IS NULL)

Which is basically the same as the first query but who knows...

**Comment by m-vo** [comment]
Check out this fiddle: https://www.db-fiddle.com/f/iEHya3Ry4mS6qWXvAbscdH/0
Looks like `DELETE` does in fact ignore the index...

**Comment by Toflar** [comment]
Okay, then we need to select the invalid ID's first and then only delete those with `WHERE id IN()` in a separate query (you cannot do this in the same as you would be selecting and deleting from the same table in the same query). That should definitely work then.

**Comment by tophcodes** [comment]
Does it really make sense to just optimise the query? I mean sure it might work and be faster, but at 20 million entries it could still take a second.

As far as I understand it the query resolves an issue that rarely ever happens, and if it does it's not at all time critical to resolve it as there's just some dead database entries lying around. Doesn't it make more sense to find another place for this query to run, rather than every time the list is accessed? I feel like adding it to Maintenance -> Purge data would be perfectly sufficient.

**Comment by leofeyer** [comment]
The revise table method does two things:

1) Remove new records that have not been completed.
2) Purge orphan records that are no longer related to an element.

@contao/developers No. 1 needs to be executed always but no. 2 could indeed be moved to a daily cronjob, couldn't it?

**Comment by m-vo** [comment]
> but at 20 million entries it could still take a second.

Did you profile or is this a guess?

---

Sure 1. could be done by checking `tstamp = 0` / `pid = 0` for instance and 2. could be outsourced. But If doing so then I would opt for a (`InnoDB` only) FK + `ON DELETE CASCADE` solution. The cronjob then only needs to run for relations without FK.

**Comment by leofeyer** [comment]
Pull request: https://github.com/contao/contao/pull/487

@padarom Can you please test the changes and see if they make a difference on your system?
@m-vo Can you please review the changes and make sure I got things right?

**Comment by tophcodes** [comment]
Query runtime is now 3525.93 ms. Still not ideal but at least it's now usable.
