### ISSUE TITLE
Canonical Query Parameter has no effect

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#4382]
### Affected version(s)

4.13.0 and 4.13.1

### Description

The canonical tag does not work correctly. The information entered is partially ignored or, depending on what is entered in the URL field, can lead to incorrect frontend output.

**Issue 1:** No matter how you specify query parameters, they are ignored. Whether you select an external or internal page URL, the query parameters in the form `foo` or `foo=goo` or `?abc=123` or `&123=abc` are not output

**Issue 2:** If you add as custom URL an external website, the complete path including the protocol would have to be specified, otherwise `www.mydomain.com` will quickly become `<link rel="canonical" href="https://demo.contao.org/www.mydomain.com">`

You can check the functionality in the [Contao demo page](https://demo.contao.org/contao) or see the forntend output [here](https://contao-test.ixtensa-workserver.de/)

**Comment by Toflar** [comment]
I cannot confirm issue 1: If I configure `page*,foo`, then call https://demo.contao.org/en/about-contao.html?test=true&foo=bar&page_42=true, I do get the correct, expected `<link rel="canonical" href="https://demo.contao.org/en/about-contao.html?foo=bar&page_42=true">`.

I can confirm the second issue, though. We should probably only allow absolute URLs in the input field (plus insert tags).

**Comment by Toflar** [comment]
@contao/developers we already do handle it. https://github.com/contao/contao/blob/4.13/core-bundle/src/Routing/ResponseContext/CoreResponseContextFactory.php#L98. But if you enter `www.foobar.com` you'll get that prefixed with the current request. Not sure if we should even try to fix anything or that's just a wrong usage. We don't have a validator for absolute URLs afaik.

**Comment by havutcuoglu** [comment]
Ok. I tried now `page*,foo ` on page Text Elements, I did not get any effect. Than I call the URL including parameter, than I can see the changes. That means, I have to add on my URL the parameter `?foo=goo` also to check the functionality and add `page*` for the field query parameter in backend. This is not intuitive.

It's correct, when I add a custom domain and the query parameter, and the parameter will ignored?
For example: `http://mydomain.com/index.html` as external and `foo=goo` as parameter.
I will expect the canonical tag to say `http://www.mydomian.com/index.html?foo=goo`

In my opinion, the canonical tag should always contain what is in the address bar. Only when I want to overwrite it do I enter an external URL or choose another page in Contao. The thing about the query parameter is really very confusing.

**Comment by havutcuoglu** [comment]
I forget, for external URLs it will be helpfuly to add in description a example text like "add external URL with http:// or https://"

**Comment by Toflar** [comment]
The canoncial link always points to the same page without query parameters. That's the whole idea of the canonical implementation. Most of the query parameters are used to filter results on a page and are irrelevant for search engines, hence the canoncial link. Think of `products.html?page=1`, `products.html?page=2` etc. Those are pagination parameters and we don't want those pages indexed by search engines. They likely all have a detail page so it makes absolutely no sense. If, however, you don't have a detail page and you want those parameters to be kept, you would add `page` to the parameters to keep for the page `products.html`. Then all parameters except for `page` are removed. 
That's the funcionality that is implemented. If you look for anything else you are probably looking for an extension that does what you need.

**Comment by fritzmg** [comment]
> We don't have a validator for absolute URLs afaik.

@Toflar we do, its rgxp is called `httpurl`. It does not allow insert tags though, iirc.

May be we should parse the entered URL and prepend scheme and/or. host automatically.

**Comment by havutcuoglu** [comment]
Thanks a lot. But I am using already a extension for canonical who filters the page, day, week, month, year etc. all contao used parameters and only have two fields where I can enter my custom URL including parameters and select it is external URL.
I just wanted to use the one from Contao so that I don't have to worry about maintenance for my own extension.

**Comment by ausi** [comment]
> But if you enter `www.foobar.com` you'll get that prefixed with the current request. Not sure if we should even try to fix anything or that's just a wrong usage.

`www.foobar.com` is a relative URL, so normalizing it to `https://example.com/www.foobar.com` is correct IMO.

Maybe we should change https://github.com/contao/contao/blob/23b6373c8a52b576911ef4acc53de209f7ef7fe2/core-bundle/src/Resources/contao/languages/en/tl_page.xlf#L147 to something like “Here you can set a custom canonical URL like https://example.com/.”

**Comment by havutcuoglu** [comment]
If you use a checkbox or selection for external/internal Links, you can parse the url string and manipulate it. You can also add and/or sheme.

**Comment by Toflar** [comment]
As discussed in our Contao Slack Call on July 28, 2022, we think it's a valid use case to allow relative URLs. We will adjust the label to include an example, though.
