### ISSUE TITLE
Dateiverwaltung - Ordner mit Sonderzeichen kopieren

### ISSUE THREAD

**Issue by peter-gorn** [contao/contao#4384]
### Affected version(s)

4.9

### Description

Hallo,
mir ist ein kleiner Bug beim Kopieren der Ordner in der Dateiverwaltung aufgefallen. Wenn der Ordner-Name beispielsweise Leerzeichen enthält, wird der paste-Icon des zu kopierenden Ordners nicht grau. Beim Versucht den Ordner in sich selbst zu kopieren (macht zwar kein Sinn und ist falsch, aber möglich :) ) gibt es dann den entsprechenden Kopier-Fehler.
Problem in DC_Folder.generateTree() aufgefallen > Sonderzeichen im Pfad sind kodiert ($arrClipboard['id'] > "files/test/test%202")

![image](https://user-images.githubusercontent.com/84569196/159929095-b2d6933c-dbcb-4414-ba49-aaaf421ecf64.png)

**Comment by cliffparnitzky** [comment]
Can confirm. Same with Contao 4.13.1.

Using the button ends with an internal error.
