### ISSUE TITLE
TinyMCE german translation

### ISSUE THREAD

**Issue by fr4nk2342** [contao/contao#4385]
### Affected version(s)

4.13

### Description

Headline is translated somewhat unusually. "Headline" should better be "Überschrift" instead of "Kopfzeile".

![Screenshot 2022-03-24 153753](https://user-images.githubusercontent.com/7665987/159941387-6af2ddbb-0482-4352-9e64-4abd081c0aea.jpg)

**Comment by de-es** [comment]
Ist mir auch schon aufgefallen. Leider ändert auch ein (manuelles) Update der Übersetzungen der aktuellen TinyMCE-Version (6.0) nichts daran, auch hier heisst es weiterhin Kopfzeile.

Stellt sich die Frage, ob es sinnvoll wäre, über Transifex bei TinyMCE eine Änderung vorzuschlagen?

**Comment by fritzmg** [comment]
> Stellt sich die Frage, ob es sinnvoll wäre, über Transifex bei TinyMCE eine Änderung vorzuschlagen?

Yes, you need to raise this issue with TinyMCE, not here in Contao.

**Comment by de-es** [comment]
Dort darauf Einfluss nehmen zu wollen, gestaltet sich schwierig: This project currently does not accept new members. :disappointed:

**Comment by fritzmg** [comment]
You can still raise the issue on GitHub.

**Comment by de-es** [comment]
Das scheint aber vergebliche Liebesmüh zu sein, wenn ich mir die Tickets bzgl. Übersetzung dort anschaue.

Wenn gewünscht, kann ich gerne einen Pull Request für die Contao Components erstellen, auch wenn das nicht der perfekte Weg zur Lösung ist.

**Comment by fritzmg** [comment]
> Das scheint aber vergebliche Liebesmüh zu sein, wenn ich mir die Tickets bzgl. Übersetzung dort anschaue.

You should still do it.

**Comment by de-es** [comment]
TinyMCE ist zur Übersetzung auf Crowdin gewechselt. Dort konnte ich die Änderung durchführen. Allerdings wird es diese nur für die v6 geben.

Damit wir nicht bis zur v6 warten müssen, siehe https://github.com/contao-components/tinymce4/pull/3
