### ISSUE TITLE
Add shared max age to response by default

### ISSUE THREAD

**Issue by m-vo** [contao/contao#4386]
### Description

```diff
// AbstractContentElementController
-        return $this->getResponse($template, $model, $request);
+        $response = $this->getResponse($template, $model, $request);
+        $this->addSharedMaxAgeToResponse($response, $model);
+        return $response;
```

To disable you can still override the method with a no-op in your controller class.

**Comment by aschempp** [comment]
This would break any existing cache information in the response.

**Comment by m-vo** [comment]
> To disable you can still override the method with a no-op in your controller class

**Comment by aschempp** [comment]
That is very bad UX. My controller returns a **custom** response, and I still have to override the method to not have my "already correct" response modified? That makes no sense.

**Comment by m-vo** [comment]
Didn't we discuss this already and decided this was the way to go for 5? IIRC the reasoning was: in general there is no reason not to use the feature. With the current approach, everyone has to manually add this nearly every time.

**Comment by leofeyer** [comment]
I‘m with @aschempp on this one. If someone send a response with a shared max age, we should not "correct" it. Maybe we can check if the header exists already?

**Comment by m-vo** [comment]
Just to make sure, we're talking about the same thing: It's not about adding anything to the `AbstractFragmentController` but the `AbstractContentElementController`. And this base class implements certain things common to our content elements (class names, css ids, headlines, automatic model tagging and so on …). Why should the start/stop setting that is present in every core content element be an exception from this? We would need to add the call to every of our content element controllers and - fun fact - we already forgot to do so for the already existing ones.

If this is really a problem in a certain use case maybe the base class for this should rather be `AbstractFragmentController` (or we need another one).

**Comment by m-vo** [comment]
Alternatively we could pass the pre-configured response in `getResponse()` as well. `$this->render()` supports passing in a response and the new fragment template could allow this as well.

**Comment by leofeyer** [comment]
> Just to make sure, we're talking about the same thing: It's not about adding anything to the `AbstractFragmentController` but the `AbstractContentElementController`.

Ah, I missed that. Then it makes sense I guess.

**Comment by m-vo** [comment]
I looked at this again, IMHO this is pretty easy to solve with the new architecture of #4393. :slightly_smiling_face:

See [`f520dc8` (#4393)](https://github.com/contao/contao/pull/4393/commits/f520dc808731eb7d7bfede54b4f18718036c7721).

There `$this->render()` prepares the response - this is what you get when calling `$template->getResponse()` or `$this->render()` in your cotroller's `getResponse()` implementation. You can then alter the response like you want and return it. Alternatively you can pass a fully custom response into either of the functions and that will be used without any modification.

This means in an `AbstractFragmentController` you get the fragment cache tags, in an `AbstractContentElementController` you'll additionally get the shared max age definition by default. And it should not harm custom implementations. :tada:

**Comment by leofeyer** [comment]
See #4407 for a follow-up PR.
