### ISSUE TITLE
Preview-Links: Expiration in Days - Never

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#4388]
### Description

In order to get rid of a htpasswd for staging environments, i started to use the system maintenance. But as of Contao 4.13, you can't send a client a backend user + password anymore to give him access to the frontend. 

Instead you can use the preview links, but have to adjust the expiration date every month, as the maximum value is 30 days. If we have an option Expiration: „Never“, it would make working with clients on a protected installation even easier (no backend user needed at all).

**Comment by aschempp** [comment]
I agree this might be inconvenient, but having a non-expiring access is a security risk imho and should not be allowed. For such cases, having a back end user still works as it did previously. A backend user can have 2FA enforced etc, a preview link URL could accidentally be shared (e.g. through a public WLAN)!

**Comment by denniserdmann** [comment]
> For such cases, having a back end user still works as it did previously

Ah, you're right. In older versions, i was sending the client to directly to the frontend, which is in Contao 4.13 saying, that the service is not available. But if i give him domain.com/preview.php/, it's working as expected. 

Thanks for clarifying that.
