### ISSUE TITLE
Merge auto-submit versions?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#4390]
### Description

As discussed in #4236, we might want to merge auto-submit versions if we can come up with a good strategy.

**Comment by aschempp** [comment]
how about checking the previous/current version when adding an new version whether it contains only one (autosubmitted) field change? Not sure that works if other fields are changes in the form.

**Comment by Toflar** [comment]
Instead of merging, we should try to not create a version at all. Also see https://github.com/contao/contao/issues/4919

**Comment by leofeyer** [comment]
Closing this in favor of #4919.
