### ISSUE TITLE
Failing functional tests after #4376

### ISSUE THREAD

**Issue by aschempp** [contao/contao#4399]
### Affected version(s)

4.13

### Description

I tried to test the changes from https://github.com/contao/contao/pull/4394 but functional tests are not working for me anymore. Most likely because my database schema isn't be reset/tables are not truncated.

I get a lot of `Doctrine\DBAL\Exception\UniqueConstraintViolationException : An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'` errors and then obviously failing routing tests because of incorrect table data.

I dumpted `$truncateTables` in `FunctionalTestCase::resetDatabaseSchema()` and it seems mostly empty or just contain one or two tables, not sure that's supposed to be? Anything I can assist to debug?

/cc @ausi

**Comment by ausi** [comment]
Which MySQL MariaDB version do you use?

**Comment by ausi** [comment]
Does the following line succeed in your setup? https://github.com/contao/contao/blob/3b02c3a8c8e90a6e0c953cb08fec6322c2065082/test-case/src/FunctionalTestCase.php#L56

**Comment by ausi** [comment]
What happens if you change https://github.com/contao/contao/blob/3b02c3a8c8e90a6e0c953cb08fec6322c2065082/test-case/src/FunctionalTestCase.php#L113 to: 
```
WHERE TABLE_SCHEMA = DATABASE()
```

**Comment by aschempp** [comment]
> Which MySQL MariaDB version do you use?

Server-Version: 5.7.34 - MySQL Community Server (GPL)

---

> SET @@SESSION.information_schema_stats_expiry = 0

Running this in PHPStorm Database console gives

```
[HY000][1193] Unknown system variable 'information_schema_stats_expiry'
```

---

> What happens if you change
> 
> https://github.com/contao/contao/blob/3b02c3a8c8e90a6e0c953cb08fec6322c2065082/test-case/src/FunctionalTestCase.php#L113
> 
> to:
> ```
> WHERE TABLE_SCHEMA = DATABASE()
> ```

Then it works! 🎉

**Comment by ausi** [comment]
What happens if you change https://github.com/contao/contao/blob/3b02c3a8c8e90a6e0c953cb08fec6322c2065082/test-case/src/FunctionalTestCase.php#L111 to: 
```
SELECT SQL_NO_CACHE TABLE_NAME
```

and revert the other mentioned changes?

**Comment by aschempp** [comment]
also, the following test seems to be failing now

```
1) Contao\CoreBundle\Tests\Functional\SearchTest::testSearchFor
Failed asserting that 1 is identical to 2.

/Users/aschempp/Projects/Contao/contao/core-bundle/tests/Functional/SearchTest.php:79
```

---

> What happens if you change
> 
> https://github.com/contao/contao/blob/3b02c3a8c8e90a6e0c953cb08fec6322c2065082/test-case/src/FunctionalTestCase.php#L111
> 
> to:
> ```
> SELECT SQL_NO_CACHE TABLE_NAME
> ```
> 
> and revert the other mentioned changes?

That does not seem to work anymore

**Comment by ausi** [comment]
Seems to be an issue with older MySQL versions, not sure how to clear the `information_schema` cache there.

**Comment by m-vo** [comment]
This is really strange. Is caching on the DB side really the problem?

With MySQL 8 the implementation of the information schema tables completely changed and only then started using ached views as an abstraction. Before, things were IMHO not cached at all (which was the root problem and people tried to use optimizations everywhere, see https://dev.mysql.com/doc/refman/5.7/en/information-schema-optimization.html). Could it be that we are running in a false MySQL server side optimization? 

Maybe dumping the output of an `EXPLAIN SELECT …` for the invalid queries could help find the culprit.

**Comment by aschempp** [comment]
closing this for now since noone seems to have the issue anymore
