### ISSUE TITLE
Two different approaches to Symfony Security/Firewall

### ISSUE THREAD

**Issue by aschempp** [contao/contao#44]
I have read up and tested the Symfony Security component to find out how it can be integrated in Contao 4. I think we all agree that we should provide some sort of integration, meaning the visitor could be authenticated inside Symfony components, the profilter etc.

# Background on Security and Firewalls

Symfony uses a so called "firewall" to protect access and authenticate users. In our case, we will need two Symfony firewalls because we have two different users for *fronted* and *backend*. Each firewall is independently configured, e.g. how the user authentication works.

### Authentication vs. Authorization

There is a clear difference between *authenticating a user* and *authorizing access to something* in the Symfony security component. We're only talking about *authentication* here. More info on the topic can be found at http://symfony.com/doc/current/book/security.html

# Implementation options
I came up with two different approaches how to deal with the user authentication.

## Using Contao to authenticate Symfony firewalls

Draft at https://github.com/aschempp/contao-core-bundle/compare/aschempp:feature/no-disableAlias...feature/security

In this approach we use the existing Contao `BackendUser` and `FrontendUser` to authenticate the visitor. The existing Contao classes are basically kept exactly as the are.

On the Symfony side, we add our own authentication management. Instead of letting Symfony store information about the current user in the session, we use the so-called *stateless* option to authenticate the Symfony user on every request by asking the Contao user. As an example, this is similar to using an API token in Symfony to identify the user (it's actually built on that). 

#### Pros
 - The Contao user classes are kept as they are and are 100% backwards compatible
 - People familiar with the Contao authentication system will still know how it works
 - It is still possible to add Symfony security voters to use Symfony for *access authorization*.

## Replacing Contao authentication with Symfony firewalls

Draft at https://github.com/aschempp/contao-core-bundle/compare/aschempp:feature/webprofiler...feature/advanced-security ~~currently only for backend user.~~

The second approach would be to replace the Contao authentication with Symfony security components. Symfony has several built-in user authentication methods, like form login or remember-me cookie.

#### Pros
 - The full power and flexibility of Symfony authentication can be used
 - Symfony developers will be familiar with how it works
 - It would much easier to add new authentication methods like Facebook or Twitter login
 - Developers can use third-party bundles to add new features (see http://knpbundles.com/keyword/authentication)
 - We can still support `BackendUser`/`FrontendUser` for legacy reasons, though the stuff like `tl_session` table needs to be re-engineered.

# Conclusions

I think using the Symfony security/authentication should/will be the "long-termin solution" anyways. It's "only" a question of "when". To me, it's a matter of how much effort we want and can invest into this topic. Adding Contao authentication (option 1) will be much easier in the first place, but I don't know if it will limit the advantages of Contao 4 and the Symfony integration.

/cc @leofeyer @Toflar @discordier

**Comment by leofeyer** [comment]
Can this ticket be closed?

**Comment by aschempp** [comment]
I would keep it because I still want to review options to implement advanced security. Feel free to assign it to me.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/122.
