### ISSUE TITLE
ua::class erzeugt nicht den gewünschten Inhalt

### ISSUE THREAD

**Issue by m-werk** [contao/contao#440]
**Affected version(s)**
4.7.x

**Description**  
Wenn im Frontend die Seite mit "STRG + F5" aktualisiert wird, steht im Quellcode unter body bei `class="win firefox gecko fx66"`. Sobald ich aber NUR F5 drücke, steht folgendes unter Class
`<esi:include src="/_fragment?_hash=1o9ZvXcHbKdlbGmAwX8kU4lAqzuF4VcOvM9rjfcx5S4%3D&_path=insertTag..........`. 
Dies ist bei jedem Browser so. 
In der Versin 4.6.x hab ich dieses phänomen nicht. Auch nicht unter 4.5.x und 4.4.x
Weiters muss noch gesagt werden, dass der Provider easyname ist. 

Wenn ich {{ua::class}} in einen Artikel eingebe, kommt die gleiche Meldung.

Alle Cache-Varianten wurden beim Provider ausgeschalten und auch der Cache von Contao unter var/cache ist leer.
Es gibt auch einen Forumseintrag dafür: https://community.contao.org/de/showthread.php?74621-Text-im-lt-body-gt-woher-kommt-dieser-code&p=501731#post501731

LG, Andi

**Comment by fritzmg** [comment]
I can confirm the problem on easyname. For some reason the esi tags re not replaced.

easyname offers a Varnish cache proxy to all shared hosting customers. However - it is disabled in our case.

**Comment by fritzmg** [comment]
Huh, weirdly, once I logged out of the back end, it suddenly worked. Even after logging into the back end again.

// edit: ah - when I disable the browser cache via the developer tools, the esi tags are replaced

So it appears you cannot disable the cache proxy completely. And if the browser sends a `Cache-Control: no-cache` request header, the esi tags are replaced.

**Comment by m-werk** [comment]
Ok, bei mir ist der Varnish chache auch deaktiviert.

> So it appears you cannot disable the cache proxy completely. If the browser sends a Cache-Control: no-cache request header, the esi tags are replaced.

Was heißt dies jetzt? Können wir was tun?

**Comment by fritzmg** [comment]
See my answer on the forum. Ask easyname to disable the Varnish Cache Proxy completely, because otherwise the esi tags of your web application are not replaced.

**Comment by leofeyer** [comment]
> Ask easyname to disable the Varnish Cache Proxy completely

Das sehe ich auch als die beste Lösung. Alternativ könntest Du folgende Zeilen in der `app.php` anpassen:

```php
//if (null !== $cache->getSurrogate() && !$cache->getSurrogate()->hasSurrogateCapability($request)) {
    $kernel = $cache;
//}
```

Die if-Bedingung ist im originalen Code nicht auskommentiert und sorgt dafür, dass der Symfony Reverse-Proxy deaktiviert wird, wenn der Request bereits von einem ESI-fähigen Proxy wie z.B. Varnish kommt. Das kann aber nur funktionieren, wenn Varnish auch für Contao konfiguriert ist – was es out-of-the-box nicht ist.
