### ISSUE TITLE
Add new DBAL type ascii_bin

### ISSUE THREAD

**Issue by ausi** [contao/contao#4401]
### Description

New type `ascii_string`, similar to `binary_string` in https://github.com/contao/contao/blob/3b7eb6f3dc8c5a46fdb94cedef5d9194e0ee2576/core-bundle/src/Doctrine/DBAL/Types/BinaryStringType.php but for `VARCHAR(…) COLLATE ascii_bin`

Idea © @m-vo

**Comment by aschempp** [comment]
Would the output be any different than the DB value? The `binary_string` type was necessary because Doctrine defaults to returning a stream for any binary data, not because of a "default SQL definition".

**Comment by ausi** [comment]
> Would the output be any different than the DB value?

No.

**Comment by aschempp** [comment]
There is no need for a custom type to support collation. In DBAL types (DCA sql as array), it should work with this:
`'sql' => ['type' => 'string', 'length' => '...', 'options' => ['collate' => 'ascii_bin']]`. We already do exactly that in our SQL string-to-DBAL parser: https://github.com/contao/contao/blob/5.x/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php#L57-L59

The `BinaryStringType` as necessary because we wanted to use the `BlobType`, but prevent the type object from returning a stream instead of the actual binary string.

**Comment by ausi** [comment]
So a custom type would be overengineered you think? 

Can we maybe support an alias instead so that 
```php
array('type'=>'string', 'length'=>64, 'customSchemaOptions'=>array('collation'=>'ascii_bin'))
```
can be written as:
```php
array('type'=>'ascii_string', 'length'=>64)
```

**Comment by aschempp** [comment]
I finally come to understand that this should be DX to solve the MySQL row size problem (https://github.com/contao/contao/pull/4179). So we don't really want an `ascii_bin` type, we want a string type that does not count against the MySQL row size? Technically speaking we could always change how this is done internally (or across platforms)?

**Comment by aschempp** [comment]
also, be aware there is an `AsciiStringType` (`ascii_string`) in Doctrine already 😆

**Comment by ausi** [comment]
> also, be aware there is an `AsciiStringType` (`ascii_string`) in Doctrine already 😆

But sadly that does not use the ascii charset 😔
It basically behaves the exact same way as the `string` type does.

**Comment by leofeyer** [comment]
I‘m in favor of a custom `ascii_bin` type. It is much shorter and since it will be used often, it will improve the DX.

**Comment by ausi** [comment]
> I‘m in favor of a custom `ascii_bin` type.

I just tried to implement this but it seems to me that this is not possible with doctrine as collation, charset and type are three different concepts that can not be set with one single column type.
It works technically but the comparator fails then because the charset info appears twice in the resulting SQL string then.

If someone wants to take a look at this, here is my failed attempt: https://github.com/ausi/contao-contao/commit/39fe07963e13f405cef3b19e2d4af855116ad2a1

**Comment by leofeyer** [comment]
That‘s a pity. 😢

**Comment by Toflar** [comment]
Maybe in combination with events?

**Comment by leofeyer** [comment]
We don't need to force it. As we already have a working solution, I am closing this ticket for the time being.
