### ISSUE TITLE
Content Element HTML without sanitization

### ISSUE THREAD

**Issue by ausi** [contao/contao#4405]
### Description

It would be great to have a second HTML element and HTML module that completely skips sanitization. This might be available only to administrators or should be disabled by default for regular backend users.

**Comment by Toflar** [comment]
Marking this `up for discussion` because the implementation should be rather easy but naming will be hard 🙈

**Comment by m-vo** [comment]
Isn't this effectively the `TemplateController` element with a custom template?

**Comment by Toflar** [comment]
I don't want to allow admins access to the templates section because then they can also override core templates. This kills versioning.

**Comment by aschempp** [comment]
Sounds like a checkbox in the HTML element to me? But I don't really understand why we added the template element and now also need this?

**Comment by Toflar** [comment]
I already gave the reason why. And a checkbox isn't the solution because users without permission must not be able to edit the element.

**Comment by aschempp** [comment]
> And a checkbox isn't the solution because users without permission must not be able to edit the element.

You can also give permissions on a checkbox? or do you mean they should not be able to edit the element then? And there's really a use case for having both? One that you/admin uses and one that regular users use? Or would you then just disallow HTML element in general?

**Comment by Toflar** [comment]
Yeah that's exactly the problem. The permission on the checkbox doesn't help because then I can access an element created by an admin and edit the HTML and it will suddenly get filtered.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to call it "unfiltered HTML" element.

**Comment by ausi** [comment]
Closed in favor of #4749
