### ISSUE TITLE
Backend dropzone fileuploader - z-index des X-Icon ist höher als <header>

### ISSUE THREAD

**Issue by berecont** [contao/contao#4406]
### Affected version(s)

4.9.27

### Description

z-index von `<div class="dz-success-mark">` ist höher gesetzt als `<header id="header">`.
Somit wird das X-icon über dem orangen Header dargestellt.
In meinem Fall ist die Erweiterung [om-backend] im Einsatz, die den z-index von 100 setzt. Doch ich konnte auch im Core keinen Eintrag finden, der den z-index des `<header>` höher als das Fehler-Icon setzt.

![zindex](https://user-images.githubusercontent.com/33038265/160470785-34d5d0e9-e164-43ee-9ca7-82b2a052136c.jpg)

**Comment by leofeyer** [comment]
Are you using a custom back end theme? Because the top bar is not fixed on my system.

**Comment by berecont** [comment]
yes - [omosde/contao-om-backend]

**Comment by leofeyer** [comment]
Then please report the bug there.
