### ISSUE TITLE
Consider keeping unknown insert tags as plain strings

### ISSUE THREAD

**Issue by m-vo** [contao/contao#4409]
### Description

Currently, insert tags that do not exist are replaced with an empty string. We should IMHO consider changing this in Contao 5 and rather treat unknown insert tags as plain strings. Example: `<{{foobar}}div>` will then remain `<{{foobar}}div>` instead of resulting in a valid div tag. 

Yes, it has always been like this, but it will make sanitization simpler and lower the attack surface, which, to me, is more important.

**Comment by cliffparnitzky** [comment]
Generally I'm am on both sides. On the one hand it is great, that a non existing insert tag doesn't destroy the output in the frontend. On the other hand it is very hard to find broken insert tags. Maybe it is an idea to implement something like a switch, e.g. in production mode inserttags are replaced like it has always been and in debug mode they are not replaced with an empty string.

**Comment by m-vo** [comment]
> On the other hand it is very hard to find broken insert tags.

Unknown insert tags are already logged.

> Maybe it is an idea to implement something like a switch, e.g. in production mode inserttags are replaced like it has always been and in debug mode they are not replaced with an empty string.

If necessary, I'd rather have a config switch than a different output depending on the environment. Again for sanity. :slightly_smiling_face:

**Comment by fritzmg** [comment]
> > On the other hand it is very hard to find broken insert tags.
> 
> Unknown insert tags are already logged.

@m-vo the logging does not really help in finding them.

**Comment by m-vo** [comment]
I don't understand the problem, if an insert tag is not replaced with an empty string, but kept, the front end won't be "destroyed".  You can simply hit ctrl+f and search for double curly braces to find them?

**Comment by aschempp** [comment]
> but it will make sanitization simpler and lower the attack surface

Can you explain that?

In my (current) opinion, removing them is correct. We are building a CMS that is supposed to generate useful webpage content **for visitors**, not for developers or sanitizers. If it is hard to debug, we need to improve debugging options (like log the current page, a PR has already been drafted). We should jot make the journey for visitors worse.

**Comment by m-vo** [comment]
Is this evil? Try checking for this: 
`ev{{non-existing}}il`

I do neither get why it's harder to debug something that you can see instead of something that you can't nor why this worsens the experience for visitors. Can you give an example where this would be the case?

**Comment by leofeyer** [comment]
I‘m for keeping unknown insert tags visible, too.

**Comment by aschempp** [comment]
> Can you give an example where this would be the case?

Not sure what example exactly. I have seen LOTS of systems with backend log messages about unknown insert tags. People don't check the logs. They wouldn't notice if they appear in the front end, the webpage would just show "invalid" stuff. Its similar to the discussion we had in https://github.com/contao/contao/issues/4142, though I agree an exception is worse than an invalid insert tag on the page 😉

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to show unknown insert tags in the future.

<img width="579" alt="" src="https://user-images.githubusercontent.com/1192057/166949768-84602f45-ad0c-4c90-96e5-8d5e46053153.png">

**Comment by asaage** [comment]
My prefered solution would be to definitely keep the Log-entry and to output them in html-comments like
```<!-- {{foobar}} -->``` so jou can find them in source.
Having them visible does not feel right.

**Comment by ausi** [comment]
> My prefered solution would be to definitely keep the Log-entry and to output them in html-comments like

This is impossible as it would close existing HTML comments (and is therefore dangerous regarding XSS).

Example before:

```html
<!-- <div title="{{foobar}}">baz</div> -->
```

After:

```html
<!-- <div title="<!-- {{foobar}} -->">baz</div> -->
```
