### ISSUE TITLE
Spam Score issue with newsletter unsubscribe header

### ISSUE THREAD

**Issue by aschempp** [contao/contao#4412]
### Affected version(s)

4.9

### Description

In https://github.com/contao/contao/issues/2174 we added a `List-Unsubscribe` header to the Contao newsletter module. In my case, the email content has this header:

```
List-Unsubscribe: <mailto:newsletter@example.com?subject=K%C3%BCndigen>
```

As you can see, it contains encoded umlauts due to the included german translation. I tested my newsletter email with mailtrap.io, and it reported a spam score for `UNRESOLVED_TEMPLATE`. This seems to be a SpamAssassin rule which I found in https://opensource.apple.com/source/SpamAssassin/SpamAssassin-124.3/SpamAssassin/rules/20_head_tests.cf

The regular expression `/^(?!(?i:X-UIDL|X-Face|To|Cc|From|Subject|References|In-Reply-To|(?:X-|Resent-|X-Original-)?Message-Id):)[\w-]{1,24}:(?:[^\n]{0,100}|\n[ \t]){0,2}%[A-Z][A-Z_-]/m` matches our header because of the umlaut characters in the email subject. That sure looks like a false positive, but it negatively impacts the spam score "for now reason".

I would suggest to change the german translation, maybe to `Newsletter-Abmeldung` like in the original issue. Not sure if we can implement a generic fix for all languages...
Since the `$GLOBALS['TL_LANG']['MSC']['unsubscribe']` labels is also used in the front end modules, we might need to add an additional label for it?

**Comment by fritzmg** [comment]
May be it would be better to implement a "real" unsubscribe URL this time around? Instead of a simple `mailto:`. (At least in Contao 5.0.)

**Comment by Toflar** [comment]
Mailchimp does that too, by the way...

**Comment by aschempp** [comment]
> Mailchimp does that too, by the way...

does what too? The umlauts or the unsubscribe mail/link?

**Comment by fritzmg** [comment]
MailChimp provides both:

```
List-Unsubscribe: <https://cityfibre.us19.list-manage.com/unsubscribe?u=…&id=…&e=…&c=…>, <mailto:unsubscribe-mc.us19_….…-…@unsubscribe.mailchimpapp.net?subject=unsubscribe>
```

However, both will be automatically processed - whereas in Contao's case it's just a simple email to the site's admin.

**Comment by aschempp** [comment]
yeah the only thing I can imagine is linking an unsubscribe page/module in the newsletter channel. But that's not really the topic of this issue 😂

**Comment by fritzmg** [comment]
Yes, I am in favour of changing the translation to something without Umlauts in Contao 4.9+ - but implement a proper unsubscribe page and module in Contao 5.0 that the newsletter can link to.

**Comment by leofeyer** [comment]
How about using `(new UnicodeString($GLOBALS['TL_LANG']['MSC']['unsubscribe']))->ascii()->toString()`?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to use `Unsubscribe` without translation.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4493
