### ISSUE TITLE
Make Twig templates createable in the Contao backend

### ISSUE THREAD

**Issue by andyKempf** [contao/contao#4413]
### Description

Hello all,
first of all thank you for this great CMS!

I think it's great that there is Twig support now.

Would it be possible, when a new template is created, to create it also as *.html.twig file? So far it is created as .html5 file by default.

Many thanks and best regards from Munich
Andi

![Bildschirmfoto 2022-03-29 um 23 51 31](https://user-images.githubusercontent.com/48767191/160713922-32153148-330b-481a-ae03-87bd01c04ac6.png)

**Comment by fkaminski** [comment]
This and other features around Twig will certainly be implemented in the future. 
See also: https://github.com/contao/contao/projects/4

**Comment by andyKempf** [comment]
@fkaminski, thanks for your feedback!
Sounds cool! 😎

**Comment by andyKempf** [comment]
Hey @leofeyer, 
if this is already planned for Contao 5, should I close this ticket? :) 
Wenn das ohnehin schon für Contao 5 geplant ist, soll ich dieses Ticket schließen?

Many greetings from Munich
Andi

**Comment by leofeyer** [comment]
@m-vo /cc

**Comment by m-vo** [comment]
We can leave this issue open and I'll close it once I'm working on this topic again.

Though I strongly suggest to use an external editor if you can. We probably won't ever be able to support auto completion, auto formatting, type hinting and all the things a real IDE/editor can provide. 

Edit: just realized this is about creating templates. This definitively needs a makeover. :smile:

**Comment by m-vo** [comment]
related #2477 (this one is for bundle templates, though, which we should not make accessible anymore in the BE)

**Comment by m-vo** [comment]
I just realized this issue already existed after I commented on its duplicate (#5223). :see_no_evil:. I'll still close this in favor of #5223 as the other now contains more information. Feel free to follow on there. Thanks for the report!
