### ISSUE TITLE
Frontend-Module editor is not displayed at first

### ISSUE THREAD

**Issue by andyKempf** [contao/contao#4414]
### Affected version(s)

4.13.1

### Description

Hi and Servus!
When I create a new frontend module via the Themes menu item, the "Navigation Menu" module type is selected by default. However, the editor for this is not displayed to me.

Only when I click on Save, the editor is displayed.

Maybe it's a bug? (The behavior seems a bit strange to me)

What do you think? My version is 4.13.1
![Bildschirmfoto 2022-03-30 um 00 04 28](https://user-images.githubusercontent.com/48767191/160715114-5bb454eb-3d4a-4c29-b967-f3faf5f6cba9.png)

Many greetings from Munich
Andi

**Comment by m-vo** [comment]
After clicking create (and before doing anything else), can you check what's in the `type` column of the newly created database entry? For example by running `SELECT type FROM tl_module WHERE id=<id>` with the displayed ID.

**Comment by cliffparnitzky** [comment]
Can't confirm. Neither in my own environment nor in the demo system.

**Comment by andyKempf** [comment]
Hi @m-vo,
thanks for your feedback. 

After I clicked "New" to create a new frontend module, that's in the database:

(ID # 9)
![Bildschirmfoto 2022-03-30 um 02 27 40](https://user-images.githubusercontent.com/48767191/160727422-71a9c5a6-78de-4354-8d46-ab9112292d23.png)


(The type is empty)

**Comment by andyKempf** [comment]
@cliffparnitzky @m-vo,
I made a video with the behavior:


https://user-images.githubusercontent.com/48767191/160727067-2a6858cd-701a-4c68-b1d4-a5f7daf1394c.mov

**Comment by m-vo** [comment]
Maybe an extension is overwriting the default value? You can check by running `vendor/bin/contao-console debug:dca tl_module | grep '"type" => array' -A 25` on the console. The `sql` key should look like this: `"sql" => "varchar(64) NOT NULL default 'navigation'"
`

If this is the case, please make sure, your schema is up to date by running `vendor/bin/contao-console contao:migrate`.

**Comment by cliffparnitzky** [comment]
Yes. There is at least one 3-party extension installed, as you can see the menu entry "Meine Inhaltselemente" which is not part of Contao core.

If the hint of @m-vo doesn't help, deinstall all 3-party extensions and then check the behaviour.

**Comment by andyKempf** [comment]
Hi @cliffparnitzky and @m-vo,
Ah sorry, I see. You're right, there's a bug from the third party plugin 'pct_customelements'.
 
Please can you close this ticket?

Have a nice day and many greetings from Munich
Andi
