### ISSUE TITLE
Custom Template with help or description possibilities

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#4419]
### Description

~Would it be technically possible for the "custom template" to specify different, correct values (only admin), 
which can then be selected by editors?~

Or at least as admin to store a description that then editors can only read.

**Comment by leofeyer** [comment]
What exactly do you mean?

**Comment by fkaminski** [comment]
If different values/inputs were possible for a key (depending on the template), it would be helpful to be able to specify this (as admin) in a description for users (or in principle).

**Comment by leofeyer** [comment]
I still don‘t know what you mean. Sorry. 🙈

**Comment by fkaminski** [comment]
Thought of something like this (in the sense of RSCE-Lite :smile: )

![image](https://user-images.githubusercontent.com/7679799/198082102-a90aadab-1a20-44ae-b3ca-1a458af496f9.png)

![image](https://user-images.githubusercontent.com/7679799/198082213-bd8a0329-1ba9-41bf-a0c5-4baae6363d02.png)

**Comment by m-vo** [comment]
In case you want this, just create your own fragment with properly named fields.

**Comment by fkaminski** [comment]
Thank you. I close this because in general it would not be so important and there are alternatives.
