### ISSUE TITLE
Remove width and height from audio in ce_player template

### ISSUE THREAD

**Issue by Aybee** [contao/contao#442]
**Affected version(s)**
4.4.36

**Description**  
Das Template ce_player gibt das hier aus.
```html
<audio width="400" height="40" preload="none" controls="">
```
Mein Validator gibt diese Meldung aus:
> Fehler: Attribute “width” not allowed on element “audio” at this point.
Fehler: Attribute “height” not allowed on element “audio” at this point.

Im Template erfolgt die Ausgabe und sollte entfernt werden.
```php
<audio<?= $this->size ?> 
```
Der Audioplayer im Chrome/Opera hat übrigens eine Höhe von 54px, IE/EDGE 30px und der im FF eine von 40px, egal was in height steht. CSS `height: auto;` sorgt in Chrome/Opera dafür, dass der Audio-Player nicht mehr sichtbar ist.

**How to reproduce**  
Erstelle ein CE-Audio und schaue in den Quelltext. Validiere das HTML.

**Comment by leofeyer** [comment]
Behoben in 8ea14b33b7e3f4e828a5b86b9d60a3daefd73889.

**Comment by Aybee** [comment]
Thank you .
