### ISSUE TITLE
Increase compatibility between MariaDB and MySQL 8 in contao:backup tasks

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#4420]
### Description

As discussed in Slack, `contao:backup:create` in a MariaDB instance creates a dump that is not importable in MySQL 8, because ` groups` is a reserved keyword in MySQL 8 and needs backticks like 
```
`groups`
```

**Comment by Toflar** [comment]
As already stated and for future reference: I'm all for supporting this very use case but `contao:backup:*` was **NOT** created to create cross-platform backups. They are specifically designed to backup and restore on **the same system**. Using it to export from one system to another one with a different database **is not a supported use case**. It might work and if the amount of work to have things compatible justifies a change (like e.g. supporting `groups`) we can add it but we should definitely draw a clear line at some point. Maintenance work must be considered.
