### ISSUE TITLE
Set default Viewport-tag

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#4436]
### Description

https://docs.contao.org/manual/en/layout/theme-manager/manage-page-layouts/#expert-settings

The FE output
`<meta name="viewport" content="width=device-width,initial-scale=1.0">`
currently only occurs when

- responsive.css is selected or
- the "Viewport-tag" entry is set manually

It would be easier & clearer if the "viewport-tag" entry is set by default with: 
`width=device-width, initial-scale=1.0`

**Comment by Tastaturberuf** [comment]
I like that, but what if someone want do have it empty?

**Comment by fritzmg** [comment]
> I like that, but what if someone want do have it empty?

It could be implemented as the default value on the database level, then you can still set it to empty (and it would not affect existing installations).

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to make `width=device-width,initial-scale=1.0,shrink-to-fit=no` the default value in the database.
