### ISSUE TITLE
Feature: ce_player default volume

### ISSUE THREAD

**Issue by kroerig** [contao/contao#444]
Hallo,

ich fände es schön, wenn man im Backend beim ce_player zusätzlich zu den Start/ Stoppstellen auch die initiale Lautstärke angeben könnte.
Aktuell starten alle Medienelemente immer auf 100% und der Zuhörer muss (je nach Inhalt) erst mal schnell den Regel runter drehen um aus dem Stuhl geblasen zu werden.

Und dann wäre es sehr schön, wenn auch bei der Wiedergabe eines Audiofiles bereits vor dem Start die Gesamtlaufzeit angezeigt werden könnte.

**Comment by asaage** [comment]
> Und dann wäre es sehr schön, wenn auch bei der Wiedergabe eines Audiofiles bereits vor dem Start die Gesamtlaufzeit angezeigt werden könnte.

das geht nicht weil ```preload="none``` für audio hartcodiert ist https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/templates/elements/ce_player.html5#L13

Ich kenne den Grund dafür nicht aber wenn man das Template an dieser Stelle in ```preload="<?= $this->preload ?>"``` ändert kann man die Gesamtlaufzeit vorab anzeigen lassen.

Was das default-volume betrifft - halte ich alles was von 100% abweicht für abwegig.
Besser: direkt bei der Aufnahme/Encoding auf einen vernünftigen Pegel achten.

**Comment by leofeyer** [comment]
> Was das default-volume betrifft - halte ich alles was von 100% abweicht für abwegig.

Ich auch ehrlich gesagt. Hab gerade mal bei YouTube, Vimeo, Spotify und Co nachgesehen und auch dort starten die Videos immer auf 100% Lautstärke.

> das geht nicht weil `preload="none"` für audio hartcodiert ist 

Das sollten wir vielleicht ändern.

**Comment by asaage** [comment]
Lautstärke als Attribut scheint auch nicht so wirklich die beste Browserunterstützung zu haben.
Ich hab diesen Link (https://html.com/attributes/audio-volume/) mit Chrome, Edge und Firefox getestet und hab immer 100%.

**Comment by leofeyer** [comment]
>> das geht nicht weil preload="none" für audio hartcodiert ist
>
> Das sollten wir vielleicht ändern.

Behoben in 8d93ac5ede75d1e0b61b7e974f86b2e244f06564.
