### ISSUE TITLE
Feature: Ping-Attribut für Links

### ISSUE THREAD

**Issue by kroerig** [contao/contao#445]
Nicht das ich es wirklich brauche, aber der ein oder andere möchte vielleicht doch Tracking nutzen.
Sollte Contao das Attribut vielleicht auch unterstützen?
https://heise.de/-4404235

**Comment by leofeyer** [comment]
Wie genau würdest Du Dir die Integration in Contao denn vorstellen?

**Comment by kroerig** [comment]
Wenn ich das Prinzip dies Attributs richtig verstanden habe, dann müssten die Optionen für Hyperlinks um einen Eintrag erweitert werden, in den man dann eine URL eintragen kann, also wie das alt- und title-Attribut.

Ggf. stellt man es auch nur als Bundle bereit, dass diejenigen nachinstallieren können, die die Funktion benötigen.

**Comment by Toflar** [comment]
Dann müsstest du ja für jeden Link einen eigenen Tracking-Endpoint bauen. Du würdest ja wissen wollen, welcher Link geklickt wurde. Mal angenommen du willst 50 Links tracken und jetzt ändert sich die URL, müsstest du 50 Einträge aktualisieren. Ich halte das nicht für sonderlich praktisch und würde eine JS-Lösung immer vorziehen. Zumal Tracking ja schon auch sehr individuell sein kann.

**Comment by kroerig** [comment]
Ich bin kein Freund von Tracking und brauche es auch nicht.
In dem Artikel steht ja, dass diese Methode auch funktioniert, wenn der Anwender JS blockiert. Wer es dann auf diese Art nutzen will, müsste sich dann halt die Mühe machen. Kommt wohl auch darauf an, wie das Tracking-Tool arbeitet.

Übermittelt werden laut Artikel Quelle und Ziel des Aufrufs. Also könnte auch eine globale Ping-URL im Startpunkt einer Webseite reichen, die dann an jedes href-Element angefügt wird.

**Comment by Toflar** [comment]
Okay. Also ich sehe hier absolut keinen Mehrwert und bin daher gegen eine Integration im Core.

**Comment by kroerig** [comment]
Ich denke mir es könnte vielleicht von dem ein oder anderen Entscheider positiv bewertet werden.
Es soll ja Firmen geben, die Tracken wollen, was das Internet hergibt.

**Comment by m-vo** [comment]
Das lässt sich auch gut als Erweiterung umsetzen. Ich sehe derzeit auch keinen Grund das im Core zu haben.

**Comment by kroerig** [comment]
Hatte ich ja oben geschrieben, wobei der Aufwand vermutlich der selbe sein wird. Und vermutlich muss auch das ein oder andere Template angepasst werden, oder?
