### ISSUE TITLE
Version conflict with only one user

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#4454]
### Affected version(s)

4.9.28 & 4.13.2

### Description

https://demo.contao.org/contao

Content > Articles > Home

- Create a new content element (Element type: Text)
- Add a text in the text field
- Add an image and click save
- Disable Add an image and click save
- A version conflict shows up

When you now enable or disable the Add an image the version conflict always shows up.

**Comment by ausi** [comment]
This is probably caused by #4236 😕

I think we have to update the hidden field that stores the current version after the ajax request of a checkbox subpalette.

**Comment by aschempp** [comment]
or merge the versions as suggested in #4390

**Comment by ausi** [comment]
How would merging the versions solve the conflict detection?

A conflict should still be detected if two users use a subpalette checkbox simultaneously I think.

**Comment by aschempp** [comment]
I did not investigate how the conflict is detected, but I would assume both is done by the version class that should merge before conflict 🙃

**Comment by ausi** [comment]
> I would assume both is done by the version class

No, DC_Table handles the conflict: https://github.com/contao/contao/blob/07422feccd4792012f0c480f7300eadf498618d3/core-bundle/src/Resources/contao/drivers/DC_Table.php#L2159-L2160

**Comment by ausi** [comment]
Should be fixed by #4470

Thank you @netzarbeiter for the example of a perfect bug description ❤️
