### ISSUE TITLE
Missing scope attribute in request object

### ISSUE THREAD

**Issue by koertho** [contao/contao#446]
**Affected version(s)**
Occured in 4.7.4
Works in 4.4.38

**Description**  
Scope Matcher can't be used to detect if frontend or backed, since `scopeMatcher->isFrontendRequest()` always returning false. The problem is, that the request object does not contain the _scope attribute. The TL_MODE variable still works, cause the ContaoFramework constructor has the variable already set.

**How to reproduce**  
Install Contao with Contao Manager (this is what I did).
Use the scope matcher as descriped in [DEPRECATED.md](https://github.com/contao/contao/blob/master/DEPRECATED.md)

**Comment by leofeyer** [comment]
How exactly are you using the scope matcher?

**Comment by koertho** [comment]
@leofeyer As I wrote, like in the DEPRECATE file. Here is the code:

```
public function getCurrentRequest()
{
    return $this->container->get('request_stack')->getCurrentRequest();
}

public function isFrontend()
{
    if ($request = $this->getCurrentRequest()) {
        return $this->scopeMatcher->isFrontendRequest($request);
    }
    return false;
}
```
Source: https://github.com/heimrichhannot/contao-utils-bundle/blob/master/src/Container/ContainerUtil.php

**Comment by leofeyer** [comment]
I assume that you are using the scope matcher in a listener, which runs before the routing. Can you provide a stack trace?

**Comment by koertho** [comment]
@leofeyer We're using it in the bundle contao config.php file. I think thats enough stacktrace? :)

```php
// src/Resources/contao/config/config.php
if (\Contao\System::getContainer()->get('huh.utils.container')->isFrontend()) { 
    // add frontend specific assets
}
```

Here is the original: 
https://github.com/heimrichhannot/contao-slick-bundle/blob/5f1b4cc4cc8fc07f395db7140018b87cb071ac9e/src/Resources/contao/config/config.php#L90

Error still exists in 4.7.5.

**Comment by leofeyer** [comment]
The `config.php` file is loaded when the Contao framework is initialized and this happens before the routing (actually the routing first initializes the framework). You therefore cannot use the scope matcher in the `config.php` file. Maybe you can use an event to add the assets?

**Comment by fritzmg** [comment]
Hm, may be we should add that to UPGRADING under __Version 4.* to 4.7__?

**Comment by leofeyer** [comment]
Only if @aschempp confirms that I'm right. 😄

**Comment by Toflar** [comment]
That's not something that needs to be documented, imho. The `config.php` is configuration. It configures things. It doesn't know about anything and should not be dependent on runtime. I know it was possible to do some `TL_MODE` comparisons etc. back in the day and many extensions did it or still do it. But technically, it has always been wrong.
If you want to decide something at runtime, the config should register listeners and they then decide what to do.

**Comment by aschempp** [comment]
Agreed with @Toflar. Also, if you write "old" stuff in `config.php`, simply use `TL_MODE`.

**Comment by koertho** [comment]
I think this must be documented, since the config.php is still needed for some cases, especially in 4.4. So when something is deprecated, the replacement must work everywhere, where the deprecated thing was used before (my opinion). At least a short note about this would be helpful for a lot of developers I think. 
I know that the config.php is not the best place for comparisons like this, but that's the way a lot of module/bundles where written in the past.

**Comment by Toflar** [comment]
I don't think we need to document anything here, no. There is no "replacement" and we did not "deprecate" anything. It just used to work by chance but the `config.php` always was a configuration file and you are not supposed to add if statements to a configuration file. Just don't do it and it will work in all versions.

It's just the fact that `config.php` is a php file so you can do whatever you want to do in it. Same as with our templates. You can also execute database queries in templates. Just because it works doesn't mean it's correct and a supported use case that will always be supported.

**Comment by fritzmg** [comment]
The news-bundle for example does the same though.

https://github.com/contao/contao/blob/69ca06aacc6ee5513a63fe2447603b63ee84f864/news-bundle/src/Resources/contao/config/config.php#L37-L41

On that note: do we have a recommended new way for this yet? In one project I used the `kernel.controller` event with a subscriber:

```php
use Contao\CoreBundle\Routing\ScopeMatcher;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\KernelEvent;
use Symfony\Component\HttpKernel\KernelEvents;

class ControllerSubscriber implements EventSubscriberInterface
{
    protected $scopeMatcher;

    public function __construct(ScopeMatcher $scopeMatcher)
    {
        $this->scopeMatcher = $scopeMatcher;
    }

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::CONTROLLER => [
                ['onKernelController', 0],
            ],
        ];
    }

    public function onKernelController(KernelEvent $e): void
    {
        $request = $e->getRequest();

        if ($this->scopeMatcher->isBackendRequest($request)) {
            if (!isset($GLOBALS['TL_JAVASCRIPT'])) {
                $GLOBALS['TL_JAVASCRIPT'] = [];
            }

            $GLOBALS['TL_JAVASCRIPT'][] = 'https://kit.fontawesome.com/5bcf1883c4.js';
        }
    }
}
```
Not sure if there is a more elegant or simpler way.
