### ISSUE TITLE
Dashboard version compare does not work

### ISSUE THREAD

**Issue by jonnysp** [contao/contao#4460]
### Affected version(s)

4.13.2

### Description

I noticed today, when i click on show differences, the window shows the dashboard again
![grafik](https://user-images.githubusercontent.com/1651241/161908563-f460db43-5202-44df-b156-a05774fa3fa0.png)
![grafik](https://user-images.githubusercontent.com/1651241/161908601-c8c50298-1b9d-48ad-9a67-c3d99154488e.png)

after closing and reloading, another version was created, and so on.

![grafik](https://user-images.githubusercontent.com/1651241/161908785-a5118f20-b572-4962-9388-1e640f6391c4.png)

I have this on 2 installations, I think that's not right.

**Comment by jonnysp** [comment]
it even reverses the change, in my case the show hide setting of an article.

something similar happens when the pen is clicked, only it jumps to the article.

**Comment by Toflar** [comment]
Cannot confirm on demo.contao.org. Can you try to create a reproducible case on demo.contao.org for us?

**Comment by jonnysp** [comment]
i don't have access to demo.contao.org/contao-manager.
update to latest and clear all caches. i have testet on local and hostet contao versions

**Comment by Toflar** [comment]
Why would you access the Contao Manager?? We're talking about the back end here, right? If you login to https://demo.contao.org/contao and edit content (to create some versions) and go to the dashboard, everything works fine. Which means that this problem cannot be reproduced and we have to close the issue. If you find a way to reproduce, we can look at it and fix it.

**Comment by leofeyer** [comment]
I cannot confirm this in the online demo, either.

**Comment by jonnysp** [comment]
i have testet on more as 5 different installations

- localhost XAMPP php 7.5 
- HE PHP 8.0.16 
- ALLInkl PHP 8.0.16
- 1&1 PHP 7.4.28
- ...

this was today after package update!
I will create a new fresh version and report

**Comment by jonnysp** [comment]
now i have it on demo contao!
![grafik](https://user-images.githubusercontent.com/1651241/161946310-29fc5074-80f3-441e-b90d-44ccabbc2cf8.png)

**Comment by fritzmg** [comment]
> now i have it on demo contao!

I can confirm the issue on demo.contao.org now as well. What are the exact reproduction steps to get there?

**Comment by jonnysp** [comment]
its when the activity as toggle "act=toggle".

open article or faq or comments and toggle ON/OFF then go back to Dashbord!

**Comment by fritzmg** [comment]
> open article or faq or comments and toggle ON/OFF then go back to Dashbord!

Toggle what exactly on/off? You mean the published state?

**Comment by jonnysp** [comment]
![grafik](https://user-images.githubusercontent.com/1651241/161961201-ac65af90-bb71-4fbb-a576-799956b57be7.png)
"veröffentlichen/unveröffentlichen"

**Comment by fritzmg** [comment]
I can confirm the reproduction.

1. Go to _Content_ » _Articles_.
2. Click the publish toggle <img src="https://demo.contao.org/system/themes/flexible/icons/visible.svg" width="16"> for any article.
3. Go to the dashboard.
4. There will be a new **Latest changes** entry for the toggle operation.
5. Click _Show differences_ <img src="https://demo.contao.org/system/themes/flexible/icons/diff.svg" width="16"> for that entry.
6. This will show the dashboard in the overlay and not the differences view.
7. Close the overlay and reload the dashbaord.
8. There will be a _new_ **Latest changes** entry for the toggle operation. i.e. the toggle operation was somehow repeated by opening the differences view.

**Comment by jonnysp** [comment]
On edit in dashboard ![grafik](https://user-images.githubusercontent.com/1651241/161965636-1251a0b2-1322-46e9-b01b-6acc15d5046f.png) also toggle the operation and redirect to the article! maybe it help.
