### ISSUE TITLE
On multiple day events all days are marked as current

### ISSUE THREAD

**Issue by joehi** [contao/contao#447]
**Affected version(s)**
Contao 4.7.4
Contao 4.4.38

**Description**  
On multiple day events in the modules *** EVENT LIST *** (option Shortened view not activated) or *** CALENDAR *** all individual days are marked with the class 'current', even if the first days are already in the past and should be marked with the class 'bygone' or the last days are in the future and should be marked with the class 'upcoming', as it is with other single day events from that same day.

**How to reproduce**  
Create a multiple day event which starts two to three days in the past from now and ends a few days in the future. Add single day events for these days as well. Look at the '<div class="event ...' tags and whether they are of the class 'bygone' or 'current' or 'upcoming'. Only the day of this multiple day event with today's date should be marked with 'current' in my opinion.

To visualize this, you can use the following CSS:

```
.event.bygone {
    background-color:#ff8080; /* red */
}
.event.current {
    background-color:#ffc080; /* orange */
}
.event.upcoming {
    background-color:#80ff80; /* green */
}
```

Not sure if this could be considered a bug or a feature request.

**Comment by fritzmg** [comment]
This is not an error imho. If you have an event, that occurs on multiple days, but does not span multiple days, then you should use recurrence.

**Comment by joehi** [comment]
I am talking about an event that spans multiple days. For example an anniversary weekend that would start on Friday and ends on Sunday.

**Comment by fritzmg** [comment]
Yes, then all days of the event should be marked as `current` in my opinion.

**Comment by joehi** [comment]
That is the case as of now. And in some way I understand your opinion. But it results in a strange list.

I list all feature events and also the events from the last seven days by including two modules of the event-list with different settings (first: last 7 days, second: all future events) on my page.  Using just one module of the event-list where you chose to list all events would produce the same result.

With CSS I grey out all events marked "bygone". If there is a multiple day events as described above it looks quite inconsistent with events marked "bygone" and days of the multiple day event marked "current" and events marked "future" all mixed together.

**Comment by asaage** [comment]
A multiple-day-event is still **one** event and should be treated as a union. It can't be "bygone" until it's completely done.
