### ISSUE TITLE
File picker background images not working in internal css editor

### ISSUE THREAD

**Issue by tintifaxxx** [contao/contao#4473]
### Affected version(s)

4.13.1, 4.13.2

### Description

The file picker for background images in the internal css editor ist not working properly anymore.
You can choose the directory, but no file is listed and so its not possible to select/change any image.
Old path after update from 4.9 => 4.13 is still available and working.
Maybe its not worth to fix anymore, cause css editor is history from Contao 5 onwards, but a bug is still a bug.

**Comment by ausi** [comment]
The picker URL looks like https://demo.contao.org/contao/picker?context=file&extras%5Bdo%5D=files&extras%5Bicon%5D=pickfile.svg&extras%5BfieldType%5D=radio&extras%5BfilesOnly%5D=1&extras%5Bextensions%5D=%25contao.image.valid_extensions%25&value=

The `contao.image.valid_extensions` parameter seems to be not resolved.
