### ISSUE TITLE
Display ongoing event

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#4476]
### Affected version(s)

4.9

### Description

Ich habe bei einer Kundin Probleme mit der Anzeige Logik bei laufenden Events. 
Um das Verhalten von Contao zu reproduzieren habe ich mir in einer Testinstallation drei Events angelegt und versucht alle Anzeige-Varianten durchzuspielen.
1. Event mit dem aktuellen Datum, ohne Uhrzeit
2. Event mit dem aktuellen Datum und mit Startzeit in der Vergangenheit, ohne Endzeit
3. Event mit dem aktuellen Datum und mit Startzeit in der Zukunft, ohne Endzeit

Nach meinem Verständnis sollten in der Liste für zukünftige Elemente am Tag mit dem aktuellen Datum (heute) alle drei Elemente angezeigt werden, wenn die Checkbox "laufendes Event ausblenden" nicht angehakt ist.

Leider werden aber nur das Element ohne Uhrzeit und das Elemente mit Uhrzeit in der Zukunft angezeigt und zwar nur dann wenn ich verkürzte Darstellung anhake. Ohne verkürzte Darstellung wird nur das Event mit Uhrzeit in der Zukunft angezeigt.
Soll das so?
Ich finde das leicht verwirrend. Es ist für mich von der Logik her nicht klar nachzuvollziehen. Vielleicht liegt das auch an mir. 

Contao 4.9.28
PHP 7.4.
XAMPP
neue leere Testinstallation auschließlich mit den Erweiterungen Easy-Themes (terminal42) und M17-Sticky-Backend-Footer (jrgregory)
keine Templateanpassungen
Listentemplate "upcoming events", Anzeigemodus "alle zukünftigen Events"
Das Problem tritt aber auch bei anderen Anzeigenmodi und der Verwendung anderer Templates auf

**Comment by ausi** [comment]
Ich kann das Verhalten reproduzieren.

Meiner Meinung nach sollte:

1. Die Checkbox „verkürzte Darstellung“ keinen Unterschied machen
2. Mit „laufendes Event ausblenden“ nur das Event mit aktuellem Datum und Startzeit in der Zukunft angezeigt werden
3. Ohne „laufendes Event ausblenden“ das Event mit aktuellem Datum und Startzeit in der Zukunft sowie das Event ohne Uhrzeit angezeigt werden.

Das Event mit Startzeit in der Vergangenheit, ohne Endzeit sollte nie angezeigt werden weil es für mich klar als „abgelaufen“ zählt. Ist eine Startzeit angegeben aber keine Endzeit so ist für mich die Endzeit dieselbe wie die Startzeit.

Ist aber nur mein Verständnis von Events, kann also durchaus anders sein ☺️

**Comment by leofeyer** [comment]
> Ist aber nur mein Verständnis von Events, kann also durchaus anders sein ☺️

Wir sollten mal festlegen, welches Verhalten genau wir haben wollen. Dann können wir darauf basiert die Implementierung anpassen.

**Comment by iainmacnab** [comment]
> "Events der aktuellen Tag anzeigen"
Super - ich sehe die Thema ist noch aktuell?
Von mir aus - Event der laufende Tag egal welche Uhrzeit anzeigen, aber mit Uhrzeit ist auch gut.

**Comment by Toflar** [comment]
As discussed in our Contao Slack Call on July 28, 2022, we want to adjust the logic to what was outlined by @ausi in https://github.com/contao/contao/issues/4476#issuecomment-1092619293

**Comment by berecont** [comment]
any news?

**Comment by fritzmg** [comment]
No news. Feel free to create or hire a PR that implements the changes as outlined in https://github.com/contao/contao/issues/4476#issuecomment-1092619293

**Comment by CMSworker** [comment]
Bin gerade hierüber gestolpert - ich sehe es eher wie @mlwebworker

Zu @ausi 's Kommentar:
> 1. Die Checkbox „verkürzte Darstellung“ keinen Unterschied machen
> 2. Mit „laufendes Event ausblenden“ nur das Event mit aktuellem Datum und Startzeit in der Zukunft angezeigt werden
> 3. Ohne „laufendes Event ausblenden“ das Event mit aktuellem Datum und Startzeit in der Zukunft sowie das Event ohne Uhrzeit angezeigt werden.
>
> Das Event mit Startzeit in der Vergangenheit, ohne Endzeit sollte nie angezeigt werden weil es für mich klar als „abgelaufen“ zählt. Ist eine Startzeit angegeben aber keine Endzeit so ist für mich die Endzeit dieselbe wie die Startzeit.

Punkt 3 und dem letzten Satz stimme ich nicht zu.

Ein Event mit heutigem Datum, bei dem nur eine Startzeit angegeben ist, die allerdings schon vorbei ist, ohne eingetragene Endzeit, sollte IMHO auch bei Punkt 3 angezeigt werden (wenn "laufendes Event ausblenden" NICHT angeklickt ist, also wenn laufende Events angezeigt werden sollen).

Beispiel: Heute um 16 Uhr war ein Termin. Es war keine Endzeit angegeben, da unklar ist, wie lange der Termin dauert. Wenn man die Seite um 16:01 Uhr aufruft, würde das Event nicht mehr angezeigt, obwohl der Termin noch läuft (hat gerade erst begonnen). Nach @ausi Auffassung ist der Termin vorbei, weil Endzeit = Anfangszeit wenn keine Endzeit eingetragen wurde. Diesem Ansatz würde ich nur beim Datum zustimmen (so ist es ja momentan auch in Contao), aber nicht bei der Uhrzeit.

So ein Beispiel kommt in von mir betreuten Projekten häufiger vor: Es wird bei vielen Terminen nur ein Datum und die Startzeit eingetragen, weil viele Veranstaltungen ein offenes Ende haben (aber nur am jeweiligen Tag stattfinden, daher wird auch kein Enddatum eingetragen).

Ich würde daher wie @mlwebworker davon ausgehen, dass der Termin mit Startzeit und ohne Endzeit in der Liste der zukünftigen Events angezeigt wird, auch wenn die Startzeit heute schon vorbei ist - solange "laufende Events ausblenden" nicht angeklickt ist. Wenn "laufende Events ausblenden" angeklickt ist, sollte der Termin natürlich nicht angezeigt werden.

Wenn keine Endzeit eingetragen wurde, ist IMHO davon auszugehen, dass der Termin bis spät am Abend gehen kann (also noch läuft, auch wenn die Startzeit bereits vorbei ist). Folglich sollte der Termin erst aus der Liste der zukünftigen Events verschwinden, wenn das heutige Datum vorbei ist (also Mitternacht). Außer, es wurde "laufende Events ausblenden" angeklickt.

Wenn weder Startuhrzeit noch Enduhrzeit eingetragen wurde, wird in Contao auch davon ausgegangen, dass der Termin von 00:00:00 bis 23:59:50 Uhr dauert. Durch die Eingabe einer Startuhrzeit sollte sich nach meinem Verständnis eben nur diese ändern, die Enduhrzeit bleibt bei 23:59:59 Uhr.

**Comment by ausi** [comment]
As discussed today, we want to adjust the logic to what was outlined by @CMSworker in https://github.com/contao/contao/issues/4476#issuecomment-1360173736
