### ISSUE TITLE
TinyMCE - adding a template not possible

### ISSUE THREAD

**Issue by elektrischerwalfisch** [contao/contao#4488]
### Affected version(s)

4.13.*

### Description

After Updating Contao 4.9. to 4.13. (and the new Version of TinyMCE) there is a problem if you want to add a template in the TinyMCE.
Full Description of the Problem here: https://community.contao.org/de/showthread.php?82865-TinyMCE-Vorlage-aus-Verzeichnis-einf%C3%BCgen-funktioniert-nicht-mehr

I guess the path to the template-folder (files/tiny_templates) is not working correctly and maybe it gots something to do with Leos Quote 

> Since the support for files/tiny_templates has been dropped meanwhile, I am closing this issue. 

 in this post: https://github.com/contao/core/issues/7722

**Comment by de-es** [comment]
Feature is superseded by customizing the template directly.

See https://github.com/contao/contao/blob/4.13/UPGRADE.md#tinymcecss-and-tiny_templates
