### ISSUE TITLE
Add GET parameter to generateFrontendUrl

### ISSUE THREAD

**Issue by hoss-ps** [contao/contao#449]
**Description**  
Currently **'generateFrontendUrl'** accepts  $strParams , and encodes it same as URL. it means for question mark and ampersand its return encoded URL format (%3F,%26). conceptualy its wrong if we assume it as a GET parameter .in this case usualy we do hardcode URL if we need some format 
like:  example.com?foo=bar&arg=val
it may have some useful result, for example **jumpToOrReload** method used it aswell, so in case needs to jumping on page with some GET params, simply can use it except combine it with **redirect** method.

**Comment by Toflar** [comment]
`$strParams` is meant to be used for the path only, not for query parameters.

**Comment by hoss-ps** [comment]
> `$strParams` is meant to be used for the path only, not for query parameters.

thats why i asked if possible to add  for query string too :)
since it use to generate frontend URL , will be fine if have query string aswell.

**Comment by Toflar** [comment]
I don't think we're going to add new functionality to deprecated methods :) Just add them yourself using e.g. `. '?' . http_build_query($params, '', '&')`

**Comment by hoss-ps** [comment]
> I don't think we're going to add new functionality to deprecated methods :) Just add them yourself using e.g. `. '?' . http_build_query($params, '', '&')`

i do the same, it was only suggestion. as mention erlier , we can use query string in jumpToOrReload  etc method aswell.
anyway thanks for reply.
