### ISSUE TITLE
Internal CSS editor visibility button broken

### ISSUE THREAD

**Issue by tintifaxxx** [contao/contao#4490]
### Affected version(s)

4.13

### Description

The visibility button - toggler, green eye, doesnt work porperly anymore.
You have to save "inside", otherwise no effect
Testet in demo version, too

**Comment by ausi** [comment]
What does “no effect” mean in this case?
In my test the visiblity icon itself seems to work.
Do you mean the css code for the frontend doesn’t change immediately?

**Comment by tintifaxxx** [comment]
ok, my fault, frontend changes
font-color doesnt change to grey in backend
maybe in my installation there was no change in frontend for another reason

**Comment by tintifaxxx** [comment]
so its more an usability issue than a bug
its hard to see, when only the eye changes to grey

**Comment by ausi** [comment]
I can reproduce that. Clicking on the visibility icon does only change the icon, after a reload the CSS text color changes to gray.

In Contao 4.9 this works as expected and the text color changes immediately.
