### ISSUE TITLE
Incorrect datepicker default value

### ISSUE THREAD

**Issue by rhymeadam** [contao/contao#4492]
### Affected version(s)

3+

### Description

I’m seeing an issue where the system date format is month, date, then the year (m/d/Y or m-d-Y for example) and when something like tl_calendar_events.startDate has a value of 04/08/2022 i.e. April 8th 2022, the datepicker's default value loads August 4th 2022 instead. I've traced this back to the datepicker since Contao 3. Andreas suggested implementing a vanilla picker in Contao 5, which makes sense to me. Thanks!

**Comment by fritzmg** [comment]
Do you mean in the back end? This happens if you changed the date format in the system settings. If your intention was to change the date format for the _front end_ only, then you need to do that in the settings of your website root and leave the date format in the system settings on its international format.

**Comment by rhymeadam** [comment]
Yes, I mean in the back end. We want the date format in the back end to by m/d/Y but it breaks the datepicker.

**Comment by fritzmg** [comment]
I don't think there is anything that can be done there. You need to define a date format that is readable by the datepicker. The American `m/d/Y` format is too ambiguous.

**Comment by rhymeadam** [comment]
How is it too ambiguous if we're specifying the format? Providing the date format works in JS, MySQL, etc. so I don't see why it's a problem for Contao unless it's a problem for the datepicker plugin, in which case I think it should be replaced. Also, it works in Contao 2.11 so I don't think it's out of the realm of possibility. And if this is a limitation of Contao's system date format and that's the answer here, then it should probably be mentioned somewhere. As it stands now, it looks to our clients as if Contao has a bug with American date formats, which can come off as unnerving to most.

**Comment by rhymeadam** [comment]
I was able to put a workaround in place by using MooTools' Class.refactor on Picker.Date.getInputDate. I basically just checked to see if in this.options.format the month was before the date and if so, I cloned the input, adjusted the date so it'd parse correctly in Date.parse, and passed the cloned input to the parent method using this.previous.apply. It seems to me that this could be done in Contao's mootao.js since it's already doing similar refactoring of other classes.

**Comment by aschempp** [comment]
Looks like our datepicker uses `Date.parse` which is not aware of the format used in Contao. It has a formatting parameter for output, but it incorrectly does not use that format for input.
https://github.com/contao-components/datepicker/blob/2.x/js/datepicker.js#L639

I think it should be possible to correctly parse custom date formats in our datepicker, so this would automatically work for all existing Contao versions. @rhymeadam wanna give it a try?
