### ISSUE TITLE
inconsistent hook processing

### ISSUE THREAD

**Issue by argus231** [contao/contao#4494]
### Affected version(s)

4.9.18

### Description

Example:
case 1
request -> /**assets**/images/4/any_file_that_cannot_exist.jpg
404 page is loading.
The hook processing of "@Hook("getFrontendModule")" is processed only after /controller::replaceDynamicScriptTags() is called.

case 2
request -> /any_site_that_cannot_exist.html
404 page is loading.
Here the hook before /controller::replaceDynamicScriptTags() is processed.

It is correct as shown in case 2, since frontend elements can also be placed on the 404 page.

Then it doesn't work like that:

switch ($element->type) {
    // postmanager content element stylesheets
    case 'text_postmanager':
       ------> $GLOBALS['TL_CSS']['text'] = 'bundles/iimpostmanager/css/text.min.css'; <------
        break;
etc.

**Comment by fritzmg** [comment]
I cannot confirm the problem.

@argus231 can you provide a stack trace for the first case?
