### ISSUE TITLE
Incompatibility between DCA constants and the universal picker

### ISSUE THREAD

**Issue by doishub** [contao/contao#4496]
### Affected version(s)

4.9.28

### Description

While researching this [ticket](https://github.com/oveleon/contao-cookiebar/issues/109), I noticed an inconsistency which occurs when an external extension uses the picker widget but not the new DCA constants.

The following line of code only checks for the constant, so DCAs that are still defined as 'Table' (string) and want to be called by a picker widget are no longer compatible with the current Contao version `4.9.28`:
https://github.com/contao/contao/blob/35806320b12d2d048ffc0d057915e027eb5d4a76/core-bundle/src/Picker/AbstractTablePickerProvider.php#L139

Or in `TablePickerProvider`:
https://github.com/contao/contao/blob/35806320b12d2d048ffc0d057915e027eb5d4a76/core-bundle/src/Picker/TablePickerProvider.php#L24-L27

If I would now adjust the extension accordingly, all running Contao instances (`<4.9.28`) that exclusively install the latest version of the extension would no longer work.

Is this behavior desired? I would have expected some kind of BC layer here now.

**Comment by bytehead** [comment]
Will be fixed by #4481 🙃

**Comment by bytehead** [comment]
Use `Contao\DC_Table::class` instead of `Table` in your DCA definition (`$GLOBALS['TL_DCA'][$table]['config']['dataContainer']`).

**Comment by bytehead** [comment]
Closing in favor of #4481, thank you for reporting though 🙏

**Comment by doishub** [comment]
> Use Contao\DC_Table::class instead of Table in your DCA definition ($GLOBALS['TL_DCA'][$table]['config']['dataContainer']).

Hm, then I have the described case here or am I thinking wrong?
> If I would now adjust the extension accordingly, all running Contao instances (<4.9.28) that exclusively install the latest version of the extension would no longer work.

**Comment by fritzmg** [comment]
That's not really an issue. The new version of your extension can just require `"contao/core-bundle": "^4.9.28"`.

**Comment by doishub** [comment]
I thought I could do without this dependency, but then I will implement it that way or wait for the fix. Thank you 🙃

**Comment by bytehead** [comment]
You could also add a conflict with `"contao/core-bundle": "4.9.28"`.

**Comment by fritzmg** [comment]
> I thought I could do without this dependency, but then I will implement it that way or wait for the fix. Thank you 🙃

There is no downside to defining your dependency this way.

**Comment by doishub** [comment]
Except that Contao instances which have to run on an older 4.9 (for whatever reason) can't use the extension anymore. I think I will wait for the fix and use a conflict. In the long run the constants will be used in any case.

**Comment by fritzmg** [comment]
> Except that Contao instances which have to run on an older 4.9 (for whatever reason) can't use the extension anymore.

Why not? They will automatically get a version of your extension that is compatible.

> I think I will wait for the fix and use a conflict.

But for the conflict to take effect you have to create a new version anyway.

**Comment by aschempp** [comment]
https://github.com/contao/contao/pull/4711 fixes the inconsistency
