### ISSUE TITLE
Remove the error suppression operator in the `Files*` classes

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#45]
@contao/developers Do you agree that we should try to remove the error suppression operator in the `Files*` classes? Don't know whether it is possible, but at least we should give it a shot.

**Comment by Toflar** [comment]
I agree with removing whatever suppresses any error message :)

**Comment by discordier** [comment]
So do I!

**Comment by leofeyer** [comment]
Implemented in contao/core-bundle@f9d48b65252b13dace83818f2329e723b5c0428b.
