### ISSUE TITLE
Unlock Installtool in Contao 4.6

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#45]
**Affected version(s)**
Contao 4.6.X

**Description** 
Looks like the command `vendor/bin/contao-console contao:install:unlock`
 is not available anymore in the command line. When i try it, i get this error:
```
There are no commands defined in the "contao:install" namespace.

  Did you mean one of these?
      contao
      contao:user
```
**How to reproduce**  

- Install a fresh contao installation from the command line
- type the install tool password wrong for 5 times
- try to unlock via command line

**Comment by leofeyer** [comment]
Fixed in ac6fe2b49d606ae79808cb5dcd5a2df0c348013b.
