### ISSUE TITLE
Install tool Database Password - Special Characters

### ISSUE THREAD

**Issue by rburch** [contao/contao#4525]
### Affected version(s)

4.13.2

### Description

Doing a fresh install of contao with contao manager. When I entered the database credentials in the install tool I got a 500 error. We discovered that our database password was creating the issue. We changed it to a different one and reinstalled from scratch and it was fine. We then changed the password to the suspect one as a test and again got the 500 error.

Here's the password we were using for the database: `%~hp#%8mS6QI~DH]kd`

We have a feeling that one special characters in the password was breaking the .yml file. It's likely ~ or ]

**Comment by aschempp** [comment]
if you could try that again, what does the YAML file look like after you entered it? Is the value inside single quotes?

**Comment by ausi** [comment]
> We have a feeling that one special characters in the password was breaking the .yml file. It's likely ~ or ]

I’d suspect the `%`

It would be great, if you could test several passwords, one with `%` one with `~` and one with `]`

**Comment by rburch** [comment]
When I do it it freezes up the site and I end up having to do a whole new install. Is there a way to reset the install tool so I can test it easier?

**Comment by rburch** [comment]
I set up a new test site for it and got the same issue with that password. I took out the % from the password and did a reinstall from scratch and it worked. Looks like it's the %. ~ and ] worked fine.

**Comment by ausi** [comment]
Might be related to #1632
