### ISSUE TITLE
General search for content in the backend

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#4526]
### Description

It would be helpful if you could freely search for any phrases/texts or other data 
in the backend and then immediately get to the corresponding backend entries via it.

Possibly this then within the Contao Dashboard (see also: #4503)

**Comment by ben-eSM** [comment]
I guess this would get along well with my suggestion in #4249.

**Comment by ameotoko** [comment]
Yes, something like https://github.com/terminal42/contao-tablelookupwizard, but in a panel. That would be awesome!

**Comment by fkaminski** [comment]
Close this then (see previous posts)
