### ISSUE TITLE
TinyMCE 6

### ISSUE THREAD

**Issue by de-es** [contao/contao#4532]
### Description

Are there any plans to deliver TinyMCE 6 with Contao 5? Should I provide a pull request?

**Comment by fkaminski** [comment]
I do not know if this is generally planned. 
FYI - A list of upcoming changes:
https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/

**Comment by leofeyer** [comment]
Yes, we are planning to ship TinyMCE 6. However, we should discuss this in the correct repo: https://github.com/contao-components/tinymce4

**Comment by de-es** [comment]
Sounds good. The core needs some - small - adjustments for v6 to work flawlessly. That's why I opened the issue here in the first place.

https://github.com/contao-components/tinymce4/issues/4
