### ISSUE TITLE
TinyMCE 6 for Contao 4?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#4538]
### Description

We should discuss whether we want to allow installing TinyMCE 6 with Contao 4.

TinyMCE 6 requires a few minor adjustments of the configuration file to work (see #4537), so once we allow version 6 to be installed, people will either have to adjust their TinyMCE configuration files or to add `"contao-components/tinymce4": "^5.0"` in their composer.json file to keep using version 5. If they only updated the dependencies and did neither, TinyMCE would stop working.

**Comment by Toflar** [comment]
Can't we allow both by accessing the installed version in the config template?

**Comment by leofeyer** [comment]
Unfortunately, this would not work for customized templates.

**Comment by Toflar** [comment]
Well they would have to be adjusted as well of course. But probably we do that in Contao 5 then?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we can only ship new asset major versions in Contao minor or major versions, so there will be no TinyMCE 6 for Contao 4.
