### ISSUE TITLE
Modul Auflistung Error ohne Ausfüllen des Felds Detailseitenbedingung

### ISSUE THREAD

**Issue by arminfrey** [contao/contao#4547]
### Affected version(s)

4.13.2

### Description

Erstellen eines Moduls Auflistung ohne die Eingabe einer Detailseitenbedingung, dann bekomme ich folgenden Fehler:

`[2022-04-26T09:35:31.768407+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 1 passed to Contao\CoreBundle\InsertTag\InsertTagParser::replaceInline() must be of the type string, null given, called in .../vendor/contao/listing-bundle/src/Resources/contao/modules/ModuleListing.php on line 79" at .../vendor/contao/core-bundle/src/InsertTag/InsertTagParser.php line 40 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Contao\\CoreBundle\\InsertTag\\InsertTagParser::replaceInline() must be of the type string, null given, called in .../vendor/contao/listing-bundle/src/Resources/contao/modules/ModuleListing.php on line 79 at .../vendor/contao/core-bundle/src/InsertTag/InsertTagParser.php:40)"}`

Wenn ich eine Detailseitenbedingung eingebe, dann funktioniert alles (die "Felder der Detailseite" dürfen leer bleiben)

**Comment by Toflar** [comment]
Closing in favor of https://github.com/contao/contao/pull/4549.

**Comment by fritzmg** [comment]
Duplicate of #4483
