### ISSUE TITLE
Pfad in Seitenstruktur wird mehrfach angezeigt

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#455]
In der 4.7.4 wird der Pfad mehrfach angezeigt, wenn man in der Seitenstruktur eine Seite hinzufügt und danach "Speichern und neu" wählt. Nach der Rückkehr in die Seitenstruktur sind man dann das:

![Seitenstruktur](https://www.schachbund.de/files/contao-forum/seitenstruktur_multidomain.jpg)

Das Ganze läßt sich in der COD (4.7.4) nachvollziehen:

1. Neuen Startpunkt anlegen
2. In einen Seitenbaum wechseln (nicht auf Hauptebene bleiben!)
3. Neue Seite einfügen
4. (Seite) Speichern und neu
5. (Seite) Speichern und neu
6. ...
7. Speichern und beenden

Je nach Anzahl der Speichern-Aktionen sieht man das Verhalten analog der Grafik mit der entsprechenden Anzahl der Pfad-Kopien. Für die Grafik habe ich zwei Seiten angelegt, also einmal "Speichern und neu" geklickt.

**Comment by leofeyer** [comment]
Tritt das Problem auch in Contao 4.4 auf?

**Comment by xchs** [comment]
In Contao 4.4.38 kann ich es nicht reproduzieren.

**Comment by leofeyer** [comment]
Das Problem wird durch die Änderungen bezüglich Cache-Tagging (siehe https://github.com/contao/contao/pull/137/commits/d0fd9f4dd638e3045a89d66fa6c274b3bc2e797e#diff-e641f7127d9e8499138942f40dceafc3R3313) verursacht.

@Toflar Ich erinnere mich an die Diskussion auf Mumble bezüglich der Implementierung – scheint als hätte `$dc = new $dataContainer($this->strTable);` doch ein paar Side-Effects. Im Grunde dürfte der `onload_callback` an dieser Stelle nicht noch einmal ausgeführt werden, was wir ggf. mit einer Property `static::$isLoaded` oder ähnlichem verhindern könnten. WDYT?

**Comment by leofeyer** [comment]
Dasselbe Problem tritt auch in der Klasse `BackendPassword` auf:

https://github.com/contao/contao/blob/5027ebcdf496f5560d320b0147aae952937b0aac/core-bundle/src/Resources/contao/controllers/BackendPassword.php#L96-L97

Dort merkt man es nur nicht, weil es kein Breadcrumb-Menü gibt. Aber die Änderungen am globalen Array durch den `onload_callback` werden auch hier doppelt ausgeführt.

**Comment by ausi** [comment]
Wäre ein dritter parameter für den `DC_Table` wie z. B. `$blnSkipLoadCallbacks = false` eine Option?

**Comment by leofeyer** [comment]
Wollte ich eigentlich vermeiden, daher die Idee mit dem `static::$isLoaded`. Aber würde natürlich auch funktionieren.

**Comment by leofeyer** [comment]
Wobei die Änderungen am globalen DCA dann immer noch ausgeführt würden, wenn jemand den dritten Parameter vergisst. Das würde mit `static::$isLoaded` nicht passieren.

**Comment by Toflar** [comment]
Aber es ist doch richtig, dass der Callback zweimal ausgeführt wird? Ich mach ja ggf. im onload_callback sowas wie `$dc->table = 'foo'` dann müsste es ja da auch ausgeführt werden.

**Comment by leofeyer** [comment]
Das ist eben die Frage, die wir diskutieren sollten. Ggf. müssen wir auch einen neuen `view_callback` oder so einführen, damit wir Dinge wie das Breadcrumb-Menü, die nur einmal ausgeführt werden sollen, an anderer Stelle hinzufügen können.

**Comment by aschempp** [comment]
Warum machen wir in https://github.com/contao/contao/commit/d0fd9f4dd638e3045a89d66fa6c274b3bc2e797e#diff-e641f7127d9e8499138942f40dceafc3R3313 ein `new` und nicht einfach ein `clone`? Bzw. an Stellen wie dem Edit-Multiple nutzen wir ja auch den bestehenden DC_Table für jedes `save_callback` und ändern die bestehende ID?

**Comment by leofeyer** [comment]
Gute Frage. Das werde ich mir ansehen.

**Comment by leofeyer** [comment]
Wie am 9. Mai auf Mumble besprochen, wollen wir versuchen, die ID und den Active-Record des vorhandenen DCs zu überschreiben und anschließend zu resetten anstatt einen neuen DC zu erstellen.

**Comment by leofeyer** [comment]
Pull-Request: https://github.com/contao/contao/pull/485
