### ISSUE TITLE
Improve default escaping strategy for Contao Twig templates

### ISSUE THREAD

**Issue by m-vo** [contao/contao#4551]
### Affected version(s)

4.13

### Description

Assume there is a Contao template `fe_page.html.twig` that includes `_my_partial.html.twig` like this (i.e. without a `@Contao` namespace prefix):

```twig
{% include "/_my_partial.html.twig" %}
```

Now our default escaper rule, `^@Contao(_[a-zA-Z0-9_-]*)?/`, that rewrites the escaper filter to our non-double-encoding one, won't match anymore for the included module. The same is the case if you include/embed/import things of a Symfony bundle template (e.g. our current image studio macros). 

This is somewhat expected and you could work around this behavior by adding your own escaper rules, but I think we should improve some things.

1) We should probably explicitly add our own views, but we could also…
2) …try to inherit the property of being a Contao template down the tree.

With inheriting I mean, that only the name of the template, that contains the include/embed/import statements matters, not the included/embedded/imported module (and their children).

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to try no. 2 (inheriting the property of being a Contao template down the tree) and see if we can make it work.

**Comment by m-vo** [comment]
Closing in favor of #4623.
