### ISSUE TITLE
"collate" is deprecated in Doctrine

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#4560]
### Affected version(s)

4.13

### Description

Looks like `collate` here should become `collation` now? 🤔

https://github.com/contao/contao/blob/751a4a821c7c69dc93a07d2f19df55bb4250f04e/manager-bundle/src/Resources/skeleton/config/config.yml#L45-L58

Reference:

* https://github.com/terminal42/contao-mailusername/issues/20
* https://github.com/doctrine/dbal/issues/5265
* https://github.com/doctrine/DoctrineBundle/issues/1468
* https://github.com/doctrine/DoctrineBundle/pull/1478

**Comment by leofeyer** [comment]
@ameotoko Can you please check if the changes from #4592 fix your issue?

**Comment by ameotoko** [comment]
Yes they do, thank you @leofeyer
