### ISSUE TITLE
It's impossible to make an option with label "0" in the Form Editor

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#4568]
### Affected version(s)

4.13.2

### Description

In the select form field, the option with label "0" is deleted on save:

![Screenshot 2022-04-29 at 11-24-10 Formulare Teamanmeldung DE Challenge Felder Formularfeld ID 648 bearbeiten relaunch2022 hands-on-technology org](https://user-images.githubusercontent.com/4446224/165918748-fce01910-dd1e-4f31-a907-11804169d30b.png)

![Screenshot 2022-04-29 at 11-24-40 Formulare Teamanmeldung DE Challenge Felder Formularfeld ID 648 bearbeiten relaunch2022 hands-on-technology org](https://user-images.githubusercontent.com/4446224/165918744-5a636649-5553-4584-b6e8-cfd41947ac45.png)

**Comment by bezin** [comment]
I can confirm this.
