### ISSUE TITLE
Mails über Relay senden mit TLS

### ISSUE THREAD

**Issue by kroerig** [contao/contao#457]
**Affected version(s)**
4.7.x (und vermutlich auch älter)

**Description**
E-Mails können nicht verschickt werden, wenn das SMTP-Relay nur TLSv1.1 oder höher unterstützt.

siehe auch:
https://community.contao.org/de/showthread.php?74767-Mail-%C3%BCber-Relay-versenden

**How to reproduce**  
Ein SMTP-Relay verwenden, das kein TLSv1 mehr unterstützt.

**Comment by leofeyer** [comment]
SwiftMailer unterstützt TLSv1.1 und TLSv1.2 ab Version 5.4.14; Du hast vermutlich noch eine ältere Version. Am besten aktualisierst Du mal Deine Pakete im Contao Manager bzw. über Composer.

**Comment by kroerig** [comment]
Habe ich, bin laut Composer bei Version 6.2.1

**Comment by leofeyer** [comment]
Dann sollte es auch gehen. Mein Mail-Server unterstützt auch kein TLSv1 mehr und ich kann problemlos mit Contao 4.7 Mails darüber versenden.

**Comment by kroerig** [comment]
Kann ich den SMTP-Dialog von Swiftmailer irgendwie mitschneiden?
Auf dem Mailserver sehe ich nur, dass er nach STARTTLS abbricht.

**Comment by leofeyer** [comment]
Ja, mit dem [Logger Plugin](https://swiftmailer.symfony.com/docs/plugins.html#logger-plugin).

**Comment by kroerig** [comment]
Wo muss ich das denn in Contao einbauen, damit das greift?

**Comment by leofeyer** [comment]
In Contao bzw. Symfony kannst Du das Logging in Deiner `config.yml` konfigurieren:

https://symfony.com/doc/current/reference/configuration/swiftmailer.html#logging
