### ISSUE TITLE
Newsletter-Versand wird unterbrochen bei nicht existierender Domain

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#4572]
### Affected version(s)

4.12.7

### Description

Der Versand eines Newsletters wird bei mir gelegentlich unterbrochen:
Expected response code "250/251/252" but got code "521", with message "521 5.1.2 Domain does not exist: 'xxx.de'".
Es würde doch reichen solche Meldungen in tl_log reinzuschreiben, anstatt den Anwender mit so einer Meldung bei der Arbeit zu unterbrechen. Erst wenn die E-Mail-Adresse mit der nichtexistierenden Domain deaktiviert ist, kan  man den Newsletter-Versand wieder aufnehmen.

**Comment by kroerig** [comment]
4.12 ist keine aktiv gepflegte Version mehr. Tritt das Verhalten auch bei 4.13 auf?
Wie werden die Mails an den MTA übergeben?

Ich hatte dieses Verhalten bisher noch nicht.

**Comment by Samson1964** [comment]
Ich konnte es erstmal nur in einer 4.9.29 testen:
Dort gibt es aber die Option Mailer-Transport noch nicht. Und der Versand funktioniert. Ich teste das nochmal in einer 4.13.

**Comment by Samson1964** [comment]
Ich habe es gerade in der Contao-Demo getestet (4.13.2). Auch dort funktionierte der Versand. In meiner 4.12. habe ich in der parameters.yml SMTP-Daten angegeben. Ich weiß natürlich nicht, ob das in der Contao-Demo auch so ist.

**Comment by kroerig** [comment]
Die (öffentliche) Contao Demo verschickt E-Mails? Das würde mich wundern. Oder meinst Du eine selbst installierte Demo?
Dein "Problem" ist in der Tat die SMTP Konfiguration. Der SMTP prüft bei der Übergabe der Mail ob die Empfängerdomain existiert. Das ist für klassische Mailprogramme recht praktisch, weil der Absender sofort die Rückmeldung bekommt, dass was nicht stimmt und kein Bounce erzeugt werden muss.

Musst Du die Mails über diesen SMTP-Server verschicken oder könntest Du auch den klassischen Versand über den lokalen MTA des Webservers nutzen? Da sollte dieses Verhalten nicht auftreten. Stattdessen bekommst Du die Rückläufer dann ein paar Sekunden später an die Absenderadresse.
