### ISSUE TITLE
Re-think the .root file name for the Twig integration

### ISSUE THREAD

**Issue by Toflar** [contao/contao#4577]
### Description

As noticed at the Contao Camp 22, the `.root` filename seems to be confusing for many people. Maybe we can come up with a better name for it?

**Comment by m-vo** [comment]
Any suggestions?

**Comment by rabauss** [comment]
`.folders` or `.tree` ?

**Comment by contaoacademy** [comment]
- `.tpldir`
- `.basedir`
- `.twigfolder`
- `.tplmount`

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to go with `.twig-root` until we come up with a better idea. 😄

**Comment by m-vo** [comment]
Closing in favor of #4620.
