### ISSUE TITLE
Improve the Model::getRelated() method

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#458]
We could improve the `Model::getRelated()` method by returning `null` if the key is `0`. @backbone87 has suggested this in https://github.com/contao/core/issues/6161#issuecomment-24514290 some time ago:

> `NOT NULL` means mandatory or in case of contao `NOT NULL default '0'` means mandatory, because 0 can never be a valid PK ref in contao. If you have an optional relation you can use `NULL (default NULL)`, which is correct in terms of schema design.

Right now, we already return `null` if `$this->$strKey` is not set:

https://github.com/contao/contao/blob/ed2fec5eaaa84875a9a14b5b90e803a65bccec7c/core-bundle/src/Resources/contao/library/Contao/Model.php#L605-L609

But we should also return `null` if `$this->$strKey < 1`, because as @backbone87 said, `0` or a negative number can never be a valid key reference in Contao.

@contao/developers WDYT?

**Comment by Toflar** [comment]
Fine with me.

**Comment by bytehead** [comment]
Fine with me.

**Comment by ausi** [comment]
Is `$this->$strKey` always an integer? What about UUIDs?

**Comment by leofeyer** [comment]
You are right, `$this->$strKey` can be a UUID. Then what about `(int) $this->$strKey === 0`?

**Comment by Toflar** [comment]
I'd rather add an `is_numeric()` check to prevent `false` from turning into a `0`. Sure, `false` makes no sense in `getRelated()` but still...we explicitly want to check for a `0` so we should make sure it is a number.

**Comment by leofeyer** [comment]
In this case we could just replace `isset($this->$strKey)` with `!empty($this->$strKey)`, couldn't we?

**Comment by ausi** [comment]
~~As the primary key integers are stored as strings in `$this->$strKey`, I think we should use:~~

You are right, using `empty()` should be the right thing to do:

```php
if (empty($this->$strKey)) {
	return null; 
}
```

**Comment by leofeyer** [comment]
Implemented in fbc056e5b3dd2e645bfe7812cb997ece8ff6b578.
