### ISSUE TITLE
Get rid of cookies and use localstorage instead

### ISSUE THREAD

**Issue by Toflar** [contao/contao#459]
From a reverse proxy's point of view, cookies make a request private thus preventing it from caching the responses (or delivering from the cache for that matter). We have removed a lot of cookies already but they are still used way too much for things that really do not need a cookie at all.

Here are the ones I saw that have to be removed:

* `BE_CELL_SIZE` - stores the cell size in the table content element. If we really want to store that then that's a perfect example for local storage because that's information that's completely irrelevant for the server.

* `BE_PAGE_OFFSET` - stores the scroll offset in the back end. Again, something that is pretty irrelevant to the server side. Although the `DC_Table` resets it (which looks strange to me).

A quickfix would be to at least set the cookie path to `/contao` and not `/` because both of them affect the BE only.

**Comment by Toflar** [comment]
Another one that has to be rebuilt using localstorage: `TS_TABLE_<id>` for the table sorter. The app absolutely doesn't need to know about the state, it's pure JS logic.

**Comment by Toflar** [comment]
PR for the hardest of these ones (the `BE_PAGE_OFFSET`): https://github.com/contao/contao/pull/467

**Comment by Toflar** [comment]
PR for `BE_CELL_SIZE`: https://github.com/contao/contao/pull/468

**Comment by leofeyer** [comment]
> Another one that has to be rebuilt using localstorage: `TS_TABLE_<id>` for the table sorter

The cookie is only used to set an initial sorting order – however, I wonder how this has ever worked given that the [`ContentTable`](https://github.com/contao/contao/blob/947b6254e4420a22ba58f6baffb125da561dd459/core-bundle/src/Resources/contao/elements/ContentTable.php#L53
) class sets a `TS_TABLE_<id>` cookie but the [`tablesort.js`](https://github.com/contao-components/tablesort/blob/b4e2ebed2277c80a8f3aedd291e69b1ee877d6b2/js/tablesort.js#L60
) script uses a `TS_<id>` cookie. 🤔 

So, how would you solve this?

1) Keep sending the cookie but remove it in the JS once the value has been added to the local storage?
2) Remove the cookie and inject a `<script>` tag, which adds the item to the local storage, instead?
3) Remove the "initial sorting order" feature, which apparently nobody uses? 😄

**Comment by leofeyer** [comment]
Note that 1) can lead to inconsistencies IMHO if the `tablesort.js` script is not included properly.

**Comment by fritzmg** [comment]
> The cookie is only used to set an initial sorting order – however, I wonder how this has ever worked given that the [`ContentTable`](https://github.com/contao/contao/blob/947b6254e4420a22ba58f6baffb125da561dd459/core-bundle/src/Resources/contao/elements/ContentTable.php#L53) class sets a `TS_TABLE_<id>` cookie but the [`tablesort.js`](https://github.com/contao-components/tablesort/blob/b4e2ebed2277c80a8f3aedd291e69b1ee877d6b2/js/tablesort.js#L60) script uses a `TS_<id>` cookie. 🤔

https://github.com/contao/core/issues/8118 :)

**Comment by Toflar** [comment]
> The cookie is only used to set an initial sorting order – however, I wonder how this has ever worked given that the [`ContentTable`](https://github.com/contao/contao/blob/947b6254e4420a22ba58f6baffb125da561dd459/core-bundle/src/Resources/contao/elements/ContentTable.php#L53) class sets a `TS_TABLE_<id>` cookie but the [`tablesort.js`](https://github.com/contao-components/tablesort/blob/b4e2ebed2277c80a8f3aedd291e69b1ee877d6b2/js/tablesort.js#L60) script uses a `TS_<id>` cookie. 🤔

I've noticed that too yesterday 😄 Imho 2) but the initial sorting order should be an argument where it's initialized:

```
var ts = new TableSort(....., '<= $this->initialSortingOrder ?>')
```

**Comment by leofeyer** [comment]
I like it. 👍

**Comment by leofeyer** [comment]
PR for tablesort.js: #471

**Comment by leofeyer** [comment]
Since all PRs have been merged, I am closing this ticket.
