### ISSUE TITLE
Optimize default value for search filter by pagetree

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#4594]
### Description

It would be helpful if there were new default settings for a value which is used more often, e.g. title as default.
Similar with the articles and content elements

Currently:
- Page = Assets-URL
- Article = Article alias
- Content elements = Alternative text

I would like to see:
- Page = page title
- Article = title
- Content element = text or heading

**Comment by fritzmg** [comment]
Currently the list is simply sorted alphabetically. Though I agree that this could be improved. May be the last used search field (for each DataContainer/back end module) could be stored in the `localStorage`?

**Comment by contaoacademy** [comment]
> May be the last used search field (for each DataContainer/back end module) could be stored in the `localStorage`?

This would be great! How much effort is that?

**Comment by contaoacademy** [comment]
I just saw that the last search is stored. However, as soon as I reset the search, then everything is cleared. I don't know if these two functions can be combined at all.

**Comment by aschempp** [comment]
I think we could just keep the last searched field in the session. Instead of dropping the value from session when filters are cleared, we could set an empty value (string or null) so we know what field was searched for.
