### ISSUE TITLE
Update to TL_VIEW cookie event listener

### ISSUE THREAD

**Issue by aschempp** [contao/contao#46]
see https://github.com/contao/core/issues/7632

**Comment by thomaspahl** [comment]
@aschempp - above issue is none - invalid, I did not test properly

**Comment by aschempp** [comment]
We're not using the Contao `setCookie` method in Symfony, so we should validate that. Don't have Symfony at hand right now.
https://github.com/contao/core-bundle/blob/develop/src/EventListener/ToggleViewListener.php#L30-L50

**Comment by leofeyer** [comment]
What are the steps to solve this issue?

**Comment by aschempp** [comment]
Feel free to assign it to me, I'll take care of it.

**Comment by leofeyer** [comment]
Thanks.

**Comment by aschempp** [comment]
See PR https://github.com/contao/core-bundle/pull/62
