### ISSUE TITLE
Sitemap, Robots and Favicon controller always return 404 with domain and port

### ISSUE THREAD

**Issue by bezin** [contao/contao#4602]
### Affected version(s)

4.13, 5.x

### Description

1. Configure a DNS entry for your root page, e.g. `contao.local`
2. Run the application on some port, e.hg. `8000`
3. Request contao.local:8000/sitemap.xml

The response will always be 404, because `$request->server->get('HTTP_HOST')` always includes the port. The port however is not configured in the DNS page settings, because it is supposed to be port agnostic – hence the matching fails. 

See [RobotsTxtController](https://github.com/contao/contao/blob/2f178ccfbaaa1db7eb1f3a9018d530e3338e7796/core-bundle/src/Controller/RobotsTxtController.php#L46), [SitemapController](https://github.com/contao/contao/blob/2f178ccfbaaa1db7eb1f3a9018d530e3338e7796/core-bundle/src/Controller/SitemapController.php#L45) and [FaviconController](https://github.com/contao/contao/blob/2f178ccfbaaa1db7eb1f3a9018d530e3338e7796/core-bundle/src/Controller/FaviconController.php#L46).

As the other issues with DNS settings and ports other than 80 it probably only affects some dev environments, but since it is supposed to be port agnostic, I think we should fix this.

**Comment by Toflar** [comment]
I think we should use `$request->getHost()` in all those places :) Can you test that and work on a PR if it works? 😇
