### ISSUE TITLE
Versionskonflikt bei Änderung Layout zuweisen

### ISSUE THREAD

**Issue by chiron501** [contao/contao#4606]
### Affected version(s)

4.9.28

### Description

Wenn man unter Seite xyz bearbeiten die Checkbox "Ein Layout zuweisen" aktiviert/deaktiviert und die Einstellungen speichert kommt eine Meldung "Versionskonflikt" obwohl weder ein anderer Benutzer angemeldet ist noch an der entsprechenden Seite arbeitet.
In der Contaoversion 4.9.27 tritt das Verhalten nicht auf.

PHP: 7.4.9

**Comment by fritzmg** [comment]
Duplicate of #4454
