### ISSUE TITLE
Add extra field for copyright notices in file manager

### ISSUE THREAD

**Issue by max-admina** [contao/contao#461]
Editors often forget to add copyright notices to uploaded images. It would help a lot, if there's a field "copyright notice" in data meta-fields in the file manager.

In the frontend, this could be part of the caption:

`<figcaption class="caption">Some text about the image <span class="copyright-info">Photo: Max Mustermann</span></figcaption>`

**Comment by asaage** [comment]
https://github.com/contao/core-bundle/issues/1297
