### ISSUE TITLE
Individuelle Weiterlesen Texte bei den News/Events Teaser- und Listenansicht.

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#4610]
### Description

Hallo lieber Contao-Team,

nachdem die "zurück zur Übersicht" Text unter Contao 4.13 #3862 individuell gestaltbar ist, würde es Sinn ergeben, den "Weiterlesen..." Text für die News und Events, Teaser- und Listenansicht auch als individuell gestaltbar implementieren.

Ist es möglich, dies in Contao als Standard zu implementieren?

Dieses Feature würde den Redakteur mehr Kreativität bieten. Und man könnte dadurch auch in SEO einiges bewirken.

Was meint Ihr dazu?

**Comment by fritzmg** [comment]
Just to clarify: instead of having just one `MSC.goBack` translation, you want to have

* `MSC.eventGoBack`
* `MSC.newsGoBack`
* …

similar to the now existing

* `MSC.eventOverview`
* `MSC.newsOverview`
* …

is that correct?

**Comment by havutcuoglu** [comment]
No, I mean the read more `$GLOBALS['TL_LANG']['MSC']['more']` to make it custom.
I know I can change it in language files but I can not make it custom for every single news or event item.

For example:
News article 1 "read more" text -> Learn more about the new COVID Omicron variant
`<a href="....">Learn more about the new COVID Omicron variant</a>`
News article 2 "read more" text -> RKI clarifies about COVID omicron variant
`<a href="....">RKI clarifies about COVID omicron variant</a>`
News article 3 "read more" text -> Why Omicron is so dangerous? How can you protect yourself?
`<a href="....">Why Omicron is so dangerous? How can you protect yourself?
</a>`

**Comment by leofeyer** [comment]
I like this idea.

**Comment by fritzmg** [comment]
Yes, this has been requested before in the community. My initial idea was to be able to provide the label per archive though, not per article.

**Comment by havutcuoglu** [comment]
If we implement the adjustment via archive level, you can also leave it as it is at the moment, because it doesn't bring any advantage.
For example you can implement from the news archives, blog, current affairs, offers, job offers etc. For one or the other it would make sense to change it to archive centrally. If somebody wish the default Text like Read more, can leave the field empty.

I think implementing it like in my example [above](https://github.com/contao/contao/issues/4610#issuecomment-1118287425) makes technical sense from an editor's perspective and SEO. We had the problem several times in the agency because the customers wanted their own texts on the links.

**Comment by asaage** [comment]
> initial idea was to be able to provide the label per archive...

Having a default per list (not archive) makes more sense i think.
Override per article: I like that too.

**Comment by aschempp** [comment]
I actually implemented this in a client project recently by adding a custom field to the `tl_news` DCA and using it in the template. But that's like the first time in 10 years that was ever requested, not sure it needs to be there by default 🤷

**Comment by havutcuoglu** [comment]
@aschempp ok. But we implemented this feature more than 10 times, because most of our clients using WordPress before. After they're changing to Contao asking about the custom text fields for news and blog items. In fact, they ask where they can customize the read more text. We have this option also by hyperlink and download elements. Why not in News items?

I think, It is a small Feature but has a big effect to usability and SEO.
