### ISSUE TITLE
tl_search.url - specified key was too long

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#4615]
### Affected version(s)

4.9

### Description

In #4427 we changed `tl_search.url` to a length of `2048` to fix #4260. However, without `innodb_large_prefix` (which is currently still a recommendation and not a requirement for Contao) this will lead to the following error:

```
An exception occurred while executing 'ALTER TABLE tl_search CHANGE url url VARCHAR(2048) DEFAULT '' NOT NULL COLLATE `ascii_bin`':  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

**Comment by ausi** [comment]
As discussed on Slack we should create a schema listener that reduces the field length of tl_search.url to 767 if innodb_large_prefix is set to false.

**Comment by Toflar** [comment]
Can we extract the whole database fields into a listener rather than having DCAs? If you disable the core search indexer you don't need it either :)

**Comment by fritzmg** [comment]
Probably more a compiler pass than a listener?

**Comment by Toflar** [comment]
Well the listener adding the schema would be a doctrine schema listener but that can be completely removed from the container in case search was disabled, yes.

**Comment by fritzmg** [comment]
The doctrine schema listener we discussed would simply adjust the field length for `tl_search.url` dynamically (similar to the automatic adjustments of key lengths depending on `innodb_large_prefix`). We don't really have a concept for dynamically added DCAs yet so I am not really sure how I would implement that 🤔

**Comment by Toflar** [comment]
Exactly like we do in our `DoctrineSchemaListener` that appends the DCA definitions to the Doctrine schema.
So basically:

```yml
// services.yml
contao.listener.search_indexer_schema:
    class: Contao\CoreBundle\EventListener\SearchIndexerSchemaListener
    tags:
        - { name: doctrine.event_listener, event: postGenerateSchema }
```

```php
class SearchIndexerSchemaListener
{
    public function postGenerateSchema(GenerateSchemaEventArgs $event): void
    {
        $schema = $event->getSchema();
        $table = $schema->createTable('tl_search'); // plus tl_search_term and tl_search_index
        // add all the columns we need and decide lengths dynamically (inject the connection and check for the platform, I guess?)
    }
}
```

And if the default indexer is deactivated, we can remove `contao.listener.search_indexer_schema` from the container in which case, no tables would be added :)

**Comment by fritzmg** [comment]
Ah, you mean creating the tables and fields "by hand" instead of via the DCA at all, got it. But that would mean nobody could make DCA adjustments anymore. We have extensions that add additional fields to `tl_search`, so I don't think we can do that.

**Comment by Toflar** [comment]
I think they could continue just like before. If you add a field to `tl_calendar` and the calendar-bundle is not installed, it works too.

**Comment by fritzmg** [comment]
No, the DCA extractor will ignore that.

**Comment by fritzmg** [comment]
But we could turn it around at least: remove the tables via the schema listener, if the default indexer is disabled.

**Comment by Toflar** [comment]
I honestly wouldn't care about that case but if you do then that's fine for me too^^
