### ISSUE TITLE
Symlinks neu erstellen

### ISSUE THREAD

**Issue by ghost** [contao/contao#462]
<a href="https://github.com/jommbee"><img src="https://avatars3.githubusercontent.com/u/4679889?v=4" align="left" width="42" height="42"></img></a> [Comment](https://github.com/contao/contao/issues/299#issuecomment-487871058) by @jommbee
April 30th, 2019, 10:59 GMT

Heute in der 4.4.39 nach Serverumzug gleicher Fehler.
Nach manuellem Fix in der Zeile:
https://github.com/contao/contao/blob/4.4/core-bundle/src/Resources/contao/library/Contao/Automator.php#L400
geht alles wunderbar.

**Comment by leofeyer** [comment]
Behoben in 46180e9238288a3e6ed6cda5b0d9c4ba1ae74d79.

**Comment by zonky2** [comment]
@leofeyer wann kommt 4.4.40?

**Comment by xchs** [comment]
Da sich die Milestones alle geändert haben (und nur noch Major und Minor Version beinhalten), ist es nun leider nicht mehr möglich, die für ein bestimmtes Release relevanten Tickets zu filtern, z. B. https://github.com/contao/contao/issues?q=milestone%3A4.4.40+is%3Aclosed

Es gibt zwar auch ein [Changelog](https://github.com/contao/contao/blob/4.4/CHANGELOG.md) für Contao 4.4.40; allerdings werden dort einerseits

- nicht immer alle Tickets eines bestimmten Releases angeführt (sondern meist nur eine Auswahl der relevantesten) und andererseits
- sind die Tickets nicht entsprechend verlinkt, wodurch man sich diese erst selbst raussuchen müsste.

:confused:

**Comment by leofeyer** [comment]
Das ist richtig. Die Tickets sind aber weiterhin in der Git-Historie verlinkt: https://github.com/contao/contao/compare/4.4.39...4.4.40
