### ISSUE TITLE
mod_article wird nicht ausgegeben, wenn es das einzige sichtbare eingebundene Modul ist.

### ISSUE THREAD

**Issue by rustykowski** [contao/contao#465]
**Affected version(s)** 4.4.39, 4.7.5

**Description**  Sind im Seitenlayout mehrere Module angelegt aber deaktiviert, und Artikel ist das einzige aktive Modul, so wird dieses nicht ausgegeben.
In welcher Spalte der Artikel eingebunden wird, ist dabei unerheblich
Das Template fe_page ist unverändert.
Löscht man alle deaktivierten Module, wird der Artikel wieder ausgegeben.

**Comment by leofeyer** [comment]
See #492.
