### ISSUE TITLE
Stop using dynamic class properties

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#4654]
### Description

We have to talk about how to get rid of this:

https://github.com/contao/contao/blob/178a5680831903cd5d2d58bf7c143f44eaad404e/core-bundle/src/Resources/contao/classes/DataContainer.php#L279-L281

Maybe it‘s enough to replace `$this->$strKey = ` with `$this->arrProperties[$strKey] =`.

**Comment by m-vo** [comment]
btw: The [proposed way](https://wiki.php.net/rfc/deprecate_dynamic_properties) by Nikita is to use a weak map or the `#[AllowDynamicProperties]` attribute:

```php
class Test {
    private WeakMap $extraInfo;
 
    public function addExtraInfo(object $obj) {
        // Instead of:
        $obj->extraInfo = ...;
        // Use:
        $this->extraInfo[$obj] = ...;
    }
}
```

**Comment by aschempp** [comment]
Since we didn't support object keys anyway (and __set keys are strings only), I wouldn't go with a WeakMap.

**Comment by ausi** [comment]
Do we use this in the core? Otherwise I’d favor removing it in Contao 5.0 and triggering a deprecation in 4.13.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to trigger a deprecation in Contao 5 and see where exactly this is still used.
