### ISSUE TITLE
The table name must not be empty

### ISSUE THREAD

**Issue by tobiasni** [contao/contao#4659]
### Affected version(s)

4.13

### Description

In [Controller.php Line 1530](https://github.com/contao/core-bundle/blob/f5f38de45bebde9a1599936ba01ece1bb4dfca20/src/Resources/contao/library/Contao/Controller.php#L1530) "isset" should be changed to "!empty".
In [Line 1501](https://github.com/contao/core-bundle/blob/f5f38de45bebde9a1599936ba01ece1bb4dfca20/src/Resources/contao/library/Contao/Controller.php#L1501) it earlier was changed from "!isset" to "empty".

I had an error "The table name must not be empty" when adding a new article or content element. May be due to an extension, but changing the code as described above fixed it for me.

**Comment by aschempp** [comment]
👍🏻 Sounds reasonable. It was changed in https://github.com/contao/core-bundle/commit/192b183fd2950508f8f217ad1ed595d812342962 to support the dynamic ptable from module config.

**Comment by fritzmg** [comment]
@tobiasni Are you able to reproduce this in a vanilla Contao 4.13 installation? If yes, please post the reproduction steps. Otherwise it looks like an extension in your instance is setting the `ptable` to empty in a `loadDataContainer` hook.

**Comment by aschempp** [comment]
@leofeyer the check is obviously only meant to handle a misconfigured extension??
