### ISSUE TITLE
Add class 'ce_headline' to main headline of content elements

### ISSUE THREAD

**Issue by dazzle89** [contao/contao#4660]
### Description

For me personally it would be nice to have a CSS class, like .ce_headline, for the MAIN headlines of content elements. So the HTML would be something like

```
<div class="ce_text>
   <h2 class="ce_headline>Headline</h2> 
   <p>Lorem ipsum...</p>
</div>
```

Here is an example when it could be useful:

With the extension "om-backend" I often create classes for backend users. So let's say I create a class for red colored headlines and I name it .headline-red

In the content element "headline" i don't see any problems with it. But when I am using the element "text", i want this CSS class to refer only to the main headline of the text element, not to headlines inside the tinymce. So until now I have to write many CSS lines, for example

```
.ce_text.headline-red > h1,
.ce_text.headline-red > h2,
.ce_text.headline-red > h3,
.ce_text.headline-red > h4,
.ce_text.headline-red > h5,
.ce_text.headline-red > h6,
.ce_headline.headline-red {
	color: red;
}
```

When there is a class for h1-h6, I only need ".ce_text.headline-red .ce_headline" instead of different selectors. I hope you understand what I mean.

**Comment by ameotoko** [comment]
You could also adjust `block_searchable.html5` in your application:

```diff
<div class="<?= $this->class ?> block"<?= $this->cssID ?><?php if ($this->style): ?> style="<?= $this->style ?>"<?php endif; ?>>

  <?php $this->block('headline'); ?>
    <?php if ($this->headline): ?>
-     <<?= $this->hl ?>><?= $this->headline ?></<?= $this->hl ?>>
+     <<?= $this->hl ?> class="ce_headline"><?= $this->headline ?></<?= $this->hl ?>>
    <?php endif; ?>
  <?php $this->endblock(); ?>

  <?php $this->block('content'); ?>
  <?php $this->endblock(); ?>

</div>
```
