### ISSUE TITLE
Allow custom wizard to be visible for disabled fields

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#4676]
### Affected version(s)

4.13

### Description

This refers to the implemented solution in #4173. 

There should be a way for custom wizards to decide for themself if they should be visible or not. Even if the field is `disabled` or `readonly`.

**Comment by aschempp** [comment]
https://github.com/contao/contao/issues/4173#issuecomment-1127431580 feels like the correct solution would be to allow a customized helpwizard based on the field value

**Comment by fritzmg** [comment]
~~@aschempp again, why are you suggesting to use the help wizard for a custom picker wizard?~~ // edit: did not see the updated comments yet 🙃
