### ISSUE TITLE
File synchronisation deletes big files in 4.13.4

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#4678]
### Affected version(s)

4.13.4

### Description

I have a few video files on my server (2,5 GB and 289MB). After uploading them via ftp, file synchronisation finds all of them and i can choose them in content elements.

When using them in a content element "video", the big file (2,5GB) gets deleted at the next synchronisation. But the file remains on the server and i can still see it in contao file manager. The content element itself is loosing the video.

**Files before sync**
<img width="584" alt="dateiverwaltung" src="https://user-images.githubusercontent.com/6390770/168597027-52b62a5d-777a-4322-a2fa-2fcca05f2ada.png">

**Content Element before sync**
<img width="536" alt="vorher" src="https://user-images.githubusercontent.com/6390770/168597125-740ed213-6bda-4316-99fb-2af76b74f403.png">

**Sync after file is in a content element**
![dateiverwaltung-synchronisation](https://user-images.githubusercontent.com/6390770/168597199-55271f25-8eb7-476f-914b-5995066e4dd4.png)

**Content element after sync**
![nachher](https://user-images.githubusercontent.com/6390770/168597250-e1aadcdd-c730-49d0-90b7-bae83915a4de.png)

**Files after sync**
<img width="584" alt="dateiverwaltung" src="https://user-images.githubusercontent.com/6390770/168597027-52b62a5d-777a-4322-a2fa-2fcca05f2ada.png">

This is probably a thing due filesize. According to https://community.contao.org/de/showthread.php?83124-Gro%C3%9Fe-Dateien-(Video)-werden-aus-der-DB-gel%C3%B6scht-wenn-im-Inhaltselement-eingebunden&p=559019&viewfull=1#post559019 this behaviour doesn´t appear in 4.9.x

Contao 4.13.4

**Comment by fritzmg** [comment]
I can confirm the issue. Reproduction:

1. Add a video file greater than 2 GiB to your Contao instance.
2. Select this video file in the video content element and save.
3. Go to the file manager and execute a file sync. It will say _"Removed the file or folder "files/foobar/test.mp4"_.
4. Go to the content element again. The video will not be selected any more.

This presumably happens with every file that is greater than 2 GiB. It does not happen in Contao 4.9 (although hashes for files that are greater than 2 GiB are also not created there, so not sure why it works there?).

/cc @m-vo

**Comment by m-vo** [comment]
> Add a video file greater than 2 GiB to your Contao instance.
> Select this video file in the video content element and save.

I wonder why it's possible to select the file in the first place: `playerSRC` stores a UUID, no? My guess would be that the legacy code (still used in DC_File/Folder) still created a DB record when using the picker or something. We'd need to investigate.

One thought (independent of the solution): We could maybe also create entries for big files, omit the hash but still make the sync work if the path is left untouched. But that sounds like a bit of work :upside_down_face:.

**Comment by fritzmg** [comment]
> I wonder why it's possible to select the file in the first place: playerSRC stores a UUID, no?

UUID generation is not affected by this, as this is just a random UUID returned by MySQL. It is independent from the file and its content.

> One thought (independent of the solution): We could maybe also create entries for big files, omit the hash but still make the sync work if the path is left untouched. But that sounds like a bit of work

That's the behavior in Contao 4.9, as far as I can tell. It's just the sync in 4.13 that now removes `tl_files` entries for files greater than 2 GiB (the 2 GiB limitation is in `Contao\File::getHash()`). The sync in Contao 4.9 did not remove `tl_files` entries for files where no hash could be generated.

**Comment by asaage** [comment]
Is this limit configurable?
I don't like that it exits in the first place. If you can afford uploads of 2G files then creating a hash from that should not be a problem either.

**Comment by fritzmg** [comment]
The limit is hard coded. The hash is (afaik) only used to detect whether a file has been moved outside of Contao during the file sync. So otherwise there are no limitations.

**Comment by ausi** [comment]
I would remove the limitation from `File::getHash()`.

But we should still check why the synchronization fails in that case. If the hash doesn’t match, the file with the same path should still not be removed.

Would the sync still work if we change `File::getHash()` from returning `''` to return `'00000000000000000000000000000000'` instead?

**Comment by ausi** [comment]
The picker calls `Dbafs::addResource()` in https://github.com/contao/contao/blob/0d610b03d2485b5257cdfba4a246f98645238c9b/core-bundle/src/Resources/contao/classes/Ajax.php#L393 which then stores the hash from https://github.com/contao/contao/blob/0d610b03d2485b5257cdfba4a246f98645238c9b/core-bundle/src/Resources/contao/library/Contao/Dbafs.php#L182

So the database has an entry after that with an empty hash. A database sync should only update that hash value IMO, but probably it doesn’t expect an empty string there?

**Comment by m-vo** [comment]
Btw., the new `Dbafs` service ignores files that are too large, i.e. they won't make it in the diff:

https://github.com/contao/contao/blob/8131c15ef1e0fc640b81459e9e61807944d0b2fb/core-bundle/src/Filesystem/Dbafs/Dbafs.php#L732-L734

Maybe, this behavior is not want we want.

**Comment by m-vo** [comment]
Discussed this briefly with @ausi: We should probably just remove the file size limitation altogether. The old implementation uses `md5_file`, the new one streams data + und updates hashes - neither of which takes a lot of memory or an exceedingly long execution time.

If there's no protest, I'd go ahead and implement this solution.

**Comment by Toflar** [comment]
Additional ideas that just came to my mind which might help working around the limitation:

- Compare the file size first and add an early abort if it's just to see if the contents still match. If the number of bytes differ, it's impossible that they'll have the same hash (I mean, technically for md5 it's not but that would be actually even an improvement then for the collision possibilities in md5).
- Make the hash a combination of a CRC32 hash and a SHA1 hash (I don't think we'd require 2 db columns for that, can just separate them with a `.` or whatever). CRC32 is way faster than MD5 or any other algorithm and explicitly designed for such use cases (and in PHP 8+ it actually is 10x faster than md5 whereas in previous versions it was not because the implementation was not really good apparently - https://3v4l.org/2MAUr) and only if those match, add a second hash check which can be a stronger one than md5 reducing the possiblity for collisions even more.

None of which might be required. I'm just thinking out loud.

**Comment by m-vo** [comment]
Closing in favor of #4683 

For the suggestion by @Toflar I created a new issue: #4684
