### ISSUE TITLE
Remove site from search index on 404

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#4685]
### Affected version(s)

4.13

### Description

If a site has been indexed and is unpublished afterwards the site can still be found using the search. Clicking the result leads to a 404 page of course but the site does not get removed from the search index then. This is due to several checks already failing

https://github.com/contao/contao/blob/50502c09eec66d75b1c1ae280ceec90a0ab4ca62/core-bundle/src/EventListener/SearchIndexListener.php#L44-L84

before we reach the actual code that would remove the site from the index

https://github.com/contao/contao/blob/50502c09eec66d75b1c1ae280ceec90a0ab4ca62/core-bundle/src/EventListener/SearchIndexListener.php#L93-L95

@fritzmg Suggested in Slack to wrap `SearchIndexListener.php#L44-L84` into a separate `needsIndex(): bool` method so we can always reach the part where the removal would take place.

**Comment by fritzmg** [comment]
This likely also occurs in 4.9, not just 4.13.
