### ISSUE TITLE
Drop simplepie/simplepie in favor of debril/feedio

### ISSUE THREAD

**Issue by bezin** [contao/contao#4689]
### Description

While working on #4682 I stumbled upon the RssReaderModule. It uses the simplepie/simplepie library to read and parse feeds. As the new Feed page controllers will use debril/feedio (because it supports reading and writing out of the box), we could refactor the RssReaderModule and drop SimplePie.

**Comment by bezin** [comment]
I will take care of this, but https://github.com/alexdebril/feed-io/pull/400 must be accepted and merged first.

**Comment by bezin** [comment]
Just a note that simplepie still is a dependency as we cannot drop the legacy RSS reader module before Contao 6.0.

**Comment by leofeyer** [comment]
What? No. The new RSS reader module should be a replacement for the old one.

**Comment by m-vo** [comment]
At the last dev meeting, we discussed that we do not want to have replacements for modules but different versions that can coexist. 

(https://github.com/contao/contao/pull/4847#issuecomment-1374797111)

**Comment by fritzmg** [comment]
We cannot drop the old module in a feature version.

See also: https://github.com/contao/contao/pull/4847#issuecomment-1374797111

**Comment by leofeyer** [comment]
Ah, I see. We are adding a whole new fragment-based module. I thought we were just replacing the feed reader library as the issue title suggests.
