### ISSUE TITLE
DCA isAssociative "true", includeBlankOption "true", entry with the key "0" always selected (PHP 7.4)

### ISSUE THREAD

**Issue by mwitzmann** [contao/contao#4694]
### Affected version(s)

4.9.29

### Description

Hi all,

```php
<?php

// [...]
'time_from' => [
    'label' => &$GLOBALS['TL_LANG'][$name]['time_from'],
    'exclude' => true,
    'inputType' => 'select',
    'options_callback' => function (\Contao\DataContainer $dc) {
        // Can be empty or e.g. "['test'] => 'test'", but selected is "[0]".
        $return = [];

        for ($i = 0; $i <= 23; $i++) {
            $return[$i] = sprintf('%s Uhr', $i);
        }

        return $return;
    },
    'eval' => [
        'tl_class' => 'w50',
        'isAssociative' => true,
        'includeBlankOption' => true,
    ],
    'sql' => "varchar(50) NOT NULL default ''",
],
// [...]
```

With the given dca field configuration, Contao automatically selects the entry with the key "0" but it should select the first "empty" value entry. Even when the first entry has a non-numeric index (e.g. "test") Contao will always select the entry with the key "0".
This occurs in PHP 7.4, but works in PHP 8.1.5.

**Comment by leofeyer** [comment]
Please do not link to non-public threads. Provide the necessary information here instead.

**Comment by fritzmg** [comment]
I can confirm the issue. Looking at the respective issues and PR's about this in the past I think it was never actually fixed and it just happens to now work with PHP 8 due to its improved type safety.
