### ISSUE TITLE
Page settings inheritance and shared cache

### ISSUE THREAD

**Issue by qzminski** [contao/contao#4699]
### Affected version(s)

4.13.x

### Description

It seems that there is a problem with page settings inherited data when the shared page cache is enabled:

1. If you open a regular page it will get cached. Then, if you enable the maintenance mode in the website root settings and visit the same page again, there will be no maintenance mode displayed, but rather the page content exactly as it has been cached.

2. If you open a regular page that has no layout defined (= inherits layout from parent page) it will get cached. Then, if you change the layout in the parent page and visit the same page again, the old layout will be displayed.

Possible solutions:

1. Add multiple response cache tags `contao.db.tl_page.` for every page ID in the current page trail.
2. Invalidate all children if a parent record is modified in the backend.

/cc @Toflar

**Comment by Toflar** [comment]
I think we should have a general response listener that adds the page tags and the trail (plus root page). I would do this in 4.13 only (even though it also affects 4.9) as there's a better way to access the page model in all circumstances. 4.9 still has quite some inconsistencies and I don't think it's worth investing. After all this is not a "bug bug". Cache invalidation when you edit is convenience, you shouldn't rely on it.

**Comment by ausi** [comment]
Wouldn’t it fit the current concept better if we would fix this in the backend?

We currently invalidate all parent (ptable) and all child (ctable) items, I think we should extend that so that parent and child items from tree views are handled the same way.

**Comment by fritzmg** [comment]
> 1. If you open a regular page it will get cached. Then, if you enable the maintenance mode in the website root settings and visit the same page again, there will be no maintenance mode displayed, but rather the page content exactly as it has been cached.

imho that's expected behavior. But the maintenance mode switch for the root could of course be changed to also invalidate the respective cache entries.

> Wouldn’t it fit the current concept better if we would fix this in the backend?

I agree. Also we should fix this in 4.9 then.

**Comment by aschempp** [comment]
This is really easy to fix even for 4.9, see https://github.com/contao/contao/pull/4714
