### ISSUE TITLE
Frontend-Preview Nachrichten / Events

### ISSUE THREAD

**Issue by SGehle** [contao/contao#47]
Hallo!
Wäre es nicht sinnvoll, wenn beim Klick auf die Frontend-Preview beim bearbeiten einer Nachricht oder eines Events der entsprechende Eintrag angezeigt wird anstelle der Startseite der Webseite?
Wenn ein Artikel bearbeitet wird, wird ja in der Vorschau auch direkt die Seite des Artikels geladen.

**Comment by leofeyer** [comment]
Ja. Allerdings ist das Ticket hier falsch. Du müsstest es bitte unter https://github.com/contao/core nochmals erstellen.
