### ISSUE TITLE
Session isn’t started inside ESI requests if it was startet in the main request

### ISSUE THREAD

**Issue by ausi** [contao/contao#470]
If the main request starts the session and there is no previous session (there is no session cookie in the request) then inside ESI requests (e.g. `{{request_token}}`) both `$session->isStarted()` && `$request->hasPreviousSession()` returns `false`.

**Comment by Toflar** [comment]
Ping @aschempp

**Comment by aschempp** [comment]
what Symfony version are you on? Maybe related to https://github.com/symfony/symfony/pull/30620

**Comment by leofeyer** [comment]
As discussed in Mumble on May 9th, @ausi will further debug this issue.

**Comment by ausi** [comment]
Not having access to a just started session inside the ESI request seems to be correct, so this is not a bug. See https://github.com/symfony/symfony/issues/31078#issuecomment-482173486

The related issue with the CSRF token will be solved differently.
