### ISSUE TITLE
Resize images command returns an error if image does not exist anymore

### ISSUE THREAD

**Issue by qzminski** [contao/contao#4723]
### Affected version(s)

4.13.x

### Description

The `contao:resize-images` command will return an error code if the source image does not exist: https://github.com/contao/contao/blob/4.13/core-bundle/src/Command/ResizeImagesCommand.php#L152-L162

Which will then be populated by parent process: https://github.com/contao/contao/blob/4.13/core-bundle/src/Command/ResizeImagesCommand.php#L367

Which results in a command exception:

![CleanShot 2022-05-24 at 15 00 20](https://user-images.githubusercontent.com/193483/170041014-3faebd60-7c83-4b03-9985-d259e2bbc4c3.png)

I think we should just return a success code, if the source image does not exist and the deferred image reference has been deleted. I would be able to provide a pull request, but first I'd like to know if it makes sense 😉 

/cc @Toflar

**Comment by Toflar** [comment]
I think the error code makes sense if someone wants to resize only one specific image. But if you run `contao:resize-images` without any argument (which will span itself with the argument, so we have to be careful here) it makes no sense, imho. Wdyt @ausi ?

**Comment by ausi** [comment]
The command itself should only fail if all resizes have failed, see https://github.com/contao/contao/blob/0e57eafe199ef2e5709e4d2c398dcf0e68a43026/core-bundle/src/Command/ResizeImagesCommand.php?rgh-link-date=2022-05-24T13%3A06%3A01Z#L331-L335

In your screenshot it appears that there were 7 images to resize and all of them failed to do so.

**Comment by Toflar** [comment]
The idea of this command is to have a worker in the background that resizes the images constantly so the web process is not tasked with this, right? At least we're using it like that because performance is more important than disk space. So the worker currently fails from time to time because no source image has been found anymore - why would I care? :)

**Comment by ausi** [comment]
It only fails if all source images are not found, which is a case you do possibly care, don’t you?

**Comment by Toflar** [comment]
Not at all :)

**Comment by ausi** [comment]
I’m not sure if I understand the use case correctly.
You could either ignore the exit code by using something like that:

```
$ vendor/bin/contao-console contao:resize-images || true
```

Or maybe we could introduce a `--worker` flag that is meant to run indefinitely?

How do you manage the background worker instance? Or is it just a cron job that runs every minute?

**Comment by Toflar** [comment]
Yeah we can ignore, sure. It was just more a question in which case the user ever needs to know those failures. I mean, a failure to me means I need to fix something. However, I cannot because the file is gone - so what's the point of telling me that it couldn't resize? :)

**Comment by ausi** [comment]
I think I understand it now. We should then add a `return 0;` after the following line: https://github.com/contao/contao/blob/0e57eafe199ef2e5709e4d2c398dcf0e68a43026/core-bundle/src/Command/ResizeImagesCommand.php#L159
