### ISSUE TITLE
Entities are not decoded in news/event titles

### ISSUE THREAD

**Issue by xchs** [contao/contao#473]
**Affected version(s)**

Contao 4.4.39

**Description**

If the **news title** contains special characters, the corresponding HTML entities are written into the HTML `<title>` element.

**How to reproduce**

* Create a new news item
* Insert a news title with special characters (e.g. `Lorem ipsum (foobar)`)
* Save and close the news item
* Open the news item in the front end and check the `<title>` element in the HTML source code:
```html
<title>Lorem ipsum &#40;foobar&#41; - Contao Official Demo</title>
```

**Comment by fritzmg** [comment]
That's how it should be, isn't it?

**Comment by xchs** [comment]
But the behavior differs between **regular pages** and **news articles**:

* **Regular page** with page title `Lorem ipsum (foobar)`:
```html
<title>Lorem ipsum (foobar) - Contao Official Demo</title>
```
* **News item** with news title `Lorem ipsum (foobar)`:
```html
<title>Lorem ipsum &#40;foobar&#41; - Contao Official Demo</title>
```

**Comment by xchs** [comment]
By the way, the same behavior also applies to **event titles**.

**Comment by leofeyer** [comment]
This is because `tl_page.pageTitle` has the `decodeEntities` flag set and `tl_news.headline` does not.

@contao/developers Any objections against adding the `decodeEntities` flag to the headline fields as well?

**Comment by Toflar** [comment]
Fine for me :)

**Comment by leofeyer** [comment]
Although – what exactly is wrong with the entities being encoded in the `<title>` attribute? Seems perfectly fine to me.

**Comment by ausi** [comment]
`tl_news.headline` also gets used in the HTML body where we need the entities to be encoded. Setting `decodeEntities` doesn’t seem to be the right solution here I think.

Encoded entities in the `<title>` seem fine to me too.

**Comment by leofeyer** [comment]
I wonder why we decode entities in the page title (see https://github.com/contao/contao/issues/473#issuecomment-489173414)?

**Comment by aschempp** [comment]
maybe because we use the title in XML sitemap etc. as well? 🤷‍♂

**Comment by leofeyer** [comment]
As discussed in Mumble on August 29th, we want to remove `'decodeEntities'=>true` in the `tl_page` DCA and check if there are places where we need to apply `StringUtil::decodeEntities()`.

**Comment by leofeyer** [comment]
See #1179
