### ISSUE TITLE
Use DeauthenticatedEvent

### ISSUE THREAD

**Issue by aschempp** [contao/contao#475]
https://github.com/symfony/symfony/pull/31138

Should we use this to delete all related `tl_remember_me` items?

**Comment by leofeyer** [comment]
Also see https://github.com/symfony/symfony/pull/31172

**Comment by leofeyer** [comment]
It seems this has been fixed in https://github.com/symfony/symfony/pull/34671. Can we close our issue then?

**Comment by aschempp** [comment]
not really. Symfony removes the cookie now, but we should still remove the entry from `tl_remember_me`?

**Comment by leofeyer** [comment]
So how do we proceed here?

**Comment by leofeyer** [comment]
@bytehead Could you please take a look at this?

**Comment by bytehead** [comment]
Close in favor of #5788
