### ISSUE TITLE
Keep some deprecated constants and methods for better BC with extensions

### ISSUE THREAD

**Issue by ausi** [contao/contao#4753]
https://github.com/contao/contao/pull/4741#issuecomment-1140804260 @aschempp
> I though we're also trying to keep important stuff that would break not-updated extensions 🤷

We should probably discuss what this “important stuff” is. From the top of my head:

- [ ] `TL_MODE`
- [ ] `TL_ROOT`
- [ ] `Controller::replaceInsertTags()`

@aschempp is there more?

**Comment by leofeyer** [comment]
+1 for `TL_MODE` and `TL_ROOT`.

But -1 for `Controller::replaceInsertTags()`; we have already discussed this and agreed to optionally add it again **after** the release of Contao 5.0 if it should turn out to cause a lot of problems.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we do not want to keep the constants.
