### ISSUE TITLE
Member login throws error when field language is eval multiple true

### ISSUE THREAD

**Issue by Aybee** [contao/contao#476]
**Affected version(s)**
4.4.39
not in 3.5.40

**Description**  
Die Fehlermeldung:
```
ContextErrorException

Warning: preg_match() expects parameter 2 to be string, array given
```
Verweis auf diese Code-Zeile
https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Translation/Translator.php#L431

Die Mitglieder sprechen mehrere Sprachen. Deswegen habe ich das Feld auf multiple gesetzt und die Speichermöglichkeit angepasst.
```php
$GLOBALS['TL_DCA']['tl_member']['fields']['language']['eval']['multiple'] = true;
$GLOBALS['TL_DCA']['tl_member']['fields']['language']['sql'] = "varchar(255) NOT NULL default ''"; // original is varchar(5)
```
Das klappt auch wunderbar. Man kann im BE mehrere Sprachen setzen und im Feld `tl_member.language` steht ein serialisiertes Array.

Aus irgendeinem Grund wird aber wohl im FE beim Login die Sprache des Mitglieds überprüft. Wenn er keine Sprache spricht (Feld ist leer) ist dies kein Problem. Spricht er aber mehrere (serialisiertes Array), dann geht nichts mehr.

**How to reproduce**  
put the value
```
a:2:{i:0;s:2:"de";i:1;s:2:"en";}
```
into `DB.tl_member.language`
Try to login as a member in FE.

**Comment by leofeyer** [comment]
@contao/developers Is this a supported use case?

**Comment by Toflar** [comment]
No, certainly not. A member cannot have multiple languages. We use this at various places e.g. to build the cache and more. Also there are possibly hundreds of extensions that expect a string there.
Just add a new field and maybe update the description of `language` to `Preferred language` or whatever.

**Comment by Aybee** [comment]
> @fritzmg Neue Tickets bitte im mono repository verfassen.

Jetzt bin ich verwirrt. Werden Contao Tickets nicht mehr hier erstellt? Was und wo ist das "mono repository"?

**Comment by Aybee** [comment]
> @Toflar  A member cannot have multiple languages. 

Oh that's a pity.

**Comment by leofeyer** [comment]
> > @fritzmg Neue Tickets bitte im mono repository verfassen.
> 
> Jetzt bin ich verwirrt. Werden Contao Tickets nicht mehr hier erstellt? Was und wo ist das "mono repository"?

Damit ist `contao/contao` gemeint und nicht mehr `contao/core-bundle`. Ich hatte Dein Ticket aber schon hierher verschoben.

<img width="573" alt="" src="https://user-images.githubusercontent.com/1192057/58911058-51ed1400-8717-11e9-9d39-992f5bfe152d.png">

**Comment by Aybee** [comment]
Ah, ok, danke.
