### ISSUE TITLE
Article List on 404 page throws RouteNotFoundException

### ISSUE THREAD

**Issue by MarkejN** [contao/contao#4769]
### Affected version(s)

4.13.4

### Description

When I place an article list module on a 404 page, I get a ResourceNotFoundException and a RouteNotFoundException. Which makes sense since there is no route for the articles. But maybe in this case the href could just be empty and all the other fields like title and id are still there?

```
Symfony\Component\Routing\Exception\ResourceNotFoundException:
Page ID 10 is not routable

  at vendor/contao/core-bundle/src/Resources/contao/models/PageModel.php:1368
  at Contao\PageModel->getFrontendUrl('/articles/id-404')
     (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticleList.php:100)
  at Contao\ModuleArticleList->compile()
     (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:214)
  at Contao\Module->generate()
     (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticleList.php:44)
  at Contao\ModuleArticleList->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:434)
  at Contao\Controller::getFrontendModule(object(ModuleModel), 'tabs_nav')
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:199)
  at Contao\PageRegular->prepare(object(PageModel))
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:60)
  at Contao\PageRegular->getResponse(object(PageModel))
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageError404.php:80)
  at Contao\PageError404->getResponse(object(PageModel), true)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:316)
  at Contao\FrontendIndex->renderPage(object(PageModel))
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:44)  
```

**Comment by Songworks** [comment]
Came upon this issue in 4.13.8 today.
The normal 404 page throws the exception "Page ID X is not routable".

edit: Also, I tried it with a completely empty, new 404 page. No visible article or content on it.

Anybody know a work around? :(

Having the 404 page redirect to another, normal page works visually at least but it would result in a 200 http status also, breaking anything that relies on the 404 status when encountering a missing pages.

Same is probably true for all the other 4xx and 5xx status pages...?

**Comment by kiparski-lumas-consulting** [comment]
> Came upon this issue in 4.13.8 today. The normal 404 page throws the exception "Page ID X is not routable".

The same thing is happening to us in 4.13.8, the log file is getting flooded with the "Page ID X is not routable". error for the 404 pages.

**Comment by Songworks** [comment]
Crude makeshift solution: Unpublish the 404-page within Contao.

That way, when Contao determines a page as 404 fe., it'll let the server/hosting handle it instead.
Whatever your server/hosting delivers won't be as pretty as Contaos status pages, but at least it has a proper status code again.

I've tested this for "401 Not authorized" page also.

**Comment by falkgeist** [comment]
I can confirm this error for Contao 4.13.12.

The plain and simple 404 page (no content) throws the RouteNotFoundException, preceded by the ResourceNotFoundException "Page ID XX is not routable" (whereas "XX" is the ID of the 404 page).

Of course the server 404 page is a workaround solution, but as already stated, not really pretty. If it wasn't for the status code, it would even be better to get the general contao error page...

**Comment by aschempp** [comment]
I think this might be fixed by https://github.com/contao/contao/pull/3540

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5792
