### ISSUE TITLE
New routing without URL suffix causes inheritance issue on 404 error pages

### ISSUE THREAD

**Issue by CMSworker** [contao/contao#4780]
### Affected version(s)

4.13.4

### Description

If a different page layout is used for the error pages than is defined in the "Website root", the CSS files of both page layouts are included in the header of the error page, when the 404 URL path contains an alias of an existing page. This inheritance problem seems to be caused by the new routing and also depends on URL aliases.

Example to recreate (can't be done in the online demo due to access restictions):

1) New Contao installation with

```
# config/config.yml
contao:
    # use new routing
    legacy_routing: false
```

2) Prepare simple theme css files in subfolders. For the test case just define different background colors, e.g. grey and orange.

![1](https://user-images.githubusercontent.com/31544192/171754171-72502a24-046e-4790-827d-e6b4df0f36aa.png)

3) Create a new theme, select the theme files folder and create two page layouts. One with the "grey" css file, the other with the "orange" css file. Disable "Combine Scripts" to be later able to see the single css file names in the frontend HTML header source code.

![2](https://user-images.githubusercontent.com/31544192/171754184-db11aa17-0f81-491f-8ae6-ad06218399f7.png)

4) Create 4 test pages in the "Site structure":
- Website Root (without "URL suffix") > Assign the grey page layout
- Homepage (index) > Assign the orange page layout
- Category (URL alias "category") > No page layout assigned
- A 404 error page > Assign the orange page layout

![3](https://user-images.githubusercontent.com/31544192/171754223-35c45bab-b7f0-4524-9277-e215a6f673ba.png)

5) Testing 404 error pages:

Test 1: yourcontaodomain.com/jhgfdsajhgfd (glibberish)
Result: 404 page is orange (as expected)

Test 2: yourcontaodomain.com/**category**/jhgfdsajhgfd
**Result: 404 page is grey (but should be orange as well)**

Now check the source code of Test 2: 
The CSS files of BOTH page layouts are included

```
<link rel="stylesheet" href="files/theme/css/layout2/orange.css?v=d52a56b1">
<link rel="stylesheet" href="files/theme/css/layout1/grey.css?v=587be0c7">
```

Somehow the "grey" page layout from the "Website root" gets inherited to the error page, that already uses the "orange" page layout. But this just happens when the 404 URL contains an alias of an existing page ("category" in my example).

Other findings from my tests:
- Changing "Enable folder URLs" doesn't influence this issue
- When you add an URL suffix in the "Website root" like ".html" the error will not occur
- When you remove "legacy_routing: false" in config.yml the error will not occur
- Changing locations of the CSS files seems not to influence the issue
- This doesn't solve the issue: https://github.com/friends-of-contao/contao.wtf/issues/14

**Comment by aschempp** [comment]
I think I know why this is happening, but I don't understand why this is related to legacy/modern routing at all, since both cases render the 404 page the same 😅 but I should be able to provide a pull request to fix this.

_Hint to myself: `TL_USER_CSS`_

**Comment by aschempp** [comment]
@CMSworker can you please test if https://github.com/contao/contao/pull/4828 fixes your issue? You might need to manually apply the changes in your Contao 4.19

**Comment by CMSworker** [comment]
@aschempp Tested and approved: The changes in #4828 solved the problem in my tests.

Maybe _legacy routing_ didn't show this CSS problem because it is adding the `.html` suffix by default? Don't know.

But anyway, thank you very much for the quick fix!
