### ISSUE TITLE
Contao search engine: News article with "noindex" is still indexed

### ISSUE THREAD

**Issue by CMSworker** [contao/contao#4795]
### Affected version(s)

4.13.5

### Description

When you select "Robots tag: noindex,follow" in a single news article setting, this article is still indexed by the Contao search engine and visible in the list of search results.

**How to reproduce:**

- Contao installation with newslist and newsreader (both pages with default "robots: index" settings)
- some news articles
- a page with the search engine module

Now go to the news articles and change the robots settings of one single news article to "noindex".

Then under "Maintenance" do "Purge the search index" and after that "Update the search index" > "Start crawling".

Then to the frontend: If you now search for a term that is only mentioned in the "noindex" news article, this article is still shown in the search results (but shouldn't because of the "noindex" setting).

**Comment by CMSworker** [comment]
Wait a second: Is this an intended behaviour, because the Contao search indexer logic is not looking for the "Robots: noindex" settings?

In this case I guess this issue could be closed, because then it is a feature request instead:

_Add Expert Setting "Do not search" in the news article setting to be able to exclude single news articles from the Contao Search_

Or is the way to handle this to add
 ```
<!-- indexer::stop -->
[...news article content...]
<!-- indexer::continue -->
```
in the single news article that should not be indexed?

**Comment by asaage** [comment]
> Or is the way to handle this to add
> ```
> 
> [...news article content...]
> 
> ```

This could probably result in nested indexer-stop blocks (depending on what the content actually is).
At this point it wouldn't work properly.
~~I would put this newsarticle into another archive with a reader that is on a "do not search - Site" if there are multiple occasions where that is needed.
For a "1of" a manual ```<!-- indexer::stop / continue -->``` wrapped around your content might work though.~~
(oops - never noticed the robots field for news)

**Comment by fritzmg** [comment]
> Wait a second: Is this an intended behaviour, because the Contao search indexer logic is not looking for the "Robots: noindex" settings?

The search index subscriber should take it into consideration.

**Comment by fritzmg** [comment]
I can confirm the issue. While the search indexer in the `kernel.terminate` event does not index the page if it has `noindex,follow`, when executing `contao:crawl` the page is still indexed.

**Comment by Toflar** [comment]
The subscriber should check for the `RobotsSubscriber::TAG_NOINDEX` tag.

**Comment by Toflar** [comment]
Closing in favor of my PR.
