### ISSUE TITLE
Add language option for global maintenance mode

### ISSUE THREAD

**Issue by rabauss** [contao/contao#4796]
### Description

It would be nice to set the `language` for the global `contao-maintenance-mode` e.g. `contao:maintenance-mode on --language=de`

At the moment `en` is always used as language for the global maintenance mode - see: 
https://github.com/contao/contao/blob/e95c3202701dfbf8e240f9755d91bc47a399c863/manager-bundle/src/Command/MaintenanceModeCommand.php#L88

**Comment by rabauss** [comment]
Okay I realized that `contao:maintenance-mode on --templateVars='{"language":"de"}'` is merging the template parameters, but the Output is not translated!

Only the html tag is "translated" to `<html lang="de">`

**Comment by koertho** [comment]
As I run into the same problem:

You can adjust the language with the default language config:
```
framework:
    default_locale: de
```

**Comment by aschempp** [comment]
changing the `default_locale` is not ideal, since not all labels might be available in `de` and `en` has always been our default value. But I agree there should be an option for the maintenance mode.

**Comment by Toflar** [comment]
Can we close this now that we have https://github.com/contao/contao/pull/6494?

**Comment by fritzmg** [comment]
I would be fine with closing this.
