### ISSUE TITLE
 Unknown insert tag flag |uncached

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#48]
**Affected version(s)**
Contao 4.4.23

**Description**  
Wenn ich insert-tags mit flags benutze erhalte ich im System Log immer die obige Meldung.

**How to reproduce**  
Ein Formular angelegt. 
Ein Modul [Eigener HTML-Code] angelegt mit 
`{{insert_form::1|uncached}}`
Das Modul im Seitenlayout eingebunden. Server-Cache aktiviert (5 Min.)

Die Mail wird verschickt aber der Eintrag im Log bleibt. Habe es auch mit {{insert_article::*|uncached}}, {{insert_module::*|uncached}}, {{insert_article::*|refresh}} oder {{insert_module::*|refresh}} probiert.

**Comment by cliffparnitzky** [comment]
Kann ich bestätigen. Gleiches tritt bei Contao 4.5 auf.

**Comment by leofeyer** [comment]
Fixed in d4fc9a443046caa67ae06b2c53513be574a94c42.

**Comment by fkaminski** [comment]
Danke, probiere ich aus.
Allerdings glaube ich das |refresh flag wird hier auch nicht berücksichtigt ...

**Comment by fkaminski** [comment]
Hallo, habe jetzt die 4.4.24 und die Fehlermeldung im Log ist weg.
Allerdings wird jetzt bei Nutzung von

`{{insert_form::1|uncached}}`

die Weiterleitungsseite des Formulars ignoriert. 
Nach dem Absenden des Formulars wird die aktuelle Seite aufgerufen?

**Comment by cliffparnitzky** [comment]
Der Fix sollte aber in der 4.4.24 noch gar nicht drin sein.

**Comment by fkaminski** [comment]
[Changelog 4.4.24](https://github.com/contao/contao/blob/4.4.24/CHANGELOG.md)

**Comment by cliffparnitzky** [comment]
Hmmm, okay.

**Comment by leofeyer** [comment]
> die Weiterleitungsseite des Formulars ignoriert.

Ich kann mir nicht vorstellen, dass das etwas mit der Änderung im Core zu tun hat. Aber Du solltest es trotzdem testen.

**Comment by fkaminski** [comment]
Hm,
weiß nicht was ich da noch weiter testen kann: 
Mit Flag bleibt er nach dem Versand auf der aktuellen Seite -
Ohne Flag wird nach dem Versand die angegebene Weiterleitungsseite aufgerufen ...

**Comment by leofeyer** [comment]
Dann mach mal bitte die Änderung rückgängig und ändere stattdessen die Zeile 1085

```php
$this->log('Unknown insert tag flag "' . $flag . '" in {{' . $strTag . '}}', __METHOD__, TL_ERROR);
```

in

```php
if ($flag != 'uncached' && $flag != 'refresh')
{
	$this->log('Unknown insert tag flag "' . $flag . '" in {{' . $strTag . '}}', __METHOD__, TL_ERROR);
}
```

**Comment by leofeyer** [comment]
Aber das kann ja nicht stimmen, denn das Flag ist ja nicht "unknown". Ich glaube das beschriebene Problem hat nichts mit der Änderung zu tun, sondern damit wie das Fragment behandelt wird.

@aschempp @Toflar /cc

**Comment by fkaminski** [comment]
Ja, sorry,
ich hätte wohl ein neues Issue eröffnen sollen ...

**Comment by aschempp** [comment]
Mit dem InsertTag oder Flag kann das doch nichts zu tun haben? 

> Allerdings wird jetzt bei Nutzung […] die Weiterleitungsseite des Formulars ignoriert.

Das deutet darauf hin dass die RedirectResponse nicht ankommt?

**Comment by leofeyer** [comment]
Vermutlich weil die Hauptresponse keine RedirectResponse ist, sondern nur die Fragment-Response.

**Comment by aschempp** [comment]
Die Fragment-Response ist ja eine Response, und die müsste eine Umleitung sein?

**Comment by leofeyer** [comment]
Vielleicht. :man_shrugging:

**Comment by aschempp** [comment]
~~Definitiv~~
~~https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/forms/Form.php#L560~~
~~https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/classes/Frontend.php#L473~~
~~https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1009-L1032~~

~~Ich sehe nur zwei Gründe warum es nicht funktionieren sollte:~~
 1. ~~Die Weiterleitungsseite wird nicht gefunden~~
 2. ~~`header_sent()` ergibt `true`~~

Ich weiss warum… https://github.com/contao/core-bundle/pull/1376#issuecomment-388747539

**Comment by leofeyer** [comment]
Aber den `RegisterFragmentsPass` gibt es erst seit der 4.5 und `ignore_errors` setzen wir erst seit der 4.6. Laut @fkaminski betrifft das Problem aber Contao 4.4. 🤔

**Comment by aschempp** [comment]
Die `uncached` Insert-Tags werden als ESI-Fragmente gerendert, und bei diesen werden Exceptions (z.B. unsere `RedirectResponse`) standardmässig ignoriert 😞

**Comment by leofeyer** [comment]
As discussed in Mumble on September 27th, this can be solved by adding `'ignore_errors' => false`:

```php
$strBuffer .= $fragmentHandler->render(
	new ControllerReference(
		'contao.controller.insert_tags:renderAction',
		array('insertTag' => '{{' . $strTag . '}}'),
		array('clientCache' => (int) $objPage->clientCache, 'pageId' => $objPage->id, 'request' => \Environment::get('request'))
	),
	'esi',
	array('ignore_errors'=>false) // see #48
);
```

**Comment by leofeyer** [comment]
Fixed in f8331ede751bbc49d8081614fd3b6e065d30fde1.
