### ISSUE TITLE
Return value of `$kernel->getContaoBundles()` not recognized

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#48]
@aschempp Any idea why the return value of `$kernel->getContaoBundles()` is not recognized by PhpStorm? I had to add an inline `@var` comment:

https://github.com/contao/core-bundle/blob/develop/contao/library/Contao/Automator.php#L556

**Comment by aschempp** [comment]
It works if you correctly set the type of the kernel variable (https://github.com/contao/core-bundle/blob/develop/src/HttpKernel/ContaoKernel.php#L33)

**Comment by leofeyer** [comment]
Perfect, thank you. Fixed in 164b47d2746ee2504d8eabe206aee742562b33a4.

I figure we cannot make PhpStorm understand `TL_ROOT`, can we?

**Comment by aschempp** [comment]
oh that would be nice… just played around with it, it seems to work if you place the following in `ide_compat.php`. It needs to be inside any of the namespace declarations.

```php
define('TL_ROOT', __DIR__ . '../../../');
```

**Comment by leofeyer** [comment]
Good idea but this does not work (check e.g. `DC_Folder`). It now says "multiple definitions". It will work if we change the [bootstrap file](https://github.com/contao/core-bundle/blob/develop/contao/bootstrap.php#L20):

```php
// Old
define('TL_ROOT', dirname($kernel->getRootDir()));

// New
define('TL_ROOT', __DIR__ . '../../../');
```

But then obviously we would be using an absolute path.

**Comment by aschempp** [comment]
It works perfectly fine for DC_Folder on line 1778 (`include TL_ROOT . '/system/config/ace.php';`) and does no longer say the folder "system" could not be found.

**Comment by leofeyer** [comment]
It does not work here :(
