### ISSUE TITLE
Individual navigation active item is trail instead active when get params in URL

### ISSUE THREAD

**Issue by Aybee** [contao/contao#480]
**Affected version(s)**
4.4.36

**Description**  
Auch bei einer individuellen Navigation wird der Menüpunkt der aktuellen Seite als `strong.active` genrendert. Dies funktioniert nicht mehr, sobald ein GET-Parameter in der URL vorkommt. Dieser Punkt wird dann als `a.trail` gerendert.

**How to reproduce**  
Teste eine individuelle Navigation mit GET-Parametern in der URL. Z.B. mit einem angepassten nav_default Template.
```php
...
<?php foreach ($this->items as $item): ?>
  <?php
    $item['href'] = $item['href'].'?key=value';
  ?>
...
```

**Comment by asaage** [comment]
Unter der Vorraussetzung, dass ```.active``` nicht klickbar ist und bleibt sehe ich bei einer Änderung eigentlich nur Usability-Nachteile wenn sich paginierte News- oder Event-Seiten, mp_forms oder auch [Suchergebnisse](https://demo.contao.org/en/search.html?keywords=Welcome&query_type=and) nicht mehr mit Navigationsmodulen auf ihren Ausgangszustand zurücksetzen lassen.

**Comment by leofeyer** [comment]
Da hat @asaage allerdings Recht.

**Comment by Toflar** [comment]
Das sehe ich anders. Paginierte Seiten werden über die Pagination erreicht. Dort findet sich auch der Link zurück auf die 1. Seite (welche nicht `page=1` enthalten sollte). `mp_forms` bietet ebenfalls einen eigenen `zurück`-Button. Die Navigation ist nicht dazu da, Filter von anderen Modulen zurück zu setzen, das muss jedes Modul selber machen.

**Comment by asaage** [comment]
> Filter von anderen Modulen zurück zu setzen, das muss jedes Modul selber machen.

Das machen sie ja auch seit jeher.
Ich würde auch die These unterstützen, dass ```.active``` Seiten durch einen Queryparameter nicht zu ```.trail``` Seiten werden sollten.
Vielleicht kann jemand mal eruieren, warum ein ```.active``` Navigations-Item nicht mehr klickbar sein soll (vielleicht eine SEO-Fachkraft) - dieses Pattern sehe ich nämlich auf einem Großteil der Seiten, die ich besuche nicht.

Url's nach dem Schema ```news/page/2```, ```events/month/201907``` oder ```myform/step/4``` wären evl. auch ein Weg, das elegant zu umschiffen (https://github.com/contao/contao/issues/390) weil die Queryparameter dann wegfallen. In diesen Fällen wären die Seiten (news, events, myform) in der Navigation dann jeweils korrekt als ```.trail``` markiert. Klingt nach einer komischen Herangehensweise - war mir aber die Überlegung wert ;)

**Comment by leofeyer** [comment]
> Vielleicht kann jemand mal eruieren, warum ein `.active` Navigations-Item nicht mehr klickbar sein soll (vielleicht eine SEO-Fachkraft) - dieses Pattern sehe ich nämlich auf einem Großteil der Seiten, die ich besuche nicht.

Eine SEO-Fachkraft wird Dir hier wohl nicht weiterhelfen können; eher jemand, der sich mit der Barrierefreiheit auskennt. Siehe z.B.: https://www.einfach-fuer-alle.de/artikel/menues/tag2/

@MacKP @kikmedia Trotzdem wäre es interessant zu wissen, warum das die Navigation  barrierefreier macht. Wisst ihr das zufällig?

**Comment by fritzmg** [comment]
Erst dadurch ist ja tatsächlich semantisch festgelegt, welcher Menüpunkt gerade aktiv ist. Die CSS Klasse alleine ist ja dahingehend nicht aussagekräftig.

**Comment by MacKP** [comment]
Da muss ich @fritzmg zustimmen. Zusätzlich ist es eigentlich auch noch so, dass man aus Sicht der Orientierung nicht auf die eigene Seite verlinken sollte (man geht über den Link auf den selben Inhalt und wundert sicht). Deswegen mach ich den Link um das Logo auch nicht auf der Startseite ;-)
Inzwischen gibt es zwar auch noch weiter möglichkeiten die aktuelle Seite zu kennzeichnen -> [aria-current](https://www.hellbusch.de/mit-aria-current-das-aktuelle-element-anzeigen/) Aber: Wo ohne aria gearbeitet werden kann ist immer besser ;-)
Viele Grüße

**Comment by fritzmg** [comment]
Ich denke wir sollten, wie @Toflar vorgeschlagen hat, den active state beibehalten, wenn GET Parameter vorhanden sind.

Den Rest kann sich ja jeder selbst im Template anpassen, nach Belieben.

**Comment by kikmedia** [comment]
Sehe ich exakt so wie @MacKP - und ich bin ebenfalls der Meinung, das bei Verlinkung eigentlich die Orientierung schlechter wird, weil ich dort, wohin ich navigieren kann, ja bereits bin.

**Comment by leofeyer** [comment]
Wir haben das Thema übrigens schon einmal diskutiert. Vor Contao 3.4 war es offenbar schon so, wie wir es jetzt neuerdings wieder haben wollen: https://github.com/contao/core/issues/7189

**Comment by asaage** [comment]
Abstimmung durch Münzwurf... 😄 ich glaub ich bin raus.

**Comment by MacKP** [comment]
> Wir haben das Thema übrigens schon einmal diskutiert. Vor Contao 3.4 war es offenbar schon so, wie wir es jetzt neuerdings wieder haben wollen: [contao/core#7189](https://github.com/contao/core/issues/7189)

Und ich bin da immer noch ganz bei @NinaG ^^

**Comment by leofeyer** [comment]
Wir müssen also `$href == Environment::get('request')` durch einen neuen Check ersetzen, der nur den Pfad ohne Query-String vergleicht. Dann sollte es passen.

**Comment by Toflar** [comment]
Richtig.

**Comment by leofeyer** [comment]
Dann sollte dies jetzt in 7a4cd8404a1ec0c4b701de501f738959042fd304 behoben sein.

**Comment by Toflar** [comment]
`Environment::get('path')` wäre wohl die elegantere Variante gewesen anstatt zu exploden, nicht? 😄 Oder gibt die nicht das zurück was sie sollte (den Pfad 😄 )?

**Comment by leofeyer** [comment]
`Environment::get('path')` ist nicht dasselbe wie `Environment::get('request')` ohne Query-String!

**Comment by Toflar** [comment]
I see, also wäre die Antwort auf meine Frage ein "Nein" gewesen 😄

**Comment by asaage** [comment]
Wie oben bereits erwähnt ist nicht nur mod_customnav sondern auch mod_navigation davon betroffen.

**Comment by Toflar** [comment]
Und? Der Fix ist ja auch in `ModuleCustomnav`? Oder was meinst du?

**Comment by asaage** [comment]
In ```ModuleCustomnav``` ja - hatte mich nur gewundert warum nicht auch in ```ModuleNavigation```

**Comment by Toflar** [comment]
`ModuleNavigation` erbt von `Module` und nutzt die parent Methode für die Navigation. Passt schon alles so 😄
