### ISSUE TITLE
Contao ignores dca files if any throwable occurs

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#4803]
### Affected version(s)

4.13.5

### Description

Since 4.13.5 the `RelLightboxMigration` loads dca containers and silences any `Throwable`. If there occurs an error (e.g. undefined array index warning) the error is ignored and Contao wants to delete existing and required database fields.

https://github.com/contao/contao/blob/e95c3202701dfbf8e240f9755d91bc47a399c863/core-bundle/src/Migration/Version413/RelLightboxMigration.php#L89-L93

**Comment by ausi** [comment]
Not to self: probably remove the try/catch and get the list of DCA tables like the installer does in https://github.com/contao/contao/blob/0e6512a5f010f6fb4d1359a2798c29eb74e3304c/core-bundle/src/Resources/contao/library/Contao/Database/Installer.php#L177
