### ISSUE TITLE
Move site structure to content group in Contao 5 back end menu

### ISSUE THREAD

**Issue by bezin** [contao/contao#4806]
### Description

Hello there, 

it never felt right to me, that the site structure is located in the layout group. To me, it belongs to the content group as the very first item. I propose we change that in Contao 5.0. 

(Yes, sometimes I just want to see the world burn 🔥 I mean it though 😂)

I expect this to be a little controversial, but I am happy to hear your thoughts :-)

Cheers

**Comment by leofeyer** [comment]
I am open for discussion, but I don‘t think that pages are content. Pages need both articles (actual content) and a layout (with modules etc.) to work, but they do not provide any content themselves (except maybe the meta title and description).

I agree that pages do not fit 100% in the layout section, though.

**Comment by ausi** [comment]
If it doesn’t fit in any secion, having it as the first entry above “Content” without a category might work too.

But as “Forms” are also in the content section, I think the Site structure (maybe rename to “Pages” then) fits into “Content” way better then layout.

All subjective though, as there is probably no “right” or “wrong” here ☺️

**Comment by bezin** [comment]
> I am open for discussion, but I don‘t think that pages are content. Pages need both articles (actual content) and a layout (with modules etc.) to work, but they do not provide any content themselves (except maybe the meta title and description).

To me, pages are the backbone of the website's content architecture and they are content themself. The require a layout but are not part of it. 

> If it doesn’t fit in any secion, having it as the first entry above “Content” without a category might work too.
But as “Forms” are also in the content section, I think the Site structure (maybe rename to “Pages” then) fits into “Content” way better then layout.

Yes, agree with this, I would also like to call it pages. It is not only about semantics, but also about priority – pages are quite buried in the layout section, especially if you add some more custom menu items to the content group. 

Also our editors usually do not have access to the layout section (layout, modules, image sizes...), but most of the time have access to the site structure. That is then the only option in the layout section and that feels kinda off.

**Comment by ameotoko** [comment]
I would think about combining "Site structure" and "Articles" into one backend module. But this will probably complicate a lot of things (although I think there used to be an extension that does that already).

**Comment by bezin** [comment]
> I would think about combining "Site structure" and "Articles" into one backend module. But this will probably complicate a lot of things (although I think there used to be an extension that does that already).

This discussion has taken place many times already :D But yes, I think so, too. However, I did not want to open this can of worms, too :-)

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to move sites and files to the "Content" area as a test and see how this feels for everyone. We can always revert later.

**Comment by bezin** [comment]
Sorry, did not see you self-assigned this
