### ISSUE TITLE
Custom 404 page is not shown for regular Symfony controllers

### ISSUE THREAD

**Issue by ausi** [contao/contao#4821]
### Affected version(s)

4.13, probably 4.9

### Description

If a Symfony controller throws a `NotFoundHttpException` as we do for example in https://github.com/contao/contao/blob/29856d68eb3fc12db9e20dd43b54e5df716e8005/core-bundle/src/Controller/ImagesController.php#L53 the custom 404 page from the site structure is not shown, instead the default 404 page is sent to the user.

This can be reproduced easily:
- https://contao.org/assets/images/foo default 404 page
- https://contao.org/assets/image/foo correct 404 page

The reason for that is, that the pretty error screen listener requires a `pageModel` attribute on the request to be present in order to determine the correct root page from which the 404 page should get shown: https://github.com/contao/contao/blob/29856d68eb3fc12db9e20dd43b54e5df716e8005/core-bundle/src/EventListener/PrettyErrorScreenListener.php#L149

I think the correct solution would be, if the `pageModel` is not set on the current route, to get the root page from the routing by providing the hostname and accept-language header of the request.

A possibly related problem is, that many places in Contao get information from the `$GLOBALS['objPage']` for which some of it is only set in `PageRegular` like the theme folder from which to load templates from: https://github.com/contao/contao/blob/f536cf98b55fbaf9ff481b0ff96f7228a2542321/core-bundle/src/Resources/contao/pages/PageRegular.php#L96

So maybe there should be a way to tell the system to _“run in the context of page or root page X“_?

**Comment by aschempp** [comment]
It is currently intended to not render the 404 in all cases. But I think we should try to render it if we have a frontend scope.

**Comment by fritzmg** [comment]
> So maybe there should be a way to tell the system to _“run in the context of page or root page X“_?

👍 

Just wanted to also note that the same also applies to 401 and 403 .

Within my `fritzmg/contao-file-access` extension I currently have the controller's scope defined as `frontend` and I am setting the root page of the current domain (and language) [manually](https://github.com/fritzmg/contao-file-access/blob/master/src/Controller/FilesController.php#L64-L71), which is not ideal.

**Comment by leofeyer** [comment]
As discussed in the Contao call, the pretty error listener should handle all HTML requests, even on non-Contao routes, if there is a matching root page in the site structure.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5794
