### ISSUE TITLE
Backend, Frontend & Manager login not working after plesk php 7.4 to 7.4.30

### ISSUE THREAD

**Issue by vmcgiov** [contao/contao#4835]
### Affected version(s)

4.9.x

### Description

All of our Contao-Installations have the issue that we cant login anymore after recent plesk update from 7.4 to 7.4.30. This includes tl_member, tl_user aswell as contao-manager login. Does anyone else suffer same issues? Everything works fine with 4.4

**Comment by aschempp** [comment]
This sounds like a server misconfiguration, make sure the server time is correct. Also, please refer to the community support options (https://to.contao.org/support) to get help about your server setup, we're using GitHub only for bug and feature tracking.

**Comment by vmcgiov** [comment]
Server time is set correct and in my opinion everything is configured the way it is supposed to be.

are you sure it has nothing to do with latest 7.4.30 bug fix [#81719] (http://bugs.php.net/81719) ?

**Comment by vmcgiov** [comment]
we run into the same problem on multiple servers (15+) and for every 4.9 installation we have.

**Comment by fritzmg** [comment]
@vmcgiov I just tried with PHP 7.4.30 locally and logging into the back end works fine.

**Comment by vmcgiov** [comment]
thank you for checking. was the 4.9 a fresh install or updated from 4.4?
> 



> @vmcgiov I just tried with PHP 7.4.30 locally and logging into the back end works fine.

**Comment by fritzmg** [comment]
@vmcgiov conceivably it could be that before the PHP update your server environment had `libsodium` enabled for PHP, and now it does not.

// although, I could not really reproduce it this way either

**Comment by vmcgiov** [comment]
> @vmcgiov conceivably it could be that before the PHP update your server environment had `libsodium` enabled for PHP, and now it does not.
> 
> // although, I could not really reproduce it this way either

@fritzmg i double checked. **libsodium** support is enabled and so is everything else required for 4.9 based on contao docs

**Comment by fritzmg** [comment]
It turns out this was a bug in the recent Plesk update, which caused argon2i to not be available anymore. It has since been fixed.

* https://talk.plesk.com/threads/missing-argon2i-and-argon2id-password-hash-algorithms-since-php-7-4-30.365241/#post-910368
* https://docs.plesk.com/release-notes/obsidian/change-log/#plesk-18044-mu3

**Comment by vmcgiov** [comment]
> It turns out this was a bug in the recent Plesk update, which caused argon2i to not be available anymore. It has since been fixed.
> 
>     * https://talk.plesk.com/threads/missing-argon2i-and-argon2id-password-hash-algorithms-since-php-7-4-30.365241/#post-910368
> 
>     * https://docs.plesk.com/release-notes/obsidian/change-log/#plesk-18044-mu3

thank you. I saw it too a few minutes ago. updated a few servers to verify. seems like it indeed solves the issues. :)

take care,
Claudio
