### ISSUE TITLE
Make media files in content element player sortable

### ISSUE THREAD

**Issue by dennisbohn** [contao/contao#4837]
### Description

It would be great if you could sort the media files inside the content element player.

![image](https://user-images.githubusercontent.com/87128053/173814105-fb02320b-c4da-4a50-b663-7c3944e363da.png)

When a video element contains multiple source files the browser selects the first supported element. When I mix h264 and vp9 I want the more efficient vp9 file as the preferred element and the h264 as fallback.

**Comment by asaage** [comment]
I honestly lost track of what is currently supported by what browser and what is preferable in terms of filesize/compression/quality...

Can't we have this automatically sorted?
Is the browser-descision based on the mime-type, the fileextension because the container-format has little to do with the codec right?
I think a manual-sort feature would be easy to add but who would realy know how to make efficient use of it?

**Comment by fritzmg** [comment]
> Can't we have this automatically sorted?

That would require file inspection. Currently the player content element automatically sorts according to the file extension. 

https://github.com/contao/contao/blob/7d9034fd5f3066e2a2fec3fe77fceb9d8035a117/core-bundle/src/Resources/contao/elements/ContentPlayer.php#L114

> I think a manual-sort feature would be easy to add but who would realy know how to make efficient use of it?

This was discussed before, but we decided against it for this very reason.

**Comment by dennisbohn** [comment]
It is a little bit annoying. At the moment I use a php script inside the video template to put the webm file before the mp4 file. Is there no way thats more userfriendly to change the order?

When there is just a fixed order you should put webm before mp4. mp4 is user for h.264 and h.265 codec. But h.265 is only supported by safari at the moment. Youtube is using vp9 for 4k videos for example and its supported by the most browsers. https://en.wikipedia.org/wiki/HTML5_video#Browser_support

Allowing users to change the order wouldnt be a disadvantage for users who dont care about video formats, because browsers automaticly pick the next supported format. For those who do it would help a lot.

**Comment by ausi** [comment]
> what was the reasoning behind sorting MP4 before WebM again?

Don’t think there was a reasoning behind that, we had no video expert to consult I think ☺️

@dennisbohn can you suggest a better sort order that we should use by default in Contao?
The current one is: `mp4`, `m4v`, `mov`, `wmv`, `webm`, `ogv`

**Comment by dennisbohn** [comment]
I would suggest to put webm in first place:
webm, mp4, m4v, mov, wmv, ogv

That would allow to use the more efficient and open source VP9 (webm) as preferred codec and H264 (mp4) as fallback.

People who just use mp4 (probably in most cases) wouldnt be affected by this change.

**Comment by ausi** [comment]
We should change the line https://github.com/contao/contao/blob/93b35a83ffd2bbc46a31b8c547e3b260f96f94be/core-bundle/src/Resources/contao/elements/ContentMedia.php#L117 then to:

```php
$arrFiles = array('webm'=>null, 'mp4'=>null, 'm4v'=>null, 'mov'=>null, 'wmv'=>null, 'ogv'=>null);
```
