### ISSUE TITLE
sectionwizard.js is broken

### ISSUE THREAD

**Issue by m-vo** [contao/contao#4844]
### Affected version(s)

5.x

### Description

In the current 5.x, the copy/delete/enable buttons in the `sectionwizard` are not working for me.

I get this error in the JS console - for instance when editing a layout:
![image](https://user-images.githubusercontent.com/5305677/174259380-84c32844-530d-488f-a3bc-d815059cb76e.png)

Here is the stacktrace in the unminified source:
```
sectionwizard.min.js?v=f3c63d9b:17 Uncaught TypeError: Cannot read properties of null (reading 'children')
    at makeSortable (sectionwizard.min.js?v=f3c63d9b:17:34)
    at sectionwizard.min.js?v=f3c63d9b:102:13
    at NodeList.forEach (<anonymous>)
    at init (sectionwizard.min.js?v=f3c63d9b:7:52)
    at sectionwizard.min.js?v=f3c63d9b:115:25
    at NodeList.forEach (<anonymous>)
    at MutationObserver.observe.attributes (sectionwizard.min.js?v=f3c63d9b:113:37)
```

The same is true for the `modulewizard`, though I'm not sure if this is just a follow-up error.

**Comment by aschempp** [comment]
What browser? What back end page? Did you click anything?

**Comment by m-vo** [comment]
Chrome Version 102.0.5005.115 (64-bit) on Linux. The fun thing is, that the error only sometimes appears with the page load. Seems like a race condition.

But I also noticed, that the buttons don't work no matter if the error is displayed or not.

Ah and: Themes / Layout / Layout XY is the page I'm looking at.

**Comment by m-vo** [comment]
The issue is, that `const tbody = table.querySelector('tbody')` can get executed before the DOM is ready - in this case `tbody` is `null` and `makeSortable(tbody)` fails.

**Comment by aschempp** [comment]
should be fixed by https://github.com/contao/contao/pull/4939
