### ISSUE TITLE
Fehler in StringUtil::deserialize

### ISSUE THREAD

**Issue by do-while** [contao/contao#4852]
### Affected version(s)

4.13

### Description

Ich habe vielfach in der Datenbank ein leeres serialisiertes Array:
`s:0:"";`

Mit `\StringUtil::deserialize('s:0:"";')` erhalte ich den String unverändert zurück.
Das unsichere PHP `unserialize` liefert korrekt ein Leerstring zurück

Bei mir: PHP 8.1.5

**Comment by ausi** [comment]
`StringUtil::deserialize` can only handle serialized arrays, not strings, see https://github.com/contao/core-bundle/pull/1486

**Comment by do-while** [comment]
Ok, das war mir nicht aufgefallen, bei Array müßte ja es ja mit a: anfangen.
Dann muss ich wohl eher gucken, wie das vom Formular in die Datenbank hinein kommt.

**Comment by ausi** [comment]
Ja, wenn Contao irgendwo `s:0:"";` wegspeichert wäre das jedenfalls ein Bug denke ich.
