### ISSUE TITLE
&nbsp; statt 0 in Modul "Auflistung"

### ISSUE THREAD

**Issue by akroii** [contao/contao#4856]
### Affected version(s)

4.9.30

### Description

Wenn man über das Auflistungs-Modul Werte einer Spalte versucht auszugeben, wird statt `0` irgendwie `&nbsp;` ausgegeben.

[https://github.com/contao/contao/blob/47697073752ae4d6fa6b63b28e0b54c50a8143f3/listing-bundle/src/Resources/contao/modules/ModuleListing.php#L316](https://github.com/contao/contao/blob/47697073752ae4d6fa6b63b28e0b54c50a8143f3/listing-bundle/src/Resources/contao/modules/ModuleListing.php#L316)

Aktuell nur in 4.9.30 gesehn und getestet.

**Comment by bezin** [comment]
This goes back to at list 4.0.0 ^^ https://github.com/contao/contao/blob/4.0.0/listing-bundle/src/Resources/contao/modules/ModuleListing.php#L310

**Comment by bezin** [comment]
[Maybe we could transform 1 and 0 to bool here](https://github.com/contao/contao/blob/47697073752ae4d6fa6b63b28e0b54c50a8143f3/listing-bundle/src/Resources/contao/modules/ModuleListing.php#L402)?

**Comment by fritzmg** [comment]
We can just change it to

```php
null !== $value && '' !== $value ? $value : '&nbsp;'
```

**Comment by ausi** [comment]
What we often use for this kind of checks is `'' !== (string) $value` AFAIK.
