### ISSUE TITLE
Files explorer icons are uploaded on drag

### ISSUE THREAD

**Issue by aznoqmous** [contao/contao#4863]
### Affected version(s)

4.13

### Description

Funny discovery this morning

How to reproduce : 
Drag edit/copy/cut/delete/info icons on files explorer and they will be uploaded as file

I've only tested it on Contao 4.13 but it might affect previous versions

![files-explorer](https://user-images.githubusercontent.com/17268514/175229270-89669d25-0b28-4fca-b12e-4deaa8101c81.jpg)

**Comment by fritzmg** [comment]
That's normal I'd say. You can drag any file you want into the file manager.

**Comment by aznoqmous** [comment]
Yes it's not really a "bug" but you could click on "Edit" and slightly move at the same time, which will result on uploading edit.svg file in the current directory

Its more of an improvement/polish to make to the file explorer IMHO

**Comment by fritzmg** [comment]
Yes, we could set `draggable="false"` on those images 👍

**Comment by aznoqmous** [comment]
Should I open an issue in Improvements/Feature as "Prevent drag on backend buttons" for this ?

**Comment by bytehead** [comment]
Could not reproduce on Contao 4.9.

**Comment by ausi** [comment]
> Should I open an issue in Improvements/Feature

No, this one is fine.

**Comment by ausi** [comment]
I was also not able to reproduce that, @aznoqmous can you give more detailed instructions on how this can happen?
What browser are you using?

**Comment by aznoqmous** [comment]
To reproduce it : 

1. Go to **Files explorer**
2. Mousedown any **list operation button**
3. Slightly move will not releasing the mouse to initiate drag
4. The `<img>` inside the button is uploaded in the current directory

The problem doesnt occur with global operation buttons (link is dragged instead of the inner `<img>`)

Im using Chrome 102.0.5005.115 on Windows 10

It could reproduce it on Contao 4.9.29

**Comment by ausi** [comment]
I was only able to reproduce this in Chrome on Windows. So maybe this is a Chrome-Windows bug.

**Comment by ausi** [comment]
In Chrome 95 on Windows everything still works correctly. 

So it seems this bug was introduced with Chrome 96 on Windows, and it therefore should be reported to Chrome.

**Comment by asaage** [comment]
The list operation buttons are images while the global operation buttons have css background.

If i had to completely redesingn that i'd say every line needs to be a form, and the list operation buttons need to be input type="image" or button with css. That would also eliminate the humongous url's and reduce the amount of markup significantly.

 ```draggable="false"``` on those images might be the easiest reliable solution. 
Maybe there are also css solutions like ```user-drag: none``` or ```user-select: none```

**Comment by ausi** [comment]
> and it therefore should be reported to Chrome.

Did anyone do that?
Because if Chrome fixes it, we don’t need a fix in Contao itself and can close this issue.
