### ISSUE TITLE
Concept for kernel.terminate with HttpCache

### ISSUE THREAD

**Issue by Toflar** [contao/contao#4869]
### Affected version(s)

all

### Description

Currently, the `kernel.terminate` event is being dispatched in both cases, with and without HttpCache. This is apparently by design as Symfony does so too and it's not wrong by definition as it also be valuable if e.g. you need to cleanup things that happened during the PHP process.

However, we also have listeners that do not make any sense when the response is coming from the cache.

For example our `SearchIndexListener`: It executes search index update database queries for every single successful cached `200` response. Which is absolutely pointless because the index **must** be up-to-date as it was adjusted the first time the response was not delivered from the cache. This is particularly problematic if you have a lot of traffic as you'll ramp up database connections for no reason.

Also, our `CommandSchedulerListener` executes DB requests. In this case, we could argue that it's useful for the poor man's cron. However, if you consider the case of a real reverse proxy like Varnish, no `kernel.terminate` listener would be called either. So in that case you would neither get any search index updated (good) nor any poor man's cron executed (debatable).

There are two possible solutions that come to my mind:

- Checking if the response has `Contao-Cache: hit` header. Then we need to discuss how the listener gets `Contao-Cache` configured because it's currently no information the container has (it's part of HttpCache) and your non ME app might have a different header name. Ideas?
- We add some kind of header to the `Request` before calling `$kernel->terminate()` which I'm not really sure if that's the correct approach because that can be tampered with.

But again, as the comparison with Varnish shows: We might also discuss whether it's correct to call `->terminate()` on `ContaoCache` (at least for the ME) at all.
I know it seems to be against the default of Symfony but on the other hand, if we go with e.g. the response header solution, every `kernel.terminate` listener has to implement that check and things wouldn't work the same with a real proxy anyway🤔

**Comment by aschempp** [comment]
I like the idea of disabling `kernel.terminate` for cached results, but the response header is the only viable option I can think of.

**Comment by leofeyer** [comment]
Not sure if we should disable the event (or not call `terminate()` on the kernel) because we don‘t know what all the listeners do. But I agree that we should not index responses coming from cache and probably not run cronjobs.

**Comment by Toflar** [comment]
I actually gravitate towards not calling any listener on cache hit. Because that's exactly what would happen in the Varnish case. Right now, it's booting the whole application to call the listeners which makes absolutely no sense. If you need something to happen after cache hit, you have to implement it in the proxy. In Varnish or anywhere else. That's why we have HttpCache subscribers.

I think I'll propose the change to Symfony itself as well and see how the discussion is going there.

**Comment by fritzmg** [comment]
Even if Symfony thinks it should be removed, I don't think it should be removed for Contao. At least we need to make sure that things like the scheduler still works during a cache hit - because that's what many setups will rely on.

**Comment by Toflar** [comment]
I strongly disagree with that. If something is coming from the cache, nothing on that system should be booted or done. That's the whole idea of a cache proxy. 

I'm not willing to accept a slower system just because of some hack. The current implementation of the scheduler is perfectly fine and it's still going to be called often enough (e.g. always when you log into the back end). 

If you want reliability, use a real cron. That's the only way to get reliability.

**Comment by Toflar** [comment]
Symfony PR: https://github.com/symfony/symfony/pull/46763

**Comment by Toflar** [comment]
BTW: If you really, really want that scheduler to run after the proxy, it should be a proxy subscriber (here: https://github.com/contao/contao/blob/4.13/manager-bundle/src/HttpKernel/ContaoCache.php#L50) - but I consider this to be a bad idea because it will cause a DB connection on every cache hit which is nonsense. And again, even if we did that, you still don't have a reliable cron.
