### ISSUE TITLE
Issue with relative URLs

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#4871]
### Affected version(s)

5.x

### Description

In #4851 we enabled the possibility to remove the `<base>` tag by outputting only absolute URLs. However, this does not work for any custom fields. For example:

```php
// contao/dca/tl_content.php
use Contao\CoreBundle\DataContainer\PaletteManipulator;

$GLOBALS['TL_DCA']['tl_content']['fields']['someLink'] = [
    'label' => ['Some link', 'Some link relating to the text.'],
    'inputType' => 'text',
    'eval' => ['rgxp' => 'url'],
    'sql' => ['type' => 'string', 'length' => 2048, 'default' => ''],
];

PaletteManipulator::create()
    ->addField('someLink', 'text_legend', PaletteManipulator::POSITION_APPEND)
    ->applyToPalette('text', 'tl_content')
;
```

```php
<!-- templates/ce_text.html5 -->
<?php $this->extend('ce_text'); ?>

<?php $this->block('content'); ?>
  <?php $this->parent(); ?>

  <?php if ($this->someLink): ?>
    <p class="someLink"><a href="<?= $this->someLink ?>">Some Link</a></p>
  <?php endif; ?>
<?php $this->endblock(); ?>
```

This will still output a relative URL and thus would not work if the `<base>` tag was removed.

In my original PR we discussed, that for any back end input field that can hold a URL a `save_callback` needs to be implemented so that the URL is always saved with `{{env::base}}` (or whichever insert tag is the correct one now) prefixed, if it's not an absolute URL (or insert tag) yet.

**Comment by ausi** [comment]
How about intercepting these values on save here: https://github.com/contao/contao/blob/f476d2a6b19f9982fffb8ca0b9be722da4ddff12/core-bundle/src/Resources/contao/library/Contao/Widget.php#L969-L981

We could prefix `{{env::base}}/` there I think. We could also remove this when loading the widget so that the user doesn’t see whats going on behind the scenes. But I’d prefer the user to see it (as they to with `|urlattr` in insert tags)

**Comment by fritzmg** [comment]
It also needs to be applied for any link in the RTE though.

**Comment by ausi** [comment]
> It also needs to be applied for any link in the RTE though.

This should already be the case in https://github.com/contao/contao/blob/f476d2a6b19f9982fffb8ca0b9be722da4ddff12/core-bundle/src/Resources/contao/classes/DataContainer.php#L468

**Comment by leofeyer** [comment]
That is not what we have discussed yesterday, though. We do not want to prefix `{{env::base}}/` when saving values (except in TinyMCE) but add `Environment::get('base')` or `$request->getBasePath().'/'` where ever these values are used.

**Comment by fritzmg** [comment]
But that's bad UX/DX. Previously we were able to add and output custom fields like shown above. But now everybody always has to:

* check whether the URL is an insert tag or absolute,
* and add the base path if not

when outputting any such variable in a custom template?

**Comment by leofeyer** [comment]
Correct. That‘s what the core has to do, too.

**Comment by fritzmg** [comment]
What if we added the logic to `StringUtil::specialcharsUrl` at least then? Then you'd always only need:

```php
<a href="<?= Contao\StringUtil::specialcharsUrl($this->someLink) ?>">Some Link</a>
```

**Comment by leofeyer** [comment]
In your example, `$this->someLink` should already have been prefixed when passed to the template.

**Comment by fritzmg** [comment]
> In your example, `$this->someLink` should already have been prefixed when passed to the template.

It's not, the template variable is passed as is.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add a helper method to the Template class and a Twig helper method that prefixes relative URLs with the request base path.
