### ISSUE TITLE
The service "contao.controller.backend_csv_import" was not found or is not public

### ISSUE THREAD

**Issue by kikmedia** [contao/contao#49]
Contao 4.6.2

On a fresh installation (PHP 7.1, Hosteurope Webserver, Symfony 4) I get the following:

 `[2018-09-05 10:40:41] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "The service "contao.controller.backend_csv_import" was not found or is not public. See https://symfony.com/doc/current/service_container.html#public-versus-private-services" at /is/htdocs/path/contao4.6/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php line 219 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): The service \"contao.controller.backend_csv_import\" was not found or is not public. See https://symfony.com/doc/current/service_container.html#public-versus-private-services at /is/htdocs/path/contao4.6/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php:219)"}`

How to reproduce

Create a new content element 'Table' and click on the 'Import CSV'-Icon.

**Comment by leofeyer** [comment]
Fixed in fc274605bb10dd458466fb49e1e5559e99287c34.
