### ISSUE TITLE
Do not cache bundles in debug mode

### ISSUE THREAD

**Issue by aschempp** [contao/contao#49]
I suggest to not cache bundles if the kernel is in debug mode. This can easily be implemented by not adding the `AddBundlesToCachePass` and not calling `loadBundleCache` in the `app_dev.php`

**Comment by leofeyer** [comment]
What's the point? Symfony does not bypass the cache in the dev environment, either.

**Comment by aschempp** [comment]
It sure does rebuild the container every time in dev mode. Not sure if its related to debug=true or the environment.

**Comment by leofeyer** [comment]
This ticket is redundant now :)
