### ISSUE TITLE
Broken subpalette toggling in 5.x

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#4900]
### Affected version(s)

5.x

### Description

Toggling subpalettes currently seems to be broken in `5.x`:

![image](https://user-images.githubusercontent.com/10257912/176475667-398cf376-4aca-4a68-972e-ec0cd227fce5.png)

(same problem in `tl_content` when editing content elements, for example)

I didn't get to the bottom of this yet, but the hint might be, that the whole palette is returned in the response, instead of requested subpalette, see screenshots below:

`5.x`:

![image](https://user-images.githubusercontent.com/10257912/176476937-a82b9159-608a-4310-af36-eb4a6a0823d9.png)

`4.13`:

![image](https://user-images.githubusercontent.com/10257912/176476978-faec3ec2-514f-4447-bad2-722ba5cb665c.png)

The problem appears on a clean fresh install of `5.x-dev`

**Comment by aschempp** [comment]
I guess that would be related to https://github.com/contao/contao/pull/4375

**Comment by ameotoko** [comment]
> I guess that would be related to #4375

That should not affect anything, the XHR request is identical in both branches (apart from request token etc.). The problem is, `$dc->edit()` renders the whole palette in `Ajax::executePostActions()` for some reason:

https://github.com/contao/contao/blob/94c2febf9e9da4aca45cc39077ee12e229014c9e/core-bundle/src/Resources/contao/classes/Ajax.php#L356-L359

Instead, I think #4792 might be responsible. This is the last big change to `DC_Table::edit()`.

**Comment by ameotoko** [comment]
I tried to debug it under both branches and compare, I hope it's somehow helpful.

In `4.13`, the successfully rendered subpalette is returned from this block of code:

https://github.com/contao/contao/blob/5068fbe9763b3aa95733e71fc038a100261c938b/core-bundle/src/Resources/contao/drivers/DC_Table.php#L1873-L1888

In correspondent block in `5.x`, `$vv` is never "[EOF]" (_for any box_), and `$blnAjax` is never `true`, so that `return` statement is never reached. Thus, the `edit()` method is being run in its full glory, until the completely rendered palette is returned back.

**Comment by fritzmg** [comment]
I can confirm the problem.

**Comment by leofeyer** [comment]
The changes from #4892 seem to cause the issue. 🤔

**Comment by leofeyer** [comment]
https://github.com/contao/contao/blob/77c8886921687ed625bf93562aa7907f1255222c/core-bundle/src/Resources/contao/drivers/DC_Table.php#L3362-L3366

Without the change, `$subpalettes` contains the following:

```
array:2 [▼
  "addImage" => "singleSRC,fullsize,size,floating,overwriteMeta"
  "markdownSource" => "code"
]
```

With the change, `$subpalettes` contains the following:

```
array:2 [▼
  "markdownSource" => "code"
]
```

I have not yet figured out why this is, but this seems to cause the issue.
