### ISSUE TITLE
"Click to edit" is not working properly in 5.x

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#4902]
### Affected version(s)

5.x

### Description

Following up the #4754, it breaks the `click2edit` feature, that has been in Contao [since 3.1](https://contao.org/en/news/contao-3_1_RC1.html) (which is undocumented BTW) in a following way:

- `[Ctrl] + click`: ~~edit the element~~ now edits the element settings
- `[Ctrl] + [Shift] + click`: ~~edit the element settings~~ does not work

It can be fixed by adding missing class in [tl_article.php](https://github.com/contao/contao/blob/94c2febf9e9da4aca45cc39077ee12e229014c9e/core-bundle/src/Resources/contao/dca/tl_article.php):

```diff
'operations' => array
	(
		'edit' => array
		(
			'href'                => 'act=edit',
			'icon'                => 'edit.svg',
			'button_callback'     => array('tl_article', 'editHeader')
		),
		'children' => array
		(
			'href'                => 'table=tl_content',
			'icon'                => 'children.svg',
+++			'attributes'          => 'class="editheader"',
			'button_callback'     => array('tl_article', 'editArticle')
		),
```

but then the functionality will be reversed, so a decision is needed here – either accept and document the reversed functionality, or maybe interchange it in `hover.js` here:

https://github.com/contao/contao/blob/94c2febf9e9da4aca45cc39077ee12e229014c9e/core-bundle/src/Resources/contao/themes/flexible/hover.js#L72-L84

**Comment by aschempp** [comment]
See #4904
