### ISSUE TITLE
the first folder is not public when creating nested folders

### ISSUE THREAD

**Issue by zonky2** [contao/contao#4923]
### Affected version(s)

4.13.5

### Description

* Create nested folder `foo/bar` and set checkbox published - folder `foo` is not published

**Comment by fritzmg** [comment]
That's the intended behaviour. After all you are creating the folder `foo/bar` and thus you are setting the folder `foo/bar` to public.

**Comment by zonky2** [comment]
o.k. - then I guess my expectations were different...
