### ISSUE TITLE
SymlinksCommand missing ContainerAware capability

### ISSUE THREAD

**Issue by Jidoka1902** [contao/contao#493]
**Affected version(s)**
4.4.39
**Description**  
SymlinksCommand misses the capability of ContainerAwareness. 

Either extending the ContainerAwareCommand or implementing the ContainerAwareInterface and using the ContainerAwareTrait (which is the new symfon way) will fix this.
**How to reproduce**  
try to create a new folder within the filsystem backend

**Comment by xchs** [comment]
Duplicate of https://github.com/contao/contao/issues/462

**Comment by xchs** [comment]
Duplicate of https://github.com/contao/contao/issues/462
