### ISSUE TITLE
DC_Table forces a field to appear as a column in `listView`, if the field is first to order by

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#4942]
### Affected version(s)

\>= 4.9

### Description

Is this code block really necessary? Say I want to initially sort my data container by a certain field, but show the value in a custom `list.label.label` callback instead of a separate column. Currently the only way to achieve it is to enable grouping, disable columns and render the whole row by yourself. Seems unnecessarily restrictive.

https://github.com/contao/contao/blob/9f6d6fc3fd3b9f07aec7312002c0e685a9e6f53e/core-bundle/src/Resources/contao/drivers/DC_Table.php#L4846-L4870

**Comment by ameotoko** [comment]
bump

**Comment by leofeyer** [comment]
Do you have an idea how to solve this in a backwards compatible way?

**Comment by ameotoko** [comment]
Not really, because I don't undertand the reason why it's there in the first place.

**Comment by fritzmg** [comment]
> Not really, because I don't undertand the reason why it's there in the first place.

It's there so that you can actually see what values you are sorting by.

**Comment by ameotoko** [comment]
> It's there so that you can actually see what values you are sorting by.

Why can't I decide as a developer, whether I want that or not?

**Comment by ameotoko** [comment]
Say I want to display records from newest to oldest, but the actual values of `id` or `created` fields are not relevant to editors. It's just wasted column space.

~Besides, if it's a timestamp field for example, its `'eval' => ['rgxp' => 'date']` setting is not respected. The column displays raw value.~

So I can't turn it off, ~and I can't control it,~ except if I render the whole label by myself in a callback.

EDIT: I might be wrong about `'rgxp'`; that could be because I already have the `label_callback` which does not handle that extra field that I tested.

**Comment by fritzmg** [comment]
> Why can't I decide as a developer, whether I want that or not?

That seems like a rhetoric question? ;) It's just not implemented. We are open for PRs to improve this (see https://github.com/contao/contao/issues/4942#issuecomment-1255052317)

**Comment by ameotoko** [comment]
Yes, it seems easy to remove, but I might not be aware of implications – why it's there in the first place, can it break anything etc. Hence my initial question;)

> Is this code block really necessary?

**Comment by fritzmg** [comment]
Why it's there has already been explained. Now a way needs to be found to be able to influence this behaviour in a backwards compatible way (could be an additional setting like `doNotAutoShowWhenSorted` - well you get the idea).

**Comment by ameotoko** [comment]
I just realized that I only care about `sorting` field in this context. I'm building a dragndrop-sortable data container, and `sorting` being forced to show is driving me crazy.

Would it still be a BC-break if only `sorting` is excluded from being automatically added?

```diff
- if (!$blnFound)
+ if (!$blnFound && $firstOrderBy !== 'sorting')
  {
    $GLOBALS['TL_DCA'][$this->strTable]['list']['label']['fields'][] = $firstOrderBy;
  }
```

I can't imagine the case where any customer currently uses a configuration such as:

![Image on 2023-11-17 02 03 52 PM](https://github.com/contao/contao/assets/10257912/80c581c7-a977-4e5f-8124-3c273eeed10e)

**Comment by ameotoko** [comment]
If introducing new setting is fine, than we could add something like `showFirstOrderBy` that defaults to `true`:

```diff
// Automatically add the "order by" field as last column if we do not have group headers 
- if ($GLOBALS['TL_DCA'][$this->strTable]['list']['label']['showColumns'])
+ if ($GLOBALS['TL_DCA'][$this->strTable]['list']['label']['showColumns'] && ($GLOBALS['TL_DCA'][$this->strTable]['list']['label']['showFirstOrderBy'] ?? true)) 
  {
  ...
  } 
```
