### ISSUE TITLE
Migration not correctly recognize decimal type

### ISSUE THREAD

**Issue by koertho** [contao/contao#4943]
### Affected version(s)

4.13.5

### Description

As already [discussed in Slack](https://contao.slack.com/archives/CK4J0KNDB/p1656919776413029): The Migration / Install Tool has issues with decimal/numeric type. Changes to the database schema are not correctly recognized, so the migration always show the queries to change the schema. 

Steps to reproduce:
1. Create a database field with numeric type

  ```
  // contao/dca/tl_content.php
  $GLOBALS['TL_DCA']['tl_content']['fields']['foobar'] = [
      'sql' => [
          'type' => 'decimal',
          'precision' => 9,
          'scale' => 6,
          'default' => '0.0',
          'notnull' => true,
      ],
  ];
  ```
  or 
  
  ```
  // contao/dca/tl_content.php
  $GLOBALS['TL_DCA']['tl_content']['fields']['foobar'] = [
      'sql' => "decimal(9,6) NOT NULL default '0.0'"
  ];
  ```

2. Call `contao:migrate` or use the install tool. Follwing query should be executed:

    `ALTER TABLE tl_content ADD foobar NUMERIC(9,6) DEFAULT '0.0' NOT NULL`

3. Every further call `contao:migrate` or the install tool will issue this query:

   `ALTER TABLE tl_content CHANGE foobar foobar NUMERIC(9,6) DEFAULT '0.0' NOT NULL`

---
Credits:
Thanks to @fritzmg for the nice code examples.

**Comment by m-vo** [comment]
We are basically only doing the following:
https://github.com/contao/contao/blob/25e9a50e41d70553c32846cacd527cdd70ade32f/core-bundle/src/Migration/CommandCompiler.php#L35-L37

https://github.com/contao/contao/blob/25e9a50e41d70553c32846cacd527cdd70ade32f/core-bundle/src/Migration/CommandCompiler.php#L60-L65

The issue most likely originates from doctrine's schema diff.  Likely related:  https://github.com/doctrine/dbal/issues/2802

**Comment by fritzmg** [comment]
I can confirm the problem. The issue does not occur in Contao 4.9 (doctrine/dbal 2.x).

**Comment by ausi** [comment]
Can confirm the issue too, with `'default' => '0.000000'` it disappears in my setup.

**Comment by leofeyer** [comment]
Closing this as it seems to be a Doctrine issue rather than a Contao issue.
