### ISSUE TITLE
CE Markdown - Insert Tags

### ISSUE THREAD

**Issue by berecont** [contao/contao#4944]
### Affected version(s)

4.13.5

### Description

Content Element _Markdown_:
Insert Tags will not be displayed as URL in frontend
Markdown: `[mein Text zum Link]({{news_url::4711}})`
Frontend: `meinedomain.tld/{{news_url::4711}}`

**Comment by fritzmg** [comment]
The front end will actually output

```html
<a href="%7B%7Bnews_url%3A%3A4711%7D%7D">mein Text zum Link</a>
```

**Comment by leofeyer** [comment]
@Toflar Can you help here?

**Comment by ausi** [comment]
We could probably try to register our own `League\CommonMark\Environment\EnvironmentBuilderInterface\ExtensionInterface` implementation that replaces insert tags in URLs before the markdown extension handles (and URL-encodes) them.

**Comment by Toflar** [comment]
I'll look into it 😊

**Comment by Toflar** [comment]
https://github.com/contao/contao/pull/5170

I thought it would be a 10 minute fix but it turned out to be a 2 hour fix...
