### ISSUE TITLE
Password policy

### ISSUE THREAD

**Issue by JohnSoliman95** [contao/contao#4946]
### Description

Greetings,

A customer asked us whether we could set up a more strict and safe password policy for backend users. I've searched for such a module, but all I could find was [terminal42/contao-password-validation](https://packagist.org/packages/terminal42/contao-password-validation) which does all we want, but unfortunately I suppose only for frontend users.

It would be nice if it was easy to set up password requirements according to our own wishes:
- min_length
- max_length
- uppercase
- lowercase
- numbers
- other_chars: "+*ç%&/()=?"
- change_days

**Comment by fritzmg** [comment]
> but all I could find was [terminal42/contao-password-validation](https://packagist.org/packages/terminal42/contao-password-validation) which does all we want, but unfortunately I suppose only for frontend users.

No, it also works for the back end: https://github.com/terminal42/contao-password-validation#password-validation

**Comment by JohnSoliman95** [comment]
Thanks for your quick reply. I guess I haven't read the documentation carefully enough.

Nevertheless, do you know if something like this or related to this is planned for future core implementation? 
That would be really neat and a big benefit; even for discussing with customers whether to pick Contao or another CMS. I mean 2FA authentification is nice and all, but having the ability to tweak the password security, maybe even a visual password validator while typing in Backend login and support for captchas (Recaptcha, Hcaptcha or whatever) in backend login form would be a nice visual proof of the security mechanisms that you could quickly show a customer. 

Of course we could just implement such tweaks using be_login template and modules like the one mentioned above, but having this as a core feature would greatly benefit the security concerns of many our customers.

**Comment by aschempp** [comment]
I personally don't think this should be a core feature. The only relevant measurement of security for a password is its length, and configuring the length is already a core feature. See https://xkcd.com/936/.

**Comment by ausi** [comment]
Fully agree with @aschempp 

> maybe even a visual password validator while typing

This is the only other thing from the mentioned list that can acutally improve security I think.
Showing people how strong their password is when registering would be a great feature.
