### ISSUE TITLE
Multidomain news and news details on same alias problems

### ISSUE THREAD

**Issue by cubex-hro** [contao/contao#4956]
### Affected version(s)

4.13.6

### Description

I have a multi-domain installation. Each page has a news area under the alias /news/ the details should also be displayed under the same alias in the frontend like /news/path-to-news-item.html. I created the pages according to the new route priority principle.

Unfortunately, I get an error message when creating the reader page on second rootpage.
![image](https://user-images.githubusercontent.com/46573494/177541082-4a0efeda-a51c-40e4-82b9-495a1a6c2ff4.png)

You can easily reproduce the whole thing if you create 2 root pages with 2 pages each (news, news-details) with the same alias (news) with the difference that the news-details has "element required" activated. Every root-page has its own domainname.
![image](https://user-images.githubusercontent.com/46573494/177541060-d75fce8b-b6c7-4048-a348-499c6a4e68da.png)

I really hope it's a bug and not misuse :)

**Comment by markusmilkereit** [comment]
Thumbs up, getting the same error when trying the new routing logic for the first time now :)

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5221
