### ISSUE TITLE
Eventlist: running events are only shown if option "Shortened view" is active

### ISSUE THREAD

**Issue by arno1979** [contao/contao#496]
**Affected version(s)**
Contao 4.4.39
Conteo 4.7.5

**Description**  
An eventlist module configured to show all upcoming events only shows running events if the seemingly unrelated option "Shortened view" is activated.
Since there is a checkbox "Hide running events" with the description "Do not show running events in the list of upcoming events." one would expect this option to determine if running events are shown or not. But "Hide running events" only works if the "Shortened view" is active.

**How to reproduce**  
Create a new event. Set the start date to the current day, add start time in the past and end time in the future. No further fields need to be filled. Publish the event.
Set the eventlist module configuration to show "All upcoming events", enable the option "Shortened view" and the event will be shown, disable it and the event will disappear from the list view.

**Comment by bennyborn** [comment]
Same as #383?

**Comment by leofeyer** [comment]
@arno1979 Is this the same as #383?

**Comment by arno1979** [comment]
@leofeyer Honestly: I am not sure. I read through #383 and my best guess that the issues are related and maybe by fixing #383 this will be fixed as well.
