### ISSUE TITLE
Dbafs: Incorrect pid when moving file outside Contao

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#4962]
### Affected version(s)

4.13.*, ~~maybe even 4.9~~

### Description

When moving a file outside Contao (directly on the filesystem) the Dbafs sync will correct the path of the file but it'll not change the pid. This leads to a wrong behaviour when having "Downloads"-Elements which are pointed to an entire directory instead of specific files.

**The Setup:**

1. Create the following folder structure

```
files
├── folder-a
├── folder-b
│   └── file.zip
```

2. Sync the DB via backend or `contao-console contao:filesync`
3. Move `file.zip` from `folder-b` to `folder-a` directly on the filesystem (not in Contao backend)
4. Sync again
5. The record for `file.zip` will now have a `pid` which points to `folder-b` instead of `folder-a`

**Screenshot for clarification of the effect:**

![image](https://user-images.githubusercontent.com/226890/177728568-080675ca-d025-46d1-9665-bce0dbbd7925.png)

**Comment by fritzmg** [comment]
I can confirm the issue. I can also confirm that the issue does not occur in Contao 4.9.

**Comment by leofeyer** [comment]
@m-vo /cc

**Comment by m-vo** [comment]
Closing in favor of #5020.
