### ISSUE TITLE
Preview of 401, 403, 404 pages executed in wrong TL_MODE

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#4987]
### Affected version(s)

4.13

### Description

When showing the preview of the `40x` pages in Contao 4.13, an error like this might occur:

```
Exception:
Could not find template "js_foobar"

  at vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\TemplateLoader.php:156
  at Contao\TemplateLoader::getDefaultPath('js_foobar', 'html5')
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\TemplateLoader.php:112)
  at Contao\TemplateLoader::getPath('js_foobar', 'html5')
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php:97)
  at Contao\Controller::getTemplate('js_foobar')
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\TemplateInheritance.php:351)
  at Contao\Template->getTemplatePath('js_foobar', 'html5')
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\TemplateInheritance.php:95)
  at Contao\Template->inherit()
     (vendor\contao\contao\core-bundle\src\Resources\contao\library\Contao\Template.php:295)
  at Contao\Template->parse()
     (vendor\contao\contao\core-bundle\src\Resources\contao\classes\FrontendTemplate.php:43)
  at Contao\FrontendTemplate->parse()
     (vendor\contao\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:692)
  at Contao\PageRegular->createFooterScripts(object(LayoutModel), object(PageModel))
     (vendor\contao\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:256)
  at Contao\PageRegular->prepare(object(PageModel))
     (vendor\contao\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:60)
  at Contao\PageRegular->getResponse(object(PageModel))
     (vendor\contao\contao\core-bundle\src\Resources\contao\pages\PageError401.php:89)
  at Contao\PageError401->getResponse(object(PageModel), true)
     (vendor\contao\contao\core-bundle\src\Resources\contao\controllers\FrontendIndex.php:320)
  at Contao\FrontendIndex->renderPage(object(PageModel))
     (vendor\contao\contao\core-bundle\src\Controller\Page\ErrorPageController.php:46)
  at Contao\CoreBundle\Controller\Page\ErrorPageController->__invoke(object(PageModel))
     (vendor\symfony\http-kernel\HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 2)
     (vendor\symfony\http-kernel\HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 2)
     (vendor\contao\contao\core-bundle\src\EventListener\PreviewUrlConvertListener.php:91)
  at Contao\CoreBundle\EventListener\PreviewUrlConvertListener->forward(object(Request), object(PageModel))
     (vendor\contao\contao\core-bundle\src\EventListener\PreviewUrlConvertListener.php:65)
  at Contao\CoreBundle\EventListener\PreviewUrlConvertListener->__invoke(object(PreviewUrlConvertEvent), 'contao.preview_url_convert', object(TraceableEventDispatcher))
  …
```

### Reproduction

1. Create a file called `templates/foobar/js_foobar.html5`.
2. Edit your theme and set **Templates folder** to `foobar`.
3. Edit your page layout and enable `js_foobar` under **JavaScript templates**.
4. Go to the _Site structure_ and click on the page icon of any of the `40x` pages to show the preview.

### Cause

1. Our `PreviewUrlConvertListener` will attempt to retrieve a page URL for the given page:
  https://github.com/contao/contao/blob/95636f5853da18fba2e2bf74bf510ab5db91e44f/core-bundle/src/EventListener/PreviewUrlConvertListener.php#L62-L66
2. This will fail with an Exception as no URL can be generated for the `40x` pages.
3. In the `catch` block the request is then forwarded as a new sub-request.
4. Using the `ErrorPageController`, the `40x` page would be rendered normally then.
5. _However, since we are in a sub-request of the `BackendPreviewController` now, the `ContaoFramework` has already been initialized with `TL_MODE` being `BE`_.
6. When trying to render the `js_foobar` template which is enabled in our layout, `Controller::getTemplate` will check the `TL_MODE` constant and since it is `BE` and not `FE`, it will not consider the page's `templateGroup`.
7. Thus the template will not found, as it only exists in the template group folder of the theme.

### Possible fix

If `Controller::getTemplate` instead uses the request and scope matcher to determine whether this request is in the front end or not, it would work. However, this change alone will not suffice, as any legacy element or module will still be rendered with `TL_MODE` being `BE`. For example, for legacy front end modules you will see the _back end wildcard representation in the front end preview now_. To fix it completely we will need to get rid of the usage of the `TL_MODE` constant altogether in the core, essentially backporting https://github.com/contao/contao/pull/4741 (apart from not the removal part).

_Note:_ any content elements or front end modules from extensions that still use `TL_MODE` would still be rendered in the wrong scope though.

/cc @ausi

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4988
