### ISSUE TITLE
strId vs. strName in FileTree

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#499]
**Affected version(s)**
Contao 4.4

**Description**  
In the following line in FileTree `$this->strId` is passed into the AJAX post request where it should be `$this->strName`. This leads to problems when having multi dimensional field names like `field[0][image]`.

https://github.com/contao/contao/blob/c1026282f5e53046501b0b07b578ad722fceab80/core-bundle/src/Resources/contao/widgets/FileTree.php#L414

**Comment by leofeyer** [comment]
Fixed in 279f94c74d820b8717a2e7a7672e67786646563e.
