### ISSUE TITLE
Creating/editing FAQ in category with deleted jumpTo page leads to error

### ISSUE THREAD

**Issue by cliffparnitzky** [contao/contao#4990]
### Affected version(s)

4.13.6

### Description

When a FAQ catagory has a `jumpTo` page defined, that is not longer valid (page deleted), creating a new or editing an existing entry in the category leads to an error.

This is an exception when creating the serp preview: [tl_faq.php line 596](https://github.com/contao/contao/blob/4.13/faq-bundle/src/Resources/contao/dca/tl_faq.php#L601)

### How to reproduce:
- create a page
- define the new page as jumpTo for a FAQ category
- delete the new page
- enter the FAQ category and try to create a new entry

**Comment by leofeyer** [comment]
To me throwing the exception is correct. I even think that we should throw the same exception in the calendar and news modules instead of silently ignoring the missing target page. @contao/developers WDYT?

**Comment by cliffparnitzky** [comment]
Maybe we should differentiate between backend and frontend. The Exception in the backend because of a wrong configuration may lead to confusion. If you are the one entering the data you will not understand why the application seems to be crashed because of malconfiguration.

For the frontend, the exception will be fine (in my opinion) ... but in the backend maybe a message would be an idea.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to ignore invalid jumpTo pages in the SERP preview in all bundles.
