### ISSUE TITLE
Quotes are not escaped in JSON-LD schema

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#5003]
### Affected version(s)

4.9.31

### Description

If the page or news title contains quotes, the generated JSON-LD schema is malformed because the quotes are not escaped. In the Google Search Console I get errors, that the page cannot parse.

**Comment by fritzmg** [comment]
I cannot confirm the issue. If I name my page `Page "test"` then the JSON-LD output will be

```json
"contao:title":"Page \"test\""
```

**Comment by theDyingMountain** [comment]
In my case, the error occurs on news titles. Can you reproduce that?

**Comment by fritzmg** [comment]
No, for news it is actually encoded in HTML entities:

```json
"contao:title":"News &#34;Test&#34;"
```

What is the HTML output of `<script type="application/ld+json">` in your case?

**Comment by theDyingMountain** [comment]
The News title is : Kaufmännischer Verwaltungsmitarbeiter "Buchhaltung und Einkauf" (m/w/d)
The HTML output is: `"contao:title":"Kaufm\u00e4nnischer Verwaltungsmitarbeiter "Buchhaltung und Einkauf" (m\/w\/d)"`

**Comment by fritzmg** [comment]
Do you have a DCA adjustment for `tl_news`?

**Comment by theDyingMountain** [comment]
Yes, but not for the title field.

**Comment by fritzmg** [comment]
Are you adding `tl_news` entries directly instead of via the back end may be?

// edit: but even with `eval.decodeEntities => true` I cannot reproduce your issue:

```json
"contao:title":"News \"Test\""
```

**Comment by theDyingMountain** [comment]
No, the entries are created directly in the backend. Okay, there must be a problem with my installation. On another installation with 4.13 it works. Did you test it with version 4.9?

**Comment by fritzmg** [comment]
I tested in 4.9.

**Comment by theDyingMountain** [comment]
I dumped the data in PageRegular.php. The title has encoded quotes before the call of json_encode. Can this be the problem?
before:
`Kaufmännischer Verwaltungsmitarbeiter &#34;Buchhaltung und Einkauf&#34; &#40;m/w/d&#41;`
after json_encode:
`Kaufm\u00e4nnischer Verwaltungsmitarbeiter &#34;Buchhaltung und Einkauf&#34; &#40;m\/w\/d&#41;`

**Comment by fritzmg** [comment]
> after json_encode:
> `Kaufm\u00e4nnischer Verwaltungsmitarbeiter &#34;Buchhaltung und Einkauf&#34; &#40;m\/w\/d&#41;`

But that's contrary to what you have said before:

> The HTML output is: "contao:title":"Kaufm\u00e4nnischer Verwaltungsmitarbeiter "Buchhaltung und Einkauf" (m\/w\/d)"

What is the actual HTML output? Can you share an example URL?

**Comment by theDyingMountain** [comment]
`Kaufm\u00e4nnischer Verwaltungsmitarbeiter &#34;Buchhaltung und Einkauf&#34; &#40;m\/w\/d&#41;` is the output of dump(json_encode($meta));

The HTML output is the same as above. The url is: https://www.intenta.de/de/intenta-gmbh/karriere/karriere-details/kaufmaennischer-verwaltungsmitarbeiter-buchhaltung-und-einkauf-m-w-d.html

**Comment by fritzmg** [comment]
Then I guess you (or an extension) may have a hook where you execute `html_entity_decode` on the whole buffer.

**Comment by fritzmg** [comment]
In any case, I think we should fix that the JSON-LD data (at least the headlines) might contain HTML entities.

**Comment by Toflar** [comment]
The response context is raw by definition. I don't see what needs to be fixed here. /cc @ausi

**Comment by fritzmg** [comment]
> I don't see what needs to be fixed here.

If you enter something like `"Foobar" {{br}}Foobar` into a news title, then the JSON-LD will contain

```json
"contao:title": "&#34;Foobar&#34; <br>Foobar"
```

But I think it should be:

```json
"contao:title": "\"Foobar\" Foobar"
```

i.e. employ a similar strategy as for the `<title>` (plus `StringUtil::decodeEntities`).

**Comment by ausi** [comment]
> Then I guess you (or an extension) may have a hook where you execute `html_entity_decode` on the whole buffer.

Agree, in a regular Contao 4.9 setup the JSON is `"contao:title":"Kaufm\u00e4nnischer Verwaltungsmitarbeiter &#34;Buchhaltung und Einkauf&#34; &#40;m\/w\/d&#41;"` which is valid JSON.

> The response context is raw by definition.

There is no response context in 4.9, that’s why the issue appears only there.

> The question is whether to decode HTML entities for the JSON.

Yes, I think we should do that here: https://github.com/contao/contao/blob/404f9ae7726851aee75e69ca4e8ac8d4acfb6c4f/core-bundle/src/Resources/contao/pages/PageRegular.php#L835

**Comment by fritzmg** [comment]
Should we use just

```php
'contao:title' => StringUtil::decodeEntities($objPage->pageTitle ?: $objPage->title),
```

or should we do

```php
'contao:title' => strip_tags(StringUtil::decodeEntities($this->replaceInsertTags($objPage->pageTitle ?: $objPage->title))),
```

similar to `<title>` in line 218, because otherwise you might end up with an insert tag in the JSON - which will then be replaced before the buffer is sent to the browser and the insert tag might again contain a `"` for instance - or HTML code.

**Comment by ausi** [comment]
I think we should do the second one, but without the `strip_tags`:

```php
'contao:title' => StringUtil::decodeEntities($this->replaceInsertTags($objPage->pageTitle ?: $objPage->title)),
```

**Comment by fritzmg** [comment]
Shouldn't we remove any HTML though, just like with the `<title>` tag?

**Comment by ausi** [comment]
Not after decoding entities I think. But before might be OK like `StringUtil::decodeEntities(strip_tags($this->replaceInsertTags(…`

**Comment by leofeyer** [comment]
In the `Feed` class, we are stripping insert tags instead of replacing them as suggested above:

https://github.com/contao/contao/blob/b5fb550fb3ebba5b50dd5c85cccc2e6341b850a1/core-bundle/src/Resources/contao/library/Contao/Feed.php#L137

I think it would be more consistent if we did the same here, wouldn‘t it?

**Comment by fritzmg** [comment]
If you have a feed title like `{{file::foobar.php}}` then the feed title would be empty (same goes for the page title). I think we should replace them.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to replace the insert tags in both classes.

**Comment by leofeyer** [comment]
While working on this I realized that we do not only strip insert tags in the `Feed` class. We basically do it everywhere, so `PageRegular` would be the only class that behaves differently. Search for `strip_tags(StringUtil::stripInsertTags(` in the code base to validate.

Hence the question is whether we want to replace all `stripInsertTags()` with `replaceInsertTags()` or not?

**Comment by ausi** [comment]
> Search for `strip_tags(StringUtil::stripInsertTags(` in the code base to validate.

I found occurrences that handle feed `<titles>` and `->pageTitle`.

> Hence the question is whether we want to replace all `stripInsertTags()` with `replaceInsertTags()` or not?

I think we want to use `replaceInsertTags()` for all titles.
**UPDATE**: But maybe not in a bugfix release.

**Comment by Toflar** [comment]
I wonder if we should deprecate the `StringUtil::stripInsertTags()` and not use it at all anymore. If you want the insert tags to be replaced, it should be done before you pass it on to any service. If you don't then they should be output raw. Maybe related to @ausi's new insert tag parser...so something for the dev meeting?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to

1. strip the tags in the next bugfix release (so it is consistent everywhere) and
2. change all occurrences to replace insert tags in the next minor version.

**Comment by leofeyer** [comment]
See #5447 for the first part. I am going to move the issue to the `5.1` milestone now as a reminder to replace the `stripInsertTags()` calls with `replaceInsertTags()`.

**Comment by fritzmg** [comment]
@leofeyer should we still change it to `replaceInsertTags` in `5.1`? Or rather wait for `6.0`.

**Comment by leofeyer** [comment]
As far as I am concerned, we can change it in Contao 5. Can you create a pull request?
