### ISSUE TITLE
Long filenames and content element invalid options - search index broken

### ISSUE THREAD

**Issue by baumannsven** [contao/contao#5004]
### Affected version(s)

4.9,4.13

### Description

I have detected the bug in Contao 4.9.x with the content element downloads.

Then i have installed a local demo with Contao 4.13.x.

For test the bug i have used the site media elements.

The first problem i have detected with the fresh installation, was the content element youtube has an invalid option for the element template. So i can not find the site in the search index. After repair this the site find in the search index.

The second problem. For this i am used the file `files/contaodemo/media/content-images/DSC_5403.jpg`. This is used in the gallery of the site. When i rename this file to `files/contaodemo/media/content-images/Lorem_ipsum_dolor_sit_amet_consetetur_sadipscing_elitr_sed_d.jpg` then i found this site in the search index. After i add one character to the filename, then i am not found this site in the search index. The filename can have 255 characters. My test has lower then 255. Why can not find the site in the search?
I have test too, move the file in `files/contaodemo`, after this i have the same problem too.

**Comment by fritzmg** [comment]
Please do not mix different issues. Open a separate issue for the problem you found in the `youtube` content element.

As with regards to the issue in the title of the issue: please post exact reproduction steps.

**Comment by baumannsven** [comment]
@fritzmg 

I have change the title of the issue. I think is right so.

The reproduction steps i have described. There are all informations here!?

**Comment by fritzmg** [comment]
I am sorry, I do not understand the problem or what exactly needs to be done to reproduce it.

**Comment by baumannsven** [comment]
As first you install Contao 4.13 with contao/official-demo.

Then execute php ./vendor/bin/contao-console contao:crawl.

The site media elements can you not find with search module, when you search for `media elements`.

For the first problem:
After i repair in the content element youtube of the site media element (content element template invalid options), then crawl with the command. So you find the site with the search engine.

For the second problem:
Rename the file from `files/contaodemo/media/content-images/DSC_5403.jpg` to `files/contaodemo/media/content-images/Lorem_ipsum_dolor_sit_amet_consetetur_sadipscing_elitr_sed_di.jpg`. Then execute the crawler command. After this you do not find the site media elements with the search module. When i delete one character of the filename and execute the crawler command. So i find the site with the search module.

**Comment by ausi** [comment]
I was able to fix the second problem: #5329

@baumannsven please open a new ticket for the first problem
