### ISSUE TITLE
Inconsistent request handling

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#5006]
### Description

Currently we mix `$requestStack->getCurrentRequest()` and `$requestStack->getMainRequest()` without a clear concept of when to use which. The difference between the two is that `getMainRequest()` returns the **first** request of the stack and `getCurrentRequest()` returns the **last** request.

As already mentioned in https://github.com/contao/contao/pull/4984#issuecomment-1186981655, `$requestStack->getSession()` also uses the **last** request, but we have used the session of the main request so far.

**Comment by aschempp** [comment]
every subrequest (in almost any case) inherits the session from the main request, so I think this is not relevant. But I never really understood when Symfony uses which request. Main request holds the actual browser request, so I would always think that's the "better" one for "global" stuff 🤷

**Comment by ausi** [comment]
As discussed in the Contao Call today this would be our propsal:

1. Prefer to use use `getCurrentRequest()`
2. If this does not work because of technical reasons (like firewall related stuff) use `getMainRequest()` and add a code comment that describes why this is the case.

_(leaving this as up for discussion to rediscuss with all core developers in the next call)_

**Comment by leofeyer** [comment]
I have fixed the obviously wrong calls in #5192. This leaves us with the following classes still using `getMainRequest()`:

* `ContaoContext`
* `ContaoCsrfTokenManager`
* `ContaoFramework`
* `CoreResponseContextFactory`
* `AccessDecisionManager`
* `FrontendPreviewAuthenticator`
* `TokenChecker`

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to adjust #5192 and replace all `getMainRequest()` occurrences with `getCurrentRequest()`, except in the `AccessDecisionManager` and the `FrontendPreviewAuthenticator` because they are firewall-related.

BTW, the `AccessDecisionManager` should be rewritten to check the firewall instead of the scope matcher.

**Comment by leofeyer** [comment]
The PR has been updated.
