### ISSUE TITLE
PageModel::getAbsoluteUrl parameters are automatically URL encoded

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#5007]
### Affected version(s)

5.0

### Description

In our news and events `SitemapListener` we use [`$objPage->getAbsoluteUrl('/%s')`](https://github.com/contao/contao/blob/5.0.0-RC1/news-bundle/src/EventListener/SitemapListener.php#L88) - i.e. we use `%s` as a placeholder for the news alias to be later inserted by `sprintf()`. However, in Contao 5.0, the resulting URL will have an URL encoded representation of the `%` character, resulting in an URL like

```
https://example.local/news/entry/%25s
```
instead of
```
https://example.local/news/entry/%s
```

which means the URL will not properly be generated by the listener and thus you end up with multiple `https://example.local/news/entry/%25s` URLs in your sitemap instead of the real news URL.

For some reason the `router` automatically URL encodes the parameters in Contao 5.0 - but does not do so in Contao 4.13 (where we use the same listener and same principle).

**Comment by aschempp** [comment]
could this be related to cmf-routing 3.0? A solution might be to use a placeholder like `__alias__` and `str_replace` that in the URL.

**Comment by fritzmg** [comment]
> A solution might be to use a placeholder like `__alias__` and `str_replace` that in the URL.

Yes, we should do that in any case I suppose. However, anyone else might expect that the parameters passed to `PageModel::getAbsoluteUrl` will not get automatically url encoded in general? We could mention that in `UPGRADE` though.

**Comment by ausi** [comment]
> For some reason the `router` automatically URL encodes the parameters in Contao 5.0 - but does not do so in Contao 4.13 (where we use the same listener and same principle).

In Contao 4.13 this was handled by `applyLegacyLogic()` https://github.com/contao/contao/blob/daee55bdc2c0c24f6d2c8a3f0c40a7fc36ad2ed8/core-bundle/src/Resources/contao/models/PageModel.php#L1495 but this no longer exists in Contao 5.0
