### ISSUE TITLE
C4.13.6 {{email_url::*}} erzeugt keine codierte E-Mail-Adresse

### ISSUE THREAD

**Issue by Bear30** [contao/contao#5015]
### Affected version(s)

4.13.6

### Description

Hallo,

{{email::*}} macht was es soll, also erzeugt eine codierte Adresse. Bei {{email_url::*}} wird nichts ersetzt

**Comment by bytehead** [comment]
Encoded wird es sicher: 
https://github.com/contao/contao/blob/95636f5853da18fba2e2bf74bf510ab5db91e44f/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L276-L290

`mailto:` fehlt einfach. 
Was ich mich auch immer mal wieder gefragt habe warum - man muss jeweils von Hand noch `&#109;&#97;&#105;&#108;&#116;&#111;&#58;` vor `{{email_url::*}}` setzen...

**Comment by Bear30** [comment]
{{email_url::*}} | Dieses Tag wird nur durch die kodierte E-Mail-Adresse ersetzt.

**Comment by fritzmg** [comment]
I cannot confirm the problem. The output of

```
{{email_url::email@example.com}}
```

is

```html
&#101;&#x6D;&#97;&#x69;&#108;&#x40;&#101;&#x78;&#97;&#x6D;&#112;&#x6C;&#101;&#x2E;&#99;&#x6F;&#109;
```

**Comment by Bear30** [comment]
Das geht nicht

**Comment by bytehead** [comment]
Achtung - Die Entwicklerkonsole der Browser decodiert wieder - du musst den Sourcecode der Seite ansehen.

**Comment by Bear30** [comment]
Stimmt ... grrhhh
