### ISSUE TITLE
Backend DatePicker lacks z-index

### ISSUE THREAD

**Issue by michb** [contao/contao#5019]
### Affected version(s)

5.0 RC

### Description

As the DatePicker is positioned `absolute` there should also be a `z-index`. We added a DatePicker filter to the top filter panel, so it is possible to overlay the alert bell, but the number near this icon has `z-index: 1` and therefore is displayed in front of the DatePicker.

Also we have another widget which has a `z-index: 10` near the DatePicker overlay.

Example screenshot
![unnamed](https://user-images.githubusercontent.com/17873830/180221679-ed09d135-d6f2-4a58-873d-e80a82cc79db.png)

So in my case a `z-index` of `10` would be sufficent, but as this overlay should always be on top it should be a higher than that.

**Comment by aschempp** [comment]
does this also happen in Contao 4.9 / 4.13 ?

**Comment by michb** [comment]
It looks the same in all Contao Versions 4.9, 4.13 and 5.0. 
But now I noticed it changes on the media query `(max-width:991px)`
For width larger `991px` it looks like in the inital post and smaller than `991px` it looks like this
![image](https://user-images.githubusercontent.com/17873830/186423014-d9345403-21d9-4479-bcfa-ee7ded416f43.png)

**Comment by leofeyer** [comment]
@michb Please create the issue again in the https://github.com/contao-components/datepicker repo. I cannot transfer it to another organization manually.
