### ISSUE TITLE
Maximum upload file size for images will be ignored

### ISSUE THREAD

**Issue by kikmedia** [contao/contao#502]
**Affected version(s)**
4.4.40, 4.6.14, 4.7.5

**Description**  
If one sets a maximum size for images in system settings, this setting will be ignored in file manager

**How to reproduce**  
Set the values for uploads to a reasonable amount, i.e. 3.500 x 3.500 pixels and 8 MB. Goto file manager and upload an image with more than 3.500 pixels. The upload will be finished, and afterwards the too-large-image will be at place in files.

IMHO this setting should prevent uploads of larger files in every case, and I think it does in Contao 3.

**Comment by fritzmg** [comment]
Which settings exactly are you referring to?

**Comment by kikmedia** [comment]
I‘m referring to the backend system settings regarding file uploads. Sorry if this wasn‘t clear enough.

**Comment by ausi** [comment]
I was not able to reproduce this issue. I uploaded a 5000 by 5000 pixel large image and it got correctly resized down to 3500.

If you are using GD on your webspace please make sure that the maximum GD image width and height are set high enough to handle your uploaded image.

Possibly related: contao/core#6726

**Comment by fritzmg** [comment]
Plus the feature of preventing large file uploads has been implemented in Contao 4.6 https://github.com/contao/core-bundle/pull/1507

**Comment by leofeyer** [comment]
@kikmedia Were you able to resolve your issue?
