### ISSUE TITLE
Content Element »Unfiltered HTML« - Keine Hilfe-Info über den Assistenten

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#5021]
### Affected version(s)

5.0 RC

### Description

Für das neue CE »Unfiltered HTML« (#4749) erhalte ich im BE beim Aufruf der Hilfe einen »Internal Server Error»:
`Model::findByPk(): Argument #1 ($varValue) must be of type int|string, got null`

**Comment by ausi** [comment]
In my test this issue occurs for all content elements, not only for the “Unfiltered HTML”

**Comment by ausi** [comment]
I’m no longer able to reproduce with the current 5.0.x branch, so I guess this was fixed.

**Comment by fkaminski** [comment]
Can confirm. So could be closed.
