### ISSUE TITLE
Default operations are always added to DC_Table view

### ISSUE THREAD

**Issue by michb** [contao/contao#5024]
### Affected version(s)

5.0

### Description

We created a DCA for showing information gathered in the frontend. This data will be shown as a list with `showColumns`.
As this data should not be altered in any way we used following configuration: 
```php
$GLOBALS['TL_DCA']['tl_xxx'] = [
    'config' => [
        'dataContainer'             => DC_Table::class
    ,   'ptable'                    => ''
    ,   'dynamicPtable'             => true
    ,   'closed'                    => true
    ,   'notCopyable'               => true
    ,   'notCreatable'              => true
    ,   'notDeletable'              => true
    ,   'notEditable'               => true
    ,   'notSortable'               => true
    ...
,   'list' => [
        'sorting' => [
            'mode'                  => 2
        ,   'fields'                => ['tstamp']
        ,   'flag'                  => 1
        ,   'panelLayout'           => 'filter;sort,search,limit'
        ]
    ,   'label' => [
            'fields'                => ['pid', 'ptable', 'type']
        ,   'showColumns'           => true
        ]
    ]
,   'fields' => [
    ...
```
Just for clarification we added all flags to denie any interaction with the records and set no `operations` under `$GLOBALS['TL_DCA']['tl_xxx']['list']`.

So I would expect to have no actions at all which is the case in Contao 4.13 and below.

But in Contao 5.0 we get the four operations `edit`, `copy`, `delete` and `show`.
As far as I understand these operations are added in the `loadDataContainer`-Hook by the `DefaultOperationsListener`. But this Hook will not consider any flags set in the `config` mentioned above. And during the actual button generation in `DataContainer`s `generateButtons` all operations in `$GLOBALS['TL_DCA'][$strTable]['list']['operations']` will be added.

**Comment by aschempp** [comment]
https://github.com/contao/contao/pull/5035 removes the disabled default operations. However, a table always has a `show` operation, since there is no permission/the user _can_ see the record. Is that a problem in your case?

**Comment by michb** [comment]
> #5035 removes the disabled default operations. However, a table always has a `show` operation, since there is no permission/the user _can_ see the record. Is that a problem in your case?

no, the `show` operation can be added
