### ISSUE TITLE
Tooltips outside viewport

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#5027]
### Affected version(s)

5.0.x-dev, 5.0

### Description

The tooltips of icons on the far most right side are shown outside the viewport.

![image](https://user-images.githubusercontent.com/226890/180434806-6d004155-da4f-4a03-9d4d-df372926c353.png)

This worked fine in 4.13 before.

![image](https://user-images.githubusercontent.com/226890/180434940-5533a4eb-f234-488d-a273-a05170eaec5f.png)

**Comment by contaoacademy** [comment]
I can confirm this.
![screen-20220812_yXN2Omzu](https://user-images.githubusercontent.com/23719181/184358302-10918847-02dc-4962-8665-9cabd15bfc10.jpg)

**Comment by ausi** [comment]
This is probably because of the rewrite in #4383. 
As far as I can see, this feature would have to be added to the new implementation as it currently doesn’t check for this.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5156
