### ISSUE TITLE
Custom labels for operations in DCA not respected anymore

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#5029]
### Affected version(s)

\>= 4.13

### Description

It seems that since 4.13 there is a bug regarding the labels for the `global_operations` and `operations` in DCA's. 

We have in various extensions, historically, custom labels for `edit`, `copy`, `delete` etc. but since 4.13 these labels are no longer used but only the "standard labels" from the core. For example, `edit` no longer says "Edit dealer ID 1" but "Edit element ID 1" and `global_operations`, which then have a translation from `$GLOBALS['TL_LANG']` in `attributes`, don't load them anymore.

**Small example**

https://github.com/numero2/contao-storelocator/blob/69d95a2e83e4492fa759807d9ce114ab7ecef978/src/Resources/contao/dca/tl_storelocator_stores.php#L52 

The translation for this operation is missing completely while the default translation gets used in line 63.

[The disussion in Slack](https://contao.slack.com/archives/CK4J0KNDB/p1658493931807159)

**Comment by fritzmg** [comment]
I am unable to reproduce the issue.

**Comment by bennyborn** [comment]
The case seems a bit more complicated. Sometimes it just works but most of the time it does not. Furthermore in Contao 5 we now have a situation where almost all labels are in english even if the profile is set to german. Maybe that's a related problem:

![image](https://user-images.githubusercontent.com/226890/181014369-6f8ea4ea-2cdb-488d-b02b-0ce50e24304f.png)

**Comment by fritzmg** [comment]
Were you able to reproduce this in a clean installation?

**Comment by m-vo** [comment]
> where almost all labels are in english even if the profile is set to german

I have experienced this before (mixed language labels) and it seemed to be opcache related. Try restarting the server and see if this resolves the issue.

**Comment by bytehead** [comment]
> I have experienced this before (mixed language labels) and it seemed to be opcache related. Try restarting the server and see if this resolves the issue.

Yep, can copy that weird behaviour. Hard to reproduce.

**Comment by bennyborn** [comment]
> Were you able to reproduce this in a clean installation?

The problem with the "all english" labels? Nope, but I haven't tried that.

Regarding the initial problem? Also nope because the core only uses the default labels of course. Maybe you wanna give it a try by installing `numero2/contao-storelocator @dev`? As you can see from the DCA there's is nothing unusual and it worked pretty much the same way since Contao 3.5.

> I have experienced this before (mixed language labels) and it seemed to be opcache related. Try restarting the server and see if this resolves the issue.

Okay, I'll try that tomorrow. Nonetheless if multiple people experienced this behaviour there seems to be a problem and "restarting" the server might not be possible on a shared hosting.

**Comment by bytehead** [comment]
> "restarting" the server might not be possible on a shared hosting.

I only saw it on the local Symfony CLI server.

**Comment by fritzmg** [comment]
> Maybe you wanna give it a try by installing `numero2/contao-storelocator @dev`?

I was unable to reproduce the issue there:

<img src="https://user-images.githubusercontent.com/4970961/181054679-172897f2-7a15-4ee4-a65f-c78d377f6528.png" width="360">

**Comment by bennyborn** [comment]
> I was unable to reproduce the issue there:

That's in 4.13 right? As I said sometimes it seems to work there but I haven't had any luck to get it working in 5 at all.
Maybe trying in 5 gives you a hint why it's not working correctly?

![image](https://user-images.githubusercontent.com/226890/181232735-ffef7e61-4b3e-4cb4-b0a1-1a26072c70c5.png)

**Comment by fritzmg** [comment]
I can reproduce it in Contao 5.0, yes. But this is likely a regression caused by the new default operations feature, which is only present in Contao 5.0+.

**Comment by fritzmg** [comment]
Since this is not reproducible in Contao 4.13 (or rather we do not have reproduction steps yet) and the bug in Contao 5.0 is likely completely different I'll mark this as a bug for Contao 5.0.

**Comment by aschempp** [comment]
> I can reproduce it in Contao 5.0, yes. But this is likely a regression caused by the new default operations feature, which is only present in Contao 5.0+.

The _new default operations feature_ only adds operations, it never changes the labels of existing ones. But sure would be interesting to investigate 😊

**Comment by fritzmg** [comment]
> The _new default operations feature_ only adds operations

It also processes their labels - but I haven't investigated yet where the label gets lost.

**Comment by ausi** [comment]
Is this issue still present or was it maybe fixed by #5060 ?

**Comment by fritzmg** [comment]
The issue is unfortunately still present in the current 5.0 branch.

**Comment by aschempp** [comment]
I am unable to reproduce this in the latest 5.0 branch. After installing numero2/contao-storelocator dev-master it works as expected. I would also assume this to have been a problem of #5060 🤔

**Comment by bennyborn** [comment]
> I am unable to reproduce this in the latest 5.0 branch.

Interesting. Just updated my local 5.0.x-dev to 9943c01 and still having the same problem.

![image](https://user-images.githubusercontent.com/226890/184833382-7fe55ecb-2db2-4b2c-8f33-fb008e775174.png)

**Comment by ausi** [comment]
Does it appear with the debug mode as well as without?
Does it make a difference if you clear the cache (`rm -rf var/cache/`)?

**Comment by fritzmg** [comment]
As far as I tested, it happens if `var/cache/<ENV>/contao` is not populated, so either:

* When using `APP_ENV=dev` (debug mode).
* When using `APP_ENV=prod` but with the cache deleted and _no_ `cache:warmup` afterwards.

**Comment by bennyborn** [comment]
It seems like @fritzmg is correct. It only happens if `var/cache/<ENV>/contao` is empty. After a `cache:warmup` it seems to work (for each environment respectively).

**Comment by ausi** [comment]
Should be fixed by #5163

**Comment by bennyborn** [comment]
> Should be fixed by #5163

Yes and no. It surely fixes the labels on the operations like `edit`, `copy` and so on but what about translations in the attributes of `global_operations` like this one? https://github.com/numero2/contao-storelocator/blob/69d95a2e83e4492fa759807d9ce114ab7ecef978/src/Resources/contao/dca/tl_storelocator_stores.php#L52

That's still empty 

![image](https://user-images.githubusercontent.com/226890/184870621-c581579a-f4ba-43c0-817e-d0cefae7a19d.png)

Or is this intended behaviour as long as the cache is not warmed up?

**Comment by ausi** [comment]
> Or is this intended behaviour as long as the cache is not warmed up?

I don’t think so.

I think the problem occurs without the cache because of the following call chain:

1. `Contao\User::loadUserByIdentifier(…)`
2. `Contao\Model::convertToPhpValue(…, …)`
3. `Contao\CoreBundle\EventListener\DoctrineSchemaListener->postGenerateSchema(…)`
4. `Contao\DcaExtractor->createExtract()`
5. `Contao\Controller::loadDataContainer(…)`

This loads all DCAs, and it does so without loading the language files first.

If the cache is built, the `DcaExtractor->createExtract()` never gets called because the data is loaded from the cache.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5418
