### ISSUE TITLE
contao-manager.phar.php must be deleted?

### ISSUE THREAD

**Issue by xcy7e** [contao/contao#503]
**Affected version(s)**
4.4.* LTS
**Description**  
Installation File requires to be deleted as stated in 500-error message overlay
**How to reproduce**  
Download contao-manager.phar (4.4.*LTS) and rename to contao-manager.phar.php;
Access it (only possible in website root directory, which requires one to empty the whole webserver-root on a server without a domain!!) and do all the checks.
If everything is set OK, an overlay pops up asking to delete everything in the root-dir of the server INCLUDING the contao-manager.phar.php. Makes no sense, and once removed nothing happens and you can obviously not refresh the page, if so -> 404 contao-manager.phar.php not found. Is it possible to install contao for a webdeveloper on his vps without a domain or is contao only designed for managed webhosting these days?

**Comment by xcy7e** [comment]
Does not occur when putting everything in /web and making /web the root directory.

It seems however this is not the best solution for anyone without domains, therefor the ability to make subdomains.

**Comment by fritzmg** [comment]
The instructions clearly say to put the phar in the web sub directory of your (future) Contao 4 installation and set the document root to that directory.

This requirement is part of Contao itself, not from the Contao Manager.
