### ISSUE TITLE
Image getPath used for backend icons should return absolute urls

### ISSUE THREAD

**Issue by michb** [contao/contao#5030]
### Affected version(s)

5.0

### Description

Problem is the following markup for the toggle icon:
```php
<img 
    src="/system/themes/flexible/icons/visible.svg" 
    width="16" 
    height="16" 
    alt="Element ID 1 veröffentlichen/unveröffentlichen" 
    data-icon="system/themes/flexible/icons/visible.svg" 
    data-icon-disabled="system/themes/flexible/icons/invisible.svg" 
    data-state="1"
>
```
Specifically the `data-icon` and `data-icon-disabled` attributes are not absolute so after one toggles the icon it changes to 
```php
<img 
    src="system/themes/flexible/icons/visible.svg"
    ...
>
```
which leads to a problem now that the `base`-tag is missing. 
If we use a custom backend route or custom backend controller generating an url like `://domain/contao/test` for the backend.

Generally we should now always use absolute urls.

So the cause generating this path is here:
https://github.com/contao/contao/blob/87b3a7cf676461608c08146678c046bd5debf4d8/core-bundle/contao/library/Contao/Image.php#L24

**Comment by aschempp** [comment]
Looks like our simple HTML parsing does not work in all cases 🙃

**Comment by ausi** [comment]
@michb can you please check if the pull request #5139 fixes your issue?

> Looks like our simple HTML parsing does not work in all cases 🙃

@aschempp Can you elaborate on what this means? HTML parsing where?

**Comment by michb** [comment]
> @michb can you please check if the pull request #5139 fixes your issue?

yes, thank you this will fix my issue.
