### ISSUE TITLE
Model::convertToPhpValue casts null values to type as well

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#5034]
### Affected version(s)

5.0

### Description

In 5.0 we introduced that the model's values are automatically cast from string (or also integer under PHP 8.1+ PDO) to their actual PHP type according to the column type.

However, this also applies to `null` values in the database. For example if you have a field with a definition like `smallint unsigned NULL` and a record's value is `null` in the database, then the value of the field will actually be `0` when loaded via the Model. Nullable database fields should still be able to hold `null` values in the Model (as is noted in the doc block anyway).

This applies to any non-string value in the database, specifically integers, floats, and booleans. String values will stay `null` (if nullable) as `Model::convertToPhpValue` does not convert those at all.

@ausi I think we probably also need to store whether a column field is nullable or not? And then don't cast those columns, if the value is null.

**Comment by ausi** [comment]
> I think we probably also need to store whether a column field is nullable or not? And then don't cast those columns, if the value is null.

Yes, I think so.
