### ISSUE TITLE
add "user group restriction" at page type "logout"

### ISSUE THREAD

**Issue by zonky2** [contao/contao#504]
add "user group restriction" at page type "logout" to show this page only if you logged in

**Comment by leofeyer** [comment]
What exactly do you mean?

**Comment by zonky2** [comment]
sorry - too short...
I miss a checkbox "only for guests" - so that the page is only displayed in the navigation when you are logged in

**Comment by leofeyer** [comment]
But "only for guests" means "show it when you are **not** logged in".

**Comment by zonky2** [comment]
JESS :D

Edit: NO!

**Comment by leofeyer** [comment]
Sorry, but that does not make any sense at all. Why would you want to hide the login page from logged in users and show it to guests only? Guests are not logged in, so they cannot log out, either.

**Comment by zonky2** [comment]
sorry - too hot this day...

I meant, of course, "only visible when I'm logged in."

**Comment by leofeyer** [comment]
Just protect the page like you do with any other "members only" page.

<img width="511" alt="" src="https://user-images.githubusercontent.com/1192057/59020131-abedf680-8849-11e9-9130-373ff239653f.png">

**Comment by zonky2** [comment]
sorry - anscheinend nicht meine "hellste" Woche ;-)
