### ISSUE TITLE
Theme-Details -> Templates-Ordner: no underscore allowed in directory name

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5044]
### Affected version(s)

5.0.0-RC1

### Description

Steps to reproduce:

1. create a new template directory in LAYOUT -> Templates with the name "my templates" (without quotation marks of course)
    -> the space character is automatically changed to an underscore character ("my_templates") and the new template directory is saved.
2. create a new theme in LAYOUT -> Themes
3. select the above newly created templates directory "my_templates" in "Templates-Ordner"
4. save the change in the theme details
-> error "Der Template-Pfad "templates/my_templates" darf folgende Zeichen nicht enthalten: _".

I think it should
a) be possible to select a template path which contains an underscore character or
b) not be possible to create a templates directory which contains an underscore character.

**Comment by m-vo** [comment]
> be possible to select a template path which contains an underscore character or

No, this was deliberately removed in 4.13 and already triggers a deprecation warning. See #3414

**Comment by m-vo** [comment]
> I think it should […] not be possible to create a templates directory which contains an underscore character.

You must be able to create directories with an underscore. For instance, if you want to overwrite the new content element templates (`content_element/foo.html.twig`). And this works fine.

We only disallow underscores in **theme** paths, as they can be arbitrarily nested (besides other niche properties). Without this restriction we would not be able to guarantee unique fully qualified template names.

Closing as this is a known limitation.
