### ISSUE TITLE
page layout -> modifications of included modules not working

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5046]
### Affected version(s)

5.0.0-RC1

### Description

Trying to duplicate or delete a row or enable/disable a module in the section "Included modules" in LAYOUT -> Themes -> Page layouts of an already existing page layout with the corresponding icons (sometimes) does not work.

The behaviour is not consistent which makes it hard to give an exact reproduction.
Tested on all major browsers (Chrome, Edge, Firefox) in their current version.

No errors in the browser console, error.log on server, logfile in /var/logs and debug mode.

**Comment by jochi44** [comment]
Interesting - as mentioned in https://github.com/contao/contao/issues/5043#issuecomment-1195129386 the behaviour is only on Chrome and Edge browser. In Firefox the modifications of included modules work.

**Comment by fritzmg** [comment]
I could not reproduce so far.

> (sometimes) does not work.

So, do you mean you click on the button and nothing happens at all?

**Comment by fritzmg** [comment]
I was actually able to reproduce this in Chrome now.

**Comment by fritzmg** [comment]
Likely the same problem as in #4844 - since the module wizard's implementation is basically the same now. I will provide the same fix as in #4939.

**Comment by aschempp** [comment]
see #5048
