### ISSUE TITLE
page layout -> rearranging included modules is not saved

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5047]
### Affected version(s)

5.0.0-RC1

### Description

Saving the page layout after rearranging included modules with the respective "move the item via drag and drop" icon does not work on an already existing page layout - the changes are not taken into account after saving.

No errors in the browser console, error.log on server, logfile in /var/logs and debug mode.
Tested in all major browsers (Chrome, Edge, Firefox) in their current version.

**Comment by jochi44** [comment]
Interesting - as mentioned in https://github.com/contao/contao/issues/5043#issuecomment-1195129386 the behaviour is only on Chrome and Edge browser. In Firefox rearranging included modules works.

**Comment by fritzmg** [comment]
This I cannot reproduce.

**Comment by m-vo** [comment]
For me rearranging modules with the drag handle only works after clicking the first one. Saving works, though. (Chrome on Linux)

But this might also have to be related to the sporadic errors I'm getting described in #4844.

**Comment by leofeyer** [comment]
@aschempp Could this be an error in the new `modulewizard.js` file?

**Comment by aschempp** [comment]
Probably since this was changed. But the Sortable script is still the same ... 🤷‍♂️

**Comment by leofeyer** [comment]
@jochi44 Does the problem still occur in Contao 5.0.1?

**Comment by fritzmg** [comment]
Likely also fixed by https://github.com/contao/contao/pull/5048 - or rather this issue is a functional duplicate of #5046
