### ISSUE TITLE
PurgePreviewLinksCron deletes not expired preview links

### ISSUE THREAD

**Issue by OMOSde** [contao/contao#5049]
### Affected version(s)

4.13

### Description

Preview links was removed also if they are not expired.

It seems there is a logic error in https://github.com/contao/contao/blob/4.13/core-bundle/src/Cron/PurgePreviewLinksCron.php#L38

use `DATE_SUB` instead of `DATE_ADD`?

**Comment by aschempp** [comment]
it intentionally deletes preview links that are older than 31 days, since anything older than 30 days is not possible. What's wrong with this in your opinion?

**Comment by fritzmg** [comment]
@aschempp the SQL query currently deletes every preview link that was _created_ at least 31 days in the _future_.

I think the intention was to write it this way:

```diff
-           'DELETE FROM tl_preview_link WHERE createdAt<=UNIX_TIMESTAMP(DATE_ADD(NOW(), INTERVAL 31 DAY))'
+           'DELETE FROM tl_preview_link WHERE expiresAt<=UNIX_TIMESTAMP(DATE_ADD(NOW(), INTERVAL 31 DAY))'
```

**Comment by fritzmg** [comment]
### Reproduction:

1. Open the preview for a page.
2. Click on _Share URL_.
3. Save the created preview link.
4. Execute `TRUNCATE tl_cron_job`.
5. Execute `vendor/bin/contao-console cron:run`.

The preview link will be deleted, even though it has not expired yet.

**Comment by ausi** [comment]
> use `DATE_SUB` instead of `DATE_ADD`?

I think this would be the correct fix, yes.

```diff
-           'DELETE FROM tl_preview_link WHERE createdAt<=UNIX_TIMESTAMP(DATE_ADD(NOW(), INTERVAL 31 DAY))'
+           'DELETE FROM tl_preview_link WHERE createdAt<=UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 31 DAY))'
```

> I think the intention was to write it this way:

I don’t think so as the code comment explicitly states to not use the expiration on purpose: https://github.com/contao/contao/blob/4.13/core-bundle/src/Cron/PurgePreviewLinksCron.php#L20

**Comment by fritzmg** [comment]
> I don’t think so as the code comment explicitly states to not use the expiration on purpose: https://github.com/contao/contao/blob/4.13/core-bundle/src/Cron/PurgePreviewLinksCron.php#L20

That comment, as far as I interpret it, only clarifies the fact why we are using `INTERVAL 31 DAY` instead of `INTERVAL 30 DAY`.

**Comment by aschempp** [comment]
The fix from @ausi looks correct to me. It sure must use createdAt and not expiresAt

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5099
