### ISSUE TITLE
asterisk is missing at confirming password

### ISSUE THREAD

**Issue by zonky2** [contao/contao#505]
**Affected version(s)**

C 4.4

**Description**  

when entering the new password form (password forgotten), the asterisk is missing at confirming input

![2192113993](https://user-images.githubusercontent.com/1192057/58765680-ac4e6f00-8575-11e9-8291-baa4d8d03100.png)

**Comment by leofeyer** [comment]
Are you sure? Because the code is in the template:

https://github.com/contao/contao/blob/c1026282f5e53046501b0b07b578ad722fceab80/core-bundle/src/Resources/contao/templates/forms/form_password.html5#L27

**Comment by zonky2** [comment]
hmm... I`ll check this

**Comment by zonky2** [comment]
sorry - Bug at contao bootstrap
