### ISSUE TITLE
symfony/maker-bundle after 1.44.0 breaks make:contao:content-element

### ISSUE THREAD

**Issue by leonexcc** [contao/contao#5051]
### Affected version(s)

4.13.6

### Description

If we run the make:contao:content-element command with symfony/maker-bundle after 1.44.0 we get the following error since the PhpCompat changed in version 1.44.0 completely (they removed support for PHP 7.4)

```
 [Symfony\Component\ErrorHandler\Error\UndefinedMethodError]
  Attempted to call an undefined method named "canUseAttributes" of class "Symfony\Bundle\MakerBundle\Util\PhpCompat
  Util".
```

If we use symfony/maker-bundle 1.43.0 it still works.

**Comment by aschempp** [comment]
I have reported the problem to https://github.com/symfony/maker-bundle/issues/1164

**Comment by aschempp** [comment]
`PhpCompatUtil` is marked `@internal` so we should never have used this. Clearly a bug in our bundle, @sheeep would you be open to a fix?

**Comment by leofeyer** [comment]
I know the class is marked as `@internal`, but we still need to use it. 🤷‍♂️
