### ISSUE TITLE
content element "image" -> image not shown when "image size" is not set

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5055]
### Affected version(s)

5.0.0-RC1

### Description

Steps to reproduce:

1. create new folder "img" in CONTENT -> Files -> "New folder" and set the "Public"-checkbox
2. upload a png-image (test.png) to this new folder with "Upload files"
3. create a new content element of element type "Image"
4. select the "Source file" which was uploaded in step 2
5. leave option "Image size" blank

In Contao 4.13.6 the image is shown, in Contao 5.0.0-RC1 the image is not shown.
The browser console shows this: `GET https://contao5.xyz.tld/files/img/test.png 404`

If the "Image size" is set (with eg "Crop (important part) | 150 | 150") the image is shown in the frontend.

**Comment by fritzmg** [comment]
I cannot reproduce the issue. It looks like in your case the symlink for your `img` folder was not created under `public/files/`. Can you confirm that?

**Comment by m-vo** [comment]
Cannot reproduce this either. 

But if directly accessing the public URL of the image does not work, the issue does not have anything to do with the image content element. It just shows in those cases where the original resource is used instead of a resized asset.

**Comment by jochi44** [comment]
> I cannot reproduce the issue. It looks like in your case the symlink for your `img` folder was not created under `public/files/`. Can you confirm that?

Unfortunately I can't confirm this.
The symlinks are there and point to ../../files/img, the image-file itself is also present.
The directory "img" is public.

```
web5@s1:/var/www/web/contao5/public/files$ ls -ltr
total 0
lrwxrwxrwx 1 web5 client1 15 Jul 26 22:33 img -> ../../files/img
lrwxrwxrwx 1 web5 client1 19 Jul 26 22:33 favicon -> ../../files/favicon
lrwxrwxrwx 1 web5 client1 15 Jul 26 22:33 css -> ../../files/css
web5@s1:/var/www/web/contao5/public/files$ ls -ltra ../../files/img
total 20
-rw-r--r-- 1 web5 client1    0 Jul 26 17:13 .public
drwxr-xr-x 5 web5 client1 4096 Jul 26 22:32 ..
-rw-r--r-- 1 web5 client1 9882 Jul 26 22:47 test.png
drwxr-xr-x 2 web5 client1 4096 Jul 26 22:49 .
web5@s1:/var/www/web/contao5/public/files$
```

**Comment by m-vo** [comment]
If the symlinks are there and you still cannot access the file in the browser, the issue is likely your web server not serving the files.

**Comment by jochi44** [comment]
> If the symlinks are there and you still cannot access the file in the browser, the issue is likely your web server not serving the files.

That's an interesting point.
I'm running contao 5.0.0-RC1 on an nginx-environment (hoster=timmehosting).
They are providing "out of the box"-nginx-directives for certain products among others also for Contao (the latest one is "Contao ab 4.8" which I chose for the contao5-test-installation).
A nginx-directive is the equivalent to a .htaccess-file.

Maybe something changed in contao5 which breaks e.g. the direct access of img-files.
I could provide the respective nginx-directive if someone wants to have a look into it.
I'm pointing @leofeyer here as probably he has experience with nginx-directives.

What still makes me wonder is that the image itself is displayed in the frontend (see screenshot).
Also content elements of type "download" or "downloads" are correctly handled and can be downloaded in the browser.

Shouldn't nothing be displayed at all if the server doesn't serve images?

![screenshot_issue_5055](https://user-images.githubusercontent.com/60215157/181247686-457ef465-529a-4ee1-ad54-9d19dec8c744.jpg)

**Comment by fritzmg** [comment]
> What still makes me wonder is that the image itself is displayed in the frontend (see screenshot).

The screenshots show the thumbnail, not the original image. What is the server response is you access `/files/img/contao_logo.png` directly?

**Comment by jochi44** [comment]
> What is the server response is you access `/files/img/contao_logo.png` directly?

It's 404 - Not found.

![screenshot_issue_5055_2](https://user-images.githubusercontent.com/60215157/181256952-8ab668b4-2a64-4430-a775-9ac1831f26bb.jpg)

**Comment by fritzmg** [comment]
This indicates that nginx was not able to find the resource and thus forwarded the request to PHP. In any case, this would be a server configuration issue and not a Contao issue. You can seek support on the Contao community forum or the Contao Slack for things like that.

**Comment by jochi44** [comment]
Note to myself:
It's NOT server related.
Updating all packages in the contao manager of the 5.0.0-RC1 installation makes the images available for direct access.
Same as setting a directory to "public" or not (this change is also taken into effect when running the package update; a rebuilding of the prod cache is not sufficient).
