### ISSUE TITLE
content element "image" -> option "Full-size view/new window" not working

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5056]
### Affected version(s)

5.0.0-RC1

### Description

Possibly related to issue #5055.

Steps to reproduce:

1. create new content element of element type "Image"
2. set "Image size" to "Crop (important part) | 150 | 150"
3. check the box "Full-size view/new window"
4. save content element
5. click on image in frontend

Error message:
```
Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

**Comment by fritzmg** [comment]
I cannot confirm the issue. It looks like the image you chose is in a folder that is not set to _public_ (or the symlink for the folder of the image was not created, see also https://github.com/contao/contao/issues/5055).

**Comment by jochi44** [comment]
Closing this issue as it is working now in my environment.
Must have been server related.

**Comment by jochi44** [comment]
Note to myself:
It's NOT server related.
Updating all packages in the contao manager of the 5.0.0-RC1 installation makes the images available for direct access.
Same as setting a directory to "public" or not (this change is also taken into effect when running the package update; a rebuilding of the prod cache is not sufficient).

**Comment by fritzmg** [comment]
Then likely the issue was that the symlinks were not created in your case. If you run `composer install` you'll see which symlinks are created in the console output.

**Comment by jochi44** [comment]
Thank you @fritzmg for the hint.
Don't `contao-console contao:migrate` and the backend function "SYSTEM -> Systemwartung -> Symlinks neu erstellen" create the symlinks as well? Or did I initially install Contao 5.0.0-RC1 wrong by installing it in the /web directory (should it be directory "public" I read somewhere)?
