### ISSUE TITLE
new version of leafo/scssphp

### ISSUE THREAD

**Issue by arboc** [contao/contao#506]
**Affected version(s)**  
all 4.4 and above

**Description**   
there is a new version for leafo/scssphp v0.8.2 which fixes some major issues...
could you please update the requirements

**Comment by xchs** [comment]
Should be fixed with https://github.com/contao/contao/pull/508

**Comment by leofeyer** [comment]
Fixed in 20aac94744211750a7418e6fa78d92acaaa1934d.
