### ISSUE TITLE
TinyMCE prevents `accesskey` shortcuts

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#5067]
### Affected version(s)

4.x

### Description

Since long time, ["accesskey" shortcuts](https://docs.contao.org/manual/en/administration-area/back-end-keyboard-shortcuts/#keyboard-shortcuts-in-edit-mode) do not work when invoked while TinyMCE instance is in focus, probably because TinyMCE does not let them bubble.

It's quite easy to fix by adding custom shortcuts to TinyMCE, but maybe it should be considered a bug in TinyMCE? I posted an issue there (see https://github.com/tinymce/tinymce/issues/8026), but also posting here so it's not forgotten.

I can also provide a PR if you decide to fix it in the meantime.

**Comment by aschempp** [comment]
That's something that always annoyed me but I saw as a known limitation. Fixing it would be great imho. Do you think we can fix the bubbling or just catch our known access keys?

**Comment by leofeyer** [comment]
See #5266 for a fix in Contao 5.0. Needs to be backported once merged.
