### ISSUE TITLE
Punycode in backend meta title

### ISSUE THREAD

**Issue by Funbug** [contao/contao#507]
**Affected version(s)**
Contao 4.7.6

**Description**  
Die Meta-Title im Backend zeigen ja nun die Domain an. Es wäre schön, wenn hier bei Umlaut-Domains nicht der Punycode angezeigt werden würde, also "köstlichfein.de" stat "xn--kstlichfein-rfb.de".

**How to reproduce**  
Backend unter einer Umlaut-Domain aufrufen.

**Comment by leofeyer** [comment]
Betrifft das nur Contao 4.7 und nicht auch Contao 4.4?

**Comment by leofeyer** [comment]
Behoben in c7e27265d346f6003af1324a00becd6da9528750.

**Comment by minstyle** [comment]
@leofeyer 

In Contao 4.9.5 ist der Bug wieder zu sehen.

Anstelle der Umlaut-Domain wird mir der Punycode (Beispiel: xn--prfner-cua.de) als Meta Title angezeigt.

**Comment by ausi** [comment]
Ich konnte den Fehler nicht reproduzieren. Passiert das auf allen Seiten im Backend?

**Comment by minstyle** [comment]
> Ich konnte den Fehler nicht reproduzieren. Passiert das auf allen Seiten im Backend?

Vielen Dank für deine Rückmeldung.

Ja, das passiert auf allen Seiten im Contao-Backend. Genauer gesagt handelt es sich bei meinem Darstellungsfehler um eine Subdomain (Beispiel: demo.xn--prfner-cua.de). Könnte es vielleicht daran liegen?

**Comment by ausi** [comment]
Ja, daran liegt es. Mit einer Subdomain kann ich das Problem reproduzieren. An dieser Stelle https://github.com/contao/contao/blob/79540dc4b96246e575355f03ec03f3c28d8c091b/core-bundle/src/Resources/contao/classes/Backend.php#L1152 müsste der check angepasst werden.

**Comment by minstyle** [comment]
Vielen Dank für deinen Support.

Ich hoffe der Bug wird mit der nächsten Contao-Version behoben sein.

Ich kann das Issue hier nicht wieder öffnen. Kann das dann nur @leofeyer ?

**Comment by ausi** [comment]
Bitte erstell ein neues Issue mit einem verweis auf dieses Ticket. _(im Optimalfall in Englisch)_
