### ISSUE TITLE
Internal redirects to documents, news, etc.

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#5074]
### Description

Internal redirects in the page structure should also be able to point to documents, news, etc.

So far only pages can be specified .

<img width="921" alt="2" src="https://user-images.githubusercontent.com/1622733/182527819-1e0e75c1-0103-4989-a3a1-30a22ef4f31f.png">
<img width="1048" alt="1" src="https://user-images.githubusercontent.com/1622733/182527827-15c1b586-5b2d-40a9-849c-db55eeb1e9a6.png">

**Comment by aschempp** [comment]
Use external redirects for this, since the picker can only pick from one table.
