### ISSUE TITLE
content element "YouTube" -> video autoplaying in backend

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5078]
### Affected version(s)

5.0.0-RC1

### Description

Steps to reproduce:
1. create new content element with element type "YouTube"
2. fill in Source -> "YouTube ID"
3. select all "Player options"
4. save content element

result: the YouTube-video is autoplayed in the contao backend.
should: the YouTube-video should not autoplay in the contao backend even if the checkbox "Autoplay" is checked (unnecessary data consumption, disturbing audio)

**Comment by fritzmg** [comment]
@jochi44 are you sure this only affects Contao 5.0?

**Comment by jochi44** [comment]
> @jochi44 are you sure this only affects Contao 5.0?

Does not happen in Contao 4.13.6, I have no 4.9 installation ready for testing.

**Comment by m-vo** [comment]
This can probably be fixed in 5.0 by adjusting the `content_element/youtube.html.twig` template and passing `as_editor_view` as the 3rd argument (condition) when setting `allow` in the `iframe_attrs`.

**Comment by ausi** [comment]
I’d even skip the `<iframe>` completely for `as_editor_view`.

**Comment by fritzmg** [comment]
Yes, the editor view should be the same as in <5.0 (i.e. just showing the linked YouTube URL).

**Comment by bytehead** [comment]
I cannot reproduce the autoplay behaviour in Firefox 102:

<img width="1774" alt="Bildschirmfoto 2022-08-04 um 07 51 03" src="https://user-images.githubusercontent.com/754921/182772762-1666b492-ad9e-41f5-8da0-6a82673a115b.png">

@jochi44 Which browser are you using?

Edit: Can reproduce this in Chrome 103.

**Comment by bytehead** [comment]
Will be fixed by #5088.
