### ISSUE TITLE
Use of slash in new css class names for content elements

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5082]
### Affected version(s)

5.0.0-RC1

### Description

The divs for "content elements" get new class names in Contao 5 including a slash as separator (eg. content_element/gallery).
Although a slash in css class names is allowed according to the wc3 css specification, I'm not shure if another character would be a better choice.

Reason:
When defining css rules for elements including slashes in a class name, the slash must be escaped.
I'm not shure, how many people even know this.

```
.content_element\/gallery ul {
    list-style: none;
}
```

What do you think?

**Comment by ausi** [comment]
What would you prefer?

- `.content_element-gallery`
- `.content_element--gallery`
- `.content_element_gallery`
- `.content_element__gallery`

**Comment by m-vo** [comment]
I think I'm still in favor of the slash. Because then it 1:1 mirrors the template & type name. 🤔

**Comment by jochi44** [comment]
@m-vo has definitely a point here.
I don't know, maybe it's not important at all and not worth the work.
I would vote for `.content_element--gallery`.

I also noticed that some content elements don't follow the new class name naming convention (eg. ce_text, ce_player, ce_template, ce_form, ce_teaser, ce_comments,...).
Should I open a new bug here or is this intended?

**Comment by m-vo** [comment]
For a few special content elements (includes, wrapper elements) there is no new fragments based one yet and therefore also no new template. (Mind that there are 2 PRs still waiting for their merge.) The text content element as well as the template one should already be there, though.

**Comment by leofeyer** [comment]
I don‘t like the slash, either. I have never seen it being used in CSS classes before.

> I would vote for `.content_element--gallery`.

Me too.

**Comment by contaoacademy** [comment]
+1 for: `.content_element--gallery`.

**Comment by aschempp** [comment]
I dislike the slash as well. However, both `--` and `__` _kinda_ follow BEM, but I would argue it would use it incorrectly. **IF** we want to follow BEM, it should probably be a `content_element__gallery`. 

But following our other existing classes, we use `widget-text`, `widget-submit` etc. for form elements, how about `content-gallery` (= `content-` suffixed by `type`)? It would also make it "easier" to use BEM in the templates.

```html
<div class="content-gallery">
    <h2 class="content-gallery__headline">foobar</h2>

    <ul class="content-gallery__list">
        <!-- ...you get the point. Through template customization only! -->
    </ul>
</div>
```

In the above example, using `content-element--gallery` would result in ugly stuff like `content-element--gallery__list` etc.

**Comment by fritzmg** [comment]
> In the above example, using content-element--gallery would result in ugly stuff like content-element--gallery__list etc.

BEM can always get ugly, that's just how BEM works 😁. However, personally I'd probably also prefer your approach I think (`.content-gallery`, `.content-gallery__headline`, etc.).

**Comment by ausi** [comment]
I also think it might make sense to base the CSS class on the `type` instead of the template name, e.g. replacing the following: https://github.com/contao/contao/blob/636ff279a3fbe73dfeeff844a3dd2bb5ca5f07ee/core-bundle/contao/templates/_new/content_element/_base.html.twig#L12 with something like:
```twig
 .addClass([element_css_classes, "content-#{type}"]) 
```

See #5117
