### ISSUE TITLE
error when adding a reply to a comment in the backend

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5085]
### Affected version(s)

5.0.0-RC1

### Description

Follow up to #5084.

Steps to reproduce:
1. Edit an existing comment in CONTENT -> Comments
2. In the "Reply"-section check the box "Add a reply", choose an "Author", fill in a "Reply" and Save the comment.

-> The error.log on the server shows this message:

`2022/08/03 20:20:38 [error] 1496#1496: *700146 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined property: stdClass::$notifyReply in /var/www/web/contao5/var/cache/prod/contao/dca/tl_comments.php on line 86PHP message: PHP Warning:  Undefined global variable $TL_ADMIN_EMAIL in /var/www/web/contao5/var/cache/prod/contao/dca/tl_comments.php on line 95PHP message: PHP Warning:  Undefined global variable $TL_ADMIN_NAME in /var/www/web/contao5/var/cache/prod/contao/dca/tl_comments.php on line 96" while reading response header from upstream, client: 84.115.224.14, server: contao5.xyz.tld, request: "POST /contao?do=comments&act=edit&id=5&rt=9130d8c24d0505ed0ed1f6.1dincqHnDdHqksYdGH3qa-LLPjH78dvjw7uL-hjC_LE.kZ3FM-S0e6id4ap7QAfTI7uqX0evpu_SqfHlu3SIqYiBn8hF6KN6vbnotQ&ref=U6wF3NtM HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php5-fpm/web57.sock:", host: "contao5.xyz.tld", referrer: "https://contao5.xyz.tld/"`

**Comment by ausi** [comment]
@jochi44 please verify if #5145 fixes your issue.

**Comment by jochi44** [comment]
> @jochi44 please verify if #5145 fixes your issue.

The issue seems to be fixed in Contao 5.x-dev although your fix was provided for 4.9.
