### ISSUE TITLE
Tooltips always show same ID when hovering over icons (edit, duplicate,...)

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5087]
### Affected version(s)

5.0.0-RC1

### Description

Hovering on the icons in CONTENT -> Pages on the right side shows the same ID in the tooltip "Edit page ID X" on every different line (see screencapture).

![screencapture_01](https://user-images.githubusercontent.com/60215157/182695949-be01cc54-4c37-4b47-94a1-566205d46943.gif)

This bug occurs in other "sections" too:
CONTENT -> Articles
CONTENT -> Files
CONTENT -> Comments
ACCOUNT MANAGER -> Users
(no more test data)

**Comment by aschempp** [comment]
will be fixed by https://github.com/contao/contao/pull/5060
