### ISSUE TITLE
Vorschau-Links: Benutzerdefinierter Gültigkeitszeitraum

### ISSUE THREAD

**Issue by minstyle** [contao/contao#5089]
### Description

Seit Contao 4.13 steht die "Vorschau-Links"-Funktion zur Verfügung:

https://docs.contao.org/manual/de/system/preview-link/

Wenn man diese Funktion nutzt, dann stehen aktuell in Contao 4.13.6 nur die drei Zeiträume `1 Tag`, `7 Tage` und `30 Tage` als Auswahl zur Verfügung, um festzulegen, wie lange der Vorschau-Link gültig sein soll.

![image](https://user-images.githubusercontent.com/2649562/182884928-1dee7c6b-6f1a-4f8f-ba76-9fe2b2054194.png)

Schön wäre es, wenn es hier zusätzlich die Möglichkeit gäbe die Eingabe eines benutzerdefinierten Zeitraums festzulegen, um bspw. auch `2 Tage` oder `2,5 Tage` abbilden zu können.

**Comment by OMOSde** [comment]
Das sollte sich mit einer DCA-Anpassung einfach realisieren lassen (ungetestet):

```
// src/Resources/contao/dca/tl_preview_link.php
<?php $GLOBALS['TL_DCA']['tl_preview_link']['fields']['expiresInDays']['options'][] = '2';
```

- Gleitkommazahlen müsste man testen
- das wird nicht für Zeiträume größer als 30 Tage funktionieren (das liegt am aktuellen Purge-Verhalten für die Vorschau-Links)
- Translation müsste selbst ergänzt werden

Interessant wäre vielleicht auch die Möglichkeit, Vorschaulinks zu verlängern und Zeiträume größer als 30 Tage zu ermöglichen (per DCA, wenn auch nicht als default)

**Comment by aschempp** [comment]
das ist **absichtlich** nicht möglich, insbesondere kein längerer Zeitraum als 30 Tage oder gar unlimitiert, das wäre aus meiner Sicht ein Sicherheitsrisiko. Der Zeitraum sollte so klein wie möglich gewählt werden, aber ich kann mir keinen ernsthaften Grund vorstellen warum jemand 2 aber nicht 7 Tage auf einen Vorschau-Link zugreifen darf?

**Comment by ausi** [comment]
> aber ich kann mir keinen ernsthaften Grund vorstellen warum jemand 2 aber nicht 7 Tage auf einen Vorschau-Link zugreifen darf?

Vielleicht derselbe Grund der die Auswahl zwischen 1 und 7 rechtfertigt?

**Comment by minstyle** [comment]
> [...] aber ich kann mir keinen ernsthaften Grund vorstellen warum jemand 2 aber nicht 7 Tage auf einen Vorschau-Link zugreifen darf?

Wenn ich bspw. Abends um 18:13 Uhr einen Vorschau-Link für den Kunden generiere und den Gültigkeitszeitraum auf 1 Tag stelle, dann ist der Link automatisch bis zum nächsten Tag um 18:13 Uhr gültig.

Wenn ich aber möchte, dass der Link am nächsten Tag nur bis 15:00 Uhr gültig sein soll, weil bspw. die Geschäftszeiten des Kunden bis 15:00 Uhr sind? Das ist jetzt ein Szenario von unendlich vielen Szenarios ;)

> [...] das ist absichtlich nicht möglich, insbesondere kein längerer Zeitraum als 30 Tage oder gar unlimitiert, das wäre aus meiner Sicht ein Sicherheitsrisiko.

Wieso ein Sicherheitsrisiko? Wäre der Hash des Links hier das Problem oder das Linkziel?

**Comment by aschempp** [comment]
> Wenn ich aber möchte, dass der Link am nächsten Tag nur bis 15:00 Uhr gültig sein soll, weil bspw. die Geschäftszeiten des Kunden bis 15:00 Uhr sind? Das ist jetzt ein Szenario von unendlich vielen Szenarios ;)

Ich verstehe schon dass du das einstellen könntest, ich sehe einfach keinen sinnvollen Grund für die Möglichkeit. Wenn der Kunde am nächsten Tag 5 Minuten länger arbeitet dann hat er Pech gehabt. Wenn du einfach 7 Tage nimmst, weil du weisst er sollte es morgen (oder Notfalls abends oder am nächsten Tag) prüfen, sind alle glücklich 😬 
Nur weil es unlimitierte Kombinations-/Konfigurationsmöglichkeiten gibt, muss man nicht alle haben. Solange mit den vorhandenen das sinnvolle erreicht werden kann, ist das aus meiner Sicht besser, einfacher zu verstehen, einfacher zu programmieren und weniger fehleranfällig.

> Wieso ein Sicherheitsrisiko? Wäre der Hash des Links hier das Problem oder das Linkziel?

In der aktuellen Situation könntest du dich dann unbegrenzt lange im Frontend unveröffentlichte Inhalte sehen. Wenn z.B. der Link also irgendwo geteilt wird, dann können alle endlos alles unveröffentlichte sehen. Kaum sinnvoll …

**Comment by ausi** [comment]
Mit #5454 kann nun ein belibiger „Gültig bis“ Zeitraum festgelegt werden.
