### ISSUE TITLE
Naming of labels for settings / for edit

### ISSUE THREAD

**Issue by Metis77** [contao/contao#509]
**Description**  
My customer always are completely confused about the difference of those editing settings and editing content label names.
I also think, that the naming is far from self-explanatory.

Therefor I suggest to change the naming of those icons simply to:
- edit content / settings
or in german
- Inhalte bearbeiten / Einstellungen

This means, drop the ID and the name of the thing like "event" or "article".
Just short and simply as suggested above.

**Example**  
Hier beispielhaft wie es gerade ist:
![naming](https://user-images.githubusercontent.com/1408361/57513378-5ee03880-730e-11e9-85f2-d9545bfed03b.jpg)

**Comment by leofeyer** [comment]
See #532.
