### ISSUE TITLE
Editing templates with the source editor changes line endings to Windows format

### ISSUE THREAD

**Issue by ausi** [contao/contao#5096]
### Affected version(s)

4.9

### Description

After editing a template file via the source editor in the backend, the line endings get changed from `\n` to `\r\n`. Not sure since when this issue occurs, but AFAIK this wasn’t always the case.

**Comment by fritzmg** [comment]
As far as I tested this solely depends on what the browser (or OS) inputs into the `<textarea>`. However, we could of course always normalize to `\n`.

**Comment by ameotoko** [comment]
I can confirm the problem, see the Slack thread: https://contao.slack.com/archives/CK9GW3ARL/p1657717360616099

**Comment by ausi** [comment]
> As far as I tested this solely depends on what the browser (or OS) inputs into the `<textarea>`.

You sure? The HTML spec seems to define that browsers always have to send `\r\n` for line breaks, see https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#multipart-form-data

**Comment by fritzmg** [comment]
Ah I see. And yeah, seems to apply to [`application/x-www-form-urlencoded`](https://url.spec.whatwg.org/#concept-urlencoded) as well.

**Comment by ausi** [comment]
But why was this not a problem earlier, I’m pretty sure I’d have noticed that.

**Comment by fritzmg** [comment]
Would you though? 🤔  I wouldn't if I don't check the line ending indicator in the lower right within VSCode for example - and when committing such a file to a repo it would likely be normalized by Git (depending on your settings).

**Comment by ausi** [comment]
> Would you though?

I think so, my GIT settings do not normalize this. (but this might not always have been the case 🤔)

How should we solve this? Always normalize to `PHP_EOL` or detect the line endings of the file use the detected ones when saving?

**Comment by fritzmg** [comment]
I think we should detect the line endings before saving and then normalize accordingly.

**Comment by ausi** [comment]
As discussed in the call today we want detect and normalize accordingly.
