### ISSUE TITLE
Error "Division by zero" in content element "Downloads"

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5118]
### Affected version(s)

5.0.0-RC3

### Description

Steps to reproduce:

1. create new content element of element type "Downloads"
2. as "Source files" choose some files; note: the files don't contain any metadata
3. check the box "Ignore files without metadata"
4. press button "Save and Close"

result:
"Internal Server Error" -> Division by zero

**Comment by ausi** [comment]
Probably a duplicate of #5081 ?

**Comment by ausi** [comment]
@jochi44 can you please verify if the changes from #5140 fix your issue?

**Comment by jochi44** [comment]
> @jochi44 can you please verify if the changes from #5140 fix your issue?

The error does not occur any more (5.x-dev).
