### ISSUE TITLE
DcaExtractor triggers warning if DCA field has no sql definition

### ISSUE THREAD

**Issue by bezin** [contao/contao#5122]
### Affected version(s)

4.13, maybe 4.9 too

### Description

Hello, 

I upgraded a project to 4.13 and PHP 8 and run into a Warning triggered in DcaExtractor

[PR 2762 ](https://github.com/contao/contao/pull/2762) is related and claims to fix this, however it does not under all conditions: In my case I have a field without SQL definition which is a MCW field on which I update another table manually (via load and save callback). Now in the extractor [$blnLoadFromFile will be set to true](https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php#L409), because of the missing sql definition. It will then proceed to [actually load `database.sql`](https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php#L447-L457) file from an installed extension. 

Then it will trigger [a warning here](https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php#L459): Warning: Undefined array key "tl_my_custom_table"

To reproduce:
Have a DCA field with inputType, but without sql definition. 
Have a database.sql
Use DcaExtractor

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5129
