### ISSUE TITLE
Do not show the password toggle if the value is *****

### ISSUE THREAD

**Issue by 3drcontao** [contao/contao#5126]
### Affected version(s)

4.13

### Description

As discussed [here ](https://community.contao.org/de/showthread.php?83546-BE-gt-Passworteinstellungen-gt-Passwort-best%C3%A4tigen-Eingabefeld-fehlt) the password show/hide toggler in the backend only shows the placeholder instead of the entered passwordphrase.

**Comment by aschempp** [comment]
This is not a bug, the password cannot be shown. We might consider not showing the toggle if the value is `*****` though.

**Comment by leofeyer** [comment]
What toggle? The password field only has a background icon but no toggle?

**Comment by 3drcontao** [comment]
Sorry if I expressed that imprecisely, you wrote:
"So far, this is working nice and neat and I was able to add the new show/hide toggle to every field in the back end where you set a new password" that is what my issue refers to.

**Comment by 3drcontao** [comment]
> This is not a bug, the password cannot be shown. We might consider not showing the toggle if the value is `*****` though.

Okay, might be that it is functional not a bug, but in my opinion it is a massive deterioration of the usability, so to speak it is kind of an usability bug. Couldn't the new password made visible by the toggler as long as it is not saved?

**Comment by fritzmg** [comment]
As already said, it is physically impossible to show a _previously_ saved password, as the password is encrypted.

If you enter a _new_ password the toggle will show you that password.

**Comment by leofeyer** [comment]
We have only added the toggle to fields where you **enter new passwords**. Fields that are used to **ask for existing passwords** do not receive a toggle.

**Comment by 3drcontao** [comment]
Now I've got it, sorry for the misunderstanding: A **new password** can be made visible by the toggler as long as it is not saved! An **existing password** can not made visible. So there is not a bug in this solution; nevertheless I think Andreas proposal " not showing the toggle if the value is ***** though" would be an improvement.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to remove the `*****` completely.
