### ISSUE TITLE
No password toggle when forcing a password change

### ISSUE THREAD

**Issue by 3drcontao** [contao/contao#5128]
### Affected version(s)

4.13

### Description

As discussed [here](https://community.contao.org/de/showthread.php?83546-BE-gt-Passworteinstellungen-gt-Passwort-best%C3%A4tigen-Eingabefeld-fehlt&p=561859&viewfull=1#post561859) there is only a padlock-icon in the password show/hide toggler in the frontend form for setting a new password for backend-users instead of a show/hide toggler to check the entered passwordphrase.

**Comment by aschempp** [comment]
I can confirm the problem. The "Change password" backend screen does not have the toggle icon.

<img width="544" alt="Bildschirmfoto 2022-08-12 um 11 18 13" src="https://user-images.githubusercontent.com/1073273/184324591-71cf6a1b-8599-4a50-897d-a15ebdfccf20.png">
