### ISSUE TITLE
CustomTpl field in tl_form_field acts strange in act=overrideAll

### ISSUE THREAD

**Issue by michb** [contao/contao#5131]
### Affected version(s)

4.13

### Description

Steps to reproduce in Contao demo

- go to `Forms` -> `Contact`
- `edit multiple` and select the fields `name` and `email`
- click `override`
- select the field `customTpl` and `continue`

Then you can select the template `form_upload` but the both fields have the type `text`. So this is weird. But on `act=edit` or `act=editAll` we can select the template `form_textfield (Default)`.

Even stranger if you have a custom template like `form_textfield_custom`. The selects have following options:
- on `act=edit` and `act=editAll`
  -  `form_textfield (Default)`
  -  `form_textfield_custom`
- on `act=overrideAll`
  -  `form_textfield_custom`

So the default option is missing and we cannot reset to the default while on `act=overrideAll`

**Comment by leofeyer** [comment]
Can you reproduce this in Contao 4.13.7? The online demo is still at 4.13.5 (will upgrade to Contao 4.13.8 later this week).

**Comment by michb** [comment]
yes the behaviour is still as described above in Contao 4.13.8

**Comment by leofeyer** [comment]
I cannot reproduce this.

https://user-images.githubusercontent.com/1192057/187187821-de2bdf17-9f64-49ec-af14-8cf0a29f78d4.mov

**Comment by michb** [comment]
You have the error right in your video. In this case you cannot select the default template. 
For example: you created the form fields and set different templates. But then you noticed this was wrong and want to set all fields back to their default template. So as seen in your video it is not possible with `override`.

And if you got no custom template some random template or none will be shown.
