### ISSUE TITLE
Contao 5: Missing CSS class in headline element

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#5134]
### Affected version(s)

5.0.x-dev

### Description

When I use the headline content element and add a custom CSS class, there is no output in the frontend.

**Steps to reproduce:**
1. Add a pure headline element
2. Add a custom css-class
3. check source-code in frontend

**Comment by ausi** [comment]
@contaoacademy can you please verify if the changes from #5135 fix your issue?

**Comment by contaoacademy** [comment]
Looks great!
![screen-20220812_sK0Z5fve](https://user-images.githubusercontent.com/23719181/184383163-2344112b-8fb9-411e-9855-05149d8de2b8.jpg)
