### ISSUE TITLE
Visible fieldset and empty legend with template member_grouped on captcha field

### ISSUE THREAD

**Issue by Aybee** [contao/contao#514]
**Affected version(s)**

4.4.40

**Description**  

Das Template member_grouped erzeugt folgende Ausgabe bei dem Captcha
```html
<fieldset>
  <legend></legend>
  <div class="widget widget-captcha mandatory" style="display: none;">
    <label for="ctrl_registration">
      <span class="invisible">Mandatory field </span>Security question<span class="mandatory">*</span>
    </label>
    <input type="text" name="captcha_registration" id="ctrl_registration" class="captcha mandatory" value="" aria-describedby="captcha_text_registration" maxlength="2" required="">
    <span id="captcha_text_registration" class="captcha_text">Please calculate 1 plus 2.</span>
    <input type="hidden" name="captcha_registration_hash" value="7a2028c128d50d7e5641ba176effff3bcf5df818645baf5c988c242dd8971ff7">
    <div style="display:none">
      <label for="ctrl_registration_hp">Do not fill in this field</label>
      <input type="text" name="captcha_registration_name" id="ctrl_registration_hp" value="">
    </div>
    <script>
      document.getElementById('ctrl_registration').parentNode.style.display = 'none';
      document.getElementById('ctrl_registration').value = '3';
    </script>
  </div>
</fieldset>
```
Das oberste `DIV` ist `display:none`, aber die Elemente `fieldset` und `legend` nicht. Das sieht schlecht aus, wenn man `fieldset` und `legend` formatiert hat, wie z.B. in der Online-Demo.

Eine Änderung des Core-Templates https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/templates/member/member_grouped.html5#L18-L25 könnte Abhilfe schaffen, z.B.
```php
...
<?php foreach ($this->categories as $legend=>$category): ?>
  <?php if (!empty($category)): ?>
    <?php if (!$legend): ?>
      <?= implode('', $category) ?>
    <?php else: ?>
      <fieldset>
        <legend><?= $legend ?></legend>
        <?= implode('', $category) ?>
      </fieldset>
    <?php endif; ?>
  <?php endif; ?>
<?php endforeach; ?>
...
```
In diesem Beispiel wird das `fieldset` und `legend` für das Captcha nicht gerendert.

Zudem ist die Legend leer, was auch nicht gut aussieht.

Eine Frage habe ich noch: Warum wird das Inline-Style `display:none` und das `value` per JS aufgesetzt? Könnte dies nicht direkt in der HTML-Variable mit enthalten sein? So sieht die Variable aus:
```html
[captcha] => 
  <div class="widget widget-captcha mandatory">
    <label for="ctrl_registration">
      <span class="invisible">Pflichtfeld</span>Sicherheitsfrage<span class="mandatory">*</span>
    </label>
    <input type="text" name="c599e354e3dbb156567ecab7b0a015dd6" id="ctrl_registration" class="captcha mandatory" value="" aria-describedby="captcha_text_registration" maxlength="2" required>
    <span id="captcha_text_registration" class="captcha_text">&#87;&#97;&#115;&#32;&#105;&#115;&#116;&#32;&#100;&#105;&#101;&#32;&#83;&#117;&#109;&#109;&#101;&#32;&#97;&#117;&#115;&#32;&#54;&#32;&#117;&#110;&#100;&#32;&#50;&#63;</span>
    <div style="display:none">
      <label for="ctrl_registration_hp">Do not fill in this field</label>
      <input type="text" name="c599e354e3dbb156567ecab7b0a015dd6_name" id="ctrl_registration_hp" value="">
    </div>
  <script>
      document.getElementById('ctrl_registration').parentNode.style.display = 'none';
      document.getElementById('ctrl_registration').value = '8';
    </script>
  </div>
```

**How to reproduce**  

Online Demo:
Erstelle ein Modul vom Typ Registrierung.
Template member_grouped auswählen.
Modul auf eine Seite platzieren.
Im Frontend ansehen.

**Comment by Aybee** [comment]
> @Aybee Warum wird das Inline-Style display:none und das value per JS aufgesetzt?

Hat @ausi auf slack.com beantwortet: Weil Besucher/Bots ohne JS somit den Value nicht gesetzt bekommen und damit das Feld zum Ausfüllen sehen müssen.

**Comment by leofeyer** [comment]
Ich sehe das Problem, allerdings finde ich die vorgeschlagene Lösung nicht gut, das `<fieldset>` wegzulassen. Das Captcha-Widget müsste dann gesondert formatiert werden, für den Fall, dass es doch mal angezeigt wird.

* Ich stimme zu, dass wir `<legend>` nicht ausgeben sollten, wenn es leer ist.
* Außerdem würde ich das JS so anpassen, dass `style.display = 'none'` zum `<fieldset>` hinzugefügt wird anstatt zum `<div>`.

Das sollte das Problem lösen, oder?

**Comment by fritzmg** [comment]
> * Außerdem würde ich das JS so anpassen, dass `style.display = 'none'` zum `<fieldset>` hinzugefügt wird anstatt zum `<div>`

Theoretisch könnte es jedoch sein, dass im selben Fieldset (leere `feGroup`) auch noch andere Felder ausgegeben werden.

**Comment by Aybee** [comment]
> @leofeyer Das sollte das Problem lösen, oder?

Ich hatte gehofft, dass du mit ner bessere Lösung kommst 😉. Das von mir und fritzmg war erstmal nur quick and dirty. Das mit dem JS hatte ich auch bereits im Hinterkopf, war mir aber unsicher, was es mit diesem JS auf sich hat.

> @fritzmg Theoretisch könnte es jedoch sein, dass im selben Fieldset (leere feGroup) auch noch andere Felder ausgegeben werden.

Das JS betrifft dann ja nur das Captcha.

Dass keine leere `legend` ausgegeben werden soll beträfe allgemein das komplette Template mit allen Gruppen und kann dann im Template allgemein auch noch aufgefangen werden.

**Comment by fritzmg** [comment]
> Das JS betrifft dann ja nur das Captcha.

Ja, aber @leofeyer Lösungsvorschlag ist ja, dass das gesamte `<fieldset>` auf `display: none;` gesetzt werden sollte. Und theoretisch könnte es wie gesagt sein, dass sich in diesem `<fieldset>` auch noch andere Felder befinden, die natürlich nicht ausgeblendet werden sollten. Praktisch wird das natürlich kaum vorkommen.

**Comment by Aybee** [comment]
Ob ein `fieldset` ohne `legend` überhaupt Sinn macht, wäre auch noch zu überdenken. Ich für meinen Teil bräuchte das nicht. Ein `fieldset` ist ja eigentlich dazu da um **mehrere** Felder zu umschließen. Für ein einzelnes Feld bräuchte man IMHO kein `fieldset`. Und wenn ein `fieldset` gerendert wird, sollte es auch eine `legend` haben. Oder?

**Comment by leofeyer** [comment]
> Und theoretisch könnte es wie gesagt sein, dass sich in diesem `<fieldset>` auch noch andere Felder befinden

Das Captcha ist standardmäßig in einem eigenen Fieldset, daher dürfte das ein theoretischer Fall bleiben. Aber um sicher zu gehen, habe ich ein Prüfung eingebaut, die das Fieldset nicht ausblendet, wenn mehr als ein Kindknoten enthalten ist.

**Comment by leofeyer** [comment]
Behoben in a9140418efb52e3cf3a05fa6ef9817a14f38a70c.

**Comment by Aybee** [comment]
Vielen Dank
