### ISSUE TITLE
Editing News Item bring content from tl_article instead of tl_content

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#5157]
### Affected version(s)

4.13.7

### Description

After updaing to Contao 4.13.7, when try to edit news item content (or add new news item), it show content from "tl_article" with same pid of news item if exists.

**Comment by leofeyer** [comment]
How can we reproduce the issue?

**Comment by ausi** [comment]
I can reproduce that issue by editing a news article. Seems to be caused by #5108

**Comment by ausi** [comment]
The `ptable` of tl_content is manually set to `tl_article` here https://github.com/contao/contao/blob/dd844c2f43bec55f9677cab4c913b09725582d84/core-bundle/src/Resources/contao/dca/tl_content.php#L36

/cc @dmolineus

**Comment by netzarbeiter** [comment]
How to reproduce:
- Go to an event or a news with an item (for example ce_text)
- The item is empty (there is no possibility to create a new content element)

![Bildschirmfoto 2022-08-16 um 14 44 45](https://user-images.githubusercontent.com/1942550/184883081-9662d334-5eb4-41d4-bf40-000567317a1a.png)
![Bildschirmfoto 2022-08-16 um 14 44 55](https://user-images.githubusercontent.com/1942550/184883083-fb2b2a51-bcab-47b6-afa9-f6df1bc22eb1.png)
