### ISSUE TITLE
zugängliche Dropdown-Navigation

### ISSUE THREAD

**Issue by skipman** [contao/contao#5160]
### Description

Link zur Info: [zugängliche Dropdown-Navigation] (https://wiki.selfhtml.org/wiki/JavaScript/Tutorials/zug%C3%A4ngliche_Dropdown-Navigation)

Ist es möglich, das direkt in den Core aufzunehmen? Die Nutzer mobiler Geräte mit Touch-Eingabe werden es danken. Was meint Ihr?

**Comment by ausi** [comment]
Welche Dropdowns in Contao sind aktuell nicht via Touch bedienbar?
Geht es um das Backend?

**Comment by asaage** [comment]
Ich glaube nicht, das das für die default-navigation im Contao FE praktikabel ist wenn das Elternelement gleichzeitig ein Link ist.
Herkömmliches "hover-Verhalten" damit abzubilden ohne JS einzusetzten scheint mir auch schwierig.

Würde das eher belassen wie es ist und eventuelle Anpassungen im individuellen css vornehmen
```
@media (hover: none) {
  /* behaviour for touch browsers */
}
```
```summary / details``` war allerdings mal für ce_accordion im Gespräch.

**Comment by aschempp** [comment]
Zum Artikel kann ich nicht viel sagen, aber die Verwendung von `<details>` und `<summary>` erscheint mir semantisch falsch. Eine Verwendung als Akkordion hatten wir schon in https://github.com/contao/contao/pull/2301#issuecomment-809140022 diskutiert, auch https://adrianroselli.com/2019/04/details-summary-are-not-insert-control-here.html#Navigation deklariert klar eine falsche Semantik und Barrierefreiheit.

**Comment by skipman** [comment]
Danke für euer Feedback! Werde mich bei Gelegenheit weiter damit befassen.
