### ISSUE TITLE
The request token is replaced only sporadically

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#5161]
### Affected version(s)

4.9.32

### Description

After updating to 4.9.32, the request token in an Isotope reader module is only replaced sporadically.

https://github.com/isotope/core/blob/2.8/system/modules/isotope/templates/isotope/iso_reader_default.html5#L4

If I put a product in the shopping cart and want to add another one, I land on the error page "Invalid request token".

The request token is not replaced in the front end.

```html
<input type="hidden" name="REQUEST_TOKEN" value="{{request_token}}">
```

**Comment by aschempp** [comment]
Looks like it does no longer happen automatically for ajax requests? 🤔

**Comment by ausi** [comment]
Can this be reproduced without Isotope?
Does downgrading to Contao 4.9.31 fix the issue?

**Comment by netzarbeiter** [comment]
Downgrading to Contao 4.9.31 fixed the issue for me.

**Comment by fritzmg** [comment]
@netzarbeiter can you test if https://github.com/contao/contao/pull/5130 may be fixes the issue? (The change within `vendor/core-bundle/src/Framework/ContaoFramework.php` should be sufficient for testing.)

**Comment by netzarbeiter** [comment]
The changes have no effect on the behaviour.

**Comment by aschempp** [comment]
This is actually a problem of Isotope 2.8.6 and not Contao. https://github.com/isotope/core/commit/1b7b15bad84bb7706978afb4da06b44585649abc#diff-72afebad9a00277ea35fef7ddf8851956b83d644d5d9a155a811e12ec3ac7a10 changed the response handling from Haste to Symfony, but Symfony (obviously) does not replace insert tags on the response. I'll provide a fix in Isotope.
