### ISSUE TITLE
CSS classes for responsive videos

### ISSUE THREAD

**Issue by ausi** [contao/contao#5172]
### Affected version(s)

5.0

### Description

Should we change the CSS classes in https://github.com/contao/contao/blob/e45e0e7d95e527253a80fae179b22280cc95623d/core-bundle/contao/templates/_new/content_element/_video.html.twig#L8 to `responsive ratio-` like they were before?
 
Or should we add the new class names to https://github.com/contao-components/contao/blob/9.x/css/responsive.css ?

I think I’d prefer the latter.

**Comment by aschempp** [comment]
I would keep the existing classes, there's really no need to rename them and ask people to migrate?

**Comment by leofeyer** [comment]
> I think I’d prefer the latter.

Me too, actually. 🙈

**Comment by ausi** [comment]
> I would keep the existing classes, there's really no need to rename them and ask people to migrate?

There is always the possibility to switch back to the old elements/templates, see https://github.com/contao/contao/blob/5.0/UPGRADE.md#content-elements

This approach was used deliberately to be more free for the class names and HTML structure of the new templates AFAIR.

**Comment by leofeyer** [comment]
Yes. And if we add the new classes to the `responsive.css` style sheet, it will work with both versions and nobody will have to migrate anything.

**Comment by leofeyer** [comment]
Version 9.3 now supports the new CSS classes: https://github.com/contao-components/contao/pull/14
