### ISSUE TITLE
<strong> aus Navigationstemplate entfernen

### ISSUE THREAD

**Issue by zonky2** [contao/contao#519]
siehe https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/templates/navigation/nav_default.html5#L5

m.E. gehört eine Auszeichnung per `<strong>` nicht per Default in das Template - das sollte per CSS gemacht werden. Statt strong könnte man ein `<span>` verwenden.

**Comment by xchs** [comment]
Es geht hier v. a. um Semantik (siehe https://github.com/contao/core/issues/6336).

**Comment by zonky2** [comment]
thx - den hatte ich nicht gefunden
