### ISSUE TITLE
Use Symfony VarDumper component

### ISSUE THREAD

**Issue by aschempp** [contao/contao#52]
http://symfony.com/blog/new-in-symfony-2-6-vardumper-component

It could actually be a compatible replacement for our `dump` function.

**Comment by aschempp** [comment]
Please assign this to me

**Comment by leofeyer** [comment]
I can't. GitHub only allows me to assign it to myself.

**Comment by aschempp** [comment]
You should probably create a team with us but only give us pull access.

**Comment by leofeyer** [comment]
Ah, I forgot to add the dev team to the new repos. Will do now :)

**Comment by aschempp** [comment]
I just tested this. It's pretty cool as it does output the dumps into the web profiler. However, there are two problems:
1. The dump function is only available after the container is build (which should be fine for legacy code)
2. Normally, it's only available in the dev environment (as the `DebugBundle` should only be loaded then).

I suggest to add this for a quick discussion.

**Comment by leofeyer** [comment]
I could live with the two limitations.

**Comment by discordier** [comment]
So could I. IMO development related things should not be available in prod at all. I like the fact that by this accidental leakage of "forgotten" showTemplateVars is finally history.

**Comment by aschempp** [comment]
@Toflar if you can agree too we can finish this an add a note to the UPGRADE.md

**Comment by Toflar** [comment]
Agreed.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/130.
