### ISSUE TITLE
Contao 5 standard favicon.ico missing

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5211]
### Affected version(s)

5.0.1

### Description

On a fresh Contao 5.0.1 installation I noticed that the standard Contao favicon.ico is missing.

![contao5_standard_favicon_missing](https://user-images.githubusercontent.com/60215157/185903132-87a4aae5-a669-450a-81df-d79f98072522.jpg)

Maybe this is intended.

**Comment by Toflar** [comment]
It is intended. If you did not configure one in the root page settings, then there is none.
