### ISSUE TITLE
Public images not accessible

### ISSUE THREAD

**Issue by jxns** [contao/contao#5215]
### Affected version(s)

5.0.1

### Description

I installed Contao 5.0.1 (fresh install, not updated) and created folders and uploaded images via the file browser. The "public" checkmark for the folders is checked. The uploaded images are correctly shown in the file browser.

But neither on the website, nor in the article preview of the backend, the pictures are accessible. I only get a 404 for the images and the debug mode for the frontend shows me the following message: 

`
Router Symfony\Bundle\FrameworkBundle\Routing\Router was not able to match, message "No routes found for "/files/test/logo.png/"."
`

Never had a problem this way. Am I missing something?

**Comment by jxns** [comment]
Just noticed that the corresponding symlink is not created in the web/files folder.
Even the "Create new symlinks" option in the maintenance section does not create the symlink.
Am I doing something wrong here?

**Comment by contaoacademy** [comment]
Hi, Contao 5 uses as default root-folder the directory `/public` instead of `/web`

If you want to use `/web`, you have to configure it manually in your `composer.json` under extra.
https://docs.contao.org/manual/de/installation/systemvoraussetzungen/#hosting-konfiguration

**Comment by jxns** [comment]
I dont need to use the /web folder, I was just confused that uploaded images are not accessible. Is this the right behaviour?
Using the "Composer Class Loader" and "Install Composer Dependencies" in the Contao Manager fixed the issue.
But I am not sure if I configured something wrong or if this is a wrong behaviour.

**Comment by ausi** [comment]
So, creating symlinks via the maintenance section did not work, but running Composer (via the Contao Manager) did work?

Can you reproduce this behavior with new folders where you activate the “public” checkbox?

**Comment by jxns** [comment]
Yes, the behavior is reproduceable.
I proceeded as follows:
1. Went to "files" in the backend. Created a new folder. "Public" checkbox was already checked by default.
2. Duplicated a working image to the new folder.
3. Changed the image to the new, duplicated image in the corresponding article

Same behavior. Image is neither visible in the backend article preview, nor in the frontend.
"Create symlinks" in the backend did not solve that. Running composer in the Contao Manager fixed it again.

**Comment by ausi** [comment]
I was not able to reproduce that, can you post the HTML source code of the `<img>` element that gets output in the frontend?

**Comment by jxns** [comment]
Of course. The source code is:
`
<img src="/files/test2/spacer.png" alt="" width="1920" height="305">
`

**Comment by ausi** [comment]
Can you please check the system log after you create a new public folder. Does it say something like “Regenerated the symlinks” or “The symlinks could not be regenerated”

**Comment by jxns** [comment]
Yes, it does say that:

> [25.08.2022 10:34] Folder "files/test2" has been created
> [25.08.2022 10:34] Regenerated the symlinks
> [25.08.2022 10:34] Folder "files/test2" has been published
> [25.08.2022 10:34] File or folder "files/testfolder/spacer.png" has been copied to "files/test2/spacer.png"
> [25.08.2022 10:34] Version 1 of record "tl_files.id=30" has been created
> [25.08.2022 10:34] Version 9 of record "tl_content.id=19" has been created (parent records: tl_article.id=15, tl_page.id=3)

**Comment by ausi** [comment]
I think I know what’s going on. If the symlinks are regenerated from the backend, the configured `%contao.web_dir%` does not get passed to the command in https://github.com/contao/contao/blob/49dab323cda78066fcd754f3475eb089f43466e6/core-bundle/contao/library/Contao/Automator.php#L369 but in the `contao-setup` command (that runs after composer install/update) it gets passed correctly in https://github.com/contao/contao/blob/49dab323cda78066fcd754f3475eb089f43466e6/manager-bundle/config/services.yaml#L30

This needs to be fixed I think.
