### ISSUE TITLE
Contao 5 - Update layout.css

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#5219]
### Affected version(s)

5.0.1

### Description

The new CSS classes are not included in `layout.css`.

For example:

- `float_left` = `media--left`
- `float_right` = `media--right`
- `ce_gallery` = `content-gallery`

**Comment by ausi** [comment]
Should we discuss if we can deprecate some of these core CSS files for the frontend?

**Comment by aschempp** [comment]
We _could_, but that would be for Contao 6 right? So not really helpful for the next few years?

**Comment by ausi** [comment]
> We _could_, but that would be for Contao 6 right?

If we want to deprecate it, we should do it straight away in Version 5, why should we wait for Contao 6?

> So not really helpful for the next few years?

Why would this deprecation not be helpful? (compared to any other deprecation)

**Comment by leofeyer** [comment]
Please create the ticket again in the correct repo https://github.com/contao-components/contao. I cannot transfer it to another organization automatically.
