### ISSUE TITLE
Twig templates missing in news module

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#5220]
### Affected version(s)

5.0.1

### Description

If I see it correctly, the news module still uses the old HTML templates.

This means that the CSS is inconsistent.

`news_latest.html5` uses the old CSS classes:
- `ce_text`
- `image_container`
- `float_above`

instead of the new one.

**Comment by ausi** [comment]
Yes, only most of the content elements are twig templates so far.

**Comment by Kahmoon** [comment]
ce_sliderStart is also using the old tag. 

```
<div class="ce_sliderStart block">
<h2>Slider</h2>
<div class="content-slider" data-config="0,300,0,">
<div class="slider-wrapper">
</div>
</div>
<nav class="slider-control">
<a href="#" class="slider-prev">Zurück</a>
<span class="slider-menu"></span>
<a href="#" class="slider-next">Vorwärts</a>
</nav>
</div>
```

Thats kinda irritating. Will all ce_* be changed? Just to prepare css files before updating from C4 to C5.

**Comment by ausi** [comment]
> Will all ce_* be changed?

Eventually, yes.

You can still go back to the old elements to get `ce_*` everywhere, see https://github.com/contao/contao/blob/5.0/UPGRADE.md#content-elements

**Comment by m-vo** [comment]
> ce_sliderStart is also using the old tag.

I did not replace the wrapper elements yet as I'd want to give the concept of real nested content elements a shot first. Then you'd get a single controller and template for an accordion/slider/… instead.

**Comment by Kahmoon** [comment]
Thanks. Actually (5.0.1)this is a bit inconsistent :-D. I´m going to use the workaround where i can use old classes until C6 and keep an eye on this .

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to keep the old CSS classes for the old elements. It is likely that Contao 5.1 will contain nested content elements and there will be new wrapper elements with new templates.
