### ISSUE TITLE
Auswahl von PNG als Favicon nicht möglich

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#5232]
### Affected version(s)

4.13.x

### Description

Aktuell kann man als Favicon nur ICO und SVG auswählen. PNG Favicons werden im Gegensatz zu SVG jedoch von allen Browsern unterstützt.
https://caniuse.com/link-icon-png
https://caniuse.com/link-icon-svg

**Comment by fritzmg** [comment]
For a forward compatible workaround you can do the following:

```php
// contao/dca/tl_page.php
$GLOBALS['TL_DCA']['tl_page']['fields']['favicon']['eval']['extensions'] .= ',png';
```

**Comment by ausi** [comment]
See #5455
