### ISSUE TITLE
tl_member.username should not be larger than VARCHAR(64)

### ISSUE THREAD

**Issue by AlexanderWillner** [contao/contao#5244]
### Affected version(s)

4.13.8

### Description

*Steps that will reproduce the problem?*
1. Write a third party login extension for Contao (e.g. for [Servicekonto.NRW](https://servicekonto.nrw) or https://id.bund.de/de/eservice/konto)
2. Store the UUID of the user (provided by the third party) to `tl_member.username`

*What is the expected result?*
Enough "space" to store the UUID.

*What happens instead?*
The generated UUIDs might be too large for the VARCHAR(64) field.

*Possible workaround:*
Change the type of the field. However, the execution of `./vendor/bin/contao-console contao:migrate -n` might fail with the following error message:

```
 * ALTER TABLE tl_member CHANGE username username VARCHAR(64) DEFAULT NULL COLLATE `utf8mb4_bin`......FAILED
 [ERROR] An exception occurred while executing a query: SQLSTATE[01000]: Warning: 1265 Data truncated for column        
         'username' at row 42                                                                                           
```

*Any additional information:*

I guess the issue could be fixed at https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/library/Contao/Database/Updater.php#L579

**Comment by fritzmg** [comment]
This is something that needs to be fixed in the login extension, not Contao.

**Comment by michb** [comment]
I think he wrote an extension, that **for example** set the field `username` to `varchar(128)`.
But then the linked update mechanism will change the field back to `varchar(64)`, which will throw the given exception.

**Comment by fritzmg** [comment]
@michb the linked Code is a Contao 3.5.0 migration. This will only be executed once when updating a database from a Contao version that is older than Contao 3.5.0 to a Contao >=3.5.0, <4 version. The issue sounds like the extension did not increase the size of the `tl_member.username` field.

**Comment by AlexanderWillner** [comment]
True, each extension could (and probably should) extend the field size - I'll will check this.
At the same time, while a (modern) UUID is a 128-bit label (like in this case) the current default limit of 64 bit seems to be arbitrary and too low imho.
Additionally, I guess the migration should not have triggered anyways, as it was an upgrade from 4.9 to 4.13 (iirc). Using the parameter `--no-backup` is a workaround to this issue. Again not sure yet why this is the case.

**Comment by fritzmg** [comment]
> At the same time, while a (modern) UUID is a 128-bit label (like in this case) the current default limit of 64 bit seems to be arbitrary and too low imho.

64 characters (not bits - it is 8 bits per character in this case) seems enough for a username. And again, if an extension uses the field for something longer, it will need to adjust the DCA accordingly.

**Comment by ausi** [comment]
> The generated UUIDs might be too large for the VARCHAR(64) field.

How? A UUID in readable form `00000000-0000-0000-0000-000000000000` is 36 characters long (including the dashes), this should easily fit inside a `VARCHAR(64)`

**Comment by AlexanderWillner** [comment]
Mh, indeed, interesting...
