### ISSUE TITLE
Cache is not refreshed when a change is made to a related content item.

### ISSUE THREAD

**Issue by Ainschy** [contao/contao#5248]
### Affected version(s)

4.13.8

### Description

A content element is maintained centrally in a page tree and used in further page trees. After changes, the cache on the related pages is not discarded.

**Comment by fritzmg** [comment]
I can confirm the issue. We are currently only tagging the id of the alias element itself - but not the the id of the included element. This issue should also occur in Contao 4.9.

// I can confirm that the issue also occurs in Contao 4.9.
