### ISSUE TITLE
Add »Display in« Info to article teaser

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#5253]
### Description

Within the "content elements" list, details such as "title", "author", etc. are listed for the article. The further info of "Display in" (Header, Main Column, Footer etc.) would be helpful here too.

![contao-screen](https://user-images.githubusercontent.com/7679799/188824358-1bed1712-1558-4d4c-af7b-6169f1a3dc39.jpg)

**Comment by fritzmg** [comment]
Just adjust your DCA:

```php
// contao/dca/tl_content.php
$GLOBALS['TL_DCA']['tl_content']['list']['sorting']['headerFields'][] = 'inColumn';
```

**Comment by aschempp** [comment]
I agree with @fkaminski that would make sense to be there by default – much more sense than the author 😆

**Comment by fritzmg** [comment]
The `author` still makes sense when `tl_news` is parent imho. To me `inColumn` would not be helpful as we almost never use that fetaure ;)

**Comment by fkaminski** [comment]
Anyway: Added this DCA entry as a tip to the manual

**Comment by Aybee** [comment]
I never use "Display in" either. Everything always in the main column. I don't use "Show from/until" either. Should turn it off now that I see it. 😆

**Comment by fkaminski** [comment]
I close the issue, because there is at least a workaround for this and it is now documented
