### ISSUE TITLE
custom templates are not listed in the module settings, if the frontend module controller extends from  Contao\CoreBundle\Controller\AbstractFragmentController

### ISSUE THREAD

**Issue by markocupic** [contao/contao#5264]
### Affected version(s)

Contao 5.0.1 PHP 8.1

### Description

1. Create a new frontend module of type "template"
2. Store a custom template in templates/mod_template_ext.html5
3. Run composer install
4. Then go back to the module settings
5. The attempt to select the newly created template fails, because the template is not listed in the dropdown menu

![image](https://user-images.githubusercontent.com/1525166/189488616-eccdaa5c-481d-4ff3-ae84-d1dfc2a01038.png)

**Comment by leofeyer** [comment]
The `mod_template.html5` template has been replaced with a Twig template in Contao 5.0.3. Does the issue still occur?

**Comment by markocupic** [comment]
Hi Leo 
No, unfortunately my customized **Twig template** `template_cust.html.twig` is still not selectable in the module settings. Contao version: 5.0.4

Where should I store it?
I've tried it (under Contao 5.0.4) in these folders:
 `templates/template_cust.html.twig`
 `templates/frontend_module/template_cust.html.twig`
 `contao/templates/template_cust.html.twig`
 `contao/templates/frontend_module/template_cust.html.twig`
 `templates/template.html.twig`
 `templates/frontend_module/template.html.twig`
 `contao/templates/template.html.twig`
 `contao/templates/frontend_module/template.html.twig`

**Comment by aschempp** [comment]
I'm not expert on the topic, but I think it should be `/templates/frontend_module/template/custom.html.twig`

**Comment by markocupic** [comment]
@aschempp 
> I'm not expert on the topic, but I think it should be `/templates/frontend_module/template/custom.html.twig`

This is it! Thank you. 👍
