### ISSUE TITLE
Picker url broken on custom backend route

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#527]
**Affected version(s)**

- Contao 4.4
- Contao 4.7

**Description**  

I use the Contao TinyMCE on a custom backend route `/contao/custom/route`. Opening the picker, triggered by `Backend.openModalBrowser` try to locate the picker at  `/contao/custom/route/picker` which results in a 404.

**How to reproduce**  

- Create a custom route
- Create a backend form with the TinyMCE
- Try to open the picker

**Comment by aschempp** [comment]
That's most likely because we're not correctly generating the picker route but just appending `/picker` to the current `/contao` route in the javascript. I guess we either need to pass the URL or set something like a global variable?

**Comment by dmolineus** [comment]
Yes, the current solution uses `document.location.pathname` and just append `/picker` to it. I also suggest using a property of the global `Contao` object. Hardcoding the path to `/contao/picker` would not regarding if the backend is visited within the `app_dev.php` context.

**Comment by aschempp** [comment]
Exactly. Can you maybe create a pull request?

**Comment by dmolineus** [comment]
Done, see #534.
