### ISSUE TITLE
Add og:image to Meta Fields for Sites, News and Events

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#5272]
### Description

<img width="1238" alt="Bildschirmfoto 2022-09-14 um 06 52 22" src="https://user-images.githubusercontent.com/1622733/190062544-8b3bb8b6-8404-46ac-827a-caf357dde1bd.png">

`<meta property="og:title" content="Seitentitel" />`
`<meta property="og:description" content="Beschreibung der Seite" />`
`<meta property="og:url" content="https://seite.de/alias" />`
`<meta property="og:image" content="https://seite.de/selected_image.jpg" />`

**Comment by aschempp** [comment]
you could use an extension like https://extensions.contao.org/?p=codefog%2Fcontao-social_images for that 🙃

**Comment by frontendschlampe** [comment]
of if you want some more: https://extensions.contao.org/?q=social&pages=1&p=hofff%2Fcontao-social-tags ;-)

**Comment by asaage** [comment]
another one: https://extensions.contao.org/?q=open&pages=1&p=numero2%2Fcontao-opengraph3
(I'm starting to feel Wordpress-Plugin-jungle-vibes 🙈)

**Comment by erikherbert** [comment]
That's the point. Why not make these things core? Aren't they standard enough?

**Comment by m-vo** [comment]
> Aren't they standard enough?

I don't think so. There is JSON-LD, Microdata, Twitter Cards and more… And some people may just not need it (think intranet scenarios for example). IMHO an extension is the better choice here.

**Comment by erikherbert** [comment]
Ok.

**Comment by fritzmg** [comment]
To be fair though, OpenGraph Meta tags are used quite frequently. It's the minimum for sharing links on any social network (including Facebook, Twitter and LinkedIn for example).
