### ISSUE TITLE
Duplicate opacity for draft operations

### ISSUE THREAD

**Issue by aschempp** [contao/contao#5274]
### Affected version(s)

4.9.32+

### Description

The changes in https://github.com/contao/contao/commit/5bf5b490e33a06943dda4e8927047f349b3b3d0c#diff-725dfe6721aaccd983e9436b6408927acc163e02cc376e6b3aa2bead73eccb7bR1000 cause a duplicate opacity on table rows. The row will have an opacity of 0.5 and its content again, which makes operations almost invisible.

I can see the reason is that the row has no sub items, but I guess we need to remove `td > *` then?

**Comment by bytehead** [comment]
Can copy this: (Contao 4.9.33): 

<img width="163" alt="Bildschirmfoto 2022-09-14 um 13 32 35" src="https://user-images.githubusercontent.com/754921/190142982-2d4a3d0d-5d74-4bc2-ac36-382800eb63fc.png">

**Comment by fritzmg** [comment]
imho operations should not have an opacity at all - as this indicates "disabled" buttons (to me). But they are not disabled (in fact you need to use them to get rid of the draft status).

**Comment by leofeyer** [comment]
The operations should definitely have an opacity because only the original author is meant to use them (if at all)! But not a double opacity of course.
