### ISSUE TITLE
Anlegen von Seiten bei frischen Installationen nicht möglich

### ISSUE THREAD

**Issue by av3** [contao/contao#5283]
### Affected version(s)

4.13.9

### Description

Mit einer frischen Installation von Contao 4.13.9 konnte ich lediglich "Startpunkt einer Website" hinzufügen. 

![image](https://user-images.githubusercontent.com/5757594/190455414-9c7ea221-9d3f-4880-961d-21392686781c.png)

Das Anlegen neuer Seiten ist nicht möglich. Ich kann zwar beliebig viele Startpunkte hinzufügen, diese dann aber auch nicht mehr bearbeiten oder löschen:

![image](https://user-images.githubusercontent.com/5757594/190455198-de5c163d-23d3-4a8e-ab7d-b7fd51abb39c.png)

Workaround: Downgrade auf 4.13.8, um eine Seite anzulegen, danach wieder Update auf 4.13.9 und ich kann dann zumindest unter der neu angelegten Seite weitere Elemente anlegen. Aber das Bearbeiten von Startpunkten oder Einfügen in Startpunkten ist nicht möglich.

**Comment by leofeyer** [comment]
I can confirm this. The issue is caused by #5268. @Toflar /cc

**Comment by zoglo** [comment]
I encountered the same issue just now. Seems like this check
https://github.com/contao/contao/blob/f103b8010caeb18ddbaf8ecd3b2780da3fb04ed4/core-bundle/src/Resources/contao/drivers/DC_Table.php#L4078
causes it.

if ($this->strTable == $table && !$isVisibleRootTrailPage)

I'm unsure if it should be an OR or if it should be removed completely as it may not have worked at all <4.13.9.

Isn't it the case that we always want to show the act buttons?

**Comment by leofeyer** [comment]
Changing line 4078 will not solve the problem, no matter whether we remove the if condition or change it to OR:

<img width="490" alt="" src="https://user-images.githubusercontent.com/1192057/190570171-e2e9c879-fd12-42b4-87da-2e57d3fde265.png">

This is how it looked before #5268:

<img width="510" alt="" src="https://user-images.githubusercontent.com/1192057/190570308-32217a4a-e6db-449e-a950-c4da85600da9.png">
