### ISSUE TITLE
Add `spellcheck="false"` to password fields

### ISSUE THREAD

**Issue by kroerig** [contao/contao#5289]
### Description

Hallo,

beim Kollegen Günter Born bin ich auf folgenden Artikel gestoßen: https://www.borncity.com/blog/2022/09/19/chrome-edge-senden-persnliche-daten-u-a-passwrter-an-google-bzw-microsoft/

Wäre es daher nicht sinnvoll, zumindest die von Contao mitgelieferten Formularfelder mit dem Attribut `spellcheck=false` auszustatten?

Klaus

**Comment by fritzmg** [comment]
There is no spellcheck for `<input type="password">`. Thus the title of the article is clickbait.

**Comment by kroerig** [comment]
Aber wie man in dem Video sieht, wird der Inhalt des Feldes übertragen. Das dürfte daran liegen, dass die Funktion "Passwort anzeigen" den Typ auf "Text" ändert und dann würde das Attribut greifen. So steht es auch im Artikel. Die Überschrift ist zwar reißerisch, aber dennoch richtig.

Es würde da vermutlich schon genügen im Formulardesigner eine Option für dieses Attribut bereitzustellen. Dann kann man schützenswerte Felder damit ausstatten.

**Comment by fritzmg** [comment]
In my opinion this is a pure browser issue and should be fixed there accordingly.

**Comment by kroerig** [comment]
Ähm, nein. Das ist eine günschte Funktion. Sofern der Anwender die erweiterte Rechtschreibprüfung aktiviert.

**Comment by fritzmg** [comment]
Ah I think I misunderstood what you meant. Yes I think it makes sense that our "show password" toggle should also add the `spellcheck="false"` attribute. @contao/developers wdyt?

**Comment by kroerig** [comment]
Aber nicht nur beim Passwort-Toggle. Auch andere Felder in Formularen können sensible Informationen enthalten, die man nicht an Systeme von Google oder Microsoft übermitteln sollte. Daher sollten alle unterstützen Felder im Formulardesinger eine Option für `spellcheck` erhalten.

**Comment by fritzmg** [comment]
Yes an _option_ - but it should not be forced for every field.

Btw. you can implement this in your Contao setup yourself with just DCA adjustments, as the `spellcheck` attribute is already supported by `Contao\Widget`:

```php
// contao/dca/tl_form_field.php
use Contao\CoreBundle\DataContainer\PaletteManipulator;

$GLOBALS['TL_DCA']['tl_form_field']['fields']['spellcheck'] = [
    'label' => ['Spellcheck', 'Enable or disable the browser spellcheck on this field.'],
    'inputType' => 'select',
    'options' => [
        'true' => 'Enable',
        'false' => 'Disable',
    ],
    'eval' => ['tl_class' => 'w50', 'includeBlankOption' => true],
    'sql' => ['type' => 'string', 'length' => 5, 'default' => null, 'notnull' => false],
];

PaletteManipulator::create()
    ->addField('spellcheck', 'expert_legend', PaletteManipulator::POSITION_APPEND)
    ->applyToPalette('text', 'tl_form_field')
    ->applyToPalette('textarea', 'tl_form_field')
;
```

**Comment by asaage** [comment]
🙈 isn't that a misconception in the spec or the spellchecker?
If spellcheck is not set it should never be treated as true.
I think that if a user enables such a spellchecker not only ```tl_form_field``` in the FE is affected but also every rte-field in the BE.
Who knows what else...?

**Comment by fritzmg** [comment]
> If spellcheck is not set it should never be treated as true.

The `spellcheck` attribute is only a _hint_ for the browser.

> I think that if a user enables such a spellchecker not only tl_form_field in the FE is affected but also every rte-field in the BE.

What exactly do you mean?

**Comment by asaage** [comment]
I dont know exactly how it's implemented in chrome but you get a clear message if you activate it.
![image](https://user-images.githubusercontent.com/4138336/191009243-516b246c-2191-4258-8191-14a5bbca458f.png)
I guess that happens on the fly and there might be other BrowserAddOns out there.
One has to rely on that third-party to respect ```spellcheck="false"``` anyway.

**Comment by m-vo** [comment]
I'd second https://github.com/contao/contao/issues/5289#issuecomment-1250847684 and only `spellcheck="false"` to the show-password toggle thing. Because there it is semantically a `type="password"` and just turned into a `type="text"` to display the content. 

Like @asaage pointed out, the warning is clear and IMHO the CMS should not interfere with this.
