### ISSUE TITLE
Insert-Tag {{insert_content}} ignoriert invisible flag

### ISSUE THREAD

**Issue by ghost** [contao/contao#5295]
### Affected version(s)

5.0.X

### Description

Bei Verwendung des insert_content Tags wird das referenzierte Content Element im Frontend immer angezeigt, auch wenn dieses auf invisible gesetzt wurde.
In Contao 4.13.X war das Verhalten noch wie erwartet.

**Comment by ausi** [comment]
For legacy content elements the visibility is checked here: https://github.com/contao/contao/blob/6646d850737f9f718a296a3e952552e171512f84/core-bundle/contao/elements/ContentElement.php#L239

But this seems to be missing from the `AbstractContentElementController`.
We’d also like to discuss if this should be handled from the outside (compositor) or the inside (controller).

Controller content elements in Contao 4.13 seem to be affected here too.

Related issue: https://github.com/contao/contao/pull/4407

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to check `isVisible` in the `ContentProxy` class in 4.9 and implement #4407 in version 5.1 but only for article content elements.
