### ISSUE TITLE
Create Twig Template - Duplicate directories

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#5297]
### Affected version(s)

5.0.2

### Description

When creating a new Twig template, it is possible to select an existing subfolder by mistake, which leads to duplicate entries (see Step III).

Step I:
![image](https://user-images.githubusercontent.com/7679799/191295426-0508b0ec-565e-4650-baad-6e5f6342ecd9.png)

Step II:
![image](https://user-images.githubusercontent.com/7679799/191296267-4f89b72e-bdc1-49e8-b89e-fe530d9070d8.png)

Step III:
![image](https://user-images.githubusercontent.com/7679799/191295975-34c72fc7-509f-4fe3-822d-857dd29d3ac2.png)

**Comment by m-vo** [comment]
That's not a bug though, is it?

**Comment by fkaminski** [comment]
that's the question :innocent:

**Comment by m-vo** [comment]
Well, it's definitively not a bug. :smile:  We can discuss how to improve things in upcoming versions in #5223.

**Comment by fkaminski** [comment]
So - since you already mentioned this in #5223 i'll close this here
