### ISSUE TITLE
Recognition of own Twig templates

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#5299]
### Description

In the template selection, you could clearly identify your own templates so far (not only the variants).

![lts-template-select](https://user-images.githubusercontent.com/7679799/191451569-7f5b5565-44eb-48c2-907d-407c51aab43a.png)

It would be helpful in Contao 5 to mark this for the twig templates as well (with an additional identifier like "global").

![5-template-select](https://user-images.githubusercontent.com/7679799/191451784-a233b1f3-6824-40d7-a47f-79d61b76828a.png)

**Comment by leofeyer** [comment]
@m-vo Is this a bug or a feature?

**Comment by m-vo** [comment]
The names in the dropdown are unique - what's the benefit of adding anything to it in parentheses? I'd even remove the `(Standard)` to be honest.

**Comment by fkaminski** [comment]
True, with Twig you can see from the name that it is a standard template. 
But with the further addition you could recognize a customized template so far (from the template/theme directory) immediately.

**Comment by m-vo** [comment]
From a technical standpoint, it's no problem to show all sources of a template's chain (e.g. `Theme foo, Global, VendorBarBundle, ContaoCoreBundle`) but my concern is that this might be too much information. 

I'm currently writing a template finder service that'll replace the current logic - I'll probably at least give it a shot I think.

**Comment by m-vo** [comment]
This could be the outcome (obviously here as a test, then rendered as the real dropdown):

![image](https://user-images.githubusercontent.com/5305677/192247692-917dc2d6-8ce4-4854-9a29-16b2bbfd7c80.png)

Note, that the theme part is only available if the theme is known when searching. So likely not in the back end if we do not find a way to tag/identify things as a theme.

/cc @Toflar @ausi Any thoughts/ideas?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to postpone the discussion until #5315 has been backported.

Edit: See https://github.com/contao/contao/pull/5619

**Comment by leofeyer** [comment]
@fkaminski Now that #5315 has been backported, has the problem been resolved?

**Comment by fkaminski** [comment]
Thanks - Close it for cleanup.
