### ISSUE TITLE
Mobilansicht im Backend > Navigation verschwindet

### ISSUE THREAD

**Issue by exscorp** [contao/contao#5305]
### Affected version(s)

4.13 evtl. auch andere

### Description

Bei der Mobilansicht im Backend (getestet in diversen Browsern auf Android und auch auf Desktop mit DevTools) verschwindet die Topnavigation bei bestimmten Aktionen und kommt auch nicht wieder. Nur ein reload der Seite hilft.

Ist in der Contao Demo reproduzierbar, z. B. das Profil aufmachen und dann auf das Contao-Logo klicken. 
Das selbe passiert auch beim den Funktionen **Alle umschalten** oder **Zürück**. 

https://user-images.githubusercontent.com/3008649/191732762-a9f64d2d-c381-43a8-aeb8-7d6086c0c00c.mp4

**Comment by leofeyer** [comment]
@ausi Any idea why this is?

**Comment by ausi** [comment]
I think it is because this code does not get executed: https://github.com/contao/contao/blob/678bc53e46bc65c0c08214a4200743b15323d24d/core-bundle/src/Resources/contao/themes/flexible/hover.js#L272 we should probably remove this check: https://github.com/contao/contao/blob/678bc53e46bc65c0c08214a4200743b15323d24d/core-bundle/src/Resources/contao/themes/flexible/hover.js#L248

**Comment by leofeyer** [comment]
@exscorp Can you please verify that the changes from #5445 fix your issue?

**Comment by exscorp** [comment]
Der Fehler besteht immer noch. Sowie @ausi schreibt, wird die class "down" nicht entfernt bzw. beim klick auf das Logo (und anderen Funktionen s.o.) wird diese class gesetzt, was keinen Sinn macht.

Ich habe in der main.css folgendes css entfernt, dann tritt der Fehler nicht auf.

https://github.com/contao/contao/blob/0bde27d5f52b343da0419e741c197bc64a09d960/core-bundle/src/Resources/contao/themes/flexible/main.css#L2193-L2196

**Comment by exscorp** [comment]
Hier noch ein kurzes Video aus der Contao Demo. Beim klick auf das Logo wird die class "down" gesetzt".


https://user-images.githubusercontent.com/3008649/198566012-18eed511-31f8-40a5-a686-de5b6c95befd.mp4

**Comment by fritzmg** [comment]
@exscorp the demo does not have the fix yet. Did you test the changes from the PR?

**Comment by exscorp** [comment]
Ja habe die Änderungen aus dem PR getestet. Oder funktioniert die Änderung bei euch?

Das Video aus der Demo bezieht sich auf die gesetzte "down" class, passiert auch mit den Änderungen aus dem PR.

**Comment by leofeyer** [comment]
Die Änderungen in #5445 sollten dafür sorgen, dass diese Klasse beim Hochscrollen wieder entfernt wird.

**Comment by ausi** [comment]
Ich habe eine neue Änderung vorgeschlagen: https://github.com/contao/contao/pull/5445#issuecomment-1294871949
Dieser Fix hat in meinen tests das Problem behoben.

**Comment by exscorp** [comment]
Kann ich bestätigen das es jetzt funktioniert aber nur auf touch Geräten. 
Könnte man diese Abfrage nicht auf "touch" sondern "Fensterbreite" abfragen?

Wenn man das Browserfenster zusammenzieht bis zu dem Punkt wo nur die Icons in der Navi angezeigt werden, ist dieser Bug noch vorhanden. Sobald man in den Toggle Device (DevTools) Modus wechselt, dann funktioniert es richtig.

**Comment by ausi** [comment]
> Wenn man das Browserfenster zusammenzieht bis zu dem Punkt wo nur die Icons in der Navi angezeigt werden, ist dieser Bug noch vorhanden.

Das kann ich nicht reproduzieren.

**Comment by exscorp** [comment]
> Das kann ich nicht reproduzieren.

Browserfester ohne DevTools

**Comment by ausi** [comment]
> Browserfester ohne DevTools

Auch im Inkognito-Modus? (Um sicherzustellen dass es nicht am alten JavaScript im Browser-Cache liegt)

**Comment by exscorp** [comment]
Ja, weil es nur auf "touch" im script prüft. Hier ein Video dazu:

https://user-images.githubusercontent.com/3008649/198583046-e1422ade-0d89-4db8-959b-45799e46d684.mp4

**Comment by ausi** [comment]
Das Video zeigt eine falsche Contao-Version. Du musst die Version aus #5445 testen die den Fix enthält.

**Comment by exscorp** [comment]
Ja, der fix funktionert.

Falsche Version habe ich nicht. Die Änderungen habe ich local, manuell gemacht und beim zweiten Test hatte ich noch diese Zeile drin `if (!('ontouchmove' in window)) return;` . Habe diese jetzt auch gelöscht und alles funktioniert wunderbar.
