### ISSUE TITLE
Password validation inactive in BackendPassword controller

### ISSUE THREAD

**Issue by AlexanderWillner** [contao/contao#5316]
### Affected version(s)

4.13.10

### Description

As described in https://github.com/terminal42/contao-password-validation/issues/3 and addressed in https://github.com/contao/contao/pull/2190 password validation in the backend doesn't work. I offered to rebase the Pull Request in https://github.com/contao/contao/pull/2190#issuecomment-1255949902 - not sure how to proceed here.

**Comment by fritzmg** [comment]
> I offered to rebase the Pull Request in [#2190 (comment)](https://github.com/contao/contao/pull/2190#issuecomment-1255949902) - not sure how to proceed here.

Just create a new PR - that would never hurt ;)

**Comment by AlexanderWillner** [comment]
Would hurt if the work would never be merged ;)

**Comment by fritzmg** [comment]
There is a zero chance of something getting merged if there is no PR in the first place. Thus your best bet is always to create a PR.

**Comment by AlexanderWillner** [comment]
Misunderstanding, there *is* already a PR. Anyways, I'll update the existing PR and we'll see how far we get ;)

**Comment by fritzmg** [comment]
> Misunderstanding, there _is_ already a PR.

Yes, but the original author is not updating it anymore it seems.

**Comment by AlexanderWillner** [comment]
Isn't this still open until #5339 or #5415 got merged?

**Comment by aschempp** [comment]
we usually close issues when a pull request is made, simple because there is another place to keep track of the issue 😊
