### ISSUE TITLE
No double aliases with multi domain installation

### ISSUE THREAD

**Issue by mapfei** [contao/contao#5322]
### Affected version(s)

4.13.10

### Description

In a multi-domain installation, all website roots must be assigned a domain, otherwise the same aliases cannot be used.

**Comment by bytehead** [comment]
I can copy this (apart from the alias `index`). There were also URL prefixes for different languages configured. /cc @aschempp

**Comment by fritzmg** [comment]
> In a multi-domain installation, all website roots must be assigned a domain, otherwise the same aliases cannot be used.

That's normal. But you should clarify your use case that you posted on the forum in more detail.
