### ISSUE TITLE
Github used by information 

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#535]
The Github used by feature shows invalid information because in the `package.json` the name is set to `core-bundle`. Apart from the fact that Github probably should implement a better way to indentify packages, the package name could also be improved by Contao.

My suggestion `@contao/contao`.

https://github.com/contao/contao/blob/2fba9dc85858dc0f7e64631c84b795852f4ff362/package.json#L2

**Comment by ausi** [comment]
Can’t we remove the `name` field completely?

And/or add `"private": true`?

**Comment by leofeyer** [comment]
Fixed in 01ee272987adfdd4e2ea4c36a82c1588f6a508b8.
