### ISSUE TITLE
Site Structure Language Field using POSIX format is undocumented

### ISSUE THREAD

**Issue by asconsulting** [contao/contao#5356]
### Affected version(s)

4.13

### Description

The language field in tl_page uses a POSIX format, that differs from the language local in previous versions. This change is not documented in Upgrade.md. This makes it counter intuitive to developers who want to use the language rgxp, which previously would have matched that field.

**Comment by leofeyer** [comment]
@asconsulting Can you provide a pull request that makes the necessary changes?
