### ISSUE TITLE
Insert Tags are replaced in the back end preview

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#5357]
### Affected version(s)

5.0

### Description

Currently in Contao 5 insert tags are replaced for the content element preview in the back end, which was not the case in Contao 4.

This was actually also an issue in Contao 4, but only for Fragment Controllers that used `FrontendTemplate::getResponse`. This seems to have never been actually fixed there - but as a workaround you could use `return new Response($template->parse())` in Contao 4.

However, this is not possible in Contao 5 anymore. In Contao 5 you _must_ use `FrontendTemplate::getResponse()` - which will always replace the insert tags.

This is unfortunately a recurring topic. However, since there are no known _breaking_ issue right now the only question is: is it correct that insert tags are replaced for the back end preview of content elements? (see also https://github.com/contao/contao/issues/2859 for example where we deliberately did _not_ want to replace insert tags in the back end)

**Comment by leofeyer** [comment]
>  is it correct that insert tags are replaced for the back end preview of content elements?

IMHO not. They should be rendered as insert tags in the preview.

**Comment by ausi** [comment]
This is handled by the twig templates for the new content elements I think.

Maybe we should use something like `{{ (as_editor_view ? text : text|insert_tag)|raw }}` in the default templates?
Some elements do that already like the HTML element for example.

**Comment by fritzmg** [comment]
But it still makes compatibility accross Contao 4 and 5 more difficult. e.g. if you use a Fragment Controller in Contao 4.9 - but want to stay compatible with Contao 5, then you would need to switch to `$template->getResponse()`, which will then replace the insert tags in the back end again.

**Comment by ausi** [comment]
> In Contao 5 you _must_ use `FrontendTemplate::getResponse()` - which will always replace the insert tags.

It would only replace the insert tags in Contao 4, right?
But I see, that this is then bad for being compatible with 4 and 5.

**Comment by fritzmg** [comment]
> It would only replace the insert tags in Contao 4, right?

No, they are replaced in Contao 5 as well - for Contao PHP templates at least.

**Comment by ausi** [comment]
I see, we should add a check for the backend scope here then I think:

https://github.com/contao/contao/blob/fe1e9e02b88c3d5ef950a3ec50504428d271b872/core-bundle/contao/library/Contao/TemplateInheritance.php#L145-L149

**Comment by fritzmg** [comment]
We discussed that before (including for 4.9+) - but I think we were against that for some reason 🤔

**Comment by ausi** [comment]
> We discussed that before (including for 4.9+) - but I think we were against that for some reason 🤔

But this code only exists in Contao 5 (as we reverted #3622 for 4.13)

**Comment by fritzmg** [comment]
I mean checking the scope.

The code you are referring to was introduced in Contao 5, yes. But it only changes that insert tags are replaced for _every_ front end template parse call and not just for `fe_page` and fragment templates, making it more granular.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add the scope check to the `TemplateInheritance` trait to be able to distinguish between `.html5` templates and `.twig` templates. Then the old templates can behave consistently in Contao 4 and 5.

**Comment by ausi** [comment]
See #5441
