### ISSUE TITLE
Artikel kopieren und einfügen Fehlermeldung

### ISSUE THREAD

**Issue by green-pixelbox** [contao/contao#5360]
### Affected version(s)

4.13.11

### Description

Wenn man einen Artikel kopiert und den dann in einer Seite einfügt erscheint eine Fehlermeldung "Function name must be a string". Geht man dann im Browser zurück, erscheint der Artikel in grau

**Comment by fritzmg** [comment]
Use the debug mode and post the stack trace.

**Comment by green-pixelbox** [comment]
Error:
Function name must be a string

  at vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:1111
  at Contao\DC_Table->copyChilds()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:940)
  at Contao\DC_Table->copy()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:667)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:44)
  at require('/srv/www/schulte-goebel/public/contao413/web/index.php')
     (web/app.php:13)

**Comment by fritzmg** [comment]
It's a regression introduced by https://github.com/contao/contao/pull/5318
Can you please test if https://github.com/contao/contao/pull/5361 fixes your issue?

**Comment by green-pixelbox** [comment]
yes :) thank you
