### ISSUE TITLE
image.html5: Missing template options

### ISSUE THREAD

**Issue by a-v-l** [contao/contao#5367]
### Affected version(s)

4.13

### Description

As stated in the documentation for the [IMAGE STUDIO](https://docs.contao.org/dev/framework/image-processing/image-studio/) options can be set by either using the method `setOptions` or within the template by setting the options array:

```php
$this->figure('path/to/my/image.png', '_my_size', 
   ['options' => ['attr' => ['class' => 'logo-container']]]
)
```

Setting `'attr' => ['class' => 'logo-container']` has no effect whatsoever. In [image.html5](https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/templates/image/image.html5#L2) the `attr` property of the rendered Contao\CoreBundle\Image\Studio\Figure object is not present:

```html
<figure class="image_container<?= $this->floatClass ?>"<?php if ($this->margin): ?> style="<?= $this->margin ?>"<?php endif; ?>>
```

Dirty workaround (as `floatClass` is present in image.html5):
```php
$this->figure('path/to/my/image.png', '_my_size', 
   ['options' => ['floatClass' => ' logo-container']]
)
```

Looking at the new [twig template](https://github.com/contao/contao/blob/5.x/core-bundle/templates/Image/Studio/_macros.html.twig) this problem is solved in Contao 5. But maybe it would be good to change the example in the documentation?

**Comment by leofeyer** [comment]
@m-vo /cc

**Comment by m-vo** [comment]
Yes this is a known limitation for the legacy template. If you need this, you can either adjust the template, use the image macros (available since 4.10) or directly use the modern Twig version available from 5.0.

I agree that we should probably improve the documentation. Would you be able to make a PR?

**Comment by m-vo** [comment]
(Or we could adjust the legacy template in 4.13, but IIRC we decided against this the last time this issue came up.)

**Comment by fkaminski** [comment]
Maybe the documentation PR »[List core twig function and filter #1087](https://github.com/contao/docs/pull/1087/files?short_path=fba03aa#diff-fba03aa418e36f4e35229ab0620f6cbaebe23075fe70674779e76bdd9561be8e)« (draft) would be the appropriate place for this.

**Comment by leofeyer** [comment]
<img width="717" alt="" src="https://user-images.githubusercontent.com/1192057/207096113-422ca7a2-5f94-4b8e-a5bb-3468b6100316.png">

@ausi Should we do this, too?

**Comment by ausi** [comment]
I think I’d be in favor of it, WDYT @m-vo ?

**Comment by m-vo** [comment]
But then all attributes not only the class, no? Like [here](https://github.com/contao/contao/blob/5.x/core-bundle/contao/templates/_new/component/_figure.html.twig#L33-L37) in the new version.

**Comment by leofeyer** [comment]
Except we have no way to build the figure attributes string in the old template, so we would have to pre-build it in the `Figure` class as we do with the link attributes:

https://github.com/contao/contao/blob/2aadd06365c46314267b42f1c0fc1354c543c9d5/core-bundle/src/Image/Studio/Figure.php#L325-L331

**Comment by ausi** [comment]
Reading over this again I’m not sure if we should implement this. If we add support for `attr` we’d consistently also have to support `link_attr`, `picture_attr`, `source_attr`, `img_attr` and `caption_attr` which is way to complicated IMO.

The documentation now says: *These options won’t be processed and are intended to ship parameters to the template. If you are using the Image Studio’s twig templates, you might for instance want to pass a HTML class: `['attr' => ['class' => 'my_figure']]`*

So it is already noted that this does only work with the twig templates.

**Comment by fritzmg** [comment]
But I would argue that wanting to add a CSS class on the `<figure>` container is the most common use case - and the current way of doing it (for HTML5 templates) via the `floatClass` template variable (without adjusting the `image` template) is pretty terrible, as you can't even use the Figure Builder for that.

**Comment by ausi** [comment]
How about adding a special case only for `['attr']['class']` after: https://github.com/contao/contao/blob/d428d705a30fa0a6c81a39f90a21a19b2f7f0de1/core-bundle/src/Image/Studio/Figure.php#L349-L351 like so:

```php
if (isset($this->getOptions()['attr']['class'])) {
    $templateData['floatClass'] = ($templateData['floatClass'] ?? '').' '.$this->getOptions()['attr']['class'];
}
```

The most common use case would then work out of the box, even with exiting templates (as they would already have the `floatClass`).

**Comment by leofeyer** [comment]
As discussed in the call, we want to implement @ausi‘s [suggestion](https://github.com/contao/contao/issues/5367#issuecomment-1493365090).

**Comment by a-v-l** [comment]
> As discussed in the call, we want to implement @ausi‘s [suggestion](https://github.com/contao/contao/issues/5367#issuecomment-1493365090).

Do you want me to make a pull request or will @ausi take care of this?

**Comment by ausi** [comment]
> Do you want me to make a pull request

Yes please.

**Comment by a-v-l** [comment]
Sorry about https://github.com/a-v-l/contao/commit/6f087a9ec2407cd79ced2282411d6962c31b30b1: I accidentally selected the wrong branch (5.x).
