### ISSUE TITLE
Neues Contentelement: Definitionsliste

### ISSUE THREAD

**Issue by ghost** [contao/contao#5374]
Ich möchte ein neues CE vorschlagen: eine Definitionsliste, also eine Erweiterung des ce_list um jeweils ein Feld (siehe auch: http://de.selfhtml.org/html/text/listen.htm#definition).
Damit wäre es Möglich, schnell ein paar Wertepaar anzugeben ohne extra eine Tabelle formatieren zu müssen.
_Beispiele:_
Max Mustermann | 1. Vorsitzender
Hans Mustermann | 2. Vorsitzender ...
_oder_
Ort | Simcity
Strasse | Neuestrasse ...

MfG, artemis

--- _Originally created by artemis on July 15th, 2009, at 07:07pm (ID 886)_

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5424
