### ISSUE TITLE
Länger anhaltender Zwischenspeicher für Kopieren bei "Mehrere Bearbeiten"

### ISSUE THREAD

**Issue by NinaG** [contao/contao#5377]
Wenn ich z. B. 3 Seiten habe, die ich in der Seitenstruktur an mehrere Stellen kopieren möchte, muss ich auf "mehrere bearbeiten" klicken, die Seiten auswählen, dann auf Kopieren klicken und die Seiten an der Zielstelle einfügen. Sobald das gemacht wurde, leert sich der "Zwischenspeicher" und ich muss den gesamten Vorgang nochmal wiederholen, wenn ich die gleichen 3 Seiten auch nochmal an eine andere Stelle kopieren will.

Ich habe hier gerade einen Fall wo ich 8 gleich benannte Seiten (mit identischen Voreinstellungen in Bezug auf Seitenlayout, Schutz, etc.) jeweils als Unterseiten von 20 Hauptseiten anlegen muss. Da der Speicher der "mehrere bearbeiten"-Funktion immer nur für einen Kopiervorgang reicht, muss ich nach jedem Vorgang den gesamten Ablauf wiederholen: 
- auf "mehrere bearbeiten" klicken, 
- die Seiten auswählen, 
- dann auf den Button "Kopieren" klicken und 
- die Seiten an der Zielstelle einfügen. 

Sobald das gemacht wurde, leert sich der "Zwischenspeicher" und ich muss den gesamten Vorgang nochmal wiederholen, wenn ich die gleichen Seiten auch nochmal an eine andere Stelle kopieren will. Das ist sehr mühsam und frustrierend.

Ich würde mir daher einen Button nach dem Schema "Kopieren und für weiteres Kopieren in der Ablage behalten" wünschen. So könnte ich dann die Seiten an der Zielstelle einbinden und würde dann unmittelbar wieder mit den Einfügesymbolen begrüßt werden, so dass ich sie an der nächsten Stelle einbinden kann, usw. Wenn es mir reicht, könnte ich den Vorgang durch den bekannten Link "Ablage leeren" beenden.

Related issues: contao/core#2871

--- _Originally created on November 24th, 2010, at 10:59am (ID 2692)_

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5417
