### ISSUE TITLE
BE-Feature: Reverse and column sorting

### ISSUE THREAD

**Issue by ben-eSM** [contao/contao#5383]
At this point, Contao only offers the functionality to sort either ascending or descending as defined in the DCA. It would be a nice feature if the user could reverse the sorting. Especially  for tables sorted by date, clients are often asking whether it's possible to reverse the sorting sometimes.

Furthermore, I think it would be a nice feature and an improvement regarding the user experience if table columns (`showColumns => true`) would be clickable to change the sort by field. It's a feature, the people know from their operating system.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5425
