### ISSUE TITLE
Add contextual help in the form module on the FE

### ISSUE THREAD

**Issue by ghost** [contao/contao#5384]
It would be interesting and useful for visitors to be able to explain how to fill a field in a form.

However, it is not possible to add a caption / help in the BE, for display in the FE.

I think we should add an extra field in the BE, type "help - give additional information on how your visitors must complete the field"

The idea is to come up with something like this: "please enter a valid address."

![image 1](https://f.cloud.github.com/assets/3490680/773811/96c30454-e943-11e2-80e8-5b366ff6275a.jpg)

A +

**Comment by asaage** [comment]
From 2013?

I would argue that's what the placeholder attribute is for.
For more "Erklärungsbedarf" use the explanation-widget. It doesn't really belong to a specific input but could be tweaked with css to achive something like above.
We have serverside validation where errormessages can't easily be adjusted.
If there was a **title=""** and  **pattern=""** attribute for input types that could make client-side messages a little more customizable. *(his might interfere with existing validations)
See: https://www.youtube.com/watch?v=s2ThIxm7FyA

**Comment by aschempp** [comment]
I would vote to close this since this is clearly not part of any standard HTML and therefore should not be a default feature in our HTML forms.
