### ISSUE TITLE
Make forms optional instead of required

### ISSUE THREAD

**Issue by marcobiedermann** [contao/contao#5387]
For better UX, I recommend to change the form fields from being mandatory fields to optional fields.
The default should be required.
http://uxmovement.com/forms/always-mark-optional-form-fields-not-required-ones/

**Comment by ausi** [comment]
I don’t think we should change the logic of the form generator here. You can mark optional fields via placeholder or add an “(optional)” to the label and still mark fields as required. 
What actually is better UX highly depends on the individual form.

**Comment by aschempp** [comment]
I fully agree with @ausi and would vote to close this issue.

**Comment by leofeyer** [comment]
I actually like the idea of having optional fields instead of required fields.

**Comment by asaage** [comment]
I don't get it.
First you should never mark unneccessary fields as required if you dont have to (i think that is by law § 3a BDSG).
If someboy requests that approach i'd just hide the asterisks and waste the placeholder for sth. like "optional".
If you suffer from in-your-face-red-asterisk just mute the color according to your needs or display them on focus or whatever.
I think that's a pattern everybody knows.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to keep marking required fields instead of optional ones, because the majority of the participants did not agree with the reasoning from the linked article.
