### ISSUE TITLE
Link „Alle umschalten“  - Status für Screenreader nicht erkennbar

### ISSUE THREAD

**Issue by NinaG** [contao/contao#5392]
Ähnlich wie in Ticket contao/contao#5393  können assistive Technologien wie Screenreader auch beim Link „Alle umschalten“ nicht erkennen, welcher Zustand (geöffnet/geschlossen) gerade aktiv ist. Die Nutzer müssten also zum nachfolgenden Tree View wechseln, dort nachschauen und dann ggf wieder zurücktabben. Möglich, aber ziemlich nervig.

**Comment by NinaG** [comment]
Die beste Lösung wäre, dass sich der Linktext je nach Zustand ändert. Derzeit ist der Linktext immer "Alle umschalten". Besser wäre es, wenn der Text je nach Zustand "Alle öffnen" oder "Alle schließen" heißen würde. Simple Lösung, die die Sache sofort für Screenreader-Nutzer (und auch sonstige Nutzer) eindeutiger macht.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5416
