### ISSUE TITLE
Statusunterscheidung Funktionsicon Veröffentlichen/Nicht veröffentlichen + Hervorheben/Zurücksetzen nicht möglich

### ISSUE THREAD

**Issue by NinaG** [contao/contao#5393]
In den Listenansichten können assistive Technologien wie Screenreader bei den Funktionsicons nicht ausgeben, welchen Status der Datensatz bei umschaltbaren Funktionen hat. Das betrifft:

- Veröffentlichen/Nicht veröffentlichen
- Hervorheben/Zurücksetzen

Die Nutzer könnten zwar in die Einstellungen des Datensatzes wechseln und dort den jeweiligen Zustand herausfinden, aber das ist insbesondere für Screenreader-Nutzer ein sehr großer Aufwand und völlig unpraktibel, wenn sie ordentlich redaktionell arbeiten wollen. Versucht einfach mal selbst in einer Liste mit z.B. mehreren hundert Seiten/Unterseiten herauszufinden, welche Seiten noch unveröffentlicht sind, wenn ihr das nur tun könnt, indem ihr jede einzelne Seite/Unterseite erst bearbeitet und euch dort bis zum Abschnitt (per Tastatur) durchangelt, an dem - am Ende - gesagt wird, ob die Seite veröffentlicht/unveröffentlicht ist. Es ist schon ein ordentlicher Aufwand, das auf einer großen Seite über die Icons auf der Listenansicht herauszufinden, aber wenn die Redakteure zusätzlich noch in die Details gehen jeder Seite gehen müssten, wird es undurchführbar.

**Comment by leofeyer** [comment]
Lösungsvorschlag?

**Comment by NinaG** [comment]
Im Prinzip wäre es einfach sinnvoll, dass je nach Zustand der Text angepasst wird.

In der Seitenstruktur lautet der ALT-Text des Icons derzeit immer "Seite veröffentlichen/unveröffentlichen". Eindeutig wäre es, wenn er je nach Zustand "Seite veröffentlichen" oder "Seite unveröffentlichen" heißen würde.

Dito bei Hervorheben/Zurücksetzen.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5419
