### ISSUE TITLE
Fehlende Alternativtexte in Dateiverwaltung

### ISSUE THREAD

**Issue by NinaG** [contao/contao#5394]
Aus dem aktuellen Barrierefreiheit-Test, den Heiko Kunert und ich mit der aktuellsten Contao 4-Version durchgeführt haben:

In der Dateiverwaltung haben die Icons für Ordner (folderC.svg) und Dateien (z.B. iconPLAIN.svg) keine Alternativtexte. Dadurch wird Screenreadern der Dateiname vorgelesen. Es wäre gut, wenn hier die korrekten Alternativtexte vergeben werden, damit sehbehinderte und blinde Nutzer auch wissen, ob sie einen Ordner oder eine Datei vor sich haben (und bei letzterem welcher Typ).

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5409
