### ISSUE TITLE
CE Tabelle: Die Symbole in den Buttons haben keine Alternativtexte

### ISSUE THREAD

**Issue by NinaG** [contao/contao#5396]
Beim Tabellen-Wizard gibt es die Buttons mit denen man Spalten duplizieren/verschieben/löschen und Reihen duplizieren/verschieben/löschen kann. Leider wurde nur den Buttons jeweils ein title-Attribut zugewiesen, während die Symbole darin keinen Alternativtext haben. Wie schon in anderen Tickets erläutert, wird das title-Attribut vielen Screenreader-Nutzern nicht ausgegeben. Daher sollte der Alternativtext bei den Symbolen umbedingt gesetzt werden.

Bitte ergänzt die Alternativtexte bei den Symbolen für Screenreader-Nutzer (kann der identische Text sein, wie das title-Attribut auf dem umhüllenden Button).

**Comment by fiedsch** [comment]
Hast Du das falsche Ticket referenziert? In #90e106f sehe ich keinen Bezug zu @NinaG's Ticket.

**Comment by leofeyer** [comment]
Das hat GitHub automatisch geschlossen wegen meines Kommentars. 🙄

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5464
