### ISSUE TITLE
comments: quotes in article-headline make submission of comment impossible

### ISSUE THREAD

**Issue by coffeincode** [contao/contao#54]
**Affected version(s)**
Contao 4.4 LTS 
Contao 4.6 (Online-Demo)

PHP 7.1

**Description**  

If you try to send a comment a news-article which has quotes in the headline the system throws an exception saying the request token is invalid. If there are no quotes no problems occur. 

Tested it in the demo system and in a live system running contao 4.4 LTS. 

**How to reproduce**  
Log in to the demo, create a news entry with quotes and try to submit a comment. 

I know that this is  not critical and that we can just use the comments with the directive not to use quotes in the article headlines if comments are allowed  but still it's a nice-to-have.

**Comment by leofeyer** [comment]
I wasn't able to reproduce this in the online demo. I have tried it with single quotes and double quotes in the news title and I was able to submit comments in both cases.

**Comment by coffeincode** [comment]
I am sorry but if I send this in the demo

![image](https://user-images.githubusercontent.com/43089826/45368320-982ba180-b5e3-11e8-9e35-c804bae86849.png)

I get this: 
![image](https://user-images.githubusercontent.com/43089826/45367889-88f82400-b5e2-11e8-98a7-6e03a831335a.png)

I can see that one comment is there but I get errors every time. Please take a second look in the demo:
https://demo.contao.org/en/news-detail/new-contao-versions-in-short-intervalls.html

tested it in Opera and in Vivaldi and in Chrome, exceptions everywhere

**Comment by leofeyer** [comment]
That's an unrelated error, which I have just fixed. Can you please try to reproduce it one more time?

**Comment by coffeincode** [comment]
Yes, now it works - thanks 👍 a LOT 😃 
Does the fix apply to Contao 4.4 too? The demo is 4.6 and our own systems run 4.4

**Comment by leofeyer** [comment]
As I said, the fix was completely unrelated.
