### ISSUE TITLE
Dateiverwaltung: Markierung wichtiger Teil des Bildes fehlerhaft

### ISSUE THREAD

**Issue by minstyle** [contao/contao#5400]
### Affected version(s)

4.13.12

### Description

Browser: Google Chrome (106.0.5249.119), Firefox 105.0.3
Betriebssystem: Windows 10

Seit dem Update auf die aktuelle Contao-Version lässt sich die Markierung des "wichtigen Teil des Bildes" nicht mit dem Mauszeiger aufheben. Wenn ich mit der Maus nur klicke um die Markierung aufzuheben, dann wird trotzdem ein Rahmen, also ein wichtiger Teil des Bildes definiert.

![image](https://user-images.githubusercontent.com/2649562/196366648-7395e4ea-69ca-4074-a081-c88876a38d81.png)

**Comment by fritzmg** [comment]
I am unable to reproduce the issue (Chrome, Firefox, Windows 10).

**Comment by minstyle** [comment]
Bei einem anderen Webprojekt mit Contao 4.13.11 der gleiche Fehler (anderer Computer, Windows 10, Chrome). Die Markierung lässt sich nicht mehr aufheben.

**Comment by leofeyer** [comment]
I can reproduce it in Safari 16.0 on macOS. @ausi Any idea what is causing this?

**Comment by ausi** [comment]
See #5437

**Comment by minstyle** [comment]
@ausi Kurze Frage: Wird es diesen Fix auch für Contao 4.13 geben? Oder nur für Contao 4.9?

**Comment by fritzmg** [comment]
4.9 wird upstream gemerged.

**Comment by minstyle** [comment]
@fritzmg Ich danke dir für die Info 👍
