### ISSUE TITLE
Frontend link broken in preview.php

### ISSUE THREAD

**Issue by aschempp** [contao/contao#541]
**Affected version(s)**
4.8

**Description**  
If the new preview.php endpoint is used, the user is forced to the back end log in page. There's a "To Frontend" link there, but it does not work. It redirects to the root page on the same entry point (`preview.php` again), which forces back to back end login.

**Comment by leofeyer** [comment]
My initial approach (adding an option to remove the `/preview.php` fragment) was probably wrong. Preview mode can only be enabled if you are logged in, sou should never be able to open the login screen in preview mode, should you?

**Comment by aschempp** [comment]
Well if you open `/preview.php` you will be redirected to the back end login screen if you do not have a valid JWT token. So that route is totally valid to me…

**Comment by leofeyer** [comment]
You should be redirected to `/contao/login` though, not to `/preview.php/contao/login`.

**Comment by leofeyer** [comment]
Fixed in bb6f4cb06f1847a62d84d296f20da62fe47edba1.
