### ISSUE TITLE
Do not show (security) warnings when a backend user change the password

### ISSUE THREAD

**Issue by AlexanderWillner** [contao/contao#5414]
### Affected version(s)

4.13.10

### Description

Steps that will reproduce the problem?
1. Enforce a password change for backend user `A`
2. Login with backend user `A`
3. Change the password

What is the expected result?
A message that the password was changed.

What happens instead?
A message that the password was changed and (security) warnings.

Possible workaround:
Set up permissions correctly to avoid these security warnings in the first place

Any additional information:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/307605/197283992-f65dd39c-d6e7-4a5c-b16a-de6cccf9825c.png">

**Comment by fritzmg** [comment]
I am unable to reproduce the issue. `tl_user::addTemplateWarning` does not get executed when being forced to change the password.

**Comment by AlexanderWillner** [comment]
Hm, interesting. I‘ve to check then why it’s popping up here. Is there some sort of „plain vanilla“ demo setup of the latest contao version available online?

**Comment by fritzmg** [comment]
https://demo.contao.org/

**Comment by leofeyer** [comment]
I cannot reproduce this, either.

**Comment by AlexanderWillner** [comment]
Indeed, not reproducible at demo.contao.org - might be related to #5316 though...
