### ISSUE TITLE
Disable 2FA on password recovery

### ISSUE THREAD

**Issue by aschempp** [contao/contao#542]
Should 2FA be disabled if a user resets his password? Otherwise he can likely still not log in…

**Comment by leofeyer** [comment]
Very good question. What happens if you request a new password for GitHub or any other service with 2FA enabled?

**Comment by Toflar** [comment]
https://security.stackexchange.com/questions/30083/if-multi-factor-authentication-is-enabled-how-should-that-affect-self-service-p

**Comment by aschempp** [comment]
Very good read! As we do not recognize devices, that means a PW reset with 2FA enabled is only ever useful if we have reset/backup codes?

**Comment by Toflar** [comment]
As long as we do not support recognizing devices, I think that's the case yes. So as of now we don't support resetting the 2FA. We'd also need to implement that for BE users anyway. Imho that's just a new feature on top of the current implementation.

**Comment by leofeyer** [comment]
I just checked how GitHub handles this. Before I can set a new password, I have to enter a 2FA code.

**Comment by aschempp** [comment]
> As we do not recognize devices

Btw, I just realized that the 2fa bundle we use actually does support trusted devices (using cookies). It's currently not enabled though.

**Comment by leofeyer** [comment]
Yes, we are trying to get all this set up in Contao 4.9 (see https://github.com/contao/contao/issues/265#issuecomment-453498815).

**Comment by leofeyer** [comment]
As discussed in Mumble on July 4th, we do not want to ask for the 2FA token during password reset. Even if an attacker sets a new password, they will not be able to log in without the 2FA token.

**Comment by richardhj** [comment]
Anything up for work? @leofeyer This is the current behavior, isn't it? Otherwise, this ticket can be marked as resolved.

**Comment by leofeyer** [comment]
I have left it open as a reminder to check again after #363 has been merged.

**Comment by leofeyer** [comment]
Resetting the password with 2FA enabled works as discussed. 👍
