### ISSUE TITLE
User insert tag throws an exception in Twig if no user is logged in

### ISSUE THREAD

**Issue by qzminski** [contao/contao#5433]
### Affected version(s)

4.13.x

### Description

I have this Twig template with a user insert tag:

```twig
<input type="email" value="{{ insert_tag('user::email') }}">
```

It results in an exception for a non-logged visitor, because the returned array in the [insert tag parser](https://github.com/contao/contao/blob/5.x/core-bundle/src/InsertTag/InsertTagParser.php#L47) is empty `[]`.

```
An exception has been thrown during the rendering of a template ("Rendering a single insert tag has to return a single raw chunk").
```

When I am logged in however, there is no error and the user's e-mail is displayed correctly.

**Comment by leofeyer** [comment]
@m-vo @ausi /cc

**Comment by ausi** [comment]
See #5438
