### ISSUE TITLE
Define the lightbox size in the image size settings

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#545]
In #529, we have added the `tl_layout.lightboxSize` field, which allows us to define an image size for lightbox images. As briefly discussed in Slack, I think that the field does not belong to the page layout and might be better placed in the content element or module where it is used.

![](https://user-images.githubusercontent.com/1192057/60576472-c4382f00-9d7d-11e9-8385-f4ce39825453.png)

**Comment by fritzmg** [comment]
Hm, but then an editor would need to do define that for _every_ content element, which, I am assuming, will largely be always the same setting.

Sure, you could define a default via your own DCA configuration. But it seems rather cumbersome.

On that note: we frequently have the use case, that consumers always want a default image size for certain section or elements. May be Contao could integrate a solution for that somehow? ;)

**Comment by Toflar** [comment]
I don't think that really makes sense. It can though but still it should work with some fallback implementation which would be fairly easy to integrate: Provide the option in the content element and if that's not there, fall back to the layout 🤷‍♂

**Comment by leofeyer** [comment]
> Hm, but then an editor would need to do define that for every content element

Just like they need to define the image size for every content element. I fail to see a difference here.

**Comment by fritzmg** [comment]
I know - most of our customers never need that though and thus it is always a default image size (or a dynamic one that we programmed). Having the lightbox image size setting for every content element is overkill in my opinion and just adds to this nuisance.

**Comment by leofeyer** [comment]
You realize that the field is only visible if the user has checked the "Full-size view" checkbox?

**Comment by asaage** [comment]
If at all It should be in **Theme->image-sizes** i think.
Maybe we could check for an entry named lightboxSize and use this otherwise fallback to Full-size - so we don't need a select there.

**Comment by m-vo** [comment]
I think people that want to have more finegrained control over a 'per theme' setting are misusing lightboxes already (UX). :wink: 

> I know - most of our customers never need that though and thus it is always a default image size (or a dynamic one that we programmed). 

I second that. That's why I'm using lots of custom elements instead of the system ones so that the element itself can decide which image sizes to pick.

We could also follow such a route (I know this is a way bigger scope than this issue but think about it):

* allow to configure everything in the CEs
* allow defining different 'base configurations' of a CE together with a new name (e.g. in the theme) where some of the fields are already filled out
* these preconfigured CEs then (also) appear in the list of CEs  

Then you could for example have the CEs 'Text with image on the left', 'Galery with huge lightbox', 'Small note'.

**Comment by ausi** [comment]
I don’t see the use case for setting the lightbox size in a content element. In 99.99% of cases this is not necessary and the 0.01% can easily extend the content element for their own needs. It is also not possible in the content element settings to select which lightbox should get used (colorbox or mediabox).

The look (CSS) and feel (JavaScript) of the lightbox is defined in the page layout and I think this is also the best place to define the size of the lightbox.

**Comment by Toflar** [comment]
I'm with @ausi here.

**Comment by leofeyer** [comment]
> It is also not possible in the content element settings to select which lightbox should get used (colorbox or mediabox).

That's true, the lightbox itself is defined in the page layout. But you can use this one lightbox in many different content elements and define multiple image sizes for the preview images. So why can we only have one fixed size for the full-size images? Makes no sense to me.

**Comment by ausi** [comment]
> So why can we only have one fixed size for the full-size images?

Because they should all be “full-size”. Just as they currently are in Contao 4.7.

The lightbox image size would mostly be used to set a maximum width/height, like `[2048, 2048, 'box']` and to configure resize options like the new skipIfDimensionsMatch flag.

**Comment by leofeyer** [comment]
There are several legit use cases for using different full-size sizes:

* I want the full-size images of gallery 1 to be 1280x720 (crop) and the ones of gallery 2 to be 1280x1280 (fit the box).
* I have a gallery that is supposed to show only the important parts of its images (thumbnails and full-size images). My other galleries shall render normally.

**Comment by asaage** [comment]
> different full-size sizes

this should definitely be called different then.
Having it on the content-element-level could be useful.

**Comment by ausi** [comment]
> There are several legit use cases for using different full-size sizes

I never came across any of those use cases in my lifetime so far, and I don’t remember any feature request for such a functionality.

I don’t say that this will never be needed in a single project, but I don’t want to bloat the settings of every content element that has the “Full-size” checkbox, just to support a use case for 0.01% of users.

>> different full-size sizes
>
> this should definitely be called different then.

It would probably be called “Lightbox image size” as you can see in the screenshot above.

**Comment by aschempp** [comment]
I don't like *Lightbox image size*. It actually is the "full size" or kinda "maximum size". If I don't enable a lightbox, the respective image will be shown in a (new) browser tab.

**Comment by leofeyer** [comment]
As discussed in Mumble on July 4th, we want to keep the lightbox settings in the page layout. Additionally, we want to move the `tl_theme.defaultImageDensities` field to `tl_layout` so we have the default image settings in the same place.

**Comment by leofeyer** [comment]
Fixed in ed1d67e8f3a9ffadcfa6c6c51d4cd0bdefdc1446.

**Comment by ThomasKettner** [comment]
I just came across this issue and like to add some thoughts that ought to be considered.

Perhaps there are not too many projects taking care about customized light-box sizes. Still there are use cases where this workflow / functionality is confusing. 
In many projects we keep original images in **unpublished folders** to prevent access from outside. The other reason for this workflow is, that we motivate editors to use the image size option. When deleting or unpublishing content elements or articles the referring images will be automatically unpublished, too. So editors need not to think about deleting the images as well. (Nearly all projects have plenty of extraneous files after a while).

The full size option is not working if the light-box size is not set in the page layout **when the file is in an unpublished folder**. As we are working with several page layouts there is always another configuration issue to think about.

It seems much more logical from an editors perspective to configure the complete image size in one place. Setting defaults could and should still be assured but this could preferably be done in the image size settings to prevent questioning and confusion at all.

Concerning the problem with unpublished folders the default setting might be to transfer the file to the assets folder in it's original size.

**Comment by fritzmg** [comment]
> Concerning the problem with unpublished folders the default setting might be to transfer the file to the assets folder in it's original size.

That is already the case if you set a lightbox image size in your page layout (unless you enabled `skip_if_dimensions_match`).

> It seems much more logical from an editors perspective to configure the complete image size in one place. 

Do you mean it should be possible to configure a default lightbox image size in the bundle configuration - and the page layout can overwrite that if desired?

**Comment by ThomasKettner** [comment]
> Do you mean it should be possible to configure a default lightbox image size in the bundle configuration - and the page layout can overwrite that if desired?

I think, the lightbox image size belongs to the image sizes editor. Here I can configure all the desired image behaviour and use this in content elements.
Fallback would be page layout if empty.

**Comment by fritzmg** [comment]
> I think, the lightbox image size belongs to the image sizes editor. Here I can configure all the desired image behaviour and use this in content elements.

In the image sizes editor you configure the image sizes. But where do you want to set the image size for lightbox images?

**Comment by ThomasKettner** [comment]
as mentioned above, in the image sizes editor.  
(of course not as a select on existing image sizes, as this would cause an endless look...)
https://github.com/contao/contao/issues/545#issuecomment-508012200

**Comment by fritzmg** [comment]
> as mentioned above, in the image sizes editor.

I don't understand. In the _image sizes editor_ you edit/create image sizes. Where do you want to be able to set the lightbox image size? Do you mean _within_ an image size?

**Comment by ThomasKettner** [comment]
> > as mentioned above, in the image sizes editor.
> 
> I don't understand. In the _image sizes editor_ you edit/create image sizes. Where do you want to be able to set the lightbox image size? Do you mean _within_ an image size?

correct!
