### ISSUE TITLE
Always optimize images even if the dimensions match

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#546]
In #529 we have added an option to optimize images even if they do not have to be resized. The option is disabled by default, which means that the original, potentially unoptimized image is used if the dimensions match. While I understand that this maintains the previous behavior, I still think we should enable the option by default. It never makes sense to use unoptimized images, does it?

**Comment by ausi** [comment]
> It never makes sense to use unoptimized images, does it?

It does, if your images are already optimized. In this case (re-)processing the image would decrease the quality and might even increase the file size.

**Comment by leofeyer** [comment]
Good point. However, experience shows that the majority of images will not be optimized, therefore I still think we should enable the option by default.

**Comment by Toflar** [comment]
There are arguments for both sides which is why it is configurable. I'd leave it as is because it makes sure there are no sudden surprises.

**Comment by leofeyer** [comment]
@ausi has suggested to enable it for all existing image sizes during the version 4.8 update (BC) but to disable it by default for new image sizes. That sounds like a good compromise to me.

**Comment by Toflar** [comment]
We can do that too, I'm okay with that.

**Comment by ausi** [comment]
Then I should probably also invert the default value in [contao/image src/ResizeOptions.php:37](https://github.com/contao/image/blob/5f1c5bea31f9b82886af647a889012f122b1fb3e/src/ResizeOptions.php#L37)

**Comment by leofeyer** [comment]
Yes please. 👍

**Comment by ausi** [comment]
Done: https://github.com/contao/image/blob/7de1bea6c17fe8584f1e742dc46bcc5053b06d69/src/ResizeOptions.php#L37

**Comment by leofeyer** [comment]
Changed in 0ad6d24830c0dc8a581bff8f411059020945ac59.
