### ISSUE TITLE
News images in reader are linked when no content elements

### ISSUE THREAD

**Issue by koertho** [contao/contao#5477]
### Affected version(s)

4.9.35, 4.13.12

### Description

Images (through singleSRC field) in news are always get linked to the news reader page. This also happens in the news reader (detail page) when no content element are available for the news article and fullsize is not set. Since we are already on the detail page, the images is linked to the current page, which is not ideal.

The problematic code: https://github.com/contao/contao/blob/a1bcee403a4fd2c6bddfcbd5106c97be66ef420c/news-bundle/src/Resources/contao/modules/ModuleNews.php#L189

Steps to reproduce:
1. Create a news reader
2. Create a news article without content elements and do not check option "fullsize" 
3. Open the news article in reader view -> the image is linked to the current page

Also discussed on slack: https://contao.slack.com/archives/CK4J0KNDB/p1667486480300469

**Comment by ausi** [comment]
Related: https://github.com/contao/news-bundle/issues/30#issuecomment-403739475

**Comment by leofeyer** [comment]
Which template are you using for the news reader module? Because the default template `news_full.html5` does not render teaser images.

**Comment by fritzmg** [comment]
> Because the default template `news_full.html5` does not render teaser images.

The default `news_full` does render teaser images: https://github.com/contao/contao/blob/b320f38f2809d5d358bcc23be432fdf9b90aef3a/news-bundle/src/Resources/contao/templates/news/news_full.html5#L22-L24

**Comment by leofeyer** [comment]
You are right. I had a text element in the news article. 🤦‍♂️
