### ISSUE TITLE
User Group Seetings too many entries

### ISSUE THREAD

**Issue by Metis77** [contao/contao#5479]
### Affected version(s)

4.13.12

### Description

Editing Contao user groups works as intended, until you need to check a lot of checkboxes.

for example with the "rocksolid" plugins and the "notificatoin center" there are too many ceckboxes.
Checking them all will not be work. saving works, but the ceckboxes that where too much, keep empty.

removing one or two already checked checkboxes above allows me to check one or two checkboxes, that where not possible before.

Adding some checkboxes above, removes the same amount of checkboxes from the bottom.

**Comment by ausi** [comment]
Probably a duplicate of #1161

**Comment by asaage** [comment]
you need to raise ```max_input_vars``` until there is a better solution

**Comment by Metis77** [comment]
indeed solved by increasing the `max_input_vars` in the php.ini.
Should we close this as duplicate of #1161?

**Comment by aschempp** [comment]
I think so, yes. Unfortunately there's nothing (easy) we can fix on our side.

**Comment by asaage** [comment]
But #1161 is a closed issue as well.?

Thoughts:

- If every panel would get it's own submit button or be placed on a separate sub-page of do=group&act=edit that should work. (but there is no UI pattern like tabs for it)
- if we could remove collapsed items from the dom and add them back on demand this could at least be configured in chunks.
- JS toggle the ```disabled``` attribute for every checkbox in a collapsed checkboxGroup...
(questionable - dont know if people expect hidden stuff to be submitted)

**Comment by fritzmg** [comment]
See https://docs.contao.org/manual/en/installation/system-requirements/#php-configuration-php-ini
