### ISSUE TITLE
Unzip ZIP files in the file manager

### ISSUE THREAD

**Issue by katgirl** [contao/contao#5480]
### Description

Due to the current wave of Google Fonts warnings we had to upload several fonts and migrate projects from Wordpress to Contao in the last weeks.
It would have helped if we had uploaded the fonts, images, ... that were delivered to us as ZIP directly to the server and unpacked them there.

**Comment by fritzmg** [comment]
If `ZipArchive` is available, it would be straight forward to implement this. However, depending on the size of the archive it could potentially take a long time and thus exceed the `max_execution_time` when extracting an archive via the web process.

**Comment by aschempp** [comment]
you're aware you can upload multiple files and folders through drag&drop in the latest Contao version?

**Comment by katgirl** [comment]
> you're aware you can upload multiple files and folders through drag&drop in the latest Contao version?

thank you, I was not aware of this
