### ISSUE TITLE
PHP 8: Warning: Undefined array key "inputType" in ModulePersonalData.php

### ISSUE THREAD

**Issue by AlexanderWillner** [contao/contao#5481]
### Affected version(s)

4.13.12

### Description

Version: PHP 8.x

Steps that will reproduce the problem?
1. Login as a login user
2. Show personal data

What is the expected result?
Show the personal data

What happens instead?
`Warning: Undefined array key "inputType"` in https://github.com/contao/contao/blob/c79ab75e51aee332a28822923adc70603d0b0872/core-bundle/src/Resources/contao/modules/ModulePersonalData.php#L141

Possible workaround:
```php
$strClass = $GLOBALS['TL_FFL'][($arrData['inputType'] ?? null)] ?? null;
```

Any additional information:
n/a

**Comment by aschempp** [comment]
did you adjust your `tl_member` DCA?

**Comment by AlexanderWillner** [comment]
Very likely. I've a number of shop instances here with many modifications/modules/themes/... and identified a couple of PHP 8 related issues in Contao Core similar to this one (i.e., non-checked array keys).

**Comment by fritzmg** [comment]
Then it needs to be fixed there, not in the core. You must not set a field to editable, if it does not have an `inputType` defined.

**Comment by AlexanderWillner** [comment]
Okay, if this is a deliberate design choice - I should debug more on the caller side anyways.

But I assumed that a core framework should be as resilient/robust as possible to input, i.e. not throw exceptions on unexpected input. That's what this proposal is about, and there are a few other places where exceptions are thrown in Contao Core with PHP 8 when running more complex/modified/non-trivial installations - or with erroneous modifications if you will ;)

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5518
