### ISSUE TITLE
Editing of multiple image files caught an error "Argument #2 ($field) must be of type string, null given"

### ISSUE THREAD

**Issue by marcfunkDE** [contao/contao#5482]
### Affected version(s)

5.0.4
PHP 8.1.7

### Description

`Internal Server Error
Was ist das Problem?
Contao\DataContainer::isFieldExcluded(): Argument #2 ($field) must be of type string, null given, called in /www/htdocs/xxx/vendor/contao/core-bundle/contao/drivers/DC_Folder.php on line 1730`

File structure:
img/kunst/

I selected multiple files for editing and select "name" and "meta" as fields. After click on "Bearbeiten" it shows the error.

**Comment by m-vo** [comment]
I can confirm this.

**Comment by m-vo** [comment]
This was introduced with https://github.com/contao/contao/pull/4709 (`DC_Folder` L1730). 
/cc @aschempp

**Comment by ausi** [comment]
Duplicate of #5456 and already fixed by #5463 ?

**Comment by leofeyer** [comment]
Indeed. 👍
