### ISSUE TITLE
Maximale Frontend-Breite für Bilder

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#549]
Die sehr sinnvolle Funktion "Maximale Frontend-Breite" ist in der 4.7 (und wohl auch schon vorher) leider aus System -> Einstellungen verschwunden und muß jetzt per FTP in der localconfig.php direkt geändert werden. Hier hilft wohl vorerst ein Patch, der das Feld wieder der Palette hinzufügt.

Ich hätte jetzt erwartet, das die maximale Frontend-Breite in das Seitenlayout aufgenommen wird, wo es ja auch hingehört. Ist das geplant?

**Comment by fritzmg** [comment]
Ich denke das wurde übersehen, ja. Sollte in das Seitenlayout wandern.

**Comment by ausi** [comment]
Die maximale Frontend-Breite ist deprecated seit Contao 4.6: https://github.com/contao/contao/blob/0ad6d24830c0dc8a581bff8f411059020945ac59/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1506

**Comment by fritzmg** [comment]
Achja :grin:
