### ISSUE TITLE
Search index: Crawling endlessly, multiple redundant results

### ISSUE THREAD

**Issue by Xendiadyon** [contao/contao#5497]
### Affected version(s)

4.9 to 4.13.12

### Description

I have several problems with the Search Index / Crawler.

## Infinite Crawling due to nested news / comment pages:
When using a newslist (with several pages), combined with a comment module (with several pages), the number of pages rise exponentially and the crawler simply stops after a timeout (10 mins or so):
![grafik](https://user-images.githubusercontent.com/2657385/201428407-90725e0f-aa21-419b-a283-b2a407083c5e.png)

The crawl-queue is huge (37.000 entries) and you can see that there must be redundant entries:
![grafik](https://user-images.githubusercontent.com/2657385/201428875-921f719d-74bd-4bf8-9ed3-d7d76f90726a.png)

Also, when I have one news detail item (news_full) on top with a multipage-newslist (news_list) underneath, it cycles through each detail entry with each of the pages:
![grafik](https://user-images.githubusercontent.com/2657385/201428741-d2066704-e1b3-459d-b5ed-c01b0c5929d0.png)

These pages are identical:
https://christian-methfessel.de/musiker/off-beat/gelassenheit/
https://christian-methfessel.de/musiker/off-beat/gelassenheit/?page_n10=2
https://christian-methfessel.de/musiker/off-beat/gelassenheit/?page_n10=3

### Results:
https://christian-methfessel.de/suche/?keywords=Geschenke
![grafik](https://user-images.githubusercontent.com/2657385/201427106-1b69bb30-8890-4eb5-9049-1428314f9fab.png)

As you can see, the crawling is infinite (until it runs into the timeout) and there are several (nearly) identical results in the search list.

### Ideas:
1. If I crawl for broken links, why do I have to wait for results until the crawler is finished? (which is, in my situation: never).
I would really much like that the result list is dynamically updated while the crawler is running. Then I already could see the first results without having to wait until the crawler is done:
![grafik](https://user-images.githubusercontent.com/2657385/201430207-4f8bed54-ba41-4eb9-9a22-293ee2917952.png)

2. If I could somehow tell the crawler that https://christian-methfessel.de/musiker/off-beat/gelassenheit/ and https://christian-methfessel.de/musiker/off-beat/gelassenheit/?page_n10=2 are identical (canonical?) and thus the `?page_n10` should simpy be ignored, this would be perfect. Then there would be less pages in the crawl queue.

3. Similarly, I would like to tell the crawler that combinations like `?page_n10=3&page_cc20=4` are nonsense and should be ignored (the expected result: the `page_n10=3` is crawled once, the `page_cc20=4` is crawled once, but the redundant `page_n10=3&page_cc20=4` and all other combinations should be ignored).

Thanks!

**Comment by ausi** [comment]
> 2\. If I could somehow tell the crawler that https://christian-methfessel.de/musiker/off-beat/gelassenheit/ and https://christian-methfessel.de/musiker/off-beat/gelassenheit/?page_n10=2 are identical (canonical?)

You can do that by activating _Enable rel="canonical"_ in the root page settings, see https://docs.contao.org/manual/de/layout/seitenstruktur/seiten-konfigurieren/#kanonische-url
