### ISSUE TITLE
Globale CSS Variablen Auswahl für Seitenbäume

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#55]
Aktuell ist es in Contao nicht möglich, Globale CSS Variablen für verschiedene Seitenbäume zu vergeben. Ich habe den konkreten Anwendungsfall, dass sich für 2 Seitenbäume mit verschiedenen Domains nur die Farbe unterscheiden. Möchte ich mit den internen Stylesheets arbeiten, habe ich keine andere Möglichkeit, als das Theme zu kopieren und dann die Variablen für die Farben zu ändern. Damit wäre der CSS Code aber doppelt vorhanden.

Lösungsideen:
- Hook um Globale Variablen zu überschreiben
- Auswahl von CSS Variablen im Seitenlayout oder in den übergeordneten Seiteneinstellungen.

**Comment by fritzmg** [comment]
Du könntest mit regulären CSS Variablen arbeiten und bspw. `{{page::rootAlias}}` als body Klasse im Seitenlayout eintragen.

**Comment by theDyingMountain** [comment]
@fritzmg: ja, aber die Variablen werden leider im IE 11 noch nicht unterstützt und der ist (leider) noch oft verbreitet...

**Comment by fritzmg** [comment]
Hm, ja stimmt.

Prinzipiell musst du für so einen Fall mehrere Seitenlayouts machen, dafür sind sie eigentlich da. Allerdings verstehe ich, dass du nicht mehrere Seitenlayouts warten möchtest, nur weil du sie wegen ein paar wenigen Unterschieden kopieren musst.

Die eigentliche Lösung zu diesem Problem wären vererbbare Seitenlayouts oder Themes.

**Comment by theDyingMountain** [comment]
Ja vererbbare Themes wäre in meinem Fall wirklich hilfreich, da dort die Variablen stehen.

**Comment by contaoacademy** [comment]
Da mit Contao 5 der interne CSS-Editor entfällt, würde ich das Ticket schließen.
