### ISSUE TITLE
404 page error im Wartungsmodus

### ISSUE THREAD

**Issue by paddibr** [contao/contao#550]
**Affected version(s)**
4.7.6

**Description**  
404 Page gibt im Wartungsmodus auf der Rootebene (also z.B. domain.tld/root) einen Skriptfehler aus. Kein Eintrag im Error-log. Auf zweiter Wurzelebene scheint es zu funktionieren.

**How to reproduce**  
404 Page, im Wartungsmodus, domain.tld/cannotfound

**Comment by leofeyer** [comment]
Auf der Rootebene lassen sich bei mir nur Seiten vom Typ "Startpunkt einer Webseite" anlegen und keine 404er-Seiten. Oder was genau meinst Du mit "Rootebene" und "Wurzelebene"?
