### ISSUE TITLE
Events: Check if URL-Parameter is valid

### ISSUE THREAD

**Issue by marcoheinz** [contao/contao#5502]
### Affected version(s)

4.9

### Description

**Problem: Searchengines are indexing invalid URL-Parameters.**
To solve this problem Contao should check if the url parameter matches the entered date/time?
If the URL-Parameters (event_1.html?day=20221111&times=1668121200,1668380399) are wrong 404 or 301 to e.g. event_1.html should be returned.

**Comment by aschempp** [comment]
you should probably configure canonical links (in Contao 4.13) to fix this issue for you.

**Comment by fritzmg** [comment]
@aschempp how would the canonical feature in Contao 4.13 help here? You can only define which parameter names are valid, but not which values are valid. Only the module knows if a parameter value is valid or not.

@marcoheinz however, the question is - where do these invalid parameters come from in the first place?

**Comment by aschempp** [comment]
Search indexes should ignore the date and time parameters.

**Comment by fritzmg** [comment]
> Search indexes should ignore the date and time parameters.

Then the search index would never index the detail page of a repeating event with the respective date.

**Comment by marcoheinz** [comment]
> however, the question is - where do these invalid parameters come from in the first place?

Don't know where e.g. Google gets these invalid parameters... There are no existing links to these date/time parameters!

Canonical wouldn't help. 

I think the best way to prevent the content from being manipulated by changing the date/time parameters would be 404 if invalid.
