### ISSUE TITLE
Error after update to V5.0.5

### ISSUE THREAD

**Issue by jedoCodes** [contao/contao#5506]
### Affected version(s)

5.0.5

### Description

After updating from 5.0.4 to 5.0.5 I get the following error message when I want to create a module.

`Contao\CoreBundle\EventListener\DataContainer\TemplateOptionsListener::__construct(): Argument #5 ($hierarchy) must be of type Contao\CoreBundle\Twig\Inheritance\TemplateHierarchyInterface, string given, called in  `

**Comment by ausi** [comment]
Looks like adding `- '@contao.twig.filesystem_loader'` was forgotten here: https://github.com/contao/contao/commit/0dfbd54cf26e2bb4168bfb038642b92255adbae0#diff-1ed02a947ba36ca7331ab438573363a620fc31d0ccd3f7e09c4c5b46e5574d54R361

**Comment by m-vo** [comment]
See #5507
