### ISSUE TITLE
Selection of important part of the image is incorrect

### ISSUE THREAD

**Issue by minstyle** [contao/contao#5508]
### Affected version(s)

4.13.13

### Description

After updating to Contao 4.13.13, I now have the error that the important part of the image can only be defined via the menu item "System > File management (in german: Dateiverwaltung)".

For example, if I select an image in the Contao content element "Gallery" and want to define or change the important part of it, the mouse selection is not available. The cursor does not turn into a crosshair (under Windows).

More information:
https://github.com/contao/contao/pull/5437

![image](https://user-images.githubusercontent.com/2649562/196366648-7395e4ea-69ca-4074-a081-c88876a38d81.png)

**Comment by ausi** [comment]
Seems to be caused by 241a69ccdd050e9f91f67f43eff830bcf1bcdcb5 because `$('header')` is null.
