### ISSUE TITLE
Frontend User groups check first if array is empty.

### ISSUE THREAD

**Issue by tsarma** [contao/contao#5509]
### Affected version(s)

4.13.12

### Description

Contao 4.13.12
PHP: 8.1

Please check if the member groups array is empty before accessing its 0th element.

![Screenshot 2022-11-15 at 17 47 45](https://user-images.githubusercontent.com/683894/202127490-c5a6beb0-d367-4ee0-90ef-7923e09495e6.png)

**Comment by bytehead** [comment]
See #5511
