### ISSUE TITLE
Session and CSRF cookie not being deleted when logging out

### ISSUE THREAD

**Issue by Toflar** [contao/contao#551]
**Affected version(s)**

4.8

**Description**  

When I log out the back end, I'd expect the cookies `SESSIONID` and `csrf_https-contao_csrf_token` cookies to be deleted but they remain valid.

**How to reproduce**  

Log in and log back out 😄

**Comment by leofeyer** [comment]
Isn't this because the session is only being regenerated and not terminated? And the CSRF cookie is probably there for the login form.

**Comment by Toflar** [comment]
CSRF: No it's there because there is another cookie = probably personal information = needs protection.

But the session cookie should be killed if log myself out.

**Comment by leofeyer** [comment]
Agreed.

**Comment by Toflar** [comment]
It's pretty much super complex 🙈 @aschempp and I worked on a possible solution, let's see what the Symfony folks think about it: https://github.com/symfony/symfony/pull/32455

**Comment by leofeyer** [comment]
symfony/symfony#32455 has been merged 🎉
