### ISSUE TITLE
EFG: Send confirmation via e-mail not sent

### ISSUE THREAD

**Issue by biowebfr** [contao/contao#5512]
### Affected version(s)

4.13.13

### Description

EFG 1.0.36

(EFG) Send **confirmation** via e-mail is not sent.

Maybe it could help, I noticed errors when I try to send it from the Form Data by using the envelop button "Send confirmation mail for reccord X"
![image](https://user-images.githubusercontent.com/46192868/202442429-c6e8774a-c636-4024-ae0a-6ff4548864f2.png)
![image](https://user-images.githubusercontent.com/46192868/202441911-d2758cef-e9d8-4942-a220-786529880641.png)

The option "(EFG) Send via e-mail" is working correctly.

**Comment by asaage** [comment]
EFG is still a thing? 👀

**Comment by bytehead** [comment]
EFG is not part of the Contao core, you have to report this issue at the EFG repository.

**Comment by bytehead** [comment]
Over here: https://github.com/pbd-kn/contao-efg-bundle

**Comment by biowebfr** [comment]
Ok sorry, I saw this : 
![image](https://user-images.githubusercontent.com/46192868/202445504-94400dca-1de5-4742-abfc-b9c58c840fce.png)


I thought it could be reported here.

**Comment by bytehead** [comment]
If you click on `Issues / Bug Report` it will bring you to the right address :)

**Comment by biowebfr** [comment]
> EFG is still a thing? 👀

Do you know another extension like EFG for Contao 4 ?

**Comment by bytehead** [comment]
I can recommend [terminal42/contao-leads ](https://extensions.contao.org/?q=leads&pages=1&p=terminal42%2Fcontao-leads) instead 😎

**Comment by biowebfr** [comment]
> If you click on `Issues / Bug Report` it will bring you to the right address :)

Ok, thanks I did it.

**Comment by biowebfr** [comment]
> I can recommend [terminal42/contao-leads ](https://extensions.contao.org/?q=leads&pages=1&p=terminal42%2Fcontao-leads) instead 😎

Ok I'll try it right now. Thanks David.

**Comment by biowebfr** [comment]
So Contao Leads is good for reccording thing, but it can't do what EFG do. Sending notification emails for admin and user using templates. :'(

Contao is the best CMS solution for me. using it for 10 years. I decided to switch to version 4 and I think EFG should be part of the core. Miss EFG !!!

**Comment by asaage** [comment]
I always use that: https://github.com/terminal42/contao-notification_center

**Comment by bytehead** [comment]
Definitely go with the notification center!

**Comment by biowebfr** [comment]
Thank you @asaage
I installed this excellent notification_center extension and it's great !!!! Bybye EFG ;)

**Comment by asaage** [comment]
It will be part of contao_core in the future as far as i understand.
