### ISSUE TITLE
EFG: FORM DATA > SQL error when saving a reccord

### ISSUE THREAD

**Issue by biowebfr** [contao/contao#5513]
### Affected version(s)

4.13.13

### Description

EFG 1.0.36

`An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer`

when I save a reccord on the owner group.

![image](https://user-images.githubusercontent.com/46192868/202444151-d0f05bdd-3f61-4c91-ba1a-b55a4e0b4ead.png)

**Comment by bytehead** [comment]
This is also EFG related, please submit to https://github.com/pbd-kn/contao-efg-bundle.
