### ISSUE TITLE
Dropzone-Uploader funktioniert nicht mehr in 4.9.36

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#5515]
### Affected version(s)

4.9.36

### Description

Nach dem Update von 4.9.35 auf 4.9.36 funktioniert der Dropzone-Uploader innerhalb von Popup-Boxen nicht mehr. Also z.B. in Nachrichten -> Teaser-Bild hinzufügen. In der Dateiverwaltung (ohne Popup) ist alles i.O.

Um das Ganze nachzuvollziehen (ein Redakteur hatte das Problem), habe ich das in meiner Entwicklungsumgebung unter 4.9.35 getestet. Dort funktionierte alles wie gewohnt. Nach dem Update auf 4.9.36 ging Dropzone nicht mehr und es kommen Fehlermeldungen auf der Konsole.

**Comment by ausi** [comment]
Es könnte sich hier um denselben Fehler wie #5508 handeln.

**Comment by Samson1964** [comment]
Stimmt. Mein Redakteur sprach auch von Problemen bei der Auswahl des wichtigen Teils.

**Comment by leofeyer** [comment]
Siehe https://github.com/contao/contao/pull/5534.
