### ISSUE TITLE
Vorschau der Seite - Meta-Tag "viewport" fehlt für responsive Kontrolle der Seite

### ISSUE THREAD

**Issue by keved93** [contao/contao#5516]
### Affected version(s)

4.13

### Description

In der Vorschau der Seite wird zurzeit der Meta-Tag für den Viewport nicht gesetzt, um das responsive Verhalten der Seite zu überprüfen. Seite ist im Wartungsmodus, müsste aber jedes mal dafür aus dem Wartungsmodus raus.

**Comment by ausi** [comment]
Wie lässt sich der Fehler auf https://demo.contao.org/ reproduzieren?

**Comment by keved93** [comment]
Wird geschlossen. Grund ist nicht das Contao, sondern ein fertiges Theme, das wohl irgendwie Einfluss darauf hat. Im Backend und zusätzliche Dateien konnte ich keinerlei Unterschiede finden, die das steuern könnten, finden. Bleibt wohl ein Mysterium.
