### ISSUE TITLE
Crawl command job argument not working

### ISSUE THREAD

**Issue by koertho** [contao/contao#5521]
### Affected version(s)

4.9, 4.13

### Description

Using the `contao:crawl` command with an job id (existing in the queue or not) always lead to ` [ERROR] Could not find the given job ID. ` As already discussed on [slack](https://contao.slack.com/archives/CK4J0KNDB/p1668156880869559), the problem is, that the queue feature simply is not implemented in the crawl command.

There are two possible solutions:

1. Remove the argument from the command as long as it is not implemented.
2. Implement the queue in the command (which would be the better, but requires more work)

I did not test it in contao 5, but I think the issue is still existing there.

**Comment by leofeyer** [comment]
@Toflar /cc

**Comment by Toflar** [comment]
Yes, that's true. Either remove the argument or implement the queue.
