### ISSUE TITLE
Install tool error

### ISSUE THREAD

**Issue by xApep** [contao/contao#5522]
### Affected version(s)

4.13.13

### Description

I have website locally which I want to transfer to production as many times before (different projects).

I exported local database and imported to production db.

Then went thru contao manager installation steps which leads me to Contao Install tool, which shows this:
![image](https://user-images.githubusercontent.com/1315340/203417691-838ad58a-5888-4829-80b6-4bd38228526d.png)

Then after "update db" I get an error:

`[2022-11-22T20:25:07.938709+00:00] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_route":"contao_install","_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction"},"request_uri":"http://greenstar.edsolution.si/contao/install","method":"POST"} []
`
`[2022-11-22T20:25:08.852144+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows rows VARCHAR(8) DEFAULT '2rwh' NOT NULL' at line 1" at /home/projectpath/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 86 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 1064): An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows rows VARCHAR(8) DEFAULT '2rwh' NOT NULL' at line 1 at /home/projectpath/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:86)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1064): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows rows VARCHAR(8) DEFAULT '2rwh' NOT NULL' at line 1 at /home/projectpath/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows rows VARCHAR(8) DEFAULT '2rwh' NOT NULL' at line 1 at /home/projectpath/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:31)"} []
`

Running
- PHP 7.4.33
- Mysql 10.3.37-MariaDB

**Comment by fritzmg** [comment]
You need to remove or update the `server_version` parameter in your `parameters.yml` and then rebuild the Symfony Application Cache.

**Comment by xApep** [comment]
I can confirm that this solved the problem.

I somehow missed that parameter when moving. Thank you very much @fritzmg !

**Comment by fritzmg** [comment]
In theory the database update from within the Contao Manager (not the Install Tool) should have pointed you to the misconfiguration.

**Comment by xApep** [comment]
The Contao Manager did not offer any db update - in the "last step" it redirected me to install tool; which is odd since newer version updated db via "contao manager"?
