### ISSUE TITLE
Ajax Request

### ISSUE THREAD

**Issue by jedoCodes** [contao/contao#5527]
### Affected version(s)

5.0.6

### Description

I get the following error message when running an Ajax Json

`<!-- Contao\Ajax::executePostActions(): Argument #1 ($dc) must be of type Contao\DataContainer, null given, called in /****/vendor/contao/core-bundle/contao/classes/Backend.php on line 308 (500 Internal Server Error) -->`

**Comment by jedoCodes** [comment]
This error occurs when you call a backend module without a table stored in the bundle's config.php

**Comment by Toflar** [comment]
Which is not supported I guess. Why is there an `action` there anyway? We cannot help you with this little information.
