### ISSUE TITLE
JS Error in Backend Popups

### ISSUE THREAD

**Issue by bildschirmartist** [contao/contao#5529]
### Affected version(s)

4.13.13

### Description

For example, if you want to edit include elements in the backend and the popup opens, a JavaScript TypeError is thrown.
This happens regardless of the content of the backend popup and can also be reproduced in the online demo (https://demo.contao.org/).
Probably this problem is also the cause for problems I have with some Contao extensions (e.g. jrgregory/m17-sticky-backend-footer) since the update to 4.13.13 in connection with backend popups.

![image](https://user-images.githubusercontent.com/2776658/203830263-fefcd2de-163d-4abf-a4b9-5400509b2592.png)
![image](https://user-images.githubusercontent.com/2776658/203830431-997afcd0-cec2-44d8-98da-1cc4096d6a37.png)
![image](https://user-images.githubusercontent.com/2776658/203830511-bc57c62c-6768-4af2-bf15-dc647adad43e.png)

FYI: I am running Contao with PHP 8.1

Edit: Perhaps it is related to issue #5508

**Comment by fritzmg** [comment]
Yes, this is basically the same issue as #5508.
