### ISSUE TITLE
CSS Class/ID Mapping / Preset 

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#5530]
### Description

With Contao 5 & Twig templates, new CSS classes/ID have been introduced and existing naming conventions, in this context, have been overwritten. Therefore, existing (4.x) theme/CSS layouts must be adapted. 

It would be nice if there was some kind of "mapping feature" in this regard. On the one hand, to facilitate the change in this regard and on the other hand, if you could import/export these as presets thus possibly different CSS frameworks (via the naming convention) could be mapped.

I don't know how this could be mapped in the backend. Ultimately, you would need a list of actual CSS classes/ID's per content element that are used in the templates or considered by default. About the mapping you could then add more CSS classes/Id's here (globally), which will then be considered in the Template (and store theses as a preset).

**Comment by m-vo** [comment]
Themes could simply support both classes in their CSS IMHO.

**Comment by fkaminski** [comment]
Okidoki. Just an idea.
