### ISSUE TITLE
Error in undo label listener

### ISSUE THREAD

**Issue by aschempp** [contao/contao#5533]
### Affected version(s)

4.13

### Description

I get the following error message in our Sentry.io reporting. Not sure why original data can be empty, but I was unable to do a PR since I'm not sure how the system should behave then?

`Contao\CoreBundle\EventListener\DataContainer\Undo\LabelListener::getTemplateData(): Argument #3 ($originalRow) must be of type array, null given, called in vendor/contao/core-bundle/src/EventListener/DataContainer/Undo/LabelListener.php on line 52`

**Comment by m-vo** [comment]
Is this the same issue as in https://github.com/contao/contao/issues/5449?

**Comment by bezin** [comment]
Unfortunately there was no further response in the other ticket. I still don't know, why and when the data is empty, but if it happens regularly we should simply handle this case and have an empty preview then. I can provide a PR for this.

**Comment by aschempp** [comment]
Closing for duplicate of #5449
