### ISSUE TITLE
Insert module "root page dependent modules" via content element does not merge css classes

### ISSUE THREAD

**Issue by doishub** [contao/contao#5535]
### Affected version(s)

4.13

### Description

When the Root Page Dependent Module is inserted via a content element, css classes are not merged.

### Reproducible by creating the following modules
- Module A: css class `module-a`
- Module B: css class `module-b`
- Module C (Root page dependent modules): with A and B
- Content Element (Module): Inserts module C and assigns css class `test`

Only the classes `module-a` or `module-b` are output, `test` is ignored

Is this the expected behavior? Then we should consider removing the ID/CSS class selection for this content element.

**Comment by ausi** [comment]
> Is this the expected behavior?

I don’t think so. I’d expect the css classes to be merged, same as it happens if you include a module as content element.

**Comment by leofeyer** [comment]
@bytehead /cc

**Comment by bytehead** [comment]
Aside from the missing classes - does it make sense to have a root page dependent module as a content element (which itself is tied to a article on a page under a root page)?

**Comment by ausi** [comment]
I think it does because the article itself can be placed on several pages.

**Comment by zoglo** [comment]
@bytehead Has this issue been fixed? The branch has still not been merged and it was marked as completed.

**Comment by bytehead** [comment]
@zoglo not yet - the related PR is still in draft mode, I'll have a look!
