### ISSUE TITLE
Fehler beim Update von 4.13.13 auf 4.13.14

### ISSUE THREAD

**Issue by Schmidty2** [contao/contao#5538]
### Affected version(s)

4.13.14

### Description

Beim Update von Contao 4.13.13 auf 4.13.14 springt der Contao-Manager in den abgesicherten Modus.
Der folgende Fehler wird in der Konsole ausgegeben:

```
In RegisterServiceSubscribersPass.php line 88:
                                                                               
  Service "Contao\CoreBundle\Controller\BackendController" misses a "containe  
  r.service_subscriber" tag with "key"/"id" attributes corresponding to entry  
   "router" as returned by "Contao\CoreBundle\Controller\BackendController::g  
  etSubscribedServices()".
```

In var/logs wir kein Fehler dokumentiert.

PHP 8.1.7 bei All-Inkl
Contao-Manager 1.6.1
Contao 4.13.13 bzw. 4.13.14

**Comment by planepix** [comment]
Same here.
https://community.contao.org/de/showthread.php?84182-Update-4-13-13-auf-4-13-14-Fehler

**Comment by bytehead** [comment]
Can copy this after running `composer update` on CLI:

```
...
Generating autoload files
112 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php bin/console --ansi cache:clear --no-warmup

In RegisterServiceSubscribersPass.php line 88:
                                                                                                                                                                                                                                            
  Service "Contao\CoreBundle\Controller\BackendController" misses a "container.service_subscriber" tag with "key"/"id" attributes corresponding to entry "router" as returned by "Contao\CoreBundle\Controller\BackendController::getSubsc  
  ribedServices()".                                                                                                                                                                                                                   
```

**Comment by Schmidty2** [comment]
Hier noch meine composer.json

```
{
    "type": "project",
    "require": {
        "bugbuster/contao-banner-bundle": "^1.3",
        "bugbuster/contao-be_user_online-bundle": "^2.2",
        "contao/calendar-bundle": "4.13.*",
        "contao/comments-bundle": "4.13.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "4.13.*",
        "contao/listing-bundle": "4.13.*",
        "contao/manager-bundle": "4.13.*",
        "contao/news-bundle": "4.13.*",
        "contao/newsletter-bundle": "4.13.*",
        "duncrow-gmbh/flipbert": "^1.6",
        "e-spin/form-newsletter-bundle": "^1.0",
        "hofff/contao-calendarfield": "^4.0",
        "inspiredminds/contao-event-registration": "^1.2",
        "inspiredminds/contao-extended-form-fields": "^2.5",
        "inspiredminds/contao-fieldset-duplication": "^1.4",
        "madeyourday/contao-rocksolid-columns": "^2.1",
        "madeyourday/contao-rocksolid-custom-elements": "^2.4",
        "madeyourday/contao-rocksolid-icon-picker": "^2.1",
        "madeyourday/contao-rocksolid-slider": "^2.2",
        "madeyourday/contao-rocksolid-theme-assistant": "^2.1",
        "numero2/contao-validate-iban-bic": "^1.0",
        "oneup/contao-ical-export": "^2.1",
        "terminal42/contao-easy_themes": "^3.0",
        "terminal42/contao-shortlink": "^1.0",
        "terminal42/notification_center": "^1.6",
        "trilobit-gmbh/contao-databaseformfieldoptions-bundle": "^1.1"
    },
    "extra": {
        "public-dir": "public",
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "@php vendor/bin/contao-setup"
        ]
    }
}
```

**Comment by sdahlmann** [comment]
I have the same error with Contao update from 4.13 to 4.14 with Dogado Hosting with PHP 8.1.

**Comment by Shoekrates** [comment]
I also ran in this issue while updating from 4.13.13 to 4.13.14, PHP 8.0.20, Hoster all-inkl.

**Comment by sdahlmann** [comment]
I have the same error with Contao update from 4.13.13 to 4.13.14 with Dogado Hosting with PH 8.1.9.

**Comment by sdahlmann** [comment]
I have the same error with Contao update from 4.13.13 to 4.13.14 with Dogado Hosting with PHP 8.1.9.

**Comment by bright-cloud-studio** [comment]
I am having the same issue trying to set up a new Contao 4.13 install as of 30 minutes ago or so. PHP 8.1 on Namecheap.

**Comment by ausi** [comment]
Please try if https://github.com/contao/conflicts/pull/39 fixes the issue.

**Comment by ausi** [comment]
This should be solved by https://github.com/contao/conflicts/pull/39 temporarily.

What caused this issue needs further investigation.

**Comment by bytehead** [comment]
PR that introduced a slighty different behaviour: https://github.com/symfony/symfony/pull/48027

**Comment by Schmidty2** [comment]
What do I have to do so that the update can be carried out?

**Comment by bytehead** [comment]
Run a `composer update` again :)

**Comment by planepix** [comment]
Adding the conflict into the composer,json fixed it. Thank you ausi and bytehead!!

Update to 4.13.14 runs well now.

**Comment by bright-cloud-studio** [comment]
I just tried a fresh install again and it is working as expected. Thanks so much!

**Comment by ausi** [comment]
Contao 5 was affected too, conflicts added in https://github.com/contao/conflicts/pull/40

**Comment by Shoekrates** [comment]
I can confirm that https://github.com/contao/conflicts/pull/39 solves the problem. I just added the line to the conflicts block in composer.json and did a composer update.
In a fresh install this morning without adding anything to the conflicts no problem occured, so I guess the problem is solved.
Thanks!

**Comment by ausi** [comment]
Symfony ticket: ~~https://github.com/symfony/symfony/issues/48388~~ https://github.com/symfony/symfony/issues/48404

**Comment by ausi** [comment]
Behoben in https://github.com/symfony/symfony/pull/48482
