### ISSUE TITLE
{{request_token}} still generates an ESI request even if it's not needed

### ISSUE THREAD

**Issue by Toflar** [contao/contao#554]
**Affected version(s)**

4.8

**Description**  

When I use `{{request_token}}` it still generates an ESI request even though it's not needed (= same logic as in the CsrfTokenCookieListener). In that case, we can just replace the tag with an empty string.

**Comment by Toflar** [comment]
After a brief discussion with @ausi, I think there's actually not much we can do about this because at the time we render the token we don't know for sure if the next request is going to need a token. So the only thing we can do here to optimize this case (if you have 5 forms on the page, we have 5 ESI requests) is to maybe switch to a JS solution. I'll make it a feature and assign it to 4.9.

**Comment by leofeyer** [comment]
Siehe #710.
