### ISSUE TITLE
Logged in member in FE preview not working

### ISSUE THREAD

**Issue by Toflar** [contao/contao#5541]
### Affected version(s)

5.*

### Description

`$container->get('contao.security.token_checker')->hasFrontendUser()` returns `false` in `preview.php` even though I'm authenticated as a FE member.

Steps to reproduce:

1. Place a module that requires FE authentication on a page. E.g. the "Personal data" front end module.
2. Open the page using the FE preview.

Expected output:

Module should be rendered.

Problem:

Module is not rendered.

**Comment by ausi** [comment]
Changing https://github.com/contao/contao/blob/a07b562273b0bf94812ccdb99106260055db5c32/core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php#L49 to:

```php
$token = new UsernamePasswordToken($user, 'contao_frontend', $user->getRoles());
```

fixed the issue in my test. 

Not sure if this is correct though, @aschempp @bytehead ?

**Comment by bytehead** [comment]
Looks correct to me 👍 Should I provide a fix and a test?

**Comment by bytehead** [comment]
Closing in favor of #5543.
