### ISSUE TITLE
Crawling protected pages seems broken

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#5546]
### Affected version(s)

4.13

### Description

Our customer has some pages which are protected by a member login.
Of course within the config.yml he has set index_protected to true.
He started the crawl by selecting a member with sufficient permissions, frontend preview with this member also works flawlessly, but in the debug.log it is stated that the crawler receives a HTTP 401 for each protected page.

It seems like the crawler is not using the selected member to perform the requests at all.

I could also recreate the same problem on a fresh 4.13 installation.

Link to the discussion in Slack for reference: https://contao.slack.com/archives/CK4J0KNDB/p1669813587617539

Also reported the issue in https://github.com/terminal42/escargot/issues/29 since it is unclear to me if it's a problem of the Contao Core or Escargot.

**Comment by bytehead** [comment]
AFAIK it's not yet possible to crawl protected pages at the moment.

**Comment by Toflar** [comment]
It is not on CLI, it is in the back end.

Please provide all steps to reproduce this issue in a clean Contao setup.

**Comment by bytehead** [comment]
Sorry - my fault 🙈

~~Then it's possibly the same issue as in #5541.~~

**Comment by bytehead** [comment]
~~@bennyborn can you try if https://github.com/contao/contao/pull/5543 fixes your issues?~~

Edit: Sorry, the fix is for 5.0+ only.

**Comment by bennyborn** [comment]
> Please provide all steps to reproduce this issue in a clean Contao setup.

1. Create a member group e.g. "Members"
2. Create a member and assign it to this group
3. Create a page, set it to "protected" and allow only the group "Members"
4. Add the following lines to your `config/config.yml`
```
contao:
  search:
    index_protected: true
```
5. Clear your Symfony / Application Cache
6. In the Backend navigate to Maintainance
7. Check the option `Update the search index`
8. Select your member created in step 2
9. Click `Start crawling`

In the Debug Log you should then find a line like this
```
"2022-11-30 13:58:32.138730","Contao\CoreBundle\Crawl\Escargot\Subscriber\SearchIndexSubscriber",...,2,,"Broken link! HTTP Status Code: 401."
```

**Comment by Toflar** [comment]
I found an issue with the `/sitemap.xml` not returning the protected pages. That's fixed in https://github.com/contao/contao/pull/5556.

However, I could not reproduce the issue otherwise. Once it was found (either by the `sitemap.xml` or via link in e.g. the navigation), it was properly indexed.

**Comment by bennyborn** [comment]
So you're saying you were not able to reproduce the issue after you implemented #5556 ?

**Comment by Toflar** [comment]
No that's not related. It just caused the protected page not to be listed in the `sitemap.xml` but once found, the request worked normally and it was added to the search index.

**Comment by bennyborn** [comment]
Hmm that's quite strange. Any hint on where one could start debugging this issue?

**Comment by Toflar** [comment]
You could just dump the request in Escargot. Maybe you'll find additional info. Also, once found, you could extract one of the non-working requests as e.g. a cURL command and re-run it as many times as you need to find out where the 401 is generated.
