### ISSUE TITLE
Image Size Mediaqueries

### ISSUE THREAD

**Issue by b42n1** [contao/contao#5549]
### Affected version(s)

5.0.7

### Description

I am not sure. Is it a bug or a feature? Or am I doing something wrong?

When I create media queries and they are greyed out everything works.
![image](https://user-images.githubusercontent.com/20787965/205298057-3eaff59e-211c-4206-9b3a-bcede994fb7c.png)
![image](https://user-images.githubusercontent.com/20787965/205298101-4c0c4be4-4e28-42a5-81ee-36b7a4a52b92.png)

When I activate them they don't load.
![image](https://user-images.githubusercontent.com/20787965/205298333-96a74470-3eb5-488c-b0c3-f98a42411168.png)
![image](https://user-images.githubusercontent.com/20787965/205298373-31b886d5-370e-48fd-98f9-fb1317cb61c8.png)

Image size settings:
![image](https://user-images.githubusercontent.com/20787965/205298436-3a0d27e3-0777-415c-a757-5e8ebbc7004d.png)

**Comment by ausi** [comment]
This is an error in Contao 5, the toggle icon shows the wrong (reverse) state.

This was probably caused by 563ab9d601ae69777b9fb447403f246bcd8fef13 cc @aschempp

**Comment by fritzmg** [comment]
`tl_image_size_item.invisible` is probably missing `'reverseToggle' => true`. However, `tl_content.invisible` is missing that too - but that works 🤔

**Comment by leofeyer** [comment]
> However, `tl_content.invisible` is missing that too - but that works 🤔

It only works because `tl_content::toggleIcon()` sets the correct state. It should have the `reverseToggle` flag as well (see #5570).
