### ISSUE TITLE
Folders with the name "0" cause problems

### ISSUE THREAD

**Issue by MarkejN** [contao/contao#5550]
### Affected version(s)

4.13

### Description

1. Creating a folder with the name `0` in the file manager returns the error message `The file "" already exists!`
2. Uploading a file to a folder named `0` (e.g. `files/0/test.txt`) works, but Contao also creates a new folder with the name of the file (`files/test.txt`).

This is possible in Contao 4.9, as far as I have tested it.

**Comment by ausi** [comment]
> This is possible in Contao 4.9, as far as I have tested it.

But the info window seems to be broken in 4.9 for a folder with the name `0`, I get the error `No parent entry for files/0`
