### ISSUE TITLE
Define a better label for guests in the "protected" section

### ISSUE THREAD

**Issue by rorych** [contao/contao#5551]
### Description

In the new Contao 4.13 protected group view the "unauthorized" option is called (in German) "Gäste" and looks like all other member groups, that were defined in the backend. If you need a group that is also called "Gäste" it is not possible to determine which is the user defined option and which comes from Contao:

<img width="448" alt="" src="https://user-images.githubusercontent.com/1192057/207895138-9c9f5c35-efc0-4138-bf77-b3d5822fcebf.png">

To make the system defined "unauthorized" option from Contao clearer, maybe a different label could be used, like:
Nicht authentifiziert (Gäste)

As discussed here: https://contao.slack.com/archives/CK4J0KNDB/p1670241229270649

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to change the name to `Gäste (nicht eingeloggt)`.
