### ISSUE TITLE
Custom tables should  be ignored

### ISSUE THREAD

**Issue by Funbug** [contao/contao#5553]
### Affected version(s)

4.13

### Description

Custom tables should not be marked for deletion by an update in the Contao Manager or CLI. Expected behaviour is that Contao only modifies and deletes its own tables begining with "tl_".

**Comment by ausi** [comment]
This was changed in #2049 see https://github.com/contao/contao/issues/4160#issuecomment-1321209253 for a workaround you can use.

**Comment by Funbug** [comment]
Workaround works just fine. Unfortunately, this new setting has cost me the deletion of two custom tables. So I had to learn it the hard way. I was used to the old install tool ignoring custom tables.

**Comment by Toflar** [comment]
4.13 automatically creates backups in `var/backups`.
