### ISSUE TITLE
"Drag and Drop" not functioning on certain Upload File pages

### ISSUE THREAD

**Issue by bright-cloud-studio** [contao/contao#5555]
### Affected version(s)

4.13.13

### Description

In the backend, if I go to System>File manager and try and upload a file things work as expected. When adding a Content Element, in this example a Gallery, and click "Change selection" the "Source files" popup appears. If I click "Upload files" there, it actually shows a different version of the Upload Files section I have not seen before. It has buttons that are usually not there, I am guessing this might be an updated version or an upcoming version. Either way, the "Click or drop files here to upload" section does not work.

We had a client asking about the upload drag and drop not working last week and I wasn't sure what she was talking about. I tried it out in multiple ways but could not recreate it. Today, on a different site I had to add a photo to a gallery and boom, I came across it. Just wanted to bring it to your attention, I didn't see an issue here for it.

**Comment by cliffparnitzky** [comment]
This is fixed with 4.13.14 ... please update.

**Comment by bright-cloud-studio** [comment]
Ah beautiful, thanks so much!

**Comment by bright-cloud-studio** [comment]
Ah beautiful, thanks so much!
