### ISSUE TITLE
Use the "resname" attribute in .xliff files

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#556]
As described in the [Xliff wiki](https://wiki.oasis-open.org/xliff/FAQ#IdvsResname), the original identifier of a text item should be stored in the `resname` attribute of the `<trans-unit>` tag. We are currently (ab)using the `id` attribute, which is why the Contao .xliff files are not compatible with the Symfony translator (see https://github.com/symfony/symfony/issues/12241).

We should adjust our Xliff loader to handle the attribute and update our .xliff files accordingly.

**Comment by leofeyer** [comment]
#1256 has shown that we need to re-discuss the concept again.

**Comment by ausi** [comment]
Why was this closed? Is there a followup ticket?

**Comment by leofeyer** [comment]
No. We have to discuss the translator concept again and agree on how to handle translations in the future. Then we can re-open this ticket or – more likely – create a new one.
