### ISSUE TITLE
Localhost > Preview doesn't work

### ISSUE THREAD

**Issue by biowebfr** [contao/contao#5561]
### Affected version(s)

4.13.14

### Description

The preview shortcut open this http://localhost/subdirectory/public/contao/preview?page=104 but instantly redirect to http://localhost/preview.php/

![image](https://user-images.githubusercontent.com/46192868/206457698-99a2b67a-080e-459f-a2b7-c879db50d897.png)

**Comment by leofeyer** [comment]
I was not able to reproduce this. I got redirected to `https://localhost/contao/managed-edition/public/preview.php/` as expected.
