### ISSUE TITLE
TinyMCE adds newline at end of text

### ISSUE THREAD

**Issue by falkgeist** [contao/contao#5567]
### Affected version(s)

4.13.10

### Description

PHP version: 8.2

If I change the text in a text element (not pasting) and save the text element, TinyMCE automatically adds a newline at the end (possibly originating [here](https://github.com/tinymce/tinymce/blob/release/6.2/modules/tinymce/src/core/main/ts/api/html/Writer.ts#L116)). Reproducible in the [Contao Demo backend](https://demo.contao.org/contao) and also in this [TinyMCE Fiddle](https://fiddle.tiny.cloud/Euiaab) (click `Save` after entering something and waiting a few seconds to see the generated html with the additional paragraph).
With the default TinyMCE options, this results in `<p>[nbsp]</p>` when viewed in code view.
Eventually, every change and save then leads to another empty paragraph at the end, bloating up the space.

The following settings in the `tinymce.init()` function:
```
force_br_newlines: false,
force_p_newlines: false,
forced_root_block: ''
```
seemingly fix the error, but essentially just prevent wrapping a `p` tag around the `&nbsp;`.
Furthermore, now ENTER inserts a linebreak (`<br>`), not a paragraph (`<p>`), which is unwanted behaviour.

I understand that this is rather a TinyMCE issue, but there exists an acceptable solution for most people there. The repercussions for Contao on the other hand are more severe, so imho there should be a solution for Contao specifically.

**Comment by falkgeist** [comment]
I'm not sure though, which TinyMCE version is used by Contao now? 4, 5 or 6? (The link provided is for v6, but the same is valid for earlier versions.)

**Comment by fritzmg** [comment]
Unless this has something to do with PHP 8.2, I am unable to reproduce this in Firefox, Chrome and Edge.

> I'm not sure though, which TinyMCE version is used by Contao now? 4, 5 or 6?

Contao 4.13 uses TinyMCE 5.

**Comment by falkgeist** [comment]
Okay, just tried to reproduce it on my phone (Android) and couldn't, so maybe it's a macOS issue. I have no idea though, why it could be happening. But the issue exists on my colleagues macbook as well, as far as I heard. I'll test more and maybe someone with access to a Mac can confirm, that it's reproducible there.
Anyways, it's then most probably not something that can be fixed in Contao...

**Comment by fritzmg** [comment]
Which browser and MacOS version?

**Comment by falkgeist** [comment]
I was encountering the issue on macOS Monterey (12.5) with Firefox 108.0b9 only (also tested Chrome 109.0.5414.87 and Safari Version 16.0 (17614.1.25.9.10, 17614)). So apparently it was a Firefox issue, but since I updated to 110.0b3, it seems to be fixed. Sorry for the trouble.

**Comment by falkgeist** [comment]
I realized now, I am not using regular Firefox, I am using Firefox Firefox Developer Edition (currently version 111.0b3). If I am using just Firefox, this is not an issue. Just if anybody has this issue again...
