### ISSUE TITLE
Disallowed resources from robots.txt are still indexed

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#5579]
### Affected version(s)

4.9

### Description

Despite having 

```
user-agent: *
disallow: /something
```

in your `robots.txt` website root setting, the crawler will still request and index these resources, since our `SearchIndexSubscriber` does not return a negative decision if a URL has been tagged with `RobotsSubscriber::TAG_DISALLOWED_ROBOTS_TXT`. Is this on purpose? i.e. should Contao's own search index crawler still index URLs that are disallowed in the `robots.txt`?

**Comment by fritzmg** [comment]
As discussed in the call today we want to take the `robots.txt` into account in our `SearchIndexSubscriber`. You can still specifically allow/disallow resources anyway via:

```
user-agent: contao/crawler
disallow: …
```

**Comment by leofeyer** [comment]
Does this issue occur in Contao 4.13, too?

**Comment by fritzmg** [comment]
Yes, the `SearchIndexSubscriber` of Contao 4.13 is no different than the one in 4.9.

**Comment by Toflar** [comment]
I've double checked this and I cannot reproduce. 
We test this: https://github.com/contao/contao/blob/4.13/core-bundle/tests/Crawl/Escargot/Subscriber/SearchIndexSubscriberTest.php#L113-L118
And the check happens in the `Util` of Escargot: https://github.com/contao/contao/blob/4.13/core-bundle/src/Crawl/Escargot/Subscriber/SearchIndexSubscriber.php#L84

I'm thus closing as discussed with @fritzmg.
