### ISSUE TITLE
useRawRequestData leads to empty data

### ISSUE THREAD

**Issue by richardhj** [contao/contao#558]
**Affected version(s)**
4.7.x

**Description**  
When validating a form, it repeatedly occurs for me, that the password `$varValue` is `null`.
All other form data is present and will be fetched correctly.

The `FormPassword` uses `useRawRequestData`.
https://github.com/contao/contao/blob/a0057c0bbfa8b85912ca7800af42208f82dc4fd2/core-bundle/src/Resources/contao/forms/FormPassword.php#L61-L66

Widgets with that attribute will be handled differently: https://github.com/contao/contao/blob/a0057c0bbfa8b85912ca7800af42208f82dc4fd2/core-bundle/src/Resources/contao/library/Contao/Widget.php#L770-L776

Introduced in ebb5b0ddcc1ee4da02488beb3994e5e532a91058.

**How to reproduce**  
I do have two cases where this occurs. One of them:

1. A module fragment with Haste form. When validating, the form the password value is `null`. I was able to fix his issue with `$form->getWidget('password')->useRawRequestData = false;`.

Besides this issue that involves a third-party-extension, the issue can be reproduced by doing the following steps on demo.contao.org:

1. Create a registration module (fields: one field being mandatory, e.g. firstname, the password field).
2. Edit the "Not Authenticated 401" page, remove the redirect.
3. Place the module on the 401 page.
4. Fill out the form, firstname persits, password field gets the error "A password has to be at least 8 characters long!".

<img width="510" alt="Screen Shot 2019-07-06 at 17 47 12" src="https://user-images.githubusercontent.com/1284725/60758299-1eebb800-a016-11e9-9679-6bce0b5460aa.png">

**Proposal**  

- It may occur, that the current request (in the sense of `->getCurrentRequest()`) does not have request data ($_POST) at all. Switching to the master request (in the sense of `->getMasterRequest()`) can work.
- Another approach for fixing this would be to get to know, why the current request does not have post values at all in some cases.
- One approach would be to use `Input::postRaw()` instead.

**Comment by leofeyer** [comment]
@Toflar I think you have implemented this in contao/core-bundle#708. Can you confirm the issue?

**Comment by Toflar** [comment]
Well, how does that fragment look like? We have introduced the `forward` renderer for exactly that reason (https://github.com/contao/contao/blob/master/core-bundle/src/Fragment/ForwardFragmentRenderer.php) but if you configure your fragment e.g. to be an ESI fragent you cannot handle POST data by design.

**Comment by richardhj** [comment]
You can reproduce the issue in the Contao demo without custom extensions involved as stated above by placing the registration module on a 401 page.

**Comment by ausi** [comment]
I was able to reproduce the issue as described above.

The master request points to the page to which the POST data was sent (`/members-area.html` in this example), the current request points to the `contao_frontend_login` route (`/_contao/login`).

But I’m not sure if using a registration form on a 401 page is a supported use case?

**Comment by leofeyer** [comment]
I'm not sure about this, either. Normally the 401 page redirects to the login page.

**Comment by richardhj** [comment]
401 Unauthorized. The user can log in or register. No?

**Comment by leofeyer** [comment]
Are you using the Terminal42 contao-autoregistration extension?
