### ISSUE TITLE
Using the "class" parameter in a picture insert tag can make the image disappear in debug mode.

### ISSUE THREAD

**Issue by vstuber** [contao/contao#5580]
### Affected version(s)

4.13.13 when running with PHP 8

### Description

This will show the image even when debug mode is active:

`{{picture::files/images/xyz.jpg}}`

but this won't

`{{picture::files/images/xyz.jpg?class=testclass}}`

I found the reason for this in "vendor/contao/core-bundle/src/Resources/contao/templates/picture/picture_default.html5"

```
<?php if ($this->class || !empty($this->img['class'])): ?>
class="<?= trim($this->class.' '.$this->img['class']) ?>"
<?php endif; ?>
```

If "$this->class" is given, the template will try to output "$this->img['class']" but the array key "class" might not exist. Using the null coalescing operator fixes the problem:

```
<?php if ($this->class || !empty($this->img['class'])): ?>
class="<?= trim($this->class.' '.($this->img['class'] ?? '')) ?>"
<?php endif; ?>
```

I haven't figured out yet why the warning is not displayed in debug mode. A warning usually stops rendering the page and shows symfony's error/warning page. In this case, however, the page renders without any problems, but some images missing...

**Comment by leofeyer** [comment]
See #5629
