### ISSUE TITLE
Backend preview URL does not work

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#5582]
### Affected version(s)

5.0.7, 5.0.x-dev

### Description

If you open the preview from the back end, i.e. via an URL like

```
https://example.com/contao/preview?page=8
```

then the resulting redirect response URL will be

```
https://example.com\/preview.php/page-alias
```

which will lead to a 404 response.

For some reason this call in `PageModel::getPreviewUrl`

https://github.com/contao/contao/blob/0941be9e3562ad09f44665723146627da7a8894c/core-bundle/contao/models/PageModel.php#L1180

results in such an aforementioned URL (with the first slash "escaped").

/cc @aschempp

**Comment by ausi** [comment]
I was not able to reproduce this with Contao 5.0.7

For a request to `/contao/preview?page=4`  
I first get a response with:  
`Location: /preview.php/contao/preview?page=4`  
and the second response with:  
`Location: https://example.com/preview.php/test-page.html`

**Comment by fritzmg** [comment]
Hm, I can reproduce it in 5.0.7 and 5.0.x-dev.

**Comment by fritzmg** [comment]
It's an issue that only occurs under Windows, presumably. The cause is this line:

https://github.com/contao/contao/blob/0941be9e3562ad09f44665723146627da7a8894c/core-bundle/contao/models/PageModel.php#L1174

`$baseUrl` is `/preview.php` and `\dirname($baseUrl)` will be `\`.

**Comment by fritzmg** [comment]
This change was introduced here: https://github.com/contao/contao/pull/5195

`$previewScript` is `/preview.php` in both Contao 4.13 and 5.0 - yet for some reason we handle it differently in Contao 5? @ausi do you remember why?

**Comment by fritzmg** [comment]
My bad, I changed this here: https://github.com/contao/contao/pull/4326 🙈

**Comment by fritzmg** [comment]
Closing in favor of #5585
