### ISSUE TITLE
Empty accesskeys in navigation

### ISSUE THREAD

**Issue by CMSworker** [contao/contao#5586]
### Affected version(s)

5.0.7

### Description

In a local test installation of Contao 5.0.7 in XAMPP (PHP 8.1.6) I noticed multiple empty `accesskey=""` in the HTML source code of navigation blocks. I did not set any keyboard shortcuts in the page settings in the backend. The accesskey fields in the backend show `0` as default value.

To investigate it, I made a copy of the template `nav_default.html5` and added a variable dump with
```php
echo \Contao\Template::dumpTemplateVars();
```
In the array lists `accesskey => false` is defined for all navigation elements.

The accesskey is generated in this line in the template file:

https://github.com/contao/contao/blob/015787fc6498cf9ecc68215d2d18e04978a3540a/core-bundle/contao/templates/navigation/nav_default.html5#L7

To avoid the generation of the empty accesskeys I modified this snippet:
`<?php if ('' !== $item['accesskey'] ): ?>`
to this:
`<?php if ('' !== $item['accesskey'] && $item['accesskey'] != false ): ?>`

If someone can confirm the generation of empty accesskeys, it could be fixed in the core template.

**Comment by leofeyer** [comment]
It should probably be `<?php if (!$item['accesskey']): ?>` or `<?php if (!empty($item['accesskey'])): ?>`.

**Comment by CMSworker** [comment]
`<?php if (!$item['accesskey']): ?>` doesn't work.

`<?php if (!empty($item['accesskey'])): ?>` works. Thank you.

**Comment by CMSworker** [comment]
@ausi noted that the change "would break `accesskey="0"`"
and suggested `<?php if ('' !== (string) $item['accesskey']): ?>`

I tested ausi's variant, it would work.

BUT I noticed that you can't declare accesskey `0` in Contao 5.0.7, at least in my test installation.

In the online demo (Contao 4.13.14) the input field for page accesskeys looks like this:

![accesskey-alt](https://user-images.githubusercontent.com/31544192/208269490-3afda31c-8160-413f-a56a-1d97f9024668.jpg)

In my local Contao 5.0.7 installation it looks like this by default:

![accesskey](https://user-images.githubusercontent.com/31544192/208269500-7d80973e-9309-48dc-8202-504ee75b0ad8.jpg)

I did not enter the zero number. `0` is the default value. When you save the page with accesskey 0, it will not be rendered in the frontend's HTML code, no matter how I change the `nav_default.html5` template.

I also noticed you can **only enter numbers** in this field. When you enter any letter and save the page, it gets converted to a number. Is this behaviour correct/intended for accesskeys?

**Comment by fritzmg** [comment]
This is actually an accidental change from https://github.com/contao/contao/pull/4797. I'll provide a PR to fix it.

**Comment by fritzmg** [comment]
See https://github.com/contao/contao/pull/5590
