### ISSUE TITLE
getTemplateData() must be of the type array, null given

### ISSUE THREAD

**Issue by luger95** [contao/contao#5595]
### Affected version(s)

4.13.0

### Description

`Argument 3 passed to Contao\CoreBundle\EventListener\DataContainer\Undo\LabelListener::getTemplateData() must be of the type array, null given, called in /vendor/contao/core-bundle/src/EventListener/DataContainer/Undo/LabelListener.php on line 5`

**Comment by fritzmg** [comment]
Duplicate of #5449
