### ISSUE TITLE
Add @deprecated to outdated classes

### ISSUE THREAD

**Issue by aschempp** [contao/contao#56]
- [x] `UnresolvableDependenciesException ` (see https://github.com/contao/core-bundle/pull/44#issuecomment-76222334) (see contao/core-bundle@958fcfcd9d52772dea272baa2cce337e09f93565)

**Comment by leofeyer** [comment]
We can only deprecate the class once we deprecate the Contao class loader.

**Comment by leofeyer** [comment]
Meanwhile implemented.
