### ISSUE TITLE
Fix the default of some fields

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#56]
See https://github.com/contao/contao/pull/20#discussion_r216916113

That's a bad example, because storing `4` instead of `0` does not affect the database size. But here are some fields we do need to fix:

 * `tl_content.sliderSpeed` stores `300` in every row (should be `0`)
 * `tl_module.queryType` stores `and` in every row (should be `''`)
 * `tl_module.searchType` stores `simple` in every row (should be `''`)
 * `tl_page.sitemap` stores `map_default` in every row (should be `''`) 

However, we should open a separate ticket hereto.

**Comment by aschempp** [comment]
We have discussed this before, if I remember correctly. This is how the DCA works, and I don't see a way to change it. We must have these defaults, otherwise defaults do not make sense at all.

**Comment by leofeyer** [comment]
We must have the defaults, yes, but we must not add them to every row in the table.

**Comment by aschempp** [comment]
That's not possible imho, otherwise you would need to update defaults when I switch the type, based on whether the field is in the palette. And also if the user has permission. But if she does not have permission, you still need to add the default. etc…

**Comment by leofeyer** [comment]
Let's try and see, shall we?

**Comment by ausi** [comment]
I don’t see why we have to remove these defaults for database size. Did you test how big the effect of these default values is regarding storage size?

> We have discussed this before, if I remember correctly.

AFAIR we discussed it in the Mumble call, see https://github.com/contao/core/issues/8075#issuecomment-275419225
