### ISSUE TITLE
$useLastModified has no effect in FilesystemConfiguration::addDefaultDbafs()

### ISSUE THREAD

**Issue by Toflar** [contao/contao#5600]
### Affected version(s)

`4.13.*, 5.*`

### Description

The `$useLastModified` parameter on `FilesystemConfiguration::addDefaultDbafs()` has no effect.

I think we're missing a `$definition->addMethodCall('useLastModified', [$useLastModified]);` [here](https://github.com/contao/contao/blob/5.x/core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php#L190).

/cc @m-vo

**Comment by m-vo** [comment]
Looks like I only added the definition for the hash generator service and forgot about the `Dbafs`. I didn't notice it, because it defaults to `true`. :facepalm: 

> I think we're missing a $definition->addMethodCall('useLastModified', [$useLastModified]); [here](https://github.com/contao/contao/blob/5.x/core-bundle/src/DependencyInjection/Filesystem/FilesystemConfiguration.php?rgh-link-date=2022-12-22T11%3A44%3A11Z#L190).

:+1:

**Comment by Toflar** [comment]
Closing in favor of https://github.com/contao/contao/pull/5603
