### ISSUE TITLE
Extra data gets completely ignored in Dbafs::setExtraMetadata()

### ISSUE THREAD

**Issue by Toflar** [contao/contao#5601]
### Affected version(s)

`4.13.*, 5.*`

### Description

Talking about this here: https://github.com/contao/contao/blob/5.x/core-bundle/src/Filesystem/Dbafs/Dbafs.php#L182

The `$event->getExtraMetadata()` is not considered, only the `$event->getRow()`.

/cc @m-vo

**Comment by m-vo** [comment]
I think this is correct - you need to implement a listener/subscriber that turns the "extra metadata" in a storable representation. The `Dbafs` service itself does not make assumptions how to treat any of the custom columns.

We do this in the core here:

https://github.com/contao/contao/blob/21b3a9ccb75087a57b34cd0ba3b2a1a695a0adad/core-bundle/src/EventListener/DbafsMetadataSubscriber.php#L76-L99

**Comment by Toflar** [comment]
I see :)
