### ISSUE TITLE
User overlay needs higher z-index

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#5604]
### Affected version(s)

4.13.6

### Description

#tmenu ul.menu_level_1 {
  z-index: 2;
}

<img width="1033" alt="Bildschirm­foto 2022-12-23 um 07 36 21" src="https://user-images.githubusercontent.com/1622733/209286059-f6bcc072-1709-4e30-b75e-675a16bff70e.png">

**Comment by fritzmg** [comment]
I can confirm the issue in `4.13.14`.

@erikherbert in the future please always update to the newest Contao version first and check if the fault still occurs there.

**Comment by fritzmg** [comment]
Also happens in Contao 4.9.
