### ISSUE TITLE
Automatic save after change element and go back

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#5605]
### Affected version(s)

5.0.6

### Description

Is it intended that after changing the element type and going back, the element is saved automatically?

https://user-images.githubusercontent.com/1622733/209286768-7888391c-5b95-4ebf-a042-723988aa01d1.mp4

**Comment by fritzmg** [comment]
Yes, that is a known limitation. Any DCA field with `'submitOnChange' => true` (e.g. the `type` field) will cause the current state to be submitted on change.

**Comment by aschempp** [comment]
For anyone finding this ticket, https://github.com/contao/contao/pull/4919 tries to solve this, but currently cannot be merged because of BC breaks.
