### ISSUE TITLE
PHP8 Undefined array key issue in tl_calendar_events

### ISSUE THREAD

**Issue by Defcon0** [contao/contao#5608]
### Affected version(s)

4.13, 5.0

### Description

Hello,

in

https://github.com/contao/contao/blob/5.x/calendar-bundle/contao/dca/tl_calendar_events.php#L848 (Contao 5.x)
https://github.com/contao/contao/blob/4.13/calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php#L913 (Contao 4.13)

there is a php 8-related "undefined array key" in a tl_calendar_events file.

I'd recommand replacing it with:

```
$arrAlias[$objAlias->parent][$objAlias->id] = $objAlias->title . ' (' . (($GLOBALS['TL_LANG']['COLS'][$objAlias->inColumn] ?? null) ?: $objAlias->inColumn) . ', ID ' . $objAlias->id . ')';
```

Would that be ok?

Bye Defcon0

**Comment by leofeyer** [comment]
> Would that be ok?

Yes. 👍

**Comment by Defcon0** [comment]
I created 2 PRs for fixing the issue ;-)
