### ISSUE TITLE
listWizard missing some CSS reset

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#5616]
### Affected version(s)

5.0.7, 5.0.x-dev

### Description

There is still at least one other issue caused by #5370 - the `listWizard` is missing some CSS reset:

<img src="https://user-images.githubusercontent.com/4970961/210111351-fed182ca-6c1f-424c-ba00-ec23451a6f70.png" width="540">

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5632
