### ISSUE TITLE
Memberlist: Display of automatically disabled members 

### ISSUE THREAD

**Issue by FrischBlau** [contao/contao#5627]
### Affected version(s)

4.13

### Description

If members are automatically deactivated at a predefined time, the icon in front of the member's name is greyed out. However, the eye icon (activate/deactivate member) remains green. This is irritating from a usability point of view. This icon should also be greyed out.
Furthermore, it is not possible to filter the member list by automatically deactivated members. With the filter option [Deactivate - yes/no], only manually deactivated members are displayed. Automatically deactivated members should also be shown here.

**Comment by aschempp** [comment]
Unfortunately, this will not be easy to solve. The eye (and the filter) represent the state of the check box, not the state of a user being able to log in etc. The same applies for content elements or any other element with the eye toggle.

**Comment by FrischBlau** [comment]
That is understandable. But there is still a contradiction when the function is called "automatic deactivation" but deactivated users cannot be found via the filter "deactivated users". From a practical point of view: In a scenario where large numbers of members are regularly deactivated automatically, you also want to delete these members (because of the GDPR for example). But first you have to find them, which is very difficult with large numbers of members without a working filter option.

**Comment by fritzmg** [comment]
> In a scenario where large numbers of members are regularly deactivated automatically, you also want to delete these members (because of the GDPR for example). But first you have to find them, which is very difficult with large numbers of members without a working filter option.

In that case you should implement a cronjob which deletes members (and their related data) if their stop time is in the past.

**Comment by aschempp** [comment]
I fully agree this is cumbersome, I do have similar problems on https://members.contao.org

You could fix this for you by adding a custom filter option to the panel, which uses your own SQL query to filter the list.
