### ISSUE TITLE
Forms generator : Add cancel button CE

### ISSUE THREAD

**Issue by JLBA** [contao/contao#563]
Hello,
As the submit button, there could be a Cancel button/link with a link to a specific page.
Or an option to activate a cancel button next to  the submit one in the same CE.

**Comment by asaage** [comment]
You can add a form-field type **Explanation** or type **html-code** an paste sth. like ```<input type="reset" value="cancel">``` to reset your field-values or any link to a specific page.

**Comment by JLBA** [comment]
Yes @asaage I did it sometimes. But I think it more useful if there is a little CE.

**Comment by leofeyer** [comment]
I agree that a "cancel" button, which takes the visitor to another page, can make sense. But I never ever needed an `input type="reset"` button. What is the use case?

**Comment by aschempp** [comment]
> I agree that a "cancel" button, which takes the visitor to another page, can make sense.

Which is essentially a link, which can be added with the explanation field type 🤷‍♂

**Comment by leofeyer** [comment]
@JLBA /ping

**Comment by JLBA** [comment]
Sorry, I was on holidays ;-)
I saw it on some forms. I suppose you typed wrong datas, you want to reset all the form ?

**Comment by contaoacademy** [comment]
> The Web would be a happier place if virtually all Reset buttons were removed. This button almost never helps users, but often hurts them.

https://www.nngroup.com/articles/reset-and-cancel-buttons/

**Comment by leofeyer** [comment]
Even though the article is almost 10 years old, it is a good read and I mostly agree with the author.

> The worst problem about Reset is that users click the button by mistake when they wanted to click Submit. Bang — all your work is gone!

That is a very strong argument against adding a reset button (given that you can still add it in an explanation field as @aschempp noted above). I am therefore closing the ticket.
