### ISSUE TITLE
Twig-Templates im Backend werden ggf. im falschen Unterordner erzeugt

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#5635]
### Affected version(s)

5.0.7

### Description

Ich wollte ein Template ```headline.html.twig``` im Backend als Varianten-Template sofort im Zielverzeichnis ```headline [templates/content_element/headline]``` ablegen. Dabei entsteht dann leider folgende Struktur:
```templates/content_element/headline/content_element/headline.html.twig```
Für das Anlegen im Ordner Templates finde ich das automatische hinzusetzen des notwendigen Ordners ```content_element``` sehr sinnvoll, im Unterordner sollte das aber wenn möglich nicht erfolgen.

**Comment by leofeyer** [comment]
@m-vo /cc

**Comment by m-vo** [comment]
I agree that this is less than optimal. Creating variant templates is simply not possible, yet (without manually adjusting the names afterwards).

I'm closing this as this is effectively a duplicate of https://github.com/contao/contao/issues/5223. I'll add your comment as a remark there.

**Comment by mlwebworker** [comment]
@m-vo der Name ist nicht das Problem, sondern die falsche Hierarchie

**Comment by m-vo** [comment]
Naja, doch. Das Anlegen von Varianten-Templates ist halt derzeit noch nicht supportet und du versuchst ein Template in einem Unterordner zu erstellen ohne dass das System weiß, dass es sich dabei um eine Variante handeln soll. Die Hierarchier ist richtig - du kannst in der Theorie ja beliebig viele Roots haben. :wink:
