### ISSUE TITLE
Legacy-Templates bei der Auswahl neuer Templates im Backend ausblenden

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#5636]
### Description
Contao-Version 5
Wenn ein Legacy Templates nicht aktiviert ist in der config.php dann sollte dieses in der Auswahl für ein neues Template im Backend entweder gar nicht zur Verfügung stehen oder nicht ausgewählt werden können.

**Comment by aschempp** [comment]
Du meinst wenn ein Legacy Inhaltselement nicht aktiviert wurde soll im Templates-Modul im Backend die entsprechende Option nicht kommen?

**Comment by mlwebworker** [comment]
Ja genau, das meine ich.

**Comment by leofeyer** [comment]
@m-vo /cc

**Comment by leofeyer** [comment]
As discussed in the call, the whole "create new template" dialog needs to be reworked. @m-vo Will try to implement it for the next LTS version (Contao 5.3).

**Comment by m-vo** [comment]
As the implementation of this will fully overlap with #5223, I'm moving the original post there and close this issue in favor of the other.
