### ISSUE TITLE
Z-Index Issue in Backend of 5.x

### ISSUE THREAD

**Issue by ben-eSM** [contao/contao#5639]
### Affected version(s)

5.x

### Description

There's a Z-Index issue with the User Menu in the Backend as can be seen in the following screenshot.
The header action items are showing above the menu.
![image](https://user-images.githubusercontent.com/1228764/211079909-370e0908-47da-4d2f-87a5-ee18fd7a4484.png)

**Comment by fritzmg** [comment]
See also https://github.com/contao/contao/issues/5604

**Comment by fritzmg** [comment]
Also happens in Contao 4.9 (if the user menu had enough entries to stick out far enough below).
