### ISSUE TITLE
Forms generator : content element for personnalized redirect page

### ISSUE THREAD

**Issue by JLBA** [contao/contao#564]
Hello,
When you want to personnalize "well sent and thanks" message, you must create a specific redirect page for each form. We could improve it this way.

In each form, a text field for the personnalized message.
And a CE to display the personnalized message or a default message you write in the CE if no personnalized. 

So only one redirect page for all forms.

**Comment by leofeyer** [comment]
Duplicate of #204.

**Comment by JLBA** [comment]
Thanks @leofeyer. Sounds great too.
