### ISSUE TITLE
Hook outputBackendTemplate triggered to early in AbstractBackendController

### ISSUE THREAD

**Issue by rabauss** [contao/contao#5658]
### Affected version(s)

4.13.x-5.x

### Description

While analyzing https://github.com/contao/contao/issues/5657 I realized that the hook `outputBackendTemplate` is triggered to early in the `AbstractBackendController`, so you are not able to replace or add some html code in the final output for the backend.

This is especially a problem for my backend customizer, because the custom parameters wont be set in the backend template anymore (https://github.com/bwein-net/contao-backend-customizer/blob/41b9e3eb0be9e83f000c9f7c56096045c288d8c3/src/EventListener/OutputBackendTemplateListener.php#L32-L40)

**Comment by fritzmg** [comment]
What exactly do you mean? `AbstractBackendController` does not trigger the Hook. The Hook is triggered in `BackendTemplate::compile` and the `$strBuffer` argument contains the final output for the legacy back end template.

**Comment by rabauss** [comment]
Yes, the hook is triggered here: https://github.com/contao/contao/blob/5bbcd4e4c8cbc7b44d8b4e51d9374b0f5a5c55d2/core-bundle/src/Controller/AbstractBackendController.php#L42

But the final output will only get the `$backendContext` and not all replacements of the buffer in the hook!
https://github.com/contao/contao/blob/5bbcd4e4c8cbc7b44d8b4e51d9374b0f5a5c55d2/core-bundle/src/Controller/AbstractBackendController.php#L51

**Comment by fritzmg** [comment]
Yes, because it is rendered as a twig template. These template hooks are only for legacy templates.

**Comment by rabauss** [comment]
I understand! But I guess I need a comparable event like the hook to enrich the `$backendContext` or a `outputBackendTemplateEvent` after rendering the twig template. 

How could I add global changes to the backend template if it's rendered via twig?

**Comment by Toflar** [comment]
Not possible at the moment because Twig does not have any events. See https://github.com/contao/contao/pull/3913.

**Comment by m-vo** [comment]
Please keep in mind, that there is no intention to support manipulating the HTML after it got rendered like you did in https://github.com/bwein-net/contao-backend-customizer/blob/41b9e3eb0be9e83f000c9f7c56096045c288d8c3/src/EventListener/OutputBackendTemplateListener.php#L32-L40.

I started outlining an improved concept in https://github.com/contao/contao/pull/5660, happy to discuss general things there.

**Comment by rabauss** [comment]
Well, maybe I need to go back to generate some custom js/css files instead of adding them on runtime via hook to the backend template. 🤔 Although I liked the current solution because there was no need to generate files anymore.

Or I need to extend the new upcoming backend template in my extension.

**Comment by m-vo** [comment]
> Or I need to extend the new upcoming backend template in my extension.

This sounds like the way to go to me. :+1: Unfortunately, this will only show its full beauty once the old template is gone and with that your adjustments will automatically be effective everywhere.

**Comment by leofeyer** [comment]
As discussed in the Contao call, this specific way of replacing or adding HTML code in the final output is not supported. #5660 will likely improve this, but for now you will have to find another solution.
