### ISSUE TITLE
Symlinking files outside Contao root dir

### ISSUE THREAD

**Issue by qzminski** [contao/contao#5661]
### Affected version(s)

5.1.x

### Description

Our system is deployed using the [Deployer](https://deployer.org/), so some folders are shared across the releases, one of them being the `/files/` folder. The basic structure looks like this:

```
- current –> points to releases/10
- releases
  - 10
    - files –> points to ../../shared/files
- shared
  - files
``` 

This setup has been battle-tested on Contao 4 and everything worked fine. After the recent update to Contao 5.1, we noticed that some images were throwing an error at https://github.com/contao/image/blob/1.x/src/Image.php#L94:

```
Path "/httpdocs/shared/files/media/image/brochure6.png" is not inside root directory "/httpdocs/releases/10"
```

After some debugging I realized that the issue has its roots here: https://github.com/contao/contao/blob/5.x/core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php#L66

The `$item->getPathname()` equals the correct `/httpdocs/releases/10/files` but this is a symlink, so `$item->getLinkTarget()` returns `../../shared/files` which is relative, and ends up being the `/httpdocs/shared/files` root path (or prefix, dunno) for the filesystem adapter. Thus the error above – `/httpdocs/shared/files` is not inside the `/httpdocs/releases/10`.

It looks like the `files` folder can never be symlinked outside the Contao root/project directory. Is there any way this can be fixed?

/cc @Toflar @m-vo @ausi

**Comment by Toflar** [comment]
Why is this only happening in v5? The code is exactly the same in 4.13, no?

**Comment by m-vo** [comment]
> Why is this only happening in v5? The code is exactly the same in 4.13, no?

Could it be, that this only shows in Contao 5 because the images/downloads content elements now use the VFS to access the data? 

I did not check things myself, so just thinking out loud: If the target directory of a local filesystem mount is symlink, we should probably follow it and use the actual path. The referenced code in the `ConfigureFilesystemPass` was a workaround for when people symlinked directories inside their `files` directory (so a different scenario) and is now probably doing something it shouldn't do. :slightly_smiling_face:

**Comment by ausi** [comment]
Can this be fixed then by replacing https://github.com/contao/contao/blob/b1e5f553b82d14f93f9a7fbaf0b7c8763acb0abe/core-bundle/src/DependencyInjection/Compiler/ConfigureFilesystemPass.php?rgh-link-date=2023-01-10T14%3A04%3A45Z#L58 with: 

```php
$finder = (new Finder())->in($projectDir)->directories()->path('/^'.preg_quote($uploadDir, '/').'\/.+/');
```

**Comment by ausi** [comment]
Or maybe better:

```php
$finder = (new Finder())->in($projectDir)->directories()->path('/^'.preg_quote($uploadDir.'/', '/').'/');
```

**Comment by qzminski** [comment]
Together with @ausi we have figured out that this would be the solution:

```php
$finder = (new Finder())->in(Path::join($projectDir, $uploadDir))->directories();
```

The previous code snippets mentioned by @ausi  wouldn't work without `->followLinks()`, but this snippet is way cleaner.
