### ISSUE TITLE
Two-factor front end listener incomplete

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#567]
There are two issues with the `TwoFactorFrontendListener` class:

https://github.com/contao/contao/blob/43b4a54e1accf926b24a975019f8b2e6884402f1/core-bundle/src/EventListener/TwoFactorFrontendListener.php#L116

1. `$unauthorizedPage->redirect` is either `permanent` or `temporary`. @bytehead I assume you meant `autoforward`?

2. If 2FA has been set up and the 401 page has an auto-forward page, the listener will endlessly redirect me to the login screen. This is because it does not handle the case "token fully authenticated".

**Comment by leofeyer** [comment]
This also seems wrong:

https://github.com/contao/contao/blob/43b4a54e1accf926b24a975019f8b2e6884402f1/core-bundle/src/EventListener/TwoFactorFrontendListener.php#L116-L118

If the 401 page does not forward to another page, we return and **bypass the 2FA check**. Is this intended?

**Comment by leofeyer** [comment]
@bytehead Can you elaborate on what exactly the `TwoFactorFrontendListener` listener is supposed to do?

**Comment by bytehead** [comment]
Afaik this is a change from @aschempp - isn't it?

**Comment by leofeyer** [comment]
And there is an unresolved comment from you regarding these lines:

https://github.com/contao/contao/blob/43b4a54e1accf926b24a975019f8b2e6884402f1/core-bundle/src/EventListener/TwoFactorFrontendListener.php#L72-L74

> This is wrong. We only need to check for `TwoFactorToken`. It's actually a `TwoFactorTokenListener` so everything else does not matter.
> 
> This configuration parameter from the two-factor-bundle means something different:
> 
> ```
>     # The security token classes, which trigger two-factor authentication.
>     # By default the bundle only reacts to Symfony's username+password authentication. If you want to enable
>     # two-factor authentication for other authentication methods, add their security token classes.
>     security_tokens:
>         - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
> ```
> 
> https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
> 
> These possibly other tokens get wrapped into a `TwoFactorToken` anyway.

What about it?

**Comment by bytehead** [comment]
You can ignore this comment, I didn't get the intended behaviour of @aschempp's change of this.

**Comment by leofeyer** [comment]
> Afaik this is a change from @aschempp - isn't it?

It seems so: 11e2d7dd3b57fbb458d49dcbc79bc3792a1b4f21

I cannot judge if the commit needs to be reverted, though, unless I know what exactly the `TwoFactorFrontendListener` listener is supposed to do. Can you explain?

**Comment by bytehead** [comment]
as far as I can see - it possibly should be `autoforward` (makes more sense).

**Comment by aschempp** [comment]
Sorry to say, but the breaking changes are all from @bytehead. I think this one is the problem: https://github.com/contao/contao/pull/363/commits/884db46498fc09254bc55c91ac5c39488be83144#diff-cc3ec0911c6de9447bc74fb5e984923fL113

**Comment by aschempp** [comment]
but it sure should have been `autoforward`, that's my mistake 🙃

**Comment by bytehead** [comment]
My change just gets rid of the superfluous `else`.

**Comment by aschempp** [comment]
> I cannot judge if the commit needs to be reverted, though, unless I know what exactly the TwoFactorFrontendListener listener is supposed to do. Can you explain?

The listener does two things:

1. If you are logged in, 2FA is enforced but not configured for your user, it will force redirect you to the 2FA setup page
2. If you are in the 2FA authentication process (username+pw valid but 2FA not given), it will make sure you enter the code and don't navigate away. That's done with two approaches
    - if there is a 401 page, we assume there must be a login module on it (which will show the 2FA process). If the 401 page has a forward page, we also assume that page has a login module and is valid. In any of these cases, we throw an access denied exception, which will be catched by our exception handler and show the 401 page.
    - if no 401 is given, we assume the page where the user logged in from must be valid

**Comment by aschempp** [comment]
> My change just gets rid of the superfluous `else`.

yeah, but now the second process is also taken into account if the user has a `UsernamePasswordToken`

**Comment by bytehead** [comment]
True that. 🙈

**Comment by leofeyer** [comment]
So this is still a major issue:

https://github.com/contao/contao/blob/29771bad558ff39dc8ad02fc7c52cfcff9539707/core-bundle/src/EventListener/TwoFactorFrontendListener.php#L117-L120

If the error 401 page does not have the "autoforward" option enabled, the 2FA check is bypassed. Here is how you can test it:

1. Use the COD with an error 401 page that has an autofoward page.
2. Set up 2FA for a member.
3. Log out and log back in, but stop after you have entered the password.
4. Try to navigate the website – you should be stuck on the login page.

Now disable the autoforward option on the error 401 page and try to navigate the website. It is now possible to go anywhere.

**Comment by bytehead** [comment]
Confirmed, I'm on it.

**Comment by bytehead** [comment]
See #570.

**Comment by leofeyer** [comment]
Thanks. ❤️
