### ISSUE TITLE
Using a custom TinyMCE config shows raw HTML in frontend

### ISSUE THREAD

**Issue by JanMalte** [contao/contao#5675]
### Affected version(s)

4.13.14

### Description

If I use a custom TinyMCE template/config for a field, the raw HTML code is shown in the frontend instead of rendering.

Using the default TinyMCE config `'eval' => ['rte' => 'tinyMCE']` is working just fine.

**Backend view**
<img width="508" alt="grafik" src="https://user-images.githubusercontent.com/544986/212171207-58de7c52-2c04-4135-bf87-53bd086d032d.png">

**Frontend view**
<img width="565" alt="grafik" src="https://user-images.githubusercontent.com/544986/212171286-782051b7-c91e-4157-8af6-c941cce2698f.png">

**DCA config**
```php
<?php

$GLOBALS['TL_DCA']['tl_content']['fields']['text']['eval']['rte'] = 'simpleTinyMCE';
```

**TinyMCE template/config**
```php
<?php $this->extend('be_tinyMCE'); ?>

<?php $this->block('plugins'); ?>
  plugins: 'autosave charmap code fullscreen importcss link lists paste searchreplace stripnbsp tabfocus visualblocks visualchars',
<?php $this->endblock(); ?>

<?php $this->block('menubar'); ?>
  menubar: 'file edit insert view',
<?php $this->endblock(); ?>

<?php $this->block('toolbar'); ?>
  toolbar: 'link unlink | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | code',
<?php $this->endblock(); ?>

<?php $this->block('custom'); ?>
  paste_as_text: true,
<?php $this->endblock(); ?>
```

**Comment by ausi** [comment]
I think you have to name your custom config something like `tinyMCESimple` or `tinySimple` because HTML is allowed automatically for all `rte`s that begin with `tiny`.

As an alternative you can set `'allowHtml' => true,` in your `eval` array.

**Comment by leofeyer** [comment]
> I think you have to name your custom config something like `tinyMCESimple` or `tinySimple` because HTML is allowed automatically for all `rte`s that begin with `tiny`.

This is the correct answer. The `allowHtml` flag alone will not make Contao load the TinyMCE javascript IIRC.

@JanMalte Try using `tinySimple` instead of `simpleTinyMCE`.

**Comment by xx81** [comment]
Hi everybody,

I ran in the same problem today. I can confirm that the input is saved as HTML-Code only, when the name of the MCE-Konfiguration starts lowercase with the word *tiny*. (e.g. tinyMCE02)

If you try something like the following in your DCA

`$GLOBALS['TL_DCA']['tl_content']['fields']['text']['eval']['rte'] = 'TinyMCE02';`

it is not working.

Maybe it is a good idear to mention that in the documentation?
(I hope I have not read it over).

**Comment by fritzmg** [comment]
> Maybe it is a good idear to mention that in the documentation?

Added in https://github.com/contao/docs/commit/0c8e4b393702d97757a516130cc5931451e90ea1

**Comment by fritzmg** [comment]
Also added a note in https://github.com/contao/docs/pull/1156
