### ISSUE TITLE
Front end modules in page layout broken

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5684]
### Affected version(s)

5.1.0-RC1

### Description

I'm working on a fresh Contao 5.1.0-RC1 installation.

Problem:
1. create a new theme
2. create a new page layout (e.g. with 3 rows - header, main row and footer)
3. editing/hiding the "Included module" in the section "Front end modules" is not working, creating a new one also does not work

**Comment by fritzmg** [comment]
This happens because the `ModuleWizard` got changed in https://github.com/contao/contao/commit/11764d7f8cfe2973bd5c2bd15be7ed2bf26c6dfa and now the `module_image` CSS class is missing. The `modulewizard.js` will need to be adjusted accordingly.
