### ISSUE TITLE
Position of "Dark mode/Light mode" in BE User menu

### ISSUE THREAD

**Issue by jochi44** [contao/contao#5685]
### Affected version(s)

5.1.0-RC1

### Description

The new option "Dark mode/Light mode" (which I love btw) in the backend user menu (upper right corner) is placed at the very bottom.
This feels somehow misplaced.

On almost every application I know the "logout" option is at the very bottom of the menu.
In my opition the "Dark mode/Light mode" option should be moved further up.
I would even prefer to have no menu entry but a symbol in the top bar.

This is not a bug, maybe this topic can simply be discussed.

**Comment by leofeyer** [comment]
> On almost every application I know the "logout" option is at the very bottom of the menu.
> In my opition the "Dark mode/Light mode" option should be moved further up.
> I would even prefer to have no menu entry but a symbol in the top bar.

I agree with both. 👍

**Comment by fkaminski** [comment]
Proposal: A simple darkmode symbol
[darkmode-white+alpah.zip](https://github.com/contao/contao/files/10424464/darkmode-white%2Balpah.zip)
