### ISSUE TITLE
5.1.0-RC1 Move the preview link

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#5686]
### Description

I really like the new feature favorites and that the edit link is in the user dropdown.

For me as a user it is not clear why the link for "Preview links" is placed in the group System and not like the favorites in the dropdown.

What do you think about adding it there and remove it from the group System.

**Kevin Jones**
kevin@contao.org
------
- Profile
- Security
- Favorites
- Preview links
- Logout
-----
Light mode

**Comment by fritzmg** [comment]
Preview links are not related to the back end user, they are part of the whole system. I think only things that are solely related to the back end user should be in the back end user dropdown.

**Comment by netzarbeiter** [comment]
You are right of course
