### ISSUE TITLE
Warning in ModuleNavigation when hard limit is not array key

### ISSUE THREAD

**Issue by TurboTurro** [contao/contao#5699]
### Affected version(s)

4.13.15

### Description

Contao Version: 4.13.15
PHP Version: 8.1
Error Message: "Warning: Undefined array key x"
Code of File: https://github.com/contao/core-bundle/blob/4.13/src/Resources/contao/modules/ModuleNavigation.php#L85
Screenshot: https://pasteboard.co/kPaPRRMDhMng.png
Reproducibility: Create navigation module set hard limit f.e 2 and activate debugmode. You'll get the warning mentioned above.

Maybe you can check the key $level in the array $trail in advance?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/5709
