### ISSUE TITLE
Default setting of type text is ignored

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#57]
**Affected version(s)**
 
- LTS 4.4 
- 4.6 not tested

**Description**  
If you use the new array syntax to define an sql type for a text field, no default value is set in the sql satement even if it's defined in the config

```php
'sql' => ['type' => 'text', 'default' => null]
```

The created sql statement is:

```
ALTER TABLE tl_example ADD content LONGTEXT NOT NULL
```
This leads to an exception if mysql is run in mode `STRICT_TRANS_TABLES`.

**How to reproduce**  

1. Run Mysql in mode `STRICT_TRANS_TABLES`
2. Define a new text field in a dca definition with the sql statement mentioned above
3. Update database with the install tool
4. Try to create a new entry using the backend.

**Comment by fritzmg** [comment]
Afaik, Doctrine ORM does not have an attribute named "default". I think you need to define it this way:
```php
'sql' => ['type' => 'text', 'nullable' => true, 'options' => ['default' => null]]
```
Though may be you can omit the `'options' => ['default' => null]` altogether.

**Comment by dmolineus** [comment]
Thanks for your response. Define `nullable` doesn't make any difference, neigther for type `text` nor type `string`. With or without `default` or `options.default`. 

Setting default for a text field is ignored completely.

```php
// Default value is ignored
$GLOBALS['TL_DCA']['tl_example']['fields']['content']['sql'] = ['type' => 'text', 'nullable' => true, 'options' => ['default' => '1'], 'default' => '2'];

$GLOBALS['TL_DCA']['tl_example']['fields']['headline']['sql'] = ['type' => 'string', 'length' => 255, 'options' => ['default' => '1'], 'default' => '2', 'nullable' => true],
//
```

Result is:

```sql

ALTER TABLE tl_example CHANGE content content LONGTEXT NOT NULL
ALTER TABLE tl_example CHANGE headline headline VARCHAR(255) DEFAULT '2' NOT NULL

```

**Comment by leofeyer** [comment]
That is most likely because [BLOB and TEXT columns cannot have DEFAULT values](https://dev.mysql.com/doc/refman/5.6/en/blob.html).

**Comment by dmolineus** [comment]
After digging into the code and into [doctrine docs](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.8/reference/schema-representation.html#portable-options) I found the right option. It's called `notnull` and not `nullable`.

**Comment by fritzmg** [comment]
Also thx for posting the link to the right doctrine docs - I was never sure which ones apply 😁  or where to find it...
