### ISSUE TITLE
Bug im Zusammenhang mit StringUtil.php und einer selten vorkommenden php.ini Parameter

### ISSUE THREAD

**Issue by Blog404DE** [contao/contao#5700]
### Affected version(s)

4.13.15 / PHP 8.1.13

### Description

Abhängig von der PHP-Konfiguration kommt es in der [_bundle/src/Resources/contao/library/Contao/StringUtil.php_](https://github.com/contao/contao/blob/0d1d079fab2eaf6ac373d8c7a0e30c6d8e029217/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L1240) kann es in der Funktion _numberToString_ zu der folgenden Fehlermeldung kommen:

> ValueError(code: 0): Unknown format specifier \"-\"

### Das Problem liegt wiefolgt:

In der PHP.ini die Einstellung _precision_ auf den Wert -1 eingestellt hat, kommt es zu dem erwähnten Fehler. -1 ist dabei ein zugelassener Konfigurations-Wert, welcher PHP anweist ein "verbesserter Algorithmus zur Rundung von Gleitkommazahlen" zu verwenden (laut PHP-Homepage). 

In der Funktion wird, sofern kein $precision übergeben wurde, die Gleitkomma-Präzision über den PHP-Konfigurationsparameter übernommen:

```php 
$precision = (int) \ini_get('precision');
```

Ein paar Zeilen weiter gibt es folgender sprintf-Aufruf:
```php 
sprintf('%.' . ($precision - 1) . 'e', $number)
```

Bei einem $precision von -1 wird der Format-Parameter wie folgt aussehen: _"%.-2e",_ was in der Form ungültig ist, soweit ich das sehe.

Aufgefallen ist mir der Fehler bisher erst im Zusammenhang mit dem RockSolid Slider (aktuelle Version) von @ausi im Zusammenhang mit einem Auftrag zur Migration einer Contao 3 Seite auf Contao 4.13 LTS. 

### Lösung

In Contao selber sollte ein negativer Precision-Wert in der php.ini abgefangen werden. Die Frage wäre hier, welcher Wert man stattdessen nimmt (z.B. der Default Wert von 14?).

**Comment by ausi** [comment]
See #5786
