### ISSUE TITLE
Breadcrumbs in der Seitenstruktur (Backend) werden nicht korrekt verlinkt.

### ISSUE THREAD

**Issue by jpkalus** [contao/contao#5707]
### Affected version(s)

4.13.8

### Description

Die Pagemounts für Benutzergruppen besagen: "Unterseiten werden automatisch hinzugefügt".

Im Seitenbaum funktioniert das auch komplett richtig. Wenn die Benutzergruppe eine Seite gemounted bekommen hat, gilt das auch für alle folgenden Unterseiten.

In den Breadcrumbs der Seitenstruktur sind aber nur die Seiten verlinkt, die der Benutzergruppe explizit zugewiesen wurden. Hier wird die Vererbung nicht berücksichtigt.

Erwartungskonform wäre, dass auch hier die Unterseiten einer gemounteten Seite verlinkt sind.

**Comment by fritzmg** [comment]
> 4.13.8

Please always test with the newest version first.

**Comment by jpkalus** [comment]
Same behavior with 4.13.15.

**Comment by leofeyer** [comment]
> In den Breadcrumbs der Seitenstruktur sind aber nur die Seiten verlinkt, die der Benutzergruppe explizit zugewiesen wurden

Wie lässt sich das Problem denn in der Online-Demo oder einer frischen Contao-Installation reproduzieren?

**Comment by aschempp** [comment]
Verstehe ich richtig dass die Seiten im Breadcrumb angezeigt werden aber keinen Link haben?

**Comment by jpkalus** [comment]
> Verstehe ich richtig dass die Seiten im Breadcrumb angezeigt werden aber keinen Link haben?

Ja!

**Comment by aschempp** [comment]
Ich denke das verhalten ist richtig, denn auf diese Seiten hast du ja auch keinen Zugriff? Also der Node-Filter kann jedenfalls nicht gehen, oder hat das Breadcrumb auch einen Link zum Frontend?

**Comment by fritzmg** [comment]
@jpkalus how is the problem reproduced exactly? Please also show a screenshot.

**Comment by jpkalus** [comment]
![1](https://user-images.githubusercontent.com/34371720/214855509-b590baff-87e3-438d-9b8d-21a9585aa80e.png)

ServiceNow ist explizit für die Benutzergruppe gemountet.
Business Intelligence ist nur implizit durch Fokusthemen gemountet.

![2](https://user-images.githubusercontent.com/34371720/214855779-0cecf562-0f6c-4834-8865-7e56638082cf.png)

Die Rechte sind in beiden Fällen identisch.

ABER:
![3](https://user-images.githubusercontent.com/34371720/214855920-4c955367-4c2e-4210-872a-aeca046e42ff.png)
Business Intelligence ist NICHT VERLINKT (rot)

![4](https://user-images.githubusercontent.com/34371720/214855997-ce568652-1bdd-43bd-9cb3-15e76213685e.png)
ServiceNow ist verlinkt (grün)

**Comment by aschempp** [comment]
Du hast in den Benutzereinstellungen sowohl "Fokusthemen" als auch "ServiceNow" angeklickt? Könntest du das kurz screenshoten?

Was passiert wenn du "ServiceNow" nicht auswählst? Es müsste ja auch explizit freigegeben sein?

**Comment by jpkalus** [comment]
Der erste Screenshot meiner vorherigen Nachricht sind die Pagemounts der zugewiesenen Gruppe. Da siehst du bereits alles.

> Du hast in den Benutzereinstellungen sowohl "Fokusthemen" als auch "ServiceNow" angeklickt?

Ja, siehe Screenshot 1

> Was passiert wenn du "ServiceNow" nicht auswählst? Es müsste ja auch explizit freigegeben sein?

Dafür habe ich als Vergleich "Business Intelligence" nur implizit gemountet. Deshalb ist dort der Breadcrumb nicht verlinkt.

**Comment by MacKP** [comment]
Bei mir das selbe Problem: Die Redakteure haben nur einen Link auf der Root-Seite und 'Alle'. Die Zugriffsrechte sind nur in der Root-Seite gesetzt (werden also vererbt). Pagemount ist die Root-Seite. Bei Artikeln können die Benutzer nicht die einzelnen Unterseiten anklicken (bei allen Unterseiten wird kein Link gesetzt). Ich gehe nicht davon aus, dass das Verhalten so richtig ist, da die Redaktuere ja an sich Zugriff darauf haben. Wenn das Seiten wären, die außerhalb des Pagemounts liegen würden, dann wäre das ja noch erklärbar. So ist das allerdings etwas blöd und umständlich zu bedienen. Contao Version bei mir ist die 4.13.15

**Comment by leofeyer** [comment]
Wie kann ich das denn in der Official Demo reproduzieren?

**Comment by MacKP** [comment]
Ab ins Backend. Switch zu h.lewis. Seiten anklicken. Dort dann die Artikel der Seite 'News' bearbeiten anklicken. Nun sieht man die Artikel der Seite News und die übergeordnete Seite 'Modules' ist in der Breadcrumb zu sehen.
'Modules' ist nicht anklickbar, nur 'Contao Official Demo' und 'Alle'.
Wenn man sich die ganzen Artikel anzeigen lässt, dann kann man erkennen, dass man alle bearbeiten kann, also auch die Artikel in 'Modules'. Es sollte also ein Link vorhanden sein in der eingeschränkten Ansicht.

Viele Grüße

**Comment by MacKP** [comment]
Hatte vergessen: Gegenprobe als Admin ist natürlich ein Link vorhanden (k.jones).

**Comment by leofeyer** [comment]
Das Problem ist dasselbe wie in #2895. Aufgrund der fehlenden Prüfung auf übergeordnete Mounts, gibt die `hasAccess()`-Methode in der Backend.php:971 `false` zurück und es wird kein Link generiert. Wir müssen das wohl nochmal diskutieren.
