### ISSUE TITLE
Twig Componenten-Template enthält "extends" statt "use"

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#5710]
### Affected version(s)

5.0

### Description

Legt man über das Backend ein neues Componenten Template an, dann wird `{% extends "@Contao/component/_component.html.twig" %}` verwendet. Korrekt wäre `use`
Siehe dazu https://contao.slack.com/archives/CK4J0KNDB/p1674477273511159?thread_ts=1674475303.558349&cid=CK4J0KNDB

**Comment by m-vo** [comment]
See #5715
