### ISSUE TITLE
Core twig templates aren't selected by default if a custom twig template exists

### ISSUE THREAD

**Issue by jamesdevine** [contao/contao#5719]
### Affected version(s)

5.0

### Description

In Contao 4, you can add a custom content element template like `ce_text_custom.html5` and Contao will continue using `ce_text.html5` by default for new text elements. In order to use `ce_text_custom.html5` you have to specify this on the element settings by changing the "Content element template" select field.

In Contao 5, if you add a custom twig template for a content element then it's possible that this becomes the default instead of the core template (I believe the sorting is alphabetical, so it depends what you name the custom template as to whether or not it becomes the default).

The expected behaviour is that Contao prefers default core templates and only uses custom templates when they are explicty set like in Contao 4.

This can be recreated by creating a custom Twig template for a text element:
`/templates/content_element/text/custom.html.twig`

This now becomes the default for all text elements, instead of `content_element/text` from ContaoCore which should still be the default.

![templates](https://user-images.githubusercontent.com/1336721/214336590-3c25a020-b01d-466d-9a80-c2b3dc14fe55.png)

**Comment by m-vo** [comment]
See #5720
