### ISSUE TITLE
Password visibility toggle

### ISSUE THREAD

**Issue by k-webdesign** [contao/contao#573]
**Description**
Hey ho,

könnten wir beim Login Modul (Backend & Frontend) einen Passwort Toggle einbauen? 
Ich find den einfach super praktisch, gerade wenn man sich mobil anmeldet oder ein gespeichertes Passwort kurz mal mit einem Klick überprüfen möchte 👀

Ob das nun ein Auge, der Text "Show" und "Hide" oder eine Checkbox unterhalb des Inputs ist, da bin ich flexibel. Ich denke, das Augen-Icon wäre international 🤷🏼‍♀️

**Example**  
<img width="406" alt="Screenshot 2019-07-10 23 23 59" src="https://user-images.githubusercontent.com/4130440/61006102-d01d8580-a369-11e9-9962-ff0f41cbfa2d.png">
<img width="419" alt="Screenshot 2019-07-10 23 23 54" src="https://user-images.githubusercontent.com/4130440/61006103-d01d8580-a369-11e9-9be4-91436e89f088.png">

**Comment by ausi** [comment]
Ich bin mir nicht sicher ob wir das einbauen sollen.

Es gibt bereits Browser die das selbst machen (IE, Edge) sowie Erweiterungen für die restlichen Browser. Diese würden das Auge dann doppelt haben, einmal von Contao und einmal nativ.

Und speziell im Fall des gespeicherten Passworts ist es fraglich ob es aus Security-Sicht richtig ist. Was wenn du z. B. dein mobiles Gerät kurz aus den Augen lässt?

**Comment by aschempp** [comment]
Ich sehe das auch eher als Aufgabe des Browsers, und nicht der Applikation. Ich möchte sowas bei mir nie haben, ich verwende einen Passwort-Manager der sich darum kümmert. Wenn dann müsste das Feature manuell aktivierbar sein, aber ich bezweifle dass es dann jemand überhaupt nutzen würde?

**Comment by Toflar** [comment]
Von mir auch 👎 , nicht unsere Aufgabe.

**Comment by k-webdesign** [comment]
Ok. Es setzt sich auf immer mehr Websites durch, daher mein Gedanke, das auch zu integrieren. Es ist gerade bei langen Passwörtern, Mobilgeräten und zum Abgleich der doppelten Eingabe des PWs bei einer Registrierung hilfreich. Natürlich könnte man das Formular auch abschicken und es eben noch mal eingeben, nur ist das ärgerlich, wenn das durch den Toggle verbessert werden kann. 
Und bis das letztendlich Standard in den Browsern wird, dachte ich an diese kleine Optimierung innerhalb von Contao.

@ausi wenn ich das Mobilgerät aus den Augen lasse, wenn das PW gespeichert ist, hab ich generell ein Problem :) Ich glaube, dass man das Anzeigen des PW speziell auf Mobilgeräten durch die Touch ID oder ähnliches noch mal absichern kann. Der Browser fragt mich beim Anzeigen eines gespeicherten Passworts ja auch noch mal nach dem PW des angemeldeten Users.

**Comment by ausi** [comment]
> wenn ich das Mobilgerät aus den Augen lasse, wenn das PW gespeichert ist, hab ich generell ein Problem :)

Aber ein deutlich kleineres. Es ist ein Unterschied ob jemand sich einmalig kurz einloggen kann auf deinem Gerät oder aber das Passwort kennt und sich auf ewig auch von einem anderen PC aus einloggen kann.

> Der Browser fragt mich beim Anzeigen eines gespeicherten Passworts ja auch noch mal nach dem PW des angemeldeten Users.

Genau das ist der Punkt, der Browser kann für die Anzeige des Passworts extra Sicherheitsvorkehrungen setzen die er für das Ausfüllen des Passworts nicht braucht.

**Comment by asaage** [comment]
Hab das nicht selbst probiert aber mit ein bisschen JS kann man sich das einfach dazubauen.
Wen's interessiert: https://www.w3schools.com/howto/howto_js_toggle_password.asp
Denke mal, den Toggle nicht unbedingt als Input definieren und dann sollte es gehen.

**Comment by leofeyer** [comment]
> Es setzt sich auf immer mehr Websites durch

Wo finde ich es denn noch, außer bei Adobe?

**Comment by k-webdesign** [comment]
Aus dem Stegreif, mehr müsste ich jetzt auch gezielt nachschlagen:

Google: ![Bildschirmfoto 2019-07-15 um 10 56 33 AM](https://user-images.githubusercontent.com/4130440/61205172-a492f600-a6ef-11e9-98d0-2c33c5147502.png)

Paypal: ![jdkbrpTZ](https://user-images.githubusercontent.com/4130440/61207577-bc6d7880-a6f5-11e9-885a-5fb595e67e67.png)

**Comment by k-webdesign** [comment]
Aus dem Stegreif, mehr müsste ich jetzt auch gezielt nachschlagen:

- Paypal
- Google
- Zooroyal

![jdkbrpTZ](https://user-images.githubusercontent.com/4130440/61207716-18380180-a6f6-11e9-9cf1-418cc9e1e808.png)

![Bildschirmfoto 2019-07-15 um 10 56 33 AM](https://user-images.githubusercontent.com/4130440/61207761-300f8580-a6f6-11e9-8000-8a38802432a7.png)

**Comment by leofeyer** [comment]
Jetzt wo ich mal darauf geachtet habe, muss ich feststellen, dass das doch ein verbreitetes Feature ist. Ich stimme daher für das Feature.

**Comment by bennyborn** [comment]
Käme darauf an wie man es implementiert. Bei unseren Seiten verzichten wir immer auf sämtliche Stylesheets oder JavaScripts aus dem Core da wir unsere Installationen so "schlank" wie möglich halten wollen. Wenn es sich also nur um eine reine JS-Lösung handelt die über das Theme gesteuert wird fände ich es nicht weiter schlimm. Persönlich brauch ich so etwas nicht ^^

**Comment by m-vo** [comment]
Zur Referenz - eine verwandte Diskussion gibt es bei der WICG: https://discourse.wicg.io/t/attribute-to-toggle-password-visibility/3809

**Comment by leofeyer** [comment]
Siehe #3052.
