### ISSUE TITLE
DCA - Subpalettes und Legends

### ISSUE THREAD

**Issue by keved93** [contao/contao#5736]
### Affected version(s)

4.13+, 5

### Description

https://github.com/contao/contao/blob/5.x/core-bundle/src/DataContainer/PaletteManipulator.php#L89

**Anwendung:** Es existiert ein Modul, das ein Content Element mit einen Select Feld bereitstellt. Je nach ausgewählter Option in diesem Select Feld soll sich das DCA vom Element erweitern. Jedoch sind es teils mehr als 10 DCA Felder pro Option, die auch Gruppiert werden müssen, um es für den Kunden übersichtlich darstellen zu können.

--

**Problem:** Der PaletteManipulator lässt bei Subpalettes (#L110) keine neue Legends zu (#L119). Diese werden einfach durch den Paramenter #L110 "true" in #L119 übersprungen.

**Alternative (veraltet):** Subpalettes als Globales Array hinzufügen, was derzeit auch ohne Probleme funktioniert.
`$GLOBALS['TL_DCA']['tl_content']['subpalettes']['xyz'] = ';{new_title_legend},title,subtitle;{new_teaser_legend},teaser;{new_image_legend},image;{new_redirect_legend},redirect';`

--

**Lösungsvorschlag 1:** `applyToSubpalette(string $name, string $table, bool $skipLegends = true)`, um selbst bestimmen zu können, wenn eigene Legends in Subpalettes hinzugefügt werden.

**Lösungsvorschlag 2:** Man nimmt den Parameter #L110 **true** ganz weg.

--

Der PaletteManipulator ist eine wirklich gute Sache, aber diese Einschränkung bei den Subpalletes ergibt derzeit leider keinen Sinn, weshalb wir den PaletteManipulator so leider nicht mehr verwenden können, um eine einheitliche Schreibweise im DCA beizubehalten.

**Comment by fritzmg** [comment]
Additional legends/fieldsets in subpalettes are not supported, this is not a bug.

**Comment by keved93** [comment]
Not a bug, but a problem.

`$GLOBALS['TL_DCA']['tl_content']['subpalettes']['xyz'] = ';{new_title_legend},title,subtitle;{new_teaser_legend},teaser;{new_image_legend},image;{new_redirect_legend},redirect'; `allows legends in additional subpallets

PallateManipulator doesn't allow this, but why? It doesn't really make sense.

**Comment by fritzmg** [comment]
> PallateManipulator doesn't allow this, but why? It doesn't really make sense.

As already said, legends/fieldsets in subpalettes are not supported. See the following example:

```php
// contao/dca/tl_content.php
$GLOBALS['TL_DCA']['tl_content']['subpalettes']['addImage'] .= ';{Foobar},listitems;';
```

After clicking **Add image** in the backend for a _Text_ content element, the edit mask will look like this:

<img src="https://user-images.githubusercontent.com/4970961/215081275-83e63f83-12ee-4489-9b73-c4e007c55695.png" width="400">

For `__selector__`s that are `select` `inputType`s it probably works, as the whole page is refreshed.

In any case, this is not a bug - but I think a feature request to allow `$skipLegends` to be set for `applyToSubpalette` might make sense. Though may be there are other issues when using legends in subpalettes, besides for `checkbox` subpalettes?

**Comment by keved93** [comment]
Yes, you are right, it is neither a bug nor a problem. We just tested it again. There are differences between `Checkbox Subpalettes` and `Select Subpalettes`.

Checkbox Subpalette and Legends not working:
$GLOBALS['TL_DCA']['tl_content']['subpalettes']['addImage'] .= ';{Foobar},listitems;';

Select Subpalettes and Legends works:
$GLOBALS['TL_DCA']['tl_content']['subpalettes']['markdownSource_sourceFile'] = ';{Foobar},listitems;';

**Comment by aschempp** [comment]
The solution to your requirements is to register an onload_callback on the DCA and manipulate the palette depending on the current record on the page. If only one field triggers the "configuration" you could also use different palettes (like "type" does in a lot of places in Contao). You can't use subpalettes for that.
