### ISSUE TITLE
PageNotFoundException auf 404-Seite

### ISSUE THREAD

**Issue by cwittstock** [contao/contao#5738]
### Affected version(s)

4.13.15

### Description

Wir haben auf der 404-Seite einen News-Leser eingebunden. Bei bestimmten Links kommt nun zu einer Exception, die aus unserer Sicht falsch ist:

- seite-existiert-nicht.html -> Führt zur funktionalen 404-Seite.
- parent-existiert-nicht/seite-existiert-nicht.html -> Führt zur funktionalen 404-Seite.
- parent-existiert/alias-existiert-nicht.html -> Führt zur PageNotFoundException (500er)

Folgender Hinweis könnte noch wichtig sein: Wir haben das Legacy-Routing aktiviert und ".html" als Suffix eingetragen.

![Screenshot Page not found (500 Internal Server Error)](https://user-images.githubusercontent.com/34371923/215085026-548a293b-2ef1-404f-a802-f7d64b9b1f81.png)

Im Stacktrace ist zu sehen, dass die 404-Seite aufgerufen wird und dann beim Einbinden des News-Lesers der Fehler auftritt. Es scheint also eine News mit dem Alias "application-management-services" gesucht zu werden. 

Ich habe mehere Dumps gemacht und bin der Meinung, dass es ein Bug ist, und ich keinen Konfigurationsfehler vorliegen habe, richtig?

**Comment by aschempp** [comment]
Verstehe ich richtig dass du auf der 404-Seite den News-Leser eingebunden hast?

**Comment by cwittstock** [comment]
Ganz genau, ja.

**Comment by aschempp** [comment]
Das solltest du nicht machen 😅 dann ist dein Problem gelöst.

**Comment by cwittstock** [comment]
Haha, danke. Die Lösung hatte ich auch schon. :D
Hast du noch eine? ;)

**Comment by fritzmg** [comment]
> Wir haben auf der 404-Seite einen News-Leser eingebunden.

Why do you have a news reader on the 404 page?

**Comment by cwittstock** [comment]
Warum werden vermeintliche Bugs mit solchen unsinnigen Fragen beantwortet? Wenn es kein Bug ist, dann schließt bitte diesen Issue. Andernfalls sollten wir uns auf das Problem konzentrieren.

**Comment by fritzmg** [comment]
> Andernfalls sollten wir uns auf das Problem konzentrieren.

Which we are doing. Having a reader on the 404 page does not work currently. The question is now whether this is a known limitation - or if there is something we should do about it, if there is a valid use case. Hence the question what your exact use case is. It is _not_ a "nonsensical question".

**Comment by cwittstock** [comment]
Contao wirft an der Stelle einen 500er Server-Fehler. Es ist völlig unerheblich, warum wir einen News-Reader auf der 404-Seite eingebaut haben. Dies ist schlichtweg ein Fehler in der Programmierung, da es keinen Sinn ergibt nach einem News-Beitrag mit dem Alias alias-existiert-nicht.html in dem Nachrichtenarchiv zu suchen.
Es wird mir hier doch sicher niemand glaubhaft versichern wollen, dass ein 500er eine "bekannte Einschränkung" ist.

Und letztendlich ist es doch eine Marketing-Entscheidung, wenn die 404-Seite nicht einfach nur ein "Oops, die Seite existiert nicht." ausgibt, oder wie im Falle der akquinet AG ein paar nützliche Links und Nachrichten-Beiträge des Unternehmens: [https://akquinet.com/alias-existiert-nicht.html](https://akquinet.com/alias-existiert-nicht.html)

(Der News-Reader ist nun übrigens vorrübergehend deaktiviert - in der Hoffnung, dass er bald wieder aktiviert werden kann.)

**Comment by asaage** [comment]
500er sollte nicht sein - da würde ich zustimmen.
News-Liste würde ich verstehen - ich denke das funktioniert auch.
News-Reader: dafür fehlt mir die Fantasie (der müsste ja auf was reagieren, was nicht existiert).

**Comment by cwittstock** [comment]
Jetzt verstehe ich auch die Problematik. Damit muss ich wohl etwas zurückrudern und mich entschuldigen:
Wir haben natürlich keinen Nachrichtenleser, sondern eine Nachrichtenliste dort eingebunden.
![grafik](https://user-images.githubusercontent.com/34371923/216133842-c97309d1-1b2e-46f5-bf08-3109874aaa5f.png)

Damit ist die Frage nach der Sinnhaftigkeit dieses Elements auf der 404-Seite auch hinfällig, oder? :D

**Comment by asaage** [comment]
Und hat diese Liste bzw. deine darin verknüpften Archive eine Weiterleitungsseite, die vom Typ PageRegular ist?
Dann müsste das doch eigentlich gehen.

**Comment by cwittstock** [comment]
Ja, ist sie. Eingebunden ist dieses Nachrichten-Archiv: https://akquinet.com/news-archiv.html. Als Weiterleitungsseite ist news-details eingebunden. Deswegen ist das die Detail-Ansicht der News: https://akquinet.com/news-details/grundstein-fuer-colocation-rechenzentrum-in-hamburg-gelegt.html
Hab ich ggf. doch etwas falsch konfiguriert?

**Comment by fritzmg** [comment]
You likely configured a newsreader in your newslist.

**Comment by cwittstock** [comment]
In der Nachrichtenliste ist ein Nachrichtenleser konfiguriert, ja. Ist das nicht normal, bzw. nötig, damit ich die Nachrichten verlinken und somit lesen kann?

![grafik](https://user-images.githubusercontent.com/34371923/216159517-d3c92511-64f7-4b76-9a95-73508c467ab9.png)

**Comment by fritzmg** [comment]
> In der Nachrichtenliste ist ein Nachrichtenleser konfiguriert, ja. Ist das nicht normal, bzw. nötig, damit ich die Nachrichten verlinken und somit lesen kann?

When you configure a newsreader in your newslist, the newslist module replaces itself with the selected newsreader module automatically if an "auto item" parameter is detected. You use this feature when you want to use a newslist and a newsreader on the same page interchangeably. If you have your newsreader on a separate page you do not need to select a newsreader in your newslist module. Otherwise you will run into issues, e.g. when the newslist module is added to a page layout. This will make all other readers (like event readers) not work anymore - and also produce issues like in your case. See also the [warning](https://docs.contao.org/manual/en/core-extensions/news/frontend-modules/#module-configuration) in the manual.

**Comment by cwittstock** [comment]
Das war mein Fehler! Danke! Und danke auch für eure Hartnäckigkeit. :D

**Comment by fritzmg** [comment]
I hope you see now that my initial question was pertinent to the investigation of this issue, regardless of how you felt ;)
