### ISSUE TITLE
Link-Insert-Tag produces false output

### ISSUE THREAD

**Issue by SpeGal** [contao/contao#5744]
### Affected version(s)

4.19

### Description

I used four insert tags in a row for a mobile sub navi:
`{{link::2971}}{{link::2972}}{{link::229}}{{link::225}}`

Two of the created links contained these elements the other two didn't:
`target="_blank" rel="noreferrer noopener"`

Comparing the page settings of all four they were identical. They all were regular pages. Only after comparing the database entries for each of the pages did I find that two of those pages must have been of the page type "external redirections" in a past life and had back then be set to "open in new window". This information was still stored in the database even after changing the page type to regular. The insert tag recognizes this entry though and creates the link accordingly.

I consider this a bug. But a potential useful one :) Just the way it's set up is not good. One should not have to look in an old setting to find the issue and it shouldn't happen on accident. If we want to use it like that, the "open in new window" setting should also appear in the "regular page". Or else create a new insert tag that can create _blank links like suggested here:
#2802

**Comment by asaage** [comment]
see (or wait for) https://github.com/contao/contao/pull/5706

**Comment by fritzmg** [comment]
It's a good point though, sometimes you may want to have `target="_blank"` for regular pages or internal redirect pages too.
