### ISSUE TITLE
Inconsistency in the _table.html.twig template

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#5745]
### Affected version(s)

5.0

### Description

There is an extra block `table_body_cell_content` in the `<td>` elements of the `<tbody>` element:

https://github.com/contao/contao/blob/c4d75fd853da7c2ac53585e152fc66aeb66cc12c/core-bundle/contao/templates/_new/component/_table.html.twig#L125-L129

However, there is no equivalent for the `<td>` elements of the `<thead>` and `<tfoot>` elements. What is the reasoning behind this?

@m-vo /cc

**Comment by m-vo** [comment]
See #5746
