### ISSUE TITLE
Logout should not remove the preview cookie

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#575]
**Affected version(s)**

4.8

**Description**  

When logging out of the back end, the `_contao_preview` cookie is removed, so the only way to debug the login page is:

* Log into the back end
* Enable the debug mode
* Manually remove the `PHPSESSID` cookie
* Reload the page

We should not remove the `_contao_preview` cookie if the debug mode is enabled IMHO.

**How to reproduce**  

Log into the back end, enable the debug mode and then log out. The debug bar is no longer shown.

**Comment by aschempp** [comment]
I don't think that's a good idea. The JWT setup is mean to only work if you are logged in to the back end. If you want to debug the login page, we should better implement something like https://github.com/contao/contao/pull/574

**Comment by leofeyer** [comment]
Agreed.
