### ISSUE TITLE
New Composer version (>= 2.2) with allow-plugins Feature breaks installation with Contao Manager

### ISSUE THREAD

**Issue by HoTodo** [contao/contao#5750]
### Affected version(s)

4.13, 5.0

### Description

When installing a new Contao instance on a system with a Composer of version 2.2 or higher the installation fails and saying that `contao-installer` (and one other package I cant remember right now) contains a Composer plugin that is not part of the allow-plugin configuration.

When running the installation on the command line, Composer asks to add the Plugin to the configuration. But with the Contao Manager there is no such option. It just fails.

I think the `composer.json` that is generated by the Contao Manager should already contain the necessary allow-plugin configuration, so that the installation does not need any user interaction to succeed.

**Comment by fritzmg** [comment]
This is an issue of the Contao Manager. Please create an issue [there](https://github.com/contao/contao-manager/issues/new/choose).

When not using the Contao Manager, the default `composer.json` of the Managed Edition already allows the necessary plugins: https://github.com/contao/managed-edition/blob/d4de2c6df3e07205edab9ba22db76997334824d0/composer.json#L21-L28

**Comment by HoTodo** [comment]
Sorry. I was not fully aware of your repository structure. Thanks for the hint.
I created the issue for the `contao-manager` repo.
