### ISSUE TITLE
Basic entities such as `[-]` and `[nbsp]` no longer work in Contao 5

### ISSUE THREAD

**Issue by heimseiten** [contao/contao#5754]
### Affected version(s)

5.1.*@RC

### Description

Bspw. im Inhaltselement "Text" oder im Inhaltselement "Überschrift". Habe es gerade noch mal mit einer frischen 5.1.*@RC versucht.

**Comment by fritzmg** [comment]
I can confirm the problem in `5.0.x-dev` and `5.x-dev`.

**Comment by heimseiten** [comment]
Perhaps another useful "Basic Entity" could be added on this occasion: #5755

**Comment by ausi** [comment]
We need to add `['eval' => ['basicEntities' => true]]` to fields we want to support. I’m not sure if that was on purpose to not add this configuration to any field in #4453

**Comment by leofeyer** [comment]
It does not seem so:

<img width="471" alt="" src="https://user-images.githubusercontent.com/1192057/216976077-b6fe4810-0130-4e44-9806-1d5b47e7a086.png">

We probably just missed the open task.

So which fields need `['eval' => ['basicEntities' => true]]`?

**Comment by fritzmg** [comment]
In theory all fields, since they can occur anywhere. If we do not want to enable it everywhere, we might need a migration of some sort?

**Comment by ausi** [comment]
> In theory all fields

IMO only text fields (not numbers, dates, internal names, ids, alias, CSS classes, domains, URLs, etc.) 
that are meant to be output in the frontend.

**Comment by fritzmg** [comment]
Yes - I meant all fields that are output somewhere in the front end by default. Also including some HTML attributes, like `tl_content.titleText`. You could have

> [gt] click here

and in Contao 4 this would result in

```html
<a … title="&gt; click here">
```

**Comment by leofeyer** [comment]
As discussed in the Contao call, we have to set `'basicEntities' => true` to all `'inputType' => 'text'` fields that do not have a `rgxp`. Except fields such as CSS ID or module title (which is never output).

**Comment by aschempp** [comment]
looks like this is very similar to all fields that should support insert tags? Not sure if we have (the same) rule for that?

**Comment by leofeyer** [comment]
Since there are over 250 text fields to check, I have created a PR that only fixes the issue for headlines: #5895 I think that is the 95% case. And if anyone ever wants to spend time on digging through the remaining 5%, they are welcome to do so.
