### ISSUE TITLE
Add a "Non-breaking space" to the Insert-Tags "Basic Entities" with e.g. [ ]

### ISSUE THREAD

**Issue by heimseiten** [contao/contao#5755]
### Description

It would be very handy to control not only when to wrap a word, but also when not to wrap two words. This would give better control over the formatting in the mobile view.

The "Basic Entity" could be [ ] or [_]

https://en.wikipedia.org/wiki/Non-breaking_space

**Comment by fritzmg** [comment]
`[nbsp]` already exists. See https://docs.contao.org/manual/en/article-management/insert-tags/#basic-entities

**Comment by heimseiten** [comment]
Sorry and thank you!
