### ISSUE TITLE
Remove the password option in the install-web-dir command

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#577]
By the way, did we drop support for the password argument on `contao:install-web-dir` 😆

_Originally posted by @aschempp in https://github.com/contao/contao/pull/574#issuecomment-510530011_

**Comment by aschempp** [comment]
Imho depends on https://github.com/contao/contao/pull/574#issuecomment-510466430

**Comment by aschempp** [comment]
see https://github.com/contao/contao/commit/64b055a331755781a0a590f037e677d35a4ef4fe#diff-36267bc77d2718a6fe1d3874ed888294
