### ISSUE TITLE
Prevent overwriting of files

### ISSUE THREAD

**Issue by n00ybfied** [contao/contao#5773]
### Affected version(s)

4.13.15

### Description

If a member uploads multiple files with the same name, only the first one is not overwritten, if the checkbox for "doNotOverwrite" is set in the formfield options.

Example (form with 5 upload fields):

User uploads "screenshot.png" in all 5 fields.
1st file is uploaded as "screenshot.png"
2nd file is renamed to "screenshot_2.png"
From the 3rd file on "screenshot_2.png" is overwritten.

Final result: screenshot.png and screenshot_2.png are in the member's folder.
Desired result would be: Folder with screenshot.png, screenshot_2.png, screenshot_3.png, screenshot_4.png, screenshot_5.png in it. ;)

See: https://community.contao.org/de/showthread.php?84591-Bestehende-Dateien-erhalten&p=569035#post569035

Thank you,
Andreas

**Comment by fritzmg** [comment]
I can confirm the issue. It also happens in Contao 4.9.
