### ISSUE TITLE
SubmitOnChange not triggering save_callback

### ISSUE THREAD

**Issue by bytehead** [contao/contao#5779]
### Affected version(s)

4.13

### Description

Follow up for #3246

**Comment by leofeyer** [comment]
How can this be? The changes from #4236 are included in Contao 4.13. 🤔 

https://github.com/contao/contao/blob/3adf2b2f672057e814375d27d036ed5ffd3eb2c1/core-bundle/src/Resources/contao/classes/Ajax.php#L468-L473

**Comment by bytehead** [comment]
Did not debug it deeply - I assume `$objVersions->create();` does not call any save callback ...

**Comment by aschempp** [comment]
> I assume `$objVersions->create();` does not call any save callback ...

It sure does not. The `save_callback` is executed by `DC_Table` and not by the version class.

**Comment by leofeyer** [comment]
@bytehead Why do you need a save_callback for an auto-submit checkbox at all?

**Comment by bytehead** [comment]
Because I have `save_callback`'s for true boolean fields (defined via Entities/ORM) - getting rid of `''` and `1` 😎 
And if the callback is not called, there's a query error when setting the value to `''`.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we have to trigger the save_callback in the `toggleSubpalette` case in the `Ajax` class.
