### ISSUE TITLE
Eingrenzung der Widgetauswahl (Checkboxen) bei Mehrfach-Bearbeiten/Überschreiben

### ISSUE THREAD

**Issue by zonky2** [contao/contao#5784]
### Description

Beim Mehrfach-Bearbeiten/Überschreiben erscheint eine Auswahl der Widgets, die geändert/überschrieben werden sollen - aktuell werden da immer _alle_ "Spalten" angezeigt - auch die, die für das/die ausgewählten Elementtypen gar nicht relevant sind.

Es ist aktuell eh schon schwer, anhand der Bezeichnung das/die richtigen Widgets raus zu suchen...

Ich wäre auch dafür, bei mehreren unterschiedlichen Elementtypen nur die Schnittmenge an Wigets anzuzeigen.

**Comment by leofeyer** [comment]
Duplicate of #3814

**Comment by zonky2** [comment]
Grr... das hab ich gesucht... sorry
