### ISSUE TITLE
Adjust UPGRADE.md

### ISSUE THREAD

**Issue by Toflar** [contao/contao#58]
* [ ] The `disableAlias` feature as been dropped completely.
* [ ] The `rewriteUrl` option has been dropped completely. The system handles this automatically now.
* [ ] The following entry points do not exist anymore and you thus have to adjust your code:
    * `contao/changelog.php` --> Use the route `contao_backend_changelog` now.
    * `contao/confirm.php` --> Use the route `contao_backend_confirm` now.
    * `contao/file.php` --> Use the route `contao_backend_file` now.
    * `contao/help.php` --> Use the route `contao_backend_help` now.
    * `contao/index.php` --> Use the route `contao_backend_login` now.
    * `contao/install.php` --> Use the route `contao_backend_install` now.
    * `contao/main.php` --> Use the route `contao_backend` now.
    * `contao/page.php` --> Use the route `contao_backend_page` now.
    * `contao/password.php` --> Use the route `contao_backend_password` now.
    * `contao/popup.php` --> Use the route `contao_backend_popup` now.
    * `contao/preview.php` --> Use the route `contao_backend_preview` now.
    * `contao/switch.php` --> Use the route `contao_backend_switch` now.
* [ ] The `ModuleLoader` should not be used anymore. If you want to know what modules/bundles are installed, use

    ```php
    <?php
    global $kernel;
    $bundles = $kernel->getContainer()->get('kernel.bundles');
    ```
* [ ] Changing configuration parameters at runtime is wrong. You should therefore not use `Config::set()` anymore. E.g. `Config::set('debugMode', true);` will have no effect anymore as the container key `kernel.debug` is now used.

* [ ] `$_SESSION['TL_USER_LOGGED_IN']` has been removed.
* [ ] TL_ROOT, TL_SCRIPT etc. nicht mehr nutzen.
* [ ] Kein `TL_SCRIPT == 'contao/install.php'` mehr.
* [ ] The MySQL requirement has been raised to v5.5.3+ (see #35)
* [ ] Methode `Frontend::parseMetaFile()` entfernt (war bereits in Contao 3 deprecated)
* [ ] Additionally, the `tinymce.css` and `tiny_templates` have been removed from files.
* [ ] The `tinymce.php` is no longer located in `system/config` and therefore can't be customized anymore.

**Comment by aschempp** [comment]
The `pathconfig.php` file can/should be removed too as we no longer need it (see https://github.com/contao/core-bundle/commit/3b738762a0bda0c8d2774faa3167a1c8ed2661b4)

**Comment by aschempp** [comment]
The MySQL requirement has been raised to v5.5.3+ (see https://github.com/contao/contao/issues/35)

**Comment by aschempp** [comment]
tinyMCE configuration is now a template instead of a file

**Comment by aschempp** [comment]
Additionally, the `tinymce.css` and `tiny_templates` have been removed from files.

**Comment by aschempp** [comment]
The `tinymce.php` is no longer located in `system/config` and therefore can't be customized anymore.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/136.
