### ISSUE TITLE
Create User CLI

### ISSUE THREAD

**Issue by katgirl** [contao/contao#5800]
### Affected version(s)

4.13.15

### Description

vendor/bin/contao-console contao:user:create --username=test --name='Test test' --email='test@test.de' --password='password!12345678' --change-password --language='de'

Give user admin permissions?

vendor/bin/contao-console contao:user:create --username=test --name='Test test' --email='test@test.de' --password='password!12345678' --change-password --language='de' --admin=no

The "--admin" option does not accept a value.

you can't create pure editors via script e.g. ansible anymore, but only admins

**Comment by fritzmg** [comment]
I can confirm the issue. The interactivity for `admin` should be omitted if you provide `--group` (or `--admin` should take a value).

**Comment by katgirl** [comment]
We create a user so that the customer can preview. We didn't need a user group for this until now. 
By changing this to either admin or a group, we would have to create a user group beforehand, which would not be nice, as this has to be done manually.

**Comment by fritzmg** [comment]
Hm, I see. We could change the option to be `VALUE_NEGATABLE`. Then you would provide `--no-admin`.

**Comment by fritzmg** [comment]
@katgirl btw. you can just use `--no-interaction`, even in the current state. e.g.:

```
contao:user:create --username=foobar --name=Foobar --email=foobar@example.com --password=xyz --no-interaction
```
