### ISSUE TITLE
Do not encapsulate widgets in mod_password.html5

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#5812]
### Affected version(s)

all

### Description

Is there any specific reason why, within `mod_password.html5`, the widgets are encapsulated by a Div `.fields`?

This seems rather inconsistent with the other templates (`mod_login.html5`, `form_wrapper.html5` / `form_inline.html5`, ...) and causes some extra trouble while trying to give all forms a uniform styling.

**Comment by leofeyer** [comment]
> Is there any specific reason why

Not that I know of. @contao/developers I guess it is best if we change this in Contao 5.1, isn‘t it? Upgrading from Contao 4 to Contao 5 already implies some template changes, so this would not cause too many troubles for our users.

**Comment by fritzmg** [comment]
Removing this would make it inconsistent with the other member related module templates. The following templates all encapsulate their fields in `<div class="fields">`:

* `mod_password`
* `mod_changePassword`
* `member_default`

**Comment by bennyborn** [comment]
I totally get the encapsulation in `member_default` because of the grouping but why in `mod_password` and `mod_changePassword`?

**Comment by fritzmg** [comment]
For consistency with ModulePersonalData, presumably.

**Comment by aschempp** [comment]
I don't have any preference at all 🤷

**Comment by bennyborn** [comment]
How do you all handle the styling of forms in Contao? 
I usually do something like this to enable my users to at least build forms with two columns:

```css
.formbody {
    display: flex;
    justify-content: flex-start;
    align-items: flex-start
}

.formbody .widget.span50 {
    flex-basis: 50%;
}
```

This would of course benefit hugely from a mostly markup across all forms. 
As I said, I'm totally fine with `member_default` doing something a bit different but all other forms could have the same structure imho.

Edit: Actually `member_default` should also work without `.fields`. Only `member_grouped` has a legitimate reason to encapsulate its widgets.

**Comment by fritzmg** [comment]
Just use display: contents on the wrapper.
