### ISSUE TITLE
The backend setting "Do not shorten elements" is not retained

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#5813]
### Affected version(s)

5.1

### Description

Die Backend-Einstellung "Elemente nicht verkürzen" wird nach dem Speichern wieder gelöscht.
Contao 5.1.0, keine Erweiterungen
PHP 8.1.16
Hostingwerk

Das Problem wurde durch einen Nutzer der Contao Academy gemeldet. Ich habe es in meiner leeren Testinstallation bestätigen können.

**Comment by mlwebworker** [comment]
Kleiner Nachtrag
Ich habe gerade folgendes festgestellt:
Wenn ich beim Benutzer "Inhaltselemente nicht einklappen" einstelle, dann ist auch in den Einstellungen "Elemente nicht verkürzen angehakt" und kann dann dort auch nicht mehr abgewählt werden. Damit würde ich sagen ist die Einstellung zum Benutzer gewandert und kann um Verwirrung zu vermeiden in den Einstellungen entfernt werden - zu mindestens, wenn es nur noch benutzerspezifisch und nicht mehr global eingestellt werden soll.

**Comment by ausi** [comment]
Kann ich reproduzieren, `$GLOBALS['TL_CONFIG']['doNotCollapse'] = true;` wird zwar in die *localconfig.php* geschrieben aber die checkbox wird nicht als aktiv angezeigt (und man kann die einstellung nicht mehr wegnehmen).

> Damit würde ich sagen ist die Einstellung zum Benutzer gewandert und kann um Verwirrung zu vermeiden in den Einstellungen entfernt werden

:+1:

**Comment by aschempp** [comment]
See https://github.com/contao/contao/pull/5821
