### ISSUE TITLE
Error when opening Cantao Webinterface

### ISSUE THREAD

**Issue by marceltoedter** [contao/contao#5822]
### Affected version(s)

n/a

### Description

Hello dear Cantao Supporters,

one of our common customers, Upstalsboom Lanhotel Varel-Dangast, is experiencing an issue when using the Cantao web-app.
The login interface appears and accepts the credentials but after logging in. It shows following error page. (see attachement)

![Screenshot_20230224_084322](https://user-images.githubusercontent.com/126241442/221144259-e3ee76ad-d204-45d0-a1b1-776dfc3a58fa.png)

I am unable to find the mentioned log file on the local device.

Please provide instructions to troubleshoot the error.

**Comment by fritzmg** [comment]
You'll need to seek help from the Contao Community (Forum or Slack): https://contao.org/en/support.html
