### ISSUE TITLE
Inhaltselemente in andere Artikel verschieben

### ISSUE THREAD

**Issue by syntaxys** [contao/contao#5823]
### Description

Es wäre eine nützliche Sache, wenn man Inhaltselemente einfach in andere Artikel verschieben könnte. Ich mache das zwar immer über die Datenbank, aber bequemer wäre das in Contao selbst. Hat das noch niemand vermisst?

**Comment by frontendschlampe** [comment]
Öhm … das geht doch schon immer mit dem blauen Pfeil …

**Comment by syntaxys** [comment]
Klar. Die Ablage. Also dann hab ich das nach 16 Jahren Contao erst eben gecheckt ... 😂🤦‍♂️
