### ISSUE TITLE
Standardeinstellungen beim Duplizieren von Seiten(-bäumen)

### ISSUE THREAD

**Issue by syntaxys** [contao/contao#5824]
### Affected version(s)

4.13.*

### Description

Aktuell habe ich 4.13 im Einsatz, um Micro-Sites für Veranstaltungen pflegen zu können. Da die Sites nur einem kleinen Besucherkreis per Einladung – jedoch öffentlich – zugänglich sind, sollen sie explizit nicht von Suchmaschinen indexiert werden.
Wenn ich nun den Seitenbaum einer Micro-Site für eine neue Subdomain dupliziere werden die Einstellungen für **Robots-Tag** und **In der HTML-Sitemap zeigen** nicht übernommen. Auch wäre es praktisch, wenn der jeweilige **Seitenalias** der Unterseiten mit übernommen werden könnte, es würde etwas Nachpflegeaufwand ersparen.

**Comment by fritzmg** [comment]
> Wenn ich nun den Seitenbaum einer Micro-Site für eine neue Subdomain dupliziere werden die Einstellungen für **Robots-Tag** und **In der HTML-Sitemap zeigen** nicht übernommen.

That would be a bug if true.


> Auch wäre es praktisch, wenn der jeweilige **Seitenalias** der Unterseiten mit übernommen werden könnte, es würde etwas Nachpflegeaufwand ersparen.

That's intentional - however you can automatically generate the aliases via _Edit multiple_.

**Comment by syntaxys** [comment]
Ok, I just made a test again and it worked as it should be. I've been sure that I set all the previous pages in the micro sites to „noindex, nofollow“ and after a new tree copy today I had the „index, follow“ setting again. Hmm? I will keep it in mind …

**Comment by asaage** [comment]
since aliases do not need to be unique anymore you could also adjust the dca of tl_page
doNotCopy=false for example...
https://github.com/contao/contao/blob/5.x/core-bundle/contao/dca/tl_page.php#L239
