### ISSUE TITLE
Umlaute in Domainnamen lassen sich nicht speichern

### ISSUE THREAD

**Issue by zonky2** [contao/contao#5825]
### Affected version(s)

4.13.16

### Description

Im **Startpunkt** habe ich als **Domainnamen** eingetragen `www.xn--hrdienst-n4a.de` - nach dem Speichern steht in dem Feld `www.hördienst.de`  - wenn ich nochmal speichern will, kommt eine **Fehlermeldung beim Alias** `Invalid Host "www.hördienst.de".`

**Comment by ausi** [comment]
Ich konnte den Fehler in Contao 4.13 nicht reproduzieren.

**Comment by zonky2** [comment]
mit 4.13.23 getestet - tritt nun nicht mehr auf
