### ISSUE TITLE
Don't cache absolute paths of templates

### ISSUE THREAD

**Issue by rabauss** [contao/contao#5826]
### Affected version(s)

4.13+

### Description

In chrooted environments like on plesk hosting you may have a changing `kernel.project_dir` via cli and web server, e.g. via cli `/httpdocs/` and via web server `/var/www/vhosts/mydomain.com/httpdocs/`

This is especially a problem on `cache:warmup`, since some paths to templates are written absolutely by contao to the cache directory, e.g. for the cache key `contao.twig.template_hierarchy` something like that
```php
'be_main' => [
        '/httpdocs/vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_main.html5' => '@Contao_ContaoCoreBundle/be_main.html5',
    ],
```
Afterwards you can see an error in the back end because via web server the "wrong" absolute path is not resolvable.
```php
Uncaught PHP Exception Twig\Error\LoaderError: "Template "@Contao_ContaoCoreBundle/be_main.html5" is not defined ... 
at vendor/twig/twig/src/Loader/ChainLoader.php line 99
```

One solution would be for contao to write relative paths to the cache folder instead of absolute paths - especially for templates!

see also: https://contao.slack.com/archives/CK4J0KNDB/p1677063729691519

**Comment by ausi** [comment]
We had a similar issue in `contao/image` and switched to using relative paths AFAIR, https://github.com/contao/image/pull/32

**Comment by aschempp** [comment]
the cache in Symfony must **never** contain absolute paths, so that's clearly a bug.

**Comment by leofeyer** [comment]
> the cache in Symfony must **never** contain absolute paths

That does not seem true. Try searching for `/Users/aschempp` in the `var/cache` folder – there were plenty of hits on my system.

**Comment by leofeyer** [comment]
But we indeed dump relative paths when generating the template cache:

https://github.com/contao/contao/blob/88399760d0bd5d751f93c477fc55d660392d4159/core-bundle/src/Cache/ContaoCacheWarmer.php#L199

@m-vo Can you fix this please?

**Comment by m-vo** [comment]
I can if it helps in certain setups. But I am not yet convinced this is a bug tbh. The issue only shows if the web process and the CLI resolve absolute paths differently, which sounds like a very strange setup to me, no?

**Comment by Toflar** [comment]
https://github.com/twigphp/Twig/issues/3218 😂

**Comment by Toflar** [comment]
So I guess it's not worth fixing as any other Twig template wouldn't work either?

**Comment by leofeyer** [comment]
As discussed in the Contao call, https://github.com/twigphp/Twig/issues/3218 needs to be fixed before it makes sense to adjust our code.
