### ISSUE TITLE
"Select all" does not work with click on LABEL

### ISSUE THREAD

**Issue by Aybee** [contao/contao#583]
**Affected version(s)**
4.4.40

**Description** 
Die Checkbox "Alle auswählen" hat einen `onclick `event. Dieser wird nicht gefeuert, wenn man auf das LABEL klickt.
```html
<div class="tl_content_right">
  <label for="tl_select_trigger" class="tl_select_label">Alle auswählen</label>
  <input type="checkbox" id="tl_select_trigger" onclick="Backend.toggleCheckboxes(this)" class="tl_tree_checkbox">
</div>
```
Damit es mit LABEL **und** INPUT funktioniert müsste der `onclick` gegen `onchange` ausgetauscht werden.

**How to reproduce**  
Mehrere bearbeiten und dann auf das LABEL "Alle auswählen" klicken.

**Comment by leofeyer** [comment]
@ausi Can you confirm this?

**Comment by ausi** [comment]
No, works fine for me in Firefox and Chrome.

**Comment by Aybee** [comment]
Please check this with page layouts. Sorry, I assumed that this does not work anywhere.

**Comment by Aybee** [comment]
Scheint mit dem Event auf dem Element `#tl_listing > div.tl_header.click2edit.toggle_select.hover-div` zusammenzuhängen. Stelle gerade fest, dass es auf dem kompletten obigen Element funktioniert, außer dem LABEL.

Könnte hiermit zusammenhängen https://github.com/contao/contao/blob/4.4/core-bundle/src/Resources/contao/themes/flexible/src/hover.js#L66-L73

**Comment by Aybee** [comment]
Try with this selector, this works for me.
```js
...
ul.getElements('input[type="checkbox"]:not(#tl_select_trigger)').each(function(el) {
...
```

**Comment by ausi** [comment]
Kannst du das Problem auf demo.contao.org reproduzieren?
Falls ja, beschreib bitte kurz die Schritte die durchzuführen sind damit man den Fehler sieht und welchen Browser und Browser-Version du einsetzt.

**Comment by Aybee** [comment]
Nein, dort in der 4.7.5 Demo habe ich das Problem nicht. Nur in all meinen 4.4.x Installationen. Windows mit FF, Chrome, Edge, Opera, IE (alle aktuell). Kann das mal jemand in einer 4.4.40 testen?

Gehe zu den **Layouts**, klicke "Mehrere bearbeiten", dann auf das Label der Checkbox "Alle auswählen" klicken. Wenn man daneben klickt geht es.
