### ISSUE TITLE
PHP8 Undefined array key "breadcrumb"

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#5833]
### Affected version(s)

\>= 4.13.14

### Description

Concerns the menu item "Templates" in the backend. If I click on a template folder there, the following exception is thrown under PHP8:

![image](https://user-images.githubusercontent.com/226890/222430667-3e8c5be0-8de8-4c7a-9d84-742ceb5bf5c3.png)

https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/dca/tl_templates.php#L240

**Comment by cliffparnitzky** [comment]
Can confirm with Contao 4.13.16 and 8.1.16. No problem with Contao 5.1.0.

**Comment by bennyborn** [comment]
> No problem with Contao 5.1.0.

Correct, this seems already fixed in 5.x
