### ISSUE TITLE
Contao 5.1 hat unendliche Backend-Breite

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#5836]
### Affected version(s)

5.1

### Description

Im Profil des Benutzers kann man nicht mehr die Breite des Backends limitieren (auf 1140px o.ä.). Das macht die Mauswege natürlich sehr viel länger, wenn man das Browserfenster nicht verkleinern möchte. Vor 6 Jahren gab es eine Diskussion darum und die Breitenbegrenzung wurde von den Entwicklern begrüßt. Und jetzt fehlt sie wieder.

**Comment by leofeyer** [comment]
See https://github.com/contao/contao/pull/4371#issuecomment-1189984807.

**Comment by fritzmg** [comment]
> See [#4371 (comment)](https://github.com/contao/contao/pull/4371#issuecomment-1189984807).

The discussion never came to a close there. See https://github.com/contao/contao/pull/4371#issuecomment-1190008568
