### ISSUE TITLE
Deleting children with parent records in "delete all" mode throws an error

### ISSUE THREAD

**Issue by qzminski** [contao/contao#5839]
### Affected version(s)

5.1.x

### Description

When trying to delete the children records with parent record, Contao will throw an exception:

![CleanShot 2023-03-06 at 10 36 31](https://user-images.githubusercontent.com/193483/223072847-9666b8d9-8900-45d3-af64-64e1adf4a85f.gif)

The problem happens exactly at this place:

https://github.com/contao/contao/blob/5.x/core-bundle/contao/drivers/DC_Table.php#L1534

The first deleted record is the parent record, which also deleted its children. Then, Contao tries to edit the next record in the queue (the child), but this record no longer exists.

I am not sure how to fix this one exactly though.

**Comment by Toflar** [comment]
Confirmed. I'm investigating.

**Comment by Toflar** [comment]
Fix: https://github.com/contao/contao/pull/5840
