### ISSUE TITLE
Datenbank-Migration funktioniert nicht

### ISSUE THREAD

**Issue by LutzWinkler** [contao/contao#5846]
### Affected version(s)

4.9.x,5.x

### Description

Nach Update von 4.9.13 auf 5.1 funktioniert die Datenbank-Migration nicht:

- Unter Systemwartung steht "4 ausstehende Datenbank-Migrationen"
- Wenn ich auf "Datenbank überprüfen" klicke, kommt anschließend die Meldung:
- "Keine ausstehenden Migrationen oder Schema-Änderungen gefunden. Deine Datenbank ist auf dem aktuellsten Stand."
- Die Meldung "4 ausstehende Datenbank-Migrationen" bleibt bestehen

Welche Migrationen anstehen, ist nirgends zu sehen.
Auch wenn Front- und Backend scheinbar einwandfrei funktionieren: die Datenbank ist jedenfalls nicht auf dem aktuellsten Stand.
Ich fürchte, das wird spätestens beim nächsten Update Probleme machen
[Screenrecording](https://privat.lutzwinkler.de/files/DB%20Migration.mp4)

**Comment by fritzmg** [comment]
> Auch wenn Front- und Backend scheinbar einwandfrei funktionieren: die Datenbank ist jedenfalls nicht auf dem aktuellsten Stand.
> Ich fürchte, das wird spätestens beim nächsten Update Probleme machen

There are likely no relevant database changes to be made, so I wouldn't worry. However, it is an issue that the system maintenance shows pending database changes and yet the command itself does not execute or show any.

**Comment by LutzWinkler** [comment]
Dieser Screen erscheint überhaupt nicht:
[Schema Änderungen](https://user-images.githubusercontent.com/6390770/197159951-6eb6399d-251d-4b95-a805-23637a2a6a02.png)
Dadurch bleibt völlig im Dunkel, welche Änderungen anstehen.

**Comment by LutzWinkler** [comment]
Wie befürchtet, gibt es bereits Probleme, die nicht sofort auffallen:
1. Wenn ich im BE auf 'Inhalte->Seiten' klicke:
> An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'feedFormat' in 'field list'
2. Wenn ich im BE auf 'Inhalte->Formulare' klicke:
> An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ajax' in 'field list'

Offenbar sind also einige Datenbankfelder **nicht** aktualisiert worden

**Comment by contaoacademy** [comment]
Kannst du den Migrate-Befehl über die Kommandozeile ausführen?
`php vendor/bin/contao-console contao:migrate -v`

Wird dir dort eine detaillierte Fehlermeldung ausgegeben?

**Comment by fritzmg** [comment]
According to their forum post they do not have SSH access.

**Comment by leofeyer** [comment]
Hast Du in Deiner Konfiguration irgendwo eine feste Version für `doctrine.dbal.server_version` eingetragen? Falls ja, lösch den Eintrag mal und versuch es erneut.

**Comment by LutzWinkler** [comment]
Hab ich nicht

**Comment by LutzWinkler** [comment]
Hab das Problem inzwischen behoben. Nach dem Update auf MySQL 8.0 funktioniert die Datenbank-Migration wieder.

Vielleicht kann man noch mal an prominenter Stellung darauf hinweisen, dass Contao 5.x MySQL 8.x erfordert.
Es ist jedenfalls sehr verwirrend, dass das Update scheinbar problemlos durchläuft, die Aktualisierung der Datenbank dann aber ohne Fehlermeldung ausbleibt.

**Comment by Toflar** [comment]
> dass Contao 5.x MySQL 8.x erfordert.

Tut es nicht.

**Comment by Aybee** [comment]
Kannste wieder öffnen, ich habe hier das gleiche Problem auf 
hostpoint.ch
PHP 8.1.17
10.6-MariaDB
Manager 1.6.3

Update von Contao 4.9.latest auf 4.13.24

Ich habe dort 2 Projekte aktualisiert, beide mit gleichem Problem, und weitere Projekte werden jetzt folgen.

In 4.13 kann ich ja noch das Installtool aufrufen mit contao/install, dort sehe ich was zu ändern ist, aber über den Manager keine Chance.

Hier die Ansichten, die man diesbezüglich zu sehen bekommt.
![20230613_195639](https://github.com/contao/contao/assets/1143013/876456bc-dfe4-45d8-b0a5-c2ee6d184e22)
![20230613_195726](https://github.com/contao/contao/assets/1143013/73ca0ad3-a31e-4dce-8a02-c0ebebb142e3)
![20230613_195824](https://github.com/contao/contao/assets/1143013/2db9c741-135b-491b-a8e2-6c6d2fee453c)

**Comment by ausi** [comment]
@Aybee 

Kannst du den Migrate-Befehl über die Kommandozeile ausführen?
`php vendor/bin/contao-console contao:migrate -v`

Wird dir dort eine detaillierte Fehlermeldung ausgegeben?

**Comment by Aybee** [comment]
Ich arbeite gerade daran, ich melde mich.

**Comment by fkaminski** [comment]
Hatte das vor vor kurzem (3.5 -> 4.13) via CM (inkl. löschen) auch: » ... ausstehende Datenbank-Migrationen«.
Dann `contao:migrate` via Console probiert und es funktionierte ohne weitere Meldungen. Im Anschluß wurde auch im CM nichts beanstandet :man_shrugging:

**Comment by Aybee** [comment]
Hier die Ausgabe von contao:migrate -v
```
PHP Warning:  Undefined array key "deleteConfirm" in /xxx/var/cache/prod/contao/dca/tl_calendar_events_subscription.php on line 19

 [INFO] Creating a database dump to "backup__20230617125600.sql.gz" with the default options. Use --no-backup to disable
        this feature.                                                                                                   

Pending database migrations (f28efe08028dc0febc6d0178ae71be7270667f08f414ae76572ac864baa0c97f)
----------------------------------------------------------------------------------------------

 * DROP TABLE tl_event_registrations
 * DROP TABLE tl_beuseronline_session
 * DROP TABLE tl_newsletter_recipients_backup
 * ALTER TABLE tl_calendar DROP ser_wait_html
 * ALTER TABLE tl_calendar DROP ser_wait_text
 * ALTER TABLE tl_calendar DROP ser_wait_subject
 * ALTER TABLE tl_calendar DROP ser_cancel_html
 * ALTER TABLE tl_calendar DROP ser_cancel_text
 * ALTER TABLE tl_calendar DROP ser_cancel_subject
 * ALTER TABLE tl_calendar DROP ser_confirm_html
 * ALTER TABLE tl_calendar DROP ser_confirm_text
 * ALTER TABLE tl_calendar DROP ser_confirm_subject
 * ALTER TABLE tl_calendar_events DROP ser_showgroups
 * ALTER TABLE tl_calendar_events DROP ser_showheadline
 * ALTER TABLE tl_calendar_events DROP ser_show
 * ALTER TABLE tl_calendar_events DROP ser_groups
 * ALTER TABLE tl_calendar_events DROP ser_date
 * ALTER TABLE tl_calendar_events DROP ser_email
 * ALTER TABLE tl_calendar_events DROP ser_maxplaces
 * ALTER TABLE tl_calendar_events DROP ser_places
 * ALTER TABLE tl_calendar_events DROP ser_register
 * ALTER TABLE tl_module DROP ser_waitinglist
 * ALTER TABLE tl_module DROP ser_quantity
 * ALTER TABLE tl_module DROP ser_showevents
 * ALTER TABLE tl_theme DROP easy_themes_internalTitle
 * ALTER TABLE tl_user DROP et_bemodRef
 * ALTER TABLE tl_user DROP et_mode
 * ALTER TABLE tl_user DROP et_short
 * ALTER TABLE tl_user DROP et_activeModules
 * ALTER TABLE tl_user DROP et_enable

 Execute the listed database updates? [yes]:
  [0] yes
  [1] yes, with deletes
  [2] no
 > 
```
https://github.com/codefog/contao-events_subscriptions/blob/2.16.3/dca/tl_calendar_events_subscription.php#L86

**Comment by fritzmg** [comment]
You'll have to first fix the error in https://github.com/codefog/contao-events_subscriptions/blob/2.16.3/dca/tl_calendar_events_subscription.php#L86

Then try again.

**Comment by Aybee** [comment]
Don't think it's a "real" bug as it's only throwing a PHP warning. And this `\''` seems to be ok.

I'm waiting for Kamil to fix this bug because I don't know how to fix it by myself.

**Comment by fritzmg** [comment]
> Don't think it's a "real" bug as it's only throwing a PHP warning

It is a "real" bug ;). The warning output interferes with the Contao Manager.

**Comment by contaoacademy** [comment]
I would also like to see better error handling or error messages in the Contao manager here.

Currently, it is difficult to find out what is causing the problem without having access to the console.
