### ISSUE TITLE
decodeEntities Insert Tag flag removed

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#585]
The `decodeEntities` Insert Tag flag was removed for Contao `3.5.16` in this commit: https://github.com/contao/core/commit/f5ad1d00a3a7ea6e382ad1d7cd7589f7d5df35e9#diff-e9b31257c5a1b6da1d5a32af792a67e3L1178 (along with 2 other flags).

Any particular reason why? The commit message doesn't really say.

**Comment by Acta2000** [comment]
I tried to use this in a form.  

Formfield -> Name = test  ->Type = Select -> Value `"Fachgebiet<br>Fachbereich"`
Used the select value on the redirect page with {{post::test}}

Output: `Fachgebiet<br>Fachbereich `
What i like to have:
Fachgebiet
Fachbereich

Debugger says: `&lt;br&#62; `

decodeEntities doesnt work anymore.

**Comment by leofeyer** [comment]
> Any particular reason why? 

Because it is a potential security risk. Think about replacing the `<br>` with `<script>` in @Acta2000's example.

**Comment by Acta2000** [comment]
But first you have to enable HTML tags? Without this no security risk? Is there any solution for my example?

**Comment by leofeyer** [comment]
I don't think so. @ausi /cc

**Comment by Acta2000** [comment]
Now i used this:

Template decode.html5

```
<?php

echo html_entity_decode(\Input::post("bereich"));

?>
```

**Comment by leofeyer** [comment]
You really should not! You are making the website vulnerable to XSS attacks this way.

Imagine if someone enters `<script>alert("XSS")</script>` into the `bereich` field. The code will be executed after the form has been submitted.

**Comment by Acta2000** [comment]
"bereich" is a select-field - on a website which only can be used by members.

**Comment by leofeyer** [comment]
That does not make it any better! First of all, can you really trust all your members? And second of all, what if one of your members is hacked and their account is abused?

**Comment by Acta2000** [comment]
You may be right. 
So there is no "save" option to use `<br>` tags ?

Whats about the Contao backend option. You have to set allowed HTML-Tags to used it on the website.
If <script> ist not allowed i cant be used in form?

**Comment by leofeyer** [comment]
There are plenty of ways to execute JavaScript without a `<script>` tag. Think of `<img src="…" onload="alert('XSS')">` for example.

**Comment by m-vo** [comment]
> So there is no "save" option to use <br> tags ?

Well you can safely pipe your output through a string replacement function in the template, just never ever blindly trust any user data (this includes all post data). And if you're at it, you could also use another token; like `[br]` or `\n`.

**Comment by Acta2000** [comment]
This Sounds  like an good idea. Using [br] and replacing it wird <br>

M. Vondano <notifications@github.com> schrieb am Di., 23. Juli 2019, 18:17:

**Comment by Acta2000** [comment]
`<?php echo str_replace('[br]', '<br>', \Input::post("bereich")); ?>`

This shouldnt be a sercurity risk anymore.

**Comment by asaage** [comment]
Why not use standard-insert-tags?
**{{br}}** - This tag will be replaced with the HTML ```<br>``` tag (line break).
If it's just for the linebreak you can check if this works - then there is no manual replacing necessary.

**Comment by Acta2000** [comment]
Because of the error "Ungültige Auswahl" if you used it in an select field!
