### ISSUE TITLE
Form hybrid with missing form throws exception

### ISSUE THREAD

**Issue by ausi** [contao/contao#5858]
### Affected version(s)

5.1

### Description

Having a form module that is linked to a no longer exising form will throw an exception like: `SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? AND tl_form_field.invisible=0 AND tl_form_field.tstamp!=0 ORDER BY tl_form_fie' at line 1`

This has two causes:

First, the hybrid has an early return if it cannot find the form model in https://github.com/contao/contao/blob/30df1a941b2f8cd74656929ce7b5fefd7581d2f8/core-bundle/contao/classes/Hybrid.php#L112-L114 but in the `generate()` method the missing model is ignored. I’d suggest we add a check for `|| !$this->arrData` in https://github.com/contao/contao/blob/30df1a941b2f8cd74656929ce7b5fefd7581d2f8/core-bundle/contao/classes/Hybrid.php#L222-L224

And second the `FormFieldModel::findPublishedByPid()` passes `$intPid` to `findBy()` without a null check which is why we probably should add an `(int) $intPid` or `array($intPid)` to https://github.com/contao/contao/blob/30df1a941b2f8cd74656929ce7b5fefd7581d2f8/core-bundle/contao/models/FormFieldModel.php#L212 and all other models that do something similar.

**Comment by leofeyer** [comment]
> I’d suggest we add a check for `|| !$this->arrData`

Agreed. 👍 

> we probably should add an `(int) $intPid` or `array($intPid)` to

Will the method still be called once we add the fix above?

**Comment by ausi** [comment]
> > we probably should add an `(int) $intPid` or `array($intPid)` to
> 
> Will the method still be called once we add the fix above?

No, the first fix is enough to fix this issue, but I still think we should fix the model methods too. Or at least add null checks and throw proper exceptions.

**Comment by leofeyer** [comment]
I see. So we have to create two PRs. 👍
