### ISSUE TITLE
Anlegen eines Moduls vom Typ Zwei-Faktor-Authentifizierung erzeugt Fehler

### ISSUE THREAD

**Issue by Kabathus** [contao/contao#5859]
### Affected version(s)

5.1

### Description

Beim anlegen eines neuen Moduls, kommt eine Fehlermeldung sobald im Dropdown bei "Modultyp" der Punkt "Zwei-Faktor-Authentifizierung" ausgewählt wird.

Fehlermeldung im Browser:
Internal Server Error
Was ist das Problem?
Tried to list template options for the modern fragment type "frontend_module/two_factor" but could not find any template. In case you wanted to use the legacy type "mod_two_factor", define it explicitly in the "template" property of your controller's service tag/attribute.

Im Log:
`request.CRITICAL: Uncaught PHP Exception LogicException: "Tried to list template options for the modern fragment type "frontend_module/two_factor" but could not find any template. In case you wanted to use the legacy type "mod_two_factor", define it explicitly in the "template" property of your controller's service tag/attribute." at /var/www/clients/client1/web193/web/vendor/contao/core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php line 85 {"exception":"[object] (LogicException(code: 0): Tried to list template options for the modern fragment type \"frontend_module/two_factor\" but could not find any template. In case you wanted to use the legacy type \"mod_two_factor\", define it explicitly in the \"template\" property of your controller's service tag/attribute. at /var/www/clients/client1/web193/web/vendor/contao/core-bundle/src/EventListener/DataContainer/TemplateOptionsListener.php:85)"} []
`

**Comment by leofeyer** [comment]
@m-vo /cc

**Comment by m-vo** [comment]
See #5870
