### ISSUE TITLE
Ajax Requests should probably check for a valid session

### ISSUE THREAD

**Issue by asaage** [contao/contao#5865]
### Affected version(s)

4.13

### Description

Lets pretend you have a BE-Page open in your browser and for whatever reason your session has expired.
You are still "able" to hide/unhide elements and get (fake)feedback in the form of an icon colorchange. The invalid session does not reveal itself at this point.

**Comment by Toflar** [comment]
I can confirm. We just swap the eye image and the request fails. There might be tons of other such cases so I guess best would be to redirect to the login page. Here's a quick attempt: https://github.com/contao/contao/pull/5868
