### ISSUE TITLE
File not inside root directory 

### ISSUE THREAD

**Issue by michael-j-r** [contao/contao#5869]
### Affected version(s)

5.x

### Description

I have linked an directory structure from outside the contao root directory into the files directory.
Everything works fine. Files can be accesses and displayed in galeries, execpt :

Using the element Galerie and enabling 'Großansicht/Neues Fenster' then the system issues the error message below, with 
.... is not inside root directory ....   But the galerie itself is able to display all requestes content. Only the lightbox/new window feature crashes.

`[2023-03-10T21:13:38.266851+01:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Path "/homepages/34/user0815/htdocs/piwigo_small/galleries/lightroom/Portrait/2022-10-22_Elena/Insta_20221022-164442-DSA01185-PS-1.jpg" is not inside root directory "/homepages/34/user0815/htdocs/miri-art2023/miri-art5"") in "@Contao_ContaoCoreBundle/component/_figure.html.twig"." at /homepages/34/user0815/htdocs/miri-art2023/miri-art5/vendor/twig/twig/src/Template.php line 185 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Path \"/homepages/34/user0815/htdocs/piwigo_small/galleries/lightroom/Portrait/2022-10-22_Elena/Insta_20221022-164442-DSA01185-PS-1.jpg\" is not inside root directory \"/homepages/34/user0815/htdocs/miri-art2023/miri-art5\"\") in \"@Contao_ContaoCoreBundle/component/_figure.html.twig\". at /homepages/34/user0815/htdocs/miri-art2023/miri-art5/vendor/twig/twig/src/Template.php:185)\n[previous exception] [object] (Contao\\Image\\Exception\\InvalidArgumentException(code: 0): Path \"/homepages/34/user0815/htdocs/piwigo_small/galleries/lightroom/Portrait/2022-10-22_Elena/Insta_20221022-164442-DSA01185-PS-1.jpg\" is not inside root directory \"/homepages/34/user0815/htdocs/miri-art2023/miri-art5\" at /homepages/34/user0815/htdocs/miri-art2023/miri-art5/vendor/contao/image/src/Image.php:94)"} []`

**Comment by m-vo** [comment]
@michael-j-r  What does the lightbox/fullsize image URL look like in your case?

Btw., the exception seems to originate from this place in `contao/image` (not saying that it's the library's fault): https://github.com/contao/image/blob/137d42de1f4ac67a346daf19d58fed0220fe5ff9/src/Image.php#L93-L95

/cc @ausi

**Comment by ausi** [comment]
> I have linked an directory structure from outside the contao root directory into the files directory.

How exactly did you do that?

**Comment by michael-j-r** [comment]
Hi, The Contao Root is at e.g./Home/User/webcontent/contao

Pictures are at/Home/User/Pics/pic1.jpg

In contao is a link in files pointing to. /Home/User/Pics

Linux > ln -s  /Home/User/Pics  /Home/User/webcontent/contao/files/Pics

/Home/User/webcontent/contao/files/Pics -> /Home/User/Pics

Pctures are found and can be displayed with the galerie or carousel.
Works perfectly fine in 4.x. and with lightbox to enlage the picture. 
In In 5.x all galerie previews work, but enabling the 'lightbox/new window' crashes the System.

Ich hoffe das erklärt was ich bisher gemacht habe und auch perfekt funktioniert hat.

Grüße
Michael

**Comment by ausi** [comment]
I was able to reproduce that error, it happens anytime the image gets output without resizing and therefore the original path is used. In https://github.com/contao/contao/blob/7557bdc199d2b0ad10686db4d54754dc750fc270/core-bundle/src/Image/Studio/FigureBuilder.php#L331 we get an absolute path to the symlinked file, so `/Home/User/Pics/pic1.jpg` in your example.

In the template the image tries to generate a URL from this path, but this is not possible because the image is outside of the webspace.

We probably need to fix this by utilizing the `VirtualFilesystemInterface::generatePublicUri()` method?
But I’m not sure if, where or how. /cc @m-vo

**Comment by michael-j-r** [comment]
Hi, The Contao Root is at e.g./Home/User/webcontent/contaoPictures are at/Home/User/Pics/pic1.jpgIn contao is a link in files pointing to. /Home/User/PicsLinux > ln -s  /Home/User/Pics  /Home/User/webcontent/contao/files/Pics -> /Home/User/PicsPctures are found and Von meinem iPad gesendetAm 13.03.2023 um 15:13 schrieb Martin Auswöger ***@***.***>:﻿

I have linked an directory structure from outside the contao root directory into the files directory.

How exactly did you do that?

**Comment by ausi** [comment]
@michael-j-r I don’t understand your last comment to this issue, you only repeated existing comments. 
Probably the “answer via email” feature of GitHub failed?

**Comment by m-vo** [comment]
As discussed on today's Contao Call, we probably need to do two things:

1) Use `VirtualFilesystemInterface::generatePublicUri()` to get the public URI.
2) Also generate a `SymlinkedLocalFilesProvider` service for each adapter we create in our `ConfigureFilesystemPass#mountAdaptersForSymlinks()` workaround.

**Comment by ericges** [comment]
Hier als Ergänzung einen relatierten Fehler, den ich erhalte, wenn der Ordner `files/media` im Contao-Root ein Symlink auf `/mnt/files/media` ist:

`[2024-04-10T12:19:53.666226+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Path "/mnt/files/media/image.svg" is not inside root directory "/var/www/html"")." at _picture.html.twig line 29 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Path \"/mnt/files/media/image.svg\" is not inside root directory \"/var/www/html\"\"). at /var/www/html/vendor/contao/core-bundle/contao/templates/twig/component/_picture.html.twig:29)\n[previous exception] [object] (Contao\\Image\\Exception\\InvalidArgumentException(code: 0): Path \"/mnt/files/media/image.svg\" is not inside root directory \"/var/www/html\" at /var/www/html/vendor/contao/image/src/Image.php:94)"} {"request_uri":"http://container.localdomain/contao?do=article&id=20&ref=<refid>&table=tl_content","request_method":"GET"}`

(zum Datenschutz anonymisiert)

[Hier zum Thread in Slack](https://contao.slack.com/archives/CK4J0KNDB/p1712743379172589)

**Comment by benfolds** [comment]
Is there any update regarding this bug? We regulary use symlinking for development and this is what's holding us back to use 5.3 😬. Is there anything we can do / help?

**Comment by ausi** [comment]
@michael-j-r @ericges @benfolds can you test if the changes from #7294 would fix your issue?
