### ISSUE TITLE
Update Contao to 4.13.17

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao#5880]
### Affected version(s)

4.13.17

### Description

I become the error "what's the matter? the website is currently not available. please come back later. contao 4.13.17" When I Update from Contao 4.13.x to 4.13.17. I have the error on two Contao installations. Can you fix this please? Many thanks.

**Comment by cliffparnitzky** [comment]
The error is known. A fix is already created: https://github.com/contao/contao/pull/5879 

Will surely be released in the coming days.
