### ISSUE TITLE
app_dev in Contao 4.4 bei 1und1 IONOS

### ISSUE THREAD

**Issue by zonky2** [contao/contao#589]
**Affected version(s)**
Contao 4.4

**Description**
Ruft man die Seite mit app_dev.php auf kommt der htaccess-Schutz zum Login - auch bei Eingabe der richtigen Logindaten kommt diese Meldung immer wieder.  

**How to fix**  
Verwenden der app_dev.php aus dem Branch 4.5 - siehe https://github.com/contao/contao-manager/wiki/1und1-IONOS

**Comment by aschempp** [comment]
@discordier kannst du dir erklären warum der Symfony Request den User + Pw nicht korrekt zurück gibt?

**Comment by discordier** [comment]
Haeh? tut er doch? Genau darum geht es doch...
nur das in 4.4 NIE der request verwendet wird sondern erst ab 4.5.

**Comment by aschempp** [comment]
Ah, also müssen wir Contao 4.4 um den Symfony Request in der app_dev.php erweitern 😊 👍

**Comment by discordier** [comment]
korrekt.

**Comment by leofeyer** [comment]
PR: #629
