### ISSUE TITLE
rel-canonical for items of events and news

### ISSUE THREAD

**Issue by zonky2** [contao/contao#5891]
### Description

It would be nice if there was the possibility to adjust the rel-canonical value also for items of events and news.

For example, I have a case where a news item is displayed in different archives and the SEO gurus would like to have a reference to only one archive page.

**Comment by fritzmg** [comment]
But in that case the canonical tag should be automatically set to the correct URL, should it not? This would be out of scope from Contao's current feature set - as you are not able to define different detail URLs for news archives currently anyway.

Regardless, since we allow to set other meta data like robots per news, it imho makes sense to allow to set canonical per news (and event).

**Comment by k-webdesign** [comment]
Normally the canonical tag should point to the same page, I agree. But sometimes there are special messages that should better point to another page (e.g. a blog article), so the global settings on the messages detail page won't help. 
The canonical tag was made to prevent duplicates, so it should be configurable for individual news items.

**Comment by fritzmg** [comment]
@k-webdesign can you explain your use-case in more detail? You want to set the canonical tag of a news item to a completely different page - but why in particular?

**Comment by k-webdesign** [comment]
@fritzmg sometimes it happens that 2 search results disatvantage each other (cannibalize). Then it could help to strengthen the wanted search result by setting the canonical tag of the undesirable page to the preferred page.
Press releases, for example, are published multiple times and the tag should point to the actual press release page, which mostly will be an external link.

**Comment by fritzmg** [comment]
Sounds reasonable 👍

In any case since we allow to override all other Meta data in news articles, it makes sense to allow overriding the canonical URL as well.

**Comment by k-webdesign** [comment]
I'd appreciate that very much 🙏🏼

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6215
