### ISSUE TITLE
Don't ignore the user rgxp when changing the user password in the BackendPassword Controller

### ISSUE THREAD

**Issue by davidmaack** [contao/contao#5896]
### Description

When changing a user-password via the backend, the $GLOBALS['TL_DCA']['tl_user']['fields']['password']['eval']['rgxp']  setting will be evaluated, so its's possible to enforce your own password policy, for example using the terminal42/contao-password-validation extenion. But when the password is getting changed by the /password route, the rgxp value will be ignored. It would be great when both ways of changing a password would behave in the same way

**Comment by fritzmg** [comment]
This should already be the case, see https://github.com/contao/contao/pull/5415

Which Contao version did you use to test this?

**Comment by davidmaack** [comment]
4.13.12 - it seems that I simply have to update the instance :)
Thanks for the hint.

**Comment by fritzmg** [comment]
Yes, you would need at least Contao `4.13.13`.
