### ISSUE TITLE
When logging out as a backend user, Contao automatically logs me out as a frontend user as well

### ISSUE THREAD

**Issue by markocupic** [contao/contao#5899]
### Affected version(s)

4.13 and 5.1

### Description

If I log in as a Contao backend and frontend user at the same time and then log out again as a backend user, I am automatically logged out as a frontend user as well. Is that intentional or a bug?

**Comment by cliffparnitzky** [comment]
As far as I remember this was already the case with Contao 2. So I suspect that there will be a good reason for this.

**Comment by leofeyer** [comment]
Yes, there is: it is the same session. If you want to avoid this issue, use two different browsers or use an incognito tab for one of the logins.

**Comment by aschempp** [comment]
This has nothing to do with Contao 2, but is a configuration of the Symfony framework. See https://symfony.com/doc/current/reference/configuration/security.html#invalidate-session

This config is mostly related to prevent session fixation attacks, also see https://symfony.com/doc/current/reference/configuration/security.html#session-fixation-strategy for the related Symfony docs.
