### ISSUE TITLE
Seitentyp bei Fehlerseiten ist defekt, wenn die Seite eine Unterseite ist.

### ISSUE THREAD

**Issue by medianetic** [contao/contao#5901]
### Affected version(s)

4.13.12

### Description

Wenn man z.B. in der Seitenstruktur eine Seite 'Fehlerseiten' anlegt und dann innerhalb der Seite eine neue Seite 'Fehler - 404' erstellt, dann ist der 404-Seitentyp nicht verfügbar, siehe Screenshot. Das ist auch so, wenn man eine bereits vorhandene 404-Fehlerseite in eine Unterseite verschiebt. Habe es auf zwei unterschiedlichen Contao-Installation getestet.

![contao_bug_1](https://user-images.githubusercontent.com/2542650/226871041-2da29b35-e0fd-4919-ad5b-52c393bf4cf7.png)

![contao_bug_2](https://user-images.githubusercontent.com/2542650/226871067-9e014e46-c65c-42bc-a8ff-bad2546d9824.png)

**Comment by fritzmg** [comment]
You are not supposed to be able to create a 404 page as a sub-page.

**Comment by medianetic** [comment]
Das Problem ist nicht relevant, wenn man eine neue Contao Installation hat, aber wenn man Fehlerseiten in einer älteren Contao Installation hatte (vorher ging das) und ein Update macht, sind unter Umständen die Fehlerseiten defekt.

**Comment by fritzmg** [comment]
> sind unter Umständen die Fehlerseiten defekt.

Are they actually? So if you request a non existent page in the front end, you do not see the 404 page?

**Comment by aschempp** [comment]
A 404 page will only be found if it is a first child of a root page. We might use permissions in Contao 5+ to make sure an error page is not moved to a subpage, but existing pages just need to be moved to work.
