### ISSUE TITLE
Missing backend icons

### ISSUE THREAD

**Issue by ausi** [contao/contao#5902]
### Affected version(s)

5.1

### Description

In 406ed123d5cc5c7b9424b4f7534fdafb8cd1401d a lot of icons got deleted (like header.svg, settings.svg,…).

Was this on purpose?

Many extensions may rely on these icons (especially header.svg for extensions that are compatible with 4 and 5) so this might be an unexpected break from Contao 5.0 to 5.1, at least it was for my extensions ☺️

**Comment by leofeyer** [comment]
Yes, it was on purpose, because the core no longer uses these icons and there are no dark mode variants for them. But I see the problem. Maybe we should add the `header.svg` icon again?

**Comment by ausi** [comment]
Or maybe redirect them? From `header.svg` to `edit.svg` for example?
Or fallback to a “missing-icon” icon, so that the operation itself can still be used?

**Comment by leofeyer** [comment]
> Or maybe redirect them? From `header.svg` to `edit.svg` for example?

That could work. 👍

**Comment by leofeyer** [comment]
As discussed in the call, we want to restore the `header.svg` and `settings.svg` files and add a dark-mode variant for them. We also want to check if we should restore the `published.svg` icon.
