### ISSUE TITLE
Kein Symlink für öffentlichen Ordner

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#5903]
### Affected version(s)

4.13

### Description

Ein Kunde von uns hat gerade einen tollen Bug gefunden 😁

Er hat, unterhalb eines nicht öffentlichen Ordners, einen neuen Ordner angelegt und diesen öffentlich geschaltet.
Natürlich konnte er dennoch nicht auf die Files von außen zugreifen. Er hat dann den Ordner nach "oben" verschoben, also auf die Hauptebene. Soweit alles gut. Aber: Nur durch das verschieben hat Contao keinen Symlink in `public/files` angelegt.

Über die Systemwartung war das Problem natürlich schnell behoben, dennoch sollte das wohl so nicht sein.

Was wäre jetzt die sinnvollste Lösung?

Symlinks beim Verschieben nochmal checken und ggf. anlegen oder Unterordnern von nicht öffentlichen Ordnern überhaupt erst nicht die Option geben diese als "öffentlich" zu markieren 🤔

**Comment by ausi** [comment]
> Er hat, unterhalb eines nicht öffentlichen Ordners, einen neuen Ordner angelegt und diesen öffentlich geschaltet.
> Natürlich konnte er dennoch nicht auf die Files von außen zugreifen.

Dieses Verhalten kann ich nicht reproduzieren. Öffentliche Ordner innerhalb von nicht-öffentlichen Ordnern haben in meinem Test problemlos funktioniert und die Dateien aus dem Ordner waren über den Browser erreichbar.

> Er hat dann den Ordner nach "oben" verschoben, also auf die Hauptebene. Soweit alles gut. Aber: Nur durch das verschieben hat Contao keinen Symlink in public/files angelegt.

Diesen Fehler kann ich reproduzieren.

> Was wäre jetzt die sinnvollste Lösung?
> 
> Symlinks beim Verschieben nochmal checken und ggf. anlegen

Ja, beim Verschieben von Ordnern müssen die Symlinks neu erstellt werden.

**Comment by bennyborn** [comment]
Stimmt, den ersten Punkt bekomme ich auch nicht reproduziert, klappt auf anhieb. 
Nur eben nach dem Verschieben bleibt im nicht-öffentlichen Ordner ein defekter Symlink liegen.
