### ISSUE TITLE
News Feeds (RSS/Atom): Only show featured news items

### ISSUE THREAD

**Issue by minstyle** [contao/contao#5909]
### Description

Currently, the RSS feed generation in Contao 4.13.18 automatically uses all news items of one or more news archives. There is no option how featured items are handled.

![grafik](https://user-images.githubusercontent.com/2649562/228144900-57cf381a-5138-4c26-87cb-0be67cc4c6d0.png)

It would be nice if there is also the possibility that a RSS feed could be generated from featured news items only.

Example (from module type `newslist`):

![grafik](https://user-images.githubusercontent.com/2649562/228146290-fa7185e6-f1b7-4be2-a19b-6ade3570ff7a.png)

**Comment by bezin** [comment]
I give it a shot, you may assign me @leofeyer

**Comment by bezin** [comment]
Wait a minute, I already implemented this for Contao 5.0 😅 Contao 4.13 won't receive new features so you may upgrade your Contao version. 

![2023-04-05 10_21_21](https://user-images.githubusercontent.com/4400435/230024000-8c1bbe7d-ca2b-44a4-96ec-5812c0c33f9c.png)
