### ISSUE TITLE
Server Error: ... Image type "mp4" was not allowed to be processed ... in _picture.html.twig

### ISSUE THREAD

**Issue by gmoelter** [contao/contao#5911]
### Affected version(s)

5.1

### Description

Der Fehler tritt auf, wenn im Galerie-Element unter den Quelldateien z.B. eine mp4-Datei ist. Das fatale ist, dass eine Nicht-Bild-Datei im Quelldatei-Auswahlfenster auch nicht angezeigt wird. Solange man einzelne Dateien auswählt ist das kein Problem, wählt man aber nur den Ordner aus, dann sind alle Dateien dabei (auch die, die man nicht sieht) und es kommt zum Fehler.

Reproduktion in demo.contao.org: Im Artikel "Media Elements" im zugehörigen Galerieelement z.B. den Ordner "documents" hinzufügen. Beim Speichern passiert es dann mit der pdf-Datei.

**Comment by ausi** [comment]
In the old element we skipped all files that are not images: https://github.com/contao/contao/blob/d5acf5330bab54f75cf6d1112f8298d1010e2964/core-bundle/contao/elements/ContentGallery.php#L134-L137

We should probably filter on file extensions (`%contao.image.valid_extensions%`) here too: https://github.com/contao/contao/blob/d5acf5330bab54f75cf6d1112f8298d1010e2964/core-bundle/src/Controller/ContentElement/ImagesController.php#L43

**Comment by leofeyer** [comment]
@m-vo /cc
