### ISSUE TITLE
In maintenance mode FE locked even for logged in BE users

### ISSUE THREAD

**Issue by Ernestopheles** [contao/contao#5918]
### Affected version(s)

4.13.18

### Description

In the manual I find:

> This feature allows you to put the Contao instance into a “maintenance mode”. While this mode is active, the front end is not reachable for regular visitors. Instead an appropriate message is shown. The back end is accessible as usual, logged in back end users can also visit the front end normally.

That's not the case with my installations: Enabling maintenance mode a) via CM or b) in BE via page-settings - locks pages for everybody, also when looged in in BE.

**Comment by aschempp** [comment]
There are two maintenance modes in Contao 4.13. You can enable one per root page to disable them for front end visitors. The one through the Contao Manager puts the whole system (including the back end) into maintenance mode. This is not a bug of Contao but maybe something wrong in the documentation, feel free to open a change request there 😊

**Comment by cliffparnitzky** [comment]
There are various entries regarding the maintananced mode in the docu. In my opinion this one explains the same as @aschempp explained: https://docs.contao.org/manual/de/cli/maintenance-mode/

**Comment by Ernestopheles** [comment]
Sorry, what you write is nothing new to me. As I already wrote, the FE is not reachable in BOTH ways to maintanance mode. 
So, I set maintenance to the root page (and not with CLI or CM). FE is not reachable although I am logged in in BE

**Comment by Ernestopheles** [comment]
There is as way to see the FE pages which are set to maintenance mode: Preview Mode in BE.

**Comment by aschempp** [comment]
ah, sorry I misunderstood. Yes, the maintenance mode is only bypassed when you use the preview mode (`preview.php`).

**Comment by ausi** [comment]
So should we change the text in the manual from 
*The back end is accessible as usual, logged in back end users can also visit the front end normally.* 
to something like this? 
*The back end is accessible as usual, logged in back end users can also visit the front via the preview.*

**Comment by aschempp** [comment]
Jup, but it depends on the Contao version. 

/cc @netzarbeiter

**Comment by netzarbeiter** [comment]
What do you think about this?

… angemeldete Backend-Benutzer können den Wartungsmodus über die Frontend-Vorschau umgehen.
… logged in back end users can bypass the maintenance mode using the front end preview.
