### ISSUE TITLE
Multiple editing in file manager leads to error message

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#5924]
### Affected version(s)

4.13.18

### Description

If I want to adjust the metadata of multiple files via "edit multiple", then this leads to an error message if the file name contains "spaces".

1. open file manager
2. multiple files with spaces in the file name
3. select files by editing them several times
4. select edit metadata
5. error message Invalid resource

`[2023-04-03T12:17:26.999220+02:00] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Invalid resource files/assets/contentpics/Chemistry%20class%20w%20teacher.jpeg" at /home/www/contao413/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Dbafs.php line 65 {"exception":"[object] (InvalidArgumentException(code: 0): Invalid resource files/assets/contentpics/Chemistry%20class%20w%20teacher.jpeg at /home/www/contao413/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Dbafs.php:65)"} []`

I know that spaces are bad practice, but what the customer does is not always in my control.

**Comment by ausi** [comment]
Could this be a duplicate of #5886 and #5887 ?

**Comment by contaoacademy** [comment]
Yes, I think it is the same problem.
