### ISSUE TITLE
Problem deleting files via multi edit if file path contains space

### ISSUE THREAD

**Issue by vicotec** [contao/contao#5928]
### Affected version(s)

4.13.18

### Description

If you try to delete one or multiple images in the file manager with multi editing activated and the file path or file name contains an empty space you get the following error:

> Forbidden
> File or folder "files/img/test%20folder/testimage.jpg" is not mounted or cannot be found.

If you replace the space with a dash or an underscore the behaviour is normal.

Reproduction:
- Open file manager
- Create a folder containing a space e.g. "test folder"
- Upload an image into the folder
- Select "Edit multiple"
- Check the image and select "Delete"
- The error occurs

There seems to be no problem, when deleting the image directly or when using multi edit for moving files.

**Comment by ausi** [comment]
Could this be a duplicate of https://github.com/contao/contao/issues/5924, https://github.com/contao/contao/issues/5886 and https://github.com/contao/contao/pull/5887 ?

**Comment by vicotec** [comment]
Yes sorry, hadn't found it with my search terms.
Duplicate #5924,  #5886 and #5887?
