### ISSUE TITLE
Safari reports TypeError - ld+json @context

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#5932]
### Affected version(s)

4.13.18

### Description

When a Contao page is accessed with the Safari browser, I see this error in the Console:
```
[Error] TypeError: undefined is not an object (evaluating 'r["@context"].toLowerCase')

	(anonyme Funktion) (de:3:186)
	Globaler Code (de:3:363)
```

Is this a Safari issue, or would this need to be fixed on Contao?
The error can also be seen on contao.org

![screen-20230405_Lq3fn31i](https://user-images.githubusercontent.com/23719181/230016561-ad2f4241-cd8d-4916-aa21-dc14adf05440.jpg)

**Comment by leofeyer** [comment]
This is a weird error message indeed. There is not even a script in line 3. @ausi Any idea?

**Comment by fritzmg** [comment]
@frontendschlampe reported this on Slack recently. Some search results for this error indicate that this might be caused by an internal JavasScript of Safari, possibly related to the Reader Mode.

**Comment by leofeyer** [comment]
I also think that this is a Safari bug. Apparently, it tries to evaluate the `<script type="application/ld+json">` data as regular JavaScript. 🙈

**Comment by ausi** [comment]
Yes, seems to be a Safari bug as every website that has `<script type="application/ld+json">` with `@context` seems to be affected by this.

**Comment by m-vo** [comment]
Looks like this (uncondirmed) WebKit issue: https://bugs.webkit.org/show_bug.cgi?id=255764

Apparently, the problem is the "square bracket syntax", i.e. a JSON array:
```html
<script type="application/ld+json">[…]</script>
```

Maybe someone with Safari could try to output multiple script tags instead and see if this would resolve the issue?

**Comment by Toflar** [comment]
I don't think we'll work around that issue just because of Safari. It's clearly a Safari bug so we might as well just wait for them to fix it :)

**Comment by m-vo** [comment]
Yes, think so too. Maybe it's worth confirming the issue over at their bug tracker, though. 🙂

**Comment by leofeyer** [comment]
I think we can use two `<script>` tags instead of one with a JSON array to be compatible with all browsers. So instead of this:

```html
<script type="application/ld+json">
[
    {
        "@context": "https://schema.org",
        "@graph": [
        ]
    },
    {
        "@context": "https://schema.contao.org",
        "@graph": [
        ]
    }
]
</script>
```

It would be this:

```html
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@graph": [
    ]
}
</script>
<script type="application/ld+json">
{
    "@context": "https://schema.contao.org",
    "@graph": [
    ]
}
</script>
```

I ran some tests with the validator and the detected data was the same. Not sure if Escargot supports this though?

**Comment by Toflar** [comment]
How's Escargot related to JSON-LD?

**Comment by ausi** [comment]
> Not sure if Escargot supports this though?

You probably meant this? https://github.com/contao/contao/blob/18aa4130af8785b6427fa33e2db9ce740cd391a0/core-bundle/src/Search/Document.php#L114

From reading the code I think your version is supported, but I didn’t test it manually.

**Comment by leofeyer** [comment]
Yes, that is what I meant. It is not part of Escargot, sorry. But it does read multiple `<script type="application/ld+json">` sections, so it is compatible.
