### ISSUE TITLE
Add links for all (not active) trailing page links in articles breadcrumb menu again

### ISSUE THREAD

**Issue by samtigall** [contao/contao#5945]
### Description

Hello Contao :)

In #3391 the links for trailing pages in breadcrumbs were removed. We recently updated contao for a customer from 4.5 to 4.13 and he used to work with that navigation. Is there a specific reason why it got removed?

Thanks!

**Comment by Toflar** [comment]
Why are you mentioning https://github.com/contao/contao/pull/3391 exactly? This does not affect the breadcrumb? Maybe you can describe your issue more in detail and tell us how to reproduce it in the online demo?

**Comment by aschempp** [comment]
`Backend::addPagesBreadcrumb` has been changed in the mentioned PR, so maybe that's affecting the breadcrumb?

**Comment by Toflar** [comment]
Yeah but I wonder why this PR has been mentioned explicitly. It's 2 years old and things have changed 10 times since. Hence the question on how to reproduce in the online demo.

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/contao/issues/5707 may be?

**Comment by samtigall** [comment]
> Duplicate of #5707 may be?

yes, correct! I didnt find that issue when i searched for breadcrumbs - sorry.
