### ISSUE TITLE
Restricting/hiding news archives for certain users does not work

### ISSUE THREAD

**Issue by md-netdesign** [contao/contao#5950]
### Affected version(s)

5.1.2

### Description

Hello there!

We've encountered a bug inside the news bundle. If a user is restricted to certain news archives, the news archive list will not load as expected with fewer visible news archives and instead a "403 Access Denied" is thrown.

### We created a minimal example with the following steps:

You can also try this with the [official contao demo](https://demo.contao.org/). There it won't work either.

(1) Install Contao 5.1
```bash
composer create-project contao/managed-edition news-bundle-bug # Contao 5.1
cd news-bundle-bug
echo "DATABASE_URL=mysql://root@localhost:3306/news-bundle-bug?serverVersion=mariadb-10.4.22" >> .env.local
vendor/bin/contao-console doctrine:database:create
vendor/bin/contao-console contao:migrate --no-interaction --with-deletes
vendor/bin/contao-console contao:user:create --username=test --name=test --email=test@contao.org --password=12345678 --admin --language=de
```

(2) Open the Contao backend and login with "test" and "12345678"
(3) Create the following page structure (so one can set a redirect page inside the news archive)
![Page structure](https://user-images.githubusercontent.com/90682614/231744721-d7451f1d-372a-4ea6-b35a-723fea229180.jpg)

(4) Create the following 2 news archives
![News archives](https://user-images.githubusercontent.com/90682614/231744895-bcd44a74-8bba-4b70-8d79-5299c6acd233.jpg)

(5) Create a new user, with the following permissions
![Base user](https://user-images.githubusercontent.com/90682614/231744970-f7599023-d1de-4b47-99c2-b8e8cbfb08af.jpg)

![User permissions 1](https://user-images.githubusercontent.com/90682614/231745024-61756637-df52-465c-ab7c-427a0e6009ba.jpg)

![User permissions 2](https://user-images.githubusercontent.com/90682614/231745040-a2c32a4e-6f0f-485f-8f40-ccd247972c4b.jpg)

(6) Log in to that user either via the backend or directly and click "News"
![Simple error](https://user-images.githubusercontent.com/90682614/231745139-bdc7dc18-004e-4a5b-af97-5e21d3bb4600.jpg)

![Stacktrace](https://user-images.githubusercontent.com/90682614/231745172-705c10a9-83cd-49c0-be85-6e3fb4f85487.jpg)

### Investigation

Looking further into it, because we first thought it might be a bug introduced by our application, we found, that the query at [line 5105 in DC_Table.php](https://github.com/contao/contao/blob/5.x/core-bundle/contao/drivers/DC_Table.php#L5105) is in no way restricted and loads all available news archives.

Dumping the query with `dd($query);` yields:
```plain
DC_Table.php on line 5105:
"SELECT * FROM tl_news_archive ORDER BY title, id"
```
which does not look right.

IMO, there should be a WHERE clause, which prevents loading all news archives, that the user has no access to.

Further down, at [line 5205](https://github.com/contao/contao/blob/5.x/core-bundle/contao/drivers/DC_Table.php#L5205), the exception will then be raised if the user has no permission to view the news archive.

---

Any advice for solving this will be appreciated, either directly as a fix in Contao or in our application. If we misunderstood the feature of restricting news archives, please point us in the right direction.

Thanks for your time in advance! 🙂

**Comment by Toflar** [comment]
Duplicate of https://github.com/contao/contao/issues/5948 - I guess?

**Comment by Toflar** [comment]
Fix would be here: https://github.com/contao/contao/pull/5949

**Comment by md-netdesign** [comment]
Thanks. I'll try the fixed version and report back!

**Comment by md-netdesign** [comment]
Yes! Duplicate of #5948.

The query now yields correctly `SELECT * FROM tl_news_archive WHERE id IN(2) ORDER BY title, id`.

Thanks for pointing us in the right direction @Toflar. We did overlook that issue, because it was already closed.
