### ISSUE TITLE
Empty Downloads content element results in error 500

### ISSUE THREAD

**Issue by stefansl** [contao/contao#5956]
### Affected version(s)

5.1.2

### Description

Add a new CE from type "Downloads". Do not choose any files and save ...

`Contao\CoreBundle\Filesystem\FilesystemUtil::listContentsFromSerialized(): Argument #2 ($sources) must be of type array|string, null given, called in /var/www/sgv/htdocs/vendor/contao/core-bundle/src/Controller/ContentElement/DownloadsController.php on line 120`

**Comment by cliffparnitzky** [comment]
Can confirm. Currently the field `Source files` is not mandatory (as it was in Contao 4.9 and Contao 4.13).

@contao/developers Any idea for which case this makes sense? Or is the solution to make this field mandatory?

**Comment by cliffparnitzky** [comment]
Just to clarify, the front end problem doen't occure with Contao 4.9 and Contao 4.13.

**Comment by stefansl** [comment]
@cliffparnitzky Ah, you're right. Same in the CE "Gallery" - field is not mandatory anymore

**Comment by m-vo** [comment]
See #5957

**Comment by cliffparnitzky** [comment]
@m-vo Looks good, but shouldn't we also think about whether the field ´multiSRC´ has to be mandatory? I think a Downloads element without files doesn‘t make sense. Same for the gallery which is also using this field.

**Comment by m-vo** [comment]
> Can confirm. Currently the field Source files is not mandatory (as it was in Contao 4.9 and Contao 4.13).

The `multiSrc` field was not mandatory in Contao 4.13 (same in 4.9 as far as I can tell).

This issue has nothing to do with the issue @stefansl mentioned in the original post. If you feel, that this should be changed, please create another ticket for this.

**Comment by fritzmg** [comment]
Even if it would be mandatory, this issue could still occur (e. g. when switching the type).

**Comment by cliffparnitzky** [comment]
> but shouldn't we also think about whether the field ´multiSRC´ has to be mandatory? I think a Downloads element without files doesn‘t make sense. Same for the gallery which is also using this field.

I've created the PR #5984.
