### ISSUE TITLE
download improvement for filemanger

### ISSUE THREAD

**Issue by asaage** [contao/contao#5965]
If you work in the BE with the filemanager it would be beneficial if you are able to download files from non-public folders.
In public folders you can get a direct link from the file-icon but that does not work from inside non-public folders.
I think i would prefer to have more consistentcy in this case (maybe by incorporating the download-conroller) and always get the wanted file as content-disposition: attachment for every file.
Sometimes there are files that can't be edited in contao and you can't find your local copy anymore and then you have to duplicate it or make the folder public to get it.
What do you think, are there any security-related concerns?

**Comment by fritzmg** [comment]
Such a button already exists:

<img src="https://user-images.githubusercontent.com/4970961/232476675-15520fc5-829a-42d7-8df5-3da4a05c6c4e.png" width="360">

**Comment by asaage** [comment]
I see - that's on the file-info modal - never noticed that.
I was thinking about the icon in front of the filename in the tree-view.

**Comment by fritzmg** [comment]
I think that should stay as it is.

**Comment by asaage** [comment]
One aditional click but it serves the purpose for me.
