### ISSUE TITLE
download(s) Template meta-title

### ISSUE THREAD

**Issue by asaage** [contao/contao#5975]
### Affected version(s)

5+

### Description

Since contao added the dbfs in 3.x i was used to alter the output of ce_download(s) by adding a title in the meta-data.
With the newly shipped twig-templates this has changed - now title is rendered as title-attribute of the link and without altering the template i'm kind of stuck to presenting (unfortunately most of the time ridiculous) filenames to the visitor.
Just wanted to know if that was a deliberate decision or if you'd consider changing that back to the previous behaviour.
![image](https://user-images.githubusercontent.com/4138336/233374317-ba14c6fd-4c8e-46c6-b3a8-ab917a47852b.png) **vs** ![image](https://user-images.githubusercontent.com/4138336/233374745-6a7f1ac9-7118-4770-8571-73d0d3dfbef7.png)

**Comment by m-vo** [comment]
See #5981
