### ISSUE TITLE
Twig interprets a redirect exception as an error

### ISSUE THREAD

**Issue by qzminski** [contao/contao#5977]
### Affected version(s)

5.1.x

### Description

It seems that Twig will catch the `Contao\CoreBundle\Exception\RedirectResponseException` and will throw type `Twig\Error\RuntimeError` error. The issue happens only with the content elements / frontend modules that use the new Twig templates (like Unfiltered HTML content element).

Steps to reproduce on demo.contao.org:

1. Create a content element of "Unfiltered HTML" type with the following content:

```
{{insert_module::17}}
```

It will display the "lost password" frontend module.

2. Go to the frontend and enter `d.evans` and `d.evans@example.com` respectively and submit the form.
3. Error.

<img width="1049" alt="CleanShot 2023-04-21 at 17 14 54" src="https://user-images.githubusercontent.com/193483/233672768-87160040-96e7-452c-8421-e46c41744dba.png">

<img width="1075" alt="CleanShot 2023-04-21 at 17 15 24" src="https://user-images.githubusercontent.com/193483/233672901-db07ca81-13e7-4d96-b51b-be50b57b7a6c.png">

/cc @Toflar

**Comment by Toflar** [comment]
@m-vo does Twig provide some exception handling extension point where we might handle this? 🙈

**Comment by m-vo** [comment]
No there ain't one unfortunately. We could maybe add a `{% try %}` tag but that's not really solving the problem. 😐 I had encountered this issue before as well (there is also a ticket somewhere). I think, ultimately, we need to refactor the controllers. But there are quite some blockers at the moment (think about permissions for the downloads for instance).

**Comment by aschempp** [comment]
maybe this will be (partially) solved by the new Twig functions? https://github.com/contao/contao/pull/5808 😎

**Comment by m-vo** [comment]
> maybe this will be (partially) solved by the new Twig functions? #5808 

No, when the function (e.g.  `{{ content_element(123) }}`) is executed you are already in the templates `try`/`catch` block. 

But, I was thinking about the issue again: Could/should we maybe add an exception event listener (like our `PrettyErrorScreenListener`) that checks for the Twig specific `RuntimeException` and rethrows it as `$e->getPrevious()` if its a `RedirectResponseException`?

**Comment by m-vo** [comment]
See #5980.
