### ISSUE TITLE
Support autocompete attribute on form controls

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#598]
**Description**  

According the html standard the autocomplete field supports a number of options to map autocomplete data to a form field (https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute).

It would be nice if

 - forms in modules (registration, comment and so on) would support it
 - form fields in the form generator have the ability to define the autocomplete field

**Comment by leofeyer** [comment]
See #1669.
