### ISSUE TITLE
The title of downloads no longer work in version 5.1

### ISSUE THREAD

**Issue by heimseiten** [contao/contao#5982]
### Affected version(s)

5.1

### Description

In the content elements "Download" "Downloads" the titles don't show up in the frontend. In 4.13 it works.

**Comment by Toflar** [comment]
Duplicate of https://github.com/contao/contao/issues/5975?

**Comment by heimseiten** [comment]
Yes. Sorry 🙈. The fix solved the issue

Thank you!
