### ISSUE TITLE
Auto-item usage broken in Contao 5

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#5983]
### Affected version(s)

5.1

### Description

This is a follow-up on #4340 where we have removed `TL_AUTO_ITEM`.

The case studies on contao.org use the following URLs:

* `https://contao.org/de/fallstudien.html`: lists all case studies
* `https://contao.org/de/fallstudien/kategorie.html`: lists all case studies from a certain category
* `https://contao.org/de/fallstudien/show/1234.html`: shows a particular case study

The changelanguage extension now generates the following links:

* `https://contao.org/en/case-studies.html`: correct
* `https://contao.org/en/case-studies/category.html`: correct
* `https://contao.org/en/case-studies/1234.html`: **incorrect** → the `/show/` fragment is missing!

There is no way to solve this problem without `TL_AUTO_ITEM`, so this is not a bug in the extension IMHO. We would need the `TL_AUTO_ITEM` information to properly fix https://github.com/terminal42/contao-changelanguage/pull/228.

**Comment by ausi** [comment]
I don’t think the core needs to be changed here, IMO the fix could be something like this: https://github.com/terminal42/contao-changelanguage/pull/229

**Comment by aschempp** [comment]
I don't understand this at all. Are _Fallstudien_ your own extension? Then you would need to provide an event listener that correctly translates the URL?

**Comment by leofeyer** [comment]
See https://github.com/terminal42/contao-changelanguage/pull/230.
