### ISSUE TITLE
undefined method named "importList" of class "Contao\ListWizard".

### ISSUE THREAD

**Issue by asaage** [contao/contao#5991]
### Affected version(s)

5.1

### Description

To reproduce:
Create a content-element Tyle "list"
if you try to import items following Error is thrown:

```Attempted to call an undefined method named "importList" of class "Contao\ListWizard".```

Fun fact: it works if the parent is an article but not if the parent is a news-item (didn't test in events though).

**Comment by ausi** [comment]
Confirmed. The issue appears in content elements from news and events.
