### ISSUE TITLE
How helpful is the "Bad credentials" log entry?

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#5992]
### Description

My log is full of there entries:

<img width="408" alt="" src="https://user-images.githubusercontent.com/1192057/234556989-488fb1e1-6c84-475e-bc5d-3ec19c130a5b.png">

The details view is this:

<img width="882" alt="" src="https://user-images.githubusercontent.com/1192057/234557088-2858881e-1929-4419-b54a-83cc24fcff67.png">

Can anyone tell me why we are writing these messages into the system log? They provide no added value IMHO.

**Comment by asaage** [comment]
I don't see a real benefit to log this here.
Might be off-topic:
If i use bad credentials there is no 401 or 403 in my webserver-logs either - which could be useful for fail2ban (don't know if that would change if a protected jump-to page was used though).

**Comment by Toflar** [comment]
Imho we can remove that. At least in prod. In dev it might be helpful when debugging but I'm okay with removing it completely.

**Comment by bytehead** [comment]
@leofeyer I'm also for removing it. You can assign me this after a decision is made ☺️

**Comment by leofeyer** [comment]
As discussed in the call, this should be a debug message logged in the default Symfony security channel.
