### ISSUE TITLE
MetaWizard loading old metadata failed

### ISSUE THREAD

**Issue by JanMalte** [contao/contao#5994]
### Affected version(s)

4.13.19

### Description

Loading the languages from existing meta data may fail and result in error loading the edit page of a file.

Affected lines/traceback
```php
# vendor/contao/core-bundle/src/Resources/contao/widgets/MetaWizard.php:168
$languages = System::getContainer()->get('contao.intl.locales')->getDisplayNames(array_keys($this->varValue));
```

Database value
`613a343a7b733a323a226465223b613a343a7b733a353a227469746c65223b733a38323a2256454c4f4265726c696e203230323320504d313a2046616872726164666573746976616c206272696e6774206e657565204d6f62696c6974c3a47420696e2064656e20616c74656e20466c7567686166656e223b733a333a22616c74223b733a303a22223b733a343a226c696e6b223b733a303a22223b733a373a2263617074696f6e223b733a303a22223b7d693a313b613a313a7b733a333a22616c74223b733a303a22223b7d693a323b613a313a7b733a343a226c696e6b223b733a303a22223b7d693a333b613a313a7b733a373a2263617074696f6e223b733a303a22223b7d7d`

Deserialized value `$this->varValue` in `MetaWizard->generate()`
```
array(4) {
  ["de"]=>
  array(4) {
    ["title"]=>
    string(82) "VELOBerlin 2023 PM1: Fahrradfestival bringt neue Mobilität in den alten Flughafen"
    ["alt"]=>
    string(0) ""
    ["link"]=>
    string(0) ""
    ["caption"]=>
    string(0) ""
  }
  [1]=>
  array(1) {
    ["alt"]=>
    string(0) ""
  }
  [2]=>
  array(1) {
    ["link"]=>
    string(0) ""
  }
  [3]=>
  array(1) {
    ["caption"]=>
    string(0) ""
  }
}
```

This leads to the following locales in `vendor/contao/core-bundle/src/Intl/Locales.php:207`
```
array(4) {
  [0]=>
  string(2) "de"
  [1]=>
  int(1)
  [2]=>
  int(2)
  [3]=>
  int(3)
}
```

**Possible workaround/fix**

```php
# vendor/contao/core-bundle/src/Resources/contao/widgets/MetaWizard.php:230
                // Add the existing entries
                if (!empty($this->varValue))
                {
                        $languages = System::getContainer()->get('contao.intl.locales')->getDisplayNames(
                            array_filter(array_keys($this->varValue), function ($k,$v) {return !is_numeric($v);}, ARRAY_FILTER_USE_BOTH)
                        );
                        $items = array();

                        // Add the input fields
                        foreach ($this->varValue as $lang=>$meta)
                        {
                            # skip value if $lang is not a string/valid locale
                            if (!is_string($lang)) {continue;}
                            # ...
```

**Comment by ausi** [comment]
> Loading the languages from existing meta data may fail and result in error

Please post the exact error message and a full stack trace if possible.

**Comment by JanMalte** [comment]
![veloberlin com_internalservererror_2023-04-27](https://user-images.githubusercontent.com/544986/234968318-3defd136-e5f6-46c7-8f40-1b31248c7a99.jpg)

sorry, I currently only have this screenshot.
As soon as I‘m back at the computer, I may add the text version and try to get a native PHP error.

**Comment by ausi** [comment]
Can you please try if changing this line https://github.com/contao/contao/blob/153d29e9c55e82089d0c0995ca6cf5c862210ae3/core-bundle/src/Resources/contao/widgets/MetaWizard.php#L168 to this:
```php
$languages = System::getContainer()->get('contao.intl.locales')->getDisplayNames(array_map('strval', array_keys($this->varValue)));
```
fixes the issue in your case?

**Comment by JanMalte** [comment]
@ausi yes, this fixes the error messages.

![grafik](https://user-images.githubusercontent.com/544986/235064954-73fd5a22-2d80-494c-a00e-71e5bf7ad1b8.png)

The old/invalid meta data is still shown. I therefor added the check & continue statement.
```php
# vendor/contao/core-bundle/src/Resources/contao/widgets/MetaWizard.php:171
// Add the input fields
foreach ($this->varValue as $lang=>$meta)
{
        # skip value if $lang is not a string/valid locale
        if (!is_string($lang)) {continue;}
```

![grafik](https://user-images.githubusercontent.com/544986/235065403-d687ac8f-8164-4a8b-85db-1edd859c175e.png)

**Comment by ausi** [comment]
> The old/invalid meta data is still shown.

I think that would be the best behavior. 
Do you know where this “old” metadata came from? I’m not aware of any previous Contao version that stores the metadata in such a way.

**Comment by JanMalte** [comment]
The latest updates has been 4.9 -> 4.13

It seems like the meta data is not stored with translations but as a flat array instead.
