### ISSUE TITLE
 Update von 3.5 auf 4.4 - Eigene Layoutbereiche werden nicht übernommen

### ISSUE THREAD

**Issue by tschero** [contao/contao#60]
**Affected version(s)**
Contao 4.4.21 - 24 LTS

**Description**  
Guten Morgen,

ich habe bisher mehrere Contao Installationen mit einem kommerziellen Template von C 3.5 auf 4.4 LTS aktualisiert.
Die aktualisierten Websites haben mehrere Seitenlayouts.
Jedes Mal werden (ausgenommen beim Seitenlayout - Home - für die Startseite) die eigenen Layoutbereiche nicht übernommen und sind leer. Somit müssen auch die FE - Module neu zugeordnet werden.
Das Problem wurde mit dem Themehersteller bereits besprochen. Der Fehler scheint bei Contao zu liegen.
Gruß
tschero

**How to reproduce**  
Update von Contao 3.5 auf 4.4 LTS mit mehreren Seitenlayouts und eigenen Layoutbereichen

**Comment by tschero** [comment]
![full_width_eig_lber](https://user-images.githubusercontent.com/7802635/45545665-466d5c00-b81b-11e8-9f6d-72fcb2588fa0.JPG)
![full_width_fe_module](https://user-images.githubusercontent.com/7802635/45545668-48cfb600-b81b-11e8-850f-c0981ab3ccb6.JPG)

**Comment by fritzmg** [comment]
Kannst du einen dump der `tl_layout` Tabelle aus der Contao 3.5 Installation zur Verfügung stellen?

**Comment by tschero** [comment]
Guten Morgen,
hier die gewünschten Info´s.

[tl_layout.zip](https://github.com/contao/contao/files/2387500/tl_layout.zip)

**Comment by leofeyer** [comment]
Behoben in 724df8295fd44378a5b5869e807c7e23ba0dbdb3.
