### ISSUE TITLE
Symfony session

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#60]
As discussed [here](https://github.com/contao/core-bundle/pull/52/files#r25709862), we are currently not using the Symfony session. Is this something we should change?

**Comment by aschempp** [comment]
The CoreBundle does not need it for now. I think we should only enable it if we plan to replace the Contao session with Symfony, but we'd need a concept for that first. Not a priority for 4.0 to me.

**Comment by Toflar** [comment]
Can be closed in favor of https://github.com/contao/core-bundle/pull/68
