### ISSUE TITLE
Add tokens for css grid

### ISSUE THREAD

**Issue by planepix** [contao/contao#600]
**Description**  
Bei einer Website arbeite ich mit CSS Grid. In der Regel mit einem externen Editor.
Ruft man diese CSS-Datei in der Dateiverwaltung auf, werden Eigenschaften von CSS Grid in der Dateiverwaltung markiert mit „Unexpected token” und „Unknown property”.

Kann man das für künftige Versionen ergänzend, so das die Hinweise obsolet werden?

**Example**  
![css-grid-backend](https://user-images.githubusercontent.com/1823889/61554125-82390980-aa5c-11e9-9f58-eb1ccdb7bd6d.png)

**Comment by leofeyer** [comment]
Das müsstest Du direkt bei [ajaxorg/ace](https://github.com/ajaxorg/ace) melden. Dort fehlen die Tokens in den CSS rules: 

https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/css_highlight_rules.js

**Comment by planepix** [comment]
Done: https://github.com/ajaxorg/ace/issues/4025
