### ISSUE TITLE
Contao stops rendering if subtemplates are too large without error or warning

### ISSUE THREAD

**Issue by LBeckX** [contao/contao#6011]
### Affected version(s)

4.13

### Description

I have built an extension that outputs tempaltes with subtemplates. These are created during the rendering process. Some of these templates have up to 9000 subtemplates.
If these subtemplates exceed a certain size, Contao stops rendering insert and script tags.
Are there any limits or maximum execution times here?
In the PHP.ini itself, I set all the limits very high, but this did not bring any success. Also, no error is output, neither in the Apache log nor in the Contao var/log or in Dev-Mode.
In PHP 7.4 with Contao 4.9 there were no problems. I compared the PHP.ini of both systems.

![image](https://user-images.githubusercontent.com/11272361/235867506-59892a50-d641-4688-a0c1-987de4e04142.png)

![image](https://user-images.githubusercontent.com/11272361/235868745-92daed00-6026-4c3d-ba80-6583f8788a5b.png)

**Comment by Toflar** [comment]
I strongly suspect you are running into some resource limits and I don't know how we should be able to help here.

This seems more like a support ticket which should go to the forums or Slack etc. but here are some general hints:

* 9000 templates - what the heck? Maybe you should re-think your approach?
* Insert tags in templates sounds wrong - you are already within PHP, you normally don't need insert tags there.
* You may want to profile your process using Blackfire or the likes

**Comment by LBeckX** [comment]
Hi Toflar
thanks for the quick answer.
It makes no difference whether there are 9000 short or 20 very long subtemplates.
It is not about insert tags in the templates but all insert tags on the page. Like in the example above in the pictures.

**Comment by Toflar** [comment]
Unless you can provide a step by step description of how we can reproduce the issue starting from an empty Contao setup, we won't be able to help and will have to close this issue.

**Comment by ausi** [comment]
@LBeckX does it help if you increase the values for `pcre.backtrack_limit` and `pcre.recursion_limit`
 (see https://www.php.net/manual/en/pcre.configuration.php )

Can you add a debug like like `dump(strlen($strBuffer))` here and tell us what the highest values was? https://github.com/contao/contao/blob/d02638f860b61a4a08ae71124d46f6997c5cb0ef/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L89-L90

**Comment by LBeckX** [comment]
@ausi @Toflar

The changes at https://www.php.net/manual/en/pcre.configuration.php
have fixed the problem!
Yeaa! Thank you very much!

The biggest value that was issued was: `1913175`

**Comment by ausi** [comment]
@LBeckX can you please check which of the two values was responsible, the backtrack_limit or the recursion_limit?

Maybe we can optimize the regular expression so that we do not run into those limits.

**Comment by LBeckX** [comment]
@ausi it was the setting of the `pcre.backtrack_limit`
In my case I have now increased it to 10000000.

Also, when saving these map values, the values were cut off and values were not transferred.
I was able to fix both with these adjustments.

```ini
max_input_vars=64000
pcre.backtrack_limit=10000000
```
