### ISSUE TITLE
Problem beim Umschreiben der .env.local

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#6013]
### Affected version(s)

4.9.41, 4.13.23

### Description

Wenn Contao beim Update das `APP_SECRET` in die `.env.local` schreibt, wird die komplette `.env.local` umgeschrieben. Bisher ist mir folgendes aufgefallen:

- die `"` werden entfernt, die um die Werte gewesen sind
- aus der DB-URL mit Variablen `DATABASE_URL="mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=${DATABASE_VERSION}"` werden die Variablen entfernt und durch die direkten Werte ersetzt

**Comment by fritzmg** [comment]
I can confirm the issue. While unnecessary double quotes being removed is to be expected, Symfony's `Dotenv` unfortunately (but expectedly) resolves any environment variables within the environment variables. There does not seem to be a way to parse them without resolving the values.

**Comment by m-vo** [comment]
We could parse the file with the component, but then manually append it, when generating the secret. At least for the older Contao versions - I don't think Sf is going to change anything here as a bugfix.

**Comment by fritzmg** [comment]
I think it would need to be a separate tool/component anyway. `DotenvManipulator`

**Comment by fritzmg** [comment]
Btw. the same problem would arise when using the Contao Manager to set the database credentials in Contao 5.

**Comment by ausi** [comment]
> I think it would need to be a separate tool/component anyway. `DotenvManipulator`

I think I would just update our current `DotenvDumper` in a way that it only manipulates the lines where a new value was set. I will try a quick PR for that... #6015
