### ISSUE TITLE
User Permissions: Allow or disallow individual front-end modules

### ISSUE THREAD

**Issue by bezin** [contao/contao#6016]
In the user permissions back-end module we can allow or disallow individual content elements. 

<img width="151" alt="2023-05-06 14_59_04" src="https://user-images.githubusercontent.com/4400435/236625662-d2f2da54-b814-4d28-ab8f-44c2ad3f174f.png">

It would be nice if we could also allow or disallow individual frontend-modules. 

Discussed in the back-end session at the [Contao Camp 2023](https://github.com/contao-community-alliance/contao-camps/blob/main/2023/camp-2023.md#samstag-06052023).

**Comment by aschempp** [comment]
I mostly would find this useful to limit the options a user can see in the `module` content element. But it obviously should also limit the module list.

**Comment by aschempp** [comment]
this has been implemented in https://github.com/contao/contao/pull/6232
