### ISSUE TITLE
Editing image sizes inside a content element

### ISSUE THREAD

**Issue by timmuz** [contao/contao#6020]
### Description

Affects: Usability

When you are inside a content element it is not possible to edit set image sizes, but it would be useful to be able, instead handling multiple tabs.

![image](https://user-images.githubusercontent.com/38328223/236627729-0387ac1f-a988-4527-956f-d374aa3dc1a4.png)

It could be realized by opening a lightbox, just like when you edit included forms or other included articles.

(As discussed on Contao Camp 2023 / https://github.com/contao-community-alliance/contao-camps/blob/main/2023/camp-2023.md#samstag-06052023)

**Comment by aschempp** [comment]
See #5610
