### ISSUE TITLE
Accessibility of BE navigation: Increase contrast between normal and hover state

### ISSUE THREAD

**Issue by spacefront** [contao/contao#6026]
### Description

The current hover state of the main backend navigation is not sufficiently different from the normal state.

To solve this, for example, use a hover state that is similar to the active state, or just orange.

**Comment by zonky2** [comment]
As discussed on Contao Camp 2023 / https://github.com/contao-community-alliance/contao-camps/blob/main/2023/camp-2023.md#samstag-06052023

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6046
