### ISSUE TITLE
Logout im Backend und Frontend sind abhängig voneinander

### ISSUE THREAD

**Issue by V15** [contao/contao#6028]
### Affected version(s)

5.1

### Description

Wenn man im Frontend als Mitglied und gleichzeitig im Backend als Benutzer anmeldet ist, und sich an einer Stelle abmeldet, wird man automatisch an der anderen Stelle ebenfalls abgemeldet.

(As discussed on Contao Camp 2023 / https://github.com/contao-community-alliance/contao-camps/blob/main/2023/camp-2023.md#samstag-06052023)

**Comment by ausi** [comment]
Duplicate of #5899

**Comment by zonky2** [comment]
@V15 dann wäre interessant, ob das als "known limitation" im Handbuch bei FAQ oder so auftaucht...
