### ISSUE TITLE
Provide shortcut / reminder to allow certain things after adding new things

### ISSUE THREAD

**Issue by bezin** [contao/contao#6030]
### Description

When you add a image size (or content element, form, page type, ...) it is not allowed in the user (group) permission per default, but has to be allowed manually afterwards. It would be nice to have a shortcut for this, e.g. as part of a notice in the backend.

![2023-05-07 12_24_02](https://user-images.githubusercontent.com/4400435/236672179-eabdb4f8-3891-4b3c-9872-1a188970f29a.jpg)

As discussed in the Back-end session at the [Contao Camp 23](https://github.com/contao-community-alliance/contao-camps/blob/main/2023/camp-2023.md#samstag-06052023)

**Comment by aschempp** [comment]
closing in favor of https://github.com/contao/contao/pull/6036
