### ISSUE TITLE
Link Contao Manager im Backend fehlt / Zusätzlicher Check im Manager?

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6032]
### Affected version(s)

4.13.x

### Description

Bei ein paar meiner Installationen hat der Manager-Link im Backend gefehlt.

Ursache war, dass ein Verzeichnis `/web` und `/public` vorhanden war. Das kam wohl, nach einer Umstellung des Dokument-Root von `web` zu `public`.

Nach Löschung des web-Verzeichnis und erneutem composer-update war der Link zum Manager wieder da.

## Frage
Wäre ein Systemcheck hilfreich, der prüft, ob public und web-Verzeichnis gleichzeitig vorhanden sind und dann eine Warnung ausgibt?
Ist das überhaupt ein Thema vom Manager oder eher von Contao?

**Comment by ausi** [comment]
Wenn `web` und `public` existiert und das verzeichnis weder in der composer.json, noch in der config.yaml konfiguriert ist, dann verwendet Contao 4 das `web` Verzeichnis.

Sollte aber eigentlich noch zu mehr Fehlern führen als nur einem fehlenden Manager-Link.

Ob wir daran etwas verbessern können bzw. sollen bin ich mir nicht sicher.

**Comment by contaoacademy** [comment]
Kann hier noch was verbessert werden oder sollen wir das Ticket schließen?

**Comment by leofeyer** [comment]
How often has this problem occurred in the last 18 months? If only a few users run into this, we should probably not invest any time.

**Comment by contaoacademy** [comment]
I haven't noticed this problem recently. I also think that we shouldn't invest any time here for the time being and close the ticket.
