### ISSUE TITLE
image size label for select in config.yml

### ISSUE THREAD

**Issue by operatorone** [contao/contao#6048]
### Description

If image sizes are defined in the config.yml, it might be a great addition not only to display the name of the size (e.g., "teaser_image") in the backend select menu but also to have a label like "Teaser - Image - 16x9", which is much more readable for the user in the select menu.

**Comment by de-es** [comment]
https://docs.contao.org/dev/framework/image-processing/image-sizes/#translating-size-configurations

**Comment by bytehead** [comment]
This is already possible as @de-es correctly linked the documentation for it.

**Comment by operatorone** [comment]
Thanks for the tip.
