### ISSUE TITLE
Forms > XML File produces invalid XML

### ISSUE THREAD

**Issue by lizardat** [contao/contao#6053]
### Affected version(s)

4.13

### Description

When sending data from a form via "send form data" > "XML File" the submitted file can contain characters that are not valid in XML files, like < > & " '
(see https://wiki.selfhtml.org/wiki/XML/Regeln/Zeichen)

example:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE form [
  <!ELEMENT form (field)+>
  <!ELEMENT field (name, value+)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
]>
<form>
      <field>
      <name>Test</name>
              <value>Das ist "ein" Test mit & Sonderzeichen</value>
          </field>
  </form>
```

These characters should be replaced as HTML entities, using htmlspecialchars or similar, to ensure XML specifications.

**Comment by leofeyer** [comment]
@contao/developers The easiest solution would be to add `htmlspecialchars()` in the `form_xml.html5` template:

https://github.com/contao/contao/blob/b549e71d594c8c544af9eb148c5878759acd0080/core-bundle/src/Resources/contao/templates/forms/form_xml.html5#L13

Any objections?

**Comment by ausi** [comment]
IMO yes, same with the field name, using the flags: `ENT_QUOTES | ENT_SUBSTITUTE | ENT_XML1` and maybe with `double_encode: false`

**Comment by leofeyer** [comment]
Actually, I cannot reproduce this issue. In my test, the string was `Das ist &quot;ein&quot; Test mit &amp; Sonderzeichen` already. @lizardat How did you set up your form?

**Comment by lizardat** [comment]
Regular text field, no input validation.
Template: form_textfield (Default)

Output e.g.:
```
      <lfz_kennzeichen>
              <value>OE"&T"</value>
          </lfz_kennzeichen>
```

**Comment by leofeyer** [comment]
What exactly do you mean by "output"?

**Comment by lizardat** [comment]
The generated xml file, that is sent by mail.
