### ISSUE TITLE
/favicon.ico route and 404 error in cpanel hosts

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#6056]
### Affected version(s)

*

### Description

Hi, the `/favicon.ico` **route** doesn't work in website that hosted with _cpanel_ host manager. I checked it in many servers. I used debug mode and review the log file, and there was no sign that this "route" be triggered. I think it's a bug in cpanel http server or litespeed, and server only try to find the `favicon.ico` in the `public` folder and if doesn't find it return 404 error.

You can see the error [here](https://respinar.com/favicon.ico).

**Comment by fritzmg** [comment]
This is likely an optimisation of the hoster's (or CPanel's) web server. It has a rule that prevents requests from being processed by PHP. You/your hoster needs to adjust this.
