### ISSUE TITLE
No message factories found

### ISSUE THREAD

**Issue by chiron501** [contao/contao#6057]
### Affected version(s)

4.13.23

### Description

Hi, bei einer Neuinstallation von Contao bricht der Installer mit folgender Meldung ab:
_No message factories found. To use Guzzle, Diactoros or Slim Framework fact  
  ories install php-http/message and the chosen message implementation._

Erst wenn ich das Paket "php-http/message" auf die Version 1.15.0 in der composer.json festschreibe bekomme ich die Installation zum laufen.

Kann das jemand bestätigen?

**Comment by aschempp** [comment]
Ja, ist bekannt, wir arbeiten an einer Lösung
https://github.com/php-http/message/pull/152#issuecomment-1550923764
https://github.com/contao/conflicts/pull/45

**Comment by aschempp** [comment]
Conflict PR ist gemergt, die Installation sollte jetzt wieder klappen.

**Comment by chiron501** [comment]
mille grazie u saved my day
