### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'label' at row 1

### ISSUE THREAD

**Issue by k-webdesign** [contao/contao#6058]
### Affected version(s)

4.13

### Description

When you duplicate an HTML form field was a text field formerly it gets constantly added "(Kopie)" to the label - which isn't even used in the HTML field. Because of this I got somewhen the error
```An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'label' at row 1```

See https://community.contao.org/de/showthread.php?85175-An-exception-occurred-while-executing-a-query-SQLSTATE-22001-String-data-right-tr&p=572755#post572755

**Comment by fritzmg** [comment]
I can confirm the issue.
