### ISSUE TITLE
Backport #5083 to Contao 4.13.x

### ISSUE THREAD

**Issue by AlexanderWillner** [contao/contao#6059]
### Affected version(s)

4.13.x

### Description

Just ran into an issue in 4.13.x [here](https://github.com/contao/contao/blob/c402b3f2f887c0e98c3892a20db6db85b851d187/core-bundle/src/Resources/contao/library/Contao/Database.php#L498) that was fixed in #5083 - I assume this should be backported?

**Comment by ausi** [comment]
This should not result in an error in contao 4.13 as superflous parameters are allowed there.

How can this be reproduced?
