### ISSUE TITLE
Convention for back end icons

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6061]
### Description

Contao already creates picture elements for theme icons with a light and dark variant, however, this does not work for custom icons in extensions yet. Therefore, I‘d like to expand the `Image::getHtml()` functionality to all icons that follow a certain convention. What would you prefer?

**1. Explicit suffixes**

- `my-icon--light.svg`
- `my-icon--dark.svg`

```php
'action' => [
    'href' => 'key=action',
    // If my-icon.svg does not exist, we check for …--light.svg and …--dark.svg
    'icon' => 'bundles/vendorname/my-icon.svg',
],
```

**2. Suffix for dark icons only**

- `my-icon.svg`
- `my-icon--dark.svg`

```php
'action' => [
    'href' => 'key=action',
    // If my-icon.svg does not exist, we skip the icon (current behavior)
    'icon' => 'bundles/vendorname/my-icon.svg',
],
```

**Other possible suffixes**

- `my-icon-dark.svg`
- `my-icon.dark.svg`

@contao/developers WDYT?

**Comment by cliffparnitzky** [comment]
I prefer variant 1 because it looks more clear and understandable to me.

**Comment by Toflar** [comment]
I think I'd prefer variant 1 for a simple reason: If we should ever have to change the default (which I don't think we'll have to but 15 years ago we also did not think about a dark mode at all), we could without having to rename any icons.
