### ISSUE TITLE
Contao replaces symlink to .env.local with regular file

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#6065]
### Affected version(s)

4.13

### Description

Contao auto-generates `APP_SECRET` env variable if it is not set or has default value (added in #5951 and #5066). However, if a Contao installation was deployed by Deployer, then `.env.local` is a symlink, because it is a shared file according to [Symfony Deployer recipe](https://github.com/deployphp/deployer/blob/ed28cb1cba33747f08ea7c14d6801cdde10fab97/recipe/symfony.php#L18-L20). In that case, Contao erases the symlink and recreates `.env.local` as a regular file.

**Comment by fritzmg** [comment]
We'll need to use `realpath` for the `.env.local` (see also https://github.com/contao/contao/pull/2209).

```diff
-$dotenv = new DotenvDumper(Path::join($this->projectDir, '.env.local'), $filesystem);
+$dotenv = new DotenvDumper(realpath(Path::join($this->projectDir, '.env.local'), $filesystem));
```

**Comment by fritzmg** [comment]
I can confirm the issue. Closing in favor of #6066, #6067
