### ISSUE TITLE
Twig template not being re-compiled after a change whilst in 'dev' environment

### ISSUE THREAD

**Issue by jamesdevine** [contao/contao#6068]
### Affected version(s)

5.1

### Description

Using latest Contao 5.1, there seems to be a bug in the **isFresh** method of **src/Twig/Loader/ContaoFilesystemLoader.php**.

I am creating a custom content element, my template is located in:
`/contao/templates/content_element/my_template.html.twig`

APP_ENV is set to 'dev'. I can see the Twig Enviornment is set correctly too, both 'autoReload' and 'debug' are set to true.

The issue is that **isFresh** returns true even when I have made a change to my template. Making a change to a twig template whilst in the dev enviroment should trigger the template to be re-compiled when the frontend is refreshed.

I believe is issue is caused because the `isFresh` method is checking to see if my template is part of a theme, then when it determines that it isn't the `parent::isFresh` check is never done.

So, the template itself is never checked for freshness but the inheritance chain is.

```php
// my template is /contao/templates/content_element/my_template.html.twig

public function isFresh(string $name, int $time): bool
 {
        // $this->getThemeTemplateName($name) returns null, so this whole block is skipped
        
        if ((null !== ($themeTemplate = $this->getThemeTemplateName($name))) && !parent::isFresh($themeTemplate, $time)) {
            return false;
        }
        
        // The inheritance chain is then checked, but the template itself ($name) never is.

        $chain = $this->getInheritanceChains()[ContaoTwigUtil::getIdentifier($name)] ?? [];

        foreach (array_keys($chain) as $path) {
            $mTime = @filemtime($path);

            if (false === $mTime || $mTime > $time) {
                return false;
            }
        }

        return true;
}
```

I think the solution is to check `parent::isFresh($name, $time)` before the chain is checked. This fixes it for me, I will submit a PR.

**Comment by leofeyer** [comment]
@m-vo /cc

**Comment by m-vo** [comment]
> The issue is that isFresh returns true even when I have made a change to my template. Making a change to a twig template whilst in the dev enviroment should trigger the template to be re-compiled when the frontend is refreshed.

The logic for the `isFresh` check currently works like this:

* If the template name is a theme template, check if it is fresh instead. If not, return `false`, else continue.
* Go through all representations for the identifier (the template hierarchy): If any file is younger than the current timestamp, return `false`, else continue.
* Return `true`. 

Which point is wrong in your opinion? Could you maybe clarify your test case or add some steps how to reproduce this in a fresh installation?

**Comment by jamesdevine** [comment]
To try and clarify what I think the issue is:

When working with a custom Twig template that is not part of a theme, the frontend continues to incorrectly display the cached version of the template even once edits have been made to the template source code. When you edit the template, you should be able to refresh the page and see the changes.

To reproduce it in a fresh install:

1. Set APP_ENV to 'dev'.

2. Create a custom content element that uses a Twig template. For example:

```php
// /src/Controller/ContentElement/CustomElementController.php
namespace App\Controller\ContentElement;

use Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController;
use Contao\CoreBundle\DependencyInjection\Attribute\AsContentElement;
use Contao\ContentModel;
use Contao\CoreBundle\Twig\FragmentTemplate;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

#[AsContentElement('my_custom_element', category:'text')]
class CustomElementController extends AbstractContentElementController
{ 
    protected function getResponse(FragmentTemplate $template, ContentModel $model, Request $request): Response
    {
        return $template->getResponse();
    }
}
```

3. Place a custom Twig template for the element in `/contao/templates/content_element/my_custom_element.html.twig` with some dummy content. So this is a non-theme template.

4. In the CMS, set up the content element to display in a frontend page so you can view the output.

5. Make an edit to the custom twig template, then refresh the frontend.

The behaviour i'd be expecting is that upon refreshing the page, any edits I have made to the template source code are reflected in the frontend. However, this currently doesn't happen. Even having changed the template's source code, the cached version is still output and the only way to get the frontend to update is by clearing the cache (or deleting the twig cache dir).

**Comment by m-vo** [comment]
Your scenario works just fine for me. Did you maybe miss creating a `.twig-root` file in `contao/templates` and seeing some other/old results?

**Comment by jamesdevine** [comment]
Yep, looks like this was infact a case of user error. Adding `.twig-root` to `contao/templates` does make this work as expected.
