### ISSUE TITLE
Sicherheitsfrage deaktivieren im Modultyp Registrierung entfernen

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#607]
4.8

Im Modultyp «Registrierung» wird in der 4.8 dem Formular der Honeypot hinzugefügt. Deshalb würde ich für diese Version die Einstellung «Sicherheitsfrage deaktivieren» entfernen.

**Comment by aschempp** [comment]
Wenn die Checkbox aktiv ist, wird der Honeypot aber nicht ausgegeben, oder? Die Sicherheitsfrage ist durch den Honeypot ja nicht weg, sie erscheint weiterhin bei falscher Honeypot-Eingabe.

**Comment by ausi** [comment]
Ich wäre dafür die „Sicherheitsfrage deaktivieren“ Checkbox zu behalten. Zum einen ist sie ein Hinweis darauf, dass überhaupt eine Sicherheitsfrage angezeigt werden kann und zum anderen kann es sinnvoll sein sie zu deaktivieren wenn man einen anderen Mechanismus zur Spam-Bekämpfung nutzt.
