### ISSUE TITLE
Invalid insert tag throws exception

### ISSUE THREAD

**Issue by aschempp** [contao/contao#6072]
### Affected version(s)

5.1

### Description

I added an invalid insert tag to my Twig template and got the follwing exception:

```
An exception has been thrown during the rendering of a template ("Rendering a single insert tag has to return a single raw chunk") in "@Contao_ContaoCoreBundle/fe_page.html5".
```

Didn't we recently change insert tags to persist if the insert tag is invalid?

/cc @m-vo

**Comment by ausi** [comment]
@aschempp how does the invalid insert-tag look like?

**Comment by ausi** [comment]
Does `->get('contao.insert_tag.parser')->render('…')` result in the same exception?

**Comment by aschempp** [comment]
I think all I did was add an invalid insert tag directly in my Twig template.

**Comment by ausi** [comment]
I was not able to reproduce that issue. 
I tried `{{ '{{invalid}}'|insert_tag }}` and `{{ insert_tag('invalid') }}` inside a Twig template. 
Both resulted in the output `{{invalid}}` as expected.

**Comment by aschempp** [comment]
Let's close this then, since I already fixed this in my project and can't find the source anymore 😇
