### ISSUE TITLE
`PageModel::getFrontendUrl` generates only scheme relative URLs

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6081]
### Affected version(s)

4.13, 5.1, 5.x

### Description

`PageModel::getFrontendUrl` is supposed to return an absolute URL if the page for which the URL is generated is on a different domain than the current domain. However, it only generates a _scheme relative_ URL currently. i.e., if you are currently on `https://example.com` and an URL is generated for a page that is within a website root with the domain `foobar.com`, the resulting URL will be

```
//foobar.com/page
```

This will break canonical URLs for example. Instead of

```html
<link rel="canonical" href="https://foobar.com/page">
```

it will be

```html
<link rel="canonical" href="https://example.com///foobar.local/page">
```

when you set the canonical URL of a page via the picker.

By comparison `PageModel::getFrontendUrl`  in Contao 4.9 generates an absolute URL (including the scheme) as expected if the target page is on a different domain.

### Reproduction 1

1. Create a second website root with a different domain.
2. Create a page within that website root with the alias `page`.
3. In your first website root create a text (or HTML) content element with the content `{{link_url::*}}` (replace `*` with the ID of the page within the other website root.

The generated URL will be `//foobar.com/page` instead of `https://foobar.com/page`.

### Reproduction 2

1. Create a second website root with a different domain.
2. Create a page within that website root with the alias `page`.
3. In your first website root edit the setting of a page.
5. Under _Canonical URL_ » **Custom URL** click the picker.
6. In the page picker, select the previously generated page of the other website root.
7. Visit the page in your first website root in the front end.

The generated canonical tag will be invalid.

**Comment by ausi** [comment]
IMO we should not use _scheme relative_ URLs at all, but absolute URLs instead.
But we should additionally also add support for these types of URLs for the canonical URL.
