### ISSUE TITLE
Missing APP_SECRET redirects Install-Tool to wrong URL

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#6088]
### Affected version(s)

4.13.24 (maybe even lower)

### Description

One of the latest changes was to automatically generate `.env` and `.env.local` files during installation. The latter includes an `APP_SECRET`. Because we don't usually work with env-files and the `APP_SECRET` will be written to the `parameters.yml` by the Install-Tool anyway, we delete those env-files, but this leads to an unexpected behaviour:

1. Setup a fresh installtion
2. Delete both `.env` files
3. Try to access `https://projectname.local/contao/install`
4. You'll automatically be redirected to `https://localhost/contao/install`

Maybe also see https://contao.slack.com/archives/CK4J0KNDB/p1685429606604379

**Comment by fritzmg** [comment]
I cannot reproduce the issue. Deleting the `.env*` files does not create a redirect to `localhost`.

However, we should probably disable the secret check for the `/contao/install` route for this edge case.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6090 and https://github.com/contao/contao/pull/6121
