### ISSUE TITLE
Metadata is null on FileMetadataEvent when using legacy addImageToTemplate() without FilesModel

### ISSUE THREAD

**Issue by oexler** [contao/contao#6094]
### Affected version(s)

4.13.24

### Description

We use the legacy `Contao\Controller::addImageToTemplate()` method with a singleSRC and no FilesModel.
Since 4.13.24 (https://github.com/contao/contao/pull/6064) `FigureBuilder->onDefineMetadata()` returns null, so the `FileMetadataEvent` has no metadata set.

In our `FileMetadataEvent` we have no information about the file that we could use as $fileMetadataEvent is empty.

A workaround from our side is to use overwriteMeta and a FilesModel for addImageToTemplate, but we don't know if Contao should behave this way, because it worked before.

**Comment by leofeyer** [comment]
Can this be reproduced in a fresh Contao 4.13 installation with the official demo?

**Comment by oexler** [comment]
I haven't tested it, but I see no way it should work there, as onDefineMetadata() returns null in [FigureBuilder.php#L655](https://github.com/contao/contao/blame/e7f39bcfb540341a4d96d2726110cea6ffcf2174/core-bundle/src/Image/Studio/FigureBuilder.php#L655). 
In Version 4.13.23 $this->metadata was set, so it  
returned $this->metadata->with($fileReferenceData); in [#L652](https://github.com/contao/contao/blame/e7f39bcfb540341a4d96d2726110cea6ffcf2174/core-bundle/src/Image/Studio/FigureBuilder.php#LL652)
But now $this->overwriteMetadata is set instead of $this->metadata.
The code that handles overwriteMetadata is only executed, when $this->filesModel is not null.
