### ISSUE TITLE
User Agent Abfrage iOS Chrome 69

### ISSUE THREAD

**Issue by operatorone** [contao/contao#61]
**Affected version(s)**
Contao 4.4.20

**Description**  
Bei Chrome auf iOS wird durch das Inserttag UA::CLASS für den Chrome 69 folgendes ausgegeben: **ios safari webkit sfMozilla/5**

Somit kann dieser Browser nicht spezifisch abgefragt werden, um Codeanpassungen zielgerichtet abzusetzen.

**How to reproduce**  
Aufruf jeder beliegen Website. Im fe_page.html5 {{ua::class}} irgendwo im Content platzieren.

**Comment by leofeyer** [comment]
Wie lautet denn der User-Agent-String in Chrome 69 auf iOS bei Dir?

**Comment by operatorone** [comment]
Leider kann ich den auf dem iPad nicht sichtbar machen in dem ich in den Quellcode schaue, weil das auf iOS-Geräten leider nicht geht. Ich habe dann per ua::class einfach mal abgefragt und da kam dann "ios safari webkit sfMozilla/5"

**Comment by fritzmg** [comment]
> Leider kann ich den auf dem iPad nicht sichtbar machen in dem ich in den Quellcode schaue

Du sollst ja nicht den Quellcode zeigen, sondern den User-Agent-String ;). Gehe einfach mit dem Chrome 69 auf deinem iPad zB [hier](https://www.whoishostingthis.com/tools/user-agent/) hin und kopiere das was unter **Your User Agent is:** steht hier ins das Ticket.

**Comment by leofeyer** [comment]
Behoben in 0c4ea3c3b493435b4e60601eab8007e0e8e8faaf.

**Comment by operatorone** [comment]
Unter whatismybrowser.com bekomme ich folgende Ausgabe: Mozilla/5.0 (iPad; CPU OS 10_3_3 like MacOSX AppleWebKit/603.1.30 (KHMTL. like Gecko) CriOS/69.0.3497.91 Mobile/14G60 Safari/602.1

**Comment by operatorone** [comment]
Super, danke für den schnellen Fix.
