### ISSUE TITLE
Saving eval 'multiple'=> true in DC_FILE driver throws an error

### ISSUE THREAD

**Issue by zoglo** [contao/contao#6105]
### Affected version(s)

5.1.7

### Description

**Error thrown:**
```
strlen(): Argument #1 ($string) must be of type string, array given
```

**Description:**
Previously (Contao 4.13), you were able to save an inputType text with eval ```'multiple'=>true``` in a DC_FILE datacontainer due to the serialized string being converted back using following code:
- https://github.com/contao/core-bundle/blob/870e51346567bffeb388012a104e6bf39e514b15/contao/drivers/DC_File.php#L424

In the current version of Contao 5.1.6, this has been removed in this commit:
- https://github.com/contao/contao/pull/4453/files
- https://github.com/contao/core-bundle/blob/870e51346567bffeb388012a104e6bf39e514b15/contao/drivers/DC_File.php#L390

Without the following code, varValue will actually be parsed as an array and throw an error when $varValue is being checked for it's strlen:
https://github.com/contao/core-bundle/blob/870e51346567bffeb388012a104e6bf39e514b15/contao/drivers/DC_File.php#L424.

```
if (!\is_array($varValue))
{
    $varValue = StringUtil::restoreBasicEntities($varValue);
}
else
{
    $varValue = serialize(array_map('\Contao\StringUtil::restoreBasicEntities', $varValue));
}
```

**Comment by fritzmg** [comment]
@ausi this was removed in https://github.com/contao/contao/pull/4453

The side effect that the value now is always deserialized but never serialized is likely unintended. I think we can remove

https://github.com/contao/contao/blob/eddd135c9e7e80e3ae61831d201882071ec4575c/core-bundle/contao/drivers/DC_File.php#L387-L391

completely?

**Comment by ausi** [comment]
> I think we can remove … completely?

Agree. Seems to be a mistake that these lines were not removed in #4453 too.
