### ISSUE TITLE
json-ld for calendar items is missing some tags

### ISSUE THREAD

**Issue by ronnybremer** [contao/contao#6129]
### Affected version(s)

4.13

### Description

I have been diving a little bit deeper into JSON-LD for calendar items and discovered, that Google search is complaining (at the moment as a warning) about the following missing tags:

- endDate
- organizer
- performer
- eventAttendanceMode

According to the code base [https://github.com/contao/contao/blob/4.13/calendar-bundle/src/Resources/contao/classes/Events.php#L487](Events.php) those tags are not produced.

Would it be possible to include them if set at the event? Especially endDate seems to be quite important, to indicate, how long the event will take place.

**Comment by fritzmg** [comment]
@ronnybremer you can adjust the JSON-LD data to your liking within your `event_*` template.

> * endDate

An `endDate` can only be provided, if you set an end date/time for your event. This is something we could do by default in Contao, yes.

> * organizer
> * performer
> * eventAttendanceMode

Contao events do not have an "organizer", "performer" or an "eventAttendanceMode". You would need to implement this yourself in your application.

**Comment by ronnybremer** [comment]
> you can adjust the JSON-LD data to your liking within your `event_*` template.

Thank you Fritz for that suggestion, I wasn't aware you could alter the array of the json-ld data before its being rendered but I figured out a way to do it.

The endDate would be great to be done automatically, as it is quite an important aspect of an event with a fixed time period.
