### ISSUE TITLE
New eventsListFetchItems Hook

### ISSUE THREAD

**Issue by christianbarkowsky** [contao/contao#614]
**Description**  
An eventsListFetchItems hook would be great - similar to the News.

**Example**  

* eventsListFetchItems

**Comment by fritzmg** [comment]
There is already the `getAllEvents` hook, which should be suitable for any case. Events work differently than news because all the events always have to be loaded and generated.

**Comment by christianbarkowsky** [comment]
I know the Hook and know how it works. But the News solution is more sexy.

**Comment by leofeyer** [comment]
Where exactly would you put the hook?
