### ISSUE TITLE
Add Import/Export feature for »user groups (permissions)«

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#6143]
### Description

It would be helpful to be able to easily export & import »user groups« with the appropriate permissions in the backend (instead of having to manually transfer the »tl_user_group«").

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/contao/issues/402 (and https://github.com/contao/contao/issues/5386) imho.

**Comment by fkaminski** [comment]
Agree: Closed in favor of #402 (and #5386).
