### ISSUE TITLE
`multiSRC` should not always be mandatory in `downloads`

### ISSUE THREAD

**Issue by MarkejN** [contao/contao#6155]
### Affected version(s)

4.13.22

### Description

In https://github.com/contao/contao/pull/5984 the `multiSRC` field in `downloads` became mandatory. But if I use the `useHomeDir` option and show the `downloads` element only to members, then I should not have to specify a directory, right?

**Comment by leofeyer** [comment]
You are absolutely right.

**Comment by cliffparnitzky** [comment]
Same for the `gallery` element.

**Comment by fritzmg** [comment]
Yeah, #5984 needs to be reverted as a whole.

**Comment by cliffparnitzky** [comment]
Or we add a load callback to set/remove the mandatory marker.

**Comment by fritzmg** [comment]
But there would be no content element that requires it to be mandatory.

**Comment by cliffparnitzky** [comment]
I mean more like this: if the `useHomeDir` is clicked, the mandatory marker at `multiSRC` is removed, and vice versa.

**Comment by fritzmg** [comment]
I don't think Contao supports that.

**Comment by cliffparnitzky** [comment]
It is only a `submitOnChange` at the `useHomeDir` field and a simple change in the `setMultiSrcFlags` load callback. It will look like this:
https://github.com/contao/contao/assets/1247552/7beb808f-b1d6-4358-986a-f403691fa9f0

I will create a PR.

**Comment by fritzmg** [comment]
Ah yes, `useHomeDir` is not a subpalette `__selector__`.
