### ISSUE TITLE
Warning when editing usergroups in debug mode (PHP 8.1)

### ISSUE THREAD

**Issue by n00ybfied** [contao/contao#6166]
### Affected version(s)

4.13.24

### Description

I'm getting a Warning when I try to edit usergroups in debug mode (PHP 8.1). I think this is a bug.

![image](https://github.com/contao/contao/assets/74267678/bb72e6a9-fedd-435b-bfec-50f958d97314)

**Stack Trace:**

ErrorException:
Warning: Undefined array key "fields"

  at vendor/contao/core-bundle/src/Resources/contao/dca/tl_user_group.php:434
  at tl_user_group->getExcludedFields()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:1327)
  at Contao\Widget::getAttributesFromDca()
     (vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:433)
  at Contao\DataContainer->row()
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:1979)
  at Contao\DC_Table->edit()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:667)
  at Contao\Backend->getBackendModule()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:44)

**Comment by fritzmg** [comment]
It looks like you have a DCA in your Contao instance without any fields. Add a `dump($k)` before line 434 in order to find out which one it is.

Generally speaking I am not sure if a DCA without any fields whatsoever is really a supported use-case.

**Comment by n00ybfied** [comment]
Ok, thank you. I'll take a look.

**Comment by n00ybfied** [comment]
Strange, can't really get my head around it. I did this:
![image](https://github.com/contao/contao/assets/74267678/1bf1fd99-6b71-4829-a2a0-48c33d02d68a)

and get this:

![image](https://github.com/contao/contao/assets/74267678/b63741ac-4fe2-44f0-85d4-e18f762039ab)

How can is_array($v['fields'] trigger a warning? I'm pretty sure that is an array. ^^

**Comment by ausi** [comment]
move the `exit;` after the whole foreach block, then you should see it.

**Comment by n00ybfied** [comment]
Sorry, bullshit. 
It was an issue with the old "Seminarverwaltung" Extension. I was able to fix it. There is no bug whatsoever. ^^
thx for helping
