### ISSUE TITLE
Custom console breaks deployer

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#617]
**Affected version(s)**

4.8.0-RC2

**Description**  

The changes from #602 break Deployer and any other script that passes the `--no-debug` flag to <del>Composer</del> the console. So instead of unsetting the option, we should only ignore it.

**Comment by aschempp** [comment]
We already do ignore the `--no-debug` flag anyway, the intent was to just remove it from the options list. But how is that related to Composer?

**Comment by leofeyer** [comment]
I meant "the console" of course. Silly me. 😄

**Comment by aschempp** [comment]
I just looked at my own recipe, and it looks like the `--no-debug` statement is added there. Maybe thats the same for you, and you should just change your `deploy.php`

```
set('console_options', '--no-interaction --env={{symfony_env}}');
```

**Comment by leofeyer** [comment]
I have removed the custom application class in 2d253fbff95172890bed579c5ab2886b1ca5ac41. The custom title and version number are still set.

**Comment by aschempp** [comment]
Sorry but I don't think that's the right solution. The `--no-debug` option does not exist on the console, so it must not show up in the description. We can still ignore it if thats reeealy a problem…

**Comment by leofeyer** [comment]
It obviously is a problem (see above).

**Comment by leofeyer** [comment]
See #626.
