### ISSUE TITLE
Wrong assigned variable

### ISSUE THREAD

**Issue by Olli** [contao/contao#6174]
### Affected version(s)

5.1

### Description
https://github.com/contao/contao/blob/050a082e300283afb6bdf741638dd7dff8939076/core-bundle/src/Controller/ContentElement/HyperlinkController.php#L45C54-L45C54 

"titleText" should be assigned to the title attribute.

**Comment by fritzmg** [comment]
For anyone wondering: the variable naming for the hyperlink fields in `tl_content` is a little confusing, vermutlich historisch bedingt. This is how it needs to be:

```html
<a href="…" title="<!-- tl_content.titleText -->"><!-- tl_content.linkTitle --></a>
```

"linkTitle" refers to the "title of the link" i.e. its inner text and _not_ the `title` attribute.
