### ISSUE TITLE
FAQ JSON-LD for several frontend-modules on same page only add data for the last archive

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#6176]
### Affected version(s)

4.13

### Description

**How to reproduce:**

1. Create 2 FAQ archives (_Archive A_ and _Archive B_)
2. create 2 FAQ Page-Modules (question and answer on same page) 
3. add these two modules on the same page

**Result:**
Only JSON-LD for _Archive B_ (the latter one) is added to the page.

**Expected Result:**
JSON-LD shows data for both archives on the page.

**Comment by leofeyer** [comment]
It seems that using `"@type": "FAQPage"` is already wrong, because it is a more specific replacement for `"@type": "WebPage"` and not a wrapper for questions and answers. We should fix that as well when fixing this issue.

**Comment by Toflar** [comment]
No it's a wrapper for questions and answers, also see https://developers.google.com/search/docs/appearance/structured-data/faqpage

**Comment by leofeyer** [comment]
No, it is not. And your link says that, too:

<img width="601" alt="" src="https://github.com/contao/contao/assets/1192057/95c4c54d-adfd-4e3b-afde-23270bae1785">


Using `"@type": "FAQPage"` **instead of** `"@type": "WebPage"` is correct. ✅ 

But we do this:

```
"@context": "https:\/\/schema.org",
"@graph": [
{
    "@type": "WebPage"
},
{
    "@type": "ImageObject",
    …
},
{
    "@type": "BreadcrumbList",
    …
},
{
    "@type": "FAQPage",
    …
},
```

And that is clearly wrong. And if we would add more than one FAQ archive, we would end up with several `"@type": "FAQPage"` blocks, which would be even more wrong.

**Comment by Toflar** [comment]
I was referring to the "wrapper for questions and answers" - which it is exactly 😊 But yes, it should replace `WebPage` probably.

**Comment by leofeyer** [comment]
As discussed in the call, there are two things that need to be fixed:

1. We have to allow adding multiple `"@type": "Question"` elements, so we can add all the FAQs.
2. In a future version, we could allow overwriting `"@type": "WebPage"` with `"@type": "FaqPage"` in the FAQ reader module.

**Comment by Toflar** [comment]
https://github.com/contao/contao/pull/6333 should fix the problem.

> In a future version, we could allow overwriting "@type": "WebPage" with "@type": "FaqPage" in the FAQ reader module.

As discussed during Contao Call: It's totally valid to have multiple `@types` so we can ignore this :)
