### ISSUE TITLE
Page Type "External Redirect" doesn't return correct url in folder like alias

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#6179]
### Affected version(s)

4.13

### Description

Hi,

I want to have a page with folder like alias such as "https://example.com/folder/page" redirected to another page like "https://example.com/news/news1".

So I create a new Page with type "External Redirect" with folder like alias "folder/page". Then select a "Link target" in "Page Picker" such as "{{news_url:1}}".

What we expect is:
https://example.com/folder/page  => https://example.com/news/news1

but this happens: 
https://example.com/folder/page => https://example.com/folder/news/news1

**Comment by ausi** [comment]
Can probably be fixed by wrapping https://github.com/contao/contao/blob/27f0144d05b2acffed7f493ca929d9a6649495c2/core-bundle/src/Resources/contao/pages/PageRedirect.php#L48 with something like this:

```php
UrlUtil::makeAbsolute(…, Environment::get('path'))
```

**Comment by fritzmg** [comment]
Related: https://github.com/contao/contao/pull/3468
Never got around to continue working on it unfortunately.
