### ISSUE TITLE
Incorrect pid of nested subfiles when copying a folder

### ISSUE THREAD

**Issue by qzminski** [contao/contao#6186]
### Affected version(s)

4.13

### Description

I am building a frontend file browser that uses Contao's DBAFS. The current position in a file tree is determined by the UUID in the URL. This is basically how I found out there's something wrong with the DBAFS. Now, on to the details.

When copying a folder that contains subfolders, the files inside the subfolder will have a wrong `pid` in the database. Let's take a look at the official Contao demo files as an example. If I copy the `theme` folder and place it somewhere else, it will copy all the subfolders and files inside it – that's correct. All of those children will also get a new `pid` value, which will be the same as the new folder's UUID. But here's the catch: this new `pid` value is correct for the subfiles on the first level, but it's not for the subfiles on deeper levels. See the image below:

![CleanShot 2023-07-03 at 13 32 04](https://github.com/contao/contao/assets/193483/2eeeb2d4-12d4-432d-9784-16277f3a8847)

I did a dump [below this line](https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/library/Contao/Dbafs.php#L373) that prints out the UUID and its new path. Here is the result:

<img width="831" alt="CleanShot 2023-07-03 at 13 39 30" src="https://github.com/contao/contao/assets/193483/4fda1f45-ccc9-4e58-b910-ddeeb9bac923">

As you can see, the `pid` remains the same for all the files which is incorrect. It should get the `pid` of its direct parent folder model. The faulty line is exactly here:

https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/library/Contao/Dbafs.php#L369

Would you like me to provide a pull request?

**Comment by Toflar** [comment]
You might want to build your new extension on top of the VFS which uses a completely revamped DBAFS implementation (https://docs.contao.org/dev/framework/filesystem/virtual-filesystem/). It should all be handled transparently, so you shouldn't even need to fiddle around with the DBAFS classes at all.

/cc @m-vo the bug should still be fixed here - agree with @qzminski's proposal?

**Comment by leofeyer** [comment]
I think @qzminski is right. 👍

**Comment by m-vo** [comment]
Yes, agree to all of you. 😊
