### ISSUE TITLE
Fully support newsletter templates

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6193]
### Description

I want to make using more complex newsletter templates such as [this](https://github.com/rodriguezcommaj/salted/blob/master/salted-responsive-email-template.html), [this](https://github.com/leemunroe/responsive-html-email-template/blob/master/email.html) or [this](https://github.com/konsav/email-templates/blob/master/general.html) more convenient. To accomplish that, we have to convert the CSS code to inline styles when rendering the template. Luckily, there is a library already:

https://github.com/tijsverkoyen/CssToInlineStyles

So ideally, the process would be something like this:

1. You copy one of the templates above into a `mail_custom.html5` template.
2. You add the `<?= $this->body ?>` placeholder and the CSS definitions to format the content.
3. When you send the newsletter, the template is parsed and fed through the `CssToInlineStyles` class.

The mail should then be compatible with most mail clients and can use modern layouts with e.g. two columns or alike.

**Comment by aschempp** [comment]
why would that not already work if you adjust the `mail_default` etc. templates accordingly?

**Comment by leofeyer** [comment]
Because the inline styles need to be applied to the mail body (aka the RTE output) as well.
