### ISSUE TITLE
Not Show Events without source

### ISSUE THREAD

**Issue by katgirl** [contao/contao#62]
**Affected version(s)**
4.6.X

**Description**  

ModuleEventReader must be ``  $objEvent->source != 'default' `` it is not requierd in dca.
I have many Events without ``source``

**How to reproduce**  
Create a new Event with Title and Date and Save it. Now you can't see in Frontend.

**Comment by fritzmg** [comment]
I am not sure what you mean. Why do you have many events without any source (is that what you are saying?)? I cannot reproduce your issue.

**Comment by katgirl** [comment]
the field are not required. My editors have therefore never filled the field.
Now after update of events -> see https://github.com/contao/calendar-bundle/issues/33 the field must be a mandatory field for the events to be displayed.

https://github.com/contao/calendar-bundle/blob/master/src/Resources/contao/modules/ModuleEventReader.php#L95-L99

**Comment by fritzmg** [comment]
The field does not need to be mandatory, since it has a default and no empty option. Also https://github.com/contao/calendar-bundle/issues/33 does not seem to be related?

However I am assuming you have disabled this field for your editors?
