### ISSUE TITLE
Review the `tl_image_size.preserveMetadata` default

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6205]
### Affected version(s)

5.2.0-RC2

### Description

By default, `tl_image_size.preserveMetadata` is set to `true` but `tl_image_size.metadata` is empty. I think we should not enable it by default and make `metadata` mandatory, so this kind of misconfiguration is prevented. @ausi WDYT?

**Comment by ausi** [comment]
If `tl_image_size.metadata` is empty, the default from the container configuration `contao.image.preserve_metadata` is used, this is also mentioned in the help text: https://github.com/contao/contao/blob/e0c479fd92e42f21cbb223d9d68fe80ce2193ba4/core-bundle/contao/languages/en/tl_image_size.xlf#L72

So I think this is correct as it currently is, or do you think this is too confusing?

**Comment by leofeyer** [comment]
It apparently confused me. 😄 But now that I know, I don‘t find it too confusing.

**Comment by leofeyer** [comment]
I think we could improve this as follows:

1. Always preserve copyright-related image metadata fields. Do not provide an option not to.

2. Convert `tl_image_size.preserveMetadata` to `tl_image_size.overwriteMetadata` and only show the checkbox menu if it is enabled:

<img width="679" alt="" src="https://github.com/contao/contao/assets/1192057/85ab4aa6-d047-4be8-91ec-6070c0321e0e">

<img width="716" alt="" src="https://github.com/contao/contao/assets/1192057/b86be356-c384-416e-a80d-e25d493c8aed">

WDYT?

**Comment by ausi** [comment]
> 1. lways preserve copyright-related image metadata fields. Do not provide an option not to.

~~I’m not sure about that. I might want to optimize the file size as much as possible by ignoring all meta data. If we do not have this option the only way to remove the copyright metadata would be to configure `contao.image.preserve_metadata` to an empty array for the whole application.~~ That’s probably fine though for most cases, and the edge case can change the config.

**Comment by ausi** [comment]
As discussed today in the call, we want to use radio buttons with three states:

- use the default
- overwrite metadata fields
- delete all metadata

and only the state “overwrite metadata fields” shows the checkbox wizard.
