### ISSUE TITLE
StringUtil::insertTagToSrc broken with form simple tokens

### ISSUE THREAD

**Issue by georgmu** [contao/contao#6209]
### Affected version(s)

4.13.26

### Description

I  have an HTML template with the following content:
```
<a href="{{env::url|urlattr}}/{{file::##form_file_id##|urlattr}}">Download-Link</a>
```

The `{{file::` gets stripped from HTML when editing the HTML the next time:
```
<a href="{{env::url|urlattr}}/##form_file_id##">Download-Link</a>
```

This is similar to #3430.

A small work-around I am using is to add `#` to the pattern in `insertTagToSrc` similar to #3455, but I am unsure if this kind of pattern change is too broad.

The better option might be to check if the path (`$paths[$i+4]`) is a simple token (by checking for `^##.*##$` or similar.)

**Comment by ausi** [comment]
I was not able to reproduce this.

How exactly did you edit the HTML template?
Do you have any extensions installed?
Can you provide a screencast video that shows the issue?

**Comment by georgmu** [comment]
I am using the Notification Center plugin ( terminal42/notification_center  1.7.2) and use the simple token in an email returned to the one filling out a form.

I will record a screencast.

**Comment by georgmu** [comment]
[Screencast showing the issue](https://github.com/contao/contao/assets/3717634/728643b7-3acf-4796-a353-87a297b68a40)

At 00:18, I create a URL with an insert tag referencing a simple token.
At 00:25, the URL is fine and as expected.
At 00:33, after saving, the insert tag is stripped, only the simple token is left.

**Comment by georgmu** [comment]
The following patch solves it for me and is not so broad as my suggestion with the '#' in the regex pattern:

```
--- a/vendor/contao/core-bundle/src/Resources/contao/library/Contao/StringUtil.php
+++ b/vendor/contao/core-bundle/src/Resources/contao/library/Contao/StringUtil.php
@@ -728,6 +728,12 @@ class StringUtil
                                continue;
                        }
 
+                       /* do not try to replace simple tokens */
+                       if (substr($paths[$i+4], 0, 2) === '##' && substr($paths[$i+4], -2) === "##") {
+                               $return .= $paths[$i+1];
+                               continue;
+                       }
+
                        $file = FilesModel::findByUuid($paths[$i+4]);
 
                        if ($file !== null)
```
