### ISSUE TITLE
Run CI for Windows again

### ISSUE THREAD

**Issue by ausi** [contao/contao#6212]
### Affected version(s)

4.13

### Description

Since https://github.com/contao/contao/pull/5866 we no longer run our test suite on windows for PRs.
Now windows is only tested twice a week via a scheduled workflow and only the 5.x branch (4.13 and 5.1 get no loger tested anymore).

I think we should bring back the windows tests. 
They seem to take less than 2 minutes, so the duration is not a problem anymore I think?

**Comment by leofeyer** [comment]
The duration was the main reason why the tests have been removed. 😄
