### ISSUE TITLE
Backend favorites don't work

### ISSUE THREAD

**Issue by sietsevandreven** [contao/contao#6213]
### Affected version(s)

5.1.9

### Description

When I open a page (e.g. themes), add it as a favorite, type a name for it and save I encounter the following error:

_Contao\CoreBundle\EventListener\Menu\BackendFavoritesListener::buildTree(): Argument #6 ($pid) must be of type int, string given, called in /home/jazzfilmfestival/public_html/vendor/contao/core-bundle/src/EventListener/Menu/BackendFavoritesListener.php on line 177_

This, or a similar one, issue was already present in 5.1.8.

**Comment by cliffparnitzky** [comment]
Cannot confirm. Any extensions installed, that causes the error?

**Comment by fritzmg** [comment]
Could happen depending on the database driver. Although PDO should return PHP integers for database integers (like tl_favorites.id in this case) under PHP 8+. Do we even support other drivers currently? 🤔 

In any case we just need to cast to `int` in line 177 (`(int) $node['id']`).

**Comment by leofeyer** [comment]
> In any case we just need to cast to `int` in line 177 (`(int) $node['id']`).

No, we should investigate why the property is a string instead of an ID. If this really turns out to be a DB problem, it might affect the whole system and not just this one file.

**Comment by fritzmg** [comment]
@leofeyer the values returned from the database are only integers if you use PDO under PHP 8.1+. If you still use MySQLi, then the values will be strings. See also https://github.com/contao/contao/pull/4797
