### ISSUE TITLE
XSS Protection header

### ISSUE THREAD

**Issue by de-es** [contao/contao#6214]
### Description

Der Header `X-Xss-Protection = 1`  scheint heutzutage mehr Schaden als Nutzen zu haben. Daher die Empfehlung, ihn explizit auf `0` zu setzen.

Referenzen:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
- https://docs.google.com/document/d/1z359JwmvFmcPZ50x50G4IuUSEASg9yTtzIbYemsKgdw (hardenize.com)

Falls ihr zustimmt, erstelle ich gerne einen PR für die zugehörige Nelmio-Konfiguration.

**Comment by ausi** [comment]
Ich bin mir nicht ganz sicher ob das nötig ist.

Der einzige für uns relevante Browser der auf diesen Header noch reagiert scheint Safari bis Version 15.3 zu sein. Somit sind vermutlich nur ca. 1% der Besucher betroffen.

**Comment by bezin** [comment]
Zumindest in der Managed Edition wird außerdem [standardmäßig der Block Mode aktiviert](https://github.com/contao/contao/blob/e0c479fd92e42f21cbb223d9d68fe80ce2193ba4/manager-bundle/skeleton/config/config.yaml#L135C25-L135C25), was auf [einer der beiden verlinkten Seiten ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection)auch empfohlen wird:
> Setting the X-XSS-Protection header to either 0 or 1; mode=block prevents vulnerabilities like the one described above. [...]

Per default ist der Header daher `X-Xss-Protection = 1; mode=block` und nicht `X-Xss-Protection = 1`

**Comment by de-es** [comment]
Den Mode hatte ich jetzt mal hinten runterfallen lassen, da er ja bei `0` keine Relevanz mehr gehabt hätte.

@ausi Schlägst du implizit vor, ihn ganz zu entfernen? Ginge auch.

**Comment by ausi** [comment]
> Schlägst du implizit vor, ihn ganz zu entfernen?

Ja, falls wir aktuell tatsächlich `X-Xss-Protection: 1` schicken, sollten wir das auf jeden fall ändern. 
Ich wäre für ganz entfernen, aber `0` oder `1; mode=block` wäre auch OK für mich.

**Comment by de-es** [comment]
Aktuell schicken wir, wie @bezin richtigerweise anmerkt, `X-Xss-Protection = 1; mode=block`. `0` wäre mein Vorschlag, ganz entfernen finde ich auch OK.

**Comment by ausi** [comment]
Dein Hinweis _„…scheint heutzutage mehr Schaden als Nutzen zu haben.“_ bezieht sich denke ich nur auf `X-Xss-Protection: 1` (ohne `mode=block`) nachdem wir aber korrekterweise `1; mode=block` verwenden würde ich es wohl dabei belassen.
Und nach ein paar Jahren dann ganz entfernen wenn Safari 15 keine Verbreitung mehr hat.
