### ISSUE TITLE
Cannot preview unpublished children of internal redirect page

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6216]
### Affected version(s)

4.13.x

### Description

Consider the following example:

<img src="https://github.com/contao/contao/assets/4970961/21dd1a58-b4ae-481b-b301-f37035864191" width="220">

"Redirect to Sibling" is a page of type "Internal redirect" with the **Redirect page** set to the page "Sibling". "Unpublished child of redirect" is a regular, but unpublished page as a child of "Reidrect to Sibling".

These are their aliases:

* `redirect-to-sibling`
* `redirect-to-sibling/unpublished-child-of-redirect`
* `sibling`

Now, if you click on the preview link for "Unpublished child of redirect" you will eventually land on the following URL after some redirects:

```
https://c413.local/preview.php/sibling/unpublished-child-of-redirect
```

This URL does not exist.

The reason is probably that, since the "Unpublished child of redirect" page is unpublished, the `unpublished-child-of-redirect` part of its URL is treated as a parameter for the page `redirect-to-sibling` and thus `redirect-to-sibling` is actually being previewed. And since `redirect-to-sibling` is a redirect to `sibling` it automatically redirects to `sibling` + the `unpublished-child-of-redirect` as a parameter.

To work around this, you need to first open the preview anywhere, then set "Unpublished" to "show" and apply, then the preview link in the back end works as expected.

Not sure if this is fixable or otherwise a known limitation.

**Comment by aschempp** [comment]
I think thats a known limitation and not a problem. If you have a 404 page that redirects e.g. to the homepage, previewing an unpublished page will also always redirect you. You would then have to enable unpublished elements and re-open the page from the back end.

We _could_ automatically enable unpublished element when clicking the page icon, would that make sense?

**Comment by fritzmg** [comment]
> We _could_ automatically enable unpublished element when clicking the page icon, would that make sense?

May be at least if the clicked page/article is unpublished, yes.

**Comment by leofeyer** [comment]
Maybe we should make "show unpublished" the default? Because viewing unpublished stuff is the main reason I use the front end preview for and I guess I am not the only one. 😉

**Comment by aschempp** [comment]
I don't think that should be the general default, I often also use this to get the front end page when editing a content element (on an already published page/news/whatever).

> We could automatically enable unpublished element when clicking the page icon, would that make sense?

that would solve your problem though, right?

**Comment by fritzmg** [comment]
Yes. But I would still only automatically enable unpublished elements, if the page itself is unpublished. Otherwise I also do not want to see unpublished elements by default.

**Comment by aschempp** [comment]
would that be a feature or a bugfix? 🤔

**Comment by fritzmg** [comment]
This is actually a duplicate of #488

**Comment by fritzmg** [comment]
Reopening as the feature of automatically showing the unpublished page is separate after all.

> would that be a feature or a bugfix? 🤔

bugfix imho

**Comment by leofeyer** [comment]
As discussed in the call, we could adjust the `PublishedFilter` so that unpublished pages are always visible in the preview.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6332
