### ISSUE TITLE
Backendbreite begrenzen

### ISSUE THREAD

**Issue by tschero** [contao/contao#6218]
### Description

Hallo Zusammen,

im Backend von Contao >= 5.1 ist mir aufgefallen, dass im Benutzerprofil die Schaltfläche "Fullscreen" - zur Begrenzung der Backendbreite - nicht mehr vorhanden ist.
Auf großen Bildschirmen empfinde ich persönlich die längeren "Mauswege" als eher störend wenn das Backend auf voller Breite angezeigt wird.

Würde es in Frage kommen, die Funktionalität zur Begrenzung der Breite des Backends in Contao >=5.1 wieder hinzuzufügen?

Grüße

**Comment by ausi** [comment]
Duplicate of #5050
