### ISSUE TITLE
Problems opening more than one preview link

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#6223]
### Affected version(s)

4.13.26

### Description

If I have more than one preview link, only opening the first one works. After that I am asked to enter a username and password. If I delete all cookies I can also open the second link.

How to reproduce this:

- Login in the back end and go to the preview of the site.
- Generate two preview links (Restrict access to specified URL is checked and the link is activated).
- Copy both preview links to your clipboard and log out from the back end.
- Open the first link from your clipboard, the page will be displayed.
- Open the second link from your clipboard, you are asked to log in.

**Comment by ausi** [comment]
I was able to reproduce this issue.

It looks like the new token is correctly stored in the session in https://github.com/contao/contao/blob/a4df08fb035d8f6f035878f73137020359951d52/core-bundle/src/Security/Authentication/FrontendPreviewAuthenticator.php#L62 but it gets overwritten afterwards by the old token, I don’t know where though.

**Comment by aschempp** [comment]
The security service automatically persists the current firewall token on response. We might need to replace the current firewall token instead of the session.

**Comment by ausi** [comment]
> We might need to replace the current firewall token instead of the session.

Done, see #6226
