### ISSUE TITLE
Add flags utf8_ucfirst, utf8_lcfirst, utf8_ucwords

### ISSUE THREAD

**Issue by madmaharaja** [contao/contao#6227]
### Description

I am currently building a French website where I am using insert tags. I want the first letter of each word that I am using the insert tags for to be capitalized. For this I am using the flag `|ucfirst` which works fine for the majority of cases. However, if the first letter of the word starts with a special character (e.g. as in "économie") then this flag does not work.

I would therefore suggest adding a version of this flag as well as two further flags that perform a unicode-conscious conversion. Based on the already existing flags `utf8_strtolower` and `utf8_strtoupper` I would therefore suggest the following naming:

- `utf8_ucfirst`
- `utf8_lcfirst`
- `utf8_ucwords`

FYI: Before posting this request, I searched the repository for any existing tickets regarding this topic and found this:
https://github.com/contao/core/issues/991
I am not sure, if this was ever implemented -- however in my Contao 4 installation and according to the [official documentation ](https://docs.contao.org/manual/en/article-management/insert-tags/) these flags don't exist yet:

**Comment by asaage** [comment]
As far as i know accents on capital letters are optional anyway.
What ist your result "conomie", Economie" or nothing at all?

**Comment by madmaharaja** [comment]
> As far as i know accents on capital letters are optional anyway. What ist your result "conomie", Economie" or nothing at all?

The result is the same as without the flag: "économie"

**Comment by leofeyer** [comment]
See #6228

**Comment by aschempp** [comment]
If I understand correctly, the fix for this would be to use `utf8_ucfirst` for our existing `ucfirst` flag, right? Should be fairly easy?

**Comment by ausi** [comment]
> If I understand correctly, the fix for this would be to use `utf8_ucfirst` for our existing `ucfirst` flag, right?

Yes, if you mean `mb_substr()` + `mb_strtoupper()` _(as `utf8_ucfirst()` was removed in Contao 5)_.

**Comment by leofeyer** [comment]
See #6940 and #6941.
