### ISSUE TITLE
Fehlerhafte Beschreibung in der Systemwartung

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#6233]
### Affected version(s)

4.13 und 5.1

### Description

In der Beschreibung für XML-Dateien neu schreiben steht:
```
Schreibt die XML-Dateien im Ordner shared neu und leert anschließend den Shared-Cache, damit keine ungültigen Links zurückbleiben.
```
Das stimmt aber nicht, denn seit Contao 4.13 ist es ja eine Route, wenn ich mich nicht ganz täusche.

**Comment by fritzmg** [comment]
> Das stimmt aber nicht, denn seit Contao 4.13 ist es ja eine Route, wenn ich mich nicht ganz täusche.

Nur für Nachrichten. Für Kalender, FAQs und sonstige Extensions gilt das noch immer. Und für Nachrichten trift der zweite Teil der Beschreibung zu (Shared Cache) - seit Contao 5, nicht seit 4.13.

**Comment by mlwebworker** [comment]
Danke für die Erklärung. Die Feinheiten sind mir dann doch entgangen.
Die Frage kam von einer Agentur, die verzweifelt die sitemap.xml im Ordner shared gesucht hat und mich darauf aufmerksam gemacht hat, dass bei den Einstellungen ja steht, dass die XML-Dateien im Ordner shared liegen.
Sie haben mir zunächst auch nicht so recht glauben wollen, dass die sitemap.xml dynamisch aufgebaut werden.
