### ISSUE TITLE
Multiple editing for images doesn't work correct.

### ISSUE THREAD

**Issue by havutcuoglu** [contao/contao#6235]
### Affected version(s)

4.13.23 and 5.1.9

### Description

Multiple editing for images doesn't work correct. 
You can select the caption and overwrite metadata and choose edit. You get empty result.
See screenshots.
You can also reproduce it in demo page [https://demo.contao.org/contao](https://demo.contao.org/contao)

![step_1](https://github.com/contao/contao/assets/11348417/81c16420-dbd2-4228-b697-0f0d420f6bd2)
![step_2](https://github.com/contao/contao/assets/11348417/005d4ea4-7326-40b7-9901-cb0bf0ccdc2b)
![step_3](https://github.com/contao/contao/assets/11348417/a9edf0e6-396f-4d8d-9f9b-bd4f44ecd684)

**Comment by ausi** [comment]
You need to edit the correct one, “Metadaten überschreiben [overwriteMeta]” instead of “Metadaten überschreiben [overwriteLink]”.

**Comment by havutcuoglu** [comment]
Oh, sorry! I didn't see this option. Why we have two “Metadaten überschreiben”?
I think it's better to change the label for overwriteMeta to "Bild Metadaten überschreiben" or "Media Metadaten überschreiben".
This is very misleading.

**Comment by havutcuoglu** [comment]
I think this feature is a good idea #3814
