### ISSUE TITLE
Backend DCA filter dropdown/select options overwritten - can't have 2 options with the same label

### ISSUE THREAD

**Issue by rhymeadam** [contao/contao#6239]
### Affected version(s)

4 and 5

### Description

Hi all, I'm running into an issue where a DCA filter of mine is based on a field with a foreign key to tl_member. I noticed that if 2 or more of the members have the exact same first and last name, the code overwrites the first occurences with the last option. I adjusted this line of code to include the $kk variable and it seems to work as intended. 

`$options_sorter[$option_label . '_' . $field . '_' . $kk] = '  <option value="' . StringUtil::specialchars($value) . '"' . ((isset($session['filter'][$filter][$field]) && $value == $session['filter'][$filter][$field]) ? ' selected="selected"' : '') . '>' . StringUtil::specialchars($option_label) . '</option>';`

https://github.com/contao/core-bundle/blob/e548fe395542a3265a7468a1d2f472cbc00eaf58/contao/drivers/DC_Table.php#L6265

**Comment by fritzmg** [comment]
I can confirm the issue in Contao 4.13. Reproduction:

* Create a back end user group with access to your news.
* Create a back end user with name "Test", username `test1`.
* Create a back end user with name "Test", username `test2`.
* Log in as `test1`, create a news record.
* Log in as `test2`, create a news record.

The _Author_ filter options when showing the news record of the news archive will only show one "Test" entry, even though there exist news from user `test1` and user `test2`.
