### ISSUE TITLE
Folder ID … is not mounted error when clicking visible root trails

### ISSUE THREAD

**Issue by ausi** [contao/contao#6243]
### Affected version(s)

5.2

### Description

Clicking on a parent folder of a file mount (`/contao?do=files&fn=files%2F…`) in the file manager results in the error `Folder ID "files/…" is not mounted`.

**Comment by leofeyer** [comment]
Yes, I have noticed this, too. It is a known limitation at the moment, as I don‘t think that there is an easy fix.
