### ISSUE TITLE
TinyMCE falsy or missing translation

### ISSUE THREAD

**Issue by Metis77** [contao/contao#6247]
### Affected version(s)

4.13

### Description

After adding the `styleselect` in the `be_tinyMCE.html5` to show my custom styles as dropdown, I found out, that it shows "Absatz" instead of "Formate". (In contao 4.9 this worked correctly)

<img width="478" alt="Bildschirmfoto 2023-07-26 um 18 22 55" src="https://github.com/contao/contao/assets/1408361/caba51a4-6ec0-47bb-ac83-46621af47bd9">

In the frontend Code this issue becomes clear even more:
<img width="441" alt="Bildschirmfoto 2023-07-26 um 18 24 16" src="https://github.com/contao/contao/assets/1408361/90847676-7bce-4985-b522-1949453d13d6">

**Comment by fritzmg** [comment]
That's normal. It shows whatever you have currently selected in the editor.

**Comment by Metis77** [comment]
hm yes, that is how the block formats worked.
but the style formats did not update before.
And thy should not, especially if the style format shows a block format.

But If you are saying, this I a new feature by TinyMCE 5, this should be closed.

**Comment by fritzmg** [comment]
It's definitely something that Contao cannot influence - and likely the intended behavior by TinyMCE.

**Comment by Metis77** [comment]
Ok, than its not helpful to further discuss this behavior here.
Thanx @fritzmg  for your feedback.

**Comment by de-es** [comment]
An der Übersetzung liegt es nicht. Siehe https://github.com/tinymce/tinymce/issues/7530

**Comment by Metis77** [comment]
@de-es Danke, das ist genau das Problem.
