### ISSUE TITLE
News "Redirect Target" with Insert Tag return 404

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#6248]
### Affected version(s)

4.* and 5.*

### Description

Suppose there is a News Item with url `https://example.com/news/this-is-a-post.html`.

We use an Insert Tag `{{news_url::8}}` as Custom URL to redirect it to another news. 

In News archive page, the link of this news item is what it should be.

But when we use news URL  directly to access it, it return 404 error with a weird URL like:
`https://example.com/news/{{news_url::8}}`

The problem shows itself when **the news link** is used on another website or clicked from search engines results.

This case can be easily reproduced in Contao's demo.

**Comment by ausi** [comment]
I was able to confirm this issue in Contao 5.1.10

**Comment by hamidpeywasti** [comment]
This also occur in **Events**.
