### ISSUE TITLE
No Assets (JS and CSS) after update to 4.13.28 (and possibly other versions)

### ISSUE THREAD

**Issue by kikmedia** [contao/contao#6257]
### Affected version(s)

4.13.28

### Description

See several threads (https://contao.slack.com/archives/CK4J0KNDB/p1690670294444009) or https://community.contao.org/de/showthread.php?85517-Nach-Update-auf-4-13-28-(von-4-13-16)-werden-keine-JS-und-CSS-mehr-geladen and https://community.contao.org/de/showthread.php?85520-Symlinks-in-public-bundles for further references.

Long story short: Seems that symlinks are broken in latest version(s) after upgrading.

**Comment by jedoCodes** [comment]
here a screenshot before upgrade to 4.13.28 (a rollback to 4.13.27 does not solve the problem )

![Screenshot at Jul 30 14-53-44](https://github.com/contao/contao/assets/1821865/ebe6781d-ecd4-47c4-a6a5-4bd65e8cf3d4)

here the console screen 

![Screenshot at Jul 30 14-57-06](https://github.com/contao/contao/assets/1821865/1fca3550-89b0-46f1-b037-a250f9e7f87b)

**Comment by m-vo** [comment]
What do you mean by "broken symlinks"? Are they missing or are they pointing to the wrong target (eg. `public/...` vs `web/..`)?

**Comment by kikmedia** [comment]
It seems that the Manager / Composer is trying to install assets as relative symbolic links but fails. Users are reporting that  the respective directories (e.g. /public/bundles) stay empty.

**Comment by m-vo** [comment]
> Users are reporting that the respective directories

So there are symlinks/directories? Could you maybe post the result of `ls -a public`?

And: are all users facing the issue using Windows/Linux?

**Comment by m-vo** [comment]
You also might want to make sure, there aren't both a `web` and `public` dir present. 🙂

**Comment by BugBuster1701** [comment]
in composer.json:
```
    "extra": {
        "public-dir": "public",
        "contao-component-dir": "assets"
    },

```
a web/ folder does not exist

**Comment by lukasbableck** [comment]
> So there are symlinks/directories? Could you maybe post the result of `ls -a public`?
> 
> And: are all users facing the issue using Windows/Linux?

There are no symlinks in public/bundles.
![Screenshot 2023-07-30 at 15 32 37](https://github.com/contao/contao/assets/42083846/d8378fc7-2f4f-410f-acfa-79e677fbe345)
![Screenshot 2023-07-30 at 15 33 48](https://github.com/contao/contao/assets/42083846/33b0c1d4-da32-433d-adc3-f2d0b875fe67)

In my case there is no web directory, only public, this installation also never had a web directory. 
And it's happening on a Debian 11 machine with nginx and PHP-FPM 8.2 for me.

**Comment by pagestyles** [comment]
It also happens if you install a new installation and place a "public based" composer.json / composer.lock to move an existing installation or update an existing installation (last is where i'm facing the issue right now)
- it was an clean 4.13 installation without ever having a web folder
macOS / all-inkl / php 8.1

**Comment by BugBuster1701** [comment]
I just updated locally on a 4.13.16 **only the Contao Manager to 1.6.5 and only updated one extension**, and now the web/bundles/ folder is empty!

**Comment by lukasbableck** [comment]
> I just updated locally on a 4.13.16 **only the Contao Manager to 1.6.5 and only updated one extension**, and now the web/bundles/ folder is empty!

Can confirm, same behaviour here. The issue seems to be unrelated to Contao 4.13.28 as it also occurs when Contao is not updated.

**Comment by lukasbableck** [comment]
https://github.com/symfony/symfony/issues/51162

**Comment by kikmedia** [comment]
I thought so before since there was one report where other versions of Contao are affected too. Could someone check please if marking a conflict with Symfony 5.4.26 solves the problem (can't check for myself, being on vacation now).

**Comment by lukasbableck** [comment]
Just did, yes it solves the issue.

**Comment by kartoffelheinz** [comment]
Yes, reverting to Symfony/finder 5.4.21 solves the issue!

**Comment by BugBuster1701** [comment]
This also works for me.

**Comment by grobitec** [comment]
Hello, I have the same problem.
Which file did you modify to switch to the older Symphony version? 
Or can someone tell me which composer command I can use for this.

Thanks a lot

**Comment by lukasbableck** [comment]
Add the following code to your composer.json and run composer update
```
"conflict": {
    "symfony/finder": "5.4.26"
},
```

**Comment by ausi** [comment]
We just added the new `symfony/finder` versions to the `contao/conflicts` package in https://github.com/contao/conflicts/pull/48 so running the update again should be enough to fix this issue for all Contao installations.

**Comment by derrabus** [comment]
We've issued new releases of the Finder component that should address this problem.

**Comment by ausi** [comment]
Thank you very much @derrabus for the fast response!
