### ISSUE TITLE
"Cannot unpack array with string keys" in ModuleFaqLister - brings down any page using it

### ISSUE THREAD

**Issue by rhymeadam** [contao/contao#6259]
### Affected version(s)

4.13.28

### Description

This is causing the FAQ lister module to throw an error. It is bringing all sites/pages using this module. Please release a patch quickly, thanks!

https://github.com/contao/contao/blob/96cea3d2ee7a51b77d1ac4c4cd1782d8d415c0ed/faq-bundle/contao/modules/ModuleFaqList.php#L108

**Comment by cliffparnitzky** [comment]
Cannot reproduce in https://demo.contao.org ... Are you sure everything is configured correctly?

**Comment by rhymeadam** [comment]
@cliffparnitzky I think this might be due our server using PHP 7.4 instead of 8.1+. Contao 4.13 is supposed to be compatible with 7.4, but this throws an error...

**Comment by cliffparnitzky** [comment]
Oha, then you should use PHP 8.1 ;-)

**Comment by jochi44** [comment]
I can confirm the issue in PHP 7.4.33.
As Contao 4.13 is compatible with PHP 7.4 this should be fixed, I think.

**Comment by jochi44** [comment]
This fix did it for me:

```
			// Order by PID
			$arrFaqs[$objFaq->pid]['items'][] = $objTemp;

			$arrFaqs[$objFaq->pid] = array_merge(
				(array)$objPid->row(), // convert to array to avoid error with non-array values
				['items' => $arrFaqs[$objFaq->pid]['items']]
			);
```

**Comment by leofeyer** [comment]
I guess we have to revert #6159 for Contao 4.13.

**Comment by m-vo** [comment]
Array unpacking is a PHP 8.1 feature. 🙃 But it should be easily replaceable with `array_merge` like in the example by @jochi44, I think.

**Comment by leofeyer** [comment]
Actually, `array_merge()` is not needed at all (see #6261). Initializing the array once is also more effective than merging the same values over and over again through the while loop.
