### ISSUE TITLE
2FA in frontend not working

### ISSUE THREAD

**Issue by ben-eSM** [contao/contao#6265]
### Affected version(s)

4.13 and 5.1

### Description

The two factor frontend authentication isn't currently working for me, no matter if I try a 5.1 or a 4.13 installation.
I've set up the 2FA module, placed it on a page and enforced the 2FA in the root page.
On the first login, I get redirected to the 2FA page as expected, to set up my 2FA device. So far so good.

However, on the next login I should get asked for the verification code, but the form for that never appears. I can see the protected pages in my navigation, so it appears that I'm already logged in. Unfortunately, no matter what menu link I click or manually enter a page url, I get redirected to the same page. The logfile shows weird route related errors.

```
[2023-08-02T20:40:51.928308+00:00] app.DEBUG: Router Symfony\Bundle\FrameworkBundle\Routing\Router was not able to match, message "No routes found for "/start.html/"." [] []
[2023-08-02T20:40:52.274153+00:00] app.DEBUG: Router Symfony\Bundle\FrameworkBundle\Routing\Router was unable to generate route. Reason: 'Route 'page_routing_object' not found': Unable to generate a URL for the named route "page_routing_object" as such route does not exist. [] []
```

The start.html route was the starting point where I had to login.

I have these issues with an existing installation as well as with 2 new test installations (4.13 and 5.1).

If I impersonate a user through the backend, I can navigate and use the site without any problems. But I guess in that case the 2FA check is getting bypassed.

**Comment by aschempp** [comment]
You might consider asking help about this setup in the community forums or our Slack channel: https://to.contao.org/support

**Comment by ben-eSM** [comment]
Actually it is not a setup / configuration issue. It is a general issue with the core.
I just verified the problem in the official contao demo. It behaves exactly the same as mentioned above.

One is able to configure the 2FA on the first login. On the subsequent login the 2FA form is not showing up after the first step authentication with the password. The system remains in an unusable state.

**Comment by ben-eSM** [comment]
Since I can reproduce it with every newly installed Contao version and even in the official Contao Demo, maybe someone else could give it a try. As said, this is clearly a bug and not a configuration issue. And I would even call it severe, as 2fa is an important security feature nowadays!

Maybe @bytehead can have a look at the issue?

**Comment by contaoacademy** [comment]
Hast du eine 401-Seite und darin ein Login-Modul hinzugefügt?

**Comment by ben-eSM** [comment]
> Hast du eine 401-Seite und darin ein Login-Modul hinzugefügt?

Ja, hab ich. Wie Anfangs erwähnt funktioniert beim ersten Login - also noch ohne eingerichtete 2FA für den User - soweit alles.
Man loggt sich ein mit Benutzername und Passwort (über die 401 Seite mit Login Modul), wird dann korrekt zur konfigurierten 2FA Seite weitergeleitet und kann die Authenticator-App soweit konfigurieren. Das passt alles.

Das Problem ist dann der nächste Login. Benutzername und Passwort werden abgefragt. Als nächstes sollte dann ja der 2FA Code abgefragt werden. Diese Abfrage kommt aber nicht und das System ist in einem undefinierten Zustand. Navigation usw. funktioniert alles nicht mehr korrekt und man bleibt immer auf der gleichen Seite hängen. Und das kann ich eben so in der offizielle demo.contao.org nachstellen als auch bei neuen Installationen.

**Comment by bytehead** [comment]
@ben-eSM kannst du mir einen SQL-Dump zu Verfügung stellen? Ich kann das Verhalten nicht reproduzieren bei mir.

**Comment by contaoacademy** [comment]
Was passiert, wenn du eine eigene Login-Seite erstellst mit Login Modul und zusätzlich das Login-Modul auf die 401-er Seite? Der Anmeldeversuche dann über die normale Login-Seite sattt über die 401?

**Comment by ben-eSM** [comment]
@bytehead Hier ein Dump von meinem Setup: [dump.sql.gz](https://github.com/contao/contao/files/13382999/dump.sql.gz)

Die Anmerkung von @contaoacademy ist jedoch spannend. Denn es ist in der Tat so, dass wenn ich das Login Modul z.B. zusätzlich noch auf die geschützte Seite setze, dann der 2. Faktor abgefragt wird.

Aber das folgende Setup geht definitiv nicht:
- 401 Seite mit Login-Modul inkl. Einstellung _Zur zuletzt besuchten Seite_
- Geschützte Seite mit beliebigem Content
- Seite mit dem 2FA-Modul
- In der Root Seite 2FA erzwingen

Das führt dann dazu, dass ein neuer User beim ersten Login zur Seite mit dem 2FA Modul geleitet wird und man den Authenticator problemlos einrichten kann. Nach Logout und erneutem Aufruf der geschützten Seite wird man zur 401 Seite weitergeleitet. Dort kann man Benutzername und Passwort eingeben und wird dann zurück zur geschützten Seite geleitet, jedoch ohne vorherige Abfrage des 2. Faktors. Und ab hier geht dann nichts mehr korrekt. Man ist in einem undefinierten Zustand zwischen eingeloggt und nicht vollständig authentifiziert.
Prinzipiell sollte das Setup wie beschrieben aber funktionieren, da ich das für ein gewöhnlichen Use-Case halte.
Das Problem ist, dass das Login Modul, bzw. die 401-Logik bereits nach Eingabe des 1. Faktors zurück leitet auf die vorherige Seite und eben nicht erst noch den 2. Faktor abfrägt.

**Comment by fritzmg** [comment]
> 401 Seite mit Login-Modul __inkl. Einstellung Zur zuletzt besuchten Seite__

You need to insert a login module on the 401 page where you have *disabled* this setting (regardless of this issue).

**Comment by ben-eSM** [comment]
> > 401 Seite mit Login-Modul **inkl. Einstellung Zur zuletzt besuchten Seite**
> 
> You need to insert a login module on the 401 page where you have _disabled_ this setting (regardless of this issue).

I can relate to that. Makes sense to disable the back to last page option.
However, the general issue still remains, no matter if this option is active or not.

**Comment by fritzmg** [comment]
Yes, I think the actual issue is, that the Contao `AuthenticationSuccessHandler` saves a target path that is the current URL, assuming that the current URL would be the URL with the login module. However, this won't work in the case of 401 responses, as the URL in this case will be the URL of the protected page.

Also I noticed that the logout page is not working at all (in this setup at least).

**Comment by aschempp** [comment]
@fritzmg can you maybe re-verify this in regards to https://github.com/contao/contao/pull/6805?

**Comment by fritzmg** [comment]
I cannot reproduce the issue in `4.13.x` at least.

**Comment by fritzmg** [comment]
Ah, never mind, I still had a login module in my layout. I can still reproduce the issue. It is unrelated to #6805.

**Comment by fritzmg** [comment]
@ben-eSM could you check if the change in https://github.com/contao/contao/pull/7323 fixes your issue?
