### ISSUE TITLE
Ständige Datenbank Änderungen seit Version 1.6.5

### ISSUE THREAD

**Issue by pressi** [contao/contao#6266]
Hallo,

seite dem CM Update auf 1.6.5, kommt im CM ständig die Meldung "Datenbank-Problem gefunden" > "Install-Tool öffnen"
Betrifft bis jetzt alle meine Installationen Contao Version 4.13.29.

Das Install-Tool will dann so ziemlich alle Datenbank Felder ändern.
![image](https://github.com/contao/contao-manager/assets/1610762/854858b2-dd08-4eed-b6c4-1610cd8591d5)

Wenn ich alle auf einmal Markiere kommt "Es ist ein Fehler aufgetreten".

`[2023-08-03T10:23:51.898724+02:00] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_route":"contao_install","_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction"},"request_uri":"https://#####/contao/install","method":"POST"} []
[2023-08-03T10:23:52.411644+02:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: ''" at /www/htdocs/#####/web2023/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 117 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 1292): An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: '' at /www/htdocs/#####/web2023/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:117)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1292): SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: '' at /www/htdocs/#####/web2023/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 22007): SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: '' at /www/htdocs/#####/web2023/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:32)"} []`

Wähle ich eine einzelne Änderung aus, lädt die Seite neu und die Änderung ist wieder in der Liste.

Hoster ist All-Inkl
Datenbank: 10.6.12-MariaDB-0ubuntu0.22.04.1-log - Ubuntu 22.04
PHP Version 8.1.16

Kann das an einer Installierten Erweiterung liegen? Es werden aber auch Core Felder geändert.

Vielen Dank & LIebe Grüße
Stephan

**Comment by aschempp** [comment]
das hat mit dem Contao Manager nichts zu tun, die Datenbank-Änderungen und das Install-Tool kommen von Contao. Ich verschiebe das Thema mal.

**Comment by ausi** [comment]
Welche Zeile genau erzeugt den Fehler `SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: ''`?

**Comment by pressi** [comment]
> Welche Zeile genau erzeugt den Fehler `SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: ''`?

Folgende Zeile hat diesen Fehler verursacht: (habe ich bereits entfernt)
"ALTER TABLE tl_article CHANGE rootPage rootPage INT UNSIGNED DEFAULT 0 NOT NULL"


Jetzt kommt dieser Fehler:

`An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows rows VARCHAR(8) DEFAULT '2rwh' NOT NULL' at line 1`

Liegt das an der in parameters.yaml eingetragenen Zeile?
database_version: 5.7.37-nmm1-log

**Comment by fritzmg** [comment]
> Liegt das an der in parameters.yaml eingetragenen Zeile?
> database_version: 5.7.37-nmm1-log

Ja, das ist die falsche `database_version`. Eigentlich sollte das `contao:migrate` Command dich darauf hinweisen 🤔

**Comment by ausi** [comment]
> Liegt das an der in parameters.yaml eingetragenen Zeile?
> database_version: 5.7.37-nmm1-log

Ja, bitte auf `database_version: 10.6.12-MariaDB` ändern.

**Comment by pressi** [comment]
> > Liegt das an der in parameters.yaml eingetragenen Zeile?
> > database_version: 5.7.37-nmm1-log
> 
> Ja, das ist die falsche `database_version`. Eigentlich sollte das `contao:migrate` Command dich darauf hinweisen 🤔

OK, ja der manuelle aufruf über die Konsole ergibt diese Meldung, der Manager zeigt das nicht an.

```
 [ERROR] Wrong database version configured, please set it to "10.6.12-MariaDB-0ubuntu0.22.04.1-log", currently set to   
         "5.7.37-nmm1-log"    
```



> > Liegt das an der in parameters.yaml eingetragenen Zeile?
> > database_version: 5.7.37-nmm1-log
> 
> Ja, bitte auf `database_version: 10.6.12-MariaDB` ändern.

ok. dann scheint es eine neue Datenbank Version vom Hoster zu geben, die alte Version des Managers hat dies nicht angezeigt. Nach der Änderung funktioniert alles wieder.
Gibt es eine Möglichkeit diese Zeile automatisch zu setzen? Wenn ich sie entferne?


Zur Info: Aufmerksam geworden bin ich auf dieses Problem über trakked, eventuell kann man dort bereits ein Prüfung einfügen mit einer Info, die Datenbank Version stimmt nicht überein, oder so ähnliches.


Viele Dank Euch beiden!

**Comment by leofeyer** [comment]
> OK, ja der manuelle aufruf über die Konsole ergibt diese Meldung, der Manager zeigt das nicht an.
> 
> ```
>  [ERROR] Wrong database version configured, please set it to "10.6.12-MariaDB-0ubuntu0.22.04.1-log", currently set to   
>          "5.7.37-nmm1-log"    
> ```

Wäre vielleicht nicht verkehrt, wenn er es täte?

**Comment by aschempp** [comment]
Also bei mir wurden solche Meldungen aber schon angezeigt… kannst jetzt aber nicht mehr sagen ob das nur bei Contao 5 so war oder auch bei Contao 4… 🤔
