### ISSUE TITLE
Preview links do not work in combination with logged in members

### ISSUE THREAD

**Issue by ausi** [contao/contao#6268]
### Affected version(s)

4.13

### Description

Creating a preview link pointing to a page that requires a frontend user does not work currently.

1. Create an unpublished page only visible to logged in members
2. Open the preview of that page
3. Select a frontend-user and show unpublished elements
4. Create a preview link
5. Open a new browser session
6. Enter the previously created link
7. Now the frontend user login page is shown and if you enter the login credentials of a frontend user, the preview token gets lost and the backend login page is shown.

**Comment by leofeyer** [comment]
Preview links do not yet support logging in as a front end user, do they?

**Comment by aschempp** [comment]
No they don't. Does this problem also exist in Contao 5? Because we changed the way the preview authentication works, as far as I remember it no longer relies on the Symfony user.

**Comment by ausi** [comment]
> Does this problem also exist in Contao 5?

I don’t know, I will try to reproduce it in Contao 5.

**Comment by ausi** [comment]
Works like a charm in Contao 5. 
So, do we even have to fix this in 4.13? Or can this be a known limitation with the old preview authentication workflow?

**Comment by leofeyer** [comment]
IMHO, it can be a known limitation in Contao 4.

**Comment by ausi** [comment]
Should we add it to https://github.com/contao/contao/blob/4.13/LIMITATIONS.md then?

**Comment by leofeyer** [comment]
Yes please.

**Comment by fritzmg** [comment]
Login does not work in general with preview links in 4.13. Are we sure we cannot fix this? This makes the front end preview unusable when the website is in maintenance mode and you want the customer to test some member functionalities.

i.e. the following does not work:

1. Put the website into maintenance mode via the website root's settings.
3. Have a login page (or 401 page with a login module).
2. Create a preview link for any non-protected page.
3. Open that preview link with a fresh browser session.
4. Go to the login page and login.

You will be redirected to the Contao back end login.

**Comment by ausi** [comment]
> This makes the front end preview unusable when the website is in maintenance mode and you want the customer to test some member functionalities.

The regular frontend preview (via backend login, not preview link) should work as you can select a frontend member in the preview toolbar then.

**Comment by fritzmg** [comment]
Yes, but that requires a back end login.
