### ISSUE TITLE
contao/phpstan: ClassNotFoundException

### ISSUE THREAD

**Issue by bytehead** [contao/contao#627]
**Affected version(s)**
4.8.*

**Description**  
https://github.com/contao/phpstan/pull/4 makes `contao/phpstan` for our contao based projects unusable.

```
[Symfony\Component\Debug\Exception\ClassNotFoundException]                                                                                                                                                
  Attempted to load class "AppKernel" from namespace "Contao\CoreBundle\Tests\Functional\app".                                                                                                              
  Did you forget a "use" statement for e.g. "Symfony\Bundle\SecurityBundle\Tests\Functional\app\AppKernel", "Symfony\Bundle\FrameworkBundle\Tests\Functional\app\AppKernel" or "App\HttpKernel\AppKernel"?
```

Test classes are only in `autoload-dev`:
https://github.com/contao/contao/blob/2d253fbff95172890bed579c5ab2886b1ca5ac41/composer.json#L220-L230

**How to reproduce**  
Use `contao/phpstan` in a contao project and run phpstan with the `contao/phpstan` extension.

**Comment by aschempp** [comment]
How does it work in `contao/contao` then? Maybe you need to manually register the test classes in your bundle?

**Comment by bytehead** [comment]
See above (Line 224), the test classes are added in `autoload-dev`. That could be one solution, but it does not make me really happy 🤷‍♂

**Comment by aschempp** [comment]
The only other solution to this would be to extract the fixtures into their own package, which seems kinda overkill to me? Maybe we should add them to `contao-test`?

**Comment by leofeyer** [comment]
See contao/phpstan#6
