### ISSUE TITLE
Memory Limit - file management preview image of animated gif under 100x75 are converted to data:image

### ISSUE THREAD

**Issue by Ainschy** [contao/contao#6270]
### Affected version(s)

4.13.29

### Description

Background: Migration of an old 2.11 to 4.13 are about 3500 animated gifs in a folder of the file management. These gifs are 75x75 and are partly 1-3Mb in size.

Opening the folder in the file manager leads to the memory limit.

The cause lies according to information of @ausi here

https://github.com/contao/contao/blob/bb9d251ceb8fd843e36778e24efedfc9964f9fda/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L2830

Suggestion from @fritzmg is to replace lines 2827 - 2835 with.
`$thumbnail .= '<br>' . Image::getHtml(System::getContainer()->get('contao.image.factory')->create($this->strRootDir . '/' . rawurldecode($currentEncoded), array(100, 75, ResizeConfiguration::MODE_BOX))->getUrl($this->strRootDir), '', 'class="preview-image" loading="lazy"');`

The test in the affected installation was successful.

**Comment by ausi** [comment]
For info: This inlining was added in https://github.com/contao/core-bundle/issues/636 to prevent broken images inside protected folders. This should not be needed anymore since we now have the `skipIfDimensionsMatch` resize option that defaults to `false` and therefore the images would always be served via `assets/images` anyway.

**Comment by leofeyer** [comment]
So we just have to revert https://github.com/contao/core-bundle/commit/f4a32d5054270b5d4c8e98b51e3b4b8a98f37856 then, right?

**Comment by ausi** [comment]
Basically yes, but as the rest of the code has changed, we just need to remove the lines 2827-2833 and 2835 from here: https://github.com/contao/contao/blob/bb9d251ceb8fd843e36778e24efedfc9964f9fda/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L2827-L2835
