### ISSUE TITLE
tl_calendar_events cannot save a date past 2038-01-18

### ISSUE THREAD

**Issue by blairwinans** [contao/contao#6272]
### Affected version(s)

4.13.x, 5.1

### Description

If you try to save the `endDate` of an event with a date greater than 2038-01-18, you will get a SQL error for the `endTime` column:

`An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'endTime' at row 1`

Steps to reproduce on the current Contao Demo (5.1, but also affects 4.13 in my testing)

1. Edit/create an event in tl_calendar_events. 
2. Set the endDate (or startDate) to a date greater than 2038-01-18.
3. You will get a 500 page and SQL error.

Obviously this involves the adjustTime callback, but I have not been able to dive into it sufficiently to see what the issue may be.

**Comment by fritzmg** [comment]
Does everything work if you make the following adjustment?

```php
// contao/dca/tl_calendar_events.php
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['startDate']['sql'] = ['type' => 'bigint', 'notnull' => false];
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['startTime']['sql'] = ['type' => 'bigint', 'notnull' => false];
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['endDate']['sql'] = ['type' => 'bigint', 'notnull' => false];
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['endTime']['sql'] = ['type' => 'bigint', 'notnull' => false];
```

Afterwards rebuild the Symfony Application Cache and update the database.

**Comment by blairwinans** [comment]
@fritzmg Just ran those DB updates, and yes—it now saves without any issues. Thank you!

**Comment by fritzmg** [comment]
@contao/developers I think we should leave this open and change this for all (integer based) timestamp fields, should we not?

**Comment by leofeyer** [comment]
As briefly discussed in Slack, we have to check if our minimum MySQL versions supports this. Also, we have to check if changing the type affects the DB size.

**Comment by ausi** [comment]
> we have to check if our minimum MySQL versions supports this

`BIGINT` was already supported in MySQL 5.0, so this should not be a problem I think.

**Comment by ausi** [comment]
> Also, we have to check if changing the type affects the DB size.

Uses 8 bytes (64 bits) instead of 4 bytes (32 bits).
