### ISSUE TITLE
Contao 5.2: wrong status labels

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6273]
### Affected version(s)

5.2.0 RC5

### Description

During my tests I noticed that the new status dependent labels are not correct everywhere.
However, I only tested the German language.

Wrong at:
- News: highlight/not highlight (not status dependent).
- Events: publish/unpublish (incorrect status).
- Events: highlight/not highlight (not status dependent)

I also noticed that the German translation is missing in the favorites management area. Just saw that this is probably also the case with Contao 5.1.

**Comment by fritzmg** [comment]
What do you mean by status dependent labels?

**Comment by aschempp** [comment]
@fritzmg https://github.com/contao/contao/pull/5419

**Comment by aschempp** [comment]
it appears I forgot about the highlight toggle buttons. But the publish buttons should be translated, could be that the german language has not been updated. @contaoacademy maybe you could quickly switch to english and see if that works?

**Comment by fritzmg** [comment]
Do you mean this?

![2023-08-10 (2)](https://github.com/contao/contao/assets/4970961/2385691a-dcb1-4344-82f4-2ebcd079a939)

If yes, then I cannot reproduce the issue.

**Comment by contaoacademy** [comment]
Yes I mean this.

But you are looking in the news. Please check the events

**Comment by fritzmg** [comment]
Ah I see what you mean now. It still says "veröffentlichen/unveröffentlichen".

**Comment by contaoacademy** [comment]
And here in Events it should be "unveröffentlichen"
<img width="848" alt="screen-20230810_94uYa2SY" src="https://github.com/contao/contao/assets/23719181/8063fa57-33a5-4c69-8107-c4f15bdcf55e">

**Comment by contaoacademy** [comment]
@aschempp 
In English it is also wrong in the events and "highlight" is not translated.

**Comment by fritzmg** [comment]
> and "highlight" is not translated.

This I cannot reproduce though.

**Comment by leofeyer** [comment]
> Events: publish/unpublish (incorrect status)

I have fixed the mixed-up labels in 23e1026fcb6c376fbb33c6e22856450a18ee3301.

> it appears I forgot about the highlight toggle buttons.

@aschempp Are you going to create a pull request?

**Comment by contaoacademy** [comment]
> I also noticed that the German translation is missing in the favorites management area. Just saw that this is probably also the case with Contao 5.1.

What about the translations for the favorites? Should I create a new issue?

**Comment by contaoacademy** [comment]
> In English it is also wrong in the events and "highlight" is not translated.

@fritzmg Sorry, das war einfach verwirrend. Vergiss es!

**Comment by fritzmg** [comment]
> What about the translations for the favorites? Should I create a new issue?

That's a separate issue, yes.

**Comment by aschempp** [comment]
> @aschempp Are you going to create a pull request?

Done: https://github.com/contao/contao/pull/6282 😎 

Kinda feels unintuitive to have `key.1` be `unpublished` and `key.2` be `published`? Maybe we should swap the two keys?

**Comment by leofeyer** [comment]
Yes, please.
