### ISSUE TITLE
Show last authentication error on all login modules

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#6275]
### Affected version(s)

4.13 (I guess same in 5.x)

### Description

If you have multiples of the same login frontend module on the same page only one of them will show any error messages if a member tries to login unsuccessfully. 

Changing https://github.com/contao/contao/blob/bb9d251ceb8fd843e36778e24efedfc9964f9fda/core-bundle/src/Resources/contao/modules/ModuleLogin.php#L116 to `$exception = $authUtils->getLastAuthenticationError(false);` seems to do the trick but isn't a clean solution.

@ausi proposed:
> wir könnten es aber beim auslesen in die request attributes schreiben $request->attributes->set(Security::AUTHENTICATION_ERROR, …) dann würde getLastAuthenticationError() zumindest für alle die noch denselben request bearbeiten funktionieren...

**Comment by fritzmg** [comment]
@bennyborn can you provide a PR with the proposed solution?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6840
