### ISSUE TITLE
German translation is missing in the favorites management area

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6277]
### Affected version(s)

5.1.+

### Description

I noticed that the German translation is missing in the favorite management area. Also in Contao 5.2

![screen-20230810_a16wFgBZ](https://github.com/contao/contao/assets/23719181/70698fb4-9582-48b3-a336-eca7fbad0f03)

![screen-20230810_5gDCpCbD](https://github.com/contao/contao/assets/23719181/39ced2d7-0d10-46c4-b3c3-a1c1a103a820)

**Comment by leofeyer** [comment]
Fixed in 3795148c01d2f877cc055a1c4efbdc2a9b5b4ba4.
