### ISSUE TITLE
`Model::findBy()` must not return a single model

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6280]
### Affected version(s)

4.0.0+

### Description

When we optimized the models for Contao 4.0.0, we changed the `Model::findBy()` method to return a collection **or** a single model (see 1440881b18e055fb247d2190b0252ea7a73054d3). However, in the code base, we typically use the method like this:

https://github.com/contao/contao/blob/648d6e3e3dd4fc33bacba6cd89b5947d4768ab50/calendar-bundle/src/EventListener/SitemapListener.php#L40-L48

https://github.com/contao/contao/blob/648d6e3e3dd4fc33bacba6cd89b5947d4768ab50/core-bundle/contao/widgets/RootPageDependentSelect.php#L29-L34

But this works only by chance and would break if a field was unique, because then we would get a single model and pass it to `foreach`. We would have to handle this case explicitly:

```php
$objCalendars = $this->framework->getAdapter(CalendarModel::class)->findByProtected(''); 
  
 if (!$objCalendars instanceof Collection) { // null or single model
     return; 
 } 
```

But there are a lot of places in the code where we use `null !==` instead of `instanceof Collection`, so this will not be a quick fix. Maybe we should revert 1440881b18e055fb247d2190b0252ea7a73054d3 instead?

Shouldn‘t only methods starting with `findOneBy` ever return a single model? And methods starting with `findBy` always return a collection? (I know that we already have `findById()`, `findByPk()` and `findByIdOrAlias()` which all return a single model.)

**Comment by aschempp** [comment]
whoa, what a strange behaviour, never noticed that. I guess it's e.g. because if you `findByUsername()` you expect to only get one member, because only one member can have that username? I generally dislike the `findBy…` _automated_ methods anyway...

**Comment by fritzmg** [comment]
> But this works only by chance and would break if a field was unique, because then we would get a single model and pass it to `foreach`.

But we know which fields are defined `unique` and thus we would never assume a collection is returned for such a field.

**Comment by ausi** [comment]
To me that is the expected behavior, `findByProtected()` returns a collection and `findByUsername()` returns a model. _(if username is a unique column)_

> Maybe we should revert [1440881](https://github.com/contao/contao/commit/1440881b18e055fb247d2190b0252ea7a73054d3) instead?

That would be a huge BC break only allowed in Contao 6 I think. But I wouldn’t change it anyways.

**Comment by leofeyer** [comment]
> To me that is the expected behavior, `findByProtected()` returns a collection and `findByUsername()` returns a model

So:

* `findByProtected()` → collection
* `findOneByProtected()` → model

But:

* `findByUsername()` → model
* `findOneByUsername()` → model

How can that be an expectable behavior? 😄

**Comment by ausi** [comment]
But also:
- `findByUuid()` => model
- `findOneByUuid()` => model
- `findByPk()` => model
- `findOneByPk()` =>  model
- `findById()` => model
- `findOneById()` => model

Do you want to change them as well? 😳

**Comment by leofeyer** [comment]
Hm, good point.

**Comment by leofeyer** [comment]
Then I will close this issue again with regard to #6283.
