### ISSUE TITLE
Method 'errorInfo' not found

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6286]
### Affected version(s)

4.13+

### Description

<img width="719" alt="" src="https://github.com/contao/contao/assets/1192057/566cc8ee-23fa-48ac-9277-450722d9353b">

The method only exists in the `PDO` class and Doctrine does not seem to map the function call.

https://github.com/contao/contao/blob/bb9d251ceb8fd843e36778e24efedfc9964f9fda/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php#L91-L93

Does this work for anyone? @ausi /cc

**Comment by ausi** [comment]
> Doctrine does not seem to map the function call

This was removed in Doctrine 3.0, see https://github.com/doctrine/dbal/pull/4030

How do we fix this? Just remove the `->error` member completely?

**Comment by leofeyer** [comment]
I guess so. 👍
