### ISSUE TITLE
Problem does not connect to database

### ISSUE THREAD

**Issue by jnegrete2020** [contao/contao#6291]
### Affected version(s)

4.13

### Description

Hi, in this way I request your help with the following: 1) I have performed installation of CMS Contao system, on my web server and I have followed the installation process as required, then when accessing Contao presents the administration and updates module, but does not present the connection module with local database,   so I do not have how to conect the application with the local database;

Therefore, I go to the maintenance area on:
contao/public/contao-manager.phar.php/#/maintenance

In this area it reports: Database migrations Database problem encountered. Database migrations ensure consistent table and data schemas

Then I go to:Open installation tool
https://xxxxxxx/contao/install

By clicking on this link the following message is displayed:
Not Found
The requested URL was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Therefore, I would like to know that I can be recommended to install a version other than 4.13?

Thank you very much for your help,

**Comment by ausi** [comment]
As the URL to the Contao Manager looks like /contao/public/contao-manager.phar.php in your installation the URL to the install tool is probably /contao/public/contao/install or /contao/public/index.php/contao/install

Either way the document root of your webserver seems to be configured incorrectly. Please follow the documentation regarding this topic: https://docs.contao.org/manual/en/installation/contao-manager/#hosting-configuration
