### ISSUE TITLE
Missing redirect for app.php leads to duplicate content

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#6292]
### Affected version(s)

4.13

### Description

I think there is a problem with duplicate content problem in current 4.13 installations?

In the `.htaccess` there is the line `RewriteRule ^index\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]`.
In earlier Contao versions there was `RewriteRule ^app.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]`.

But now we have the problem that the redirection only exists for the `index.php` but not for the `app.php`.
So I can easily add an `/app.php/` to every URL and get duplicate content.

**Comment by fritzmg** [comment]
imho it wouldn't hurt to also add

```
RewriteRule ^app\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]
```

by default for Contao 4.13.
