### ISSUE TITLE
Recompile templates when property changes

### ISSUE THREAD

**Issue by aschempp** [contao/contao#63]
The `$blnCompiled` property of templates must be reset if `__set` is called.

**Comment by leofeyer** [comment]
To be exact, it has to be reset when any of the following methods is called:

- `__set()`
- `setData()`
- `setFormat()`

Not sure about `setName()` as changing the name should not change the content, right?

**Comment by aschempp** [comment]
I guess it would, because hooks would act on the name.

**Comment by leofeyer** [comment]
Then all four of them. Agreed?

**Comment by aschempp** [comment]
yes

**Comment by leofeyer** [comment]
You know what, I think we should remove the `$blnCompiled` check completely. Then we had the Contao 3 behavior and we don't have to fear any issues (such as the one we are discussion now). Also agreed?

**Comment by aschempp** [comment]
right! It's unlikely that the template will be generated multiple times, so there's no reason to "cache".

**Comment by leofeyer** [comment]
Removed in f82b7d2122cca175c74dfe110e6f28bbf2a44cac.
