### ISSUE TITLE
Cannot create page after update to 4.4.25 (Internal Server Error)

### ISSUE THREAD

**Issue by bohnmedia** [contao/contao#63]
**Affected version(s)**
Contao 4.4.25 (Managed Edition)

**Description**
After updating from Contao 4.4.21 to 4.4.25 its not possible to create new pages.

Error message:
Internal Server Error
The registry already contains an instance for tl_page::id(2)

**How to reproduce**  
We get the same problem on a fresh 4.4.25 installation. (Managed Edition)

- Install 4.4.25 (Managed Edition)
- Log into backend
- Goto site structure
- Click on new page and into page ID 0
- Enter page name, page type (website root), language and set language fallback
- Click on save

**Comment by OMOSde** [comment]
I can confirm the issue on a fresh 4.4.25 installation (php 7.2.10). We downgrade the test installation to 4.4.24 and it works like a charm.

**Comment by kikmedia** [comment]
Confirmed, PHP 7.2.

**Comment by xchs** [comment]
I can confirm the issue for Contao 4.6.4, too.

**Comment by Defcon0** [comment]
Same here (4.4.25, PHP 7.1).

**Comment by TB1234** [comment]
I can also confirm this problem in one installation. 
Contao 4.6.4 with PHP 7.2.10

**Comment by ReneLuecking** [comment]
Ich konnte das Problem beheben, in dem ich in der [tl_page.php](https://github.com/contao/core-bundle/blob/4.6/src/Resources/contao/dca/tl_page.php#L1069) die Zeile `$objPage = new PageModel($dc->activeRecord);` zu `$objPage = PageModel::findById($dc->activeRecord->id);` geändert habe.

**Comment by leofeyer** [comment]
Fixed in b6c1d775262a48ec82c444fa99f2d6124f2df1fa.
