### ISSUE TITLE
Only generate the `srcset` attribute if required

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6301]
### Description

At the moment, the `Picture` class always generates both the `src` and the `srcset` property. In our template, we then have to check if both values are the same to decide whether or not the `srcset` property should be rendered.

https://github.com/contao/contao/blob/e3e265e89c9fd834b27e66f0635ad1ee60108d32/core-bundle/contao/templates/picture/picture_default.html5#L9

https://github.com/contao/contao/blob/e3e265e89c9fd834b27e66f0635ad1ee60108d32/core-bundle/contao/templates/_new/component/_picture.html.twig#L35

I wonder why we don‘t unset the `srcset` property in this case, so we can just do an `isset()` or `is defined` check in the templates?

**Comment by ausi** [comment]
The code that generates `src`/`srcset` for `<img>` and `<source>` is the same, and omitting `srcset` for the `<source>`s is not possible, so we’d have to unset it after it was generated specifically for `<img>` only.

Looking at this I noticed that we currently remove any `x` descriptor from the `srcset` in https://github.com/contao/image/blob/858d8be1f8500d26ace75c3a724b2ce73b11eebe/src/PictureGenerator.php#L224-L226 which is wrong as the `x` descriptor influences the rendered size of the image. We should remove these lines I think, this would also mean that `srcset` and `src` can never be the same anymore anyways.

**Comment by leofeyer** [comment]
But even then, the `srcset` in `<img src="foo.jpg" srcset="foo.jpg 1x">` would still be unnecessary, wouldn‘t it?

**Comment by fritzmg** [comment]
Technically we could omit the 1x srcset: https://stackoverflow.com/questions/34466761/html5-srcset-is-1x-mandatory

**Comment by ausi** [comment]
Omitting in the template is fine IMO, but I don’t like removing the `srcset` from the array.
If I want to use the image data e.g. for a CSS `image-set()`, the `srcset` cannot be omitted.

We currently also generate a `src`-value for the `<source>` elements even though it is not used in the template. But it might be useful if someone wants use the data for CSS (by combining media queries with `background-image`).
