### ISSUE TITLE
Script handler still adds "app" directory

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#631]
**Affected version(s)**

4.8

**Description**  

The script handler of the manager bundle still adds the `app` directory in the `addAppDirectory()` method. Since we now use the `config` directory instead, can this be removed? @aschempp /cc

**Comment by aschempp** [comment]
Not sure, we still use the app directory in the install tool, don't we? ;-)

**Comment by leofeyer** [comment]
I have just discovered that `contao-community-alliance/composer-plugin` uses the `app/Resources/contao/config` directory for the runonce files:

https://github.com/contao-community-alliance/composer-plugin/blob/2686fb2299fa4fcde1d3a54ec10cd497661d8536/src/Plugin.php#L92

We should change this as well, shouldn't we?

**Comment by aschempp** [comment]
I don't think that's worth the effort. The old way is still perfectly valid, if your extension needs to be compatible with multiple Contao versions…?

**Comment by leofeyer** [comment]
Wouldn't `var/runonce` (or even `system/tmp`) be a better choice that also works with all Contao 4 versions?

**Comment by aschempp** [comment]
why would that work in all versions? It's the legacy `runonce.php` file that was supported since forever in Contao 2/3. And I don't think we want to invent a new place for a file that should become obsolete…

**Comment by leofeyer** [comment]
Because `system/tmp` exists in all Contao 4 versions?

**Comment by aschempp** [comment]
But runonce.php files in the system/tmp directory are not executed by the install tool …

**Comment by leofeyer** [comment]
That could certainly be adjusted. 🙄 

The point is that Contao 4.8 does not require an `app` folder anymore, therefore we should stop using it. I agree that adjusting the composer-plugin might not be worth the effort though.

**Comment by aschempp** [comment]
That's what I'm saying. We can obviously adjust anything, but we should not update a outdated feature just for the sake of "seeing a folder that is not state-of-the-art"…

**Comment by leofeyer** [comment]
Fixed in 3deeee007a933a566b451258abd9f2b6ea4d2503.

**Comment by aschempp** [comment]
Please do not remove public static methods, they are part of the API. They are meant to be used in the `composer.json` if you only want parts of the app initialization process…

**Comment by leofeyer** [comment]
The BC promise does not cover the Composer script handlers, but here you go: 4b6ee21be1021ef48ebfd0a3c3c88a40336d13fc
