### ISSUE TITLE
info modal pop up shows "Untitled" without translation

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#632]
**Affected version(s)**
4.8

**Description**  
In Contao 4.8 we do not explicitly have to translate the labels for `edit`, `delete`, `show` etc. any more. However, if you do not provide a translation for `show`, the modal pop up when clicking on the ℹ️ symbol will have __Untitled__ as its title, instead of "Show details of element ID x".

Not sure if this is technically a bug, but it would be nice if we did not necessarily have to provide a translation for `show` as well.

**Comment by leofeyer** [comment]
How do I reproduce this in the online demo?

**Comment by fritzmg** [comment]
> How do I reproduce this in the online demo?

I can't. You need to create a new DCA where the translation for `$GLOBALS['TL_LANG']['tl_foo']['show']` is missing or remove the translation for a core module, `$GLOBALS['TL_LANG']['tl_news']['show']` for example.

**Comment by leofeyer** [comment]
Fixed in 75e60ab137496d1d6f7ae85a326cf1c91cd15793.
