### ISSUE TITLE
The insert tags may get URL encoded when saved in the backend

### ISSUE THREAD

**Issue by qzminski** [contao/contao#6323]
### Affected version(s)

4.13, 5.x

### Description

It seems that in Contao 5.2 things changed a bit regarding the URL encoding of the field values in the backend. Here is the story: in the content element of `Hyperlink` type and inside the `Link target` we provide the following value:

```
{{link_url::117}}
```

It works fine. But then we need to add some hash to this for JS script like so:

```
{{link_url::117}}#portfolio:category
```

After saving the record the input gets encoded:

```
{{link_url%3A%3A117}}#portfolio%3Acategory
```

That's fine if the insert tag would be preserved, because now it's broken. If I change it manually to this:

```
{{link_url::117}}#portfolio%3Acategory
```

And save again, it seems to keep this value. But whenever I change `%3A` to `:` it again encodes the WHOLE field input and including the insert tag, which should not happen I think.

As discussed with @ausi, it is likely this commit that introduced this behavior: https://github.com/contao/contao/commit/8e9edfb376bea50e205edf3857d5b008d97af70e#diff-785aa5fc38b938ea78f20ed7b0b939f04b0ccdc803a0c5545a6f4da8e5215038

**Comment by ausi** [comment]
I think we need to replace the line https://github.com/contao/contao/blob/0cf72e231a0a117d4045680a959d4cf223f002bf/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L943 with something like the following:

```php
$arrChunks = preg_split('/({{[^{}]*}})/', $strString, -1, PREG_SPLIT_DELIM_CAPTURE);
$strString = '';

foreach ($arrChunks as $index => $strChunk)
{
	$strString .= ($index % 2) ? $strChunk : preg_replace($colonRegEx, '%3A', $strChunk);
}
```

This would only encode the colons outside of insert tags so `{{link_url::117}}#portfolio:category` will correctly be replaced with `{{link_url::117}}#portfolio%3Acategory`

**Comment by qzminski** [comment]
Just wanted to confirm that @ausi proposal does fix the problem.
