### ISSUE TITLE
Insert tag for back link not working properly

### ISSUE THREAD

**Issue by Anke** [contao/contao#6344]
### Affected version(s)

5.1.11 / 5.2.0

### Description

Hi,

with C5.1 und C5.2 the backlink insert tag `{{link::back}}` isn't working (correctly). 

When I put the insert tag into a content element "Text", it isn't visible in the backend after saving and closing the content element. In the FE I get this:

```
<div class="content-text">
  <div class="rte">
    <p></p>
  </div>
</div>

```
Entering the same insert tag into a Hyperlink CE, I do get a link and link title in the FE, however the link leads to the home page and not to the page last visited.

I tried to reproduce this in the Contao demo (5.1.11). The FE output is this:

```
<div class="ce_text block">
<p></p>  
</div>
```

At least the insert tag is visible in the backend in the article's list of content elements.

**Comment by Toflar** [comment]
The `{{link::back}}` insert tag has been deprecated ever since Contao 4.9 and does not exist in Contao 5 anymore.

**Comment by Anke** [comment]
Okay ... I wish it had been added to the hyperlink and toplink CE's ...
