### ISSUE TITLE
Internal server error when theme screenshot image is missing

### ISSUE THREAD

**Issue by xchs** [contao/contao#636]
**Affected version(s)**

Contao 4.4 / Contao 4.8

**Description** 

Contao is throwing an internal server error exception when the theme screenshot/preview image is missing or defect.

**How to reproduce**  

* Add a screenshot image in the theme settings
* Delete or rename the screenshot image file
* Try to open _Layout_ > _Themes_

**Expected behavior**

Ignore the missing or defect screenshot/preview image and open the _Themes_ back end module.

**Comment by leofeyer** [comment]
I wasn't able to reproduce this. I have deleted the theme image and when I re-opened the themes module, the theme was shown without it. No exception message.

What exactly does the exception message say?

**Comment by leofeyer** [comment]
Ok, @ausi reminded me not to remove the file in the file manager and now I see the exception.

**Comment by leofeyer** [comment]
Fixed in b91d01c0a7e83f9f3c6bf27bebfc4445c4f688ad.
