### ISSUE TITLE
Keine Anzeige der Bildausrichtung bei Inhaltselement Bild

### ISSUE THREAD

**Issue by minstyle** [contao/contao#637]
**Affected version(s)**
Contao 4.4.1
Contao 4.7.7

**Description**
![image](https://user-images.githubusercontent.com/2649562/63153938-d0b3d680-c00f-11e9-9313-da8e94b7415b.png)
In den Benutzerrechten besteht Zugriff auf die Bildausrichtung.

![image](https://user-images.githubusercontent.com/2649562/63154021-fe008480-c00f-11e9-8a74-28bf5191e8bd.png)
Im Contao-Backend fehlt die Auswahl der Bildausrichtung.

**How to reproduce**
Neues Inhaltselement "Bild" auswählen und im Bereich "Dateien und Ordner" steht keine Auswahl der "Bildausrichtung" mehr zur Verfügung.

Das Problem ist auch in der aktuellen Contao-Demo (Rolle: Admin) reproduzierbar.

**Comment by leofeyer** [comment]
Kann ich in der Onlinedemo nicht reproduzieren.

* Login als "h.lewis"
* Artikel -> Home -> Bearbeiten
* Erstes Inhaltselement bearbeiten und "Ein Bild hinzufügen" aktivieren
* Das Feld "Bildausrichtung" ist sichtbar.

Vielleicht wird das Feld bei Dir durch einen Inhaltsblocker des Browsers entfernt?

**Comment by minstyle** [comment]
Was du beschreibst, beschreibt leider nicht meinen Weg.

Du musst ein neues Inhaltselement "Bild" erstellen. Hier ist die Bildausrichtung nicht verfügbar.

**Comment by minstyle** [comment]
@leofeyer 
Sorry, habe mich verguckt. Ich sehe gerade, beim Inhaltselement "Bild" steht die Bildausrichtung standardmäßig nicht zur Verfügung.
