### ISSUE TITLE
Rename the _contao_preview cookie

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#638]
The JWT cookie is still called `_contao_preview`, although it does not have anything to do with the front end preview anymore. We should rename it to `contao_settings` or something else.

**Comment by aschempp** [comment]
yes, please rename to `contao_settings`. I thought you already did as we agreed on that 🙈

**Comment by leofeyer** [comment]
There was no more time…

**Comment by leofeyer** [comment]
Fixed in d2a0b61e6d3f36b27e5c4624267ac075ef9b71e6.

**Comment by aschempp** [comment]
just for the next time… 😂 
https://github.com/contao/contao-manager/issues/500#issuecomment-638785169
