### ISSUE TITLE
Missing tooltips on the Contao Backend on touch devices

### ISSUE THREAD

**Issue by may17** [contao/contao#6382]
It seems like there is no touch support for the explanation tooltips below each backend field on touch devices.

Tested on my iPhone 6s on safari.

**Comment by fiedsch** [comment]
can't confirm this here (iPhone7)
![iphone7_tooltips](https://user-images.githubusercontent.com/5047601/42771777-980cb1cc-8928-11e8-8f2c-eeb959f0c7ee.PNG)

**Comment by may17** [comment]
Hm ok, thats strange :D I‘ve got that issue on Demo.contao.org i will check that on some other devices.

**Comment by tophcodes** [comment]
Tested on iPhone 6 (iOS 11.2.6) and iPhone 6S Plus (iOS 12.0 16A5318d), tooltips don't show up on either device.

**Comment by leofeyer** [comment]
I can confirm that the tooltips do not show up in Safari on iOS.

@contao/developers Is this something we want to fix?

**Comment by xchs** [comment]
I found other bugs (mainly regarding the positioning of the tooltip) but I don't know if it's really worth the effort to fix them. 😄

**Comment by ausi** [comment]
> Is this something we want to fix?

I think so. Otherwise, if the explanation text is cut off there would be no other way to show the complete text.

**Comment by leofeyer** [comment]
Ok. And how do we fix it? 😄
