### ISSUE TITLE
no events with this combination: show all past events /  hide running events

### ISSUE THREAD

**Issue by arboc** [contao/contao#6387]
### Affected version(s)

4.13.30

### Description

With the combination:
-  show all past events
-  hide running events

within the event listing module no events will be shown altough we have events in the past.

![image](https://github.com/contao/contao/assets/4447843/0d175b9e-22e6-422b-9152-5c0593bf0562)

**Comment by leofeyer** [comment]
Does this problem still occur in Contao 4.13.35?

**Comment by arboc** [comment]
unfortunately yes

**Comment by leofeyer** [comment]
How can we reproduce this?

**Comment by ausi** [comment]
I can confirm the issue.

What behavior do we want to have here?
Should the checkbox make no difference?
Or should it work the same as for the the upcoming events?

**Comment by arboc** [comment]
Just make some events in the past, that should be shown.  
And set the FE module (vent listing module) as described.

**Comment by leofeyer** [comment]
> What behavior do we want to have here? Should the checkbox make no difference? Or should it work the same as for the upcoming events?

That depends. Are running events currently shown in the "all past events" list?

**Comment by ausi** [comment]
> Are running events currently shown in the "all past events" list?

Yes, they are. 
So I guess the correct fix would be to make the checkbox work the same? Meaning only show events that have an `effectiveEndTime` is in the past if the checkbox is set?

**Comment by arboc** [comment]
agree
