### ISSUE TITLE
relative image url in schema.org jsonLd

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#6388]
### Affected version(s)

4.13

### Description

URL of images in schema.org jsonLd are relative in Contao 4.13.

Consider there is blog post in `https://example.com/blog/some-title`. And the image is located in `files/image.jpg`.

soure code of page shows `"contentUrl": "files/image.jpg"` in jsonLd.

But when checking page schema in [Schema.org](https://validator.schema.org/) it shows that image URL is:
`https://example.com/blog/files/image.jpg`!

in Contao 5, there is a `/` in the beginning of URLs and there is no problem.
`"contentUrl": "/files/image.jpg"`

**Comment by leofeyer** [comment]
@ausi What is the best way to fix this?

https://github.com/contao/contao/blob/670fefadf40fd2eeda2cd55c3734faf4665b9daa/core-bundle/src/Image/Studio/Figure.php#L136

Should we just add a `/` in front of `$this->getImage()->getImageSrc()`?

**Comment by ausi** [comment]
If we want an absolute URL:

```php
'contentUrl' => UrlUtil::makeAbsolute($this->getImage()->getImageSrc(), $request->getSchemeAndHttpHost().$request->getBasePath().'/');
```

Or if we want a path-absolute URL:

```php
'contentUrl' => UrlUtil::makeAbsolute($this->getImage()->getImageSrc(), $request->getBasePath().'/');
```

But do we have access to the request in the figure?

**Comment by fritzmg** [comment]
Imho the scheme and domain of the current request _context_ should be used. This way you will still have a valid URL when this gets generated on the command line (if you have a default scheme and domain set for the request context via the `router.request_context.…` parameters).

**Comment by Toflar** [comment]
Just an info: If we make this absolute, we have to check if https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/modules/ModuleSearch.php#L316 still works or needs adjustments too.

**Comment by ausi** [comment]
> we have to check if [`4.13`/core-bundle/src/Resources/contao/modules/ModuleSearch.php#L316](https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/modules/ModuleSearch.php?rgh-link-date=2023-09-06T14%3A33%3A59Z#L316) still works or needs adjustments too.

Yes, `FigureBuilder::fromUrl()` does handle absolute and path-absolute URLs as well, https://github.com/contao/contao/blob/4.13/core-bundle/tests/Image/Studio/FigureBuilderTest.php#L239-L285

**Comment by hamidpeywasti** [comment]
Hi, it seems that we have same problem for `url` in schema. Actually, the URL is also relative!

**Comment by fritzmg** [comment]
Yes, we need to use scheme or path absolute URLs for the schema markup in general.

**Comment by leofeyer** [comment]
> But do we have access to the request in the figure?

Nope. 🙈

**Comment by leofeyer** [comment]
> https://github.com/contao/contao/blob/670fefadf40fd2eeda2cd55c3734faf4665b9daa/core-bundle/src/Image/Studio/Figure.php#L136
> 
> Should we just add a `/` in front of `$this->getImage()->getImageSrc()`?

As discussed in the Contao call, we want to fix it like this if `getImageSrc()` does not begin with `http`. This will not work locally if Contao is in a sub-directory, but no one reads the schema.org data of local installations, so this should suffice for Contao 4.13. The issue does not occur in Contao 5.
