### ISSUE TITLE
Some routes do not work

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#64]
The following routes no longer work:

 - `http://contao.local/app_dev.php/`
 - `http://contao.local/app_dev.php/en`

@aschempp I guess that's why we had a `contao_root` route in the previous version of the front end loader?

**Comment by aschempp** [comment]
I noticed this too. However, it's not a bug in Contao 4, I found the same in Contao 3 if you have no 404-page redirecting to the language root…

**Comment by leofeyer** [comment]
I just tested it:

* `http://localhost/contao3` takes me to `http://localhost/contao3/en/` [OK]
* `http://localhost/contao3/` takes me to `http://localhost/contao3/en/` [OK]
* `http://localhost/contao3/en` takes me to `http://localhost/contao3/en/en` [NOK]

In contrast:

* `http://contao4.local/` throws a `ResourceNotFoundException` [NOK]
* `http://contao4.local/en` also throws a `ResourceNotFoundException` [NOK]

This might of course be due to an incomplete URL rewrite configuration. But couldn't we add routes to handle these cases?

**Comment by aschempp** [comment]
Also see https://github.com/contao/core/issues/7666

I never got a `ResourceNotFound`, I did get a `DieNicely` with page-not-found.

**Comment by leofeyer** [comment]
Do you have "add language to URL" enabled?

**Comment by aschempp** [comment]
I tried both. It worked just fine without, and I had the same issues with `prepend_locale: true`

**Comment by leofeyer** [comment]
That's why we had a `contao_root` route in the first version of the loader. But I'll check whether I can work around the two issues using the rewrite module of the web server.

**Comment by aschempp** [comment]
I don’t think so. The Symfony router does match the route, but Contao does not correctly handle it (at least in my case).

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/142.
