### ISSUE TITLE
Darstellungsfehler im Backend, Dateiverwaltung, Dateiupload, Button Text

### ISSUE THREAD

**Issue by Nightwing0815** [contao/contao#640]
Version 4.8.0

Im Backend in der Dateiverwaltung, Button Dateiupload, fehlt bis auf einen Buchstaben (D) die Buttonbeschreibung, siehe Bild:

![](https://user-images.githubusercontent.com/1192057/63186485-d5eb4280-c05c-11e9-8104-5c49f70d8d10.png)

Reproduziert von xchs @ Contao Forum

ToM

**Comment by fritzmg** [comment]
It seems you submitted the issue before describing it ;). Please edit in the description.

**Comment by leofeyer** [comment]
Behoben in 3a8116997f3788e32c1d4d76e20da1fc4a7668fd.
