### ISSUE TITLE
duplicate permission 'create' instead of 'delete' - maybe a mistake due to a typo

### ISSUE THREAD

**Issue by cmette** [contao/contao#6403]
### Affected version(s)

5.1.11

### Description

https://github.com/contao/contao/blob/18aa4130af8785b6427fa33e2db9ce740cd391a0/newsletter-bundle/src/Security/ContaoNewsletterPermissions.php#L21

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6416
