### ISSUE TITLE
Cannot add `target="_blank"` with `Template::figure`

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6406]
### Affected version(s)

4.13+

### Description

When using `$this->figure` within a PHP template there does not seem to be a way to add a `target="_blank"` attribute to the link.

For example when using

```php
<?=
  $this->figure(
    'files/lorem/ipsum.jpg', 
    [320, 200, 'crop'], 
    ['linkHref' => 'https://example.com', 'enableLightbox' => true]
  )
?>
```

the expectation is that the `FigureBuilder` automatically adds `target="_blank"` since the link href is an external URL. The `FigureBuilder` checks for that here:

https://github.com/contao/contao/blob/b332608c169d3bceacc98927c2cbab66bc543aa4/core-bundle/src/Image/Studio/FigureBuilder.php#L739

However, the URL is retrieved from the meta data only:

https://github.com/contao/contao/blob/b332608c169d3bceacc98927c2cbab66bc543aa4/core-bundle/src/Image/Studio/FigureBuilder.php#L722-L728

i.e. a previously called `setLinkHref` will not be taken into account and so the URL is empty. Thus instead of adding `target="_blank"`, `data-lightbox` is added.

Adding

```php
if ($href = $result->getLinkHref()) {
    return $href;
}
```

in the inline function does not work unfortunately, as this results in a recursion.

/cc @m-vo

**Comment by ausi** [comment]
So the following check does not work correctly?

https://github.com/contao/contao/blob/b332608c169d3bceacc98927c2cbab66bc543aa4/core-bundle/src/Image/Studio/FigureBuilder.php#L705-L708

**Comment by fritzmg** [comment]
`$result->hasLightbox()` returns `true`. `hasLightbox` subsequently executes `FigureBuilder::onDefineLightboxResult` where `$getMetadataUrl` returns `null` - and thus a lightbox image is created.

**Comment by ausi** [comment]
I see...

So the correct fix might be to add the following check to the beginning of the `FigureBuilder::onDefineLightboxResult`?

```php
if (isset($this->additionalLinkAttributes['href'])) {
    return null;
}
```

**Comment by fritzmg** [comment]
I don't think so, the checks within `$getResourceOrUrl` should still take place. Because if you do something like this:

```php
<?=
  $this->figure(
    'files/lorem/ipsum.jpg', 
    [320, 200, 'crop'], 
    ['linkHref' => 'files/lorem/ipsum.jpg', 'enableLightbox' => true]
  )
?>
```

it should still open a lightbox.

I guess we could add

```php
if ($href = ($this->additionalLinkAttributes['href'] ?? null)) {
    return $href;
}
```

to `$getMetadataUrl` though.

**Comment by ausi** [comment]
I think the href attribute should be the first here then:

https://github.com/contao/contao/blob/b332608c169d3bceacc98927c2cbab66bc543aa4/core-bundle/src/Image/Studio/FigureBuilder.php#L763-L764

like so:

```php
$lightboxResourceOrUrl = $this->additionalLinkAttributes['href'] ?? $this->lightboxResourceOrUrl ?? $getMetadataUrl() ?? $this->filePath;
```

**Comment by fritzmg** [comment]
Not sure - isn't the intention of `FigureBuilder::setLightboxResourceOrUrl` to override the URL no matter what?

**Comment by ausi** [comment]
> Not sure - isn't the intention of `FigureBuilder::setLightboxResourceOrUrl` to override the URL no matter what?

I don’t think so, if you set it to `https://example.com/` it gets ignored because it does not have a valid image file extension. To me `lightboxResourceOrUrl` is meant for images only, but `linkHref` ist meant for external non-image-URLs as well.

**Comment by fritzmg** [comment]
Closing in favor of #6419
