### ISSUE TITLE
`doctrine/dbal: 3.7.0` causes performance issue with `contao:migrate`

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6409]
### Affected version(s)

4.13.x, 5.x

### Description

`doctrine/dbal: 3.7.0` was released recently and this causes an issue with some fields of the `tl_remember_me` entity. The following queries always want to be executed when updating the database:

```
* ALTER TABLE tl_remember_me CHANGE value value BINARY(64) NOT NULL COMMENT '(DC2Type:binary_string)'
* ALTER TABLE tl_remember_me CHANGE series series BINARY(32) NOT NULL COMMENT '(DC2Type:binary_string)'
```

Also the performance of `contao:migrate` degrades significantly with `doctrine/dbal: 3.7.0` (at least in my environment). With `3.6.x` it takes around 2 seconds - and now around __260 seconds__.

**Comment by ausi** [comment]
Should we debug the cause and report it to doctrine?
And in the meantime add a conflict to contao/conflicts?

**Comment by m-vo** [comment]
@fritzmg Could you maybe checkout the sources of `doctrine/dbal` and do a `git bisect`? IIRC there were some changes to binary stuff recently but I could not find the respective commits/PRs...

**Comment by ausi** [comment]
> Also the performance of `contao:migrate` degrades significantly with `doctrine/dbal: 3.7.0` (at least in my environment). With `3.6.x` it takes around 2 seconds - and now around **260 seconds**.

What did you test here exactly?
Was the migration that took 2 seconds without any queries? If so, you need to use `--no-backup` to compare the times I think.

**Comment by ausi** [comment]
The cause seems to be https://github.com/doctrine/dbal/commit/04c3330dcf55a232dede0b467394b35ee46e520a from https://github.com/doctrine/dbal/pull/5916

If I remove the following lines the issue disappears: https://github.com/doctrine/dbal/blob/00d03067f07482f025d41ab55e4ba0db5eca2cdf/src/Platforms/AbstractPlatform.php#L4637-L4639

**Comment by fritzmg** [comment]
> What did you test here exactly?

A few runs of `contao:migrate --no-interaction --no-backup` with 3.6.x and a few runs with 3.7.0. 3.6.x takes always 2 seconds, 3.7.0 always around 260 seconds.

**Comment by ausi** [comment]
I created a PR in doctrine/dbal to fix the diff issue: https://github.com/doctrine/dbal/pull/6168

@fritzmg can you check if this also resolves the performance problem as I was not able to reproduce that?

**Comment by fritzmg** [comment]
The performance issue is still there (still around 260 seconds every time). One thing to note is that my test database has a lot of fields and tables that can be dropped (which I never drop). Can you may be reproduce it with the following `composer.json` and MySQL dump?

```json
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Managed Edition",
    "license": "LGPL-3.0-or-later",
    "require": {
        "contao/contao": "4.13.x-dev",
        "doctrine/dbal": "3.7.x-dev as 3.7.99"
    },
    "conflict": {
        "contao-components/installer": "<1.3",
        "league/commonmark": ">=2.3"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "@php vendor/bin/contao-setup"
        ]
    },
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "contao-components/installer": true,
            "contao-community-alliance/composer-plugin": true,
            "contao/manager-plugin": true,
            "php-http/discovery": false
        }
    }
}
```

[c413-empty.zip](https://github.com/contao/contao/files/12764487/c413-empty.zip)

**Comment by de-es** [comment]
Kann die Performance-Problematik bestätigen. Getestet mit: Contao 4.13.31 lokale Demoinstallation, PHP 8.2, MariaDB 11.1.

Downgrade von `doctrine/dbal` von 3.7.1 auf 3.6.7 behebt das Problem wieder.

**Comment by ausi** [comment]
> Can you may be reproduce it with the following `composer.json` and MySQL dump?

I was not able to reproduce it using your dump. I tested it with 3.6.7, 3.7.0 and 3.7.1 and `contao:migrate --no-interaction --no-backup` always took about 1.2 seconds (with an empty cache).

> Kann die Performance-Problematik bestätigen. Getestet mit: Contao 4.13.31 lokale Demoinstallation, PHP 8.2, MariaDB 11.1.

@fritzmg are you also using MariaDB 11? I tested it on a MySQL 8.0.33 server. **UPDATE:** tested it with MariaDB 11.1 now too, but I was still not able to reproduce it.

**Comment by ausi** [comment]
> Kann die Performance-Problematik bestätigen.

@de-es Wie stark ändert sich die performance, also wie viele sekunden dauert der `migrate` command mit 3.6.7 im Vergleich zu 3.7.1?

**Comment by de-es** [comment]
@ausi 2sec vs. 6min 45sec mit `contao:migrate --no-interaction --no-backup`

**Comment by ausi** [comment]
@de-es on which operating system? Windows?

**Comment by de-es** [comment]
@ausi (Arch) Linux

**Comment by fritzmg** [comment]
MariaDB 10.8.3 under Windows in my case.

**Comment by fritzmg** [comment]
Same issue with MariaDB 11.1.2 under Windows in my case.

**Comment by fritzmg** [comment]
We have tracked down the performance issue to https://github.com/doctrine/dbal/commit/b7b4870947e49ef26c2054cbc89078bf6fe949c9

This affects all MariaDB instances starting with MariaDB 10.4.3. The issue is that MariaDB still has no native support for a `JSON` datatype - however instead it aliases the `JSON` datatype to `LONGTEXT`, plus it adds a check constraint (https://jira.mariadb.org/browse/MDEV-13916). So for Doctrine to know whether a field is actually `JSON` under MariaDB 10.4.3+, it has to query `information_schema.CHECK_CONSTRAINTS` - this however can be very, very slow because any such unrestricted query always scans _all_ tables of _all_ databases. So if, in your local setup for example, the used database user has access to a lot of databases with a lot of tables this issue becomes more apparent.

Doctrine's current query uses a `JOIN` which is technically restricted - but still happens to scan all tables of all databases for unknown reasons. @ausi is working on a PR to fix that.

MySQL 8 is not affected because they were able to completely overhaul this - while MariaDB still relies on the old, slow implementation of `information_schema` (see https://jira.mariadb.org/browse/MDEV-11655).

**Comment by ausi** [comment]
> @ausi is working on a PR to fix that.

See https://github.com/doctrine/dbal/pull/6202

**Comment by ausi** [comment]
@de-es it would be great if you could verify that the fix works on your system too.

**Comment by de-es** [comment]
@ausi Ja, funktioniert nun wieder einwandfrei. Vielen Dank für den Fix. :+1:

**Comment by de-es** [comment]
3.7.2 was released.
