### ISSUE TITLE
Allow imagine-class independent WEBP conversion

### ISSUE THREAD

**Issue by MarkejN** [contao/contao#641]
**Description**  
I wanted to test the new webp image conversion feature in 4.8.0 on an All-Inkl Server where both Imagick (w/o webp support) and Gd (w/ webp support) were enabled.
Contao chose Imagick over Gd for its imagine class and therefore displayed that webp is not supported on my server. Now it was necessary to manually configure Gd as the imagine class in the config.yml for it to work.

Is it possible and reasonable to let the webp conversion part automatically determine and use a fitting conversion method independently of the imagine class that Contao chose?

**Comment by ausi** [comment]
No. The imagine class is the one who resizes and saves the image in the WEBP format. Doing the resize in a different imagine implementation than the WEBP encoding is not easily possible.

**Comment by aschempp** [comment]
Should we chose GD over Imagine if what's described is the case?

**Comment by fritzmg** [comment]
Why does your server environment not have webp support in Imagick?

**Comment by fkaminski** [comment]
Just for info:
Same with local installations via Docker/devilbox.org. Both gd and imagick are present within the PHP 7.x images but only gd supports WebP. With configure the config/config.yml like

```
contao:
    image:
        imagine_service: 'contao.image.imagine.gd'
```
it works for now. I leave a feature request for the devilbox so:
https://github.com/cytopia/devilbox/issues/619

**Comment by ausi** [comment]
> Should we chose GD over Imagine if what's described is the case?

I don’t think so.

**Comment by MarkejN** [comment]
> Why does your server environment not have webp support in Imagick?

I wrote All-Inkl about this. Maybe they plan to change this in the future.

WebGo seems to have the same setup.

**Comment by leofeyer** [comment]
You can overwrite the default Imagine service in your `config.yml` like this:

```yaml
contao:
    image:
        imagine_service: 'contao.image.imagine.gd'
```

Since there is nothing more to do on our side, I am closing the ticket.
