### ISSUE TITLE
Error with eval 'path' in file picker

### ISSUE THREAD

**Issue by zonky2** [contao/contao#6412]
### Affected version(s)

4.13.30

### Description

When I restrict the `path` in a DCA,

```
$GLOBALS['TL_DCA'][$strTblName]['fields']['mcwtest1'] =
    [
        'exclude'   => true,
        'inputType' => 'multiColumnWizard',
        'eval'      => [
            'minCount'     => 3,
            'maxCount'     => 5,
            'columnFields' => [
                'col_image'   => [
                    'label'     => 'Grundriss',
                    'exclude'   => true,
                    'inputType' => 'fileTree',
                    'eval'      => [
                        'fieldType'  => 'radio',
                        'files'      => true,
                        'filesOnly'  => true,
                        'extensions' => \Contao\Config::get('validImageTypes'),
                        'mandatory'  => true,
                        'path'       => 'files/content/images',
                    ],
                ],
...
```

At first, we see image 1:

![bug_0](https://github.com/contao/contao/assets/1045318/cd003f37-4035-4974-ab8e-6efc4b050d45)

the following errors result:

* if one clicks on a (sub)folder, no more files are displayed (image 1).
* if you click on a level in the breadcrumb that is higher than the given path, nothing is shown anymore (picture 2)

Current workaround: if you know some of the image names, the search still works...

Image 2
![bug_1](https://github.com/contao/contao/assets/1045318/42188d18-169f-4b4c-83db-c4c8c2604dbe)

Image 3
![bug_2](https://github.com/contao/contao/assets/1045318/5b9697f7-2ff0-4f7e-b682-40e93b963d66)

**Comment by asaage** [comment]
first image = image 0 😂

What was your selected bredcrumb/current-dir in the filemanager beforehand?
I suspect it is related to an issue i experienced [here](https://github.com/isotope/core/issues/2469)

**Comment by zonky2** [comment]
see the `path` value: `files/content/images`

Image 0 : I thought somewhere the filenames are output... the first one starts with 0 ;-)

**Comment by asaage** [comment]
> see the `path` value: `files/content/images`

I dont mean your dca setting but the thing that is stored in session (or localstorage) when you go to the filemanager and click on the folder-icon of `files/othercontent` so it is displayed in the breadcrumb.
Is your fileTree-Input then able to show something from `files/content/images`?

**Comment by ausi** [comment]
Does this issue also appear if you do not use the `multiColumnWizard` widget?

**Comment by zonky2** [comment]
the same behavior occurs with MetaModels - there you can specify a starting point at file attribute

https://community.contao.org/de/showthread.php?85973-Kann-in-den-MMs-keine-Files-Bilder-erg%C3%A4nzen

I used the MCW to exclude MM or DCG and because it was easy to build a test case... with RST-CE this is surely also possible

**Comment by zonky2** [comment]
same bug at Contao (testet on C 4.13.34)

change at `tl_content.php` https://github.com/contao/contao/blob/8114301bc2ef7bedd90dcc5afc9ee634cd526dd2/core-bundle/src/Resources/contao/dca/tl_content.php#L246-L256
and set your own `path`

```
        'singleSRC' => array
        (
            'exclude'       => true,
            'inputType'     => 'fileTree',
            'eval'          => array(
                'filesOnly'  => true,
                'fieldType'  => 'radio',
                'extensions' => \Contao\Config::get('validImageTypes'),
                'mandatory'  => true,
                'tl_class'   => 'clr',
                'path'       => 'files/content/images'
            ),
            'load_callback' => array
            (
                array('tl_content', 'setSingleSrcFlags')
            ),
            'sql'           => "binary(16) NULL"
        ),
```

**Comment by zonky2** [comment]
hat den jemand den Bug auf dem Schirm? insgesammt etwas misslich für die Usability ohne mögliche Vorauswahl :(

**Comment by leofeyer** [comment]
The issue only occurs if the file manager breadcrumb menu is active:

<img width="450" alt="" src="https://github.com/contao/contao/assets/1192057/17fd6ba3-be1b-4667-bd8d-c4ff82cf53a0">

<img width="467" alt="" src="https://github.com/contao/contao/assets/1192057/c41fc8a7-292c-40f6-9f2c-0dc97336a18c">

---

<img width="325" alt="" src="https://github.com/contao/contao/assets/1192057/f4236e7c-864b-4ba5-84b8-aca7d82d773d">

<img width="539" alt="" src="https://github.com/contao/contao/assets/1192057/db26c458-2a69-4d7f-9a77-d77bbf4b6a67">

@contao/developers How do we solve this?

**Comment by leofeyer** [comment]
As discussed in the Contao call, if the breadcrumb value is outside the given path, the path should be shown.
