### ISSUE TITLE
Incorrect routing "Page Not Found" page on root without "URL prefix" in multilingual website

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#6415]
### Affected version(s)

*

### Description

In multilingual website that one of website roots has no **URL prefix**, 404-error Page return article from other languages.

for example if there is a website with two languages:
https://example.de/        => (Website in German - **without any Prefix**)
https://example.de/en    => (Website in English - with `en` prefix

and both of root has their own page-not-found pages.

But `https://example.de/404-error` return articles (contents) from English website root page-not-foud articles.

If both roots have **URL Prefix**, there will be no problem.

I think this problem maybe will occur in other Error Pages, But I don't check.

**Comment by fritzmg** [comment]
You mean `https://example.de/does-not-exist` shows the 404 page of the _English_ website root?

**Comment by hamidpeywasti** [comment]
@fritzmg Yes

Real Case:
https://respinar.com/not-exist
https://respinar.com/en/not-exist
https://respinar.com/de/not-exist

**Comment by hamidpeywasti** [comment]
This problem occurs only for URLs that the first part does not exist.
That mean if there is a page such "https://example.com/about".
If we try "https://example.com/about/not-exist", it will return correct error-page.

**Comment by aschempp** [comment]
what error page would you expect? Since a page does not exist, it will try to locate your language and show what is preferred by your browser.

**Comment by fritzmg** [comment]
> Since a page does not exist, it will try to locate your language and show what is preferred by your browser.

But that should only be the case if the URL is ambiguous in regards to the website root. In this case any URL without a prefix should always display the 404 page of the `de` website root and any URL with the `en/` prefix should always display the 404 page of the `en` website root.

**Comment by hamidpeywasti** [comment]
@aschempp OK, You are right.

But suppose that preferred language is English. The website has two two languages DE (without prefix) and EN (en prefix).

DE: https://exmple.com/not-exit -> returns 404-error-page from preferred language **EN** root.
DE: https://exmple.com/about/not-exist -> returns 404-error-page from **DE** root (not preferred).

EN: https://exmple.com/en/not-exit -> returns 404-error-page from **EN** root.

Does routing choose the preferred language or the root language at all?

**Comment by asaage** [comment]
So you have **en** as fallback-language but the **de** website-root without prefix?
I think that's an edge-case. I'd rather use proper subdomains, consistent url-prefixing or another fallback-language.

**Comment by hamidpeywasti** [comment]
@asaage I didn't consider fallback-language.

**Comment by aschempp** [comment]
> But that should only be the case if the URL is ambiguous in regards to the website root. In this case any URL without a prefix should always display the 404 page of the `de` website root and any URL with the `en/` prefix should always display the 404 page of the `en` website root.

Not sure that make sense. You could also have no language prefix on both root pages, as long as the aliases don't collide. Not sure investigating this is worth the effort 😇

**Comment by fritzmg** [comment]
> You could also have no language prefix on both root pages, as long as the aliases don't collide.

Yes, in that case it is ambiguous. But in the case of this ticket it would not be ambiguous.
