### ISSUE TITLE
Bei Nutzung vordefinierter Größen keine Auswahl bestehender Bildgrößen Formate möglich

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#642]
**Affected version(s)**
Contao 4.8

**Description**  
As mentioned in the samples on #537 and https://contao.org/de/news/contao_4-8-0.html i get an error when using "cssClass: ''xyz" within the "items" section after cache clear in the CM like:

> Unrecognized option "cssClass" under "contao.image.sizes.foobarA.items.0". 
> Available options are "densities", "height", "media", "resizeMode", "sizes" 
> , "width", "zoom".

By removing this entry from the "items" section it will work 
So maybe you could update the samples.

Anyway. 
When i have one or more predefined entries i could not use the other entries like "Propotional", "Am Rahmen anpassen" etc. anymore. They will no longer be accepted.

**How to reproduce**  
- Setup config/config.yml
- Cache clear with CM/contao-console
- Try to use "Bildgröße/Proportional"

**Comment by ausi** [comment]
> By removing this entry from the "items" section it will work
> So maybe you could update the samples.

I agree, this should be updated.

> When i have one or more predefined entries i could not use the other entries like "Propotional", "Am Rahmen anpassen" etc. anymore. They will no longer be accepted.

I was not able to reproduce that. “Bildgröße/Proportional” worked as expected in my test. How does your *config.yml* look like?

**Comment by fkaminski** [comment]
Leave my sample in the forum:
https://community.contao.org/de/showthread.php?75736-Fragen-(-Sammlung-)-zu-den-neuen-Features&p=509148&viewfull=1#post509148
Maybe it is a formatting issue in the .yml?

**Comment by fkaminski** [comment]
Maybe is has nothing to do with the config/config.yml. 

I delete the config file, clear the cache via contao-console and still can not select eiher "Proportional", "Am Rahmen anpassen" etc.. So i can not select these at all.

Tested in two fresh 4.8 Installations, no bundles  ( local via Docker/devilbox and via hoster hostingwerk ).

**Comment by ausi** [comment]
What exactly means “can not select” in this case? Do you get an error message? Can you post a screenshot of the problem?

**Comment by fkaminski** [comment]
![contao-#642](https://user-images.githubusercontent.com/7679799/63224994-3e0c6680-c1cc-11e9-9c17-8859b61e0f4e.gif)

**Comment by ausi** [comment]
You have to also set the width and/or height if you select one of the manual sizes.

**Comment by fkaminski** [comment]
Sorry - better do not work on weekends. Works like charm:

![contao-#642-2](https://user-images.githubusercontent.com/7679799/63225158-cd664980-c1cd-11e9-8e94-d90ba863a4d9.gif)

**Comment by ausi** [comment]
🙃
