### ISSUE TITLE
FAQ : Call to a member function getAbsoluteUrl() on null

### ISSUE THREAD

**Issue by luger95** [contao/contao#6421]
### Affected version(s)

4.13.30

### Description

When you save a question in the FAQ module, the following error appears: "Call to a member function getAbsoluteUrl() on null".

LOG :

> request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function getAbsoluteUrl() on null" at /var/cache/prod/contao/dca/tl_faq.php line 278 {"exception":"[object] (Error(code: 0): Call to a member function getAbsoluteUrl() on null at /var/cache/prod/contao/dca/tl_faq.php:278)"} []

**Comment by fritzmg** [comment]
Please use the debug mode and post the full stack trace.
