### ISSUE TITLE
Datenbank-Problem gefunden

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#6424]
### Affected version(s)

4.13.31

### Description

![Bildschirmfoto 2023-10-09 um 15 39 32](https://github.com/contao/contao/assets/1942550/7d1b1683-1a7b-4c4c-a1b6-fcac75f2d13f)

Bei einigen Aktualisierungen auf 4.13.31 werde ich im Contao Manager darauf hingewiesen, dass ein Datenbank-Problem gefunden worden ist und ich doch bitte das Install-Tool öffnen soll. Ich öffne das Install-Tool und führe die Datenbankmigration ohne Probleme durch. Die Meldung im Contao Manager bleibt gleich. 

In einer Installation habe ich dann die folgende Zeile gelöscht und den Cache neu aufgebaut.

`database_version: 10.3.34-MariaDB-0+deb10u1-log`

Danach war wieder alles in Ordnung.

**Comment by CMSworker** [comment]
Got a similar problem. I first had updated Contao Manager to version 1.7.1

After that I installed the Update from Contao 5.2.2 to 5.2.3 and after that the Manager stated the database problem.

![db-problem](https://github.com/contao/contao/assets/31544192/45ad02aa-2a82-4f9f-862f-749c01805455)

It looks like the "+" is ignored in the check of the database config (MariaDB version 10.4.28 should be covered when "MariaDB 10.2.7+" is selected in the database settings of the Contao Manager)

@netzarbeiter Where should the line be deleted you stated at the end of your post?

Edit: Looks like I'm now stuck in the Contao Manager and can only access database settings or the Safe Mode with restricted functionality...

![Manager-Abgesichert](https://github.com/contao/contao/assets/31544192/6c14ec2c-6686-4f98-be74-f41175e059a4)

**Comment by no-one** [comment]
Also reported here: https://community.contao.org/de/showthread.php?85807-quot-Falsche-quot-MariaDB-Version-nach-Update

**Comment by fritzmg** [comment]
Starting with the next Contao 4.13 release, the database version will not be set by the install tool anymore (see https://github.com/contao/contao/pull/6425).

Furthermore, starting with Contao Manager version 1.8, the database version will also not be set anymore by the Contao Manager. And if you set the the database credential via the Contao Manager again (even in 4.13), the database version will not be set anymore, even if you previously set it via the `parameters.yml` (via the Install Tool for example).

**Comment by leofeyer** [comment]
If you have this issue, you either have to 

1) adjust your `parameters.yml` file and remove the `database_version:` entry or

2) adjust your `.env.local` file and remove the `?serverVersion=` part of the `DATABASE_URL`.

Then rebuild the cache and the issue should be gone.

**Comment by aschempp** [comment]
You can fix your local issue by updating the database URL in your Contao Manager. I would say we can fix this issue then 😊
