### ISSUE TITLE
Image full-size view not working with unpublished folder

### ISSUE THREAD

**Issue by ThomasKettner** [contao/contao#6428]
### Affected version(s)

4.13

### Description

We have images stored in an unpublished folder in order to avoid general public access.
We use the image sizes function when publishing these images in a specific format / resolution.
The images are generated correctly and stored in the public assets folder as expected.

But when activating the full-size view, the original path is being used. Thus the full-size image can not be found because of the unpublished folder.

Why not use the assets path of the generated image?

**Comment by fritzmg** [comment]
You need to set a lightbox image size in your layout to achieve that.

**Comment by ThomasKettner** [comment]
shame on me, long forgotten features...
have found the discussion to this issue: [https://github.com/contao/contao/issues/545](url)
Doesn't seem very logical to me to configure image sizes in different places. But no need to open a new discussion in this thread. Thx

**Comment by fritzmg** [comment]
> Doesn't seem very logical to me to configure image sizes in different places

What do you mean by that?

**Comment by ThomasKettner** [comment]
https://github.com/contao/contao/issues/545#issuecomment-1756842768

**Comment by fritzmg** [comment]
Your comment there does not really answer my question ;)
