### ISSUE TITLE
Error when opening the filepicker in the backend.

### ISSUE THREAD

**Issue by markocupic** [contao/contao#643]
Contao 4.8

I get this error when trying to embed a gallery in the contao backend. When opening the filepicker I get this error. The installation was updated from Contao 4.7 to version 4.8.
 
ErrorMsg: "The X coordinate plus the width must not be greater than 1"

I've got an other 4.8 installation and there the error doesn't occur.

See: https://community.contao.org/de/showthread.php?75740-Dateiverwaltung-funktioniert-nach-Update-auf-Contao-4-8-nicht-mehr&p=509159#post509159

**Comment by BugBuster1701** [comment]
My Installation was updated from 4.8.RC1 or 2 (I don't know.) to 4.8.0

"X, Y, width and height must be a float between 0 and 1"

```
[2019-08-17 17:45:13] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: 
"X, Y, width and height must be a float between 0 and 1" 
at /contao48.contaodev/vendor/contao/image/src/ImportantPart.php line 40
 {"exception":"[object] (InvalidArgumentException(code: 0): 
X, Y, width and height must be a float between 0 and 1 
at /contao48.contaodev/vendor/contao/image/src/ImportantPart.php:40)"} []
```

Edit: The file management also cannot be opened without errormessage, therefore it is not possible to save the important part again. 

Edit: I have one picture with this values:
```
importantPartX 	importantPartY 	
266 	        133
```

**Comment by xchs** [comment]
> therefore it is not possible to save the important part again

Why not? Just set the important part of the image again:

* Open your user "_Profile_"
* Disable the "_Show thumbnail images_" setting and save the profile data
* Open the "_File manager_"
* Edit an image file
* Mark the important part of the image and save

**Comment by BugBuster1701** [comment]
- Edit an image file: the same Error

**Comment by fritzmg** [comment]
Having to set the important part for all images again shouldn't be the solution.

**Comment by xchs** [comment]
Of course not!

**Comment by BugBuster1701** [comment]
My Hack: https://community.contao.org/de/showthread.php?75740-Dateiverwaltung-funktioniert-nach-Update-auf-Contao-4-8-nicht-mehr&p=509171&viewfull=1#post509171

**Comment by ausi** [comment]
The error messages are probably related to a failed database update. How the important part should be updated can be seen in the update script: https://github.com/contao/contao/blob/879e05ecc75a6bf70aabc1c3d867eb420f291f60/installation-bundle/src/Database/Version480Update.php#L124-L166

If you run that code manually it should fix the values and the error should go away.

**Comment by ausi** [comment]
Pull request to fix the issue that the filemanager can no longer be opened: #645

**Comment by markocupic** [comment]
Ok. Under thousands of jpeg/jpg files I found two files where the value of "importantPartX" and "importantPartWidth" were set to 1. 

To solve the problem, I've set both values to 0.

**Comment by leofeyer** [comment]
See #645.

**Comment by Wedego** [comment]
Hi all, the same Problem on Contao 4.8.7 today:
  Stack Trace 
Stack Trace 

InvalidArgumentException

InvalidArgumentException:
The Y coordinate plus the height must not be greater than 1

  at vendor/contao/image/src/ImportantPart.php:58
  at Contao\Image\ImportantPart->__construct(0.11846153846154, 0.63076923076923, 0.62538461538462, 0.73269230769231)
     (vendor/contao/core-bundle/src/Image/ImageFactory.php:366)
  at Contao\CoreBundle\Image\ImageFactory->createImportantPart(object(Image))
     (vendor/contao/core-bundle/src/Image/ImageFactory.php:161)
  at Contao\CoreBundle\Image\ImageFactory->create('/var/www/vhosts/ xxxxxxxxx  .de/httpdocs/files/wetogo/images/5.jpg', array(100, 75, 'box'))
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php:2788)
  at Contao\DC_Folder->generateTree('/var/www/vhosts/ xxxxxxxxx  .de/httpdocs/files/wetogo/images', 40, false, false, false, array())
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php:2726)
  at Contao\DC_Folder->generateTree('/var/www/vhosts/ xxxxxxxxx  .de/httpdocs/files/wetogo', 20, false, false, false, array())
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php:2726)
  at Contao\DC_Folder->generateTree('/var/www/vhosts/ xxxxxxxxx  .de/httpdocs/files/wetogo', 0, true, false, false, array())
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php:405)
  at Contao\DC_Folder->showAll()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:630)
  at Contao\Backend->getBackendModule('files', object(Picker))
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:161)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:50)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:31)
  at require('/var/www/vhosts/ xxxxxxxxx  .de/httpdocs/web/index.php')
     (web/app.php:4)

**Comment by Wedego** [comment]
Erledigt:
ich habe von hier: https://github.com/ausi/contao-conta...ageFactory.php
die "ImageFactoty.php" genommen und bei mir ausgetauscht. Danach ist alles ok bis jetzt.
Danke fürs Lesen.
