### ISSUE TITLE
Einstellung Skripte komprimieren

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#644]
Im Backend wird bei der Einstellung "Skripte komprimieren" die Erläuterung _"Eine komprimierte Version der kombinierten CSS- bzw. JavaScript-Dateien erstellen. Erfordert die Anpassung der .htaccess-Datei."_ angezeigt.

Im Gegensatz zu Contao 3 ist bei Contao 4.4.42 in der .htaccess-Datei jedoch kein Codeblock vorhanden, der hierfür einkommentiert werden kann.

**Comment by fritzmg** [comment]
Du musst es selbst konfigurieren. Die default .htaccess von Contao 4 hat generell nicht mehr so viel Voreinstellungen wie Contao 3 (zB Cache Times).

**Comment by Mynyx** [comment]
Dass die .htaccess-Datei die Funktionen des Contao Core-Bundle unterstützt, wäre allerdings schon sinnvoll? Ein Neuling würde wohl kaum auf die Idee kommen, sich die Konfigurationen aus Contao 3 herauszusuchen.

Im Gegensatz dazu sind die zusätzlichen Cache-Konfigurationen für die vollständige Funktionalität des Core nicht notwendig.

**Comment by leofeyer** [comment]
Die Einstellung ist sowieso deprecated und wurde in Contao 4.7 entfernt.
