### ISSUE TITLE
Syntax highlighting dropdown list in code element not complete

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#6440]
### Description

Im Code-Element im Backend fehlt bei der Syntaxhervorhebung "Twig".
Das kann man über eine DCA-Anpassung nachrüsten, dazu muss man allerdings auch wissen, dass die Sprache zur Verfügung steht. Danke an Moritz für die entsprechende DCA-Anpassung.
Ich denke allerdings, dass es schön wäre die Auswahl grundsätzlich zur Verfügung zu haben.

**Comment by m-vo** [comment]
Here are the languages supported by our highlighter by default: https://highlightjs.readthedocs.io/en/latest/supported-languages.html (the ones with an empty "package" column in the table).

I wonder if we should just add `twig` or more or all of the above?

**Comment by leofeyer** [comment]
Please only add `twig`.

**Comment by m-vo** [comment]
See #6444
