### ISSUE TITLE
Simplification of the component template _headline.html.twig

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#6441]
### Description

Wie mit Moritz besprochen scheint eine Vereinfachung des Komponenten-Templates `_headline.html.twig` möglich zu sein.
Statt
```
{%- block headline_inner %}    
  {%- apply spaceless %}        
   {{ headline.text|insert_tag|raw }}    
  {% endapply -%}
{% endblock -%}
```
müsste man mit
```{%- block headline_inner %}{{ headline.text|insert_tag|raw }}{% endblock -%}```
Ebenfalls korrekt alle Whitespaces behandeln können.

**Comment by ausi** [comment]
Ich würde es aber für die bessere Übersicht dennoch in drei Zeilen schreiben:

```twig
{%- block headline_inner -%}
  {{ headline.text|insert_tag|raw }}
{%- endblock -%}
```

**Comment by m-vo** [comment]
See #6443
