### ISSUE TITLE
Simplifying working with HTML attributes in Twig templates

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#6442]
### Description

Ausgangspunkt ist die Lösung des Problems:
Für ein Logo soll beim Link als alternativer Text und als Bildtitel der Insertag `{{page::rootPageTitle}}` verwendet werden.
Dazu ist eine Anpassung des Twig-Templates erforderlich.
Die Anpassung des entsprechenden Komponenten-Templates erfordert derzeit ein komplettes Überschreiben des gesamten Blocks.

```
{# templates/component/_picture.html.twig #}

{% use "@Contao/component/_picture.html.twig" %}


        {% block image %}
            {% set img = figure.image.img %}
            {% set defineProportions = img.width|default(false) and img.height|default(false) %}
            {% set img_attributes = attrs(img_attributes|default)
                .set('src', img.src)
                .set('alt', figure.hasMetadata ? figure.metadata.alt|insert_tag : '')
                .setIfExists('title', figure.hasMetadata ? (figure.metadata.title|insert_tag ?: null) : null)
                .setIfExists('srcset', img.srcset is defined and img.srcset != img.src ? img.srcset : null)
                .setIfExists('sizes', img.sizes|default)
                .setIfExists('width', defineProportions ? img.width : null)
                .setIfExists('height', defineProportions ? img.height : null)
                .setIfExists('loading', img.loading|default)
                .addClass(img.class|default)
                .mergeWith(figure.options.img_attr|default)
            %}
            <img{{ img_attributes }}>
        {% endblock %}
```

Moritz, sieht mehrere Möglichkeiten das eventuell zu vereinfachen bzw. zu verbessern:

> Das Problem hat man derzeit immer, wenn man entweder konkrete Werte anders belegen oder sie komplett entfernen will. Das liegt einfach daran, dass die Templates, die andere überschreiben (= höher in der Hierarchie) zwangsläufig immer vor ihren Parents ausgeführt werden, die Logik zum Setzen der Werte aber in den Parents steckt. Daher kommt auch das "set and merge" Pattern (set a = attrs(a|default)) .
> Ich sehe mehrere Möglichkeiten das Verhalten zu verbessern:
> 
> 1. Wir ändern das Pattern von attributes = attrs(attributes|default).<stuff> zu attributes = attrs().<stuff>.mergeWith(attributes|default), sodass zuvor gesetzte Werte immer gewinnen.
> 2. Wir fügen der HtmlAttributes Klasse Methoden/Flags hinzu, um eine Änderung als "important" zu markieren, bzw. ein Überschreiben zu erzwingen. Damit können dann auch Werte gewinnen, die zuvor gesetzt waren.
> 3. Oder analog: Wir fügen der HtmlAttributes Klasse Methoden/Flags hinzu, um Sachen zu setzen, falls diese noch nicht gesetzt sind.

> (In der Zukunft könnte ich mir auch vorstellen attrs() zu einem Tag machen ({% attrs %}) und die Inhalte dann zu parsen - dann könnte man alle möglichen Optimierungen auch schon zu Compile-Zeit machen, wie etwa automatische "|default" Werte für setIfExist und Konstruktor u.s.w. Und auch dabei gäb es vermutlich Möglichkeit das Problem anzugehen. Aber ich glaube wir brauchen etwas kurzfristigeres…)

**Comment by hendrikbengs** [comment]
Ich bin über den Slack-Thread hier gelandet und dächte das die Info hier mit hineinpassen könnte.

Und zwar nutze ich gern [AlpineJS](https://alpinejs.dev/). Die Kombination von AlpineJS und Twig (HtmlAttributes) ist an der Stelle eigentlich ideal. Probleme treten aber dann auf, wenn z.B. Attribute wie `@click="foo"` oder `x-bind:class="bar"` gesetzt werden sollen. Es wird dann folgende Fehlermeldung ausgegeben:

```
A HTML attribute name must only consist of the characters [a-z0-9_-], must start with a letter, must not end with a underscore/hyphen and must not contain two underscores/hyphens in a row
```

Es wäre schön wenn für diese speziellen Anwendungsfälle eine Ausnahme möglich wäre?!

**Comment by m-vo** [comment]
@hendrikbengs Kannst du dafür ein neues Issue aufmachen?

**Comment by m-vo** [comment]
We should probably also consider removing the attribute related blocks then to further simplify the templates... These are only there to completely overwrite the default attributes, what is then possible within the attribute system itself.

**Comment by leofeyer** [comment]
> Wir ändern das Pattern von attributes = attrs(attributes|default). zu attributes = attrs()..mergeWith(attributes|default), sodass zuvor gesetzte Werte immer gewinnen.

As discussed in the Contao call, this is what we want to do. @m-vo will take create a pull request.
