### ISSUE TITLE
Special characters with HTML attributes in Twig templates

### ISSUE THREAD

**Issue by hendrikbengs** [contao/contao#6445]
### Description

Siehe #6442

Ich nutze gern [AlpineJS](https://alpinejs.dev/). Die Kombination von AlpineJS und Twig (HtmlAttributes) ist eigentlich ideal. Probleme treten aber dann auf, wenn z.B. Attribute wie `@click="foo"` oder `x-bind:class="bar"` gesetzt werden sollen. Es wird dann folgende Fehlermeldung ausgegeben:

```
A HTML attribute name must only consist of the characters [a-z0-9_-], must start with a letter, must not end with a underscore/hyphen and must not contain two underscores/hyphens in a row
```

Es wäre schön wenn für diese speziellen Anwendungsfälle eine Ausnahme möglich wäre?!

**Comment by ausi** [comment]
Anscheinend unterstüzt AlpineJS leider keine vollständig valide HTML5 Syntax. ( https://github.com/alpinejs/alpine/issues/433 )

Ich denke der Einfachkeit halber sollten wir wohl einfach Attribute die mit `@` beginnen oder doppelpunkte enthalten erlauben, auch wenn das kein valides HTML ist.

Oder alternativ einfach alles erlauben was laut der HTML-Parser-Spezifikation als attribut geparsed werden kann: `[^>\s/][^>\s/=]*`
