### ISSUE TITLE
The Twig use statement does not work when extending legacy templates

### ISSUE THREAD

**Issue by m-vo** [contao/contao#6447]
### Affected version(s)

5.2

### Description

When extending from a legacy template horizontal reuse seems to be broken.

Reproducer:
```twig
{# templates/fe_page.html.twig #}
{% extends "@Contao/fe_page.html5" %}
{% use "@Contao/component/_figure.html.twig" %}
```

This will lead to an error saying `figure` was not set, which it isn't, but the component block's function should not even get called at that point. :thinking:

**Comment by leofeyer** [comment]
See #6450.
