### ISSUE TITLE
New Suggestion for Edit-Icon

### ISSUE THREAD

**Issue by GOVILI** [contao/contao#6452]
### Description

The edit icons in the backend have been changed. The previous yellow pen for editing the item properties has moved one position further. And the previously crossed tool icon is now in the first position and has been changed to the yellow pencil. Of course, this causes confusion for users who are switching, but this is perhaps a matter of habit. I think it is more important that previous documentations and forum messages remain clear. Otherwise, we must always pay attention to the version for which the information is valid in all descriptions. 
The new icon could stay for me, but I think it is difficult to reuse the previous icon with a different function. 
From my point of view, three aspects are important here: the appearance of the icon itself (should it be a pen), the switch of the position of the icon and the colour of the icon. 
At a minimum, I would suggest changing the colour so that at least phrases like "click on the yellow pen" (which is how I know most of them in everyday use) lead to the desired irritation: "There is no yellow pen". 
For this reason, here is the suggestion to use the pen in blue.
![edit_new](https://github.com/contao/contao/assets/7502694/174587d8-3372-46fa-81f3-a0c00aa35a81)

Another possibility would be to take only the spanner from the previously crossed tool symbol + change the colour to blue (= similar but different symbol + mirrored + colour different):
![header_new](https://github.com/contao/contao/assets/7502694/77c55ee4-baaa-419f-840f-15dc7980f455)

**Comment by fritzmg** [comment]
> The new icon could stay for me, but I think it is difficult to reuse the previous icon with a different function.

But that is what has been fixed. In Contao 2, 3 and 4, the pen icon did two different things: it either opened the edit mask of a record - or it showed the child elements of the given parent record. This has been fixed in Contao 5. Now the pen icon _always_ edits a record.

**Comment by GOVILI** [comment]
I understand the approach and I also think it is very good that the new version tries to pay attention to stringency. 👍 For new users, that is absolutely right.
In my view, stringency also refers to the knowledge that has been learned and is documented. To solve both, the pen would probably have to be completely replaced by a new icon?!
This would in turn require us to change all the other parts of the documentation for the new version, etc., which of course is not good either. So the real question is, which compromise is the most acceptable...

**Comment by fritzmg** [comment]
> This would in turn require us to change all the other parts of the documentation for the new version, etc

That's normal. It is a new major version after all.

**Comment by GOVILI** [comment]
ok, I see. Then let us close this ticket.
