### ISSUE TITLE
Fehlerhafte Vorschläge zur Datenbankaktualisierung im Installtool

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#646]
Nach der Installation von Contao 4.4.42 mit Newsletter-Bundle und Kopieren der Datenbank aus Contao 3.5.40 werden im Installtool zur Aktualisierung der Datenbank in der standardmäßig vorausgewählten Rubrik "Spalten ändern" u. a. die folgenden beiden Änderungen vorgeschlagen:
````
ALTER TABLE tl_newsletter_channel CHANGE smtpuser sender VARCHAR(128) DEFAULT '' NOT NULL
ALTER TABLE tl_newsletter_channel CHANGE smtppass template VARCHAR(32) DEFAULT '' NOT NULL
````
Statt die Spalten ```sender``` und  ```template``` neu anzulegen, werden die Spalten ```smtpuser``` und ```smtppass``` umbebannt.

**Comment by fritzmg** [comment]
Das passiert, wenn ein Feld entfernt werden würde und ein anderes Feld von einem ähnlichen Typ hinzugefügt werden würde. Anstatt das eine Feld zu droppen und das andere Feld neu anzulegen, wird es umbenannt. Ist also insofern normal.

**Comment by OMOSde** [comment]
Enthält das umbenannte Feld dann nicht potentiell falsche Daten?

**Comment by aschempp** [comment]
Leider ja. Die einzige Lösung dafür wäre wohl das Update automatisch zu machen (also im 4.8-Update die alten Felder zu löschen).

**Comment by Mynyx** [comment]
Wieso nicht einfach die Felder neu anlegen?

**Comment by leofeyer** [comment]
Ich verstehe auch nicht so recht, warum Doctrine das so macht. 🤷‍♂

**Comment by aschempp** [comment]
Wenn in einer Tabelle ein Feld neu ist und eines fehlt, und beide denselben Typ haben, vermutet Doctrine dass die Felder umbenannt wurden. Was in den meisten Fällen auch zutrifft 😉

**Comment by Toflar** [comment]
Der Doctrine Schema Manager tut genau das was er sollte: Er managed ein Schema. Seine Aufgabe ist es, zwei Schemata zu vergleichen und dann von Schema A nach Schema B zu migrieren. Was mit den Daten passiert, ist dem Schema Manager egal. Dafür wären Migrationen notwendig.
Also Doctrine macht eigentlich alles richtig. Aber für unseren Anwendungsfall ist es ggf. nicht ganz optimal. Mir fällt nur gerade nicht ein, was wir tun könnten.

**Comment by ausi** [comment]
Lässt sich die Erkennung für die Umbenennung einer Spalte deaktivieren? Umbenannte Spalten sind ja eher selten in unserem Fall und wenn dann würden wir die Umbenennung ohnehin in der Update-Routine durchführen.

**Comment by Toflar** [comment]
Nope. Der `Comparator` ist hardcoded (https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Schema.php#L420 und https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Comparator.php#L230).
Aber es wäre wohl relativ einfach (`new Comparator(false)` oder so) das Doctrine beizubringen. Nur ob sie das wollen, in welcher Form und wann es schlussendlich released würde, bleibt natürlich offen.
Soll ich mal ein Ticket machen und nachfragen ob sie ggf. überhaupt einen PR akzeptieren würden?

**Comment by bytehead** [comment]
Ich finde das Feature praktisch. Falls es deaktiviert werden würde, gerne per config damit es nach Wunsch aktiv bleiben kann.

**Comment by Toflar** [comment]
Würde ich nicht machen. Du nutzt ja das Installtool eh nicht und würdest bei `doctrine:migrations:diff` das jetzige Verhalten bekommen :) Für das Installtool wäre das andere Verhalten für die meisten Leute ein guter Default.

**Comment by bytehead** [comment]
Ich nutze das install tool - einfach nicht als GUI. Aber kann sonst einfach `doctrine:schema:update` verwenden, wenn Felder umbenannt wurden (und die Daten erhalten bleiben sollen).

**Comment by ausi** [comment]
> Soll ich mal ein Ticket machen und nachfragen ob sie ggf. überhaupt einen PR akzeptieren würden?

Ja, bitte ☺️

**Comment by Toflar** [comment]
Done: https://github.com/doctrine/dbal/issues/3661

**Comment by leofeyer** [comment]
> Mir fällt nur gerade nicht ein, was wir tun könnten.

@aschempp hat [oben](https://github.com/contao/contao/issues/646#issuecomment-522431367) schon eine mögliche Lösung gepostet:

> im 4.8-Update die alten Felder zu löschen

**Comment by Toflar** [comment]
Wir wollen ja nicht blind löschen. Wir haben immer die User gefragt bisher. Ist auch praktisch, weil manchmal lass ich alte Felder bewusst noch rumschwirren bis ich sie dann ein paar Wochen später lösche.

**Comment by leofeyer** [comment]
Scheinbar kann man das in Doctrine doch anpassen, wie @dmolineus in #1716 erklärt.
