### ISSUE TITLE
Wartungsmodus verhindert das generieren der Vorschaubilder in BE und FE, auch in der Vorschau

### ISSUE THREAD

**Issue by Ainschy** [contao/contao#647]
**Contao 4.8.0**

**Bei aktivem Wartungsmodus werden keine Bilder in der Dateiverwaltung erzeugt.** 
Der Netzwerk Tab im Browser quittiert die Anfragen mit 503. Die Bilder werden dabei nicht im Assets Ordner abgelegt. Das gleiche gilt für die Frontend Vorschau. Erst nach dem deaktivieren des Wartungsmodus wurden die Bilder korrekt .

**Den Wartungsmodus aktivieren und beim Benutzer den Bilder-Cache leeren, dann in der Dateiverwaltung einen Bildordner aufrufen.**

**Comment by ausi** [comment]
Wir sollten den Wartungsmodus für die Bild-Requests deaktivieren. 
Pull-Request: #648
