### ISSUE TITLE
Fragment priority when reusing the same identifier

### ISSUE THREAD

**Issue by m-vo** [contao/contao#6471]
### Affected version(s)

5.3

### Description

Currently, there are two issues when redeclaring a content element/frontend module type. 

If you want to replace the `text` content element, you could for instance do something like this:
```php
// App/Controller/ContentElement/MyTextController.php
#[AsContentElement(type: 'text', category: 'texts', template: 'content_element/text')]
class MyTextController extends AbstractContentElement { 
  // […]
}
```

But the core's `text` type would still be used. Additionally the `debug:fragments` command would output two entries for `text` but both would show the core's class.

The reason for this is, that the `RegisterFragmentPass` uses priority tagged services, i.e. you need to manually tag your service with a `priority` (it does not work in the attribute). I would argue, that we should probably use the bundle loading order instead or - at least - the app should always come last by default if not configured differently. 

The issue with `debug:fragments` is something else: there the `add()` method assumes it is only called once per identifier. We should probably store all information together (`data[] = […, …, …]`)  instead of in three different arrays.

As this whole setup is compile time only, we could also change the logic in the `RegisterFragmentPass` to only add the effective calls to the definitions once *all* found entities were processed.

/cc @bytehead

**Comment by aschempp** [comment]
I always assumed the order of bundles affects the sorting as well as the priority, simply because the array that stored the information must have an order. However, due to sorting algorithms, that could actually be lost.

Regarding the command list, would you still get two text elements when priority is used? That looks like a bug to me.

**Comment by m-vo** [comment]
> Regarding the command list, would you still get two text elements when priority is used? That looks like a bug to me.

Yes, because there are still two independent services. And for each of them we add calls for the fragment registry and the debug command. If there are two services with the same type, we should IMHO either only add method calls for the latter (which would solve the problem in the debug command) *or* keep the behavior but then store the data in the command differently or index it by identifier, so that only the effective one is shown. 

After all, in the the registry, there is a comment suggesting, that it's fine to add multiple calls with the same identifier:
https://github.com/contao/contao/blob/a084e49f5c65eeb6cd58ea441513473419a6a520/core-bundle/src/Fragment/FragmentRegistry.php#L19-L25

**Comment by m-vo** [comment]
By the way, currently the debug command would just output identical rows, because it iterates the identifiers but looks up the wrong data. :smile:

**Comment by bytehead** [comment]
The problem only occurs in 5.x
