### ISSUE TITLE
Screenreader erfasst nicht URL Auswahl bei URL einfügen

### ISSUE THREAD

**Issue by pedal123** [contao/contao#6472]
### Affected version(s)

4.13.32

### Description

Contao ist ziemlich gut für Blinde geeignet.
Mit dem Screenreader ist aber aber nicht möglich eine URL einzufügen.
Elementtyp Text -> Link einfügen/bearbeiten (erstes Fenster funktioniert) ->  bei "URL auswählen" (nächstes Fenster) bleibt der Reader im Fenster darunter hängen. Das Fenster mit Seiten, Dateien, Nachrichten usw. ist nicht erreichbar.
Der Kollege behilft sich mit mit einer gemerkten Nachrichten ID und dem Eingeben von {{news_url::*|urlattr}}.

**Comment by leofeyer** [comment]
Wir müssen vermutlich ein komplett anderes Skript für Modal-Windows verwenden, um diese barrierefrei zu gestalten. http://www.humaan.com/modaal/ scheint mir dafür gut geeignet, allerdings wäre das meiner Meinung nach eher ein neues Feature für Contao 5.3 als ein Bugfix für 4.13. @contao/developers Wie seht ihr das?

**Comment by pedal123** [comment]
Wenn ich das richtig verstehe gibt es im "simple-modal" Fenster keine Aria-Attribute, vielleicht könnte man die nachrüsten?
https://www.w3.org/TR/aria-in-html/

**Comment by ausi** [comment]
Eventell könnte man als Bugfix den Fokus via JavaScript setzen, z. B. hier https://github.com/contao/contao/blob/47287e08d133bcd47e155683b0e5ecbe5071c60e/core-bundle/src/Resources/public/core.js#L1096 folgendes hinzufügen: ` onload="this.contentWindow.focus()"`

**Comment by leofeyer** [comment]
@pedal123 Kannst Du testen, ob @ausi‘s Vorschlag funktioniert?

**Comment by pedal123** [comment]
Hat bei mir leider nicht funktioniert.
Testen ist im Prinzip einfach, wenn man es mit der Tabulatortaste erreichen kann funktioniert es, Leertaste funktioniert als Mausklick.

**Comment by ausi** [comment]
Mit folgenden Änderungen war in meinem Test alles zum Setzen eines Links mit der Tastatur bedienbar:
- https://github.com/contao/contao/pull/6490
- https://github.com/contao-components/simplemodal/pull/4

**Comment by pedal123** [comment]
Ist jetzt getestet. 
Funktioniert. 
Allerbesten Dank!
