### ISSUE TITLE
Version413\AlwaysForwardMigration failed

### ISSUE THREAD

**Issue by tonsinn** [contao/contao#6475]
### Affected version(s)

4.13.32

### Description

trying database update Contao\CoreBundle\Migration\Version413\AlwaysForwardMigration
an error occures:

An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

**Comment by fritzmg** [comment]
This error is likely caused by an extension which is using an unbuffered query - likely unknowingly via Contao's legacy database interfaces.

**Comment by tonsinn** [comment]
problem solved with the install tool outside of the contao manager. 
thanks fritzmg
