### ISSUE TITLE
Vimeo player settings: field label typo

### ISSUE THREAD

**Issue by xchs** [contao/contao#6480]
### Affected version(s)

4.13, 5.2

### Description

There is a typo in the German translation of the following field label name:

![image](https://github.com/contao/contao/assets/1218766/d20deaf8-0cf5-41f8-b3e0-c3e6dd29b7c6)

Maybe it could be adjusted on Transifex. Thanks.

**Comment by leofeyer** [comment]
I have fixed this in Transifex. The changes will be rolled out with the next releases.
