### ISSUE TITLE
no dumped variables in debug-mode

### ISSUE THREAD

**Issue by plandolt** [contao/contao#649]
**Affected version(s)**
4.8 (but might be also a problem in previous version)

**Description**
Dumping a variable with `dump(...);` ist using the symfony var-dumper to display the variable immediately when the debug-modus is off. But wenn i switch it on via backend and then try to dump a variable in the frontend there is no output at all. When the debug-toolbar is available the dumped content will be accessible trough the debug tab in the debug-toolbar but this is empty.

Any idea whats going wrong?

**Comment by jgriepenburg** [comment]
Same Problem here.

**Comment by fkaminski** [comment]
Tested with a fresh (local) 4.8 Installation - works for me - see:
https://community.contao.org/de/showthread.php?82-Alle-verf%C3%BCgbaren-Variablen-in-einem-Template-anzeigen&p=509460&viewfull=1#post509460

**Comment by aschempp** [comment]
I have seen this in some installations as well, but not in all. I have not been able to figure it out yet 😞

**Comment by Tastaturberuf** [comment]
If I use the 4.7 app_dev.php in 4.8 it works.

As workaround i renamed it to dev.php because the composer install or update  delete it every time.

**Comment by aschempp** [comment]
I was unable to reproduce this in a fresh installation. @scuben in what file exactly did you place the `dump` statement?

**Comment by plandolt** [comment]
I dump a variable in a FrontendModule in its `compile` method. With `env=prod` the dump is shown at the very top of the page (obviously). But with `env=dev` there is no dump shown on page and no dump in the debug tab of the toolbar.

**Comment by plandolt** [comment]
I narrowed the problem a bit. The dump gets flushed as the `reset` method on `DumpDataCollector.php` gets called.

When i comment Line 30:35 in `web/index.php` I have the dump in the debug toolbar. So far I guess that something in the ContaoCache is responsible to let the `reset` method (through a listener) being called.

**Comment by bytehead** [comment]
I can copy this in Contao `4.8.1` and a `<?php dump($this) ?>` statement in the `fe_page` template.

**Comment by leofeyer** [comment]
See #712.
