### ISSUE TITLE
Make requirement of tecnickcom/tcpdf optional

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#65]
Afaik the tcpdf library is only used for exporting articles in Contao. However, this is a feature I only use in 1% of my projects. So the size of this library is really huge (~30 MB). Since Contao 4 uses composer to manage dependenecies it's not a big deal to make it an optional dependency. The pdf export for articles should be only available if it's installed then.

**Comment by ausi** [comment]
👍 from me.

But I think we should then make it installable via the Contao Manager. Maybe by creating a `pdf-export-bundle` and moving the code from `ModuleArticle::generatePdf()` and `tl_article.printable` there?

The biggest problem I see here is backwards compatibility. Maybe we can install the `contao/pdf-export-bundle` by default for the managed-edition? But even then, everyone that would update from Contao 4.6 to 4.7 would lose the PDF export.

**Comment by dmolineus** [comment]
> But I think we should then make it installable via the Contao Manager. Maybe by creating a pdf-export-bundle and moving the code from ModuleArticle::generatePdf() and tl_article.printable there?

Making it installable would be necessary. Does the package indexer already whitelist packages which are suggested by a contao-bundle?

**Comment by leofeyer** [comment]
> everyone that would update from Contao 4.6 to 4.7 would lose the PDF export.

If the announcement has a detailed hint, I think it would be ok.

**Comment by leofeyer** [comment]
Changed in f6e6df28ca4fbe1d17a990344a79c05158b23ce5 and https://github.com/contao/tcpdf-bundle.

**Comment by leofeyer** [comment]
I'm reopening this as removing the `tcpdf.php` file is a BC break. Also, other extensions might need to include the file if they want to use TCPDF, so this needs to be solved differently.

**Comment by ausi** [comment]
How about moving the *tcpdf.php* file to the bundle and including it in contao/core-bundle? something like:

```php
$path = __DIR__.'/../../../../../tcpdf-bundle/src/Resources/contao/config/tcpdf.php';

if (!file_exists($path)) {
	throw new \LogicException('contao/tcpdf-bundle must be installed to use TCPDF in Contao');
}

@trigger_error('Using the tcpdf.php file from contao/core-bundle has been deprecated and will no longer work in Contao 5.0. Use the file from contao/tcpdf-bundle instead.', E_USER_DEPRECATED);

return include $path;
```

@leofeyer will/should the tcpdf bundle go into the monorepo?

**Comment by leofeyer** [comment]
> will/should the tcpdf bundle go into the monorepo?

No, since we don't need to keep the tags in sync.

**Comment by leofeyer** [comment]
> I'm reopening this as removing the `tcpdf.php` file is a BC break.

The bundle will now add the symlink so `system/config/tcpdf.php` always exists.
