### ISSUE TITLE
"There is no "contao-components/html5shiv" asset package.

### ISSUE THREAD

**Issue by kroerig** [contao/contao#650]
**Affected version(s)**
4.8.0
**Description**  
After upgrade from 4.7 contao throws an error page and logs the following:

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\Asset\Exception\InvalidArgumentException: "There is no "contao-components/html5shiv" asset package." at /var/www/web0/html/contao4/vendor/symfony/asset/Packages.php line 78 {"exception":"[object] (Symfony\\Component\\Asset\\Exception\\InvalidArgumentException(code: 0): There is no \"contao-components/html5shiv\" asset package. at /var/www/web0/html/contao4/vendor/symfony/asset/Packages.php:78)"} []`

**How to reproduce**  
Upgrade from 4.7.x to 4.8.0

**Comment by xchs** [comment]
Do you have a custom `fe_page.html5` template?

**Comment by Nightwing0815** [comment]
Had the same issue. You'll have to renew the changes on your fe_page template.
html5shiv is an deprecated core component, your fe_page has a call for it inside ;-)

[fe_page.html5](https://github.com/contao/contao/compare/4.7...4.8.0#diff-d1c7d2765794f5c11273a7438b71df39)

**Comment by kroerig** [comment]
Thx. Found it. A note during the update would have been fine.
