### ISSUE TITLE
Unable to use "Content element" as non-admin user because of "invalid ID" error

### ISSUE THREAD

**Issue by chris74656** [contao/contao#6504]
### Affected version(s)

5.2.6

### Description

This can be reproduced in demo.contao.org by:

1. Sign into the backend as an editor, i.e. h.lewis
2. Open any article and create a content element of type "Content element"
3. Click on "Change selection"
4. Picker opens but shows an error "Invalid content element ID ."

![image](https://github.com/contao/contao/assets/3785634/598f2032-9a1e-456c-a2af-7a00ac6832e2)

The problem does not occur for admins.
The problem doesn not occur for non-admin users, if an admin has previously selected an element, so that the field is not empty.

**Comment by ausi** [comment]
I can confirm the issue. (Contao 4 does not seem to be affected)

**Comment by ausi** [comment]
@chris74656 can you confirm that the changes from #6510 fix your issue?

**Comment by chris74656** [comment]
Yes, #6510 fixes the issue, thanks!
