### ISSUE TITLE
Error UnusedArgumentsException for auto_item with multiple parameters

### ISSUE THREAD

**Issue by hjuefricke** [contao/contao#6512]
### Affected version(s)

5.2

### Description

If there is more than one url fragment, e.g. ".../page/para1/1/para2/2", the error "_Unused arguments: para1, para2_" (vendor/contao/core-bundle/contao/classes/FrontendTemplate.php:114) is thrown.
If only one parameter is appended, auto_item is set as desired.

I found so far:
In Contao\CoreBundle\Routing\Enhancer\InputEnhancer $input->setUnusedRouteParameters($inputKeys) is called in line 81for all fragments. If I comment this out, everything works well.

**Comment by fritzmg** [comment]
That's normal. Your controller needs to use `Input::get('para1')` and `Input::get('para2')`, otherwise this exception will occur.

**Comment by hjuefricke** [comment]
Thanks for the quick reply! It Works.

I used:
$request->attributes->get('_contao_input')['setGet']

It would be nice if we could avoid using the Input Class additionaly to Request Class in future.

**Comment by fritzmg** [comment]
imho for legacy functionality like this you will always need to use `Contao\Input`. The modern way would be to use a [Page controller](https://docs.contao.org/dev/framework/page-controllers/) instead.

**Comment by hjuefricke** [comment]
I mean for FrontendModulController.

**Comment by fritzmg** [comment]
Yes, if you use the legacy path parameters (no matter where), you will need to use `Contao\Input`. If you use a Page controller you can then instead pass the parameters to your module controller via request attributes for example.
