### ISSUE TITLE
Wrong Link to insert tags page in help

### ISSUE THREAD

**Issue by av3** [contao/contao#6536]
### Affected version(s)

5.2.4, 4.13.32

### Description

On the page contao/help?table=tl_content&field=text the link for "Insert-Tags" leads to https://docs.contao.org/dev/framework/insert-tags/, but users wo open the help page to see the insert tags would need https://docs.contao.org/manual/en/article-management/insert-tags/ or https://docs.contao.org/manual/de/artikelverwaltung/insert-tags/

**Comment by netzarbeiter** [comment]
I have added the links for insert tags and markdown, so you can use them in transifex.


- Weitere Informationen zu Insert-Tags finden Sie im [Contao-Handbuch](https://to.contao.org/docs/insert-tags) /  https://to.contao.org/docs/insert-tags. https://github.com/contao/contao/blob/3b3a551ab2151eb2013916734fae5d828f6011e7/core-bundle/contao/languages/de/explain.xlf#L18
- Weitere Informationen zu Markdown finden Sie im [Contao-Handbuch](https://to.contao.org/docs/markdown) / https://to.contao.org/docs/markdown. https://github.com/contao/contao/blob/3b3a551ab2151eb2013916734fae5d828f6011e7/core-bundle/contao/languages/de/explain.xlf#L34

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6602 and https://github.com/contao/contao/pull/6601
