### ISSUE TITLE
Pages -> generate aliases (multiple levels)

### ISSUE THREAD

**Issue by bytehead** [contao/contao#6542]
### Affected version(s)

4.13

### Description

1. Copy a full page tree (e.g. for an additional language)
2. Edit the page tree (page names)
3. Expand all page nodes of the new tree
4. Edit multiple, choos all of the new tree and click "Generate aliases"

Aliases of pages with level > 1 don't get the parent alias for folder url style aliases.

To fix the aliases of subpages I have to do this as many times as my page tree has levels.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6549
