### ISSUE TITLE
UnwrapTwigExceptionListener fails when using TWIG templates inside news/calendar events

### ISSUE THREAD

**Issue by md-netdesign** [contao/contao#6548]
### Affected version(s)

up to 5.2.6

### Description

Hello,

we've encountered a bug with the download elements in the latest Contao version (5.2.6), while using TWIG templates for the news/calendar extension.

The exact problem lies within the [`UnwrapTwigExceptionListener.php`](https://github.com/contao/contao/blob/5.2/core-bundle/src/EventListener/UnwrapTwigExceptionListener.php). There, any `ResponseException` is correctly unwrapped, when used directly. If any download element is used within a news post or calendar event and printed via TWIG, this fails, because the exception is wrapped in another `RuntimeException`, before it is passed to the `UnwrapTwigExceptionListener`. The wrapping is done in the [`ContextFactory`'s `__toString()` method](https://github.com/contao/contao/blob/5.2/core-bundle/src/Twig/Interop/ContextFactory.php#L155).

Given the following code sample, in (for example) the `news_full.html.twig` template:
```twig
{% if text|default(null) %}
    {{ text|raw }}
{% endif %}
```
…clicking on the download link fails with the following exception:

> `ResponseException` » `RuntimeException` » `RuntimeError`
> An exception has been thrown during the rendering of a template ("Error evaluating "text": This exception has no message. Use $exception->getResponse() instead.").

While throwing the `RuntimeError`, the Contao `UnwrapTwigExceptionListener` is called, but does nothing, because the wrapped exception is a `RuntimeException` instead of a `ResponseException` directly. (see [`UnwrapTwigExceptionListener.php Line 30/31`](https://github.com/contao/contao/blob/5.2/core-bundle/src/EventListener/UnwrapTwigExceptionListener.php#L30))

We know, that news and calendar events have attachments, which do not raise that issue. But, sometimes it would be preferable for a customer to place a download element anywhere in the post, instead of where we decide to place the attachments in the template.

Please let me know, if there is anything we miss here. Or if there's a trick while outputting the `text` variable inside of the `news_full.html.twig` template.

Otherwise, this would be our proposed change, inside the `UnwrapTwigExceptionListener`, replacing lines 29–32:
```php
if (
    !($throwable = $event->getThrowable()) instanceof RuntimeError
    || !(
        ($previous = $throwable->getPrevious()) instanceof RuntimeException ?
            $previous = $previous->getPrevious() :
            $previous
    ) instanceof ResponseException
) {
```

We're happy to provide a pull request.

Thanks in advance!

**Comment by m-vo** [comment]
Thanks for investigating. Why is the exception wrapped multiple times in the first place? This might be the actual bug.

**Comment by md-netdesign** [comment]
The exception is wrapped, because of the [`ContextFactory`'s `__toString()` method](https://github.com/contao/contao/blob/5.2/core-bundle/src/Twig/Interop/ContextFactory.php#L155) in the `Contao\CoreBundle\Twig\Interop` namespace. When evaluated as a string, the `ResponseException` is caught and wrapped inside a `RuntimeException`.

```php
/**
 * Called when evaluating "{{ var }}" in a Twig template.
 */
public function __toString(): string
{
    try {
        return (string) $this();
    } catch (\Throwable $e) {
        throw new \RuntimeException(sprintf('Error evaluating "%s": %s', $this->name, $e->getMessage()), 0, $e);
    }
}
```

I can't guess why this is done specifically in this place.

IMO the `ResponseException` could also just be thrown anyway. Theoretically all other exceptions would also just propagate higher and would ultimatly be caught by Symfony. (We did not test that yet.)

**Comment by md-netdesign** [comment]
Just for clarity: I did notice, that we're talking about the `__toString()` method of the anonymous class, which is returned by the [`ContextFactory`'s `getCallableWrapper` method](https://github.com/contao/contao/blob/5.2/core-bundle/src/Twig/Interop/ContextFactory.php#L124).

**Comment by md-netdesign** [comment]
Well, here's a possible solution without changing the core-bundle or anything else, if someone needs it:

Using
```twig
{% set html = text.invoke()|default %}
{% if html %}
    {{ html|raw }}
{% endif %}
```
instead of the original snippet (= `{{ text|raw }}`) will only wrap the ResponseException once, so the `UnwrapTwigExceptionListener` will correctly unwrap TWIGs `RuntimeError` and no exception get's passed to Monolog, because the `ResponseException` is handled by Contao before.

This works, because the anonymous class inside of the `ContextFactory` also contains an [`invoke`](https://github.com/contao/contao/blob/5.2/core-bundle/src/Twig/Interop/ContextFactory.php#L164) method.

If no fix is desired, this can be closed. Otherwise, we're happy to provide a pull request either for the `UnwrapTwigExceptionListener` or the `__toString()` method of the anonymous class.

**Comment by m-vo** [comment]
I think I'm fine with removing the try/catch block in `__toString()` of the wrapper for anonymous functions. 👍

This was supposed to add DX for people transitioning to Twig but is probably not that important.

Would you like to make a PR with this change?

**Comment by md-netdesign** [comment]
Yes. (But it could take a few days 😉)
