### ISSUE TITLE
Form field generator shows irrelevant fields to configure

### ISSUE THREAD

**Issue by Toflar** [contao/contao#655]
**Affected version(s)**

4.8

**Description**  

The new `min` and `max` value in the form field settings are just fine. However, if I choose `numeric` values in the `validation` section, should not see the other two (`maxlength` and `minlength`) because they will be ignored anyway.

![image](https://user-images.githubusercontent.com/481937/63421303-a778b900-c408-11e9-87d8-869ea642aee7.png)

So I guess the `rgxp` would need to become a `selector` as well and we need some more palettes like `text_digit` etc. to show the correct fields.

**Comment by leofeyer** [comment]
Fixed in bb3c29a8af0c395092b298278e8c4d4f48a4faa8.
