### ISSUE TITLE
Twig: simplify extending headlines for all elements

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#6550]
### Affected version(s)

5.X

### Description

As discussed in slack, it's quite difficult to extend headlines for all content elements and the headline element at the moment.

@m-vo suggested using the following (somehow ugly) solution

```
{% use "@Contao/component/_headline.html.twig" %}

{% block headline_attributes %}
    {% set headline = headline|merge({attributes: attrs(headline.attributes|default).addClass('foobar')}) %}
    {{ parent() }}
{% endblock %}
```

and this works for elements that extend component/_headline.html.twig, but not for the headline element itself. 
Updating `content_element/_hedline.html.twig` (and maybe refactoring component/_headline) should fix this problem.

**Comment by m-vo** [comment]
We need to merge the attributes. Otherwise either case will not work due to the headline element having no real wrapper.

**Comment by leofeyer** [comment]
> Updating `content_element/_hedline.html.twig` (and maybe refactoring component/_headline) should fix this problem.

Can you create a pull request with the necessary changes?

**Comment by denniserdmann** [comment]
Unfortunately not (i don't have the skills). I created this ticket because we discussed this problem a couple of days ago in slack.

**Comment by falkgeist** [comment]
Pitching in, since I just had a discussion around this with @m-vo on Slack.
I made a PR base on the original slack discussion and added some comment on how to e.g. add a class.
