### ISSUE TITLE
Improve usability in repeated fields like `listWizard`

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#6560]
### Description

In 99,9999% cases, when you use a `listWizard` backend widget, you want different values in each row. Currently the workflow is:

1. fill in a row
2. click on ![image](https://github.com/contao/contao/assets/10257912/1eaff3ec-fb78-4c17-98e8-f27c8a0a3a49) icon
3. in the duplicated `input` field: a) click and select, or b) click and `backspace` multiple times, or c) triple-click if you're an advanced user
4. *then* you're free to type the new value

I think the expected (and more efficient) behaviour for the majority of users would instead be to have the duplicated field empty, or have the text in it already selected:

<img width="490" alt="Image on 2023-11-24 10 12 34 PM" src="https://github.com/contao/contao/assets/10257912/22420fe0-3c30-43d0-a3ac-e0879c60a2e7">

**Comment by cliffparnitzky** [comment]
Just to mention: the multi column wizard offers a new button (creates a new row with empty fields) and a duplicate button, that copies the data of the current row to a new one.

**Comment by leofeyer** [comment]
@ameotoko Please check if #6819 works for you.
