### ISSUE TITLE
Improve Usability - Toggle Sidebar Navigation

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#6562]
### Description

It would be helpful, if the »Toggle Navigation« would be always reachable (on every breakpoint).
And also be accessible via a keyboard shortcut (see #6561)

![ct-menu-screen](https://github.com/contao/contao/assets/7679799/348c43cd-a6e4-4e6e-9cc5-816268d5c978)

**Comment by fritzmg** [comment]
What do you mean "on every breakpoint"?

**Comment by fkaminski** [comment]
To have it always.

Currently it depends on:
`@media (max-width: 991px) { ...`

**Comment by fritzmg** [comment]
But what would that button do then?

**Comment by fkaminski** [comment]
To toggle (hide/show) the left sidebar navigation (as with smaller screens).

**Comment by fritzmg** [comment]
You mean you want to be able to hide the main menu in the desktop view?

**Comment by fkaminski** [comment]
Yes.
When I look at the UI behavior in e.g. "[Photoshop Web](https://photoshop.adobe.com/id/tmp:hg9mn8?learnid=7b050fa34872&discover_page=true)", "[VisualStudioCode Web](https://vscode.dev/)" or "[codesandbox.io](https://codesandbox.io/s/?utm_source=landingpage)", one means is to temporarily hide (also quickly via keyboard shortcuts) navigation elements or context menus (also in desktop view).

However, this also means that important (navigation) features must still be accessible via keyboard shortcuts (see #6561).
(Those who do not like keyboard shortcuts can use "normal" menu/navigation options). 

Sidenote: "Sticky" content could then also be dispensed with - JM2C. 

I think you can never have enough (horizontal) editing space. 
Especially in connection with future Contao implementations such as: 

- #6521 
- #6353
- Or possibly a new, right sidebar with context-related quick actions or other UI components in the future
- etc.

**Comment by fkaminski** [comment]
I don't always need the left main navigation when I'm editing content. Especially not when keyboard shortcuts are available (I personally always use keyboard shortcuts when possible). 

It's one of those things: 
- If you like it, you can use it. 
- If you don't like it, you don't have to use it.

But I can understand possible concerns in this regard,
so you might as well close this without hesitation.

**Comment by aschempp** [comment]
I am personally not a fan of this. If you have enough room for the content (which currently is up to the developer of the back end design), there's really no point in hiding the navigation. It would make your content section larger, which imho is already an issue in Contao 5 due to the unlimited width 🤷

**Comment by fkaminski** [comment]
As I said, I can understand concerns in this respect. There are also many opposing viewpoints/requests on this. For example, reducing the backend width ("boxed" instead of "full") or even making the main navigation "sticky", etc..

All of them would certainly have their justification. 
Nevertheless: This implementation does not harm anyone who does not want to use it.

But I will close this, as there will probably not be a majority in this regard.
