### ISSUE TITLE
Images are not shown within RSS XML

### ISSUE THREAD

**Issue by kroerig** [contao/contao#6563]
### Affected version(s)

4.13

### Description

Images cannot be loaded because of relative links.

`
         <picture>           <source srcset="assets/images/9/Anatomy_Bildrezension-ab407564.webp 1x, assets/images/7/Anatomy_Bildrezension-a23c9c81.webp 1.5x, assets/images/4/Anatomy_Bildrezension-55b9bace.webp 1.969x" type="image/webp" width="650" height="396">      <img src="https://www.dieluetteraten.de/assets/images/f/Anatomy_Bildrezension-389ceb00.jpg" srcset="assets/images/f/Anatomy_Bildrezension-389ceb00.jpg 1x, assets/images/6/Anatomy_Bildrezension-94c01ac0.jpg 1.5x, files/luetteraten/img/buchtipps/Anatomy_Bildrezension.jpg 1.969x" width="650" height="396" alt="" loading="lazy">   </picture>      
`

**Comment by fritzmg** [comment]
What images do you mean? Do you mean you have set the **Export settings** to _Full stories_ and these are images from regular text, image or gallery content elements?

**Comment by kroerig** [comment]
Yes, export settings are set to _Full story_ and the event texts have images included.

Example:
https://www.dieluetteraten.de/buchtipps.html
https://www.dieluetteraten.de/share/buchtipps.xml

**Comment by fritzmg** [comment]
I was unable to reproduce the issue. However, I was able to find a [bug](https://github.com/contao/contao/issues/6570) that could potentially cause your issue. To confirm this you can click on the ![](https://demo.contao.org/system/themes/flexible/icons/show.svg) icon of the created feed and check whether its **Base URL** is empty.

**Comment by fritzmg** [comment]
However, I can confirm that only the `src` of an image gets the absolute URL when generating the feed. All other paths are relative:

```html
<div class="ce_image block">
    <figure class="image_container float_above">
        <picture>
            <source srcset="assets/images/7/DeathtoStock_Meticulous-07-33a15386.webp 1x, assets/images/5/DeathtoStock_Meticulous-07-14508612.webp 2x" media="(max-width: 799px)" type="image/webp" width="100" height="82">
            <source srcset="assets/images/5/DeathtoStock_Meticulous-07-020e7df0.jpg 1x, assets/images/8/DeathtoStock_Meticulous-07-38338a53.jpg 2x" media="(max-width: 799px)" width="100" height="82">
            <source srcset="assets/images/5/DeathtoStock_Meticulous-07-14508612.webp 1x, assets/images/1/DeathtoStock_Meticulous-07-96984395.webp 2x" type="image/webp" width="200" height="164"> <img src="https://c413.contao.local/assets/images/8/DeathtoStock_Meticulous-07-38338a53.jpg" srcset="assets/images/8/DeathtoStock_Meticulous-07-38338a53.jpg 1x, assets/images/4/DeathtoStock_Meticulous-07-5ce5e95f.jpg 2x" width="200" height="164" alt="">
        </picture>
    </figure>
</div>
```

Judging by your initial post @kroerig the same seems to be the case with your instance (so it's unrelated to the `feedBase` bug).
