### ISSUE TITLE
Using the subpage layout for the Newsreader module within News Archive module

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#6564]
### Description

Hi,
When we use **News reader module** within the **News Archive module**, it's better that **subpage layout** being used for news reader page (news item).

I mean, the news item is actually a subpage. Currently, it's considered as parent page and main layout is used for that.
```

https://example.com/news                     (Include News Archive module) -> parent page
https://example.com/news/news-item        (News Reader module is activated) -> subpage
```

I hope I was able to convey my meaning.

**Comment by fritzmg** [comment]
I think what you want to do is define two different page layouts - one for the news archive list and one for the news detail, correct?

If so, then what you can do is create two pages with the same alias (e.g. `news`):

* The first one will be the one with your news archive module (disable the news reader module within the news archive module).
* The second one will be the one with your news reader module. You will also need to enable **Require item** and may be set the routing priority to `1` (or higher).

This way you can define two different page layouts as these are now two distinct pages.

**Comment by hamidpeywasti** [comment]
@fritzmg Thank you.
Your solution is better.
