### ISSUE TITLE
Backend keyboard shortcut [Alt]+[t] does not work

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#6565]
### Affected version(s)

4.13.x 5.x

### Description

The [keyboard shortcut](https://docs.contao.org/manual/en/administration-area/back-end-keyboard-shortcuts/#general-keyboard-shortcuts) [Alt]+[t] (Go to top of page) does not work for me in the backend - chrome or firefox 
(Considering [browser-specific differences](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey) - here windows). Others **work**.

- Start the [Contao demo](https://demo.contao.org/contao/login) with BE Login 
- Switch to the article list
- Collapse all nodes
- Scroll to the end/bottom

Expected behavior: Go to the top of the page with the keyboard shortcut

**Comment by fritzmg** [comment]
Is such a short cut even needed? (Since you can use the home key for that anyway, well unless you have an 80% keyboard without it)

**Comment by fkaminski** [comment]
Sure, but since it is [documented](https://docs.contao.org/manual/en/administration-area/back-end-keyboard-shortcuts/#general-keyboard-shortcuts), it should also work (or we should take it out of the manual)

**Comment by fritzmg** [comment]
Yes, that's the point of my question. If it's not there because it's not needed then we just need to remove it from the docs.

**Comment by fkaminski** [comment]
I would prefer update the docs & close this fow now.

**Comment by fritzmg** [comment]
First we need to find out whether this is a deliberate omission or not ;)

**Comment by fkaminski** [comment]
Well, I wouldn't fight it :-)
An example that would immediately come to mind would be in connection with #6353 
(instead of considerations regarding "sticky" implementations). 

On the other hand, a "visual" UI handling (gototop) in the backend would always be useful.

**Comment by fritzmg** [comment]
This has nothing to do with that. This issue is solely about the missing Alt+T keyboard shortcut.

**Comment by leofeyer** [comment]
We deliberately removed the Alt+T shortcut years ago, because every browser already has a shortcut for that.

**Comment by fritzmg** [comment]
Closing in favor of [1265](https://github.com/contao/docs/pull/1265)
