### ISSUE TITLE
Future of the Contao "CSS Framework"

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#6589]
### Description

Now we have a new [Contao demo](https://github.com/contao/contao-demo) 
& this will be maintained via GitHub & certainly further developed.

Never used the Contao "CSS-Framework" personally, but this is certainly helpful for users. 
Future options could be:

- Completely neglect the "CSS framework" in the future & rely/refer to the Demo (Installation).
- Consider using the current [scss](https://github.com/contao/contao-demo/tree/5.2.x/files/contaodemo/theme/src/scss) sources of the demo (or parts of it) for the core "CSS framework"

There may already be ideas for this, then please just close this post.
Otherwise...

**Comment by m-vo** [comment]
I don't think we should ship any new opinionated framework with the core but make it easily possible for extensions to do so. Then users can install whatever they want/need. 

#6531 kind of is a foundation for this (basically removing everything to the bare minimum).

**Comment by fkaminski** [comment]
Makes sense.
