### ISSUE TITLE
Contao Crawler also checks profiler pages

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#6592]
### Affected version(s)

4.13

### Description

With activated Debug Mode, the Contao crawler (started via backend) also checks the symfony profiler pages (typical URI `https://abc.localhost/_profiler/24d1b4?panel=request`).

The solution is simple: _Don't activate the Debug Mode when crawling!_

But maybe a fix is as simple as adding a `<!-- indexer::stop -->` before the synfony panel (and continue the indexer after the panel).

**Comment by fritzmg** [comment]
> But maybe a fix is as simple as adding a `<!-- indexer::stop -->` before the synfony panel (and continue the indexer after the panel).

That won't stop the crawler ;) (it only affects what content is indexed). You could add

```
user-agent: *
disallow: /_profiler
```

to your robots.txt in the website root (or we could add that dynamically for the debug mode)

**Comment by Toflar** [comment]
Symfony itself actually makes sure to send a `x-robots-tag: noindex` header but that doesn't stop it from crawling of course. 

> or we could add that dynamically for the debug mode

This would be the way to go.

**Comment by leofeyer** [comment]
Instead of adjusting the `robots.txt` request, why don‘t we just respect the `x-robots-tag: noindex` header sent by Symfony?

**Comment by Toflar** [comment]
We do. But crawling !== search indexing. I guess @denniserdmann wants to reduce the requests. This is of course not possible with a header that is only sent when you actually do send the request ;)

**Comment by denniserdmann** [comment]
In my case, i was wondering why the crawler was running so long (10 Minutes before canceling) when the website had about 50 pages. Thanks to the crawler debug log, i found out that the profiler was the problem.

**Comment by leofeyer** [comment]
> We do. But crawling !== search indexing.

I see. 👍

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6599
