### ISSUE TITLE
Incorrect help message when sending newsletters

### ISSUE THREAD

**Issue by aschempp** [contao/contao#66]
**Affected version(s)**
4.4 (?)

**Description**  
When sending newsletter, the following message shows up: https://github.com/contao/contao/blob/master/newsletter-bundle/src/Resources/contao/languages/en/tl_newsletter.xlf#L87
This is no longer correct, as logging is done in the system log. Not sure what's the most efficient way for a user to determine the "numeric offset" from the system log.

**Comment by leofeyer** [comment]
Here is how I would do it:

![](https://user-images.githubusercontent.com/1192057/45799987-b19daf00-bcaf-11e8-935a-22155da7c419.png)

Then the numeric offset would be 2.

**Comment by leofeyer** [comment]
Fixed in 1e7304cd66a4ccd2a3c5e143b50f894e8dac829a.
