### ISSUE TITLE
Sort tables in backup SQL dump

### ISSUE THREAD

**Issue by de-es** [contao/contao#6610]
### Description

Damit man die erstellten SQL-Backups per Diff schnell und einfach zum Finden von Fehlern/Änderungen vergleichen  kann, müsste sichergestellt werden, dass die Tabellen immer in der selben Reihenfolge geschrieben werden.

Eine Sortierung könnte in [getTablesToDump](https://github.com/contao/contao/blob/5.x/core-bundle/src/Doctrine/Backup/Dumper.php#L171) erfolgen.

**Comment by Toflar** [comment]
Yeah, why not :) Go ahead!
