### ISSUE TITLE
Form data being stored/sent despite errors

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6611]
### Affected version(s)

5.2, 5.x

### Description

In https://github.com/contao/contao/pull/4898 we added the possibility to add errors to forms in general, rather than only individual widgets. However, this is solely based on the `processFormData` method and hook. Adding an error to the form at this point is too late though. Contao will already have sent the email and stored the data (if either are enabled) as if the form submission was valid. And depending on the order of `processFormData` hooks, these will also be executed as if the form submission was valid. Another issue also arises with form uploads: since the success email is being sent it may contain links to uploaded files. These files will later on be deleted and thus invalidate these links.

Even if you did add an error to the form _before_ `processFormData` (e.g. via `compileFormFields`) this won't help as `Form::processFormData` will still be executed if all the widgets validated.

I think `Form::processFormData` must be executed iff the form is valid. As such we need a way to define the form submission as invalid _before_ that method is executed. Currently there is no way to do so though.

/cc @rabauss

**Comment by leofeyer** [comment]
As discussed in the Contao call, the `|| $this->hasErrors()` part from line 310 should be added in line 304 as well.

https://github.com/contao/contao/blob/d50e67901a36692f57f1a27680dced916ce6ddd6/core-bundle/contao/forms/Form.php#L310

https://github.com/contao/contao/blob/d50e67901a36692f57f1a27680dced916ce6ddd6/core-bundle/contao/forms/Form.php#L304

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add a `if ($this->hasErrors()) { return; }` check before line 402.

https://github.com/contao/contao/blob/d50e67901a36692f57f1a27680dced916ce6ddd6/core-bundle/contao/forms/Form.php#L402

**Comment by fritzmg** [comment]
See #6623
