### ISSUE TITLE
Not possible to set an id for the a-tag in the TinyMCE

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#6618]
### Affected version(s)

4.13 und 5.2

### Description

Für den a-Tag im TinyMCE lässt sich keine ID setzen - auch dann nicht, wenn man explizit noch einmal die ID in den Sicherheitseinstellungen beim a-Tag erlaubt. Wenn man versucht für das a-Tag in der Quellcodeansicht des TinyMCE eine ID zu setzen, dann wird diese nach dem speichern komplett gelöscht. Eine Klasse funktioniert. Auch das Setzen einer ID für andere Element z.B. p-Tag funktioniert.
Siehe dazu auch https://community.contao.org/de/showthread.php?86062-id-Attribut-im-Anker

Ist das aus Sicherheitsgründen notwendig oder ein Bug?

**Comment by fritzmg** [comment]
Hast du es auch in der TinyMCE Config erlaubt?

**Comment by mlwebworker** [comment]
Da es nicht mein Problem ist und ich es nur für jemanden aus dem Forum gemeldet habe, hatte ich es bei mir nicht mit Anpassung im Tiny getestet. Hatte ich bisher gar nicht auf dem Schirm.
Habe jetzt folgendes in dem angepassten Template stehen:

```
<?php $this->extend('be_tinyMCE'); ?>

<?php $this->block('valid_elements'); ?>
    extended_valid_elements: 'q[cite|class|title],article,section,hgroup,figure,figcaption,a[rel|rev|charset|hreflang|tabindex|accesskey|type|name|href|target|title|class|onfocus|onblur|data-lightbox|id]',
<?php $this->endblock(); ?>
```

Damit funktioniert es.
Wäre es nicht sinnvoll das vom Core her schon zu implementieren, zumal es scheinbar früher möglich war, die id im a-Tag zu verwenden? Spricht da etwas dagegen?

**Comment by fritzmg** [comment]
What exactly is the use case?

**Comment by mlwebworker** [comment]
Im Fall im Forum werden vom Fließtext Fußnoten angesprungen und von den Fußnoten kann wieder zurück in den Text gesprungen werden.
Wie gesagt ich habe den Fall nicht. Deshalb kann ich auch nur dieses Beispiel anbringen.

**Comment by fritzmg** [comment]
Sounds very specific to me and thus adjusting the `be_tinyMCE` template is the correct solution 👍

**Comment by mlwebworker** [comment]
Für mich ok. Irritierend für Nutzer ist es immer, wenn etwas, dass früher funktioniert hat jetzt nicht mehr funktioniert.

**Comment by fritzmg** [comment]
The TinyMCE version has changed frequently with Contao and with that features always were added, removed or changed.

**Comment by mlwebworker** [comment]
Ich denke, dann sollten wir es lassen wie es ist und wer das braucht muss es halt im Template anpassen.

**Comment by fritzmg** [comment]
This might be a regression caused by https://github.com/contao/contao/pull/5559

I am not sure what changed, but when reverting #5559 `data-lightbox` still works - and so do things like `id`, `rel` and `style` (/cc @aschempp).

**Comment by mlwebworker** [comment]
Kann das unter Umständen auch noch davon abhängen, welche Version des Tiny MCE installiert ist? In der 4.13 ist das doch nicht zwingend einheitlich oder täusche ich mich da.

**Comment by fritzmg** [comment]
I could not reproduce it with TinyMCE 4 either.

Closing in favor of #6721
