### ISSUE TITLE
Hardcoded ID field ignores what is configured in relation array "field" value.

### ISSUE THREAD

**Issue by asconsulting** [contao/contao#6619]
### Affected version(s)

4.13+

### Description

The ID for the backend widget is hard coded, which ignores what someone has configured in the relation array of the DCA.

`'status' => array
		(
			'inputType'               => 'select',
			'foreignKey'              => 'tl_my_related_table.name',
			'relation'                => array('field'=>'status', 'table'=>'tl_my_related_table', 'type'=>'hasOne', 'load'=>'lazy'),
			'eval'                    => array('chosen'=>true, 'includeBlankOption'=>true, 'tl_class'=>'w50'),
			'sql'                     => "varchar(128) COLLATE utf8_bin NOT NULL default ''"
		),`

In this example the field name of "status" is ignored and the widget rendered with the numeric ID as the key instead of what is in the "status" field of the tl_my_related_table

**Comment by asconsulting** [comment]
A work around for people experiencing this issue is to make an options call back
`'options_callback' 		  => static function ($dc)
{
$arrOptions = [];
$objStatus = \Contao\Database::getInstance()->execute("SELECT status, name FROM tl_my_related_table WHERE published = '1'");
if ($objStatus->numRows) {
	while($objStatus->next()) {
		$arrOptions[$objStatus->status] = $objStatus->name;
	}
}
return $arrOptions;
},`

**Comment by ausi** [comment]
Can probably be fixed by changing https://github.com/contao/contao/blob/bfe21e75db4dc20c9309b9947e6af9b609e8932a/core-bundle/src/Resources/contao/library/Contao/Widget.php#L1339 to something like:

```php
$strField = Database::quoteIdentifier($arrData['relation']['field'] ?? 'id');
$objOptions = Database::getInstance()->query("SELECT $strField as id, " . $arrKey[1] . " AS value FROM " . $arrKey[0] . " WHERE tstamp>0 ORDER BY value"); 
```

**Comment by leofeyer** [comment]
@asconsulting Can you create a pull request with the changes outlined above?

**Comment by asconsulting** [comment]
Pull Request: https://github.com/contao/contao/pull/6622
