### ISSUE TITLE
absolute insert tag flag is reported non-existent in logs

### ISSUE THREAD

**Issue by Toflar** [contao/contao#662]
**Affected version(s)**

4.8 (likely also 4.4, did not double check)

**Description**  

I get hundreds of

`Unknown insert tag flag "absolute" in {{link_url::299|absolute}}`

log entries. This is because `absolute` is a special flag to the link insert tags.

**How to reproduce**  

Add the mentioned insert tag with the `absolute` flag somewhere on the page.

**Comment by leofeyer** [comment]
Fixed in fd4088118086ac187e867b5f0959526f86593109.
