### ISSUE TITLE
Use of undefined constant TL_ASSETS_URL

### ISSUE THREAD

**Issue by Xendiadyon** [contao/contao#663]
**Affected version(s)**
Contao 4.4.42

**Description**  
Starting from the last Contao-Update to 4.4.42, a warning is displayed in the Backend (is there a setting how the Warnings display can be disabled?)

In the Backend, I get the following Warning:
`Warning: Use of undefined constant TL_ASSETS_URL - assumed 'TL_ASSETS_URL' (this will throw an Error in a future version of PHP) in .../vendor/contao/core-bundle/src/Resources/contao/library/Contao/Combiner.php on line 288`

https://github.com/contao/contao/blob/706d44345430260ca74450cd5684ea3501ac07ee/core-bundle/src/Resources/contao/library/Contao/Combiner.php#L286-L289

If `TL_ASSETS_URL` is not defined, it should not be used:
		`if ($strUrl === null && defined('TL_ASSETS_URL'))`
		
Moreover, the optional `$strUrl` doesn't seem to be used at all in this function, so what is the reason that this line still exists?

**How to reproduce**  

1. Have no TL_ASSETS_URL defined
2. Have the error-level Reporting to "Warning" for some yet unknown reason (since Contao 4.4.42 & PHP 7.3 @ Domainfactory)
3. Go to the Contao-Backend (e.g., login mask) in prod-Mode.

**Comment by Xendiadyon** [comment]
Adjust Error Reporting:
.../app/config/config.yml

https://maximivanov.github.io/php-error-reporting-calculator/
   ` error_level:          8183 # E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_USER_DEPRECATED`
to
    ` error_level:          8181 # E_ALL & ~E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_USER_DEPRECATED`

Would this be clever (we don't want to display warning in our productive system) or would this generate problems?

**Comment by leofeyer** [comment]
> If `TL_ASSETS_URL` is not defined, it should not be used

How can the constant be undefined? `Backend::__construct()` calls `$this->setStaticUrls()` and this method defines the constant. Did you probably forget a `parent::__construct()` call in your own controller?

> Moreover, the optional `$strUrl` doesn't seem to be used at all in this function,

It is used twice according to my counting (check the `return` statements).
