### ISSUE TITLE
versioning shows a user for version 1

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#664]
**Affected version(s)**
4.8 (probably 4.4 as well)

**Description**
When the first new additional version of a record is created, the version comparison and drop down show a user for the first version of the record, even though the user who created the first version of the record isn't tracked by Contao at all. Instead, Contao simply uses the same user whoever created the second version of the record.

Imho no user should be shown there to avoid confusion.

**How to reproduce**
1. Log into the back end of the Contao demo as `k.jones`.
2. Create a new text content element with the content `Test` and save.
3. Log into the back end of the Contao demo as `h.lewis`.
4. Edit said content element and update the content to `Test 2` and save.

After saving, the version drop down will appear and it will show the author of the first version of the record being `h.lewis`, even though `k.jones` created that version of the record.

**Comment by leofeyer** [comment]
This is not trivial, because if I skipped step 3, the author of the first version would be correct.

**Comment by fritzmg** [comment]
Well yes, because Contao sets the user of the first version to whoever created the second version... that's the problem ;). Contao should not display a user for the first version at all, because it currently does not track who created the first version.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 29th, we might be able to check for tstamp=0 to figure out whether the current user has created the initial version or not.

**Comment by fritzmg** [comment]
How? The tstamp is set as soon as you save the element.

1. Create a new content element _Text_.
2. Put in some text.
3. Click _Save and close_.
4. Click on ℹ️ 
5. Look at __Revision date__.

It's not `0`.

**Comment by leofeyer** [comment]
That is true unfortunately, because the `Version` class ignores records with `tstamp=0`:

https://github.com/contao/contao/blob/d19f747865194b6b101a986ca56ecaa369bcd82e/core-bundle/src/Resources/contao/classes/Versions.php#L167-L170

I have to check if we can work around this.

**Comment by leofeyer** [comment]
Fixed in 5e86f85458eb61c65539e7f84b981a5c3db085ff.
