### ISSUE TITLE
Improve description for the robots field in tl_page

### ISSUE THREAD

**Issue by stefansl** [contao/contao#6647]
### Description

As discussed in 2019 https://github.com/contao/contao/issues/501 Contao changed the behaviour of the sitemap switch. I really didn't realized that and searched for the possibility to deactivate the site in my sitemap.xml. 
I think it should be mentioned in the robots field, that the setting influences the sitemap.xml. Like (in DE): "Hier legen Sie fest, wie Suchmaschinen die Seite behandeln und ob die Seite ggf. in der sitemap.xml auftauchen soll."

**Comment by aschempp** [comment]
Would you be able to do a pull request for branch `5.x` on the english language files? Translations would be done through www.transifex.com then.

**Comment by de-es** [comment]
Könnte geschlossen werden, oder?
