### ISSUE TITLE
Also check /contao/templates in the "file" insert tag

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#665]
The `{{file::template.html5}}` insert tag can be used to include a template file. However, it only looks in the `/templates` directory and not in `/contao/templates`, therefore I always end up using a custom insert tag that checks both directories.

@contao/developers Do you think we should enhance the `{{file}}` insert tag to check both directories?

**Comment by ausi** [comment]
How about deprecating the `{{file::*}}` insert tag for including a template and create a new `{{template::}}` instead?

The new insert-tag could then use the template loader directly, so it would support all template locations. Additionally we could use the Template class and pass the data from the query string directly to the template instead of the current way (via `$_GET`). It would also allow us to include TWIG templates I think.

**Comment by leofeyer** [comment]
I like this idea. Especially because my custom insert tag is already named `{{template}}` and so I would not have to adjust anything. 😂

**Comment by aschempp** [comment]
I never understood why anyone would use a `{{file::}}` (or `{{template::}}`) insert tag, maybe you can enlighten me?

**Comment by asaage** [comment]
I use it basically to insert javascript, iframes and sometimes inline-svg on selected pages without the need of changing the allowed-tags or adding new layouts for example.

**Comment by contaoacademy** [comment]
I use {{file::}} to add PHP-Script in Forms

example:
https://contao-academy.de/blog/formularfelder-get-url-vorbelegen

**Comment by fkaminski** [comment]
I use it for inline svg's and optional color param like:
https://community.contao.org/de/showthread.php?72991-Man-lernt-nie-aus-Thread&p=508177&viewfull=1#post508177

**Comment by fritzmg** [comment]
I use the HTML content element and HTML module for that (see https://github.com/contao/core-bundle/pull/1315).

**Comment by m-vo** [comment]
>I use it basically to insert javascript, iframes and sometimes inline-svg 

These things aren't templates though? Without a controller doing something to the sources aren't these just assets? I'm not sure a `{{template}}` insert tag (without options like placeholder fillers) is the right approach.

**Comment by asaage** [comment]
> These things aren't templates though? Without a controller doing something to the sources aren't these just assets?

For me these are just files - and it happens to be that the file insert-tag can process them only from the templates-dirctory.
there are a number of ```j_``` and  ```anatytics_``` "templates" which you can add to your layout via a checkox but if you need that as "content" the ```{{file::}}``` insert-tag is the easiest way i could think of.
I don't get the use-case of a ```{{template}}``` insert-tag. Doesn't a Template always belong to something (Modell or Module) which provides the data?

**Comment by fritzmg** [comment]
It's still a viable approach for inline SVGs for example. Or other content that might be inserted in certain places which cannot be done as a content element or module, imho.

In general I am all for a `{{template::*}}` insert tag that renders a template in the proper template context, rather than just including the file :)

**Comment by m-vo** [comment]
Sidenote: I'm not sure if a regular user should even be able to insert random files/templates out of the box.

**Comment by asaage** [comment]
Valid point - but i think a regular user would not have access to the templates-directory and therefore would not  know about filenames or content anyway.

**Comment by m-vo** [comment]
> a regular user would not have access to the templates-directory and therefore would not know about filenames or content anyway.

That's security through obscurity (if it's a security thing anyways).

**Comment by aschempp** [comment]
for inserting any HTML, I think the correct approach would either be a `j_xxx` template to enable in the page layout, or use an HTML module and custom `mod_html_` template. The only approach that cannot be solved is what @contaoacademy does, but that looks like a nice little XSS attack vector to me...

**Comment by leofeyer** [comment]
Using templates to insert SVG images or other reusable fragments is a valid use case. As I said, I have a custom `{{template}}` insert tag, which does exactly that, in all my installations.

> or use an HTML module and custom `mod_html_` template.

That would work as well.

**Comment by contaoacademy** [comment]
> The only approach that cannot be solved is what @contaoacademy does, but that looks like a nice little XSS attack vector to me...

What is the best way to solve my case? Javascript?

**Comment by aschempp** [comment]
> > The only approach that cannot be solved is what @contaoacademy does, but that looks like a nice little XSS attack vector to me...
> 
> What is the best way to solve my case? Javascript?

Good question. Javascript would certainly work and be more secure. But that was more a general statement: you're working with user input, and you can never trust the user. Your PHP script does not take care of any potentially dangerous data (e.g. validating the input).

**Comment by leofeyer** [comment]
As discussed in Mumble on November 28th, we do not want to support the `/contao/templates` path in the `{{file}}` insert tag.
