### ISSUE TITLE
Dark Mode and tinyMCE - unreadable highlighted link

### ISSUE THREAD

**Issue by berecont** [contao/contao#6654]
### Affected version(s)

5.x

### Description

Contao 5 in Dark Mode. When you select a link in tinyMCE, it is highlighted in 'blue,' and the text below it becomes unreadable.
![poor-contrast](https://github.com/contao/contao/assets/33038265/aa6434e4-16a8-4f94-bb3f-22e6ac4dd16c)

**Comment by leofeyer** [comment]
Does the issue occur in the TinyMCE online demo as well?

**Comment by berecont** [comment]
Yes, it also occurs in the online demo. The screenshot is from the online demo.

**Comment by leofeyer** [comment]
I mean the TinyMCE demo: https://www.tiny.cloud/docs/tinymce/latest/full-featured-open-source-demo/

**Comment by berecont** [comment]
Ah OK, now I see - the issue is part of tinyMCE. It occurs in the tinyMCE online demo too.

**Comment by leofeyer** [comment]
Then you should report it there, so the TinyMCE developers can fix it.
