### ISSUE TITLE
tinyMCE and toggling between Dark and Light Mode

### ISSUE THREAD

**Issue by berecont** [contao/contao#6655]
### Affected version(s)

5.x

### Description

Contao 5 in Dark Mode with tinyMCE.
When tinyMCE is open in Dark Mode: switching to Light Mode will keep tinyMCE in Dark Mode.
When tinyMCE is open in Light Mode: switching to Dark Mode will keep tinyMCE in Light Mode.

**Comment by aschempp** [comment]
This is a known limitation of tinyMCE, you have go reload the page to get the correct color.
