### ISSUE TITLE
Keyboard shortcuts - Click and edit

### ISSUE THREAD

**Issue by berecont** [contao/contao#6656]
### Affected version(s)

5.x

### Description

[Documentation](https://docs.contao.org/manual/en/administration-area/back-end-keyboard-shortcuts/#click-to-edit)

For Windows on Contao 4:
[Ctrl] + click: edit the element
[Ctrl] + [Shift] + click: edit the element settings

For Windows on Contao 5 it's reverse:
[Ctrl] + click: edit the element settings
[Ctrl] + [Shift] + click: edit the element

**Comment by ameotoko** [comment]
See https://github.com/contao/docs/issues/1279
