### ISSUE TITLE
4.8.1 nicht alle Vorschaubilder in der Dateiverwaltung und im Frontend werden gezeigt

### ISSUE THREAD

**Issue by jankout** [contao/contao#666]
**Affected version(s)**
4.8.1
**Description**  
Ich habe einige Webseite auf die neuste Version 4.8.1 aktualisiert. Einige Installationen haben gar keine Probleme und bei 2, wo nicht so viele Erweiterungen installiert sind, werden die Vorschaubilder nicht sowohl im Backend als auch im Frontend gezeigt/generiert.  
**How to reproduce**  
Installation durchführen und die Dateiverwaltung anschauen. 
**Anbieter**
all-inkl.com

**Comment by xchs** [comment]
Vielleicht hat es bei Dir die gleiche Ursache wie hier: https://community.contao.org/de/showthread.php?75730-Update-von-4-7-7-auf-4-8-0-gt-Bilder-aus-quot-assets-quot-werden-nicht-angezeigt-FE-BE&p=509203&viewfull=1#post509203

**Comment by jankout** [comment]
> Vielleicht hat es bei Dir die gleiche Ursache wie hier: https://community.contao.org/de/showthread.php?75730-Update-von-4-7-7-auf-4-8-0-gt-Bilder-aus-quot-assets-quot-werden-nicht-angezeigt-FE-BE&p=509203&viewfull=1#post509203

Danke. Was ist aber die Lösung? Die betroffenen Zeilen in htaccess zu löschen?

**Comment by xchs** [comment]
Wenn es in Deiner `.htaccess` ebenfalls diesen Hotlinking-Schutz gibt, dann würde ich diese Direktiven zumindest mal auskommentieren.

**Comment by leofeyer** [comment]
Ich schließe das Ticket, da es sich hierbei nicht um ein Contao-Problem handelt.

**Comment by jankout** [comment]
@xchs Ich habe da in der htaccess-Datei gar keine solche Anweisungen. 

@leofeyer Daher bitte noch überprüfen.

**Comment by xchs** [comment]
Ein allgemeines Contao-Problem ist es wohl nicht, sonst wären ja mehr Leute davon betroffen.
Melde Dich mit Deinem Problem im [Forum](https://community.contao.org).
