### ISSUE TITLE
Layout shift in file manager in Chrome due to images

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6662]
### Affected version(s)

4.13.x, 5.2.x, 5.x

### Description

There is a cumulative layout shift issue in Chrome in the file manager. In Firefox all the `<img>` occupy their size according to the `width` and `height` attributes as expected, causing no layout shift while the images are loading:

<img src="https://github.com/contao/contao/assets/4970961/05c0db0e-dd76-43fc-90ef-75673fd1be1d" width="672">

\
However, in Chrome this is not working:

<img src="https://github.com/contao/contao/assets/4970961/dc4b2f74-e5e5-4a00-91a0-8acb1242540e" width="533">

\
Causing the layout to shift while the images are loaded (or lazy loaded after scrolling). Even though the inspector tells us, that the correct intrinsic size is determined:

<img src="https://github.com/contao/contao/assets/4970961/2f491a47-62be-4160-9d9e-1c8b0d960152" width="208">

\
I think part of the problem is that we are lacking `display: block` (or `inline-block`) for these `<img>` - but that does not fix the issue in Chrome.

@ausi may be you have an idea why this is happening?

**Comment by zoglo** [comment]
@fritzmg I just checked something and realized that removing the "width: auto" from here will solve the issue.

https://github.com/contao/contao/blob/68b169eca43e4fc7ef3dddc7336b0c84905dec92/core-bundle/src/Resources/contao/themes/flexible/main.css#L1213

We don't need it anymore as aspect-ratio is available in all modern browsers (https://caniuse.com/mdn-html_elements_img_aspect_ratio_computed_from_attributes)
