### ISSUE TITLE
`deleteAll` does not work on `tl_page` for non-admins

### ISSUE THREAD

**Issue by aschempp** [contao/contao#6666]
### Affected version(s)

4.13, 5.2

### Description

Easily reproducible in the online demo:
 1. Set page permissions in root page to allow delete pages to editors
 2. Login as j.lewis
 3. Go to Sites and try to edit-all and delete multiple pages

**Comment by leofeyer** [comment]
I‘d say that is a known limitation in Contao 4.13 that was fixed in Contao 5.3. Or is there an easy fix for Contao 4.13?

**Comment by aschempp** [comment]
I did not investiage for a solution, I'm happy with handling this as a known limitation 😊
