### ISSUE TITLE
Permission denied to `show` action if user does not have access to a page type

### ISSUE THREAD

**Issue by aschempp** [contao/contao#6667]
### Affected version(s)

4.13, 5.2

### Description

Can easily be reproduced in the online demo:
 1. Login as j.lewis
 2. Click on the Info (`show`) icon of the 404 page

I think the correct fix would be to allow the show action. Because the user has access to that part of the tree (contrary to visible trail pages, that do not and should not have the info). The user just does not have access to modify these pages.

**Comment by leofeyer** [comment]
> I think the correct fix would be to allow the show action.

I think so, too. 👍

**Comment by leofeyer** [comment]
See #6778 for the fix for Contao 4.13.
