### ISSUE TITLE
Backend verwendet kein HTTPS

### ISSUE THREAD

**Issue by jxns** [contao/contao#667]
**Affected version(s)**

4.8.0

**Description**  

Seit dem Update auf 4.8.0 habe ich bei mehreren Installationen das Problem, dass im Backend nicht mehr automatisch HTTPS verwendet wird. Dies führt auch dazu, dass die Vorschaufunktion (im Backend, ganz oben der Link "Vorschau") die Seite bzw. die Vorschau nicht mehr anzeigt.

**Comment by xchs** [comment]
Magst Du Dich mit Deinem Problem im [Forum](https://community.contao.org/) melden, da es sich hier wohl um kein allgemeines Contao-Problem handelt.

**Comment by fritzmg** [comment]
Das back end hat doch noch nie automatisch HTTPS verwendet?

**Comment by jxns** [comment]
Bei der automatischen Verwendung bin ich mir nicht sicher. Mir ist nur die Problematik mit der Vorschaufunktion aufgefallen. Die tritt bei mir ausschließlich in 4.8.0 Installationen auf. Dann ist mir das mit dem HTTPS aufgefallen und ich dachte, dass es da evtl. einen Zusammenhang gibt, da auch die Vorschau dann versucht nur auf HTTP zuzugreifen. Hier kommt dann jedoch nur die Meldung: [Domainname] hat die Verbindung abgelehnt.

Rufe ich das gleiche mit dem Backend über HTTPS auf, dann funktioniert die Vorschaufunktion.

Ich kann mich ansonsten aber auch noch im Forum damit melden, falls das hier nicht so ganz herpasst?

**Comment by fritzmg** [comment]
Ja, poste das Problem im Forum und beschreibe das Problem auch genauer.
