### ISSUE TITLE
Input type text - rgxp number

### ISSUE THREAD

**Issue by bytehead** [contao/contao#668]
**Affected version(s)**
4.8 (didn't check 4.4...)

**Description**  
You can't put an empty string or something other than numbers:
![Bildschirmfoto 2019-08-23 um 13 14 00](https://user-images.githubusercontent.com/754921/63588974-1a6c6600-c5a8-11e9-9d02-7a55b94add3c.png)

If you submit an empty string, it will save as 0.

Thus you're not able to set no maximum or minimum value.
According to the spec, it should be possible:
> If the value of the max attribute isn't a number, then the element has no maximum value.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#max

**How to reproduce**  
Try to save form field with a not numeric value.

**Comment by bytehead** [comment]
Same behaviour with `minlength` and `maxlength` fields:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#maxlength

**Comment by leofeyer** [comment]
I just realized that bbce9e01939d19485914f62ba0f6810a15da91c8 does not work for `min` and `max`, as `0` is a valid value (other than for `minlength` and `maxlength`). Need to rework this.

**Comment by leofeyer** [comment]
Fixed in 2d3173b2a614e620558f96489f5d6e5f832b53b2 now.
