### ISSUE TITLE
Config for new accordion not applied

### ISSUE THREAD

**Issue by aschempp** [contao/contao#6680]
### Affected version(s)

5.3

### Description

Should the property here
https://github.com/contao/contao/blob/5.x/core-bundle/contao/templates/twig/content_element/accordion.html.twig#L32

be set from the new checkbox here?
https://github.com/contao/contao/blob/5.x/core-bundle/contao/dca/tl_content.php#L393

@leofeyer

**Comment by leofeyer** [comment]
No, that is a different option. The new checkbox controls the `data-open` attribute here:

https://github.com/contao/contao/blob/5.x/core-bundle/contao/templates/twig/content_element/accordion.html.twig#L15
