### ISSUE TITLE
Slow queries

### ISSUE THREAD

**Issue by Toflar** [contao/contao#6681]
### Affected version(s)

5.2.x

### Description

I've enabled the MySQL slow query log for 2 weeks and then used [`pt-query-digest`](https://docs.percona.com/percona-toolkit/pt-query-digest.html) to analyze the most common slow queries on a 5.2.7. 

I've filtered out a lot of them (like migration DB queries or search which are slow for a reason) but here are the ones where I think we possibly can do something about them:

1. `SELECT MAX(tstamp) AS tc, (SELECT MAX(tstamp) FROM tl_news) AS tn FROM tl_content`
2. `DELETE FROM tl_version WHERE tstamp < 1696410021`
3. `select * from  tl_version WHERE tstamp < 1696410021`
4. `select * from  tl_log WHERE tstamp < 1702854015`
5. `SELECT tl_page.* FROM tl_page WHERE tl_page.dns='<REDACTED>' AND tl_page.fallback=1 AND tl_page.published=1 AND (tl_page.start='' OR tl_page.start<=1703359140) AND (tl_page.stop='' OR tl_page.stop>1703359140) LIMIT 0,1`
6. `select * from  tl_undo WHERE tstamp < 1701597608`
7. ~~`SELECT IFNULL(MIN(id), 0), IFNULL(MAX(id), 0), COUNT(*) FROM tl_search`~~
8. ~~`SELECT id, @pid:=pid FROM tl_page WHERE id='1375' UNION SELECT id, @pid:=pid FROM tl_page WHERE id=@pid UNION SELECT id, @pid:=pid FROM tl_page WHERE id=@pid UNION SELECT id, @pid:=pid FROM tl_page WHERE id=@pid UNION SELECT id, @pid:=pid FROM tl_page WHERE id=@pid UNION SELECT id, @pid:=pid FROM tl_page WHERE id=@pid UNION SELECT id, @pid:=pid FROM tl_page WHERE id=@pid UNION SELECT id, @pid:=pid FROM tl_page WHERE id=@pid UNION SELECT id, @pid:=pid FROM tl_page WHERE id=@pid UNION SELECT id, @pid:=pid FROM tl_page WHERE id=@pid`~~ https://github.com/contao/contao/issues/6682
9. `SELECT tl_faq_category.* FROM tl_faq_category WHERE tl_faq_category.jumpTo='327'`
10. `SELECT tl_news_archive.* FROM tl_news_archive WHERE tl_news_archive.jumpTo='3289'`
11. `SELECT c.id FROM tl_content c LEFT JOIN tl_article p ON c.pid=p.id WHERE c.ptable='tl_article' AND p.id IS NULL`

**Comment by Toflar** [comment]
Here's what I think we should do:

\1) This is coming from the `{{last_update}}` insert tag, I think. Adding an index on `tstamp` would fix this.

\2), 3), 4), 6) I think we should add `index` to all `tstamp` columns. I think a lot of those queries come from sorting in the back end or from purging old entries.

\5) This we need to check, but apparently we also need to update indexes here

\7) Not sure, cc @ausi 

\8) This is `Database::getParentRecords()`. Maybe we could revisit this and `getChildRecords()` and see if there are more efficient ways to do recursive calls today (and while doing so, outsource this in a new database utility class based on the Doctrine connection instead of our old `Database` class)

\9) 10) Not sure why it's searching for strings but we miss indexes here.

\11) Looks like we're missing an index on `ptable` alone. We have one on `'pid,ptable,invisible,start,stop'` but we are querying it differently in other places apparently. Not sure where this is coming from yet.

**Comment by ausi** [comment]
> We have one on `'pid,ptable,invisible,start,stop'`

I think this needs to be changed to `'ptable,pid,invisible,start,stop'` as we never query for the `pid` without also querying for `ptable`.

**Comment by leofeyer** [comment]
Would this also require replacing `WHERE pid=? AND ptable=?` with `WHERE ptable=? AND pid=?` so the field order matches the index order?

**Comment by ausi** [comment]
> Would this also require replacing `WHERE pid=? AND ptable=?` with `WHERE ptable=? AND pid=?` so the field order matches the index order?

No, the order in the query should not be relevant.

**Comment by ausi** [comment]
> 7. `SELECT IFNULL(MIN(id), 0), IFNULL(MAX(id), 0), COUNT(*) FROM tl_search`

How slow is this? It is only used when indexing a page, so probably not that relevant.

Can you try in your setup if the following query is faster?
```sql
SELECT (SELECT MIN(id) FROM tl_search), (SELECT MAX(id) FROM tl_search), (SELECT COUNT(*) FROM tl_search);
```

**Comment by m-vo** [comment]
Is 8) coming from the old Dbafs implementation? If so, this should fix itself when we migrate away from it.

**Comment by Toflar** [comment]
> 7\. SELECT IFNULL(MIN(id), 0), IFNULL(MAX(id), 0), COUNT(*) FROM tl_search
> How slow is this? It is only used when indexing a page, so probably not that relevant.

Here's the entire info, anonymized (maybe it's just the sheer number (`--limit`)?:

```
# Query 9: 0.18 QPS, 0.00x concurrency, ID 0xE8B99B63EBBCB2CAF2E5A2DD184E42A7 at byte 5431008730
# This item is included in the report because it matches --limit.
# Scores: V/M = 0.09
# Time range: 2023-12-21 08:56:13 to 2024-01-03 07:49:58
# Attribute    pct   total     min     max     avg     95%  stddev  median
# ============ === ======= ======= ======= ======= ======= ======= =======
# Count          1  196408
# Exec time      0   1469s   124us      2s     7ms    21ms    26ms     3ms
# Lock time      2     35s    38us   742ms   176us    98us     5ms    57us
# Rows sent      0 191.80k       1       1       1       1       0       1
# Rows examine   7   1.54G       1  24.41k   8.21k  22.45k   8.22k   3.35k
# Rows affecte   0       0       0       0       0       0       0       0
# Bytes sent     0  30.22M     155     163  161.33  158.58    1.01  158.58
# Query size     0  13.11M      70      70      70      70       0      70
# String:
# Databases    <REDACTED> (80723/41%), <REDACTED> (30173/15%)... 18 more
# Hosts        localhost
# Users        <REDACTED> (80723/41%), <REDACTED> (30173/15%)... 18 more
# Query_time distribution
#   1us
#  10us
# 100us  ################
#   1ms  ################################################################
#  10ms  ############
# 100ms  #
#    1s  #
#  10s+
# Tables
#    SHOW TABLE STATUS FROM `<REDACTED>` LIKE 'tl_search'\G
#    SHOW CREATE TABLE `<REDACTED>`.`tl_search`\G
# EXPLAIN /*!50100 PARTITIONS*/
SELECT IFNULL(MIN(id), 0), IFNULL(MAX(id), 0), COUNT(*) FROM tl_search\G
```

**Comment by Toflar** [comment]
> Is 8) coming from the old Dbafs implementation? If so, this should fix itself when we migrate away from it.

No, this is coming from various places. It's `Database::getParentRecords()`.

**Comment by ausi** [comment]
> > 7. SELECT IFNULL(MIN(id), 0), IFNULL(MAX(id), 0), COUNT(*) FROM tl_search
> > How slow is this? It is only used when indexing a page, so probably not that relevant.
> 
> Here's the entire info, anonymized (maybe it's just the sheer number (`--limit`)?:

These numbers look fine to me.

**Comment by Toflar** [comment]
I agree, I'll remove it from the list.

**Comment by leofeyer** [comment]
Regarding no. 8: We should check if a recursive function is more efficient. Chances are that multiple `SELECT pid FROM tl_page WHERE id=?` queries are faster than one big one.

**Comment by Toflar** [comment]
The fastest run I could get with the current UNION query took `0.0038` seconds. But most of the time it was above `0.01` seconds or worse (the deeper the tree, the slower the query of course). Sometimes (and I think that's why it's reported in the slow query log) it takes up to half a second - probably because of exactly the multiple queries.
The WITH RECURSIVE took `0.0005` seconds on average and it was always faster.

Here's the query for `getParentRecords()`, if you want to try yourself (replace `42` with the deepest ID of your page tree) 😊 

```sql
WITH RECURSIVE trail AS (
    SELECT
        id, pid
    FROM
        tl_page
    WHERE
        id=42
    UNION ALL
    SELECT
        t.id, t.pid
    FROM
        tl_page AS t, trail
    WHERE
        t.id = trail.pid
)
SELECT id FROM trail;
```

**Comment by Toflar** [comment]
But `getChildRecords()` would benefit even more from those because there we are currently executing `n` queries, one by one. But I will extract these findings in another ticket because clearly, that is a new feature for 5.4+.

**Comment by leofeyer** [comment]
`WITH RECURSIVE` would require MySQL 8.0+ and MariaDB 10.2+. I‘m not sure if we can stop supporting MySQL 5 yet.

**Comment by Toflar** [comment]
Of course not, we can just continue to use the current fallback.

**Comment by Toflar** [comment]
PR for all the rest: https://github.com/contao/contao/pull/6683
