### ISSUE TITLE
Description of "Template Data" in "Custom Template" content element

### ISSUE THREAD

**Issue by fiedsch** [contao/contao#6685]
### Affected version(s)

4.13.x and 5.x

### Description

The description explains that the data can be accessed via `$this->data` which should be `$this->keys` as seen in the [original template](https://github.com/contao/contao/blob/33b090b8286bae096565a2c322b28d7dfef1e825/core-bundle/src/Resources/contao/templates/elements/ce_template.html5#L5)'s data access.

The same applies to the custom template module.

A PR would have to go to Transfix, wouldn't it?

**Comment by leofeyer** [comment]
You would have to update the English `tl_content.xlf` file in a pull request:

https://github.com/contao/contao/blob/a243ac38c038f4453e6a2cc7c9bb98af8a4eac68/core-bundle/src/Resources/contao/languages/en/tl_content.xlf#L236-L238

The translations will be updated on Transifex and pulled in automatically.

**Comment by fiedsch** [comment]
Thanks. Will make a PR tomorrow. Which branch should I target as the error exists in 4.x and 5.x?

**Comment by leofeyer** [comment]
Please base the PR on the `4.13` branch.

**Comment by fritzmg** [comment]
`$this->data` is correct in principle for Contao 4.13. `$this->keys` was added [later](https://github.com/contao/contao/pull/4665), deprecating the original `$this->data` key - which was then removed in Contao 5 (though we never implemented an actual deprecation for this).
