### ISSUE TITLE
Error-Log um Eintrag der Seite ergänzen

### ISSUE THREAD

**Issue by MacKP** [contao/contao#669]
Aktuell habe ich massiv viel Log-Einträge in der Art: `Unknown insert tag {{env:request}}`
Leider helfen die bereitgestellten Informationen nicht (also wer für den Aufruf zuständig ist etc.).
Schön wäre es, wenn dort noch zusätzlich stehen würde, welche Seite aufgerufen wurde um den Fehler schon mal weiter eingrenzen zu können.

**Example**  
`Unknown insert tag {{env:request}} on Page https://example.com/mynicesite.html`

**Comment by leofeyer** [comment]
Implemented in 3d65f31212123a90816fc75eb6ef1b98749285c1.
