### ISSUE TITLE
Should we ignore "fragment" templates in modules and content elements?

### ISSUE THREAD

**Issue by aschempp** [contao/contao#6694]
### Description

I currently have a project where I split my frontend module and content element tempaltes into a lot of fragments. They look something like this:

```
@Contao/frontend_module/app_project_list.html.twig
@Contao/frontend_module/app_project_list/_project.html.twig
@Contao/frontend_module/app_project_list/_empty.html.twig
```

Underscore is the kinda default prefix for a fragment as far as I know. I wonder if we should ignore templates starting with underscore in the back end `customTpl` selection?

/cc @m-vo

**Comment by m-vo** [comment]
Yes, that's exactly what I suggested a while ago. 😀
I would implement this in the Twig Finder, so that it's also available for anybody else. 

We could even make ignoring partial templates the default, if we consider the current behaviour to be a bug.

**Comment by aschempp** [comment]
I would be fine with "fixing this bug" in 5.3.

**Comment by m-vo** [comment]
See #7621.
