### ISSUE TITLE
contao backup command: disable compression via custom filename not possible

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#6698]
### Affected version(s)

Contao 5.2

### Description

Based on the docs, you can disable compression by choosing a custom filename and omit the .gz suffix, see [docs](https://docs.contao.org/manual/en/cli/db-backups/#configuration:~:text=If%20you%20want%2C%20you%20can%20change%20the%20name%20and%20thus%20the%20time%20yourself%20by%20specifying%20the%20complete%20backup%20name.%20By%20omitting%20.gz%20you%20also%20conveniently%20disable%20compression%3A)

In reality, this doesn't work. A file with custom name, for example `my_super_backup_name__20220101000000.sql` is created, but it's still a compressed file (which needs to be decompressed).

**Comment by Toflar** [comment]
Confirmed.

**Comment by Toflar** [comment]
See https://github.com/contao/contao/pull/6699
