### ISSUE TITLE
Drop phpunit/php-token-stream as requirement in contao 4.4 composer.json

### ISSUE THREAD

**Issue by fatcrobat** [contao/contao#67]
**Affected version(s)**

4.4.x

**Description**  

We test our bundles and love to make this with phpunit 7, because phpunit 6 support ends in Feb 2019. Writing tests is time consuming and we dont want to invent the wheel again. In order to support contao 4.4, 4.5 and 4.6 we are forced to stick with phpunit >=6.0 <6.5 because contao 4.4 has a requirement to  `phpunit/php-token-stream` in version 1.4. We appreciate if you remove this requirement or move it to "require-dev" section in order to test contao 4.4 with phpunit 7.

**How to reproduce**  

Run composer update with the composer.json content below:

```
{
    "name": "heimrichhannot/contao-api-bundle",
    "type": "contao-bundle",
    "description": "A generic API with restricted access to provide access to 3rd party applications.",
    "license": "LGPL-3.0-or-later",
    "require": {
        "php": "^7.1",
        "contao/core-bundle": "4.4",
        "symfony/framework-bundle": "^3.4",
        "heimrichhannot/contao-categories-bundle": "^1.0-beta",
        "urodoz/truncate-html": "^1.0",
        "firebase/php-jwt": "^4.0"
    },
    "require-dev": {
        "contao/test-case": "^1.3",
        "contao/manager-plugin": "^2.0",
        "friendsofphp/php-cs-fixer": "^2.2",
        "phpunit/phpunit": "^7.0",
        "php-http/guzzle6-adapter": "^1.1",
        "php-http/message-factory": "^1.0.2",
        "php-coveralls/php-coveralls": "^2.0",
        "symfony/phpunit-bridge": "^3.2"
    },
    "conflict": {
        "contao/core": "*",
        "contao/manager-plugin": "<2.0 || >=3.0"
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

**Comment by ausi** [comment]
I don’t think we can drop the requirement because we are using it in https://github.com/contao/contao/blob/d53d1c95840d9c660e49b97f822ff6c60d3ad16e/core-bundle/src/Config/Loader/PhpFileLoader.php#L65

However, I think we should check if Contao is compatible with `phpunit/php-token-stream` in version 3.0.0 – which is very likely I think – and change the requirement to `^1.4 || ^3.0`

**Comment by fatcrobat** [comment]
Thanks, would appreciate the update.

**Comment by leofeyer** [comment]
> we should check if Contao is compatible with `phpunit/php-token-stream` in version 3.0.0 – which is very likely I think

It is and we have already [adjusted the version](https://github.com/contao/contao/blob/4.6/core-bundle/composer.json#L60) constraint in Contao 4.6. Changed in 667a0b41de28316a6879f930965d87368b2edbb2.
