### ISSUE TITLE
Basic Entity Tags - Ersetzung des Tag [{] nach {{ funktioniert nicht mehr

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#670]
**Affected version(s)**
4.4.40
4.7.7
4.8.1

**Description**  
Früher (seit wann, weiß ich nicht) wurde `[{]` und `[}]` in `{{`und `}}` umgewandelt.
Dadurch konnte ich bei meinen Tutorials Inserttags im Klartext ausgeben, ohne dass diese umgewandelt wurden.

Leider funktioniert das inzwischen nicht mehr.

Vielleicht gibt es ja eine andere Möglichkeit, wie ich Inserttags einfügen kann und diese einfach PLAIN ausgegeben werden.

**Update - 24.08.19**
Unter Contao 3.5.40 funktioniert es noch wie erwartet.

Evtl. ist dafür diese Code-Zeile zuständig?
https://github.com/contao/core/blob/3.5/system/modules/core/classes/FrontendTemplate.php#L101

**Comment by leofeyer** [comment]
Ja, das ist mir auch schon aufgefallen. Ich hatte mir dann mit `{$shy;{` beholfen.

**Comment by contaoacademy** [comment]
Vielleicht könnte man auch einfach diese Funktion erweitern?
`restoreBasicEntities`

https://github.com/contao/contao/blob/75e6eb0974055124ef2b54389ccd0d50cf35cba5/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L252

**Comment by leofeyer** [comment]
Das wird nicht funktionieren, da die Basic-Entities beim Ersetzen der Inserttags mit ersetzt werden (siehe b04d617f30d081ea7c1120909d9e3ff007800b9d) – was meiner Meinung nach allerdings falsch ist.

Wurde hier geändert: https://github.com/contao/contao/commit/ae29d98681f7e606682746ef18938c2f3041a907#diff-517f6dbd45c267ecfdc015aabdb4d0bfL136

**Comment by contaoacademy** [comment]
Wäre es denkbar, dass man beim InsertTag einen zusätzlichen Parameter erstellt.
`{{ua::browser|skip}}`

Durch das `skip` würde der Insertag einfach ausgegeben werden, ohne diesen zu nutzen.

**Comment by fritzmg** [comment]
Das würd mit der aktuellen, rekursiven Implementation nicht funktionieren.

**Comment by leofeyer** [comment]
Behoben in b93ee638549f982b826ff6c346b9060a0cb0f557.
