### ISSUE TITLE
dcapicker with globe has too much padding right

### ISSUE THREAD

**Issue by erikherbert** [contao/contao#6705]
### Affected version(s)

4.13.*

### Description

The content of the input is truncated on the right. The icon was once in the input.

https://github.com/contao/contao/blob/e352dbeab7c0aaa7524fdd1b7db4528736f11909/core-bundle/contao/themes/flexible/styles/basic.css#L872

<img width="1019" alt="Bildschirmfoto 2024-01-11 um 13 02 56" src="https://github.com/contao/contao/assets/1622733/e34df713-5c27-4513-abe9-4a5bc87acb32">
<img width="843" alt="Bildschirmfoto 2024-01-11 um 13 02 01" src="https://github.com/contao/contao/assets/1622733/f2b2da15-991d-498e-b56a-98630c8d62c9">

**Comment by leofeyer** [comment]
Fixed in 46d7548e1d9306f17da71edaea68a183719ec273.
