### ISSUE TITLE
Fehler in Versionsübersicht bei umbenannten Ordnern

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#671]
Nach der Umbenennung eines Ordners in der Dateiverwaltung führt auf der Startseite des Backends in der Tabelle "Zuletzt bearbeitet" ein Klick auf eines der beiden Icons des entsprechenden Eintrags zu einem Fehler:

> Forbidden
> Was ist das Problem?
> File or folder "files/alter-name" is not mounted or cannot be found.

In der Fehlermeldung wird der alte Name des Ordners, wie er vor der Umbenennung war, angezeigt.

**Comment by leofeyer** [comment]
Behoben in f8ae36aeceba761e530d40c5a29dbf0fa22a7c45.
