### ISSUE TITLE
TinyMCE does not display any content

### ISSUE THREAD

**Issue by jedoCodes** [contao/contao#6713]
### Affected version(s)

5.2.7

### Description

TinyMCE does not display the text in MacOS Safari. I can only edit it when I display the raw data (HTML string).

This concerns the Contao 5 versions, the 4.13 does not seem to be affected.

I can only work around this by changing the user agent to Chrome or Firefox. 

- php82
- Contao 5.2.7 - cleanInstall (no extensions)
- Safari 17.2.1

![Screenshot at Jan 14 09-01-02](https://github.com/contao/contao/assets/1821865/db502d8f-a835-449d-929c-f5e8b56b579f)
![Screenshot at Jan 14 09-01-25](https://github.com/contao/contao/assets/1821865/503d14e4-58e9-46ba-9bdf-fbfc651e7319)

**Comment by leofeyer** [comment]
Sorry for the late reply. Does this issue still occur in Contao 5.3?

**Comment by jedoCodes** [comment]
I'm currently using Contao 5.4 and the problem doesn't exist.

Thanks
