### ISSUE TITLE
`PageModel:: findFirstPublishedByPid()` should not return an XML page

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6715]
### Affected version(s)

5.2

### Description

The `PageModel:: findFirstPublishedByPid()` method should skip the news feed page, because it returns an XML response and not an HTML response.

https://github.com/contao/contao/assets/1192057/6f7b5c26-4162-4d01-a47d-13ff773fbc1c

**Comment by aschempp** [comment]
Quoting @fritzmg

> Wenn du nicht den Alias `index` nutzt, zeigt dir Contao die erste Seite im Seitenbaum an. Daher solltest du auch dort die Seite platzieren, die du anzeigen willst. Und nicht den News Feed bspw. (und auch nicht die anderen Systemseiten imho)

I fully agree with that statement. It's a misconfiguration, not a bug in the system.

**Comment by aschempp** [comment]
The origin of this issue if probably the `FeedMigration` which should be fixed in https://github.com/contao/contao/pull/6963

**Comment by leofeyer** [comment]
As discussed in the Contao core, we want this behavior change, so arbitrary page controllers can be used as "first regular page".
