### ISSUE TITLE
Simple Tokens not allowing # before simple token

### ISSUE THREAD

**Issue by koertho** [contao/contao#6716]
### Affected version(s)

4.13.x

### Description

Putting a # in front of an simple token will hinder replacing the simple token.

Example: ###order_id## will not be replaced (explected output for example #5300)

Tested in:
Contao 4.13.35
PHP 8.2.13

This was also discussed in Slack: https://contao.slack.com/archives/CK4J0KNDB/p1705315711120819

**Comment by Toflar** [comment]
See https://github.com/contao/contao/pull/6717
