### ISSUE TITLE
CSP breaks the form fields

### ISSUE THREAD

**Issue by aschempp** [contao/contao#6722]
### Affected version(s)

5.3

### Description

The new CSP features seem to break form fields in the front end.

> Attempted to call an undefined method named "attr" of class "Contao\FormCaptcha".

https://github.com/contao/contao/blob/5.x/core-bundle/contao/templates/forms/form_captcha.html5#L25

This is probably because widget templates do not extend from `Template` but from `Widget`.

**Comment by fritzmg** [comment]
Closing in favour of #6723
