### ISSUE TITLE
Page included in sitemap.xml even if you select "show never".

### ISSUE THREAD

**Issue by xApep** [contao/contao#6728]
### Affected version(s)

4.13.35

### Description

If you set Show in sitemap to "show never", page is still included in sitemap.xml
![image](https://github.com/contao/contao/assets/1315340/406f9947-339e-439a-bc09-4c11a1fab7d8)

**Comment by fritzmg** [comment]
This setting refers to the HTML sitemap module and has no effect on the `sitemap.xml`.

If you want a page to not show up in the `sitemap.xml` then you will need to set the robots tag to `nofollow,noindex`.

**Comment by xApep** [comment]
Haha, so after 15 years of using Contao, now I know that this does not exclude page from sitemap 😅

Thank you mister and sorry for not publishing a bug.

**Comment by fritzmg** [comment]
> Haha, so after 15 years of using Contao, now I know that this does not exclude page from sitemap 😅

Well it hasn't always been this way ;).

**Comment by de-es** [comment]
Related https://github.com/contao/contao/issues/6647
