### ISSUE TITLE
Use a faster hash algorithm to generate the CSP hashes

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6729]
### Description

Is it really necessary to use `sha384` to generate the CSP hashes? Since we don‘t encrypt sensitive data here, a faster algorithm such as `sha256` could speed things up, don‘t you think? @fritzmg @Toflar /cc

**Comment by fritzmg** [comment]
Nelmio uses `sha256` by default, `paragonie/csp-builder` used `sha384` by default.  I chose the latter as "more is always better" but may be not ;)

**Comment by Toflar** [comment]
`sha384` does not suffer from length extension attacks. Looks like `sha384` is actually faster than `sha256` on 64-bit machines because then it can use 64-bit words.

For reference: https://pycryptodome.readthedocs.io/en/latest/src/hash/sha384.html and https://en.wikipedia.org/wiki/SHA-2.

**Comment by fritzmg** [comment]
Then we keep `sha384` as the default, right?

**Comment by leofeyer** [comment]
The information in the linked article is a bit confusing:

<img width="738" alt="" src="https://github.com/contao/contao/assets/1192057/42ac9d63-f66c-427f-a036-04a90d1b1cdd">

What is it now?

**Comment by fritzmg** [comment]
They mean SHA-512/256, which is not the same as SHA-256. SHA-512/256 is a truncated version of SHA-512. SHA-512/256 is faster on 64-bit machines than SHA-256.

**Comment by Toflar** [comment]
SHA-512/256 is not the same as SHA-256. SHA-512/256 is a truncated version of SHA-512 (just like SHA-384).

SHA-256 uses eight 32-bit words. SHA-512 (and SHA-384) use 64-bit. 

See Wikipedia:

> SHA-224 and SHA-384 are truncated versions of SHA-256 and SHA-512 respectively, computed with different initial values. SHA-512/224 and SHA-512/256 are also truncated versions of SHA-512, but the initial values are generated using the method described in [Federal Information Processing Standards](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards) (FIPS) PUB 180-4.

**Comment by leofeyer** [comment]
TIL 😄 Thank you both.
