### ISSUE TITLE
Drop MyISAM support

### ISSUE THREAD

**Issue by m-vo** [contao/contao#673]
The InnoDB implementation of modern databases (>= MySQL 5.7) doesn't lack any<sup>\*)</sup> of the earlier MyISAM features like fast reads or full text indexing. Imho, today, MyISAM should only be used in exoctic cases where there is a minimal performance benefit needed or maybe for huge tables and critical disk space (or if there is no alternative of course). 

I'm not fully aware of the InnoDB support on shared hosting nowadays - I didn't come across one that was **not** supporting InnoDB for a long time.

Dropping MyISAM support<sup>\*\*)</sup> would allow:

* easier refactoring
* use of transactions everywhere (as a speed booster)
* set the stage for FK implementations with delete cascades

<sup>\*)</sup> they can indeed still be a bit smaller and store the count making count(*) faster, but hey...
<sup>\*\*)</sup> for core tables

**Comment by fritzmg** [comment]
So far I have only encountered Hosters that did not support MyISAM anymore - not the other way around.

**Comment by m-vo** [comment]
Good read about MyISAM very likely beeing faded out in the future: https://stackoverflow.com/questions/47680213/what-are-the-current-differences-between-myisam-and-innodb-storage-engines-speci/48302638#48302638

Also this, Oracle recommending InnoDB except for *specialized use cases* and putting MyISAM to the list of *Alternative Storage Engines* in MySQL 8.0:
https://dev.mysql.com/doc/refman/8.0/en/storage-engines.html

**Comment by leofeyer** [comment]
You probably remember that we tried to establish MySQL 5.7.7 and InnoDB as system requirements in Contao 4? Long story short, we could not. 😄

Therefore dropping MyISAM support is off the table for Contao 4.

**Comment by m-vo** [comment]
But a) time has passed and b) if we decide to drop it in Contao 5, we should imo add a deprecation warning. So I think discussing this issue is legitimate.
