### ISSUE TITLE
Let‘s talk about assignments in conditions

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6733]
### Description

There are many discussions about assignments in conditions and whether to use them or not, e.g.

* https://www.drupal.org/project/coding_standards/issues/2907332
* https://github.com/phpstan/phpstan/issues/647
* https://github.com/squizlabs/PHP_CodeSniffer/issues/2891
* https://www.reddit.com/r/PHP/comments/2abiqa/var_assignment_in_condition/

I took a look at our codebase and found three groups of assignments in conditions:

### Simple cases

```php
if (!$feed = $adapter->findByPk($feedId)) {
}
```

```php
if (!$request = $this->requestStack->getCurrentRequest()) {
}
```

```php
while (false !== ($pos = strrpos($part, '/'))) {
}
```

```php
if (null === ($value = $row[$mandatoryKey] ?? null)) {
}
```

### Assignment in function calls

```php
if (is_file($manifestPath = Path::join($path, 'manifest.json'))) {
}
```

```php
if (\in_array($extension = ContaoTwigUtil::getExtension($path), ['html.twig', 'html5'], true)) {
}
```

### Complex cases

```php
if ((!$page = $this->getPageModel()) || null === $page->layout) {
}
```

```php
if (($expression = iterator_to_array($filterArgs)[0] ?? null) instanceof ConstantExpression) {
}
```

The complex cases are tricky to analyze statically (both in PhpStorm and in PHPStan), so we often had to use inline `/** @var */` comments to work around this in the past. If we simplified those cases, we could get rid of the workarounds.

So my question is: To what extent do we want to keep using assignments in conditions in the future?

**Comment by aschempp** [comment]
I found out that tools are able to analyze this version, which is fine with me:

```
if (($expression = iterator_to_array($filterArgs)[0] ?? null) && $expression instanceof ConstantExpression) {
}
```

**Comment by leofeyer** [comment]
No, they are not. As you see, PhpStorm assigns `mixed|null` instead of `ConstantExpression`:

<img width="796" alt="" src="https://github.com/contao/contao/assets/1192057/4be2214e-469c-4471-a5f7-1992ba7b7e1b">

---

As soon as I take the assignment out of the condition, it analyzes everything correctly:

<img width="813" alt="" src="https://github.com/contao/contao/assets/1192057/762a2dce-b308-4479-a48d-34caa1c6cf90">

**Comment by m-vo** [comment]
As long as things do not get too long and they are coupled to the following code part, I like inline assignments.

They can also make use of short circuiting:

```php
f(false && $foo = 'thing') {
  // do something with foo
}

// no unnecessary assignment happened
```
