### ISSUE TITLE
Termine werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by uliverse** [contao/contao#674]
Nach Update von 4.6 auf 4.8 werden Events nicht mehr aufgelistet. Es erscheint der Hinweis: „Aktuell sind keine Termine vorhanden”.
Dasselbe Problem habe ich auch bei einer neuen Installation.

**Comment by leofeyer** [comment]
Wie lässt sich das Problem in der [Online-Demo](https://demo.contao.org/contao) reproduzieren?

**Comment by uliverse** [comment]
Dort kann ich es leider nicht reproduzieren. Der Fehler tritt jedoch lokal auf (AMPPS, PHP 7.1.8, MySQL 5.6.36)

**Comment by leofeyer** [comment]
Dann musst Du herausfinden, warum das bei Dir lokal so ist. Eventuell liegt es an einer Drittanbieter-Erweiterung.
