### ISSUE TITLE
Symfony translations are not loaded if no Contao language file exists

### ISSUE THREAD

**Issue by aschempp** [contao/contao#6741]
### Affected version(s)

5.3

### Description

I have created a new DCA with translations in `/translations/contao_tl_my_dca.en.yaml`. The file is not loaded as long as there is no _legacy_ language file, e.g. in `/contao/languages/en/tl_my_dca.php`. As soon as I add the legacy file, even if it is empty, the Symfony translations are loaded as expected.

**Comment by aschempp** [comment]
@ausi any idea how to fix this?

**Comment by fritzmg** [comment]
I think you mean me? I haven't looked into it yet, sorry 🙈

**Comment by ausi** [comment]
> @ausi any idea how to fix this?

I think we should add it in the cache warmer here: https://github.com/contao/contao/blob/4034b234a11241e225c67ad86ee94dec0cbf690a/core-bundle/src/Cache/ContaoCacheWarmer.php#L173-L177

**Comment by fritzmg** [comment]
See #6889
