### ISSUE TITLE
Rebrand Twitter to X

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6748]
### Affected version(s)

5.3.0-RC1

### Description

This is not high priority but I think we should change "Twitter" to "X".
I find it sufficient enough to do this only in 5.3 - wdyt?

Backend -> Article details -> syndication -> "Share on Twitter"
Frontend -> change icon and link

**Comment by zoglo** [comment]
Shouldn't we call it `X / Twitter` instead?

**Comment by ausi** [comment]
I think `X (formerly Twitter)` or `X, formerly known as Twitter` are widely used

**Comment by fritzmg** [comment]
twitter.com itself also uses

```html
<meta content="X (formerly Twitter)" property="og:site_name" />
```

**Comment by leofeyer** [comment]
Changed in 48ed7bf92ba59a0bb65aae2929e4256475d8588e.
