### ISSUE TITLE
Remove css class “rte”

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6751]
### Affected version(s)

5.3.0-RC1

### Description

Content elements of type “text” get wrapped in a `<div>` with class “rte” since Contao 5 (I think):

```
<div class="rte">
   <p>My text</p>
</div>
```

I don’t know when this was introduced exactly.
I assume “rte” stands for “rich text editor”. However, I don't see the point behind it. For me this is just "overhead" in the html output.

If there is a reason for having this, it should be documented somewhere.

**Comment by asaage** [comment]
I think it's really convenient because ist separates rte content from headings and add-image in content-text and it is reusabe for teasers, accordions and other elements. It makes consistent text-styling so much easier and i already use it.

**Comment by m-vo** [comment]
> I assume “rte” stands for “rich text editor”.

Yes.

I second what @asaage pointed out. On the editor side, you can allow certain tags and styling options that are available in the rich text editor. To style those things with CSS, you IMHO want to have a selector that matches those things as closely as possible.

I thought about adding a `_rich_text` component. Then you could not only adjust/remove the class to your liking by editing one file but also keep all applied filters the same everywhere (like `|insert_tag_raw|encode_email` or the like).

**Comment by jochi44** [comment]
OK, got it.
As 5.3 is the next LTS I was testing extra carefully.
And I know, that you guys are always following the principles of lean coding.
I'm closing this issue.
