### ISSUE TITLE
Rows loaded via Ajax are missing click events

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6752]
### Affected version(s)

5.3.0-RC1

### Description

First of all, sorry for the long title 😉
There is a non consistent strange behavior where sometimes clicking somewhere in a row of a check option would not tick the checkbox. Note: Ticking the checkbox itself always works.

I think I found a reproducible example:

1.	Make sure you have uploaded some files onto your Contao installation.
2.	Go to CONTENT -> Files
3.	Collapse all by clicking the small arrow-right icon of the root folder
4.	Click “Edit multiple”
5.	Click “Expand all”
6.	Try to select a folder or a file with clicking somewhere in the desired “row”.

Result:	The checkbox on the far-right side would not check.

This happens to me throughout all the various backend check menus (e.g. selecting an image in a content element; selecting a css file in the external style sheets selection of a page layout,…) but not consistently.

I’m running Google Chrome v120.0.6099.225 (64 bit).
No errors in the browser console.

**Comment by zoglo** [comment]
~~Can't reproduce that behavior on current RC1~~

**Comment by leofeyer** [comment]
I can confirm the issue. @aschempp I think we have to adjust the Stimulus controller to add the missing events to the rows loaded via Ajax?

**Comment by zoglo** [comment]
Can confirm that `toggle-nodes-controller.js` is causing the issue

**Comment by fritzmg** [comment]
Well the issue is that the event listener for the row click is still added via legacy JavasScript instead of a stimulus controller, no?

**Comment by zoglo** [comment]
> Well the issue is that the event listener for the row click is still added via legacy JavasScript instead of a stimulus controller, no?

It doesn't exist at all for the row click. Removing the toggle nodes controller did readd it so this might actually be the case and it's getting removed but not added by the controller?

**Comment by fritzmg** [comment]
> It doesn't exist at all for the row click.

Not sure what you mean? It does exist - but it's not applied after an additional subtree has been loaded via AJAX. The solution is to implement `Backend.enableToggleSelect` as a stimulus controller instead.

**Comment by fritzmg** [comment]
Although I just noticed that our `toggle-nodes-controller` already dispatches the `ajax_change` event which _should_ actually add the event listener again.

https://github.com/contao/contao/blob/92cebdc7714121a2120f668e8a9b78468fa27278/core-bundle/assets/controllers/toggle-nodes-controller.js#L143-L144

https://github.com/contao/contao/blob/92cebdc7714121a2120f668e8a9b78468fa27278/core-bundle/assets/scripts/core.js#L2305-L2308

**Comment by zoglo** [comment]
@fritzmg

I just replaced window.addEvent() with the native window.addEventListener() and it does work for me.
> https://github.com/contao/contao/blob/92cebdc7714121a2120f668e8a9b78468fa27278/core-bundle/assets/scripts/core.js#L2305-L2308

I am unsure why the added listener via ["MooTools addEvent"](https://mootools.net/core/docs/1.6.0/Element/Element.Event#Element:addEvent) does not listen to it.

Wouldn't it work if we replace it with https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener since it's the same anyways?

I just tested on a 5.2 and the ```window.addEvent('ajax_change' ``` doesn't trigger because the page always reloads when expanding all files.

To make sure there is no other issues with ajax involved, shouldn't
> https://github.com/contao/contao/blob/92cebdc7714121a2120f668e8a9b78468fa27278/core-bundle/assets/scripts/core.js#L976-L981

be changed as well?

**Comment by leofeyer** [comment]
> I just replaced window.addEvent() with the native window.addEventListener() and it does work for me.

I think that is the right fix anyway. 👍

**Comment by fritzmg** [comment]
I don't think we can really switch everything from MooTools events to native events, technically, can we? If someone had a MooTools event listener in the back end in their own code, it won't work anymore. Though we could create "bridge event listeners" for BC (listen to native event, then fire MooTools event as well - or vice versa, depending on what we do).

**Comment by leofeyer** [comment]
Hm, good point. Maybe @aschempp can help here?

**Comment by zoglo** [comment]
Fixed in #6784

See: https://mootools.net/core/docs/1.5.1/Element/Element.Event#Element:fireEvent

Gotta fire the correct Event for MooTools since it's a hook for it.
