### ISSUE TITLE
Content element “Download” - option “Full-size view/new window” has no effect

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6754]
### Affected version(s)

5.3.0-RC1

### Description

Note: I’ve tested this with a file of type “pdf”.

Option “Show preview images”
Checking the option “Full-size view/new window” inside has no impact, the pdf file is shown in the current browser window not in a new window.

**Comment by asaage** [comment]
This is related to the preview-image - do you have a lightbox enabled?
The option you are looking for is probably " Show in browser / Show the file in the browser instead of opening the download dialog."

**Comment by fritzmg** [comment]
As also mentioned [here](https://github.com/contao/contao/issues/6756#issuecomment-1902683865) this option relates to the preview images, not the actual download file itself.

**Comment by ausi** [comment]
Closed in favor of #6755
