### ISSUE TITLE
Add Level for Section Headline in new Accordion Elements

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#6763]
### Description

**Current Behaviour:** By default, the new accordion toggler in Contao 5.3 is a `<h3>`. In former versions it was a `<div>`, which is quite neutral and you don't need to care of headlines before and after accordions. 

If you have a look at the [Contao Demo](https://demo.contao.org/accordion.html), in this case you would have a missing `<h2>` headline and some SEO and Usability Tools would complain that (including google lighthouse).

**Possible Solutions:** add a select field to choose the headline level or switch back to neutral `<div>`.

**Comment by fritzmg** [comment]
imho this should be considered a bug. If you have a `<h3>` or `<h4>` right before an accordion and the accordion content is supposed to be semantically structured within that section then it would currently be structured in the wrong way. And creating a custom template for each use-case is probably not the right way to go.

**Comment by asaage** [comment]
Honestly i would prefer to get rid of the mooHeadline field all together and use the headline field.
I can't think of any reason why the mooHeadline shouldn't be one of h1-h6.
You get the flexibility without adjusting the template, it would also ease switching betwen text-element and accordion type and improve the look of it in the BE.
![image](https://github.com/contao/contao/assets/4138336/b6eb09d1-feca-4022-9dcf-b3152e3ed6c3)

**Comment by asaage** [comment]
If you decide to go that route (eliminating mooHeadline) https://github.com/contao/contao/pull/6765 could come in handy to still have a neutral option.
I'm afraid there will be a debate about paragraph not being a headline though 🙈.

**Comment by denniserdmann** [comment]
> Honestly i would prefer to get rid of the mooHeadline field all together and use the headline field.

+1 for that. This would solve another problem with the current order, having a headline before the section headline, but the output is the opposite: 

<img alt="" src="https://github.com/contao/contao/assets/3773697/8796649d-1b38-4559-8a3d-37e6a5bfa174">

vs.

<img alt="" src="https://github.com/contao/contao/assets/3773697/0ae7f787-28b1-4a53-a57a-732f7b7da84f">

**Comment by asaage** [comment]
@denniserdmann your first screenshot confuses me. How can you have both headline and sectionheadline?
Is that the nested-element's feature of 5.3?

**Comment by denniserdmann** [comment]
@asaage exactly.

**Comment by asaage** [comment]
so we still have separation between headline and section-headline and no div 🤔

**Comment by fritzmg** [comment]
@asaage what do you mean?

**Comment by asaage** [comment]
I did not tinker with 5.3 yet (just 5.2 without the nested elements).
I thought we would use headline for the toggle but it seems now there will be two seperate fileds headline and section-headline.
Earlier there was just one: mooHeadline (if it's an accordion) and headline if it's any other element.

**Comment by fritzmg** [comment]
Yes, the _Section headline_ is always the headline of the section, similar to `mooHeadline`.

Any other headline is then just a regular headline within the accordion content.

**Comment by asaage** [comment]
So in therory its just a regular content-text-element and if i pull it out of the wrapper the section-headline is gone?
If that's the case i already dont't like the concept 🙈.
Until now one could at least switch the element-type and copy-paste from mooheadline to headline or the other way around.

**Comment by skipman** [comment]
I think we should ask Nina (Gerling) at the next Contao show which solution is more accessible.

Personally, I lean towards a div. 20 FAQs and each time the editor has to choose the right headline tag for this page I don't think it's particularly user-friendly. And 20 Headlines may be confusing. And 20 headings in a row can be irritating or disruptive, especially with short answers.
