### ISSUE TITLE
Legacy-Elemente (Slider Umschlag Anfang) - add classes

### ISSUE THREAD

**Issue by berecont** [contao/contao#6768]
### Affected version(s)

5.3.x-dev

### Description

to work with swiperJS Framework, there should be two more classes
`'swiper'` and `'swiper-wrapper'`

```
<div class="<?= $this->class ?> block"<?= $this->cssID ?><?php if ($this->style): ?> style="<?= $this->style ?>"<?php endif; ?>>

  <?php if ($this->headline): ?>
    <<?= $this->hl ?>><?= $this->headline ?></<?= $this->hl ?>>
  <?php endif; ?>

  <div class="content-slider swiper" data-config="<?= $this->config ?>">
    <div class="slider-wrapper swiper-wrapper">
```

**Comment by fritzmg** [comment]
To clarify: @berecont means when you are using the legacy `Contao\ContentSliderStart` and `Contao\ContentSliderStop` content elements via

```php
// contao/config.php
$GLOBALS['TL_CTE']['slider']['sliderStart'] = \Contao\ContentSliderStart::class;
$GLOBALS['TL_CTE']['slider']['sliderStop'] = \Contao\ContentSliderStop::class;
```

**Comment by leofeyer** [comment]
The legacy elements only work with the legacy slider script `contao-components/swipe`. If you want to use the new `contao-component/swiper` script, you have to use the new swiper element.

**Comment by fritzmg** [comment]
This means though that all Contao installations using the slider will break when updating to Contao 5.3+ currently, as Contao 5.3 re-uses the `js_slider` template.

**Comment by leofeyer** [comment]
> as Contao 5.3 re-uses the `js_slider` template.

What do you mean?

**Comment by fritzmg** [comment]
Oh, never mind, my mistake. The `js_slider` template is unchanged and the new Swiper's script is in contained within `swiper.html.twig` 👍
