### ISSUE TITLE
Wrong ptable when nesting an element in "edit multiple" mode

### ISSUE THREAD

**Issue by MarkejN** [contao/contao#6772]
### Affected version(s)

5.3.x-dev

### Description

I have a content element that I want to insert into the new accordion element (in my case the ID `3`). When I move it with the move operation, it works fine: `pid` is changed to `3` and `ptable` to `tl_content`. However, when I move it in multi-edit mode, only the `pid` is changed to 3 and the `ptable` remains `tl_article`, causing the element to disappear in the backend.

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
I was able to reproduce the issue. In my test the same issue happens when trying to move elements via edit-multiple from `tl_article` to `tl_news` for example (But only in 5.3, 5.2 does not seem to be affected).
