### ISSUE TITLE
2FA - scanning of QR code in dark mode not working

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6773]
### Affected version(s)

5.x

### Description

When running the Contao backend in “dark mode” the scanning of the QR code when enabling two factor authentication is not working. At least I didn’t get it to work.

Maybe we can introduce a catchy hint somewhere to switch to light mode for the scanning of the QR code or force the `<div class="two-factor">` to have a light background and dark elements.

PS: Thanks to the nice post man telling me this recently when I was trying to scan a QR code from my phone which is running on dark mode 😊.

**Comment by fritzmg** [comment]
Why would QR codes not work with a black/dark surrounding background? Or does our QR code not have a sufficiently large white margin?

**Comment by jochi44** [comment]
@fritzmg I don't know. Could you please try it?

**Comment by bytehead** [comment]
works in my local demo:

![Bildschirmfoto 2024-01-25 um 11 02 04](https://github.com/contao/contao/assets/754921/0190be34-e7ab-4a1e-b55d-b92a00ee2290)

**Comment by fritzmg** [comment]
I do think we need to add a white margin to the QR code though, as some QR code scanners might not work properly without it.

**Comment by leofeyer** [comment]
Works for me, too. Which phone did you use?

**Comment by fritzmg** [comment]
It also does not work with my Android phone (Motorola One Vision).

**Comment by leofeyer** [comment]
And can you please test if the following CSS rule fixes the issue for you:

```css
.two-factor .qr-code img {
    border: 1px solid #fff;
}
```

**Comment by fritzmg** [comment]
The 1px border was enough for my phone. However I think we should choose a border with at least the pixel size of the QR code - 3px in our case.

**Comment by bytehead** [comment]
Better like this? 

![Bildschirmfoto 2024-01-25 um 17 54 06](https://github.com/contao/contao/assets/754921/5fea7ba1-b322-4cda-a4bb-5c2942cc368a)

**Comment by jochi44** [comment]
> Better like this?
> 
> ![Bildschirmfoto 2024-01-25 um 17 54 06](https://private-user-images.githubusercontent.com/754921/299744987-5fea7ba1-b322-4cda-a4bb-5c2942cc368a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMDQ2MzIsIm5iZiI6MTcwNjIwNDMzMiwicGF0aCI6Ii83NTQ5MjEvMjk5NzQ0OTg3LTVmZWE3YmExLWIzMjItNGNkYS1hNGJiLTVjMjk0MmNjMzY4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxNzM4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzIyZjE1NDk2Mzg4ZDVhOWIyNDJiYTY1ZWE3Yzg3OWM4MGNhNTJhOWY2MzM3NTUzN2YxMTVjMGI1OTNlYzZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A_QZhImz64oyGEtzwntyyedSQ0KVpds8-vs2IMZ7pgk)

It's working now on my Google Pixel 👍
