### ISSUE TITLE
Nested Elements: Back-Button after element creation leads to dashboard

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#6776]
### Affected version(s)

5.3.X

### Description

If go inside one of the new nested elements, such as accordion or slider and add a new content-element (by creating a new or moving an existing element), the back-button loses it's target and leads back to the dashboard (`/contao`).

Hint: This doesn't happen if i 'm just watching what's inside the nested element.

**Comment by aschempp** [comment]
Can confirm, happened to me a lot as well.
