### ISSUE TITLE
'alias' db fields are too short

### ISSUE THREAD

**Issue by pgerundt** [contao/contao#678]
Just ran into an error when trying to save a news with a long (> 128 chars) headline:

'headline' is `maxlength 255` and type `varchar(255)`
https://github.com/contao/news-bundle/blob/60c04935829aa6251e40ef47542de5fdca5d6d50/src/Resources/contao/dca/tl_news.php#L166
but 'alias' is only `maxlength 128`and type `varchar(128)`
https://github.com/contao/news-bundle/blob/60c04935829aa6251e40ef47542de5fdca5d6d50/src/Resources/contao/dca/tl_news.php#L174

Same goes for 'title' and 'alias' in tl_page:
https://github.com/contao/core-bundle/blob/144dd53a10c22f9ad58312c0e22faa9ffcd6bfa7/src/Resources/contao/dca/tl_page.php#L218

**Comment by leofeyer** [comment]
I am not sure if 255 characters long aliases make much sense, so instead of increasing the alias field length, we could also cut the title/description after 128 characters.

@contao/developers WDYT?

**Comment by Toflar** [comment]
I think increasing to 255 makes sense. Not when I think about a news alias but when I think about a page alias that also contains folders, I see that 128 may be too short. Think about something like `/about-the-company/customer-relations-department/team-members/elizabeth-hamilton.html` - this is not a super special page alias but already about 80 chars long. I'm sure there are valid use cases for 255 chars. I wouldn't go any longer though.
It doesn't affect the db indexes either.

**Comment by leofeyer** [comment]
True. 👍

**Comment by leofeyer** [comment]
Fixed in f8d1f44665e62aa79a65b9b86baf58973334cf26.
