### ISSUE TITLE
Improve text|csp_inline_styles|insert_tag|encode_email|raw

### ISSUE THREAD

**Issue by ausi** [contao/contao#6783]
### Description

https://github.com/contao/contao/pull/6719#discussion_r1460420443
> … I just think that `text|rich_text` would be a much better DX than `text|csp_inline_styles|insert_tag|raw`. Can we create filters that combine other filters? Then we could have both the `csp_inline_styles` filter and the `rich_text` filter.

> OK, so you would want a `rich_text` filter that is the combination of `|csp_inline_styles|insert_tag|raw`?
> > Can we create filters that combine other filters?
> 
> I guess we could just call the runtime methods directly one after the other, but I’m not sure how to handle `is_safe` and `preserves_safety`.
> 
> I think we should name this filter here `csp_inline_styles` then, and create a new ticket for a “combined filter” called `rich_text` where we can discuss if and how we want to implement the chaining.

https://github.com/contao/contao/issues/6751#issuecomment-1902613045
> I thought about adding a `_rich_text` component. Then you could not only adjust/remove the class to your liking by editing one file but also keep all applied filters the same everywhere (like `|insert_tag_raw|encode_email` or the like).

These are two suggestions how to improve not having to write `{{ text|csp_inline_styles|insert_tag|encode_email|raw }}` repeatedly in many templates. I think I favor the `_rich_text` component solution.

**Comment by leofeyer** [comment]
> I think I favor the `_rich_text` component solution.

Me too.

**Comment by m-vo** [comment]
See #7034
