### ISSUE TITLE
Document deprecation of {{link::back}}

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6785]
### Description

The insert tag `{{link::back}}` is deprecated since Contao 4.9 and doesn't work in Contao 5.x. I couldn’t find the deprecation to be documented anywhere.
Is this worth to be documented somewhere (DEPRECATED.md for 5.3 or in the official documentation)?

**Comment by zoglo** [comment]
Related issue: #6344 

Still in documentation: https://docs.contao.org/manual/en/article-management/insert-tags/#link-elements

The Deprecated.md of 4.9 and 4.13 doesn't say anything about it, nor seeing anything within upgrade.md

**Comment by leofeyer** [comment]
There is a deprecation in Contao 4.13:

https://github.com/contao/contao/blob/46d7548e1d9306f17da71edaea68a183719ec273/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L490

But the Contao manual sure needs to be adjusted. Can you open a ticket there?

**Comment by jochi44** [comment]
Done -> https://github.com/contao/docs/issues/859#issuecomment-1911710456
