### ISSUE TITLE
Improvements to legacy accordion elements

### ISSUE THREAD

**Issue by jochi44** [contao/contao#6786]
### Description

a) Element type “accordion single element”

- The `<section>` has css class `"ce_text"` assigned which should be `"content-text"` to fit the Contao 5 convention or be removed.
- The things entered in the rich text editor should be wrapped in a `<div class="rte"></div>` (the `<div>` is there, the class is missing) to fit the Contao 5 convention.

b) Element type "Accordion wrapper stop"

- The "Accordion settings" (-> Element classes) in the backend are useless and could be removed.

c) New handorgel.js

- `<body>` ID

When activating the java script template `"js_accordion"` in a page layout, the website gets the `<body>` ID `"handorgel1"` assigned which I think is not ideal and probably some people don’t want. But probably it’s technically necessary 🤷‍♀️.

- Info notice
When creating an element of type "accordion single element" or "accordion wrapper start" the info text at the top of the page `"The moo_accordion or j_accordion template needs to be included in the page layout."` should also include `"js_accordion"` (=the javascript template) which is (as far as I got) the new handorgel.js solution.

**Comment by zoglo** [comment]
> * Info notice
>   When creating an element of type "accordion single element" or "accordion wrapper start" the info text at the top of the page `"The moo_accordion or j_accordion template needs to be included in the page layout."` should also include `"js_accordion"` (=the javascript template) which is (as far as I got) the new handorgel.js solution.

This should be a separate issue if that's the case for the accordion that works with Handorgel.js.

**Comment by fritzmg** [comment]
@jochi44 the legacy elements will not be changed.

**Comment by jochi44** [comment]
OK, got it.
I assume the legacy elements will die in a future Contao version.

**Comment by jochi44** [comment]
OK, got it.
I assume the legacy elements will die in a future Contao version.

**Comment by jochi44** [comment]
OK, got it.
I assume the legacy elements will die in a future Contao version.
