### ISSUE TITLE
Contao 4.8.1 broken newsletter labels

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#679]
**Affected version(s)**
Contao 4.8.1

**Description**  
All bugs are at the page to send a newsletter
Top Breadcrumb broken: Newsletter › Newsletter - Alle › e (https://ibb.co/KWcHhbC)
Button to send Newsletter: "Newsletter senden" = "N" (https://ibb.co/fC365vN)

**How to reproduce**

**Comment by leofeyer** [comment]
I have just realized that this has already been fixed in  88cded4f5bf315340f9af5bda8001c1585f4aece; only the German translation is not up to date. Since this will resolve itself with the next version, I am closing this ticket.
