### ISSUE TITLE
Contao 5: PDF-ICON für content-download und content-downloads HTML.TWIG

### ISSUE THREAD

**Issue by TS16V** [contao/contao#6792]
### Affected version(s)

Contao 5.1.11

### Description

The Problem look here:

https://community.contao.org/de/showthread.php?86248-Contao-5-PDF-ICON-f%C3%BCr-content-download-und-content-downloads-HTML-TWIG&p=579942&viewfull=1#post579942

![Unbenannt-5](https://github.com/contao/contao/assets/38064792/4c7b7f79-d473-493b-873a-f1f7e359d377)

**Comment by fritzmg** [comment]
@TS16V please do not just link to a forum thread. You need to describe exactly what the issue is.

**Comment by TS16V** [comment]
In Contao 5 I have the following problem with the different display of the download PDF icons.
I have attached a picture:

![Unbenannt-5](https://github.com/contao/contao/assets/38064792/f8c34118-8e68-435d-baf8-adb3a6c225c6)


In **content-download** is not  ul li , why the icon slips.

In **content-downloads** the PDF icon sits perfectly.

How can the problem be solved so that the PDF icon is positioned just as well in the content download as in the content downloads?

**Comment by fritzmg** [comment]
> How can the problem be solved so that the PDF icon is positioned just as well in the content download as in the content downloads?

This is a pure CSS issue on your end.

However, I do agree that the new templates for the `download` and `downloads` element could be improved. With the legacy templates you were able to style download links from both the download and downloads content elements in a unified way, because they both use the `.download-element` class on an immediate parent to the `<a>`.

**Comment by fritzmg** [comment]
To clarify: the new `download` template also uses the `download-element` class - however it is applied directly to the main wrapper - and not to a paragraph surrounding only the download link (like it was the case previously).

**Comment by fritzmg** [comment]
I just noticed that nothing is really wrong here anyway. The `download` element already has the `download-element` class on its wrapper and thus you can style all download links, including the ones from news and event enclosures, via `.download-element > a` - and any preview with `.download-element > figure`. Which is more consistent than the situation in Contao 4.13.
