### ISSUE TITLE
The invalid form control with name=‘…’ is not focusable

### ISSUE THREAD

**Issue by kroerig** [contao/contao#6793]
### Affected version(s)

4.13, 5.x

### Description

Beim Absenden eines Fomulars ohne Daten erhält man in der Browserkonsole die o.g. Medlung für alle Elemente des Formulars im Firefox 121:
![grafik](https://github.com/contao/contao/assets/5148795/b95a1871-7666-4f5f-894a-09deeff47525)

**Comment by fritzmg** [comment]
I am able to reprodue the issue. However, I was unable to figure out why Firefox reports this. In theory this should only happen if you have either

```html
<input type="hidden" value="" required>
```

or

```html
<input type="text" ...><!-- hidden via CSS -->
```

But neither is the case 🤔 

// This also happens in the back end btw.

**Comment by kroerig** [comment]
> I was unable to figure out why Firefox reports this.

Chrome doesn't.

**Comment by ausi** [comment]
I was not able to reproduce this in Firefox 122

**Comment by fritzmg** [comment]
Hm, still reproducable for me in Firefox 122. My reproduction was:

* Edit a page in Contao 5.3.
* Remove the page title (or any other mandatory field).
* Save

**Comment by kroerig** [comment]
I can reproduce it with FF 122 and the login form on https://demo.contao.org/login.html

**Comment by ausi** [comment]
Can reproduce it now too. I looks like this was added with Firefox 121, see https://bugzilla.mozilla.org/show_bug.cgi?id=1648733

**Comment by fritzmg** [comment]
But it looks like this is a bug in Firefox itself then, is it not? This error should only happen on fields that are invalid and cannot be focused.

**Comment by ausi** [comment]
Yes, I think this needs to be reported to Mozilla.

**Comment by fritzmg** [comment]
Yes, it is easily reproducable with a very simple form: https://codepen.io/fritzmg/pen/abMVyPr

See https://bugzilla.mozilla.org/show_bug.cgi?id=1876792
