### ISSUE TITLE
Content routing not lenient enough

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6797]
### Affected version(s)

5.3

### Description

Up until Contao 5.3 having invalid redirect pages selected in a news article or in a news archive was not a problem, as Contao will just employ fallbacks.

For example:

1. If you have set the `source` of a news to `internal` and the target page does not exist anymore, the news URL generation would just fall back to the regular detail URL of the news.
2. If the redirect page in a news archive does not exist anymore, the news URL generation would just fall back to the URL of the current request.

This is not the case anymore with the new content routing. In the former case, the following error will occur when the URL of the respective news is generated:

```
Contao\CoreBundle\Exception\ForwardPageNotFoundException:

  at vendor\contao\core-bundle\src\Routing\Content\ContentUrlResult.php:76
  at Contao\CoreBundle\Routing\Content\ContentUrlResult::redirect(null)
     (vendor\contao\news-bundle\src\Routing\NewsResolver.php:43)
  at Contao\NewsBundle\Routing\NewsResolver->resolve(object(NewsModel))
     (vendor\contao\core-bundle\src\Routing\ContentUrlGenerator.php:149)
  at Contao\CoreBundle\Routing\ContentUrlGenerator->resolveContent(object(NewsModel))
     (vendor\contao\core-bundle\src\Routing\ContentUrlGenerator.php:69)
  at Contao\CoreBundle\Routing\ContentUrlGenerator->generate(object(NewsModel), array())
     (vendor\contao\news-bundle\contao\modules\ModuleNews.php:327)
  at Contao\ModuleNews->generateContentUrl(object(NewsModel), false)
     (vendor\contao\news-bundle\contao\modules\ModuleNews.php:305)
  at Contao\ModuleNews->generateLink('…', object(NewsModel), false)
     (vendor\contao\news-bundle\contao\modules\ModuleNews.php:87)
  at Contao\ModuleNews->parseArticle(object(NewsModel), false, ' featured', 3)
     (vendor\contao\news-bundle\contao\modules\ModuleNews.php:285)
  at Contao\ModuleNews->parseArticles(object(Collection))
     (vendor\contao\news-bundle\contao\modules\ModuleNewsList.php:157)
  at Contao\ModuleNewsList->compile()
     (vendor\contao\core-bundle\contao\modules\Module.php:213)
  at Contao\Module->generate()
     (vendor\contao\news-bundle\contao\modules\ModuleNewsList.php:73)
  at Contao\ModuleNewsList->generate()
```

This can be easily fixed via:

```diff
class NewsResolver implements ContentUrlResolverInterface
{
    public function __construct(private readonly ContaoFramework $framework)
    {
    }

    public function resolve(object $content): ContentUrlResult|null
    {
        if (!$content instanceof NewsModel) {
            return null;
        }

        switch ($content->source) {
            // Link to an external page
            case 'external':
                return ContentUrlResult::url($content->url);

            // Link to an internal page
            case 'internal':
                $pageAdapter = $this->framework->getAdapter(PageModel::class);

-               return ContentUrlResult::redirect($pageAdapter->findPublishedById($content->jumpTo));
+               if ($page = $pageAdapter->findPublishedById($content->jumpTo)) {
+                   return ContentUrlResult::redirect($page);
+               }
+
+               break;

            // Link to an article
            case 'article':
                $articleAdapter = $this->framework->getAdapter(ArticleModel::class);

-               return ContentUrlResult::redirect($articleAdapter->findPublishedById($content->articleId));
+               if ($article = $articleAdapter->findPublishedById($content->articleId)) {
+                   return ContentUrlResult::redirect($article);
+               }
+
+               break;
        }

        $pageAdapter = $this->framework->getAdapter(PageModel::class);

        // Link to the default page
        return ContentUrlResult::resolve($pageAdapter->findPublishedById((int) $content->getRelated('pid')?->jumpTo));
    }

    public function getParametersForContent(object $content, PageModel $pageModel): array
    {
        if (!$content instanceof NewsModel) {
            return [];
        }

        return ['parameters' => '/'.($content->alias ?: $content->id)];
    }
}
```

In the latter case, the following error will occur:

```
Contao\CoreBundle\Exception\ForwardPageNotFoundException:

  at vendor\contao\core-bundle\src\Routing\Content\ContentUrlResult.php:94
  at Contao\CoreBundle\Routing\Content\ContentUrlResult::resolve(null)
     (vendor\contao\news-bundle\src\Routing\NewsResolver.php:64)
  at Contao\NewsBundle\Routing\NewsResolver->resolve(object(NewsModel))
     (vendor\contao\core-bundle\src\Routing\ContentUrlGenerator.php:149)
  at Contao\CoreBundle\Routing\ContentUrlGenerator->resolveContent(object(NewsModel))
     (vendor\contao\core-bundle\src\Routing\ContentUrlGenerator.php:69)
  at Contao\CoreBundle\Routing\ContentUrlGenerator->generate(object(NewsModel), array())
     (vendor\contao\news-bundle\contao\modules\ModuleNews.php:327)
  at Contao\ModuleNews->generateContentUrl(object(NewsModel), false)
     (vendor\contao\news-bundle\contao\modules\ModuleNews.php:305)
  at Contao\ModuleNews->generateLink('…', object(NewsModel), false)
     (vendor\contao\news-bundle\contao\modules\ModuleNews.php:87)
  at Contao\ModuleNews->parseArticle(object(NewsModel), false, ' featured', 3)
     (vendor\contao\news-bundle\contao\modules\ModuleNews.php:285)
  at Contao\ModuleNews->parseArticles(object(Collection))
     (vendor\contao\news-bundle\contao\modules\ModuleNewsList.php:157)
  at Contao\ModuleNewsList->compile()
     (vendor\contao\core-bundle\contao\modules\Module.php:213)
  at Contao\Module->generate()
     (vendor\contao\news-bundle\contao\modules\ModuleNewsList.php:73)
  at Contao\ModuleNewsList->generate()
```

This could be fixed by injecting the request stack into the resolver and then falling back to the current request's URL if the `jumpTo` page of the news archive is not found. Or we catch the exception in `ModuleNews::generateContentUrl` and return `Environment::get('url')` then.

The same issues likely also apply to calendars etc.

**Comment by leofeyer** [comment]
But isn‘t it good if people realize that something is not configured correctly?

**Comment by fritzmg** [comment]
I don't think it's good that when you update from Contao 4 to 5 or from Contao <5.3 to >=5.3 that your website suddenly ends up with a server error. And even if we consider this to be ok, the error message will not tell you at all what the problem is - or what you would need to adjust.

In general we do not want behavior changes in bugfix and minor version updates, do we?

**Comment by Toflar** [comment]
I don't think changing this in the resolvers themselves is a good idea. You want to know that it failed. But the exception should probably be caught in the **old** places where this was the previous behavior.

**Comment by fritzmg** [comment]
> I don't think changing this in the resolvers themselves is a good idea. You want to know that it failed. But the exception should probably be caught in the **old** places where this was the previous behavior.

But then we cannot restore the previous behavior where there are two fallback levels:

1. If `tl_news.jumpTo` does not exist anymore, URL generation falls back to its regular detail URL using `tl_news_archive.jumpTo`.
2. If `tl_news_archive.jumpTo` does not exist anymore, URL generation falls back to the current request URL.

**Comment by Toflar** [comment]
> If `tl_news_archive.jumpTo` does not exist anymore, URL generation falls back to the current request URL.

This would never make any sense? That would mean the SerpPreview would show `foobar.com/contao?.....` as a preview URL for a news entry? 😄

**Comment by fritzmg** [comment]
Regardless, that is the current (<5.3) behavior of `News::generateNewsUrl`. Also, what other URL would you then generate when you catch the exception in the place where you call `$contentUrlGenerator->generate()`? Or do you mean the news entry should then not be generated at all? (e.g. the exception needs to be caught in `ModuleNewsList` instead for example.)

**Comment by aschempp** [comment]
I agree with @fritzmg that the page should not fail. But we need to dicuss what should be the default.
Rendering the original reader URL makes no sense, because that would just generate an error itself (see https://github.com/contao/contao/blob/5.2/news-bundle/contao/modules/ModuleNewsReader.php#L96).

I think the _correct_ way would be to render an empty URL. And adjust the templates to not generate a link if the href is empty?

**Comment by fritzmg** [comment]
> I think the _correct_ way would be to render an empty URL. And adjust the templates to not generate a link if the href is empty?

Sounds good to me. And I agree that the previous fallbacks did not really make all that much sense anyway. The important thing ist just to not make the website fail after updating to 5.3. 

So just return `null` in the resolver then?

**Comment by fritzmg** [comment]
There is also another error reproduceable in the back end:

1. Create a new news.
2. Switch the source to _Page_.
3. Switch the source back to _Default_.

The following error will occur:

```
LogicException:
Unable to generate a content URL for the SERP widget, please provide the url_callback.

  at vendor\contao\contao\core-bundle\contao\widgets\SerpPreview.php:171
  at Contao\SerpPreview->getUrl()
     (vendor\contao\contao\core-bundle\contao\widgets\SerpPreview.php:53)
  at Contao\SerpPreview->generate()
     (vendor\contao\contao\core-bundle\contao\library\Contao\Widget.php:647)
  at Contao\Widget->generateWithError()
     (vendor\contao\contao\core-bundle\contao\templates\backend\be_widget.html5:3)
  at include('vendor\\contao\\contao\\core-bundle\\contao\\templates\\backend\\be_widget.html5')
     (vendor\contao\contao\core-bundle\contao\library\Contao\TemplateInheritance.php:109)
  at Contao\Widget->inherit()
     (vendor\contao\contao\core-bundle\contao\library\Contao\Widget.php:595)
  at Contao\Widget->parse()
     (vendor\contao\contao\core-bundle\contao\classes\DataContainer.php:777)
  at Contao\DataContainer->row()
     (vendor\contao\contao\core-bundle\contao\drivers\DC_Table.php:2199)
```

**Comment by aschempp** [comment]
I think there issues have been solved, can we close this @fritzmg ?

**Comment by fritzmg** [comment]
Yes, https://github.com/contao/contao/pull/6854 and https://github.com/contao/contao/pull/6861 should be enough 👍
