### ISSUE TITLE
contao/contao should replace contao/core

### ISSUE THREAD

**Issue by aschempp** [contao/contao#68]
I think this is wrong: https://github.com/contao/core-bundle/blob/develop/composer.json#L34

The replacement of `contao/core` is `contao/contao` (the meta package).

**Comment by leofeyer** [comment]
Changed in contao/core@1e734373a18226dc930cb4df3025fb88aea157dc and contao/core-bundle@f7061486148e0c9b1ba9db72988912986133ee1e.
