### ISSUE TITLE
The registry already contains an instance for tl_page::id()

### ISSUE THREAD

**Issue by timgatzky** [contao/contao#68]
**Affected version(s)**
4.4.25

**Description**  
The registry already contains an instance for tl_page::id()

public function scheduleUpdate() Methode creates a new Instance of PageModel 

**How to reproduce**  
Hi Leute,
beim Speichern eines Seiten-Datensatzes kommt es unter 4.4.25 zu besagten Fehler in unseren Systemen. Auslöser ist die neue scheduleUpdate() Methode. Es wird eine $objPage Instanz von Null erstellt, was ggf. in der Registry nicht gegengeprüft wird, ob für die Seiten-ID bereits eine Instanz existiert. 

Abhilfe würde hier die Erstellung direkt über PageModel::findByPk bringen, da auch vorab auf die Existenz einer ID geprüft wurde.

/dca/tl_page, 1048
$objPage = \PageModel::findByPk($dc->activeRecord->id);
#$objPage = new PageModel($dc->activeRecord); // 4.4.25
$objPage->loadDetails();

**Comment by netzarbeiter** [comment]
Duplicate of https://github.com/contao/contao/issues/63
