### ISSUE TITLE
C 4.8.1 {{image::*}} im Newsletter Template erzeugt keine Bilder mehr

### ISSUE THREAD

**Issue by Kahmoon** [contao/contao#680]
**Affected version(s)**
Contao 4.8.1

**Description**  
Ich verwende im Newsletter Template ein Logo via replaceInsertTags

`<?= $this->replaceInsertTags( '{{image::fa971c31-7300-11e8-8b83-74d02bcb043d?width=450&height=150&mode=crop}}' ); ?>`

Bisher hat das auch super funktioniert. Seit Contao 4.8.1 ist das Bild im Newsletter nicht mehr vorhanden.

**How to reproduce / Workaround**  
Erzeuge ich via Inhaltselement "Text" und dem Inserttag selbst {{image::fa971c31-7300-11e8-8b83-74d02bcb043d?width=450&height=150&mode=crop}} das Bild und rufe es im Frontend einmalig auf, funktioniert auch die Grafik im Newsletter.

Ändere ich die Größeneinstellung im Template ist die Grafik wieder nicht verfügbar. Erst wenn ich die Grafik mit den neuen Einstellungen wieder einmalig im Frontend via Inserttag aufrufe, funktioniert sie auch wieder im Newsletter.

Ich gehe also davon aus das {{image::*}}  im Template keine Bildversionen mehr erzeugt. Vermutlicher Zusammenhand mit Deferred Image Creation.

VG Frank

**Comment by fritzmg** [comment]
> Ich gehe also davon aus das replaceInsertTags im Template keine Bildversionen mehr erzeugt. Vermutlicher Zusammenhand mit Deferred Image Creation.

`replaceInsertTags` hat damit nichts zu tun. Generell werden keine Bilder mehr erzeugt - sondern erst, wenn auf das Bild zugegriffen wird. Das ist aber in diesem Fall ein Problem - weil das Bild, wahrscheinlich? - ansonsten von Contao direkt integriert worden wäre - anstatt extern verlinkt.

**Comment by Kahmoon** [comment]
Da es ein fixes Element in jedem Newsletter ist (was sicher bei vielen der Fall ist), habe ich das Logo im Template platziert um es nicht immer wieder manuell via Newsletter einzufügen. Das macht es dem Kunden auch leichter und reduziert Fehlerquellen :D

**Comment by ausi** [comment]
Ich denke die E-Mail-Klasse muss ensprechend angepasst werden damit das Bild erzeugt wird bevor es im E-Mail inkludiert wird: https://github.com/contao/contao/blob/94773be168891ca1a9ef8ad7e81c2d515e32558a/core-bundle/src/Resources/contao/library/Contao/Email.php#L414

**Comment by leofeyer** [comment]
Wieso verwendest Du denn `<?= $this->replaceInsertTag('{{image}}') ?>` in einem PHP-Template? Dort kannst Du doch direkt mit der Image-Factory arbeiten.

**Comment by Kahmoon** [comment]
Was ist die Image-Factory? Ich hatte das dort schon seit 4.6 via mail_default.html5 so gemacht. Einen anderen Weg kenne ich leider nicht.

Wenn es hierfür einen besseren Weg gibt...gerne!

**Comment by fritzmg** [comment]
> Wieso verwendest Du denn `<?= $this->replaceInsertTag('{{image}}') ?>` in einem PHP-Template? Dort kannst Du doch direkt mit der Image-Factory arbeiten.

Würde das Problem aber auch nicht beheben.

**Comment by leofeyer** [comment]
Siehe #693.
