### ISSUE TITLE
`web_dir` config not removed

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6800]
### Affected version(s)

5.2, 5.3, 5.x

### Description

While inspecting `config:dump-reference contao` (for the docs) I noticed that we deprecated the `web_dir` setting in Contao 4.13 - but never removed it in Contao 5:

https://github.com/contao/contao/blob/2fcaedc5924d8c279327faf3ed87ffb485adfbd3/core-bundle/src/DependencyInjection/Configuration.php#L101-L109

Furthermore, the description says

> Defaults to %kernel.project_dir%/public.

However, it actually only defaults to `'public'` in Contao 5 (relative, without the project directory). It is correctly defaulting to `'%kernel.project_dir%/public'` in Contao 4.13:

https://github.com/contao/contao/blob/09a214bf84ee787c37dfb46cf939317aa575b895/core-bundle/src/DependencyInjection/Configuration.php#L123

https://github.com/contao/contao/blob/09a214bf84ee787c37dfb46cf939317aa575b895/core-bundle/src/DependencyInjection/Configuration.php#L714-L723

Is there a specific reason that we kept the config? If yes, should we fix its default value?

**Comment by aschempp** [comment]
aren't we using this to store the path configured in the `composer.json`?

**Comment by fritzmg** [comment]
> aren't we using this to store the path configured in the `composer.json`?

I assume you mean the `contao.web_dir` _parameter_, which is not set according to the bundle _config_ anymore in Contao 5 (only according to the `composer.json` config):

https://github.com/contao/contao/blob/2fcaedc5924d8c279327faf3ed87ffb485adfbd3/core-bundle/src/DependencyInjection/ContaoCoreExtension.php#L109

**Comment by leofeyer** [comment]
This is definitely a useless left-over that needs to be removed (see #6845).
