### ISSUE TITLE
The cache for contao.twig.loader_paths contains duplicate paths

### ISSUE THREAD

**Issue by kp-mtrame** [contao/contao#6802]
### Affected version(s)

4.13, 5.2, 5.3

### Description

When the cache folder (/var/cache/) is empty and ./vendor/bin/contao-setup is invoked, the paths for contao.twig.loader_paths are duplicated. This is because during the execution of the 'cache:warmup' command, 'warmup' is already performed in ContaoKernel::initializeContainer(), and then during the command's execution, Contao\CoreBundle\Twig\Loader\ContaoFilesystemLoaderWarmer is executed again.

**Comment by fritzmg** [comment]
I can confirm the issue in Contao 4.13 as well es Contao 5.

**Comment by leofeyer** [comment]
@kp-mtrame Do you use Windows or Unix?

**Comment by kp-mtrame** [comment]
Contao runs in a Docker container on Linux.

**Comment by leofeyer** [comment]
@kp-mtrame Can you please check if #6847 fixes your problem?
