### ISSUE TITLE
System / website administrator e-mail address overwrites from-field

### ISSUE THREAD

**Issue by AlexanderPilhar** [contao/contao#681]
**Affected version(s)**
4.4.41 (and likely others as well)

**Description**
In `Settings > Global configuration > E-mail address of the system administrator` and `Site structure > Website root > Global settings > E-mail address of the website administrator` help-text says "Auto-generated messages like subscription confirmation e-mails will be sent to this address." - which might be misleading because e-mails are not only being sent to this address but also are sent FROM this address.
This turns out to be a problem when using an Office 365 account (`parameters.yml`) since they don't allow to overwrite `from` field (`from` address must be the same as in `mailer_user` in `parameters.yml` which is used to login to Office 365).
If one accidently overwrites `from` field in mail address for either system administrator or website administrator the result when sending an e-mail will be: `... could not be sent: Expected response code 250 but got code "554", with message "554 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. ...`.

**How to reproduce**  
- Use Office 365 account for mailer settings in parameters.yml.
- Use any different mail address for system administrator and/or website administrator.
- Try to send an e-mail.

**Suggestion**
Either make clear that the e-mail address for system / website administrator will be used for `from` field when sending e-mails or introduce a separate from-email address setting in global settings.

**Comment by fritzmg** [comment]
Imho this is part of a more general problem. See also https://github.com/contao/core-bundle/issues/1613

I would propose, that email settings (SMTP & from address, etc.) can be overridden in the website root.

* This would solve https://github.com/contao/core-bundle/issues/1613.
* Regarding the `from` address you would have the following fallback stages:
  1. Use the `from` address defined in the email settings of the website root.
  2. If no from address was defined in the website root, use the administrator email address of the website root.
  3. If no administrator email address is defined in the website root, use the administrator email address of the system settings/config.

**Comment by fritzmg** [comment]
And a more general question: should it be possible to have _no_ from address? Can emails without a `From` in its header be sent via SMTP? Would SMTP Servers add the `From` address - depending on the authenticated account, if applicable?

**Comment by AlexanderPilhar** [comment]
`Newsletters > Sender settings > Sender e-mail address` is likely to be affected as well.

> And a more general question: should it be possible to have no from address? Can emails without a From in its header be sent via SMTP? Would SMTP Servers add the From address - depending on the authenticated account, if applicable?

I'm no expert in mail protocols - so, I'm sorry but I can't answer these questions. But [Wikipedia - Simple Mail Transfer Protocol, SMTP transport example](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol#SMTP_transport_example) looks quite useful.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 29th, we want to have a fixed "from" address that is configured in the `parameters.yml` or `services.yml` (where you also configure the SMTP login credentials). This works in the new Symfony Mailer, which we could use in Contao 4.9. We have to check if SwiftMailer supports this as well.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 29th, we want to implement https://github.com/contao/core-bundle/issues/1613#issuecomment-417350012 with a fixed "from" address (currently only supported in the new Symfony Mailer and not in SwiftMailer) and add it as drop-down menu in the global settings, in the website root pages and the newsletter module.

**Comment by m-vo** [comment]
btw.: support for multiple mailers is also on the way in Symfony Mailer https://github.com/symfony/symfony/pull/33409

**Comment by leofeyer** [comment]
See https://github.com/contao/contao/pull/1469.
