### ISSUE TITLE
"tl_user::addTemplateWarning" does not respect the group rights

### ISSUE THREAD

**Issue by BugBuster1701** [contao/contao#6810]
### Affected version(s)

4.13, 5.x

### Description

The "addTemplateWarning" method only reads the tl_user table.
This causes several errors.

- If a user has their own rights, e.g. theme import, and the group rights do not, **and** "Permission inheritance" is set to "**Use group settings only**", the warning is still displayed in "Account - Users": "`There is at least one regular user with permission to import themes......"
`
- If a user has theme import rights in the group, but not for themselves, a warning is never displayed under "Account - Users". (But it does for "Accounts - User Groups")

The same naturally also applies to "TemplateWarning" and "UnfilteredHtmlWarning".

**Comment by aschempp** [comment]
would you be able to do a pull request to fix the problem?
