### ISSUE TITLE
Symfony forms and request tokens

### ISSUE THREAD

**Issue by veronikaplenta** [contao/contao#6817]
### Affected version(s)

5.3.x-dev

### Description

When trying to use a Symfony form in a fragment controller, upon sending the form the request token is invalid. (CSRF token is set correctly)

When I include multiple forms on the same page, they have different request tokens (Contao form, Symfony form, doesn't matter.)

**Comment by fritzmg** [comment]
The request tokens are also different in the back end - each DCA action has a different RT, which should not be the case.

**Comment by ausi** [comment]
> The request tokens are also different in the back end - each DCA action has a different RT, which should not be the case.

They are all the same but their representation is different as they get randomized since https://github.com/symfony/symfony/pull/39919, see https://github.com/symfony/symfony/blob/add24fa38e0438f1188211cce7adf418f41b04a0/src/Symfony/Component/Security/Csrf/CsrfTokenManager.php#L110-L131 We added support for these randomized values in https://github.com/contao/contao/pull/4045

For information about how to use the CSRF token with Symfony forms see https://github.com/contao/contao/pull/3214

**Comment by fritzmg** [comment]
According to the Slack discussion, @veronikaplenta already uses the methods provided in #3214.

**Comment by veronikaplenta** [comment]
Did anyone look into this yet? As @fritzmg mentioned, I use the methods from #3214. The same setup works in Contao 4.13.
If it helps, I could set up a small repo with an example.

**Comment by fritzmg** [comment]
An easy reproduction would certainly help 🙂

**Comment by veronikaplenta** [comment]
Well, turns out I couldn't reproduce it. :D In my example it all worked fine. I did a bit more testing and removing the CSRF options from the form (it's a GET form, but I'm sending a POST AJAX request from within the form to populate form fields) works. I'm a bit confused, because in the example it worked with GET and CSRF options. But I got it working now in the project.

**Comment by Toflar** [comment]
Sounds like you might have been affected by https://github.com/contao/contao/pull/6801 😉

**Comment by veronikaplenta** [comment]
That does sound likely.
Although the problem persisted after a composer update. 🤔

**Comment by fritzmg** [comment]
> Although the problem persisted after a composer update. 🤔

The fix has been released yesterday, may be you tried before that?

**Comment by veronikaplenta** [comment]
No, I ran composer update less than an hour ago

**Comment by Toflar** [comment]
Anyway, closing because apparently there's no reproducer at the moment. Feel free to reopen if there is one :)
