### ISSUE TITLE
Add an event before twig template is rendered to modify existing templates in bundle

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#6823]
### Description

for Contao 5.3

see also discussion on Slack: https://contao.slack.com/archives/CK4J0KNDB/p1706647880230049

Hello everyone,

**using the new Twig-Templates, the hooks “onParseTemplate” and “outputFrontendTemplate” no longer work.**
So there is no longer any option to modify twig templates for e.g. Page, Article, etc. in bundles like before.
So how is it planned to modify e.g. fe_page.html.twig in a separate bundle in the future?

Using the hooks "getContentElement" and "getFrontendModule" you can at least adjust the content elements and frontend modules in Twig, but with article, news, page templates, etc.there is no there is no solution yet.
(Furthermore, you only have the finished HTML buffer and you can only make adjustments to the HTML code with regexp and a lot of effort)

**So the following idea:**
Add en event that is dispatched before the Twig template is rendered with maybe the following information as an ObjectReference:
- FragmentTemplate
- Model
- Twig HTML Buffer
- attributes/parameters
...

This would give you the opportunity to programmatically modify the template in bundles.

Twig is well integrated into Contao and you can actually overwrite everything cleanly with set .., attr(...), etc. using the backend, but not programatically in your own bundle.

Basically, I understand the approach that you shouldn't actually do something like that, but somehow it should be possible to modify a template using a own bundle.

**A classic example is the cookiebar extention.**
(https://extensions.contao.org/?q=cookie&pages=1&p=oveleon%2Fcontao-cookiebar)
Here you cannot overwrite the templates in the bundle file based because all templates from various extensions have to be considered. That's why you would subscribe via event to the render process of the Template and then check whether DSGVO-relevant attributes are used in the template (maybe as variables or using regexp in the HTML).

There was also a discussion in Slack about whether you really need the HTML or whether you should use a ResponseListener.
I think that it is necessary because, on the one hand, you need the assignment of HTML to FragmentTemplate in order to react appropriately and, on the other hand, it is otherwise difficult to make template adjustments (adding new parameters and using them in the template).
​
What do you think about that? More opinions would be great!

Thanks

**Comment by m-vo** [comment]
See https://github.com/contao/contao/pull/3913 for some previous discussion/code.

**Comment by xprojects-de** [comment]
> See #3913 for some previous discussion/code.

Nice. That´s it!

**Comment by aschempp** [comment]
closing in favor of https://github.com/contao/contao/pull/3913 then
