### ISSUE TITLE
Submitting nested content element runs into recursion

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#6824]
### Affected version(s)

5.3-dev

### Description

I played around the new nested content element feature in Contao and immediately run into an recursion issue.  After debugging this the issues is in `Contao\Controller::getParentEntries()` called by `Contao\Versions::create()`.

https://github.com/contao/contao/blob/2cf7bbc56bc236e5d2c66e660488e711d3368845/core-bundle/contao/library/Contao/Controller.php#L1285-L1321

```php
$arrParent = [
"tl_content.id=1214"
"tl_content.id=125"
"tl_content.id=40"
"tl_content.id=24"
"tl_content.id=1"
"tl_content.id=19"
"tl_content.id=1"
];
```

Looking at the collected parents it starts to loop between the entry ID 1 and entry ID 19. This is caused by ignoring the dynamice `ptable` of the content element. The `ptable` information is only fetched from the configuration https://github.com/contao/contao/blob/2cf7bbc56bc236e5d2c66e660488e711d3368845/core-bundle/contao/library/Contao/Controller.php#L1299 

That's not correct. The ptable entry might be different in each entry fetched from the database. In my example above `tl_content.id=125` already has a `ptable=tl_article` .

**Comment by ausi** [comment]
I think we need to add a check for `dynamicPtable` there and use `$objParent->ptable` then.

**Comment by leofeyer** [comment]
I think we only have to revert the changes now that we use `ctable` instead of `ptable`.

@dmolineus Can you please check if #6833 fixes your issue?

**Comment by dmolineus** [comment]
> I think we only have to revert the changes now that we use `ctable` instead of `ptable`.
> 
> @dmolineus Can you please check if #6833 fixes your issue?

Unfortunately it doesn't. The recursion still remains:

```
0 = "tl_content.id=1214"
1 = "tl_content.id=125"
2 = "tl_content.id=40"
3 = "tl_content.id=24"
4 = "tl_content.id=1"
5 = "tl_content.id=19"
6 = "tl_content.id=1"
```

I think ausi is right, the dynamicPtable requires a different approach. Imho the method was broken before introducing custom elements as pointed out here https://github.com/contao/contao/pull/6833#issuecomment-1923264792
