### ISSUE TITLE
Theme Import help text is outdated, should include zip files

### ISSUE THREAD

**Issue by denniserdmann** [contao/contao#6850]
### Affected version(s)

5.3

### Description

As of Contao 5.3 (or even before, i'm not sure) you can upload theme files with zip extension as well. But the current help text confuses the user, as there is only .cto and .sql mentioned. 

see https://github.com/contao/contao/blob/5.3/core-bundle/contao/languages/de/tl_theme.xlf#L48-L51

**Comment by leofeyer** [comment]
Fixed in b6a46ed04fc1166ffbd367d63c77d8752d7976cb.
