### ISSUE TITLE
Assets-URL on root  page not working anymore

### ISSUE THREAD

**Issue by moonfr34k** [contao/contao#6853]
### Affected version(s)

5.2.7

### Description

If you give a start page an asset URL, all links in the frontend are still generated without the asset URL.

![image](https://github.com/contao/contao/assets/4944500/7e9f90d5-f729-4da5-8239-09dfd88e3ca2)

![image](https://github.com/contao/contao/assets/4944500/b3d9346b-0e02-4b1e-b759-5c3cd9f6b2f0)

**Comment by fritzmg** [comment]
@moonfreak may be the debug mode was enabled in your case? Because this is not added when the debug mode is enabled.

**Comment by moonfr34k** [comment]
I tried both, prod and dev mode, cache has been cleared.

**Comment by fritzmg** [comment]
I cannot reproduce this issue in `prod`. Are you sure you populated _both_ the **Assets URL** and **Files URL**? For thumbnails the _latter_ is used. The former is used for JS and CSS.

**Comment by moonfr34k** [comment]
I am not using the file host, i only need the asset host.

**Comment by fritzmg** [comment]
As already mentioned you need to use the **Files URL** for the thumbnails.
