### ISSUE TITLE
Drop support of empty ptable for content element.

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#686]
Contao 3 introduced the dymanic parent table feature for content elements. For backwards compatibility an empty ptable column of tl_content is threated as `tl_article`, so additional conditions to check this were included in the core.

I think Contao 4 would be a good point to drop this backward compatibility. 3rd party extensions would have to set the ptable always.

An migration script (from Cto 3 to 4) could change any empty ptable value of `tl_content` to `tl_article`.

**Comment by leofeyer** [comment]
Changed in #4653.
