### ISSUE TITLE
File names in DB are not updated correctly when they are renamed on the server

### ISSUE THREAD

**Issue by LIVID-Media** [contao/contao#6862]
### Affected version(s)

5.2.8

### Description

I have a strange behaviour when renaming files directly on the server.

1. I copy a file via FTP to the server into a subfolder of "/files" - e.g. image.jpg
2. I perform a synchronisation in the backend under "Files"
3. Now I change the file name via FTP (e.g. to image1.jpg) and synchronise the files again - the change is recognised
4. The new file name (image1.jpg) is displayed in the backend, but the old file name (image.jpg) is still displayed in the "name" column in the DB

And it's also not possible to search for the new file name in the backend.

**Comment by cliffparnitzky** [comment]
I think this is not possible and was not intended to be.

**Comment by fritzmg** [comment]
You should always avoid making changes outside the file manager.

**Comment by m-vo** [comment]
IMHO the file name should also get updated in the DBAFS sync. Looks like a bug to me.

**Comment by LIVID-Media** [comment]
> You should always avoid making changes outside the file manager.

You are right, but I think it happens from time to time that files are changed directly via FTP. If the file name is also updated during sync, the problem is solved.

**Comment by cliffparnitzky** [comment]
How should this technically be solved? How should the DBAFS sync, that the file is renamed and not a new one? 

Therefor:
> You should always avoid making changes outside the file manager.

**Comment by fritzmg** [comment]
> How should this technically be solved? How should the DBAFS sync, that the file is renamed and not a new one?

@cliffparnitzky The issue is that the _name_ in the `tl_files` record was not updated, even though the _path_ was (at least according to the issue description).

> How should the DBAFS sync, that the file is renamed and not a new one?

The DBAFS sync always was able to do this since the inception of the DBAFS in Contao 3.2 (by comparing file hashes).

**Comment by m-vo** [comment]
We probably need to adjust the name and file extension after these lines ...
https://github.com/contao/contao/blob/8ccecc3701e508e616e556c544d61ebb7a159cf4/core-bundle/src/Filesystem/Dbafs/Dbafs.php#L608-L611

... like we did for the inserts:
https://github.com/contao/contao/blob/8ccecc3701e508e616e556c544d61ebb7a159cf4/core-bundle/src/Filesystem/Dbafs/Dbafs.php#L570-L575

**Comment by leofeyer** [comment]
As discussed in the call, we have to add

```php
// Backwards compatibility
if ('tl_files' === $this->table) {
    $dataToUpdate['name'] = basename($itemToUpdate->getPath());
    $dataToUpdate['extension'] = $itemToUpdate->isFile() ? Path::getExtension($itemToUpdate->getPath()) : '';
}
```

after line 610.

**Comment by leofeyer** [comment]
See #6872 for the fix.

However, I had to omit `$dataToUpdate['extension']` because there is no `$itemToUpdate->isFile()` method. Such a method only exists in the `ItemToCreate` class but not in the `ItemToUpdate` class, most likely because we do not support changing the file type from `file` to `folder` or from `.jpg` to `.png`.
