### ISSUE TITLE
"Two pages with the same alias" with news module - inserttag problem

### ISSUE THREAD

**Issue by Physiklehrer** [contao/contao#6863]
### Affected version(s)

4.13, 5.x

### Description

Online-Demo:
- Rename site alias "news-detail" to "news" and set "element necessary" to active
- Rename site alias "events-detail" to "events" and set "element necessary" to active
- Create somewhere else inserttags "{{link::news}}" und "{{link::events}}

You will see: the events module works as expected. The inserttag shows the main events page und if you click at one of the events you get the specific event.

But the news-Inserttag ist NOT working. It shows not the main news page and if you go there manually the detail sites of the events are NOT available (an error occured).

Thanks a lot!

**Comment by fritzmg** [comment]
That is to be expected. If the same alias exists multiple times in `tl_page` it is undefined for which page the `{{link::*}}` insert tag will generate the URL. You cannot use this insert tag this way.

**Comment by Physiklehrer** [comment]
Thanks for your response. Beside the inserttag issue: alias "news" for the news list page ("element necessaray" NOT active) and the same alias "news" ("element necessary" active) for the news reader detail page is not allowed any more? Some versions ago this new feature was introduced.

**Comment by fritzmg** [comment]
No, that works as expected. But your issue concerns the `{{link::*}}` insert tag.

**Comment by Physiklehrer** [comment]
https://contao.org/de/news/contao_4-13-0 > "Zwei Seiten mit demselben Alias". This is not working any more for the news module.

**Comment by fritzmg** [comment]
> This is not working any more for the news module.

Why, what is the issue? If there is an issue with that, you should create a separate ticket for that and explain in more detail, what you did. Your current report is for the `{{link::*}}` insert tag, which has nothing to do with that?

**Comment by Physiklehrer** [comment]
I solved the inserttag issue by using the id instead of the alias so there is no routing problem with duplicate alias. Thank you and feel free to close this ticket.
