### ISSUE TITLE
Do not extend from the original Twig filesystem loader

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6871]
### Description

Side note: Our loader extends from the original Twig filesystem loader but it really should not. In the beginning I thought this was a good idea but with the added features, the two are very different now. So, in a future PR I would like to change this and subsequently remove some methods like `prependPath()` that do not make sense in our context and that I also did not touch in this PR. We probably need to discuss if we can/should do this break ("@experimental") or not.

_Originally posted by @m-vo in #6868_

**Comment by m-vo** [comment]
This got handled in #6936.
