### ISSUE TITLE
Missing indexer stop and continue in content elements

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#6874]
### Affected version(s)

5.3.0-RC3

### Description

Just as a example: 

The content element "Top link" comes now without the indexer stop and continue.

```
<div class="content-toplink">
<a href="#top" data-toplink="" title="test">test</a>
</div>
```

In 4.13 it looked like this:

```
<!-- indexer::stop -->
<div class="ce_toplink block">
<a href="#top" title="test">test</a>
</div>
<!-- indexer::continue -->
```

**Comment by fritzmg** [comment]
Also applies to `gallery`, `vimeo`, `player` and `youtube`, which previously extended from `block_unsearchable`.

**Comment by fritzmg** [comment]
Actually I could not reproduce this for the "Top link" content element:

```html
<!-- indexer::stop -->
<div class="content-toplink">
  <a href="#top" data-toplink title="Top">Top</a>
</div>
<!-- indexer::continue -->
```

Our `ToplinkController` already defines `searchable = false`:

https://github.com/contao/contao/blob/3145d8b798c5191709cec250015b2ef9b1aa23e6/core-bundle/src/Controller/ContentElement/ToplinkController.php#L27

Which is then taken into account in the `_base` template:

https://github.com/contao/contao/blob/3145d8b798c5191709cec250015b2ef9b1aa23e6/core-bundle/contao/templates/twig/content_element/_base.html.twig#L3-L5

But it's missing from other content elements.
