### ISSUE TITLE
Add validateFormField hook to ModuleRegistration

### ISSUE THREAD

**Issue by creo-code** [contao/contao#6875]
### Description
The ModuleRegistration class in Contao doesn't have a validateFormField method, which is useful in the Form class for checking data before it's submitted. You can see how it's used in the Form class here:
https://github.com/contao/contao/blob/5.x/core-bundle/contao/forms/Form.php#L258-L265

But it's missing in ModuleRegistration over here: 
https://github.com/contao/contao/blob/5.x/core-bundle/contao/modules/ModuleRegistration.php#L213

Having this method would let us do things like:
- Block submissions with "bad keywords"
- Make sure certain fields are filled out correctly
- Set up own honeypots

Right now, this hook is in the Form class but not in others like ModuleChangePassword, ModulePersonalData, Comments....

**Comment by fritzmg** [comment]
It's not missing - the form hooks are _only_ for the Contao Form Generator.

The form for the registration form is built from the DCA definition of `tl_member`.

You can achieve what you need by using regular DCA callbacks. e.g. if you want to block "bad keywords" for a specific field, you can implement a `save_callback`: https://docs.contao.org/dev/reference/dca/callbacks/#fields-field-save
