### ISSUE TITLE
To Remove InterestCohortListener

### ISSUE THREAD

**Issue by eznix86** [contao/contao#6876]
### Affected version(s)

5.x

### Description

Permissions-Policy header should be removed since Google has retired FLoC

**Comment by eznix86** [comment]
Or replace it with `Permissions-Policy: browsing-topics=()`

**Comment by zoglo** [comment]
2021:
https://blog.doenselmann.com/google-floc-auf-eigener-webseite-unterbinden/

Today:
https://en.wikipedia.org/wiki/Federated_Learning_of_Cohorts#:~:text=On%20January%2025%2C%202022%2C%20Google%20officially%20announced%20it%20had%20ended%20development%20of%20FLoC%20technologies%20and%20proposed%20the%20new%20Topics%20API%20to%20replace%20it.%5B10%5D%5B11%5D%20Brave%20developers%20criticized%20Topics%20API%20as%20a%20rebranding%20of%20FLoC%20with%20only%20minor%20changes%20and%20without%20addressing%20their%20main%20concerns.

Status: Replaced by Browsing Topics API

https://www.theverge.com/2022/1/25/22900567/google-floc-abandon-topics-api-cookies-tracking

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to remove the `interest-cohort` header. Depending on what everybody else does (see e.g. https://github.com/nelmio/NelmioSecurityBundle/issues/240), we might replace it with `browsing-topics`, but we will decide that at a later stage.
