### ISSUE TITLE
Make nested content elements recognizable

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#6878]
### Affected version(s)

5.3.0-RC3

### Description

First of all, I love the new nested content elements. Thank you very much.

It is currently not possible to recognize a nested content element in the select menu or in the help wizard.

![image1](https://github.com/contao/contao/assets/1942550/252297d9-e968-4099-8c64-2b7e04a53181)
![image2](https://github.com/contao/contao/assets/1942550/1373043e-3f72-4d72-ad32-783b9409ffcc)

**Comment by Toflar** [comment]
I agree that this might be helpful for users. I would also simplify the docs and explaining things to customers imho 👍

**Comment by leofeyer** [comment]
I disagree. It's an implementation detail, and for someone who wants to use an accordion, it makes no difference whether it's a nested element or not. This would only make sense if there were nested and non-nested accordion elements, which is not the case. There is only one (non-legacy) accordion element.

**Comment by Toflar** [comment]
How come it does not make a difference? If it is a nested element, you are supposed to add child elements and if not, then not? It gives the user the information where to manage the content, doesn't it?

**Comment by aschempp** [comment]
ping?
