### ISSUE TITLE
Re-add attributes to commands

### ISSUE THREAD

**Issue by m-vo** [contao/contao#6881]
### Affected version(s)

5.3

### Description

In https://github.com/contao/contao/pull/6743 attributes were removed from the commands. This, however, made them not being lazy anymore. IMHO we should revert these changes (= re-add the attributes).

One side-effect of this is, that the `ResizeImagesCommand` now forces the `Resizer` service to be instantiated, which fails during initial setup (`composer create-project`) because of the - at that point still empty - `kernel.secret` parameter.

**Comment by aschempp** [comment]
I guess you mean e.g. https://github.com/contao/contao/pull/6743/files#diff-bea386aebfe7e4b8efee79db226aa212fe9b8fb0e8c006b00f8d1c2cdf9dbb42

No idea why "adding autoconfiguration" meant removing attributes here, I fully agree we need to use attribute and not configuration.

**Comment by fritzmg** [comment]
> No idea why "adding autoconfiguration" meant removing attributes here

Likely because the parent class will already tag the service through `autoconfigure` - however, we need to add additional tag information via the attribute to make it lazy.

**Comment by leofeyer** [comment]
Exactly.
