### ISSUE TITLE
Nested accordions over 2 levels

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6885]
### Affected version(s)

5.3

### Description

I have tried to create nested accordions. In other words, an accordion and within it further accordions with corresponding elements.

Here is an attempt to visualize this.
![screen-20240212_TY3gzCP8](https://github.com/contao/contao/assets/23719181/73f483f1-660c-4d97-9da0-0c30220f7594)

I have configured it as follows in Contao 5.3.
![screen-20240212_UEIRMXpi](https://github.com/contao/contao/assets/23719181/b2bf994b-126d-4234-9238-cccced02c009)

However, it does not work correctly in the frontend.
The folding mechanism of the individual accordion elements does not work reliably.

Is this use case even possible or is this a limitation?

This is what I found on handorgel:
https://github.com/oncode/handorgel/issues/35

Should the problem be fixed for handorgel and Contao or only on the Contao side?

**Comment by fritzmg** [comment]
[As far as I tested](https://codepen.io/fritzmg/pen/qBvQZbb) there is no issue with nested accordions - as long as you use Handorgel's default CSS for example. Without any CSS the behavior is a bit flaky, yes. But Contao cannot change that.

**Comment by fritzmg** [comment]
Example template that works with nested accordions:

```twig
{# templates/content_element/accordion.html.twig #}
{% extends "@Contao/content_element/accordion.html.twig" %}

{% block init_options %}
    multiSelectable: true
{% endblock %}

{% block style %}
    {% add "handorgel_css" to head %}
        {% with {file: 'https://unpkg.com/handorgel@1.0/lib/css/handorgel.min.css'} %}{{ block('stylesheet_component') }}{% endwith %}
    {% endadd %}
{% endblock %}
```

**Comment by contaoacademy** [comment]
Thank you very much @fritzmg.

It works with your template. I am therefore closing the ticket.
