### ISSUE TITLE
Optimize link list for smaller screens

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6886]
### Affected version(s)

5.3.x

### Description

The new link-list feature is great. (https://github.com/contao/contao/pull/6353)

However, I have noticed that with very long input masks with many labels, the link list may not be fully displayed on smaller screens.

Example:

- Viewport: 1280px
- User groups

![screen-20240213_EeuslNhQ](https://github.com/contao/contao/assets/23719181/9cdee8f7-3eae-453c-87eb-04ab1d053a9d)

**Comment by de-es** [comment]
Du kannst hier horizontal scrollen mit SHIFT+Mousewheel.

**Comment by contaoacademy** [comment]
> Du kannst hier horizontal scrollen mit SHIFT+Mousewheel.

Thanks for the tip, I didn't know that.

I still think that this needs to be improved somehow.
Perhaps scrolling could be indicated by arrows?

**Comment by leofeyer** [comment]
Actually, scrolling is indicated by the fading edges, which is a quite common pattern to indicate that there is more content.

**Comment by contaoacademy** [comment]
> Actually, scrolling is indicated by the fading edges, which is a quite common pattern to indicate that there is more content.

All right. If the last word just fits into the line, then there is no fading.
If the behavior is correct, please feel free to close the ticket.

![screen-20240213_UWwFFzuT](https://github.com/contao/contao/assets/23719181/b88dc626-5940-4bb2-84f8-ba7a001bc295)

**Comment by de-es** [comment]
```
.jump-targets .inner {
    scrollbar-width: thin;
}
```
könnte noch eine Lösung sein, auch wenn die [Browserkompatibilität](https://caniuse.com/?search=scrollbar-width) nicht durchgängig gegeben ist. Zumindest im Firefox (Desktop & Mobile) und Chrome Mobile sieht es gut aus. Chrome Desktop funktioniert zwar, aber optisch (noch) nicht ganz so schön. Andere Browser nicht getestet.
