### ISSUE TITLE
Problem with permissions to frontend modules

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6887]
### Affected version(s)

5.3.x-dev

### Description

Feature: https://github.com/contao/contao/pull/6232

I tried to only allow the modules for calendars. This works correctly in the content element module, but when clicking on Theme > Layout the following error message appears:

```
Forbidden
What is the problem?
Access denied to [Subject: Source: tl_module; ID: 62] [contao_dc.tl_module].
```

Here is a video of my configuration:
https://www.loom.com/share/71ee09a36c4c49d19f5e02d0e9990c47?sid=ca158e7d-43cb-40cd-9785-9a5ed9f2687b

**Comment by aschempp** [comment]
Closed in favor of https://github.com/contao/contao/pull/6890
