### ISSUE TITLE
Missing add_schema_org in download.html.twig

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6888]
### Affected version(s)

5.3.x

### Description

It's about Feature: https://github.com/contao/contao/pull/6485/

The Schema.org data is added to the player and downloads. The customization is missing in the template for a single download.

see: https://github.com/contao/contao/blob/5.x/core-bundle/contao/templates/twig/content_element/download.html.twig

Missing:
```
{# Add metadata #}
{% block metadata %}
…
{% endblock %}
```

**Comment by m-vo** [comment]
We should probably move it entirely to the `_download` component - similar to what's in the `_picture` component for the image data. 

Because the metadata should always be added by default, no?

**Comment by Toflar** [comment]
Yes, do you mind creating a PR?😇

**Comment by leofeyer** [comment]
#6893 should do the trick, right?
