### ISSUE TITLE
Rename Piwik to Matomo

### ISSUE THREAD

**Issue by xchs** [contao/contao#690]
The web analytics platform Piwik has changed the name from Piwik to Matomo. See the [announcement](https://matomo.org/blog/2018/01/piwik-is-now-matomo/) for more information.

**Comment by rabauss** [comment]
Why is this issue marked as incompatible?

**Comment by fritzmg** [comment]
Yeah, this isn't incompatible at all actually? 😁 Contao can safely rename `analytics_piwik.html5` to `analytics_matomo.html5`, even in a bugfix version, since anyone actually using the template will have their own copy (still called `analytics_piwik`) in their `templates/` directory.

**Comment by rabauss** [comment]
That's why I wondered about the incompatibility - maybe I will push a simple PR

**Comment by leofeyer** [comment]
See #1908.
