### ISSUE TITLE
templates/content_element/text --> twig-Templates

### ISSUE THREAD

**Issue by birdsinthesun** [contao/contao#6903]
### Affected version(s)

5.3.0

### Description

Hi,
ich habe mir die neueste Version installiert und wollte geänderte Twig-Templates im Bereich Inhaltselemente-> Text zuordnen. Leider zeigt mir Contao meine geänderten Templates nicht an. Ich habe es so gemacht wie in der Doku beschrieben.

**Comment by aschempp** [comment]
hast du die Templates über das Backend erstellt? Falls nicht, versucht mal den Cache (z.B. über den Contao Manager) neu aufzubauen.

**Comment by birdsinthesun** [comment]
Hi. Danke schonmal. Ich habe die Templates über das BE erstellt. Ich versuche das dann gleich mal trotzdem den Cache neu aufzubauen

**Comment by birdsinthesun** [comment]
Ok, habe sämtliche Caches gelöscht. Es geht leider trotzdem nicht. Also Contao Manager sagt, das alles ok ist und im Debug-Modus werden auch keine Errors angegeben :-)

**Comment by fritzmg** [comment]
What exact file did you create?

**Comment by birdsinthesun** [comment]
It's the core-template text. I didn't change anything yet :-)

**Comment by birdsinthesun** [comment]
templates/birdsinthesun/content_element/text/highlight.html.twig


{% extends "@Contao/content_element/text.html.twig" %}

{#
  ** Add changes to the base template here. **

  Hint: Try adjusting blocks and attributes instead of
  overwriting the whole template. This way your version
  can remain compatible with future changes to the base
  template as well as adjustments made by extensions.

  Currently available blocks:
    "picture_component", "image", "sources", "source",
    "schema_org", "figure_component", "media",
    "media_link", "caption", "caption_inner",
    "content", "text_media", "text",
    "text_attributes", "headline_component",
    "headline_attributes", "headline_inner",
    "wrapper", "wrapper_tag", "attributes", "inner"

  Example:
    {% block picture_component %}
       {{ parent() }}
       My additional content for 'picture_component'…
    {% endblock %}
#}

**Comment by fritzmg** [comment]
Is `templates/birdsinthesun/` a registered theme template path?

**Comment by m-vo** [comment]
And since you put it in a subdirectory - did you also create a `.twig-root` file inside `templates/birdsinthesun`?

**Comment by birdsinthesun** [comment]
@fritzmg  yes

@m-vo no . I'll try. what's the content of the .twig-root file?

**Comment by m-vo** [comment]
If it's a theme directory, that's something else. The purpose of the `.twig-root` is documented here: https://docs.contao.org/dev/framework/templates/architecture/#twig-root

**Comment by m-vo** [comment]
To debug, phrase use the `debug:contao-twig` command:

`vendor/bin/contao-console debug:contao-twig content_element/text --theme=<your theme slug>`

**Comment by birdsinthesun** [comment]
@m-vo Thanks a lot! That's cool with this command. I have to contact my Hosting, because I set the PHP-Version to 8.3, but the console says there is the version 7.2. setted.

**Comment by birdsinthesun** [comment]
@m-vo I got an answer from my Hosting-Provider. They say there is no fault from this site. So maybe the detection of the PHP-Version has a problem? I don't know. The PHP-Version of my Website is seted to Version 8.3 =)
Do you have an Idea, what can I do to debug my Installation? 

I think thats strange that the Contao-Manager don't detect a wrong Version but the debug-command did.

**Comment by fritzmg** [comment]
> I have to contact my Hosting, because I set the PHP-Version to 8.3, but the console says there is the version 7.2. setted.

You will need to use the path or alias of the correct PHP CLI binary (e.g. `php83`, `php8.3`, `/usr/bin/php83` etc.).

**Comment by birdsinthesun** [comment]
@fritzmg Thanks a lot! I found a file in this directory named "php". I tryed to rename it to "php83", but "permission denied" :-/.

**Comment by fritzmg** [comment]
No, you misunderstand. You are not supposed to rename anything. You need to find the correct PHP CLI in your hosting environment.

**Comment by birdsinthesun** [comment]
@fritzmg Sorry, but I have not enough Server-Knowlege to understand this.

**Comment by birdsinthesun** [comment]
![grafik](https://github.com/contao/contao/assets/73081731/69787479-fed7-45bb-9a98-431d66ffd6c3)

**Comment by asaage** [comment]
You might find the appropriate cli binary under ```/usr/local/php83/bin/php```
To make it default in your shell edit ```/conf/phpversion```
https://helpcenter.netcup.com/de/wiki/webhosting/php-shell/

**Comment by birdsinthesun** [comment]
@asaage Thanks a lot! Now the version is changed.

**Comment by birdsinthesun** [comment]
@m-vo I run the debug-twig comand and there is no error-message. I took the twig-root file in the directory. So in the Console it is recognized. But in the Contao-Backend it's not recognized as before. I also emty all cache =)

![grafik](https://github.com/contao/contao/assets/73081731/da9e131e-6f2f-466e-b276-51c2afcaf935)

**Comment by m-vo** [comment]
What do you mean by "in the backend"? You cannot select theme templates in the content element/module/form type dropdowns - that is by design.

**Comment by birdsinthesun** [comment]
@m-vo Look, there is a Drop Down :-)


![grafik](https://github.com/contao/contao/assets/73081731/be4abb59-32da-4036-bee4-437a72cd4ee8)

**Comment by m-vo** [comment]
Yes, and it is showing exactly what it is supposed to. Templates from theme directories overwrite regular ones *at runtime*. You cannot select them as a variant.

https://docs.contao.org/dev/framework/templates/architecture/#themes

**Comment by birdsinthesun** [comment]
@m-vo sorry for the stupid questions. It works now =) AND THANKS FOR HELP

**Comment by m-vo** [comment]
You're welcome. I'm closing this here as it looks like there is no issue. Feel free to reopen if things are otherwise.

**Comment by birdsinthesun** [comment]
![contao2](https://github.com/contao/contao/assets/73081731/bd25aae6-fa7a-4376-b50c-b80d4c94b3c3)
