### ISSUE TITLE
Contao 5.3, edit article and comma character

### ISSUE THREAD

**Issue by sdahlmann** [contao/contao#6904]
### Affected version(s)

5.3.0

### Description

If I change the name of the article header under articles under Contao 5.3, a comma character appears in the Contao backend. I think this is a mistake. I can't delete the comma.
![Contao_5 3_error](https://github.com/contao/contao/assets/17680074/70e10e00-a45f-4af4-860d-96cf9495e437)

**Comment by aschempp** [comment]
I can't reproduce this in my local installation. Can you try the browser HTML inspector to see where exactly the comma is appearing? And maybe make a screenshot of your article settings?

**Comment by fritzmg** [comment]
> If I change the name of the article header

To be clear: you mean editing the settings of an article and changing the article's _title_, correct? If yes, I also cannot reproduce.

**Comment by fritzmg** [comment]
@sdahlmann do you have any extensions or customisations? Because your article view does not look right in general. It is supposed to look like this:

<img src="https://github.com/contao/contao/assets/4970961/e5c29ceb-5da8-4e20-acbc-e60ffdeab9a2" width="205">

**Comment by sdahlmann** [comment]
When I change the title name of the article the error occurs. If I undo this change via versioning, the error goes away again. Contao runs with PHP 8.2 and MySQL 8.0. Attached are a few images/attachments where you can see what the HTML source code looks like when the error is there and which extensions are installed.
![Contao_Erweiterungen](https://github.com/contao/contao/assets/17680074/da294f8b-1b7b-4b3f-8785-d96ee3be6eaf)
![easy_themes](https://github.com/contao/contao/assets/17680074/65a955b8-b05e-4aa1-a7da-41848c68ac5a)
![HTML-Code](https://github.com/contao/contao/assets/17680074/341564a4-028a-4407-9d87-33c6fe662e7f)

**Comment by fritzmg** [comment]
This is likely an error in one of these extensions and not an error in Contao.

**Comment by aschempp** [comment]
This is most likely related to the second extension you installed.
