### ISSUE TITLE
CLI command to export a theme for the manager installation

### ISSUE THREAD

**Issue by fkaminski** [contao/contao#6911]
### Description

Since the Manager supports the import of a complete theme during the initial installation, 
it would be helpful, if a CLI command could be used to create the necessary data based on an existing installation. 

![contao-manager-setup](https://github.com/contao/contao/assets/7679799/c0ec5cec-5bfa-48c5-acda-594c6a2d010e)

cross reference: https://github.com/contao/docs/issues/1344

**Comment by fkaminski** [comment]
If it is time-consuming, we can close it. The procedure is documented:
https://docs.contao.org/manual/en/guides/manager-theme/

**Comment by leofeyer** [comment]
As discussed in the Contao call, the .zip files have different sets of files depending on the purpose of the theme (e.g. the Isotope demo contains more files than the Contao demo), so we can't know which files need to be exported with such a command. We would have to add a lot of optional flags, which will probably be more difficult to learn than the documented procedure. 😄
