### ISSUE TITLE
Nested elements back link not working on multiple nesting

### ISSUE THREAD

**Issue by ben-eSM** [contao/contao#6913]
### Affected version(s)

5.3.0

### Description

Using the backlink on multiple level nested elements always leads to the first level (article) instead of going back just to the next level above.

**Comment by leofeyer** [comment]
Yes, that is an open issue unfortunately: #6803

**Comment by ausi** [comment]
See #7010

**Comment by leofeyer** [comment]
Closing this in favor of #6804 and #7010.
