### ISSUE TITLE
Header overflow

### ISSUE THREAD

**Issue by de-es** [contao/contao#6914]
### Affected version(s)

5.3.0

### Description

![contao_hamburger](https://github.com/contao/contao/assets/7645771/2d097812-d958-4efa-832e-7c956c01ee34)

Sobald das Hamburgermenü sichtbar ist, lässt sich der gesamte Body um 2px horizontal verschieben.

Kann in der Official Demo nachvollzogen werden.

Ursache ist in `main.css`:

```
#tmenu .burger button {
	margin-right: -2px;
}
```

Das Löschen der Margin löst das Problem. Getestet in FF und Chrome, latest, Desktop & Mobile.

**Comment by leofeyer** [comment]
Thank you for debugging this. See #6917.
