### ISSUE TITLE
Make buttons & jump targets sticky in popup/modal

### ISSUE THREAD

**Issue by de-es** [contao/contao#6915]
### Description

Seit 5.3 sind die Aktionsbuttons (und die neuen Jump Targets) sticky beim Bearbeiten eines Elements. Allerdings (noch) nicht, wenn diese im Modalfenster geöffnet werden.

Das könnte noch ergänzt werden, wenn man das `overflow` in `main.css` entfernt aus 

```
.popup #main .content {
	border: 0;
	margin: 0;
	overflow: auto;
}
```

Getestet in FF und Chrome, latest, Desktop & Mobile.

**Comment by leofeyer** [comment]
Thank you @de-es. See #6917.
