### ISSUE TITLE
add defered scripts not possible

### ISSUE THREAD

**Issue by Metis77** [contao/contao#692]
$GLOBALS['TL_JAVASCRIPT'][] = 'script.js|async';
$GLOBALS['TL_JAVASCRIPT'][] = 'script.js|static';

Works fine, but:

$GLOBALS['TL_JAVASCRIPT'][] = 'script.js|defer';
is not supported?

If so, I think it should also be supported.

**Comment by leofeyer** [comment]
I don't know. Why don't you add your deferred scripts at the bottom of the page? You can use `$GLOBALS['TL_MOOTOOLS']` or `$GLOBALS['TL_JQUERY']` instead of `$GLOBALS['TL_JAVASCRIPT']` to do this.

@contao/developers Maybe we should add a generic key instead of `TL_MOOTOOLS` and `TL_JQUERY`?

**Comment by Metis77** [comment]
> Why don't you add your deferred scripts at the bottom of the page?

Placed in the head, the script starts to load sooner.
With the attribute `defer ` it will not block other contents from loading and execute itself right after HTML document / DOM has been fully parsed, but before document.load.

Placing a script before the closing `</body> `is indeed similar, but not the same.
Such a script will start downloading later and therefore run later.

In particular such  is helpful for lazy loading scripts or stuff like modernizr.

So next to the attributes `static` and `async`, having `defer` would be great.

**Comment by fritzmg** [comment]
You can also use `$GLOBALS['TL_HEAD']`.

Generally I agree though that since `async` is supported, `defer` should be supported as well.
