### ISSUE TITLE
Domain prefix added to "mailto:" links in "External redirect" page type

### ISSUE THREAD

**Issue by Webstylerin** [contao/contao#6921]
### Affected version(s)

5.3.0

### Description

Hello,

I've encountered an issue when setting up the "External redirect" page type with a "mailto:" address. Instead of using the "mailto:" link as provided, the system incorrectly appends the site's domain in front of the "mailto:" address, resulting in an incorrect URL formation.

I was able to replicate this problem using the demo installation, and the screenshots I'm attaching are from there.

![Bildschirmfoto 2024-02-21 um 16 41 17](https://github.com/contao/contao/assets/3033160/9842d39b-c2f5-4605-8024-f6812074cfbd)
![Bildschirmfoto 2024-02-21 um 16 40 03](https://github.com/contao/contao/assets/3033160/ea11685c-a17e-4862-b93f-807cddfad7e8)

Best regards,
Nicole

**Comment by ausi** [comment]
Do you have a custom setting for `contao.sanitizer.allowed_url_protocols` in your config?

What does `vendor/bin/contao-console debug:container --parameter=contao.sanitizer.allowed_url_protocols` show?

**Comment by Webstylerin** [comment]
In my installation, it shows:

```
 ---------------------------------------- ----------------------------------------------------------------- 
  Parameter                                Value                                                            
 ---------------------------------------- ----------------------------------------------------------------- 
  contao.sanitizer.allowed_url_protocols   ["http","https","ftp","mailto","tel","data","skype","whatsap...  
 ---------------------------------------- ----------------------------------------------------------------- 
```
No custom settings. As mentioned, the same thing happens in the Contao demo.

**Comment by ausi** [comment]
In the HTML source code the output looks like `<a href="https://demo.contao.org/mailto:&#116;&#x65;…">` so there seems to be something that incorrectly tries to make the URL absolute.

**Comment by ausi** [comment]
It looks like the URL helper does not support `mailto:` links here: https://github.com/contao/contao/blob/5974a2595b9b8ede670992959686d8ecbbb5e142/core-bundle/src/Routing/Content/StringResolver.php#L34 _(untested)_

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6925
