### ISSUE TITLE
Unsaved image size breaks newslist

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#6922]
### Affected version(s)

4.13 | 5.x

### Description

If I have a news list with a self-defined image size and create a new breakpoint for the image size, but do **not save** it but leave the edit mask open, the news list in the frontend throws an error `Mode must be one of the Contao\Image\ResizeConfiguration::MODE_* constants.`

**Comment by aschempp** [comment]
I guess we should only take image sizes with `tstamp > 0` into account when generating images.
