### ISSUE TITLE
Veralteter Fehlertext bei "Ungültiges Anfrage-Token"

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#6924]
### Affected version(s)

5.3.0

### Description

Mir wurde heute eine Fehlermeldung angezeigt "Ungültiges Anfrage-Token".

Dabei ist mir aufgefallen, dass der Text etwas veraltet ist: "In Contao 2.10 wurde die Referer-Prüfung…"
siehe Screenshot.

Denke mal wir sollten in Contao 5 micht mehr auf eine Änderung unter Contao 2.10 hinweisen.
![screen-20240222_t0ZD0UMl](https://github.com/contao/contao/assets/23719181/5ba1c980-07c3-40fe-b67f-d8c04ded51f8)

**Comment by zoglo** [comment]
Wouldn't this be a bug in Contao 4.13 as well?
