### ISSUE TITLE
Symfony toolbar does not work with CSP enabled

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#6929]
### Affected version(s)

5.3.0

### Description

With CSP enabled, the inline style sheet of the Symfony toolbar is not loaded. I think we have to add its nonce to our CSP header, don‘t we? @fritzmg @Toflar /cc

**Comment by fritzmg** [comment]
The Symfony Toolbar Listener handles CSP itself, i.e. it checks if the response contains a CSP header and if yes adds its own nonces etc.

This worked when I tested it, not sure what went wrong now.

**Comment by leofeyer** [comment]
You are right, the nonce is added:

<img width="474" alt="" src="https://github.com/contao/contao/assets/1192057/14614f87-86bf-4327-a3b4-4db3bccf6256">

<img width="1135" alt="" src="https://github.com/contao/contao/assets/1192057/c88b47ea-f020-4ba5-a49e-04172eaa6473">

---

But there is still a reported violation in the line with the Symfony toolbar:

<img width="490" alt="" src="https://github.com/contao/contao/assets/1192057/2be9e43f-f4d5-4465-a780-4e09fe206330">

🤔

**Comment by ausi** [comment]
`style-src-attr` is about inline styles applied via `style="…"` so the `<style nonce="…">` is already working correctly I think.

**Comment by ausi** [comment]
I was not able to reproduce that. 
My header: `Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'nonce-7101e227d83be38ca1c29698b9433907'; style-src 'self' 'unsafe-inline' 'nonce-9e8de1181ea802c68e6f0cd3cc44b9aa'`
Symfony Toolbar 6.4.3

**Comment by ausi** [comment]
As the toolbar adds `unsafe-inline` for `style-src` I don’t understand how there could be a viloation for `style-src-attr` at all. Are you sure the report is from the same request?

**Comment by leofeyer** [comment]
Yes, the browser console shows the error, too:

<img width="1163" alt="" src="https://github.com/contao/contao/assets/1192057/20e89819-ab32-454a-94d2-3c3aec3b5463">

Luckily Chrome has a more detailed console output:

<img width="510" alt="" src="https://github.com/contao/contao/assets/1192057/2001c3c1-4940-4557-922c-1bc7927372aa">

Using `innerHTML` seems to be tricky with CSP: https://datatables.net/forums/discussion/68460/content-security-policy-csp

**Comment by ausi** [comment]
The console output has an interesting note: `'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.`.
So I think this looks like a bug in the Symfony profiler: https://github.com/symfony/symfony/blob/f78f932dc3974884a3c35c227b345c9d920f3f39/src/Symfony/Bundle/WebProfilerBundle/Csp/ContentSecurityPolicyHandler.php#L152-L154

If they add `unsafe-inline` they also need to remove all `hash-` and `sha…-` values according to that note from your screenshot.

**Comment by fritzmg** [comment]
See https://github.com/symfony/symfony/issues/53552 
@leofeyer and @ausi may be post your findings there to get the issue re-opened.

**Comment by leofeyer** [comment]
I investigated this further and found out that the problematic code is injected by the Symfony local web server:

<img width="239" alt="" src="https://github.com/contao/contao/assets/1192057/e66b9691-1547-440b-99ec-901d6e61ca9e">

```html
<div class="sf-cli sf-toolbar-block sf-toolbar-block-sf-cli sf-toolbar-status-normal sf-toolbar-block-right">
	<div class="sf-toolbar-icon">
		<span class="sf-toolbar-label">
			<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="24" height="24" viewBox="0 0 24 24" enable-background="new 0 0 24 24" version="1.1">
				<path style="stroke:none;fill-rule:evenodd;fill:white;fill-opacity:1;" d="M 24 2.398438 C 24 1.074219 22.925781 0 21.601562 0 L 2.398438 0 C 1.074219 0 0 1.074219 0 2.398438 L 0 21.601562 C 0 22.925781 1.074219 24 2.398438 24 L 21.601562 24 C 22.925781 24 24 22.925781 24 21.601562 Z M 24 2.398438 "/>
				<path style="stroke:none;fill-rule:nonzero;fill:black;fill-opacity:1;" d="M 18.078125 3.109375 C 16.742188 3.15625 15.578125 3.894531 14.710938 4.910156 C 13.75 6.027344 13.109375 7.351562 12.648438 8.703125 C 11.824219 8.027344 11.191406 7.152344 9.867188 6.773438 C 8.847656 6.480469 7.773438 6.601562 6.785156 7.335938 C 6.320312 7.683594 5.996094 8.210938 5.84375 8.710938 C 5.449219 9.996094 6.261719 11.144531 6.628906 11.558594 L 7.4375 12.421875 C 7.605469 12.59375 8.007812 13.035156 7.808594 13.667969 C 7.597656 14.359375 6.765625 14.804688 5.914062 14.542969 C 5.53125 14.425781 4.984375 14.144531 5.105469 13.742188 C 5.15625 13.578125 5.273438 13.457031 5.335938 13.316406 C 5.394531 13.195312 5.421875 13.105469 5.441406 13.050781 C 5.597656 12.542969 5.382812 11.878906 4.835938 11.710938 C 4.328125 11.554688 3.808594 11.679688 3.605469 12.332031 C 3.378906 13.078125 3.734375 14.425781 5.640625 15.015625 C 7.875 15.703125 9.765625 14.484375 10.035156 12.898438 C 10.203125 11.90625 9.753906 11.167969 8.933594 10.21875 L 8.261719 9.476562 C 7.855469 9.070312 7.71875 8.378906 8.136719 7.847656 C 8.492188 7.402344 8.996094 7.210938 9.824219 7.433594 C 11.03125 7.761719 11.566406 8.597656 12.464844 9.273438 C 12.09375 10.492188 11.851562 11.710938 11.632812 12.804688 L 11.5 13.621094 C 10.855469 16.984375 10.367188 18.832031 9.09375 19.890625 C 8.839844 20.074219 8.472656 20.347656 7.917969 20.367188 C 7.628906 20.375 7.535156 20.175781 7.53125 20.089844 C 7.527344 19.886719 7.695312 19.792969 7.808594 19.703125 C 7.980469 19.609375 8.238281 19.457031 8.21875 18.960938 C 8.203125 18.378906 7.71875 17.875 7.023438 17.898438 C 6.5 17.917969 5.703125 18.40625 5.734375 19.308594 C 5.765625 20.238281 6.628906 20.933594 7.9375 20.890625 C 8.636719 20.867188 10.195312 20.582031 11.730469 18.753906 C 13.519531 16.660156 14.019531 14.261719 14.394531 12.503906 L 14.816406 10.183594 C 15.050781 10.210938 15.300781 10.230469 15.570312 10.238281 C 17.796875 10.285156 18.910156 9.132812 18.929688 8.292969 C 18.941406 7.785156 18.597656 7.285156 18.113281 7.296875 C 17.769531 7.304688 17.335938 7.535156 17.230469 8.011719 C 17.128906 8.480469 17.941406 8.902344 17.308594 9.3125 C 16.855469 9.605469 16.050781 9.808594 14.914062 9.644531 L 15.121094 8.5 C 15.542969 6.335938 16.0625 3.671875 18.035156 3.609375 C 18.179688 3.601562 18.703125 3.613281 18.71875 3.960938 C 18.722656 4.078125 18.691406 4.109375 18.554688 4.375 C 18.417969 4.582031 18.363281 4.757812 18.371094 4.960938 C 18.390625 5.511719 18.8125 5.875 19.417969 5.855469 C 20.234375 5.828125 20.46875 5.035156 20.453125 4.628906 C 20.421875 3.671875 19.410156 3.066406 18.078125 3.109375 Z M 18.078125 3.109375 "/>
			</svg>
		</span>
		<span class="sf-toolbar-value">Server</span>
	</div>
	<div class="sf-toolbar-info" style="left: 0px;">
		<div class="sf-toolbar-info-group">
			<div class="sf-toolbar-info-piece">
				<b>Symfony CLI</b>5.8.11
			</div>
			<div class="sf-toolbar-info-piece">
				<b>PHP</b>PHP FPM 8.3.3
			</div>
			<div class="sf-toolbar-info-piece">
				<b>Tunnel</b><span class="sf-toolbar-status sf-toolbar-status-red">Down</span>
			</div>
			<div class="sf-toolbar-info-piece">
				<b>Docker Compose</b><span class="sf-toolbar-status sf-toolbar-status-red">Down</span>
			</div>
			<div class="sf-toolbar-info-piece">
				<b>Env Vars</b><span class="sf-toolbar-status sf-toolbar-status-red">None</span>
			</div>
			<div class="sf-toolbar-info-piece"><b>RabbitMQ UI</b> <span class="sf-toolbar-status sf-toolbar-status-red">Down</span></div>
			<div class="sf-toolbar-info-piece"><b>Webmail</b> <span class="sf-toolbar-status sf-toolbar-status-red">Down</span></div>
			<div class="sf-toolbar-info-piece">
				<b><a class="sf-cli-blackfire" href="https://blackfire.io/" rel="noopener" target="_blank">Blackfire.io Agent</a></b><span class="sf-toolbar-status sf-toolbar-status-red">Down</span></div>
		
		</div>
	</div>
	<div></div>
</div>
```

There is a `style="left: 0px;"` in the code and two `style="stroke:none;…"` attributes in the inline SVG which cause the three violations reported above. The problem does not occur on Nginx, Apache or any other non-local web server, so I guess we can ignore it, can‘t we?

**Comment by Toflar** [comment]
Can you report it to the project though? https://github.com/symfony-cli/symfony-cli

**Comment by leofeyer** [comment]
https://github.com/symfony-cli/symfony-cli/issues/446
