### ISSUE TITLE
Theme-Import and -Export --> templates/subfolder

### ISSUE THREAD

**Issue by birdsinthesun** [contao/contao#6934]
### Affected version(s)

5.3

### Description

Hi. The import and export did not include the subfolders of the templates-folder.
## The EXPORT-ENVIRONMENT
![grafik](https://github.com/contao/contao/assets/73081731/5377f56b-0043-4671-9686-25c5aa4b8f2c)

## The IMPORT-ENVIRONMENT
![grafik](https://github.com/contao/contao/assets/73081731/5bd9e2b6-2d70-43d5-8d58-bc57d0869b2b)

**Comment by asaage** [comment]
As far as i understand the text/highligt.html.twig wouldn't work regardless the fact it's ex/imported.
You would need ```templates/content_element/text/highlight.html.twig``` for ```templates/birdsinthesun/content_element/text/highlight.html.twig``` to work right?

**Comment by birdsinthesun** [comment]
No. The subfolders are not included in the .cto file.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we can add subfolders to the `.cto` file.

However, as explained by @asaage above, the `templates/birdsinthesun/content_element/text/highlight.html.twig` will not work without a `templates/content_element/text/highlight.html.twig` template.

**Comment by zoglo** [comment]
See: https://github.com/contao/contao/pull/7472
