### ISSUE TITLE
Newsletterliste-Modul und Newsletterleser --> Verteiler ist leer obwohl einer existiert

### ISSUE THREAD

**Issue by birdsinthesun** [contao/contao#6935]
### Affected version(s)

5.3

### Description

![grafik](https://github.com/contao/contao/assets/73081731/6e342a40-4d6c-47e0-949c-e20dd48f530e)

**Comment by fritzmg** [comment]
Did you configure a redirect page in your newsletter channels? Only channels with configured redirect pages will be shown here.

**Comment by birdsinthesun** [comment]
Thank you. It is irritating, that that isn't the same in the newsletter-abo-modul and in the newsletter-quit-modul. But now I know it. Thanks again

**Comment by fritzmg** [comment]
The newsletter list depends on that setting, while the other one does not.
