### ISSUE TITLE
The captcha legend is displayed in the "member_grouped" template

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#6937]
### Affected version(s)

5.3.0

### Description

The captcha legend respectively the fieldset should be set to "display: none" (like in Contao 4.13) and the language setting in "tl_member.xlf" is missing.

```
<trans-unit id="tl_member.captchaDetails">
	<source>Captcha details</source>
	<target>Captcha-Details</target>
</trans-unit>
```

Reproduce the issue in the online demo:

- Create a front end module of type "Registration"
- Select all editable fields
- Choose "member_grouped" as form template and klick "Save and close"
- Add the module in an article
- Go to the front end preview of this article

![image1](https://github.com/contao/contao/assets/1942550/9e590445-0ff2-4498-b2c2-904d7b3f77fd)
![image2](https://github.com/contao/contao/assets/1942550/0663a09f-0f00-4237-8a11-aa3f5dfebf5f)

**Comment by fritzmg** [comment]
There are a few errors at play here:

* The current JavaScript does not hide the parent `fieldset`, if a `<legend>` is present.
* The output of the `<legend>` is deliberate - however, its content should be "Security question" and not `captchaDetails`.
* The same error would also occur in Contao 4.13, but for some reason the  `<legend>` is not output there (which is not intended).
