### ISSUE TITLE
Inkonsistenz in der Dateiverwaltung nach Versionswiederherstellung

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#694]
Nach der Umbenennung eines Ordners in der Dateiverwaltung und anschließender Wiederherstellung der vorherigen Version, tritt in der Dateiverwaltung offenbar eine Inkonsistenz auf. Bei Durchführung der Synchronisation erscheint folgender Hinweis:
> Die Datei bzw. der Ordner "files/alter-name" wurde gelöscht

**Comment by leofeyer** [comment]
Da umbenannte Dateien auch noch andere Probleme in Verbindung mit der Versionierung verursachen (siehe z.B. #671), sollten wir beim Umbenennen von Dateien die bestehenden Versionen löschen.

**Comment by leofeyer** [comment]
Wie am 26. September auf Mumble besprochen, dürfen der Dateiname und der Pfad nicht versioniert werden.

**Comment by leofeyer** [comment]
Behoben in 9a8e91681a4d1acaf45e3ab48584f437be7a9078.
