### ISSUE TITLE
Diff view does not work for mass edited data

### ISSUE THREAD

**Issue by bytehead** [contao/contao#6942]
### Affected version(s)

4.13, 5.3

### Description

Tested on https://demo.contao.org:

Re-generate aliases for all pages (multiple edit) and the diff/change view does not work (probably wrong url for popup) afterwards:

![Bildschirmfoto 2024-02-27 um 10 53 17](https://github.com/contao/contao/assets/754921/052c388a-a63e-4ac3-a55e-a07a06bf9c12)

**Comment by leofeyer** [comment]
Confirmed.
