### ISSUE TITLE
Twig Templates not found in Custom Bundles

### ISSUE THREAD

**Issue by tdoescher** [contao/contao#6948]
### Affected version(s)

5.3

### Description

I want to use Twig-Templates in my [Google Maps Bundle](https://github.com/tdoescher/contao-googlemaps-bundle) and extend support for CSP.

In Frontend it works, but in the Backend i got this error below when i edit my content element:

Tried to list template options for the modern fragment type "content_element/googlemaps_embed" but could not find any template. Did you forget to create the default template?

I cant find any mistake in my Bundle, is this an error in Contao 5.3? I still have to register the templates somewhere?

**Comment by fritzmg** [comment]
Your bundle is missing the `src/Resources/contao/templates/.twig-root` file.

https://docs.contao.org/dev/framework/templates/architecture/#twig-root

**Comment by tdoescher** [comment]
Thank you, I hadn't seen this part of the documentary before.
