### ISSUE TITLE
Bearbeiten von Mitgliedergruppen und Benutzergruppen Abschnitt "Konto-Einstellungen"

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#695]
Beim Bearbeiten von Mitgliedergruppen sowie Benutzergruppen ist die Bezeichnung des untersten Abschnitts "Konto-Einstellungen". Zutreffender wäre eine Bezeichnung wie "Gruppen-Einstellungen".

**Comment by leofeyer** [comment]
Siehe #1124
