### ISSUE TITLE
System-Log Meldung "User "xyz" has logged in" ohne Benutzernamen im Feld Benutzer

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#696]
Im System-Log fehlt bei der Meldung ```User "xyz" has logged in``` die Angabe des Benutzernamens im Feld Benutzer, dort ist nur "anon." vermerkt. Bei Contao 3.5 wurde dort noch der Benutzername gespeichert.

**Comment by aschempp** [comment]
In welcher Contao-Version hast du das entdeckt? Hast du 2FA aktiviert? Frontend oder Backend? Und ist es in der Online Demo reproduzierbar?

**Comment by Mynyx** [comment]
> In welcher Contao-Version hast du das entdeckt?

4.4.42

> Hast du 2FA aktiviert?

Nein

> Frontend oder Backend?

Beides

> Und ist es in der Online Demo reproduzierbar?

Nein

**Comment by leofeyer** [comment]
<del>In Contao 4.4 wird tatsächlich `anon.` anstatt des Benutzernamens gespeichert.</del> In der 4.8 tritt das Problem nicht mehr auf.

**Edit:** Ich konnte das Problem in Contao 4.4.43 nicht mehr reproduzieren. @Mynyx Tritt das Problem bei Dir in Contao 4.4.43 noch auf?

**Comment by Mynyx** [comment]
> Tritt das Problem bei Dir in Contao 4.4.43 noch auf?

Ja, das Problem tritt unverändert auf.

**Comment by Mynyx** [comment]
Werden hierzu noch weitere Informationen benötigt?

**Comment by leofeyer** [comment]
Ja. Da ich das Problem nicht reproduzieren kann, wäre es schön, wenn Du es in Deinem System debuggen könntest.

**Comment by leofeyer** [comment]
@Mynyx Gibt es hierzu neue Erkenntnisse?
