### ISSUE TITLE
Can't find a way to get support

### ISSUE THREAD

**Issue by biowebfr** [contao/contao#6972]
### Affected version(s)

4

### Description

I'm really sorry to post here, I know I should not but I tried to post on the forum (https://community.contao.org/) and I get this : 
![image](https://github.com/contao/contao/assets/46192868/0310357a-7409-40da-9cca-6c2a693437b9)

So I can't post my question and I don't find any discord or whatever plateform to ask the community on the website instead of this forum.

Can someone oriente me ?

Again really sorry about this.
Thank you.

**Comment by fritzmg** [comment]
» https://contao.org/en/support

There is an issue with the English forum as far as I know. You can also post your question on the German forum if you want. Otherwise you can use the #english channel in the community Slack.
