### ISSUE TITLE
Symfony Profiler: type error in Security panel

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#6988]
### Affected version(s)

5.3.1

### Description

If you open the _Security_ tab in the Symfony Profiler, the following error occurs:

```
Twig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector::getVoters(): Return value must be of type Symfony\Component\VarDumper\Cloner\Data|array, null returned").

  at vendor\symfony\security-bundle\Resources\views\Collector\security.html.twig:394
```

```
TypeError:
Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector::getVoters(): Return value must be of type Symfony\Component\VarDumper\Cloner\Data|array, null returned

  at vendor\symfony\security-bundle\DataCollector\SecurityDataCollector.php:310
  at Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector->getVoters()
     (vendor\twig\twig\src\Extension\CoreExtension.php:1635)
  at twig_get_attribute()
     (var\cache\dev\twig\e0\e06641b3c245457efd48241b8429e11b.php:907)
  at __TwigTemplate_fbb474e51ebbc75140771bb23f7378cb->block_panel()
     (vendor\twig\twig\src\Template.php:171)
  at Twig\Template->displayBlock()
     (var\cache\dev\twig\be\be4fb5d7861c7319d5e2fe400dceaadc.php:102)
  at __TwigTemplate_0560d52f871b91fe69ac98c28badcfdd->block_body()
     (vendor\twig\twig\src\Template.php:171)
  at Twig\Template->displayBlock()
     (var\cache\dev\twig\5d\5d546e294384ca9d24298c3c40066e83.php:110)
  at __TwigTemplate_ce7be3800a42b24d143acdf76a001cc2->doDisplay()
     (vendor\twig\twig\src\Template.php:394)
  at Twig\Template->displayWithErrorHandling()
     (vendor\twig\twig\src\Template.php:367)
  at Twig\Template->display()
     (var\cache\dev\twig\be\be4fb5d7861c7319d5e2fe400dceaadc.php:52)
  at __TwigTemplate_0560d52f871b91fe69ac98c28badcfdd->doDisplay()
     (vendor\twig\twig\src\Template.php:394)
  at Twig\Template->displayWithErrorHandling()
     (vendor\twig\twig\src\Template.php:367)
  at Twig\Template->display()
     (var\cache\dev\twig\e0\e06641b3c245457efd48241b8429e11b.php:52)
  at __TwigTemplate_fbb474e51ebbc75140771bb23f7378cb->doDisplay()
     (vendor\twig\twig\src\Template.php:394)
  at Twig\Template->displayWithErrorHandling()
     (vendor\twig\twig\src\Template.php:367)
  at Twig\Template->display()
     (vendor\twig\twig\src\Template.php:379)
  at Twig\Template->render()
     (vendor\twig\twig\src\TemplateWrapper.php:38)
  at Twig\TemplateWrapper->render()
     (vendor\twig\twig\src\Environment.php:280)
  at Twig\Environment->render()
     (vendor\symfony\web-profiler-bundle\Controller\ProfilerController.php:411)
  at Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController->renderWithCspNonces()
     (vendor\symfony\web-profiler-bundle\Controller\ProfilerController.php:111)
  at Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController->panelAction()
     (vendor\symfony\http-kernel\HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor\symfony\http-kernel\HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor\symfony\http-kernel\Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public\index.php:44)       
```

**Comment by fritzmg** [comment]
This looks like it is also a Symfony issue. The `SecurityDataCollector::getVoter()` method wrongly assumes that `$this->data['voters']` will always have data - which is not the case if no voters were present/added during collection.

However, shouldn't there always be voters?

**Comment by fritzmg** [comment]
> However, shouldn't there always be voters?

The reason is our decoration of Symfony's access decision manager, which breaks the tracing functionality of Symfony's `TraceableAccessDecisionManager`. See the explanation here: https://github.com/symfony/symfony/issues/54225#issuecomment-1987234541

As such this cannot be easily fixed within Contao I think - unless we find a way to _not_ decorate the access decision manager.

/cc @aschempp

**Comment by aschempp** [comment]
> As such this cannot be easily fixed within Contao I think - unless we find a way to _not_ decorate the access decision manager.

I don't think we can. There is one access decision manager in Symfony, be we need multiple access decision strategies depending on the firewall. But I guess this is solved with a PR to Symfony?

**Comment by fritzmg** [comment]
Yes, it needs to be fixed in Symfony. In order to make the voters visible in the profiler our decorator service can also implement an adjustment after the fix was released.

**Comment by aschempp** [comment]
Would the adjustment harm before it is realeased in Symfony? Because then we might already "fix" this and be ready as soon as Symfony is fixed?

**Comment by fritzmg** [comment]
Yes - as discussed in the Symfony issue I will provide a PR so that the `TraceableAccessDecisionManager` checks for `method_exists(..., 'getVoters')` etc. and this was agreed on. So we could implement these methods ahead of time in our decorator service - in anticipation that it will be fixed in Symfony this way.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7021
