### ISSUE TITLE
System-Log Eintrag bei Wiederherstellung von gelöschten Elementen

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#699]
Bei der Wiederherstellung von gelöschten Elementen wird im System-Log ein Eintrag mit der Nachricht ```Undone SELECT * FROM tl_undo WHERE id='123' LIMIT 0,1``` erzeugt.

Es wäre sinnvoller, wenn für den System-Log Eintrag statt ```SELECT * FROM tl_undo WHERE id='123' LIMIT 0,1```die ursprüngliche DELETE-Query verwendet würde, wie sie in ```tl_undo``` in der Spalte ```query``` gespeichert ist.

**Comment by leofeyer** [comment]
Siehe #495.
