### ISSUE TITLE
Twig Rendering error related to mime types / pdf attachment

### ISSUE THREAD

**Issue by greenertux** [contao/contao#6992]
### Affected version(s)

5.3.1

### Description

We noticed one page is no longer accessible, I suspect after upgrading to Contao 5.3.0. The update to 5.3.1 did not solve the issue.
In the frontend we just get "internal server error" in logs and debugging the following error appears:
`An exception has been thrown during the rendering of a template ("Unable to retrieve metadata from "Intranet/dateien/Dokumente/Betriebsrat/Newsletter Nr.06/2016.pdf": A mime type could not be detected. Set the "$default" argument to suppress this exception.").`
It seems to be something is not working correctly in `vendor/contao/core-bundle/contao/templates/twig/component/_download.html.twig:64`

This page has many PDF attachments, but somehow only that particular one is causing problems. I have checked using `file --mime-type` command on that particular file and it can detect `application/pdf` just fine. I also checked file system permissions and it has the same permissions as all other files do.

I have not been able to find the part in Contao's codebase where the actual mime type checking is done.

**Comment by m-vo** [comment]
Just to be sure I understand your setup: You have a page with a download(s) content element where it breaks if said pdf file was selected in the backend?

**Comment by greenertux** [comment]
Basically yes, but this page is really old and that attachment is from 2016, so it was attached to that file long ago. I cannot even open the article in the backend anymore, I get the same error then. That's why I assume a bug was introduced somewhere in the latest versions.
I am certain that article has not been changed for at least 6 months because the problem exists in both our test and production systems and the test system was copied from production > 6 months ago.

**Comment by m-vo** [comment]
See #7032

**Comment by greenertux** [comment]
Thanks, replacing FilesystemItem.php fixes the problem for me.
