### ISSUE TITLE
%locale% must not be in parameters.yml

### ISSUE THREAD

**Issue by aschempp** [contao/contao#70]
We have discussed this before. The `%locale%` is the system fallback for everything like language files and therefore should not be configurable by the user. Otherwise if I choose to use `de` as default, modules without a german translation would not provide any labels.

**Comment by leofeyer** [comment]
This is actually how Symfony does it.

https://github.com/symfony/symfony-standard/blob/2.7/app/config/parameters.yml.dist#L17

If someone wants to change it, why would we stop him?

**Comment by aschempp** [comment]
We should not ask for it in the parameters.yml.dist because it's likely german natives will set it to "de" which will likely break lots of extensions and maybe the core too.

**Comment by leofeyer** [comment]
Why would it? And why not follow the Symfony standard here?

**Comment by aschempp** [comment]
We've discussed this before. The Contao default locale always was "en". Every module will/should provide an english language folder as the fallback, even if the content is german. If I set the locale to "fr", the backend would not have any labels at all (if FR is not shipped with the core).

**Comment by leofeyer** [comment]
We cannot influence the settings anyway, because it is part of the standard edition and people might as well use the Symfony standard edition with the locale being configurable. Therefore we should follow the Symfony standards.

> If I set the locale to "fr", the backend would not have any labels at all

That's probably not true, because English is always loaded as fallback language.

**Comment by aschempp** [comment]
> That's probably not true, because English is always loaded as fallback language.

That's exactly the point, it is NOT. At least not for the Symfony translator, and addition that configuration but not using it our own would make no sense at all.

**Comment by leofeyer** [comment]
We are not using the Symfony translator yet. And in Contao, English is always loaded as fallback language in case there are missing labels. But we can discuss this on Mumble if you want.

**Comment by aschempp** [comment]
Yes please.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/148.
