### ISSUE TITLE
The registry already contains an instance for tl_page::id beim Anlegen einer Seite

### ISSUE THREAD

**Issue by mwitzmann** [contao/contao#70]
**Affected version(s)**
Tritt auf in 4.4.25 und 4.6.4 (in der Contao-Demo):

**How to reproduce**  
Legt man eine neue Seite über die Seitenstruktur an und speichert den Datensatz unter Angabe der Pflichtfelder, erhält man oben genannte Fehlermeldung.

In Contao 4.4.24 funktioniert es.

**Comment by wernergraser** [comment]
same as #63
