### ISSUE TITLE
Link bei nicht öffentlichen Dateien in Dateiverwaltung

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#700]
In der Übersicht der Dateiverwaltung ist das Icon vor dem Dateinamen auch bei Dateien, die sich in einem nicht öffentlichen Ordner befinden, mit der öffentlichen URL verlinkt. Ein Klick auf das Icon bei diesen Dateien führt dementsprechend zu einer Fehlerseite.

**Comment by leofeyer** [comment]
Geändert in 9b208773b939955879c1704931ec39ac36d8574e.
