### ISSUE TITLE
Make our custom Twig escaper forward compatible with Twig 3.9

### ISSUE THREAD

**Issue by m-vo** [contao/contao#7009]
### Affected version(s)

5.x

### Description

As of https://github.com/twigphp/Twig/pull/3883/files the original escaper filter methods were moved into static functions (targeted for Twig 3.9). They are now marked as internal but as we still do not want to repeat this code, we need to make our calls forward compatible.

**Comment by leofeyer** [comment]
See #7123 (and follow-up PRs)
