### ISSUE TITLE
4.8.1: Custom section does not appear

### ISSUE THREAD

**Issue by jankout** [contao/contao#701]
**Affected version(s)**
4.8.1

**Description**  
The custom section does not appear.

**How to reproduce**  

1. Add a custom section in the page template (eg. "1 column")
2. save it
3. add a module (eg. article) to the custom section
4. go to the module Article and add new article for the custom section and fill it with content

The source code seems like this

<img width="529" alt="custom section code" src="https://user-images.githubusercontent.com/3715050/64055092-ba1e8b00-cb8a-11e9-94f8-c63deab2b3ac.png">

**Comment by aschempp** [comment]
See https://github.com/contao/contao/issues/677
