### ISSUE TITLE
Twig Template: Extending News bundle template leads to Exception

### ISSUE THREAD

**Issue by ghost** [contao/contao#7020]
### Affected version(s)

4.13.38

### Description

In Contao 4.13.37, the following worked:
`{% extends '@Contao_ContaoNewsBundle/modules/mod_newsreader.html5' %}`
In Contao 4.13.38, an exception is thrown:
`... Template \"@Contao_ContaoNewsBundle/modules/mod_newsreader.html5\" is not defined in ...`
Have I overlooked something, or am I doing something wrong?

**Comment by fritzmg** [comment]
Please post the path and content of your template.

**Comment by ghost** [comment]
Sure!

```
# bundles/MyVendor/MyBundle/src/Resources/contao/templates/modules/mod_newsreader_jobs.html.twig

{% trans_default_domain "contao_tl_news" %}
{% extends '@Contao_ContaoNewsBundle/modules/mod_newsreader.html5' %}

{% block content %}

    {{ '{{picture::public/bundles/myvendormybundle/img/jobs/job-detail-header.jpg?size=7}}' }}

    {{ articles | raw }}

{% endblock %}
```

**Comment by m-vo** [comment]
Why are you using the specific namespace instead of the managed namespace (`@Contao`)?

**Comment by m-vo** [comment]
Also, there is very likely no such template in that subdirectory. That would need a twig root file in the main template directory. 

&rarr; `{% extends '@Contao/mod_newsreader.html5` %}

**Comment by ghost** [comment]
I have already tried various namespaces, but the error remains
`@Contao`
`@ContaoNewsBundle`
`@Contao_NewsBundle`
Could you please provide the correct namespace?

**Comment by ghost** [comment]
I can confirm that it works with `{% extends '@Contao/mod_newsreader.html5' %}` and `{% extends '@Contao/mod_newslist.html5' %}`
