### ISSUE TITLE
Any Nonce in CSP-header if not Content-Element is visible

### ISSUE THREAD

**Issue by xprojects-de** [contao/contao#7022]
### Affected version(s)

5.3

### Description

Hello,

if you have CSP activated with following content (see below) and you have a page e.g. HTML-Module in header but without any published content element then there is a nonce in the CSP-header which probably doesn't come from Contao i think!
As soon as just one content element is activated, the correct nonce is set!

**CSP-Content Rootpage:**
default-src 'self' data:;
script-src 'self' https://*.googletagmanager.com;
style-src 'self';
img-src 'self' https://*.google-analytics.com https://*.googletagmanager.com;
connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com

**Header in Response:**
Content-Security-Policy
default-src 'self' data:; script-src 'self' https://*.googletagmanager.com 'nonce-/w6r5NE0t9WzS8PibjrHP6GB' 'unsafe-inline' 'nonce-9c7b713a4edaadf75f4c74cac460386f'; style-src 'self' 'unsafe-inline' 'nonce-c61f1557991877cbd79de12e65ee7a2b'; img-src 'self' https://*.google-analytics.com https://*.googletagmanager.com; connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com; report-uri https://contao.local5.latest:8890/_contao/csp/report/2

I set a breakpoint in the Contao\CSPHandler at getNonce and that is defacto not called. As soon as just one ore more elements are published the method is called!
I also have a kernel request listener and the nonce isn't there yet either. But the nonce is then finally present in the browser and all my scripts are not loaded because they do not have a nonce!!?!

That is very strange!
You can reproduce it by activating the CSP in the root page, copying the above content and outputting the page without published content elements!

Am I doing something wrong? Who set the nonce?

Greetings

**Comment by ausi** [comment]
I was not able to reproduce that in production. However a nonce gets added if the debug mode is enabled.

**Comment by xprojects-de** [comment]
yes you are right! It only in the debug mode! Sorry!

**Comment by xprojects-de** [comment]
Should I close the issue or should we still look at it?

**Comment by ausi** [comment]
If this causes issues I think we should open an issue in Symfony for it.
