### ISSUE TITLE
parseFrontendTemplate hook for Twig templates

### ISSUE THREAD

**Issue by tdoescher** [contao/contao#7023]
### Description

Hello,

the parseFrontendTemplate hook does not work for Twig templates, is there an alternative way to manipulate Twig templates? I can't find anything in the documentation.

**Comment by m-vo** [comment]
It's intentional that the `parseFrontendTemplate` hook does not work anymore for twig templates. We discussed introducing an event that allows to manipulate the template context when rendering but we are still lacking use cases where it is really necessary. What are you trying to achieve? 
 
  You might also want to look into https://github.com/contao/contao/pull/3913 and related issues.

**Comment by tdoescher** [comment]
I use this Hook to wrap elements inside an template-Tag, so I can change easy the visibility with JavaScript. I use this in my contao-cokiban-bunde.

**Comment by m-vo** [comment]
This sounds like it should better be done in the templates themselves, no? For instance in the `content_element/_base.html.twig` template if you want to target all content elements.

**Comment by tdoescher** [comment]
No, that would not be a good solution. Then I would have to manually customize all templates that should be protected by my Cokiban bundle. Currently I can simply specify the templates (ce_googlemaps_embed, ce_youtube, analytics_google) to be protected in the config. For the elements I could still work with the getContentElement hook, but then this no longer works with the analytics_google or js_... templates.

**Comment by m-vo** [comment]
You only need to adjust the `content_element/_base.html.twig` template. In there you either get the config from the current `tl_content` row (already there under `data`) or you write a custom function that returns it from any other location. And then you add your wrapper depending on your config.

Manipulating HTML, that was previously compiled is almost always a bad idea from a security standpoint.

**Comment by m-vo** [comment]
Regarding the "other" templates, I think you should adjust them individually. They can be *anything* and you probably cannot assume, that it's ok/safe to inject a wrapper (or any other modification).

Also think about future templates that you cannot know - e.g for the backend.

**Comment by tdoescher** [comment]
Ok, So far this method has worked very reliably, the templates are only changed if you explicitly set this in the config, the user must of course check whether this works. Backend templates do not play a role.

**Comment by tdoescher** [comment]
I have solved my problem by adding an custom TwigExtension and extend the default _base.html.twig Template.

Thanks @m-vo  for the suggestion.
