### ISSUE TITLE
Not existing `/contao` URL generates front end 401 page

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#7024]
### Affected version(s)

4.13, 5.3

### Description

If you access a URL with the `/contao` (`%contao.backend.route_prefix%`) prefix, but the URL does not exist in the router, the _front end_ 401 page will be generated. For example: https://demo.contao.org/contao/foobar

I expected either the back end login to be shown (if you are not logged in) or the front end 404 page but not its 401 page.

**Comment by aschempp** [comment]
I think this is easily explainable: A non-existing route does not have a backend scope, so the front end is rendered. But our skeleton defaults to protect `/contao` with `ROLE_USER` (see https://github.com/contao/contao/blob/5.x/manager-bundle/skeleton/config/security.yaml#L55).

The only solution I can think of would be to always make `/contao` a backend scope, but that might cause other issues, and we do not have a 404 page in the back end.

**Comment by leofeyer** [comment]
I think every route that begins with `%contao.backend.route_prefix%` should have back end scope, shouldn‘t it?

**Comment by leofeyer** [comment]
As discussed in the Contao call, the user should see the back end login form if they are not yet authenticated or the back end 404 page (which is the default Symfony 404 page).

**Comment by aschempp** [comment]
see #7086
