### ISSUE TITLE
Edit button in file manager is not disabled

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#7038]
### Affected version(s)

5.3.x

### Description

If you grant access to the file manager to a regular back end user, but do not allow any fields of `tl_files` to be edited, the edit button is still displayed in the file manager. Clicking on the edit button will result in an `AccessDeniedException`.

The edit button should be disabled in such a case.

**Comment by leofeyer** [comment]
I cannot confirm this in my installation:

<img width="817" alt="" src="https://github.com/contao/contao/assets/1192057/f9d44fb9-81fe-416a-be22-8d60e74b3b7f">

**Comment by fritzmg** [comment]
This is from my local `5.3.x` installation (tested with `5.3.1` tag and current `5.3.x` branch):

![Screen Shot 2024-03-21 at 11 32 45](https://github.com/contao/contao/assets/4970961/148588cb-ba09-4c37-b57c-a6384f7f2dbe)

![Screen Shot 2024-03-21 at 11 32 55](https://github.com/contao/contao/assets/4970961/19b6aefd-ec7c-4a7a-be26-603912de5def)

**Comment by leofeyer** [comment]
Are you sure that neither the user group permissions nor the user permissions grant access?

<img width="548" alt="" src="https://github.com/contao/contao/assets/1192057/0f56482e-a44c-4e60-93f3-ca685e0369be">

<img width="638" alt="" src="https://github.com/contao/contao/assets/1192057/8c782dc8-0981-491d-8033-9ce0b6743a0d">

<img width="543" alt="" src="https://github.com/contao/contao/assets/1192057/e02909e4-67e6-4ffc-861a-845802c2a97d">

**Comment by fritzmg** [comment]
The difference is that you did not grant any **File operation permissions**. To summarize the reproduction:

1. Create a user group.
2. Grant access to the file manager in the user group.
3. Add a file mount to the user group.
4. Leave the standard **File operation permission** (i.e. the first 3).
5. Do _not_ grant any `tl_files` field permissions.

**Comment by leofeyer** [comment]
Confirmed. And Contao 4.13 should behave the same, because we don‘t check `USER_CAN_EDIT_FIELDS_OF_TABLE` there, either:

https://github.com/contao/contao/blob/8c417810f32236f68a3b9ee618d2842ae86c19cf/core-bundle/src/Resources/contao/dca/tl_files.php#L690-L693

Unfortunately, there is no voter for `tl_files` yet. @aschempp /cc

**Comment by leofeyer** [comment]
As discussed in the Contao call, @aschempp is working on the necessary voters.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7175
