### ISSUE TITLE
Contao 4.4: content jumps left/right depending on vertical scroll

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#704]
If you have enabled the option `limitWidth` for the back-end theme, the `#container` will jump left and right in operating systems or browsers with fixed scrollbars, when you navigate between a page that requires vertical scrolling and one that does not.

This could be fixed by
```css
body {
    overflow-y:scroll;
}
```
(also happens in Contao 3 and presumably Contao 4.3)

**Comment by leofeyer** [comment]
Eventually added in c169750a23e3fb5cf1cbe19143740e11be5b8a6e.

**Comment by fritzmg** [comment]
😎
