### ISSUE TITLE
Icons of sortable tables are no longer displayed

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#7040]
### Affected version(s)

5.3.1

### Description

If the option "Sortable table" is activated for a table, under Contao 4.13 an icon is automatically placed in the table header to indicate the sortability.

The icon is still present in the CSS. However, it is no longer displayed because the "sortable" class is no longer added.

![screen-20240321_xNc5QKjn](https://github.com/contao/contao/assets/23719181/adf73ce2-9f22-4ebb-a167-ee53394e9d28)

**Comment by zoglo** [comment]
I can confirm this but the tablesort plugin has been changed (mootools is not being used anymore)
* https://github.com/contao-components/tristen-tablesort

The CSS is not shipped with it.

You should be able to use these styles though:
* https://github.com/tristen/tablesort/blob/380e63d6333695fcced674a2ba808b9e88b67681/tablesort.css
* https://tristen.ca/tablesort/demo/

**Comment by contaoacademy** [comment]
Many thanks for the information. With the additional CSS it works again.

IMO the CSS should be added to Contao so that it works out of the box as before.
