### ISSUE TITLE
"Save URL as favorite" doesn't work anymore

### ISSUE THREAD

**Issue by V15** [contao/contao#7043]
### Affected version(s)

5.3.2

### Description

I just installed a new Contao 5.3.2 with the official demo and wanted to add a favorite.
The page reloads but nothing happens.

The demo version from contao.org is not up to date yet - therefore no test possible there...

**Comment by fritzmg** [comment]
I can confirm the issue.

**Comment by leofeyer** [comment]
Fixed in 4f39db3ce911adbcce8c835b316d42497f2d1ebe.
