### ISSUE TITLE
Cannot create website root

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#7047]
### Affected version(s)

5.3.2

### Description

In `5.3.2`/`5.3.x` website roots cannot be created currently, if no root nodes are already present. After clicking "New", only the "Clear clipboard" button appears. The tree view is missing its fixed "Site structure" root node entirely.

![Screen Shot 2024-03-21 at 23 40 03](https://github.com/contao/contao/assets/4970961/5aebb30c-6e1d-495a-969e-6fd5e0bf8213)

**Comment by fritzmg** [comment]
The regression is caused by https://github.com/contao/contao/commit/f3d144421de23d4876d14da57debdb14d6edc9fc

Reverting that commit fixes both this issue and #7043

**Comment by leofeyer** [comment]
Reverted in 4f39db3ce911adbcce8c835b316d42497f2d1ebe.

**Comment by aschempp** [comment]
https://github.com/contao/contao/pull/7055 fixes the original bug
