### ISSUE TITLE
Request Token Empty

### ISSUE THREAD

**Issue by stefanheimes** [contao/contao#7051]
### Affected version(s)

=>4.13.37

### Description

Since the version of Contao 4.13.37, the request token is missing in formulas in the frontend. The Request Token will be output in the templates, but will be removed from the HTML before it will be sent to the browser. There are no Cookie send back to the browser as well, no PHP-Session Cookie and no CSRF-Cookie. 

I have built a test on the contao demo. I have created a new page with only the password forgotten module. If I open this page without any cookies in my FF or Chrome, for the first time, the token is missing. 

Contao Demo:
![image](https://github.com/contao/contao/assets/988286/67ea2327-c119-4657-85ac-840de53dcb47)

In my installation, this will result in an exception 'cause the request token is missing in the POST. 

Test cases with missing tokens:
- Customer installation Contao 4.13.37
  - With a Contao 4.13.36 everything works  
- New blank installation with Contao Demo Theme, 4.13.39
- Contao Demo 5.3.1

When I open the Contao-Backend-Login, the token will be set, as well as the two cookies, for the PHP-Session and the CSRF one. After I have these two Cookies, everything works.

**Comment by ausi** [comment]
> In my installation, this will result in an exception 'cause the request token is missing in the POST.

This should not happen if your POST request does not contain any cookies. Can you show the request headers of your POST request?

**Comment by fritzmg** [comment]
To be clear: the request token being empty is not a bug. There will only be a request token, if a request token is actually required.

**Comment by stefanheimes** [comment]
@ausi My POST didn't contain a request token, 'cause in the HTML the request token isn't set in the hidden input. I have debugged the templates from the modules password-forgotten and found out, that the request token was there at that moment, but was removed afterward before the whole HTML was sent to the browser. 

@fritzmg Question: Did the password forgotten module need a request token? Or other: If I have a Session ID Cookie and a CSRF Cookie, 'cause I was on the Backend-Login page, why did I get a token on the test page afterwards?

**Comment by fritzmg** [comment]
> @fritzmg Question: Did the password forgotten module need a request token?

It does not depend on the module. Broadly speaking - a request token will only be set, if you have a PHP session.

> why did I get a token on the test page afterwards?

Because a session was probably started during this request.

**Comment by stefanheimes** [comment]
@fritzmg I have tested it on the offical Contao demo, so that I could be free from extensions and custom code. The offical Cotnao Demo didn't start the session, too. So something can't be right, can it?

**Comment by fritzmg** [comment]
> So something can't be right, can it?

What do you mean? Was there an issue in the demo?

**Comment by stefanheimes** [comment]
@fritzmg Create a new site on the demo, add there the password forgotten module. Then go to this page without any Cookies, then the request token isn't set in the hidden input field. On the first call of the Page, the page response as it should minus the request token in the HTML and without the information in the response to set cookies, so no PHP Session Cookie is set or CSRF Token is set.

**Comment by stefanheimes** [comment]
I see that the CSRF Toke was set, 'cause I had made a `die` in the template, I see that the session handler from Symfony was triggered with a Create and a Save 'cause I set some dumps. But the Token will be removed by the system and there were no Cookies send back to the Browser on the first Page visit, even after I refreshed the page several times, there were no Cookies.

**Comment by ausi** [comment]
Can you show the request headers of your POST request that caused the request token missing error?

**Comment by fritzmg** [comment]
> @fritzmg Create a new site on the demo, add there the password forgotten module. Then go to this page without any Cookies, then the request token isn't set in the hidden input field. On the first call of the Page, the page response as it should minus the request token in the HTML and without the information in the response to set cookies, so no PHP Session Cookie is set or CSRF Token is set.

As already mentioned, it is normal that no request token is present.

**Comment by stefanheimes** [comment]
@fritzmg Okay then I have to change the Ticket from no CSRF Token to, User Session didn't start.

**Comment by fritzmg** [comment]
I am not sure what you mean - why do you want a session to be started?

**Comment by stefanheimes** [comment]
@ausi @fritzmg Maybe let's start from the other site: I have a Contao 4.13.36 in the module for the forgotten password, the request token will be always there, with the update to 37 the request token is missing, and I will end in an error. The POST Body looks so: 

![image](https://github.com/contao/contao/assets/988286/a9fcad31-0162-4aff-b312-1b08ee018b24)

If the request token isn't needed, all the time, like @fritzmg try to explain me, than is something other missing?

**Comment by ausi** [comment]
Can you show the request headers of your POST request that causes the request token missing error?

**Comment by stefanheimes** [comment]
@ausi Sorry, yes of course: 

Headers;
![image](https://github.com/contao/contao/assets/988286/48dccccb-4d14-4540-ae9b-939152d7778c)

Post Data: 
![image](https://github.com/contao/contao/assets/988286/1aef3466-b5d5-49ed-9330-8e593fa14948)

**Comment by ausi** [comment]
Can you debug what this method returns here? https://github.com/contao/contao/blob/8c417810f32236f68a3b9ee618d2842ae86c19cf/core-bundle/src/Csrf/ContaoCsrfTokenManager.php#L99-L108

It should return `true` but it looks like it returns `false`

**Comment by ausi** [comment]
Please also dump the output of `$request->hasSession()` and `$request->getSession()->isStarted()` there.

**Comment by stefanheimes** [comment]
@ausi here are the results: 

![image](https://github.com/contao/contao/assets/988286/9f68473b-a85d-4b2c-9e70-891f48d66171)

**Comment by ausi** [comment]
OK. So even even though your request does not send a session cookie there is already a session started when the `RequestTokenListener` does its check.
We need to find out what is starting the session here.

**Comment by fritzmg** [comment]
@stefanheimes this is not an issue that occurs in a vanilla installation, correct? There have been reports in the community where the request token error occurs in setups where some consent overlay solutions send an AJAX request to the Contao front end that internally starts a session (albeit without really using it - hence no CSRF token cookie is actually set).

This should be fixed in the extension causing the session to be started. 

However, within Contao we should also apply the changes done in https://github.com/contao/contao/pull/6801 and https://github.com/contao/contao/pull/6959 to the `ContaoCsrfTokenManager`. This will likely alleviate the issue.

**Comment by ausi** [comment]
> However, within Contao we should also apply the changes done in #6801 and #6959 to the `ContaoCsrfTokenManager`. This will likely alleviate the issue.

To validate that, @stefanheimes can you please also dump the value of `$request->getSession()->isEmpty()`

**Comment by stefanheimes** [comment]
I have tested it again in a blank Contao 4.13 and the offical Contao Demo. 
I didn't get the "request token missing" error there. But I'm more confused now than before. 

If I have a Form without a spam protection and the problem from above, that the request token isn't set, which I can reproduce on the offical contao demo. Why is it possible to submit forms without Cookies, spam protection (captcha form field) and the missing token. I though all the time, the token should prevent direct submits from bots. But at the moment it seems to be possible to submit forms directly via POST calls without any issues. I'm happy if someone could check this or explain it to me. 

In the Customer Installation I will run into the request Token issue, we use the password forgotten, without spam protection. Request Tokens, aren't deactivated via Contao configuration. If I test it on a clean 4.13. Contao, on a Form without spam protection e.g. captcha form field, the action token is still missing, but I can submit the form without a problem. 

I don't know if this all comes from the same problem or if I just have some wrong tests or if I misunderstand the functions. 

I will take a look again in the customer installation and check if there is another call which triggers the session to start. 

@ausi @fritzmg Thanks for the input and help. 

@ausi here the dump again, session is empty and it is started. 
![image](https://github.com/contao/contao/assets/988286/58e11dbb-fc13-4552-884f-367aa0e53223)

**Comment by stefanheimes** [comment]
@ausi @fritzmg To summary all and hopefuly to resolve my misunderstanding: The request token isn't needed, if you are not authenticated or if you not have an active session, 'cause than all forms are safe to be submitted 'cause everyone could submit this form. So if we have an active session, which will not create a PHP-Session Cookie and the csrf Cookie, contao will run into this problem 'cause the session is stared, but the cookies are missing. 

As such the problem is not that the request token in the HTML is missing, 'cause it is not needed, the problem is the session which didn't create a cookie but was started.

So simple solution, find the one thing, which starts the session and fix it or write some data into the session so that the cookie will be created or else we will have this problem. 

Sorry, it took a while to arrange all the puzzles correctly.

**Comment by ausi** [comment]
> Sorry, it took a while to arrange all the puzzles correctly.

Not a problem! The CSRF token logic is sometimes hard to grasp, for ourselfes too ☺️

> So simple solution, find the one thing, which starts the session and fix it…

Yes, but we can and should also fix it in Contao itself. We just need to add a check for the `->isEmpty()` case. I will provide a pull request for it.

**Comment by ausi** [comment]
See #7052

**Comment by stefanheimes** [comment]
@ausi Looks good for me, thanks

![image](https://github.com/contao/contao/assets/988286/1971f513-6d56-4c3f-826d-70d36aa35bce)
