### ISSUE TITLE
PreviewFactory#createPreviewFigureBuilder produces a warning for non-existing paths

### ISSUE THREAD

**Issue by m-vo** [contao/contao#7053]
### Affected version(s)

4.13, 5.3

### Description

Consider the following code:

```php
$figure = $this->previewFactory
    ->createPreviewFigureBuilder($path, '_preview')
    ->buildIfResourceExists()
;
```

If `path` does not point to a valid resource (anymore), the call to `createPreviewFigureBuilder` will produce a warning:

    Warning: filemtime(): stat failed for […]

This makes the API a bit cumbersome to use, because now you'll first need to check if a file exists before you can make calls to the factory. Can we improve this? In the above example, it would be nice, if the result would just be null like when using the `FigureBuilder` directly.

/cc @ausi

**Comment by leofeyer** [comment]
Where is the `filemtime()` call executed?

**Comment by m-vo** [comment]
Inside  `PreviewFactory#createCachePath()` IIRC.
