### ISSUE TITLE
add js_accordion will render wrong body id

### ISSUE THREAD

**Issue by berecont** [contao/contao#7058]
### Affected version(s)

5.3

### Description

Contao 5.3.3 local installation Laragon
you can also reproduce at online demo

Page layout: add` js_accordion` at `JavaScript-Templates` and save
Frontend will render `<body id="handorgel1">`

Page layout: without adding` js_accordion`
Frontend will render `<body id="top">`

Add a content element Handorgel, without adding `js_accordion`
Frontend will render `<body id="top">`

remark: there's no hint, that it is no longer necessary to check ` js_accordion` for legacy elements and do-not-check for Handorgel

**Comment by berecont** [comment]
additional info:
Sourcecode: `<body id="top">` 
DOM: `<body id="handorgel1">`
totop-link is not affected by this

in case, this doesn't matter: issue can be closed

**Comment by fritzmg** [comment]
It looks like, since we are initialising `handorgel` on the `document.body`:

https://github.com/contao/contao/blob/110d32fd52f5abfb58a07d15813d09dda7292e8e/core-bundle/contao/templates/js/js_accordion.html5#L30
the Handorgel JavaScript will replace that element's ID (or at least the verison in `contao-components/handorgel`).

**Comment by zoglo** [comment]
> there's no hint, that it is no longer necessary to check  js_accordion for legacy elements and do-not-check for Handorgel

You still have to check the new `js_accordion.html5` for the legacy elements if you want to use the new handorgel.js with them

**Comment by leofeyer** [comment]
@zoglo Does #7074 fix this issue?

**Comment by fritzmg** [comment]
Yep - we can close this.
