### ISSUE TITLE
Administrators can't edit their own user

### ISSUE THREAD

**Issue by de-es** [contao/contao#7059]
### Affected version(s)

5.3.3

### Description

Administratoren können ihren eigenen Datensatz nicht bearbeiten/speichern, wenn sie ihn über Account-Manager -> Users -> Edit bearbeiten wollen:

`Not enough permissions to update [Subject: Source: tl_user; ID: 1].`

Über das Profil funktioniert es natürlich weiterhin.

Zum Nachvollziehen: [Kevin Jones in der Demo öffnen](https://demo.contao.org/contao?do=user&act=edit&id=1)  und zB auf `Save` gehen.

Bug oder known limitation?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7064
