### ISSUE TITLE
Missing CSS for .media--below in the legacy Framework

### ISSUE THREAD

**Issue by stefansl** [contao/contao#7061]
### Affected version(s)

5.*

### Description

Since version 5.0.0 Contao switched to twig templates and the order of the markup in the template text.html.twig doesn't change anymore if you choose the position of the media to below. It's meant to order it by CSS now and that's fine for me.
As long as the classes .media--left and .media--right can be still found in the /assets/contao/layout.css .media--below should be there, too.
F.e. like this:
```
.media--below {
    display: flex;
    flex-direction: column;
}
.media--below .rte {
    order: 2;
}
.media--below figure {
    order: 3;
}
```

**Comment by leofeyer** [comment]
> It's meant to order it by CSS now and that's fine for me.

@m-vo Is that true?

**Comment by contaoacademy** [comment]
Yes, that is correct. `.media--left` and `.media--right` are defined in `layout.css` and `.media--below` is missing.

It would be nice if the missing CSS will be added so it worked out of the box when the layout framework is active.

Also see: https://github.com/contao/contao/pull/5173

**Comment by m-vo** [comment]
> It's meant to order it by CSS now and that's fine for me.

Yes, because the layout should not change semantics. 

~~And by default the text part will always come first content as it is usually the thing with more importance in the text element.~~ Ok, I see we changed that in #5173…

**Comment by mdollde** [comment]
Also see: https://github.com/contao-components/contao/issues/18
:-)

Regards
Mathias

**Comment by leofeyer** [comment]
The suggestion above uses `flex` whereas the suggestion in https://github.com/contao-components/contao/issues/18 uses `grid`. Which one is "correct"?
