### ISSUE TITLE
Upgrade to TinyMCE 7

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#7070]
### Description

https://www.tiny.cloud/docs/tinymce/latest/migration-from-6x/

**Comment by zoglo** [comment]
New change that should be important as well as it's self-hosted within contao (GPLv2+)
https://www.tiny.cloud/docs/tinymce/latest/license-key/

```js
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  license_key: 'gpl'
});
```
