### ISSUE TITLE
Correctly URL-encode contentURL

### ISSUE THREAD

**Issue by ausi** [contao/contao#7084]
### Affected version(s)

5.3

### Description

As discussed in https://github.com/contao/contao/pull/7062#issuecomment-2037131864

**Comment by ausi** [comment]
The news and event templates already use `$figure->getSchemaOrgData()` which correctly encodes the URL, so the issue in #7062 seems to be from a different source. 

@qzminski @Toflar I guess you did not use `$figure->getSchemaOrgData()` in your project?

**Comment by Toflar** [comment]
That's right, fixed ;)
