### ISSUE TITLE
tstamp may not be updated after sorting changed because of cut/copy operation

### ISSUE THREAD

**Issue by ReneLuecking** [contao/contao#7085]
### Affected version(s)

All versions

### Description

First of all I'm not sure if this is really considered a bug or working as intended.

I'm using tl_content as an example but in general all tables with pid and sorting are affected.

When moving content elements from one place to another Contao may update the sorting value of surrounding elements which where not explicitly moved. As an example lets say we have an article with 5 content elements in it:

| id | sorting | tstamp | type |
| - | - | - | - |
| 1 | 64 | 1000000000 | headline |
| 2 | 128 | 1000000000 | text |
| 3 | 129 | 1000000000 | html |
| 4 | 130 | 1000000000 | image |
| 5 | 131 | 1000000000 | text |

Now I want to move the elements with ID 4 and 5 between 2 and 3. To do this I select ID 4 and 5, click "Cut" and then "Paste after" ID 2. This results in the following data:

| id | sorting | tstamp | type |
| - | - | - | - |
| 1 | 64 | 1000000000 | headline |
| 2 | 128 | 1000000000 | text |
| 3 | 134 | 1000000000 | html |
| 4 | 129 | 1234567890 | image |
| 5 | 130 | 1234567890 | text |

ID 4 and 5 have updated sorting values to represent their new position and updated tstamps as I explicitly moved them. ID 3 also has an updated sorting value as it had to move down to make place for ID 4 and 5., BUT ID 3 does NOT have an updated tstamp as it was not moved explicitly.

Depending on the definition you could either say that ID 3 should have a new tstamp, as it has technically changed, but you could also say it should not have a new tstamp as it was not changed by a user.

The reason I even bring this topic up is the following: we have custom code in place to keep two Contao systems in sync. That means if something changes in system 1 it should also get updated in system 2. The tstamp is used to detect and sync any changes, otherwise we would always need to check all database entries for changes, as usually the tstamp gets updated if something changes. Except in this specific case.

I'm really not sure if that is an issue for anyone except me and if it should be changed or not. If it will be changed, as far as I know the following 3 statements in `DC_Table` would need to also update the tstamp:

https://github.com/contao/contao/blob/28c37794bb8ea3e23876a99b4b8eada121f8d3a8/core-bundle/contao/drivers/DC_Table.php#L1389-L1392

https://github.com/contao/contao/blob/28c37794bb8ea3e23876a99b4b8eada121f8d3a8/core-bundle/contao/drivers/DC_Table.php#L1447-L1449

https://github.com/contao/contao/blob/28c37794bb8ea3e23876a99b4b8eada121f8d3a8/core-bundle/contao/drivers/DC_Table.php#L1565-L1567

**Comment by aschempp** [comment]
> First of all I'm not sure if this is really considered a bug or working as intended.

Marking this as up-for-discussion because I'm not sure either 😅

**Comment by ausi** [comment]
As discussed in the call today when only `sorting` is updated, `tstamp` should not get updated as the `sorting` field is not part of the contents of the entry (in an API the `sorting` field would be hidden, as it is an implementation detail). We should change the implementation so that `tstamp` is never updated together with `sorting`.

In order to synchronize two lists of sorted entries, the sorted IDs should be compared, not `tstamp` or `sorting`.
