### ISSUE TITLE
DCA - MemberFEModule

### ISSUE THREAD

**Issue by katgirl** [contao/contao#7090]
### Affected version(s)

4.13.x

### Description

```php
$GLOBALS['TL_DCA']['tl_member']['fields']['memberid'] = [
    'exclude'                 => true,
    'search'                  => true,
    'inputType'               => 'text',
    'eval'                    => array('maxlength'=>255, 'unique'=>true, 'decodeEntities'=>true, 'feEditable'=>false, 'feViewable'=>true, 'feGroup'=>'personal', 'tl_class'=>'w50 clr'),
    'sql'                     => "varchar(11) NOT NULL default ''"
];
```

If I understand documentation correctly, then ```feViewable``` should allow the field to be selected in the personal data module. With ```feEditable``` you can then decide whether the field can be edited by the member.
Unfortunately, with the DCA field selected above, the selection in the Personal Data module is not possible. Only if ```feEditable``` is also set to ```true```.

**Comment by fritzmg** [comment]
`feViewable` is a remnant from Contao 2's `memberlist` module and was never removed. It has no meaning in Contao 3+.

**Comment by fritzmg** [comment]
See #7092
