### ISSUE TITLE
Stop using the `assets` folder

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#7093]
### Description

Our goal is not to use the `assets` folder anymore, because it is "reserved" for the Symfony app. Therefore:

1. Install the Contao components into `public/components`.

2. Move the `assets/{css,images,js}` folders to `public/assets/{css,images,js}`, so the existing paths in CDNs and other caches don‘t change.

Also see #7013.

**Comment by asaage** [comment]
That would result in ```contao/public/public/assets/``` (first public beeing the webroot) and looks really strange 🤔

**Comment by fritzmg** [comment]
@asaage you are misinterpreting the paths. All the paths are relative to the project's directory.
