### ISSUE TITLE
ScriptHandler should use a command

### ISSUE THREAD

**Issue by aschempp** [contao/contao#71]
I think our script handler, which creates the legacy folders, should be available as a Symfony console command. The script handler should then just call the command, like Sensio Distribution Bundle does (https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L418). Otherwise the basic structure can't be manually set up if one's not using the standard-edition.

**Comment by leofeyer** [comment]
Implemented in ccdad7f181b404ecb60ceae029dd07ed6c8ba54d.
