### ISSUE TITLE
Custom navigation not possible for root pages

### ISSUE THREAD

**Issue by akroii** [contao/contao#71]
**Affected version(s)**
4.4,4.6

**Description**  
If I use a custom navigation and select all my root-pages, the frontend navigation is empty.
I wonder why there is a separate [bundle](https://github.com/heimrichhannot/contao-rootnav) for this. Because I am able to check root pages in backend.
![bildschirmfoto 2018-09-19 um 16 52 44](https://user-images.githubusercontent.com/8830861/45761430-8cb42800-bc2c-11e8-983b-c45d0565491b.png)

**How to reproduce**  
1. Create new module -> custom navigation
2. select root-"pages" in navigation settings
3. embed your custom navigation module in frontend

**Comment by xchs** [comment]
See https://github.com/contao/core-bundle/issues/1641
