### ISSUE TITLE
Child records are not copied because of permissions

### ISSUE THREAD

**Issue by Toflar** [contao/contao#7101]
### Affected version(s)

5.3.*

### Description

I could reproduce the problem with forms not having any form fields copied but it's probably also affecting other areas of Contao.

How to reproduce in the Contao Demo:

1. Edit the user group `Editors` as follows:
    a.  Give the users access to the `Forms`
    b. Allow them the form `Search`
    c. Give them the permission to create forms
    d. Add all fields of `tl_form` and `tl_form_field` to the list of fields allowed to edit
2. Switch to the user `j.wilson`
3. Duplicate the form `Search`
4. Save
5. This new form won't have any form fields copied 🐞 

The reason for this is that the newly created form is only added to the permissions in the `oncopy_callback` of `tl_form`. However, [this callback is executed **after** Contao checked for permissions](https://github.com/contao/contao/blob/5.3/core-bundle/contao/drivers/DC_Table.php#L1053-L1070). Which means that when Contao checks for [`CreateAction` in `copyChildren()`](https://github.com/contao/contao/blob/5.3/core-bundle/contao/drivers/DC_Table.php#L1221), the newly created form is not part of the permissions yet.

No idea how to fix that 🤯

**Comment by leofeyer** [comment]
@aschempp Do you have an idea or should I add the "up for discussion" label?
