### ISSUE TITLE
Fatal error: Attribute "SensitiveParameter" cannot target property

### ISSUE THREAD

**Issue by akroii** [contao/contao#7108]
### Affected version(s)

5.3.4

### Description

Hello there,
i've tried to install newest C 5.3.4 local on my ddev machine. After the installation process it appears the error message:
![image](https://github.com/contao/contao/assets/8830861/ffca84c2-3fd7-4515-9347-a27e7ee600e7)

```
$ /usr/bin/php8.2 -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -ddisplay_startup_errors=0 -derror_reporting=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=UTC /var/www/html/public/contao-manager.phar.php composer install --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating optimized autoload files
contao/manager-plugin: Dumping generated plugins file...
contao/manager-plugin: ...done dumping generated plugins file
Class Contao\ManagerPlugin\PluginLoader located in ./vendor/contao/manager-plugin/src/Resources/PluginLoader.php does not comply with psr-4 autoloading standard. Skipping.
112 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php vendor/bin/contao-setup
Fatal error: Attribute "SensitiveParameter" cannot target property (allowed targets: parameter) in /var/www/html/vendor/contao/core-bundle/src/EventListener/InsecureInstallationListener.php on line 25
PHP Fatal error:  Attribute "SensitiveParameter" cannot target property (allowed targets: parameter) in /var/www/html/vendor/contao/core-bundle/src/EventListener/InsecureInstallationListener.php on line 25
Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255
# Process terminated with exit code 255
# Result: Unknown error
```
PHP 8.2.5
DDEV version     v1.21.2
architecture     amd64
db               drud/ddev-dbserver-mariadb-10.4:v1.21.2
dba              phpmyadmin:5
ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.2
docker           24.0.2
docker-compose   v2.10.2
docker-platform  docker-desktop
mutagen          0.16.0-rc1
os               linux
router           drud/ddev-router:v1.21.2
web              drud/ddev-webserver:v1.21.2

**Comment by fritzmg** [comment]
Hm, that is odd. This is a PHP bug - but it should have been fixed in PHP 8.2.0+ already: https://github.com/php/php-src/issues/9420

According to your console output (and info) you are using PHP 8.2.5.

Can you please confirm the PHP version by executing:

```
/usr/bin/php8.2 -v
```

And also

```
php -v
```

**Comment by akroii** [comment]
![image](https://github.com/contao/contao/assets/8830861/fe0aa17b-d8f8-4c73-a116-b5335b5332f0)

**Comment by fritzmg** [comment]
8.2.5 is a year old at this point, you could try to update the PHP version to 8.2.17 (or 8.3.x).

**Comment by akroii** [comment]
The problem was that I thought I had 8.2.5, but I was actually using 8.2.0RC. This is because I have to use `ddev php -v` instead of `php -v` to access my PHP version within ddev. Otherwise the PHP version of the WSL system applies.
Btw... Problem is gone in PHP Version 8.3.2-1+0~20240120.16+debian11~1.gbpb43448

**Comment by Toflar** [comment]
Perfect, closing then 😊
