### ISSUE TITLE
Template "@KnpMenu/menu.html.twig" is not defined.

### ISSUE THREAD

**Issue by Luiswagener** [contao/contao#7118]
### Affected version(s)

4.13.40

### Description

When I update my packages via "composer update", the bundle "knplabs/knp-menu-bundle" is updated from version 3.3.0 to 3.4.0. After that, the template "@KnpMenu/menu.html.twig" can no longer be found in the when i want to login into the Contao backend. The version 3.4.0 is commited 30 minutes ago.

**Comment by leofeyer** [comment]
See https://github.com/KnpLabs/KnpMenuBundle/issues/476

**Comment by fritzmg** [comment]
Fixed in `knplabs/knp-menu-bundle` `3.4.1` already.
