### ISSUE TITLE
Can't access backend after upgrade to 4.13.41

### ISSUE THREAD

**Issue by jochi44** [contao/contao#7121]
### Affected version(s)

4.13.41

### Description

After upgrading one of my Contao installations i can not access the backend.
An "internal server error" is shown:

`An exception has been thrown during the rendering of a template ("Call to undefined function Contao\CoreBundle\Twig\Extension\twig_escape_filter_is_safe()").`

**Comment by leofeyer** [comment]
We have just added a conflict for Twig 3.9. Please update the dependencies again.

**Comment by jochi44** [comment]
> We have just added a conflict for Twig 3.9. Please update the dependencies again.

I think the conflict needs to be added for Contao 5.3 as well.

**Comment by minstyle** [comment]
I have the same problem. I can't update from Contao 4.4. (PHP 7.3) to Contao 4.13.41 (PHP 8.2).

**Comment by fritzmg** [comment]
> I have the same problem. I can't update from Contao 4.4. (PHP 7.3) to Contao 4.13.41 (PHP 8.2).

https://github.com/contao/conflicts/pull/61

**Comment by minstyle** [comment]
@fritzmg It doesn't work for me to add `"twig/twig": "3.9.0"` in `conflict` as @zoglo mentioned. The issue still exists and the same error is thrown.

**Comment by fritzmg** [comment]
> @fritzmg It doesn't work for me to add `"twig/twig": "3.9.0"` in `conflict` as @zoglo mentioned. The issue still exists and the same error is thrown.

That's because there exists `twig/twig: 3.9.1` now. See https://github.com/contao/contao/issues/7121#issuecomment-2060799204

**Comment by minstyle** [comment]
After adding `"twig/twig": "2.7.0 || 3.9.0 || 3.9.1"` in composer.json (https://github.com/contao/conflicts/pull/61/commits/cd4fb8047fee39d6e589049f79b335ddf2113f6b) it works. Thank's @fritzmg 👍

**Comment by zoglo** [comment]
@minstyle you should use 
```
"twig/twig": "2.7.0 || 3.9.*"
```

**Comment by minstyle** [comment]
@zoglo OK, `twig/twig v3.8.0` is installed now. (See also https://github.com/contao/conflicts/pull/61/commits/aef5ed9d88dfd37d23808b3807989b2a8f4e830f)

**Comment by fritzmg** [comment]
> After adding `"twig/twig": "2.7.0 || 3.9.0 || 3.9.1"` in composer.json ([contao/conflicts@cd4fb80](https://github.com/contao/conflicts/commit/cd4fb8047fee39d6e589049f79b335ddf2113f6b)) it works. Thank's @fritzmg 👍

You don't need to add `2.7.0`.



> @minstyle you should use
> 
> ```
> "twig/twig": "2.7.0 || 3.9.*"
> ```

Be careful, if you add `3.9.*` yourself, you will need to keep track of https://github.com/contao/contao/pull/7122 and remove it once released.
