### ISSUE TITLE
Composer Logfile shouldn't self-delete after finishing queue

### ISSUE THREAD

**Issue by Nightwing0815** [contao/contao#713]
Version 4.8.x

I think, composer's logfile (= **composer-install.out.log** ) shouldn't self-delete after finishing the queue. So you can have look afterwards, which components gets an update. And it's imho better for copying text out, for example for a forum post, when something went south.

ToM

**Comment by fritzmg** [comment]
@Nightwing0815 this is the wrong repository. This is an issue for the Contao Manager.
