### ISSUE TITLE
Contao 5.3 does not detect SSL connection in reverse proxy setup

### ISSUE THREAD

**Issue by greenertux** [contao/contao#7135]
### Affected version(s)

5.3.6

### Description

I'm running Contao 5.3.6 with the following environment variables:
TRUSTED_PROXIES=192.168.29.2
TRUSTED_HOSTS=mydomain.de

When I open Tools->PHP Information in Contao Manager everything looks fine. I'm seeing the environment variables and I can also see the following HTTP Headers:
HTTP_X_FORWARDED_FOR = my ip
HTTP_X_FORWARDED_HOST = mydomain.de
HTTP_X_FORWARDED_PORT = 443
HTTP_X_FORWARDED_PROTO = https
REMOTE_ADDR = 192.168.29.2

Unfortunately Contao seems not to detect that the request should be treated as HTTPS. It generates http only URLs and when I switch the master page to SSL I get a redirect loop because even if I access via HTTPS it still tries to redirect to the same URL.
As far as I understand, if TRUSTED_PROXIES is set it should respect HTTP_X_FORWARDED_PROTO even if the reverse proxy accesses Contao via HTTP and Port 80, right?
Is there anything I can do to debug this?

**Comment by greenertux** [comment]
Never mind, I thought it was possible to actually use environment variables, but apparently it only works if the .env file is used.

**Comment by fritzmg** [comment]
Using environment variables is fine. Have you confirmed that they were actually passed to your PHP environment for the web process?

**Comment by greenertux** [comment]
> Using environment variables is fine. Have you confirmed that they were actually passed to your PHP environment for the web process?

I thought so too, but when I click on Tools->PHP Information I see it in the environments section. However it only works when I also add it to the .env file.
So it apparently is a bug?

**Comment by fritzmg** [comment]
> I thought so too, but when I click on Tools->PHP Information I see it in the environments section.

Do you mean _Configuration_ ➡️ _View full PHP configuration_ in the Profiler?

**Comment by greenertux** [comment]
> Do you mean _Configuration_ ➡️ _View full PHP configuration_ in the Profiler?

This is what I used in Contao Manager to view the Environment variables
![image](https://github.com/contao/contao/assets/13280348/9d7449db-a66b-4414-8ebf-2d41b2dbd755)

**Comment by fritzmg** [comment]
Well, to be sure you should check within Contao itself again. (Enable the debug mode to access the profiler.)

**Comment by greenertux** [comment]
I have enabled debug mode in Contao Manager, but nothing changes when accessing the front end.
Is the toolbar loaded from domain/_wdt/dbd103? Because that request is blocked because the page is loaded via https and contao tries to load the debug toolbar via http :(
![image](https://github.com/contao/contao/assets/13280348/54d683d1-0fc4-483f-9a81-3d120126709e)

**Comment by fritzmg** [comment]
The debug mode can also be enabled in the back end of Contao. Afterwards you can access the PHP info via `/_profiler/phpinfo`. There you can check whether the `TRUSTED_PROXIES` environment variable was actually passed to the PHP environment.

**Comment by greenertux** [comment]
Thanks - I just verified that the Environment section looks the same as in Contao Manager. The TRUSTED_PROXIES variable is shown, even though it only works in the frontend when I copy the same entry into the .env file.

**Comment by fritzmg** [comment]
> even though it only works in the frontend when I copy the same entry into the .env file.

That is still odd. You could debug whether the correct values are passed here: https://github.com/contao/manager-bundle/blob/13b614acb765f906b91fed03f448e026960876de/src/HttpKernel/ContaoKernel.php#L238

**Comment by greenertux** [comment]
> > even though it only works in the frontend when I copy the same entry into the .env file.
> 
> That is still odd. You could debug whether the correct values are passed here: https://github.com/contao/manager-bundle/blob/13b614acb765f906b91fed03f448e026960876de/src/HttpKernel/ContaoKernel.php#L238
Sorry, but how do I check this? I added `dump();` to after the line you highlighted, but couldn't find anything in the debugger.

I noticed that $_ENV['TRUSTED_PROXIES'] and $_SERVER['TRUSTED_PROXIES'] are only set when I configure TRUSTED_PROXIES via the .env file, not when I define it as environment variable.

**Comment by fritzmg** [comment]
But they do show up in `/_profiler/phpinfo`?

**Comment by greenertux** [comment]
> But they do show up in `/_profiler/phpinfo`?

If I only configure the environment variables $_ENV['TRUSTED_PROXIES'] and $_SERVER['TRUSTED_PROXIES'] don't show up in `/_profiler/phpinfo` 
When I add the same value to .env the values show up correctly in `/_profiler/phpinfo`

**Comment by fritzmg** [comment]
> If I only configure the environment variables $_ENV['TRUSTED_PROXIES'] and $_SERVER['TRUSTED_PROXIES'] don't show up in `/_profiler/phpinfo`

Then it's an issue with your hosting environment. It does not seem to pass your environment variables to the PHP process. This is not related to Contao itself.

**Comment by greenertux** [comment]
> > If I only configure the environment variables $_ENV['TRUSTED_PROXIES'] and $_SERVER['TRUSTED_PROXIES'] don't show up in `/_profiler/phpinfo`
> 
> Then it's an issue with your hosting environment. It does not seem to pass your environment variables to the PHP process. This is not related to Contao itself.

What I don't get is why the environment variables show up perfectly fine in the PHP Info. Doesn't that mean the environment variables are passed to PHP just fine?
![grafik](https://github.com/contao/contao/assets/13280348/f8be9a70-307f-4539-97af-e6be5529f838)

**Comment by fritzmg** [comment]
I am confused. Does `/_profiler/phpinfo` show the respective `$_SERVER` variables or not?

**Comment by greenertux** [comment]
> I am confused. Does `/_profiler/phpinfo` show the respective `$_SERVER` variables or not?

It shows the `$_SERVER` variables only when I have configured it in the .env file.
If I just use environment variables I can see those environment values in the "Environment" section of phpinfo, but not the `$_SERVER` variables.
That makes me believe the environment variables are passed to PHP, but are somehow not processed by Symphony / Contao.

It looks like it's not a general problem with environment variables though, because `MAILER_DSN` is also defined via environment variables and works like it should. No idea why that does not work with the `TRUSTED_PROXIES` variable.

**Comment by fritzmg** [comment]
> That makes me believe the environment variables are passed to PHP, but are somehow not processed by Symphony / Contao.

The `$_SERVER` super globals are set by PHP, not by Contao. Contao/Symfony only writes into `$_SERVER` to populate the `.env` vars (but does not overwrite existing ones by default).

**Comment by greenertux** [comment]
Thanks for you help, if you believe this not to be a Contao issue feel free to close this bug. I am fine with using the .env file to configure TRUSTED_PROXIES.

**Comment by greenertux** [comment]
I am now using SSL for the connection between Traefik and Contao and magically all problems disappeared.
