### ISSUE TITLE
Contao class and sass conflict for video aspect ratios.

### ISSUE THREAD

**Issue by rburch** [contao/contao#7136]
### Affected version(s)

5.3.6

### Description

I'm in Contao 5.3. I'me trying to style videos and I'm hitting a conflict with the aspect ration classes and sass. Contao uses aspect--16:9 as a class, but that is not valid in sass because of the : and therefor throws an error if I try and use that in my css. Contao should probably use something like aspect--16-9 instead.

**Comment by leofeyer** [comment]
You probably have to escape the colon as `\:` to make it work. See https://github.com/contao-components/contao/blob/9.x/css/responsive.css#L75-L78

**Comment by rburch** [comment]
Yes that works. I didn't know css used escapes. I guess in 20+ years some how  I've never needed them. Thanks!
