### ISSUE TITLE
Edit Twig Templates like in SW6

### ISSUE THREAD

**Issue by mstudio-dev** [contao/contao#7141]
### Description

How about if the Twig templates in the backend were displayed in a similar way to Shopware 6? In my opinion that would be functional and clear.
<img width="1109" alt="image" src="https://github.com/contao/contao/assets/10011141/4b52cab6-e99c-4117-a86a-a20ca01f3315">

**Comment by fritzmg** [comment]
Related: https://github.com/contao/contao/issues/7140

**Comment by m-vo** [comment]
#7587 and followup PRs will greatly improve editing Twig templates in the back end.
