### ISSUE TITLE
versionPeriod config should be available in the backend

### ISSUE THREAD

**Issue by FlowinBeatz** [contao/contao#7158]
### Affected version(s)

4.13.x

### Description

According to the [Docs](https://docs.contao.org/manual/de/system/einstellungen/#localconfig) the `versionPeriod` setting should be available in the backend.

**Comment by fritzmg** [comment]
To clarify: the `versionPeriod` localconfig setting currently has no equivalent bundle configuration. Yet it was removed from `TL_SETTINGS` making it an inaccessible, hidden feature currently. We either need to provide a bundle configuration for this setting or re-instate the back end system setting. For Contao 4.13 the latter is probably the only option.

**Comment by leofeyer** [comment]
What’s `versionPeriod`?

**Comment by FlowinBeatz** [comment]
`versionPeriod` is the period an element's version is stored in the database.

**Comment by leofeyer** [comment]
These fields have been removed more than 4 years ago (see #203). But you can still adjust the value in your `localconfig.php` if you want to.

**Comment by FlowinBeatz** [comment]
Question is why it was removed. Can't find it in #203. @fritzmg categorized it as a bug in our Slack conversation. 

As the system settings are getting smaller from version to version it becomes harder to find some useful functions and settings. Can't see the advantages of it for admins.

**Comment by fritzmg** [comment]
> As the system settings are getting smaller from version to version it becomes harder to find some useful functions and settings.

Yes, that is exactly the point. All the other settings have been either moved or removed completely. But the `*Period` settings are now obscured because they are neither visible in the back end settings nor in `config:dump-reference` - even though they are still actively used by Contao.

**Comment by FlowinBeatz** [comment]
Okay. You decide what's the right thing to do from here :-)

**Comment by fritzmg** [comment]
See https://github.com/contao/contao/pull/7160
