### ISSUE TITLE
Eigenem Layoutbereich kann kein Template zugeordnet werden

### ISSUE THREAD

**Issue by hendrikbengs** [contao/contao#716]
Version: ab Contao 4.8.1 (getestet in der Contao Demo)

Die Auswahl eines Templates im Bereich »Eigene Layoutbereiche«, innerhalb der Seitenlayouts, scheint nicht mehr möglich. Der Layoutbereich wird zwar trotzdem angelegt und kann über die eingebundenen Module auch ausgewählt werden. Eine Ausgabe im Frontend findet aber nicht statt, da wohl kein Template zugeordnet wird.

<img width="1021" alt="Bildschirmfoto 2019-09-03 um 15 51 00" src="https://user-images.githubusercontent.com/35339838/64178643-1ec73780-ce62-11e9-9537-95d9912e7993.png">

**Comment by fritzmg** [comment]
Duplicate of #677
