### ISSUE TITLE
Invalides Markup bei Splashscreen

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#7162]
### Affected version(s)

5.3

### Description

In den Elementen in denen ein Splashscreen vorkommt wird seit 5.3 ein Button statt eines Ankers genutzt. Allerdings ist die Meldung des Splashscreens in ein `p` gepackt. Da `button` ein Inline-Element ist haut das so nicht ganz hin. Spräche was dagegen aus dem `p` z.B. ein `span` zu machen?

https://github.com/contao/contao/blob/5.3/core-bundle/contao/templates/twig/content_element/youtube.html.twig#L10
https://github.com/contao/contao/blob/5.3/core-bundle/contao/templates/twig/content_element/vimeo.html.twig#L5

**Comment by leofeyer** [comment]
Do we need a `<span>` at all?

**Comment by m-vo** [comment]
> Do we need a `<span>` at all?

Yes, because then you can position the text relative to the splash screen image (see the `_video.html.twig` base template for context).

IMHO switching to span is the correct solution. @bennyborn Can you make a PR with the changes?

**Comment by bennyborn** [comment]
@m-vo As stated in Slack I'm currently a bit short on time but I can surely provide a PR next week

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7165
