### ISSUE TITLE
The "defer" flag for JS files does not work if combining scripts is enabled

### ISSUE THREAD

**Issue by ReneLuecking** [contao/contao#7166]
### Affected version(s)

5.x

### Description

When using the "defer" flag while combining scripts is enabled, the combined script only gets the "async" attribute, not the "defer" attribute:

https://github.com/contao/contao/blob/d2f96ba790829e4c4234d2e2b7ab03681e69797e/core-bundle/contao/library/Contao/Controller.php#L961-L965

The code in line 965 should instead be:

```php
$strScripts = Template::generateScriptTag($objCombinerDefer->getCombinedFile(), false, false, null, null, null, true) . $strScripts;
``` 

or using PHP 8 named arguments:

```php
$strScripts = Template::generateScriptTag($objCombinerDefer->getCombinedFile(), defer: true) . $strScripts;
``` 

Shall I create a PR with a fix? If so, would you prefer the named arguments variant or the "old school" full list of arguments?

**Comment by leofeyer** [comment]
> Shall I create a PR with a fix?

Yes please.

> If so, would you prefer the named arguments variant or the "old school" full list of arguments?

I prefer the "new" variant, but I‘m fine either way.
