### ISSUE TITLE
PhpSubprocess and messenger:consume, duplicate php executable in command line

### ISSUE THREAD

**Issue by md-netdesign** [contao/contao#7191]
### Affected version(s)

5.3.7

### Description

Hello!

We caught a bug with the [latest adjustments to the ProcessUtil.php](https://github.com/contao/contao/commit/192247be866c2807af05b8ae51ec00f7055b0b4b) by @Toflar. Because of the switch to the mandatory PhpSubprocess Class, the executed command line contains the php executable path twice, which in turn does not execute any command, therefore does not run the `contao:supervise-workers` command and ultimatly does not run any worker via `messenger:consume` from the `contao:cron` command.

If you execute `contao:cron` regularly, the `messenger:consume` commands should also be spawned and run for exactly one minute. This does currently (5.3.7) **not happen**.

---

[Line 60 of ProcessUtil](https://github.com/contao/contao/blob/db87fd8fe50bb162106a29f2a4985c6d7f78da6f/core-bundle/src/Util/ProcessUtil.php#L60) does add the php binary to the command and [Line 56-60 of PhpSubprocess](https://github.com/symfony/process/blob/3839e56b94dd1dbd13235d27504e66baf23faba0/PhpSubprocess.php#L56-L60) does this again. Therefore, the resulting command line is something like:
`/usr/bin/php -n -c <temporary php.ini> /usr/bin/php /srv/www/project-directory/bin/console contao:supervise-workers`

This will interpret the php binary as the main script and thus just output the binary contents of the executable and then returning. The `bin/console` script ist just passed as an cli argument and therefore never executed.

The proposed fix would be:
Changing
https://github.com/contao/contao/blob/db87fd8fe50bb162106a29f2a4985c6d7f78da6f/core-bundle/src/Util/ProcessUtil.php#L60
to
`return new PhpSubprocess([$this->getConsolePath(), $command, ...$commandArguments]);`
This would result in an correct command line:
`/usr/bin/php -n -c <temporary php.ini> /srv/www/project-directory/bin/console contao:supervise-workers`

If you're approving this change, we're happy to provide a pull request.

Thanks for your time.

**Comment by Toflar** [comment]
This was already fixed in https://github.com/contao/contao/pull/7144 afaics.

**Comment by md-netdesign** [comment]
Yes. That will also fix it. Thanks for the info. 😄

**Comment by Toflar** [comment]
A new release is around the corner, so shouldn't be too long before you get the fix 😊
