### ISSUE TITLE
Beim inkludieren von einer Elementgruppe werden die Inhalte nicht angezeigt

### ISSUE THREAD

**Issue by pressi** [contao/contao#7198]
### Affected version(s)

5.3.7

### Description

Hallo,

auch in der Demo getestet.

**Vorgehensweise**
Element erstellen: "Elementgruppe", darin Inhalt einfügen z.B. Text, Bild.

Andere Seite:
Neues Include-Elemente > "Inhaltselement" erstellen, bei "Bezogenes Inhaltselement" die vorher erstellte Elementgruppe zuweisen.

Die Ausgabe im Frontend bleibt leer. Im Code wird nur der Wrapper angezeigt.

LG
pressi

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7241
