### ISSUE TITLE
Root page links in custom navigation

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#72]
This is a follow-up to contao/core-bundle#1641. I think that the changes in 3c92fb923e13678c7d47fe397ca6f398ff596515 are wrong, because now we cannot switch between two root pages if the language is not added to the URL, can we? IMHO it should be:

```php
case 'root':
	// Overwrite the alias to link to the language URL (see #1641)
	if (Config::get('addLanguageToUrl'))
	{
		$objModel->alias = 'index';
	}
```

@Defcon0 @fritzmg @ausi @asaage What do you think?

**Comment by fritzmg** [comment]
The root pages could be on different domains, then it would be valid to have an URL for the root page without its actual alias. So:

#### 1. Root pages with different languages on the same domain with language fragment:

* `https://example.org/en`
* `https://example.org/de`

#### 2. Root pages on different domains:

* `https://example.org`
* `https://example.com`

#### 3. Root pages on the same domain, with different languages but no language fragment:

* `https://example.org/example-site-en.html`
* `https://example.org/example-site-de.html`

However, I can't think of a way how you could be able to distinguish case no. 2 from case no. 3. Also the root pages could have mixed configurations.

**Comment by leofeyer** [comment]
> However, can't think of a way how you could be able to distinguish case no. 2 from case no. 3

If the page has an URL configured and this URL differs from the current host, it is case 2. All other cases are no. 3. Do you agree?

**Comment by fritzmg** [comment]
What if you have 3 website roots:

1. example.org, en
2. loremipsum.com, en
3. loremipsum.com, de

If you are on `example.org` in the front end, the domains of 2. and 3. will be different - however, they need to be handled like in case no. 3.

**Comment by leofeyer** [comment]
You are right. I guess we can only offer the "redirect to the empty URL" feature if `addLanguageToUrl` is enabled then.

**Comment by fritzmg** [comment]
I dislike that though, since I consider case no. 3 to be an edge case. If I have a simple multidomain setup like `example.de` and `example.com`, I'd want the URLs of the root pages of my custom navigation to be

* `https://example.de`
* `https://example.com`

And not

* `https://example.de/some-website-de.html`
* `https://example.com/some-website-en.html`

**Comment by leofeyer** [comment]
Let's discuss this in the next Mumble call.

**Comment by fritzmg** [comment]
I won't have time next week, I hope someone else agrees with me 😁

**Comment by asaage** [comment]
I think that's somehow related to https://github.com/contao/core-bundle/issues/1051 and case no. 3 is not an edge case at all.
In addition to that i think you can never switch between two root pages if the language is not added to the URL and you use the same domains. Thats why i in this case use the 'index' alias only in the fallback-language-Tree and rely on the ```findFirstPublishedRegularByPid``` for the other Trees.

**Comment by fritzmg** [comment]
> In addition to that i think you can never switch between two root pages if the language is not added to the URL

You can, see case no. 3. Those URLs would be generated for root pages without the recent changes.

**Comment by asaage** [comment]
```php
case 'root':
  $href= \PageModel::findFirstPublishedRegularByPid($objModel->id)->getFrontendUrl();
```

Untested... 

- this leads to ```$href=""``` for the current root - i am not shure if or where this would be adjusted to ```"./"``` 
- fails without published regular page in rootpage

**Comment by leofeyer** [comment]
@fritzmg We still have no solution for this one, have we?

**Comment by fritzmg** [comment]
Hm, how about:
```php
case 'root':
    // Overwrite the alias to link to the language URL (see #1641)
    if (Config::get('addLanguageToUrl') || PageModel::countBy(["dns = ?", "type = 'root'"], [$objModel->dns]) <= 1)
    {
        $objModel->alias = 'index';
    }
```
I think this (crude) solution would actually cover all 3 aforementioned cases, wouldn't it?

* If the language is added to the URL, we can omit the alias.
* If there is only one website root for a domain (or no specific one), we can omit the alias.
* If there is actually two or more website roots for a domain, we cannot omit the alias.

**Comment by leofeyer** [comment]
I think this could work. 👍 Thank you.

**Comment by leofeyer** [comment]
This feature does not really work I'm afraid.

* English (alias `english`)
  * Home (alias `index`)
* Deutsch (alias `deutsch`)
  * Startseite (alias `startseite`)

The module generates the following links:

* `http://localhost/english.html`
* `http://localhost/deutsch.html`

However, when I click on `http://localhost/english.html`, the following happens:

* `FrontendIndex::renderPage()` recognizes in line 223 that it is a root page and executes `PageRoot::generate()`.
* `PageRoot::getRedirectUrl()` executes `PageModel::findFirstPublishedByPid()` and returns the first regular page.
* Since the regular page has the alias `index`, `PageModel::getFrontendUrl()` generates the following URL: `http://localhost`
* After being redirected to `http://localhost`, Contao recognizes that my browser language is German, so it redirects me back to `http://localhost/deutsch.html`. 🤦‍♂️ 

To solve this, we should only allow to select root pages in the custom navigation module if the language is added to the URL.

**Comment by leofeyer** [comment]
Fixed in 0fbe25d770c84aa08deed18d9797919e02171fd5.

**Comment by ausi** [comment]
> To solve this, we should only allow to select root pages in the custom navigation module if the language is added to the URL.

I’m not sure if this is the correct fix. Wouldn’t the setup you described be broken anyways? (regardless of a custom navigation modules)

**Comment by leofeyer** [comment]
Probably yes.

**Comment by fritzmg** [comment]
May be we should revert https://github.com/contao/contao/commit/0fbe25d770c84aa08deed18d9797919e02171fd5 ? As @ausi said, the issue that https://github.com/contao/contao/commit/0fbe25d770c84aa08deed18d9797919e02171fd5 tries to solve would be present anyway and is not related to the custom navigation module. Having such a setup is simply a wrong configuration.
