### ISSUE TITLE
ce_youtube iframe ohne title

### ISSUE THREAD

**Issue by bekanntmacher** [contao/contao#720]
Mir ist aufgefallen, dass das Video-Element kein `title` Attribut setzt.

Es wäre super, wenn ein separates Feld geschaffen werden könnte. Die Übernahme der Bildunterschrift für das title-Attribut könnte auch eine Lösung sein.

https://www.w3.org/TR/WCAG20-TECHS/H64.html

**Comment by leofeyer** [comment]
Würden die Browser das überhaupt anzeigen?

**Comment by fritzmg** [comment]
Browser nicht, aber screen reader etc. Es geht ja grundsätzlich um die semantische Ausweisung des Inhalts des iframes (egal ob ein Browser das einzeigen würde oder nicht).

**Comment by leofeyer** [comment]
Also geht es nur um Screenreader? Dann müssten wir dasselbe beim `<audio>`-Tag ebenfalls tun, oder?

**Comment by fritzmg** [comment]
Ich denke das würde Sinn machen, ja.

**Comment by zoglo** [comment]
See: #7572
