### ISSUE TITLE
JS-evaluation in ajax-enabled forms

### ISSUE THREAD

**Issue by asaage** [contao/contao#7203]
### Affected version(s)

5.3.7

### Description

When a form is ajax enabled, script-tags are not loaded and executed (exept in the initial page-load).
Not sure, if that is by design, a known limitation or just a missing ```eval();``` somewhere.
It occured first to me in a mp_form but the problem seems to be in the xhr-handler.
Such a script-tag exists especially in the [captcha-field/widget](https://github.com/contao/contao/blob/5.x/core-bundle/contao/templates/forms/form_captcha.html5#L25) (maybe others too).
To recreate: make a form, enable ajax, add an email-field, a captcha-field and a submit. In the FE force a validation error by submitting example@foo (mailaddress without tld). As a result the form will return with the usual errormessage but the captcha-field will be visible and not hidden as usual.

related:
- https://community.contao.org/de/showthread.php?86809-mp_forms-mit-captcha
- https://github.com/terminal42/contao-mp_forms/issues/82

**Comment by fritzmg** [comment]
I can confirm the issue.

**Comment by ausi** [comment]
To fix this we should IMO not evaluate the `<script>`s of the ajax response, but instead add an `ajax-form-onload` event listener to the captcha script.

**Comment by fritzmg** [comment]
Or may be implement it as a mutation observer instead?

**Comment by asaage** [comment]
> ... add ... event listener to the captcha script.

I would prefer if a solution does not depend on a special widget.
If you add js to other widgets (like for example displaying the value of a range-slider) you would face the same problem again.

**Comment by fritzmg** [comment]
@asaage The solution will be done within the captcha widget's JavaScript. And any other widget of course needs to implement their JavaScript in a way that is independent from whether the form is submitted via AJAX or not (and that has always been the case).

**Comment by asaage** [comment]
i figure, that would probably not solve the original issue i had in mp_forms and complicate enhancing formfield templates with js unneccessary 🤷‍♂️

**Comment by fritzmg** [comment]
> that would probably not solve the original issue i had in mp_form

May be ask on the Contao Community Forum or Community Slack for help regarding that issue.

>  and complicate enhancing formfield templates with js unneccessary 🤷‍♂️

I am not sure what you mean here. May be also ask on the Contao Community Forum or Community Slack for advice on how to handle forms that are submitted via AJAX properly (this is a general topic unrelated to Contao itself).

**Comment by asaage** [comment]
> I am not sure what you mean here.

The simplest (nonsense)example i can think of would be
https://github.com/contao/contao/blob/5.x/core-bundle/contao/templates/forms/form_text.html5#L17 replacing
```diff
--- <p class="error"><?= $this->getErrorAsString() ?></p>
+++ <script>alert("<?= $this->getErrorAsString() ?>");</script>
```
Which currently would not work in AJAX-form and will not if just the captcha widget is fixed.

I would probably try fixing it somewhere around here: https://github.com/contao/contao/blob/5.x/core-bundle/contao/templates/forms/form_wrapper.html5#L28

Since Contao now comes with the ability to create AJAX forms i dont' think it's really "unrelated" to Contao itself.
Anyhow, i might not see the whole picture and understand why eval would/could be bad - I can still work around it with a regular (non-ajax) form and keep track of my current scroll-position on-submit which is just a bit jerky.

**Comment by fritzmg** [comment]
@zoglo not sure what is so funny about this reply?

@asaage as already mentioned, you will always need to implement your JavaScript in an agnostic way. The way you want to implement it would also not work if you used other libraries that provide AJAX form submit functionalities like terminal42/contao-ajaxform or Turbo.

**Comment by ausi** [comment]
> Anyhow, i might not see the whole picture and understand why eval would/could be bad…

- It would for example not work if you have CSP enabled. (Which will affect more and more websites in the future)
- There is also a huge number of edge cases that would not work using `eval()`. 
  (like `document.currentScript`, `document.write()`, domready events,…)
- Implementing the individual scripts themselves using events or an observer is the correct way that would then also make them work in other dynamic contexts.

**Comment by zoglo** [comment]
> @zoglo not sure what is so funny about this reply?

@fritzmg I just agree 100% with you

**Comment by m-vo** [comment]
Maybe https://developer.mozilla.org/en-US/docs/Web/API/Range/createContextualFragment can be utilized to stream the AJAX results into the existing DOM. They should get passed to the parser then (and thus scripts executed). But not sure if this actually works...

**Comment by ausi** [comment]
> Maybe [developer.mozilla.org/en-US/docs/Web/API/Range/createContextualFragment](https://developer.mozilla.org/en-US/docs/Web/API/Range/createContextualFragment) can be utilized

`createContextualFragment` would work for getting the scripts executed, but the issues outlined in https://github.com/contao/contao/issues/7203#issuecomment-2137344311 would remain (except the one with `document.currentScript`).

But as both solutions can coexist I think using `createContextualFragment` is the right way forward.
