### ISSUE TITLE
Problems with event reader in combination with newslist

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#7210]
### Affected version(s)

5.3.8

### Description

I am currently not sure whether this is simply a known limitation or a bug that can be corrected.

The following configuration is required:
- Create a page with an event list
- One page for the details with event reader
- A news list in the footer of the page. Or simply directly below the event reader on the event details page. In the Newslist module, configure the option "Automatically switch to the newsreader if an item has been selected.".

Now open the event list and click on an event. A 404 error occurs here. The event is not displayed.

It appears that an attempt is being made to redirect to the newsreader. The newsreader cannot distinguish between news and event. I have no idea whether this can be solved technically or whether this configuration is simply not allowed.

**Comment by fritzmg** [comment]
You likely accidentally configured a reader module in your news list module.

**Comment by contaoacademy** [comment]
Yes, that was a mistake / configuration error. The question is simply whether something like this can be technically prevented. If not, then the ticket can be closed.

**Comment by fritzmg** [comment]
The module cannot know that, no. If you enable this option in the list module, the module is automatically replaced with the selected reader module if an `auto_item` is present in the URL.

**Comment by contaoacademy** [comment]
I am closing the ticket as this is a misconfiguration.
