### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Toflar** [contao/contao#722]
ToDo's:

- [x] Raise all Symfony requirements to `4.4.*` once they are released (Nov 2019)
- [x] Raise `toflar/psr6-symfony-http-cache-store` to `^2.1` to support `BinaryFileResponse`s (`/favicon.ico` endpoint)
- [x] Replace `league/uri`. It's not recommended to use this package anymore (https://uri.thephpleague.com/uri/5.0/). It contains way too many things. Escargot uses `nyholm/psr7` already because it's much more lightweight. We might need some parts from `league` though e.g. to do query parameter handling which is not part of PSR-7. But for those we should use the specific packages (in that case `league/uri-components` I think).

**Comment by leofeyer** [comment]
All done. 🎉
