### ISSUE TITLE
`Input::get()` no longer works to retrieve passed parameters in the `{{file::*}}` insert tag

### ISSUE THREAD

**Issue by doishub** [contao/contao#7220]
### Affected version(s)

5.x

### Description

Since the input class in Contao 5 listens to the `request-stack`, the retrieval via `Input:get` no longer works in own files, which are passed via the `{{file::data.php?field=myField}}`.

Instead of `Input::get('field')`, `$_GET['field']` must now be used.

**Comment by ausi** [comment]
We probably need to duplicate and add the request to the stack in https://github.com/contao/contao/blob/58352cf86a41e267032d1c4fb8e0671ae1d70bbd/core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php#L637

**Comment by ausi** [comment]
Should get fixed by #7287

But please be aware that this usage of the `{{file::*}}` insert tag is deprecated: _“Using the file insert tag to include templates has been deprecated and will no longer work in Contao 6. Use the "Template" content element instead.”_
