### ISSUE TITLE
Should we maybe change the icon link in the page list view?

### ISSUE THREAD

**Issue by Toflar** [contao/contao#723]
**Affected version(s)**

4.8

**Description** 

I am talking about the following links:
![screenshot](https://user-images.githubusercontent.com/481937/64346338-3b927500-cff2-11e9-8b93-c3b176e5a26a.png)

These are currently pointing to the absolute URL of the respective pages (so e.g. it redirects to `https://example.com/about-contao.html`.
Before Contao 4.8, it didn't really matter because if you had FE preview enabled, you were working in the preview mode right away and if not, then not.
However, with Contao 4.8 we now have a `preview.php` route to circument the cache and so at the moment, you have no way to access the FE preview of a certain page from the list view right away anymore. You need to edit the page and then click on "front end preview" in the top bar.

I think we should change this behaviour to always link to the preview URL (`https://example.com/preview.php/about-contao.html`). I think when you're working in the back end you most likely want to have the preview mode to be available.

**Comment by leofeyer** [comment]
Agreed. 👍

**Comment by Toflar** [comment]
Especially when you have an unpublished page in the back end. You can click on the icon and you get a 404 page even if you activated `show unpublished items` before (in a different tab for example).

**Comment by leofeyer** [comment]
Changed in 33524e26a3242c31e2005c96cc6f4bed90c08cd8.
