### ISSUE TITLE
Tag <br> in Detailansicht

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#724]
In dem Overlay "Details ... anzeigen" (blaues Icon) werden bei machen Feldern `<br>` Tags als Text angezeigt.

Beispielsweise in der Seitenstruktur beim Feld Zugriffsrechte: `u1<br>u2<br>u3<br>u4<br>u5<br>u6<br>g4<br>g5<br>g6`

**Comment by leofeyer** [comment]
Kann ich nicht bestätigen:

<img width="527" alt="" src="https://user-images.githubusercontent.com/1192057/65425898-61e84b00-de0f-11e9-9e9d-0787ae0f0722.png">

**Comment by Mynyx** [comment]
Screenshot aus 4.4.43:
![image](https://user-images.githubusercontent.com/1632642/65437306-daf19d80-de23-11e9-90f5-d6c1a7ab0b28.png)

**Comment by leofeyer** [comment]
Behoben in b641146d423debb041ad94037bf03a8ea89fd082.
