### ISSUE TITLE
Firefox does not display the line lines in lists, e.g. for members

### ISSUE THREAD

**Issue by zonky2** [contao/contao#7242]
### Affected version(s)

5.3.x

### Description

The reason is a bug in FF - the question is whether we want to wait until this is fixed or fix it ourselves.

A simple variant would be change from `collapse`  to `separate` in CSS

```
table {
  border-collapse: separate;
}
```

See
https://stackoverflow.com/questions/24103392/bottom-border-doesnt-show-up-in-firefox
https://stackoverflow.com/questions/7517127/borders-not-shown-in-firefox-with-border-collapse-on-table-position-relative-o

![Mitglieder_FF](https://github.com/contao/contao/assets/1045318/54204131-5898-4bf1-bcc9-f4db59689099)

**Comment by fritzmg** [comment]
@zonky2 which Firefox version are you using on which operating system? I cannot reproduce this issue on Firefox 126.0 under Windows at least.

**Comment by zonky2** [comment]
Debian & FF 115.10.0esr (64-Bit)

**Comment by fritzmg** [comment]
Firefox 115 ESR reaches its end in 4 months, so if this issue only occurs there then imho it's not worth changing anything here. On the other hand

```css
table.tl_listing {
    border-collapse: separate;
}
```

would be a fairly small change and does not seem to impact anything otherwise.

**Comment by zonky2** [comment]
If I am the only one, I can also overwrite this locally...

**Comment by cliffparnitzky** [comment]
> Firefox 126.0 under Windows

I'm using the same like @fritzmg ... no problem. All lines visible.

**Comment by zonky2** [comment]
ok
