### ISSUE TITLE
Wrong single quote encoding on email (&apos;)

### ISSUE THREAD

**Issue by scoomDev** [contao/contao#7245]
### Affected version(s)

4.13.40 -> 4.13.44

### Description

When sending an email from a form generated by Contao, the single quote are badly encoded and look like this: `&apos;`
I was unable to test versions prior to 4.13.40

### Possible solution

add `ENT_QUOTES|ENT_HTML5` argument to `StringUtil::decodeEntities` on `core-bundle/src/Resources/contao/forms/Form.php:479`

`$email->text = StringUtil::decodeEntities(trim($message), ENT_QUOTES|ENT_HTML5) . $uploaded . "\n\n";`

**Comment by fritzmg** [comment]
I can confirm the issue. To reproduce you have to insert a _Textarea_ form field (not a regular text field) and enable email submission. Then input single quotes in the textarea and send.

**Comment by ausi** [comment]
We have to change https://github.com/contao/contao/blob/16ed09efdd13cf32b92616c0681d45604bce92ac/core-bundle/contao/library/Contao/StringUtil.php#L219 to `return html_entity_decode($strString, $strQuoteStyle|ENT_HTML5, 'UTF-8');`

**Comment by ausi** [comment]
Looks like we missed that in #6808 
we should probably check if there are other places we use `html_entity_decode()` without the `ENT_HTML5` flag.
