### ISSUE TITLE
Inserttag {{link_url::7}} gets the wrong output if the page (with id 7) has 'Require an item' enabled

### ISSUE THREAD

**Issue by MacKP** [contao/contao#7250]
### Affected version(s)

4.13.44

### Description

I have a page with the Checkbox enabled for 'Require an item' and i have used the Inserttag for Linking to that page.
The output is now './' and not the URL to the Page with the ID 7.
The behavior I would expact here would be the normal Link to that page. Of course i would then be forwardet to the 404 Page, but i used this to manipulate the output of the link and generate a other Link here.
In Contao 4.9.x this worked nicely.

kind regards

**Comment by fritzmg** [comment]
This is a regression introduced by https://github.com/contao/contao/pull/2555. The `./` URL is supposed to be generated only for the `index` page - but now it is also generated for any page whose URL cannot be generated (due to `requireItem` for instance).

> The behavior I would expact here would be the normal Link to that page.

That cannot happen. The URL for a page that requires an item cannot be generated without a parameter.

**Comment by MacKP** [comment]
> That cannot happen. The URL for a page that requires an item cannot be generated without a parameter.

In Contao 4.9 it was generated ;-)

And on the other Hand it is a little bit confusing, that the Link is the Startpage and not the 404 Error Page. I mean.. i get the Point.. and in my Case it is my Problem, but the result is not what i would expect here.

**Comment by fritzmg** [comment]
> And on the other Hand it is a little bit confusing, that the Link is the Startpage

That's the issue. imho the insert tag must either

* be replaced by an empty string
* or not replaced at all

`./` should be reserved for the URL of the `index` page.

**Comment by MacKP** [comment]
I would prefer that it would not be replaced at all. An empty string is also a little bit confusing i think.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to replace it by an empty string.

**Comment by fritzmg** [comment]
See #7264
