### ISSUE TITLE
Install tool: Page Not Found after update to 4.13.44

### ISSUE THREAD

**Issue by bildschirmartist** [contao/contao#7252]
### Affected version(s)

4.13.44

### Description

I have just updated from Contao 4.13.43 to Contao 4.13.44 and now I have the problem that I cannot access the install tool (https://example.com/contao/install). Instead I get a 404 message. When I try to access the Contao backend, I get the Install Tool displayed.

You can reproduce the error by setting the environment variable `APP_ENV=prod` and setting the `cache.adapter.redis` as framework system cache in the `config_prod.yml`:

```config.yml
framework:
  cache:
    default_redis_provider: 'redis://redis:6379'
    system: cache.adapter.redis
```

In Contao 4.13.43 there are no problems here

**Comment by aschempp** [comment]
if you do not configure the Redis cache it works as expected?

**Comment by bildschirmartist** [comment]
Yes, it works as expected then.

**Comment by fritzmg** [comment]
I cannot reproduce the issue. I started a redis server and added the config

```yaml
framework:
    cache:
        default_redis_provider: 'redis://localhost:6379'
        system: cache.adapter.redis
```

then executed `contao-setup` - but the Install Tool was still accessible.

**Comment by bildschirmartist** [comment]
> I cannot reproduce the issue. I started a redis server and added the config
> 
> ```yaml
> framework:
>     cache:
>         default_redis_provider: 'redis://localhost:6379'
>         system: cache.adapter.redis
> ```
> 
> then executed `contao-setup` - but the Install Tool was still accessible.

@fritzmg: Did you set the `APP_ENV` to `prod`? The error only appears in prod mode.

**Comment by fritzmg** [comment]
Yes, I tested without `APP_ENV=dev` (`prod` is the default in the Contao Managed Edition).

**Comment by bildschirmartist** [comment]
Okay, after deleting the redis cache by hand, the install tool is accessible again.
It might have something to do with the update procedure:

1. Update contao via composer update from 4.13.43 to 4.13.44 with `APP_ENV` set to `dev`
2. Set `APP_ENV` to `prod`
3. Install page is not accessible under `/contao/install` path
4. Delete Redis cache and `var/cache` folders by hand
5. Install page is accessible again

**Comment by fritzmg** [comment]
You need to run `contao-setup` again after changing `APP_ENV`.

Your issue is unrelated to the Contao update.

**Comment by bildschirmartist** [comment]
In my case, it was unfortunately not enough to call contao-setup with a modified `APP_ENV`. I had to delete `var/cache/` and the Redis content afterwards completely by hand; only then the install tool could be called up again.
