### ISSUE TITLE
Backend users with . in username get error when logging in

### ISSUE THREAD

**Issue by danielwolf1** [contao/contao#726]
**Affected version(s)**
4.4.43
**Description**  
If a user with a . in the username is logged in (for example firstname.lastname), an error occures:
/vendor/contao/core-bundle/src/Resources/contao/library/Contao/StringUtil.php on Line 1033 as the regex is matching the username

**How to reproduce**  

1. Create a backend user firstname.lastname
2. Log in and try to edit some articles
3. Error occures

**Comment by xchs** [comment]
I cannot reproduce that.

**Comment by fritzmg** [comment]
@danielwolf1 use the `app_dev.php` and post a full stack trace.
