### ISSUE TITLE
Orphaned temporary ini files in /tmp, when using workers via contao:cron

### ISSUE THREAD

**Issue by md-netdesign** [contao/contao#7260]
### Affected version(s)

5.3.8

### Description

Hello,

we caught a bug while using the Symfony Messenger Workers via `contao:cron` and the supervisor. A new temporary php.ini is created for each subprocess and the ones for the `messenger:consume` commands stay in `/tmp`, even with the unlink shutdown function in place.

This is because the `contao:supervise-workers` command will get killed due to the 60 second timeout in PhpSubprocess class:
https://github.com/symfony/symfony/blob/b3508ee76e982474b4a16c546c2e1a92825ec61b/src/Symfony/Component/Process/PhpSubprocess.php#L54

The supervisor process can't wait for the children (`messenger:consume`) to exit, therefore they will get killed and the temporary ini files will stay in place, ultimately leaving thousands of files in `/tmp`. (At least 3 per minute 😉)

The fix would be as simple as increasing the timeout value while invoking the supervisor to something reasonable like 90 or 120 seconds, to allow the actual workers to exit gracefully after 60 seconds:
https://github.com/contao/contao/blob/6de3df7f79e6287781564a5e0cd274f411f66f33/core-bundle/src/Util/ProcessUtil.php#L60

This could also be added as an argument to the `ProcessUtil::createSymfonyConsoleProcess` function, so the default timeout would not be touched. Instead it could be added here:
https://github.com/contao/contao/blob/6de3df7f79e6287781564a5e0cd274f411f66f33/core-bundle/src/Cron/SuperviseWorkersCron.php#L34

What do you think? We're happy to provide a PR.
Thanks for your time.

**Comment by fritzmg** [comment]
There is a rework in progress that might also alleviate this issue: https://github.com/contao/contao/pull/7253

However: why is the shutdown function not getting called? Our supervisor does not forcefully kill processes, does it?

**Comment by md-netdesign** [comment]
The shutdown function is not getting called, because the process is actually killed (more or less):

Here, a timeout of 60 seconds is set:
https://github.com/symfony/symfony/blob/b3508ee76e982474b4a16c546c2e1a92825ec61b/src/Symfony/Component/Process/PhpSubprocess.php#L54
```php
public function __construct(array $command, ?string $cwd = null, ?array $env = null, int $timeout = 60, ?array $php = null)
```

The supervisor will _at least_ take 60 seconds to execute (55s for the supervising, _at least_ 5s waiting for children to exit). But due to the the messenger queue with Doctrine and the sleep option, this baseline of 60s can actually last up to 80 seconds. The worker would then have a timeout of more than 60 seconds.

The thing is, due to the 60 seconds default timeout in the PhpSubprocess class, the supervisor is timed out. After the timeout, the shutdown function **of the supervisor** is called and the temporary php.ini **for the supervisor** is removed.
But, due to the unexpected shutdown/timeout of the supervisor, the worker processes (the supervisors children) are killed by the operating system. The waiting is actually done and thought of the supervisor class, but the timeout prevents that from happening. Therefore the shutdown handlers of the workers won't get called and at least 3 temporary php.ini remain per minute.
(When executing the `contao:supervise-workers` directly without `contao:cron`, the workers remove their tmp php.ini, because the workers itself and not the supervisor are timed out.)

#7253 could maybe fix this, but if the workers are also started via the Contao cron system and the supervisor stays in place, the problem may also remain. I did not look too deep into the PR.

An increased timeout would be great to deal with that. Currently we're aggregating about 500 MB of temporary php.ini files per day. 😅

**Comment by Toflar** [comment]
Thanks for the detailed analysis, this all makes sense! Imho we have two options.

- Either we set `timeout` to `null` here: https://github.com/contao/contao/blob/5.3/core-bundle/src/Util/ProcessUtil.php#L60 which makes it the default for everybody that uses the `ProcessUtil` - not sure if that's good.
- Or we use `setTimeout(null)` on the Process created here: https://github.com/contao/contao/blob/5.3/core-bundle/src/Cron/SuperviseWorkersCron.php#L34

Can you check if either of those solutions fixes the problem?

**Comment by fritzmg** [comment]
I see, so the issue is that we have subprocesses of subprocesses, correct? (cron > supervisor > worker) And if one subprocess reaches its timeout, its subprocesses get killed rather than being shutdown.

**Comment by md-netdesign** [comment]
Not sure if removing the timeout is good. It sure limits the total time a message can be processed, but in case of an error or if something gets stuck like an external program executed by a message handler, a timeout is really helpful if new workers get spawned every minute, which may stuck at the same message over and over again. 😉

Also, a higher value would be sufficient. I tested with 90 seconds and in our case, this works fine:
https://github.com/contao/contao/blob/5.3/core-bundle/src/Util/ProcessUtil.php#L60
```php
new PhpSubprocess([$this->getConsolePath(), $command, ...$commandArguments], php: [$this->getPhpBinary()], timeout: 90);
```

I also testet "no" timeout, which obviously also works:
```php
return new PhpSubprocess([$this->getConsolePath(), $command, ...$commandArguments], php: [$this->getPhpBinary()], timeout: PHP_INT_MAX);
```
`null` as the timeout is not allowed currently on [PhpSubprocess](https://github.com/symfony/process/blob/56c8a1ea51eb70003fee94a78c7d6d0f44832ce7/PhpSubprocess.php#L54) directly. It could be changed as the base [Process](https://github.com/symfony/process/blob/56c8a1ea51eb70003fee94a78c7d6d0f44832ce7/Process.php#L146) class would allow a `null` value.

**Comment by Toflar** [comment]
Yeah we should definitely not disable it by default but we know that our `messenger:consume` command is actually perfectly allowed to take 30 minutes to complete. It must be allowed to run as long as any message takes to be processed. So if a message takes 30 minutes to complete, that's just fine. Imho we have to disable it in the `SuperviseWorkersCron`. Do you want to create a PR against the 5.3 branch for that?

**Comment by md-netdesign** [comment]
Yes, I'll look into it and I'd use a 30 minute timeout as the default value, which you also used as a baseline in #7251.

**Comment by Toflar** [comment]
I think we cannot accept a hardcoded limit. We do not know how long a job might take to complete.

**Comment by md-netdesign** [comment]
Okay, then I would remove the limit completely.

**Comment by fritzmg** [comment]
I am wondering though it this isn't also a flaw within Symfony itself - i.e. relying on the shutdown function to remove the temporary `.ini` files. By definition `PhpSubprocess` is always used within another process and thus if the parent process dies for whatever reason, the files never get removed.

**Comment by Toflar** [comment]
I guess you are very welcome to improve it. I designed it like this because I wouldn't know how you would want to catch having a process being killed :) But maybe anybody has an idea for a better approach.

**Comment by md-netdesign** [comment]
> I am wondering though it this isn't also a flaw within Symfony itself

Not really. In Symfony, the default process does not have a timeout. Only the PhpSubprocess is given a default timeout, which can optionally (as in the PR) be removed.

The shutdown function **is invoked** on the timed out process. But not on processes, which the timed out process creates. These are killed by the OS itself.

---

So, what's working is: `contao:supervise-workers` > `messenger:consume` (both shutdown functions would have been invoked, `contao:supervise-workers` finishes normally, `messenger:consume` is terminated [not killed!] via timeout)

---

A not working scenario is: `contao:cron` > `contao:supervise-workers` > `messenger:consume`, because the timeout would be applied to `contao:supervise-workers`, which terminates the parent process of `messenger:consume` and therefore the OS kills them and reclaimes resources.
- shutdown function of `contao:supervise-workers` is called
- shutdown function of `messenger:consume` is **not called**, because killed by OS

---

This is not a really a flaw, it's because both sub processes assume a max duration of 60s, which the `messenger:consume` always hit, because they are limited at 60s, as the `contao:supervise-workers`, which starts them some time after starting up itself.

**Comment by fritzmg** [comment]
> Not really. In Symfony, the default process does not have a timeout.

That's not true, the default is `60` as well: https://github.com/symfony/symfony/blob/817a4b20c0e60b28c83f04e681ef2dbfdeb27734/src/Symfony/Component/Process/Process.php#L144

**Comment by fritzmg** [comment]
> So, what's working is: contao:supervise-workers > messenger:consume (both shutdown functions would have been invoked, contao:supervise-workers finishes normally, messenger:consume is terminated [not killed!] via timeout)

This scenario would also fail, if the `contao:supervise-workers` process gets killed or times out.

**Comment by ausi** [comment]
> i.e. relying on the shutdown function

According to [the docs](https://www.php.net/manual/en/function.register-shutdown-function.php) you could use `pcntl_signal` to achieve a clean exit and make sure the shutdown function is called:

```
pcntl_signal(SIGTERM, function () { exit; });
```

But I’m not sure if this works in that case (depends on how the subprocesses are killed)

**Comment by fritzmg** [comment]
That still would not help if `SIGKILL` got used.

Ultimately there can always be cases where an `.ini` file gets left behind in the temp folder (forever). May be this can only be solved through garbage collection?

**Comment by md-netdesign** [comment]
> Ultimately there can always be cases where an `.ini` file gets left behind in the temp folder (forever). May be this can only be solved through garbage collection?

That's true. In our case, the /tmp directory get's cleared periodically of old files, so garbage collection is not required by Contao itself in our case. The issue was only visible due to the amount of Contao projects with workers, which accumulated on this single server.

**Comment by md-netdesign** [comment]
> > Not really. In Symfony, the default process does not have a timeout.
> 
> That's not true, the default is `60` as well: https://github.com/symfony/symfony/blob/817a4b20c0e60b28c83f04e681ef2dbfdeb27734/src/Symfony/Component/Process/Process.php#L144

Missed that, sorry. But it can be set directly to `null` there.

**Comment by ausi** [comment]
> Ultimately there can always be cases where an `.ini` file gets left behind in the temp folder

We could pass all the ini settings using `-d` options instead of an ini file. If there is no limit on command line options or command string length this should work I think.

> May be this can only be solved through garbage collection?

The operating system should take care of that, but it still should only be needed for edge cases (500 MB temporary files per day is waaay to much).

**Comment by md-netdesign** [comment]
> The operating system should take care of that, but it still should only needed for edge cases (500 MB temporary files per day is waaay to much).

Absolutly! But with the PR this won't really happen anymore. Then it would be just edge cases. So it would be totally acceptable. :)

**Comment by fritzmg** [comment]
> We could pass all the ini settings using `-d` options instead of an ini file. If there is no limit on command line options or command string length this should work I think.

It seems it is 131072 under Linux: https://serverfault.com/a/844666

**Comment by fritzmg** [comment]
> The operating system should take care of that, but it still should only be needed for edge cases (500 MB temporary files per day is waaay to much).

Though it appears some Linux distributions only clear temp files on boot by default - which could mean never. But I hope web hosters consider this.

Windows never deletes any tmp files itself automatically.

**Comment by Toflar** [comment]
Adjusting the timeout is correct anyway. No matter what we improve in Symfony or not.
