### ISSUE TITLE
Spanish backend language files are not loaded

### ISSUE THREAD

**Issue by swiss-netwalk** [contao/contao#7261]
### Affected version(s)

5.3.9

### Description

You can select Spanish in the backend profile, but no language files are exchanged. English is displayed instead. (Also in the online demo)
<https://github.com/contao/contao/tree/5.3.9/core-bundle/contao/languages/es>
https://github.com/contao/contao/tree/5.2.10/core-bundle/contao/languages/es

**Comment by zoglo** [comment]
^
The whole 5.3.* branch does not have any language files associated for the following languages (as far as I looked within contao/core-bundle)

**Spanish**
- https://github.com/contao/contao/tree/5.2.9/core-bundle/contao/languages/es
- https://github.com/contao/contao/tree/5.3.9/core-bundle/contao/languages/es

**Farsi**
- https://github.com/contao/contao/tree/5.2.9/core-bundle/contao/languages/fa
- https://github.com/contao/contao/tree/5.3.9/core-bundle/contao/languages/fa

____

<img src="https://github.com/contao/contao/assets/55794780/cd0a0e73-2fe0-49de-b44d-7dec81c8ce15" width="360">

**Comment by leofeyer** [comment]
Translations are only included if they are at least 95% complete. Current stats for Spanish:

* calendar-bundle: 97%
* comments-bundle: 98.7%
* core-bundle: **93.7%**
* faq-bundle: 97.5%
* listing-bundle: 100%
* manager-bundle: 100%
* news-bundle: **94.7%**
* newsletter-bundle: 96.5%

So there should be Spanish language files in all bundles except the core bundle and the news bundle. The only way to get this fixed is to complete the translation on transifex.com.

**Comment by fritzmg** [comment]
The remaining `tl_style` and `tl_style_sheet` language files are probably remnants for BC reasons, as these translations do not exist anymore in Contao 5.

**Comment by alex1971** [comment]
Translations in spanish are now completed on transifex.com

![Bildschirmfoto 2024-06-06 um 17 44 41](https://github.com/contao/contao/assets/6985539/59d407a4-e1bc-4702-a20b-19f2b1d3bca1)
