### ISSUE TITLE
Feature request : exclude /api routes from being stored as referrer

### ISSUE THREAD

**Issue by aznoqmous** [contao/contao#7265]
### Description

**Issue :** Recent changes regarding storing backend controller routes as referrer broke return / save and close buttons

**Case :** I've got a few bundles that uses fetch requests inside Contao backend to query api routes
By default, those api routes are now stored as referrers when fetched so a return action redirect directly to the api route

Could it be possible to exclude all routes starting with "/api" from being stored as referrer ?
I could also go and edit every bundles/sites controllers that reproduces this behaviour, but excluding "^/api/" from being storred as referrer sounded natural, as per this request

[initial issue](https://github.com/contao/contao/issues/7190)
[commit](https://github.com/contao/core-bundle/commit/855dc1a96edc5591a9144a44cbaa12a93ab8aea0)

**Comment by fritzmg** [comment]
I was afraid of that 😁

@contao/developers should we change it to Opt-In after all?

@aznoqmous depending on how you define your routes, you might be able to set a default for your routes, thus you have to set `_store_referrer: false` only in one place.

**Comment by aznoqmous** [comment]
Sure, setting it in ``routing.yml`` for each controller did the trick 

I filed a quick proposal [here ](https://github.com/contao/core-bundle/compare/4.13...aznoqmous:core-bundle:patch-1)
Will ask for pull request if you wish !

**Comment by fritzmg** [comment]
Excluding it for every route starting with `/api` is too arbitrary.

> Sure, setting it in routing.yml for each controller did the trick

Well I did not mean setting it for each controller. I meant doing it like this for example:

```yaml
# config/routes.yaml
api:
    resource: ../src/Controller/Api
    type: attribute
    prefix: /api
    defaults:
        _scope: backend
        _store_referrer: false
```

But as I said, it depends on how you are defining your routes - and where in your namespace your API controllers reside.

**Comment by leofeyer** [comment]
> @contao/developers should we change it to Opt-In after all?

IIRC, we said that there are only a few use cases in which we don‘t want to store the referrer, therefore we chose opt-out. A back end API is one of these few use cases in my opinion.
