### ISSUE TITLE
Feature Request: Place multiple customized swiper elements on a page

### ISSUE THREAD

**Issue by berecont** [contao/contao#7271]
### Description

Contao 5.3 Content Element Content-Slider
Currently, it is only possible to display a single functional (template customized) slider element on a page. From the second swiper element with customized templates onwards, only (the last) one on the page works.

I am referring to the request for adjustments within the `{% block script %}` `<script{{ script_attributes }}>` in a template `mycustomizedswipertemplate.html.twig`.

**Comment by berecont** [comment]
example:

first CE Content-Slider

```
{# /templates/content_element/swiper/topslider.html.twig #}

{% extends "@Contao/content_element/swiper.html.twig" %}

{% block controls %}

    {% set button_prev_attributes = attrs()
        .set('type', 'button')
        .addClass('swiper-button-prev button button-border border-0 button-rounded')
        .mergeWith(button_prev_attributes|default)
    %}
    <button{{ button_prev_attributes }}></button>
    {% set button_next_attributes = attrs()
        .set('type', 'button')
        .addClass('swiper-button-next button button-border border-0 button-rounded')
        .mergeWith(button_next_attributes|default)
    %}
    <button{{ button_next_attributes }}></button>
    {% set pagination_attributes = attrs()
        .addClass('swiper-pagination')
        .mergeWith(pagination_attributes|default)
    %}
    <div{{ pagination_attributes }}></div>

{% endblock %}


{% block script %}

    {{ parent() }}

    {% add "swiper_js" to body %}
        {% set script_attributes = attrs()
            .setIfExists('nonce', csp_nonce('script-src'))
            .mergeWith(script_attributes|default)
        %}
        <script src="{{ asset('js/swiper-bundle.min.js', 'contao-components/swiper') }}"></script>
        <script{{ script_attributes }}>
            (function() {
                const swiper = document.querySelectorAll('.swiper');
                swiper.forEach (el => {
                    let opts = {
                        speed: el.getAttribute('data-speed'),
                        initialSlide: el.getAttribute('data-offset'),
                        loop: el.hasAttribute('data-loop'),
                    };

                    let delay = el.getAttribute('data-delay');
                    if (delay > 0) {
                        opts['autoplay'] = { delay: delay };
                    }

                    new Swiper(el, Object.assign({
                        {% block init_options %}
                            navigation: {
                                prevEl: '.swiper-button-prev',
                                nextEl: '.swiper-button-next',
                            },
                        {% endblock %}
                    }, opts));
                });
            })();
        </script>
    {% endadd %}
{% endblock %}
```

second CE Content-Slider
```

{# /templates/content_element/swiper/auszeichnungen.html.twig #}

{% extends "@Contao/content_element/swiper.html.twig" %}

{% block controls %}

    {% set button_prev_attributes = attrs()
        .set('type', 'button')
        .addClass('swiper-button-prev button button-border border-0 button-rounded')
        .mergeWith(button_prev_attributes|default)
    %}
    <button{{ button_prev_attributes }}></button>
    {% set button_next_attributes = attrs()
        .set('type', 'button')
        .addClass('swiper-button-next button button-border border-0 button-rounded')
        .mergeWith(button_next_attributes|default)
    %}
    <button{{ button_next_attributes }}></button>
    {% set pagination_attributes = attrs()
        .addClass('swiper-pagination')
        .mergeWith(pagination_attributes|default)
    %}
    <div{{ pagination_attributes }}></div>

{% endblock %}

{% block script %}

    {{ parent() }}

    {% add "swiper_js" to body %}
        {% set script_attributes = attrs()
            .setIfExists('nonce', csp_nonce('script-src'))
            .mergeWith(script_attributes|default)
        %}
        <script src="{{ asset('js/swiper-bundle.min.js', 'contao-components/swiper') }}"></script>
        <script{{ script_attributes }}>
            (function() {
                const swiper = document.querySelectorAll('.swiper');
                swiper.forEach (el => {
                    let opts = {
                        speed: el.getAttribute('data-speed'),
                        initialSlide: el.getAttribute('data-offset'),
                        loop: el.hasAttribute('data-loop'),
                    };

                    let delay = el.getAttribute('data-delay');
                    if (delay > 0) {
                        opts['autoplay'] = { delay: delay };
                    }

                    new Swiper(el, Object.assign({
                        {% block init_options %}
                            navigation: {
                                prevEl: '.swiper-button-prev',
                                nextEl: '.swiper-button-next',
                            },
                            grabCursor: true,
                            slidesPerView: 2,
                            breakpoints: {
                                576: {
                                slidesPerView: 3,
                                spaceBetween: 40,
                                },
                                768: {
                                slidesPerView: 4,
                                spaceBetween: 40,
                                },
                                1024: {
                                slidesPerView: 5,
                                spaceBetween: 50,
                                },
                            },                            

                        {% endblock %}
                    }, opts));
                });
            })();
        </script>
    {% endadd %}
{% endblock %}
```
only the second one works

**Comment by leofeyer** [comment]
That‘s because both templates do `{% add "swiper_js" to body %}`. If you change this  to `{% add "swiper_js_topslider" to body %}` and `{% add "swiper_js_auszeichnungen" to body %}`, both scripts will be loaded.

**Comment by fritzmg** [comment]
@leofeyer this alone will not be sufficient. You would also have to remove `<script src="{{ asset('js/swiper-bundle.min.js', 'contao-components/swiper') }}"></script>` from one of them. But then one will depend on the other.

Then you also have to adjust the initialization script to only affect one specific swiper element. But then if you add another swiper to the same page which does not use a variant template, its initialization script will affect all the other swipers still (and it would again add `<script src="{{ asset('js/swiper-bundle.min.js', 'contao-components/swiper') }}"></script>`).

**Comment by zoglo** [comment]
Imho, this is a customization limitation rather than a bug or a feature since custom options are being parsed whilst initializing the slider on elements that have the same classes.
You absolutely need to add a custom class to the element and initialize swiper on that.

@fritzmg afaik, loading the script multiple times could be handled with a `js_swiper`-template but it would be a BC break for anyone overriding their templates completely to change the slider init (as seen in this issue). Rest could work through `data-*`-attributes.

**Comment by fritzmg** [comment]
> You absolutely need to add a custom class to the element and initialize swiper on that.

That alone won't be sufficient either, as the original script will still initialize all swipers.

**Comment by zoglo** [comment]
> That alone won't be sufficient either, as the original script will still initialize all swipers.
Unless you rewrite the slider initialization and the element classes for the current swiper elements, it will always be like that, yes.

Hence why I said to use it with a template and have the options in the markup rather than in the slider-init.

This adapter works with the Tiny Slider for example and reads the data attributes

https://github.com/contao-thememanager/ctm-tiny-slider/blob/cad3753b8900049840412762a4fb7a40ad5f4702/contao/templates/js/js_ctm_tinyslider.html5#L98 

![image](https://github.com/contao/contao/assets/55794780/3eb7fe4b-27ff-4518-8cf4-4213adf44b60)

**Comment by m-vo** [comment]
In the end, each output element should include the same named target ("add foo to body") for adding the bundled swiper resource, but its own separate init script - either directly inline, or in the body without a named target ("add to body").

You could do this relatively easily in your version of the `script` block. But we could improve this, by adding another block just for the swiper resource, so that you would not have to repeat this. 👍

**Comment by m-vo** [comment]
Or: you could introduce data attributes for the specific things in the elements and enhance the script for all. Then it would also be beneficial to have some blocks inside the script.

**Comment by fritzmg** [comment]
Personally I would put the whole Swiper configuration as JSON in a data attribute. And said JSON will be generated by the fragment. May be this is something we want to provide by default in our controller? Then adding new options could be as easy as extending the DCA (possibly).

**Comment by zoglo** [comment]
It's basically what I said above - it's just how you'd do that without a BC break.

Maybe it'll just work the same for already modified templates due to loading the original script.
The new one would load an adapter, the script and add the data attributes.

**Comment by fritzmg** [comment]
We can still add the old data attributes for BC in the default template (it's only 4 of them).

**Comment by delirius** [comment]
In swiper.html.twig, all objects with the '.swiper' class are always processed. If there are several sliders on a page, the last setting is applied to all objects. One suggestion is to assign a unique id for each slider. And to divide the script block into a general swiper script and a configuration script. 
PR #7438

**Comment by leofeyer** [comment]
See #7271
