### ISSUE TITLE
2FA - guest and logged in at same time

### ISSUE THREAD

**Issue by FrankBuchmann** [contao/contao#7272]
### Affected version(s)

4.13.44

### Description

After the login form, the next step takes you to the 2FA page.
Here is the problem: Both the pages “for guests only” and the pages “for certain member groups” are displayed in the menu.

So you are a guest and logged in at the same time.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we have to adjust the voter so users are treated as guests unless they have completed the 2FA step.

**Comment by fritzmg** [comment]
@FrankBuchmann could you check if the change in https://github.com/contao/contao/pull/7323 fixes your issue?
