### ISSUE TITLE
Application Configuration .env.dist

### ISSUE THREAD

**Issue by tme55** [contao/contao#7280]
### Affected version(s)

4.13.44

### Description

Zuerst möchte ich sagen, dass ich mir nicht sicher bin, ob nachfolgendes ein Contao-Bug, Symfony-Bug, ein Fehler in der Dokumentation ist oder ich es einfach nicht verstehe.

Laut [Developer Documentation](https://docs.contao.org/dev/getting-started/starting-development/#application-configuration) kann eine `.env.dist` erstellt werden, die genutzt wird, falls `.env` nicht vorhanden ist. Ich habe nun in einem Deloy nur die `.env.dist` auf den Server geschoben. Die Konfiguration dortdrin wird jedoch komplett ignoriert. Auch ein `./vendor/bin/contao-console debug:dotenv` weiss nichts damit anzufangen:

`Dotenv Variables & Files  
[ERROR] Dotenv component is not initialized. `

Das Neuaufbauen des Caches ändert nichts an dem Verhalten. `./vendor/bin/contao-setup` legt eine leere `.env` an, die laut Doku gegenüber `.env.dist` priorisiert wird.

**Comment by fritzmg** [comment]
The information in the documentation is out of date for two reasons:

 In principle it is true that the `.env.dist` will be loaded, if no `.env` is found (at least according to the code comments in Symfony 5). However, the `contao-setup` script of the Contao Managed Edition will _always_ create a `.env` file. It does not consider this use case.

Furthermore the `.env.dist` is a remnant from previous Symfony versions and its use is now discouraged. See the explanation here: https://symfony.com/blog/improvements-to-the-handling-of-env-files-for-all-symfony-versions
