### ISSUE TITLE
{{file::*}} not supporting passed arguments

### ISSUE THREAD

**Issue by xApep** [contao/contao#7286]
### Affected version(s)

5.3.9

### Description

This was working on Contao 4 now I do not know if this is not supported in Contao 5 or approach has changed, but by official docs it should work.

Let me explain.
In header.html5 we have
`{{file::icons/carrot-down.html5?settings=w-4}}`

carrot-down.html5 looks like this
```
`<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 16 16"
  class="<?= \Contao\Input::get('settings'); ?>">
  <path d="M0,0H16V16H0Z" fill="none" />
  <path data-name="Path" d="M4.243,3.3,7.543,0l.943.943L4.243,5.185,0,.943.943,0Z"
    transform="translate(3.757 5.481)" fill="currentColor" />
</svg>`
```

Now the problem is that settings does not print anything, also if I dump `\Contao\Input::get('settings')` it is returning `null`

**Comment by xApep** [comment]
I see already an open ticket issue which is related: https://github.com/contao/contao/issues/7220

**Comment by ausi** [comment]
Yes, this is a duplicate of #7220

**Comment by ausi** [comment]
Should get fixed by #7287

But please be aware that this usage of the `{{file::*}}` insert tag is deprecated: _“Using the file insert tag to include templates has been deprecated and will no longer work in Contao 6. Use the "Template" content element instead.”_

**Comment by xApep** [comment]
> Should get fixed by #7287
> 
> But please be aware that this usage of the `{{file::*}}` insert tag is deprecated: _“Using the file insert tag to include templates has been deprecated and will no longer work in Contao 6. Use the "Template" content element instead.”_

Thank you for the replay. 

Can you paste a link from which doc did you copy paste “Using the file insert tag to include templates has been deprecated and will no longer work in Contao 6. Use the "Template" content element instead.”? I want to see what Use template means :)

Thanks

**Comment by ausi** [comment]
> Can you paste a link from which doc did you copy paste…

It’s the deprecation notice directly from the source code: https://github.com/contao/contao/blob/2ff871dcec97ce4ef9fd8d74f4c08be855958a0b/core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php#L624

> I want to see what Use template means :)

This refers to the content element type “Custom Template”, see https://docs.contao.org/manual/en/article-management/content-elements/include-elements/#custom-template

**Comment by xApep** [comment]
> > Can you paste a link from which doc did you copy paste…
> 
> It’s the deprecation notice directly from the source code:
> 
> https://github.com/contao/contao/blob/2ff871dcec97ce4ef9fd8d74f4c08be855958a0b/core-bundle/src/InsertTag/Resolver/LegacyInsertTag.php#L624
> 
> > I want to see what Use template means :)
> 
> This refers to the content element type “Custom Template”, see https://docs.contao.org/manual/en/article-management/content-elements/include-elements/#custom-template

Maybe I'm blond, but I just can't find relation of usage for {{file}} and Custom template - aren't those two completely  2 different things?

**Comment by ausi** [comment]
> Maybe I'm blond, but I just can't find relation of usage for {{file}} and Custom template - aren't those two completely 2 different things?

Instead of using the `{{file}}` insert tag to include a template you should use the content element “Custom Template” to include a template.
If you explicitly need to include this via an insert tag then, you can use `{{insert_content::*}}` for that.

**Comment by xApep** [comment]
Yeah I get this.

But {{file}} includes physical file, for instance svg icons which you place them in templates folder and then you can simply reuse them in .html5 or .twig templates or in backend fields.

**Comment by fritzmg** [comment]
Including files with {{file::*}} is fine and not deprecated.

**Comment by ausi** [comment]
Including file-**paths** using `{{file::*}}` with a UUID is still supported.
But including anything from the templates folder is depreacted.

> for instance svg icons which you place them in templates folder and then you can simply reuse them

I think for this case using a dedicated `{{svg}}` insert tag might be the better solution for the future.
