### ISSUE TITLE
DC_Table MODE_TREE javascript not working if `global_operations` `toggleNodes` missing

### ISSUE THREAD

**Issue by michb** [contao/contao#7288]
### Affected version(s)

5.3.9

### Description

In Contao 5.3 if you configure a dca with `DC_Table` and `MODE_TREE` the javascript to collapse/expand the children will not work  if the `global_operations` `toggleNodes` is not present.

IMHO `toggleNodes` should be optional as this is technically not required to collapse or expand the children in the tree.

To reproduce you can add
```
unset($GLOBALS['TL_DCA']['tl_page']['list']['global_operations']['toggleNodes']);
```
to an onload callback in `tl_page`, like `tl_page::adjustDca`.

**Comment by leofeyer** [comment]
How do you trigger the script without the operation?

**Comment by michb** [comment]
I mean the collapse and expand operation of individual entries in the tree.

**Comment by Toflar** [comment]
I can confirm the issue.
