### ISSUE TITLE
laufende Events  mit Zeitangabe werden ausgeblendet

### ISSUE THREAD

**Issue by tuxenberger** [contao/contao#729]
**Affected version(s)**

Version 4.4.42 / 4.8.2

**Description**  

Event list module configured as below screenshot.
Alle Events are single events with one date (same start and enddate (start 06.09.2019 end 06.09.2019) and are setup wit a starttime (startzeit 16:30 endzeit 17:30)

Problem: When reaching the starttime, the event will be hide.

I used google for the problem and found a forum entry that the problem was fixed in 3.5.18

https://community.contao.org/de/showthread.php?64303-Eventliste-blendet-laufende-Events-aus.

**How to reproduce**  

Could reproduce that in the event list: insert date of today and a starttime. When starttime = actual time of the server, event will hide immediately. Liste-Template was "teaser" with some edits, not the default..

![Bildschirmfoto 2019-09-06 um 15 24 25](https://user-images.githubusercontent.com/10707430/64437370-79f96400-d0c6-11e9-8c96-3e2318ffadcb.png)

![Bildschirmfoto 2019-09-06 um 15 24 50](https://user-images.githubusercontent.com/10707430/64437391-81207200-d0c6-11e9-974e-6f9a0b2a6ede.png)

**Comment by tuxenberger** [comment]
Nach einigen Tests nun eine Relativierung: es funktioniert doch.

Lösung: Im Eventlisten-Modul die Option: "Verkürzte Darstellung" aktivieren. Da wäre ich nie drauf gekommen, da die Optionsbeschreibung in der Info auch keinen Hinweis gibt:
"Events nur einmal anzeigen, auch wenn sie mehrere Tage umfassen."

Meine Events waren einmaliger Events ohne Wiederholung - folglich habe ich die Option auch nicht als relevant angesehen. 

Könnte man ggf. die Optionsbenennung anpassen, damit die Funktion klarer wird?
Beispielsweise: 
"Laufende Events bis zur Endzeit (Uhrzeit) anzeigen und dann ausblenden. Wiederholende Events nur einmal anzeigen, auch wenn sie mehrere Tage umfassen."

**Comment by fritzmg** [comment]
Diese Option sollte darauf ja eigentlich keine Auswirkung haben?

**Comment by tuxenberger** [comment]
Ist genau so im der Contao-Demo konfiguriert - was mich auf die Spur der Funktion gebracht hat. 
Hier sind ja auch wiederholende Termine eingestellt. Aber mein Test-Einzelseminar war auch über die Startuhrzeit raus in der Liste bis zur Endzeit angezeigt und wurde dann erst ausgeblendet. Also genau die Anzeigeoption, die ich gesucht hatte. 

Was halt für Zusätzliche Verwirrung gesorgt hatte war die weiter unten zu findende Option "Laufende Events ausblenden" mit der Beschreibung "Laufende Events in der Liste der zukünftigen Events nicht anzeigen." Damit war für mich klar, das laufende Events von sich aus eigentlich bis zum Ende angezeigt werden - was aber nicht der Fall ist. Sobald die Startzeit erreicht ist wird der Event (Listenkonfiguration: Alle Zukünftigen Events) ausgeblendet. 

Wenn man das Ganze nun so zusammenbaut, das laufende Termine bis zum Uhrzeit-Ende angezeigt werden sollen und danach erst in einer Liste mit abgelaufenen Terminen erscheinen sollen funktioniert das auch nicht - die Liste mit den abgelaufenen Events zeigt den Event an, sobald dieser die Anfangszeit erreicht hat.

Beispiel hier:

![Bildschirmfoto 2019-09-12 um 10 49 57](https://user-images.githubusercontent.com/10707430/64770221-08e60080-d54d-11e9-84c9-21674944fd89.png)

Diese Konfiguration war bei einem Festival, wo ja alle Auftritte bis zur End-Uhrzeit für einen Zuschauer "verfügbar" sind und erst dann in abgelaufene Termine verschoben (angezeigt) werden sollten geplant - und hat mir gehöriges Kopfzerberechen bereitet, da die Anforderung erst kurz vor Festivalstart gestellt wurde und der Fehler damit auch quasi Live erst aufgefallen ist. 

Ich habe das dann mit manuellem rumkopieren der abgelaufenen Events und der Option "Alle Events anzeigen" gelöst. Die Definition "Anzeigen bis" hat da auch nicht weiter geholfen, da ja dann der komplette Datensatz nicht mehr angezeigt worden wäre - also auch keine Anzeige im Archiv möglich war. 

Eine weiterer Lösungsansatz ein Duplikat aller Events in einer zweiten Liste hat die Uhrzeit und Datumsangaben (richtiger wiese) nicht mit übertragen und die Datensätze wären auch unter eine anderen URL (Alias wäre ja sonst doppelt gewesen) erreichbar (Suchmaschine kriegt dann 404  zurück und listet die URL aus).

Bei Seminaren oder Filem, also "geschlossenen" Veranstaltungen ist das aktuelle Verhalten ja kein Problem, in "offenen" Veranstaltungen dir bis zum Ende verfügbar sein sollen schon.
