### ISSUE TITLE
Search Engine > Crawling not finding anything

### ISSUE THREAD

**Issue by biowebfr** [contao/contao#7297]
### Affected version(s)

5.3.9

### Description

Hi,

I can't find a way to make the crawling command to work.

![image](https://github.com/contao/contao/assets/46192868/2a70c85a-ba7e-4129-8bba-d64e239c35d9)

I've  defined the correct domain, all pages and the search module are correctly configured.

Is there a bug or something in the lastest version of Contao ?

**Comment by Toflar** [comment]
You can enable the debug log (see command line options), it will tell you why nothing was indexed :)

**Comment by biowebfr** [comment]
Thank you Toflar, so it says : 
'''"Terminal42\Escargot\Subscriber\RobotsSubscriber",http://contao5.test/client,,0,noindex,"Added the ""noindex"" tag because the X-Robots-Tag header contained ""noindex"".'''

But I can't find any configuration in the root page of the site to change this.

**Comment by biowebfr** [comment]
So here is something I discover.
I didn't have any robot.txt inside /public and the result was this (the command never ends):
![image](https://github.com/contao/contao/assets/46192868/af3c5f45-cc59-4c90-b9a3-8a96bb1a2ec0)

I add a robot.txt inside the /public then I have this result.
And now the command ends but with errors leading to this noindex issue
![image](https://github.com/contao/contao/assets/46192868/4d04a91a-2be4-4d5c-8cfb-e89c13a9a801)

![image](https://github.com/contao/contao/assets/46192868/87310456-fa9b-4be5-a1aa-41f148c1da24)

**Comment by Toflar** [comment]
The `robots.txt` is created dynamically by Contao (it's a route). And the `X-Robots-Tag: noindex` is added automatically in DEV.
Anyway, I don't think there's a bug here and this is a case for the support channels.

**Comment by biowebfr** [comment]
Ok thank you so much, it feels like an issue because the documentation doesn't mention this DEV limitation regarding the crawl command.
https://docs.contao.org/manual/en/cli/crawl/

Switching env to prod resolve the thing. 

So I don't want to abuse, but last question, can we access to the content of robot.txt ?

**Comment by Toflar** [comment]
The docs are open source, please contribute :) 

> So I don't want to abuse, but last question, can we access to the content of robot.txt ?

https://docs.contao.org/dev/reference/events/#contao-robots-txt

**Comment by biowebfr** [comment]
I'll do it, sorry for the inconvenience.

**Comment by Toflar** [comment]
No inconvenience at all 😊 Just trying to keep the bug tracker focused on bugs only, otherwise we'll drown in issues 😅
