### ISSUE TITLE
Kick all deprecated things for 4.0

### ISSUE THREAD

**Issue by Toflar** [contao/contao#73]
We have tons of `@deprecated` statements that have been added in version 2 or 3 already, those methods/classes should be dropped in 4.0 :)

**Comment by leofeyer** [comment]
Fine with me, I guess. Would have to take a detailed look though.

**Comment by Toflar** [comment]
Would be pretty helpful because then all `@deprecated` hints are related to "from version 3 to version 4".

**Comment by discordier** [comment]
I'd love to see a lot to disappear.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/151.
