### ISSUE TITLE
The registry already contains an instance for tl_page::id()  .. Registry.php:174

### ISSUE THREAD

**Issue by wwwebgainss** [contao/contao#73]
Hi,

after a fresh installation of Contao v. 4.4.25 when i am trying to save a page, i get this error. 

RuntimeException(code: 0): The registry already contains an instance for tl_page::id() at /web/web11249/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model/Registry.php:174

**Comment by leofeyer** [comment]
See #63.

**Comment by wwwebgainss** [comment]
Muchas Gracias!
