### ISSUE TITLE
Content elements in the news are rendered twice

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#7311]
### Affected version(s)

4.13.45

### Description

When debugging my news detail page, I noticed that the variables are always output twice. This is due to the preparation of the Schema.org data.

```
<?php

$schemaOrg = $this->getSchemaOrgData();

if ($this->hasText) {
    $schemaOrg['text'] = $this->rawHtmlToPlainText($this->text);
}

$this->addSchemaOrg($schemaOrg);
```

It may be possible to prevent all content elements from being rendered again.

**Comment by fritzmg** [comment]
Closing in favor of #7314
