### ISSUE TITLE
Error: Call to undefined function Symfony..

### ISSUE THREAD

**Issue by iamfoa** [contao/contao#7312]
### Affected version(s)

5.3.10

### Description

After installing version 5.3.10 the following error appers:
php.CRITICAL: Uncaught Error: Call to undefined function Symfony\Component\Messenger\EventListener\pcntl_signal_dispatch() {"exception":"[object] (Error(code: 0)

**Comment by fritzmg** [comment]
This is an issue in Symfony: https://github.com/symfony/symfony/pull/57514

**Comment by Toflar** [comment]
It's just been released: https://github.com/symfony/symfony/releases/tag/v6.4.9
Just update the dependencies again, and you should be good to go.
