### ISSUE TITLE
DCA eval "'decodeEntities' => true" does not work for '<' character.

### ISSUE THREAD

**Issue by tsarma** [contao/contao#7322]
### Affected version(s)

4.13.x

### Description

I am using this regex `/^[\w .,<>]+$/u` for Contao form field custom validation. But in the Database it is saved as `/^[\w .,&lt;>]+$/u`. The character `<` is encoded. 

Also inside https://github.com/contao/contao/blob/4.13/core-bundle/src/EventListener/Widget/CustomRgxpListener.php#L46 , we need to decode the value from frontend form Input before matching to the regex

```php
if (!preg_match($widget->customRgxp, StringUtil::decodeEntities($input))) {
```

**Comment by ausi** [comment]
The `<` character always gets encoded. You can use `'useRawRequestData'=>true` to get the value without any encoding. In this case you need to make sure it gets properly encoded in all places where it is output to the browser.

**Comment by ausi** [comment]
You can find more details of how the `Input` encoding works here: https://github.com/contao/contao/pull/4453#issuecomment-1094112590

**Comment by fritzmg** [comment]
Should we enable that by default for `tl_form_field.customRgxp`?

**Comment by tsarma** [comment]
@fritzmg When there is a field provided to enter a custom regex, then a user would expect it stays same. So in that sense I would not encode anything for `tl_form_field.customRgxp`.  But as an argument put forward by @ausi that Contao encodes `<` character always, is like you have to live with it by system design. 
In my case I ended up defining my own `addCustomRegexp` hook for my custom validation.

**Comment by ausi** [comment]
> Should we enable that by default for `tl_form_field.customRgxp`?

I’m not sure. We never output it as HTML, right? (like as `<input pattern="…">` or so?)

**Comment by fritzmg** [comment]
> I’m not sure. We never output it as HTML, right? (like as `<input pattern="…">` or so?)

At the moment we don't, no.

We could also decode the entities here instead:

https://github.com/contao/contao/blob/34d4ec1c21f5bb22e43cfabf3a6b49b8028421b8/core-bundle/src/EventListener/Widget/CustomRgxpListener.php#L38

Then we could also remove `'decodeEntities'=>true` from the field, ensuring that entities are always encoded if someone adds the regular expression to a `pattern` attribute in a template.

**Comment by leofeyer** [comment]
@tsarma Can you make a pull request with the necessary changes?
