### ISSUE TITLE
Job ID when crawling should be output at the start

### ISSUE THREAD

**Issue by zonky2** [contao/contao#7324]
### Description

C 4.13/5.3
see https://github.com/Toflar/contao/blob/bada178a0fbbb3c599a0853a5135b1ac9e979bb6/core-bundle/src/Command/CrawlCommand.php#L148

**Comment by Toflar** [comment]
Why?

**Comment by zonky2** [comment]
According to the manual, the job can be interrupted and resumed by entering the ID. However, if the ID is only displayed when the crawler is finished, you don't need to keep it running... Without the ID, however, you cannot continue the job...

**Comment by zonky2** [comment]
Yanick @ Slack:

> Nee, die ID ist ja nur dafür da, einen noch nicht beendeten Job wieder aufzunehmen. Also die macht nur in Verbindung von `max-requests` Sinn.

**Comment by leofeyer** [comment]
So has the problem been solved or not?
