### ISSUE TITLE
CSS class/id for include element not in frontend

### ISSUE THREAD

**Issue by Funbug** [contao/contao#7338]
### Affected version(s)

5.3.11

### Description

The CSS class/id for an include element doesn't show up in the frontend at all. In Contao 4.13 those got merged with the ones from the included element. This would be my expected behaviour for 5.3 as well.

**Comment by ausi** [comment]
I was able to reproduce that on demo.contao.org, but I’m not sure why this happens.

**Comment by aschempp** [comment]
it happens because of https://github.com/contao/contao/pull/6985/files#diff-5d8e5f6404d79ec664e67c00607bb1e8d4f7fad38c49b0dac7167afbfeded3d2R566. We now clone the original model, if it has been modified that change is now lost …

**Comment by ausi** [comment]
So we just need to replace `$objRow = $objRow->cloneOriginal();` with `$objRow = clone $objRow;` and it works again?

**Comment by aschempp** [comment]
That could work, yes

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7364
