### ISSUE TITLE
Use the ICU data from the Symfony intl component

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#734]
Im Unicode Common Locale Data Repository steht eine neue Version 35.1 mit aktuellen Länderbezeichnungen zur Verfügung (siehe auch contao/core#8453).

**Comment by leofeyer** [comment]
Welche Bezeichnungen haben sich geändert?

**Comment by Mynyx** [comment]
Zum Beispiel Mazedonien zu Nordmazedonien und Tschechische Republik zu Tschechien.

**Comment by Toflar** [comment]
Wir sollten uns imho eh auf die `intl` Komponente dafür verlassen.

**Comment by leofeyer** [comment]
Dagegen sprechen aus meiner Sicht mehrere Gründe:

1. Hat die `intl`-Extension überhaupt alle Übersetzungen, die wir im Backend auch haben?

2. Wie verhält es sich, wenn man eine alte PHP-Version (z.B. 7.1) verwendet? Hat man dann immer nur die alten Länderbezeichnungen?

**Comment by Toflar** [comment]
>     1. Hat die `intl`-Extension überhaupt alle Übersetzungen, die wir im Backend auch haben?

Jup, plus all die, die uns fehlen :) ICU/Unicode halt.

>     2\. Wie verhält es sich, wenn man eine alte PHP-Version (z.B. 7.1) verwendet? Hat man dann immer nur die alten Länderbezeichnungen?

Das hat damit nichts zu tun. Die `intl`-Extension bzw. die darunterliegende ICU Bibliothek muss halt aktuell gehalten werden. Das muss sie aber eh. Wir nutzen die Komponenten ja sonst auch bereits.

**Comment by leofeyer** [comment]
Dann sollten wir das in der 4.9 umbauen.

**Comment by ausi** [comment]
Aus Erfahrung mit dem Slug-Generator haben wir aber auch gelernt, dass diverse Hoster 10-Jahre alte ICU-Versionen einsetzen https://github.com/contao/core-bundle/issues/1352#issuecomment-363116503

Wie wäre es, wenn wir die Daten weiterhin in Contao pflegen, aber ein Skript schreiben dass sich die Bezeichnungen aus dem aktuellsten CLDR holt?

**Comment by leofeyer** [comment]
Eben das war ja meine Frage. 😂

**Comment by Toflar** [comment]
Ich persönlich würde einfach null Rücksicht auf diesen Fall nehmen. Wer 10 Jahre alte Software einsetzt, hat dann halt falsche Länder. Das ist mir herzlich egal 🤷‍♂

**Comment by leofeyer** [comment]
Ich habe unsere Liste jetzt erstmal aktualisiert: 6c4feeeeed5314242a644b7507eaefafb8eb69d8

Bezüglich des Umbaus auf `intl` bleibe ich skeptisch. Die Leute werden nicht verstehen, dass es an ihrem Hosting liegt, und Contao die Schuld geben.

**Comment by aschempp** [comment]
> Bezüglich des Umbaus auf intl bleibe ich skeptisch. Die Leute werden nicht verstehen, dass es an ihrem Hosting liegt, und Contao die Schuld geben.

Das sehe ich leider auch so

**Comment by m-vo** [comment]
Could the [Symfony intl component](https://github.com/symfony/intl) help here? It says: `The replacement layer is limited to the locale "en".` but it still contains the data. Not sure how this works.

 see for example https://github.com/symfony/intl/blob/master/Resources/data/regions/de.json

**Comment by leofeyer** [comment]
We should definitely use the ICU Data from the Symfony Intl Component as described here:

https://symfony.com/doc/current/components/intl.html#accessing-icu-data

This way we do not have to maintain our own list of countries and languages and Symfony also supports ISO 639-2 alpha-3, which we want to support in Contao, too, in the future.

**Comment by aschempp** [comment]
Please be aware that we need a way to still locally configure countries etc. I've had clients requesting "non-existing"/non-acknowledged countries like Tibet or Taiwan because of personal beliefs...

**Comment by leofeyer** [comment]
I am not sure if that is a supported use case in the first place, but until Contao 5, the existing hooks will continue to work.

**Comment by leofeyer** [comment]
See #3138
