### ISSUE TITLE
CTE Downloads: Number of preview images also changes number of download items

### ISSUE THREAD

**Issue by mpitz** [contao/contao#7341]
### Affected version(s)

5.3.11

### Description

For the downloads content element, the number of items option is offered in the "Show preview images" settings. According to the documentation, this should specify the number of pages that should be shown, for example, from a PDF. However, the number of files to be output is also adjusted here. The number of download items should not be limited by this, however.

![image](https://github.com/contao/contao/assets/6831223/b06b0bc3-0714-4bbb-a6f5-5f2b2706a098)

**Comment by fritzmg** [comment]
`DownloadsController` is erroneously using `tl_content.numberOfItems` to limit the amount of files. However, such a feature never existed. `tl_content.numberOfItems` is used to limit the preview images per file in the downloads content element. See

https://github.com/contao/contao/blob/07375dc515cb36622c36707f3e9b83c89078b71a/core-bundle/contao/dca/tl_content.php#L142

https://github.com/contao/contao/blob/07375dc515cb36622c36707f3e9b83c89078b71a/core-bundle/contao/dca/tl_content.php#L162

@mpitz you could test by removing

https://github.com/contao/contao/blob/07375dc515cb36622c36707f3e9b83c89078b71a/core-bundle/src/Controller/ContentElement/DownloadsController.php#L51-L57

**Comment by mpitz** [comment]
@fritzmg 👍🏼 if you remove lines 51-57 it works as intended.

**Comment by asaage** [comment]
btw - what is neccessary to have this working for pdf-files?
I'm sure imagick is installed but for pdf-files i just get a pdf-icon-svg.
Probably GD is used instead of imagick.?
``` contao-console debug:container contao.image.imagine``` gives me 'Class: Imagine\Imagick\Imagine' though
