### ISSUE TITLE
CSRF cookie not deleted together with session cookie

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#7344]
### Affected version(s)

5.3.x

### Description

When you submit a form via POST, the form's data will be temporarily stored in the session for 10 seconds (so that the form data can be displayed on a subsequent success page for example). After these 10 seconds the session is automatically destroyed, as it will be empty. Since there is no session cookie anymore, the CSRF cookie will also get deleted eventually - however, this does not happen within the same response.

Ideally the deletion of the CSRF cookie should happen within the same response, I think?

### Reproduction

1. Create a form with at least one text form field and a submit button.
2. Insert the form in the front end somewhere.
3. Open the page with the form in the front end with a clear browser session (no pre-existing cookies).
4. Submit the form. The response will contain the CSRF and session cookies.
5. Wait 10 seconds.
6. Refresh the page. The response will delete only the session cookie.
7. Refresh the page again. The response will delete the CSRF cookie.

**Comment by ausi** [comment]
We’d need to implement this in the `CsrfTokenCookieSubscriber::requiresCsrf()` method by comparing every request cookie with the response cookies to see if it was deleted (by checking if `getExpiresTime()` is in the past I think?). And also additionally ignore all deleted (expired) cookies in the response.
