### ISSUE TITLE
JavaScript error after submitting a form as soon as the confirmation message is displayed

### ISSUE THREAD

**Issue by becker-ch** [contao/contao#7349]
### Affected version(s)

5.3.11

### Description

After submitting a form, an error occurs as soon as the confirmation message is displayed:
"Uncaught TypeError: document.currentScript.previousElementSibling.querySelector(...) is null"
On the confirmation page the following JavaScript-Code is included but not the form:
`<script>
    document.currentScript.previousElementSibling.querySelector('form').addEventListener('submit', e => {
      // Prevent double form submission
      if (e.submitter) {
        setTimeout(() => e.submitter.disabled = true);
        setTimeout(() => e.submitter.disabled = false, 30000);
      }
    });
  </script>`
JavaScript tries to find the form on the confirmation page, but it no longer exists. Therefore, document.currentScript.previousElementSibling.quer ySelector("form") returns null. Attempting to call addEventListener on null results in an error.

**Comment by fritzmg** [comment]
I can confirm the issue. To reproduce you need to _disable_ **Submit via AJAX** and define a **Confirmation message**.

**Comment by ausi** [comment]
This can probably be fixed by replacing `querySelector('form').addEventListener(…` with `querySelector('form')?.addEventListener(…`
