### ISSUE TITLE
Breite der Select-Menüs im Overlay Versionsvergleich

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#735]
Im Overlay zum Versionsvergleich wäre genug Platz um die beiden Select-Menüs, mit denen die zu vergleichenden Versionen ausgewählt werden, breiter zu gestalten. Dann wären die Usernames zu den Versionen auch sichtbar, wenn die Optionsliste nicht ausgeklappt ist.

**Comment by leofeyer** [comment]
Geändert in fb8219839dc8ad215c4042310e8e1a58d0762c9a.
