### ISSUE TITLE
Mixed content in frontend

### ISSUE THREAD

**Issue by cosmicbeamer** [contao/contao#7353]
### Affected version(s)

5.3.9

### Description

I am running Contao behind a Caddy proxy, the backend works without any issues, but in the frontend I get mixed content. Already set the IP of the proxy in the .env an .env.local but nothing changed. If I try to load the resources directly via https://example.com/resource.css it works.  I also tried to force https via  .htaccess  for the Apache behind the proxy, but this did not work.

**Comment by fritzmg** [comment]
You should always first update to the latest Contao version.

> but in the frontend I get mixed content

What do you mean with mixed content?

**Comment by cosmicbeamer** [comment]
I have updated to 5.3.11 – problem still present ;)

Mixed content:

[Warning] [blocked] The page at https://example.com/ was not allowed to run insecure content from http://example.com/assets/css/styles-d36a6537.css

**Comment by fritzmg** [comment]
If the original request was done via HTTPS but Contao only detects HTTP, then probably either the following is true:

* The `TRUSTED_PROXIES` environment variable does not contain the right IPs.
* The reverse proxy is not sending the appropriate `X-Forwarded-*` headers.

**Comment by cosmicbeamer** [comment]
TRUSTED_PROXIES is set to the external IPv4 of the Proxy. And  X-Forwarded-* should be ok. Used the same settings on other projects like nextcloud

–
example.com {
  reverse_proxy 1.2.3.4 {
    header_up X-Real-IP {remote_host}
    header_up X-Forwarded-For {remote_host}
    header_up X-Forwarded-Proto {scheme}
    header_up X-Forwarded-Host {host}
    header_up X-Forwarded-Port {server_port}
  }
–

**Comment by cosmicbeamer** [comment]
Adding  `
header {
  Content-Security-Policy "upgrade-insecure-requests;"
}
` to the Caddy config solved the problem.
