### ISSUE TITLE
Fresh installation of 5.4 not possible

### ISSUE THREAD

**Issue by aschempp** [contao/contao#7354]
### Affected version(s)

5.4.x-dev

### Description

Unfortunately, the changes in https://github.com/contao/contao/commit/ce48ebc5f69ee658f6ef357fc3c87fd2dbc36f79 seem to break a new installation. `contao:symlinks` tries to create symlinks to paths that have not yet been created in the `contao:install` command now (/system/modules/ in my case).

Related: https://github.com/contao/contao/pull/7094

**Comment by leofeyer** [comment]
Ah, yes, I forgot to debug and fix this 🤦‍♂️
