### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by xApep** [contao/contao#7361]
### Affected version(s)

5.3.11

### Description

Not sure what is going on but...this is error which I get on every backend change / articles / pages / form fields - well I think every change really.

![image](https://github.com/user-attachments/assets/bc4304f7-e64e-4148-bbfd-417e80d1ad8a)

For instance, I work in backend and then refresh frontend to see changes, it works ok, then when I repeat that, I get error above. Currently I'm at domain.com/sl. Then If I go to domain.com it redirects me to domain.com/en (which is ok) and it works. Then if I get back to domain.com/sl it works fine, until I repeat: backend changes and refresh the frontend.

This is not tight to browser, because when I got error, I tried to open the same link in another browser and the error was still there, until I went to domain.com/en

Edit 1:
I have notice that this error happens only if after backend changes I try to refresh Home of second Website root. If after edit I refresh any other page, everything is ok.

Edit 2:
Edit 1 is kinda invalid, since I also experience the same on other pages but not that often as on Edit 1 (home) it happens every time

**Comment by zoglo** [comment]
Could it be that you have setup custom `.htaccess` redirects?
Maybe it's also a hosting issue with redirecting to `https` and/or `www`?

**Comment by xApep** [comment]
Unfortunately nothing from above. This is on our "dev" server, no settings or redirects (the only htaccess is the one that contao installed it) but until 5.3, everything was working fine.

Maybe we have something wrongly in website root settings?
![screencapture-imas-edsolution-si-contao-2024-07-23-13_51_16](https://github.com/user-attachments/assets/fb2c5e5c-c802-4972-b880-3561ebf6eda9)
![screencapture-imas-edsolution-si-contao-2024-07-23-13_50_54](https://github.com/user-attachments/assets/20d74847-48d6-4317-8fc5-bf76563ff238)
![root-en](https://github.com/user-attachments/assets/9e5eb763-80cf-4bd6-bc7b-66a904a4fafe)

**Comment by fritzmg** [comment]
You did not set a domain name. And are you really accessing the site without https?

**Comment by xApep** [comment]
Do I need to set domain name, since every language is under the same domain?

I have now set https for all website roots

**Comment by fritzmg** [comment]
> Do I need to set domain name, since every language is under the same domain?

Setting a domain is always recommended.

**Comment by xApep** [comment]
Thanks. I will test it more and come back with new conclusions =)

**Comment by fritzmg** [comment]
Closing, as there is no evidence for a bug in Contao itself and likely just a configuration error.
