### ISSUE TITLE
Compression not working under the Contao

### ISSUE THREAD

**Issue by xApep** [contao/contao#7363]
### Affected version(s)

5.3.11

### Description

Not really sure what is going on, but let me try to explain =)

This is test of gzip compression where tested link domain.com is Contao website
![image](https://github.com/user-attachments/assets/7a3a942f-d4fd-44bf-b4fd-33210ae663d8)

This is test of gzip compression where tested link domain.com/pi.php is not Contao website
![image](https://github.com/user-attachments/assets/746999cb-4d38-4afd-8fc7-7d66c03a1d24)

Both tested links are on the same hosting account, etc. - pi.php lives in public/pi.php where public is also a document root for Contao

Also this is phpinfo from pi.php
![image](https://github.com/user-attachments/assets/f7131b67-52ef-48df-bad0-4e345d38ad79)

**Comment by fritzmg** [comment]
@xApep please use the Contao Community forum or the community Slack. All your recent issues are very likely not related to the Contao core.

**Comment by zoglo** [comment]
This is unrelated to contao.

@xApep you have to enable the compression for your server on your own.
You may find more information regarding this in some FAQ of your hoster.

**Comment by xApep** [comment]
compression (zlib) is enabled as you can see from phpinfo() and also from the test of pi.php which is at the same location as whole Contao website - so I'm not really sure how this could be related to server settings. It kinda looks like that Contao does some tricks which "disabled" compressions?

**Comment by xApep** [comment]
Thanks to @zoglo and @ausi we have found the solution. 
One thing is to set apache config or add this to htaccess

```
AddOutputFilterByType DEFLATE text/html text/plain text/css application/json
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE text/xml application/xml text/x-component
AddOutputFilterByType DEFLATE application/xhtml+xml application/rss+xml application/atom+xml
AddOutputFilterByType DEFLATE image/x-icon image/svg+xml application/vnd.ms-fontobject application/x-font-ttf font/opentype
```
