### ISSUE TITLE
Hotwired turbo throws an error when loading records with a `TinyMCE` field

### ISSUE THREAD

**Issue by zoglo** [contao/contao#7368]
### Affected version(s)

5.4.0-RC1

### Description

Creating e.g. a new form ends up showing a white page because other scripts overwrite the document such as TinyMCE in this line:
https://github.com/contao/contao/blob/287b2b03faf4d4910859782eed19ede95ebbd21f/core-bundle/contao/templates/backend/be_tinyMCE.html5#L7-L9

~~due to hotwired turbo trying to remove the progress bar before the html has been loaded completely.~~

**Comment by fritzmg** [comment]
I could reproduce the issue once - but not consistently. Looks like there is a race condition.

**Comment by zoglo** [comment]
> I could reproduce the issue once - but not consistently. Looks like there is a race condition.

Basically happens when clearing cache and creating a new element, yup

**Comment by m-vo** [comment]
I was not able to reproduce the behavior even with clearing/nuking the cache before.

Does this happen with/because of prefetching or always? You could try to disable it by always calling `e.preventDefault()` in our `turbo:before-prefetch` event listener.

**Comment by zoglo** [comment]
@m-vo even with just `import '@hotwired/turbo'` included, this happens.
~~Just assuming but what would happen if we'd add the script after the body itself.~~ (Same thing)

**Comment by fritzmg** [comment]
@zoglo prefetch is enabled by default

**Comment by zoglo** [comment]
So basically disabling it like this did not help.
> Does this happen with/because of prefetching or always? You could try to disable it by always calling e.preventDefault() in our turbo:before-prefetch event listener.

Using the meta tag do disallow prefetching did not help:
> https://turbo.hotwired.dev/handbook/drive#prefetching-links-on-hover

It also didn't help to disable it as an attribute:
```html
<a href="/contao?do=form&amp;act=create&amp;rt=abcdefg&amp;ref=1234567" class="header_new" accesskey="n" data-action="contao--scroll-offset#store" data-turbo-prefetch="false" title="Create a new form">New</a>
```

What did help was completely disabling the Turbo.session.drive
> https://turbo.hotwired.dev/reference/drive#turbo.session.drive

**Comment by zoglo** [comment]
^ Might be related to:
https://github.com/contao/contao/blob/287b2b03faf4d4910859782eed19ede95ebbd21f/core-bundle/contao/templates/backend/be_tinyMCE.html5#L7-L9

Not loading the tinymce prevents this from happening.

**Comment by fritzmg** [comment]
May be we'll need to implement https://github.com/contao/contao/pull/7011#issuecomment-2209479639 after all - for now anyway?

**Comment by zoglo** [comment]
I know it may sound very simple and stupid but why not just add ACE and TinyMCE to the global scripts within be_main.html5?

We'll always have to deal with race conditions due to how Turbo renders the logic after the page has been fetched.

E.g. using something like
```js
if (!window.tinymce) {
  const tinymce = document.createElement('script');
  tinymce.setAttribute('src', '<?= $this->asset('js/tinymce.min.js', 'contao-components/tinymce4') ?>');
  window.document.head.append(tinymce);
}
```
Would add the script to the head (for the prefetch and the normal visit), we'll still have to wait for it to be loaded so most likely a MutationObserver on the tinymce fields waiting till window.tinymce exists.

We already do it here:
https://github.com/contao/contao/blob/287b2b03faf4d4910859782eed19ede95ebbd21f/core-bundle/assets/scripts/modulewizard.js#L180

Most simple and stupid solution however:
Directly adding Ace and TinyMCE to the `be_main.html5`

**Comment by m-vo** [comment]
> May be we'll need to implement https://github.com/contao/contao/pull/7011#issuecomment-2209479639 after all - for now anyway?

I think that might be the most straightforward solution for now, yes. Did any of you check if this actually solves this issue?

> We already do it [MutationObersver] here

Also every stimulus controller is basically one (which to me is also the easiest way to use one).

> I know it may sound very simple and stupid but why not just add ACE and TinyMCE to the global scripts within be_main.html5?

Not opposed to this as well. As long as they're not initialized with a DOM element they probably don't take up any resources.

**Comment by zoglo** [comment]
Nonetheless, the usage of `document.write()` should be removed and replaced by something else.

Even the Spec warns about it, perfectly describing the issue we have:
https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#document.write()

> [!WARNING]  
> In other cases, the call can clear the current page first, as if [document.open()](https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-document-open) had been called.

Also here: https://developer.mozilla.org/en-US/docs/Web/API/Document/write

> [!NOTE]  
> Note: Because `document.write()` writes to the document **stream**, calling `document.write()` on a closed (loaded) document automatically calls `document.open()`, [which will clear the document](https://developer.mozilla.org/en-US/docs/Web/API/Document/open#notes).

**Comment by fritzmg** [comment]
> I think that might be the most straightforward solution for now, yes. Did any of you check if this actually solves this issue?

Well, it doesn't - there is actually no support for `$GLOBALS['TL_HEAD']` in the back end.

**Comment by zoglo** [comment]
Should we use
1. `window.document.head.append` and include a mutationObserver
2. include `tinymce.js` and `ace.js` within `be_main.html5`?

The `be_main` includes would be BC-friendly because `window.tinymce` and `window.ace` would exist, thus most likely never triggering the `document.write()`. (Yeah, people should always keep their templates up to date between minors 😄)

**Comment by fritzmg** [comment]
We should probably go for adding it to `be_main` 👍

**Comment by leofeyer** [comment]
Let‘s try @zoglo‘s [proposed solution](https://github.com/contao/contao/issues/7368#issuecomment-2254537299) 👍

**Comment by leofeyer** [comment]
Will this still work if TinyMCE is loaded via Ajax in a subpalette?

**Comment by fritzmg** [comment]
Yes, if we simply generally add the scripts to the `<head>` in `be_main` we don't need `document.write` anymore.

**Comment by zoglo** [comment]
![image](https://github.com/user-attachments/assets/3ba5f204-6cc1-48ba-acd1-4a42ab254ca0)
I guess this should explain it @leofeyer :)

Since it's in `be_main`, it will always exist

**Comment by fritzmg** [comment]
The picker has nothing to do with it though?

**Comment by zoglo** [comment]
Understood it incorrectly - Yeah, you are right. However it would always be loaded in be_main and will always be available as fritz said
