### ISSUE TITLE
ALTCHA captcha not working in unsafe environments within chromium based browsers

### ISSUE THREAD

**Issue by zoglo** [contao/contao#7369]
### Affected version(s)

5.4.0-RC1

### Description

The newly introduced ALTCHA captcha uses parts of the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) / https://www.chromium.org/blink/webcrypto/ that do not work within unsafe origins (e.g. `http://`)

Here is a list of safe origins:
| [Safe origins](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/security/faq.md#which-origins-are-secure) |
| -- |
| (https, *, *) |
| (wss, *, *) |
| (*, localhost, *) |
| (*, 127/8, *) |
| (*, ::1/128, *) |
| (file, *, —) |
| (chrome-extension, *, —) |

More information here as well:
https://stackoverflow.com/questions/57146558/typeerror-digest-of-undefined-in-development-environment

### Proposal

This could be considered as a known limitation within LIMITATIONS.md

**Comment by ausi** [comment]
As we know if the page is served via HTTP or HTTPS when the widget gets rendered, should we skip the widget in that case? Or maybe replace it with the `FormCaptcha` widget?

**Comment by zoglo** [comment]
I was thinking if it would be necessary to show a message for the ALTCHA widget itself, however, this looks like a limitation to me since this only affects chromium based browsers :)

**Comment by leofeyer** [comment]
It is a known limitation IMHO.

**Comment by ausi** [comment]
> this looks like a limitation to me since this only affects chromium based browsers :)

it affects all browsers AFAIK.

> It is a known limitation IMHO.

but we still should fix that the form gets completly broken on HTTP, right?

**Comment by zoglo** [comment]
True - The Altcha won't verify due to the JavaScript throwing an error. That the user can't submit the form.

I see two ways of fixing this (+ the documented limitation)

* Fallback to the normal captcha as ausi suggested
* Adding a message in the widget itself

**Comment by aschempp** [comment]
Falling back to the regular Captcha sounds reasonable to me?

**Comment by fritzmg** [comment]
imho we do not need such a fallback.

**Comment by zoglo** [comment]
Either a message or a fallback. The usual Layer 8 does not check the limitations.md

**Comment by fritzmg** [comment]
imho we do not need to fail gracefully/silently here at all. We could also just do

```php
if (!$request->isSecure()) {
    throw new \RuntimeException('The ALTCHA widget cannot be used with an unencrypted connection.');
}
```

**Comment by Toflar** [comment]
I don't think we should throw an exception. The form can be perfectly used and tested on unsecured dev environments. But maybe it should just output the info `The ALTCHA widget requires an HTTPS connection in order to have access to the required browser APIs, thus protection has been disabled.` in it's `generate()` method?

**Comment by leofeyer** [comment]
But then there would be no protection at all if the insecure environment happens to be a prod environment.

**Comment by Toflar** [comment]
Imho an `http`-only site in production is not a use case we need to worry about. If someone wants to invest time in this, feel free because I certainly won't 😄

**Comment by leofeyer** [comment]
I kind of agree with that. @ausi WDYT?

**Comment by fritzmg** [comment]
My other thought was to not render the widget and instead just generate a log message in the system log, that would be easy enough as well and gives some more direct feedback (if someone looks for it).

**Comment by ausi** [comment]
> My other thought was to not render the widget and instead just generate a log message in the system log

I like this solution best 👍

**Comment by aschempp** [comment]
why are we trying to make stuff hard for users intentionally?

> Either a message or a fallback. The usual Layer 8 does not check the limitations.md

Fully agree with that. Neither do they check the logs (until its too late and they get spammed maybe).

**Comment by leofeyer** [comment]
Please note that `localhost` and `*.localhost` domains even work with HTTP connections (see https://github.com/altcha-org/altcha/issues/43#issuecomment-2197096134), so the number of affected websites is even lower than we thought.

I suggest to show the following warning when the connection is insecure:

<img width="758" alt="" src="https://github.com/user-attachments/assets/212c1ee4-a879-40e8-80e0-d5027e88fc15">

**Comment by fritzmg** [comment]
Fine with me too. I am mainly against silently falling back to a completely different widget.

**Comment by Toflar** [comment]
I am happy with the message, as already proposed in https://github.com/contao/contao/issues/7369#issuecomment-2256050904. It's the easiest and most comprehensible way for users.
