### ISSUE TITLE
Template source is misleading (for front end modules)

### ISSUE THREAD

**Issue by jc97** [contao/contao#737]
**Affected version(s)** Contao 4.x

**Description**  

On creating or editing a front end module you can usually select a template for the front end (e.g. news template for a news list). The drop down list contains all available templates. Thereby the template path of the corresponding front end theme is not correctly considered. 

**How to reproduce**  

Create two template folders, e.g. `/test1/`  and `/test2/`. Overwrite a core template in `/test1/`, e.g. `news_latest`. Afterwards, create two front end themes, e.g. *test1* and *test2*. Assign `/test1/` as template folder for theme *test1* and `/test2/` for theme *test2*. Create a front end module corresponding to the template, e.g. a news list. Now, the available templates are shown in drop down field *news template*. For the overwritten template `news_latest` it will show *test1* in brackets behind the template name as template source. But this is not correct. In the front end Contao will use the template provided by the bundle, because the overwritten template is stored in a path not assigned to the theme. This behaviour is correct! But the user might assume that the template in `/test1/` is used.

Additionally, Contao offers templates with adapted names from other template folders too (e.g. `/test1/news_latest_custom`. This template shouldn't be offered for a module created in theme *test2*.

**Comment by leofeyer** [comment]
So both problems are caused by Contao offering templates from theme "test1" in the module in theme "test2", correct?

**Comment by aschempp** [comment]
That's what I understand as well. We can't fix this everywhere though, as some places the template selection is not related to a specific theme. Also, copying a module from one theme to another would not change the existing template selection. Maybe we should just improve the wording?

**Comment by jc97** [comment]
Yes, this is the problem. 

At least, Contao should show all possible sources in brackets. Additionally, I suggest showing only the available templates. On copying a module it could be accessed anyway (not good, but working, I guess).
