### ISSUE TITLE
Redundant ARIA labels

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#7388]
### Affected version(s)

5.4

### Description

<img width="786" alt="" src="https://github.com/user-attachments/assets/4e62c4d5-25a0-4484-a7fd-9b7a883a290e">

The [best practices](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/navigation_role#best_practices) advise us not to describe the role of a landmark in its label because it may be announced redundantly.

While this kind of works in English, it does not in German. The label would have to be `Haupt` so that the screen reader reads out `Haupt Navigation` in the best case. (It could also read out `Navigation Haupt`, depending on whether the role or the label is read first.) However, the correct word would be `Hauptnavigation` or `Hauptmenü` anyway.

So even though it may be announced redundantly, I tend to use `aria-label="Hauptnavigation"` instead of `aria-label="Haupt"`. The latter just does not make sense to me. @contao/developers WDYT?

**Comment by fritzmg** [comment]
May be @NinaG or @teviii can give some feedback here? Surely there must be some best practices regarding translations of ARIA roles and labels in different languages?

**Comment by leofeyer** [comment]
@ausi ran some tests and this is the voice-over result in Firefox:

![](https://github.com/user-attachments/assets/31c10a25-cee3-4c9c-9436-0834d48d923f)

We then discussed a possible solution:

* Link, Navigation überspringen, **Hauptmenü**, Navigation
* Link, Navigation überspringen, **Navigationspfad**, Navigation
* Link, Navigation überspringen, **Kopfzeile**, Navigation
* Link, Navigation überspringen, **Fußzeile**, Navigation
* Link, Navigation überspringen, **Paginierung**, Navigation

This would work in English and German, but I don‘t know if it can be adapted in other languages as well.

**Comment by leofeyer** [comment]
I‘m a little disappointed that none of our "accessibility experts" cared to contribute their knowledge. Meanwhile Contao 5.4 has been released, so I‘m closing the ticket now. But I will be happy to reopen it if there is any feedback in the future.
