### ISSUE TITLE
Inhaltselement Typ Code: 2 Templates, eines Standard, und eines, um langen Codeblock ausblendbar zu machen

### ISSUE THREAD

**Issue by Nightwing0815** [contao/contao#739]
Hallo,

wie [hier schonmal beschrieben](https://community.contao.org/de/showthread.php?74140-moo_accordion-bei-Klick-nach-oben-scrollen&p=510284&viewfull=1#post510284), wäre es mMn nicht schlecht, grossen und somit langen Inhalt vom Typ Code ausblendbar zu machen, schliesslich wird Code + Syntaxhighlightning im Contao angeboten, und oft hat man ja langen Code stehen (= bestes Beispiel im Contao Forum ).
Ich denke, das macht es angenehmer für den Betrachter...

Für mich habe ich das ce_code.html5 Template umgestrickt und verdoppelt, sodas ich sowohl wenige Codezeilen ohne Box aber viele versteckt in der Box anzeigen kann (= [Beispiel hier](https://nightwing.eu/cms-contao/codewrapper/) ).
Zwei Templates, etwas CSS und ein Script (= abgewandeltes moo_accordion.html5)
Finde ich persönlich sexyer und weniger mühsam, wie das Element z.B. in das Element Typ Umschlag zu stecken ;-)

Die Files verlinke ich, da der Code hier nicht sauber dargestellt wird (= rechte Mausetaste, Ziel speichern...):
[ce_code_nowrap.html5](https://nightwing.eu/files/files/contao/ce_code_nowrap.html5)
[ce_code_wrapper.html5](https://nightwing.eu/files/files/contao/ce_code_wrapper.html5)
[moo_codewrapper.html5](https://nightwing.eu/files/files/contao/moo_codewrapper.html5) ***
[codewrapper_layout.css](https://nightwing.eu/files/files/contao/codewrapper_layout.css)

Hier noch ein Beispiel mit teils langen Codeblöcken, daran sieht man den Vorteil: [click me softly](https://nightwing.eu/cod-2/standalone-anti-camper-mod/), bzw. zwei Bilder hier:

Langer Code ausgeblendet:
![1](https://user-images.githubusercontent.com/54181775/64549117-53d6fc80-d330-11e9-92fd-5c2b7f952514.PNG)

Eingeblendet zum Lesen:
![2](https://user-images.githubusercontent.com/54181775/64549118-546f9300-d330-11e9-830b-91eac3ee1321.PNG)

ToM

*** Die Scrollfunktion ist noch nicht ganz nach meinem Empfinden, es spackt rum, wenn man eins geöffnet hat, weiterliest und dann logischerweise ein neues öffnet (das dann das zuerst gewählte schliesst)...

**Comment by leofeyer** [comment]
Wir haben das Ticket besprochen und sind der Meinung, dass es die Aufgabe des Themes ist, die Codeblöcke sinnvoll im Frontend darzustellen.

Ich persönlich finde die beiden Screenshots mit den eingeklappten Code-Blöcken auch in keiner Weise weniger verwirrend oder besser lesbar als mit ausgeklappten Code-Blöcken. Hier müsste auf jeden Fall das UX nochmal überarbeitet werden. Außerdem müsste aus diesem Ticket ein richtiger Pull-Request gemacht werden, damit man nachvollziehen kann, was genau geändert wurde.

Alles in allem lohnt sich der Aufwand aber nicht, daher schließe ich – auch aufgrund des fehlenden Interesses – das Ticket.

**Comment by Nightwing0815** [comment]
Vielen Dank, das Ihr Euch damit auseinandergesetzt habt!
