### ISSUE TITLE
Page layout - Custom JavaScript code multiple lines

### ISSUE THREAD

**Issue by berecont** [contao/contao#7399]
### Affected version(s)

5.4.0-RC2

### Description

there are 1 or more Custom JavaScript code lines - all numbered with #1 
Click `Save` » the next one will added. Numbered with #1 too
Click `Save and close` and reopen » the number of lines plus one more will be shown

local Installation Laragon, Windows 11
php82

**Comment by m-vo** [comment]
Can confirm this. Seems like another Turbo issue. :disappointed:

**Comment by m-vo** [comment]
Apparently the same happens when you are in an edit mask that contains chosen select fields (e.g. a text element), then navigate away without saving (e.g. click 'Forms'), then use the browser's history back function: now there is an additional select dropdown each.

**Comment by leofeyer** [comment]
I stumbled across that too.

**Comment by m-vo** [comment]
See #7408.
