### ISSUE TITLE
Remove the changelog view in backend

### ISSUE THREAD

**Issue by aschempp** [contao/contao#74]
I think we should get rid of this "feature". According to @leofeyer people use it to see what changed **after** a live-update. I think that's totally wrong, because it would be way more useful then to check **before** a live-update, but thats not possible.

We could keep the icon/link but simply point it to https://contao.org/de/changelog.html

**Comment by Toflar** [comment]
:+1: It's not something that belongs to a CMS anyway^^

**Comment by leofeyer** [comment]
Full ACK.

**Comment by xchs** [comment]
> We could keep the icon/link but simply point it to https://contao.org/de/changelog.html

If necessary, we should point it to https://contao.org/changelog.html (i.e. without the language string as first URL parameter), since you will be forwarded automatically depending on the browser language.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/152.
