### ISSUE TITLE
Weird error in symfony routing (only with curl)

### ISSUE THREAD

**Issue by pgerundt** [contao/contao#740]
This one is a really crazy bug:

- Create two website roots in different languages (e.g. "de" and "en")
- Create a page with identical alias in both languages (e.g. "main")
- Create a subpage in both languages with different aliases (e.g. "main/sub-de" and "main/sub-en")

The page tree should look like this:
```
de [root]
- main (main.html)
- - sub-de (main/sub-de.html)
en [root]
- main (main.html)
- - sub-en (main/sub-en.html)
```
You can access all four pages in your browser, but...
if you try to call them via curl (e.g. https://onlinecurl.com/), one of the subpages returns a 404.
(It depends on which main-page was created first.)

I guess contao/symfony "selects" the wrong "main"-page and cannot find the subpage in the wrong language. I don't know why it works in the browser.

Can anyone confirm?
I would love to debug this. Can someone give me a hint where to look?

**Comment by xchs** [comment]
Did you test this with Contao 4.8.2?

**Comment by pgerundt** [comment]
Nope, only 4.7.7 at the moment.

**Comment by fritzmg** [comment]
@pgerundt bevor posting bugs, you must always update to the latest Contao version. In your case 4.4.43

**Comment by pgerundt** [comment]
There was a typo in my comment. The affected version is 4.7.7 - but I will check it on 4.8.x as well.

**Comment by Toflar** [comment]
Do you send the `Accept: text/html` header in your tests?

**Comment by pgerundt** [comment]
To be honest: I don't know.
It shouldn't matter because the bug came up when we tried to post website urls on Facebook, Xing, LinkedIn, ...
All websites responded with an error.

**Comment by Toflar** [comment]
Well, the correct HTTP headers matter. Because that's how the Internet works...

**Comment by xchs** [comment]
> Create a page with identical alias in both languages (e.g. "main")

How did you manage that? Did you enable `prepend_locale` as well?

**Comment by pgerundt** [comment]
> Well, the correct HTTP headers matter. Because that's how the Internet works...

So Facebook, Xing and LinkedIn are using the "wrong" HTTP headers? And it works with links from any website - except ones from contao-driven sites?

**Comment by pgerundt** [comment]
> > Create a page with identical alias in both languages (e.g. "main")

> How did you manage that? Did you enable `prepend_locale` as well?

No. I used different domains for both sites.

**Comment by Toflar** [comment]
> So Facebook, Xing and LinkedIn are using the "wrong" HTTP headers? And it works with links from any website - except ones from contao-driven sites?

I didn't say that. Every server may handle every request differently. But if you do not send `Accept: text/html` you are not asking for HTML content === you do not behave the same as a browser. So for example there's no point in redirecting such a request to the Contao 404 page because Contao can only handle HTML requests and responses. Maybe your Symfony application also handles JSON or XML. It would make no sense to reply with Contao's 404 page to a JSON request.

**Comment by pgerundt** [comment]
Give me a second to set up a 4.8.x contao and provide you with a link...

**Comment by pgerundt** [comment]
Ok guys, here we go:

```
http://contao-latest-de.showroom.efficient.it/main/sub-de.html
http://contao-latest-en.showroom.efficient.it/main/sub-en.html
```

Now try to curl `http://contao-latest-de.showroom.efficient.it/main/sub-de.html` from your console, try it with https://onlinecurl.com/, try to post it on Xing ("Ungültige bzw. nicht unterstützte URL"), on Facebook ("An Error Occured: Not Found") or LinkedIn ("Vorschau kann nicht geladen werden. Sie können den Link so veröffentlichen, wie er ist, oder einen anderen Link verwenden.").

**Comment by pgerundt** [comment]
> So for example there's no point in redirecting such a request to the Contao 404 page because Contao can only handle HTML requests and responses. Maybe your Symfony application also handles JSON or XML. It would make no sense to reply with Contao's 404 page to a JSON request.

Sorry, I did not want to be rude.
Oh, Contao DOES reply with a 404 page (if it exists).

So to sum this up:
Access `http://contao-latest-de.showroom.efficient.it/main/sub-de.html` via browser => response with requested page
Call `http://contao-latest-de.showroom.efficient.it/main/sub-de.html` via Curl, post the url on social media => response with 404 or contao's 404 page

**Comment by Toflar** [comment]
I think we have a different issue here. The issue is that the `Accept-Language` header is missing. If you do `curl http://contao-latest-de.showroom.efficient.it/main/sub-de.html` you get a 404. If you do `curl -H "Accept-Language: de" http://contao-latest-de.showroom.efficient.it/main/sub-de.html`, it works fine.
Did you double check the language settings and fallback configuration is correct?

**Comment by ausi** [comment]
I can confirm this issue. The problem occurs if the `Accept-Language` of the client doesn’t match any language of the two root-pages.

@pgerundt can you please change the languages of your two root pages to `zh` and `ja`. If I’m correct the 404 page should then also be shown in the browser.

**Comment by ausi** [comment]
Looks like there is something wrong with the matching of the route.

Instead of matching the page `main/sub-de` it matches the parent `main` and keeps `/sub-de` as a parameter which then results in a 404 because the parameter doesn’t get used.

**Comment by pgerundt** [comment]
> @pgerundt can you please change the languages of your two root pages to `zh` and `ja`. If I’m correct the 404 page should then also be shown in the browser.

@ausi is right. Changing the languages to `zh` and `ja` shows a 404 in the browser:
http://contao-latest-de.showroom.efficient.it/main/sub-de.html

**Comment by leofeyer** [comment]
A few things are odd here:

1. Which of the website root pages did you define as language fallback?

2. The alias `main/sub-de` will only work if you enable `folderUrl`, which I assume you did?

3. It should not be possible to create two pages with the same alias (`main`) without enabling `contao.prepend_locale` (aka `addLanguageToUrl`), so I assume that you did, didn't you? However, if you did, `/main/sub-de.html` should forward you to `/de/main/sub-de.html`.

@ausi How did you configure Contao to reproduce this issue?

**Comment by xchs** [comment]
@leofeyer He did set two different domains for the website root pages.

**Comment by pgerundt** [comment]
@leofeyer 

> 1. Which of the website root pages did you define as language fallback?


Both of the root pages are set as language fallback. Because they use different domains (`contao-latest-de` and `contao-latest-en`). Otherwise an error is displayed.

> 2. The alias `main/sub-de` will only work if you enable `folderUrl`, which I assume you did?

This is correct, `folderUrl` is enabled.


> 3. It should not be possible to create two pages with the same alias (`main`) without enabling `contao.prepend_locale` (aka `addLanguageToUrl`), so I assume that you did, didn't you? However, if you did, `/main/sub-de.html` should forward you to `/de/main/sub-de.html`.

It is possible if you use two different domains.



Feel free to check or play around with the settings:

http://contao-latest.showroom.efficient.it/contao
username: `admin`
password: `Issue#740`

**Comment by leofeyer** [comment]
> He did set two different domains for the website root pages.

I missed that, thanks for the heads up. I can reproduce it now.

<img width="790" alt="" src="https://user-images.githubusercontent.com/1192057/64676170-4a0ae180-d475-11e9-9774-b30b99e707ee.png">

Does not seem to be a route matching issue though.

**Comment by ausi** [comment]
In my test the route for `/main.html` matched which is `tl_page.4` in my case.

<img width="649" alt="Bildschirmfoto 2019-09-11 um 09 29 23" src="https://user-images.githubusercontent.com/367169/64676858-bfc37d00-d476-11e9-8d60-5bb5541eaeaa.png">

<img width="645" alt="Bildschirmfoto 2019-09-11 um 09 29 34" src="https://user-images.githubusercontent.com/367169/64676867-c3ef9a80-d476-11e9-94fd-a40f4c5b373e.png">

**Comment by leofeyer** [comment]
So this is where the issue occurs:

https://github.com/contao/contao/blob/0b2823089a027c0ad2b3897fe769f6fae2b8a31f/core-bundle/src/Routing/RouteProvider.php#L87-L90

`$candidates` is `['main/sub-de', 'main']` and `$pages` is `['main', 'main/sub-de']`, so the route collection eventually has `['/main{parameters}.html', '/main/sub-de{parameters}.html']`. And since the first match wins, it will be `main` instead of `main/sub-de`.

**Comment by leofeyer** [comment]
See #744.
