### ISSUE TITLE
Unable to submit / save new elements with tinyMCE

### ISSUE THREAD

**Issue by zoglo** [contao/contao#7402]
### Affected version(s)

5.4.0-RC2

### Description

When trying to save a new `text-element`, you can't save / submit the form due to following validation error in the developer console:
```js
An invalid form control with name='text' is not focusable.
```
The textarea for `text` is required but is set to `display: none`, thus not being focusable.

There's also an issue on trying to update mandatory fields using TinyMCE

Related issue on TinyMCE:
https://github.com/tinymce/tinymce/issues/2584

Related commit of a former fix:
https://github.com/Probesys/bileto/commit/5d1e324fc87082be6fcc20286c06fa1a8fea43ef
> This commit also explains that it may be a side effect of turbo in their case and it removes the required attribute

/cc @m-vo

**Comment by m-vo** [comment]
See #7408.
