### ISSUE TITLE
Delayed "confirm to leave"

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#7403]
### Affected version(s)

5.4.x

### Description

Unfortunately there is one additional (somewhat cosmetic) issue that arises with Turbo: the JavaScript pop-up to confirm that you want to leave the page will be "delayed". Try the following:

* Create a new `text` content element.
* Enter some text in the **Text** TinyMCE, but don't save.
* Hover over Content » Forms (to prefetch), then click on Content » Forms (issue might also arise without prefetch).
* Click to edit a form or its form fields.

The JavaScript pop-up to confirm to leave the page (originating from entering a text in the TinyMCE of the `text` content element from before) will now show.

<img src="https://github.com/user-attachments/assets/1e779c2b-051c-4edc-82f1-377a99b8da47" width="400">

**Comment by m-vo** [comment]
Can confirm, will look into this.

**Comment by fritzmg** [comment]
The message likely stems from the TinyMCE [`autosave`](https://www.tiny.cloud/docs/tinymce/latest/autosave/) plugin. Ideally we would need to trigger this after one of the turbo events (but it also needs to prevent turbo from rendering). Not sure that is possible, at least there does not seem to be a way to hook into that 🤔

**Comment by m-vo** [comment]
It works in theory with something like this:

```js
window.addEventListener("turbo:before-visit", (event) => {
    if(!window.dispatchEvent(new Event('beforeunload', {cancelable: true})) && !confirm('Discard unsaved changes?')) {
        event.preventDefault();
    }
})
```

But not sure if it's a good idea to create the confirm message ourselves or if there are edge cases to this where you do not want to issue the event.

**Comment by m-vo** [comment]
See #7408.
