### ISSUE TITLE
Markdown Content Element does not encode email addresses

### ISSUE THREAD

**Issue by richardhj** [contao/contao#7414]
### Affected version(s)

5.3.x

### Description

E-mail addresses in markdown are not HTML encoded.

I assume this is related to the new twig templates, even though not verified.

Reproducable in the Contao online demo with default Markdown content element and twig template.

<img width="1196" alt="Screenshot 2024-08-05 at 20 26 26" src="https://github.com/user-attachments/assets/e62d5265-e2ab-4627-baf5-5d0b4327661d">

**Comment by leofeyer** [comment]
Did you use the `{{email::}}` insert tag?

**Comment by Toflar** [comment]
See https://github.com/contao/contao/pull/7416
