### ISSUE TITLE
Fehlende Übersetzung und Beschreibung bei Inhaltselementen (overwriteLink, youTubeOptions, vimeoOptions, … )

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#742]
**Affected version(s)**
Contao 4.8

**Description**  
Ein neues Download-Element erstellen und den Bereich "Download-Einstellungen" öffnen. Hier fehlt die Übersetzung und Beschreibung bei "overwriteLink"

![fehlende-uebersetzung](https://user-images.githubusercontent.com/23719181/64598720-77de2080-d3b8-11e9-8730-b081e4925864.jpg)

**Comment by leofeyer** [comment]
Dasselbe gilt auch für das Feld `skipEmpty` in den Formulareinstellungen:

<img width="766" alt="" src="https://user-images.githubusercontent.com/1192057/64599208-4154d580-d3b9-11e9-8d0a-396649b16ea8.png">

Unter "Restore" -> "Show details" fehlen ebenfalls ein paar Übersetzungen:

<img width="407" alt="" src="https://user-images.githubusercontent.com/1192057/64599258-57fb2c80-d3b9-11e9-88ce-67bd8a993871.png">

Und das Feld `tl_content.headline` wird scheinbar unter "Restore" -> "Show details" gar nicht angezeigt? 🤔

**Comment by contaoacademy** [comment]
Ja, Vimeo und YouTube ist mir auch gerade aufgefallen, ich werde dazu kein eigenes Ticket erstellen und habe mal den Titel geändert.

**Comment by leofeyer** [comment]
Behoben in 0b2823089a027c0ad2b3897fe769f6fae2b8a31f.
