### ISSUE TITLE
Incorrect SQL queries in combination with mysql-8.0.17

### ISSUE THREAD

**Issue by syntaxys** [contao/contao#743]
**Affected version(s)**
tested with latest 4.7 and 4.8

**Description**
MySQL added reserved word MEMBER in 8.0.17. The installation script terminates, e.g. in case of the following query.

**How to reproduce**  

_CREATE TABLE tl_comments (id INT UNSIGNED AUTO_INCREMENT NOT NULL, tstamp INT UNSIGNED DEFAULT 0 NOT NULL, source VARCHAR(32) DEFAULT '' NOT NULL, parent INT UNSIGNED DEFAULT 0 NOT NULL, date VARCHAR(64) DEFAULT '' NOT NULL, name VARCHAR(64) DEFAULT '' NOT NULL, email VARCHAR(255) DEFAULT '' NOT NULL, website VARCHAR(128) DEFAULT '' NOT NULL, member INT UNSIGNED DEFAULT 0, comment TEXT DEFAULT NULL, addReply CHAR(1) DEFAULT '' NOT NULL, author INT UNSIGNED DEFAULT 0 NOT NULL, reply TEXT DEFAULT NULL, published CHAR(1) DEFAULT '' NOT NULL, ip VARCHAR(64) DEFAULT '' NOT NULL, notified CHAR(1) DEFAULT '' NOT NULL, notifiedReply CHAR(1) DEFAULT '' NOT NULL, INDEX published (published), INDEX source_parent_published (source, parent, published), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC_ 

**How to solve it**  

_CREATE TABLE tl_comments (id INT UNSIGNED AUTO_INCREMENT NOT NULL, tstamp INT UNSIGNED DEFAULT 0 NOT NULL, source VARCHAR(32) DEFAULT '' NOT NULL, parent INT UNSIGNED DEFAULT 0 NOT NULL, date VARCHAR(64) DEFAULT '' NOT NULL, name VARCHAR(64) DEFAULT '' NOT NULL, email VARCHAR(255) DEFAULT '' NOT NULL, website VARCHAR(128) DEFAULT '' NOT NULL, **'member'** INT UNSIGNED DEFAULT 0, comment TEXT DEFAULT NULL, addReply CHAR(1) DEFAULT '' NOT NULL, author INT UNSIGNED DEFAULT 0 NOT NULL, reply TEXT DEFAULT NULL, published CHAR(1) DEFAULT '' NOT NULL, ip VARCHAR(64) DEFAULT '' NOT NULL, notified CHAR(1) DEFAULT '' NOT NULL, notifiedReply CHAR(1) DEFAULT '' NOT NULL, INDEX published (published), INDEX source_parent_published (source, parent, published), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC_

**Comment by leofeyer** [comment]
Duplicate of #727
