### ISSUE TITLE
Twig slots implementation incomplete

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#7434]
### Affected version(s)

5.4.0-RC3

### Description

<img width="834" alt="" src="https://github.com/user-attachments/assets/b65bd263-23ac-4b83-8726-f32c8022c0bb">

I think we have to fix this, don‘t we? @m-vo @ausi /cc

**Comment by ausi** [comment]
Probably, yes. I’ll try to create a PR for that.

**Comment by m-vo** [comment]
For using `RawFilter` we'd need to bump the Twig version IIRC.
