### ISSUE TITLE
Hovering over icons in backend does not show the description

### ISSUE THREAD

**Issue by tabcontao** [contao/contao#7445]
### Affected version(s)

5.4.0

### Description

On some or most pages in the backend, there is no description shown when hovering with the mouse over an icon. Some example pages where this happens (not) are "Seiten", "Artikel", "Themes", "Templates", "Einstellungen". After refreshing the page (Strg+R) it works as expected. On other pages, like e.g. "Dateien", it works without refreshing the page. Interestingly, it works with Google Chrome initially on page "Seiten" sometimes, but refreshing the window, clicking through some other pages in backend, it stops working again.

Tested with Firefox (129.0.1 private window), Google Chrome 127.0.6533.120 (Offizieller Build) (64-Bit).

**Comment by zoglo** [comment]
I guess it's the `document.createElement` for the tooltip container not creating the element due to being prefetched
https://github.com/contao/contao/blob/3ebce2778499fb2618d8e848e88edfc6bf725313/core-bundle/assets/scripts/tips.js#L4-L8

**Comment by fritzmg** [comment]
We should probably implement a proper Stimulus controller instead.
