### ISSUE TITLE
Theme import fails with Form responses must redirect to another location

### ISSUE THREAD

**Issue by ausi** [contao/contao#7448]
### Affected version(s)

5.4.0

### Description

Probably related to Turbo?

**Comment by zoglo** [comment]
Is related to turbo @ausi. We should most likely disable it for the import form?

**Comment by zoglo** [comment]
https://github.com/contao/contao/blob/3ebce2778499fb2618d8e848e88edfc6bf725313/core-bundle/contao/classes/Theme.php#L134

I just tested this with the `data-turbo=false` attribute and it works.

Just unsure if that's the correct approach right now 🤔

**Comment by fritzmg** [comment]
Yes, either disable Turbo - or adjust the response accordingly, if it makes sense to do so in this case.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7449
