### ISSUE TITLE
Dopdown Felder doppeln sich bei der Erstellung

### ISSUE THREAD

**Issue by redwise** [contao/contao#7461]
### Affected version(s)

5.4.0

### Description

In der Version 5.4 doppel sich die Dropdown Felder, gut zu beobachten auf der Demoseite in den Template Einstellungen.
<img width="936" alt="Bildschirmfoto 2024-08-20 um 08 57 37" src="https://github.com/user-attachments/assets/e328c3f5-f531-4ab8-a7bb-5b2485f59a2b">
 
 Sämmliche Funktionen in anderen Elementen sind ebenfals davon betroffen.

**Comment by leofeyer** [comment]
This has been fixed in #7451 already.
