### ISSUE TITLE
Use the attr() method in templates (see #7218) 

### ISSUE THREAD

**Issue by zonky2** [contao/contao#7463]
### Affected version(s)

5.4

### Description

Before the change, `style` did not have to be set (`null`) - after the change, style must be an array or empty string - in my opinion, this requires unnecessary adjustments to your own code or extensions.

``` diff
- <div class="<?= $this->class ?> block"<?= $this->cssID ?><?php if ($this->style): ?> style="<?= $this->style ?>"<?php endif;?>>
+ ->addStyle($this->style)
```

see https://github.com/contao/contao/commit/14c242d65b11d6a261c6a00c9b087778ae0baa67

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/contao/pull/7446
