### ISSUE TITLE
Fehler beim Einbinden von MooTools via CDN (googleapis.com)

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#747]
Bei Aktivierung der Option zum Einbinden von MooTools via CDN (googleapis.com) im Seitenlayout, wird in den Header Folgendes aufgenommen:
``<script src="https://ajax.googleapis.com/ajax/libs/mootools/1.6.1/mootools.min.js"></script>``
 
Die URL https://ajax.googleapis.com/ajax/libs/mootools/1.6.1/mootools.min.js führt jedoch zu einem Fehler 404.

**Comment by andreheeke** [comment]
Das Problem ist: MooTools ist noch nicht in Version 1.6.1 erschienen. Lediglich die 1.6.0 wird über Google Hosted Libraries bereitgestellt.

**Comment by leofeyer** [comment]
Unsere MooTools-Komponente hat aber schon ein Tag `1.6.1`. 🤦‍♂ Ist jetzt behoben.
