### ISSUE TITLE
Add Closed Captions & Subtitles to Video-Element

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#7479]
### Description

In order to move a little further towards accessibility in the future, it would be great if the video elements could also be provided with corresponding subtitles (e.g. as VTT).

See also https://developer.mozilla.org/en-US/docs/Web/Media/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video

**Comment by zoglo** [comment]
See: #7604
