### ISSUE TITLE
Feld tl_user admin bei Bearbeiten von Benutzergruppen im Abschnitt Erlaubte Felder ausblenden

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#748]
Eine Vergabe des Rechtes für das Feld tl_user admin im Abschnitt "Erlaubte Felder" beim Bearbeiten von Benutzergruppen wird offenbar aus Sicherheitsgründen ignoriert. Das heißt auch Benutzer, die das Recht für dieses Feld haben, können keinen Benutzer zu Administrator machen.

Der Klarheit wegen würde es sich daher anbieten, das Feld tl_user admin beim Bearbeiten von Benutzergruppen im Abschnitt "Erlaubte Felder" auszublenden.

**Comment by leofeyer** [comment]
Geändert in 8eeba911aa2e779c34207a984e6d76e55ffefce6.

**Comment by aschempp** [comment]
@leofeyer der Fix ist falsch, es sollte einfach https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/dca/tl_user.php#L242 auf `false` geändert (oder einfach entfernt) werden.

**Comment by leofeyer** [comment]
Sicher nicht, denn sonst würde das Feld ja **immer** angezeigt!

**Comment by aschempp** [comment]
das ergibt für mich keinen Sinn. Wir sollten doch nicht das Feld in den Berechtigungen "manipulieren", sondern aus der Palette für den User entfernen?

**Comment by leofeyer** [comment]
Da hast Du Recht. 🤦‍♂

**Comment by leofeyer** [comment]
See #880.
