### ISSUE TITLE
Verwaltung des Rechts für das Modul Templates

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#749]
Wenn einem regulären Benutzer das Recht für das Modul Templates eingeräumt wurde, erscheint im Modul Benutzer eine Warnung: "Mindestens ein regulärer Benutzer hat Zugriff auf den Template-Editor. Da Templates PHP-Dateien sind, haben diese Benutzer implizit die volle Kontrolle über das System!"

Ein regulärer Benutzer kann jedoch auch, wenn er aufgrund der Einstellung "Erlaubte Felder" in einer seiner Benutzergruppen das Recht für das Feld ``modules`` in ``tl_user`` oder ``tl_user_group`` hat, sich oder anderen Zugriff auf den Template-Editor verschaffen.

Es wäre daher sinnvoll, wenn auch gewarnt werden würde, wenn das Recht für das Feld ``modules`` in ``tl_user`` oder ``tl_user_group`` an reguläre Benutzer vergeben ist.

Am sichersten wäre es, wenn die Berechtigung für das Modul Templates nur von Administratoren vergeben werden könnte, unabhängig von der Berechtigung für das Feld ``modules`` in ``tl_user`` oder ``tl_user_group``.

**Comment by leofeyer** [comment]
> Am sichersten wäre es, wenn die Berechtigung für das Modul Templates nur von Administratoren vergeben werden könnte,

Da gebe ich Dir Recht, allerdings funktioniert das nicht, wenn ein Benutzer gleichzeitig auch die Benutzerrechte bearbeiten kann.

* Der Admin schaltet den Template-Editor in den Benutzerrechten frei.
* Der Benutzer bearbeitet seinen eigenen Datensatz, wobei ihm das Feld `tpl_editor` aber nicht angezeigt wird, weil er ja kein Admin ist.
* Der Benutzer speichert und hat jetzt keinen Zugriff mehr auf den Template-Editor.

Ich denke, dass uns in diesem Fall auch nur die Möglichkeit einer Warnung bleibt. @contao/developers Was denkt ihr?

**Comment by Mynyx** [comment]
> Der Benutzer speichert und hat jetzt keinen Zugriff mehr auf den Template-Editor.

Könnte das vielleicht mit einer Callback-Funktion, die bei Bearbeitungen von Benutzern ohne Administratorrechte die Änderung am Feld `tpl_editor` zurücksetzt, verhindert werden?

**Comment by leofeyer** [comment]
Wie am 26. September auf Mumble besprochen, wäre eine Warnung durchaus ausreichend. Trotzdem werde ich auch das mit dem Callback versuchen.

**Comment by leofeyer** [comment]
Ich habe den Callback in 6d6b12296ac27e36758506b5f5d3ea90d1e16025 implementiert.
