### ISSUE TITLE
Larger files take forever to load in the code editor

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#7492]
### Affected version(s)

5.4

### Description

Download and unpack the [test.scss.gz](https://github.com/user-attachments/files/16778673/test.scss.gz) file and put the file into your `files/` folder. Then open the code editor.

* Contao 5.3: the editor is ready in less than 1 second.
* Contao 5.4: the editor takes **12,57 seconds** until it is ready.

The larger the file, the longer the editor takes.

**Comment by m-vo** [comment]
Is something blocking or is the browser busy at all times? Random guess: The latter could maybe have something to do with the `maxLines: Infinity` change (continuously rendering or something).

**Comment by fritzmg** [comment]
I can confirm the issue. Firefox is also unable to render the editor properly in 5.4 (initially).

**Comment by leofeyer** [comment]
> The latter could maybe have something to do with the `maxLines: Infinity` change (continuously rendering or something).

Good thought, but we have already added `maxLines: Infinity` in Contao 5.3. The main difference is that the ACE initialization script is a Stimulus controller now in Contao 5.4.

**Comment by m-vo** [comment]
That is interesting. Is it because the init now runs in a microtask? We could try using `setTimeout(..., 0)` just to narrow down the problem.

**Comment by fritzmg** [comment]
Hm, this is odd. I disabled the Stimulus controller and copied the `be_ace.html5` from Contao 5.3 - while this improves the init process from 7 to 3 seconds in my case, it is still longer than in Contao 5.3 (where it is ~1 sec).

**Comment by leofeyer** [comment]
If I remove `maxLines: Infinity`, the editor loads fast again. But why does this not affect Contao 5.3 then?

**Comment by m-vo** [comment]
No clue so far. But setting max lines to a sensible value might make sense anyways. Ace only renders "visible" lines for performance and I'm not sure it can take scrolling into account.

**Comment by leofeyer** [comment]
Using `maxLines: Infinity` is generally not a good idea (see https://github.com/ajaxorg/ace/issues/2947). We should instead adjust the editor height to the viewport and scroll inside the editor instead of scrolling the whole page:

<img width="1080" alt="" src="https://github.com/user-attachments/assets/b3fb4208-d1b9-4c57-ba52-6609d3063ba9">

**Comment by leofeyer** [comment]
Adding `editor.container.style.height = 'calc(100vh - 320px)';` in the `be_ace` template worked well in my tests, but I‘m sure there is a more sophisticated solution.
