### ISSUE TITLE
 Backup-Codes lassen sich nicht generieren

### ISSUE THREAD

**Issue by BugBuster1701** [contao/contao#7498]
### Affected version(s)

5.4.1

### Description

Bei der Zwei-Faktor-Authentifizierung lassen sich keine Backup-Codes generieren.
In der DEV Log tauchen keine Meldungen auf die sich von Contao 5.3 unterscheiden.

Aber in der Browser Console:
`Error: Form responses must redirect to another location`

Hat was mit Turbo zu tun würde ich mal vermuten.

**Comment by BugBuster1701** [comment]
Hotfix wäre im be_two_factor.html5 Zeile 64 erweitern um `data-turbo="false"`.
Hab das aber nicht mit allen Buttons getestet aus Zeitgründen oder ob andere Möglichkeiten existieren.

**Comment by zoglo** [comment]
Found a similar thread within the community boards apparently affecting 4.13 and 5.3 as well.

Did you also check the latest LTS?

**Comment by zoglo** [comment]
> https://github.com/contao/contao/issues/7498#issuecomment-2323525690

Works fine in 4.13 and 5.3 (Just tested it)
