### ISSUE TITLE
Move to Symfony 2.7 asap

### ISSUE THREAD

**Issue by aschempp** [contao/contao#75]
The stable release of Symfony 2.7 will be available starting in May.
http://symfony.com/roadmap?version=2.7#checker

I think we should definitely ship Contao 4 with Symfony 2.7 so we don't have to migrate our base framework in the next 2 years. http://symfony.com/blog/category/living-on-the-edge

**Comment by leofeyer** [comment]
+1 generally.

However, I doubt that we will stay with Symfony 2.7 until 2018 :)

**Comment by discordier** [comment]
+1 and as long as we only restrict to minor, composer will bump us up to new versions.

**Comment by leofeyer** [comment]
See https://github.com/contao/core-bundle/issues/153.
