### ISSUE TITLE
Turbo X Non-OK responses

### ISSUE THREAD

**Issue by richardhj** [contao/contao#7501]
### Affected version(s)

5.4.1

### Description

When the edit operation results in a 500 response (in my case, a non-up-to-date database), the site shows "Content missing".
<img width="489" alt="Screenshot 2024-09-02 at 22 04 54" src="https://github.com/user-attachments/assets/cfcdc171-b0e6-4e6e-bbff-572cc33cc257">
<img width="494" alt="Screenshot 2024-09-02 at 22 04 52" src="https://github.com/user-attachments/assets/9cd5f996-e71d-4ef6-9b3a-6357259e60af">

**Comment by fritzmg** [comment]
What is the response body in your case?

**Comment by richardhj** [comment]
Symfony exception page
<img width="435" alt="Screenshot 2024-09-03 at 08 32 22" src="https://github.com/user-attachments/assets/a48e8fcf-b878-48ea-ace5-e1aa7afb0e25">

This could also be expected behavior 😆
