### ISSUE TITLE
Rate Limit absent on forgot password page

### ISSUE THREAD

**Issue by kunalmhaske21212** [contao/contao#7502]
### Affected version(s)

all

### Description
This Vulnerability can be used as an email bomber for bombing some user accounts with forgotten password emails. Also, the Impact is high on mail servers. If some attacker sends emails using the same loop, It will keep the mail servers busy and can make them unavailable to other users.

STEPS TO REPRODUCE:
1) Go to password reset password enter email and intercept the request in burp.
2) Now send that request to Intruder and select payloads for user-agent.
3) Start the attack
4) Now check the email address is been flooded with mail

**Comment by kunalmhaske21212** [comment]
Hello @aschempp @leofeyer ,
Please give me a response regarding reward. Please sir.

**Comment by bytehead** [comment]
See #7581
