### ISSUE TITLE
Add name as allowed attribute to the <details> HTML element

### ISSUE THREAD

**Issue by mdollde** [contao/contao#7507]
### Description

The `<details>` HTML element can have two attributes, `open` and `name`. By default, only `open` is an allowed attribute in Contao.

_This attribute enables multiple `<details>` elements to be connected, with only one open at a time. This allows developers to easily create UI features such as accordions without scripting._
see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#name

With Firefox 130 out, `name` has support from all major browsers now and the attribute should be added to Contao.
https://caniuse.com/mdn-html_elements_details_name

Greetings
Mathias

**Comment by leofeyer** [comment]
@ausi Did we not add `name` for a reason?

**Comment by ausi** [comment]
> Did we not add `name` for a reason?

No, it did not exist yet at the time we defined the default list of allowed attributes.

**Comment by ausi** [comment]
Closed in favor of #7512
