### ISSUE TITLE
Error 500: ArticleContentVoter::getPageId(): Return value must be of type ?int, string returned

### ISSUE THREAD

**Issue by piotrwarsztocki** [contao/contao#7508]
### Affected version(s)

5.3.13

### The lastest update **5.3.12 -> 5.3.13** completely blocked the ability to edit "Content/Articles" articles.

When I try to go there through the menu I get a **500 error** with the message:

> "Contao\CoreBundle\Security\Voter\DataContainer\ArticleContentVoter::getPageId(): Return value must be of type ?int, string returned"

Here is a fragment of the log entry

> [2024-09-04T08:08:11.826034+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Contao\CoreBundle\Security\Voter\DataContainer\ArticleContentVoter::getPageId(): Return value must be of type ?int, string returned" at ArticleContentVoter.php line 69 {"exception":"[object] (TypeError(code: 0): Contao\\CoreBundle\\Security\\Voter\\DataContainer\\ArticleContentVoter::getPageId(): Return value must be of type ?int, string returned at /home/.../public_html/vendor/contao/core-bundle/src/Security/Voter/DataContainer/ArticleContentVoter.php:69)"} {"request_uri":"https://www...pl/admin?do=article&ref=mgLbnYQR","request_method":"GET"}

The problem occurred on all pages that I updated to 5.13.13

The downgrade **5.13.13 -> 5.13.12** helps to solve the problem.

**Comment by aschempp** [comment]
You probably have an old database server version that does not return the correct types. But it sure is a bug in Contao as well, will be fixed by https://github.com/contao/contao/pull/7509
