### ISSUE TITLE
Recht für Backend-Modul Sicherheit

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#751]
Bei Benutzern und Benutzergruppen ist es im Abschnitt "Erlaubte Module" möglich, das Modul "Sicherheit" auszuwählen.

Über das Benutzermenü ist das Modul "Sicherheit" jedoch immer aufrufbar, auch wenn es im Abschnitt "Erlaubte Module" nicht ausgewählt wurde.

Es ist mir auch ansonsten keine Auswirkung aufgefallen, wenn das Modul für einen Benutzer erlaubt ist oder nicht.

**Comment by leofeyer** [comment]
Behoben in a0c6bb4810860e561202485a0bb71ef7fa5b6645.
