### ISSUE TITLE
Twig template locator should use %contao.resources_paths%

### ISSUE THREAD

**Issue by richardhj** [contao/contao#7519]
### Affected version(s)

5.4.1

### Description

The `%contao.resources_paths%` is currently used to locate, among others, dca files.

IMHO, the Twig locator should also look up templates under these paths for th `@Contao_App` namespace.

https://github.com/contao/contao/blob/6f8832ffea3c8454c90d0b09429c5654232afe39/core-bundle/src/Twig/Loader/TemplateLocator.php#L93

This would help me, to override the path in a [multi app Symfony application](https://symfony.com/doc/current/configuration/multiple_kernels.html).

**Comment by m-vo** [comment]
The `TemplateLocator` goes through the same resources as the `AddResourcesPath` (that builds the mentioned parameter at compile time). I don't quite get what you are trying to achieve.

Do you want to move the global `contao` directory to somewhere else? If so, I'm not sure manipulating the `contao.resources_paths` parameter is/can be supported. We would need to implement a parameter for the path instead and use that everywhere (I think).

**Comment by richardhj** [comment]
> The `TemplateLocator` goes through the same resources as the `AddResourcesPath` (that builds the mentioned parameter at compile time). I don't quite get what you are trying to achieve.

In fact it goes through all bundles directories and add twig pahts for the `Contao_FooBarBundle` namespace.
It is not using the %contao.resources_paths% at this moment.

> Do you want to move the global `contao` directory to somewhere else? If so, I'm not sure manipulating the `contao.resources_paths` parameter is/can be supported. We would need to implement a parameter for the path instead and use that everywhere (I think).

Actually my app root is not under `/` but under `/apps/foo/`. I have set up my application as described here: https://symfony.com/doc/current/configuration/multiple_kernels.html

I want Twig templates (for the `Contao_App` namespace) to be found that are under `/apps/foo/templates`.

To be honest, `%contao.resources_paths% holds both app and vendor paths, so it cannot be used in the current implementaiton.

**Comment by m-vo** [comment]
> Actually my app root is not under / but under /apps/foo/.

Got it now. 👍 Is the Twig implementation the only thing holding you back from following that strategy or are there other parts that would need to be adjusted?

**Comment by richardhj** [comment]
The paths for loading DCA and language files [are also hardcoded here](https://github.com/contao/contao/blob/6f8832ffea3c8454c90d0b09429c5654232afe39/core-bundle/src/DependencyInjection/Compiler/AddResourcesPathsPass.php#L51), but I was able to override using a compiler pass in the app.

So yes, the Twig templates are the only thing holding me back currenlty. (I was able to override the templates path via the theme, but this means that the templates are not available in the backend).

Regardless of whether we are talking about Twig templates or DCA, I can imagine of being able to easily change those config paths (not via a compiler pass necessarily). All major Symfony bundles allow to config paths (i.e., asset mapper, Twig, ...), maybe this would be a way to go?

**Comment by m-vo** [comment]
So, I guess we would need to discuss if the location of the `contao` directory should be made configurable.

**Comment by Toflar** [comment]
I guess this can be closed then @aschempp ?

**Comment by aschempp** [comment]
yes!
