### ISSUE TITLE
Fehler in Paginierung der Versionsübersicht

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#752]
In https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/classes/Versions.php#L647 führt die Bedingung `version>1` dazu, dass die Paginierung fehlerhaft ist - es werden zu wenige Seiten berechnet. Denn in der Tabelle werden alle Versionen angezeigt, auch Version 1.

**Comment by leofeyer** [comment]
Behoben in 1131f97cfdc0d1649d459cfe80225c85be1f6fb6.
