### ISSUE TITLE
Improve dropdown for customizable templates

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#7523]
### Description

In Contao 5 sollte die Dropdownbox für die anpassbaren Templates verbessert werden. Im Moment werden für die Inhaltselemente sowohl die alten Legacy-Templates angezeigt als auch die neuen Twig-Templates. 
Es wäre m.E. übersichtlicher, wenn  die Legacy-Template in der Auswahlliste für die Template-Anpassungen ausgeblendet werden, wenn deren Benutzung nicht explizit eingestellt wird und umgekehrt, sollten die Twig-Templates ausgeblendet werden, wenn jemand die Nutzung der Legacy-Templates eingestellt hat.

**Comment by fritzmg** [comment]
? Es sollten entweder nur die neuen oder die alten angezeigt werden, je nach Inhaltselement. Wenn dem nicht so ist, wäre das ein Bug.

**Comment by mlwebworker** [comment]
Es geht um das Dropdown für das Erstellen eines neuen Templates - im Bild am Beispiel für ein Text-Element.
Ich bin mir nicht sicher, ob das wirklich ein Bug ist, man sieht ja dass es sich um HTML5- bzw. Twig-Templates handelt.

![image](https://github.com/user-attachments/assets/b22d7b4e-f4da-4585-b409-0560499af35e)

**Comment by fritzmg** [comment]
Ah sorry, falsch verstanden. Grundsätzlich sind dort alle im System verfügbaren Templates auswählbar. Das muss auch so bleiben - denn nur weil du im Core das alte Inhaltselement "ContentText" nicht aktiviert hast, heißt das ja nicht, dass dieses Template nicht andernorts in Verwendung ist. Grundsätzlich gibt es keine Verbindung zwischen Controller und Template. Ein Controller kann beliebige Templates nutzen.

**Comment by mlwebworker** [comment]
Das hörte sich bei @m-vo in Slack aber anders an https://contao.slack.com/archives/CK4J0KNDB/p1725643855911109

**Comment by fritzmg** [comment]
Bitte nie Slack Links posten. Wenn dann musst du es hier nochmals zitieren.

**Comment by mlwebworker** [comment]
Ich habe gerade noch mal geschaut in Slack ging es tatsächlich um die Auswahl die Template-Einstellungen beim Element.
Das muss ich dann noch mal testen
