### ISSUE TITLE
Incorrect template selection in the gallery content element

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#7524]
### Affected version(s)

5

### Description

Im Inhaltselement Galerie stehen in den Template-Einstellungen zwei Templates zur Auswahl.
Bei Verwendung der Twig-Templates wird aber nur das Inhaltselement-Template verwendet. Das Galerie-Template wird nur in Legacy-Elementen benötigt und Anpassungen an diesem Element greifen bei Verwendung der Twig-Elemente natürlich nicht.
Bei Verwendung der Twig-Templates sollte das Galerie-Template deshalb nicht angezeigt werden.

![image](https://github.com/user-attachments/assets/67ddadb0-5b51-4463-b57c-0d48a5908b12)

**Comment by fritzmg** [comment]
To fix this we can add/remove the field from the palette depending on the value in `$GLOBALS['TL_CTE']['media']['gallery']`.
