### ISSUE TITLE
Legende im BE komplett klickbar - so wie Cursor das anzeigt

### ISSUE THREAD

**Issue by zonky2** [contao/contao#7526]
### Affected version(s)

5.3.13

### Description

Im BE wechselt der Cursor zu Pointer, wenn man mit der Maus über eine Legende fährt - wirklich klickbar ist aber nur der enthaltene Button

Die gesammte Legende sollte klickbar sein, so wie es der Wechsel des Cursors suggeriert.

![grafik](https://github.com/user-attachments/assets/b3df82e9-b0cf-44db-9bc5-01ba107e5897)

**Comment by zonky2** [comment]
Ich habe das in 5.3.14 geprüft - es wird weiterhin **nicht** der gesamte Bereich getriggert... ich meine, man muss auch in den "lifafarbenen Bereich" klicken können - siehe Bild oben - bzw. dort wo der Mauszeiger steht (s.u.)


![grafik](https://github.com/user-attachments/assets/7838500d-3545-4950-9560-6cb2fa59b713)

**Comment by fritzmg** [comment]
@zonky2 see the linked PR.

**Comment by zonky2** [comment]
> @zonky2 see the linked PR.

@fritzmg: Ja, sehe ich... offensichtlich soll ich dort was sehen, was ich aber nicht sehe - ggf. hilfst Du mir auf die Sprünge

**Comment by fritzmg** [comment]
The PR has not been merged yet. You would need to check out the PR in order to test the fix.

**Comment by zonky2** [comment]
o.k. - ich hab ich davon irritieren lassen, dass das Issue als "erledigt" gilt und hier auftaucht
https://github.com/contao/contao/issues?q=milestone%3A5.3+is%3Aclosed+sort%3Aupdated-desc

ich check mal den PR

**Comment by fritzmg** [comment]
> o.k. - ich hab ich davon irritieren lassen, dass das Issue als "erledigt" gilt und hier auftaucht
> https://github.com/contao/contao/issues?q=milestone%3A5.3+is%3Aclosed+sort%3Aupdated-desc

You need to check the actual releases. An issue or PR being closed does not mean it has been released yet.
