### ISSUE TITLE
Use base64 encoded file paths in URLs?

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#7529]
### Affected version(s)

4.x, 5.x

### Description

Contao uses the full path to a file as a query parameter in various places. For example, within `DC_Folder`, individual files are always identified via their full path (as they do not have to be in the database) and thus the full path is present in all query parameters for the various back end actions. Our download content elements also use the full path in the query parameter for downloading files.

Now, if a hosting environment uses OSSEC IDS _and_ a file happens to have, for example, `… Input …` somewhere in its name, this will trigger [this rule](https://github.com/ossec/ossec-hids/blob/39a93137c1620edfd9ace8cd0a49d57ebb7e5329/etc/rules/web_rules.xml#L65-L71) - e.g. for any of the back end actions in the file manager for this file, or when downloading this file in the front end. A file name like that is not outlandish. In our case these were files uploaded in the front end and as such there are of course no externally imposed file naming rules.

Personally I think such firewalls are overreaching and unsuitable to be applied to all web applications by default.

However, may be having the full path to a file as a query parameter (especially if it happens to be very long) is not ideal regardless, thus I wanted to discuss whether we should instead `base64_encode` the filename for example.

So instead of 

```
https://example.com/contao?do=files&act=delete&id=files%2Fsome%2Fvery%2Flong%2Ffile%2Fpath%2Fto%2Fa%2Fvery%2Flong%2Ffile%2Fname%2Florem%20ipsums%20dolor%20sit%20amet%20consectetuer%20adipiscing%20elitr%20foobar.pdf&rt=…
```

you would have

```
https://example.com/contao?do=files&act=delete&id=ZmlsZXMvc29tZS92ZXJ5L2xvbmcvZmlsZS9wYXRoL3RvL2EvdmVyeS9sb25nL2ZpbGUvbmFtZS9sb3JlbSBpcHN1bXMgZG9sb3Igc2l0IGFtZXQgY29uc2VjdGV0dWVyIGFkaXBpc2NpbmcgZWxpdHIgZm9vYmFyLnBkZg==&rt=…
```

It will always be longer - but at least now the path and name cannot interfere anymore.

@contao/developers wdyt?

**Comment by ausi** [comment]
> Now, if a hosting environment uses OSSEC IDS _and_ a file happens to have, for example, `… Input …` somewhere in its name, this will trigger [this rule](https://github.com/ossec/ossec-hids/blob/39a93137c1620edfd9ace8cd0a49d57ebb7e5329/etc/rules/web_rules.xml#L65-L71)

Does this mean a URL like `https://example.com/search?keywords=Input%20Test` would be blocked? If so, I’m against fixing this on our side as this is clearly a nonsense configuration.

**Comment by fritzmg** [comment]
As far as I understand it, yes. Same with `keywords=iframe%20test`. Another issue occurred together with client side tracking via Matomo, where the title of the page is sent to the Matomo instance. So if you have a page with `The input ...` as its title the firewall will be triggered as well.

**Comment by ausi** [comment]
Blocking any url that includes `Input%20` makes no sense at all. I remember customers with similar problems, like they could not save a layout in the backend if it included a `<script>` tag. They all solved it by disabling the cause which was in that case `mod_security`.

Encoding our values with base64 would actually worsen security, at least potentially. Injecting null-bytes or other invalid characters would then be possible, all the “protection” from using our `Input` class would be gone for such parameters.

I think we have to see this in a different way. If the server is configured to block `Input%20` we should not try to bypass that because the person who configured that server decided that this is insecure. Using base64 would bring back that “security issue” the server admin tried to block.

Are there actually hosing providers that block `Input%20` without the option to opt out of that?

**Comment by fritzmg** [comment]
I think maybe the OSSEC rules are not really meant to be used in a shared hosting environment where you have no deeper knowledge of the apps running on the hosting itself. Or at least not down to such a low level. The rule blocking `input%20` is at level **6**. OSSEC rules have levels 0 through 16 - the higher the level the more severe or certain an attack is. If you go down to level **5** for example then [any request that results in a 4xx response](https://github.com/ossec/ossec-hids/blob/39a93137c1620edfd9ace8cd0a49d57ebb7e5329/etc/rules/web_rules.xml#L31-L35) is considered an "attack" - which obviously should also never be applied by default. According to [OSSEC's documentation](https://www.ossec.net/docs/manual/rules-decoders/rule-levels.html) only level **15** or higher ensures no false positives.

**Comment by aschempp** [comment]
Just on a funny side note. I recently got one of my client sites scanned by an enterprise security tool. It reported this (at _Info_ level). So this security tool thinks using base64 can be problematic.

> Applications sometimes Base64-encode parameters in an attempt to obfuscate them from users or facilitate
transport of binary data. The presence of Base64-encoded data may indicate security-sensitive information
or functionality that is worthy of further investigation. The data should be reviewed to determine whether it
contains any interesting information, or provides any additional entry points for malicious input.

**Comment by fritzmg** [comment]
As discussed it makes no sense to implement this (see previous comments).
