### ISSUE TITLE
Exception in Version480Update.php

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#753]
In https://github.com/contao/contao/blob/master/installation-bundle/src/Database/Version480Update.php#L236 wird die Query `DROP TABLE tl_remember_me` auch ausgeführt, wenn diese Tabelle gar nicht existiert, wodurch es zu einer Exception kommen kann.

**Comment by leofeyer** [comment]
Behoben in 4c060364964f34989efdc4221f4fdeee7c7c62ab.
