### ISSUE TITLE
permissions of user groups are not respected

### ISSUE THREAD

**Issue by leon1995** [contao/contao#7531]
### Affected version(s)

5.3.14

### Description

A group is not able to create a new ~~file~~ folder in "Files"-section for the respected filemount, even though it has all permissions there is for the file section.
I think this might also affect news and events (and maybe others) that they cant be changed or cant create new elements
![Screenshot 2024-09-13 at 12 04 59](https://github.com/user-attachments/assets/25041d7c-0e79-4b99-b0da-4a0c1e8852a8)
![Screenshot 2024-09-13 at 13 18 51](https://github.com/user-attachments/assets/6b45048d-1c95-4841-b024-5731cd4c5a41)
![Screenshot 2024-09-13 at 15 06 57](https://github.com/user-attachments/assets/18525c89-c544-4525-8854-2f12ef433f9a)
[this issue has been created based upon a post in the forum](https://community.contao.org/de/showthread.php?87356-Backend-permission-f%C3%BCr-files)

EDIT: Yes I mean folders, not files. I replaced it in the text

**Comment by fritzmg** [comment]
> A group is not able to create a new file in "Files" for the respected filemount

You mean folders, right? You cannot create files - only upload them (and it looks like uploading is still possible).

I can confirm the issue of non-admins not being able to create folders in their filemounts.

**Comment by fritzmg** [comment]
@leon1995 you probably did not give any `tl_files` permissions. Your back end user needs to have at least the permission to edit `tl_files.name` in order to be able to create a folder (otherwise you wouldn't be able to set a name for the folder).

**Comment by leon1995** [comment]
thats probably it... wow I didnt know. Thanks!
