### ISSUE TITLE
Response from a fragment controller is sent directly to client, if status code is 422

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#7536]
### Affected version(s)

4.13, 5.3

### Description

If a FragmentController returns a response with status code `422`, that response is sent directly to client, instead of embedding it into the full page. I found it, trying use a Symfony form in a frontend controller, but it can be easily reproduced even without a form:

```php
#[AsFrontendModule]
class ExampleModuleController extends AbstractFrontendModuleController
{
    protected function getResponse(Template $template, ModuleModel $model, Request $request): Response
    {
        $response = $template->getResponse();
        $response->setStatusCode(Response::HTTP_UNPROCESSABLE_ENTITY);

        return $response;
    }
}
```

Try to request the page with `curl` or a browser. The response body contains only the content of the module template, instead of the complete HTML document.

**Comment by fritzmg** [comment]
I can confirm this in Contao 5.3. You are saying this also happens in 4.13?

**Comment by ameotoko** [comment]
Yes, I was able to reproduce it in 4.13 as well.

**Comment by fritzmg** [comment]
I can confirm it in 4.13 as well.

**Comment by fritzmg** [comment]
Symfony's `FragmentHandler` will throw a `\RuntimeException` if a fragment's response is not successful (which will be the case for a `422` response):

https://github.com/symfony/symfony/blob/60a39d6ec7bbd414b9727ecfd703f4de1b962f08/src/Symfony/Component/HttpKernel/Fragment/FragmentHandler.php#L100-L103

Contao's `FragmentHandler` will then convert this to a `ResponseException`:

https://github.com/contao/contao/blob/e630d0fc90a29b83173d1b2265459becb6d6e27d/core-bundle/src/Fragment/FragmentHandler.php#L74-L78

Which, down the line, will cause the fragment's response to be sent directly to the browser.

**Comment by m-vo** [comment]
Just wondering: When would the body of a 4** response be relevant for anything other than information about the error/issue? Or in other words: Why do you need the other fragments/controllers to render content?

**Comment by ameotoko** [comment]
> When would the body of a 4** response be relevant for anything other than information about the error/issue?

In case of 422 - that's what Symfony does🤷🏻‍♂️. Besides, ~~in Contao~~, 404 pages can have content. Anywhere, probably, not only in Contao.

**Comment by fritzmg** [comment]
@m-vo Symfony automatically sets the status code when rendering a form. If one of your fragments contains a form which does not validate during `POST`, the response status of the main request needs to be `422` (in general and for Turbo).

In theory this means that even within a regular Symfony application you cannot render a form as a fragment, as it would throw an exception 🤔. Though I haven't tried yet.

**Comment by ameotoko** [comment]
@fritzmg this Symfony behaviour is opt-in, the status code is only set automatically if you want it. All that Symfony does is a convenience shortcut.

In Symfony 5, if you pass a `FormInterface` to `render()`, it will check form validity for you, set the response code and call `$form->createView()` for you. It will skip all that if you pass `FormViewInterface` yourself.

And in Symfony 6, there is even a separate `renderForm()` method, which you have to call explicitly instead of `render()`, if you want that behaviour.

**Comment by fritzmg** [comment]
What I mean is you cannot use

```twig
{{ render(controller('App\\Controller\\FormController::someForm')) }}
```

where `FormController::someForm` simply passes the form to the template.

**Comment by ameotoko** [comment]
By default, that should work though? The default practice in S5 was to pass form view to the template, and in S6 I think it would throw when you pass `FormInterface` to `render()`, so you'd need to make an explicit decision, either to pass form view or use `renderForm()`.

Besides, I don't think it makes sense to render a form as fragment in pure Symfony application, only in context of Contao.

**Comment by fritzmg** [comment]
> Besides, I don't think it makes sense to render a form as fragment in pure Symfony application

Using `{{ render() }}` in Symfony applications is perfectly normal.

**Comment by fritzmg** [comment]
As suspected it also does not work in a regular Symfony application. e.g.:

```php
// src/Controller/AppController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\NotBlank;

class AppController extends AbstractController
{
    #[Route('/')]
    public function index(): Response
    {
        return $this->render('index.html.twig');
    }

    public function form(Request $request): Response
    {
        $form = $this->createFormBuilder()
            ->add('foo', TextType::class, [
                    'constraints' => new NotBlank(),
                    'required' => false,
                ]
            )
            ->add('submit', SubmitType::class)
            ->getForm()
        ;

        $form->handleRequest($request);

        return $this->renderForm('form.html.twig', ['form' => $form]);
    }
}
```
```twig
{# templates/index.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    {{ render(controller('App\\Controller\\AppController::form', {request: app.request})) }}
{% endblock %}
```
```twig
{# templates/form.html.twig #}
{{ form(form) }}
```

This will throw an error when submitting the form and it does not validate:

```
Symfony\Component\HttpKernel\Exception\HttpException:

  at vendor\symfony\http-kernel\Fragment\FragmentHandler.php:102
  at Symfony\Component\HttpKernel\Fragment\FragmentHandler->deliver(object(Response))
     (vendor\symfony\http-kernel\Fragment\FragmentHandler.php:85)
  at Symfony\Component\HttpKernel\Fragment\FragmentHandler->render(object(ControllerReference), 'inline', array('ignore_errors' => false))
     (vendor\symfony\http-kernel\DependencyInjection\LazyLoadingFragmentHandler.php:49)
  at Symfony\Component\HttpKernel\DependencyInjection\LazyLoadingFragmentHandler->render(object(ControllerReference), 'inline', array())
     (vendor\symfony\twig-bridge\Extension\HttpKernelRuntime.php:46)
  at Symfony\Bridge\Twig\Extension\HttpKernelRuntime->renderFragment(object(ControllerReference))
     (var\cache\dev\twig\37\3705868621d3a0480b53aed0988a3f2f.php:68)
```

**Comment by ameotoko** [comment]
Does it work with this?

```diff
- return $this->renderForm('form.html.twig', ['form' => $form]);
+ return $this->render('form.html.twig', ['form' => $form->createView()]);
```

**Comment by fritzmg** [comment]
This would work, but is not the recommendation from Symfony.

**Comment by aschempp** [comment]
> What I mean is you cannot use
> 
> ```
> {{ render(controller('App\\Controller\\FormController::someForm')) }}
> ```

That is something we discussed and explicitly do not support. Our fragment system works differently, that's why we have `frontend_module` and `content_element` Twig functions in Contao 5.3. This would work for forms, since `Form` is a legacy class and would not run a subrequest.

Generally speaking on the perspective of Symfony, a fragment should never receive input and should only ever render a 200 return code. It should never contain a form or validate it etc, that's the job of the main page controller. It only works in Contao because we added our own `forward` fragment handler for BC reasons, the default Symfony `inline` fragment handler does not even forward POST data to the fragment.

**Comment by fritzmg** [comment]
> That is something we discussed and explicitly do not support. Our fragment system works differently, that's why we have `frontend_module` and `content_element` Twig functions in Contao 5.3. This would work for forms, since `Form` is a legacy class and would not run a subrequest.

My example was regarding a Symfony application and had nothing to do with Contao itself.

**Comment by leofeyer** [comment]
As discussed in the Contao call, there is not much we can do about this because it is not supported in Symfony.
