### ISSUE TITLE
Contao Captcha throws a JavaScript Error in the backend

### ISSUE THREAD

**Issue by zoglo** [contao/contao#7542]
### Affected version(s)

4.13, 5.3, 5.4

### Description

Simply add the original security question captcha field within `tl_form_field` (in the backend) and wait a few seconds for the error to appear in console

![image](https://github.com/user-attachments/assets/84cd8f65-e768-4f7a-9fec-ad7709a4cc3d)
![image](https://github.com/user-attachments/assets/441db7bd-3ede-471b-a033-265357906e7d)

/cc @ausi

**Comment by ausi** [comment]
Can confirm. The error reads `Uncaught (in promise) TypeError: e.form is null` in my test.

We should probably not output the captcha javascript in the backend.
