### ISSUE TITLE
Unterschiedliche Ausgabe der Style-Angabe vom DCA in BE und FE

### ISSUE THREAD

**Issue by zonky2** [contao/contao#7558]
### Affected version(s)

5.3.15

### Description

Die Style-Angabe des DCA wurde in Contao 4.13 bei einem Text-Feld sowohl beim `input` als auch beim umschließenden `div` eingefügt

in Contao 5.3 ist das

- im BE nur noch beim `input`
- im FE (z. B. Mitgliederdaten) weiterhin sowohl beim `input` als auch beim umschließenden `div` 

Ich konnte nichts finden, 

a) warum das geändert wurde  und
b) warum es einen Unterschied zwischen BE und FE gibt

**Comment by fritzmg** [comment]
> Die Style-Angabe des DCA wurde in Contao 4.13 bei einem Text-Feld sowohl beim `input` als auch beim umschließenden `div` eingefügt

I cannot confirm that. If I use

```php
// contao/dca/tl_content.php
$GLOBALS['TL_DCA']['tl_content']['fields']['headline']['eval']['style'] = 'background-color:cyan';
```

for example, the HTML output will be:

```html
<div class="w50 clr widget">
  <h3><label>Headline</label></h3>
  <input type="text" name="headline[value]" id="ctrl_headline" class="tl_text_unit" value="" maxlength="200" style="background-color:cyan" onfocus="Backend.getScrollOffset()"> 
  <select name="headline[unit]" class="tl_select_unit" onfocus="Backend.getScrollOffset()">
    …
  </select>
  …
</div>
```

in Contao 4.13 and 5.3.x.

**Comment by zonky2** [comment]
```php
// contao/dca/tl_member.php
$GLOBALS['TL_DCA']['tl_member']['fields']['lat']['eval']['style'] = 'display:none';
```

```html
// BE
<div class="clr w50 widget">
  <h3><label for="ctrl_lat">Latitude</label></h3>
  <input type="text" name="lat" id="ctrl_lat" class="tl_text" value="52.6128132" style="display: none;" data-action="focus->contao--scroll-offset#store" data-contao--scroll-offset-target="autoFocus">
  <p class="tl_help tl_tip">Latitude vom Ort.</p>
</div>
```

```html
// FE
<div class="widget widget-text" style="display: none;">
  <label for="ctrl_lat_711">Latitude</label>
  <input type="text" name="lat" id="ctrl_lat_711" class="text" value="" style="display: none;">
</div>
```

**Comment by fritzmg** [comment]
@zonky2 yes, but that is not the issue I was refering to. I was refering to:

> Die Style-Angabe des DCA wurde in Contao 4.13 bei einem Text-Feld sowohl beim input als auch beim umschließenden div eingefügt

Which is not the case.

**Comment by fritzmg** [comment]
> in Contao 5.3 ist das
> 
> * im FE (z. B. Mitgliederdaten) weiterhin sowohl beim `input` als auch beim umschließenden `div`

I cannot reproduce this. If I set

```php
// contao/dca/tl_member.php
$GLOBALS['TL_DCA']['tl_member']['fields']['email']['eval']['style'] = 'background-color:cyan';
```

the HTML output in the `registration` module will be

```html
<div class="widget widget-text mandatory">
  <label for="ctrl_email_6" class="mandatory">
    <span class="invisible">Mandatory field </span>E-mail address<span class="mandatory">*</span>
  </label>
  <input type="email" name="email" id="ctrl_email_6" class="text mandatory" value="" required="" maxlength="255" style="background-color:cyan">
</div>
```

in Contao 4.13 and 5.3.x.

**Comment by zonky2** [comment]
dann ist dort ggf. noch was individuelles eingebaut...
