### ISSUE TITLE
Impossible to delete entries in metaWizard

### ISSUE THREAD

**Issue by 463** [contao/contao#7569]
### Affected version(s)

5.3.15

### Description

If I have a saved translation in the metaWizard I am not able to delete the entry by the delete-button. Only the entrys content will be deleted. This becomes obviously e. g. after changing the root language.
Up to Contao 4.x all entries until one last were able to delete.
Bug or feature?

**Comment by fritzmg** [comment]
The meta wizard will always show the languages of all website roots. Deleting will only delete the content, not the language itself. This is also the case in Contao 4.13.

**Comment by 463** [comment]
If I change or delete one root language I am not able to delete the prior language entries in the data base fields any more. The entries in this language remain untouched and inaccessible in the data base. So far ok. But after a manual transfer to the changed language a afterwards deletion is impossible. The same in case of a complete language deletion.

In 4.x the delete button deletes both the view of this entry in the BE and also the database language entry.

The obvious result of deleting the individual entrys content is the same, but the result in the background is different.

**Comment by fritzmg** [comment]
Yes - but what issue does this cause for you specifically?

**Comment by 463** [comment]
We want branch from pt to pt_PT and pt_BR.

**Comment by fritzmg** [comment]
But what is the issue you are encountering specifically?

**Comment by 463** [comment]
If I change from the existing pt to pt_PT the original pt stays as a ghost.

**Comment by fritzmg** [comment]
That would also happen if you change the language for a website root in Contao 4. And it should not interfere with anything.

Regardless of which Contao version you are using - if you really do not want these "ghosts", you would need to write a migration or command to migrate your existing meta data information to the new language or languages. It would be unreasonable to do this manually for _every_ file via the file manager.

**Comment by 463** [comment]
May be this is really specific and it is easier to modify the data base field directly.

In Contao 4 it was easy by click the delete button and in the data base field the language was removed. On the other side it was sometimes a little confusing if you deleted the language block and after saving the visual deleted languages these one that have a root language came back and other with no root language are gone. Therefore the actual version is much more clear and clean but I must find for us a proper and easy solution.

Thanks.

**Comment by fritzmg** [comment]
> but I must find for us a proper and easy solution.

As I said, I think you should write your own [migration](https://docs.contao.org/dev/framework/migrations/) that will automatically either delete all `pt` entries from `tl_files.meta` - or rewrite and duplicate them to `pt_PT` and `pt_BR`.

**Comment by a-kehr** [comment]
@fritzmg 

hätte eine Verständnisfrage zum Downlaods-Element mit Meta Data.

Wenn ich eine Installation mit mehreren Sprachen habe, wird ab der Zeile https://github.com/contao/contao/blob/5.x/core-bundle/contao/elements/ContentDownloads.php#L233-L244 ja der ganze Prozess ja nicht ausgeführt. Wenn ich die Datei bearbeite habe ich ja bereits für jede einzelne Sprache ja das Wizard für die Eingaben bereits verfügbar. Es würde ja nur funktionieren, wenn ich die anderen Sprachen lösche, danach wäre das Array ja leer und würde auf die Fallback-Sprache greifen wenn man die Meta-Daten nicht ignoriert.

Wenn man die Zeile

`if (empty($arrMeta))` in `if (empty($arrMeta) || 0 === count(array_filter($arrMeta)))` ändern würde, so würde auch der restliche Prozess ausgeführt.

Ich habe es für meinen Fall jetzt über den submit-callback gelöst. Beim speichern lösche ich mir einfach die Leeren Sprachen.

**Comment by aschempp** [comment]
I don't understand the arguments of @fritzmg here. If the wizard is supposed to show all languages of my root pages, it should obviously allow to delete languages that no longer are root pages. This is clearly a bug to me 😕

**Comment by leofeyer** [comment]
As discussed in the call, we should remove empty languages when saving so their key does not exist in the database. But we have to add form fields for all languages every time the page is loaded.

**Comment by Toflar** [comment]
Closing in favor of https://github.com/contao/contao/pull/7795.
