### ISSUE TITLE
Hinweistext Felder Server-Cachezeit und Client-Cachezeit bei Seiten

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#757]
Die Hinweistexte zu den Feldern `Server-Cachezeit` und `Client-Cachezeit` bei Seiten lauten folgendermaßen:

> Der Zeitraum in Sekunden, nach dem die Seite von einem gemeinsam genutzten Cache als veraltet eingestuft werden soll.
> 
> Der Zeitraum in Sekunden, nach dem die Seite vom Browser als veraltet eingestuft werden soll.

Es können jedoch verschiedene Zeiträume in Sekunden, Minuten, Stunden und Tagen ausgewählt werden, die Angabe "Zeitraum in Sekunden" ergibt daher wenig Sinn.

**Comment by xchs** [comment]
Jetzt habe ich eine Weile nach dem Ticket gesucht, weil ich wusste, dass genau das Gleiche vor einigen Wochen schon jemand angesprochen hatte, aber das war in Slack. :)

**Comment by dmolineus** [comment]
Vermutlich meinst du #661

**Comment by xchs** [comment]
Oh ja, genau. Danke. Ich wusste ja, da war was... 😄 
Auf Slack hatte es ja auch @zonky2 angesprochen.

Und jetzt weiß ich auch, warum ich vorhin per Suche nichts gefunden hatte: Im Ticket steht "chaching" und ich habe nach "cache" gesucht 😸

**Comment by leofeyer** [comment]
Duplicate of #661

**Comment by zonky2** [comment]
schreibfehler gefixt
