### ISSUE TITLE
adjust manager-bundle to current Symfony best practises?

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#758]
Currently the manager-bundle loads the following configuration files from `config/`:

* `config/config.yml`
* `config/config_dev.yml`
* `config/config_prod.yml`
* `config/parameters.yml` (legacy)
* `config/routing.yml`

I was wondering if the manager-bundle should be adjusted to the current Symfony 4 practises:

1. The `.yaml` file extension is used by default rather than `.yml`. 
2. The `routing.yml` is now called `routes.yaml` by default. 
3. The configuration of bundles/packages is now split into individual `.yaml` files within the `config/packages/` folder.

I don't think 3.) makes sense within the Contao Managed Edition - but may be 1.) and 2.) should be supported for a more unified experience - and a unified documentation?

**Comment by fritzmg** [comment]
Also: shouldn't the `config/services.yml` be automatically loaded as well, if present?

**Comment by aschempp** [comment]
To be precise, the bundle only loads one of the config files, and you need to import the other one(s) accordingly.

The problem with "supporting" the new version is that the old one must remain for BC, and that means there will be 20 options at some point, with no clear benefit except an "updated" file name?
