### ISSUE TITLE
Session gets started when accessing /contao

### ISSUE THREAD

**Issue by ausi** [contao/contao#7585]
### Affected version(s)

5.3, 4.13

### Description

Opening https://demo.contao.org/contao/ sets a Session Cookie and CSRF Cookie before the Login. We Night want to fix that?

/cc @fritzmg

**Comment by fritzmg** [comment]
4.13 is affected too, yes.

We should:

* Avoid redirecting to `/contao/login` with the `redirect` query parameter pointing back to `/contao` when accessing `/contao`, since this is superfluous (i.e. we should redirect from `/contao` to `/contao/login` without any query parameters).
* Not start a session when accessing any `/contao` route while not being logged in yet (the session should be started after successful authentication).

**Comment by leofeyer** [comment]
Is this really a problem? If someone opens the login page, we can be 99.999% sure that their next step will be to log in. And then they would get the cookie anyway.

**Comment by aschempp** [comment]
do we know why the session is started? I wouldn't think about it too much either, unless it is a bug somewhere.

**Comment by fritzmg** [comment]
> do we know why the session is started?

Symfony always sets a `_security.<firewall-name>.target_path` variable in the session for non-stateless firewalls - which we do not actually need (see #7605).

**Comment by aschempp** [comment]
I meant what code does that 😅

**Comment by fritzmg** [comment]
The firewall's `ExceptionListener` when the 401 exception is thrown when accessing `/contao` without being logged in:

https://github.com/symfony/symfony/blob/cdc130d6f96b90034fe792eaf5204b894a87fd78/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L206-L208

**Comment by aschempp** [comment]
Thanks! Anyone remember the reason we're storing the redirect in the URL instead of the default Symfony setup? Maybe that's a leftover from Symfony 5 / old security?

**Comment by bytehead** [comment]
I think we ported that behaviour even from before Symfony Security times.

**Comment by fritzmg** [comment]
`referer`/`redirect` handling was added in https://github.com/contao/contao/commit/f4e8b499cbb3d80b0605b46f23be211b2f334abb as far as I can see - and then later improved in https://github.com/contao/contao/commit/ae86d71b661ca80c1573113dfe1ba4d66ad79737

**Comment by aschempp** [comment]
If I understand correctly, the `redirect` query parameter is required because the session is per firewall, but we do redirect across firewalls (e.g. backend login for preview.php in the front end). Approving your PR then 👍

**Comment by leofeyer** [comment]
#7605 cannot be merged upstream to Contao 5, so I'm reopening this issue so we don't forget to create another pull request.
