### ISSUE TITLE
Positive feedback from server-side form validation

### ISSUE THREAD

**Issue by de-es** [contao/contao#7599]
### Description

Analog zur `error`-Klasse bei fehlgeschlagender Validierung eines Form-Widgets, wäre auch eine Klasse für erfolgreiche Validierung gut, damit man dies im Frontend entsprechend visualisieren kann.

**Comment by zoglo** [comment]
Anything that doesn't have the `error` class would count as a valid field so why not just use:
```css
.widget:not('.error') {
}
```

And in terms of visualizing it, you can already use css to do so; and this would work with every form field.

**Required and invalid:**
```css
input:required:invalid {
}
```
**Just invalid:**
```css
input:invalid {
}
```
**Valid:**
```css
input:valid {
}
```

**Comment by fritzmg** [comment]
> Anything that doesn't have the `error` class would count as a valid field so why not just use:

This would also be applied when the form has not been submitted yet.

**Comment by aschempp** [comment]
> This would also be applied when the form has not been submitted yet.

so we would need a class that is added to the form if it was submitted? Because then `form.submitted :not(.error)` could be used?

I also think this would not necessarily be easy. Is an empty field that is allowed to be empty considered valid? Or just empty? etc.?

**Comment by fritzmg** [comment]
> so we would need a class that is added to the form if it was submitted? Because then `form.submitted :not(.error)` could be used?

Correct. Either per widget - or per `<form>` would suffice as well.

> I also think this would not necessarily be easy. Is an empty field that is allowed to be empty considered valid? Or just empty? etc.?

This is something you could still control via CSS.

**Comment by ausi** [comment]
This is already possible using only CSS:

```css
.formbody:has(> .error) > .widget:not(.error) {
  background: green;
}
```

**Comment by de-es** [comment]
Vielen Dank für euer Feedback. Mein initialer use case bei der Anfrage war der, dass erst nach dem Submit und auch nur Pflichtfelder visuell validiert werden. Mit @ausi 's Vorschlag lässt sich das umsetzen.

Die Einsatzmöglichkeiten von `has` gehen manchmal noch unter. Damn you IE11! :grimacing:
