### ISSUE TITLE
404 und 403 Fehler im Backend

### ISSUE THREAD

**Issue by ReneLuecking** [contao/contao#76]
Wenn ich das Contao-Backend mit deaktiviertem oder geleertem Browser-Cache aufrufe, erhalte ich sehr viele 404- und 403-Fehler für CSS, JS und Bild-Dateien (siehe Bild). Die Fehler sind, soweit ich das bisher beurteilen kann, unabhängig davon, wo die Dateien im Dateisystem liegen. Bei mehrfachen neuladen der Seite mit deaktiviertem Browser-Cache ist es immer eine andere Auswahl an Dateien, die nicht geladen werden. Sobald der Browser-Cache aktiviert wird, werden mit jedem neuladen die erfolgreich geladenen Dateien im Cache abgelegt, sodass nach einigen Versuchen irgendwann alle Dateien im Cache liegen und keine Fehler mehr auftreten, bis der Cache wieder geleert wird.

Wenn ich die Dateien direkt im Browser aufrufe, klappt das immer.

![image](https://user-images.githubusercontent.com/21099788/45815497-20433280-bcd9-11e8-841a-352c3caeb957.png)

Ich bin mit nicht sicher, ob das Problem bei Contao oder Symfony liegt, oder ob es mit meinem Setup zusammenhängt. Daher wollte ich nachhören, ob da bereits etwas bekannt ist? Ich beitreibe den Webserver mit Contao innerhalb eines Docker-Containers basierend auf [php:7.2-apache](https://hub.docker.com/_/php/). Mein Hostsystem, von dem aus ich per Chrome oder Firefox auch Contao zugreife, ist Windows 10.

**Comment by leofeyer** [comment]
Bitte wende Dich mit solchen Fragen an das [Forum](https://community.contao.org/de/). Sollte sich herausstellen, dass es sich um einen Bug in Contao handelt, können wir dieses Ticket wieder öffnen.
