### ISSUE TITLE
New dca callback for rootNodes in universal picker and 

### ISSUE THREAD

**Issue by ben-eSM** [contao/contao#760]
In conjunction with the upcoming universal picker from @aschempp, I think it would be nice if there'd be a callback for the dca attribute rootNodes. Being able to only show partial trees in the picker would be quite interesting.

**Comment by leofeyer** [comment]
@aschempp WDYT?

**Comment by aschempp** [comment]
Not sure what exactly is needed. `rootNotes` is something the widget applies to the popup, but the DCA itself can also have callbacks and filters. The DCA should already have all callbacks necessary to modify anything?

**Comment by ben-eSM** [comment]
I think it would be nice if one has the possibility to only show specific entries when a table is shown via universal picker. I'm not sure how to realize that without such a callback. Is there an easy way to do this with the existing callbacks?

**Comment by aschempp** [comment]
I think you can do that with a `onload_callback` and set DCA filters?

**Comment by leofeyer** [comment]
@ben-eSM Has @aschempp's answer solved your problem? Can we close the issue?

**Comment by ben-eSM** [comment]
I didn't come back to that issue until today, but I think @aschempp's proposal to use an onload_callback should work.
