### ISSUE TITLE
be_ace configuration leads to problems with longer inputs 

### ISSUE THREAD

**Issue by Pellinger** [contao/contao#7602]
### Affected version(s)

5.4.3

### Description

In the template be_ace (version 5.4), the line
`editor.container.style.maxHeight = ‘calc(100vh - 320px)’;`
causes a problem when entering longer code in the (ace) text-areas. The length of the display of longer entries is then limited.

@zoglo suggested removing this line as a hotfix and already discussed further solutions with @ausi 

[Slack](https://contao.slack.com/archives/CJT61P8R1/p1728051766894749?thread_ts=1728050143.399519&cid=CJT61P8R1)

**Comment by zoglo** [comment]
Can confirm it in the demo by exceeding over 100 lines of code.

We do have the possibility to set a proper maxheight but this one will be limited by a number:
[https://ajaxorg.github.io/ace-api-docs/classes/src_virtual_renderer.VirtualRenderer.html#layerConfig.__type-9.maxHeig[…]-,maxHeight,-%3A%20number%3B](https://ajaxorg.github.io/ace-api-docs/classes/src_virtual_renderer.VirtualRenderer.html#layerConfig.__type-9.maxHeight:~:text=%3A%20number%3B-,maxHeight,-%3A%20number%3B)

Could try a combination of both with a style max-height of 100vh and that option, would need to be tested if it works.

**Comment by leofeyer** [comment]
What exactly is the problem?

**Comment by zoglo** [comment]
Lemme show it with proper screenshots

In the first one, the max-height will actually cut off any more lines that are added:
![image](https://github.com/user-attachments/assets/0274e135-32e0-4c1a-8516-ac5b8dde9168)

In the second one you won't see more code than the height of (100vh - 320px), you basically can not see the rest of the 320px:
![image](https://github.com/user-attachments/assets/0fd7da03-3718-4424-ae7d-6c404d01c058)
