### ISSUE TITLE
issues with naming folders

### ISSUE THREAD

**Issue by cscheibelhut** [contao/contao#7612]
### Affected version(s)

5.3.9

### Description

It often happens that a folder is named incorrectly, with spaces or special characters, etc. This is known to cause errors, especially when loading images stored in those folders. It would be very helpful if such naming mistakes could be prevented right from the start, making it impossible to create a folder with an incorrect name in the first place.

**Comment by fritzmg** [comment]
What kind of issue are you experiencing and what are the exact reproduction steps?

**Comment by cscheibelhut** [comment]
In this case, an image file used in a slider was stored in a folder with spaces in its name. The slider took a long time to load, and the following message appeared in the console:

/files/Test%20Folder/file.jpg Could not be loaded!

**Comment by fritzmg** [comment]
Spaces in folder or file names are not an issue.

Your issue seems to be related to your slider implementation, not with Contao itself. Or can this be reproduced with the content slider in Contao 5.3 itself?

**Comment by asaage** [comment]
May be off-topic because i dont know if it does anything to foldernames but I'd recommend https://github.com/numero2/contao-proper-filenames.

**Comment by cscheibelhut** [comment]
@fritzmg there doesn't seem to be an issue when using the content slider. It seems to be a problem with the eclipse theme slider.
Okay, thank you, I will contact them.

**Comment by timgatzky** [comment]
It's an issue of Themepunchs RevolutionSlider Script, not a Contao issue. The slider uses strict CSS background-image for its image processing and unescaped paths/filenames are invalid in CSS.
