### ISSUE TITLE
missing langauge files in contao/core

### ISSUE THREAD

**Issue by hamidpeywasti** [contao/contao#7615]
### Affected version(s)

5.*

### Description

Hi,
In some languages like "Persian (fa)", only "tl_style_sheet.xlf" and "tl_style.xlf" are included in core-bundle. Other files of this language are missing.

**Comment by zoglo** [comment]
@hamidpeywasti, that's because these aren't hitting the 95% translation mark anymore. It's an automated process and can be fixed by helping translating the contao project via https://explore.transifex.com/contao/

Some files aren't hitting the 95% translation mark, thus being excluded.

**Comment by hamidpeywasti** [comment]
Ok, currently, it is 97% for Persian. As a Persian translator of Contao, I will complete it.

There are `tl_style_sheet.xlf` and `tl_style.xlf` files in `fa` folder that are useless in Contao 5! These files don't exist in `en`, but they do in other languages.

![image](https://github.com/user-attachments/assets/9bdbd9b3-1179-4fc2-a359-f2e66123722c)

**Comment by leofeyer** [comment]
There were a couple of left-over files and even a missing one in the news bundle. I have just fixed this in 0a4ca17a35abf88dc86a8a62665dee93e0b02377. The changes will be released in the next version (Contao 5.3.16).

**Comment by hamidpeywasti** [comment]
@zoglo, I did it and hope so they will be added in the next release.
