### ISSUE TITLE
Error within clipboardPermissions when deleting an item within the clipboard

### ISSUE THREAD

**Issue by zoglo** [contao/contao#7619]
### Affected version(s)

5.3.x, 5.4.x, 5.x

### Description

How to reproduce:

- Copy an article
- Delete that article before pasting it anywhere

Since the non-existing item is still in the clipboard (and the clipboard stays active), it will now throw an indefinite error in the article view since `$this->getCurrentRecord` does not exist anymore.

```
array_replace(): Argument #1 ($array) must be of type array, null given
```

*Affected line*
https://github.com/contao/contao/blob/cc6b952e98de13572b1aeae89d67fc2b160fa9b0/core-bundle/contao/drivers/DC_Table.php#L6835

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7415
