### ISSUE TITLE
Contao-Manager  <= 1.8.9 --> Unexpected output  --> Installation schlägt fehl / nicht möglich

### ISSUE THREAD

**Issue by dguelden** [contao/contao#7625]
### Affected version(s)

<= 1.8.9 

### Description

Contao Installation schlägt fehl / nicht möglich:

- Komplett frisch installiertes System Ubuntu 24.04 LTS mit LXD
- Verwendung / Installation innerhalb von LXD Instanzen
- Thema ist unabhängig  vom verwendeten Webserver (Apache, Nginx, etc.)
- PHP in Version 8.3.6

Trace-Output:
a) Warning: Undefined array key "argv"
b) Warning: Trying to access array offset on null
c) Deprecated: realpath(): Passing null to parameter #1 ($path) of type string is deprecated

Details, siehe Dateianhänge:

[Bug-Report_Ausgabe_Erstinstallation.pdf](https://github.com/user-attachments/files/17342879/Bug-Report_Ausgabe_Erstinstallation.pdf)
[Bug-Report_PHP-8.3.6_phpinfo.pdf](https://github.com/user-attachments/files/17342880/Bug-Report_PHP-8.3.6_phpinfo.pdf)

**Comment by zoglo** [comment]
That should be posted in https://github.com/contao/contao-manager

**Comment by dguelden** [comment]
Thank you for your hint. Report created there and closed here.
