### ISSUE TITLE
Markdown content element footnotes not working

### ISSUE THREAD

**Issue by dubs10** [contao/contao#7638]
### Affected version(s)

5.3.15

### Description

Footnotes markdown code isn't converting correctly into relevant anchors and styles. Instead it's showing as raw markdown.

To replicate: Create any markdown content element. Paste in the demo code from the manual:
```
This is a text with a footnote.[^1]

[^1]: And this is the footnote.
```
View the content element on the front end. You'll see its not interpreted at all.

**Comment by fritzmg** [comment]
Footnotes are not part of the [basic syntax](https://www.markdownguide.org/basic-syntax/).

**Comment by dubs10** [comment]
> Footnotes are not part of the [basic syntax](https://www.markdownguide.org/basic-syntax/).

True, but then neither are tables, yet they are rendered. Footnotes are also mentioned in the manual. 

I think we either need some more clarity on which markdown elements are allowed in the manual, or consistency in which ones are rendered.

**Comment by fritzmg** [comment]
The `markdown` content element of Contao 5 uses [league/commonmark](https://github.com/thephpleague/commonmark) with the following extensions:

https://github.com/contao/contao/blob/b0bbaf4a22deeb88539eeaa2956aa16670f4ef4b/core-bundle/src/Controller/ContentElement/MarkdownController.php#L91-L102

If you need footnotes you can add the `FootnoteExtension` extension in your own content element that extends from the core one. See 

https://github.com/contao/contao/blob/b0bbaf4a22deeb88539eeaa2956aa16670f4ef4b/core-bundle/src/Controller/ContentElement/MarkdownController.php#L74-L78

**Comment by dubs10** [comment]
> The `markdown` content element of Contao 5 uses [league/commonmark](https://github.com/thephpleague/commonmark) with the following extensions:
> 
> https://github.com/contao/contao/blob/b0bbaf4a22deeb88539eeaa2956aa16670f4ef4b/core-bundle/src/Controller/ContentElement/MarkdownController.php#L91-L102
> 
> If you need footnotes you can add the `FootnoteExtension` extension in your own content element that extends from the core one. See
> 
> https://github.com/contao/contao/blob/b0bbaf4a22deeb88539eeaa2956aa16670f4ef4b/core-bundle/src/Controller/ContentElement/MarkdownController.php#L74-L78

Thanks! I'll give that workaround a go.

**Comment by fritzmg** [comment]
To be clear: this is what I have in mind:

```php
// src/Controller/ContentElement/MarkdownController.php
namespace App\Controller\ContentElement;

use Contao\ContentModel;
use Contao\CoreBundle\Controller\ContentElement\MarkdownController as ContaoMarkdownController;
use Contao\CoreBundle\DependencyInjection\Attribute\AsContentElement;
use League\CommonMark\ConverterInterface;
use League\CommonMark\Environment\EnvironmentBuilderInterface;
use League\CommonMark\Extension\Footnote\FootnoteExtension;
use League\CommonMark\MarkdownConverter;
use Symfony\Component\HttpFoundation\Request;

#[AsContentElement(category: 'texts')]
class MarkdownController extends ContaoMarkdownController
{
    protected function createConverter(ContentModel $model, Request $request): ConverterInterface
    {
        $converter = parent::createConverter($model, $request);
        
        if ($converter instanceof MarkdownConverter) {
            $environment = $converter->getEnvironment();

            if ($environment instanceof EnvironmentBuilderInterface) {
                $environment->addExtension(new FootnoteExtension());
            }
        }

        return $converter;
    }
}
```

This will override the core's `MarkdownController` with the `MarkdownController` of your App and add the `FootnoteExtension`.

**Comment by dubs10** [comment]
> To be clear: this is what I have in mind:
> 
> ```
> // src/Controller/ContentElement/MarkdownController.php
> namespace App\Controller\ContentElement;
> 
> use Contao\ContentModel;
> use Contao\CoreBundle\Controller\ContentElement\MarkdownController as ContaoMarkdownController;
> use Contao\CoreBundle\DependencyInjection\Attribute\AsContentElement;
> use League\CommonMark\ConverterInterface;
> use League\CommonMark\Environment\EnvironmentBuilderInterface;
> use League\CommonMark\Extension\Footnote\FootnoteExtension;
> use League\CommonMark\MarkdownConverter;
> use Symfony\Component\HttpFoundation\Request;
> 
> #[AsContentElement(category: 'texts')]
> class MarkdownController extends ContaoMarkdownController
> {
>     protected function createConverter(ContentModel $model, Request $request): ConverterInterface
>     {
>         $converter = parent::createConverter($model, $request);
>         
>         if ($converter instanceof MarkdownConverter) {
>             $environment = $converter->getEnvironment();
> 
>             if ($environment instanceof EnvironmentBuilderInterface) {
>                 $environment->addExtension(new FootnoteExtension());
>             }
>         }
> 
>         return $converter;
>     }
> }
> ```
> 
> This will override the core's `MarkdownController` with the `MarkdownController` of your App and add the `FootnoteExtension`.

Much appreciated, Fritzmg!

**Comment by aschempp** [comment]
Any reason we don't add that extension to the core element?

**Comment by leofeyer** [comment]
Yes, it doesn't hurt to add it, does it?

**Comment by fritzmg** [comment]
@Toflar chose GitHub flavored Markdown as the default. If you want more extensions than that you can extend it yourself (see above).

**Comment by leofeyer** [comment]
But GitHub does support footnotes? Let's just add the `FootnotesExtension` in the next feature release.

**Comment by fritzmg** [comment]
> But GitHub does support footnotes?

Does it? I don't see it here: https://github.github.com/gfm/
Nor would it be added by `League\CommonMark\Extension\GithubFlavoredMarkdownExtension`.

**Comment by leofeyer** [comment]
You are right 👍 Then let's close the PR as there is a solution documented above now.
