### ISSUE TITLE
Theme > Layout: nur vorhandene Spalten auswählbar machen

### ISSUE THREAD

**Issue by zonky2** [contao/contao#765]
**Affected version(s)**
all: 3.5 ... 4.8

**Description**  
bei der Demo auf Layout "1-column" gehen - dort ist nur eine Spalte definiert aber dennoch Spalte Links/Rechts auswählbar... es sollten nur mögliche Spalten angegeben werden

**How to reproduce**  

![Screenshot](https://user-images.githubusercontent.com/1045318/65030413-cb63e780-d93f-11e9-920a-d3da032e2022.jpg)

**Comment by leofeyer** [comment]
Geändert in 6556a1bcaa46cd7ba0363c3aa1ddce1810456279.
