### ISSUE TITLE
Array key "repeatEnd" is undefined

### ISSUE THREAD

**Issue by Jadascripts** [contao/contao#7655]
**Used Bundle and Contao Version**
4.13.49

**Used PHP Version**
8.3

In the File ModuleEventlist.php there has been a fix for the Issue #8447. This outputs a warning when php 8.3 is used, I assume because the Array Key $event['repeatEnd'] is not checked.
<img width="748" alt="Bildschirm­foto 2024-10-18 um 13 58 51" src="https://github.com/user-attachments/assets/4b62b4f6-50db-4c0d-bae7-d99c7a84f184">

<img width="1053" alt="Bildschirm­foto 2024-10-18 um 13 58 59" src="https://github.com/user-attachments/assets/7cdecabb-ccc8-4c40-a34a-e696b145af5b">

**Comment by rorych** [comment]
This seems to be a self-made problem ;) and can be closed.
The events are being manipulated in the project itself via the Hook getAllEvents.
Without the hook, the repeatEnd is always set correctly.

Case can be closed.

**Comment by fritzmg** [comment]
Hm, how exactly are you adding the events in the hook? May be we need to consider this case regardless.

**Comment by rorych** [comment]
It's an update we did, 3 years ago someone thought it was a good idea to loop the events, then loop the properties and if they are empty() unset the key. I'm still analyzing why. But seems clear that it is not the best idea ;)
