### ISSUE TITLE
Error in selecting element types

### ISSUE THREAD

**Issue by mlwebworker** [contao/contao#7664]
### Affected version(s)

5.3.16

### Description

Nach Update auf Version 5.3.16 gibt es Fehler bei den Elementtypen. Der Fehler wurde von einem Kunden in der Contao Academy gemeldet und ich habe daraufhin meine Testinstallation (Blanke Installation mit Contao Demo) aktualisiert und kann den Fehler reproduzieren.

<img width="455" alt="2024-10-22_172316" src="https://github.com/user-attachments/assets/b1558ca1-3559-4a4a-9347-063e90615bff">

Eine solch falsche Auswahl gibt es augenscheinlich bei allen Inhaltselementen (alle Elemente mit Twig-Templates?) 
Der Debugmodus im Backend zeigt keinen Fehler.
In der Online-Demo mit Contao 5.4.3 tritt der Fehler nicht auf.

**Comment by bytehead** [comment]
Probably related to #7516
