### ISSUE TITLE
After updating to 4.8.3 the debug button disappears

### ISSUE THREAD

**Issue by stefansl** [contao/contao#767]
**Affected version(s)**
4.8.3

**Description**  
After updating Contao 4.8.2 (may effect earlier versions, too) to 4.8.3 clicking the debug button throws an error:
`[2019-09-16 11:57:39] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "The "contao_manager.jwt_manager" service is synthetic, it needs to be set at boot time before it can be used." at /var/www/metten/contao4/vendor/symfony/dependency-injection/Container.php line 260 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): The \"contao_manager.jwt_manager\" service is synthetic, it needs to be set at boot time before it can be used. at /var/www/metten/contao4/vendor/symfony/dependency-injection/Container.php:260)"} []`
This happens, when I reload the backend without deleting the browser cache.

After deleting the browser cache the debug button disappears.

Deleting/renaming /.env solves the issue here.

**How to reproduce**  
composer update ;)

**Comment by aschempp** [comment]
I think there are two issues here:
1. the cache problem – not sure if/how we can fix that
2. the fact that the `.env` affects whether the button is visible in the back end, which should not be the case here (no `APP_ENV=` in the file)

**Comment by stefansl** [comment]
I tested it on another server -> same issue. But deleting .env after updating contao solved the issue and the browser cache problem is obsolete.

**Comment by leofeyer** [comment]
Symfony automatically populates the `APP_ENV` variable, even if it is not actually set in the `.env` file. 🤦‍♂ 

https://github.com/symfony/symfony/blob/1efae63e64d765d786ca50e9181c57b54587afd9/src/Symfony/Component/Dotenv/Dotenv.php#L90-L92

So I guess we cannot rely on the `$_SERVER['APP_ENV']` check for the debug bar. Reverting 9f2ea76205bc12764afbb0deaa2971bb157a89bf will fix the issue.

**Comment by leofeyer** [comment]
See #775.
