### ISSUE TITLE
No FileProvider within the BackendSearch

### ISSUE THREAD

**Issue by zoglo** [contao/contao#7676]
### Affected version(s)

5.x

### Description

There are no search results (for files), provider is `null`
This happened after #7627 has been introduced.

**Edit:**
Nowadays we'd use `cmsig:seal:index-create`

**Comment by m-vo** [comment]
Cannot confirm, it's working for me. Did you run `contao:backend-search:index`?

**Comment by zoglo** [comment]
Did run it twice on the latest changes (as it's part of the composer update)

Edit:
Just ran the command (it's still not finished) and it did found results so consider this closed.

Can't explain why it didn't do it on the composer update or on the first tries on the test environment (Unix)

**Comment by m-vo** [comment]
You are maybe confusing building the index (which happens during `contao:setup`) and indexing (which you need to trigger yourself)?
