### ISSUE TITLE
Inserttags are not supported within the field "Additional <head> tags"

### ISSUE THREAD

**Issue by benfolds** [contao/contao#7695]
### Affected version(s)

5.3.11

### Description

I am not sure what is the problem, and also seen in #2537 that this normally should work 🥴?

When inserting something like this inside the layout at the additional <head> tags field:

```
<meta property="og:title" content=" {{page::pageTitle}} ">
<meta property="og:description" content="{{page::description}}">
```

the insert tags will get printed out as they are. 
![image](https://github.com/user-attachments/assets/5d32a40e-0287-4fd7-947a-69529655c739)

**Comment by benfolds** [comment]
They are also not resolved within the body-class field. Printing out something like that is very helpful:

```{{page::alias}} parent--{{page::parentAlias}}```

**Comment by ausi** [comment]
I was not able to reproduce that on https://demo.contao.org/

Are you using a custom `fe_page` template? Maybe one that is written in Twig?
See https://docs.contao.org/dev/framework/templates/creating-templates/#insert-tags

**Comment by benfolds** [comment]
You are right! We are extending the fe_page at `templates/fe_page.html.twig` with this block:
```
{% extends "@Contao/fe_page.html.twig" %}

{% block head %}
    {{ parent() }}
    {{ vite() }}
{% endblock %}
```

There is no custom `fe_page.html5` file.

I tried different ways to replace the inserttags within parent like `{{ parent()|insert_tag }}` or `{{ insert_tag(parent()) }}` but this does not work.

**Comment by ausi** [comment]
This is a bug. We probably need to replace the insert tags somewhere here: https://github.com/contao/contao/blob/a5b7b8b9f6385a6c9726e7421871a29d4536fcf3/core-bundle/src/Twig/Extension/ContaoExtension.php#L351 but only if it is a FrontendTemplate or Widget as this is the check we use here: https://github.com/contao/contao/blob/a5b7b8b9f6385a6c9726e7421871a29d4536fcf3/core-bundle/contao/library/Contao/TemplateInheritance.php#L145-L146
And we should not replace insert tags in the `arrBlocks` array that has the rendered output of the twig template.

**Comment by ausi** [comment]
@benfolds can you test if the changes from #7753 would fix your issue?

**Comment by benfolds** [comment]
Just tested, running! 👌
