### ISSUE TITLE
Upstream merge issue

### ISSUE THREAD

**Issue by Toflar** [contao/contao#7697]
### Affected version(s)

5.3 && 5.4

### Description

https://github.com/contao/contao/commit/7097bfeab247df3bcbb1930026a40dd6426f1f4f was apparently not properly merged upstream, the limit is still set to `30` in the latest 5.3 and 5.4 versions.

**Comment by leofeyer** [comment]
Fixed in a262bd18a4a334076f1d6f911932859fa8b1bc86.
