### ISSUE TITLE
2FA: Security Token anzeigen

### ISSUE THREAD

**Issue by TB1234** [contao/contao#77]
**Description**  
Aktuell wird im BE nur ein Barcode zum scannen angezeigt. Allerdings gibt es auch die Möglichkeit, 2FA zu verwenden, ohne das ich einen Barcode Scanne oder aber das ich gar keinen Barcode Scanner zur Verfügung habe. Für diesen Fall wäre es gut, wenn der Code zusätzlich mit angezeigt werden würde. Imo ist dies eigentlicht Standard und wird auch bei allen anderen großen Web-Systemen so gemacht, die 2FA anbieten (Git, Amazon, ...)

**Example**  
Entfällt da oben erklärt.

**Comment by leofeyer** [comment]
> Für diesen Fall wäre es gut, wenn der Code zusätzlich mit angezeigt werden würde. 

Was genau meinst Du mit "Code"? Den `otpauth://`-Link?

**Comment by TB1234** [comment]
Nein. Den sog. TOTP Seed. Den kannst du dann z. B. in Programme wie KeePass etc. übernehmen.

**Comment by leofeyer** [comment]
@bytehead /cc

**Comment by bytehead** [comment]
Der TOTP Seed setzt sich aus verschiedenen Parametern zusammen:
```php
```

**Comment by bytehead** [comment]
Der TOTP Link setzt sich aus verschiedenen Parametern zusammen:
```php
$totp = new TOTP(
    $user->getEmail(),
    $user->getOtpSecret(),
    $period,
    $digest,
    $digits
);
```

~Was davon meinst du, müsste sichtbar sein?~
Du meinst mit Seed wohl den Secret?

In meinem lokalen Beispiel (Contao Official Demo) ist die generierte URL folgende:
`otpauth://totp/http%3A%2F%2F127.0.0.1%3A8002:k.jones@http%3A%2F%2F127.0.0.1%3A8002?secret=RI2FPZK7NHQYTSUNLXAHJOUO4NDFPJEWZTZIDGKYK562UIR7IDF56CHW2PNS5U4I6XLXPYW3JQN65XF4KN754UDRQR2DUCSK7HEP4YN2H567M5U6PNA2ZFJUOEFJ3V7CXMQIRB7TBN63PG2TLCR5D3ROAYGU673XCOEYPFFEAS3JIFAI3TPZGA6Z3GAF7TXNLDT4FTL6KL25W&issuer=http%3A%2F%2F127.0.0.1%3A8002`

Der Secret ist eher lang - ich weiss nicht ob du das von Hand irgendwo eintippen willst? :thinking:

Anbei ein Screenshot, wie ich dein Anliegen verstehe:
![bildschirmfoto 2018-09-20 um 18 26 47](https://user-images.githubusercontent.com/754921/45832656-d66f4200-bd02-11e8-9681-1d55731a6123.png)

**Comment by TB1234** [comment]
Naja meine Systeme können markieren und dann kann ich Copy und Paste machen ;-)

Kennst du das nicht von anderen Systemen? Also ich bekomme überall den Seed angezeigt und kann den dann weg kopieren. Ich probier das mal mit den Seed aus den der URL aus einem Contao System.

**Comment by bytehead** [comment]
> Naja meine Systeme können markieren und dann kann ich Copy und Paste machen ;-)

Stimmt! 😁

Einbauen könnten wir das sicher. 
Ist mir bis jetzt (offensichtlich nicht bewusst) nie begegnet.

Was denkst du @leofeyer?

**Comment by TB1234** [comment]
Hm, ich hab das jetzt mal versucht. Allerdings war es mir nicht möglich, 2FA zu aktivieren. Ich habe en Seed direkt aus dem Link übernommen und dann in die TOTP Funktion von KeepasXC übernommen. Der dann damit erzeugte Code wird jedoch nicht aktzeptiert.

Ich vermute aber, das hier nichts besonderes dahinter ist oder? Es ist ein normaler RFC 6238 TOTP Code oder?

**Comment by bytehead** [comment]
~RFC 4648 wenn ich mich richtig erinnere...~

Sorry, natürlich RFC 6238 mit der Library von Spomky-Labs: https://github.com/Spomky-Labs/otphp

**Comment by TB1234** [comment]
Naja aber gängig für TOTP ist doch 6238. https://tools.ietf.org/html/rfc6238

Oder ist das RFC 4226 mit HTOP?

**Comment by TB1234** [comment]
Ah, ich habs... In der URL wird der Seed Base32 Encoded angegeben. In der Ausgabe wie ich diese hier benötige muss diese jedoch im Klartext erscheinen. Nur so kann ich dann was damit anfangen.

Hier die Infor wie die URL Aufgebaut ist: https://github.com/google/google-authenticator/wiki/Key-Uri-Format

**Comment by bytehead** [comment]
Das Secret ist binary (`random_bytes(128)`), das kann aber der Browser nicht darstellen.

**Comment by TB1234** [comment]
Ja, das hab ich gesehen als ich es gerade umgewandelt habe. ;-)

Dann ist das aber nur nutzbwar wenn ich das Scanne und direkt in eine entsprechende App nutze. Das nicht bei jedem der Fall und somit z. B. auch für mich nicht nutzbar. Warum auch Binary? An sich ist das doch egal solange der Seed sicher ist.

![amazon](https://user-images.githubusercontent.com/9974734/45834275-028cc200-bd07-11e8-8ee2-9239a9dfddbc.png)
Hier mal ein Beispiel wie das z. B. bei Amazon aussieht. So kenne ich das und so ist das imo auch praktikabel.

**Comment by leofeyer** [comment]
Ich finde die Idee gut. Natürlich nur wenn es auch funktioniert. 😄

**Comment by bytehead** [comment]
Also dürfte einfach der Secret nicht mehr binary sein.
Ich guck mir das an, kannst an mich assignen @leofeyer.

> Warum auch Binary? 

Wohl kein spezieller Grund, ich bin einfach der Dokumentation gefolgt: https://github.com/Spomky-Labs/otphp/blob/v9.0/doc/Customize.md#secret :)

**Comment by leofeyer** [comment]
Siehe #86.
