### ISSUE TITLE
Autoteaser

### ISSUE THREAD

**Issue by kroerig** [contao/contao#770]
**Description**  
Joomla-User und auch Wordpress-User sind es gewöhnt ohne große Mühen vom System einen Teaser generiert zu bekommen.

In Joomla indem man einfach im Texteditor einen Trenner einfügt. Der Text bis dorthin wird als Teaser übernommen. Im WP stell man einfach die Anzahl der Zeichen, die als Teasertext angezeigt werden sollen. Sollte das mal mitten ins Wort fallen sucht WP nach einem Leerzeichen, an dem dann der Teaser endet.

In Contao muss man den Teaser extra pflegen.

Wäre es möglich/ gewünscht eine solche Funktion auch in Contao einzubauen? Umsteiger von Joomla und WP haben sich daran gewöhnt hier keine doppelte Arbeit machen zu müssen.

**Comment by fritzmg** [comment]
Wie stellst du dir das vor? Willst du zu Contao 2 zurück kehren, wo der News Detail Inhalt nur aus einem Textfeld besteht? ;)

Das was du haben willst passt nicht in das Konzept von Contao.

**Comment by asaage** [comment]
Ich find' Autoteaser jetzt irgendwie auch nicht so prall - pflegen ist gut.
Allerdings fehlt im core immernoch ein passendes content-element um mit Teasern umzugehen https://github.com/contao/core-bundle/issues/1417

**Comment by kroerig** [comment]
> 
> 
> Wie stellst du dir das vor? Willst du zu Contao 2 zurück kehren, wo der News Detail Inhalt nur aus einem Textfeld besteht? ;)
> 
Nein, aber nicht alles doppelt pflegen und die Umsteiger abholen.

In den meister Fällen dürfte der Teaser der Anfang des Textes oder eine kurze Zusammenfassung, die dann meist auch im Artikel vor dem Haupttext steht.

Da könnte man doch z.B. ein Teaser-Element bauen, dass man einfach ganz normal in den Artikel einbaut, dessen Inhalt dann aber für den Teaser genommen wird.

**Comment by fritzmg** [comment]
> Nein, aber nicht alles doppelt pflegen und die Umsteiger abholen.
> 
> In den meister Fällen dürfte der Teaser der Anfang des Textes oder eine kurze Zusammenfassung, die dann meist auch im Artikel vor dem Haupttext steht.

Die Frage war, wie du dir das vorstellst. Der Detailinhalt ist mit Inhaltselementen aufgebaut. Meinst du, du möchtest, das einfach das erste (Text) Inhaltselement der Teaser sein soll? ggf. mit der selben Logik wie bei WordPress?

Halte ich für umständlich. Könnte man aber per Erweiterung einbauen, wenn man will.


> Da könnte man doch z.B. ein Teaser-Element bauen, dass man einfach ganz normal in den Artikel einbaut, dessen Inhalt dann aber für den Teaser genommen wird.

Wozu ist das gut? Es gibt ja schon ein Teaser Feld. Außerdem ist das ja genau das, was du nicht haben möchtest.

**Comment by kroerig** [comment]
Ja, es gibt das Teaserfeld. Das hat aber (bisher) keinen Bezug zu den Inhaltselementen. Der Inhalt muss separat eingetragen werden. Eleganter wäre, wenn der Teaser automatisch aus dem Artikelinhalt generiert würde. Dazu würde es ja reichen, wenn man einem Textement einfach die Funktion "Teaser" zuweisen könnte. Daraus könnte Contao dann den Teaserinhalt nehmen.

WordPress ist für die meisten Anwender intuitiv bedienbar. Warum? Weil das System ihnen die Technik abnimmt. Ich füge einfach ein Element "Newsvorschau" ein und das System baut einen Teaser ohne dass ich einen eintragen musste. Diese kleinen Automatismen machen das System so beliebt und erfolgreich. (Gut, dafür kann es andere Sachen nicht)

**Comment by aschempp** [comment]
Die News werden ja per Template gesteuert, und im Prinzip lässt sich das doch bereits problemlos per Template machen? In etwa so:

```php
$teaser = StringUtil::substr(strip_tags($this->text), 200);
```

**Comment by Nightwing0815** [comment]
@kroerig @aschempp 
Hier der Code für News und Events, wie aschempp schon gepostet hat:

news_latest.html5:

		<?php if ($this->teaser): ?>
		  <?php echo \StringUtil::substr($this->teaser,80); ?>
		<?php else: ?>
		  <?php echo \StringUtil::substr($this->text,80); ?>
		<?php endif; ?>		

event_teaser.html5:

        <?php if (!$this->addBefore): ?>
		  <?php if ($this->teaser): ?>
		    <?php echo \StringUtil::substr($this->teaser,80); ?>
		  <?php else: ?>
		    <?php echo \StringUtil::substr($this->details,80); ?>
		  <?php endif; ?>		
        <?php endif; ?>


        <?php if ($this->addBefore): ?>
		  <?php if ($this->teaser): ?>
		    <?php echo \StringUtil::substr($this->teaser,80); ?>
		  <?php else: ?>
		    <?php echo \StringUtil::substr($this->details,80); ?>
		  <?php endif; ?>		
	    <?php endif; ?>



Funktioniert wunderbar :-)

ToM

**Comment by Aybee** [comment]
substr()
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/StringUtil.php#L42
substrHtml()
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/StringUtil.php#L104

**Comment by leofeyer** [comment]
Ich fände es schon nice, wenn wir kein Teaser-Feld mehr in den Einstellungen hätten. Stattdessen könnte man z.B. eine "Erstes Inhaltselement als Teaser verwenden"-Checkbox einbauen.

Allerdings wäre das ein BC-Break.

**Comment by asaage** [comment]
Ich hab da verschiedene Anwendungsfälle (teilweise gemischt in ein un dem selben Archiv).
z.B. Weiterleitung auf externe/interne Seite (da will ich nicht auf das Teaser Feld verzichten und genötigt werden ein Inhaltselement anzulegen).
einige Seiten haben auch nur Listings in denen der Teaser gar nicht angezeigt wird (simple oder short weiss ich gerad nicht) da ist es mangels content oftmals auch ausreichend, nur das Teaserfeld zu bestücken und keine Inhaltselemente anzulegen.
Ich find das eigentlich gut so, wie es ist.

**Comment by contaoacademy** [comment]
Ich nutze den Teasertext auch häufig wie @asaage das beschreibt ohne extra Inhaltselemente.

Allerdings gibt es auch Installationen da wäre die Idee von @leofeyer mit der Checkbox sehr hilfreich. Frage ist halt jetzt, was der häufigere Anwendungsfall ist. Oder könnte man die Checkbox auch optional einbauen. So dass man "entweder oder" nutzen kann?

**Comment by kroerig** [comment]
Es würde ja schon reichen, wenn man einfach ein Inhaltsfeld mit der Eigenschaft "Teaser" versehen könnte. Ähnlich wie bei hervorgehobenen News. Dann könnte das Teaserfeld bleiben, aber wenn bei einem Element dieses Flag gesetzt ist, dann über schreibt das das Teaserfeld.

So kann dann auch ein einfacher Redakteur, der kein Recht hat die Seiteneigenschaften zu bearbeiten, den Teaser beeinflussen.
@leofeyer Das auf das erste Element zu beschränken, würde verhindern, dass ich in der News z.b. folgenden Aufbaut habe:
- Überschrift
- Bild
- Einleitung
- Haupttext

In dem Fall würde ich dann einfach hingehen und z.B. Einleitung als Teaser flaggen, oder das Bild mit in die Einleitung übernehmen, damit es mit im Teaser erscheint.

**Comment by kroerig** [comment]
> 
> 
> Ich fände es schon nice, wenn wir kein Teaser-Feld mehr in den Einstellungen hätten. Stattdessen könnte man z.B. eine "Erstes Inhaltselement als Teaser verwenden"-Checkbox einbauen.
> 
> Allerdings wäre das ein BC-Break.

Ich stolpere gerade wieder über diesen Vorschlag? Besteht die Chance, dass da was kommt?

**Comment by m-vo** [comment]
PR erhöht Chance denke ich, aber vermutlich ist das was was nicht ganz unkontrovers diskutiert wird. :slightly_smiling_face:

**Comment by fritzmg** [comment]
> Ich stolpere gerade wieder über diesen Vorschlag? Besteht die Chance, dass da was kommt?

You can do it with a fairly simple application customisation:

```php
// src/EventListener/UseFirstContentElementAsTeaserListener.php
declare(strict_types=1);

namespace App\EventListener;

use Contao\ContentModel;
use Contao\CoreBundle\ServiceAnnotation\Hook;
use Contao\FrontendTemplate;
use Contao\Module;

/**
 * This will fetch the first "text" content element 
 * of a news article and uses that for the teaser.
 * 
 * @Hook("parseArticles")
 */
class UseFirstContentElementAsTeaserListener
{
    public function __invoke(FrontendTemplate $template, array $newsEntry, Module $module): void
    {
        if (!empty($newsEntry['teaser'])) {
            return;
        }

        $newsId = (int) $newsEntry['id'];
        $template->teaser = function () use ($newsId): ?string  {
            $options = ['order' => 'sorting', 'limit' => 1, 'return' => 'Model'];
            $ce = ContentModel::findPublishedByPidAndTable($newsId, 'tl_news', $options);

            if (null === $ce || 'text' !== $ce->type) {
                return null;
            }

            return $ce->text;
        };
    }
}
```

**Comment by kroerig** [comment]
> 
> 
> PR erhöht Chance denke ich, aber vermutlich ist das was was nicht ganz unkontrovers diskutiert wird. 🙂

Ich bin kein Entwickler, aber wenn der Code von @fritzmg funktioniert, dann sollte sich das ja umsetzen lassen.

**Comment by fritzmg** [comment]
As already said, you can customise your Contao installation to achieve what you want.

**Comment by aschempp** [comment]
> Ich bin kein Entwickler, aber wenn der Code von @fritzmg funktioniert, dann sollte sich das ja umsetzen lassen.

Nicht jede Funktion die man programmieren _kann_, _muss_ man auch einbauen. Wenn eine Funktion für die Mehrheit keinen Mehrwert bietet oder das System unnötig kompliziert, dann ist dafür eine Erweiterung oder eine App-spezifische Anpassung das Richtige.

**Comment by andre5tz** [comment]
Hallo,

ich bin über den Beitrag im Forum [Erfahrungsbericht mit Redakteuren / Best Practice?](https://community.contao.org/de/showthread.php?81304-Erfahrungsbericht-mit-Redakteuren-Best-Practice&highlight=Erfahrungsbericht) wieder auf das Thema gestoßen. Über die Suche, was bereits diskutiert wird, bin ich hier gelandet.

Aus Anwendersicht: 
Es ist extrem störend, einen Nachrichtenteaser mit Bild zu erstellen, um den gleichen Teaser dann nochmal als Inhaltselement einzutragen. Ich habe weit über 1.000 Nachrichtenbeiträge in Contao erstellt und ein Teaser mit Bild nervt echt am meisten, sorry. Ich wundere mich daher nicht, wenn ich den Erfahrungsbericht aus dem Forum lese.

Die Lösung über ein Template geht bestimmt, muss aber alle bisherigen Beiträge berücksichtigen und neue Anwender/Webmaster/Administratoren werden es unter Umständen nicht wissen. Contao könnte aus dem Grund vielleicht nicht ausgewählt werden.

**Ein Vorschlag zur Diskussion:**

1. Ein Auswahlfeld im Nachrichtenbeitrag "Teaser als Inhaltselement".
2. Ein neues Inhaltselement Teaser
3. Dieses Inhaltselement wird automatisch mit den Teaser-Daten aus dem Nachrichtenbeitrag gefüllt und als Inhaltselement angelegt, bzw. greift auf die Daten direkt zu.
4. Wird das Inhaltselement "Teaser" verändert, ändert sich auch der Bereich (Text und Bild) im Nachrichtenbeitrag.
5. Wird des Inhaltselement "Teaser" gelöscht, wird das Auswahlfeld "Teaser als Inhaltselement" im Nachrichtenbeitrag deaktiviert. (Der Inhalt (Text und Bild im Nachrichtenbeitrag) wird nicht gelöscht.)
6. Wird das Kontrollkästchen "Teaser als Inhaltselement" deaktiviert, wird das Inhaltselement Teaser gelöscht. (Optional mit Information "Wollen Sie wirklich deaktivieren, damit wird das Inhaltselement Teaser aus dem Beitrag gelöscht.")
7. Optional ein Feld "Teaserlänge" im Nachrichtenarchiv, damit der Webmaster noch etwas Kontrolle hat, wie lang ein Teaser max angezeigt wird.

Vorteil:
Ich sehe keine Problem für alte Beiträge.
Redakteure sollten sich damit schnell zurechtfinden.
Neue Anwender/Webmaster/Administratoren sehen die Optimierung sofort und müssen nicht erst nach langjähriger Erfahrung feststellen, dass man mal schnell was "programmieren" kann.

Für mich persönlich gehört es fest einzustellen für die Nachrichten und Events. Artikelteaser wäre sicher auch zu überlegen, ich denke aber hier wird das Problem nicht so oft auftauchen.

Ich glaube, jeder der regelmäßig Nachrichtenbeiträge und Veranstaltungen mit Contao erstellt, würde sich riesig freuen, ich zumindest.

Was meint Ihr?

Vielen Dank :-)

Viele Grüße
André

**Comment by fritzmg** [comment]
> Es ist extrem störend, einen Nachrichtenteaser mit Bild zu erstellen, um den gleichen Teaser dann nochmal als Inhaltselement einzutragen.

Why do you want to do that? If you create no content elements for your news, the teaser will automatically be displayed with the default `news_full` template in the newsreader module, alongside the news teaser image. See https://github.com/contao/contao/blob/6bf5ae1a6bfa365375514bd3a604996882fd187f/news-bundle/src/Resources/contao/templates/news/news_full.html5#L14-L30

**Comment by andre5tz** [comment]
> Why do you want to do that? If you create no content elements for your news, the teaser will automatically be displayed with the default `news_full` template in the newsreader module, alongside the news teaser image. See

Ganze einfach, der Teaser ist in der Regel nur ein kurzer Auszug aus der Nachricht, wie der Name schon sagt, Teaser. 
Die eigentliche Nachricht hat dann den entsprechend längeren Text und was sonst noch an Inhaltselementen dazu kommt.

Für uns, eine Gemeindeverwaltung, sind das die "amtlichen'" Nachrichten und Bekanntmachungen. "Kurznachrichten" kommen selten vor, da ist es dann einfach, stimmt natürlich.

So wie es jetzt ist dürfen wir uns nicht wundern, wenn einfach alles in den Teaser "geknallt" wird, geht schneller und ist schneller erledigt. Dann hätten wir die Nachrichtenerweiterung aber nicht mit Inhaltselementen erweitern müssen. 
Die Umsetzung war aber notwendig, hilfreich und richtig!

Ich sehe es als logischen Schritt zur Vollendung der Nachrichten und Events-Erweiterungen :-)
Ist aber erst mal nur meine Sichtweise, das ist auch klar.

**Comment by fritzmg** [comment]
What exactly is it that you want changed? If you want the feature as described above, there is already a solution for that, if you need that in your Contao instance. See https://github.com/contao/contao/issues/770#issuecomment-811096829

**Comment by andre5tz** [comment]
Yes of course. 
Es ist nur ein Versuch von mir, einen Ansatz zu beschreiben, der allen nutzen könnte.

Aus Sicht eines Programmierers stellt sich die Frage warum fragt der denn, geht doch, ist doch einfach zu lösen, Ansatz ist doch schon beschrieben!

Aus Sicht des Anwenders, OK, dann lassen wir es eben! Geht nicht ... ist technisch nicht möglich, kann ich nicht, verstehe ich sowieso nicht ;-)

Ganz im ernst.
Ich habe nicht ansatzweise eine Ahnung, wie ich #770 (comment) updatesicher umsetzen sollte, müsste ich dann beauftragen oder selbst probieren.
Nur, wenn es so einfach ist und quasi auf dem Tablett liegt, warum kommt es dann nicht gleich in den Core?

Die Frage ist doch, ob es ein sinnvoller Vorschlag ist, der für die meisten Anwender einen Vorteil bringt oder eben nicht.


Jetzt treiben sich hier eher weniger Anwender rum. Dazu zeigt mir meine persönliche Erfahrung, dass viele Anwender die Dinge so hinnehmen wie sie sind und niemals auf die Idee kommen, einen Verbesserungsvoschlag zu machen. Meist wird "vor sich hingemeckert". Im Ergebnis kann sich ein Produkt dann aber nicht oder nur sehr langsam weiterentwickeln.

>  * This will fetch the first "text" content element 
>  * of a news article and uses that for the teaser.
>  * 
>  * @Hook("parseArticles")
>  */

Was würde in dem Fall #770 mit den "alten" Nachrichten passieren? Bekommen die alle einen zweiten Teaser?
Wäre damit zwingend das erste Textelement der Teaser, ein Vorschalten eines Inhaltselementes wäre demnach nicht mölich?

**Comment by fritzmg** [comment]
> Ich habe nicht ansatzweise eine Ahnung, wie ich #770 (comment) updatesicher umsetzen sollte, müsste ich dann beauftragen oder selbst probieren.

You only need to create the file as described and that's it (may be execute `composer install -o` afterwards, depending on your environment).

**Comment by andre5tz** [comment]
> Was würde in dem Fall #770 mit den "alten" Nachrichten passieren? Bekommen die alle einen zweiten Teaser?

**Comment by fritzmg** [comment]
> Was würde in dem Fall #770 mit den "alten" Nachrichten passieren? Bekommen die alle einen zweiten Teaser?

No, the described code only fetches the first content element, if the teaser is empty.

**Comment by andre5tz** [comment]
Ok, vielen herzlichen Dank, dann schaue ich die Tage mal, ob das eine Lösung ist, mit der ich zurecht komme. 👍 

Unabhängig davon bitte ich darum, das Thema nochmal aus Anwendersicht zu betrachten und zu überlegen, wie der Bereich in Contao zukünftig opitimiert werden kann, ohne Anpassungen und für alle gleich "sichtbar", würde mich freuen.

Vielen Dank nochmal und ein schönes Wochenende :-)

**Comment by andre5tz** [comment]
Habe mich an #770 versucht, brauche wohl Hilfe für dummies. Ich bekomme es nicht zum Laufen, leider.

Contao 4.4 (Testinstllation) und Contao 4.11, jeweils aktuell.
Neue Datei in /Pfad zu Contao/contao/vendor/contao/news-bundle/src/EventListener/UseFirstContentElementAsTeaserListener.php angelegt und den Inhalt aus #770 eingefügt. Auch mal <?php am Anfang der Datei eingefügt.

> You only need to create the file as described and that's it (may be execute `composer install -o` afterwards, depending on your environment).

Was müsste ich auf der Konsole genau eintragen? Systemwartung im Contao Manager hat nicht geholfen.

**Comment by fritzmg** [comment]
> Contao 4.4 (Testinstllation)

In Contao 4.4 reicht es nicht diese Datei einfach anzulegen, da muss der Hook auch noch zusätzlich in der `app/Resources/contao/config/config.php` registriert werden. In Contao 4.11 sollte es ohne Weiteres funktionieren, sofern du danach in deiner lokalen Entwicklungsumgebung zumindest `composer install` aufrufst (über die Konsole oder den Contao Manager).

> Systemwartung im Contao Manager hat nicht geholfen.

Im Contao Manager wäre das "Composer-Abhängigkeiten installieren" in der Systemwartung.

**Comment by aschempp** [comment]
I have created a draft pull request in https://github.com/contao/contao/pull/3313 which might add this feature to Contao 4.13

**Comment by andre5tz** [comment]
> > Contao 4.4 (Testinstllation)
> 
> In Contao 4.4 reicht es nicht diese Datei einfach anzulegen, da muss der Hook auch noch zusätzlich in der `app/Resources/contao/config/config.php` registriert werden. In Contao 4.11 sollte es ohne Weiteres funktionieren, sofern du danach in deiner lokalen Entwicklungsumgebung zumindest `composer install` aufrufst (über die Konsole oder den Contao Manager).
> Im Contao Manager wäre das "Composer-Abhängigkeiten installieren" in der Systemwartung.

Ich habe es heute nochmal mit der 4.11 versucht und über den Contao Manager 'composter install' ausgeführt. Leider kein Ergebnis. Ich bekomme es nicht zum Laufen, bei mir will der Autoteaser einfach nicht.

Mit  #3313 sehe ich die Lösung, von daher freue ich mich drauf und alles wird gut, bzw. noch besser. :-)
Eine Anmerkung noch, 

>     * maybe add the same feature to events etc?

Ja bitte.

Vielen Dank Euch
VG
André

**Comment by fritzmg** [comment]
@andre5tz if you still want this in Contao 4.9 or 4.11/12, you should contact the community for help :) (forum or Slack).
