### ISSUE TITLE
Global operations appear without configuration

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/contao#7702]
### Affected version(s)

Contao 5.3.17
PHP 8.2.24

### Description

I don't define the `all` key, but the `DefaultGlobalOperationsListener` set it anyway. I don't want an `all` key in my configuration. Same with all row operations as well.

![grafik](https://github.com/user-attachments/assets/b1c57dcf-a712-426d-953d-f271456edeff)

### Reproduce

```php
// contao/dca/tl_test.php

$GLOBALS['TL_DCA']['tl_test'] = [
    'config' => [
        'dataContainer' => \Contao\DC_Table::class
    ]
];
```

`php bin/console debug:dca tl_test`

```
array:2 [
  "config" => array:2 [
    "dataContainer" => "Contao\DC_Table"
    "ondelete_callback" => array:1 [
      0 => array:2 [
        0 => "contao.listener.data_container.record_preview"
        1 => "storePrecompiledRecordPreview"
      ]
    ]
  ]
  "list" => array:2 [
    "global_operations" => array:1 [
      "all" => array:4 [
        "href" => "act=select"
        "class" => "header_edit_all"
        "attributes" => "accesskey="e""
        "label" => & null
      ]
    ]
    "operations" => array:4 [
      "edit" => array:4 [
        "href" => "act=edit"
        "icon" => "edit.svg"
        "button_callback" => Closure(DataContainerOperation $operation): void^ {#4730
          returnType: "void"
          class: "Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener"
          this: Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener {#10199 …}
          use: {
            $actionClass: "Contao\CoreBundle\Security\DataContainer\UpdateAction"
            $table: "tl_test"
            $new: null
          }
          file: "D:\Laragon\www\contao-5\vendor\contao\core-bundle\src\EventListener\DataContainer\DefaultOperationsListener.php"
          line: "180 to 184"
        }
        "label" => & null
      ]
      "copy" => array:4 [
        "href" => "act=copy"
        "icon" => "copy.svg"
        "button_callback" => Closure(DataContainerOperation $operation): void^ {#10633
          returnType: "void"
          class: "Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener"
          this: Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener {#10199 …}
          use: {
            $actionClass: "Contao\CoreBundle\Security\DataContainer\CreateAction"
            $table: "tl_test"
            $new: null
          }
          file: "D:\Laragon\www\contao-5\vendor\contao\core-bundle\src\EventListener\DataContainer\DefaultOperationsListener.php"
          line: "180 to 184"
        }
        "label" => & null
      ]
      "delete" => array:5 [
        "href" => "act=delete"
        "icon" => "delete.svg"
        "attributes" => "data-action="contao--scroll-offset#store" onclick="if(!confirm(''))return false""
        "button_callback" => Closure(DataContainerOperation $operation): void^ {#10831
          returnType: "void"
          class: "Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener"
          this: Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener {#10199 …}
          use: {
            $actionClass: "Contao\CoreBundle\Security\DataContainer\DeleteAction"
            $table: "tl_test"
            $new: null
          }
          file: "D:\Laragon\www\contao-5\vendor\contao\core-bundle\src\EventListener\DataContainer\DefaultOperationsListener.php"
          line: "180 to 184"
        }
        "label" => & null
      ]
      "show" => array:3 [
        "href" => "act=show"
        "icon" => "show.svg"
        "label" => & null
      ]
    ]
  ]
]
```

**Comment by Tastaturberuf** [comment]
Here is the introducing commit https://github.com/contao/contao/commit/3d403b5ee98ce56c1c073803c7eac78387f440e6

**Comment by Toflar** [comment]
We cannot change that anymore, this would be a BC break. Maybe some `'all' => false` or so could work.

**Comment by fritzmg** [comment]
I think the intention was that if you define

```php
'global_operations' => []
```

as opposed to not defining `global_operations` at all, no default operations will be added. See

https://github.com/contao/contao/blob/a262bd18a4a334076f1d6f911932859fa8b1bc86/core-bundle/src/EventListener/DataContainer/DefaultGlobalOperationsListener.php#L39-L43

@aschempp can you confirm?

However the following lines will cause the default operations to be added again:

https://github.com/contao/contao/blob/a262bd18a4a334076f1d6f911932859fa8b1bc86/core-bundle/src/EventListener/DataContainer/DefaultGlobalOperationsListener.php#L47-L51

Changing this to

```diff
-   if (!array_filter($dca, static fn ($v, $k) => isset($defaults[$k]) || (\is_string($v) && isset($defaults[$v])), ARRAY_FILTER_USE_BOTH)) {
+   if ($dca && !array_filter($dca, static fn ($v, $k) => isset($defaults[$k]) || (\is_string($v) && isset($defaults[$v])), ARRAY_FILTER_USE_BOTH)) {
```

would make this possible again.

**Comment by Tastaturberuf** [comment]
@fritzmg  solution works fine for me.

**Comment by Tastaturberuf** [comment]
Maybe change this in the [DefaultOperationsListener](https://github.com/contao/contao/blob/5.x/core-bundle/src/EventListener/DataContainer/DefaultOperationsListener.php) as well.

```php
'global_operations' => [],
'operations' => [],
```
In this case there will be no global operations (intended) but all operations where generated. 

This should work like: if there are no keys(`global_operations`, `operations`), generate all possible operations. if there are keys, check for string and generate the operation if it matches. Do not touch other keys.

**Comment by fritzmg** [comment]
There is another issue: if you only define the following

```php
'global_operations' => [
    'foo' => […]
]
```

the `all` and `toggleNodes` operations will still be added (if applicable), even if you don't want them. There is also evidence that this might not be intentional as we currently define `all` and `toggleNodes` specifically for `tl_files` for example, since there is an additional `sync` global operation:

https://github.com/contao/contao/blob/a262bd18a4a334076f1d6f911932859fa8b1bc86/core-bundle/contao/dca/tl_files.php#L84-L91

If it is intentional that `all` and `toggleNodes` will _always_ be added when applicable, then we could omit these there.

**Comment by leofeyer** [comment]
> We cannot change that anymore, this would be a BC break. Maybe some `'all' => false` or so could work.

As discussed in the Contao call, this is the most compatible solution. @Tastaturberuf Can you create a pull request?

**Comment by aschempp** [comment]
We have discussed this again in the Core team (since I was not part of the Contao call). We couldn't come up with a good solution and I disagree with the `false`-approach.

If I understand @Tastaturberuf correctly in https://github.com/contao/contao/issues/7702#issuecomment-2462672786

> @fritzmg solution works fine for me.

you're referring to 

> I think the intention was that if you define
> 
> ```
> 'global_operations' => []
> ```
> 
> as opposed to not defining `global_operations` at all, no default operations will be added. See
> 
> https://github.com/contao/contao/blob/a262bd18a4a334076f1d6f911932859fa8b1bc86/core-bundle/src/EventListener/DataContainer/DefaultGlobalOperationsListener.php#L39-L43

This solves your problem anyway? So there's nothing (urgent) to fix here?

**Comment by fritzmg** [comment]
That is something we would need to fix in Contao. Currently the default operations are added regardless.

**Comment by aschempp** [comment]
Fixed in https://github.com/aschempp/contao/commit/f926dfaca905c235ebbbd7fcb6cca06dcec2545b (see #7758)

**Comment by Tastaturberuf** [comment]
@aschempp approach looks good for me.
