### ISSUE TITLE
Zeitzone: Unbekannte Option: MET

### ISSUE THREAD

**Issue by zonky2** [contao/contao#7704]
### Affected version(s)

5.3.17 - frische Insatllation

### Description

![grafik](https://github.com/user-attachments/assets/b96edc6b-2a80-478b-9350-d42029b12e83)

**Comment by fritzmg** [comment]
This is because you have configured in an invalid time zone in your localconfig.php or within your PHP configuration. "MET" is not a valid time zone (anymore). See here for valid timezones: https://www.php.net/manual/en/timezones.php

**Comment by zonky2** [comment]
=> STRATO
