### ISSUE TITLE
Backend Darstellung der Favoriten mit Sonderzeichen-Problem

### ISSUE THREAD

**Issue by M8MYDAY** [contao/contao#7706]
### Affected version(s)

5.3

### Description

Hi Leute,

hatte nur bemerkt, dass bei Contao 5.3 bei der Favoritenfunktion Sonderzeichen wie Klammern nicht korrekt umgewandelt werden.

Siehe Screenshot:
![Screenshot 2024-11-08 201046](https://github.com/user-attachments/assets/c5394ce1-b4a5-470e-a115-3959d627e576)

**Comment by zoglo** [comment]
Can confirm in the current demo:
![image](https://github.com/user-attachments/assets/7dc51302-b53e-4063-bedc-0722136d90e2)
![image](https://github.com/user-attachments/assets/0b59d942-2f42-4869-b1b0-07629f042203)

**Comment by zoglo** [comment]
See #7708
