### ISSUE TITLE
Not enough permissions to modify content elements of type "0".

### ISSUE THREAD

**Issue by JLBA** [contao/contao#7707]
### Affected version(s)

4.9.32

### Description

Hello,
I got a website with Contao 4.9.32 with some news archives. I've created a user group to let a user add and manage news. This was working until now but since I'v added some missing permissions, the user can't create new news. 
And when trying to add content element in actual news, we got this this error code : `Not enough permissions to modify content elements of type "0".

Fortunately, this work for admin users. 

This pb seems similar to this one : [https://github.com/contao/contao/issues/1454](https://github.com/contao/contao/issues/1454)

Thanks for help.

![image](https://github.com/user-attachments/assets/cded32cd-7c6d-4274-8620-66e1f3638d8e)
`

**Comment by fritzmg** [comment]
Contao 4.9 has reached the end of its life a long time ago. You will need to update to at least Contao 4.13.49 first and reproduce the issue there again.

**Comment by aschempp** [comment]
Contao 4.9 does not have permissions for content elements. You likely have https://github.com/terminal42/contao-ce-access installed, but that extension is abandoned. You should update to at least Contao 4.13.
