### ISSUE TITLE
Funktion "Aliase generieren" prüft Berechtigung für Feld "alias" nicht

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#771]
Die in den verschiedenen Ansichten nach Klick auf "Mehrere bearbeiten" verfügbare Funktion "Aliase generieren" kann auch von Benutzern durchgeführt werden, die keine Berechtigung für das Feld "alias" der entsprechenden Tabelle haben.

**Comment by leofeyer** [comment]
Behoben in cd3f98a6d7fe5e37e9c7ef13960704b98f051dc5.
