### ISSUE TITLE
Error pages should not have `Save and duplicate`

### ISSUE THREAD

**Issue by zoglo** [contao/contao#7710]
### Affected version(s)

`4.13.x` `5.3.x`

### Description

The error pages (which are not allowed to be copied) can still be copied by using Save and duplicate `saveNduplicate` which will result in an error:

```
Not enough permissions to create [Subject: Source: tl_page].
```

### How to reproduce

Go to [demo.contao.org/contao](https://demo.contao.org/contao) and edit any error page (401, 404, 503) and click on `Save and duplicate`

**Comment by fritzmg** [comment]
This also affects Contao 4.13. While no exception is thrown there, it will show "Unknown option: error_404" after _Save and duplicate_.

**Comment by leofeyer** [comment]
The milestone should still be set to `5.3`, because anything assigned to `4.13` will be "affects only 4.13" in the future. I have added a new _also affects 4.13_  tag that we can use to mark issues that could be backported.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7712
