### ISSUE TITLE
Update von 4.13 auf 5.3 Migration\Version500\BasicEntitiesMigration Schleife 

### ISSUE THREAD

**Issue by codesache** [contao/contao#7718]
### Affected version(s)

5.3.17

### Description

Im Content der tl_content (4.13.x) war ein [Nbsp] enthalten (großes N) das bei der Migration von 4.13.49 auf 5.3.17 zu einer Schleife bei Migration\Version500\BasicEntitiesMigration führte.
 vendor/contao/core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php 
 
 Der $test in Zeile 55 berücksichtigt das leider nicht. 
 
 Lösung war per phpmyadmin die  [Nbsp] in  [nbsp] zu ändern.
 
 Könnt ihr euch den $test ansehen und bei  [Nbsp] drüber zu springen. 
 
  
https://community.contao.org/de/showthread.php?87586-Update-von-4-13-auf-5-3-Migration-Version500-BasicEntitiesMigration-Schleife

**Comment by fritzmg** [comment]
I can confirm the issue. Reproduction:

1. Enter `[Nbsp]` (uppercase N) in a `text` content element for example.
2. Disable [this line](https://github.com/contao/contao/blob/4164e9a69dfa9f718baa14358035cd4fd2af3516/core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php#L44) to let the `BasicEntitiesMigration` run again.
3. Execute `contao:migrate --no-interaction`.

The `Contao\CoreBundle\Migration\Version500\BasicEntitiesMigration` will be executed indefinitely.

**Comment by fiedsch** [comment]
Some details:

* https://github.com/contao/contao/blob/82e74b57e055a9516727d438d1b5fb32d7320819/core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php#L80 finds the mentioned `[Nbsp]` as `REGEX` is not case sensitive
* `StringUtil::restoreBasicEntities()` in https://github.com/contao/contao/blob/82e74b57e055a9516727d438d1b5fb32d7320819/core-bundle/src/Migration/Version500/AbstractBasicEntitiesMigration.php#L90 uses `str_replace` which is 
case sensitive, so nothing gets updated and you are stuck in an endless loop.

**Comment by leofeyer** [comment]
@ausi What is the correct way to solve this? A case-sensitive regex in MySQL (not trivial <5.7) or a case-insensitive replacing in the `StringUtil::restoreBasicEntities()` method?

**Comment by m-vo** [comment]
Case-insensitive replacing sounds correct to me if `[Nbsp]` would work as a basic entity - is this the case?

**Comment by fritzmg** [comment]
No, `[Nbsp]` does not work. The migration needs to be case sensitive.
