### ISSUE TITLE
Validierung Benutzername

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#772]
Beim Bearbeiten eines Benutzers im Backend wird zum Benutzernamen folgender Hinweistext angezeigt:
> Aus Sicherheitsgründen können Sie folgende Zeichen hier nicht verwenden: =<>&/()#

Tatsächlich ist es jedoch möglich im Benutzernamen ein Slash zu verwenden, eine Fehlermeldung erscheint bei Eingabe eines Backslashs.

Im Installtool beim Anlegen des Administratorkontos erscheint im Gegensatz dazu bei Eingabe eines Slahs eine Fehlermeldung und Backslashs werden zugelassen.

**Comment by leofeyer** [comment]
Hatten wir das nicht in d04e455e466b6dc065d444e95f3918df51145555 behoben?

**Edit:** Wir sollten die Änderungen noch in die 4.4 zurückportieren. Und die Validierung im Installtool prüfen.

**Comment by leofeyer** [comment]
Behoben in 4402d52c1811dd9d20b97589ee5bf60c9db6e243.
