### ISSUE TITLE
Sticky Backend Footer to Core

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#773]
Please add the function "Sticky Backend Footer"
https://github.com/may17/contao-m17StickyBEFooter from @may17 to Contao-Core.

![sticky-backend-footer](https://user-images.githubusercontent.com/23719181/65220479-181ffd80-dabb-11e9-82ca-0f4c364ed746.jpg)

The user should have the option to enable/disable this function in the profile.

In my opinion this is a great improvement for user experience.

**Comment by m-vo** [comment]
Ich hab's nicht mehr vermisst seit ich die Tastatur-Shortcuts kenne. 

Das soll nicht heißen, dass ich das nicht gut fände. :smile:  Vlt. eher: + ggf. Tastatur-Shortcuts in die Button-Titel?

**Comment by stefansl** [comment]
It's a matter of taste. I prefer this one: https://github.com/OMOSde/contao-om-backend

**Comment by contaoacademy** [comment]
Ich glaube diese Erweiterung ist ein "Easy Pick" und bringt einen großen Mehrwert für den unbedarften Redakteur.

Ich selbst nutze ebenfalls Tastatur-Shortcuts. Auch die Empfehlung von @stefansl finde ich gut. 

Doch ich glaube einfach, dass es die kleinen Dinge sind die schnell integriert sind und dem unbedarften Redakteur weiter helfen.

**Comment by Aybee** [comment]
Ich persönlich bevorzuge fixierte Buttons oben und immer sichtbar.

**Comment by leofeyer** [comment]
Ergebnis der Diskussion: 4 Teilnehmer und 4 Meinungen!

1. Ich nutze Sticky Backend Footer
2. Ich nutze Sticky Backend Footer nicht mehr seit ich die Tastatur-Shortcuts kenne
3. Ich nutze lieber Contao-OM-Backend
4. Ich bevorzuge fixierte Buttons oben und immer sichtbar

Und genau das ist der Grund, warum wir keine Lösung in den Core übernehmen. Es gibt halt einfach nicht den "richtigen" Weg, daher lohnt es sich auch nicht, einen solchen vorgeben zu wollen.

**Comment by contaoacademy** [comment]
Alles klar :-)

**Comment by Total-Reality** [comment]
Also ich find das nicht gut, dass das Thema so abgewürgt wird. Das Problem ist ganz einfach, dass sich in github so gut wie keine normalen User tummeln. 
Wir müssen einfach mal dafür sorgen, dass Contao von der Backend Usability besser wird! Und es geht noch um Längen besser. Wir wollen doch die weltweite Verbreitung verbessern und Contao zum besten CMS machen. Das gelingt aber nicht, wenn ich 1000 km nach unten scrollen muss, damit ich endlich mal den Dialog speichern kann... wie oft kam es schon vor, dass man bei den extrem langen Dialogen von Events und News nur die Überschrift ändern musste, aber dann genervt war, dass man wieder 25 A2 Seiten nach unten scrollen darf?
Wenn es hier zu keiner konstruktiven Diskussion bzw. Lösung kommt, müssen wir das halt mal im Contao Community Forum thematisieren oder gibt es dort schon ein Thema dazu @contaoacademy ?

1. Sticky Backend Footer ist die sinnvollste Erweiterung überhaupt.
2. Nur weil es Tastatur-Shortcuts gibt, heißt das ja nicht dass man Sticky Footer nicht braucht. Was ist das denn für ein Toschlag-Argument?
3. Contao OM Backend ist total verbuggt und macht immerzu irgendwelche Probleme.
4. Fixierte Buttons oben zu haben ist für mich total unlogisch und schlechte Usability. Aber man er das so haben will, dann kann er es ja gerne per CSS umstylen.

Fakt ist jedenfalls... Wir betreuen sehr viele Websites, Kunden und auch andere Agenturen. 
Von den Kunden waren alle begeistert, nachdem wir die m17 sticky footer Erweiterung installiert haben. Sehr viele davon waren dann etwas traurig, dass sie diese Erweiterung schon seit langem gerne eingesetzt hätten und damit sehr viel Zeit gespart hätten.
Ca. 50% der Agenturen, die wir kennen verwenden diese Erweiterung ebenfalls. Die meisten Agenturen, die die Erweiterung noch nicht kannten setzen sie seitdem auch in allen ihren Projekten ein und sind nun begeistert.

Ich kann seit Jahren nicht verstehen, dass die Erweiterung nicht im Core enthalten ist. In JEDER installation braucht man das. 
Was ist meine erste Aktion nachdem ich mit dem Contao Manager Contao 4.9 installiere? 
M17 sticky footer + easy themes installieren. Ohne diese beiden Erweiterungen (oder vergleichbare Pendents) kann so gut wie niemand vernünftig arbeiten. Denn wenn man das nicht tut, braucht man gefühlt doppelt so lange für alles.

Ich habe vorhin schon abgekotzt, weil ich in der Contao Demo (ohne Sticky Footer) ein paar Dinge testen musste (und wieder km scrollen musste), um neutrale Screenshots zu machen.

Also doch: **Es gibt den richtigen Weg**.

**Comment by m-vo** [comment]
Du benutzt die Worte "Sticky Backend Footer ist die sinnvollste Erweiterung überhaupt." und für Kritik an anderen Meinungen "Totschlagargument" in einem Beitrag.😀

 @leofeyer hat doch oben schon Beispiele für die diversen schwer vereinbaren Vorstellungen aufgezählt. Wenn's was Gutes gibt worauf sich alle einigen können, hat ja niemand was dagegen.

**Comment by Total-Reality** [comment]
Die wichtigste Frage vorab bzw. einfach mal anders herum gefragt: Was spricht denn gegen die Implementierung? Also welche Verschlechterung ergibt sich dadurch? 

@m-vo Ich habe **dich** ja nicht kritisiert, ich find nur die Simplifizierung bzw. Zusammenfassung der Meinungen und dem daraus abgeleiteten Fazit destruktiv. 
Würde dich denn der Sticky Footer stören, weil du Tastatur Shortcuts einsetzt? 
Kann ich mir im Leben nicht vorstellen.

Aus eigener Erfahrung weiß ich, dass fast niemand diese Shortcuts einsetzt. Das sind doch eher die Technik-Nerds. 
Ich z.B. habe schon über 60 Erweiterungen programmiert und ich kann über 400 Zeichen auf der Tastatur blind tippen, aber ich nutze diese Shortcuts nicht. Ich will die Buttons sehen und ich will sie auch anklicken...

Von den über 300 Kunden und deren Mitarbeitern kenne ich auf Anhieb nur 2, die Tastatur-Shortcuts benutzen, aber okay, ich kann ja mal eine Umfrage starten...

Und natürlich kriegt man die Vorstellungen zusammen. 

Man kann es ja auch einstellbar machen in den Contao Einstellungen.
Sticky Footer / Buttons (Select): Nein, Oben, Unten, Beides (falls möglich)

Damit sind Meinung 1, 2 und 4 schon mal integriert. 

Wenn jemand OM Backend besser findet, bitteschön, dann kann er diese Extension ja zusätzlich trotzdem noch installieren. Das ist ja in dem Sinne nun auch kein Argument gegen Sticky Footer.

**Comment by contaoacademy** [comment]
Es gibt sicher wichtigere Themen, als über so ein kleines Feature zu diskutieren.
Da die Erweiterung ja schnell installiert ist, gibt es ja einen Workaround ;-)

Unabhängig davon hätte ich das Feature ebenfalls gerne im Core, kann jedoch beide Seiten verstehen.
Jeder hat seine eigene Arbeitsweise und deswegen finde ich den Vorschlag von @Total-Reality einen guten Kompromiss.

> Man kann es ja auch einstellbar machen in den Contao Einstellungen.
Sticky Footer / Buttons (Select): Nein, Oben, Unten, Beides (falls möglich)

Immerhin wurde die Erweiterung bereits mehr als 38.000-mal heruntergeladen.

Wie wäre es mit einer repräsentativen Umfrage?
Vielleicht dazu eine News auf contao.org und mal sehen wie die Resonanz ist.

**Comment by m-vo** [comment]
>  gibt es ja einen Workaround ;-)

Die richtigen Pakete zu installieren ist ja kein Workaround. Das ist vielmehr genau die Idee von Package-Management vs. Monolith. Ich installiere das Cache- oder HTTP-Backend, das ich *fürs Projekt* brauche, die Contao Bundles, die *ich* gerade  brauche, die Dev Tools, die *mir* helfen u.s.w.. Ich hab damit die Wahl sowohl für meinen Geschmack als auch für die jeweiligen Anforderungen etwas auszusuchen. Das ist eine Stärke, keine Schwäche. :smile_cat: 

> Man kann es ja auch einstellbar machen in den Contao Einstellungen.

> Jeder hat seine eigene Arbeitsweise und deswegen finde ich den Vorschlag von @Total-Reality einen guten Kompromiss.

Meine Einschätzung aus Entwickler-Sicht sieht da etwas anders aus. Jede einzelne neue Einstellung bringt Komplexität. Für User, die wissen müssen was die Einstellung macht, aber vor allem auch für den Code, der jetzt dynamisch ist, Anpassungen schwer bis unmöglich werden und die Sache damit Gefahr läuft eher ein Blocker für Innovation zu sein. Es gibt unzählige Beispiele im Core dafür.

Kriterien für "eine Konfiguration anbieten" sind IMHO (u.a.):

* wie viele Leute brauchen es / wie kritisch ist es?
* gibt es einfache Alternativen oder braucht man "Hacks"?
* gibt es stattdessen einen besseren "sensible default"?
* ist das zukunftssicher?


Aber vor allem, denke ich auch:

> Es gibt sicher wichtigere Themen

@Total-Reality Du kannst natürlich auch einen PR machen, in dem wir Verbesserungen dann diskutieren können. Du darfst nur nicht frustriert sein, falls dann andere Leute anderer Meinung sind. :slightly_smiling_face:

**Comment by contaoacademy** [comment]
> Die richtigen Pakete zu installieren ist ja kein Workaround

Das war vielleicht die falsche Wortwahl in dem Zusammenhang. Ich denke es ist klar was ich meine. Es gibt eine Lösung.

> Meine Einschätzung aus Entwickler-Sicht sieht da etwas anders aus. Jede einzelne neue Einstellung bringt Komplexität.

Ein Grund mehr, wieso wir "NICHT-Entwickler" öfters in die Gedankenwelt der Entwickler mitgenommen werden sollten.

**Comment by may17** [comment]
Also als Autor des Sticky Backend footers kann ich sagen, dass ich kein Problem damit hätte ein pull requests zu erstellen und das Feature in den Core zu übertragen.

Vielleicht lässt man noch eine deaktivieren Option springen. Auf der.anderen Seite kann ich mir nicht vorstellen das irgendwer das Feature deaktivieren würde wenn es Standardmäßig mit ausgeliefert werden würde.

Der Sticky Backend Footer war schon immer Korrektur in der UX des Contao Backends, eine die offensichtlich viele als sinnvoll erachten. Es gibt auch seit einem Jahr einen kompletten rewrite in Vanilla Javascript als Beta.

Ich verstehe das man nicht jede Extension in den Core holen möchte allerdings geht es hier nur um Javascript und CSS :)

**Comment by Total-Reality** [comment]
> Immerhin wurde die Erweiterung bereits mehr als 38.000-mal heruntergeladen.

Das finde ich auch sehr beeindruckend. Es würden sich auch noch viel mehr Anwender nutzen, wenn sie die Erweiterung kennen würden. Viele Leute können sich doch gar nicht vorstellen, dass es so eine Erweiterung überhaupt gibt.

> Wie wäre es mit einer repräsentativen Umfrage?
> Vielleicht dazu eine News auf contao.org und mal sehen wie die Resonanz ist.

Finde ich sehr gut, hin zu mehr "Basis-Demokratie". Weg von den "Parteitagen" auf denen alles entschieden wird ;-)

> Meine Einschätzung aus Entwickler-Sicht sieht da etwas anders aus. Jede einzelne neue Einstellung bringt Komplexität. Für User, die wissen müssen was die Einstellung macht, aber vor allem auch für den Code, der jetzt dynamisch ist, Anpassungen schwer bis unmöglich werden und die Sache damit Gefahr läuft eher ein Blocker für Innovation zu sein. Es gibt unzählige Beispiele im Core dafür.

Die meisten Leute kamen mit Contao 3.5 viel besser zurecht als mit Contao 4. Das Argument, dass es zu viele Einstellungen gibt, zieht demnach nicht, da die Contao Einstellungen in 3.5 deutlich komplexer waren. Zudem hat sogar Contao 2 schon einen CMS Vergleich gewonnen (Screen Guide). Damit Contao 4 auch solche großen Vergleiche gewinnt, sind deutliche Nachschärfungen nötig und dazu würde die Sticky Footer Geschichte auf jeden Fall auch mit beitragen.

Außerdem ist ja niemand gezwungen die Einstellung zu aktivieren bzw. zu deaktivieren. may17 hat recht. Diese Erweiterung würde doch so gut wie niemand mehr deaktivieren, weil sie meines Erachtens nur Vorteile bringt. Zeitersparnis für die Redakteure und Zeitersparnis für die Admins, die nicht erst eine Erweiterung installieren müssen, die sowieso in jeder Installation benötigt wird.

Darüber hinaus sollte man auch noch bedenken, dass eine zusätzliche Erweiterung das System an sich anpasst, das vorher schon auf andere Art und Weise programmiert wurde. Das bedeutet, dass CSS-Code etc. umgeschrieben werden muss und JS-Code eingeschleust werden muss, der wieder Dinge abändert. Das alles ist im Prinzip eine unnötige Performance-Bremse im Gegenzug dazu, wenn es gleich im Core mit richtigem HTML-Code inkl. spezifischer CSS-Anweisungen eingebaut wäre.

> Ich installiere das Cache- oder HTTP-Backend, das ich fürs Projekt brauche, die Contao Bundles, die ich gerade brauche, die Dev Tools, die mir helfen u.s.w.. Ich hab damit die Wahl sowohl für meinen Geschmack als auch für die jeweiligen Anforderungen etwas auszusuchen. Das ist eine Stärke, keine Schwäche. 😸

Diese Erweiterung (sowie easy_themes) braucht man aber in jeder Installation. Denn in jeder Installation hat man Backend-Dialoge in denen man mehr oder weniger lange scrollen muss. 
Ansonsten stimme ich dir zu, alles was man bspw. nur in 50% der Projekte braucht, gehört nicht in den Core. Und das wurde ja auch schon sinnvoll in Contao 4 gesplittet (so dass man bei der Installation auf News, Events etc. verzichten kann). 
Wenn so eine harte Anti-Haltung im Core-Team existieren sollte, dann könntet ihr ggf. darüber nachdenken, dass die Erweiterung ebenso wie News, Events, Kommentare etc. eine Core-Extension ist, die nur bei vollständiger Installation dabei ist und sonst nur bei Bedarf dazu installiert werden kann. Wobei das bei diesem Thema sicherlich übertrieben ist, da es ja wirklich nur CSS/JS ist wie may17 schon geschrieben hat :)

**Comment by fritzmg** [comment]
> Diese Erweiterung (sowie easy_themes) braucht man aber in jeder Installation.

That statement is not universally true. I for one have never installed either of these extensions. Mind you, that doesn't mean that I do not think that either of these extensions can be or are useful to a lot of people of course.

**Comment by Total-Reality** [comment]
Ob deine Antwort in der Hinsicht relevant ist, ist die Frage, ob du überhaupt aktiv (viele) Projekte betreust bzw. erstellst oder ob du fast ausschließlich Backend Entwicklung betreibst? Ich betreibe BE & FE Entwicklung im Verhältnis 70 / 30 und beides sehr exzessiv (durchschnittlich über 10 Stunden am Tag). 
Obwohl ich also demnach prozentual viel weniger im Backend Dinge erstelle und einstelle als viele andere, sage selbst ich, dass ich ne Macke kriegen würde, wenn es easy_themes und m17 stick footer nicht gäbe. 
Ich kann nicht nachvollziehen wie man ohne das arbeiten kann? Das ist doch total ineffizient. Also ich muss dann konstatieren, dass alle mit easy_themes und m17 20 bis 30% schneller arbeiten als alle anderen, die diese Erweiterungen nicht einsetzen oder aber diese Leute haben einen Zaubertrick?!

Das betrifft eigentlich alle Seiten mit:
- Mehr als 5 Modulen
- Mehr als 1 Bildgröße

Gäbe es diese beiden Erweiterungen nicht, würde ich vermutlich entweder versuchen diese selbst zu programmieren oder ein eigenes CMS zu programmieren, das nicht so umständlich ist. 

Aber es kann natürlich durchaus sein, dass du so perfekt bist, dass du immer sofort alle Einstellungen in allen Seiten, Modulen und Seitenlayouts korrekt setzt. Dann musst du in jeden Dialog natürlich nur 1 einziges mal in deinem Leben hineingehen und hast diese Probleme dann eben nicht.

**Comment by aschempp** [comment]
Wenn du 10 Stunden im Backend arbeitest und dank Sticky Footer 20-30% Effizienz gewinnst, solltest du vielleicht die Backend Tastenkürzel lernen? 😅

Ich kann mir auch gut vorstellen dass die Erweiterungen vielen Leuten was bringen. Ich verwende allerdings auch keine davon. Ich hab Sticky Footer schon bei Drittsystemen gesehen und mich genervt dass es Bildschirmplatz braucht. Ich brauch die Buttons nie weil ich nur mit Tastenkombinationen arbeite.

Schön ist doch dass jede:r arbeiten kann wie er/sie will. Sich als "besser"/schneller zu profilieren weil jemand eine andere Arbeitsweise hat find ich überheblich.

**Comment by Total-Reality** [comment]
Danke. Ich finde deine Antwort extrem arrogant. 

Warum?
1. Woher willst du wissen, dass ich die Tastenkombination nicht kenne? Du behauptest ja ich müsste sie lernen.

2. "Sich als "besser"/schneller zu profilieren weil jemand eine andere" - Quatsch mit Soße - ich habe geschrieben, dass ALLE schneller sind, die diese Erweiterungen einsetzen gegenüber denen, die sie nicht einsetzen. Ergänzend hätte ich sicherlich besser schreiben sollen:
- Alle, die Backend Sticky Footer oder Tastatur-Shortcuts einsetzen, sind 5% bis 10% schneller als alle anderen
- Alle, die Easy Themes einsetzen sind 15 bis 20% schneller als alle anderen

Das sind einfach gefühlte Werte, die ich jetzt nicht in einer Studie gemessen habe, aber viele werden wissen was ich meine.
Es geht mir hauptsächlich um die Phase in der man eine Seite entwickelt. Daher nochmal die Frage: Gibt es hier einen Zaubertrick um ohne ET schnell in die Module, Seitenlayouts etc. zu kommen?
 
3. Du liest auch sonst gar nicht genau was ich schreibe. Siehe unten. 

4. Es sind minimale Zeitunterschiede, ob ich nun auf den Button klicke oder per Tastenkombination.

5. Du betrachtest nur dich selbst ( du bist ein Technik Nerd) und reflektierst Null die normalen User. 

6. Ich finde es einfach mega Scheiße, dass man hier im Github und teilweise im Contao Community Forum oft angegriffen wird, wenn man eine andere Ansicht hat. Man wird oft von "Core" Admins von oben herab betrachtet.
Da hat man oft gar keinen Bock mehr überhaupt noch was für die "Community" beizutragen.
Das ist das allerletzte engagierte Leute aus der eigenen Community anzugreifen.

Aufgrund dieser Arroganz ist es ja kein Wunder, dass sich einige Sachen bei der Usability so langsam weiter entwickeln. Ich kenne leider sehr viele Leute, die sich ständig bei mir "ausheulen", dass (nett ausgedrückt) noch sehr viel Luft nach oben beim antiquierten Contao-Backend besteht.

Das ist doch von meiner Seite alles nicht böse gemeint, ich will nur, dass das System für die meisten normalen User und Anfänger verbessert wird.
Die Tastenkombinationen nutzen doch hauptsächlich eher die Technik Nerds.

Und nun erklär mir mal wie du mit Tastenkombinationen in Seitenlayout 2 und Modul 25 kommst?

Noch zur Richtigstellung:
1. Ich hab erstens gar nicht gesagt, dass ich mehr als 10 Stunden pro Tag im Backend bin, sondern bei mehr als 10 Stunden Arbeit insgesamt 30% der Zeit im Frontend Entwicklung mache (also im Backend als "Redakteur" bzw. Admin unterwegs bin). 
2. Ich habe auch nicht gesagt, dass man 20 bis 30% Effizienz wegen Sticky Footer gewinnt, sondern Sticky Footer + Easy Themes zusammen genommen (mal davon abgesehen, dass Terminal42 das entwickelt hat und du wahrscheinlich der Geschäftsführer bist).

Zudem ist es schon etwas lächerlich, dass du selbst nicht mal die easy_themes Erweiterung einsetzt, obwohl ihr bzw. Yanick sie entwickelt hat. Also vielen Dank an dieser Stelle dann wenigstens an Yanick für diese geniale Erweiterung.

Also vielleicht möge man sich mal mit den Fakten beschäftigen anstatt sich zu profilieren, indem man andere verleumdet und angeht.
Und da du mir ja auch einen "netten" Rat gegeben hast: Lern doch mal dich netter auszudrücken als Aushängeschild von Contao. Dann braucht ihr auch nicht so viel Geld für Marketing-Maßnahmen auszugeben.

> Ich hab Sticky Footer schon bei Drittsystemen gesehen und mich genervt dass es Bildschirmplatz braucht.

Wow, also wenn man Full HD Monitore hat, dann fällt das wohl Null ins Gewicht. Zudem würde das Problem für dich nicht existieren, wenn man es optional in den Contao Einstellungen oder beim User Profil einstellbar machen würde, Siehe auch https://github.com/contao/contao/issues/773#issuecomment-761541271

**Comment by aschempp** [comment]
Tut mir leid wenn das als "von oben herab" rüber kam, so war es nicht gemeint.

Warum sagst du es ist "lächerlich" dass ich eine Erweiterung nicht einsetze? Ich benötige sie nicht, es ist doch meine freie Entscheidung wie ich mein Backend nutze, und ich nutze es nicht "falsch" weil ich es nicht so nutze wie du? Übrigens arbeite ich seit 9 Monaten (bestens) auf meinem 13" Laptop im Homeoffice.

Ja ich bin (einer der beiden) Geschäftsführer von terminal42. Easy_themes hat Yanick erfunden, ich weiss nicht ob für sich oder einen Kunden. Ich hab es am Anfang genutzt, aber mich mittlerweile umgewöhnt.
Und deine Anschuldigung zum Impressum bezieht sich vermutlich auf deutsches Recht, wir sind aber eine Schweizer Firma ;-)

**Comment by Total-Reality** [comment]
Ja sorry auch von mir, wegen mancher Aussagen, die polemisch rüber kommen und am Thema vorbei gehen. ihr könnt doch alle gerne so arbeiten wie ihr das für richtig haltet.
Ich verstehe es trotzdem nicht wie man ohne die easy_themes Erweiterung vernünftig arbeiten kann. Vielleicht kannst du mir das mal per Mail erklären (habe dir eine geschrieben).
Denn das hat ja nichts mit dem Thema hier zu tun, von daher entschuldige ich mich für meine systematische Kritik. 

Ich möchte allerdings nochmal festhalten, dass es nicht mein Ziel ist mich zu profilieren oder jemanden zu kritisieren, sondern ich kämpfe nur für die Sache an sich. Meine Freundin würde mich hassen, wenn sie wüsste wieviel Zeit ich hier für mein Engagement rein stecke und mir einige Beiträge hätte sparen können, wenn ich nicht auf jede Kritik eingehen würde. 

Es ist doch nur mein einziges Ziel, dass das System besser wird. Und dafür brauchen wir euch. Nicht nur für unsere Kunden, sondern alle, die es möchten, sollen Tools und Werkzeuge an die Hand bekommen, damit sie besser und schneller mit Contao arbeiten können. Ich wünsche mir für uns alle einen höheren Marktanteil von Contao, weil wir es alle verdient haben, allen voran Leo Feyer. Und da macht es mich einfach traurig und bringt mich zum resignieren, dass einfach so viele Chancen ungenutzt liegen bleiben.
Welcher CMS-Tester / Magazin etc. installiert denn erst mal zig Erweiterungen und sagt erst dann "das System ist aber toll"?
Das Core System an sich muss einen schon umhauen.

Das hier ist das Ticket von @contaoacademy und ich will das nicht das sinnvolle Anliegen durch gegenseitige Angriffe und Rechtfertigungen kaputt machen. Wir sollten alle viel mehr zusammen halten. Wir sind keine Gegner und auch keine Konkurrenten, sondern die anderen CMS sind wenn überhaupt die "Gegner". Und dafür sollten wir gemeinsam kämpfen. 
Vielleicht auch mit so basisdemokratischen Ideen wie sie @contaoacademy geschrieben hatte.

Vielleicht sollten wir uns das mehr bewusst machen auf welcher Seite wir eigentlich stehen und welches Glück wir haben, dass Leo Feyer dieses CMS damals erfunden hat und seit jeher betreut. Ohne ihn hätte ich meine Partnerin nicht kennengelernt.
Es ist auch zu kurz gekommen welch großartige Arbeit ihr leistet. Ihr sorgt dafür, dass Hunderte oder vielleicht sogar Tausende Menschen einen Job haben. Und für viele ist es bestimmt auch dank Contao ihr Traumberuf (geworden). Also vielen Dank dafür.

Ich hoffe, dass es vielleicht noch andere Wortmeldungen gibt, die auf das eigentliche Thema eingehen, also auf m17 sticky footer.

Vielen Dank also nochmal an @may17 für die tolle Erweiterung.

Schönen Abend noch.

**Comment by operatorone** [comment]
Also ich benutze den Sticky Footer auch fast permanent in jedem Projekt. Ich finde man sollte einfach dem Backend-User die Möglichkeit geben zu entscheiden, da es wirklich eine gute Funktionalität ist, die jedem zur Verfügung stehen sollte. Auch, wenn der Admin/Programmierer die Erweiterung nicht installiert hat. Wenn auch alternativen existieren, bin ich doch der Meinung, dass Contao im generellen davon profitieren kann, im Backend gegenüber anderen Systemen weiterhin die Nase vorn zu haben.

**Comment by fritzmg** [comment]
> Wenn auch alternativen existieren, bin ich doch der Meinung, dass Contao im generellen davon profitieren kann, im Backend gegenüber anderen Systemen weiterhin die Nase vorn zu haben.

But how do you define what's "best"? Why is better to constantly obstruct a portion of the back end view with buttons that you do not need to have visible while editing?

**Comment by operatorone** [comment]
The best thing to do is to simply set up the backend the way you can work best. "The best" is always in the eye of the beholder, but the benefit is to create the possibilities to arrange it according to taste.

**Comment by contaoacademy** [comment]
I think we should stop asking "What do I like".

Maybe it is better to ask: "Does this make Contao easier to use for more than 50% oft the users!"
And if the answer is "YES!", we should implement this feature.

The developer could ask:
"How could we implement this feature best with the minimum of work and produce as less maintenance as possible in the future."

- What about a public survey?
- What is the actual effort for implementation this feature?
- Who could implement this feature and who will pay for it?

**Comment by Total-Reality** [comment]
> > Wenn auch alternativen existieren, bin ich doch der Meinung, dass Contao im generellen davon profitieren kann, im Backend gegenüber anderen Systemen weiterhin die Nase vorn zu haben.
> 
> But how do you define what's "best"? Why is better to constantly obstruct a portion of the back end view with buttons that you do not need to have visible while editing?

Warum fangen wir jetzt wieder an Englisch zu diskutieren, wenn selbst Leo und nen anderer Core Admin zuvor bereits in Deutsch geschrieben haben? Aber okay.
Spooky, warum bist du hier eigentlich immer so unentspannt und engstirnig? Im Community Forum bist du immer so nett, ich verstehs nicht. 
Das was du hier als Argument führst, wurde oben ja bereits widerlegt durch den Ansatz, dass man es optional wieder deaktivieren kann in den Contao Einstellungen oder bei den User Settings.

> I think we should stop asking "What do I like".

Genau. Sag ich ja die ganze Zeit.

> Maybe it is better to ask: "Does this make Contao easier to use for more than 50% oft the users!"

50% ist etwas wenig ehrlich gesagt. Es sollten schon über 60 oder 70% sein, aber ich denke, dass diese Zahl locker zusammen kommt.

> What about a public survey?
Wo kann man denn im Contao Universum eine objektive Umfrage starten?
Die Association z.B. ist zu techniklastig. Die Premium Partner zum Teil auch...

Ihr habt doch bestimmt viele Connections durch die Academy? Ich sag mal, dass die Zielgruppe dort eher in dem Bereich unterwegs ist, der in meinen Augen interessant und einfach die größte Bandbreite umfasst.

Die Zielgruppe für die Arbeit im Backend von Contao sind eher die Leute dort (Redakteure und Agenturen) und nicht ein Github-Forum mit 10 bis 20 streitlustigen Core- und Backend-Entwicklern (mich eingeschlossen) :D Backend-Entwickler sind keine richtige Zielgruppe bei diesem Thema, da diese ja in der Regel nicht wie verrückt Inhalte etc. in Contao herumschubsen müssen. Daher ist die ganze Diskussion hier eigentlich auch komplett an der Zielgruppe vorbei. Man kommt mit den besten Argumenten der Welt hier nicht mehr weiter.

Kann man da nicht direkt irgendwo auf der Academy Website eine Umfrage unter Mitglieder einführen? Oder man macht sie offen als eine Art Petition? 
Wenn dafür irgendwelche Erweiterungen benötigt oder programmiert werden müssen, dann sag bescheid...
