### ISSUE TITLE
Double encoding in HtmlAttributes

### ISSUE THREAD

**Issue by ausi** [contao/contao#7748]
### Affected version(s)

4.13+

### Description

Using something like `attrs().set('data-json', data|json_encode)` in Twig can cause issues if `data` has values with HTML entities inside. Basically the same issue as we fixed in https://github.com/contao/contao/pull/7556

**Comment by fritzmg** [comment]
For reference: we use that here for example:

https://github.com/contao/contao/blob/975f40085cb7c1bfe7a6c2e9f4839504897cddc3/core-bundle/contao/templates/twig/content_element/swiper.html.twig#L20

**Comment by ausi** [comment]
~~We could try to see if `.set('data-json', data|json_encode|e('html', double_encode = true))` would work. 🤔~~

UPDATE: `attrs().setDoubleEncoding(true).set('data-json', data)` would work (but is not needed for JSON anymore because of #7556)

**Comment by ausi** [comment]
See https://github.com/contao/contao/pull/7556#issuecomment-2500773347
