### ISSUE TITLE
Character set 'binary' cannot be used in conjunction with 'utf8mb4_general_ci' in call to regexp_like

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#7759]
> It seems like the newly added Migration is not compatible with MySQL 8 (only with MariaDB).
> 
> I'm getting this error on db migrate with newest PHP 8.3, Contao 5.3 and MySQL 8:
> 
> 
> 
> `  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 3995 Character set 'binary' cannot be used in conjunction with 'utf8mb4_general_ci' in call to regexp_like. `
> 
> 
> 
> The problematic SQL Statement seems to be:
> 
> 
> 
> `SELECT TRUE FROM tl_article WHERE CAST(`title` AS BINARY) REGEXP '\\[(&|&amp;|lt|gt|nbsp|-)\\]' LIMIT 1;`
> 
> 
> 
> Is this issue known? 

 _Originally posted by @rorych in [923e4f0](https://github.com/contao/core-bundle/commit/923e4f0dbc050fcc5e0771a0eb6223c960687e2b#commitcomment-149700384)_

**Comment by leofeyer** [comment]
This is a follow-up issue on #7727. @ausi @fritzmg /cc

**Comment by ausi** [comment]
`CAST(title AS BINARY) REGEXP CAST('\\[(&|&amp;|lt|gt|nbsp|-)\\]' AS BINARY)` seems to work in MySQL 8.

In MySQL we could also use `REGEXP_LIKE('\\[(&|&amp;|lt|gt|nbsp|-)\\]', title, 'c');` for case-sensitive matches, but that does not seem to work in mariadb :(

**Comment by m-vo** [comment]
We could use executable comments in the query to differentiate but I would rather have a solution that works across platforms. 🙈

**Comment by ausi** [comment]
Yes, my first suggestion should work everywhere I think.

**Comment by leofeyer** [comment]
@ausi Can you test if `CAST(title AS BINARY) REGEXP BINARY '\\[(&|&amp;|lt|gt|nbsp|-)\\]'` works as well? I successfully tested it on MySQL 9.1 and MariaDB 10.5.

**Comment by ausi** [comment]
Yes, but the `BINARY` operator is deprecated so we should not use it I think.
https://dev.mysql.com/doc/refman/8.4/en/cast-functions.html#operator_binary
> The `BINARY` operator is deprecated; you should expect its removal in a future version of MySQL. Use `CAST(... AS BINARY)` instead.

And mixing both styles seems counter intuitive, so I would either use
`BINARY title REGEXP BINARY '\\[(&|&amp;|lt|gt|nbsp|-)\\]'`
or
`CAST(title AS BINARY) REGEXP CAST('\\[(&|&amp;|lt|gt|nbsp|-)\\]' AS BINARY)`
with the latter one preferred because of the deprecation.
