### ISSUE TITLE
UX Improvement: Prevent losing changes in overlay

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#7763]
### Description

During a training session with a customer, I just realized that some people might find it a bit difficult to handle the popups/overlays and lose changes as a result.

In the core it is probably not too bad, but especially in the notification center when editing a notification it can happen that you write a text for minutes. If you are then careless and click outside the overlay, all changes are immediately lost.

My suggestion would be a listener that prevents the overlay from being accidentally closed after changes in the inputs - a `window.confirm()` perhaps?

![image](https://github.com/user-attachments/assets/bc17523d-743a-46bc-a145-e5ab20586a9b)

**Comment by fritzmg** [comment]
The modal is currently being reworked by @aschempp - so this could be considered there.

However, I consider it actually a bug that you can close the modal window by clicking anywhere else. We call it a _modal_ window after all - and by definition you are not allowed to interact with anything else, except the modal window itself, once open.

> A modal window creates a mode that _disables user interaction with the main window_ but keeps it visible, with the modal window as a child window in front of it. _Users must interact with the modal window before they can return to the parent window_. This avoids interrupting the workflow on the main window.

https://en.wikipedia.org/wiki/Modal_window

**Comment by bennyborn** [comment]
You're right. Until now I didn't even see that this was labeled as a "modal" in the markup. 😂
So yeah, a simple click should not be able to close it 👍
