### ISSUE TITLE
Sortable selection fields with chosen

### ISSUE THREAD

**Issue by katgirl** [contao/contao#7771]
### Description

It would be nice if you could sort selection fields with chosen too.
Explanation:
We have a table with all the people in a company. For the frontend, we have a module where you can select the people for the branch. These should be displayed in a certain order. 

```php
  // Add select field from tl_personen
  $GLOBALS['TL_DCA']['tl_content']['fields']['addPerson'] = [
      'inputType'               => 'select',
      'foreignKey'              => 'tl_personen.name',
      'eval'                    => ['isSortable'=> true, 'multiple' => true, 'mandatory'=>true, 'chosen'=>true, 'tl_class'=>'w50'],
      'sql'                     => 'blob NULL',
  ];
```

**Comment by aschempp** [comment]
I don't think the chosen script supports this at all. Neither does a regular `<select>` with multiple options. But you can simply use the `checkboxWizard` for this case.
