### ISSUE TITLE
Error at help wizard element type

### ISSUE THREAD

**Issue by zonky2** [contao/contao#7776]
### Affected version(s)

5.3.x - 5.4.x

### Description

Click at (?) to open help wizard from element type

`Contao\CoreBundle\EventListener\DataContainer\ContentElementTypeListener::getAllowedElements(): Argument #1 ($ptable) must be of type string, null given, called in /home/www/releases/80/vendor/contao/core-bundle/src/EventListener/DataContainer/ContentElementTypeListener.php on line 34`

same at current demo

**Comment by de-es** [comment]
Duplicates #7689

**Comment by bytehead** [comment]
See #7690

**Comment by zonky2** [comment]
hmm hatte nach `getAllowedElements` gesucht und keine Treffer bekommen...
