### ISSUE TITLE
Meta data for directorys

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#778]
Is there a use case for using meta data in a folder?

If not, what about to remove the meta data when editing directorys.

**Comment by asaage** [comment]
There might be extensions that make use of directory-meta-data.
Like for example  a zipped-folder-download content-element
or a modified search-modue. I implemented both of that for a customer once (but i don't think he is really using it)
I don't see any benefit in removing it for directories - it's the same table (tl_files) anyway.

**Comment by m-vo** [comment]
If we drop this, we could as well drop storing folders in `tl_files` completely. And thus also removing folder hashes and parent-child relations, which would greatly simplify the sync. (But as @asaage pointed out this would be a BC break.)

**Comment by fritzmg** [comment]
You can't drop folders from the Dbafs as you can select folders as well.

**Comment by m-vo** [comment]
But you could do this implicitly as well by using the path or a file. Right now a moved folder can only be tracked if the content is exactly the same anyways. Imo having it in the Dbafs layer doesn't mean it has to be 1:1 in the database (db should be implementation detail).

**Comment by fritzmg** [comment]
> But you could do this implicitly as well by using the path or a file.

But you store UUIDs in the database, not file paths. A folder needs an UUID as well.

> Right now a moved folder can only be tracked if the content is exactly the same anyways.

This is only relevant, if you move files/folders outside of the file manager, which is not recommended or the norm anyway.

**Comment by m-vo** [comment]
I don't think so. But I also think we aren't talking about the same thing :-). If you want we can discuss that on Slack to not further hijack this issue.

**Comment by Mynyx** [comment]
> I don't see any benefit in removing it for directories - it's the same table (tl_files) anyway.

It will improve the user experience, because the input fields without a comprehensible function are confusing.

But the database would not have to be modified, so there could be an simple option for extension developers to show the input fields for directories if required.

**Comment by leofeyer** [comment]
See #1055
