### ISSUE TITLE
Improve Twig exception handling

### ISSUE THREAD

**Issue by aschempp** [contao/contao#7783]
### Affected version(s)

5.3

### Description

I think we need to improve Twig exception handling. I have an insert tag in my content, that throws a `PageNotFoundException` if something is not found. The exception renders the HTTP 500 error screen instead of a 404 _page not found_. I would expect the same to happen if a `ResponseException` is thrown. Imho we should add Contao handling for these cases.

**Comment by ausi** [comment]
Shouldn’t this already be handled in the `UnwrapTwigExceptionListener`? 
https://github.com/contao/contao/blob/06173abd57ec66cc3657f349c14785dbd955b447/core-bundle/src/EventListener/UnwrapTwigExceptionListener.php

Can you debug why that does not work in your case?
Is your exception not of type `Twig\Error\RuntimeError`?

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7793 then 🙃
