### ISSUE TITLE
Recent contao versions not available through all channels

### ISSUE THREAD

**Issue by Whissi** [contao/contao#78]
I haven't tested Contao Manager yet (that phar file) so maybe that's the only working way at the moment to get latest Contao version:

https://docs.contao.org/books/manual/current/en/01-installation/installing-contao.html says 

> Latest version of Contao (4.x):
> `curl -L http://download.contao.org | tar -xzp`

But this will bring you 4.5.10 from 2018-06-26. Current 4.5.x is 4.5.14 from 2018-08-28.
However, I would expect to get 4.6.5 using that command.

> LTS version of Contao (3.5):
> `curl -L http://download.contao.org/lts | tar -xzp`

OK, this should be updated for 4.4. But anyway, this method is broken, URL returns

> Invalid parameter "lts".

How about

> A specific version (e.g. 3.5.2):
> `curl -L http://download.contao.org/3.5.2 | tar -xzp`

Let's try it for 4.4.26 which was released today:

> Contao 4.4.25 is not available as .zip download. Please use the Contao Manager or Composer to install Contao. See https://contao.org/en/download.html for more information.

OK, so this method is obviously deprecated for >4.x... let's try Composer:

No chance, according to https://packagist.org/packages/contao/managed-edition, package was last updated on 2018-08-23.

Maybe I am missing something but how do I get latest LTS version?

PS: If you are going to update manual, please change URLs to HTTPS. Any installation following that documentation is currently vulnerable to a MITM attack. Heck, you don't even tell people to validate checksums.... maybe this can be improved.

**Comment by Whissi** [comment]
> No chance, according to https://packagist.org/packages/contao/managed-edition, package was last updated on 2018-08-23.
> 
> Maybe I am missing something but how do I get latest LTS version?

Looks like I misread things. From compopser output,
> Installing contao/managed-edition (4.4.21)
>  \- Installing contao/managed-edition (4.4.21): Loading from cache

I got the impression that I was installing Contao 4.4.21 but the 'bundles' are 4.4.26,

>  \- Installing contao/core-bundle (4.4.26): Loading from cache
>  \- Installing contao/installation-bundle (4.4.26): Loading from cache
>  \- Installing contao/manager-bundle (4.4.26): Loading from cache
>  \- Installing contao/calendar-bundle (4.4.26): Loading from cache
>  \- Installing contao/comments-bundle (4.4.26): Loading from cache
>  \- Installing contao/faq-bundle (4.4.26): Loading from cache
>  \- Installing contao/listing-bundle (4.4.26): Loading from cache
>  \- Installing contao/news-bundle (4.4.26): Loading from cache
>  \- Installing contao/newsletter-bundle (4.4.26): Loading from cache

 and recent changes like commit b6c1d775262a48ec82c444fa99f2d6124f2df1fa are present.

I'll keep this issue open until someone will notice the other documentation issues (especially the HTTPS thing). Feel free to update issue title or close).

**Comment by dmolineus** [comment]
Die Managed Edition liegt auch nur in Version 4.4.21 auf Packagist vor. Warum dessen Version nicht mit hochgezogen wird, weiß ich nicht.

**Comment by leofeyer** [comment]
@Whissi Dieser Artikel beantwortet Deine Fragen: https://contao.org/de/news/entschlackung-des-release-prozesses.html

> Die Managed Edition liegt auch nur in Version 4.4.21 auf Packagist vor.

Auch das wird in dem oben verlinkten Artikel beantwortet. Da es [keine `composer.lock` mehr](https://github.com/contao/managed-edition/tree/4.4) gibt, erhält man automatisch immer die neueste Version der Bundles.
