### ISSUE TITLE
Contao Manager does not show up in Contao back end

### ISSUE THREAD

**Issue by anatol06** [contao/contao#780]
HI!
I need to have Contao Manager in Contao back end.
I installed with Compsoer last version of Contao then - Conao Manager 
`php composer.phar require contao-themes-net/mate-theme-bundle`
Everything is OK except that Manager does not show up in Contao back end.
It shows up just in debug mode.
My environment is [DevilBox](http://devilbox.org/) installed on WSL2(Ubuntu 18.04) on WIndows 10.

With other projects in this environment I don't have problems.

**Comment by aschempp** [comment]
How did you install the Contao Manager ?

**Comment by anatol06** [comment]
I solved the issue!
In order the Manager to appear in back end it is necessary not only to update the DB after installation, but also to update all extensions listed by manager.

**Comment by anatol06** [comment]
1. Download the contao-manager.phar from contao.org: https://contao.org/en/download.html
	2. 
Transfer the contao-manager.phar to the web/ folder (= the DocumentRoot of the domain) of your website
	3. 
Rename the contao-manager.phar file to contao-manager.phar.php and open it in your browser  e.g.




https://example.com/contao-manager.phar.php
	1. 
Update all extensions and DB
	2. 
Update all extensions in Manager

**Comment by anatol06** [comment]
1. Download the contao-manager.phar from contao.org: https://contao.org/en/download.html
2. Transfer the contao-manager.phar to the web/ folder (= the DocumentRoot of the domain) of your website
3. Rename the contao-manager.phar file to contao-manager.phar.php and open it in your browser  e.g.
https://example.com/contao-manager.phar.php
5. Update all extensions and DB
