### ISSUE TITLE
Icon misplaced on download element with headline

### ISSUE THREAD

**Issue by rabauss** [contao/contao#7805]
### Affected version(s)

5.3.x

### Description

If you create a single download element with headline, the icon from `icon.css` is misplaced.

Either we have to change the selector here https://github.com/contao-components/contao/blob/9.x/css/icons.css#L9 to
`.download-element a` and all extensions selectors (e.g. `.ext-pdf a`) as well

Or the CSS class on the download element has to be set on the `a` instead of on the content element.

What do you think?

**Comment by zoglo** [comment]
*Can be easily reproduced by checking the icon.css in the css-frameworks in the respective layout and removing all the custom styles in the contao-demo (even if using the developer tools) - this does not affect 4.13*
![image](https://github.com/user-attachments/assets/cf799020-e371-4c7a-becc-ac12c15db79b)

Contao 5.3
![image](https://github.com/user-attachments/assets/eeca285d-73f3-40a7-8f6e-a5cd35b41d5b)

Contao 4.13
![image](https://github.com/user-attachments/assets/83cbb709-c3c6-4818-86f7-861dc22a6289)

**Comment by zoglo** [comment]
@rabauss either a template change for the single download element or changing the background-image to the link (which would be the best case, however we'd need to change it for **every** *extension*, not just the `.download-element` :)

*And needs to be tested with 4.13 again, maybe the template change to revert to the old structure might be better?*

**Comment by leofeyer** [comment]
@m-vo WDYT?

**Comment by m-vo** [comment]
When implementing the new download elements, I made sure, that both the list and the single one share a common component. So common styles should  IMHO be applied to the component part, i.e the `a` tag, not the things around them.

Adding a `p` tag around the single download link makes no sense semantically, does it? Or is there any advantage? I think I would vote for adjusting the CSS side.

**Comment by zoglo** [comment]
See https://github.com/contao-components/contao/pull/19
