### ISSUE TITLE
Search UI nitpicks

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#7812]
### Description

Just a few minor nitpicks that we should fix:

<img width="588" alt="" src="https://github.com/user-attachments/assets/bdf9ab44-fd40-4b8c-80e5-bdd05e6591c6" />

![](https://github.com/user-attachments/assets/a410b9d5-5d0e-4511-a8fe-23bf6f898e02)

**Comment by zoglo** [comment]
See #7813
