### ISSUE TITLE
Erläuterungen zu Backend-Menüpunkten

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#782]
Die Erläuterungen zu den Backend-Menüpunkten (`title`-Attribut der Links) bedürfen teilweise einer Überarbeitung.

Themes:  `Frontend-Module, Stylesheets, Seitenlayouts und Templates verwalten`, jedoch besteht für Templates ein separater Menüpunkt. Demgegenüber fehlen Bildgrößen in der Auflistung.

Templates: `Templates im Backend bearbeiten` erscheint im Vergleich zu den anderen Menüpunkten nicht konsistent, da die Bearbeitung bei allen Menüpunkten im Backend geschieht, ohne dass dies bei den anderen Menüpunkten gesondert erwähnt werden würde. Stattdessen vielleicht `Templates verwalten und deren Quelltext bearbeiten`. 

Systemwartung: `Contao warten oder aktualisieren`, in Contao 4 ist es allerdings nicht mehr möglich über die Systemwartung eine Aktualisierung durchzuführen.

**Comment by leofeyer** [comment]
See #1197
