### ISSUE TITLE
Hilfetext ist bei Seiten ohne Unterseiten verschoben

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#783]
In der Seitenstruktur ist bei Seiten ohne Unterseiten der Hilfetext nach links verschoben und wird nicht unmittelbar unter dem Icon angezeigt:

![image](https://user-images.githubusercontent.com/1632642/65384232-14d97b80-dd20-11e9-91dc-6d25a306999c.png)

**Comment by leofeyer** [comment]
Welche Contao-Version betrifft das?

**Comment by Mynyx** [comment]
Sowohl 4.4 als auch 4.8.

**Comment by leofeyer** [comment]
Behoben in 55750ed8d8bedb293faa9e0ae792cd1586182f5d.
