### ISSUE TITLE
Leeres Auswahlmenü für Ursprungstemplate bei Vergleich von Templates mit abweichendem Präfix

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#784]
Beim Vergleich von Templates ist das Auswahlmenü für das Ursprungstemplate leer, wenn das zu vergleichende Template ein abweichendes Präfix hat (zum Beispiel `x_x.html5`). Dadurch ist es nicht möglich, einen Vergleich durchzuführen.

Entweder könnte der Button zur Vergleichsansicht in diesem Fall deaktiviert werden oder es könnten wie bei Templates ohne Präfix (zum Beispiel `x.html5`)  im Auswahlmenü alle Templates angezeigt werden.

**Comment by leofeyer** [comment]
Wie genau lässt sich das reproduzieren?

**Comment by Mynyx** [comment]
Ein Template erstellen und zu `x_x.html5` umbenennen.

**Comment by leofeyer** [comment]
Aber `x_` ist ja kein gültiges Präfix, daher ist es korrekt, dass kein Template angezeigt wird.

**Comment by Mynyx** [comment]
Daher der Vorschlag, entweder den Button zur Vergleichsansicht in diesem Fall zu deaktivieren oder im Auswahlmenü alle Templates anzuzeigen, wie dies auch bei Templates ohne Präfix geschieht.
