### ISSUE TITLE
Übersetzung der einzelnen Felder von tl_page bei Benutzergruppen fehlt

### ISSUE THREAD

**Issue by Floxn** [contao/contao#787]
**Affected version(s)**
4.8.3
**Description**  
Bei den erlaubten Feldern in den Einstellungen der Benutzergruppen fehlt die deutsche (andere auch?) Übersetzung. 
<img width="270" alt="Bildschirmfoto 2019-09-23 um 13 48 19" src="https://user-images.githubusercontent.com/15326334/65423409-2c406380-de09-11e9-996d-fdb9c06f3ab9.png">

**How to reproduce**  
Login in [demo.contao.org/contao](https://demo.contao.org/contao?do=group&act=edit&id=1&rt=8boXwpFkcrKth9qOiTt1FofCCJKuFI24n4mhoibnUOY&ref=MOPIZ7UP)

**Comment by leofeyer** [comment]
Fixed in a81a11b919126798b8a9adb8d1632d69035a9ba5.
