### ISSUE TITLE
Erklärungstext Link zum Quelltexteditor

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#789]
In den Modulen Templates und Dateiverwaltung lautet der Erklärungstext des Links zum Quelltexteditor `Die Datei "..." bearbeiten`. Der Erklärungstext zum Bearbeiten der Dateieigenschaften lautet mit `Datei oder Verzeichnis "..." bearbeiten` nahezu gleich, sodass der Erkenntnisgewinn recht gering ist.

Daher würde ich vorschlagen den Erklärungstext des Links zum Quelltexteditor auf `Den Quelltext der Datei "..." bearbeiten` zu ändern.

**Comment by leofeyer** [comment]
See #1149
