### ISSUE TITLE
development tools

### ISSUE THREAD

**Issue by mmiat** [contao/contao#79]
https://contao.org/en/extension-list/view/development.10040019.en.html
is this project dead? it could be very useful! but it doesn't work with contao 3: Fatal error: Cannot redeclare class tl_extension in system\modules\devtools\dca\tl_extension.php on line 271

**Comment by discordier** [comment]
I do not understand your issue, Contao 3 comes bundled with the [devtools](https://github.com/contao/core/tree/master/system/modules/devtools)
