### ISSUE TITLE
 Quelltext-Einrückung beim Templatevergleich

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#790]
Beim Templatevergleich wird in Zeilen, die mit Leerzeichen eingerückt sind, ein Leerzeichen zu wenig angezeigt.

Mit zwei Leerzeichen eingerückte Zeilen sind im Vergleich nur noch mit einem Leerzeichen eingerückt, mit vier Leerzeichen eingerückte Zeilen nur noch mit drei Leerzeichen usw.

**Comment by leofeyer** [comment]
Kannst Du bitte einen Screenshot hochladen?

**Comment by asaage** [comment]
![image](https://user-images.githubusercontent.com/4138336/65782468-06d79080-e14e-11e9-97b8-857adaae44c5.png)
In der Tat verschwinden einige Leerzeichen.
Denke mal das wird am diff-parser liegen der macht aus Leerzeichen und Tab's ```&nbsp;``` und lässt dazwischen auch noch Leerzeichen stehen.

Wenn da überhaupt Handlungsbedarf besteht dann denke ich würde ich eher eine monospace Schrift an der Stelle bevorzugen.

**Comment by Mynyx** [comment]
> In der Tat verschwinden einige Leerzeichen.
> Denke mal das wird am diff-parser liegen der macht aus Leerzeichen und Tab's `&nbsp;` und lässt dazwischen auch noch Leerzeichen stehen.

Dass die Leerzeichen nicht als normale Leerzeichen sondern teils als `&nbsp;` ausgegeben werden, ist nicht das Problem, in der Gesamtheit ist es allerdings eines zu wenig.

Wobei ich nun noch festgestellt habe, dass wenn eine Zeile mit genau einem Leerzeichen beginnt, dieses auch verschwindet.

> Wenn da überhaupt Handlungsbedarf besteht dann denke ich würde ich eher eine monospace Schrift an der Stelle bevorzugen.

Die Problematik besteht insbesondere darin, dass beim Kopieren und Einfügen ein Leerzeichen fehlt. Kopiert man beispielsweise eine Zeile aus der originalen Version eines Templates in das eigene Template, wird anschließend aufgrund des fehlenden Leerzeichens immer noch eine Abweichung angezeigt.

**Comment by leofeyer** [comment]
Wir könnten das relativ einfach beheben, indem wir die Formatierung `#diff dl` um `font: .75rem "Roboto Mono",monospace` ergänzen:

<img width="890" alt="" src="https://user-images.githubusercontent.com/1192057/67760710-16464400-fa42-11e9-9fab-e50e9c94b912.png">

Allerdings würden dann auch die Diffs von normalen Datensätzen mit fester Laufweite ausgegeben:

<img width="895" alt="" src="https://user-images.githubusercontent.com/1192057/67760874-66bda180-fa42-11e9-881b-5adab148da97.png">

Mich würde das nicht stören. @contao/developers WDYT?

**Comment by Mynyx** [comment]
> Wir könnten das relativ einfach beheben, indem wir die Formatierung `#diff dl` um `font: .75rem "Roboto Mono",monospace` ergänzen:

Was genau könnte mit der Änderung der Schriftart behoben werden? Das Problem ist, dass bereits im generierten Quelltext Leerzeichen fehlen.

**Comment by leofeyer** [comment]
> Was genau könnte mit der Änderung der Schriftart behoben werden?

Siehe die Screenshots in meinem Kommentar.

**Comment by leofeyer** [comment]
See #904 for the Contao 4.4 changes. I am going to re-assign the ticket to the 4.8 milestone now, because the fix is different there.

**Comment by leofeyer** [comment]
See #915 for the Contao 4.8 changes.
