### ISSUE TITLE
Always show tl_image_size.formats in the backend

### ISSUE THREAD

**Issue by ausi** [contao/contao#791]
If `tl_image_size.formats` has a value in the database but WEBP is (currently) not supported we should still show the values from the database in the checkbox wizard so that the admin can see the enabled options and is able to disable them.

https://github.com/contao/contao/blob/deac104160f6fef153a2549619537afdef30e017/core-bundle/src/Resources/contao/dca/tl_image_size.php#L379

**Comment by fritzmg** [comment]
May be just delete line 394? Then the error message will still be shown and you can deselect the options.

**Comment by ausi** [comment]
But then the options would also be shown if the column in the database is empty. IMO we should not enable the posibility to add a wrong configuration but only to remove an invalid one.

**Comment by ausi** [comment]
Closed in favor of #804
