### ISSUE TITLE
Legacy image and picture classes do not support predefined image sizes (via config)

### ISSUE THREAD

**Issue by m-vo** [contao/contao#792]
**Description**  
`\Contao\Image::create()` does not support image sizes defined via configuration.

Only numeric values are accepted and resolved as entries of `tl_image_size`:
https://github.com/contao/contao/blob/f6997ffb142cc6c69eba6e647cde303deec68f60/core-bundle/src/Resources/contao/library/Contao/Image.php#L767-L772

Imo we should either add that functionality or instead use the `contao.image.image_factory` service in this function. Otherwise 3rd party extensions like [isotope](https://github.com/isotope/core/issues/2081) won't work.

(The same holds true for `\Contao\Picture`.)

**Comment by ausi** [comment]
Closed in favor of #805
