### ISSUE TITLE
Modultyp Login-Formular Einstellung Anzahl an Spalten

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#793]
Bei dem Modultyp `Login-Formular` kann bei der Einstellung `Anzahl an Spalten` zwischen den Optionen `Eine Spalte` und `Zwei Spalten` gewählt werden. 

Die Optionen haben jedoch keine erkennbare Auswirkung auf die Ausgabe.

**Comment by asaage** [comment]
https://github.com/contao/core-bundle/issues/1577

**Comment by Mynyx** [comment]
Vielleicht einen Hinweis ergänzen, dass die Einstellung der Abwärtskompatibilität dient und bei Verwendung des aktuellen Templates keine Funktion mehr hat?

**Comment by leofeyer** [comment]
Wir könnten das Feld aus der Palette nehmen, dann wäre es immer noch in der DB für den Theme-Import, würde aber nicht mehr beim Bearbeiten im BE angezeigt.

**Comment by leofeyer** [comment]
Siehe #1001
