### ISSUE TITLE
Fehlende Übersetzung innodb_large_prefix im Installtool

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#794]
Bei der Installation von Contao 4.8.3 wird im Installtool für `innodb_large_prefix` und `innodb_large_prefix_explain` keine Übersetzung angezeigt:

![image](https://user-images.githubusercontent.com/1632642/65669131-49607680-e043-11e9-8f79-b3cc62c16902.png)

**Comment by leofeyer** [comment]
Fixed in 2e27773f1c553e779928f1bd23c82bb8141abbb0.
