### ISSUE TITLE
Update veraltete Bildgrößenangaben

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#795]
In älteren Inhaltselementen vom Typ Bild ist als Bildgröße (Feld `size`) oftmals das Format Proportional ohne Größenangaben gespeichert (`a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:12:"proportional";}`).

Wenn das Inhaltselement gespeichert wird, führt dies nun zu einer Fehlermeldung, da die Größenangaben fehlen und es ist eine manuelle Änderung des des Formats zu `-` erforderlich.

Dies könnte vermieden werden, wenn beispielsweise im Rahmen der Updateroutine im Installtool Datensätze mit `a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:12:"proportional";}` automatisch zu `a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}` geändert werden würden.

**Comment by leofeyer** [comment]
Vermutlich könnten wir das Feld auch einfach leeren, denn `a:3:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";}` entspricht `['', '', '']` und das wird genauso gehandhabt wie ein leerer String.

**Comment by ausi** [comment]
Als Alternative könnten wir das ImageSize widget anpassen sodass es beim laden von `['', '', 'proportional']` automatisch auf `['', '', '']` ändert.

**Comment by Mynyx** [comment]
> Als Alternative könnten wir das ImageSize widget anpassen sodass es beim laden von `['', '', 'proportional']` automatisch auf `['', '', '']` ändert.

Das hätte den Vorteil, dass das Problem automatisch auch in Erweiterungen behoben wäre.

Warum nicht 4.4?

**Comment by ausi** [comment]
> Warum nicht 4.4?

Dort sollte der Fehler nicht auftreten, oder?

**Comment by Mynyx** [comment]
Doch, sogar in 3.5 😃

**Comment by leofeyer** [comment]
Behoben in a80dfaaf38e809d7f059272e31d6224e73fe63a9.
