### ISSUE TITLE
Update Formularfelder Typ Überschrift

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#796]
Beim Update von Contao 3 zu Contao 4 werden Formularfelder vom Typ Überschrift automatisch zum Typ Erklärung geändert.

Es wäre hilfreich, wenn dabei auch automatisch das neue Feld `CSS-Klasse` auf `headline` gesetzt werden würde.

**Comment by leofeyer** [comment]
There is no CSS class `headline` in the headline form field in Contao 3.5. Do you mean `widget-headline`?

**Comment by aschempp** [comment]
There was one in Contao 3 😉 
https://github.com/contao/core/blob/3.5/system/modules/core/templates/forms/form_headline.html5#L4

**Comment by leofeyer** [comment]
I see.

**Comment by aschempp** [comment]
I denke das können wir als obsolet betrachten, Contao 3 ist nun seit Jahren tot 😆
