### ISSUE TITLE
Fehlendes Template führt zu weißer Seite ohne Log-Eintrag

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#798]
Wenn im Frontend ein Template nicht gefunden werden kann, führt dies zu einer weißen Seite (das Template `@ContaoCore/Error/error.html.twig` wird nicht angezeigt) und es erfolgt kein Eintrag im Log (`var/log/prod-xxxx-xx-xx.log`).

Dieses Problem tritt beispielsweise auf, wenn in einem Seitenlayout noch XHTML als Ausgabeformat gespeichert ist.

Auch reproduzierbar indem `vendor/contao/core-bundle/src/Resources/contao/templates/frontend/fe_page.html5` beliebig umbenannt wird.

**Comment by leofeyer** [comment]
Das liegt hieran:

https://github.com/contao/contao/blob/3a48a3dd0a441342121a388f014dce66ea8c4cc0/manager-bundle/src/Resources/skeleton/web/index.php#L17-L18

Ich finde diese Zeile auch falsch, aber wir haben es bei einem Call diskutiert und die @contao/developers haben mich überstimmt. 🤷‍♂

**Comment by Toflar** [comment]
Wieso sollte das daran liegen?

**Comment by leofeyer** [comment]
Weil es das tut. Gerade getestet. 😂

**Comment by Toflar** [comment]
Ja aber das hat damit ja nichts zu tun.
Wir wollen keine PHP-Fehler in Production.

Der Fall müsste abgefangen und in eine Exception konvertiert werden.

**Comment by ausi** [comment]
Ich konnte den Fehler nicht reproduzieren (in Version 4.4 und 4.8). Welche Contao-Version wurde verwendet?

**Comment by Mynyx** [comment]
Sowohl 4.4 als auch 4.8. 

Jedoch habe ich bei einem erneuten Versuch den Fehler zu reproduzieren auch festgestellt, dass ich ihn nicht in allen Installationen mit diesen Versionen reproduzieren kann. Woran dies liegt, habe ich jedoch noch nicht herausgefunden.

Allerdings konnte @leofeyer das Problem offenbar ebenfalls reproduzieren (https://github.com/contao/contao/issues/798#issuecomment-546414888).

**Comment by ausi** [comment]
Eventuell macht die PHP-Version den Unterschied? Ich habe mit PHP 7.2.7 getestet.

**Comment by Mynyx** [comment]
An der PHP-Version scheint es auf den ersten Blick nicht zu liegen, denn ich kann das Problem sowohl mit 7.1.30, 7.2.19 als auch 7.3.6 reproduzieren.

**Comment by aschempp** [comment]
Ich vermute es ist ein `require` das nicht abgefangen wird/werden kann? Vielleicht sollten wir Templates `include`n und dann prüfen ob's geklappt hat?

**Comment by Toflar** [comment]
Korrekt. Das meinte ich mit 

> Der Fall müsste abgefangen und in eine Exception konvertiert werden.

**Comment by leofeyer** [comment]
Also in der 4.4 kann ich das Problem auch nicht reproduzieren. Hab `core-bundle/src/Resources/contao/templates/frontend/fe_page.html5` umbenannt und sehe jetzt im Frontend die Pretty-Error-Screen.

@Mynyx Kannst Du das Problem in Contao 4.4 reproduzieren und wenn ja, wie?

**Comment by leofeyer** [comment]
@Mynyx /ping

**Comment by Mynyx** [comment]
> @Mynyx Kannst Du das Problem in Contao 4.4 reproduzieren und wenn ja, wie?

Ja, weiße Seite tritt in 4.4.45 auf, wenn ``vendor/contao/core-bundle/src/Resources/contao/templates/frontend/fe_page.html5`` umbenannt wird.

**Comment by Mynyx** [comment]
Im Debug-Modus erscheint dann eine ``ContextErrorException``:
> Warning: include(/www/htdocs/xxx/contao/vendor/contao/core-bundle/src/Resources/contao/templates/frontend/fe_page.html5): failed to open stream: No such file or directory

**Comment by leofeyer** [comment]
See #1016
