### ISSUE TITLE
Inhaltselement Typ Downloads Versionsvergleich nach geänderter Reihenfolge der Quelldateien

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#799]
Wenn bei Inhaltselementen vom Typ Downloads die Reihenfolge der Quelldateien verändert wird, wird das Feld Sortierreihenfolge beim Versionsvergleich mit leerem Inhalt angezeigt:

![image](https://user-images.githubusercontent.com/1632642/65723528-da206c00-e0ae-11e9-8d5e-b26d95f1c31b.png)

**Comment by leofeyer** [comment]
Welche Contao-Version ist betroffen?

**Comment by leofeyer** [comment]
See #1002
