### ISSUE TITLE
Alias ContaoFrameworkInterface

### ISSUE THREAD

**Issue by koertho** [contao/contao#8]
**Affected version(s)**
All Versions with Symfony 4 (Contao 4.5+)

**Description**  
Autowiring changed with Symfony 4, so Interfaces must be declared with an alias service to be autwired. 
See [Upgrade introductions](https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md#dependencyinjection).

**How to reproduce**  
Create an class, add ContaoFrameworkInterface as Parameter, register it as service and set autowire to true, instead of set the arguments manually. Works with Symfony 3, fails in Symfony 4.

**Solution** 
Add `Contao\CoreBundle\Framework\ContaoFrameworkInterface: '@contao.framework'` to the service definition.

**Comment by leofeyer** [comment]
What exactly do we need to change? @contao/developers /cc

**Comment by bytehead** [comment]
>  Rename (or alias) your services to their FQCN id to make them autowirable

**Comment by leofeyer** [comment]
See #22.
