### ISSUE TITLE
Tiny MCE | Textänderung im Pop-up bei Verlinkung

### ISSUE THREAD

**Issue by stefan-at-work** [contao/contao#80]
Sofern man eine Textpassage im Tiny markiert und verlinken will, erscheint bei der Eingabe ohne http/https eingibt das Pop-up mit folgendem Hinweis:

> Diese Adresse scheint ein externer Link zu sein. Möchten Sie das dazu benötigte "http://" voranstellen?

Da das https-Protokoll mittlerweile Standard ist, schlage ich vor dies entsprechend zu ändern und dem Link ein https voranzustellen.

**Comment by cliffparnitzky** [comment]
Das Popup erscheint offenbar nur, wenn man die Link URL mit `www.` beginnt. Auf jeden Fall kommt die Meldung aus dem Tiny MCE und wird auch dort nur anzupassen sein.

**Comment by stefan-at-work** [comment]
@cliffparnitzky - Danke für den Hinweis. @leofeyer  Dann kann das Ticket geschlossen werden.
