### ISSUE TITLE
file manager - files cannot be moved to parent folders

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#802]
**Affected version(s)**
Contao 4.8.3

**Description**  
Moving files from a subfolder to a parent folder not possible (see screenshot)
![filemanager](https://user-images.githubusercontent.com/23719181/65752248-aecc6a00-e10c-11e9-9fe1-6383bfa386ac.jpg)

**How to reproduce**  
1. Create subfolders
2. move a file from a subfolder to a parent folder

Notice: Drag & Drop is working

**Comment by asaage** [comment]
This also applies to duplicating files and in the templates module.

**Comment by fredigut** [comment]
Drag & Drop funkioniert auch nicht korrekt. Das verschobene Bild wird umbenannt und als PNG statt JPG abgelegt und gleichzeitig verkleinert (siehe Screenshot)
![Bildschirmfoto 2019-09-28 um 11 28 08](https://user-images.githubusercontent.com/42616484/65814542-7e0b3400-e1e3-11e9-96cd-ea67ab2ba9be.png)

**Comment by leofeyer** [comment]
Fixed in 5320072cbba5dcc3be31c28d567e24b5c7f2a4b9.
