### ISSUE TITLE
Protokoll in Titel und Benutzername bei Zwei-Faktor-Authentifizierung

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#807]
Wenn die Zwei-Faktor-Authentifizierung aktiviert wird, enthalten die an die genutzte App durch den QR-Code übertragenen Angaben zu Titel und Benutzername das Protokoll, worunter die Übersichtlichkeit leidet.

So lautet zum Beispiel der übertragene Benutzername `max.mustermann@https://www.example.com` statt `max.mustermann@www.example.com`.

**Comment by leofeyer** [comment]
Geändert in 06ce1f1e4f98de91d12348180b60c0da55b2fed0.
