### ISSUE TITLE
Partieller Seitencache, No-Cache Blöcke in Templates, vergleichbar mit Seitenindex

### ISSUE THREAD

**Issue by timgatzky** [contao/contao#81]
**Description**  
Der Grundgedanke ist dynamische Elemente / personenbezogene Elemente in Templates partiell aus dem Seitencache zu nehmen. 
Der Seitencache als Ist-Zustand einer Seite, liefert z.B. bei Auswahlen durch einen Betrachter (z.B. Datenschutzauswahlen), einem weiteren Betrachter ggf. den Ist-Zustand des vorherigen Betrachters, weil die Seite dem zweiten Betrachter aus dem Cache geliefert wird.
Derzeit stellt nur Javascript eine zuverlässige Methode dar, um auch rückwirkend am Cache vorbei, personenbezogene / browerbezogene Auswahlen (Cookie, localstorage) zu treffen. PHP kann hier leider nicht mehr genutzt werden, da ab dem Zeitpunkt das eine Seite im Cache liegt, diese als Komplett-Html-Paket ausgeliefert wird.

**Example**  
Ich denke, Ihr wisst auch ohne Beispiel um dieses Phänomen. Wer dennoch ein Beispiel möchte: http://contao4.tim-gatzky.de/seitencache.html

Die Uhrzeit dient als lesbaren Zeitstempel, wann die Seite in den Cache gewandert ist.
Einfach mit zwei Browsern testen oder mit einem Kollegen. Der eine setzt die Auswahl, der andere schaut daraufhin in die Seite und bekommt den Status als hätte er die Auswahl getroffen. 
Anbei ein Screenshot des Test-Codes.

Das Feature-Request daher auf cache:stop, continue Sektionen. Diese würden dynamische Bereiche in Templates ausschließen vom Seitencache.

Mein Test-Template
![screenshot_3565](https://user-images.githubusercontent.com/970730/45865197-f93e3c80-bd7c-11e8-92fa-fdfc8e53e2a8.jpg)

**Comment by fritzmg** [comment]
Ab Contao 4.5 kannst du Module und Inhaltselemente als fragments registrieren (https://github.com/contao/core-bundle/pull/700) und ab Contao 4.6 ist das ganze leichter umzusetzen (https://github.com/contao/core-bundle/pull/1376).

**Comment by Toflar** [comment]
Das geht alles bereits :-) ESI FTW

**Comment by timgatzky** [comment]
Es ist bereits möglich mit einfachen Template-Kommentaren Bereiche aus dem Seitencache auszuschließen? Hast du dazu ein Tutorial oder ein Beispiel an der Hand, wo dies vorgestellt wurde?

**Comment by Toflar** [comment]
Das geht nicht out-of-the-box bzw. wir haben keinen Helper im Template dafür. Der Teil des Templates den du ausklammern möchtest müsste ein eigenes Fragment sein, welches du dann aufrufen musst. 
Grundsätzlich wären die Schritte zum Verständnis:

* Erstmal verstehen wie ESI funktioniert (im Symfony Umfeld: https://symfony.com/doc/current/http_cache/esi.html)
* Dann unsere Implementierung verstehen die eine weitere Abstraktionsebene auf das Fragment-Handling von Symfony bildet. (Das wären die verlinkten PR's, ich weiss nicht wie weit @fritzmg mit der geplanten neuen Doku bereits ist).
* Dann ist es möglich, weitere Fragment-Typen (analog FE Modulen, CE Elementen etc.) zu registrieren und anzusprechen (das ist vorgesehen). Die dann aus dem Template (à la `render_esi()` bei Symfony mit Twig) anzusprechen ist im Moment noch nicht im Core aber theoretisch machbar bzw. kann auch selber nachgerüstet werden. Unsere Templates akzeptieren ja Funktionen.

**Comment by Toflar** [comment]
Ergänzend dazu vielleicht noch die ganz einfache Variante, die aber nicht besonders schön ist, weil sie keine eigenen Cache-Zeiten erlaubt: Einen InsertTag machen und das Flag `uncached` nutzen, also z.B. so: `{{person::15|uncached}}`. Diese werden via ESI durch den InsertTag Controller gerendert.

**Comment by timgatzky** [comment]
Das probiere ich aus. Danke Dir. Ab welcher Contao Version gilt dies?

**Comment by leofeyer** [comment]
> Ab Contao 4.5 kannst du Module und Inhaltselemente als fragments registrieren ([contao/core-bundle#700](https://github.com/contao/core-bundle/pull/700)) und ab Contao 4.6 ist das ganze leichter umzusetzen ([contao/core-bundle#1376](https://github.com/contao/core-bundle/pull/1376)).
