### ISSUE TITLE
Listing events is broken with 32-bit php versions

### ISSUE THREAD

**Issue by m-vo** [contao/contao#811]
**Affected version(s)**
4.8

**Description**  
The changes from 8befee845bd83a1fe10f317d1e0bebcc977b6766 introduce a large integer that is interpreted as float on 32-bit builds. 
```php
$i = 4294967295;

// results on 32-bit builds:
var_dump($i); // float
var_dump($i > PHP_INT_MAX); // bool(true)
var_dump((int) $i); // -1
```

This value is casted to an integer here (which fails with the results `-1`):
https://github.com/contao/contao/blob/master/calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php#L240-L244

As an effect the query returns no events.

**Comment by leofeyer** [comment]
I guess it should be `min(4294967295, PHP_INT_MAX)` then.

**Comment by m-vo** [comment]
agreed

**Comment by m-vo** [comment]
closing in favor of #814
