### ISSUE TITLE
Validate stop date > start date

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#812]
**Affected version(s)**

I think all versions will be affected.

**Description**

Actually the function _show from/show until_ is working just for the following cases:

1. _show from_ is activated
2. _show until_ is activated
3. _both options_ are activated, but _show until_ must be a higher date than _show from_

The following option is not working:
4. _both options_ are activated, but _show until_ is a smaller date than _show from_ 

**How to reproduce**

I have a text element (I think, the problem also exists for articles and pages), which is online, but I want to hide it for a day:
_show from_ is **2019-10-04 00:01**
_show until_ is **2019-10-03 00:01**

I expect, that the text is shown until 2019-10-03 00:01, hidden the whole day of 2019-10-03 and visible again until 2019-10-04 00:01.

But the result is: the text is never visible.

**Comment by asaage** [comment]
Iinteresting use-case...
I guess if it will ever behave like that in the future we will need more icons https://github.com/contao/core-bundle/pull/940 😆

**Comment by Mynyx** [comment]
See https://github.com/contao/core/issues/8818

**Comment by leofeyer** [comment]
That is a very adventurous expectation indeed. 😄

**Comment by frontendschlampe** [comment]
> That is a very adventurous expectation indeed. 😄

Really?

I have the following use case: I have a button on a webpage. The webpage describes an external service. The button is linked to the external service. But the service is not reachable for 3 days because of maintenance. So I want to hide the button for the 3 days and show a hint, that the service is not available. When the service is back again, I want to hide the hint and show the button. Show/hide the hint is no problem, but hide/show the button is the problem.

**Comment by asaage** [comment]
I don't necessarily consider this as a bug - althought the start/stop-fields could theoretically check each other for plausibility in terms of the implemented logic to avoid adventurous expectations.

I probably would appreciate the possibility of start>stop as a feature.

@frontendschlampe An intermediate solution would be to duplicate the content (button) and show one *until* and the other one *from*.

**Comment by frontendschlampe** [comment]
I don't know, if we can call it bug or feature! ;-)

It's not described, that _show from/show until_ is working only from _show from_ to _show until_. I think it's not relevant if it's working from _show from_ to _show until_ or _show until_ to _show from_. There're just two fields:

1. _show from_
2. _show until_

I think, there's no technical limitation which field should be filled or which date should be higher.

**Comment by frontendschlampe** [comment]
> @frontendschlampe An intermediate solution would be to duplicate the content (button) and show one until and the other one from.

It's a solution, but not a good one. I solved the problem manually! ;-)

**Comment by leofeyer** [comment]
As discussed in Mumble on October 24th, we do not want to implement this, because it will lead to inconsistent behaviour (some modules will support it, others will not) and it will negatively affect the database performance.

You can solve your case by adding an alias element, which duplicates the original content element; apply the stop time to the original content element ant the start time to the alias element.

**Comment by leofeyer** [comment]
To prevent this kind of "misconfiguration" in the future, we want to validate that the stop time is greater than the start time.

**Comment by leofeyer** [comment]
See #896

**Comment by leofeyer** [comment]
Since Contao 4.4 is now in the "security updates only" phase of the LTS cycle, I am moving this issue to the 4.9 milestone.
