### ISSUE TITLE
automatic internal redirect of an internal redirect

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#813]
**Affected version(s)**

I think all versions will be affected.

**Description**

For a page we can make an internal redirect. If I don't directly choose a target page (no selection), Contao makes a redirect to the first child page, but this is only working, if the first child page is no redirect page. As discussed in last Mumble call we can change this.

**How to reproduce**  

- _page 1_ - internal redirect, no selection of redirect page
  - _page 1.1_ - internal redirect, no selection of redirect page
    - _page 1.1.1_ - regular page

Expectation: if I will open _page 1_ in the frontend I will be redirected to _page 1.1.1_

Result: I get a error 404 for _page 1_

**Comment by frontendschlampe** [comment]
Which activity is desired?

**Comment by aschempp** [comment]
well I guess a pull request would be best? 😂

**Comment by leofeyer** [comment]
We need to confirm and fix this issue.

**Comment by leofeyer** [comment]
> Result: I get a error 404 for page 1

Actually, this seems to be the desired result. If you do not specify a target, Contao will use the `PageModel::findFirstPublishedRegularByPid()` method to find a regular child page (not child-child page!). And since there is no regular page on the first level, showing the 404 page seems appropriate to me.

**Comment by frontendschlampe** [comment]
I know, we already discussed it on a Mumble Call some months ago (I don't know, why it's not documented), but I think, it's not necessary that this should be desired. I think, it would be better if we can follow the redirect until there's a final page. There will also be no side effects if we change it, because nobody use it, because it ends in a 404.

Why is it "unconfirmed" - the behavior is confirmed. We can decide if it's a bug or a feature.

**Comment by leofeyer** [comment]
> Why is it "unconfirmed"

You are reporting a bug, which I cannot reproduce, because I think that the behavior is correct. Therefore I cannot confirm that this is a bug -> unconfirmed. 🤷‍♂️ 

@contao/developers Do you agree that the current behavior is correct?

**Comment by fritzmg** [comment]
Did this ever work before? If not, then I would consider it a new feature.

**Comment by frontendschlampe** [comment]
> You are reporting a bug, which I cannot reproduce, because I think that the behavior is correct. Therefore I cannot confirm that this is a bug -> unconfirmed. 🤷‍♂️

ah ... ok ... I see ... np :-)

> Did this ever work before? If not, then I would consider it a new feature.

I don't think, that it ever work before, so we can decide if it's a bug, a feature or a known limitation. ;-)

**Comment by fritzmg** [comment]
I would label it as `feature` + `help wanted`.

**Comment by leofeyer** [comment]
I'd vote for "known limitation", because if we would try to implement this, we'd run into more problems:

```
- Page 1 (redirect)
    - Page 1 (redirect)
        - Page 11 (regular)
```

If we would adjust the router to find Page 11 in this case, which page should it find in this one?

```
- Page 1 (redirect)
    - Page 1 (redirect)
        - Page 11 (regular)
    - Page 2 (regular)
```

And what about people who have exactly this setup and rely on the router to find Page 2, because the method is called (and has always been called) "findFirstPublished**Regular**Page"?

**Comment by aschempp** [comment]
We don't need to find page 11, we just need to allow any page except errors when forwarding. The target page will issue the appropriate redirect.
