### ISSUE TITLE
System-Log Funktion Contao\PageRoot::getNextPage

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#815]
Im System-Log wird zur Funktion `Contao\PageRoot::getNextPage` die Meldung `No active page found under root page "1")` protokolliert. Die schließende Klammer am Ende ist wohl ein Tippfehler.

**Comment by leofeyer** [comment]
Welche Contao-Version ist betroffen?

**Comment by Mynyx** [comment]
Contao 4.4.44

**Comment by leofeyer** [comment]
See #881.
