### ISSUE TITLE
Erklärungstext zur Einstellung "Den Command-Scheduler deaktivieren"

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#817]
Der Erklärungstext zu der Option `Den Command-Scheduler deaktivieren` in den Einstellungen lautet `Den Periodic Command Scheduler deaktivieren und die _contao/cron-Route mittels eines echten Cronjobs (den Sie selbst einrichten müssen) ausführen.` bzw. `Disable the periodic command scheduler and trigger the _contao/cron route by a real cron job (which you have to set up manually).`

Eine Information, welches Intervall der echte Cronjob haben sollte, wäre an dieser Stell noch sinnvoll.

Hilfreich wäre es auch die Erläuterung abzukürzen und die ausführliche Erläuterung in einen Hilfe-Assistenten zu verschieben, um die vollständige URL der Route anzuzeigen und copy & paste zu ermöglichen.

**Comment by andreheeke** [comment]
Ich sehe das nicht als notwendige Ergänzung. Dies ist eher ein Fall für die neue Contao-Dokumentation, die etwa zur Konferenz veröffentlicht werden soll. Außerdem ist es eine Entscheidung des Webmasters wie häufig er den Cron ausführt. Das ist eine ziemlich individuelle Frage...

**Comment by Toflar** [comment]
BTW: Doku-Beiträge sind herzlich willkommen und zwar hier: https://github.com/contao/docs
