### ISSUE TITLE
Verschobene Icons in Dateiverwaltung wenn Recht für Quelltexteditor fehlt

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#819]
Im Backend werden die Icons normalerweise stets bündig angezeigt und für nicht aufrufbare Aktionen wird ein graues Icon dargestellt, um die bündige Darstellung zu wahren:

![image](https://user-images.githubusercontent.com/1632642/66254290-9abfe280-e774-11e9-9dbd-bdd3147db19e.png)

Wenn einem regulären Benutzer jedoch das Recht `Dateien im Quelltexteditor bearbeiten` in der Dateiverwaltung fehlt, wird das Icon zum Quelltexteditor gar nicht angezeigt und die übrigen Icons sind verschoben:

![image](https://user-images.githubusercontent.com/1632642/66254328-01450080-e775-11e9-912c-8116ed16a35d.png)

**Comment by asaage** [comment]
https://github.com/contao/contao/issues/195

**Comment by Mynyx** [comment]
> #195

Die Diskussion wurde damit abgeschlossen, dass die grauen Icons beibehalten werden. Dazu ist der oben beschriebene Fall inkonsistent.

**Comment by leofeyer** [comment]
Welche Contao-Version betrifft das?

**Comment by Mynyx** [comment]
Contao 4.4.44

Um den Unterschied zu erkennen, ist es notwendig, dass in den Filemounts auch Unterordner bestehen.

**Comment by leofeyer** [comment]
See #882.
