### ISSUE TITLE
Wrong Description - Hide the YouTube logo

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#82]
**Affected version(s)**
Contao 4.6, other versions not tested

**Description**  
Add a new YouTube Video as content-element.
Set player options "Hide the YouTube logo"
If you activate the checkbox for this option, the logo would be shown instead of hidden.
If you deactivate the checkbox for this option, the logo is hidden.

**How to fix**  
Change the description of this option or fix the function to match the description of the option.

**Comment by leofeyer** [comment]
I cannot reproduce this.

**Regular**

<img width="411" alt="" src="https://user-images.githubusercontent.com/1192057/46287334-843fe380-c582-11e8-98ee-5476be27339e.png">

<img width="432" alt="" src="https://user-images.githubusercontent.com/1192057/46287341-8ace5b00-c582-11e8-973d-10bff0daee5c.png">

**Hidden**

<img width="437" alt="" src="https://user-images.githubusercontent.com/1192057/46287359-9883e080-c582-11e8-9e0a-25129746a31d.png">

<img width="425" alt="" src="https://user-images.githubusercontent.com/1192057/46287362-9caffe00-c582-11e8-86d4-8532e82e316b.png">

**Comment by contaoacademy** [comment]
I have checked this again.
You're right. In the toolbar everything is fine.
I didn't press the play-button.

See this screenshot of my splash-screen bevor I press play-button:

![settings](https://user-images.githubusercontent.com/23719181/46293025-a2154480-c592-11e8-9c12-9aa99b4e495d.png)

![nologo](https://user-images.githubusercontent.com/23719181/46292996-9164ce80-c592-11e8-870f-12f5650c380e.png)

Sorry for that. I think we could close this ticket…
