### ISSUE TITLE
Richtung des Icons für Seitentyp Externe Weiterleitung

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#820]
In Contao 4 wird für den Seitentyp `Externe Weiterleitung` ein Icon mit Pfeil nach links angezeigt:
![image](https://user-images.githubusercontent.com/1632642/66254528-b5e02180-e777-11e9-86c8-b9dff0bd57c3.png)

Mit einem Pfeil nach links würde ich jedoch eher eine Navigation zurück verbinden und nicht eine Weiterleitung.

In Contao 3 handelte es sich noch um einen Pfeil nach rechts:
![image](https://user-images.githubusercontent.com/1632642/66254541-d90ad100-e777-11e9-9df9-948d28aeb080.png)

**Comment by leofeyer** [comment]
This is probably so you can distinguish the two page types when they are unpublished:

<img width="258" alt="" src="https://user-images.githubusercontent.com/1192057/67765643-e9e3f500-fa4c-11e9-9477-6c8219543eb6.png">

@contao/developers I don't think we should change this, should we?

**Comment by OMOSde** [comment]
I also connect an external link with an arrow to the top right. Maybe that would be a variant.

**Comment by leofeyer** [comment]
As discussed in Mumble on December 19th, we agree that the two icons could be optimized. If you have any ideas, please upload your suggestions here.

**Comment by fritzmg** [comment]
In Contao 5.4+ both page types now use the same icon. Sooo... fixed? 😁
