### ISSUE TITLE
Ordner files/__new__ wird nicht gelöscht

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#821]
Wenn in der Dateiverwaltung ein neuer Ordner beispielsweise im Wurzelverzeichnis erstellt wird, dann wird bereits bei Aufruf des Formulares `Einen neuen Ordner erstellen` ein neuer Ordner `files/__new__` angelegt.

Wenn anschließend ohne Eingabe eines Namens auf Speichern geklickt wird (HTML5-Validierung deaktivieren), wird die Datei `files/__new__/.public` angelegt.

Dadurch wird der Ordner `files/__new__` bei Abbruch des Vorgangs nicht gelöscht. Bei Aufruf der Dateiverwaltung im Debug-Modus erscheint die Fehlermeldung `Warning: rmdir(/www/htdocs/xxx/contao/files/__new__): Directory not empty`.

**Comment by leofeyer** [comment]
Welche Contao-Version betrifft das?

**Comment by andreheeke** [comment]
Kann ich unter Contao 4.4 bestätigen.
Allerdings musste ich dafür das required-Attribut auch von dem Input-Tag manuell im DOM entfernen. Erstens glaube ich nicht das der Großteil der Nutzer die HTML5-Validierung manuell deaktiviert oder das jemand das Contao-Backend unter IE10 und älter noch nutzt (hoffen darf man ja)...

**Comment by leofeyer** [comment]
@contao/developers Sollten wir diesen Fall serverseitig auch noch behandeln, obwohl er nur dadurch eintreten kann, dass jemand den HTML-Code manipuliert?

**Comment by Toflar** [comment]
Das sollten wir, ja. Clientside Validierung ist immer nur UX :)

**Comment by Mynyx** [comment]
Der Fehler ist zuerst im Livebetrieb aufgefallen. Ich glaube kaum, dass tatsächlich jemand den HTML-Code manipuliert hat.

**Comment by leofeyer** [comment]
Siehe #903.
