### ISSUE TITLE
Feld "Nur Gästen anzeigen" bei Frontend-Modulen für Mitglieder 

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#823]
Beim Bearbeiten von Frontend-Modulen für Mitglieder (z. B. "Personendaten" oder "Passwort ändern") wird das Feld "Nur Gästen anzeigen" in der Rubrik Experteneinstellungen angezeigt, obwohl diese Module ausschließlich angemeldeten Mitgliedern angezeigt werden.

**Comment by Mynyx** [comment]
Analog betrifft dies auch das Feld "Modul schützen" bei Modulen wie "Registrierung".

**Comment by aschempp** [comment]
Sinnvollerweise sollten wir wohl die entsprechenden Felder aus den Paletten entfernen

**Comment by leofeyer** [comment]
Siehe #883.

**Comment by leofeyer** [comment]
I am going to reopen this and assign it to the 4.8 milestone, so we do not forget to also adjust the new 2FA modules.

**Comment by leofeyer** [comment]
Now that we have agreed on keeping both fields for the login module, there is nothing do adjust anymore.

**Comment by Mynyx** [comment]
> I am going to reopen this and assign it to the 4.8 milestone, so we do not forget to also adjust the new 2FA modules.

And what about this?

**Comment by leofeyer** [comment]
See my comment above. 2FA is part of the login module.

**Comment by aschempp** [comment]
Isn't there a separate module to setup 2FA? Which is only available to members, so it should not have the `guest` option?

**Comment by leofeyer** [comment]
See #1005
