### ISSUE TITLE
Optimierung DC_Table::filterMenu

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#825]
Durch Ergänzung der folgenden elseif-Statements in der Funktion `DC_Table::filterMenu` um `isset`-Bedingungen, ist eine signifikante Optimierung möglich. Wenn die Fälle nicht gegeben sind, wird die Scriptlaufzeit bei großen Datenmengen um mehr als die Hälfte reduziert.

https://github.com/contao/contao/blob/8b8c1e02c29705887293d51331a3212b95ddf798/core-bundle/src/Resources/contao/drivers/DC_Table.php#L5827-L5828
Neu:
```php
						elseif ($GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['eval']['isBoolean'] || (isset($GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['inputType']) && $GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['inputType'] == 'checkbox' && !$GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['eval']['multiple']))
```

https://github.com/contao/contao/blob/8b8c1e02c29705887293d51331a3212b95ddf798/core-bundle/src/Resources/contao/drivers/DC_Table.php#L5862-L5863
Neu:
```php
						elseif ($GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['eval']['isAssociative'] || (isset($GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['options']) && array_is_assoc($GLOBALS['TL_DCA'][$this->strTable]['fields'][$field]['options'])))
```

**Comment by leofeyer** [comment]
> wird die Scriptlaufzeit bei großen Datenmengen um mehr als die Hälfte reduziert.

Wie lässt sich das nachvollziehen?

**Comment by Mynyx** [comment]
Beispielsweise im System-Log mit 10.000 unterschiedlichen Einträgen in ``tl_log::username``.

**Comment by leofeyer** [comment]
Kannst Du mir einen SQL-Dump Deiner Tabelle `tl_log` zukommen lassen, damit ich es selbst testen kann? In meiner `tl_log` sind nur knapp 1.000 Einträge.

**Comment by leofeyer** [comment]
@contao/developers Könnt ihr das bei euch reproduzieren?

**Comment by ausi** [comment]
Nein, nicht ohne den SQL-Dump.

**Comment by leofeyer** [comment]
@Mynyx Kannst Du uns bitte den SQL-Dump Deiner Tabelle zur Verfügung stellen?
