### ISSUE TITLE
User permissions for backend modules of system/design can not be enabled

### ISSUE THREAD

**Issue by rabauss** [contao/contao#826]
**Affected version(s)**
4.4.44 (with custom system/design extensions - only tested for system extension)
4.8.4 (with custom design extensions - not tested)

**Description**  
Since https://github.com/contao/contao/commit/6d6b12296ac27e36758506b5f5d3ea90d1e16025 we have some problems with user permissions of system/design modules. At first I could not explain it and then I did some research.

Because the checkbox widget decides [here](https://github.com/contao/contao/blob/0236382bf085f0a210409957c4b9c70c184f810b/core-bundle/src/Resources/contao/library/Contao/Widget.php#L1366) if it has to use the key or the value. If the modules array has inconsistent array keys, then it will use the key instead of the value. 

With the key as checkbox value for the back end modules, you won't be able to enable any system/design module e.g. file manager (which should have 'files' not '0' as checkbox value) for users or user groups. Or better say: the permissions are saved but with the wrong value, which cannot be validated.

**How to reproduce**  

You have to install a custom extension, which adds a new back end module to `$GLOBALS['BE_MOD']['system']` after the `undo` key - or analog for design modules.
Then you will have the described troubles because of inconsistent array index.

**How to solve**  

After the `unset` of keys in the method `getModules` the arrays `$arrModules['system']` and `$arrModules['design']` should get reindexed.

**Comment by leofeyer** [comment]
```php
unset($arrModules['design'][$key]);
$arrModules['design'] = array_values($arrModules['design']);
```

**Comment by leofeyer** [comment]
See #834.
