### ISSUE TITLE
Dateiverwaltung - Umlaute im Dateinamen erzeugen Fehler

### ISSUE THREAD

**Issue by smeyli** [contao/contao#827]
**Affected version(s)**
4.8.3 und 4.8.2
PHP 7.2
All-Inkl V6-Server

**Description**
Dateiverwaltung: ist eine Datei mit einem Umlaut in einem angelegten Verzeichnis vorhanden, lässt sich dieses Verzeichnis nicht öffnen. Ebensowenig kann man alle Verzeichnisse auf einmal umschalten (Öffnen) - Internal Server Error, Die Dateiverwaltung ist nicht mehr aufrufbar - Es bleibt nur der Weg über "Session-Daten" bereinigen im Benutzerprofil.

**How to reproduce**  
Files via FTP umbenennen.
Das Umbenennen im Backend erzeugt keinerlei Fehlermeldungen.

**Comment by Zodiac1978** [comment]
Echter Umlaut oder Vokal + Trema?
Siehe: https://torstenlandsiedel.de/2016/01/08/normalisieren-eine-bugticket-erlebnisreise-in-die-unicode-welt/

Passiert vor allem bei Macs, da das Dateisystem HFS+ mit NFD (statt NFC) arbeitet. Upload mit Safari sollte klappen, aber Upload mit Firefox/Chrome/etc. macht dann Probleme, da sie nicht beim Upload normalisieren.

Wenn es das ist, dann wäre Betriebssystem + Browser noch ganz interessant zu erfahren.

**Comment by ausi** [comment]
Ich konnte das Problem nicht reproduzieren.

Ist in den Log-Dateien eine Fehlermeldung zu sehen?

> **How to reproduce**
> Files via FTP umbenennen.

Auf was muss die Datei umbenannt werden damit der Fehler auftritt? Kannst du ein konkretes Beispiel geben?

**Comment by xchs** [comment]
> Auf was muss die Datei umbenannt werden damit der Fehler auftritt?

Im Forum war die Rede von Dateinamen mit "ß": https://community.contao.org/de/showthread.php?76121-Dateiverwaltung-erzeugt-quot-internal-Server-Error-quot&p=512173&viewfull=1#post512173

**Comment by ausi** [comment]
Auf einem Linux-Host hab ich einen invaliden UTF-8-Dateinamen getestet `foo\xDFbar.txt` und `f\xF6o\xDFbar.txt`.

Den Fehler konnte ich dennoch nicht exakt reproduzieren. In meinem Test wurden die beiden Dateien leer angezeigt:

<img width="712" alt="Bildschirmfoto 2019-10-14 um 21 57 12" src="https://user-images.githubusercontent.com/367169/66779181-d1f96680-eecd-11e9-8f4b-942e2f2a771c.png">

Die Frage ist, wie sollen wir mit invaliden UTF-8-Dateien umgehen? Ich denke die sicherste Variante wäre eine Warnung zu triggern und die Datei zu ignorieren.

**Comment by leofeyer** [comment]
@smeyli /ping https://github.com/contao/contao/issues/827#issuecomment-541354669

**Comment by leofeyer** [comment]
Part one of the fix: https://github.com/contao/image/issues/61

Additionally, we have to add an UTF-8 check in the `DC_Folder` class, which skips files with invalid characters in their names and adds a warning so the user knows what is wrong.

**Comment by ausi** [comment]
On my todo list.

**Comment by ausi** [comment]
Closed in favor of #1825

**Comment by Metis77** [comment]
Contao 4.9.8
Genau der Fehler tritt bei mir gerade wieder auf. 
Aber nur auf dem Server ... nicht lokal.

Bei uns reproduzierbar:
Ordner mit Umlauten werden einfach nicht erkannt.
Erstelle ich einen Umlaut in Contao, zB ein ü so wird daraus ein `Ã¼`

Die Coallation ist sowohl lokal, also auch auf dem Server `utf8_general_ci`

**Comment by ausi** [comment]
> Erstelle ich einen Umlaut in Contao, zB ein ü so wird daraus ein `Ã¼`

Du erstellst einen Ordner mit Umlaut in Contao, an welchen Stellen wird dann `Ã¼` angezeigt? Am Dateistystem vom Werbserver, in Contao selbst, in der Datenkbanktabelle tl_files?

**Comment by Metis77** [comment]
> > Erstelle ich einen Umlaut in Contao, zB ein ü so wird daraus ein `Ã¼`
> 
> Du erstellst einen Ordner mit Umlaut in Contao, an welchen Stellen wird dann `Ã¼` angezeigt? Am Dateistystem vom Werbserver, in Contao selbst, in der Datenkbanktabelle tl_files?

In Contao selbst bleibt es beim `ü`, aber im Dateisystem des Server (gesehen per FTP) wird daraus ein `Ã¼`.
Und wenn ich per FTP was mit Umlaut anlege (egal ob Verzeichnis oder Datei), dann wird es in Contao (auch nach einem Sync) gar nicht erst angezeigt.

**Comment by fritzmg** [comment]
Das liegt aber am FTP Client bzw. Server, nicht an Contao.

**Comment by ausi** [comment]
> Das liegt aber am FTP Client bzw. Server, nicht an Contao.

Korrekt.

> Und wenn ich per FTP was mit Umlaut anlege (egal ob Verzeichnis oder Datei), dann wird es in Contao (auch nach einem Sync) gar nicht erst angezeigt.

Das ist das richtige Verhalten von Contao. Im Debug-Modus solltest du eigentlich die Fehlermeldung `Path "..." contains malformed UTF-8 characters.` erhalten.

**Comment by Metis77** [comment]
Ok verstehe. Vielen Dank Euch und sorry für den falschen Alarm.
Nach Umstellung auf SFTP klappt es auch mit Umlauten sauber. 
Strange new world :P
