### ISSUE TITLE
Dateiverwaltung: Fehlende Bestätigung nach erfolgreicher Verkleinerung eines Bildes

### ISSUE THREAD

**Issue by githuppi** [contao/contao#83]
**Betroffene Version**
Version 4.4.23

**Beschreibung** 
Wenn ich über die Drop-Zone ein Bild hochlade, welches die maximale Breite für Bild-Uploads in Pixeln überschreitet, erhalte ich nach dem erfolgreichen Upload keine Hinweismeldung.

Normalerweise gibt es den Hinweis: 
Das Bild Test.jpg wurde auf die maximalen Abmessungen verkleinert.

**Wie zu reproduzieren** 
In den Einstellungen eine maximale Breite für Bild-Uploads hinterlegen.
Ein Bild über die Drop-Zone hochladen, welches die maximale Breite überschreitet.

**Comment by leofeyer** [comment]
Behoben in 93315e7976e983619840addb0ee615337c166e02.
