### ISSUE TITLE
booknav does not work as inspected

### ISSUE THREAD

**Issue by Aybee** [contao/contao#832]
**Affected version(s)**
4.4 + 4.8 (online demo)

**Description**  
Ich erwarte, dass die Buchnavigation die Seiten erkennt, welche sich auf der gleichen Ebene befinden, und dementsprechend Links anbietet um auf die nächste/vorherige Seite oder die Elternseite zu verlinken (top). Es ist schwer zu beschreiben was passiert. Die booknav taucht manchmal auf, manchmal nicht und oft mit falschen Links.

**How to reproduce**  
Ein Modul Typ Buchnavigation erstellen - Startpunkt als Referenzseite setzen - und in allen Layouts einbinden. (Gerade in der online Demo gemacht, evtl. noch vorhanden). Die Buchnavigation auf allen Seiten testen.

**Comment by asaage** [comment]
Meines Wissens liest sie ab der Referenzseite den Seitenbaum von von oben nach unten wie er im BE angelegt ist.
Durch interne Weiterleitungen oder "im Menü nicht sichtbar" kann es natürlich zu Sprüngen oder Aussetzern kommen.

**Comment by leofeyer** [comment]
Wie genau lässt sich das Problem reproduzieren?
