### ISSUE TITLE
Force FE users to change password

### ISSUE THREAD

**Issue by Anke** [contao/contao#836]
**Description**  
I'm pleading for a possibility to make FE users change their passwords sporadically.

At the moment I can only reset their passwords by overwriting them, so that they will not be able to login but be forced to use "I forgot my password" function. In this case, however, nothing will prevent users from re-using their old passwords, that they might have been using for 8 years.

**Example**  
Like for backend users I'm thinking of an option like "Password change required" for front end user accounts. And when the FE user changes his/her password, Contao ought to keep the user from using his former password.

**Comment by aschempp** [comment]
https://extensions.contao.org/?p=terminal42%2Fcontao-password-validation

**Comment by Anke** [comment]
Cool - danke!
