### ISSUE TITLE
Friendly-name e-mail address with less-than and greater-than signs

### ISSUE THREAD

**Issue by xchs** [contao/contao#838]
**Affected version(s)**
Contao 4.4 & Contao 4.8

**Description** 
Contao should actually be able to handle both `Foobar <foobar@example.com>` and `Foobar [foobar@example.com]` friendly-name e-mail addresses. The `rgxp` evaluation in the `Widget` class checks for an friendly-name e-mail address in

https://github.com/contao/contao/blob/2635f5a043c1308fd3fe1352b4b9de7665206cc8/core-bundle/src/Resources/contao/library/Contao/Widget.php#L969-L983

and converts the friendly-name e-mail address to the format with square brackets (`Foobar [foobar@example.com]`).

The `StringUtil::splitFriendlyEmail()` function splits the friendly-name e-mail address and returns both the _name_ and the _e-mail address_ in an array:

https://github.com/contao/contao/blob/2635f5a043c1308fd3fe1352b4b9de7665206cc8/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L404-L424

Actually, that should work (see e.g. https://3v4l.org/k2M60).

For some reason, however, Contao shows an error message when it comes to store a friendly-name e-mail address with less-than (`<`) and greater-than (`>`) signs (`Foobar <foobar@example.com>`). During my tests the less-than (`<`) sign was sometimes converted to `&lt;` so the `;` character could cause problems when [validating the e-mail address](https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/library/Contao/Validator.php#L125-L148).

**How to reproduce** 
* Log into the Contao back end
* Open the _System settings_
* Enter e.g. `Foobar <foobar@example.com>` as friendly-name e-mail address for the system administrator
* Save the _System settings_

**Comment by leofeyer** [comment]
You cannot use the `Name <email>` format in an input field, because the `Input` class (or more specifically the PHP `strip_tags()` method) would remove the `<email>` part that looks like an HTML tag. You will have to use the `Name [email]` format instead.

**Comment by xchs** [comment]
All right, that explains the behavior.

So in that case, we could actually remove that check, right?

https://github.com/contao/contao/blob/2635f5a043c1308fd3fe1352b4b9de7665206cc8/core-bundle/src/Resources/contao/library/Contao/StringUtil.php#L413-L416

Do you think we should point out in the help text that only the `Name [email]` format is valid?

**Comment by fritzmg** [comment]
You cannot remove this. This StringUtil function is also independent of this issue.

**Comment by leofeyer** [comment]
Correct. The `StringUtil` class handles both cases.
