### ISSUE TITLE
ce_hyperlink href doesn't match Environment request

### ISSUE THREAD

**Issue by obendev** [contao/contao#839]
Hey, I tried setting my own active state for a page. While coding I noticed that the href in ce_hyperlink has a weird string.

Hyperlink is set to Inserttag `{{link_url::13}}` which is equal to `secretalias`.
URL I'm on: `https://domain.tld/secretalias`
```php
var_dump($this->href);
var_dump($this->Environment->request);

var_dump(bin2hex($this->href));
var_dump(bin2hex($this->Environment->request));
```

Output
```
string(16) "secretalias"
string(11) "secretalias"

string(32) "7b7b6c696e6b5f75726c3a3a31337d7d"
string(22) "736563726574616c696173"
```

This makes this impossible to use
```php
if ($this->href == $this->Environment->request)
```

Also, `objPage->alias` matches `$this->Environment->request`, so it should work.
```php
global $objPage;

var_dump($objPage->alias);
var_dump($this->Environment->request);

var_dump(bin2hex($objPage->alias));
var_dump(bin2hex($this->Environment->request));
```

Output
```
string(11) "secretalias"
string(11) "secretalias"

string(22) "736563726574616c696173"
string(22) "736563726574616c696173"
```

All code was executed in ce_hyperlink.html5 Template on Contao 4.4.42, fresh installation without any extensions.

What I tried so far (Without any useful result or solution)
```
htmlspecialchars_decode
html_entity_decode
mb_detect_encoding (same)
mb_convert_encoding
utf8_encode
strip_tags
trim
```

**Comment by obendev** [comment]
**Solution** is `replaceInsertTags`
```php
if ($this->replaceInsertTags($this->href) == $objPage->alias)
```

Because `$this->href` is `{{link_url::13}}`, not `secretalias`.

**Comment by leofeyer** [comment]
You could also check `$this->href == '{{link_url::'.$objPage->id.'}}'`.
