### ISSUE TITLE
Formular: Pflichtfeld Validierungsmeldung auf englischer Seite in deutscher Sprache 

### ISSUE THREAD

**Issue by githuppi** [contao/contao#84]
**Betroffene Versionen**
Version 3.5.X
Version 4.4

** Beschreibung** 
Die Validierungsmeldung vom Pflichtfeld (required) eines Formulares erscheint auf einer englischen Seite in deutscher Sprache.

**Wie zu reproduzieren**  
Browser auf englisch einstellen, 
englische Seite mit Formular aufrufen, 
Pflichtfeld in Formular unausgefüllt lassen und Formular absenden.

**Comment by asaage** [comment]
Du musst im Formular(BE) die

- [x] HTML5-Validierung deaktivieren

Oder die Sprache deines Betriebssystems bzw. Browsers ändern wenn du die HTML5-Validierung nutzen möchtest.
Die "Bevorzugte Sprachen für die **Darstellung von Websites** wählen" (so wird es zumindest im Firefox bezeichnet) hat keinen Einfluss darauf. Denn Die Meldungen kommen vom Browser selbst und nicht von der Website. Wenn dein Browser englische Menü's zeigt bekommst du auch englische Fehlermeldungen.

**Comment by tinokramm** [comment]
> […] Wenn dein Browser englische Menü's zeigt bekommst du auch englische Fehlermeldungen.

Das Verhalten kann ich so nicht nachvollziehen. Stelle ich den Chrome auf Englisch, dann gibt mir Contao im FE die englischen Menüs aus. Die HTML5-Validierungsmeldung bleibt jedoch leider auf Deutsch. Stelle ich die Systemsprache auf Englisch, erscheint auch die Validierungsmeldung auf Englisch.

**Comment by fritzmg** [comment]
> Die HTML5-Validierungsmeldung bleibt jedoch leider auf Englisch.

Das ist normal. Die HTML5 Validierung hat mit Contao nichts zu tun. Die wird vom Browser in der Sprache des Browsers dargestellt.

**Comment by tinokramm** [comment]
Hm. Mir scheint das unausgegoren zu sein. Wenn ich mich als User auf einer Website bewusst für eine fremdsprachige Ausgabe entscheide – egal was im Browser oder System eingestellt ist – dann müsste doch konsequenter Weise auch die Validierungsmeldung übersetzt sein.

**Comment by fritzmg** [comment]
So ist das aber nun mal nicht ;). Contao kann das nicht ändern, da es eine Sache des Browsers ist.

Wenn dir das nicht gefällt, kannst du die HTML5 Validierung ja abschalten.
