### ISSUE TITLE
CSS Medientypen werden nicht exportiert.

### ISSUE THREAD

**Issue by kroerig** [contao/contao#842]
**Affected version(s)**
4.8.x und vermutlich auch alle älteren

**Description**  
Beim Exportieren des CSS Stylesheets eines Themes werden die Medientypen nicht mit exportiert (sofern nicht mit Mediaqueries verbunden)

**How to reproduce**  
Stylesheet mit Medientyp "print" anlegen und exportieren.
Die exportierte Datei enthält keinen `@print {}`- Block.

Das erschwert Nutzern des internen Editors die Umstellung und sollte vor einem Entfernen des Editors behoben werden.

**Comment by leofeyer** [comment]
See #905. Note that the media type is only added if there is no media query.
