### ISSUE TITLE
Suche funktioniert nicht mehr

### ISSUE THREAD

**Issue by eki89** [contao/contao#843]
**Affected version(s)**
4.8.x - Ältere Versionen scheinbar nicht betroffen

**Description**
Die Contao-Suche gibt keine Suchergebnisse mehr aus. Der Suchindex wird dabei grundsätzlich angelegt in der Datenbank.

**How to reproduce**
Die indexierung funktioniert in zwei unserer Installationen nicht mehr. Teilweise wird ein Suchcache angelegt, der scheinbar ab einem bestimmten Moment gewiped wird, bzw. nicht mehr berücksichtigt wird.

@Community: Kann jemand bestätigen, dass die Suche unter Contao 4.8 grundsätzlich nicht mehr zuverlässig funktioniert?

**Comment by fritzmg** [comment]
Were you able to reproduce it in a fresh Contao 4.8.4 installation?

**Comment by eki89** [comment]
Habe Contao soeben neu aufgesetzt und getestet. Wird keine Weiterleitung im Modul "Suchmaschine" eingestellt, funktioniert die Auflistung. Das macht so weit an sich auch durchaus Sinn, da man eh nicht das gleiche Suchmodul nutzen kann, wenn dieses im Layout verankert ist. Im Zusammenhang mit geschützten Seiten scheint es aber weiterhin Probleme zu geben. Ich versuche den Zustand in der frischen Installation nachzustellen und berichte nochmal.

**Comment by fritzmg** [comment]
> Wird keine Weiterleitung im Modul "Suchmaschine" eingestellt, funktioniert die Auflistung. Das macht so weit an sich auch durchaus Sinn, da man eh nicht das gleiche Suchmodul nutzen kann, wenn dieses im Layout verankert ist.

Das ist normal. Für ein Suchmodul im Seitenlayout benutzt du die Weiterleitungsseite. Für das Suchmodul zur Anzeige der Ergebnisste stellst du _keine_ Weiterleitungsseite ein.

> Im Zusammenhang mit geschützten Seiten scheint es aber weiterhin Probleme zu geben.

Welche Probleme? Geschütze Seiten werden nicht in den Suchindex aufgenommen, sofern nicht die entsprechende Option dafür in den System Einstellungen gesetzt ist.

**Comment by eki89** [comment]
> Welche Probleme? Geschütze Seiten werden nicht in den Suchindex aufgenommen, sofern nicht die entsprechende Option dafür in den System Einstellungen gesetzt ist.

Ich konnte mit deinen Tipps beide Probleme in diesem Zusammenhang lösen. Vielen Dank für deine Hilfe und entschuldigung für die falsche Fehlermeldung. Ich werde in Zukunft zunächst versuchen das Problem in einer frischen Installation zu reproduzieren.
