### ISSUE TITLE
MySQL 8.0.15 - Error bei Abfrage der Benutzergruppe

### ISSUE THREAD

**Issue by saress** [contao/contao#847]
**Affected version(s)**
Contao 4.4.44 LTS, MySQL 8.0.15

**Description**  
Der Versuch die Benutzergruppe bei den Benutzern oder Mitgliedern im Backend zu filtern
führt zu einer Fehlermeldung im Frontend, die anscheinend damit zu tun hat, dass Contao in der Query mit "groups" ein in MySQL 8 reserviertes Wort verwendet, siehe auch hier:

https://community.contao.org/de/showthread.php?76187-MySQL-8-0-15-SQL-Error-bei-Abfrage&p=512560&viewfull=1#post512560

Beste Grüße
Sares

**Comment by ausi** [comment]
Siehe auch https://github.com/contao/contao/issues/727#issuecomment-532132757

Anscheinend fehlen hier einige Aufrufe von `Database::quoteIdentifier()` für die Spalte auf der gefiltert wird im DC_Table: https://github.com/contao/contao/blob/0236382bf085f0a210409957c4b9c70c184f810b/core-bundle/src/Resources/contao/drivers/DC_Table.php#L5474-L5546

**Comment by leofeyer** [comment]
> Versuch […] im Backend zu filtern führt zu einer Fehlermeldung im Frontend

@saress Was genau ist damit gemeint?

**Comment by leonexcc** [comment]
Im Listing der Mitglieder oben eine Benutzergruppe auswählen und danach filtern:

![Bildschirmfoto 2019-10-28 um 16 51 59](https://user-images.githubusercontent.com/7428636/67694338-7934ce00-f9a3-11e9-9660-50cd33631cc5.png)

Darauf folgt folgende Exception:

An exception occurred while executing 'SELECT COUNT(*) AS count FROM tl_member WHERE groups LIKE '%\"1\"%'':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups LIKE '%\"1\"%'' at line 1

**Comment by leofeyer** [comment]
Der Fehler im Backend ist mir klar, aber der im Frontend nicht. Wo genau tritt der auf?

**Comment by leonexcc** [comment]
Tut mir Leid, das hab ich nicht korrekt gelesen. Das verstehe ich auch nicht ganz.

**Comment by saress** [comment]
@leofeyer : sorry, das ist natürlich nicht das Frontend gewesen, sondern das Standard-Backend-Template für Fehlermeldungen, hab mich da "optisch" etwas verwirren lassen :-)

**Comment by leofeyer** [comment]
Alles klar. 👍

**Comment by leofeyer** [comment]
See #906
