### ISSUE TITLE
Newsletter subscribe module don't show channels without redirect page

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#848]
**Affected version(s)**
4.8.4
4.4.44 

**Description**  
In the newsletter subscribe module only channels are displayed that have explicitly defined a redirect page.

**How to reproduce**  

1. Add a new newsletter channel without selecting a redirect page
2. Add a module "newsletter subscribe"
3. You couldn't find a channel
4. Add a redirect page to the channel
5. You could select the channel in the "newsletter subscribe" module

I think the "redirect page" should be a mandatory field or the "newsletter subscribe module" should also listen channels without a defined redirect page.

Maybe this behavior has to do something with: #494

**Comment by leofeyer** [comment]
See #907
