### ISSUE TITLE
Argument 1 passed to ParagonIE\ConstantTime\Base32::encodeUpperUnpadded() must be of the type string, null given

### ISSUE THREAD

**Issue by ghost** [contao/contao#85]
**Affected version(s)**
4.6.5

**Description**

Ich hab gerade meine 4.4er Version auf 4.6 geupgradet und wollte natürlich sofort die 2FA ausprobieren. Scannen des Codes funktioniert, gebe ich allerdings den Bestätigungscode ein, bekomme ich folgende Fehlermeldung beim Klicken des "Aktivieren"-Buttons:

`Argument 1 passed to ParagonIE\ConstantTime\Base32::encodeUpperUnpadded() must be of the type string, null given, called in /var/www/html/contao/vendor/contao/core-bundle/src/Security/TwoFactor/Authenticator.php on line 78`

POST-Parameter hängen dem Request an, die Funktion sollte die Werte demnach eigentlich bekommen.

Zum Upgrade habe ich die composer.json einer frischen 4.6er Installation in meine bestehende eingegliedert. Soweit läuft sonst aber alles super :)

**How to reproduce**  
s.o.

**Comment by leofeyer** [comment]
Hast Du das Datenbank-Update im Installtool durchgeführt? Das Feld `tl_user.secret` ist bei Dir scheinbar `null`, sollte aber das Secret enthalten.

**Comment by ghost** [comment]
Haha, das war's 👍 könnte man beim Update via Composer vielleicht nicht am Ende der Routine-Arbeiten einen Hinweis ausgeben, daran zu denken, dass Installtool zu öffnen? ^^

**Comment by leofeyer** [comment]
> könnte man beim Update via Composer vielleicht nicht am Ende der Routine-Arbeiten einen Hinweis ausgeben, daran zu denken, dass Installtool zu öffnen?

@aschempp Meines Wissens nach macht der Manager das, oder?

**Comment by fritzmg** [comment]
Der Contao Manager schon - aber ich denke @paaddyy meint bei composer Operationen direkt auf der Konsole.

**Comment by ghost** [comment]
genau, ich mein den Update via Konsole :)

**Comment by leofeyer** [comment]
Ach so. Dafür müsste man wohl ein Composer-Plugin schreiben.

**Comment by leofeyer** [comment]
@aschempp Können wir das im Manager-Plugin machen oder müsste es separat sein?

**Comment by aschempp** [comment]
Was willst du machen? Einen Contao-Nutzer darauf hinweisen dass er das Install-Tool öffnen muss??

**Comment by leofeyer** [comment]
Ja, so eine Art "What's next" wie bei Symfony Flex.

**Comment by aschempp** [comment]
Naja, ganz ehrlich… wenn man Composer auf Kommandozeile nutzt sollte man doch wissen was man tut? Sonst sollte man besser den Manager verwenden?

**Comment by ghost** [comment]
Nichts gegen den Manager, aber ich denke manche verwenden nur die Konsole, da es bequemer ist (jedenfalls für mich als Admin, der sowieso immer Konsolen zu Servern offen hat). 
War ja auch nur eine Idee, dort einen Hinweis anzuzeigen. Denn ich glaube, ich bin nicht der einzige, der das öfters mal vergisst und sich über Sachen danach wundert..^^

**Comment by aschempp** [comment]
Natürlich, ich verwende auch die Konsole. Wir könnten natürlich einfach einen Hinweis in unseren ScriptHandler machen …

**Comment by leofeyer** [comment]
Gute Idee. 👍
