### ISSUE TITLE
Wrong base url with reverse proxy

### ISSUE THREAD

**Issue by MaximilianMrkwrt** [contao/contao#851]
**Affected version(s)**
4.8

**Description**  
base url is https://example.com/example.com instead of https://example.com

I have a contao server behind a reverse proxy, which looks like this:
Internet <--HTTPS--> Reverse Proxy <--HTTP--> Contao
For that reason I have set `['TL_CONFIG']['sslProxyDomain'] = 'example.com';`

**How to reproduce**  
Put contao behind a reverse proxy and set `sslProxyDomain`. The reverse proxy must use the X-Forwarded-Host http header

**Workaround / Fix**  
I fixed it for me, by editing https://github.com/contao/contao/blob/3a70ea01a545d97481c3120fcd847eb878dc1ad7/core-bundle/src/Resources/contao/library/Contao/Environment.php#L339-L351

I changed L347 to `return 'https://' . $xhost`

**Comment by aschempp** [comment]
I don't think you need to set `sslProxyDomain`, have you tried what happens without it?

**Comment by MaximilianMrkwrt** [comment]
Of course, if I don't set `sslProxyDomain`, base url will be http://example.com instead of https://example.com. Or even worse, when the proxy doesn't use the Host header, since it uses the X-Forwarded-Host header: http://some-local-ip ... Because of this, `sslProxyDomain` exists (I think). Only problem is `return 'https://' . $xhost . '/' . $host;`. I can't imagine a useful scenario for appending `/$host` to `https://example.com`

**Comment by MaximilianMrkwrt** [comment]
Let's say you have `$xhost`= example.com and `$host` = 192.168.0.3 than `return 'https://' . $xhost . '/' . $host` would give you https://example.com/192.168.0.3 . That doesn't make any sense for me. 

However: If you don't use `sslProxyDomain` at all, you get `<base href="http://example.com/">` instead of **https**, because the reverse proxy uses http to communicate with the contao server, but the user gets his requested html always served via https from the reverse proxy. And because of [Mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) the user sees garbage instead of a good looking website.

**Comment by leofeyer** [comment]
About 15 years ago, SSL certificates were quite expensive, therefore many hosting companies allowed their clients to access their website `http://client.com` via HTTPS as `https://ssl-sites.com/client.com`. Contao supported this use case, which is why the proxy URL contains both `$xhost` and `$host`.

Nowadays, this setup is obsolete and we should adjust Contao accordingly.

**Comment by MaximilianMrkwrt** [comment]
If you change that line like I did and want `https://ssl-sites.com/client.com` for SSL as your base url, you could still write `ssl-sites.com/client.com` in `sslProxyDomain`.

**Comment by leofeyer** [comment]
True. 👍

**Comment by leofeyer** [comment]
See #1053
