### ISSUE TITLE
Verwaltung des Rechts für das Theme-Modul Theme-Import

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#853]
Wenn einem regulären Benutzer das Recht für das Modul Templates eingeräumt wurde, erscheint im Modul Benutzer eine Warnung: "Mindestens ein regulärer Benutzer hat Zugriff auf den Template-Editor. Da Templates PHP-Dateien sind, haben diese Benutzer implizit die volle Kontrolle über das System!"

1. Wenn einem regulären Benutzer das Recht für das Theme-Modul ``Theme-Import`` eingeräumt wurde, erscheint keine Warnung, obwohl auf diesem Weg ebenfalls der Import von beliebigen Templates möglich ist.

2. Ein regulärer Benutzer kann auch, wenn er aufgrund der Einstellung ``Erlaubte Felder`` in einer seiner Benutzergruppen das Recht für das Feld ``themes`` in ``tl_user`` oder ``tl_user_group`` hat, sich oder anderen Zugriff auf den ``Theme-Import`` verschaffen.
Die Berechtigung für das Theme-Modul ``Theme-Import`` sollte daher nur von Administratoren vergeben werden könnte, unabhängig von der Berechtigung für das Feld ``theme`` in ``tl_user`` oder ``tl_user_group``.

**Comment by aschempp** [comment]
Aus meiner Sicht sollten Themes nur vom Admin importiert werden können.

**Comment by Toflar** [comment]
Definitiv, seh ich auch so wie @aschempp.

**Comment by leofeyer** [comment]
Sehe ich auch so. Allerdings können wir das nicht in einer Patch-Version ändern, oder?

**Comment by Mynyx** [comment]
Es wäre auch eine Überlegung, das Modul ``Theme-Export`` ebenfalls nur für Administratoren zu erlauben. Eine Manipulation des Systems ist damit zwar nicht möglich, aber der Export umfasst ggf. weitaus mehr Daten als auf die der Benutzer regulär zugreifen dürfte. Nicht zuletzt könnte eine Exportfunktion ohne Importfunktion verwirrend wirken.

**Comment by leofeyer** [comment]
Wie am 19. Dezember auf Mumble besprochen, sollen zukünftig nur Benutzer Themes importieren und exportieren können, die Zugriff auf den Template-Editor haben.

**Comment by leofeyer** [comment]
Leider haben wir nicht bedacht, dass das Recht für den Import bzw. Export von Themes bereits separat vergeben werden kann:

<img width="451" alt="" src="https://user-images.githubusercontent.com/1192057/72417956-32709c00-377a-11ea-9e5d-61f6f19ec418.png">

@contao/developers Wir bräuchten also tatsächlich eine Info wie beim Theme-Editor, oder?

**Comment by Toflar** [comment]
Scheint mir sinnvoll, ja.

**Comment by leofeyer** [comment]
Siehe #1196.
