### ISSUE TITLE
navigation-menu does not allways show redirect-pages

### ISSUE THREAD

**Issue by asaage** [contao/contao#855]
**Affected version(s)** 4.8.4 (probably earlier)

**Description**  
If you create a internal-redirect page without a target that page will automatically be redirected to the first child-page and then appear like that in the navigation module. That does not work if that child-page itself is a internal- or external redirect-page. None of the pages apear in the regular menu-module at all.
Is this intentional to prevent too many redirects?
For me it seems to be a bug because it works for the breadcumb and you can work around it by pointing the page-with-issue to an arbitary (preferably it's first childpage) location.

**How to reproduce**  
create following sitestructure
- root-site
  - regular-page
  - page-with-issue (type internalredirect / no target)
    - firstchildpage (type externalredirect or internalredirect to other-page)
  - other-page

then observe how a regular navigation module behaves.

**Comment by aschempp** [comment]
sounds like a duplicate of https://github.com/contao/contao/issues/813 ?

**Comment by asaage** [comment]
#813 was about the 404 Response #855 is about missing menu-items.
Probably there is one fix for both issues 🤷🏼‍♂️

**Comment by asaage** [comment]
@stalebot: Thanks for your notification.

**Comment by asaage** [comment]
I couldn't reproduce this in 4.9.3. The menu seems to be correct now - not shure why.
But the internal-redirect-page without target still does not point to it's first child-page if that is also a redirect (in/external).

**Comment by leofeyer** [comment]
That seems intended, as we are using the `PageModel::findFirstPublishedRegularByPid()` method to find the child page.

**Comment by asaage** [comment]
Okay - I don't understand why it's only looking for regular pages (maybe to prevent redirect-loops?)
Can be closed then i guess - but i didn't try that for 4.4.

**Comment by leofeyer** [comment]
> why it's only looking for regular pages (maybe to prevent redirect-loops?)

Exactly.
