### ISSUE TITLE
eval.path does not work correctly with the new fileTree picker

### ISSUE THREAD

**Issue by ausi** [contao/contao#856]
**Affected version(s)** 4.8 (probably also 4.4?)

If I go to the file manager and select the folder *files/foo*, this folder gets stored in the session under `tl_files_node`.

If I then click on a `fileTree` widget which has the configuration `eval => ['path' => 'files/bar']` the breadcrumbs incorrectly display *files/foo* and no file or folder is visible:

![Screenshot_2019-10-17 Sale › Produkt ID 374 bearbeiten area at 127 0 0 1 xip io](https://user-images.githubusercontent.com/367169/67020100-f3d93000-f0fd-11e9-86ef-681e6d9ac8a2.png)

The problem is that the breadcrumbs logic gets executed `onload_callback` https://github.com/contao/contao/blob/4.8/core-bundle/src/Resources/contao/classes/Backend.php#L1046 and the picker only afterwards https://github.com/contao/contao/blob/4.8/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L3073-L3074

The old file selector has the logic for this issue here: https://github.com/contao/contao/blob/4.3.0/core-bundle/src/Resources/contao/widgets/FileSelector.php#L211-L226

**Comment by leofeyer** [comment]
See #888
