### ISSUE TITLE
mod_article Artikelalias wird im frontend nicht mehr als ID eingetragen

### ISSUE THREAD

**Issue by green-pixelbox** [contao/contao#859]
Contao 4.4.42

Der Name des ARtikelalias im Backend wird im Frontend nicht mehr im DIV als ID eingetragen, sondern es gibt eine Standardausgabe mit "article-ID". Erst wenn ich in das CSS-Feld ID den Namen eintrage, wird im Frontend im DIV das auch als ID eingetragen, soweit richtig. Aber warum wird der Artikelalias nicht mehr als ID im Frontend ausgegeben? Hat das einen Grund? Das Problem trat nach einem Update von 3.5 auf 4.4 auf. Es funktioniert aber auch nicht bei einer frischen Installtion von Contao 4.4.

**Comment by xchs** [comment]
Siehe https://github.com/contao/core/issues/4837
