### ISSUE TITLE
Layout - Order of frontend modules reversed

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#861]
**Affected version(s)**
4.4.44

**Description**  
In the layout, the columns for frontend modules are displayed in reverse order.

Previously: Header > Main > Footer
Now: Footer > Main > Header

See screenshot
![module](https://user-images.githubusercontent.com/23719181/67207013-0495e880-f413-11e9-8ed3-84be08434e43.jpg)

**Comment by mlwebworker** [comment]
Ich finde ja die alphabetische Sortierung hat auch etwas für sich. Früher habe ich mich immer geärgert, dass Custom-Bereiche ganz unten landen. Das dürfte damit ja auch der Vergangenheit angehören.

**Comment by contaoacademy** [comment]
> Ich finde ja die alphabetische Sortierung hat auch etwas für sich. 

Ich finde es so unlogisch sortiert. Unter Contao 4.8 ist es noch so wie früher und ich sehe darin einen Bug.

**Comment by xchs** [comment]
Im Forum wurde das ebenfalls angesprochen: https://community.contao.org/de/showthread.php?76134-Contao-4-4-44-Seitenlayouts-Frontend-Module-2-Spalte-wird-sortiert

**Comment by leofeyer** [comment]
Ich sehe darin keinen Bug.

Vor Contao 4.8 waren die eigenen Layoutbereiche immer am Ende und jeder, dessen Layoutbereich mit "A" begann, hat sich gewundert, warum dieser nicht angezeigt wird (weil eben erwartet wurde, dass "A" oben steht). Jetzt sind die Bereiche alphabetisch geordnet und der Bereich mit "A" wird wie erwartet oben angezeigt.

Natürlich stolpert man als erfahrener Contao-Nutzer vielleicht darüber, weil es halt anders ist als vorher. Aber anders heißt ja nicht automatisch schlechter.

**Comment by contaoacademy** [comment]
@leofeyer 
Hmm, es ist vielleicht kein Bug.
Aber das Verhalten zwischen Contao 4.44.4 und Contao 4.8.4 ist trotzdem anders.
Unter 4.4 wie im 1. Post (Fußzeile vor Kopfzeile) unter 4.8.4 so wie ich das kenne (Kopfzeile vor Fußzeile) (siehe Screenshot)
![contao-4-8](https://user-images.githubusercontent.com/23719181/67590959-8449ed00-f75c-11e9-8d63-b8b5d384ec77.jpg)

**Comment by contaoacademy** [comment]
Ergänzung…
Im Grunde ist es mir egal. Hauptsache bei Contao 4.8.4 verhält es sich dann gleich wie unter 4.4.44

**Comment by Mynyx** [comment]
> Vor Contao 4.8 waren die eigenen Layoutbereiche immer am Ende und jeder, dessen Layoutbereich mit "A" begann, hat sich gewundert, warum dieser nicht angezeigt wird (weil eben erwartet wurde, dass "A" oben steht).

Vielleicht die eigenen Layoutbereiche am Anfang anzeigen und darunter die Standardlayoutbereiche in logischer Reihenfolge.

**Comment by aschempp** [comment]
Ich sehe nur zwei Möglichkeiten:
1. Alphabetisch (einfach umzusetzen / bereits der Fall)
2. Wie konfiguriert. Das wäre imho am sinnvollsten. Die Layoutbereiche haben eine definierte Position, entsprechend könnten sie auch in der Liste sein.

**Comment by contaoacademy** [comment]
> 2\. Wie konfiguriert. Das wäre imho am sinnvollsten. Die Layoutbereiche haben eine definierte Position, entsprechend könnten sie auch in der Liste sein.

Ich denke, das wäre doch die logische Variante. Damit habe ich die volle Kontrolle über die Position der Module und kann mir das so aufbauen wie es mir gefällt.

**Comment by leofeyer** [comment]
Hm, also in Contao 4.8 scheinen die Bereiche bereits nach definierter Position sortiert zu sein; wir haben das offenbar als neues Feature in der 4.6 hinzugefügt (siehe 94de42ae7cfc2d06e2f222a0d26bd089ed131a5b bzw. https://github.com/contao/core-bundle/issues/1529).

@contao/developers Wenn das ein neues Feature in der 4.6 war, bedeutet das "wontfix" für dieses Issue in Contao 4.4 oder soll ich die Änderungen zurückportieren?

**Comment by contaoacademy** [comment]
Ich wäre für "Änderungen zurückportieren".

**Comment by Toflar** [comment]
wontfix.
Für mich ist das klar für den Betrieb irrelevant und kein Bug.
Die 4.9 steht eh vor der Tür - ich möchte mich ungern mit solchen Details aufhalten.

**Comment by ausi** [comment]
wontfix

**Comment by contaoacademy** [comment]
> Die 4.9 steht eh vor der Tür - ich möchte mich ungern mit solchen Details aufhalten.

Da stimme ich dir zu.
Ich schließe das Ticket, da das Verhalten unter Contao 4.9 ja dann wie bei Contao 4.8 sein wird.

**Comment by aschempp** [comment]
> Für mich ist das klar für den Betrieb irrelevant und kein Bug.

Ich habe leider gestern festgestellt, dass das nicht so ist. Durch die geänderte Reihenfolge hat sich auch die Reihenfolge der Generierung im Frontend verändert. Früher wurden Header-Module immer vor den Main-Modulen generiert, darauf verlässt sich z.B. Isotope. Durch die Sortierung nach Name ist das nicht mehr so bzw. sogar "zufällig" je nach Sprache.

Noch schlimmer daran ist, dass die Sortierung beim anlegen beibehalten wird! Erst nach einem erneuten Speichern der Darstellung ist die Reihenfolge in der DB alphabetisch…

**Comment by leofeyer** [comment]
See #1042
