### ISSUE TITLE
Attribut referrerpolicy bei <script>-Tags für CDN-Ressourcen

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#867]
Durch Hinzufügen des Attributs ``referrerpolicy`` mit dem Wert ``no-referrer`` im ``<script>``-Tag, könnte bei der Einbindung von JavaScript CDN-Ressourcen der Datenschutz verbessert werden, da der Referer-Header so nicht mehr an den CDN-Betreiber übermittelt wird.

**Comment by leofeyer** [comment]
Ich nehme an, dass Du Dich auf die Einbindung von MooTools und jQuery beziehst?

**Comment by leofeyer** [comment]
Grundsätzlich finde ich die Idee gut, auch wenn bisher nur [Chrome und Firefox](https://caniuse.com/#feat=mdn-html_elements_script_referrerpolicy) das `referrerpolicy`-Attribut auf dem `<script>`-Tag unterstützen.

**Comment by Mynyx** [comment]
> Ich nehme an, dass Du Dich auf die Einbindung von MooTools und jQuery beziehst?

Ja

> Grundsätzlich finde ich die Idee gut, auch wenn bisher nur [Chrome und Firefox](https://caniuse.com/#feat=mdn-html_elements_script_referrerpolicy) das `referrerpolicy`-Attribut auf dem `<script>`-Tag unterstützen.

In den anderen Browsern sollte das zusätzliche Attribut nicht schaden und zusammen mit Opera, der dieses Attribut ebenfalls unterstützt, sind je nach Statistik über 75 % Marktanteil abgedeckt (https://de.statista.com/statistik/daten/studie/13007/umfrage/marktanteile-der-browser-bei-der-internetnutzung-in-deutschland-seit-2009/).

**Comment by leofeyer** [comment]
Siehe #1052
