### ISSUE TITLE
Feature: News um Meta-Description und Meta-Titel erweitern (SEO)

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#87]
**Description**  
Ich würde gerne bei den Nachrichten den Meta-Titel und die Meta-Beschreibung selbst schreiben können.
Im Moment werden die Daten automatisch aus Titel und Teaser erstellt.

Das ist für SEO allerdings nicht immer optimal.

**Example**  
Im Grunde müsste einfach die folgende Erweiterung in den Core übernommen werden:
https://packagist.org/packages/erdmannfreunde/contao-news-meta

![meta-tags](https://user-images.githubusercontent.com/23719181/45890504-6d033800-bdc3-11e8-9242-dd81142be780.png)

Viele Grüße
Christian

**Comment by contaoacademy** [comment]
Hier noch eine weitere Extension zum gleichen Thema:
https://packagist.org/packages/srhinow/meta-4-coremodules

**Comment by leofeyer** [comment]
Siehe #161.
