### ISSUE TITLE
Unterscheidung Besucher und Mitglied im Hilfe-Assistent Seitentyp 

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#872]
Im Hilfe-Assistenten zum Feld Seitentyp werden derzeit die Begriffe Besucher (visitor) und Benutzer (user) verwendet.

Der Begriff Benutzer (user) wird jedoch zum einen auch in Fällen verwendet, wo eigentlich Besucher im Allgemeinen gemeint sind, und in den anderen Fällen wäre es sinnvoll, diesen durch den spezifischeren Begriff Mitglied (member) zu ersetzen.

Page type | Description
-- | --
Regular page | A regular page contains articles and content elements. It is the default page type.
Internal redirect | This type of page automatically forwards visitors to another page within the site structure.
External redirect | This type of page automatically redirects visitors to an external website. It works like a hyperlink.
Website root | This type of page marks the starting point of a new website within the site structure.
Logout | This type of page automatically logs out the ~~user~~ _member_.
401 Not authenticated | If a ~~user~~ _visitor_ requests a protected page without being authenticated, a 401 error page will be loaded instead.
403 Access denied | If a ~~user~~ _member_ requests a protected page without permission, a 403 error page will be loaded instead.
404 Page not found | If a ~~user~~ _visitor_ requests a non-existent page, a 404 error page will be loaded instead.

**Comment by leofeyer** [comment]
See #1054
