### ISSUE TITLE
Einstellungen "Maximale GD-Bildbreite" und "Maximale GD-Bildhöhe"

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#875]
In den Einstellungen werden die Felder "Maximale GD-Bildbreite" und "Maximale GD-Bildhöhe" angezeigt.

Soweit dies für mich nachvollziehbar ist, gelten diese Einstellungen jedoch unabhängig von der verwendeten Erweiterung, also nicht nur für GD sondern auch für Imagick und Gmagick.

**Comment by ausi** [comment]
Nein, diese Limits gelten nur für GD, nicht für Imagick oder Gmagick, siehe https://github.com/contao/contao/blob/3a48a3dd0a441342121a388f014dce66ea8c4cc0/core-bundle/src/Image/LegacyResizer.php#L121

**Comment by Mynyx** [comment]
Zum Beispiel bei dieser Funktion gelten die Limits aber unabhängig von der verwendeten Bibliothek (Zeile 443)?

https://github.com/contao/contao/blob/3a48a3dd0a441342121a388f014dce66ea8c4cc0/core-bundle/src/Resources/contao/widgets/FileTree.php#L441-L467

**Comment by leofeyer** [comment]
Sieht aus als hätten wir die `FileTree`-Klasse in contao/core-bundle#826 nicht mit aktualisiert.

@ausi Haben wir das absichtlich nicht gemacht, weil das FileTree-Widget ja deprecated ist (zugunsten des Pickers)?

**Comment by ausi** [comment]
Denke nicht, dass wir das absichtlich ausgelassen haben. Wenn es deprecated ist, ist es aber auch nicht nötig es zu aktualisieren IMO, weil es sich ja genau so verhält wie früher.

**Comment by Mynyx** [comment]
Woran ist zu erkennen, dass die ``FileTree``-Klasse deprecated ist?

**Comment by leofeyer** [comment]
Ist sie nicht. Hatte sie mit der `FileSelector`-Klasse verwechselt.

**Comment by Mynyx** [comment]
Reopen?

**Comment by leofeyer** [comment]
Nein?

> Wenn es deprecated ist, ist es aber auch nicht nötig es zu aktualisieren IMO, weil es sich ja genau so verhält wie früher.

**Comment by Mynyx** [comment]
Ich verstehe noch nicht, welche Klasse denn jetzt tatsächlich deprecated ist?

Auch in https://github.com/contao/contao/blob/3a70ea01a545d97481c3120fcd847eb878dc1ad7/core-bundle/src/Resources/contao/widgets/FileSelector.php finde ich keine Deprecation?
