### ISSUE TITLE
Hinweis auf maximale Bildbreite und -höhe bei Dateiupload

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#876]
In der Dateiverwaltung wird beim Dateiupload ein Hinweis auf die maximale Bildbreite und -höhe angezeigt:
> Wählen Sie die Dateien, die Sie auf den Server übertragen möchten (maximal 2,0 MiB und 3000x3000 Pixel).

Dabei werden jedoch fälschlich die Einstellungen ``gdMaxImgWidth`` und ``gdMaxImgHeight`` statt 
``imageWidth`` und ``imageHeight`` verwendet.

https://github.com/contao/contao/blob/4.8.4/core-bundle/src/Resources/contao/classes/DropZone.php#L78-L82

https://github.com/contao/contao/blob/4.8.4/core-bundle/src/Resources/contao/classes/FileUpload.php#L211-L215

**Comment by fritzmg** [comment]
Nein, das ist korrekt so. Die `imageWidth` bzw. `imageHeight` ist keine limitierende Einstellung für den Upload. Bilder werden nach dem Upload auf diese Größe verkleinert, daher muss man natürlich auch in der Lage sein Bilder hoch zu laden, die größer als `imageWidth` und `imageHeight` sind.
