### ISSUE TITLE
Artikel-Aliase, die nur aus Ziffern bestehen, sind nicht erlaubt?!

### ISSUE THREAD

**Issue by Samson1964** [contao/contao#88]
In der COD wird bei einem Artikel mit dem Titel "2013" automatisch ein Alias "id-2013" erstellt. In meiner 4.5.14 wird stattdessen das Alias auf "2013" gesetzt. Ich finde das Verhalten (ohne id-) normal: Es sieht schöner aus und ist wohl seit einer Version 3 mittlerweile auch erlaubt (bei Seitenaliasen). Leider meldet mein C4 und auch die COD mit Alias "2013" einen 404er. Füge ich irgendwo im Alias einen Buchstaben hinzu - egal wo, wird der Artikel gefunden. Demzufolge wird auch bei Artikeln die id-Prefix nicht mehr benötigt, denn "2013test" funktioniert ja auch.

Wurde hier vergessen die Prüfung auf "Nur Ziffern nicht erlaubt" zu deaktivieren?

**Comment by leofeyer** [comment]
Siehe https://github.com/contao/core-bundle/issues/1598.
