### ISSUE TITLE
Übersetzung "member groups"

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#889]
Die Übersetzung ``tl_module.protected.1`` sollte statt ``Das Modul nur bestimmten Gruppen anzeigen.`` vollständig ``Das Modul nur bestimmten Mitgliedergruppen anzeigen.`` heißen.

https://github.com/contao/contao/blob/cd84cd0079583c6cf965e9367a1325942abbc479/core-bundle/src/Resources/contao/languages/de/tl_module.xlf#L384-L387

**Comment by Mynyx** [comment]
https://github.com/contao/contao/blob/cd84cd0079583c6cf965e9367a1325942abbc479/core-bundle/src/Resources/contao/languages/de/tl_article.xlf#L96-L99

https://github.com/contao/contao/blob/cd84cd0079583c6cf965e9367a1325942abbc479/core-bundle/src/Resources/contao/languages/de/tl_content.xlf#L568-L571

**Comment by Mynyx** [comment]
https://github.com/contao/contao/blob/2c65d17cb60c5690d432972d9f8bcd8547e779f2/calendar-bundle/src/Resources/contao/languages/de/tl_calendar.xlf#L88-L91
https://github.com/contao/contao/blob/02bd531bd4cbc634b3b9a99a3f5824dc9422b579/news-bundle/src/Resources/contao/languages/de/tl_news_archive.xlf#L88-L91

**Comment by leofeyer** [comment]
Ich habe die deutsche Übersetzung in allen drei Versionen (4.4, 4.8 und 4.9) angepasst.
