### ISSUE TITLE
Exception wenn Gast Seitentyp Abmelden aufruft

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#890]
Wenn ein Gast eine Seite mit dem Seitentyp Abmelden aufruft, wird eine ``InvalidArgumentException: Unable to generate a logout url for an anonymous token.`` geworfen und dem Gast wird das Template ``@ContaoCore/Error/error.html.twig`` angezeigt.

Stattdessen sollte der Gast einfach weitergeleitet werden.

**Comment by asaage** [comment]
Ich bekomme dann eine 401 Seite - und das erscheint mir auch sinnvoll so.

**Comment by aschempp** [comment]
Ich denke auch dass dann eine 401-Seite kommen sollte 🤔

**Comment by leofeyer** [comment]
Ich auch. Und die 401er-Seite entscheidet dann, ob weitergeleitet wird oder nicht.

**Comment by Mynyx** [comment]
Soeben nochmals in 4.8.5 getestet, die ``InvalidArgumentException`` tritt immer noch auf.

**Comment by leofeyer** [comment]
Das scheint dann ein Problem mit Deiner Installation zu sein. Wir konnten den Fehler wie oben geschrieben nicht reproduzieren.

**Comment by fritzmg** [comment]
Reproduction:

1. Open https://demo.contao.org/contao?do=page&act=edit&id=44
2. Login as `k.jones`.
3. Confirm request token mismatch.
4. Under _Access protection_ disable __Protect page__ and then _Save_.
5. Open https://demo.contao.org/en/logout.html in the front end.

It is basically a misconfiguration.
