### ISSUE TITLE
Erklärungstext Weiterleitungsseite beim Seitentyp Abmelden

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#893]
Zum Feld ``Weiterleitungsseite`` wird beim Bearbeiten von Seiten mit dem Seitentyp Abmelden folgender Erklärungstext angezeigt:
> Bitte wählen Sie die Seite aus, zu der Besucher weitergeleitet werden. Wenn Sie keine Zielseite auswählen, wird automatisch zur ersten regulären Unterseite weitergeleitet.

Das Feld ``Weiterleitungsseite`` ist jedoch ein Pflichtfeld, sodass es nicht möglich ist, keine Zielseite auszuwählen.

**Comment by leofeyer** [comment]
Das liegt daran, dass das Feld auch noch bei anderen Seitentypen zum Einsatz kommt, bei denen es kein Pflichtfeld ist. Extra deswegen eine weitere Übersetzung anzulegen, halte ich jedoch für übertrieben.
