### ISSUE TITLE
Feld "Beschreibung der Seite" (Description) bei Fehlerseiten

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#894]
Das Feld ``Beschreibung der Seite`` (Description) ist bei Fehlerseiten (401, 403, 404) nicht sinnvoll, denn Fehlerseiten sollten von Suchmaschinen nicht indexiert werden. Daher ist das Feld bei diesen Seitentypen überflüssig.

**Comment by ausi** [comment]
Die Description wird nicht nur von Suchmaschienen ausgewertet, deshalb würde ich das Feld nicht entfernen.

**Comment by Mynyx** [comment]
Wofür wird sie denn außerdem verwendet?

**Comment by ausi** [comment]
Einige Browser nutzen sie z. B. für Bookmarks. Social-Media-Portale zeigen oft die Description wenn ein Link geteilt wird. Accessibility-Tools könnten Sie auch verwenden um eine Kurz-Beschreibung der Seite anzuzeigen.

**Comment by aschempp** [comment]
the majority of the Mumble call participants agreed that there might be a use case, and therefore there's not valid/hard reason to remove it.
