### ISSUE TITLE
Icon "Anzeigen ab/bis" in Liste Inhaltselemente

### ISSUE THREAD

**Issue by mlaubacher** [contao/contao#898]
Ein zusätzliches Icon in der Auflistung der Inhaltselemente, welches zeigt ob ein Eintrag in den Feldern "Anzeigen bis" oder "Anzeigen ab" vorhanden ist, würde es ermöglichen besser zu erkennen ob ein Element tatsächlich publiziert ist.
Mit einem zusätzlichen Icon könnte man darauf hinweisen, dass ein Element allenfalls nicht publiziert ist, obwohl das Auge grün ist.

**Comment by mlaubacher** [comment]
Falls weiterhin nur ein Icon angezeigt werden soll müsste das Auge Icon 3 Stati haben und das Verhalten könnte folgendermassen sein:
- Sobald ein Eintrag "Anzeigen bis" oder "Anzeigen von" vorhanden = Icon greyed out, da keine Aussage möglich ob publizert oder nicht
- kein Eintrag "Anzeigen bis" oder "Anzeigen von" und Status visible = Auge offen
- kein Eintrag "Anzeigen bis" oder "Anzeigen von" und Status invisible = Auge durchgestrichen

**Comment by asaage** [comment]
Der start-stop-published-icon-issue ist hier: https://github.com/contao/core-bundle/pull/940
Fakt ist, mit 3 Status am Auge wird das nichts - es dient schleißlich auch als publish-toggle.

**Comment by mlaubacher** [comment]
Danke für den Hinweis asaage! Ich werde in das obige issue schreiben und dieses schliessen.
Zu Deinem Hinweis: Ich denke das ist eines der Probleme, dass das Icon einerseits ein Status Indikator ist und gleichzeitig eine Funktion (toggle). Insbesondere da weder toggle noch status-anzeige korrekt sind (oder korrekt funktionieren) wenn start/stop-daten gesetzt sind, resp. inkonsistent sind.
