### ISSUE TITLE
Open questions regarding the Symfony integration

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#9]
Questions to discuss at the upcoming Mumble call:

- [x] How do we inject the Contao configuration?
- [x] How do we integrate the DI container?
- [x] How do we integrate the event dispatcher?
- [x] How do we minimize the number of duplicate files (see [#10-comment46790152](https://github.com/contao/contao/issues/10#issuecomment-46790152))?
- [x] Do we want the back end to go through the Symfony router?
- [x] Should we boot the kernel in `dev` mode if the Contao debug mode is enabled?

**Comment by aschempp** [comment]
The remaining tasks should be completed now so this can be closed.
