### ISSUE TITLE
Mehrfache Vergabe von Versionsnummern

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#900]
Bei der Verarbeitung von parallelen Requests, kann es zur mehrfachen Vergabe von Versionsnummern kommen.

![image](https://user-images.githubusercontent.com/1632642/67806557-67caef00-fa93-11e9-8295-9ece429024ca.png)

**Comment by aschempp** [comment]
Eine Version wovon? Ist das aus der `tl_version`?

**Comment by Mynyx** [comment]
Genau

**Comment by leofeyer** [comment]
> Bei der Verarbeitung von parallelen Requests

Wie genau hast Du das denn gemacht?

**Comment by Mynyx** [comment]
Ein Mitglied, von dem noch keine initiale Version gespeichert war, hat offenbar den "Aktivierungslink" des Moduls "Passwort vergessen" mehrfach angeklickt.
