### ISSUE TITLE
Mehrfache Datenbankabfragen für Bildgrößen im Frontend

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#901]
Wenn eine Bildgröße im Frontend bei mehreren Bildern verwendet wird, erfolgt dennoch für jedes einzelne Bild eine separate Abfrage nach den Media-Querys (``tl_image_size_item``) dieser Bildgröße.

 ``SELECT tl_image_size_item.* FROM tl_image_size_item WHERE tl_image_size_item.pid=X AND tl_image_size_item.invisible='' ORDER BY sorting ASC``

Zum Beispiel bei Seiten mit einer Galerie erfolgt dieselbe Abfrage so mitunter mehrere Dutzend Mal.

**Comment by leofeyer** [comment]
See #921
