### ISSUE TITLE
Seitencache funktioniert nicht richtig 

### ISSUE THREAD

**Issue by pressi** [contao/contao#902]
**Affected version(s)**
Contao 4.4.43

**Description**  
Der Seitencache scheint die Seiten nur pro Client zu speichern.
Beim ersten Aufrufen dauert das laden der Seite länger, beim zweiten mal schnell. Das selbe auf einem anderem Client. Es sollte ja aber schon von einem anderen Client bereit gestellt worden sein, daher schon beim ersten Aufruf schnell laden?

**How to reproduce**  
Ich habe in der Root Seite den Cache aktiviert, Browser- und Clientcache auf 3 Tage gesetzt.
Ich setzte bei einzelnen Seite die nicht gecached werden sollten beiden Zeiten auf 0. 
Es wird die Einstellung ja vererbt? 
Und kann auf einzelnen Seiten überschrieben werden?

Habe ich etwas übersehen?

**Comment by Toflar** [comment]
Kann die Seite irgendwo eingesehen werden? Ansonsten ist es für uns auf Basis dieser Informationen eigentlich unmöglich irgendwas zu tun.

**Comment by pressi** [comment]
> Kann die Seite irgendwo eingesehen werden? Ansonsten ist es für uns auf Basis dieser Informationen eigentlich unmöglich irgendwas zu tun.

Hier wäre der Link zu der Seite:
https://www.original.plus

Eine Unterseite zum Beispiel:
https://www.original.plus/startseite/unternehmen/vision.html

**Comment by Toflar** [comment]
Mir fällt spontan nichts auf, aber eben. Es kann irgendeine Extension sein, die den Cache deaktiviert etc.
Also wir können hier nicht wirklich helfen. Es müsste halt reproduzierbar sein in einer komplett neuen, leeren Contao-Installation.

**Comment by pressi** [comment]
> Mir fällt spontan nichts auf, aber eben. Es kann irgendeine Extension sein, die den Cache deaktiviert etc.
> Also wir können hier nicht wirklich helfen. Es müsste halt reproduzierbar sein in einer komplett neuen, leeren Contao-Installation.

Was mir auch gerade aufgefallen ist, kann sein das wenn man im Backend eingeloggt ist, der Seitencache auch ignoriert wird?
Als ich mich jetzt ausgeloggt habe, sah ich plötzlich eine andere Version einer Seite als die wenn ich eingeloggt bin.

**Comment by Toflar** [comment]
Ja, in allen Versionen. Sonst wäre das mit der Frontend-Vorschau bisschen schwierig ;)

**Comment by pressi** [comment]
> Ja, in allen Versionen. Sonst wäre das mit der Frontend-Vorschau bisschen schwierig ;)

OK, wie funktioniert der Cache, es werden ja pro Browser und Betriebssystem auch Klassen im Body-Tag eingefügt, wird hierfür immer eine neue "Seitenversion" erstellt?
Seiten mit einem Formular müssen vom Cache ausgeschlossen werden, da sonst eine Meldung mit "Ungültiger Anfrage-Token" erscheint?

**Comment by aschempp** [comment]
@Toflar hatte dazu einen Vortrag auf der Contao Konferenz. Sollte in Kürze auf dem YouTube Kanal veröffentlicht werden: https://www.youtube.com/user/contaocms

**Comment by Toflar** [comment]
Nein, Seiten mit einem Formular müssen nicht vom Cache ausgenommen werden. Sowohl die Tokens als auch die CSS-Klassen werden über ESI Tags gerendert.
Aber beides macht den Cache insgesamt langsamer, weshalb die Klassen in der 4.8 standardmässig weg sind und Tokens dahingehend optimiert wurden, dass sie nur noch bei eingeloggten Usern gebraucht werden (CSRF ist für normale Besucher nicht nötig).

**Comment by pressi** [comment]
@Toflar Danke für die Infos.
Wie funktioniert das mit Cookies. Kann es sein das der Cache auch wenn das Cookie auf dieser Seite nicht abgerufen wird, den Cache ignoriert, sobald ein Cookie gesetzt ist?
Ich habe jetzt in einer Kopie ein Update auf Contao 4.8. gemacht, das scheint besser zu funktionieren, aber sobald ein Cookie gesetzt ist, wird die Seite (und zwar alle Seiten) wieder langsam.

**Comment by fritzmg** [comment]
Ja, Cookies werden ja mit jedem Request automatisch mit an den Server gesendet und verhindern auch die Nutzung des Caches. Mit Ausnahme von bestimmten Cookies - diese Ausnahmen kannst du mit der `COOKIE_WHITELIST` Umgebungsvariable erweitern. Oder du aktivierst die Shared Cache Checkbox - dann kommen die Seiten _immer_ aus dem Cache. Du musst aber dann selbst dafür sorgen, dass Seiten, die Nutzerspezifische Inhalte ausgeben, vom Caching ausgenommen sind.

(@Toflar korrekt? 😁 )

**Comment by Toflar** [comment]
Nein, nicht ganz korrekt :)

Ihr müsst euch den Cache als eigene Komponente vorstellen. Er weiss nichts von Contao und kann auch auf einem anderen Server liegen. D.h. er muss zum Zeitpunkt des Requests bereits entscheiden können, ob er die Antwort aus dem Cache liefern darf oder nicht.
Leider gibt es technisch keine Möglichkeit, einem Cache dynamisch mitzuteilen, welche Cookies applikationsrelevant sind und welche nicht. D.h. wann immer ein Request mit einem Cookie daherkommt (`Cookie` Header), muss der Cache davon ausgehen, dass es sich potenziell um einen persönlichen Request (also z.B. ein eingeloggter Benutzer) handelt. Das gleiche gilt übrigens auch für den `Authorization` Header (z.B. Basic Authentication, auch bekannt als "Apache .htaccess-Schutz" :)). Er wird in diesem Fall also niemals einen Eintrag aus dem Cache ausliefern.

Leider gibt es haufenweise Cookies die nicht applikationsrelevant sind (also Contao liest sie nicht aus). Beispiele dafür sind Google Analytics Cookies, Matomo Cookies, Cloudflare etc.
Im Umkehrschluss bedeutet das, unser Cache würde quasi nie greifen, weil fast jede Seite mit irgend so einem Cookie daherkommt (GDPR sei Dank, werden es weniger).

Aus diesem Grund müssen wir dem Cache mitteilen, welche Cookies relevant sind. Wie gesagt, dynamisch/automatisch geht das nicht. Wir brauchen also eine vorkonfigurierte Liste.
Wer einen Cache wie Varnish o.ä. nutzt, weiss wie er die pflegen kann. Wer den Cache nutzt, der Contao mitliefert, kann diese Liste mittels der `COOKIE_WHITELIST` Umgebungsvariable pflegen.
Wer sich fragt warum nicht in der `config.yml` oder so: Wie gesagt, der Cache läuft ausserhalb von Contao - Contao ist noch nicht mal gestartet wenn der Cache entscheiden muss, was er ausliefern soll.

Diese Liste von Cookies definiert also quasi, welche wirklich zur Applikation (Contao) weitergereicht werden sollen und welche ignoriert werden können = sie werden vom Request gelöscht und erst dann wird geschaut ob ein Cache-Eintrag ausgeliefert werden kann. Das bedeutet, wenn kein relevantes Cookie mitgeschickt wurde, verhält sich der Cache als wäre gar keins mitgeschickt worden und kann einen Eintrag entsprechend aus dem Cache ausliefern.

Nun können wir aber nicht von all unseren Usern verlangen, dass sie wissen, welche `n` Cookies für ihre Applikation relevant sind. Wir könnten natürlich dokumentieren welche der Contao Core braucht aber man installiert sich dann mal eben 10 Erweiterungen dazu und weiss dann wieder nicht, ob diese Extensions auch Cookies brauchen und somit die Konfiguration beeinflussen. Und bevor jetzt jemand auf die glorreiche Idee kommt, dass die jeweiligen Extensions das ja dem Cache mitteilen könnten: Wie gesagt, der Cache läuft komplett ausserhalb von Contao, ggf. sogar auf einem anderen Server :)

Folglich haben wir uns überlegt, statt die Konfiguration einer Whitelist zu erzwingen, unserem Cache eine Blacklist mitzuliefern, die einfach die bekanntesten irrelevanten Cookies kennt.
Dadurch können wir dafür sorgen, dass die Cache-Hit-Rate besser wird, ohne dass sich der Otto Normalverbraucher um das Thema kümmern muss, wenn er nicht will.

Auch lesenwert ist ggf. mein Blogpost: https://contao.org/de/news/die-jagd-auf-ueberfluessige-cookies.html 

Ich hoffe das bringt ein bisschen Licht ins Dunkel. :)

PS: Es wäre schön, wenn wir ein Kapitel zu "Caching" in der neuen Anwenderdoku hätten, ich reviewe gerne. Das wäre ein schöner Weg was zurück zu geben :-)

**Comment by fritzmg** [comment]
> PS: Es wäre schön, wenn wir ein Kapitel zu "Caching" in der neuen Anwenderdoku hätten, ich reviewe gerne. Das wäre ein schöner Weg was zurück zu geben :-)

Jap, auf jeden Fall. Fehlt momentan eigentlich noch komplett (also auch die Einstellungsmöglichkeiten in der Seitenstruktur). Mach mal ein Ticket dafür ;)

**Comment by pressi** [comment]
@Toflar Danke für die Erklärung.
Ich habe mir jetzt auch den Vortrag der Contao Konferenz angeschaut, das hat schon alles Licht ins Dunkel gebracht. ;)
Danke für Eure Hilfe und Arbeit an Contao. Ich schließe somit das Ticket, da es somit kein Contao Problem ist.
