### ISSUE TITLE
Fehlende URL-Kodierung von {{file::UUID}} Inserttag

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#909]
Bei der Ausgabe des ``{{file::UUID}}`` Inserttag erfolgt keine URL-Kodierung, beispielsweise wenn der Pfad ein Leerzeichen enthält.

**Comment by aschempp** [comment]
Eine automatische URL-Kodierung kann nicht stattfinden, das System kann nicht wissen ob du das benötigst. Mit `{{file::UUID|urlencode}}` solltest du das selber machen können.

**Comment by fritzmg** [comment]
Würde nicht `urlencode` auch die slashes encoden?

**Comment by aschempp** [comment]
Möglich, dann wäre wohl eine anderes Flag richtig Aber von Beginn weg encodieren ist auf jeden Fall falsch.
https://docs.contao.org/manual/de/artikelverwaltung/insert-tags/#insert-tag-flags

**Comment by Mynyx** [comment]
> Eine automatische URL-Kodierung kann nicht stattfinden, das System kann nicht wissen ob du das benötigst. Mit `{{file::UUID|urlencode}}` solltest du das selber machen können.

Das {{file::UUID}} Inserttag wird auch vom Picker eingefügt. Es muss vorausgesetzt werden können, dass automatisch eine valide URL erzeugt wird.

**Comment by leofeyer** [comment]
Ich halte das schon für ein valides Issue. Zumindest sollten wir es mal mit den @contao/developers besprechen.

**Comment by aschempp** [comment]
Ja im TinyMCE Picker sollte ein entsprechendes Flag hinzugefügt werden. Aber der InsertTag kann auch für etwas benutzt werden dass keine Encodierung will, Output-Encoding ist immer Kontext-abhängig!

**Comment by Mynyx** [comment]
Der Picker mit Inserttag-Ausgabe wird nicht nur im TinyMCE verwendet.

Bereits vorhandene Inserttags müssten dann auch automatisch im Rahmen eines Updates angepasst werden.

**Comment by leofeyer** [comment]
Es geht ja auch nicht um Output-Encoding, sondern um URL-Encoding. Und da wäre es IMHO schon korrekt, wenn `%20` anstatt ` ` im Quelltext steht.

**Comment by ausi** [comment]
Ich denke `{{file::UUID}}` ist dafür gedacht die URL zu der Datei auszugeben (deshalb wird es auch von den Pickern verwendet) und somit sollte der Pfad auch korrekt URL-encoded werden.

**Comment by leofeyer** [comment]
@aschempp hat doch Recht damit, dass wir den Pfad nicht standardmäßig enkodieren dürfen, da man ihn sonst nicht mehr lesbar im HTML ausgeben kann. Beispiel:

```html
<figure>
    <img src="{{file::084287e8-d403-11e9-b8be-b8098abe7f19}}" alt>
    <figcaption>{{file::084287e8-d403-11e9-b8be-b8098abe7f19}}</figcaption>
</figure>
```

Die Bildunterschrift wäre dann `files%2Fpublic%2Fthis%20is%20an%20image.jpg` anstatt `files/public/this is an image.jpg` und der Anwender hätte keine Möglichkeit mehr, die Ausgabe zu korrigieren, weil es aus Sicherheitsgründen kein `rawurldecode`-Flag gibt.

**Comment by fritzmg** [comment]
Die vom URL picker zurück gegebene URL wäre dann aber nun weiterhin "falsch"?

**Comment by Toflar** [comment]
Ab der 4.8 könnten wir das theoretisch fixen. Da lässt sich der generierte InsertTag ja beeinflussen dank [meines PRs](https://github.com/contao/contao/pull/450).

**Comment by leofeyer** [comment]
Das ganze ist eh nur ein theoretisches Problem, weil der Picker ja auch so funktioniert, oder?

**Comment by fritzmg** [comment]
Es geht ja um die URL, die im Frontend generiert wird. Die hat dann bspw. spaces statt `%20`.

**Comment by leofeyer** [comment]
Die URL, die wo genau im Frontend generiert wird?

**Comment by fritzmg** [comment]
> Die URL, die wo genau im Frontend generiert wird?

![01](https://user-images.githubusercontent.com/4970961/68114210-64998e00-feed-11e9-92df-e63887fb34dc.png)

![02](https://user-images.githubusercontent.com/4970961/68114213-65322480-feed-11e9-972d-e0cdb7337e0f.png)

```html
<div class="ce_hyperlink first block">
  <a href="files/folder with spaces/file with spaces and &.jpg" class="hyperlink_txt" title="">files/folder with spaces/file with spaces and &.jpg</a>
</div>
```

**Comment by leofeyer** [comment]
Aber der Link funktioniert ja trotzdem, oder?

**Comment by fritzmg** [comment]
Ja :). Ich weiß nicht, ob es einen Browser gibt, der damit tatsächlich nicht klar kommt. Laut HTML Validator wäre es aber ein Fehler:

![htmlvalidator](https://user-images.githubusercontent.com/4970961/68115170-adeadd00-feef-11e9-863e-6d2ff5e057a1.png)

Das `&` ist dem Validator interessanterweise egal, wird aber vom Browser als Fehler markiert:

![browser](https://user-images.githubusercontent.com/4970961/68115323-120da100-fef0-11e9-8421-85e320091b46.png)

**Comment by leofeyer** [comment]
Ja, da müssten wir wohl ein `ampersand()` ergänzen. Ich schau es mir nochmal genau an.

**Comment by fritzmg** [comment]
Aber nur per flag - weil der Insert Tag könnte ja an Stellen eingesetzt werden, wo keine HTML entities sein können/dürfen.

**Comment by ausi** [comment]
Wer nutzt `{{file::UUID}}` als Bildunterschrift? IMO sollte es im Standardfall eine valide URL sein.

Wie wäre es mit weiteren Optionen?

|                             |                        |
|-----------------------------|------------------------|
| {{file::UUID}}              | folder/file%20name.jpg |
| {{file::UUID:url}}          | folder/file%20name.jpg |
| {{file::UUID:path}}         | folder/file name.jpg   |
| {{file::UUID:name}}         | file name.jpg          |
| {{file::UUID:meta:caption}} | Caption Text           |

Oder wäre die korrekte schreibweise `{{file_url::}}`, `{{file_path::}}` usw?

So könnte man jedenfalls andere Use-Cases abdecken und `{{file::UUID}}` selbst beheben damit immer eine valide URL dabei rauskommt.

**Comment by leofeyer** [comment]
Vermutlich eher `file_url::UUID` als `file::UUID:url`. Aber wir können den Standardfall nicht ohne BC-Break ändern.

**Comment by ausi** [comment]
> Aber wir können den Standardfall nicht ohne BC-Break ändern.

Ich denke dass jemand `{{file::UUID}}` nicht als URL eingesetzt hat ist äußerst selten. Wenn jemand den Insert-Tag tatsächlich als Text verwendet, wäre der BC-Break kein großes Problem denke ich da der Text ja weiterhin lesbar bleibt.

**Comment by Toflar** [comment]
Ich bin auch der Meinung, dass der Standardfall wohl encoded sein sollte.

**Comment by leofeyer** [comment]
Wie am 28. November auf Mumble besprochen, soll die Ausgabe standardmäßig URL-kodiert werden (`System::urlEncode()`).

**Comment by leofeyer** [comment]
Siehe #1268.
