### ISSUE TITLE
Do not list frontend user without login permissions in maintenance dropdown

### ISSUE THREAD

**Issue by Sioweb** [contao/contao#91]
**Affected version(s)** 4.6

**Description** 

Users without "Allow login" option are also listet in maintenance backend. This causes error; User can not be validatet

**How to reproduce**  

- Create new user without Login
- Open maintenance
- build searchindex with this user
- Error

**Comment by leofeyer** [comment]
Changed in 1b3541166565f85797a46d51818da1000345461f.
