### ISSUE TITLE
Darstellungsfehler in Bearbeitungsansicht der Dateiverwaltung

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#910]
In der Dateiverwaltung tritt beim Bearbeiten von Dateien ein Darstellungsfehler auf, wenn die Hauptspalte mindestens so lang ist wie das Menü (beispielsweise durch Metadaten für verschiedene Sprachen). Es wird dann ein grauer Bereich unterhalb des ``div#container``-Elements angezeigt.

![image](https://user-images.githubusercontent.com/1632642/67892183-72998880-fb54-11e9-95af-fbe9f4e586c3.png)

**Comment by leofeyer** [comment]
Welche Contao-Version betrifft das?

**Comment by Mynyx** [comment]
4.8.4

**Comment by leofeyer** [comment]
@ausi Any idea how to fix this?

**Comment by ausi** [comment]
The `<div class="chzn-drop">` causes this margin at the bottom of the page.

We should problably set `top` to `-9000` in [chosen.js:83](https://github.com/contao-components/chosen/blob/637bd469f4230fc63c4cc594478a7515bdd9fa35/js/chosen.js#L83), [chosen.js:87](https://github.com/contao-components/chosen/blob/637bd469f4230fc63c4cc594478a7515bdd9fa35/js/chosen.js#L87) and [chosen.js:435](https://github.com/contao-components/chosen/blob/637bd469f4230fc63c4cc594478a7515bdd9fa35/js/chosen.js#L435) in addition to `left`.

**Comment by leofeyer** [comment]
Unfortunately, this breaks the "scroll into view" functionality in [chosen.js:373](https://github.com/contao-components/chosen/blob/637bd469f4230fc63c4cc594478a7515bdd9fa35/js/chosen.js#L373-L377), causing some weird page jumps. Any other ideas?

**Comment by ausi** [comment]
Setting `overflow: hidden` for the `chzn-container` when it is closed (and resetting it when opened) should work too I think.

**Comment by leofeyer** [comment]
That works. 👍 It is a little "jumpy", but I think we can live with that, can't we?

![](https://user-images.githubusercontent.com/1192057/69713351-abe9f780-1104-11ea-89d9-87b080a2b7dc.gif)

**Comment by leofeyer** [comment]
Fixed in contao-components/chosen@7f03cea8db23d0a3990fde33d58ab66ef649c302
