### ISSUE TITLE
Welche Templates werden genutzt?

### ISSUE THREAD

**Issue by marcfunkitug** [contao/contao#912]
Es wäre schön, wenn bei dem Bereich Templates angezeigt wird, ob das jeweilige Template irgendwo aktiv genutzt wird.

Wenn wir z. B. eine Webseite relaunchen und im Vorfeld viele Templates verwendet haben und mit dem Relaunch neue Templates nutzen, verliert man leider schnell die Übersicht, welche Templates alt sind und ggf. gelöscht werden können und welche in Verwendung sind.

Anzeigemöglichkeit: Icon am Ende der Zeile, welches zeigt, ob das Template aktiv genutzt wird oder nicht.

**Comment by Toflar** [comment]
Das funktioniert nicht zuverlässig, denn wir könenn nicht wissen, wo sie genutzt werden. Genauso wie es auch bei Modulen, Dateien etc. nicht funktioniert.
Ich könnte bspw. in `mod_foobar.html5` ein `<?php $this->insert('mod_foobar2', $data) ?>` haben. Sprich `mod_foobar2.html5` wird benötigt, aber niemand weiss davon.
Man kann natürlich versuchen die Infos wegzuspeichern und zu synchronisieren aber es wird niemals eine zuverlässige Info sein und dann ist sie m.M.n. unbrauchbar.
