### ISSUE TITLE
Fix a typo in the German translation

### ISSUE THREAD

**Issue by xchs** [contao/contao#914]
**Affected version(s)**

Contao 4.4 & 4.8

**Description** 

There is a tiny typo in the German translation string (two space characters after the word "_Artikel_"):
https://github.com/contao/contao/blob/2d5832fa11753aea0b0511721c35a88f83d17502/core-bundle/src/Resources/contao/languages/de/tl_article.xlf#L98

Once you have time, maybe you can change that on Transifex.

**Comment by leofeyer** [comment]
Done.
