### ISSUE TITLE
Von der Synchronisation ausgenommene Ordner und Dateien in FileTree-Widget auswählbar

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#919]
Im ``FileTree``-Widget sind auch von der Synchronisation ausgenommene Ordner und Dateien auswählbar.

Nach Klick auf den Button ``Anwenden`` geht die Auswahl verloren.

**Comment by leofeyer** [comment]
The FileTree widget is deprecated. You should use the DCA picker instead. (And we should probably trigger an exception warning.)

**Comment by Mynyx** [comment]
Isn't it a bug?

The widget is used by Contao 4.4 and 4.8.

**Comment by leofeyer** [comment]
Where exactly is the widget used in Contao 4.8?

**Comment by Mynyx** [comment]
https://github.com/contao/contao/search?q=inputType+fileTree&unscoped_q=inputType+fileTree shows several DCA files?

**Comment by aschempp** [comment]
`FileTree` is not deprecated at all, that's what's used to pick a file. The `dcaPicker` is only for text fields with picker option. Also, the same issue will likely happen on the `dcaPicker`, as the picked element does not have a UUID in the database.

**Comment by leofeyer** [comment]
I know. I have confused it with the `FileSelector` class.

**Comment by bennyborn** [comment]
Any update on this? We've just run into the same problem.
@leofeyer Also, please make sure that the issues for milestone 4.4 are transferred to 4.9 ;)

**Comment by leofeyer** [comment]
@contao/developers How would you prefer to fix this?

1. Hide unsynced folders completely
2. Show unsynced folders but disable the checkbox

No. 1 is cleaner but does not allow to edit an unsynced folder (e.g. to make it a synced folder). No. 2 allows for that but it also clutters the folder list with a lot of disabled choices.
