### ISSUE TITLE
{{link_open::*}} zeigt bei ungültiger Id nichts an

### ISSUE THREAD

**Issue by bekanntmacher** [contao/contao#92]
Wenn die Page Id ungültig ist, zeigt `{{link_open}}` nichts an, was dann im Zusammenhang mit `{{link_close}}` zum Problem führt, sprich invalides HTML erzeugt, Bsp.:

`<div class="button">Hallo</a></div>`

Besser wäre, wenn die URL einfach leer gelassen würde:

`<div class="button"><a href="">Hallo</a></div>`

**Comment by leofeyer** [comment]
Behoben in 4c6c56bee56e083ba2fe2940bab420cab94609a6.
