### ISSUE TITLE
Gespeicherte Bildgröße wird gelöscht, wenn bearbeitender Benutzer keine Berechtigung für diese hat

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#920]
Wenn ein regulärer Benutzer ein Element bearbeitet, das ein ``ImageSize``-Widget enthält (beispielsweise ein Inhaltselement mit dem Typ Galerie), bei dem von einem anderen Benutzer bereits eine Bildgröße gespeichert wurde, und der bearbeitende Benutzer keine Berechtigung für die gespeicherte Bildgröße hat, dann wird die gespeicherte Bildgröße gelöscht, wenn der bearbeitende Nutzer das Element speichert.

**Comment by leofeyer** [comment]
Es macht ja auch keinen Sinn, einem Redakteur Zugriff auf ein Inhaltselement zu geben, in dem eine Bildgröße verwendet wird, auf die er/sie keinen Zugriff hat, oder?

**Comment by Mynyx** [comment]
Die Zugriffsrechte können ja nicht auf Ebene der Inhaltselemente konfiguriert werden, sondern nur auf Artikelebene?

Und es dürfte bei umfangreicheren Projekten auch schwerfallen, vollständig den Überblick zu behalten, wo welche Bildgröße verwendet wurde.

Das Risiko, dass eine Bildgröße versehentlich gelöscht wird, ist so kaum zu eliminieren. Grundsätzlich sollte beim Speichern eines Elements meiner Auffassung nach keine Änderung ohne Zutun des Benutzers erfolgen.

**Comment by aschempp** [comment]
> Die Zugriffsrechte können ja nicht auf Ebene der Inhaltselemente konfiguriert werden, sondern nur auf Artikelebene?

Mit `ce-access` oder Contao 4.9 ist das möglich. Ausserdem kann man dem Redakteur auch das entsprechende Feld wegnehmen.

Ich verstehe das Problem schon, aber ich denke nicht dass das System eine falsche Konfiguration für dich *korrigieren* kann…

**Comment by Mynyx** [comment]
Bei Wegnahme des Feldes könnten Redakteure aber gar keine Bilder mehr bearbeiten. 

Es ist darüber hinaus ja auch nicht so einfach ersichtlich, wo das Problem herrührt, wenn zunächst mal nur festgestellt wird, dass Bildgrößeneinstellungen verloren gehen. Bis das Problem debuggt ist und herausgefunden ist, dass es an den Berechtigungen liegt, muss für die Fehlersuche erstmal einige Arbeitszeit aufgewendet werden.

Unabhängig von der Frage, wie realistisch es ist, dieses Szenario durch die Konfiguration zu verhindern, bleibt auch der Punkt bestehen, dass beim Speichern eines Elements eine unkontrollierte Änderung eintritt, obwohl der Benutzer selbst gar keine Änderung vorgenommen hat. Das sollte grundsätzlich nicht passieren.

**Comment by leofeyer** [comment]
Wie am 27. August auf Mumble besprochen, sollte in diesem Fall der aktuelle Wert als unbekannte Option zum Select-Menü hinzugefügt werden, damit dieser beim Speichern erhalten bleibt.
