### ISSUE TITLE
Unpublished Content-elements are visible after frontend-preview

### ISSUE THREAD

**Issue by akroii** [contao/contao#922]
**Affected version(s)**
Contao 4.4.42
Contao 4.8.4

**Description**  
Unpublished Content-elements are visible after frontend-preview.

**How to reproduce**  
I have an article wich is being disabled. In this article there's a content-element `image` which is enabled. When I switch to preview mode and activate option `show hidden elements` now everything is visible as aspected. But after I quit the preview mode the disabled article is still visible. Even I reload page and clear http_cache, because I have to delete my cookies.

Step 1: Unpublished article and visible content-element
![Bildschirmfoto 2019-11-04 um 11 05 11](https://user-images.githubusercontent.com/8830861/68112997-0079c880-fef3-11e9-8478-1f6bd6e75eda.png)

Content element "image":
![Bildschirmfoto 2019-11-04 um 11 06 02](https://user-images.githubusercontent.com/8830861/68113049-1d160080-fef3-11e9-9645-b3c3c17c5a60.png)

Step 2: Turn on preview mode and make everything visible.
![Bildschirmfoto 2019-11-04 um 11 06 34](https://user-images.githubusercontent.com/8830861/68113087-35861b00-fef3-11e9-8b4c-a92ce39a6783.png)

Step 3: Quit exit mode.
Result: Everything is still visible on the hole website.

Step 4: Clear contao http_cache.
Nothing changes

Step 5: Clear cookies. Everything is fine. Unpublished article is disabled and not visible anymore.

**Comment by fritzmg** [comment]
This is normal. Your setting is saved until your session expires.

**Comment by akroii** [comment]
Even I quit the preview mode?
![Bildschirmfoto 2019-11-04 um 11 20 06](https://user-images.githubusercontent.com/8830861/68113909-1be5d300-fef5-11e9-9680-52b289a99fd2.png)
My editors are confused, because the quitted the preview mode :)

**Comment by fritzmg** [comment]
Yes, even if you quit the preview mode.

**Comment by leofeyer** [comment]
That is because closing the preview bar is not "quitting the preview mode". You are just removing the preview bar.

To quit the preview mode, you have to set "unpublished elements" to "hide" and click "Apply".
