### ISSUE TITLE
PHP 7.2+ for Contao 4.9

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#923]
Unfortunately, MySQL has decided to make `member` a reserved keyword in version 8.0.17, which required bug fixes in Contao and Doctrine DBAL. Also unfortunately, Doctrine has decided to fix this only in [version 2.10](https://github.com/doctrine/dbal/releases/tag/v2.10.0), which requires at least PHP 7.2.

This means for us that people cannot use Contao with MySQL 8.0.17+ and PHP <7.2.

Now with regard to Contao 4.9, we are thinking about making PHP 7.2 the minimum PHP version. This would imply that Contao 4.9 is not compatible with PHP 7.1 (which reaches its EOL in a couple of days) but in return is compatible with all MySQL versions.

Are there any objections besides "my hosting company does not offer PHP 7.2"?

**Comment by fritzmg** [comment]
No objections from me :)

Btw. Contao 4.4 technically supports PHP 5.6 - however you cannot use the following combination either:

* Contao 4.4
* PHP 5.6
* MySQL 8.0

**Comment by leofeyer** [comment]
I know. We could continue to support PHP 7.1, but contrary to PHP 5.6, which is the last version of PHP 5, PHP 7.1 is just a regular minor version of PHP 7 with no particular significance.

**Comment by Toflar** [comment]
I'm clearly in favor of raising the minimum required PHP version to 7.2.
PHP 7.1 is [EOL in 26 days](https://www.php.net/supported-versions.php) which means you should stop using it asap anyway.
Doctrine is one of our main dependencies and I feel like it's easier to communicate that we just require PHP 7.2 instead of something like "depending on your platform you may or may not use Contao 4.9 with MySQL 8".

**Comment by leofeyer** [comment]
Another argument in favor of dropping PHP 7.1: We could then use [pcov](https://github.com/krakjoe/pcov) to generate the code coverage reports, which is supported in PHPUnit 8.

See https://kizu514.com/blog/pcov-is-better-than-phpdbg-and-xdebug-for-code-coverage/

**Comment by aschempp** [comment]
I'm conflicted between *technically "correct"* and *useful*. Here's my thoughts:
If we increase the PHP version, we lower the adoption of Contao 4.9. People that won't use it are the ones where PHP 7.2/7.3 is not available yet. It is very unlikely these hosters are running outdated PHP versions, but are using the latest MySQL.
So essentially, any provider with MySQL 8 will most likely offer PHP 7.2/7.3, so our users really shouldn't have any issues, regardless of PHP 7.1 support.

If I correctly recall our developer meeting, we discussed to keep PHP 7.1, same as we kept PHP 5.6 for Contao 4.4. We decided to raise to PHP 7.3 for Contao 4.10, so we have an LTS that still runs on "older" stuff.

**Comment by Toflar** [comment]
> If I correctly recall our developer meeting, we discussed to keep PHP 7.1, same as we kept PHP 5.6 for Contao 4.4. We decided to raise to PHP 7.3 for Contao 4.10, so we have an LTS that still runs on "older" stuff.

That was before DBAL raised their minimum required version. We have a new situation here.
Whatever we discussed then is irrelevant now.

**Comment by m-vo** [comment]
I see MySQL 8 popping up everywhere now. Imo **not** raising the requirement and (therefore not supporting it in the upcoming LTS) would be the bigger problem.

**Comment by ausi** [comment]
> If I correctly recall our developer meeting, we discussed to keep PHP 7.1,

I think we also agreed that if there is a good reason or a feature that we need we would increase it to 7.2. And we have a good reason now I think.

**Comment by aschempp** [comment]
Having 7.1 for the LTS and switching to 7.3 for the next minor seemed "more important" to me. But it won't make a real difference anyway :D

**Comment by leofeyer** [comment]
Ok, the number of upvotes is pretty clear. 😄 See #943.
