### ISSUE TITLE
Rundungsfehler für Important Part bei Bildern nach Update von 4.7 auf 4.8

### ISSUE THREAD

**Issue by frontendschlampe** [contao/contao#927]
**Affected version(s)**
Update von 4.7 auf 4.8

**Description**  
Nach dem Update erhalte ich im Systemlog diverse Fehlermeldungen folgender Art:
```html
Invalid important part x=0.00117647058824, y=0.506172839506, width=0.998823529412, height=0.479717813051 for image "/www/htdocs/XXX/www.XXX.de/files/mein-bild.jpg".
```

**How to reproduce**  
Ich kann es nicht genau reproduzieren, aber lt. Slack-Thread mit @ausi sind wir zum Entschluss eines Rundungsfehlers gekommen. In der Datenbank mit 4.7 stehen folgende Werte beim Bild mit der Größe 850 x 567px:

```html
importantPartX = 1
importantPartY = 287
importantPartWidth = 849
importantPartHeight = 272
```

nach dem Update stehen dann folgende Werte in der DB:

```html
importantPartX = 0.00117647058824
importantPartY = 0.506172839506
importantPartWidth = 0.998823529412
importantPartHeight = 0.479717813051
```

Wenn man jetzt `importantPartX = 0.00117647058824` und `importantPartWidth = 0.998823529412` zusammenrechnet, kommt man auf `1.0000000000002`

**Comment by ausi** [comment]
It looks like PHP/Doctrine/PDO transfers float values as strings to the database and loses a huge amount of its precision this way.

_849 / 850_ gives _0.9988235294117647058823529411764705..._ but gets stored as `0.998823529412` even though MySQL could store four digits more. And _1 / 850_ gives _0.0011764705882352941176470588235294..._ but gets stored as `0.00117647058824`.

So this is probably not an issue with the update routine but a rounding issue we should account for in the contao/image library itself I think.

See contao/image#60

**Comment by ausi** [comment]
The backwards compatibility code needs to be updated too, see #935

**Comment by m-vo** [comment]
Are you sure that the errors you're seeing aren't due to the fact that floats are typically stored in IEE754 format (base+precision+exponent) instead of a list of single digits?

**Comment by ausi** [comment]
Yes, with the transfer to the database more precision is lost. In PHP alone `(849 / 850) + (1 / 850) === 1.0` is true.

But maybe this issue could appear without the database too in some edge-cases. That’s why I think we should not try to fix the database migration but allow a small error in the ImportantPart to fix it for all cases.

**Comment by m-vo** [comment]
I'm not sure how PHP stores those values internally or if there is already optimization magic going on. 

I meant: The IEE754 binary representation of 0.9988235 is `00111111011111111011001011100110` which is the exact same as the one for 0.9988235294117647058823529411764705 (example for 32 bit). The induced error isn't stable - it depends on the actual number ([Playground](https://www.h-schmidt.net/FloatConverter/IEEE754.html)). So I'd say this is expected for a float datatype even though the problem isn't leaking in this example. :smiley: 

Note that different architectures running the code might produce subtle differences. See https://www.php.net/manual/en/language.types.float.php

**Comment by ausi** [comment]
<https://www.php.net/manual/en/language.types.float.php>
> Although it depends on the system, PHP typically uses the IEEE 754 double precision format

Double precision would be something like `0.9988235294117647`. Both PHP and MySQL can handle this value in my tests.

But again, no matter where the rounding issues come from, my fix should fix them all, don’t you think?

**Comment by m-vo** [comment]
Sure, for the detection in the core. The `ImportantPart` could imo as well simply constrain the values without checking) for not having to specify a precision margin). But that's an API design decision.

**Comment by leofeyer** [comment]
See #935
