### ISSUE TITLE
Reihenfolge der Spalten bei "Eingebundene Module" nicht individuell sortierbar

### ISSUE THREAD

**Issue by zonky2** [contao/contao#928]
**Affected version(s)**
Contao 4.4.44

Die Zeilen sortieren sich mit Fußzeile als ersten Block usw. - siehe Screenshot
https://easycaptures.com/fs/uploaded/1408/5048176431.png

In aktueller Demo 4.8.4 wird Fußzeile an das Ende sortiert - offensichtlich werden die Zeilen Blockweise (Kopfzeile, Linke Spalte, Hauptspalte, Fußzeile, ...) sortiert - oder?

**Comment by xchs** [comment]
Duplicate of https://github.com/contao/contao/issues/861

**Comment by zonky2** [comment]
o.k. - dann habe ich nicht lange genug gesucht :(
