### ISSUE TITLE
Filesystem tools may access invalid paths during initializeSystemHook

### ISSUE THREAD

**Issue by m-vo** [contao/contao#929]
**Affected version(s)**
4.4 / 4.8

**Description**  
Using `File->write()` during the `initializeSystem` hook can fail because the [`tmp` subdirectory](https://github.com/contao/contao/blob/2d5832fa11753aea0b0511721c35a88f83d17502/core-bundle/src/Resources/contao/library/Contao/File.php#L844) inside `/system` might not yet exist. 

Effectively this leads to an error in [madeyourday/contao-rocksolid-custom-elements](https://github.com/madeyourday/contao-rocksolid-custom-elements/issues/114) during installation.

**Fix**
We should probably check the path before writing.

**Comment by aschempp** [comment]
Shouldn't `File->write()` create directories as necessary?

**Comment by m-vo** [comment]
It should I guess. But [currently](https://github.com/contao/contao/blob/2d5832fa11753aea0b0511721c35a88f83d17502/core-bundle/src/Resources/contao/library/Contao/File.php#L853) it simply calls  `Files->fopen()` which then fails.

**Comment by fritzmg** [comment]
May be related: https://github.com/contao/core-bundle/issues/1177

**Comment by leofeyer** [comment]
This is what @ausi said in https://github.com/madeyourday/contao-rocksolid-custom-elements/issues/114#issuecomment-549073241:

> Using the filesystem tools should be OK in an `initializeSystem` hook IMO.

I am not sure if I agree, as I am not sure whether we can assume a running system during system initialization?

**Comment by leofeyer** [comment]
As discussed in Mumble on November 28th, @m-vo needs to debug this more detailed, as the install command does not boot the Contao framework.

**Comment by rabauss** [comment]
I have also investigated this problem, too. The `system/tmp` folder does not exist if the hook `initializeSystem` is used by RocksolidCustomElements.

That's like @ m-vo said, because of:
> It should I guess. But [currently](https://github.com/contao/contao/blob/2d5832fa11753aea0b0511721c35a88f83d17502/core-bundle/src/Resources/contao/library/Contao/File.php#L853) it simply calls `Files->fopen()` which then fails.

There are two possible solutions:

1. Create `system/tmp` if it not exists in `File->fputs`
2. Execute the Hook `initializeSystem` after `system/tmp` should be created

**Comment by leofeyer** [comment]
As discussed in Mumble on April, 9th, we want to adjust the `triggerInitializeSystemHook()` method:

```php
private function triggerInitializeSystemHook(): void
{
    if (empty($GLOBALS['TL_HOOKS']['initializeSystem']) || !is_dir($this->rootDir.'/system/tmp')) {
        return;
    }

    foreach ($GLOBALS['TL_HOOKS']['initializeSystem'] as $callback) {
        System::importStatic($callback[0])->{$callback[1]}();
    }

    if (file_exists($this->rootDir.'/system/config/initconfig.php')) {
        @trigger_error('Using the "initconfig.php" file has been deprecated and will no longer work in Contao 5.0.', E_USER_DEPRECATED);
        include $this->rootDir.'/system/config/initconfig.php';
    }
}
```
