### ISSUE TITLE
Schloss-Icon für nicht öffentliche Dateien

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#930]
In der Dateiverwaltung werden nicht öffentliche Ordner mit einem Schloss-Icon gekennzeichnet. Bei den Dateien, die sich unmittelbar in ``files/`` und nicht in einem Unterordner befinden, ist jedoch nicht erkennbar, dass diese nicht öffentlich sind.

Es wäre daher sinnvoll, das Schloss-Icon auch bei nicht öffentlichen Dateien und nicht nur bei nicht öffentlichen Ordnern anzuzeigen. Darüber hinaus würde dies die Usability insbesondere im Picker verbessern, da der Veröffentlichungsstatus so unmittelbar, ohne Blick auf den Ordner, ersichtlich wäre.

**Comment by leofeyer** [comment]
Siehe https://github.com/contao/contao/pull/168.
