### ISSUE TITLE
Berechtigungen in der Dateiverwaltung

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#931]
In der Dateiverwaltung fehlt eine Möglichkeit, um Benutzerberechtigungen für einzelne Felder zu konfigurieren (insbesondere ``Name``, ``Öffentlich``, ``Nicht synchronisieren`` und ``Metadaten``).

Ein Risiko besteht beispielsweise darin, dass ein Benutzer mit dem Recht ``Dateien und Verzeichnisse bearbeiten, kopieren und verschieben`` bei einem Ordner  ``Nicht synchronisieren`` auswählt, denn dann werden bei der nächsten Synchronisation sämtliche Metadaten der enthaltenen Dateien ohne Vorwarnung unwiderruflich gelöscht.

**Comment by leofeyer** [comment]
See #3103
