### ISSUE TITLE
Abgleich BE-Bezeichnung und Handbuch

### ISSUE THREAD

**Issue by zonky2** [contao/contao#936]
wie in
in https://docs.contao.org/manual/de/theme-manager/seitenlayouts-verwalten/#frontend-module
zu sehen, gibt es für die als "Layoutbereiche" bezeichneten Elemente die Spaltenüberschrift "Spalte" - obwohl es dann z.B. "Kopfzeile" oder "Fußzeile" heißt.

M.E. wäre eine Umbenennung in der Tabelle in "Layoutbereich" selbsterklärender.

**Comment by fritzmg** [comment]
Müsste aber auch andernorts geändert werden - also bspw. bei der "Spaltenauswahl" in den Artikeleinstellungen.

**Comment by leofeyer** [comment]
See #1150
