### ISSUE TITLE
Kein individuelles Template bei "Mehrere bearbeiten > Mehrere überschreiben"

### ISSUE THREAD

**Issue by exscorp** [contao/contao#938]
**Affected version(s)**
4.8.x
##
**Description**  
Ich hatte gerade den Fall das in einem Artikel 12 ce_text Elemente ein anderes Template bekommen sollten. Wollte Mehrere bearbeiten > Überschreiben und das neue Template zuweisen, die Liste ist aber leer. Wenn ich die Elemente einzeln bearbeite, dann wird das neue Template angezeigt.

Durch die Templateauswahländerung in 4.8 kann man bei **Mehrere bearbeiten** > **Mehrere überschreiben** kein individuelles Template mehr auswählen, die Liste ist leer.

Dies tritt überall auf wo man ein **Individuelles Template** auswählen kann (Inhaltselemente, Frontend-Module).

< 4.8 wurden ja alle Templates angezeigt, dies sollte auch in diesem Fall (Mehrere bearbeiten) sein, sonst macht die Funktion **Mehrere bearbeiten** > **Mehrere überschreiben** keinen sinn.
##
**How to reproduce**  

- ein Artikel mit mehreren (gleichen) Inhaltselementen auswählen
- auf **Mehrere bearbeiten** klicken
- Inhaltselemente auswählen
- auf **Überschreiben** klicken
- **Individuelles Template [customTpl]** auswählen
- Individuelles Template Auswahlliste ist leer

**Comment by leofeyer** [comment]
Siehe #1007
