### ISSUE TITLE
Remove mandatory-flag from source files when option "use home directory" is selected

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#94]
**Affected version(s)**
Contao 3.5, Contao 4.x

**Description**  
If I set the option "use home directory" for the elements downloads or gallery, I also have to choose a source file. In my opinion this is not necessary, because the source files would be generated automatically. 

Is it possible to remove the "mandatory-flag", if the option "use home directory" is set?
Or does contao need this as fallback?

![use home directory](https://user-images.githubusercontent.com/23719181/46010039-9c66bd00-c0c1-11e8-8579-9a1fe1adc86b.jpg)

**Comment by fritzmg** [comment]
The mandatory flag shouldn't be necessary. If no files or folders have been selected and no user home directory is available, then the element simply should not render.

**Comment by leofeyer** [comment]
What if a user does not have a home directory?

**Comment by fritzmg** [comment]
If the user does not have a home directory and no source files or folders were selected, the content element should simply
```php
return '';
```
imho.

**Comment by leofeyer** [comment]
Fixed in 90b992f0959ab7873b904c2ef5b3e9fbd888e66f.
