### ISSUE TITLE
sitemap.xml is generated with /preview.php/ URLs

### ISSUE THREAD

**Issue by m-knorr** [contao/contao#942]
We currently have the problem, that sometimes the sitemap.xml is generated with preview.php URLs.

Regular site count is at about 256 pages, and we get errors in our SEO tool and from the Google Search Console as well, that ~250 pages of ~500 pages are redirects with "noindex".

So every page is in the list twice.

Is it possible that the sitemap is created depending on the user that is logged in?

Current Contao version is 4.8.4.

**Comment by leofeyer** [comment]
See #1008
