### ISSUE TITLE
contao.cache.clear_internal and contao.cache.warm_internal need to be public

### ISSUE THREAD

**Issue by m-vo** [contao/contao#949]
**Affected version(s)**
all that work with Symfony>=4.0

**Description**  
`contao.cache.clear_internal` and `contao.cache.warm_internal` are used directly via `$container->get()` (in `Contao\Automator`) but both aren't public. Using the automator command to purge/generate the internal cache therefore fails.

**How to reproduce**  
```
$ contao-console contao:auto purgeInternalCache
The "contao.cache.clear_internal" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. (see help contao:automator).
```

```
$ contao-console contao:auto generateInternalCache
The "contao.cache.warm_internal" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. (see help contao:automator).
```

**Comment by leofeyer** [comment]
@contao/developers IMHO we should remove the method body of the `purgeInternalCache()` and `generateInternalCache()` methods and trigger a deprecations notice instead. The internal cache can only be purged/built by purging/building the Symfony cache. Any objections?

**Comment by m-vo** [comment]
Fun fact: I only stumbled across this because I entered the wrong number (`contao:automator`). 😄

**Comment by leofeyer** [comment]
See #1009.

> IMHO we should remove the method body of the methods and trigger a deprecations notice instead

While changing this, I realized that the two methods do not rebuild the entire cache but only the `/contao` subfolder. I have therefore left the methods as is and made the cache services public instead.

**Comment by ReneLuecking** [comment]
Is there any reason why this got fixed in 4.8 but not in >=4.9?

**Comment by leofeyer** [comment]
Hm, I don't know. @contao/developers Did we intentionally not merge the changes upstream?

**Comment by fritzmg** [comment]
At least I don't remember any discussion about it. I think it might simply be an oversight. After all, the Automator is still accessing these services from the container and thus they definitely need to be public, do they not?

**Comment by leofeyer** [comment]
Strange enough, the unit tests actually ensures that the service is public. 🤔 

https://github.com/contao/contao/blob/c219abba6768a6110d402dad4761f67fc9b7acc0/core-bundle/tests/DependencyInjection/ContaoCoreExtensionTest.php#L1235-L1238

**Comment by m-vo** [comment]
Are we testing the wrong thing there? All services are reported as  `public` at that stage...

**Comment by leofeyer** [comment]
That is true, unfortunately, because service definitions are both public and private by default in Symfony 4.4. 🤦🏻‍♂️ 

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/DependencyInjection/Definition.php#L37-L38
