### ISSUE TITLE
Shared Cache doesn't automatically renew if CSS/JS Scriptcache ist changed

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#950]
**Affected version(s)**
4.8
**Description**  
The CSS/JS Script Cache is broken, when I use the Shared Cache and make some changes on the Scripts. Then the scripts could not be loaded on the page. The only solution is to clear the symfony cache in the Contao Manager, clearing the shared cache in maintenance module doesn't helps.
**How to reproduce**  
1. Use Shared Cache Setting
2. Make some changes in the CSS or JS Scripts
3. Clear the Scriptcache

**Comment by leofeyer** [comment]
Please provide more detailed information.

**Comment by theDyingMountain** [comment]
At the moment, I can't reproduce this, but this problem occurred on 2 Contao installations on different servers. I will continue to look for this behavior in future projects.

**Comment by leofeyer** [comment]
Ok. I am closing the issue then. Feel free to reopen it when you have new information.

**Comment by theDyingMountain** [comment]
Unfortunately I'm not allowed to reopen the issue. My colleague was able to reproduce the behaviour. Here are the steps (in german):

1. Private Browser Fenster mit der Seite öffnen (so lange neu laden bis Cache: fresh)
2. Im normalen Fenster einloggen und CSS ändern
3. Frontend neu laden -> CSS Änderung wird angezeigt
4. Private Fenster neu laden -> CSS Änderung wird nicht angezeigt (da noch Cache Version)
5. Backend -> Shared Cache löschen
6. Private Fenster neu laden -> CSS Datei Error 404
7. Backend -> Skriptcache löschen + Shared Cache löschen
8. Private Fenster neu laden -> keine Veränderung
9. Manager -> Symfony Cache löschen
10. Private Fenster neu laden -> funktioniert wieder

**Comment by MarkejN** [comment]
The problem might be a bug inside Maintenance > Purge the shared cache. This doesn't seem to actually purge the cache. Contao-Cache always stays on "fresh" even after clicking it. I tested this in a fresh Contao 4.8.7 instance.

If I understand correctly, changing CSS results in new paths to the assets folder. It is then necessary to purge the shared cache, because it now contains paths that are no longer valid. Pressing the "purge the shared cache" didn't help as described in this issue. But clearing the symfony cache does the job (profile > purge data > shared cache: works too). So the problem could be only the checkbox inside Maintenance.

**Comment by Toflar** [comment]
The problem is that clearing the shared cache does not work. But this is not a problem of Contao, it's a problem of multiple dependencies. Working on it.

**Comment by Toflar** [comment]
Needed adjustments in my store implementation and still needs adjustments in the FOS HttpCache.
See the PR for more details: https://github.com/FriendsOfSymfony/FOSHttpCache/pull/475
Imho this issue can be closed once that PR is cleaned up, merged and we have a new release of FOS HttpCache.

**Comment by Toflar** [comment]
The PR has already been merged. Once https://packagist.org/packages/friendsofsymfony/http-cache version `2.8.1` is released, you may update your dependencies and see if it fixes your issue :)

**Comment by Toflar** [comment]
`2.9.0` has just been released. Can you guys update your dependencies and see if this solves the issue? We can close this one then :)

**Comment by MarkejN** [comment]
Sorry for the delay, I updated and tested it successfully and it solved the issue. Thanks for the effort!

**Comment by Toflar** [comment]
Thanks for the feedback :)
