### ISSUE TITLE
SQL Error id, pid NULL on theme import

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#958]
**Affected version(s)**
4.8.5
**Description**  
I have two 4.8.5 Contao installations. If i exported the theme from one installation, and imported the theme in the other I get the following error:
`An exception occurred while executing 'INSERT INTO tl_image_size (id, pid, tstamp, name, cssClass, densities, sizes, width, height, resizeMode, zoom, skipIfDimensionsMatch, formats) VALUES (NULL, NULL, '1573488461', 'Galerie', '', '1x, 1.5x, 2x', '', '528', '396', 'crop', '100', '1', '')': SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'pid' cannot be null`
I get the same error with the tl_style_sheets table.
**How to reproduce**

1. Create theme with stylesheets and images sizes
2. Import this theme in another installation

**Comment by ausi** [comment]
I was not able to reproduce this issue.

Please turn on the debug mode and add `dump($arrMapper);` to line 455 in the file *vendor/contao/core-bundle/src/Resources/contao/classes/Theme.php*
After importing the theme then you should see a dump of the mapper data.

**Comment by theDyingMountain** [comment]
Hm I also was not able to reproduce the issue now. Maybe there are some database issues on the server that causes the issue some days ago?

**Comment by ReneLuecking** [comment]
For all those who also encounter it, like me: I've found the problem and the solution.

The error only occurs if MySQL 8 is used and the theme import is done within the first 24 hours after installing Contao. The reason is that MySQL has added the setting [`information_schema_stats_expiry`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_information_schema_stats_expiry) in version 8. This setting specifies how long the information from `SHOW TABLE STATUS` is cached. The default value is 86400 seconds (24 hours). `SHOW TABLE STATUS` is used during theme import to determine the next auto increment id (`Database::getNextId()`). On a fresh Contao installation, this should be the 1. But: the information from `SHOW TABLE STATUS` is already cached by MySQL when creating a table and it sets the initial value for the id to null. Exactly this null value appears in the error message. Only after 24 hours the value is no longer null. Therefore the problem was not reproducible a few days later.

The solution is simply to set `information_schema_stats_expiry` to 0. This deactivates the cache. If desired, Contao could set this for the current database session before each call of `SHOW TABLE STATUS`.

**Comment by m-vo** [comment]
> By default, MySQL retrieves cached values for those columns from the mysql.index_stats and mysql.table_stats dictionary tables when the columns are queried, which is more efficient than retrieving statistics directly from the storage engine. If cached statistics are not available or have expired, MySQL retrieves the latest statistics from the storage engine and caches them in the mysql.index_stats and mysql.table_stats dictionary tables. Subsequent queries retrieve the cached statistics until the cached statistics expire. 

> To update cached values at any time for a given table, use ANALYZE TABLE.
> To always retrieve the latest statistics directly from the storage engine and bypass cached values, set information_schema_stats_expiry to 0.

It really seems necessary to do so. What a weird API.

**Comment by leofeyer** [comment]
We are using `SHOW TABLE STATUS` in the `Database::getSizeOf()` and `Database::getNextId()` methods. @contao/developers Maybe there is another (better) way to retrieve the data?

**Comment by ausi** [comment]
Setting `information_schema_stats_expiry` to `0` before using `SHOW TABLE STATUS` seems to be the correct solution IMO.

**Comment by leofeyer** [comment]
What about the following alternative queries?

* `SELECT SUM(DATA_LENGTH + INDEX_LENGTH) AS size FROM information_schema.TABLES WHERE TABLE_SCHEMA='contao4' AND TABLE_NAME='tl_log'`
* `SELECT AUTO_INCREMENT as next_id FROM information_schema.TABLES WHERE TABLE_SCHEMA='contao4' AND TABLE_NAME='tl_log'`

@ReneLuecking Are these using the cached data as well?

**Comment by m-vo** [comment]
As `information_schema.tables` is a view and not a direct query to the storage engine (see https://dev.mysql.com/doc/refman/8.0/en/information-schema-optimization.html), I don't think we can rely on it being fresh on every read. 

Imo @ausi's proposal is the right way to do it. The MySQL docs specifically says: `To always retrieve the latest statistics directly from the storage engine and bypass cached values, set information_schema_stats_expiry to 0`

**Comment by ausi** [comment]
We should verify that setting the expiration to 0 doesn’t have an effect on queries like `SELECT * FROM ...` (it has to retrieve which columns the table has). If so, we should probably use the `ANALYZE TABLE` approach instead.

**Comment by leofeyer** [comment]
I ran a couple of tests and I can confirm that the following works in MySQL 8.0.19:

```php
if ($this->resConnection->getDatabasePlatform() instanceof MySQL80Platform) {
    $this->resConnection->executeQuery('SET @@SESSION.information_schema_stats_expiry = 0');
}

$statement = $this->resConnection->executeQuery('SHOW TABLE STATUS LIKE ' . $this->resConnection->quote($strTable));
$status = $statement->fetch(\PDO::FETCH_ASSOC);
```

@ReneLuecking @theDyingMountain Can you please check if the code solves your problem?

**Comment by leofeyer** [comment]
@ausi @m-vo Is there a better way to detect this "feature" than to check the database platform? Because once there is a `MySQL81Platform` class or MariaDB adopts the feature, the current check will break.

**Comment by m-vo** [comment]
I think we could probably check if the `information_schema_stats_expiry` system variable exists by checking if `SHOW SESSION VARIABLES LIKE 'information_schema_stats_expiry'` returns a result.

As soon as the variable exists it imo won't hurt to set it to `0`.

**Comment by leofeyer** [comment]
But that would be one additional MySQL query per every call (compared to just a PHP `instanceof` check). Not sure if that is more efficient.

**Comment by m-vo** [comment]
Hmm, depends a bit on how common this variable is - if nearly everyone uses it we could also set it every time (and catch the error). Not sure if this is a good practice (and currently it's still rather niche I guess).

What about caching it? This would then suddenly fail if the hoster updates the database version.

Edit: For me it takes (only?) ~0.46ms to execute the query.

**Comment by ausi** [comment]
> we could also set it every time (and catch the error).

I think this is the way to go. Triggering an `Unknown system variable` error should be extremely fast, especially compared to a rather costly `SHOW TABLE STATUS` query.

**Comment by aschempp** [comment]
I wonder if there's a simpler solution to this? At least for `Database::getNextId()`, wouldn't a `SELECT MAX(id)+1 AS next_id FROM table` work as well? 

`Database::getSizeOf()` seems pretty irrelevant as it's only used in the maintenance module, and I  would be fine with this being cached for 24hrs…

**Comment by ausi** [comment]
> At least for `Database::getNextId()`, wouldn't a `SELECT MAX(id)+1 AS next_id FROM table` work as well?

I don’t think so. If the last row gets deleted, `MAX(id)+1` is no longer the same as the auto increment value.

Do we use `Database::getNextId()` in any performance relevant cases?

**Comment by aschempp** [comment]
> I don’t think so. If the last row gets deleted, MAX(id)+1 is no longer the same as the auto increment value.

I know. But adding a row with that value is still valid.

> Do we use Database::getNextId() in any performance relevant cases?

Nope, only for the theme export.

**Comment by ausi** [comment]
> I know. But adding a row with that value is still valid.

But it would “reuse” old IDs which could lead to unwanted side effects.

> > Do we use Database::getNextId() in any performance relevant cases?
> 
> Nope, only for the theme export.

Then we should go with the `information_schema_stats_expiry` approach I think.
