### ISSUE TITLE
Wrong request in fragment controller on PageError401

### ISSUE THREAD

**Issue by richardhj** [contao/contao#966]
**Affected version(s)**
4.8.*

**Description**  
When any module is placed on an Error 401 page, the wrong request object is passed.
`$request->getRequestUrl()` returns the URL of the `_contao/login` route instead of the actual URL of the page.
Example code: https://github.com/richardhj/contao-email-token-login/blob/9825029eb89f50b411ec793eaffe00238e70c190/src/Module/TokenLogin.php#L166

```php
// Returns "_contao/login"
dump($request->getRequestUri());
```

**How to reproduce**  

1. Place any content element or module on a page with the type PageError401.
2. Hook into the module:

```php
$requestStack = Controller::getContainer()->get('request_stack');

// Returns "_contao/login"
dump($requestStack->getCurrentRequest()->getRequestUri());

// Returns "test.html"
dump($requestStack->getMasterRequest()->getRequestUri());

// Returns "test.html"
dump(Environment::get('request'));
```
3. Now place a module with fragment controller on the page 401.
```php
// Returns "_contao/login"
dump($request->getRequestUri());
// But should be "test.html"
```

**Comment by richardhj** [comment]
Duplicate of #558 🙈

**Comment by leofeyer** [comment]
I have marked the original issue as "up for discussion".
