### ISSUE TITLE
Login's redirectBack not working after successful 2FA authentication

### ISSUE THREAD

**Issue by richardhj** [contao/contao#967]
**Affected version(s)**
4.8.*

**Description**  
When the login form is placed on a PageError401 page, the user stays on the error page instead of getting directed to the home page. The login form uses "redirectBack" configuration.

**How to reproduce**  
1. Enable 2FA for one member
2. Enable `redirectBack` for the login module
3. Place the login form on a PageError401
4. Log in with the member, authenticate with TOTP

<img width="338" alt="Screen Shot 2019-11-13 at 13 20 16" src="https://user-images.githubusercontent.com/1284725/68732902-644d7100-0618-11ea-8f71-79744c50a6ab.png">

**Expected behavior:** 
Redirect on the home page.

**Actual behavior:**
The user stays on the PageError401 page.

Without 2FA, the user gets redirected to the home page. With 2FA, the user stays on the 401 page after they is fully authenticated.

____

This does not work, because `$_POST` is always `[]` in my case.
https://github.com/contao/contao/blob/07759ec47a22f09265166d803c512f9b15669294/core-bundle/src/Resources/contao/modules/ModuleLogin.php#L62

____

When the user is unauthenticated:
```
      <input type="hidden" name="_target_path" value="https://example.org/">
```

When the user has 2FA in progress:
```
      <input type="hidden" name="_target_path" value="https://example.org/401-unauthenticated">
```
In the second case, the `_target_path` should stay the same.

____

May be related to #966 ?

**Comment by fritzmg** [comment]
If you place a login form on the 401 page, you have to disable redirect back, since you already are on the correct URL.

**Comment by richardhj** [comment]
> If you place a login form on the 401 page, you have to disable redirect back, since you already are on the correct URL.

This does not influence the behavior, since the error occured in the first place and I enabled "redirectBack" afterwards.

**Comment by leofeyer** [comment]
I do not consider it good practice to have a login form on an error page. You should enable forwarding to the actual login page instead.

**Comment by aschempp** [comment]
Pretty sure this is fixed by https://github.com/contao/contao/pull/1178 😎

**Comment by Toflar** [comment]
Now that this is merged, can you check again @richardhj ?

**Comment by richardhj** [comment]
Fixed :+1:
