### ISSUE TITLE
(Kopie) String beim Kopieren von Bildgrößen Mediaqueries entfernen

### ISSUE THREAD

**Issue by theDyingMountain** [contao/contao#969]
**Description**  
Aktuell wird beim Kopieren einer Bildgrößenquery immer der (Kopie) String angehangen. Dieser ist unnötig und lästig zu entfernen, da er nicht sowieso nicht in der Query enthalten sein darf.

**Comment by leofeyer** [comment]
Welche Contao-Version ist betroffen?

**Comment by theDyingMountain** [comment]
4.8.5

**Comment by leofeyer** [comment]
Ich bin gegen diese Änderung, weil man dann beim Kopieren mehrerer Datensätze nicht mehr erkennen kann, welches der originale Datensatz ist und welcher der kopierte.

@contao/developers WDYT?

**Comment by Toflar** [comment]
Es geht um das einzelne Item (den Mediaquery). Nicht um den Namen bei der Grösse selbst. Der ist tatsächlich nutzlos.

**Comment by leofeyer** [comment]
Nein, es geht um die Bildgrößenquerys, also `tl_image_size_items`. Dort gibt es kein `name`-Feld, daher wird das "(Kopie)" an das Media-Query angehängt.

Trotzdem bleibt das die einzige Möglichkeit, um Original und Kopie unterscheiden zu können.

**Comment by Toflar** [comment]
Ja, sag ich ja. Um das hier: https://github.com/contao/contao/blob/master/core-bundle/src/Resources/contao/dca/tl_image_size_item.php#L21

**Comment by leofeyer** [comment]
Ja. 👍

**Comment by Toflar** [comment]
Gut, dann bleib ich dabei: Wegen mir kann's weg :)

**Comment by leofeyer** [comment]
Wie unterscheidest Du dann zukünftig, welches Element das Original ist und welches die Kopie?

**Comment by Toflar** [comment]
Der Fall tritt gar nie ein. Wenn ich etwas dupliziere will ich dieselben Einstellungen für einen anderen Mediaquery. D.h. ich dupliziere und muss dann den Mediaquery anpassen und dabei jedes Mal das "(Kopie)" löschen. Ich denke das war die Intention hinter diesem Ticket. Also ein Mediaquery ist eh immer invalid mit "(Kopie)" drin.

**Comment by leofeyer** [comment]
Das ergibt Sinn. 👍

**Comment by theDyingMountain** [comment]
@Toflar: Genau richtig, dass war die Intention hinter dem Ticket 😉

**Comment by leofeyer** [comment]
Siehe #1051.
