### ISSUE TITLE
Order of backend modules changed after updating system in Contao Manager

### ISSUE THREAD

**Issue by juju2** [contao/contao#970]
**Affected version(s)**
4.4.45 (at least)

**Description**  
After e.g. uninstalling a backend module or updating an extension via Contao Manager the order of backend modules underneath the headline "Content" has changed in the Contao backend menu. 

The Events for example by default are at position 3 (after Articles and News) and after making the described changes the order changes to Articles, Events, News, ...

I testet making a downgrade to Contao 4.4.44: After downgrading the menu is put back to the normal (default) order. After uninstalling another module the order has changed again.

**How to reproduce**  
- Make fresh install of Contao 4.4.45
- Log into contao backend and check order of modules underneath "Content"
- Uninstall a module (e.g. FAQ) via Contao Manager
- check the backend order again and "Events" should have moved to the 2nd position

**Comment by leofeyer** [comment]
The order of back end menu items is not predictable. It depends on which extensions are installed, how the manager determines the loading order and how those extensions add menu items (prepend, inject, append).

**Comment by fritzmg** [comment]
> The order of back end menu items is not predictable.

It should be in a vanilla Contao installation though.

**Comment by aschempp** [comment]
> > The order of back end menu items is not predictable.
> 
> It should be in a vanilla Contao installation though.

It is, but he was adding and removing extensions, therefore affecting the *vanilla-ness*
