### ISSUE TITLE
FE-Module: Suche nach erweitern um ID

### ISSUE THREAD

**Issue by zonky2** [contao/contao#974]
FE-Module: Suche nach erweitern um ID 

Insbesondere wenn man mit Insert-Tags arbeitet und wissen will was `{{insert_modul::42}}` war, ist manchmal eine langwierige Suche angesagt (es sei den, man hat die Listenausgabe gepimt und gibt die ID mit aus)

Eine Erweiterung des Sucheintrages nach ID würde das sehr erleichtern.

**Comment by Tastaturberuf** [comment]
@leofeyer add Label `easy pick`
