### ISSUE TITLE
Symfony 5 is required for Monolog 2 support

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#978]
We have transitionally fixed the "Symfony 5 is required for Monolog 2 support" problem by adding a conflict in https://github.com/contao/conflicts/commit/99f14df05740a7d0818735e1dead739a59af73c6. Now we should discuss how and when to remove it again, since we want to use Monolog 2 with Symfony 5 some day.

**Comment by leofeyer** [comment]
See https://github.com/symfony/monolog-bundle/issues/330

**Comment by leofeyer** [comment]
As discussed in Mumble on November 28th, we have to require `"monolog/monolog": "^1.22"` in Contao 4.4 to fix this.

**Comment by aschempp** [comment]
This has been fixed in Symfony 3.4 in https://github.com/symfony/symfony/pull/32469 as soon as the next version is released.

**Comment by leofeyer** [comment]
Symfony 3.4.36 has been released two days ago. So do we not change anything on our end?

**Comment by leofeyer** [comment]
@contao/developers Symfony 3.4.36 has been released two days ago. So do we not change anything on our end?

**Comment by Toflar** [comment]
I don't know if requiring at least 3.4.36 will help. It will just downgrade your Contao version if you don't pin it at a certain hotfix version :(

**Comment by ausi** [comment]
We could add `< 3.4.36` to `contao/conflicts` but I’m not sure if this is a good idea...

**Comment by leofeyer** [comment]
I don't think so.
