### ISSUE TITLE
Contao news / Sicherheitshinweise zu Contao-Themes / Link Free Themes Month not active

### ISSUE THREAD

**Issue by Ernestopheles** [contao/contao#984]
**Affected version(s)**

**Description**  

**How to reproduce**  
open URL [https://contao.org/de/blog-leser/items/im-juli-ist-contao-free-themes-month.html](url)

**Comment by m-vo** [comment]
What is even the question?

**Comment by Ernestopheles** [comment]
Link [Free Themes Month](url) not active

**Comment by xchs** [comment]
This belongs to the [contao/website](https://github.com/contao/website) repo.

**Comment by Ernestopheles** [comment]
ok, thanks
