### ISSUE TITLE
[PHP Fatal Error] Argument passed to FragmentRegistry::get() must be of the type string, object given

### ISSUE THREAD

**Issue by clemensfreitag-dev** [contao/contao#993]
**Affected version(s)**

Contao: Contao 4.8.5 installed with Contao Manager
PHP: `7.3.11-1+0~20191026.48+debian9~1.gbpf71ca0`

**Description**  

After a clean installation of Contao and some configurations on the backend, I observe the following PHP fatal error in the Apache logs on all most every frontend access: 

`[php7:error] [pid 26793] [client [CROP]] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Argument 1 passed to Contao\\CoreBundle\\Fragment\\FragmentRegistry::get() must be of the type string, object given, called in [CROP]/contao4-dev/vendor/contao/core-bundle/src/HttpKernel/ControllerResolver.php on line 43 in [CROP]/contao4-dev/vendor/contao/core-bundle/src/Fragment/FragmentRegistry.php:54\nStack trace:\n#0 [CROP]/contao4-dev/vendor/contao/core-bundle/src/HttpKernel/ControllerResolver.php(43): Contao\\CoreBundle\\Fragment\\FragmentRegistry->get(Object(Closure))\n#1 [CROP]/contao4-dev/vendor/symfony/http-kernel/HttpKernel.php(134): Contao\\CoreBundle\\HttpKernel\\ControllerResolver->getController(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 [CROP]/contao4-dev/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)\n# in [CROP]/contao4-dev/vendor/contao/core-bundle/src/Fragment/FragmentRegistry.php on line 54, referer: [CROP]/home.html
`
(host-related data replaced with [CROP])

The same issue is also reported here but I didn't identified any bug related on GitHub so far: 
https://community.contao.org/de/showthread.php?75959-Fehler-nach-Update-von-4-7-zu-4-8-3

Briefly looking into the source of the mentioned ControllerResolver.php: 

```
    public function getController(Request $request)
    {
        if ($request->attributes->has('_controller')) {
            $fragmentConfig = $this->registry->get($request->attributes->get('_controller'));
```
`$request->attributes->get('_controller')` seems to return an object instead of a string what the called get() would expect. 

**How to reproduce**  

I assume it's not related to my server configuration, so I assume it's reproducable with the mentioned Contao+PHP setup.

**Comment by clemensfreitag-dev** [comment]
I saw this issue first with Contao 4.8.4, however also observed it after update to Contao 4.8.5 with Contao Manager

**Comment by aschempp** [comment]
Interesting! Maybe the `_controller` attribute can be an object if a `ControllerReference` is used in a subrequest. Did you install any extensions that could be related?

**Comment by clemensfreitag-dev** [comment]
Actually this was a good hint! Besides `contao/manager-bundle` I installed:

```
terminal42/notification_center
contao-bootstrap/bundle
```

I experimented a bit with contao-bootstrap but decided to not use it. I de-installed contao-bootstrap and actually the fatal error vanished. Out of curiosity, I even re-installed contao-bootstrap and modified some of the frontend module to use BS templates but wasn't able to reproduce it. 

Right now, I could only apply guesswork what happened, so I'd be ok to just close it.

**Comment by m-vo** [comment]
@dmolineus

**Comment by dmolineus** [comment]
`contao-bootstrap` doesn't use fragments, own routes nor manipulates requests/routes. So I'm not sure if it's related to the extension (or it's dependencies). 

According to https://symfony.com/doc/current/create_framework/http_kernel_controller_resolver.html the `_controller` attribute might contain other information than strings, see example:

```php
$routes->add('leap_year', new Routing\Route('/is_leap_year/{year}', [
    'year' => null,
    '_controller' => [new LeapYearController(), 'index'],
]));
```

**Comment by Ernestopheles** [comment]
I faced this problem too. Did install only the Easythemes extension. 
Contao 4.8.5

**Comment by Ernestopheles** [comment]
In an fresh installation of Contao 4.85 (full) with the Mate theme (2.3.2) freshly installed the templates can be imported without error.

**Comment by Ernestopheles** [comment]
Before that I tried a bit with deinstalling everything (Easythemes, each module from contao news to contao lists) - but that did not help.

**Comment by leofeyer** [comment]
See #1087
