### ISSUE TITLE
webp in Dateiverwaltung

### ISSUE THREAD

**Issue by BugBuster1701** [contao/contao#994]
**Affected version(s)**

in Contao 4.8.5 getestet

**Description**  

Unter PHP 7.2, webp Support in GD vorhanden und über config.yml gesetzt, da imagick auch installiert ist, aber ohne webp. Experteneinstellung zeigt auch an, das ich jpg, png und gif in webp wandeln lassen könnte.
in der Dateiverwaltung, webp Upload und Endung sind erlaubt, wird mir zwar Größe und Abmaße einer webp Datei angezeigt aber kein Vorschaubild.
![Dateiverwaltung_contao48_webp](https://user-images.githubusercontent.com/1218809/69009004-2d959480-0951-11ea-9b54-3b7ae1ed1d3b.png)

Es fehlt übrigens auch das assets image `iconWEBP.svg`, daher wird stattdessen `iconPLAIN.svg` verwendet.

**How to reproduce**  

Upload eines webp Bild in der Dateiverwaltung. ~~webp Endung für Erlaubte Upload/Download-Dateitypen vorher freischalten.~~

**Comment by xchs** [comment]
> webp Endung für Erlaubte Upload/Download-Dateitypen vorher freischalten.

Ist das nicht bereits der Fall in Contao 4.8.5? Eigentlich sollte WebP dort bereits standardmäßig erlaubt sein (siehe https://github.com/contao/contao/pull/829).

**Comment by BugBuster1701** [comment]
Aja, ich hatte mit 4.8.4 angefangen zu testen und dann erst das Update gemacht.

**Comment by leofeyer** [comment]
The missing preview image issue can be solved by adding `webp` to the list of GD images:

https://github.com/contao/contao/blob/0a2c8fa64c195a1e3482c3a9c9dfe73624ba8956/core-bundle/src/Resources/contao/library/Contao/File.php#L379-L381

@ausi Any objections? Does the GDlib handle webp images unrestrictedly?

**Comment by ausi** [comment]
> Does the GDlib handle webp images unrestrictedly?

Yes, I think so, but only if PHP was compiled with webp support. But JPEG support needs to be enabled during compilation of PHP too, so it should be fine IMO to add `webp` here.

**Comment by leofeyer** [comment]
See #1018

**Comment by BugBuster1701** [comment]
Funktioniert. Perfekt wäre dann noch ein passendes iconWEBP.svg.

**Comment by leofeyer** [comment]
Siehe #1122
