### ISSUE TITLE
Fix incompatibilities with PCRE 8.32 in Contao 4.4 LTS

### ISSUE THREAD

**Issue by plorenz-etes** [contao/contao#995]
**Affected version(s)**
Contao 4.4.*

**Description**  
There was a Merge Request #916 which fixes #886 in Contao 4.8. However, this wasn't backported to Contao 4.4 yet. We've got customers on RedHat 7.6 with this exact PCRE version who run into this problem.

**How to reproduce**  
See #886 - but for some reason, we only run into this bug using MetaModels. However, manually backporting the changes from #916 fixes the problem instantly.

**Comment by dmolineus** [comment]
How do you backport this fix to Contao 4.4? The translator was introduced in Contao 4.5. MetaModels uses https://github.com/contao-community-alliance/translator. I guess you should open the issue there.

**Comment by plorenz-etes** [comment]
@dmolineus Ah yes, you're right - sorry, this got mixed up because the BackportedTranslator class looks quite similar to Contao's Translator class. Opening an issue at contao-community-alliance/translator - sorry!

**Comment by dmolineus** [comment]
Pull requests are welcome :-)
