### ISSUE TITLE
Backend Navigation: Top-Navigation Icons verschieben sich beim Scrollen am Handy

### ISSUE THREAD

**Issue by saress** [contao/contao#997]
**Affected version(s)**
Contao 4.4.45 und Contao 4.8.5

**Description**  
Logged man sich am Handy  (in meinem Fall Samsung Galaxy S10) ins Backend ein, klickt auf das Hamburger Menü und scrolled dann bei geöffnetem Offcanvas Menü nach unten bis die Top-Navigation aus dem sichtbaren Bereich verschwindet und danach wieder retour nach oben, dann sind alle Icons der Top-Navigation nach rechts verschoben (mit Ausnahme des Contao Logos). 
Hier hilft dann nur mehr ein Reload der Seite, danach werden wieder alle Icons (Contao Logo, Hinweise, Vorschau, Profil, Abmelden & Hamburger Icon) richtig angezeigt.

**How to reproduce**  
1. Backend Login mit Handy
2. Click auf Hamburger Menü (Offcanvas Menü fährt links herein, geöffnet lassen)
3. Nach unten scrollen / wischen bis die Top-Navigation nicht mehr sichtbar ist
4. Wieder nach oben scrollen
5. Icons der Top-Navigation sind nach rechts verschoben (mit Ausnahme des Contao Logos).

Beste Grüße
Sares

**Comment by xchs** [comment]
> wischen bis die Top-Navigation nicht mehr sichtbar ist

Welchen Browser verwendest Du denn auf Deinem Smartphone? Mir ist ebenfalls aufgefallen, dass sich die mobilen Browser diesbezüglich unterschiedlich verhalten.

**Comment by saress** [comment]
Google Chrome in der aktuellsten Version.

Beste Grüße 
Saress

**Comment by saress** [comment]
Das Verhalten hat sich in der aktuellen C4.9-dev noch nicht geändert, wie ich gerade in einer Testinstallation festgestellt habe.

**Comment by ausi** [comment]
Ich kann den Fehler reproduzieren:

<img width="392" alt="Bildschirmfoto 2020-02-08 um 23 32 17" src="https://user-images.githubusercontent.com/367169/74092948-b98c0800-4acb-11ea-8dba-d25b33b7a086.png">

Das Problem ist, dass sich mit dem Öffnen der Navigation der Body verbreitert und Chrome somit in einen anderen Darstellungsmodus wechselt wodurch fixierte Elemente anders angezeigt werden.

Sollte sich mit folgendem CSS beheben lassen:

```css
@media (max-width: 991px) {
    #container {
        overflow: hidden;
    }
}
```

@saress kannst du verifizieren ob der Fix bei dir funktioniert?

Als Alternative könnten wir darauf verzichten das `#main`-Element nach rechts zu verschieben und das `#left`-Element mit einem höheren Z-Index darüber anzeigen.

**Comment by saress** [comment]
@ausi vielen Dank, hab ich gerade ausprobiert und bei mir am Handy werden die Icons nach dem Scrollen nach oben wieder an der richtigen Stelle angezeigt, scheint also zu funktionieren :-)

**Comment by leofeyer** [comment]
Siehe #1302.
