### ISSUE TITLE
Upgrade contao 3.5.2 to 4.4 LTS

### ISSUE THREAD

**Issue by baymax88** [contao/contao#998]
**Affected version(s)**
contao 4.4 LTS

**Description**  
I hope to upgrade my current site (built with contao 3.5.2).
I tried to upgrade it on my local first but not going well.
Please let me know how to upgrade it.

Thanks

**Comment by xchs** [comment]
Please refer to the [forums](https://community.contao.org/) for this kind of questions.

**Comment by contaoacademy** [comment]
https://contao-academy.de/blog/update-contao-3-auf-contao-4
